### PR TITLE
examples: add libpmem2 to remaining examples.

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1740)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1740)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1740)* status: all files reviewed, 6 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[`examples/03-read-to-persistent/server.c` line 42 at r1](https://reviewable.io/reviews/pmem/rpma/1740#-N2FYFXjCP42BNnnZUaD:-N2FYFXjCP42BNnnZUaE:bnq66yo) ([raw file](https://github.com/pmem/rpma/blob/25cbc5d9c5f01ca947c44b818d4c8b53c3ab2724/examples/03-read-to-persistent/server.c#L42)):*
> ```C
> 	int ret;
> 
> 	/* hereresources - memory region */
> ```

resources



_Code quote:_
```C
	/* hereresources - memory region */
```
___
*[`examples/04-write-to-persistent/client.c` line 289 at r1](https://reviewable.io/reviews/pmem/rpma/1740#-N2FYtVC-yhStlC2EpMm:-N2FYtVC-yhStlC2EpMn:b-q37o3i) ([raw file](https://github.com/pmem/rpma/blob/25cbc5d9c5f01ca947c44b818d4c8b53c3ab2724/examples/04-write-to-persistent/client.c#L289)):*
> ```C
> 
> err_free:
> #ifdef USE_LIBPMEM
> ```

USE_PMEM
___
*[`examples/05-flush-to-persistent/client.c` line 293 at r1](https://reviewable.io/reviews/pmem/rpma/1740#-N2FZBoh1y8chlA15oWv:-N2FZBoh1y8chlA15oWw:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/25cbc5d9c5f01ca947c44b818d4c8b53c3ab2724/examples/05-flush-to-persistent/client.c#L293)):*
> ```C
> 
> err_free:
> #ifdef USE_LIBPMEM
> ```

.
___
*[`examples/05-flush-to-persistent/server.c` line 248 at r1](https://reviewable.io/reviews/pmem/rpma/1740#-N2F_5Op4vLD5bI4HL57:-N2F_5Op4vLD5bI4HL58:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/25cbc5d9c5f01ca947c44b818d4c8b53c3ab2724/examples/05-flush-to-persistent/server.c#L248)):*
> ```C
> 
> err_free:
> #ifdef USE_LIBPMEM
> ```

.
___
*[`examples/09-flush-to-persistent-GPSPM/server.c` line 113 at r1](https://reviewable.io/reviews/pmem/rpma/1740#-N2F_X66714Q1Zcfa1Qz:-N2F_X66714Q1Zcfa1R-:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/25cbc5d9c5f01ca947c44b818d4c8b53c3ab2724/examples/09-flush-to-persistent-GPSPM/server.c#L113)):*
> ```C
> 		}
> 	}
> #endif /* USE_LIBPMEM */
> ```

.
___
*[`examples/09-flush-to-persistent-GPSPM/server.c` line 286 at r1](https://reviewable.io/reviews/pmem/rpma/1740#-N2F__q72Y_1MG-38XNS:-N2F__q72Y_1MG-38XNT:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/25cbc5d9c5f01ca947c44b818d4c8b53c3ab2724/examples/09-flush-to-persistent-GPSPM/server.c#L286)):*
> ```C
> #else
> 	(void) printf(
> 			"hereAt this point, pmem_persist(3) should be called if libpmem will be in use\n");
> ```

.

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1740)* status: all files reviewed, 14 unresolved discussions (waiting on @haichangsi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1740#-N2FdgSiDppddY86gvQq:-N2FdgSiDppddY86gvQr:b-gzsgbh) (no related file):*
@haichangsi - are we able to detect `is_pmem` in the case of libpmem2?



_Code quote (from examples/04-write-to-persistent/server.c):_
```C
		/* pmem is expected */
		if (!is_pmem) {
			(void) fprintf(stderr, "%s is not an actual PMEM\n",
					pmem_path);
			(void) pmem_unmap(mr_ptr, mr_size);
			return -1;
		}
```

___
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1740#-N2Fiz506K1hkImxg1I0:-N2Fiz519iTD5hoVxg51:b-9jfhu1) (no related file):*
How(when) do we set `is_pmem` in the case of libpmem2?

___
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1740#-N2FjhSD2OHmpb4aSsGd:-N2FjhSD2OHmpb4aSsGe:bhegmxm) (no related file):*
would it be better to split this PR into several - one per example?

___
___
*[`examples/03-read-to-persistent/server.c` line 43 at r1](https://reviewable.io/reviews/pmem/rpma/1740#-N2FfJRt0T1yla6rZwNo:-N2FfJRu4W6ZNTp0lX2E:b-796vdn) ([raw file](https://github.com/pmem/rpma/blob/25cbc5d9c5f01ca947c44b818d4c8b53c3ab2724/examples/03-read-to-persistent/server.c#L43)):*
> ```C
> 
> 	/* hereresources - memory region */
> 	struct example_mem mem;
> ```

If it does not work let unify example_mem struct:
struct example_mem {
	/* memory buffer */
	char *mr_ptr;
	/* size of the mapped persistent memory */
	size_t mr_size;
	size_t data_offset;
	int is_pmem;
	persist_fn persist;

#ifdef USE_LIBPMEM2
	/* libpmem2 structure used for mapping PMem */
	struct pmem2_map *map;
#else
	/* let's keep the same structure for both pmem and pmem2 */
	void *unused;
#endif
};



_Suggestion:_
```C
	struct example_mem mem = {NULL, 0, 0, 0, NULL};
```
___
*[`examples/03-read-to-persistent/server.c` line 56 at r1](https://reviewable.io/reviews/pmem/rpma/1740#-N2Fh1X3AAXoRsyVUi5q:-N2Fh1X3AAXoRsyVUi5r:bwut3yq) ([raw file](https://github.com/pmem/rpma/blob/25cbc5d9c5f01ca947c44b818d4c8b53c3ab2724/examples/03-read-to-persistent/server.c#L56)):*
> ```C
> 		pmem_path = argv[3];
> 
> 		ret = client_pmem_map_file(pmem_path, argc, &mem);
> ```

What is the purpose to pass `argc` to `client_pmem_map_file`?



_Suggestion:_
```C
		ret = client_pmem_map_file(argv[3], &mem);
```
___
*[`examples/03-read-to-persistent/server.c` line 58 at r1](https://reviewable.io/reviews/pmem/rpma/1740#-N2Fer_z0sOa9TojL31h:-N2Fer_z0sOa9TojL31i:bx7nusy) ([raw file](https://github.com/pmem/rpma/blob/25cbc5d9c5f01ca947c44b818d4c8b53c3ab2724/examples/03-read-to-persistent/server.c#L58)):*
> ```C
> 		ret = client_pmem_map_file(pmem_path, argc, &mem);
> 		if (ret)
> 			goto err_free;
> ```

`client_pmem_map_file` shall clean up by itself in case of any failure.



_Suggestion:_
```C
		if (ret)
			return -1;
```
___
*[`examples/03-read-to-persistent/server.c` line 61 at r1](https://reviewable.io/reviews/pmem/rpma/1740#-N2FhqU-8cQYv6WIoJ9b:-N2FhqU-8cQYv6WIoJ9c:b-baagi8) ([raw file](https://github.com/pmem/rpma/blob/25cbc5d9c5f01ca947c44b818d4c8b53c3ab2724/examples/03-read-to-persistent/server.c#L61)):*
> ```C
> 
> 		/*
> 		 * At the beginning of the persistent memory, a signature is
> ```

Would it be better to move `signature` handling to yet another common `common_pmem_signature_check` function? 



_Code quote:_
```C
		/*
		 * At the beginning of the persistent memory, a signature is
		 * stored which marks its content as valid. So the length
		 * of the mapped memory has to be at least of the length of
		 * the signature to convey any meaningful content and be usable
		 * as a persistent store.
		 */
```
___
*[`examples/05-flush-to-persistent/CMakeLists.txt` line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1740#-N2Fks9M8NV2ENKy4w1a:-N2Fks9M8NV2ENKy4w1b:bboo54w) ([raw file](https://github.com/pmem/rpma/blob/25cbc5d9c5f01ca947c44b818d4c8b53c3ab2724/examples/05-flush-to-persistent/CMakeLists.txt#L39)):*
> ```CMake
> link_directories(${LIBRPMA_LIBRARY_DIRS})
> 
> function(add_example name)
> ```

shall this be moved to some common CMakeFile



_Code quote:_
```CMake
function(add_example name)
```

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1740)* status: all files reviewed, 14 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[`examples/03-read-to-persistent/CMakeLists.txt` line 59 at r1](https://reviewable.io/reviews/pmem/rpma/1740#-N2Pz_UN9BV7OaUkHVWt:-N2Pz_UO6otgQiwGdrXU:undefined) ([raw file](https://github.com/pmem/rpma/blob/25cbc5d9c5f01ca947c44b818d4c8b53c3ab2724/examples/03-read-to-persistent/CMakeLists.txt#L59)):*
> ```CMake
> 		target_compile_definitions(${name}
> 			PRIVATE USE_LIBPMEM2)
> 	endif()
> ```





_Suggestion:_
```CMake
	elseif(LIBPMEM_FOUND)
```
___
*[`examples/03-read-to-persistent/server.c` line 51 at r1](https://reviewable.io/reviews/pmem/rpma/1740#-N2Pzwbq8KRsF8-E0dQb:-N2Pzwbq8KRsF8-E0dQc:b-sx84ma) ([raw file](https://github.com/pmem/rpma/blob/25cbc5d9c5f01ca947c44b818d4c8b53c3ab2724/examples/03-read-to-persistent/server.c#L51)):*
> ```C
> 
> #ifdef USE_PMEM
> 	char *pmem_path = NULL;
> ```

obsolete

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1740)* status: all files reviewed, 12 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)

___
*[`examples/03-read-to-persistent/CMakeLists.txt` line 59 at r1](https://reviewable.io/reviews/pmem/rpma/1740#-N2Pz_UN9BV7OaUkHVWt:-N2QlwJq2w5HDAoDo13q:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/25cbc5d9c5f01ca947c44b818d4c8b53c3ab2724/examples/03-read-to-persistent/CMakeLists.txt#L59)):*
> ```CMake
> 		target_compile_definitions(${name}
> 			PRIVATE USE_LIBPMEM2)
> 	endif()
> ```

Done.
___
*[`examples/03-read-to-persistent/server.c` line 42 at r1](https://reviewable.io/reviews/pmem/rpma/1740#-N2FYFXjCP42BNnnZUaD:-N2Qlvw4Dz9VNV2VSnAP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/25cbc5d9c5f01ca947c44b818d4c8b53c3ab2724/examples/03-read-to-persistent/server.c#L42)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

resources
</blockquote></details>

Done.
___
*[`examples/03-read-to-persistent/server.c` line 43 at r1](https://reviewable.io/reviews/pmem/rpma/1740#-N2FfJRt0T1yla6rZwNo:-N2Qly7J0CPxp5BIwFzj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/25cbc5d9c5f01ca947c44b818d4c8b53c3ab2724/examples/03-read-to-persistent/server.c#L43)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

If it does not work let unify example_mem struct:
struct example_mem {
	/* memory buffer */
	char *mr_ptr;
	/* size of the mapped persistent memory */
	size_t mr_size;
	size_t data_offset;
	int is_pmem;
	persist_fn persist;

#ifdef USE_LIBPMEM2
	/* libpmem2 structure used for mapping PMem */
	struct pmem2_map *map;
#else
	/* let's keep the same structure for both pmem and pmem2 */
	void *unused;
#endif
};
</blockquote></details>

Done.
___
*[`examples/03-read-to-persistent/server.c` line 51 at r1](https://reviewable.io/reviews/pmem/rpma/1740#-N2Pzwbq8KRsF8-E0dQb:-N2QmWIt-XLcQzLE0MRv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/25cbc5d9c5f01ca947c44b818d4c8b53c3ab2724/examples/03-read-to-persistent/server.c#L51)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

obsolete
</blockquote></details>

Done.

**Review by haichangsi — COMMENTED** [review]
This pr should be closed.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1740#-:-N2QpDzKAHnUz24Dp_JM:b3e4w7l)* status: all files reviewed, 12 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)

**Review by grom72 — COMMENTED** [review]
If you want to close it just close it.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1740#-:-N2QvVfo6i8oufgZzV4V:b-yi2pfk)* status: all files reviewed, 7 unresolved discussions (waiting on @haichangsi, @ldorau, and @osalyk)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1740)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1740#-N2FjhSD2OHmpb4aSsGd:-N2kQV2i7R_RLH3hyQpZ:b77tnv9) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

would it be better to split this PR into several - one per example?
</blockquote></details>

Yes, so let's close this PR

---

**Pull request closed without merging**
