### PR TITLE
test: fix helgrind suppressions

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1045)

### CODE REVIEW

**Comment by ldorau** [comment]
See: https://app.circleci.com/pipelines/github/ldorau/rpma/424/workflows/e4036e57-00b1-4b1b-bba7-b114d3ed9795/jobs/436

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1045)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tests/helgrind.supp, line 150 at r1](https://reviewable.io/reviews/pmem/rpma/1045#-M_0fOuHEGk8lRNXAm7Z:-M_0fOuHEGk8lRNXAm7_:bx4m086) ([raw file](https://github.com/pmem/rpma/blob/b160e8fc34c16e4128d2e5bb27c44c831aca35a8/tests/helgrind.supp#L150)):*
> ```
> # - rpma_utils_get_ibv_context
> # - rpma_ep_shutdown
> # - rpma_info_new (ucma_set_af_ib_support)
> ```

Where this one comes from?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1045)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tests/helgrind.supp, line 150 at r1](https://reviewable.io/reviews/pmem/rpma/1045#-M_0fOuHEGk8lRNXAm7Z:-M_0htQ-BCT0n40C48OW:bj9iz38) ([raw file](https://github.com/pmem/rpma/blob/b160e8fc34c16e4128d2e5bb27c44c831aca35a8/tests/helgrind.supp#L150)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Where this one comes from?
</blockquote></details>

From the one removed above:

```
{
   Possible data race during write of size 8
   Helgrind:Race
   fun:idm_clear
   fun:ucma_remove_id
   fun:ucma_free_id
   fun:rdma_destroy_id
   fun:ucma_set_af_ib_support
   fun:ucma_init
   fun:ucma_init
   fun:rdma_getaddrinfo
   fun:rpma_info_new
   fun:rpma_utils_get_ibv_context
   ...
}
```

**Review by janekmi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1045#-:-M_12_6U5Xu2VYWpAtsb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
