### PR TITLE
test: add missing suppressions for drd and helgrind

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1835)

### CODE REVIEW

**Comment by ldorau** [comment]
See:
https://app.circleci.com/pipelines/github/ldorau/rpma/4242/workflows/87e824cc-86f6-47d8-ba6a-276219be86c8/jobs/4325
https://app.circleci.com/pipelines/github/ldorau/rpma/4243/workflows/278c37ad-bd50-4c7d-a930-e131e77f8833/jobs/4326

**Review by grom72 — COMMENTED** [review]
Can you add OS info to every new suppression?

> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1835#-:-N4WhgnuEnykmsB43fh6:buq3097)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — COMMENTED** [review]
Yes, done.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1835#-:-N4WlRWoAzv-O-vHrHD4:b60r506)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1835#-:-N4WoXzE7roX1QnvoqaW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1835)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
