### PR TITLE
common: 1.1.0-rc1 release

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/2020)

### CODE REVIEW

**Review by osalyk — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2020)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2020)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`CHANGELOG.md` line 8 at r1](https://reviewable.io/reviews/pmem/rpma/2020#-NBI-b04815FTo8SicQl:-NBI-b04815FTo8SicQm:b-g6bpyy) ([raw file](https://github.com/pmem/rpma/blob/7f2429f0f43658190c8d974b52a53999eda94dd8/CHANGELOG.md#L8)):*
> ```Markdown
> and this project adheres to [Semantic Versioning](https://semver.org/spec/v2.0.0.html).
> 
> ## [Unreleased]
> ```

Do we need this bullet in the release version?



_Code quote:_
```Markdown
## [Unreleased]
```

**Review by osalyk — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2020#-:-NBI-lzl45ayTMbwSM_s:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
:goat: 

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2020#-:-NBI-muh2cjFQjkx51B8:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2020)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`CHANGELOG.md` line 8 at r1](https://reviewable.io/reviews/pmem/rpma/2020#-NBI-b04815FTo8SicQl:-NBI-zNo6KFrZDz34el7:bgezvhn) ([raw file](https://github.com/pmem/rpma/blob/7f2429f0f43658190c8d974b52a53999eda94dd8/CHANGELOG.md#L8)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Do we need this bullet in the release version?
</blockquote></details>

Yes, it should be present always.

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2020#-:-NBIE6B9CE6LXFxMfDwo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
