### PR TITLE
tools: print a message if the series does not have the required keys

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1137)

### CODE REVIEW

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1137#-:-Me9LWv4731G1-UD2NMn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1137)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/lib/Figure.py, line 109 at r1](https://reviewable.io/reviews/pmem/rpma/1137#-Me9xPaz29Fwi_HU6YkF:-Me9xPaz29Fwi_HU6YkG:bk3cxb3) ([raw file](https://github.com/pmem/rpma/blob/576e66bc36568ea87fd28508cb0ed3b6df434fa2/tools/perf/lib/Figure.py#L109)):*
> ```Python
>                     axis = 'y'
>                     wrong_key = self.y
>                 print(f'Value ' + str(axis) + '=' + str(wrong_key) + ' are not in the ' + str(keys))
> ```

```python
# global
SKIP_NO_AXIS_MSG = "SKIP: Axis '{}' is not provided by the series of id={}. Available keys are: {}"

if self.x not in keys:
    print(SKIP_NO_AXIS_MSG.format(self.x, series[id], str(keys))
    continue
elif self.y not in keys:
    print(SKIP_NO_AXIS_MSG.format(self.y, series[id], str(keys))
    continue

```

Note:
- the first level if-statement is not needed
- f-strings does not need `+` operators. But it seems we can not use f-strings since it requires too new python version which is not available in all distributions we want to support.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1137)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[tools/perf/lib/Figure.py, line 109 at r1](https://reviewable.io/reviews/pmem/rpma/1137#-Me9xPaz29Fwi_HU6YkF:-MeA4FZQBvOVmwyY_k6o:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/576e66bc36568ea87fd28508cb0ed3b6df434fa2/tools/perf/lib/Figure.py#L109)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```python
# global
SKIP_NO_AXIS_MSG = "SKIP: Axis '{}' is not provided by the series of id={}. Available keys are: {}"

if self.x not in keys:
    print(SKIP_NO_AXIS_MSG.format(self.x, series[id], str(keys))
    continue
elif self.y not in keys:
    print(SKIP_NO_AXIS_MSG.format(self.y, series[id], str(keys))
    continue

```

Note:
- the first level if-statement is not needed
- f-strings does not need `+` operators. But it seems we can not use f-strings since it requires too new python version which is not available in all distributions we want to support.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1137)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1137)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1137)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/lib/Figure.py, line 109 at r1](https://reviewable.io/reviews/pmem/rpma/1137#-Me9xPaz29Fwi_HU6YkF:-MfEAxfQ-biWH5yaFJ3n:b-t7sx0) ([raw file](https://github.com/pmem/rpma/blob/576e66bc36568ea87fd28508cb0ed3b6df434fa2/tools/perf/lib/Figure.py#L109)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

By `# global` I mean it has to be global. :grin: 
Put it somewhere directly within the Figure class or even outside the class.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1137)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[tools/perf/lib/Figure.py, line 109 at r1](https://reviewable.io/reviews/pmem/rpma/1137#-Me9xPaz29Fwi_HU6YkF:-MfED-FHAb6xYbyjIDGR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/576e66bc36568ea87fd28508cb0ed3b6df434fa2/tools/perf/lib/Figure.py#L109)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

By `# global` I mean it has to be global. :grin: 
Put it somewhere directly within the Figure class or even outside the class.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1137#-:-MfEDoCB6DpsJHP_cXX9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
