### PR TITLE
common: generate documentation in the 'manpages' directory

### PR DESCRIPTION
**Pull request by ldorau**
This patch is the second part of the change in #536.

This PR has to be merged just after having merged #536.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/538)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/538#-:-MIchCRxC2tA6enkNhPm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/538#-:-MId2FrO8oWp6_vUWofu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by ldorau** [comment]
Postponed

**Comment by ldorau** [comment]
@janekmi @grom72 @osalyk Reopened, directory changed to 'manpages' like in PMDK.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/538#-:-MIrueElBKmUYe7XKPG1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
