### PR TITLE
common: add common

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/4)

### CODE REVIEW

**Comment by ldorau** [comment]
Please rebase to the current #1

**Comment by osalyk** [comment]
> Please rebase to the current #1

Done.

**Comment by ldorau** [comment]
@osalyk please rebase on current master, #1 has been merged

**Comment by ldorau** [comment]
> util.c is missing
> 

`util.c` and `out.c` are not required yet - try to build my branch: https://github.com/ldorau/rpma/tree/test-add-rpma_config-unittest

**Pull request merged**
