### PR TITLE
tools: perf: reorg Figure.py and flat.py

### PR DESCRIPTION
**Pull request by janekmi**
Admitting, the flat.py code is relevant only for figures both are merged into a single module. Simplifying both at the same time.

Requires:

- [x] #1358 
- [x] #1361

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1364)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1364)* status: 1 of 12 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1364)* status: 2 of 12 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 9 of 12 files at r1, 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1364#-:-MpkX6XJ6yi5do9yR6qE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> Reviewed 9 of 12 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1364)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1364#-:-Mpk_VtT1sFPyF-sHwWN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
