### PR TITLE
tools: move DDIO's steps out of the loop

### PR DESCRIPTION
**Pull request by yangx-jy**
It is unnecessary to set up DDIO in a loop.

Signed-off-by: Xiao Yang <yangx.jy@cn.fujitsu.com>

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/823)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/823)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[tools/rpma_fio_bench.sh, line 266 at r1](https://reviewable.io/reviews/pmem/rpma/823#-MSX-Ei68mX5oT-humXr:-MSX-Ei68mX5oT-humXs:b-k1w6p3) ([raw file](https://github.com/pmem/rpma/blob/e01966d5dc31e4d1d565899409ae781c2a178300/tools/rpma_fio_bench.sh#L266)):*
> ```
> exit 1
> ```

Please leave `return` here as it was before - it is supposed to return only from the `benchmark_one()` function, not exit from the script.

**Review by ldorau — COMMENTED** [review]
Good catch :-)

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/823#-:-MSX-bpQ7RiLbKyFgrdy:be2e71v)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

**Comment by yangx-jy** [comment]
___
*[tools/rpma_fio_bench.sh, line 266 at r1](https://reviewable.io/reviews/pmem/rpma/823#-MSX-Ei68mX5oT-humXr:-MSX07NR0Ttk9-Em-7cx:beqauu7) ([raw file](https://github.com/pmem/rpma/blob/e01966d5dc31e4d1d565899409ae781c2a178300/tools/rpma_fio_bench.sh#L266)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> exit 1
> ```

Please leave `return` here as it was before - it is supposed to return only from the `benchmark_one()` function, not exit from the script.
</blockquote></details>

Hi @ldorau

I call exit here because I think running per benchmark_one() uses the same enviorment variables,  Is it right?

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/823)* status: all files reviewed, 4 unresolved discussions (waiting on @yangx-jy)

___
*[tools/rpma_fio_bench.sh, line 246 at r1](https://reviewable.io/reviews/pmem/rpma/823#-MSX49vt4E9VnkhsNIYV:-MSX49vt4E9VnkhsNIYW:bizxj4v) ([raw file](https://github.com/pmem/rpma/blob/e01966d5dc31e4d1d565899409ae781c2a178300/tools/rpma_fio_bench.sh#L246)):*
> ```
> ./ddio.sh $REMOTE_USER@$SERVER_IP:$DIR
> ```

wrong alignment - add one tab more please
___
*[tools/rpma_fio_bench.sh, line 251 at r1](https://reviewable.io/reviews/pmem/rpma/823#-MSX4IFd8wiFHVVjXGEm:-MSX4IFd8wiFHVVjXGEn:bsloqe6) ([raw file](https://github.com/pmem/rpma/blob/e01966d5dc31e4d1d565899409ae781c2a178300/tools/rpma_fio_bench.sh#L251)):*
> ```
> 		$REMOTE_USER@$SERVER_IP \
> 		"sudo $DIR/ddio.sh -d $REMOTE_RNIC_PCIE_ROOT_PORT -s $DDIO_MODE \
> 		> $LOG_ERR 2>&1" 2>>$LOG_ERR
> ```

wrong alignment - add one tab more please
___
*[tools/rpma_fio_bench.sh, line 256 at r1](https://reviewable.io/reviews/pmem/rpma/823#-MSX4L4G-CEnd-l-T6jZ:-MSX4L4G-CEnd-l-T6j_:bfkkgye) ([raw file](https://github.com/pmem/rpma/blob/e01966d5dc31e4d1d565899409ae781c2a178300/tools/rpma_fio_bench.sh#L256)):*
> ```
> 		$REMOTE_USER@$SERVER_IP \
> 		"sudo $DIR/ddio.sh -d $REMOTE_RNIC_PCIE_ROOT_PORT -q \
> 		> $LOG_ERR 2>&1" 2>>$LOG_ERR
> ```

wrong alignment - add one tab more please
___
*[tools/rpma_fio_bench.sh, line 266 at r1](https://reviewable.io/reviews/pmem/rpma/823#-MSX-Ei68mX5oT-humXr:-MSX3_L41KudEM3Q06c3:b-wtu9h5) ([raw file](https://github.com/pmem/rpma/blob/e01966d5dc31e4d1d565899409ae781c2a178300/tools/rpma_fio_bench.sh#L266)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi @ldorau

I call exit here because I think running per benchmark_one() uses the same enviorment variables,  Is it right? 
</blockquote></details>

Setting the DDIO state depends on PERSIST_MODE (GPSPM or APM) - so it can behave differently in different calls of this function depending on the value of PERSIST_MODE.

**Review by yangx-jy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/823)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[tools/rpma_fio_bench.sh, line 246 at r1](https://reviewable.io/reviews/pmem/rpma/823#-MSX49vt4E9VnkhsNIYV:-MSX5i08BLAMHqAWggPl:b-ym5874) ([raw file](https://github.com/pmem/rpma/blob/e01966d5dc31e4d1d565899409ae781c2a178300/tools/rpma_fio_bench.sh#L246)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> ./ddio.sh $REMOTE_USER@$SERVER_IP:$DIR
> ```

wrong alignment - add one tab more please
</blockquote></details>

Sorry for the mistake.  Done
___
*[tools/rpma_fio_bench.sh, line 251 at r1](https://reviewable.io/reviews/pmem/rpma/823#-MSX4IFd8wiFHVVjXGEm:-MSX5kiO6rFMCiHdfpPc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e01966d5dc31e4d1d565899409ae781c2a178300/tools/rpma_fio_bench.sh#L251)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 		$REMOTE_USER@$SERVER_IP \
> 		"sudo $DIR/ddio.sh -d $REMOTE_RNIC_PCIE_ROOT_PORT -s $DDIO_MODE \
> 		> $LOG_ERR 2>&1" 2>>$LOG_ERR
> ```

wrong alignment - add one tab more please
</blockquote></details>

Done.
___
*[tools/rpma_fio_bench.sh, line 256 at r1](https://reviewable.io/reviews/pmem/rpma/823#-MSX4L4G-CEnd-l-T6jZ:-MSX5mZy6jemY8wwHtPA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e01966d5dc31e4d1d565899409ae781c2a178300/tools/rpma_fio_bench.sh#L256)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 		$REMOTE_USER@$SERVER_IP \
> 		"sudo $DIR/ddio.sh -d $REMOTE_RNIC_PCIE_ROOT_PORT -q \
> 		> $LOG_ERR 2>&1" 2>>$LOG_ERR
> ```

wrong alignment - add one tab more please
</blockquote></details>

Done.
___
*[tools/rpma_fio_bench.sh, line 266 at r1](https://reviewable.io/reviews/pmem/rpma/823#-MSX-Ei68mX5oT-humXr:-MSX5rNz18mftZUHQB37:b33zhcc) ([raw file](https://github.com/pmem/rpma/blob/e01966d5dc31e4d1d565899409ae781c2a178300/tools/rpma_fio_bench.sh#L266)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Setting the DDIO state depends on PERSIST_MODE (GPSPM or APM) - so it can behave differently in different calls of this function depending on the value of PERSIST_MODE. 
</blockquote></details>

It is reasonable.  Done

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/823)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/823#-:-MSX6ZpuA0pskvaMFX1H:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by ldorau — APPROVED** [review]
@janekmi @osalyk please review

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/823#-:-MSXDKUz9T-g0gjxqyks:b-3a72wj)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by ldorau — APPROVED** [review]
@yangx-jy please rebase

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/823#-:-MSXHDSBALGrQTt3JFCK:b-wmc05i)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/823#-:-MSXRG3v7IaPH9qrpfSv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/823)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/823)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Comment by yangx-jy** [comment]
Hi,

I also move the following code out of the loop:
```
if [ "$DUMP_CMDS" == "1" ]; then
        echo "REMOTE_DIRECT_WRITE_TO_PMEM=$REMOTE_DIRECT_WRITE_TO_PMEM" >> $SERVER_DUMP
        echo >> $SERVER_DUMP
fi
```

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/823)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/823#-:-MSbvqt27mZ1tE_C9vaN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/823)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Pull request merged**
