### PR TITLE
tools: write: GPSPM: add backticks to busy_wait_polling=X

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1232)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1232#-:-MiMQmza1OlmKp4ezzjy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1232)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/templates/part_write.md, line 15 at r1](https://reviewable.io/reviews/pmem/rpma/1232#-MiMWk55CmqQjpWPizsT:-MiMWk55CmqQjpWPizsU:b-6m714g) ([raw file](https://github.com/pmem/rpma/blob/7436b536a12f5d8b2e4733974700ac980721e07d/tools/perf/templates/part_write.md#L15)):*
> ```Markdown
> - **APM** uses `rpma_flush()` following a sequence of `rpma_write()` operations to provide the remote persistency. This method requires **the RPMA Target** to be capable of *Direct Write to PMem* (for details please see [Direct Write to PMem​​](https://pmem.io/rpma/documentation/basic-direct-write-to-pmem.html)).
> - **GPSPM** uses `rpma_send()` and `rpma_recv()` operations for sending requests to **the RPMA Target** to assure persistency of the data written using `rpma_write()`. **The RPMA Target** has to provide a thread handling these requests e.g. persisting the data using the `pmem_persist()` operation. When the persistency of the data is assured the response is sent back using also `rpma_send()` and `rpma_recv()`. Depending on how the thread polls for incoming requests you may distinguish two modes:
>     - **GPSPM-RT** where the thread polling for incoming requests busy-wait for them (busy\_wait\_polling=1) and
> ```

Backticks still missing: '`'
___
*[tools/perf/templates/part_write.md, line 16 at r1](https://reviewable.io/reviews/pmem/rpma/1232#-MiMX5Vw4XZTfg2y6I0E:-MiMX5Vw4XZTfg2y6I0F:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/7436b536a12f5d8b2e4733974700ac980721e07d/tools/perf/templates/part_write.md#L16)):*
> ```Markdown
> - **GPSPM** uses `rpma_send()` and `rpma_recv()` operations for sending requests to **the RPMA Target** to assure persistency of the data written using `rpma_write()`. **The RPMA Target** has to provide a thread handling these requests e.g. persisting the data using the `pmem_persist()` operation. When the persistency of the data is assured the response is sent back using also `rpma_send()` and `rpma_recv()`. Depending on how the thread polls for incoming requests you may distinguish two modes:
>     - **GPSPM-RT** where the thread polling for incoming requests busy-wait for them (busy\_wait\_polling=1) and
>     - **GPSPM** where the thread schedule to be wakened up when a request will appear (busy\_wait\_polling=0). Picking one of these polling modes over another introduces specific challenges and benefits.
> ```

.
___
*[tools/perf/templates/tc2_write.md, line 1 at r1](https://reviewable.io/reviews/pmem/rpma/1232#-MiMU19sB7BuFm113w5b:-MiMU19u1GyMk6ualmX3:biyuylt) ([raw file](https://github.com/pmem/rpma/blob/7436b536a12f5d8b2e4733974700ac980721e07d/tools/perf/templates/tc2_write.md#L1)):*
> ```Markdown
> Benchmarking two ways of writing data persistently to **the RPMA Target**: *Appliance Persistency Method* (**APM**) and *General Purpose Persistency Method* (**GPSPM**). Where:
> ```

This file is aimed to be delated in this sprint. Updating it is confusing. Please don't do this.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1232)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tools/perf/templates/part_write.md, line 15 at r1](https://reviewable.io/reviews/pmem/rpma/1232#-MiMWk55CmqQjpWPizsT:-MiM_CKs0gG7vT1lcPiS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7436b536a12f5d8b2e4733974700ac980721e07d/tools/perf/templates/part_write.md#L15)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Backticks still missing: '`'
</blockquote></details>

Done.
___
*[tools/perf/templates/part_write.md, line 16 at r1](https://reviewable.io/reviews/pmem/rpma/1232#-MiMX5Vw4XZTfg2y6I0E:-MiM_CaF1t_K2vn3UbsP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7436b536a12f5d8b2e4733974700ac980721e07d/tools/perf/templates/part_write.md#L16)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/templates/tc2_write.md, line 1 at r1](https://reviewable.io/reviews/pmem/rpma/1232#-MiMU19sB7BuFm113w5b:-MiM_7lcDrG7t9-SXiM5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7436b536a12f5d8b2e4733974700ac980721e07d/tools/perf/templates/tc2_write.md#L1)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This file is aimed to be delated in this sprint. Updating it is confusing. Please don't do this.
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1232)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/templates/part_write.md, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/1232#-MiMau1SC70J4J1q5GB9:-MiMau1UCJt2tSO0XoQQ:b-y06tvx) ([raw file](https://github.com/pmem/rpma/blob/5ec4bf5014c72d2f775b951aa25bde7c3eb21aec/tools/perf/templates/part_write.md#L15)):*
> ```Markdown
> - **APM** uses `rpma_flush()` following a sequence of `rpma_write()` operations to provide the remote persistency. This method requires **the RPMA Target** to be capable of *Direct Write to PMem* (for details please see [Direct Write to PMem​​](https://pmem.io/rpma/documentation/basic-direct-write-to-pmem.html)).
> - **GPSPM** uses `rpma_send()` and `rpma_recv()` operations for sending requests to **the RPMA Target** to assure persistency of the data written using `rpma_write()`. **The RPMA Target** has to provide a thread handling these requests e.g. persisting the data using the `pmem_persist()` operation. When the persistency of the data is assured the response is sent back using also `rpma_send()` and `rpma_recv()`. Depending on how the thread polls for incoming requests you may distinguish two modes:
>     - **GPSPM-RT** where the thread polling for incoming requests busy-wait for them (`busy\_wait\_polling=1`) and
> ```

Escaping is not needed when within backticks.
___
*[tools/perf/templates/part_write.md, line 16 at r2](https://reviewable.io/reviews/pmem/rpma/1232#-MiMb1E86nEgG1JppCFn:-MiMb1E86nEgG1JppCFo:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/5ec4bf5014c72d2f775b951aa25bde7c3eb21aec/tools/perf/templates/part_write.md#L16)):*
> ```Markdown
> - **GPSPM** uses `rpma_send()` and `rpma_recv()` operations for sending requests to **the RPMA Target** to assure persistency of the data written using `rpma_write()`. **The RPMA Target** has to provide a thread handling these requests e.g. persisting the data using the `pmem_persist()` operation. When the persistency of the data is assured the response is sent back using also `rpma_send()` and `rpma_recv()`. Depending on how the thread polls for incoming requests you may distinguish two modes:
>     - **GPSPM-RT** where the thread polling for incoming requests busy-wait for them (`busy\_wait\_polling=1`) and
>     - **GPSPM** where the thread schedule to be wakened up when a request will appear (`busy\_wait\_polling=0`). Picking one of these polling modes over another introduces specific challenges and benefits.
> ```

.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1232)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/templates/part_write.md, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/1232#-MiMau1SC70J4J1q5GB9:-MiMcGkj5lFGFZ7DtLBJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5ec4bf5014c72d2f775b951aa25bde7c3eb21aec/tools/perf/templates/part_write.md#L15)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Escaping is not needed when within backticks.
</blockquote></details>

Done.
___
*[tools/perf/templates/part_write.md, line 16 at r2](https://reviewable.io/reviews/pmem/rpma/1232#-MiMb1E86nEgG1JppCFn:-MiMcH2r8Dm8lnp1YCnW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5ec4bf5014c72d2f775b951aa25bde7c3eb21aec/tools/perf/templates/part_write.md#L16)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1232#-:-MiMeb1E9gn6iPrcBxNJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
