### PR TITLE
examples: remove unused doc_snippets

### PR DESCRIPTION
**Pull request by yangx-jy**
Signed-off-by: Xiao Yang <yangx.jy@fujitsu.com>

- - -
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/2036)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2036)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2036#-NCZRUc09vcyPklPQHyw:-NCZRUc16Bwi90DWQB2_:b2qtuew) (no related file):*
Please add info about it to CHANGELOG.md.

___

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2036#-:-NCZU8uS64lv2JsPaptG:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

**Review by ldorau — COMMENTED** [review]
:lgtm: except of my one issue (CHANGELOG.md)

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2036#-:-NCZUtKP0JFSk8XjH7Wj:b-cve1l8)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2036#-:-NCZwnlq3H5Cz-_WLjj4:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2036#-:-NC_GpY--8SfI6qKsJIX:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2036#-NC_Gm8774rQF0WCWAq3:-NC_Gm888ieSFyvz3xS4:b-ujmq67) (no related file):*
Rebase please

___

**Review by yangx-jy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2036)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @ldorau and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2036#-NC_Gm8774rQF0WCWAq3:-NC_RdUb4W8qP9wGSAXB:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Rebase please
</blockquote></details>

Done.

___

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2036)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Pull request merged**
