### PR TITLE
tools: set read lat & bw configs for ib_read_*

### PR DESCRIPTION
**Pull request by janekmi**
Requires:
- [x] #808
- [x] #814

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/820)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/820)* status: 2 of 9 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/templates/.gitignore, line 6 at r1](https://reviewable.io/reviews/pmem/rpma/820#-MSWTjCVA5cv0UfBEIQr:-MSWTjCVA5cv0UfBEIQs:b9fbj3r) ([raw file](https://github.com/pmem/rpma/blob/511e03f1cca6eb44b86b8540347ffdc4760b9958/tools/templates/.gitignore#L6)):*
> ```ignore
> !tc1_read.md
> !tc2_write.md
> !tc3_mix.md
> ```

new line is missing
___
*[tools/templates/tc_config.md.template, line 25 at r1](https://reviewable.io/reviews/pmem/rpma/820#-MSWTnCF8spQ45gyOafG:-MSWTnCF8spQ45gyOafH:b9fbj3r) ([raw file](https://github.com/pmem/rpma/blob/511e03f1cca6eb44b86b8540347ffdc4760b9958/tools/templates/tc_config.md.template#L25)):*
> ```
> </pre></td></tr>
> </tbody>
> </table>
> ```

new line is missing

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/820)* status: 2 of 9 files reviewed, 2 unresolved discussions (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/820#-MSWUEGY2mII3QyN57xy:-MSWUEGY2mII3QyN57xz:by2tyay) (no related file):*
misleading PR description

---

**Review by grom72 — COMMENTED** [review]
> Reviewed 7 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/820)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/820)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/820#-MSWUEGY2mII3QyN57xy:-MSWxpsm0YSZavwQokkH:b3g1xes) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

misleading PR description
</blockquote></details>

Nooo. If you filter out all related PRs it still misleads you?

---

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/820)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[tools/templates/.gitignore, line 6 at r1](https://reviewable.io/reviews/pmem/rpma/820#-MSWTjCVA5cv0UfBEIQr:-MSWy51N1knGF1CQW3bg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/511e03f1cca6eb44b86b8540347ffdc4760b9958/tools/templates/.gitignore#L6)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

new line is missing
</blockquote></details>

Done.
___
*[tools/templates/tc_config.md.template, line 25 at r1](https://reviewable.io/reviews/pmem/rpma/820#-MSWTnCF8spQ45gyOafG:-MSWy7jm03R6UinYe2Eu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/511e03f1cca6eb44b86b8540347ffdc4760b9958/tools/templates/tc_config.md.template#L25)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

new line is missing
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/820)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/820#-:-MSX81OT0QcnLMGKmQqf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/820#-:-MSXe4EbAqVyLoVlJSMq:bnfp4nl)* status: 4 of 5 files reviewed, all discussions resolved

**Pull request merged**
