### PR TITLE
tools: perf: document lib.figure.{base,html,image}

### PR DESCRIPTION
**Pull request by janekmi**
Additionally, the commit contains:
- forcing each Figure instance to have a result_dir set from the conception.

Requires:

- [x] #1366
- [x] #1367
- [x] #1368
- [x] #1369

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1371)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1371)* status: 0 of 16 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1371)* status: 0 of 16 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1371#-MpksQWn2Ck89P4QjKNI:-MpksQWn2Ck89P4QjKNJ:b-v3kov0) (no related file):*
CI builds fail

---

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1371)* status: 0 of 16 files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1371#-MpksQWn2Ck89P4QjKNI:-Mpkyko96s6KySMvRtri:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

CI builds fail
</blockquote></details>

Done.

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 11 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1371)* status: 11 of 16 files reviewed, 5 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/lib/figure/__init__.py, line 11 at r2](https://reviewable.io/reviews/pmem/rpma/1371#-Mpl0rM45Bk0lu7Wbc46:-Mpl0rM45Bk0lu7Wbc47:bzi31bx) ([raw file](https://github.com/pmem/rpma/blob/cc7cba42939b2d0940de914309f43c815cf4e351/tools/perf/lib/figure/__init__.py#L11)):*
> ```
> a benchmarking process
> ```

the benchmarking process
___
*[tools/perf/lib/figure/__init__.py, line 13 at r2](https://reviewable.io/reviews/pmem/rpma/1371#-Mpl0xFa30-t1CoUAzEr:-Mpl0xFa30-t1CoUAzEs:bc0iwb7) ([raw file](https://github.com/pmem/rpma/blob/cc7cba42939b2d0940de914309f43c815cf4e351/tools/perf/lib/figure/__init__.py#L13)):*
> ```
> the figure metadata
> ```

the figure's metadata
___
*[tools/perf/lib/figure/__init__.py, line 17 at r2](https://reviewable.io/reviews/pmem/rpma/1371#-Mpl14CFCve0XpUDJHzF:-Mpl14CFCve0XpUDJHzG:b-mx5wzu) ([raw file](https://github.com/pmem/rpma/blob/cc7cba42939b2d0940de914309f43c815cf4e351/tools/perf/lib/figure/__init__.py#L17)):*
> ```
> figures definition
> ```

`figures' definition` or `definition of figures`
___
*[tools/perf/lib/figure/__init__.py, line 19 at r2](https://reviewable.io/reviews/pmem/rpma/1371#-Mpl1HLmAZINDiI98-4M:-Mpl1HLmAZINDiI98-4N:bnbygr3) ([raw file](https://github.com/pmem/rpma/blob/cc7cba42939b2d0940de914309f43c815cf4e351/tools/perf/lib/figure/__init__.py#L19)):*
> ```
> a given
> ```

the given
___
*[tools/perf/lib/figure/__init__.py, line 19 at r2](https://reviewable.io/reviews/pmem/rpma/1371#-Mpl1_Ez7GgV0aFj8BCX:-Mpl1_Ez7GgV0aFj8BCY:b-oeu4w5) ([raw file](https://github.com/pmem/rpma/blob/cc7cba42939b2d0940de914309f43c815cf4e351/tools/perf/lib/figure/__init__.py#L19)):*
> ```
> a given part's figure JSON input file
> ```

There is so many nouns here, that I do not know what you mean...

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1371)* status: 11 of 16 files reviewed, 6 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[tools/perf/lib/figure/__init__.py, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/1371#-Mpl4Nxd91SpO2EAF0SC:-Mpl4Nxd91SpO2EAF0SD:b-6k4aax) ([raw file](https://github.com/pmem/rpma/blob/1b1b2cc32ec62dc24ad0205813d38da5789561c2/tools/perf/lib/figure/__init__.py#L17)):*
> ```Python
> `lib.benchmark.base.Benchmark` instance.
> 
> Knowing that figures definition on the input may be multidimensional,
> ```

**Note **
The definition of figures on the input (<italic>figure.json<italic>) may be multidimensional.
`lib.figure.flat.flatten` is used by default to create a list of `lib.figure.base.Figure` instances from a part of JSON input file.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1371)* status: 11 of 16 files reviewed, 6 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[tools/perf/lib/figure/__init__.py, line 19 at r2](https://reviewable.io/reviews/pmem/rpma/1371#-Mpl1_Ez7GgV0aFj8BCX:-Mpl5Sqv228qB_4LEF1P:b-eh4l5j) ([raw file](https://github.com/pmem/rpma/blob/cc7cba42939b2d0940de914309f43c815cf4e351/tools/perf/lib/figure/__init__.py#L19)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> a given part's figure JSON input file
> ```

There is so many nouns here, that I do not know what you mean...
</blockquote></details>

+1 - see above -> Note

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1371)* status: 11 of 16 files reviewed, 6 unresolved discussions (waiting on @grom72, @haichangsi, @janekmi, and @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 3 of 16 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1371)* status: 15 of 16 files reviewed, 7 unresolved discussions (waiting on @grom72, @haichangsi, @janekmi, and @ldorau)

___
*[tools/perf/lib/figure/base.py, line 207 at r2](https://reviewable.io/reviews/pmem/rpma/1371#-MplCgXuD04Sc6y9coir:-MplCgXuD04Sc6y9cois:b-z9tluq) ([raw file](https://github.com/pmem/rpma/blob/cc7cba42939b2d0940de914309f43c815cf4e351/tools/perf/lib/figure/base.py#L207)):*
> ```
>         to a `Figure.file`
>         JSON file
> ```
to a JSON file (`Figure file`)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1371)* status: 12 of 16 files reviewed, 5 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[tools/perf/lib/figure/__init__.py, line 11 at r2](https://reviewable.io/reviews/pmem/rpma/1371#-Mpl0rM45Bk0lu7Wbc46:-MplDnSc--iUt5uxuHTk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cc7cba42939b2d0940de914309f43c815cf4e351/tools/perf/lib/figure/__init__.py#L11)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> a benchmarking process
> ```

the benchmarking process
</blockquote></details>

Done.
___
*[tools/perf/lib/figure/__init__.py, line 13 at r2](https://reviewable.io/reviews/pmem/rpma/1371#-Mpl0xFa30-t1CoUAzEr:-MplDqRs4qg0Y1SaVL9w:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cc7cba42939b2d0940de914309f43c815cf4e351/tools/perf/lib/figure/__init__.py#L13)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> the figure metadata
> ```

the figure's metadata
</blockquote></details>

Done.
___
*[tools/perf/lib/figure/__init__.py, line 17 at r2](https://reviewable.io/reviews/pmem/rpma/1371#-Mpl14CFCve0XpUDJHzF:-MplE1sCCKcJAnybbQV7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cc7cba42939b2d0940de914309f43c815cf4e351/tools/perf/lib/figure/__init__.py#L17)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> figures definition
> ```

`figures' definition` or `definition of figures`
</blockquote></details>

Done.
___
*[tools/perf/lib/figure/__init__.py, line 19 at r2](https://reviewable.io/reviews/pmem/rpma/1371#-Mpl1HLmAZINDiI98-4M:-MplE4WhAx4FtNad2VVI:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cc7cba42939b2d0940de914309f43c815cf4e351/tools/perf/lib/figure/__init__.py#L19)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> a given
> ```

the given
</blockquote></details>

Done.
___
*[tools/perf/lib/figure/__init__.py, line 19 at r2](https://reviewable.io/reviews/pmem/rpma/1371#-Mpl1_Ez7GgV0aFj8BCX:-MplEj9bE-QNQ1oUkT6E:b-yw8ca2) ([raw file](https://github.com/pmem/rpma/blob/cc7cba42939b2d0940de914309f43c815cf4e351/tools/perf/lib/figure/__init__.py#L19)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

+1 - see above -> Note
</blockquote></details>

Any better?
___
*[tools/perf/lib/figure/base.py, line 207 at r2](https://reviewable.io/reviews/pmem/rpma/1371#-MplCgXuD04Sc6y9coir:-MplHnX3BT3p2oB1VdX7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cc7cba42939b2d0940de914309f43c815cf4e351/tools/perf/lib/figure/base.py#L207)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
>         to a `Figure.file`
>         JSON file
> ```
to a JSON file (`Figure file`)
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 8 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1371)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @grom72, @haichangsi, @janekmi, and @ldorau)

___
*[tools/perf/lib/figure/__init__.py, line 19 at r2](https://reviewable.io/reviews/pmem/rpma/1371#-Mpl1_Ez7GgV0aFj8BCX:-MplNgVc06m4WMW4CuaC:b-kgq88g) ([raw file](https://github.com/pmem/rpma/blob/cc7cba42939b2d0940de914309f43c815cf4e351/tools/perf/lib/figure/__init__.py#L19)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Any better?
</blockquote></details>

` the part's figure JSON input file.` still is not clear for me ...

For example: ` the part's figure` means "the figure of the part" - is it correct ?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1371)* status: 14 of 16 files reviewed, 1 unresolved discussion (waiting on @grom72, @haichangsi, and @ldorau)

___
*[tools/perf/lib/figure/__init__.py, line 19 at r2](https://reviewable.io/reviews/pmem/rpma/1371#-Mpl1_Ez7GgV0aFj8BCX:-MplRd4dE55nHRnzNHy-:b-5ueq4z) ([raw file](https://github.com/pmem/rpma/blob/cc7cba42939b2d0940de914309f43c815cf4e351/tools/perf/lib/figure/__init__.py#L19)):*
> For example: the part's figure means "the figure of the part" - is it correct ?

Yes. But I think it will be easier to not come back so far to mention parts here. It does not add anything.

Please take a look one more time.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1371)* status: 15 of 16 files reviewed, 10 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/lib/figure/base.py, line 112 at r3](https://reviewable.io/reviews/pmem/rpma/1371#-MplS3QrC0u_w0ATTsgb:-MplS3QrC0u_w0ATTsgc:b-60ft6c) ([raw file](https://github.com/pmem/rpma/blob/ad400ef58f8bed85472bbbcf9f05c8f80c92d414/tools/perf/lib/figure/base.py#L112)):*
> ```
> on a given series
> ```

`of the given series` or `in the given series`
___
*[tools/perf/lib/figure/base.py, line 138 at r3](https://reviewable.io/reviews/pmem/rpma/1371#-MplSPlu3ogvaUf42nfW:-MplSPlu3ogvaUf42nfX:b-538soc) ([raw file](https://github.com/pmem/rpma/blob/ad400ef58f8bed85472bbbcf9f05c8f80c92d414/tools/perf/lib/figure/base.py#L138)):*
> ```
> which store
> ```

which stores
___
*[tools/perf/lib/figure/base.py, line 139 at r3](https://reviewable.io/reviews/pmem/rpma/1371#-MplSS0sEE0Vz8dFbi47:-MplSS0sEE0Vz8dFbi48:bpnldjj) ([raw file](https://github.com/pmem/rpma/blob/ad400ef58f8bed85472bbbcf9f05c8f80c92d414/tools/perf/lib/figure/base.py#L139)):*
> ```
> which store
> ```

.
___
*[tools/perf/lib/figure/base.py, line 146 at r3](https://reviewable.io/reviews/pmem/rpma/1371#-MplSf7w7LX_WvgQ4FuO:-MplSf7w7LX_WvgQ4FuP:bfvgqz) ([raw file](https://github.com/pmem/rpma/blob/ad400ef58f8bed85472bbbcf9f05c8f80c92d414/tools/perf/lib/figure/base.py#L146)):*
> ```
> A `dict` compiling the current state of the figure.
> ```

A `dict` being a compilation of the current state of the figure.
___
*[tools/perf/lib/figure/base.py, line 151 at r3](https://reviewable.io/reviews/pmem/rpma/1371#-MplSruV3vLCV_Wsig0n:-MplSruV3vLCV_Wsig0o:b-czvk9o) ([raw file](https://github.com/pmem/rpma/blob/ad400ef58f8bed85472bbbcf9f05c8f80c92d414/tools/perf/lib/figure/base.py#L151)):*
> ```
> Do the results for the figure have been collected?
> ```

Have the results for the figure been collected?
___
*[tools/perf/lib/figure/base.py, line 203 at r3](https://reviewable.io/reviews/pmem/rpma/1371#-MplTHI40FVimwwhunMv:-MplTHI40FVimwwhunMw:brl0qdr) ([raw file](https://github.com/pmem/rpma/blob/ad400ef58f8bed85472bbbcf9f05c8f80c92d414/tools/perf/lib/figure/base.py#L203)):*
> ```
> the order benchmark's result file
> ```

`the order OF benchmark's result file` or `the order OF benchmarks' result files` ?
___
*[tools/perf/lib/figure/base.py, line 207 at r3](https://reviewable.io/reviews/pmem/rpma/1371#-MplTfphAUKZ_SeQm6Qz:-MplTfphAUKZ_SeQm6R-:b-w0uyri) ([raw file](https://github.com/pmem/rpma/blob/ad400ef58f8bed85472bbbcf9f05c8f80c92d414/tools/perf/lib/figure/base.py#L207)):*
> ```
> are collected it
> ```

are collected, it (add comma)
___
*[tools/perf/lib/figure/base.py, line 207 at r3](https://reviewable.io/reviews/pmem/rpma/1371#-MplTkMcCZVQLCUokK3c:-MplTkMcCZVQLCUokK3d:b-o16qdl) ([raw file](https://github.com/pmem/rpma/blob/ad400ef58f8bed85472bbbcf9f05c8f80c92d414/tools/perf/lib/figure/base.py#L207)):*
> ```
> it is write down 
> ```

it is written down 
___
*[tools/perf/lib/figure/base.py, line 273 at r3](https://reviewable.io/reviews/pmem/rpma/1371#-MplTvDP47mJT7HNIc92:-MplTvDP47mJT7HNIc93:b-g68gkx) ([raw file](https://github.com/pmem/rpma/blob/ad400ef58f8bed85472bbbcf9f05c8f80c92d414/tools/perf/lib/figure/base.py#L273)):*
> ```
> is done the collected
> ```

is done, the collected ...

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1371)* status: 15 of 16 files reviewed, 9 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/lib/figure/__init__.py, line 19 at r2](https://reviewable.io/reviews/pmem/rpma/1371#-Mpl1_Ez7GgV0aFj8BCX:-MplUPXfBgJSrSePYqEE:b-pogvhr) ([raw file](https://github.com/pmem/rpma/blob/cc7cba42939b2d0940de914309f43c815cf4e351/tools/perf/lib/figure/__init__.py#L19)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

> For example: the part's figure means "the figure of the part" - is it correct ?

Yes. But I think it will be easier to not come back so far to mention parts here. It does not add anything.

Please take a look one more time.
</blockquote></details>

That's clear now :-)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1371)* status: all files reviewed, 10 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/lib/figure/html.py, line 20 at r4](https://reviewable.io/reviews/pmem/rpma/1371#-MplUnwh1lzlRjC-LK7z:-MplUnwh1lzlRjC-LK8-:bbz9m1x) ([raw file](https://github.com/pmem/rpma/blob/30aaeb2d46fa575748fa4f32749363993324b8f1/tools/perf/lib/figure/html.py#L20)):*
> ```
> an ordered list
> ```

the ordered list

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1371)* status: 14 of 16 files reviewed, 10 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/lib/figure/base.py, line 112 at r3](https://reviewable.io/reviews/pmem/rpma/1371#-MplS3QrC0u_w0ATTsgb:-MplVWb70acyuPaHn2_Y:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ad400ef58f8bed85472bbbcf9f05c8f80c92d414/tools/perf/lib/figure/base.py#L112)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> on a given series
> ```

`of the given series` or `in the given series`
</blockquote></details>

Done.
___
*[tools/perf/lib/figure/base.py, line 138 at r3](https://reviewable.io/reviews/pmem/rpma/1371#-MplSPlu3ogvaUf42nfW:-MplVZbNBHQY6Qw3xWLE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ad400ef58f8bed85472bbbcf9f05c8f80c92d414/tools/perf/lib/figure/base.py#L138)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> which store
> ```

which stores
</blockquote></details>

Done.
___
*[tools/perf/lib/figure/base.py, line 139 at r3](https://reviewable.io/reviews/pmem/rpma/1371#-MplSS0sEE0Vz8dFbi47:-MplV_38E0v9g4fK63QK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ad400ef58f8bed85472bbbcf9f05c8f80c92d414/tools/perf/lib/figure/base.py#L139)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> which store
> ```

.
</blockquote></details>

Done.
___
*[tools/perf/lib/figure/base.py, line 146 at r3](https://reviewable.io/reviews/pmem/rpma/1371#-MplSf7w7LX_WvgQ4FuO:-MplVhbkCq8WdYhRGGp-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ad400ef58f8bed85472bbbcf9f05c8f80c92d414/tools/perf/lib/figure/base.py#L146)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> A `dict` compiling the current state of the figure.
> ```

A `dict` being a compilation of the current state of the figure.
</blockquote></details>

Done.
___
*[tools/perf/lib/figure/base.py, line 151 at r3](https://reviewable.io/reviews/pmem/rpma/1371#-MplSruV3vLCV_Wsig0n:-MplVmnGAVK0jWOwgmMT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ad400ef58f8bed85472bbbcf9f05c8f80c92d414/tools/perf/lib/figure/base.py#L151)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> Do the results for the figure have been collected?
> ```

Have the results for the figure been collected?
</blockquote></details>

Done.
___
*[tools/perf/lib/figure/base.py, line 203 at r3](https://reviewable.io/reviews/pmem/rpma/1371#-MplTHI40FVimwwhunMv:-MplWame3p4HcXVvG4EA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ad400ef58f8bed85472bbbcf9f05c8f80c92d414/tools/perf/lib/figure/base.py#L203)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> the order benchmark's result file
> ```

`the order OF benchmark's result file` or `the order OF benchmarks' result files` ?
</blockquote></details>

Done.
___
*[tools/perf/lib/figure/base.py, line 207 at r3](https://reviewable.io/reviews/pmem/rpma/1371#-MplTfphAUKZ_SeQm6Qz:-MplVyB-8mCOrBhPBw2h:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ad400ef58f8bed85472bbbcf9f05c8f80c92d414/tools/perf/lib/figure/base.py#L207)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> are collected it
> ```

are collected, it (add comma)
</blockquote></details>

Done.
___
*[tools/perf/lib/figure/base.py, line 207 at r3](https://reviewable.io/reviews/pmem/rpma/1371#-MplTkMcCZVQLCUokK3c:-MplW-ivCTPYfEgh_yTM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ad400ef58f8bed85472bbbcf9f05c8f80c92d414/tools/perf/lib/figure/base.py#L207)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> it is write down 
> ```

it is written down 
</blockquote></details>

Done.
___
*[tools/perf/lib/figure/base.py, line 273 at r3](https://reviewable.io/reviews/pmem/rpma/1371#-MplTvDP47mJT7HNIc92:-MplW2ZyBGzc0JygBxtC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ad400ef58f8bed85472bbbcf9f05c8f80c92d414/tools/perf/lib/figure/base.py#L273)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> is done the collected
> ```

is done, the collected ...
</blockquote></details>

Done.
___
*[tools/perf/lib/figure/html.py, line 20 at r4](https://reviewable.io/reviews/pmem/rpma/1371#-MplUnwh1lzlRjC-LK7z:-MplW6_t9CusySYLPn6k:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/30aaeb2d46fa575748fa4f32749363993324b8f1/tools/perf/lib/figure/html.py#L20)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> an ordered list
> ```

the ordered list
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1371#-:-MplcuPABWlkhXYfx5U5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1371#-:-MpliOAC3dzDDPQ5Q-oj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
