### PR TITLE
examples: fix memory allocations in example 07

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/2081)

### CODE REVIEW

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2081#-:-NGGjd2gCKFWN3tgFaUq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2081)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`examples/07-atomic-write/server.c` line 19 at r2](https://reviewable.io/reviews/pmem/rpma/2081#-NGHAwGiDQbtNvDI0Mpn:-NGHAwGiDQbtNvDI0Mpo:b-4vtdyq) ([raw file](https://github.com/pmem/rpma/blob/18f5364c5def9fa3778491b94271332221b94d16/examples/07-atomic-write/server.c#L19)):*
> ```C
> 
> #ifdef USE_PMEM
> #define USAGE_STR "usage: %s <server_address> <port> [<pmem-path>]\n"PMEM_USAGE
> ```

@ldorau can you make a separate section for the log header signature? It improves source code readability.



_Suggestion:_
```C
#ifdef USE_PMEM
#define USAGE_STR "usage: %s <server_address> <port> [<pmem-path>]\n"PMEM_USAGE
#else
#define USAGE_STR "usage: %s <server_address> <port>\n"
#endif /* USE_PMEM */

#ifdef USE_PMEM
#define LOG_HDR_SIGNATURE "LOG"
#endif /* USE_PMEM */
```

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2081)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[`examples/07-atomic-write/server.c` line 93 at r2](https://reviewable.io/reviews/pmem/rpma/2081#-NGHCIb24KHoEBUp5DLR:-NGHCIb24KHoEBUp5DLS:bqtjosc) ([raw file](https://github.com/pmem/rpma/blob/18f5364c5def9fa3778491b94271332221b94d16/examples/07-atomic-write/server.c#L93)):*
> ```C
> 		(void) fprintf(stderr, NO_PMEM_MSG);
> 		mem.mr_size = LOG_SIZE;
> 		mem.mr_ptr = malloc_aligned(LOG_SIZE);
> ```

do not initialize mem before successful memory allocation



_Suggestion:_
```C
		mem.mr_ptr = malloc_aligned(LOG_SIZE);
		if (mem.mr_ptr == NULL)
			return -1;
		mem.mr_size = LOG_SIZE;
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2081)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2081)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2081)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72 and @osalyk)

___
*[`examples/07-atomic-write/server.c` line 93 at r2](https://reviewable.io/reviews/pmem/rpma/2081#-NGHCIb24KHoEBUp5DLR:-NGHDuwm17psUpZqpRGW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/18f5364c5def9fa3778491b94271332221b94d16/examples/07-atomic-write/server.c#L93)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

do not initialize mem before successful memory allocation
</blockquote></details>

Done.

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2081#-:-NGHF-sk2HM4YKf_mhun:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
