### PR TITLE
rpma: analysis of thread safety: rpma_ep_

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [ ] #1755

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1761)

### CODE REVIEW

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1761)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1761#-:-N2z43UcDyhiE6gh588s:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1761)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1761#-N2zfa9N5yucNyeRFI2Y:-N2zfa9N5yucNyeRFI2Z:b9djvyh) (no related file):*
``the same time`` or ``at a time``



_Code quote (from THREAD_SAFETY.md):_
```Markdown
the same time
```

___

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1761)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1761#-N2zfa9N5yucNyeRFI2Y:-N2zupAnCGNxnS5HCe1E:bb6qe1x) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

``the same time`` or ``at a time``
</blockquote></details>

??

___

**Review by osalyk — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1761)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1761)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @grom72 and @osalyk)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1761#-:-N3-6da9Ej4xXjVhgOwm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
