### PR TITLE
test: add common epoll functions to MT framework

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1713)

### CODE REVIEW

**Comment by ldorau** [comment]
All those functions were copied from the 06 example.

**Review by osalyk — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1713)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[`tests/multithreaded/common/mtt_common-epoll.h` line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1713#-N0oJHWaAtB1PNqfCy6Z:-N0oJHWaAtB1PNqfCy6_:bb6ht37) ([raw file](https://github.com/pmem/rpma/blob/1cf9385bd7e668d7f74a54155bf14ba293987910/tests/multithreaded/common/mtt_common-epoll.h#L2)):*
> ```objc
> /* SPDX-License-Identifier: BSD-3-Clause */
> /* Copyright 2020-2022, Intel Corporation */
> ```

2022
___
*[`tests/multithreaded/common/mtt_common-epoll.h` line 26 at r1](https://reviewable.io/reviews/pmem/rpma/1713#-N0oJ7C0BjG004GQEeeu:-N0oJ7C0BjG004GQEeev:bhtpuv1) ([raw file](https://github.com/pmem/rpma/blob/1cf9385bd7e668d7f74a54155bf14ba293987910/tests/multithreaded/common/mtt_common-epoll.h#L26)):*
> ```objc
> 
> int epoll_add(int epoll, int fd, void *arg, event_func func,
> 		struct custom_event *ce);
> ```

Will fit in one line.
___
*[`tests/multithreaded/common/mtt_common-epoll.c` line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1713#-N0oJJSNB8-T6gg374HS:-N0oJJSNB8-T6gg374HT:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/1cf9385bd7e668d7f74a54155bf14ba293987910/tests/multithreaded/common/mtt_common-epoll.c#L2)):*
> ```C
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2020-2022, Intel Corporation */
> ```

.
___
*[`tests/multithreaded/common/mtt_common-epoll.c` line 43 at r1](https://reviewable.io/reviews/pmem/rpma/1713#-N0oJOSn0i7vtKnZmnCz:-N0oJOSn0i7vtKnZmnD-:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/1cf9385bd7e668d7f74a54155bf14ba293987910/tests/multithreaded/common/mtt_common-epoll.c#L43)):*
> ```C
>  */
> int
> epoll_add(int epoll, int fd, void *arg, event_func func,
> ```

.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1713)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @osalyk)

___
*[`tests/multithreaded/common/mtt_common-epoll.h` line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1713#-N0oJHWaAtB1PNqfCy6Z:-N0oJdJdDErXnKzM0u_s:bvvuhmz) ([raw file](https://github.com/pmem/rpma/blob/1cf9385bd7e668d7f74a54155bf14ba293987910/tests/multithreaded/common/mtt_common-epoll.h#L2)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

2022
</blockquote></details>

No, this code is mostly copied, so the copyright dates cannot change.
___
*[`tests/multithreaded/common/mtt_common-epoll.h` line 26 at r1](https://reviewable.io/reviews/pmem/rpma/1713#-N0oJ7C0BjG004GQEeeu:-N0oKLBDD1IceX03tlSr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1cf9385bd7e668d7f74a54155bf14ba293987910/tests/multithreaded/common/mtt_common-epoll.h#L26)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Will fit in one line.
</blockquote></details>

Done.



_Code quote:_
```objc
nt epoll_add(int epoll, int fd, void *arg, event_func
```
___
*[`tests/multithreaded/common/mtt_common-epoll.c` line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1713#-N0oJJSNB8-T6gg374HS:-N0oJscq2JR_jK4Ak1Ab:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/1cf9385bd7e668d7f74a54155bf14ba293987910/tests/multithreaded/common/mtt_common-epoll.c#L2)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

.
</blockquote></details>

.
___
*[`tests/multithreaded/common/mtt_common-epoll.c` line 43 at r1](https://reviewable.io/reviews/pmem/rpma/1713#-N0oJOSn0i7vtKnZmnCz:-N0oKLsu1eTIeOhMp5Pk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1cf9385bd7e668d7f74a54155bf14ba293987910/tests/multithreaded/common/mtt_common-epoll.c#L43)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1713#-:-N0oMjV3CIlHv72_E3Mq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1713)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1713#-:-N0p-m0-7Z6jkJJ03fKY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
