### PR TITLE
tools: perf: complete and incomplete end

### PR DESCRIPTION
**Pull request by janekmi**
Requires:

- [x] #1357

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1363)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1363)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1363)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1363#-:-Mph_CCb9-d5dY2mXFF6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1363)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/report_bench.py, line 73 at r2](https://reviewable.io/reviews/pmem/rpma/1363#-Mphf226AgFKuFNgysWG:-Mphf226AgFKuFNgysWH:bnfd0cq) ([raw file](https://github.com/pmem/rpma/blob/9d5ccf5a08ad28b26402859e83846da8ac0e1bab/tools/perf/report_bench.py#L73)):*
> ```
> Done.
> ```
"Bench dump is done."
as an alternative 
"Dumped"
___
*[tools/perf/report_bench.py, line 76 at r2](https://reviewable.io/reviews/pmem/rpma/1363#-Mphf9CxDRAG72boyMIz:-Mphf9CxDRAG72boyMJ-:bs3t7j4) ([raw file](https://github.com/pmem/rpma/blob/9d5ccf5a08ad28b26402859e83846da8ac0e1bab/tools/perf/report_bench.py#L76)):*
> ```
> Complete.
> ```
Bench run is completed.
___
*[tools/perf/report_bench.py, line 78 at r2](https://reviewable.io/reviews/pmem/rpma/1363#-MphfG_3-O4mILzonaxC:-MphfG_3-O4mILzonaxD:b-yaohfb) ([raw file](https://github.com/pmem/rpma/blob/9d5ccf5a08ad28b26402859e83846da8ac0e1bab/tools/perf/report_bench.py#L78)):*
> ```
> Incomplete
> ```
.

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1363)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1363)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1363)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/report_bench.py, line 73 at r2](https://reviewable.io/reviews/pmem/rpma/1363#-Mphf226AgFKuFNgysWG:-MphmSjc9HCzECmvwtsf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9d5ccf5a08ad28b26402859e83846da8ac0e1bab/tools/perf/report_bench.py#L73)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Done.
> ```
"Bench dump is done."
as an alternative 
"Dumped"
</blockquote></details>

Done.
___
*[tools/perf/report_bench.py, line 76 at r2](https://reviewable.io/reviews/pmem/rpma/1363#-Mphf9CxDRAG72boyMIz:-MphmtamAu56AVieJtII:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9d5ccf5a08ad28b26402859e83846da8ac0e1bab/tools/perf/report_bench.py#L76)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Complete.
> ```
Bench run is completed.
</blockquote></details>

Done.
___
*[tools/perf/report_bench.py, line 78 at r2](https://reviewable.io/reviews/pmem/rpma/1363#-MphfG_3-O4mILzonaxC:-MphmuZg8mHv_i6Milt7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9d5ccf5a08ad28b26402859e83846da8ac0e1bab/tools/perf/report_bench.py#L78)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Incomplete
> ```
.
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1363#-:-MpjhblO4B7sZHZOs0kf:bnfp4nl)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1363#-:-MpjpUXL4nknSbiqUy5J:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
