### PR TITLE
test: add new suppressions for drd and helgrind

### PR DESCRIPTION
**Pull request by ldorau**
See: https://app.circleci.com/pipelines/github/ldorau/rpma/4252/workflows/f50c40ac-b135-43b2-a281-8cabc79fc05c/jobs/4335

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1837)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
Can you add the libibverbs version?

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1837#-:-N4XdSSx98CUSGisIgCE:bdeke7h)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`tests/helgrind.supp` line 403 at r1](https://reviewable.io/reviews/pmem/rpma/1837#-N4XccAl7sUobPzqQm9q:-N4XccAl7sUobPzqQm9r:b-djwxls) ([raw file](https://github.com/pmem/rpma/blob/b22dec1a5b342288eaef4b71740fba3a00499746/tests/helgrind.supp#L403)):*
> ```
>    fun:rpma_mr_reg
>    ...
> }
> ```

missing new line at the end of the file

**Review by ldorau — COMMENTED** [review]
Added

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1837#-:-N4XmhlZE8kXViwpWLuK:b-8b11j9)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`tests/helgrind.supp` line 403 at r1](https://reviewable.io/reviews/pmem/rpma/1837#-N4XccAl7sUobPzqQm9q:-N4XmjkW2CAmSt6HzcYM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b22dec1a5b342288eaef4b71740fba3a00499746/tests/helgrind.supp#L403)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

missing new line at the end of the file
</blockquote></details>

Done.

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1837#-:-N4XnVnI03xQkBgVuxWl:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1837)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
