### PR TITLE
rpma: move description of thread safety to THREAD_SAFETY.md

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [ ] #1755 

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1758)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1758)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`src/include/librpma.h` line 320 at r1](https://reviewable.io/reviews/pmem/rpma/1758#-N2z1wJD00DzBr4ayp-G:-N2z1wJECmLaxyox8IMt:b-3p8zr1) ([raw file](https://github.com/pmem/rpma/blob/27c7d9e9fb49f842e7bc274fd02b5432a796df2e/src/include/librpma.h#L320)):*
> ```objc
>  *
>  * The analysis of thread safety of the librpma library is described in details
>  * in the THREAD_SAFETY.md file.
> ```

This section is used to produce librpma documentation:
https://pmem.io/rpma/manpages/master/librpma.7/
I think we need a full HTTP link to GitHub.



_Code quote:_
```objc
THREAD_SAFETY.md
```

**Review by osalyk — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1758)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1758)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72 and @osalyk)

___
*[`src/include/librpma.h` line 320 at r1](https://reviewable.io/reviews/pmem/rpma/1758#-N2z1wJD00DzBr4ayp-G:-N2z6RbD6z6ijqCx1VLm:biw8y1v) ([raw file](https://github.com/pmem/rpma/blob/27c7d9e9fb49f842e7bc274fd02b5432a796df2e/src/include/librpma.h#L320)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

This section is used to produce librpma documentation:
https://pmem.io/rpma/manpages/master/librpma.7/
I think we need a full HTTP link to GitHub.
</blockquote></details>

Right. Done.

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1758#-:-N2z94ENAPu22FqDhaN0:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1758#-:-N2zAr6s722oid2LSar4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

___
*[`src/include/librpma.h` line 320 at r1](https://reviewable.io/reviews/pmem/rpma/1758#-N2z1wJD00DzBr4ayp-G:-N2zAa5b3fx-z0dszyBY:b-va1n5i) ([raw file](https://github.com/pmem/rpma/blob/27c7d9e9fb49f842e7bc274fd02b5432a796df2e/src/include/librpma.h#L320)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Right. Done.
</blockquote></details>

It is OK for now. But we have to think of a long-term solution when we have different releases with different API call sets.

**Pull request merged**
