### PR TITLE
common: clean up lib.report.utils tests

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #1466 

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1464)

### CODE REVIEW

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1464#-:-MsAZ6Lq942j0la8hkin:bnfp4nl)* status: 0 of 4 files reviewed, all discussions resolved

**Review by grom72 — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1464)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1464)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1464)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
