### PR TITLE
tools: allow malloc for GPSPM persist mode

### PR DESCRIPTION
**Pull request by janekmi**
- following the FIO engines capabilities

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/780)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/780)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/780#-:-MS1u9YqDjjChQK5VYg_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/780)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/780)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
please rebase

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/780#-:-MS3Jj1Q72eUYkfjNMLR:bymv1jp)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/780)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/780#-:-MS3KxIT1Dn0PC5TTEIK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
