### PR TITLE
test: replace SUCCESS with MOCK_OK

### PR DESCRIPTION
**Pull request by yangx-jy**
Use unified MOCK_OK for return value.

Signed-off-by: Xiao Yang <yangx.jy@fujitsu.com>

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1024)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1024#-:-MZCxZqi2wIPKda3X9UG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1024#-:-MZDdLwV9vPKEjtDGGjc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1024)* status: all files reviewed, 3 unresolved discussions (waiting on @yangx-jy)

___
*[tests/unit/private_data/private_data-common.h, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1024#-MZXM64V-FK806VByHuz:-MZXM64W4aTw7o4WCeT6:bxth9aa) ([raw file](https://github.com/pmem/rpma/blob/d446d2763225e287adc01712629026a6de54ae60/tests/unit/private_data/private_data-common.h#L2)):*
> ```objc
> /* SPDX-License-Identifier: BSD-3-Clause */
> /* Copyright 2020, Intel Corporation */
> ```

2020-2021

FYI @ldorau @grom72 @osalyk for some reason this issue was not detected automatically.
___
*[tests/unit/private_data/private_data-common.c, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1024#-MZXNjda6r8syjuNlOhe:-MZXNjda6r8syjuNlOhf:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/d446d2763225e287adc01712629026a6de54ae60/tests/unit/private_data/private_data-common.c#L2)):*
> ```C
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2020, Intel Corporation */
> ```

.
___
*[tests/unit/private_data/private_data-store.c, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1024#-MZXNlD1-fERni6NPXn6:-MZXNlD1-fERni6NPXn7:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/d446d2763225e287adc01712629026a6de54ae60/tests/unit/private_data/private_data-store.c#L2)):*
> ```C
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2020, Intel Corporation */
> ```

.

**Review by yangx-jy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1024)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @janekmi, @osalyk, and @yangx-jy)

___
*[tests/unit/private_data/private_data-common.c, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1024#-MZXNjda6r8syjuNlOhe:-M_3QyHG83NwuY_mkug2:boxubp) ([raw file](https://github.com/pmem/rpma/blob/d446d2763225e287adc01712629026a6de54ae60/tests/unit/private_data/private_data-common.c#L2)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

I have added Fujitsu's Copyright.  Do I need to do anything else?
___
*[tests/unit/private_data/private_data-store.c, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1024#-MZXNlD1-fERni6NPXn6:-M_3RHjODwRBPhBIatZi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d446d2763225e287adc01712629026a6de54ae60/tests/unit/private_data/private_data-store.c#L2)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1024#-:-M_U-r7QD9WaAktxMj39:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Pull request merged**
