### PR TITLE
rpma: fix return value of rpma_mr_remote_from_descriptor()

### PR DESCRIPTION
**Pull request by ldorau**
... and a log message.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/380)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/380)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/mr.c, line 356 at r1](https://reviewable.io/reviews/pmem/rpma/380#-MGnXEgWE4XLGApibGIV:-MGnXEgWE4XLGApibGIW:b-fuggsl) ([raw file](https://github.com/pmem/rpma/blob/1477b4a7d755d77f5090e03c1b0c6d41564cade5/src/mr.c#L356)):*
> ```C
> 	if (plt != RPMA_MR_PLT_VOLATILE && plt != RPMA_MR_PLT_PERSISTENT) {
> 		RPMA_LOG_ERROR(
> 			"incorrect value of the kind of memory read from descriptor: %i",
> ```

incorrect value of the **memory placement** read from **the** descriptor

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/380)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[src/mr.c, line 356 at r1](https://reviewable.io/reviews/pmem/rpma/380#-MGnXEgWE4XLGApibGIV:-MGo6fXX-iCXAVE2auyl:bwwc8mh) ([raw file](https://github.com/pmem/rpma/blob/1477b4a7d755d77f5090e03c1b0c6d41564cade5/src/mr.c#L356)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

incorrect value of the **memory placement** read from **the** descriptor
</blockquote></details>

Exactly :-) Done.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/380#-:-MGqiHzdBD09FMcgP-sK:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/380#-:-MGqwh_-6fF8TbC2_vnr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
