### PR TITLE
common: disable TEST_PYTHON_TOOLS in Debian 9 and CentOS 7

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1388)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1388)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[.github/workflows/on_pull_request.yml, line 31 at r1](https://reviewable.io/reviews/pmem/rpma/1388#-Mpv2oRR548M2-VPgRhf:-Mpv2oRR548M2-VPgRhg:badj1pt) ([raw file](https://github.com/pmem/rpma/blob/a48a0516ffe21b177b9f6b8280978b6e93a3ba96/.github/workflows/on_pull_request.yml#L31)):*
> ```YAML
>                  "N=4 OS=fedora OS_VER=34    TYPE=normal CC=clang AUTO_DOC_UPDATE=1",
>                  # Debian 9 has older Python v3.5.3 (and pylint3 v1.6.5)
>                  "N=5 OS=debian OS_VER=9     TYPE=normal CC=gcc   PUSH_IMAGE=1  TEST_PYTHON_TOOLS=OFF"]
> ```

Why do we have Debian 9 here? xD

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1388)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[.github/workflows/on_pull_request.yml, line 31 at r1](https://reviewable.io/reviews/pmem/rpma/1388#-Mpv2oRR548M2-VPgRhf:-Mpv3y1x5XYz_5eCO6kd:bmvke0b) ([raw file](https://github.com/pmem/rpma/blob/a48a0516ffe21b177b9f6b8280978b6e93a3ba96/.github/workflows/on_pull_request.yml#L31)):*
> ```
> # Debian 9 has older Python v3.5.3 (and pylint3 v1.6.5)
> ```

Because of the above comment.
I can remove the pylint part now.

**Review by ldorau — COMMENTED** [review]
All builds pass now:
https://github.com/ldorau/rpma/actions/runs/1530444464
https://github.com/ldorau/rpma/actions/runs/1530475535

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1388#-:-Mpv4p8wCBtfZNqrc4ia:by2a5pf)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1388)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1388#-:-Mpv64tV0DZJVgeWTL0b:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1388)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[.github/workflows/on_pull_request.yml, line 31 at r1](https://reviewable.io/reviews/pmem/rpma/1388#-Mpv2oRR548M2-VPgRhf:-Mpv5vcq-Yue88FjzmtS:bn1qelp) ([raw file](https://github.com/pmem/rpma/blob/a48a0516ffe21b177b9f6b8280978b6e93a3ba96/.github/workflows/on_pull_request.yml#L31)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> # Debian 9 has older Python v3.5.3 (and pylint3 v1.6.5)
> ```

Because of the above comment.
I can remove the pylint part now.
</blockquote></details>

I think we can bump up the version. I recommend Debian 10. The oldest still supported.

EOL for Debian 9 was in January 2020.
Ref: https://endoflife.software/operating-systems/linux/debian

**Review by janekmi — APPROVED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1388#-:-Mpv6kKU2T8KGKlZenAX:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1388)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

___
*[.github/workflows/on_pull_request.yml, line 31 at r1](https://reviewable.io/reviews/pmem/rpma/1388#-Mpv2oRR548M2-VPgRhf:-Mpv6_vN3b6Q3zyYCgZy:b-kwfdga) ([raw file](https://github.com/pmem/rpma/blob/a48a0516ffe21b177b9f6b8280978b6e93a3ba96/.github/workflows/on_pull_request.yml#L31)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we can bump up the version. I recommend Debian 10. The oldest still supported.

EOL for Debian 9 was in January 2020.
Ref: https://endoflife.software/operating-systems/linux/debian
</blockquote></details>

Removing EOL OSes is another kind of change and I can do that in a separate PR.
This PR only adds `TEST_PYTHON_TOOLS=OFF`.

**Pull request merged**
