### PR TITLE
rpma: write the 'PEER' section of the librpma.7 manual

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/521)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/521)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[src/include/librpma.h, line 184 at r1](https://reviewable.io/reviews/pmem/rpma/521#-MIYqzDL6ipyF5kni_u9:-MIYqzDM9GRL-1TPIx0B:b-oc8oc2) ([raw file](https://github.com/pmem/rpma/blob/4d5396a07a617156deadbe9234f19ed64969b35c/src/include/librpma.h#L184)):*
> ```objc
>  * PEER
>  *
>  * Peer is a software abstraction representing an initiator or target node
> ```

Peer is a software abstraction representing the common context of all other structures used by librpma API.
As this structure is related most to ibv protection domain.

Peer allows us to initiate establishing a connection (as an active or passive side) , it also gave access for memory registration (via rpma_mr_reg().
To establish a connection on the passive side a listening end-point must be created - end-point waits for incoming connection requests which may be either accepted or rejected by the librpma user.
In case of active side a connection_request shall be created in the context of a peer() to maintain connection establish process.
___
*[src/include/librpma.h, line 187 at r1](https://reviewable.io/reviews/pmem/rpma/521#-MIZ-RPi0IShIUU3RfU4:-MIZ-RPi0IShIUU3RfU5:bftt53g) ([raw file](https://github.com/pmem/rpma/blob/4d5396a07a617156deadbe9234f19ed64969b35c/src/include/librpma.h#L187)):*
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>

> ```
> for the application using the librpma library for remote persistent
>  * memory access. Passive and active peers are distinguished.
>  * The passive peer is the one playing role of server – waiting for other
>  * peers to connect to (similar to socket listening for incoming connections).
>  * The active peer establishes a connection to the passive one
>  * (in a similar way to a socket connect()). Both peers can start
>  * any RDMA service as soon as a connection is established.
>  *
>  * At the beginning, in order to create a peer, a user has to obtain
>  * an RDMA device context by the given IPv4/IPv6 address using
>  * rpma_utils_get_ibv_context().
> ```
</details>

to be removed - peer in SAS is not exactly what peer in librpma.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/521)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[src/include/librpma.h, line 194 at r1](https://reviewable.io/reviews/pmem/rpma/521#-MIZ12_R-BHjd14oH3y_:-MIZ12_SAurYumPOC39s:b6s5uyl) ([raw file](https://github.com/pmem/rpma/blob/4d5396a07a617156deadbe9234f19ed64969b35c/src/include/librpma.h#L194)):*
> ```
>  * At the beginning, in order to create a peer, a user has to obtain
>  * an RDMA device context by the given IPv4/IPv6 address using
>  * rpma_utils_get_ibv_context(). Then a new peer object can be created
> ```
This section/paragraph is OK.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/521)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/include/librpma.h, line 184 at r1](https://reviewable.io/reviews/pmem/rpma/521#-MIYqzDL6ipyF5kni_u9:-MIZ1WJx0i7-Qy9aGDOg:b-ohtilg) ([raw file](https://github.com/pmem/rpma/blob/4d5396a07a617156deadbe9234f19ed64969b35c/src/include/librpma.h#L184)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Peer is a software abstraction representing the common context of all other structures used by librpma API.
As this structure is related most to ibv protection domain.

Peer allows us to initiate establishing a connection (as an active or passive side) , it also gave access for memory registration (via rpma_mr_reg().
To establish a connection on the passive side a listening end-point must be created - end-point waits for incoming connection requests which may be either accepted or rejected by the librpma user.
In case of active side a connection_request shall be created in the context of a peer() to maintain connection establish process.




</blockquote></details>

I like @grom72 version better. But I will have some comments... sec.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/521)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/include/librpma.h, line 184 at r1](https://reviewable.io/reviews/pmem/rpma/521#-MIYqzDL6ipyF5kni_u9:-MIZ2yjMDNE_8wOGBwVA:b-eahkzh) ([raw file](https://github.com/pmem/rpma/blob/4d5396a07a617156deadbe9234f19ed64969b35c/src/include/librpma.h#L184)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I like @grom72 version better. But I will have some comments... sec.
</blockquote></details>

A peer is an abstraction representing an RDMA-capable device. All other RPMA objects have to be created in the context of a peer.

A peer allows to:

- establishing connections (Client Operation)
- registering memory regions (Memory Management)
- creating endpoints for listening for incoming connections (Server Operation)
___
*[src/include/librpma.h, line 187 at r1](https://reviewable.io/reviews/pmem/rpma/521#-MIZ-RPi0IShIUU3RfU4:-MIZ3BPmCXHDbJA5L4BS:b-8fx2u7) ([raw file](https://github.com/pmem/rpma/blob/4d5396a07a617156deadbe9234f19ed64969b35c/src/include/librpma.h#L187)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> for the application using the librpma library for remote persistent
>  * memory access. Passive and active peers are distinguished.
>  * The passive peer is the one playing role of server – waiting for other
>  * peers to connect to (similar to socket listening for incoming connections).
>  * The active peer establishes a connection to the passive one
>  * (in a similar way to a socket connect()). Both peers can start
>  * any RDMA service as soon as a connection is established.
>  *
>  * At the beginning, in order to create a peer, a user has to obtain
>  * an RDMA device context by the given IPv4/IPv6 address using
>  * rpma_utils_get_ibv_context().
> ```
to be removed - peer in SAS is not exactly what peer in librpma.
</blockquote></details>

:+1: 
___
*[src/include/librpma.h, line 191 at r1](https://reviewable.io/reviews/pmem/rpma/521#-MIZ3F4K4B4VaL5uXW5Y:-MIZ3F4K4B4VaL5uXW5Z:b-vxm6cu) ([raw file](https://github.com/pmem/rpma/blob/4d5396a07a617156deadbe9234f19ed64969b35c/src/include/librpma.h#L191)):*
> ```objc
>  * The active peer establishes a connection to the passive one
>  * (in a similar way to a socket connect()). Both peers can start
>  * any RDMA service as soon as a connection is established.
> ```

As mentioned above. To be removed. Sorry. :-)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/521)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/521)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[src/include/librpma.h, line 184 at r1](https://reviewable.io/reviews/pmem/rpma/521#-MIYqzDL6ipyF5kni_u9:-MIZ5GjGBAXi9wv6gHvY:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4d5396a07a617156deadbe9234f19ed64969b35c/src/include/librpma.h#L184)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

A peer is an abstraction representing an RDMA-capable device. All other RPMA objects have to be created in the context of a peer.

A peer allows to:

- establishing connections (Client Operation)
- registering memory regions (Memory Management)
- creating endpoints for listening for incoming connections (Server Operation)
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 187 at r1](https://reviewable.io/reviews/pmem/rpma/521#-MIZ-RPi0IShIUU3RfU4:-MIZ57LtDnTtbhlnxCkL:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4d5396a07a617156deadbe9234f19ed64969b35c/src/include/librpma.h#L187)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 191 at r1](https://reviewable.io/reviews/pmem/rpma/521#-MIZ3F4K4B4VaL5uXW5Y:-MIZ57xdD58ynKpRBLRT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4d5396a07a617156deadbe9234f19ed64969b35c/src/include/librpma.h#L191)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

As mentioned above. To be removed. Sorry. :-)
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 194 at r1](https://reviewable.io/reviews/pmem/rpma/521#-MIZ12_R-BHjd14oH3y_:-MIZ58sVEFATGylDVuRu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4d5396a07a617156deadbe9234f19ed64969b35c/src/include/librpma.h#L194)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
>  * At the beginning, in order to create a peer, a user has to obtain
>  * an RDMA device context by the given IPv4/IPv6 address using
>  * rpma_utils_get_ibv_context(). Then a new peer object can be created
> ```
This section/paragraph is OK.
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/521#-:-MIZ5ctc-8sOlLeN9me3:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/521)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/521#-:-MIZ8erS7mPWPDs3zbdy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
