### PR TITLE
common: tools: RPMA read latency automat

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/607)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
please rebase

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/607#-:-MNTOXE53UJViEL2GPu8:bymv1jp)* status: 0 of 2 files reviewed, all discussions resolved

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/607)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tools/fio_jobs/librpma-client-read.fio, line 1 at r1](https://reviewable.io/reviews/pmem/rpma/607#-MNT_ODo1D_HG2HwmZn6:-MNT_ODp0EXAUeCgi1SI:bvplxy7) ([raw file](https://github.com/pmem/rpma/blob/e96eaee58dc4a7c8249bff7842d190f4647a396b/tools/fio_jobs/librpma-client-read.fio#L1)):*
> ```
> # The engine requires some options to work correctly:
> ```

The README file would be useful in this directory to explain what these files are for ...
___
*[tools/fio_jobs/librpma-client-read.fio, line 1 at r1](https://reviewable.io/reviews/pmem/rpma/607#-MNT_arJ8AkcsMI29UfW:-MNT_arK3irtAwPbRrsB:bm2eus0) ([raw file](https://github.com/pmem/rpma/blob/e96eaee58dc4a7c8249bff7842d190f4647a396b/tools/fio_jobs/librpma-client-read.fio#L1)):*
> ```
> The engine 
> ```

The librpma_client engine
___
*[tools/fio_jobs/librpma-server.fio, line 1 at r1](https://reviewable.io/reviews/pmem/rpma/607#-MNT_rQj23RGPbM8Ce7_:-MNT_rQj23RGPbM8Ce7a:b7g2ddc) ([raw file](https://github.com/pmem/rpma/blob/e96eaee58dc4a7c8249bff7842d190f4647a396b/tools/fio_jobs/librpma-server.fio#L1)):*
> ```
> The engine
> ```

The librpma_server engine

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/607)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi)

___
*[tools/rpma_read_lat.sh, line 10 at r1](https://reviewable.io/reviews/pmem/rpma/607#-MNTaaYV5g3-YeVE2G32:-MNTaaYV5g3-YeVE2G33:bq7d809) ([raw file](https://github.com/pmem/rpma/blob/e96eaee58dc4a7c8249bff7842d190f4647a396b/tools/rpma_read_lat.sh#L10)):*
> ```
> both server and the client
> ```

I would write: `both server and client`
___
*[tools/rpma_read_lat.sh, line 12 at r1](https://reviewable.io/reviews/pmem/rpma/607#-MNTaKAU61BdsYpaX-Yx:-MNTaKAU61BdsYpaX-Yy:bap5vkf) ([raw file](https://github.com/pmem/rpma/blob/e96eaee58dc4a7c8249bff7842d190f4647a396b/tools/rpma_read_lat.sh#L12)):*
> ```
> ...  with all
> # the resutls.
> ```

`... with all results.`

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/607)* status: all files reviewed, 7 unresolved discussions (waiting on @janekmi)

___
*[tools/rpma_read_lat.sh, line 81 at r1](https://reviewable.io/reviews/pmem/rpma/607#-MNTd9cY3PUvDL2xIVkn:-MNTd9cY3PUvDL2xIVko:b-4zusby) ([raw file](https://github.com/pmem/rpma/blob/e96eaee58dc4a7c8249bff7842d190f4647a396b/tools/rpma_read_lat.sh#L81)):*
> ```
>  "Error: FIO job failed"
> ```

`echo  ... `
___
*[tools/rpma_read_lat.sh, line 83 at r1](https://reviewable.io/reviews/pmem/rpma/607#-MNTcxxRCnPUj3YWG-hx:-MNTcxxSAlh6M6_q_L06:b-dftemw) ([raw file](https://github.com/pmem/rpma/blob/e96eaee58dc4a7c8249bff7842d190f4647a396b/tools/rpma_read_lat.sh#L83)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     [ "$?" -ne 0 ] && {
>         "Error: FIO job failed"
>         exit 1
>     }
> ```
</details>


```
if [ "$?" -ne 0 ]; then
        echo "Error: FIO job failed"
        exit 1
fi
```

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/607)* status: 1 of 5 files reviewed, 7 unresolved discussions (waiting on @ldorau)

___
*[tools/rpma_read_lat.sh, line 10 at r1](https://reviewable.io/reviews/pmem/rpma/607#-MNTaaYV5g3-YeVE2G32:-MNTgBVq19nx3DiFBHPd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e96eaee58dc4a7c8249bff7842d190f4647a396b/tools/rpma_read_lat.sh#L10)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> both server and the client
> ```

I would write: `both server and client`
</blockquote></details>

Done.
___
*[tools/rpma_read_lat.sh, line 12 at r1](https://reviewable.io/reviews/pmem/rpma/607#-MNTaKAU61BdsYpaX-Yx:-MNTgJ7mCdP6oGfYhD2y:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e96eaee58dc4a7c8249bff7842d190f4647a396b/tools/rpma_read_lat.sh#L12)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> ...  with all
> # the resutls.
> ```

`... with all results.`
</blockquote></details>

Done.
___
*[tools/rpma_read_lat.sh, line 81 at r1](https://reviewable.io/reviews/pmem/rpma/607#-MNTd9cY3PUvDL2xIVkn:-MNTgNAbCZlJ3Llqel0u:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e96eaee58dc4a7c8249bff7842d190f4647a396b/tools/rpma_read_lat.sh#L81)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  "Error: FIO job failed"
> ```

`echo  ... `
</blockquote></details>

Done.
___
*[tools/rpma_read_lat.sh, line 83 at r1](https://reviewable.io/reviews/pmem/rpma/607#-MNTcxxRCnPUj3YWG-hx:-MNTgTiC0cvw3Wg8tJyW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e96eaee58dc4a7c8249bff7842d190f4647a396b/tools/rpma_read_lat.sh#L83)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>     [ "$?" -ne 0 ] && {
>         "Error: FIO job failed"
>         exit 1
>     }
> ```

```
if [ "$?" -ne 0 ]; then
        echo "Error: FIO job failed"
        exit 1
fi
```

</blockquote></details>

Done.
___
*[tools/fio_jobs/librpma-client-read.fio, line 1 at r1](https://reviewable.io/reviews/pmem/rpma/607#-MNT_arJ8AkcsMI29UfW:-MNTetXP6PZZUqmv6hwb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e96eaee58dc4a7c8249bff7842d190f4647a396b/tools/fio_jobs/librpma-client-read.fio#L1)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> The engine 
> ```

The librpma_client engine
</blockquote></details>

Done.
___
*[tools/fio_jobs/librpma-client-read.fio, line 1 at r1](https://reviewable.io/reviews/pmem/rpma/607#-MNT_ODo1D_HG2HwmZn6:-MNTg1Cr-gIthENisGh1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e96eaee58dc4a7c8249bff7842d190f4647a396b/tools/fio_jobs/librpma-client-read.fio#L1)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The README file would be useful in this directory to explain what these files are for ...
</blockquote></details>

Done.
___
*[tools/fio_jobs/librpma-server.fio, line 1 at r1](https://reviewable.io/reviews/pmem/rpma/607#-MNT_rQj23RGPbM8Ce7_:-MNTewB30V0Uh83AGvrQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e96eaee58dc4a7c8249bff7842d190f4647a396b/tools/fio_jobs/librpma-server.fio#L1)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> The engine
> ```

The librpma_server engine
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/607)* status: 1 of 5 files reviewed, 8 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/rpma_read_lat.sh, line 10 at r2](https://reviewable.io/reviews/pmem/rpma/607#-MNTgrZ7CjYsJRa7lWR7:-MNTgrZ7CjYsJRa7lWR8:b-m5untl) ([raw file](https://github.com/pmem/rpma/blob/2c702faec04e841856b2775112ebc4be480152b7/tools/rpma_read_lat.sh#L10)):*
> ```
> multile
> ```
multiple

**Review by ldorau — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/607)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/607)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/607)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @ldorau and @osalyk)

___
*[tools/rpma_read_lat.sh, line 10 at r2](https://reviewable.io/reviews/pmem/rpma/607#-MNTgrZ7CjYsJRa7lWR7:-MNTj2TY29u8rerN-9yd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2c702faec04e841856b2775112ebc4be480152b7/tools/rpma_read_lat.sh#L10)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

> ```
> multile
> ```
multiple
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/607#-:-MNTjbr856-Kx-5rUPKH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/607#-:-MNTk_5S1SZRYGh2f_Yt:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/607)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
