### PR TITLE
tools: include Figure and Appendix titles into generated report figures

### PR DESCRIPTION
**Pull request by janekmi**
Requires:

- [x] #694

I see beautiful titles coming:

Figure_2_rpma_read_lat_vs_ib

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/704)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/704)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/create_report_figures.sh, line 209 at r1](https://reviewable.io/reviews/pmem/rpma/704#-MPiZYGb7mgKhnIz2Hd-:-MPiZYGb7mgKhnIz2Hd0:b-f8t8m9) ([raw file](https://github.com/pmem/rpma/blob/e7854351a9335ba496477caadcd4cdcea2fbc9dc/tools/create_report_figures.sh#L209)):*
> ```
> ib_read_lat
> ```
ib_read_lat from DRAM

**Review by grom72 — COMMENTED** [review]
Legend is too big ;)

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/704#-:-MPifgaL31AnTS-QB-O0:b5itnb6)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/704)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tools/create_report_figures.sh, line 68 at r1](https://reviewable.io/reviews/pmem/rpma/704#-MPjDOMR72LoXTz7bPkV:-MPjDOMR72LoXTz7bPkW:bk0klrp) ([raw file](https://github.com/pmem/rpma/blob/e7854351a9335ba496477caadcd4cdcea2fbc9dc/tools/create_report_figures.sh#L68)):*
> ```
>"Appendix $no. Complete statistics of $title collected from all of the platforms used"
> ```
"Appendix $no. Latency of <ib_read_lat|rpma_read()|...> for all used platforms"
___
*[tools/create_report_figures.sh, line 129 at r1](https://reviewable.io/reviews/pmem/rpma/704#-MPjDtUFAtThc0WgtSJC:-MPjDtUFAtThc0WgtSJD:b-paxkc9) ([raw file](https://github.com/pmem/rpma/blob/e7854351a9335ba496477caadcd4cdcea2fbc9dc/tools/create_report_figures.sh#L129)):*
> ```
> Complete statistics of $title collected from all of the platforms used
> ```
The bandwidth of $title for all used platforms

**Review by janekmi — COMMENTED** [review]
> Legend is too big ;)

No comments. :-P

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/704#-:-MPkLu3sCGTlMahZWURu:buai0os)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tools/create_report_figures.sh, line 68 at r1](https://reviewable.io/reviews/pmem/rpma/704#-MPjDOMR72LoXTz7bPkV:-MPkLynI7Xuehc6Z2_t0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e7854351a9335ba496477caadcd4cdcea2fbc9dc/tools/create_report_figures.sh#L68)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
>"Appendix $no. Complete statistics of $title collected from all of the platforms used"
> ```
"Appendix $no. Latency of <ib_read_lat|rpma_read()|...> for all used platforms"
</blockquote></details>

Done.
___
*[tools/create_report_figures.sh, line 129 at r1](https://reviewable.io/reviews/pmem/rpma/704#-MPjDtUFAtThc0WgtSJC:-MPkM-Zj59qSinBtJIuD:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e7854351a9335ba496477caadcd4cdcea2fbc9dc/tools/create_report_figures.sh#L129)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Complete statistics of $title collected from all of the platforms used
> ```
The bandwidth of $title for all used platforms
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/704)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[tools/create_report_figures.sh, line 209 at r1](https://reviewable.io/reviews/pmem/rpma/704#-MPiZYGb7mgKhnIz2Hd-:-MPkMRDI36h6Xks8rmIv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e7854351a9335ba496477caadcd4cdcea2fbc9dc/tools/create_report_figures.sh#L209)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> ib_read_lat
> ```
ib_read_lat from DRAM
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/704)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/create_report_figures.sh, line 112 at r2](https://reviewable.io/reviews/pmem/rpma/704#-MPmnYf427nyrT3M_ddi:-MPmnYf427nyrT3M_ddj:b-oqskns) ([raw file](https://github.com/pmem/rpma/blob/d10f6c6c951813c52966acf29f968a59587116ec/tools/create_report_figures.sh#L112)):*
> ```
> function bw_appendix()
> ```
It is almost the same as lat_appendinx.
Can we combine these two functions into one?
with arg_axis set to 'bs' in case of lat appendix.

**Review by grom72 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/704#-:-MPmoIHL-2yiEzjDH6Ly:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Pull request merged**
