### PR TITLE
examples: add script for running examples on SoftRoCE

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #265 

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/266)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
:teddy_bear: 

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/266#-:-MF25TxV7ha96PooBQAE:b-r1iuu2)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[examples/README, line 14 at r1](https://reviewable.io/reviews/pmem/rpma/266#-MF23ufV3S-GQatPX8Eb:-MF23ufW4-mmdFlf3bL-:b-f97vu9) ([raw file](https://github.com/pmem/rpma/blob/527f9899515107d54540208acceaa3a7b4e6819d/examples/README#L14)):*
> ```
> and the 'examples/run-all-on-SoftRoCE.sh' script
> for running all examples on SoftRoCE
> (it can be run using 'make test_softroce').
> ```

I think the make version should be referred similarity to the config_rxe in the #265  
___
*[examples/run-all-on-SoftRoCE.sh, line 16 at r1](https://reviewable.io/reviews/pmem/rpma/266#-MF24I2hB3s6s6EjXovh:-MF24I2hB3s6s6EjXovi:b-czavur) ([raw file](https://github.com/pmem/rpma/blob/527f9899515107d54540208acceaa3a7b4e6819d/examples/run-all-on-SoftRoCE.sh#L16)):*
> ```Shell
> 
> MODULE="rdma_rxe"
> SCRIPT="utils/rxe_config.sh"
> ```

**Just for the record**: you have to update the path.
___
*[examples/run-all-on-SoftRoCE.sh, line 52 at r1](https://reviewable.io/reviews/pmem/rpma/266#-MF24UIXD8cc41u8nx2Z:-MF24UIXD8cc41u8nx2_:b8uv1ar) ([raw file](https://github.com/pmem/rpma/blob/527f9899515107d54540208acceaa3a7b4e6819d/examples/run-all-on-SoftRoCE.sh#L52)):*
> ```Shell
> 	echo "Running examples for IP address $IP_ADDRESS and port $PORT:"
> 	echo
> }
> ```

This function seems to have a lot of code copied from config_rxe.sh. Maybe it is a better idea to make it a mode of the config_rxe.sh?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/266)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[examples/README, line 14 at r1](https://reviewable.io/reviews/pmem/rpma/266#-MF23ufV3S-GQatPX8Eb:-MF4L2vK7UqntyqOufUi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/527f9899515107d54540208acceaa3a7b4e6819d/examples/README#L14)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think the make version should be referred similarity to the config_rxe in the #265  
</blockquote></details>

Done.
___
*[examples/run-all-on-SoftRoCE.sh, line 16 at r1](https://reviewable.io/reviews/pmem/rpma/266#-MF24I2hB3s6s6EjXovh:-MF4LMmj73pspi1Fk76U:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/527f9899515107d54540208acceaa3a7b4e6819d/examples/run-all-on-SoftRoCE.sh#L16)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

**Just for the record**: you have to update the path.
</blockquote></details>

Done.
___
*[examples/run-all-on-SoftRoCE.sh, line 52 at r1](https://reviewable.io/reviews/pmem/rpma/266#-MF24UIXD8cc41u8nx2Z:-MF4jldxD-g2VBQAWOHQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/527f9899515107d54540208acceaa3a7b4e6819d/examples/run-all-on-SoftRoCE.sh#L52)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This function seems to have a lot of code copied from config_rxe.sh. Maybe it is a better idea to make it a mode of the config_rxe.sh?
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/266)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/266)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[examples/config_softroce.sh, line 75 at r2](https://reviewable.io/reviews/pmem/rpma/266#-MF67XAk-8jwAzWASJ_J:-MF67XAk-8jwAzWASJ_K:b-ryzbpq) ([raw file](https://github.com/pmem/rpma/blob/edf186c8a471111dfeaf1636d2ac15c948b52350/examples/config_softroce.sh#L75)):*
> ```Shell
> 		exit 1
> 	fi
> ```

Not needed new line?
___
*[examples/config_softroce.sh, line 79 at r2](https://reviewable.io/reviews/pmem/rpma/266#-MF67cjxBg_FoVi57qvm:-MF67cjxBg_FoVi57qvn:be714d4) ([raw file](https://github.com/pmem/rpma/blob/edf186c8a471111dfeaf1636d2ac15c948b52350/examples/config_softroce.sh#L79)):*
> ```Shell
> 
> echo "Configuring SoftRoCE for the '$LINK' network interface:"
> sudo rdma link add rxe_$LINK type rxe netdev $LINK
> ```

It seems you can reach this line in the verify mode. It is as intended?
___
*[examples/run-all-on-SoftRoCE.sh, line 30 at r2](https://reviewable.io/reviews/pmem/rpma/266#-MF67x3iEZdvpa0dKrsT:-MF67x3iEZdvpa0dKrsU:bg8mulw) ([raw file](https://github.com/pmem/rpma/blob/edf186c8a471111dfeaf1636d2ac15c948b52350/examples/run-all-on-SoftRoCE.sh#L30)):*
> ```Shell
> 	fi
> 
> 	echo "Running examples for IP address $IP_ADDRESS and port $PORT:"
> ```

':' at the end seems awkward.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/266)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[examples/config_softroce.sh, line 75 at r2](https://reviewable.io/reviews/pmem/rpma/266#-MF67XAk-8jwAzWASJ_J:-MF7_8cJ1KrZRwlWrfiL:ba3dfob) ([raw file](https://github.com/pmem/rpma/blob/edf186c8a471111dfeaf1636d2ac15c948b52350/examples/config_softroce.sh#L75)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not needed new line?
</blockquote></details>

Removed
___
*[examples/config_softroce.sh, line 79 at r2](https://reviewable.io/reviews/pmem/rpma/266#-MF67cjxBg_FoVi57qvm:-MF7ZeydAc23VVxAzzBw:b3r1ih3) ([raw file](https://github.com/pmem/rpma/blob/edf186c8a471111dfeaf1636d2ac15c948b52350/examples/config_softroce.sh#L79)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It seems you can reach this line in the verify mode. It is as intended?
</blockquote></details>

Yes, SoftRoCE will be configured if it has not been done yet.
___
*[examples/run-all-on-SoftRoCE.sh, line 30 at r2](https://reviewable.io/reviews/pmem/rpma/266#-MF67x3iEZdvpa0dKrsT:-MF7_NPVB-W7zqm4ugvN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/edf186c8a471111dfeaf1636d2ac15c948b52350/examples/run-all-on-SoftRoCE.sh#L30)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

':' at the end seems awkward.
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/266)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[examples/config_softroce.sh, line 79 at r2](https://reviewable.io/reviews/pmem/rpma/266#-MF67cjxBg_FoVi57qvm:-MF9OFej3uLf7aK9d33j:byit91s) ([raw file](https://github.com/pmem/rpma/blob/edf186c8a471111dfeaf1636d2ac15c948b52350/examples/config_softroce.sh#L79)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, SoftRoCE will be configured if it has not been done yet.
</blockquote></details>

For me, verify sounds as read-only mode. No changes should be made.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/266)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[examples/config_softroce.sh, line 79 at r2](https://reviewable.io/reviews/pmem/rpma/266#-MF67cjxBg_FoVi57qvm:-MF9TtqQ9LwG-QsFkVEY:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/edf186c8a471111dfeaf1636d2ac15c948b52350/examples/config_softroce.sh#L79)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

For me, verify sounds as read-only mode. No changes should be made.
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
:goat: 

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/266#-:-MF9WAsi5w2gIJ0_EZ9Z:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/266#-:-MF9bmoB2TDKkQhvM16X:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
