### PR TITLE
tools: csv compare legend entries has to match the CSV files

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/643)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/643#-:-MO5nyau2cH45dhWdKc-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/643)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/csv_compare.py, line 56 at r1](https://reviewable.io/reviews/pmem/rpma/643#-MO5nzWB09B7lsB4QUoz:-MO5nzWC6OQO55Qi3tDd:b-9i2w4i) ([raw file](https://github.com/pmem/rpma/blob/11bbfc855abc377a46f8a7db2452da1f7c983301/tools/csv_compare.py#L56)):*
> ```
> 'csv_files'
> ```

Shouldn't it be `'--csv_files'` ?

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/643#-:-MO6LyJP1Ag_gTRYinsv:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/643)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

___
*[tools/csv_compare.py, line 56 at r1](https://reviewable.io/reviews/pmem/rpma/643#-MO5nzWB09B7lsB4QUoz:-MO6MJKr2V9YAVHroqn1:b-rbt5u7) ([raw file](https://github.com/pmem/rpma/blob/11bbfc855abc377a46f8a7db2452da1f7c983301/tools/csv_compare.py#L56)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 'csv_files'
> ```

Shouldn't it be `'--csv_files'` ?
</blockquote></details>

I wanted to make the command line as short as possible so `csv_files` is a positional argument. Please see: https://docs.python.org/3/library/argparse.html#name-or-flags

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/643)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
