### PR TITLE
test: add MT test for rpma_ep_next_conn_req()

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1928)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1928)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1928)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`tests/multithreaded/ep/client_rpma_ep_next_conn_req.c` line 21 at r1](https://reviewable.io/reviews/pmem/rpma/1928#-N7QaOON-9gIWWhs37OE:-N7UHLeE0KuMInFfk2ax:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0c66d254653450ba30ecf18dac18cf03c1d5a5a5/tests/multithreaded/ep/client_rpma_ep_next_conn_req.c#L21)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

set private data and connect to a server
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1928)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[`tests/multithreaded/ep/rpma_ep_next_conn_req.c` line 142 at r3](https://reviewable.io/reviews/pmem/rpma/1928#-N7R9gs-9tGVwC1zsWqG:-N7UNuYE1cTn0-jhOrOV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/afe25cd65a6239716920392bbe0170701f8984dd/tests/multithreaded/ep/rpma_ep_next_conn_req.c#L142)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Is it OK as ``child_process_func`` is started before ``thread`` function?
I think we need some mechanism to postpone 
```
	switch ((pid = fork())) {
	case 0: /* this is the child */
		ret = child_process_func(prestate);
```
 until main threads are run
</blockquote></details>

Done.

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 1 of 2 files at r3, 3 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1928#-:-N7UdD6EAlY-XE6zqW00:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1928#-:-N7UeWdM5kZtp_ll3lRC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1928)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by Patryk717 — COMMENTED** [review]
:goat: 

> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1928#-:-N7VFvc255hv9NFNyyv-:bdycpsm)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @grom72 and @osalyk)

**Review by haichangsi — COMMENTED** [review]
Remember about changelog ;)

> Reviewed 1 of 4 files at r1, 1 of 2 files at r3, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1928#-:-N7VICdS36EvQVsG2Y3s:b6zdlx7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72 and @osalyk)

**Review by osalyk — APPROVED** [review]
> Reviewed 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1928)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — COMMENTED** [review]
@haichangsi Done

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1928#-:-N7VZ1D960LWWOdLPhCI:b-d33hx0)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @grom72)

**Review by haichangsi — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1928#-:-N7VZDu79QBTIUhfMqum:bnfp4nl)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
