### PR TITLE
example: add example 15

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1712)

### CODE REVIEW

**Review by osalyk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1712)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @haichangsi and @osalyk)

___
*[`examples/15-multiple-connections-SHCCH/client.c` line 6 at r1](https://reviewable.io/reviews/pmem/rpma/1712#-N0k-yLyBHL1QeZcp49S:-N0k-yLyBHL1QeZcp49T:bt25jge) ([raw file](https://github.com/pmem/rpma/blob/c874bf8265d7a306d2b3605915cbe3017b282fc7/examples/15-multiple-connections-SHCCH/client.c#L6)):*
> ```C
> /*
>  * client.c -- a client of the multiple-connections
>  * with shared completion channel example
> ```

Client does not use a shared completion channel
___
*[`examples/15-multiple-connections-SHCCH/server.c` line 23 at r1](https://reviewable.io/reviews/pmem/rpma/1712#-N0k-UsY3J57BcsSRF6d:-N0k-UsY3J57BcsSRF6e:bv2bax2) ([raw file](https://github.com/pmem/rpma/blob/c874bf8265d7a306d2b3605915cbe3017b282fc7/examples/15-multiple-connections-SHCCH/server.c#L23)):*
> ```C
> #include "common-conn.h"
> #include "common-epoll.h"
> #include "conn.h"
> ```

It's not needed
___
*[`examples/15-multiple-connections-SHCCH/server.c` line 373 at r1](https://reviewable.io/reviews/pmem/rpma/1712#-N0k-aGRBASy6RvxTIPy:-N0k-aGRBASy6RvxTIPz:byp18fd) ([raw file](https://github.com/pmem/rpma/blob/c874bf8265d7a306d2b3605915cbe3017b282fc7/examples/15-multiple-connections-SHCCH/server.c#L373)):*
> ```C
> 		return;
> ```

Remove

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1712)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[`examples/15-multiple-connections-SHCCH/client.c` line 6 at r1](https://reviewable.io/reviews/pmem/rpma/1712#-N0k-yLyBHL1QeZcp49S:-N0k9F9i9YBI-2VGgB2J:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c874bf8265d7a306d2b3605915cbe3017b282fc7/examples/15-multiple-connections-SHCCH/client.c#L6)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Client does not use a shared completion channel
</blockquote></details>

Done.
___
*[`examples/15-multiple-connections-SHCCH/server.c` line 23 at r1](https://reviewable.io/reviews/pmem/rpma/1712#-N0k-UsY3J57BcsSRF6d:-N0k9Fdk-7wJCpes-z98:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c874bf8265d7a306d2b3605915cbe3017b282fc7/examples/15-multiple-connections-SHCCH/server.c#L23)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

It's not needed
</blockquote></details>

Done.
___
*[`examples/15-multiple-connections-SHCCH/server.c` line 373 at r1](https://reviewable.io/reviews/pmem/rpma/1712#-N0k-aGRBASy6RvxTIPy:-N0k9Dom5W51DOa9yq1v:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c874bf8265d7a306d2b3605915cbe3017b282fc7/examples/15-multiple-connections-SHCCH/server.c#L373)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Remove
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1712)* status: all files reviewed, 4 unresolved discussions (waiting on @haichangsi and @osalyk)

___
*[`examples/15-multiple-connections-SHCCH/server.c` line 7 at r3](https://reviewable.io/reviews/pmem/rpma/1712#-N0kPH0WEbe8agTFh_Vy:-N0kPH0WEbe8agTFh_Vz:b-9t1hnd) ([raw file](https://github.com/pmem/rpma/blob/1f847ffa6604aec4f3bbfb55c6bc84d534c986d9/examples/15-multiple-connections-SHCCH/server.c#L7)):*
> ```C
> /*
>  * server.c -- a server of the multiple-connections
>  * with shared completion channel example
> ```

The limit is 100 chars now



_Code quote:_
```C
 * server.c -- a server of the multiple-connections
 * with shared completion channel example
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1712)* status: all files reviewed, 7 unresolved discussions (waiting on @haichangsi and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1712#-N0kTUpFCa6GL-tYTPbl:-N0kTUpFCa6GL-tYTPbm:b-5c8q31) (no related file):*
You have introduced a memleak:
```
==35992== 72 bytes in 3 blocks are definitely lost in loss record 29 of 41
==35992==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==35992==    by 0x484EEB9: rpma_conn_cfg_new (conn_cfg.c:106)
==35992==    by 0x10AED7: server_handle_incoming_client (server.c:372)
==35992==    by 0x10B1FD: main (server.c:472)
```
See: https://app.circleci.com/pipelines/github/pmem/rpma/1557/workflows/4052a949-9320-4694-96f9-8983787cfccf/jobs/1564

Please fix it.

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1712)* status: all files reviewed, 7 unresolved discussions (waiting on @haichangsi and @osalyk)

___
*[`examples/15-multiple-connections-SHCCH/server.c` line 219 at r3](https://reviewable.io/reviews/pmem/rpma/1712#-N0kSnelCR4GXI4sWk8S:-N0oHHK42jpmTuc2KRr4:bbv1wz1) ([raw file](https://github.com/pmem/rpma/blob/1f847ffa6604aec4f3bbfb55c6bc84d534c986d9/examples/15-multiple-connections-SHCCH/server.c#L219)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`clnt->cq` should not be modified here.
</blockquote></details>

I meant you should use a new local variable for this cq.

**Review by osalyk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1712)* status: all files reviewed, 5 unresolved discussions (waiting on @haichangsi)

___
*[`examples/15-multiple-connections-SHCCH/server.c` line 375 at r3](https://reviewable.io/reviews/pmem/rpma/1712#-N0oT6UwBYkZZSyj0GFO:-N0oT6UwBYkZZSyj0GFP:bcggvgq) ([raw file](https://github.com/pmem/rpma/blob/1f847ffa6604aec4f3bbfb55c6bc84d534c986d9/examples/15-multiple-connections-SHCCH/server.c#L375)):*
> ```C
> 		return;
> 
> 	if (rpma_conn_cfg_set_compl_channel(svr->cfg, true))
> ```

Move this to server_init()



_Code quote:_
```C
	svr->cfg = NULL;
	if (rpma_conn_cfg_new(&svr->cfg))
		return;

	if (rpma_conn_cfg_set_compl_channel(svr->cfg, true))
		return;
```

**Review by osalyk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1712)* status: all files reviewed (commit messages unreviewed), 8 unresolved discussions (waiting on @haichangsi)

___
*[`examples/15-multiple-connections-SHCCH/server.c` line 92 at r4](https://reviewable.io/reviews/pmem/rpma/1712#-N0oodLG4vjQcau2cKfN:-N0oodLG4vjQcau2cKfO:b-4l2l9a) ([raw file](https://github.com/pmem/rpma/blob/938acabed9b8816a6940e8eb17277aca11feeaf8/examples/15-multiple-connections-SHCCH/server.c#L92)):*
> ```C
> 	svr->cfg = NULL;
> 	if ((ret = rpma_conn_cfg_new(&svr->cfg)))
> 		return ret;
> ```

Be sure to free up resources
___
*[`examples/15-multiple-connections-SHCCH/server.c` line 95 at r4](https://reviewable.io/reviews/pmem/rpma/1712#-N0ooe5d1Kodru6cTaqO:-N0ooe5eEOAHOOopvCIm:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/938acabed9b8816a6940e8eb17277aca11feeaf8/examples/15-multiple-connections-SHCCH/server.c#L95)):*
> ```C
> 
> 	if ((ret = rpma_conn_cfg_set_compl_channel(svr->cfg, true)))
> 		return ret;
> ```

.
___
*[`examples/15-multiple-connections-SHCCH/server.c` line 240 at r4](https://reviewable.io/reviews/pmem/rpma/1712#-N0oo8nA2zIW0Zt6W3Su:-N0oo8nA2zIW0Zt6W3Sv:b9tarvo) ([raw file](https://github.com/pmem/rpma/blob/938acabed9b8816a6940e8eb17277aca11feeaf8/examples/15-multiple-connections-SHCCH/server.c#L240)):*
> ```C
> 	/* get next completion */
> 	struct ibv_wc wc;
> 	ret = rpma_cq_get_wc(clnt->cq, 1, &wc, NULL);
> ```

Use local variable (cq)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1712)* status: all files reviewed (commit messages unreviewed), 9 unresolved discussions (waiting on @haichangsi)

___
*[`examples/15-multiple-connections-SHCCH/server.c` line 113 at r4](https://reviewable.io/reviews/pmem/rpma/1712#-N0opEhJ76gcTOWWZ_cw:-N0opEhJ76gcTOWWZ_cx:bku8bq5) ([raw file](https://github.com/pmem/rpma/blob/938acabed9b8816a6940e8eb17277aca11feeaf8/examples/15-multiple-connections-SHCCH/server.c#L113)):*
> ```C
> 
> 	/* delete connection configuration */
> 	ret = rpma_conn_cfg_delete(&svr->cfg);
> ```

Move to the top.

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1712)* status: 1 of 2 files reviewed, 9 unresolved discussions (waiting on @ldorau and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1712#-N0kTUpFCa6GL-tYTPbl:-N0opijMAHvnCNxL2z3G:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

You have introduced a memleak:
```
==35992== 72 bytes in 3 blocks are definitely lost in loss record 29 of 41
==35992==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==35992==    by 0x484EEB9: rpma_conn_cfg_new (conn_cfg.c:106)
==35992==    by 0x10AED7: server_handle_incoming_client (server.c:372)
==35992==    by 0x10B1FD: main (server.c:472)
```
See: https://app.circleci.com/pipelines/github/pmem/rpma/1557/workflows/4052a949-9320-4694-96f9-8983787cfccf/jobs/1564

Please fix it.
</blockquote></details>

Done.

---
___
*[`examples/15-multiple-connections-SHCCH/server.c` line 7 at r3](https://reviewable.io/reviews/pmem/rpma/1712#-N0kPH0WEbe8agTFh_Vy:-N0oWyZl26Jru98o5nyA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1f847ffa6604aec4f3bbfb55c6bc84d534c986d9/examples/15-multiple-connections-SHCCH/server.c#L7)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The limit is 100 chars now
</blockquote></details>

Done.
___
*[`examples/15-multiple-connections-SHCCH/server.c` line 219 at r3](https://reviewable.io/reviews/pmem/rpma/1712#-N0kSnelCR4GXI4sWk8S:-N0og84V42QoklpJTmD4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1f847ffa6604aec4f3bbfb55c6bc84d534c986d9/examples/15-multiple-connections-SHCCH/server.c#L219)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I meant you should use a new local variable for this cq.
</blockquote></details>

Done.
___
*[`examples/15-multiple-connections-SHCCH/server.c` line 226 at r3](https://reviewable.io/reviews/pmem/rpma/1712#-N0kT4-bB6Ue-30XreVM:-N0ol2_93OliejLI1AD5:b7sydyq) ([raw file](https://github.com/pmem/rpma/blob/1f847ffa6604aec4f3bbfb55c6bc84d534c986d9/examples/15-multiple-connections-SHCCH/server.c#L226)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why have changed that?
</blockquote></details>

I wanted to do here things we take care of in client_handle_connection_event(). It is not necessary here. Done.
___
*[`examples/15-multiple-connections-SHCCH/server.c` line 375 at r3](https://reviewable.io/reviews/pmem/rpma/1712#-N0oT6UwBYkZZSyj0GFO:-N0o_Tua1j2TNUJofpt2:b-mp7ily) ([raw file](https://github.com/pmem/rpma/blob/1f847ffa6604aec4f3bbfb55c6bc84d534c986d9/examples/15-multiple-connections-SHCCH/server.c#L375)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Move this to server_init()
</blockquote></details>

Yeah, I saw that myself, one goto could cause a memory leak. Thanks. Done.
___
*[`examples/15-multiple-connections-SHCCH/server.c` line 92 at r4](https://reviewable.io/reviews/pmem/rpma/1712#-N0oodLG4vjQcau2cKfN:-N0osYbF9g83L6oodojj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/938acabed9b8816a6940e8eb17277aca11feeaf8/examples/15-multiple-connections-SHCCH/server.c#L92)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Be sure to free up resources
</blockquote></details>

Done.
___
*[`examples/15-multiple-connections-SHCCH/server.c` line 95 at r4](https://reviewable.io/reviews/pmem/rpma/1712#-N0ooe5d1Kodru6cTaqO:-N0osIAT4k8I0tJmpTq_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/938acabed9b8816a6940e8eb17277aca11feeaf8/examples/15-multiple-connections-SHCCH/server.c#L95)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`examples/15-multiple-connections-SHCCH/server.c` line 113 at r4](https://reviewable.io/reviews/pmem/rpma/1712#-N0opEhJ76gcTOWWZ_cw:-N0osXc21np4aekPn5un:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/938acabed9b8816a6940e8eb17277aca11feeaf8/examples/15-multiple-connections-SHCCH/server.c#L113)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Move to the top. 
</blockquote></details>

Done.
___
*[`examples/15-multiple-connections-SHCCH/server.c` line 240 at r4](https://reviewable.io/reviews/pmem/rpma/1712#-N0oo8nA2zIW0Zt6W3Su:-N0oqQ9HBBl2JjEyvv80:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/938acabed9b8816a6940e8eb17277aca11feeaf8/examples/15-multiple-connections-SHCCH/server.c#L240)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Use local variable (cq)
</blockquote></details>

Done.

**Review by osalyk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1712)* status: all files reviewed, 8 unresolved discussions (waiting on @haichangsi, @ldorau, and @osalyk)

___
*[`examples/15-multiple-connections-SHCCH/server.c` line 92 at r4](https://reviewable.io/reviews/pmem/rpma/1712#-N0oodLG4vjQcau2cKfN:-N0ou9Ng2ZvqWrmsUuiv:br7sr4m) ([raw file](https://github.com/pmem/rpma/blob/938acabed9b8816a6940e8eb17277aca11feeaf8/examples/15-multiple-connections-SHCCH/server.c#L92)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet
___
*[`examples/15-multiple-connections-SHCCH/server.c` line 111 at r5](https://reviewable.io/reviews/pmem/rpma/1712#-N0ou-D9AuUi7em_aGYd:-N0ou-D9AuUi7em_aGYe:b-357oad) ([raw file](https://github.com/pmem/rpma/blob/e37e693af114e07bd929599a61f9ca348842af8a/examples/15-multiple-connections-SHCCH/server.c#L111)):*
> ```C
> {
> 	/* delete connection configuration */
> 	ret = rpma_conn_cfg_delete(&svr->cfg);
> ```

int ret
___
*[`examples/15-multiple-connections-SHCCH/server.c` line 114 at r5](https://reviewable.io/reviews/pmem/rpma/1712#-N0ou1MQ1mWF5F7m43PY:-N0ou1MR1eiE48ssWN5P:b2nibgc) ([raw file](https://github.com/pmem/rpma/blob/e37e693af114e07bd929599a61f9ca348842af8a/examples/15-multiple-connections-SHCCH/server.c#L114)):*
> ```C
> 
> 	/* deregister the memory region */
> 	int ret = rpma_mr_dereg(&svr->dst_mr);
> ```

ret

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1712)* status: 1 of 2 files reviewed, 8 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[`examples/15-multiple-connections-SHCCH/server.c` line 92 at r4](https://reviewable.io/reviews/pmem/rpma/1712#-N0oodLG4vjQcau2cKfN:-N0ow6f8EAW0NLKhOr_l:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/938acabed9b8816a6940e8eb17277aca11feeaf8/examples/15-multiple-connections-SHCCH/server.c#L92)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Not yet
</blockquote></details>

Done.
___
*[`examples/15-multiple-connections-SHCCH/server.c` line 111 at r5](https://reviewable.io/reviews/pmem/rpma/1712#-N0ou-D9AuUi7em_aGYd:-N0ow8Vf-kvnKISb5DmU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e37e693af114e07bd929599a61f9ca348842af8a/examples/15-multiple-connections-SHCCH/server.c#L111)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

int ret
</blockquote></details>

Done.
___
*[`examples/15-multiple-connections-SHCCH/server.c` line 114 at r5](https://reviewable.io/reviews/pmem/rpma/1712#-N0ou1MQ1mWF5F7m43PY:-N0ow8nW86YDIoavqYq-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e37e693af114e07bd929599a61f9ca348842af8a/examples/15-multiple-connections-SHCCH/server.c#L114)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

ret
</blockquote></details>

Done.

**Review by osalyk — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1712)* status: 1 of 2 files reviewed, 6 unresolved discussions (waiting on @haichangsi, @ldorau, and @osalyk)

___
*[`examples/15-multiple-connections-SHCCH/server.c` line 94 at r6](https://reviewable.io/reviews/pmem/rpma/1712#-N0ox1Go4yK2kTRbqHEh:-N0ox1Go4yK2kTRbqHEi:b67r4hu) ([raw file](https://github.com/pmem/rpma/blob/68d127bdd91946026c84339da6f6642f714ba0d6/examples/15-multiple-connections-SHCCH/server.c#L94)):*
> ```C
> 		rpma_mr_dereg(&svr->dst_mr);
> 		free(svr->dst_ptr);
> 		close(svr->epoll);
> ```

Please change to:
ret = rpma_conn_cfg_new(&svr->cfg);
if (ret) {
    ...
}



_Code quote:_
```C
	if ((ret = rpma_conn_cfg_new(&svr->cfg))) {
		rpma_mr_dereg(&svr->dst_mr);
		free(svr->dst_ptr);
		close(svr->epoll);
		return ret;
```
___
*[`examples/15-multiple-connections-SHCCH/server.c` line 100 at r6](https://reviewable.io/reviews/pmem/rpma/1712#-N0oxAr0A0otLRkZQKpa:-N0oxAr0A0otLRkZQKpb:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/68d127bdd91946026c84339da6f6642f714ba0d6/examples/15-multiple-connections-SHCCH/server.c#L100)):*
> ```C
> 	if ((ret = rpma_conn_cfg_set_compl_channel(svr->cfg, true))) {
> 		rpma_conn_cfg_delete(&svr->cfg);
> 		rpma_mr_dereg(&svr->dst_mr);
> ```

.



_Code quote:_
```C
	if ((ret = rpma_conn_cfg_set_compl_channel(svr->cfg, true))) {
		rpma_conn_cfg_delete(&svr->cfg);
		rpma_mr_dereg(&svr->dst_mr);
		free(svr->dst_ptr);
		close(svr->epoll);
		return ret;
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1712)* status: 1 of 2 files reviewed, 6 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[`examples/15-multiple-connections-SHCCH/server.c` line 94 at r6](https://reviewable.io/reviews/pmem/rpma/1712#-N0ox1Go4yK2kTRbqHEh:-N0oyJ0k1hLWe3fulFHW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/68d127bdd91946026c84339da6f6642f714ba0d6/examples/15-multiple-connections-SHCCH/server.c#L94)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Please change to:
ret = rpma_conn_cfg_new(&svr->cfg);
if (ret) {
    ...
}
</blockquote></details>

Done.
___
*[`examples/15-multiple-connections-SHCCH/server.c` line 100 at r6](https://reviewable.io/reviews/pmem/rpma/1712#-N0oxAr0A0otLRkZQKpa:-N0oyJfkCWi_RsCTRPQz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/68d127bdd91946026c84339da6f6642f714ba0d6/examples/15-multiple-connections-SHCCH/server.c#L100)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by osalyk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1712)* status: all files reviewed, 7 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[`examples/15-multiple-connections-SHCCH/server.c` line 87 at r7](https://reviewable.io/reviews/pmem/rpma/1712#-N0oz0UO4ZynDWwJ4Xy1:-N0oz0UO4ZynDWwJ4Xy2:bpspk79) ([raw file](https://github.com/pmem/rpma/blob/a56c0fae8a82069217d1564eb053796732824903/examples/15-multiple-connections-SHCCH/server.c#L87)):*
> ```C
> 	if (ret) {
> 		free(svr->dst_ptr);
> 		close(svr->epoll);
> ```

return ret;
___
*[`examples/15-multiple-connections-SHCCH/server.c` line 91 at r7](https://reviewable.io/reviews/pmem/rpma/1712#-N0ozWUY9Ut1dHwvkjo1:-N0ozWUY9Ut1dHwvkjo2:b5cyrh7) ([raw file](https://github.com/pmem/rpma/blob/a56c0fae8a82069217d1564eb053796732824903/examples/15-multiple-connections-SHCCH/server.c#L91)):*
> ```C
> 
> 	svr->cfg = NULL;
> 	ret = rpma_conn_cfg_new(&svr->cfg);
> ```

Add comment
___
*[`examples/15-multiple-connections-SHCCH/server.c` line 105 at r7](https://reviewable.io/reviews/pmem/rpma/1712#-N0ozBW42bRajay1bPP3:-N0ozBW42bRajay1bPP4:b-s3hmk9) ([raw file](https://github.com/pmem/rpma/blob/a56c0fae8a82069217d1564eb053796732824903/examples/15-multiple-connections-SHCCH/server.c#L105)):*
> ```C
> 		free(svr->dst_ptr);
> 		close(svr->epoll);
> 		return ret;
> ```

Not needed.

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1712)* status: 1 of 2 files reviewed, 7 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[`examples/15-multiple-connections-SHCCH/server.c` line 87 at r7](https://reviewable.io/reviews/pmem/rpma/1712#-N0oz0UO4ZynDWwJ4Xy1:-N0p-196DUofgHx-ry92:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a56c0fae8a82069217d1564eb053796732824903/examples/15-multiple-connections-SHCCH/server.c#L87)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

return ret;
</blockquote></details>

Done.
___
*[`examples/15-multiple-connections-SHCCH/server.c` line 91 at r7](https://reviewable.io/reviews/pmem/rpma/1712#-N0ozWUY9Ut1dHwvkjo1:-N0p-mlx-Au-gQP95rP2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a56c0fae8a82069217d1564eb053796732824903/examples/15-multiple-connections-SHCCH/server.c#L91)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Add comment
</blockquote></details>

Done.
___
*[`examples/15-multiple-connections-SHCCH/server.c` line 105 at r7](https://reviewable.io/reviews/pmem/rpma/1712#-N0ozBW42bRajay1bPP3:-N0p-0aF5SmFdjPxKL-l:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a56c0fae8a82069217d1564eb053796732824903/examples/15-multiple-connections-SHCCH/server.c#L105)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Not needed.
</blockquote></details>

Done.

**Review by osalyk — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1712)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1712#-:-N0p1Mbs1uq4fe_BSvZ6:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1712)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[`examples/15-multiple-connections-SHCCH/server.c` line 96 at r8](https://reviewable.io/reviews/pmem/rpma/1712#-N0pDHML9-ty91vyT6j3:-N0pDHML9-ty91vyT6j4:b-stxv9k) ([raw file](https://github.com/pmem/rpma/blob/f6a55bf8a5a0ad7068ba1cf79f925c460dbd61c3/examples/15-multiple-connections-SHCCH/server.c#L96)):*
> ```C
> 	if (ret) {
> 		rpma_mr_dereg(&svr->dst_mr);
> 		free(svr->dst_ptr);
> ```

Please change error handling in the whole functions to goto-labels like in other places.



_Code quote:_
```C
	/* create connection configuration */
	svr->cfg = NULL;
	ret = rpma_conn_cfg_new(&svr->cfg);
	if (ret) {
		rpma_mr_dereg(&svr->dst_mr);
		free(svr->dst_ptr);
		close(svr->epoll);
		return ret;
	}

	ret = rpma_conn_cfg_set_compl_channel(svr->cfg, true);
	if (ret) {
		rpma_conn_cfg_delete(&svr->cfg);
		rpma_mr_dereg(&svr->dst_mr);
		free(svr->dst_ptr);
		close(svr->epoll);
	}
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1712)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1712#-N1CvdKz50gJZnakDhEv:-N1CvdKz50gJZnakDhEw:b-y3zpa1) (no related file):*
```
*** Running example: 15-multiple-connections-SHCCH 
Starting the server ...
May 02 19:37:54.725215 [35106] *NOTE*  ep.c:  92: rpma_ep_listen: Waiting for incoming connection on 172.28.30.185:7204
free(): double free detected in tcache 2
../examples/run-all-on-SoftRoCE.sh: line 77: 35106 Aborted                 (core dumped) $VLD_SCMD $DIR/server $IP_ADDRESS $PORT
```
https://app.circleci.com/pipelines/github/pmem/rpma/1567/workflows/a9d7a254-2f07-4603-8326-31d23fbd6b06/jobs/1574

---

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1712)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72 and @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1712#-:-N1D7241D0ujgaym9WZA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72 and @osalyk)

**Review by osalyk — APPROVED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1712)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1712#-:-N1DoSqx3jVQzqQCX-NA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1712)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
