### PR TITLE
[WIP] tools: Runner with common set log file name

### PR DESCRIPTION
**Pull request by grom72**
set_log_file_name moved to Runner class

- [x] #1452 
- [x] #1453 
- [ ] #1454 
- [x] #1455
- [ ] #1456 
- [ ] #1469 
- [ ] #1458

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1459)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1459)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by Patryk717 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1459#-:-Ms4Vl573eIGFnZk1qaM:bdycpsm)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1459)* status: 0 of 18 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1459)* status: 0 of 21 files reviewed, all discussions resolved (waiting on @ldorau)

**Comment by ldorau** [comment]
Postponed

**Pull request closed without merging**
