### PR TITLE
common: print out why pushing the image has been skipped

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/2065)

### CODE REVIEW

**Review by osalyk — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2065)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[`utils/docker/pull-or-rebuild-image.sh` line 41 at r1](https://reviewable.io/reviews/pmem/rpma/2065#-NG0mRQ06sgZNg0Vuy8U:-NG0mRQ06sgZNg0Vuy8V:bt0toaa) ([raw file](https://github.com/pmem/rpma/blob/2d1d9572c9e217cad8b12422b1934661611d219b/utils/docker/pull-or-rebuild-image.sh#L41)):*
> ```Shell
> 	# of the "pull_request" type). In that case, create the empty
> 	# file.
> 	if [[ "${CI_REPO_SLUG}" == "${GITHUB_REPO}" && "$CI_BRANCH" == "master" \
> ```

Shouldn't it be changed to main?



_Suggestion:_
```Shell
main
```
___
*[`utils/docker/pull-or-rebuild-image.sh` line 52 at r1](https://reviewable.io/reviews/pmem/rpma/2065#-NG0mXFv04Ml3d_9iSdZ:-NG0mXFv04Ml3d_9iSd_:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/2d1d9572c9e217cad8b12422b1934661611d219b/utils/docker/pull-or-rebuild-image.sh#L52)):*
> ```Shell
> 			echo "GITHUB_REPO=$GITHUB_REPO"
> 		fi
> 		[ "$CI_BRANCH" != "master" ] && echo "CI_BRANCH=$CI_BRANCH"
> ```

.



_Code quote:_
```Shell
master
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2065)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[`utils/docker/pull-or-rebuild-image.sh` line 41 at r1](https://reviewable.io/reviews/pmem/rpma/2065#-NG0mRQ06sgZNg0Vuy8U:-NG0q9g-EAyk7b8bcrQo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2d1d9572c9e217cad8b12422b1934661611d219b/utils/docker/pull-or-rebuild-image.sh#L41)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Shouldn't it be changed to main?
</blockquote></details>

Done.
___
*[`utils/docker/pull-or-rebuild-image.sh` line 52 at r1](https://reviewable.io/reviews/pmem/rpma/2065#-NG0mXFv04Ml3d_9iSdZ:-NG0qAqu0GqEKd4lvMHT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2d1d9572c9e217cad8b12422b1934661611d219b/utils/docker/pull-or-rebuild-image.sh#L52)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2065#-:-NG0roCe5rskYS4EB11D:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2065)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2065#-:-NG17h166TXycOqVBuWE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
