### PR TITLE
common: pass conn_cfg via peer_create_qp()

### PR DESCRIPTION
**Pull request by janekmi**
Requires:
- [x] #337 
- [x] #331
- [x] #338
- [x] #339

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/340)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 41 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/340)* status: 1 of 6 files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/340)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tests/unit/peer/peer-create_qp.c, line 21 at r2](https://reviewable.io/reviews/pmem/rpma/340#-MGIbNBc8ok6LZOLNITC:-MGIbNBc8ok6LZOLNITD:bov5upz) ([raw file](https://github.com/pmem/rpma/blob/f25e9a9e0ad0789f4a2e46f582896b9ae7de68eb/tests/unit/peer/peer-create_qp.c#L21)):*
> ```C
> #include "test-common.h"
> 
> struct conn_cfg_get_q_size_mock_args Get_sq_size = {
> ```

static

If https://github.com/pmem/rpma/pull/308 were merged it would be detected automatically ...
___
*[tests/unit/peer/peer-create_qp.c, line 26 at r2](https://reviewable.io/reviews/pmem/rpma/340#-MGIb_QR7yf8xthyWwSC:-MGIb_QR7yf8xthyWwSD:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/f25e9a9e0ad0789f4a2e46f582896b9ae7de68eb/tests/unit/peer/peer-create_qp.c#L26)):*
> ```C
> };
> 
> struct conn_cfg_get_q_size_mock_args Get_rq_size = {
> ```

.

**Review by grom72 — COMMENTED** [review]
> Reviewed 5 of 41 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/340)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[src/peer.c, line 51 at r2](https://reviewable.io/reviews/pmem/rpma/340#-MGIcQj2BPjATIPbbgTS:-MGIcQj2BPjATIPbbgTT:b-53on1g) ([raw file](https://github.com/pmem/rpma/blob/f25e9a9e0ad0789f4a2e46f582896b9ae7de68eb/src/peer.c#L51)):*
> ```
> (void) rpma_conn_cfg_get_sq_size
> ```
is there any other place where we check getter result?
if no I suggest converting  rpma_conn_cfg_get_sq_size(...) to uint32_t rpma_conn_cfg_get_sq_size(cfg)

**Review by osalyk — COMMENTED** [review]
> Reviewed 1 of 41 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/340)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by ldorau — COMMENTED** [review]
> Reviewed 5 of 41 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/340)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/340)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/peer.c, line 51 at r2](https://reviewable.io/reviews/pmem/rpma/340#-MGIcQj2BPjATIPbbgTS:-MGItOgACo2Ugq6vWvXB:b9p2jhd) ([raw file](https://github.com/pmem/rpma/blob/f25e9a9e0ad0789f4a2e46f582896b9ae7de68eb/src/peer.c#L51)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> (void) rpma_conn_cfg_get_sq_size
> ```
is there any other place where we check getter result?
if no I suggest converting  rpma_conn_cfg_get_sq_size(...) to uint32_t rpma_conn_cfg_get_sq_size(cfg)
</blockquote></details>

It is part of public API. We can not do this, otherwise we have no option to return an error.
___
*[tests/unit/peer/peer-create_qp.c, line 21 at r2](https://reviewable.io/reviews/pmem/rpma/340#-MGIbNBc8ok6LZOLNITC:-MGItil91er_jcl1igNp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f25e9a9e0ad0789f4a2e46f582896b9ae7de68eb/tests/unit/peer/peer-create_qp.c#L21)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

static

If https://github.com/pmem/rpma/pull/308 were merged it would be detected automatically ...
</blockquote></details>

Done.
___
*[tests/unit/peer/peer-create_qp.c, line 26 at r2](https://reviewable.io/reviews/pmem/rpma/340#-MGIb_QR7yf8xthyWwSC:-MGItk4u4YUFRv-fRySN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f25e9a9e0ad0789f4a2e46f582896b9ae7de68eb/tests/unit/peer/peer-create_qp.c#L26)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/340)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/peer.c, line 51 at r2](https://reviewable.io/reviews/pmem/rpma/340#-MGIcQj2BPjATIPbbgTS:-MGIu3Ps88iWPEZnHHIq:b361hxr) ([raw file](https://github.com/pmem/rpma/blob/f25e9a9e0ad0789f4a2e46f582896b9ae7de68eb/src/peer.c#L51)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is part of public API. We can not do this, otherwise we have no option to return an error.
</blockquote></details>

Hmmm OK - let's take a look at this next sprint

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/340#-:-MGIx40j-5Gcl0rjr-9h:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/340#-:-MGIx9ndD7MU4feTUaXg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:goat: 

> Reviewed 1 of 41 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/340#-:-MGIypXG13qoyTbGaLMX:b6e9vsk)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
