### PR TITLE
rpma: remove rpma_write_atomic()

### PR DESCRIPTION
**Pull request by ldorau**
1) Remove `rpma_write_atomic()`.
`rpma_write_atomic()` has been replaced with `rpma_atomic_write()`  .

2) Remove `bool fence` argument from `rpma_mr_write()`.
The `bool fence` argument of `rpma_mr_write()` has not been used
since `rpma_write_atomic()` was removed, so this argument can be
removed too.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1618)

### CODE REVIEW

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1618#-:-MxnvUWBBL8wM7lT4PuS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Comment by ldorau** [comment]
1) Remove `rpma_write_atomic()`.
`rpma_write_atomic()` has been replaced with `rpma_atomic_write()`  .

2) Remove `bool fence` argument from `rpma_mr_write()`.
The `bool fence` argument of `rpma_mr_write()` has not been used
since `rpma_write_atomic()` was removed, so this argument can be
removed too.

**Review by grom72 — APPROVED** [review]
> Reviewed 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1618)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1618)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 4 of 14 files at r1, 7 of 8 files at r3, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1618#-:-My6NJYy0qa6qCfecpze:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
