### PR TITLE
tools: introduce create_report_figures.sh

### PR DESCRIPTION
**Pull request by janekmi**
Output:

```
report_CUSTOM_STAMP
├── 02_read_lat
│   ├── Appendix_B1_ib_read_lat.png
│   ├── Appendix_B2_rpma_read_lat_DRAM.png
│   ├── Appendix_B3_rpma_read_lat_PMEM.png
│   └── Figure_2_3_4_rpma_read_lat_vs_ib.png
├── 03_read_bw_bs
│   ├── Appendix_C1_ib_read_bw_bs.png
│   ├── Appendix_C2_rpma_read_bw_bs_dram.png
│   ├── Appendix_C3_rpma_read_bw_bs_pmem.png
│   └── Figure_5_rpma_read_bw_bs_vs_ib.png
└── 04_read_bw_th
    ├── Appendix_D1_ib_read_bw_th.png
    ├── Appendix_D2_rpma_read_bw_th_dram.png
    ├── Appendix_D3_rpma_read_bw_th_pmem.png
    └── Figure_6_rpma_read_bw_th_vs_ib.png
```
Input:
```
data_path
└── READ
    ├── MACHINE_A
    │   ├── DRAM
    │   │   ├── BIOS_mem_BW
    │   │   │   └── CSV
    │   │   │       ├── ib_read_bw-bs-1th-20-12-10-151006.csv
    │   │   │       ├── ib_read_bw-dp-4096bs-20-12-14-112159.csv
    │   │   │       ├── ib_read_bw-dp-exp-4096bs-20-12-15-102316.csv
    │   │   │       ├── ib_read_bw-dp-lin-4096bs-20-12-15-103624.csv
    │   │   │       ├── ib_read_bw-th-4096bs-20-12-10-143552.csv
    │   │   │       ├── rpma_fio_read_bw-bs-20-12-10-145053.csv
    │   │   │       ├── rpma_fio_read_bw-dp-20-12-14-111020.csv
    │   │   │       ├── rpma_fio_read_bw-dp-exp-20-12-15-105735_dram.csv
    │   │   │       ├── rpma_fio_read_bw-dp-exp-20-12-15-112746_dram.csv
    │   │   │       ├── rpma_fio_read_bw-dp-lin-20-12-15-113839_dram.csv
    │   │   │       └── rpma_fio_read_bw-th-20-12-10-151804.csv
    │   │   └── BIOS_mem_LAT
    │   │       └── CSV
    │   │           ├── ib_read_lat-20-12-10-110138.csv
    │   │           └── rpma_fio_read_lat-20-12-10-111654.csv
    │   └── PMEM
    │       └── BIOS_mem_BW
    │           └── CSV
    │               ├── rpma_fio_read_bw-bs-20-12-14-103055.csv
    │               ├── rpma_fio_read_bw-dp-20-12-14-105404.csv
    │               ├── rpma_fio_read_bw-dp-exp-20-12-15-115724_pmem.csv
    │               ├── rpma_fio_read_bw-dp-lin-20-12-15-120845_pmem.csv
    │               ├── rpma_fio_read_bw-th-20-12-14-103931.csv
    │               └── rpma_fio_read_lat-20-12-14-110446.csv
    ├── MACHINE_B
    │   ├── DRAM
    │   │   └── BIOS_mam_LAT
    │   │       └── CSV
    │   │           ├── ib_read_bw-bs-1th-20-12-10-155301.csv
    │   │           ├── ib_read_bw-dp-exp-4096bs-20-12-15-114354.csv
    │   │           ├── ib_read_bw-dp-lin-4096bs-20-12-15-113354.csv
    │   │           ├── ib_read_bw-th-4096bs-20-12-10-155558.csv
    │   │           ├── ib_read_lat-20-12-10-154941.csv
    │   │           ├── rpma_fio_read_bw-bs-20-12-10-161457.csv
    │   │           ├── rpma_fio_read_bw-dp-exp-20-12-15-120429.csv
    │   │           ├── rpma_fio_read_bw-dp-lin-20-12-15-115132.csv
    │   │           ├── rpma_fio_read_bw-th-20-12-10-162442.csv
    │   │           └── rpma_fio_read_lat-20-12-10-161037.csv
    │   └── PMEM
    │       └── BIOS_mem_LAT
    │           └── CSV
    │               ├── rpma_fio_read_bw-bs-20-12-14-124247.csv
    │               ├── rpma_fio_read_bw-dp-exp-20-12-15-122747.csv
    │               ├── rpma_fio_read_bw-dp-exp-20-12-15-125212.csv
    │               ├── rpma_fio_read_bw-dp-lin-20-12-15-121451.csv
    │               ├── rpma_fio_read_bw-dp-lin-20-12-15-131516.csv
    │               ├── rpma_fio_read_bw-th-20-12-14-115006.csv
    │               ├── rpma_fio_read_bw-th-20-12-14-122732.csv
    │               └── rpma_fio_read_lat-20-12-14-113257.csv
    └── MACHINE_C
        ├── DRAM
        │   └── BIOS_mem_LAT
        │       └── CSV
        │           ├── ib_read_bw-bs-1th-20-12-14-084743.csv
        │           ├── ib_read_bw-dp-exp-4096bs-20-12-15-050237.csv
        │           ├── ib_read_bw-dp-lin-4096bs-20-12-15-051027.csv
        │           ├── ib_read_bw-th-4096bs-20-12-14-085028.csv
        │           ├── ib_read_lat-20-12-14-084430.csv
        │           ├── rpma_fio_read_bw-bs-20-12-14-082110.csv
        │           ├── rpma_fio_read_bw-dp-exp-20-12-15-052231.csv
        │           ├── rpma_fio_read_bw-dp-lin-20-12-15-053302.csv
        │           ├── rpma_fio_read_bw-th-20-12-14-082739.csv
        │           └── rpma_fio_read_lat-20-12-14-081717.csv
        └── PMEM
            └── BIOS_mem_LAT
                └── CSV
                    ├── rpma_fio_read_bw-bs-20-12-14-092710.csv
                    ├── rpma_fio_read_bw-dp-exp-20-12-15-054628.csv
                    ├── rpma_fio_read_bw-dp-lin-20-12-15-055708.csv
                    ├── rpma_fio_read_bw-th-20-12-14-093339.csv
                    └── rpma_fio_read_lat-20-12-14-092316.csv
```

This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/675)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/675)* status: 1 of 2 files reviewed, all discussions resolved

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/675)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/create_report_figures.sh, line 24 at r2](https://reviewable.io/reviews/pmem/rpma/675#-MOjdJuX1uLf2fqbrwfJ:-MOjdJuX1uLf2fqbrwfK:bm03rl4) ([raw file](https://github.com/pmem/rpma/blob/a908ef4e0b0470c6152e3e6236e79058b60b36bb/tools/create_report_figures.sh#L24)):*
> ```
>     echo "export LAT_MACHINE=NAME_OF_THE_MACHINE"
>     echo "export BW_MACHINE=NAME_OF_THE_MACHINE"
> ```

What are they ? An explanation, please
___
*[tools/create_report_figures.sh, line 107 at r2](https://reviewable.io/reviews/pmem/rpma/675#-MOjcFST758jap1ZF1FI:-MOjcFST758jap1ZF1FJ:b-bhnpo6) ([raw file](https://github.com/pmem/rpma/blob/a908ef4e0b0470c6152e3e6236e79058b60b36bb/tools/create_report_figures.sh#L107)):*
> ```
> mkdir 02_read_lat
> cd 02_read_lat
> ```

`02` - magic number ? 
Why does numbering start from `02`?

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/675)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tools/create_report_figures.sh, line 30 at r2](https://reviewable.io/reviews/pmem/rpma/675#-MOjjlAc-rtzIxYMqaCe:-MOjjlAc-rtzIxYMqaCf:b-zo2pr) ([raw file](https://github.com/pmem/rpma/blob/a908ef4e0b0470c6152e3e6236e79058b60b36bb/tools/create_report_figures.sh#L30)):*
> ```
> if [ "$#" -ne "0" ]; then
>     usage "too many arguments"
> fi
> ```

I propose to require one argument: `DATA_PATH=/custom/data/path`and print the usage if no argument is given.

At this moment - if no argument is given - a few screens of stack traces errors are printed out - it does not look good.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/675)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tools/create_report_figures.sh, line 111 at r2](https://reviewable.io/reviews/pmem/rpma/675#-MOjmXE51IxeICd0XIH-:-MOjmXE51IxeICd0XIH0:b-ahibcx) ([raw file](https://github.com/pmem/rpma/blob/a908ef4e0b0470c6152e3e6236e79058b60b36bb/tools/create_report_figures.sh#L111)):*
> ```
> lat_figure 
> ```

I receive such warning on each call to `lat_figure `:

```
rpma/tools/csv_compare.py:254: UserWarning: Tight layout not applied. tight_layout cannot make axes width small enough to accommodate all axes decorations
  plt.savefig(args.output_file)
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/675)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[tools/create_report_figures.sh, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/675#-MOjmyx123zSAffLWN1t:-MOjmyx123zSAffLWN1u:bk9ktf4) ([raw file](https://github.com/pmem/rpma/blob/a908ef4e0b0470c6152e3e6236e79058b60b36bb/tools/create_report_figures.sh#L15)):*
> ```
> function usage()
> ```

Where is the output report saved?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/675)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[tools/create_report_figures.sh, line 111 at r2](https://reviewable.io/reviews/pmem/rpma/675#-MOjmXE51IxeICd0XIH-:-MOk5apM3GAXwV_KA5d0:bmzwxri) ([raw file](https://github.com/pmem/rpma/blob/a908ef4e0b0470c6152e3e6236e79058b60b36bb/tools/create_report_figures.sh#L111)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> lat_figure 
> ```

I receive such warning on each call to `lat_figure `:

```
rpma/tools/csv_compare.py:254: UserWarning: Tight layout not applied. tight_layout cannot make axes width small enough to accommodate all axes decorations
  plt.savefig(args.output_file)
```
</blockquote></details>

It disappeared after renaming machines' directories to `MACHINE_X_Y`

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/675)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/create_report_figures.sh, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/675#-MOjmyx123zSAffLWN1t:-MOkDgSYEhj_Yzv4SDTT:b-bgfrt8) ([raw file](https://github.com/pmem/rpma/blob/a908ef4e0b0470c6152e3e6236e79058b60b36bb/tools/create_report_figures.sh#L15)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> function usage()
> ```

Where is the output report saved?
</blockquote></details>

Here is no report created. Only the figures. There are stored in the report_$STAMP directory next to the tool itself.
___
*[tools/create_report_figures.sh, line 30 at r2](https://reviewable.io/reviews/pmem/rpma/675#-MOjjlAc-rtzIxYMqaCe:-MOkE3CtEfqyNOOXpxCy:b2739y) ([raw file](https://github.com/pmem/rpma/blob/a908ef4e0b0470c6152e3e6236e79058b60b36bb/tools/create_report_figures.sh#L30)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> if [ "$#" -ne "0" ]; then
>     usage "too many arguments"
> fi
> ```

I propose to require one argument: `DATA_PATH=/custom/data/path`and print the usage if no argument is given.

At this moment - if no argument is given - a few screens of stack traces errors are printed out - it does not look good.

</blockquote></details>

As a regular user of this script, I do not like passing the data directory over and over again.

No errors anymore. SKIPS at most.
___
*[tools/create_report_figures.sh, line 107 at r2](https://reviewable.io/reviews/pmem/rpma/675#-MOjcFST758jap1ZF1FI:-MOkEaZW4SgrQzQaatYF:b13wl55) ([raw file](https://github.com/pmem/rpma/blob/a908ef4e0b0470c6152e3e6236e79058b60b36bb/tools/create_report_figures.sh#L107)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> mkdir 02_read_lat
> cd 02_read_lat
> ```

`02` - magic number ? 
Why does numbering start from `02`?
</blockquote></details>

Yes. This is a magic number. This script is aimed to build figures for the report and it assumes a specific structure of the report. So the first figure it generates is the second in the report. I do not want to generalize this script now.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/675)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/create_report_figures.sh, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/675#-MOjmyx123zSAffLWN1t:-MOkNXZk666hOGBXneTi:b-f40kji) ([raw file](https://github.com/pmem/rpma/blob/a908ef4e0b0470c6152e3e6236e79058b60b36bb/tools/create_report_figures.sh#L15)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Here is no report created. Only the figures. There are stored in the report_$STAMP directory next to the tool itself.
</blockquote></details>

I meant to add info about it to this help message.
___
*[tools/create_report_figures.sh, line 30 at r2](https://reviewable.io/reviews/pmem/rpma/675#-MOjjlAc-rtzIxYMqaCe:-MOkNmeS7kQTdF9giuCE:b32w0x) ([raw file](https://github.com/pmem/rpma/blob/a908ef4e0b0470c6152e3e6236e79058b60b36bb/tools/create_report_figures.sh#L30)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

As a regular user of this script, I do not like passing the data directory over and over again.

No errors anymore. SKIPS at most.
</blockquote></details>

OK
___
*[tools/create_report_figures.sh, line 107 at r2](https://reviewable.io/reviews/pmem/rpma/675#-MOjcFST758jap1ZF1FI:-MOkNwYYAC5RVC8X5pj0:b32w0x) ([raw file](https://github.com/pmem/rpma/blob/a908ef4e0b0470c6152e3e6236e79058b60b36bb/tools/create_report_figures.sh#L107)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Yes. This is a magic number. This script is aimed to build figures for the report and it assumes a specific structure of the report. So the first figure it generates is the second in the report. I do not want to generalize this script now.
</blockquote></details>

OK

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/675)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tools/create_report_figures.sh, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/675#-MOjmyx123zSAffLWN1t:-MOkQ-YZ6SiyfvugxHBl:bhcohwf) ([raw file](https://github.com/pmem/rpma/blob/a908ef4e0b0470c6152e3e6236e79058b60b36bb/tools/create_report_figures.sh#L15)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I meant to add info about it to this help message.
</blockquote></details>

Even better. I have added the information to the standard output. I think you will like it.
___
*[tools/create_report_figures.sh, line 24 at r2](https://reviewable.io/reviews/pmem/rpma/675#-MOjdJuX1uLf2fqbrwfJ:-MOkOpZGEtghqV1Zl1MW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a908ef4e0b0470c6152e3e6236e79058b60b36bb/tools/create_report_figures.sh#L24)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>     echo "export LAT_MACHINE=NAME_OF_THE_MACHINE"
>     echo "export BW_MACHINE=NAME_OF_THE_MACHINE"
> ```

What are they ? An explanation, please
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/675#-:-MOkaNnvCq8c7aCGxIY0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
