### PR TITLE
doc: add a reference to BENCHMARKING.md Requirements section

### PR DESCRIPTION
**Pull request by grom72**
Components needed to use benchmurking tools are also required
for benchmarking tools development

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1431)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1431)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1431#-:-Mr6YpF5CGkAFz88WtXv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1431)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/pmem/rpma/1431#-Mr6srC88S0kyB3vI790):*
benchmarking * if it matters

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1431)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1431)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @haichangsi)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/pmem/rpma/1431#-Mr6srC88S0kyB3vI790):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

benchmarking * if it matters
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1431)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1431)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[tools/perf/CONTRIBUTING.md, line 9 at r2](https://reviewable.io/reviews/pmem/rpma/1431#-Mr7c4Nz9uxhZfhOj0HJ:-Mr7c4Nz9uxhZfhOj0HK:befiy3b) ([raw file](https://github.com/pmem/rpma/blob/aae3f899fa2f85042afe4f015ffa30338e693d2b/tools/perf/CONTRIBUTING.md#L9)):*
> ```Markdown
> ## Prerequisites
> 
> Before you start developing performance tools, ensure that you have installed all components required to run tools as it is described in
> ```

the performance tools



_Code quote:_
```Markdown
performance tools
```
___
*[tools/perf/CONTRIBUTING.md, line 9 at r2](https://reviewable.io/reviews/pmem/rpma/1431#-Mr7c8fs6YiYQYsXJXTN:-Mr7c8fs6YiYQYsXJXTO:bo8qd6a) ([raw file](https://github.com/pmem/rpma/blob/aae3f899fa2f85042afe4f015ffa30338e693d2b/tools/perf/CONTRIBUTING.md#L9)):*
> ```Markdown
> ## Prerequisites
> 
> Before you start developing performance tools, ensure that you have installed all components required to run tools as it is described in
> ```

run the tools



_Code quote:_
```Markdown
run tools
```

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1431)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)

___
*[tools/perf/CONTRIBUTING.md, line 9 at r2](https://reviewable.io/reviews/pmem/rpma/1431#-Mr7c4Nz9uxhZfhOj0HJ:-Mr7e7Od5xAB_ky_K24D:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/aae3f899fa2f85042afe4f015ffa30338e693d2b/tools/perf/CONTRIBUTING.md#L9)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

the performance tools
</blockquote></details>

Done.
___
*[tools/perf/CONTRIBUTING.md, line 9 at r2](https://reviewable.io/reviews/pmem/rpma/1431#-Mr7c8fs6YiYQYsXJXTN:-Mr7eFdt7bQCGtNfTHC9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/aae3f899fa2f85042afe4f015ffa30338e693d2b/tools/perf/CONTRIBUTING.md#L9)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

run the tools
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1431)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @haichangsi and @ldorau)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1431#-:-Mr7eYzZ4XqAgWwin9OZ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1431)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1431)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1431)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[-- commits, line 4 at r1](https://reviewable.io/reviews/pmem/rpma/1431#-Mr6srC88S0kyB3vI790):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Fixed :lgtm:

**Pull request merged**
