### PR TITLE
doc: add SEE ALSO section (completion, err, log)

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/496)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/496)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[src/include/librpma.h, line 2128 at r1](https://reviewable.io/reviews/pmem/rpma/496#-MITb7fz4bX2ukm8yWM3:-MITb7fz4bX2ukm8yWM4:bpxck4d) ([raw file](https://github.com/pmem/rpma/blob/645d8732a5258576571922f48dba3ba86287c046/src/include/librpma.h#L2128)):*
> ```objc
>  *
>  * SEE ALSO
>  * rpma_log_set_function(3), rpma_log_set_threshold(3) and https://pmem.io/rpma/
> ```

get_threshold

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/496)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[src/include/librpma.h, line 2128 at r1](https://reviewable.io/reviews/pmem/rpma/496#-MITb7fz4bX2ukm8yWM3:-MITq-A76Stme0K35NzA:bvpibix) ([raw file](https://github.com/pmem/rpma/blob/645d8732a5258576571922f48dba3ba86287c046/src/include/librpma.h#L2128)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

get_threshold
</blockquote></details>

Is a description of the get_threshold() function

**Review by janekmi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/496#-:-MITrlU7AzCM7AORS4n9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/496#-:-MITxCAK0CnZkLd_ILuo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
