### PR TITLE
test: add rpma_conn_cfg_get_timeout multithreaded test

### PR DESCRIPTION
**Pull request by ewanglong**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1103)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1103)* status: all files reviewed, 3 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/conn/rpma_conn_cfg_get_timeout.c, line 5 at r1](https://reviewable.io/reviews/pmem/rpma/1103#-McxhUbw3LdJX-xp1lbG:-McxhUbw3LdJX-xp1lbH:b-qgerp1) ([raw file](https://github.com/pmem/rpma/blob/29bb54eb793cc1cd0c0da3719d079aca581d0608/tests/multithreaded/conn/rpma_conn_cfg_get_timeout.c#L5)):*
> ```
>  * rpma_conn_cfg_get_rq_size.c -- rpma_conn_cfg_get_rq_size multithreaded test
> ```

`rpma_conn_cfg_get_timeout` 2 times
___
*[tests/multithreaded/conn/rpma_conn_cfg_get_timeout.c, line 16 at r1](https://reviewable.io/reviews/pmem/rpma/1103#-McxhbpM0oFQ1Ves94gJ:-McxhbpM0oFQ1Ves94gK:b-1p02ev) ([raw file](https://github.com/pmem/rpma/blob/29bb54eb793cc1cd0c0da3719d079aca581d0608/tests/multithreaded/conn/rpma_conn_cfg_get_timeout.c#L16)):*
> ```
> struct prestate {
> 	struct rpma_conn_cfg *cfg_ptr;
> };
> ```

Move it to the common header, please.
___
*[tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c, line 57 at r1](https://reviewable.io/reviews/pmem/rpma/1103#-McxhLkJ-mLyyCb4IjVb:-McxhLkJ-mLyyCb4IjVc:b-rvz3od) ([raw file](https://github.com/pmem/rpma/blob/0b2e66d7427af34ed87c6a7db15e934f43b80ff6/tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c#L57)):*
> ```
>  "rpma_conn_cfg_set_timeout",
> ```

Please move this fix to a separate PR

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1103)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/conn/rpma_conn_cfg_get_timeout.c, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1103#-McxlWt16jGBxPB_7Gob:-McxlWt16jGBxPB_7Goc:b-5d7mn2) ([raw file](https://github.com/pmem/rpma/blob/29bb54eb793cc1cd0c0da3719d079aca581d0608/tests/multithreaded/conn/rpma_conn_cfg_get_timeout.c#L13)):*
> ```C
> #include "mtt.h"
> 
> #define TIMEOUT_MS_EXP 2000
> ```

This is also used by more than one test. Please make it common.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1103)* status: all files reviewed, 5 unresolved discussions (waiting on @ewanglong)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1103#-MdRqVZg7FoEmLA10TzU:-MdRqVZg7FoEmLA10TzV:b-n6khor) (no related file):*
Please rebase

---

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1103)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1103#-MdRqVZg7FoEmLA10TzU:-MdUsZhc-qDp0IDLmqWv:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please rebase
</blockquote></details>

Done.

---
___
*[tests/multithreaded/conn/rpma_conn_cfg_get_timeout.c, line 5 at r1](https://reviewable.io/reviews/pmem/rpma/1103#-McxhUbw3LdJX-xp1lbG:-MdUs_W577l9EdVfJXS7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/29bb54eb793cc1cd0c0da3719d079aca581d0608/tests/multithreaded/conn/rpma_conn_cfg_get_timeout.c#L5)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  * rpma_conn_cfg_get_rq_size.c -- rpma_conn_cfg_get_rq_size multithreaded test
> ```

`rpma_conn_cfg_get_timeout` 2 times
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_cfg_get_timeout.c, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1103#-McxlWt16jGBxPB_7Gob:-MdUrVNKER8s0KWukkk6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/29bb54eb793cc1cd0c0da3719d079aca581d0608/tests/multithreaded/conn/rpma_conn_cfg_get_timeout.c#L13)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This is also used by more than one test. Please make it common.
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_cfg_get_timeout.c, line 16 at r1](https://reviewable.io/reviews/pmem/rpma/1103#-McxhbpM0oFQ1Ves94gJ:-MdUrWjVBEdWXcibzr1Y:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/29bb54eb793cc1cd0c0da3719d079aca581d0608/tests/multithreaded/conn/rpma_conn_cfg_get_timeout.c#L16)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> struct prestate {
> 	struct rpma_conn_cfg *cfg_ptr;
> };
> ```

Move it to the common header, please.

</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c, line 57 at r1](https://reviewable.io/reviews/pmem/rpma/1103#-McxhLkJ-mLyyCb4IjVb:-MdUsa30B2hfCBapFjOK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0b2e66d7427af34ed87c6a7db15e934f43b80ff6/tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c#L57)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  "rpma_conn_cfg_set_timeout",
> ```

Please move this fix to a separate PR
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1103)* status: all files reviewed, 3 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/multithreaded/conn/rpma_conn_cfg_get_timeout.c, line 5 at r1](https://reviewable.io/reviews/pmem/rpma/1103#-McxhUbw3LdJX-xp1lbG:-MdVS6m77z9LFJs7R_K_:br7sr4m) ([raw file](https://github.com/pmem/rpma/blob/29bb54eb793cc1cd0c0da3719d079aca581d0608/tests/multithreaded/conn/rpma_conn_cfg_get_timeout.c#L5)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1103)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tests/multithreaded/conn/rpma_conn_cfg_get_timeout.c, line 5 at r1](https://reviewable.io/reviews/pmem/rpma/1103#-McxhUbw3LdJX-xp1lbG:-MdVfTPf7VOFOb4ww_Ba:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/29bb54eb793cc1cd0c0da3719d079aca581d0608/tests/multithreaded/conn/rpma_conn_cfg_get_timeout.c#L5)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not yet
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1103)* status: all files reviewed, 3 unresolved discussions (waiting on @ewanglong and @ldorau)

___
*[tests/multithreaded/conn/rpma_conn_cfg_get_timeout.c, line 15 at r3](https://reviewable.io/reviews/pmem/rpma/1103#-MdVhwq7D5ZCEcxQwyz8:-MdVhwq7D5ZCEcxQwyz9:bdt2occ) ([raw file](https://github.com/pmem/rpma/blob/4aeb284ae78c5d6fd79689a3294cb0d44b1e0a99/tests/multithreaded/conn/rpma_conn_cfg_get_timeout.c#L15)):*
> ```C
> 
> /*
>  * thread -- get connection configured cq size and check if its value is
> ```

timeout
___
*[tests/multithreaded/conn/rpma_conn_cfg_get_timeout.c, line 22 at r3](https://reviewable.io/reviews/pmem/rpma/1103#-MdVhtS3-JaWIf2g07FM:-MdVhtS3-JaWIf2g07FN:b-sc901q) ([raw file](https://github.com/pmem/rpma/blob/4aeb284ae78c5d6fd79689a3294cb0d44b1e0a99/tests/multithreaded/conn/rpma_conn_cfg_get_timeout.c#L22)):*
> ```C
> {
> 	struct rpma_conn_cfg_common_prestate *pr =
> 	(struct rpma_conn_cfg_common_prestate *)prestate;
> ```

Indentation +1

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1103)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tests/multithreaded/conn/rpma_conn_cfg_get_timeout.c, line 15 at r3](https://reviewable.io/reviews/pmem/rpma/1103#-MdVhwq7D5ZCEcxQwyz8:-MdVjNE83inN6d0cT74B:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4aeb284ae78c5d6fd79689a3294cb0d44b1e0a99/tests/multithreaded/conn/rpma_conn_cfg_get_timeout.c#L15)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

timeout
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_cfg_get_timeout.c, line 22 at r3](https://reviewable.io/reviews/pmem/rpma/1103#-MdVhtS3-JaWIf2g07FM:-MdVjNzZBLVTHXriUYFo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4aeb284ae78c5d6fd79689a3294cb0d44b1e0a99/tests/multithreaded/conn/rpma_conn_cfg_get_timeout.c#L22)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Indentation +1
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1103#-:-MdWCSoA6oYXxmIfux0m:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1103#-:-MdXEEg1EQdTtIs5YSI1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1103)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Pull request merged**
