### PR TITLE
tools: update ib_read.sh to measure bandwidth vs data size and threads

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/624)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/624)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[tools/ib_read.sh, line 83 at r1](https://reviewable.io/reviews/pmem/rpma/624#-MNxBDF0B8qEIlRt88tn:-MNxBDF0B8qEIlRt88to:b-bwf0xj) ([raw file](https://github.com/pmem/rpma/blob/b01e9ed8e76f2a328ad80173c71b762d58f21a8f/tools/ib_read.sh#L83)):*
> ```Shell
> 	NAME="${MODE}-${THREADS}th"
> 	verify_data_size
> 	verify_indexes
> ```

I do not like the idea of having an array of natural number 1..N. It can be easily generated ad hoc: `seq 1 $N` e.g.:

```sh
DATA_SIZE=(256 1024 4096 8192 65536)
ITERATIONS=(100000000 100000000 100000000 85753202 11138529)
ROUNDS=${#ITERATIONS[@]} # since iterations array is common for all cases
verify_data_size $ROUNDS # I'm not sure I like better as is comparing to passing an argument. Please reconsider.
```

So the main for-loop will look as follows:

```sh
for i in `seq 1 $ROUNDS`; do
# ...
```
___
*[tools/ib_read.sh, line 87 at r1](https://reviewable.io/reviews/pmem/rpma/624#-MNxA40f81gGYDIM2Dy-:-MNxA40f81gGYDIM2Dy0:b566gao) ([raw file](https://github.com/pmem/rpma/blob/b01e9ed8e76f2a328ad80173c71b762d58f21a8f/tools/ib_read.sh#L87)):*
> ```Shell
> bw-th)
> 	IB_TOOL=ib_read_bw
> 	HEADER="#bytes     #iterations    BW_peak[MB/sec]    BW_average[MB/sec]   MsgRate[Mpps]"
> ```

A global variable just to make sure we do not have to keep both copies in sync?
___
*[tools/ib_read.sh, line 157 at r1](https://reviewable.io/reviews/pmem/rpma/624#-MNxDFoW7u9tY_P62Qis:-MNxDFoW7u9tY_P62Qit:bsyl8e7) ([raw file](https://github.com/pmem/rpma/blob/b01e9ed8e76f2a328ad80173c71b762d58f21a8f/tools/ib_read.sh#L157)):*
> ```Shell
> 	# XXX --duration hides detailed statistics
> 	echo "[size: ${DS}, threads: ${TH}, iters: ${ITERATIONS[${i}]}] (duration: ~60s)"
> 	numactl -N $JOB_NUMA ${IB_TOOL} $DS_OPT $QP_OPT --iters ${ITERATIONS[${i}]} \
> ```

I think we can get the exact value for this round in the `case` above as anything else.
So we will here a little simpler call.
___
*[tools/ib_read.sh, line 164 at r1](https://reviewable.io/reviews/pmem/rpma/624#-MNxDmt3D4v8gc-5AOYG:-MNxDmt3D4v8gc-5AOYH:b-uajq7y) ([raw file](https://github.com/pmem/rpma/blob/b01e9ed8e76f2a328ad80173c71b762d58f21a8f/tools/ib_read.sh#L164)):*
> ```Shell
> 	# kill the server
> 	sshpass -p "$REMOTE_PASS" -v ssh $REMOTE_USER@$SERVER_IP \
> 		"killall ${IB_TOOL} 2>>$LOG_ERR" 2>>$LOG_ERR || true
> ```

It is an unremovable feature now?
The server cannot stop by itself?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/624)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[tools/ib_read.sh, line 83 at r1](https://reviewable.io/reviews/pmem/rpma/624#-MNxBDF0B8qEIlRt88tn:-MNxkDjU6uRXNtuie03U:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b01e9ed8e76f2a328ad80173c71b762d58f21a8f/tools/ib_read.sh#L83)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I do not like the idea of having an array of natural number 1..N. It can be easily generated ad hoc: `seq 1 $N` e.g.:

```sh
DATA_SIZE=(256 1024 4096 8192 65536)
ITERATIONS=(100000000 100000000 100000000 85753202 11138529)
ROUNDS=${#ITERATIONS[@]} # since iterations array is common for all cases
verify_data_size $ROUNDS # I'm not sure I like better as is comparing to passing an argument. Please reconsider.
```

So the main for-loop will look as follows:

```sh
for i in `seq 1 $ROUNDS`; do
# ...
```
</blockquote></details>

Done.
___
*[tools/ib_read.sh, line 87 at r1](https://reviewable.io/reviews/pmem/rpma/624#-MNxA40f81gGYDIM2Dy-:-MNxkESx1BdW9roZO7yE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b01e9ed8e76f2a328ad80173c71b762d58f21a8f/tools/ib_read.sh#L87)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

A global variable just to make sure we do not have to keep both copies in sync?
</blockquote></details>

Done.
___
*[tools/ib_read.sh, line 157 at r1](https://reviewable.io/reviews/pmem/rpma/624#-MNxDFoW7u9tY_P62Qis:-MNxlX7a12Gwv_xQwa2I:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b01e9ed8e76f2a328ad80173c71b762d58f21a8f/tools/ib_read.sh#L157)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we can get the exact value for this round in the `case` above as anything else.
So we will here a little simpler call.
</blockquote></details>

Done.
___
*[tools/ib_read.sh, line 164 at r1](https://reviewable.io/reviews/pmem/rpma/624#-MNxDmt3D4v8gc-5AOYG:-MNxlXeN3x8c7mjajEcx:bqsqxj3) ([raw file](https://github.com/pmem/rpma/blob/b01e9ed8e76f2a328ad80173c71b762d58f21a8f/tools/ib_read.sh#L164)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is an unremovable feature now?
The server cannot stop by itself?
</blockquote></details>

I have added it just in case - just to be sure there is no server process. I am not sure it is necessary. It can be removed I think.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/624)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tools/ib_read.sh, line 164 at r1](https://reviewable.io/reviews/pmem/rpma/624#-MNxDmt3D4v8gc-5AOYG:-MNxrmJT4PZuCSThXmQY:bimh9w3) ([raw file](https://github.com/pmem/rpma/blob/b01e9ed8e76f2a328ad80173c71b762d58f21a8f/tools/ib_read.sh#L164)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I have added it just in case - just to be sure there is no server process. I am not sure it is necessary. It can be removed I think.
</blockquote></details>

Please remove it if it is not needed for now.
___
*[tools/ib_read.sh, line 16 at r2](https://reviewable.io/reviews/pmem/rpma/624#-MNxsK-s3S1cTYkc80Hd:-MNxsK-s3S1cTYkc80He:b7nqxwu) ([raw file](https://github.com/pmem/rpma/blob/2e024a19d4f105be0365ca3096dd8e080f790a95/tools/ib_read.sh#L16)):*
> ```Shell
> 
> HEADER_LAT=" #bytes #iterations    t_min[usec]    t_max[usec]  t_typical[usec]    t_avg[usec]    t_stdev[usec]   99% percentile[usec]   99.9% percentile[usec]"
> HEADER_BW="#bytes     #iterations    BW_peak[Gb/sec]    BW_average[Gb/sec]   MsgRate[Mpps]"
> ```

`HEADER_LAT` has a space at the beginning left there intentional.
`HEADER_BW` generates correct CSVs without space at the beginning?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/624)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/ib_read.sh, line 164 at r1](https://reviewable.io/reviews/pmem/rpma/624#-MNxDmt3D4v8gc-5AOYG:-MNxxixd2hVtuMjnT7Mk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b01e9ed8e76f2a328ad80173c71b762d58f21a8f/tools/ib_read.sh#L164)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please remove it if it is not needed for now.
</blockquote></details>

Done.
___
*[tools/ib_read.sh, line 16 at r2](https://reviewable.io/reviews/pmem/rpma/624#-MNxsK-s3S1cTYkc80Hd:-MNxxjj75en84GVKqoDe:b-bodmd4) ([raw file](https://github.com/pmem/rpma/blob/2e024a19d4f105be0365ca3096dd8e080f790a95/tools/ib_read.sh#L16)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`HEADER_LAT` has a space at the beginning left there intentional.
`HEADER_BW` generates correct CSVs without space at the beginning?
</blockquote></details>

The space at the beginning is not needed in both cases.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/624#-:-MNyN4qq4yF2MvSugrxP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

___
*[tools/ib_read.sh, line 16 at r2](https://reviewable.io/reviews/pmem/rpma/624#-MNxsK-s3S1cTYkc80Hd:-MNyMzZDC048AytIBFts:b-91y9rm) ([raw file](https://github.com/pmem/rpma/blob/2e024a19d4f105be0365ca3096dd8e080f790a95/tools/ib_read.sh#L16)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The space at the beginning is not needed in both cases.
</blockquote></details>

You are right. It is even harmful.

**Pull request merged**
