### PR TITLE
common: update CHANGELOG

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1544)

### CODE REVIEW

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1544#-:-Mv3h6qTEmKAF5FbOLhJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Comment by yangx-jy** [comment]
___
*[CHANGELOG.md, line 10 at r2](https://reviewable.io/reviews/pmem/rpma/1544#-MvHfQGR1kxj3eK4PPcY:-MvHfQGR1kxj3eK4PPcZ:b5yy8gn) ([raw file](https://github.com/pmem/rpma/blob/f4be53181c1687d6ed9159a5ef236790887b60bb/CHANGELOG.md#L10)):*
> ```Markdown
> ## [Unreleased]
> ### Added
> - example (#12) for separate receive completion queue (RCQ),
> ```

1) Is it better to use a full stop at the end?
2) should we add an empty line before `- APIs`?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1544)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @osalyk and @yangx-jy)

___
*[CHANGELOG.md, line 10 at r2](https://reviewable.io/reviews/pmem/rpma/1544#-MvHfQGR1kxj3eK4PPcY:-MvI0NL63QQRbsjWfEfm:b-vdz28l) ([raw file](https://github.com/pmem/rpma/blob/f4be53181c1687d6ed9159a5ef236790887b60bb/CHANGELOG.md#L10)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

1) Is it better to use a full stop at the end?
2) should we add an empty line before `- APIs`?
</blockquote></details>

Yes, you are right, thanks!

**Review by osalyk — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1544)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

**Review by yangx-jy — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1544#-:-MvIEFUj01TjikEkalua:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

**Review by grom72 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1544)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1544#-:-MvIxWhR1MMnrwAHvF4X:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1544)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
