### PR TITLE
tools: fix y-axis to 110% of max

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1244)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1244)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/lib/figure.py, line 223 at r1](https://reviewable.io/reviews/pmem/rpma/1244#-MiVJ7e5B28vIF3IMasB:-MiVJ7e5B28vIF3IMasC:b-nxzskh) ([raw file](https://github.com/pmem/rpma/blob/863851547cd0586832e562a6b9f34e634540fb69/tools/perf/lib/figure.py#L223)):*
> ```
>             if max(yslist) > max_yaxis:
>                 max_yaxis = max(yslist)
> ```

This can be a bit faster:

```
            max = max(yslist)
            if max > max_yaxis:
                max_yaxis = max
```

**Review by janekmi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1244)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1244#-MiVImLFDGPGNwraD6-5:-MiVImLGChMOewveKm7Q:b-gzak0x) (no related file):*
increase -> fix

---
___
*[tools/perf/lib/figure.py, line 223 at r1](https://reviewable.io/reviews/pmem/rpma/1244#-MiVJ7e5B28vIF3IMasB:-MiVNg7_139D0K-8fTh3:bida4j2) ([raw file](https://github.com/pmem/rpma/blob/863851547cd0586832e562a6b9f34e634540fb69/tools/perf/lib/figure.py#L223)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>             if max(yslist) > max_yaxis:
>                 max_yaxis = max(yslist)
> ```

This can be a bit faster:

```
            max = max(yslist)
            if max > max_yaxis:
                max_yaxis = max
```
</blockquote></details>

Please don't. It has to be predefined by the user maximum possible bandwidth. It has nothing to do with what has been achieved during the benchmarking. I think the easiest way is to make it an optional argument of the config.json.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1244)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tools/perf/lib/figure.py, line 223 at r1](https://reviewable.io/reviews/pmem/rpma/1244#-MiVJ7e5B28vIF3IMasB:-MiVOGBoBmIVl8r96fXn:b-81la7d) ([raw file](https://github.com/pmem/rpma/blob/863851547cd0586832e562a6b9f34e634540fb69/tools/perf/lib/figure.py#L223)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please don't. It has to be predefined by the user maximum possible bandwidth. It has nothing to do with what has been achieved during the benchmarking. I think the easiest way is to make it an optional argument of the config.json.
</blockquote></details>

Right

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1244)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1244)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1244#-MiVImLFDGPGNwraD6-5:-MiVZ9fu18-wek0VK-iT:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

increase -> fix
</blockquote></details>

Done.

---
___
*[tools/perf/lib/figure.py, line 223 at r1](https://reviewable.io/reviews/pmem/rpma/1244#-MiVJ7e5B28vIF3IMasB:-MiVYsqFAHd-x-cRlgXK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/863851547cd0586832e562a6b9f34e634540fb69/tools/perf/lib/figure.py#L223)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Right
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1244)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1244)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tools/perf/config.json.example, line 18 at r3](https://reviewable.io/reviews/pmem/rpma/1244#-MiVnzSbCkxdSqd6GtvD:-MiVnzSbCkxdSqd6GtvE:b-l7zfuk) ([raw file](https://github.com/pmem/rpma/blob/c8e3e2373b5d10c849334e21b3c581bf89cb4d33/tools/perf/config.json.example#L18)):*
> ```
> rnic_max_bw
> ```

`rnic` looks strange, maybe `RNIC_MAX_BW` ?
___
*[tools/perf/report_figures.py, line 33 at r3](https://reviewable.io/reviews/pmem/rpma/1244#-MiVnmjx1sDUY195Iovf:-MiVnmjy7MaaPV7mXMSN:b-owguln) ([raw file](https://github.com/pmem/rpma/blob/c8e3e2373b5d10c849334e21b3c581bf89cb4d33/tools/perf/report_figures.py#L33)):*
> ```
>  1.1*bench.config
> ```

`1.1 * bench.config`

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1244)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/config.json.example, line 18 at r3](https://reviewable.io/reviews/pmem/rpma/1244#-MiVnzSbCkxdSqd6GtvD:-MiVwT1-E8uR0pzP2bCi:b-duyo7r) ([raw file](https://github.com/pmem/rpma/blob/c8e3e2373b5d10c849334e21b3c581bf89cb4d33/tools/perf/config.json.example#L18)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> rnic_max_bw
> ```

`rnic` looks strange, maybe `RNIC_MAX_BW` ?

</blockquote></details>

In uppercase the variables that go into the ./rpma_fio_bench.sh script.
___
*[tools/perf/report_figures.py, line 33 at r3](https://reviewable.io/reviews/pmem/rpma/1244#-MiVnmjx1sDUY195Iovf:-MiVq-_KDAGEZzQapZMp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c8e3e2373b5d10c849334e21b3c581bf89cb4d33/tools/perf/report_figures.py#L33)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  1.1*bench.config
> ```

`1.1 * bench.config`
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1244)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1244)* status: all files reviewed, 8 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/config.json.example, line 18 at r4](https://reviewable.io/reviews/pmem/rpma/1244#-MiWPhzX6nQe_S6syz96:-MiWPhzX6nQe_S6syz97:b-h7wd24) ([raw file](https://github.com/pmem/rpma/blob/f9c30ba05424bf7830f9dca13189c86bb1d21fa9/tools/perf/config.json.example#L18)):*
> ```
>     "REMOTE_JOB_PATH": "path",
>     "REMOTE_JOB_MEM_PATH": "path",
>     "rnic_max_bw": "(optional) in Gbps"
> ```

It should be a number and should not be put here since it is optional. I think it should be described in the CONFIG.JSON.MD instead.
___
*[tools/perf/report_figures.py, line 29 at r4](https://reviewable.io/reviews/pmem/rpma/1244#-MiWQDl42vtj_d7y8yLi:-MiWQDl42vtj_d7y8yLj:b-bqrtp1) ([raw file](https://github.com/pmem/rpma/blob/f9c30ba05424bf7830f9dca13189c86bb1d21fa9/tools/perf/report_figures.py#L29)):*
> ```Python
>     args = PARSER.parse_args()
>     bench = Bench.carry_on(args.bench)
>     bench.check_completed()
> ```

You only have to calculate it once.

```python
bw_max = bench.config.get('rnic_max_bw', None)
if bw_max is not None:
    bw_max *= 1.1
```
___
*[tools/perf/report_figures.py, line 33 at r4](https://reviewable.io/reviews/pmem/rpma/1244#-MiWS-2O0fUEOJD9ez-w:-MiWS-2S8V5irK17_7dC:br794id) ([raw file](https://github.com/pmem/rpma/blob/f9c30ba05424bf7830f9dca13189c86bb1d21fa9/tools/perf/report_figures.py#L33)):*
> ```Python
>         yaxis_max = 0
>         if 'rnic_max_bw' in bench.config:
>             yaxis_max = 1.1 * bench.config['rnic_max_bw']
> ```

```python
if figure.xarg == 'bw_avg':
    figure.set_yaxis_max(bw_max)
```
___
*[tools/perf/lib/figure.py, line 39 at r4](https://reviewable.io/reviews/pmem/rpma/1244#-MiWRYkJCYKnKN180YTZ:-MiWRYkK3u81v_UsWnjl:b-7kqe3n) ([raw file](https://github.com/pmem/rpma/blob/f9c30ba05424bf7830f9dca13189c86bb1d21fa9/tools/perf/lib/figure.py#L39)):*
> ```Python
>         self.file = self.output['file']
>         self.argx = self.output['x']
>         self.argy = self.output['y']
> ```

`self.yaxis_max = None`
___
*[tools/perf/lib/figure.py, line 67 at r4](https://reviewable.io/reviews/pmem/rpma/1244#-MiWRdeSCNQGZx8auA82:-MiWRdeSCNQGZx8auA83:b52dpa5) ([raw file](https://github.com/pmem/rpma/blob/f9c30ba05424bf7830f9dca13189c86bb1d21fa9/tools/perf/lib/figure.py#L67)):*
> ```Python
>         """Are all steps completed?"""
>         return self.output['done']
> ```

```python
def set_yaxis_max(self, max):
    self.yaxis_max = max
```
___
*[tools/perf/lib/figure.py, line 203 at r4](https://reviewable.io/reviews/pmem/rpma/1244#-MiWSB_1EqYETlodVGcD:-MiWSB_1EqYETlodVGcE:bgc1akg) ([raw file](https://github.com/pmem/rpma/blob/f9c30ba05424bf7830f9dca13189c86bb1d21fa9/tools/perf/lib/figure.py#L203)):*
> ```Python
>         return os.path.join('.', output)
> 
>     def to_png(self, include_title, yaxis_max):
> ```

I do not like the idea of building up a list of parameters here.
Maybe even `include_title` should go away from here at some point.
___
*[tools/perf/lib/figure.py, line 234 at r4](https://reviewable.io/reviews/pmem/rpma/1244#-MiWRpra8S2rqUxaC9OT:-MiWRpra8S2rqUxaC9OU:bsoksiw) ([raw file](https://github.com/pmem/rpma/blob/f9c30ba05424bf7830f9dca13189c86bb1d21fa9/tools/perf/lib/figure.py#L234)):*
> ```Python
>         plot.set_xlabel(self._label(self.argx))
>         plot.set_ylabel(self._label(self.argy, with_better=True))
>         if yaxis_max:
> ```

```python
if self.yaxis_max is not None:
```
___
*[tools/perf/lib/figure.py, line 235 at r4](https://reviewable.io/reviews/pmem/rpma/1244#-MiWRvpG7q9xR8hUmlOl:-MiWRvpG7q9xR8hUmlOm:b8ilm0u) ([raw file](https://github.com/pmem/rpma/blob/f9c30ba05424bf7830f9dca13189c86bb1d21fa9/tools/perf/lib/figure.py#L235)):*
> ```Python
>         plot.set_ylabel(self._label(self.argy, with_better=True))
>         if yaxis_max:
>             if not re.match(r"lat*", self.argy):
> ```

It is clever. I have to admit. But I want you to think why it is fundamentally wrong. ;-)
My proposition in other comments.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1244)* status: all files reviewed, 8 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/config.json.example, line 18 at r4](https://reviewable.io/reviews/pmem/rpma/1244#-MiWPhzX6nQe_S6syz96:-MiWaydRAh8Euc0SvbpU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f9c30ba05424bf7830f9dca13189c86bb1d21fa9/tools/perf/config.json.example#L18)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It should be a number and should not be put here since it is optional. I think it should be described in the CONFIG.JSON.MD instead.
</blockquote></details>

Done.
___
*[tools/perf/report_figures.py, line 29 at r4](https://reviewable.io/reviews/pmem/rpma/1244#-MiWQDl42vtj_d7y8yLi:-MiWUtvk5U6xNV41fS5g:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f9c30ba05424bf7830f9dca13189c86bb1d21fa9/tools/perf/report_figures.py#L29)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You only have to calculate it once.

```python
bw_max = bench.config.get('rnic_max_bw', None)
if bw_max is not None:
    bw_max *= 1.1
```
</blockquote></details>

Done.
___
*[tools/perf/report_figures.py, line 33 at r4](https://reviewable.io/reviews/pmem/rpma/1244#-MiWS-2O0fUEOJD9ez-w:-MiWVGT30IwcmUCiIXMt:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f9c30ba05424bf7830f9dca13189c86bb1d21fa9/tools/perf/report_figures.py#L33)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```python
if figure.xarg == 'bw_avg':
    figure.set_yaxis_max(bw_max)
```
</blockquote></details>

Done.
___
*[tools/perf/lib/figure.py, line 39 at r4](https://reviewable.io/reviews/pmem/rpma/1244#-MiWRYkJCYKnKN180YTZ:-MiWb0hJBNZYKz6fkAaB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f9c30ba05424bf7830f9dca13189c86bb1d21fa9/tools/perf/lib/figure.py#L39)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`self.yaxis_max = None`
</blockquote></details>

Done.
___
*[tools/perf/lib/figure.py, line 67 at r4](https://reviewable.io/reviews/pmem/rpma/1244#-MiWRdeSCNQGZx8auA82:-MiWVdWZ5YwrHnvh9ieB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f9c30ba05424bf7830f9dca13189c86bb1d21fa9/tools/perf/lib/figure.py#L67)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```python
def set_yaxis_max(self, max):
    self.yaxis_max = max
```
</blockquote></details>

Done.
___
*[tools/perf/lib/figure.py, line 203 at r4](https://reviewable.io/reviews/pmem/rpma/1244#-MiWSB_1EqYETlodVGcD:-MiWb1ny5X8qJ6MxS7gu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f9c30ba05424bf7830f9dca13189c86bb1d21fa9/tools/perf/lib/figure.py#L203)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I do not like the idea of building up a list of parameters here.
Maybe even `include_title` should go away from here at some point.
</blockquote></details>

Done.
___
*[tools/perf/lib/figure.py, line 234 at r4](https://reviewable.io/reviews/pmem/rpma/1244#-MiWRpra8S2rqUxaC9OT:-MiWUNKl6RecvuhkYvFA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f9c30ba05424bf7830f9dca13189c86bb1d21fa9/tools/perf/lib/figure.py#L234)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```python
if self.yaxis_max is not None:
```
</blockquote></details>

Done.
___
*[tools/perf/lib/figure.py, line 235 at r4](https://reviewable.io/reviews/pmem/rpma/1244#-MiWRvpG7q9xR8hUmlOl:-MiWaxkUDoI3XOFJJUfb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f9c30ba05424bf7830f9dca13189c86bb1d21fa9/tools/perf/lib/figure.py#L235)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is clever. I have to admit. But I want you to think why it is fundamentally wrong. ;-)
My proposition in other comments.
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1244)* status: 0 of 4 files reviewed, 9 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[tools/perf/lib/figure.py, line 11 at r3](https://reviewable.io/reviews/pmem/rpma/1244#-MiWmRNN9IZO-dgO6a7P:-MiWmRNN9IZO-dgO6a7Q:b-9jvmox) ([raw file](https://github.com/pmem/rpma/blob/c8e3e2373b5d10c849334e21b3c581bf89cb4d33/tools/perf/lib/figure.py#L11)):*
> ```Python
> import json
> import os.path
> import re
> ```

`W0611: Unused import re (unused-import)`

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1244)* status: 3 of 4 files reviewed, 9 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[tools/perf/CONFIG.JSON.md, line 11 at r6](https://reviewable.io/reviews/pmem/rpma/1244#-MiWmqG8BGzaSZNtKDdI:-MiWmqG8BGzaSZNtKDdJ:bvlb5za) ([raw file](https://github.com/pmem/rpma/blob/1da4663e0ac72ead5598f5e56ea8750123a75de8/tools/perf/CONFIG.JSON.md#L11)):*
> ```
> We can set the maximum bandwidth of the RNIC. This will be used to draw graphs, as the height of the y-axis 110% * rnic_max_bw
> ```

The maximum bandwidth of the RNIC can be set. It is used during drawing graphs, as the height of the y-axis is set to 110% of `rnic_max_bw`.

**Review by janekmi — APPROVED** [review]
> Reviewed 2 of 4 files at r5, 1 of 1 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1244)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/CONFIG.JSON.md, line 11 at r6](https://reviewable.io/reviews/pmem/rpma/1244#-MiWmqG8BGzaSZNtKDdI:-MiWpapF6BjKFLiSS9Un:b-x5t3nh) ([raw file](https://github.com/pmem/rpma/blob/1da4663e0ac72ead5598f5e56ea8750123a75de8/tools/perf/CONFIG.JSON.md#L11)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> We can set the maximum bandwidth of the RNIC. This will be used to draw graphs, as the height of the y-axis 110% * rnic_max_bw
> ```

The maximum bandwidth of the RNIC can be set. It is used during drawing graphs, as the height of the y-axis is set to 110% of `rnic_max_bw`.
</blockquote></details>

What do you think about the latest proposal?
___
*[tools/perf/lib/figure.py, line 11 at r3](https://reviewable.io/reviews/pmem/rpma/1244#-MiWmRNN9IZO-dgO6a7P:-MiWmqFZ8kLChIv2wHhm:b-pyzkpu) ([raw file](https://github.com/pmem/rpma/blob/c8e3e2373b5d10c849334e21b3c581bf89cb4d33/tools/perf/lib/figure.py#L11)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`W0611: Unused import re (unused-import)`
</blockquote></details>

Done. ;-)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1244)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

___
*[tools/perf/CONFIG.JSON.md, line 11 at r6](https://reviewable.io/reviews/pmem/rpma/1244#-MiWmqG8BGzaSZNtKDdI:-MiWpvb0BgWkjr2TqaoV:b8eau52) ([raw file](https://github.com/pmem/rpma/blob/1da4663e0ac72ead5598f5e56ea8750123a75de8/tools/perf/CONFIG.JSON.md#L11)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

What do you think about the latest proposal?
</blockquote></details>

I like it.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1244)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1244#-MiWqUz3B6LsrTG9DQ9A:-MiWqUz47SlzGbAJab6D:b-7r3hxw) (no related file):*
If `rnic_max_bw` should be set in `config.json`, there is no way to add/set/change it when the benchmarks had already been finished and results are ready. IMHO there should a possibility to add/set/change it in the second step - when generating the figures using `report_figures.py`.  I have the results ready and I would like to just regenerate the figures without running all benchmarks again ...

---

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1244)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1244#-MiWqUz3B6LsrTG9DQ9A:-MiWtL3HBSO4JYYJCAN6:b-nlfeu0) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

If `rnic_max_bw` should be set in `config.json`, there is no way to add/set/change it when the benchmarks had already been finished and results are ready. IMHO there should a possibility to add/set/change it in the second step - when generating the figures using `report_figures.py`.  I have the results ready and I would like to just regenerate the figures without running all benchmarks again ...
</blockquote></details>

You can add a line to the bench.json

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1244)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1244#-MiWqUz3B6LsrTG9DQ9A:-MiWuiIB0ztTgedkiIhf:b-vfk6q1) (no related file):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

You can add a line to the bench.json
</blockquote></details>

So this possibility should be described in the documentation.

---

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1244)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1244#-MiWqUz3B6LsrTG9DQ9A:-MiXO8sB6FeOTp3teq1q:bio7z39) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

So this possibility should be described in the documentation.
</blockquote></details>

Good catch @ldorau. It is needed when `./report_figures.py` is called. No point in collecting it faster. On the other hand, we do not have a config specific to this step. Maybe we should consider allowing providing `report.json` optionally during this step. This and possibly other useful parameters may be stored there. It makes sense also because it in some way is a visualization parameter.

What do you think?

---

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1244)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1244#-MiWqUz3B6LsrTG9DQ9A:-Mi_FXTB6eutJWzbinNM:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, `./report_figures.py` needs a configuration file specific for this step. It can be optional `report.json`.
</blockquote></details>

Done.

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r9, 3 of 3 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1244)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/report_figures.py, line 39 at r9](https://reviewable.io/reviews/pmem/rpma/1244#-Mi_H-eABjm4SnlP7nMr:-Mi_H-eABjm4SnlP7nMs:b-psyyaa) ([raw file](https://github.com/pmem/rpma/blob/e8b393c905497b1d0f0ad7a72b82bd33ffe40edc/tools/perf/report_figures.py#L39)):*
> ```
> figure.set_yaxis_max(bw_max)
> ```

Will it work if `bw_max == None` ?

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1244)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/report.json.example, line 3 at r10](https://reviewable.io/reviews/pmem/rpma/1244#-Mi_I3O02DET3sAZ1NZ0:-Mi_I3O02DET3sAZ1NZ1:b-bxfypp) ([raw file](https://github.com/pmem/rpma/blob/8f7821178aca08bf10277a08eacd5deeccc15a50/tools/perf/report.json.example#L3)):*
> ```
> in Gbps."
> ```

a comma is missing at the end of the line

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1244)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/report.json.example, line 3 at r10](https://reviewable.io/reviews/pmem/rpma/1244#-Mi_I3O02DET3sAZ1NZ0:-Mi_ImOY5P_V1NdRwPsM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8f7821178aca08bf10277a08eacd5deeccc15a50/tools/perf/report.json.example#L3)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> in Gbps."
> ```

a comma is missing at the end of the line
</blockquote></details>

Done.
___
*[tools/perf/report_figures.py, line 39 at r9](https://reviewable.io/reviews/pmem/rpma/1244#-Mi_H-eABjm4SnlP7nMr:-Mi_IQpz1UwtEpb2VmYm:b-50ttqe) ([raw file](https://github.com/pmem/rpma/blob/e8b393c905497b1d0f0ad7a72b82bd33ffe40edc/tools/perf/report_figures.py#L39)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> figure.set_yaxis_max(bw_max)
> ```

Will it work if `bw_max == None` ?
</blockquote></details>

Before setting **plot.set_ylim(top=self.yaxis_max)**, we check this value.

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1244#-:-Mi_Je0F7GZo_W6zoyBi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

___
*[tools/perf/report_figures.py, line 39 at r9](https://reviewable.io/reviews/pmem/rpma/1244#-Mi_H-eABjm4SnlP7nMr:-Mi_JbRU-R3aB8rdAaZv:b32w0x) ([raw file](https://github.com/pmem/rpma/blob/e8b393c905497b1d0f0ad7a72b82bd33ffe40edc/tools/perf/report_figures.py#L39)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Before setting **plot.set_ylim(top=self.yaxis_max)**, we check this value.
</blockquote></details>

OK

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1244)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tools/perf/report_figures.py, line 34 at r11](https://reviewable.io/reviews/pmem/rpma/1244#-Mi_Sar_-J6kC1i61X6K:-Mi_Y3gl00071SWGV1DE:b32v57) ([raw file](https://github.com/pmem/rpma/blob/aa91978a479723007ee65e847a65e2dac1a34943/tools/perf/report_figures.py#L34)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You assume the visualization part is required. Whereas I think it should not.

```python
bw_max = args.report['json'].get('visualization', {}).get('rnic_max_bw', None)
```
</blockquote></details>

+1

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1244)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/report.json.example, line 5 at r11](https://reviewable.io/reviews/pmem/rpma/1244#-Mi_Sv_46lnC4Hm1bbkp:-Mi_Z_nd617uRZ4YxYn5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/aa91978a479723007ee65e847a65e2dac1a34943/tools/perf/report.json.example#L5)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we need `REPORT.JSON.MD`. :laughing: 
But at this point, it is good enough. :+1: 
One last thing, please move it to the bottom of the file.
</blockquote></details>

Done.
___
*[tools/perf/report_figures.py, line 34 at r11](https://reviewable.io/reviews/pmem/rpma/1244#-Mi_Sar_-J6kC1i61X6K:-Mi__ahp4eQeq2jr-UUT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/aa91978a479723007ee65e847a65e2dac1a34943/tools/perf/report_figures.py#L34)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 2 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1244)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r12, 1 of 1 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1244#-:-Mi_faQuCOBL0klnvyoY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
