### PR TITLE
rpma: update librpma.h and CHANGELOG

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1678)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1678)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1678#-N059r3BENuo3x7vvvFg:-N059r3BENuo3x7vvvFh:ba6ldr4) (no related file):*
Shall we add a few sentences about the new solution and the differences between cq_wait and conn_wait?

---
___
*[src/include/librpma.h, line 1402 at r1](https://reviewable.io/reviews/pmem/rpma/1678#-N059O-y7hSo-Yh_Q216:-N059O-y7hSo-Yh_Q217:bgt6ihp) ([raw file](https://github.com/pmem/rpma/blob/1d5cadd5439fe34cb621b35c0f3646b69c31ba3c/src/include/librpma.h#L1402)):*
> ```objc
> 
> /** 3
>  * rpma_conn_cfg_set_compl_channel - set if completion channel can be shared
> ```

Is there any way to not use a shared channel if it is configured?



_Code quote:_
```objc
 can be
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1678)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1678#-N059r3BENuo3x7vvvFg:-N05JzbdAmekiFlUSudU:b90ft60) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Shall we add a few sentences about the new solution and the differences between cq_wait and conn_wait?
</blockquote></details>

We can, but what place would be best for that in your opinion?

---
___
*[src/include/librpma.h, line 1402 at r1](https://reviewable.io/reviews/pmem/rpma/1678#-N059O-y7hSo-Yh_Q216:-N05Jk254xmK-vcVmfBE:b-qy6d7n) ([raw file](https://github.com/pmem/rpma/blob/1d5cadd5439fe34cb621b35c0f3646b69c31ba3c/src/include/librpma.h#L1402)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Is there any way to not use a shared channel if it is configured?
</blockquote></details>

Common completion channel will be used always, but it will be shared indeed only when there are two CQs (main CQ an RCQ).



_Code quote:_
```objc
completion channel
```

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1678)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1678#-N059r3BENuo3x7vvvFg:-N05P8IM-H6n6cXjBNVt:b-xpqihn) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

We can, but what place would be best for that in your opinion?
</blockquote></details>

Either in CHANGELOG or in rpma_conn_wait() or both.

---

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1678#-:-N05Pkr_03M3aDaXacjK:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1678#-:-N05RDk2-q1mOueul0qE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
:lgtm_strong: 

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1678#-:-N05VqCj6xHb5lVQWxje:b-uwkowd)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1678)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1678#-:-N05rgYB0qKVbRDlK3wO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
