### PR TITLE
tools: perf: introduce lib.format

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1332)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1332)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1332)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1332#-:-Mosl0jP-oHSNReOFnZO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1332)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1332)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/lib/format/fio.py, line 4 at r2](https://reviewable.io/reviews/pmem/rpma/1332#-Mp5tZDPD_novSoWeL-0:-Mp5tZDPD_novSoWeL-1:bb6ht36) ([raw file](https://github.com/pmem/rpma/blob/b4361ada053a7715b5a322f63d5274a8dd7b77d3/tools/perf/lib/format/fio.py#L4)):*
> ```Python
> #
> # SPDX-License-Identifier: BSD-3-Clause
> # Copyright 2020-2021, Intel Corporation
> ```

2021
___
*[tools/perf/lib/format/ib_read_bw.py, line 4 at r2](https://reviewable.io/reviews/pmem/rpma/1332#-Mp5tdfj20nlSEZzgxNm:-Mp5tdfj20nlSEZzgxNn:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/b4361ada053a7715b5a322f63d5274a8dd7b77d3/tools/perf/lib/format/ib_read_bw.py#L4)):*
> ```Python
> #
> # SPDX-License-Identifier: BSD-3-Clause
> # Copyright 2020-2021, Intel Corporation
> ```

.
___
*[tools/perf/lib/format/ib_read_lat.py, line 4 at r2](https://reviewable.io/reviews/pmem/rpma/1332#-Mp5thVO6qes4zlzwuvf:-Mp5thVO6qes4zlzwuvg:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/b4361ada053a7715b5a322f63d5274a8dd7b77d3/tools/perf/lib/format/ib_read_lat.py#L4)):*
> ```Python
> #
> # SPDX-License-Identifier: BSD-3-Clause
> # Copyright 2020-2021, Intel Corporation
> ```

.

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1332)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1332)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/lib/format/fio.py, line 4 at r2](https://reviewable.io/reviews/pmem/rpma/1332#-Mp5tZDPD_novSoWeL-0:-Mp5uXsO4a_4pDoc3vJ7:b-p8bc0p) ([raw file](https://github.com/pmem/rpma/blob/b4361ada053a7715b5a322f63d5274a8dd7b77d3/tools/perf/lib/format/fio.py#L4)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

2021
</blockquote></details>

I'm not so sure. Most of this code is copied from other places.
___
*[tools/perf/lib/format/ib_read_bw.py, line 4 at r2](https://reviewable.io/reviews/pmem/rpma/1332#-Mp5tdfj20nlSEZzgxNm:-Mp5ukuT1U_vp2RxG4wV:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/b4361ada053a7715b5a322f63d5274a8dd7b77d3/tools/perf/lib/format/ib_read_bw.py#L4)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

.
</blockquote></details>

.
___
*[tools/perf/lib/format/ib_read_lat.py, line 4 at r2](https://reviewable.io/reviews/pmem/rpma/1332#-Mp5thVO6qes4zlzwuvf:-Mp5unT41Uo1Kw5gWtLD:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/b4361ada053a7715b5a322f63d5274a8dd7b77d3/tools/perf/lib/format/ib_read_lat.py#L4)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

.
</blockquote></details>

.

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1332)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1332)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tools/perf/lib/format/fio.py, line 4 at r2](https://reviewable.io/reviews/pmem/rpma/1332#-Mp5tZDPD_novSoWeL-0:-Mp5w5ZlEU0n0FscP40N:bfi1y97) ([raw file](https://github.com/pmem/rpma/blob/b4361ada053a7715b5a322f63d5274a8dd7b77d3/tools/perf/lib/format/fio.py#L4)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I'm not so sure. Most of this code is copied from other places.
</blockquote></details>

But this is the new file.

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1332)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1332)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
