### PR TITLE
test: add rpma_conn_cfg_set_rq_size multithreaded test

### PR DESCRIPTION
**Pull request by ewanglong**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1099)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1099)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

___
*[tests/multithreaded/conn/rpma_conn_cfg_set_rq_size.c, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1099#-Mcxe_Rr5Re9fOvDZye3:-Mcxe_Rr5Re9fOvDZye4:b-skbmtb) ([raw file](https://github.com/pmem/rpma/blob/273bc8d8906754629372a35c1d1728f1bb1717c7/tests/multithreaded/conn/rpma_conn_cfg_set_rq_size.c#L13)):*
> ```
> Q_SIZE_EXP
> ```

Please rename it to` Q_SIZE_EXPECTED` because `EXP` is ambiguous.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1099)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

___
*[tests/multithreaded/conn/rpma_conn_cfg_set_rq_size.c, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1099#-Mcxe_Rr5Re9fOvDZye3:-McxfkPB-IDzO2v8Pqea:b-ad4r11) ([raw file](https://github.com/pmem/rpma/blob/273bc8d8906754629372a35c1d1728f1bb1717c7/tests/multithreaded/conn/rpma_conn_cfg_set_rq_size.c#L13)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> Q_SIZE_EXP
> ```

Please rename it to` Q_SIZE_EXPECTED` because `EXP` is ambiguous.

</blockquote></details>

A comment is enough here.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1099)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/conn/rpma_conn_cfg_set_rq_size.c, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1099#-McxgZezBkJbY7MQ3c74:-McxgZf-1C-tt_Ugwu1n:btuj9e7) ([raw file](https://github.com/pmem/rpma/blob/273bc8d8906754629372a35c1d1728f1bb1717c7/tests/multithreaded/conn/rpma_conn_cfg_set_rq_size.c#L39)):*
> ```C
> 
> 	*state_ptr = st;
> }
> ```

Please make common parts common.

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1099)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

___
*[tests/multithreaded/conn/rpma_conn_cfg_set_rq_size.c, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1099#-Mcxe_Rr5Re9fOvDZye3:-MdKYDfjBOa4LuyAqrAl:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/273bc8d8906754629372a35c1d1728f1bb1717c7/tests/multithreaded/conn/rpma_conn_cfg_set_rq_size.c#L13)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

A comment is enough here.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1099#-:-MdMJXG9D4UL2a02AHCX:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

**Review by janekmi — APPROVED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1099)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Review by janekmi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1099#-:-MdNn0di3CuTRdvMGdZQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Pull request merged**
