### PR TITLE
common: 0.11.0-rc1 release

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1548)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1548)* status: 0 of 2 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1548#-MvJXXIbBAAG0JKjeJib:-MvJXXIbBAAG0JKjeJic:ba70c3o) (no related file):*
Waiting for https://github.com/pmem/rpma/pull/1537

---

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1548#-:-MvJYDenBcV7V9auei5M:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1548)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1548)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
