### PR TITLE
tools: use simple purecss layout for the report readability

### PR DESCRIPTION
**Pull request by janekmi**
Requires:
- [x] #764

Preview:
image

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/765)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 9 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/765)* status: 9 of 11 files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/765)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/765#-:-MRxIR947xtK8Z3fydES:bdycpsm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Comment by ldorau** [comment]
Please rebase

**Review by ldorau — APPROVED** [review]
> Reviewed 5 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/765)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/templates/header.md, line 3 at r2](https://reviewable.io/reviews/pmem/rpma/765#-MRzBo1I0D-_5-RwLwDs:-MRzBo1I0D-_5-RwLwDt:bw0wpjl) ([raw file](https://github.com/pmem/rpma/blob/3115fbc4326b304971a455210094a1a4fa12ac72/tools/templates/header.md#L3)):*
> ```Markdown
> # RPMA - Performance Report
> 
> ## Release {{release}}
> ```

no new line at the end

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/765#-:-MRzC0wp9KL-BRuxBTUy:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Pull request merged**
