### PR TITLE
tools: perf: allow not flat figures descriptions

### PR DESCRIPTION
**Pull request by janekmi**
Requires:
- [x] #1065

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1068)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1068)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1068#-Mb5rpuUDE4xCyL28Yqc:-Mb5rpuUDE4xCyL28Yqd:b-ln7lr7) (no related file):*
Maybe you can use one of those:
https://www.wordhippo.com/what-is/the-opposite-of/flat.html
instead of "not flat" ?

---

**Review by ldorau — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1068#-:-Mb5yYtOCWqMxRnQSvFU:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1068)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1068#-:-Mb6RyaS54PNQnvlnFRv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1068#-:-Mb6Sop0A0T5aBC7zmG0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1068)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
