### PR TITLE
tools: perf: document lib.benchmark.runner

### PR DESCRIPTION
**Pull request by janekmi**
Requires:

- [x] #1375
- [x] #1379
- [x] #1381

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1382)

### CODE REVIEW

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1382)* status: 0 of 25 files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1382)* status: 0 of 25 files reviewed, all discussions resolved (waiting on @haichangsi and @ldorau)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1382#-:-MpvFxdK8IGVXRUsMVPy:bnfp4nl)* status: 1 of 25 files reviewed, all discussions resolved (waiting on @grom72, @haichangsi, and @ldorau)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1382)* status: 1 of 25 files reviewed, 1 unresolved discussion (waiting on @grom72, @haichangsi, @janekmi, and @ldorau)

___
*[tools/perf/lib/benchmark/runner/base.py, line 35 at r1](https://reviewable.io/reviews/pmem/rpma/1382#-MpvTuLwBcnKtW0wAYae:-MpvTuLwBcnKtW0wAYaf:b-yj5wtn) ([raw file](https://github.com/pmem/rpma/blob/18c9a23fa00ac14532ccd8f62c50bb5d0d96975b/tools/perf/lib/benchmark/runner/base.py#L35)):*
> ```
> the configuration
> ```
the actual configuration

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1382)* status: 1 of 26 files reviewed, 1 unresolved discussion (waiting on @grom72, @haichangsi, and @ldorau)

___
*[tools/perf/lib/benchmark/runner/base.py, line 35 at r1](https://reviewable.io/reviews/pmem/rpma/1382#-MpvTuLwBcnKtW0wAYae:-MpvUWQo6_CcYK6D8nLy:b-gnp0e2) ([raw file](https://github.com/pmem/rpma/blob/18c9a23fa00ac14532ccd8f62c50bb5d0d96975b/tools/perf/lib/benchmark/runner/base.py#L35)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> the configuration
> ```
the actual configuration
</blockquote></details>

This sentence is repeated over and over again throughout the whole `lib` package.
Please add changing all these sentences to the backlog.

**Review by grom72 — COMMENTED** [review]
> Reviewed 7 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1382)* status: 5 of 26 files reviewed, 6 unresolved discussions (waiting on @grom72, @haichangsi, @janekmi, and @ldorau)

___
*[tools/perf/lib/benchmark/runner/bash.py, line 66 at r1](https://reviewable.io/reviews/pmem/rpma/1382#-MpvUMuOE5QW9tQ1eTzE:-MpvUMuP9R51g3TZbSt3:b-5ndl2s) ([raw file](https://github.com/pmem/rpma/blob/18c9a23fa00ac14532ccd8f62c50bb5d0d96975b/tools/perf/lib/benchmark/runner/bash.py#L66)):*
> ```
> the configuration
> ```
.
___
*[tools/perf/lib/benchmark/runner/common.py, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1382#-MpvUaD0AeeTZmRkUPM5:-MpvUaD0AeeTZmRkUPM6:bnpabsl) ([raw file](https://github.com/pmem/rpma/blob/18c9a23fa00ac14532ccd8f62c50bb5d0d96975b/tools/perf/lib/benchmark/runner/common.py#L13)):*
> ```
> an unexpected mode value
> ```
an error message when unexpected mode is detected
___
*[tools/perf/lib/benchmark/runner/dummy.py, line 19 at r1](https://reviewable.io/reviews/pmem/rpma/1382#-MpvUtz54gpvvfnAn-IO:-MpvUtz54gpvvfnAn-IP:b-90o9lb) ([raw file](https://github.com/pmem/rpma/blob/18c9a23fa00ac14532ccd8f62c50bb5d0d96975b/tools/perf/lib/benchmark/runner/dummy.py#L19)):*
> ```
> When no actual results are expected.
> ```
 When no actual results are expected.
**Note** XXX -> please describe when and how it can be used.
___
*[tools/perf/lib/report/__init__.py, line 14 at r1](https://reviewable.io/reviews/pmem/rpma/1382#-MpvWkEF8Q1FterQ-bJZ:-MpvWkEGEaJK_1rTOUs0:b52s6d6) ([raw file](https://github.com/pmem/rpma/blob/18c9a23fa00ac14532ccd8f62c50bb5d0d96975b/tools/perf/lib/report/__init__.py#L14)):*
> ```
> modules combinese these
> ```
module combines
___
*[tools/perf/lib/report/__init__.py, line 15 at r1](https://reviewable.io/reviews/pmem/rpma/1382#-MpvX5gA3qbgmd12V0TJ:-MpvX5gA3qbgmd12V0TK:b1coft6) ([raw file](https://github.com/pmem/rpma/blob/18c9a23fa00ac14532ccd8f62c50bb5d0d96975b/tools/perf/lib/report/__init__.py#L15)):*
> ```
> parts and figures you have already generated into a final
> ```
parts and related figures that have already been generated into a final

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1382)* status: 6 of 26 files reviewed, 6 unresolved discussions (waiting on @grom72, @haichangsi, @janekmi, and @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1382)* status: 6 of 26 files reviewed, 3 unresolved discussions (waiting on @grom72, @haichangsi, @janekmi, and @ldorau)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1382)* status: 6 of 26 files reviewed, 3 unresolved discussions (waiting on @grom72, @haichangsi, @janekmi, and @ldorau)

___
*[tools/perf/lib/benchmark/runner/bash.py, line 66 at r1](https://reviewable.io/reviews/pmem/rpma/1382#-MpvUMuOE5QW9tQ1eTzE:-MpvY-rm7VvrzCNj0OqA:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/18c9a23fa00ac14532ccd8f62c50bb5d0d96975b/tools/perf/lib/benchmark/runner/bash.py#L66)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> the configuration
> ```
.
</blockquote></details>

.
___
*[tools/perf/lib/benchmark/runner/common.py, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1382#-MpvUaD0AeeTZmRkUPM5:-MpvYaX5BRoYaFsfDHyy:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/18c9a23fa00ac14532ccd8f62c50bb5d0d96975b/tools/perf/lib/benchmark/runner/common.py#L13)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> an unexpected mode value
> ```
an error message when unexpected mode is detected
</blockquote></details>

Done.
___
*[tools/perf/lib/report/__init__.py, line 14 at r1](https://reviewable.io/reviews/pmem/rpma/1382#-MpvWkEF8Q1FterQ-bJZ:-MpvZBs6AeVVhW3VIfro:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/18c9a23fa00ac14532ccd8f62c50bb5d0d96975b/tools/perf/lib/report/__init__.py#L14)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> modules combinese these
> ```
module combines
</blockquote></details>

Done.
___
*[tools/perf/lib/report/__init__.py, line 15 at r1](https://reviewable.io/reviews/pmem/rpma/1382#-MpvX5gA3qbgmd12V0TJ:-MpvZljFBYpwajz1xQkK:b-fkri14) ([raw file](https://github.com/pmem/rpma/blob/18c9a23fa00ac14532ccd8f62c50bb5d0d96975b/tools/perf/lib/report/__init__.py#L15)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> parts and figures you have already generated into a final
> ```
parts and related figures that have already been generated into a final
</blockquote></details>

Sorry for the misleading stack of commits. This file is not a part of this change.

**Review by ldorau — COMMENTED** [review]
> Reviewed 13 of 20 files at r2, 5 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1382)* status: 24 of 26 files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1382)* status: 24 of 26 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1382)* status: 24 of 26 files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tools/perf/lib/benchmark/base.py, line 175 at r3](https://reviewable.io/reviews/pmem/rpma/1382#-Mpva-Y6A_MLTEquLt9U:-Mpva-Y6A_MLTEquLt9V:b-jxb2zc) ([raw file](https://github.com/pmem/rpma/blob/33a900ad8b8a770202ebf7cacec70122bf99db11/tools/perf/lib/benchmark/base.py#L175)):*
> ```
>         - `lib.benchmark.runner.bash.Bash.run()` when the legacy `ib_read.sh`
>           and `rpma_fio_bench.sh` are meant to be used or
> ```
Shall we mark this as deprecated?
Or do we do not go in this direction?

**Review by ldorau — APPROVED** [review]
> Reviewed 5 of 25 files at r1, 2 of 20 files at r2, 1 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1382)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1382#-:-Mpvcb1ADXsIUZC-khy4:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1382#-:-MpvchhjAuKHtsLnuLG_:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1382)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1382#-:-MpvetQM0yh5OK0SZxR0:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1382)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
