### PR TITLE
doc: improve the documentation to rpma_mr... functions

### PR DESCRIPTION
**Pull request by osalyk**
- [x] #422

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/426)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/426)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[src/include/librpma.h, line 333 at r1](https://reviewable.io/reviews/pmem/rpma/426#-MHzvQew4nZFZ0ZkUAsS:-MHzvQew4nZFZ0ZkUAsT:btka02) ([raw file](https://github.com/pmem/rpma/blob/fe2f78c3a3282eacc0862ed4e8b553d9f51b2b68/src/include/librpma.h#L333)):*
> ```objc
>  *	struct rpma_peer;
>  *	struct rpma_mr_local;
>  *	enum rpma_mr_plt {
> ```

`enum rpma_mr_plt ` has been removed.
The PR has to be reworked after having merged #422 - you can try now to rework it on top of #422

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/426)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/426)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/include/librpma.h, line 333 at r1](https://reviewable.io/reviews/pmem/rpma/426#-MHzvQew4nZFZ0ZkUAsS:-MI-CK-GBM0ST0yyfC4v:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fe2f78c3a3282eacc0862ed4e8b553d9f51b2b68/src/include/librpma.h#L333)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`enum rpma_mr_plt ` has been removed.
The PR has to be reworked after having merged #422 - you can try now to rework it on top of #422 
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 29 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/426)* status: 2 of 29 files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[src/include/librpma.h, line 451 at r3](https://reviewable.io/reviews/pmem/rpma/426#-MI-KX810bjuuvqovII7:-MI-KX810bjuuvqovII8:b5iekkd) ([raw file](https://github.com/pmem/rpma/blob/4cdcaa385b7f6365db3ccc68444e24aea8f97927/src/include/librpma.h#L451)):*
> ```
> of a memory
> ```

of the memory ...
___
*[src/include/librpma.h, line 476 at r3](https://reviewable.io/reviews/pmem/rpma/426#-MI-KdNN53Z09rG5elnG:-MI-KdNN53Z09rG5elnH:b-6guuix) ([raw file](https://github.com/pmem/rpma/blob/4cdcaa385b7f6365db3ccc68444e24aea8f97927/src/include/librpma.h#L476)):*
> ```
> gets a remote memory region size
> ```

gets the size of the remote memory region
___
*[src/include/librpma.h, line 524 at r3](https://reviewable.io/reviews/pmem/rpma/426#-MI-Kp-925q5Pdj0M3_e:-MI-Kp-925q5Pdj0M3_f:b-uum5zl) ([raw file](https://github.com/pmem/rpma/blob/4cdcaa385b7f6365db3ccc68444e24aea8f97927/src/include/librpma.h#L524)):*
> ```
> deletes a remote 
> ```

deletes the remote

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/426)* status: 2 of 29 files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[src/include/librpma.h, line 451 at r3](https://reviewable.io/reviews/pmem/rpma/426#-MI-KX810bjuuvqovII7:-MI-Qir_AqMv5FLpNPpQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4cdcaa385b7f6365db3ccc68444e24aea8f97927/src/include/librpma.h#L451)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> of a memory
> ```

of the memory ...
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 476 at r3](https://reviewable.io/reviews/pmem/rpma/426#-MI-KdNN53Z09rG5elnG:-MI-QqgP0KvIJxrslorP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4cdcaa385b7f6365db3ccc68444e24aea8f97927/src/include/librpma.h#L476)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> gets a remote memory region size
> ```

gets the size of the remote memory region
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 524 at r3](https://reviewable.io/reviews/pmem/rpma/426#-MI-Kp-925q5Pdj0M3_e:-MI-Qx6k3ayOmRfznKNG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4cdcaa385b7f6365db3ccc68444e24aea8f97927/src/include/librpma.h#L524)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> deletes a remote 
> ```

deletes the remote 
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/426)* status: 2 of 29 files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 13 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/426)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
thx! :-)

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/426#-:-MI-uYBJ-ZIfwTO60h4U:b-8p3iug)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/426)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[src/include/librpma.h, line 569 at r6](https://reviewable.io/reviews/pmem/rpma/426#-MI2qZXEC2pKT6xw1Z2K:-MI2qZXEC2pKT6xw1Z2L:b-o6sj4r) ([raw file](https://github.com/pmem/rpma/blob/142de5801d05dc920c3ab1c350178b3ee8b7659d/src/include/librpma.h#L569)):*
> ```
> gets a flush types
> ```

gets flush types (no `a`)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/426)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/426)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/include/librpma.h, line 569 at r6](https://reviewable.io/reviews/pmem/rpma/426#-MI2qZXEC2pKT6xw1Z2K:-MI2rSzG-a0juUHefW1Y:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/142de5801d05dc920c3ab1c350178b3ee8b7659d/src/include/librpma.h#L569)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> gets a flush types
> ```

gets flush types (no `a`)
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/426)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
@grom72 please review

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/426#-:-MI37tRA3JGTj_1knSp_:bgjoyzx)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/426)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[src/include/librpma.h, line 522 at r7](https://reviewable.io/reviews/pmem/rpma/426#-MI3UavwDs0Dy_z56hlR:-MI3UavwDs0Dy_z56hlS:b-xcgd50) ([raw file](https://github.com/pmem/rpma/blob/06ebae5957035ea3a2d3628f6c8e5d524dff3e1a/src/include/librpma.h#L522)):*
> ```
> rpma_mr_remote_from_descriptor
> ```

rpma_mr_get_descriptor_size

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/426)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/include/librpma.h, line 522 at r7](https://reviewable.io/reviews/pmem/rpma/426#-MI3UavwDs0Dy_z56hlR:-MI3XEimCnmXmj5lf4FR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/06ebae5957035ea3a2d3628f6c8e5d524dff3e1a/src/include/librpma.h#L522)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> rpma_mr_remote_from_descriptor
> ```

rpma_mr_get_descriptor_size
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/426#-:-MI3Y9U8CoT9xTIJRL8E:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/426)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/426#-:-MI4C762AMtNsQn1-wV1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/426)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/426)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
