### PR TITLE
tools: add REMOTE_TRACER

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1479)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1479)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1479)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1479)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 161 at r1](https://reviewable.io/reviews/pmem/rpma/1479#-Mt3VD2nAR_RM49YaMiC:-Mt3VD2nAR_RM49YaMiD:bjaeuiq) ([raw file](https://github.com/pmem/rpma/blob/a3e005cb5299aa3b9de6176b2c689302cc586bdc/tools/perf/lib/benchmark/runner/fio.py#L161)):*
> ```Python
>             args = ['numactl', '-N', r_numa_n]
> 
>         args.extend([self.__r_fio_path])
> ```

```python
        args.append(self.__r_fio_path)
```



_Code quote:_
```Python
        args.extend([self.__r_fio_path])
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1479)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 161 at r1](https://reviewable.io/reviews/pmem/rpma/1479#-Mt3VD2nAR_RM49YaMiC:-Mt3_y5o3ViCfVFwcS_U:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a3e005cb5299aa3b9de6176b2c689302cc586bdc/tools/perf/lib/benchmark/runner/fio.py#L161)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```python
        args.append(self.__r_fio_path)
```

</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1479#-:-Mt3sO_l3gKBlb1OGSbz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1479#-:-Mt7j-R721MBP_aCP7L0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1479)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
