### PR TITLE
tools: implement Figure.to_html()

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1114)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1114)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/lib/Figure.py, line 179 at r1](https://reviewable.io/reviews/pmem/rpma/1114#-MdWFAcUD1Cz1HIbMJ1F:-MdWFAcVA0twU-ymtazN:b-2oagmy) ([raw file](https://github.com/pmem/rpma/blob/97eb183e95dfb8d38b8ce60e3f5e467ce4e9d9aa/tools/perf/lib/Figure.py#L179)):*
> ```Python
>     def to_html(self, result_dir):
>         """Combine a Figure's png and data table into a single HTML snippet"""
>         html = '' + self.title + ''
> ```

When a HTML tag does not have pair like `<table></table>` it should be closed like this: ``.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1114)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/Figure.py, line 179 at r1](https://reviewable.io/reviews/pmem/rpma/1114#-MdWFAcUD1Cz1HIbMJ1F:-MdWLB39AA95sfe5XeKe:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/97eb183e95dfb8d38b8ce60e3f5e467ce4e9d9aa/tools/perf/lib/Figure.py#L179)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

When a HTML tag does not have pair like `<table></table>` it should be closed like this: ``.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1114#-:-MdWLjmxEjRU2Uh546gC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1114#-:-MdWQ7fu7vJZnp8pHpY1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
