### PR TITLE
test: add rpma_conn_cfg_get_sq_size multithreaded test

### PR DESCRIPTION
**Pull request by ewanglong**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1101)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1101)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

___
*[tests/multithreaded/conn/rpma_conn_cfg_get_sq_size.c, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1101#-McxgMlw8SafouPMn0ld:-McxgMlw8SafouPMn0le:bsgtt62) ([raw file](https://github.com/pmem/rpma/blob/13e1370f1a45ffb4fb785a5f0382b316930312c8/tests/multithreaded/conn/rpma_conn_cfg_get_sq_size.c#L13)):*
> ```
> Q_SIZE_EXP
> ```

Please add a comment that this is the EXPected value.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1101)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/conn/rpma_conn_cfg_get_sq_size.c, line 35 at r1](https://reviewable.io/reviews/pmem/rpma/1101#-McxjxyC2IKDk4dk89l9:-McxjxyC2IKDk4dk89lA:btuj9e7) ([raw file](https://github.com/pmem/rpma/blob/13e1370f1a45ffb4fb785a5f0382b316930312c8/tests/multithreaded/conn/rpma_conn_cfg_get_sq_size.c#L35)):*
> ```C
> 	if ((ret = rpma_conn_cfg_set_sq_size(pr->cfg_ptr, Q_SIZE_EXP)))
> 		MTT_RPMA_ERR(tr, "rpma_conn_cfg_set_sq_size", ret);
> }
> ```

Please make common parts common.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1101)* status: all files reviewed, 3 unresolved discussions (waiting on @ewanglong)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1101#-MdRqKaHBmyn6RWWam2i:-MdRqKaI4KrxtpRfsTdM:b-n6khor) (no related file):*
Please rebase

---

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1101)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1101#-MdRqKaHBmyn6RWWam2i:-MdUn7hA2ZoZo1DZU2kF:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please rebase
</blockquote></details>

Done.

---
___
*[tests/multithreaded/conn/rpma_conn_cfg_get_sq_size.c, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1101#-McxgMlw8SafouPMn0ld:-MdUn1Lo4jeGSHly2Vnq:bbqqts2) ([raw file](https://github.com/pmem/rpma/blob/13e1370f1a45ffb4fb785a5f0382b316930312c8/tests/multithreaded/conn/rpma_conn_cfg_get_sq_size.c#L13)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> Q_SIZE_EXP
> ```

Please add a comment that this is the EXPected value.
</blockquote></details>

move to common header part.
___
*[tests/multithreaded/conn/rpma_conn_cfg_get_sq_size.c, line 35 at r1](https://reviewable.io/reviews/pmem/rpma/1101#-McxjxyC2IKDk4dk89l9:-MdUn5ZZCKkYakmq9F0S:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/13e1370f1a45ffb4fb785a5f0382b316930312c8/tests/multithreaded/conn/rpma_conn_cfg_get_sq_size.c#L35)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please make common parts common.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1101#-:-MdVRcWl8P73niAFpIsc:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1101)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

___
*[tests/multithreaded/conn/rpma_conn_cfg_get_sq_size.c, line 22 at r2](https://reviewable.io/reviews/pmem/rpma/1101#-MdVgnjL3FiERYtQyFrA:-MdVgnjL3FiERYtQyFrB:b-sc901q) ([raw file](https://github.com/pmem/rpma/blob/6cf261808f7cb6ce30cd132633911ef74d8a4b4d/tests/multithreaded/conn/rpma_conn_cfg_get_sq_size.c#L22)):*
> ```C
> {
> 	struct rpma_conn_cfg_common_prestate *pr =
> 	(struct rpma_conn_cfg_common_prestate *)prestate;
> ```

Indentation +1

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1101)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[tests/multithreaded/conn/rpma_conn_cfg_get_sq_size.c, line 22 at r2](https://reviewable.io/reviews/pmem/rpma/1101#-MdVgnjL3FiERYtQyFrA:-MdViEMe-D07AZGgmeSg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6cf261808f7cb6ce30cd132633911ef74d8a4b4d/tests/multithreaded/conn/rpma_conn_cfg_get_sq_size.c#L22)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Indentation +1
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1101)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1101#-:-MdXDWYW9M7nifOs8O7g:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Pull request merged**
