### PR TITLE
tools: follow Abstract Factory design patter to call proper runner

### PR DESCRIPTION
**Pull request by grom72**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1433)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1433)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1433)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1433)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1433)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @grom72 and @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1433)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72 and @osalyk)

___
*[-- commits, line 2 at r3](https://reviewable.io/reviews/pmem/rpma/1433#-Ms4hFlF8octDRfhxeft):*
```
FAIL: commit message exceeds 72 chars per line (commit_len)
```



_Code quote:_
```
 tools: Executor class to run proper runner based on giben benchmark and config
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1433)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[-- commits, line 2 at r3](https://reviewable.io/reviews/pmem/rpma/1433#-Ms4h_mb5wdzuq45ONz3):*
given



_Code quote:_
```
giben
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1433)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[tools/perf/lib/benchmark/runner/executor.py, line 11 at r3](https://reviewable.io/reviews/pmem/rpma/1433#-Ms4mAQh5gUXA883G06k:-Ms4mAQh5gUXA883G06l:bikqh36) ([raw file](https://github.com/pmem/rpma/blob/13ae5ee12cdf3f8342ac0e5407ee94f3268fd1d2/tools/perf/lib/benchmark/runner/executor.py#L11)):*
> ```Python
> #
> 
> """the benchmark runner executor(EXPERIMENTAL)"""
> ```

Missing the space character in between.



_Code quote:_
```Python
executor(EXPERIMENTAL)
```

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1433)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1433)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/lib/benchmark/runner/executor.py, line 11 at r3](https://reviewable.io/reviews/pmem/rpma/1433#-Ms4mAQh5gUXA883G06k:-Ms4o2zCAVAbIleSTG1R:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/13ae5ee12cdf3f8342ac0e5407ee94f3268fd1d2/tools/perf/lib/benchmark/runner/executor.py#L11)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Missing the space character in between.
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1433)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[-- commits, line 2 at r3](https://reviewable.io/reviews/pmem/rpma/1433#-Ms4hFlF8octDRfhxeft):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
FAIL: commit message exceeds 72 chars per line (commit_len)
```
</blockquote></details>

Done.
___
*[-- commits, line 2 at r3](https://reviewable.io/reviews/pmem/rpma/1433#-Ms4h_mb5wdzuq45ONz3):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

given
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1433)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1433)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1433)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[-- commits, line 4 at r4](https://reviewable.io/reviews/pmem/rpma/1433#-Ms4oMNLDcXr3frwIcW7):*
runs



_Code quote:_
```
run
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1433)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[-- commits, line 5 at r4](https://reviewable.io/reviews/pmem/rpma/1433#-Ms4oWIfEU1g8Ri-dz36):*
on the given



_Code quote:_
```
on given
```

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1433)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1433)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[-- commits, line 4 at r4](https://reviewable.io/reviews/pmem/rpma/1433#-Ms4oMNLDcXr3frwIcW7):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

runs
</blockquote></details>

Done.
___
*[-- commits, line 5 at r4](https://reviewable.io/reviews/pmem/rpma/1433#-Ms4oWIfEU1g8Ri-dz36):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

on the given
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1433)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1433#-:-Ms4ouKQ6Fode64_o8Mv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1433#-:-Ms4qo62-7X-RUF9I8hV:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
