### PR TITLE
examples: improve README files (13, 14)

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1709)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1709)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[`examples/14-receive-completion-queue-SHCCH/README.md` line 15 at r1](https://reviewable.io/reviews/pmem/rpma/1709#-N0j-ylG2Y3IEBFSW_Z6:-N0j-ylG2Y3IEBFSW_Z7:undefined) ([raw file](https://github.com/pmem/rpma/blob/8b383b459775f205f8eb3b49731d0145d0587b14/examples/14-receive-completion-queue-SHCCH/README.md#L15)):*
> ```Markdown
> message and disconnects.
> 
> **Note**: In this example we use the shared completion event channel for CQ and RCQ.
> ```





_Suggestion:_
```Markdown
**Note**: In this example, we use two separate completion queues:
 - CQ for completions of sends and
 - RCQ for completions of receives.

**Note**: In this example, we use the shared completion event channel for CQ and RCQ.
```

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1709)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1709#-N0j1abM294NUs6kBZ1u:-N0j1abN0r2WnfOnKEb1:b-ji2krz) (no related file):*
I think that we should emphasize that the most interesting part can be found in the ``wait_and_validate_completion()`` function.

---

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1709)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1709)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1709#-N0j1abM294NUs6kBZ1u:-N0jAHz6-7tXq9fbL6oW:b32v57) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I think that we should emphasize that the most interesting part can be found in the ``wait_and_validate_completion()`` function.
</blockquote></details>

+1

---

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1709)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1709#-N0j1abM294NUs6kBZ1u:-N0jCeruCl2SKcLhDVq5:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

---
___
*[`examples/14-receive-completion-queue-SHCCH/README.md` line 15 at r1](https://reviewable.io/reviews/pmem/rpma/1709#-N0j-ylG2Y3IEBFSW_Z6:-N0jBA_r2uC4Ac6Rc8Rj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8b383b459775f205f8eb3b49731d0145d0587b14/examples/14-receive-completion-queue-SHCCH/README.md#L15)):*
> ```Markdown
> message and disconnects.
> 
> **Note**: In this example we use the shared completion event channel for CQ and RCQ.
> ```

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1709)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`examples/13-flush-to-persistent-GPSPM-SHCCH/README.md` line 21 at r2](https://reviewable.io/reviews/pmem/rpma/1709#-N0jDm2x8cBbhWyKO4Zy:-N0jDm2y-76AeheNc9M9:bo2dhp0) ([raw file](https://github.com/pmem/rpma/blob/86fb07934d79ec6f2f20c4497569194906a72481/examples/13-flush-to-persistent-GPSPM-SHCCH/README.md#L21)):*
> ```Markdown
> **Note**: In this example, we use the shared completion event channel for CQ and RCQ.
> To collect a completions, we use the rpma_conn_wait() function. The mechanism for collecting
> and processing completions is in the wait_and_validate_completion() function.
> ```

The most interesting part of this example is the mechanism for collecting and processing completions. It is implemented in the wait_and_validate_completion() function. We use the rpma_conn_wait() function to collect completions.



_Code quote:_
```Markdown
To collect a completions, we use the rpma_conn_wait() function. The mechanism for collecting
and processing completions is in the wait_and_validate_completion() function.
```
___
*[`examples/14-receive-completion-queue-SHCCH/README.md` line 19 at r2](https://reviewable.io/reviews/pmem/rpma/1709#-N0jESn9DF52q1tL4pOu:-N0jESn9DF52q1tL4pOv:bou1pfx) ([raw file](https://github.com/pmem/rpma/blob/86fb07934d79ec6f2f20c4497569194906a72481/examples/14-receive-completion-queue-SHCCH/README.md#L19)):*
> ```Markdown
>  - RCQ for completions of receives.
> To collect a completions, we use the rpma_conn_wait() function. The mechanism for collecting
> and processing completions is in the wait_and_validate_completion() function.
> ```

The mechanism for collecting and processing completions is implemented in the wait_and_validate_completion() function. We use the rpma_conn_wait() function to collect completions.



_Code quote:_
```Markdown
To collect a completions, we use the rpma_conn_wait() function. The mechanism for collecting
and processing completions is in the wait_and_validate_completion() function.
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1709)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`examples/13-flush-to-persistent-GPSPM-SHCCH/README.md` line 21 at r2](https://reviewable.io/reviews/pmem/rpma/1709#-N0jDm2x8cBbhWyKO4Zy:-N0jGo3KDV6KhvyGS2fk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/86fb07934d79ec6f2f20c4497569194906a72481/examples/13-flush-to-persistent-GPSPM-SHCCH/README.md#L21)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The most interesting part of this example is the mechanism for collecting and processing completions. It is implemented in the wait_and_validate_completion() function. We use the rpma_conn_wait() function to collect completions.
</blockquote></details>

Done.
___
*[`examples/14-receive-completion-queue-SHCCH/README.md` line 19 at r2](https://reviewable.io/reviews/pmem/rpma/1709#-N0jESn9DF52q1tL4pOu:-N0jGNkpA5IyfrXMd4VK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/86fb07934d79ec6f2f20c4497569194906a72481/examples/14-receive-completion-queue-SHCCH/README.md#L19)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The mechanism for collecting and processing completions is implemented in the wait_and_validate_completion() function. We use the rpma_conn_wait() function to collect completions.
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1709)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`examples/13-flush-to-persistent-GPSPM-SHCCH/README.md` line 21 at r2](https://reviewable.io/reviews/pmem/rpma/1709#-N0jDm2x8cBbhWyKO4Zy:-N0jZ7L59gpe4MwU1YaY:bczeemy) ([raw file](https://github.com/pmem/rpma/blob/86fb07934d79ec6f2f20c4497569194906a72481/examples/13-flush-to-persistent-GPSPM-SHCCH/README.md#L21)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

What about "The most interesting part of this example is the " ?

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1709)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`examples/13-flush-to-persistent-GPSPM-SHCCH/README.md` line 21 at r2](https://reviewable.io/reviews/pmem/rpma/1709#-N0jDm2x8cBbhWyKO4Zy:-N0j_pbUAIdmAiivD1Xu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/86fb07934d79ec6f2f20c4497569194906a72481/examples/13-flush-to-persistent-GPSPM-SHCCH/README.md#L21)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

What about "The most interesting part of this example is the " ?
</blockquote></details>

Done.

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1709)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1709)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[`examples/14-receive-completion-queue-SHCCH/README.md` line 19 at r2](https://reviewable.io/reviews/pmem/rpma/1709#-N0jESn9DF52q1tL4pOu:-N0jobOE6A85PjbyMKt6:b-o7360n) ([raw file](https://github.com/pmem/rpma/blob/86fb07934d79ec6f2f20c4497569194906a72481/examples/14-receive-completion-queue-SHCCH/README.md#L19)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You have reverted the old version.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1709)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[`examples/14-receive-completion-queue-SHCCH/README.md` line 19 at r2](https://reviewable.io/reviews/pmem/rpma/1709#-N0jESn9DF52q1tL4pOu:-N0jpTfzDoin9uG2vnt_:b3atjbf) ([raw file](https://github.com/pmem/rpma/blob/86fb07934d79ec6f2f20c4497569194906a72481/examples/14-receive-completion-queue-SHCCH/README.md#L19)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

You have reverted the old version.
</blockquote></details>

Done. Sorry :)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1709#-:-N0jxkEbBAIdkr6OrwMO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1709)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1709#-:-N0khVsb0ZJztT5HqWqT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1709)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
