### PR TITLE
rpma: mark rpma_write_atomic() as deprecated

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1608)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1608)* status: all files reviewed, 5 unresolved discussions (waiting on @osalyk)

___
*[CHANGELOG.md, line 11 at r1](https://reviewable.io/reviews/pmem/rpma/1608#-MxYocIE5kr-7wyls7NQ:-MxYocIE5kr-7wyls7NR:b-57tdxn) ([raw file](https://github.com/pmem/rpma/blob/1cb90005009d152f7ff08dfa89a7a5c690515c31/CHANGELOG.md#L11)):*
> ```Markdown
> ### Deprecated
> - API:
> 	- rpma_write_atomic - replaced with rpma_atomic_write
> ```

Spaces instead of tabs, please.



_Code quote:_
```Markdown
	- rpma_write_atomic
```
___
*[CHANGELOG.md, line 12 at r1](https://reviewable.io/reviews/pmem/rpma/1608#-MxYogWG9rxp3wHYr7TC:-MxYogWG9rxp3wHYr7TD:b2oemvb) ([raw file](https://github.com/pmem/rpma/blob/1cb90005009d152f7ff08dfa89a7a5c690515c31/CHANGELOG.md#L12)):*
> ```Markdown
> - API:
> 	- rpma_write_atomic - replaced with rpma_atomic_write
> ### Fixed
> ```

one empty line in between



_Code quote:_
```Markdown
	- rpma_write_atomic - replaced with rpma_atomic_write
### Fixed
```
___
*[src/include/librpma.h, line 2483 at r1](https://reviewable.io/reviews/pmem/rpma/1608#-MxYovt9CRpEThZnI8I1:-MxYovt9CRpEThZnI8I2:blridhb) ([raw file](https://github.com/pmem/rpma/blob/1cb90005009d152f7ff08dfa89a7a5c690515c31/src/include/librpma.h#L2483)):*
> ```objc
>  *
>  * DEPRECATED
>  * This API call should be replaced with rpma_atomic_write()
> ```

```
 * DEPRECATED
 * This API call should be replaced with rpma_atomic_write().
 * This is an example snippet of code using the old API:
 *
 *	....
 *
 * The above snippet should be replaced with
 * the following one using the new API:
 *
 *	....
 *
```



_Code quote:_
```objc
 * This API call should be replaced with rpma_atomic_write()
```
___
*[src/include/librpma.h, line 2483 at r1](https://reviewable.io/reviews/pmem/rpma/1608#-MxYqjcx6M-R9VbsNHno:-MxYqjcx6M-R9VbsNHnp:bouyu0b) ([raw file](https://github.com/pmem/rpma/blob/1cb90005009d152f7ff08dfa89a7a5c690515c31/src/include/librpma.h#L2483)):*
> ```objc
>  *
>  * DEPRECATED
>  * This API call should be replaced with rpma_atomic_write()
> ```

`... (). ` (dot at the end)



_Code quote:_
```objc
e()
```
___
*[src/include/librpma.h, line 2484 at r1](https://reviewable.io/reviews/pmem/rpma/1608#-MxYp6_q4R4iIE6mJ5hV:-MxYp6_q4R4iIE6mJ5hW:b-u17ie2) ([raw file](https://github.com/pmem/rpma/blob/1cb90005009d152f7ff08dfa89a7a5c690515c31/src/include/librpma.h#L2484)):*
> ```objc
>  * DEPRECATED
>  * This API call should be replaced with rpma_atomic_write()
>  * 
> ```

redundant two spaces at the end



_Code quote:_
```objc
 *··
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1608)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[CHANGELOG.md, line 11 at r1](https://reviewable.io/reviews/pmem/rpma/1608#-MxYocIE5kr-7wyls7NQ:-MxYt0eUDzjq0-Rr8PPB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1cb90005009d152f7ff08dfa89a7a5c690515c31/CHANGELOG.md#L11)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Spaces instead of tabs, please.
</blockquote></details>

Done.
___
*[CHANGELOG.md, line 12 at r1](https://reviewable.io/reviews/pmem/rpma/1608#-MxYogWG9rxp3wHYr7TC:-MxYt13j3YWL57uK_p_x:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1cb90005009d152f7ff08dfa89a7a5c690515c31/CHANGELOG.md#L12)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

one empty line in between
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2483 at r1](https://reviewable.io/reviews/pmem/rpma/1608#-MxYqjcx6M-R9VbsNHno:-MxYt4ogA9MOSwjGWB-E:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1cb90005009d152f7ff08dfa89a7a5c690515c31/src/include/librpma.h#L2483)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`... (). ` (dot at the end)
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2483 at r1](https://reviewable.io/reviews/pmem/rpma/1608#-MxYovt9CRpEThZnI8I1:-MxYtpDyDcToCsV0V0bs:bu50vid) ([raw file](https://github.com/pmem/rpma/blob/1cb90005009d152f7ff08dfa89a7a5c690515c31/src/include/librpma.h#L2483)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
 * DEPRECATED
 * This API call should be replaced with rpma_atomic_write().
 * This is an example snippet of code using the old API:
 *
 *	....
 *
 * The above snippet should be replaced with
 * the following one using the new API:
 *
 *	....
 *
```
</blockquote></details>

@grom72 do you think this change is needed?
___
*[src/include/librpma.h, line 2484 at r1](https://reviewable.io/reviews/pmem/rpma/1608#-MxYp6_q4R4iIE6mJ5hV:-MxYtEVlAUy_OOMUGWBA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1cb90005009d152f7ff08dfa89a7a5c690515c31/src/include/librpma.h#L2484)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

redundant two spaces at the end
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1608)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/1608#-MxYuPDy2VbinHmGYJ82):*
`rpma: mark rpma_write_atomic() as deprecated`



_Code quote:_
```
rpma: mark as deprecated rpma_write_atomic()
```

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1608)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[src/include/librpma.h, line 2483 at r1](https://reviewable.io/reviews/pmem/rpma/1608#-MxYovt9CRpEThZnI8I1:-MxYuz8790_oczMoH926:b2nign6) ([raw file](https://github.com/pmem/rpma/blob/1cb90005009d152f7ff08dfa89a7a5c690515c31/src/include/librpma.h#L2483)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

@grom72 do you think this change is needed?
</blockquote></details>

yes

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1608)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/1608#-MxYuPDy2VbinHmGYJ82):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`rpma: mark rpma_write_atomic() as deprecated`
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2483 at r1](https://reviewable.io/reviews/pmem/rpma/1608#-MxYovt9CRpEThZnI8I1:-MxZCV-EDTkR1rueE0gS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1cb90005009d152f7ff08dfa89a7a5c690515c31/src/include/librpma.h#L2483)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

yes
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1608)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1608#-:-MxZFWIf95W72SP2uRtd:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1608#-:-MxZMUGV9q6fGEVhH0EE:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1608)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1608)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1608#-MxZkNJy0SSWQPQQxf1_:-MxZkNJz6XLSzZKDK_hz:b-o92tik) (no related file):*
Waiting for #1595 and #1601

---

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1608#-:-Mx_1p9q8biuoufejAXX:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1608)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
