### PR TITLE
rpma: fix memory leak in error handling of rpma_conn_req_connect()

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1727)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1727)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`src/conn_req.c` line 462 at r1](https://reviewable.io/reviews/pmem/rpma/1727#-N1cSKIh60BtVnQ7OQjs:-N1cSKIh60BtVnQ7OQjt:undefined) ([raw file](https://github.com/pmem/rpma/blob/c662a4d78916af6240ff9faab500416b66cf6443/src/conn_req.c#L462)):*
> ```C
> 		ret = rpma_conn_req_accept(req, &conn_param, conn_ptr);
> 	else
> 		ret = rpma_conn_req_connect_active(req, &conn_param, conn_ptr);
> ```





_Suggestion:_
```C
	if ((*req_ptr)->edata)
		ret = rpma_conn_req_accept(*req_ptr, &conn_param, conn_ptr);
	else
		ret = rpma_conn_req_connect_active(*req_ptr, &conn_param, conn_ptr);
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1727)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`src/conn_req.c` line 462 at r1](https://reviewable.io/reviews/pmem/rpma/1727#-N1cSKIh60BtVnQ7OQjs:-N1cZfbD0BCQdfiPKYrK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c662a4d78916af6240ff9faab500416b66cf6443/src/conn_req.c#L462)):*
> ```C
> 		ret = rpma_conn_req_accept(req, &conn_param, conn_ptr);
> 	else
> 		ret = rpma_conn_req_connect_active(req, &conn_param, conn_ptr);
> ```

Done.

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1727)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`src/conn_req.c` line 433 at r2](https://reviewable.io/reviews/pmem/rpma/1727#-N1cd5ejAm3lX6w8jptu:-N1cd5ejAm3lX6w8jptv:undefined) ([raw file](https://github.com/pmem/rpma/blob/9f4f6d145c5398bac51c7d4a6425c419daacc518/src/conn_req.c#L433)):*
> ```C
>  * rpma_conn_req_connect -- prepare connection parameters and request
>  * connecting a connection request (either active or passive). When done
>  * release the connection request object (regardless of the result).
> ```





_Suggestion:_
```C
release (delete)
```

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1727#-:-N1czvIi5HJEyEWmfyOo:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1727)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`src/conn_req.c` line 433 at r2](https://reviewable.io/reviews/pmem/rpma/1727#-N1cd5ejAm3lX6w8jptu:-N1d52Dr9zm-1K-534pQ:bfp6chj) ([raw file](https://github.com/pmem/rpma/blob/9f4f6d145c5398bac51c7d4a6425c419daacc518/src/conn_req.c#L433)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@grom72 please resolve

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1727)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1727#-:-N1gQH0l39gKC3AdPVob:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
