### PR TITLE
remove and hide functions from the rpma_err module

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/464)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 26 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/464)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[src/rpma_err.c, line 14 at r1](https://reviewable.io/reviews/pmem/rpma/464#-MIJEsgi-8quEnai6MGX:-MIJEsgi-8quEnai6MGY:b-jcz9g8) ([raw file](https://github.com/pmem/rpma/blob/d86378aac8c13ea4743ca0ecc2ddd1dea656b6fb/src/rpma_err.c#L14)):*
> ```C
> int Rpma_provider_error = 0;
> 
> /* public librpma API */
> ```

You have to create a `/* internal librpma API */` section and move the `rpma_err_get_provider_error()` function into it.
___
*[src/include/librpma.h, line 85 at r1](https://reviewable.io/reviews/pmem/rpma/464#-MIJFjGF119fx-Co8M3p:-MIJFjGF119fx-Co8M3q:bgcho14) ([raw file](https://github.com/pmem/rpma/blob/d86378aac8c13ea4743ca0ecc2ddd1dea656b6fb/src/include/librpma.h#L85)):*
> ```objc
>  * - RPMA_E_PROVIDER - rdma_getaddrinfo(), rdma_create_id(), rdma_bind_addr()
>  *   or rdma_resolve_addr() failed, errno can be checked using
>  *   rpma_err_get_provider_error()
> ```

```
- RPMA_E_PROVIDER - rdma_getaddrinfo(), rdma_create_id(), rdma_bind_addr() or rdma_resolve_addr() failed, the exact cause of the error can be read from the log
```
___
*[src/include/librpma.h, line 116 at r1](https://reviewable.io/reviews/pmem/rpma/464#-MIJGWpv2sHORAXmqTSw:-MIJGWpv2sHORAXmqTSx:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/d86378aac8c13ea4743ca0ecc2ddd1dea656b6fb/src/include/librpma.h#L116)):*
> ```objc
>  * - RPMA_E_INVAL - dev or is_odp_capable is NULL
>  * - RPMA_E_PROVIDER - ibv_query_device_ex() failed, errno can be checked using
>  *   rpma_err_get_provider_error()
> ```

.

**Review by ldorau — APPROVED** [review]
> Reviewed 22 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/464)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/464)* status: 24 of 26 files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[src/rpma_err.c, line 14 at r1](https://reviewable.io/reviews/pmem/rpma/464#-MIJEsgi-8quEnai6MGX:-MIJHNa93L_3K8Qa7T2y:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d86378aac8c13ea4743ca0ecc2ddd1dea656b6fb/src/rpma_err.c#L14)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You have to create a `/* internal librpma API */` section and move the `rpma_err_get_provider_error()` function into it.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 85 at r1](https://reviewable.io/reviews/pmem/rpma/464#-MIJFjGF119fx-Co8M3p:-MIJI0dS2sRLlaSOUYaC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d86378aac8c13ea4743ca0ecc2ddd1dea656b6fb/src/include/librpma.h#L85)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```
- RPMA_E_PROVIDER - rdma_getaddrinfo(), rdma_create_id(), rdma_bind_addr() or rdma_resolve_addr() failed, the exact cause of the error can be read from the log
```
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 116 at r1](https://reviewable.io/reviews/pmem/rpma/464#-MIJGWpv2sHORAXmqTSw:-MIJI9Km7L_GrOLR0e2C:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d86378aac8c13ea4743ca0ecc2ddd1dea656b6fb/src/include/librpma.h#L116)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 3 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/464)* status: 24 of 26 files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/464)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 26 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/464)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/464#-:-MIJPWIR-e1hShA7EGPA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/464#-:-MIJRQuV6PwB7U-0Ipsw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
