### PR TITLE
tools: perf: improve data tables

### PR DESCRIPTION
**Pull request by janekmi**
- collect a common subset of x-values
- replace missing y-values with '-'

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1234)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1234)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/figure.py, line 257 at r1](https://reviewable.io/reviews/pmem/rpma/1234#-MiMUuotED9cvQDn3K08:-MiMUuotED9cvQDn3K09:b-134zd3) ([raw file](https://github.com/pmem/rpma/blob/3373c53b869907ba14295919132c94d4428179f6/tools/perf/lib/figure.py#L257)):*
> ```
> str(points.get(xarg, '-')))
> ```

Please add setting a precision here too (maybe like `"{0:.2f}".format(a)` ?)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1234)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/lib/figure.py, line 257 at r1](https://reviewable.io/reviews/pmem/rpma/1234#-MiMUuotED9cvQDn3K08:-MiM_Vu58zF463EXsgtW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3373c53b869907ba14295919132c94d4428179f6/tools/perf/lib/figure.py#L257)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> str(points.get(xarg, '-')))
> ```

Please add setting a precision here too (maybe like `"{0:.2f}".format(a)` ?)
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1234)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

___
*[tools/perf/lib/figure.py, line 257 at r1](https://reviewable.io/reviews/pmem/rpma/1234#-MiMUuotED9cvQDn3K08:-MiM_i8pBNDHmDuZBn11:b-k1hkqq) ([raw file](https://github.com/pmem/rpma/blob/3373c53b869907ba14295919132c94d4428179f6/tools/perf/lib/figure.py#L257)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Great :-)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1234)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1234#-MiMafXW17l8g5-3S3kQ:-MiMc6uZBAuv99pLeVYS:b-kev0sl) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

CI builds failed
</blockquote></details>

:crossed_fingers: 

---

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1234)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1234#-:-MiMdJUQCTp_5DdeAZRX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1234#-:-MiQ3IXC8WgmRG8cIK6W:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1234)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/figure.py, line 164 at r3](https://reviewable.io/reviews/pmem/rpma/1234#-MiQ6ryt8HRMYk5yWIT9:-MiQ6ryt8HRMYk5yWITA:b-7o2mwo) ([raw file](https://github.com/pmem/rpma/blob/86f3b13620d8fa3f966ba3f0bf8345b107d7d67b/tools/perf/lib/figure.py#L164)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>     def _get_xcommon(self):
>         """generate an ordered list of common x-values"""
>         xlist = [p[0] for oneseries in self.series for p in oneseries['points']]
>         xlist.sort()
>         return list(set(xlist))
> ```
</details>


Does it show all x values even if there are no data? I mean: does it prevent from the following issue?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1234)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/lib/figure.py, line 164 at r3](https://reviewable.io/reviews/pmem/rpma/1234#-MiQ6ryt8HRMYk5yWIT9:-MiQL14pCJSE5Pi_RtR2:bc2nsnu) ([raw file](https://github.com/pmem/rpma/blob/86f3b13620d8fa3f966ba3f0bf8345b107d7d67b/tools/perf/lib/figure.py#L164)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>     def _get_xcommon(self):
>         """generate an ordered list of common x-values"""
>         xlist = [p[0] for oneseries in self.series for p in oneseries['points']]
>         xlist.sort()
>         return list(set(xlist))
> ```

Does it show all x values even if there are no data? I mean: does it prevent from the following issue?



</blockquote></details>

Yes. It should.

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1234)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1234)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/figure.py, line 164 at r3](https://reviewable.io/reviews/pmem/rpma/1234#-MiQ6ryt8HRMYk5yWIT9:-MiQShQsAmimFPUxr0-B:b-v803ou) ([raw file](https://github.com/pmem/rpma/blob/86f3b13620d8fa3f966ba3f0bf8345b107d7d67b/tools/perf/lib/figure.py#L164)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Yes. It should.
</blockquote></details>

I will verify that.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1234)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/figure.py, line 163 at r3](https://reviewable.io/reviews/pmem/rpma/1234#-MiQZ1Vd9b8Vu2auJ6Y-:-MiQZ1Vd9b8Vu2auJ6Y0:br3qcdi) ([raw file](https://github.com/pmem/rpma/blob/86f3b13620d8fa3f966ba3f0bf8345b107d7d67b/tools/perf/lib/figure.py#L163)):*
> ```
> xlist.sort()
> ```

It doesn't look too good ;-)


___
*[tools/perf/lib/figure.py, line 164 at r3](https://reviewable.io/reviews/pmem/rpma/1234#-MiQ6ryt8HRMYk5yWIT9:-MiQYv9_16MqL8R6tQx2:bo0pbb6) ([raw file](https://github.com/pmem/rpma/blob/86f3b13620d8fa3f966ba3f0bf8345b107d7d67b/tools/perf/lib/figure.py#L164)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I will verify that.
</blockquote></details>

It is OK

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1234)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1234#-MiQ_4dKBi-rYgLTZDqx:-MiQ_4dKBi-rYgLTZDqy:b-n6khor) (no related file):*
Please rebase

---

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1234)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/lib/figure.py, line 163 at r3](https://reviewable.io/reviews/pmem/rpma/1234#-MiQZ1Vd9b8Vu2auJ6Y-:-MiQ_WOcDMxVy-qKMD-A:bj5xl4u) ([raw file](https://github.com/pmem/rpma/blob/86f3b13620d8fa3f966ba3f0bf8345b107d7d67b/tools/perf/lib/figure.py#L163)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> xlist.sort()
> ```

It doesn't look too good ;-)



</blockquote></details>

:rofl:

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1234)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1234#-MiQ_4dKBi-rYgLTZDqx:-MiQawYOBwyxBKajjlwb:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please rebase
</blockquote></details>

Done.

---

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1234)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1234)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1234)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/lib/figure.py, line 163 at r3](https://reviewable.io/reviews/pmem/rpma/1234#-MiQZ1Vd9b8Vu2auJ6Y-:-MiQho1L3cKLJGzoyeny:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/86f3b13620d8fa3f966ba3f0bf8345b107d7d67b/tools/perf/lib/figure.py#L163)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

:rofl: 
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1234)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1234)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
