### PR TITLE
common: 0.9.0-rc1 release

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/471)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/471)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[CHANGELOG.md, line 8 at r1](https://reviewable.io/reviews/pmem/rpma/471#-MIKChBD6bD5OVIubO_M:-MIKChBD6bD5OVIubO_N:bacqqj6) ([raw file](https://github.com/pmem/rpma/blob/c571797954cf97d70754c4bad461a86cb1ad75f2/CHANGELOG.md#L8)):*
> ```
> 0.9.0-rc1
> ```

And not `0.9-rc1` ?
`0.9.0-rc1` looks a bit weird to me.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/471)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[CHANGELOG.md, line 8 at r1](https://reviewable.io/reviews/pmem/rpma/471#-MIKChBD6bD5OVIubO_M:-MIKDzBX0ihNp4UcCmvY:b-1xtwyg) ([raw file](https://github.com/pmem/rpma/blob/c571797954cf97d70754c4bad461a86cb1ad75f2/CHANGELOG.md#L8)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 0.9.0-rc1
> ```

And not `0.9-rc1` ?
`0.9.0-rc1` looks a bit weird to me.
</blockquote></details>

https://semver.org/spec/v2.0.0.html I tried to adhere to a proposed standard.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/471#-:-MIKH36K8vWpKH0G1KX6:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[CHANGELOG.md, line 8 at r1](https://reviewable.io/reviews/pmem/rpma/471#-MIKChBD6bD5OVIubO_M:-MIKGswO6-M3d5CON-cL:b-ypyo6n) ([raw file](https://github.com/pmem/rpma/blob/c571797954cf97d70754c4bad461a86cb1ad75f2/CHANGELOG.md#L8)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

https://semver.org/spec/v2.0.0.html I tried to adhere to a proposed standard.
</blockquote></details>

:+1:  for @janekmi

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/471)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/471#-:-MIKIC2B25taEc7PyXTG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
