### PR TITLE
test: add own server for the rpma_conn_get_private_data MT test

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1048)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
ping

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1048#-:-Mam-Fo02Ea5rtmkBd9U:bb7mm0n)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1048)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1048#-:-Mb0y_nl-K2SXIv-CQ5k:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Comment by ldorau** [comment]
ping :-)

**Review by osalyk — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1048)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @grom72)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1048#-:-Mbq6OcG6K5OWMEo4kd0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1048#-Mbq65Ju9UMWrMMmzrLp:-Mbq65Ju9UMWrMMmzrLq:b-da4ocw) (no related file):*
I expect to have it replaced with a generally useful server when we got an inter-process synchronization for the MTT framework. But, it is a reasonable step forward.

---

**Pull request merged**
