### PR TITLE
tools: add StrictHostKeyChecking=no option to ssh

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/769)

### CODE REVIEW

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/769#-:-MRxvbyH7tFfG-p4h82K:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by yangx-jy — COMMENTED** [review]
:lgtm:

Sorry for missing it here.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/769#-:-MRxwAAv5TF6vnVvyYgH:b-1cuoaa)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by yangx-jy — COMMENTED** [review]
After thinking about it agin, only the first ssh connection needs the option so it seems unnecessary for the second ssh connection.

Of course, It is OK for me to add it.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/769#-:-MRxypwG1B2KH7M-XzI1:b2f6y89)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
Why? Is it cached or something?

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/769#-:-MRy-LMkDge7WpAIUfik:bmqze5j)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by yangx-jy — COMMENTED** [review]
Yes, the host key will be cached (e.g. /root/.ssh/known_hosts) after the fist ssh connection.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/769#-:-MRy1KYn6sTusa60cj0f:b-2jyikf)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — APPROVED** [review]
I would keep this option just in case somebody would reorganize this code and would not notice this functionality.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/769#-:-MRyAon9DUWJR9Y3UU2x:bvbhonk)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
OK, I agree to keep it

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/769#-:-MRyGTTzAP7_FRkUcbFW:b74ktq9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/769)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/769#-:-MRyRDKTBYr_GkCTZ3F3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Comment by yangx-jy** [comment]
Agreed.  It is reasonable to keep it.

**Pull request merged**
