### PR TITLE
tools: mark old bash scripts as deprecated

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1493)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1493)* status: 4 of 14 files reviewed, 1 unresolved discussion (waiting on @grom72 and @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1493#-MtH8rekEBGCkwq7w7RM:-MtH8rel73oztCxXwZwU:b-ralmay) (no related file):*
ib_read.py can not be used directly. Instead of that report_bench.py with adjusted figure (read.json) shall be used.



_Code quote (from tools/perf/ib_read.sh):_
```Shell
# DEPRECATED - please use ./lib/benchmark/runner/ib_read.py instead
```

---

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1493)* status: 11 of 14 files reviewed, 4 unresolved discussions (waiting on @grom72 and @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1493#-MtHANkU162uuyzIfUvJ:-MtHANkU162uuyzIfUvK:bq8oj1l) (no related file):*
Main repo CHANGELOG.md shall be updated as well to inform in general about these changes in the benchmark environment.

---
___
*[tools/perf/lib/benchmark/base.py, line 194 at r1](https://reviewable.io/reviews/pmem/rpma/1493#-MtH9kZL9NxC4-uy2cNK:-MtH9kZL9NxC4-uy2cNL:bve4ij6) ([raw file](https://github.com/pmem/rpma/blob/fa673e3109d39b6c74033f57d4f729518c2333ac/tools/perf/lib/benchmark/base.py#L194)):*
> ```Python
>         if config.get('dummy_results', False):
>             runner = Dummy
>         elif '.sh' in self.__oneseries['tool']:
> ```

These two lines shall be marked as deprecated instead of comment above



_Code quote:_
```Python
        elif '.sh' in self.__oneseries['tool']:
            runner = Bash
```
___
*[tools/perf/lib/benchmark/runner/__init__.py, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/1493#-MtH9xrw8WlBHidTim22:-MtH9xrw8WlBHidTim23:b-jjdjg9) ([raw file](https://github.com/pmem/rpma/blob/fa673e3109d39b6c74033f57d4f729518c2333ac/tools/perf/lib/benchmark/runner/__init__.py#L20)):*
> ```Python
> 
> from .base import BaseRunner
> from .bash import Bash
> ```

Above comment closer to import line



_Code quote:_
```Python
from .bash import Bash
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1493)* status: 12 of 14 files reviewed, 4 unresolved discussions (waiting on @grom72 and @haichangsi)

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1493)* status: 12 of 14 files reviewed, 4 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

**Comment by ldorau** [comment]
> I used a deprecated library to mark deprecated classes and methods with @deprecated decorator but then I realized that this requires installing a new library so I dropped this idea
> 
Very good decision :-)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 3 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1493)* status: 12 of 14 files reviewed, 8 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[tools/perf/bench_common.sh, line 9 at r1](https://reviewable.io/reviews/pmem/rpma/1493#-MtMj7as-Cr7g9lOmlwS:-MtMj7atARW4mZFLrC38:b-21yll1) ([raw file](https://github.com/pmem/rpma/blob/fa673e3109d39b6c74033f57d4f729518c2333ac/tools/perf/bench_common.sh#L9)):*
> ```Shell
> 
> #
> # bench_common.sh -- a single-sided ib_read_lat/bw
> ```

`DEPRECATED` should be more visible ("at the first place"):

```
#
# bench_common.sh -- (DEPRECATED) a single-sided ib_read_lat/bw
#                    and Fio tools common (EXPERIMENTAL)
#
```



_Code quote:_
```Shell
#
# bench_common.sh -- a single-sided ib_read_lat/bw
#                    and Fio tools common (EXPERIMENTAL)
#
# DEPRECATED
```
___
*[tools/perf/csv2standardized.py, line 10 at r1](https://reviewable.io/reviews/pmem/rpma/1493#-MtMjwL-01h3MIXlHmhq:-MtMjwL-01h3MIXlHmhr:b-akvf67) ([raw file](https://github.com/pmem/rpma/blob/fa673e3109d39b6c74033f57d4f729518c2333ac/tools/perf/csv2standardized.py#L10)):*
> ```Python
> 
> #
> # csv2standardized.py -- standardize a CSV (EXPERIMENTAL)
> ```

```
#
# csv2standardized.py -- (DEPRECATED) standardize a CSV (EXPERIMENTAL)
#
```



_Code quote:_
```Python
#

# DEPRECATED - no need to use in the new Python framework

#
# csv2standardized.py -- standardize a CSV (EXPERIMENTAL)
#
```
___
*[tools/perf/csv_compare.py, line 8 at r1](https://reviewable.io/reviews/pmem/rpma/1493#-MtMkEM-3tBEyCUx-46G:-MtMkEM-3tBEyCUx-46H:b-7c9m92) ([raw file](https://github.com/pmem/rpma/blob/fa673e3109d39b6c74033f57d4f729518c2333ac/tools/perf/csv_compare.py#L8)):*
> ```Python
> 
> #
> # csv_compare.py -- compare CSV files (EXPERIMENTAL)
> ```

```
#
# csv_compare.py -- (DEPRECATED) compare CSV files (EXPERIMENTAL)
#
```



_Code quote:_
```Python
#
# csv_compare.py -- compare CSV files (EXPERIMENTAL)
#
```
___
*[tools/perf/csv_compare.py, line 14 at r1](https://reviewable.io/reviews/pmem/rpma/1493#-MtMkMFX7FcGIbycljKJ:-MtMkMFX7FcGIbycljKK:bcglv6l) ([raw file](https://github.com/pmem/rpma/blob/fa673e3109d39b6c74033f57d4f729518c2333ac/tools/perf/csv_compare.py#L14)):*
> ```Python
> #
> 
> # DEPRECATED - no need to use in the new Python framework
> ```

No need for this line. That line is enough:
`# csv_compare.py -- (DEPRECATED) compare CSV files (EXPERIMENTAL)`



_Code quote:_
```Python
# DEPRECATED - no need to use in the new Python framework
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1493)* status: 12 of 14 files reviewed, 9 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[tools/perf/fio_json2csv.py, line 10 at r1](https://reviewable.io/reviews/pmem/rpma/1493#-MtMkiAZ6QoH1FgWr9V0:-MtMkiA_5mu5qMVw3Pnp:b-hpojk0) ([raw file](https://github.com/pmem/rpma/blob/fa673e3109d39b6c74033f57d4f729518c2333ac/tools/perf/fio_json2csv.py#L10)):*
> ```Python
> 
> """fio-json2csv.py -- generate a CSV from FIO JSON (EXPERIMENTAL)
>    DEPRECATED - no need to use in the new Python framework"""
> ```

IMHO this is enough, @grom72 what do you think?

```
"""fio-json2csv.py -- (DEPRECATED) generate a CSV from FIO JSON (EXPERIMENTAL)"""
```

Please change the rest in the same way.



_Code quote:_
```Python
# DEPRECATED - no need to use in the new Python framework

"""fio-json2csv.py -- generate a CSV from FIO JSON (EXPERIMENTAL)
   DEPRECATED - no need to use in the new Python framework"""
```

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1493)* status: 12 of 14 files reviewed, 12 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[tools/perf/fio_json2csv.py, line 10 at r1](https://reviewable.io/reviews/pmem/rpma/1493#-MtMkiAZ6QoH1FgWr9V0:-MtMmuUz0xwPWl5TS609:b32v57) ([raw file](https://github.com/pmem/rpma/blob/fa673e3109d39b6c74033f57d4f729518c2333ac/tools/perf/fio_json2csv.py#L10)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

IMHO this is enough, @grom72 what do you think?

```
"""fio-json2csv.py -- (DEPRECATED) generate a CSV from FIO JSON (EXPERIMENTAL)"""
```

Please change the rest in the same way.
</blockquote></details>

+1

**Comment by ldorau** [comment]
Not valid

**Pull request closed without merging**
