### PR TITLE
common: fix description of librpma

### PR DESCRIPTION
**Pull request by ldorau**
librpma is a C library to simplify accessing
persistent memory (PMem) and not persistent memory devices.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/546)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/546)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/546#-:-MJ7WwVA6uoP0joC8vrh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
@janekmi please review

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/546#-:-MJB1rh-9iZM2L-GHCS5:b-f79qgk)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/546#-:-MJTuyOD-hACCgzuA42Q:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/546)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/546#-MJTv8QPA6DxtZU8sDdp:-MJTv8QPA6DxtZU8sDdq:bef0q57) (no related file):*
Please fix also README.md and all other occurrences.
Probably you may find also a similar sentence on gh-pages of rpma and pmdk as well.

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/546)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/546#-MJTv8QPA6DxtZU8sDdp:-MJVYWbO5hBZ-L-SxJj5:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please fix also README.md and all other occurrences.
Probably you may find also a similar sentence on gh-pages of rpma and pmdk as well.
</blockquote></details>

Done.

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/546)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/546#-MJTv8QPA6DxtZU8sDdp:-MJVeEX4Bq47BRTKi7qj:bu02lmw) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

https://github.com/pmem/rpma/pull/549

---

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/546#-:-MJWl45d3VVuSXuBVRFH:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Pull request merged**
