### PR TITLE
common: set sanitizer and coverage flags only in the main CMake file

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/460)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/460)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/460)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[examples/CMakeLists.txt, line 24 at r1](https://reviewable.io/reviews/pmem/rpma/460#-MIIZWAi9JbpqRnkkuX0:-MIIZWAi9JbpqRnkkuX1:b-ayk) ([raw file](https://github.com/pmem/rpma/blob/962eeda6eb297c9d9b39b5d65d48449ca7a86b3a/examples/CMakeLists.txt#L24)):*
> ```
> USE_ASAN
> ```
do we remove this fully?
___
*[examples/CMakeLists.txt, line 27 at r1](https://reviewable.io/reviews/pmem/rpma/460#-MIIZbMq6LcYsTG-HcrM:-MIIZbMrE_iHR1uLt5JA:b-ysnebk) ([raw file](https://github.com/pmem/rpma/blob/962eeda6eb297c9d9b39b5d65d48449ca7a86b3a/examples/CMakeLists.txt#L27)):*
> ```
> USE_UBSAN
> ```
.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/460)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[examples/CMakeLists.txt, line 24 at r1](https://reviewable.io/reviews/pmem/rpma/460#-MIIZWAi9JbpqRnkkuX0:-MIIavZO0en2tJUxlgsa:b-dlm19v) ([raw file](https://github.com/pmem/rpma/blob/962eeda6eb297c9d9b39b5d65d48449ca7a86b3a/examples/CMakeLists.txt#L24)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> USE_ASAN
> ```
do we remove this fully?
</blockquote></details>

??? I have only moved it to the main CMake file
___
*[examples/CMakeLists.txt, line 27 at r1](https://reviewable.io/reviews/pmem/rpma/460#-MIIZbMq6LcYsTG-HcrM:-MIIbAqEAYWy9gxmcVaK:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/962eeda6eb297c9d9b39b5d65d48449ca7a86b3a/examples/CMakeLists.txt#L27)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> USE_UBSAN
> ```
.
</blockquote></details>

.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/460)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[examples/CMakeLists.txt, line 24 at r1](https://reviewable.io/reviews/pmem/rpma/460#-MIIZWAi9JbpqRnkkuX0:-MIIbJ4l8eLVc8YCZGeD:b-56nwv7) ([raw file](https://github.com/pmem/rpma/blob/962eeda6eb297c9d9b39b5d65d48449ca7a86b3a/examples/CMakeLists.txt#L24)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

??? I have only moved it to the main CMake file
</blockquote></details>

It should be set only once in the main CMake file.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/460#-:-MIId_Q0Dn7rSs2MscIg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/460)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/460#-MIIe0H62V_5jwaJkVzz:-MIIe0H73AMBRSfAmlwg:bmodxn3) (no related file):*
```
2020-09-28T06:00:40.6528009Z -- Performing Test C_HAS_ASAN_UBSAN
2020-09-28T06:00:40.7134538Z address sanitizer not supported
2020-09-28T06:00:40.7135655Z -- Performing Test C_HAS_ASAN_UBSAN - Failed
2020-09-28T06:00:40.7139849Z undefined sanitizer not supported
```

Works as intended?

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/460)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/460#-MIIe0H62V_5jwaJkVzz:-MIIrCwxDoH5fbhHlXP2:b-886gsx) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```
2020-09-28T06:00:40.6528009Z -- Performing Test C_HAS_ASAN_UBSAN
2020-09-28T06:00:40.7134538Z address sanitizer not supported
2020-09-28T06:00:40.7135655Z -- Performing Test C_HAS_ASAN_UBSAN - Failed
2020-09-28T06:00:40.7139849Z undefined sanitizer not supported
```

Works as intended?
</blockquote></details>

Fixed

---

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/460#-:-MIJ74r-2ZDIx3JKtK_a:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
