### PR TITLE
[WIP] tools: Runner intro

### PR DESCRIPTION
**Pull request by grom72**
New Runner abstract class to cover all common runners operations
- [x] #1452 
- [x] #1461
- [x] #1453 
- [x] #1455 

PR should be split into 2-3 separate
1) Runner class with common support for self.__benchmark, self.__config = config, self.__idfile + only basic UT
2) move common validation from ib_read and fio runners to Runner class + UT adjustment
3) add support for _oneseries, _tool, _tool_mode, _mode to Runner class (and remove them from fio/ib_read runners)

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1454)

### CODE REVIEW

**Review by Patryk717 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1454#-:-Ms-biOw1a4bIehepHk_:bdycpsm)* status: 0 of 8 files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1454)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 8 files at r1, 1 of 1 files at r2, 1 of 1 files at r3, 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1454)* status: 3 of 8 files reviewed, all discussions resolved (waiting on @grom72 and @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1454)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @grom72 and @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1454)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @grom72 and @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1454)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @grom72 and @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1454)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @grom72 and @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 8 files at r1, 1 of 3 files at r4, 1 of 2 files at r5, 3 of 7 files at r6, 2 of 4 files at r8, 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1454)* status: 6 of 10 files reviewed, all discussions resolved (waiting on @grom72 and @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1454)* status: 4 of 11 files reviewed, all discussions resolved (waiting on @grom72 and @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 4 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1454)* status: 5 of 11 files reviewed, all discussions resolved (waiting on @grom72 and @ldorau)

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1454)* status: 5 of 11 files reviewed, all discussions resolved (waiting on @grom72, @haichangsi, and @ldorau)

**Comment by ldorau** [comment]
Postponed

**Pull request closed without merging**
