### PR TITLE
tools: add introduction to the report

### PR DESCRIPTION
**Pull request by janekmi**
Requires:
- [x] #807

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/808)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/808)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/808)* status: all files reviewed, 11 unresolved discussions (waiting on @janekmi)

___
*[tools/create_report.py, line 39 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MSSztZk--5Nsxq_bDZ3:-MSSztZk--5Nsxq_bDZ4:bukpxdw) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/create_report.py#L39)):*
> ```
> (f"The 
> ```

Is `f` needed here? What does it mean?
___
*[tools/templates/introduction.md.template, line 3 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MST-_PO-VQpDE7G_Zk7:-MST-_PO-VQpDE7G_Zk8:b-qwedwo) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L3)):*
> ```
> out of band 
> ```

`out-of-band` ?
___
*[tools/templates/introduction.md.template, line 3 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MST-enuAVGmyosOZonL:-MST-enuAVGmyosOZonM:b44a0wi) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L3)):*
> ```
> communiation
> ```

`communiCation`
___
*[tools/templates/introduction.md.template, line 3 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MST-uvE75RVn7W8n2Uk:-MST-uvF7SmU9_m7JLcv:b3w9hx4) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L3)):*
> ```
> connection.
> ```

`connectionS.`
___
*[tools/templates/introduction.md.template, line 3 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MST01ScCSv6VxDZLdvc:-MST01ScCSv6VxDZLdvd:b4zdpor) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L3)):*
> ```
> As the second one the client engine is started
> ```

`The client engine is started as the second one ...`
___
*[tools/templates/introduction.md.template, line 3 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MST0DJL3qT8UozBajRp:-MST0DJL3qT8UozBajRq:b-m2sy5q) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L3)):*
> ```
> and establish 
> ```

`and it establishes ... `
___
*[tools/templates/introduction.md.template, line 3 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MST0KETEiyIisZzvdEC:-MST0KETEiyIisZzvdED:b-i0vfg7) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L3)):*
> ```
> a preconfigured number
> ```

`the preconfigured number ...`
___
*[tools/templates/introduction.md.template, line 3 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MST0SZfCcULOSVjpevB:-MST0SZfCcULOSVjpevC:b2fxez2) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L3)):*
> ```
> After this setup 
> ```

`After this setup steps ...`
___
*[tools/templates/introduction.md.template, line 7 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MST0jfe3d-KjfVOg5G3:-MST0jfe3d-KjfVOg5G4:b-no67ax) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L7)):*
> ```
>  UPI 
> ```

What does it stand for ?
___
*[tools/templates/introduction.md.template, line 9 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MST0yRx-0f8TgKpRfAq:-MST0yRx-0f8TgKpRfAr:b-37s321) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L9)):*
> ```
> The set up consists
> ```

`The setup consists`
___
*[tools/templates/introduction.md.template, line 9 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MST13Pg6EF5-PZ9lTha:-MST13Ph2jn7rRHQmPsJ:bf4exee) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L9)):*
> ```
> as initiator
> ```

`as the initiator`

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/808)* status: all files reviewed, 11 unresolved discussions (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/808)* status: all files reviewed, 11 unresolved discussions (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/808)* status: all files reviewed, 16 unresolved discussions (waiting on @janekmi)

___
*[tools/templates/introduction.md.template, line 1 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MSWEB-B89E_78_x5oVK:-MSWEB-B89E_78_x5oVL:bimnx1e) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L1)):*
> ```
> This is
> ```
It is
___
*[tools/templates/introduction.md.template, line 1 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MSWEGYM7eLuJnk55Utj:-MSWEGYM7eLuJnk55Utk:b-ycsic9) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L1)):*
> ```
> Remote Persistent Memory Access (RPMA)
> ```
The Remote Persistent Memory Access (RPMA) library (librpma)
___
*[tools/templates/introduction.md.template, line 3 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MSWEdrW8Wk_-g7Z4g0I:-MSWEdrW8Wk_-g7Z4g0J:byrs759) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L3)):*
> ```
> Before running the client engine on the initiator side, the server engine has to be started.
> ```
The server engine has to be started before running the client engine on the initiator side.
___
*[tools/templates/introduction.md.template, line 3 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MSWFr1cDK6ptDhN71Fv:-MSWFr1d7l4YBMoby2fO:b-uzqiq6) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L3)):*
> ```
> incoming client's connection
> ```
the incoming client's connection
___
*[tools/templates/introduction.md.template, line 3 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MSWGRBYBoBhd487cYyj:-MSWGRBYBoBhd487cYyk:bscz7wd) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L3)):*
> ```
>As the second one the client
> ```
As the second one **,** the client

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/808)* status: all files reviewed, 18 unresolved discussions (waiting on @janekmi)

___
*[tools/templates/introduction.md.template, line 9 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MSWLBuu2O3zTbZkBGGk:-MSWLBuu2O3zTbZkBGGl:b2y1l5s) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L9)):*
> ```
> NUMA node and one 100Gbps Mellanox ConnectX-5 NIC connected. The initiator system has one Mellanox ConnectX-5 100Gbps NIC connected directly to the target without any switch. From two ports available for Mellanox NICs only one is in use during the measurements.
> ```
NUMA node. Both the initiator and the target are equipped with 100Gbps Mellanox ConnectX-5 NICs. The initiator is connected to the target system directly using QSFP28 cables without any switches. From two ports available on NICs only one is in use during the measurements.
___
*[tools/templates/introduction.md.template, line 9 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MSWLyj06YIfq8ajSAwN:-MSWLyj06YIfq8ajSAwO:b-fu6kx1) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L9)):*
> ```
> The target is connected to the initiator system point-to-point using QSFP28 cables without any switches
> ```
to be removed, see the comment above

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/808)* status: all files reviewed, 19 unresolved discussions (waiting on @janekmi)

___
*[tools/templates/introduction.md.template, line 9 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MSWMOTW1qmHYCcZ459R:-MSWMOTW1qmHYCcZ459S:bqd4c6k) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L9)):*
> ```
> has six Intel&reg; Optane&trade; Persistent Memory devices
> ```
interleaving to be mentioned here ...

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/808)* status: all files reviewed, 18 unresolved discussions (waiting on @janekmi)

___
*[tools/create_report.py, line 39 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MSSztZk--5Nsxq_bDZ3:-MSWtX_w-BoVa5VQlooq:b7gpxkz) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/create_report.py#L39)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> (f"The 
> ```

Is `f` needed here? What does it mean?
</blockquote></details>

https://realpython.com/python-f-strings/#f-strings-a-new-and-improved-way-to-format-strings-in-python

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/808)* status: all files reviewed, 18 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tools/templates/introduction.md.template, line 1 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MSWEB-B89E_78_x5oVK:-MSWu7il6BVOwHSVmMnJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L1)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> This is
> ```
It is
</blockquote></details>

Done.
___
*[tools/templates/introduction.md.template, line 1 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MSWEGYM7eLuJnk55Utj:-MSWu9c339K82cVbZyl4:b7gvp3o) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L1)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Remote Persistent Memory Access (RPMA)
> ```
The Remote Persistent Memory Access (RPMA) library (librpma)
</blockquote></details>

It reminds me of a Matryoshka Doll. xD

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/808)* status: 3 of 4 files reviewed, 16 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[tools/templates/introduction.md.template, line 1 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MSWEGYM7eLuJnk55Utj:-MSWuTgWC0zA38pFl-ub:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L1)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It reminds me of a Matryoshka Doll. xD
</blockquote></details>

Done.
___
*[tools/templates/introduction.md.template, line 3 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MST-enuAVGmyosOZonL:-MSWuZM6359v9REEeO72:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L3)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> communiation
> ```

`communiCation`
</blockquote></details>

Done.
___
*[tools/templates/introduction.md.template, line 3 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MST-uvE75RVn7W8n2Uk:-MSWubTRDnyjVMPVzMMz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L3)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> connection.
> ```

`connectionS.`
</blockquote></details>

Done.
___
*[tools/templates/introduction.md.template, line 3 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MST01ScCSv6VxDZLdvc:-MSWuhyAC9AE-kg2V5cm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L3)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> As the second one the client engine is started
> ```

`The client engine is started as the second one ...`
</blockquote></details>

Done.
___
*[tools/templates/introduction.md.template, line 3 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MST0DJL3qT8UozBajRp:-MSWukgr8nf53ZybKrhi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L3)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> and establish 
> ```

`and it establishes ... `
</blockquote></details>

Done.
___
*[tools/templates/introduction.md.template, line 3 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MST0KETEiyIisZzvdEC:-MSWunteDwRcEGQScKff:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L3)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> a preconfigured number
> ```

`the preconfigured number ...`
</blockquote></details>

Done.
___
*[tools/templates/introduction.md.template, line 3 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MST0SZfCcULOSVjpevB:-MSWusl-4JkIiJ9U6JV-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L3)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> After this setup 
> ```

`After this setup steps ...`
</blockquote></details>

Done.
___
*[tools/templates/introduction.md.template, line 3 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MSWEdrW8Wk_-g7Z4g0I:-MSWv2tLAzkQb3Z-stDU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L3)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Before running the client engine on the initiator side, the server engine has to be started.
> ```
The server engine has to be started before running the client engine on the initiator side.
</blockquote></details>

Done.
___
*[tools/templates/introduction.md.template, line 3 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MSWFr1cDK6ptDhN71Fv:-MSWvDl8ERlg9-nAz1Lz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L3)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> incoming client's connection
> ```
the incoming client's connection
</blockquote></details>

Done.
___
*[tools/templates/introduction.md.template, line 3 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MSWGRBYBoBhd487cYyj:-MSWvFVmCxffSUFFeVbj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L3)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
>As the second one the client
> ```
As the second one **,** the client
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/808)* status: 3 of 4 files reviewed, 16 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/templates/introduction.md.template, line 9 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MST0yRx-0f8TgKpRfAq:-MSWvvLc8SopK89ITeIX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L9)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> The set up consists
> ```

`The setup consists`
</blockquote></details>

Done.
___
*[tools/templates/introduction.md.template, line 9 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MST13Pg6EF5-PZ9lTha:-MSWvzyOAIVeIlQatQd0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L9)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> as initiator
> ```

`as the initiator`
</blockquote></details>

Done.
___
*[tools/templates/introduction.md.template, line 9 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MSWLBuu2O3zTbZkBGGk:-MSWwTOa0w6wXB0C_BPE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L9)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> NUMA node and one 100Gbps Mellanox ConnectX-5 NIC connected. The initiator system has one Mellanox ConnectX-5 100Gbps NIC connected directly to the target without any switch. From two ports available for Mellanox NICs only one is in use during the measurements.
> ```
NUMA node. Both the initiator and the target are equipped with 100Gbps Mellanox ConnectX-5 NICs. The initiator is connected to the target system directly using QSFP28 cables without any switches. From two ports available on NICs only one is in use during the measurements.
</blockquote></details>

Done.
___
*[tools/templates/introduction.md.template, line 9 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MSWLyj06YIfq8ajSAwN:-MSWwVB2DV0mRl4_dguC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L9)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> The target is connected to the initiator system point-to-point using QSFP28 cables without any switches
> ```
to be removed, see the comment above
</blockquote></details>

Done.
___
*[tools/templates/introduction.md.template, line 9 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MSWMOTW1qmHYCcZ459R:-MSWwYQF2rqJF0KAxdqf:b2lyy61) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L9)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> has six Intel&reg; Optane&trade; Persistent Memory devices
> ```
interleaving to be mentioned here ...
</blockquote></details>

I think not. It is already mentioned in the detailed configuration.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/808)* status: all files reviewed, 8 unresolved discussions (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/808)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/templates/introduction.md.template, line 9 at r2](https://reviewable.io/reviews/pmem/rpma/808#-MSWLyj06YIfq8ajSAwN:-MSWyejL9EeQp10odYQ9:b-b0k185) ([raw file](https://github.com/pmem/rpma/blob/9cbc4685315ee63b307b753ffca995b24e674deb/tools/templates/introduction.md.template#L9)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It still exists in 2 places.

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/808)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/808#-:-MSX2UzcBtVv_Nnxzto1:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/808#-:-MSXIPEcB3gnz3EUfU1s:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/808)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/808#-:-MSXJ42K9IC2hmYLApHI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
