### PR TITLE
tools: perf: introduce a way to regenerate file.json files

### PR DESCRIPTION
**Pull request by janekmi**
Requires:

- [x] #1249
- [x] #1246

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1250)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1250)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1250)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1250#-Miujy0P9eUP0aNL97II:-Miujy0P9eUP0aNL97IJ:bc16daj) (no related file):*
```
$ ./report_figures.py --bench ./report_python/bench.json --regenerate_jsons
Traceback (most recent call last):
  File "/mnt/files/repos/rpma/tools/perf/./report_figures.py", line 40, in <module>
    main()
  File "/mnt/files/repos/rpma/tools/perf/./report_figures.py", line 31, in main
    bench = Bench.carry_on(args.bench)
  File "/mnt/files/repos/rpma/tools/perf/lib/bench.py", line 45, in carry_on
    figures = [Figure(f, result_dir) for f in bench['figures']]
  File "/mnt/files/repos/rpma/tools/perf/lib/bench.py", line 45, in <listcomp>
    figures = [Figure(f, result_dir) for f in bench['figures']]
  File "/mnt/files/repos/rpma/tools/perf/lib/figure.py", line 46, in __init__
    self.common_params = data['json'][self.key]['common_params']
KeyError: 'common_params'
```

---

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1250)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1250)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1250#-Miujy0P9eUP0aNL97II:-Miv002E-afRRy9U4g-f:b32w0x) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
$ ./report_figures.py --bench ./report_python/bench.json --regenerate_jsons
Traceback (most recent call last):
  File "/mnt/files/repos/rpma/tools/perf/./report_figures.py", line 40, in <module>
    main()
  File "/mnt/files/repos/rpma/tools/perf/./report_figures.py", line 31, in main
    bench = Bench.carry_on(args.bench)
  File "/mnt/files/repos/rpma/tools/perf/lib/bench.py", line 45, in carry_on
    figures = [Figure(f, result_dir) for f in bench['figures']]
  File "/mnt/files/repos/rpma/tools/perf/lib/bench.py", line 45, in <listcomp>
    figures = [Figure(f, result_dir) for f in bench['figures']]
  File "/mnt/files/repos/rpma/tools/perf/lib/figure.py", line 46, in __init__
    self.common_params = data['json'][self.key]['common_params']
KeyError: 'common_params'
```

</blockquote></details>

OK

---

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1250)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1250#-:-Miv3lgqDdqonK4Ro8-u:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1250#-:-MivNV7M7-_qVhdofQ4O:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1250)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
