### PR TITLE
doc: performance tuning - cleanup

### PR DESCRIPTION
**Pull request by janekmi**
Preview: https://janekmi.github.io/rpma/documentation/perf-tuning.html

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/844)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/844)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[documentation/perf-tuning.md, line 5 at r1](https://reviewable.io/reviews/pmem/rpma/844#-MSdTmZC7O023YgtNDnw:-MSdTmZC7O023YgtNDnx:b-absntd) ([raw file](https://github.com/pmem/rpma/blob/3fa1487adf39f8e8cc93e24d4eef0fcaf4687521/documentation/perf-tuning.md#L5)):*
> ```Markdown
> layout: pmdk
> ---
> ```

##Remote Persistent Memory Access

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/844)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[documentation/perf-tuning.md, line 5 at r1](https://reviewable.io/reviews/pmem/rpma/844#-MSdTmZC7O023YgtNDnw:-MSe1N7X19jJ3uQ0sC-5:b-75ompl) ([raw file](https://github.com/pmem/rpma/blob/3fa1487adf39f8e8cc93e24d4eef0fcaf4687521/documentation/perf-tuning.md#L5)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

##Remote Persistent Memory Access
</blockquote></details>

Have you seen the preview: https://janekmi.github.io/rpma/documentation/perf-tuning.html ?
We have solved the lack of reference to RPMA differently.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/844)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[documentation/perf-tuning.md, line 125 at r1](https://reviewable.io/reviews/pmem/rpma/844#-MSfo8N58w8QWzYOw_JR:-MSfo8N58w8QWzYOw_JS:b-35ckuq) ([raw file](https://github.com/pmem/rpma/blob/3fa1487adf39f8e8cc93e24d4eef0fcaf4687521/documentation/perf-tuning.md#L125)):*
> ```
> you may calculate what is RNIC bandwidth limitation
> ```

`you may calculate the RNIC bandwidth limitation`
___
*[documentation/perf-tuning.md, line 125 at r1](https://reviewable.io/reviews/pmem/rpma/844#-MSfoE0xCIqwTPqVYtIJ:-MSfoE0xCIqwTPqVYtIK:bc5rz52) ([raw file](https://github.com/pmem/rpma/blob/3fa1487adf39f8e8cc93e24d4eef0fcaf4687521/documentation/perf-tuning.md#L125)):*
> ```
> pleas
> ```

please

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/844)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[documentation/perf-tuning.md, line 125 at r1](https://reviewable.io/reviews/pmem/rpma/844#-MSfo8N58w8QWzYOw_JR:-MSgFfTl8RU3W6e0_TSB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3fa1487adf39f8e8cc93e24d4eef0fcaf4687521/documentation/perf-tuning.md#L125)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> you may calculate what is RNIC bandwidth limitation
> ```

`you may calculate the RNIC bandwidth limitation`
</blockquote></details>

Done.
___
*[documentation/perf-tuning.md, line 125 at r1](https://reviewable.io/reviews/pmem/rpma/844#-MSfoE0xCIqwTPqVYtIJ:-MSgG3WOC419mT7wupVL:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3fa1487adf39f8e8cc93e24d4eef0fcaf4687521/documentation/perf-tuning.md#L125)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> pleas
> ```

please
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/844#-:-MSgKV1s8anMDaGdi49C:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/844)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/844#-:-MSgM6WNDSoCWyQA_N-w:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/844#-:-MSgOKS71GQquTbKiDnV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
