### PR TITLE
tools: add dependencies to reporting tools

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/872)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/872)* status: all files reviewed, 8 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/BENCHMARKING.md, line 9 at r1](https://reviewable.io/reviews/pmem/rpma/872#-MTBP8xTAJeNlr1zkxEd:-MTBP8xTAJeNlr1zkxEe:b7c0pbx) ([raw file](https://github.com/pmem/rpma/blob/0d858d40a66c5e360ced00dcaf429b7da7c8b5cd/tools/perf/BENCHMARKING.md#L9)):*
> ```Markdown
> ## Requirements
> 
> To use these tools, you must have several components installed in your system:
> ```

To use the benchmarking tools (e.g. ib_read.sh, rpma_fio_bench.sh)...
___
*[tools/perf/BENCHMARKING.md, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/872#-MTBN07NBzWi-ptNtg7U:-MTBHzxP7mpEhem-ZAaQ:b7gsohm) ([raw file](https://github.com/pmem/rpma/blob/0d858d40a66c5e360ced00dcaf429b7da7c8b5cd/tools/perf/BENCHMARKING.md#L17)):*
> ```Markdown
>  - fio (supporting the librpma fio engine)
>  - numactl
>  - sshpass
> ```

We are missing here:
- pciutils
for ddio.sh which may be invoked from rpmem_fio_bench.sh.
___
*[tools/perf/BENCHMARKING.md, line 42 at r1](https://reviewable.io/reviews/pmem/rpma/872#-MTBP_j93dqysr7taNmM:-MTBP_j93dqysr7taNmN:b-irya9e) ([raw file](https://github.com/pmem/rpma/blob/0d858d40a66c5e360ced00dcaf429b7da7c8b5cd/tools/perf/BENCHMARKING.md#L42)):*
> ```Markdown
> ```
> 
> *Note*: All of the scripts presented in the following sections must be run on the client side.
> ```

This note should go below the newly added part.
___
*[tools/perf/BENCHMARKING.md, line 44 at r1](https://reviewable.io/reviews/pmem/rpma/872#-MTBPIvT9yo6G4Fhun4Z:-MTBPIvT9yo6G4Fhun4_:bdja9jx) ([raw file](https://github.com/pmem/rpma/blob/0d858d40a66c5e360ced00dcaf429b7da7c8b5cd/tools/perf/BENCHMARKING.md#L44)):*
> ```Markdown
> *Note*: All of the scripts presented in the following sections must be run on the client side.
> 
> To use the report generation tools, you must additionally install:
> ```

... and reporting tools (e.g. csv_compare.py, report_bench.sh, create_report_figures.sh, create_report.py, fio-histogram.py), ...
___
*[tools/perf/BENCHMARKING.md, line 47 at r1](https://reviewable.io/reviews/pmem/rpma/872#-MTBNrzO5Pg5wRc3NXxq:-MTBNrzO5Pg5wRc3NXxr:b43zux5) ([raw file](https://github.com/pmem/rpma/blob/0d858d40a66c5e360ced00dcaf429b7da7c8b5cd/tools/perf/BENCHMARKING.md#L47)):*
> ```Markdown
>  - jinja2
>  - markdown2
>  - shutil
> ```

It is a part of The Standard Python Library: https://docs.python.org/3/library/shutil.html
___
*[tools/perf/BENCHMARKING.md, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/872#-MTBOVty2awx3mO-8Kcu:-MTBOVty2awx3mO-8Kcv:b7ldd2u) ([raw file](https://github.com/pmem/rpma/blob/0d858d40a66c5e360ced00dcaf429b7da7c8b5cd/tools/perf/BENCHMARKING.md#L48)):*
> ```Markdown
>  - markdown2
>  - shutil
>  - pil
> ```

pil -> PIL
___
*[tools/perf/BENCHMARKING.md, line 50 at r1](https://reviewable.io/reviews/pmem/rpma/872#-MTBOPCi57k_jcmEqtd8:-MTBOPCi57k_jcmEqtd9:b4knwz8) ([raw file](https://github.com/pmem/rpma/blob/0d858d40a66c5e360ced00dcaf429b7da7c8b5cd/tools/perf/BENCHMARKING.md#L50)):*
> ```Markdown
>  - pil
>  - textwrap
>  - csv
> ```

The same for textwrap and csv:
- https://docs.python.org/3/library/textwrap.html
- https://docs.python.org/3/library/csv.html
___
*[tools/perf/BENCHMARKING.md, line 51 at r1](https://reviewable.io/reviews/pmem/rpma/872#-MTBOjsaDcKxrAup2hyA:-MTBOjsaDcKxrAup2hyB:b1gpsmp) ([raw file](https://github.com/pmem/rpma/blob/0d858d40a66c5e360ced00dcaf429b7da7c8b5cd/tools/perf/BENCHMARKING.md#L51)):*
> ```Markdown
>  - textwrap
>  - csv
> ```

Please add also an installation instruction the same it is done above.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/872)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/BENCHMARKING.md, line 9 at r1](https://reviewable.io/reviews/pmem/rpma/872#-MTBP8xTAJeNlr1zkxEd:-MTBphaVD6T11_llxyWL:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0d858d40a66c5e360ced00dcaf429b7da7c8b5cd/tools/perf/BENCHMARKING.md#L9)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

To use the benchmarking tools (e.g. ib_read.sh, rpma_fio_bench.sh)...
</blockquote></details>

Done.
___
*[tools/perf/BENCHMARKING.md, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/872#-MTBN07NBzWi-ptNtg7U:-MTBpw86-QpfSR3wZn9n:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0d858d40a66c5e360ced00dcaf429b7da7c8b5cd/tools/perf/BENCHMARKING.md#L17)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

We are missing here:
- pciutils
for ddio.sh which may be invoked from rpmem_fio_bench.sh.
</blockquote></details>

Done.
___
*[tools/perf/BENCHMARKING.md, line 42 at r1](https://reviewable.io/reviews/pmem/rpma/872#-MTBP_j93dqysr7taNmM:-MTBq4Xt7UbN7STvGQ6B:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0d858d40a66c5e360ced00dcaf429b7da7c8b5cd/tools/perf/BENCHMARKING.md#L42)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This note should go below the newly added part.
</blockquote></details>

Done.
___
*[tools/perf/BENCHMARKING.md, line 44 at r1](https://reviewable.io/reviews/pmem/rpma/872#-MTBPIvT9yo6G4Fhun4Z:-MTBqHLiBYgSXOSeniTx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0d858d40a66c5e360ced00dcaf429b7da7c8b5cd/tools/perf/BENCHMARKING.md#L44)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

... and reporting tools (e.g. csv_compare.py, report_bench.sh, create_report_figures.sh, create_report.py, fio-histogram.py), ...
</blockquote></details>

Done.
___
*[tools/perf/BENCHMARKING.md, line 47 at r1](https://reviewable.io/reviews/pmem/rpma/872#-MTBNrzO5Pg5wRc3NXxq:-MTBqJ8d90BCjuW4SciO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0d858d40a66c5e360ced00dcaf429b7da7c8b5cd/tools/perf/BENCHMARKING.md#L47)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is a part of The Standard Python Library: https://docs.python.org/3/library/shutil.html
</blockquote></details>

Done.
___
*[tools/perf/BENCHMARKING.md, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/872#-MTBOVty2awx3mO-8Kcu:-MTBqKf3Dsm9a6FuExtX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0d858d40a66c5e360ced00dcaf429b7da7c8b5cd/tools/perf/BENCHMARKING.md#L48)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

pil -> PIL
</blockquote></details>

Done.
___
*[tools/perf/BENCHMARKING.md, line 50 at r1](https://reviewable.io/reviews/pmem/rpma/872#-MTBOPCi57k_jcmEqtd8:-MTBqMbdEOyE1OKA-rQ7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0d858d40a66c5e360ced00dcaf429b7da7c8b5cd/tools/perf/BENCHMARKING.md#L50)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The same for textwrap and csv:
- https://docs.python.org/3/library/textwrap.html
- https://docs.python.org/3/library/csv.html
</blockquote></details>

Done.
___
*[tools/perf/BENCHMARKING.md, line 51 at r1](https://reviewable.io/reviews/pmem/rpma/872#-MTBOjsaDcKxrAup2hyA:-MTBqQjR5SraXTHr5DjD:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0d858d40a66c5e360ced00dcaf429b7da7c8b5cd/tools/perf/BENCHMARKING.md#L51)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please add also an installation instruction the same it is done above.
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/872)* status: all files reviewed, 4 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/BENCHMARKING.md, line 9 at r2](https://reviewable.io/reviews/pmem/rpma/872#-MTFVv7z0DD2atL7uzg3:-MTFVv7z0DD2atL7uzg4:b-a5uixc) ([raw file](https://github.com/pmem/rpma/blob/5ff3c9798e427e841aeb637ea9446dec53090a19/tools/perf/BENCHMARKING.md#L9)):*
> ```Markdown
> ## Requirements
> 
> To use the benchmarking tools (e.g. ib_read.sh, rpma_fio_bench.sh), you must have several components installed in your system:
> ```

Please escape underscores. `_` -> `\_`
___
*[tools/perf/BENCHMARKING.md, line 14 at r2](https://reviewable.io/reviews/pmem/rpma/872#-MTFW1WQ5VoJmVISFbVa:-MTFW1WQ5VoJmVISFbVb:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/5ff3c9798e427e841aeb637ea9446dec53090a19/tools/perf/BENCHMARKING.md#L14)):*
> ```Markdown
>  - pandas
>  - matplotlib
>  - perftest (providing ib tools like `ib_read_lat`, `ib_read_bw` etc)
> ```

.
___
*[tools/perf/BENCHMARKING.md, line 18 at r2](https://reviewable.io/reviews/pmem/rpma/872#-MTFW0Mm2ANFNpz2_uzU:-MTFW0Mm2ANFNpz2_uzV:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/5ff3c9798e427e841aeb637ea9446dec53090a19/tools/perf/BENCHMARKING.md#L18)):*
> ```Markdown
>  - numactl
>  - sshpass
>  - pciutils (for ddio.sh which may be invoked from rpmem_fio_bench.sh)
> ```

.
___
*[tools/perf/BENCHMARKING.md, line 43 at r2](https://reviewable.io/reviews/pmem/rpma/872#-MTFW39H1heo-555DbgH:-MTFW39H1heo-555DbgI:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/5ff3c9798e427e841aeb637ea9446dec53090a19/tools/perf/BENCHMARKING.md#L43)):*
> ```Markdown
> ```
> 
> To use the reporting tools (e.g. csv_compare.py, report_bench.sh, create_report_figures.sh, create_report.py, fio-histogram.py), you must additionally install:
> ```

.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/872)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/BENCHMARKING.md, line 9 at r2](https://reviewable.io/reviews/pmem/rpma/872#-MTFVv7z0DD2atL7uzg3:-MTFbAkS1qFc58c7M_xm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5ff3c9798e427e841aeb637ea9446dec53090a19/tools/perf/BENCHMARKING.md#L9)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please escape underscores. `_` -> `\_`
</blockquote></details>

Done.
___
*[tools/perf/BENCHMARKING.md, line 14 at r2](https://reviewable.io/reviews/pmem/rpma/872#-MTFW1WQ5VoJmVISFbVa:-MTFbFYWB8TydX3U9AuD:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5ff3c9798e427e841aeb637ea9446dec53090a19/tools/perf/BENCHMARKING.md#L14)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/BENCHMARKING.md, line 18 at r2](https://reviewable.io/reviews/pmem/rpma/872#-MTFW0Mm2ANFNpz2_uzU:-MTFbISK9o90801AOhcu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5ff3c9798e427e841aeb637ea9446dec53090a19/tools/perf/BENCHMARKING.md#L18)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/BENCHMARKING.md, line 43 at r2](https://reviewable.io/reviews/pmem/rpma/872#-MTFW39H1heo-555DbgH:-MTFbLNt-NaYhCsMszqs:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5ff3c9798e427e841aeb637ea9446dec53090a19/tools/perf/BENCHMARKING.md#L43)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/872#-:-MTFmawU68j6iO5rJAna:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/872)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/BENCHMARKING.md, line 18 at r3](https://reviewable.io/reviews/pmem/rpma/872#-MTFuA8cDdxueG7gz_43:-MTFuA8cDdxueG7gz_44:b-n4qost) ([raw file](https://github.com/pmem/rpma/blob/7f85f7ccb2df71e07613cc1aaa968baa1a25ef07/tools/perf/BENCHMARKING.md#L18)):*
> ```Markdown
>  - numactl
>  - sshpass
>  - pciutils (for ddio.sh which may be invoked from rpmem\_fio\_bench.sh)
> ```

rpmem? :joy:

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/872)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[tools/perf/BENCHMARKING.md, line 18 at r3](https://reviewable.io/reviews/pmem/rpma/872#-MTFuA8cDdxueG7gz_43:-MTGRslLBseIu4C8v5sh:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7f85f7ccb2df71e07613cc1aaa968baa1a25ef07/tools/perf/BENCHMARKING.md#L18)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

rpmem? :joy: 
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/872)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/872#-:-MTGp97h4LQ_Su7gz0Uv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
