### PR TITLE
tools: introduce LOG_CMDS

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/821)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/821)* status: 1 of 2 files reviewed, 6 unresolved discussions (waiting on @janekmi)

___
*[tools/ib_read.sh, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/821#-MSWMuvl2-xevExhTJsx:-MSWMuvl2-xevExhTJsy:blrj0ep) ([raw file](https://github.com/pmem/rpma/blob/0c02737564ec197598e653729ccca286bb898ee9/tools/ib_read.sh#L39)):*
> ```
> it does not the actual execution
> ```
what do you mean?
___
*[tools/ib_read.sh, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/821#-MSWO0tR7u-LgTeagttJ:-MSWO0tR7u-LgTeagttK:b-xbiau3) ([raw file](https://github.com/pmem/rpma/blob/0c02737564ec197598e653729ccca286bb898ee9/tools/ib_read.sh#L39)):*
> ```
> echo "export LOG_CMDS=1 (it does not the actual execution)"
> ```
would it be better to have one more command line parameter?
___
*[tools/ib_read.sh, line 129 at r1](https://reviewable.io/reviews/pmem/rpma/821#-MSWNQnX9Dkzemj7oaKb:-MSWNQnX9Dkzemj7oaKc:b-17gkhf) ([raw file](https://github.com/pmem/rpma/blob/0c02737564ec197598e653729ccca286bb898ee9/tools/ib_read.sh#L129)):*
> ```
> THREADS=(8 12)
> ```
```THREADS=(1 2 4 8 12)```

or any comment is needed
___
*[tools/rpma_fio_bench.sh, line 46 at r1](https://reviewable.io/reviews/pmem/rpma/821#-MSWOXDO9_hsiKR5tFFt:-MSWOXDO9_hsiKR5tFFu:bl4e2zu) ([raw file](https://github.com/pmem/rpma/blob/0c02737564ec197598e653729ccca286bb898ee9/tools/rpma_fio_bench.sh#L46)):*
> ```Shell
> 	echo "export TRACER='gdbserver localhost:2345'"
> 	echo "export REMOTE_TRACER='gdbserver localhost:2345'"
> 	echo "export LOG_CMDS=1 (it does not the actual execution)"
> ```

what about having one more call parameter instead of export LOG_CMDS?:
Usage: $0 **[--log]** <server_ip> all|apm|gpspm [all|read|randread|write|randwrite|rw|randrw] [all|bw-bs|bw-dp-exp|bw-dp-lin|bw-th|lat]
___
*[tools/rpma_fio_bench.sh, line 46 at r1](https://reviewable.io/reviews/pmem/rpma/821#-MSWPgWzBrHm9MoFNpmM:-MSWPgWzBrHm9MoFNpmN:b90v0u7) ([raw file](https://github.com/pmem/rpma/blob/0c02737564ec197598e653729ccca286bb898ee9/tools/rpma_fio_bench.sh#L46)):*
> ```
> it does not the actual execution
> ```
what does it mean?
___
*[tools/rpma_fio_bench.sh, line 81 at r1](https://reviewable.io/reviews/pmem/rpma/821#-MSWP2BD8OxJjM4OwdXS:-MSWP2BD8OxJjM4OwdXT:bg1bvna) ([raw file](https://github.com/pmem/rpma/blob/0c02737564ec197598e653729ccca286bb898ee9/tools/rpma_fio_bench.sh#L81)):*
> ```Shell
> 	show_environment
> fi
> ```


if [ "$1" == "--log" ]; then
	LOG_CMDS=1
        shift 1
fi

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/821)* status: all files reviewed, 7 unresolved discussions (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/821#-MSWRJ3KAn0tvr5AOiqk:-MSWRJ3LB5eu2wceZw70:bknwc8f) (no related file):*
Is this feature needed?

---

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/821)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72 and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/821#-MSWRJ3KAn0tvr5AOiqk:-MSWpaaQ2udoBAe7v7wl:bocdwh5) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Is this feature needed?
</blockquote></details>

Like a... it is very needed. Otherwise, there is no easy way to easily browse the parameters values run-by-run.

---

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/821)* status: 1 of 2 files reviewed, 7 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tools/ib_read.sh, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/821#-MSWO0tR7u-LgTeagttJ:-MSWq-RD9H_ikod2PqAJ:bsazz9i) ([raw file](https://github.com/pmem/rpma/blob/0c02737564ec197598e653729ccca286bb898ee9/tools/ib_read.sh#L39)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> echo "export LOG_CMDS=1 (it does not the actual execution)"
> ```
would it be better to have one more command line parameter?
</blockquote></details>

No. It is so debug probably one man in the world will use it at the time.
___
*[tools/ib_read.sh, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/821#-MSWMuvl2-xevExhTJsx:-MSWq88L0FMR9Og0Osm0:b-7omoxt) ([raw file](https://github.com/pmem/rpma/blob/0c02737564ec197598e653729ccca286bb898ee9/tools/ib_read.sh#L39)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> it does not the actual execution
> ```
what do you mean?
</blockquote></details>

I mean turning on this option suppresses the main function of this script, namely when it is turned on no benchmark will be executed.
___
*[tools/ib_read.sh, line 129 at r1](https://reviewable.io/reviews/pmem/rpma/821#-MSWNQnX9Dkzemj7oaKb:-MSWqUyb0X662cnk4WjE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0c02737564ec197598e653729ccca286bb898ee9/tools/ib_read.sh#L129)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> THREADS=(8 12)
> ```
```THREADS=(1 2 4 8 12)```

or any comment is needed
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/821)* status: 1 of 2 files reviewed, 7 unresolved discussions (waiting on @grom72)

___
*[tools/rpma_fio_bench.sh, line 46 at r1](https://reviewable.io/reviews/pmem/rpma/821#-MSWOXDO9_hsiKR5tFFt:-MSWqyHL6SBA2tGM4Bhb:b-aplt44) ([raw file](https://github.com/pmem/rpma/blob/0c02737564ec197598e653729ccca286bb898ee9/tools/rpma_fio_bench.sh#L46)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

what about having one more call parameter instead of export LOG_CMDS?:
Usage: $0 **[--log]** <server_ip> all|apm|gpspm [all|read|randread|write|randwrite|rw|randrw] [all|bw-bs|bw-dp-exp|bw-dp-lin|bw-th|lat]
</blockquote></details>

It is long enough without it. And as I said, I assume nobody cares about this parameter. It is for us.
___
*[tools/rpma_fio_bench.sh, line 46 at r1](https://reviewable.io/reviews/pmem/rpma/821#-MSWPgWzBrHm9MoFNpmM:-MSWrF0SDbbyLJ7Zv-Dd:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/0c02737564ec197598e653729ccca286bb898ee9/tools/rpma_fio_bench.sh#L46)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> it does not the actual execution
> ```
what does it mean?
</blockquote></details>

.
___
*[tools/rpma_fio_bench.sh, line 81 at r1](https://reviewable.io/reviews/pmem/rpma/821#-MSWP2BD8OxJjM4OwdXS:-MSWrJJh1GreHmvk5tNA:bf429n9) ([raw file](https://github.com/pmem/rpma/blob/0c02737564ec197598e653729ccca286bb898ee9/tools/rpma_fio_bench.sh#L81)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>


if [ "$1" == "--log" ]; then
	LOG_CMDS=1
        shift 1
fi

</blockquote></details>

I do not see much difference between the new parameter and e.g. `SHORT_RUNTIME`. Why you would like to see it as a command-line parameter? It is so hard to do:
- `LOG_CMDS=1 ./run_fio_bench.sh $SERVER all` vs
- `./run_fio_bench.sh --log $SERVER all`.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/821)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tools/ib_read.sh, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/821#-MSWMuvl2-xevExhTJsx:-MSWsdta2lTJDab1zUAK:b-bwdm79) ([raw file](https://github.com/pmem/rpma/blob/0c02737564ec197598e653729ccca286bb898ee9/tools/ib_read.sh#L39)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I mean turning on this option suppresses the main function of this script, namely when it is turned on no benchmark will be executed.
</blockquote></details>

```It shows only the actual execution```
___
*[tools/ib_read.sh, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/821#-MSWso6q8yn_ewa-ofyX:-MSWso6q8yn_ewa-ofyY:b-4mtw3u) ([raw file](https://github.com/pmem/rpma/blob/0c02737564ec197598e653729ccca286bb898ee9/tools/ib_read.sh#L39)):*
> ```
> LOG_CMDS
> ```
```SHOW_CMDS```
___
*[tools/rpma_fio_bench.sh, line 81 at r1](https://reviewable.io/reviews/pmem/rpma/821#-MSWP2BD8OxJjM4OwdXS:-MSWsS1E0ZzhG_oIk1BZ:b-2hok0y) ([raw file](https://github.com/pmem/rpma/blob/0c02737564ec197598e653729ccca286bb898ee9/tools/rpma_fio_bench.sh#L81)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I do not see much difference between the new parameter and e.g. `SHORT_RUNTIME`. Why you would like to see it as a command-line parameter? It is so hard to do:
- `LOG_CMDS=1 ./run_fio_bench.sh $SERVER all` vs
- `./run_fio_bench.sh --log $SERVER all`.
</blockquote></details>

but this means that also --env shall be removed unified

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/821)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tools/rpma_fio_bench.sh, line 46 at r1](https://reviewable.io/reviews/pmem/rpma/821#-MSWPgWzBrHm9MoFNpmM:-MSWsvG4-YhCoJaLrFOo:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/0c02737564ec197598e653729ccca286bb898ee9/tools/rpma_fio_bench.sh#L46)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/821)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tools/rpma_fio_bench.sh, line 81 at r1](https://reviewable.io/reviews/pmem/rpma/821#-MSWP2BD8OxJjM4OwdXS:-MSWyowR7q-yCNud21rl:bvls39n) ([raw file](https://github.com/pmem/rpma/blob/0c02737564ec197598e653729ccca286bb898ee9/tools/rpma_fio_bench.sh#L81)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

but this means that also --env shall be removed unified
</blockquote></details>

`--env` has really nothing to do with all other arguments and even adding any other option to the command-line has no sense if you use `--env` (this is why it is a completely separate command-line variant). This is not the case for `LOG_CMDS` where all other parameters are needed the most for proper commands log generation.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/821)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tools/ib_read.sh, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/821#-MSWMuvl2-xevExhTJsx:-MSWq2T5DPZlzxdYVuKu:b-7nedap) ([raw file](https://github.com/pmem/rpma/blob/0c02737564ec197598e653729ccca286bb898ee9/tools/ib_read.sh#L39)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```It shows only the actual execution```
</blockquote></details>

@janekmi a verb is missing in this sentence - it is not a correct English sentence

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/821)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/821)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/821)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/ib_read.sh, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/821#-MSWso6q8yn_ewa-ofyX:-MSXC2_jATAqn0v0wVAZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0c02737564ec197598e653729ccca286bb898ee9/tools/ib_read.sh#L39)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> LOG_CMDS
> ```
```SHOW_CMDS```
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/821)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tools/ib_read.sh, line 167 at r3](https://reviewable.io/reviews/pmem/rpma/821#-MSXCFjSEEflNDrSzLUb:-MSXCFjSEEflNDrSzLUc:b-mf0cm1) ([raw file](https://github.com/pmem/rpma/blob/0413cf4e710de69b6082c84e77f9da84e4a5b5b5/tools/ib_read.sh#L167)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 		SERVER=${NAME}-server.log
> 		CLIENT=${NAME}-client.log
> 		echo "Log commands [server]: $SERVER"
> 		echo "Log commands [client]: $CLIENT"
> ```
</details>


Maybe `SERVER_LOG` and `CLIENT_LOG` ?
___
*[tools/ib_read.sh, line 39 at r4](https://reviewable.io/reviews/pmem/rpma/821#-MSXCY5WAlCAhDOCJRdQ:-MSXCY5X6I3U9KbpPH4G:b4vo6c9) ([raw file](https://github.com/pmem/rpma/blob/1dbcd10e196230098a4d656c312a6ca12b5bb448/tools/ib_read.sh#L39)):*
> ```
> it does not run the actual execution
> ```

`... but only logs all commands that would be executed)` ?
___
*[tools/rpma_fio_bench.sh, line 46 at r3](https://reviewable.io/reviews/pmem/rpma/821#-MSXCsT947knkg6wFWxL:-MSXCsT947knkg6wFWxM:b-dflbho) ([raw file](https://github.com/pmem/rpma/blob/0413cf4e710de69b6082c84e77f9da84e4a5b5b5/tools/rpma_fio_bench.sh#L46)):*
> ```
> (it does not run the actual execution)"
> ```

`... but only logs all commands that would be executed)` ?
___
*[tools/rpma_fio_bench.sh, line 214 at r3](https://reviewable.io/reviews/pmem/rpma/821#-MSXCwxb2KPguH5NynmP:-MSXCwxb2KPguH5NynmQ:b-y8hshf) ([raw file](https://github.com/pmem/rpma/blob/0413cf4e710de69b6082c84e77f9da84e4a5b5b5/tools/rpma_fio_bench.sh#L214)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> 		SERVER=${NAME}-server.log
> 		CLIENT=${NAME}-client.log
> 		echo "Log commands [server]: $SERVER"
> 		echo "Log commands [client]: $CLIENT"
> ```
</details>


.

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/821)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @janekmi)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/821)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/821#-:-MSXE4my40VvvC3fOe0X:bg7igkv)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/821)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/821)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/821#-:-MSXF9-N5GQAQ-59blrA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/821)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/821#-:-MSXGvH8ByosCBdfY2Cq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
