### PR TITLE
tools: do not fail ddio.sh when 'if' conditions are not met

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/774)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/774)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/ddio.sh, line 4 at r1](https://reviewable.io/reviews/pmem/rpma/774#-MRydCVx9mQ36lJGI3cj:-MRydCVx9mQ36lJGI3ck:b-7k8v93) ([raw file](https://github.com/pmem/rpma/blob/22e0a89a905e3ab45b1a6c9be64f80b096b6a352/tools/ddio.sh#L4)):*
> ```Shell
> #
> # SPDX-License-Identifier: BSD-3-Clause
> # Copyright 2020, Intel Corporation
> ```

2020-2021

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/774)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/ddio.sh, line 4 at r1](https://reviewable.io/reviews/pmem/rpma/774#-MRydCVx9mQ36lJGI3cj:-MRydOWs08z3DxvEN6ot:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/22e0a89a905e3ab45b1a6c9be64f80b096b6a352/tools/ddio.sh#L4)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

2020-2021
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/774)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/774#-:-MRye1Fe6m6prQFV1v23:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/774)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[tools/ddio.sh, line 184 at r3](https://reviewable.io/reviews/pmem/rpma/774#-MRzClV04GmD0Tqp1Du9:-MRzClV04GmD0Tqp1DuA:b-vur72e) ([raw file](https://github.com/pmem/rpma/blob/7ff94c0adc418e0e785860d9303427414d18d210/tools/ddio.sh#L184)):*
> ```Shell
> 	[ -z "$device" ] && usage "device required: $device" 
> 	setpci -s "$device" "$perfctrlsts_0_reg" 2>&1 > /dev/null
> 	[ "$?" -ne "0" ] && usage "invalid device: $device"
> ```

I know this is not the last command in any execution path but the script will fail if somebody won't notice this function may fail on success too.
___
*[tools/ddio.sh, line 193 at r3](https://reviewable.io/reviews/pmem/rpma/774#-MRzD1g_93DPmYEjDA2t:-MRzD1g_93DPmYEjDA2u:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/7ff94c0adc418e0e785860d9303427414d18d210/tools/ddio.sh#L193)):*
> ```Shell
> function _require_root()
> {
> 	[ "$EUID" -ne "0" ] && usage "root privileges required"
> ```

.
___
*[tools/ddio.sh, line 252 at r3](https://reviewable.io/reviews/pmem/rpma/774#-MRzD6I53cWj8QihpqJP:-MRzD6I53cWj8QihpqJQ:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/7ff94c0adc418e0e785860d9303427414d18d210/tools/ddio.sh#L252)):*
> ```Shell
> 		pcs1=$(_bit_enable "$pcs1" "$tphdis_bit")
> 		pcs1_mod=1
> 	}
> ```

.
___
*[tools/ddio.sh, line 276 at r3](https://reviewable.io/reviews/pmem/rpma/774#-MRzD7dG7t-UwkQNHi5O:-MRzD7dG7t-UwkQNHi5P:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/7ff94c0adc418e0e785860d9303427414d18d210/tools/ddio.sh#L276)):*
> ```Shell
> 		pcs1=$(_bit_disable "$pcs1" "$tphdis_bit")
> 		pcs1_mod=1
> 	}
> ```

.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/774)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/774#-MRzDDLn8zNzhDzwq_Oj:-MRzDDLn8zNzhDzwq_Ok:ba2sjwo) (no related file):*
Good catch. ;-)

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/774)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[tools/ddio.sh, line 184 at r3](https://reviewable.io/reviews/pmem/rpma/774#-MRzClV04GmD0Tqp1Du9:-MS1TMxe7PDKcMmvHS9d:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7ff94c0adc418e0e785860d9303427414d18d210/tools/ddio.sh#L184)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I know this is not the last command in any execution path but the script will fail if somebody won't notice this function may fail on success too.
</blockquote></details>

Done.
___
*[tools/ddio.sh, line 193 at r3](https://reviewable.io/reviews/pmem/rpma/774#-MRzD1g_93DPmYEjDA2t:-MS1TSJz9GNvKU0WiTyx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7ff94c0adc418e0e785860d9303427414d18d210/tools/ddio.sh#L193)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/ddio.sh, line 252 at r3](https://reviewable.io/reviews/pmem/rpma/774#-MRzD6I53cWj8QihpqJP:-MS1Tgx-7A6EQSYkNv7x:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7ff94c0adc418e0e785860d9303427414d18d210/tools/ddio.sh#L252)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/ddio.sh, line 276 at r3](https://reviewable.io/reviews/pmem/rpma/774#-MRzD7dG7t-UwkQNHi5O:-MS1Thic97BlMRh4qaUk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7ff94c0adc418e0e785860d9303427414d18d210/tools/ddio.sh#L276)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/774#-:-MS24U581sVHuXGytJiO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
