### PR TITLE
rpma: improve README.md file

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1966)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
Preview: https://github.com/ldorau/rpma/blob/rpma-improve-README.md-file/README.md

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1966#-:-N8TcaDk2W1bUJIcYsiQ:b-neipca)* status: 0 of 1 files reviewed, all discussions resolved

**Review by haichangsi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1966)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[`README.md` line 43 at r1](https://reviewable.io/reviews/pmem/rpma/1966#-N8Tj3f5DiyExTiiyNGN:-N8Tj3f5DiyExTiiyNGO:b2niczw) ([raw file](https://github.com/pmem/rpma/blob/21a143c3a7fbd0742e4dde2831212b0f9cb0408f/README.md#L43)):*
> ```Markdown
> ## More Info
> 
> [Persistent Memory Over Traditional RDMA White Paper - Part 1](https://software.intel.com/content/www/us/en/develop/articles/persistent-memory-replication-over-traditional-rdma-part-1-understanding-remote-persistent.html) - which describes a technology behind RPMA. **Note:** Parts 2-4 relates directly to librpmem library which is a predecessor of librpma. So parts 2-4 do not relate exactly to how librpma works.
> ```

the



_Code quote:_
```Markdown
to librpmem library
```
___
*[`README.md` line 43 at r1](https://reviewable.io/reviews/pmem/rpma/1966#-N8TjFvGC77yihv99ORj:-N8TjFvH0KnWDoxd4Fv5:b2niczw) ([raw file](https://github.com/pmem/rpma/blob/21a143c3a7fbd0742e4dde2831212b0f9cb0408f/README.md#L43)):*
> ```Markdown
> ## More Info
> 
> [Persistent Memory Over Traditional RDMA White Paper - Part 1](https://software.intel.com/content/www/us/en/develop/articles/persistent-memory-replication-over-traditional-rdma-part-1-understanding-remote-persistent.html) - which describes a technology behind RPMA. **Note:** Parts 2-4 relates directly to librpmem library which is a predecessor of librpma. So parts 2-4 do not relate exactly to how librpma works.
> ```

the



_Code quote:_
```Markdown
of librpma
```
___
*[`README.md` line 43 at r1](https://reviewable.io/reviews/pmem/rpma/1966#-N8TjHz2EWFMc2MfhQJV:-N8TjHz2EWFMc2MfhQJW:b2niczw) ([raw file](https://github.com/pmem/rpma/blob/21a143c3a7fbd0742e4dde2831212b0f9cb0408f/README.md#L43)):*
> ```Markdown
> ## More Info
> 
> [Persistent Memory Over Traditional RDMA White Paper - Part 1](https://software.intel.com/content/www/us/en/develop/articles/persistent-memory-replication-over-traditional-rdma-part-1-understanding-remote-persistent.html) - which describes a technology behind RPMA. **Note:** Parts 2-4 relates directly to librpmem library which is a predecessor of librpma. So parts 2-4 do not relate exactly to how librpma works.
> ```

the



_Code quote:_
```Markdown
ow librpma
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1966)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

___
*[`README.md` line 43 at r1](https://reviewable.io/reviews/pmem/rpma/1966#-N8Tj3f5DiyExTiiyNGN:-N8XKwDVEDAW3rvOiH0L:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/21a143c3a7fbd0742e4dde2831212b0f9cb0408f/README.md#L43)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

the
</blockquote></details>

Done.
___
*[`README.md` line 43 at r1](https://reviewable.io/reviews/pmem/rpma/1966#-N8TjFvGC77yihv99ORj:-N8XL8OdDRDWboLtiwzk:b-mr6bqf) ([raw file](https://github.com/pmem/rpma/blob/21a143c3a7fbd0742e4dde2831212b0f9cb0408f/README.md#L43)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

the
</blockquote></details>

Why? Do you know a grammar rule for this case? IMHO there are two correct possibilities: `the librpma library` or `librpma` (without any article, because it is an "own" name): 
https://ell.stackexchange.com/questions/59742/should-the-names-of-computer-programs-and-libraries-be-preceded-by-an-article
___
*[`README.md` line 43 at r1](https://reviewable.io/reviews/pmem/rpma/1966#-N8TjHz2EWFMc2MfhQJV:-N8XMaU0BlRAo1MOqu_S:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/21a143c3a7fbd0742e4dde2831212b0f9cb0408f/README.md#L43)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

the
</blockquote></details>

.

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1966)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[`README.md` line 43 at r1](https://reviewable.io/reviews/pmem/rpma/1966#-N8TjFvGC77yihv99ORj:-N8Xab1o8P1TLWZwqTii:b-spewqy) ([raw file](https://github.com/pmem/rpma/blob/21a143c3a7fbd0742e4dde2831212b0f9cb0408f/README.md#L43)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why? Do you know a grammar rule for this case? IMHO there are two correct possibilities: `the librpma library` or `librpma` (without any article, because it is an "own" name): 
https://ell.stackexchange.com/questions/59742/should-the-names-of-computer-programs-and-libraries-be-preceded-by-an-article

</blockquote></details>

Mostly because creators of the word often define such a thing, it seems to me that you defined it this way (https://pmem.io/rpma/), also you use it this way above, 'the X library' so for me it is natural to use it also with 'the X' when you obviously mean 'the X library', if you think I am not correct then just leave it the way it is
___
*[`README.md` line 43 at r1](https://reviewable.io/reviews/pmem/rpma/1966#-N8TjHz2EWFMc2MfhQJV:-N8XcesREw2cyILVHkat:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/21a143c3a7fbd0742e4dde2831212b0f9cb0408f/README.md#L43)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1966)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @haichangsi)

___
*[`README.md` line 43 at r1](https://reviewable.io/reviews/pmem/rpma/1966#-N8TjFvGC77yihv99ORj:-N8XtbTI609y_yNiFo12:b-hp1h2s) ([raw file](https://github.com/pmem/rpma/blob/21a143c3a7fbd0742e4dde2831212b0f9cb0408f/README.md#L43)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Mostly because creators of the word often define such a thing, it seems to me that you defined it this way (https://pmem.io/rpma/), also you use it this way above, 'the X library' so for me it is natural to use it also with 'the X' when you obviously mean 'the X library', if you think I am not correct then just leave it the way it is
</blockquote></details>

I decided to leave it as is (without any article), because of two reasons:
1) `libgcc` for example does the same: https://gcc.gnu.org/onlinedocs/gccint/Libgcc.html
2) consistency - there are **about 190** occurrences of `librpma` without any article and **only 2** `the librpma` (I will change them too in a separate PR).
___
*[`README.md` line 43 at r1](https://reviewable.io/reviews/pmem/rpma/1966#-N8TjHz2EWFMc2MfhQJV:-N8XuhDiE91d1hr2UEI5:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/21a143c3a7fbd0742e4dde2831212b0f9cb0408f/README.md#L43)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

.
</blockquote></details>

.

**Review by haichangsi — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1966#-:-N8XxrMx9Ayqz4IKJR-M:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
