### PR TITLE
examples: add running all examples under valgrind

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #988 

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/986)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 10 files at r1, 2 of 9 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/986#-:-MY4SS1S3uwuTZ7RDDca:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 10 files at r1, 4 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/986)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[examples/memcheck-librdmacm.supp, line 1 at r2](https://reviewable.io/reviews/pmem/rpma/986#-MY4V3E7Ea7fg0TVlJY2:-MY4V3E89AoBDtBV-l5c:bo2ugtw) ([raw file](https://github.com/pmem/rpma/blob/6aacdddf69b7bcd4772815bc1e3ed636ddcec168/examples/memcheck-librdmacm.supp#L1)):*
> ```
> {
> ```

This file should be called: memcheck-libibverbs.supp.
___
*[examples/memcheck-librdmacm.supp, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/986#-MY4VJRE7Zn1ZZ_LFcIs:-MY4VJRE7Zn1ZZ_LFcIt:b-vy7my5) ([raw file](https://github.com/pmem/rpma/blob/6aacdddf69b7bcd4772815bc1e3ed636ddcec168/examples/memcheck-librdmacm.supp#L2)):*
> ```
> {
>    Verbs devices, once they are opened, are never closed (RXE variant)
> ```

'context' and 'device' words are used in a not very obvious way. This is a good example since the call stack starts from device but at the top we got context. Since verbs providers API is as follow I think we should rename this suppression to:

- Verbs context, ...

Whereas the one below (`<ucma_init -> try_all_drivers>`)should be called:

- Verbs device, ...
___
*[examples/memcheck-librdmacm.supp, line 30 at r2](https://reviewable.io/reviews/pmem/rpma/986#-MY4UNfF1cZdrpc5MDv9:-MY4UNfF1cZdrpc5MDvA:b-5vtp7b) ([raw file](https://github.com/pmem/rpma/blob/6aacdddf69b7bcd4772815bc1e3ed636ddcec168/examples/memcheck-librdmacm.supp#L30)):*
> ```
> 
> {
>    <ucma_init -> find_sysfs_devs_nl>
> ```

Sysfs device, once it is allocated, is not freed.

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/986)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[examples/memcheck-librdmacm.supp, line 1 at r2](https://reviewable.io/reviews/pmem/rpma/986#-MY4W8bzEwGxt4hh2qdg:-MY4W8bzEwGxt4hh2qdh:b-5fmoad) ([raw file](https://github.com/pmem/rpma/blob/6aacdddf69b7bcd4772815bc1e3ed636ddcec168/examples/memcheck-librdmacm.supp#L1)):*
> ```
> {
> ```

Secondly, I'm not sure it should be kept in the examples directory. It would be used also for MT tests, right?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/986)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[examples/memcheck-librdmacm.supp, line 1 at r2](https://reviewable.io/reviews/pmem/rpma/986#-MY4V3E7Ea7fg0TVlJY2:-MY4aA4z-37L1L3vjg3h:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6aacdddf69b7bcd4772815bc1e3ed636ddcec168/examples/memcheck-librdmacm.supp#L1)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This file should be called: memcheck-libibverbs.supp.
</blockquote></details>

Done.
___
*[examples/memcheck-librdmacm.supp, line 1 at r2](https://reviewable.io/reviews/pmem/rpma/986#-MY4W8bzEwGxt4hh2qdg:-MY4aATz8lm05UpvY3G3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6aacdddf69b7bcd4772815bc1e3ed636ddcec168/examples/memcheck-librdmacm.supp#L1)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Secondly, I'm not sure it should be kept in the examples directory. It would be used also for MT tests, right?
</blockquote></details>

Done.
___
*[examples/memcheck-librdmacm.supp, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/986#-MY4VJRE7Zn1ZZ_LFcIs:-MY4cI8E28SCOsYL3N4O:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6aacdddf69b7bcd4772815bc1e3ed636ddcec168/examples/memcheck-librdmacm.supp#L2)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

'context' and 'device' words are used in a not very obvious way. This is a good example since the call stack starts from device but at the top we got context. Since verbs providers API is as follow I think we should rename this suppression to:

- Verbs context, ...

Whereas the one below (`<ucma_init -> try_all_drivers>`)should be called:

- Verbs device, ...
</blockquote></details>

Done.
___
*[examples/memcheck-librdmacm.supp, line 30 at r2](https://reviewable.io/reviews/pmem/rpma/986#-MY4UNfF1cZdrpc5MDv9:-MY4cIUDBQEzplG25im5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6aacdddf69b7bcd4772815bc1e3ed636ddcec168/examples/memcheck-librdmacm.supp#L30)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Sysfs device, once it is allocated, is not freed.
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
Commit message fixed

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/986#-:-MY5VYVo4rUtAZ81LDlg:bs2d8rb)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
