### PR TITLE
common: tools: ib_read_lat trim output

### PR DESCRIPTION
**Pull request by janekmi**
Trimming allows aligning header and value rows
and get rid off preceding CSV column.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/619)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/619)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/ib_read_lat.sh, line 70 at r1](https://reviewable.io/reviews/pmem/rpma/619#-MNdOyk1BA7nOyUUg6jd:-MNdOyk1BA7nOyUUg6je:b-8oblxh) ([raw file](https://github.com/pmem/rpma/blob/2cf59b098e696bb7f6d8fb2038da94c5e855d004/tools/ib_read_lat.sh#L70)):*
> ```Shell
>         --perform_warm_up $SERVER_IP $AUX_PARAMS 2>>$LOG_ERR | grep $ds | \
>         grep -v '[B]' | sed 's/^[ ]*//' | sed 's/[ ]*$//' | \
> 	sed -r 's/[[:blank:]]+/,/g' >> $OUTPUT
> ```

+ tab

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/619)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/ib_read_lat.sh, line 70 at r1](https://reviewable.io/reviews/pmem/rpma/619#-MNdOyk1BA7nOyUUg6jd:-MNdS0kN8QymuhJV6v99:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2cf59b098e696bb7f6d8fb2038da94c5e855d004/tools/ib_read_lat.sh#L70)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

+ tab
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/619#-:-MNdS98K9o3eGq32_tHu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/619)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
