### PR TITLE
common: find libibverbs and librdmacm w/o PkgConfig

### PR DESCRIPTION
**Pull request by ldorau**
Make it possible to find the libibverbs and librdmacm libraries
without PkgConfig (e.g. when those libraries do not provide
a package-config file (*.pc) what happens in case of older OS releases.

Ref: #289

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/345)

### CODE REVIEW

**Comment by ldorau** [comment]
Build of rpma succeeds, only " Testing standalone compilation of examples" fails:
https://github.com/ldorau/rpma/actions/runs/237714635
- it will be fixed in a separate PR

**Comment by ldorau** [comment]
> Build of rpma succeeds, only " Testing standalone compilation of examples" fails:
> it will be fixed in a separate PR

The correct link is: https://github.com/ldorau/rpma/actions/runs/237764834

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 15 files at r3, 13 of 13 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/345)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/345#-MGgkFoGAmyTBnOM2UoG:-MGgkFoH1CDcAd6cd9XE:b-8cioiv) (no related file):*
Please rebase.

---
___
*[cmake/FindLIBIBVERBS.cmake, line 12 at r4](https://reviewable.io/reviews/pmem/rpma/345#-MGgrPoCADqDl67AbO0t:-MGgrPoCADqDl67AbO0u:bytea1d) ([raw file](https://github.com/pmem/rpma/blob/b4837adefbdb24084e645bdd303d8e35a686ea0d/cmake/FindLIBIBVERBS.cmake#L12)):*
> ```CMake
> 
> if(LIBIBVERBS_LIBRARY)
> 	message(STATUS "  Found libibverbs w/o PkgConfig")
> ```

Too many spaces.
___
*[cmake/FindLIBRDMACM.cmake, line 12 at r4](https://reviewable.io/reviews/pmem/rpma/345#-MGgroPg6l1TYuFJeJUS:-MGgroPg6l1TYuFJeJUT:bytea1d) ([raw file](https://github.com/pmem/rpma/blob/b4837adefbdb24084e645bdd303d8e35a686ea0d/cmake/FindLIBRDMACM.cmake#L12)):*
> ```CMake
> 
> if(LIBRDMACM_LIBRARY)
> 	message(STATUS "  Found librdmacm w/o PkgConfig")
> ```

Too many spaces.
___
*[cmake/librpma.pc.in, line 8 at r4](https://reviewable.io/reviews/pmem/rpma/345#-MGglvSiAhlhXHYDh-pu:-MGglvSiAhlhXHYDh-pv:bsx4f2f) ([raw file](https://github.com/pmem/rpma/blob/b4837adefbdb24084e645bdd303d8e35a686ea0d/cmake/librpma.pc.in#L8)):*
> ```
> Version: @VERSION@
> URL: https://github.com/pmem/rpma
> Requires: libibverbs librdmacm
> ```

This part was modified by another PR. Rebase should clean it up. ;-)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/345)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/345#-MGgkFoGAmyTBnOM2UoG:-MGh-9BA-1oOUhTSr9jD:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please rebase.
</blockquote></details>

Done.

---
___
*[cmake/FindLIBIBVERBS.cmake, line 12 at r4](https://reviewable.io/reviews/pmem/rpma/345#-MGgrPoCADqDl67AbO0t:-MGgyS377H_w1tUx0_qF:bpiygt5) ([raw file](https://github.com/pmem/rpma/blob/b4837adefbdb24084e645bdd303d8e35a686ea0d/cmake/FindLIBIBVERBS.cmake#L12)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Too many spaces.
</blockquote></details>

It is on purpose:
```
-- Checking for module 'libibverbs'
--   No package 'libibverbs' found
-- Checking for module 'libibverbs' w/o PkgConfig
--   Found libibverbs w/o PkgConfig
-- Checking for module 'librdmacm'
--   No package 'librdmacm' found
-- Checking for module 'librdmacm' w/o PkgConfig
--   Found librdmacm w/o PkgConfig
```
___
*[cmake/FindLIBRDMACM.cmake, line 12 at r4](https://reviewable.io/reviews/pmem/rpma/345#-MGgroPg6l1TYuFJeJUS:-MGgyZDeBPyH8oKVJc4y:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/b4837adefbdb24084e645bdd303d8e35a686ea0d/cmake/FindLIBRDMACM.cmake#L12)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Too many spaces.
</blockquote></details>

.
___
*[cmake/librpma.pc.in, line 8 at r4](https://reviewable.io/reviews/pmem/rpma/345#-MGglvSiAhlhXHYDh-pu:-MGh-B-A6CIfC-8LhwJW:b7udaov) ([raw file](https://github.com/pmem/rpma/blob/b4837adefbdb24084e645bdd303d8e35a686ea0d/cmake/librpma.pc.in#L8)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This part was modified by another PR. Rebase should clean it up. ;-)
</blockquote></details>

Rebased. Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/345#-:-MGhD0XZ78CKKc8-EIw7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 1 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/345#-:-MGhJAUr7gfoAQZ5XyVu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
