### PR TITLE
examples: validate a value of timeout in example 13

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1978)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
@yangx-jy please review

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1978#-:-N8xnIVQ-BDIg4rhaH38:b-wlz2sy)* status: 0 of 12 files reviewed, all discussions resolved

**Comment by yangx-jy** [comment]
*[`examples/13-messages-ping-pong-with-srq/server.c` line 137 at r1](https://reviewable.io/reviews/pmem/rpma/1978#-N8xrAAl44Mfzk86Dku8:-N8xrAAl44Mfzk86Dku9:bua0tcr) ([raw file](https://github.com/pmem/rpma/blob/0242efbb8e5ae612ff08424e545ad51d5de35372/examples/13-messages-ping-pong-with-srq/server.c#L137)):*
> ```C
> 	char *addr = argv[1];
> 	char *port = argv[2];
> 	int timeout = argv[3] ? strtoul_noerror(argv[3]) * 1000 : TIMEOUT_5S;
> ```

@ldorau

Why do we need to call `strtoul_noerror` here? `epoll_wait()` uses `int` timeout argument so I think `atoi()` is enough.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1978)* status: 0 of 12 files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[`examples/13-messages-ping-pong-with-srq/server.c` line 137 at r1](https://reviewable.io/reviews/pmem/rpma/1978#-N8xrAAl44Mfzk86Dku8:-N90TBXP2IxLSX3e3LtM:bmxe06y) ([raw file](https://github.com/pmem/rpma/blob/0242efbb8e5ae612ff08424e545ad51d5de35372/examples/13-messages-ping-pong-with-srq/server.c#L137)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

@ldorau

Why do we need to call `strtoul_noerror` here? `epoll_wait()` uses `int` timeout argument so I think `atoi()` is enough.
</blockquote></details>

Yes, `atoi()` is enough. My purpose was that `strtoul_noerror()` has an error handling. We can leave `atoi()` here, but we should add an error handling ...

**Review by haichangsi — COMMENTED** [review]
:lgtm: 

> Reviewed 12 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1978#-:-N90Zi012CxgynhkQ3gi:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

**Comment by yangx-jy** [comment]
*[`examples/13-messages-ping-pong-with-srq/server.c` line 141 at r2](https://reviewable.io/reviews/pmem/rpma/1978#-N90yr_a7ERr9E6NW5BT:-N90yr_a7ERr9E6NW5BU:b-lwhqhv) ([raw file](https://github.com/pmem/rpma/blob/6896e95f2cd258cd12e30315c053d4ba7fd7edcb/examples/13-messages-ping-pong-with-srq/server.c#L141)):*
> ```C
> 	if (timeout == 0) {
> 		(void) fprintf(stderr, "atoi() failed - incorrect <timeout> value: %s\n", argv[3]);
> 		return -1;
> ```

@ldorau 

According to atoi(3)'s manual, there is no way to distinguish between 0 as an error and as the converted value.  So this check seems meaningless.

However, we may need to check if timeout is a positive number. for example:
```
if (timeout <= 0) {
    (void) fprintf(stderr, "<timeout> value should be a positive number\n");
    return -1;
}
```
`timeout == 0' makes `epoll_wait()` return immediately even if no events are available. `timeout < 0` makes `epoll_wait()` block indefinitely.  I think both of them are invalid for the example.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1978)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @haichangsi and @yangx-jy)

___
*[`examples/13-messages-ping-pong-with-srq/server.c` line 141 at r2](https://reviewable.io/reviews/pmem/rpma/1978#-N90yr_a7ERr9E6NW5BT:-N912SAAEqi0RApJEZDy:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6896e95f2cd258cd12e30315c053d4ba7fd7edcb/examples/13-messages-ping-pong-with-srq/server.c#L141)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

@ldorau 

According to atoi(3)'s manual, there is no way to distinguish between 0 as an error and as the converted value.  So this check seems meaningless.

However, we may need to check if timeout is a positive number. for example:
```
if (timeout <= 0) {
    (void) fprintf(stderr, "<timeout> value should be a positive number\n");
    return -1;
}
```
`timeout == 0' makes `epoll_wait()` return immediately even if no events are available. `timeout < 0` makes `epoll_wait()` block indefinitely.  I think both of them are invalid for the example.
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1978)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @haichangsi and @yangx-jy)

___
*[`examples/13-messages-ping-pong-with-srq/server.c` line 137 at r1](https://reviewable.io/reviews/pmem/rpma/1978#-N8xrAAl44Mfzk86Dku8:-N912WYN8Nb4nEzTewlI:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0242efbb8e5ae612ff08424e545ad51d5de35372/examples/13-messages-ping-pong-with-srq/server.c#L137)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, `atoi()` is enough. My purpose was that `strtoul_noerror()` has an error handling. We can leave `atoi()` here, but we should add an error handling ...
</blockquote></details>

Done.

**Comment by yangx-jy** [comment]
*[`examples/13-messages-ping-pong-with-srq/server.c` line 141 at r2](https://reviewable.io/reviews/pmem/rpma/1978#-N90yr_a7ERr9E6NW5BT:-N912IwJ7KdoeDqaRS7E:b-6cu7he) ([raw file](https://github.com/pmem/rpma/blob/6896e95f2cd258cd12e30315c053d4ba7fd7edcb/examples/13-messages-ping-pong-with-srq/server.c#L141)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@ldorau  If you want to check if atoi() failed, is it ok to add "atoi() failed or " into the output?
```
(void) fprintf(stderr, "atoi() failed or <timeout> should be a positive number of seconds (%s given)\n", argv[3]);
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1978)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @haichangsi and @yangx-jy)

___
*[`examples/13-messages-ping-pong-with-srq/server.c` line 141 at r2](https://reviewable.io/reviews/pmem/rpma/1978#-N90yr_a7ERr9E6NW5BT:-N916VGb48zaYfyDKJst:b-m7xd16) ([raw file](https://github.com/pmem/rpma/blob/6896e95f2cd258cd12e30315c053d4ba7fd7edcb/examples/13-messages-ping-pong-with-srq/server.c#L141)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

@ldorau  If you want to check if atoi() failed, is it ok to add "atoi() failed or " into the output?
```
(void) fprintf(stderr, "atoi() failed or <timeout> should be a positive number of seconds (%s given)\n", argv[3]);
```
</blockquote></details>

I think that the current message is enough.

**Review by yangx-jy — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1978#-:-N917RKy9f6n9WrBD2V4:bnfp4nl)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @haichangsi and @ldorau)

___
*[`examples/13-messages-ping-pong-with-srq/server.c` line 141 at r2](https://reviewable.io/reviews/pmem/rpma/1978#-N90yr_a7ERr9E6NW5BT:-N917TB62pqwmfDEboe_:bvw2yns) ([raw file](https://github.com/pmem/rpma/blob/6896e95f2cd258cd12e30315c053d4ba7fd7edcb/examples/13-messages-ping-pong-with-srq/server.c#L141)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I think that the current message is enough.
</blockquote></details>

Agreed. It's OK to me. ^_^

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1978)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @haichangsi and @yangx-jy)

___
*[`examples/13-messages-ping-pong-with-srq/server.c` line 141 at r2](https://reviewable.io/reviews/pmem/rpma/1978#-N90yr_a7ERr9E6NW5BT:-N91azwPCgZcwaO4IYEc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6896e95f2cd258cd12e30315c053d4ba7fd7edcb/examples/13-messages-ping-pong-with-srq/server.c#L141)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Agreed. It's OK to me. ^_^
</blockquote></details>

Done.

**Comment by ldorau** [comment]
@yangx-jy Thanks a lot for the review!

**Pull request merged**
