### PR TITLE
common: separate folder for all benchmarking tools

### PR DESCRIPTION
**Pull request by grom72**
Separate folder for benchmarking stuff to keep main tools folder for more generic items i.e. ddio, softroce configuration

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/810)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 31 of 31 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/810)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/810)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/810#-MSi7fPeBIQSwjNX8fWW:-MSi7fPeBIQSwjNX8fWX:b-8cioiv) (no related file):*
Please rebase.

---

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/810)* status: 16 of 37 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/810#-MSi7fPeBIQSwjNX8fWW:-MSj8nyMASBJh60OtPAa:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please rebase.
</blockquote></details>

Done.

---

**Review by ldorau — APPROVED** [review]
> Reviewed 21 of 21 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/810)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/810)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/810#-MSi7fPeBIQSwjNX8fWW:-MSjApcr1-C2-MHn-OHQ:bawcyz2) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please rebase again :-( I am so sorry ...

---

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/810)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/810)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/810#-MSi7fPeBIQSwjNX8fWW:-MSjBgL28QDA1j9AjTBd:bb6tzbb) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please rebase again :-( I am so sorry ...
</blockquote></details>

DOne

---

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/810)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/810)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/810#-:-MSjHQXZ8JtRyGZOoqPZ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 7 of 31 files at r1, 10 of 21 files at r2, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/810)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/810#-MSi7fPeBIQSwjNX8fWW:-MSjOQEA9G-9MBKkiZ-b:b7te2o0) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

DOne
</blockquote></details>

Sorry. Please rebase one more time.

---
___
*[tools/perf/templates/.gitignore, line 10 at r4](https://reviewable.io/reviews/pmem/rpma/810#-MSjOAuO7O3M68bjKUKs:-MSjOAuPAI8TOBtXmeUx:b-co6k4x) ([raw file](https://github.com/pmem/rpma/blob/67329c100c16db0b6a1e9ad4350fbd753798e82f/tools/perf/templates/.gitignore#L10)):*
> ```ignore
> !tc1_read.md
> !tc2_write.md
> !tc3_mix.md
> ```

This file does not longer exist on the master.

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 31 files at r1, 6 of 21 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/810)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/810)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/810)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/810)* status: 26 of 48 files reviewed, 1 unresolved discussion (waiting on @grom72, @janekmi, and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/810#-MSi7fPeBIQSwjNX8fWW:-MSlW7IEABJe_wQzc-Yj:bb6un1j) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Sorry. Please rebase one more time.
</blockquote></details>

Done

---

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/810)* status: 26 of 48 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[tools/perf/templates/.gitignore, line 10 at r4](https://reviewable.io/reviews/pmem/rpma/810#-MSjOAuO7O3M68bjKUKs:-MSlWCz531nICVkL8xt_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/67329c100c16db0b6a1e9ad4350fbd753798e82f/tools/perf/templates/.gitignore#L10)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This file does not longer exist on the master.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 23 of 24 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/810)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 23 of 24 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/810#-:-MSluM-E2dDJY2Sli8bM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/810#-MSltgUn617SeY37XAZm:-MSltgUo9pn6vh5V-07y:b-8xc914) (no related file):*
Please update https://github.com/pmem/rpma/blob/gh-pages/documentation/perf-tuning.md#running-workloads

---

**Pull request merged**
