### PR TITLE
rpma: add the rpma_log_set_function mtt test

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1946)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1946)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1946)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1946)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[`tests/multithreaded/log/rpma_log_set_function.c` line 41 at r1](https://reviewable.io/reviews/pmem/rpma/1946#-N7p0oOp8-ZqzMvzIQNq:-N7p0oOp8-ZqzMvzIQNr:b-ynhrms) ([raw file](https://github.com/pmem/rpma/blob/aa4f139628658f4dfab32694667d6732cff46033/tests/multithreaded/log/rpma_log_set_function.c#L41)):*
> ```C
> 
> 	if ((ret = rpma_log_set_function(RPMA_LOG_USE_DEFAULT_FUNCTION))) {
> 		MTT_RPMA_ERR(tr, "rpma_log_set_function", ret);
> ```

I think it is enough:
```c
/*
 * thread -- set log function
 */
void
thread(unsigned id, void *prestate, void *state, struct mtt_result *tr)
{
	int ret;

	if ((ret = rpma_log_set_function(RPMA_LOG_USE_DEFAULT_FUNCTION))) {
		MTT_RPMA_ERR(tr, "rpma_log_set_function", ret);
		return;
	}
}
```

No other variables, prestates and functions are needed.



_Code quote:_
```C
void
thread(unsigned id, void *prestate, void *state, struct mtt_result *tr)
{
	struct prestate *pr = (struct prestate *)prestate;
	int ret;

	if ((ret = rpma_log_set_function(RPMA_LOG_USE_DEFAULT_FUNCTION))) {
		MTT_RPMA_ERR(tr, "rpma_log_set_function", ret);
		return;
	}
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1946)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

___
*[`tests/multithreaded/log/CMakeLists.txt` line 9 at r1](https://reviewable.io/reviews/pmem/rpma/1946#-N7p1bWs6xWjCev71-6B:-N7p1bWs6xWjCev71-6C:b-lt2300) ([raw file](https://github.com/pmem/rpma/blob/aa4f139628658f4dfab32694667d6732cff46033/tests/multithreaded/log/CMakeLists.txt#L9)):*
> ```CMake
> 
> add_multithreaded(NAME log BIN rpma_log_set_function
> 	SRCS rpma_log_set_function.c ../../../src/log.c ../../../src/log_default.c)
> ```

It will not be needed either.



_Code quote:_
```CMake
../../../src/log.c ../../../src/log_default.c
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1946)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[`tests/multithreaded/log/CMakeLists.txt` line 9 at r1](https://reviewable.io/reviews/pmem/rpma/1946#-N7p1bWs6xWjCev71-6B:-N7p5zLe9ISjqcMiLwRx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/aa4f139628658f4dfab32694667d6732cff46033/tests/multithreaded/log/CMakeLists.txt#L9)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It will not be needed either.
</blockquote></details>

Done.
___
*[`tests/multithreaded/log/rpma_log_set_function.c` line 41 at r1](https://reviewable.io/reviews/pmem/rpma/1946#-N7p0oOp8-ZqzMvzIQNq:-N7p5GmyCjOsZ3tgXLOv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/aa4f139628658f4dfab32694667d6732cff46033/tests/multithreaded/log/rpma_log_set_function.c#L41)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I think it is enough:
```c
/*
 * thread -- set log function
 */
void
thread(unsigned id, void *prestate, void *state, struct mtt_result *tr)
{
	int ret;

	if ((ret = rpma_log_set_function(RPMA_LOG_USE_DEFAULT_FUNCTION))) {
		MTT_RPMA_ERR(tr, "rpma_log_set_function", ret);
		return;
	}
}
```

No other variables, prestates and functions are needed.
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1946)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

___
*[`tests/multithreaded/log/rpma_log_set_function.c` line 10 at r2](https://reviewable.io/reviews/pmem/rpma/1946#-N7pCa387TfNVJzOYVFS:-N7pCa387TfNVJzOYVFT:bpp6stj) ([raw file](https://github.com/pmem/rpma/blob/da0ecff8b7686ed545af6d33e36e2f9f9413b205/tests/multithreaded/log/rpma_log_set_function.c#L10)):*
> ```C
> #include <librpma.h>
> 
> #include "../src/log_default.h"
> ```

not needed



_Code quote:_
```C
#include "../src/log_default.h"
```
___
*[`tests/multithreaded/log/rpma_log_set_function.c` line 14 at r2](https://reviewable.io/reviews/pmem/rpma/1946#-N7pCfJY7fv_PUnvO0z-:-N7pCfJY7fv_PUnvO0z0:b-70aw0n) ([raw file](https://github.com/pmem/rpma/blob/da0ecff8b7686ed545af6d33e36e2f9f9413b205/tests/multithreaded/log/rpma_log_set_function.c#L14)):*
> ```C
> 
> /*
>  * thread -- set log function and check if its value is as expected
> ```

`thread -- set log function`



_Code quote:_
```C
thread -- set log function and check if its value is as expected
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1946)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[`tests/multithreaded/log/rpma_log_set_function.c` line 10 at r2](https://reviewable.io/reviews/pmem/rpma/1946#-N7pCa387TfNVJzOYVFS:-N7pNGp46fTE15Vfblmx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/da0ecff8b7686ed545af6d33e36e2f9f9413b205/tests/multithreaded/log/rpma_log_set_function.c#L10)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

not needed
</blockquote></details>

Done.
___
*[`tests/multithreaded/log/rpma_log_set_function.c` line 14 at r2](https://reviewable.io/reviews/pmem/rpma/1946#-N7pCfJY7fv_PUnvO0z-:-N7pNDxBE_xJkRV7oESH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/da0ecff8b7686ed545af6d33e36e2f9f9413b205/tests/multithreaded/log/rpma_log_set_function.c#L14)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`thread -- set log function`
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1946)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[`tests/multithreaded/log/rpma_log_set_function.c` line 9 at r3](https://reviewable.io/reviews/pmem/rpma/1946#-N7pOCOo4ujxkWmnuCGW:-N7pOCOo4ujxkWmnuCGX:b-nsqcu9) ([raw file](https://github.com/pmem/rpma/blob/f6b6fcd6cd0c0d60db9a5c12ac9847246045e930/tests/multithreaded/log/rpma_log_set_function.c#L9)):*
> ```C
> 
> #include <librpma.h>
> ```

redundant empty line

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1946)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`tests/multithreaded/log/rpma_log_set_function.c` line 9 at r3](https://reviewable.io/reviews/pmem/rpma/1946#-N7pOCOo4ujxkWmnuCGW:-N7t7Z1I1RssFChRpx0y:b-l5dy7i) ([raw file](https://github.com/pmem/rpma/blob/f6b6fcd6cd0c0d60db9a5c12ac9847246045e930/tests/multithreaded/log/rpma_log_set_function.c#L9)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

redundant empty line
</blockquote></details>

Hasn't it always been one empty line between "" and <> includes? Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1946)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[`tests/multithreaded/log/rpma_log_set_threshold.c` line 5 at r4](https://reviewable.io/reviews/pmem/rpma/1946#-N7t9O216CvRxZQNXlAe:-N7t9O216CvRxZQNXlAf:b2u4mu5) ([raw file](https://github.com/pmem/rpma/blob/5d96d4da98b8b9268d5379fbeb726906d71b0dc6/tests/multithreaded/log/rpma_log_set_threshold.c#L5)):*
> ```C
> 
> /*
>  * rpma_log_set_threshold.c -- rpma_log_set_threshold multithreaded test
> ```

It is the rpma_log_set_function mtt test



_Code quote:_
```C
/*
 * rpma_log_set_threshold.c -- rpma_log_set_threshold multithreaded test
 */
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1946)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[`tests/multithreaded/log/rpma_log_set_threshold.c` line 5 at r4](https://reviewable.io/reviews/pmem/rpma/1946#-N7t9O216CvRxZQNXlAe:-N7tllgy5IdlzeJBakfA:b-l825gq) ([raw file](https://github.com/pmem/rpma/blob/5d96d4da98b8b9268d5379fbeb726906d71b0dc6/tests/multithreaded/log/rpma_log_set_threshold.c#L5)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It is the rpma_log_set_function mtt test
</blockquote></details>

there was a problem with a rebase, sorry. done.
___
*[`tests/multithreaded/log/rpma_log_set_threshold.c` line 29 at r4](https://reviewable.io/reviews/pmem/rpma/1946#-N7tQa516822NleRMHzB:-N7tlu_H8YZbw_JQoYxo:b1obxx7) ([raw file](https://github.com/pmem/rpma/blob/5d96d4da98b8b9268d5379fbeb726906d71b0dc6/tests/multithreaded/log/rpma_log_set_threshold.c#L29)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Why don't we check if the rpma_log_get_threshold() function succeeded?
</blockquote></details>

There is another pr for the set_threshold test, sorry.

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1946#-:-N7tn7A_67dM11WLoTWJ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1946)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
