### PR TITLE
examples: fix non null terminated string

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/353)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/353)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/353#-MGNaQczD2F1p2mUGsJy:-MGNaQczD2F1p2mUGsJz:bpsce3) (no related file):*
Please add to the commit message something like:

> Forced by the static analyzer which has pointed out that strncpy \*theoretically\* may not null-terminate the output string.

---

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/353)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/353#-MGNaQczD2F1p2mUGsJy:-MGNboHGCbw43Qv7TXeD:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please add to the commit message something like:

> Forced by the static analyzer which has pointed out that strncpy \*theoretically\* may not null-terminate the output string.
</blockquote></details>

Done.

---

**Review by grom72 — COMMENTED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/353#-:-MGNxIeZ7YbOyZtvts4D:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/353#-:-MGOFxMW1KJla1CpiHQV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
