### PR TITLE
doc: add pylint to INSTALL.md

### PR DESCRIPTION
**Pull request by yangx-jy**
Signed-off-by: Xiao Yang <yangx.jy@fujitsu.com>

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1096)

### CODE REVIEW

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1096#-:-Mcxf-5p69awqjIDmry-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1096#-:-Mcxq9jG3ykYrnAn-k60:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1096)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1096)* status: all files reviewed, 2 unresolved discussions (waiting on @yangx-jy)

___
*[INSTALL.md, line 33 at r1](https://reviewable.io/reviews/pmem/rpma/1096#-McxxSm2AjikBYS6pegC:-McxxSm2AjikBYS6pegD:b-otkigx) ([raw file](https://github.com/pmem/rpma/blob/d6bcac63908201c3c8dc9eb17e62e3a935173f58/INSTALL.md#L33)):*
> ```Markdown
> (see [CMake standard options](INSTALL.md#cmake-standard-options) and
> [Configuring CMake options](INSTALL.md#configuring-cmake-options)).
> ```

```md
### In order to test the Python tools you also need:

- pylint

**Note**: testing the Python tools can be turned off using the CMake 'TEST_PYTHON_TOOLS' option
(see [CMake standard options](INSTALL.md#cmake-standard-options) and
[Configuring CMake options](INSTALL.md#configuring-cmake-options)).
```
___
*[INSTALL.md, line 69 at r1](https://reviewable.io/reviews/pmem/rpma/1096#-McxyMs8BlSkhVrHwg3Y:-McxyMs8BlSkhVrHwg3Z:b1rgy9n) ([raw file](https://github.com/pmem/rpma/blob/d6bcac63908201c3c8dc9eb17e62e3a935173f58/INSTALL.md#L69)):*
> ```Markdown
> | CMAKE_INSTALL_PREFIX | Install path prefix, prepended onto install directories | *dir path* | /usr/local |
> | COVERAGE | Run coverage test | ON/OFF | OFF |
> | DEVELOPER_MODE | Enable developer checks | ON/OFF | OFF |
> ```

```md
| TEST_PYTHON_TOOLS | Enable testing Python tools | ON/OFF | ON |
```

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1096)* status: all files reviewed, 3 unresolved discussions (waiting on @yangx-jy)

___
*[INSTALL.md, line 12 at r1](https://reviewable.io/reviews/pmem/rpma/1096#-McygkrJ0sX_pIdtkEGq:-McygkrJ0sX_pIdtkEGr:b6dtvus) ([raw file](https://github.com/pmem/rpma/blob/d6bcac63908201c3c8dc9eb17e62e3a935173f58/INSTALL.md#L12)):*
> ```Markdown
> - [CMake](http://www.cmake.org) >= 3.3
> - pkg-config
> - pylint
> ```

It is not so strict a requirement. Please see the idea below.

**Review by yangx-jy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1096)* status: 0 of 25 files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[INSTALL.md, line 12 at r1](https://reviewable.io/reviews/pmem/rpma/1096#-McygkrJ0sX_pIdtkEGq:-Md-uvzn4HtwYyRZmu48:b-ozuiy6) ([raw file](https://github.com/pmem/rpma/blob/d6bcac63908201c3c8dc9eb17e62e3a935173f58/INSTALL.md#L12)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is not so strict a requirement. Please see the idea below.
</blockquote></details>

Done.

Thanks, you are right.
I noticed it can be turned off by `-DTEST_PYTHON_TOOLS =OFF` but didn't relaized we should add some explanation in the below section.
___
*[INSTALL.md, line 33 at r1](https://reviewable.io/reviews/pmem/rpma/1096#-McxxSm2AjikBYS6pegC:-Md-vAp26Tq-5G6yWbD8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d6bcac63908201c3c8dc9eb17e62e3a935173f58/INSTALL.md#L33)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```md
### In order to test the Python tools you also need:

- pylint

**Note**: testing the Python tools can be turned off using the CMake 'TEST_PYTHON_TOOLS' option
(see [CMake standard options](INSTALL.md#cmake-standard-options) and
[Configuring CMake options](INSTALL.md#configuring-cmake-options)).
```
</blockquote></details>

Done.
___
*[INSTALL.md, line 69 at r1](https://reviewable.io/reviews/pmem/rpma/1096#-McxyMs8BlSkhVrHwg3Y:-Md-vBpB1toQ03XxAjaz:b-fzzwgw) ([raw file](https://github.com/pmem/rpma/blob/d6bcac63908201c3c8dc9eb17e62e3a935173f58/INSTALL.md#L69)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```md
| TEST_PYTHON_TOOLS | Enable testing Python tools | ON/OFF | ON |
```
</blockquote></details>

Done.

I add `TEST_PYTHON_TOOLS ` after `TEST_DIR` because it is named with the prefix `TEST_`.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 25 of 25 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1096#-:-Md0xlpq4iK3dvQc_p1L:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1096)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1096#-Md0xp63AltsE0cOgRkK:-Md0xp63AltsE0cOgRkL:b-hmtsba) (no related file):*
@osalyk @ldorau please return to this review.

---

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1096#-:-Md1DlGs4W7ZcT8D69Eg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 25 of 25 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1096#-:-Md1Jbb5-zBv0RUemyMb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1096#-Md0xp63AltsE0cOgRkK:-Md1JikBEPv1PoE6n9J1:bnfp4nl) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

@osalyk @ldorau please return to this review.
</blockquote></details>

:lgtm:

---

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1096)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Pull request merged**
