### PR TITLE
doc: perf-tuning-latency stub

### PR DESCRIPTION
**Pull request by janekmi**
Preview: https://janekmi.github.io/rpma/

This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/594)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/594)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[index.md, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/594#-MMUjrf0EkCcMZ0eMey6:-MMUjrf0EkCcMZ0eMey7:b-uin5i9) ([raw file](https://github.com/pmem/rpma/blob/b9ff15c8cb255071d1b33451d898b820bccf6363/index.md#L17)):*
> ```
>  list
> ```

`list`? Hmm, maybe `Documents recommended for reading:` ?

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/594)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[documentation/perf-tuning-latency.md, line 8 at r1](https://reviewable.io/reviews/pmem/rpma/594#-MMUn22GEWn1k9qkOSJC:-MMUn22H2MFWVJlwEWgF:bwj952i) ([raw file](https://github.com/pmem/rpma/blob/b9ff15c8cb255071d1b33451d898b820bccf6363/documentation/perf-tuning-latency.md#L8)):*
> ```
> practices, and
> ```

`practices and` - no comma
___
*[documentation/perf-tuning-latency.md, line 8 at r1](https://reviewable.io/reviews/pmem/rpma/594#-MMUn88h97TQ1bw9uazs:-MMUn88i9vyfUpk-H5Qh:bhlzn4i) ([raw file](https://github.com/pmem/rpma/blob/b9ff15c8cb255071d1b33451d898b820bccf6363/documentation/perf-tuning-latency.md#L8)):*
> ```
> of best methods
> ```

`of the best methods`
___
*[documentation/perf-tuning-latency.md, line 8 at r1](https://reviewable.io/reviews/pmem/rpma/594#-MMUnIFhAQZcQ1k1IpcG:-MMUnIFhAQZcQ1k1IpcH:bwp6qaf) ([raw file](https://github.com/pmem/rpma/blob/b9ff15c8cb255071d1b33451d898b820bccf6363/documentation/perf-tuning-latency.md#L8)):*
> ```
> build
> ```

`built`

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/594)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi)

___
*[documentation/perf-tuning-latency.md, line 14 at r1](https://reviewable.io/reviews/pmem/rpma/594#-MMUz8cK2bKqFYxEosmf:-MMUz8cL4KjQTZoq9MOy:b7mehc8) ([raw file](https://github.com/pmem/rpma/blob/b9ff15c8cb255071d1b33451d898b820bccf6363/documentation/perf-tuning-latency.md#L14)):*
> ```
> the workloads build
> ```

What is "`the workloads build`" ?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/594)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi)

___
*[documentation/perf-tuning-latency.md, line 14 at r1](https://reviewable.io/reviews/pmem/rpma/594#-MMV2V7CEcv-MMmq76fQ:-MMV2V7CEcv-MMmq76fR:b-xmw9zx) ([raw file](https://github.com/pmem/rpma/blob/b9ff15c8cb255071d1b33451d898b820bccf6363/documentation/perf-tuning-latency.md#L14)):*
> ```
> each configuration change
> ```

`each change of configuration` sounds better IMHO
___
*[documentation/perf-tuning-latency.md, line 14 at r1](https://reviewable.io/reviews/pmem/rpma/594#-MMUz8cK2bKqFYxEosmf:-MMV2qgR2dJE0Mnx83zN:bnvwcqd) ([raw file](https://github.com/pmem/rpma/blob/b9ff15c8cb255071d1b33451d898b820bccf6363/documentation/perf-tuning-latency.md#L14)):*
> ```
> the workloads build based o
> ```

built or based ?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/594)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[index.md, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/594#-MMUjrf0EkCcMZ0eMey6:-MMV6TM6D1EhvlXXxZs3:b5nim0j) ([raw file](https://github.com/pmem/rpma/blob/b9ff15c8cb255071d1b33451d898b820bccf6363/index.md#L17)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  list
> ```

`list`? Hmm, maybe `Documents recommended for reading:` ?
</blockquote></details>

I like mine more. xD
___
*[documentation/perf-tuning-latency.md, line 8 at r1](https://reviewable.io/reviews/pmem/rpma/594#-MMUn22GEWn1k9qkOSJC:-MMV6yoM-HFaw3QzeeEC:bfuv5ry) ([raw file](https://github.com/pmem/rpma/blob/b9ff15c8cb255071d1b33451d898b820bccf6363/documentation/perf-tuning-latency.md#L8)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> practices, and
> ```

`practices and` - no comma
</blockquote></details>

FYI https://www.grammarly.com/blog/comma-before-and/
___
*[documentation/perf-tuning-latency.md, line 8 at r1](https://reviewable.io/reviews/pmem/rpma/594#-MMUn88h97TQ1bw9uazs:-MMV7etC9vtj-upfMh5c:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b9ff15c8cb255071d1b33451d898b820bccf6363/documentation/perf-tuning-latency.md#L8)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> of best methods
> ```

`of the best methods`
</blockquote></details>

Done.
___
*[documentation/perf-tuning-latency.md, line 8 at r1](https://reviewable.io/reviews/pmem/rpma/594#-MMUnIFhAQZcQ1k1IpcG:-MMV8CUY6lJtY01pVoi4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b9ff15c8cb255071d1b33451d898b820bccf6363/documentation/perf-tuning-latency.md#L8)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> build
> ```

`built`

</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/594)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/594#-:-MMVAFylCDZZ1YbjAto0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/594#-:-MMVEh4K5RWRHhceKxu2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
