### PR TITLE
Update all examples to use new APIs

### PR DESCRIPTION
**Pull request by yangx-jy**
Ref: #1212

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1271)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1271#-:-Mj8vJ5G5fvdNFZO6syA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1271)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by ldorau — COMMENTED** [review]
> Reviewed 8 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1271)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 4 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1271)* status: all files reviewed, 3 unresolved discussions (waiting on @yangx-jy)

___
*[examples/06-multiple-connections/server.c, line 153 at r1](https://reviewable.io/reviews/pmem/rpma/1271#-MjDnal40b4btWKHjjjn:-MjDnal58f4ZK7XnUPSC:brcfqrw) ([raw file](https://github.com/pmem/rpma/blob/d042f72d478685ccaba4ffe033ebfc77e719530d/examples/06-multiple-connections/server.c#L153)):*
> ```
> /* get the connection's completion fd and add it to epoll */
> ```

This comment should be moved before `rpma_cq_get_fd(cq, &fd);` and a new one should be added here.
___
*[examples/06-multiple-connections/server.c, line 216 at r1](https://reviewable.io/reviews/pmem/rpma/1271#-MjDoMpb7z4TGiQYVd_T:-MjDoMpb7z4TGiQYVd_U:b-7hibl3) ([raw file](https://github.com/pmem/rpma/blob/d042f72d478685ccaba4ffe033ebfc77e719530d/examples/06-multiple-connections/server.c#L216)):*
> ```
> /* prepare detected completions for processing */
> ```

wrong comment
___
*[examples/06-multiple-connections/server.c, line 220 at r1](https://reviewable.io/reviews/pmem/rpma/1271#-MjDoPDg5q1Ax_7NfMQI:-MjDoPDg5q1Ax_7NfMQJ:bs1acb6) ([raw file](https://github.com/pmem/rpma/blob/d042f72d478685ccaba4ffe033ebfc77e719530d/examples/06-multiple-connections/server.c#L220)):*
> ```
> /* another error occurred - disconnect */
> ```

.

**Review by yangx-jy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1271)* status: 11 of 12 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[examples/06-multiple-connections/server.c, line 153 at r1](https://reviewable.io/reviews/pmem/rpma/1271#-MjDnal40b4btWKHjjjn:-MjEDj3iEYMoojGPc2IY:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d042f72d478685ccaba4ffe033ebfc77e719530d/examples/06-multiple-connections/server.c#L153)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> /* get the connection's completion fd and add it to epoll */
> ```

This comment should be moved before `rpma_cq_get_fd(cq, &fd);` and a new one should be added here.
</blockquote></details>

Done.
___
*[examples/06-multiple-connections/server.c, line 216 at r1](https://reviewable.io/reviews/pmem/rpma/1271#-MjDoMpb7z4TGiQYVd_T:-MjEDkbg9f-Ox1AtR7mq:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d042f72d478685ccaba4ffe033ebfc77e719530d/examples/06-multiple-connections/server.c#L216)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> /* prepare detected completions for processing */
> ```

wrong comment
</blockquote></details>

Done.
___
*[examples/06-multiple-connections/server.c, line 220 at r1](https://reviewable.io/reviews/pmem/rpma/1271#-MjDoPDg5q1Ax_7NfMQI:-MjEDmAn4Rzpl-Ev_uPP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d042f72d478685ccaba4ffe033ebfc77e719530d/examples/06-multiple-connections/server.c#L220)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> /* another error occurred - disconnect */
> ```

.

</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1271#-:-MjERG3P2jyFdfxYPxjK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1271)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by yangx-jy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1271)* status: 11 of 12 files reviewed, 2 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[examples/06-multiple-connections/server.c, line 401 at r2](https://reviewable.io/reviews/pmem/rpma/1271#-Mjo-Px46rwnRmSrmO6O:-Mjs490x5rvTFkO9p3S-:b-fjapn9) ([raw file](https://github.com/pmem/rpma/blob/d569a2db9dfd557179f4c7e7548f7232580e09ce/examples/06-multiple-connections/server.c#L401)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think you can add this part here:

```c
	/* get the connection's main CQ */
	struct rpma_cq *cq = NULL;
	int ret = rpma_conn_get_cq(clnt->conn, &clnt->cq);
	if (ret) {
		/* an error occurred - disconnect */
		(void) rpma_conn_disconnect(clnt->conn);
		return;
	}
```

so, you don't need to call `_get_cq()` over and over again.

**NOTE**: You have to extend the `struct client_res` structure to accommodate also the `cq`.
</blockquote></details>

Done.  Good suggestion. ^_^
___
*[examples/08-messages-ping-pong/client.c, line 131 at r2](https://reviewable.io/reviews/pmem/rpma/1271#-Mjnxo4835ati22TCMtb:-Mjs4F1jDZwlAAwpxMbl:bpycwng) ([raw file](https://github.com/pmem/rpma/blob/d569a2db9dfd557179f4c7e7548f7232580e09ce/examples/08-messages-ping-pong/client.c#L131)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Won't it fit into a single line?
</blockquote></details>

Yes, `make cstyle` will show `line > 80 characters` when it is changed to a single line.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1271)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1271)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1271#-:-MkutLf98mSYTOnv8oR4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1271)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Pull request merged**
