### PR TITLE
doc: document rpma_log_default_func()

### PR DESCRIPTION
**Pull request by osalyk**
Preview https://github.com/pmem/rpma/pull/1923/files?short_path=ea207e6#diff-ea207e67fe0d4bb1af009552a536828a143e75e0689c11647debe197efae06f0

This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1923)

### CODE REVIEW

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1923)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1923)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1923)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1923)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[`THREAD_SAFETY.md` line 118 at r1](https://reviewable.io/reviews/pmem/rpma/1923#-N7L3FAn7ZLz3Hpa7c81:-N7L3FAn7ZLz3Hpa7c82:b-kiex8y) ([raw file](https://github.com/pmem/rpma/blob/b3ee1b8092386d40b1cece4c998fc70c556170e6/THREAD_SAFETY.md#L118)):*
> ```Markdown
> - rpma_utils_get_ibv_context
> 
> ### `rpma_log_default_function()`
> ```

Maybe no backticks here?



_Code quote:_
```Markdown
### `rpma_log_default_function()`
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1923)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[`THREAD_SAFETY.md` line 118 at r1](https://reviewable.io/reviews/pmem/rpma/1923#-N7L3FAn7ZLz3Hpa7c81:-N7LMNliEZYs0CaJkJm1:b-7qbn23) ([raw file](https://github.com/pmem/rpma/blob/b3ee1b8092386d40b1cece4c998fc70c556170e6/THREAD_SAFETY.md#L118)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Maybe no backticks here?
</blockquote></details>

(in a header)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1923)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[`THREAD_SAFETY.md` line 118 at r1](https://reviewable.io/reviews/pmem/rpma/1923#-N7L3FAn7ZLz3Hpa7c81:-N7ZkUN1E0oSGzIn5y_K:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b3ee1b8092386d40b1cece4c998fc70c556170e6/THREAD_SAFETY.md#L118)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

(in a header)
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1923)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[`THREAD_SAFETY.md` line 83 at r2](https://reviewable.io/reviews/pmem/rpma/1923#-N7oEMuT6blqqeoBfD1w:-N7oEMuT6blqqeoBfD1x:b-gtyqiy) ([raw file](https://github.com/pmem/rpma/blob/f830ed8fc7d73a75f8559ba331fd1acea4b28cfd/THREAD_SAFETY.md#L83)):*
> ```Markdown
> ## Conditionally thread-safe API calls
> 
> **Note**: Thread safety of the following functions' depends on the support of atomic on the specific OS. If it is supported then they are all thread-safe (except rpma_conn_req_connect).
> ```

functions



_Code quote:_
```Markdown
functions'
```
___
*[`THREAD_SAFETY.md` line 83 at r2](https://reviewable.io/reviews/pmem/rpma/1923#-N7oEPCl-Zmg1CWS2DAe:-N7oEPCl-Zmg1CWS2DAf:b-4q2963) ([raw file](https://github.com/pmem/rpma/blob/f830ed8fc7d73a75f8559ba331fd1acea4b28cfd/THREAD_SAFETY.md#L83)):*
> ```Markdown
> ## Conditionally thread-safe API calls
> 
> **Note**: Thread safety of the following functions' depends on the support of atomic on the specific OS. If it is supported then they are all thread-safe (except rpma_conn_req_connect).
> ```

atomic operations (`atomic_store` and `atomic_load`)



_Code quote:_
```Markdown
atomic
```
___
*[`THREAD_SAFETY.md` line 83 at r2](https://reviewable.io/reviews/pmem/rpma/1923#-N7oEsot5xjur39yShWx:-N7oEsot5xjur39yShWy:b-ffraxt) ([raw file](https://github.com/pmem/rpma/blob/f830ed8fc7d73a75f8559ba331fd1acea4b28cfd/THREAD_SAFETY.md#L83)):*
> ```Markdown
> ## Conditionally thread-safe API calls
> 
> **Note**: Thread safety of the following functions' depends on the support of atomic on the specific OS. If it is supported then they are all thread-safe (except rpma_conn_req_connect).
> ```

`all (except of rpma_conn_req_connect) thread-safe.`

Why `rpma_conn_req_connect` ? It is not listed here ...



_Code quote:_
```Markdown
all thread-safe (except rpma_conn_req_connect).
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1923)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[`THREAD_SAFETY.md` line 83 at r2](https://reviewable.io/reviews/pmem/rpma/1923#-N7oEMuT6blqqeoBfD1w:-N7oRr6AABH-DwO4Dcdj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f830ed8fc7d73a75f8559ba331fd1acea4b28cfd/THREAD_SAFETY.md#L83)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

functions
</blockquote></details>

Done.
___
*[`THREAD_SAFETY.md` line 83 at r2](https://reviewable.io/reviews/pmem/rpma/1923#-N7oEPCl-Zmg1CWS2DAe:-N7oRxLBABKnrYHKSAkb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f830ed8fc7d73a75f8559ba331fd1acea4b28cfd/THREAD_SAFETY.md#L83)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

atomic operations (`atomic_store` and `atomic_load`)
</blockquote></details>

Done.
___
*[`THREAD_SAFETY.md` line 83 at r2](https://reviewable.io/reviews/pmem/rpma/1923#-N7oEsot5xjur39yShWx:-N7oSAvQ9woUveGv2Pvf:b-p8ytir) ([raw file](https://github.com/pmem/rpma/blob/f830ed8fc7d73a75f8559ba331fd1acea4b28cfd/THREAD_SAFETY.md#L83)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`all (except of rpma_conn_req_connect) thread-safe.`

Why `rpma_conn_req_connect` ? It is not listed here ...
</blockquote></details>

There it is, in line 110

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1923)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1923)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[`THREAD_SAFETY.md` line 83 at r2](https://reviewable.io/reviews/pmem/rpma/1923#-N7oEsot5xjur39yShWx:-N7tmtL_Cn9jwEDtEH3h:b-ndps15) ([raw file](https://github.com/pmem/rpma/blob/f830ed8fc7d73a75f8559ba331fd1acea4b28cfd/THREAD_SAFETY.md#L83)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

There it is, in line 110
</blockquote></details>

I would leave it as it was, it sounds more native I think, I mean 'all thread-safe (except rpma_conn_req_connect)'
___
*[`THREAD_SAFETY.md` line 132 at r3](https://reviewable.io/reviews/pmem/rpma/1923#-N7p6asICJgPamTH8z8p:-N7p6asJ-S35ksFwqdeS:bqoskme) ([raw file](https://github.com/pmem/rpma/blob/3cc8069ea34d0ada0f1544b258f3c22785c175b7/THREAD_SAFETY.md#L132)):*
> ```Markdown
> - when establishing connections *LOG_LEVEL_NOTICE*
> 
> In the first case, when we set *LOG_LEVEL_WARNING/ERROR* the function will be called only in error situations. So there is no risk to normal operation.
> ```

to a normal



_Code quote:_
```Markdown
to normal
```
___
*[`THREAD_SAFETY.md` line 136 at r3](https://reviewable.io/reviews/pmem/rpma/1923#-N7tnD0T2Zo3C-AFW8KC:-N7tnD0U1PCKKAHNJXHI:bji9y0t) ([raw file](https://github.com/pmem/rpma/blob/3cc8069ea34d0ada0f1544b258f3c22785c175b7/THREAD_SAFETY.md#L136)):*
> ```Markdown
> In the second case, we call the function in functions that are marked as not thread-safe.
> 
> The `rpma_log_default_function()` function is NOT thread-safe because it uses the [localtime_r(3)](https://www.gnu.org/software/libc/manual/html_node/Broken_002ddown-Time.html#index-localtime_005fr) and [syslog(3)](https://www.gnu.org/software/libc/manual/html_node/syslog_003b-vsyslog.html#index-syslog) functions which are labeled as **MT-Safe env locale**.
> ```

and the 



_Code quote:_
```Markdown
and
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1923)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[`THREAD_SAFETY.md` line 83 at r2](https://reviewable.io/reviews/pmem/rpma/1923#-N7oEsot5xjur39yShWx:-N7tqCh734spS2yAhXVj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f830ed8fc7d73a75f8559ba331fd1acea4b28cfd/THREAD_SAFETY.md#L83)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

I would leave it as it was, it sounds more native I think, I mean 'all thread-safe (except rpma_conn_req_connect)'
</blockquote></details>

Done.
___
*[`THREAD_SAFETY.md` line 132 at r3](https://reviewable.io/reviews/pmem/rpma/1923#-N7p6asICJgPamTH8z8p:-N7tqHFF0Nh16Ez-Svca:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3cc8069ea34d0ada0f1544b258f3c22785c175b7/THREAD_SAFETY.md#L132)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

to a normal
</blockquote></details>

Done.
___
*[`THREAD_SAFETY.md` line 136 at r3](https://reviewable.io/reviews/pmem/rpma/1923#-N7tnD0T2Zo3C-AFW8KC:-N7tqad29qWyN-vBLvNR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3cc8069ea34d0ada0f1544b258f3c22785c175b7/THREAD_SAFETY.md#L136)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

and the 
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1923)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi and @osalyk)

___
*[`THREAD_SAFETY.md` line 83 at r4](https://reviewable.io/reviews/pmem/rpma/1923#-N7uIAAHBNYXIwZabDJI:-N7uIAAHBNYXIwZabDJJ:bee5bre) ([raw file](https://github.com/pmem/rpma/blob/7651b8cfac747944cfdb4e534cf8941b73bfc625/THREAD_SAFETY.md#L83)):*
> ```Markdown
> ## Conditionally thread-safe API calls
> 
> **Note**: Thread safety of the following functions depends on the support of atomic operations (`atomic_store` and `atomic_load`) on the specific OS. If it is supported then they are all thread-safe (except rpma_conn_req_connect).
> ```

@haichangsi maybe `they all are thread-safe`?



_Code quote:_
```Markdown
they are all thread-safe
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1923)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[`THREAD_SAFETY.md` line 83 at r4](https://reviewable.io/reviews/pmem/rpma/1923#-N7uIAAHBNYXIwZabDJI:-N7uNGJ_0uRSGV8b-vAp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7651b8cfac747944cfdb4e534cf8941b73bfc625/THREAD_SAFETY.md#L83)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@haichangsi maybe `they all are thread-safe`?
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1923)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1923)* status: all files reviewed, 6 unresolved discussions (waiting on @haichangsi and @osalyk)

___
*[`THREAD_SAFETY.md` line 129 at r5](https://reviewable.io/reviews/pmem/rpma/1923#-N7uYdH29vzDdmTmjmoA:-N7uYdH29vzDdmTmjmoB:bv830hn) ([raw file](https://github.com/pmem/rpma/blob/02a3e7874dc5a7a6d3795c470522f241e12be74a/THREAD_SAFETY.md#L129)):*
> ```Markdown
> 
> The `rpma_log_default_function()` function is used throughout the API:
> - at the stage of detecting errors and warnings *LOG_LEVEL_WARNING/ERROR*
> ```

when logging errors and warnings (with the *LOG_LEVEL_ERROR* or *LOG_LEVEL_WARNING* log levels)



_Code quote:_
```Markdown
at the stage of detecting errors and warnings *LOG_LEVEL_WARNING/ERROR*
```
___
*[`THREAD_SAFETY.md` line 130 at r5](https://reviewable.io/reviews/pmem/rpma/1923#-N7uZ3Sq2_OsyokdPVVS:-N7uZ3Sq2_OsyokdPVVT:b-fb6g4e) ([raw file](https://github.com/pmem/rpma/blob/02a3e7874dc5a7a6d3795c470522f241e12be74a/THREAD_SAFETY.md#L130)):*
> ```Markdown
> The `rpma_log_default_function()` function is used throughout the API:
> - at the stage of detecting errors and warnings *LOG_LEVEL_WARNING/ERROR*
> - when establishing connections *LOG_LEVEL_NOTICE*
> ```

... a connection (with the *LOG_LEVEL_NOTICE* log level)



_Code quote:_
```Markdown
connections *LOG_LEVEL_NOTICE*
```
___
*[`THREAD_SAFETY.md` line 132 at r5](https://reviewable.io/reviews/pmem/rpma/1923#-N7uZHmBALlhB_nYJDEZ:-N7uZHmBALlhB_nYJDE_:bgg8pg7) ([raw file](https://github.com/pmem/rpma/blob/02a3e7874dc5a7a6d3795c470522f241e12be74a/THREAD_SAFETY.md#L132)):*
> ```Markdown
> - when establishing connections *LOG_LEVEL_NOTICE*
> 
> In the first case, when we set *LOG_LEVEL_WARNING/ERROR* the function will be called only in error situations. So there is no risk to a normal operation.
> ```

In the first case, the function is called only in error handling paths, so there is no risk to a normal operation.



_Code quote:_
```Markdown
In the first case, when we set *LOG_LEVEL_WARNING/ERROR* the function will be called only in error situations. So there is no risk to a normal operation.
```
___
*[`THREAD_SAFETY.md` line 134 at r5](https://reviewable.io/reviews/pmem/rpma/1923#-N7uZxI22zKzEUMWE2Jo:-N7uZxI22zKzEUMWE2Jp:bkyxadd) ([raw file](https://github.com/pmem/rpma/blob/02a3e7874dc5a7a6d3795c470522f241e12be74a/THREAD_SAFETY.md#L134)):*
> ```Markdown
> In the first case, when we set *LOG_LEVEL_WARNING/ERROR* the function will be called only in error situations. So there is no risk to a normal operation.
> 
> In the second case, we call the function in functions that are marked as not thread-safe.
> ```

In the second case, it is called in functions that are marked as not thread-safe.



_Code quote:_
```Markdown
In the second case, we call the function in functions that are marked as not thread-safe.
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1923)* status: all files reviewed, 8 unresolved discussions (waiting on @haichangsi and @osalyk)

___
*[`THREAD_SAFETY.md` line 83 at r5](https://reviewable.io/reviews/pmem/rpma/1923#-N7u__2EE9yTnpddghCc:-N7u__2EE9yTnpddghCd:b4q6n12) ([raw file](https://github.com/pmem/rpma/blob/02a3e7874dc5a7a6d3795c470522f241e12be74a/THREAD_SAFETY.md#L83)):*
> ```Markdown
> ## Conditionally thread-safe API calls
> 
> **Note**: Thread safety of the following functions depends on the support of atomic operations (`atomic_store` and `atomic_load`) on the specific OS. If it is supported then they all are thread-safe (except rpma_conn_req_connect).
> ```

If they are supported ...



_Code quote:_
```Markdown
If it is supported
```
___
*[`THREAD_SAFETY.md` line 83 at r5](https://reviewable.io/reviews/pmem/rpma/1923#-N7u_l8UAA7WjXkOPsOO:-N7u_l8UAA7WjXkOPsOP:bi40zn6) ([raw file](https://github.com/pmem/rpma/blob/02a3e7874dc5a7a6d3795c470522f241e12be74a/THREAD_SAFETY.md#L83)):*
> ```Markdown
> ## Conditionally thread-safe API calls
> 
> **Note**: Thread safety of the following functions depends on the support of atomic operations (`atomic_store` and `atomic_load`) on the specific OS. If it is supported then they all are thread-safe (except rpma_conn_req_connect).
> ```

then all the following functions are thread-safe ...



_Code quote:_
```Markdown
then they all are thread-safe
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1923)* status: all files reviewed, 8 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[`THREAD_SAFETY.md` line 83 at r5](https://reviewable.io/reviews/pmem/rpma/1923#-N7u__2EE9yTnpddghCc:-N7ujFdWC64UlVCVEQVJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/02a3e7874dc5a7a6d3795c470522f241e12be74a/THREAD_SAFETY.md#L83)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

If they are supported ...
</blockquote></details>

Done.
___
*[`THREAD_SAFETY.md` line 83 at r5](https://reviewable.io/reviews/pmem/rpma/1923#-N7u_l8UAA7WjXkOPsOO:-N7ujKmB0dhZ4XFbZgCi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/02a3e7874dc5a7a6d3795c470522f241e12be74a/THREAD_SAFETY.md#L83)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

then all the following functions are thread-safe ...
</blockquote></details>

Done.
___
*[`THREAD_SAFETY.md` line 129 at r5](https://reviewable.io/reviews/pmem/rpma/1923#-N7uYdH29vzDdmTmjmoA:-N7ujUNF9fkzHaucJHED:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/02a3e7874dc5a7a6d3795c470522f241e12be74a/THREAD_SAFETY.md#L129)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

when logging errors and warnings (with the *LOG_LEVEL_ERROR* or *LOG_LEVEL_WARNING* log levels)
</blockquote></details>

Done.
___
*[`THREAD_SAFETY.md` line 130 at r5](https://reviewable.io/reviews/pmem/rpma/1923#-N7uZ3Sq2_OsyokdPVVS:-N7uj_kX9kwUOzBmAOq_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/02a3e7874dc5a7a6d3795c470522f241e12be74a/THREAD_SAFETY.md#L130)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

... a connection (with the *LOG_LEVEL_NOTICE* log level)
</blockquote></details>

Done.
___
*[`THREAD_SAFETY.md` line 132 at r5](https://reviewable.io/reviews/pmem/rpma/1923#-N7uZHmBALlhB_nYJDEZ:-N7ujj0t3pDwo0rArjhQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/02a3e7874dc5a7a6d3795c470522f241e12be74a/THREAD_SAFETY.md#L132)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

In the first case, the function is called only in error handling paths, so there is no risk to a normal operation.
</blockquote></details>

Done.
___
*[`THREAD_SAFETY.md` line 134 at r5](https://reviewable.io/reviews/pmem/rpma/1923#-N7uZxI22zKzEUMWE2Jo:-N7ujm1s6zLeise4OBEB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/02a3e7874dc5a7a6d3795c470522f241e12be74a/THREAD_SAFETY.md#L134)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

In the second case, it is called in functions that are marked as not thread-safe.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1923)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1923#-:-N7ukaSO0eSz8WVjWeyk:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

**Review by Patryk717 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1923#-:-N7yLgy9EU1tmNN_PSeH:bdycpsm)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1923)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

**Pull request merged**
