### PR TITLE
examples: remove redundant src from Cmakelist example09

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1926)

### CODE REVIEW

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1926)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1926)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1926#-N7P7vo80KX3PWuuFH_5):*
examples: remove redundant source file from CMakeList in example09



_Code quote:_
```
examples: remove redundant src from Cmakelist example09
```

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1926#-:-N7PMaUp0gI7RlXH6cr6:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1926)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ldorau)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1926#-N7P7vo80KX3PWuuFH_5):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

examples: remove redundant source file from CMakeList in example09
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1926)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
