### PR TITLE
tools: improving information on latency measurements

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/650)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/650)* status: all files reviewed, 5 unresolved discussions (waiting on @osalyk)

___
*[tools/BENCHMARKING.md, line 9 at r1](https://reviewable.io/reviews/pmem/rpma/650#-MO6vGbKAufXNCou_1Zm:-MO6vGbKAufXNCou_1Zn:b-8u861w) ([raw file](https://github.com/pmem/rpma/blob/1a62155d310aa26f4ccff9cd4dc8d644d76edb87/tools/BENCHMARKING.md#L9)):*
> ```Markdown
> ## Requirements
> 
> To use these tools, you must have several components installed:
> ```

... installed in your system:
___
*[tools/BENCHMARKING.md, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/650#-MO6w3IFCmBD5ePtUs_v:-MO6w3IFCmBD5ePtUs_w:bumxjzq) ([raw file](https://github.com/pmem/rpma/blob/1a62155d310aa26f4ccff9cd4dc8d644d76edb87/tools/BENCHMARKING.md#L13)):*
> ```Markdown
>  - python3-pip
>  - python-pandas
>  - python-matplotlib
> ```

Since we are installing pandas and matplotlib as python packages (no via any Linux package manager) I think it makes more sense to name it as pandas and matplotlib without `python-` prefix.
___
*[tools/BENCHMARKING.md, line 23 at r1](https://reviewable.io/reviews/pmem/rpma/650#-MO6x-tB7ZsS2vMXAxIK:-MO6x-tB7ZsS2vMXAxIL:b-c7khk9) ([raw file](https://github.com/pmem/rpma/blob/1a62155d310aa26f4ccff9cd4dc8d644d76edb87/tools/BENCHMARKING.md#L23)):*
> ```Markdown
> ## Comparing the RPMA read with the baseline
> 
> The scripts must be run on the client side.
> ```

Since it is a general rule, I think you can take this line to the requirements section and make it a note e.g.:

```
*Note*: All of the scripts presented in following sections must be run on the client-side.
```
___
*[tools/BENCHMARKING.md, line 64 at r1](https://reviewable.io/reviews/pmem/rpma/650#-MO6xX8jC9kNdN0xYmjL:-MO6xX8jC9kNdN0xYmjM:b-batl95) ([raw file](https://github.com/pmem/rpma/blob/1a62155d310aa26f4ccff9cd4dc8d644d76edb87/tools/BENCHMARKING.md#L64)):*
> ```Markdown
> 
> ```sh
> $ python3 csv_compare.py --output_layout lat file-1.csv [... file-n.csv]
> ```

python3 is redundant here. You can simply do:

```sh
$ ./csv_compare.py # ...
```
___
*[tools/BENCHMARKING.md, line 68 at r1](https://reviewable.io/reviews/pmem/rpma/650#-MO6xyj352mb8P0skM8u:-MO6xyj352mb8P0skM8v:bvarbbv) ([raw file](https://github.com/pmem/rpma/blob/1a62155d310aa26f4ccff9cd4dc8d644d76edb87/tools/BENCHMARKING.md#L68)):*
> ```Markdown
> ```
> Optional arguments:
>  - -h, --help - show this help message and exit
> ```

I think we do not want to copy here the complete help message from the tool.
I would:
- remove the help reference overall
- use some of the options in the example above
- here only describe some not obvious functions of the options used in the example.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/650)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tools/BENCHMARKING.md, line 23 at r1](https://reviewable.io/reviews/pmem/rpma/650#-MO6x-tB7ZsS2vMXAxIK:-MO6zk34Cv3sgMVSax18:bnuf6lw) ([raw file](https://github.com/pmem/rpma/blob/1a62155d310aa26f4ccff9cd4dc8d644d76edb87/tools/BENCHMARKING.md#L23)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Since it is a general rule, I think you can take this line to the requirements section and make it a note e.g.:

```
*Note*: All of the scripts presented in following sections must be run on the client-side.
```
</blockquote></details>

`in the following sections`

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/650)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/BENCHMARKING.md, line 9 at r1](https://reviewable.io/reviews/pmem/rpma/650#-MO6vGbKAufXNCou_1Zm:-MO7-5UW2txM5KuIGxoO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1a62155d310aa26f4ccff9cd4dc8d644d76edb87/tools/BENCHMARKING.md#L9)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

... installed in your system:
</blockquote></details>

Done.
___
*[tools/BENCHMARKING.md, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/650#-MO6w3IFCmBD5ePtUs_v:-MO7-BF4ETP5CFMuEVxf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1a62155d310aa26f4ccff9cd4dc8d644d76edb87/tools/BENCHMARKING.md#L13)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Since we are installing pandas and matplotlib as python packages (no via any Linux package manager) I think it makes more sense to name it as pandas and matplotlib without `python-` prefix.
</blockquote></details>

Done.
___
*[tools/BENCHMARKING.md, line 23 at r1](https://reviewable.io/reviews/pmem/rpma/650#-MO6x-tB7ZsS2vMXAxIK:-MO730ptD0vNrt34ATJB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1a62155d310aa26f4ccff9cd4dc8d644d76edb87/tools/BENCHMARKING.md#L23)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`in the following sections`
</blockquote></details>

Done.
___
*[tools/BENCHMARKING.md, line 64 at r1](https://reviewable.io/reviews/pmem/rpma/650#-MO6xX8jC9kNdN0xYmjL:-MO7-TzbC3KaAhtZNQyT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1a62155d310aa26f4ccff9cd4dc8d644d76edb87/tools/BENCHMARKING.md#L64)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

python3 is redundant here. You can simply do:

```sh
$ ./csv_compare.py # ...
```
</blockquote></details>

Done.
___
*[tools/BENCHMARKING.md, line 68 at r1](https://reviewable.io/reviews/pmem/rpma/650#-MO6xyj352mb8P0skM8u:-MO72uVY1nuK9PEykwqn:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1a62155d310aa26f4ccff9cd4dc8d644d76edb87/tools/BENCHMARKING.md#L68)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we do not want to copy here the complete help message from the tool.
I would:
- remove the help reference overall
- use some of the options in the example above
- here only describe some not obvious functions of the options used in the example.
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/650)* status: all files reviewed, 7 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tools/BENCHMARKING.md, line 21 at r2](https://reviewable.io/reviews/pmem/rpma/650#-MO7DFxM4Lm89gk0r3d-:-MO7DFxM4Lm89gk0r3d0:bfvy65u) ([raw file](https://github.com/pmem/rpma/blob/ab62a9c22fc912070d9f54abd788fc841e0a1784/tools/BENCHMARKING.md#L21)):*
> ```
> the client-side
> ```

the client side (no dash)
___
*[tools/BENCHMARKING.md, line 61 at r2](https://reviewable.io/reviews/pmem/rpma/650#-MO7DO6F7qElitup2t7N:-MO7DO6F7qElitup2t7O:b-n9ll0w) ([raw file](https://github.com/pmem/rpma/blob/ab62a9c22fc912070d9f54abd788fc841e0a1784/tools/BENCHMARKING.md#L61)):*
> ```
> using `csv_compare.py` tool
> ```

using THE `csv_compare.py` tool

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/650)* status: all files reviewed, 7 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/BENCHMARKING.md, line 21 at r2](https://reviewable.io/reviews/pmem/rpma/650#-MO7DFxM4Lm89gk0r3d-:-MO7E4OH2ne4sS3wYz5c:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ab62a9c22fc912070d9f54abd788fc841e0a1784/tools/BENCHMARKING.md#L21)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> the client-side
> ```

the client side (no dash)
</blockquote></details>

Done.
___
*[tools/BENCHMARKING.md, line 61 at r2](https://reviewable.io/reviews/pmem/rpma/650#-MO7DO6F7qElitup2t7N:-MO7EC7K8QLD91J9FpYU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ab62a9c22fc912070d9f54abd788fc841e0a1784/tools/BENCHMARKING.md#L61)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> using `csv_compare.py` tool
> ```

using THE `csv_compare.py` tool
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/650)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/650#-:-MO7H2Zu0xb9ig6mI5uW:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/650#-:-MO7lDV8AjYfKGoFotno:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
