### PR TITLE
doc: check if src2man, find and diff are installed

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #379

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/390)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/390)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[doc/CMakeLists.txt, line 16 at r1](https://reviewable.io/reviews/pmem/rpma/390#-MH0p8cQ4WywXy8N-OQc:-MH0p8cQ4WywXy8N-OQd:b-uhv1hs) ([raw file](https://github.com/pmem/rpma/blob/e27964abd4902a80c20e2b6f8d566660e48817f5/doc/CMakeLists.txt#L16)):*
> ```CMake
> endif()
> 
> if(SRC2MAN AND GROFF)
> ```

`AND FIND AND DIFF`?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/390)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[doc/CMakeLists.txt, line 16 at r1](https://reviewable.io/reviews/pmem/rpma/390#-MH0p8cQ4WywXy8N-OQc:-MHAFFxxBQkcEQbsBrTQ:b71umsl) ([raw file](https://github.com/pmem/rpma/blob/e27964abd4902a80c20e2b6f8d566660e48817f5/doc/CMakeLists.txt#L16)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`AND FIND AND DIFF`?
</blockquote></details>

Of course... I had already fixed that, but apparently I had pushed out an old wrong version ...

**Comment by lukaszstolarczuk** [comment]
you can update the requirements in INSTALL.md (and BTW, you can point that these packages are required only for docs, so user can disable docs' building)

**Comment by ldorau** [comment]
> you can update the requirements in INSTALL.md (and BTW, you can point that these packages are required only for docs, so user can disable docs' building)

Right, added, thanks @lukaszstolarczuk !

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/390)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[INSTALL.md, line 28 at r3](https://reviewable.io/reviews/pmem/rpma/390#-MHO2vH2-DXrJvA2rNn7:-MHO2vH2-DXrJvA2rNn8:b3h755y) ([raw file](https://github.com/pmem/rpma/blob/6462f2ba249226a5cd850500fcb871b99b010b6a/INSTALL.md#L28)):*
> ```Markdown
> to generate the Markdown documentation.
> 
> **Note**: building documentation can be turned off using the CMake 'BUILD_DOC' option
> ```

the documentation

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/390)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[INSTALL.md, line 28 at r3](https://reviewable.io/reviews/pmem/rpma/390#-MHO2vH2-DXrJvA2rNn7:-MHPb7u909d03wmzAs9H:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6462f2ba249226a5cd850500fcb871b99b010b6a/INSTALL.md#L28)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

the documentation
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/390#-:-MHQnv0iDFEc0IDHg2FP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/390#-:-MHQojei-J9bPDzBuAUK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/390)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
