### PR TITLE
exmaples: print out IP of SoftRoCE-configured network interface

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #756 
- [x] #758 

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/747)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/747#-:-MRJs3jCEHg2m7tz850B:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/747)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[examples/config_softroce.sh, line 32 at r1](https://reviewable.io/reviews/pmem/rpma/747#-MRZN5qq0T1YLIUwsflz:-MRZN5qrAfKkTOx6joDv:b-4f1b35) ([raw file](https://github.com/pmem/rpma/blob/c0f23d9258b1e1e63cf39cf88f7c26c7a9785c89/examples/config_softroce.sh#L32)):*
> ```Shell
> 	NETDEV=$(rdma link show | grep -e "$STATE_OK" | head -n1 | cut -d' ' -f8)
> 	IP=$(ip -4 -j -p a show $NETDEV | grep -e local | cut -d'"' -f4)
> 	echo "IP address of the SoftRoCE-configured network interface: $IP"
> ```

The IP address...

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/747)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/747#-MRZNfe5CfHPJ_N0X--J:-MRZNfe5CfHPJ_N0X--K:bxoui26) (no related file):*
```sh
$ ./config_softroce.sh
SoftRoCE has been already configured:
0/1: mlx5_0/1: state ACTIVE physical_state LINK_UP netdev ens785f0
1/1: mlx5_1/1: state ACTIVE physical_state LINK_UP netdev ens785f1
IP address of the SoftRoCE-configured network interface:
```

Am I doing something wrong?

---

**Review by ldorau — COMMENTED** [review]
Requires: #756 and #758 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/747#-:-MRZpvM78Qlp9NgzYqw_:b-hti4j6)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/747#-MRZNfe5CfHPJ_N0X--J:-MRZpudX1jkVo9QVO9OX:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```sh
$ ./config_softroce.sh
SoftRoCE has been already configured:
0/1: mlx5_0/1: state ACTIVE physical_state LINK_UP netdev ens785f0
1/1: mlx5_1/1: state ACTIVE physical_state LINK_UP netdev ens785f1
IP address of the SoftRoCE-configured network interface:
```

Am I doing something wrong?
</blockquote></details>

Done.

---
___
*[examples/config_softroce.sh, line 32 at r1](https://reviewable.io/reviews/pmem/rpma/747#-MRZN5qq0T1YLIUwsflz:-MRZh9kt1TCp124fIFbW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c0f23d9258b1e1e63cf39cf88f7c26c7a9785c89/examples/config_softroce.sh#L32)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The IP address...
</blockquote></details>

Done.

**Comment by ldorau** [comment]
Requires: #756 and #758

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/747)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/747#-MRZNfe5CfHPJ_N0X--J:-MR_1S4o7Q--n1WpnorN:b-512jbl) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

No, it was a bug. Fixed.

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/747)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/747#-MRZNfe5CfHPJ_N0X--J:-MR_9a2D5qX1nd6lYdat:b-8fgz3v) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No, it was a bug. Fixed.
</blockquote></details>

Now:
```
SoftRoCE has been already configured:
0/1: mlx5_0/1: state ACTIVE physical_state LINK_UP netdev ens785f0
1/1: mlx5_1/1: state ACTIVE physical_state LINK_UP netdev ens785f1
The IP addresses of the SoftRoCE-configured network interfaces:
- network interface: ens785f0, no IP address assigned
- network interface: ens785f1, IP address: 192.168.2.7
```

---

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/747)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/747#-:-MRe0PFA5kc5kpiClQG6:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by ldorau — COMMENTED** [review]
Rebased

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/747#-:-MRefWGf-wnYwpTvWbpF:b9x2p3v)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/747#-:-MReg0Y1BmHBFGEbl0qw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
