### PR TITLE
tools: add authors to the preamble

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1178)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1178)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/lib/Report.py, line 23 at r1](https://reviewable.io/reviews/pmem/rpma/1178#-MfmZ7nM7aUhLQ0xnlwa:-MfmZ7nM7aUhLQ0xnlwb:b-bbxchn) ([raw file](https://github.com/pmem/rpma/blob/5646c907454468348a7fe0d31669c24ea2ee41e9/tools/perf/lib/Report.py#L23)):*
> ```Python
>             for author in self.config['report']['authors']:
>                 authors += "\n- " + author
>             self.config['report']['authors'] = authors
> ```

```python
self.config['report']['authors'] = "\n".join(['- ' + author for author in self.config['report']['authors']])
```

Python does not like for-loops. As long as it can be replaced it is easier for him to optimise the execution.
Note: The `for` inside the `join([ /* ... */])` is a list comprehension. Not a for-loop.

Ref: https://djangostars.com/blog/list-comprehensions-and-generator-expressions/

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1178)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/Report.py, line 23 at r1](https://reviewable.io/reviews/pmem/rpma/1178#-MfmZ7nM7aUhLQ0xnlwa:-Mfmb7kREcIcf1Y6WeQL:boyexb3) ([raw file](https://github.com/pmem/rpma/blob/5646c907454468348a7fe0d31669c24ea2ee41e9/tools/perf/lib/Report.py#L23)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```python
self.config['report']['authors'] = "\n".join(['- ' + author for author in self.config['report']['authors']])
```

Python does not like for-loops. As long as it can be replaced it is easier for him to optimise the execution.
Note: The `for` inside the `join([ /* ... */])` is a list comprehension. Not a for-loop.

Ref: https://djangostars.com/blog/list-comprehensions-and-generator-expressions/
</blockquote></details>

Done. Thanks!

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1178#-:-MfmbZ3k2fhOUr-EtgGk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1178#-:-Mfq7zBy9e1yMvFxI7P9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
