### PR TITLE
common: add Ubuntu 22.04 to CI and remove EOLed 21.04

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1787)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
Should we remove 21.04 and 21.10 at the same time?

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1787#-:-N3JUb8S5VUKghl77tR9:bqfy5ju)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1787)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
21.04 is EOL and can be removed, but 21.10 not.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1787#-:-N3JaYNpBesYBf6FXBK6:bizib8s)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1787#-:-N3Jbkqk0NiD7hRH1z79:bb6un1j)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @grom72)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1787#-:-N3Jd2xq8rNY8-dXXijk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
