### PR TITLE
rpma: analysis of thread safety (peer + peer_cfg)

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1756)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1756)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1756#-:-N2w0mVU7xHLp8wTtW_5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1756)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[`THREAD_SAFETY.md` line 8 at r1](https://reviewable.io/reviews/pmem/rpma/1756#-N2wpvlzD2rfbqwdhJmL:-N2wpvlzD2rfbqwdhJmM:bz19bi9) ([raw file](https://github.com/pmem/rpma/blob/6aa653338d63c229bcc277da23b8c5bad4515637/THREAD_SAFETY.md#L8)):*
> ```Markdown
> 
> The following API calls of the librpma library are thread-safe:
> - struct rpma_peer;
> ```

`struct rpma_peer` is not an API call - why is it mentioned here?



_Code quote:_
```Markdown
The following API calls of the librpma library are thread-safe:
- struct rpma_peer;
```
___
*[`THREAD_SAFETY.md` line 20 at r1](https://reviewable.io/reviews/pmem/rpma/1756#-N2wqBW6CLR5PQzZKR3e:-N2wqBW6CLR5PQzZKR3f:blrjdeu) ([raw file](https://github.com/pmem/rpma/blob/6aa653338d63c229bcc277da23b8c5bad4515637/THREAD_SAFETY.md#L20)):*
> ```Markdown
> 
> The following API calls of the librpma library are NOT thread-safe:
> - struct rpma_peer_cfg;
> ```

`struct rpma_peer_cfg` is not an API call - why is it mentioned here?



_Code quote:_
```Markdown
The following API calls of the librpma library are NOT thread-safe:
- struct rpma_peer_cfg;
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1756)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[`THREAD_SAFETY.md` line 24 at r1](https://reviewable.io/reviews/pmem/rpma/1756#-N2wusv3E45kvGWfKYSh:-N2wusv43t33MFdVSJR0:bokid8l) ([raw file](https://github.com/pmem/rpma/blob/6aa653338d63c229bcc277da23b8c5bad4515637/THREAD_SAFETY.md#L24)):*
> ```Markdown
> - rpma_peer_cfg_get_direct_write_to_pmem()
> - rpma_peer_cfg_get_descriptor()
> - rpma_peer_cfg_get_descriptor_size()
> ```

Why is it not thread safe?



_Code quote:_
```Markdown
rpma_peer_cfg_get_descriptor_size()
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1756)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[`THREAD_SAFETY.md` line 8 at r1](https://reviewable.io/reviews/pmem/rpma/1756#-N2wpvlzD2rfbqwdhJmL:-N2z0dn1AGJ4RC1OnWYA:bcobggg) ([raw file](https://github.com/pmem/rpma/blob/6aa653338d63c229bcc277da23b8c5bad4515637/THREAD_SAFETY.md#L8)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`struct rpma_peer` is not an API call - why is it mentioned here?
</blockquote></details>

@grom72  should we be reviewing structures? 
___
*[`THREAD_SAFETY.md` line 24 at r1](https://reviewable.io/reviews/pmem/rpma/1756#-N2wusv3E45kvGWfKYSh:-N2z0Nbh0xcK0ZCGdz84:bnyykk5) ([raw file](https://github.com/pmem/rpma/blob/6aa653338d63c229bcc277da23b8c5bad4515637/THREAD_SAFETY.md#L24)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why is it not thread safe?
</blockquote></details>

You're right, thanks.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1756)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1756)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1756)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72 and @osalyk)

___
*[`THREAD_SAFETY.md` line 10 at r3](https://reviewable.io/reviews/pmem/rpma/1756#-N2zY44nDd_QcjOPD1f1:-N2zY44nDd_QcjOPD1f2:by5hcrb) ([raw file](https://github.com/pmem/rpma/blob/5796d9242c71d0503141268aad5bfe7c62ce5f22/THREAD_SAFETY.md#L10)):*
> ```Markdown
> - rpma_peer_new
> - rpma_peer_delete
> ```

I think this empty line is not needed.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1756)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[`THREAD_SAFETY.md` line 20 at r1](https://reviewable.io/reviews/pmem/rpma/1756#-N2wqBW6CLR5PQzZKR3e:-N2zdXN63wuq-Q-IdQWI:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6aa653338d63c229bcc277da23b8c5bad4515637/THREAD_SAFETY.md#L20)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`struct rpma_peer_cfg` is not an API call - why is it mentioned here?
</blockquote></details>

Done.
___
*[`THREAD_SAFETY.md` line 10 at r3](https://reviewable.io/reviews/pmem/rpma/1756#-N2zY44nDd_QcjOPD1f1:-N2zdcKW7KC4UFdX1xb7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5796d9242c71d0503141268aad5bfe7c62ce5f22/THREAD_SAFETY.md#L10)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I think this empty line is not needed.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1756#-:-N2ze22U3xWD52FHuyuB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1756)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

___
*[`THREAD_SAFETY.md` line 8 at r1](https://reviewable.io/reviews/pmem/rpma/1756#-N2wpvlzD2rfbqwdhJmL:-N2zengK4vXm4j6DIk23:bgu8yjs) ([raw file](https://github.com/pmem/rpma/blob/6aa653338d63c229bcc277da23b8c5bad4515637/THREAD_SAFETY.md#L8)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

@grom72  should we be reviewing structures? 
</blockquote></details>

yes - see the way how @ldorau described conn and conn_req

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1756)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @ldorau)

___
*[`THREAD_SAFETY.md` line 8 at r1](https://reviewable.io/reviews/pmem/rpma/1756#-N2wpvlzD2rfbqwdhJmL:-N2zjSv5-briMdgX9jev:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6aa653338d63c229bcc277da23b8c5bad4515637/THREAD_SAFETY.md#L8)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

yes - see the way how @ldorau described conn and conn_req
</blockquote></details>

Done.

**Pull request merged**
