### PR TITLE
common: generate markdown doc and use it for gh-pages

### PR DESCRIPTION
**Pull request by janekmi**
You can view the final result simulation here: https://janekmi.github.io/rpma/

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/268)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/268#-:-MF41v6C30QVbVIADIBQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/268)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/268)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/268#-:-MF4QM7U72Ns8fKjnqOr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
:rocket: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/268#-:-MF4RU3i3VNxgiDxla3C:biyjirz)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
