### PR TITLE
doc: HW & SW setup starting point description

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] ~~#800~~

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/824)

### CODE REVIEW

**Comment by ldorau** [comment]
Preview: https://ldorau.github.io/rpma/documentation/basic-hw_sw_setup_starting_point.html

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/824)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[documentation/basic-hw_sw_setup_starting_point.md, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/824#-MSbgy_LDtW2ybKIAJHg:-MSbgy_LDtW2ybKIAJHh:btsi2cy) ([raw file](https://github.com/pmem/rpma/blob/12dbe0bb28b149ee3c29e3a216b447f0cd8fc7ef/documentation/basic-hw_sw_setup_starting_point.md#L17)):*
> ```Markdown
>    - Intel® Optane™ persistent memory modules,
>    - DRAM DIMMs and
>    - RNICs
> ```

Since it is one of the first manuals the user should read I recommend to make it less abbreviated e.g.: RDMA-capable NIC

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/824)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[documentation/basic-hw_sw_setup_starting_point.md, line 6 at r1](https://reviewable.io/reviews/pmem/rpma/824#-MSbpGOCAw2lYOLfA1cP:-MSbpGOCAw2lYOLfA1cQ:b-dkl6sr) ([raw file](https://github.com/pmem/rpma/blob/12dbe0bb28b149ee3c29e3a216b447f0cd8fc7ef/documentation/basic-hw_sw_setup_starting_point.md#L6)):*
> ```Markdown
> ---
> 
> ### Remote Persistent Memory Access
> ```

Please see #839.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/824)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[documentation/basic-hw_sw_setup_starting_point.md, line 6 at r1](https://reviewable.io/reviews/pmem/rpma/824#-MSbpGOCAw2lYOLfA1cP:-MSc-Z-b5hklTuZYAKfi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/12dbe0bb28b149ee3c29e3a216b447f0cd8fc7ef/documentation/basic-hw_sw_setup_starting_point.md#L6)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please see #839.
</blockquote></details>

Done.
___
*[documentation/basic-hw_sw_setup_starting_point.md, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/824#-MSbgy_LDtW2ybKIAJHg:-MSc-YMU7QCgn2HQ-rMz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/12dbe0bb28b149ee3c29e3a216b447f0cd8fc7ef/documentation/basic-hw_sw_setup_starting_point.md#L17)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Since it is one of the first manuals the user should read I recommend to make it less abbreviated e.g.: RDMA-capable NIC
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/824)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[index.md, line 20 at r3](https://reviewable.io/reviews/pmem/rpma/824#-MScJoglDkp9Sf8HqnKs:-MScJoglDkp9Sf8HqnKt:b-t0ff3j) ([raw file](https://github.com/pmem/rpma/blob/a0d9324bd0e229c141611833b552a54cba589380/index.md#L20)):*
> ```Markdown
> 
> * [Basic - Direct write to PMem (WIP)](./documentation/basic-direct-write-to-pmem.html)
> * [Basic - HW & SW setup starting point (WIP)](./documentation/basic-hw_sw_setup_starting_point.html)
> ```

~~(WIP)~~?
___
*[documentation/basic-hw_sw_setup_starting_point.md, line 19 at r3](https://reviewable.io/reviews/pmem/rpma/824#-MScMBYL-qsjnIH6W-0w:-MScMBYL-qsjnIH6W-0x:b-y8l92o) ([raw file](https://github.com/pmem/rpma/blob/a0d9324bd0e229c141611833b552a54cba589380/documentation/basic-hw_sw_setup_starting_point.md#L19)):*
> ```Markdown
> 2) Verify that you have the required Linux kernel version: the Linux NVDIMM/PMem drivers are enabled by default, starting with Linux mainline kernel 4.2. We recommend mainline kernel version 4.19 or later to deliver Reliability, Availability and Serviceability (RAS) features required by the Persistent Memory Development Kit (PMDK) [[2]][start-2]
> 
> 3) Populate your DIMMs according to one of the recommended topologies as described in detail in the 1.2.4.1 chapter "Recommended Topologies" of "Intel Optane DC Persistent Memory Quick Start Guide" [[3]][start-3].
> ```

`Intel&reg; Optane &trade;`

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/824)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[index.md, line 20 at r3](https://reviewable.io/reviews/pmem/rpma/824#-MScJoglDkp9Sf8HqnKs:-MScPGsC0hOGvLKe52Nr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a0d9324bd0e229c141611833b552a54cba589380/index.md#L20)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

~~(WIP)~~?
</blockquote></details>

Done.
___
*[documentation/basic-hw_sw_setup_starting_point.md, line 19 at r3](https://reviewable.io/reviews/pmem/rpma/824#-MScMBYL-qsjnIH6W-0w:-MScPJ1351TfAAoRCzXp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a0d9324bd0e229c141611833b552a54cba589380/documentation/basic-hw_sw_setup_starting_point.md#L19)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`Intel&reg; Optane &trade;`
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/824#-:-MScPZp56oTxoLg8mP5z:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/824#-:-MScUsDABFdCRFGQYug2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
