### PR TITLE
tools: add 'all' options to rpma_fio_bench.sh

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/678)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/678#-:-MOkHehlBTUTgh3Hy5Jk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/678)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/678)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Comment by ldorau** [comment]
Requires (contains): #681

**Review by ldorau — COMMENTED** [review]
@janekmi @grom72 please review

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/678#-:-MPcTxhk5_kkvtOA63th:b-d57pf4)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/678)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/rpma_fio_bench.sh, line 230 at r3](https://reviewable.io/reviews/pmem/rpma/678#-MPcVCe0E7j2Pg2bcdxs:-MPcVCe0E7j2Pg2bcdxt:be2dmyv) ([raw file](https://github.com/pmem/rpma/blob/5c59ea15c3f8f05777213edc5ba86ed7ad057c62/tools/rpma_fio_bench.sh#L230)):*
> ```Shell
> else
> 	benchmark_one $OP $MODE $SERVER_IP
> fi
> ```

```sh
if [ "$OP" == "all" ]; then
    OP="$OPS"
fi

if [ "$MODE" == "all" ]; then
    MODE="$MODES"
fi

for o in $OP; do
    for m in $MODE; do
        benchmark_one $o $m $SERVER_IP
    done
done
```

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/678)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/rpma_fio_bench.sh, line 230 at r3](https://reviewable.io/reviews/pmem/rpma/678#-MPcVCe0E7j2Pg2bcdxs:-MPcWVW22mE9afT_ulCF:boycm0x) ([raw file](https://github.com/pmem/rpma/blob/5c59ea15c3f8f05777213edc5ba86ed7ad057c62/tools/rpma_fio_bench.sh#L230)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```sh
if [ "$OP" == "all" ]; then
    OP="$OPS"
fi

if [ "$MODE" == "all" ]; then
    MODE="$MODES"
fi

for o in $OP; do
    for m in $MODE; do
        benchmark_one $o $m $SERVER_IP
    done
done
```

</blockquote></details>

OPS -> OPS_ALL
OP -> OPS
MODES -> MODES_ALL
MODE -> MODES

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/678)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi and @osalyk)

___
*[tools/rpma_fio_bench.sh, line 230 at r3](https://reviewable.io/reviews/pmem/rpma/678#-MPcVCe0E7j2Pg2bcdxs:-MPcZu0a0xVI61zZ-ffy:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5c59ea15c3f8f05777213edc5ba86ed7ad057c62/tools/rpma_fio_bench.sh#L230)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

OPS -> OPS_ALL
OP -> OPS
MODES -> MODES_ALL
MODE -> MODES
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/678#-:-MPcoV1k-CJBDP7lc2g9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
