### PR TITLE
rpma: analysis of thread safety: rpma_mr_

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1763)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1763)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[`THREAD_SAFETY.md` line 12 at r1](https://reviewable.io/reviews/pmem/rpma/1763#-N2zS3YW8VyIADpK1MoI:-N2zS3YW8VyIADpK1MoJ:b-ydg8k3) ([raw file](https://github.com/pmem/rpma/blob/d8b45b497559b5f4738a5ca1be4c5b1e9985f0ba/THREAD_SAFETY.md#L12)):*
> ```Markdown
> - rpma_mr_get_descriptor()
> - rpma_mr_remote_from_descriptor()
> - rpma_mr_get_descriptor_size()
> ```

We do not use brackets in other PRs



_Code quote:_
```Markdown
- rpma_mr_reg()
- rpma_mr_dereg()
- rpma_mr_get_descriptor()
- rpma_mr_remote_from_descriptor()
- rpma_mr_get_descriptor_size()
- rpma_mr_get_ptr()
- rpma_mr_get_size()
- rpma_mr_remote_get_size()
- rpma_mr_remote_delete()
- rpma_mr_remote_get_flush_type()
- rpma_mr_advise()
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1763)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`THREAD_SAFETY.md` line 12 at r1](https://reviewable.io/reviews/pmem/rpma/1763#-N2zS3YW8VyIADpK1MoI:-N2zUeP_1Ey8HR7zRhrt:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d8b45b497559b5f4738a5ca1be4c5b1e9985f0ba/THREAD_SAFETY.md#L12)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

We do not use brackets in other PRs
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1763)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1763)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1763#-:-N2zeGyW47OA7gnirMC5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1763)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1763)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1763#-:-N2zx0Zw1CrU1sgEo9lU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1763)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1763#-N2zx2Tz29SklHqWCIUB:-N2zx2Tz29SklHqWCIUC:b-r5g5pn) (no related file):*
Please rebase and resolve conflicts.

___

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1763)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1763#-N2zx2Tz29SklHqWCIUB:-N3-2rpi9-PRgfj0sE5W:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please rebase and resolve conflicts.
</blockquote></details>

Done.

___

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1763)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1763#-N2zx2Tz29SklHqWCIUB:-N3-4_w3BOtTxRE84jOy:b6zx8d0) (no related file):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

once again, please (excuse me)

___

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1763)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72 and @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1763)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1763#-N2zx2Tz29SklHqWCIUB:-N3-6mFTApH5BfqwGGRH:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

once again, please (excuse me)
</blockquote></details>

Done.

___

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1763)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
