### PR TITLE
rpma: add fault injection and debug tracing

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1647)

### CODE REVIEW

**Review by grom72 — APPROVED** [review]
> Reviewed 12 of 21 files at r1, 7 of 8 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647#-:-N-MArQb2BWdmygyGhF_:bdycpsm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
> Reviewed 12 of 21 files at r1, 6 of 8 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647)* status: 20 of 21 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/debug.h, line 14 at r4](https://reviewable.io/reviews/pmem/rpma/1647#-N-McWjK-q5VUGbqrb6y:-N-McWjK-q5VUGbqrb6z:b-h4dwiu) ([raw file](https://github.com/pmem/rpma/blob/63b928179a2cfa98dd67541fdc2b735f61614a7e/src/debug.h#L14)):*
> ```objc
> 
> #ifdef DEBUG_LOG_TRACE
> #define RPMA_LOG_TRACE \
> ```

```RPMA_DEBUG_TRACE``` ??

``RPMA_LOG_xxxx`` are related to the core librpma logging functionality.



_Code quote:_
```objc
RPMA_LOG_TRACE
```
___
*[src/debug.h, line 24 at r4](https://reviewable.io/reviews/pmem/rpma/1647#-N-MgaWl5jNN_Hy28m7m:-N-MgaWm7xgr40R5VcGD:b-lzc9lp) ([raw file](https://github.com/pmem/rpma/blob/63b928179a2cfa98dd67541fdc2b735f61614a7e/src/debug.h#L24)):*
> ```objc
> 	do { \
> 		int ret = rpma_fault_injection(); \
> 		if (ret == RPMA_E_FAULT_INJECT) \
> ```

```
		if (ret == RPMA_E_FAULT_INJECT)  {\
			RPMA_LOG_DEBUG("[FAULT INJECTION]"); \
			return RPMA_E_FAULT_INJECT; \
		}\
```



_Code quote:_
```objc
		if (ret == RPMA_E_FAULT_INJECT) \
			return RPMA_E_FAULT_INJECT; \
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647)* status: 20 of 21 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/debug.h, line 24 at r4](https://reviewable.io/reviews/pmem/rpma/1647#-N-MgaWl5jNN_Hy28m7m:-N-MojnP7YCEmllMv7ym:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/63b928179a2cfa98dd67541fdc2b735f61614a7e/src/debug.h#L24)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```
		if (ret == RPMA_E_FAULT_INJECT)  {\
			RPMA_LOG_DEBUG("[FAULT INJECTION]"); \
			return RPMA_E_FAULT_INJECT; \
		}\
```
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647)* status: 20 of 21 files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[src/debug.h, line 14 at r4](https://reviewable.io/reviews/pmem/rpma/1647#-N-McWjK-q5VUGbqrb6y:-N-MpS2P833QyMgxOLuo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/63b928179a2cfa98dd67541fdc2b735f61614a7e/src/debug.h#L14)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```RPMA_DEBUG_TRACE``` ??

``RPMA_LOG_xxxx`` are related to the core librpma logging functionality.
</blockquote></details>

Done.

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647)* status: 8 of 21 files reviewed, 1 unresolved discussion (waiting on @grom72, @ldorau, and @osalyk)

___
*[src/debug.h, line 24 at r4](https://reviewable.io/reviews/pmem/rpma/1647#-N-MgaWl5jNN_Hy28m7m:-N-Mz_e5A8zeX2wuZwsn:b-ynksxf) ([raw file](https://github.com/pmem/rpma/blob/63b928179a2cfa98dd67541fdc2b735f61614a7e/src/debug.h#L24)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

ret == RPMA_E_FAULT_INJECT is not a counter value.

I proposed a separate message with capital letters to make it easier to find in the log ``[FAULT INJECTION ]`` point.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647)* status: 8 of 21 files reviewed, 1 unresolved discussion (waiting on @grom72 and @osalyk)

___
*[src/debug.h, line 24 at r4](https://reviewable.io/reviews/pmem/rpma/1647#-N-MgaWl5jNN_Hy28m7m:-N-N0TQB7dFXP_h1RwoM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/63b928179a2cfa98dd67541fdc2b735f61614a7e/src/debug.h#L24)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

ret == RPMA_E_FAULT_INJECT is not a counter value.

I proposed a separate message with capital letters to make it easier to find in the log ``[FAULT INJECTION ]`` point.
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
An example output:
```
Starting the client ...
RPMA_FAULT_INJECTION=10  build/examples/12-receive-completion-queue/client 192.168.1.100 7204 7 3
Apr 11 11:57:56.400195 [96157] *INFO*  rpma.c:  26: rpma_utils_get_ibv_context: [#1]
Apr 11 11:57:56.400228 [96157] *INFO*  info.c:  40: rpma_info_new: [#2]
Apr 11 11:57:56.401769 [96157] *INFO*  info.c: 125: rpma_info_resolve_addr: [#3]
Apr 11 11:57:56.401917 [96157] *INFO*  info.c:  96: rpma_info_delete: [#4]
Apr 11 11:57:56.401941 [96157] *INFO*  peer.c: 228: rpma_peer_new: [#5]
Apr 11 11:57:56.401956 [96157] *INFO*  rpma.c:  87: rpma_utils_ibv_context_is_odp_capable: [#6]
Apr 11 11:57:56.401985 [96157] *INFO*  mr.c: 352: rpma_mr_reg: [#7]
Apr 11 11:57:56.402002 [96157] *INFO*  peer.c: 173: rpma_peer_mr_reg: [#8]
Apr 11 11:57:56.402017 [96157] *INFO*  peer.c:  45: rpma_peer_usage_to_access: [#9]
Apr 11 11:57:56.402047 [96157] *INFO*  mr.c: 352: rpma_mr_reg: [FAULT INJECTION]
Apr 11 11:57:56.402064 [96157] *INFO*  mr.c: 387: rpma_mr_dereg: [#11]
Apr 11 11:57:56.402086 [96157] *INFO*  peer.c: 285: rpma_peer_delete: [#12]
```

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647#-:-N-N2sdtAmzyPzzn1nVr:b-6n6cw2)* status: 7 of 21 files reviewed, 1 unresolved discussion (waiting on @grom72 and @osalyk)

**Review by ldorau — COMMENTED** [review]
And an example output of debug trace:
```
*** Running example: 12-receive-completion-queue 
Starting the server ...
Apr 11 12:45:38.798986 [153839] *INFO*  rpma.c:  25: rpma_utils_get_ibv_context: -
Apr 11 12:45:38.799017 [153839] *INFO*  info.c:  39: rpma_info_new: -
Apr 11 12:45:38.800485 [153839] *INFO*  info.c: 147: rpma_info_bind_addr: -
Apr 11 12:45:38.800577 [153839] *INFO*  info.c:  95: rpma_info_delete: -
Apr 11 12:45:38.800599 [153839] *INFO*  peer.c: 227: rpma_peer_new: -
Apr 11 12:45:38.800614 [153839] *INFO*  rpma.c:  86: rpma_utils_ibv_context_is_odp_capable: -
Apr 11 12:45:38.800646 [153839] *INFO*  ep.c:  43: rpma_ep_listen: -
Apr 11 12:45:38.800673 [153839] *INFO*  info.c:  39: rpma_info_new: -
Apr 11 12:45:38.800689 [153839] *INFO*  info.c: 147: rpma_info_bind_addr: -
Apr 11 12:45:38.800723 [153839] *INFO*  info.c:  95: rpma_info_delete: -
Apr 11 12:45:38.800739 [153839] *NOTE*  ep.c:  96: rpma_ep_listen: Waiting for incoming connection on 192.168.1.100:7204
Apr 11 12:45:38.800753 [153839] *INFO*  mr.c: 351: rpma_mr_reg: -
Apr 11 12:45:38.800772 [153839] *INFO*  peer.c: 172: rpma_peer_mr_reg: -
Apr 11 12:45:38.800797 [153839] *INFO*  peer.c:  44: rpma_peer_usage_to_access: -
Apr 11 12:45:38.800832 [153839] *INFO*  mr.c: 351: rpma_mr_reg: -
Apr 11 12:45:38.800848 [153839] *INFO*  peer.c: 172: rpma_peer_mr_reg: -
Apr 11 12:45:38.800862 [153839] *INFO*  peer.c:  44: rpma_peer_usage_to_access: -
Apr 11 12:45:38.800886 [153839] *INFO*  conn_cfg.c: 121: rpma_conn_cfg_new: -
Apr 11 12:45:38.800903 [153839] *INFO*  conn_cfg.c: 231: rpma_conn_cfg_set_rcq_size: -
Apr 11 12:45:38.800919 [153839] *INFO*  ep.c: 168: rpma_ep_next_conn_req: -
```

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647#-:-N-NDlUW-0LogH0VUbcw:b8i8heg)* status: 7 of 21 files reviewed, 1 unresolved discussion (waiting on @grom72 and @osalyk)

**Review by grom72 — COMMENTED** [review]
Why all messages are displayed with the ``*INFO*`` label?

> Reviewed 12 of 13 files at r6, 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647#-:-N-NJKW9CPPdwM0RXx7j:b-e6tk5l)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @osalyk)

**Review by ldorau — COMMENTED** [review]
`s/INFO/DEBUG/g` ;-) I have just changed the log level in debug.h to INFO to get the output faster :-)

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647#-:-N-NKHCd2oOWhDIskw_-:b-ghtwnp)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @osalyk)

**Review by grom72 — APPROVED** [review]
OK

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647#-:-N-NLKU3Ai3gKrSYzyas:bb70uqp)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — COMMENTED** [review]
The first issue found using fault injection: 
https://app.circleci.com/pipelines/github/ldorau/rpma/2913/workflows/719d171f-a758-42cf-aa50-f67280a08d17/jobs/2928

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647#-:-N-NS3MBEjCNXeTDZuf1:b-xaz2so)* status: 11 of 21 files reviewed, all discussions resolved (waiting on @grom72 and @osalyk)

**Review by grom72 — COMMENTED** [review]
> Reviewed 3 of 10 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647)* status: 14 of 21 files reviewed, all discussions resolved (waiting on @grom72 and @osalyk)

**Review by ldorau — COMMENTED** [review]
And the next one:
https://app.circleci.com/pipelines/github/ldorau/rpma/2917/workflows/7138a552-d110-4840-b34c-028988ad4318/jobs/2932

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647#-:-N-NhpJFBKZ41A2YuIx0:b-drejl6)* status: 14 of 21 files reviewed, all discussions resolved (waiting on @grom72 and @osalyk)

**Review by ldorau — COMMENTED** [review]
https://app.circleci.com/pipelines/github/ldorau/rpma/2918/workflows/d200c30a-1313-4a57-803e-36757d96cded/jobs/2933

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647#-:-N-NoNMjCYRPz4OmAI6T:brzt5wi)* status: 14 of 21 files reviewed, all discussions resolved (waiting on @grom72 and @osalyk)

**Comment by ldorau** [comment]
The following issue was found using this PR: https://github.com/pmem/rpma/pull/1686

**Comment by ldorau** [comment]
The following issues was found using this PR: 
- https://github.com/pmem/rpma/pull/1686
- https://github.com/pmem/rpma/pull/1687
- https://github.com/pmem/rpma/pull/1688

**Review by grom72 — APPROVED** [review]
> Reviewed 16 of 16 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647#-:-N0B_IRf0I7qgmbbqEvU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — COMMENTED** [review]
> Reviewed 9 of 10 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647)* status: 28 of 29 files reviewed, all discussions resolved (waiting on @grom72 and @osalyk)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 10 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647)* status: 28 of 29 files reviewed, all discussions resolved (waiting on @grom72 and @osalyk)

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r12, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — APPROVED** [review]
> Reviewed 4 of 4 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — COMMENTED** [review]
> Reviewed 14 of 16 files at r15, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647)* status: 30 of 32 files reviewed, all discussions resolved (waiting on @grom72 and @osalyk)

**Review by grom72 — APPROVED** [review]
> Reviewed 2 of 16 files at r15.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[`src/debug.h` line 34 at r15](https://reviewable.io/reviews/pmem/rpma/1647#-N1Nj6bN4MfPeta7j9Q1:-N1ORoSZ71qWZJBJIpDX:b-wp4jvf) ([raw file](https://github.com/pmem/rpma/blob/97d3bb9de8b370925db3e20c8c690e50dac2a6df/src/debug.h#L34)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

``rpma_fault_injection()''definition should be before first recall in macro
Can we show a counter value also when fault injection occurs?
Can we not return anything else than the status ``OK - 0``/``RPMA_E_FAULT_INJECT`` from ``rpma_fault_injection``
</blockquote></details>

Declaration of `rpma_fault_injection()` does not have to be before first recall in macro. Defines are usually placed before declarations.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647)* status: 30 of 32 files reviewed, 6 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`src/debug.h` line 34 at r15](https://reviewable.io/reviews/pmem/rpma/1647#-N1Nj6bN4MfPeta7j9Q1:-N1OUqdy5dZO3soVRzbp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/97d3bb9de8b370925db3e20c8c690e50dac2a6df/src/debug.h#L34)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Declaration of `rpma_fault_injection()` does not have to be before first recall in macro. Defines are usually placed before declarations.
</blockquote></details>

Done.
___
*[`src/debug.c` line 18 at r15](https://reviewable.io/reviews/pmem/rpma/1647#-N1NjpxVBn3YprUeZOqx:-N1OUtgv39JwkMgA6vgZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/97d3bb9de8b370925db3e20c8c690e50dac2a6df/src/debug.c#L18)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`src/debug.c` line 21 at r15](https://reviewable.io/reviews/pmem/rpma/1647#-N1NqXOc9eRGUIjNUwRo:-N1OV0IC46vFSMKXh0ly:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/97d3bb9de8b370925db3e20c8c690e50dac2a6df/src/debug.c#L21)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`src/debug.c` line 34 at r15](https://reviewable.io/reviews/pmem/rpma/1647#-N1Nqb-E3-4C0cvp5zHl:-N1OUyQ98FJwP87xOuH5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/97d3bb9de8b370925db3e20c8c690e50dac2a6df/src/debug.c#L34)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`src/debug.c` line 36 at r15](https://reviewable.io/reviews/pmem/rpma/1647#-N1NqfXU6TsnGo9sPX_0:-N1OUyy84koMdDm6R6Ge:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/97d3bb9de8b370925db3e20c8c690e50dac2a6df/src/debug.c#L36)):*
> ```C
> 			return RPMA_E_FAULT_INJECT;
> 
> 		return counter;
> ```

Done.
___
*[`src/debug.c` line 39 at r15](https://reviewable.io/reviews/pmem/rpma/1647#-N1Nqvqr9pUrd8O0PNy1:-N1OV-9mEr1yer434nRC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/97d3bb9de8b370925db3e20c8c690e50dac2a6df/src/debug.c#L39)):*
> ```C
> 	}
> 
> 	return 0;
> ```

Done.

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647)* status: all files reviewed, 6 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[`src/conn_req.c` line 214 at r16](https://reviewable.io/reviews/pmem/rpma/1647#-N1OfhdZ4VN_tP9vFXnQ:-N1OfhdZ4VN_tP9vFXnR:blhzie5) ([raw file](https://github.com/pmem/rpma/blob/379020c588cf97813ad22bc3b857e7789f0bb24e/src/conn_req.c#L214)):*
> ```C
> 		goto err_conn_req_delete;
> 	}
> ```

One more fault injection point



_Code quote:_
```C
	RPMA_FAULT_INJECTION(
	{
		rdma_destroy_qp(req->id);
		(void) rpma_cq_delete(&req->rcq);
		(void) rpma_cq_delete(&req->cq);
		if (req->channel)
			(void) ibv_destroy_comp_channel(req->channel);
	});
```
___
*[`src/conn_req.c` line 221 at r16](https://reviewable.io/reviews/pmem/rpma/1647#-N1OfziB044SrzxCd3r8:-N1OfziB044SrzxCd3r9:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/379020c588cf97813ad22bc3b857e7789f0bb24e/src/conn_req.c#L221)):*
> ```C
> 		goto err_conn_disconnect;
> 	}
> ```

.



_Suggestion:_
```C
	RPMA_FAULT_INJECTION(
	{
		(void) rdma_disconnect(req->id);
		rdma_destroy_qp(req->id);
		(void) rpma_cq_delete(&req->rcq);
		(void) rpma_cq_delete(&req->cq);
		if (req->channel)
			(void) ibv_destroy_comp_channel(req->channel);
	});
```
___
*[`src/conn_req.c` line 284 at r16](https://reviewable.io/reviews/pmem/rpma/1647#-N1Od3lD7TwcOh_86RwD:-N1Od3lD7TwcOh_86RwE:b-oa8nob) ([raw file](https://github.com/pmem/rpma/blob/379020c588cf97813ad22bc3b857e7789f0bb24e/src/conn_req.c#L284)):*
> ```C
> 		return ret;
> 	}
> ```

We should enable force injection with almost every rdma_* and ibv_* function calls



_Suggestion:_
```C
	RPMA_FAULT_INJECTION(
	{
		rdma_destroy_qp(req->id);
		(void) rpma_conn_delete(&conn);
	});
```
___
*[`src/conn_req.c` line 433 at r16](https://reviewable.io/reviews/pmem/rpma/1647#-N1OeEzK831qIuMtlkRD:-N1OeEzK831qIuMtlkRE:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/379020c588cf97813ad22bc3b857e7789f0bb24e/src/conn_req.c#L433)):*
> ```C
> 		ret = RPMA_E_PROVIDER;
> 		goto err_info_delete;
> 	}
> ```

.



_Suggestion:_
```C
	RPMA_FAULT_INJECTION(
	{
		(void) rpma_info_delete(&info);
	});
```
___
*[`src/conn_req.c` line 447 at r16](https://reviewable.io/reviews/pmem/rpma/1647#-N1OeSA-02sXH6H5u7kw:-N1OeSA-02sXH6H5u7kx:b-o1yhkc) ([raw file](https://github.com/pmem/rpma/blob/379020c588cf97813ad22bc3b857e7789f0bb24e/src/conn_req.c#L447)):*
> ```C
> 		goto err_destroy_id;
> 	}
> ```

 	RPMA_FAULT_INJECTION(
 	{
 		(void) rdma_destroy_id(id);
                (void) rpma_info_delete(&info);
 	});
___
*[`src/ep.c` line 136 at r16](https://reviewable.io/reviews/pmem/rpma/1647#-N1Oaro4-cqbjhWw-1QB:-N1Oaro5-yW5LPKXTiW6:b-f6epmy) ([raw file](https://github.com/pmem/rpma/blob/379020c588cf97813ad22bc3b857e7789f0bb24e/src/ep.c#L136)):*
> ```C
> 	*ep_ptr = NULL;
> 
> 	RPMA_FAULT_INJECTION();
> ```

shall we unify 



_Suggestion:_
```C
	RPMA_FAULT_INJECTION(
	{		
		rdma_destroy_id(((struct rpma_ep *)ep)->id);
		rdma_destroy_event_channel(((struct rpma_ep *)ep)->evch);
		free(ep);
	});
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[`src/ep.c` line 136 at r16](https://reviewable.io/reviews/pmem/rpma/1647#-N1Oaro4-cqbjhWw-1QB:-N1b_NkB0qSml2ykPTE9:bsik7j0) ([raw file](https://github.com/pmem/rpma/blob/379020c588cf97813ad22bc3b857e7789f0bb24e/src/ep.c#L136)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

shall we unify 
</blockquote></details>

I think no. The current form does not need to be updated when the function changes, while the new one will have to be updated every time the function is changed what increases the cost of maintainability of this function.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[`src/conn_req.c` line 284 at r16](https://reviewable.io/reviews/pmem/rpma/1647#-N1Od3lD7TwcOh_86RwD:-N1bah1n47gMOl_5tW-J:b-5q7d2c) ([raw file](https://github.com/pmem/rpma/blob/379020c588cf97813ad22bc3b857e7789f0bb24e/src/conn_req.c#L284)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

We should enable force injection with almost every rdma_* and ibv_* function calls
</blockquote></details>

This possibility is worth considering, but in my opinion in a separate PR, as this one is already big enough.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[`src/conn_req.c` line 433 at r16](https://reviewable.io/reviews/pmem/rpma/1647#-N1OeEzK831qIuMtlkRD:-N1bbA-bA2J8talcUujF:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/379020c588cf97813ad22bc3b857e7789f0bb24e/src/conn_req.c#L433)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

.
___
*[`src/conn_req.c` line 447 at r16](https://reviewable.io/reviews/pmem/rpma/1647#-N1OeSA-02sXH6H5u7kw:-N1baooF8yt1zWHYMgur:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/379020c588cf97813ad22bc3b857e7789f0bb24e/src/conn_req.c#L447)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

 	RPMA_FAULT_INJECTION(
 	{
 		(void) rdma_destroy_id(id);
                (void) rpma_info_delete(&info);
 	});

</blockquote></details>

.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`src/conn_req.c` line 214 at r16](https://reviewable.io/reviews/pmem/rpma/1647#-N1OfhdZ4VN_tP9vFXnQ:-N1bcoj4DidTd8xYVBDc:brajwu3) ([raw file](https://github.com/pmem/rpma/blob/379020c588cf97813ad22bc3b857e7789f0bb24e/src/conn_req.c#L214)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

One more fault injection point
</blockquote></details>

Try to do it and check how the function looks like. I am afraid it will make the function ugly and unreadable.
IMHO we should avoid inserting `RPMA_FAULT_INJECTION(exit_code)` with such extensive `exit_code`.
___
*[`src/conn_req.c` line 221 at r16](https://reviewable.io/reviews/pmem/rpma/1647#-N1OfziB044SrzxCd3r8:-N1bd0sd5E6QOdNNpiZY:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/379020c588cf97813ad22bc3b857e7789f0bb24e/src/conn_req.c#L221)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

.

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1647#-N1bl_gMCC7FB8MmouzY:-N1bl_gMCC7FB8MmouzZ:b-91fqnv) (no related file):*
Let's move additional fault injection points to separate PR.
So far we have one fault injection per function + one fault injection per each ``rpma_*`` subfunction.
In the future, it should be possible to break execution every time the ``rdma_*`` or ``ibv_*`` function is called.

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1647#-N1bl_gMCC7FB8MmouzY:-N1c3X3k7KPATB7SSlnK:b32v57) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Let's move additional fault injection points to separate PR.
So far we have one fault injection per function + one fault injection per each ``rpma_*`` subfunction.
In the future, it should be possible to break execution every time the ``rdma_*`` or ``ibv_*`` function is called.
</blockquote></details>

+1

---

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — APPROVED** [review]
> Reviewed 2 of 2 files at r19, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
:goat: 

> Reviewed 1 of 2 files at r4, 13 of 13 files at r6, 3 of 16 files at r10, 10 of 16 files at r15, 1 of 2 files at r16, 1 of 1 files at r17, 1 of 2 files at r19, 1 of 1 files at r20, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647#-:-N1mfOMJ47_Jw-BgVEFD:bdycpsm)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[`INSTALL.md` line 85 at r19](https://reviewable.io/reviews/pmem/rpma/1647#-N1mRmHt9iRFQ0pPkJdj:-N1mRmHt9iRFQ0pPkJdk:bso6cx4) ([raw file](https://github.com/pmem/rpma/blob/59103a953030621080ecb4edd51774eab730b331/INSTALL.md#L85)):*
> ```Markdown
> | USE_ASAN | Enable AddressSanitizer | ON/OFF | OFF |
> | USE_UBSAN | Enable UndefinedBehaviorSanitizer | ON/OFF | OFF |
> | DEBUG_LOG_TRACE | enable logging functions' traces | ON/OFF | OFF |
> ```

Enable



_Code quote:_
```Markdown
enable
```
___
*[`INSTALL.md` line 86 at r19](https://reviewable.io/reviews/pmem/rpma/1647#-N1mRpLm9M05nWFd8zcZ:-N1mRpLm9M05nWFd8zc_:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/59103a953030621080ecb4edd51774eab730b331/INSTALL.md#L86)):*
> ```Markdown
> | USE_UBSAN | Enable UndefinedBehaviorSanitizer | ON/OFF | OFF |
> | DEBUG_LOG_TRACE | enable logging functions' traces | ON/OFF | OFF |
> | DEBUG_FAULT_INJECTION | enable fault injection | ON/OFF | OFF |
> ```

.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647)* status: 31 of 32 files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`INSTALL.md` line 85 at r19](https://reviewable.io/reviews/pmem/rpma/1647#-N1mRmHt9iRFQ0pPkJdj:-N1mgkeq2I0dZD_mQCly:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/59103a953030621080ecb4edd51774eab730b331/INSTALL.md#L85)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Enable
</blockquote></details>

Done.
___
*[`INSTALL.md` line 86 at r19](https://reviewable.io/reviews/pmem/rpma/1647#-N1mRpLm9M05nWFd8zcZ:-N1mgiX8CgTOfakxNRAT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/59103a953030621080ecb4edd51774eab730b331/INSTALL.md#L86)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r21, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1647#-:-N1mhCWwDD476QJCAKqC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
