### PR TITLE
test: add unit test and doc for rpma_conn_get_compl_fd()

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1650)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1650)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @haichangsi and @ldorau)

___
*[src/include/librpma.h, line 1845 at r1](https://reviewable.io/reviews/pmem/rpma/1650#-N-RpImK9GCj07tF_7qD:-N-RpImK9GCj07tF_7qE:b6lhb6s) ([raw file](https://github.com/pmem/rpma/blob/9d2d4394727aac3b9f4331d8c9081cd7a35b76a7/src/include/librpma.h#L1845)):*
> ```objc
>  * code on failure. rpma_conn_get_cq() does not set *cq_ptr value on failure.
>  *
>  * ERRORS
> ```

Do not remove it.



_Code quote:_
```objc
 * ERRORS
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1650)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @haichangsi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1650#-N-RxymCDCn4ooVHXXwt:-N-RxymCDCn4ooVHXXwu:b-ni3tmb) (no related file):*
Rebase please.

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1650)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[tests/unit/conn/conn-get_compl_fd.c, line 71 at r1](https://reviewable.io/reviews/pmem/rpma/1650#-N-RyNdU48M5IXSRt1bv:-N-RyNdU48M5IXSRt1bw:b6nsrta) ([raw file](https://github.com/pmem/rpma/blob/b1d6de0ab912c81bbd49e4c7fbebcd74743070e3/tests/unit/conn/conn-get_compl_fd.c#L71)):*
> ```C
> 
> 	/* verify the results */
> 	assert_int_equal(ret, 0);
> ```

Please use `MOCK_OK` instead of `0` in unit tests.



_Code quote:_
```C
0
```

**Review by grom72 — APPROVED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1650)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi and @ldorau)

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1650)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi and @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1650)* status: all files reviewed, 4 unresolved discussions (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1650#-N-Wb3hS4Vb-r6ENdJ1t:-N-Wb3hS4Vb-r6ENdJ1u:b-c0150s) (no related file):*
Builds fail

---

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1650)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1650#-N-RxymCDCn4ooVHXXwt:-N-bDwrGDa3wmbq7e4ct:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Rebase please.
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1650#-N-Wb3hS4Vb-r6ENdJ1t:-N-bDxDU1Tb1gq4JD_CI:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Builds fail
</blockquote></details>

Done.

---
___
*[src/include/librpma.h, line 1845 at r1](https://reviewable.io/reviews/pmem/rpma/1650#-N-RpImK9GCj07tF_7qD:-N-bENFI0C48DAnmtYbC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9d2d4394727aac3b9f4331d8c9081cd7a35b76a7/src/include/librpma.h#L1845)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Do not remove it.
</blockquote></details>

Done.
___
*[tests/unit/conn/conn-get_compl_fd.c, line 71 at r1](https://reviewable.io/reviews/pmem/rpma/1650#-N-RyNdU48M5IXSRt1bv:-N-bE6GH4O9dtwmNoF1y:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b1d6de0ab912c81bbd49e4c7fbebcd74743070e3/tests/unit/conn/conn-get_compl_fd.c#L71)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please use `MOCK_OK` instead of `0` in unit tests.
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1650)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1650#-N-Wb3hS4Vb-r6ENdJ1t:-N-c12-B-6gryifvAkuU:b-x2uc0m) (no related file):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet, they still fail.

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1650)* status: 3 of 5 files reviewed, 2 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[src/include/librpma.h, line 2169 at r2](https://reviewable.io/reviews/pmem/rpma/1650#-N-c1_-JDCyH9-d_PxHY:-N-c1_-K9_IL3JB0BxNZ:bgqnkk3) ([raw file](https://github.com/pmem/rpma/blob/5f50ac2b403ca6232f9737643d0f7aeeceea3f98/src/include/librpma.h#L2169)):*
> ```objc
>  *
>  * - RPMA_E_INVAL - conn or fd is NULL
>  * - RPMA_E_NOT_SHARED_CHNL - shared channel is NULL
> ```

the completion channel is not shared.



_Code quote:_
```objc
shared channel is NULL
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1650)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[tests/unit/conn/conn-common.c, line 90 at r2](https://reviewable.io/reviews/pmem/rpma/1650#-N-c2lId0mvMvH0xfd2r:-N-c2lId0mvMvH0xfd2s:bjmoztm) ([raw file](https://github.com/pmem/rpma/blob/5f50ac2b403ca6232f9737643d0f7aeeceea3f98/tests/unit/conn/conn-common.c#L90)):*
> ```C
> 	int ret;
> 
> 	/* prepare an object */
> ```

See how @osalyk did it in https://github.com/pmem/rpma/pull/1655



_Code quote:_
```C
	/* prepare an object */
	if (cstate->rcq != NULL)
	{
		ret = rpma_conn_new(MOCK_PEER, MOCK_CM_ID,
			MOCK_RPMA_CQ, cstate->rcq,
			MOCK_COMP_CHANNEL, &cstate->conn);
	}
	else
	{
		ret = rpma_conn_new(MOCK_PEER, MOCK_CM_ID,
				MOCK_RPMA_CQ, cstate->rcq,
				NULL, &cstate->conn);
	}
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1650)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[tests/unit/conn/conn-get_compl_fd.c, line 115 at r2](https://reviewable.io/reviews/pmem/rpma/1650#-N-c4jyf0ZQ_hXKNsALB:-N-c4jyf0ZQ_hXKNsALC:b-twauhv) ([raw file](https://github.com/pmem/rpma/blob/5f50ac2b403ca6232f9737643d0f7aeeceea3f98/tests/unit/conn/conn-get_compl_fd.c#L115)):*
> ```C
> 	cmocka_unit_test_prestate_setup_teardown(
> 		get_compl_fd__success, setup__conn_new,
> 		teardown__conn_delete, &Conn_with_rcq),
> ```

`Conn_with_rcq_channel`



_Code quote:_
```C
Conn_with_rcq
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1650)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[tests/unit/conn/conn-common.c, line 90 at r2](https://reviewable.io/reviews/pmem/rpma/1650#-N-c2lId0mvMvH0xfd2r:-N-c5NMs3DE-RNGIWxU-:bagolv) ([raw file](https://github.com/pmem/rpma/blob/5f50ac2b403ca6232f9737643d0f7aeeceea3f98/tests/unit/conn/conn-common.c#L90)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

See how @osalyk did it in https://github.com/pmem/rpma/pull/1655
</blockquote></details>

You can just rebase on top of #1655

**Review by osalyk — APPROVED** [review]
> Reviewed 1 of 4 files at r1, 1 of 4 files at r2, 7 of 11 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1650)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 7 of 11 files at r3, 3 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1650)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[tests/unit/conn/conn-get_compl_fd.c, line 61 at r4](https://reviewable.io/reviews/pmem/rpma/1650#-N-cQ2MBCK91wB9CHY0u:-N-cQ2MBCK91wB9CHY0v:b-a4jrkf) ([raw file](https://github.com/pmem/rpma/blob/326477cc82e806a7f602d3ad42e14254ec0afea5/tests/unit/conn/conn-get_compl_fd.c#L61)):*
> ```C
> 
> /*
>  * get_compl_fd__channel_NULL -- channel is NULL
> ```

get_compl_fd__E_NOT_SHARED_CHNL -- rpma_conn_get_compl_fd fails with RPMA_E_NOT_SHARED_CHNL



_Code quote:_
```C
get_compl_fd__channel_NULL -- channel is NULL
```
___
*[tests/unit/conn/conn-get_compl_fd.c, line 64 at r4](https://reviewable.io/reviews/pmem/rpma/1650#-N-cPmlD6cQ7wyo-8r-i:-N-cPmlD6cQ7wyo-8r-j:baopwjt) ([raw file](https://github.com/pmem/rpma/blob/326477cc82e806a7f602d3ad42e14254ec0afea5/tests/unit/conn/conn-get_compl_fd.c#L64)):*
> ```C
>  */
> static void
> get_compl_fd__channel_NULL(void **cstate_ptr)
> ```

get_compl_fd__E_NOT_SHARED_CHNL



_Code quote:_
```C
get_compl_fd__channel_NULL
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1650)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[src/include/librpma.h, line 2169 at r2](https://reviewable.io/reviews/pmem/rpma/1650#-N-c1_-JDCyH9-d_PxHY:-N-cQOkc7UoZ2iVokh0C:bsb5177) ([raw file](https://github.com/pmem/rpma/blob/5f50ac2b403ca6232f9737643d0f7aeeceea3f98/src/include/librpma.h#L2169)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

the completion channel is not shared.
</blockquote></details>

Has `RPMA_E_NOT_SHARED_CHNL`  disappeared ? ;-)

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1650)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[src/include/librpma.h, line 2169 at r2](https://reviewable.io/reviews/pmem/rpma/1650#-N-c1_-JDCyH9-d_PxHY:-N-cSdYP9fqHaBWhMYJy:bap281c) ([raw file](https://github.com/pmem/rpma/blob/5f50ac2b403ca6232f9737643d0f7aeeceea3f98/src/include/librpma.h#L2169)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Has `RPMA_E_NOT_SHARED_CHNL`  disappeared ? ;-)
</blockquote></details>

It is rebased on top of @osalyk pr, not mine doc
___
*[tests/unit/conn/conn-get_compl_fd.c, line 61 at r4](https://reviewable.io/reviews/pmem/rpma/1650#-N-cQ2MBCK91wB9CHY0u:-N-cTCqe5Tx_nH1Tdo2D:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/326477cc82e806a7f602d3ad42e14254ec0afea5/tests/unit/conn/conn-get_compl_fd.c#L61)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

get_compl_fd__E_NOT_SHARED_CHNL -- rpma_conn_get_compl_fd fails with RPMA_E_NOT_SHARED_CHNL
</blockquote></details>

Done.
___
*[tests/unit/conn/conn-get_compl_fd.c, line 64 at r4](https://reviewable.io/reviews/pmem/rpma/1650#-N-cPmlD6cQ7wyo-8r-i:-N-cTNaK7ZayFjX0z0eU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/326477cc82e806a7f602d3ad42e14254ec0afea5/tests/unit/conn/conn-get_compl_fd.c#L64)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

get_compl_fd__E_NOT_SHARED_CHNL
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1650)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1650#-N-Wb3hS4Vb-r6ENdJ1t:-N-cVZK0-I7BxHm7S_TC:bvyku9u) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not yet, they still fail.
</blockquote></details>

`/rpma/tests/unit/conn/conn-get_compl_fd.c:61: ERROR: trailing whitespace`

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1650)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)

___
*[src/include/librpma.h, line 2169 at r2](https://reviewable.io/reviews/pmem/rpma/1650#-N-c1_-JDCyH9-d_PxHY:-N-cjrNm5X0jkmRz8soc:bdmh8zb) ([raw file](https://github.com/pmem/rpma/blob/5f50ac2b403ca6232f9737643d0f7aeeceea3f98/src/include/librpma.h#L2169)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No, I'm not falling for it ;-)
All the comments are from your PR. You can see the snippet of your code in the first comment: `shared channel is NULL` which I suggested to replace with `the completion channel is not shared.` - where is it now?
See: https://github.com/pmem/rpma/pull/1650#pullrequestreview-942211516
and
https://reviewable.io/reviews/pmem/rpma/1650#-N-c1_-JDCyH9-d_PxHY:-N-c1_-K9_IL3JB0BxNZ:bgqnkk3
</blockquote></details>

Ah, reviewable has moved the comment down, see above ...
___
*[src/include/librpma.h, line 2169 at r5](https://reviewable.io/reviews/pmem/rpma/1650#-N-ck39w27wpPRyXOejb:-N-ck39w27wpPRyXOejc:b-u2fqii) ([raw file](https://github.com/pmem/rpma/blob/d117e0dfc62abf95446eb738eed468f862956cf9/src/include/librpma.h#L2169)):*
> ```objc
>  *
>  * - RPMA_E_INVAL - conn or fd is NULL
>  * - RPMA_E_NOT_SHARED_CHNL - completion channel is NULL
> ```

... that comment should be here.
See: https://reviewable.io/reviews/pmem/rpma/1650#-N-c1_-JDCyH9-d_PxHY:-N-c1_-K9_IL3JB0BxNZ:bgqnkk3



_Code quote:_
```objc
RPMA_E_NOT_SHARED_CHNL - completion channel is NULL
```

**Review by grom72 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1650)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi and @osalyk)

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1650)* status: 2 of 11 files reviewed, 3 unresolved discussions (waiting on @ldorau and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1650#-N-Wb3hS4Vb-r6ENdJ1t:-N0-hdFgEU2PmEPTIBKP:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`/rpma/tests/unit/conn/conn-get_compl_fd.c:61: ERROR: trailing whitespace`
</blockquote></details>

Done.

---
___
*[src/include/librpma.h, line 2169 at r2](https://reviewable.io/reviews/pmem/rpma/1650#-N-c1_-JDCyH9-d_PxHY:-N0-rhiT3xpvWNLIAp8X:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5f50ac2b403ca6232f9737643d0f7aeeceea3f98/src/include/librpma.h#L2169)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Ah, reviewable has moved the comment down, see above ...
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2169 at r5](https://reviewable.io/reviews/pmem/rpma/1650#-N-ck39w27wpPRyXOejb:-N0-rgLt0Sz05iuRgFvT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d117e0dfc62abf95446eb738eed468f862956cf9/src/include/librpma.h#L2169)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

... that comment should be here.
See: https://reviewable.io/reviews/pmem/rpma/1650#-N-c1_-JDCyH9-d_PxHY:-N-c1_-K9_IL3JB0BxNZ:bgqnkk3
</blockquote></details>

Done.

**Review by osalyk — APPROVED** [review]
> Reviewed 9 of 9 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1650)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau and @osalyk)

**Review by ldorau — APPROVED** [review]
> Reviewed 8 of 9 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1650)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by osalyk — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1650#-:-N006YVo5GBubUq0Nd6c:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1650#-:-N006h4K3ACCcrRiS6sN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1650)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[tests/unit/conn/conn-get_compl_fd.c, line 73 at r8](https://reviewable.io/reviews/pmem/rpma/1650#-N0072BUCw7RTfSfdgcb:-N0072BUCw7RTfSfdgcc:b3l3rev) ([raw file](https://github.com/pmem/rpma/blob/508870c270821e8ff2727462e786392ff987d8c5/tests/unit/conn/conn-get_compl_fd.c#L73)):*
> ```C
> 	int ret = rpma_conn_get_compl_fd(cstate->conn, &fd);
> 
> 	/* verify the results */
> ```

Shall we verify also that the fd has not been modified inside ``rpma_conn_get_compl_fd``?



_Code quote:_
```C
verify
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 9 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1650)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1650)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1650)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[tests/unit/conn/conn-get_compl_fd.c, line 73 at r8](https://reviewable.io/reviews/pmem/rpma/1650#-N0072BUCw7RTfSfdgcb:-N00Dcar8kmdaDwSAZo-:b-3vhnk9) ([raw file](https://github.com/pmem/rpma/blob/508870c270821e8ff2727462e786392ff987d8c5/tests/unit/conn/conn-get_compl_fd.c#L73)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Shall we verify also that the fd has not been modified inside ``rpma_conn_get_compl_fd``?
</blockquote></details>

We can, @haichangsi please add everywhere where needed:
```c
assert_int_equal(fd, 0);
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1650)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @grom72, @ldorau, and @osalyk)

___
*[tests/unit/conn/conn-get_compl_fd.c, line 73 at r8](https://reviewable.io/reviews/pmem/rpma/1650#-N0072BUCw7RTfSfdgcb:-N00G56I3e_6en-vSyHd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/508870c270821e8ff2727462e786392ff987d8c5/tests/unit/conn/conn-get_compl_fd.c#L73)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

We can, @haichangsi please add everywhere where needed:
```c
assert_int_equal(fd, 0);
```
</blockquote></details>

Done.

**Review by osalyk — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1650)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1650)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1650#-:-N00I4GICq4oh4lLe8ZT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1650)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
