### PR TITLE
doc: rename peer_cfg get/set functions

### PR DESCRIPTION
**Pull request by janekmi**
aka direct_write_to_pmem

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/399)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/399#-:-MH9p6hk2Da9nUDw64nN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/399#-:-MHA6l4t9mZZpAaVOcIq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/399#-:-MHAIdeaDOkov8IWDNtZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/399)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
