### PR TITLE
test: add a rpma_log_set_get_threshold MT test

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1954)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1954)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi and @osalyk)

___
*[`tests/multithreaded/log/rpma_log_set_get_threshold.c` line 5 at r1](https://reviewable.io/reviews/pmem/rpma/1954#-N7yAvdG9QWCR-6leBlN:-N7yAvdG9QWCR-6leBlO:b18mksr) ([raw file](https://github.com/pmem/rpma/blob/58e25e0bb37f0623e37adcf07991dd570140ae4d/tests/multithreaded/log/rpma_log_set_get_threshold.c#L5)):*
> ```C
> 
> /*
>  * rpma_log_set_get_threshold.c -- rpma_log_set_get_threshold multithreaded test
> ```

multithreaded test of rpma_log_set_threshold + rpma_log_get_threshold



_Code quote:_
```C
rpma_log_set_get_threshold multithreaded test
```
___
*[`tests/multithreaded/log/rpma_log_set_get_threshold.c` line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1954#-N7yAmCe1ibyUoJYrvVa:-N7yAmCe1ibyUoJYrvVb:buypcee) ([raw file](https://github.com/pmem/rpma/blob/58e25e0bb37f0623e37adcf07991dd570140ae4d/tests/multithreaded/log/rpma_log_set_get_threshold.c#L13)):*
> ```C
> 
> /*
>  * thread -- set log function and check if its value is as expected
> ```

threshold



_Code quote:_
```C
log function
```
___
*[`tests/multithreaded/log/rpma_log_set_get_threshold.c` line 32 at r1](https://reviewable.io/reviews/pmem/rpma/1954#-N7yArpR2fCH3bXVw9L1:-N7yArpS5MdOlD2KdSXJ:b-7ncvoh) ([raw file](https://github.com/pmem/rpma/blob/58e25e0bb37f0623e37adcf07991dd570140ae4d/tests/multithreaded/log/rpma_log_set_get_threshold.c#L32)):*
> ```C
> 
> 	if (level != RPMA_LOG_LEVEL_INFO) {
> 		MTT_ERR(tr, "pr->level != RPMA_LOG_LEVEL_INFO", EINVAL);
> ```

level



_Code quote:_
```C
pr->level
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1954)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[`tests/multithreaded/log/rpma_log_set_get_threshold.c` line 5 at r1](https://reviewable.io/reviews/pmem/rpma/1954#-N7yAvdG9QWCR-6leBlN:-N7ybNiv5lYCj-94t619:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/58e25e0bb37f0623e37adcf07991dd570140ae4d/tests/multithreaded/log/rpma_log_set_get_threshold.c#L5)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

multithreaded test of rpma_log_set_threshold + rpma_log_get_threshold
</blockquote></details>

Done.
___
*[`tests/multithreaded/log/rpma_log_set_get_threshold.c` line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1954#-N7yAmCe1ibyUoJYrvVa:-N7ybIIs-10jHjMBxTK8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/58e25e0bb37f0623e37adcf07991dd570140ae4d/tests/multithreaded/log/rpma_log_set_get_threshold.c#L13)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

threshold
</blockquote></details>

Done.
___
*[`tests/multithreaded/log/rpma_log_set_get_threshold.c` line 32 at r1](https://reviewable.io/reviews/pmem/rpma/1954#-N7yArpR2fCH3bXVw9L1:-N7ybGDHDP-EW8h6sKEg:b-ql1cci) ([raw file](https://github.com/pmem/rpma/blob/58e25e0bb37f0623e37adcf07991dd570140ae4d/tests/multithreaded/log/rpma_log_set_get_threshold.c#L32)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

level
</blockquote></details>

it is level

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1954)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi and @osalyk)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/pmem/rpma/1954#-N7z-3Tw72jMPdw8x7WA):*
rpma_log_set_get_threshold MT test



_Code quote:_
```
log_set_get_threshold mtt test
```
___
*[`tests/multithreaded/log/rpma_log_set_get_threshold.c` line 32 at r1](https://reviewable.io/reviews/pmem/rpma/1954#-N7yArpR2fCH3bXVw9L1:-N7z-C6Y1Oyf4vVBaZCn:bd4ft5k) ([raw file](https://github.com/pmem/rpma/blob/58e25e0bb37f0623e37adcf07991dd570140ae4d/tests/multithreaded/log/rpma_log_set_get_threshold.c#L32)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

it is level
</blockquote></details>

But there is no `pr->` - just replace `pr->level` with `level`.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1954)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi and @osalyk)

___
*[`tests/multithreaded/log/rpma_log_set_get_threshold.c` line 5 at r2](https://reviewable.io/reviews/pmem/rpma/1954#-N7z-bY19npBtahUCThU:-N7z-bY19npBtahUCThV:b-anvvaq) ([raw file](https://github.com/pmem/rpma/blob/62bb7cda69d7455d85c995a790f0aa9ef7710b9d/tests/multithreaded/log/rpma_log_set_get_threshold.c#L5)):*
> ```C
> 
> /*
>  * rpma_log_set_get_threshold.c -- multithreaded test of rpma_log_set_threshold + rpma_log_get_threshold
> ```

```
/rpma/tests/multithreaded/log/rpma_log_set_get_threshold.c:5: line > 100 characters
make[2]: *** [tests/CMakeFiles/cstyle-tests-all.dir/build.make:62: cstyle-tests-all-status] Error 1
make[1]: *** [CMakeFiles/Makefile2:826: tests/CMakeFiles/cstyle-tests-all.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```



_Code quote:_
```C
rpma_log_set_get_threshold.c -- multithreaded test of rpma_log_set_threshold + rpma_log_get_threshold
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1954)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/pmem/rpma/1954#-N7z-3Tw72jMPdw8x7WA):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

rpma_log_set_get_threshold MT test
</blockquote></details>

Done.
___
*[`tests/multithreaded/log/rpma_log_set_get_threshold.c` line 32 at r1](https://reviewable.io/reviews/pmem/rpma/1954#-N7yArpR2fCH3bXVw9L1:-N7zBide5aLU5f_3hpe_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/58e25e0bb37f0623e37adcf07991dd570140ae4d/tests/multithreaded/log/rpma_log_set_get_threshold.c#L32)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

But there is no `pr->` - just replace `pr->level` with `level`.
</blockquote></details>

Done.
___
*[`tests/multithreaded/log/rpma_log_set_get_threshold.c` line 5 at r2](https://reviewable.io/reviews/pmem/rpma/1954#-N7z-bY19npBtahUCThU:-N7zARGn05Rp6fZ_TQvn:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/62bb7cda69d7455d85c995a790f0aa9ef7710b9d/tests/multithreaded/log/rpma_log_set_get_threshold.c#L5)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
/rpma/tests/multithreaded/log/rpma_log_set_get_threshold.c:5: line > 100 characters
make[2]: *** [tests/CMakeFiles/cstyle-tests-all.dir/build.make:62: cstyle-tests-all-status] Error 1
make[1]: *** [CMakeFiles/Makefile2:826: tests/CMakeFiles/cstyle-tests-all.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1954)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1954)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1954#-N7zDFhNDJidyxWbXmfa:-N7zDFhNDJidyxWbXmfb:b-ujmq67) (no related file):*
Rebase please

___

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1954)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @ldorau and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1954#-N7zDFhNDJidyxWbXmfa:-N7zED2Z8eFjrDRP5jEc:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Rebase please
</blockquote></details>

Done.

___

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1954)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi and @osalyk)

___
*[`CHANGELOG.md` line 28 at r4](https://reviewable.io/reviews/pmem/rpma/1954#-N7zERn87DWecN54YsXF:-N7zERn92HnEGO3ImY3z:b3xxfkg) ([raw file](https://github.com/pmem/rpma/blob/94b7bd6f446f0596f5aa352a264eae1cb654f819/CHANGELOG.md#L28)):*
> ```Markdown
>   - rpma_conn_req_connect
>   - rpma_ep_next_conn_req
>   - rpma_log_set_function
> ```

```
  - rpma_log_set_function
  - rpma_log_set_get_threshold
  - rpma_log_set_threshold
```



_Code quote:_
```Markdown
  - rpma_log_set_function
  - rpma_log_set_threshold
  - rpma_log_set_get_threshold
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1954)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @ldorau and @osalyk)

___
*[`CHANGELOG.md` line 28 at r4](https://reviewable.io/reviews/pmem/rpma/1954#-N7zERn87DWecN54YsXF:-N7zFAn-6dk3883tAgij:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/94b7bd6f446f0596f5aa352a264eae1cb654f819/CHANGELOG.md#L28)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
  - rpma_log_set_function
  - rpma_log_set_get_threshold
  - rpma_log_set_threshold
```

</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1954)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1954#-:-N7zHJV8-zbmB_ypOrsu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, 1 of 2 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1954#-:-N7zHiAlBvnwEsnuACiU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1954)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
