### PR TITLE
tools: update BENCHMARKING.md and config.json.example

### PR DESCRIPTION
**Pull request by Patryk717**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1522)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1522)* status: all files reviewed, 7 unresolved discussions (waiting on @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1522#-MuUpvNL4KN3IylptHtP:-MuUpvNL4KN3IylptHtQ:b-gl8842) (no related file):*
Please rebase on the current master

---
___
*[tools/perf/BENCHMARKING.md, line 205 at r1](https://reviewable.io/reviews/pmem/rpma/1522#-MuUq67E8VDLvDpxyYdi:-MuUq67E8VDLvDpxyYdj:b-o369um) ([raw file](https://github.com/pmem/rpma/blob/277d27bd9878952fd21b3516bc89351dc2b6ca5f/tools/perf/BENCHMARKING.md#L205)):*
> ```Markdown
> With the help of additional parameters, you can adjust various aspects of the output.
> 
> ## Troubleshooting
> ```

The below procedures I would call rather "Prerequisites for benchmarking".

If you want to have the "Troubleshooting" section you have to define problems first and then give a solution for each of them.



_Code quote:_
```Markdown
## Troubleshooting
```
___
*[tools/perf/BENCHMARKING.md, line 206 at r1](https://reviewable.io/reviews/pmem/rpma/1522#-MuUog26EF6DKKZZHfcq:-MuUog26EF6DKKZZHfcr:b1ah4bm) ([raw file](https://github.com/pmem/rpma/blob/277d27bd9878952fd21b3516bc89351dc2b6ca5f/tools/perf/BENCHMARKING.md#L206)):*
> ```Markdown
> 
> ## Troubleshooting
> Run ssh manually from client to server at least once before report_bench.py is run
> ```

from the client to the server



_Code quote:_
```Markdown
from client to server
```
___
*[tools/perf/BENCHMARKING.md, line 208 at r1](https://reviewable.io/reviews/pmem/rpma/1522#-MuUoXhtAhsZzXAZqKmY:-MuUoXhtAhsZzXAZqKmZ:b2nicir) ([raw file](https://github.com/pmem/rpma/blob/277d27bd9878952fd21b3516bc89351dc2b6ca5f/tools/perf/BENCHMARKING.md#L208)):*
> ```Markdown
> Run ssh manually from client to server at least once before report_bench.py is run
> ``` sh
> $ ./ssh user@192.168.0.1
> ```

ssh



_Code quote:_
```Markdown
./ssh
```
___
*[tools/perf/BENCHMARKING.md, line 208 at r1](https://reviewable.io/reviews/pmem/rpma/1522#-MuUpJhs35JrFYdqAglf:-MuUpJhs35JrFYdqAglg:b-s64c3) ([raw file](https://github.com/pmem/rpma/blob/277d27bd9878952fd21b3516bc89351dc2b6ca5f/tools/perf/BENCHMARKING.md#L208)):*
> ```Markdown
> Run ssh manually from client to server at least once before report_bench.py is run
> ``` sh
> $ ./ssh user@192.168.0.1
> ```

Maybe: `ssh ${REMOTE_USER}@${SERVER_IP}` ?



_Code quote:_
```Markdown
user@192.168.0.1
```
___
*[tools/perf/BENCHMARKING.md, line 212 at r1](https://reviewable.io/reviews/pmem/rpma/1522#-MuUpbYv3mNQd3HiZySF:-MuUpbYv3mNQd3HiZySG:b-28w657) ([raw file](https://github.com/pmem/rpma/blob/277d27bd9878952fd21b3516bc89351dc2b6ca5f/tools/perf/BENCHMARKING.md#L212)):*
> ```Markdown
> Before starting any work, check that you have the correct date in the operating system
> ``` sh
> $ sudo date +%Y%m%d -s "20220128"
> ```

Please give an example with setting date **and time**.



_Code quote:_
```Markdown
sudo date +%Y%m%d -s "20220128"
```
___
*[tools/perf/BENCHMARKING.md, line 216 at r1](https://reviewable.io/reviews/pmem/rpma/1522#-MuUpnX32ChqAjITy5P2:-MuUpnX32ChqAjITy5P3:b-udws82) ([raw file](https://github.com/pmem/rpma/blob/277d27bd9878952fd21b3516bc89351dc2b6ca5f/tools/perf/BENCHMARKING.md#L216)):*
> ```Markdown
> If you have set up fsdax check if the place where it is mounted has adequate access
> ```
> $ sudo chmod 777 /mnt/xxxx
> ```

For DevDAX you have to do the same



_Code quote:_
```Markdown
If you have set up fsdax check if the place where it is mounted has adequate access
```
$ sudo chmod 777 /mnt/xxxx
```


<!-- Sent from Reviewable.io -->

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1522)* status: all files reviewed, 8 unresolved discussions (waiting on @Patryk717)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1522#-MuUrdy14hLiUk6dtheC):*
`tools: update`



_Code quote:_
```
 Tools: Update
```

**Review by Patryk717 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1522)* status: 1 of 2 files reviewed, 8 unresolved discussions (waiting on @ldorau and @Patryk717)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1522#-MuUrdy14hLiUk6dtheC):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`tools: update`
</blockquote></details>

Done.
___
*[tools/perf/BENCHMARKING.md, line 205 at r1](https://reviewable.io/reviews/pmem/rpma/1522#-MuUq67E8VDLvDpxyYdi:-MuUwpix1moEi5MjkPwk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/277d27bd9878952fd21b3516bc89351dc2b6ca5f/tools/perf/BENCHMARKING.md#L205)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The below procedures I would call rather "Prerequisites for benchmarking".

If you want to have the "Troubleshooting" section you have to define problems first and then give a solution for each of them.
</blockquote></details>

Done.
___
*[tools/perf/BENCHMARKING.md, line 206 at r1](https://reviewable.io/reviews/pmem/rpma/1522#-MuUog26EF6DKKZZHfcq:-MuUxArj-kLfdj5J67wD:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/277d27bd9878952fd21b3516bc89351dc2b6ca5f/tools/perf/BENCHMARKING.md#L206)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

from the client to the server
</blockquote></details>

Done.
___
*[tools/perf/BENCHMARKING.md, line 208 at r1](https://reviewable.io/reviews/pmem/rpma/1522#-MuUoXhtAhsZzXAZqKmY:-MuUxn3b0JYjM0DLtlwB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/277d27bd9878952fd21b3516bc89351dc2b6ca5f/tools/perf/BENCHMARKING.md#L208)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

ssh
</blockquote></details>

Done.
___
*[tools/perf/BENCHMARKING.md, line 208 at r1](https://reviewable.io/reviews/pmem/rpma/1522#-MuUpJhs35JrFYdqAglf:-MuUyKdIBgtUBcujUlgW:b7aok2o) ([raw file](https://github.com/pmem/rpma/blob/277d27bd9878952fd21b3516bc89351dc2b6ca5f/tools/perf/BENCHMARKING.md#L208)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Maybe: `ssh ${REMOTE_USER}@${SERVER_IP}` ?
</blockquote></details>

good done
___
*[tools/perf/BENCHMARKING.md, line 212 at r1](https://reviewable.io/reviews/pmem/rpma/1522#-MuUpbYv3mNQd3HiZySF:-MuV30IIEjpbnVMgpfns:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/277d27bd9878952fd21b3516bc89351dc2b6ca5f/tools/perf/BENCHMARKING.md#L212)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please give an example with setting date **and time**.
</blockquote></details>

Done.
___
*[tools/perf/BENCHMARKING.md, line 216 at r1](https://reviewable.io/reviews/pmem/rpma/1522#-MuUpnX32ChqAjITy5P2:-MuV3G_REU2yw3QbLX6p:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/277d27bd9878952fd21b3516bc89351dc2b6ca5f/tools/perf/BENCHMARKING.md#L216)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

For DevDAX you have to do the same
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1522)* status: all files reviewed, 4 unresolved discussions (waiting on @Patryk717)

___
*[tools/perf/config.json.example, line 4 at r3](https://reviewable.io/reviews/pmem/rpma/1522#-MuVGK6s6rx5SM8i3HE-:-MuVGK6s6rx5SM8i3HE0:b-hrx5b4) ([raw file](https://github.com/pmem/rpma/blob/bb647fa0dc8d39b12fe730f095ded44a297370c0/tools/perf/config.json.example#L4)):*
> ```
>     "_comment": "A configuration file providing all information describing the system which are necessary to run ./rpma_fio_bench.sh and ./ib_read.sh.",
>     "platform_generation": "Cascade Lake/Ice Lake",
>     "server_ip": "XXX.XXX.XXX.XXX",
> ```

Those lines should not be changed, please revert.



_Code quote:_
```
    "_comment": "A configuration file providing all information describing the system which are necessary to run ./rpma_fio_bench.sh and ./ib_read.sh.",
    "platform_generation": "Cascade Lake/Ice Lake",
    "server_ip": "XXX.XXX.XXX.XXX",
```
___
*[tools/perf/config.json.example, line 12 at r3](https://reviewable.io/reviews/pmem/rpma/1522#-MuVGNve25QynAE-K_6L:-MuVGNve25QynAE-K_6M:bpmxn3u) ([raw file](https://github.com/pmem/rpma/blob/bb647fa0dc8d39b12fe730f095ded44a297370c0/tools/perf/config.json.example#L12)):*
> ```
>     "REMOTE_AUX_PARAMS": "-d XXX -R",
>     "REMOTE_DIRECT_WRITE_TO_PMEM": false,
>     "REMOTE_JOB_MEM_PATH": "path"
> ```

This line should not be changed, please revert the original version.



_Code quote:_
```
"REMOTE_JOB_MEM_PATH": "path"
```
___
*[tools/perf/config.json.example, line 14 at r3](https://reviewable.io/reviews/pmem/rpma/1522#-MuVGbuV2en3bKj5UfBM:-MuVGbuV2en3bKj5UfBN:bqsg2n4) ([raw file](https://github.com/pmem/rpma/blob/bb647fa0dc8d39b12fe730f095ded44a297370c0/tools/perf/config.json.example#L14)):*
> ```
>     "REMOTE_JOB_MEM_PATH": "path"
> }
> ```

Please add one empty line at the end.

**Review by Patryk717 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1522)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1522#-MuUpvNL4KN3IylptHtP:-MuVDZFX3O_UoJuXZeYl:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please rebase on the current master
</blockquote></details>

Done.

---
___
*[tools/perf/config.json.example, line 4 at r3](https://reviewable.io/reviews/pmem/rpma/1522#-MuVGK6s6rx5SM8i3HE-:-MuVIkNVBF_lpgl1kvTq:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bb647fa0dc8d39b12fe730f095ded44a297370c0/tools/perf/config.json.example#L4)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Those lines should not be changed, please revert.
</blockquote></details>

Done.
___
*[tools/perf/config.json.example, line 12 at r3](https://reviewable.io/reviews/pmem/rpma/1522#-MuVGNve25QynAE-K_6L:-MuVKEjU72Ea21_a5kpi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bb647fa0dc8d39b12fe730f095ded44a297370c0/tools/perf/config.json.example#L12)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

This line should not be changed, please revert the original version.
</blockquote></details>

Done.
___
*[tools/perf/config.json.example, line 14 at r3](https://reviewable.io/reviews/pmem/rpma/1522#-MuVGbuV2en3bKj5UfBM:-MuVKEXM-KJvPiQvX84_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bb647fa0dc8d39b12fe730f095ded44a297370c0/tools/perf/config.json.example#L14)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please add one empty line at the end.
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1522)* status: all files reviewed, 1 unresolved discussion (waiting on @Patryk717)

___
*[tools/perf/config.json.example, line 14 at r3](https://reviewable.io/reviews/pmem/rpma/1522#-MuVGbuV2en3bKj5UfBM:-MuVT32a0yx1P14Qdthx:b-jv9l2b) ([raw file](https://github.com/pmem/rpma/blob/bb647fa0dc8d39b12fe730f095ded44a297370c0/tools/perf/config.json.example#L14)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet, there is still a red sign here at the bottom of this file.

**Review by Patryk717 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1522)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/config.json.example, line 14 at r3](https://reviewable.io/reviews/pmem/rpma/1522#-MuVGbuV2en3bKj5UfBM:-MuVZQTeECJX4zIOO2sD:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bb647fa0dc8d39b12fe730f095ded44a297370c0/tools/perf/config.json.example#L14)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not yet, there is still a red sign here at the bottom of this file.
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1522)* status: all files reviewed, 1 unresolved discussion (waiting on @Patryk717)

___
*[tools/perf/BENCHMARKING.md, line 167 at r6](https://reviewable.io/reviews/pmem/rpma/1522#-MuVfG7D9H8xGTRJUqja:-MuVfG7D9H8xGTRJUqjb:b-iarzai) ([raw file](https://github.com/pmem/rpma/blob/a6e78f2bf56a62845baa341e34ff480464798a66/tools/perf/BENCHMARKING.md#L167)):*
> ```Markdown
> $ sudo chmod 777 /mnt/pmem0 
> $ sudo chmod 666 /dev/dax0.0
> ```
> ```

There is also one empty line missing at the end of this file (see a red mark).

**Review by Patryk717 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1522)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/BENCHMARKING.md, line 167 at r6](https://reviewable.io/reviews/pmem/rpma/1522#-MuVfG7D9H8xGTRJUqja:-MuVg8UZ3KKAwfyhSUnu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a6e78f2bf56a62845baa341e34ff480464798a66/tools/perf/BENCHMARKING.md#L167)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

There is also one empty line missing at the end of this file (see a red mark).
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1522)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)

**Review by haichangsi — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1522#-:-MuhDKy87BVfSvyMrrnS:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1522)* status: all files reviewed, 1 unresolved discussion (waiting on @Patryk717)

___
*[tools/perf/BENCHMARKING.md, line 166 at r7](https://reviewable.io/reviews/pmem/rpma/1522#-Muj-dlg5Vlvt7JWhD0I:-Muj-dlh2s6fFnLyFsIJ:bpfe8el) ([raw file](https://github.com/pmem/rpma/blob/87c1df434bce115cc605c74bf55fb4c4f3dd3c07/tools/perf/BENCHMARKING.md#L166)):*
> ```Markdown
> ``` sh
> $ sudo chmod 777 /mnt/pmem0 
> $ sudo chmod 666 /dev/dax0.0
> ```

@osalyk Do you have any other ideas?



_Code quote:_
```Markdown
## Prerequisites for benchmarking

Run ssh manually from the client to the server at least once before report_bench.py is run:
``` sh
$ ssh ${REMOTE_USER}@${SERVER_IP}
```

Before starting any work, make sure that you have the correct date in the operating system:
``` sh
$ sudo date -s "01/28/2022 10:03:00"
```

If you have set up FsDAX or DevDAX make sure they have RW access:
``` sh
$ sudo chmod 777 /mnt/pmem0
$ sudo chmod 666 /dev/dax0.0
```

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1522)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)

___
*[tools/perf/BENCHMARKING.md, line 166 at r7](https://reviewable.io/reviews/pmem/rpma/1522#-Muj-dlg5Vlvt7JWhD0I:-MujSsik-ya9uhBx0B7R:b-x2lgma) ([raw file](https://github.com/pmem/rpma/blob/87c1df434bce115cc605c74bf55fb4c4f3dd3c07/tools/perf/BENCHMARKING.md#L166)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

I think that's all
</blockquote></details>

OK, so do you accept this change?

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1522)* status: all files reviewed, 1 unresolved discussion (waiting on @Patryk717)

___
*[tools/perf/BENCHMARKING.md, line 163 at r7](https://reviewable.io/reviews/pmem/rpma/1522#-MujTCe-BrdUzlL5aJ9B:-MujTCe-BrdUzlL5aJ9C:bjt55aw) ([raw file](https://github.com/pmem/rpma/blob/87c1df434bce115cc605c74bf55fb4c4f3dd3c07/tools/perf/BENCHMARKING.md#L163)):*
> ```Markdown
> ```
> 
> If you have set up FsDAX or DevDAX make sure they have RW access:
> ```

a user has the RW access to these devices:



_Code quote:_
```Markdown
they have RW access:
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1522)* status: all files reviewed, 1 unresolved discussion (waiting on @Patryk717)

___
*[tools/perf/BENCHMARKING.md, line 163 at r7](https://reviewable.io/reviews/pmem/rpma/1522#-MujTCe-BrdUzlL5aJ9B:-MujTaLy4pZz8BkTRCuX:b8eixh0) ([raw file](https://github.com/pmem/rpma/blob/87c1df434bce115cc605c74bf55fb4c4f3dd3c07/tools/perf/BENCHMARKING.md#L163)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

a user has the RW access to these devices:
</blockquote></details>

or even better:
`you have the RW access to these devices:`

**Review by Patryk717 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1522)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @haichangsi, @ldorau, and @osalyk)

___
*[tools/perf/BENCHMARKING.md, line 163 at r7](https://reviewable.io/reviews/pmem/rpma/1522#-MujTCe-BrdUzlL5aJ9B:-MujUWs34KGyo5DLSBO1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/87c1df434bce115cc605c74bf55fb4c4f3dd3c07/tools/perf/BENCHMARKING.md#L163)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

or even better:
`you have the RW access to these devices:`

</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1522#-:-MujV1A_Ay-5EY6UlHB7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1522#-:-MujXD512OnN-2aRdBn5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)

___
*[tools/perf/BENCHMARKING.md, line 166 at r7](https://reviewable.io/reviews/pmem/rpma/1522#-Muj-dlg5Vlvt7JWhD0I:-MujX6jfDugc7K7Z5c_G:b2nhswy) ([raw file](https://github.com/pmem/rpma/blob/87c1df434bce115cc605c74bf55fb4c4f3dd3c07/tools/perf/BENCHMARKING.md#L166)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK, so do you accept this change?
</blockquote></details>

Yes

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1522)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1522)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)

**Pull request merged**
