### PR TITLE
examples: fix the 07-atomic-write example

### PR DESCRIPTION
**Pull request by osalyk**
based on #982

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/998)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/998#-:-MYIoEIf4s5V3iI5Cr6K:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/998)* status: all files reviewed, 5 unresolved discussions (waiting on @osalyk)

___
*[examples/07-atomic-write/client.c, line 112 at r1](https://reviewable.io/reviews/pmem/rpma/998#-MYK6mK2DrGKdlLA7F0g:-MYK6mK2DrGKdlLA7F0h:bfksp12) ([raw file](https://github.com/pmem/rpma/blob/4f57c6f85ae24c7a11083c233a31427ee5478fc8/examples/07-atomic-write/client.c#L112)):*
> ```C
> 		goto err_mr_remote_delete;
> 
> 	/* wait for the completion to be ready */
> ```

`/* try to get a completion */`
___
*[examples/07-atomic-write/client.c, line 117 at r1](https://reviewable.io/reviews/pmem/rpma/998#-MYK6z4a1vG6z8HZRkaF:-MYK6z4a1vG6z8HZRkaG:bd0iyp5) ([raw file](https://github.com/pmem/rpma/blob/4f57c6f85ae24c7a11083c233a31427ee5478fc8/examples/07-atomic-write/client.c#L117)):*
> ```C
> 		goto err_mr_remote_delete;
> 
> 	if (ret == RPMA_E_NO_COMPLETION) {
> ```

`/* wait for the completion to be ready */`
___
*[examples/07-atomic-write/client.c, line 179 at r1](https://reviewable.io/reviews/pmem/rpma/998#-MYK777k7VJ4_4YtU3cU:-MYK777k7VJ4_4YtU3cV:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/4f57c6f85ae24c7a11083c233a31427ee5478fc8/examples/07-atomic-write/client.c#L179)):*
> ```C
> 			break;
> 
> 		/* wait for the completion to be ready */
> ```

.
___
*[examples/07-atomic-write/client.c, line 184 at r1](https://reviewable.io/reviews/pmem/rpma/998#-MYK7AR97QcdqpUuASls:-MYK7ARA2XKRg6WAuI9E:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/4f57c6f85ae24c7a11083c233a31427ee5478fc8/examples/07-atomic-write/client.c#L184)):*
> ```C
> 			break;
> 
> 		if (ret == RPMA_E_NO_COMPLETION) {
> ```

.
___
*[examples/07-atomic-write/client.c, line 192 at r1](https://reviewable.io/reviews/pmem/rpma/998#-MYK7mZV6CTR86j6SMFc:-MYK7mZV6CTR86j6SMFd:buinbll) ([raw file](https://github.com/pmem/rpma/blob/4f57c6f85ae24c7a11083c233a31427ee5478fc8/examples/07-atomic-write/client.c#L192)):*
> ```C
> 					continue;
> 				break;
> 			}
> ```

I think we can not continue without completion. Prove me wrong. ;-)

```c
if ((ret = rpma_conn_completion_wait(conn)))
    break;
else if ((ret = rpma_conn_completion_get(conn, &cmpl)))
    break;
```

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/998)* status: all files reviewed, 5 unresolved discussions (waiting on @osalyk)

___
*[examples/07-atomic-write/client.c, line 192 at r1](https://reviewable.io/reviews/pmem/rpma/998#-MYK7mZV6CTR86j6SMFc:-MYK80pi1rbqZJnS5STA:bf7zd44) ([raw file](https://github.com/pmem/rpma/blob/4f57c6f85ae24c7a11083c233a31427ee5478fc8/examples/07-atomic-write/client.c#L192)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we can not continue without completion. Prove me wrong. ;-)

```c
if ((ret = rpma_conn_completion_wait(conn)))
    break;
else if ((ret = rpma_conn_completion_get(conn, &cmpl)))
    break;
```
</blockquote></details>

It was different for #982 since there at the beginning of the loop was another attempt to collect a completion. Whereas here by continuing we agree to write another chunk of data. We can no afford it.

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/998)* status: all files reviewed, 5 unresolved discussions (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/998)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[examples/07-atomic-write/client.c, line 112 at r1](https://reviewable.io/reviews/pmem/rpma/998#-MYK6mK2DrGKdlLA7F0g:-MYK91_m-36aGtBLNy5d:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4f57c6f85ae24c7a11083c233a31427ee5478fc8/examples/07-atomic-write/client.c#L112)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`/* try to get a completion */`
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 117 at r1](https://reviewable.io/reviews/pmem/rpma/998#-MYK6z4a1vG6z8HZRkaF:-MYK9CBx0eRp7L6HnaJR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4f57c6f85ae24c7a11083c233a31427ee5478fc8/examples/07-atomic-write/client.c#L117)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`/* wait for the completion to be ready */`
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 179 at r1](https://reviewable.io/reviews/pmem/rpma/998#-MYK777k7VJ4_4YtU3cU:-MYK9INY6ChFKj7o4Kbv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4f57c6f85ae24c7a11083c233a31427ee5478fc8/examples/07-atomic-write/client.c#L179)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 184 at r1](https://reviewable.io/reviews/pmem/rpma/998#-MYK7AR97QcdqpUuASls:-MYK9KZq2VINlkT1tUXd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4f57c6f85ae24c7a11083c233a31427ee5478fc8/examples/07-atomic-write/client.c#L184)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 192 at r1](https://reviewable.io/reviews/pmem/rpma/998#-MYK7mZV6CTR86j6SMFc:-MYK9pEd70er0mt_QyeO:bh95ke4) ([raw file](https://github.com/pmem/rpma/blob/4f57c6f85ae24c7a11083c233a31427ee5478fc8/examples/07-atomic-write/client.c#L192)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It was different for #982 since there at the beginning of the loop was another attempt to collect a completion. Whereas here by continuing we agree to write another chunk of data. We can no afford it.
</blockquote></details>

You're right

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/998#-:-MYKCZrT8z49Pg6rcjvk:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/998#-:-MYKSp3y5V_4okHkv_AU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
