### PR TITLE
common: upgrade Fedora and Ubuntu OSes in per-PR CI builds

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1259)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1259#-:-MifPDztCrVmljCdvFmS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1259#-:-MitoaWo6Vw9Uw7Wz5-e:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1259)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1259#-MitpCEXC3Zc7yclKiwE:-MitpCEYBbVm9FQgOe0x:bamvrb0) (no related file):*
Can we upgrade also the Debian release?

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1259)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1259#-MitpCEXC3Zc7yclKiwE:-Mitq00w82goSqY4xDSo:b34s2qr) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Can we upgrade also the Debian release?
</blockquote></details>

We have Debian 9 on purpose:
```
# Debian 9 has older Python v3.5.3 (and pylint3 v1.6.5)
```

---

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1259)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1259#-MitpCEXC3Zc7yclKiwE:-MituIPI4_B0heA07ads:b6zrrk4) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

We have Debian 9 on purpose:
```
# Debian 9 has older Python v3.5.3 (and pylint3 v1.6.5)
```

</blockquote></details>

Good catch!

---

**Pull request merged**
