### PR TITLE
tools: introduce SHORT_RUNTIME for ib_read.sh

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/797)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/797)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/ib_read.sh, line 38 at r1](https://reviewable.io/reviews/pmem/rpma/797#-MS6uK969em0KBIrZPwm:-MS6uK969em0KBIrZPwn:btj3ow7) ([raw file](https://github.com/pmem/rpma/blob/19ac61437a56b7cc8759172fa3fde8fecd0f6dfd/tools/ib_read.sh#L38)):*
> ```Shell
> 	echo "export REMOTE_IB_PATH=/custom/ib tool/path/"
> 	echo "Debug:"
> 	echo "export SHORT_RUNTIME=0 (adequate for functional verification only)"
> ```

SHORT_RUNTIME=1 ?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/797)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/ib_read.sh, line 38 at r1](https://reviewable.io/reviews/pmem/rpma/797#-MS6uK969em0KBIrZPwm:-MS77u5A-ykz-Jjaji-g:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/19ac61437a56b7cc8759172fa3fde8fecd0f6dfd/tools/ib_read.sh#L38)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

SHORT_RUNTIME=1 ?
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/797#-:-MS78WEiAZ6XTLOZipN_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/797#-:-MS7AVWS4W9fQwm61kjj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
