### PR TITLE
common: update version of Docker images to 0.9.0

### PR DESCRIPTION
**Pull request by ldorau**
Introduce the IMG_VER variable containing a version
of the Docker images and update the version from 0.1 to 0.9.0.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/553)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/553)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/553)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[utils/docker/images/set-images-version.sh, line 16 at r2](https://reviewable.io/reviews/pmem/rpma/553#-MKjxxJt9JY02a2irBeZ:-MKjxxJt9JY02a2irBe_:b1c29o8) ([raw file](https://github.com/pmem/rpma/blob/736cdecb828ba95194640db42a1a687f677b1055/utils/docker/images/set-images-version.sh#L16)):*
> ```Shell
> #
> 
> export IMG_VER=0.9.0
> ```

Why not use some version of `git describe` with and dropping of the tail?
Is it possible?

I do not like the idea of having a file with a hardcoded version since it seems we should keep them separate for each release?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/553)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[utils/docker/images/set-images-version.sh, line 16 at r2](https://reviewable.io/reviews/pmem/rpma/553#-MKjxxJt9JY02a2irBeZ:-MKl45xj7glyKyfwWqym:b-r7mkkk) ([raw file](https://github.com/pmem/rpma/blob/736cdecb828ba95194640db42a1a687f677b1055/utils/docker/images/set-images-version.sh#L16)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Why not use some version of `git describe` with and dropping of the tail?
Is it possible?

I do not like the idea of having a file with a hardcoded version since it seems we should keep them separate for each release?
</blockquote></details>

This is NOT possible for the following two reasons:

1) The change of `IMG_VER` should trigger the rebuild of all docker images, but the rebuild can be triggered only but modifying certain files.
2) Only dropping the tail is not enough - the master branch and the last stable branch would have the same value of `IMG_VER`. Something would have to be added to `IMG_VER` of the master branch, but the 1) obstacle is still valid.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/553)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[utils/docker/images/set-images-version.sh, line 16 at r2](https://reviewable.io/reviews/pmem/rpma/553#-MKjxxJt9JY02a2irBeZ:-MKn6Hq587UthJYXg5PB:b-3ldc3s) ([raw file](https://github.com/pmem/rpma/blob/736cdecb828ba95194640db42a1a687f677b1055/utils/docker/images/set-images-version.sh#L16)):*
> I do not like the idea of having a file with a hardcoded version since it seems we should keep them separate for each release?

Every branch (master and stable-*) would have only one its own file with its version.

**Comment by ldorau** [comment]
Requires:
- [ ] #547

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/553#-:-MKt-4C5DTouBTwiNv-z:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/553#-:-MKt4HoE9nt7sViet8xd:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
