### PR TITLE
tools: add more information to dump files

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1151)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1151)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1151#-Mf7mO1K4Bk3p5nvQfjS:-Mf7mO1K4Bk3p5nvQfjT:bp5m7kj) (no related file):*
This patch is making the output even more crowded than it is so far, isn't it?

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1151)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1151#-Mf7mO1K4Bk3p5nvQfjS:-Mf7uCSv2gZCyXoSCh-X:b-yn82w3) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This patch is making the output even more crowded than it is so far, isn't it?
</blockquote></details>

IMHO it makes it clear at last. So far I didn't know what is going on in it. DUMP_CMDS isn't dumping commands but files even without printing their names.

---

**Review by osalyk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1151)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1151)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1151#-Mf7mO1K4Bk3p5nvQfjS:-MfYXRf56_a2l9MFpZuw:brv95n6) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

IMHO it makes it clear at last. So far I didn't know what is going on in it. DUMP_CMDS isn't dumping commands but files even without printing their names.
</blockquote></details>

Please paste here an example of how the effect will effectively look like.

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1151)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1151#-Mf7mO1K4Bk3p5nvQfjS:-MfaYk9357Tb7AFjCDCD:b4d7j08) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please paste here an example of how the effect will effectively look like.
</blockquote></details>

Before:

```
[global]
ioengine=librpma_apm_client
create_serialize=0 # (required) forces specific initiation sequence
serverip=192.168.1.100
port=7204
thread
disable_clat=1
lat_percentiles=1
percentile_list=99.0:99.9:99.99:99.999


[client]
sync=0
numjobs=1
group_reporting=1
iodepth=2
readwrite=rw
rwmixread=70 # valid only for the 'rw' and 'randrw' readwrite modes
blocksize=256
ramp_time=15
time_based
runtime=60
---
[global]
ioengine=librpma_apm_client
create_serialize=0 # (required) forces specific initiation sequence
serverip=192.168.1.100
port=7204
thread
disable_clat=1
lat_percentiles=1
percentile_list=99.0:99.9:99.99:99.999
....
```

After:

```
Command:
$ serverip=192.168.1.100 blocksize=256 sync=0 numjobs=1 iodepth=2                       readwrite=rw ramp_time=15 runtime=60  fio  --section server >> rpma_fio_apm_busy-wait_rw_bw-bs_th1_dp2_dram-21-07-27-080426-errors.log 2>&1

Fio job file (./fio_jobs/librpma_apm-client.fio):
[global]
ioengine=librpma_apm_client
create_serialize=0 # (required) forces specific initiation sequence
serverip=192.168.1.100
port=7204
thread
disable_clat=1
lat_percentiles=1
percentile_list=99.0:99.9:99.99:99.999


[client]
sync=0
numjobs=1
group_reporting=1
iodepth=2
readwrite=rw
rwmixread=70 # valid only for the 'rw' and 'randrw' readwrite modes
blocksize=256
ramp_time=15
time_based
runtime=60
---
Command:
$ serverip=192.168.1.100 blocksize=1024 sync=0 numjobs=1 iodepth=2                      readwrite=rw ramp_time=15 runtime=60  fio  --section server >> rpma_fio_apm_busy-wait_rw_bw-bs_th1_dp2_dram-21-07-27-080426-errors.log 2>&1

Fio job file (./fio_jobs/librpma_apm-client.fio):
[global]
ioengine=librpma_apm_client
create_serialize=0 # (required) forces specific initiation sequence
serverip=192.168.1.100
port=7204
thread
disable_clat=1
lat_percentiles=1
percentile_list=99.0:99.9:99.99:99.999
...
```

---

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1151)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/rpma_fio_bench.sh, line 300 at r2](https://reviewable.io/reviews/pmem/rpma/1151#-MgP_9e49ILnJnswQyZc:-MgP_9e49ILnJnswQyZd:b-z1adde) ([raw file](https://github.com/pmem/rpma/blob/e087648475877e1a719c75302225e6837caac3d4/tools/perf/rpma_fio_bench.sh#L300)):*
> ```Shell
> 			sshpass -p "$REMOTE_PASS" -v ssh -o StrictHostKeyChecking=no \
> 				$REMOTE_USER@$SERVER_IP "$ENV $REMOTE_TRACER \
> 				${REMOTE_FIO_PATH}fio $REMOTE_JOB_PATH $FILE_NAME $FILTER >> $LOG_ERR 2>&1" 2>>$LOG_ERR &
> ```

I do not like the idea of having two copies of this line. Since in both cases it is only a string, I think we can build it before the if-statement and either run it or dump it.
___
*[tools/perf/rpma_fio_bench.sh, line 306 at r2](https://reviewable.io/reviews/pmem/rpma/1151#-MgPemHw7px_BCUzF011:-MgPemHw7px_BCUzF012:b-t8jmou) ([raw file](https://github.com/pmem/rpma/blob/e087648475877e1a719c75302225e6837caac3d4/tools/perf/rpma_fio_bench.sh#L306)):*
> ```Shell
> 			echo >> $SERVER_DUMP
> 			echo "Fio job file (./fio_jobs/librpma_${PERSIST_MODE}-server.fio):" >> $SERVER_DUMP
> 			bash -c "cat ./fio_jobs/librpma_${PERSIST_MODE}-server.fio | \
> ```

I'm thinking about why this path is built manually? :thinking: 
___
*[tools/perf/rpma_fio_bench.sh, line 342 at r2](https://reviewable.io/reviews/pmem/rpma/1151#-MgPf0pi6l28uuk4qkjd:-MgPf0pi6l28uuk4qkje:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/e087648475877e1a719c75302225e6837caac3d4/tools/perf/rpma_fio_bench.sh#L342)):*
> ```Shell
> 		elif [ "$DUMP_CMDS" == "1" ]; then
> 			echo "Command:" >> $CLIENT_DUMP
> 			echo "$ $ENV $REMOTE_TRACER ${REMOTE_FIO_PATH}fio $REMOTE_JOB_PATH $FILTER >> $LOG_ERR 2>&1" >> $CLIENT_DUMP
> ```

.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1151)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/rpma_fio_bench.sh, line 300 at r2](https://reviewable.io/reviews/pmem/rpma/1151#-MgP_9e49ILnJnswQyZc:-MhSLVcq06_ptqbJIU77:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e087648475877e1a719c75302225e6837caac3d4/tools/perf/rpma_fio_bench.sh#L300)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I do not like the idea of having two copies of this line. Since in both cases it is only a string, I think we can build it before the if-statement and either run it or dump it.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 306 at r2](https://reviewable.io/reviews/pmem/rpma/1151#-MgPemHw7px_BCUzF011:-MhSLY1_7Y-f8RR-chOk:bfmgtzq) ([raw file](https://github.com/pmem/rpma/blob/e087648475877e1a719c75302225e6837caac3d4/tools/perf/rpma_fio_bench.sh#L306)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I'm thinking about why this path is built manually? :thinking: 
</blockquote></details>

In order to substitute the variables in the file with the variables from $ENV. Anyway it is not a part of this PR.
___
*[tools/perf/rpma_fio_bench.sh, line 342 at r2](https://reviewable.io/reviews/pmem/rpma/1151#-MgPf0pi6l28uuk4qkjd:-MhSLXEi7nAeB0GGKkeU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e087648475877e1a719c75302225e6837caac3d4/tools/perf/rpma_fio_bench.sh#L342)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1151#-:-Mhn2xNpB5Q8JkiMZrTp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
