### PR TITLE
tools: add target description

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1233)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1233)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/report.json.example, line 54 at r1](https://reviewable.io/reviews/pmem/rpma/1233#-MiMXWBq1MYBSgROJym3:-MiMXWBq1MYBSgROJym4:b-i7x2xi) ([raw file](https://github.com/pmem/rpma/blob/e870c86ef513dc5fb513a5f802d123378cf8381d/tools/perf/report.json.example#L54)):*
> ```
>             ]
>         },
>         "target_description" :
> ```

I do not like creating a structure this way. I think you should instead try to change the structure:

```json
"target": {
    "description": "...",
    "details": {
        "Repository": [
...
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1233)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[tools/perf/report.json.example, line 54 at r1](https://reviewable.io/reviews/pmem/rpma/1233#-MiMXWBq1MYBSgROJym3:-MiQFJPOD0pu9XbpsasU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e870c86ef513dc5fb513a5f802d123378cf8381d/tools/perf/report.json.example#L54)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I do not like creating a structure this way. I think you should instead try to change the structure:

```json
"target": {
    "description": "...",
    "details": {
        "Repository": [
...
```
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1233)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1233#-:-MiQ_ABm7RwVBE9uJEOV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1233)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
