### PR TITLE
test: update suppressions of rpma_get_timestamp_prefix

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1858)

### CODE REVIEW

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1858#-:-N5EM82j-OK3PDVsrsmC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1858)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[`tests/drd.supp` line 102 at r1](https://reviewable.io/reviews/pmem/rpma/1858#-N5EvrTL1Hxo21amoKzG:-N5EvrTL1Hxo21amoKzH:btkf0e8) ([raw file](https://github.com/pmem/rpma/blob/9ba65978f2051bd263ae4e99bb6760774bb82632/tests/drd.supp#L102)):*
> ```
>    ...
>    fun:__tz_convert
>    ...
> ```

What line in rpma_log_default_function do we call __tz_convert directly?



_Suggestion:_
```
fun:rpma_get_timestamp_prefix
```
___
*[`tests/helgrind.supp` line 102 at r1](https://reviewable.io/reviews/pmem/rpma/1858#-N5EwAU7A8ObiorNC-UL:-N5EwAU7A8ObiorNC-UM:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/9ba65978f2051bd263ae4e99bb6760774bb82632/tests/helgrind.supp#L102)):*
> ```
>    ...
>    fun:__tz_convert
>    ...
> ```

.



_Suggestion:_
```
fun:rpma_get_timestamp_prefix
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1858)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[`tests/drd.supp` line 102 at r1](https://reviewable.io/reviews/pmem/rpma/1858#-N5EvrTL1Hxo21amoKzG:-N5Ey23d3b5Ctrjr85Cr:bb710wt) ([raw file](https://github.com/pmem/rpma/blob/9ba65978f2051bd263ae4e99bb6760774bb82632/tests/drd.supp#L102)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

What line in rpma_log_default_function do we call __tz_convert directly?
</blockquote></details>

None
___
*[`tests/helgrind.supp` line 102 at r1](https://reviewable.io/reviews/pmem/rpma/1858#-N5EwAU7A8ObiorNC-UL:-N5Ey4GP8JIt1Pe1fAsP:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/9ba65978f2051bd263ae4e99bb6760774bb82632/tests/helgrind.supp#L102)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

.

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1858#-:-N5F-3ze3vHkndiRFrTE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
