### PR TITLE
examples: add void for functions ignoring the return value

### PR DESCRIPTION
**Pull request by yangx-jy**
Signed-off-by: Xiao Yang <yangx.jy@cn.fujitsu.com>

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/874)

### CODE REVIEW

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/874#-:-MTBgS877mEHGVV-Ewoc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/874)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[examples/10-send-with-imm/client.c, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/874#-MTEpzQnCpvjhWAzigq6:-MTEpzQoCuiup-_0yC8w:b-7k8v93) ([raw file](https://github.com/pmem/rpma/blob/8a446e5a53ae6cec1eaf4fc0d760621d8ab50ecd/examples/10-send-with-imm/client.c#L2)):*
> ```C
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright (c) 2020 Fujitsu */
> ```

2020-2021

**Review by yangx-jy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/874)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @janekmi and @osalyk)

___
*[examples/10-send-with-imm/client.c, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/874#-MTEpzQnCpvjhWAzigq6:-MTFdkLA0di6-FJvXEGs:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8a446e5a53ae6cec1eaf4fc0d760621d8ab50ecd/examples/10-send-with-imm/client.c#L2)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

2020-2021
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/874#-:-MTFo-o1DKrBEQplu8Kg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/874#-:-MTFxtblE4maZPx-PhmD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Pull request merged**
