### PR TITLE
examples: fix error: 'for' loop initial declarations are only allowed…

### PR DESCRIPTION
**Pull request by ldorau**
Add the '-std=gnu99' flag to fix the following error:
```
/rpma/examples/06-multiple-connections/server.c: In function 'client_new':
/rpma/examples/06-multiple-connections/server.c:118:2: error: 'for' loop initial declarations are only allowed in C99 mode
  for (int i = 0; i < CLIENT_MAX; ++i) {
  ^
```

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/359)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/359#-:-MGOXZcY4koJ2cR-MNIK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/359#-:-MGbSPrD72G_eUE53oS7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
Rebased

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/359#-:-MGh_EAI4YoKgLsm7SJZ:b9x2p3v)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/359)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by ldorau** [comment]
@janekmi ping, it is an important fix

**Pull request merged**
