### PR TITLE
tools: document how to gain ib tools and fio benchmark

### PR DESCRIPTION
**Pull request by yangx-jy**
Signed-off-by: Xiao Yang <yangx.jy@cn.fujitsu.com>

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/714)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/714)* status: all files reviewed, 3 unresolved discussions (waiting on @yangx-jy)

___
*[tools/BENCHMARKING.md, line 27 at r1](https://reviewable.io/reviews/pmem/rpma/714#-MQCXvCuE4HYa6B-AsKR:-MQCXvCv-fCBSHCpj5B8:b4gr62c) ([raw file](https://github.com/pmem/rpma/blob/5c22eab448aaab30970aa85dd3fc853077f58cbd/tools/BENCHMARKING.md#L27)):*
> ```
> $ make install
> ```

`$ sudo make install`
___
*[tools/BENCHMARKING.md, line 35 at r1](https://reviewable.io/reviews/pmem/rpma/714#-MQCXzgbEoTkJ94CSjXF:-MQCXzgbEoTkJ94CSjXG:b4gr62c) ([raw file](https://github.com/pmem/rpma/blob/5c22eab448aaab30970aa85dd3fc853077f58cbd/tools/BENCHMARKING.md#L35)):*
> ```
> $ make install
> ```

`$ sudo make install`
___
*[tools/BENCHMARKING.md, line 40 at r1](https://reviewable.io/reviews/pmem/rpma/714#-MQCY90j4VZJstacbEMk:-MQCY90j4VZJstacbEMl:b-iiwa9l) ([raw file](https://github.com/pmem/rpma/blob/5c22eab448aaab30970aa85dd3fc853077f58cbd/tools/BENCHMARKING.md#L40)):*
> ```
> package doesn't 
> ```

`packages don't` (there are many fio packages for different distros)

**Review by yangx-jy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/714)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[tools/BENCHMARKING.md, line 27 at r1](https://reviewable.io/reviews/pmem/rpma/714#-MQCXvCuE4HYa6B-AsKR:-MQFB1zACu-HEg9pTxF6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5c22eab448aaab30970aa85dd3fc853077f58cbd/tools/BENCHMARKING.md#L27)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> $ make install
> ```

`$ sudo make install`
</blockquote></details>

Done.
___
*[tools/BENCHMARKING.md, line 35 at r1](https://reviewable.io/reviews/pmem/rpma/714#-MQCXzgbEoTkJ94CSjXF:-MQFB2rq66U3Qs1JQMtS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5c22eab448aaab30970aa85dd3fc853077f58cbd/tools/BENCHMARKING.md#L35)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> $ make install
> ```

`$ sudo make install`
</blockquote></details>

Done.
___
*[tools/BENCHMARKING.md, line 40 at r1](https://reviewable.io/reviews/pmem/rpma/714#-MQCY90j4VZJstacbEMk:-MQFB3MYA_gS0IkEXr2e:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5c22eab448aaab30970aa85dd3fc853077f58cbd/tools/BENCHMARKING.md#L40)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> package doesn't 
> ```

`packages don't` (there are many fio packages for different distros)
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/714)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[tools/BENCHMARKING.md, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/714#-MQGU5RsBPUwkp7Q_Fu6:-MQGU5Rt4WVkDr6jlzmX:b1gz9r3) ([raw file](https://github.com/pmem/rpma/blob/f07fe8fd170e5879c2f4db05b5ea5cd6e7c3664e/tools/BENCHMARKING.md#L15)):*
> ```
>  - fio
> ```

@janekmi @grom72 Maybe like that ?

```
 - fio (with librpma fio engine from https://github.com/pmem/fio.git)
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/714)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[tools/BENCHMARKING.md, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/714#-MQGU5RsBPUwkp7Q_Fu6:-MQGUzYmDiYGgL0jGV5G:b-ltkbii) ([raw file](https://github.com/pmem/rpma/blob/f07fe8fd170e5879c2f4db05b5ea5cd6e7c3664e/tools/BENCHMARKING.md#L15)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  - fio
> ```

@janekmi @grom72 Maybe like that ?

```
 - fio (with librpma fio engine from https://github.com/pmem/fio.git)
```
</blockquote></details>

Or rather:

```
- fio (with the librpma engine from https://github.com/pmem/fio.git)
```

**Comment by yangx-jy** [comment]
___
*[tools/BENCHMARKING.md, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/714#-MQGU5RsBPUwkp7Q_Fu6:-MQGfTdlDcQ2BiFtv31O:b-m2aigl) ([raw file](https://github.com/pmem/rpma/blob/f07fe8fd170e5879c2f4db05b5ea5cd6e7c3664e/tools/BENCHMARKING.md#L15)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Or rather:

```
- fio (with the librpma engine from https://github.com/pmem/fio.git)
```

</blockquote></details>

Hi @ldorau 
 
How about removing the URL, as below:
- fio (supporting the librpma engine)

Because of the following reasons:
1) fio packages will support the librpma engine in future.
2) Subsequent steps has mentioned the URL.

Best Regards,
Xiao Yang

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/714)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[tools/BENCHMARKING.md, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/714#-MQGU5RsBPUwkp7Q_Fu6:-MQGxmqFD-M_Mh8f7lTP:b-l7ljsk) ([raw file](https://github.com/pmem/rpma/blob/f07fe8fd170e5879c2f4db05b5ea5cd6e7c3664e/tools/BENCHMARKING.md#L15)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi @ldorau 
 
How about removing the URL, as below:
- fio (supporting the librpma engine)

Because of the following reasons:
1) fio packages will support the librpma engine in future.
2) Subsequent steps has mentioned the URL.

Best Regards,
Xiao Yang
</blockquote></details>

So how about that? ;-)

```
 - ...
 - fio (supporting the librpma engine)

*Note*: currently only https://github.com/pmem/fio.git supports the librpma fio engine.

```

and we will remove this Note, when the librpma fio engine will be merged upstream.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/714)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)

___
*[tools/BENCHMARKING.md, line 40 at r2](https://reviewable.io/reviews/pmem/rpma/714#-MQGzPlO2uu0lvFIyL7Z:-MQGzPlO2uu0lvFIyL7_:bvrremw) ([raw file](https://github.com/pmem/rpma/blob/f07fe8fd170e5879c2f4db05b5ea5cd6e7c3664e/tools/BENCHMARKING.md#L40)):*
> ```
> librpma fio engine
> ```

`the librpma fio engine`

**Comment by yangx-jy** [comment]
___
*[tools/BENCHMARKING.md, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/714#-MQGU5RsBPUwkp7Q_Fu6:-MQH7C6F1aUIEJuuU0QK:b-tbc2jn) ([raw file](https://github.com/pmem/rpma/blob/f07fe8fd170e5879c2f4db05b5ea5cd6e7c3664e/tools/BENCHMARKING.md#L15)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

So how about that? ;-)

```
 - ...
 - fio (supporting the librpma engine)

*Note*: currently only https://github.com/pmem/fio.git supports the librpma fio engine.

```

and we will remove this Note, when the librpma fio engine will be merged upstream.
</blockquote></details>

Hi @ldorau 

I have added the similar note after detailed install steps so is it necessary to add above note here?
 - Current fio packages don't support librpma fio engine.

Best Regards,
Xiao Yang

**Comment by yangx-jy** [comment]
___
*[tools/BENCHMARKING.md, line 40 at r2](https://reviewable.io/reviews/pmem/rpma/714#-MQGzPlO2uu0lvFIyL7Z:-MQH97sb2pSicTwWWGbe:b-qz47db) ([raw file](https://github.com/pmem/rpma/blob/f07fe8fd170e5879c2f4db05b5ea5cd6e7c3664e/tools/BENCHMARKING.md#L40)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> librpma fio engine
> ```

`the librpma fio engine`
</blockquote></details>

It is fine to me.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/714)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[tools/BENCHMARKING.md, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/714#-MQGU5RsBPUwkp7Q_Fu6:-MQHJxMr3l3pv1sCRCJD:bobhubz) ([raw file](https://github.com/pmem/rpma/blob/f07fe8fd170e5879c2f4db05b5ea5cd6e7c3664e/tools/BENCHMARKING.md#L15)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi @ldorau 

I have added the similar note after detailed install steps so is it necessary to add above note here?
 - Current fio packages don't support librpma fio engine.

Best Regards,
Xiao Yang 
</blockquote></details>

I would leave this note and remove the note below, because the needed information is what works (and not what does not work).

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/714)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)

___
*[tools/BENCHMARKING.md, line 40 at r2](https://reviewable.io/reviews/pmem/rpma/714#-MQGzPlO2uu0lvFIyL7Z:-MQHKkq9AFJF_uWXgCqB:bip788k) ([raw file](https://github.com/pmem/rpma/blob/f07fe8fd170e5879c2f4db05b5ea5cd6e7c3664e/tools/BENCHMARKING.md#L40)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

It is fine to me.
</blockquote></details>

An info about that will be added above so this change is not needed.

**Comment by yangx-jy** [comment]
___
*[tools/BENCHMARKING.md, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/714#-MQGU5RsBPUwkp7Q_Fu6:-MQHKjIU---Y6SSx3Vxt:bjf71im) ([raw file](https://github.com/pmem/rpma/blob/f07fe8fd170e5879c2f4db05b5ea5cd6e7c3664e/tools/BENCHMARKING.md#L15)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I would leave this note and remove the note below, because the needed information is what works (and not what does not work).
</blockquote></details>

Got it.

I will update the PR soon.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/714)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/714#-:-MQHO24f7TvU3Q7ZstrA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Pull request merged**
