### PR TITLE
examples: use USE_PMEM instead of USE_LIBPMEM in examples 09 and 09s

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1959)

### CODE REVIEW

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1959#-:-N83vzyx4HlnOn2kuwDD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by haichangsi — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1959)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1959#-N842lRZ6jY68T8fNoEz):*
but you didn't change USE_LIBPMEM to USE_PMEM, you added IBV_ADVISE_MR_FLAGS_SUPPORTED



_Code quote:_
```
examples: use USE_PMEM instead of USE_LIBPMEM in examples 09 and 09s
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1959)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1959#-N842lRZ6jY68T8fNoEz):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

but you didn't change USE_LIBPMEM to USE_PMEM, you added IBV_ADVISE_MR_FLAGS_SUPPORTED
</blockquote></details>

I have replaced `USE_LIBPMEM` with `USE_PMEM` in the code - read carefully again. This the most important change. 

The change in the comment is just a cosmetic one.



_Code quote (from examples/09-flush-to-persistent-GPSPM/server.c):_
```C
USE_LIBPMEM
```

**Review by haichangsi — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1959#-:-N848aSc2cBPnZOHUXeE:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1959#-N842lRZ6jY68T8fNoEz):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I have replaced `USE_LIBPMEM` with `USE_PMEM` in the code - read carefully again. This the most important change. 

The change in the comment is just a cosmetic one.
</blockquote></details>

again you are right, sorry, lgtm

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1959)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1959#-N842lRZ6jY68T8fNoEz):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

again you are right, sorry, lgtm
</blockquote></details>

Done.

**Pull request merged**
