### PR TITLE
rpma: set default value of CMAKE_BUILD_TYPE to Release

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1888)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1888)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[`CMakeLists.txt` line 66 at r1](https://reviewable.io/reviews/pmem/rpma/1888#-N5dmqtiAxGIDVZiiqj4:-N5dmqtiAxGIDVZiiqj5:b-bvdun2) ([raw file](https://github.com/pmem/rpma/blob/88eb090ee4a9a97283647840c99107d161fdc352/CMakeLists.txt#L66)):*
> ```CMake
> 	message(STATUS "No build type selected (CMAKE_BUILD_TYPE), defaulting to Release")
> 	set(CMAKE_BUILD_TYPE "Release" CACHE STRING
> 		"Choose the type of build, options are: Debug and Release" FORCE)
> ```

Let's use the ccmake's message:
`Choose the type of build, options are: None Debug Release RelWithDebInfo MinSizeRel ...`



_Code quote:_
```CMake
Choose the type of build, options are: Debug and Release
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1888)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[`CMakeLists.txt` line 66 at r1](https://reviewable.io/reviews/pmem/rpma/1888#-N5dmqtiAxGIDVZiiqj4:-N5dnAq-DqofYOibobIS:b-a9r5o4) ([raw file](https://github.com/pmem/rpma/blob/88eb090ee4a9a97283647840c99107d161fdc352/CMakeLists.txt#L66)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Let's use the ccmake's message:
`Choose the type of build, options are: None Debug Release RelWithDebInfo MinSizeRel ...`
</blockquote></details>

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1888)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

___
*[`CMakeLists.txt` line 63 at r1](https://reviewable.io/reviews/pmem/rpma/1888#-N5dyHRuCmfcXGjG2vhp:-N5dyHRuCmfcXGjG2vhq:b8uib1y) ([raw file](https://github.com/pmem/rpma/blob/88eb090ee4a9a97283647840c99107d161fdc352/CMakeLists.txt#L63)):*
> ```CMake
> 	CACHE STRING "working directory for tests")
> 
> if(NOT CMAKE_BUILD_TYPE)
> ```

Small improvement.



_Suggestion:_
```CMake
set(buildTypes Debug Release)
if(NOT CMAKE_BUILD_TYPE)
	message(STATUS "No build type selected (CMAKE_BUILD_TYPE), defaulting to Release")
	set(CMAKE_BUILD_TYPE "Release" CACHE STRING
		"Choose the type of build, options are: Debug and Release" FORCE)
	set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS ${buildTypes})
endif()
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1888)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`CMakeLists.txt` line 63 at r1](https://reviewable.io/reviews/pmem/rpma/1888#-N5dyHRuCmfcXGjG2vhp:-N5eYSmvEx21iLx-loYT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/88eb090ee4a9a97283647840c99107d161fdc352/CMakeLists.txt#L63)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Small improvement.
</blockquote></details>

Done.
___
*[`CMakeLists.txt` line 66 at r1](https://reviewable.io/reviews/pmem/rpma/1888#-N5dmqtiAxGIDVZiiqj4:-N5eYGqnBFwiCDEO1ibm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/88eb090ee4a9a97283647840c99107d161fdc352/CMakeLists.txt#L66)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>


</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1888)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`CMakeLists.txt` line 63 at r2](https://reviewable.io/reviews/pmem/rpma/1888#-N5ecHSe60iFpSOYiZ59:-N5i3YjNA_Gd-6BgCpCo:b32v57) ([raw file](https://github.com/pmem/rpma/blob/2439d4cdec2dd7359321702fd6ee961ab6297fde/CMakeLists.txt#L63)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It should be: `None Debug Release RelWithDebInfo MinSizeRel` now ...
</blockquote></details>

+1

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1888)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1888)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[`CMakeLists.txt` line 63 at r2](https://reviewable.io/reviews/pmem/rpma/1888#-N5ecHSe60iFpSOYiZ59:-N5j2SDq5BdfhbpsHjLr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2439d4cdec2dd7359321702fd6ee961ab6297fde/CMakeLists.txt#L63)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1888)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1888#-:-N5j60Ox82Z7cgUPX8ET:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1888)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[`CMakeLists.txt` line 63 at r3](https://reviewable.io/reviews/pmem/rpma/1888#-N5j691W4R7QojU3lcC-:-N5j691W4R7QojU3lcC0:bxb8zx9) ([raw file](https://github.com/pmem/rpma/blob/4d5f1264ad607d8de7e5ea0843d979d4e917a1b4/CMakeLists.txt#L63)):*
> ```CMake
> 	CACHE STRING "working directory for tests")
> 
> set(buildTypes None Debug Release RelWithDebInfo MinSizeRel)
> ```

Move this line inside the `if` below, because it is used only there.



_Code quote:_
```CMake
set(buildTypes None Debug Release RelWithDebInfo MinSizeRel)
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1888)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`CMakeLists.txt` line 63 at r3](https://reviewable.io/reviews/pmem/rpma/1888#-N5j691W4R7QojU3lcC-:-N5j79y_7K8hDENl_f3n:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4d5f1264ad607d8de7e5ea0843d979d4e917a1b4/CMakeLists.txt#L63)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Move this line inside the `if` below, because it is used only there.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1888)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by lukaszstolarczuk — COMMENTED** [review]
FYI, we (in pmemstream) go a little bit further and added a check if the type defined by the user is one of the known build types.
This way if the user mistakenly writes e.g. "Debuuuug" they will be informed about an unusual build type (CMake may do something unexpected with unknown build types).

see our CMake:
https://github.com/pmem/pmemstream/blob/master/CMakeLists.txt#L50-L56

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1888#-:-N5jByyECwxz8EChFiab:b-dlitqy)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — APPROVED** [review]
+1

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1888#-:-N5jFH753rDpw2X2aHmZ:b32v57)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1888#-:-N5jIIJV1eljLy621JxF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1888)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1888)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1888)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

___
*[`CMakeLists.txt` line 63 at r3](https://reviewable.io/reviews/pmem/rpma/1888#-N5j691W4R7QojU3lcC-:-N5nksTz2GJ1sEogLuk5:b32w0x) ([raw file](https://github.com/pmem/rpma/blob/4d5f1264ad607d8de7e5ea0843d979d4e917a1b4/CMakeLists.txt#L63)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

I reversed this change.
</blockquote></details>

OK

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1888#-:-N5nlqk907nAPUyfbnO2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
