### PR TITLE
common: add memcheck suppresions

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1882)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1882)* status: 3 of 5 files reviewed, 7 unresolved discussions (waiting on @grom72 and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1882#-N5_9G0M2_jyMdyjzyDo:-N5_9G0M2_jyMdyjzyDp:b675ez4) (no related file):*
It is important to detect all only ``SoftRoCE`` suppressions.

___
___
*[`tests/memcheck-libibverbs-librdmacm.supp` line 9 at r1](https://reviewable.io/reviews/pmem/rpma/1882#-N5_8vS28hyymg5u4OZg:-N5_8vS3BPu227dhfzEV:b-11zwfe) ([raw file](https://github.com/pmem/rpma/blob/1664e97d632c629d1c8d7577ac70aa8563243686/tests/memcheck-libibverbs-librdmacm.supp#L9)):*
> ```
> 
> {
>    Verbs context, once it is opened, it is never closed (RXE variant).
> ```

Is it also ``SoftRoCE specific memory leak``



_Code quote:_
```
{
   Verbs context, once it is opened, it is never closed (RXE variant).
```
___
*[`tests/memcheck-libibverbs-librdmacm.supp` line 67 at r1](https://reviewable.io/reviews/pmem/rpma/1882#-N5_94Mk1auZeVFpRnfE:-N5_94Mk1auZeVFpRnfF:bsrye6z) ([raw file](https://github.com/pmem/rpma/blob/1664e97d632c629d1c8d7577ac70aa8563243686/tests/memcheck-libibverbs-librdmacm.supp#L67)):*
> ```
>    fun:malloc
>    fun:ucma_init_device.part.0
>    ...
> ```

do we know the librpma context?



_Code quote:_
```
   ...
```
___
*[`tests/memcheck-libibverbs-librdmacm.supp` line 125 at r1](https://reviewable.io/reviews/pmem/rpma/1882#-N5_9Tk7BnCU3tSgDWJP:-N5_9Tk7BnCU3tSgDWJQ:b32vmt) ([raw file](https://github.com/pmem/rpma/blob/1664e97d632c629d1c8d7577ac70aa8563243686/tests/memcheck-libibverbs-librdmacm.supp#L125)):*
> ```
>    fun:rpma_conn_req_from_id
>    fun:rpma_conn_req_new
>    fun:main
> ```

??



_Suggestion:_
```
...
```
___
*[`tests/memcheck-libibverbs-librdmacm.supp` line 141 at r1](https://reviewable.io/reviews/pmem/rpma/1882#-N5_9X4z7MyRfV5PV__v:-N5_9X4z7MyRfV5PV__w:b32vmt) ([raw file](https://github.com/pmem/rpma/blob/1664e97d632c629d1c8d7577ac70aa8563243686/tests/memcheck-libibverbs-librdmacm.supp#L141)):*
> ```
>    fun:rdma_get_cm_event
>    ...
>    fun:rpma_info_resolve_addr
> ```

??



_Suggestion:_
```
fun:rpma_info_resolve_addr
...
```
___
*[`tests/memcheck-libibverbs-librdmacm.supp` line 200 at r1](https://reviewable.io/reviews/pmem/rpma/1882#-N5_9i1bBLa1Zyhq5pT5:-N5_9i1bBLa1Zyhq5pT6:b-iwsa7y) ([raw file](https://github.com/pmem/rpma/blob/1664e97d632c629d1c8d7577ac70aa8563243686/tests/memcheck-libibverbs-librdmacm.supp#L200)):*
> ```
>    To be analysed later
>    Memcheck:Leak
>    match-leak-kinds: possible
> ```

redundancy??



_Code quote:_
```
   match-leak-kinds: possible
   fun:calloc
```
___
*[`tests/memcheck-libibverbs-librdmacm.supp` line 207 at r1](https://reviewable.io/reviews/pmem/rpma/1882#-N5_9_b1Bw1KB8V1KjEP:-N5_9_b290r8PWKMWo8l:undefined) ([raw file](https://github.com/pmem/rpma/blob/1664e97d632c629d1c8d7577ac70aa8563243686/tests/memcheck-libibverbs-librdmacm.supp#L207)):*
> ```
>    fun:rpma_info_bind_addr
>    fun:rpma_utils_get_ibv_context
>    fun:main
> ```





_Suggestion:_
```
...
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1882)* status: all files reviewed, 7 unresolved discussions (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1882)* status: all files reviewed, 9 unresolved discussions (waiting on @osalyk)

___
*[`THREAD_SAFETY.md` line 128 at r1](https://reviewable.io/reviews/pmem/rpma/1882#-N5_UsjU64148B_LhiIx:-N5_UsjVDYJDRSkx1lAQ:btftgpz) ([raw file](https://github.com/pmem/rpma/blob/1664e97d632c629d1c8d7577ac70aa8563243686/THREAD_SAFETY.md#L128)):*
> ```Markdown
> ## Analysis of Valgrind suppressions
> 
> ### Suppressions for libibverbs
> ```

libibverbs and librdmacm



_Code quote:_
```Markdown
libibverbs
```
___
*[`THREAD_SAFETY.md` line 130 at r1](https://reviewable.io/reviews/pmem/rpma/1882#-N5_UvzMEFpolIIyp2-l:-N5_UvzMEFpolIIyp2-m:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/1664e97d632c629d1c8d7577ac70aa8563243686/THREAD_SAFETY.md#L130)):*
> ```Markdown
> ### Suppressions for libibverbs
> 
> The suppressions for libibverbs are described in the [tests/memcheck-libibverbs-librdmacm.supp](tests/memcheck-libibverbs-librdmacm.supp) file.
> ```

.



_Code quote:_
```Markdown
libibverbs
```

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1882)* status: 4 of 5 files reviewed, 7 unresolved discussions (waiting on @grom72 and @osalyk)

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1882)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`tests/memcheck-libibverbs-librdmacm.supp` line 9 at r4](https://reviewable.io/reviews/pmem/rpma/1882#-N5dvoy8Ew8qF336Qr6q:-N5eBbTa3mKcWyKnapDP:b32v57) ([raw file](https://github.com/pmem/rpma/blob/fc8f6f7ebd6349f2881f202abfbd164e8a7d08c4/tests/memcheck-libibverbs-librdmacm.supp#L9)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

What about common format? I think we should use it also here.
</blockquote></details>

+1

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1882)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[`tests/memcheck-libibverbs-librdmacm.supp` line 9 at r4](https://reviewable.io/reviews/pmem/rpma/1882#-N5dvoy8Ew8qF336Qr6q:-N5eOCBuCdr0EdoxKDFJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fc8f6f7ebd6349f2881f202abfbd164e8a7d08c4/tests/memcheck-libibverbs-librdmacm.supp#L9)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1882)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1882)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`tests/memcheck-libibverbs-librdmacm.supp` line 9 at r4](https://reviewable.io/reviews/pmem/rpma/1882#-N5dvoy8Ew8qF336Qr6q:-N5eQpWv9prBkOtqhdQw:b-tc8438) ([raw file](https://github.com/pmem/rpma/blob/fc8f6f7ebd6349f2881f202abfbd164e8a7d08c4/tests/memcheck-libibverbs-librdmacm.supp#L9)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

"Occurs in traces of: ..." is missing

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1882)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[`tests/memcheck-libibverbs-librdmacm.supp` line 9 at r4](https://reviewable.io/reviews/pmem/rpma/1882#-N5dvoy8Ew8qF336Qr6q:-N5eUx8BA7HG195FHBmG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fc8f6f7ebd6349f2881f202abfbd164e8a7d08c4/tests/memcheck-libibverbs-librdmacm.supp#L9)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

"Occurs in traces of: ..." is missing
</blockquote></details>

Done.

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1882)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1882)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[`tests/memcheck-libibverbs-librdmacm.supp` line 64 at r7](https://reviewable.io/reviews/pmem/rpma/1882#-N5iL24O69aBMKLB0Yop:-N5iL24O69aBMKLB0Yoq:b-g4i57g) ([raw file](https://github.com/pmem/rpma/blob/72fa7764c6caf0ffe7de11d11794044b9246b081/tests/memcheck-libibverbs-librdmacm.supp#L64)):*
> ```
> # OS: Ubuntu 22.04
> # libibverbs, version 1.14.39.0
> # librdmacm, version 1.3.39.0
> ```

Are these all suppressions starting from here from RDMA HW? If yes:
1) Missing OFED version.
2) Are versions of libibverbs and librdmacm  really the same as on CircleCI? In case of drd and helgrind suppressions we have different versions ...



_Code quote:_
```
# OS: Ubuntu 22.04
# libibverbs, version 1.14.39.0
# librdmacm, version 1.3.39.0
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1882)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`tests/memcheck-libibverbs-librdmacm.supp` line 64 at r7](https://reviewable.io/reviews/pmem/rpma/1882#-N5iL24O69aBMKLB0Yop:-N5iQggKBxVMnHzaDr-C:b-xyzhaz) ([raw file](https://github.com/pmem/rpma/blob/72fa7764c6caf0ffe7de11d11794044b9246b081/tests/memcheck-libibverbs-librdmacm.supp#L64)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Are these all suppressions starting from here from RDMA HW? If yes:
1) Missing OFED version.
2) Are versions of libibverbs and librdmacm  really the same as on CircleCI? In case of drd and helgrind suppressions we have different versions ...
</blockquote></details>

These suppressions came out on SoftRoCE, everything is entered correctly

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1882#-:-N5iXZ7iDbYQswnAL2za:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
