### PR TITLE
tools: verify path to the IB tool

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1128)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1128)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/ib_read.sh, line 220 at r1](https://reviewable.io/reviews/pmem/rpma/1128#-MdrQy7xClMWBgaj-Xjy:-MdrQy7xClMWBgaj-Xjz:b-f04ayh) ([raw file](https://github.com/pmem/rpma/blob/2a460152eaa887aebb3cdfc298d7f3a20e2dc542/tools/perf/ib_read.sh#L220)):*
> ```Shell
> 		prepare_RUN_NAME_and_CMP__SUBST
> 
> 		if [ ! -f ${IB_PATH}/${IB_TOOL} ]; then
> ```

What if no IB_PATH is provided but the `IB_TOOL` is available from the PATH?
___
*[tools/perf/ib_read.sh, line 223 at r1](https://reviewable.io/reviews/pmem/rpma/1128#-MdrR9f5A6o8y3Vf4qpG:-MdrR9f5A6o8y3Vf4qpH:b-fvmego) ([raw file](https://github.com/pmem/rpma/blob/2a460152eaa887aebb3cdfc298d7f3a20e2dc542/tools/perf/ib_read.sh#L223)):*
> ```Shell
> 			echo "Error: ${IB_PATH}/${IB_TOOL} does not exist"
> 			exit 1
> 		fi
> ```

REMOTE_IB_PATH?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1128)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/ib_read.sh, line 220 at r1](https://reviewable.io/reviews/pmem/rpma/1128#-MdrQy7xClMWBgaj-Xjy:-MdufGKQ7kUfkM5Ao8G1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2a460152eaa887aebb3cdfc298d7f3a20e2dc542/tools/perf/ib_read.sh#L220)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

What if no IB_PATH is provided but the `IB_TOOL` is available from the PATH?
</blockquote></details>

Done.
___
*[tools/perf/ib_read.sh, line 223 at r1](https://reviewable.io/reviews/pmem/rpma/1128#-MdrR9f5A6o8y3Vf4qpG:-MdufGxBDT67DDE1fs0Z:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2a460152eaa887aebb3cdfc298d7f3a20e2dc542/tools/perf/ib_read.sh#L223)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

REMOTE_IB_PATH?
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1128#-:-Mdum0C_DfpDvqmavuWO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1128#-:-Mdum9RA371EvF0WOpQQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
