### PR TITLE
test: fix and enable the rpma_conn_get_private_data MT test

### PR DESCRIPTION
**Pull request by ldorau**
The client sometimes has to wait for the server to start listening,
so the client should retry to connect to the server several
times.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1604)

### CODE REVIEW

**Review by Patryk717 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1604#-:-MxIstXR2TQNukHW0leM:bdycpsm)* status: 0 of 2 files reviewed, all discussions resolved

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1604#-:-MxtLy1XAQv-PFKkdKxu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1604)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by haichangsi — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1604#-:-MyCLpPK4-83xaeCFBDH:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
