### PR TITLE
test: add missing unit tests for rpma_mr_atomic_write()

### PR DESCRIPTION
**Pull request by yangx-jy**
Current unit tests cannot cover the following lines in rpma_mr_atomic_write():
https://app.codecov.io/gh/pmem/rpma/pull/2108/blob/src/mr.c#L248 https://app.codecov.io/gh/pmem/rpma/pull/2108/blob/src/mr.c#L252

Add missing unit tests by restructuring mr-atomic_write.c.

- - -
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/2110)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2110)* status: 0 of 1 files reviewed, all discussions resolved

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2110)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2110)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2110)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[`tests/unit/mr/mr-atomic_write.c` line 62 at r1](https://reviewable.io/reviews/pmem/rpma/2110#-NPqsFW-8uHELRSQSjqx:-NPqsFW-8uHELRSQSjqy:b-cllevf) ([raw file](https://github.com/pmem/rpma/blob/cf79b5f3353459b144730fc140013ff19b308e48/tests/unit/mr/mr-atomic_write.c#L62)):*
> ```C
> 		args.rkey = MOCK_RKEY;
> 		args.ret = ret;
> 		will_return(ibv_post_send_mock, &args);
> ```

Maybe we could avoid duplicating the following code in `configure_mr_atomic_write()` ?



_Code quote:_
```C
		args.qp = MOCK_QP;
		args.opcode = IBV_WR_RDMA_WRITE;
		args.send_flags = IBV_SEND_INLINE | IBV_SEND_FENCE;
		if (flags == RPMA_F_COMPLETION_ALWAYS)
			args.send_flags |= IBV_SEND_SIGNALED;
		args.wr_id = (uint64_t)MOCK_OP_CONTEXT;
		args.remote_addr = MOCK_RADDR + MOCK_DST_OFFSET;
		args.rkey = MOCK_RKEY;
		args.ret = ret;
		will_return(ibv_post_send_mock, &args);
```

**Comment by yangx-jy** [comment]
*[`tests/unit/mr/mr-atomic_write.c` line 62 at r1](https://reviewable.io/reviews/pmem/rpma/2110#-NPqsFW-8uHELRSQSjqx:-NPrUGQ_6OQvf79I0Z16:b-b64kuc) ([raw file](https://github.com/pmem/rpma/blob/cf79b5f3353459b144730fc140013ff19b308e48/tests/unit/mr/mr-atomic_write.c#L62)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Maybe we could avoid duplicating the following code in `configure_mr_atomic_write()` ?
</blockquote></details>

Done. `configure_mr_atomic_write()` contains the duplicated code and `configure_mr_atomic_write_with_qpx()` takes use of it.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2110)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2110)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2110#-NPstF_o2CMtA7RUDK_7:-NPstF_o2CMtA7RUDK_8:bnad3fa) (no related file):*
@yangx-jy @grom72 What do you think about the following change to the current code?:
https://github.com/ldorau/rpma/commit/b945c78bff91d961e4bf8ea9ef818bf673e1962d
Resulting file: https://github.com/ldorau/rpma/blob/test-less-code/tests/unit/mr/mr-atomic_write.c
Branch: https://github.com/ldorau/rpma/commits/test-less-code
Pros:
- less code
- less ifdefs
- simpler code

___

**Comment by yangx-jy** [comment]
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@yangx-jy @grom72 What do you think about the following change to the current code?:
https://github.com/ldorau/rpma/commit/b945c78bff91d961e4bf8ea9ef818bf673e1962d
Resulting file: https://github.com/ldorau/rpma/blob/test-less-code/tests/unit/mr/mr-atomic_write.c
Branch: https://github.com/ldorau/rpma/commits/test-less-code
Pros:
- less code
- less ifdefs
- simpler code
</blockquote></details>

Agreed, it is actually better than the current code.
I have updated this PR based on your change.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2110)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2110)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2110#-NPstF_o2CMtA7RUDK_7:-NPueng_7JUMbDgF2OIz:b-fs66kn) (no related file):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Agreed, it is actually better than the current code.
I have updated this PR based on your change.
</blockquote></details>

Even better than mine :-)

___

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2110#-:-NPujtrw6tCUPlj3VZ8B:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2110#-:-NPv88WxC4Ueanl2DD6r:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by grom72 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2110)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2110)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Pull request merged**
