### PR TITLE
examples: Add a ping-pong example supporting multiple connections

### PR DESCRIPTION
**Pull request by ultra-nexus**
- This example is based on the example-06

Signed-off-by: Hao Li <lihao2018.fnst@cn.fujitsu.com>

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/783)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/783)* status: 3 of 6 files reviewed, 12 unresolved discussions (waiting on @ultra-nexus)

___
*[examples/10-messages-ping-pong-with-multiple-connections/client.c, line 80 at r1](https://reviewable.io/reviews/pmem/rpma/783#-MShwoEH4XGOSGAzkT7x:-MShwoEH4XGOSGAzkT7y:b-747wy0) ([raw file](https://github.com/pmem/rpma/blob/b6d4021d6e90803346da8f51244691c73c4472c7/examples/10-messages-ping-pong-with-multiple-connections/client.c#L80)):*
> ```C
> 	if (send_ptr == NULL || recv_ptr == NULL) {
> 		ret = -1;
> 		goto err_peer_delete;
> ```

If either send_ptr or recv_ptr is not NULL you have to free it. I know we are closing the app but otherwise, it is hard to track memory leaks e.g. using Valgrind. A good practice.
You can see example-08 for what I would recommend.
___
*[examples/10-messages-ping-pong-with-multiple-connections/client.c, line 109 at r1](https://reviewable.io/reviews/pmem/rpma/783#-MShxxYPE9e95x22yq4s:-MShxxYPE9e95x22yq4t:b-pwpkjt) ([raw file](https://github.com/pmem/rpma/blob/b6d4021d6e90803346da8f51244691c73c4472c7/examples/10-messages-ping-pong-with-multiple-connections/client.c#L109)):*
> ```C
> 	if (rpma_conn_completion_get(conn, &cmpl))
> 		goto err_conn_disconnect;
> 	if (cmpl.op != RPMA_OP_SEND && cmpl.op_status != IBV_WC_SUCCESS) {
> ```

Sadly you can not assume the completion for RPMA_OP_SEND will come before RPMA_OP_RECV.
You can either send the message with RPMA_F_COMPLETION_ON_ERROR or you have to make here a more versatile loop for both completions in whatever order they might have come.
___
*[examples/10-messages-ping-pong-with-multiple-connections/client.c, line 147 at r1](https://reviewable.io/reviews/pmem/rpma/783#-MShybeZDC8G3VoLZbyY:-MShybeZDC8G3VoLZbyZ:b8v4mmi) ([raw file](https://github.com/pmem/rpma/blob/b6d4021d6e90803346da8f51244691c73c4472c7/examples/10-messages-ping-pong-with-multiple-connections/client.c#L147)):*
> ```C
> 		printf("Fail to send name to server: op=%d status=%d\n",
> 						cmpl.op, cmpl.op_status);
> 		goto err_conn_disconnect;
> ```

Not needed. The label is just after the if-statement.
___
*[examples/10-messages-ping-pong-with-multiple-connections/server.c, line 75 at r1](https://reviewable.io/reviews/pmem/rpma/783#-MShzr1B0ZsxMtuBbDWb:-MShzr1B0ZsxMtuBbDWc:b4shdzq) ([raw file](https://github.com/pmem/rpma/blob/b6d4021d6e90803346da8f51244691c73c4472c7/examples/10-messages-ping-pong-with-multiple-connections/server.c#L75)):*
> ```C
> 	/* allocate a memory */
> 	size_t dst_size = MAX_MSG_SIZE * CLIENT_MAX;
> 	svr->src_ptr = "What's your name?";
> ```

You can not do this. Such a memory is potentially not aligned to the page.
___
*[examples/10-messages-ping-pong-with-multiple-connections/server.c, line 84 at r1](https://reviewable.io/reviews/pmem/rpma/783#-MSi-0WqAewCcmCZWJrJ:-MSi-0WqAewCcmCZWJrK:b-jq222s) ([raw file](https://github.com/pmem/rpma/blob/b6d4021d6e90803346da8f51244691c73c4472c7/examples/10-messages-ping-pong-with-multiple-connections/server.c#L84)):*
> ```C
> 	/* register the memory */
> 	ret = rpma_mr_reg(peer, svr->src_ptr, MAX_MSG_SIZE,
> 				RPMA_MR_USAGE_SEND, &svr->src_mr);
> ```

I would like to have at least a common naming convention between the client and the server of the same example.
If this memory is used for sending, the client names such a memory `send_ptr` and `send_mr`.
Please unify the names.
___
*[examples/10-messages-ping-pong-with-multiple-connections/server.c, line 111 at r1](https://reviewable.io/reviews/pmem/rpma/783#-MSi-oDf7Pn9TVkQNAXA:-MSi-oDf7Pn9TVkQNAXB:b-625ggw) ([raw file](https://github.com/pmem/rpma/blob/b6d4021d6e90803346da8f51244691c73c4472c7/examples/10-messages-ping-pong-with-multiple-connections/server.c#L111)):*
> ```
> 	/* deregister the memory region */
> 	int ret = rpma_mr_dereg(&svr->src_mr);
> 	ret |= rpma_mr_dereg(&svr->dst_mr);
> ```

When you do such a thing the return value makes no sense so there is no point in writing an exact errno value later on.
Either do the same: `ret |=  close(svr->epoll);` or make sure the return value makes any sense from the begining.
___
*[examples/10-messages-ping-pong-with-multiple-connections/server.c, line 211 at r1](https://reviewable.io/reviews/pmem/rpma/783#-MSi0f_S05Nraly_lnPX:-MSi0f_S05Nraly_lnPY:b-f03x9v) ([raw file](https://github.com/pmem/rpma/blob/b6d4021d6e90803346da8f51244691c73c4472c7/examples/10-messages-ping-pong-with-multiple-connections/server.c#L211)):*
> ```C
> 		/* no completion is ready - continue */
> 		if (ret == RPMA_E_NO_COMPLETION)
> 			goto cont;
> ```

Why not just `return;`?

FYI we accept `goto x` only for plain error handling not for actual execution logic.
___
*[examples/10-messages-ping-pong-with-multiple-connections/server.c, line 241 at r1](https://reviewable.io/reviews/pmem/rpma/783#-MSi1dhJ0Qucgq5U5EhZ:-MSi1dhJ0Qucgq5U5Eh_:b-hbrjpy) ([raw file](https://github.com/pmem/rpma/blob/b6d4021d6e90803346da8f51244691c73c4472c7/examples/10-messages-ping-pong-with-multiple-connections/server.c#L241)):*
> ```C
> 				goto err;
> 			/* we need to wait for client's name */
> 			goto cont;
> ```

return?
___
*[examples/10-messages-ping-pong-with-multiple-connections/server.c, line 248 at r1](https://reviewable.io/reviews/pmem/rpma/783#-MSi1ju459vbWzDSZrM-:-MSi1ju459vbWzDSZrM0:b-hiacly) ([raw file](https://github.com/pmem/rpma/blob/b6d4021d6e90803346da8f51244691c73c4472c7/examples/10-messages-ping-pong-with-multiple-connections/server.c#L248)):*
> ```C
> 					(char *)svr->dst_ptr + clnt->offset);
> 			/* this client is done */
> 			goto done;
> ```

I'm not yet sure but probably you can mark somehow the client when it is done or has to be disconnected because of an error and handle the cleanup outside of this handler.
Because having this err/done label makes this function messy and it serves two functions so... it probably should be splitted.
___
*[examples/10-messages-ping-pong-with-multiple-connections/server.c, line 252 at r1](https://reviewable.io/reviews/pmem/rpma/783#-MSi2GbgAN1uexMjicM2:-MSi2GbgAN1uexMjicM3:b-hbrjpy) ([raw file](https://github.com/pmem/rpma/blob/b6d4021d6e90803346da8f51244691c73c4472c7/examples/10-messages-ping-pong-with-multiple-connections/server.c#L252)):*
> ```C
> 	} else if (cmpl.op == RPMA_OP_SEND &&
> 			cmpl.op_status == IBV_WC_SUCCESS) {
> 		goto cont;
> ```

return?
___
*[examples/10-messages-ping-pong-with-multiple-connections/server.c, line 264 at r1](https://reviewable.io/reviews/pmem/rpma/783#-MSi1HBDBZKv3s1LPaIr:-MSi1HBDBZKv3s1LPaIs:btiwepm) ([raw file](https://github.com/pmem/rpma/blob/b6d4021d6e90803346da8f51244691c73c4472c7/examples/10-messages-ping-pong-with-multiple-connections/server.c#L264)):*
> ```C
> done:
> err:
> 	(void) rpma_conn_disconnect(clnt->conn);
> ```

I think you probably have to do more than that. Anything from `client_delete()`?
___
*[examples/10-messages-ping-pong-with-multiple-connections/server.c, line 292 at r1](https://reviewable.io/reviews/pmem/rpma/783#-MSi2_-d8C74DA-QMvaM:-MSi2_-d8C74DA-QMvaN:b-pjs1it) ([raw file](https://github.com/pmem/rpma/blob/b6d4021d6e90803346da8f51244691c73c4472c7/examples/10-messages-ping-pong-with-multiple-connections/server.c#L292)):*
> ```C
> 	case RPMA_CONN_ESTABLISHED:
> 		printf("Client-[%lu] connected\n", clnt->client_id);
> 		client_connected_cnt++;
> ```

I liked more the handler-based architecture the base implementation has. ;-)

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/783)* status: 3 of 6 files reviewed, 14 unresolved discussions (waiting on @ultra-nexus)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/783#-MSi2woPBFI39cHOQEWT:-MSi2woPBFI39cHOQEWU:b-ggtfpq) (no related file):*
Since this example is aimed to be a SRQ example in the future, I think the name should reflect what it is all about e.g. 10-shared-receive-queue.

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/783#-MSi3y9A98Dpi0vLsmL1:-MSi3y9A98Dpi0vLsmL2:bk8ydry) (no related file):*
Do you expect this example to be merged before the actual SRQ functionality? Or you will be adjusting this example along with developing SRQ and you want both of them to be merged at the same time?

---

**Review by ultra-nexus — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/783)* status: 3 of 6 files reviewed, 14 unresolved discussions (waiting on @janekmi and @ultra-nexus)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/783#-MSi2woPBFI39cHOQEWT:-MSkCufaEHgrIuzObUSN:b-lymi2z) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Since this example is aimed to be a SRQ example in the future, I think the name should reflect what it is all about e.g. 10-shared-receive-queue.
</blockquote></details>

I once thought I need to create two examples, one for non-SRQ and the other for SRQ. It should be OK to use one example for these two purpose as the code in these two example is almost identical.

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/783#-MSi3y9A98Dpi0vLsmL1:-MSkG_zQ-vbafGLdo1PM:beahi45) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Do you expect this example to be merged before the actual SRQ functionality? Or you will be adjusting this example along with developing SRQ and you want both of them to be merged at the same time?
</blockquote></details>

I think it would be better merge them at the same time. I'm not sure whether I will update this example during SRQ development. Thanks.

---
___
*[examples/10-messages-ping-pong-with-multiple-connections/client.c, line 109 at r1](https://reviewable.io/reviews/pmem/rpma/783#-MShxxYPE9e95x22yq4s:-MSkGwl92iSvogB0MScg:b-75ru0e) ([raw file](https://github.com/pmem/rpma/blob/b6d4021d6e90803346da8f51244691c73c4472c7/examples/10-messages-ping-pong-with-multiple-connections/client.c#L109)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Sadly you can not assume the completion for RPMA_OP_SEND will come before RPMA_OP_RECV.
You can either send the message with RPMA_F_COMPLETION_ON_ERROR or you have to make here a more versatile loop for both completions in whatever order they might have come.
</blockquote></details>

Thanks! This is extremely helpful! I'm currently struggling to fix a strange problem in this example with SRQ enabled when running on real InfiniBand hardware, but fail to figure out what's wrong. After change my code according to this comment, the problem is fixed.

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/783)* status: 3 of 6 files reviewed, 13 unresolved discussions (waiting on @ultra-nexus)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/783#-MSi2woPBFI39cHOQEWT:-MSlgVu_5diy4VPmzs-I:bohw1kt) (no related file):*
<details><summary><i>Previously, ultra-nexus wrote…</i></summary><blockquote>

I once thought I need to create two examples, one for non-SRQ and the other for SRQ. It should be OK to use one example for these two purpose as the code in these two example is almost identical.
</blockquote></details>

I think examples are to show customers how to use the available features. So, an example showing how to use SRQ is fine. :-) Please rename.

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/783#-MSi3y9A98Dpi0vLsmL1:-MSlgqAL87ZiukJR5f_Q:bbyr6as) (no related file):*
<details><summary><i>Previously, ultra-nexus wrote…</i></summary><blockquote>

I think it would be better merge them at the same time. I'm not sure whether I will update this example during SRQ development. Thanks.
</blockquote></details>

Ok. So I will take a look here from time to time and mark this PR as WIP.

---
___
*[examples/10-messages-ping-pong-with-multiple-connections/client.c, line 109 at r1](https://reviewable.io/reviews/pmem/rpma/783#-MShxxYPE9e95x22yq4s:-MSlh4wM8bjtmpn2RHwq:b-wrutf) ([raw file](https://github.com/pmem/rpma/blob/b6d4021d6e90803346da8f51244691c73c4472c7/examples/10-messages-ping-pong-with-multiple-connections/client.c#L109)):*
<details><summary><i>Previously, ultra-nexus wrote…</i></summary><blockquote>

Thanks! This is extremely helpful! I'm currently struggling to fix a strange problem in this example with SRQ enabled when running on real InfiniBand hardware, but fail to figure out what's wrong. After change my code according to this comment, the problem is fixed.
</blockquote></details>

np. :-)

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/783)* status: 5 of 6 files reviewed, 13 unresolved discussions (waiting on @ultra-nexus)

**Comment by janekmi** [comment]
@ultra-nexus, I hope you are doing well. We miss you. I will be pleased to reopen this ancient PR for you when you will be ready. Cheers!

**Pull request closed without merging**
