### PR TITLE
doc: update pmem.io benchmarking manuals for ICX

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1638)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1638)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[index.md, line 19 at r1](https://reviewable.io/reviews/pmem/rpma/1638#-MzsWmf324esDIwlxouB:-MzsWmf324esDIwlxouC:b-fu7m1k) ([raw file](https://github.com/pmem/rpma/blob/9735daf416c5630b0088efa080a78d5d259f23b2/index.md#L19)):*
> ```Markdown
> #### Recommended reading list
> 
> * [Basic - Direct write to PMem](./documentation/basic-direct-write-to-pmem.html)
> ```

`Direct write to PMem for Cascade Lake Intel&reg; Xeon&reg; Processor]`



_Code quote:_
```Markdown
Direct write to PMem]
```
___
*[index.md, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/1638#-MzsWyQUCNo_-uKmBvVp:-MzsWyQUCNo_-uKmBvVq:b-na76pt) ([raw file](https://github.com/pmem/rpma/blob/9735daf416c5630b0088efa080a78d5d259f23b2/index.md#L20)):*
> ```Markdown
> 
> * [Basic - Direct write to PMem](./documentation/basic-direct-write-to-pmem.html)
> * [Basic - Direct write to PMem for ICX](./documentation/basic-direct-write-to-pmem-ICX.html)
> ```

`Direct write to PMem for Ice Lake Intel&reg; Xeon&reg; Processor]`



_Code quote:_
```Markdown
Direct write to PMem for ICX]
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1638)* status: 1 of 2 files reviewed, 6 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[documentation/basic-direct-write-to-pmem-ICX.md, line 8 at r1](https://reviewable.io/reviews/pmem/rpma/1638#-MzscIcd7n25_6PEDxWw:-MzscIcd7n25_6PEDxWx:b-4y4t7a) ([raw file](https://github.com/pmem/rpma/blob/9735daf416c5630b0088efa080a78d5d259f23b2/documentation/basic-direct-write-to-pmem-ICX.md#L8)):*
> ```Markdown
> # Direct Write to PMem
> 
> *Direct Write to PMem* is a readiness of hardware and software configuration which allows effectively and persistently write data to PMem physically attached to one system from another system using RDMA-capable network. How to achive *Direct Write to PMem* capability may differs from system to system because of variety of potential 'interruptions' (e.g. caching) in data's way to be stored persistently on PMem.
> ```

`achieve`



_Code quote:_
```Markdown
achive
```
___
*[documentation/basic-direct-write-to-pmem-ICX.md, line 8 at r1](https://reviewable.io/reviews/pmem/rpma/1638#-MzscLa42o7S1LYZmwIG:-MzscLa42o7S1LYZmwIH:b-l9ywrs) ([raw file](https://github.com/pmem/rpma/blob/9735daf416c5630b0088efa080a78d5d259f23b2/documentation/basic-direct-write-to-pmem-ICX.md#L8)):*
> ```Markdown
> # Direct Write to PMem
> 
> *Direct Write to PMem* is a readiness of hardware and software configuration which allows effectively and persistently write data to PMem physically attached to one system from another system using RDMA-capable network. How to achive *Direct Write to PMem* capability may differs from system to system because of variety of potential 'interruptions' (e.g. caching) in data's way to be stored persistently on PMem.
> ```

`may differ`



_Code quote:_
```Markdown
may differs 
```
___
*[documentation/basic-direct-write-to-pmem-ICX.md, line 12 at r1](https://reviewable.io/reviews/pmem/rpma/1638#-MzscQIp63nEVjcI9LNe:-MzscQIp63nEVjcI9LNf:b-njwnne) ([raw file](https://github.com/pmem/rpma/blob/9735daf416c5630b0088efa080a78d5d259f23b2/documentation/basic-direct-write-to-pmem-ICX.md#L12)):*
> ```Markdown
> ## 3rd Generation Intel&reg; Xeon&reg; Scalable Processors
> 
> For the 3rd Generation Intel&reg; Xeon&reg; Scalable Processors (**Ice Lake**) the only configuration item one should take care of is Intel&reg; Data Direct I/O Technology (**DDIO**). **DDIO** assumes the good enough place to effectively store data comming from the RDMA (and any other DMA traffic) is the CPU LLC from which CPU can access it more easily than when it would be stored in DRAM or on PMem [[1]][ddio]. This is beneficial for any other DMA traffic but prevents from achiving *Direct Write to PMem*.
> ```

` coming `



_Code quote:_
```Markdown
 comming 
```
___
*[documentation/basic-direct-write-to-pmem-ICX.md, line 12 at r1](https://reviewable.io/reviews/pmem/rpma/1638#-MzscV7o2xzHu4ZH4Ctl:-MzscV7o2xzHu4ZH4Ctm:b3w71xp) ([raw file](https://github.com/pmem/rpma/blob/9735daf416c5630b0088efa080a78d5d259f23b2/documentation/basic-direct-write-to-pmem-ICX.md#L12)):*
> ```Markdown
> ## 3rd Generation Intel&reg; Xeon&reg; Scalable Processors
> 
> For the 3rd Generation Intel&reg; Xeon&reg; Scalable Processors (**Ice Lake**) the only configuration item one should take care of is Intel&reg; Data Direct I/O Technology (**DDIO**). **DDIO** assumes the good enough place to effectively store data comming from the RDMA (and any other DMA traffic) is the CPU LLC from which CPU can access it more easily than when it would be stored in DRAM or on PMem [[1]][ddio]. This is beneficial for any other DMA traffic but prevents from achiving *Direct Write to PMem*.
> ```

`achieving`



_Code quote:_
```Markdown
achiving
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1638)* status: all files reviewed, 8 unresolved discussions (waiting on @osalyk)

___
*[documentation/basic-direct-write-to-pmem-ICX.md, line 14 at r1](https://reviewable.io/reviews/pmem/rpma/1638#-Mzsg6_N3hQXvkJ6iGXF:-Mzsg6_N3hQXvkJ6iGXG:bd8fpja) ([raw file](https://github.com/pmem/rpma/blob/9735daf416c5630b0088efa080a78d5d259f23b2/documentation/basic-direct-write-to-pmem-ICX.md#L14)):*
> ```Markdown
> For the 3rd Generation Intel&reg; Xeon&reg; Scalable Processors (**Ice Lake**) the only configuration item one should take care of is Intel&reg; Data Direct I/O Technology (**DDIO**). **DDIO** assumes the good enough place to effectively store data comming from the RDMA (and any other DMA traffic) is the CPU LLC from which CPU can access it more easily than when it would be stored in DRAM or on PMem [[1]][ddio]. This is beneficial for any other DMA traffic but prevents from achiving *Direct Write to PMem*.
> 
> For the **Ice Lake** processor **DDIO** can be turned off (at the same time enabling *Direct Write to PMem*) globally for all DMA traffic in the system, please contact your BIOS provider for details.
> ```

`**DDIO** should be turned off`



_Code quote:_
```Markdown
**DDIO** can be turned off
```
___
*[documentation/basic-direct-write-to-pmem-ICX.md, line 14 at r1](https://reviewable.io/reviews/pmem/rpma/1638#-MzsgG4r0C1SnpPLGsIg:-MzsgG4r0C1SnpPLGsIh:bvemc3t) ([raw file](https://github.com/pmem/rpma/blob/9735daf416c5630b0088efa080a78d5d259f23b2/documentation/basic-direct-write-to-pmem-ICX.md#L14)):*
> ```Markdown
> For the 3rd Generation Intel&reg; Xeon&reg; Scalable Processors (**Ice Lake**) the only configuration item one should take care of is Intel&reg; Data Direct I/O Technology (**DDIO**). **DDIO** assumes the good enough place to effectively store data comming from the RDMA (and any other DMA traffic) is the CPU LLC from which CPU can access it more easily than when it would be stored in DRAM or on PMem [[1]][ddio]. This is beneficial for any other DMA traffic but prevents from achiving *Direct Write to PMem*.
> 
> For the **Ice Lake** processor **DDIO** can be turned off (at the same time enabling *Direct Write to PMem*) globally for all DMA traffic in the system, please contact your BIOS provider for details.
> ```

(enabling *Direct Write to PMem* at the same time)



_Code quote:_
```Markdown
at the same time enabling *Direct Write to PMem*)
```

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1638)* status: all files reviewed, 9 unresolved discussions (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1638#-Mzsh2326T-qhisqYVJJ:-Mzsh2326T-qhisqYVJK:b-kxxhvo) (no related file):*
My proposal is to merge both ICX and CLX in one document
```
# Direct Write to PMem
...
```
(as it is now)
```
A sentence saying that different platforms have different ways to disable/enable DDIO
[Link to 3rd generation]
[Link to 2nd generation]
```
```
# 3rd Generation Intel&reg; Xeon&reg; Scalable Processors
...
# 2rd Generation Intel&reg; Xeon&reg; Scalable Processors
...
# References
...
...
```

---

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1638)* status: all files reviewed, 9 unresolved discussions (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1638)* status: 0 of 3 files reviewed, 9 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1638#-Mzsh2326T-qhisqYVJJ:-MztMO4oAo8rZJBbvGXm:b-896fix) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

My proposal is to merge both ICX and CLX in one document
```
# Direct Write to PMem
...
```
(as it is now)
```
A sentence saying that different platforms have different ways to disable/enable DDIO
[Link to 3rd generation]
[Link to 2nd generation]
```
```
# 3rd Generation Intel&reg; Xeon&reg; Scalable Processors
...
# 2rd Generation Intel&reg; Xeon&reg; Scalable Processors
...
# References
...
...
```


</blockquote></details>

Done.

---
___
*[index.md, line 19 at r1](https://reviewable.io/reviews/pmem/rpma/1638#-MzsWmf324esDIwlxouB:-MztMXa2A303LmvWZnWy:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9735daf416c5630b0088efa080a78d5d259f23b2/index.md#L19)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`Direct write to PMem for Cascade Lake Intel&reg; Xeon&reg; Processor]`
</blockquote></details>

Done.
___
*[index.md, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/1638#-MzsWyQUCNo_-uKmBvVp:-MztMXqBEt9EvQlZzaZW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9735daf416c5630b0088efa080a78d5d259f23b2/index.md#L20)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`Direct write to PMem for Ice Lake Intel&reg; Xeon&reg; Processor]`
</blockquote></details>

Done.
___
*[documentation/basic-direct-write-to-pmem-ICX.md, line 8 at r1](https://reviewable.io/reviews/pmem/rpma/1638#-MzscIcd7n25_6PEDxWw:-MztMwMdEupxJh8USMkE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9735daf416c5630b0088efa080a78d5d259f23b2/documentation/basic-direct-write-to-pmem-ICX.md#L8)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`achieve`
</blockquote></details>

Done.
___
*[documentation/basic-direct-write-to-pmem-ICX.md, line 8 at r1](https://reviewable.io/reviews/pmem/rpma/1638#-MzscLa42o7S1LYZmwIG:-MztMyghAtHhwVGwtFAH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9735daf416c5630b0088efa080a78d5d259f23b2/documentation/basic-direct-write-to-pmem-ICX.md#L8)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`may differ`
</blockquote></details>

Done.
___
*[documentation/basic-direct-write-to-pmem-ICX.md, line 12 at r1](https://reviewable.io/reviews/pmem/rpma/1638#-MzscQIp63nEVjcI9LNe:-MztNGu_2GIQ2wAl9cuM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9735daf416c5630b0088efa080a78d5d259f23b2/documentation/basic-direct-write-to-pmem-ICX.md#L12)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

` coming `
</blockquote></details>

Done.
___
*[documentation/basic-direct-write-to-pmem-ICX.md, line 12 at r1](https://reviewable.io/reviews/pmem/rpma/1638#-MzscV7o2xzHu4ZH4Ctl:-MztNKUhBxcDoANSad_o:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9735daf416c5630b0088efa080a78d5d259f23b2/documentation/basic-direct-write-to-pmem-ICX.md#L12)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`achieving`
</blockquote></details>

Done.
___
*[documentation/basic-direct-write-to-pmem-ICX.md, line 14 at r1](https://reviewable.io/reviews/pmem/rpma/1638#-Mzsg6_N3hQXvkJ6iGXF:-MztNPzbCYKmO4rlVl3N:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9735daf416c5630b0088efa080a78d5d259f23b2/documentation/basic-direct-write-to-pmem-ICX.md#L14)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`**DDIO** should be turned off`
</blockquote></details>

Done.
___
*[documentation/basic-direct-write-to-pmem-ICX.md, line 14 at r1](https://reviewable.io/reviews/pmem/rpma/1638#-MzsgG4r0C1SnpPLGsIg:-MztNWyd32sxiHFWxVx9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9735daf416c5630b0088efa080a78d5d259f23b2/documentation/basic-direct-write-to-pmem-ICX.md#L14)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

(enabling *Direct Write to PMem* at the same time)
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1638)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1638#-:-MztZS9x88Sh2N96yqaj:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1638)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[documentation/basic-direct-write-to-pmem.md, line 10 at r2](https://reviewable.io/reviews/pmem/rpma/1638#-Mztmbx9--Dla5Ez6Qeu:-Mztmbx9--Dla5Ez6Qev:bebboqe) ([raw file](https://github.com/pmem/rpma/blob/5d58b5f912e5fa7af47a0a914978dabc8ac52b5b/documentation/basic-direct-write-to-pmem.md#L10)):*
> ```Markdown
> *Direct Write to PMem* is a readiness of hardware and software configuration which allows effectively and persistently write data to PMem physically attached to one system from another system using RDMA-capable network. How to achieve *Direct Write to PMem* capability may differ from system to system because of variety of potential 'interruptions' (e.g. caching) in data's way to be stored persistently on PMem.
> 
> The ways to disable/enable Intel&reg; Data Direct I/O Technology (**DDIO**) vary by processor generation.
> ```

For details see sections below for the [3rd (Ice Lake)](#icelake) and the [2nd (Cascade Lake)](#cascadelake) Processor Generations
___
*[documentation/basic-direct-write-to-pmem.md, line 12 at r2](https://reviewable.io/reviews/pmem/rpma/1638#-MztnHEPDqZ8s54fZLeC:-MztnHEPDqZ8s54fZLeD:b6hwn2c) ([raw file](https://github.com/pmem/rpma/blob/5d58b5f912e5fa7af47a0a914978dabc8ac52b5b/documentation/basic-direct-write-to-pmem.md#L12)):*
> ```Markdown
> The ways to disable/enable Intel&reg; Data Direct I/O Technology (**DDIO**) vary by processor generation.
> 
> ## 3rd Generation Intel&reg; Xeon&reg; Scalable Processors (**Ice Lake**)
> ```

## 3rd Generation Intel&reg; Xeon&reg; Scalable Processors (**Ice Lake**)   {#icelake}



_Code quote:_
```Markdown
## 3rd Generation Intel&reg; Xeon&reg; Scalable Processors (**Ice Lake**)
```
___
*[documentation/basic-direct-write-to-pmem.md, line 20 at r2](https://reviewable.io/reviews/pmem/rpma/1638#-MztnwA50bIZjK9yHFab:-MztnwA50bIZjK9yHFac:b-jrygwv) ([raw file](https://github.com/pmem/rpma/blob/5d58b5f912e5fa7af47a0a914978dabc8ac52b5b/documentation/basic-direct-write-to-pmem.md#L20)):*
> ```Markdown
> For more information on **DDIO** and its configuration please see the list of references [[1]][ddio][[2]][dpdk].
> 
> ## 2nd Generation Intel&reg; Xeon&reg; Scalable Processors (**Cascade Lake**)
> ```

## 2nd Generation Intel&reg; Xeon&reg; Scalable Processors (**Cascade Lake**) {#cascadelake)



_Code quote:_
```Markdown
## 2nd Generation Intel&reg; Xeon&reg; Scalable Processors (**Cascade Lake**)
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1638)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[documentation/basic-direct-write-to-pmem.md, line 10 at r2](https://reviewable.io/reviews/pmem/rpma/1638#-Mztmbx9--Dla5Ez6Qeu:-MztzZBJ23Ix5Fbcg96u:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5d58b5f912e5fa7af47a0a914978dabc8ac52b5b/documentation/basic-direct-write-to-pmem.md#L10)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

For details see sections below for the [3rd (Ice Lake)](#icelake) and the [2nd (Cascade Lake)](#cascadelake) Processor Generations
</blockquote></details>

Done.
___
*[documentation/basic-direct-write-to-pmem.md, line 12 at r2](https://reviewable.io/reviews/pmem/rpma/1638#-MztnHEPDqZ8s54fZLeC:-MztzZdL-m4stAVnpjaI:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5d58b5f912e5fa7af47a0a914978dabc8ac52b5b/documentation/basic-direct-write-to-pmem.md#L12)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

## 3rd Generation Intel&reg; Xeon&reg; Scalable Processors (**Ice Lake**)   {#icelake}
</blockquote></details>

Done.
___
*[documentation/basic-direct-write-to-pmem.md, line 20 at r2](https://reviewable.io/reviews/pmem/rpma/1638#-MztnwA50bIZjK9yHFab:-Mztza7iEUYeN_b0tCiU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5d58b5f912e5fa7af47a0a914978dabc8ac52b5b/documentation/basic-direct-write-to-pmem.md#L20)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

## 2nd Generation Intel&reg; Xeon&reg; Scalable Processors (**Cascade Lake**) {#cascadelake)
</blockquote></details>

Done.

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1638)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1638)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1638#-:-Mzy1yL80YKMvzFzIxRe:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1638#-:-Mzy1zZj9hmGDOYOa3qA:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
