### PR TITLE
tools: escape markdown special characters in configuration

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1247)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1247#-:-MiVyrmP4O4P1zx4O4xA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1247)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/lib/common.py, line 63 at r1](https://reviewable.io/reviews/pmem/rpma/1247#-MiWWIlf2chSK1-Q3q2f:-MiWWIlg7qgYaFCrRzJ-:b-gmcpui) ([raw file](https://github.com/pmem/rpma/blob/6eeba588af0b7e9ff2547f3c4ba020722c1ac21e/tools/perf/lib/common.py#L63)):*
> ```Python
> def escape(x):
>     """Escape markdown special characters"""
>     if type(x) is str:
> ```

I think we should use `isinstanceof(x, str)`.

Ref: https://towardsdatascience.com/difference-between-type-and-isinstance-in-python-47fae6fbb068
___
*[tools/perf/lib/Report.py, line 56 at r1](https://reviewable.io/reviews/pmem/rpma/1247#-MiWWvWF8-gs0THc2K8C:-MiWWvWF8-gs0THc2K8D:b-4w268q) ([raw file](https://github.com/pmem/rpma/blob/6eeba588af0b7e9ff2547f3c4ba020722c1ac21e/tools/perf/lib/Report.py#L56)):*
> ```Python
>         if missing is not None:
>             raise SyntaxError("{} misses {} entry".format(input_file, missing))
> ```

I think it should go somewhere here. The ifs above are more about validation instead of processing.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1247)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/lib/common.py, line 63 at r1](https://reviewable.io/reviews/pmem/rpma/1247#-MiWWIlf2chSK1-Q3q2f:-MiWjOAn7DGQwGn1kWJd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6eeba588af0b7e9ff2547f3c4ba020722c1ac21e/tools/perf/lib/common.py#L63)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we should use `isinstanceof(x, str)`.

Ref: https://towardsdatascience.com/difference-between-type-and-isinstance-in-python-47fae6fbb068
</blockquote></details>

Done.
___
*[tools/perf/lib/Report.py, line 56 at r1](https://reviewable.io/reviews/pmem/rpma/1247#-MiWWvWF8-gs0THc2K8C:-MiWjiyk3pL5H8HN_AkT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6eeba588af0b7e9ff2547f3c4ba020722c1ac21e/tools/perf/lib/Report.py#L56)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think it should go somewhere here. The ifs above are more about validation instead of processing.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1247#-:-MiWkqMJDi00hfu6eils:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
