### PR TITLE
examples: change read-after-write (RAW) buffer size

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/2017)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2017)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[`examples/04-write-to-persistent/client.c` line 126 at r1](https://reviewable.io/reviews/pmem/rpma/2017#-NBCUrjW6wNEAsNLJyLO:-NBCUrjW6wNEAsNLJyLP:b-hy6iy6) ([raw file](https://github.com/pmem/rpma/blob/925f57049d4a1915ce4b556006a5b22e04f9eed7/examples/04-write-to-persistent/client.c#L126)):*
> ```C
> 
> 	/* register the RAW buffer */
> 	ret = rpma_mr_reg(peer, raw, 8, RPMA_MR_USAGE_READ_DST, &raw_mr);
> ```

`RAW_BUFFER_SIZE`



_Code quote:_
```C
8
```
___
*[`examples/04-write-to-persistent/client.c` line 167 at r1](https://reviewable.io/reviews/pmem/rpma/2017#-NBCUyMM4SpmlGOgQUQW:-NBCUyMN2vsEIPEH6MGW:b-hy6iy6) ([raw file](https://github.com/pmem/rpma/blob/925f57049d4a1915ce4b556006a5b22e04f9eed7/examples/04-write-to-persistent/client.c#L167)):*
> ```C
> 
> 	/* the read serves here as flushing primitive */
> 	ret = rpma_read(conn, raw_mr, 0, dst_mr, 0, 8,
> ```

`RAW_BUFFER_SIZE`



_Code quote:_
```C
8
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2017)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2017#-NBCV2kP5dHggHUnJhLM:-NBCV2kQ9NZmUu6dtoXY:b-hmatcn) (no related file):*
Update `CHANGELOG.md` please

___

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2017)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2017#-NBCV2kP5dHggHUnJhLM:-NBCYS6sB4OYXMp-ODER:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Update `CHANGELOG.md` please
</blockquote></details>

Done.

___
___
*[`examples/04-write-to-persistent/client.c` line 126 at r1](https://reviewable.io/reviews/pmem/rpma/2017#-NBCUrjW6wNEAsNLJyLO:-NBCVV6kC9MJfKJ-N8OT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/925f57049d4a1915ce4b556006a5b22e04f9eed7/examples/04-write-to-persistent/client.c#L126)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`RAW_BUFFER_SIZE`
</blockquote></details>

Done.
___
*[`examples/04-write-to-persistent/client.c` line 167 at r1](https://reviewable.io/reviews/pmem/rpma/2017#-NBCUyMM4SpmlGOgQUQW:-NBCV_U89yIzj45Xl-Dn:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/925f57049d4a1915ce4b556006a5b22e04f9eed7/examples/04-write-to-persistent/client.c#L167)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`RAW_BUFFER_SIZE`
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2017)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`CHANGELOG.md` line 17 at r2](https://reviewable.io/reviews/pmem/rpma/2017#-NBCZCJU1zrjm57Uxqzf:-NBCZg9R4GGLDx3V9UK6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/84312904735a86bc8e88d2f95d113c61563ca03d/CHANGELOG.md#L17)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`changed size of the read-after-write (RAW) buffer in the examples`
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2017#-:-NBC_9ZcD-nssn5ElP78:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2017)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2017#-:-NBCiI0_6n_UXsD7tbup:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2017)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
