### PR TITLE
examples: set the return value if an error occurs

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1612)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1612)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[examples/07-atomic-write/client.c, line 131 at r1](https://reviewable.io/reviews/pmem/rpma/1612#-MxiIBVQ1J1BF65Gaphz:-MxiIBVQ1J1BF65Gapi-:b-u7ys1x) ([raw file](https://github.com/pmem/rpma/blob/c0c6f07b60eeb50f1cd5d2bbca14064a2c458dd8/examples/07-atomic-write/client.c#L131)):*
> ```C
> 
> 	if (wc.status != IBV_WC_SUCCESS) {
> 		(void) fprintf(stderr, "rpma_read() failed: %s\n",
> ```

The same issue.



_Code quote:_
```C
	if (wc.status != IBV_WC_SUCCESS) {
		(void) fprintf(stderr, "rpma_read() failed: %s\n",
				ibv_wc_status_str(wc.status));
		goto err_mr_remote_delete;
	}
```
___
*[examples/07-atomic-write/client.c, line 141 at r1](https://reviewable.io/reviews/pmem/rpma/1612#-MxiI6ppAAZu-wJyyHK9:-MxiI6pq2C-RPRKX8ba7:b-9fwzlb) ([raw file](https://github.com/pmem/rpma/blob/c0c6f07b60eeb50f1cd5d2bbca14064a2c458dd8/examples/07-atomic-write/client.c#L141)):*
> ```C
> 	if (remote_size <= used.uint64) {
> 		fprintf(stderr,
> 				"Log size exhausted.\n");
> ```

one line, please



_Code quote:_
```C
		fprintf(stderr,
				"Log size exhausted.\n");
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1612)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[examples/07-atomic-write/client.c, line 131 at r1](https://reviewable.io/reviews/pmem/rpma/1612#-MxiIBVQ1J1BF65Gaphz:-MxiIQJR8runZCqy2y0R:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c0c6f07b60eeb50f1cd5d2bbca14064a2c458dd8/examples/07-atomic-write/client.c#L131)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The same issue.
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 141 at r1](https://reviewable.io/reviews/pmem/rpma/1612#-MxiI6ppAAZu-wJyyHK9:-MxiIRftAhcX_i5kVKYz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c0c6f07b60eeb50f1cd5d2bbca14064a2c458dd8/examples/07-atomic-write/client.c#L141)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

one line, please
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1612)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/1612#-MxiIZudCEVPrwKiW3t5):*
if



_Code quote:_
```
if if
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1612)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ldorau)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/1612#-MxiIZudCEVPrwKiW3t5):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

if
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1612)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1612#-:-MxiJUjL7X1k4iNaul-M:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1612#-:-MxiLVBQ1IKPlmZSrDd5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
