### PR TITLE
rpma: improve DEVELOPMENT.md file

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1871)

### CODE REVIEW

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1871#-:-N5JdcJB9bN-7Kbq_Dxm:bg7igkv)* status: 0 of 1 files reviewed, all discussions resolved

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1871)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[`DEVELOPMENT.md` line 117 at r1](https://reviewable.io/reviews/pmem/rpma/1871#-N5Jo2cj0spcEYA8BOAB:-N5Jo2cj0spcEYA8BOAC:bjrxiip) ([raw file](https://github.com/pmem/rpma/blob/c51402cbc1640660cddcf7eef6af64bc2efa0e3f/DEVELOPMENT.md#L117)):*
> ```Markdown
> The integration tests are implemented as examples run together with the fault injection mechanism.
> 
> In order to run integration tests on SoftRoCE/RDMA HW, set following environment variables:
> ```

the integration tests



_Code quote:_
```Markdown
integration tests
```
___
*[`DEVELOPMENT.md` line 117 at r1](https://reviewable.io/reviews/pmem/rpma/1871#-N5Jo4vM71TVS3ET2wQY:-N5Jo4vM71TVS3ET2wQZ:bcyv79v) ([raw file](https://github.com/pmem/rpma/blob/c51402cbc1640660cddcf7eef6af64bc2efa0e3f/DEVELOPMENT.md#L117)):*
> ```Markdown
> The integration tests are implemented as examples run together with the fault injection mechanism.
> 
> In order to run integration tests on SoftRoCE/RDMA HW, set following environment variables:
> ```

the following environment variables:



_Code quote:_
```Markdown
following environment variables:
```
___
*[`DEVELOPMENT.md` line 118 at r1](https://reviewable.io/reviews/pmem/rpma/1871#-N5Jp7Np9Z6hHDzqGQa9:-N5Jp7Np9Z6hHDzqGQaA:b-bjz7o) ([raw file](https://github.com/pmem/rpma/blob/c51402cbc1640660cddcf7eef6af64bc2efa0e3f/DEVELOPMENT.md#L118)):*
> ```Markdown
> 
> In order to run integration tests on SoftRoCE/RDMA HW, set following environment variables:
>  - the `RPMA_TESTING_IP` to an IP address of a configured RDMA-capable network interface
> ```

```
 - `DEBUG_FAULT_INJECTION` to `ON` and
 - `RPMA_TESTING_IP` to an IP address of a configured RDMA-capable network interface
```



_Code quote:_
```Markdown
 - the `RPMA_TESTING_IP` to an IP address of a configured RDMA-capable network interface
 - the `DEBUG_FAULT_INJECTION` to `ON`
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1871)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[`DEVELOPMENT.md` line 117 at r1](https://reviewable.io/reviews/pmem/rpma/1871#-N5Jo2cj0spcEYA8BOAB:-N5JqKJc-cj6gf3aLILz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c51402cbc1640660cddcf7eef6af64bc2efa0e3f/DEVELOPMENT.md#L117)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

the integration tests
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 117 at r1](https://reviewable.io/reviews/pmem/rpma/1871#-N5Jo4vM71TVS3ET2wQY:-N5JqOn9CGaYeSvvK7PJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c51402cbc1640660cddcf7eef6af64bc2efa0e3f/DEVELOPMENT.md#L117)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

the following environment variables:
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 118 at r1](https://reviewable.io/reviews/pmem/rpma/1871#-N5Jp7Np9Z6hHDzqGQa9:-N5JqYgJDrsIi9GNFGdk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c51402cbc1640660cddcf7eef6af64bc2efa0e3f/DEVELOPMENT.md#L118)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
 - `DEBUG_FAULT_INJECTION` to `ON` and
 - `RPMA_TESTING_IP` to an IP address of a configured RDMA-capable network interface
```
</blockquote></details>

Done.

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1871)* status: all files reviewed (commit messages unreviewed), 4 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[`DEVELOPMENT.md` line 128 at r2](https://reviewable.io/reviews/pmem/rpma/1871#-N5Jww83Bxv0vURGxSzd:-N5Jww83Bxv0vURGxSze:b-7llaml) ([raw file](https://github.com/pmem/rpma/blob/8c1c66a298eff5f57f65cdc2209767e65135c5a8/DEVELOPMENT.md#L128)):*
> ```Markdown
> from the build directory or
> 
> ```sh
> ```

@osalyk can you also fix/extend documentation to reflect all ``run-all-examples.sh`` parameters:
```
# Usage: run-all-examples.sh <binary-examples-directory> [--valgrind|--fault-injection]
#                            [--stop-on-failure] [<pmem-path>] [IP_address] [port]
``` 



_Code quote:_
```Markdown
```sh
$ ./examples/run-all-examples.sh ./build/examples/ --fault-injection
```
```


<!-- Sent from Reviewable.io -->

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1871)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`DEVELOPMENT.md` line 128 at r2](https://reviewable.io/reviews/pmem/rpma/1871#-N5Jww83Bxv0vURGxSzd:-N5K-wjA-IisvMubp_e1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8c1c66a298eff5f57f65cdc2209767e65135c5a8/DEVELOPMENT.md#L128)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

@osalyk can you also fix/extend documentation to reflect all ``run-all-examples.sh`` parameters:
```
# Usage: run-all-examples.sh <binary-examples-directory> [--valgrind|--fault-injection]
#                            [--stop-on-failure] [<pmem-path>] [IP_address] [port]
``` 
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1871)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`DEVELOPMENT.md` line 120 at r3](https://reviewable.io/reviews/pmem/rpma/1871#-N5K17v74dNC6aLUPBrF:-N5K17v81i2L3NweFppP:b533b5p) ([raw file](https://github.com/pmem/rpma/blob/334b87945b5e273576f24e65d4a1062c7b22bc60/DEVELOPMENT.md#L120)):*
> ```Markdown
>  - `DEBUG_FAULT_INJECTION` to `ON` and
>  - `RPMA_TESTING_IP` to an IP address of a configured RDMA-capable network interface
> and then they can be started using one of the following commands:
> ```

In order to run the integration tests on SoftRoCE or RDMA HW:
1) set the `RPMA_TESTING_IP` environment variable to an IP address of a configured RDMA-capable network interface:
```sh
$ export RPMA_TESTING_IP=192.168.0.1 # insert your own IP address here
```

2) build the librpma library with the `TESTS_RDMA_CONNECTION` and `DEBUG_FAULT_INJECTION` CMake variables set to `ON`:
```sh
$ cd build
$ cmake -DCMAKE_BUILD_TYPE=Debug -DTESTS_RDMA_CONNECTION=ON -DDEBUG_FAULT_INJECTION=ON ..
$ make -j$(nproc)
```

and then the integration tests can be started using one of the following commands:



_Code quote:_
```Markdown
In order to run the integration tests on SoftRoCE/RDMA HW, set the following environment variables:
 - `DEBUG_FAULT_INJECTION` to `ON` and
 - `RPMA_TESTING_IP` to an IP address of a configured RDMA-capable network interface
and then they can be started using one of the following commands:
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1871)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`DEVELOPMENT.md` line 134 at r3](https://reviewable.io/reviews/pmem/rpma/1871#-N5K1jix2E7Xq20WgjH4:-N5K1jix2E7Xq20WgjH5:bilrnxj) ([raw file](https://github.com/pmem/rpma/blob/334b87945b5e273576f24e65d4a1062c7b22bc60/DEVELOPMENT.md#L134)):*
> ```Markdown
> from the main directory of the librpma repository.
> 
> To see all available configuration options please take a look at the help:
> ```

`at the help message printed out by the following command:`



_Code quote:_
```Markdown
at the help:
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1871)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`DEVELOPMENT.md` line 120 at r3](https://reviewable.io/reviews/pmem/rpma/1871#-N5K17v74dNC6aLUPBrF:-N5K2rtu1VL5PwMZQxfU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/334b87945b5e273576f24e65d4a1062c7b22bc60/DEVELOPMENT.md#L120)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

In order to run the integration tests on SoftRoCE or RDMA HW:
1) set the `RPMA_TESTING_IP` environment variable to an IP address of a configured RDMA-capable network interface:
```sh
$ export RPMA_TESTING_IP=192.168.0.1 # insert your own IP address here
```

2) build the librpma library with the `TESTS_RDMA_CONNECTION` and `DEBUG_FAULT_INJECTION` CMake variables set to `ON`:
```sh
$ cd build
$ cmake -DCMAKE_BUILD_TYPE=Debug -DTESTS_RDMA_CONNECTION=ON -DDEBUG_FAULT_INJECTION=ON ..
$ make -j$(nproc)
```

and then the integration tests can be started using one of the following commands:
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 134 at r3](https://reviewable.io/reviews/pmem/rpma/1871#-N5K1jix2E7Xq20WgjH4:-N5K2yQN5b3SNRI7zz2A:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/334b87945b5e273576f24e65d4a1062c7b22bc60/DEVELOPMENT.md#L134)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`at the help message printed out by the following command:`
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1871#-:-N5K3cHWDu-kbTcDh2zB:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1871#-:-N5K5DmbB0up1m4Qgnle:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1871)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1871)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
