### PR TITLE
rpma: improve comments

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/483)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/483)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[src/peer.c, line 77 at r1](https://reviewable.io/reviews/pmem/rpma/483#-MIPGYE16FtxqwmyRH2z:-MIPGYE16FtxqwmyRH3-:b-6ndns6) ([raw file](https://github.com/pmem/rpma/blob/cf90150d29013f921a971e53638d4372de5cb3a1/src/peer.c#L77)):*
> ```C
> 	/*
> 	 * The actual capabilities and properties of the created QP
> 	 * are returned through qp_init_attr
> ```

You are missing `.` at the end of the sentence.
___
*[tests/unit/mr/mr-descriptor.c, line 402 at r1](https://reviewable.io/reviews/pmem/rpma/483#-MIPGeUv6lxXyx3qMY0A:-MIPGeUv6lxXyx3qMY0B:b-fuhp06) ([raw file](https://github.com/pmem/rpma/blob/cf90150d29013f921a971e53638d4372de5cb3a1/tests/unit/mr/mr-descriptor.c#L402)):*
> ```C
> 		int flush_type = (i % 2) ?
> 		RPMA_MR_USAGE_FLUSH_TYPE_PERSISTENT :
> 		RPMA_MR_USAGE_FLUSH_TYPE_VISIBILITY;
> ```

Indentation.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/483)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[src/peer.c, line 77 at r1](https://reviewable.io/reviews/pmem/rpma/483#-MIPGYE16FtxqwmyRH2z:-MIPH3CL89N7RNiutYqZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cf90150d29013f921a971e53638d4372de5cb3a1/src/peer.c#L77)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You are missing `.` at the end of the sentence.
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-descriptor.c, line 402 at r1](https://reviewable.io/reviews/pmem/rpma/483#-MIPGeUv6lxXyx3qMY0A:-MIPHTqwB32Rm0OlgGRX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cf90150d29013f921a971e53638d4372de5cb3a1/tests/unit/mr/mr-descriptor.c#L402)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Indentation.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/483#-:-MIPK8q-6fiuv18nEKWs:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/483#-:-MIPaRRyBJMHX_FV7iM1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
