### PR TITLE
rpma: scaffolding of the DEVELOPMENT.md file

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1808)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1808)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1808)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
IMHO the documentation of unit tests should be a part of CONTRIBUTING.md. Unit tests are not required during the installation step.

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1808#-:-N3xYilNEIDG7oIYHGJd:b-e319e6)* status: all files reviewed, 5 unresolved discussions (waiting on @osalyk)

___
*[`CI_ENVIRONMENT.md` line 1 at r1](https://reviewable.io/reviews/pmem/rpma/1808#-N3xY5ql8NBS-XZXji2N:-N3xY5ql8NBS-XZXji2O:bm46p9n) ([raw file](https://github.com/pmem/rpma/blob/6209a6f4db6e41cf4fa7db8149acf1331434bb5c/CI_ENVIRONMENT.md#L1)):*
> ```Markdown
> # CI ENVIRONMENT
> ```

`TESTING`



_Code quote:_
```Markdown
CI ENVIRONMENT
```
___
*[`CI_ENVIRONMENT.md` line 5 at r1](https://reviewable.io/reviews/pmem/rpma/1808#-N3xXndaEmC_7nrkiDZF:-N3xXndaEmC_7nrkiDZG:b-tksbff) ([raw file](https://github.com/pmem/rpma/blob/6209a6f4db6e41cf4fa7db8149acf1331434bb5c/CI_ENVIRONMENT.md#L5)):*
> ```Markdown
> This document describes how to prepare CI environment with MT tests and integration tests execution.
> 
> ## Stable CI
> ```

What do you mean by `Stable CI`? What should be described here?



_Code quote:_
```Markdown
Stable CI
```
___
*[`CI_ENVIRONMENT.md` line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1808#-N3xYELo9CR0INbWBci8:-N3xYELo9CR0INbWBci9:b-s9s4zv) ([raw file](https://github.com/pmem/rpma/blob/6209a6f4db6e41cf4fa7db8149acf1331434bb5c/CI_ENVIRONMENT.md#L13)):*
> ```Markdown
> XXX
> 
> ### on SoftRoCE
> ```

### Run all tests on SoftRoCE



_Code quote:_
```Markdown
### on SoftRoCE
```
___
*[`CI_ENVIRONMENT.md` line 17 at r1](https://reviewable.io/reviews/pmem/rpma/1808#-N3xYLEc30M6D7GwUpto:-N3xYLEc30M6D7GwUptp:b-i0y1qb) ([raw file](https://github.com/pmem/rpma/blob/6209a6f4db6e41cf4fa7db8149acf1331434bb5c/CI_ENVIRONMENT.md#L17)):*
> ```Markdown
> XXX
> 
> ### on RDMA HW
> ```

### Run all tests on RDMA HW



_Code quote:_
```Markdown
### on RDMA HW
```
___
*[`CI_ENVIRONMENT.md` line 21 at r1](https://reviewable.io/reviews/pmem/rpma/1808#-N3xYYrIEyI5pQOCKwVj:-N3xYYrIEyI5pQOCKwVk:b-zaeawb) ([raw file](https://github.com/pmem/rpma/blob/6209a6f4db6e41cf4fa7db8149acf1331434bb5c/CI_ENVIRONMENT.md#L21)):*
> ```Markdown
> XXX
> 
> ## Run integration tests
> ```

on SoftRoCE or on RDMA HW?



_Code quote:_
```Markdown
Run integration tests
```

**Review by grom72 — APPROVED** [review]
+1

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1808#-:-N3xeiDW18f2uVTR9thH:b2ngthb)* status: all files reviewed, 5 unresolved discussions (waiting on @osalyk)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1808)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[`CI_ENVIRONMENT.md` line 5 at r1](https://reviewable.io/reviews/pmem/rpma/1808#-N3xXndaEmC_7nrkiDZF:-N3xenOA6baNXWqJu2Id:bg9sfa0) ([raw file](https://github.com/pmem/rpma/blob/6209a6f4db6e41cf4fa7db8149acf1331434bb5c/CI_ENVIRONMENT.md#L5)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

What do you mean by `Stable CI`? What should be described here?
</blockquote></details>

Continuous Integration Environment Setup

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1808)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)

___
*[`TESTING.md` line 5 at r2](https://reviewable.io/reviews/pmem/rpma/1808#-N3xlw527RxqOPs2KWEY:-N3xlw527RxqOPs2KWEZ:b7fgn) ([raw file](https://github.com/pmem/rpma/blob/eedf5fb1b7e912ce69140928b6fa4c70cfa412bd/TESTING.md#L5)):*
> ```Markdown
> This document describes how to prepare environment with MT tests and integration tests execution.
> 
> ## Run all tests on SoftRoCE
> ```

It seems that `all tests` should contain also `integration tests` ...
So do you mean all unit tests here?



_Code quote:_
```Markdown
all tests
```
___
*[`TESTING.md` line 9 at r2](https://reviewable.io/reviews/pmem/rpma/1808#-N3xmHWZ661YuuMBY9oM:-N3xmHWZ661YuuMBY9oN:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/eedf5fb1b7e912ce69140928b6fa4c70cfa412bd/TESTING.md#L9)):*
> ```Markdown
> XXX
> 
> ## Run all tests on RDMA HW
> ```

.



_Code quote:_
```Markdown
all tests
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1808)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)

___
*[`INSTALL.md` line 131 at r2](https://reviewable.io/reviews/pmem/rpma/1808#-N3xmOc4-CavTCGWdu4S:-N3xmOc4-CavTCGWdu4T:by8j7o5) ([raw file](https://github.com/pmem/rpma/blob/eedf5fb1b7e912ce69140928b6fa4c70cfa412bd/INSTALL.md#L131)):*
> ```Markdown
> ## Testing
> 
> To learn how to run all tests, please see:
> ```

In order to learn ...



_Code quote:_
```Markdown
To learn
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1808)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1808#-N3xmbUA70f7tZWHsfnv:-N3xmbUA70f7tZWHsfnw:bhtz7uz) (no related file):*
`error: no BSD-3-Clause SPDX tag in file: /rpma/TESTING.md`

It seems that this file should be excluded ...

___

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1808)* status: all files reviewed, 4 unresolved discussions (waiting on @haichangsi, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1808#-N3xmbUA70f7tZWHsfnv:-N3xoMlFAV7vIYUSH_Oz:b32v57) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`error: no BSD-3-Clause SPDX tag in file: /rpma/TESTING.md`

It seems that this file should be excluded ...
</blockquote></details>

+1

___

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1808)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)

___
*[`INSTALL.md` line 131 at r2](https://reviewable.io/reviews/pmem/rpma/1808#-N3xmOc4-CavTCGWdu4S:-N3xr2zJ2kl4KAJc-UZ3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/eedf5fb1b7e912ce69140928b6fa4c70cfa412bd/INSTALL.md#L131)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

In order to learn ...
</blockquote></details>

Done.
___
*[`CI_ENVIRONMENT.md` line 5 at r1](https://reviewable.io/reviews/pmem/rpma/1808#-N3xXndaEmC_7nrkiDZF:-N3xrE9o9OI-RJRIuvHx:bmmlrha) ([raw file](https://github.com/pmem/rpma/blob/6209a6f4db6e41cf4fa7db8149acf1331434bb5c/CI_ENVIRONMENT.md#L5)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Continuous Integration Environment Setup
</blockquote></details>

This part is already included in the INSTALL.md file
___
*[`TESTING.md` line 3 at r2](https://reviewable.io/reviews/pmem/rpma/1808#-N3xoWHc6fZPTAq04-OI:-N3xrPoN-kp6ZxLC-J78:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/eedf5fb1b7e912ce69140928b6fa4c70cfa412bd/TESTING.md#L3)):*
> ```Markdown
> # TESTING
> 
> This document describes how to prepare environment with MT tests and integration tests execution.
> ```

Done.
___
*[`TESTING.md` line 5 at r2](https://reviewable.io/reviews/pmem/rpma/1808#-N3xlw527RxqOPs2KWEY:-N3xrVFH8G0E7bpt65wG:b4v1mmo) ([raw file](https://github.com/pmem/rpma/blob/eedf5fb1b7e912ce69140928b6fa4c70cfa412bd/TESTING.md#L5)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It seems that `all tests` should contain also `integration tests` ...
So do you mean all unit tests here?
</blockquote></details>

Unit and multithreaded tests. Integration tests will run differently (unless I'm mistaken) so I added a separate paragraph

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1808)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)

___
*[`TESTING.md` line 5 at r2](https://reviewable.io/reviews/pmem/rpma/1808#-N3xlw527RxqOPs2KWEY:-N3xzgkh2h14yBxJ-XCI:b-4l499r) ([raw file](https://github.com/pmem/rpma/blob/eedf5fb1b7e912ce69140928b6fa4c70cfa412bd/TESTING.md#L5)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Unit and multithreaded tests. Integration tests will run differently (unless I'm mistaken) so I added a separate paragraph
</blockquote></details>

OK, but "all" still means all (unless I'm mistaken ;-))

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1808)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1808#-N3xmbUA70f7tZWHsfnv:-N3y0XcABsvQK5Oe8L6N:b-896fix) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

___

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1808)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1808#-N3xmbUA70f7tZWHsfnv:-N3y1oG34FNFEGFl8z2M:b-s2bhwo) (no related file):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`-e 'TEST*'` should be removed from `utils/check_license/check-headers.sh`

___
___
*[`utils/check_license/file-exceptions.sh` line 7 at r4](https://reviewable.io/reviews/pmem/rpma/1808#-N3y1TGk2HAwNE27zizA:-N3y1TGk2HAwNE27zizB:b-1ip45b) ([raw file](https://github.com/pmem/rpma/blob/ab4d8687d3622fe0057817ea8f397324ef4debac/utils/check_license/file-exceptions.sh#L7)):*
> ```Shell
> # file-exceptions.sh - filter out files not checked for copyright and license
> 
> grep -v -E -e 'TESTING.md'
> ```

No, please revert.

`-e 'TEST*'` should be removed from `utils/check_license/check-headers.sh`



_Code quote:_
```Shell
grep -v -E -e 'TESTING.md'
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1808)* status: 1 of 4 files reviewed, 5 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1808#-N3xmbUA70f7tZWHsfnv:-N3y2lStB1s5cl7TB5bB:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`-e 'TEST*'` should be removed from `utils/check_license/check-headers.sh`
</blockquote></details>

Done.

___
___
*[`utils/check_license/file-exceptions.sh` line 7 at r4](https://reviewable.io/reviews/pmem/rpma/1808#-N3y1TGk2HAwNE27zizA:-N3y3-6t9EmkQ9yPL1ul:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ab4d8687d3622fe0057817ea8f397324ef4debac/utils/check_license/file-exceptions.sh#L7)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No, please revert.

`-e 'TEST*'` should be removed from `utils/check_license/check-headers.sh`
</blockquote></details>

Done.
___
*[`TESTING.md` line 5 at r2](https://reviewable.io/reviews/pmem/rpma/1808#-N3xlw527RxqOPs2KWEY:-N3y2wH_4p_8QHbftZPB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/eedf5fb1b7e912ce69140928b6fa4c70cfa412bd/TESTING.md#L5)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK, but "all" still means all (unless I'm mistaken ;-))
</blockquote></details>

Done.
___
*[`TESTING.md` line 9 at r2](https://reviewable.io/reviews/pmem/rpma/1808#-N3xmHWZ661YuuMBY9oM:-N3y2y_l8zYwHSL_94sE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/eedf5fb1b7e912ce69140928b6fa4c70cfa412bd/TESTING.md#L9)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1808)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)

___
*[`TESTING.md` line 3 at r6](https://reviewable.io/reviews/pmem/rpma/1808#-N3yGxY7BTV7G0MvXoWN:-N3yGxY7BTV7G0MvXoWO:b-1h8jud) ([raw file](https://github.com/pmem/rpma/blob/a905562fc96e412e5469cf9b97139de499b550f5/TESTING.md#L3)):*
> ```Markdown
> # TESTING
> 
> This document describes how to prepare environment with the execution of multi-threaded and integration tests.
> ```

```
... the environment for execution of all available kinds of tests:
- unit tests,
- multi-threaded (MT) test and
- integration tests.
```



_Code quote:_
```Markdown
environment with the execution of multi-threaded and integration tests.
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1808)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)

___
*[`TESTING.md` line 3 at r6](https://reviewable.io/reviews/pmem/rpma/1808#-N3yGxY7BTV7G0MvXoWN:-N3yHs8sA9pZ0o3nRKpP:b-1cfrwn) ([raw file](https://github.com/pmem/rpma/blob/a905562fc96e412e5469cf9b97139de499b550f5/TESTING.md#L3)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
... the environment for execution of all available kinds of tests:
- unit tests,
- multi-threaded (MT) test and
- integration tests.
```
</blockquote></details>

multi-threaded (MT) testS

**Review by ldorau — COMMENTED** [review]
No, I think that all kinds of test should be described here and there should be a link to this document added to CONTRIBUTING.md.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1808#-:-N3yIFCO6Vv0UK9Tf4ey:b-29hr14)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1808)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[`TESTING.md` line 3 at r6](https://reviewable.io/reviews/pmem/rpma/1808#-N3yGxY7BTV7G0MvXoWN:-N3ySWRfAwUC_1h5eNzN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a905562fc96e412e5469cf9b97139de499b550f5/TESTING.md#L3)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

multi-threaded (MT) testS
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1808)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72 and @haichangsi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1808)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)

___
*[`TESTING.md` line 3 at r7](https://reviewable.io/reviews/pmem/rpma/1808#-N3zWhad78Rqc4g8-8GW:-N3zWhad78Rqc4g8-8GX:b-7y5n7l) ([raw file](https://github.com/pmem/rpma/blob/f408e03ee8821ddfe6c9786f96bbaac4a18bfc78/TESTING.md#L3)):*
> ```Markdown
> # TESTING
> 
> This document describes how to prepare environment for execution of all available kinds of tests:
> ```

the environment



_Code quote:_
```Markdown
environment
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1808)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[`TESTING.md` line 3 at r7](https://reviewable.io/reviews/pmem/rpma/1808#-N3zWhad78Rqc4g8-8GW:-N40pOANC3hwkPOBeOYT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f408e03ee8821ddfe6c9786f96bbaac4a18bfc78/TESTING.md#L3)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

the environment
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1808)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72 and @haichangsi)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1808)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72 and @haichangsi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1808)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)

___
*[`INSTALL.md` line 132 at r9](https://reviewable.io/reviews/pmem/rpma/1808#-N41mrks5Q669V333blA:-N41mrks5Q669V333blB:b70esn5) ([raw file](https://github.com/pmem/rpma/blob/4f994197e25ea055ac624af9cd7400f1269cc686/INSTALL.md#L132)):*
> ```Markdown
> 
> In order to learn how to run all tests, please see:
> [TESTING.md](TESTING.md)
> ```

Update, please
It can also fit into one line.



_Code quote:_
```Markdown
[TESTING.md](TESTING.md)
```
___
*[`DEVELOPMENT.md` line 7 at r9](https://reviewable.io/reviews/pmem/rpma/1808#-N41mfpT3OoTYzS9fD7S:-N41mfpT3OoTYzS9fD7T:b-nxn94o) ([raw file](https://github.com/pmem/rpma/blob/4f994197e25ea055ac624af9cd7400f1269cc686/DEVELOPMENT.md#L7)):*
> ```Markdown
> # TESTING
> 
> This document describes how to prepare the environment for execution of all available kinds of tests:
> ```

This section



_Code quote:_
```Markdown
This document
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1808)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)

___
*[`utils/check_license/check-headers.sh` line 98 at r9](https://reviewable.io/reviews/pmem/rpma/1808#-N41n0KwEKLQPslIfSxV:-N41n0KwEKLQPslIfSxW:b-8ce3qk) ([raw file](https://github.com/pmem/rpma/blob/0168ae272e1c35a8000f43796bfc7cb107e13293/utils/check_license/check-headers.sh#L98)):*
> ```Shell
> FILES=$($GIT $GIT_COMMAND | ${SOURCE_ROOT}/utils/check_license/file-exceptions.sh | \
> 	grep    -E -e '*\.[chs]$' -e '*\.[ch]pp$' -e '*\.sh$' \
> 		   -e '*\.py$' -e '*\.link$' -e 'Makefile*' -e 'TEST*' \
> ```

This change is not needed in this PR now.



_Code quote:_
```Shell
 -e 'TEST*' 
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1808)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[`INSTALL.md` line 132 at r9](https://reviewable.io/reviews/pmem/rpma/1808#-N41mrks5Q669V333blA:-N41oFVxBtGjfvqIVegk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4f994197e25ea055ac624af9cd7400f1269cc686/INSTALL.md#L132)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Update, please
It can also fit into one line.
</blockquote></details>

Done.
___
*[`utils/check_license/check-headers.sh` line 98 at r9](https://reviewable.io/reviews/pmem/rpma/1808#-N41n0KwEKLQPslIfSxV:-N41oTE04Ji9gBSoEncN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0168ae272e1c35a8000f43796bfc7cb107e13293/utils/check_license/check-headers.sh#L98)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

This change is not needed in this PR now.
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 7 at r9](https://reviewable.io/reviews/pmem/rpma/1808#-N41mfpT3OoTYzS9fD7S:-N41o3da9_hJb5blWd44:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4f994197e25ea055ac624af9cd7400f1269cc686/DEVELOPMENT.md#L7)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

This section
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 3 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1808)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1808)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[`INSTALL.md` line 132 at r9](https://reviewable.io/reviews/pmem/rpma/1808#-N41mrks5Q669V333blA:-N41qVszEXsFIWX7DrPa:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4f994197e25ea055ac624af9cd7400f1269cc686/INSTALL.md#L132)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not yet - it is not TESTING now
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1808)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72 and @haichangsi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1808#-:-N42bk_bB18agSuCJYdh:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72 and @haichangsi)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1808#-:-N42kUhx0fQn8AduyonI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

___
*[`CI_ENVIRONMENT.md` line 5 at r1](https://reviewable.io/reviews/pmem/rpma/1808#-N3xXndaEmC_7nrkiDZF:-N42_nOpBWBHTZGLi8SQ:b-o3a2xx) ([raw file](https://github.com/pmem/rpma/blob/6209a6f4db6e41cf4fa7db8149acf1331434bb5c/CI_ENVIRONMENT.md#L5)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

This part is already included in the INSTALL.md file
</blockquote></details>

No - INSTALL.md should cover only these items that are needed to build the library (no UT, no documentation, etc)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1808)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1808)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi and @osalyk)

___
*[`INSTALL.md` line 131 at r11](https://reviewable.io/reviews/pmem/rpma/1808#-N467uVc4V47a9ATAO3i:-N467uVc4V47a9ATAO3j:b-nlaqx9) ([raw file](https://github.com/pmem/rpma/blob/2409eba90ac03be6e614e15be28e1b627742a497/INSTALL.md#L131)):*
> ```Markdown
> ## Testing
> 
> In order to learn how to run all tests, please see [TESTING](DEVELOPMENT.md#TESTING) section in [DEVELOPMENT.md](DEVELOPMENT.md) file.
> ```

[Testing](DEVELOPMENT.md#Testing) 



_Code quote:_
```Markdown
[TESTING](DEVELOPMENT.md#TESTING) 
```
___
*[`CI_ENVIRONMENT.md` line 5 at r1](https://reviewable.io/reviews/pmem/rpma/1808#-N3xXndaEmC_7nrkiDZF:-N4673Js06yzXAfo5u8T:b-maw5dm) ([raw file](https://github.com/pmem/rpma/blob/6209a6f4db6e41cf4fa7db8149acf1331434bb5c/CI_ENVIRONMENT.md#L5)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

No - INSTALL.md should cover only these items that are needed to build the library (no UT, no documentation, etc)
</blockquote></details>

@grom72 In INSTALL.md we have:
```
## Testing

In order to learn how to run all tests, please see [TESTING](DEVELOPMENT.md#TESTING) section in [DEVELOPMENT.md](DEVELOPMENT.md) file.
```

So we have to have "Testing" here too.

Or maybe I do not understand what the problem is?
___
*[`DEVELOPMENT.md` line 5 at r11](https://reviewable.io/reviews/pmem/rpma/1808#-N467koJC5rYF57NuIDH:-N467koJC5rYF57NuIDI:bgwlqmg) ([raw file](https://github.com/pmem/rpma/blob/2409eba90ac03be6e614e15be28e1b627742a497/DEVELOPMENT.md#L5)):*
> ```Markdown
> XXX
> 
> # TESTING
> ```

`# Testing`



_Code quote:_
```Markdown
# TESTING
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1808)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[`INSTALL.md` line 131 at r11](https://reviewable.io/reviews/pmem/rpma/1808#-N467uVc4V47a9ATAO3i:-N46BhcfAOqMMa7uhs9y:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2409eba90ac03be6e614e15be28e1b627742a497/INSTALL.md#L131)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

[Testing](DEVELOPMENT.md#Testing) 
</blockquote></details>

Done.
___
*[`CI_ENVIRONMENT.md` line 5 at r1](https://reviewable.io/reviews/pmem/rpma/1808#-N3xXndaEmC_7nrkiDZF:-N46BR4V-P5zd7IqjClm:bvsl110) ([raw file](https://github.com/pmem/rpma/blob/6209a6f4db6e41cf4fa7db8149acf1331434bb5c/CI_ENVIRONMENT.md#L5)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@grom72 In INSTALL.md we have:
```
## Testing

In order to learn how to run all tests, please see [TESTING](DEVELOPMENT.md#TESTING) section in [DEVELOPMENT.md](DEVELOPMENT.md) file.
```

So we have to have "Testing" here too.

Or maybe I do not understand what the problem is?
</blockquote></details>

This comment was about the previous version of the scaffold
___
*[`DEVELOPMENT.md` line 5 at r11](https://reviewable.io/reviews/pmem/rpma/1808#-N467koJC5rYF57NuIDH:-N46B_M0CYvULqQurGmb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2409eba90ac03be6e614e15be28e1b627742a497/DEVELOPMENT.md#L5)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`# Testing`
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 2 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1808)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
