### PR TITLE
tools: Part.__init__() unittests and docstring

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1134)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1134)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1134)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/tests/lib/part/test_init.py, line 99 at r2](https://reviewable.io/reviews/pmem/rpma/1134#-Me-DfPo6VNQwMuk-JkY:-Me-DfPo6VNQwMuk-JkZ:bfgjxel) ([raw file](https://github.com/pmem/rpma/blob/68c3fce7cb0358a5d16d95858490cfe4c5d1b70d/tools/perf/tests/lib/part/test_init.py#L99)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> STR_LIST_DUMMY_3 = {
>     STRING_DUMMY_1,
>     STRING_DUMMY_1,
>     STRING_DUMMY_1,
>     STRING_DUMMY_1,
>     STRING_DUMMY_1
> }
> ```
</details>


`[...]`

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1134)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/tests/lib/part/test_init.py, line 142 at r2](https://reviewable.io/reviews/pmem/rpma/1134#-Me-E1n04j3QIuPPhq1b:-Me-E1n04j3QIuPPhq1c:b-pk7cni) ([raw file](https://github.com/pmem/rpma/blob/68c3fce7cb0358a5d16d95858490cfe4c5d1b70d/tools/perf/tests/lib/part/test_init.py#L142)):*
> ```Python
>     assert dictcmp(part.variables, expected_variables)
> 
> @pytest.mark.parametrize('input_json,expected_variables', [
> ```

Those 3 tests fail:
```
FAILED tools/perf/tests/lib/part/test_init.py::test_nested_lines[input_json0-expected_variables0] - AssertionError: assert False
FAILED tools/perf/tests/lib/part/test_init.py::test_nested_lines[input_json1-expected_variables1] - AssertionError: assert False
FAILED tools/perf/tests/lib/part/test_init.py::test_nested_lines[input_json2-expected_variables2] - AssertionError: assert False
```

For example in case of `input_json2-expected_variables2`:
```
<class 'dict'>
{'a': {'b': {'c': {'d': {'e': 'jmvfzrvvul\njmvfzrvvul\njmvfzrvvul\njmvfzrvvul\njmvfzrvvul'}}}}, 'f': {'g': {'h': {'i': 'jmvfzrvvul\njmvfzrvvul\njmvfzrvvul\njmvfzrvvul\njmvfzrvvul'}}}}
<class 'dict'>
{'a': {'b': {'c': {'d': {'e': 'jlkfsdlkjrwklj'}}}}, 'f': {'g': {'h': {'i': 'jlkfsdlkjrwklj'}}}}
```

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1134)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1134)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/tests/lib/part/test_init.py, line 105 at r2](https://reviewable.io/reviews/pmem/rpma/1134#-Me-GdN82LDdISpV3jTZ:-Me-GdN82LDdISpV3jT_:b-3apmv5) ([raw file](https://github.com/pmem/rpma/blob/68c3fce7cb0358a5d16d95858490cfe4c5d1b70d/tools/perf/tests/lib/part/test_init.py#L105)):*
> ```
> STRING_DUMMY_3_CONCAT = 'jlkfsdlkjrwklj'
> ```

The following change fixes those 3 failing tests:
```
STRING_DUMMY_3_CONCAT = 4 * (STRING_DUMMY_1 + '\n') + STRING_DUMMY_1
```

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1134)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1134)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1134)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/tests/lib/part/test_init.py, line 105 at r2](https://reviewable.io/reviews/pmem/rpma/1134#-Me-GdN82LDdISpV3jTZ:-Me0Tspy5nhl1Ydrnkxi:b-4404qi) ([raw file](https://github.com/pmem/rpma/blob/68c3fce7cb0358a5d16d95858490cfe4c5d1b70d/tools/perf/tests/lib/part/test_init.py#L105)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> STRING_DUMMY_3_CONCAT = 'jlkfsdlkjrwklj'
> ```

The following change fixes those 3 failing tests:
```
STRING_DUMMY_3_CONCAT = 4 * (STRING_DUMMY_1 + '\n') + STRING_DUMMY_1
```

</blockquote></details>

It was failing because of an invalid mock. Fixed.
___
*[tools/perf/tests/lib/part/test_init.py, line 142 at r2](https://reviewable.io/reviews/pmem/rpma/1134#-Me-E1n04j3QIuPPhq1b:-Me0TybbC1xGbQeMjfmO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/68c3fce7cb0358a5d16d95858490cfe4c5d1b70d/tools/perf/tests/lib/part/test_init.py#L142)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Those 3 tests fail:
```
FAILED tools/perf/tests/lib/part/test_init.py::test_nested_lines[input_json0-expected_variables0] - AssertionError: assert False
FAILED tools/perf/tests/lib/part/test_init.py::test_nested_lines[input_json1-expected_variables1] - AssertionError: assert False
FAILED tools/perf/tests/lib/part/test_init.py::test_nested_lines[input_json2-expected_variables2] - AssertionError: assert False
```

For example in case of `input_json2-expected_variables2`:
```
<class 'dict'>
{'a': {'b': {'c': {'d': {'e': 'jmvfzrvvul\njmvfzrvvul\njmvfzrvvul\njmvfzrvvul\njmvfzrvvul'}}}}, 'f': {'g': {'h': {'i': 'jmvfzrvvul\njmvfzrvvul\njmvfzrvvul\njmvfzrvvul\njmvfzrvvul'}}}}
<class 'dict'>
{'a': {'b': {'c': {'d': {'e': 'jlkfsdlkjrwklj'}}}}, 'f': {'g': {'h': {'i': 'jlkfsdlkjrwklj'}}}}
```

</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1134)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1134#-:-Me3m9U_25Cwd62bqCyk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
@osalyk please review

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1134#-:-Me3slgL8Alt2PC2gXnX:bqeplii)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
Please rebase :goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1134#-:-Me4XdskDBJpIPX9vNxB:bl5leog)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1134)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1134#-:-Me4bMXk0Yir4TPz1m2g:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1134#-:-Me4cINJAAt0C_Cxr34O:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1134)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
