### PR TITLE
rpma: remove provider error

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/477)

### CODE REVIEW

**Comment by ldorau** [comment]
Tested on: https://github.com/ldorau/rpma/actions/runs/278224427

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 46 of 46 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/477)* status: all files reviewed, 17 unresolved discussions (waiting on @ldorau)

___
*[src/conn_req.c, line 202 at r1](https://reviewable.io/reviews/pmem/rpma/477#-MIOAxKY4zymO4Ud4S8l:-MIOAxKZCFAMVqxdEAdD:bc7t8yd) ([raw file](https://github.com/pmem/rpma/blob/86a1c9b5bae845c1034cbbc3e527455ac2dfaba7/src/conn_req.c#L202)):*
> ```C
> 	if (rdma_connect(req->id, conn_param)) {
> 		provider_error = errno;
> 		RPMA_LOG_ERROR_WITH_ERRNO(provider_error,
> ```

You can further simplify this part. `provider_error` seems unnecessary here.
___
*[src/peer.c, line 119 at r1](https://reviewable.io/reviews/pmem/rpma/477#-MIOByFw5oiztjUyDmyn:-MIOByFw5oiztjUyDmyo:bah51of) ([raw file](https://github.com/pmem/rpma/blob/86a1c9b5bae845c1034cbbc3e527455ac2dfaba7/src/peer.c#L119)):*
> ```C
> 	if (errno != EOPNOTSUPP) {
> 		RPMA_LOG_ERROR_WITH_ERRNO(errno,
> 			"ibv_reg_mr()");
> ```

It seems a lot of this calls can now take only a single line.
___
*[src/rpma.c, line 92 at r1](https://reviewable.io/reviews/pmem/rpma/477#-MIOCr03DmyaSi4BBnzc:-MIOCr03DmyaSi4BBnzd:bnpnlw9) ([raw file](https://github.com/pmem/rpma/blob/86a1c9b5bae845c1034cbbc3e527455ac2dfaba7/src/rpma.c#L92)):*
> ```C
> 	struct ibv_device_attr_ex attr = {{{0}}};
> 	errno = ibv_query_device_ex(dev, NULL /* input */,
> 			&attr);
> ```

Fits into a single line?
___
*[tests/unit/common/mocks-rpma-conn.c, line 31 at r1](https://reviewable.io/reviews/pmem/rpma/477#-MIOHJN-5Ie3AIvUr8MT:-MIOHJN-5Ie3AIvUr8MU:bzfwvq9) ([raw file](https://github.com/pmem/rpma/blob/86a1c9b5bae845c1034cbbc3e527455ac2dfaba7/tests/unit/common/mocks-rpma-conn.c#L31)):*
> ```C
> 	if (!conn) {
> 		int result = mock_type(int);
> 		if (result == RPMA_E_PROVIDER)
> ```

```
/* XXX validate the errno handling */
```
___
*[tests/unit/common/mocks-rpma-conn.c, line 54 at r1](https://reviewable.io/reviews/pmem/rpma/477#-MIOHPQjAPaI3r-EWIVA:-MIOHPQjAPaI3r-EWIVB:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/86a1c9b5bae845c1034cbbc3e527455ac2dfaba7/tests/unit/common/mocks-rpma-conn.c#L54)):*
> ```C
> 	int result = mock_type(int);
> 	if (result) {
> 		if (result == RPMA_E_PROVIDER)
> ```

.
___
*[tests/unit/common/mocks-rpma-flush.c, line 69 at r1](https://reviewable.io/reviews/pmem/rpma/477#-MIOHRFL7OXUwxMzH1an:-MIOHRFL7OXUwxMzH1ao:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/86a1c9b5bae845c1034cbbc3e527455ac2dfaba7/tests/unit/common/mocks-rpma-flush.c#L69)):*
> ```C
> 
> 	int ret = mock_type(int);
> 	if (ret == RPMA_E_PROVIDER)
> ```

.
___
*[tests/unit/common/mocks-rpma-info.c, line 31 at r1](https://reviewable.io/reviews/pmem/rpma/477#-MIOHSKZ5w_sKWpnSSwY:-MIOHSKZ5w_sKWpnSSwZ:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/86a1c9b5bae845c1034cbbc3e527455ac2dfaba7/tests/unit/common/mocks-rpma-info.c#L31)):*
> ```C
> 		assert_int_not_equal(result, 0);
> 
> 		if (result == RPMA_E_PROVIDER)
> ```

.
___
*[tests/unit/common/mocks-rpma-info.c, line 65 at r1](https://reviewable.io/reviews/pmem/rpma/477#-MIOHTHq-rpU99EbeIRl:-MIOHTHq-rpU99EbeIRm:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/86a1c9b5bae845c1034cbbc3e527455ac2dfaba7/tests/unit/common/mocks-rpma-info.c#L65)):*
> ```C
> 
> 	int ret = mock_type(int);
> 	if (ret == RPMA_E_PROVIDER)
> ```

.
___
*[tests/unit/common/mocks-rpma-info.c, line 84 at r1](https://reviewable.io/reviews/pmem/rpma/477#-MIOHUOmE3PBXU_eRI7f:-MIOHUOmE3PBXU_eRI7g:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/86a1c9b5bae845c1034cbbc3e527455ac2dfaba7/tests/unit/common/mocks-rpma-info.c#L84)):*
> ```C
> 
> 	int ret = mock_type(int);
> 	if (ret)
> ```

.
___
*[tests/unit/common/mocks-rpma-peer.c, line 29 at r1](https://reviewable.io/reviews/pmem/rpma/477#-MIOHWpT4ff7o9pIGcWt:-MIOHWpT4ff7o9pIGcWu:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/86a1c9b5bae845c1034cbbc3e527455ac2dfaba7/tests/unit/common/mocks-rpma-peer.c#L29)):*
> ```C
> 
> 	int result = mock_type(int);
> 	if (result == RPMA_E_PROVIDER)
> ```

.
___
*[tests/unit/common/mocks-rpma-peer.c, line 57 at r1](https://reviewable.io/reviews/pmem/rpma/477#-MIOHYPb1xAO9kPTgBHO:-MIOHYPb1xAO9kPTgBHP:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/86a1c9b5bae845c1034cbbc3e527455ac2dfaba7/tests/unit/common/mocks-rpma-peer.c#L57)):*
> ```C
> 	*ibv_mr_ptr = args->mr;
> 	if (*ibv_mr_ptr == NULL) {
> 		errno = args->verrno;
> ```

.
___
*[tests/unit/common/mocks-rpma-utils.c, line 29 at r1](https://reviewable.io/reviews/pmem/rpma/477#-MIOH_-h4kslAujIMorE:-MIOH_-h4kslAujIMorF:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/86a1c9b5bae845c1034cbbc3e527455ac2dfaba7/tests/unit/common/mocks-rpma-utils.c#L29)):*
> ```C
> 	if (*is_odp_capable == MOCK_ERR_PENDING) {
> 		int ret = mock_type(int);
> 		if (ret == RPMA_E_PROVIDER)
> ```

.
___
*[tests/unit/ep/ep-common.c, line 208 at r1](https://reviewable.io/reviews/pmem/rpma/477#-MIOHbYV4_SVfMtTDD2q:-MIOHbYV4_SVfMtTDD2r:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/86a1c9b5bae845c1034cbbc3e527455ac2dfaba7/tests/unit/ep/ep-common.c#L208)):*
> ```C
> 	assert_ptr_equal(info, MOCK_INFO);
> 
> 	errno = mock_type(int);
> ```

.
___
*[tests/unit/peer/peer-mr_reg.c, line 108 at r1](https://reviewable.io/reviews/pmem/rpma/477#-MIOFK455BcQaMcGPzPe:-MIOFK455BcQaMcGPzPf:b-867xyf) ([raw file](https://github.com/pmem/rpma/blob/86a1c9b5bae845c1034cbbc3e527455ac2dfaba7/tests/unit/peer/peer-mr_reg.c#L108)):*
> ```C
> #ifdef ON_DEMAND_PAGING_SUPPORTED
> #else
> #endif
> ```

Please remove.
___
*[tests/unit/utils/utils-common.c, line 38 at r1](https://reviewable.io/reviews/pmem/rpma/477#-MIOGn8l8Jki9C3t0zX4:-MIOGn8m9gkSF0HvfB2K:bzfwvq9) ([raw file](https://github.com/pmem/rpma/blob/86a1c9b5bae845c1034cbbc3e527455ac2dfaba7/tests/unit/utils/utils-common.c#L38)):*
> ```C
> 	if (*info_ptr == NULL) {
> 		int result = mock_type(int);
> 		if (result == RPMA_E_PROVIDER)
> ```

```
/* XXX validate the errno handling */
```
___
*[tests/unit/utils/utils-common.c, line 89 at r1](https://reviewable.io/reviews/pmem/rpma/477#-MIOH4dnE0p1gHoqJfMo:-MIOH4dnE0p1gHoqJfMp:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/86a1c9b5bae845c1034cbbc3e527455ac2dfaba7/tests/unit/utils/utils-common.c#L89)):*
> ```C
> 
> 	int ret = mock_type(int);
> 	if (ret)
> ```

.
___
*[tests/unit/utils/utils-common.c, line 107 at r1](https://reviewable.io/reviews/pmem/rpma/477#-MIOH6Z228shbh7AFOx4:-MIOH6Z228shbh7AFOx5:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/86a1c9b5bae845c1034cbbc3e527455ac2dfaba7/tests/unit/utils/utils-common.c#L107)):*
> ```C
> 
> 	int ret = mock_type(int);
> 	if (ret)
> ```

.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/477)* status: 31 of 46 files reviewed, 17 unresolved discussions (waiting on @janekmi)

___
*[src/conn_req.c, line 202 at r1](https://reviewable.io/reviews/pmem/rpma/477#-MIOAxKY4zymO4Ud4S8l:-MIOJWqm5phmS7NSqJz8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/86a1c9b5bae845c1034cbbc3e527455ac2dfaba7/src/conn_req.c#L202)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You can further simplify this part. `provider_error` seems unnecessary here.
</blockquote></details>

Done.
___
*[src/peer.c, line 119 at r1](https://reviewable.io/reviews/pmem/rpma/477#-MIOByFw5oiztjUyDmyn:-MIOPVIX5VQrK9oLUlmo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/86a1c9b5bae845c1034cbbc3e527455ac2dfaba7/src/peer.c#L119)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It seems a lot of this calls can now take only a single line.
</blockquote></details>

Done.
___
*[src/rpma.c, line 92 at r1](https://reviewable.io/reviews/pmem/rpma/477#-MIOCr03DmyaSi4BBnzc:-MIOPdDL5pJmu9m_VLlR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/86a1c9b5bae845c1034cbbc3e527455ac2dfaba7/src/rpma.c#L92)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Fits into a single line?
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-rpma-conn.c, line 31 at r1](https://reviewable.io/reviews/pmem/rpma/477#-MIOHJN-5Ie3AIvUr8MT:-MIOQ7If6uyatBkeM43a:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/86a1c9b5bae845c1034cbbc3e527455ac2dfaba7/tests/unit/common/mocks-rpma-conn.c#L31)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```
/* XXX validate the errno handling */
```
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-rpma-conn.c, line 54 at r1](https://reviewable.io/reviews/pmem/rpma/477#-MIOHPQjAPaI3r-EWIVA:-MIOQ7cV2nUUkA-oDm4S:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/86a1c9b5bae845c1034cbbc3e527455ac2dfaba7/tests/unit/common/mocks-rpma-conn.c#L54)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-rpma-flush.c, line 69 at r1](https://reviewable.io/reviews/pmem/rpma/477#-MIOHRFL7OXUwxMzH1an:-MIOQ8kx1Acirbiqz-02:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/86a1c9b5bae845c1034cbbc3e527455ac2dfaba7/tests/unit/common/mocks-rpma-flush.c#L69)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-rpma-info.c, line 31 at r1](https://reviewable.io/reviews/pmem/rpma/477#-MIOHSKZ5w_sKWpnSSwY:-MIOQ9j33llWmJwiHMoK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/86a1c9b5bae845c1034cbbc3e527455ac2dfaba7/tests/unit/common/mocks-rpma-info.c#L31)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-rpma-info.c, line 65 at r1](https://reviewable.io/reviews/pmem/rpma/477#-MIOHTHq-rpU99EbeIRl:-MIOQADpDs1Cp5QlrXGN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/86a1c9b5bae845c1034cbbc3e527455ac2dfaba7/tests/unit/common/mocks-rpma-info.c#L65)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-rpma-info.c, line 84 at r1](https://reviewable.io/reviews/pmem/rpma/477#-MIOHUOmE3PBXU_eRI7f:-MIOQOL55peIno9srzY6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/86a1c9b5bae845c1034cbbc3e527455ac2dfaba7/tests/unit/common/mocks-rpma-info.c#L84)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-rpma-peer.c, line 29 at r1](https://reviewable.io/reviews/pmem/rpma/477#-MIOHWpT4ff7o9pIGcWt:-MIOQbo450cZpKBGrlyM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/86a1c9b5bae845c1034cbbc3e527455ac2dfaba7/tests/unit/common/mocks-rpma-peer.c#L29)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-rpma-peer.c, line 57 at r1](https://reviewable.io/reviews/pmem/rpma/477#-MIOHYPb1xAO9kPTgBHO:-MIOQl6e-inAilVJwX8r:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/86a1c9b5bae845c1034cbbc3e527455ac2dfaba7/tests/unit/common/mocks-rpma-peer.c#L57)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-rpma-utils.c, line 29 at r1](https://reviewable.io/reviews/pmem/rpma/477#-MIOH_-h4kslAujIMorE:-MIOQmCL-e3OrKf-6bZR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/86a1c9b5bae845c1034cbbc3e527455ac2dfaba7/tests/unit/common/mocks-rpma-utils.c#L29)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/ep/ep-common.c, line 208 at r1](https://reviewable.io/reviews/pmem/rpma/477#-MIOHbYV4_SVfMtTDD2q:-MIOQuNS8d2sv9HwOkQs:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/86a1c9b5bae845c1034cbbc3e527455ac2dfaba7/tests/unit/ep/ep-common.c#L208)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/peer/peer-mr_reg.c, line 108 at r1](https://reviewable.io/reviews/pmem/rpma/477#-MIOFK455BcQaMcGPzPe:-MIOR0js97Cn7H0mwyR9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/86a1c9b5bae845c1034cbbc3e527455ac2dfaba7/tests/unit/peer/peer-mr_reg.c#L108)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please remove.
</blockquote></details>

Done.
___
*[tests/unit/utils/utils-common.c, line 38 at r1](https://reviewable.io/reviews/pmem/rpma/477#-MIOGn8l8Jki9C3t0zX4:-MIOR27v0xZvsb6UqFUg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/86a1c9b5bae845c1034cbbc3e527455ac2dfaba7/tests/unit/utils/utils-common.c#L38)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```
/* XXX validate the errno handling */
```
</blockquote></details>

Done.
___
*[tests/unit/utils/utils-common.c, line 89 at r1](https://reviewable.io/reviews/pmem/rpma/477#-MIOH4dnE0p1gHoqJfMo:-MIOR7zCCl1bdNe-RhjD:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/86a1c9b5bae845c1034cbbc3e527455ac2dfaba7/tests/unit/utils/utils-common.c#L89)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/utils/utils-common.c, line 107 at r1](https://reviewable.io/reviews/pmem/rpma/477#-MIOH6Z228shbh7AFOx4:-MIORJo42HUtYRcJ--HU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/86a1c9b5bae845c1034cbbc3e527455ac2dfaba7/tests/unit/utils/utils-common.c#L107)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 15 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/477)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/conn.c, line 502 at r2](https://reviewable.io/reviews/pmem/rpma/477#-MIOUQr4ABxVzVKfYLsf:-MIOUQr4ABxVzVKfYLsg:b3305l4) ([raw file](https://github.com/pmem/rpma/blob/f1d65162134c390e08701cd6f415cef540b308f6/src/conn.c#L502)):*
> ```C
> 	} else if (result < 0) {
> 		RPMA_LOG_ERROR("ibv_poll_cq() failed");
> 		return RPMA_E_PROVIDER;
> ```

This part is addressed by #476.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/477)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[src/conn.c, line 502 at r2](https://reviewable.io/reviews/pmem/rpma/477#-MIOUQr4ABxVzVKfYLsf:-MIOZL_jAIs6Nsb64IUN:b-vrli48) ([raw file](https://github.com/pmem/rpma/blob/f1d65162134c390e08701cd6f415cef540b308f6/src/conn.c#L502)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This part is addressed by #476.
</blockquote></details>

I have to change it too.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/477)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[src/conn.c, line 502 at r2](https://reviewable.io/reviews/pmem/rpma/477#-MIOUQr4ABxVzVKfYLsf:-MIOZkka9MiyItBAdfWB:b-95m1ah) ([raw file](https://github.com/pmem/rpma/blob/f1d65162134c390e08701cd6f415cef540b308f6/src/conn.c#L502)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I have to change it too.
</blockquote></details>

There is no other correct fix for this place.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/477)* status: 44 of 46 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[src/conn.c, line 502 at r2](https://reviewable.io/reviews/pmem/rpma/477#-MIOUQr4ABxVzVKfYLsf:-MIOaxFi8xrSeD9r7pM6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f1d65162134c390e08701cd6f415cef540b308f6/src/conn.c#L502)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

There is no other correct fix for this place.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/477#-:-MIOiGsh34aClXa7NaZc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> ```
> errno = 
> ```
errno = ... => int rpma_errno =

> Reviewed 1 of 15 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/477#-:-MIOj_-y1zlXsF-KCGla:bpe30pl)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[src/conn_req.c, line 79 at r3](https://reviewable.io/reviews/pmem/rpma/477#-MIOj92_1IXklk3JfPMC:-MIOj92_1IXklk3JfPMD:b-mbl9ud) ([raw file](https://github.com/pmem/rpma/blob/a6bb3ac642dd2e6fb15bd5908f5cf86dc1def423/src/conn_req.c#L79)):*
> ```
> errno
> ```
.
___
*[src/conn_req.c, line 79 at r3](https://reviewable.io/reviews/pmem/rpma/477#-MIOjrX49rFSm18pntvO:-MIOjrX49rFSm18pntvP:b3twdqh) ([raw file](https://github.com/pmem/rpma/blob/a6bb3ac642dd2e6fb15bd5908f5cf86dc1def423/src/conn_req.c#L79)):*
> ```
> errno 
> ```

**Review by ldorau — COMMENTED** [review]
Why?

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/477#-:-MIOlxZyE-REQPNyGWAJ:bb76mu4)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[src/conn_req.c, line 79 at r3](https://reviewable.io/reviews/pmem/rpma/477#-MIOjrX49rFSm18pntvO:-MIOmF-C6FAVqIfA5MOE:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/a6bb3ac642dd2e6fb15bd5908f5cf86dc1def423/src/conn_req.c#L79)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> errno 
> ```

</blockquote></details>

.
___
*[src/conn_req.c, line 79 at r3](https://reviewable.io/reviews/pmem/rpma/477#-MIOj92_1IXklk3JfPMC:-MIOmKAHC57vzsQc-K23:b-7sd6rd) ([raw file](https://github.com/pmem/rpma/blob/a6bb3ac642dd2e6fb15bd5908f5cf86dc1def423/src/conn_req.c#L79)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> errno
> ```
.
</blockquote></details>

I think it is OK

**Review by janekmi — APPROVED** [review]
@grom72 forgot errno is thread-local. Never mind.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/477#-:-MIOumxu50KWU1vVlR9X:brgceq6)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Pull request merged**
