### PR TITLE
doc: improve the documentation to rpma_ep... functions

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/429)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/429)* status: all files reviewed, 4 unresolved discussions (waiting on @osalyk)

___
*[src/include/librpma.h, line 931 at r1](https://reviewable.io/reviews/pmem/rpma/429#-MHzxmP48FouNymplLhm:-MHzxmP48FouNymplLhn:bahg4fd) ([raw file](https://github.com/pmem/rpma/blob/3e06f996198e1ab7cbd016f9117518ca105371d2/src/include/librpma.h#L931)):*
> ```objc
>  *
>  * DESCRIPTION
>  * Create an endpoint and initialize listening for incoming connections
> ```

`rpma_ep_listen() createS ... and initializeS ...`
___
*[src/include/librpma.h, line 962 at r1](https://reviewable.io/reviews/pmem/rpma/429#-MHzxy1F-fGFl7bONeqB:-MHzxy1F-fGFl7bONeqC:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/3e06f996198e1ab7cbd016f9117518ca105371d2/src/include/librpma.h#L962)):*
> ```objc
>  *
>  * DESCRIPTION
>  * Stop listening for incoming connections and delete the endpoint.
> ```

.
___
*[src/include/librpma.h, line 988 at r1](https://reviewable.io/reviews/pmem/rpma/429#-MHzxzP_6-EA8iM-QhjX:-MHzxzP_6-EA8iM-QhjY:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/3e06f996198e1ab7cbd016f9117518ca105371d2/src/include/librpma.h#L988)):*
> ```objc
>  *
>  * DESCRIPTION
>  * Gets a file descriptor of the endpoint.
> ```

.
___
*[src/include/librpma.h, line 1016 at r1](https://reviewable.io/reviews/pmem/rpma/429#-MHzy-8I7-MChD_rRbaY:-MHzy-8I7-MChD_rRbaZ:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/3e06f996198e1ab7cbd016f9117518ca105371d2/src/include/librpma.h#L1016)):*
> ```objc
>  *
>  * DESCRIPTION
>  * Obtains the next connection request from the endpoint.
> ```

.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/429)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[src/include/librpma.h, line 931 at r1](https://reviewable.io/reviews/pmem/rpma/429#-MHzxmP48FouNymplLhm:-MI-HmSwE96fIf-WCJBn:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3e06f996198e1ab7cbd016f9117518ca105371d2/src/include/librpma.h#L931)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`rpma_ep_listen() createS ... and initializeS ...`
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 962 at r1](https://reviewable.io/reviews/pmem/rpma/429#-MHzxy1F-fGFl7bONeqB:-MI-HvXj0wYamoCUcZOy:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3e06f996198e1ab7cbd016f9117518ca105371d2/src/include/librpma.h#L962)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 988 at r1](https://reviewable.io/reviews/pmem/rpma/429#-MHzxzP_6-EA8iM-QhjX:-MI-I16r7L_lWdIx3nGY:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3e06f996198e1ab7cbd016f9117518ca105371d2/src/include/librpma.h#L988)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1016 at r1](https://reviewable.io/reviews/pmem/rpma/429#-MHzy-8I7-MChD_rRbaY:-MI-I5Vw6Bm3x60rvPnR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3e06f996198e1ab7cbd016f9117518ca105371d2/src/include/librpma.h#L1016)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/429)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
@grom72 please review

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/429#-:-MI-K1qy3MH8TybwOMZD:bgjoyzx)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/429)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[src/include/librpma.h, line 989 at r2](https://reviewable.io/reviews/pmem/rpma/429#-MI3Ww6a-OSsQyV9n_XC:-MI3Ww6a-OSsQyV9n_XD:b-ns7w5p) ([raw file](https://github.com/pmem/rpma/blob/fa98c23b9c466fb9bf94bdac71cc297d55026188/src/include/librpma.h#L989)):*
> ```
> gets a file 
> ```

gets THE file ...

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/429)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/include/librpma.h, line 989 at r2](https://reviewable.io/reviews/pmem/rpma/429#-MI3Ww6a-OSsQyV9n_XC:-MI3_-YrDAb_tOd467ui:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fa98c23b9c466fb9bf94bdac71cc297d55026188/src/include/librpma.h#L989)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> gets a file 
> ```

gets THE file ...
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/429)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/429#-:-MI3avUD3tR_ddVlC60K:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/429)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau and @osalyk)

___
*[src/include/librpma.h, line 1021 at r4](https://reviewable.io/reviews/pmem/rpma/429#-MI4GCdU6sy7ya3eYmL1:-MI4GCdU6sy7ya3eYmL2:b-44d4z2) ([raw file](https://github.com/pmem/rpma/blob/7214935e65bb14edcfcb1de88282dd278c4a46f4/src/include/librpma.h#L1021)):*
> ```
> ep
> ```
ep_ptr

**Review by grom72 — COMMENTED** [review]
_ptr suffix to be added to pointer to pointer (e.g. **ep -> **ep_ptr)

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/429#-:-MI4Hyrj0OCkzCxs1_ci:bx50bzm)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[src/include/librpma.h, line 1052 at r4](https://reviewable.io/reviews/pmem/rpma/429#-MI4Hm-cBt_6qcSQxTsO:-MI4Hm-cBt_6qcSQxTsP:b-44d4z2) ([raw file](https://github.com/pmem/rpma/blob/7214935e65bb14edcfcb1de88282dd278c4a46f4/src/include/librpma.h#L1052)):*
> ```
> ep
> ```
ep_ptr

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/429#-:-MI4N39V4MJmP9ylzAe_:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/429)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
