### PR TITLE
test: MTT: check if the child process terminated

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1644)

### CODE REVIEW

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1644)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1644)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[tests/multithreaded/common/mtt.c, line 362 at r1](https://reviewable.io/reviews/pmem/rpma/1644#-N-29NkG8OcR-zuWcvOA:-N-29NkG8OcR-zuWcvOB:b-n8jn0e) ([raw file](https://github.com/pmem/rpma/blob/bf005a1f27b5bd9f8f0ddcbc2b04c59b2cd2ef25/tests/multithreaded/common/mtt.c#L362)):*
> ```C
> 	}
> 
> 	if ((result = mtt_check_child_process(child_pid)))
> ```

Shall this code be moved to ``if() {`` 



_Code quote:_
```C
	if ((result = mtt_check_child_process(child_pid)))
		goto err_kill_child;
```
___
*[tests/multithreaded/common/mtt.c, line 371 at r1](https://reviewable.io/reviews/pmem/rpma/1644#-N-2BMvFCSGbE4RQ_Zv8:-N-2BMvFCSGbE4RQ_Zv9:b3g1d6c) ([raw file](https://github.com/pmem/rpma/blob/bf005a1f27b5bd9f8f0ddcbc2b04c59b2cd2ef25/tests/multithreaded/common/mtt.c#L371)):*
> ```C
> 			MTT_INTERNAL_ERR("%s", tr_local.errmsg);
> 			result = tr_local.ret;
> 			(void) mtt_check_child_process(child_pid);
> ```

```
if(child_pid)
	(void) mtt_check_child_process(child_pid);
```



_Code quote:_
```C
			(void) mtt_check_child_process(child_pid);
```
___
*[tests/multithreaded/common/mtt.c, line 409 at r1](https://reviewable.io/reviews/pmem/rpma/1644#-N-2B_6HDfif47Zp_dcW:-N-2B_6HDfif47Zp_dcX:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/bf005a1f27b5bd9f8f0ddcbc2b04c59b2cd2ef25/tests/multithreaded/common/mtt.c#L409)):*
> ```C
> 	}
> 
> 	if ((result = mtt_check_child_process(child_pid)))
> ```

.



_Code quote:_
```C
	if ((result = mtt_check_child_process(child_pid)))
		goto err_fini_threads_args;
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1644)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[tests/multithreaded/common/mtt.c, line 362 at r1](https://reviewable.io/reviews/pmem/rpma/1644#-N-29NkG8OcR-zuWcvOA:-N-2CkaZ3yeZhDyO0bJf:b7vxuao) ([raw file](https://github.com/pmem/rpma/blob/bf005a1f27b5bd9f8f0ddcbc2b04c59b2cd2ef25/tests/multithreaded/common/mtt.c#L362)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Shall this code be moved to ``if() {`` 
</blockquote></details>

Can be, but this check has to be done inside the function anyway, so it will be checked twice ...
___
*[tests/multithreaded/common/mtt.c, line 371 at r1](https://reviewable.io/reviews/pmem/rpma/1644#-N-2BMvFCSGbE4RQ_Zv8:-N-2DD-s2gKkPvW3jwLw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bf005a1f27b5bd9f8f0ddcbc2b04c59b2cd2ef25/tests/multithreaded/common/mtt.c#L371)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```
if(child_pid)
	(void) mtt_check_child_process(child_pid);
```
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mtt.c, line 409 at r1](https://reviewable.io/reviews/pmem/rpma/1644#-N-2B_6HDfif47Zp_dcW:-N-2DDTI5hXwzMkDAS8L:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bf005a1f27b5bd9f8f0ddcbc2b04c59b2cd2ef25/tests/multithreaded/common/mtt.c#L409)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1644)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1644#-:-N-2zJ-g517f0bhnkLlX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1644#-:-N-7LLGs5M0pgWL4AdOP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
