### PR TITLE
tools: reorganize / cleanup the templates directory

### PR DESCRIPTION
**Pull request by janekmi**
- all template files are either *.md, *.html or *.md.copyme
- *.md.copyme files are expected to be:
  - copied to report_xyz/ directory
  - renamed from *.md.copyme to *.md
  - filled by the user
- BENCHMARKING.md updated accordingly

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/850)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/850)* status: 0 of 16 files reviewed, 1 unresolved discussion

___
*[tools/create_report.py, line 34 at r1](https://reviewable.io/reviews/pmem/rpma/850#-MSi_f4xA003NT6EQ5jK:-MSi_f4xA003NT6EQ5jL:b-o7wf22) ([raw file](https://github.com/pmem/rpma/blob/89e644eead1457f0cc444e0060a1d0477a1dc3e4/tools/create_report.py#L34)):*
> ```Python
> REPORT_CONTENTS_HTML = [
>     'report_menu'
> ]
> ```

It was a dictionary for no reason.
___
*[tools/create_report.py, line 43 at r1](https://reviewable.io/reviews/pmem/rpma/850#-MSi_lyU6rGg6jg-zorC:-MSi_lyU6rGg6jg-zorD:b-o7wf22) ([raw file](https://github.com/pmem/rpma/blob/89e644eead1457f0cc444e0060a1d0477a1dc3e4/tools/create_report.py#L43)):*
> ```Python
> APPENDICES_CONTENTS_HTML = [
>     'appendices_menu'
> ]
> ```

It was a dictionary for no reason.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/850)* status: 0 of 16 files reviewed, all discussions resolved

___
*[tools/create_report.py, line 43 at r1](https://reviewable.io/reviews/pmem/rpma/850#-MSi_tzB8QFqkh80saIP:-MSi_tzB8QFqkh80saIQ:b-o7wf22) ([raw file](https://github.com/pmem/rpma/blob/89e644eead1457f0cc444e0060a1d0477a1dc3e4/tools/create_report.py#L43)):*
> ```Python
> APPENDICES_CONTENTS_HTML = [
>     'appendices_menu'
> ]
> ```

It was a dictionary for no reason.

**Review by ldorau — APPROVED** [review]
> Reviewed 16 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/850)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/850#-:-MSj44DE50kue2-S_YCq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
