### PR TITLE
test: enable user error messages with actual values

### PR DESCRIPTION
**Pull request by grom72**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1768)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1768)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1768)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`tests/multithreaded/common/mtt.h` line 73 at r1](https://reviewable.io/reviews/pmem/rpma/1768#-N3cggoG21_oLuoLPXgl:-N3cggoG21_oLuoLPXgm:b-1a25rv) ([raw file](https://github.com/pmem/rpma/blob/835e5b29c45a0b2d1c2b19ff6b8d5872c66b19b3/tests/multithreaded/common/mtt.h#L73)):*
> ```objc
> #define MTT_ERR_MSG(result, msg, err, ...) \
> 	do { \
> 		char msg_buf[MTT_ERRMSG_MAX / 2]; \
> ```

Why is it divided by 2?



_Code quote:_
```objc
MTT_ERRMSG_MAX / 2
```

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1768)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`tests/multithreaded/common/mtt.h` line 73 at r1](https://reviewable.io/reviews/pmem/rpma/1768#-N3cggoG21_oLuoLPXgl:-N3cgqVLBWFXTstjssMy:b-nu5d8k) ([raw file](https://github.com/pmem/rpma/blob/835e5b29c45a0b2d1c2b19ff6b8d5872c66b19b3/tests/multithreaded/common/mtt.h#L73)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why is it divided by 2?
</blockquote></details>

To have space for the timestamp, __FILE__, etc.

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1768#-:-N3cikGC338HG1bYbpm0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1768#-:-N3dTBz66Mj80VkXMZJQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1768)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
