### PR TITLE
tools: perf: introduce a "CPU load impact" part to the report

### PR DESCRIPTION
**Pull request by janekmi**
Requires:
- [x] #1031

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1032)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1032)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/templates/tc4_cpu.md, line 31 at r1](https://reviewable.io/reviews/pmem/rpma/1032#-MZMQcMo5b5949Pr4Br3:-MZMQcMo5b5949Pr4Br4:bc3vaeu) ([raw file](https://github.com/pmem/rpma/blob/1f0778c2c09bb5173befb85ce7ff648403cfb460/tools/perf/templates/tc4_cpu.md#L31)):*
> ```
> 
> ```
eol is missing

**Review by grom72 — COMMENTED** [review]
:goat: 

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1032#-:-MZMmwWF4inZ02wKYCEq:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1032)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/perf/templates/tc4_cpu.md, line 31 at r1](https://reviewable.io/reviews/pmem/rpma/1032#-MZMQcMo5b5949Pr4Br3:-MZMo6i16xoGJM-PNvO6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1f0778c2c09bb5173befb85ce7ff648403cfb460/tools/perf/templates/tc4_cpu.md#L31)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> 
> ```
eol is missing
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1032#-:-MZMy5V_DuG4x_LkjPtI:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Pull request merged**
