### PR TITLE
rpma: fix 'store to misaligned address' errors in serializing data

### PR DESCRIPTION
**Pull request by ldorau**
Fix the following errors:

```
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /home/ldorau/work/rpma/src/mr.c:264:2 in 
/home/ldorau/work/rpma/src/mr.c:266:2: runtime error: store to misaligned address 0x7ffe81e477e9 for type 'uint64_t' (aka 'unsigned long'), which requires 8 byte alignment
0x7ffe81e477e9: note: pointer points here
 03 02 01  00 ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  ff ff ff ff ff
              ^ 
```

Ref: #303

Requires:
- [x] #380

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/386)

### CODE REVIEW

**Comment by ldorau** [comment]
The build with ASAN and UBSAN turned is passing now: #309

**Review by janekmi — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/386)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/mr.c, line 332 at r1](https://reviewable.io/reviews/pmem/rpma/386#-MGqzjfP2sPCUFpEhYet:-MGqzjfP2sPCUFpEhYeu:b-fsm3br) ([raw file](https://github.com/pmem/rpma/blob/8861d4637a2c609c496903963320cc840a03644f/src/mr.c#L332)):*
> ```C
> 	uint32_t rkey = htole32(mr->ibv_mr->rkey);
> 	memcpy(buff, &rkey, sizeof(uint32_t));
> 	buff += sizeof(uint32_t);
> ```

UBSAN also complained about the serialization part?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/386)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[src/mr.c, line 332 at r1](https://reviewable.io/reviews/pmem/rpma/386#-MGqzjfP2sPCUFpEhYet:-MGr2pl8BiEcpHkEE0WD:b2nhswy) ([raw file](https://github.com/pmem/rpma/blob/8861d4637a2c609c496903963320cc840a03644f/src/mr.c#L332)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

UBSAN also complained about the serialization part?
</blockquote></details>

Yes

**Review by grom72 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/386#-:-MGr9Whs8BueJPP7h4qn:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Comment by ldorau** [comment]
Rebased

**Review by janekmi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/386#-:-MGs8qONDgQ7SHC2MdSX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
