### PR TITLE
common: add packaging

### PR DESCRIPTION
**Pull request by ldorau**
Missing:
- [x] #297 
- [x] #292
- [x] documentation

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/299)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/299)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[cmake/packages.cmake, line 44 at r1](https://reviewable.io/reviews/pmem/rpma/299#-MFgWICI1ZQ_KIPPf5O0:-MFgWICJCirvUnNDkZOz:bbymz59) ([raw file](https://github.com/pmem/rpma/blob/0f735908dd0694f2085b4af132508e335a6522a1/cmake/packages.cmake#L44)):*
> ```CMake
> set(CPACK_RPM_PACKAGE_LICENSE "BSD")
> set(CPACK_RPM_PACKAGE_ARCHITECTURE x86_64)
> set(CPACK_RPM_PACKAGE_REQUIRES "libibverbs >= ${LIBIBVERBS_REQUIRED_VERSION}, librdmacm >= ${LIBRDMACM_REQUIRED_VERSION}")
> ```

Deb's require `dev` whereas rpm's do not?
___
*[utils/docker/run-build.sh, line 143 at r1](https://reviewable.io/reviews/pmem/rpma/299#-MFgWZ_86gJGNyHEEBga:-MFgWZ_86gJGNyHEEBgb:b8a5qgo) ([raw file](https://github.com/pmem/rpma/blob/0f735908dd0694f2085b4af132508e335a6522a1/utils/docker/run-build.sh#L143)):*
> ```Shell
> #
> # XXX - tests are temporarly disabled,
> # because one test fails in the Release build.
> ```

Just for the memory.
___
*[utils/docker/run-build.sh, line 173 at r1](https://reviewable.io/reviews/pmem/rpma/299#-MFgWqw-DsqeVqUYNZ_y:-MFgWqw-DsqeVqUYNZ_z:bsyi8a) ([raw file](https://github.com/pmem/rpma/blob/0f735908dd0694f2085b4af132508e335a6522a1/utils/docker/run-build.sh#L173)):*
> ```Shell
> 
> cd $WORKDIR
> rm -rf $WORKDIR/build
> ```

I like the idea to install the generated packages and... try standalone example compilation afterwards. What do you think?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/299)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[cmake/packages.cmake, line 44 at r1](https://reviewable.io/reviews/pmem/rpma/299#-MFgWICI1ZQ_KIPPf5O0:-MFiPwG5Ap65tHqpb6rX:b4shl25) ([raw file](https://github.com/pmem/rpma/blob/0f735908dd0694f2085b4af132508e335a6522a1/cmake/packages.cmake#L44)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Deb's require `dev` whereas rpm's do not?
</blockquote></details>

Yes, because there is no '-devel' version of those two packages in Fedora ...
___
*[utils/docker/run-build.sh, line 143 at r1](https://reviewable.io/reviews/pmem/rpma/299#-MFgWZ_86gJGNyHEEBga:-MFiPI0V1zvr7eB0tmJI:b-lbut5x) ([raw file](https://github.com/pmem/rpma/blob/0f735908dd0694f2085b4af132508e335a6522a1/utils/docker/run-build.sh#L143)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Just for the memory.
</blockquote></details>

What do you mean?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/299)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[utils/docker/run-build.sh, line 173 at r1](https://reviewable.io/reviews/pmem/rpma/299#-MFgWqw-DsqeVqUYNZ_y:-MFjIaPM0aVZAIpMFXMp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0f735908dd0694f2085b4af132508e335a6522a1/utils/docker/run-build.sh#L173)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I like the idea to install the generated packages and... try standalone example compilation afterwards. What do you think?
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/299#-:-MFpvw4w5oeHKQ5oMNZi:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[cmake/packages.cmake, line 44 at r1](https://reviewable.io/reviews/pmem/rpma/299#-MFgWICI1ZQ_KIPPf5O0:-MFpu_bD3R5c0rCAO2s1:bu2wv42) ([raw file](https://github.com/pmem/rpma/blob/0f735908dd0694f2085b4af132508e335a6522a1/cmake/packages.cmake#L44)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, because there is no '-devel' version of those two packages in Fedora ...
</blockquote></details>

I see. The 'devel' part is provided via the rdma-core-devel package.
___
*[utils/docker/run-build.sh, line 143 at r1](https://reviewable.io/reviews/pmem/rpma/299#-MFgWZ_86gJGNyHEEBga:-MFpv-9dCLOcKp0FtVrv:bvk9ode) ([raw file](https://github.com/pmem/rpma/blob/0f735908dd0694f2085b4af132508e335a6522a1/utils/docker/run-build.sh#L143)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

What do you mean?
</blockquote></details>

Please do not bother yourself. This is only my note to not forget tracking the XXX part. ;-)

Since there is nothing to track any more. Closing.

**Review by janekmi — APPROVED** [review]
:lgtm_strong: 

> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/299#-:-MG3j7hx6gHW3eLmatcn:b-yncq6h)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/299)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/299#-MG3jtrt2gVDvlcWwreW:-MG3jtru6_FwLz4jBtTL:b-ie8120) (no related file):*
Oh no!:

Contents of these packages are somewhat strange:

```
2020-08-31T13:36:46.8468139Z /usr/share/doc/rpma/examples
2020-08-31T13:36:46.8468456Z /usr/share/doc/rpma/examples/01-connection
2020-08-31T13:36:46.8468765Z /usr/share/doc/rpma/examples/01-connection/client.c
2020-08-31T13:36:46.8469102Z /usr/share/doc/rpma/examples/01-connection/server.c
2020-08-31T13:36:46.8469697Z /usr/share/doc/rpma/examples/02-read-to-volatile
2020-08-31T13:36:46.8470036Z /usr/share/doc/rpma/examples/02-read-to-volatile/client.c
2020-08-31T13:36:46.8470371Z /usr/share/doc/rpma/examples/02-read-to-volatile/server.c
2020-08-31T13:36:46.8470697Z /usr/share/doc/rpma/examples/03-read-to-persistent
2020-08-31T13:36:46.8471032Z /usr/share/doc/rpma/examples/03-read-to-persistent/client.c
2020-08-31T13:36:46.8471374Z /usr/share/doc/rpma/examples/03-read-to-persistent/server.c
2020-08-31T13:36:46.8471693Z /usr/share/doc/rpma/examples/04-write-to-persistent
2020-08-31T13:36:46.8472042Z /usr/share/doc/rpma/examples/04-write-to-persistent/client.c
2020-08-31T13:36:46.8472383Z /usr/share/doc/rpma/examples/04-write-to-persistent/server.c
2020-08-31T13:36:46.8472710Z /usr/share/doc/rpma/examples/05-flush-to-persistent
2020-08-31T13:36:46.8473047Z /usr/share/doc/rpma/examples/05-flush-to-persistent/client.c
2020-08-31T13:36:46.8473380Z /usr/share/doc/rpma/examples/05-flush-to-persistent/server.c
2020-08-31T13:36:46.8473718Z /usr/share/doc/rpma/examples/06-multiple-connections
2020-08-31T13:36:46.8474057Z /usr/share/doc/rpma/examples/06-multiple-connections/client.c
2020-08-31T13:36:46.8474427Z /usr/share/doc/rpma/examples/06-multiple-connections/multiple-connections-common.h
2020-08-31T13:36:46.8474840Z /usr/share/doc/rpma/examples/06-multiple-connections/server.c
2020-08-31T13:36:46.8474972Z /usr/share/doc/rpma/examples/common
2020-08-31T13:36:46.8475293Z /usr/share/doc/rpma/examples/common/common-conn.c
2020-08-31T13:36:46.8475619Z /usr/share/doc/rpma/examples/common/common-conn.h
2020-08-31T13:36:46.8475944Z /usr/share/doc/rpma/examples/common/common-epoll.c
2020-08-31T13:36:46.8476265Z /usr/share/doc/rpma/examples/common/common-epoll.h
2020-08-31T13:36:46.8476413Z /usr/share/doc/rpma/examples/doc_snippets
2020-08-31T13:36:46.8476743Z /usr/share/doc/rpma/examples/doc_snippets/template-snippet.c
2020-08-31T13:36:46.8476872Z /usr/share/doc/rpma/examples/log
2020-08-31T13:36:46.8477191Z /usr/share/doc/rpma/examples/log/log-example.c
2020-08-31T13:36:46.8477518Z /usr/share/doc/rpma/examples/log/log-worker.c
2020-08-31T13:36:46.8477828Z /usr/share/doc/rpma/examples/template-example
2020-08-31T13:36:46.8478164Z /usr/share/doc/rpma/examples/template-example/template-example.c
```

I would expect docs here instead of examples .c files.

---

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/299)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[INSTALL.md, line 80 at r3](https://reviewable.io/reviews/pmem/rpma/299#-MG3k0pj3qmOoEUDDjbE:-MG3k0pk4B5ya-nRHaMh:bdlny5j) ([raw file](https://github.com/pmem/rpma/blob/5927c8b3c5c95b1515a3be44020c6e64e76f0b6b/INSTALL.md#L80)):*
> ```
> -DCMAKE_INSTALL_PREFIX=/usr
> ```
is there any way to use default value for installation destination folder?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/299)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[INSTALL.md, line 80 at r3](https://reviewable.io/reviews/pmem/rpma/299#-MG3k0pj3qmOoEUDDjbE:-MG3m7KhCXw4gL-PirHr:b-8m7s89) ([raw file](https://github.com/pmem/rpma/blob/5927c8b3c5c95b1515a3be44020c6e64e76f0b6b/INSTALL.md#L80)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> -DCMAKE_INSTALL_PREFIX=/usr
> ```
is there any way to use default value for installation destination folder?
</blockquote></details>

Yes, of course:
```
cmake .. -DCPACK_GENERATOR="$GEN"
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/299)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/299#-MG3jtrt2gVDvlcWwreW:-MG3oQyt8gyHprL-VWBr:b-jjxjhd) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Oh no!:

Contents of these packages are somewhat strange:

```
2020-08-31T13:36:46.8468139Z /usr/share/doc/rpma/examples
2020-08-31T13:36:46.8468456Z /usr/share/doc/rpma/examples/01-connection
2020-08-31T13:36:46.8468765Z /usr/share/doc/rpma/examples/01-connection/client.c
2020-08-31T13:36:46.8469102Z /usr/share/doc/rpma/examples/01-connection/server.c
2020-08-31T13:36:46.8469697Z /usr/share/doc/rpma/examples/02-read-to-volatile
2020-08-31T13:36:46.8470036Z /usr/share/doc/rpma/examples/02-read-to-volatile/client.c
2020-08-31T13:36:46.8470371Z /usr/share/doc/rpma/examples/02-read-to-volatile/server.c
2020-08-31T13:36:46.8470697Z /usr/share/doc/rpma/examples/03-read-to-persistent
2020-08-31T13:36:46.8471032Z /usr/share/doc/rpma/examples/03-read-to-persistent/client.c
2020-08-31T13:36:46.8471374Z /usr/share/doc/rpma/examples/03-read-to-persistent/server.c
2020-08-31T13:36:46.8471693Z /usr/share/doc/rpma/examples/04-write-to-persistent
2020-08-31T13:36:46.8472042Z /usr/share/doc/rpma/examples/04-write-to-persistent/client.c
2020-08-31T13:36:46.8472383Z /usr/share/doc/rpma/examples/04-write-to-persistent/server.c
2020-08-31T13:36:46.8472710Z /usr/share/doc/rpma/examples/05-flush-to-persistent
2020-08-31T13:36:46.8473047Z /usr/share/doc/rpma/examples/05-flush-to-persistent/client.c
2020-08-31T13:36:46.8473380Z /usr/share/doc/rpma/examples/05-flush-to-persistent/server.c
2020-08-31T13:36:46.8473718Z /usr/share/doc/rpma/examples/06-multiple-connections
2020-08-31T13:36:46.8474057Z /usr/share/doc/rpma/examples/06-multiple-connections/client.c
2020-08-31T13:36:46.8474427Z /usr/share/doc/rpma/examples/06-multiple-connections/multiple-connections-common.h
2020-08-31T13:36:46.8474840Z /usr/share/doc/rpma/examples/06-multiple-connections/server.c
2020-08-31T13:36:46.8474972Z /usr/share/doc/rpma/examples/common
2020-08-31T13:36:46.8475293Z /usr/share/doc/rpma/examples/common/common-conn.c
2020-08-31T13:36:46.8475619Z /usr/share/doc/rpma/examples/common/common-conn.h
2020-08-31T13:36:46.8475944Z /usr/share/doc/rpma/examples/common/common-epoll.c
2020-08-31T13:36:46.8476265Z /usr/share/doc/rpma/examples/common/common-epoll.h
2020-08-31T13:36:46.8476413Z /usr/share/doc/rpma/examples/doc_snippets
2020-08-31T13:36:46.8476743Z /usr/share/doc/rpma/examples/doc_snippets/template-snippet.c
2020-08-31T13:36:46.8476872Z /usr/share/doc/rpma/examples/log
2020-08-31T13:36:46.8477191Z /usr/share/doc/rpma/examples/log/log-example.c
2020-08-31T13:36:46.8477518Z /usr/share/doc/rpma/examples/log/log-worker.c
2020-08-31T13:36:46.8477828Z /usr/share/doc/rpma/examples/template-example
2020-08-31T13:36:46.8478164Z /usr/share/doc/rpma/examples/template-example/template-example.c
```

I would expect docs here instead of examples .c files.
</blockquote></details>

`make install` also installs those files ...

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/299)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/299#-MG3jtrt2gVDvlcWwreW:-MG3qq1e5Qb2uwovmgA7:bsmi7oq) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`make install` also installs those files ...
</blockquote></details>

In the main CMake file:
```
install(DIRECTORY examples/ DESTINATION ${CMAKE_INSTALL_DOCDIR}/examples
	FILES_MATCHING PATTERN "*.[ch]")
```

---

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/299)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/299#-MG3jtrt2gVDvlcWwreW:-MG3rZvo-c4uiv2paOhj:b-8ooww4) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

In the main CMake file:
```
install(DIRECTORY examples/ DESTINATION ${CMAKE_INSTALL_DOCDIR}/examples
	FILES_MATCHING PATTERN "*.[ch]")
```

</blockquote></details>

Ok. I like the idea to fix this in a separate PR.

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/299)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[INSTALL.md, line 80 at r3](https://reviewable.io/reviews/pmem/rpma/299#-MG3k0pj3qmOoEUDDjbE:-MG3ro0N-mQVFfj_eBtN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5927c8b3c5c95b1515a3be44020c6e64e76f0b6b/INSTALL.md#L80)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, of course:
```
cmake .. -DCPACK_GENERATOR="$GEN"
```
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/299)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/299#-:-MG3s9nR2VaxPi3XQbXe:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/299)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
