### PR TITLE
test: add rpma_conn_cfg_get_cq_size multithreaded test

### PR DESCRIPTION
**Pull request by ewanglong**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1100)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1100)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

___
*[tests/multithreaded/conn/rpma_conn_cfg_get_cq_size.c, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1100#-Mcxfx9P0Tyefnie8Emo:-Mcxfx9QEWVT5MflFGa7:bsgtt62) ([raw file](https://github.com/pmem/rpma/blob/44cd8dded247731f35e9e8d15f82679a37a953b0/tests/multithreaded/conn/rpma_conn_cfg_get_cq_size.c#L13)):*
> ```
> Q_SIZE_EXP
> ```

Please add a comment that this is the EXPected value.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1100)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/conn/rpma_conn_cfg_get_cq_size.c, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/1100#-McxiZWK28VuP9momcMS:-McxiZWK28VuP9momcMT:b-g2c55g) ([raw file](https://github.com/pmem/rpma/blob/44cd8dded247731f35e9e8d15f82679a37a953b0/tests/multithreaded/conn/rpma_conn_cfg_get_cq_size.c#L17)):*
> ```C
> struct prestate {
> 	struct rpma_conn_cfg *cfg_ptr;
> };
> ```

This also should be part of `rpma_conn_cfg_common.h`.
___
*[tests/multithreaded/conn/rpma_conn_cfg_get_cq_size.c, line 34 at r1](https://reviewable.io/reviews/pmem/rpma/1100#-Mcxisam-NftD_9OxAi5:-Mcxisam-NftD_9OxAi6:b1upc1w) ([raw file](https://github.com/pmem/rpma/blob/44cd8dded247731f35e9e8d15f82679a37a953b0/tests/multithreaded/conn/rpma_conn_cfg_get_cq_size.c#L34)):*
> ```C
> 
> 	if ((ret = rpma_conn_cfg_set_cq_size(pr->cfg_ptr, Q_SIZE_EXP)))
> 		MTT_RPMA_ERR(tr, "rpma_conn_cfg_set_cq_size", ret);
> ```

When making this function common you will have to set all queue sizes. I think it is not a big overhead.
Maybe put a comment, why we are doing it.
___
*[tests/multithreaded/conn/rpma_conn_cfg_get_cq_size.c, line 35 at r1](https://reviewable.io/reviews/pmem/rpma/1100#-McxiNdJ0a0yFCVaY_zU:-McxiNdJ0a0yFCVaY_zV:bskref3) ([raw file](https://github.com/pmem/rpma/blob/44cd8dded247731f35e9e8d15f82679a37a953b0/tests/multithreaded/conn/rpma_conn_cfg_get_cq_size.c#L35)):*
> ```C
> 	if ((ret = rpma_conn_cfg_set_cq_size(pr->cfg_ptr, Q_SIZE_EXP)))
> 		MTT_RPMA_ERR(tr, "rpma_conn_cfg_set_cq_size", ret);
> }
> ```

The `prestate_init/_fini()` should also be part of `rpma_conn_cfg_common.c/.h`.

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1100)* status: 0 of 4 files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tests/multithreaded/conn/rpma_conn_cfg_get_cq_size.c, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1100#-Mcxfx9P0Tyefnie8Emo:-MdKfHy71zURUPqtlur3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/44cd8dded247731f35e9e8d15f82679a37a953b0/tests/multithreaded/conn/rpma_conn_cfg_get_cq_size.c#L13)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> Q_SIZE_EXP
> ```

Please add a comment that this is the EXPected value.
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_cfg_get_cq_size.c, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/1100#-McxiZWK28VuP9momcMS:-MdKfIeY3mx9mHwktW6F:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/44cd8dded247731f35e9e8d15f82679a37a953b0/tests/multithreaded/conn/rpma_conn_cfg_get_cq_size.c#L17)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This also should be part of `rpma_conn_cfg_common.h`.
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_cfg_get_cq_size.c, line 34 at r1](https://reviewable.io/reviews/pmem/rpma/1100#-Mcxisam-NftD_9OxAi5:-MdKfJI0BCFxWAB_OpvN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/44cd8dded247731f35e9e8d15f82679a37a953b0/tests/multithreaded/conn/rpma_conn_cfg_get_cq_size.c#L34)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

When making this function common you will have to set all queue sizes. I think it is not a big overhead.
Maybe put a comment, why we are doing it.
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_cfg_get_cq_size.c, line 35 at r1](https://reviewable.io/reviews/pmem/rpma/1100#-McxiNdJ0a0yFCVaY_zU:-MdKfHF5E5bIOfPI9HNo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/44cd8dded247731f35e9e8d15f82679a37a953b0/tests/multithreaded/conn/rpma_conn_cfg_get_cq_size.c#L35)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The `prestate_init/_fini()` should also be part of `rpma_conn_cfg_common.c/.h`.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1100)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1100#-:-MdMKOI0D9VXYosRFU8w:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1100)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/conn/rpma_conn_cfg_common.h, line 34 at r2](https://reviewable.io/reviews/pmem/rpma/1100#-MdNo_Cy2uArEtp7zvxN:-MdNo_CzD-a5xtJ6S13e:b-cx036u) ([raw file](https://github.com/pmem/rpma/blob/e8c03e934a5015d0fabc819871349ad52bee364e/tests/multithreaded/conn/rpma_conn_cfg_common.h#L34)):*
> ```objc
> 		struct mtt_result *tr);
> 
> void rpma_conn_cfg_common_prestate_fini(void *prestate, struct mtt_result *tr);
> ```

Same here. I think the most useful order of structures and function declarations is:

- struct prestate
- prestate_init()
- prestate_fini()
- struct state
- state_init()
- state_fini()
___
*[tests/multithreaded/conn/rpma_conn_cfg_common.c, line 108 at r2](https://reviewable.io/reviews/pmem/rpma/1100#-MdNncZNAMqfTiJIQleU:-MdNncZOCGTjRaBxD0lS:bp3a084) ([raw file](https://github.com/pmem/rpma/blob/e8c03e934a5015d0fabc819871349ad52bee364e/tests/multithreaded/conn/rpma_conn_cfg_common.c#L108)):*
> ```C
> 	if ((ret = rpma_conn_cfg_delete(&pr->cfg_ptr)))
> 		MTT_RPMA_ERR(tr, "rpma_conn_cfg_delete", ret);
> }
> ```

I think this function should go just after the `rpma_conn_cfg_common_prestate_init()` function.
Because all these four functions is not a very useful sequence which may be used as follow:

- prestate_init()
- state_init()
- state_fini()
- prestate_fini()

On the contrary, I can not imagine a test that will use all these four functions to establish a sensible use case.
This is why I think you should keep these functions as pairs instead:

- prestate_init()
- prestate_fini()
- state_init()
- state_fini()

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1100)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tests/multithreaded/conn/rpma_conn_cfg_common.h, line 34 at r2](https://reviewable.io/reviews/pmem/rpma/1100#-MdNo_Cy2uArEtp7zvxN:-MdPjomR3SS6jgMLzhQz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e8c03e934a5015d0fabc819871349ad52bee364e/tests/multithreaded/conn/rpma_conn_cfg_common.h#L34)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Same here. I think the most useful order of structures and function declarations is:

- struct prestate
- prestate_init()
- prestate_fini()
- struct state
- state_init()
- state_fini()
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_cfg_common.c, line 108 at r2](https://reviewable.io/reviews/pmem/rpma/1100#-MdNncZNAMqfTiJIQleU:-MdPjppv6S8x89lrko6s:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e8c03e934a5015d0fabc819871349ad52bee364e/tests/multithreaded/conn/rpma_conn_cfg_common.c#L108)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think this function should go just after the `rpma_conn_cfg_common_prestate_init()` function.
Because all these four functions is not a very useful sequence which may be used as follow:

- prestate_init()
- state_init()
- state_fini()
- prestate_fini()

On the contrary, I can not imagine a test that will use all these four functions to establish a sensible use case.
This is why I think you should keep these functions as pairs instead:

- prestate_init()
- prestate_fini()
- state_init()
- state_fini()
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1100)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1100#-:-MdRVnJGEkwORBQ76yI1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Pull request merged**
