### PR TITLE
test: add rpma_peer_cfg_set_direct_write_to_pmem MT test

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1915)

### CODE REVIEW

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1915)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1915)* status: all files reviewed, 4 unresolved discussions (waiting on @osalyk)

___
*[`tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c` line 29 at r1](https://reviewable.io/reviews/pmem/rpma/1915#-N6DKNYiEsYah0ViSHc4:-N6DKNYiEsYah0ViSHc5:bqqres7) ([raw file](https://github.com/pmem/rpma/blob/721cfb95057f0d2d88c1dbecd1081b1c3a52981e/tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c#L29)):*
> ```C
>  */
> void
> init(unsigned id, void *prestate, void **state_ptr,
> ```

to ensure no issue in test initialization



_Suggestion:_
```C
thread_seq_init
```
___
*[`tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c` line 61 at r1](https://reviewable.io/reviews/pmem/rpma/1915#-N6DKpEo7HhcD4ihBufo:-N6DKpEo7HhcD4ihBufp:b-x53aym) ([raw file](https://github.com/pmem/rpma/blob/721cfb95057f0d2d88c1dbecd1081b1c3a52981e/tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c#L61)):*
> ```C
> 	if ((ret = rpma_peer_cfg_set_direct_write_to_pmem(st->pcfg, DIRECT_WRITE_TO_PMEM))) {
> 		MTT_RPMA_ERR(result, "rpma_peer_cfg_set_direct_write_to_pmem", ret);
> 		rpma_peer_cfg_delete(&st->pcfg);
> ```

let ``fini()`` does the final cleaning
___
*[`tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c` line 68 at r1](https://reviewable.io/reviews/pmem/rpma/1915#-N6DKzLL2D03Szl6_8Fh:-N6DKzLL2D03Szl6_8Fi:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/721cfb95057f0d2d88c1dbecd1081b1c3a52981e/tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c#L68)):*
> ```C
> 	if ((ret = rpma_peer_cfg_get_direct_write_to_pmem(st->pcfg, &direct_write_to_pmem))) {
> 		MTT_RPMA_ERR(result, "rpma_peer_cfg_get_direct_write_to_pmem", ret);
> 		rpma_peer_cfg_delete(&st->pcfg);
> ```

.
___
*[`tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c` line 107 at r1](https://reviewable.io/reviews/pmem/rpma/1915#-N6DKQK0-I2DfUTLWNhI:-N6DKQK0-I2DfUTLWNhJ:undefined) ([raw file](https://github.com/pmem/rpma/blob/721cfb95057f0d2d88c1dbecd1081b1c3a52981e/tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c#L107)):*
> ```C
> 			&prestate,
> 			NULL,
> 			NULL,
> ```





_Suggestion:_
```C
			&prestate,
			NULL,
			thread_seq_init,
			NULL,
```

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1915)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[`tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c` line 61 at r1](https://reviewable.io/reviews/pmem/rpma/1915#-N6DKpEo7HhcD4ihBufo:-N6DahaXEjKj-dKZlmuM:b-7dg490) ([raw file](https://github.com/pmem/rpma/blob/721cfb95057f0d2d88c1dbecd1081b1c3a52981e/tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c#L61)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

No other test has such an implementation
</blockquote></details>

the worse for other tests ;)
___
*[`tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c` line 68 at r1](https://reviewable.io/reviews/pmem/rpma/1915#-N6DKzLL2D03Szl6_8Fh:-N6Dam6-AmnguHVt6apl:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/721cfb95057f0d2d88c1dbecd1081b1c3a52981e/tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c#L68)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

.
</blockquote></details>

.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1915)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[`tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c` line 61 at r1](https://reviewable.io/reviews/pmem/rpma/1915#-N6DKpEo7HhcD4ihBufo:-N6DkNCj4n-uATIPpFig:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/721cfb95057f0d2d88c1dbecd1081b1c3a52981e/tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c#L61)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

the worse for other tests ;)
</blockquote></details>

Done.
___
*[`tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c` line 68 at r1](https://reviewable.io/reviews/pmem/rpma/1915#-N6DKzLL2D03Szl6_8Fh:-N6DkNjY0k8mZ7udj_KT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/721cfb95057f0d2d88c1dbecd1081b1c3a52981e/tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c#L68)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1915)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[`tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c` line 73 at r3](https://reviewable.io/reviews/pmem/rpma/1915#-N6DvIBn8Q5dmCFFBlLa:-N6DvIBn8Q5dmCFFBlLb:b-pq6199) ([raw file](https://github.com/pmem/rpma/blob/5e1ae30a746749cc8b64c7a268bbabf546ec1175/tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c#L73)):*
> ```C
> 
> 	/* create a new peer cfg object */
> 	if ((ret = rpma_peer_cfg_set_direct_write_to_pmem(st->pcfg, DIRECT_WRITE_TO_PMEM))) {
> ```

It will be automatically called by mtt framework, isn't it?
https://github.com/pmem/rpma/blob/1b664fcecbf07ebe3a98cc1301facd788317c16b/tests/multithreaded/common/mtt.c#L457



_Suggestion:_
```C
	if ((ret = rpma_peer_cfg_set_direct_write_to_pmem(st->pcfg, DIRECT_WRITE_TO_PMEM))) {
		MTT_RPMA_ERR(result, "rpma_peer_cfg_set_direct_write_to_pmem", ret);
		return;
	}
```
___
*[`tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c` line 80 at r3](https://reviewable.io/reviews/pmem/rpma/1915#-N6DwEf-ApX9xRI-f0Ms:-N6DwEf-ApX9xRI-f0Mt:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/5e1ae30a746749cc8b64c7a268bbabf546ec1175/tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c#L80)):*
> ```C
> 
> 	bool direct_write_to_pmem = false;
> 	if ((ret = rpma_peer_cfg_get_direct_write_to_pmem(st->pcfg, &direct_write_to_pmem))) {
> ```

.



_Suggestion:_
```C
	if ((ret = rpma_peer_cfg_get_direct_write_to_pmem(st->pcfg, &direct_write_to_pmem))) {
		MTT_RPMA_ERR(result, "rpma_peer_cfg_get_direct_write_to_pmem", ret);
		return;
	}
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1915)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[`tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c` line 73 at r3](https://reviewable.io/reviews/pmem/rpma/1915#-N6DvIBn8Q5dmCFFBlLa:-N6H4oVzC6dussC8L-6X:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5e1ae30a746749cc8b64c7a268bbabf546ec1175/tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c#L73)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

It will be automatically called by mtt framework, isn't it?
https://github.com/pmem/rpma/blob/1b664fcecbf07ebe3a98cc1301facd788317c16b/tests/multithreaded/common/mtt.c#L457
</blockquote></details>

Done.
___
*[`tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c` line 80 at r3](https://reviewable.io/reviews/pmem/rpma/1915#-N6DwEf-ApX9xRI-f0Ms:-N6H4pQuB2jF6xNv0K7A:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5e1ae30a746749cc8b64c7a268bbabf546ec1175/tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c#L80)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1915#-:-N6Ha5aqASJWY7YfKpy_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1915)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1915#-:-N6HbZBt4B7a2h9ctTWb:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1915)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by haichangsi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1915#-:-N6MW3Sc78wPZvbc3AuH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by haichangsi — COMMENTED** [review]
Thank you for reminding me. Now I remind you. What about CHANGELOG? ;)

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1915#-:-N6M_rjV5eAws5AKpYct:b7m5ft7)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1915#-:-N6Me5a8-sacunh67ILO:b-896fix)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @grom72 and @haichangsi)

**Review by grom72 — APPROVED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1915)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
