### PR TITLE
rpma: log the GID only when the build type is set to 'Debug'

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/2039)

### CODE REVIEW

**Review by osalyk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2039)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72, @haichangsi, and @ldorau)

___
*[`CHANGELOG.md` line 62 at r2](https://reviewable.io/reviews/pmem/rpma/2039#-NCeLoi75ittDbaBFMfu:-NCeLoi8E5AVZ-RV8cnl:b-s9w48i) ([raw file](https://github.com/pmem/rpma/blob/b6ebf004f24713ffb08a50d0f488698ba104d0c6/CHANGELOG.md#L62)):*
> ```Markdown
>   - 13-messages-ping-pong-with-srq - a multi-connection example for shared RQ with ping-pong messages
> 
> - logging of the source and the destination GID addresses in rpma_conn_req_new_from_id() only when the build type is set to 'Debug'
> ```

You should write it in the [Unreleased] section

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2039)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/pmem/rpma/2039#-NCeRsaL8_cCaZGxwfRC):*
`when CMAKE_BUILD_TYPE is set to 'Debug'`



_Code quote:_
```
when the build type is set to 'Debug'
```
___
*[`CHANGELOG.md` line 62 at r2](https://reviewable.io/reviews/pmem/rpma/2039#-NCeLoi75ittDbaBFMfu:-NCeRV0N0omKPDfU7TaG:b-frhb98) ([raw file](https://github.com/pmem/rpma/blob/b6ebf004f24713ffb08a50d0f488698ba104d0c6/CHANGELOG.md#L62)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

You should write it in the [Unreleased] section
</blockquote></details>

+1 Yes, `CHANGELOG.md` is an append-only file ;-) - you cannot modify the past releases.
___
*[`src/conn_req.c` line 166 at r2](https://reviewable.io/reviews/pmem/rpma/2039#-NCeTLEPBXRI8ZvmoIZo:-NCeTLEPBXRI8ZvmoIZp:b5scw4w) ([raw file](https://github.com/pmem/rpma/blob/b6ebf004f24713ffb08a50d0f488698ba104d0c6/src/conn_req.c#L166)):*
> ```C
> 	}
> #undef GID_STR_LEN
> ```

remove this empty line, please

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2039)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/pmem/rpma/2039#-NCeRsaL8_cCaZGxwfRC):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`when CMAKE_BUILD_TYPE is set to 'Debug'`
</blockquote></details>

Done.
___
*[`CHANGELOG.md` line 62 at r2](https://reviewable.io/reviews/pmem/rpma/2039#-NCeLoi75ittDbaBFMfu:-NCedeEO9xLJtdcyFZLa:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b6ebf004f24713ffb08a50d0f488698ba104d0c6/CHANGELOG.md#L62)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

+1 Yes, `CHANGELOG.md` is an append-only file ;-) - you cannot modify the past releases.
</blockquote></details>

Done.
___
*[`src/conn_req.c` line 166 at r2](https://reviewable.io/reviews/pmem/rpma/2039#-NCeTLEPBXRI8ZvmoIZo:-NCedxRKE5JEu--w3Duw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b6ebf004f24713ffb08a50d0f488698ba104d0c6/src/conn_req.c#L166)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

remove this empty line, please
</blockquote></details>

Done.

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2039#-:-NCefcO163y80nf0gXl1:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2039)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72 and @haichangsi)

___
*[`CHANGELOG.md` line 21 at r3](https://reviewable.io/reviews/pmem/rpma/2039#-NCek9oU-mObYh5Du3Vn:-NCek9oV2F6xWEo42XLH:blg51st) ([raw file](https://github.com/pmem/rpma/blob/11446c886ecc1769eef4e47ed600547bc6a96e37/CHANGELOG.md#L21)):*
> ```Markdown
> 
> ### Changed
> - logging of the source and the destination GID addresses in rpma_conn_req_new_from_id() only when CMAKE_BUILD_TYPE is set to 'Debug'
> ```

`... was restricted to only one case when CMAKE_BUILD_TYPE is set to 'Debug'`



_Code quote:_
```Markdown
only when CMAKE_BUILD_TYPE is set to 'Debug'
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2039)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @grom72, @ldorau, and @osalyk)

___
*[`CHANGELOG.md` line 21 at r3](https://reviewable.io/reviews/pmem/rpma/2039#-NCek9oU-mObYh5Du3Vn:-NCeoRdP8zG0sUAs03wT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/11446c886ecc1769eef4e47ed600547bc6a96e37/CHANGELOG.md#L21)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`... was restricted to only one case when CMAKE_BUILD_TYPE is set to 'Debug'`
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2039#-:-NCeowOyA2UiYURzzs3Y:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
@grom72  ?

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2039#-:-NCeoxmM84_sXAt2Xdxb:bndhleo)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2039)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2039#-:-NCsuN7CA4C5vuu7YqpD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by osalyk — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2039)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
