### PR TITLE
 tools: add test case descriptions

### PR DESCRIPTION
**Pull request by janekmi**
Requires:
- [x] #826

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/831)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/831)* status: all files reviewed, 8 unresolved discussions (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/831#-MSaWVGo8iGs6-3Q5wtO:-MSaWVGo8iGs6-3Q5wtP:bo6f8sp) (no related file):*
Would it be better to talk about the RPMA target instead of server-side, server side, remote-side, remote side?
Figure 0 introduces RPMA terget.

---
___
*[tools/templates/tc1_read.md, line 5 at r1](https://reviewable.io/reviews/pmem/rpma/831#-MSaW6LKCdMA5LcHvL6L:-MSaW6LKCdMA5LcHvL6M:b-tdo6iq) ([raw file](https://github.com/pmem/rpma/blob/122a62763b45854fb6a28439fdd86c6057702c5c/tools/templates/tc1_read.md#L5)):*
> ```
> Comparing the latency of `rpma_read()` from PMem on the remote-side (the server-side) to the latency of `rpma_read()` from DRAM on the remote-side using the `ib_read_lat` as the baseline.
> ```
 Comparing the latency of `rpma_read()` from PMem on the server-side (the remote-side) to the latency of `rpma_read()` from DRAM on the server-side using the `ib_read_lat` as the baseline.
___
*[tools/templates/tc2_write.md, line 1 at r1](https://reviewable.io/reviews/pmem/rpma/831#-MSaWmH-31x477UqYogu:-MSaWmH-31x477UqYogv:b-q2ghuf) ([raw file](https://github.com/pmem/rpma/blob/122a62763b45854fb6a28439fdd86c6057702c5c/tools/templates/tc2_write.md#L1)):*
> ```
> the remote-side
> ```
the RPMA target?
___
*[tools/templates/tc2_write.md, line 1 at r1](https://reviewable.io/reviews/pmem/rpma/831#-MSaYnAJ48g0bbeQVigB:-MSaYnAJ48g0bbeQVigC:b-yr5zki) ([raw file](https://github.com/pmem/rpma/blob/122a62763b45854fb6a28439fdd86c6057702c5c/tools/templates/tc2_write.md#L1)):*
> ```Markdown
> Benchmarking two ways of writing data persistently on the remote-side: *Appliance Persistency Method* (**APM**) and *General Purpose Persistency Method* (**GPSPM**). Where:
> ```

for APM, GPSPM shall we refer to our WP?
https://software.intel.com/content/www/us/en/develop/articles/persistent-memory-replication-over-traditional-rdma-part-1-understanding-remote-persistent.html
___
*[tools/templates/tc2_write.md, line 6 at r1](https://reviewable.io/reviews/pmem/rpma/831#-MSaYbn19Y5eIIN_hSR_:-MSaYbn19Y5eIIN_hSRa:b-rjgpjf) ([raw file](https://github.com/pmem/rpma/blob/122a62763b45854fb6a28439fdd86c6057702c5c/tools/templates/tc2_write.md#L6)):*
> ```
> without *Direct Write to PMem* capability
> ```
with *Direct Write to PMem* capability disabled
___
*[tools/templates/tc3_mix.md, line 1 at r1](https://reviewable.io/reviews/pmem/rpma/831#-MSaXjq340zbBBP5TzTn:-MSaXjq4EGM8xC-Eeyim:bge23kc) ([raw file](https://github.com/pmem/rpma/blob/122a62763b45854fb6a28439fdd86c6057702c5c/tools/templates/tc3_mix.md#L1)):*
> ```
> Benchmarking ... with
> ```
????
I could skip everything after ***with*** 
___
*[tools/templates/tc3_mix.md, line 5 at r1](https://reviewable.io/reviews/pmem/rpma/831#-MSaYDjz3iKjFDnknhhY:-MSaYDjz3iKjFDnknhhZ:b-xn1ioa) ([raw file](https://github.com/pmem/rpma/blob/122a62763b45854fb6a28439fdd86c6057702c5c/tools/templates/tc3_mix.md#L5)):*
> ```
> reads and writes
> ```
reads and writes (APM)
___
*[tools/templates/tc3_mix.md, line 19 at r1](https://reviewable.io/reviews/pmem/rpma/831#-MSaYPz7EV2627EtAji7:-MSaYPz7EV2627EtAji8:b-v2xyut) ([raw file](https://github.com/pmem/rpma/blob/122a62763b45854fb6a28439fdd86c6057702c5c/tools/templates/tc3_mix.md#L19)):*
> ```
> reads and writes
> ```
.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/831)* status: 0 of 3 files reviewed, 8 unresolved discussions (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/831#-MSaWVGo8iGs6-3Q5wtO:-MSb8St80kqu8RPJ1ui2:b-896fix) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Would it be better to talk about the RPMA target instead of server-side, server side, remote-side, remote side?
Figure 0 introduces RPMA terget.
</blockquote></details>

Done.

---
___
*[tools/templates/tc1_read.md, line 5 at r1](https://reviewable.io/reviews/pmem/rpma/831#-MSaW6LKCdMA5LcHvL6L:-MSb8w5QCcNPJmPbS_Ss:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/122a62763b45854fb6a28439fdd86c6057702c5c/tools/templates/tc1_read.md#L5)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Comparing the latency of `rpma_read()` from PMem on the remote-side (the server-side) to the latency of `rpma_read()` from DRAM on the remote-side using the `ib_read_lat` as the baseline.
> ```
 Comparing the latency of `rpma_read()` from PMem on the server-side (the remote-side) to the latency of `rpma_read()` from DRAM on the server-side using the `ib_read_lat` as the baseline.

</blockquote></details>

Done.
___
*[tools/templates/tc2_write.md, line 1 at r1](https://reviewable.io/reviews/pmem/rpma/831#-MSaYnAJ48g0bbeQVigB:-MSb9cUk6dLWB0ftRVNp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/122a62763b45854fb6a28439fdd86c6057702c5c/tools/templates/tc2_write.md#L1)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

for APM, GPSPM shall we refer to our WP?
https://software.intel.com/content/www/us/en/develop/articles/persistent-memory-replication-over-traditional-rdma-part-1-understanding-remote-persistent.html
</blockquote></details>

Done.
___
*[tools/templates/tc2_write.md, line 1 at r1](https://reviewable.io/reviews/pmem/rpma/831#-MSaWmH-31x477UqYogu:-MSb9krE5MtdA3RQ377m:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/122a62763b45854fb6a28439fdd86c6057702c5c/tools/templates/tc2_write.md#L1)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> the remote-side
> ```
the RPMA target?
</blockquote></details>

Done.
___
*[tools/templates/tc2_write.md, line 6 at r1](https://reviewable.io/reviews/pmem/rpma/831#-MSaYbn19Y5eIIN_hSR_:-MSb9yDE9ZLTRy_rJpxa:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/122a62763b45854fb6a28439fdd86c6057702c5c/tools/templates/tc2_write.md#L6)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> without *Direct Write to PMem* capability
> ```
with *Direct Write to PMem* capability disabled
</blockquote></details>

Done.
___
*[tools/templates/tc3_mix.md, line 1 at r1](https://reviewable.io/reviews/pmem/rpma/831#-MSaXjq340zbBBP5TzTn:-MSbAD0Z-d6UlQfNkPpB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/122a62763b45854fb6a28439fdd86c6057702c5c/tools/templates/tc3_mix.md#L1)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Benchmarking ... with
> ```
????
I could skip everything after ***with*** 
</blockquote></details>

Done.
___
*[tools/templates/tc3_mix.md, line 5 at r1](https://reviewable.io/reviews/pmem/rpma/831#-MSaYDjz3iKjFDnknhhY:-MSbAX3B9jYpcIMpkGb_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/122a62763b45854fb6a28439fdd86c6057702c5c/tools/templates/tc3_mix.md#L5)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> reads and writes
> ```
reads and writes (APM)
</blockquote></details>

Done.
___
*[tools/templates/tc3_mix.md, line 19 at r1](https://reviewable.io/reviews/pmem/rpma/831#-MSaYPz7EV2627EtAji7:-MSbAY1E5qHK4z8QzITj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/122a62763b45854fb6a28439fdd86c6057702c5c/tools/templates/tc3_mix.md#L19)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> reads and writes
> ```
.
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/831#-:-MSbGIm76Ixk42SM1Hs4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/831)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tools/templates/tc2_write.md, line 6 at r2](https://reviewable.io/reviews/pmem/rpma/831#-MSbqroL-1VxhzBqp23T:-MSbqroM-puIIGjLKGQB:bejj6ml) ([raw file](https://github.com/pmem/rpma/blob/bfd56c80821c8411063995531ab73cec6b4c9d17/tools/templates/tc2_write.md#L6)):*
> ```
> Chapter Two Remote Replication Methods
> ```

Chapter "Two Remote Replication Methods"
___
*[tools/templates/tc2_write.md, line 8 at r2](https://reviewable.io/reviews/pmem/rpma/831#-MSbr98-B6_mgbk2jWSM:-MSbr98-B6_mgbk2jWSN:b-21t4z6) ([raw file](https://github.com/pmem/rpma/blob/bfd56c80821c8411063995531ab73cec6b4c9d17/tools/templates/tc2_write.md#L8)):*
> ```
> Note data
> ```

Note that data
___
*[tools/templates/tc3_mix.md, line 1 at r2](https://reviewable.io/reviews/pmem/rpma/831#-MSbrcgZ9xdMSKq0Nuu1:-MSbrcgZ9xdMSKq0Nuu2:b-tjnl6e) ([raw file](https://github.com/pmem/rpma/blob/bfd56c80821c8411063995531ab73cec6b4c9d17/tools/templates/tc3_mix.md#L1)):*
> ```
> mixing `rpma_read()` from PMem on **the RPMA Target** and **APM** writes to the s
> ```

`rpma_read()` and  writes ?

reads and writes  OR `rpma_read()` and  `rpma_write()`

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/831)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/templates/tc2_write.md, line 6 at r2](https://reviewable.io/reviews/pmem/rpma/831#-MSbqroL-1VxhzBqp23T:-MSbt17u4vehSsVQJXDB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bfd56c80821c8411063995531ab73cec6b4c9d17/tools/templates/tc2_write.md#L6)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> Chapter Two Remote Replication Methods
> ```

Chapter "Two Remote Replication Methods"
</blockquote></details>

Done.
___
*[tools/templates/tc2_write.md, line 8 at r2](https://reviewable.io/reviews/pmem/rpma/831#-MSbr98-B6_mgbk2jWSM:-MSbt5jg5W42j7ADsjqZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bfd56c80821c8411063995531ab73cec6b4c9d17/tools/templates/tc2_write.md#L8)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> Note data
> ```

Note that data
</blockquote></details>

Done.
___
*[tools/templates/tc3_mix.md, line 1 at r2](https://reviewable.io/reviews/pmem/rpma/831#-MSbrcgZ9xdMSKq0Nuu1:-MSbth0K6OA4hA7oU6ta:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bfd56c80821c8411063995531ab73cec6b4c9d17/tools/templates/tc3_mix.md#L1)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> mixing `rpma_read()` from PMem on **the RPMA Target** and **APM** writes to the s
> ```

`rpma_read()` and  writes ?

reads and writes  OR `rpma_read()` and  `rpma_write()` 
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/831)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/831#-:-MSbvIyO96LGtq2m9W61:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/831)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
