### PR TITLE
tools: configure SoftRoCE before build commands on CircleCi

### PR DESCRIPTION
**Pull request by grom72**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1883)

### CODE REVIEW

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1883#-:-N5_VN9S4ZJVzQBk7Uzz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by haichangsi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1883#-:-N5_gHkm3HwaQ5nm_PW1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1883)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1883)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1883#-N5eMFcJ7kcTEbt6dCPo:-N5eMFcJ7kcTEbt6dCPp:b969t5x) (no related file):*
@grom72 rebase please

___

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1883)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`.circleci/config.yml` line 31 at r2](https://reviewable.io/reviews/pmem/rpma/1883#-N5eNJCCEzSpPyZG4fg8:-N5eNJCCEzSpPyZG4fg9:bgffc0l) ([raw file](https://github.com/pmem/rpma/blob/8c556e819a7675af8a5cfebd685cfa73598242af/.circleci/config.yml#L31)):*
> ```YAML
>       - run:
>           # Configure SoftRoCE and read the RPMA_TESTING_IP environment variable
>           name: Configure SoftRoCE
> ```

It is duplicated now



_Code quote:_
```YAML
      - run:
          # Configure SoftRoCE and read the RPMA_TESTING_IP environment variable
          name: Configure SoftRoCE
          command: cd build && make config_softroce && source $BASH_ENV
```

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1883)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1883#-N5eMFcJ7kcTEbt6dCPo:-N5eNO143zzQSMtHc6cQ:b-896fjx) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@grom72 rebase please
</blockquote></details>

Done

___
___
*[`.circleci/config.yml` line 31 at r2](https://reviewable.io/reviews/pmem/rpma/1883#-N5eNJCCEzSpPyZG4fg8:-N5eNQO08eBbryVA-vdB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8c556e819a7675af8a5cfebd685cfa73598242af/.circleci/config.yml#L31)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It is duplicated now
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1883)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`.circleci/config.yml` line 31 at r2](https://reviewable.io/reviews/pmem/rpma/1883#-N5eNJCCEzSpPyZG4fg8:-N5eNQZQAKzcd3KESLNi:b-ecvt8e) ([raw file](https://github.com/pmem/rpma/blob/8c556e819a7675af8a5cfebd685cfa73598242af/.circleci/config.yml#L31)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It is duplicated now
</blockquote></details>

Now it is OK :-)

**Pull request merged**
