### PR TITLE
tools: perf: split report bench into apm_gpsm, apm_gpspm_cpu and aof

### PR DESCRIPTION
**Pull request by janekmi**
Requires:
- [x] #1030

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1034)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1034)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/report_bench.sh, line 157 at r1](https://reviewable.io/reviews/pmem/rpma/1034#-MZMV9349BvybmI4Des1:-MZMV9349BvybmI4Des2:bn74jv5) ([raw file](https://github.com/pmem/rpma/blob/18fd1642e04bae8800d9d80a65c3d1caebf81449/tools/perf/report_bench.sh#L157)):*
> ```
> apvgp|asvah)
> ```
Should be renamed too
___
*[tools/perf/rpma_fio_bench.sh, line 50 at r1](https://reviewable.io/reviews/pmem/rpma/1034#-MZMVVaaCQF28ykhY5VW:-MZMVVab8Urj8pYABkez:b-8b12p5) ([raw file](https://github.com/pmem/rpma/blob/18fd1642e04bae8800d9d80a65c3d1caebf81449/tools/perf/rpma_fio_bench.sh#L50)):*
> ```
> =${CPU_LOAD_RANGE-00_100}
> ```

`=${CPU_LOAD_RANGE_00_100}`

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1034)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/report_bench.sh, line 157 at r1](https://reviewable.io/reviews/pmem/rpma/1034#-MZMV9349BvybmI4Des1:-MZMWCZb2WhnmEvbIFcC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/18fd1642e04bae8800d9d80a65c3d1caebf81449/tools/perf/report_bench.sh#L157)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> apvgp|asvah)
> ```
Should be renamed too
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1034)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1034)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1034#-:-MZMZFhoAtp-gYizyNpb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1034#-:-MZM_Uw60OVLgUSuabCu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
