### PR TITLE
test: add one rpma_read and two rpma_write MT tests

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #1710
- [x] #1713

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1717)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
> Reviewed 3 of 14 files at r1, 3 of 8 files at r3, 1 of 1 files at r4, 2 of 2 files at r6, 1 of 1 files at r7, 2 of 2 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1717)* status: 12 of 16 files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 14 files at r1, 3 of 8 files at r3, 1 of 1 files at r4, 4 of 4 files at r5, 2 of 2 files at r6, 1 of 1 files at r7, 2 of 2 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1717)* status: all files reviewed, 12 unresolved discussions (waiting on @ldorau)

___
*[`tests/multithreaded/conn/rpma_read.c` line 46 at r9](https://reviewable.io/reviews/pmem/rpma/1717#-N0pOmnSC_MJ8iTGb7Iy:-N0pOmnTAtVr3_2PJNIE:b-kxp73y) ([raw file](https://github.com/pmem/rpma/blob/ae94045f172d46bbb7f11eabe6b2ac21661a4a77/tests/multithreaded/conn/rpma_read.c#L46)):*
> ```C
> 	}
> 
> 	if (wc.status != IBV_WC_SUCCESS) {
> ```

We do not know if it is a read until we check it.



_Suggestion:_
```C
	if (wc.opcode != IBV_WC_RDMA_READ) {
		MTT_ERR_MSG(result, "unexpected wc.opcode value", -1);
		return;
	}
	
	if (wc.status != IBV_WC_SUCCESS) {
		MTT_ERR_MSG(result, "rpma_read() failed", -1);
		return;
	}
```
___
*[`tests/multithreaded/conn/rpma_write.c` line 30 at r9](https://reviewable.io/reviews/pmem/rpma/1717#-N0pNWXM4dUJlO-rBCPF:-N0pNWXM4dUJlO-rBCPG:bfmz4nk) ([raw file](https://github.com/pmem/rpma/blob/ae94045f172d46bbb7f11eabe6b2ac21661a4a77/tests/multithreaded/conn/rpma_write.c#L30)):*
> ```C
> 
> 	/* wait for the completion to be ready */
> 	ret = rpma_cq_wait(ts->cq);
> ```

How difficult will be to run this test w/ and w/o wait?



_Code quote:_
```C
ret = rpma_cq_wait(ts->cq);
```
___
*[`tests/multithreaded/conn/rpma_write.c` line 36 at r9](https://reviewable.io/reviews/pmem/rpma/1717#-N0pNSm98PhJi37PGxh2:-N0pNSm98PhJi37PGxh3:undefined) ([raw file](https://github.com/pmem/rpma/blob/ae94045f172d46bbb7f11eabe6b2ac21661a4a77/tests/multithreaded/conn/rpma_write.c#L36)):*
> ```C
> 	}
> 
> 	/* wait for a completion of the RDMA write */
> ```





_Suggestion:_
```C
/* get a completion of the RDMA write */
```
___
*[`tests/multithreaded/conn/rpma_write.c` line 44 at r9](https://reviewable.io/reviews/pmem/rpma/1717#-N0pMgaYCl6vW6jdREpo:-N0pMgaYCl6vW6jdREpp:bhlobu1) ([raw file](https://github.com/pmem/rpma/blob/ae94045f172d46bbb7f11eabe6b2ac21661a4a77/tests/multithreaded/conn/rpma_write.c#L44)):*
> ```C
> 
> 	if (wc.status != IBV_WC_SUCCESS) {
> 		MTT_ERR_MSG(result, "rpma_write() failed", -1);
> ```

First, we have to know that it is a rpma_write() operation, then we can check its status and print an error message.



_Suggestion:_
```C
	if (wc.opcode != IBV_WC_RDMA_WRITE) {
		MTT_ERR_MSG(result, "unexpected wc.opcode value", -1);
		return;
	}
	
	if (wc.status != IBV_WC_SUCCESS) {
		MTT_ERR_MSG(result, "rpma_write() failed", -1);
		return;
	}
```
___
*[`tests/multithreaded/conn/rpma_write_read.c` line 44 at r9](https://reviewable.io/reviews/pmem/rpma/1717#-N0pMxFV1fC9fraj93_F:-N0pMxFV1fC9fraj93_G:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/ae94045f172d46bbb7f11eabe6b2ac21661a4a77/tests/multithreaded/conn/rpma_write_read.c#L44)):*
> ```C
> 	}
> 
> 	if (wc.status != IBV_WC_SUCCESS) {
> ```

.



_Suggestion:_
```C

	if (wc.opcode != IBV_WC_RDMA_WRITE) {
		MTT_ERR_MSG(result, "unexpected wc.opcode value", -1);
		return;
	}
	
	if (wc.status != IBV_WC_SUCCESS) {
		MTT_ERR_MSG(result, "rpma_write() failed", -1);
		return;
	}
```
___
*[`tests/multithreaded/conn/rpma_write_read.c` line 80 at r9](https://reviewable.io/reviews/pmem/rpma/1717#-N0pN1yICpzO6PMGKXbV:-N0pN1yICpzO6PMGKXbW:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/ae94045f172d46bbb7f11eabe6b2ac21661a4a77/tests/multithreaded/conn/rpma_write_read.c#L80)):*
> ```C
> 
> 	if (wc.status != IBV_WC_SUCCESS) {
> 		MTT_ERR_MSG(result, "rpma_read() failed", -1);
> ```

.



_Suggestion:_
```C
	if (wc.opcode != IBV_WC_RDMA_READ) {
		MTT_ERR_MSG(result, "unexpected wc.opcode value", -1);
		return;
	}
	
	if (wc.status != IBV_WC_SUCCESS) {
		MTT_ERR_MSG(result, "rpma_read() failed", -1);
		return;
	}
```
___
*[`tests/multithreaded/conn/server_rpma_common.c` line 103 at r9](https://reviewable.io/reviews/pmem/rpma/1717#-N0pLNH6ETSB7Qy5WCEa:-N0pLNH79SC2h1SMzBc6:b-6ssht9) ([raw file](https://github.com/pmem/rpma/blob/ae94045f172d46bbb7f11eabe6b2ac21661a4a77/tests/multithreaded/conn/server_rpma_common.c#L103)):*
> ```C
>  */
> struct client_res *
> client_new(struct server_res *svr)
> ```

The name definitely should not start with ``client`` as it is a part of server functionality.
Below is an example.



_Suggestion:_
```C
server_first_free_client_slot
```
___
*[`tests/multithreaded/conn/server_rpma_common.c` line 122 at r9](https://reviewable.io/reviews/pmem/rpma/1717#-N0pO13cDE5utomR6Eeq:-N0pO13cDE5utomR6Eer:b-o2yc9v) ([raw file](https://github.com/pmem/rpma/blob/ae94045f172d46bbb7f11eabe6b2ac21661a4a77/tests/multithreaded/conn/server_rpma_common.c#L122)):*
> ```C
> }
> 
> void client_handle_completion(struct custom_event *ce);
> ```

The handle of the client's completion.



_Suggestion:_
```C
client_completion_event_handle
```
___
*[`tests/multithreaded/conn/server_rpma_common.c` line 123 at r9](https://reviewable.io/reviews/pmem/rpma/1717#-N0pOAvuBQwtmzCPS-db:-N0pOAvuBQwtmzCPS-dc:undefined) ([raw file](https://github.com/pmem/rpma/blob/ae94045f172d46bbb7f11eabe6b2ac21661a4a77/tests/multithreaded/conn/server_rpma_common.c#L123)):*
> ```C
> 
> void client_handle_completion(struct custom_event *ce);
> void client_handle_connection_event(struct custom_event *ce);
> ```





_Suggestion:_
```C
client_connection_event_handle
```
___
*[`tests/multithreaded/conn/server_rpma_common.c` line 129 at r9](https://reviewable.io/reviews/pmem/rpma/1717#-N0pLj1b7cggCobjn5ap:-N0pLj1b7cggCobjn5aq:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/ae94045f172d46bbb7f11eabe6b2ac21661a4a77/tests/multithreaded/conn/server_rpma_common.c#L129)):*
> ```C
>  */
> int
> client_add_to_epoll(struct client_res *clnt, int epoll)
> ```

.



_Suggestion:_
```C
server_add_client_fd_to_epoll
```
___
*[`tests/multithreaded/conn/server_rpma_common.c` line 159 at r9](https://reviewable.io/reviews/pmem/rpma/1717#-N0pLrix0jqk5GAY_spr:-N0pLrix0jqk5GAY_sps:b-y0xfg8) ([raw file](https://github.com/pmem/rpma/blob/ae94045f172d46bbb7f11eabe6b2ac21661a4a77/tests/multithreaded/conn/server_rpma_common.c#L159)):*
> ```C
>  */
> void
> client_delete(struct client_res *clnt)
> ```

.

short form ``svr_delete_client`` or just ``delete_client``



_Suggestion:_
```C
server_delete_client
```
___
*[`tests/multithreaded/conn/server_rpma_common.c` line 215 at r9](https://reviewable.io/reviews/pmem/rpma/1717#-N0pOPBC80gwA8zYf2cy:-N0pOPBC80gwA8zYf2cz:undefined) ([raw file](https://github.com/pmem/rpma/blob/ae94045f172d46bbb7f11eabe6b2ac21661a4a77/tests/multithreaded/conn/server_rpma_common.c#L215)):*
> ```C
>  */
> void
> server_handle_incoming_client(struct custom_event *ce)
> ```





_Suggestion:_
```C
server_incoming_connection_handle
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1717)* status: all files reviewed, 12 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`tests/multithreaded/conn/rpma_read.c` line 46 at r9](https://reviewable.io/reviews/pmem/rpma/1717#-N0pOmnSC_MJ8iTGb7Iy:-N1D-oQh3NZUTm3v7yiv:bs7qofg) ([raw file](https://github.com/pmem/rpma/blob/ae94045f172d46bbb7f11eabe6b2ac21661a4a77/tests/multithreaded/conn/rpma_read.c#L46)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

We do not know if it is a read until we check it.
</blockquote></details>

It cannot be done in this way. ibv_poll_cq()'s manual says:
"*If the completion status is other than IBV_WC_SUCCESS, only the following attributes are valid: wr_id, status, qp_num, and vendor_err.*"

I have changed the message to "completion status is different from IBV_WC_SUCCESS".



_Code quote:_
```C
status
```
___
*[`tests/multithreaded/conn/rpma_write.c` line 30 at r9](https://reviewable.io/reviews/pmem/rpma/1717#-N0pNWXM4dUJlO-rBCPF:-N1D17PR35iL-JmnqCXO:bewrg0t) ([raw file](https://github.com/pmem/rpma/blob/ae94045f172d46bbb7f11eabe6b2ac21661a4a77/tests/multithreaded/conn/rpma_write.c#L30)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

How difficult will be to run this test w/ and w/o wait?
</blockquote></details>

Probably we will have to add a new command line parameter.
___
*[`tests/multithreaded/conn/rpma_write.c` line 36 at r9](https://reviewable.io/reviews/pmem/rpma/1717#-N0pNSm98PhJi37PGxh2:-N1D1QMa2KE0Vw6Cd1Gv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ae94045f172d46bbb7f11eabe6b2ac21661a4a77/tests/multithreaded/conn/rpma_write.c#L36)):*
> ```C
> 	}
> 
> 	/* wait for a completion of the RDMA write */
> ```

Done.
___
*[`tests/multithreaded/conn/rpma_write.c` line 44 at r9](https://reviewable.io/reviews/pmem/rpma/1717#-N0pMgaYCl6vW6jdREpo:-N1D1XQj-41ZdjWjhCZ7:b-dj4dt8) ([raw file](https://github.com/pmem/rpma/blob/ae94045f172d46bbb7f11eabe6b2ac21661a4a77/tests/multithreaded/conn/rpma_write.c#L44)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

First, we have to know that it is a rpma_write() operation, then we can check its status and print an error message.
</blockquote></details>

No ... "*If the completion status is other than IBV_WC_SUCCESS, only the following attributes are valid: wr_id, status, qp_num, and vendor_err.*"
___
*[`tests/multithreaded/conn/rpma_write_read.c` line 44 at r9](https://reviewable.io/reviews/pmem/rpma/1717#-N0pMxFV1fC9fraj93_F:-N1D2GKpDVwV10LjTDmc:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/ae94045f172d46bbb7f11eabe6b2ac21661a4a77/tests/multithreaded/conn/rpma_write_read.c#L44)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

.
___
*[`tests/multithreaded/conn/rpma_write_read.c` line 80 at r9](https://reviewable.io/reviews/pmem/rpma/1717#-N0pN1yICpzO6PMGKXbV:-N1D2Hv82Wleu3Mjtr7C:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/ae94045f172d46bbb7f11eabe6b2ac21661a4a77/tests/multithreaded/conn/rpma_write_read.c#L80)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1717)* status: 10 of 16 files reviewed, 12 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`tests/multithreaded/conn/server_rpma_common.c` line 103 at r9](https://reviewable.io/reviews/pmem/rpma/1717#-N0pLNH6ETSB7Qy5WCEa:-N1D3dv_5GT-sG2SOnIw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ae94045f172d46bbb7f11eabe6b2ac21661a4a77/tests/multithreaded/conn/server_rpma_common.c#L103)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

The name definitely should not start with ``client`` as it is a part of server functionality.
Below is an example.
</blockquote></details>

Done.
___
*[`tests/multithreaded/conn/server_rpma_common.c` line 122 at r9](https://reviewable.io/reviews/pmem/rpma/1717#-N0pO13cDE5utomR6Eeq:-N1D4-Ov2YjBnIyjtqc1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ae94045f172d46bbb7f11eabe6b2ac21661a4a77/tests/multithreaded/conn/server_rpma_common.c#L122)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

The handle of the client's completion.
</blockquote></details>

Done.
___
*[`tests/multithreaded/conn/server_rpma_common.c` line 123 at r9](https://reviewable.io/reviews/pmem/rpma/1717#-N0pOAvuBQwtmzCPS-db:-N1D47HY9XD63F7WAknF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ae94045f172d46bbb7f11eabe6b2ac21661a4a77/tests/multithreaded/conn/server_rpma_common.c#L123)):*
> ```C
> 
> void client_handle_completion(struct custom_event *ce);
> void client_handle_connection_event(struct custom_event *ce);
> ```

Done.
___
*[`tests/multithreaded/conn/server_rpma_common.c` line 129 at r9](https://reviewable.io/reviews/pmem/rpma/1717#-N0pLj1b7cggCobjn5ap:-N1D4KgL2xXgfpt9VZqO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ae94045f172d46bbb7f11eabe6b2ac21661a4a77/tests/multithreaded/conn/server_rpma_common.c#L129)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`tests/multithreaded/conn/server_rpma_common.c` line 159 at r9](https://reviewable.io/reviews/pmem/rpma/1717#-N0pLrix0jqk5GAY_spr:-N1D4bbe9LamRMngj_mx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ae94045f172d46bbb7f11eabe6b2ac21661a4a77/tests/multithreaded/conn/server_rpma_common.c#L159)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.

short form ``svr_delete_client`` or just ``delete_client``
</blockquote></details>

Done.
___
*[`tests/multithreaded/conn/server_rpma_common.c` line 215 at r9](https://reviewable.io/reviews/pmem/rpma/1717#-N0pOPBC80gwA8zYf2cy:-N1D5aZr87PauSe5T0pR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ae94045f172d46bbb7f11eabe6b2ac21661a4a77/tests/multithreaded/conn/server_rpma_common.c#L215)):*
> ```C
>  */
> void
> server_handle_incoming_client(struct custom_event *ce)
> ```

Done.

**Review by grom72 — APPROVED** [review]
> Reviewed 6 of 6 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1717)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1717)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau and @osalyk)

___
*[`tests/multithreaded/conn/server_rpma_common.h` line 62 at r11](https://reviewable.io/reviews/pmem/rpma/1717#-N1DM_7n0l05UPMpDMrd:-N1DM_7n0l05UPMpDMre:undefined) ([raw file](https://github.com/pmem/rpma/blob/92fe2fe02c55c4c7229c8d72379c52c7de5be914/tests/multithreaded/conn/server_rpma_common.h#L62)):*
> ```objc
> 
> /*
>  * client_handle_is_ready -- callback on connection is established (test-specific)
> ```





_Suggestion:_
```objc
client_is_ready_handle
```

**Review by grom72 — COMMENTED** [review]
:goat: 

> Reviewed 5 of 5 files at r12, 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1717#-:-N1DZiPvBGq81_tBwYS3:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau and @osalyk)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1717)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72 and @osalyk)

___
*[`tests/multithreaded/conn/server_rpma_common.h` line 62 at r11](https://reviewable.io/reviews/pmem/rpma/1717#-N1DM_7n0l05UPMpDMrd:-N1Da94b12dSfJrxI_Pq:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/92fe2fe02c55c4c7229c8d72379c52c7de5be914/tests/multithreaded/conn/server_rpma_common.h#L62)):*
> ```objc
> 
> /*
>  * client_handle_is_ready -- callback on connection is established (test-specific)
> ```

Done.

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1717#-:-N1DcMMP0r_kL5x0WZyA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r12, 3 of 3 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1717#-:-N1Dh0Y_DRy8d3q07Wz_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r14.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1717)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @osalyk)

**Review by grom72 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1717)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — APPROVED** [review]
> Reviewed 3 of 4 files at r15, 1 of 1 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1717)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by osalyk — APPROVED** [review]
> Reviewed 1 of 1 files at r16, 2 of 2 files at r17, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1717)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
> Reviewed 3 of 4 files at r15, 1 of 1 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1717)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
