### PR TITLE
common: explicit message about EXPERIMENTAL nature of the script

### PR DESCRIPTION
**Pull request by grom72**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/648)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/648)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/ib_read.sh, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/648#-MO6kjWl4b21lu_RXhH8:-MO6kjWl4b21lu_RXhH9:bxjk7ec) ([raw file](https://github.com/pmem/rpma/blob/97c662e7add3af44fecbd425ade7e88ad267e17b/tools/ib_read.sh#L20)):*
> ```Shell
> TIMESTAMP=$(date +%y-%m-%d-%H%M%S)
> 
> echo "THIS TOOL IS EXPERIMENTAL. YOU ARE USING IT ON YOUR OWN RISK."
> ```

Please agree on a single output format with @ldorau #647.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/648)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/ib_read.sh, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/648#-MO6kjWl4b21lu_RXhH8:-MO6uPeh681l-_LJHmCG:ban5eo4) ([raw file](https://github.com/pmem/rpma/blob/97c662e7add3af44fecbd425ade7e88ad267e17b/tools/ib_read.sh#L20)):*
> ```
> echo "THIS TOOL IS EXPERIMENTAL. YOU ARE USING IT ON YOUR OWN RISK."
> ```
Is taken from ddio.sh script

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/648)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/ib_read.sh, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/648#-MO6kjWl4b21lu_RXhH8:-MO7ATe76AOy6WTjEmGQ:b-478ala) ([raw file](https://github.com/pmem/rpma/blob/97c662e7add3af44fecbd425ade7e88ad267e17b/tools/ib_read.sh#L20)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> echo "THIS TOOL IS EXPERIMENTAL. YOU ARE USING IT ON YOUR OWN RISK."
> ```
Is taken from ddio.sh script

</blockquote></details>

I think the message "`THIS TOOL IS EXPERIMENTAL. YOU ARE USING IT ON YOUR OWN RISK.`" is too dramatic. It may give the impression that this tool is dangerous and can erase the data or destroy the hardware. In my opinion the `"This tool is EXPERIMENTAL"` message is enough.

The `ddio.sh` script is a different case - it changes the HW settings. The benchmarking scripts do not do that.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/648)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/648)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[tools/ib_read.sh, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/648#-MO6kjWl4b21lu_RXhH8:-MOAluRV6LQWzYR9NEsJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/97c662e7add3af44fecbd425ade7e88ad267e17b/tools/ib_read.sh#L20)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I think the message "`THIS TOOL IS EXPERIMENTAL. YOU ARE USING IT ON YOUR OWN RISK.`" is too dramatic. It may give the impression that this tool is dangerous and can erase the data or destroy the hardware. In my opinion the `"This tool is EXPERIMENTAL"` message is enough.

The `ddio.sh` script is a different case - it changes the HW settings. The benchmarking scripts do not do that.

</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/648)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/648#-:-MOAuVke9kNzyf-Y3num:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Pull request merged**
