### PR TITLE
examples: fix 07-atomic-write example

### PR DESCRIPTION
**Pull request by ldorau**
It sometimes happens that the second `rpma_conn_completion_get()`
(after `rpma_conn_completion_wait()`) also fails with `RPMA_E_NO_COMPLETION`:

```
rpma_conn_completion_get()
rpma_conn_completion_wait()
rpma_conn_completion_get()
```

so we have to repeat them until `rpma_conn_completion_get()` succeeds.

Fixes: #1010

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1011)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1011#-:-MYe2MOo6wAfiIAzAiwc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1011)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1011#-MYl5txLDmvSMYGedHTn:-MYl5txLDmvSMYGedHTo:bnnhhmk) (no related file):*
Do you have any piece from the documentation which allows `rpma_conn_completion_wait()` to succeed whilst an actual completion is not yet available?

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1011)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1011#-MYl5txLDmvSMYGedHTn:-MYmo8Y3BCTFloEocZBG:bi61xuh) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Do you have any piece from the documentation which allows `rpma_conn_completion_wait()` to succeed whilst an actual completion is not yet available?
</blockquote></details>

No, it sometimes happens on SoftRoCE, just that.

---

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1011)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1011#-MYl5txLDmvSMYGedHTn:-MYtkjmU7Hywk8wiZrRx:beezqi0) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No, it sometimes happens on SoftRoCE, just that.
</blockquote></details>

I don't like writing SoftRoCE-specific things in an example. People will learn from here that it is required to have a loop overarching these API calls whereas in most cases it is not true.

Why this happens in this example but not in the others? Is there anything special about it?

---

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1011)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1011#-MYl5txLDmvSMYGedHTn:-MYx-PPy1JG3j8xr8UT6:bl17exu) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I don't like writing SoftRoCE-specific things in an example. People will learn from here that it is required to have a loop overarching these API calls whereas in most cases it is not true.

Why this happens in this example but not in the others? Is there anything special about it?
</blockquote></details>

Does ibv_poll_cq() consumes also an event from ibv_get_cq_event()? - No.
Imlemeatio  must cover two scenarios:
- completion is received before ibv_req_notify_cq()
- completion is received after ibv_req_notify_cq()
In the case of SoftROCE, it is most probably some particular time dependence.

---

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1011#-:-MYx1PdK0ud5gDwIy2Ya:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1011)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1011#-MYl5txLDmvSMYGedHTn:-MYx1RbdCiwwf2pUi9oc:be984lo) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Does ibv_poll_cq() consumes also an event from ibv_get_cq_event()? - No.
Imlemeatio  must cover two scenarios:
- completion is received before ibv_req_notify_cq()
- completion is received after ibv_req_notify_cq()
In the case of SoftROCE, it is most probably some particular time dependence.
</blockquote></details>

The solution should be propagated later on to all examples.

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1011)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1011#-MYl5txLDmvSMYGedHTn:-MYxPjdg6W7gMVa-PfM_:b-50rcgi) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

The solution should be propagated later on to all examples.
</blockquote></details>

It occurs also on the real HW once per about 122 times on average.
Precisely it occurred after the following number of retries: 20, 80, 169, 254, 128, 100, 105 ...

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1011)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1011#-MYl5txLDmvSMYGedHTn:-MYxhTsz6dv51LFldAJg:b-yqteyd) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It occurs also on the real HW once per about 122 times on average.
Precisely it occurred after the following number of retries: 20, 80, 169, 254, 128, 100, 105 ...

</blockquote></details>

With this fix it works well also on the real HW.

---

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1011)* status: all files reviewed, 5 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1011#-MYl5txLDmvSMYGedHTn:-MYyEXTO7LU3trDLE7rp:bml1rou) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

With this fix it works well also on the real HW.
</blockquote></details>

Thank you for proving it is not limited to SoftRoCE.

---
___
*[examples/07-atomic-write/client.c, line 123 at r1](https://reviewable.io/reviews/pmem/rpma/1011#-MYxbHLi96YRNQIPzQtk:-MYxbHLj3SbtcNz2-9qa:b-iwhz2e) ([raw file](https://github.com/pmem/rpma/blob/9382fc1f80df85b1285c67eb067957882df1d0d7/examples/07-atomic-write/client.c#L123)):*
> ```C
> 		if ((ret = rpma_conn_completion_wait(conn)))
> 			goto err_mr_remote_delete;
> 	} while (1); /* no completion available */
> ```

Have you truly got an error here?

It is the first completion of the app. In my opinion, no matter when the completion will come the previous implementation doing get/wait/get should be sufficient, it is not?
___
*[examples/07-atomic-write/client.c, line 179 at r1](https://reviewable.io/reviews/pmem/rpma/1011#-MYyBBaT8abL3an2eXtj:-MYyBBaT8abL3an2eXtk:b-2ryfd) ([raw file](https://github.com/pmem/rpma/blob/9382fc1f80df85b1285c67eb067957882df1d0d7/examples/07-atomic-write/client.c#L179)):*
> ```C
> 			break;
> 
> 		do {
> ```

I'm missing a comment on why we have a loop here e.g.:

Since completions are collected in a for-loop it may happen the completion is collected (rpma_conn_completion_get()) before an event indicating its arrival (rpma_conn_completion_wait()). So, when the next revolution will come the next completion may not be ready yet and despite the rpma_conn_completion_wait() indicates the next completion is ready it is not because the event is related to the completion already consumed in the previous revolution.
___
*[examples/07-atomic-write/client.c, line 188 at r1](https://reviewable.io/reviews/pmem/rpma/1011#-MYyAmh_8_o8d94VZZFL:-MYyAmh_8_o8d94VZZFM:b-o7ndv8) ([raw file](https://github.com/pmem/rpma/blob/9382fc1f80df85b1285c67eb067957882df1d0d7/examples/07-atomic-write/client.c#L188)):*
> ```C
> 
> 			/* wait for the completion to be ready */
> 			if ((ret = rpma_conn_completion_wait(conn)))
> ```

I'm missing a comment here:
`since the completion fd is by default in a blocking mode any non-zero return from this function indicates an error`
___
*[examples/07-atomic-write/client.c, line 190 at r1](https://reviewable.io/reviews/pmem/rpma/1011#-MYyAeQ65C9iVeEdJNxy:-MYyAeQ65C9iVeEdJNxz:b8834wq) ([raw file](https://github.com/pmem/rpma/blob/9382fc1f80df85b1285c67eb067957882df1d0d7/examples/07-atomic-write/client.c#L190)):*
> ```C
> 			if ((ret = rpma_conn_completion_wait(conn)))
> 				goto err_mr_remote_delete;
> 		} while (1); /* no completion available */
> ```

`a completion has to appear at some point`?
___
*[examples/07-atomic-write/client.c, line 190 at r1](https://reviewable.io/reviews/pmem/rpma/1011#-MYyCcx98AluOTlUE0dA:-MYyCcx98AluOTlUE0dB:bhh51ac) ([raw file](https://github.com/pmem/rpma/blob/9382fc1f80df85b1285c67eb067957882df1d0d7/examples/07-atomic-write/client.c#L190)):*
> ```C
> 			if ((ret = rpma_conn_completion_wait(conn)))
> 				goto err_mr_remote_delete;
> 		} while (1); /* no completion available */
> ```

# Discussing

If the issue is where we think it is the following fix should work as well:

```c
// no do-while-loop
ret = rpma_conn_completion_get(conn, &cmpl);
if (ret && ret != RPMA_E_NO_COMPLETION)
    break;

if (ret == RPMA_E_NO_COMPLETION {
    /* wait for the completion to be ready */
    if ((ret = rpma_conn_completion_wait(conn)))
        break;
    else if ((ret = rpma_conn_completion_get(conn, &cmpl)))
        break;
} else {
    /* XXX collect and ack the event related to the collected completion */
    if ((ret = rpma_conn_completion_wait(conn)))
        break;
}
```

Of course, this implementation is dirty and may be simplified. But I wanted to make it easier to follow.
If it is the case I think we should consider introducing an API like `rpma_conn_completion_ack(conn)` which should be called after `rpma_conn_completion_get()` if one want to use `rpma_conn_completion_wait()` afterwards.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1011)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[examples/07-atomic-write/client.c, line 123 at r1](https://reviewable.io/reviews/pmem/rpma/1011#-MYxbHLi96YRNQIPzQtk:-MYyFuEE6R1J_eQA0z0M:b-tb2qkp) ([raw file](https://github.com/pmem/rpma/blob/9382fc1f80df85b1285c67eb067957882df1d0d7/examples/07-atomic-write/client.c#L123)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Have you truly got an error here?

It is the first completion of the app. In my opinion, no matter when the completion will come the previous implementation doing get/wait/get should be sufficient, it is not?
</blockquote></details>

No, AFAIR I did not, I just wanted to unify both places.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1011)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[examples/07-atomic-write/client.c, line 190 at r1](https://reviewable.io/reviews/pmem/rpma/1011#-MYyCcx98AluOTlUE0dA:-MYyjmInDAlCLEeLQvhi:b-aia4l0) ([raw file](https://github.com/pmem/rpma/blob/9382fc1f80df85b1285c67eb067957882df1d0d7/examples/07-atomic-write/client.c#L190)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

# Discussing

If the issue is where we think it is the following fix should work as well:

```c
// no do-while-loop
ret = rpma_conn_completion_get(conn, &cmpl);
if (ret && ret != RPMA_E_NO_COMPLETION)
    break;

if (ret == RPMA_E_NO_COMPLETION {
    /* wait for the completion to be ready */
    if ((ret = rpma_conn_completion_wait(conn)))
        break;
    else if ((ret = rpma_conn_completion_get(conn, &cmpl)))
        break;
} else {
    /* XXX collect and ack the event related to the collected completion */
    if ((ret = rpma_conn_completion_wait(conn)))
        break;
}
```

Of course, this implementation is dirty and may be simplified. But I wanted to make it easier to follow.
If it is the case I think we should consider introducing an API like `rpma_conn_completion_ack(conn)` which should be called after `rpma_conn_completion_get()` if one want to use `rpma_conn_completion_wait()` afterwards.
</blockquote></details>

The issue is different. Please read the commit message. Your proposal does not change anything. The program exits with error when the second `rpma_conn_completion_get` fails with `RPMA_E_NO_COMPLETION`.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1011)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[examples/07-atomic-write/client.c, line 190 at r1](https://reviewable.io/reviews/pmem/rpma/1011#-MYyAeQ65C9iVeEdJNxy:-MYyp-r03U0NZYBeD_C7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9382fc1f80df85b1285c67eb067957882df1d0d7/examples/07-atomic-write/client.c#L190)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`a completion has to appear at some point`?
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1011)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[examples/07-atomic-write/client.c, line 179 at r1](https://reviewable.io/reviews/pmem/rpma/1011#-MYyBBaT8abL3an2eXtj:-MYyr6QG8AHiA2WYd5Ql:bkjf04f) ([raw file](https://github.com/pmem/rpma/blob/9382fc1f80df85b1285c67eb067957882df1d0d7/examples/07-atomic-write/client.c#L179)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I'm missing a comment on why we have a loop here e.g.:

Since completions are collected in a for-loop it may happen the completion is collected (rpma_conn_completion_get()) before an event indicating its arrival (rpma_conn_completion_wait()). So, when the next revolution will come the next completion may not be ready yet and despite the rpma_conn_completion_wait() indicates the next completion is ready it is not because the event is related to the completion already consumed in the previous revolution.
</blockquote></details>

Where is this for-loop you have mentioned?

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1011)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[examples/07-atomic-write/client.c, line 123 at r1](https://reviewable.io/reviews/pmem/rpma/1011#-MYxbHLi96YRNQIPzQtk:-MYyqGKmBkQUYmwqXXnc:b-jh1v8r) ([raw file](https://github.com/pmem/rpma/blob/9382fc1f80df85b1285c67eb067957882df1d0d7/examples/07-atomic-write/client.c#L123)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No, AFAIR I did not, I just wanted to unify both places.
</blockquote></details>

An additional loop for aesthetic reasons is not a good idea. The loop has to serve a well-defined purpose. I am against changing the implementation here if it is not necessary.
___
*[examples/07-atomic-write/client.c, line 179 at r1](https://reviewable.io/reviews/pmem/rpma/1011#-MYyBBaT8abL3an2eXtj:-MYyrXXDCyTo8vIS1ti0:bha1nin) ([raw file](https://github.com/pmem/rpma/blob/9382fc1f80df85b1285c67eb067957882df1d0d7/examples/07-atomic-write/client.c#L179)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Where is this for-loop you have mentioned?
</blockquote></details>

It starts in line 153.
___
*[examples/07-atomic-write/client.c, line 190 at r1](https://reviewable.io/reviews/pmem/rpma/1011#-MYyCcx98AluOTlUE0dA:-MYyqwZ86J-SQEuuY3Tc:bd9b03h) ([raw file](https://github.com/pmem/rpma/blob/9382fc1f80df85b1285c67eb067957882df1d0d7/examples/07-atomic-write/client.c#L190)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The issue is different. Please read the commit message. Your proposal does not change anything. The program exits with error when the second `rpma_conn_completion_get` fails with `RPMA_E_NO_COMPLETION`.
</blockquote></details>

So the question is why it fails since, having my implementation, completions and events should go hand-in-hand.
Can you imagine a scenario in which they are somehow decoupled? Which may result in an "empty" event with no completion to collect?

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1011)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1011)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[examples/07-atomic-write/client.c, line 190 at r1](https://reviewable.io/reviews/pmem/rpma/1011#-MYyCcx98AluOTlUE0dA:-MYysxrVCaOkjZB07Qc4:b-svbkhm) ([raw file](https://github.com/pmem/rpma/blob/9382fc1f80df85b1285c67eb067957882df1d0d7/examples/07-atomic-write/client.c#L190)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

So the question is why it fails since, having my implementation, completions and events should go hand-in-hand.
Can you imagine a scenario in which they are somehow decoupled? Which may result in an "empty" event with no completion to collect?
</blockquote></details>

It is possible that completion might not generate an event.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1011)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[examples/07-atomic-write/client.c, line 123 at r1](https://reviewable.io/reviews/pmem/rpma/1011#-MYxbHLi96YRNQIPzQtk:-MYyyE9y4xyulT_7ITDd:b-9wc4a0) ([raw file](https://github.com/pmem/rpma/blob/9382fc1f80df85b1285c67eb067957882df1d0d7/examples/07-atomic-write/client.c#L123)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

An additional loop for aesthetic reasons is not a good idea. The loop has to serve a well-defined purpose. I am against changing the implementation here if it is not necessary.
</blockquote></details>

OK, reverted
___
*[examples/07-atomic-write/client.c, line 179 at r1](https://reviewable.io/reviews/pmem/rpma/1011#-MYyBBaT8abL3an2eXtj:-MYywlS066buMcpX0CCe:b-ocism6) ([raw file](https://github.com/pmem/rpma/blob/9382fc1f80df85b1285c67eb067957882df1d0d7/examples/07-atomic-write/client.c#L179)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It starts in line 153.
</blockquote></details>

Ahh, this loop ... :-) OK
___
*[examples/07-atomic-write/client.c, line 188 at r1](https://reviewable.io/reviews/pmem/rpma/1011#-MYyAmh_8_o8d94VZZFL:-MYyrMey40kl_JBy0LjS:bv6dlx6) ([raw file](https://github.com/pmem/rpma/blob/9382fc1f80df85b1285c67eb067957882df1d0d7/examples/07-atomic-write/client.c#L188)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I'm missing a comment here:
`since the completion fd is by default in a blocking mode any non-zero return from this function indicates an error`
</blockquote></details>

Is an example appropriate place for such low-level technical comment? Maybe it should go rather to the documentation of this function in the public header?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1011)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[examples/07-atomic-write/client.c, line 123 at r1](https://reviewable.io/reviews/pmem/rpma/1011#-MYxbHLi96YRNQIPzQtk:-MYz1B68-_Uu-keje9zc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9382fc1f80df85b1285c67eb067957882df1d0d7/examples/07-atomic-write/client.c#L123)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK, reverted
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 179 at r1](https://reviewable.io/reviews/pmem/rpma/1011#-MYyBBaT8abL3an2eXtj:-MYz1C19-pHXK4xcX8wN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9382fc1f80df85b1285c67eb067957882df1d0d7/examples/07-atomic-write/client.c#L179)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Ahh, this loop ... :-) OK
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1011)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[examples/07-atomic-write/client.c, line 190 at r1](https://reviewable.io/reviews/pmem/rpma/1011#-MYyCcx98AluOTlUE0dA:-MYz3IEK0Qk9k0EqkdzD:b-h4vz0t) ([raw file](https://github.com/pmem/rpma/blob/9382fc1f80df85b1285c67eb067957882df1d0d7/examples/07-atomic-write/client.c#L190)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

It is possible that completion might not generate an event.
</blockquote></details>

The `else` added by you will never be executed, because if `(ret != RPMA_E_NO_COMPLETION)` it will exit at the first `break`here:
```
		/* try to get a completion */
		ret = rpma_conn_completion_get(conn, &cmpl);
		if (ret && ret != RPMA_E_NO_COMPLETION)
			break;
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1011)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[examples/07-atomic-write/client.c, line 190 at r1](https://reviewable.io/reviews/pmem/rpma/1011#-MYyCcx98AluOTlUE0dA:-MYz40ce6UNhDT8tf5fo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9382fc1f80df85b1285c67eb067957882df1d0d7/examples/07-atomic-write/client.c#L190)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The `else` added by you will never be executed, because if `(ret != RPMA_E_NO_COMPLETION)` it will exit at the first `break`here:
```
		/* try to get a completion */
		ret = rpma_conn_completion_get(conn, &cmpl);
		if (ret && ret != RPMA_E_NO_COMPLETION)
			break;
```
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1011#-:-MZ42HfLAemuu8Cz-tsa:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[examples/07-atomic-write/client.c, line 188 at r1](https://reviewable.io/reviews/pmem/rpma/1011#-MYyAmh_8_o8d94VZZFL:-MZ41uM92JAEuppaTEyw:b6b7hr0) ([raw file](https://github.com/pmem/rpma/blob/9382fc1f80df85b1285c67eb067957882df1d0d7/examples/07-atomic-write/client.c#L188)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Is an example appropriate place for such low-level technical comment? Maybe it should go rather to the documentation of this function in the public header?
</blockquote></details>

@ldorau is right
___
*[examples/07-atomic-write/client.c, line 191 at r3](https://reviewable.io/reviews/pmem/rpma/1011#-MZ41abo-w-DmIAtmrCX:-MZ41abo-w-DmIAtmrCY:b4putsz) ([raw file](https://github.com/pmem/rpma/blob/02bb0cd1dff5a372b2f83d99e3b4e26ada9bbec1/examples/07-atomic-write/client.c#L191)):*
> ```C
> 		 * that had already been consumed in the previous iteration.
> 		 */
> 		do {
> ```

:ok_hand:

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1011)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[examples/07-atomic-write/client.c, line 188 at r1](https://reviewable.io/reviews/pmem/rpma/1011#-MYyAmh_8_o8d94VZZFL:-MZBd-LV-0JKpormN1N6:b32w0x) ([raw file](https://github.com/pmem/rpma/blob/9382fc1f80df85b1285c67eb067957882df1d0d7/examples/07-atomic-write/client.c#L188)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

@ldorau is right
</blockquote></details>

OK

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1011#-:-MZCYtAU4CLx-MCsKXxa:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

**Review by ldorau — COMMENTED** [review]
See: https://app.circleci.com/pipelines/github/ldorau/rpma/388/workflows/c7d0e39f-74f8-4455-b15e-2def3a30162e/jobs/400

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1011#-:-MZnphaGB4LuESTaVLi8:b-q6iqdh)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

**Review by ldorau — COMMENTED** [review]
See: https://app.circleci.com/pipelines/github/ldorau/rpma/413/workflows/4438458c-bee8-4463-bec9-f889aacfccbe/jobs/425

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1011#-:-MZwaj7IDnY6ddGd5PD8:b9zaa5o)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

**Review by ldorau — COMMENTED** [review]
See: https://app.circleci.com/pipelines/github/ldorau/rpma/425/workflows/10c59f67-53f7-4659-a97f-13fb35a46fdc/jobs/437

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1011#-:-M_0i7yH1TWdPXnxxqo7:b-yxw82z)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

**Comment by janekmi** [comment]
This fix was replaced by #1057.

**Pull request closed without merging**
