### PR TITLE
rpma: improve error logging

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/476)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/476)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[src/conn.c, line 186 at r1](https://reviewable.io/reviews/pmem/rpma/476#-MINxZ1s2h3i7VwexBgA:-MINxZ1s2h3i7VwexBgB:bljyocy) ([raw file](https://github.com/pmem/rpma/blob/79cefa58000bf2411ba4f555c7a6bd035fbd3e06/src/conn.c#L186)):*
> ```
> "%s: %d"
> ```

```
"%s: %s"
```
___
*[src/conn.c, line 508 at r1](https://reviewable.io/reviews/pmem/rpma/476#-MINxHVz08QlfttY1I4K:-MINxHW-2ojjGI8UpBuT:bdzysio) ([raw file](https://github.com/pmem/rpma/blob/79cefa58000bf2411ba4f555c7a6bd035fbd3e06/src/conn.c#L508)):*
> ```
> RPMA_LOG_ERROR("ibv_poll_cq() failed (no details provided)");
> ```

just:
`RPMA_LOG_ERROR("ibv_poll_cq() failed");`

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/476)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[src/conn.c, line 186 at r1](https://reviewable.io/reviews/pmem/rpma/476#-MINxZ1s2h3i7VwexBgA:-MINxxmS-BU4VxvJZcfj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/79cefa58000bf2411ba4f555c7a6bd035fbd3e06/src/conn.c#L186)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> "%s: %d"
> ```

```
"%s: %s"
```
</blockquote></details>

Done.
___
*[src/conn.c, line 508 at r1](https://reviewable.io/reviews/pmem/rpma/476#-MINxHVz08QlfttY1I4K:-MINy45ME3064snAa1NR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/79cefa58000bf2411ba4f555c7a6bd035fbd3e06/src/conn.c#L508)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> RPMA_LOG_ERROR("ibv_poll_cq() failed (no details provided)");
> ```

just:
`RPMA_LOG_ERROR("ibv_poll_cq() failed");`
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/476)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/476)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[src/conn.c, line 508 at r2](https://reviewable.io/reviews/pmem/rpma/476#-MIOPDr44_BYz3q3j1kl:-MIOPDr44_BYz3q3j1km:b-wlj2dv) ([raw file](https://github.com/pmem/rpma/blob/fb5412c9afaab35d84519068d62847c6bc912713/src/conn.c#L508)):*
> ```C
> 		/* ibv_poll_cq() may return only -1; no errno provided */
> 		Rpma_provider_error = result;
> 		RPMA_LOG_ERROR("ibv_poll_cq() failed");
> ```

```c
RPMA_LOG_ERROR("ibv_poll_cq() failed (no details provided)");
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/476)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[src/conn.c, line 508 at r2](https://reviewable.io/reviews/pmem/rpma/476#-MIOPDr44_BYz3q3j1kl:-MIOaT6z2fpGiDoRthKT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fb5412c9afaab35d84519068d62847c6bc912713/src/conn.c#L508)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
RPMA_LOG_ERROR("ibv_poll_cq() failed (no details provided)");
```
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/476)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/476#-:-MIOb6V652xHhmccOjm1:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/476#-:-MIOeQ4gEvMjNeh9C85G:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
