### PR TITLE
test: rpma_utils_ibv_context_is_odp_capable multithreaded test

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1025)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1025)* status: all files reviewed, 14 unresolved discussions (waiting on @osalyk)

___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/1025#-MZG1aLR-nFN3PaQKCTi:-MZG1aLS91cwIO03f3Fw:b-jmbwzs) ([raw file](https://github.com/pmem/rpma/blob/b192ccde914ab67d9d98359a8ecabc00887cc683/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L20)):*
> ```C
> 	char *addr;
> 	struct ibv_context *dev;
> 	int is_odp_supported;
> ```

I would argue this one should be called _exp.
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 24 at r1](https://reviewable.io/reviews/pmem/rpma/1025#-MZG1gWW6g5FrZXPkWeo:-MZG1gWW6g5FrZXPkWep:bnftu8z) ([raw file](https://github.com/pmem/rpma/blob/b192ccde914ab67d9d98359a8ecabc00887cc683/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L24)):*
> ```C
> 
> struct state {
> 	int is_odp_supported_exp;
> ```

~~_exp~~
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 29 at r1](https://reviewable.io/reviews/pmem/rpma/1025#-MZG1rkN7O1KxScCPhL6:-MZG1rkN7O1KxScCPhL7:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/b192ccde914ab67d9d98359a8ecabc00887cc683/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L29)):*
> ```C
> /*
>  * prestate_init -- obtain an ibv_context for a local IP address
>  * and check if the device context's capability supports On-Demand Paging
> ```

.
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 45 at r1](https://reviewable.io/reviews/pmem/rpma/1025#-MZG1nGj13rQjxGf2Y5C:-MZG1nGj13rQjxGf2Y5D:babxzfg) ([raw file](https://github.com/pmem/rpma/blob/b192ccde914ab67d9d98359a8ecabc00887cc683/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L45)):*
> ```C
> 	}
> 
> 	/* check if the device context's capability supports On-Demand Paging */
> ```

`check if the device supports On-Demand Paging`
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 50 at r1](https://reviewable.io/reviews/pmem/rpma/1025#-MZG1uCCCV06aF0-IsrF:-MZG1uCCCV06aF0-IsrG:b-s3hmk9) ([raw file](https://github.com/pmem/rpma/blob/b192ccde914ab67d9d98359a8ecabc00887cc683/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L50)):*
> ```C
> 	if (ret) {
> 		MTT_RPMA_ERR(tr, "rpma_utils_ibv_context_is_odp_capable", ret);
> 		return;
> ```

Not needed.
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 67 at r1](https://reviewable.io/reviews/pmem/rpma/1025#-MZG1yZs40R79LcV3AJm:-MZG1yZs40R79LcV3AJn:b-s3hmk9) ([raw file](https://github.com/pmem/rpma/blob/b192ccde914ab67d9d98359a8ecabc00887cc683/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L67)):*
> ```C
> 
> 	*state_ptr = st;
> }
> ```

Not needed.
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 86 at r1](https://reviewable.io/reviews/pmem/rpma/1025#-MZG208N99Gw67uSF5Xr:-MZG208N99Gw67uSF5Xs:b-70vfl1) ([raw file](https://github.com/pmem/rpma/blob/b192ccde914ab67d9d98359a8ecabc00887cc683/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L86)):*
> ```C
> 		MTT_RPMA_ERR(tr, "rpma_utils_get_ibv_context", ret);
> 		return;
> 	}
> ```

Not needed. You should use the device context from the prestate.
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 88 at r1](https://reviewable.io/reviews/pmem/rpma/1025#-MZG24QaDfgd3V6F-34x:-MZG24QaDfgd3V6F-34y:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/b192ccde914ab67d9d98359a8ecabc00887cc683/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L88)):*
> ```C
> 	}
> 
> 	/* check if the device context's capability supports On-Demand Paging */
> ```

.
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 90 at r1](https://reviewable.io/reviews/pmem/rpma/1025#-MZG25QQDn-K2bQ2ySRN:-MZG25QQDn-K2bQ2ySRO:b54lejg) ([raw file](https://github.com/pmem/rpma/blob/b192ccde914ab67d9d98359a8ecabc00887cc683/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L90)):*
> ```C
> 	/* check if the device context's capability supports On-Demand Paging */
> 	ret = rpma_utils_ibv_context_is_odp_capable(dev,
> 				&st->is_odp_supported_exp);
> ```

Use local variable `is_odp_supported`
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 93 at r1](https://reviewable.io/reviews/pmem/rpma/1025#-MZG2BqQ7jC1kMruU4AO:-MZG2BqQ7jC1kMruU4AP:b-s3hmk9) ([raw file](https://github.com/pmem/rpma/blob/b192ccde914ab67d9d98359a8ecabc00887cc683/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L93)):*
> ```C
> 	if (ret) {
> 		MTT_RPMA_ERR(tr, "rpma_utils_ibv_context_is_odp_capable", ret);
> 		return;
> ```

Not needed.
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 97 at r1](https://reviewable.io/reviews/pmem/rpma/1025#-MZG2EJTAVBhIhNA7YdT:-MZG2EJTAVBhIhNA7YdU:b-sal4yk) ([raw file](https://github.com/pmem/rpma/blob/b192ccde914ab67d9d98359a8ecabc00887cc683/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L97)):*
> ```C
> 		fprintf(stderr,
> 				"Unexpected value: is_odp_supported = %d, is_odp_supported_exp = %d\n",
> 			pr->is_odp_supported, st->is_odp_supported_exp);
> ```

You can not push anything to the stderr. You are in a thread.
Please use MTT_ERR.
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 98 at r1](https://reviewable.io/reviews/pmem/rpma/1025#-MZG2V0p7ANxrMcKwVDB:-MZG2V0p7ANxrMcKwVDC:b-s3hmk9) ([raw file](https://github.com/pmem/rpma/blob/b192ccde914ab67d9d98359a8ecabc00887cc683/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L98)):*
> ```C
> 				"Unexpected value: is_odp_supported = %d, is_odp_supported_exp = %d\n",
> 			pr->is_odp_supported, st->is_odp_supported_exp);
> 		return;
> ```

Not needed.
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 110 at r1](https://reviewable.io/reviews/pmem/rpma/1025#-MZG2XZs9y1hFxE8DWbg:-MZG2XZs9y1hFxE8DWbh:b-s3hmk9) ([raw file](https://github.com/pmem/rpma/blob/b192ccde914ab67d9d98359a8ecabc00887cc683/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L110)):*
> ```C
> 	struct state *st = (struct state *)*state_ptr;
> 	free(st);
> }
> ```

Not needed.
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 120 at r1](https://reviewable.io/reviews/pmem/rpma/1025#-MZG2bWp7m5K0uWO4Z9t:-MZG2bWp7m5K0uWO4Z9u:ba4a2de) ([raw file](https://github.com/pmem/rpma/blob/b192ccde914ab67d9d98359a8ecabc00887cc683/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L120)):*
> ```
> 		return -1;
> 	struct prestate prestate = {args.addr, NULL, 0};
> 	struct mtt_test test = {
> ```

You are missing a few new lines here.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1025)* status: 0 of 1 files reviewed, 14 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/1025#-MZG1aLR-nFN3PaQKCTi:-MZGk_by5CXq4Os4kt-R:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b192ccde914ab67d9d98359a8ecabc00887cc683/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L20)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I would argue this one should be called _exp.
</blockquote></details>

Done.
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 24 at r1](https://reviewable.io/reviews/pmem/rpma/1025#-MZG1gWW6g5FrZXPkWeo:-MZGkaWT0vDxSNlHQjQ5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b192ccde914ab67d9d98359a8ecabc00887cc683/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L24)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

~~_exp~~
</blockquote></details>

Done.
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 29 at r1](https://reviewable.io/reviews/pmem/rpma/1025#-MZG1rkN7O1KxScCPhL6:-MZGkwP9EhTu0GEGeYow:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b192ccde914ab67d9d98359a8ecabc00887cc683/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L29)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 45 at r1](https://reviewable.io/reviews/pmem/rpma/1025#-MZG1nGj13rQjxGf2Y5C:-MZGkkuY8xTuR-fasIBa:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b192ccde914ab67d9d98359a8ecabc00887cc683/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L45)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`check if the device supports On-Demand Paging`
</blockquote></details>

Done.
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 50 at r1](https://reviewable.io/reviews/pmem/rpma/1025#-MZG1uCCCV06aF0-IsrF:-MZGlBjQ1cEL0FpcZbD_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b192ccde914ab67d9d98359a8ecabc00887cc683/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L50)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not needed.
</blockquote></details>

Done.
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 67 at r1](https://reviewable.io/reviews/pmem/rpma/1025#-MZG1yZs40R79LcV3AJm:-MZGnFg95dgZ7bP6z_tA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b192ccde914ab67d9d98359a8ecabc00887cc683/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L67)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not needed.
</blockquote></details>

Done.
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 86 at r1](https://reviewable.io/reviews/pmem/rpma/1025#-MZG208N99Gw67uSF5Xr:-MZGlvnd-2RHxUbmeetc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b192ccde914ab67d9d98359a8ecabc00887cc683/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L86)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not needed. You should use the device context from the prestate.
</blockquote></details>

Done.
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 88 at r1](https://reviewable.io/reviews/pmem/rpma/1025#-MZG24QaDfgd3V6F-34x:-MZGkqKB9Oikcy8rMPA2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b192ccde914ab67d9d98359a8ecabc00887cc683/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L88)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 90 at r1](https://reviewable.io/reviews/pmem/rpma/1025#-MZG25QQDn-K2bQ2ySRN:-MZGnUso7a5J3ON_bZkH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b192ccde914ab67d9d98359a8ecabc00887cc683/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L90)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Use local variable `is_odp_supported`
</blockquote></details>

Done.
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 93 at r1](https://reviewable.io/reviews/pmem/rpma/1025#-MZG2BqQ7jC1kMruU4AO:-MZGmGBn0Fb1Zix-a9Xn:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b192ccde914ab67d9d98359a8ecabc00887cc683/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L93)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not needed.
</blockquote></details>

Done.
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 97 at r1](https://reviewable.io/reviews/pmem/rpma/1025#-MZG2EJTAVBhIhNA7YdT:-MZGmiL-2d9WjOAYQwhA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b192ccde914ab67d9d98359a8ecabc00887cc683/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L97)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You can not push anything to the stderr. You are in a thread.
Please use MTT_ERR.
</blockquote></details>

Done.
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 98 at r1](https://reviewable.io/reviews/pmem/rpma/1025#-MZG2V0p7ANxrMcKwVDB:-MZGmj982_KkAn_jr0MW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b192ccde914ab67d9d98359a8ecabc00887cc683/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L98)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not needed.
</blockquote></details>

Done.
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 110 at r1](https://reviewable.io/reviews/pmem/rpma/1025#-MZG2XZs9y1hFxE8DWbg:-MZGnh2E6HA9w1d--i9x:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b192ccde914ab67d9d98359a8ecabc00887cc683/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L110)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not needed.
</blockquote></details>

Done.
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 120 at r1](https://reviewable.io/reviews/pmem/rpma/1025#-MZG2bWp7m5K0uWO4Z9t:-MZGn7HV9TePmiO0NUP-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b192ccde914ab67d9d98359a8ecabc00887cc683/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L120)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

> ```
> 		return -1;
> 	struct prestate prestate = {args.addr, NULL, 0};
> 	struct mtt_test test = {
> ```

You are missing a few new lines here.
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1025)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 50 at r1](https://reviewable.io/reviews/pmem/rpma/1025#-MZG1uCCCV06aF0-IsrF:-MZIFQvU5-9FUE7fpFlB:brqn95u) ([raw file](https://github.com/pmem/rpma/blob/b192ccde914ab67d9d98359a8ecabc00887cc683/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L50)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You can also get rid of the brackets. ;-)
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/1025#-MZIGHHwBZqlkQgGBJ4u:-MZIGHHwBZqlkQgGBJ4v:b-k9rye9) ([raw file](https://github.com/pmem/rpma/blob/8d73ac3e89e1c484802a6699aa54deb5ac46eb63/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L15)):*
> ```C
> 
> #include <librpma.h>
> #include <mtt.h>
> ```

Please use `""` instead of `<>`.
And separate this local header inclusion from the public one.
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 66 at r2](https://reviewable.io/reviews/pmem/rpma/1025#-MZIGhvH-6eDcZVDIlke:-MZIGhvH-6eDcZVDIlkf:brwljsg) ([raw file](https://github.com/pmem/rpma/blob/8d73ac3e89e1c484802a6699aa54deb5ac46eb63/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L66)):*
> ```C
> 	} else if (is_odp_supported != pr->is_odp_supported_exp) {
> 		MTT_RPMA_ERR(tr,
> 		"is_odp_supported != is_odp_supported_exp", ret);
> ```

```c
MTT_ERR(tr, "is_odp_supported != is_odp_supported_exp", EINVAL);
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1025)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 50 at r1](https://reviewable.io/reviews/pmem/rpma/1025#-MZG1uCCCV06aF0-IsrF:-MZILotd74ugZy6wWsQK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b192ccde914ab67d9d98359a8ecabc00887cc683/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L50)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You can also get rid of the brackets. ;-)
</blockquote></details>

Done.
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/1025#-MZIGHHwBZqlkQgGBJ4u:-MZILWVZDzRRrBT7FP6E:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8d73ac3e89e1c484802a6699aa54deb5ac46eb63/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L15)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please use `""` instead of `<>`.
And separate this local header inclusion from the public one.
</blockquote></details>

Done.
___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 66 at r2](https://reviewable.io/reviews/pmem/rpma/1025#-MZIGhvH-6eDcZVDIlke:-MZIM32q627jCdDg4iSV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8d73ac3e89e1c484802a6699aa54deb5ac46eb63/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L66)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
MTT_ERR(tr, "is_odp_supported != is_odp_supported_exp", EINVAL);
```
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1025)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 66 at r2](https://reviewable.io/reviews/pmem/rpma/1025#-MZIGhvH-6eDcZVDIlke:-MZIOxjK2zocHlKe4uXP:bwobtat) ([raw file](https://github.com/pmem/rpma/blob/8d73ac3e89e1c484802a6699aa54deb5ac46eb63/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L66)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

MTT_RPMA_ERR -> MTT_ERR

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1025)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c, line 66 at r2](https://reviewable.io/reviews/pmem/rpma/1025#-MZIGhvH-6eDcZVDIlke:-MZIPY7y2sa0C5K2_qNX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8d73ac3e89e1c484802a6699aa54deb5ac46eb63/tests/multithreaded/utils/rpma_utils_ibv_context_is_odp_capable.c#L66)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

MTT_RPMA_ERR -> MTT_ERR
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1025#-:-MZIRNesCSox4_VXcvDl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
