### PR TITLE
tools: ib_read.py - change names from logfile to errfile

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1416)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1416)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1416)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 189 at r2](https://reviewable.io/reviews/pmem/rpma/1416#-MqzklYGBAQIXZa4Vis9:-MqzklYHBQoOb7M1G8Md:b-hjbn6r) ([raw file](https://github.com/pmem/rpma/blob/308aa4e3409b794d735b095707b38526f9f269d8/tools/perf/lib/benchmark/runner/ib_read.py#L189)):*
> ```
> ___log__
> ```
__log__ or __err__?

**Review by osalyk — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1416)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1416#-Mr18O7c1jKzXvog2Sa6:-Mr18O7dBP1Q3CnJUU6L:bt7qhct) (no related file):*
Why do we need this change?

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1416)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1416#-Mr18O7c1jKzXvog2Sa6:-Mr1S1ZFAOYLAnF4f1_t:b-pdhx4r) (no related file):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Why do we need this change?
</blockquote></details>

Because we need separate log files for 
1) stdout and dumped commands
2) stderr

like it was in the bash version:

```
	elif [ "$DUMP_CMDS" == "1" ]; then
		SERVER_DUMP=${NAME}-server.log
		CLIENT_DUMP=${NAME}-client.log
		LOG_ERR=${NAME}-errors.log
```

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1416#-Mr1TCyg8bmaRcSBWKk8:-Mr1TCyg8bmaRcSBWKk9:bi0bhsn) (no related file):*
@haichangsi Since we need both log files, this PR should be modified in the following way, so please:
1) do the following changes for both runners: ib_read and fio,
2) do not change, but add new error log file names (because we still need the old one),
3) direct all stdout to *.log and all stderr to *.err,
4) give the commit and PR an appropriate name

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1416)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 189 at r2](https://reviewable.io/reviews/pmem/rpma/1416#-MqzklYGBAQIXZa4Vis9:-Mr1X67TCr7RVSbjNKHx:bu5ub17) ([raw file](https://github.com/pmem/rpma/blob/308aa4e3409b794d735b095707b38526f9f269d8/tools/perf/lib/benchmark/runner/ib_read.py#L189)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> ___log__
> ```
__log__ or __err__?
</blockquote></details>

We will set here names for all log files:
```
        self.__settings['logfile_server'] = name + '-server.log'
        self.__settings['logfile_client'] = name + '-client.log'
        self.__settings['errfile_server'] = name + '-server.err'
        self.__settings['errfile_client'] = name + '-client.err'
```

so, in my opinion, the current name is good and can stay as is.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1416)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1416#-Mr18O7c1jKzXvog2Sa6:-Mr1tWyw1NbZVaPa0Nnl:bh6y3mo) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Because we need separate log files for 
1) stdout and dumped commands
2) stderr

like it was in the bash version:

```
	elif [ "$DUMP_CMDS" == "1" ]; then
		SERVER_DUMP=${NAME}-server.log
		CLIENT_DUMP=${NAME}-client.log
		LOG_ERR=${NAME}-errors.log
```
</blockquote></details>

Change of design - there should be only one log file for stdout, stderr and dumped commands, so this PR can be closed.

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1416#-Mr1TCyg8bmaRcSBWKk8:-Mr1tBwN7OQ8SBnSX_3i:bh6y3mo) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@haichangsi Since we need both log files, this PR should be modified in the following way, so please:
1) do the following changes for both runners: ib_read and fio,
2) do not change, but add new error log file names (because we still need the old one),
3) direct all stdout to *.log and all stderr to *.err,
4) give the commit and PR an appropriate name

</blockquote></details>

Change of design - there should be only one log file for stdout, stderr and dumped commands, so this PR can be closed.

---

**Pull request closed without merging**
