### PR TITLE
tools: fio.py: implement __client_run()

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1417)

### CODE REVIEW

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1417)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1417)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @grom72 and @haichangsi)

**Review by osalyk — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1417)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1417#-Mr1Mq2m2Lu_p9KTdNhs:-Mr1Mq2n0MJ_wenSv9i-:b-ujmq67) (no related file):*
Rebase please

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1417)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72, @haichangsi, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1417#-Mr1Mq2m2Lu_p9KTdNhs:-Mr1Q0vdBx8cTWaUzaXP:b-896fix) (no related file):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Rebase please
</blockquote></details>

Done.

---

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1417)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 219 at r2](https://reviewable.io/reviews/pmem/rpma/1417#-Mr1ZwEF2UONHrTZZJ-B:-Mr1ZwEF2UONHrTZZJ-C:b-dcbcdn) ([raw file](https://github.com/pmem/rpma/blob/90d59f662e8870e3cd077c829051bef3549e3557/tools/perf/lib/benchmark/runner/fio.py#L219)):*
> ```Python
>             args = ['numactl', '-N', str(self.__config['JOB_NUMA'])]
> 
>         fio_path = join(self.__config.get('FIO_PATH', ''),
> ```

self.__fio_path

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1417)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72, @haichangsi, and @osalyk)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 219 at r2](https://reviewable.io/reviews/pmem/rpma/1417#-Mr1ZwEF2UONHrTZZJ-B:-Mr1a8Xi4Jr53YfgH7IT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/90d59f662e8870e3cd077c829051bef3549e3557/tools/perf/lib/benchmark/runner/fio.py#L219)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

self.__fio_path
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1417)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 203 at r3](https://reviewable.io/reviews/pmem/rpma/1417#-Mr1cVbi7BTiCo0z-zgq:-Mr1cVbi7BTiCo0z-zgr:b-35j7dh) ([raw file](https://github.com/pmem/rpma/blob/484bab462ec97ebd07bbf2df6e8320ef89253e5b/tools/perf/lib/benchmark/runner/fio.py#L203)):*
> ```Python
>         """run the client (locally) and wait till the end of execution"""
>         short_runtime = self.__config.get('SHORT_RUNTIME', False)
>         c_time = self.__TIME['short' if short_runtime else 'full']
> ```

duration (?)



_Code quote:_
```Python
 c_time
```
___
*[tools/perf/lib/benchmark/runner/fio.py, line 220 at r3](https://reviewable.io/reviews/pmem/rpma/1417#-Mr1dPZCBd93d-c5Nxd7:-Mr1dPZD3goTBaDKhZf2:b-96qooe) ([raw file](https://github.com/pmem/rpma/blob/484bab462ec97ebd07bbf2df6e8320ef89253e5b/tools/perf/lib/benchmark/runner/fio.py#L220)):*
> ```Python
>             args = ['numactl', '-N', str(self.__config['JOB_NUMA'])]
> 
>         persist_mode = self.__benchmark.oneseries['tool_mode']
> ```

persist_mode = self.__tool_mode



_Code quote:_
```Python
persist_mode = self.__benchmark.oneseries['tool_mode']
```
___
*[tools/perf/lib/benchmark/runner/fio.py, line 221 at r3](https://reviewable.io/reviews/pmem/rpma/1417#-Mr1dp4UAKvW5bJNfSEO:-Mr1dp4UAKvW5bJNfSEP:b-1l8v1x) ([raw file](https://github.com/pmem/rpma/blob/484bab462ec97ebd07bbf2df6e8320ef89253e5b/tools/perf/lib/benchmark/runner/fio.py#L221)):*
> ```Python
> 
>         persist_mode = self.__benchmark.oneseries['tool_mode']
>         job_file = './fio_jobs/librpma_{}-client.fio'.format(persist_mode)
> ```

shall this be moved to __init__?



_Code quote:_
```Python
job_file
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1417)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau and @osalyk)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1417)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 203 at r3](https://reviewable.io/reviews/pmem/rpma/1417#-Mr1cVbi7BTiCo0z-zgq:-Mr1f4sZ92S4EskDFix4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/484bab462ec97ebd07bbf2df6e8320ef89253e5b/tools/perf/lib/benchmark/runner/fio.py#L203)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

duration (?)
</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/runner/fio.py, line 220 at r3](https://reviewable.io/reviews/pmem/rpma/1417#-Mr1dPZCBd93d-c5Nxd7:-Mr1lUdQ8OAFvvlzvzQt:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/484bab462ec97ebd07bbf2df6e8320ef89253e5b/tools/perf/lib/benchmark/runner/fio.py#L220)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

persist_mode = self.__tool_mode
</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/runner/fio.py, line 221 at r3](https://reviewable.io/reviews/pmem/rpma/1417#-Mr1dp4UAKvW5bJNfSEO:-Mr1oELw2HAtANol7GoP:baifumr) ([raw file](https://github.com/pmem/rpma/blob/484bab462ec97ebd07bbf2df6e8320ef89253e5b/tools/perf/lib/benchmark/runner/fio.py#L221)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

shall this be moved to __init__?
</blockquote></details>

It is different for client and server, so I think it is not needed.

**Review by osalyk — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1417)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @osalyk)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1417)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1417#-Mr1sd0a03F69ZjvZ2UJ:-Mr1sd0a03F69ZjvZ2UK:b-sis9k9) (no related file):*
Shall all const i.e. __CPU_LOAD_RANGE be placed together?

---

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1417#-:-Mr1tPJi9YIln0z9AIC5:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau and @osalyk)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1417)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1417#-Mr1sd0a03F69ZjvZ2UJ:-Mr1uykZ2TpMGllfsHQQ:b-v24lxz) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Shall all const i.e. __CPU_LOAD_RANGE be placed together?
</blockquote></details>

in separate PR

---

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1417#-:-Mr1vAhH-HlS9KMJrcG5:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Pull request merged**
