### PR TITLE
doc: librpma.7: Client Operation

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/489)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/489)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 65 at r1](https://reviewable.io/reviews/pmem/rpma/489#-MIT6laND0FBGc5lxWq8:-MIT6laND0FBGc5lxWq9:b-7r1dmw) ([raw file](https://github.com/pmem/rpma/blob/b0089813472a7db0a22093cb0302ded5ffdf1ff4/src/include/librpma.h#L65)):*
> ```objc
>  * - rpma_conn_req_connect - initiate connecting the connection request
>  * - rpma_conn_next_event - wait for RPMA_CONN_ESTABLISHED event
>  * - Perform Remote Memory Access and/or Messaging over connection.
> ```

The client to close a connection has to perform the following steps:
___
*[src/include/librpma.h, line 1301 at r1](https://reviewable.io/reviews/pmem/rpma/489#-MIT74dB2O4Q8IJGV_dG:-MIT74dB2O4Q8IJGV_dH:b9fdxbr) ([raw file](https://github.com/pmem/rpma/blob/b0089813472a7db0a22093cb0302ded5ffdf1ff4/src/include/librpma.h#L1301)):*
> ```
>  initiate connecting the connection request
> ```
initiate the connection request
___
*[src/include/librpma.h, line 1315 at r1](https://reviewable.io/reviews/pmem/rpma/489#-MIT7BjR8jG__hp1Ye9L:-MIT7BjR8jG__hp1Ye9M:b-xs87gd) ([raw file](https://github.com/pmem/rpma/blob/b0089813472a7db0a22093cb0302ded5ffdf1ff4/src/include/librpma.h#L1315)):*
> ```
> initiate connecting the connection requests
> ```
initiate the connection requests

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/489)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 63 at r1](https://reviewable.io/reviews/pmem/rpma/489#-MIT7PM7DMLHKS-29gwv:-MIT7PM7DMLHKS-29gww:b-qxyvex) ([raw file](https://github.com/pmem/rpma/blob/b0089813472a7db0a22093cb0302ded5ffdf1ff4/src/include/librpma.h#L63)):*
> ```
> initiate connecting the connection request
> ```
initiate the connection established procedure/sequence

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/489)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @grom72)

___
*[src/include/librpma.h, line 63 at r1](https://reviewable.io/reviews/pmem/rpma/489#-MIT7PM7DMLHKS-29gwv:-MITDeRz8ftb-auPks_v:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b0089813472a7db0a22093cb0302ded5ffdf1ff4/src/include/librpma.h#L63)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> initiate connecting the connection request
> ```
initiate the connection established procedure/sequence
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 65 at r1](https://reviewable.io/reviews/pmem/rpma/489#-MIT6laND0FBGc5lxWq8:-MITBjOjBAyhr2ZfcHxW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b0089813472a7db0a22093cb0302ded5ffdf1ff4/src/include/librpma.h#L65)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

The client to close a connection has to perform the following steps:
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1301 at r1](https://reviewable.io/reviews/pmem/rpma/489#-MIT74dB2O4Q8IJGV_dG:-MITDpAFCkt-RO-wyAeH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b0089813472a7db0a22093cb0302ded5ffdf1ff4/src/include/librpma.h#L1301)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
>  initiate connecting the connection request
> ```
initiate the connection request
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1315 at r1](https://reviewable.io/reviews/pmem/rpma/489#-MIT7BjR8jG__hp1Ye9L:-MITDuCR-vH2GV8odwby:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b0089813472a7db0a22093cb0302ded5ffdf1ff4/src/include/librpma.h#L1315)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> initiate connecting the connection requests
> ```
initiate the connection requests
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/489)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/489#-:-MITErxACshNAZ2y0DZS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/489)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[src/include/librpma.h, line 53 at r3](https://reviewable.io/reviews/pmem/rpma/489#-MITGMLm4Rk929gnAtEl:-MITGMLm4Rk929gnAtEm:b-5cg1pn) ([raw file](https://github.com/pmem/rpma/blob/b89e84a912c5c1ce976295761d8c6a84e4a285b9/src/include/librpma.h#L53)):*
> ```objc
>  *
>  * CLIENT OPERATION
>  * A client is an active side of the process of establishing a connection.
> ```

an empty line is missing here
___
*[src/include/librpma.h, line 53 at r3](https://reviewable.io/reviews/pmem/rpma/489#-MITGU906hLh3CQA1dqU:-MITGU9107-N2s8nl8RS:b-rqtk3n) ([raw file](https://github.com/pmem/rpma/blob/b89e84a912c5c1ce976295761d8c6a84e4a285b9/src/include/librpma.h#L53)):*
> ```
> an active side
> ```

the active side
___
*[src/include/librpma.h, line 54 at r3](https://reviewable.io/reviews/pmem/rpma/489#-MITGozfDuC9-g8X380l:-MITGozfDuC9-g8X380m:bestmn6) ([raw file](https://github.com/pmem/rpma/blob/b89e84a912c5c1ce976295761d8c6a84e4a285b9/src/include/librpma.h#L54)):*
> ```
>  * The process after creating a connection request object is common for both
>  * sides.
> ```

```
 * This process is common for both sides after creating a connection request object.
```

Is that what you mean?

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/489)* status: all files reviewed, 9 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 60 at r3](https://reviewable.io/reviews/pmem/rpma/489#-MITP_wC9mUJdO7Som0G:-MITP_wDDwOmIviY1w3-:bacjlk0) ([raw file](https://github.com/pmem/rpma/blob/b89e84a912c5c1ce976295761d8c6a84e4a285b9/src/include/librpma.h#L60)):*
> ```
> The client to establish
> ```

`The client in order to establish`
___
*[src/include/librpma.h, line 64 at r3](https://reviewable.io/reviews/pmem/rpma/489#-MITPlDREqryfbs1phP_:-MITPlDREqryfbs1phPa:b-544rbe) ([raw file](https://github.com/pmem/rpma/blob/b89e84a912c5c1ce976295761d8c6a84e4a285b9/src/include/librpma.h#L64)):*
> ```
> RPMA_CONN_ESTABLISHED event
> ```

`the RPMA_CONN_ESTABLISHED event`
___
*[src/include/librpma.h, line 69 at r3](https://reviewable.io/reviews/pmem/rpma/489#-MITPqX-3NuC2P_7NDlK:-MITPqX-3NuC2P_7NDlL:b-r1mvu4) ([raw file](https://github.com/pmem/rpma/blob/b89e84a912c5c1ce976295761d8c6a84e4a285b9/src/include/librpma.h#L69)):*
> ```
> The client to close
> ```

.
___
*[src/include/librpma.h, line 72 at r3](https://reviewable.io/reviews/pmem/rpma/489#-MITPtHBCKyTgHSQ-oCa:-MITPtHBCKyTgHSQ-oCb:b-uvoc3g) ([raw file](https://github.com/pmem/rpma/blob/b89e84a912c5c1ce976295761d8c6a84e4a285b9/src/include/librpma.h#L72)):*
> ```
> or RPMA_CONN_CLOSED event
> ```

.
___
*[src/include/librpma.h, line 1320 at r3](https://reviewable.io/reviews/pmem/rpma/489#-MITPz2sCsie1zNSi0VO:-MITPz2sCsie1zNSi0VP:bmbrd6i) ([raw file](https://github.com/pmem/rpma/blob/b89e84a912c5c1ce976295761d8c6a84e4a285b9/src/include/librpma.h#L1320)):*
> ```
> initiate
> ```

initiates
___
*[src/include/librpma.h, line 1322 at r3](https://reviewable.io/reviews/pmem/rpma/489#-MITQ6Cb-AM_H3c89sGd:-MITQ6Cb-AM_H3c89sGe:b-544rbe) ([raw file](https://github.com/pmem/rpma/blob/b89e84a912c5c1ce976295761d8c6a84e4a285b9/src/include/librpma.h#L1322)):*
> ```
> RPMA_CONN_ESTABLISHED event
> ```

`the RPMA_CONN_ESTABLISHED event`

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/489)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @ldorau)

___
*[src/include/librpma.h, line 53 at r3](https://reviewable.io/reviews/pmem/rpma/489#-MITGMLm4Rk929gnAtEl:-MITPf4t9b2alhQJ7WQq:buxiy8p) ([raw file](https://github.com/pmem/rpma/blob/b89e84a912c5c1ce976295761d8c6a84e4a285b9/src/include/librpma.h#L53)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

an empty line is missing here
</blockquote></details>

It seems after sections in all other manpages we do not have an empty line here. I think we can align.
___
*[src/include/librpma.h, line 53 at r3](https://reviewable.io/reviews/pmem/rpma/489#-MITGU906hLh3CQA1dqU:-MITQhK5DzcnAlCyXUP1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b89e84a912c5c1ce976295761d8c6a84e4a285b9/src/include/librpma.h#L53)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> an active side
> ```

the active side
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 54 at r3](https://reviewable.io/reviews/pmem/rpma/489#-MITGozfDuC9-g8X380l:-MITQr066ZY5sClGJJIN:b-rc4s4u) ([raw file](https://github.com/pmem/rpma/blob/b89e84a912c5c1ce976295761d8c6a84e4a285b9/src/include/librpma.h#L54)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  * The process after creating a connection request object is common for both
>  * sides.
> ```

```
 * This process is common for both sides after creating a connection request object.
```

Is that what you mean?
</blockquote></details>

Yes, it is. But I think this sentence is not needed here. Removed.
___
*[src/include/librpma.h, line 60 at r3](https://reviewable.io/reviews/pmem/rpma/489#-MITP_wC9mUJdO7Som0G:-MITTXs7DSPi1YR_1BLE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b89e84a912c5c1ce976295761d8c6a84e4a285b9/src/include/librpma.h#L60)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> The client to establish
> ```

`The client in order to establish`
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 64 at r3](https://reviewable.io/reviews/pmem/rpma/489#-MITPlDREqryfbs1phP_:-MITTdgE4gHig_sLi3tj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b89e84a912c5c1ce976295761d8c6a84e4a285b9/src/include/librpma.h#L64)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> RPMA_CONN_ESTABLISHED event
> ```

`the RPMA_CONN_ESTABLISHED event`
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 69 at r3](https://reviewable.io/reviews/pmem/rpma/489#-MITPqX-3NuC2P_7NDlK:-MITTewH3c8xzTXQIiUn:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b89e84a912c5c1ce976295761d8c6a84e4a285b9/src/include/librpma.h#L69)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> The client to close
> ```

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 72 at r3](https://reviewable.io/reviews/pmem/rpma/489#-MITPtHBCKyTgHSQ-oCa:-MITTgNZ369kvE4axyBa:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b89e84a912c5c1ce976295761d8c6a84e4a285b9/src/include/librpma.h#L72)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> or RPMA_CONN_CLOSED event
> ```

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1320 at r3](https://reviewable.io/reviews/pmem/rpma/489#-MITPz2sCsie1zNSi0VO:-MITTrtY3mkUSnZifBFp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b89e84a912c5c1ce976295761d8c6a84e4a285b9/src/include/librpma.h#L1320)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> initiate
> ```

initiates
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1322 at r3](https://reviewable.io/reviews/pmem/rpma/489#-MITQ6Cb-AM_H3c89sGd:-MITTu9v51Ya7rKRkib7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b89e84a912c5c1ce976295761d8c6a84e4a285b9/src/include/librpma.h#L1322)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> RPMA_CONN_ESTABLISHED event
> ```

`the RPMA_CONN_ESTABLISHED event`
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/489)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 60 at r3](https://reviewable.io/reviews/pmem/rpma/489#-MITP_wC9mUJdO7Som0G:-MITUxSnAzSTHQydPHzZ:bqm89jv) ([raw file](https://github.com/pmem/rpma/blob/b89e84a912c5c1ce976295761d8c6a84e4a285b9/src/include/librpma.h#L60)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

One more thing - please add commas:

`The client, in order to establish a connection, has to perform the following`

or:

`In order to establish a connection the client has to perform the following`
___
*[src/include/librpma.h, line 69 at r3](https://reviewable.io/reviews/pmem/rpma/489#-MITPqX-3NuC2P_7NDlK:-MITV7LWEV81hrUVb4iz:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/b89e84a912c5c1ce976295761d8c6a84e4a285b9/src/include/librpma.h#L69)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/489#-:-MITWaPx-4OrZL-RTgV7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/489)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[src/include/librpma.h, line 1433 at r5](https://reviewable.io/reviews/pmem/rpma/489#-MITY-k36c0pwGJfFfbE:-MITY-k4DvMp83SQlW8R:b-q2tgtr) ([raw file](https://github.com/pmem/rpma/blob/4087c48cd3bbbf5595910e2f4508f3c4de7b7443/src/include/librpma.h#L1433)):*
> ```
> is notified by
> ```

... is **signalled** by ...


(the other process is being **notified** by this even - 'notify' should be used for the other side of the connection)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/489)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/include/librpma.h, line 1433 at r5](https://reviewable.io/reviews/pmem/rpma/489#-MITY-k36c0pwGJfFfbE:-MITa3yR4snd_hbc2Yk9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4087c48cd3bbbf5595910e2f4508f3c4de7b7443/src/include/librpma.h#L1433)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> is notified by
> ```

... is **signalled** by ...


(the other process is being **notified** by this even - 'notify' should be used for the other side of the connection)
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/489#-:-MITaiU-6Ojzxk0MKzml:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
