### PR TITLE
tools: intrudce appendices generation

### PR DESCRIPTION
**Pull request by janekmi**
Includes:
- creating a general part of rendering a document
- making header a document specific
- implement the appendices structure for the generator
- a simple all-in-one appendices content structure

Requires:
- [x] #826
- [x] #832
- [x] #833

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/835)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/835)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 7 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/835#-:-MSc9PIz4ryLhCXWQ7tb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/835#-:-MScPFrg9IUuTWaZ_6i4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/835)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
