### PR TITLE
doc: librpma.7: queues, performance and resource use

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/508)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/508)* status: 0 of 1 files reviewed, all discussions resolved

___
*[src/include/librpma.h, line 151 at r1](https://reviewable.io/reviews/pmem/rpma/508#-MIUkFld-id14rP9DrFS:-MIUkFld-id14rP9DrFT:b-8o11fo) ([raw file](https://github.com/pmem/rpma/blob/77dae405fdd0d0d620a5c81e1ef4f988f88a37df/src/include/librpma.h#L151)):*
> ```objc
>  * - rpma_conn_get_completion_fd() - XXX
>  *
>  * .SH QUEUES, PERFORMANCE AND RESOURCE USE
> ```

For an unknown reason, our documentation generation toolchain does not recognize this as a header. So I had to force him...

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/508)* status: 0 of 1 files reviewed, all discussions resolved

___
*[src/include/librpma.h, line 151 at r1](https://reviewable.io/reviews/pmem/rpma/508#-MIUkFld-id14rP9DrFS:-MIVNAYA8KkmVNM0_nBD:b-7s4tye) ([raw file](https://github.com/pmem/rpma/blob/77dae405fdd0d0d620a5c81e1ef4f988f88a37df/src/include/librpma.h#L151)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

For an unknown reason, our documentation generation toolchain does not recognize this as a header. So I had to force him...
</blockquote></details>

coma?

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/508)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[src/include/librpma.h, line 187 at r1](https://reviewable.io/reviews/pmem/rpma/508#-MIVOSfA4MfNPdecEgn0:-MIVOSfA4MfNPdecEgn1:ba6fp5v) ([raw file](https://github.com/pmem/rpma/blob/77dae405fdd0d0d620a5c81e1ef4f988f88a37df/src/include/librpma.h#L187)):*
<details><summary><i alt="summary">Quoted 21 lines of code…</i></summary>

> ```
>  * .B Remote Memory Access
>  * operations and
>  * .B Messaging
>  * operations can consume
>  * .B CQ
>  * space.
>  * - send queue
>  * .B (SQ)
>  * where all
>  * .B Remote Memory Access
>  * operations and rpma_send() operations are placed before they are executed by
>  * the RDMA-capable network interface.
>  * - receive queue
>  * .B (RQ)
>  * where rpma_recv() entries are placed before they are consumed by
>  * the rpma_send() coming from another side of the connection.
>  *
>  * You must assume
>  * .B SQ
>  * and
>  * .B RQ
> ```
</details>


It is unreadable :-(

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/508)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[src/include/librpma.h, line 151 at r1](https://reviewable.io/reviews/pmem/rpma/508#-MIUkFld-id14rP9DrFS:-MIVPC6HE3V1ZkL7gSn-:b-257lek) ([raw file](https://github.com/pmem/rpma/blob/77dae405fdd0d0d620a5c81e1ef4f988f88a37df/src/include/librpma.h#L151)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

coma?
</blockquote></details>

It is unreadable :-(

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/508)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[src/include/librpma.h, line 151 at r1](https://reviewable.io/reviews/pmem/rpma/508#-MIUkFld-id14rP9DrFS:-MIVR_UM0OqqmqlL--Hl:b-bszndw) ([raw file](https://github.com/pmem/rpma/blob/77dae405fdd0d0d620a5c81e1ef4f988f88a37df/src/include/librpma.h#L151)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It is unreadable :-(
</blockquote></details>

RDMA PROVIDER CONFIGURATION

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/508)* status: all files reviewed, 14 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[src/include/librpma.h, line 158 at r1](https://reviewable.io/reviews/pmem/rpma/508#-MIVPsmG--qjS2lpBd5v:-MIVPsmG--qjS2lpBd5w:bsmdnxa) ([raw file](https://github.com/pmem/rpma/blob/77dae405fdd0d0d620a5c81e1ef4f988f88a37df/src/include/librpma.h#L158)):*
> ```
> consumes
> ```

consume
___
*[src/include/librpma.h, line 158 at r1](https://reviewable.io/reviews/pmem/rpma/508#-MIVQ1cy7NP65eTxMQSq:-MIVQ1czDENdrorL-xpr:bsgq16t) ([raw file](https://github.com/pmem/rpma/blob/77dae405fdd0d0d620a5c81e1ef4f988f88a37df/src/include/librpma.h#L158)):*
> ```
> the RDMA-capable network interface
> ```

an RDMA-capable network interface (RNIC?)
___
*[src/include/librpma.h, line 165 at r1](https://reviewable.io/reviews/pmem/rpma/508#-MIVQL_251qvdZi_Gz6s:-MIVQL_251qvdZi_Gz6t:b-htazb) ([raw file](https://github.com/pmem/rpma/blob/77dae405fdd0d0d620a5c81e1ef4f988f88a37df/src/include/librpma.h#L165)):*
> ```
> have been required
> ```

`was required` ('when' implies Past Simple tense)
___
*[src/include/librpma.h, line 165 at r1](https://reviewable.io/reviews/pmem/rpma/508#-MIVQdd0-y9IPYR7jxPp:-MIVQdd0-y9IPYR7jxPq:btjtkkr) ([raw file](https://github.com/pmem/rpma/blob/77dae405fdd0d0d620a5c81e1ef4f988f88a37df/src/include/librpma.h#L165)):*
> ```
> the user
> ```

a user
___
*[src/include/librpma.h, line 178 at r1](https://reviewable.io/reviews/pmem/rpma/508#-MIVQulwAsm4X0UD8cJ3:-MIVQulwAsm4X0UD8cJ4:b-pxr8dj) ([raw file](https://github.com/pmem/rpma/blob/77dae405fdd0d0d620a5c81e1ef4f988f88a37df/src/include/librpma.h#L178)):*
> ```
> the RDMA-capable 
> ```

an RDMA-capable ...
___
*[src/include/librpma.h, line 191 at r1](https://reviewable.io/reviews/pmem/rpma/508#-MIVRNTkCf87kVT5CsZi:-MIVRNTkCf87kVT5CsZj:bmllluf) ([raw file](https://github.com/pmem/rpma/blob/77dae405fdd0d0d620a5c81e1ef4f988f88a37df/src/include/librpma.h#L191)):*
> ```
> which you know have been scheduled later
> ```

`which was scheduled later` ('later' implies Past Simple tense)
___
*[src/include/librpma.h, line 194 at r1](https://reviewable.io/reviews/pmem/rpma/508#-MIVRkjV-zDOVrEoguOT:-MIVRkjV-zDOVrEoguOU:b-u36b0h) ([raw file](https://github.com/pmem/rpma/blob/77dae405fdd0d0d620a5c81e1ef4f988f88a37df/src/include/librpma.h#L194)):*
> ```
> You must also know that
> ```

`You also must be aware that`
___
*[src/include/librpma.h, line 195 at r1](https://reviewable.io/reviews/pmem/rpma/508#-MIVS0up4kaK5P18OIaq:-MIVS0up4kaK5P18OIar:ba4cd2z) ([raw file](https://github.com/pmem/rpma/blob/77dae405fdd0d0d620a5c81e1ef4f988f88a37df/src/include/librpma.h#L195)):*
> ```
> it is unable to 
> ```

it is impossible to 
___
*[src/include/librpma.h, line 196 at r1](https://reviewable.io/reviews/pmem/rpma/508#-MIVSBjjDGX6W15tfVYO:-MIVSBjjDGX6W15tfVYP:bwm84m7) ([raw file](https://github.com/pmem/rpma/blob/77dae405fdd0d0d620a5c81e1ef4f988f88a37df/src/include/librpma.h#L196)):*
> ```
> won't 
> ```

`will not` (we should use the formal style)
___
*[src/include/librpma.h, line 198 at r1](https://reviewable.io/reviews/pmem/rpma/508#-MIVSSRB-FQqdktmmlvK:-MIVSSRB-FQqdktmmlvL:b-42bo4l) ([raw file](https://github.com/pmem/rpma/blob/77dae405fdd0d0d620a5c81e1ef4f988f88a37df/src/include/librpma.h#L198)):*
> ```
> will suffer
> ```

will be degraded
___
*[src/include/librpma.h, line 201 at r1](https://reviewable.io/reviews/pmem/rpma/508#-MIVSoE1DSJ9RTCOhQoo:-MIVSoE1DSJ9RTCOhQop:b-2lzclx) ([raw file](https://github.com/pmem/rpma/blob/77dae405fdd0d0d620a5c81e1ef4f988f88a37df/src/include/librpma.h#L201)):*
> ```
> have
> ```

has
___
*[src/include/librpma.h, line 213 at r1](https://reviewable.io/reviews/pmem/rpma/508#-MIVSzw8E9uXPh_85U8I:-MIVSzw8E9uXPh_85U8J:b-eusjg7) ([raw file](https://github.com/pmem/rpma/blob/77dae405fdd0d0d620a5c81e1ef4f988f88a37df/src/include/librpma.h#L213)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
>  * - rpma_conn_cfg_set_cq_size() - set
>  * .B CQ
>  * length
>  * - rpma_conn_cfg_set_sq_size() - set
>  * .B SQ
>  * length
>  * - rpma_conn_cfg_set_rq_size() - set
>  * .B RQ
>  * length
> ```
</details>


- set length of CQ/SQ/RQ

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/508)* status: all files reviewed, 13 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 151 at r1](https://reviewable.io/reviews/pmem/rpma/508#-MIUkFld-id14rP9DrFS:-MIVZndHArZi38_RyQcy:bd09pzo) ([raw file](https://github.com/pmem/rpma/blob/77dae405fdd0d0d620a5c81e1ef4f988f88a37df/src/include/librpma.h#L151)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

RDMA PROVIDER CONFIGURATION
</blockquote></details>

Does it have to have all these formatting tags ? :-(
___
*[src/include/librpma.h, line 187 at r1](https://reviewable.io/reviews/pmem/rpma/508#-MIVOSfA4MfNPdecEgn0:-MIV_86kAndccKbDr6MN:bd09pzo) ([raw file](https://github.com/pmem/rpma/blob/77dae405fdd0d0d620a5c81e1ef4f988f88a37df/src/include/librpma.h#L187)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  * .B Remote Memory Access
>  * operations and
>  * .B Messaging
>  * operations can consume
>  * .B CQ
>  * space.
>  * - send queue
>  * .B (SQ)
>  * where all
>  * .B Remote Memory Access
>  * operations and rpma_send() operations are placed before they are executed by
>  * the RDMA-capable network interface.
>  * - receive queue
>  * .B (RQ)
>  * where rpma_recv() entries are placed before they are consumed by
>  * the rpma_send() coming from another side of the connection.
>  *
>  * You must assume
>  * .B SQ
>  * and
>  * .B RQ
> ```

It is unreadable :-(
</blockquote></details>

Does it have to have all these formatting tags ? :-(

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/508)* status: 0 of 1 files reviewed, 12 unresolved discussions (waiting on @ldorau)

___
*[src/include/librpma.h, line 151 at r1](https://reviewable.io/reviews/pmem/rpma/508#-MIUkFld-id14rP9DrFS:-MIY8kgi-YNYdtA7-rmB:b-h33w7r) ([raw file](https://github.com/pmem/rpma/blob/77dae405fdd0d0d620a5c81e1ef4f988f88a37df/src/include/librpma.h#L151)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Does it have to have all these formatting tags ? :-(
</blockquote></details>

Sadly yes.
___
*[src/include/librpma.h, line 158 at r1](https://reviewable.io/reviews/pmem/rpma/508#-MIVPsmG--qjS2lpBd5v:-MIY933zBhFldZmn2QyW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/77dae405fdd0d0d620a5c81e1ef4f988f88a37df/src/include/librpma.h#L158)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> consumes
> ```

consume
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 158 at r1](https://reviewable.io/reviews/pmem/rpma/508#-MIVQ1cy7NP65eTxMQSq:-MIY9AWR60bqbA4mhEwm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/77dae405fdd0d0d620a5c81e1ef4f988f88a37df/src/include/librpma.h#L158)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> the RDMA-capable network interface
> ```

an RDMA-capable network interface (RNIC?)
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 165 at r1](https://reviewable.io/reviews/pmem/rpma/508#-MIVQL_251qvdZi_Gz6s:-MIY9SHsEoIBULrCyrlX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/77dae405fdd0d0d620a5c81e1ef4f988f88a37df/src/include/librpma.h#L165)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> have been required
> ```

`was required` ('when' implies Past Simple tense)
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 165 at r1](https://reviewable.io/reviews/pmem/rpma/508#-MIVQdd0-y9IPYR7jxPp:-MIY9WSVB_53uJ1HFLVu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/77dae405fdd0d0d620a5c81e1ef4f988f88a37df/src/include/librpma.h#L165)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> the user
> ```

a user
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 178 at r1](https://reviewable.io/reviews/pmem/rpma/508#-MIVQulwAsm4X0UD8cJ3:-MIY9c3o9FPm2a9clnTT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/77dae405fdd0d0d620a5c81e1ef4f988f88a37df/src/include/librpma.h#L178)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> the RDMA-capable 
> ```

an RDMA-capable ...
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 187 at r1](https://reviewable.io/reviews/pmem/rpma/508#-MIVOSfA4MfNPdecEgn0:-MIY9gfP5liltwcBaCQo:bn5le1x) ([raw file](https://github.com/pmem/rpma/blob/77dae405fdd0d0d620a5c81e1ef4f988f88a37df/src/include/librpma.h#L187)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Does it have to have all these formatting tags ? :-(
</blockquote></details>

Yes. Sorry.
___
*[src/include/librpma.h, line 191 at r1](https://reviewable.io/reviews/pmem/rpma/508#-MIVRNTkCf87kVT5CsZi:-MIY9s-92DsMK8FwXJHk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/77dae405fdd0d0d620a5c81e1ef4f988f88a37df/src/include/librpma.h#L191)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> which you know have been scheduled later
> ```

`which was scheduled later` ('later' implies Past Simple tense)
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 194 at r1](https://reviewable.io/reviews/pmem/rpma/508#-MIVRkjV-zDOVrEoguOT:-MIYA92OEtuzzI8gPvPO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/77dae405fdd0d0d620a5c81e1ef4f988f88a37df/src/include/librpma.h#L194)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> You must also know that
> ```

`You also must be aware that`
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 195 at r1](https://reviewable.io/reviews/pmem/rpma/508#-MIVS0up4kaK5P18OIaq:-MIYAHnC-KMgS9buM7gh:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/77dae405fdd0d0d620a5c81e1ef4f988f88a37df/src/include/librpma.h#L195)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> it is unable to 
> ```

it is impossible to 
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 196 at r1](https://reviewable.io/reviews/pmem/rpma/508#-MIVSBjjDGX6W15tfVYO:-MIYAMJR8vnYBGNu8CI_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/77dae405fdd0d0d620a5c81e1ef4f988f88a37df/src/include/librpma.h#L196)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> won't 
> ```

`will not` (we should use the formal style)
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 198 at r1](https://reviewable.io/reviews/pmem/rpma/508#-MIVSSRB-FQqdktmmlvK:-MIYAPxV1aNVHyTg5CR7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/77dae405fdd0d0d620a5c81e1ef4f988f88a37df/src/include/librpma.h#L198)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> will suffer
> ```

will be degraded
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 201 at r1](https://reviewable.io/reviews/pmem/rpma/508#-MIVSoE1DSJ9RTCOhQoo:-MIYASiVC-n8zdTTKOHH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/77dae405fdd0d0d620a5c81e1ef4f988f88a37df/src/include/librpma.h#L201)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> have
> ```

has
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 213 at r1](https://reviewable.io/reviews/pmem/rpma/508#-MIVSzw8E9uXPh_85U8I:-MIYAdoI2whizCx4CJwa:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/77dae405fdd0d0d620a5c81e1ef4f988f88a37df/src/include/librpma.h#L213)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  * - rpma_conn_cfg_set_cq_size() - set
>  * .B CQ
>  * length
>  * - rpma_conn_cfg_set_sq_size() - set
>  * .B SQ
>  * length
>  * - rpma_conn_cfg_set_rq_size() - set
>  * .B RQ
>  * length
> ```

- set length of CQ/SQ/RQ
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/508)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[src/include/librpma.h, line 265 at r2](https://reviewable.io/reviews/pmem/rpma/508#-MIYD6Xs7ouVG-cOyXrl:-MIYD6Xs7ouVG-cOyXrm:b-sfbfg7) ([raw file](https://github.com/pmem/rpma/blob/e94f43c8d9d35c5de2645f8a858f89e49b87c12b/src/include/librpma.h#L265)):*
> ```
> RNIC resources
> ```

RNIC's resources

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/508#-:-MIYDTcsBdJDPk_Ht24U:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/508#-:-MIYbaC1-bx0jvzvAjuW:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/508)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/include/librpma.h, line 265 at r2](https://reviewable.io/reviews/pmem/rpma/508#-MIYD6Xs7ouVG-cOyXrl:-MIYvDzbE-xKft9LmCQE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e94f43c8d9d35c5de2645f8a858f89e49b87c12b/src/include/librpma.h#L265)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> RNIC resources
> ```

RNIC's resources
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/508)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/508#-:-MIYw87y-IpTifM1CgaA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
