### PR TITLE
tools: rpma_fio_bench.sh benchmarks reads and writes

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/668)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/668)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[tools/fio_jobs/librpma-client-write-bw.fio, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/668#-MOaMpy_BQ3hiTU1kSGL:-MOaMpy_BQ3hiTU1kSGM:b-46y3xh) ([raw file](https://github.com/pmem/rpma/blob/59c4d81bfc8c9fabcc98005ae2bdabdf941d2744/tools/fio_jobs/librpma-client-write-bw.fio#L20)):*
> ```
> iodepth=${iodepth}
> iomem_align=$pagesize
> readwrite=write
> ```

Is it any different compared to what we have for read-bw?
It seems the only difference is this one line.
___
*[tools/fio_jobs/librpma-client-write-lat.fio, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/668#-MOaN9V190xXVIzLfLf1:-MOaN9V190xXVIzLfLf2:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/59c4d81bfc8c9fabcc98005ae2bdabdf941d2744/tools/fio_jobs/librpma-client-write-lat.fio#L20)):*
> ```
> sync=1
> iomem_align=$pagesize
> readwrite=write
> ```

.
___
*[tools/rpma_fio_bench.sh, line 100 at r1](https://reviewable.io/reviews/pmem/rpma/668#-MOaKbMREd7WSH-m5DwH:-MOaKbMREd7WSH-m5DwI:b-eb01wa) ([raw file](https://github.com/pmem/rpma/blob/59c4d81bfc8c9fabcc98005ae2bdabdf941d2744/tools/rpma_fio_bench.sh#L100)):*
> ```Shell
> 
> NAME=rpma_fio_${OP}_${MODE}-${TIMESTAMP}
> DIR=/dev/shm
> ```

The name conveys no meaning. Consider e.g. `SHM`?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/668)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tools/fio_jobs/librpma-client-write-bw.fio, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/668#-MOaMpy_BQ3hiTU1kSGL:-MOaUM706ZxlIJ2pBZWu:bz1d9zj) ([raw file](https://github.com/pmem/rpma/blob/59c4d81bfc8c9fabcc98005ae2bdabdf941d2744/tools/fio_jobs/librpma-client-write-bw.fio#L20)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Is it any different compared to what we have for read-bw?
It seems the only difference is this one line.
</blockquote></details>

Now it is the only difference. but it can change in the future.
___
*[tools/fio_jobs/librpma-client-write-lat.fio, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/668#-MOaN9V190xXVIzLfLf1:-MOaUXUG9Hsmx6avNpTy:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/59c4d81bfc8c9fabcc98005ae2bdabdf941d2744/tools/fio_jobs/librpma-client-write-lat.fio#L20)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

.
___
*[tools/rpma_fio_bench.sh, line 100 at r1](https://reviewable.io/reviews/pmem/rpma/668#-MOaKbMREd7WSH-m5DwH:-MOaUasa20j5qcPoPsqm:b-z5485z) ([raw file](https://github.com/pmem/rpma/blob/59c4d81bfc8c9fabcc98005ae2bdabdf941d2744/tools/rpma_fio_bench.sh#L100)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The name conveys no meaning. Consider e.g. `SHM`?
</blockquote></details>

DIR stands just for any directory. What if we change it to "/tmp"  for example in the future?

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/668#-:-MOaeoP546BPgF-0QkI8:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/668)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/fio_jobs/librpma-client-write-bw.fio, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/668#-MOaMpy_BQ3hiTU1kSGL:-MOaiJBbCthkHbXj7dDY:b69iwxq) ([raw file](https://github.com/pmem/rpma/blob/59c4d81bfc8c9fabcc98005ae2bdabdf941d2744/tools/fio_jobs/librpma-client-write-bw.fio#L20)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Now it is the only difference. but it can change in the future.
</blockquote></details>

Your argument does not sound valid. Using the same argument you may argue we need a separate script for running write benchmarks but in this case, you have merged both read and write.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/668)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/fio_jobs/librpma-client-write-bw.fio, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/668#-MOaMpy_BQ3hiTU1kSGL:-MOamcG-8xWsxjqNhCOj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/59c4d81bfc8c9fabcc98005ae2bdabdf941d2744/tools/fio_jobs/librpma-client-write-bw.fio#L20)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Your argument does not sound valid. Using the same argument you may argue we need a separate script for running write benchmarks but in this case, you have merged both read and write.
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/668)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/fio_jobs/librpma-client-write-lat.fio, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/668#-MOaN9V190xXVIzLfLf1:-MOaoEnM9PiICglPzRC9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/59c4d81bfc8c9fabcc98005ae2bdabdf941d2744/tools/fio_jobs/librpma-client-write-lat.fio#L20)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/668#-:-MOaoeU348msHKWBNEBG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/668#-:-MOb24fMBXJhMqZGriRc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
