### PR TITLE
tools: perf: document lib.report

### PR DESCRIPTION
**Pull request by janekmi**
Requires:

- [x] #1375
- [x] #1379

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1381)

### CODE REVIEW

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1381)* status: 0 of 17 files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1381)* status: 0 of 17 files reviewed, all discussions resolved (waiting on @haichangsi and @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 17 files at r1, 17 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1381)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/lib/report/__init__.py, line 14 at r2](https://reviewable.io/reviews/pmem/rpma/1381#-MpvJN2N3ANpjbMLmM9X:-MpvJN2N3ANpjbMLmM9Y:b-zc11zx) ([raw file](https://github.com/pmem/rpma/blob/cea2cb7b594716778a43e0717712ffca6685a9f1/tools/perf/lib/report/__init__.py#L14)):*
> ```
> This modules combinese
> ```

This module combines
___
*[tools/perf/lib/report/base.py, line 44 at r2](https://reviewable.io/reviews/pmem/rpma/1381#-MpvJhzWCUcn8LNVyXnH:-MpvJhzWCUcn8LNVyXnI:b-78qokb) ([raw file](https://github.com/pmem/rpma/blob/cea2cb7b594716778a43e0717712ffca6685a9f1/tools/perf/lib/report/base.py#L44)):*
> ```
> remainding 
> ```

reminding ?
___
*[tools/perf/lib/report/base.py, line 45 at r2](https://reviewable.io/reviews/pmem/rpma/1381#-MpvJnDFBQa6LmXuJIV3:-MpvJnDFBQa6LmXuJIV4:b-kbb22k) ([raw file](https://github.com/pmem/rpma/blob/cea2cb7b594716778a43e0717712ffca6685a9f1/tools/perf/lib/report/base.py#L45)):*
> ```
> prepare
> ```

prepared ?
___
*[tools/perf/lib/report/base.py, line 206 at r2](https://reviewable.io/reviews/pmem/rpma/1381#-MpvKMPZBttmrBFNq7Bc:-MpvKMPZBttmrBFNq7Bd:b-yryg37) ([raw file](https://github.com/pmem/rpma/blob/cea2cb7b594716778a43e0717712ffca6685a9f1/tools/perf/lib/report/base.py#L206)):*
> ```
> to a file `output`.html file
> ```

to the `output`.html file
___
*[tools/perf/lib/report/utils.py, line 47 at r2](https://reviewable.io/reviews/pmem/rpma/1381#-MpvLb2877FdnO9Rftw6:-MpvLb2877FdnO9Rftw7:b-vux7tl) ([raw file](https://github.com/pmem/rpma/blob/cea2cb7b594716778a43e0717712ffca6685a9f1/tools/perf/lib/report/utils.py#L47)):*
> ```
> containg
> ```

containing ?

**Review by osalyk — COMMENTED** [review]
> Reviewed 1 of 17 files at r1, 2 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1381)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1381)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/lib/report/utils.py, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/1381#-MpvMR9M8UbjYIbe5H4k:-MpvMR9M8UbjYIbe5H4l:bghx996) ([raw file](https://github.com/pmem/rpma/blob/cea2cb7b594716778a43e0717712ffca6685a9f1/tools/perf/lib/report/utils.py#L15)):*
> ```
>  str="\n"
> ```

 str = "\n"

https://github.com/ldorau/rpma/actions/runs/1530792325

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1381)* status: 14 of 18 files reviewed, 6 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[tools/perf/lib/report/__init__.py, line 14 at r2](https://reviewable.io/reviews/pmem/rpma/1381#-MpvJN2N3ANpjbMLmM9X:-MpvS-LS4COAu4wCXt3S:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cea2cb7b594716778a43e0717712ffca6685a9f1/tools/perf/lib/report/__init__.py#L14)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> This modules combinese
> ```

This module combines
</blockquote></details>

Done.
___
*[tools/perf/lib/report/base.py, line 44 at r2](https://reviewable.io/reviews/pmem/rpma/1381#-MpvJhzWCUcn8LNVyXnH:-MpvSGeh2W_RPl_5Iv5o:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cea2cb7b594716778a43e0717712ffca6685a9f1/tools/perf/lib/report/base.py#L44)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> remainding 
> ```

reminding ?
</blockquote></details>

Done.
___
*[tools/perf/lib/report/base.py, line 45 at r2](https://reviewable.io/reviews/pmem/rpma/1381#-MpvJnDFBQa6LmXuJIV3:-MpvSQa2E5zr4GwPBoq2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cea2cb7b594716778a43e0717712ffca6685a9f1/tools/perf/lib/report/base.py#L45)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> prepare
> ```

prepared ?
</blockquote></details>

Done.
___
*[tools/perf/lib/report/base.py, line 206 at r2](https://reviewable.io/reviews/pmem/rpma/1381#-MpvKMPZBttmrBFNq7Bc:-MpvSZBs3--3PJAr0e7P:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cea2cb7b594716778a43e0717712ffca6685a9f1/tools/perf/lib/report/base.py#L206)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> to a file `output`.html file
> ```

to the `output`.html file
</blockquote></details>

Done.
___
*[tools/perf/lib/report/utils.py, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/1381#-MpvMR9M8UbjYIbe5H4k:-MpvSgnL0H7klbr0uNur:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cea2cb7b594716778a43e0717712ffca6685a9f1/tools/perf/lib/report/utils.py#L15)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  str="\n"
> ```

 str = "\n"

https://github.com/ldorau/rpma/actions/runs/1530792325
</blockquote></details>

Done.
___
*[tools/perf/lib/report/utils.py, line 47 at r2](https://reviewable.io/reviews/pmem/rpma/1381#-MpvLb2877FdnO9Rftw6:-MpvSlz7CCDcPD3YSDBe:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cea2cb7b594716778a43e0717712ffca6685a9f1/tools/perf/lib/report/utils.py#L47)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> containg
> ```

containing ?
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1381)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 17 files at r2, 3 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1381#-:-MpvWhY1AEN3w7-j1ucl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1381#-:-MpvY9C20Ib6MRim8plB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
