### PR TITLE
rpma: make rpma_conn_cfg_get_cqe() and rpma_conn_cfg_get_rcqe() void

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1685)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1685)* status: 6 of 7 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1685#-N0AX3hsAXSY0vI3RYKU):*
I think it will be good to extend documentation by saying that it is an internal API and we do not need to return any status code.
___
*[src/conn_cfg.h, line 23 at r1](https://reviewable.io/reviews/pmem/rpma/1685#-N0AaMmN2lZ-qvQ8Fud7:-N0AaMmN2lZ-qvQ8Fud8:b-3sm664) ([raw file](https://github.com/pmem/rpma/blob/428406a390b5031b038e35fde5b161e2cf1a9af5/src/conn_cfg.h#L23)):*
> ```objc
>  * ERRORS
>  * rpma_conn_cfg_get_cqe() cannot fail.
>  */
> ```

 * ASSUMPTIONS
 * - cfg != NULL && cqe != NULL
 */



_Code quote:_
```objc
 */
```
___
*[src/conn_cfg.h, line 29 at r1](https://reviewable.io/reviews/pmem/rpma/1685#-N0AabH03RmKapH9mKFb:-N0AabH03RmKapH9mKFc:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/428406a390b5031b038e35fde5b161e2cf1a9af5/src/conn_cfg.h#L29)):*
> ```objc
>  * ERRORS
>  * rpma_conn_cfg_get_rcqe() cannot fail.
>  */
> ```

.



_Code quote:_
```objc
 */
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1685)* status: 5 of 7 files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1685#-N0AX3hsAXSY0vI3RYKU):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I think it will be good to extend documentation by saying that it is an internal API and we do not need to return any status code.
</blockquote></details>

Done.
___
*[src/conn_cfg.h, line 23 at r1](https://reviewable.io/reviews/pmem/rpma/1685#-N0AaMmN2lZ-qvQ8Fud7:-N0B-7DV5DBM7JqQiu6d:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/428406a390b5031b038e35fde5b161e2cf1a9af5/src/conn_cfg.h#L23)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

 * ASSUMPTIONS
 * - cfg != NULL && cqe != NULL
 */
</blockquote></details>

Done.
___
*[src/conn_cfg.h, line 29 at r1](https://reviewable.io/reviews/pmem/rpma/1685#-N0AabH03RmKapH9mKFb:-N0B-8t86UK0KwzgQpBq:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/428406a390b5031b038e35fde5b161e2cf1a9af5/src/conn_cfg.h#L29)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1685)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1685#-:-N0BHS2D7Q5Nh1l1od_6:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1685)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1685)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[src/conn_cfg.c, line 77 at r3](https://reviewable.io/reviews/pmem/rpma/1685#-N0BXMWx53YHTHMDY7_T:-N0BXMWx53YHTHMDY7_U:byquu61) ([raw file](https://github.com/pmem/rpma/blob/b927901e089144ce3863a881d3a2a466e4ab56a4/src/conn_cfg.c#L77)):*
> ```C
> rpma_conn_cfg_get_cqe(const struct rpma_conn_cfg *cfg, int *cqe)
> {
> 	uint32_t cq_size = 0;
> ```

Do we need this?



_Code quote:_
```C
 = 0
```
___
*[src/conn_cfg.c, line 90 at r3](https://reviewable.io/reviews/pmem/rpma/1685#-N0BXP2CAbOJ53ypUT2p:-N0BXP2CAbOJ53ypUT2q:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/b927901e089144ce3863a881d3a2a466e4ab56a4/src/conn_cfg.c#L90)):*
> ```C
> rpma_conn_cfg_get_rcqe(const struct rpma_conn_cfg *cfg, int *rcqe)
> {
> 	uint32_t rcq_size = 0;
> ```

.



_Code quote:_
```C
 = 0
```

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1685)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1685)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[src/conn_cfg.c, line 77 at r3](https://reviewable.io/reviews/pmem/rpma/1685#-N0BXMWx53YHTHMDY7_T:-N0CdC18-gzidrZssiB0:b8vxlej) ([raw file](https://github.com/pmem/rpma/blob/b927901e089144ce3863a881d3a2a466e4ab56a4/src/conn_cfg.c#L77)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Do we need this?
</blockquote></details>

Yes, valgrind shows "uninitialized" error without it.
___
*[src/conn_cfg.c, line 90 at r3](https://reviewable.io/reviews/pmem/rpma/1685#-N0BXP2CAbOJ53ypUT2p:-N0CdQV8C2p_zeNJtu3a:b8vxlej) ([raw file](https://github.com/pmem/rpma/blob/b927901e089144ce3863a881d3a2a466e4ab56a4/src/conn_cfg.c#L90)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Yes, valgrind shows "uninitialized" error without it.

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1685)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
