### PR TITLE
[WIP] tools: Runner with common run command

### PR DESCRIPTION
**Pull request by grom72**
pre and post command controlled by Runner class

- [x] #1461
- [ ] #1452 
- [x] #1453
- [ ] #1454 
- [ ] #1455 
- [ ] #1456
- [ ] #1469 

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1457)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1457)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by Patryk717 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1457#-:-Ms4Le77BZzgcND4TIki:bdycpsm)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1457)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1457)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @ldorau)

**Comment by ldorau** [comment]
Postponed

**Pull request closed without merging**
