### PR TITLE
tools: add checking xADR parameter for Ice Lake platforms

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1636)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1636)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[tools/perf/CONFIG.JSON.md, line 44 at r1](https://reviewable.io/reviews/pmem/rpma/1636#-MzZmRi_3xm96fErXKkE:-MzZmRi_3xm96fErXKkF:bpvma69) ([raw file](https://github.com/pmem/rpma/blob/6734d3c8ab0cb9547e4154716cd8f9cbd7f5e27f/tools/perf/CONFIG.JSON.md#L44)):*
> ```Markdown
> - "FIO_PATH" - an absolute path to the directory, where the fio binary is located on the local node,
> - "REMOTE_FIO_PATH" - an absolute path to the directory, where the fio binary is located on the remote node,
> - "xADR" - a state of eADR (True or False). Used only on Ice Lake platforms. 
> ```

`), used`



_Code quote:_
```Markdown
). Used
```
___
*[tools/perf/config.json.example, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1636#-MzZmKXA5E1AtaHG4NLE:-MzZmKXA5E1AtaHG4NLF:b-tft0xe) ([raw file](https://github.com/pmem/rpma/blob/6734d3c8ab0cb9547e4154716cd8f9cbd7f5e27f/tools/perf/config.json.example#L13)):*
> ```
>     "REMOTE_DIRECT_WRITE_TO_PMEM": false,
>     "REMOTE_PMEM_PATH": "for example: /dev/dax0.0 or /mnt/pmem0/file",
>     "X_ADR": true
> ```

`xADR`



_Code quote:_
```
X_ADR
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1636)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

___
*[tools/perf/lib/Requirement.py, line 291 at r1](https://reviewable.io/reviews/pmem/rpma/1636#-MzZv4rb1GLugRMX0oFw:-MzZv4rb1GLugRMX0oFx:b7fuc7k) ([raw file](https://github.com/pmem/rpma/blob/6734d3c8ab0cb9547e4154716cd8f9cbd7f5e27f/tools/perf/lib/Requirement.py#L291)):*
> ```Python
>                     return True
>                 else:
>                     raise ValueError('REMOTE_DIRECT_WRITE_TO_PMEM cannot be False when xADR is True')
> ```

This is the `else` branch, so `REMOTE_DIRECT_WRITE_TO_PMEM` is `True` here, so the message:
`'REMOTE_DIRECT_WRITE_TO_PMEM cannot be False when xADR is True')` does not make sense here ...



_Code quote:_
```Python
                else:
                    raise ValueError('REMOTE_DIRECT_WRITE_TO_PMEM cannot be False when xADR is True')
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1636)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/CONFIG.JSON.md, line 44 at r1](https://reviewable.io/reviews/pmem/rpma/1636#-MzZmRi_3xm96fErXKkE:-MzaBiPO6nMPAcnxJB2w:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6734d3c8ab0cb9547e4154716cd8f9cbd7f5e27f/tools/perf/CONFIG.JSON.md#L44)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`), used`
</blockquote></details>

Done.
___
*[tools/perf/config.json.example, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1636#-MzZmKXA5E1AtaHG4NLE:-MzaBdSuAr0bOCt6RjaG:b-zc2p07) ([raw file](https://github.com/pmem/rpma/blob/6734d3c8ab0cb9547e4154716cd8f9cbd7f5e27f/tools/perf/config.json.example#L13)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`xADR`
</blockquote></details>

It was because of wrong merging. Sorry. Done.
___
*[tools/perf/lib/Requirement.py, line 291 at r1](https://reviewable.io/reviews/pmem/rpma/1636#-MzZv4rb1GLugRMX0oFw:-MzaDLxvDG8sttPrk9r-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6734d3c8ab0cb9547e4154716cd8f9cbd7f5e27f/tools/perf/lib/Requirement.py#L291)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

This is the `else` branch, so `REMOTE_DIRECT_WRITE_TO_PMEM` is `True` here, so the message:
`'REMOTE_DIRECT_WRITE_TO_PMEM cannot be False when xADR is True')` does not make sense here ...


</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1636)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[tools/perf/lib/Requirement.py, line 291 at r2](https://reviewable.io/reviews/pmem/rpma/1636#-MzehEyrC4AUr2MyfyrV:-MzehEyrC4AUr2MyfyrW:b51exvt) ([raw file](https://github.com/pmem/rpma/blob/954035b968f15270db00fc3bc0074da5fc9bfb63/tools/perf/lib/Requirement.py#L291)):*
> ```Python
>                     return True
>                 else:
>                     raise ValueError('When xADR is True REMOTE_DIRECT_WRITE_TO_PMEM has to be False')
> ```

`REMOTE_DIRECT_WRITE_TO_PMEM has to be False, when xADR is True`



_Code quote:_
```Python
When xADR is True REMOTE_DIRECT_WRITE_TO_PMEM has to be False'
```

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1636)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

___
*[tools/perf/config.json.example, line 13 at r2](https://reviewable.io/reviews/pmem/rpma/1636#-MznQXRI5ML4Q2NIqn2C:-MznQXRI5ML4Q2NIqn2D:b-yab1zl) ([raw file](https://github.com/pmem/rpma/blob/954035b968f15270db00fc3bc0074da5fc9bfb63/tools/perf/config.json.example#L13)):*
> ```
>     "REMOTE_DIRECT_WRITE_TO_PMEM": false,
>     "REMOTE_PMEM_PATH": "for example: /dev/dax0.0 or /mnt/pmem0/file",
>     "xADR": true
> ```

``"xADR": false``



_Code quote:_
```
"xADR": true
```

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1636)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/1636#-MznUbHi9HynCU04SE19):*
ignore REMOTE_DIRECT_WRITE_TO_PMEM = false when xADR is enabled on the Ice Lake platform



_Code quote:_
```
add checking xADR parameter for Ice Lake platforms
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1636)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[tools/perf/CONFIG.JSON.md, line 44 at r2](https://reviewable.io/reviews/pmem/rpma/1636#-Mznnm4p20l1PHBhl4WF:-Mznnm4p20l1PHBhl4WG:b-92p1b8) ([raw file](https://github.com/pmem/rpma/blob/954035b968f15270db00fc3bc0074da5fc9bfb63/tools/perf/CONFIG.JSON.md#L44)):*
> ```Markdown
> - "FIO_PATH" - an absolute path to the directory, where the fio binary is located on the local node,
> - "REMOTE_FIO_PATH" - an absolute path to the directory, where the fio binary is located on the remote node,
> - "xADR" - a state of eADR (True or False), used only on Ice Lake platforms. 
> ```

(the default value is False)

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1636)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/1636#-MznUbHi9HynCU04SE19):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

ignore REMOTE_DIRECT_WRITE_TO_PMEM = false when xADR is enabled on the Ice Lake platform
</blockquote></details>

@grom72 it is too long ...

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1636)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/1636#-MznUbHi9HynCU04SE19):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@grom72 it is too long ...
</blockquote></details>

tools: add checking xADR parameter for Ice Lake platforms

Ignore REMOTE_DIRECT_WRITE_TO_PMEM = false when xADR is enabled on the Ice Lake platform.

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1636)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[tools/perf/CONFIG.JSON.md, line 44 at r2](https://reviewable.io/reviews/pmem/rpma/1636#-Mznnm4p20l1PHBhl4WF:-MznoqYv2x6mLiyPJI-b:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/954035b968f15270db00fc3bc0074da5fc9bfb63/tools/perf/CONFIG.JSON.md#L44)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

(the default value is False)
</blockquote></details>

Done.
___
*[tools/perf/config.json.example, line 13 at r2](https://reviewable.io/reviews/pmem/rpma/1636#-MznQXRI5ML4Q2NIqn2C:-MznnPPV-wCs_uDdWNg3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/954035b968f15270db00fc3bc0074da5fc9bfb63/tools/perf/config.json.example#L13)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

``"xADR": false``
</blockquote></details>

Done.
___
*[tools/perf/lib/Requirement.py, line 291 at r2](https://reviewable.io/reviews/pmem/rpma/1636#-MzehEyrC4AUr2MyfyrV:-MznnQ407nJPaYV3GERI:bw5h3gv) ([raw file](https://github.com/pmem/rpma/blob/954035b968f15270db00fc3bc0074da5fc9bfb63/tools/perf/lib/Requirement.py#L291)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`REMOTE_DIRECT_WRITE_TO_PMEM has to be False, when xADR is True`
</blockquote></details>

Done. no comma

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1636)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/1636#-MznUbHi9HynCU04SE19):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

tools: add checking xADR parameter for Ice Lake platforms

Ignore REMOTE_DIRECT_WRITE_TO_PMEM = false when xADR is enabled on the Ice Lake platform.

</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1636)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[-- commits, line 2 at r4](https://reviewable.io/reviews/pmem/rpma/1636#-MznwVzmCKTFaUCKwjJv):*
@grom72 

```
FAIL: commit message exceeds 72 chars per line (commit_len)

commit 9b812cf1d756f09133fd7d9e483570197c10fc1f
Author: Kacper Stefanski <kacper.stefanski@intel.com>
Date:   Fri Apr 1 04:30:09 2022 -0400

    tools: add checking xADR parameter for Ice Lake platforms
    Ignore REMOTE_DIRECT_WRITE_TO_PMEM = false
    when xADR is enabled on the Ice Lake platform
```



_Code quote:_
```
tools: add checking xADR parameter for Ice Lake platforms
```

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1636)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/1636#-MznUbHi9HynCU04SE19):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Missing <cr> between title and body

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1636)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi and @ldorau)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1636)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[-- commits, line 2 at r4](https://reviewable.io/reviews/pmem/rpma/1636#-MznwVzmCKTFaUCKwjJv):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@grom72 

```
FAIL: commit message exceeds 72 chars per line (commit_len)

commit 9b812cf1d756f09133fd7d9e483570197c10fc1f
Author: Kacper Stefanski <kacper.stefanski@intel.com>
Date:   Fri Apr 1 04:30:09 2022 -0400

    tools: add checking xADR parameter for Ice Lake platforms
    Ignore REMOTE_DIRECT_WRITE_TO_PMEM = false
    when xADR is enabled on the Ice Lake platform
```
</blockquote></details>

Missing <cr> between title and body

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1636)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/1636#-MznUbHi9HynCU04SE19):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Missing <cr> between title and body
</blockquote></details>

Missing ``<cr><lf>`` between title and body
___
*[-- commits, line 2 at r4](https://reviewable.io/reviews/pmem/rpma/1636#-MznwVzmCKTFaUCKwjJv):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Missing <cr> between title and body
</blockquote></details>

Missing ``<cr><lf>`` between title and body

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1636)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/1636#-MznUbHi9HynCU04SE19):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Missing ``<cr><lf>`` between title and body
</blockquote></details>

You mean <lf> only? ;). Done.
___
*[-- commits, line 2 at r4](https://reviewable.io/reviews/pmem/rpma/1636#-MznwVzmCKTFaUCKwjJv):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

That's right, see: https://github.com/pmem/rpma/blob/master/CONTRIBUTING.md#commit-messages
</blockquote></details>

Done.

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1636)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/1636#-MznUbHi9HynCU04SE19):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

You mean <lf> only? ;). Done.
</blockquote></details>

only <lf> ...

**Review by ldorau — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1636)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1636#-:-MzsGdIuECEqlZ0pnx38:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1636)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1636#-:-MzsXupf0IRtXWPCklOT:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1636)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1636)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[tools/perf/lib/Requirement.py, line 288 at r5](https://reviewable.io/reviews/pmem/rpma/1636#-MzsZW-p34T1oV2zOELf:-MzsZW-q4OfQ2evvyy2u:bb1tx2r) ([raw file](https://github.com/pmem/rpma/blob/46cf8d6fceafa8b82c68c5e945494e1f8545d078/tools/perf/lib/Requirement.py#L288)):*
> ```Python
>         def is_met(cls, req, config):
>             if config.get('xADR', False) is True:
>                 if config['REMOTE_DIRECT_WRITE_TO_PMEM'] is False:
> ```

What if `'REMOTE_DIRECT_WRITE_TO_PMEM' not in config` here? 
`REMOTE_DIRECT_WRITE_TO_PMEM` is always required, so it should look rather like:

```python
        @classmethod
        def is_met(cls, req, config):
            if 'REMOTE_DIRECT_WRITE_TO_PMEM' not in config:
                raise ValueError('REMOTE_DIRECT_WRITE_TO_PMEM is missing in the config')
            if config.get('xADR', False) is True:
                if config['REMOTE_DIRECT_WRITE_TO_PMEM'] is False:
                    return True
                else:
                    raise ValueError('REMOTE_DIRECT_WRITE_TO_PMEM has to be False when xADR is True')
            # For the ICX generation, there is no way of toggling Direct Write
            # to PMem from the OS level. The configuration has to be adjusted
            # manually on the BIOS level.
            return req['direct_write_to_pmem'] == \
                config['REMOTE_DIRECT_WRITE_TO_PMEM']
```



_Code quote:_
```Python
if config['REMOTE_DIRECT_WRITE_TO_PMEM'] is False:
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1636)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @grom72, @ldorau, and @osalyk)

___
*[tools/perf/lib/Requirement.py, line 288 at r5](https://reviewable.io/reviews/pmem/rpma/1636#-MzsZW-p34T1oV2zOELf:-MzsgkOIEK5ydl8GVDRr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/46cf8d6fceafa8b82c68c5e945494e1f8545d078/tools/perf/lib/Requirement.py#L288)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

What if `'REMOTE_DIRECT_WRITE_TO_PMEM' not in config` here? 
`REMOTE_DIRECT_WRITE_TO_PMEM` is always required, so it should look rather like:

```python
        @classmethod
        def is_met(cls, req, config):
            if 'REMOTE_DIRECT_WRITE_TO_PMEM' not in config:
                raise ValueError('REMOTE_DIRECT_WRITE_TO_PMEM is missing in the config')
            if config.get('xADR', False) is True:
                if config['REMOTE_DIRECT_WRITE_TO_PMEM'] is False:
                    return True
                else:
                    raise ValueError('REMOTE_DIRECT_WRITE_TO_PMEM has to be False when xADR is True')
            # For the ICX generation, there is no way of toggling Direct Write
            # to PMem from the OS level. The configuration has to be adjusted
            # manually on the BIOS level.
            return req['direct_write_to_pmem'] == \
                config['REMOTE_DIRECT_WRITE_TO_PMEM']
```
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1636)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[tools/perf/lib/Requirement.py, line 295 at r6](https://reviewable.io/reviews/pmem/rpma/1636#-MzsgxGw2Df2KKYXGDFz:-MzsgxGw2Df2KKYXGDG-:bxcq700) ([raw file](https://github.com/pmem/rpma/blob/30cb4a4a76c61296d7e443feb730a946292d1f3c/tools/perf/lib/Requirement.py#L295)):*
> ```Python
>                     raise ValueError('REMOTE_DIRECT_WRITE_TO_PMEM has to be False when xADR is True')
>             elif 'REMOTE_DIRECT_WRITE_TO_PMEM' not in config:
>                 raise ValueError('REMOTE_DIRECT_WRITE_TO_PMEM is missing in the config')
> ```

It is not needed now.



_Code quote:_
```Python
            elif 'REMOTE_DIRECT_WRITE_TO_PMEM' not in config:
                raise ValueError('REMOTE_DIRECT_WRITE_TO_PMEM is missing in the config')
```

**Review by grom72 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1636)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1636)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/lib/Requirement.py, line 295 at r6](https://reviewable.io/reviews/pmem/rpma/1636#-MzsgxGw2Df2KKYXGDFz:-MztK6ub9zvI3-A1Onek:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/30cb4a4a76c61296d7e443feb730a946292d1f3c/tools/perf/lib/Requirement.py#L295)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It is not needed now.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1636#-:-MztMDue1UVXCIEYW_sQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
