### PR TITLE
rpma: make rpma_log_set_threshold() thread-safe

### PR DESCRIPTION
**Pull request by haichangsi**
Add a mtt test for rpma_log_set_threshold.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1951)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1951)* status: 0 of 7 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1951)* status: 1 of 7 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1951)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @haichangsi and @ldorau)

___
*[`tests/multithreaded/log/rpma_log_set_threshold.c` line 26 at r1](https://reviewable.io/reviews/pmem/rpma/1951#-N7tnXHs9ANTgymmgtjJ:-N7tnXHs9ANTgymmgtjK:b-ckj13e) ([raw file](https://github.com/pmem/rpma/blob/3f08a675213cd09008c4d8e1f48d41b72cca36b0/tests/multithreaded/log/rpma_log_set_threshold.c#L26)):*
> ```C
> 	}
> 
> 	rpma_log_get_threshold(RPMA_LOG_THRESHOLD, &level);
> ```

Why don't we check if the rpma_log_get_threshold() function succeeded?



_Code quote:_
```C
rpma_log_get_threshold(RPMA_LOG_THRESHOLD, &level);
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1951)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @haichangsi, @ldorau, and @osalyk)

___
*[`src/log.c` line 12 at r1](https://reviewable.io/reviews/pmem/rpma/1951#-N7u2Zp-2CwriNqzJDqy:-N7u2Zp-2CwriNqzJDqz:b9jt74d) ([raw file](https://github.com/pmem/rpma/blob/3f08a675213cd09008c4d8e1f48d41b72cca36b0/src/log.c#L12)):*
> ```C
> #include <syslog.h>
> #include <time.h>
> #ifdef ATOMIC_STORE_SUPPORTED
> ```

Replace all `ATOMIC_STORE_SUPPORTED` with `ATOMIC_OPERATIONS_SUPPORTED` - see https://github.com/pmem/rpma/pull/1950



_Code quote:_
```C
ATOMIC_STORE_SUPPORTED
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1951)* status: all files reviewed, 6 unresolved discussions (waiting on @haichangsi and @osalyk)

___
*[`CHANGELOG.md` line 27 at r1](https://reviewable.io/reviews/pmem/rpma/1951#-N7u3095DBxW5ZjYSApI:-N7u3095DBxW5ZjYSApJ:b-ujmq67) ([raw file](https://github.com/pmem/rpma/blob/3f08a675213cd09008c4d8e1f48d41b72cca36b0/CHANGELOG.md#L27)):*
> ```Markdown
>   - rpma_conn_apply_remote_peer_cfg
>   - rpma_conn_req_connect
>   - rpma_ep_next_conn_req
> ```

Rebase please



_Code quote:_
```Markdown
  - rpma_ep_next_conn_req
  - rpma_log_set_threshold
  - rpma_peer_cfg_set_direct_write_to_pmem
```
___
*[`tests/multithreaded/log/CMakeLists.txt` line 9 at r1](https://reviewable.io/reviews/pmem/rpma/1951#-N7u3GucBHC17dojimnH:-N7u3GucBHC17dojimnI:b-s3hmk9) ([raw file](https://github.com/pmem/rpma/blob/3f08a675213cd09008c4d8e1f48d41b72cca36b0/tests/multithreaded/log/CMakeLists.txt#L9)):*
> ```CMake
> 
> add_multithreaded(NAME log BIN rpma_log_set_threshold
> 	SRCS rpma_log_set_threshold.c ../../../src/log.c ../../../src/log_default.c)
> ```

Not needed.



_Code quote:_
```CMake
../../../src/log.c ../../../src/log_default.c
```
___
*[`tests/multithreaded/log/rpma_log_set_threshold.c` line 22 at r1](https://reviewable.io/reviews/pmem/rpma/1951#-N7u4GZh3y_ia9VeqkVU:-N7u4GZh3y_ia9VeqkVV:b9owed9) ([raw file](https://github.com/pmem/rpma/blob/3f08a675213cd09008c4d8e1f48d41b72cca36b0/tests/multithreaded/log/rpma_log_set_threshold.c#L22)):*
> ```C
> 
> 	if ((ret = rpma_log_set_threshold(RPMA_LOG_THRESHOLD, RPMA_LOG_LEVEL_INFO))) {
> 		MTT_RPMA_ERR(tr, "rpma_log_set_threshold", ret);
> ```

It is enough in the rpma_log_set_threshold MT test.



_Code quote:_
```C
void
thread(unsigned id, void *prestate, void *state, struct mtt_result *tr)
{
	enum rpma_log_level level;
	int ret;

	if ((ret = rpma_log_set_threshold(RPMA_LOG_THRESHOLD, RPMA_LOG_LEVEL_INFO))) {
		MTT_RPMA_ERR(tr, "rpma_log_set_threshold", ret);
		return;
	}
```
___
*[`tests/multithreaded/log/rpma_log_set_threshold.c` line 26 at r1](https://reviewable.io/reviews/pmem/rpma/1951#-N7u4Md80q57idTkraVh:-N7u4Md80q57idTkraVi:bh9fv4i) ([raw file](https://github.com/pmem/rpma/blob/3f08a675213cd09008c4d8e1f48d41b72cca36b0/tests/multithreaded/log/rpma_log_set_threshold.c#L26)):*
> ```C
> 	}
> 
> 	rpma_log_get_threshold(RPMA_LOG_THRESHOLD, &level);
> ```

It can be added in a new, separate, `rpma_log_set_get_threshold` MT test.



_Code quote:_
```C
	rpma_log_get_threshold(RPMA_LOG_THRESHOLD, &level);

	if (level != RPMA_LOG_LEVEL_INFO) {
		MTT_ERR(tr, "pr->level != RPMA_LOG_LEVEL_INFO", EINVAL);
	}
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1951)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[`CHANGELOG.md` line 27 at r1](https://reviewable.io/reviews/pmem/rpma/1951#-N7u3095DBxW5ZjYSApI:-N7w9Glc23PId9ms5Uch:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3f08a675213cd09008c4d8e1f48d41b72cca36b0/CHANGELOG.md#L27)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Rebase please
</blockquote></details>

Done.
___
*[`src/log.c` line 12 at r1](https://reviewable.io/reviews/pmem/rpma/1951#-N7u2Zp-2CwriNqzJDqy:-N7w9FgrClznUPJE7W9F:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3f08a675213cd09008c4d8e1f48d41b72cca36b0/src/log.c#L12)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Replace all `ATOMIC_STORE_SUPPORTED` with `ATOMIC_OPERATIONS_SUPPORTED` - see https://github.com/pmem/rpma/pull/1950
</blockquote></details>

Done.
___
*[`tests/multithreaded/log/CMakeLists.txt` line 9 at r1](https://reviewable.io/reviews/pmem/rpma/1951#-N7u3GucBHC17dojimnH:-N7w9J5u5QiKL949Hi9I:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3f08a675213cd09008c4d8e1f48d41b72cca36b0/tests/multithreaded/log/CMakeLists.txt#L9)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not needed.
</blockquote></details>

Done.
___
*[`tests/multithreaded/log/rpma_log_set_threshold.c` line 22 at r1](https://reviewable.io/reviews/pmem/rpma/1951#-N7u4GZh3y_ia9VeqkVU:-N7w9_QTCG91A2ar_RfE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3f08a675213cd09008c4d8e1f48d41b72cca36b0/tests/multithreaded/log/rpma_log_set_threshold.c#L22)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It is enough in the rpma_log_set_threshold MT test.
</blockquote></details>

Done.
___
*[`tests/multithreaded/log/rpma_log_set_threshold.c` line 26 at r1](https://reviewable.io/reviews/pmem/rpma/1951#-N7u4Md80q57idTkraVh:-N7w9Xtx2_cnMjyTzx3m:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3f08a675213cd09008c4d8e1f48d41b72cca36b0/tests/multithreaded/log/rpma_log_set_threshold.c#L26)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It can be added in a new, separate, `rpma_log_set_get_threshold` MT test.
</blockquote></details>

Done.
___
*[`tests/multithreaded/log/rpma_log_set_threshold.c` line 26 at r1](https://reviewable.io/reviews/pmem/rpma/1951#-N7tnXHs9ANTgymmgtjJ:-N7w9ZrAA01rQgDMxSb_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3f08a675213cd09008c4d8e1f48d41b72cca36b0/tests/multithreaded/log/rpma_log_set_threshold.c#L26)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Why don't we check if the rpma_log_get_threshold() function succeeded?
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1951)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi and @osalyk)

___
*[`CHANGELOG.md` line 29 at r2](https://reviewable.io/reviews/pmem/rpma/1951#-N7y9C3O1tfYyZzRJgN7:-N7y9C3O1tfYyZzRJgN8:b-ymz0a2) ([raw file](https://github.com/pmem/rpma/blob/cbb1edd3eb29297c04ca2276b9a277b1683a6ac5/CHANGELOG.md#L29)):*
> ```Markdown
>   - rpma_ep_next_conn_req
> <<<<<<< HEAD
>   - rpma_log_set_function
> ```

Resolve the conflict, please.



_Code quote:_
```Markdown
<<<<<<< HEAD
  - rpma_log_set_function
||||||| parent of 3f08a675 (rpma: make log_set_threshold thread-safe.)
=======
  - rpma_log_set_threshold
>>>>>>> 3f08a675 (rpma: make log_set_threshold thread-safe.)
```
___
*[`tests/multithreaded/log/rpma_log_set_threshold.c` line 13 at r2](https://reviewable.io/reviews/pmem/rpma/1951#-N7y9fn8DlggUKiNCI6U:-N7y9fn8DlggUKiNCI6V:budulhk) ([raw file](https://github.com/pmem/rpma/blob/cbb1edd3eb29297c04ca2276b9a277b1683a6ac5/tests/multithreaded/log/rpma_log_set_threshold.c#L13)):*
> ```C
> 
> /*
>  * thread -- set log function
> ```

set threshold



_Code quote:_
```C
set log function
```

**Review by osalyk — COMMENTED** [review]
:goat: 

> Reviewed 6 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1951#-:-N7yAeMK7W2gTIkRQ25_:bdycpsm)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1951)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

___
*[`tests/multithreaded/log/rpma_log_set_threshold.c` line 13 at r2](https://reviewable.io/reviews/pmem/rpma/1951#-N7y9fn8DlggUKiNCI6U:-N7yBLyo9pxVaikitopY:b-vvlixr) ([raw file](https://github.com/pmem/rpma/blob/cbb1edd3eb29297c04ca2276b9a277b1683a6ac5/tests/multithreaded/log/rpma_log_set_threshold.c#L13)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

set threshold
</blockquote></details>

set the log level threshold

**Review by Patryk717 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1951#-:-N7yLlwj2uenVsFvSO6a:bdycpsm)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1951)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[`CHANGELOG.md` line 29 at r2](https://reviewable.io/reviews/pmem/rpma/1951#-N7y9C3O1tfYyZzRJgN7:-N7ycENr3c9VainjSRkg:b2gajeq) ([raw file](https://github.com/pmem/rpma/blob/cbb1edd3eb29297c04ca2276b9a277b1683a6ac5/CHANGELOG.md#L29)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Resolve the conflict, please.
</blockquote></details>

wow, sry, done
___
*[`tests/multithreaded/log/rpma_log_set_threshold.c` line 13 at r2](https://reviewable.io/reviews/pmem/rpma/1951#-N7y9fn8DlggUKiNCI6U:-N7ybvAqAgT2khfSQLD7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cbb1edd3eb29297c04ca2276b9a277b1683a6ac5/tests/multithreaded/log/rpma_log_set_threshold.c#L13)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

set the log level threshold
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1951)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/pmem/rpma/1951#-N7yna4g43VTA8R3422L):*
No dot at the end, please



_Code quote:_
```
thread-safe.
```
___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/pmem/rpma/1951#-N7ynyY_6q-B9F92IlyZ):*
rpma_log_set_threshold()



_Code quote:_
```
log_set_threshold
```
___
*[`-- commits` line 4 at r3](https://reviewable.io/reviews/pmem/rpma/1951#-N7yngrTC0e_6XJR8jHu):*
Make rpma_log_set_threshold() thread-safe and add a MT test for it.



_Code quote:_
```
Add a mtt test for rpma_log_set_threshold.
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1951)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @ldorau)

___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/pmem/rpma/1951#-N7yna4g43VTA8R3422L):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No dot at the end, please
</blockquote></details>

Done.
___
*[`-- commits` line 2 at r3](https://reviewable.io/reviews/pmem/rpma/1951#-N7ynyY_6q-B9F92IlyZ):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

rpma_log_set_threshold()
</blockquote></details>

Done.
___
*[`-- commits` line 4 at r3](https://reviewable.io/reviews/pmem/rpma/1951#-N7yngrTC0e_6XJR8jHu):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Make rpma_log_set_threshold() thread-safe and add a MT test for it.
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1951)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/pmem/rpma/1951#-N7z8qdV2DPx8Z0VSd7F):*
I am afraid it will be too long. I meant something different:
```
rpma: make rpma_log_set_threshold() thread-safe

Make rpma_log_set_threshold() thread-safe and add a MT test for it.
```



_Code quote:_
```
rpma: make rpma_log_set_threshold() thread-safe and add a MT test for it
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1951)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/pmem/rpma/1951#-N7z8qdV2DPx8Z0VSd7F):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I am afraid it will be too long. I meant something different:
```
rpma: make rpma_log_set_threshold() thread-safe

Make rpma_log_set_threshold() thread-safe and add a MT test for it.
```

</blockquote></details>

Or:
```
rpma: make rpma_log_set_threshold() thread-safe

Make rpma_log_set_threshold() thread-safe
and add a MT test for it.
```

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1951)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

___
*[`-- commits` line 2 at r4](https://reviewable.io/reviews/pmem/rpma/1951#-N7z8qdV2DPx8Z0VSd7F):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Or:
```
rpma: make rpma_log_set_threshold() thread-safe

Make rpma_log_set_threshold() thread-safe
and add a MT test for it.
```

</blockquote></details>

Huh, and yet it works

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1951#-:-N7zCxYWDL2D7us-h-Nf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
