### PR TITLE
common: fix some spelling errors

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/2038)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2038)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`tools/perf/multiply_connection_benchmark.md` line 99 at r1](https://reviewable.io/reviews/pmem/rpma/2038#-NCaFi9z7rYEc0hPU2xs:-NCaFiA-0MDtbSCSVs4b:undefined) ([raw file](https://github.com/pmem/rpma/blob/652fdd33572c58e4b2435cbec83d061f260cf876/tools/perf/multiply_connection_benchmark.md#L99)):*
> ```Markdown
>     args.append('--filename_format={}.\\$jobnum'.format(pmem_path))
> ```
> ### Finally tuning
> ```





_Suggestion:_
```Markdown
Final tuning
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2038)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2038)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`tools/perf/multiply_connection_benchmark.md` line 99 at r1](https://reviewable.io/reviews/pmem/rpma/2038#-NCaFi9z7rYEc0hPU2xs:-NCaPq1j4nKQhcXl-8IZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/652fdd33572c58e4b2435cbec83d061f260cf876/tools/perf/multiply_connection_benchmark.md#L99)):*
> ```Markdown
>     args.append('--filename_format={}.\\$jobnum'.format(pmem_path))
> ```
> ### Finally tuning
> ```

Done.

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2038#-:-NCaQdzk9Rwxwy08IW7n:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Comment by yangx-jy** [comment]
*[`tools/perf/multiply_connection_benchmark.md` line 99 at r3](https://reviewable.io/reviews/pmem/rpma/2038#-NCbxkK60LF173cIkeQM:-NCbxkK60LF173cIkeQN:bpzu81t) ([raw file](https://github.com/pmem/rpma/blob/7ffb1b405599fa5c21c821fd2208660641e10a3d/tools/perf/multiply_connection_benchmark.md#L99)):*
> ```Markdown
>     args.append('--filename_format={}.\\$jobnum'.format(pmem_path))
> ```
> ### Finaly tuning
> ```

Finally?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2038)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[`tools/perf/multiply_connection_benchmark.md` line 99 at r3](https://reviewable.io/reviews/pmem/rpma/2038#-NCbxkK60LF173cIkeQM:-NCcsAinECSYHiYNZXXg:b-gwkbbu) ([raw file](https://github.com/pmem/rpma/blob/7ffb1b405599fa5c21c821fd2208660641e10a3d/tools/perf/multiply_connection_benchmark.md#L99)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Finally?
</blockquote></details>

It was `Finally` and it has been corrected to `Final`.

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2038#-:-NCcyB3u3Kjw4-U3cU0o:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

**Pull request merged**
