### PR TITLE
common: 0.9.0 changelog update

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/533)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/533#-:-MIZNAusCvTTWm2uAn5W:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/533)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[CHANGELOG.md, line 11 at r1](https://reviewable.io/reviews/pmem/rpma/533#-MIZNdn1CVVvg3OBu_aC:-MIZNdn1CVVvg3OBu_aD:b-6y6fnf) ([raw file](https://github.com/pmem/rpma/blob/d7d957333e3668ffd7fec43167c60854d60f393b/CHANGELOG.md#L11)):*
> ```
> The API providing 
> ```

The API provides

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/533)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/533)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[CHANGELOG.md, line 11 at r1](https://reviewable.io/reviews/pmem/rpma/533#-MIZNdn1CVVvg3OBu_aC:-MIZO2qaE92SiPPU5LPZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d7d957333e3668ffd7fec43167c60854d60f393b/CHANGELOG.md#L11)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> The API providing 
> ```

The API provides
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/533)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[CHANGELOG.md, line 13 at r2](https://reviewable.io/reviews/pmem/rpma/533#-MIZNsvC6kMwVp_S1Xdr:-MIZNsvD6iyW9CUJTcYO:bu21nj7) ([raw file](https://github.com/pmem/rpma/blob/0c58756b9799af32e497ffecdd1e80512a08a123/CHANGELOG.md#L13)):*
> ```
> showing
> ```

show
___
*[CHANGELOG.md, line 14 at r2](https://reviewable.io/reviews/pmem/rpma/533#-MIZO0CG6Y3KXScE5Thk:-MIZO0CG6Y3KXScE5Thl:b-sqkwgu) ([raw file](https://github.com/pmem/rpma/blob/0c58756b9799af32e497ffecdd1e80512a08a123/CHANGELOG.md#L14)):*
> ```
> base on
> ```

basing on
___
*[CHANGELOG.md, line 16 at r2](https://reviewable.io/reviews/pmem/rpma/533#-MIZONI96x2NA4IvWLtY:-MIZONI96x2NA4IvWLtZ:bmp3lv3) ([raw file](https://github.com/pmem/rpma/blob/0c58756b9799af32e497ffecdd1e80512a08a123/CHANGELOG.md#L16)):*
> ```
> An extensive documentation describing
> ```

The extensive documentation describes

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/533)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/533)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[CHANGELOG.md, line 11 at r3](https://reviewable.io/reviews/pmem/rpma/533#-MIZOtIL6gj9fvMLITTj:-MIZOtIL6gj9fvMLITTk:bqg2i00) ([raw file](https://github.com/pmem/rpma/blob/bb158c1a5d4b4f8a8b95bf871b1f14c4f1a8902b/CHANGELOG.md#L11)):*
> ```
> of a remote persistency
> ```

`of the remote persistency` or even no article: `of remote persistency` -because it is an abstraction

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/533)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[CHANGELOG.md, line 13 at r2](https://reviewable.io/reviews/pmem/rpma/533#-MIZNsvC6kMwVp_S1Xdr:-MIZOkMM6wG0o60WvcHd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0c58756b9799af32e497ffecdd1e80512a08a123/CHANGELOG.md#L13)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> showing
> ```

show
</blockquote></details>

Done.
___
*[CHANGELOG.md, line 14 at r2](https://reviewable.io/reviews/pmem/rpma/533#-MIZO0CG6Y3KXScE5Thk:-MIZOpVB2sBnKZ2VU7Q5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0c58756b9799af32e497ffecdd1e80512a08a123/CHANGELOG.md#L14)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> base on
> ```

basing on
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/533)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[CHANGELOG.md, line 16 at r2](https://reviewable.io/reviews/pmem/rpma/533#-MIZONI96x2NA4IvWLtY:-MIZPgaU1VT5RxEm3o0z:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0c58756b9799af32e497ffecdd1e80512a08a123/CHANGELOG.md#L16)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> An extensive documentation describing
> ```

The extensive documentation describes
</blockquote></details>

Done.
___
*[CHANGELOG.md, line 11 at r3](https://reviewable.io/reviews/pmem/rpma/533#-MIZOtIL6gj9fvMLITTj:-MIZPhlc3hxxx0A0tzCo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bb158c1a5d4b4f8a8b95bf871b1f14c4f1a8902b/CHANGELOG.md#L11)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> of a remote persistency
> ```

`of the remote persistency` or even no article: `of remote persistency` -because it is an abstraction 
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/533)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/533#-:-MIZPvl46Cjj2iIcRPTq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
