### PR TITLE
tools: implement Figure.html_data_table()

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1113)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1113)* status: all files reviewed, 5 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/lib/Figure.py, line 174 at r1](https://reviewable.io/reviews/pmem/rpma/1113#-MdSNsBCCQxy8Ta7lZPj:-MdSNsBCCQxy8Ta7lZPk:b-lxu21c) ([raw file](https://github.com/pmem/rpma/blob/ec564f7c4a0bec3cad60a81fa7616cdb2ebbf2e0/tools/perf/lib/Figure.py#L174)):*
> ```Python
>         Create an HTML snippet string with a table containing the Figure data.
>         """
>         html = "<style> td { border: 1px solid black; } </style> <table>"
> ```

Knowing this snippet will end up inside a bigger HTML document it has not to be styled individually.
Please see the already existing report as a reference.
___
*[tools/perf/lib/Figure.py, line 177 at r1](https://reviewable.io/reviews/pmem/rpma/1113#-MdSW7CR1KCm2_luz6yX:-MdSW7CR1KCm2_luz6yY:broml4v) ([raw file](https://github.com/pmem/rpma/blob/ec564f7c4a0bec3cad60a81fa7616cdb2ebbf2e0/tools/perf/lib/Figure.py#L177)):*
> ```Python
> 
>         # header
>         html += "<tr> <td></td>"
> ```

Please use `<th>` instead of `<td>` for the header cells.
___
*[tools/perf/lib/Figure.py, line 177 at r1](https://reviewable.io/reviews/pmem/rpma/1113#-MdSYhKOASNn_GynHLXo:-MdSYhKOASNn_GynHLXp:brliw6j) ([raw file](https://github.com/pmem/rpma/blob/ec564f7c4a0bec3cad60a81fa7616cdb2ebbf2e0/tools/perf/lib/Figure.py#L177)):*
> ```Python
> 
>         # header
>         html += "<tr> <td></td>"
> ```

No spaces between HTML tags needed. Is it for readability?
___
*[tools/perf/lib/Figure.py, line 183 at r1](https://reviewable.io/reviews/pmem/rpma/1113#-MdSYJt4E_wUU0prxoFU:-MdSYJt4E_wUU0prxoFV:b-ojp22c) ([raw file](https://github.com/pmem/rpma/blob/ec564f7c4a0bec3cad60a81fa7616cdb2ebbf2e0/tools/perf/lib/Figure.py#L183)):*
> ```Python
> 
>         # rows
>         for serie in self.series:
> ```

I'm not sure whether 'serie' is a single form of series.
Do you have any references? So far I have used `oneseries` to indicate singular.
___
*[tools/perf/lib/Figure.py, line 184 at r1](https://reviewable.io/reviews/pmem/rpma/1113#-MdSYqwu6mbR_-99dcxq:-MdSYqwu6mbR_-99dcxr:b3l6bw0) ([raw file](https://github.com/pmem/rpma/blob/ec564f7c4a0bec3cad60a81fa7616cdb2ebbf2e0/tools/perf/lib/Figure.py#L184)):*
> ```Python
>         # rows
>         for serie in self.series:
>             html += "<tr> <td>" + serie.label + "</td>"
> ```

Spaces for readability?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1113)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/lib/Figure.py, line 174 at r1](https://reviewable.io/reviews/pmem/rpma/1113#-MdSNsBCCQxy8Ta7lZPj:-MdVTUDg0LoR5g3C0MX7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ec564f7c4a0bec3cad60a81fa7616cdb2ebbf2e0/tools/perf/lib/Figure.py#L174)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Knowing this snippet will end up inside a bigger HTML document it has not to be styled individually.
Please see the already existing report as a reference.
</blockquote></details>

Done.
___
*[tools/perf/lib/Figure.py, line 177 at r1](https://reviewable.io/reviews/pmem/rpma/1113#-MdSW7CR1KCm2_luz6yX:-MdVTUe2CPh_8z-K5lvT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ec564f7c4a0bec3cad60a81fa7616cdb2ebbf2e0/tools/perf/lib/Figure.py#L177)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please use `<th>` instead of `<td>` for the header cells.
</blockquote></details>

Done.
___
*[tools/perf/lib/Figure.py, line 177 at r1](https://reviewable.io/reviews/pmem/rpma/1113#-MdSYhKOASNn_GynHLXo:-MdVTVJD2GHrfMjK4j9T:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ec564f7c4a0bec3cad60a81fa7616cdb2ebbf2e0/tools/perf/lib/Figure.py#L177)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

No spaces between HTML tags needed. Is it for readability?
</blockquote></details>

Done.
___
*[tools/perf/lib/Figure.py, line 183 at r1](https://reviewable.io/reviews/pmem/rpma/1113#-MdSYJt4E_wUU0prxoFU:-MdVTWUJDgWcrw_ccGCd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ec564f7c4a0bec3cad60a81fa7616cdb2ebbf2e0/tools/perf/lib/Figure.py#L183)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I'm not sure whether 'serie' is a single form of series.
Do you have any references? So far I have used `oneseries` to indicate singular.
</blockquote></details>

Done.
___
*[tools/perf/lib/Figure.py, line 184 at r1](https://reviewable.io/reviews/pmem/rpma/1113#-MdSYqwu6mbR_-99dcxq:-MdVTX2R3GfGihv-oc8w:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ec564f7c4a0bec3cad60a81fa7616cdb2ebbf2e0/tools/perf/lib/Figure.py#L184)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Spaces for readability?
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1113#-:-MdVkUCB92iSqG4-QeSv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1113#-:-MdVmh4Y2YiWTQeUrfQx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
