### PR TITLE
common: check if librdmacm has correct signature of rdma_getaddrinfo()

### PR DESCRIPTION
**Pull request by ldorau**
Required:
- [x] #363

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/369)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/369)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[CMakeLists.txt, line 112 at r1](https://reviewable.io/reviews/pmem/rpma/369#-MGg6kQz8hZud_90T0QF:-MGg6kR-0sojAaLXI7oY:bjcn10) ([raw file](https://github.com/pmem/rpma/blob/3daf5ebc3c82da14bb0b57eb147dc257ebdd9bdc/CMakeLists.txt#L112)):*
> ```
> FATAL_ERROR
> ```
Is it a fatal case or only information that ODP fallback in mr registration shall not be compiled?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/369)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[CMakeLists.txt, line 112 at r1](https://reviewable.io/reviews/pmem/rpma/369#-MGg6kQz8hZud_90T0QF:-MGgQYn13sc_p22eWtIc:b-wzuhfw) ([raw file](https://github.com/pmem/rpma/blob/3daf5ebc3c82da14bb0b57eb147dc257ebdd9bdc/CMakeLists.txt#L112)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> FATAL_ERROR
> ```
Is it a fatal case or only information that ODP fallback in mr registration shall not be compiled?
</blockquote></details>

It is FATAL_ERROR, because compilation will fail.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/369)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[CMakeLists.txt, line 112 at r1](https://reviewable.io/reviews/pmem/rpma/369#-MGg6kQz8hZud_90T0QF:-MGgh5VaB6Kj8aIuEfd4:bs0kp25) ([raw file](https://github.com/pmem/rpma/blob/3daf5ebc3c82da14bb0b57eb147dc257ebdd9bdc/CMakeLists.txt#L112)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It is FATAL_ERROR, because compilation will fail.
</blockquote></details>

IMHO we should have a flag set here that will disable all fallback from source code using #ifdef

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/369)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[CMakeLists.txt, line 112 at r1](https://reviewable.io/reviews/pmem/rpma/369#-MGg6kQz8hZud_90T0QF:-MGguNm_18epWPAPqZDP:b-rciy31) ([raw file](https://github.com/pmem/rpma/blob/3daf5ebc3c82da14bb0b57eb147dc257ebdd9bdc/CMakeLists.txt#L112)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

IMHO we should have a flag set here that will disable all fallback from source code using #ifdef
</blockquote></details>

Yes, we should do it and we will do that later, because there is much more work to do....

**Comment by ldorau** [comment]
Rebased, undrafted, ready to be merged ;-)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/369)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[cmake/functions.cmake, line 162 at r2](https://reviewable.io/reviews/pmem/rpma/369#-MGmqWay5c2o2HidataP:-MGmqWay5c2o2HidataQ:bkbxsz7) ([raw file](https://github.com/pmem/rpma/blob/39d30f23313d52cc7ed43bafb6d93ffe1541d47f/cmake/functions.cmake#L162)):*
> ```CMake
> # check if librdmacm has correct signature of rdma_getaddrinfo()
> set(CMAKE_REQUIRED_LIBRARIES "-lrdmacm;${CMAKE_REQUIRED_LIBRARIES}")
> set(CMAKE_REQUIRED_FLAGS "-Werror=discarded-qualifiers;${CMAKE_REQUIRED_FLAGS}")
> ```

Do these flags affect the main library build configuration?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/369)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[cmake/functions.cmake, line 162 at r2](https://reviewable.io/reviews/pmem/rpma/369#-MGmqWay5c2o2HidataP:-MGmtJtjBw_soRSyPD8q:b-lkdids) ([raw file](https://github.com/pmem/rpma/blob/39d30f23313d52cc7ed43bafb6d93ffe1541d47f/cmake/functions.cmake#L162)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Do these flags affect the main library build configuration?
</blockquote></details>

I do not think so, but just to be sure I added save&restore.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/369)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[cmake/functions.cmake, line 162 at r2](https://reviewable.io/reviews/pmem/rpma/369#-MGmqWay5c2o2HidataP:-MGmugbWCBsy09hcE0db:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/39d30f23313d52cc7ed43bafb6d93ffe1541d47f/cmake/functions.cmake#L162)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I do not think so, but just to be sure I added save&restore.
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/369)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[cmake/functions.cmake, line 162 at r2](https://reviewable.io/reviews/pmem/rpma/369#-MGmqWay5c2o2HidataP:-MGnW9RJ6_Np7ZkjHqBt:b-6cegot) ([raw file](https://github.com/pmem/rpma/blob/39d30f23313d52cc7ed43bafb6d93ffe1541d47f/cmake/functions.cmake#L162)):*
I have just asked. x-D

According to https://cmake.org/cmake/help/latest/command/set.html:

> Sets the given <variable> in the current function or directory scope.

So, we can set these variables in the function scope and have no worries. :-)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/369)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[cmake/functions.cmake, line 162 at r2](https://reviewable.io/reviews/pmem/rpma/369#-MGmqWay5c2o2HidataP:-MGoBuJN8MH8ZaDkzNIU:b-xt35tn) ([raw file](https://github.com/pmem/rpma/blob/39d30f23313d52cc7ed43bafb6d93ffe1541d47f/cmake/functions.cmake#L162)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I have just asked. x-D

According to https://cmake.org/cmake/help/latest/command/set.html:

> Sets the given <variable> in the current function or directory scope.

So, we can set these variables in the function scope and have no worries. :-)
</blockquote></details>

Right :-) However it's worth to read the documentation ;-)

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/369)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/369#-:-MGr0jUN6ANDXSzg4MQ8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/369#-:-MGrdFm9Ct5hRp_XNCgV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/369#-:-MGrvN-86lAxZew-R5XH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
