### PR TITLE
test: librdmacm / ucma_init() / cma_dev_cnt race assesment

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1006)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
:goat: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1006#-:-MYUIqIL117lKKOp4G9J:bdycpsm)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tests/drd.supp, line 9 at r1](https://reviewable.io/reviews/pmem/rpma/1006#-MYUJD276cRWtan9HZoy:-MYUJD276cRWtan9HZoz:b-3h3z7p) ([raw file](https://github.com/pmem/rpma/blob/8569fd6af1fd03e83c009e7041526895d90e3f85/tests/drd.supp#L9)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> #
> # Assesment: These suppressions do not indicate a lack of MT safety.
> #
> # XXX requires an argument.
> #
> ```
</details>

# Assesment: XXX required. Probably these suppressions do not indicate a lack of MT safety.
___
*[tests/helgrind.supp, line 9 at r1](https://reviewable.io/reviews/pmem/rpma/1006#-MYUJR7q6kbKH9sgqA1A:-MYUJR7q6kbKH9sgqA1B:b-mmeqkl) ([raw file](https://github.com/pmem/rpma/blob/8569fd6af1fd03e83c009e7041526895d90e3f85/tests/helgrind.supp#L9)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> #
> # Assesment: These suppressions do not indicate a lack of MT safety.
> #
> # XXX requires an argument.
> #
> ```
</details>

.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1006)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tests/drd.supp, line 83 at r1](https://reviewable.io/reviews/pmem/rpma/1006#-MYcs3Qt-HW_GhXXckj_:-MYcs3Qt-HW_GhXXckja:b-9tmpvj) ([raw file](https://github.com/pmem/rpma/blob/8569fd6af1fd03e83c009e7041526895d90e3f85/tests/drd.supp#L83)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> {
>    Conflicting store of size 4
>    drd:ConflictingAccess
>    fun:ucma_init
>    fun:ucma_init
>    ...
> }
> ```
</details>


This one can be removed now, because it is covered by the previous one.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1006)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tests/drd.supp, line 9 at r1](https://reviewable.io/reviews/pmem/rpma/1006#-MYUJD276cRWtan9HZoy:-MYgY7B16kKbl2Mr7RPk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8569fd6af1fd03e83c009e7041526895d90e3f85/tests/drd.supp#L9)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> #
> # Assesment: These suppressions do not indicate a lack of MT safety.
> #
> # XXX requires an argument.
> #
> ```
# Assesment: XXX required. Probably these suppressions do not indicate a lack of MT safety.

</blockquote></details>

Done.
___
*[tests/helgrind.supp, line 9 at r1](https://reviewable.io/reviews/pmem/rpma/1006#-MYUJR7q6kbKH9sgqA1A:-MYgYRGI-qupXM_aZGlD:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8569fd6af1fd03e83c009e7041526895d90e3f85/tests/helgrind.supp#L9)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> #
> # Assesment: These suppressions do not indicate a lack of MT safety.
> #
> # XXX requires an argument.
> #
> ```
.
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1006)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tests/drd.supp, line 83 at r1](https://reviewable.io/reviews/pmem/rpma/1006#-MYcs3Qt-HW_GhXXckj_:-MYg_sxo27IjI24CvyYC:bba6zs0) ([raw file](https://github.com/pmem/rpma/blob/8569fd6af1fd03e83c009e7041526895d90e3f85/tests/drd.supp#L83)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> {
>    Conflicting store of size 4
>    drd:ConflictingAccess
>    fun:ucma_init
>    fun:ucma_init
>    ...
> }
> ```

This one can be removed now, because it is covered by the previous one.
</blockquote></details>

Thank you. Good catch.

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1006)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1006#-:-MYhaAHc32PjQ-6xuOFj:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1006#-:-MYi2c0o0KV3FdLV06m8:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1006)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1006#-:-MYmbDCY4AkJjOC2bJpq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1006)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
