### PR TITLE
tools: fio: verify if tool_mode has a correct value

### PR DESCRIPTION
**Pull request by ldorau**
Depends on:
- [x] #1449

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1450)

### CODE REVIEW

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1450#-:-MrThMVREsvRqieVrhgj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1450#-:-MrWOuKx2-3Vt5yehd7D:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
Rebased

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1450#-:-Mrg0w6ECkl1NX6iFMdG:b9x2p3v)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1450)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
