### PR TITLE
examples: run all examples with fault injection

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #1815

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1816)

### CODE REVIEW

**Review by osalyk — APPROVED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1816)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1816)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[`examples/run-all-examples.sh` line 17 at r2](https://reviewable.io/reviews/pmem/rpma/1816#-N41wRcE5Y3QWnxXyvG5:-N41wRcE5Y3QWnxXyvG6:b-i1uqnq) ([raw file](https://github.com/pmem/rpma/blob/40a613655fd9ab1b1ae479dd40c5793d46aab051/examples/run-all-examples.sh#L17)):*
> ```Shell
> TIMEOUT=3s
> 
> IP_ADDRESS=
> ```

do we need this if we have below:
```
IP_ADDRESS=$2
PORT=$3
```



_Code quote:_
```Shell
IP_ADDRESS=
PORT=
```
___
*[`examples/run-all-examples.sh` line 32 at r2](https://reviewable.io/reviews/pmem/rpma/1816#-N41wmnnCfBwSFKztPqp:-N41wmnnCfBwSFKztPqq:undefined) ([raw file](https://github.com/pmem/rpma/blob/40a613655fd9ab1b1ae479dd40c5793d46aab051/examples/run-all-examples.sh#L32)):*
> ```Shell
> 
> IP_ADDRESS=$2
> PORT=$3
> ```





_Suggestion:_
```Shell
PORT=$3
if [ "$PORT" == "" ]; then
	PORT="7204"
fi
```
___
*[`examples/run-all-examples.sh` line 61 at r2](https://reviewable.io/reviews/pmem/rpma/1816#-N41y_EE6ePcMoSP53A9:-N41y_EE6ePcMoSP53AA:bdms16t) ([raw file](https://github.com/pmem/rpma/blob/40a613655fd9ab1b1ae479dd40c5793d46aab051/examples/run-all-examples.sh#L61)):*
> ```Shell
> C_LOG_FILE="nohup_client.out"
> 
> function print_out_log_file() {
> ```

where is it used?



_Code quote:_
```Shell
print_out_log_file()
```
___
*[`examples/run-all-examples.sh` line 156 at r2](https://reviewable.io/reviews/pmem/rpma/1816#-N41wsWXBPs86-iSlzqN:-N41wsWXBPs86-iSlzqO:bqx5qb) ([raw file](https://github.com/pmem/rpma/blob/40a613655fd9ab1b1ae479dd40c5793d46aab051/examples/run-all-examples.sh#L156)):*
> ```Shell
> 	fi
> 
> 	if [ "$PORT" == "" ]; then
> ```

It is not a part of SoftRoCE verification.
Let's move it to the beginning of the script.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1816)* status: 1 of 4 files reviewed, 4 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`examples/run-all-examples.sh` line 17 at r2](https://reviewable.io/reviews/pmem/rpma/1816#-N41wRcE5Y3QWnxXyvG5:-N41zV5C7IVjvx10QDAe:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/40a613655fd9ab1b1ae479dd40c5793d46aab051/examples/run-all-examples.sh#L17)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

do we need this if we have below:
```
IP_ADDRESS=$2
PORT=$3
```
</blockquote></details>

Done.
___
*[`examples/run-all-examples.sh` line 32 at r2](https://reviewable.io/reviews/pmem/rpma/1816#-N41wmnnCfBwSFKztPqp:-N41zabv0Fa87PpD5KAs:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/40a613655fd9ab1b1ae479dd40c5793d46aab051/examples/run-all-examples.sh#L32)):*
> ```Shell
> 
> IP_ADDRESS=$2
> PORT=$3
> ```

Done.
___
*[`examples/run-all-examples.sh` line 61 at r2](https://reviewable.io/reviews/pmem/rpma/1816#-N41y_EE6ePcMoSP53A9:-N41zlrU-1YcNdEyGx_o:b-rlgcay) ([raw file](https://github.com/pmem/rpma/blob/40a613655fd9ab1b1ae479dd40c5793d46aab051/examples/run-all-examples.sh#L61)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

where is it used?
</blockquote></details>

```
./examples/run-all-examples.sh:78:		print_out_log_file $LOG_FILE
./examples/run-all-examples.sh:257:			print_out_log_file ${BIN_DIR}/$EXAMPLE-valgrind-client.log
./examples/run-all-examples.sh:286:			print_out_log_file ${BIN_DIR}/$EXAMPLE-valgrind-server.log
```



_Code quote:_
```Shell
print_out_log_file
```
___
*[`examples/run-all-examples.sh` line 156 at r2](https://reviewable.io/reviews/pmem/rpma/1816#-N41wsWXBPs86-iSlzqN:-N41zyIXCHXVsYmRH70_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/40a613655fd9ab1b1ae479dd40c5793d46aab051/examples/run-all-examples.sh#L156)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

It is not a part of SoftRoCE verification.
Let's move it to the beginning of the script.
</blockquote></details>

Done.



_Code quote:_
```Shell
if
```

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1816)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @ldorau and @osalyk)

___
*[`examples/run-all-examples.sh` line 53 at r2](https://reviewable.io/reviews/pmem/rpma/1816#-N421pgD2GOPJ1s4pxjE:-N421pgE5rYEfxfH7OHW:b45h) ([raw file](https://github.com/pmem/rpma/blob/40a613655fd9ab1b1ae479dd40c5793d46aab051/examples/run-all-examples.sh#L53)):*
> ```Shell
> 	VLD_CCMD_ORIG=$VLD_CCMD
> 
> 	echo "Running examples with Valgrind is tuned for debug build of librpma on Ubuntu 20.04 (see the CircleCI build)."
> ```





_Suggestion:_
```Shell
22.04
```

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1816)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1816#-N42N57R189_km2MLzXb:-N42ZP3a-vw1u8JKYmVc:b6b35yl) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

What for? What do you want to achieve?

Splitting rather makes no sense. The current script can be modified a bit to be able to run only one of examples.
</blockquote></details>

Just for usability. We have already ``run_example()`` function. It should be easy to move this function  + some add-ons to separate file and make the main script ``run-all-examples.sh`` simpler.

___

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1816#-:-N42iq6vAduWhNlp52Yv:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1816)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1816)* status: all files reviewed, 7 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1816#-N42N57R189_km2MLzXb:-N46owmCChzV_O2UWrP_:bv1u6e3) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Now we have:
```sh
EXAMPLES=$(find $BIN_DIR -name server | sort)
for srv in $EXAMPLES; do
	DIR=$(dirname $srv)
	run_example $DIR
done
```
In order to run only one example, this:
```sh
EXAMPLES=$(find $BIN_DIR -name server | sort)
```
should be changed to that:
```sh
EXAMPLES="<one of examples>"
```
so it will not simplify it too much ;)
</blockquote></details>

I thought about the approach when you have run_example.sh script that runs only one example and run-all-examples.sh add only the logic to check soft-roce and the loop to run all examples

___
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1816#-N46pLqY8Wzi_QpMcmqj:-N46pLqY8Wzi_QpMcmqk:bty3dyt) (no related file):*
Is it possible to have a parameter to stop execution after the first fault?

___
___
*[`examples/run-all-examples.sh` line 11 at r8](https://reviewable.io/reviews/pmem/rpma/1816#-N46pWPWABvOZTaoaPKs:-N46pWPWABvOZTaoaPKt:b-odosyd) ([raw file](https://github.com/pmem/rpma/blob/306812ef0a0730aacfcb925ac9965da51a89e758/examples/run-all-examples.sh#L11)):*
> ```Shell
> #
> 
> # value used to get the maximum reachable value of fault injection for each example
> ```

can we move this part after ``### SCRIPT STARTS HERE ###``



_Code quote:_
```Shell
# value used to get the maximum reachable value of fault injection for each example
GET_FI_MAX=999999

# timeout value for both the server and the client
TIMEOUT=3s

BIN_DIR=$1

MODE="none"
if [ "$2" == "--valgrind" ]; then
	MODE="valgrind"
	shift
elif [ "$2" == "--fault-injection" ]; then
	MODE="fault-injection"
	shift
fi

IP_ADDRESS=$2
PORT=$3


if [ "$PORT" == "" ]; then
	PORT="7204"
fi
```
___
*[`examples/run-all-examples.sh` line 33 at r8](https://reviewable.io/reviews/pmem/rpma/1816#-N46pe385OX7BfUGxboJ:-N46pe385OX7BfUGxboK:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/306812ef0a0730aacfcb925ac9965da51a89e758/examples/run-all-examples.sh#L33)):*
> ```Shell
> fi
> 
> if [ "$MODE" == "valgrind" -o "$MODE" == "fault-injection" ]; then
> ```

.



_Code quote:_
```Shell
if [ "$MODE" == "valgrind" -o "$MODE" == "fault-injection" ]; then
	VLD_CMD="valgrind --leak-check=full"
	VLD_SUPP_PATH=$(dirname $0)/../tests/
	VLD_SUPP="--suppressions=${VLD_SUPP_PATH}/memcheck-libibverbs.supp"
	VLD_SUPP="${VLD_SUPP} --suppressions=${VLD_SUPP_PATH}/memcheck-libnl.supp"
	VLD_SUPP="${VLD_SUPP} --gen-suppressions=all"
	# prepare the server command
	VLD_SLOG_FILE="${BIN_DIR}/valgrind-server.log"
	VLD_SLOG="--log-file=${VLD_SLOG_FILE}"
	VLD_SCMD="${VLD_CMD} ${VLD_SUPP} ${VLD_SLOG}"
	# prepare the client command
	VLD_CLOG_FILE="${BIN_DIR}/valgrind-client.log"
	VLD_CLOG="--log-file=${VLD_CLOG_FILE}"
	VLD_CCMD="${VLD_CMD} ${VLD_SUPP} ${VLD_CLOG}"
	VLD_MSG="(under Valgrind)"
	# save the original values
	VLD_SCMD_ORIG=$VLD_SCMD
	VLD_CCMD_ORIG=$VLD_CCMD

	echo "Running examples with Valgrind is tuned for debug build of librpma on Ubuntu 22.04 (see the CircleCI build)."
	echo "It may fail for any other OS, OS version, rdma-core version and for the release build."
	echo
fi

S_LOG_FILE="nohup_server.out"
C_LOG_FILE="nohup_client.out"
```
___
*[`examples/run-all-examples.sh` line 206 at r8](https://reviewable.io/reviews/pmem/rpma/1816#-N46q9V5AoydtBUM8IHW:-N46q9V5AoydtBUM8IHX:bl97zio) ([raw file](https://github.com/pmem/rpma/blob/306812ef0a0730aacfcb925ac9965da51a89e758/examples/run-all-examples.sh#L206)):*
> ```Shell
> 	case $EXAMPLE in
> 	06-multiple-connections)
> 		[ "$MODE" != "fault-injection" ] && SEEDS="8 9 11 12" || SEEDS="8"
> ```

Please increase readability (if possible)
We either use a sequence of SEEDS or fault injection with one seed



_Suggestion:_
```Shell
[ "$MODE" == "fault-injection" ] && SEEDS="8" || SEEDS="8 9 11 12""
```
___
*[`examples/run-all-examples.sh` line 213 at r8](https://reviewable.io/reviews/pmem/rpma/1816#-N46qfKoDYK3QcikYuT6:-N46qfKoDYK3QcikYuT7:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/306812ef0a0730aacfcb925ac9965da51a89e758/examples/run-all-examples.sh#L213)):*
> ```Shell
> 		;;
> 	07-atomic-write)
> 		[ "$MODE" != "fault-injection" ] && WORDS="1st_word 2nd_word 3rd_word" || WORDS="1st_word"
> ```

.



_Code quote:_
```Shell
[ "$MODE" != "fault-injection" ] && WORDS="1st_word 2nd_word 3rd_word" || WORDS="1st_word"
```
___
*[`examples/run-all-examples.sh` line 218 at r8](https://reviewable.io/reviews/pmem/rpma/1816#-N46qhFF-zOpH5uFjO3T:-N46qhFF-zOpH5uFjO3U:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/306812ef0a0730aacfcb925ac9965da51a89e758/examples/run-all-examples.sh#L218)):*
> ```Shell
> 	08-messages-ping-pong)
> 		SEED=7
> 		[ "$MODE" != "fault-injection" ] && ROUNDS=3 || ROUNDS=1
> ```

.



_Code quote:_
```Shell
[ "$MODE" != "fault-injection" ] && ROUNDS=3 || ROUNDS=1
```
___
*[`examples/run-all-examples.sh` line 229 at r8](https://reviewable.io/reviews/pmem/rpma/1816#-N46qieR0jDsr4wtdbrj:-N46qieR0jDsr4wtdbrk:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/306812ef0a0730aacfcb925ac9965da51a89e758/examples/run-all-examples.sh#L229)):*
> ```Shell
> 	12-receive-completion-queue)
> 		START_VALUE=7
> 		[ "$MODE" != "fault-injection" ] && ROUNDS=3 || ROUNDS=1
> ```

.



_Code quote:_
```Shell
[ "$MODE" != "fault-injection" ] && ROUNDS=3 || ROUNDS=1
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1816)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1816#-N42N57R189_km2MLzXb:-N46srMHErzhV7ECKuc6:bm5bt4q) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I thought about the approach when you have run_example.sh script that runs only one example and run-all-examples.sh add only the logic to check soft-roce and the loop to run all examples
</blockquote></details>

`run_example.sh` would have to check SoftRoCE too, so `run-all-examples.sh` would add only the loop - so it would be exactly like above ...

___
___
*[`examples/run-all-examples.sh` line 11 at r8](https://reviewable.io/reviews/pmem/rpma/1816#-N46pWPWABvOZTaoaPKs:-N46tP0AC-Vc7QHCTDaJ:blh2l6) ([raw file](https://github.com/pmem/rpma/blob/306812ef0a0730aacfcb925ac9965da51a89e758/examples/run-all-examples.sh#L11)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

can we move this part after ``### SCRIPT STARTS HERE ###``
</blockquote></details>

IMHO setting the constants and using the command line arguments should be done at the beginning, because it helps understand how the script should be called.
___
*[`examples/run-all-examples.sh` line 33 at r8](https://reviewable.io/reviews/pmem/rpma/1816#-N46pe385OX7BfUGxboJ:-N46v-oP3x3wseUsjWBS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/306812ef0a0730aacfcb925ac9965da51a89e758/examples/run-all-examples.sh#L33)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`examples/run-all-examples.sh` line 206 at r8](https://reviewable.io/reviews/pmem/rpma/1816#-N46q9V5AoydtBUM8IHW:-N46vUZb-5uTWRPoJOoX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/306812ef0a0730aacfcb925ac9965da51a89e758/examples/run-all-examples.sh#L206)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Please increase readability (if possible)
We either use a sequence of SEEDS or fault injection with one seed
</blockquote></details>

Done.



_Code quote:_
```Shell
[ "$MODE" != "fault-injection" ] && SEEDS="8 9 11 12" || SEEDS="8"
```
___
*[`examples/run-all-examples.sh` line 213 at r8](https://reviewable.io/reviews/pmem/rpma/1816#-N46qfKoDYK3QcikYuT6:-N46vVHi14vxjIy6ZsqP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/306812ef0a0730aacfcb925ac9965da51a89e758/examples/run-all-examples.sh#L213)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`examples/run-all-examples.sh` line 218 at r8](https://reviewable.io/reviews/pmem/rpma/1816#-N46qhFF-zOpH5uFjO3T:-N46vVm85pp2ctIxW3zo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/306812ef0a0730aacfcb925ac9965da51a89e758/examples/run-all-examples.sh#L218)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`examples/run-all-examples.sh` line 229 at r8](https://reviewable.io/reviews/pmem/rpma/1816#-N46qieR0jDsr4wtdbrj:-N46vWVq5d0KRNJu1HC9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/306812ef0a0730aacfcb925ac9965da51a89e758/examples/run-all-examples.sh#L229)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1816)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1816#-N46pLqY8Wzi_QpMcmqj:-N46xTqD7jwF6e1i0YXj:b-896fix) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Is it possible to have a parameter to stop execution after the first fault?
</blockquote></details>

Done.

___

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1816)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`examples/run-all-examples.sh` line 127 at r11](https://reviewable.io/reviews/pmem/rpma/1816#-N471rvE-Kw6ZjY2zJz-:-N471rvE-Kw6ZjY2zJz0:undefined) ([raw file](https://github.com/pmem/rpma/blob/544a1d8675bc6d6a4e83f46a4d80a4533cf0db84/examples/run-all-examples.sh#L127)):*
> ```Shell
> 		echo "=========================================="
> 		echo
> 		[ $STOP_ON_FAILURE -eq 1 ] && exit 1
> ```





_Suggestion:_
```Shell
		if [ $STOP_ON_FAILURE -eq 1 ]; then
			cat $C_LOG_FILE
			exit 1
		fi
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1816)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`examples/run-all-examples.sh` line 127 at r11](https://reviewable.io/reviews/pmem/rpma/1816#-N471rvE-Kw6ZjY2zJz-:-N47AImp6fk_5gnqAvdK:b-d3wuy3) ([raw file](https://github.com/pmem/rpma/blob/544a1d8675bc6d6a4e83f46a4d80a4533cf0db84/examples/run-all-examples.sh#L127)):*
> ```Shell
> 		echo "=========================================="
> 		echo
> 		[ $STOP_ON_FAILURE -eq 1 ] && exit 1
> ```

No, the log has already been printed out in `run_example()`



_Code quote:_
```Shell
$STOP_ON_FAILURE -eq 1 ] 
```

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1816#-:-N47DyJJCSuueUORBQKw:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ldorau)

**Pull request merged**
