### PR TITLE
reports: CLX + MLX + CentOS 8.2 kernel 4.18

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1296)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1296)* status: 0 of 3 files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1296#-MkbAnp82Gsmruf7lq_d:-MkbAnp82Gsmruf7lq_e:b-kpjqcu) (no related file):*
Preview: https://janekmi.github.io/rpma/

---

**Comment by janekmi** [comment]
image

**Comment by janekmi** [comment]
image

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1296#-:-MkbDwEAEUNj-Iql0dF2:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1296)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[index.md, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/1296#-Mkgb9ET1LlwZGju-Flx:-Mkgb9ET1LlwZGju-Fly:bh8qi67) ([raw file](https://github.com/pmem/rpma/blob/49ef9a3ec7969ceb8696de26faba41660669664e/index.md#L17)):*
> ```
> Reports
> ```

reports
___
*[reports/index.md, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1296#-MkgbCDmAm2SlI65mZ-G:-MkgbCDmAm2SlI65mZ-H:bselhbi) ([raw file](https://github.com/pmem/rpma/blob/49ef9a3ec7969ceb8696de26faba41660669664e/reports/index.md#L2)):*
> ```
> Reports
> ```

.
___
*[reports/index.md, line 6 at r1](https://reviewable.io/reviews/pmem/rpma/1296#-MkgbEOU8JS_nbvWZp1T:-MkgbEOU8JS_nbvWZp1U:bselhbi) ([raw file](https://github.com/pmem/rpma/blob/49ef9a3ec7969ceb8696de26faba41660669664e/reports/index.md#L6)):*
> ```
> Reports
> ```

.

**Review by grom72 — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1296)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi)

___
*[index.md, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/1296#-MkgcWfE-41sPJqfo1qK:-MkgcWfE-41sPJqfo1qL:b-cy5yf2) ([raw file](https://github.com/pmem/rpma/blob/49ef9a3ec7969ceb8696de26faba41660669664e/index.md#L17)):*
> ```
> [Performance Reports]
> ```
Let's make this the section next to Recommended reading list
___
*[reports/index.md, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1296#-MkbC1ff5OzVacAb6ct_:-MkbC1ff5OzVacAb6cta:b-k1do5j) ([raw file](https://github.com/pmem/rpma/blob/49ef9a3ec7969ceb8696de26faba41660669664e/reports/index.md#L2)):*
> ```
> Performance Reports
> ```
Remote Persistent Memory Performance Reports

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1296)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi)

___
*[index.md, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/1296#-MkgcWfE-41sPJqfo1qK:-MkgjKvy9pKD-4920Rqo:bx429fj) ([raw file](https://github.com/pmem/rpma/blob/49ef9a3ec7969ceb8696de26faba41660669664e/index.md#L17)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> [Performance Reports]
> ```
Let's make this the section next to Recommended reading list
</blockquote></details>

The last section.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1296)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[index.md, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/1296#-Mkgb9ET1LlwZGju-Flx:-Mkgj4nM1TZ0L7A2PhEE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/49ef9a3ec7969ceb8696de26faba41660669664e/index.md#L17)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> Reports
> ```

reports
</blockquote></details>

Done.
___
*[index.md, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/1296#-MkgcWfE-41sPJqfo1qK:-Mkgk0VG7ZcAi1y78ohK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/49ef9a3ec7969ceb8696de26faba41660669664e/index.md#L17)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

The last section.
</blockquote></details>

Done.
___
*[reports/index.md, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1296#-MkgbCDmAm2SlI65mZ-G:-Mkgjn6VE2-ebg7CzUN5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/49ef9a3ec7969ceb8696de26faba41660669664e/reports/index.md#L2)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> Reports
> ```

.
</blockquote></details>

Done.
___
*[reports/index.md, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1296#-MkbC1ff5OzVacAb6ct_:-MkgkAUD7MS8yFGhmQ2o:b1vxe0e) ([raw file](https://github.com/pmem/rpma/blob/49ef9a3ec7969ceb8696de26faba41660669664e/reports/index.md#L2)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Performance Reports
> ```
Remote Persistent Memory Performance Reports
</blockquote></details>

Have you seen this?



You really prefer having something like:



I especially do not like having "Remote Persistent Memory" twice next to each other.
___
*[reports/index.md, line 6 at r1](https://reviewable.io/reviews/pmem/rpma/1296#-MkgbEOU8JS_nbvWZp1T:-MkgjoDm4vPX7qllMG4H:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/49ef9a3ec7969ceb8696de26faba41660669664e/reports/index.md#L6)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> Reports
> ```

.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1296)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1296)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1296#-:-MkkqxH572DlWCLs-DjX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1296)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
