### PR TITLE
common: rename run-all-on-SoftRoCE.sh to run-all-examples.sh

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1815)

### CODE REVIEW

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1815#-:-N41VqCuEj_UjDOdKJov:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1815#-:-N41tYsN4qZqKD0yoW6e:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1815)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`examples/README.md` line 15 at r1](https://reviewable.io/reviews/pmem/rpma/1815#-N41uKiG5iVUOnn-u2Eo:-N41uH8rAyyYRN8fK3e4:bla4yim) ([raw file](https://github.com/pmem/rpma/blob/4e063a6a65a576d791645e8787007cc9f9e7a1d3/examples/README.md#L15)):*
> ```Markdown
> 
> This directory contains also the 'run-all-examples.sh' script
> for running all examples on a configured RDMA-capable network interface
> ```

SHall we add here that it is either SoftRoCE or RDMA HW loopback?

**Review by grom72 — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1815)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1815)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @grom72 and @osalyk)

___
*[`examples/README.md` line 15 at r1](https://reviewable.io/reviews/pmem/rpma/1815#-N41uKiG5iVUOnn-u2Eo:-N41vacD-rKBb3xcY9fX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4e063a6a65a576d791645e8787007cc9f9e7a1d3/examples/README.md#L15)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

SHall we add here that it is either SoftRoCE or RDMA HW loopback?
</blockquote></details>

Done.

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1815#-:-N41vtvgAAVzgzEFvjuv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
