### PR TITLE
rpma: coherent message about pmem library used by examples

### PR DESCRIPTION
**Pull request by grom72**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1877)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1877)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1877)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`CMakeLists.txt` line 123 at r1](https://reviewable.io/reviews/pmem/rpma/1877#-N5eKPklCkO1HKHr5XsH:-N5eKPklCkO1HKHr5XsI:b-5ogpvd) ([raw file](https://github.com/pmem/rpma/blob/6375064d33360774a4cbbee5a0cc372805992469/CMakeLists.txt#L123)):*
> ```CMake
> 	endif()
> else()
> 	message(STATUS "libpmem will be used for examples that use PMem.")
> ```

if `(LIBPMEM_FOUND AND LIBPMEM2_FOUND)` then `libpmem2` should be used, not `libpmem`.



_Code quote:_
```CMake
message(STATUS "libpmem will be used for examples that use PMem.")
```

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1877)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`CMakeLists.txt` line 123 at r1](https://reviewable.io/reviews/pmem/rpma/1877#-N5eKPklCkO1HKHr5XsH:-N5eMEQ33O30OGo-WXu9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6375064d33360774a4cbbee5a0cc372805992469/CMakeLists.txt#L123)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

if `(LIBPMEM_FOUND AND LIBPMEM2_FOUND)` then `libpmem2` should be used, not `libpmem`.
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1877)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`CMakeLists.txt` line 123 at r2](https://reviewable.io/reviews/pmem/rpma/1877#-N5eMbNm4H3pmr5eK0ft:-N5eONhG8TIq7pwz4q-z:bwdkxy) ([raw file](https://github.com/pmem/rpma/blob/ae8eca70904f643e94a94105080a4fb88689fba1/CMakeLists.txt#L123)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

... but unfortunately it is not true yet, because most of examples do not have a support for libpmem2 yet, so this PR has to wait until all examples will support libpmem2 ...
</blockquote></details>

what about such a message?

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1877)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1877)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1877)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1877)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`CMakeLists.txt` line 123 at r2](https://reviewable.io/reviews/pmem/rpma/1877#-N5eMbNm4H3pmr5eK0ft:-N5j6pxd4FWICpKvA3PG:bbp2lzn) ([raw file](https://github.com/pmem/rpma/blob/ae8eca70904f643e94a94105080a4fb88689fba1/CMakeLists.txt#L123)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

what about such a message?
</blockquote></details>

We still do not know if libpmem is installed ...

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1877)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[`CMakeLists.txt` line 123 at r2](https://reviewable.io/reviews/pmem/rpma/1877#-N5eMbNm4H3pmr5eK0ft:-N5jGhKSEPcUWkKj-IxV:bt2vr1b) ([raw file](https://github.com/pmem/rpma/blob/ae8eca70904f643e94a94105080a4fb88689fba1/CMakeLists.txt#L123)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

We still do not know if libpmem is installed ...
</blockquote></details>

Fixed.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1877)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Pull request merged**
