### PR TITLE
doc: perf-tuning-latency DDIO

### PR DESCRIPTION
**Pull request by janekmi**
Preview: https://janekmi.github.io/rpma/

This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/598)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
Is there a preview available?

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/598#-:-MM_uF713X5KMKN4mT7u:brvnzei)* status: 1 of 2 files reviewed, all discussions resolved

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/598)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi)

___
*[documentation/basic-direct-write-to-pmem.md, line 8 at r1](https://reviewable.io/reviews/pmem/rpma/598#-MM_vDo4BFlDbP-tPbC6:-MM_vDo4BFlDbP-tPbC7:b6cdups) ([raw file](https://github.com/pmem/rpma/blob/562947520c083f191a6250c8f23016057388baf7/documentation/basic-direct-write-to-pmem.md#L8)):*
> ```
> RPMEM
> ```

`RPMEM` is it publicly known shortcut?
___
*[documentation/basic-direct-write-to-pmem.md, line 16 at r1](https://reviewable.io/reviews/pmem/rpma/598#-MM_vTbk5TPoZYIzZ4vZ:-MM_vTbk5TPoZYIzZ4v_:bi73c7r) ([raw file](https://github.com/pmem/rpma/blob/562947520c083f191a6250c8f23016057388baf7/documentation/basic-direct-write-to-pmem.md#L16)):*
> ```
> the user
> ```

`users`
___
*[documentation/basic-direct-write-to-pmem.md, line 28 at r1](https://reviewable.io/reviews/pmem/rpma/598#-MM_wjoK3_4coTd3HcHc:-MM_wjoK3_4coTd3HcHd:b69k1oi) ([raw file](https://github.com/pmem/rpma/blob/562947520c083f191a6250c8f23016057388baf7/documentation/basic-direct-write-to-pmem.md#L28)):*
> ```
> whereas -v display 
> ```

`whereas '-v' displays `
___
*[documentation/basic-direct-write-to-pmem.md, line 30 at r1](https://reviewable.io/reviews/pmem/rpma/598#-MM_w575DHxrWqohTRc9:-MM_w5768umLIyRyC8US:b-m09zbc) ([raw file](https://github.com/pmem/rpma/blob/562947520c083f191a6250c8f23016057388baf7/documentation/basic-direct-write-to-pmem.md#L30)):*
> ```
> https://github.com/janekmi/
> ```

remember to update this link
___
*[documentation/basic-direct-write-to-pmem.md, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/598#-MM_wQsw24pd1zvKzemu:-MM_wQsw24pd1zvKzemv:bfvj6oi) ([raw file](https://github.com/pmem/rpma/blob/562947520c083f191a6250c8f23016057388baf7/documentation/basic-direct-write-to-pmem.md#L39)):*
> ```
> for each system which PMem
> ```

`which` ? Maybe `with PMem` ?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/598)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @ldorau)

___
*[documentation/basic-direct-write-to-pmem.md, line 8 at r1](https://reviewable.io/reviews/pmem/rpma/598#-MM_vDo4BFlDbP-tPbC6:-MMa-LKoCn6mQjwlyECh:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/562947520c083f191a6250c8f23016057388baf7/documentation/basic-direct-write-to-pmem.md#L8)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> RPMEM
> ```

`RPMEM` is it publicly known shortcut?
</blockquote></details>

Done.
___
*[documentation/basic-direct-write-to-pmem.md, line 16 at r1](https://reviewable.io/reviews/pmem/rpma/598#-MM_vTbk5TPoZYIzZ4vZ:-MM_yon686PP4H2aIGQH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/562947520c083f191a6250c8f23016057388baf7/documentation/basic-direct-write-to-pmem.md#L16)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> the user
> ```

`users`
</blockquote></details>

Done.
___
*[documentation/basic-direct-write-to-pmem.md, line 28 at r1](https://reviewable.io/reviews/pmem/rpma/598#-MM_wjoK3_4coTd3HcHc:-MM_yuWpCG8qMLiOxfAu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/562947520c083f191a6250c8f23016057388baf7/documentation/basic-direct-write-to-pmem.md#L28)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> whereas -v display 
> ```

`whereas '-v' displays `
</blockquote></details>

Done.
___
*[documentation/basic-direct-write-to-pmem.md, line 30 at r1](https://reviewable.io/reviews/pmem/rpma/598#-MM_w575DHxrWqohTRc9:-MM_z8AZ9b1heYdMabnw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/562947520c083f191a6250c8f23016057388baf7/documentation/basic-direct-write-to-pmem.md#L30)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> https://github.com/janekmi/
> ```

remember to update this link
</blockquote></details>

Done.
___
*[documentation/basic-direct-write-to-pmem.md, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/598#-MM_wQsw24pd1zvKzemu:-MM_zfTq-iTflESyn7G5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/562947520c083f191a6250c8f23016057388baf7/documentation/basic-direct-write-to-pmem.md#L39)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> for each system which PMem
> ```

`which` ? Maybe `with PMem` ?
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/598)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[documentation/basic-direct-write-to-pmem.md, line 28 at r1](https://reviewable.io/reviews/pmem/rpma/598#-MM_wjoK3_4coTd3HcHc:-MMa0OLm6O-2xNdFypum:b-u4fh2i) ([raw file](https://github.com/pmem/rpma/blob/562947520c083f191a6250c8f23016057388baf7/documentation/basic-direct-write-to-pmem.md#L28)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

displayS

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/598#-:-MMa1AtpDNggntimfR-w:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/598)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/598#-:-MMa21xG3Mr2d9FMhHhg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
