### PR TITLE
examples: fix running the 08-messages-ping-pong example on SoftRoCE

### PR DESCRIPTION
**Pull request by ldorau**
Start the client of the `08-messages-ping-pong` example only once.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/352)

### CODE REVIEW

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/352#-:-MGNaArJEbXOlPNTZiih:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/352#-:-MGNwflaCiwPCrI9dpim:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/352)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
@janekmi ping

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/352#-:-MGhnliV97LHLOdqSksu:b-3p17t8)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
