### PR TITLE
examples: add common-pmem_map_file to example07

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1957)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1957)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1957)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi and @osalyk)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1957#-N83dq3jEfR4O0j7xoiE):*
Really? ;-)



_Code quote:_
```
and signature_check
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1957)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ldorau and @osalyk)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1957#-N83dq3jEfR4O0j7xoiE):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Really? ;-)
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1957)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1957#-:-N83h6FM9A-UsOh7IkkI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1957#-:-N83wH-87owIU0sjupfb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
