### PR TITLE
tools: Benchmark.run() unittests and docstring

### PR DESCRIPTION
**Pull request by janekmi**
Requires:

- [x] #1132 
- [x] #1130 

This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1129)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1129)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1129#-Mdv3qLI9shZ9iPiNLMI:-Mdv3qLI9shZ9iPiNLMJ:bymv1jp) (no related file):*
please rebase

---

**Review by ldorau — COMMENTED** [review]
> Reviewed 8 of 11 files at r4, 2 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1129)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1129)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1129)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/tests/lib/benchmark/test_run.py, line 102 at r7](https://reviewable.io/reviews/pmem/rpma/1129#-MdvbLhU6zB9D7SJVudt:-MdvbLhU6zB9D7SJVudu:b-qnfr1i) ([raw file](https://github.com/pmem/rpma/blob/15805793c8e7959630f24134f41970091ff6c26b/tools/perf/tests/lib/benchmark/test_run.py#L102)):*
> ```Python
>     ['bw-bs', 'bw-dp-exp', 'bw-dp-lin', 'bw-th', 'bw-cpu', 'bw-cpu-mt', 'lat',
>         'lat-cpu'])
> def test_rpma_fio_bench(tool_mode, readwrite, mode, monkeypatch):
> ```

Update test according to:
```
        if 'tool_mode' in self.oneseries.keys() and self.oneseries['tool_mode'] == 'gpspm':
            if 'busy_wait_polling' not in self.oneseries:
                raise ValueError
```

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1129)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1129)* status: 8 of 11 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/tests/lib/benchmark/test_run.py, line 102 at r7](https://reviewable.io/reviews/pmem/rpma/1129#-MdvbLhU6zB9D7SJVudt:-MdvcWLNCgy12slIzpmq:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/15805793c8e7959630f24134f41970091ff6c26b/tools/perf/tests/lib/benchmark/test_run.py#L102)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Update test according to:
```
        if 'tool_mode' in self.oneseries.keys() and self.oneseries['tool_mode'] == 'gpspm':
            if 'busy_wait_polling' not in self.oneseries:
                raise ValueError
```

</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 3 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1129)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1129)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1129#-Mdvo63w9HWeE1tyAhxj:-Mdvo63x5uA2DxiRRKvs:b-n6khor) (no related file):*
Please rebase

---

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1129)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1129#-Mdvo63w9HWeE1tyAhxj:-Mdvyyx10hanHqLGDOMz:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please rebase
</blockquote></details>

Done.

---

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1129#-:-MdwJmEf2eQ4OiN9xzPB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1129#-:-MdzbZjBCvdij3WPbs5h:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1129)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
