### PR TITLE
common: add a build with ASAN and UBSAN turned on

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #380 
- [x] #386 

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/309)

### CODE REVIEW

**Comment by ldorau** [comment]
The builds fail, because of https://github.com/pmem/rpma/issues/303

**Comment by ldorau** [comment]
The CI builds have passed! :-D

**Review by janekmi — COMMENTED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/309#-:-MGr0I7Y8ouTIegxJWgN:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by ldorau** [comment]
Rebased

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/309#-:-MGsHI2pCcnF6AHyMMS7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
