### PR TITLE
tools: improve setting dumping commands

### PR DESCRIPTION
**Pull request by ldorau**
Depends on:
- [x] #1446 
- [x] #1447

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1449)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1449)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1449#-:-MrSW1wW3qzKOpm0Wzqe:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1449)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1449)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1449#-:-MrWOoaW43Ml2_-CayPO:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1449#-:-MravUOPCYY1Fh0hDfok:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
