### PR TITLE
test: add rpma_conn_cfg_get_rq_size multithreaded test

### PR DESCRIPTION
**Pull request by ewanglong**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1102)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1102)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

___
*[tests/multithreaded/conn/rpma_conn_cfg_get_rq_size.c, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1102#-Mcxga2v5ETFZjiDmyZR:-Mcxga2v5ETFZjiDmyZS:bsgtt62) ([raw file](https://github.com/pmem/rpma/blob/35267565e37caeabe9dfb29efead968dac10d3fa/tests/multithreaded/conn/rpma_conn_cfg_get_rq_size.c#L13)):*
> ```
> Q_SIZE_EXP
> ```

Please add a comment that this is the EXPected value.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1102)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/conn/rpma_conn_cfg_get_rq_size.c, line 35 at r1](https://reviewable.io/reviews/pmem/rpma/1102#-Mcxl0PV0u3z9rNYROi-:-Mcxl0PW9VONfSZiPlPw:btuj9e7) ([raw file](https://github.com/pmem/rpma/blob/35267565e37caeabe9dfb29efead968dac10d3fa/tests/multithreaded/conn/rpma_conn_cfg_get_rq_size.c#L35)):*
> ```C
> 	if ((ret = rpma_conn_cfg_set_rq_size(pr->cfg_ptr, Q_SIZE_EXP)))
> 		MTT_RPMA_ERR(tr, "rpma_conn_cfg_set_rq_size", ret);
> }
> ```

Please make common parts common.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1102)* status: all files reviewed, 3 unresolved discussions (waiting on @ewanglong)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1102#-MdRqTWG9HOQzB1bMzTA:-MdRqTWH9viSZmQu2RsU:b-n6khor) (no related file):*
Please rebase

---

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1102)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1102#-MdRqTWG9HOQzB1bMzTA:-MdUo6dv1IelfSBORV3P:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please rebase
</blockquote></details>

Done.

---
___
*[tests/multithreaded/conn/rpma_conn_cfg_get_rq_size.c, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1102#-Mcxga2v5ETFZjiDmyZR:-MdUo9opDXB5PSE7nUFr:b-p6644u) ([raw file](https://github.com/pmem/rpma/blob/35267565e37caeabe9dfb29efead968dac10d3fa/tests/multithreaded/conn/rpma_conn_cfg_get_rq_size.c#L13)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> Q_SIZE_EXP
> ```

Please add a comment that this is the EXPected value.
</blockquote></details>

moved it to common header file.
___
*[tests/multithreaded/conn/rpma_conn_cfg_get_rq_size.c, line 35 at r1](https://reviewable.io/reviews/pmem/rpma/1102#-Mcxl0PV0u3z9rNYROi-:-MdUoDRc-FQgnO-B64bb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/35267565e37caeabe9dfb29efead968dac10d3fa/tests/multithreaded/conn/rpma_conn_cfg_get_rq_size.c#L35)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please make common parts common.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1102#-:-MdVRtK9A5i2-WAszWsg:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1102)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

___
*[tests/multithreaded/conn/rpma_conn_cfg_get_rq_size.c, line 22 at r2](https://reviewable.io/reviews/pmem/rpma/1102#-MdVh3vw4c2ZWwpftLeX:-MdVh3vw4c2ZWwpftLeY:b-sc901q) ([raw file](https://github.com/pmem/rpma/blob/1c75c383ce46b37d4f7ca844b8e1d2409acaa1ad/tests/multithreaded/conn/rpma_conn_cfg_get_rq_size.c#L22)):*
> ```C
> {
> 	struct rpma_conn_cfg_common_prestate *pr =
> 	(struct rpma_conn_cfg_common_prestate *)prestate;
> ```

Indentation +1

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1102)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[tests/multithreaded/conn/rpma_conn_cfg_get_rq_size.c, line 22 at r2](https://reviewable.io/reviews/pmem/rpma/1102#-MdVh3vw4c2ZWwpftLeX:-MdVifPe7_A6EN9B-ChR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1c75c383ce46b37d4f7ca844b8e1d2409acaa1ad/tests/multithreaded/conn/rpma_conn_cfg_get_rq_size.c#L22)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Indentation +1
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1102)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1102#-:-MdXDfLt8XWcCRpgwGSn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Review by janekmi — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1102)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1102)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1102)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Pull request merged**
