### PR TITLE
tools: ib_read.py, fio.py - add DUMP_CMDS for a client and a server

### PR DESCRIPTION
**Pull request by haichangsi**
---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1418)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1418)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
I do not see any value from separate log and error files.
Users must merge information manually by having two separate files.

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1418#-:-Mr18L5z284HwamU6DJR:bsblmwz)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @grom72 and @ldorau)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1418)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72, @haichangsi, and @ldorau)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 204 at r1](https://reviewable.io/reviews/pmem/rpma/1418#-Mr18_bv6aj5hahZSbNx:-Mr18_bv6aj5hahZSbNy:bo0hqgq) ([raw file](https://github.com/pmem/rpma/blob/c8e109c276c5530f6bf7b02791a2df237b847654/tools/perf/lib/benchmark/runner/ib_read.py#L204)):*
> ```Python
>         time_stamp = datetime.now().strftime("%Y-%m-%d-%H:%M:%S.%f")
>         name = '/tmp/ib_read_{}-{}'.format(self.__mode, time_stamp)
>         self.__settings['errfile_server'] = name + '-server.err'
> ```

only one log file per each server/client



_Code quote:_
```Python
        self.__settings['errfile_server'] = name + '-server.err'
        self.__settings['errfile_client'] = name + '-client.err'
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1418)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

**Review by haichangsi — COMMENTED** [review]
done

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1418#-:-Mr6gUh--amr1rW9LKav:bb7f2mf)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 204 at r1](https://reviewable.io/reviews/pmem/rpma/1418#-Mr18_bv6aj5hahZSbNx:-Mr6gWwC1F3NIYj5_41Y:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c8e109c276c5530f6bf7b02791a2df237b847654/tools/perf/lib/benchmark/runner/ib_read.py#L204)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

only one log file per each server/client
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1418)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 57 at r2](https://reviewable.io/reviews/pmem/rpma/1418#-Mr6kPjhAxG6iHZhBLOu:-Mr6kPjhAxG6iHZhBLOv:b-4c4e6z) ([raw file](https://github.com/pmem/rpma/blob/ca7a9b9040028381c5d235ebabab81cab0b00126/tools/perf/lib/benchmark/runner/ib_read.py#L57)):*
> ```
> dump_cmds
> ```

Please use `__dump_cmds` to make it private.
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 227 at r2](https://reviewable.io/reviews/pmem/rpma/1418#-Mr6lD9o1TX2_TGupc8F:-Mr6lD9o1TX2_TGupc8G:bgvpzdz) ([raw file](https://github.com/pmem/rpma/blob/ca7a9b9040028381c5d235ebabab81cab0b00126/tools/perf/lib/benchmark/runner/ib_read.py#L227)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
>         # clearing log files
>         with open(self.__settings['logfile_server']) as log_server, \
>             open(self.__settings['logfile_client']) as log_client:
>             log_server.truncate(0)
>             log_client.truncate(0)
> ```
</details>


It is not needed, because the names of the files are unique, so the log files do not exist yet in this place.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1418)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1418#-Mr6lpo01dTbClvhpdxN:-Mr6lpo17olutqFntmAd:bkk0mb8) (no related file):*
Please add the same to fio.py in this PR (and change name of commit and PR)

---

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1418)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1418#-Mr6lpo01dTbClvhpdxN:-Mr6psXs3ntg-aHtp6uv:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please add the same to fio.py in this PR (and change name of commit and PR)
</blockquote></details>

Done.

---
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 57 at r2](https://reviewable.io/reviews/pmem/rpma/1418#-Mr6kPjhAxG6iHZhBLOu:-Mr6pa9r5AfreNU7_MqL:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ca7a9b9040028381c5d235ebabab81cab0b00126/tools/perf/lib/benchmark/runner/ib_read.py#L57)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> dump_cmds
> ```

Please use `__dump_cmds` to make it private.
</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 227 at r2](https://reviewable.io/reviews/pmem/rpma/1418#-Mr6lD9o1TX2_TGupc8F:-Mr6pbWe1XYMYAcYWbip:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ca7a9b9040028381c5d235ebabab81cab0b00126/tools/perf/lib/benchmark/runner/ib_read.py#L227)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>         # clearing log files
>         with open(self.__settings['logfile_server']) as log_server, \
>             open(self.__settings['logfile_client']) as log_client:
>             log_server.truncate(0)
>             log_client.truncate(0)
> ```

It is not needed, because the names of the files are unique, so the log files do not exist yet in this place.
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1418)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 216 at r3](https://reviewable.io/reviews/pmem/rpma/1418#-Mr714f76_627IyU-bPL:-Mr714f76_627IyU-bPM:b-enq8na) ([raw file](https://github.com/pmem/rpma/blob/aba120b33278c39338e5cbe8ef726f969c5d5d9e/tools/perf/lib/benchmark/runner/fio.py#L216)):*
> ```
> ['logfile_server']
> ```

client, not server
___
*[tools/perf/lib/benchmark/runner/fio.py, line 217 at r3](https://reviewable.io/reviews/pmem/rpma/1418#-Mr71IzYECIQKMwCdz-d:-Mr71IzZ1-ZbqIqPLNHm:bosw33k) ([raw file](https://github.com/pmem/rpma/blob/aba120b33278c39338e5cbe8ef726f969c5d5d9e/tools/perf/lib/benchmark/runner/fio.py#L217)):*
> ```
> "[server]$ 
> ```

.
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 197 at r3](https://reviewable.io/reviews/pmem/rpma/1418#-Mr70i6I7jLWck_3lQ9i:-Mr70i6I7jLWck_3lQ9j:bb8l8e3) ([raw file](https://github.com/pmem/rpma/blob/aba120b33278c39338e5cbe8ef726f969c5d5d9e/tools/perf/lib/benchmark/runner/ib_read.py#L197)):*
> ```
> """set names of errors and log files"""
> ```

Please leave as it was before:
```
"""set names of log files"""
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1418)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 216 at r3](https://reviewable.io/reviews/pmem/rpma/1418#-Mr714f76_627IyU-bPL:-Mr72s20-RvC64UC70cN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/aba120b33278c39338e5cbe8ef726f969c5d5d9e/tools/perf/lib/benchmark/runner/fio.py#L216)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> ['logfile_server']
> ```

client, not server
</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/runner/fio.py, line 217 at r3](https://reviewable.io/reviews/pmem/rpma/1418#-Mr71IzYECIQKMwCdz-d:-Mr72ro_4NoxqgmVat0b:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/aba120b33278c39338e5cbe8ef726f969c5d5d9e/tools/perf/lib/benchmark/runner/fio.py#L217)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> "[server]$ 
> ```

.
</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 197 at r3](https://reviewable.io/reviews/pmem/rpma/1418#-Mr70i6I7jLWck_3lQ9i:-Mr72rB587HWuGh4skn2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/aba120b33278c39338e5cbe8ef726f969c5d5d9e/tools/perf/lib/benchmark/runner/ib_read.py#L197)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> """set names of errors and log files"""
> ```

Please leave as it was before:
```
"""set names of log files"""
```

</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1418)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1418#-:-Mr72zDe0mZgIvJDFwQ8:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1418#-:-Mr7X62-5rIK5Ka0ENs8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1418)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
