### PR TITLE
tools: fix RemoteCmd

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1441)

### CODE REVIEW

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1441#-:-MrNOoue3tZd7sBigdQD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1441)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/lib/remote_cmd.py, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/1441#-MrNaHv3EvVCK2jBtRmp:-MrNaHv3EvVCK2jBtRmq:be86j72) ([raw file](https://github.com/pmem/rpma/blob/039ae0dd10ab4df37aa044f97d565bf61c72fab8/tools/perf/lib/remote_cmd.py#L20)):*
> ```Python
>     """run a command on a remote node over SSH"""
> 
>     def __init__(self, ssh_client, stdout, stderr, exit_status = None):
> ```

```
C: 20, 0: No space allowed around keyword argument assignment
    def __init__(self, ssh_client, stdout, stderr, exit_status = None):
                                                               ^ (bad-whitespace)
```



_Code quote:_
```Python
exit_status = None)
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1441)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/lib/remote_cmd.py, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/1441#-MrNaHv3EvVCK2jBtRmp:-MrNctj8CPXDzFbHwsmo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/039ae0dd10ab4df37aa044f97d565bf61c72fab8/tools/perf/lib/remote_cmd.py#L20)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
C: 20, 0: No space allowed around keyword argument assignment
    def __init__(self, ssh_client, stdout, stderr, exit_status = None):
                                                               ^ (bad-whitespace)
```
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1441)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[tools/perf/lib/remote_cmd.py, line 19 at r1](https://reviewable.io/reviews/pmem/rpma/1441#-MrNbpmI5iwrU6oCUvbY:-MrNbpmI5iwrU6oCUvbZ:bu16vkz) ([raw file](https://github.com/pmem/rpma/blob/039ae0dd10ab4df37aa044f97d565bf61c72fab8/tools/perf/lib/remote_cmd.py#L19)):*
> ```Python
> class RemoteCmd:
>     """run a command on a remote node over SSH"""
> ```

```
@property
    def exit_status(self):
        return self.__exit_status
@property
    def stderr(self):
        return self.__stderr
```
___
*[tools/perf/lib/remote_cmd.py, line 22 at r1](https://reviewable.io/reviews/pmem/rpma/1441#-MrNbGyFDbjC5yJmXzex:-MrNbGyFDbjC5yJmXzey:b-er74jq) ([raw file](https://github.com/pmem/rpma/blob/039ae0dd10ab4df37aa044f97d565bf61c72fab8/tools/perf/lib/remote_cmd.py#L22)):*
> ```Python
>     def __init__(self, ssh_client, stdout, stderr, exit_status = None):
>         self.__ssh_client = ssh_client
>         self.stdout = stdout
> ```

```__stdout```



_Code quote:_
```Python
stdout
```
___
*[tools/perf/lib/remote_cmd.py, line 23 at r1](https://reviewable.io/reviews/pmem/rpma/1441#-MrNbK_qDUBMBJ4NVeXf:-MrNbK_qDUBMBJ4NVeXg:b-g7sysd) ([raw file](https://github.com/pmem/rpma/blob/039ae0dd10ab4df37aa044f97d565bf61c72fab8/tools/perf/lib/remote_cmd.py#L23)):*
> ```Python
>         self.__ssh_client = ssh_client
>         self.stdout = stdout
>         self.stderr = stderr
> ```

```stderr```



_Code quote:_
```Python
stderr
```
___
*[tools/perf/lib/remote_cmd.py, line 24 at r1](https://reviewable.io/reviews/pmem/rpma/1441#-MrNbNoA4lww__M9yKZ7:-MrNbNoBD3cr_prS2atk:bde8b01) ([raw file](https://github.com/pmem/rpma/blob/039ae0dd10ab4df37aa044f97d565bf61c72fab8/tools/perf/lib/remote_cmd.py#L24)):*
> ```Python
>         self.stdout = stdout
>         self.stderr = stderr
>         self.exit_status = exit_status
> ```

```___exit_status```



_Code quote:_
```Python
exit_status
```
___
*[tools/perf/lib/remote_cmd.py, line 28 at r1](https://reviewable.io/reviews/pmem/rpma/1441#-MrNbRqaAxRT7dWLG-W8:-MrNbRqaAxRT7dWLG-W9:b-l81xak) ([raw file](https://github.com/pmem/rpma/blob/039ae0dd10ab4df37aa044f97d565bf61c72fab8/tools/perf/lib/remote_cmd.py#L28)):*
> ```Python
>     def wait(self) -> None:
>         """wait for the command to finish"""
>         self.exit_status = self.stdout.channel.recv_exit_status()
> ```

```self.__exit_status```



_Suggestion:_
```Python
self.exit_status
```
___
*[tools/perf/lib/remote_cmd.py, line 28 at r1](https://reviewable.io/reviews/pmem/rpma/1441#-MrNbYk714Ibjz5tLdIi:-MrNbYk87mVfV1pCrfIr:b-71huvv) ([raw file](https://github.com/pmem/rpma/blob/039ae0dd10ab4df37aa044f97d565bf61c72fab8/tools/perf/lib/remote_cmd.py#L28)):*
> ```Python
>     def wait(self) -> None:
>         """wait for the command to finish"""
>         self.exit_status = self.stdout.channel.recv_exit_status()
> ```

```self.__stddout.channel```



_Suggestion:_
```Python
self.stdout.channel
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1441)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1441)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1441)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1441)* status: all files reviewed, 6 unresolved discussions (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1441)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[tools/perf/lib/remote_cmd.py, line 19 at r1](https://reviewable.io/reviews/pmem/rpma/1441#-MrNbpmI5iwrU6oCUvbY:-MrNhG_j9yLBk9BK1pDM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/039ae0dd10ab4df37aa044f97d565bf61c72fab8/tools/perf/lib/remote_cmd.py#L19)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```
@property
    def exit_status(self):
        return self.__exit_status
@property
    def stderr(self):
        return self.__stderr
```
</blockquote></details>

Done.
___
*[tools/perf/lib/remote_cmd.py, line 22 at r1](https://reviewable.io/reviews/pmem/rpma/1441#-MrNbGyFDbjC5yJmXzex:-MrQtK-B-dYYPoRNBPR5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/039ae0dd10ab4df37aa044f97d565bf61c72fab8/tools/perf/lib/remote_cmd.py#L22)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```__stdout```
</blockquote></details>

Done.
___
*[tools/perf/lib/remote_cmd.py, line 23 at r1](https://reviewable.io/reviews/pmem/rpma/1441#-MrNbK_qDUBMBJ4NVeXf:-MrNhNUX77FxJtg4sy4U:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/039ae0dd10ab4df37aa044f97d565bf61c72fab8/tools/perf/lib/remote_cmd.py#L23)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```stderr```
</blockquote></details>

Done.
___
*[tools/perf/lib/remote_cmd.py, line 24 at r1](https://reviewable.io/reviews/pmem/rpma/1441#-MrNbNoA4lww__M9yKZ7:-MrNhW0DE09VO7uo4pH9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/039ae0dd10ab4df37aa044f97d565bf61c72fab8/tools/perf/lib/remote_cmd.py#L24)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```___exit_status```
</blockquote></details>

Done.
___
*[tools/perf/lib/remote_cmd.py, line 28 at r1](https://reviewable.io/reviews/pmem/rpma/1441#-MrNbRqaAxRT7dWLG-W8:-MrNhaIfAgwX3-CJmlcj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/039ae0dd10ab4df37aa044f97d565bf61c72fab8/tools/perf/lib/remote_cmd.py#L28)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```self.__exit_status```
</blockquote></details>

Done.
___
*[tools/perf/lib/remote_cmd.py, line 28 at r1](https://reviewable.io/reviews/pmem/rpma/1441#-MrNbYk714Ibjz5tLdIi:-MrNhbyi6RhNUy5SwiU6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/039ae0dd10ab4df37aa044f97d565bf61c72fab8/tools/perf/lib/remote_cmd.py#L28)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```self.__stddout.channel```
</blockquote></details>

Done.

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1441#-:-MrR-v-u0FSq5GVYw47E:bg7igkv)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1441)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[tools/perf/lib/remote_cmd.py, line 23 at r5](https://reviewable.io/reviews/pmem/rpma/1441#-MrRFzMH0TWn0GKRAOnV:-MrRFzMH0TWn0GKRAOnW:bthfbgc) ([raw file](https://github.com/pmem/rpma/blob/7963860cc2ca8ca298ba62a9a3cd3960889eed29/tools/perf/lib/remote_cmd.py#L23)):*
> ```Python
>     def exit_status(self):
>         """exit status from the process on the server"""
>         return self.__exit_status
> ```

Please move it after `def stderr(self):` to keep the order: stdout, stderr, exit_status.



_Code quote:_
```Python
    @property
    def exit_status(self):
        """exit status from the process on the server"""
        return self.__exit_status
```

**Review by ldorau — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1441#-:-MrRGEty-mMI-HoNOu0R:bdycpsm)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72 and @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1441#-:-MrRGsjQ9bAG3qk0gbIx:bnfp4nl)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1441#-:-MrRMy6sANXvEUMyQof8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1441)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
