### PR TITLE
examples: use the RPMA logging

### PR DESCRIPTION
**Pull request by janekmi**
Requires:
- [x] #277 
- [x] #278

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/279)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 5 of 44 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/279)* status: 5 of 44 files reviewed, 5 unresolved discussions (waiting on @janekmi)

___
*[src/conn.c, line 229 at r1](https://reviewable.io/reviews/pmem/rpma/279#-MF71b8oEOJv6GlK_3X4:-MF71b8oEOJv6GlK_3X5:b-re6cqp) ([raw file](https://github.com/pmem/rpma/blob/5bb8aa28581a43613adf5289c04cefbb1bcbd64d/src/conn.c#L229)):*
> ```C
> 		return RPMA_E_PROVIDER;
> 	}
> ```

notice/info required  about successful disconnect request
___
*[src/conn.c, line 439 at r1](https://reviewable.io/reviews/pmem/rpma/279#-MF72Vwg0EVGS3D_i_US:-MF72VwhDPEbSH3aPTrm:bkl4ahx) ([raw file](https://github.com/pmem/rpma/blob/5bb8aa28581a43613adf5289c04cefbb1bcbd64d/src/conn.c#L439)):*
> ```
> RPMA_E_NO_COMPLETION
> ```
RPMA_LOG_INFO/DEBUG about this situation
___
*[src/conn.c, line 445 at r1](https://reviewable.io/reviews/pmem/rpma/279#-MF72Q3D7Ewi3HZWAFTA:-MF72Q3D7Ewi3HZWAFTB:b-w1r4zx) ([raw file](https://github.com/pmem/rpma/blob/5bb8aa28581a43613adf5289c04cefbb1bcbd64d/src/conn.c#L445)):*
> ```
> RPMA_E_UNKNOWN
> ```
missing LOG_ERROR
___
*[src/conn.c, line 456 at r1](https://reviewable.io/reviews/pmem/rpma/279#-MF72EjU6iK31NsTJ6xo:-MF72EjU6iK31NsTJ6xp:bz6si0p) ([raw file](https://github.com/pmem/rpma/blob/5bb8aa28581a43613adf5289c04cefbb1bcbd64d/src/conn.c#L456)):*
> ```
> RPMA_E_NOSUPP
> ```
RPMA_LOG_WARNING about unsupported opcode
___
*[src/conn.c, line 463 at r1](https://reviewable.io/reviews/pmem/rpma/279#-MF71q_E95-iEhTb5gRe:-MF71q_F5hlqCmAnJzih:b-5ysks3) ([raw file](https://github.com/pmem/rpma/blob/5bb8aa28581a43613adf5289c04cefbb1bcbd64d/src/conn.c#L463)):*
> ```
> RPMA_LOG_INFO
> ```
RPMA_LOG_WARNING as this is something that we do not expect in normal execution

**Review by grom72 — COMMENTED** [review]
:goat: 

> Reviewed 4 of 44 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/279#-:-MF9WPU88W-zYGds-JeA:bdycpsm)* status: 9 of 44 files reviewed, 5 unresolved discussions (waiting on @janekmi)

___
*[examples/common/common-conn.c, line 5 at r1](https://reviewable.io/reviews/pmem/rpma/279#-MF9JN8q7j8rHAfLj5Q-:-MF9JN8q7j8rHAfLj5Q0:ba6lu6s) ([raw file](https://github.com/pmem/rpma/blob/5bb8aa28581a43613adf5289c04cefbb1bcbd64d/examples/common/common-conn.c#L5)):*
> ```
> common-conn.c
> ```
seems that this file could be removed in the near future as many of functions here have become trivial

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/279)* status: 2 of 32 files reviewed, 5 unresolved discussions (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/279#-MF9mN6T3eafmI7M21f0:-MF9mN6T3eafmI7M21f1:by1906i) (no related file):*
Please comment the library logging implementation in #278.

---
___
*[src/conn.c, line 229 at r1](https://reviewable.io/reviews/pmem/rpma/279#-MF71b8oEOJv6GlK_3X4:-MF9iM7b50a4dhG3T7Eg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5bb8aa28581a43613adf5289c04cefbb1bcbd64d/src/conn.c#L229)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

notice/info required  about successful disconnect request
</blockquote></details>

Done.
___
*[src/conn.c, line 439 at r1](https://reviewable.io/reviews/pmem/rpma/279#-MF72Vwg0EVGS3D_i_US:-MF9j1gy7eFI5EO-r5fe:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5bb8aa28581a43613adf5289c04cefbb1bcbd64d/src/conn.c#L439)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> RPMA_E_NO_COMPLETION
> ```
RPMA_LOG_INFO/DEBUG about this situation
</blockquote></details>

Done.
___
*[src/conn.c, line 445 at r1](https://reviewable.io/reviews/pmem/rpma/279#-MF72Q3D7Ewi3HZWAFTA:-MF9kXq_9UzMju_vBsre:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5bb8aa28581a43613adf5289c04cefbb1bcbd64d/src/conn.c#L445)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> RPMA_E_UNKNOWN
> ```
missing LOG_ERROR
</blockquote></details>

Done.
___
*[src/conn.c, line 456 at r1](https://reviewable.io/reviews/pmem/rpma/279#-MF72EjU6iK31NsTJ6xo:-MF9lbkm3sWET7NnGUJt:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5bb8aa28581a43613adf5289c04cefbb1bcbd64d/src/conn.c#L456)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> RPMA_E_NOSUPP
> ```
RPMA_LOG_WARNING about unsupported opcode
</blockquote></details>

Done.
___
*[src/conn.c, line 463 at r1](https://reviewable.io/reviews/pmem/rpma/279#-MF71q_E95-iEhTb5gRe:-MF9h69o6QCM2FWRjvZT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5bb8aa28581a43613adf5289c04cefbb1bcbd64d/src/conn.c#L463)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> RPMA_LOG_INFO
> ```
RPMA_LOG_WARNING as this is something that we do not expect in normal execution
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/279)* status: 2 of 35 files reviewed, all discussions resolved (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/279#-MF9mN6T3eafmI7M21f0:-MF9zVmK-SbV3wJrVZFY:b32wtd) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please comment the library logging implementation in #278.
</blockquote></details>

ok

---
___
*[src/conn.c, line 456 at r1](https://reviewable.io/reviews/pmem/rpma/279#-MF72EjU6iK31NsTJ6xo:-MF9zIcV9dv70T7sCqT5:b-r80psi) ([raw file](https://github.com/pmem/rpma/blob/5bb8aa28581a43613adf5289c04cefbb1bcbd64d/src/conn.c#L456)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Is it an error situation or network strange behavior -> warning?

**Review by osalyk — COMMENTED** [review]
> Reviewed 1 of 44 files at r1, 11 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/279)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi)

___
*[examples/06-multiple-connections/server.c, line 357 at r3](https://reviewable.io/reviews/pmem/rpma/279#-MFASQB-E1itXY9K4Swr:-MFASQB-E1itXY9K4Sws:bk29451) ([raw file](https://github.com/pmem/rpma/blob/f8aa10483a8cebaea745fcad22a5600f37418984/examples/06-multiple-connections/server.c#L357)):*
> ```C
> 	/* receive an incoming connection request */
> 	struct rpma_conn_req *req = NULL;
> 	int ret = rpma_ep_next_conn_req(svr->ep, &req);
> ```

if (function());
___
*[examples/06-multiple-connections/server.c, line 369 at r3](https://reviewable.io/reviews/pmem/rpma/279#-MFASa6g8rgpvEpKAycJ:-MFASa6g8rgpvEpKAycK:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/f8aa10483a8cebaea745fcad22a5600f37418984/examples/06-multiple-connections/server.c#L369)):*
> ```C
> 
> 	/* accept the connection request and obtain the connection object */
> 	ret = rpma_conn_req_connect(&req, NULL, &clnt->conn);
> ```

.
___
*[examples/06-multiple-connections/server.c, line 381 at r3](https://reviewable.io/reviews/pmem/rpma/279#-MFASeSQCrVfgVdcRdPX:-MFASeSQCrVfgVdcRdPY:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/f8aa10483a8cebaea745fcad22a5600f37418984/examples/06-multiple-connections/server.c#L381)):*
> ```C
> 	}
> 
> 	ret = client_add_to_epoll(clnt, svr->epoll);
> ```

.
___
*[examples/common/common-conn.c, line 48 at r3](https://reviewable.io/reviews/pmem/rpma/279#-MFAT9nk2OmBeSWovNZp:-MFAT9nk2OmBeSWovNZq:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/f8aa10483a8cebaea745fcad22a5600f37418984/examples/common/common-conn.c#L48)):*
> ```C
> 	/* allocate a page size aligned local memory pool */
> 	void *mem;
> 	int ret = posix_memalign(&mem, (size_t)pagesize, size);
> ```

.
___
*[examples/common/common-conn.c, line 99 at r3](https://reviewable.io/reviews/pmem/rpma/279#-MFATHyF8bpbS_GrEZb1:-MFATHyF8bpbS_GrEZb2:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/f8aa10483a8cebaea745fcad22a5600f37418984/examples/common/common-conn.c#L99)):*
> ```C
> 
> 	/* wait for the connection to establish */
> 	ret = rpma_conn_next_event(*conn_ptr, &conn_event);
> ```

.

**Review by ldorau — COMMENTED** [review]
:goat: 

> Reviewed 3 of 44 files at r1, 11 of 15 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/279#-:-MFAUbp79n0U6Cl57RvC:bdycpsm)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/279)* status: 12 of 14 files reviewed, 5 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[examples/06-multiple-connections/server.c, line 357 at r3](https://reviewable.io/reviews/pmem/rpma/279#-MFASQB-E1itXY9K4Swr:-MFAV84k04AXy9vCCSyc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f8aa10483a8cebaea745fcad22a5600f37418984/examples/06-multiple-connections/server.c#L357)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

if (function());
</blockquote></details>

Done.
___
*[examples/06-multiple-connections/server.c, line 369 at r3](https://reviewable.io/reviews/pmem/rpma/279#-MFASa6g8rgpvEpKAycJ:-MFAVHS343sSvO4gsK42:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f8aa10483a8cebaea745fcad22a5600f37418984/examples/06-multiple-connections/server.c#L369)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[examples/06-multiple-connections/server.c, line 381 at r3](https://reviewable.io/reviews/pmem/rpma/279#-MFASeSQCrVfgVdcRdPX:-MFAVJqJ4mQsG-5eGXQk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f8aa10483a8cebaea745fcad22a5600f37418984/examples/06-multiple-connections/server.c#L381)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[examples/common/common-conn.c, line 48 at r3](https://reviewable.io/reviews/pmem/rpma/279#-MFAT9nk2OmBeSWovNZp:-MFAVeRMDvBAnl30z_wv:b49dbh4) ([raw file](https://github.com/pmem/rpma/blob/f8aa10483a8cebaea745fcad22a5600f37418984/examples/common/common-conn.c#L48)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

.
</blockquote></details>

ret in this case is used for error printing.
___
*[examples/common/common-conn.c, line 99 at r3](https://reviewable.io/reviews/pmem/rpma/279#-MFATHyF8bpbS_GrEZb1:-MFAVvd9BFFTdB5MMRIA:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/f8aa10483a8cebaea745fcad22a5600f37418984/examples/common/common-conn.c#L99)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

.
</blockquote></details>

.

**Review by ldorau — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/279#-:-MFAWolm9eVPKrNntzKE:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/279#-:-MFAYnTt9U7Zyn9hvYxS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
