### PR TITLE
test: add rpma_conn_cfg_get/set_srq MT tests

### PR DESCRIPTION
**Pull request by osalyk**
- [x] #1616

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1955)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 53 of 53 files at r1, 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1955)* status: all files reviewed, 4 unresolved discussions (waiting on @osalyk)

___
*[`tests/drd.supp` line 475 at r2](https://reviewable.io/reviews/pmem/rpma/1955#-N7zBHRu1h7jJvGUyL55:-N7zBHRu1h7jJvGUyL56:b-xo7rcg) ([raw file](https://github.com/pmem/rpma/blob/31fb63aec1321f3956d067bf739227401d1d5afc/tests/drd.supp#L475)):*
> ```
>    fun:rpma_conn_cfg_get_srq
>    ...
> }
> ```

EOL at EOF is missing.



_Code quote:_
```
}
```
___
*[`tests/helgrind.supp` line 440 at r2](https://reviewable.io/reviews/pmem/rpma/1955#-N7zBbxE77ImPh45OjNu:-N7zBbxE77ImPh45OjNv:bhfxtx0) ([raw file](https://github.com/pmem/rpma/blob/31fb63aec1321f3956d067bf739227401d1d5afc/tests/helgrind.supp#L440)):*
> ```
> #
> # Occurs in traces of:
> # - rpma_conn_cfg_set_srq
> ```

Add the same for _get() please



_Code quote:_
```
# Occurs in traces of:
# - rpma_conn_cfg_set_srq
```
___
*[`tests/helgrind.supp` line 445 at r2](https://reviewable.io/reviews/pmem/rpma/1955#-N7zBUp-77fCHmhfEqk9:-N7zBUp-77fCHmhfEqkA:bhfxtx0) ([raw file](https://github.com/pmem/rpma/blob/31fb63aec1321f3956d067bf739227401d1d5afc/tests/helgrind.supp#L445)):*
> ```
>    Possible data race
>    Helgrind:Race
>    fun:rpma_conn_cfg_set_srq
> ```

Add the same for _get() please



_Code quote:_
```
fun:rpma_conn_cfg_set_srq
```
___
*[`tests/multithreaded/conn_cfg/rpma_conn_cfg_common.h` line 22 at r2](https://reviewable.io/reviews/pmem/rpma/1955#-N7zGERP8iO5mdqGoclH:-N7zGERP8iO5mdqGoclI:blpwn1u) ([raw file](https://github.com/pmem/rpma/blob/31fb63aec1321f3956d067bf739227401d1d5afc/tests/multithreaded/conn_cfg/rpma_conn_cfg_common.h#L22)):*
> ```objc
> 
> /* SRQ object */
> #define RPMA_SRQ_EXP (struct rpma_srq *)0xCD12
> ```

Why `_EXP` ? What does it mean?



_Code quote:_
```objc
RPMA_SRQ_EXP
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1955)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[`tests/drd.supp` line 475 at r2](https://reviewable.io/reviews/pmem/rpma/1955#-N7zBHRu1h7jJvGUyL55:-N7zIvjvAq6GAHBVjUtl:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/31fb63aec1321f3956d067bf739227401d1d5afc/tests/drd.supp#L475)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

EOL at EOF is missing.
</blockquote></details>

Done.
___
*[`tests/helgrind.supp` line 440 at r2](https://reviewable.io/reviews/pmem/rpma/1955#-N7zBbxE77ImPh45OjNu:-N7zIzfX68enrh32D5vt:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/31fb63aec1321f3956d067bf739227401d1d5afc/tests/helgrind.supp#L440)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Add the same for _get() please
</blockquote></details>

Done.
___
*[`tests/helgrind.supp` line 445 at r2](https://reviewable.io/reviews/pmem/rpma/1955#-N7zBUp-77fCHmhfEqk9:-N7zJ4tj3cbf6W7F11A8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/31fb63aec1321f3956d067bf739227401d1d5afc/tests/helgrind.supp#L445)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Add the same for _get() please
</blockquote></details>

Done.
___
*[`tests/multithreaded/conn_cfg/rpma_conn_cfg_common.h` line 22 at r2](https://reviewable.io/reviews/pmem/rpma/1955#-N7zGERP8iO5mdqGoclH:-N7zJQFjCQxHmSm2XASt:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/31fb63aec1321f3956d067bf739227401d1d5afc/tests/multithreaded/conn_cfg/rpma_conn_cfg_common.h#L22)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why `_EXP` ? What does it mean?
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 8 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1955)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1955)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[`tests/drd.supp` line 462 at r4](https://reviewable.io/reviews/pmem/rpma/1955#-N7zj94n1IpvJGDpGflt:-N7zj94n1IpvJGDpGflu:b7g5nbb) ([raw file](https://github.com/pmem/rpma/blob/8e8e6ac15077317a1b144c71c1e635ba49a4bd31/tests/drd.supp#L462)):*
> ```
> # Occurs in traces of:
> # - rpma_conn_cfg_set_srq
> # - rpma_conn_cfg_get_srq
> ```

They will be made thread-safe.



_Code quote:_
```
# - rpma_conn_cfg_set_srq
# - rpma_conn_cfg_get_srq
```
___
*[`tests/helgrind.supp` line 441 at r4](https://reviewable.io/reviews/pmem/rpma/1955#-N7zjH8YE3af9vjoOkLx:-N7zjH8YE3af9vjoOkLy:b7g5nbb) ([raw file](https://github.com/pmem/rpma/blob/8e8e6ac15077317a1b144c71c1e635ba49a4bd31/tests/helgrind.supp#L441)):*
> ```
> # Occurs in traces of:
> # - rpma_conn_cfg_set_srq
> # - rpma_conn_cfg_get_srq
> ```

They will be made thread-safe.



_Code quote:_
```
# - rpma_conn_cfg_set_srq
# - rpma_conn_cfg_get_srq
```

**Review by haichangsi — COMMENTED** [review]
What about the CHANGELOG? ;)

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1955#-:-N83Zxhe0242GUj55jMt:bojufka)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1955#-:-N83t1Zk2UJNRTRcvGDZ:bb6un1j)* status: 61 of 62 files reviewed, 2 unresolved discussions (waiting on @ldorau and @osalyk)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1955)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1955)* status: 51 of 62 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[`tests/drd.supp` line 462 at r4](https://reviewable.io/reviews/pmem/rpma/1955#-N7zj94n1IpvJGDpGflt:-N88CZMK9JlilR-wqVfK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8e8e6ac15077317a1b144c71c1e635ba49a4bd31/tests/drd.supp#L462)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

They will be made thread-safe.
</blockquote></details>

Done.
___
*[`tests/helgrind.supp` line 441 at r4](https://reviewable.io/reviews/pmem/rpma/1955#-N7zjH8YE3af9vjoOkLx:-N88CYjgEHrD-W9Dmp51:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8e8e6ac15077317a1b144c71c1e635ba49a4bd31/tests/helgrind.supp#L441)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

They will be made thread-safe.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 11 files at r6, 9 of 9 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1955)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1955)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1955#-N88mi3J5mL3agnM6WHn:-N88mi3J5mL3agnM6WHo:b-anfneg) (no related file):*
Waiting for #1616 to be merged.

___

**Review by ldorau — COMMENTED** [review]
As regards the following MT tests:

```
  - rpma_conn_cfg_get_srq
  - rpma_conn_cfg_set_srq
```

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1955#-:-N88myTW6MK0sNw1k1uT:ba437qz)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Review by Patryk717 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1955#-:-N89Y2Pf7fRmaVDlRxqe:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1955)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[`-- commits` line 28 at r7](https://reviewable.io/reviews/pmem/rpma/1955#-N8wYrsyAcOP9bU_x3eP):*
`test: add rpma_conn_cfg_get/set_srq MT tests`



_Code quote:_
```
common: add rpma_conn_cfg_get/set_srq MT tests
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1955)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1955#-N8xPGohBG8t-bG7QMoW:-N8xPGohBG8t-bG7QMoX:b-ni3tmb) (no related file):*
Rebase please.

___

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1955)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1955#-N8xPGohBG8t-bG7QMoW:-N9jdAVSEx2Bb0p_WPMt:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Rebase please.
</blockquote></details>

Done.

___
___
*[`-- commits` line 28 at r7](https://reviewable.io/reviews/pmem/rpma/1955#-N8wYrsyAcOP9bU_x3eP):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`test: add rpma_conn_cfg_get/set_srq MT tests`
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 55 of 55 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1955)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 5 of 9 files at r7, 23 of 55 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1955#-:-NA3E0S9DIEoysDy2dMY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1955)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1955)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[`CHANGELOG.md` line 49 at r8](https://reviewable.io/reviews/pmem/rpma/1955#-NA3NvdD4oiUGtPVOKxc:-NA3NvdD4oiUGtPVOKxd:b-2j55bp) ([raw file](https://github.com/pmem/rpma/blob/5383ca25f63d740eff1269117d60c1ece07a89ca/CHANGELOG.md#L49)):*
> ```Markdown
>   - rpma_peer_cfg_set_direct_write_to_pmem
>   - rpma_conn_cfg_get_srq
>   - rpma_conn_cfg_set_srq
> ```

Alphabetical order



_Code quote:_
```Markdown
  - rpma_conn_cfg_get_srq
  - rpma_conn_cfg_set_srq
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1955)* status: 61 of 62 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[`CHANGELOG.md` line 49 at r8](https://reviewable.io/reviews/pmem/rpma/1955#-NA3NvdD4oiUGtPVOKxc:-NA3Rk5-5W5NgtrhlGUL:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5383ca25f63d740eff1269117d60c1ece07a89ca/CHANGELOG.md#L49)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Alphabetical order
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1955)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1955)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
