### PR TITLE
tools: check if fio is present remotely

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1354)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1354)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 33 at r1](https://reviewable.io/reviews/pmem/rpma/1354#-MpQlLZa5SN4QQxOp6l3:-MpQlLZb9zOddpGrgLwF:b-qw06ab) ([raw file](https://github.com/pmem/rpma/blob/16df5d3120e87eb44ae3e740827405f6399b4f31/tools/perf/lib/benchmark/runner/fio.py#L33)):*
> ```Python
>                              .format(fio_local_path))
> 
>         cmd = ' '.join(['which', fio_local_path])
> ```

Please use `REMOTE_FIO_PATH` and os.path.join

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1354)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1354)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 33 at r1](https://reviewable.io/reviews/pmem/rpma/1354#-MpQlLZa5SN4QQxOp6l3:-MpQotZV3F84A1zCHv4u:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/16df5d3120e87eb44ae3e740827405f6399b4f31/tools/perf/lib/benchmark/runner/fio.py#L33)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please use `REMOTE_FIO_PATH` and os.path.join
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1354#-:-MpQsaPEDuIqlymkd8wo:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1354#-:-MpR2nir88yoACbQuKVQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
