### PR TITLE
tools: fix collect_results() when collecting mix workloads

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1451)

### CODE REVIEW

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1451#-:-Mraq1t30h2PjkjNHwlM:bg7igkv)* status: 0 of 1 files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1451)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1451)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @grom72 and @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1451)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/lib/figure/base.py, line 234 at r1](https://reviewable.io/reviews/pmem/rpma/1451#-MsA4z-HD44pt9MiAJxI:-MsA4z-HD44pt9MiAJxJ:bc8tugf) ([raw file](https://github.com/pmem/rpma/blob/5cd3ff02041ee4df2df10077f2e7daccd0a3af41/tools/perf/lib/figure/base.py#L234)):*
> ```Python
>             if isinstance(rows[0], list):
>                 # rows[0] has to be a dict
>                 # FioFormat.parse() arranges the results this way
> ```

```
                # rows[0] has to be a dict, but in case of fio results 
                # it is a list of two dicts, so we have to take only the proper one
```



_Code quote:_
```Python
                # rows[0] has to be a dict
                # FioFormat.parse() arranges the results this way
```
___
*[tools/perf/lib/figure/base.py, line 239 at r1](https://reviewable.io/reviews/pmem/rpma/1451#-MsA4rRq7UtAqb9X7ZPE:-MsA4rRq7UtAqb9X7ZPF:b122ndb) ([raw file](https://github.com/pmem/rpma/blob/5cd3ff02041ee4df2df10077f2e7daccd0a3af41/tools/perf/lib/figure/base.py#L239)):*
> ```Python
>                 else:
>                     rw_dir = 1
>                 for i, _ in enumerate(rows):
> ```

`for i in range(len(rows)):`



_Code quote:_
```Python
for i, _ in enumerate(rows):
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1451)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/lib/figure/base.py, line 234 at r1](https://reviewable.io/reviews/pmem/rpma/1451#-MsA4z-HD44pt9MiAJxI:-MsAM20LCW0yG2DMkCCH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5cd3ff02041ee4df2df10077f2e7daccd0a3af41/tools/perf/lib/figure/base.py#L234)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
                # rows[0] has to be a dict, but in case of fio results 
                # it is a list of two dicts, so we have to take only the proper one
```
</blockquote></details>

Done.
___
*[tools/perf/lib/figure/base.py, line 239 at r1](https://reviewable.io/reviews/pmem/rpma/1451#-MsA4rRq7UtAqb9X7ZPE:-MsAQC4OCVpRaD3wvtBL:b-ubjk3t) ([raw file](https://github.com/pmem/rpma/blob/5cd3ff02041ee4df2df10077f2e7daccd0a3af41/tools/perf/lib/figure/base.py#L239)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`for i in range(len(rows)):`
</blockquote></details>

This way pylint fails:
Consider using enumerate instead of iterating with range and len (consider-using-enumerate)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1451)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

___
*[tools/perf/lib/figure/base.py, line 239 at r1](https://reviewable.io/reviews/pmem/rpma/1451#-MsA4rRq7UtAqb9X7ZPE:-MsAUsGM-mETXC3MQ72j:b32w0x) ([raw file](https://github.com/pmem/rpma/blob/5cd3ff02041ee4df2df10077f2e7daccd0a3af41/tools/perf/lib/figure/base.py#L239)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

This way pylint fails:
Consider using enumerate instead of iterating with range and len (consider-using-enumerate)
</blockquote></details>

OK

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1451#-:-MsAUvOr0ZSOpuUit4Xo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
