### PR TITLE
doc: librpma.7: thread safety

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/517)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/517)* status: 0 of 1 files reviewed, 1 unresolved discussion

*[a discussion](https://reviewable.io/reviews/pmem/rpma/517#-MIY2uneD44Lu9rZE7n3:-MIY2uneD44Lu9rZE7n4:b-2c7dft) (no related file):*
I also want, in the next step, add to each manual a paragraph either:

> This function is considered not thread-safe. For details please see librpma(7) manual page.

or:

> This function is thread-safe. For details please see librpma(7) manual page.

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/517)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 259 at r1](https://reviewable.io/reviews/pmem/rpma/517#-MIY4xEG1q2_iNCTlluS:-MIY4xEG1q2_iNCTlluT:b-f5kbnf) ([raw file](https://github.com/pmem/rpma/blob/e0c2dc28c9c530f1e38177bd7f1b5f60487b60ef/src/include/librpma.h#L259)):*
<details><summary><i alt="summary">Quoted 15 lines of code…</i></summary>

> ```
>  * - rpma_conn_apply_remote_peer_cfg
>  * - rpma_conn_get_private_data
>  * - rpma_conn_next_completion
>  * - rpma_conn_next_event
>  * - rpma_conn_prepare_completions
>  * - rpma_flush
>  * - rpma_mr_remote_delete
>  * - rpma_mr_remote_from_descriptor
>  * - rpma_mr_remote_get_flush_type
>  * - rpma_mr_remote_get_size
>  * - rpma_read
>  * - rpma_recv
>  * - rpma_send
>  * - rpma_write
>  * - rpma_write_atomic
> ```
</details>


brackets missing

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/517)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/517#-MIY2uneD44Lu9rZE7n3:-MIY5ALL8P4MFpaS-9we:b-wpgvw0) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I also want, in the next step, add to each manual a paragraph either:

> This function is considered not thread-safe. For details please see librpma(7) manual page.

or:

> This function is thread-safe. For details please see librpma(7) manual page.
</blockquote></details>

:+1: 

`is considered AS not thread-safe`

---

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/517)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[src/include/librpma.h, line 259 at r1](https://reviewable.io/reviews/pmem/rpma/517#-MIY4xEG1q2_iNCTlluS:-MIYDnMKB-D_dMXJ3UgA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e0c2dc28c9c530f1e38177bd7f1b5f60487b60ef/src/include/librpma.h#L259)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  * - rpma_conn_apply_remote_peer_cfg
>  * - rpma_conn_get_private_data
>  * - rpma_conn_next_completion
>  * - rpma_conn_next_event
>  * - rpma_conn_prepare_completions
>  * - rpma_flush
>  * - rpma_mr_remote_delete
>  * - rpma_mr_remote_from_descriptor
>  * - rpma_mr_remote_get_flush_type
>  * - rpma_mr_remote_get_size
>  * - rpma_read
>  * - rpma_recv
>  * - rpma_send
>  * - rpma_write
>  * - rpma_write_atomic
> ```

brackets missing
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/517)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 232 at r2](https://reviewable.io/reviews/pmem/rpma/517#-MIYGdBF8dqQTcL85QEc:-MIYGdBF8dqQTcL85QEd:bhwvmf4) ([raw file](https://github.com/pmem/rpma/blob/899d91720617ec0d1bafc0bba509bbfc818ffff0/src/include/librpma.h#L232)):*
> ```
>  * THREAD SAFETY
>  * The librpma API is divided into stages:
> ```

The header is blending with the description and is less visible.
IMHO with one empty line it would look much better.
I would change it in all places...

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/517)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 232 at r2](https://reviewable.io/reviews/pmem/rpma/517#-MIYHPLX94rFuQwqPuXr:-MIYHPLX94rFuQwqPuXs:bpjltpx) ([raw file](https://github.com/pmem/rpma/blob/899d91720617ec0d1bafc0bba509bbfc818ffff0/src/include/librpma.h#L232)):*
> ```
> into stages:
> ```

`into two stages:`

or:

`into the following stages:`
___
*[src/include/librpma.h, line 236 at r2](https://reviewable.io/reviews/pmem/rpma/517#-MIYH_NH8RQZYrrXX7Y9:-MIYH_NI0ba2ZQrKRkCp:brg2kfa) ([raw file](https://github.com/pmem/rpma/blob/899d91720617ec0d1bafc0bba509bbfc818ffff0/src/include/librpma.h#L236)):*
> ```
> object.
> ```

object and

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/517)* status: all files reviewed, 7 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 234 at r2](https://reviewable.io/reviews/pmem/rpma/517#-MIYI-TB9aLKItdT59QE:-MIYI-TB9aLKItdT59QF:bwcu5px) ([raw file](https://github.com/pmem/rpma/blob/899d91720617ec0d1bafc0bba509bbfc818ffff0/src/include/librpma.h#L234)):*
> ```
>  from a single
>  * dedicated application thread at a time.
> ```

` from a single dedicated thread at the time`
___
*[src/include/librpma.h, line 235 at r2](https://reviewable.io/reviews/pmem/rpma/517#-MIYINMACU3FpJgFWBQ9:-MIYINMB4uGJOe__4aU0:b-btqu8b) ([raw file](https://github.com/pmem/rpma/blob/899d91720617ec0d1bafc0bba509bbfc818ffff0/src/include/librpma.h#L235)):*
> ```
> These are all API calls which lead ...
> ```

`These API calls lead ...`
___
*[src/include/librpma.h, line 236 at r2](https://reviewable.io/reviews/pmem/rpma/517#-MIYIuH-7VNpPNbvhEJ-:-MIYIuH-7VNpPNbvhEJ0:bz60rzy) ([raw file](https://github.com/pmem/rpma/blob/899d91720617ec0d1bafc0bba509bbfc818ffff0/src/include/librpma.h#L236)):*
> ```objc
>  * - the initiation stage API calls which should be called from a single
>  * dedicated application thread at a time. These are all API calls which lead
>  * to the creation of the connection object.
> ```

```
The initiation stage API calls are:
...
...
...
```

?

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/517)* status: all files reviewed, 10 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 238 at r2](https://reviewable.io/reviews/pmem/rpma/517#-MIYXwVR14VFXfZLQQBh:-MIYXwVR14VFXfZLQQBi:bvljqf4) ([raw file](https://github.com/pmem/rpma/blob/899d91720617ec0d1bafc0bba509bbfc818ffff0/src/include/librpma.h#L238)):*
> ```
>  as single connection
> ```

 as a single connection
___
*[src/include/librpma.h, line 239 at r2](https://reviewable.io/reviews/pmem/rpma/517#-MIYY-UmARfMONGZaVTk:-MIYY-UmARfMONGZaVTl:bln4e9e) ([raw file](https://github.com/pmem/rpma/blob/899d91720617ec0d1bafc0bba509bbfc818ffff0/src/include/librpma.h#L239)):*
> ```
> * a time.
> ```

`* at the time.`
___
*[src/include/librpma.h, line 243 at r2](https://reviewable.io/reviews/pmem/rpma/517#-MIYY7DUCLyl46xnZN3z:-MIYY7DV8joR_7Ooi9Gp:b-h6ceqw) ([raw file](https://github.com/pmem/rpma/blob/899d91720617ec0d1bafc0bba509bbfc818ffff0/src/include/librpma.h#L243)):*
> ```
> are:
> ```

`are following:`

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/517)* status: 0 of 1 files reviewed, 11 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[src/include/librpma.h, line 236 at r3](https://reviewable.io/reviews/pmem/rpma/517#-MIYrEvR6rGtxdZf9SZR:-MIYrEvR6rGtxdZf9SZS:b-x2r2k8) ([raw file](https://github.com/pmem/rpma/blob/efeae98526ef9edd77a3da7450fa9a23610760ad/src/include/librpma.h#L236)):*
> ```objc
>  * API calls:
>  *
>  * - rpma_conn_apply_remote_peer_cfg()
> ```

peer_cfg setters are not thread-safe ergo
peer_cfg getters are not thread-safe ergo
apply is not thread-safe.
___
*[src/include/librpma.h, line 244 at r3](https://reviewable.io/reviews/pmem/rpma/517#-MIYrU5fE4U8IpE2HZRh:-MIYrU5fE4U8IpE2HZRi:b-hdi0eh) ([raw file](https://github.com/pmem/rpma/blob/efeae98526ef9edd77a3da7450fa9a23610760ad/src/include/librpma.h#L244)):*
> ```objc
>  * - rpma_conn_cfg_set_rq_size()
>  * - rpma_conn_cfg_set_sq_size()
>  * - rpma_conn_cfg_set_timeout()
> ```

setters are using plain assignment ergo they are not thread-safe ergo
getters are not thread-safe neither
___
*[src/include/librpma.h, line 246 at r3](https://reviewable.io/reviews/pmem/rpma/517#-MIYrgEP0L8d_sll4von:-MIYrgEP0L8d_sll4voo:bpfwga6) ([raw file](https://github.com/pmem/rpma/blob/efeae98526ef9edd77a3da7450fa9a23610760ad/src/include/librpma.h#L246)):*
> ```objc
>  * - rpma_conn_cfg_set_timeout()
>  * - rpma_conn_delete()
>  * - rpma_conn_disconnect()
> ```

rdma_cm involved. Not yet proved to be thread-safe.
___
*[src/include/librpma.h, line 247 at r3](https://reviewable.io/reviews/pmem/rpma/517#-MIYrlnU-kWzojG00_hQ:-MIYrlnU-kWzojG00_hR:bfykge7) ([raw file](https://github.com/pmem/rpma/blob/efeae98526ef9edd77a3da7450fa9a23610760ad/src/include/librpma.h#L247)):*
> ```objc
>  * - rpma_conn_delete()
>  * - rpma_conn_disconnect()
>  * - rpma_conn_get_private_data()
> ```

The setting is not thread-safe ergo
getting is neither
___
*[src/include/librpma.h, line 254 at r3](https://reviewable.io/reviews/pmem/rpma/517#-MIYrvuv5aM6aDVUar3s:-MIYrvuv5aM6aDVUar3t:bpfwga6) ([raw file](https://github.com/pmem/rpma/blob/efeae98526ef9edd77a3da7450fa9a23610760ad/src/include/librpma.h#L254)):*
> ```objc
>  * - rpma_ep_listen()
>  * - rpma_ep_next_conn_req()
>  * - rpma_ep_shutdown()
> ```

rdma_cm involved. Not yet proved to be thread-safe.
___
*[src/include/librpma.h, line 255 at r3](https://reviewable.io/reviews/pmem/rpma/517#-MIYs1kRCyI-AREQzizO:-MIYs1kRCyI-AREQzizP:b-a8fjp2) ([raw file](https://github.com/pmem/rpma/blob/efeae98526ef9edd77a3da7450fa9a23610760ad/src/include/librpma.h#L255)):*
> ```objc
>  * - rpma_ep_next_conn_req()
>  * - rpma_ep_shutdown()
>  * - rpma_log_set_threshold()
> ```

Hm... maybe it is thread-safe. TBDiscussed.
___
*[src/include/librpma.h, line 259 at r3](https://reviewable.io/reviews/pmem/rpma/517#-MIYsBGrBBHX7xBZzk2w:-MIYsBGrBBHX7xBZzk2x:bqy80bp) ([raw file](https://github.com/pmem/rpma/blob/efeae98526ef9edd77a3da7450fa9a23610760ad/src/include/librpma.h#L259)):*
> ```objc
>  * - rpma_peer_cfg_get_descriptor_size()
>  * - rpma_peer_cfg_get_direct_write_to_pmem()
>  * - rpma_peer_cfg_set_direct_write_to_pmem()
> ```

Setter are not thread-safe ergo
getters are not thread-safe neither ergo
constructing a descriptor is not too
___
*[src/include/librpma.h, line 261 at r3](https://reviewable.io/reviews/pmem/rpma/517#-MIYsORvET8baCyablxP:-MIYsORvET8baCyablxQ:bpfwga6) ([raw file](https://github.com/pmem/rpma/blob/efeae98526ef9edd77a3da7450fa9a23610760ad/src/include/librpma.h#L261)):*
> ```objc
>  * - rpma_peer_cfg_set_direct_write_to_pmem()
>  * - rpma_utils_conn_event_2str()
>  * - rpma_utils_get_ibv_context()
> ```

rdma_cm involved. Not yet proved to be thread-safe.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/517)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/517#-MIY2uneD44Lu9rZE7n3:-MIYtBwTBIb2VPMJzgcA:b-u2f3mi) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

:+1: 

`is considered AS not thread-safe`

</blockquote></details>

After reconsideration... I revoke this idea.

---
___
*[src/include/librpma.h, line 232 at r2](https://reviewable.io/reviews/pmem/rpma/517#-MIYHPLX94rFuQwqPuXr:-MIYtNBI2TFKEZl8ujao:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/899d91720617ec0d1bafc0bba509bbfc818ffff0/src/include/librpma.h#L232)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> into stages:
> ```

`into two stages:`

or:

`into the following stages:`
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 234 at r2](https://reviewable.io/reviews/pmem/rpma/517#-MIYI-TB9aLKItdT59QE:-MIYtQ9V08Y2FWtwXWwv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/899d91720617ec0d1bafc0bba509bbfc818ffff0/src/include/librpma.h#L234)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  from a single
>  * dedicated application thread at a time.
> ```

` from a single dedicated thread at the time`

</blockquote></details>

Done.
___
*[src/include/librpma.h, line 235 at r2](https://reviewable.io/reviews/pmem/rpma/517#-MIYINMACU3FpJgFWBQ9:-MIYtOVv80Wq09yzLBj7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/899d91720617ec0d1bafc0bba509bbfc818ffff0/src/include/librpma.h#L235)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> These are all API calls which lead ...
> ```

`These API calls lead ...`
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 236 at r2](https://reviewable.io/reviews/pmem/rpma/517#-MIYH_NH8RQZYrrXX7Y9:-MIYtP8T4VRFlfJYxvUW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/899d91720617ec0d1bafc0bba509bbfc818ffff0/src/include/librpma.h#L236)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> object.
> ```

object and
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 236 at r2](https://reviewable.io/reviews/pmem/rpma/517#-MIYIuH-7VNpPNbvhEJ-:-MIYtQqf4dUqAnpy5mrP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/899d91720617ec0d1bafc0bba509bbfc818ffff0/src/include/librpma.h#L236)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
The initiation stage API calls are:
...
...
...
```

?
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 238 at r2](https://reviewable.io/reviews/pmem/rpma/517#-MIYXwVR14VFXfZLQQBh:-MIYtRhN5jNg6SZ3v3eo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/899d91720617ec0d1bafc0bba509bbfc818ffff0/src/include/librpma.h#L238)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  as single connection
> ```

 as a single connection
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 239 at r2](https://reviewable.io/reviews/pmem/rpma/517#-MIYY-UmARfMONGZaVTk:-MIYtSWj6rQ_JBHUUn-b:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/899d91720617ec0d1bafc0bba509bbfc818ffff0/src/include/librpma.h#L239)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> * a time.
> ```

`* at the time.`
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 243 at r2](https://reviewable.io/reviews/pmem/rpma/517#-MIYY7DUCLyl46xnZN3z:-MIYtTGPC_W2asDRtuvH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/899d91720617ec0d1bafc0bba509bbfc818ffff0/src/include/librpma.h#L243)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> are:
> ```

`are following:`
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/517)* status: 0 of 1 files reviewed, 10 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[src/include/librpma.h, line 262 at r4](https://reviewable.io/reviews/pmem/rpma/517#-MIYuFMv2pNylvM_K1Mr:-MIYuFMv2pNylvM_K1Ms:bhu2egm) ([raw file](https://github.com/pmem/rpma/blob/dafeed46bfeda2561eadd9fbacdb701787ad4389/src/include/librpma.h#L262)):*
> ```
> resources
> ```
RPMA library resources

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/517)* status: 0 of 1 files reviewed, 11 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[src/include/librpma.h, line 233 at r4](https://reviewable.io/reviews/pmem/rpma/517#-MIYuilE6eMCJRDb9MgT:-MIYuilE6eMCJRDb9MgU:bndcln5) ([raw file](https://github.com/pmem/rpma/blob/dafeed46bfeda2561eadd9fbacdb701787ad4389/src/include/librpma.h#L233)):*
> ```
> Most of the librpma API calls are thread-safe but there are also very important exemptions.
> ```
Most of the core librpma API calls are thread-safe. However, there are several functions listed below that are NOT thread-safe.
They are mainly related to connection setup (including configuration ) and connection shtdown handling.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/517)* status: 0 of 1 files reviewed, 11 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[src/include/librpma.h, line 255 at r3](https://reviewable.io/reviews/pmem/rpma/517#-MIYs1kRCyI-AREQzizO:-MIYxPaqDsdcCWXt2ye_:b-pwpfps) ([raw file](https://github.com/pmem/rpma/blob/efeae98526ef9edd77a3da7450fa9a23610760ad/src/include/librpma.h#L255)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Hm... maybe it is thread-safe. TBDiscussed.
</blockquote></details>

it does not change anything as ep_next_conn_req is not thread-safe - it means that all calls related to connection establish are not thread-safe in general

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/517)* status: 0 of 1 files reviewed, 10 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/include/librpma.h, line 255 at r3](https://reviewable.io/reviews/pmem/rpma/517#-MIYs1kRCyI-AREQzizO:-MIYyW8r9_3lt5ejdzzt:bm4pwgt) ([raw file](https://github.com/pmem/rpma/blob/efeae98526ef9edd77a3da7450fa9a23610760ad/src/include/librpma.h#L255)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

it does not change anything as ep_next_conn_req is not thread-safe - it means that all calls related to connection establish are not thread-safe in general
</blockquote></details>

This comment was related to rpma_log_set_threshold(). NVM.
___
*[src/include/librpma.h, line 233 at r4](https://reviewable.io/reviews/pmem/rpma/517#-MIYuilE6eMCJRDb9MgT:-MIYyVKI9IG6ZbYXGTPr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dafeed46bfeda2561eadd9fbacdb701787ad4389/src/include/librpma.h#L233)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Most of the librpma API calls are thread-safe but there are also very important exemptions.
> ```
Most of the core librpma API calls are thread-safe. However, there are several functions listed below that are NOT thread-safe.
They are mainly related to connection setup (including configuration ) and connection shtdown handling. 


</blockquote></details>

Done.
___
*[src/include/librpma.h, line 262 at r4](https://reviewable.io/reviews/pmem/rpma/517#-MIYuFMv2pNylvM_K1Mr:-MIYyPb8CkHRsFRJe17E:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dafeed46bfeda2561eadd9fbacdb701787ad4389/src/include/librpma.h#L262)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> resources
> ```
RPMA library resources
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/517)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/517)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[src/include/librpma.h, line 234 at r5](https://reviewable.io/reviews/pmem/rpma/517#-MIYzHhz4ZgodlcRLmU8:-MIYzHi-0Fm2LgRaQldB:b-txm58o) ([raw file](https://github.com/pmem/rpma/blob/94fbadf1e5bccb2351c1b9f813facfd14723ba55/src/include/librpma.h#L234)):*
> ```
> exemptions
> ```

`exceptions` is better IMHO
___
*[src/include/librpma.h, line 234 at r5](https://reviewable.io/reviews/pmem/rpma/517#-MIYzWM2-J_nkTFLqrwA:-MIYzWM2-J_nkTFLqrwB:by8wq3e) ([raw file](https://github.com/pmem/rpma/blob/94fbadf1e5bccb2351c1b9f813facfd14723ba55/src/include/librpma.h#L234)):*
> ```
> to connection ...
> ```

to the connection's ...
___
*[src/include/librpma.h, line 267 at r5](https://reviewable.io/reviews/pmem/rpma/517#-MIZ-QZ706ze8bH7oDQQ:-MIZ-QZ83xDF0ZyCWzxH:b-ry7q0j) ([raw file](https://github.com/pmem/rpma/blob/94fbadf1e5bccb2351c1b9f813facfd14723ba55/src/include/librpma.h#L267)):*
> ```
> It is up to the user to ...
> ```

`It is the user's responsibility to ...`

**Review by grom72 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/517#-:-MIZ5FOP09tcE9KHUL3N:bdycpsm)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/517)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[src/include/librpma.h, line 234 at r5](https://reviewable.io/reviews/pmem/rpma/517#-MIYzWM2-J_nkTFLqrwA:-MIZ5t8i3ZG0L1lGRDzr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/94fbadf1e5bccb2351c1b9f813facfd14723ba55/src/include/librpma.h#L234)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> to connection ...
> ```

to the connection's ...
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 267 at r5](https://reviewable.io/reviews/pmem/rpma/517#-MIZ-QZ706ze8bH7oDQQ:-MIZ68Lt0HqeGNMFh1j-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/94fbadf1e5bccb2351c1b9f813facfd14723ba55/src/include/librpma.h#L267)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> It is up to the user to ...
> ```

`It is the user's responsibility to ...`
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/517)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/517#-:-MIZ6stv4vgBJ0ZW5sHd:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/517#-:-MIZ761QB1RRMKBirs1i:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/517)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
