### PR TITLE
tools: report figures for rpma_write() + rpma_flush()

### PR DESCRIPTION
**Pull request by janekmi**
Requires:

- [x] #675

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/677)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/677)* status: 1 of 2 files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/677)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
Looks OK for now.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/677#-:-MOkmL7nDH1Qlvz_EaMd:bce4pgi)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/677)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/create_report_figures.sh, line 293 at r3](https://reviewable.io/reviews/pmem/rpma/677#-MOkx9Gj6T0M58axSoSf:-MOkx9Gj6T0M58axSoSg:blpiw6h) ([raw file](https://github.com/pmem/rpma/blob/d79fc698feff496e18e226ea8cbddac32f2a5e80/tools/create_report_figures.sh#L293)):*
> ```Shell
> fi
> 
> cd ..
> ```

new line at the EOF is missing

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/677)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/create_report_figures.sh, line 293 at r3](https://reviewable.io/reviews/pmem/rpma/677#-MOkx9Gj6T0M58axSoSf:-MOppeSIAyntaETSky_-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d79fc698feff496e18e226ea8cbddac32f2a5e80/tools/create_report_figures.sh#L293)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

new line at the EOF is missing
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/677)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/677#-:-MOprahpECo3HBW5WBmt:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/677#-:-MOpsG2EC9AAcQi_MoP4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/677)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
