### PR TITLE
rpma: implement rpma_mr_send()

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/307)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
There is no dependency from #306.

> Reviewed 5 of 5 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/307#-:-MFq43VnB-ar9CyeGYWP:bhhwwgd)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — COMMENTED** [review]
Other than that, so far so good. :+1: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/307#-:-MFq4gtTEY8g6nXOkEfw:bf1544b)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
Indeed :-) Rebased.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/307#-:-MG2KbbyBMqgTpLjdQK3:bld66lq)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/307#-:-MG2LuOV5gX8zGPO6PTB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm: 

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/307#-:-MG2RNqIAVrvi19LyCEv:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[tests/unit/mr/mr-send.c, line 5 at r3](https://reviewable.io/reviews/pmem/rpma/307#-MG2NnhZ6AZ6tgNb3Zk-:-MG2Nnh_5HYtvxn_cZzF:btbgxbk) ([raw file](https://github.com/pmem/rpma/blob/5360889a8d85b5c447be689991990cde6e319690/tests/unit/mr/mr-send.c#L5)):*
> ```
> mr-test-send.c
> ```
Just do not understand me wrong, but is there any common part that could be shared with mr_write tests?

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/307)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
