### PR TITLE
tools: introduce Python tools tests structure

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1121)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1121)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/CMakeLists.txt, line 7 at r1](https://reviewable.io/reviews/pmem/rpma/1121#-MdpCzEH-6LIlKPacwcP:-MdpCzEH-6LIlKPacwcQ:bqxqo25) ([raw file](https://github.com/pmem/rpma/blob/7ddaed18833afceaea959ba0fcb3bf7c9c91c417/tools/perf/CMakeLists.txt#L7)):*
> ```
> # XXX requires adding pytest to all CI images
> ```

Really? Why? `add_cstyle_pep8` adds only those files to `pylint` checks ...

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1121)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/CMakeLists.txt, line 7 at r1](https://reviewable.io/reviews/pmem/rpma/1121#-MdpCzEH-6LIlKPacwcP:-MdpRKLc9euDX72TvULU:b-51ezqc) ([raw file](https://github.com/pmem/rpma/blob/7ddaed18833afceaea959ba0fcb3bf7c9c91c417/tools/perf/CMakeLists.txt#L7)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> # XXX requires adding pytest to all CI images
> ```

Really? Why? `add_cstyle_pep8` adds only those files to `pylint` checks ...
</blockquote></details>

`pylint` checks dependencies. If you do not have `pytest` in this case it will be reported. 

```
$ pylint test_report_bench.py 
************* Module test_report_bench
test_report_bench.py:9:0: E0401: Unable to import 'pytest' (import-error)
```

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1121)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

___
*[tools/perf/CMakeLists.txt, line 7 at r1](https://reviewable.io/reviews/pmem/rpma/1121#-MdpCzEH-6LIlKPacwcP:-MdpVbCsDgOHqUYhBlt0:b32w0x) ([raw file](https://github.com/pmem/rpma/blob/7ddaed18833afceaea959ba0fcb3bf7c9c91c417/tools/perf/CMakeLists.txt#L7)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`pylint` checks dependencies. If you do not have `pytest` in this case it will be reported. 

```
$ pylint test_report_bench.py 
************* Module test_report_bench
test_report_bench.py:9:0: E0401: Unable to import 'pytest' (import-error)
```
</blockquote></details>

OK

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1121#-:-MdpVd4N0XTvF5GtZ8M4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1121#-:-MdpdwLODK2_fxzMafmT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1121)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
