### PR TITLE
common: fix all "message(NOTICE)" with "message(STATUS)"

### PR DESCRIPTION
**Pull request by ldorau**
Replace all "message(NOTICE)" with "message(STATUS)".
There is no "message(NOTICE)" command ...

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/461)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/461#-:-MIIXO081QudY7f8Uik6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/461#-:-MIIZi5ICeorBQda0igJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/461)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/461#-MIIcqR837oMs-GcFEbd:-MIIcqR837oMs-GcFEbe:b-3bpta8) (no related file):*
```
2020-09-28T06:08:02.2101276Z -- Performing Test ON_DEMAND_PAGING_SUPPORTED - Success
2020-09-28T06:08:02.2101964Z -- -- On-Demand Paging (ODP) in libibverbs supported - Success
```

Does it work as intended?

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/461)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @grom72, @janekmi, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/461#-MIIcqR837oMs-GcFEbd:-MIIfqcm56AZKtuT9SYs:btsjtrn) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```
2020-09-28T06:08:02.2101276Z -- Performing Test ON_DEMAND_PAGING_SUPPORTED - Success
2020-09-28T06:08:02.2101964Z -- -- On-Demand Paging (ODP) in libibverbs supported - Success
```

Does it work as intended?
</blockquote></details>

Not entirely ;-) Fixed.

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/461)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @grom72, @janekmi, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/461#-MIIcqR837oMs-GcFEbd:-MIIg2-40QQiiqpcyhPm:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not entirely ;-) Fixed.
</blockquote></details>

Done.

---

**Review by grom72 — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/461)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/461#-:-MIIw8cM6Vs2WWsUDLsY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
