### PR TITLE
tools: add configuration common, target and bios.excerpt to the preamble

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #1178 
- [x] #1179

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1180)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1180)* status: all files reviewed, 8 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/config.json.example, line 49 at r1](https://reviewable.io/reviews/pmem/rpma/1180#-MfnO_hl-G_ikO49LkmM:-MfnO_hl-G_ikO49LkmN:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/a8b3d76a871b98a2c2d9a713ba2eda384f15e758/tools/perf/config.json.example#L49)):*
> ```
>         "configuration" : {
>             "common": {
>                 "type": "kvtable",
> ```

.
___
*[tools/perf/config.json.example, line 95 at r1](https://reviewable.io/reviews/pmem/rpma/1180#-MfnNpvtAUSJcFEnxNYH:-MfnNpvtAUSJcFEnxNYI:b-jy4cze) ([raw file](https://github.com/pmem/rpma/blob/a8b3d76a871b98a2c2d9a713ba2eda384f15e758/tools/perf/config.json.example#L95)):*
> ```
>                     "Version 51mlnx1 Release 1.51258"
>                 ]
>             },
> ```

Too detailed. I think, for the sake of an example what we got here (please see the link) is enough.
I do not want to provide too many details just in case somebody will forget to adjust them to describe their own configuration.

Ref: https://github.com/pmem/rpma/blob/master/tools/perf/templates/configuration_common.md.copyme
___
*[tools/perf/config.json.example, line 97 at r1](https://reviewable.io/reviews/pmem/rpma/1180#-MfnOZi-ElEuAxXcNmUl:-MfnOZi-ElEuAxXcNmUm:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/a8b3d76a871b98a2c2d9a713ba2eda384f15e758/tools/perf/config.json.example#L97)):*
> ```
>             },
>             "target" : {
>                 "type": "kvtable",
> ```

.
___
*[tools/perf/config.json.example, line 107 at r1](https://reviewable.io/reviews/pmem/rpma/1180#-MfnOYNe0Pyu_6VcmqKk:-MfnOYNe0Pyu_6VcmqKl:b-1bypak) ([raw file](https://github.com/pmem/rpma/blob/a8b3d76a871b98a2c2d9a713ba2eda384f15e758/tools/perf/config.json.example#L107)):*
> ```
>                     "https://pmem.io/rpma/documentation/basic-direct-write-to-pmem.html"
>                 ]
>             },
> ```

Ref: https://github.com/pmem/rpma/blob/master/tools/perf/templates/configuration_target.md.copyme
___
*[tools/perf/config.json.example, line 110 at r1](https://reviewable.io/reviews/pmem/rpma/1180#-MfnObalCdsW5bTWbU08:-MfnObalCdsW5bTWbU09:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/a8b3d76a871b98a2c2d9a713ba2eda384f15e758/tools/perf/config.json.example#L110)):*
> ```
>             "bios": {
>                 "settings" : {
>                     "type": "kvtable",
> ```

.
___
*[tools/perf/config.json.example, line 120 at r1](https://reviewable.io/reviews/pmem/rpma/1180#-MfnOhFJ7gcuMvTaX_uh:-MfnOhFJ7gcuMvTaX_ui:b2jrpkm) ([raw file](https://github.com/pmem/rpma/blob/a8b3d76a871b98a2c2d9a713ba2eda384f15e758/tools/perf/config.json.example#L120)):*
> ```
>                         "https://pmem.io/rpma/documentation/perf-tuning.html"
>                     ]
>                 },
> ```

https://github.com/pmem/rpma/blob/master/tools/perf/templates/bios.md.copyme
___
*[tools/perf/config.json.example, line 122 at r1](https://reviewable.io/reviews/pmem/rpma/1180#-MfnOgi341wdSiFO6NOM:-MfnOgi341wdSiFO6NON:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/a8b3d76a871b98a2c2d9a713ba2eda384f15e758/tools/perf/config.json.example#L122)):*
> ```
>                 },
>                 "excerpt" : {
>                     "type": "kvtable",
> ```

.
___
*[tools/perf/config.json.example, line 156 at r1](https://reviewable.io/reviews/pmem/rpma/1180#-MfnOiy2675ft8oBxioJ:-MfnOiy2675ft8oBxioK:b2jrpkm) ([raw file](https://github.com/pmem/rpma/blob/a8b3d76a871b98a2c2d9a713ba2eda384f15e758/tools/perf/config.json.example#L156)):*
> ```
>                         "Disabled"
>                     ]
>                 }
> ```

https://github.com/pmem/rpma/blob/master/tools/perf/templates/bios.md.copyme

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1180)* status: 1 of 4 files reviewed, 8 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/config.json.example, line 49 at r1](https://reviewable.io/reviews/pmem/rpma/1180#-MfnO_hl-G_ikO49LkmM:-MfpwxQo8OtdTER0rHS_:brayyv2) ([raw file](https://github.com/pmem/rpma/blob/a8b3d76a871b98a2c2d9a713ba2eda384f15e758/tools/perf/config.json.example#L49)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

I do not understand what do you want me to do with this - just remove ?
___
*[tools/perf/config.json.example, line 95 at r1](https://reviewable.io/reviews/pmem/rpma/1180#-MfnNpvtAUSJcFEnxNYH:-Mfq01024tkSmt_Peg_K:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a8b3d76a871b98a2c2d9a713ba2eda384f15e758/tools/perf/config.json.example#L95)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Too detailed. I think, for the sake of an example what we got here (please see the link) is enough.
I do not want to provide too many details just in case somebody will forget to adjust them to describe their own configuration.

Ref: https://github.com/pmem/rpma/blob/master/tools/perf/templates/configuration_common.md.copyme

</blockquote></details>

Done.
___
*[tools/perf/config.json.example, line 107 at r1](https://reviewable.io/reviews/pmem/rpma/1180#-MfnOYNe0Pyu_6VcmqKk:-Mfq01zZ556NNqu4LvDv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a8b3d76a871b98a2c2d9a713ba2eda384f15e758/tools/perf/config.json.example#L107)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Ref: https://github.com/pmem/rpma/blob/master/tools/perf/templates/configuration_target.md.copyme
</blockquote></details>

Done.
___
*[tools/perf/config.json.example, line 120 at r1](https://reviewable.io/reviews/pmem/rpma/1180#-MfnOhFJ7gcuMvTaX_uh:-Mfq03ZWCRnDdwxFk3Rn:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a8b3d76a871b98a2c2d9a713ba2eda384f15e758/tools/perf/config.json.example#L120)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

https://github.com/pmem/rpma/blob/master/tools/perf/templates/bios.md.copyme
</blockquote></details>

Done.
___
*[tools/perf/config.json.example, line 156 at r1](https://reviewable.io/reviews/pmem/rpma/1180#-MfnOiy2675ft8oBxioJ:-Mfq04f33gNrLBp4jyAc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a8b3d76a871b98a2c2d9a713ba2eda384f15e758/tools/perf/config.json.example#L156)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

https://github.com/pmem/rpma/blob/master/tools/perf/templates/bios.md.copyme
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1180)* status: 1 of 4 files reviewed, 8 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/config.json.example, line 49 at r1](https://reviewable.io/reviews/pmem/rpma/1180#-MfnO_hl-G_ikO49LkmM:-Mfq5Acy31-jwpYmc5xK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a8b3d76a871b98a2c2d9a713ba2eda384f15e758/tools/perf/config.json.example#L49)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I do not understand what do you want me to do with this - just remove ?
</blockquote></details>

Done.
___
*[tools/perf/config.json.example, line 97 at r1](https://reviewable.io/reviews/pmem/rpma/1180#-MfnOZi-ElEuAxXcNmUl:-Mfq58Yg3djovcH9qpno:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a8b3d76a871b98a2c2d9a713ba2eda384f15e758/tools/perf/config.json.example#L97)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/config.json.example, line 110 at r1](https://reviewable.io/reviews/pmem/rpma/1180#-MfnObalCdsW5bTWbU08:-Mfq59JxAgEfZamk426W:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a8b3d76a871b98a2c2d9a713ba2eda384f15e758/tools/perf/config.json.example#L110)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/config.json.example, line 122 at r1](https://reviewable.io/reviews/pmem/rpma/1180#-MfnOgi341wdSiFO6NOM:-Mfq57gy4OsIX2kbkPtg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a8b3d76a871b98a2c2d9a713ba2eda384f15e758/tools/perf/config.json.example#L122)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, 1 of 2 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1180)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/lib/Part.py, line 20 at r4](https://reviewable.io/reviews/pmem/rpma/1180#-MfqK08X-l44UFXkNZnX:-MfqK08X-l44UFXkNZnY:b2no22l) ([raw file](https://github.com/pmem/rpma/blob/018b04f263e3f2d767b02daf717de5957fc1a497/tools/perf/lib/Part.py#L20)):*
> ```Python
>     """A single report object"""
> 
>     def process_variables_level(self, variables, common):
> ```

I think this function has the potential to go out of this module.
___
*[tools/perf/lib/Report.py, line 35 at r4](https://reviewable.io/reviews/pmem/rpma/1180#-MfqKCXW5gvKTHDcqfDt:-MfqKCXW5gvKTHDcqfDu:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/018b04f263e3f2d767b02daf717de5957fc1a497/tools/perf/lib/Report.py#L35)):*
> ```Python
>                 if 'excerpt' in variables['configuration']['bios']:
>                     if 'type' not in variables['configuration']['bios']['excerpt']:
>                         variables['configuration']['bios']['excerpt']['type'] = 'kvtable'
> ```

.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1180)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/Report.py, line 35 at r4](https://reviewable.io/reviews/pmem/rpma/1180#-MfqKCXW5gvKTHDcqfDt:-MfqXyYFEWvgFo0c2V6-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/018b04f263e3f2d767b02daf717de5957fc1a497/tools/perf/lib/Report.py#L35)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/lib/Part.py, line 20 at r4](https://reviewable.io/reviews/pmem/rpma/1180#-MfqK08X-l44UFXkNZnX:-MfqVfpj6r1IFNXsDQJ1:b-cqvu2g) ([raw file](https://github.com/pmem/rpma/blob/018b04f263e3f2d767b02daf717de5957fc1a497/tools/perf/lib/Part.py#L20)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think this function has the potential to go out of this module.
</blockquote></details>

OK, it is not a part of this PR.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1180#-:-MfqfE-U4F3L2BthFGPv:bnfp4nl)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1180#-:-MfqfkRJ0uwEUU74cffs:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
