### PR TITLE
rpma: remove deprecated completions API

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1578)

### CODE REVIEW

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1578)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1578)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/include/librpma.h, line 2881 at r1](https://reviewable.io/reviews/pmem/rpma/1578#-MvcC6u66lybEzFwVWmC:-MvcC6u66lybEzFwVWmD:b-bbwsf) ([raw file](https://github.com/pmem/rpma/blob/df3461816ec71e4d87f307a7290beca24bcaca7e/src/include/librpma.h#L2881)):*
> ```objc
>  *	if (wc.opcode != IBV_WC_RDMA_READ) { error_handling_code() }
>  *
>  *	void *op_context = (void *)wc.wr_id;
> ```

We should document that op_context from rpma_read/write/send/recv is returned by wc.wr_id



_Code quote:_
```objc
void *op_context = (void *)wc.wr_id;
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1578)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[src/include/librpma.h, line 2881 at r1](https://reviewable.io/reviews/pmem/rpma/1578#-MvcC6u66lybEzFwVWmC:-MvcJJt_5zQn3EODtS6u:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/df3461816ec71e4d87f307a7290beca24bcaca7e/src/include/librpma.h#L2881)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

We should document that op_context from rpma_read/write/send/recv is returned by wc.wr_id
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1578)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1578)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1578#-:-Mvcqfig2aTqhyZeJgtj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1578)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1578#-Mvd2cN53RShuJiDp5Dq:-MvdC0r18jmvv8VTJXPF:bwbw51t) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Waiting for https://github.com/pmem/rpma/pull/1574 to be merged
</blockquote></details>

Merged

---

**Pull request merged**
