### PR TITLE
tools: add missing configuration elements (report)

### PR DESCRIPTION
**Pull request by janekmi**
- PMem specific configuration
- RDMA-capable NIC (including MTU and protocol)
- storage

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/776)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/776)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/776#-MS1HvkK9oqb_83mRXRT:-MS1HvkK9oqb_83mRXRU:b-nk4k4f) (no related file):*
What about target dax/ file size?

---

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/776)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/776#-MS1HvkK9oqb_83mRXRT:-MS20DPI7W5L-n2Ynm2r:b-3ix40i) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

What about target dax/ file size?
</blockquote></details>

Here you are:

```
XGiB Device DAX / FileSystem DAX file on Xx Interleaved region
```

---

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/776)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/776#-:-MS2IgcCECfBqFRcZgZZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/776)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/templates/configuration_common.md.template, line 7 at r2](https://reviewable.io/reviews/pmem/rpma/776#-MS2No7l29ahJzMIlf3w:-MS2No7l29ahJzMIlf3x:bio291k) ([raw file](https://github.com/pmem/rpma/blob/a3b3e63f5471735b0444291508fe04aff1f54a7c/tools/templates/configuration_common.md.template#L7)):*
> ```
> JGB
> ```

`XGB` or `xGB` ?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/776)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/templates/configuration_common.md.template, line 7 at r2](https://reviewable.io/reviews/pmem/rpma/776#-MS2No7l29ahJzMIlf3w:-MS2TRq2EdwTtkXYsoB8:b-u6q1ot) ([raw file](https://github.com/pmem/rpma/blob/a3b3e63f5471735b0444291508fe04aff1f54a7c/tools/templates/configuration_common.md.template#L7)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> JGB
> ```

`XGB` or `xGB` ?
</blockquote></details>

I have tried to follow a convention `<a capital letter to be replaced by the actual value><unit>`. Where using J or X do not matter. Does it answer your question? :-)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/776)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

___
*[tools/templates/configuration_common.md.template, line 7 at r2](https://reviewable.io/reviews/pmem/rpma/776#-MS2No7l29ahJzMIlf3w:-MS2Z40lCi8ZqcKk4eUV:b2nhswy) ([raw file](https://github.com/pmem/rpma/blob/a3b3e63f5471735b0444291508fe04aff1f54a7c/tools/templates/configuration_common.md.template#L7)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I have tried to follow a convention `<a capital letter to be replaced by the actual value><unit>`. Where using J or X do not matter. Does it answer your question? :-)
</blockquote></details>

Yes

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/776#-:-MS2Z7g6AIpo6IR9xuMi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
