### PR TITLE
tools: extend block size range to be able to saturate 100Gb connection

### PR DESCRIPTION
**Pull request by grom72**
The block size range is extended to 256kB to be able to saturate 100Gb RDMA connection with one thread/job.
bs for latency has also been extended to have the same range of input parameters

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1104)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1104)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1104#-McyjLhH4RoafN9q6E4m:-McyjLhH4RoafN9q6E4n:b-l6m90o) (no related file):*
All extended scenarios require verification.

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1104)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1104#-McyjLhH4RoafN9q6E4m:-Md1nZp9C9iT_lrqoYwS:b-gknm45) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

All extended scenarios require verification.
</blockquote></details>

Tests started ...

---

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1104)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[tools/perf/ib_read.sh, line 70 at r1](https://reviewable.io/reviews/pmem/rpma/1104#-MdGrySl-PCGnFlv3_T_:-MdGrySl-PCGnFlv3_Ta:bq05jyd) ([raw file](https://github.com/pmem/rpma/blob/6fc585ca652d0d359d533fbad00a862fd90ef6d8/tools/perf/ib_read.sh#L70)):*
> ```Shell
> 		# values measured empirically, so that duration was ~60s
> 		# 100000000 is the maximum value of iterations
> 		ITERATIONS=(48336720 48336720 34951167 24475088 23630690 8299603 5001135 5001135 5001135)
> ```

Do we know # of iterations is big enough to match ~60 seconds runtime?
___
*[tools/perf/ib_read.sh, line 123 at r1](https://reviewable.io/reviews/pmem/rpma/1104#-MdGsA5l5zjpWl0VpNcC:-MdGsA5l5zjpWl0VpNcD:bq05jyd) ([raw file](https://github.com/pmem/rpma/blob/6fc585ca652d0d359d533fbad00a862fd90ef6d8/tools/perf/ib_read.sh#L123)):*
> ```Shell
> 		DEPTH=1
> 		# values measured empirically, so that duration was ~60s
> 		ITERATIONS=(27678723 27678723 20255739 16778088 11423082 8138946 6002473 6002473 6002473)
> ```

Do we know # of iterations is big enough to match ~60 seconds runtime?

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1104)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/ib_read.sh, line 70 at r1](https://reviewable.io/reviews/pmem/rpma/1104#-MdGrySl-PCGnFlv3_T_:-MeYwKYf1QyD2yTInsIs:bas2wcg) ([raw file](https://github.com/pmem/rpma/blob/6fc585ca652d0d359d533fbad00a862fd90ef6d8/tools/perf/ib_read.sh#L70)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Do we know # of iterations is big enough to match ~60 seconds runtime?
</blockquote></details>

BS 131072 - 4800000
BS 262144 - 2600000
___
*[tools/perf/ib_read.sh, line 123 at r1](https://reviewable.io/reviews/pmem/rpma/1104#-MdGsA5l5zjpWl0VpNcC:-MeYwOsz2uhDwawpIeni:b-8ilntm) ([raw file](https://github.com/pmem/rpma/blob/6fc585ca652d0d359d533fbad00a862fd90ef6d8/tools/perf/ib_read.sh#L123)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Do we know # of iterations is big enough to match ~60 seconds runtime?
</blockquote></details>

BS 131072 - 3600000
BS 262144 - 2100000

**Review by janekmi — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1104)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1104#-:-MeZ8aa95WT2pJrrXkd8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1104)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1104#-:-MeZReEm253EjOMLsnj-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1104)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
