### PR TITLE
common: clean up CMake variables

### PR DESCRIPTION
**Pull request by ldorau**
Clean up the CMake variables:
- remove unused TESTS_LONG,
- rename DEVELOPER_MODE to BUILD_DEVELOPER_MODE
- rename COVERAGE to TESTS_COVERAGE
- rename TRACE_TESTS to TESTS_VERBOSE_OUTPUT
- rename TEST_PYTHON_TOOLS to TESTS_PYTHON_TOOLS
- rename USE_ASAN to DEBUG_USE_ASAN
- rename USE_UBSAN to DEBUG_USE_UBSAN
- rename CHECK_CSTYLE to BUILD_CHECK_CSTYLE

Change default values of CMake variables:
- CMAKE_BUILD_TYPE from Debug to Release
- BUILD_EXAMPLES - from ON to OFF
- TESTS_PYTHON_TOOLS - from ON to OFF

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1833)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1833)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[`CMakeLists.txt` line 46 at r1](https://reviewable.io/reviews/pmem/rpma/1833#-N4WbvxNEWFVbj-4UDwA:-N4WbvxO1OJJTJJJ_xYN:undefined) ([raw file](https://github.com/pmem/rpma/blob/3912f5c8d32cd0ab5b7ab19fbc9ce9efae01238c/CMakeLists.txt#L46)):*
> ```CMake
> option(TESTS_COVERAGE "run coverage test" OFF)
> option(TESTS_NO_FORTIFY_SOURCE "enable tests that do not pass when -D_FORTIFY_SOURCE=2 flag set" OFF)
> option(TESTS_PYTHON_TOOLS "run tests for Python tools" OFF)
> ```





_Suggestion:_
```CMake
option(TESTS_PERF_TOOLS "run tests for performance analysis tools" OFF)
```

**Review by osalyk — CHANGES_REQUESTED** [review]
> Reviewed 8 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1833)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[`CMakeLists.txt` line 40 at r2](https://reviewable.io/reviews/pmem/rpma/1833#-N4WdmfBACPIATvuapFu:-N4WdmfBACPIATvuapFv:b-w0ohwo) ([raw file](https://github.com/pmem/rpma/blob/e92a63f1c5a50609755e9bbe647ec4cf4ec51cf9/CMakeLists.txt#L40)):*
> ```CMake
> option(BUILD_DOC "build documentation" ON)
> option(BUILD_TESTS "build tests" ON)
> option(BUILD_EXAMPLES "build examples" OFF)
> ```

I would leave building examples. The user can run a single working example.

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1833)* status: all files reviewed, 8 unresolved discussions (waiting on @ldorau)

___
*[`CMakeLists.txt` line 49 at r1](https://reviewable.io/reviews/pmem/rpma/1833#-N4WeYs9DL5WJwSWzcoJ:-N4WeYs9DL5WJwSWzcoK:undefined) ([raw file](https://github.com/pmem/rpma/blob/3912f5c8d32cd0ab5b7ab19fbc9ce9efae01238c/CMakeLists.txt#L49)):*
> ```CMake
> option(TESTS_RDMA_CONNECTION "enable tests that require a configured RDMA-capable network interface" OFF)
> option(TESTS_USE_FORCED_PMEM "run tests with PMEM_IS_PMEM_FORCE=1" OFF)
> option(TESTS_USE_VALGRIND "enable tests with valgrind (if found)" OFF)
> ```





_Suggestion:_
```CMake
option(TESTS_USE_VALGRIND "enable tests with valgrind (helgrind/drd/memcheck)" OFF)
```
___
*[`CMakeLists.txt` line 51 at r1](https://reviewable.io/reviews/pmem/rpma/1833#-N4Wcv_12pdycj-xPuzl:-N4Wcv_12pdycj-xPuzm:undefined) ([raw file](https://github.com/pmem/rpma/blob/3912f5c8d32cd0ab5b7ab19fbc9ce9efae01238c/CMakeLists.txt#L51)):*
> ```CMake
> option(TESTS_USE_VALGRIND "enable tests with valgrind (if found)" OFF)
> option(TESTS_USE_VALGRIND_PMEMCHECK "enable tests with valgrind pmemcheck (if found)" OFF)
> option(TESTS_VERBOSE_OUTPUT "more verbose test outputs" OFF)
> ```





_Suggestion:_
```CMake
verbose test outputs
```
___
*[`CMakeLists.txt` line 55 at r1](https://reviewable.io/reviews/pmem/rpma/1833#-N4WdVWN92HcBARIAg_d:-N4WdVWN92HcBARIAg_e:undefined) ([raw file](https://github.com/pmem/rpma/blob/3912f5c8d32cd0ab5b7ab19fbc9ce9efae01238c/CMakeLists.txt#L55)):*
> ```CMake
> option(DEBUG_LOG_TRACE "enable logging function traces" OFF)
> option(DEBUG_FAULT_INJECTION "enable fault injection" OFF)
> option(DEBUG_USE_ASAN "enable AddressSanitizer (debugging)" OFF)
> ```





_Suggestion:_
```CMake
option(DEBUG_USE_ASAN "enable AddressSanitizer (-fsanitize=address)" OFF)
```
___
*[`CMakeLists.txt` line 56 at r1](https://reviewable.io/reviews/pmem/rpma/1833#-N4Wdg9h2ASDJ7NYSgCO:-N4Wdg9h2ASDJ7NYSgCP:undefined) ([raw file](https://github.com/pmem/rpma/blob/3912f5c8d32cd0ab5b7ab19fbc9ce9efae01238c/CMakeLists.txt#L56)):*
> ```CMake
> option(DEBUG_FAULT_INJECTION "enable fault injection" OFF)
> option(DEBUG_USE_ASAN "enable AddressSanitizer (debugging)" OFF)
> option(DEBUG_USE_UBSAN "enable UndefinedBehaviorSanitizer (debugging)" OFF)
> ```





_Suggestion:_
```CMake
option(DEBUG_USE_UBSAN "enable UndefinedBehaviorSanitizer (-fsanitize=undefined)" OFF)
```
___
*[`DEVELOPMENT.md` line 16 at r1](https://reviewable.io/reviews/pmem/rpma/1833#-N4WeuYT1aRWrxA2R2w_:-N4WeuYT1aRWrxA2R2wa:bj4q1l2) ([raw file](https://github.com/pmem/rpma/blob/3912f5c8d32cd0ab5b7ab19fbc9ce9efae01238c/DEVELOPMENT.md#L16)):*
> ```Markdown
> | CMAKE_INSTALL_PREFIX | Install path prefix, prepended onto install directories | *dir path* | /usr/local |
> | TESTS_COVERAGE | Run coverage test | ON/OFF | OFF |
> | BUILD_DEVELOPER_MODE | Enable developer checks | ON/OFF | OFF |
> ```

move to ``BUILD_`` group above.



_Code quote:_
```Markdown
| BUILD_DEVELOPER_MODE | Enable developer checks | ON/OFF | OFF |
```
___
*[`DEVELOPMENT.md` line 19 at r1](https://reviewable.io/reviews/pmem/rpma/1833#-N4WfJUZ93QKzBQ3S3Ws:-N4WfJUZ93QKzBQ3S3Wt:bn3ahtq) ([raw file](https://github.com/pmem/rpma/blob/3912f5c8d32cd0ab5b7ab19fbc9ce9efae01238c/DEVELOPMENT.md#L19)):*
> ```Markdown
> | TESTS_USE_FORCED_PMEM | Run tests with PMEM_IS_PMEM_FORCE=1 | ON/OFF | OFF |
> | TESTS_USE_VALGRIND | Enable tests with valgrind | ON/OFF | ON |
> | TEST_DIR | Working directory for tests | *dir path* | ./build/test |
> ```

Can we sort this list:
1. custom librpma options ``BUILD_``, ``TESTS_``, ``DEBUG_``
2. CMAKE generic flags: ``CMAKE_``
3. other flags: ``TEST_DIR``



_Code quote:_
```Markdown
TEST_DIR
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1833)* status: all files reviewed, 8 unresolved discussions (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1833)* status: all files reviewed, 8 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[`CMakeLists.txt` line 40 at r2](https://reviewable.io/reviews/pmem/rpma/1833#-N4WdmfBACPIATvuapFu:-N4WhFIP7A4XyX0KEu_s:b4xg6qs) ([raw file](https://github.com/pmem/rpma/blob/e92a63f1c5a50609755e9bbe647ec4cf4ec51cf9/CMakeLists.txt#L40)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

I would leave building examples. The user can run a single working example.
</blockquote></details>

It is not needed to instal the library.

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1833)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1833)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau and @osalyk)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1833)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`CMakeLists.txt` line 46 at r1](https://reviewable.io/reviews/pmem/rpma/1833#-N4WbvxNEWFVbj-4UDwA:-N4X2SgSEzlv1UMcRv_P:b-1dfggl) ([raw file](https://github.com/pmem/rpma/blob/3912f5c8d32cd0ab5b7ab19fbc9ce9efae01238c/CMakeLists.txt#L46)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Do you not want to change the variable name?
</blockquote></details>

Ah, I didn't noticed. Changed.

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1833)* status: 3 of 10 files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1833#-:-N4XGOks9vItgvhkNQna:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 7 of 7 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1833)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

___
*[`CMakeLists.txt` line 46 at r1](https://reviewable.io/reviews/pmem/rpma/1833#-N4WbvxNEWFVbj-4UDwA:-N4XJrc8Bf18BXDpqDEI:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/3912f5c8d32cd0ab5b7ab19fbc9ce9efae01238c/CMakeLists.txt#L46)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Ah, I didn't noticed. Changed.
</blockquote></details>

Done

**Pull request merged**
