### PR TITLE
tools: tool added to mandatory keys

### PR DESCRIPTION
**Pull request by grom72**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1467)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1467)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1467#-MsEmz-o8r6P91cDhObl:-MsEmz-o8r6P91cDhObm:b50j8mm) (no related file):*
Please change the commit message:
tool and busy-wait-poling added to mandatory keys

---

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1467)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1467#-MsEmz-o8r6P91cDhObl:-MsF5mlN1TurQYBXnrQO:b-896fix) (no related file):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Please change the commit message:
tool and busy-wait-poling added to mandatory keys
</blockquote></details>

Done.

---

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1467)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1467#-:-MsFAmLrBDFJH_xJksyX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1467)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[utils/pylint.rc, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/1467#-MsUg7Y46dDTpzOJqkbS:-MsUg7Y53OQURW3An2M2:b-l4vpuh) ([raw file](https://github.com/pmem/rpma/blob/0ee6892cb09c0578a15e5b4b112456de73a7d43d/utils/pylint.rc#L15)):*
> ```
> # len-as-condition - bug in Pylint, fixed as of Pylint 2.4 (https://github.com/PyCQA/pylint/pull/2815)
> # duplicate-code - XXX requires consideration
> # bad-continuation - still enabled by default on old releases https://github.com/PyCQA/pylint/pull/3571
> ```

Issue in #1468 



_Code quote:_
```
# bad-continuation - still enabled by default on old releases https://github.com/PyCQA/pylint/pull/3571
```

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1467)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72, @ldorau, and @osalyk)

___
*[utils/pylint.rc, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/1467#-MsUg7Y46dDTpzOJqkbS:-MsUgu7Z5TBJW_N1TVU-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0ee6892cb09c0578a15e5b4b112456de73a7d43d/utils/pylint.rc#L15)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Issue in #1468 
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1467#-:-MsUhotH1YLSFkyXxi8n:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1467)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 319 at r3](https://reviewable.io/reviews/pmem/rpma/1467#-MsUkJYr5FIhcHsr9fCM:-MsUkJYr5FIhcHsr9fCN:b1k7xs1) ([raw file](https://github.com/pmem/rpma/blob/b72880b4550b95ac7c94e97eeef7a0599e701959/tools/perf/lib/benchmark/runner/fio.py#L319)):*
> ```Python
> 
>     __ONESERIES_REQUIRED = ['tool', 'tool_mode', 'mode', 'rw', 'filetype',
>                             'busy_wait_polling']
> ```

@grom72 @osalyk  It seems it is not required, is it?
https://github.com/pmem/rpma/blob/master/tools/perf/lib/benchmark/runner/fio.py#L142

**Review by osalyk — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1467)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 319 at r3](https://reviewable.io/reviews/pmem/rpma/1467#-MsUkJYr5FIhcHsr9fCM:-MsUlp7rAye9Qjp8uRba:bcwzw3d) ([raw file](https://github.com/pmem/rpma/blob/b72880b4550b95ac7c94e97eeef7a0599e701959/tools/perf/lib/benchmark/runner/fio.py#L319)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@grom72 @osalyk  It seems it is not required, is it?
https://github.com/pmem/rpma/blob/master/tools/perf/lib/benchmark/runner/fio.py#L142


</blockquote></details>

Yes you're right.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1467)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 319 at r3](https://reviewable.io/reviews/pmem/rpma/1467#-MsUkJYr5FIhcHsr9fCM:-MsUpNwuB4guBWz1iVDY:b-1jcc4i) ([raw file](https://github.com/pmem/rpma/blob/b72880b4550b95ac7c94e97eeef7a0599e701959/tools/perf/lib/benchmark/runner/fio.py#L319)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Yes you're right.
</blockquote></details>

@grom72 ?

**Review by ldorau — COMMENTED** [review]
:lgtm_cancel: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1467#-:-MsUpXiK4TFdwido-n_j:b8b79qu)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1467)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72, @ldorau, and @osalyk)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 319 at r3](https://reviewable.io/reviews/pmem/rpma/1467#-MsUkJYr5FIhcHsr9fCM:-MsUrwRQ9m9l9FuOZr64:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b72880b4550b95ac7c94e97eeef7a0599e701959/tools/perf/lib/benchmark/runner/fio.py#L319)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@grom72 ?
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1467)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
