### PR TITLE
common: replace the --fault-injection option with --integration-tests

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #1874
- [x] #1880 

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1881)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1881)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[`examples/run-all-examples.sh` line 8 at r1](https://reviewable.io/reviews/pmem/rpma/1881#-N5_6wz8ERu2T3ySk_ck:-N5_6wz8ERu2T3ySk_cl:b-5bip0h) ([raw file](https://github.com/pmem/rpma/blob/4ac213561faa5bc392c8cd60479846f9d95e8b1e/examples/run-all-examples.sh#L8)):*
> ```Shell
> # run-all-examples.sh - run all examples (optionally under valgrind or with fault injection)
> #
> # Usage: run-all-examples.sh <binary-examples-directory> [--valgrind|--integration-tests]
> ```

At least one sentence of documentation about the ``--integration-tests`` option is required.



_Code quote:_
```Shell
--integration-tests
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1881)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1881)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`examples/run-all-examples.sh` line 8 at r1](https://reviewable.io/reviews/pmem/rpma/1881#-N5_6wz8ERu2T3ySk_ck:-N5_IMGt4pEfIIB0fE3r:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4ac213561faa5bc392c8cd60479846f9d95e8b1e/examples/run-all-examples.sh#L8)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

At least one sentence of documentation about the ``--integration-tests`` option is required.
</blockquote></details>

Done.

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1881)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`examples/run-all-examples.sh` line 51 at r2](https://reviewable.io/reviews/pmem/rpma/1881#-N5_N5Q-Bc_jH_82lLjh:-N5_N5Q-Bc_jH_82lLji:undefined) ([raw file](https://github.com/pmem/rpma/blob/dfe1542b4107a4649eb7db228cab0209b1344244/examples/run-all-examples.sh#L51)):*
> ```Shell
> \n\
> The '--integration-tests' option starts integration tests documented \
> in the https://github.com/pmem/rpma/blob/master/DEVELOPMENT.md file.\n"
> ```





_Suggestion:_
```Shell
https://github.com/pmem/rpma/blob/master/DEVELOPMENT.md#running-integration-tests
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1881)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1881#-:-N5_Nddm0VH1jrmDki8k:bnfp4nl)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1881)* status: 1 of 6 files reviewed, all discussions resolved (waiting on @grom72)

___
*[`examples/run-all-examples.sh` line 51 at r2](https://reviewable.io/reviews/pmem/rpma/1881#-N5_N5Q-Bc_jH_82lLjh:-N5_Tiye7myqfOyjAeuL:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/dfe1542b4107a4649eb7db228cab0209b1344244/examples/run-all-examples.sh#L51)):*
> ```Shell
> \n\
> The '--integration-tests' option starts integration tests documented \
> in the https://github.com/pmem/rpma/blob/master/DEVELOPMENT.md file.\n"
> ```

Done

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 2 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1881#-:-N5doP-O1zmRpouHfZr7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
