### PR TITLE
rpma: see you, Jan!

### PR DESCRIPTION
**Pull request by ldorau**
Thank you, Jan, very much for all your contributions
and maintaining librpma from the very begining!
See you, Jan!

RPMA team

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1550)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
:(

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1550#-:-MvNJlu7CU8TOBRxWDTk:b32vhv)* status: 0 of 1 files reviewed, all discussions resolved

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1550#-:-MvNJrIP3D3wmjzMQk_b:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved

**Review by osalyk — APPROVED** [review]
:smiling_face_with_tear:  :lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1550#-:-MvNKqIuDuZQHVsfbLS5:b-f8lum6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Comment by janekmi** [comment]
:smiling_face_with_tear: Thank you all! What we have done together is truly epic!

**Pull request merged**
