### PR TITLE
rpma: change names of completion API calls

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/519)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 15 of 17 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/519)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tests/unit/conn/conn-completion_get.c, line 5 at r2](https://reviewable.io/reviews/pmem/rpma/519#-MIYUrhpE_iKydqFrUs6:-MIYUrhpE_iKydqFrUs7:b-npm3rs) ([raw file](https://github.com/pmem/rpma/blob/df2567fb1eb44d711d7ce41c53e1581342248f48/tests/unit/conn/conn-completion_get.c#L5)):*
> ```
> conn-test-completion_get.c
> ```
conn-completion_get.c

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/519)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 15 of 17 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/519#-:-MIYVD5rED-Ko5o90cGK:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/519#-:-MIYVQFX5wbnzIdCs-50:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/519)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @grom72 and @osalyk)

___
*[tests/unit/conn/conn-completion_get.c, line 5 at r2](https://reviewable.io/reviews/pmem/rpma/519#-MIYUrhpE_iKydqFrUs6:-MIYWUeSBrUAYcCbEL7I:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/df2567fb1eb44d711d7ce41c53e1581342248f48/tests/unit/conn/conn-completion_get.c#L5)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> conn-test-completion_get.c
> ```
conn-completion_get.c
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/519#-:-MIYZUbx-1SgO267iLCE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 15 of 17 files at r1, 2 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/519#-:-MIZ0VsPEzNp5-rM3SwB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
