### PR TITLE
test: do some cleanup for unit tests

### PR DESCRIPTION
**Pull request by yangx-jy**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1925)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1925)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[`tests/unit/peer/peer-create_qp.c` line 24 at r2](https://reviewable.io/reviews/pmem/rpma/1925#-N7GJf_F4FEAAs46eZvE:-N7GJf_F4FEAAs46eZvF:bzek3ef) ([raw file](https://github.com/pmem/rpma/blob/2d8ede9a44cdbd0bda452a81ec3c0051cd9ef19e/tests/unit/peer/peer-create_qp.c#L24)):*
> ```C
> static struct conn_cfg_get_mock_args Get_args = {
> 	.cfg = MOCK_CONN_CFG_CUSTOM,
> 	.sq_size = MOCK_SQ_SIZE_CUSTOM,
> ```

What about other fields from ``conn_cfg_get_mock_args `` structure?
struct conn_cfg_get_mock_args {
	struct rpma_conn_cfg *cfg;
	int timeout_ms;
	uint32_t sq_size;
	uint32_t rq_size;
	uint32_t cq_size;
	uint32_t rcq_size;
	bool shared;
};



_Code quote:_
```C
	.sq_size = MOCK_SQ_SIZE_CUSTOM,
	.rq_size = MOCK_RQ_SIZE_CUSTOM
```

**Review by yangx-jy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1925)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`tests/unit/peer/peer-create_qp.c` line 24 at r2](https://reviewable.io/reviews/pmem/rpma/1925#-N7GJf_F4FEAAs46eZvE:-N7GRZj917X6H2Iy_BQD:b-rxrir0) ([raw file](https://github.com/pmem/rpma/blob/2d8ede9a44cdbd0bda452a81ec3c0051cd9ef19e/tests/unit/peer/peer-create_qp.c#L24)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

What about other fields from ``conn_cfg_get_mock_args `` structure?
struct conn_cfg_get_mock_args {
	struct rpma_conn_cfg *cfg;
	int timeout_ms;
	uint32_t sq_size;
	uint32_t rq_size;
	uint32_t cq_size;
	uint32_t rcq_size;
	bool shared;
};

</blockquote></details>

Other fields are not used in `rpma_peer_create_qp` unit tests.
This change avoids defining a lot of structures which includes duplicated cfg member.
Do you have any better way?

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1925)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Comment by yangx-jy** [comment]
*[`tests/unit/peer/peer-create_qp.c` line 24 at r2](https://reviewable.io/reviews/pmem/rpma/1925#-N7GJf_F4FEAAs46eZvE:-N7IxWr19WNxSXUIPVjR:b5qhuzb) ([raw file](https://github.com/pmem/rpma/blob/2d8ede9a44cdbd0bda452a81ec3c0051cd9ef19e/tests/unit/peer/peer-create_qp.c#L24)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Other fields are not used in `rpma_peer_create_qp` unit tests.
This change avoids defining a lot of structures which includes duplicated cfg member.
Do you have any better way?
</blockquote></details>

@grom72 @ldorau 

BTW, I hope this PR can be reviewed as soon as possible because my SRQ implementation depends on it.

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1925)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`tests/unit/peer/peer-create_qp.c` line 24 at r2](https://reviewable.io/reviews/pmem/rpma/1925#-N7GJf_F4FEAAs46eZvE:-N7K4RLX8I1s4t4Xr0WF:b-24iyia) ([raw file](https://github.com/pmem/rpma/blob/2d8ede9a44cdbd0bda452a81ec3c0051cd9ef19e/tests/unit/peer/peer-create_qp.c#L24)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

@grom72 @ldorau 

BTW, I hope this PR can be reviewed as soon as possible because my SRQ implementation depends on it.
</blockquote></details>

How about solution that uses values from conn_cfg.c:
```
static struct rpma_conn_cfg Conn_cfg_default  = {
	.timeout_ms = RPMA_DEFAULT_TIMEOUT_MS,
	.cq_size = RPMA_DEFAULT_Q_SIZE,
	.rcq_size = RPMA_DEFAULT_RCQ_SIZE,
	.sq_size = RPMA_DEFAULT_Q_SIZE,
	.rq_size = RPMA_DEFAULT_Q_SIZE,
	.shared_comp_channel = RPMA_DEFAULT_SHARED_COMPL_CHANNEL
};
```



_Code quote:_
```C
conn_cfg_get_mock_arg
```

**Comment by yangx-jy** [comment]
*[`tests/unit/peer/peer-create_qp.c` line 24 at r2](https://reviewable.io/reviews/pmem/rpma/1925#-N7GJf_F4FEAAs46eZvE:-N7KGHFA5vieZpfTF_4f:b61hlex) ([raw file](https://github.com/pmem/rpma/blob/2d8ede9a44cdbd0bda452a81ec3c0051cd9ef19e/tests/unit/peer/peer-create_qp.c#L24)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

How about solution that uses values from conn_cfg.c:
```
static struct rpma_conn_cfg Conn_cfg_default  = {
	.timeout_ms = RPMA_DEFAULT_TIMEOUT_MS,
	.cq_size = RPMA_DEFAULT_Q_SIZE,
	.rcq_size = RPMA_DEFAULT_RCQ_SIZE,
	.sq_size = RPMA_DEFAULT_Q_SIZE,
	.rq_size = RPMA_DEFAULT_Q_SIZE,
	.shared_comp_channel = RPMA_DEFAULT_SHARED_COMPL_CHANNEL
};
```
</blockquote></details>

`struct conn_cfg_get_mock_args` is used to simulate `struct rpma_conn_cfg`.  In addition, it adds cfg member to check if the value of cfg is expected.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 9 of 10 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1925#-:-N7KKfdMAuml4g1kTJzo:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1925#-:-N7KLSBV-IB_Rs5DgAWQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Pull request merged**
