### PR TITLE
examples: run integration tests on SoftRoCE or RDMA HW

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1822)

### CODE REVIEW

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1822#-:-N47rZzE4CeUJa14Yrzv:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1822#-N47r_LE9uyxPm7QwM3I:-N47r_LE9uyxPm7QwM3J:bved1sp) (no related file):*
It seems that this script is going to be very complex - shall we consider converting it to Python?

___

**Review by osalyk — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1822)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1822)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1822#-:-N4BWtb45v9YCrdggLki:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1822)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1822)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1822)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1822)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1822)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[`examples/run-all-examples.sh` line 84 at r8](https://reviewable.io/reviews/pmem/rpma/1822#-N4DKU_uA_fmRpt74oEc:-N4DKU_uA_fmRpt74oEd:b-vg63jv) ([raw file](https://github.com/pmem/rpma/blob/31e356e8840aa1db15553628db45595602d57701/examples/run-all-examples.sh#L84)):*
> ```Shell
> fi
> 
> IP_ADDRESS=$2
> ```

``IP_ADDRESS`` is an optional parameter



_Suggestion:_
```Shell
IP_ADDRESS=$2
if [ $IP_ADDRESS ~= [0-9]*\.[0-9]*\.[0-9]*\.[0-9]* ]; then
	PORT=$3
else
	PORT=$2
	IP_ADDRES=""
fi
```
___
*[`examples/run-all-examples.sh` line 86 at r8](https://reviewable.io/reviews/pmem/rpma/1822#-N4DKb1s9x_ama_jSvn3:-N4DKb1s9x_ama_jSvn4:b-4a5l60) ([raw file](https://github.com/pmem/rpma/blob/31e356e8840aa1db15553628db45595602d57701/examples/run-all-examples.sh#L86)):*
> ```Shell
> IP_ADDRESS=$2
> PORT=$3
> if [ "$IP_ADDRESS" != "" -a "$PORT" == "" ]; then
> ```

We can use the default ``PORT`` regardless of the ``IP_ADDRESS`` value



_Suggestion:_
```Shell
if [ "$PORT" == "" ]; then
	PORT="7204"
fi
```
___
*[`examples/run-all-examples.sh` line 190 at r8](https://reviewable.io/reviews/pmem/rpma/1822#-N4DKv5ICINXITN7kog6:-N4DKv5ICINXITN7kog7:bjdqao8) ([raw file](https://github.com/pmem/rpma/blob/31e356e8840aa1db15553628db45595602d57701/examples/run-all-examples.sh#L190)):*
> ```Shell
> 	fi
> 
> 	if [ "$IP_ADDRESS" != "" -a "$PORT" == "" ]; then
> ```

redundant
___
*[`examples/run-all-examples.sh` line 353 at r8](https://reviewable.io/reviews/pmem/rpma/1822#-N4DLeqO-cdC4hJbs3bD:-N4DLeqP22O57i-lAGmM:b-6g6t0s) ([raw file](https://github.com/pmem/rpma/blob/31e356e8840aa1db15553628db45595602d57701/examples/run-all-examples.sh#L353)):*
> ```Shell
> 	if [[ "$_PATH" = "/*" ]] && [ -c "$_PATH" -o -f "$_PATH" ]; then
> 		echo "Notice: running examples on PMem: $RPMA_EXAMPLES_PMEM_PATH (RPMA_EXAMPLES_PMEM_PATH)."
> 		PMEM_PATH=$RPMA_EXAMPLES_PMEM_PATH
> ```

This part shall be moved to the beginning section of the script where parameters are gathered.



_Code quote:_
```Shell
if [ "$PMEM_PATH" == "" -a "$RPMA_EXAMPLES_PMEM_PATH" != "" ]; then
	_PATH=$RPMA_EXAMPLES_PMEM_PATH
	if [[ "$_PATH" = "/*" ]] && [ -c "$_PATH" -o -f "$_PATH" ]; then
		echo "Notice: running examples on PMem: $RPMA_EXAMPLES_PMEM_PATH (RPMA_EXAMPLES_PMEM_PATH)."
		PMEM_PATH=$RPMA_EXAMPLES_PMEM_PATH
	else
		echo "Notice: $RPMA_EXAMPLES_PMEM_PATH is not an absolute path of a file nor a character device"
		exit 1
	fi
elif [ "$PMEM_PATH" == "" ]; then
	echo "Notice: PMem path (RPMA_EXAMPLES_PMEM_PATH) is not set, examples will be run on DRAM."
fi
```

**Review by grom72 — COMMENTED** [review]
:lgtm_cancel: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1822#-:-N4DPajMA2Ge5Le2l-rW:b8b79qu)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1822)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72)

___
*[`examples/run-all-examples.sh` line 84 at r8](https://reviewable.io/reviews/pmem/rpma/1822#-N4DKU_uA_fmRpt74oEc:-N4QqFco1D4un7X1i0OI:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/31e356e8840aa1db15553628db45595602d57701/examples/run-all-examples.sh#L84)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

``IP_ADDRESS`` is an optional parameter
</blockquote></details>

Done.
___
*[`examples/run-all-examples.sh` line 86 at r8](https://reviewable.io/reviews/pmem/rpma/1822#-N4DKb1s9x_ama_jSvn3:-N4QqgPQ0OZ0yY_VCJJY:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/31e356e8840aa1db15553628db45595602d57701/examples/run-all-examples.sh#L86)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

We can use the default ``PORT`` regardless of the ``IP_ADDRESS`` value
</blockquote></details>

Done.
___
*[`examples/run-all-examples.sh` line 190 at r8](https://reviewable.io/reviews/pmem/rpma/1822#-N4DKv5ICINXITN7kog6:-N4Qqhm81JB0eU0EO84n:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/31e356e8840aa1db15553628db45595602d57701/examples/run-all-examples.sh#L190)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

redundant
</blockquote></details>

Done.
___
*[`examples/run-all-examples.sh` line 353 at r8](https://reviewable.io/reviews/pmem/rpma/1822#-N4DLeqO-cdC4hJbs3bD:-N4Qr9v1BLy-KNFXZcoi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/31e356e8840aa1db15553628db45595602d57701/examples/run-all-examples.sh#L353)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

This part shall be moved to the beginning section of the script where parameters are gathered.
</blockquote></details>

Done.

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1822)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`examples/run-all-examples.sh` line 207 at r10](https://reviewable.io/reviews/pmem/rpma/1822#-N4R7d-d338w4Pp53Oe6:-N4R7d-d338w4Pp53Oe7:b-z6x35y) ([raw file](https://github.com/pmem/rpma/blob/65b79b4fbb360802483941612fe98d9d89c91b6a/examples/run-all-examples.sh#L207)):*
> ```Shell
> 	fi
> 
> 	if [ "$IP_ADDRESS" != "" -a "$PORT" == "" ]; then
> ```

``$IP_ADDRESS`` is already set or ``exit 1`` is executed



_Suggestion:_
```Shell
	if "$PORT" == ""; then
		PORT="7204"
	fi
```

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1822)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[`examples/run-all-examples.sh` line 190 at r8](https://reviewable.io/reviews/pmem/rpma/1822#-N4DKv5ICINXITN7kog6:-N4R8-el2ZQO4kOt69pT:b3kre) ([raw file](https://github.com/pmem/rpma/blob/31e356e8840aa1db15553628db45595602d57701/examples/run-all-examples.sh#L190)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1822)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[`examples/run-all-examples.sh` line 190 at r8](https://reviewable.io/reviews/pmem/rpma/1822#-N4DKv5ICINXITN7kog6:-N4R8iTK3zHopzMIxumQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/31e356e8840aa1db15553628db45595602d57701/examples/run-all-examples.sh#L190)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[`examples/run-all-examples.sh` line 207 at r10](https://reviewable.io/reviews/pmem/rpma/1822#-N4R7d-d338w4Pp53Oe6:-N4R8inXEDXLsh4G4Uv1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/65b79b4fbb360802483941612fe98d9d89c91b6a/examples/run-all-examples.sh#L207)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

``$IP_ADDRESS`` is already set or ``exit 1`` is executed
</blockquote></details>

Done.

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1822#-:-N4RL2Fp9tVNXvKNPMf8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
