### PR TITLE
rpma: clean up and improve DEVELOPMENT.md file

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1874)

### CODE REVIEW

**Comment by ldorau** [comment]
Preview: https://github.com/ldorau/rpma/blob/rpma-clean-up-and-improve-DEVELOPMENT.md-file/DEVELOPMENT.md

**Review by haichangsi — COMMENTED** [review]
Extremely helpful. :lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1874#-:-N5LHH892jrNkJCbX4_v:bkyokxe)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1874)* status: all files reviewed, 6 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[`DEVELOPMENT.md` line 18 at r2](https://reviewable.io/reviews/pmem/rpma/1874#-N5YqoBo-OhBgjuGjtv5:-N5YqoBo-OhBgjuGjtv6:b-vgho9) ([raw file](https://github.com/pmem/rpma/blob/9a2fbb8ac1e74dafa8e893c12400f0d13139e906/DEVELOPMENT.md#L18)):*
> ```Markdown
> 
> ```sh
> [rpma/build]$ cmake -DBUILD_DOC=ON -DCMAKE_BUILD_TYPE=Debug ..
> ```

BUILD_DOC is ON by default, let's use a more likely scenario



_Suggestion:_
```Markdown
-DBUILD_DEVELOPER_MODE=ON
```
___
*[`DEVELOPMENT.md` line 69 at r2](https://reviewable.io/reviews/pmem/rpma/1874#-N5Yrvk-Da8bcqHW9Wq5:-N5Yrvk-Da8bcqHW9Wq6:b-pt0z7k) ([raw file](https://github.com/pmem/rpma/blob/9a2fbb8ac1e74dafa8e893c12400f0d13139e906/DEVELOPMENT.md#L69)):*
> ```Markdown
> The unit tests are implemented using the [cmocka](https://cmocka.org/) framework. They do not need any RDMA-capable network interface. All unit tests are located in the `./tests/unit/` subfolder of the main directory.
> 
> In order to run **only** the unit tests:
> ```

worth mentioning that it is the default configuration of the librpma 



_Code quote:_
```Markdown
In order to run **only** the unit tests
```
___
*[`DEVELOPMENT.md` line 92 at r2](https://reviewable.io/reviews/pmem/rpma/1874#-N5YsjPQDJhC7Y4JI0mx:-N5YsjPQDJhC7Y4JI0my:undefined) ([raw file](https://github.com/pmem/rpma/blob/9a2fbb8ac1e74dafa8e893c12400f0d13139e906/DEVELOPMENT.md#L92)):*
> ```Markdown
> to print out also the output of the failed tests.
> 
> ## Preparing the environment for running multi-threaded or integration tests on SoftRoCE or RDMA HW
> ```





_Suggestion:_
```Markdown
## Run multi-threaded and integration tests
### Preparing the environment for running multi-threaded or integration tests on SoftRoCE or RDMA HW
```
___
*[`DEVELOPMENT.md` line 116 at r2](https://reviewable.io/reviews/pmem/rpma/1874#-N5Yt1SXBqQrvoQXVEva:-N5Yt1SYDmaVUCSshYKX:bwamil) ([raw file](https://github.com/pmem/rpma/blob/9a2fbb8ac1e74dafa8e893c12400f0d13139e906/DEVELOPMENT.md#L116)):*
> ```Markdown
> 
> The IP address of an RDMA-capable network interface (SoftRoCE or RDMA HW) can be checked using the same commands as for configuring SoftRoCE (listed above).
> ```

### Build multi-threaded and integration tests
___
*[`DEVELOPMENT.md` line 117 at r2](https://reviewable.io/reviews/pmem/rpma/1874#-N5YtYj6AVSnfWHRAR1O:-N5YtYj6AVSnfWHRAR1P:undefined) ([raw file](https://github.com/pmem/rpma/blob/9a2fbb8ac1e74dafa8e893c12400f0d13139e906/DEVELOPMENT.md#L117)):*
> ```Markdown
> The IP address of an RDMA-capable network interface (SoftRoCE or RDMA HW) can be checked using the same commands as for configuring SoftRoCE (listed above).
> 
> 4. In order to run the **multi-threaded tests** build the librpma library with the `TESTS_RDMA_CONNECTION` and the `TESTS_USE_VALGRIND` CMake variables set to `ON` (it is good to set also the `CMAKE_BUILD_TYPE` CMake variable to `Debug` to be able to see the debug information in case of failures):
> ```





_Suggestion:_
```Markdown
1.
```
___
*[`DEVELOPMENT.md` line 125 at r2](https://reviewable.io/reviews/pmem/rpma/1874#-N5Yt_vFDCtn-C4wBBAw:-N5Yt_vFDCtn-C4wBBAx:undefined) ([raw file](https://github.com/pmem/rpma/blob/9a2fbb8ac1e74dafa8e893c12400f0d13139e906/DEVELOPMENT.md#L125)):*
> ```Markdown
> ```
> 
> 5. In order to run the **integration tests** build the librpma library with the `TESTS_RDMA_CONNECTION` and the `DEBUG_FAULT_INJECTION` CMake variables set to `ON`. Valgrind must be installed to run the integration tests. It is good to set also the `CMAKE_BUILD_TYPE` CMake variable to `Debug` to be able to see the debug information in case of failures:
> ```





_Suggestion:_
```Markdown
2.
```

**Review by haichangsi — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1874)* status: all files reviewed, 6 unresolved discussions (waiting on @ldorau)

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1874)* status: all files reviewed, 7 unresolved discussions (waiting on @ldorau)

___
*[`DEVELOPMENT.md` line 129 at r2](https://reviewable.io/reviews/pmem/rpma/1874#-N5Z0NrxBiagVNNZWQTi:-N5Z0NrxBiagVNNZWQTj:b-wbv5jr) ([raw file](https://github.com/pmem/rpma/blob/9a2fbb8ac1e74dafa8e893c12400f0d13139e906/DEVELOPMENT.md#L129)):*
> ```Markdown
> ```sh
> [rpma]$ cd build
> [rpma/build]$ cmake -DCMAKE_BUILD_TYPE=Debug -DTESTS_RDMA_CONNECTION=ON -DDEBUG_FAULT_INJECTION=ON ..
> ```

Do we need or not Valigrind for the fault injection mechanism?



_Suggestion:_
```Markdown
-DDEBUG_FAULT_INJECTION=ON -DTESTS_USE_VALGRIND=ON ..
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1874)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72)

___
*[`DEVELOPMENT.md` line 18 at r2](https://reviewable.io/reviews/pmem/rpma/1874#-N5YqoBo-OhBgjuGjtv5:-N5ZXt113q8phHgTyUrF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9a2fbb8ac1e74dafa8e893c12400f0d13139e906/DEVELOPMENT.md#L18)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

BUILD_DOC is ON by default, let's use a more likely scenario
</blockquote></details>

Done.



_Code quote:_
```Markdown
 cmake -DBUILD_DOC=ON -DCMAKE_BUILD_TYPE=Debu
```
___
*[`DEVELOPMENT.md` line 69 at r2](https://reviewable.io/reviews/pmem/rpma/1874#-N5Yrvk-Da8bcqHW9Wq5:-N5ZYHDW-wR_mMsZr3Xa:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9a2fbb8ac1e74dafa8e893c12400f0d13139e906/DEVELOPMENT.md#L69)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

worth mentioning that it is the default configuration of the librpma 
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 92 at r2](https://reviewable.io/reviews/pmem/rpma/1874#-N5YsjPQDJhC7Y4JI0mx:-N5ZdVcS2ZecxhBroEWe:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9a2fbb8ac1e74dafa8e893c12400f0d13139e906/DEVELOPMENT.md#L92)):*
> ```Markdown
> to print out also the output of the failed tests.
> 
> ## Preparing the environment for running multi-threaded or integration tests on SoftRoCE or RDMA HW
> ```

Done.
___
*[`DEVELOPMENT.md` line 116 at r2](https://reviewable.io/reviews/pmem/rpma/1874#-N5Yt1SXBqQrvoQXVEva:-N5ZdWbo3Qpdo9Mf72jK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9a2fbb8ac1e74dafa8e893c12400f0d13139e906/DEVELOPMENT.md#L116)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

### Build multi-threaded and integration tests
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 117 at r2](https://reviewable.io/reviews/pmem/rpma/1874#-N5YtYj6AVSnfWHRAR1O:-N5ZdjWZ-lhh06MnWFjP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9a2fbb8ac1e74dafa8e893c12400f0d13139e906/DEVELOPMENT.md#L117)):*
> ```Markdown
> The IP address of an RDMA-capable network interface (SoftRoCE or RDMA HW) can be checked using the same commands as for configuring SoftRoCE (listed above).
> 
> 4. In order to run the **multi-threaded tests** build the librpma library with the `TESTS_RDMA_CONNECTION` and the `TESTS_USE_VALGRIND` CMake variables set to `ON` (it is good to set also the `CMAKE_BUILD_TYPE` CMake variable to `Debug` to be able to see the debug information in case of failures):
> ```

Done.
___
*[`DEVELOPMENT.md` line 125 at r2](https://reviewable.io/reviews/pmem/rpma/1874#-N5Yt_vFDCtn-C4wBBAw:-N5ZdkAe1GmuqU76Q6St:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9a2fbb8ac1e74dafa8e893c12400f0d13139e906/DEVELOPMENT.md#L125)):*
> ```Markdown
> ```
> 
> 5. In order to run the **integration tests** build the librpma library with the `TESTS_RDMA_CONNECTION` and the `DEBUG_FAULT_INJECTION` CMake variables set to `ON`. Valgrind must be installed to run the integration tests. It is good to set also the `CMAKE_BUILD_TYPE` CMake variable to `Debug` to be able to see the debug information in case of failures:
> ```

Done.
___
*[`DEVELOPMENT.md` line 129 at r2](https://reviewable.io/reviews/pmem/rpma/1874#-N5Z0NrxBiagVNNZWQTi:-N5ZdmsC2KXiiZWiw5yZ:b59719r) ([raw file](https://github.com/pmem/rpma/blob/9a2fbb8ac1e74dafa8e893c12400f0d13139e906/DEVELOPMENT.md#L129)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Do we need or not Valigrind for the fault injection mechanism?
</blockquote></details>

The fault injection mechanism itself does not need valgrind, but the integrations tests (using the fault injection mechanism) do require valgrind.

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1874)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`DEVELOPMENT.md` line 129 at r2](https://reviewable.io/reviews/pmem/rpma/1874#-N5Z0NrxBiagVNNZWQTi:-N5Zni_S6IYgcGgqvFxq:br1c86u) ([raw file](https://github.com/pmem/rpma/blob/9a2fbb8ac1e74dafa8e893c12400f0d13139e906/DEVELOPMENT.md#L129)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The fault injection mechanism itself does not need valgrind, but the integrations tests (using the fault injection mechanism) do require valgrind.
</blockquote></details>

Perhaps it will be better to have ``TESTS_INTEGRATION_TESTS`` instead of ``DEBUG_FAULT_INJECTION``.
It is more clear from the default execution path logic.
We want to enable INTEGRATION_TESTS ane it is implemented via FAULT_INJECTION mechanism.



_Code quote:_
```Markdown
DEBUG_FAULT_INJECTION
```

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1874)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`DEVELOPMENT.md` line 73 at r3](https://reviewable.io/reviews/pmem/rpma/1874#-N5ZtSpuBCQc_ZQ1CwKX:-N5ZtSpuBCQc_ZQ1CwKY:undefined) ([raw file](https://github.com/pmem/rpma/blob/8d4c70e08dfd454cce125012be1cab341f7098f1/DEVELOPMENT.md#L73)):*
> ```Markdown
> 
> ```sh
> [rpma]$ cd build
> ```





_Suggestion:_
```Markdown
```sh
[rpma]$ cd build
[rpma/build]$ cmake -DCMAKE_BUILD_TYPE=Debug -DTESTS_RDMA_CONNECTION=OFF -DTESTS_USE_VALGRIND=OFF ..
[rpma/build]$ make -j$(nproc)

```
or just
```sh
[rpma]$ cd build; rm -rf *
[rpma/build]$ cmake -DCMAKE_BUILD_TYPE=Debug ..
[rpma/build]$ make -j$(nproc)
```
on empty ``build`` subfolder.
```


<!-- Sent from Reviewable.io -->

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1874#-:-N5_7xpr8CA5AiYJFL1X:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1874)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`DEVELOPMENT.md` line 73 at r3](https://reviewable.io/reviews/pmem/rpma/1874#-N5ZtSpuBCQc_ZQ1CwKX:-N5_G5JF2TKyOTwu3L10:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8d4c70e08dfd454cce125012be1cab341f7098f1/DEVELOPMENT.md#L73)):*
> ```Markdown
> 
> ```sh
> [rpma]$ cd build
> ```

Done.

**Pull request merged**
