### PR TITLE
tools: replace DS (data size) with BS (block size)

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/645)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/645#-:-MO67tnF-wCjyTcEYEtf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/645#-:-MO6V5hVBs94L1UUXxV9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/645)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/645#-MO6_kmv1U2qtG53kH0N:-MO6_kmv1U2qtG53kH0O:bjh6ymg) (no related file):*
If you want to be orthodox we can also rename the array in the `ib_read.sh` script:

```
ib_read.sh:52:  if [ ${#DATA_SIZE[@]} -ne ${#ITERATIONS[@]} ]; then
ib_read.sh:53:          echo "Error: sizes of the arrays: DATA_SIZE(${#DATA_SIZE[@]}) and ITERATIONS(${#ITERATIONS[@]}) are different!"
ib_read.sh:71:  DATA_SIZE=(256 1024 4096 8192 65536)
ib_read.sh:85:  DATA_SIZE=4096
ib_read.sh:90:  NAME="${MODE}-${DATA_SIZE}bs"
ib_read.sh:97:  DATA_SIZE=(1024 4096 65536)
ib_read.sh:123:         BS="${DATA_SIZE[${i}]}"
ib_read.sh:131:         BS="${DATA_SIZE}"
ib_read.sh:140:         BS="${DATA_SIZE[${i}]}"
```

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/645)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @janekmi and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/645#-MO6_kmv1U2qtG53kH0N:-MO6cixq1nVzdS1AlkfS:b-hpyfo5) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

If you want to be orthodox we can also rename the array in the `ib_read.sh` script:

```
ib_read.sh:52:  if [ ${#DATA_SIZE[@]} -ne ${#ITERATIONS[@]} ]; then
ib_read.sh:53:          echo "Error: sizes of the arrays: DATA_SIZE(${#DATA_SIZE[@]}) and ITERATIONS(${#ITERATIONS[@]}) are different!"
ib_read.sh:71:  DATA_SIZE=(256 1024 4096 8192 65536)
ib_read.sh:85:  DATA_SIZE=4096
ib_read.sh:90:  NAME="${MODE}-${DATA_SIZE}bs"
ib_read.sh:97:  DATA_SIZE=(1024 4096 65536)
ib_read.sh:123:         BS="${DATA_SIZE[${i}]}"
ib_read.sh:131:         BS="${DATA_SIZE}"
ib_read.sh:140:         BS="${DATA_SIZE[${i}]}"
```
</blockquote></details>

Right. Done

---

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/645#-:-MO6eeGKAGg_SH6f64ty:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
