### PR TITLE
common: remove -dbgsym pkgs from CircleCI environment

### PR DESCRIPTION
**Pull request by grom72**
For details see:
 https://app.circleci.com/pipelines/github/pmem/rpma/1860/workflows/c18ca9dd-26ab-4caa-a1b1-e95c9b4f8cba/jobs/1881

This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1912)

### CODE REVIEW

**Review by osalyk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1912)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`.circleci/config.yml` line 40 at r1](https://reviewable.io/reviews/pmem/rpma/1912#-N6CCrBF986D74Lv4PB_:-N6CCrBGEUYVLzh-c-Yu:b-sg7ok2) ([raw file](https://github.com/pmem/rpma/blob/117ab33467a78d49d8832e3ee81034aacf699ace/.circleci/config.yml#L40)):*
> ```YAML
>       - run:
>           name: Run tests with memcheck
>           command: cd build && ctest -R "multithreaded.*(none|memcheck)$" --output-on-failure
> ```

Leave as it was or change the run name



_Code quote:_
```YAML
          name: Run tests with memcheck
          command: cd build && ctest -R "multithreaded.*(none|memcheck)$" --output-on-failure
```
___
*[`tests/drd.supp` line 539 at r1](https://reviewable.io/reviews/pmem/rpma/1912#-N6CCYxlA0S-DhF86zbl:-N6CCYxlA0S-DhF86zbm:b-kjseml) ([raw file](https://github.com/pmem/rpma/blob/117ab33467a78d49d8832e3ee81034aacf699ace/tests/drd.supp#L539)):*
> ```
>    fun:rdma_create_qp_ex
>    fun:rdma_create_qp
>    fun:rpma_peer_create_qp
> ```

Please use the template



_Code quote:_
```
{
   General suppression related to internal SoftRoCE Mutex issue
   drd:MutexErr
   fun:pthread_spin_init@*
   obj:/usr/lib/x86_64-linux-gnu/libibverbs/librxe-rdmav34.so
   fun:rdma_create_qp_ex
   fun:rdma_create_qp
   fun:rpma_peer_create_qp
   ...
}
```

**Review by osalyk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1912)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72)

___
*[`tests/drd.supp` line 547 at r3](https://reviewable.io/reviews/pmem/rpma/1912#-N6Cmq9l5kV0hk6YEmMG:-N6Cmq9l5kV0hk6YEmMH:b2ngvnt) ([raw file](https://github.com/pmem/rpma/blob/7b2ae55538756190d5ac4c35372c0d49de5b985f/tests/drd.supp#L547)):*
> ```
>    drd:MutexErr
>    fun:pthread_spin_init@*
>    obj:/usr/lib/x86_64-linux-gnu/libibverbs/librxe-rdmav34.so
> ```

...
___
*[`tests/drd.supp` line 550 at r3](https://reviewable.io/reviews/pmem/rpma/1912#-N6CmreH36ptPWrh4QMe:-N6CmreH36ptPWrh4QMf:b3kqt) ([raw file](https://github.com/pmem/rpma/blob/7b2ae55538756190d5ac4c35372c0d49de5b985f/tests/drd.supp#L550)):*
> ```
>    fun:rdma_create_qp_ex
>    fun:rdma_create_qp
>    fun:rpma_peer_create_qp1
> ```

*

**Review by osalyk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1912)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72)

___
*[`tests/drd.supp` line 550 at r3](https://reviewable.io/reviews/pmem/rpma/1912#-N6CmreH36ptPWrh4QMe:-N6CnMzc8c1TnVyTcwKG:b-axct1p) ([raw file](https://github.com/pmem/rpma/blob/7b2ae55538756190d5ac4c35372c0d49de5b985f/tests/drd.supp#L550)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

*
</blockquote></details>

It was going to be \*

**Review by osalyk — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1912)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @grom72 and @haichangsi)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1912#-:-N6DGZHq0913kBy-gbMS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by osalyk — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1912)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by osalyk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1912)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[`tests/drd.supp` line 535 at r7](https://reviewable.io/reviews/pmem/rpma/1912#-N6DMmw1EA5H5LGV8d2G:-N6DMmw1EA5H5LGV8d2H:bypk5w7) ([raw file](https://github.com/pmem/rpma/blob/884f7a1b2c0f86619a633c35a6d0c4f0dac2742e/tests/drd.supp#L535)):*
> ```
> # Assessment: this suppression indicates a lack of MT safety when SoftRoCE is used.
> #
> # OS - Ubuntu 22.04
> ```

OS: ubuntu-2204:2022.04.1 of CircleCI



_Code quote:_
```
OS - Ubuntu 22.04
```
___
*[`tests/drd.supp` line 536 at r7](https://reviewable.io/reviews/pmem/rpma/1912#-N6DMg5L7uWUANUD3VrS:-N6DMg5L7uWUANUD3VrT:b-y6cwor) ([raw file](https://github.com/pmem/rpma/blob/884f7a1b2c0f86619a633c35a6d0c4f0dac2742e/tests/drd.supp#L536)):*
> ```
> #
> # OS - Ubuntu 22.04
> # OFED - MLNX_OFED 5.6-2.0.9.0
> ```

It is SoftRoCE, not needed



_Code quote:_
```
OFED - MLNX_OFED 5.6-2.0.9.0
```
___
*[`tests/drd.supp` line 538 at r7](https://reviewable.io/reviews/pmem/rpma/1912#-N6DMYbP0X9lrSkcXt1a:-N6DMYbP0X9lrSkcXt1b:brc4irn) ([raw file](https://github.com/pmem/rpma/blob/884f7a1b2c0f86619a633c35a6d0c4f0dac2742e/tests/drd.supp#L538)):*
> ```
> # OFED - MLNX_OFED 5.6-2.0.9.0
> # libibverbs - 1.14.40.0
> # librdmacm - 1.3.40.0
> ```





_Code quote:_
```
# libibverbs - 1.14.40.0
# librdmacm - 1.3.40.0
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1912)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[`tests/drd.supp` line 535 at r7](https://reviewable.io/reviews/pmem/rpma/1912#-N6DMmw1EA5H5LGV8d2G:-N6DOrz041ugzvjq11Nb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/884f7a1b2c0f86619a633c35a6d0c4f0dac2742e/tests/drd.supp#L535)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

OS: ubuntu-2204:2022.04.1 of CircleCI
</blockquote></details>

Done.
___
*[`tests/drd.supp` line 536 at r7](https://reviewable.io/reviews/pmem/rpma/1912#-N6DMg5L7uWUANUD3VrS:-N6DP-VL5vxtAdTTJFgU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/884f7a1b2c0f86619a633c35a6d0c4f0dac2742e/tests/drd.supp#L536)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

It is SoftRoCE, not needed
</blockquote></details>

Done.
___
*[`tests/drd.supp` line 538 at r7](https://reviewable.io/reviews/pmem/rpma/1912#-N6DMYbP0X9lrSkcXt1a:-N6DP2PK77cTsTwPD8I8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/884f7a1b2c0f86619a633c35a6d0c4f0dac2742e/tests/drd.supp#L538)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>


</blockquote></details>

Done.

**Review by osalyk — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1912)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
