### PR TITLE
tools: perf: document lib.format

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1385)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1385)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1385)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/format/fio.py, line 157 at r1](https://reviewable.io/reviews/pmem/rpma/1385#-MpvO9282VXNYKviTAic:-MpvO9282VXNYKviTAid:b-ydwsgx) ([raw file](https://github.com/pmem/rpma/blob/ca7963568a8da312b46b188094f6af1d44379e78/tools/perf/lib/format/fio.py#L157)):*
> ```
>             ....  Under each of
>             the storead a 2nd level `dict` with all the results according to ...
> ```

1) I do not understand this sentence - please rephrase.

2) `a 2nd` -> `the 2nd `
3) `the storead` -> `the stored`
4) `the chosen`

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1385)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/lib/format/fio.py, line 157 at r1](https://reviewable.io/reviews/pmem/rpma/1385#-MpvO9282VXNYKviTAic:-MpvRLOo-3CtO8vlniGw:b-k6olmy) ([raw file](https://github.com/pmem/rpma/blob/ca7963568a8da312b46b188094f6af1d44379e78/tools/perf/lib/format/fio.py#L157)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>             ....  Under each of
>             the storead a 2nd level `dict` with all the results according to ...
> ```

1) I do not understand this sentence - please rephrase.

2) `a 2nd` -> `the 2nd `
3) `the storead` -> `the stored`
4) `the chosen`
</blockquote></details>

What do you think now?

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1385)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

___
*[tools/perf/lib/format/fio.py, line 157 at r1](https://reviewable.io/reviews/pmem/rpma/1385#-MpvO9282VXNYKviTAic:-MpvRWJfAZIgGlTsKNp1:b-k1hkpz) ([raw file](https://github.com/pmem/rpma/blob/ca7963568a8da312b46b188094f6af1d44379e78/tools/perf/lib/format/fio.py#L157)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

What do you think now?
</blockquote></details>

Great :-D

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1385#-:-MpvWbdA79CJDgSgBr4n:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1385#-:-MpvXbo173UZfKaX_0FS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1385)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1385)* status: all files reviewed, 2 unresolved discussions

___
*[tools/perf/lib/format/fio.py, line 149 at r2](https://reviewable.io/reviews/pmem/rpma/1385#-MpvY_Ay4svNCaFdw9mz:-MpvY_Ay4svNCaFdw9n-:b-i0bh9k) ([raw file](https://github.com/pmem/rpma/blob/26ca69e529f277b42ccb19978515f25041fbbca1/tools/perf/lib/format/fio.py#L149)):*
> ```
> parse
> ```
parse_row
___
*[tools/perf/lib/format/fio.py, line 152 at r2](https://reviewable.io/reviews/pmem/rpma/1385#-MpvYk-MCOgvqS688-oh:-MpvYk-MCOgvqS688-oi:bg6m0ot) ([raw file](https://github.com/pmem/rpma/blob/26ca69e529f277b42ccb19978515f25041fbbca1/tools/perf/lib/format/fio.py#L152)):*
> ```
> follow
> ```
can we also provide an example of input?

**Pull request merged**
