### PR TITLE
examples: remove unnecessary rpma_conn_req_delete()

### PR DESCRIPTION
**Pull request by osalyk**
#1747

- - -
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/2010)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 9 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2010)* status: 9 of 10 files reviewed, 5 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`examples/09-flush-to-persistent-GPSPM/server.c` line 177 at r1](https://reviewable.io/reviews/pmem/rpma/2010#-NAmiGacEvkCFOCRETY5:-NAmiGacEvkCFOCRETY6:undefined) ([raw file](https://github.com/pmem/rpma/blob/d30046572c4179357e4fc96b7f722fc3b7dd5b0c/examples/09-flush-to-persistent-GPSPM/server.c#L177)):*
> ```C
> 	/* accept the connection request and obtain the connection object */
> 	if ((ret = rpma_conn_req_connect(&req, &pdata, &conn)))
> 		return ret;
> ```





_Suggestion:_
```C
goto err_cfg_delete;
```
___
*[`examples/09-flush-to-persistent-GPSPM/server.c` line 285 at r1](https://reviewable.io/reviews/pmem/rpma/2010#-NAmixsZ-Ml1u0qsXkB2:-NAmixsZ-Ml1u0qsXkB3:b-eg9rbt) ([raw file](https://github.com/pmem/rpma/blob/d30046572c4179357e4fc96b7f722fc3b7dd5b0c/examples/09-flush-to-persistent-GPSPM/server.c#L285)):*
> ```C
> 	(void) printf("New value: %s\n", (char *)mem.mr_ptr + mem.data_offset);
> 
> err_conn_delete:
> ```

conn_req shall not be deleted if conn is deleted



_Suggestion:_
```C
err_conn_delete:
	(void) rpma_conn_delete(&conn);
	goto err_cfg_delete; 

err_req_delete:
	(void) rpma_conn_req_delete(&req);
```
___
*[`examples/09scch-flush-to-persistent-GPSPM/server.c` line 178 at r1](https://reviewable.io/reviews/pmem/rpma/2010#-NAmjUqL1jwd2GxsLH9O:-NAmjUqL1jwd2GxsLH9P:undefined) ([raw file](https://github.com/pmem/rpma/blob/d30046572c4179357e4fc96b7f722fc3b7dd5b0c/examples/09scch-flush-to-persistent-GPSPM/server.c#L178)):*
> ```C
> 	/* accept the connection request and obtain the connection object */
> 	if ((ret = rpma_conn_req_connect(&req, &pdata, &conn)))
> 		return ret;
> ```





_Suggestion:_
```C
goto err_cfg_delete;
```
___
*[`examples/10-send-with-imm/server.c` line 83 at r1](https://reviewable.io/reviews/pmem/rpma/2010#-NAmjptt3EjEojXaoHx2:-NAmjptt3EjEojXaoHx3:undefined) ([raw file](https://github.com/pmem/rpma/blob/d30046572c4179357e4fc96b7f722fc3b7dd5b0c/examples/10-send-with-imm/server.c#L83)):*
> ```C
> 
> 	/* accept the connection request and obtain the connection object */
> 	ret = rpma_conn_req_connect(&req, NULL, &conn);
> ```





_Suggestion:_
```C
	if (ret = rpma_conn_req_connect(&req, NULL, &conn))
	
```
___
*[`examples/11-write-with-imm/server.c` line 115 at r1](https://reviewable.io/reviews/pmem/rpma/2010#-NAmjzobAMhfd1LI6Gsf:-NAmjzobAMhfd1LI6Gsg:undefined) ([raw file](https://github.com/pmem/rpma/blob/d30046572c4179357e4fc96b7f722fc3b7dd5b0c/examples/11-write-with-imm/server.c#L115)):*
> ```C
> 	pdata.ptr = &dst_data;
> 	pdata.len = sizeof(struct common_data);
> 	ret = rpma_conn_req_connect(&req, &pdata, &conn);
> ```





_Suggestion:_
```C
	if (ret = rpma_conn_req_connect(&req, &pdata, &conn))
	
```

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2010)* status: 9 of 10 files reviewed, 5 unresolved discussions (waiting on @grom72 and @osalyk)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2010)* status: all files reviewed, 5 unresolved discussions (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2010)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72)

___
*[`examples/09-flush-to-persistent-GPSPM/server.c` line 177 at r1](https://reviewable.io/reviews/pmem/rpma/2010#-NAmiGacEvkCFOCRETY5:-NAmpWNyAdErUch_EMXk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d30046572c4179357e4fc96b7f722fc3b7dd5b0c/examples/09-flush-to-persistent-GPSPM/server.c#L177)):*
> ```C
> 	/* accept the connection request and obtain the connection object */
> 	if ((ret = rpma_conn_req_connect(&req, &pdata, &conn)))
> 		return ret;
> ```

Done.
___
*[`examples/09-flush-to-persistent-GPSPM/server.c` line 285 at r1](https://reviewable.io/reviews/pmem/rpma/2010#-NAmixsZ-Ml1u0qsXkB2:-NAmpraQ1hVRkiY-tcDV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d30046572c4179357e4fc96b7f722fc3b7dd5b0c/examples/09-flush-to-persistent-GPSPM/server.c#L285)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

conn_req shall not be deleted if conn is deleted
</blockquote></details>

Done.
___
*[`examples/09scch-flush-to-persistent-GPSPM/server.c` line 178 at r1](https://reviewable.io/reviews/pmem/rpma/2010#-NAmjUqL1jwd2GxsLH9O:-NAmpybuDfRO5RdSnTxq:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d30046572c4179357e4fc96b7f722fc3b7dd5b0c/examples/09scch-flush-to-persistent-GPSPM/server.c#L178)):*
> ```C
> 	/* accept the connection request and obtain the connection object */
> 	if ((ret = rpma_conn_req_connect(&req, &pdata, &conn)))
> 		return ret;
> ```

Done.
___
*[`examples/10-send-with-imm/server.c` line 83 at r1](https://reviewable.io/reviews/pmem/rpma/2010#-NAmjptt3EjEojXaoHx2:-NAmsOHE0A-KhW7KiHIQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d30046572c4179357e4fc96b7f722fc3b7dd5b0c/examples/10-send-with-imm/server.c#L83)):*
> ```C
> 
> 	/* accept the connection request and obtain the connection object */
> 	ret = rpma_conn_req_connect(&req, NULL, &conn);
> ```

Done.
___
*[`examples/11-write-with-imm/server.c` line 115 at r1](https://reviewable.io/reviews/pmem/rpma/2010#-NAmjzobAMhfd1LI6Gsf:-NAmrWVo9VdaNoMsUE5w:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d30046572c4179357e4fc96b7f722fc3b7dd5b0c/examples/11-write-with-imm/server.c#L115)):*
> ```C
> 	pdata.ptr = &dst_data;
> 	pdata.len = sizeof(struct common_data);
> 	ret = rpma_conn_req_connect(&req, &pdata, &conn);
> ```

Done.

**Review by haichangsi — COMMENTED** [review]
> Reviewed 6 of 10 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2010)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2010)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/pmem/rpma/2010#-NArZrePCYt4y7UABcKp):*
Ref: #1747

**Review by ldorau — COMMENTED** [review]
> Reviewed 6 of 10 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2010)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2010)* status: all files reviewed (commit messages unreviewed), 6 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/pmem/rpma/2010#-NArZrePCYt4y7UABcKp):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Ref: #1747
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2010)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2010)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
The integration tests have passed.

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2010#-:-NAsnyhK1qqjJT_50tps:bksprbj)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2010#-:-NAs-5fM0jkVmAixz7fj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2010)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
The integration tests:
https://app.circleci.com/pipelines/github/ldorau/rpma?branch=examples-run-all-examples-with-the-maximum-fault-injection-SERVER
https://app.circleci.com/pipelines/github/ldorau/rpma?branch=examples-run-all-examples-with-the-maximum-fault-injection-CLIENT

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2010#-:-NAwqHHz1X8JsYndC_fO:b-35fv27)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
