### PR TITLE
 common: run pytest in CI builds

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #1163 
- [x] #1165

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1164)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
It requires a fix for the following error;

```
==================================== ERRORS ====================================
_________________ ERROR at setup of test_dummy_results[False] __________________
file /rpma/tools/perf/tests/lib/benchmark/test_run.py, line 296
  @pytest.mark.parametrize('dummy_results', [False, True])
  def test_dummy_results(dummy_results, benchmark_dummy, tmp_path, monkeypatch):
E       fixture 'tmp_path' not found
>       available fixtures: benchmark_dummy, cache, capfd, capsys, doctest_namespace, monkeypatch, pytestconfig, record_xml_property, recwarn, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/rpma/tools/perf/tests/lib/benchmark/test_run.py:296
__________________ ERROR at setup of test_dummy_results[True] __________________
file /rpma/tools/perf/tests/lib/benchmark/test_run.py, line 296
  @pytest.mark.parametrize('dummy_results', [False, True])
  def test_dummy_results(dummy_results, benchmark_dummy, tmp_path, monkeypatch):
E       fixture 'tmp_path' not found
>       available fixtures: benchmark_dummy, cache, capfd, capsys, doctest_namespace, monkeypatch, pytestconfig, record_xml_property, recwarn, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/rpma/tools/perf/tests/lib/benchmark/test_run.py:296
===================== 281 passed, 2 error in 0.92 seconds ======================
```

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1164#-:-MfbTrvQ32lO98EhgjHC:b-z8lv7g)* status: 0 of 5 files reviewed, all discussions resolved

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1164)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[utils/docker/run-build.sh, line 167 at r2](https://reviewable.io/reviews/pmem/rpma/1164#-MfcMeH231R73-JyUlG4:-MfcMeH231R73-JyUlG5:b-7xbvw0) ([raw file](https://github.com/pmem/rpma/blob/c8ec83e8454f687686ae1f37bfef4ca149ca59f3/utils/docker/run-build.sh#L167)):*
> ```Shell
> 	echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
> 	echo "!!! NOTICE: pytest not found - skipping python tests !!!"
> 	echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
> ```

Isn't it the same? I am considering using the same format of the message.

```c
				echo
				echo "SKIP: Skipping the '$e' example, because libprotobuf-c is missing"
				echo
```
___
*[utils/docker/images/Dockerfile.debian-9, line 65 at r2](https://reviewable.io/reviews/pmem/rpma/1164#-MfcM3ieAHBd0VcVPvoM:-MfcM3ieAHBd0VcVPvoN:b-uad276) ([raw file](https://github.com/pmem/rpma/blob/c8ec83e8454f687686ae1f37bfef4ca149ca59f3/utils/docker/images/Dockerfile.debian-9#L65)):*
> ```
> && rm -rf /var/lib/apt/lists/*
> 
> # create link for pytest
> ```

a link
___
*[utils/docker/images/Dockerfile.debian-9, line 66 at r2](https://reviewable.io/reviews/pmem/rpma/1164#-MfcMKsG8PqPW04keQwi:-MfcMKsG8PqPW04keQwj:b5x2i4k) ([raw file](https://github.com/pmem/rpma/blob/c8ec83e8454f687686ae1f37bfef4ca149ca59f3/utils/docker/images/Dockerfile.debian-9#L66)):*
> ```
> 
> # create link for pytest
> RUN ln -s /usr/bin/pytest-3 /usr/bin/pytest
> ```

The symlink is not created automatically?
___
*[utils/docker/images/Dockerfile.debian-9, line 91 at r2](https://reviewable.io/reviews/pmem/rpma/1164#-MfcLoPr4Y6_2z3linl2:-MfcLoPr4Y6_2z3linl3:b251y7l) ([raw file](https://github.com/pmem/rpma/blob/c8ec83e8454f687686ae1f37bfef4ca149ca59f3/utils/docker/images/Dockerfile.debian-9#L91)):*
> ```
> RUN pip3 install --user pandas
> RUN pip3 install --user matplotlib
> RUN pip3 install --user markdown2
> ```

Maybe introduce also a variable for all of these? Just to keep all packages in a similar fashion?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1164)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[utils/docker/run-build.sh, line 167 at r2](https://reviewable.io/reviews/pmem/rpma/1164#-MfcMeH231R73-JyUlG4:-MffezLW9kpMtvlkoQLI:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c8ec83e8454f687686ae1f37bfef4ca149ca59f3/utils/docker/run-build.sh#L167)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Isn't it the same? I am considering using the same format of the message.

```c
				echo
				echo "SKIP: Skipping the '$e' example, because libprotobuf-c is missing"
				echo
```
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.debian-9, line 65 at r2](https://reviewable.io/reviews/pmem/rpma/1164#-MfcM3ieAHBd0VcVPvoM:-MffcmPP14iEc9npIoSl:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c8ec83e8454f687686ae1f37bfef4ca149ca59f3/utils/docker/images/Dockerfile.debian-9#L65)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

a link
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.debian-9, line 66 at r2](https://reviewable.io/reviews/pmem/rpma/1164#-MfcMKsG8PqPW04keQwi:-MffbwHf5grzTP2uLGtQ:b-an9iu2) ([raw file](https://github.com/pmem/rpma/blob/c8ec83e8454f687686ae1f37bfef4ca149ca59f3/utils/docker/images/Dockerfile.debian-9#L66)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The symlink is not created automatically?
</blockquote></details>

No, it isn't. If it were, I wouldn't do that.
___
*[utils/docker/images/Dockerfile.debian-9, line 91 at r2](https://reviewable.io/reviews/pmem/rpma/1164#-MfcLoPr4Y6_2z3linl2:-Mffe68yDohJ8BKSWRgu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c8ec83e8454f687686ae1f37bfef4ca149ca59f3/utils/docker/images/Dockerfile.debian-9#L91)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Maybe introduce also a variable for all of these? Just to keep all packages in a similar fashion?
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1164#-:-Mffv5DI6GvlFkWNWKwH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
@osalyk please review

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1164#-:-MfgEhIHEqkrlJTPjXER:bqeplii)* status: 4 of 6 files reviewed, all discussions resolved (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1164)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1164#-:-MfgOAkM7CrsGAJWy4ed:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
