### PR TITLE
tools: perf: improve scripts documentation

### PR DESCRIPTION
**Pull request by janekmi**
Including:
- docstrings
- argparse --help

Taking into account the pdoc3 output readability.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1357)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1357)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[tools/perf/report_create.py, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1357#-MpeeGmG9wFcGS8bKPwU:-MpeeGmG9wFcGS8bKPwV:b-i9nfgj) ([raw file](https://github.com/pmem/rpma/blob/043d845b973121c9d066a9ed9346834571dcfb2a/tools/perf/report_create.py#L13)):*
> ```
> Restore
> ```
How to understand "Restore" here?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1357)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/perf/report_create.py, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1357#-MpeeGmG9wFcGS8bKPwU:-MpfWISBEaAL-W3qkeUO:b6s6zct) ([raw file](https://github.com/pmem/rpma/blob/043d845b973121c9d066a9ed9346834571dcfb2a/tools/perf/report_create.py#L13)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Restore
> ```
How to understand "Restore" here?
</blockquote></details>

A `Bench` object has an internal state it is written down (cached) into a JSON file (bench.json).
When the execution is resumed the content of the bench.json file is read and the original `Bench` object is recreated/restored.

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1357)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1357)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tools/perf/report_bench.py, line 38 at r1](https://reviewable.io/reviews/pmem/rpma/1357#-Mpfs2YO9gmmmhIS9XzZ:-Mpfs2YO9gmmmhIS9Xz_:bq8eyju) ([raw file](https://github.com/pmem/rpma/blob/043d845b973121c9d066a9ed9346834571dcfb2a/tools/perf/report_bench.py#L38)):*
> ```
> descrbing
> ```

describing
___
*[tools/perf/report_figures.py, line 51 at r1](https://reviewable.io/reviews/pmem/rpma/1357#-MpfsxZ51aJUkmGnU-_-:-MpfsxZ51aJUkmGnU-_0:b-brs1j2) ([raw file](https://github.com/pmem/rpma/blob/043d845b973121c9d066a9ed9346834571dcfb2a/tools/perf/report_figures.py#L51)):*
> ```
> def generate_figures(args: argparse.Namespace) -> None:
> ```

What does this syntax mean? Could you paste a link to the relevant documentation?
___
*[tools/perf/report_figures.py, line 52 at r1](https://reviewable.io/reviews/pmem/rpma/1357#-MpftAly5iVCwbjEFHNi:-MpftAly5iVCwbjEFHNj:bhbdrhm) ([raw file](https://github.com/pmem/rpma/blob/043d845b973121c9d066a9ed9346834571dcfb2a/tools/perf/report_figures.py#L52)):*
> ```
> XXXX Loop 
> ```

Start this sentence from the new line to make it more visible, please

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1357)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[tools/perf/report_figures.py, line 51 at r1](https://reviewable.io/reviews/pmem/rpma/1357#-MpfsxZ51aJUkmGnU-_-:-Mpfu-nv-NJZ9BLO1ipw:blqiblh) ([raw file](https://github.com/pmem/rpma/blob/043d845b973121c9d066a9ed9346834571dcfb2a/tools/perf/report_figures.py#L51)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> def generate_figures(args: argparse.Namespace) -> None:
> ```

What does this syntax mean? Could you paste a link to the relevant documentation?
</blockquote></details>

Sure.

Ref: https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1357)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/report_create.py, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1357#-MpeeGmG9wFcGS8bKPwU:-Mpfvx4466Rc9NRCDcBr:b-4gg84a) ([raw file](https://github.com/pmem/rpma/blob/043d845b973121c9d066a9ed9346834571dcfb2a/tools/perf/report_create.py#L13)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

A `Bench` object has an internal state it is written down (cached) into a JSON file (bench.json).
When the execution is resumed the content of the bench.json file is read and the original `Bench` object is recreated/restored.
</blockquote></details>

Now it is clear ;). I suggest to add this to source documentation

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1357)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/report_figures.py, line 51 at r1](https://reviewable.io/reviews/pmem/rpma/1357#-MpfsxZ51aJUkmGnU-_-:-MpfxICKAShwcwy9V4Kb:b-ucfknh) ([raw file](https://github.com/pmem/rpma/blob/043d845b973121c9d066a9ed9346834571dcfb2a/tools/perf/report_figures.py#L51)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Sure.

Ref: https://mypy.readthedocs.io/en/stable/cheat_sheet_py3.html
</blockquote></details>

Thanks!

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1357)* status: 1 of 4 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/report_bench.py, line 38 at r1](https://reviewable.io/reviews/pmem/rpma/1357#-Mpfs2YO9gmmmhIS9XzZ:-MpfxSXy9nKgrpIDvsGb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/043d845b973121c9d066a9ed9346834571dcfb2a/tools/perf/report_bench.py#L38)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> descrbing
> ```

describing
</blockquote></details>

Done.
___
*[tools/perf/report_create.py, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1357#-MpeeGmG9wFcGS8bKPwU:-Mpfz37S4Zy7Nn4hdVha:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/043d845b973121c9d066a9ed9346834571dcfb2a/tools/perf/report_create.py#L13)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Now it is clear ;). I suggest to add this to source documentation
</blockquote></details>

Done.
___
*[tools/perf/report_figures.py, line 52 at r1](https://reviewable.io/reviews/pmem/rpma/1357#-MpftAly5iVCwbjEFHNi:-Mpg0KNp3VH9BVUD1elW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/043d845b973121c9d066a9ed9346834571dcfb2a/tools/perf/report_figures.py#L52)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> XXXX Loop 
> ```

Start this sentence from the new line to make it more visible, please
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1357)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
:lgtm: except of failing builds - please fix

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1357#-:-MpgEgXwE2VIfIyyxWdu:b-mw4kps)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1357)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 4 files at r1, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1357#-:-MpgPF-45NijvWVw0Sio:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1357#-:-MpgRxWz73jS6leqYQxY:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1357)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/perf/report_create.py, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1357#-MpeeGmG9wFcGS8bKPwU:-MpgSPTe9FxJlibSgh9c:b-f0lly4) ([raw file](https://github.com/pmem/rpma/blob/043d845b973121c9d066a9ed9346834571dcfb2a/tools/perf/report_create.py#L13)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I see it is fixed.

**Pull request merged**
