### PR TITLE
tools: add REMOTE_SAR_RESULTS_DIR to REMOTE_CMD_PRE/POST

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #934

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/935)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/935)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/rpma_fio_bench.sh, line 45 at r1](https://reviewable.io/reviews/pmem/rpma/935#-MVsEri91jcbzQFoC8A-:-MVsEri91jcbzQFoC8A0:b-oshzxs) ([raw file](https://github.com/pmem/rpma/blob/5734e319e078fb4e6e00b46aaec1f42ea5de09fe/tools/perf/rpma_fio_bench.sh#L45)):*
> ```Shell
> 	echo "export REMOTE_ANOTHER_NUMA=1"
> 	echo "export REMOTE_SAR_RESULTS_DIR=/tmp/"
> 	echo "export REMOTE_CMD_PRE='rm -f \${REMOTE_SAR_RESULTS_DIR}sar.dat; numactl -N \${REMOTE_ANOTHER_NUMA} sar -u -P \${REMOTE_JOB_NUMA_CPULIST} -o \${REMOTE_SAR_RESULTS_DIR}sar.dat 5 > /dev/null'"
> ```

I think it will be less error-prone having:

```sh
$ export dir=/tmp
$ ls $dir/subdir # this
$ ls ${dir}subdir # instead of this
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/935)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/rpma_fio_bench.sh, line 45 at r1](https://reviewable.io/reviews/pmem/rpma/935#-MVsEri91jcbzQFoC8A-:-MW-7yQFE9z0Vk2PMgpX:b-fes7l3) ([raw file](https://github.com/pmem/rpma/blob/5734e319e078fb4e6e00b46aaec1f42ea5de09fe/tools/perf/rpma_fio_bench.sh#L45)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think it will be less error-prone having:

```sh
$ export dir=/tmp
$ ls $dir/subdir # this
$ ls ${dir}subdir # instead of this
```
</blockquote></details>

In case of your proposal, if a user does not define `REMOTE_SAR_RESULTS_DIR`, the script will try to save results to the `/sar.dat` file in the root directory, what is not a good solution ;-)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/935#-:-MW3rEJC1lkSU6ANBR-C:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

___
*[tools/perf/rpma_fio_bench.sh, line 45 at r1](https://reviewable.io/reviews/pmem/rpma/935#-MVsEri91jcbzQFoC8A-:-MW3qsoT03hNV0fqaP5Q:b-ii5sth) ([raw file](https://github.com/pmem/rpma/blob/5734e319e078fb4e6e00b46aaec1f42ea5de09fe/tools/perf/rpma_fio_bench.sh#L45)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

In case of your proposal, if a user does not define `REMOTE_SAR_RESULTS_DIR`, the script will try to save results to the `/sar.dat` file in the root directory, what is not a good solution ;-)
</blockquote></details>

You are right. ;-)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/935#-:-MW3vjLb4fwpg0yhPoGI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
