### PR TITLE
tools: add 'all' options to ib_read.sh

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/679)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/679#-:-MOkK-a_3yfBSgRG7Uc7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/679)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/ib_read.sh, line 148 at r1](https://reviewable.io/reviews/pmem/rpma/679#-MOkt0ac6FKwLSAHfMrf:-MOkt0ac6FKwLSAHfMrg:b-qjqm4j) ([raw file](https://github.com/pmem/rpma/blob/064e2ff3278e039803c5ec9f456c11ed73d3a53e/tools/ib_read.sh#L148)):*
> ```
> TIMESTAMP=$(date +%y-%m-%d-%H%M%S)
> ```
shall we use a common timestamp for all benchmark file names when the **all** option is in use?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/679)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @osalyk)

___
*[tools/ib_read.sh, line 148 at r1](https://reviewable.io/reviews/pmem/rpma/679#-MOkt0ac6FKwLSAHfMrf:-MOkvM467kIq_tE-etkI:biw8y1v) ([raw file](https://github.com/pmem/rpma/blob/064e2ff3278e039803c5ec9f456c11ed73d3a53e/tools/ib_read.sh#L148)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> TIMESTAMP=$(date +%y-%m-%d-%H%M%S)
> ```
shall we use a common timestamp for all benchmark file names when the **all** option is in use?
</blockquote></details>

Right. Done.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/679#-:-MOl3hgqE_mGevBsOJSn:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/679)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
@janekmi please review

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/679#-:-MPcU2cQ-XGhDvwcW8_M:b-f79qgk)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/679)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/ib_read.sh, line 250 at r2](https://reviewable.io/reviews/pmem/rpma/679#-MPcXQbO8phf0OAnZGBZ:-MPcXQbO8phf0OAnZGB_:b-gl6i7r) ([raw file](https://github.com/pmem/rpma/blob/1d0c7c1f79eb96460cd9e092d0f9d0066cf195f6/tools/ib_read.sh#L250)):*
> ```Shell
> else
> 	benchmark_one $MODE $SERVER_IP
> fi
> ```

```sh
if [ "$MODES" == "all" ]; then
    MODES="$MODES_ALL"
fi

for m in $MODES; do
    benchmark_one $m $SERVER_IP
done
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/679)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[tools/ib_read.sh, line 250 at r2](https://reviewable.io/reviews/pmem/rpma/679#-MPcXQbO8phf0OAnZGBZ:-MPcaWLX2NXWYeg1kb-j:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1d0c7c1f79eb96460cd9e092d0f9d0066cf195f6/tools/ib_read.sh#L250)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```sh
if [ "$MODES" == "all" ]; then
    MODES="$MODES_ALL"
fi

for m in $MODES; do
    benchmark_one $m $SERVER_IP
done
```
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/679#-:-MPcnYuD0Bfz9WFFCg51:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
