### PR TITLE
examples: use shared completion channel in example 14

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1708)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
:goat: 

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1708#-:-N0iwq_N5IXDVORLV-sD:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[`examples/14-receive-completion-queue-SHCCH/client.c` line 139 at r1](https://reviewable.io/reviews/pmem/rpma/1708#-N0ivwtm7ZR-6nyT5Oh1:-N0ivwtm7ZR-6nyT5Oh2:b-xh4eg8) ([raw file](https://github.com/pmem/rpma/blob/b77e9066894c9a848fc5985e3894abe962a4d9ce/examples/14-receive-completion-queue-SHCCH/client.c#L139)):*
> ```C
> 	*send = I_M_DONE;
> 	if ((ret = rpma_send(conn, send_mr, 0, MSG_SIZE, RPMA_F_COMPLETION_ON_ERROR, NULL)))
> 		goto err_conn_disconnect;
> ```

What is the purpose of goto to the next line of code?



_Code quote:_
```C
goto err_conn_disconnect;
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1708)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`examples/14-receive-completion-queue-SHCCH/client.c` line 139 at r1](https://reviewable.io/reviews/pmem/rpma/1708#-N0ivwtm7ZR-6nyT5Oh1:-N0iyA7f-Ds-OAdv1107:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b77e9066894c9a848fc5985e3894abe962a4d9ce/examples/14-receive-completion-queue-SHCCH/client.c#L139)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

What is the purpose of goto to the next line of code?
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1708)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — COMMENTED** [review]
> Reviewed 4 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1708)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1708#-:-N0jBMNu1ZwIxTveX2rg:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1708#-:-N0jLHSs8xrnVqSNavuU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1708)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
