### PR TITLE
tools: implement __set_DDIO

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1401)

### CODE REVIEW

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1401)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1401)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/lib/Requirement.py, line 216 at r1](https://reviewable.io/reviews/pmem/rpma/1401#-MqOz-DC29TjUlfr2N2z:-MqOz-DC29TjUlfr2N3-:bqvt8u2) ([raw file](https://github.com/pmem/rpma/blob/85dc44c9a482b5c8fa1e9a3bcf9fec8647f9cf72/tools/perf/lib/Requirement.py#L216)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>             ddio = '../ddio.sh'
>             remote_dir = '/dev/shm'
>             remote_ddio = '/dev/shm/ddio.sh'
> 
> ```
</details>

ddio = '/ddio.h'
local_dir = '..'
local_ddio = local_dir + ddio
remote_dir = '/dev/shm'
remote_ddio = remote_dir +ddio
....
RemoteCmd.copy_to_remote(config, local_ddio, remote_dir)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1401)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/perf/lib/Requirement.py, line 216 at r1](https://reviewable.io/reviews/pmem/rpma/1401#-MqOz-DC29TjUlfr2N2z:-MqP3UY_0KWrLEg3KYBL:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/85dc44c9a482b5c8fa1e9a3bcf9fec8647f9cf72/tools/perf/lib/Requirement.py#L216)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
>             ddio = '../ddio.sh'
>             remote_dir = '/dev/shm'
>             remote_ddio = '/dev/shm/ddio.sh'
> 
> ```
ddio = '/ddio.h'
local_dir = '..'
local_ddio = local_dir + ddio
remote_dir = '/dev/shm'
remote_ddio = remote_dir +ddio
....
RemoteCmd.copy_to_remote(config, local_ddio, remote_dir)
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1401)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/lib/Requirement.py, line 215 at r2](https://reviewable.io/reviews/pmem/rpma/1401#-MqP40nnBTiPABjDgs0x:-MqP40nnBTiPABjDgs0y:bm5zly9) ([raw file](https://github.com/pmem/rpma/blob/a2de165ea5830c8af6da9fd5bfe78ea51b62b3c7/tools/perf/lib/Requirement.py#L215)):*
> ```
> ddio = 'ddio.sh'
> ```
ddio = '/ddio.sh'
or add '/' to all in any other way

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1401)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @grom72 and @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1401)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1401)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[tools/perf/lib/Requirement.py, line 215 at r2](https://reviewable.io/reviews/pmem/rpma/1401#-MqP40nnBTiPABjDgs0x:-MqP4JmND-fCK0IAEmRN:b83n9s5) ([raw file](https://github.com/pmem/rpma/blob/a2de165ea5830c8af6da9fd5bfe78ea51b62b3c7/tools/perf/lib/Requirement.py#L215)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> ddio = 'ddio.sh'
> ```
ddio = '/ddio.sh'
or add '/' to all in any other way
</blockquote></details>

No, `join()` adds '/' during joining paths

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1401#-:-MqPEx7n181DGxoFTqAB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
