### PR TITLE
common: add matplotlib, pytest and co. to Docker files

### PR DESCRIPTION
**Pull request by ldorau**
Add matplotlib, pytest and other required python packages
to Docker files of OSes tested in nightly CI builds.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1256)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
:goat: 

> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1256#-:-MiccEgk-u8tfP358Xj7:bdycpsm)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[utils/docker/images/Dockerfile.debian-10, line 71 at r1](https://reviewable.io/reviews/pmem/rpma/1256#-MicaWBV8NZvwiECO_v8:-MicaWBV8NZvwiECO_v9:b-k0o2wi) ([raw file](https://github.com/pmem/rpma/blob/efcec7b15b8681aa95c01106349404cd333eeca8/utils/docker/images/Dockerfile.debian-10#L71)):*
> ```
> && rm -rf /var/lib/apt/lists/*
> 
> RUN pip3 install --upgrade pip
> ```

Why it is necessary?
___
*[utils/docker/images/Dockerfile.fedora-29, line 72 at r1](https://reviewable.io/reviews/pmem/rpma/1256#-Micajrk9aIQAHU21CD_:-Micajrk9aIQAHU21CDa:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/efcec7b15b8681aa95c01106349404cd333eeca8/utils/docker/images/Dockerfile.fedora-29#L72)):*
> ```
> && dnf clean all
> 
> RUN pip3 install --upgrade pip
> ```

.
___
*[utils/docker/images/Dockerfile.fedora-30, line 71 at r1](https://reviewable.io/reviews/pmem/rpma/1256#-MicamQR4EZsyW7ONd6V:-MicamQR4EZsyW7ONd6W:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/efcec7b15b8681aa95c01106349404cd333eeca8/utils/docker/images/Dockerfile.fedora-30#L71)):*
> ```
> && dnf clean all
> 
> RUN pip3 install --upgrade pip
> ```

.
___
*[utils/docker/images/Dockerfile.fedora-31, line 71 at r1](https://reviewable.io/reviews/pmem/rpma/1256#-Micaoeb6lEqv25x4L2A:-Micaoeb6lEqv25x4L2B:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/efcec7b15b8681aa95c01106349404cd333eeca8/utils/docker/images/Dockerfile.fedora-31#L71)):*
> ```
> && dnf clean all
> 
> RUN pip3 install --upgrade pip
> ```

.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1256)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[utils/docker/images/Dockerfile.debian-10, line 71 at r1](https://reviewable.io/reviews/pmem/rpma/1256#-MicaWBV8NZvwiECO_v8:-MieH8Td50wqhp2ZYcvK:b-geyflm) ([raw file](https://github.com/pmem/rpma/blob/efcec7b15b8681aa95c01106349404cd333eeca8/utils/docker/images/Dockerfile.debian-10#L71)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Why it is necessary?
</blockquote></details>

Without it "`pip3 install --user $PYTHON_DEPS`" fails, see for example: 
https://github.com/ldorau/rpma/runs/3481187453?check_suite_focus=true
___
*[utils/docker/images/Dockerfile.fedora-29, line 72 at r1](https://reviewable.io/reviews/pmem/rpma/1256#-Micajrk9aIQAHU21CD_:-MieIITv69Od-bvYFhtq:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/efcec7b15b8681aa95c01106349404cd333eeca8/utils/docker/images/Dockerfile.fedora-29#L72)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

.
___
*[utils/docker/images/Dockerfile.fedora-30, line 71 at r1](https://reviewable.io/reviews/pmem/rpma/1256#-MicamQR4EZsyW7ONd6V:-MieIJtR0fbfBVqe-NHV:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/efcec7b15b8681aa95c01106349404cd333eeca8/utils/docker/images/Dockerfile.fedora-30#L71)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

.
___
*[utils/docker/images/Dockerfile.fedora-31, line 71 at r1](https://reviewable.io/reviews/pmem/rpma/1256#-Micaoeb6lEqv25x4L2A:-MieIL-x5m1XED06eMkM:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/efcec7b15b8681aa95c01106349404cd333eeca8/utils/docker/images/Dockerfile.fedora-31#L71)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 21 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1256#-:-MifLL4yBwXR48BsXeGt:bnfp4nl)* status: 7 of 25 files reviewed, 4 unresolved discussions (waiting on @janekmi)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 21 of 21 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1256)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[utils/docker/images/Dockerfile.archlinux-latest, line 67 at r2](https://reviewable.io/reviews/pmem/rpma/1256#-MitgEDF3s_nA4B5Slnd:-MitgEDG05W46M0MswWm:b-aufs8o) ([raw file](https://github.com/pmem/rpma/blob/d60af373b52e48e5b8945bf025c2f8861310b358/utils/docker/images/Dockerfile.archlinux-latest#L67)):*
> ```
> && rm -rf /var/cache/pacman/pkg/*
> 
> RUN pip3 install --upgrade pip
> ```

Why you have decided to put it so far from the actual use of `pip3`?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1256)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[utils/docker/images/Dockerfile.archlinux-latest, line 67 at r2](https://reviewable.io/reviews/pmem/rpma/1256#-MitgEDF3s_nA4B5Slnd:-Mitl9jx3T160MFsEiyO:b-sd9xcu) ([raw file](https://github.com/pmem/rpma/blob/d60af373b52e48e5b8945bf025c2f8861310b358/utils/docker/images/Dockerfile.archlinux-latest#L67)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Why you have decided to put it so far from the actual use of `pip3`?
</blockquote></details>

Because `upgrade` has to be run by root and `install` by a user.

**Review by janekmi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1256#-:-Mitm6Q2BqfEW3Hh9QYP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1256)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
