### PR TITLE
tools: create html compare files

### PR DESCRIPTION
**Pull request by osalyk**
Ref: #1495

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1503)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1503)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1503)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @ldorau and @osalyk)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1503#-Mtn-tCdEPPDlKPMFgjM):*
Please add:

Ref: #1495



_Code quote:_
```
- 5ef09a8: tools: create html compare files
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1503)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1503#-Mtn-tCdEPPDlKPMFgjM):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please add:

Ref: #1495
</blockquote></details>

Done.

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1503)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @haichangsi and @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1503)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @haichangsi and @ldorau)

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1503)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)

___
*[tools/perf/lib/figure/image.py, line 139 at r1](https://reviewable.io/reviews/pmem/rpma/1503#-MtoJgWpCAsE981PCpkF:-MtoJgWpCAsE981PCpkG:b-xon7uq) ([raw file](https://github.com/pmem/rpma/blob/5ef09a845d193e7910f54a99e1b9dccd671559ec/tools/perf/lib/figure/image.py#L139)):*
> ```Python
>     plt.close(fig)
> 
> def create_html(results: list, file_name: str, img_path: str) -> None:
> ```

why don't we put this in compare.py?



_Code quote:_
```Python
def create_html
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1503)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72, @haichangsi, and @ldorau)

___
*[tools/perf/lib/figure/image.py, line 139 at r1](https://reviewable.io/reviews/pmem/rpma/1503#-MtoJgWpCAsE981PCpkF:-Mtqhr4f2DyzA9Xu8i79:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5ef09a845d193e7910f54a99e1b9dccd671559ec/tools/perf/lib/figure/image.py#L139)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

why don't we put this in compare.py?
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1503)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72, @haichangsi, and @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1503)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[tools/perf/lib/compare.py, line 229 at r3](https://reviewable.io/reviews/pmem/rpma/1503#-Mtr40gnAUZIQgbjw6DT:-Mtr40gnAUZIQgbjw6DU:b-5yf0dh) ([raw file](https://github.com/pmem/rpma/blob/0901b92bc5f308c85702078891a0f2cb2b42c006/tools/perf/lib/compare.py#L229)):*
> ```Python
> 
>         Generate a HTML file compiling all the provided results.
>         """
> ```

IMHO "Generate a HTML file compiling all the provided results." is enough and "create html file" is redundant.



_Code quote:_
```Python
        """create html file

        Generate a HTML file compiling all the provided results.
        """
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1503)* status: 2 of 6 files reviewed, 2 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[tools/perf/lib/compare.py, line 229 at r3](https://reviewable.io/reviews/pmem/rpma/1503#-Mtr40gnAUZIQgbjw6DT:-Mtsjwq92ZwmiYNtX0YC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0901b92bc5f308c85702078891a0f2cb2b42c006/tools/perf/lib/compare.py#L229)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

IMHO "Generate a HTML file compiling all the provided results." is enough and "create html file" is redundant.
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1503)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @grom72, @haichangsi, and @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 4 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1503)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[tools/perf/templates/layout_cmp.html, line 28 at r5](https://reviewable.io/reviews/pmem/rpma/1503#-MuKQf0-D0lFPn5vH-RO:-MuKQf0-D0lFPn5vH-RP:b-18pxy5) ([raw file](https://github.com/pmem/rpma/blob/f25ce181cf4b2e073b3611757d68d231cec6839d/tools/perf/templates/layout_cmp.html#L28)):*
> ```HTML
> </head>
> <body>
>     {{table}}
> ```

Could you add some free space/lines after the last table at the end of the output HTML file?



_Code quote:_
```HTML
    {{table}}
```
___
*[tools/perf/templates/layout_cmp.html, line 39 at r5](https://reviewable.io/reviews/pmem/rpma/1503#-MuKDX1Z1-7O0yFnyBEh:-MuKDX1_ABm25uicc_J1:bmc5a5i) ([raw file](https://github.com/pmem/rpma/blob/f25ce181cf4b2e073b3611757d68d231cec6839d/tools/perf/templates/layout_cmp.html#L39)):*
> ```HTML
>             // add styl="width: 100%"" to all img objects
>     var imgs = document.getElementsByTagName('image');
>             
> ```

redundant empty line with spaces



_Code quote:_
```HTML
        ·····
```

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1503)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @osalyk)

**Review by ldorau — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1503#-:-MuKRMCD8VCNz3THrZ8J:bdycpsm)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1503)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/templates/layout_cmp.html, line 28 at r5](https://reviewable.io/reviews/pmem/rpma/1503#-MuKQf0-D0lFPn5vH-RO:-MuKXiVo931o7OYsHipa:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f25ce181cf4b2e073b3611757d68d231cec6839d/tools/perf/templates/layout_cmp.html#L28)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Could you add some free space/lines after the last table at the end of the output HTML file?
</blockquote></details>

Done.
___
*[tools/perf/templates/layout_cmp.html, line 39 at r5](https://reviewable.io/reviews/pmem/rpma/1503#-MuKDX1Z1-7O0yFnyBEh:-MuKXrWL2DGOB6GX3a1i:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f25ce181cf4b2e073b3611757d68d231cec6839d/tools/perf/templates/layout_cmp.html#L39)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

redundant empty line with spaces
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1503)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1503#-:-MuKxt077Q7AnJ8-mger:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r3, 3 of 4 files at r4, 1 of 1 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1503#-:-MuLDuVc-_L82BZ-QW9q:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1503)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
