### PR TITLE
tools: rename Figure_0 to Figure_000

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/828)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/828)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/828#-MSaV3i48pwyJ-_SA6q2:-MSaV3i48pwyJ-_SA6q3:b-e6yiku) (no related file):*
Where is Figure_000?

---

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/828)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/828#-MSaV3i48pwyJ-_SA6q2:-MSb3EzZAU7m8VKBmfCA:b-72tsws) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Where is Figure_000?
</blockquote></details>

It has to be provided by the user using the `--high_level_setup_figure` option.

---

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/828#-:-MSb6uNfAAcKE0_Kem5i:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/828)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Pull request merged**
