### PR TITLE
rpma: unify SQ/WQE send_flags in one place for readability

### PR DESCRIPTION
**Pull request by changchengx**
Signed-off-by: Changcheng Liu <changcheng.liu@aliyun.com>

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/767)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/767)* status: all files reviewed, 1 unresolved discussion (waiting on @changchengx)

___
*[src/include/librpma.h, line 1959 at r1](https://reviewable.io/reviews/pmem/rpma/767#-MShgbvH-h35O12KHVuy:-MShgbvH-h35O12KHVuz:bu08t6o) ([raw file](https://github.com/pmem/rpma/blob/d346666a8fca1555386588b7f9d2acbabc2b5374/src/include/librpma.h#L1959)):*
> ```objc
> /* generate operation completion on success */
> #define RPMA_F_COMPLETION_ON_SUCCESS \
> 	(RPMA_F_COMPLETION_ALWAYS & ~RPMA_F_COMPLETION_ON_ERROR)
> ```

Sorry, this change won't be merged because:

- putting this flag on the public header makes it generally available for the end-user applications whereas
- RPMA_F_COMPLETION_ON_SUCCESS makes no sense on the API level because
- in this case, the librpma library would need to filter out the completion on an error which
- is not generally a good idea for the end-user to voluntarily ignore the transmission errors

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/767)* status: all files reviewed, 1 unresolved discussion (waiting on @changchengx)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/767)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[src/include/librpma.h, line 1959 at r1](https://reviewable.io/reviews/pmem/rpma/767#-MShgbvH-h35O12KHVuy:-MTKCKrkB1PFmXUmwTWj:b32v57) ([raw file](https://github.com/pmem/rpma/blob/d346666a8fca1555386588b7f9d2acbabc2b5374/src/include/librpma.h#L1959)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Sorry, this change won't be merged because:

- putting this flag on the public header makes it generally available for the end-user applications whereas
- RPMA_F_COMPLETION_ON_SUCCESS makes no sense on the API level because
- in this case, the librpma library would need to filter out the completion on an error which
- is not generally a good idea for the end-user to voluntarily ignore the transmission errors
</blockquote></details>

+1

**Comment by janekmi** [comment]
@changchengx please let me know if you will have any second thoughts on this topic. Closing for now.

**Pull request closed without merging**
