### PR TITLE
doc: Update BENCHMARKING.md

### PR DESCRIPTION
**Pull request by yangx-jy**
1) Rename rpma_fio_read.sh to rpma_fio_bench.sh
2) Rename REMOTE_JOB_MEM to REMOTE_JOB_MEM_PATH
3) Add two new options of rpma_fio_bench.sh

Signed-off-by: Xiao Yang <yangx.jy@cn.fujitsu.com>

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/696)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/696)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/696#-MPhQz9z7fwmRCWxsT1I:-MPhQz9z7fwmRCWxsT1J:b-o8kbmo) (no related file):*
Thank you for noticing and fixing. 

---
___
*[tools/BENCHMARKING.md, line 64 at r1](https://reviewable.io/reviews/pmem/rpma/696#-MPhRHWD2qzahYa_sQcu:-MPhRHWE9isFevQBu7db:ba4t1sv) ([raw file](https://github.com/pmem/rpma/blob/cdd85396de69f4f117ed5948bbc8ac89d19c5926/tools/BENCHMARKING.md#L64)):*
> ```Markdown
> $ export REMOTE_JOB_MEM_PATH=mmap:/path/to/mem
> 
> $ ./rpma_fio_bench.sh <all|apm|gpspm> read lat <SERVER_IP>
> ```

The librpma_gpspm_server fio engine does not yet support read. At this point, I would recommend using `apm` here.
Please adjust it everywhere.

**Comment by yangx-jy** [comment]
___
*[tools/BENCHMARKING.md, line 64 at r1](https://reviewable.io/reviews/pmem/rpma/696#-MPhRHWD2qzahYa_sQcu:-MPhZ8eI4E9ZVBLES2Lm:b-ln7193) ([raw file](https://github.com/pmem/rpma/blob/cdd85396de69f4f117ed5948bbc8ac89d19c5926/tools/BENCHMARKING.md#L64)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The librpma_gpspm_server fio engine does not yet support read. At this point, I would recommend using `apm` here.
Please adjust it everywhere.
</blockquote></details>

Hi @janekmi 

Thanks for your quick reply.

I have used apm instead as you suggested.

Best Regards,
Xiao Yang

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/696)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @yangx-jy)

___
*[tools/BENCHMARKING.md, line 62 at r2](https://reviewable.io/reviews/pmem/rpma/696#-MPhaZ261IaeR2n6X4-f:-MPhaZ27AnVxmmJEBSjo:bub3f86) ([raw file](https://github.com/pmem/rpma/blob/cf8bd128a30c86ae333c6a078b3537ec05f11f8a/tools/BENCHMARKING.md#L62)):*
> ```
> REMOTE_JOB_MEM_PATH=mmap:/path/to/mem
> ```

and without `mmap:` from now on (only a path):

```
$ export REMOTE_JOB_MEM_PATH=/path/to/mem
```

Thanks for fixing this!

**Comment by yangx-jy** [comment]
___
*[tools/BENCHMARKING.md, line 62 at r2](https://reviewable.io/reviews/pmem/rpma/696#-MPhaZ261IaeR2n6X4-f:-MPhcIll2duuiyeS4Ylp:b-38xzh0) ([raw file](https://github.com/pmem/rpma/blob/cf8bd128a30c86ae333c6a078b3537ec05f11f8a/tools/BENCHMARKING.md#L62)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> REMOTE_JOB_MEM_PATH=mmap:/path/to/mem
> ```

and without `mmap:` from now on (only a path):

```
$ export REMOTE_JOB_MEM_PATH=/path/to/mem
```

Thanks for fixing this!
</blockquote></details>

Hi @ldorau 

Sorry for missing the point.

I have removed it now.

Best Regards,
Xiao Yang

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/696)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/696#-:-MPhcnEcCwobHXBobnxi:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/696#-:-MPhd4J73pOcomQq72lL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Pull request merged**
