### PR TITLE
tools: add footer with ref

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1236)

### CODE REVIEW

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1236#-:-MiQzcGNEzM6TfcwUSDc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
rebased

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1236#-:-MiQzxBWE9kJ97cWEGY5:b-hm0ll1)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1236#-:-MiR-lGe7NoFHJ1ximnl:bnfp4nl)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @janekmi and @osalyk)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1236#-:-MiRYHSe80iEvP2dRqxy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
