### PR TITLE
tools: add DEBUG_SKIP_REMOTE_CMDS config.json variable

### PR DESCRIPTION
**Pull request by ldorau**
Add the `SKIP_REMOTE_CMDS` config.json variable to skip running
all remote commands including copying files to the remote node.

Fixes: #1488

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1518)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1518)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1518#-MuLFkYk2BR954csTGCK:-MuLFkYk2BR954csTGCL:b-fxnbjx) (no related file):*
Shall we mark all development/test related flags with the same prefix i.e. ```DEV_```?
Just to indicate that these flags shall not be used during final benchmarking process?

---
___
*[tools/perf/lib/benchmark/runner/fio.py, line 214 at r1](https://reviewable.io/reviews/pmem/rpma/1518#-MuLElHtCB3h7Dos-ZU6:-MuLElHtCB3h7Dos-ZU7:bfbg17l) ([raw file](https://github.com/pmem/rpma/blob/344dfd366bcce297b58688b9d59aeda562f23699/tools/perf/lib/benchmark/runner/fio.py#L214)):*
> ```Python
>             with open(settings['logfile_server'], 'a', encoding='utf-8') as log:
>                 log.write("[server]$ {}".format(' '.join(args)))
>         if not self.__skip_running_tools and not self.__skip_remote_cmds:
> ```

not (self.__skip_running_tools or self.__skip_remote_cmds):



_Code quote:_
```Python
not self.__skip_running_tools and not self.__skip_remote_cmds:
```
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 122 at r1](https://reviewable.io/reviews/pmem/rpma/1518#-MuLExAHCvq2YaKzOobJ:-MuLExAHCvq2YaKzOobK:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/344dfd366bcce297b58688b9d59aeda562f23699/tools/perf/lib/benchmark/runner/ib_read.py#L122)):*
> ```Python
>             with open(settings['logfile_server'], 'a', encoding='utf-8') as log:
>                 log.write("[server]$ {}".format(' '.join(args)))
>         if not self.__skip_running_tools and not self.__skip_remote_cmds:
> ```

.



_Code quote:_
```Python
not self.__skip_running_tools and not self.__skip_remote_cmds
```

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1518)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1518)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1518#-MuLFkYk2BR954csTGCK:-MuPz5W4-yxjcaEvCf6_:b5plwfg) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Shall we mark all development/test related flags with the same prefix i.e. ```DEV_```?
Just to indicate that these flags shall not be used during final benchmarking process?

</blockquote></details>

or `DEBUG_`

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1518)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1518#-MuLFkYk2BR954csTGCK:-MuPzB3i98r3JJHSRloC:b3kre) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

or `DEBUG_`
</blockquote></details>

?

---

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1518)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1518#-MuLFkYk2BR954csTGCK:-MuQJIuVD1W9OhKt368O:brk132p) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

?
</blockquote></details>

DEBUG_

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1518)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @grom72 and @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1518#-MuLFkYk2BR954csTGCK:-MuQN3v28eSUSbN_ZTXF:bb6un1j) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

DEBUG_
</blockquote></details>

Done

---
___
*[tools/perf/lib/benchmark/runner/fio.py, line 214 at r1](https://reviewable.io/reviews/pmem/rpma/1518#-MuLElHtCB3h7Dos-ZU6:-MuQ1KST6zzQXWepwplv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/344dfd366bcce297b58688b9d59aeda562f23699/tools/perf/lib/benchmark/runner/fio.py#L214)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

not (self.__skip_running_tools or self.__skip_remote_cmds):
</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 122 at r1](https://reviewable.io/reviews/pmem/rpma/1518#-MuLExAHCvq2YaKzOobJ:-MuQ1JcU09cBBKnXZl-3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/344dfd366bcce297b58688b9d59aeda562f23699/tools/perf/lib/benchmark/runner/ib_read.py#L122)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by grom72 — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1518)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1518#-:-MuQPw5U3RzJr_WoXXcs:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1518)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
