### PR TITLE
examples:08-messages-ping-pong: post recv-wr to the target connection…

### PR DESCRIPTION
**Pull request by changchengx**
align with usage in while-loop and client's usage for easy
understanding.

Signed-off-by: Changcheng Liu <changcheng.liu@aliyun.com>

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/350)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/350)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @changchengx)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/350#-MGNEWGT7z5ZE_ygGE8L:-MGNEWGUATeKCANhNVde:b-er7dte) (no related file):*
**This PR introduces a race.**
On the server-side, the `_recv()` is done before `_connect()` on purpose.

# Your proposition (race)
The client, just after establishing a connection, sends a message to the server.
If the server will do a `_recv()` after the `_connect()` it may be not in place on time.

# The current implementation
Whereas in the current implementation the `_recv()` is in place before the `_connect()`.  (No race)

---

**Comment by changchengx** [comment]
> # Your proposition (race)
> The client, just after establishing a connection, sends a message to the server.
> If the server will do a `_recv()` after the `_connect()` it may be not in place on time.
> 
Before server ```/* wait for the connection to be established */```, could the client post Send-WR to Send-Queue?

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/350)* status: all files reviewed, 1 unresolved discussion (waiting on @changchengx)

**Comment by changchengx** [comment]
@janekmi 
I understand your concern.
With using this PR, I add the below change in my local repository:
```c
diff --git a/examples/08-messages-ping-pong/server.c b/examples/08-messages-ping-pong/server.c
index e9b251b..fdc4868 100644
--- a/examples/08-messages-ping-pong/server.c
+++ b/examples/08-messages-ping-pong/server.c
@@ -85,6 +85,8 @@ main(int argc, char *argv[])
        if ((ret = rpma_conn_req_connect(&req, NULL, &conn)))
                goto err_mr_dereg;
 
+
+    sleep(50);
        /*
         * Put an initial receive to be prepared for the first message of
         * the client's ping-pong.
```
server & client still works well.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/350)* status: all files reviewed, 1 unresolved discussion (waiting on @changchengx)

**Comment by changchengx** [comment]
@ldorau 
I always get below notification. I don't what's the discussion and how to solve it:
```
Reviewed 1 of 1 files at r2.
Reviewable status: all files reviewed, 1 unresolved discussion (waiting on @changchengx)
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/350)* status: all files reviewed, 1 unresolved discussion (waiting on @changchengx)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/350#-MGNEWGT7z5ZE_ygGE8L:-MGb1XpB7LHlBmyvDQVY:b-fx7q4h) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

**This PR introduces a race.**
On the server-side, the `_recv()` is done before `_connect()` on purpose.

# Your proposition (race)
The client, just after establishing a connection, sends a message to the server.
If the server will do a `_recv()` after the `_connect()` it may be not in place on time.

# The current implementation
Whereas in the current implementation the `_recv()` is in place before the `_connect()`.  (No race)
</blockquote></details>

@changchengx Try to mark the above discussion as Satisfied - however this is stiil unresolved by @janekmi ...

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/350)* status: all files reviewed, 1 unresolved discussion (waiting on @changchengx)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/350#-MGNEWGT7z5ZE_ygGE8L:-MGb1vBo3Q0nBYW2cTId:b-3w4q37) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@changchengx Try to mark the above discussion as Satisfied - however this is stiil unresolved by @janekmi ...
</blockquote></details>

I meant this discussion, not the above one ;-)

---

**Review by janekmi — COMMENTED** [review]
> Before server /* wait for the connection to be established */, could the client post Send-WR to Send-Queue?

The [rdma_cm(7)](https://linux.die.net/man/7/rdma_cm) manual page states that both sides of the connection should perform data transfers after `RDMA_CM_EVENT_ESTABLISHED`. But it not defines any order at which these events will be generated between the server and the client.

So, having a global time source, two possible situations seems equally plausible:

|Time|Server|Client|
|---|---|---|
|1||ESABLISHED|
|2||Send-WR|
|3|ESTABLISHED||

OR

|Time|Server|Client|
|---|---|---|
|1||ESABLISHED|
|2|ESTABLISHED||
|3||Send-WR|

This is why we recommend posting a Recv-WR **before** accepting the connection.

Why are you asking? Maybe I can help you another way?

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/350#-:-MGjokh51s0ENnsIS7rZ:b-awxgg0)* status: all files reviewed, 1 unresolved discussion (waiting on @changchengx)

**Comment by changchengx** [comment]
@janekmi 
I‘ll send email to you later about why I want to do it in that way.
Since the function is OK with the current code, I'll close this PR.

**Pull request closed without merging**
