### PR TITLE
doc: fix link to BENCHMARKING.md after moving it to perf

### PR DESCRIPTION
**Pull request by grom72**
- [x] #863

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/864)

### CODE REVIEW

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/864#-:-MT-p24M5fzgj94MGlFd:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/864)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[documentation/perf-tuning.md, line 174 at r2](https://reviewable.io/reviews/pmem/rpma/864#-MT9kyNw8boJ6GQ4mm8e:-MT9kyNw8boJ6GQ4mm8f:b-thswqp) ([raw file](https://github.com/pmem/rpma/blob/69bed0108e287f914b7961195af19458ce0e543d/documentation/perf-tuning.md#L174)):*
> ```Markdown
> [https://github.com/pmem/rpma/master/tools/perf/BENCHMARKING.md][perf-bench]
> 
> [perf-bench]: [https://github.com/pmem/rpma/blob/master/tools/perf/BENCHMARKING.md]
> ```

Not needed [   ]

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/864)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi and @osalyk)

___
*[documentation/perf-tuning.md, line 174 at r2](https://reviewable.io/reviews/pmem/rpma/864#-MT9kyNw8boJ6GQ4mm8e:-MTA-2Wq-KNugHvN4QFB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/69bed0108e287f914b7961195af19458ce0e543d/documentation/perf-tuning.md#L174)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Not needed [   ]
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/864#-:-MTA9UEX4uoAK6AJM3j4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/864)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
