### PR TITLE
rpma: make usage of rpma_cq_wait() and rpma_cq_get_wc() more precise

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1541)

### CODE REVIEW

**Review by osalyk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1541)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1541#-MuzkhL79kclpbA9ty7X:-MuzkhL79kclpbA9ty7Y:b-n6khor) (no related file):*
Please rebase

---

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1541#-:-MuzljqzC0RSH7K1eAeZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1541#-:-Mv2hgJd38y0ZjsqHzNh:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — CHANGES_REQUESTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1541#-:-Mv4-jLt6nXTwM_CHcl6:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/include/librpma.h, line 2728 at r3](https://reviewable.io/reviews/pmem/rpma/1541#-Mv40GtAEDa_qR5mIf0C:-Mv40GtAEDa_qR5mIf0D:b-l5x72n) ([raw file](https://github.com/pmem/rpma/blob/1e9174bc479a5397637168b4c147f1a9520ef224/src/include/librpma.h#L2728)):*
> ```objc
>  * It should be called before rpma_cq_get_wc(3). After having rpma_cq_wait()
>  * called, all completions should be got using rpma_cq_get_wc(3) before
>  * the next rpma_cq_wait() call.
> ```

rpma_cq_wait() waits for an incoming completion. If it succeeds the all completion should be got using rpma_cq_get_wc(3) before the next rpma_cq_wait() call.

What do you think?



_Code quote:_
```objc
 * rpma_cq_wait() waits for an incoming completion. If it succeeds
 * the completion can be collected using rpma_cq_get_wc(3).
 * It should be called before rpma_cq_get_wc(3). After having rpma_cq_wait()
 * called, all completions should be got using rpma_cq_get_wc(3) before
 * the next rpma_cq_wait() call.
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1541)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[src/include/librpma.h, line 2728 at r3](https://reviewable.io/reviews/pmem/rpma/1541#-Mv40GtAEDa_qR5mIf0C:-Mv42_ms1GkPSpT8LD9n:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1e9174bc479a5397637168b4c147f1a9520ef224/src/include/librpma.h#L2728)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

rpma_cq_wait() waits for an incoming completion. If it succeeds the all completion should be got using rpma_cq_get_wc(3) before the next rpma_cq_wait() call.

What do you think?
</blockquote></details>

Done.

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1541#-:-Mv42jHp6szgshDaZwDQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1541#-:-MvIs8jN7xkSv40fm1lo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
