### PR TITLE
tools: add _DEBUG prefix to the rest of debug config.json variables

### PR DESCRIPTION
**Pull request by ldorau**
Replace:
- `SHORT_RUNTIME` with `DEBUG_SHORT_RUNTIME`,
- `TRACER` with `DEBUG_TRACER` and
- `REMOTE_TRACER` with `DEBUG_REMOTE_TRACER`.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1520)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
See: #1518 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1520#-:-MuQXvqZCe7bhfwH3Tg0:bipynqe)* status: 0 of 3 files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1520)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1520#-:-MuQbgXI3JS7M9R2cgnP:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @grom72)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1520#-:-MuQqVco8tPzsw4yojS-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
