### PR TITLE
rpma: make peer_cfg thread-safe

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1917)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1917)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

___
*[`src/peer_cfg.c` line 38 at r1](https://reviewable.io/reviews/pmem/rpma/1917#-N6NIAzB0KCDiwOYMYmp:-N6NIAzB0KCDiwOYMYmq:b-vj8coq) ([raw file](https://github.com/pmem/rpma/blob/3a812b92b2c9d48dae9c2af3bd15a543b6eaf13f/src/peer_cfg.c#L38)):*
> ```C
> 
> #ifdef ATOMIC_STORE_SUPPORTED
> static struct rpma_peer_cfg Peer_cfg_default = {
> ```

Do we need this structure?
___
*[`src/peer_cfg.c` line 63 at r1](https://reviewable.io/reviews/pmem/rpma/1917#-N6NHtMXCMPwF3LD7Pz9:-N6NHtMXCMPwF3LD7PzA:undefined) ([raw file](https://github.com/pmem/rpma/blob/3a812b92b2c9d48dae9c2af3bd15a543b6eaf13f/src/peer_cfg.c#L63)):*
> ```C
> 	/* set default values */
> 
> #ifdef ATOMIC_STORE_SUPPORTED
> ```





_Suggestion:_
```C
#ifdef ATOMIC_STORE_SUPPORTED
	bool direct_write_to_pmem = RPMA_DEFAULT_DIRECT_WRITE_TO_PMEM
	atomic_init(&cfg->direct_write_to_pmem,
		atomic_load_explicit(&direct_write_to_pmem, __ATOMIC_SEQ_CST));
#else
	cfg->direct_write_to_pmem = RPMA_DEFAULT_DIRECT_WRITE_TO_PMEM;
#endif /* ATOMIC_STORE_SUPPORTED */
```
___
*[`src/peer_cfg.c` line 200 at r1](https://reviewable.io/reviews/pmem/rpma/1917#-N6NIYeK-ZZx2st8fJ1a:-N6NIYeK-ZZx2st8fJ1b:b-iquee4) ([raw file](https://github.com/pmem/rpma/blob/3a812b92b2c9d48dae9c2af3bd15a543b6eaf13f/src/peer_cfg.c#L200)):*
> ```C
> 		return RPMA_E_NOMEM;
> 
> 	rpma_peer_cfg_set_direct_write_to_pmem(cfg, *(uint8_t *)desc);
> ```

revert this as it is not needed here. we modify just allocated structure - no risk of interference with any other thread



_Code quote:_
```C
rpma_peer_cfg_set_direct_write_to_pmem(cfg, *(uint8_t *)desc);
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1917)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[`src/peer_cfg.c` line 38 at r1](https://reviewable.io/reviews/pmem/rpma/1917#-N6NIAzB0KCDiwOYMYmp:-N6NP4fD3MF3NBdbt3Pj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3a812b92b2c9d48dae9c2af3bd15a543b6eaf13f/src/peer_cfg.c#L38)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Do we need this structure?
</blockquote></details>

Done.
___
*[`src/peer_cfg.c` line 63 at r1](https://reviewable.io/reviews/pmem/rpma/1917#-N6NHtMXCMPwF3LD7Pz9:-N6NP3Hy2weLGrP4MqWG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3a812b92b2c9d48dae9c2af3bd15a543b6eaf13f/src/peer_cfg.c#L63)):*
> ```C
> 	/* set default values */
> 
> #ifdef ATOMIC_STORE_SUPPORTED
> ```

Done.
___
*[`src/peer_cfg.c` line 200 at r1](https://reviewable.io/reviews/pmem/rpma/1917#-N6NIYeK-ZZx2st8fJ1a:-N6NPr-q-ysRKuMR0hbX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3a812b92b2c9d48dae9c2af3bd15a543b6eaf13f/src/peer_cfg.c#L200)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

revert this as it is not needed here. we modify just allocated structure - no risk of interference with any other thread
</blockquote></details>

Done.

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1917)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @grom72 and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1917#-N6NVQqJ5u7u15VS5IEw:-N6NtDA06pOuXRHI4Qqg:b-896fix) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Please check if some lines can be combined into one longer
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1917#-N6NUvs838GnkPNED_-c:-N6NuPHY8fDFrcPKrRC9:b-896fix) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Changelog.md is missing
</blockquote></details>

Done.

___
___
*[`src/peer_cfg.c` line 91 at r2](https://reviewable.io/reviews/pmem/rpma/1917#-N6NVH2Z3J9kXvH6pbKj:-N6NtB_r5ZXLAGXPLpw7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ddc441c41c53c273a8c9f0fae0ed674857d3d995/src/peer_cfg.c#L91)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

is it possible to have this in one line?
</blockquote></details>

Done.

**Review by grom72 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1917)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by osalyk — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1917)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by osalyk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1917)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1917#-N6SBp3l07mhaS7edT67:-N6SBp3l07mhaS7edT68:b-ggul8x) (no related file):*
Please verify with peer_cfg... test

___

**Review by Patryk717 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1917#-:-N6Snlas7DuEtEIemgmk:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1917)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72 and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1917#-N6SBp3l07mhaS7edT67:-N6Sw1Wg97sabj2gAisi:b-896fix) (no related file):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Please verify with peer_cfg... test
</blockquote></details>

Done.

___

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1917)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi and @osalyk)

___
*[`src/peer_cfg.c` line 28 at r4](https://reviewable.io/reviews/pmem/rpma/1917#-N6TMJKZBg460AvkeRBp:-N6TMJKZBg460AvkeRBq:undefined) ([raw file](https://github.com/pmem/rpma/blob/7248fa3d77b1758acdfb750845c032dc6cccbe0b/src/peer_cfg.c#L28)):*
> ```C
> #define SUPPORTED2STR(var) ((var) ? "supported" : "unsupported")
> 
> #define RPMA_DEFAULT_DIRECT_WRITE_TO_PMEM false
> ```





_Suggestion:_
```C
static bool RPMA_DEFAULT_DIRECT_WRITE_TO_PMEM = false;
```
___
*[`src/peer_cfg.c` line 58 at r4](https://reviewable.io/reviews/pmem/rpma/1917#-N6TMWjy-TKDWIOZfFzL:-N6TMWjy-TKDWIOZfFzM:undefined) ([raw file](https://github.com/pmem/rpma/blob/7248fa3d77b1758acdfb750845c032dc6cccbe0b/src/peer_cfg.c#L58)):*
> ```C
> 
> #ifdef ATOMIC_STORE_SUPPORTED
> 	bool direct_write_to_pmem = RPMA_DEFAULT_DIRECT_WRITE_TO_PMEM;
> ```





_Suggestion:_
```C
	atomic_init(&cfg->direct_write_to_pmem,
		atomic_load_explicit(&RPMA_DEFAULT_DIRECT_WRITE_TO_PMEM, __ATOMIC_SEQ_CST));
```

**Review by osalyk — COMMENTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1917)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1917)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[`src/peer_cfg.c` line 28 at r4](https://reviewable.io/reviews/pmem/rpma/1917#-N6TMJKZBg460AvkeRBp:-N6gNX6s9zuMAJzE7Isa:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7248fa3d77b1758acdfb750845c032dc6cccbe0b/src/peer_cfg.c#L28)):*
> ```C
> #define SUPPORTED2STR(var) ((var) ? "supported" : "unsupported")
> 
> #define RPMA_DEFAULT_DIRECT_WRITE_TO_PMEM false
> ```

Done.
___
*[`src/peer_cfg.c` line 58 at r4](https://reviewable.io/reviews/pmem/rpma/1917#-N6TMWjy-TKDWIOZfFzL:-N6gNhjp4KU9HJfeGNLP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7248fa3d77b1758acdfb750845c032dc6cccbe0b/src/peer_cfg.c#L58)):*
> ```C
> 
> #ifdef ATOMIC_STORE_SUPPORTED
> 	bool direct_write_to_pmem = RPMA_DEFAULT_DIRECT_WRITE_TO_PMEM;
> ```

Done.

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1917#-:-N6gb2E25MLNmuECKD6m:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1917)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1917#-:-N6h3d1r7F07MwELokmZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by osalyk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1917)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
