### PR TITLE
add const to all possible API calls

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/439)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> ```
> void *op_context
> ```
to
```
const void *op_context
```
 *everywhere* where possible

> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/439#-:-MI01ioeAiC7Gxqdbh6R:b-lpnkkn)* status: all files reviewed, 8 unresolved discussions (waiting on @osalyk)

___
*[src/conn.c, line 361 at r1](https://reviewable.io/reviews/pmem/rpma/439#-MI01EnF4qGI_DaqTb-t:-MI01EnF4qGI_DaqTb-u:b-awmh7k) ([raw file](https://github.com/pmem/rpma/blob/992ebc1acfc4286535ec3ad084b02f2460ed6a88/src/conn.c#L361)):*
> ```
> void
> ```
const void
___
*[src/ep.c, line 164 at r1](https://reviewable.io/reviews/pmem/rpma/439#-MI02Hun4O84dqOIf7Bv:-MI02Huo0kKwveXtyhvU:b-i28kt6) ([raw file](https://github.com/pmem/rpma/blob/992ebc1acfc4286535ec3ad084b02f2460ed6a88/src/ep.c#L164)):*
> ```
> struct rpma_conn_cfg *cfg
> ```
const  struct rpma_conn_cfg *cfg
___
*[src/flush.h, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/439#-MI02VCW5EbziIVssnaj:-MI02VCW5EbziIVssnak:b-nn396o) ([raw file](https://github.com/pmem/rpma/blob/992ebc1acfc4286535ec3ad084b02f2460ed6a88/src/flush.h#L17)):*
> ```
> void *op_context
> ```
const void *op_context
___
*[src/include/librpma.h, line 205 at r1](https://reviewable.io/reviews/pmem/rpma/439#-MI031co5fS0ulEMrQAR:-MI031co5fS0ulEMrQAS:b-jvkv6r) ([raw file](https://github.com/pmem/rpma/blob/992ebc1acfc4286535ec3ad084b02f2460ed6a88/src/include/librpma.h#L205)):*
> ```
> rpma_peer_cfg_descriptor
> ```
void
___
*[src/include/librpma.h, line 816 at r1](https://reviewable.io/reviews/pmem/rpma/439#-MI03hQbD7tlYypkS8cv:-MI03hQbD7tlYypkS8cw:b-4md8xs) ([raw file](https://github.com/pmem/rpma/blob/992ebc1acfc4286535ec3ad084b02f2460ed6a88/src/include/librpma.h#L816)):*
> ```
> struct
> ```
const struct
___
*[src/include/librpma.h, line 832 at r1](https://reviewable.io/reviews/pmem/rpma/439#-MI03sqBEdJ8cXqCQrXy:-MI03sqCCtLKwhA9UUyZ:b-4md8xs) ([raw file](https://github.com/pmem/rpma/blob/992ebc1acfc4286535ec3ad084b02f2460ed6a88/src/include/librpma.h#L832)):*
> ```
> struct
> ```
const struct
___
*[src/include/librpma.h, line 998 at r1](https://reviewable.io/reviews/pmem/rpma/439#-MI04bUL8mwEtrG3aGHv:-MI04bUL8mwEtrG3aGHw:b-4md8xs) ([raw file](https://github.com/pmem/rpma/blob/992ebc1acfc4286535ec3ad084b02f2460ed6a88/src/include/librpma.h#L998)):*
> ```
> struct
> ```
const struct
___
*[src/include/librpma.h, line 1012 at r1](https://reviewable.io/reviews/pmem/rpma/439#-MI04mTR7EfahkTnLK5U:-MI04mTR7EfahkTnLK5V:b-4md8xs) ([raw file](https://github.com/pmem/rpma/blob/992ebc1acfc4286535ec3ad084b02f2460ed6a88/src/include/librpma.h#L1012)):*
> ```
> struct
> ```
const struct

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/439)* status: all files reviewed, 8 unresolved discussions (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
Please rebase

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/439#-:-MI0we4d4X0Bep5pzgTs:b-n6khor)* status: all files reviewed, 8 unresolved discussions (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/439#-:-MI38GeNCTOYyUn0-f2O:b-896fix)* status: 5 of 20 files reviewed, 8 unresolved discussions (waiting on @grom72)

___
*[src/conn.c, line 361 at r1](https://reviewable.io/reviews/pmem/rpma/439#-MI01EnF4qGI_DaqTb-t:-MI38I7Y69ZmFxLxa-IQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/992ebc1acfc4286535ec3ad084b02f2460ed6a88/src/conn.c#L361)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> void
> ```
const void
</blockquote></details>

Done.
___
*[src/ep.c, line 164 at r1](https://reviewable.io/reviews/pmem/rpma/439#-MI02Hun4O84dqOIf7Bv:-MI34TDu-0yJVaWOXWMm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/992ebc1acfc4286535ec3ad084b02f2460ed6a88/src/ep.c#L164)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> struct rpma_conn_cfg *cfg
> ```
const  struct rpma_conn_cfg *cfg
</blockquote></details>

Done.
___
*[src/flush.h, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/439#-MI02VCW5EbziIVssnaj:-MI38JAg78bwAIW-Wvha:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/992ebc1acfc4286535ec3ad084b02f2460ed6a88/src/flush.h#L17)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> void *op_context
> ```
const void *op_context
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 205 at r1](https://reviewable.io/reviews/pmem/rpma/439#-MI031co5fS0ulEMrQAR:-MI34hgVA8TUs6F4uhJR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/992ebc1acfc4286535ec3ad084b02f2460ed6a88/src/include/librpma.h#L205)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> rpma_peer_cfg_descriptor
> ```
void
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 816 at r1](https://reviewable.io/reviews/pmem/rpma/439#-MI03hQbD7tlYypkS8cv:-MI35xW-9Pspp4QiNbCJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/992ebc1acfc4286535ec3ad084b02f2460ed6a88/src/include/librpma.h#L816)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> struct
> ```
const struct
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 832 at r1](https://reviewable.io/reviews/pmem/rpma/439#-MI03sqBEdJ8cXqCQrXy:-MI36-2GApATH1lix7o4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/992ebc1acfc4286535ec3ad084b02f2460ed6a88/src/include/librpma.h#L832)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> struct
> ```
const struct
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 998 at r1](https://reviewable.io/reviews/pmem/rpma/439#-MI04bUL8mwEtrG3aGHv:-MI3680c75Et9zN9RMQC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/992ebc1acfc4286535ec3ad084b02f2460ed6a88/src/include/librpma.h#L998)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> struct
> ```
const struct
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1012 at r1](https://reviewable.io/reviews/pmem/rpma/439#-MI04mTR7EfahkTnLK5U:-MI36AOfAXNEoqFlf1xX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/992ebc1acfc4286535ec3ad084b02f2460ed6a88/src/include/librpma.h#L1012)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> struct
> ```
const struct
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 5 of 15 files at r1, 15 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/439)* status: all files reviewed, 8 unresolved discussions (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/439#-:-MI3XzZS33kqefGidoG7:bnfp4nl)* status: all files reviewed, 8 unresolved discussions (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 15 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/439#-:-MI3hkHMDVcRZwhrS1ch:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/439)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/439)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
