### PR TITLE
rpma: write the 'REMOTE MEMORY ACCESS' section of the librpma.7 manual

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/522)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/522)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/include/librpma.h, line 46 at r1](https://reviewable.io/reviews/pmem/rpma/522#-MIYyQyp1mUXdvoW8RYx:-MIYyQyp1mUXdvoW8RYy:b-1u1s26) ([raw file](https://github.com/pmem/rpma/blob/718ff71941f6d37c34e6b6396bb1a1b8de15fd9a/src/include/librpma.h#L46)):*
> ```
> ,
> ```
, atomic write implementation is based on the assumption (not explicitly mentioned by RDMA spec) that 8byte align write could not be split into two operations either on RDMA wires nor on PCIe bus.

**Review by janekmi — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/522)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/include/librpma.h, line 41 at r1](https://reviewable.io/reviews/pmem/rpma/522#-MIZ-W4U0icjmxG48jOr:-MIZ-W4U0icjmxG48jOs:b-lq9zge) ([raw file](https://github.com/pmem/rpma/blob/718ff71941f6d37c34e6b6396bb1a1b8de15fd9a/src/include/librpma.h#L41)):*
> ```objc
>  * dedicated for accessing a remote memory:
>  * - rpma_read() - initiates the read operation (transferring data from
>  * the remote memory to the local memory),
> ```

initiated transferring data from the remote memory to the local memory

- a little shorter and simpler
- read is already mentioned in the name of the function

If you agree please apply everywhere.
___
*[src/include/librpma.h, line 46 at r1](https://reviewable.io/reviews/pmem/rpma/522#-MIYyQyp1mUXdvoW8RYx:-MIZ-npR3EFSh3Uvrr4E:b-rrd8se) ([raw file](https://github.com/pmem/rpma/blob/718ff71941f6d37c34e6b6396bb1a1b8de15fd9a/src/include/librpma.h#L46)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> ,
> ```
, atomic write implementation is based on the assumption (not explicitly mentioned by RDMA spec) that 8byte align write could not be split into two operations either on RDMA wires nor on PCIe bus. 
</blockquote></details>

I think such details should find their way to the dedicated rpma_write_atomic manual describing all intricacies.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/522)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/include/librpma.h, line 46 at r1](https://reviewable.io/reviews/pmem/rpma/522#-MIYyQyp1mUXdvoW8RYx:-MIZ0aTA57ODZqSY0zXU:bfu0yrx) ([raw file](https://github.com/pmem/rpma/blob/718ff71941f6d37c34e6b6396bb1a1b8de15fd9a/src/include/librpma.h#L46)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think such details should find their way to the dedicated rpma_write_atomic manual describing all intricacies.
</blockquote></details>

I agree, it is not a place for details.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/522)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[src/include/librpma.h, line 41 at r1](https://reviewable.io/reviews/pmem/rpma/522#-MIZ-W4U0icjmxG48jOr:-MIZ0stT41bm5nruyw60:b8hdarx) ([raw file](https://github.com/pmem/rpma/blob/718ff71941f6d37c34e6b6396bb1a1b8de15fd9a/src/include/librpma.h#L41)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

initiated transferring data from the remote memory to the local memory

- a little shorter and simpler
- read is already mentioned in the name of the function

If you agree please apply everywhere.
</blockquote></details>

OK, I will apply it everywhere

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/522)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[src/include/librpma.h, line 46 at r1](https://reviewable.io/reviews/pmem/rpma/522#-MIYyQyp1mUXdvoW8RYx:-MIZ1DaM6gqEI3jvzP9z:b-wti19y) ([raw file](https://github.com/pmem/rpma/blob/718ff71941f6d37c34e6b6396bb1a1b8de15fd9a/src/include/librpma.h#L46)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I agree, it is not a place for details.
</blockquote></details>

this is the place to say that it is not true atomic operation

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/522)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[src/include/librpma.h, line 41 at r1](https://reviewable.io/reviews/pmem/rpma/522#-MIZ-W4U0icjmxG48jOr:-MIZ20o820-lRQv5gDYg:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/718ff71941f6d37c34e6b6396bb1a1b8de15fd9a/src/include/librpma.h#L41)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK, I will apply it everywhere
</blockquote></details>

Done
___
*[src/include/librpma.h, line 46 at r1](https://reviewable.io/reviews/pmem/rpma/522#-MIYyQyp1mUXdvoW8RYx:-MIZ2lWU7oY0qxEU32fu:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/718ff71941f6d37c34e6b6396bb1a1b8de15fd9a/src/include/librpma.h#L46)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

this is the place to say that it is not true atomic operation 
</blockquote></details>

Done

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/522#-:-MIZ4cMF5nhyA5eyWn5K:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/522#-:-MIZ5DDjDnVEFhzWG3e0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
