### PR TITLE
test: add rpma_mr_get_size multithreaded test

### PR DESCRIPTION
**Pull request by ewanglong**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1062)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1062)* status: all files reviewed, 10 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/mr/rpma_mr_get_size.c, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1062#-MaF5NPa48NQZys1epMO:-MaF5NPa48NQZys1epMP:be34x6f) ([raw file](https://github.com/pmem/rpma/blob/c265488f7e764d8d6dd4fa39a1edf4b5dbac00ba/tests/multithreaded/mr/rpma_mr_get_size.c#L39)):*
> ```C
> 
> 	if ((ret = rpma_utils_get_ibv_context(pr->addr,
> 			RPMA_UTIL_IBV_CONTEXT_LOCAL, &pr->dev))) {
> ```

No need to store it in the prestate.
___
*[tests/multithreaded/mr/rpma_mr_get_size.c, line 51 at r1](https://reviewable.io/reviews/pmem/rpma/1062#-MaF5SiiDWghUeWKGFjR:-MaF5SiiDWghUeWKGFjS:beinnnz) ([raw file](https://github.com/pmem/rpma/blob/c265488f7e764d8d6dd4fa39a1edf4b5dbac00ba/tests/multithreaded/mr/rpma_mr_get_size.c#L51)):*
> ```C
> 	pr->mr_ptr = mtt_malloc_aligned(KILOBYTE, tr);
> 	if (pr->mr_ptr == NULL)
> 		return;
> ```

The error handling is missing.
___
*[tests/multithreaded/mr/rpma_mr_get_size.c, line 56 at r1](https://reviewable.io/reviews/pmem/rpma/1062#-MaF5WkM17S3Hd0ojloE:-MaF5WkM17S3Hd0ojloF:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/c265488f7e764d8d6dd4fa39a1edf4b5dbac00ba/tests/multithreaded/mr/rpma_mr_get_size.c#L56)):*
> ```C
> 			RPMA_MR_USAGE_READ_SRC, &pr->mr))) {
> 		MTT_RPMA_ERR(tr, "rpma_mr_reg", ret);
> 		return;
> ```

.
___
*[tests/multithreaded/mr/rpma_mr_get_size.c, line 60 at r1](https://reviewable.io/reviews/pmem/rpma/1062#-MaF5Ylj-nW27_8rOC9H:-MaF5Ylj-nW27_8rOC9I:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/c265488f7e764d8d6dd4fa39a1edf4b5dbac00ba/tests/multithreaded/mr/rpma_mr_get_size.c#L60)):*
> ```C
> 
> 	if ((ret = rpma_mr_get_size(pr->mr, &pr->mr_size_exp)))
> 		MTT_RPMA_ERR(tr, "rpma_mr_get_size", ret);
> ```

.
___
*[tests/multithreaded/mr/rpma_mr_get_size.c, line 60 at r1](https://reviewable.io/reviews/pmem/rpma/1062#-MaF5ZLH7YYY0qfP-yk8:-MaF5ZLH7YYY0qfP-yk9:b497hcy) ([raw file](https://github.com/pmem/rpma/blob/c265488f7e764d8d6dd4fa39a1edf4b5dbac00ba/tests/multithreaded/mr/rpma_mr_get_size.c#L60)):*
> ```C
> 
> 	if ((ret = rpma_mr_get_size(pr->mr, &pr->mr_size_exp)))
> 		MTT_RPMA_ERR(tr, "rpma_mr_get_size", ret);
> ```

You should check it against `KILOBYTE`.
___
*[tests/multithreaded/mr/rpma_mr_get_size.c, line 87 at r1](https://reviewable.io/reviews/pmem/rpma/1062#-MaF5hLo46CR9vUSDjEb:-MaF5hLo46CR9vUSDjEc:b-itcua3) ([raw file](https://github.com/pmem/rpma/blob/c265488f7e764d8d6dd4fa39a1edf4b5dbac00ba/tests/multithreaded/mr/rpma_mr_get_size.c#L87)):*
> ```C
> {
> 	struct prestate *pr = (struct prestate *)prestate;
> 	struct state *st = (struct state *)state;
> ```

You do not need it.
___
*[tests/multithreaded/mr/rpma_mr_get_size.c, line 91 at r1](https://reviewable.io/reviews/pmem/rpma/1062#-MaF5ld3B-BgF8fTjGcC:-MaF5ld3B-BgF8fTjGcD:bwujzmf) ([raw file](https://github.com/pmem/rpma/blob/c265488f7e764d8d6dd4fa39a1edf4b5dbac00ba/tests/multithreaded/mr/rpma_mr_get_size.c#L91)):*
> ```C
> 	int ret = rpma_mr_get_size(pr->mr, &st->mr_size);
> 	if (ret)
> 		MTT_RPMA_ERR(result, "rpma_mr_get_size", ret);
> ```

No point in continuing. Return.
___
*[tests/multithreaded/mr/rpma_mr_get_size.c, line 94 at r1](https://reviewable.io/reviews/pmem/rpma/1062#-MaF5rZm09higx4tZtqR:-MaF5rZm09higx4tZtqS:bg3tpf0) ([raw file](https://github.com/pmem/rpma/blob/c265488f7e764d8d6dd4fa39a1edf4b5dbac00ba/tests/multithreaded/mr/rpma_mr_get_size.c#L94)):*
> ```C
> 
> 	if (st->mr_size != pr->mr_size_exp)
> 		MTT_ERR(result, "rpma_mr_get_size returned an unexpected value",
> ```

`"mr_size != pr->mr_size_exp"`
___
*[tests/multithreaded/mr/rpma_mr_get_size.c, line 112 at r1](https://reviewable.io/reviews/pmem/rpma/1062#-MaF5zQXAA9x_FMAwLkQ:-MaF5zQXAA9x_FMAwLkR:bt7yq9o) ([raw file](https://github.com/pmem/rpma/blob/c265488f7e764d8d6dd4fa39a1edf4b5dbac00ba/tests/multithreaded/mr/rpma_mr_get_size.c#L112)):*
> ```C
> 
> /*
>  * prestate_fini -- deregister the memory region and delete the peer object
> ```

..., free it and delete...
___
*[tests/multithreaded/mr/rpma_mr_get_size.c, line 120 at r1](https://reviewable.io/reviews/pmem/rpma/1062#-MaF63Ds6NxfSLpuxqLT:-MaF63Ds6NxfSLpuxqLU:b8j6eaa) ([raw file](https://github.com/pmem/rpma/blob/c265488f7e764d8d6dd4fa39a1edf4b5dbac00ba/tests/multithreaded/mr/rpma_mr_get_size.c#L120)):*
> ```C
> 	int ret;
> 
> 	if (pr->mr) {
> ```

It is not necessary.

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1062)* status: 1 of 2 files reviewed, 10 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/mr/rpma_mr_get_size.c, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1062#-MaF5NPa48NQZys1epMO:-MaRVZ1X84EjzGfh-9Wa:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c265488f7e764d8d6dd4fa39a1edf4b5dbac00ba/tests/multithreaded/mr/rpma_mr_get_size.c#L39)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

No need to store it in the prestate.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_size.c, line 51 at r1](https://reviewable.io/reviews/pmem/rpma/1062#-MaF5SiiDWghUeWKGFjR:-MaRVZWE7zYgiC-wP1Jt:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c265488f7e764d8d6dd4fa39a1edf4b5dbac00ba/tests/multithreaded/mr/rpma_mr_get_size.c#L51)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The error handling is missing.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_size.c, line 56 at r1](https://reviewable.io/reviews/pmem/rpma/1062#-MaF5WkM17S3Hd0ojloE:-MaRVZxV1OMWIhTqBEzK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c265488f7e764d8d6dd4fa39a1edf4b5dbac00ba/tests/multithreaded/mr/rpma_mr_get_size.c#L56)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_size.c, line 60 at r1](https://reviewable.io/reviews/pmem/rpma/1062#-MaF5Ylj-nW27_8rOC9H:-MaRV_PGCrWdhc6Sb1g4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c265488f7e764d8d6dd4fa39a1edf4b5dbac00ba/tests/multithreaded/mr/rpma_mr_get_size.c#L60)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_size.c, line 60 at r1](https://reviewable.io/reviews/pmem/rpma/1062#-MaF5ZLH7YYY0qfP-yk8:-MaRV_p0Bbg6BW2z_5BG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c265488f7e764d8d6dd4fa39a1edf4b5dbac00ba/tests/multithreaded/mr/rpma_mr_get_size.c#L60)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You should check it against `KILOBYTE`.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_size.c, line 87 at r1](https://reviewable.io/reviews/pmem/rpma/1062#-MaF5hLo46CR9vUSDjEb:-MaRVaRJ8h_p63qmeDPb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c265488f7e764d8d6dd4fa39a1edf4b5dbac00ba/tests/multithreaded/mr/rpma_mr_get_size.c#L87)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You do not need it.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_size.c, line 91 at r1](https://reviewable.io/reviews/pmem/rpma/1062#-MaF5ld3B-BgF8fTjGcC:-MaRVaw63UeyEkqR8udx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c265488f7e764d8d6dd4fa39a1edf4b5dbac00ba/tests/multithreaded/mr/rpma_mr_get_size.c#L91)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

No point in continuing. Return.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_size.c, line 94 at r1](https://reviewable.io/reviews/pmem/rpma/1062#-MaF5rZm09higx4tZtqR:-MaRVbQq6Z5X0YNEEfyh:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c265488f7e764d8d6dd4fa39a1edf4b5dbac00ba/tests/multithreaded/mr/rpma_mr_get_size.c#L94)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`"mr_size != pr->mr_size_exp"`
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_size.c, line 112 at r1](https://reviewable.io/reviews/pmem/rpma/1062#-MaF5zQXAA9x_FMAwLkQ:-MaRVfGv2mPeQ_6alQbC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c265488f7e764d8d6dd4fa39a1edf4b5dbac00ba/tests/multithreaded/mr/rpma_mr_get_size.c#L112)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

..., free it and delete...
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_size.c, line 120 at r1](https://reviewable.io/reviews/pmem/rpma/1062#-MaF63Ds6NxfSLpuxqLT:-MaRVe4z-w0zGgiGA9D8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c265488f7e764d8d6dd4fa39a1edf4b5dbac00ba/tests/multithreaded/mr/rpma_mr_get_size.c#L120)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is not necessary.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1062#-:-Mam7gcX5-Dv31aQsmC7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Review by ewanglong — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1062#-:-Mb0-Bq85pfTOZU2uV-I:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1062)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1062#-Mb0nn0s6b-Z3__sQBfM:-Mb0nn0s6b-Z3__sQBfN:b-8cioiv) (no related file):*
Please rebase.

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1062)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1062#-Mb0nn0s6b-Z3__sQBfM:-MbB2Ii3200ldccd1692:b-6d23dx) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please rebase.
</blockquote></details>

@ewanglong please rebase - there is a conflict

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1062)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1062)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1062#-Mb0nn0s6b-Z3__sQBfM:-MbBLRRO5lRUHOgRb-Za:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@ewanglong please rebase - there is a conflict
</blockquote></details>

Done.

---

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1062#-:-MbBMg-V-cN-nfiJXjPv:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Pull request merged**
