### PR TITLE
common: add CPACK_GENERATOR to DEVELOPMENT.md

### PR DESCRIPTION
**Pull request by yangx-jy**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/2129)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2129)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[`DEVELOPMENT.md` line 35 at r1](https://reviewable.io/reviews/pmem/rpma/2129#-NU_ST-cArwWefVhS2NU:-NU_ST-cArwWefVhS2NV:bnrf6vr) ([raw file](https://github.com/pmem/rpma/blob/94c916f226183a0d17f4b92c60f81643d1e63949/DEVELOPMENT.md#L35)):*
> ```Markdown
> | CMAKE_BUILD_TYPE | Choose the type of build | None/Release/Debug/RelWithDebInfo | Release |
> | CMAKE_INSTALL_PREFIX | An install path prefix, prepended to install directories | *dir path* | /usr/local |
> | CPACK_GENERATOR | Use CPack to generate a librpma package | ""/RPM/DEB | "" |
> ```

`a librpma package (RPM or DEB)`

**Review by yangx-jy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2129)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`DEVELOPMENT.md` line 35 at r1](https://reviewable.io/reviews/pmem/rpma/2129#-NU_ST-cArwWefVhS2NU:-NUt021P6qvozr9EwoBu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/94c916f226183a0d17f4b92c60f81643d1e63949/DEVELOPMENT.md#L35)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`a librpma package (RPM or DEB)`
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2129#-:-NUuQ9lR10ojdYW2sQGX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by ldorau — APPROVED** [review]
@grom72 @janekmi @osalyk ping

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2129#-:-NUuQCgC17rUa6TT1Ooy:b-n8bv1l)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2129)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Pull request merged**
