### PR TITLE
tools: perf: introduce controling DDIO from the Python-level

### PR DESCRIPTION
**Pull request by janekmi**
Requirements:

- [x] #1330
- [x] #1328

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1331)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1331)* status: 0 of 12 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 12 files at r1, 7 of 7 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1331)* status: 9 of 12 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 3 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1331#-:-MosnSrA0SVzsB1nw-8K:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1331)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1331#-MostmU_2nCgWFZ26v7D:-MostmU_2nCgWFZ26v7E:b-mkowak) (no related file):*
@janekmi rebase please

---

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1331)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1331)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1331#-:-Mp5sdjf2ixYBfdsa6jG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1331)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
