### PR TITLE
test: add MT helgrind and drd tests to CircleCI

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #980
- [x] suppression files
- [x] #988 

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/984)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/984)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/984)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, 2 of 4 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/984)* status: all files reviewed, 9 unresolved discussions (waiting on @ldorau)

___
*[tests/drd.supp, line 20 at r4](https://reviewable.io/reviews/pmem/rpma/984#-MY5TiQH-01OfW4mTDIR:-MY5TiQH-01OfW4mTDIS:bs4g6ce) ([raw file](https://github.com/pmem/rpma/blob/e220e657b8f667ac81aa0577e49d95ba4a63851d/tests/drd.supp#L20)):*
> ```
>    Race while reading the name of time zone ("GMT").
>    drd:ConflictingAccess
>    ...
> ```

We cannot go any more specific?
___
*[tests/drd.supp, line 29 at r4](https://reviewable.io/reviews/pmem/rpma/984#-MY5TyWF9JiVRKEFOxud:-MY5TyWF9JiVRKEFOxue:b999ymt) ([raw file](https://github.com/pmem/rpma/blob/e220e657b8f667ac81aa0577e49d95ba4a63851d/tests/drd.supp#L29)):*
> ```
>    <rdma_getaddrinfo()>
>    drd:ConflictingAccess
>    ...
> ```

What's wrong with this API call?
___
*[tests/drd.supp, line 39 at r4](https://reviewable.io/reviews/pmem/rpma/984#-MY5U8jVCfnlcEJ4yhNG:-MY5U8jVCfnlcEJ4yhNH:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/e220e657b8f667ac81aa0577e49d95ba4a63851d/tests/drd.supp#L39)):*
> ```
>    <rdma_create_id()>
>    drd:ConflictingAccess
>    ...
> ```

.
___
*[tests/drd.supp, line 48 at r4](https://reviewable.io/reviews/pmem/rpma/984#-MY5U9qwBUW_oGNfgcLZ:-MY5U9qwBUW_oGNfgcL_:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/e220e657b8f667ac81aa0577e49d95ba4a63851d/tests/drd.supp#L48)):*
> ```
>    <rdma_bind_addr()>
>    drd:ConflictingAccess
>    ...
> ```

.
___
*[tests/drd.supp, line 58 at r4](https://reviewable.io/reviews/pmem/rpma/984#-MY5UBNkB5aIHQ3jCpsK:-MY5UBNkB5aIHQ3jCpsL:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/e220e657b8f667ac81aa0577e49d95ba4a63851d/tests/drd.supp#L58)):*
> ```
>    <rdma_destroy_id()>
>    drd:ConflictingAccess
>    ...
> ```

.
___
*[tests/helgrind.supp, line 31 at r4](https://reviewable.io/reviews/pmem/rpma/984#-MY5UORpD0loGWH0W_C2:-MY5UORpD0loGWH0W_C3:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/e220e657b8f667ac81aa0577e49d95ba4a63851d/tests/helgrind.supp#L31)):*
> ```
>    <rdma_getaddrinfo()>
>    Helgrind:Race
>    ...
> ```

.
___
*[tests/helgrind.supp, line 41 at r4](https://reviewable.io/reviews/pmem/rpma/984#-MY5UPCZ9rB0INrSt_qm:-MY5UPCZ9rB0INrSt_qn:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/e220e657b8f667ac81aa0577e49d95ba4a63851d/tests/helgrind.supp#L41)):*
> ```
>    <rdma_create_id()>
>    Helgrind:Race
>    ...
> ```

.
___
*[tests/helgrind.supp, line 50 at r4](https://reviewable.io/reviews/pmem/rpma/984#-MY5UPg2AhxxKfIV0U2Y:-MY5UPg32bT9ZSgCD67Z:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/e220e657b8f667ac81aa0577e49d95ba4a63851d/tests/helgrind.supp#L50)):*
> ```
>    <rdma_bind_addr()>
>    Helgrind:Race
>    ...
> ```

.
___
*[tests/helgrind.supp, line 60 at r4](https://reviewable.io/reviews/pmem/rpma/984#-MY5UQKdAsGRUOTUBn1w:-MY5UQKdAsGRUOTUBn1x:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/e220e657b8f667ac81aa0577e49d95ba4a63851d/tests/helgrind.supp#L60)):*
> ```
>    <rdma_destroy_id()>
>    Helgrind:Race
>    ...
> ```

.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/984)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/984#-MY5WdUf5zx7rh2FcIhF:-MY5WdUf5zx7rh2FcIhG:b-frc5ff) (no related file):*
We have agreed to go more specific with the `rdma_` suppressions iteratively.

---

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/984)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/984)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[tests/drd.supp, line 20 at r4](https://reviewable.io/reviews/pmem/rpma/984#-MY5TiQH-01OfW4mTDIR:-MYAT2f19ic_K0a_FM4A:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e220e657b8f667ac81aa0577e49d95ba4a63851d/tests/drd.supp#L20)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

We cannot go any more specific?
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, 2 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/984#-:-MYAcHwY3jurOQUEa2nJ:bnfp4nl)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/984#-:-MYAdoFC3Zc0Kgh_A-kK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
