### PR TITLE
rpma: remove rpma_write_atomic()

### PR DESCRIPTION
**Pull request by ldorau**
rpma_write_atomic() has been replaced with rpma_atomic_write().

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1615)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1615)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1615#-Mxnn_l2DxHKIenrz2Tv:-Mxnn_l2DxHKIenrz2Tw:bu7yxk3) (no related file):*
shall we remove ```bool fence`` from ```rpma_mr_write``` as it is no longer needed?

---

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1615)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1615#-Mxnn_l2DxHKIenrz2Tv:-MxnoHdL-jah7QPVXd6j:b-3xwbfh) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

shall we remove ```bool fence`` from ```rpma_mr_write``` as it is no longer needed?
</blockquote></details>

or separate PR??

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1615)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1615#-Mxnn_l2DxHKIenrz2Tv:-MxnoJ4m8ZShw8_36HtO:b-kdxmfw) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

or separate PR??
</blockquote></details>

In a separate PR.

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1615)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1615#-Mxnn_l2DxHKIenrz2Tv:-Mxnv-u09iImmaRQSENM:b-mx4twg) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

In a separate PR.
</blockquote></details>

https://github.com/pmem/rpma/pull/1618

Done

---

**Comment by ldorau** [comment]
Included in #1618

**Pull request closed without merging**
