### PR TITLE
rpma: relationship of libibverbs and librdmacm

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1788)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1788)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @osalyk)

___
*[`THREAD_SAFETY.md` line 114 at r1](https://reviewable.io/reviews/pmem/rpma/1788#-N3JdkR47EDcBZRKPJIX:-N3JdkR47EDcBZRKPJIY:b-5yexph) ([raw file](https://github.com/pmem/rpma/blob/5ab2f56992b878fb4bfb10eb0109841088c03d28/THREAD_SAFETY.md#L114)):*
> ```Markdown
> ## Relationship of libibverbs and librdmacm
> 
> The verbs API is fully thread safe and verbs can be called from every thread in the process.
> ```

I think it should be moved to **The main assumptions** sections.
The librpma thread-safe is based on libibverbs thread-safe. 



_Code quote:_
```Markdown
## Relationship of libibverbs and librdmacm

The verbs API is fully thread safe and verbs can be called from every thread in the process.
Detailed description is available at:

 - [rdmamojo/libibverbs](https://www.rdmamojo.com/2013/07/26/libibverbs-thread-safe-level/)
 - [ibv_alloc_td.3](https://man7.org/linux/man-pages/man3/ibv_alloc_td.3.html)
```

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1788)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1788)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1788)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`THREAD_SAFETY.md` line 114 at r1](https://reviewable.io/reviews/pmem/rpma/1788#-N3JdkR47EDcBZRKPJIX:-N3Ji12_6Z9vcFblP3dU:b-zar2ef) ([raw file](https://github.com/pmem/rpma/blob/5ab2f56992b878fb4bfb10eb0109841088c03d28/THREAD_SAFETY.md#L114)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I think it should be moved to **The main assumptions** sections.
The librpma thread-safe is based on libibverbs thread-safe. 
</blockquote></details>

Do you want to move an entire paragraph higher?

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1788)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[`THREAD_SAFETY.md` line 114 at r1](https://reviewable.io/reviews/pmem/rpma/1788#-N3JdkR47EDcBZRKPJIX:-N3JrN6V-zZjMXns-wj5:bfwi20m) ([raw file](https://github.com/pmem/rpma/blob/5ab2f56992b878fb4bfb10eb0109841088c03d28/THREAD_SAFETY.md#L114)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Do you want to move an entire paragraph higher?
</blockquote></details>

Yes, the thread-safety of libibverbs is an assumption of our library thread-safety.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1788)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[`THREAD_SAFETY.md` line 114 at r1](https://reviewable.io/reviews/pmem/rpma/1788#-N3JdkR47EDcBZRKPJIX:-N3K0tnRAGaH5Er1o_zz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5ab2f56992b878fb4bfb10eb0109841088c03d28/THREAD_SAFETY.md#L114)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Yes, the thread-safety of libibverbs is an assumption of our library thread-safety.
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1788)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`THREAD_SAFETY.md` line 15 at r2](https://reviewable.io/reviews/pmem/rpma/1788#-N3K81t11HrRmqF2KQVa:-N3K81t11HrRmqF2KQVb:boif0d2) ([raw file](https://github.com/pmem/rpma/blob/2a0f9dec24bf975acc4a058518053f3a6aeb2edb/THREAD_SAFETY.md#L15)):*
> ```Markdown
>  - [ibv_alloc_td.3](https://man7.org/linux/man-pages/man3/ibv_alloc_td.3.html)
> 
> ### This analysis is based on are following:
> ```

`**The main assumptions** this analysis is based on are following:`



_Code quote:_
```Markdown
This analysis is based on are following:
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1788)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`THREAD_SAFETY.md` line 15 at r2](https://reviewable.io/reviews/pmem/rpma/1788#-N3K81t11HrRmqF2KQVa:-N3K9GK1-kH8x8ygHhFY:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2a0f9dec24bf975acc4a058518053f3a6aeb2edb/THREAD_SAFETY.md#L15)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`**The main assumptions** this analysis is based on are following:`
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1788)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

**Review by grom72 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1788)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1788)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[`THREAD_SAFETY.md` line 114 at r1](https://reviewable.io/reviews/pmem/rpma/1788#-N3JdkR47EDcBZRKPJIX:-N3O2MPs72lDBcLJ_SJ1:b2jxi3w) ([raw file](https://github.com/pmem/rpma/blob/5ab2f56992b878fb4bfb10eb0109841088c03d28/THREAD_SAFETY.md#L114)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't like it. It does not look good. 
It should be only mentioned in the main assumptions, but the whole section should stay here.
___
*[`THREAD_SAFETY.md` line 5 at r3](https://reviewable.io/reviews/pmem/rpma/1788#-N3O3aHi6XbfpX9OX_Co:-N3O3aHi6XbfpX9OX_Cp:b8gddzg) ([raw file](https://github.com/pmem/rpma/blob/f281b6d2772a4fbbe577283bedb3f351e64211bc/THREAD_SAFETY.md#L5)):*
> ```Markdown
> This document presents the analysis of thread safety of the librpma library.
> 
> ## The main assumptions
> ```

```
## Main assumptions

The main assumptions this analysis is based on are following:

1) the API of libibverbs is fully thread safe and it can be called from every thread in the process (see [Relationship of libibverbs and librdmacm](#relationship-of-libibverbs-and-librdmacm) for details)
2) many threads may use the same peer (`struct rpma_peer`) to create separate connections,
3) the whole process of creating a new connection (`struct rpma_conn`) has to be run by exactly one thread (different threads must not be involved in creating the same connection),
4) each of the endpoints (`struct rpma_ep`) can be used by only one thread at the same time and
5) each of the connections (`struct rpma_conn`) can be used by only one thread at the same time.
```



_Code quote:_
```Markdown
## The main assumptions

### Relationship of libibverbs and librdmacm

The verbs API is fully thread safe and verbs can be called from every thread in the process.
Detailed description is available at:

 - [rdmamojo/libibverbs](https://www.rdmamojo.com/2013/07/26/libibverbs-thread-safe-level/)
 - [ibv_alloc_td.3](https://man7.org/linux/man-pages/man3/ibv_alloc_td.3.html)

### **The main assumptions** this analysis is based on are following:
1) many threads may use the same peer (`struct rpma_peer`) to create separate connections,
2) the whole process of creating a new connection (`struct rpma_conn`) has to be run by exactly one thread (different threads must not be involved in creating the same connection),
3) each of the endpoints (`struct rpma_ep`) can be used by only one thread at the same time and
4) each of the connections (`struct rpma_conn`) can be used by only one thread at the same time.
```
___
*[`THREAD_SAFETY.md` line 115 at r3](https://reviewable.io/reviews/pmem/rpma/1788#-N3O39h39F6iX9iy_SmQ:-N3O39h39F6iX9iy_SmR:bflrvu7) ([raw file](https://github.com/pmem/rpma/blob/4969b07110b1e9f56a377c61a352e18e8f23c68c/THREAD_SAFETY.md#L115)):*
> ```Markdown
> - rpma_utils_get_ibv_context
> 
> ## Relationship of libibverbs and librdmacm
> ```

```
## Relationship of libibverbs and librdmacm

The API of libibverbs is fully thread safe and it can be called from every thread in the process.
The detailed description is available at:

 - [rdmamojo/libibverbs](https://www.rdmamojo.com/2013/07/26/libibverbs-thread-safe-level/)
 - [ibv_alloc_td.3](https://man7.org/linux/man-pages/man3/ibv_alloc_td.3.html)

```



_Code quote:_
```Markdown
## Relationship of libibverbs and librdmacm

XXX
```

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1788#-:-N3O7gam-ls92dOiZJQk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
