### PR TITLE
tools: push IOPS to fio-csv output

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1111)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
:clap: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1111#-:-MdNr5WP9YyyDYLUG8nZ:bc0irgz)* status: all files reviewed, 4 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/csv2standardized.py, line 36 at r1](https://reviewable.io/reviews/pmem/rpma/1111#-MdNpg_A6FYwe6H19_4Z:-MdNpg_A6FYwe6H19_4_:b-vvcog9) ([raw file](https://github.com/pmem/rpma/blob/79439d795559f5beda31a64b6c9667a4433bdbc9/tools/perf/csv2standardized.py#L36)):*
> ```Python
> #   - iops - avg. IOPS
> #   - iops_min - min IOPS (optional)
> #   - iops_max - max IOPS (optional)
> ```

1. I think it will be a lot nicer to keep the same order as for BW
2. All BW fields have suffixes. For IOPS I think it should be no different.
2. I think we can do better in explaining what we mean by IOPS e.g as follows

```
# - iops_* group (optional)
#   - iops_min - min [operations/sec] (optional)
#   - iops_max - max [operations/sec] (optional)
#   - iops_avg - avg. [operations/sec]
```
___
*[tools/perf/csv2standardized.py, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/1111#-MdNqthE0BvOC-Q8zx8R:-MdNqthE0BvOC-Q8zx8S:b-cezcn3) ([raw file](https://github.com/pmem/rpma/blob/79439d795559f5beda31a64b6c9667a4433bdbc9/tools/perf/csv2standardized.py#L48)):*
> ```Python
>     'ops', 'lat_pctl_99.0', 'lat_pctl_99.9', 'lat_pctl_99.99',
>     'lat_pctl_99.999', 'bw_avg', 'bw_min', 'bw_max',
>     'iops', 'iops_min', 'iops_max', 'cpuload']
> ```

iops_avg
___
*[tools/perf/csv2standardized.py, line 62 at r1](https://reviewable.io/reviews/pmem/rpma/1111#-MdNqa52738e99GvcayR:-MdNqa535_B4K5TdnIfA:b-t2uokb) ([raw file](https://github.com/pmem/rpma/blob/79439d795559f5beda31a64b6c9667a4433bdbc9/tools/perf/csv2standardized.py#L62)):*
> ```Python
>     'lat_stdev', 'lat_pctl_99.0', 'lat_pctl_99.9', 'lat_pctl_99.99',
>     'lat_pctl_99.999', 'bw_min', 'bw_max', 'bw_avg',
>     'iops', 'iops_min', 'iops_max', 'cpuload']
> ```

Please adjust to the order proposed above.
___
*[tools/perf/csv2standardized.py, line 62 at r1](https://reviewable.io/reviews/pmem/rpma/1111#-MdNr2eF7Z3JOXY07yO3:-MdNr2eF7Z3JOXY07yO4:b-cezcn3) ([raw file](https://github.com/pmem/rpma/blob/79439d795559f5beda31a64b6c9667a4433bdbc9/tools/perf/csv2standardized.py#L62)):*
> ```Python
>     'lat_stdev', 'lat_pctl_99.0', 'lat_pctl_99.9', 'lat_pctl_99.99',
>     'lat_pctl_99.999', 'bw_min', 'bw_max', 'bw_avg',
>     'iops', 'iops_min', 'iops_max', 'cpuload']
> ```

iops_avg

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1111)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/csv2standardized.py, line 36 at r1](https://reviewable.io/reviews/pmem/rpma/1111#-MdNpg_A6FYwe6H19_4Z:-MdQcsI7ElF_4VGuxrZh:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/79439d795559f5beda31a64b6c9667a4433bdbc9/tools/perf/csv2standardized.py#L36)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

1. I think it will be a lot nicer to keep the same order as for BW
2. All BW fields have suffixes. For IOPS I think it should be no different.
2. I think we can do better in explaining what we mean by IOPS e.g as follows

```
# - iops_* group (optional)
#   - iops_min - min [operations/sec] (optional)
#   - iops_max - max [operations/sec] (optional)
#   - iops_avg - avg. [operations/sec]
```
</blockquote></details>

Done.
___
*[tools/perf/csv2standardized.py, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/1111#-MdNqthE0BvOC-Q8zx8R:-MdQdsxW9i2CB8_SLXSx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/79439d795559f5beda31a64b6c9667a4433bdbc9/tools/perf/csv2standardized.py#L48)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

iops_avg
</blockquote></details>

Done.
___
*[tools/perf/csv2standardized.py, line 62 at r1](https://reviewable.io/reviews/pmem/rpma/1111#-MdNqa52738e99GvcayR:-MdQe3y389qILXtHSooN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/79439d795559f5beda31a64b6c9667a4433bdbc9/tools/perf/csv2standardized.py#L62)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please adjust to the order proposed above.
</blockquote></details>

Done.
___
*[tools/perf/csv2standardized.py, line 62 at r1](https://reviewable.io/reviews/pmem/rpma/1111#-MdNr2eF7Z3JOXY07yO3:-MdQe4XZCn6EpPAVH66B:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/79439d795559f5beda31a64b6c9667a4433bdbc9/tools/perf/csv2standardized.py#L62)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

iops_avg
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1111)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/csv2standardized.py, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/1111#-MdNqthE0BvOC-Q8zx8R:-MdR6T9xA2nUTdnNW_gv:bphsx0n) ([raw file](https://github.com/pmem/rpma/blob/79439d795559f5beda31a64b6c9667a4433bdbc9/tools/perf/csv2standardized.py#L48)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The order is different here.
___
*[tools/perf/csv2standardized.py, line 62 at r1](https://reviewable.io/reviews/pmem/rpma/1111#-MdNqa52738e99GvcayR:-MdR6_xX9tI0z-RMw6p_:bphsx0n) ([raw file](https://github.com/pmem/rpma/blob/79439d795559f5beda31a64b6c9667a4433bdbc9/tools/perf/csv2standardized.py#L62)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The order is different here.

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1111)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1111#-:-MdR92QJBNbks4PgFUeR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1111#-:-MdR93KrARl9nZfX5e0y:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1111)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1111)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
