### PR TITLE
common: check and fix format of SPDX tags

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/276)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 98 of 98 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/276)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[utils/check_license/check-headers.sh, line 120 at r2](https://reviewable.io/reviews/pmem/rpma/276#-MF65dw3BpohCJJ2mzSc:-MF65dw3BpohCJJ2mzSd:b72haww) ([raw file](https://github.com/pmem/rpma/blob/1d1f4ffc1d97f5499a029e7cb9a504a1e97c37a5/utils/check_license/check-headers.sh#L120)):*
> ```Shell
> 		fi
> 	elif [[ $(echo $file) =~ ".h" ]]; then
> 		if grep -q -e "\/\/ SPDX-License-Identifier: $LICENSE" $src_path; then
> ```

Patterns for *.c and *.h files are the same or I am missing something?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/276)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[utils/check_license/check-headers.sh, line 120 at r2](https://reviewable.io/reviews/pmem/rpma/276#-MF65dw3BpohCJJ2mzSc:-MF7_l8SBK-fq69Y6S46:b-6zkvvc) ([raw file](https://github.com/pmem/rpma/blob/1d1f4ffc1d97f5499a029e7cb9a504a1e97c37a5/utils/check_license/check-headers.sh#L120)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Patterns for *.c and *.h files are the same or I am missing something?
</blockquote></details>

*.c: `if ! grep` - negation
*.h: `if grep` - no negation

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 45 of 98 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/276#-:-MF9Eh1B5LftlkJEN-SZ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[utils/check_license/check-headers.sh, line 120 at r2](https://reviewable.io/reviews/pmem/rpma/276#-MF65dw3BpohCJJ2mzSc:-MF9Gwgu0alJf6h409-C:bvs9ofc) ([raw file](https://github.com/pmem/rpma/blob/1d1f4ffc1d97f5499a029e7cb9a504a1e97c37a5/utils/check_license/check-headers.sh#L120)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

*.c: `if ! grep` - negation
*.h: `if grep` - no negation
</blockquote></details>

C source: // SPDX-License-Identifier: <SPDX License Expression>
C header: /* SPDX-License-Identifier: <SPDX License Expression> */
ASM:      /* SPDX-License-Identifier: <SPDX License Expression> */
scripts:  # SPDX-License-Identifier: <SPDX License Expression>
.rst:     .. SPDX-License-Identifier: <SPDX License Expression>
.dts{i}:  // SPDX-License-Identifier: <SPDX License Expression>

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/276)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[utils/check_license/check-headers.sh, line 120 at r2](https://reviewable.io/reviews/pmem/rpma/276#-MF65dw3BpohCJJ2mzSc:-MF9PCxrBla6O9dLPxyd:b1ozusa) ([raw file](https://github.com/pmem/rpma/blob/1d1f4ffc1d97f5499a029e7cb9a504a1e97c37a5/utils/check_license/check-headers.sh#L120)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

C source: // SPDX-License-Identifier: <SPDX License Expression>
C header: /* SPDX-License-Identifier: <SPDX License Expression> */
ASM:      /* SPDX-License-Identifier: <SPDX License Expression> */
scripts:  # SPDX-License-Identifier: <SPDX License Expression>
.rst:     .. SPDX-License-Identifier: <SPDX License Expression>
.dts{i}:  // SPDX-License-Identifier: <SPDX License Expression>
</blockquote></details>

@grom72 what did you intended to say by that?

We check those:

C source: // SPDX-License-Identifier:
C header: /* SPDX-License-Identifier: */
scripts: # SPDX-License-Identifier:

All the rest we do not have in or repo.

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/276)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[utils/check_license/check-headers.sh, line 120 at r2](https://reviewable.io/reviews/pmem/rpma/276#-MF65dw3BpohCJJ2mzSc:-MF9P_K2A7Cf2i09sgIX:b4thwll) ([raw file](https://github.com/pmem/rpma/blob/1d1f4ffc1d97f5499a029e7cb9a504a1e97c37a5/utils/check_license/check-headers.sh#L120)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@grom72 what did you intended to say by that?

We check those:

C source: // SPDX-License-Identifier:
C header: /* SPDX-License-Identifier: */
scripts: # SPDX-License-Identifier:

All the rest we do not have in or repo.
</blockquote></details>

Wouldn't be easier to match what should be instead of checking it is not one of the invalid forms?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/276)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[utils/check_license/check-headers.sh, line 120 at r2](https://reviewable.io/reviews/pmem/rpma/276#-MF65dw3BpohCJJ2mzSc:-MF9Qjvu6wdXfguCRQ8j:b-7cbpyr) ([raw file](https://github.com/pmem/rpma/blob/1d1f4ffc1d97f5499a029e7cb9a504a1e97c37a5/utils/check_license/check-headers.sh#L120)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Wouldn't be easier to match what should be instead of checking it is not one of the invalid forms?
</blockquote></details>

Right :-)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/276)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[utils/check_license/check-headers.sh, line 120 at r2](https://reviewable.io/reviews/pmem/rpma/276#-MF65dw3BpohCJJ2mzSc:-MF9V6FH5YgDZVZAOdOS:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/1d1f4ffc1d97f5499a029e7cb9a504a1e97c37a5/utils/check_license/check-headers.sh#L120)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Right :-)
</blockquote></details>

Done

**Review by grom72 — COMMENTED** [review]
> Reviewed 6 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/276)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/276#-:-MF9cESQ8-EwhBSomfVV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
