### PR TITLE
tools: perf: BaseRunner and IbReadRunner (scaffolding)

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1328)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1328)* status: 0 of 9 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, 3 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1328)* status: 5 of 9 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, 1 of 5 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1328)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[tools/perf/lib/benchmark/runner/base.py, line 17 at r3](https://reviewable.io/reviews/pmem/rpma/1328#-Mongj882UvG06O8Xmlb:-Mongj882UvG06O8Xmlc:b-68rvo3) ([raw file](https://github.com/pmem/rpma/blob/4f36f2f5f29c3b71af9d9c03cdaa353231853266/tools/perf/lib/benchmark/runner/base.py#L17)):*
> ```
>  'ib': 
> ```

Maybe ` 'ib_read': ` ?

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1328)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1328)* status: 8 of 9 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/lib/benchmark/runner/base.py, line 17 at r3](https://reviewable.io/reviews/pmem/rpma/1328#-Mongj882UvG06O8Xmlb:-Monzmwe0l6reytehk4g:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4f36f2f5f29c3b71af9d9c03cdaa353231853266/tools/perf/lib/benchmark/runner/base.py#L17)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  'ib': 
> ```

Maybe ` 'ib_read': ` ?
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1328)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
> Reviewed 2 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1328)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1328#-:-Moradtw5xa7-QuKQd1e:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1328)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1328#-:-MoshVWu81n3UWkEWT6_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
