### PR TITLE
rpma: implement rpma_atomic_write()

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #1594
- [ ] unit tests

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1595)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1595)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1595#-MwasKCCC6Fci6fGMp4A:-MwasKCCC6Fci6fGMp4B:b-8ro3zp) (no related file):*
Please check PR title.

---

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1595)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[src/mr.c, line 201 at r2](https://reviewable.io/reviews/pmem/rpma/1595#-MwawAR_-XVDZhiz839D:-MwawAR_-XVDZhiz839E:bibepbn) ([raw file](https://github.com/pmem/rpma/blob/52bd2a6457e16fc799d61c0698fcc7686818eb18/src/mr.c#L201)):*
> ```C
> 
> 	/* source */
> 	sge.addr = (uint64_t)((uintptr_t)src);
> ```

do we want any mechanism here (iterate via 8 bytes) to check that there will not be a memory exception inside ```ibv_post_send()```?



_Code quote:_
```C
sge.addr = (uint64_t)((uintptr_t)src);
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1595)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[src/mr.c, line 201 at r2](https://reviewable.io/reviews/pmem/rpma/1595#-MwawAR_-XVDZhiz839D:-MwaxYqFAfXassjCASct:btaykm7) ([raw file](https://github.com/pmem/rpma/blob/52bd2a6457e16fc799d61c0698fcc7686818eb18/src/mr.c#L201)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

do we want any mechanism here (iterate via 8 bytes) to check that there will not be a memory exception inside ```ibv_post_send()```?
</blockquote></details>

I'm afraid there is no easy and low-cost way to verify that. Do you have any idea how we could do that? I do not.

If we try to iterate and read this memory, we will just get SEGFAULT here.

If a user provides trashes at the input, then they receive thrashes (SEGFAULT for example) at the output - that's the general rule, so it is the user's responsibility to provide a correct input data. We cannot check everything. We often check pointers against the NULL (0x0) value, but if a user provides a pointer with a value of 0x1, 0x2, ... then they will get SEGFAULT anyway ...



_Code quote:_
```C
opcode=IBV_WR_RDMA_WRITE
```

**Review by grom72 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1595)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1595)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — CHANGES_REQUESTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1595#-:-MwbPBeyB54nto0OVuUn:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/mr.c, line 213 at r3](https://reviewable.io/reviews/pmem/rpma/1595#-MwbPVB02AbD857L7wVl:-MwbPVB02AbD857L7wVm:bf371bn) ([raw file](https://github.com/pmem/rpma/blob/f949908a035d8a6f32f2e7564200c738d8b1f24a/src/mr.c#L213)):*
> ```C
> 	wr.next = NULL;
> 	wr.opcode = IBV_WR_RDMA_WRITE;
> 	wr.send_flags = IBV_SEND_INLINE | IBV_SEND_FENCE;
> ```

Short information to be added here ( @ldorau feel free to rephrase it):
/* IBV_SEND_FENCE is used to force any ongoing read operation (that might emulate remote flush) to be finished before an atomic write is executed */



_Code quote:_
```C
IBV_SEND_FENCE
```

**Review by grom72 — COMMENTED** [review]
:lgtm_cancel: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1595#-:-MwbQK4DDUGe4xi4WRTK:b8b79qu)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1595)* status: 1 of 9 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[src/mr.c, line 213 at r3](https://reviewable.io/reviews/pmem/rpma/1595#-MwbPVB02AbD857L7wVl:-MwzIFpa338CNAxYp4R2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f949908a035d8a6f32f2e7564200c738d8b1f24a/src/mr.c#L213)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Short information to be added here ( @ldorau feel free to rephrase it):
/* IBV_SEND_FENCE is used to force any ongoing read operation (that might emulate remote flush) to be finished before an atomic write is executed */
</blockquote></details>

Done.

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1595)* status: 1 of 9 files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by osalyk — APPROVED** [review]
> Reviewed 2 of 9 files at r1, 2 of 8 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1595)* status: 4 of 10 files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1595)* status: 4 of 10 files reviewed, 2 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1595#-Mx-q33I0RkI4bmXjcSg:-Mx-q33JB-SLYSBE5TRl:b-ro0r1e) (no related file):*
This PR cannot be merged without unit tests.

---

**Review by grom72 — APPROVED** [review]
> Reviewed 7 of 8 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1595)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72, @haichangsi, and @osalyk)

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1595)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72, @haichangsi, and @osalyk)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1595#-:-MxYOqwr6X3IMgVBLx_Y:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72, @haichangsi, and @osalyk)

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1595#-:-MxYT8IS0Ysfi_YkRFV1:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72, @haichangsi, and @osalyk)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1595)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72, @haichangsi, and @osalyk)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1595#-:-MxZR6nR3FhZuZEHuhHk:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72, @haichangsi, and @osalyk)

**Review by osalyk — APPROVED** [review]
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1595)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72, @haichangsi, and @osalyk)

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1595)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)

___
*[CHANGELOG.md, line 14 at r7](https://reviewable.io/reviews/pmem/rpma/1595#-MxZkINY8pyL2OdPu6lk:-MxZkINY8pyL2OdPu6ll:b-b738qa) ([raw file](https://github.com/pmem/rpma/blob/9c1ecad9167b445fa9bb0e44c837d57df6bf0464/CHANGELOG.md#L14)):*
> ```Markdown
> 
> ### Changed
> - ibv_qp_cap.max_inline_data set to 8 bytes
> ```

ibv_qp_cap.max_inline_data set to 8 bytes to allow atomic write implementation over ibv_send with IBV_SEND_INLINE



_Code quote:_
```Markdown
ibv_qp_cap.max_inline_data set to 8 bytes
```

**Review by grom72 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1595)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72, @haichangsi, and @osalyk)

**Comment by ldorau** [comment]
Included in https://github.com/pmem/rpma/pull/1601

**Pull request closed without merging**
