### PR TITLE
tools: add block size values

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/683)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/683)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/rpma_fio_bench.sh, line 62 at r1](https://reviewable.io/reviews/pmem/rpma/683#-MOriHCj2oUV24icXjPb:-MOriHCj2oUV24icXjPc:b-jx9xzr) ([raw file](https://github.com/pmem/rpma/blob/7755666b8f24378eb49f70601fd219e8d945938f/tools/rpma_fio_bench.sh#L62)):*
> ```Shell
> 	THREADS=1
> 	BLOCK_SIZE=(256 1024 4096 8192 16384 24576 32768 65536)
> 	ITERATIONS=${#BLOCK_SIZE[@]}
> ```

I would propose 512 and 2048 also

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/683)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/rpma_fio_bench.sh, line 62 at r1](https://reviewable.io/reviews/pmem/rpma/683#-MOriHCj2oUV24icXjPb:-MP35yCsAiIShQbWQPU5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7755666b8f24378eb49f70601fd219e8d945938f/tools/rpma_fio_bench.sh#L62)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I would propose 512 and 2048 also
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/683)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/683#-:-MP3IDi81sMhAS6y5vlT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/683)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/rpma_fio_bench.sh, line 61 at r2](https://reviewable.io/reviews/pmem/rpma/683#-MPcGCekCq5oh8j0fjM8:-MPcGCel5J-CuZcBxoSw:b-51wvlw) ([raw file](https://github.com/pmem/rpma/blob/de592f9db0b6b8822699be126ad99fdeca0114f6/tools/rpma_fio_bench.sh#L61)):*
> ```
> 24576 
> ```

Is `24576` really needed? It is not a power of 2 - are you sure it will look good on a graph with the logarithmic scale?

**Review by janekmi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/683#-:-MPcdxRwAoelrV_VnS85:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/rpma_fio_bench.sh, line 61 at r2](https://reviewable.io/reviews/pmem/rpma/683#-MPcGCekCq5oh8j0fjM8:-MPcdXk86AhhuD0EYQ_i:b-9f5w32) ([raw file](https://github.com/pmem/rpma/blob/de592f9db0b6b8822699be126ad99fdeca0114f6/tools/rpma_fio_bench.sh#L61)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 24576 
> ```

Is `24576` really needed? It is not a power of 2 - are you sure it will look good on a graph with the logarithmic scale?
</blockquote></details>

Let be it. Currently, it is not about the powers of 2 but more about having characteristics points of the chart using as few points as possible.

**Review by janekmi — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/683)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/683)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/683#-:-MPcf0B_DyTwq8dCxSYS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
