### PR TITLE
doc: perf-tuning-latency workloads

### PR DESCRIPTION
**Pull request by janekmi**
Requires:
- [x] #595
- [x] #600

This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/599)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
Preview is not available at the given link: https://janekmi.github.io/rpma/documentation/perf-tuning-latency.html

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/599#-:-MM_sIIg8nI_bBLsPKaZ:b-207s03)* status: 0 of 1 files reviewed, all discussions resolved

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/599)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[documentation/perf-tuning-latency.md, line 108 at r1](https://reviewable.io/reviews/pmem/rpma/599#-MM_sc9a1rPt3JGcxOqx:-MM_sc9a1rPt3JGcxOqy:b-ir2juq) ([raw file](https://github.com/pmem/rpma/blob/642a3e38369c87397ab36b7f0936f21806cedb72/documentation/perf-tuning-latency.md#L108)):*
> ```
> in check
> ```

? what do you mean by `in check`? Maybe  `When you have everything checked ...`

**Review by janekmi — COMMENTED** [review]
You are right. I can not host all of these at the same time.
The updated revision should be there in a minute.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/599#-:-MM_u3pK7h_orLxmoGYX:b-ppkcp5)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[documentation/perf-tuning-latency.md, line 108 at r1](https://reviewable.io/reviews/pmem/rpma/599#-MM_sc9a1rPt3JGcxOqx:-MM_w-jG7rgXquAeHlNW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/642a3e38369c87397ab36b7f0936f21806cedb72/documentation/perf-tuning-latency.md#L108)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> in check
> ```

? what do you mean by `in check`? Maybe  `When you have everything checked ...`
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/599)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/599#-:-MM_xBvrDYS55dxOr835:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
