### PR TITLE
test: add rpma_conn_req_recv() to mtt_client_connect()

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1720)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1720)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1720#-N0pKWhG-Ekl7U9xW9T3:-N0pNBRU0PuIfOw5SJ8e:byjfen2) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Just want to ack why do we add some parameters in this PR and do not use them?
</blockquote></details>

Because there are no test yet that can use them.

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1720)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1720#-N0pKWhG-Ekl7U9xW9T3:-N0pNNJBEj9VX4nah5WJ:b-ehj5t1) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Because there are no test yet that can use them.
</blockquote></details>

For an example of usage see here: https://github.com/ldorau/rpma/commits/test-add-rpma_recv-MT-test.

---

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1720#-:-N0pU3dZ1I-sm50W-Ou8:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1720)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request closed without merging**
