### PR TITLE
doc: perf-tuning-latency BIOS & CPU

### PR DESCRIPTION
**Pull request by janekmi**
Preview: https://janekmi.github.io/rpma/documentation/perf-tuning-latency.html

This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/595)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/595)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[documentation/perf-tuning-latency.md, line 21 at r1](https://reviewable.io/reviews/pmem/rpma/595#-MMVsK_TAUt1GrWp1Gu8:-MMVsK_TAUt1GrWp1Gu9:bhll0gp) ([raw file](https://github.com/pmem/rpma/blob/a2f0b9ba1738691ceb867aa5364a073972cb23ed/documentation/perf-tuning-latency.md#L21)):*
> ```
> Turbo 
> ```

What do you mean? Turbo button? ;-)
___
*[documentation/perf-tuning-latency.md, line 22 at r1](https://reviewable.io/reviews/pmem/rpma/595#-MMVskneDJNlX5laZCU4:-MMVskneDJNlX5laZCU5:blq975w) ([raw file](https://github.com/pmem/rpma/blob/a2f0b9ba1738691ceb867aa5364a073972cb23ed/documentation/perf-tuning-latency.md#L22)):*
> ```
> after turning C-states off
> ```

Where did you write about it?
___
*[documentation/perf-tuning-latency.md, line 23 at r1](https://reviewable.io/reviews/pmem/rpma/595#-MMVtOZj6_NMyA6HWdV6:-MMVtOZj6_NMyA6HWdV7:b-keg0pf) ([raw file](https://github.com/pmem/rpma/blob/a2f0b9ba1738691ceb867aa5364a073972cb23ed/documentation/perf-tuning-latency.md#L23)):*
> ```
> fan speed settings
> ```

How should the speed of fans should be adjusted? Faster/slower? ;-)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/595)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/595)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[documentation/perf-tuning-latency.md, line 22 at r1](https://reviewable.io/reviews/pmem/rpma/595#-MMVskneDJNlX5laZCU4:-MM_N1WvDHC2HIBqcwQy:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a2f0b9ba1738691ceb867aa5364a073972cb23ed/documentation/perf-tuning-latency.md#L22)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> after turning C-states off
> ```

Where did you write about it?
</blockquote></details>

Done.
___
*[documentation/perf-tuning-latency.md, line 23 at r1](https://reviewable.io/reviews/pmem/rpma/595#-MMVtOZj6_NMyA6HWdV6:-MM_Nx8UAbNmsuvrcvSF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a2f0b9ba1738691ceb867aa5364a073972cb23ed/documentation/perf-tuning-latency.md#L23)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> fan speed settings
> ```

How should the speed of fans should be adjusted? Faster/slower? ;-)
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/595)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/595#-:-MM_PEFM8ZpBBIkPT_oU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/595#-:-MM_RKm71dvoFktUrLsw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
