### PR TITLE
rpma: add RDMA_CM_EVENT_REJECTED event handler

### PR DESCRIPTION
**Pull request by osalyk**
Improve examples?

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/802)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/802)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/802#-MSDNhId74DwyFLrVw3U:-MSDNhId74DwyFLrVw3V:b-7rn2ii) (no related file):*
Please use this API at least in one simple example so we will be sure the API is complete and can be used for repeating the connection attempt.

---
___
*[tests/unit/conn/conn-next_event.c, line 508 at r1](https://reviewable.io/reviews/pmem/rpma/802#-MSDMu0zBZOlVYcTaW_5:-MSDMu1-A7UiElgwmUGW:b-8zj0vi) ([raw file](https://github.com/pmem/rpma/blob/b0de5f261237b0d62937045f152d9b1495748793/tests/unit/conn/conn-next_event.c#L508)):*
> ```C
> 
> /*
>  * next_event__success_REJECTED - happy day scenario
> ```

Always look on the bright side of life... :sun_behind_small_cloud:

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/802#-:-MSDPlDz7comxy3DjjQ4:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/802)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[examples/01-connection/client.c, line 86 at r2](https://reviewable.io/reviews/pmem/rpma/802#-MSRIRF6DdteqVwdI7Tn:-MSRIRF6DdteqVwdI7To:b-rsnrhj) ([raw file](https://github.com/pmem/rpma/blob/751b4a9804af2777ed213719b3250284d43035ad/examples/01-connection/client.c#L86)):*
> ```
> err_conn_delete;
> ```
goto from inside the loop in no critical error situation is not good solution see my proposal in pmem/fio/198

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/802)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[examples/01-connection/client.c, line 22 at r2](https://reviewable.io/reviews/pmem/rpma/802#-MSRJElU7t_qTGel57dN:-MSRJElU7t_qTGel57dO:bw963ir) ([raw file](https://github.com/pmem/rpma/blob/751b4a9804af2777ed213719b3250284d43035ad/examples/01-connection/client.c#L22)):*
> ```
> 5
> ```
```#define RETRY_DELAY 5 ```

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/802)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/802)* status: all files reviewed, 4 unresolved discussions (waiting on @osalyk)

___
*[examples/01-connection/client.c, line 61 at r2](https://reviewable.io/reviews/pmem/rpma/802#-MSR_MyE4GfSkNOrpL9q:-MSR_MyE4GfSkNOrpL9r:bbwgtx2) ([raw file](https://github.com/pmem/rpma/blob/751b4a9804af2777ed213719b3250284d43035ad/examples/01-connection/client.c#L61)):*
> ```C
> 		return ret;
> 
> 	/* connect the connection request and obtain the connection object */
> ```

`/* prepare a connection's private data */`
___
*[examples/01-connection/client.c, line 92 at r2](https://reviewable.io/reviews/pmem/rpma/802#-MSR_pxR1NvxEQqjXUPW:-MSR_pxR1NvxEQqjXUPX:btkv0j4) ([raw file](https://github.com/pmem/rpma/blob/751b4a9804af2777ed213719b3250284d43035ad/examples/01-connection/client.c#L92)):*
> ```C
> 		if (rpma_conn_disconnect(conn)) {
> 			(void) rpma_conn_delete(&conn);
> 			goto err_peer_delete;
> ```

```c
    if (rpma_conn_disconnect(conn)) {
        (void) rpma_conn_delete(&conn);
        conn = NULL; /* just in case rpma_conn_delete will fail */
        break;
    } else {
        if (rpma_conn_delete(&conn)) {
            conn = NULL;
            break;
        }
     }
```

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/802)* status: all files reviewed, 5 unresolved discussions (waiting on @osalyk)

___
*[examples/01-connection/client.c, line 101 at r2](https://reviewable.io/reviews/pmem/rpma/802#-MSRb3Jb82QSMGYPiCEU:-MSRb3Jb82QSMGYPiCEV:b-bmc7nf) ([raw file](https://github.com/pmem/rpma/blob/751b4a9804af2777ed213719b3250284d43035ad/examples/01-connection/client.c#L101)):*
> ```C
> 		retry(retry);
> 	}
> ```

```c
if (conn == NULL)
    goto err_peer_delete;
```

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/802)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[examples/01-connection/client.c, line 86 at r2](https://reviewable.io/reviews/pmem/rpma/802#-MSRIRF6DdteqVwdI7Tn:-MSRdXvp3Rzcv3hh9fRe:b-585sa5) ([raw file](https://github.com/pmem/rpma/blob/751b4a9804af2777ed213719b3250284d43035ad/examples/01-connection/client.c#L86)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> err_conn_delete;
> ```
goto from inside the loop in no critical error situation is not good solution see my proposal in pmem/fio/198
</blockquote></details>

My proposition to solve this issue is:

```c
static inline void
conn_drop_and_delete(struct rpma_conn **conn_ptr) {
    (void) rpma_conn_disconnect(conn_ptr);
    (void) rpma_conn_delete(conn_ptr);
    *conn_ptr = NULL; 
}

/* ... */

ret = rpma_conn_next_event(conn, &conn_event);
if (ret) {
    conn_drop_and_delete(&conn);
    break;
} else if (conn_event == RPMA_CONN_ESTABLISHED) {
    break;
} else if (conn_event == RPMA_CONN_REJECTED) {
    fprintf(stderr,
            "rpma_conn_next_event: %s\n",
            rpma_utils_conn_event_2str(conn_event));
    if (retry < MAX_RETRY - 1) {
        fprintf(stderr, "The retry number exceeded. Closing.\n");
        conn_drop_and_delete(&conn);
        break;
    } else {
        fprintf(stderr, "Retrying...\n");
    }
} else {
    fprintf(stderr,
            "rpma_conn_next_event returned an unexpected event: %s\n",
            rpma_utils_conn_event_2str(conn_event));
    conn_drop_and_delete(&conn);
    break;
}
```

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/802)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @osalyk)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/802)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[examples/01-connection/client.c, line 86 at r2](https://reviewable.io/reviews/pmem/rpma/802#-MSRIRF6DdteqVwdI7Tn:-MSRhZAH9TtcD22SKF7y:b9cwc8w) ([raw file](https://github.com/pmem/rpma/blob/751b4a9804af2777ed213719b3250284d43035ad/examples/01-connection/client.c#L86)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

My proposition to solve this issue is:

```c
static inline void
conn_drop_and_delete(struct rpma_conn **conn_ptr) {
    (void) rpma_conn_disconnect(conn_ptr);
    (void) rpma_conn_delete(conn_ptr);
    *conn_ptr = NULL; 
}

/* ... */

ret = rpma_conn_next_event(conn, &conn_event);
if (ret) {
    conn_drop_and_delete(&conn);
    break;
} else if (conn_event == RPMA_CONN_ESTABLISHED) {
    break;
} else if (conn_event == RPMA_CONN_REJECTED) {
    fprintf(stderr,
            "rpma_conn_next_event: %s\n",
            rpma_utils_conn_event_2str(conn_event));
    if (retry < MAX_RETRY - 1) {
        fprintf(stderr, "The retry number exceeded. Closing.\n");
        conn_drop_and_delete(&conn);
        break;
    } else {
        fprintf(stderr, "Retrying...\n");
    }
} else {
    fprintf(stderr,
            "rpma_conn_next_event returned an unexpected event: %s\n",
            rpma_utils_conn_event_2str(conn_event));
    conn_drop_and_delete(&conn);
    break;
}
```
</blockquote></details>

```*conn_ptr = NULL;``` not needed
```conn_drop_and_delete(&conn);``` shall be called every time conn_event == RPMA_CONN_REJECTED
___
*[examples/01-connection/client.c, line 90 at r2](https://reviewable.io/reviews/pmem/rpma/802#-MSRiPBH8YaVsy3d-f1h:-MSRiPBH8YaVsy3d-f1i:b-oku25n) ([raw file](https://github.com/pmem/rpma/blob/751b4a9804af2777ed213719b3250284d43035ad/examples/01-connection/client.c#L90)):*
> ```
> 		if (rpma_conn_disconnect(conn)) {
> 			(void) rpma_conn_delete(&conn);
> 			goto err_peer_delete;
> ```
why is it a part of the connection establish loop

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/802)* status: 5 of 6 files reviewed, 6 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/802#-MSDNhId74DwyFLrVw3U:-MSNMsEuAt0Hhk35aklS:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please use this API at least in one simple example so we will be sure the API is complete and can be used for repeating the connection attempt.
</blockquote></details>

Done.

---
___
*[examples/01-connection/client.c, line 22 at r2](https://reviewable.io/reviews/pmem/rpma/802#-MSRJElU7t_qTGel57dN:-MSR_lrQ22GIaHU8UuqF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/751b4a9804af2777ed213719b3250284d43035ad/examples/01-connection/client.c#L22)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> 5
> ```
```#define RETRY_DELAY 5 ```
</blockquote></details>

Done.
___
*[examples/01-connection/client.c, line 61 at r2](https://reviewable.io/reviews/pmem/rpma/802#-MSR_MyE4GfSkNOrpL9q:-MSRc-VSASHQL9B5y8Gl:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/751b4a9804af2777ed213719b3250284d43035ad/examples/01-connection/client.c#L61)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`/* prepare a connection's private data */`
</blockquote></details>

Done.
___
*[examples/01-connection/client.c, line 86 at r2](https://reviewable.io/reviews/pmem/rpma/802#-MSRIRF6DdteqVwdI7Tn:-MSRjjwWEpcllHubXyht:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/751b4a9804af2777ed213719b3250284d43035ad/examples/01-connection/client.c#L86)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```*conn_ptr = NULL;``` not needed
```conn_drop_and_delete(&conn);``` shall be called every time conn_event == RPMA_CONN_REJECTED
</blockquote></details>

Done.
___
*[examples/01-connection/client.c, line 92 at r2](https://reviewable.io/reviews/pmem/rpma/802#-MSR_pxR1NvxEQqjXUPW:-MSRcRszBNXrZyHG1FSl:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/751b4a9804af2777ed213719b3250284d43035ad/examples/01-connection/client.c#L92)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
    if (rpma_conn_disconnect(conn)) {
        (void) rpma_conn_delete(&conn);
        conn = NULL; /* just in case rpma_conn_delete will fail */
        break;
    } else {
        if (rpma_conn_delete(&conn)) {
            conn = NULL;
            break;
        }
     }
```
</blockquote></details>

Done.
___
*[examples/01-connection/client.c, line 101 at r2](https://reviewable.io/reviews/pmem/rpma/802#-MSRb3Jb82QSMGYPiCEU:-MSRcc187Q301NV-e71J:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/751b4a9804af2777ed213719b3250284d43035ad/examples/01-connection/client.c#L101)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
if (conn == NULL)
    goto err_peer_delete;
```
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/802)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[examples/01-connection/client.c, line 87 at r4](https://reviewable.io/reviews/pmem/rpma/802#-MSRkpBeDdXzGupaKjWF:-MSRkpBeDdXzGupaKjWG:b-fuhp06) ([raw file](https://github.com/pmem/rpma/blob/7f131a1a182187f50a4e5feacd2f7be4181c3a61/examples/01-connection/client.c#L87)):*
> ```C
> 			fprintf(stderr,
> 			"rpma_conn_next_event: %s\n",
> 			rpma_utils_conn_event_2str(conn_event));
> ```

Indentation.
___
*[examples/01-connection/client.c, line 96 at r4](https://reviewable.io/reviews/pmem/rpma/802#-MSRl-aB9qvJ4YOwocnz:-MSRl-aB9qvJ4YOwoco-:b-lau9c3) ([raw file](https://github.com/pmem/rpma/blob/7f131a1a182187f50a4e5feacd2f7be4181c3a61/examples/01-connection/client.c#L96)):*
> ```C
> 			} else {
> 				fprintf(stderr,
> 						"The retry number exceeded. Closing.\n");
> ```

This line does not fit into the previous line?
___
*[examples/01-connection/client.c, line 101 at r4](https://reviewable.io/reviews/pmem/rpma/802#-MSRl8sl2aYq9MSSxgW_:-MSRl8sl2aYq9MSSxgWa:b2j1gg1) ([raw file](https://github.com/pmem/rpma/blob/7f131a1a182187f50a4e5feacd2f7be4181c3a61/examples/01-connection/client.c#L101)):*
> ```C
> 		} else {
> 			fprintf(stderr,
> 					"rpma_conn_next_event returned an unexpected event\n");
> ```

Please use `rpma_utils_conn_event_2str()`.

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/802)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[examples/01-connection/client.c, line 70 at r4](https://reviewable.io/reviews/pmem/rpma/802#-MSRlenGAtanSudo3qhA:-MSRlenGAtanSudo3qhB:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/7f131a1a182187f50a4e5feacd2f7be4181c3a61/examples/01-connection/client.c#L70)):*
> ```C
> 		ret = rpma_conn_req_new(peer, addr, port, NULL, &req);
> 		if (ret)
> 			goto err_peer_delete;
> ```

.
___
*[examples/01-connection/client.c, line 74 at r4](https://reviewable.io/reviews/pmem/rpma/802#-MSRlfJT0vDiCix0U8kY:-MSRlfJT0vDiCix0U8kZ:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/7f131a1a182187f50a4e5feacd2f7be4181c3a61/examples/01-connection/client.c#L74)):*
> ```C
> 		ret = rpma_conn_req_connect(&req, &pdata, &conn);
> 		if (ret)
> 			goto err_req_delete;
> ```

.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/802)* status: all files reviewed, 5 unresolved discussions (waiting on @osalyk)

___
*[examples/01-connection/client.c, line 86 at r4](https://reviewable.io/reviews/pmem/rpma/802#-MSRkWcA8FEx_6W35uFm:-MSRkWcB5Qp_3O1JMsIS:b1yvk71) ([raw file](https://github.com/pmem/rpma/blob/7f131a1a182187f50a4e5feacd2f7be4181c3a61/examples/01-connection/client.c#L86)):*
> ```
> 			fprintf(stderr,
> 			"rpma_conn_next_event: %s\n",
> 			rpma_utils_conn_event_2str(conn_event));
> ```
too many lines??

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/802)* status: all files reviewed, 5 unresolved discussions (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/802)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[examples/01-connection/client.c, line 86 at r4](https://reviewable.io/reviews/pmem/rpma/802#-MSRkWcA8FEx_6W35uFm:-MSRqO2UCah4PBe5Ja1i:bl8chhn) ([raw file](https://github.com/pmem/rpma/blob/7f131a1a182187f50a4e5feacd2f7be4181c3a61/examples/01-connection/client.c#L86)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> 			fprintf(stderr,
> 			"rpma_conn_next_event: %s\n",
> 			rpma_utils_conn_event_2str(conn_event));
> ```
too many lines??
</blockquote></details>

wrong alignment

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/802)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/802)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[examples/01-connection/client.c, line 70 at r4](https://reviewable.io/reviews/pmem/rpma/802#-MSRlenGAtanSudo3qhA:-MSRmaCr6eMulbyYG7gH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7f131a1a182187f50a4e5feacd2f7be4181c3a61/examples/01-connection/client.c#L70)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[examples/01-connection/client.c, line 74 at r4](https://reviewable.io/reviews/pmem/rpma/802#-MSRlfJT0vDiCix0U8kY:-MSRmahm9_LeX0WjOACK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7f131a1a182187f50a4e5feacd2f7be4181c3a61/examples/01-connection/client.c#L74)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[examples/01-connection/client.c, line 86 at r4](https://reviewable.io/reviews/pmem/rpma/802#-MSRkWcA8FEx_6W35uFm:-MSRsFKo4OAmqhGAQ9Ok:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7f131a1a182187f50a4e5feacd2f7be4181c3a61/examples/01-connection/client.c#L86)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

wrong alignment
</blockquote></details>

Done.
___
*[examples/01-connection/client.c, line 87 at r4](https://reviewable.io/reviews/pmem/rpma/802#-MSRkpBeDdXzGupaKjWF:-MSRls5yAQJQ-xvjTuZI:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7f131a1a182187f50a4e5feacd2f7be4181c3a61/examples/01-connection/client.c#L87)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Indentation.
</blockquote></details>

Done.
___
*[examples/01-connection/client.c, line 96 at r4](https://reviewable.io/reviews/pmem/rpma/802#-MSRl-aB9qvJ4YOwocnz:-MSRmOJoDowQLoxuY3o5:b-z94wyg) ([raw file](https://github.com/pmem/rpma/blob/7f131a1a182187f50a4e5feacd2f7be4181c3a61/examples/01-connection/client.c#L96)):*
> This line does not fit into the previous line?
90 characters
___
*[examples/01-connection/client.c, line 101 at r4](https://reviewable.io/reviews/pmem/rpma/802#-MSRl8sl2aYq9MSSxgW_:-MSRmx6KDEM9Rs6KOom8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7f131a1a182187f50a4e5feacd2f7be4181c3a61/examples/01-connection/client.c#L101)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please use `rpma_utils_conn_event_2str()`.
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/802)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @janekmi)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/802)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[examples/01-connection/client.c, line 76 at r5](https://reviewable.io/reviews/pmem/rpma/802#-MSRwljP8-HAm8zcicBv:-MSRwljP8-HAm8zcicBw:b-anusrq) ([raw file](https://github.com/pmem/rpma/blob/3eb7cd6310268841c20606a62976165f4d0abd14/examples/01-connection/client.c#L76)):*
> ```C
> 		ret = rpma_conn_req_new(peer, addr, port, NULL, &req);
> 		if (ret) {
> 			conn_drop_and_delete(&conn);
> ```

No `conn` at this point. I think just a `break` is enough.
___
*[examples/01-connection/client.c, line 82 at r5](https://reviewable.io/reviews/pmem/rpma/802#-MSRwupw23aqVfPPPU7l:-MSRwupx6v1Pb_msmZMU:b-5iysor) ([raw file](https://github.com/pmem/rpma/blob/3eb7cd6310268841c20606a62976165f4d0abd14/examples/01-connection/client.c#L82)):*
> ```C
> 		ret = rpma_conn_req_connect(&req, &pdata, &conn);
> 		if (ret) {
> 			conn_drop_and_delete(&conn);
> ```

No `conn` at this point.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/802)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[examples/01-connection/client.c, line 76 at r5](https://reviewable.io/reviews/pmem/rpma/802#-MSRwljP8-HAm8zcicBv:-MSRyfJ85426Nd0r1nTe:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3eb7cd6310268841c20606a62976165f4d0abd14/examples/01-connection/client.c#L76)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

No `conn` at this point. I think just a `break` is enough.
</blockquote></details>

Done.
___
*[examples/01-connection/client.c, line 82 at r5](https://reviewable.io/reviews/pmem/rpma/802#-MSRwupw23aqVfPPPU7l:-MSRyeITDm13jZXiZfGK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3eb7cd6310268841c20606a62976165f4d0abd14/examples/01-connection/client.c#L82)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

No `conn` at this point.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/802)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/802#-:-MSS7S3d2Np2_aG44xE3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
