### PR TITLE
common: threads awareness added to log

### PR DESCRIPTION
**Pull request by grom72**
To add threads awareness to log implementation

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/485)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/485)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72)

___
*[src/log.c, line 84 at r1](https://reviewable.io/reviews/pmem/rpma/485#-MIPSxGN0lOg0Y4JX6aB:-MIPSxGN0lOg0Y4JX6aC:baeknbf) ([raw file](https://github.com/pmem/rpma/blob/cff9de847261a155454ae993afffe70558f0f81b/src/log.c#L84)):*
> ```C
> 		log_function_new = rpma_log_default_function;
> 	else
> 		log_function_new = log_function;
> ```

```c
if (log_function == RPMA_LOG_USE_DEFAULT_FUNCTION)
    log_function = rpma_log_default_function;
```

No additional variable required.
___
*[src/log.c, line 92 at r1](https://reviewable.io/reviews/pmem/rpma/485#-MIPTHITEQZmKZYDURM0:-MIPTHITEQZmKZYDURM1:b-fmd9s9) ([raw file](https://github.com/pmem/rpma/blob/cff9de847261a155454ae993afffe70558f0f81b/src/log.c#L92)):*
> ```C
> 		return 0;
> 	else
> 		return Rpma_log_function == log_function_new ? 0 :
> ```

You assume it is possible that compare & swap will fail but the result will be as intended?
___
*[src/log.c, line 118 at r1](https://reviewable.io/reviews/pmem/rpma/485#-MIPTZu9Es93HcuUSw56:-MIPTZu9Es93HcuUSw57:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/cff9de847261a155454ae993afffe70558f0f81b/src/log.c#L118)):*
> ```C
> 		return 0;
> 	else
> 		return Rpma_log_threshold[threshold] == level ? 0 :
> ```

.
___
*[src/include/librpma.h, line 1968 at r1](https://reviewable.io/reviews/pmem/rpma/485#-MIPUDgY82JtGT61ktmr:-MIPUDgY82JtGT61ktms:b-zhpjx7) ([raw file](https://github.com/pmem/rpma/blob/cff9de847261a155454ae993afffe70558f0f81b/src/include/librpma.h#L1968)):*
> ```objc
>  * RPMA_LOG_THRESHOLD_AUX
>  * - RPMA_E_INVAL - level is not a value defined by enum rpma_log_level type
>  * - RPMA_E_UNKNOWN - level is not set due to multi-threading issue
> ```

Either unknown or known. I think we have no basis to assume it is because of multithreading.
Maybe solve it this way:
- RPMA_E_UNKNOWN - unknown error occurred

I am still working on MT related sections. So please stay tuned.
___
*[src/include/librpma.h, line 2062 at r1](https://reviewable.io/reviews/pmem/rpma/485#-MIPUx0Y9MIV_a6nCgAL:-MIPUx0Y9MIV_a6nCgAM:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/cff9de847261a155454ae993afffe70558f0f81b/src/include/librpma.h#L2062)):*
> ```objc
>  *
>  * ERRORS
>  * - RPMA_E_UNKNOWN - function is not set due to multi-threading issue
> ```

.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/485)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[src/log.c, line 92 at r1](https://reviewable.io/reviews/pmem/rpma/485#-MIPTHITEQZmKZYDURM0:-MIPX4F1-BGOqxj0QMTs:b-k9id4a) ([raw file](https://github.com/pmem/rpma/blob/cff9de847261a155454ae993afffe70558f0f81b/src/log.c#L92)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You assume it is possible that compare & swap will fail but the result will be as intended?
</blockquote></details>

Yes if we have two threads trying to do the same thing in parallel.
___
*[src/log.c, line 118 at r1](https://reviewable.io/reviews/pmem/rpma/485#-MIPTZu9Es93HcuUSw56:-MIPXBRp1wr0JErLAcK0:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/cff9de847261a155454ae993afffe70558f0f81b/src/log.c#L118)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/485)* status: 2 of 4 files reviewed, 5 unresolved discussions (waiting on @janekmi)

___
*[src/log.c, line 84 at r1](https://reviewable.io/reviews/pmem/rpma/485#-MIPSxGN0lOg0Y4JX6aB:-MIP_u_ZAmnCRTCtmQk1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cff9de847261a155454ae993afffe70558f0f81b/src/log.c#L84)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
if (log_function == RPMA_LOG_USE_DEFAULT_FUNCTION)
    log_function = rpma_log_default_function;
```

No additional variable required.
</blockquote></details>

Done.
___
*[src/log.c, line 92 at r1](https://reviewable.io/reviews/pmem/rpma/485#-MIPTHITEQZmKZYDURM0:-MIP_osS236o0SAXClh_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cff9de847261a155454ae993afffe70558f0f81b/src/log.c#L92)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Yes if we have two threads trying to do the same thing in parallel.
</blockquote></details>

Done.
___
*[src/log.c, line 118 at r1](https://reviewable.io/reviews/pmem/rpma/485#-MIPTZu9Es93HcuUSw56:-MIP_pWK0t44s78s1pcI:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cff9de847261a155454ae993afffe70558f0f81b/src/log.c#L118)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1968 at r1](https://reviewable.io/reviews/pmem/rpma/485#-MIPUDgY82JtGT61ktmr:-MIP_l2i5LCZIUfJVhtj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cff9de847261a155454ae993afffe70558f0f81b/src/include/librpma.h#L1968)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Either unknown or known. I think we have no basis to assume it is because of multithreading.
Maybe solve it this way:
- RPMA_E_UNKNOWN - unknown error occurred

I am still working on MT related sections. So please stay tuned.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2062 at r1](https://reviewable.io/reviews/pmem/rpma/485#-MIPUx0Y9MIV_a6nCgAL:-MIP_lldAEy3v2Lq9CH4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cff9de847261a155454ae993afffe70558f0f81b/src/include/librpma.h#L2062)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/485)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[src/log.c, line 92 at r1](https://reviewable.io/reviews/pmem/rpma/485#-MIPTHITEQZmKZYDURM0:-MIPaCLE1alGPTZ3cASE:bthrtb2) ([raw file](https://github.com/pmem/rpma/blob/cff9de847261a155454ae993afffe70558f0f81b/src/log.c#L92)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

In my opinion, it is still the wrong use of the library. Please give me a better reason. ;-)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/485)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[src/log.c, line 92 at r1](https://reviewable.io/reviews/pmem/rpma/485#-MIPTHITEQZmKZYDURM0:-MIPiS1V3ZbEY6kbYBQk:b-896fjx) ([raw file](https://github.com/pmem/rpma/blob/cff9de847261a155454ae993afffe70558f0f81b/src/log.c#L92)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

In my opinion, it is still the wrong use of the library. Please give me a better reason. ;-)
</blockquote></details>

Done

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/485#-:-MIPnP7jEvoWOgq1B5i1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/485)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/485#-MISYbnu6E75mhyqnOiN:-MISYbnu6E75mhyqnOiO:b-l67y4a) (no related file):*
Coverage decreased. 2 misses introduced.

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/485)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/485#-MISYbnu6E75mhyqnOiN:-MISZ0pJ0ObIGZDHSgkq:b-i7y823) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Coverage decreased. 2 misses introduced.
</blockquote></details>

log.c: 89 & 114

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/485)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/485#-MISYbnu6E75mhyqnOiN:-MISZ9Pq-w4JmYfGvAmZ:b-9py5rd) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

log.c: 89 & 114
</blockquote></details>

https://codecov.io/gh/pmem/rpma/pull/485/src/src/log.c?before=src/log.c

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/485)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[src/log.c, line 89 at r3](https://reviewable.io/reviews/pmem/rpma/485#-MIS_46YB6L8mmqFUEby:-MIS_46YB6L8mmqFUEbz:bc8a84x) ([raw file](https://github.com/pmem/rpma/blob/ed40344ed11ce5b7ad5fcc020b2faaad1ee2b967/src/log.c#L89)):*
> ```
> RPMA_E_UNKNOWN;
> ```

RPMA_E_AGAIN ?
___
*[src/log.c, line 114 at r3](https://reviewable.io/reviews/pmem/rpma/485#-MIS_7dK6bb5fQbgtJT-:-MIS_7dK6bb5fQbgtJT0:bc8a84x) ([raw file](https://github.com/pmem/rpma/blob/ed40344ed11ce5b7ad5fcc020b2faaad1ee2b967/src/log.c#L114)):*
> ```
> RPMA_E_UNKNOWN;
> ```

RPMA_E_AGAIN ?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/485)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/485#-MISYbnu6E75mhyqnOiN:-MIS_E4M87RirC_HvBRk:bnp58m6) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

https://codecov.io/gh/pmem/rpma/pull/485/src/src/log.c?before=src/log.c
</blockquote></details>

Ahh, that is the race case, that is OK ...

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/485)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[src/log.c, line 89 at r3](https://reviewable.io/reviews/pmem/rpma/485#-MIS_46YB6L8mmqFUEby:-MIScK2a52ouVhcb1q3e:bcna1uj) ([raw file](https://github.com/pmem/rpma/blob/ed40344ed11ce5b7ad5fcc020b2faaad1ee2b967/src/log.c#L89)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> RPMA_E_UNKNOWN;
> ```

RPMA_E_AGAIN ?
</blockquote></details>

It is not an unknown error. We exactly know what happened. The `RPMA_E_AGAIN` is the best in such case.

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/485)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/log.c, line 89 at r3](https://reviewable.io/reviews/pmem/rpma/485#-MIS_46YB6L8mmqFUEby:-MISsrzV-sOr4U6Dj6ha:bu3hzb6) ([raw file](https://github.com/pmem/rpma/blob/ed40344ed11ce5b7ad5fcc020b2faaad1ee2b967/src/log.c#L89)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It is not an unknown error. We exactly know what happened. The `RPMA_E_AGAIN` is the best in such case.
</blockquote></details>

I like this idea.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/485)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[src/log.c, line 89 at r3](https://reviewable.io/reviews/pmem/rpma/485#-MIS_46YB6L8mmqFUEby:-MISwGc20cDg5aZtczo5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ed40344ed11ce5b7ad5fcc020b2faaad1ee2b967/src/log.c#L89)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I like this idea.
</blockquote></details>

Done.
___
*[src/log.c, line 114 at r3](https://reviewable.io/reviews/pmem/rpma/485#-MIS_7dK6bb5fQbgtJT-:-MISwHjG71xJ2rNXlf1f:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ed40344ed11ce5b7ad5fcc020b2faaad1ee2b967/src/log.c#L114)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> RPMA_E_UNKNOWN;
> ```

RPMA_E_AGAIN ?
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r2, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/485)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/485)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/485)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/include/librpma.h, line 1970 at r5](https://reviewable.io/reviews/pmem/rpma/485#-MISzzXO5NHA29JIU1Sq:-MISzzXO5NHA29JIU1Sr:bkk6aj8) ([raw file](https://github.com/pmem/rpma/blob/557c8d7eb84a4aadb6248ff853ab77786cf17f64/src/include/librpma.h#L1970)):*
> ```objc
>  * RPMA_LOG_THRESHOLD_AUX
>  * - RPMA_E_INVAL - level is not a value defined by enum rpma_log_level type
>  * - RPMA_E_AGAIN - temporary error occurred - retry may fix the problem
> ```

the retry
___
*[src/include/librpma.h, line 2064 at r5](https://reviewable.io/reviews/pmem/rpma/485#-MIT-0mFEV7RTxQNBbgu:-MIT-0mFEV7RTxQNBbgv:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/557c8d7eb84a4aadb6248ff853ab77786cf17f64/src/include/librpma.h#L2064)):*
> ```objc
>  *
>  * ERRORS
>  * - RPMA_E_AGAIN - temporary error occurred - retry may fix the problem
> ```

.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/485)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 1970 at r5](https://reviewable.io/reviews/pmem/rpma/485#-MISzzXO5NHA29JIU1Sq:-MIT0MByDLMzQ_SUZoou:beclrlj) ([raw file](https://github.com/pmem/rpma/blob/557c8d7eb84a4aadb6248ff853ab77786cf17f64/src/include/librpma.h#L1970)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

the retry
</blockquote></details>

`a temporary error occurred, the retry may fix the problem`
___
*[src/include/librpma.h, line 2064 at r5](https://reviewable.io/reviews/pmem/rpma/485#-MIT-0mFEV7RTxQNBbgu:-MIT0SVr0I8zWycQ0-cO:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/557c8d7eb84a4aadb6248ff853ab77786cf17f64/src/include/librpma.h#L2064)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/485)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[src/include/librpma.h, line 1970 at r5](https://reviewable.io/reviews/pmem/rpma/485#-MISzzXO5NHA29JIU1Sq:-MIT44eH-Etb3g9EBVB7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/557c8d7eb84a4aadb6248ff853ab77786cf17f64/src/include/librpma.h#L1970)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`a temporary error occurred, the retry may fix the problem`
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2064 at r5](https://reviewable.io/reviews/pmem/rpma/485#-MIT-0mFEV7RTxQNBbgu:-MIT45EC-suVeBcFHUm4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/557c8d7eb84a4aadb6248ff853ab77786cf17f64/src/include/librpma.h#L2064)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/485)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/485#-:-MIT4Cvk6n5rlz4U8hjp:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/485)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/485)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/485)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/485#-MIT8c_J0LhpuIRzXf1A:-MIT8c_K1IvVX4bg98nk:bbrspgn) (no related file):*
Please wait a moment with merging this. I want to do one test.

---

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/485)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/pmem/rpma/485#-MIT8c_J0LhpuIRzXf1A:-MITCM2R2-wYFSW58qwr:b3tnj2y) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please wait a moment with merging this. I want to do one test.
</blockquote></details>

Tests passed :lgtm_strong: 

---

**Pull request merged**
