### PR TITLE
tools: fix test expressions in ddio.sh

### PR DESCRIPTION
**Pull request by ldorau**
'-eq' and '-ne' should be used only for integers, not for strings.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/773)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/773)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/773#-MRyQDAc2Ls3DemwiOUG:-MRyQDAc2Ls3DemwiOUH:b1kwm3k) (no related file):*
Are you sure?

Ref: https://tldp.org/LDP/abs/html/comparison-ops.html

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/773)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/773#-MRyQDAc2Ls3DemwiOUG:-MRySNqB-HJo5yt-xJhY:be142rg) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Are you sure?

Ref: https://tldp.org/LDP/abs/html/comparison-ops.html
</blockquote></details>

What is this link? See the test(1) manual.

---

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/773#-:-MRzBmjO-ssjhD2xpY28:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/773#-:-MRzKN8f6FRSaDERuekV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
