### PR TITLE
common: 1.1.1-rc1 release

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/2083)

### CODE REVIEW

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2083#-:-NHOKYOX0UGA_vt96mm2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2083)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2083)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`CHANGELOG.md` line 10 at r3](https://reviewable.io/reviews/pmem/rpma/2083#-NLL5RTv42Z7-_sXD9Dx:-NLL5RTv42Z7-_sXD9Dy:undefined) ([raw file](https://github.com/pmem/rpma/blob/58de8654e5adccc456544a7514b734ecb09cebf4/CHANGELOG.md#L10)):*
> ```Markdown
> ## [Unreleased]
> 
> ## [1.1.1-rc1] - 2022-11-18
> ```





_Suggestion:_
```Markdown
2023-01-09
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2083)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`CHANGELOG.md` line 10 at r3](https://reviewable.io/reviews/pmem/rpma/2083#-NLL5RTv42Z7-_sXD9Dx:-NLL5o0Q12hHzcHFRZ3I:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/58de8654e5adccc456544a7514b734ecb09cebf4/CHANGELOG.md#L10)):*
> ```Markdown
> ## [Unreleased]
> 
> ## [1.1.1-rc1] - 2022-11-18
> ```

Done.

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2083#-:-NLL6clF7KSNiJNSDZ45:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
