### PR TITLE
tools: fix three pylint errors

### PR DESCRIPTION
**Pull request by ldorau**
Fix three pylint errors in one line:

See: https://github.com/pmem/rpma/runs/4375161325

```
************* Module lib.figure.image
/rpma/tools/perf/lib/figure/image.py:56:27: C0326: Exactly one space required around keyword argument assignment
             yaxis_max: int=None, suptitle: str=None, title: str=None) -> None:
                           ^ (bad-whitespace)
/rpma/tools/perf/lib/figure/image.py:56:47: C0326: Exactly one space required around keyword argument assignment
             yaxis_max: int=None, suptitle: str=None, title: str=None) -> None:
                                               ^ (bad-whitespace)
/rpma/tools/perf/lib/figure/image.py:56:64: C0326: Exactly one space required around keyword argument assignment
             yaxis_max: int=None, suptitle: str=None, title: str=None) -> None:
                                                                ^ (bad-whitespace)

```

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1376)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
And from build of this PR:
```
************* Module lib.figure.image
C: 56, 0: No space allowed around keyword argument assignment
             output_path: str, yaxis_max: int = None,
                                              ^ (bad-whitespace)
C: 57, 0: No space allowed around keyword argument assignment
             suptitle: str = None, title: str = None) -> None:
                           ^ (bad-whitespace)
C: 57, 0: No space allowed around keyword argument assignment
             suptitle: str = None, title: str = None) -> None:
                                              ^ (bad-whitespace)
```
:-D

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1376#-:-Mpp5tv_19y6RAfqyp2S:b-xqss9w)* status: 0 of 1 files reviewed, all discussions resolved

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1376#-:-MpuHI-YBdUnt3KHBF9W:bg7igkv)* status: 0 of 1 files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
All builds pass now:
https://github.com/ldorau/rpma/actions/runs/1530444464
https://github.com/ldorau/rpma/actions/runs/1530475535

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1376#-:-Mpv51Ps2LVgUdze006s:by2a5pf)* status: 0 of 5 files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1376#-:-Mpv5nfeAS1Wdk7uuKxi:bnfp4nl)* status: 2 of 5 files reviewed, all discussions resolved (waiting on @grom72)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1376#-:-Mpv6Zvs-41uqR-6ERyQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
