### PR TITLE
tools: ib_read short runtime

### PR DESCRIPTION
**Pull request by grom72**
Enable short runtime (10 iterations) for ib_read runner

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1453)

### CODE REVIEW

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1453#-:-Ms-OIETB-neiVimNQdz:bg7igkv)* status: 0 of 1 files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1453)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1453)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1453)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1453)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 146 at r1](https://reviewable.io/reviews/pmem/rpma/1453#-Ms4ygrk1TWpO8AnuW9Z:-Ms4ygrk1TWpO8AnuW9_:bd2daul) ([raw file](https://github.com/pmem/rpma/blob/484fcfa58d7fc03cfc8b8cc56e2b069abd7efc68/tools/perf/lib/benchmark/runner/ib_read.py#L146)):*
> ```Python
>         numa_n = str(self.__config['JOB_NUMA'])
>         short_runtime = self.__config.get('SHORT_RUNTIME', False)
>         if short_runtime:
> ```

```
        if self.__config.get('SHORT_RUNTIME', False):
```



_Code quote:_
```Python
        short_runtime = self.__config.get('SHORT_RUNTIME', False)
        if short_runtime:
```
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 147 at r1](https://reviewable.io/reviews/pmem/rpma/1453#-Ms4yact4rChJOc0WW6c:-Ms4yacu8nOgP36CKJ0S:b-hfjwc2) ([raw file](https://github.com/pmem/rpma/blob/484fcfa58d7fc03cfc8b8cc56e2b069abd7efc68/tools/perf/lib/benchmark/runner/ib_read.py#L147)):*
> ```Python
>         short_runtime = self.__config.get('SHORT_RUNTIME', False)
>         if short_runtime:
>             it_opt = '--iters= 5'
> ```

`'--iters=5'` (no space before `5`)



_Code quote:_
```Python
'--iters= 5'
```
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 147 at r1](https://reviewable.io/reviews/pmem/rpma/1453#-Ms4z2o58E2Ae-PreGUU:-Ms4z2o58E2Ae-PreGUV:b-v7cqtr) ([raw file](https://github.com/pmem/rpma/blob/484fcfa58d7fc03cfc8b8cc56e2b069abd7efc68/tools/perf/lib/benchmark/runner/ib_read.py#L147)):*
> ```Python
>         short_runtime = self.__config.get('SHORT_RUNTIME', False)
>         if short_runtime:
>             it_opt = '--iters= 5'
> ```

Why 5? Maybe 10 or 100? - such numbers look better ;-)



_Code quote:_
```Python
 '--iters= 5'
```

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1453)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 146 at r1](https://reviewable.io/reviews/pmem/rpma/1453#-Ms4ygrk1TWpO8AnuW9Z:-Ms54yeH8m1TroJ6aYQf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/484fcfa58d7fc03cfc8b8cc56e2b069abd7efc68/tools/perf/lib/benchmark/runner/ib_read.py#L146)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
        if self.__config.get('SHORT_RUNTIME', False):
```
</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 147 at r1](https://reviewable.io/reviews/pmem/rpma/1453#-Ms4yact4rChJOc0WW6c:-Ms54y23AGt3C0tDhdbb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/484fcfa58d7fc03cfc8b8cc56e2b069abd7efc68/tools/perf/lib/benchmark/runner/ib_read.py#L147)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`'--iters=5'` (no space before `5`)
</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 147 at r1](https://reviewable.io/reviews/pmem/rpma/1453#-Ms4z2o58E2Ae-PreGUU:-Ms54zOH6GDS2N7EdegO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/484fcfa58d7fc03cfc8b8cc56e2b069abd7efc68/tools/perf/lib/benchmark/runner/ib_read.py#L147)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why 5? Maybe 10 or 100? - such numbers look better ;-)
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1453)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1453)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1453#-:-Ms56jh_ETlAFAqfKeVP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
