### PR TITLE
tools: add support for ib_read_bw to csv2standardized.py

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/631)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/631)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[tools/csv2standardized.py, line 27 at r1](https://reviewable.io/reviews/pmem/rpma/631#-MO12zmQCE6Q_7yeon4B:-MO12zmR2c-KdBLGGByW:bi11lzv) ([raw file](https://github.com/pmem/rpma/blob/f5163429f75e0b63e01491d760061d98e2fb4369/tools/csv2standardized.py#L27)):*
> ```Python
> # - lat_pctl_99.999 - 99.999th percentile latency [usec] (optional)
> #
> # - bw_peak - peak of bandwidth [Gb/sec]
> ```

bw_peak is not part of the output CSV format. No need to put it here then.
___
*[tools/csv2standardized.py, line 59 at r1](https://reviewable.io/reviews/pmem/rpma/631#-MO13PKp6iOZgWAgdGZ8:-MO13PKp6iOZgWAgdGZ9:b-csyiy5) ([raw file](https://github.com/pmem/rpma/blob/f5163429f75e0b63e01491d760061d98e2fb4369/tools/csv2standardized.py#L59)):*
> ```Python
> 
> ib_bw_output_names = [
>     'bs', 'bw_avg', 'msg_rate']
> ```

We tend to keep ops in the output.
___
*[tools/ib_read.sh, line 159 at r1](https://reviewable.io/reviews/pmem/rpma/631#-MO145GtAuz1oEB9nEnZ:-MO145GuALudyGmpVMds:b7m5tqa) ([raw file](https://github.com/pmem/rpma/blob/f5163429f75e0b63e01491d760061d98e2fb4369/tools/ib_read.sh#L159)):*
> ```Shell
> done
> 
> CSV_MODE=$(echo ${IB_TOOL} | sed 's/_read//g')
> ```

It seems `g` is too broad. We can go along without it.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/631)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tools/csv2standardized.py, line 27 at r1](https://reviewable.io/reviews/pmem/rpma/631#-MO12zmQCE6Q_7yeon4B:-MO14z2wAmXOdhEFJWLJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f5163429f75e0b63e01491d760061d98e2fb4369/tools/csv2standardized.py#L27)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

bw_peak is not part of the output CSV format. No need to put it here then.
</blockquote></details>

Done.
___
*[tools/csv2standardized.py, line 59 at r1](https://reviewable.io/reviews/pmem/rpma/631#-MO13PKp6iOZgWAgdGZ8:-MO14zZs3yCmnBtMw0ty:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f5163429f75e0b63e01491d760061d98e2fb4369/tools/csv2standardized.py#L59)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

We tend to keep ops in the output.
</blockquote></details>

Done.
___
*[tools/ib_read.sh, line 159 at r1](https://reviewable.io/reviews/pmem/rpma/631#-MO145GtAuz1oEB9nEnZ:-MO15CjO9OoGP7xlmscY:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f5163429f75e0b63e01491d760061d98e2fb4369/tools/ib_read.sh#L159)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It seems `g` is too broad. We can go along without it.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/631)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/631#-:-MO15bAM-4ab2mFcVgTh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
