### PR TITLE
doc: improve the documentation to rpma...completion functions

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/431)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/431)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[src/include/librpma.h, line 1220 at r1](https://reviewable.io/reviews/pmem/rpma/431#-MHzyX2H-ff9zj0EwUl5:-MHzyX2H-ff9zj0EwUl6:bdlh17x) ([raw file](https://github.com/pmem/rpma/blob/96029610a2067429c0a1c47ff0ee21a9fa1f4935/src/include/librpma.h#L1220)):*
> ```objc
>  *
>  * DESCRIPTION
>  * Gets a completion file descriptor of the connection.
> ```

`rpma_conn_get_completion_fd() gets ...`
___
*[src/include/librpma.h, line 1261 at r1](https://reviewable.io/reviews/pmem/rpma/431#-MHzyfxR6sEAhUvoCKqb:-MHzyfxS5Vq435NsUYOv:big4to3) ([raw file](https://github.com/pmem/rpma/blob/96029610a2067429c0a1c47ff0ee21a9fa1f4935/src/include/librpma.h#L1261)):*
> ```
> succeeded
> ```

succeeds
___
*[src/include/librpma.h, line 1289 at r1](https://reviewable.io/reviews/pmem/rpma/431#-MHzyk5N-7Fy_cxYbqXx:-MHzyk5N-7Fy_cxYbqXy:b-nech12) ([raw file](https://github.com/pmem/rpma/blob/96029610a2067429c0a1c47ff0ee21a9fa1f4935/src/include/librpma.h#L1289)):*
> ```objc
>  *
>  * DESCRIPTION
>  * Receive the next available completion of an already posted operation. All
> ```

`rpma_conn_next_completion() receives ...`

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/431)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[src/include/librpma.h, line 1220 at r1](https://reviewable.io/reviews/pmem/rpma/431#-MHzyX2H-ff9zj0EwUl5:-MI-KqAd4UupcYoVFzm8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/96029610a2067429c0a1c47ff0ee21a9fa1f4935/src/include/librpma.h#L1220)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`rpma_conn_get_completion_fd() gets ...`
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1261 at r1](https://reviewable.io/reviews/pmem/rpma/431#-MHzyfxR6sEAhUvoCKqb:-MI-KxPS3ZHc9jsjjf4i:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/96029610a2067429c0a1c47ff0ee21a9fa1f4935/src/include/librpma.h#L1261)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> succeeded
> ```

succeeds
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1289 at r1](https://reviewable.io/reviews/pmem/rpma/431#-MHzyk5N-7Fy_cxYbqXx:-MI-L1Pd326Ce1nfg89V:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/96029610a2067429c0a1c47ff0ee21a9fa1f4935/src/include/librpma.h#L1289)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`rpma_conn_next_completion() receives ...`
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/431)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[src/include/librpma.h, line 1220 at r1](https://reviewable.io/reviews/pmem/rpma/431#-MHzyX2H-ff9zj0EwUl5:-MI-MKVyDSareFVs5wW9:bm4agcd) ([raw file](https://github.com/pmem/rpma/blob/96029610a2067429c0a1c47ff0ee21a9fa1f4935/src/include/librpma.h#L1220)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`gets the ...` (sorry)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/431)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
@grom72 please review

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/431#-:-MI386Kl9Osz0Zndr-cA:bgjoyzx)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/431#-:-MI3XgOm5oJlxR_d-hjK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/431#-:-MI4KjSC3JIuA2R5UpFS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/431)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/431)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
