### PR TITLE
rpma: finish the documentation for rpma_atomic_write()

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1598)

### CODE REVIEW

**Review by haichangsi — COMMENTED** [review]
:goat: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1598#-:-Mx1SkP9Drvx3p_dUniz:bdycpsm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1598#-:-Mx3O0LE2K3deW49_7Vq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1598)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[src/include/librpma.h, line 2506 at r1](https://reviewable.io/reviews/pmem/rpma/1598#-Mx3PIbY5meckAKQqp9K:-Mx3PIbY5meckAKQqp9L:bdni78n) ([raw file](https://github.com/pmem/rpma/blob/a576b58f340720700315853d8c54e2570ea5c903/src/include/librpma.h#L2506)):*
> ```objc
>  * rpma_atomic_write() initiates the atomic 8 bytes write operation
>  * (transferring data from the local memory to the remote memory).
>  * The atomic write operation allows transferring only 8 bytes of data
> ```

exactly



_Code quote:_
```objc
only
```
___
*[src/include/librpma.h, line 2507 at r1](https://reviewable.io/reviews/pmem/rpma/1598#-Mx3P4BTEDOZKIV4CZ55:-Mx3P4BTEDOZKIV4CZ56:bj4cals) ([raw file](https://github.com/pmem/rpma/blob/a576b58f340720700315853d8c54e2570ea5c903/src/include/librpma.h#L2507)):*
> ```objc
>  * (transferring data from the local memory to the remote memory).
>  * The atomic write operation allows transferring only 8 bytes of data
>  * and storing them atomically in the remote memory.
> ```

what do you mean ``` automatically ``` in this context?



_Code quote:_
```objc
atomically
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1598)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)

___
*[src/include/librpma.h, line 2506 at r1](https://reviewable.io/reviews/pmem/rpma/1598#-Mx3PIbY5meckAKQqp9K:-Mx3WagI-fAhaHwaZYY0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a576b58f340720700315853d8c54e2570ea5c903/src/include/librpma.h#L2506)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

exactly
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2507 at r1](https://reviewable.io/reviews/pmem/rpma/1598#-Mx3P4BTEDOZKIV4CZ55:-Mx3VYky5Z4gRAtpLqx8:bkf5ya8) ([raw file](https://github.com/pmem/rpma/blob/a576b58f340720700315853d8c54e2570ea5c903/src/include/librpma.h#L2507)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

what do you mean ``` automatically ``` in this context?
</blockquote></details>

:-D read it again, please :-D

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1598)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1598#-:-Mx3ZmZF7oKPhYv1GDHi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
