### PR TITLE
test: add the missing test case

### PR DESCRIPTION
**Pull request by osalyk**
Ref: #349

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/367)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/367#-:-MGcWENcEFIJx9dT8Rq2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/367)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tests/unit/mr/mr-reg.c, line 45 at r1](https://reviewable.io/reviews/pmem/rpma/367#-MGeZNi577YTAVzWq2uO:-MGeZNi67bOXOVD88a_v:b46i05m) ([raw file](https://github.com/pmem/rpma/blob/09f9f47b306df14d0367afc4b4d76f416c55b24c/tests/unit/mr/mr-reg.c#L45)):*
> ```C
> 	/* values used in reg_dereg__success called with (prestates + 7) */
> 	{RPMA_MR_USAGE_RECV, IBV_ACCESS_LOCAL_WRITE, NULL},
> 	/* values used in reg_dereg__success called with (prestates + 8) */
> ```

I think we also need a case such as:

```c
{RPMA_MR_USAGE_SEND, 0, NULL}
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/367)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tests/unit/mr/mr-reg.c, line 45 at r1](https://reviewable.io/reviews/pmem/rpma/367#-MGeZNi577YTAVzWq2uO:-MGg4l7E8avgY4nCMDuP:b-akik8m) ([raw file](https://github.com/pmem/rpma/blob/09f9f47b306df14d0367afc4b4d76f416c55b24c/tests/unit/mr/mr-reg.c#L45)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we also need a case such as:

```c
{RPMA_MR_USAGE_SEND, 0, NULL}
```
</blockquote></details>

@janekmi  - Shall we have also 
``
{RPMA_MR_USAGE_RECV |  RPMA_MR_USAGE_FLUSHABLE,  IBV_ACCESS_LOCAL_WRITE | IBV_ACCESS_REMOTE_READ, NULL} 
``
for read after send method?

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/367)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72, @janekmi, and @ldorau)

___
*[tests/unit/mr/mr-reg.c, line 45 at r1](https://reviewable.io/reviews/pmem/rpma/367#-MGeZNi577YTAVzWq2uO:-MGgGSqL2Vek7MBOZVFg:b-auzdf2) ([raw file](https://github.com/pmem/rpma/blob/09f9f47b306df14d0367afc4b4d76f416c55b24c/tests/unit/mr/mr-reg.c#L45)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

@janekmi  - Shall we have also 
``
{RPMA_MR_USAGE_RECV |  RPMA_MR_USAGE_FLUSHABLE,  IBV_ACCESS_LOCAL_WRITE | IBV_ACCESS_REMOTE_READ, NULL} 
``
for read after send method?
</blockquote></details>

Add: {RPMA_MR_USAGE_SEND, 0, NULL}

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/367)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/367#-:-MGh810SA2yap-a7KQsZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
