### PR TITLE
tools: add checks to Benchmark.run()

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1132)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1132)* status: all files reviewed, 5 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/lib/Benchmark.py, line 98 at r2](https://reviewable.io/reviews/pmem/rpma/1132#-MdvRtmm3lyBjPFmsgzB:-MdvRtmm3lyBjPFmsgzC:bm0asnd) ([raw file](https://github.com/pmem/rpma/blob/13fa6a9830067f704d9e955615cc427fb4e6ee2e/tools/perf/lib/Benchmark.py#L98)):*
> ```Python
> 
>     def _benchmark_args(self, env):
>         if not 'tool' in self.oneseries or not 'mode' in self.oneseries:
> ```

I like more the natural order `'tool' not in self.oneseries`.
___
*[tools/perf/lib/Benchmark.py, line 100 at r2](https://reviewable.io/reviews/pmem/rpma/1132#-MdvSKAHEUjlZGdJeNV8:-MdvSKAHEUjlZGdJeNV9:b-so9r6o) ([raw file](https://github.com/pmem/rpma/blob/13fa6a9830067f704d9e955615cc427fb4e6ee2e/tools/perf/lib/Benchmark.py#L100)):*
> ```Python
>         if not 'tool' in self.oneseries or not 'mode' in self.oneseries:
>             raise ValueError
>         args = ['./' + self.oneseries['tool'], env['server_ip']]
> ```

What if `env['server_ip']` is missing? :-)
I will add a test.
___
*[tools/perf/lib/Benchmark.py, line 112 at r2](https://reviewable.io/reviews/pmem/rpma/1132#-MdvS8a0EfWer6_AYpWx:-MdvS8a0EfWer6_AYpWy:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/13fa6a9830067f704d9e955615cc427fb4e6ee2e/tools/perf/lib/Benchmark.py#L112)):*
> ```Python
>         env = self._get_env(config, result_dir)
> 
>         if not 'filetype' in self.oneseries or not 'id' in self.oneseries:
> ```

.
___
*[tools/perf/lib/Benchmark.py, line 116 at r2](https://reviewable.io/reviews/pmem/rpma/1132#-MdvSoMk4BfMlgBnYK2h:-MdvSoMk4BfMlgBnYK2i:b-rvszx9) ([raw file](https://github.com/pmem/rpma/blob/13fa6a9830067f704d9e955615cc427fb4e6ee2e/tools/perf/lib/Benchmark.py#L116)):*
> ```Python
> 
>         if self.oneseries['filetype'] == 'malloc':
>             env['REMOTE_JOB_MEM_PATH'] = 'malloc'
> ```

```python
elif self.oneseries['filetype'] == 'pmem':
    if 'REMOTE_JOB_MEM_PATH' not in env or env['REMOTE_JOB_MEM_PATH'] == 'malloc'):
        raise ValueError
```
___
*[tools/perf/lib/Benchmark.py, line 126 at r2](https://reviewable.io/reviews/pmem/rpma/1132#-MdvTB8xDl0x4tkoCXgT:-MdvTB8xDl0x4tkoCXgU:b-5n5qd5) ([raw file](https://github.com/pmem/rpma/blob/13fa6a9830067f704d9e955615cc427fb4e6ee2e/tools/perf/lib/Benchmark.py#L126)):*
> ```Python
>                 env['BUSY_WAIT_POLLING'] = '1'
>             else:
>                 env['BUSY_WAIT_POLLING'] = '0'
> ```

I do not have any idea what to do when `busy_wait_polling` is missing from `self.oneseries`.
Maybe it should be required? Any thoughts?

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1132)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/lib/Benchmark.py, line 126 at r2](https://reviewable.io/reviews/pmem/rpma/1132#-MdvTB8xDl0x4tkoCXgT:-MdvXIpjBTQhEBkCPooD:b-wqs3n2) ([raw file](https://github.com/pmem/rpma/blob/13fa6a9830067f704d9e955615cc427fb4e6ee2e/tools/perf/lib/Benchmark.py#L126)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I do not have any idea what to do when `busy_wait_polling` is missing from `self.oneseries`.
Maybe it should be required? Any thoughts?
</blockquote></details>

Only for GPSPM, in APM it can be default value

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1132)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[tools/perf/lib/Benchmark.py, line 126 at r2](https://reviewable.io/reviews/pmem/rpma/1132#-MdvTB8xDl0x4tkoCXgT:-MdvYTU13sPNjx_sXdkV:bje7rgg) ([raw file](https://github.com/pmem/rpma/blob/13fa6a9830067f704d9e955615cc427fb4e6ee2e/tools/perf/lib/Benchmark.py#L126)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Only for GPSPM, in APM it can be default value
</blockquote></details>

Even undetermined TBH. ;-)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1132)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tools/perf/lib/Benchmark.py, line 98 at r2](https://reviewable.io/reviews/pmem/rpma/1132#-MdvRtmm3lyBjPFmsgzB:-MdvVBn_DO1Ib4f-0OxI:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/13fa6a9830067f704d9e955615cc427fb4e6ee2e/tools/perf/lib/Benchmark.py#L98)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I like more the natural order `'tool' not in self.oneseries`.
</blockquote></details>

Done.
___
*[tools/perf/lib/Benchmark.py, line 100 at r2](https://reviewable.io/reviews/pmem/rpma/1132#-MdvSKAHEUjlZGdJeNV8:-MdvYaKJDOB9Lhgtrz4y:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/13fa6a9830067f704d9e955615cc427fb4e6ee2e/tools/perf/lib/Benchmark.py#L100)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

What if `env['server_ip']` is missing? :-)
I will add a test.
</blockquote></details>

Done.
___
*[tools/perf/lib/Benchmark.py, line 112 at r2](https://reviewable.io/reviews/pmem/rpma/1132#-MdvS8a0EfWer6_AYpWx:-MdvXN_SBXF0qz1lqC5Q:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/13fa6a9830067f704d9e955615cc427fb4e6ee2e/tools/perf/lib/Benchmark.py#L112)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/lib/Benchmark.py, line 116 at r2](https://reviewable.io/reviews/pmem/rpma/1132#-MdvSoMk4BfMlgBnYK2h:-MdvXlKrC2J3wZMf_WTe:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/13fa6a9830067f704d9e955615cc427fb4e6ee2e/tools/perf/lib/Benchmark.py#L116)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```python
elif self.oneseries['filetype'] == 'pmem':
    if 'REMOTE_JOB_MEM_PATH' not in env or env['REMOTE_JOB_MEM_PATH'] == 'malloc'):
        raise ValueError
```

</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1132)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[tools/perf/lib/Benchmark.py, line 100 at r2](https://reviewable.io/reviews/pmem/rpma/1132#-MdvSKAHEUjlZGdJeNV8:-Mdv_7Dw7pQZxm5jrwfh:b-8pau78) ([raw file](https://github.com/pmem/rpma/blob/13fa6a9830067f704d9e955615cc427fb4e6ee2e/tools/perf/lib/Benchmark.py#L100)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

'env'

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1132)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/lib/Benchmark.py, line 100 at r2](https://reviewable.io/reviews/pmem/rpma/1132#-MdvSKAHEUjlZGdJeNV8:-Mdv_j5-Ah1C6iTjpEi-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/13fa6a9830067f704d9e955615cc427fb4e6ee2e/tools/perf/lib/Benchmark.py#L100)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

'env'
</blockquote></details>

Done.
___
*[tools/perf/lib/Benchmark.py, line 126 at r2](https://reviewable.io/reviews/pmem/rpma/1132#-MdvTB8xDl0x4tkoCXgT:-Mdv_Wy956WPnoUwFhvB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/13fa6a9830067f704d9e955615cc427fb4e6ee2e/tools/perf/lib/Benchmark.py#L126)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Even undetermined TBH. ;-)
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1132#-:-MdvcI806obeHHvzGocc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1132#-:-Mdvl8vd1CN5htuWSm_B:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
