### PR TITLE
 tools: perf: Benchmark args and env implementation

### PR DESCRIPTION
**Pull request by janekmi**
Requires:

- [x] #1065

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1073)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1073)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/Benchmark.py, line 80 at r1](https://reviewable.io/reviews/pmem/rpma/1073#-Mb5xgtL55myeSfi_xDL:-Mb5xgtL55myeSfi_xDM:b89bbc2) ([raw file](https://github.com/pmem/rpma/blob/b25cd7114daf1c7fb51fe94f764f4fef1dbf3891/tools/perf/lib/Benchmark.py#L80)):*
> ```
> ····
> ```

Four spaces starting the line ?

**Review by ldorau — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1073#-:-Mb5yRY33F7cS_3KSOXT:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1073)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/lib/Benchmark.py, line 80 at r1](https://reviewable.io/reviews/pmem/rpma/1073#-Mb5xgtL55myeSfi_xDL:-Mb6GFlD6lbVs41-iYJ_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b25cd7114daf1c7fb51fe94f764f4fef1dbf3891/tools/perf/lib/Benchmark.py#L80)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> ····
> ```

Four spaces starting the line ?
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1073#-:-Mb6Rtrr0MqpP-stxnHa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1073#-:-Mb6g9q_2HUGhVWuwdqS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1073)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
