### PR TITLE
test: add rpma_log_[get/set]_threshold unit tests

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/280)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/280)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[tests/unit/log/threshold.c, line 25 at r1](https://reviewable.io/reviews/pmem/rpma/280#-MF9v7-HBt8fwRDOPm_A:-MF9v7-I-2IrmIG8voBX:b-l05fjx) ([raw file](https://github.com/pmem/rpma/blob/c2733a2451eb4a318cd78f406ba6cdaf44273a26/tests/unit/log/threshold.c#L25)):*
> ```C
> {
> 	int ret = rpma_log_set_threshold(INVALID_THRESHOLD_MOCK,
> 	RPMA_LOG_DISABLED);
> ```

incorrect alignment
___
*[tests/unit/log/threshold.c, line 37 at r1](https://reviewable.io/reviews/pmem/rpma/280#-MF9vC2l8Mz8bZqoCbsA:-MF9vC2l8Mz8bZqoCbsB:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/c2733a2451eb4a318cd78f406ba6cdaf44273a26/tests/unit/log/threshold.c#L37)):*
> ```C
> {
> 	int ret = rpma_log_set_threshold(RPMA_LOG_THRESHOLD,
> 	INVALID_LEVEL_MOCK);
> ```

.
___
*[tests/unit/log/threshold.c, line 49 at r1](https://reviewable.io/reviews/pmem/rpma/280#-MF9vD-J97GqyCaqzOSt:-MF9vD-J97GqyCaqzOSu:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/c2733a2451eb4a318cd78f406ba6cdaf44273a26/tests/unit/log/threshold.c#L49)):*
> ```C
> {
> 	int ret = rpma_log_set_threshold(INVALID_THRESHOLD_MOCK,
> 	INVALID_LEVEL_MOCK);
> ```

.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/280)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @osalyk)

___
*[tests/unit/log/threshold.c, line 75 at r1](https://reviewable.io/reviews/pmem/rpma/280#-MF9vzNv-kDw5gSMZiCg:-MF9vzNv-kDw5gSMZiCh:b-c35atc) ([raw file](https://github.com/pmem/rpma/blob/c2733a2451eb4a318cd78f406ba6cdaf44273a26/tests/unit/log/threshold.c#L75)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> rpma_log_level *level = malloc(sizeof(rpma_log_level));
> 	int ret = rpma_log_get_threshold(INVALID_THRESHOLD_MOCK, level);
> 	assert_int_equal(ret, RPMA_E_INVAL);
> 	free(level);
> ```
</details>


No `malloc()` please:

```
{
	rpma_log_level level;
	int ret = rpma_log_get_threshold(INVALID_THRESHOLD_MOCK, &level);

	assert_int_equal(ret, RPMA_E_INVAL);
}
```
___
*[tests/unit/log/threshold.c, line 110 at r1](https://reviewable.io/reviews/pmem/rpma/280#-MF9wAmVBcM70ItA62PD:-MF9wAmVBcM70ItA62PE:bdj0m5q) ([raw file](https://github.com/pmem/rpma/blob/c2733a2451eb4a318cd78f406ba6cdaf44273a26/tests/unit/log/threshold.c#L110)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> rpma_log_level *level = malloc(sizeof(rpma_log_level));
> 	int ret = rpma_log_get_threshold(RPMA_LOG_THRESHOLD, level);
> 	assert_int_equal(ret, 0);
> 	free(level);
> ```
</details>


.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/280)* status: all files reviewed, 5 unresolved discussions (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/280)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @ldorau)

___
*[tests/unit/log/threshold.c, line 25 at r1](https://reviewable.io/reviews/pmem/rpma/280#-MF9v7-HBt8fwRDOPm_A:-MF9wlg_6lNLAdY1kRoK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c2733a2451eb4a318cd78f406ba6cdaf44273a26/tests/unit/log/threshold.c#L25)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

incorrect alignment
</blockquote></details>

Done.
___
*[tests/unit/log/threshold.c, line 37 at r1](https://reviewable.io/reviews/pmem/rpma/280#-MF9vC2l8Mz8bZqoCbsA:-MF9woTFDDK4yDeFZ4oQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c2733a2451eb4a318cd78f406ba6cdaf44273a26/tests/unit/log/threshold.c#L37)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/log/threshold.c, line 49 at r1](https://reviewable.io/reviews/pmem/rpma/280#-MF9vD-J97GqyCaqzOSt:-MF9wqfA1MUItS5UBkJ9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c2733a2451eb4a318cd78f406ba6cdaf44273a26/tests/unit/log/threshold.c#L49)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/log/threshold.c, line 75 at r1](https://reviewable.io/reviews/pmem/rpma/280#-MF9vzNv-kDw5gSMZiCg:-MF9xBpN835wG25f2hqX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c2733a2451eb4a318cd78f406ba6cdaf44273a26/tests/unit/log/threshold.c#L75)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> rpma_log_level *level = malloc(sizeof(rpma_log_level));
> 	int ret = rpma_log_get_threshold(INVALID_THRESHOLD_MOCK, level);
> 	assert_int_equal(ret, RPMA_E_INVAL);
> 	free(level);
> ```

No `malloc()` please:

```
{
	rpma_log_level level;
	int ret = rpma_log_get_threshold(INVALID_THRESHOLD_MOCK, &level);

	assert_int_equal(ret, RPMA_E_INVAL);
}
```
</blockquote></details>

Done.
___
*[tests/unit/log/threshold.c, line 110 at r1](https://reviewable.io/reviews/pmem/rpma/280#-MF9wAmVBcM70ItA62PD:-MF9xRJ00Ns2wrJ67OLX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c2733a2451eb4a318cd78f406ba6cdaf44273a26/tests/unit/log/threshold.c#L110)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> rpma_log_level *level = malloc(sizeof(rpma_log_level));
> 	int ret = rpma_log_get_threshold(RPMA_LOG_THRESHOLD, level);
> 	assert_int_equal(ret, 0);
> 	free(level);
> ```

.
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/280#-:-MFA203JEtLx7pM61x6b:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/280)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[tests/unit/log/threshold.c, line 60 at r2](https://reviewable.io/reviews/pmem/rpma/280#-MFA5q809OuAYLEX0pf4:-MFA5q809OuAYLEX0pf5:b-3srj8o) ([raw file](https://github.com/pmem/rpma/blob/dea5a6135f8abda9f8e5416784ccc9828aec23d1/tests/unit/log/threshold.c#L60)):*
> ```C
> set_threshold__success(void **unused)
> {
> 	int ret = rpma_log_set_threshold(RPMA_LOG_THRESHOLD, RPMA_LOG_DISABLED);
> ```

I think we can do in a loop here tests for both RPMA_LOG_THRESHOLD and RPMA_LOG_THRESHOLD_AUX.
___
*[tests/unit/log/threshold.c, line 66 at r2](https://reviewable.io/reviews/pmem/rpma/280#-MFA5xox1D8IzZVv8RG0:-MFA5xox1D8IzZVv8RG1:bb7og4i) ([raw file](https://github.com/pmem/rpma/blob/dea5a6135f8abda9f8e5416784ccc9828aec23d1/tests/unit/log/threshold.c#L66)):*
> ```C
> 
> /*
>  * get_threshold__threshold_invalid -- set invalid threshold
> ```

set?
___
*[tests/unit/log/threshold.c, line 109 at r2](https://reviewable.io/reviews/pmem/rpma/280#-MFA67gZ7B3w7RU4V7oW:-MFA67gZ7B3w7RU4V7oX:b-3dtx3r) ([raw file](https://github.com/pmem/rpma/blob/dea5a6135f8abda9f8e5416784ccc9828aec23d1/tests/unit/log/threshold.c#L109)):*
> ```C
> 
> 	assert_int_equal(ret, 0);
> }
> ```

This test case should be merged with set_threshold__success. Let's call the merged unit test e.g. threshold__lifecycle. Where you have to:
1. loop over THRESHOLD and AUX
2. set different threshold levels
3. get threshold level and verify its correctness

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/280)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tests/unit/log/threshold.c, line 60 at r2](https://reviewable.io/reviews/pmem/rpma/280#-MFA5q809OuAYLEX0pf4:-MFAIbxHB2SRAI5G3oiQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dea5a6135f8abda9f8e5416784ccc9828aec23d1/tests/unit/log/threshold.c#L60)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we can do in a loop here tests for both RPMA_LOG_THRESHOLD and RPMA_LOG_THRESHOLD_AUX.
</blockquote></details>

Done.
___
*[tests/unit/log/threshold.c, line 66 at r2](https://reviewable.io/reviews/pmem/rpma/280#-MFA5xox1D8IzZVv8RG0:-MFA785u-jSwhPFp4G-V:b-sarplc) ([raw file](https://github.com/pmem/rpma/blob/dea5a6135f8abda9f8e5416784ccc9828aec23d1/tests/unit/log/threshold.c#L66)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

set?
</blockquote></details>

setting the wrong value
___
*[tests/unit/log/threshold.c, line 109 at r2](https://reviewable.io/reviews/pmem/rpma/280#-MFA67gZ7B3w7RU4V7oW:-MFAIari9Ozd3ZarwqFC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dea5a6135f8abda9f8e5416784ccc9828aec23d1/tests/unit/log/threshold.c#L109)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This test case should be merged with set_threshold__success. Let's call the merged unit test e.g. threshold__lifecycle. Where you have to:
1. loop over THRESHOLD and AUX
2. set different threshold levels
3. get threshold level and verify its correctness
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/280)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tests/unit/log/threshold.c, line 66 at r2](https://reviewable.io/reviews/pmem/rpma/280#-MFA5xox1D8IzZVv8RG0:-MFAJDNN3On7bz4Z2cfI:b-vex8zq) ([raw file](https://github.com/pmem/rpma/blob/dea5a6135f8abda9f8e5416784ccc9828aec23d1/tests/unit/log/threshold.c#L66)):*
To avoid misunderstandings I prefer using here `using` instead of `set`. My proposition is:
> get_threshold__threshold_invalid -- use an invalid threshold

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/280)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tests/unit/log/threshold.c, line 66 at r2](https://reviewable.io/reviews/pmem/rpma/280#-MFA5xox1D8IzZVv8RG0:-MFAL2WgAvV7vnKfbkA5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dea5a6135f8abda9f8e5416784ccc9828aec23d1/tests/unit/log/threshold.c#L66)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

To avoid misunderstandings I prefer using here `using` instead of `set`. My proposition is:
> get_threshold__threshold_invalid -- use an invalid threshold
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/280#-:-MFALt5C1MdcQCiU89yP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
