### PR TITLE
common: update PATH to make sure src2man is found

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/356)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/356)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[utils/src2mans.sh, line 56 at r1](https://reviewable.io/reviews/pmem/rpma/356#-MGO5yxzEhp720gsHZtI:-MGO5yxzEhp720gsHZtJ:bt1jour) ([raw file](https://github.com/pmem/rpma/blob/8b72286436c35a9065b78a5b414b04f865e33fce/utils/src2mans.sh#L56)):*
> ```Shell
> #
> export "PATH=$PATH:/usr/local/bin"
> ```

shall we add CMake parameter to provide this folder if everything will fail?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/356)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[utils/src2mans.sh, line 56 at r1](https://reviewable.io/reviews/pmem/rpma/356#-MGO5yxzEhp720gsHZtI:-MGO6oZNBKGPZGYDGSdG:bi7hhwq) ([raw file](https://github.com/pmem/rpma/blob/8b72286436c35a9065b78a5b414b04f865e33fce/utils/src2mans.sh#L56)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

shall we add CMake parameter to provide this folder if everything will fail?
</blockquote></details>

I do not understand ... What is 'everything'? Why can it fail?

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/356#-:-MGOx9fl6M9ySKvu3hsg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/356#-:-MGbSBsn73gHxx8qW0gf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/356)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[utils/src2mans.sh, line 51 at r1](https://reviewable.io/reviews/pmem/rpma/356#-MGnY8HM9lie0IIj-XCD:-MGnY8HM9lie0IIj-XCE:bk20wi7) ([raw file](https://github.com/pmem/rpma/blob/8b72286436c35a9065b78a5b414b04f865e33fce/utils/src2mans.sh#L51)):*
> ```Shell
> 
> #
> # src2man is usually located in '/usr/local/bin'.
> ```

Do you mean when src2man is installed from sources without proper configuration?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/356)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[utils/src2mans.sh, line 51 at r1](https://reviewable.io/reviews/pmem/rpma/356#-MGnY8HM9lie0IIj-XCD:-MGoArPxCdhkbUc872c4:b-do16dr) ([raw file](https://github.com/pmem/rpma/blob/8b72286436c35a9065b78a5b414b04f865e33fce/utils/src2mans.sh#L51)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Do you mean when src2man is installed from sources without proper configuration?
</blockquote></details>

Right :-) This PR was replaced with https://github.com/pmem/rpma/pull/383

**Comment by ldorau** [comment]
This PR was replaced with #383

**Pull request closed without merging**
