### PR TITLE
common: update the official library name

### PR DESCRIPTION
**Pull request by grom72**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/711)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/711)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[README.md, line 1 at r1](https://reviewable.io/reviews/pmem/rpma/711#-MPnnHsl-3ejHWWEtsnj:-MPnnHsm-BkF0R9HHWoG:b-tyo3lg) ([raw file](https://github.com/pmem/rpma/blob/c2cbdfd473b2a6f63674af06b22b627a32229ee5/README.md#L1)):*
I think I would go with something like here: https://github.com/pmem/vmemcache

> librpma: Remote Persistent Memory Access Library

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/711)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[README.md, line 1 at r1](https://reviewable.io/reviews/pmem/rpma/711#-MPnnHsl-3ejHWWEtsnj:-MPnoJApDOH_d1qU-9lY:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c2cbdfd473b2a6f63674af06b22b627a32229ee5/README.md#L1)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think I would go with something like here: https://github.com/pmem/vmemcache

> librpma: Remote Persistent Memory Access Library
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/711#-:-MQCWxok33Xsx4YCs145:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
@grom72 please rebase

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/711#-:-MQChuSG9SzsmXPtwdpg:bgjc1nd)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/711#-:-MQH8NEG4hyz6jpIsB8P:bb6un1j)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/711)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/711#-:-MQIA3sw4JVzMxNBgcCM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
