### PR TITLE
test: improve rpma_peer_cfg_set... MT test

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1919)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
:goat: 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1919#-:-N6P_g94CH6SdzDkfZ6n:bdycpsm)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1919#-N6P_ceb6DxXkkxDHHZ7:-N6P_ceb6DxXkkxDHHZ8:b-cxwhhy) (no related file):*
Changelog.md ??

___
___
*[`tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c` line 16 at r1](https://reviewable.io/reviews/pmem/rpma/1919#-N6P_qof74qIsD-XtO5Y:-N6P_qof74qIsD-XtO5Z:b-yzto7u) ([raw file](https://github.com/pmem/rpma/blob/4d46b5274676ffb27b4308e067ed42ffb1f5695e/tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c#L16)):*
> ```C
> #define DIRECT_WRITE_TO_PMEM	true
> 
> struct rpma_peer_cfg_prestate {
> ```

Can we use just ``prestate`` name for prestate structure?



_Suggestion:_
```C
prestate
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1919)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1919#-N6P_ceb6DxXkkxDHHZ7:-N6RIAaU8F9KyVmvlmAF:bk4fh6x) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Changelog.md ??
</blockquote></details>

CHANGELOG.md was updated in PR #1915 


___
___
*[`tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c` line 16 at r1](https://reviewable.io/reviews/pmem/rpma/1919#-N6P_qof74qIsD-XtO5Y:-N6RHTEs6HwIXDb9PKHi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4d46b5274676ffb27b4308e067ed42ffb1f5695e/tests/multithreaded/peer/rpma_peer_cfg_set_direct_write_to_pmem.c#L16)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Can we use just ``prestate`` name for prestate structure?
</blockquote></details>

Done.

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1919#-:-N6RelS5El02MzVhLKOk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1919)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
