### PR TITLE
tools: complete report_bench.sh scenarios

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/786)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/786)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tools/report_bench.sh, line 44 at r1](https://reviewable.io/reviews/pmem/rpma/786#-MS38i984MZtAbSwk5zb:-MS38i984MZtAbSwk5zc:b-ue0jgt) ([raw file](https://github.com/pmem/rpma/blob/7d64fd8154d9a4e21a9e03753448b90798beb22d/tools/report_bench.sh#L44)):*
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>

> ```
> # The subshell and -x is used as cheap logging
> (set -x; \
> 	for mode in lat bw-bs bw-th; do \
> 		./ib_read.sh $SERVER_IP $mode && \
> 		for op in read randread; do \
> 			REMOTE_JOB_MEM_PATH=$DRAM ./rpma_fio_bench.sh $SERVER_IP apm $op $mode && \
> 			REMOTE_JOB_MEM_PATH=$PMEM ./rpma_fio_bench.sh $SERVER_IP apm $op $mode; \
> 		done \
> 	done
> )
> ```
</details>


Actually, why do you use a subshell here? Why not in the following way? IMHO it is simpler:

```
# -x is used as a cheap logging
set -x
for mode in lat bw-bs bw-th; do
	./ib_read.sh $SERVER_IP $mode
	for op in read randread; do
		REMOTE_JOB_MEM_PATH=$DRAM ./rpma_fio_bench.sh $SERVER_IP apm $op $mode
		REMOTE_JOB_MEM_PATH=$PMEM ./rpma_fio_bench.sh $SERVER_IP apm $op $mode
	done
done
set +x
```
___
*[tools/report_bench.sh, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/786#-MS39TAB0qWIFF2ZISmV:-MS39TAB0qWIFF2ZISmW:bxzrlao) ([raw file](https://github.com/pmem/rpma/blob/7d64fd8154d9a4e21a9e03753448b90798beb22d/tools/report_bench.sh#L48)):*
> ```
> # The subshell and -x is used as cheap logging
> (set -x; \
> ```

.
___
*[tools/report_bench.sh, line 63 at r1](https://reviewable.io/reviews/pmem/rpma/786#-MS39V0o44OEMTcf8tQG:-MS39V0o44OEMTcf8tQH:bnfjih5) ([raw file](https://github.com/pmem/rpma/blob/7d64fd8154d9a4e21a9e03753448b90798beb22d/tools/report_bench.sh#L63)):*
> ```
> # The subshell and -x is used as cheap logging
> # To be compared with "PMEM apm read/randread" and "PMEM apm write/randwrite"
> (set -x; \
> ```

.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/786)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/786)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[tools/report_bench.sh, line 44 at r1](https://reviewable.io/reviews/pmem/rpma/786#-MS38i984MZtAbSwk5zb:-MS3I5s96I84eCg3tX91:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7d64fd8154d9a4e21a9e03753448b90798beb22d/tools/report_bench.sh#L44)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> # The subshell and -x is used as cheap logging
> (set -x; \
> 	for mode in lat bw-bs bw-th; do \
> 		./ib_read.sh $SERVER_IP $mode && \
> 		for op in read randread; do \
> 			REMOTE_JOB_MEM_PATH=$DRAM ./rpma_fio_bench.sh $SERVER_IP apm $op $mode && \
> 			REMOTE_JOB_MEM_PATH=$PMEM ./rpma_fio_bench.sh $SERVER_IP apm $op $mode; \
> 		done \
> 	done
> )
> ```

Actually, why do you use a subshell here? Why not in the following way? IMHO it is simpler:

```
# -x is used as a cheap logging
set -x
for mode in lat bw-bs bw-th; do
	./ib_read.sh $SERVER_IP $mode
	for op in read randread; do
		REMOTE_JOB_MEM_PATH=$DRAM ./rpma_fio_bench.sh $SERVER_IP apm $op $mode
		REMOTE_JOB_MEM_PATH=$PMEM ./rpma_fio_bench.sh $SERVER_IP apm $op $mode
	done
done
set +x
```
</blockquote></details>

Done.
___
*[tools/report_bench.sh, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/786#-MS39TAB0qWIFF2ZISmV:-MS3I6WQ88p95f87LO4a:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7d64fd8154d9a4e21a9e03753448b90798beb22d/tools/report_bench.sh#L48)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> # The subshell and -x is used as cheap logging
> (set -x; \
> ```

.
</blockquote></details>

Done.
___
*[tools/report_bench.sh, line 63 at r1](https://reviewable.io/reviews/pmem/rpma/786#-MS39V0o44OEMTcf8tQG:-MS3IJxk-QmaBpnel5Nz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7d64fd8154d9a4e21a9e03753448b90798beb22d/tools/report_bench.sh#L63)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> # The subshell and -x is used as cheap logging
> # To be compared with "PMEM apm read/randread" and "PMEM apm write/randwrite"
> (set -x; \
> ```

.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/786)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/786#-:-MS3IYZJ4OuwjBA3ZUw8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
