### PR TITLE
test: update suppressions of libibverbs and librdmacm

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #1858 
- [x] #1860

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1862)

### CODE REVIEW

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1862)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1862)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @haichangsi and @ldorau)

___
*[`tests/helgrind.supp` line 326 at r6](https://reviewable.io/reviews/pmem/rpma/1862#-N5dn_4b1gGr7BThhHP9:-N5dn_4b1gGr7BThhHPA:buzcpm9) ([raw file](https://github.com/pmem/rpma/blob/052cefbc26e0b795fb5c2630b9618999c81591d5/tests/helgrind.supp#L326)):*
> ```
> # OS: ubuntu-2204:2022.04.1 of CircleCI
> # libibverbs: 1.39.0.1
> # librdmacm: 1.39.0.1
> ```

Looking at the new suppresions below I probably added wrong versions in my last PR. I found it on CircleCi:
...
Preparing to unpack .../35-libibverbs1_39.0-1_amd64.deb ...



_Code quote:_
```
# libibverbs: 1.39.0.1
# librdmacm: 1.39.0.1
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1862)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[`tests/helgrind.supp` line 326 at r6](https://reviewable.io/reviews/pmem/rpma/1862#-N5dn_4b1gGr7BThhHP9:-N5dt6aG5M2pc1GjDfPP:b48yr74) ([raw file](https://github.com/pmem/rpma/blob/052cefbc26e0b795fb5c2630b9618999c81591d5/tests/helgrind.supp#L326)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Looking at the new suppresions below I probably added wrong versions in my last PR. I found it on CircleCi:
...
Preparing to unpack .../35-libibverbs1_39.0-1_amd64.deb ...
</blockquote></details>

So please submit a PR with a fix to your suppressions.

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1862#-:-N5eBTGh9gCs2Ali8R7T:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1862#-:-N5ePv6n971Z7ZKpr85o:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
