### PR TITLE
examples: add support for PMem to run-all-examples.sh

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1820)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1820)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`examples/run-all-examples.sh` line 11 at r1](https://reviewable.io/reviews/pmem/rpma/1820#-N47doAeBr5d9FEZ74QN:-N47qVrE0QJIUK7ZIU-B:b-wm39sl) ([raw file](https://github.com/pmem/rpma/blob/ba54a788e5584381d86f547fe918abb6ac3de007/examples/run-all-examples.sh#L11)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Would it be better to have this as the last parameter of the script?
It is a completely invisible option for ordinary script users.
</blockquote></details>

`[IP_address] [port]` are often omitted, so it would be difficult to distinguish this arguments, unless we use `getopt` ...

**Review by grom72 — APPROVED** [review]
Are you going to update the documentation in a separate PR?

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1820#-:-N47rImI7wEd_wGEdcS3:b-pq46xx)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
Yes

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1820#-:-N47uDI80m3xpBgkVYnQ:b2nhswy)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1820#-:-N47wnRk5B4voEC_J2ci:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
The documentation is updated in https://github.com/pmem/rpma/pull/1822

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1820#-:-N49Lw804WuJm7TS_Etf:be8evse)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1820#-:-N4BDPVx80Sr_vhmIqcT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
