### PR TITLE
common: print out the 'common' area in nothing else was printed

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/406)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/406)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[utils/check-area.sh, line 52 at r1](https://reviewable.io/reviews/pmem/rpma/406#-MHNwA08BF6UE5ybf3RX:-MHNwA08BF6UE5ybf3RY:b4z0mye) ([raw file](https://github.com/pmem/rpma/blob/c9d7fc62dd80f9d86fe81c3192b740670f2b17cd/utils/check-area.sh#L52)):*
> ```Shell
> 			-e "Makefile\$"
> 
> # print out the 'common' area in nothing else was printed
> ```

in -> if

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/406)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[utils/check-area.sh, line 52 at r1](https://reviewable.io/reviews/pmem/rpma/406#-MHNwA08BF6UE5ybf3RX:-MHPeKwA4oh1WNkKmspk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c9d7fc62dd80f9d86fe81c3192b740670f2b17cd/utils/check-area.sh#L52)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

in -> if
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/406#-:-MHR289I4Ko09U5i_3fr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/406#-:-MHV827t9KyVM6m_XPFs:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
@grom72 please review

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/406#-:-MHkIuaD2aWetomqgqLq:bgjoyzx)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/406#-:-MI-EbE16gdH8IqS964a:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
