### PR TITLE
examples: standardize the code style in example files

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/2015)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 22 of 22 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2015)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/pmem/rpma/2015#-NBC_QPnC5NS3HHE-SEn):*
Squash those two commits, please



_Code quote:_
```
- 1478ecb: examples: standardize the code style in example files

- 6c258ba: common: update CHANGELOG.md
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2015)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ldorau)

___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/pmem/rpma/2015#-NBC_QPnC5NS3HHE-SEn):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Squash those two commits, please
</blockquote></details>

Done.

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2015)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2015#-NBCsGzmADQJORLMPxGh:-NBCsGzmADQJORLMPxGi:bbpv7ln) (no related file):*
Please check with following condition: ``.if \(\([a-z]* =`` there are still few ``if ((*=`` occurrences

___

**Review by grom72 — COMMENTED** [review]
> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2015)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2015)* status: 20 of 22 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2015#-NBCsGzmADQJORLMPxGh:-NBGpSLp9c-ZnUijbMw1:b-896fix) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Please check with following condition: ``.if \(\([a-z]* =`` there are still few ``if ((*=`` occurrences
</blockquote></details>

Done.

___

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2015)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2015)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2015#-:-NBHkS45AQeLKd2pJj6V:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2015)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2015)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
