### PR TITLE
examples: clarify setting and using mr_size in example 07

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/2047)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2047)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`examples/07-atomic-write/client.c` line 55 at r1](https://reviewable.io/reviews/pmem/rpma/2047#-NFD7eiwE4F4-dOFfcSK:-NFD7eiwE4F4-dOFfcSL:b-mbw3s8) ([raw file](https://github.com/pmem/rpma/blob/69bb3a7446ea0a9f726e81cbd700b8267d5b5f16/examples/07-atomic-write/client.c#L55)):*
> ```C
> 
> 	/* prepare memory */
> 	mr_size = KILOBYTE;
> ```

Why not ``size_t mr_size = KILOBYTE;`` above?



_Code quote:_
```C
mr_size = KILOBYTE;
```

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2047)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`examples/07-atomic-write/client.c` line 43 at r1](https://reviewable.io/reviews/pmem/rpma/2047#-NFDKiEiEqNnTav6k6BA:-NFDKiEiEqNnTav6k6BB:undefined) ([raw file](https://github.com/pmem/rpma/blob/69bb3a7446ea0a9f726e81cbd700b8267d5b5f16/examples/07-atomic-write/client.c#L43)):*
> ```C
> 	/* resources - memory region */
> 	void *mr_ptr = NULL;
> 	size_t mr_size;
> ```





_Suggestion:_
```C
size_t mr_size = 0;
```

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2047)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`examples/07-atomic-write/client.c` line 42 at r1](https://reviewable.io/reviews/pmem/rpma/2047#-NFDO4zD90CSZfdJi_TC:-NFDO4zD90CSZfdJi_TD:undefined) ([raw file](https://github.com/pmem/rpma/blob/69bb3a7446ea0a9f726e81cbd700b8267d5b5f16/examples/07-atomic-write/client.c#L42)):*
> ```C
> 
> 	/* resources - memory region */
> 	void *mr_ptr = NULL;
> ```





_Suggestion:_
```C
void *mr_ptr;
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2047)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`examples/07-atomic-write/client.c` line 42 at r1](https://reviewable.io/reviews/pmem/rpma/2047#-NFDO4zD90CSZfdJi_TC:-NFDRzQE5yXAz2dOm7CM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/69bb3a7446ea0a9f726e81cbd700b8267d5b5f16/examples/07-atomic-write/client.c#L42)):*
> ```C
> 
> 	/* resources - memory region */
> 	void *mr_ptr = NULL;
> ```

Done.

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2047)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2047#-:-NFDhlD2DbBYR_2p7PLA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
