### PR TITLE
tools: verify the path of fio

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1127)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1127)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/rpma_fio_bench.sh, line 58 at r1](https://reviewable.io/reviews/pmem/rpma/1127#-MdrQRrW6xmEhRlBkuS1:-MdrQRrX6TZ4rbqFnmBD:bnrbxik) ([raw file](https://github.com/pmem/rpma/blob/179f0d8cebd5c69bf61dc335c33ac795e5419535/tools/perf/rpma_fio_bench.sh#L58)):*
> ```Shell
> 		echo "Error: wrong path to the 'fio' tool - \"${FIO_PATH}/fio\" does not exist"
> 		exit 1
> 	fi
> ```

Going down this path we should also verify the REMOTE_FIO_PATH, won't you think?

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1127)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/rpma_fio_bench.sh, line 55 at r1](https://reviewable.io/reviews/pmem/rpma/1127#-MdrRKkt5OlPh3_hWR14:-MdrRKkt5OlPh3_hWR15:b-lrryky) ([raw file](https://github.com/pmem/rpma/blob/179f0d8cebd5c69bf61dc335c33ac795e5419535/tools/perf/rpma_fio_bench.sh#L55)):*
> ```Shell
> function benchmark_one() {
> 
> 	if [ ! -f ${FIO_PATH}/fio ]; then
> ```

What if fio is available from the PATH so FIO_PATH is not provided? I have heard some of you install FIO in the system. ;-)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1127)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/rpma_fio_bench.sh, line 55 at r1](https://reviewable.io/reviews/pmem/rpma/1127#-MdrRKkt5OlPh3_hWR14:-Mdu_9vM2Am5Gr9xzJw8:b-vxtkhy) ([raw file](https://github.com/pmem/rpma/blob/179f0d8cebd5c69bf61dc335c33ac795e5419535/tools/perf/rpma_fio_bench.sh#L55)):*
> What if fio is available from the PATH so FIO_PATH is not provided? I have heard some of you install FIO in the system. ;-)

:+1:

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1127)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/rpma_fio_bench.sh, line 55 at r1](https://reviewable.io/reviews/pmem/rpma/1127#-MdrRKkt5OlPh3_hWR14:-MdubWvGAPadMKZ5kpJ3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/179f0d8cebd5c69bf61dc335c33ac795e5419535/tools/perf/rpma_fio_bench.sh#L55)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

> What if fio is available from the PATH so FIO_PATH is not provided? I have heard some of you install FIO in the system. ;-)

:+1: 
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 58 at r1](https://reviewable.io/reviews/pmem/rpma/1127#-MdrQRrW6xmEhRlBkuS1:-MdubXFr7D8VL3gW4Rid:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/179f0d8cebd5c69bf61dc335c33ac795e5419535/tools/perf/rpma_fio_bench.sh#L58)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Going down this path we should also verify the REMOTE_FIO_PATH, won't you think?
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1127#-:-MdulK0iBBLBVCoHMz9-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1127#-:-Mdul_u713XqK20Tyu2_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
