### PR TITLE
tools: fix continue mode

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1478)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
:goat: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1478#-:-MsdrL391U3PhbBa8DnE:bdycpsm)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @osalyk)

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1478)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1478)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1478#-MseGGR00YN_-GGEApWW):*
is it an improvement or a fix?
Could you elaborate what problem this PR solves?



_Code quote:_
```
- 4aea9a1: tools: improve continue mode
```

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1478)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1478)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @grom72)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1478#-MseGGR00YN_-GGEApWW):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

is it an improvement or a fix?
Could you elaborate what problem this PR solves?
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1478)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[tools/perf/lib/Requirement.py, line 44 at r2](https://reviewable.io/reviews/pmem/rpma/1478#-MserGo2BAANoNkilPVw:-MserGo2BAANoNkilPVx:b-l7sn8l) ([raw file](https://github.com/pmem/rpma/blob/aea98fb5e0877f300b73932b61c518dcc69329bd/tools/perf/lib/Requirement.py#L44)):*
> ```Python
>         else:
>             self.__benchmarks = {id: Benchmark(b)
>                 for id, b in req.get('benchmarks', {}).items()}
> ```

Isn't it the same ?

```python
        else:
            self.__benchmarks = {}
```



_Code quote:_
```Python
        else:
            self.__benchmarks = {id: Benchmark(b)
                for id, b in req.get('benchmarks', {}).items()}
```

**Review by grom72 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1478)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1478)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/lib/Requirement.py, line 44 at r2](https://reviewable.io/reviews/pmem/rpma/1478#-MserGo2BAANoNkilPVw:-Mt1xIsY0F_naPcAN-Fx:b32v57) ([raw file](https://github.com/pmem/rpma/blob/aea98fb5e0877f300b73932b61c518dcc69329bd/tools/perf/lib/Requirement.py#L44)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Isn't it the same ?

```python
        else:
            self.__benchmarks = {}
```

</blockquote></details>

+1

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1478)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/lib/Requirement.py, line 44 at r2](https://reviewable.io/reviews/pmem/rpma/1478#-MserGo2BAANoNkilPVw:-Mt1xrLB91OdJ5sz4ZJh:bh95ke4) ([raw file](https://github.com/pmem/rpma/blob/aea98fb5e0877f300b73932b61c518dcc69329bd/tools/perf/lib/Requirement.py#L44)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

+1
</blockquote></details>

You're right

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1478)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1478)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1478)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/lib/Requirement.py, line 35 at r3](https://reviewable.io/reviews/pmem/rpma/1478#-Mt2X5GV1rvau5Ebfhup:-Mt2X5GV1rvau5Ebfhuq:bbdkzng) ([raw file](https://github.com/pmem/rpma/blob/f280bcc9a9c3a4afd34aa8e194ca72916ab8b2e6/tools/perf/lib/Requirement.py#L35)):*
> ```Python
> 
>     def __init__(self, req: dict):
>         # when we restore the list of requirements,
> ```

# When



_Code quote:_
```Python
# when
```
___
*[tools/perf/lib/Requirement.py, line 37 at r3](https://reviewable.io/reviews/pmem/rpma/1478#-Mt2XBGi1N84olfKEOjn:-Mt2XBGi1N84olfKEOjo:b-g5kujp) ([raw file](https://github.com/pmem/rpma/blob/f280bcc9a9c3a4afd34aa8e194ca72916ab8b2e6/tools/perf/lib/Requirement.py#L37)):*
> ```Python
>         # when we restore the list of requirements,
>         # we need to extract the benchmarks information.
>         # Otherwise, we create a benchmark dictionary
> ```

dictionary



_Code quote:_
```Python
dictionary
```
___
*[tools/perf/lib/Requirement.py, line 37 at r3](https://reviewable.io/reviews/pmem/rpma/1478#-Mt2_B4IBwZWnCriiEN0:-Mt2_B4IBwZWnCriiEN1:b-cz2duw) ([raw file](https://github.com/pmem/rpma/blob/f280bcc9a9c3a4afd34aa8e194ca72916ab8b2e6/tools/perf/lib/Requirement.py#L37)):*
> ```Python
>         # when we restore the list of requirements,
>         # we need to extract the benchmarks information.
>         # Otherwise, we create a benchmark dictionary
> ```

What is "a benchmark dictionary"?



_Code quote:_
```Python
 a benchmark dictionary
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1478)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/lib/Requirement.py, line 35 at r3](https://reviewable.io/reviews/pmem/rpma/1478#-Mt2X5GV1rvau5Ebfhup:-Mt2_QtuAs8EGhrQbVK2:b-50ca4y) ([raw file](https://github.com/pmem/rpma/blob/f280bcc9a9c3a4afd34aa8e194ca72916ab8b2e6/tools/perf/lib/Requirement.py#L35)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

# When
</blockquote></details>

`# When`

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1478)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/lib/Requirement.py, line 35 at r3](https://reviewable.io/reviews/pmem/rpma/1478#-Mt2X5GV1rvau5Ebfhup:-Mt2aHCa9O5UTXeLn_gf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f280bcc9a9c3a4afd34aa8e194ca72916ab8b2e6/tools/perf/lib/Requirement.py#L35)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`# When`
</blockquote></details>

Done.
___
*[tools/perf/lib/Requirement.py, line 37 at r3](https://reviewable.io/reviews/pmem/rpma/1478#-Mt2XBGi1N84olfKEOjn:-Mt2aJaS5lC3-cP0d4X_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f280bcc9a9c3a4afd34aa8e194ca72916ab8b2e6/tools/perf/lib/Requirement.py#L37)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

dictionary. (a dot at the end)
</blockquote></details>

Done.
___
*[tools/perf/lib/Requirement.py, line 37 at r3](https://reviewable.io/reviews/pmem/rpma/1478#-Mt2_B4IBwZWnCriiEN0:-Mt2cUs338exAHf2Y2A5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f280bcc9a9c3a4afd34aa8e194ca72916ab8b2e6/tools/perf/lib/Requirement.py#L37)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

What is "a benchmark dictionary"?
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1478)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1478#-:-Mt3GUfyDjBOAZLEXRDV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
