### PR TITLE
tools: extend file name with meaningful information about workload

### PR DESCRIPTION
**Pull request by grom72**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/691)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/691)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72)

___
*[tools/rpma_fio_bench.sh, line 57 at r1](https://reviewable.io/reviews/pmem/rpma/691#-MPdrZOE92huSZ6H4er8:-MPdrZOE92huSZ6H4er9:b-523918) ([raw file](https://github.com/pmem/rpma/blob/d6a45df959e544a001e5630dd6e83c1f6b9eb184/tools/rpma_fio_bench.sh#L57)):*
> ```Shell
> 		COMMENT=""
> 	else
> 		COMMENT="_$5"
> ```

`__${5}__`

(double underscore on both sides)
___
*[tools/rpma_fio_bench.sh, line 81 at r1](https://reviewable.io/reviews/pmem/rpma/691#-MPdrjKu5fsYCL5glWLS:-MPdrjKu5fsYCL5glWLT:b-45w6sc) ([raw file](https://github.com/pmem/rpma/blob/d6a45df959e544a001e5630dd6e83c1f6b9eb184/tools/rpma_fio_bench.sh#L81)):*
> ```Shell
> 		ITERATIONS=${#BLOCK_SIZE[@]}
> 		DEPTH=2
> 		NAME_SUFFIX=th${THREADS}_dp${DEPTH}
> ```

All of these are in the data inside the file. No point in having it here also.
___
*[tools/rpma_fio_bench.sh, line 88 at r1](https://reviewable.io/reviews/pmem/rpma/691#-MPdrtfnEGZtTiOpzzyg:-MPdrtfnEGZtTiOpzzyh:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/d6a45df959e544a001e5630dd6e83c1f6b9eb184/tools/rpma_fio_bench.sh#L88)):*
> ```Shell
> 		DEPTH=(1 2 4 8 16 32 64 128)
> 		ITERATIONS=${#DEPTH[@]}
> 		NAME_SUFFIX=th${THREADS}_bs${BLOCK_SIZE}
> ```

.
___
*[tools/rpma_fio_bench.sh, line 95 at r1](https://reviewable.io/reviews/pmem/rpma/691#-MPdruDA57o8XFEchjEX:-MPdruDA57o8XFEchjEY:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/d6a45df959e544a001e5630dd6e83c1f6b9eb184/tools/rpma_fio_bench.sh#L95)):*
> ```Shell
> 		DEPTH=(1 2 3 4 5 6 7 8 9 10)
> 		ITERATIONS=${#DEPTH[@]}
> 		NAME_SUFFIX=th${THREADS}_bs${BLOCK_SIZE}
> ```

.
___
*[tools/rpma_fio_bench.sh, line 102 at r1](https://reviewable.io/reviews/pmem/rpma/691#-MPdruigCseJCSTseq3V:-MPdruigCseJCSTseq3W:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/d6a45df959e544a001e5630dd6e83c1f6b9eb184/tools/rpma_fio_bench.sh#L102)):*
> ```Shell
> 		DEPTH=2
> 		ITERATIONS=${#THREADS[@]}
> 		NAME_SUFFIX=bs${BLOCK_SIZE}_dp${DEPTH}
> ```

.
___
*[tools/rpma_fio_bench.sh, line 209 at r1](https://reviewable.io/reviews/pmem/rpma/691#-MPdrzCwCQOZsgmT0g1j:-MPdrzCwCQOZsgmT0g1k:b-s3hmk9) ([raw file](https://github.com/pmem/rpma/blob/d6a45df959e544a001e5630dd6e83c1f6b9eb184/tools/rpma_fio_bench.sh#L209)):*
> ```Shell
> else
> 	COMMENT=""
> fi
> ```

Not needed.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/691)* status: all files reviewed, 8 unresolved discussions (waiting on @grom72)

___
*[tools/rpma_fio_bench.sh, line 58 at r1](https://reviewable.io/reviews/pmem/rpma/691#-MPdrnZiE5mnqvtVU03O:-MPdrnZj7NCuDp6ZMXQh:b-6gvbnz) ([raw file](https://github.com/pmem/rpma/blob/d6a45df959e544a001e5630dd6e83c1f6b9eb184/tools/rpma_fio_bench.sh#L58)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 	if [ "Z$5" == "Z" ]; then
> 		COMMENT=""
> 	else
> 		COMMENT="_$5"
> 	fi
> ```
</details>


```
[ "$5" != "" ] && COMMENT="_$5"
```
___
*[tools/rpma_fio_bench.sh, line 209 at r1](https://reviewable.io/reviews/pmem/rpma/691#-MPdsGq-4RrmfqA6X6VK:-MPdsGq-4RrmfqA6X6VL:b7hhcwt) ([raw file](https://github.com/pmem/rpma/blob/d6a45df959e544a001e5630dd6e83c1f6b9eb184/tools/rpma_fio_bench.sh#L209)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> if [ "$#" -gt 4 ]; then
>         COMMENT=$5
> else
> 	COMMENT=""
> fi
> ```
</details>


not needed

**Review by ldorau — CHANGES_REQUESTED** [review]
Please rebase

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/691#-:-MPds_rf1Yw-0OX3IDcz:b-n6khor)* status: all files reviewed, 9 unresolved discussions (waiting on @grom72)

___
*[tools/rpma_fio_bench.sh, line 116 at r1](https://reviewable.io/reviews/pmem/rpma/691#-MPdsgJO6R5P03qPDmU5:-MPdsgJO6R5P03qPDmU6:b-d6gr2h) ([raw file](https://github.com/pmem/rpma/blob/d6a45df959e544a001e5630dd6e83c1f6b9eb184/tools/rpma_fio_bench.sh#L116)):*
> ```Shell
> 	[ "$DEST" == "malloc" ] && DEST="dram"
> 
> 	NAME=rpma_fio_${OP}_${P_MODE}_${MODE}_${NAME_SUFFIX}_${DEST}${COMMENT}-${TIMESTAMP}
> ```

`P_MODE` before `OP` please

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/691)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/rpma_fio_bench.sh, line 209 at r1](https://reviewable.io/reviews/pmem/rpma/691#-MPdsGq-4RrmfqA6X6VK:-MPe0vi690CfMa0bvGFq:b32v57) ([raw file](https://github.com/pmem/rpma/blob/d6a45df959e544a001e5630dd6e83c1f6b9eb184/tools/rpma_fio_bench.sh#L209)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> if [ "$#" -gt 4 ]; then
>         COMMENT=$5
> else
> 	COMMENT=""
> fi
> ```

not needed
</blockquote></details>

+1

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/691)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[tools/rpma_fio_bench.sh, line 58 at r1](https://reviewable.io/reviews/pmem/rpma/691#-MPdrnZiE5mnqvtVU03O:-MPe2B_p8X85m7GYgjRu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d6a45df959e544a001e5630dd6e83c1f6b9eb184/tools/rpma_fio_bench.sh#L58)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 	if [ "Z$5" == "Z" ]; then
> 		COMMENT=""
> 	else
> 		COMMENT="_$5"
> 	fi
> ```

```
[ "$5" != "" ] && COMMENT="_$5"
```
</blockquote></details>

Done.
___
*[tools/rpma_fio_bench.sh, line 81 at r1](https://reviewable.io/reviews/pmem/rpma/691#-MPdrjKu5fsYCL5glWLS:-MPe2E8M83AOdTlm2-5A:b2rbflc) ([raw file](https://github.com/pmem/rpma/blob/d6a45df959e544a001e5630dd6e83c1f6b9eb184/tools/rpma_fio_bench.sh#L81)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

All of these are in the data inside the file. No point in having it here also.
</blockquote></details>

The point is to have it as part of the file name if you have a lot of different files and search for a particular characteristic.
___
*[tools/rpma_fio_bench.sh, line 88 at r1](https://reviewable.io/reviews/pmem/rpma/691#-MPdrtfnEGZtTiOpzzyg:-MPe2RLW6bIO124CVGj9:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/d6a45df959e544a001e5630dd6e83c1f6b9eb184/tools/rpma_fio_bench.sh#L88)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

.
___
*[tools/rpma_fio_bench.sh, line 95 at r1](https://reviewable.io/reviews/pmem/rpma/691#-MPdruDA57o8XFEchjEX:-MPe2SfcDW9_4J7XywxG:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/d6a45df959e544a001e5630dd6e83c1f6b9eb184/tools/rpma_fio_bench.sh#L95)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

.
___
*[tools/rpma_fio_bench.sh, line 116 at r1](https://reviewable.io/reviews/pmem/rpma/691#-MPdsgJO6R5P03qPDmU5:-MPe2XGw1ki027GNiEQR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d6a45df959e544a001e5630dd6e83c1f6b9eb184/tools/rpma_fio_bench.sh#L116)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`P_MODE` before `OP` please
</blockquote></details>

Done.
___
*[tools/rpma_fio_bench.sh, line 209 at r1](https://reviewable.io/reviews/pmem/rpma/691#-MPdsGq-4RrmfqA6X6VK:-MPe3c5_5sGXGyeR94mI:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d6a45df959e544a001e5630dd6e83c1f6b9eb184/tools/rpma_fio_bench.sh#L209)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/691#-:-MPe7d86A2uX8IMdahgJ:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/691)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/691#-:-MPhBfq_1uFG7L_KWYDZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
