### PR TITLE
doc: librpma discontinuation announcement

### PR DESCRIPTION
**Pull request by grom72**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/2137)

### CODE REVIEW

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2137#-:-Nd_Uyrx9fAsl4yL3-in:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2137)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`README.md` line 19 at r1](https://reviewable.io/reviews/pmem/rpma/2137#-Nd_VuL0CGWEb5DR22eF:-Nd_VuL0CGWEb5DR22eG:bptzngn) ([raw file](https://github.com/pmem/rpma/blob/e4c70ba86972bdf209512fd7fc11ad720b3862bc/README.md#L19)):*
> ```Markdown
> Intel no longer accepts patches to this project.
> If you have an ongoing need to use this project, are interested in independently developing it, or would like to maintain patches for the open source software community, please create your own fork of this project.
> You will find more information [here](https://pmem.io/blog/2022/11/update-on-pmdk-and-our-long-term-support-strategy/).
> ```

Can we apply this kind of formatting: https://github.com/pmem/libpmemobj-cpp?
Without it, the announcement is almost invisible.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2137)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[`.github/workflows/on_pull_request.yml` line 34 at r2](https://reviewable.io/reviews/pmem/rpma/2137#-Nd_ZkOl-HWisR0lZixo:-Nd_ZkOl-HWisR0lZixp:undefined) ([raw file](https://github.com/pmem/rpma/blob/c3ca5ae2997f6ae87e26f3a8d7d7145c6fb5ffd5/.github/workflows/on_pull_request.yml#L34)):*
> ```YAML
>                  "N=6 OS=rockylinux OS_VER=8  CC=gcc   PUSH_IMAGE=1",
>                  # Ubuntu-latest with rdma-core v45.0 installed from sources
>                  "N=7 OS=ubuntu OS_VER=latest-with-rdma-core-45 CC=gcc", # disabled intentionaly before project archiving: TESTS_COVERAGE=1",
> ```





_Suggestion:_
```YAML
# TESTS_COVERAGE=1 disabled intentionally before project archiving
```

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2137)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[`README.md` line 19 at r1](https://reviewable.io/reviews/pmem/rpma/2137#-Nd_VuL0CGWEb5DR22eF:-Nd_cdpTBXpZaVnwbRpg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e4c70ba86972bdf209512fd7fc11ad720b3862bc/README.md#L19)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Can we apply this kind of formatting: https://github.com/pmem/libpmemobj-cpp?
Without it, the announcement is almost invisible.
</blockquote></details>

Done.
___
*[`.github/workflows/on_pull_request.yml` line 34 at r2](https://reviewable.io/reviews/pmem/rpma/2137#-Nd_ZkOl-HWisR0lZixo:-Nd_cjSe1Y8W-vWtUvOf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c3ca5ae2997f6ae87e26f3a8d7d7145c6fb5ffd5/.github/workflows/on_pull_request.yml#L34)):*
> ```YAML
>                  "N=6 OS=rockylinux OS_VER=8  CC=gcc   PUSH_IMAGE=1",
>                  # Ubuntu-latest with rdma-core v45.0 installed from sources
>                  "N=7 OS=ubuntu OS_VER=latest-with-rdma-core-45 CC=gcc", # disabled intentionaly before project archiving: TESTS_COVERAGE=1",
> ```

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2137)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2137)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2137)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2137)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2137#-:-Nd_jiGAAsFYMI5JHbOo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
