### PR TITLE
examples: fix example03's client

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1744)

### CODE REVIEW

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1744#-:-N2Pz77K8RiBSIB9CZBH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by osalyk — COMMENTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1744)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1744#-N2QWDgK6BDb5mhOVSBp:-N2QWDgK6BDb5mhOVSBq:b-n0micd) (no related file):*
What about the server?

___

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1744)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

**Review by osalyk — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1744#-:-N2jeksh21zzJDspzW14:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1744#-N2QWDgK6BDb5mhOVSBp:-N2jeffH3_uEAK89Q5D0:bbmbyey) (no related file):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

What about the server?
</blockquote></details>

#1746 

___

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1744)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1744)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[`examples/common/common-pmem_map_file.h` line 31 at r1](https://reviewable.io/reviews/pmem/rpma/1744#-N2ktK7H0rAqem4IhcNP:-N2ktK7H0rAqem4IhcNQ:bmi7tie) ([raw file](https://github.com/pmem/rpma/blob/60b59e2faf491d7de9fa7fe6160cc54ecb505a94/examples/common/common-pmem_map_file.h#L31)):*
> ```objc
> 	struct pmem2_map *map;
> #else
> 	/* let's keep the same structure for both pmem and pmem2 */
> ```

Why? What is it for?
@grom72 ?



_Code quote:_
```objc
#else
	/* let's keep the same structure for both pmem and pmem2 */
	void *unused;
```

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1744)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`examples/common/common-pmem_map_file.h` line 31 at r1](https://reviewable.io/reviews/pmem/rpma/1744#-N2ktK7H0rAqem4IhcNP:-N2kyYMC9B8_vK6ov43Z:b4i40bz) ([raw file](https://github.com/pmem/rpma/blob/60b59e2faf491d7de9fa7fe6160cc54ecb505a94/examples/common/common-pmem_map_file.h#L31)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why? What is it for?
@grom72 ?
</blockquote></details>

``struct example_mem mem = {NULL, 0, 0, 0, NULL};`` - to unify and simplify the way of initialization 



_Code quote (from examples/03-read-to-persistent/client.c):_
```C
struct example_mem mem = {NULL, 0, 0, 0, NULL};
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1744)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`examples/common/common-pmem_map_file.h` line 31 at r1](https://reviewable.io/reviews/pmem/rpma/1744#-N2ktK7H0rAqem4IhcNP:-N2lDa5kDh0e8ilQzKs4:b-4ber9) ([raw file](https://github.com/pmem/rpma/blob/60b59e2faf491d7de9fa7fe6160cc54ecb505a94/examples/common/common-pmem_map_file.h#L31)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

``struct example_mem mem = {NULL, 0, 0, 0, NULL};`` - to unify and simplify the way of initialization 
</blockquote></details>

But this extra field is not initialized now :-)

The initialization can be done using `memset(mem, 0, sizeof());` - IMHO it is better than adding an extra, unused field to the structure.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1744)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[`examples/03-read-to-persistent/client.c` line 58 at r1](https://reviewable.io/reviews/pmem/rpma/1744#-N2pJ8F8-QT0kMXXe-dD:-N2pJ8F8-QT0kMXXe-dE:b-8yml61) ([raw file](https://github.com/pmem/rpma/blob/60b59e2faf491d7de9fa7fe6160cc54ecb505a94/examples/03-read-to-persistent/client.c#L58)):*
> ```C
> 
> 	/* resources - memory region */
> 	struct example_mem mem = {NULL, 0, 0, 0, NULL};
> ```

Please use `memset(mem, 0, sizeof());` instead.



_Code quote:_
```C
struct example_mem mem = {NULL, 0, 0, 0, NULL};
```
___
*[`examples/common/common-pmem_map_file.h` line 31 at r1](https://reviewable.io/reviews/pmem/rpma/1744#-N2ktK7H0rAqem4IhcNP:-N2pJEQz1CPT5qFuKLWv:b-gf6n6c) ([raw file](https://github.com/pmem/rpma/blob/60b59e2faf491d7de9fa7fe6160cc54ecb505a94/examples/common/common-pmem_map_file.h#L31)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

But this extra field is not initialized now :-)

The initialization can be done using `memset(mem, 0, sizeof());` - IMHO it is better than adding an extra, unused field to the structure.
</blockquote></details>

Please remove this unused field in the structure.

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1744)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi and @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1744)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

___
*[`examples/common/common-pmem_map_file.h` line 31 at r1](https://reviewable.io/reviews/pmem/rpma/1744#-N2ktK7H0rAqem4IhcNP:-N2pnP7Q6XBFf6mRk7FT:b32w0x) ([raw file](https://github.com/pmem/rpma/blob/60b59e2faf491d7de9fa7fe6160cc54ecb505a94/examples/common/common-pmem_map_file.h#L31)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

OK, let's  use memset()
</blockquote></details>

OK

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1744)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1744)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[`examples/03-read-to-persistent/client.c` line 58 at r1](https://reviewable.io/reviews/pmem/rpma/1744#-N2pJ8F8-QT0kMXXe-dD:-N36FuHy9n7uAxpmn5pR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/60b59e2faf491d7de9fa7fe6160cc54ecb505a94/examples/03-read-to-persistent/client.c#L58)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please use `memset(mem, 0, sizeof());` instead.
</blockquote></details>

Done.
___
*[`examples/common/common-pmem_map_file.h` line 31 at r1](https://reviewable.io/reviews/pmem/rpma/1744#-N2ktK7H0rAqem4IhcNP:-N36Fvm-Cct_nMYVsu8y:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/60b59e2faf491d7de9fa7fe6160cc54ecb505a94/examples/common/common-pmem_map_file.h#L31)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK
</blockquote></details>

Done.

**Review by grom72 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1744)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1744)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
