### PR TITLE
doc: describe paragraph running workloads

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/837)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/837)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[documentation/perf-tuning-latency.md, line 157 at r1](https://reviewable.io/reviews/pmem/rpma/837#-MSbHAyA4ma0n-CM9kyA:-MSbHAyA4ma0n-CM9kyB:b-q6i68j) ([raw file](https://github.com/pmem/rpma/blob/19f24bff1d3a7c76b6801fbe7d4e7f227cf4b910/documentation/perf-tuning-latency.md#L157)):*
> ```Markdown
> ## Running workloads
> 
> To learn how to run individual workload, visit:
> ```

the individual

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/837)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[documentation/perf-tuning-latency.md, line 157 at r1](https://reviewable.io/reviews/pmem/rpma/837#-MSbHGSt0W2ApewU_HJ2:-MSbHGSt0W2ApewU_HJ3:b-yfkbrv) ([raw file](https://github.com/pmem/rpma/blob/19f24bff1d3a7c76b6801fbe7d4e7f227cf4b910/documentation/perf-tuning-latency.md#L157)):*
> ```Markdown
> ## Running workloads
> 
> To learn how to run individual workload, visit:
> ```

please visit?
___
*[documentation/perf-tuning-latency.md, line 157 at r1](https://reviewable.io/reviews/pmem/rpma/837#-MSbHMRLCxvLnSw9sZ_n:-MSbHMRLCxvLnSw9sZ_o:bybnre0) ([raw file](https://github.com/pmem/rpma/blob/19f24bff1d3a7c76b6801fbe7d4e7f227cf4b910/documentation/perf-tuning-latency.md#L157)):*
> ```Markdown
> ## Running workloads
> 
> To learn how to run individual workload, visit:
> ```

workload**s**?

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/837)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[documentation/perf-tuning-latency.md, line 157 at r1](https://reviewable.io/reviews/pmem/rpma/837#-MSbHAyA4ma0n-CM9kyA:-MSbJHzH7q2C2SHzLFoE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/19f24bff1d3a7c76b6801fbe7d4e7f227cf4b910/documentation/perf-tuning-latency.md#L157)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

the individual
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/837#-:-MSbLe3g7yjSDR16yfJ1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/837)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[documentation/perf-tuning-latency.md, line 157 at r2](https://reviewable.io/reviews/pmem/rpma/837#-MSbtQkgDxo43SskClk9:-MSbtQkgDxo43SskClkA:bfzv9w4) ([raw file](https://github.com/pmem/rpma/blob/3aa699e7ea670402efe0d10ee87311df77464c37/documentation/perf-tuning-latency.md#L157)):*
> ```
> To learn
> ```

In order to learn ...

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/837)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[documentation/perf-tuning-latency.md, line 157 at r2](https://reviewable.io/reviews/pmem/rpma/837#-MSbtQkgDxo43SskClk9:-MSbv44k9LTELSkHTnTV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3aa699e7ea670402efe0d10ee87311df77464c37/documentation/perf-tuning-latency.md#L157)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> To learn
> ```

In order to learn ...
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/837#-:-MSbvjRx6eUcpO7Lk-ig:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/837)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
