### PR TITLE
common: 0.9.0

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/535)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/535)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/535#-:-MIZRMxP3ne10zGB1XZ-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/535#-:-MIZRPXn-XwMkTHLBqBD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/535)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/535#-:-MIZRy2d7UsNMZIA1lXY:bnfp4nl)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @grom72 and @ldorau)

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/535)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[CHANGELOG.md, line 16 at r2](https://reviewable.io/reviews/pmem/rpma/535#-MIZS3H34kTZf9kyFRrI:-MIZS3H34kTZf9kyFRrJ:bjq50px) ([raw file](https://github.com/pmem/rpma/blob/2b07833d590e66133d7073e36bdebe95901e4730/CHANGELOG.md#L16)):*
> ```
> An extensive 
> ```

The extensive

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/535)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/535)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/535#-:-MIZSHf8EGm_v08aji3w:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/535)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
