### PR TITLE
rpma: mark as deprecated rpma_cq_get_completion(), struct rpma_completion and enum rpma_op

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1525)

### CODE REVIEW

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1525#-:-Muj-9DzAmeN-CMv28zo:bg7igkv)* status: 0 of 1 files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1525)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1525)* status: all files reviewed, 4 unresolved discussions (waiting on @haichangsi)

___
*[src/include/librpma.h, line 2720 at r1](https://reviewable.io/reviews/pmem/rpma/1525#-MujQPkPAm8rJQTJeGRl:-MujQPkQ5r4no2g-2J-k:bal9vw) ([raw file](https://github.com/pmem/rpma/blob/b07c1ce0b7afd944987652ba030c74894eb0de07/src/include/librpma.h#L2720)):*
> ```objc
> int rpma_conn_get_completion_fd(const struct rpma_conn *conn, int *fd);
> 
> /* For details please see rpma_cq_get_completion(3). (deprecated) */
> ```

`/* DEPRECATED - for details please see rpma_cq_get_completion(3). */`



_Code quote:_
```objc
/* For details please see rpma_cq_get_completion(3). (deprecated) */
```
___
*[src/include/librpma.h, line 2730 at r1](https://reviewable.io/reviews/pmem/rpma/1525#-MujQXe72bdmvh3Ckd8u:-MujQXe8-4rgZY3h8h6S:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/b07c1ce0b7afd944987652ba030c74894eb0de07/src/include/librpma.h#L2730)):*
> ```objc
> };
> 
> /* For details please see rpma_cq_get_completion(3). (deprecated) */
> ```

.



_Code quote:_
```objc
/* For details please see rpma_cq_get_completion(3). (deprecated) */
```
___
*[src/include/librpma.h, line 2985 at r1](https://reviewable.io/reviews/pmem/rpma/1525#-MujRCwt2p5WR0Eg4JJE:-MujRCwt2p5WR0Eg4JJF:b2s23tv) ([raw file](https://github.com/pmem/rpma/blob/b07c1ce0b7afd944987652ba030c74894eb0de07/src/include/librpma.h#L2985)):*
> ```objc
>  *	struct rpma_completion cmpl;
>  *
>  *	ret = rpma_cq_get_completion(cq, &cmpl);
> ```

```c
 *	ret = rpma_cq_get_completion(cq, &cmpl);
 *	if (ret) { error_handling_code() }
 *
```



_Code quote:_
```objc
 *	ret = rpma_cq_get_completion(cq, &cmpl);
```
___
*[src/include/librpma.h, line 2995 at r1](https://reviewable.io/reviews/pmem/rpma/1525#-MujRPU96rYoOYu-_1Lf:-MujRPU96rYoOYu-_1Lg:bd12kss) ([raw file](https://github.com/pmem/rpma/blob/b07c1ce0b7afd944987652ba030c74894eb0de07/src/include/librpma.h#L2995)):*
> ```objc
>  *	struct ibv_wc wc;
>  *
>  *	ret = rpma_cq_get_wc(cq, 1, &wc, NULL);
> ```

Please add
```c
 *	if (ret) { error_handling_code() }
```



_Code quote:_
```objc
 *	ret = rpma_cq_get_wc(cq, 1, &wc, NULL);
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1525)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[src/include/librpma.h, line 2720 at r1](https://reviewable.io/reviews/pmem/rpma/1525#-MujQPkPAm8rJQTJeGRl:-MukOXjQ-tV4fy5d1UGV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b07c1ce0b7afd944987652ba030c74894eb0de07/src/include/librpma.h#L2720)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`/* DEPRECATED - for details please see rpma_cq_get_completion(3). */`
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2730 at r1](https://reviewable.io/reviews/pmem/rpma/1525#-MujQXe72bdmvh3Ckd8u:-MukOYPTCzBvM-Y-JOwY:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b07c1ce0b7afd944987652ba030c74894eb0de07/src/include/librpma.h#L2730)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2995 at r1](https://reviewable.io/reviews/pmem/rpma/1525#-MujRPU96rYoOYu-_1Lf:-MukP-CQ5UczGNYEcCD3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b07c1ce0b7afd944987652ba030c74894eb0de07/src/include/librpma.h#L2995)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please add
```c
 *	if (ret) { error_handling_code() }
```

</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1525)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1525#-MukbA7GE7qEKlRxSuZl:-MukbA7GE7qEKlRxSuZm:bmnk84h) (no related file):*
Please add the following lines:
```
### Deprecated
- APIs:
  - rpma_cq_get_completion - replaced with rpma_cq_get_wc
  - struct rpma_completion - replaced with struct ibv_wc from libibverbs
  - enum rpma_op - replaced with enum ibv_wc_opcode from libibverbs

```
to CHANGELOG.md at the line https://github.com/pmem/rpma/blob/master/CHANGELOG.md?plain=1#L16 (before `Removed`)

---
___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/1525#-MukZEdDEOTYFBBZJp3J):*
Please change the commit message to the following one:
```
rpma: mark rpma_cq_get_completion() as deprecated

Mark as deprecated:
- rpma_cq_get_completion(),
- struct rpma_completion and
- enum rpma_op.
```



_Code quote:_
```
rpma: librpma.h rpma_cq_get_completion deprecated
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1525)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1525#-MukbA7GE7qEKlRxSuZl:-MuomLPy0bnsa73LEew_:b-q1wsdq) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please add the following lines:
```
### Deprecated
- APIs:
  - rpma_cq_get_completion - replaced with rpma_cq_get_wc
  - struct rpma_completion - replaced with struct ibv_wc from libibverbs
  - enum rpma_op - replaced with enum ibv_wc_opcode from libibverbs

```
to CHANGELOG.md at the line https://github.com/pmem/rpma/blob/master/CHANGELOG.md?plain=1#L16 (before `Removed`)
</blockquote></details>

This PR is rebased on the devel branch as you suggested but your example CHANGELOG is from the master branch. What should I do ?

---
___
*[src/include/librpma.h, line 2985 at r1](https://reviewable.io/reviews/pmem/rpma/1525#-MujRCwt2p5WR0Eg4JJE:-MuomuW1AQdLoXGjd-OZ:b-29gorc) ([raw file](https://github.com/pmem/rpma/blob/b07c1ce0b7afd944987652ba030c74894eb0de07/src/include/librpma.h#L2985)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```c
 *	ret = rpma_cq_get_completion(cq, &cmpl);
 *	if (ret) { error_handling_code() }
 *
```
</blockquote></details>

It is done

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1525)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1525#-MukbA7GE7qEKlRxSuZl:-MuoqO8ABI40tIPYQrLF:byukgwy) (no related file):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

This PR is rebased on the devel branch as you suggested but your example CHANGELOG is from the master branch. What should I do ?
</blockquote></details>

This PR should be submitted to the master branch

---

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1525)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1525#-MukbA7GE7qEKlRxSuZl:-Muoy-IF7juIWlLCnfV8:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

This PR should be submitted to the master branch
</blockquote></details>

Done.

---
___
*[-- commits, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/1525#-MukZEdDEOTYFBBZJp3J):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please change the commit message to the following one:
```
rpma: mark rpma_cq_get_completion() as deprecated

Mark as deprecated:
- rpma_cq_get_completion(),
- struct rpma_completion and
- enum rpma_op.
```
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1525)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[CHANGELOG.md, line 21 at r3](https://reviewable.io/reviews/pmem/rpma/1525#-Mup2zJL8NbBWjx9hpJc:-Mup2zJL8NbBWjx9hpJd:b-lronqc) ([raw file](https://github.com/pmem/rpma/blob/f10b8eac9161b48d1176dc9674efdace982bee7d/CHANGELOG.md#L21)):*
> ```Markdown
>   - struct rpma_completion - replaced with struct ibv_wc from libibverbs
>   - enum rpma_op - replaced with enum ibv_wc_opcode from libibverbs
> ### Removed
> ```

Please add one empty line in between



_Code quote:_
```Markdown
  - enum rpma_op - replaced with enum ibv_wc_opcode from libibverbs
### Removed
```

**Review by ldorau — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1525#-:-Mup3TZ1CRD_Wg4z3mhr:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1525)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[CHANGELOG.md, line 21 at r3](https://reviewable.io/reviews/pmem/rpma/1525#-Mup2zJL8NbBWjx9hpJc:-MupWB3C6CebsyISKuT9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f10b8eac9161b48d1176dc9674efdace982bee7d/CHANGELOG.md#L21)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please add one empty line in between
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1525#-:-MupZM6e9Sm3u-PU3yXU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1525#-:-MutHKB385uHsEc-ho7J:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1525)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
