### PR TITLE
common: unified files names

### PR DESCRIPTION
**Pull request by grom72**
all tests source code file name follow the same format:
<module>-<service_with_undrscores>

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/512)

### CODE REVIEW

**Review by ldorau — APPROVED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/512)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/512#-:-MIVUuWW40Y4Sux76aze:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/512#-:-MIVW6iL62JTBHFOPNlj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/512)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/512#-:-MIYCBQC5n5fMveLg2bt:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
