### PR TITLE
doc: add performance reports for Ice Lake

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1789)

### CODE REVIEW

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1789)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1789)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1789)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[`reports/index.md` line 14 at r1](https://reviewable.io/reviews/pmem/rpma/1789#-N3USHCO0IhU9VGWvoS7:-N3USHCPEAanEhQVaY6y:b2kv30d) ([raw file](https://github.com/pmem/rpma/blob/c936e71c9d69b48429caaa7e764d2206754af639/reports/index.md#L14)):*
> ```Markdown
> ## Ice Lake
> * [Intel&reg; Ice Lake + Mellanox&reg; ConnectX&reg;-5 + CentOS Linux 8.2 kernel 4.18 + Device DAX](https://github.com/pmem/rpma/releases/download/0.14.0/RPMA_Perf_report_ICX_MLX_CentOS8.2_DEVDAX.pdf)
> * [Intel&reg; Ice Lake + Mellanox&reg; ConnectX&reg;-5 + CentOS Linux 8.2 kernel 4.18 + File System DAX](https://github.com/pmem/rpma/releases/download/0.14.0/RPMA_Perf_report_ICX_MLX_CentOS8.2_FSDAX.pdf)
> ```

missing EOF

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1789#-:-N3UYLOe-J4ohIauGX9r:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
