### PR TITLE
rpma: implement rpma_mr_recv() and its unit tests

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/328)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/328)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/328#-MG8pyDQ24RPDmBaVaIV:-MG8pyDQ24RPDmBaVaIW:bbtzsiu) (no related file):*
You are sure the PR's are interdependent?

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/328)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/328#-MG8pyDQ24RPDmBaVaIV:-MG8rlRA-rP1nHXC_w8n:b52c2jf) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You are sure the PR's are interdependent?
</blockquote></details>

Indeed, they are not ... Rebased

---

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/328#-:-MG9CnUV-uNhVHIkrByr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/328#-:-MGCtM543CP80xx_vo_a:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
