### PR TITLE
examples: 08 messages ping pong

### PR DESCRIPTION
**Pull request by janekmi**
Requires:
- [x] #311
- [x] #335 

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/312)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/312)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi)

___
*[examples/08-messages-ping-pong/client.c, line 27 at r1](https://reviewable.io/reviews/pmem/rpma/312#-MFzLX8t5s826uWNMLEL:-MFzLX8t5s826uWNMLEM:b-nubflk) ([raw file](https://github.com/pmem/rpma/blob/28377b2e29b1bfc5d5efaa7653d18ce1570769de/examples/08-messages-ping-pong/client.c#L27)):*
> ```
> <rounds>
> ```
it will be good to define here also delay between rounds
___
*[examples/08-messages-ping-pong/client.c, line 102 at r1](https://reviewable.io/reviews/pmem/rpma/312#-MFzK0VX2OJOeQFSx-d1:-MFzK0VYARfBEu4qtZ38:b-smso6v) ([raw file](https://github.com/pmem/rpma/blob/28377b2e29b1bfc5d5efaa7653d18ce1570769de/examples/08-messages-ping-pong/client.c#L102)):*
> ```
> for (; rounds >= 0; --rounds)
> ```
while (--rounds)
___
*[examples/08-messages-ping-pong/README.md, line 7 at r1](https://reviewable.io/reviews/pmem/rpma/312#-MFzLl5bAyhSr6LDNXFe:-MFzLl5bAyhSr6LDNXFf:b-d2p995) ([raw file](https://github.com/pmem/rpma/blob/28377b2e29b1bfc5d5efaa7653d18ce1570769de/examples/08-messages-ping-pong/README.md#L7)):*
> ```
> The server prepares a receiving buffer
> for each of the clients.
> ```
I personally do not like this concept - it should be a simple example of sending and receiving.

if we want to have a multiclient solution would be good to have like in rping https://linux.die.net/man/1/rping a possibility to kill server with Ctrl-C 
___
*[examples/08-messages-ping-pong/server.c, line 5 at r1](https://reviewable.io/reviews/pmem/rpma/312#-MFzL7JHCqBy3MKev8oK:-MFzL7JIAejI4E8jJoBt:b-1ls17j) ([raw file](https://github.com/pmem/rpma/blob/28377b2e29b1bfc5d5efaa7653d18ce1570769de/examples/08-messages-ping-pong/server.c#L5)):*
> ```
> a server of the messages-ping-pong example
> ```
I expect this example to be a very simple one with 1:1 connection architecture.
___
*[examples/08-messages-ping-pong/server.c, line 375 at r1](https://reviewable.io/reviews/pmem/rpma/312#-MFzQFe4CDcmnhywOrhH:-MFzQFe56DZHuirl-nte:b-a4uqfq) ([raw file](https://github.com/pmem/rpma/blob/28377b2e29b1bfc5d5efaa7653d18ce1570769de/examples/08-messages-ping-pong/server.c#L375)):*
> ```
> rpma_log_set_threshold(RPMA_LOG_THRESHOLD, RPMA_LOG_LEVEL_INFO);
> 	r
> ```
this could be controlled with parameter 
see https://linux.die.net/man/1/rping

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/312)* status: 2 of 6 files reviewed, 5 unresolved discussions (waiting on @grom72)

___
*[examples/08-messages-ping-pong/client.c, line 27 at r1](https://reviewable.io/reviews/pmem/rpma/312#-MFzLX8t5s826uWNMLEL:-MG4B8iq4UlUXWvTgx38:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/28377b2e29b1bfc5d5efaa7653d18ce1570769de/examples/08-messages-ping-pong/client.c#L27)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> <rounds>
> ```
it will be good to define here also delay between rounds
</blockquote></details>

Done.
___
*[examples/08-messages-ping-pong/client.c, line 102 at r1](https://reviewable.io/reviews/pmem/rpma/312#-MFzK0VX2OJOeQFSx-d1:-MG4BAh-5GFbHdEewATV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/28377b2e29b1bfc5d5efaa7653d18ce1570769de/examples/08-messages-ping-pong/client.c#L102)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> for (; rounds >= 0; --rounds)
> ```
while (--rounds)
</blockquote></details>

Done.
___
*[examples/08-messages-ping-pong/README.md, line 7 at r1](https://reviewable.io/reviews/pmem/rpma/312#-MFzLl5bAyhSr6LDNXFe:-MG4BDnhD4oazxJtWvUa:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/28377b2e29b1bfc5d5efaa7653d18ce1570769de/examples/08-messages-ping-pong/README.md#L7)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> The server prepares a receiving buffer
> for each of the clients.
> ```
I personally do not like this concept - it should be a simple example of sending and receiving.

if we want to have a multiclient solution would be good to have like in rping https://linux.die.net/man/1/rping a possibility to kill server with Ctrl-C 
</blockquote></details>

Done.
___
*[examples/08-messages-ping-pong/server.c, line 5 at r1](https://reviewable.io/reviews/pmem/rpma/312#-MFzL7JHCqBy3MKev8oK:-MG4BFQv9M2DjosAkT8r:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/28377b2e29b1bfc5d5efaa7653d18ce1570769de/examples/08-messages-ping-pong/server.c#L5)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> a server of the messages-ping-pong example
> ```
I expect this example to be a very simple one with 1:1 connection architecture.
</blockquote></details>

Done.
___
*[examples/08-messages-ping-pong/server.c, line 375 at r1](https://reviewable.io/reviews/pmem/rpma/312#-MFzQFe4CDcmnhywOrhH:-MG4BIIv5IENrErqOe7l:b-r35t6h) ([raw file](https://github.com/pmem/rpma/blob/28377b2e29b1bfc5d5efaa7653d18ce1570769de/examples/08-messages-ping-pong/server.c#L375)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> rpma_log_set_threshold(RPMA_LOG_THRESHOLD, RPMA_LOG_LEVEL_INFO);
> 	r
> ```
this could be controlled with parameter 
see https://linux.die.net/man/1/rping
</blockquote></details>

Sure it can. When we will return to exact rping example probably we will also add such a parameter.

**Review by grom72 — COMMENTED** [review]
:goat: 

> Reviewed 4 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/312#-:-MG4F_Kg5s7bM9tFIRqZ:bdycpsm)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/312)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi)

___
*[examples/08-messages-ping-pong/client.c, line 31 at r3](https://reviewable.io/reviews/pmem/rpma/312#-MG4lL6-6kX_OD_ap98O:-MG4lL6-6kX_OD_ap98P:blaq8me) ([raw file](https://github.com/pmem/rpma/blob/badfff1fa76257d7548273c09aa89885e195e76b/examples/08-messages-ping-pong/client.c#L31)):*
> ```
> exit(-1);
> ```
do not know what to say ... it is like exception in C++ but ... this is not C++
___
*[examples/08-messages-ping-pong/client.c, line 100 at r3](https://reviewable.io/reviews/pmem/rpma/312#-MG4moEd0oNxIJhYdUc1:-MG4moEd0oNxIJhYdUc2:b-tr6xp0) ([raw file](https://github.com/pmem/rpma/blob/badfff1fa76257d7548273c09aa89885e195e76b/examples/08-messages-ping-pong/client.c#L100)):*
> ```
> RPMA_F_COMPLETION_ALWAYS
> ```
Is there any other option possible here?
___
*[examples/08-messages-ping-pong/client.c, line 110 at r3](https://reviewable.io/reviews/pmem/rpma/312#-MG4nK7ODS0KOldnrs4v:-MG4nK7ODS0KOldnrs4w:bqwqh0f) ([raw file](https://github.com/pmem/rpma/blob/badfff1fa76257d7548273c09aa89885e195e76b/examples/08-messages-ping-pong/client.c#L110)):*
> ```
> rpma_conn_prepare_completions
> ```
shall we use it here if we do not use fd?
is it enough to have only rpma_conn_next_completi?
___
*[examples/08-messages-ping-pong/client.c, line 118 at r3](https://reviewable.io/reviews/pmem/rpma/312#-MG4m_Lb5ro0OcfTe_5j:-MG4m_Lb5ro0OcfTe_5k:bovnicc) ([raw file](https://github.com/pmem/rpma/blob/badfff1fa76257d7548273c09aa89885e195e76b/examples/08-messages-ping-pong/client.c#L118)):*
> ```C
> 				cmpl.op_context != recv ||
> 				cmpl.byte_len != MSG_SIZE) {
> 			(void) fprintf(stderr,
> ```

Can we have this string more meaningful?
___
*[examples/08-messages-ping-pong/client.c, line 121 at r3](https://reviewable.io/reviews/pmem/rpma/312#-MG4m6IF16i0lRtfkV4B:-MG4m6IF16i0lRtfkV4C:btoou1l) ([raw file](https://github.com/pmem/rpma/blob/badfff1fa76257d7548273c09aa89885e195e76b/examples/08-messages-ping-pong/client.c#L121)):*
> ```
> IBV_WC_SUCCESS
> ```
as string?
___
*[examples/08-messages-ping-pong/server.c, line 117 at r3](https://reviewable.io/reviews/pmem/rpma/312#-MG4odHKA6RzDayb4Cxf:-MG4odHKA6RzDayb4Cxg:b-mvc9pf) ([raw file](https://github.com/pmem/rpma/blob/badfff1fa76257d7548273c09aa89885e195e76b/examples/08-messages-ping-pong/server.c#L117)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> (void) fprintf(stderr,
> 					"received completion is not as expected (%d != %d || %d != %d || %p != %p || %"
> 					PRIu32 " != %ld)\n",
> 					cmpl.op, RPMA_OP_RECV,
> 					cmpl.op_status, IBV_WC_SUCCESS,
> 					cmpl.op_context, recv,
> 					cmpl.byte_len, MSG_SIZE);
> ```
</details>

 34 != 45 || 0 != 4 ... do not say anything about exit reason

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/312)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[examples/08-messages-ping-pong/client.c, line 110 at r3](https://reviewable.io/reviews/pmem/rpma/312#-MG4nK7ODS0KOldnrs4v:-MG7ChiF1BsQ6PhtGtMO:b-vkpk6t) ([raw file](https://github.com/pmem/rpma/blob/badfff1fa76257d7548273c09aa89885e195e76b/examples/08-messages-ping-pong/client.c#L110)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> rpma_conn_prepare_completions
> ```
shall we use it here if we do not use fd?
is it enough to have only rpma_conn_next_completi?
</blockquote></details>

Yes we have. Otherwise, `rpma_conn_next_completion()` is non-blocking so we would have to have a loop.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/312)* status: 4 of 6 files reviewed, 6 unresolved discussions (waiting on @grom72)

___
*[examples/08-messages-ping-pong/client.c, line 31 at r3](https://reviewable.io/reviews/pmem/rpma/312#-MG4lL6-6kX_OD_ap98O:-MG7GFRo0GCWj360Uafi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/badfff1fa76257d7548273c09aa89885e195e76b/examples/08-messages-ping-pong/client.c#L31)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> exit(-1);
> ```
do not know what to say ... it is like exception in C++ but ... this is not C++
</blockquote></details>

Done.
___
*[examples/08-messages-ping-pong/client.c, line 100 at r3](https://reviewable.io/reviews/pmem/rpma/312#-MG4moEd0oNxIJhYdUc1:-MG7GImG-uF-JMjuBFAW:b-jbfcbx) ([raw file](https://github.com/pmem/rpma/blob/badfff1fa76257d7548273c09aa89885e195e76b/examples/08-messages-ping-pong/client.c#L100)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> RPMA_F_COMPLETION_ALWAYS
> ```
Is there any other option possible here?
</blockquote></details>

Do be discussed. ;-)
___
*[examples/08-messages-ping-pong/client.c, line 118 at r3](https://reviewable.io/reviews/pmem/rpma/312#-MG4m_Lb5ro0OcfTe_5j:-MG7GCDo8FCImlaJq7DS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/badfff1fa76257d7548273c09aa89885e195e76b/examples/08-messages-ping-pong/client.c#L118)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Can we have this string more meaningful?
</blockquote></details>

Done.
___
*[examples/08-messages-ping-pong/client.c, line 121 at r3](https://reviewable.io/reviews/pmem/rpma/312#-MG4m6IF16i0lRtfkV4B:-MG7GD332G7Zvr3TO0vX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/badfff1fa76257d7548273c09aa89885e195e76b/examples/08-messages-ping-pong/client.c#L121)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> IBV_WC_SUCCESS
> ```
as string?

</blockquote></details>

Done.
___
*[examples/08-messages-ping-pong/server.c, line 117 at r3](https://reviewable.io/reviews/pmem/rpma/312#-MG4odHKA6RzDayb4Cxf:-MG7GEILAn6T8GZM0ezk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/badfff1fa76257d7548273c09aa89885e195e76b/examples/08-messages-ping-pong/server.c#L117)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> (void) fprintf(stderr,
> 					"received completion is not as expected (%d != %d || %d != %d || %p != %p || %"
> 					PRIu32 " != %ld)\n",
> 					cmpl.op, RPMA_OP_RECV,
> 					cmpl.op_status, IBV_WC_SUCCESS,
> 					cmpl.op_context, recv,
> 					cmpl.byte_len, MSG_SIZE);
> ```
 34 != 45 || 0 != 4 ... do not say anything about exit reason
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/312#-:-MG7NIJNBoYD-UUJbxIo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/312)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[examples/08-messages-ping-pong/server.c, line 118 at r5](https://reviewable.io/reviews/pmem/rpma/312#-MG7NS3FDemStSQQEXae:-MG7NS3FDemStSQQEXaf:bjuh88d) ([raw file](https://github.com/pmem/rpma/blob/22ab75b4537ce0d29c9712486068970380615bfa/examples/08-messages-ping-pong/server.c#L118)):*
> ```C
> 				cmpl.byte_len != MSG_SIZE) {
> 			(void) fprintf(stderr,
> 					"received completion is not as expected (%d != %d [cmpl.op] || %s != %s || %p != %p [cmpl.op_context] || %"
> ```

Too long

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/312)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[examples/08-messages-ping-pong/server.c, line 118 at r5](https://reviewable.io/reviews/pmem/rpma/312#-MG7NS3FDemStSQQEXae:-MG7TfCLCyuIv7ld4ewg:bgwr2rk) ([raw file](https://github.com/pmem/rpma/blob/22ab75b4537ce0d29c9712486068970380615bfa/examples/08-messages-ping-pong/server.c#L118)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Too long
</blockquote></details>

No, it is not since it is a string which is unbreakable.

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/312)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/312)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[examples/08-messages-ping-pong/client.c, line 56 at r6](https://reviewable.io/reviews/pmem/rpma/312#-MGChgz_CmT8aK3eDbX9:-MGChgza2MiMfnpKzcpY:b-4maigx) ([raw file](https://github.com/pmem/rpma/blob/6d1674efeee6f6b13111127784198642880877e6/examples/08-messages-ping-pong/client.c#L56)):*
> ```
> if (argc == 5)
> 		sleep_usec = strtoul_noerror(argv[5]);
> ```
argc == 6
___
*[examples/08-messages-ping-pong/README.md, line 22 at r6](https://reviewable.io/reviews/pmem/rpma/312#-MGCiCSi1vLFl76pJFpX:-MGCiCSi1vLFl76pJFpY:bp1s0mo) ([raw file](https://github.com/pmem/rpma/blob/6d1674efeee6f6b13111127784198642880877e6/examples/08-messages-ping-pong/README.md#L22)):*
> ```Markdown
> 
> ```bash
> [user@client]$ ./client $server_address $port $seed $rounds
> ```

[<sleep>]

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/312)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[examples/08-messages-ping-pong/client.c, line 56 at r6](https://reviewable.io/reviews/pmem/rpma/312#-MGChgz_CmT8aK3eDbX9:-MGDKwh62D0eoRrfoE5U:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6d1674efeee6f6b13111127784198642880877e6/examples/08-messages-ping-pong/client.c#L56)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

> ```
> if (argc == 5)
> 		sleep_usec = strtoul_noerror(argv[5]);
> ```
argc == 6
</blockquote></details>

Done.
___
*[examples/08-messages-ping-pong/README.md, line 22 at r6](https://reviewable.io/reviews/pmem/rpma/312#-MGCiCSi1vLFl76pJFpX:-MGDKZeiBFSq6yM2GTfm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6d1674efeee6f6b13111127784198642880877e6/examples/08-messages-ping-pong/README.md#L22)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

[<sleep>]
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/312)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/312)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/312#-:-MGDZzVQ2qh01qdL4QvG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:goat: 

> Reviewed 1 of 2 files at r7, 3 of 3 files at r8, 3 of 3 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/312#-:-MGE6FEb2XWpl9veaPmx:bdycpsm)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
