### PR TITLE
common: remove deprecated API

### PR DESCRIPTION
**Pull request by Patryk717**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1529)

### CODE REVIEW

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1529)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 5 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1529)* status: 5 of 10 files reviewed, 2 unresolved discussions (waiting on @haichangsi, @ldorau, and @Patryk717)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1529#-MukdR52EM3SsVFRdstY):*
common: remove deprecated API



_Code quote:_
```
common: remove old api
```
___
*[CHANGELOG.md, line 61 at r1](https://reviewable.io/reviews/pmem/rpma/1529#-Mukd6ao4s4IYgCKBnll:-Mukd6apERGtViZ1033m:bnzco83) ([raw file](https://github.com/pmem/rpma/blob/da31cc6f0e5793ad6ba848612a5949f9ace407c1/CHANGELOG.md#L61)):*
> ```Markdown
>   - rpma_conn_completion_get - replaced with rpma_conn_get_cq and rpma_cq_get_completion,
>   - rpma_conn_completion_wait - replaced with rpma_conn_get_cq and rpma_cq_wait,
>   - rpma_conn_get_completion_fd - replaced with rpma_conn_get_cq and rpma_cq_get_fd.
> ```

These lines should stay as are. Do not remove them.



_Code quote:_
```Markdown
### Deprecated
- APIs:
  - rpma_conn_completion_get - replaced with rpma_conn_get_cq and rpma_cq_get_completion,
  - rpma_conn_completion_wait - replaced with rpma_conn_get_cq and rpma_cq_wait,
  - rpma_conn_get_completion_fd - replaced with rpma_conn_get_cq and rpma_cq_get_fd.
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1529)* status: 5 of 10 files reviewed, 3 unresolved discussions (waiting on @haichangsi, @ldorau, and @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1529#-MukdvUT5yjfkrwy-K-Z:-MukdvUT5yjfkrwy-K-_:b-ne7glb) (no related file):*
1) Please make all CI builds pass.
2) Please verify locally (before pushing it out) if the pull request builds correctly.

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1529)* status: 5 of 13 files reviewed, 3 unresolved discussions (waiting on @haichangsi, @ldorau, and @Patryk717)

___
*[tests/cmake/helpers.cmake, line 238 at r3](https://reviewable.io/reviews/pmem/rpma/1529#-MuoYyFTCIA4DEbPvxSW:-MuoYyFUDLUSk3Enp55s:btit0cc) ([raw file](https://github.com/pmem/rpma/blob/da31cc6f0e5793ad6ba848612a5949f9ace407c1/tests/cmake/helpers.cmake#L238)):*
> ```CMake
> # the command.
> function(execute name)
>     check_target(${name})
> ```

Why have you removed that?



_Code quote:_
```CMake
function(execute name)
    check_target(${name})

    execute_common(true ${TRACER}_${TESTCASE} ${name} ${ARGN})
endfunction()

# Executes test command ${name} under GDB.
# First argument of the command is a gdb batch file.
# Second argument of the command is the test command.
# Optional function arguments are passed as consecutive arguments to
# the command.
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1529)* status: 5 of 13 files reviewed, 3 unresolved discussions (waiting on @haichangsi, @ldorau, and @Patryk717)

___
*[tests/integration/common/mocks.c, line 99 at r3](https://reviewable.io/reviews/pmem/rpma/1529#-MuoZVbR2C_4V03BDP0W:-MuoZVbR2C_4V03BDP0X:btit0cc) ([raw file](https://github.com/pmem/rpma/blob/da31cc6f0e5793ad6ba848612a5949f9ace407c1/tests/integration/common/mocks.c#L99)):*
> ```C
> 
> /*
>  * ibv_get_cq_event -- ibv_get_cq_event() mock
> ```

Why have you removed that?



_Code quote:_
```C
/*
 * ibv_get_cq_event -- ibv_get_cq_event() mock
 */
int
ibv_get_cq_event(struct ibv_comp_channel *channel, struct ibv_cq **cq,
		void **cq_context)
{
	check_expected_ptr(channel);
	assert_non_null(cq);
	assert_non_null(cq_context);

	errno = mock_type(int);
	if (!errno) {
		*cq = MOCK_CQ;
		*cq_context = NULL;
		return 0;
	}

	return -1;
}
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 3 of 10 files at r1, 1 of 6 files at r3, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1529)* status: 9 of 13 files reviewed, 4 unresolved discussions (waiting on @haichangsi, @ldorau, and @Patryk717)

___
*[doc/manuals_3.txt, line 33 at r4](https://reviewable.io/reviews/pmem/rpma/1529#-Mup7GgW5jGSa384cgiZ:-Mup7GgW5jGSa384cgi_:b-1zjj6r) ([raw file](https://github.com/pmem/rpma/blob/da31cc6f0e5793ad6ba848612a5949f9ace407c1/doc/manuals_3.txt#L33)):*
> ```help
> rpma_cq_get_fd.3
> rpma_cq_get_wc.3
> rpma_cq_wait.3
> ```

Why have you removed `rpma_cq_wait.3` ?



_Code quote:_
```help
rpma_cq_wait.3
```
___
*[tests/cmake/helpers.cmake, line 238 at r3](https://reviewable.io/reviews/pmem/rpma/1529#-MuoYyFTCIA4DEbPvxSW:-Mup7PuOB8N6bWBNw82a:b32gy8v) ([raw file](https://github.com/pmem/rpma/blob/da31cc6f0e5793ad6ba848612a5949f9ace407c1/tests/cmake/helpers.cmake#L238)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why have you removed that?
</blockquote></details>

I think this file should not be changed at all.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1529)* status: 10 of 13 files reviewed, 4 unresolved discussions (waiting on @haichangsi, @ldorau, and @Patryk717)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1529)* status: all files reviewed, 3 unresolved discussions (waiting on @Patryk717)

___
*[tests/cmake/helpers.cmake, line 238 at r3](https://reviewable.io/reviews/pmem/rpma/1529#-MuoYyFTCIA4DEbPvxSW:-MupLxCm8km3bKjycXzU:b-liko3r) ([raw file](https://github.com/pmem/rpma/blob/da31cc6f0e5793ad6ba848612a5949f9ace407c1/tests/cmake/helpers.cmake#L238)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I think this file should not be changed at all.
</blockquote></details>

Please do not change this file at all.
___
*[tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c, line 5 at r5](https://reviewable.io/reviews/pmem/rpma/1529#-MupMOHy9RU64T5sSN9H:-MupMOHy9RU64T5sSN9I:b-t3rmv3) ([raw file](https://github.com/pmem/rpma/blob/da31cc6f0e5793ad6ba848612a5949f9ace407c1/tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c#L5)):*
> ```C
> 
> /*
>  * example-02-read-to-volatile.c -- 'read to volatile' integration tests
> ```

Why have you removed this file ???



_Code quote:_
```C
example-02-read-to-volatile.c
```
___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 5 at r5](https://reviewable.io/reviews/pmem/rpma/1529#-MupMUUmEx5mmL5EENbA:-MupMUUmEx5mmL5EENbB:b-t3rmv3) ([raw file](https://github.com/pmem/rpma/blob/da31cc6f0e5793ad6ba848612a5949f9ace407c1/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L5)):*
> ```C
> 
> /*
>  * example-04-write-to-persistent.c -- 'write to persistent' integration tests
> ```

Why have you removed this file ???



_Code quote:_
```C
example-04-write-to-persistent.c
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1529)* status: all files reviewed, 1 unresolved discussion (waiting on @Patryk717)

___
*[tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c, line 5 at r5](https://reviewable.io/reviews/pmem/rpma/1529#-MupMOHy9RU64T5sSN9H:-MupNJHJ3tlQZSeztdcm:bmmv0lm) ([raw file](https://github.com/pmem/rpma/blob/da31cc6f0e5793ad6ba848612a5949f9ace407c1/tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c#L5)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why have you removed this file ???
</blockquote></details>

It is OK, Reviewable displayed it as it was removed.
___
*[tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c, line 5 at r5](https://reviewable.io/reviews/pmem/rpma/1529#-MupMUUmEx5mmL5EENbA:-MupNVMlDZQkQo-Xj9Oc:b-8mf14w) ([raw file](https://github.com/pmem/rpma/blob/da31cc6f0e5793ad6ba848612a5949f9ace407c1/tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c#L5)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why have you removed this file ???
</blockquote></details>

It is OK, Reviewable displayed it as it was removed.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1529)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)

**Review by osalyk — APPROVED** [review]
> Reviewed 6 of 10 files at r1, 1 of 6 files at r3, 1 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1529)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1529)* status: all files reviewed, 3 unresolved discussions (waiting on @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1529#-MupPc438Ij1a26HyaSp:-MupPc438Ij1a26HyaSq:b-ec29q5) (no related file):*
Please add to the CHANGLOG under the first Removed:
```
- APIs:
  - rpma_conn_completion_get - replaced with rpma_conn_get_cq and rpma_cq_get_wc,
  - rpma_conn_completion_wait - replaced with rpma_conn_get_cq and rpma_cq_wait,
  - rpma_conn_get_completion_fd - replaced with rpma_conn_get_cq and rpma_cq_get_fd.
```
so it should look like that: 
```
### Removed
- APIs:
  - rpma_conn_completion_get - replaced with rpma_conn_get_cq and rpma_cq_get_wc,
  - rpma_conn_completion_wait - replaced with rpma_conn_get_cq and rpma_cq_wait,
  - rpma_conn_get_completion_fd - replaced with rpma_conn_get_cq and rpma_cq_get_fd.

- Tools:
  - Benchmarking framework basing on bash scripts.

```

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1529#-MupQffSE0z4o8wzQgPQ:-MupQffSE0z4o8wzQgPR:bf9jp3m) (no related file):*
Replace `rpma_conn_completion_get` with `rpma_cq_get_wc` in the following lines:
```
./tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c:193:	/* configure mock for rpma_conn_completion_get() */
./tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c:161:	/* configure mock for rpma_conn_completion_get() */
```

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1529#-MupR4iz71uLT0pTrzf2:-MupR4j-E9kZEOJQrTEs:bv9ull9) (no related file):*
Replace `rpma_conn_completion_wait` with `rpma_cq_wait` in the following lines:
```
./tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c:187:	/* configure mocks for rpma_conn_completion_wait() */
./tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c:155:	/* configure mocks for rpma_conn_completion_wait() */
```

---

**Review by Patryk717 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1529)* status: 10 of 13 files reviewed, 3 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1529#-MupR4iz71uLT0pTrzf2:-MupWOEZ1l8-5DnOLqqZ:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Replace `rpma_conn_completion_wait` with `rpma_cq_wait` in the following lines:
```
./tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c:187:	/* configure mocks for rpma_conn_completion_wait() */
./tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c:155:	/* configure mocks for rpma_conn_completion_wait() */
```

</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1529#-MupPc438Ij1a26HyaSp:-MupWSss-VAgPzKUcUQp:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please add to the CHANGLOG under the first Removed:
```
- APIs:
  - rpma_conn_completion_get - replaced with rpma_conn_get_cq and rpma_cq_get_wc,
  - rpma_conn_completion_wait - replaced with rpma_conn_get_cq and rpma_cq_wait,
  - rpma_conn_get_completion_fd - replaced with rpma_conn_get_cq and rpma_cq_get_fd.
```
so it should look like that: 
```
### Removed
- APIs:
  - rpma_conn_completion_get - replaced with rpma_conn_get_cq and rpma_cq_get_wc,
  - rpma_conn_completion_wait - replaced with rpma_conn_get_cq and rpma_cq_wait,
  - rpma_conn_get_completion_fd - replaced with rpma_conn_get_cq and rpma_cq_get_fd.

- Tools:
  - Benchmarking framework basing on bash scripts.

```
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1529#-MupQffSE0z4o8wzQgPQ:-MupWToo6I46169RuivZ:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Replace `rpma_conn_completion_get` with `rpma_cq_get_wc` in the following lines:
```
./tests/integration/example-04-write-to-persistent/example-04-write-to-persistent.c:193:	/* configure mock for rpma_conn_completion_get() */
./tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c:161:	/* configure mock for rpma_conn_completion_get() */
```

</blockquote></details>

Done.

---
___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1529#-MukdR52EM3SsVFRdstY):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

common: remove deprecated API
</blockquote></details>

Done.
___
*[CHANGELOG.md, line 61 at r1](https://reviewable.io/reviews/pmem/rpma/1529#-Mukd6ao4s4IYgCKBnll:-MuoDybe6itvbT0Q6iui:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/da31cc6f0e5793ad6ba848612a5949f9ace407c1/CHANGELOG.md#L61)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

These lines should stay as are. Do not remove them.
</blockquote></details>

Done.
___
*[doc/manuals_3.txt, line 33 at r4](https://reviewable.io/reviews/pmem/rpma/1529#-Mup7GgW5jGSa384cgiZ:-MupHNcB2GHYaRWuYpyR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/da31cc6f0e5793ad6ba848612a5949f9ace407c1/doc/manuals_3.txt#L33)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why have you removed `rpma_cq_wait.3` ?
</blockquote></details>

Done.
___
*[tests/cmake/helpers.cmake, line 238 at r3](https://reviewable.io/reviews/pmem/rpma/1529#-MuoYyFTCIA4DEbPvxSW:-Muot4XM1jqs_ClPP6h_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/da31cc6f0e5793ad6ba848612a5949f9ace407c1/tests/cmake/helpers.cmake#L238)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please do not change this file at all.
</blockquote></details>

Done.
___
*[tests/integration/common/mocks.c, line 99 at r3](https://reviewable.io/reviews/pmem/rpma/1529#-MuoZVbR2C_4V03BDP0W:-Muou4Nr2kQ55BVLwi08:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/da31cc6f0e5793ad6ba848612a5949f9ace407c1/tests/integration/common/mocks.c#L99)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why have you removed that?
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1529)* status: all files reviewed, 1 unresolved discussion (waiting on @Patryk717)

___
*[CHANGELOG.md, line 21 at r8](https://reviewable.io/reviews/pmem/rpma/1529#-MupZUQL9NRTp8euSQUj:-MupZUQL9NRTp8euSQUk:b6fblsd) ([raw file](https://github.com/pmem/rpma/blob/23e951d11dee5170a07f63d71500d88c59323715/CHANGELOG.md#L21)):*
> ```Markdown
>   - rpma_conn_completion_wait - replaced with rpma_conn_get_cq and rpma_cq_wait,
>   - rpma_conn_get_completion_fd - replaced with rpma_conn_get_cq and rpma_cq_get_fd.
>   
> ```

Remove 3 spaces here (it should be an empty line)



_Code quote:_
```Markdown
···
```

**Review by ldorau — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1529#-:-MupZzKx0EhdaLgIRhkX:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @Patryk717)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1529#-:-Mupm9ep6kgse07iEz5-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1529#-:-MutGSgvBk9BhW75gTeb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1529)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1529)* status: all files reviewed, 1 unresolved discussion (waiting on @Patryk717)

___
*[CHANGELOG.md, line 18 at r9](https://reviewable.io/reviews/pmem/rpma/1529#-MutIZkxCpAq_Nw7TW1z:-MutIZky3Y3fASYs8Md1:b-v829sy) ([raw file](https://github.com/pmem/rpma/blob/85ff810e010f72efc2f7a149f76e1acaff8c7109/CHANGELOG.md#L18)):*
> ```Markdown
> ### Removed
> - APIs:
>   - rpma_conn_completion_get - replaced with rpma_conn_get_cq and rpma_cq_get_completion,
> ```

rpma_cq_get_wc



_Code quote:_
```Markdown
rpma_cq_get_completion
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1529)* status: all files reviewed, 2 unresolved discussions (waiting on @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1529#-MutLwpd0nFwdM6scpSS:-MutLwpd0nFwdM6scpST:bq9wo93) (no related file):*
Please update the master branch and rebase on the current master branch.

---

**Review by Patryk717 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1529)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @ldorau, @osalyk, and @Patryk717)

___
*[CHANGELOG.md, line 18 at r9](https://reviewable.io/reviews/pmem/rpma/1529#-MutIZkxCpAq_Nw7TW1z:-MutOkqc9VT10KizGtIB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/85ff810e010f72efc2f7a149f76e1acaff8c7109/CHANGELOG.md#L18)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

rpma_cq_get_wc
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1529)* status: all files reviewed, 1 unresolved discussion (waiting on @Patryk717)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1529)* status: all files reviewed, 3 unresolved discussions (waiting on @Patryk717)

___
*[CHANGELOG.md, line 18 at r9](https://reviewable.io/reviews/pmem/rpma/1529#-MutIZkxCpAq_Nw7TW1z:-MutQ4EG29PBvCu3rZBB:br7sr4m) ([raw file](https://github.com/pmem/rpma/blob/85ff810e010f72efc2f7a149f76e1acaff8c7109/CHANGELOG.md#L18)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet
___
*[CHANGELOG.md, line 59 at r10](https://reviewable.io/reviews/pmem/rpma/1529#-MutQB-_AxvCC4CAZ1kO:-MutQB-_AxvCC4CAZ1kP:b-wnu9zc) ([raw file](https://github.com/pmem/rpma/blob/da31cc6f0e5793ad6ba848612a5949f9ace407c1/CHANGELOG.md#L59)):*
> ```Markdown
> ### Deprecated
> - APIs:
>   - rpma_conn_completion_get - replaced with rpma_conn_get_cq and rpma_cq_get_completion,
> ```

It should stay as it was here



_Code quote:_
```Markdown
rpma_cq_get_completion,
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1529)* status: all files reviewed, 3 unresolved discussions (waiting on @Patryk717)

___
*[CHANGELOG.md, line 20 at r11](https://reviewable.io/reviews/pmem/rpma/1529#-MutjXRM7OQzI9D7oUmp:-MutjXRM7OQzI9D7oUmq:b7fg3o3) ([raw file](https://github.com/pmem/rpma/blob/3c1b93ebc55b7e9f66076fa099d5237e74dfd58e/CHANGELOG.md#L20)):*
> ```Markdown
>   - rpma_cq_get_completion - replaced with rpma_cq_get_wc
>   - struct rpma_completion - replaced with struct ibv_wc from libibverbs
>   - enum rpma_op - replaced with enum ibv_wc_opcode from libibverbs
> ```

This has to stay.



_Code quote:_
```Markdown
### Deprecated
- APIs:
  - rpma_cq_get_completion - replaced with rpma_cq_get_wc
  - struct rpma_completion - replaced with struct ibv_wc from libibverbs
  - enum rpma_op - replaced with enum ibv_wc_opcode from libibverbs
```
___
*[CHANGELOG.md, line 20 at r11](https://reviewable.io/reviews/pmem/rpma/1529#-MutjcYoED6ke5vsb4UU:-MutjcYoED6ke5vsb4UV:b-9oylsw) ([raw file](https://github.com/pmem/rpma/blob/a32e0143eb5af184866ee0ab7b35d0ecb9a34e75/CHANGELOG.md#L20)):*
> ```Markdown
>   - rpma_conn_completion_get - replaced with rpma_conn_get_cq and rpma_cq_get_wc,
>   - rpma_conn_completion_wait - replaced with rpma_conn_get_cq and rpma_cq_wait,
>   - rpma_conn_get_completion_fd - replaced with rpma_conn_get_cq and rpma_cq_get_fd.
> ```

... and this should be added.



_Code quote:_
```Markdown
### Removed
- APIs:
  - rpma_conn_completion_get - replaced with rpma_conn_get_cq and rpma_cq_get_wc,
  - rpma_conn_completion_wait - replaced with rpma_conn_get_cq and rpma_cq_wait,
  - rpma_conn_get_completion_fd - replaced with rpma_conn_get_cq and rpma_cq_get_fd.
```

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1529)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)

**Comment by grom72** [comment]
Fixs: #1212

**Pull request merged**
