### PR TITLE
test: add rpma_srq MT tests

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1986)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1986)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @grom72 and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1986#-N9kXiSZ0EwPSKoW8U2t:-N9kXiSZ0EwPSKoW8U2u:b-mk2kh9) (no related file):*
Documentation is missing.

___

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1986)* status: 3 of 8 files reviewed, 5 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`tests/drd.supp` line 468 at r1](https://reviewable.io/reviews/pmem/rpma/1986#-N9mbR9y6xWQbM3BBXRS:-N9mbR9y6xWQbM3BBXRT:b-qm33ae) ([raw file](https://github.com/pmem/rpma/blob/078f57116b57f95156ed56534316238c346412cb/tests/drd.supp#L468)):*
> ```
>    drd:ConflictingAccess
>    ...
>    fun:rpma_srq_delete
> ```

Is it valid for ``rpma_srq_new``?



_Code quote:_
```
rpma_srq_delete
```
___
*[`tests/drd.supp` line 495 at r1](https://reviewable.io/reviews/pmem/rpma/1986#-N9m_wav7vPHEfRYeM65:-N9m_wawBGBcGPHE7PGU:b3kre) ([raw file](https://github.com/pmem/rpma/blob/078f57116b57f95156ed56534316238c346412cb/tests/drd.supp#L495)):*
> ```
>    drd:CondErr
>    ...
>    fun:ibv_create_srq*
> ```

?



_Code quote:_
```
*
```
___
*[`tests/drd.supp` line 504 at r1](https://reviewable.io/reviews/pmem/rpma/1986#-N9m_yQ9EwVj3vaI9rfC:-N9m_yQ9EwVj3vaI9rfD:b3kre) ([raw file](https://github.com/pmem/rpma/blob/078f57116b57f95156ed56534316238c346412cb/tests/drd.supp#L504)):*
> ```
>    drd:MutexErr
>    ...
>    fun:ibv_create_srq*
> ```

?



_Code quote:_
```
*
```
___
*[`tests/helgrind.supp` line 465 at r1](https://reviewable.io/reviews/pmem/rpma/1986#-N9m_tsGAqB3m2YkN1Z9:-N9m_tsGAqB3m2YkN1ZA:b32vmt) ([raw file](https://github.com/pmem/rpma/blob/078f57116b57f95156ed56534316238c346412cb/tests/helgrind.supp#L465)):*
> ```
>    Helgrind:Race
>    ...
>    fun:ibv_create_srq@*
> ```

??



_Code quote:_
```
@*
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1986)* status: 4 of 8 files reviewed, 5 unresolved discussions (waiting on @grom72 and @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1986)* status: 4 of 8 files reviewed, 5 unresolved discussions (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1986#-N9kXiSZ0EwPSKoW8U2t:-N9oku0Z9dZyx0ZQ62qS:b-896fix) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Documentation is missing.
</blockquote></details>

Done.

___
___
*[`tests/drd.supp` line 468 at r1](https://reviewable.io/reviews/pmem/rpma/1986#-N9mbR9y6xWQbM3BBXRS:-N9oo2m8-4yQPWfeWPlH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/078f57116b57f95156ed56534316238c346412cb/tests/drd.supp#L468)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Is it valid for ``rpma_srq_new``?
</blockquote></details>

Done.
___
*[`tests/drd.supp` line 495 at r1](https://reviewable.io/reviews/pmem/rpma/1986#-N9m_wav7vPHEfRYeM65:-N9ooOnO145drGxnmV3o:byr5z6n) ([raw file](https://github.com/pmem/rpma/blob/078f57116b57f95156ed56534316238c346412cb/tests/drd.supp#L495)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

?
</blockquote></details>

fun:ibv_create_srq@@IBVERBS_1.1
___
*[`tests/drd.supp` line 504 at r1](https://reviewable.io/reviews/pmem/rpma/1986#-N9m_yQ9EwVj3vaI9rfC:-N9ooRSL7cUoAnq89nEc:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/078f57116b57f95156ed56534316238c346412cb/tests/drd.supp#L504)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

?
</blockquote></details>

.
___
*[`tests/helgrind.supp` line 465 at r1](https://reviewable.io/reviews/pmem/rpma/1986#-N9m_tsGAqB3m2YkN1Z9:-N9ooTE2E9pFnfEaRgZU:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/078f57116b57f95156ed56534316238c346412cb/tests/helgrind.supp#L465)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

??
</blockquote></details>

.

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1986)* status: 2 of 10 files reviewed, 1 unresolved discussion (waiting on @grom72 and @osalyk)

___
*[`THREAD_SAFETY.md` line 124 at r2](https://reviewable.io/reviews/pmem/rpma/1986#-N9pd3xq0TW8FZKUQNTQ:-N9pd3xq0TW8FZKUQNTR:b32vmt) ([raw file](https://github.com/pmem/rpma/blob/34ec300cf3e506a96f73030a4e922877e64f3965/THREAD_SAFETY.md#L124)):*
> ```Markdown
> - rpma_mr_reg
> - rpma_mr_dereg
> - rpma_srq_get_rcq
> ```

??



_Code quote:_
```Markdown
- rpma_srq_get_rcq
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1986)* status: 0 of 10 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`THREAD_SAFETY.md` line 124 at r2](https://reviewable.io/reviews/pmem/rpma/1986#-N9pd3xq0TW8FZKUQNTQ:-N9pie0xBfd6oc7EsJ4j:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/34ec300cf3e506a96f73030a4e922877e64f3965/THREAD_SAFETY.md#L124)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

??
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 4 of 8 files at r1, 2 of 4 files at r2, 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1986)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1986#-:-N9pqkIW9SQQyb-XuDLr:bnfp4nl)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1986)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 4 of 8 files at r1, 2 of 4 files at r2, 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1986)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`CHANGELOG.md` line 49 at r3](https://reviewable.io/reviews/pmem/rpma/1986#-NA36coc85b7lA0w00U7:-NA36coc85b7lA0w00U8:b-s5f9s1) ([raw file](https://github.com/pmem/rpma/blob/e24b3b79e4eca369a489c281ae9326d21609b522/CHANGELOG.md#L49)):*
> ```Markdown
>   - rpma_peer_cfg_set_direct_write_to_pmem
>   - rpma_srq_get_rcq
>   - rpma_srq_delete
> ```

`delete` should be before `get`



_Code quote:_
```Markdown
  - rpma_srq_get_rcq
  - rpma_srq_delete
```
___
*[`tests/multithreaded/srq/CMakeLists.txt` line 3 at r3](https://reviewable.io/reviews/pmem/rpma/1986#-NA37D0L2GYF839PRY_-:-NA37D0L2GYF839PRY_0:b-6s6ok7) ([raw file](https://github.com/pmem/rpma/blob/e24b3b79e4eca369a489c281ae9326d21609b522/tests/multithreaded/srq/CMakeLists.txt#L3)):*
> ```CMake
> #
> # SPDX-License-Identifier: BSD-3-Clause
> # Copyright 2021-2022, Intel Corporation
> ```

2022 only



_Code quote:_
```CMake
2021-2022
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1986)* status: 9 of 10 files reviewed, 4 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`tests/multithreaded/srq/rpma_srq_delete.c` line 50 at r3](https://reviewable.io/reviews/pmem/rpma/1986#-NA38d3NDiXnJRX-Z4iu:-NA38d3NDiXnJRX-Z4iv:b-dul48n) ([raw file](https://github.com/pmem/rpma/blob/e24b3b79e4eca369a489c281ae9326d21609b522/tests/multithreaded/srq/rpma_srq_delete.c#L50)):*
> ```C
> 	int ret;
> 	struct prestate *pr = (struct prestate *)prestate;
> 	struct state *st = (struct state *)calloc(1, sizeof(struct state));
> ```

```c
	struct prestate *pr = (struct prestate *)prestate;
	int ret;

	struct state *st = (struct state *)calloc(1, sizeof(struct state));
	...
```



_Code quote:_
```C
	int ret;
	struct prestate *pr = (struct prestate *)prestate;
	struct state *st = (struct state *)calloc(1, sizeof(struct state));
```
___
*[`tests/multithreaded/srq/rpma_srq_delete.c` line 58 at r3](https://reviewable.io/reviews/pmem/rpma/1986#-NA38sTK9M3yd6-Jz3AW:-NA38sTK9M3yd6-Jz3AX:b-153h27) ([raw file](https://github.com/pmem/rpma/blob/e24b3b79e4eca369a489c281ae9326d21609b522/tests/multithreaded/srq/rpma_srq_delete.c#L58)):*
> ```C
> 	MTT_PORT_INIT;
> 	MTT_PORT_SET(pr->port, id);
> 	if ((ret = rpma_srq_new(pr->peer, NULL, &st->srq)))
> ```

One empty line in between:
```c
	MTT_PORT_SET(pr->port, id);

	if ((ret = rpma_srq_new(pr->peer, NULL, &st->srq)))
```



_Code quote:_
```C
	MTT_PORT_SET(pr->port, id);
	if ((ret = rpma_srq_new(pr->peer, NULL, &st->srq)))
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1986)* status: 9 of 10 files reviewed, 9 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`tests/multithreaded/srq/rpma_srq_get_rcq.c` line 21 at r3](https://reviewable.io/reviews/pmem/rpma/1986#-NA39k-M0AIFzNWcbe9_:-NA39k-M0AIFzNWcbe9a:b-s3hmk9) ([raw file](https://github.com/pmem/rpma/blob/e24b3b79e4eca369a489c281ae9326d21609b522/tests/multithreaded/srq/rpma_srq_get_rcq.c#L21)):*
> ```C
> 
> struct state {
> 	struct rpma_cq *rcq;
> ```

Not needed.



_Code quote:_
```C
struct state {
	struct rpma_cq *rcq;
};
```
___
*[`tests/multithreaded/srq/rpma_srq_get_rcq.c` line 52 at r3](https://reviewable.io/reviews/pmem/rpma/1986#-NA39vx97HT1-vqFLY5k:-NA39vx97HT1-vqFLY5l:b-s3hmk9) ([raw file](https://github.com/pmem/rpma/blob/e24b3b79e4eca369a489c281ae9326d21609b522/tests/multithreaded/srq/rpma_srq_get_rcq.c#L52)):*
> ```C
> /*
>  * init -- allocate state
>  */
> ```

Not needed.



_Code quote:_
```C
/*
 * init -- allocate state
 */
void
init(unsigned id, void *prestate, void **state_ptr,
		struct mtt_result *tr)
```
___
*[`tests/multithreaded/srq/rpma_srq_get_rcq.c` line 78 at r3](https://reviewable.io/reviews/pmem/rpma/1986#-NA3A-TDCfDy76taeAuG:-NA3A-TDCfDy76taeAuH:b-t4m43m) ([raw file](https://github.com/pmem/rpma/blob/e24b3b79e4eca369a489c281ae9326d21609b522/tests/multithreaded/srq/rpma_srq_get_rcq.c#L78)):*
> ```C
> 	MTT_PORT_INIT;
> 	MTT_PORT_SET(pr->port, id);
> 	if ((ret = rpma_srq_get_rcq(pr->srq, &st->rcq)))
> ```

Use a local variable instead.



_Code quote:_
```C
&st->rcq
```
___
*[`tests/multithreaded/srq/rpma_srq_get_rcq.c` line 86 at r3](https://reviewable.io/reviews/pmem/rpma/1986#-NA39tgKBXyRQfLxTHmF:-NA39tgKBXyRQfLxTHmG:b-s3hmk9) ([raw file](https://github.com/pmem/rpma/blob/e24b3b79e4eca369a489c281ae9326d21609b522/tests/multithreaded/srq/rpma_srq_get_rcq.c#L86)):*
> ```C
>  */
> static void
> fini(unsigned id, void *prestate, void **state_ptr,
> ```

Not needed.



_Code quote:_
```C
/*
 * fini -- free the state
 */
static void
fini(unsigned id, void *prestate, void **state_ptr,
		struct mtt_result *tr)
```
___
*[`tests/multithreaded/srq/rpma_srq_new.c` line 43 at r3](https://reviewable.io/reviews/pmem/rpma/1986#-NA39SMhA2XuLLbed2Uj:-NA39SMhA2XuLLbed2Uk:bvbs65w) ([raw file](https://github.com/pmem/rpma/blob/e24b3b79e4eca369a489c281ae9326d21609b522/tests/multithreaded/srq/rpma_srq_new.c#L43)):*
> ```C
> 
> /*
>  * init -- allocate state
> ```

allocate a state



_Code quote:_
```C
allocate state
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1986)* status: all files reviewed, 10 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`tests/multithreaded/srq/rpma_srq_new.c` line 69 at r3](https://reviewable.io/reviews/pmem/rpma/1986#-NA3AVO-4ARL8wqn6adX:-NA3AVO-4ARL8wqn6adY:bvn7a6e) ([raw file](https://github.com/pmem/rpma/blob/e24b3b79e4eca369a489c281ae9326d21609b522/tests/multithreaded/srq/rpma_srq_new.c#L69)):*
> ```C
> 	MTT_PORT_INIT;
> 	MTT_PORT_SET(pr->port, id);
> 	if ((ret = rpma_srq_new(pr->peer, NULL, &st->srq)))
> ```

Add one empty line in between.



_Code quote:_
```C
	MTT_PORT_SET(pr->port, id);
	if ((ret = rpma_srq_new(pr->peer, NULL, &st->srq)))
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1986)* status: all files reviewed, 11 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`tests/multithreaded/srq/rpma_srq_get_rcq.c` line 78 at r3](https://reviewable.io/reviews/pmem/rpma/1986#-NA3Assk-fi5WhBGjBfx:-NA3Assk-fi5WhBGjBfy:bvn7a6e) ([raw file](https://github.com/pmem/rpma/blob/e24b3b79e4eca369a489c281ae9326d21609b522/tests/multithreaded/srq/rpma_srq_get_rcq.c#L78)):*
> ```C
> 	MTT_PORT_INIT;
> 	MTT_PORT_SET(pr->port, id);
> 	if ((ret = rpma_srq_get_rcq(pr->srq, &st->rcq)))
> ```

Add one empty line in between.



_Code quote:_
```C
	MTT_PORT_SET(pr->port, id);
	if ((ret = rpma_srq_get_rcq(pr->srq, &st->rcq)))
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1986)* status: 5 of 10 files reviewed, 11 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`CHANGELOG.md` line 49 at r3](https://reviewable.io/reviews/pmem/rpma/1986#-NA36coc85b7lA0w00U7:-NA3QMzo2wGUxDArj9S5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e24b3b79e4eca369a489c281ae9326d21609b522/CHANGELOG.md#L49)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`delete` should be before `get`
</blockquote></details>

Done.
___
*[`tests/multithreaded/srq/CMakeLists.txt` line 3 at r3](https://reviewable.io/reviews/pmem/rpma/1986#-NA37D0L2GYF839PRY_-:-NA3QRMx6AdZX22iFbzm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e24b3b79e4eca369a489c281ae9326d21609b522/tests/multithreaded/srq/CMakeLists.txt#L3)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

2022 only
</blockquote></details>

Done.
___
*[`tests/multithreaded/srq/rpma_srq_delete.c` line 50 at r3](https://reviewable.io/reviews/pmem/rpma/1986#-NA38d3NDiXnJRX-Z4iu:-NA3QaN22tMX2R691Bq1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e24b3b79e4eca369a489c281ae9326d21609b522/tests/multithreaded/srq/rpma_srq_delete.c#L50)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```c
	struct prestate *pr = (struct prestate *)prestate;
	int ret;

	struct state *st = (struct state *)calloc(1, sizeof(struct state));
	...
```
</blockquote></details>

Done.
___
*[`tests/multithreaded/srq/rpma_srq_delete.c` line 58 at r3](https://reviewable.io/reviews/pmem/rpma/1986#-NA38sTK9M3yd6-Jz3AW:-NA3QcPz-Nl5bdvUw3zX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e24b3b79e4eca369a489c281ae9326d21609b522/tests/multithreaded/srq/rpma_srq_delete.c#L58)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

One empty line in between:
```c
	MTT_PORT_SET(pr->port, id);

	if ((ret = rpma_srq_new(pr->peer, NULL, &st->srq)))
```

</blockquote></details>

Done.
___
*[`tests/multithreaded/srq/rpma_srq_get_rcq.c` line 21 at r3](https://reviewable.io/reviews/pmem/rpma/1986#-NA39k-M0AIFzNWcbe9_:-NA3Qdk1BxJfimWmITSa:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e24b3b79e4eca369a489c281ae9326d21609b522/tests/multithreaded/srq/rpma_srq_get_rcq.c#L21)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not needed.
</blockquote></details>

Done.
___
*[`tests/multithreaded/srq/rpma_srq_get_rcq.c` line 52 at r3](https://reviewable.io/reviews/pmem/rpma/1986#-NA39vx97HT1-vqFLY5k:-NA3Q3BT15qEnYosEpxM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e24b3b79e4eca369a489c281ae9326d21609b522/tests/multithreaded/srq/rpma_srq_get_rcq.c#L52)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not needed.
</blockquote></details>

Done.
___
*[`tests/multithreaded/srq/rpma_srq_get_rcq.c` line 78 at r3](https://reviewable.io/reviews/pmem/rpma/1986#-NA3A-TDCfDy76taeAuG:-NA3Q3yI8eZVZb1xddxf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e24b3b79e4eca369a489c281ae9326d21609b522/tests/multithreaded/srq/rpma_srq_get_rcq.c#L78)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Use a local variable instead.
</blockquote></details>

Done.
___
*[`tests/multithreaded/srq/rpma_srq_get_rcq.c` line 78 at r3](https://reviewable.io/reviews/pmem/rpma/1986#-NA3Assk-fi5WhBGjBfx:-NA3Q8KyD7LVY2iYtpEj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e24b3b79e4eca369a489c281ae9326d21609b522/tests/multithreaded/srq/rpma_srq_get_rcq.c#L78)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Add one empty line in between.
</blockquote></details>

Done.
___
*[`tests/multithreaded/srq/rpma_srq_get_rcq.c` line 86 at r3](https://reviewable.io/reviews/pmem/rpma/1986#-NA39tgKBXyRQfLxTHmF:-NA3Q9Ur9oHaubcbTLgq:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e24b3b79e4eca369a489c281ae9326d21609b522/tests/multithreaded/srq/rpma_srq_get_rcq.c#L86)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not needed.
</blockquote></details>

Done.
___
*[`tests/multithreaded/srq/rpma_srq_new.c` line 43 at r3](https://reviewable.io/reviews/pmem/rpma/1986#-NA39SMhA2XuLLbed2Uj:-NA3QDRb0n4UDIekMWTd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e24b3b79e4eca369a489c281ae9326d21609b522/tests/multithreaded/srq/rpma_srq_new.c#L43)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

allocate a state
</blockquote></details>

Done.
___
*[`tests/multithreaded/srq/rpma_srq_new.c` line 69 at r3](https://reviewable.io/reviews/pmem/rpma/1986#-NA3AVO-4ARL8wqn6adX:-NA3QGch7_bZPjHHqpz1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e24b3b79e4eca369a489c281ae9326d21609b522/tests/multithreaded/srq/rpma_srq_new.c#L69)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Add one empty line in between.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1986)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
