### PR TITLE
tools: add remote_command_pre/post

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1427)

### CODE REVIEW

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1427)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1427)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @haichangsi and @ldorau)

**Review by grom72 — COMMENTED** [review]
:goat:

> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1427#-:-Mr2vmLh4muYSUwHETR7:bdycps0)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1427#-Mr2vWYO-41Iv0oDlhQ3:-Mr2vWYO-41Iv0oDlhQ4:bpi22hf) (no related file):*
I think we need a superclass (abstract) Runner with all common code there.  But this could be added separately.

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1427)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/lib/benchmark/runner/common.py, line 77 at r1](https://reviewable.io/reviews/pmem/rpma/1427#-Mr3BHyw3hlW9CefuMwl:-Mr3BHyw3hlW9CefuMwm:b70yl9y) ([raw file](https://github.com/pmem/rpma/blob/4eb84c63071783eebf3ab3489dd349adb0bfaffd/tools/perf/lib/benchmark/runner/common.py#L77)):*
> ```
>         cmd = cmd + " &"
>         run_pre = RemoteCmd.run_sync(config, cmd, raise_on_error=True)
>         # XXX - by '&' exit_status is always 0
> ```

Why don't you use `run_async()` ?
___
*[tools/perf/lib/benchmark/runner/common.py, line 79 at r1](https://reviewable.io/reviews/pmem/rpma/1427#-Mr3AoGs6PyIWW-jMzRr:-Mr3AoGt7veGIipOgi7Y:bnraeev) ([raw file](https://github.com/pmem/rpma/blob/4eb84c63071783eebf3ab3489dd349adb0bfaffd/tools/perf/lib/benchmark/runner/common.py#L79)):*
> ```
> run_pre.stderr.readline()
> ```

It does not work for me.

That works: `run_pre.read().decode().strip()`

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1427)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[tools/perf/lib/benchmark/runner/common.py, line 77 at r1](https://reviewable.io/reviews/pmem/rpma/1427#-Mr3BHyw3hlW9CefuMwl:-Mr3HVSB3Jth8MFWjcLr:bvz51ra) ([raw file](https://github.com/pmem/rpma/blob/4eb84c63071783eebf3ab3489dd349adb0bfaffd/tools/perf/lib/benchmark/runner/common.py#L77)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>         cmd = cmd + " &"
>         run_pre = RemoteCmd.run_sync(config, cmd, raise_on_error=True)
>         # XXX - by '&' exit_status is always 0
> ```

Why don't you use `run_async()` ?
</blockquote></details>

I guess we have to wait for the command completion.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1427)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[tools/perf/lib/benchmark/runner/common.py, line 77 at r1](https://reviewable.io/reviews/pmem/rpma/1427#-Mr3BHyw3hlW9CefuMwl:-Mr6EzPhCfvAegTNO1Uo:b-7qnkuc) ([raw file](https://github.com/pmem/rpma/blob/4eb84c63071783eebf3ab3489dd349adb0bfaffd/tools/perf/lib/benchmark/runner/common.py#L77)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I guess we have to wait for the command completion.
</blockquote></details>

To stop the measurement we need to send another command.
___
*[tools/perf/lib/benchmark/runner/common.py, line 79 at r1](https://reviewable.io/reviews/pmem/rpma/1427#-Mr3AoGs6PyIWW-jMzRr:-Mr6JoSyC7yNvyhGkPc_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4eb84c63071783eebf3ab3489dd349adb0bfaffd/tools/perf/lib/benchmark/runner/common.py#L79)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> run_pre.stderr.readline()
> ```

It does not work for me.

That works: `run_pre.read().decode().strip()`
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1427)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau and @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1427)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[tools/perf/lib/benchmark/runner/common.py, line 77 at r1](https://reviewable.io/reviews/pmem/rpma/1427#-Mr3BHyw3hlW9CefuMwl:-Mr6eGT-DxNgcXkNQm7C:bkiz4f1) ([raw file](https://github.com/pmem/rpma/blob/4eb84c63071783eebf3ab3489dd349adb0bfaffd/tools/perf/lib/benchmark/runner/common.py#L77)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

To stop the measurement we need to send another command.
</blockquote></details>

Yes, it's true and it's not a hindrance at all - you may do it like that:
https://github.com/ldorau/rpma/tree/review-osalyk-pre_post_command
```python
def run_pre_command(config, oneseries, x_value):
    """run pre command"""
    run_pre = None
    if 'REMOTE_CMD_PRE' in config and config['REMOTE_CMD_PRE'] != '':
        cmd = prepare_cmd(config, oneseries, config['REMOTE_CMD_PRE'], x_value)
        run_pre = RemoteCmd.run_async(config, cmd)
    return run_pre

def __wait_for_pre_command(pre_command, raise_on_error = True):
    if pre_command is None:
        return
    print('Waiting for pre-command ...')
    pre_command.wait()
    if pre_command.exit_status == 0:
        return
    print('--- pre-command\'s stderr: ---')
    stderr_msg = pre_command.stderr.read().decode().strip()
    if raise_on_error:
        raise ValueError(stderr_msg)
    print(stderr_msg)
    print('--- end of pre-command\'s stderr ---\n')

def run_post_command(config, oneseries, pre_command = None):
    """run post command and wait for the end of the pre command"""
    if 'REMOTE_CMD_POST' in config and config['REMOTE_CMD_POST'] != '':
        cmd = prepare_cmd(config, oneseries, config['REMOTE_CMD_POST'])
        try:
            RemoteCmd.run_sync(config, cmd, raise_on_error=True)
        except:
            print('Post-command failed!')
            __wait_for_pre_command(pre_command, raise_on_error = False)
            print('--- post-command\'s output: ---')
            raise
    __wait_for_pre_command(pre_command)

```
___
*[tools/perf/lib/benchmark/runner/common.py, line 57 at r2](https://reviewable.io/reviews/pmem/rpma/1427#-Mr6g3jPAzGOAf84sRcl:-Mr6g3jPAzGOAf84sRcm:bqan0iq) ([raw file](https://github.com/pmem/rpma/blob/7f75ad211ae89dc36432ee0501896ec5ef24088d/tools/perf/lib/benchmark/runner/common.py#L57)):*
> ```
> x_value = None
> ```

`x_value = ''`  

or

`and x_value:` below.

(please use the same:`''` or `None` in both places)
___
*[tools/perf/lib/benchmark/runner/common.py, line 65 at r2](https://reviewable.io/reviews/pmem/rpma/1427#-Mr6gJHM5d7u32EoLoHs:-Mr6gJHM5d7u32EoLoHt:bf69261) ([raw file](https://github.com/pmem/rpma/blob/7f75ad211ae89dc36432ee0501896ec5ef24088d/tools/perf/lib/benchmark/runner/common.py#L65)):*
> ```
> and x_value != '':
> ```

`and x_value:`

(please use the same:`''` or `None` in both places)
___
*[tools/perf/lib/benchmark/runner/common.py, line 79 at r2](https://reviewable.io/reviews/pmem/rpma/1427#-Mr6ehS72SdWJpXkRd0o:-Mr6ehS72SdWJpXkRd0p:btu85vd) ([raw file](https://github.com/pmem/rpma/blob/7f75ad211ae89dc36432ee0501896ec5ef24088d/tools/perf/lib/benchmark/runner/common.py#L79)):*
> ```
>         # XXX - by '&' exit_status is always 0
>         if run_pre.stderr.read().decode().strip():
>             raise ValueError(run_pre.stderr.read().decode().strip())
> ```

This code will never be called if you use `&`

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1427)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1427#-Mr2vWYO-41Iv0oDlhQ3:-Mr6hAKL7dABLXvJKn2p:bkl9qun) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I think we need a superclass (abstract) Runner with all common code there.  But this could be added separately.
</blockquote></details>

Yes, we can (https://github.com/pmem/rpma/issues/1436)

---

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1427)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[tools/perf/lib/benchmark/runner/common.py, line 77 at r1](https://reviewable.io/reviews/pmem/rpma/1427#-Mr3BHyw3hlW9CefuMwl:-Mr6lNbL2dbOTqk4hQAU:b-5czbsz) ([raw file](https://github.com/pmem/rpma/blob/4eb84c63071783eebf3ab3489dd349adb0bfaffd/tools/perf/lib/benchmark/runner/common.py#L77)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, it's true and it's not a hindrance at all - you may do it like that:
https://github.com/ldorau/rpma/tree/review-osalyk-pre_post_command
```python
def run_pre_command(config, oneseries, x_value):
    """run pre command"""
    run_pre = None
    if 'REMOTE_CMD_PRE' in config and config['REMOTE_CMD_PRE'] != '':
        cmd = prepare_cmd(config, oneseries, config['REMOTE_CMD_PRE'], x_value)
        run_pre = RemoteCmd.run_async(config, cmd)
    return run_pre

def __wait_for_pre_command(pre_command, raise_on_error = True):
    if pre_command is None:
        return
    print('Waiting for pre-command ...')
    pre_command.wait()
    if pre_command.exit_status == 0:
        return
    print('--- pre-command\'s stderr: ---')
    stderr_msg = pre_command.stderr.read().decode().strip()
    if raise_on_error:
        raise ValueError(stderr_msg)
    print(stderr_msg)
    print('--- end of pre-command\'s stderr ---\n')

def run_post_command(config, oneseries, pre_command = None):
    """run post command and wait for the end of the pre command"""
    if 'REMOTE_CMD_POST' in config and config['REMOTE_CMD_POST'] != '':
        cmd = prepare_cmd(config, oneseries, config['REMOTE_CMD_POST'])
        try:
            RemoteCmd.run_sync(config, cmd, raise_on_error=True)
        except:
            print('Post-command failed!')
            __wait_for_pre_command(pre_command, raise_on_error = False)
            print('--- post-command\'s output: ---')
            raise
    __wait_for_pre_command(pre_command)

```
</blockquote></details>

But as I understand we have to wait with the core benchmark run until pre command is finished
And if pre-command is used for something longer then it is pre-command responsibility to ensure asynchronous operation i.e. rune sth in a background

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1427)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/lib/benchmark/runner/common.py, line 77 at r1](https://reviewable.io/reviews/pmem/rpma/1427#-Mr3BHyw3hlW9CefuMwl:-Mr6mqTc6PSK_fOEN1-s:b-bweey8) ([raw file](https://github.com/pmem/rpma/blob/4eb84c63071783eebf3ab3489dd349adb0bfaffd/tools/perf/lib/benchmark/runner/common.py#L77)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

But as I understand we have to wait with the core benchmark run until pre command is finished
And if pre-command is used for something longer then it is pre-command responsibility to ensure asynchronous operation i.e. rune sth in a background
</blockquote></details>

Yes, you are right. That's OK.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1427)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/lib/benchmark/runner/common.py, line 79 at r2](https://reviewable.io/reviews/pmem/rpma/1427#-Mr6ehS72SdWJpXkRd0o:-Mr6nooQAjUAET0r_KbV:b-5gt3zw) ([raw file](https://github.com/pmem/rpma/blob/7f75ad211ae89dc36432ee0501896ec5ef24088d/tools/perf/lib/benchmark/runner/common.py#L79)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>         # XXX - by '&' exit_status is always 0
>         if run_pre.stderr.read().decode().strip():
>             raise ValueError(run_pre.stderr.read().decode().strip())
> ```

This code will never be called if you use `&`
</blockquote></details>

... so it can (should?) be removed ...

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1427)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/lib/benchmark/runner/common.py, line 79 at r2](https://reviewable.io/reviews/pmem/rpma/1427#-Mr6ehS72SdWJpXkRd0o:-Mr7bNGoB0VdgsJufCcT:b6kd1y2) ([raw file](https://github.com/pmem/rpma/blob/7f75ad211ae89dc36432ee0501896ec5ef24088d/tools/perf/lib/benchmark/runner/common.py#L79)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

... so it can (should?) be removed ...
</blockquote></details>

If it sometimes prints something it can stay ;-)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1427)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[tools/perf/lib/benchmark/runner/common.py, line 57 at r2](https://reviewable.io/reviews/pmem/rpma/1427#-Mr6g3jPAzGOAf84sRcl:-MrMadzt9FjIzBwTPnip:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7f75ad211ae89dc36432ee0501896ec5ef24088d/tools/perf/lib/benchmark/runner/common.py#L57)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> x_value = None
> ```

`x_value = ''`  

or

`and x_value:` below.

(please use the same:`''` or `None` in both places)

</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/runner/common.py, line 65 at r2](https://reviewable.io/reviews/pmem/rpma/1427#-Mr6gJHM5d7u32EoLoHs:-MrMahlj6WT1JPzrwQT8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7f75ad211ae89dc36432ee0501896ec5ef24088d/tools/perf/lib/benchmark/runner/common.py#L65)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> and x_value != '':
> ```

`and x_value:`

(please use the same:`''` or `None` in both places)
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1427)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1427)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/lib/remote_cmd.py, line 20 at r5](https://reviewable.io/reviews/pmem/rpma/1427#-MrMx2F11HrJNDUq_-kA:-MrMx2F11HrJNDUq_-kB:b-ikr81j) ([raw file](https://github.com/pmem/rpma/blob/6d7dd71f4bfbd2cf0406e56fe75193036026f4ed/tools/perf/lib/remote_cmd.py#L20)):*
> ```Python
>     """run a command on a remote node over SSH"""
> 
>     def __init__(self, ssh_client, stdout, stderr):
> ```

```def __init__(self, ssh_client, stdout, stderr, exec_stderr, exist_status = None)```

Without that, we are not able to use RemoteCmd in unit tests
See the second comment below.



_Suggestion:_
```Python
 def __init__(self, ssh_client, stdout, stderr, exec_stderr)
```
___
*[tools/perf/lib/remote_cmd.py, line 21 at r5](https://reviewable.io/reviews/pmem/rpma/1427#-MrMxJ88689EgxPKEjIp:-MrMxJ88689EgxPKEjIq:b-d9h2q5) ([raw file](https://github.com/pmem/rpma/blob/6d7dd71f4bfbd2cf0406e56fe75193036026f4ed/tools/perf/lib/remote_cmd.py#L21)):*
> ```Python
> 
>     def __init__(self, ssh_client, stdout, stderr):
>         self.ssh_client = ssh_client
> ```

```self.__ssh_client```

Please use double underscore for all private members



_Code quote:_
```Python
self.ssh_client
```
___
*[tools/perf/lib/remote_cmd.py, line 24 at r5](https://reviewable.io/reviews/pmem/rpma/1427#-MrMxDn75KZiEDKt22Zp:-MrMxDn75KZiEDKt22Zq:b-2sdfcy) ([raw file](https://github.com/pmem/rpma/blob/6d7dd71f4bfbd2cf0406e56fe75193036026f4ed/tools/perf/lib/remote_cmd.py#L24)):*
> ```Python
>         self.stdout = stdout
>         self.stderr = stderr
>         self.exit_status = None
> ```

``` self.exit_status = exit_status```

Without that, we are not able to use RemoteCmd in unit tests



_Code quote:_
```Python
 self.exit_status = None
```
___
*[tools/perf/lib/benchmark/runner/common.py, line 65 at r2](https://reviewable.io/reviews/pmem/rpma/1427#-Mr6gJHM5d7u32EoLoHs:-MrMxqk9B2zla7VE8F0P:b-pglpmj) ([raw file](https://github.com/pmem/rpma/blob/7f75ad211ae89dc36432ee0501896ec5ef24088d/tools/perf/lib/benchmark/runner/common.py#L65)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Why does ```''``` win? ```None``` is more meaningful, IMHO

**Review by grom72 — COMMENTED** [review]
> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1427)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1427)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/lib/remote_cmd.py, line 20 at r5](https://reviewable.io/reviews/pmem/rpma/1427#-MrMx2F11HrJNDUq_-kA:-MrN8BVmAlzfnkyuLEZY:b32v57) ([raw file](https://github.com/pmem/rpma/blob/6d7dd71f4bfbd2cf0406e56fe75193036026f4ed/tools/perf/lib/remote_cmd.py#L20)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```def __init__(self, ssh_client, stdout, stderr, exec_stderr, exist_status = None)```

Without that, we are not able to use RemoteCmd in unit tests
See the second comment below.
</blockquote></details>

+1
___
*[tools/perf/lib/remote_cmd.py, line 21 at r5](https://reviewable.io/reviews/pmem/rpma/1427#-MrMxJ88689EgxPKEjIp:-MrN8CHHE2Zwikqx1_ei:b32v57) ([raw file](https://github.com/pmem/rpma/blob/6d7dd71f4bfbd2cf0406e56fe75193036026f4ed/tools/perf/lib/remote_cmd.py#L21)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```self.__ssh_client```

Please use double underscore for all private members

</blockquote></details>

+1
___
*[tools/perf/lib/remote_cmd.py, line 24 at r5](https://reviewable.io/reviews/pmem/rpma/1427#-MrMxDn75KZiEDKt22Zp:-MrN890fBn-FE5MQIBxj:b32v57) ([raw file](https://github.com/pmem/rpma/blob/6d7dd71f4bfbd2cf0406e56fe75193036026f4ed/tools/perf/lib/remote_cmd.py#L24)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

``` self.exit_status = exit_status```

Without that, we are not able to use RemoteCmd in unit tests
</blockquote></details>

+1

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1427)* status: 3 of 4 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/lib/benchmark/runner/common.py, line 65 at r2](https://reviewable.io/reviews/pmem/rpma/1427#-Mr6gJHM5d7u32EoLoHs:-MrN8G4nBCjqzxcbGyX_:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/7f75ad211ae89dc36432ee0501896ec5ef24088d/tools/perf/lib/benchmark/runner/common.py#L65)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Why does ```''``` win? ```None``` is more meaningful, IMHO
</blockquote></details>

Done
___
*[tools/perf/lib/remote_cmd.py, line 20 at r5](https://reviewable.io/reviews/pmem/rpma/1427#-MrMx2F11HrJNDUq_-kA:-MrN7ui8EwHJz29RBFgr:bmgwnj8) ([raw file](https://github.com/pmem/rpma/blob/6d7dd71f4bfbd2cf0406e56fe75193036026f4ed/tools/perf/lib/remote_cmd.py#L20)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```def __init__(self, ssh_client, stdout, stderr, exec_stderr, exist_status = None)```

Without that, we are not able to use RemoteCmd in unit tests
See the second comment below.
</blockquote></details>

Is a change to another PR
___
*[tools/perf/lib/remote_cmd.py, line 21 at r5](https://reviewable.io/reviews/pmem/rpma/1427#-MrMxJ88689EgxPKEjIp:-MrN7z2047rD0St49GNb:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/6d7dd71f4bfbd2cf0406e56fe75193036026f4ed/tools/perf/lib/remote_cmd.py#L21)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```self.__ssh_client```

Please use double underscore for all private members

</blockquote></details>

.
___
*[tools/perf/lib/remote_cmd.py, line 24 at r5](https://reviewable.io/reviews/pmem/rpma/1427#-MrMxDn75KZiEDKt22Zp:-MrN8-l_BsdYf_S8WW30:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/6d7dd71f4bfbd2cf0406e56fe75193036026f4ed/tools/perf/lib/remote_cmd.py#L24)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

``` self.exit_status = exit_status```

Without that, we are not able to use RemoteCmd in unit tests
</blockquote></details>

.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1427)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[tools/perf/lib/remote_cmd.py, line 20 at r5](https://reviewable.io/reviews/pmem/rpma/1427#-MrMx2F11HrJNDUq_-kA:-MrN8_0m5a95Glioq9f7:b2sinjv) ([raw file](https://github.com/pmem/rpma/blob/6d7dd71f4bfbd2cf0406e56fe75193036026f4ed/tools/perf/lib/remote_cmd.py#L20)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Is a change to another PR
</blockquote></details>

Yes, in a separate PR
___
*[tools/perf/lib/remote_cmd.py, line 21 at r5](https://reviewable.io/reviews/pmem/rpma/1427#-MrMxJ88689EgxPKEjIp:-MrN8epp6qdtgBvYA47C:b2sinjv) ([raw file](https://github.com/pmem/rpma/blob/6d7dd71f4bfbd2cf0406e56fe75193036026f4ed/tools/perf/lib/remote_cmd.py#L21)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Yes, in a separate PR
___
*[tools/perf/lib/remote_cmd.py, line 24 at r5](https://reviewable.io/reviews/pmem/rpma/1427#-MrMxDn75KZiEDKt22Zp:-MrN8g9D49tiVVv2eRx6:b2sinjv) ([raw file](https://github.com/pmem/rpma/blob/6d7dd71f4bfbd2cf0406e56fe75193036026f4ed/tools/perf/lib/remote_cmd.py#L24)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Yes, in a separate PR

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1427#-:-MrN9ByH-MLtfXkTNF18:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1427#-:-MrNCPf8B_bp__Dqf_0I:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1427)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
