### PR TITLE
common: add automatic update of man pages in the pmem.github.io repo

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1574)

### CODE REVIEW

**Comment by ldorau** [comment]
@lukaszstolarczuk please review

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1574#-:-MvTnvbl0BhiEAStJD_K:bg7igkv)* status: 0 of 2 files reviewed, all discussions resolved

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1574)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @haichangsi, @ldorau, and @lukaszstolarczuk)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1574)* status: 0 of 4 files reviewed, 1 unresolved discussion (waiting on @haichangsi, @ldorau, and @lukaszstolarczuk)

___
*[utils/docker/run-doc-update.sh, line 9 at r1](https://reviewable.io/reviews/pmem/rpma/1574#-MvTsqBf1U_q8HqiAlEl:-MvXNCdzAUKDa2vxQdau:b-qbs159) ([raw file](https://github.com/pmem/rpma/blob/e42f9c9e8a9adbf43939b7a8671ca8be358c3175/utils/docker/run-doc-update.sh#L9)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'm not sure if you have to set this variable up, it should already be set in CI (https://github.com/pmem/rpma/blob/master/utils/docker/run-build.sh#L24-L27)

Of course unless you want to run this script locally
</blockquote></details>

1) I want to be sure it has the correct value assigned - it is not a big cost to set it again anyway.
2) Yes, I sometimes run it locally
___
*[utils/docker/run-doc-update.sh, line 15 at r1](https://reviewable.io/reviews/pmem/rpma/1574#-MvTpdoKC4eNrnoXbDo8:-MvXPlI44SfjohND1Gxp:b-vgty88) ([raw file](https://github.com/pmem/rpma/blob/e42f9c9e8a9adbf43939b7a8671ca8be358c3175/utils/docker/run-doc-update.sh#L15)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

FYI, we've removed 'valid-branches.sh' some time ago, because it required us to update that file every time we added a new branch and we're lazy :wink: 

This is our approach:
https://github.com/pmem/pmemstream/blob/master/utils/docker/run-doc-update.sh#L29-L38
</blockquote></details>

Right, I have removed `valid-branches.sh` too.
___
*[utils/docker/run-doc-update.sh, line 18 at r1](https://reviewable.io/reviews/pmem/rpma/1574#-MvTwnymBcNMKNIh_0Pr:-MvXPtf99vSXGf7xA2jI:b9zcjft) ([raw file](https://github.com/pmem/rpma/blob/e42f9c9e8a9adbf43939b7a8671ca8be358c3175/utils/docker/run-doc-update.sh#L18)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

As far as I can see, for now, you only support "master", but on pmem.io you're publishing manpages separately for all tags. With the current approach, you'll still have to manually add manpages for tagged versions.
</blockquote></details>

Yes, currently automatic update works only for the master branch and it is OK for us.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1574)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @haichangsi and @lukaszstolarczuk)

___
*[-- commits, line 3 at r1](https://reviewable.io/reviews/pmem/rpma/1574#-MvTodjy4xslPQtNM-Ow):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Are you publishing rpma manpages somewhere else than on pmem.io?

I'm not sure if you can't just update the template and not parse your md files every time
</blockquote></details>

We are publishing rpma man pages on the 'man-pages' branch too.
___
*[utils/docker/run-doc-update.sh, line 95 at r1](https://reviewable.io/reviews/pmem/rpma/1574#-MvTue_f22-N5T5f7Y35:-MvXWEHv8Ex_wsVwbp_h:bmhnybp) ([raw file](https://github.com/pmem/rpma/blob/e42f9c9e8a9adbf43939b7a8671ca8be358c3175/utils/docker/run-doc-update.sh#L95)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

are you sure you want to still commit into 'man-pages' branch? It's not displayed anywhere, right..?
</blockquote></details>

Yes, I am sure, I want to keep it for now.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 2 of 3 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1574#-:-MvXczgQ7TPj3Ts7U6KX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1574)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

___
*[-- commits, line 8 at r1](https://reviewable.io/reviews/pmem/rpma/1574#-MvTxDUL6oa7_J9jHo0T):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

you could mention in commit message the original author, to give him the kudos :wink: 
</blockquote></details>

I have to make sure he allows that ;-)

**Review by lukaszstolarczuk — COMMENTED** [review]
:+1: still loking good :)

> Reviewed 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1574#-:-MvY52C6CeNbzU8AOLqp:bnqjeit)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1574)* status: 3 of 6 files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by haichangsi — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1574#-:-MvcBK3E6uWbuw0VBAZ3:bg7igkv)* status: 3 of 6 files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by haichangsi — COMMENTED** [review]
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1574)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1574)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1574)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
