### PR TITLE
test: add rpma_mr_get_ptr multithreaded test

### PR DESCRIPTION
**Pull request by ewanglong**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1060)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1060)* status: all files reviewed, 10 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/mr/rpma_mr_get_ptr.c, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/1060#-MaF4ARL6M8XXGquChyR:-MaF4ARL6M8XXGquChyS:bs60n7b) ([raw file](https://github.com/pmem/rpma/blob/a34df99637dc78a8b8faa0579f56f090db48123d/tests/multithreaded/mr/rpma_mr_get_ptr.c#L20)):*
> ```C
> 	void *mr_ptr;
> 	struct rpma_mr_local *mr;
> 	void *mr_ptr_exp;
> ```

Both `mr_ptr` and `mr_ptr_exp` are the same. I think we can keep only one of them.
___
*[tests/multithreaded/mr/rpma_mr_get_ptr.c, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1060#-MaF33W9Dswn3eq5kbtX:-MaF33W9Dswn3eq5kbtY:b6jnexm) ([raw file](https://github.com/pmem/rpma/blob/a34df99637dc78a8b8faa0579f56f090db48123d/tests/multithreaded/mr/rpma_mr_get_ptr.c#L39)):*
> ```C
> 
> 	if ((ret = rpma_utils_get_ibv_context(pr->addr,
> 			RPMA_UTIL_IBV_CONTEXT_LOCAL, &pr->dev))) {
> ```

You don't have to store `dev` in the prestate structure.
___
*[tests/multithreaded/mr/rpma_mr_get_ptr.c, line 51 at r1](https://reviewable.io/reviews/pmem/rpma/1060#-MaF3FIh1JhfZbp3EgoL:-MaF3FIh1JhfZbp3EgoM:b88w400) ([raw file](https://github.com/pmem/rpma/blob/a34df99637dc78a8b8faa0579f56f090db48123d/tests/multithreaded/mr/rpma_mr_get_ptr.c#L51)):*
> ```C
> 	pr->mr_ptr = mtt_malloc_aligned(KILOBYTE, tr);
> 	if (pr->mr_ptr == NULL)
> 		return;
> ```

The error handling is missing e.g. `rpma_peer_delete()` at this point.
___
*[tests/multithreaded/mr/rpma_mr_get_ptr.c, line 56 at r1](https://reviewable.io/reviews/pmem/rpma/1060#-MaF3SqP9-8AOl_W4Nga:-MaF3SqP9-8AOl_W4Ngb:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/a34df99637dc78a8b8faa0579f56f090db48123d/tests/multithreaded/mr/rpma_mr_get_ptr.c#L56)):*
> ```C
> 			RPMA_MR_USAGE_READ_SRC, &pr->mr))) {
> 		MTT_RPMA_ERR(tr, "rpma_mr_reg", ret);
> 		return;
> ```

.
___
*[tests/multithreaded/mr/rpma_mr_get_ptr.c, line 60 at r1](https://reviewable.io/reviews/pmem/rpma/1060#-MaF3WFRAMUsDC5huiFs:-MaF3WFRAMUsDC5huiFt:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/a34df99637dc78a8b8faa0579f56f090db48123d/tests/multithreaded/mr/rpma_mr_get_ptr.c#L60)):*
> ```C
> 
> 	if ((ret = rpma_mr_get_ptr(pr->mr, &pr->mr_ptr_exp)))
> 		MTT_RPMA_ERR(tr, "rpma_mr_get_ptr", ret);
> ```

.
___
*[tests/multithreaded/mr/rpma_mr_get_ptr.c, line 60 at r1](https://reviewable.io/reviews/pmem/rpma/1060#-MaF3wpd7jOf3gvuBSxO:-MaF3wpd7jOf3gvuBSxP:b4z5tqh) ([raw file](https://github.com/pmem/rpma/blob/a34df99637dc78a8b8faa0579f56f090db48123d/tests/multithreaded/mr/rpma_mr_get_ptr.c#L60)):*
> ```C
> 
> 	if ((ret = rpma_mr_get_ptr(pr->mr, &pr->mr_ptr_exp)))
> 		MTT_RPMA_ERR(tr, "rpma_mr_get_ptr", ret);
> ```

You should compare the obtained pointer against `pr->mr_ptr`. They should be the same.
___
*[tests/multithreaded/mr/rpma_mr_get_ptr.c, line 80 at r1](https://reviewable.io/reviews/pmem/rpma/1060#-MaF3eEt8OUK4rdr_LV_:-MaF3eEt8OUK4rdr_LVa:b-99ar8c) ([raw file](https://github.com/pmem/rpma/blob/a34df99637dc78a8b8faa0579f56f090db48123d/tests/multithreaded/mr/rpma_mr_get_ptr.c#L80)):*
> ```C
> 
> /*
>  * thread -- gets memory region pointer
> ```

`get the memory region pointer`
___
*[tests/multithreaded/mr/rpma_mr_get_ptr.c, line 87 at r1](https://reviewable.io/reviews/pmem/rpma/1060#-MaF3muQA9B6gL_bbDUw:-MaF3muQA9B6gL_bbDUx:b-tvzbh9) ([raw file](https://github.com/pmem/rpma/blob/a34df99637dc78a8b8faa0579f56f090db48123d/tests/multithreaded/mr/rpma_mr_get_ptr.c#L87)):*
> ```C
> {
> 	struct prestate *pr = (struct prestate *)prestate;
> 	struct state *st = (struct state *)state;
> ```

This test does not need a state.
___
*[tests/multithreaded/mr/rpma_mr_get_ptr.c, line 94 at r1](https://reviewable.io/reviews/pmem/rpma/1060#-MaF4Lyq0h7ZHv2XLnjQ:-MaF4Lyq0h7ZHv2XLnjR:b-h2o4kf) ([raw file](https://github.com/pmem/rpma/blob/a34df99637dc78a8b8faa0579f56f090db48123d/tests/multithreaded/mr/rpma_mr_get_ptr.c#L94)):*
> ```C
> 
> 	if (st->mr_ptr != pr->mr_ptr_exp)
> 		MTT_ERR(result, "rpma_mr_get_ptr returned an unexpected value",
> ```

`"mr_ptr != st->mr_ptr_exp"`
___
*[tests/multithreaded/mr/rpma_mr_get_ptr.c, line 112 at r1](https://reviewable.io/reviews/pmem/rpma/1060#-MaF4eFn2GQ7rPoqaHyJ:-MaF4eFn2GQ7rPoqaHyK:b3v6gna) ([raw file](https://github.com/pmem/rpma/blob/a34df99637dc78a8b8faa0579f56f090db48123d/tests/multithreaded/mr/rpma_mr_get_ptr.c#L112)):*
> ```C
> 
> /*
>  * prestate_fini -- deregister the memory region and delete the peer object
> ```

`deregister the memory region, free it and delete the peer object`

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1060)* status: all files reviewed, 11 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/mr/rpma_mr_get_ptr.c, line 91 at r1](https://reviewable.io/reviews/pmem/rpma/1060#-MaF6EF4AwWieSvaf_JJ:-MaF6EF4AwWieSvaf_JK:bwujzmf) ([raw file](https://github.com/pmem/rpma/blob/a34df99637dc78a8b8faa0579f56f090db48123d/tests/multithreaded/mr/rpma_mr_get_ptr.c#L91)):*
> ```C
> 	int ret = rpma_mr_get_ptr(pr->mr, &st->mr_ptr);
> 	if (ret)
> 		MTT_RPMA_ERR(result, "rpma_mr_get_ptr", ret);
> ```

No point in continuing. Return.

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1060)* status: 1 of 2 files reviewed, 11 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/mr/rpma_mr_get_ptr.c, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/1060#-MaF4ARL6M8XXGquChyR:-MaRVm8W6IgZsoghCiaj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a34df99637dc78a8b8faa0579f56f090db48123d/tests/multithreaded/mr/rpma_mr_get_ptr.c#L20)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Both `mr_ptr` and `mr_ptr_exp` are the same. I think we can keep only one of them.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_ptr.c, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1060#-MaF33W9Dswn3eq5kbtX:-MaRVmdx0qWa7HCl5MIF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a34df99637dc78a8b8faa0579f56f090db48123d/tests/multithreaded/mr/rpma_mr_get_ptr.c#L39)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You don't have to store `dev` in the prestate structure.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_ptr.c, line 51 at r1](https://reviewable.io/reviews/pmem/rpma/1060#-MaF3FIh1JhfZbp3EgoL:-MaRVn9D49G0RZhXIqRC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a34df99637dc78a8b8faa0579f56f090db48123d/tests/multithreaded/mr/rpma_mr_get_ptr.c#L51)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The error handling is missing e.g. `rpma_peer_delete()` at this point.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_ptr.c, line 56 at r1](https://reviewable.io/reviews/pmem/rpma/1060#-MaF3SqP9-8AOl_W4Nga:-MaRVneH6LXjCN72bvT3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a34df99637dc78a8b8faa0579f56f090db48123d/tests/multithreaded/mr/rpma_mr_get_ptr.c#L56)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_ptr.c, line 60 at r1](https://reviewable.io/reviews/pmem/rpma/1060#-MaF3WFRAMUsDC5huiFs:-MaRVo3x82WNTbJzq-zF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a34df99637dc78a8b8faa0579f56f090db48123d/tests/multithreaded/mr/rpma_mr_get_ptr.c#L60)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_ptr.c, line 60 at r1](https://reviewable.io/reviews/pmem/rpma/1060#-MaF3wpd7jOf3gvuBSxO:-MaRVoUu4ZJJrxJeOGB0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a34df99637dc78a8b8faa0579f56f090db48123d/tests/multithreaded/mr/rpma_mr_get_ptr.c#L60)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You should compare the obtained pointer against `pr->mr_ptr`. They should be the same.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_ptr.c, line 80 at r1](https://reviewable.io/reviews/pmem/rpma/1060#-MaF3eEt8OUK4rdr_LV_:-MaRVowNEpfCV427Wm7-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a34df99637dc78a8b8faa0579f56f090db48123d/tests/multithreaded/mr/rpma_mr_get_ptr.c#L80)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`get the memory region pointer`
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_ptr.c, line 87 at r1](https://reviewable.io/reviews/pmem/rpma/1060#-MaF3muQA9B6gL_bbDUw:-MaRVpLc0OTZUHRNQ4Hg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a34df99637dc78a8b8faa0579f56f090db48123d/tests/multithreaded/mr/rpma_mr_get_ptr.c#L87)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This test does not need a state.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_ptr.c, line 91 at r1](https://reviewable.io/reviews/pmem/rpma/1060#-MaF6EF4AwWieSvaf_JJ:-MaRVpl98MZiKGJA_9PR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a34df99637dc78a8b8faa0579f56f090db48123d/tests/multithreaded/mr/rpma_mr_get_ptr.c#L91)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

No point in continuing. Return.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_ptr.c, line 94 at r1](https://reviewable.io/reviews/pmem/rpma/1060#-MaF4Lyq0h7ZHv2XLnjQ:-MaRVq9u-Sr30qG532Bt:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a34df99637dc78a8b8faa0579f56f090db48123d/tests/multithreaded/mr/rpma_mr_get_ptr.c#L94)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`"mr_ptr != st->mr_ptr_exp"`
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_get_ptr.c, line 112 at r1](https://reviewable.io/reviews/pmem/rpma/1060#-MaF4eFn2GQ7rPoqaHyJ:-MaRVqb76Bx88H0dBVZS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a34df99637dc78a8b8faa0579f56f090db48123d/tests/multithreaded/mr/rpma_mr_get_ptr.c#L112)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`deregister the memory region, free it and delete the peer object`
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1060#-:-Mam6K2f8Pidpk2DOi7i:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1060#-:-Mam90Qv8TJlPDpQnARk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Pull request merged**
