### PR TITLE
rpma: write the 'COMPLETIONS' section of the librpma.7 manual

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/518)

### CODE REVIEW

**Comment by ldorau** [comment]
TODO: replace `rpma_conn_prepare_completions()` with `rpma_conn_wait_for_completions()`

**Review by grom72 — COMMENTED** [review]
> Reviewed 18 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/518)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/include/librpma.h, line 193 at r1](https://reviewable.io/reviews/pmem/rpma/518#-MIZ0TIoAPWmmJOVukZf:-MIZ0TIoAPWmmJOVukZg:bsqq0zr) ([raw file](https://github.com/pmem/rpma/blob/bd4f9f3de7c6aa01bd986e76e9037456d6474665/src/include/librpma.h#L193)):*
> ```objc
>  * on success. Completions are collected in the completion queue (CQ)
>  * (see the **QUEUES, PERFORMANCE AND RESOURCE USE** section
>  * for more details on queues).
> ```

Completion codes are reused from the libibverbs library where IBV_WC_SUCCESS status indicates successful operation completion.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/518)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[src/include/librpma.h, line 193 at r1](https://reviewable.io/reviews/pmem/rpma/518#-MIZ0TIoAPWmmJOVukZf:-MIZ327e8vGRz51qNa92:b-ymhzfl) ([raw file](https://github.com/pmem/rpma/blob/bd4f9f3de7c6aa01bd986e76e9037456d6474665/src/include/librpma.h#L193)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Completion codes are reused from the libibverbs library where IBV_WC_SUCCESS status indicates successful operation completion.
</blockquote></details>

OK, so am I supposed to add this sentence?

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/518)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/include/librpma.h, line 193 at r1](https://reviewable.io/reviews/pmem/rpma/518#-MIZ0TIoAPWmmJOVukZf:-MIZ4IsS7RhghHOHpfJ6:b-n0tjw8) ([raw file](https://github.com/pmem/rpma/blob/bd4f9f3de7c6aa01bd986e76e9037456d6474665/src/include/librpma.h#L193)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK, so am I supposed to add this sentence?
</blockquote></details>

yes please

**Review by grom72 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/518#-:-MIZ5NRJ-u9xGIB5c_SX:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/518)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[src/include/librpma.h, line 193 at r1](https://reviewable.io/reviews/pmem/rpma/518#-MIZ0TIoAPWmmJOVukZf:-MIZ6GicDAaNV2bkWNX2:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/bd4f9f3de7c6aa01bd986e76e9037456d6474665/src/include/librpma.h#L193)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

yes please
</blockquote></details>

Done

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/518#-:-MIZ7VZj3T7L42CFbXn9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/518#-:-MIZ7eR_7q843v-PX71i:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
