### PR TITLE
tools: rename librpma to librpma_apm

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/763)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/763#-:-MRxGnl70wGmTvYZ9kW7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/763)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/rpma_fio_bench.sh, line 108 at r1](https://reviewable.io/reviews/pmem/rpma/763#-MRxOSVkAfTBe8s_tITt:-MRxOSVkAfTBe8s_tITu:b-bxbhw4) ([raw file](https://github.com/pmem/rpma/blob/d6b3ac8671461d061ea409c037fd5d37aad70529/tools/rpma_fio_bench.sh#L108)):*
> ```
> SET_MODE
> ```

I would call it `PERSIST_MODE` - what do you think?

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/763)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[tools/rpma_fio_bench.sh, line 108 at r1](https://reviewable.io/reviews/pmem/rpma/763#-MRxOSVkAfTBe8s_tITt:-MRxdXk25DhMGLd43_1T:b-xyzp8o) ([raw file](https://github.com/pmem/rpma/blob/d6b3ac8671461d061ea409c037fd5d37aad70529/tools/rpma_fio_bench.sh#L108)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> SET_MODE
> ```

I would call it `PERSIST_MODE` - what do you think?
</blockquote></details>

You won a contest to name a variable :1st_place_medal:

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/763)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/763)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/rpma_fio_bench.sh, line 200 at r2](https://reviewable.io/reviews/pmem/rpma/763#-MRxjyV02kKDzEoverga:-MRxjyV17al4giIZ2rV-:b-9e58cx) ([raw file](https://github.com/pmem/rpma/blob/cee629a8bfc456d16c91e410d5f83811bf18ee19/tools/rpma_fio_bench.sh#L200)):*
> ```
> librpma${PERSIST_MODE}
> ```

Maybe it will be more clear in this way?

`PERSIST_MODE="gpspm"` or `PERSIST_MODE="apm"` and `librpma_${PERSIST_MODE}-...`

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/763#-:-MRxmU6hAiweVp7U0QdO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
