### PR TITLE
Gh pages disclaimer

### PR DESCRIPTION
**Pull request by grom72**
- [x] #864

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/868)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/868)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[documentation/basic-hw_sw_setup_starting_point.md, line 15 at r1](https://reviewable.io/reviews/pmem/rpma/868#-MT9kVoW4_jzSHNuJDqg:-MT9kVoW4_jzSHNuJDqh:b-vtpndh) ([raw file](https://github.com/pmem/rpma/blob/b59dff7bbe258f375762490a921607936543193f/documentation/basic-hw_sw_setup_starting_point.md#L15)):*
> ```Markdown
> *Your costs and results may vary.*
> 
> Intel technologies may require enabled hardware, software or service activation.*
> ```

Missing *

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/868)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[documentation/basic-hw_sw_setup_starting_point.md, line 15 at r1](https://reviewable.io/reviews/pmem/rpma/868#-MT9kVoW4_jzSHNuJDqg:-MT9ypHi6gT75rtNK7Se:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b59dff7bbe258f375762490a921607936543193f/documentation/basic-hw_sw_setup_starting_point.md#L15)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Missing *
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/868#-:-MTAA3ZM3pfq_xPPCvo5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/868)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/868#-MTASjX_4G1p4ngLo6Ys:-MTASjX_4G1p4ngLo6Yt:b-8cioiv) (no related file):*
Please rebase.

---
___
*[documentation/basic-direct-write-to-pmem.md, line 10 at r2](https://reviewable.io/reviews/pmem/rpma/868#-MTARn2088eWOFBLDDdP:-MTARn2088eWOFBLDDdQ:b50w1n3) ([raw file](https://github.com/pmem/rpma/blob/137ef8264f92ebd62a9516e61bd98a2044d4cd44/documentation/basic-direct-write-to-pmem.md#L10)):*
> ```Markdown
> *Direct Write to PMem* is a readiness of hardware and software configuration which allows effectively and persistently write data to PMem physically attached to one system from another system using RDMA-capable network. How to achive *Direct Write to PMem* capability may differs from system to system because of variety of potential 'interruptions' (e.g. caching) in data's way to be stored persistently on PMem.
> 
> ## Disclaimer
> ```

Please give a new line here.
___
*[documentation/basic-direct-write-to-pmem.md, line 19 at r2](https://reviewable.io/reviews/pmem/rpma/868#-MTARpG9DF8YAEOKn-zU:-MTARpG9DF8YAEOKn-zV:bq4xwfn) ([raw file](https://github.com/pmem/rpma/blob/137ef8264f92ebd62a9516e61bd98a2044d4cd44/documentation/basic-direct-write-to-pmem.md#L19)):*
> ```Markdown
> *Intel technologies may require enabled hardware, software or service activation.*
> 
> *Intel disclaims all express and implied warranties, including without limitation, the implied warranties of merchantability, fitness for a particular purpose, and non-infringement, as well as any warranty arising from course of performance, course of dealing, or usage in trade.*
> ```

Can we put all of these at the end of the file?
___
*[documentation/basic-direct-write-to-pmem.md, line 19 at r2](https://reviewable.io/reviews/pmem/rpma/868#-MTARuf17jhh_iUr1Uhr:-MTARuf17jhh_iUr1Uhs:bxaqgi3) ([raw file](https://github.com/pmem/rpma/blob/137ef8264f92ebd62a9516e61bd98a2044d4cd44/documentation/basic-direct-write-to-pmem.md#L19)):*
> ```Markdown
> *Intel technologies may require enabled hardware, software or service activation.*
> 
> *Intel disclaims all express and implied warranties, including without limitation, the implied warranties of merchantability, fitness for a particular purpose, and non-infringement, as well as any warranty arising from course of performance, course of dealing, or usage in trade.*
> ```

Formatting is odd, to say the least. Can we format it differently?
For me, it recalls a list of a sort. So maybe format these as a list?

**Review by ldorau — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/868)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/868)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/868#-MTAeO9_CTqzG63CIJlj:-MTAeO9_CTqzG63CIJlk:bbfc4dx) (no related file):*
Please push it on your gh-pages to be able to see the preview.

---

**Review by janekmi — COMMENTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/868)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/868)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/868#-MTASjX_4G1p4ngLo6Ys:-MTFFi6W2eZL3DYH_lLz:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please rebase.
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/868#-MTAeO9_CTqzG63CIJlj:-MTFFiuM4NJCY0CxRdTI:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please push it on your gh-pages to be able to see the preview.
</blockquote></details>

Done.

---
___
*[documentation/basic-direct-write-to-pmem.md, line 19 at r2](https://reviewable.io/reviews/pmem/rpma/868#-MTARuf17jhh_iUr1Uhr:-MTFBjVGA0wOoLwpPK7C:bz2p6ey) ([raw file](https://github.com/pmem/rpma/blob/137ef8264f92ebd62a9516e61bd98a2044d4cd44/documentation/basic-direct-write-to-pmem.md#L19)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Formatting is odd, to say the least. Can we format it differently?
For me, it recalls a list of a sort. So maybe format these as a list?
</blockquote></details>

Formatting follows legal suggestions.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/868)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[documentation/basic-direct-write-to-pmem.md, line 10 at r2](https://reviewable.io/reviews/pmem/rpma/868#-MTARn2088eWOFBLDDdP:-MTFFqjZ4gHO-wy-FuIX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/137ef8264f92ebd62a9516e61bd98a2044d4cd44/documentation/basic-direct-write-to-pmem.md#L10)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please give a new line here.
</blockquote></details>

Done.
___
*[documentation/basic-direct-write-to-pmem.md, line 19 at r2](https://reviewable.io/reviews/pmem/rpma/868#-MTARpG9DF8YAEOKn-zU:-MTFGC-XCFBwepEDoWEf:b-prenpc) ([raw file](https://github.com/pmem/rpma/blob/137ef8264f92ebd62a9516e61bd98a2044d4cd44/documentation/basic-direct-write-to-pmem.md#L19)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Can we put all of these at the end of the file?
</blockquote></details>

I will check with a legal

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/868)* status: 2 of 3 files reviewed, 5 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[documentation/basic-direct-write-to-pmem.md, line 19 at r2](https://reviewable.io/reviews/pmem/rpma/868#-MTARuf17jhh_iUr1Uhr:-MTFGfvP46GbrAdVfZdr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/137ef8264f92ebd62a9516e61bd98a2044d4cd44/documentation/basic-direct-write-to-pmem.md#L19)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Formatting follows legal suggestions.
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/868)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi and @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/868)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/868#-MTAeO9_CTqzG63CIJlj:-MTFHlnb0H3WIu3_nYN1:bjmwa4q) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Something is wrong, see: https://grom72.github.io/rpma/documentation/basic-direct-write-to-pmem.html
Please update and push out your PMDK gh-pages.

---

**Review by janekmi — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/868)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/868)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/868#-MTAeO9_CTqzG63CIJlj:-MTFtMaV8w3tGjU7GJA9:b-896fjx) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Something is wrong, see: https://grom72.github.io/rpma/documentation/basic-direct-write-to-pmem.html
Please update and push out your PMDK gh-pages.
</blockquote></details>

Done

---
___
*[documentation/basic-direct-write-to-pmem.md, line 19 at r2](https://reviewable.io/reviews/pmem/rpma/868#-MTARpG9DF8YAEOKn-zU:-MTFtS0i-qQzQVL-WIYF:b87ykgt) ([raw file](https://github.com/pmem/rpma/blob/137ef8264f92ebd62a9516e61bd98a2044d4cd44/documentation/basic-direct-write-to-pmem.md#L19)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I will check with a legal
</blockquote></details>

I propose to leave it as it is, and when I got a reply, we could move it to the end of the file.

**Pull request closed without merging**
