### PR TITLE
tools: improve benchmarking.md file

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/654)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/654)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/BENCHMARKING.md, line 100 at r1](https://reviewable.io/reviews/pmem/rpma/654#-MOBRbih4h67WC6K1pru:-MOBRbii8JgBd0i3g3Tw:bxr4pg) ([raw file](https://github.com/pmem/rpma/blob/ef0289dfa878954e28efa43f8af7e1f2b20ee858/tools/BENCHMARKING.md#L100)):*
> ```Markdown
> ```
> 
> With the help of additional parameters, we can also adjust various output aspects.
> ```

various aspects of the output.

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/654)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[tools/BENCHMARKING.md, line 85 at r1](https://reviewable.io/reviews/pmem/rpma/654#-MOBSSoDBGYIzgf4h8qE:-MOBSSoDBGYIzgf4h8qF:bmo7rt4) ([raw file](https://github.com/pmem/rpma/blob/ef0289dfa878954e28efa43f8af7e1f2b20ee858/tools/BENCHMARKING.md#L85)):*
> ```Markdown
> ```
> 
>  - iterates over the number of threads (1, 2, 4, 8, 12)
> ```

16 is missing.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/654)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/BENCHMARKING.md, line 85 at r1](https://reviewable.io/reviews/pmem/rpma/654#-MOBSSoDBGYIzgf4h8qE:-MOBVS5Y05Q2Wr_47RE3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ef0289dfa878954e28efa43f8af7e1f2b20ee858/tools/BENCHMARKING.md#L85)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

16 is missing.
</blockquote></details>

Done.
___
*[tools/BENCHMARKING.md, line 100 at r1](https://reviewable.io/reviews/pmem/rpma/654#-MOBRbih4h67WC6K1pru:-MOBVc_BB4hyVcWRfb54:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ef0289dfa878954e28efa43f8af7e1f2b20ee858/tools/BENCHMARKING.md#L100)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

various aspects of the output.
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/654)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/654#-:-MOBw-EqCTj2xrT9d0lL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
