### PR TITLE
examples: add a readme to the example15

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1718)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1718)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[`examples/15-multiple-connections-SHCCH/README.md` line 26 at r1](https://reviewable.io/reviews/pmem/rpma/1718#-N0p61VqE8GYW0FJ4286:-N0p61VqE8GYW0FJ4287:undefined) ([raw file](https://github.com/pmem/rpma/blob/fef26b29ac570f22d04c7b99220a929fc9928e09/examples/15-multiple-connections-SHCCH/README.md#L26)):*
> ```Markdown
> 
> **Note**: In this example, we use the shared completion event channel for CQ for completions of send.
> We use the rpma_conn_wait() function to collect completions.
> ```





_Suggestion:_
```Markdown
wait for completions' events
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1718)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`examples/15-multiple-connections-SHCCH/README.md` line 26 at r1](https://reviewable.io/reviews/pmem/rpma/1718#-N0p61VqE8GYW0FJ4286:-N15Gez78rMRwS860Rnz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fef26b29ac570f22d04c7b99220a929fc9928e09/examples/15-multiple-connections-SHCCH/README.md#L26)):*
> ```Markdown
> 
> **Note**: In this example, we use the shared completion event channel for CQ for completions of send.
> We use the rpma_conn_wait() function to collect completions.
> ```

Done.

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1718#-:-N1CumwUA7HmqhINnHSO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1718)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1718#-:-N1Cv4vq9MI_Y7gvPHPX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
