### PR TITLE
tools: fio.py SETTINGS_BY_MODE filled up

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1391)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1391)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 218 at r1](https://reviewable.io/reviews/pmem/rpma/1391#-Mq-aCUV4E3KcwWLNOpo:-Mq-aCUV4E3KcwWLNOpp:b83t1pz) ([raw file](https://github.com/pmem/rpma/blob/47eeb1bda4fe5528f8c66461f103342ffac1a78c/tools/perf/lib/benchmark/runner/fio.py#L218)):*
> ```
>             'iodepth': [1, 2, 4, 8, 16, 32, 64, 128],
>             'iterations': 8,
> ```

All 'iterations' should be set by `len()`:

```
            'iodepth': DEPTH_VALUES,
            'iterations': len(DEPTH_VALUES),
```
___
*[tools/perf/lib/benchmark/runner/fio.py, line 225 at r1](https://reviewable.io/reviews/pmem/rpma/1391#-Mq-aZJs4yigW3wq3UWD:-Mq-aZJs4yigW3wq3UWE:b-guebum) ([raw file](https://github.com/pmem/rpma/blob/47eeb1bda4fe5528f8c66461f103342ffac1a78c/tools/perf/lib/benchmark/runner/fio.py#L225)):*
> ```
>             'iodepth': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
>             'iterations': 8,
> ```

.

( '.' means "same as above")
___
*[tools/perf/lib/benchmark/runner/fio.py, line 232 at r1](https://reviewable.io/reviews/pmem/rpma/1391#-Mq-b-le1LwLF_SlqDiA:-Mq-b-le1LwLF_SlqDiB:bliyitx) ([raw file](https://github.com/pmem/rpma/blob/47eeb1bda4fe5528f8c66461f103342ffac1a78c/tools/perf/lib/benchmark/runner/fio.py#L232)):*
> ```
>             'threads': [1, 2, 4, 8, 12, 16, 32, 64],
>             ....
>             'iterations': 8,
> ```

```
            'threads': THREADS_VALUES,
            ....
            'iterations': len(THREADS_VALUES),
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1391)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 218 at r1](https://reviewable.io/reviews/pmem/rpma/1391#-Mq-aCUV4E3KcwWLNOpo:-MqBd43W-upjVoNyxrUZ:b-jctftc) ([raw file](https://github.com/pmem/rpma/blob/47eeb1bda4fe5528f8c66461f103342ffac1a78c/tools/perf/lib/benchmark/runner/fio.py#L218)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>             'iodepth': [1, 2, 4, 8, 16, 32, 64, 128],
>             'iterations': 8,
> ```

All 'iterations' should be set by `len()`:

```
            'iodepth': DEPTH_VALUES,
            'iterations': len(DEPTH_VALUES),
```
</blockquote></details>

Depth values here and below are different. Should I use a different variable for every list then?

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1391)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi and @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1391)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 218 at r1](https://reviewable.io/reviews/pmem/rpma/1391#-Mq-aCUV4E3KcwWLNOpo:-MqE2qEA-3Sc8GBO3YhC:buqd8rq) ([raw file](https://github.com/pmem/rpma/blob/47eeb1bda4fe5528f8c66461f103342ffac1a78c/tools/perf/lib/benchmark/runner/fio.py#L218)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Depth values here and below are different. Should I use a different variable for every list then?
</blockquote></details>

Yes, but this variable should be a local one. Please do this like that: https://github.com/ldorau/rpma/commit/cae02691ecf14284ed1032a56b0b73ec79420c23

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1391)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 218 at r1](https://reviewable.io/reviews/pmem/rpma/1391#-Mq-aCUV4E3KcwWLNOpo:-MqEPJSl60yTy82dmUXB:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/47eeb1bda4fe5528f8c66461f103342ffac1a78c/tools/perf/lib/benchmark/runner/fio.py#L218)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, but this variable should be a local one. Please do this like that: https://github.com/ldorau/rpma/commit/cae02691ecf14284ed1032a56b0b73ec79420c23
</blockquote></details>

Done
___
*[tools/perf/lib/benchmark/runner/fio.py, line 225 at r1](https://reviewable.io/reviews/pmem/rpma/1391#-Mq-aZJs4yigW3wq3UWD:-MqEPKuH86n5CUHXX6g7:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/47eeb1bda4fe5528f8c66461f103342ffac1a78c/tools/perf/lib/benchmark/runner/fio.py#L225)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>             'iodepth': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
>             'iterations': 8,
> ```

.

( '.' means "same as above")
</blockquote></details>

Done
___
*[tools/perf/lib/benchmark/runner/fio.py, line 232 at r1](https://reviewable.io/reviews/pmem/rpma/1391#-Mq-b-le1LwLF_SlqDiA:-MqEPMVk29LDQSOb6sJd:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/47eeb1bda4fe5528f8c66461f103342ffac1a78c/tools/perf/lib/benchmark/runner/fio.py#L232)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>             'threads': [1, 2, 4, 8, 12, 16, 32, 64],
>             ....
>             'iterations': 8,
> ```

```
            'threads': THREADS_VALUES,
            ....
            'iterations': len(THREADS_VALUES),
```
</blockquote></details>

Done

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1391)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 206 at r2](https://reviewable.io/reviews/pmem/rpma/1391#-MqEPwht-dNPkQlf34j-:-MqEPwht-dNPkQlf34j0:bme4504) ([raw file](https://github.com/pmem/rpma/blob/fae683e2ecf6f0cf28e1156a41d3f014dd6ded91/tools/perf/lib/benchmark/runner/fio.py#L206)):*
> ```
>     __X_KEYS = ['threads', 'bs', 'iodepth']
>     __BW_DP_EXP_DEPTH = [1, 2, 4, 8, 16, 32, 64, 128]
> ```

Please add one empty line in between.
___
*[tools/perf/lib/benchmark/runner/fio.py, line 207 at r2](https://reviewable.io/reviews/pmem/rpma/1391#-MqER7tM5voWeIQxpqzv:-MqER7tNCC_9BeeC6x1-:b-7u5mdc) ([raw file](https://github.com/pmem/rpma/blob/fae683e2ecf6f0cf28e1156a41d3f014dd6ded91/tools/perf/lib/benchmark/runner/fio.py#L207)):*
> ```
>     __BW_DP_EXP_DEPTH = [1, 2, 4, 8, 16, 32, 64, 128]
>     __BW_DP_LIN_DEPTH = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
> ```

Please add `S`at the end:
`__BW_DP_EXP_DEPTH` -> `__BW_DP_EXP_DEPTHS`
`__BW_DP_LIN_DEPTH` -> `__BW_DP_LIN_DEPTHS`

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1391)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 247 at r2](https://reviewable.io/reviews/pmem/rpma/1391#-MqETIDi6WBQ6iST2LTG:-MqETIDi6WBQ6iST2LTH:bp7121d) ([raw file](https://github.com/pmem/rpma/blob/fae683e2ecf6f0cf28e1156a41d3f014dd6ded91/tools/perf/lib/benchmark/runner/fio.py#L247)):*
> ```
> 'threads': THREADS_VALUES,
> ```

There is `THREADS=$CORES_PER_SOCKET` in *.sh script

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1391)* status: all files reviewed, 4 unresolved discussions (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1391#-MqIsjYKBFxFDa2j7bLv:-MqIsjYKBFxFDa2j7bLw:b-ujmq67) (no related file):*
Rebase please

---

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1391)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1391#-MqIsjYKBFxFDa2j7bLv:-MqLbX-KC2zRCYXiH0Zq:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Rebase please
</blockquote></details>

Done.

---
___
*[tools/perf/lib/benchmark/runner/fio.py, line 206 at r2](https://reviewable.io/reviews/pmem/rpma/1391#-MqEPwht-dNPkQlf34j-:-MqLbSFxD0ccDL5Tf31Z:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/fae683e2ecf6f0cf28e1156a41d3f014dd6ded91/tools/perf/lib/benchmark/runner/fio.py#L206)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>     __X_KEYS = ['threads', 'bs', 'iodepth']
>     __BW_DP_EXP_DEPTH = [1, 2, 4, 8, 16, 32, 64, 128]
> ```

Please add one empty line in between.
</blockquote></details>

Done
___
*[tools/perf/lib/benchmark/runner/fio.py, line 207 at r2](https://reviewable.io/reviews/pmem/rpma/1391#-MqER7tM5voWeIQxpqzv:-MqLbUY3B-A_8mpwIhJ0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fae683e2ecf6f0cf28e1156a41d3f014dd6ded91/tools/perf/lib/benchmark/runner/fio.py#L207)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>     __BW_DP_EXP_DEPTH = [1, 2, 4, 8, 16, 32, 64, 128]
>     __BW_DP_LIN_DEPTH = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
> ```

Please add `S`at the end:
`__BW_DP_EXP_DEPTH` -> `__BW_DP_EXP_DEPTHS`
`__BW_DP_LIN_DEPTH` -> `__BW_DP_LIN_DEPTHS`
</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/runner/fio.py, line 247 at r2](https://reviewable.io/reviews/pmem/rpma/1391#-MqETIDi6WBQ6iST2LTG:-MqLbWAL2Atx-2oT2eB5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fae683e2ecf6f0cf28e1156a41d3f014dd6ded91/tools/perf/lib/benchmark/runner/fio.py#L247)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 'threads': THREADS_VALUES,
> ```

There is `THREADS=$CORES_PER_SOCKET` in *.sh script
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1391)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1391#-:-MqOOJj781150Je1nspS:bg7igkv)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1391)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1391#-MqIsjYKBFxFDa2j7bLv:-MqOP01-BTJtgrYApy73:b-2hwpbx) (no related file):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please rebase again ...

---
___
*[tools/perf/lib/benchmark/runner/fio.py, line 82 at r3](https://reviewable.io/reviews/pmem/rpma/1391#-MqOOpmf8syOeE3hPwf6:-MqOOpmf8syOeE3hPwf7:birvt0j) ([raw file](https://github.com/pmem/rpma/blob/5870767876bf1440abfa631c1e03bc693de91b39/tools/perf/lib/benchmark/runner/fio.py#L82)):*
> ```
>  if mode == 'bw-cpu-mt':
> ```

Please add the comment before:
```
# set 'threads' to CORES_PER_SOCKET in the 'bw-cpu-mt' mode
```
___
*[tools/perf/lib/benchmark/runner/fio.py, line 252 at r3](https://reviewable.io/reviews/pmem/rpma/1391#-MqOE9nh8axfnI7bbP-a:-MqOE9nh8axfnI7bbP-b:b-v6fm5a) ([raw file](https://github.com/pmem/rpma/blob/5870767876bf1440abfa631c1e03bc693de91b39/tools/perf/lib/benchmark/runner/fio.py#L252)):*
> ```
>  'threads': 0,
> ```

Please add the comment here:
```
'threads': 0, # will be set to CORES_PER_SOCKET in __init__
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1391)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1391)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1391)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1391#-MqIsjYKBFxFDa2j7bLv:-MqREdzI44c97MtHeoBB:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please rebase again ...
</blockquote></details>

Done.

---
___
*[tools/perf/lib/benchmark/runner/fio.py, line 82 at r3](https://reviewable.io/reviews/pmem/rpma/1391#-MqOOpmf8syOeE3hPwf6:-MqREYlLEDiuuu_Vhj0k:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5870767876bf1440abfa631c1e03bc693de91b39/tools/perf/lib/benchmark/runner/fio.py#L82)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  if mode == 'bw-cpu-mt':
> ```

Please add the comment before:
```
# set 'threads' to CORES_PER_SOCKET in the 'bw-cpu-mt' mode
```

</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/runner/fio.py, line 252 at r3](https://reviewable.io/reviews/pmem/rpma/1391#-MqOE9nh8axfnI7bbP-a:-MqREYYy5b3mCj7XC7OI:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5870767876bf1440abfa631c1e03bc693de91b39/tools/perf/lib/benchmark/runner/fio.py#L252)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  'threads': 0,
> ```

Please add the comment here:
```
'threads': 0, # will be set to CORES_PER_SOCKET in __init__
```
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1391)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1391#-:-MqTJXhaDc_l590bV7tK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by osalyk — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1391)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[tools/perf/lib/benchmark/runner/common.py, line 40 at r4](https://reviewable.io/reviews/pmem/rpma/1391#-MqTR_2m-c18aTmHTuaz:-MqTR_2m-c18aTmHTub-:bf13bsm) ([raw file](https://github.com/pmem/rpma/blob/8c09d336ed68131b96dc14550204e66eea00eb95/tools/perf/lib/benchmark/runner/common.py#L40)):*
> ```Python
>             return True
>     return False
> CPU_LOAD_00_99 = [0, 25, 50, 75, 99]
> ```

What about CPU_LOAD_75_99?

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1391)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1391)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[tools/perf/lib/benchmark/runner/common.py, line 40 at r4](https://reviewable.io/reviews/pmem/rpma/1391#-MqTR_2m-c18aTmHTuaz:-MqUDhNTDMTPV7WU5O1t:bynbvrj) ([raw file](https://github.com/pmem/rpma/blob/8c09d336ed68131b96dc14550204e66eea00eb95/tools/perf/lib/benchmark/runner/common.py#L40)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

What about CPU_LOAD_75_99?
</blockquote></details>

Very good catch @osalyk ! :-)

@haichangsi There is `CPU_LOAD_RANGE_VALUES` used in `rpma_fio_bench.sh` (not `CPU_LOAD_00_99`):

```
		CPU_LOAD=(${!CPU_LOAD_RANGE_VALUES})
```

See also:
```
CPU_LOAD_00_99="0 25 50 75 99"
CPU_LOAD_75_99="75 80 85 90 95 99"
CPU_LOAD_RANGE=${CPU_LOAD_RANGE-00_99} # the default value
CPU_LOAD_RANGE_VALUES="CPU_LOAD_$CPU_LOAD_RANGE"
```

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1391)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1391)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72, @ldorau, and @osalyk)

___
*[tools/perf/lib/benchmark/runner/common.py, line 40 at r4](https://reviewable.io/reviews/pmem/rpma/1391#-MqTR_2m-c18aTmHTuaz:-MqZ8oNr4YWClYtLvaIx:b-b30vxk) ([raw file](https://github.com/pmem/rpma/blob/8c09d336ed68131b96dc14550204e66eea00eb95/tools/perf/lib/benchmark/runner/common.py#L40)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Very good catch @osalyk ! :-)

@haichangsi There is `CPU_LOAD_RANGE_VALUES` used in `rpma_fio_bench.sh` (not `CPU_LOAD_00_99`):

```
		CPU_LOAD=(${!CPU_LOAD_RANGE_VALUES})
```

See also:
```
CPU_LOAD_00_99="0 25 50 75 99"
CPU_LOAD_75_99="75 80 85 90 95 99"
CPU_LOAD_RANGE=${CPU_LOAD_RANGE-00_99} # the default value
CPU_LOAD_RANGE_VALUES="CPU_LOAD_$CPU_LOAD_RANGE"
```

</blockquote></details>

Done, check please if this is the correct way to do this

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1391)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72, @ldorau, and @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1391)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi and @osalyk)

___
*[tools/perf/lib/benchmark/runner/common.py, line 40 at r4](https://reviewable.io/reviews/pmem/rpma/1391#-MqTR_2m-c18aTmHTuaz:-MqZq8-rC10daGUSc3Vb:b5c6g1t) ([raw file](https://github.com/pmem/rpma/blob/8c09d336ed68131b96dc14550204e66eea00eb95/tools/perf/lib/benchmark/runner/common.py#L40)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done, check please if this is the correct way to do this
</blockquote></details>

There is a simpler way to do this ...
___
*[tools/perf/lib/benchmark/runner/common.py, line 25 at r5](https://reviewable.io/reviews/pmem/rpma/1391#-MqZqMG70tqKnhQ0yaC_:-MqZqMG70tqKnhQ0yaCa:b-cu1udj) ([raw file](https://github.com/pmem/rpma/blob/fe237d91a3347cb2fc18312add5487dcf7465b4f/tools/perf/lib/benchmark/runner/common.py#L25)):*
> ```
> THREADS_VALUES = [1, 2, 4, 8, 12, 16, 32, 64]
> ```

Please move it to fio.sh, because it is used only there (it was my mistake).

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1391)* status: all files reviewed, 4 unresolved discussions (waiting on @haichangsi and @osalyk)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 271 at r6](https://reviewable.io/reviews/pmem/rpma/1391#-Mqsl5CSByFW4HUSS7aP:-Mqsl5CSByFW4HUSS7aQ:bz9jd63) ([raw file](https://github.com/pmem/rpma/blob/232403cb5b26f357ce999c98ca2948d7ab0e754c/tools/perf/lib/benchmark/runner/fio.py#L271)):*
> ```
>             'cpuload': [], # will be set in __init__,
>             'iterations': 0, # will be set in __init__,
> ```

Please remove commas at the end of those lines.
___
*[tools/perf/lib/benchmark/runner/fio.py, line 279 at r6](https://reviewable.io/reviews/pmem/rpma/1391#-MqslBjECccIsy0HvG_H:-MqslBjECccIsy0HvG_I:b-2oewjx) ([raw file](https://github.com/pmem/rpma/blob/232403cb5b26f357ce999c98ca2948d7ab0e754c/tools/perf/lib/benchmark/runner/fio.py#L279)):*
> ```
>             'cpuload': [], # will be set in __init__,
>             'iterations': 0, # will be set in __init__,
> ```

.
___
*[tools/perf/lib/benchmark/runner/fio.py, line 294 at r6](https://reviewable.io/reviews/pmem/rpma/1391#-MqslDe5BO4wLJaNDyCv:-MqslDe5BO4wLJaNDyCw:b-2oewjx) ([raw file](https://github.com/pmem/rpma/blob/232403cb5b26f357ce999c98ca2948d7ab0e754c/tools/perf/lib/benchmark/runner/fio.py#L294)):*
> ```
>             'cpuload': [], # will be set in __init__,
>             'iterations': 0, # will be set in __init__,
> ```

.

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1391)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 271 at r6](https://reviewable.io/reviews/pmem/rpma/1391#-Mqsl5CSByFW4HUSS7aP:-Mqslws07iorU7K9DLSC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/232403cb5b26f357ce999c98ca2948d7ab0e754c/tools/perf/lib/benchmark/runner/fio.py#L271)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>             'cpuload': [], # will be set in __init__,
>             'iterations': 0, # will be set in __init__,
> ```

Please remove commas at the end of those lines.
</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/runner/fio.py, line 279 at r6](https://reviewable.io/reviews/pmem/rpma/1391#-MqslBjECccIsy0HvG_H:-MqslxBW-t0aSsULAWK5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/232403cb5b26f357ce999c98ca2948d7ab0e754c/tools/perf/lib/benchmark/runner/fio.py#L279)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>             'cpuload': [], # will be set in __init__,
>             'iterations': 0, # will be set in __init__,
> ```

.
</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/runner/fio.py, line 294 at r6](https://reviewable.io/reviews/pmem/rpma/1391#-MqslDe5BO4wLJaNDyCv:-MqslxVn805fESVqaUB5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/232403cb5b26f357ce999c98ca2948d7ab0e754c/tools/perf/lib/benchmark/runner/fio.py#L294)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>             'cpuload': [], # will be set in __init__,
>             'iterations': 0, # will be set in __init__,
> ```

.
</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/runner/common.py, line 40 at r4](https://reviewable.io/reviews/pmem/rpma/1391#-MqTR_2m-c18aTmHTuaz:-Mqsm-2P1uZ8hxTe1N4F:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8c09d336ed68131b96dc14550204e66eea00eb95/tools/perf/lib/benchmark/runner/common.py#L40)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

There is a simpler way to do this ...
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1391)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1391#-:-MqsmByt1s-T-dnOPO-h:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1391#-:-Mqsq5PA43rSj-ntrGka:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1391)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Pull request merged**
