### PR TITLE
common: make sure WORKDIR has correct permissions

### PR DESCRIPTION
**Pull request by ldorau**
Ref: #1875

- - -
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/2007)

### CODE REVIEW

**Review by osalyk — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2007)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2007#-:-NAIvj683ZNPqbXeK-fg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2007#-:-NAIwYUl31yVsoRsrYkC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by haichangsi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2007#-:-NAIwtvsEXLxpOs_OJ6f:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
