### PR TITLE
rpma: move librpma_log.h into librpma.h

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/433)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/433#-:-MHujhSvCHMIH954c1Lb:bnfp4nl)* status: 2 of 24 files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> Reviewed 22 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/433)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> Reviewed 24 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/433)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/433#-:-MHwb0aUCZlGzVvjRDyX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
