### PR TITLE
examples: make the internal API comply the new chars line limit

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1987)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1987)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1987#-NA4-VL4BEMfDnCIU8Yl:-NA4-VL4BEMfDnCIU8Ym:b-npd77q) (no related file):*
Do we have information about the new line length somewhere in CHANGELOG.md?

___

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1987#-:-NA4903Z02YlMq6SQrXm:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi and @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1987)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi and @osalyk)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 13 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1987#-:-NA4AUGG03JefV00b3vx:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1987)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1987)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @grom72, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1987#-NA4-VL4BEMfDnCIU8Yl:-NA4DRq05IeU6FX1s_xf:b-896fix) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Do we have information about the new line length somewhere in CHANGELOG.md?
</blockquote></details>

Done.

___

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1987#-:-NA4EtgK1mafWfEan4mn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1987)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
