### PR TITLE
tools: rpma_read benchmarks also the bandwidth

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #645

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/647)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/647)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[tools/rpma_read.sh, line 8 at r1](https://reviewable.io/reviews/pmem/rpma/647#-MO6WC675GIEUYKs1lap:-MO6WC689PxefcIy5AgH:bcsdt89) ([raw file](https://github.com/pmem/rpma/blob/5b6fb93bc460b38b4dd12a8004571813560c79b7/tools/rpma_read.sh#L8)):*
> ```
> rpma_read
> ```
rpma_fio_read
to indicate that fio will be used ;)
___
*[tools/rpma_read.sh, line 8 at r1](https://reviewable.io/reviews/pmem/rpma/647#-MO6Wlb44c23ZoqwJmXL:-MO6Wlb44c23ZoqwJmXM:bt5izl) ([raw file](https://github.com/pmem/rpma/blob/5b6fb93bc460b38b4dd12a8004571813560c79b7/tools/rpma_read.sh#L8)):*
> ```
>  a single-sided RPMA benchmark
> ```
a single-side Fio RPMA benchmark
___
*[tools/rpma_read.sh, line 53 at r1](https://reviewable.io/reviews/pmem/rpma/647#-MO6WOEo7dJD297UTV-N:-MO6WOEo7dJD297UTV-O:b-lkt6se) ([raw file](https://github.com/pmem/rpma/blob/5b6fb93bc460b38b4dd12a8004571813560c79b7/tools/rpma_read.sh#L53)):*
> ```Shell
> echo "Performance results: $OUTPUT"
> echo "Output and errors (both sides): $LOG_ERR"
> echo
> ```

echo: "Experimental"
 to indicate users all the time that tool is experimental

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/647)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[tools/rpma_read.sh, line 8 at r1](https://reviewable.io/reviews/pmem/rpma/647#-MO6WC675GIEUYKs1lap:-MO6e-qq6EYXTmORel_G:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5b6fb93bc460b38b4dd12a8004571813560c79b7/tools/rpma_read.sh#L8)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> rpma_read
> ```
rpma_fio_read
to indicate that fio will be used ;)

</blockquote></details>

Done.
___
*[tools/rpma_read.sh, line 8 at r1](https://reviewable.io/reviews/pmem/rpma/647#-MO6Wlb44c23ZoqwJmXL:-MO6e4Nt7RkgF_-9YH3m:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5b6fb93bc460b38b4dd12a8004571813560c79b7/tools/rpma_read.sh#L8)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
>  a single-sided RPMA benchmark
> ```
a single-side Fio RPMA benchmark
</blockquote></details>

Done.
___
*[tools/rpma_read.sh, line 53 at r1](https://reviewable.io/reviews/pmem/rpma/647#-MO6WOEo7dJD297UTV-N:-MO6eGx99aB_kJ_anIXs:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5b6fb93bc460b38b4dd12a8004571813560c79b7/tools/rpma_read.sh#L53)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

echo: "Experimental"
 to indicate users all the time that tool is experimental
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/647)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/647#-:-MO6lJyL--aQgy7Q0wDV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/647)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/rpma_fio_read.sh, line 53 at r3](https://reviewable.io/reviews/pmem/rpma/647#-MO6vFgR6GyHbXBA2Qsv:-MO6vFgR6GyHbXBA2Qsw:bh8imxo) ([raw file](https://github.com/pmem/rpma/blob/dee5fc35c901e90ed8db5f4d5842faa1fc4d508f/tools/rpma_fio_read.sh#L53)):*
> ```
> echo "This tool is EXPERIMENTAL!"
> ```
```
echo "THIS TOOL IS EXPERIMENTAL. YOU ARE USING IT ON YOUR OWN RISK."
```
and put it as first line in message section (before function_usage())

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/647)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/rpma_fio_read.sh, line 53 at r3](https://reviewable.io/reviews/pmem/rpma/647#-MO6vFgR6GyHbXBA2Qsv:-MO7-7JmC7EjpcowxzbI:bev4ikg) ([raw file](https://github.com/pmem/rpma/blob/dee5fc35c901e90ed8db5f4d5842faa1fc4d508f/tools/rpma_fio_read.sh#L53)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> echo "This tool is EXPERIMENTAL!"
> ```
```
echo "THIS TOOL IS EXPERIMENTAL. YOU ARE USING IT ON YOUR OWN RISK."
```
and put it as first line in message section (before function_usage())

</blockquote></details>

I think the message "`"THIS TOOL IS EXPERIMENTAL. YOU ARE USING IT ON YOUR OWN RISK."`"  is too dramatic. It may give the impression that this tool is dangerous and can erase the data or destroy the hardware. In my opinion the current message is enough.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/647#-:-MO7koLC4MGSZFplrpYH:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — COMMENTED** [review]
Rebased

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/647#-:-MO80B115Oip-jn_fSTK:b9x2p3v)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/647)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/rpma_fio_read.sh, line 53 at r3](https://reviewable.io/reviews/pmem/rpma/647#-MO6vFgR6GyHbXBA2Qsv:-MO8mRSM0PVZQ9eH1tN4:b-omhkgr) ([raw file](https://github.com/pmem/rpma/blob/dee5fc35c901e90ed8db5f4d5842faa1fc4d508f/tools/rpma_fio_read.sh#L53)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I think the message "`"THIS TOOL IS EXPERIMENTAL. YOU ARE USING IT ON YOUR OWN RISK."`"  is too dramatic. It may give the impression that this tool is dangerous and can erase the data or destroy the hardware. In my opinion the current message is enough.
</blockquote></details>

Since you both have to left today earlier without solving this argument and I need this PR to be merged ASAP I propose to fix all of the messages in #648. Which is not so critical.

**Pull request merged**
