### PR TITLE
tools: perf: separate report.json from config.json

### PR DESCRIPTION
**Pull request by janekmi**
The config.json ['report'] section is obviously not used till the final report is generated. Where config.json is provided at the beginning of the pipeline, the ['report'] section is used in the final step. The ['report'] section is also independent of any specific platform configuration. Obviously, it is a generalization but can be used interchangeably between various sibling setups. So, the idea is to separate what is specific to a given setup from what is a lot more general. Additionally, it will make the process of preparing the config.json for benchmarking a lot easier because it will not require writing an extensive description of the test setup before even running anything.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1196)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 4 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1196)* status: 4 of 7 files reviewed, 5 unresolved discussions (waiting on @janekmi)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1196#-MhDic1bBOlujeKhwtoY:-MhDic1c3qKMDNBHybz7:b-n898sh) ([raw file](https://github.com/pmem/rpma/blob/02bf814a6dde35dafbad2a81368437b56d87d51f/-- commits#L2)):*
any comment why this change?
___
*[tools/perf/report_create.py, line 22 at r1](https://reviewable.io/reviews/pmem/rpma/1196#-MhDh5qs9-E5fymLDlEh:-MhDh5qs9-E5fymLDlEi:b-6r1mzi) ([raw file](https://github.com/pmem/rpma/blob/02bf814a6dde35dafbad2a81368437b56d87d51f/tools/perf/report_create.py#L22)):*
> ```Python
>                     help='a bench.json file of a completed benchmark')
> PARSER.add_argument('--report', type=json_from_file, required=True,
>                     help='a report configuration file')
> ```

perhaps similarily to the above param: `a report.json configuration file`
___
*[tools/perf/report_create.py, line 24 at r1](https://reviewable.io/reviews/pmem/rpma/1196#-MhDgwMr5HGVSzre0aN7:-MhDgwMr5HGVSzre0aN8:b-od0xqv) ([raw file](https://github.com/pmem/rpma/blob/02bf814a6dde35dafbad2a81368437b56d87d51f/tools/perf/report_create.py#L24)):*
> ```Python
>                     help='a report configuration file')
> PARSER.add_argument('--output', default='report',
>                     help='a name of the output file')
> ```

perhaps more precise: `a name of the generated report file`
___
*[tools/perf/lib/Report.py, line 71 at r1](https://reviewable.io/reviews/pmem/rpma/1196#-MhDkqfsB2aU1qqkuAe4:-MhDkqfsB2aU1qqkuAe5:bohc92k) ([raw file](https://github.com/pmem/rpma/blob/02bf814a6dde35dafbad2a81368437b56d87d51f/tools/perf/lib/Report.py#L71)):*
> ```Python
>     def __init__(self, loader, env, bench, vars):
>         self.env = env # jinja2.Environment
>         self._set_variables(vars['json'])
> ```

maybe I'm missing something, but I'm not sure what is `vars['json']`
___
*[tools/perf/lib/Report.py, line 100 at r1](https://reviewable.io/reviews/pmem/rpma/1196#-MhDgnlAB_mg5l1S1QFW:-MhDgnlB-rycGWl3Wqoy:b-y1s8gs) ([raw file](https://github.com/pmem/rpma/blob/02bf814a6dde35dafbad2a81368437b56d87d51f/tools/perf/lib/Report.py#L100)):*
> ```Python
>         html = layout_tmpl.render(variables)
>         # write the output file
>         output_file = os.path.join(self.result_dir, output + '.html')
> ```

I'd be nice to print this full path/full name to stdout

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1196)* status: 4 of 9 files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1196#-MhDic1bBOlujeKhwtoY:-MhEPp3TAnvrtFXoAcrh:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/02bf814a6dde35dafbad2a81368437b56d87d51f/-- commits#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

any comment why this change?
</blockquote></details>

Done.
___
*[tools/perf/report_create.py, line 22 at r1](https://reviewable.io/reviews/pmem/rpma/1196#-MhDh5qs9-E5fymLDlEh:-MhEMWI21Qo5J0-PMNVJ:b-hmq5ee) ([raw file](https://github.com/pmem/rpma/blob/02bf814a6dde35dafbad2a81368437b56d87d51f/tools/perf/report_create.py#L22)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps similarily to the above param: `a report.json configuration file`
</blockquote></details>

`bench.json` is a fixed name whereas the report configuration file can be named according to the user desire.
___
*[tools/perf/report_create.py, line 24 at r1](https://reviewable.io/reviews/pmem/rpma/1196#-MhDgwMr5HGVSzre0aN7:-MhEMoiL-_ghvlQZfHtU:b-mfm8o9) ([raw file](https://github.com/pmem/rpma/blob/02bf814a6dde35dafbad2a81368437b56d87d51f/tools/perf/report_create.py#L24)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps more precise: `a name of the generated report file`
</blockquote></details>

Maybe. I will think about it in a separate PR.
___
*[tools/perf/lib/Report.py, line 71 at r1](https://reviewable.io/reviews/pmem/rpma/1196#-MhDkqfsB2aU1qqkuAe4:-MhEMxH591D0GLN2P1Eg:b-3glz9r) ([raw file](https://github.com/pmem/rpma/blob/02bf814a6dde35dafbad2a81368437b56d87d51f/tools/perf/lib/Report.py#L71)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

maybe I'm missing something, but I'm not sure what is `vars['json']`
</blockquote></details>

This one is tricky. This is because of how we parse the provided input JSON files.

Ref: https://github.com/pmem/rpma/blob/master/tools/perf/lib/common.py#L25
___
*[tools/perf/lib/Report.py, line 100 at r1](https://reviewable.io/reviews/pmem/rpma/1196#-MhDgnlAB_mg5l1S1QFW:-MhENBi85HQwBgAFFKWO:b4djkdq) ([raw file](https://github.com/pmem/rpma/blob/02bf814a6dde35dafbad2a81368437b56d87d51f/tools/perf/lib/Report.py#L100)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'd be nice to print this full path/full name to stdout
</blockquote></details>

Maybe. To be considered in a separate PR.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1196)* status: 4 of 9 files reviewed, all discussions resolved (waiting on @janekmi)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1196#-MhDic1bBOlujeKhwtoY:-MhEcYJa5qKibCGHgc9F:b2nid0f) ([raw file](https://github.com/pmem/rpma/blob/02bf814a6dde35dafbad2a81368437b56d87d51f/-- commits#L2)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

thx
___
*[tools/perf/lib/Report.py, line 71 at r1](https://reviewable.io/reviews/pmem/rpma/1196#-MhDkqfsB2aU1qqkuAe4:-MhEc5wq-DXjTjire_Bj:bw92acu) ([raw file](https://github.com/pmem/rpma/blob/02bf814a6dde35dafbad2a81368437b56d87d51f/tools/perf/lib/Report.py#L71)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This one is tricky. This is because of how we parse the provided input JSON files.

Ref: https://github.com/pmem/rpma/blob/master/tools/perf/lib/common.py#L25
</blockquote></details>

that's your scripts :wink:

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1196)* status: 4 of 9 files reviewed, all discussions resolved (waiting on @janekmi)

___
*[tools/perf/lib/Report.py, line 71 at r1](https://reviewable.io/reviews/pmem/rpma/1196#-MhDkqfsB2aU1qqkuAe4:-MhICRKlBdKGxyyafoUg:b-5y9say) ([raw file](https://github.com/pmem/rpma/blob/02bf814a6dde35dafbad2a81368437b56d87d51f/tools/perf/lib/Report.py#L71)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

that's your scripts :wink:
</blockquote></details>

I'm not a fan of the current solution either. If you have an idea for a better, more comprehensible solution please let me know. :-)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 6 of 7 files at r1, 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1196)* status: 7 of 9 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/Report.py, line 57 at r3](https://reviewable.io/reviews/pmem/rpma/1196#-MhT6QdV2MlCg3tSJ-ad:-MhT6QdV2MlCg3tSJ-ae:bpj2ixd) ([raw file](https://github.com/pmem/rpma/blob/613079df1c12fca0b9922974d5b4a57b0101a510/tools/perf/lib/Report.py#L57)):*
> ```
> inReport
> ```

`in Report`

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1196)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/tests/lib/bench/test_new.py, line 32 at r3](https://reviewable.io/reviews/pmem/rpma/1196#-MhTLqexE5NV4-sJ891s:-MhTLqexE5NV4-sJ891t:b-qpwljk) ([raw file](https://github.com/pmem/rpma/blob/613079df1c12fca0b9922974d5b4a57b0101a510/tools/perf/tests/lib/bench/test_new.py#L32)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>     {
>         'dummy_key_1': 'dummy_value_1',
>         'dummy_key_2': 'dummy_value_2'
>     }
> ```
</details>


Duplicated code. Can we do it in this way?

```
DUMMY = {
    'dummy_key_1': 'dummy_value_1',
    'dummy_key_2': 'dummy_value_2'
}

CONFIG_DUMMY = DUMMY

FIGURES_DUMMY = [ DUMMY ]
```

**Review by osalyk — COMMENTED** [review]
:goat: 

> Reviewed 5 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1196#-:-MhmVDkI7vg8KUEc5wtB:bdycpsm)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1196)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/lib/Report.py, line 57 at r3](https://reviewable.io/reviews/pmem/rpma/1196#-MhT6QdV2MlCg3tSJ-ad:-MhmDIVjBW_hZW4uzCN6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/613079df1c12fca0b9922974d5b4a57b0101a510/tools/perf/lib/Report.py#L57)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> inReport
> ```

`in Report`
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/bench/test_new.py, line 32 at r3](https://reviewable.io/reviews/pmem/rpma/1196#-MhTLqexE5NV4-sJ891s:-MhmWWATB_xKDw47EYTR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/613079df1c12fca0b9922974d5b4a57b0101a510/tools/perf/tests/lib/bench/test_new.py#L32)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>     {
>         'dummy_key_1': 'dummy_value_1',
>         'dummy_key_2': 'dummy_value_2'
>     }
> ```

Duplicated code. Can we do it in this way?

```
DUMMY = {
    'dummy_key_1': 'dummy_value_1',
    'dummy_key_2': 'dummy_value_2'
}

CONFIG_DUMMY = DUMMY

FIGURES_DUMMY = [ DUMMY ]
```

</blockquote></details>

Done.

**Pull request merged**
