### PR TITLE
test: update suppression of ucma_init()

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1860)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1860)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`tests/drd.supp` line 190 at r1](https://reviewable.io/reviews/pmem/rpma/1860#-N59qdIr0RbNT0MgkP1S:-N59rmsV9t4b3y5tAYO0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6eaeb1849dd0a759bb85bcfa5214e37be0e4a8e0/tests/drd.supp#L190)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

# Occurs in traces of:
# - rpma_utils_get_ibv_context
...

</blockquote></details>

Done.

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1860#-:-N5EN-ge7LnPhlwkA8Ae:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1860)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`tests/helgrind.supp` line 170 at r2](https://reviewable.io/reviews/pmem/rpma/1860#-N5EvWQz0eTyrLtEBt46:-N5EvWQz0eTyrLtEBt47:b-6pm7qh) ([raw file](https://github.com/pmem/rpma/blob/1bcfe077683cfada7109c735ac508deb876c86a1/tests/helgrind.supp#L170)):*
> ```
>    ...
>    fun:ucma_init
>    ...
> ```

Let's put rdma entry point



_Suggestion:_
```
...
fun:rdma_getaddrinfo
...
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1860)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72 and @osalyk)

___
*[`tests/helgrind.supp` line 170 at r2](https://reviewable.io/reviews/pmem/rpma/1860#-N5EvWQz0eTyrLtEBt46:-N5EwgcW0CMyMEaDDo_f:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1bcfe077683cfada7109c735ac508deb876c86a1/tests/helgrind.supp#L170)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Let's put rdma entry point
</blockquote></details>

Done.

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1860#-:-N5F-Dzv9LnnBCJlGjn7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
