### PR TITLE
rpma: make the librpma.h comply the new chars line limit

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1993)

### CODE REVIEW

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1993#-:-NA9Nd-w2nsdhmlfnXWw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72 and @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1993)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[`CHANGELOG.md` line 77 at r1](https://reviewable.io/reviews/pmem/rpma/1993#-NA9NR_S3kFoeuZh2OWb:-NA9NR_S3kFoeuZh2OWc:b-zf7ft5) ([raw file](https://github.com/pmem/rpma/blob/8f72af0ac2cd505419787d93e8b3d14c0cf45f8e/CHANGELOG.md#L77)):*
> ```Markdown
>   - TESTS_PERF_TOOLS - from ON to OFF
> 
>  - all examples and internal API files now comply the new character limit per line (100 characters)
> ```

`comply with` ?
`now` at the end ?

`all examples and internal API files comply with the new character limit per line (100 characters)  now`



_Code quote:_
```Markdown
all examples and internal API files now comply the new character limit per line (100 characters)
```
___
*[`src/include/librpma.h` line 227 at r1](https://reviewable.io/reviews/pmem/rpma/1993#-NA9O3jB9wNImqMJBhbK:-NA9O3jB9wNImqMJBhbL:be9henu) ([raw file](https://github.com/pmem/rpma/blob/8f72af0ac2cd505419787d93e8b3d14c0cf45f8e/src/include/librpma.h#L227)):*
> ```objc
>  * When you have a file descriptor, you can make it non-blocking using fcntl(2) as follows:
>  *
>  *      int ret = fcntl(fd, F_GETFL);
> ```

Tabs instead of spaces in case of code snippets



_Code quote:_
```objc
 *      int ret = fcntl(fd, F_GETFL);
 *      fcntl(fd, F_SETFL, flags | O_NONBLOCK);
```

**Review by grom72 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1993)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1993)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[`CHANGELOG.md` line 77 at r1](https://reviewable.io/reviews/pmem/rpma/1993#-NA9NR_S3kFoeuZh2OWb:-NA9S1uC1FqitDddAxAz:b-xndyqh) ([raw file](https://github.com/pmem/rpma/blob/8f72af0ac2cd505419787d93e8b3d14c0cf45f8e/CHANGELOG.md#L77)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`comply with` ?
`now` at the end ?

`all examples and internal API files comply with the new character limit per line (100 characters)  now`
</blockquote></details>

'comply with' done but 'now' sounds better in the middle
___
*[`src/include/librpma.h` line 227 at r1](https://reviewable.io/reviews/pmem/rpma/1993#-NA9O3jB9wNImqMJBhbK:-NA9S0Kk12EAwZp6upju:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8f72af0ac2cd505419787d93e8b3d14c0cf45f8e/src/include/librpma.h#L227)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Tabs instead of spaces in case of code snippets
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1993)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[`CHANGELOG.md` line 77 at r1](https://reviewable.io/reviews/pmem/rpma/1993#-NA9NR_S3kFoeuZh2OWb:-NA9Uh878TkZwOQrM8Kx:b32w0x) ([raw file](https://github.com/pmem/rpma/blob/8f72af0ac2cd505419787d93e8b3d14c0cf45f8e/CHANGELOG.md#L77)):*
<details><summary><i>Previously, haichangsi (Kacper Stefanski) wrote…</i></summary><blockquote>

'comply with' done but 'now' sounds better in the middle
</blockquote></details>

OK
___
*[`src/include/librpma.h` line 227 at r1](https://reviewable.io/reviews/pmem/rpma/1993#-NA9O3jB9wNImqMJBhbK:-NA9UozFD4zlTYm4Uqfi:b-32whdn) ([raw file](https://github.com/pmem/rpma/blob/8f72af0ac2cd505419787d93e8b3d14c0cf45f8e/src/include/librpma.h#L227)):*
<details><summary><i>Previously, haichangsi (Kacper Stefanski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet, please remove one space before the tab.

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1993)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`src/include/librpma.h` line 227 at r1](https://reviewable.io/reviews/pmem/rpma/1993#-NA9O3jB9wNImqMJBhbK:-NA9VIoe4BJ3QElbsadl:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8f72af0ac2cd505419787d93e8b3d14c0cf45f8e/src/include/librpma.h#L227)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not yet, please remove one space before the tab.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1993#-:-NA9VdIbB4RuedzYUpnH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
