### PR TITLE
doc: librpma.7: Server Operation

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/491)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/491)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 76 at r1](https://reviewable.io/reviews/pmem/rpma/491#-MITHcr68Q0kGfCz0Czp:-MITHcr68Q0kGfCz0Czq:b-iued0c) ([raw file](https://github.com/pmem/rpma/blob/d97c9d2872c9fe509bbb7798951d7d5ca952eb8e/src/include/librpma.h#L76)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>  * - rpma_conn_next_event - wait for RPMA_CONN_CLOSED event
>  * - rpma_conn_disconnect - disconnect the connection
>  * - rpma_conn_delete - delete the closed connection
>  * - rpma_ep_shutdown - stop listening and delete the endpoint
> ```
</details>

this is not clear for me  - is it a part of establish procedure?
___
*[src/include/librpma.h, line 77 at r1](https://reviewable.io/reviews/pmem/rpma/491#-MITIDH-8zwB3s3tW7vN:-MITIDH04s2kw0-Xt73h:brjvq07) ([raw file](https://github.com/pmem/rpma/blob/d97c9d2872c9fe509bbb7798951d7d5ca952eb8e/src/include/librpma.h#L77)):*
> ```
>  * - rpma_conn_delete - delete the closed connection
>  * - rpma_ep_shutdown - stop listening and delete the endpoint
> ```
shall be this part added as the last stage of connection establishment - 
"as soon as no more connection is expected we could close ep ..."

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/491)* status: all files reviewed, 10 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 64 at r1](https://reviewable.io/reviews/pmem/rpma/491#-MITWl9TDwK4TU4U0W2J:-MITWl9TDwK4TU4U0W2K:bpsqi0l) ([raw file](https://github.com/pmem/rpma/blob/d97c9d2872c9fe509bbb7798951d7d5ca952eb8e/src/include/librpma.h#L64)):*
> ```
> a passive side
> ```

the passive side
___
*[src/include/librpma.h, line 73 at r1](https://reviewable.io/reviews/pmem/rpma/491#-MITX2sy0BprSdKE0uOM:-MITX2sy0BprSdKE0uON:beonfo0) ([raw file](https://github.com/pmem/rpma/blob/d97c9d2872c9fe509bbb7798951d7d5ca952eb8e/src/include/librpma.h#L73)):*
> ```
> RPMA_CONN_ESTABLISHED event
> ```

the RPMA_CONN_ESTABLISHED event
___
*[src/include/librpma.h, line 75 at r1](https://reviewable.io/reviews/pmem/rpma/491#-MITX5lC8cxrCSQHHrx_:-MITX5lC8cxrCSQHHrxa:b7uxl5a) ([raw file](https://github.com/pmem/rpma/blob/d97c9d2872c9fe509bbb7798951d7d5ca952eb8e/src/include/librpma.h#L75)):*
> ```
> RPMA_CONN_CLOSED event
> ```

the RPMA_CONN_CLOSED event
___
*[src/include/librpma.h, line 1178 at r1](https://reviewable.io/reviews/pmem/rpma/491#-MITXIpZDuaMmTbqg9mZ:-MITXIpZDuaMmTbqg9m_:bsc3pem) ([raw file](https://github.com/pmem/rpma/blob/d97c9d2872c9fe509bbb7798951d7d5ca952eb8e/src/include/librpma.h#L1178)):*
> ```
> tear-down the connection
> ```

tear the connection down
___
*[src/include/librpma.h, line 1188 at r1](https://reviewable.io/reviews/pmem/rpma/491#-MITXM6p5qVrPS6pvYUu:-MITXM6p5qVrPS6pvYUv:b-okd2uq) ([raw file](https://github.com/pmem/rpma/blob/d97c9d2872c9fe509bbb7798951d7d5ca952eb8e/src/include/librpma.h#L1188)):*
> ```
> tears-down the connection.
> ```

tears the connection down.
___
*[src/include/librpma.h, line 1191 at r1](https://reviewable.io/reviews/pmem/rpma/491#-MITYwFPCZFJnPN2N8Ko:-MITYwFPCZFJnPN2N8Kp:b-cwqr3f) ([raw file](https://github.com/pmem/rpma/blob/d97c9d2872c9fe509bbb7798951d7d5ca952eb8e/src/include/librpma.h#L1191)):*
> ```
> is notified by RPMA_CONN_CLOSED event
> ```

is **signalled** by **the** RPMA_CONN_CLOSED event
___
*[src/include/librpma.h, line 1192 at r1](https://reviewable.io/reviews/pmem/rpma/491#-MITZ29p5QzQON17q0Gc:-MITZ29p5QzQON17q0Gd:bls6wyf) ([raw file](https://github.com/pmem/rpma/blob/d97c9d2872c9fe509bbb7798951d7d5ca952eb8e/src/include/librpma.h#L1192)):*
> ```
> t(). OR
> ```

1) no '.' full stop
2) why OR and not 'or'?
___
*[src/include/librpma.h, line 1425 at r1](https://reviewable.io/reviews/pmem/rpma/491#-MITZJ7X6q-7EcsZgVmk:-MITZJ7X6q-7EcsZgVml:b-c38etq) ([raw file](https://github.com/pmem/rpma/blob/d97c9d2872c9fe509bbb7798951d7d5ca952eb8e/src/include/librpma.h#L1425)):*
> ```
> delete 
> ```

deletes

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/491)* status: 0 of 1 files reviewed, 10 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/include/librpma.h, line 64 at r1](https://reviewable.io/reviews/pmem/rpma/491#-MITWl9TDwK4TU4U0W2J:-MIU2QAJ7YtrC7gAt40l:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d97c9d2872c9fe509bbb7798951d7d5ca952eb8e/src/include/librpma.h#L64)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> a passive side
> ```

the passive side
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 73 at r1](https://reviewable.io/reviews/pmem/rpma/491#-MITX2sy0BprSdKE0uOM:-MIU2mLY6uXW6L4Wfp_B:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d97c9d2872c9fe509bbb7798951d7d5ca952eb8e/src/include/librpma.h#L73)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> RPMA_CONN_ESTABLISHED event
> ```

the RPMA_CONN_ESTABLISHED event
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 75 at r1](https://reviewable.io/reviews/pmem/rpma/491#-MITX5lC8cxrCSQHHrx_:-MIU2oJ8BF-XXaSRZJlG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d97c9d2872c9fe509bbb7798951d7d5ca952eb8e/src/include/librpma.h#L75)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> RPMA_CONN_CLOSED event
> ```

the RPMA_CONN_CLOSED event
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 76 at r1](https://reviewable.io/reviews/pmem/rpma/491#-MITHcr68Q0kGfCz0Czp:-MIU2ph15rbCDKqifZMX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d97c9d2872c9fe509bbb7798951d7d5ca952eb8e/src/include/librpma.h#L76)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
>  * - rpma_conn_next_event - wait for RPMA_CONN_CLOSED event
>  * - rpma_conn_disconnect - disconnect the connection
>  * - rpma_conn_delete - delete the closed connection
>  * - rpma_ep_shutdown - stop listening and delete the endpoint
> ```
this is not clear for me  - is it a part of establish procedure?
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 77 at r1](https://reviewable.io/reviews/pmem/rpma/491#-MITIDH-8zwB3s3tW7vN:-MIU7buh1JL5CfkbibuK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d97c9d2872c9fe509bbb7798951d7d5ca952eb8e/src/include/librpma.h#L77)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
>  * - rpma_conn_delete - delete the closed connection
>  * - rpma_ep_shutdown - stop listening and delete the endpoint
> ```
shall be this part added as the last stage of connection establishment - 
"as soon as no more connection is expected we could close ep ..."
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1178 at r1](https://reviewable.io/reviews/pmem/rpma/491#-MITXIpZDuaMmTbqg9mZ:-MIU36BPAUmuJShICKIr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d97c9d2872c9fe509bbb7798951d7d5ca952eb8e/src/include/librpma.h#L1178)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> tear-down the connection
> ```

tear the connection down
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1188 at r1](https://reviewable.io/reviews/pmem/rpma/491#-MITXM6p5qVrPS6pvYUu:-MIU36ps7SM5VtApP3BL:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d97c9d2872c9fe509bbb7798951d7d5ca952eb8e/src/include/librpma.h#L1188)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> tears-down the connection.
> ```

tears the connection down.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1191 at r1](https://reviewable.io/reviews/pmem/rpma/491#-MITYwFPCZFJnPN2N8Ko:-MIU3BfM-fpFRJilcMnk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d97c9d2872c9fe509bbb7798951d7d5ca952eb8e/src/include/librpma.h#L1191)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> is notified by RPMA_CONN_CLOSED event
> ```

is **signalled** by **the** RPMA_CONN_CLOSED event
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1192 at r1](https://reviewable.io/reviews/pmem/rpma/491#-MITZ29p5QzQON17q0Gc:-MIU3GwqCa_5RFgUWSF_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d97c9d2872c9fe509bbb7798951d7d5ca952eb8e/src/include/librpma.h#L1192)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> t(). OR
> ```

1) no '.' full stop
2) why OR and not 'or'?
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1425 at r1](https://reviewable.io/reviews/pmem/rpma/491#-MITZJ7X6q-7EcsZgVmk:-MIU3MWjB3h4uIOKrTD8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d97c9d2872c9fe509bbb7798951d7d5ca952eb8e/src/include/librpma.h#L1425)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> delete 
> ```

deletes
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/491)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/491)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/491#-:-MIU9RbM9PbSynpdSoEw:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/491#-:-MIUkV798slvHh1lsZL7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/491#-:-MIUtebqEi3LANgeW55r:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
