### PR TITLE
Add SRQ feature

### PR DESCRIPTION
**Pull request by ultra-nexus**
* Implement SRQ
* Update testcases
* Update doc
* Add new example

Signed-off-by: Hao Li <lihao2018.fnst@cn.fujitsu.com>

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/685)

### CODE REVIEW

**Comment by ultra-nexus** [comment]
Any comments are welcome 😏 Hope I can refine my code under your instructions.

**Review by ldorau — COMMENTED** [review]
> Reviewed 10 of 43 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/685)* status: 10 of 48 files reviewed, all discussions resolved

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 11 of 43 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/685)* status: 17 of 48 files reviewed, 14 unresolved discussions (waiting on @ultra-nexus)

___
*[examples/10-messages-ping-pong-use-srq/CMakeLists.txt, line 9 at r2](https://reviewable.io/reviews/pmem/rpma/685#-MQY5ad-CaEewPwTIawr:-MQY5ad-CaEewPwTIaws:ba4j08t) ([raw file](https://github.com/pmem/rpma/blob/1cae8eac14c79c32c314ddd1f764bb8da78cfb1c/examples/10-messages-ping-pong-use-srq/CMakeLists.txt#L9)):*
> ```CMake
> project(messages-ping-pong C)
> 
> set(CMAKE_VERBOSE_MAKEFILE ON)
> ```

Not needed any more?
___
*[examples/10-messages-ping-pong-use-srq/CMakeLists.txt, line 38 at r2](https://reviewable.io/reviews/pmem/rpma/685#-MQY5dy-9FYI8-XL_NTF:-MQY5dy-9FYI8-XL_NTG:b-n9lw73) ([raw file](https://github.com/pmem/rpma/blob/1cae8eac14c79c32c314ddd1f764bb8da78cfb1c/examples/10-messages-ping-pong-use-srq/CMakeLists.txt#L38)):*
> ```CMake
> 	target_include_directories(example-${name}
> 		PRIVATE
> 			../../src
> ```

I think it should not be needed here.
___
*[examples/10-messages-ping-pong-use-srq/client.c, line 17 at r2](https://reviewable.io/reviews/pmem/rpma/685#-MQY5uVR77Ove80UYa_l:-MQY5uVS8l1RrCLY2F-I:b-6fuzrx) ([raw file](https://github.com/pmem/rpma/blob/1cae8eac14c79c32c314ddd1f764bb8da78cfb1c/examples/10-messages-ping-pong-use-srq/client.c#L17)):*
> ```C
> #include <sys/types.h>
> #include <unistd.h>
> #include <conn_cfg.h>
> ```

You can not use it directly. It is not part of the API. Sorry.
___
*[examples/10-messages-ping-pong-use-srq/client.c, line 34 at r2](https://reviewable.io/reviews/pmem/rpma/685#-MQY65mk6hwy14Iw63t3:-MQY65mk6hwy14Iw63t4:blbd58f) ([raw file](https://github.com/pmem/rpma/blob/1cae8eac14c79c32c314ddd1f764bb8da78cfb1c/examples/10-messages-ping-pong-use-srq/client.c#L34)):*
> ```C
> 	}
> 	return out;
> }
> ```

Since it is common for the 08 example and now the 10 example it should be moved to a kind of common e.g. examples/common/common-params.c
___
*[examples/10-messages-ping-pong-use-srq/client.c, line 102 at r2](https://reviewable.io/reviews/pmem/rpma/685#-MQY7bVLEDO0HYCXKKst:-MQY7bVM8rjs3JgK89W5:bufkvbv) ([raw file](https://github.com/pmem/rpma/blob/1cae8eac14c79c32c314ddd1f764bb8da78cfb1c/examples/10-messages-ping-pong-use-srq/client.c#L102)):*
> ```C
> 		.max_wr = 20,
> 		.max_sge = RPMA_MAX_SGE,
> 		.srq_limit = 10
> ```

What benefits of using SRQ this example shows?
___
*[examples/10-messages-ping-pong-use-srq/client.c, line 103 at r2](https://reviewable.io/reviews/pmem/rpma/685#-MQY6ot9CeT1EvILuHCt:-MQY6ot9CeT1EvILuHCu:b-avxyb0) ([raw file](https://github.com/pmem/rpma/blob/1cae8eac14c79c32c314ddd1f764bb8da78cfb1c/examples/10-messages-ping-pong-use-srq/client.c#L103)):*
> ```C
> 		.max_sge = RPMA_MAX_SGE,
> 		.srq_limit = 10
> 	};
> ```

This structure is not for direct use. You have to use / crease setters and getters.
___
*[examples/10-messages-ping-pong-use-srq/messages-ping-pong-use-srq-common.h, line 9 at r2](https://reviewable.io/reviews/pmem/rpma/685#-MQY55_X88kCUvGXlS54:-MQY55_Y2VqbAHHWM3g4:b-5zbd94) ([raw file](https://github.com/pmem/rpma/blob/1cae8eac14c79c32c314ddd1f764bb8da78cfb1c/examples/10-messages-ping-pong-use-srq/messages-ping-pong-use-srq-common.h#L9)):*
> ```objc
>  */
> 
> #ifndef EXAMPLES_MSG_PING_PONG_USE_SRQ_COMMON
> ```

USE -> WITH?
___
*[examples/10-messages-ping-pong-use-srq/messages-ping-pong-use-srq-common.h, line 20 at r2](https://reviewable.io/reviews/pmem/rpma/685#-MQY5CTmCeN6SeQglX7t:-MQY5CTmCeN6SeQglX7u:b-5fhmy3) ([raw file](https://github.com/pmem/rpma/blob/1cae8eac14c79c32c314ddd1f764bb8da78cfb1c/examples/10-messages-ping-pong-use-srq/messages-ping-pong-use-srq-common.h#L20)):*
> ```objc
> #define I_M_DONE	(uint64_t)UINT64_MAX
> 
> #endif /* EXAMPLES_MSG_PING_USE_SRQ_PONG_COMMON */
> ```

It is not a bit different compared to the 08 example's common.
Maybe just move this file to examples/common/common-msgs.h?
___
*[examples/10-messages-ping-pong-use-srq/README.md, line 1 at r2](https://reviewable.io/reviews/pmem/rpma/685#-MQY4pCC31M1DkFZCgfo:-MQY4pCC31M1DkFZCgfp:bnpvicw) ([raw file](https://github.com/pmem/rpma/blob/1cae8eac14c79c32c314ddd1f764bb8da78cfb1c/examples/10-messages-ping-pong-use-srq/README.md#L1)):*
> ```Markdown
> Example of using messaging
> ```

... with SRQ?
___
*[examples/10-messages-ping-pong-use-srq/README.md, line 13 at r2](https://reviewable.io/reviews/pmem/rpma/685#-MQY4eXB6v8E-wfdDUxa:-MQY4eXB6v8E-wfdDUxb:bymau8m) ([raw file](https://github.com/pmem/rpma/blob/1cae8eac14c79c32c314ddd1f764bb8da78cfb1c/examples/10-messages-ping-pong-use-srq/README.md#L13)):*
> ```Markdown
> When the client gets the new value from the server it repeats the process
> for the configured number of rounds. When it is quitting, it send the I_M_DONE
> message and disconnects.
> ```

I think we need here an SRQ reference.
___
*[examples/10-messages-ping-pong-use-srq/server.c, line 16 at r2](https://reviewable.io/reviews/pmem/rpma/685#-MQY7A792p2C_Ce5lCsj:-MQY7A792p2C_Ce5lCsk:b-3203kb) ([raw file](https://github.com/pmem/rpma/blob/1cae8eac14c79c32c314ddd1f764bb8da78cfb1c/examples/10-messages-ping-pong-use-srq/server.c#L16)):*
> ```C
> #include <sys/epoll.h>
> #include <unistd.h>
> #include <conn_cfg.h>
> ```

Not for direct use.
___
*[examples/10-messages-ping-pong-use-srq/server.c, line 90 at r2](https://reviewable.io/reviews/pmem/rpma/685#-MQY7HNu0myxMjk_mzUU:-MQY7HNu0myxMjk_mzUV:b-vqr6kb) ([raw file](https://github.com/pmem/rpma/blob/1cae8eac14c79c32c314ddd1f764bb8da78cfb1c/examples/10-messages-ping-pong-use-srq/server.c#L90)):*
> ```C
> 		.max_sge = RPMA_MAX_SGE,
> 		.srq_limit = 10
> 	};
> ```

Please use setters and getters.
___
*[examples/common/common-conn.c, line 66 at r2](https://reviewable.io/reviews/pmem/rpma/685#-MQY3wANA7jh51tRG45f:-MQY3wANA7jh51tRG45g:bjmi0uw) ([raw file](https://github.com/pmem/rpma/blob/1cae8eac14c79c32c314ddd1f764bb8da78cfb1c/examples/common/common-conn.c#L66)):*
> ```C
> client_connect(struct rpma_peer *peer, const char *addr, const char *port,
> 		struct rpma_conn_private_data *pdata,
> 		struct rpma_conn **conn_ptr, struct rpma_conn_cfg *cfg)
> ```

We have accepted a convention to have an output argument (conn_ptr) as the last one in this case.
___
*[src/peer.c, line 67 at r2](https://reviewable.io/reviews/pmem/rpma/685#-MQY8roI5NH3DyrZ6f-D:-MQY8roJ3DLqE4g0O0h3:b-e9pkfb) ([raw file](https://github.com/pmem/rpma/blob/1cae8eac14c79c32c314ddd1f764bb8da78cfb1c/src/peer.c#L67)):*
> ```C
> 		srq_init_attr.attr.max_sge = max_sge;
> 		srq_init_attr.attr.srq_limit = srq_limit;
> 		rdma_create_srq(id, peer->pd, &srq_init_attr);
> ```

The benefit of having SRQ is to have the possibility to share it between multiple connections.
Do you see any option for implementing such capability with your design?

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/685)* status: 17 of 48 files reviewed, 15 unresolved discussions (waiting on @ultra-nexus)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/685#-MQY9OaGEVDOLz0TffrS:-MQY9OaGEVDOLz0TffrT:bxw5kh7) (no related file):*
Hi @ultra-nexus! Thank you for starting this conversation. ;-)

After putting some comments I have realized this PR is in its early stage. So please ignore them for a moment a start with a question:

The benefit of having SRQ is to have the possibility to share it between multiple connections.
Do you see any option for implementing such capability with your design?

---

**Comment by ultra-nexus** [comment]
> The benefit of having SRQ is to have the possibility to share it between multiple connections.

I didn't realize this 😅 . If I understand correctly, when a client connects to the server, the server allocates a QP to handle the request and all QPs in server side share a SRQ.

> Do you see any option for implementing such capability with your design?

I will redesign the code to reflect this capability and I may focus on core code in `src/` directory. I want to update testcases after the core code seems reasonable. Thanks!

**Comment by ultra-nexus** [comment]
疯狂调试，最后有了些理解，目前在研究mult和shift的原理，与HZ的关系，TICK_NSEC什么意思

**Review by janekmi — COMMENTED** [review]
Ok. So please let us know where your PR is ready for reviewing the idea. :-)

> Besides, I think we need an example to illustrate how a server handles multiple client requests. I can also use it to test my SRQ patch. Could I submit such an example?

Have you seen this example: https://github.com/pmem/rpma/tree/master/examples/06-multiple-connections ?

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/685#-:-MRfdMP8CnA_5vX1U7Bt:b-3zhgt1)* status: 17 of 48 files reviewed, 15 unresolved discussions (waiting on @ultra-nexus)

**Comment by ultra-nexus** [comment]
> Have you seen this example: https://github.com/pmem/rpma/tree/master/examples/06-multiple-connections ?
> 
> > _[Reviewable](https://reviewable.io/reviews/pmem/rpma/685#-:-MRfdMP8CnA_5vX1U7Bt:b-3zhgt1)_ status: 17 of 48 files reviewed, 15 unresolved discussions (waiting on @ultra-nexus)

Thanks. This example is awesome! I didn't notice it before. As it doesn't use receive queue, I will write a ping pong example with multiple connection.

**Comment by ultra-nexus** [comment]
A new example is created at https://github.com/pmem/rpma/pull/783. I will use this example to test SRQ.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/685)* status: 17 of 48 files reviewed, 16 unresolved discussions (waiting on @ultra-nexus)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/685#-MTtNzRW8LfYamAhA-7t:-MTtNzRW8LfYamAhA-7u:b-8cioiv) (no related file):*
Please rebase.

---

**Comment by ultra-nexus** [comment]
@janekmi Hi. Sorry for the delay. I have re-implemented the SRQ. However, when testing it on real hardware, I encounter a problem that the data receiving is broken when enabling SRQ. It seems the Shared Receive Queue is completely messed up. I have struggled in this problem for a long time but can't solve it. At last, I push it to this PR and hope you can give me some hints about how to solve this. Thanks!

**Review by janekmi — COMMENTED** [review]
Hi @ultra-nexus. I will try tomorrow. In the meantime, I have taken a look at the API you have proposed. Do you see a way for the end-user to assign the same RQ to multiple connections?

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/685#-:-MUygtXl45NPOFmbLnSY:b1q8vod)* status: 0 of 7 files reviewed, 16 unresolved discussions (waiting on @ldorau and @ultra-nexus)

**Comment by ultra-nexus** [comment]
> 
> 
> Hi @ultra-nexus. I will try tomorrow. In the meantime, I have taken a look at the API you have proposed. Do you see a way for the end-user to assign the same RQ to multiple connections?
> 
> > _[Reviewable](https://reviewable.io/reviews/pmem/rpma/685#-:-MUygtXl45NPOFmbLnSY:b1q8vod)_ status: 0 of 7 files reviewed, 16 unresolved discussions (waiting on @ldorau and @ultra-nexus)

Hi, the SRQ pointer is saved in peer struct and all clients can use this SRQ to create QP.

**Review by janekmi — COMMENTED** [review]
Would you mind moving this discussion here: #958 ?
It will be useful to have a complete API proposition there eventually along with the general idea.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/685#-:-MW4HQwt-vqwEru3iu4U:blhrpb0)* status: 0 of 7 files reviewed, 16 unresolved discussions (waiting on @ldorau and @ultra-nexus)

**Review by ldorau — COMMENTED** [review]
> Reviewed 8 of 49 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/685)* status: 2 of 7 files reviewed, 17 unresolved discussions (waiting on @ultra-nexus)

___
*[CMakeLists.txt, line 38 at r3](https://reviewable.io/reviews/pmem/rpma/685#-MW4mSrT3aVqX2ZLgs1f:-MW4mSrT3aVqX2ZLgs1g:bi9k0v2) ([raw file](https://github.com/pmem/rpma/blob/f8ba94192772489a7a3cb03246e670ef65254c15/CMakeLists.txt#L38)):*
> ```
> option(BUILD_TESTS "build tests" OFF)
> ```

Why ?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/685)* status: 2 of 7 files reviewed, 17 unresolved discussions (waiting on @ultra-nexus)

___
*[CMakeLists.txt, line 38 at r3](https://reviewable.io/reviews/pmem/rpma/685#-MW4mSrT3aVqX2ZLgs1f:-MW4mtEV5Uf5y2USuN6F:b-hn3988) ([raw file](https://github.com/pmem/rpma/blob/f8ba94192772489a7a3cb03246e670ef65254c15/CMakeLists.txt#L38)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> option(BUILD_TESTS "build tests" OFF)
> ```

Why ?
</blockquote></details>

It cannot be changed and has to be reverted.

**Review by ultra-nexus — COMMENTED** [review]
Sure. Thanks

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/685#-:-MW7hC-G3JxULX4uGDZ1:b6hq02d)* status: 2 of 7 files reviewed, 17 unresolved discussions (waiting on @ldorau and @ultra-nexus)

___
*[CMakeLists.txt, line 38 at r3](https://reviewable.io/reviews/pmem/rpma/685#-MW4mSrT3aVqX2ZLgs1f:-MW7hE7c3HZUiyzmeokJ:bqdo7i5) ([raw file](https://github.com/pmem/rpma/blob/f8ba94192772489a7a3cb03246e670ef65254c15/CMakeLists.txt#L38)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It cannot be changed and has to be reverted.
</blockquote></details>

I'm not sure if my current implementation has problems, so I only modified the code in `src/` and haven't adjusted the testcases. I turn this option off to make the compilation successful. I will revert it.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/685)* status: 2 of 7 files reviewed, 17 unresolved discussions (waiting on @ultra-nexus)

___
*[CMakeLists.txt, line 38 at r3](https://reviewable.io/reviews/pmem/rpma/685#-MW4mSrT3aVqX2ZLgs1f:-MW8mQ9p-L8_KtPCE1jT:b-m6bee1) ([raw file](https://github.com/pmem/rpma/blob/f8ba94192772489a7a3cb03246e670ef65254c15/CMakeLists.txt#L38)):*
<details><summary><i>Previously, ultra-nexus wrote…</i></summary><blockquote>

I'm not sure if my current implementation has problems, so I only modified the code in `src/` and haven't adjusted the testcases. I turn this option off to make the compilation successful. I will revert it.
</blockquote></details>

OK, so please add a comment `/* XXX change it to ON when all tests pass */` here just to not forget about it

**Review by ultra-nexus — COMMENTED** [review]
I have fixed the problem I mentioned above. The problem is in my new example not in the implementation of SRQ.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/685#-:-MWRrUwL8fcVtTH1VtVk:bg6gm6g)* status: 2 of 7 files reviewed, 17 unresolved discussions (waiting on @ldorau and @ultra-nexus)

___
*[CMakeLists.txt, line 38 at r3](https://reviewable.io/reviews/pmem/rpma/685#-MW4mSrT3aVqX2ZLgs1f:-MWRqgaaCplRyMEnxT9i:b2nhll9) ([raw file](https://github.com/pmem/rpma/blob/f8ba94192772489a7a3cb03246e670ef65254c15/CMakeLists.txt#L38)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK, so please add a comment `/* XXX change it to ON when all tests pass */` here just to not forget about it
</blockquote></details>

Ok.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/685)* status: 8 of 49 files reviewed, 17 unresolved discussions (waiting on @janekmi, @ldorau, and @ultra-nexus)

___
*[CMakeLists.txt, line 38 at r3](https://reviewable.io/reviews/pmem/rpma/685#-MW4mSrT3aVqX2ZLgs1f:-MfHPGY90fwy6wbT6RFJ:b-ssc0t3) ([raw file](https://github.com/pmem/rpma/blob/f8ba94192772489a7a3cb03246e670ef65254c15/CMakeLists.txt#L38)):*
<details><summary><i>Previously, ultra-nexus wrote…</i></summary><blockquote>

Ok.
</blockquote></details>

You haven't added the comment yet.

**Comment by janekmi** [comment]
@ultra-nexus, I hope you are doing well. We miss you. I will be pleased to reopen this ancient PR for you when you will be ready. Cheers!

**Pull request closed without merging**
