### PR TITLE
common: correct the path of check-ms-license.pl

### PR DESCRIPTION
**Pull request by yangx-jy**
fix the following error when running 'make check-license': 
---------------------------------------------------------
 Checking copyright headers of all files...
../utils/check_license/check-headers.sh: line 191: \
    ../utils/check_license/check-ms-license.pl: No such file or directory
...
---------------------------------------------------------

Signed-off-by: Xiao Yang <yangx.jy@fujitsu.com>

- - -
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/2035)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2035)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2035#-NCZSERX6g65KjwwWpHF:-NCZSERX6g65KjwwWpHG:b2qtuew) (no related file):*
Please add info about it to CHANGELOG.md.

___

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2035)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2035)* status: all files reviewed, 4 unresolved discussions (waiting on @yangx-jy)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/pmem/rpma/2035#-NCZTBEZ0JPx_whLklMq):*
Fix



_Code quote:_
```
fix
```
___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/pmem/rpma/2035#-NCZSza904DVps1kNPWD):*
Maybe just an empty line instead of this?



_Code quote:_
```
  ---------------------------------------------------------
```
___
*[`-- commits` line 10 at r1](https://reviewable.io/reviews/pmem/rpma/2035#-NCZT42z096rdXq1XJ7O):*
Maybe remove it? IMHO it looks better without this line.



_Code quote:_
```
  ---------------------------------------------------------
```

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2035#-:-NCZiEHzAN0l2wl_O4Cd:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @yangx-jy)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2035#-:-NC_GRfI94mu0gIHfBPP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Pull request merged**
