### PR TITLE
common: add missing CMake file

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1284)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1284#-:-MjdCEoE-zNZysRvzJ10:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1284)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[cmake/FindLIBRPMA.cmake, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/1284#-MjdDBtu1tqrMizlQ31z:-MjdDBtvAoh2N3GpJOiy:bck022z) ([raw file](https://github.com/pmem/rpma/blob/10a2e39cbaf51ebbc26957b28a4fd7df8a007b45/cmake/FindLIBRPMA.cmake#L20)):*
> ```CMake
> 		message(WARNING ${MSG_NOT_FOUND})
> 	endif()
> endif()
> ```

Why do we need this one?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1284)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[cmake/FindLIBRPMA.cmake, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/1284#-MjdDBtu1tqrMizlQ31z:-MjdFHQd6VI_arYPZS7u:bwidge) ([raw file](https://github.com/pmem/rpma/blob/10a2e39cbaf51ebbc26957b28a4fd7df8a007b45/cmake/FindLIBRPMA.cmake#L20)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Why do we need this one?
</blockquote></details>

Examples need it:
```
./examples/01-connection/CMakeLists.txt:25:	find_package(LIBRPMA REQUIRED librpma)
./examples/02-read-to-volatile/CMakeLists.txt:25:	find_package(LIBRPMA REQUIRED librpma)
./examples/03-read-to-persistent/CMakeLists.txt:28:	find_package(LIBRPMA REQUIRED librpma)
./examples/04-write-to-persistent/CMakeLists.txt:28:	find_package(LIBRPMA REQUIRED librpma)
./examples/05-flush-to-persistent/CMakeLists.txt:28:	find_package(LIBRPMA REQUIRED librpma)
./examples/06-multiple-connections/CMakeLists.txt:30:	find_package(LIBRPMA REQUIRED librpma)
./examples/07-atomic-write/CMakeLists.txt:30:	find_package(LIBRPMA REQUIRED librpma)
./examples/08-messages-ping-pong/CMakeLists.txt:24:	find_package(LIBRPMA REQUIRED librpma)
./examples/09-flush-to-persistent-GPSPM/CMakeLists.txt:29:	find_package(LIBRPMA REQUIRED librpma)
./examples/10-send-with-imm/CMakeLists.txt:25:	find_package(LIBRPMA REQUIRED librpma)
./examples/11-write-with-imm/CMakeLists.txt:24:	find_package(LIBRPMA REQUIRED librpma)
./examples/template-example/CMakeLists.txt:23:	find_package(LIBRPMA REQUIRED librpma)
```

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1284)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[cmake/FindLIBRPMA.cmake, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/1284#-MjdDBtu1tqrMizlQ31z:-Mje6sct12pwE_NtzIR9:bkk6qrt) ([raw file](https://github.com/pmem/rpma/blob/10a2e39cbaf51ebbc26957b28a4fd7df8a007b45/cmake/FindLIBRPMA.cmake#L20)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Examples need it:
```
./examples/01-connection/CMakeLists.txt:25:	find_package(LIBRPMA REQUIRED librpma)
./examples/02-read-to-volatile/CMakeLists.txt:25:	find_package(LIBRPMA REQUIRED librpma)
./examples/03-read-to-persistent/CMakeLists.txt:28:	find_package(LIBRPMA REQUIRED librpma)
./examples/04-write-to-persistent/CMakeLists.txt:28:	find_package(LIBRPMA REQUIRED librpma)
./examples/05-flush-to-persistent/CMakeLists.txt:28:	find_package(LIBRPMA REQUIRED librpma)
./examples/06-multiple-connections/CMakeLists.txt:30:	find_package(LIBRPMA REQUIRED librpma)
./examples/07-atomic-write/CMakeLists.txt:30:	find_package(LIBRPMA REQUIRED librpma)
./examples/08-messages-ping-pong/CMakeLists.txt:24:	find_package(LIBRPMA REQUIRED librpma)
./examples/09-flush-to-persistent-GPSPM/CMakeLists.txt:29:	find_package(LIBRPMA REQUIRED librpma)
./examples/10-send-with-imm/CMakeLists.txt:25:	find_package(LIBRPMA REQUIRED librpma)
./examples/11-write-with-imm/CMakeLists.txt:24:	find_package(LIBRPMA REQUIRED librpma)
./examples/template-example/CMakeLists.txt:23:	find_package(LIBRPMA REQUIRED librpma)
```
</blockquote></details>

Does it also look for the librpma binary in the build directory? Or it has to be installed in the system?

**Comment by yangx-jy** [comment]
___
*[cmake/FindLIBRPMA.cmake, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/1284#-MjdDBtu1tqrMizlQ31z:-Mjh3ccwCDM6oPrAcxGg:b-h3m3vl) ([raw file](https://github.com/pmem/rpma/blob/10a2e39cbaf51ebbc26957b28a4fd7df8a007b45/cmake/FindLIBRPMA.cmake#L20)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Does it also look for the librpma binary in the build directory? Or it has to be installed in the system?
</blockquote></details>

I think this one is not needed becasue examples look for the librpma binary in the system.
BTW: examples look for the librpma binary by `rpma/examples/cmake/FindLIBRPMA.cmake`

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1284)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[cmake/FindLIBRPMA.cmake, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/1284#-MjdDBtu1tqrMizlQ31z:-MjmB5B_5MfcEQRetZQj:b-k3mncm) ([raw file](https://github.com/pmem/rpma/blob/10a2e39cbaf51ebbc26957b28a4fd7df8a007b45/cmake/FindLIBRPMA.cmake#L20)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

I think this one is not needed becasue examples look for the librpma binary in the system.
BTW: examples look for the librpma binary by `rpma/examples/cmake/FindLIBRPMA.cmake`
</blockquote></details>

Right, examples have their own `FindLIBRPMA.cmake` file. I have missed it. Thanks!

Removed.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1284#-:-MjmfWdT0BAd9EIkLrL1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
