### PR TITLE
tools: add f(cpuload) to the AOF mode in report_bench.sh

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/944)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/944)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/944#-MW3qGD69oe86SbtuOIl:-MW3qGD69oe86SbtuOIm:b7rrd67) (no related file):*
**Note**: `rpma_fio_bench.sh` does not support `*-cpu*` modes for the `aof_*` yet.

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/944)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/944#-MW3qGD69oe86SbtuOIl:-MW46IFg5UGgG7zqYDwd:b-piwl8w) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

**Note**: `rpma_fio_bench.sh` does not support `*-cpu*` modes for the `aof_*` yet.
</blockquote></details>

https://github.com/pmem/rpma/pull/956

https://github.com/pmem/fio/pull/252

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/944)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/944#-MW3qGD69oe86SbtuOIl:-MW4VffY3R8Hn6LWy7Um:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

https://github.com/pmem/rpma/pull/956

https://github.com/pmem/fio/pull/252
</blockquote></details>

Done.

---

**Review by janekmi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/944#-:-MW4W5of-ljS-6MRjLFg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/944#-:-MW4XyA36sc9WtldL7t6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
