### PR TITLE
tools: print message at the beginning of the benchmark

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1399)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1399)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1399)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1399#-MqL0dRc1t62iIrenQBY:-MqL0dRc1t62iIrenQBZ:b-gsjzz8) (no related file):*
Can you attach an example message?

---

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1399)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 157 at r1](https://reviewable.io/reviews/pmem/rpma/1399#-MqO-JHn3QLA3C2gvRCW:-MqO-JHn3QLA3C2gvRCX:b-cevuu6) ([raw file](https://github.com/pmem/rpma/blob/115d2aad88cd2cea62a2bc806780a63990421a4a/tools/perf/lib/benchmark/runner/ib_read.py#L157)):*
> ```
> .format(self.__mode, self.__config['server_ip']))
> ```
Do we have any way to show here also self.__oneseries['tool'] and self.__oneseries['tool_mode']

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1399#-:-MqOC4JOBICxGOW-hu7V:bg7igkv)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1399)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1399#-MqL0dRc1t62iIrenQBY:-MqQuTqK01_9w3_smEeb:b-f4uoht) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Can you attach an example message?
</blockquote></details>

An example of the current version:
```
STARTING benchmark for MODE=lat IP=192.168.101.4 ...
```

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1399)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 157 at r1](https://reviewable.io/reviews/pmem/rpma/1399#-MqO-JHn3QLA3C2gvRCW:-MqR5Yay1NyIZRlkd0Wg:broubdk) ([raw file](https://github.com/pmem/rpma/blob/115d2aad88cd2cea62a2bc806780a63990421a4a/tools/perf/lib/benchmark/runner/ib_read.py#L157)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> .format(self.__mode, self.__config['server_ip']))
> ```
Do we have any way to show here also self.__oneseries['tool'] and self.__oneseries['tool_mode']
</blockquote></details>

Yes, done

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1399)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1399#-MqL0dRc1t62iIrenQBY:-MqR5qyj9uQ3pNVzSzSB:b-di2lsg) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

An example of the current version:
```
STARTING benchmark for MODE=lat IP=192.168.101.4 ...
```
</blockquote></details>

Now they look like that:
```
STARTING benchmark for MODE=lat TOOL=ib_read IP=192.168.1.100 ...
STARTING benchmark for MODE=lat TOOL=fio(apm) IP=192.168.1.100 ...
STARTING benchmark for MODE=lat TOOL=fio(apm) IP=192.168.1.100 ...
STARTING benchmark for MODE=bw-bs TOOL=ib_read IP=192.168.1.100 ...
STARTING benchmark for MODE=bw-bs TOOL=fio(apm) IP=192.168.1.100 ...
STARTING benchmark for MODE=bw-bs TOOL=fio(apm) IP=192.168.1.100 ...
STARTING benchmark for MODE=bw-th TOOL=ib_read IP=192.168.1.100 ...
STARTING benchmark for MODE=bw-th TOOL=fio(apm) IP=192.168.1.100 ...
STARTING benchmark for MODE=bw-th TOOL=fio(apm) IP=192.168.1.100 ...
STARTING benchmark for MODE=lat TOOL=fio(apm) IP=192.168.1.100 ...
STARTING benchmark for MODE=lat TOOL=fio(apm) IP=192.168.1.100 ...
STARTING benchmark for MODE=bw-bs TOOL=fio(apm) IP=192.168.1.100 ...
STARTING benchmark for MODE=bw-bs TOOL=fio(apm) IP=192.168.1.100 ...
STARTING benchmark for MODE=bw-th TOOL=fio(apm) IP=192.168.1.100 ...
STARTING benchmark for MODE=bw-th TOOL=fio(apm) IP=192.168.1.100 ...

```

---

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1399)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/lib/benchmark/runner/common.py, line 46 at r2](https://reviewable.io/reviews/pmem/rpma/1399#-MqTOKc--I6VHR0vVuJL:-MqTOKc0Cx4eporpGlMu:b-axllhh) ([raw file](https://github.com/pmem/rpma/blob/f8bc891c11a3e3250b5c7a6c2e86c213ed29bd0e/tools/perf/lib/benchmark/runner/common.py#L46)):*
> ```
> STARTING benchmark for MODE={} TOOL={} 
> ```
STARTING benchmark TOOL={} for MODE={}

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1399)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1399)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/perf/lib/benchmark/runner/common.py, line 46 at r2](https://reviewable.io/reviews/pmem/rpma/1399#-MqTOKc--I6VHR0vVuJL:-MqTUNdP5L1cSJfFptSB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f8bc891c11a3e3250b5c7a6c2e86c213ed29bd0e/tools/perf/lib/benchmark/runner/common.py#L46)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> STARTING benchmark for MODE={} TOOL={} 
> ```
STARTING benchmark TOOL={} for MODE={}  
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1399#-:-MqT_GYM3gr-ebG6HZNk:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1399)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1399#-MqT_aU99FD1KyhpmCCH:-MqT_aUA71NGsFHgRXfK:bqeplii) (no related file):*
@osalyk please review

---

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1399#-:-MqU93mA5RzdugMPTwwp:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Pull request merged**
