### PR TITLE
rpma: remove redundant code of GPSPM exapmles

### PR DESCRIPTION
**Pull request by grom72**
Put all common source code of GPSPM examples into one folder.

- - -
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/2012)

### CODE REVIEW

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2012#-:-NAxEOgiCNsO4qv9mfHe:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by haichangsi — COMMENTED** [review]
:lgtm:

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2012#-:-NAxT0JF5J0Yo5Wej3VK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2012)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
> Reviewed 15 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2012)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2012)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2012#-NBBLINTDGBlGB6kYxz0:-NBBLINTDGBlGB6kYxz1:b-xp9oyn) (no related file):*
Update CHANGELOG.md, please

___

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2012)* status: 3 of 27 files reviewed, 1 unresolved discussion (waiting on @haichangsi, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2012#-NBBLINTDGBlGB6kYxz0:-NBBOvOwEvKTltL0hw2R:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Update CHANGELOG.md, please
</blockquote></details>

Done.

___

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2012)* status: 3 of 27 files reviewed, 1 unresolved discussion (waiting on @haichangsi, @ldorau, and @osalyk)

**Review by ldorau — APPROVED** [review]
> Reviewed 16 of 19 files at r5, 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2012)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
