### PR TITLE
tools: complete the benchmarking.md file

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/667)

### CODE REVIEW

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/667)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/667#-:-MOad9GC7OBAbc2GEpNI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/667)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[tools/BENCHMARKING.md, line 73 at r1](https://reviewable.io/reviews/pmem/rpma/667#-MOfRpTvCqKj-10BxC2S:-MOfRpTvCqKj-10BxC2T:bduoy5a) ([raw file](https://github.com/pmem/rpma/blob/051e13907fe89ecbbf035972e44c766f7ddbb22b/tools/BENCHMARKING.md#L73)):*
> ```Markdown
>  - iterates over the block size (256B, 1024B, 4096B, 8192B, 65536B)
>  - thread = 1
>  - tx_depth = 2
> ```

Please leave an empty line here.
___
*[tools/BENCHMARKING.md, line 80 at r1](https://reviewable.io/reviews/pmem/rpma/667#-MOfRr-v9KclXTzjCGvE:-MOfRr-v9KclXTzjCGvF:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/051e13907fe89ecbbf035972e44c766f7ddbb22b/tools/BENCHMARKING.md#L80)):*
> ```Markdown
>  - iterates over the number of threads (1, 2, 4, 8, 12)
>  - block size = 4096B
>  - tx_depth = 2
> ```

.

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/667)* status: all files reviewed, 9 unresolved discussions (waiting on @osalyk)

___
*[tools/BENCHMARKING.md, line 87 at r1](https://reviewable.io/reviews/pmem/rpma/667#-MOfSGGrDWzUs68HYJ4z:-MOfSGGrDWzUs68HYJ5-:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/051e13907fe89ecbbf035972e44c766f7ddbb22b/tools/BENCHMARKING.md#L87)):*
> ```Markdown
>  - iterates over the tx_depth value increasing linearly (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
>  - thread = 1
>  - block size = 4096B
> ```

.
___
*[tools/BENCHMARKING.md, line 94 at r1](https://reviewable.io/reviews/pmem/rpma/667#-MOfSJPy5fqS_3gtrlWU:-MOfSJPy5fqS_3gtrlWV:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/051e13907fe89ecbbf035972e44c766f7ddbb22b/tools/BENCHMARKING.md#L94)):*
> ```Markdown
>  - iterates over the tx_depth value increasing exponentially (1, 2, 4, 8, 16, 32, 64, 128)
>  - thread = 1
>  - block size = 4096B
> ```

.
___
*[tools/BENCHMARKING.md, line 103 at r1](https://reviewable.io/reviews/pmem/rpma/667#-MOfSLqm00xDUDEu3flN:-MOfSLqm00xDUDEu3flO:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/051e13907fe89ecbbf035972e44c766f7ddbb22b/tools/BENCHMARKING.md#L103)):*
> ```Markdown
>  - iterates over the block size (256B, 1024B, 4096B, 8192B, 65536B)
>  - thread = 1
>  - iodepth = 2
> ```

.
___
*[tools/BENCHMARKING.md, line 110 at r1](https://reviewable.io/reviews/pmem/rpma/667#-MOfSMkU2kQGifUF-SJz:-MOfSMkU2kQGifUF-SK-:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/051e13907fe89ecbbf035972e44c766f7ddbb22b/tools/BENCHMARKING.md#L110)):*
> ```Markdown
>  - iterates over the number of threads (1, 2, 4, 8, 12, 16)
>  - block size = 4096B
>  - iodepth = 2
> ```

.
___
*[tools/BENCHMARKING.md, line 113 at r1](https://reviewable.io/reviews/pmem/rpma/667#-MOfSORQA72BLcTJiYI6:-MOfSORQA72BLcTJiYI7:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/051e13907fe89ecbbf035972e44c766f7ddbb22b/tools/BENCHMARKING.md#L113)):*
> ```Markdown
> ```sh
> $ ./rpma_fio_read.sh bw-th <SERVER_IP>
> ```
> ```

.
___
*[tools/BENCHMARKING.md, line 116 at r1](https://reviewable.io/reviews/pmem/rpma/667#-MOfSPDg8GC-HeO2v9Xc:-MOfSPDg8GC-HeO2v9Xd:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/051e13907fe89ecbbf035972e44c766f7ddbb22b/tools/BENCHMARKING.md#L116)):*
> ```Markdown
>  - iterates over the iodepth value increasing linearly (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
>  - thread = 1
>  - block size = 4096B
> ```

.
___
*[tools/BENCHMARKING.md, line 123 at r1](https://reviewable.io/reviews/pmem/rpma/667#-MOfSQF6CB5YaLSgYq8F:-MOfSQF6CB5YaLSgYq8G:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/051e13907fe89ecbbf035972e44c766f7ddbb22b/tools/BENCHMARKING.md#L123)):*
> ```Markdown
>  - iterates over the iodepth value increasing exponentially (1, 2, 4, 8, 16, 32, 64, 128)
>  - thread = 1
>  - block size = 4096B
> ```

.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/667)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/BENCHMARKING.md, line 73 at r1](https://reviewable.io/reviews/pmem/rpma/667#-MOfRpTvCqKj-10BxC2S:-MOfWR8i28pIxMolTycN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/051e13907fe89ecbbf035972e44c766f7ddbb22b/tools/BENCHMARKING.md#L73)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please leave an empty line here.
</blockquote></details>

Done.
___
*[tools/BENCHMARKING.md, line 80 at r1](https://reviewable.io/reviews/pmem/rpma/667#-MOfRr-v9KclXTzjCGvE:-MOfWh0-Em2FEHfcXq7o:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/051e13907fe89ecbbf035972e44c766f7ddbb22b/tools/BENCHMARKING.md#L80)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/BENCHMARKING.md, line 87 at r1](https://reviewable.io/reviews/pmem/rpma/667#-MOfSGGrDWzUs68HYJ4z:-MOfWhg-2C3Ie0TfjvRu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/051e13907fe89ecbbf035972e44c766f7ddbb22b/tools/BENCHMARKING.md#L87)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/BENCHMARKING.md, line 94 at r1](https://reviewable.io/reviews/pmem/rpma/667#-MOfSJPy5fqS_3gtrlWU:-MOfWi9pD1hO2UAmbQQM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/051e13907fe89ecbbf035972e44c766f7ddbb22b/tools/BENCHMARKING.md#L94)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/BENCHMARKING.md, line 103 at r1](https://reviewable.io/reviews/pmem/rpma/667#-MOfSLqm00xDUDEu3flN:-MOfWifE8BFpDpuF0DQd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/051e13907fe89ecbbf035972e44c766f7ddbb22b/tools/BENCHMARKING.md#L103)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/BENCHMARKING.md, line 110 at r1](https://reviewable.io/reviews/pmem/rpma/667#-MOfSMkU2kQGifUF-SJz:-MOfWjD77fgqi_o4FlAn:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/051e13907fe89ecbbf035972e44c766f7ddbb22b/tools/BENCHMARKING.md#L110)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/BENCHMARKING.md, line 113 at r1](https://reviewable.io/reviews/pmem/rpma/667#-MOfSORQA72BLcTJiYI6:-MOfWjfK7Nx5NV7SHloo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/051e13907fe89ecbbf035972e44c766f7ddbb22b/tools/BENCHMARKING.md#L113)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/BENCHMARKING.md, line 116 at r1](https://reviewable.io/reviews/pmem/rpma/667#-MOfSPDg8GC-HeO2v9Xc:-MOfWkGsD_-iL7Dy-CZ0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/051e13907fe89ecbbf035972e44c766f7ddbb22b/tools/BENCHMARKING.md#L116)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/BENCHMARKING.md, line 123 at r1](https://reviewable.io/reviews/pmem/rpma/667#-MOfSQF6CB5YaLSgYq8F:-MOfWknx9a8ZSxcHyDxf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/051e13907fe89ecbbf035972e44c766f7ddbb22b/tools/BENCHMARKING.md#L123)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/667)* status: all files reviewed, 9 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/667#-:-MOfXijf6_7_ZSxDYDQO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
