### PR TITLE
common: remove unused Dockerfiles and update INSTALL.md

### PR DESCRIPTION
**Pull request by ldorau**
Ref: #1511
Ref: 99c0b8e83cd64f719fff55a2dd4e12bc92a80a9d

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1523)

### CODE REVIEW

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1523#-:-MuVEKLL4ObjJsdmcjgu:bg7igkv)* status: 0 of 8 files reviewed, all discussions resolved

**Review by haichangsi — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1523#-:-MuhC_LO18Qt7_CudGpr:bg7igkv)* status: 0 of 8 files reviewed, all discussions resolved

**Review by haichangsi — COMMENTED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1523)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1523#-:-MujQRUgEH7cho3e8nq9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
