### PR TITLE
common: add CentOS Stream CI build to Nightly_Rebuild

### PR DESCRIPTION
**Pull request by ldorau**
There is NO official docker image of CentOS Stream,
so we use tgagor/centos-stream.

See:
https://hub.docker.com/r/tgagor/centos-stream/tags
https://timor.site/2021/02/centos-8-stream-docker-image/

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1278)

### CODE REVIEW

**Comment by ldorau** [comment]
All builds pass:
https://github.com/ldorau/rpma/actions/runs/1229010690

**Review by ldorau — COMMENTED** [review]
Notice: the Dockerfile has been copied from CentOS-8 - it simplifies review ;-)

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1278#-:-MjUmYQnEZzd5uGAwEUb:b-7y7go7)* status: 0 of 2 files reviewed, all discussions resolved

**Review by janekmi — CHANGES_REQUESTED** [review]
Thanks for the tip. :wink: 

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1278#-:-MjV1FbL3j59KaGUKvlo:bqz3pfe)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[.github/workflows/nightly_rebuild.yml, line 38 at r1](https://reviewable.io/reviews/pmem/rpma/1278#-MjV04N8-CNIvbARj1wK:-MjV01MK0JK4QkoCLYyv:b-jvo18r) ([raw file](https://github.com/pmem/rpma/blob/b391a5925829a0cdaa927db4b5f3e31b9ec3b909/.github/workflows/nightly_rebuild.yml#L38)):*
> ```YAML
>                  "N=Debian_Experimental  OS=debian               OS_VER=experimental   REBUILD_ALWAYS=YES",
>                  "N=Arch_Linux_Latest    OS=archlinux            OS_VER=latest         REBUILD_ALWAYS=YES",
>                  # there is NO official docker image of CentOS Stream, so we use tgagor/centos-stream
> ```

I think this message at this level is hard to relate to and duplicates with the one in the docker image file.
I think we can remove it from here.
___
*[utils/docker/images/Dockerfile.centos-stream-latest, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1278#-MjV0HyT4464NfZOvZgZ:-MjV0HyT4464NfZOvZg_:b9qrg6p) ([raw file](https://github.com/pmem/rpma/blob/b391a5925829a0cdaa927db4b5f3e31b9ec3b909/utils/docker/images/Dockerfile.centos-stream-latest#L13)):*
According to the author (https://hub.docker.com/r/tgagor/centos-stream):

> I decided to rebuild them weekly with all security patches and moved to new location: tgagor/centos. This one I will keep for backward compatibility (at least for some time).

I think we should use an image from the tgagor/centos. What do you think?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1278)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[.github/workflows/nightly_rebuild.yml, line 38 at r1](https://reviewable.io/reviews/pmem/rpma/1278#-MjV04N8-CNIvbARj1wK:-MjXmwY51gyYKkVcgBlh:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b391a5925829a0cdaa927db4b5f3e31b9ec3b909/.github/workflows/nightly_rebuild.yml#L38)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think this message at this level is hard to relate to and duplicates with the one in the docker image file.
I think we can remove it from here.
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.centos-stream-latest, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1278#-MjV0HyT4464NfZOvZgZ:-MjXmnxdAJ7hcCa-LOfw:blnv9xc) ([raw file](https://github.com/pmem/rpma/blob/b391a5925829a0cdaa927db4b5f3e31b9ec3b909/utils/docker/images/Dockerfile.centos-stream-latest#L13)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

According to the author (https://hub.docker.com/r/tgagor/centos-stream):

> I decided to rebuild them weekly with all security patches and moved to new location: tgagor/centos. This one I will keep for backward compatibility (at least for some time).

I think we should use an image from the tgagor/centos. What do you think?
</blockquote></details>

Right, I have missed it. Thanks!

Done.

**Review by ldorau — COMMENTED** [review]
New builds: https://github.com/ldorau/rpma/runs/3595104283?check_suite_focus=true

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1278#-:-MjXnOR61tk5n-0oNiT8:bc7rb56)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — CHANGES_REQUESTED** [review]
:goat: 

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1278#-:-MjY0UAK0o0Th90skRQg:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[.github/workflows/nightly_rebuild.yml, line 38 at r2](https://reviewable.io/reviews/pmem/rpma/1278#-MjY0Is4162ecXrpqew1:-MjY0Is4162ecXrpqew2:bfh9fgb) ([raw file](https://github.com/pmem/rpma/blob/14e36089284b260ecde2929e4ce8899d0bd9e7b8/.github/workflows/nightly_rebuild.yml#L38)):*
> ```YAML
>                  "N=Debian_Experimental  OS=debian               OS_VER=experimental   REBUILD_ALWAYS=YES",
>                  "N=Arch_Linux_Latest    OS=archlinux            OS_VER=latest         REBUILD_ALWAYS=YES",
>                  "N=CentOS-Stream        OS=centos               OS_VER=stream         REBUILD_ALWAYS=YES",
> ```

**Minor**: Why do you use `-` instead of `_` as the separator?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1278)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[.github/workflows/nightly_rebuild.yml, line 38 at r2](https://reviewable.io/reviews/pmem/rpma/1278#-MjY0Is4162ecXrpqew1:-MjY1Jjn5nn0ptyKmZlf:bwberni) ([raw file](https://github.com/pmem/rpma/blob/14e36089284b260ecde2929e4ce8899d0bd9e7b8/.github/workflows/nightly_rebuild.yml#L38)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

**Minor**: Why do you use `-` instead of `_` as the separator?
</blockquote></details>

Just a mistake, fixed.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1278#-:-MjYAy_R70o2J0C6Qkvf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1278#-:-MjYchEd7VCIKHsVhMdY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
