### PR TITLE
examples: change style of some messages

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/887)

### CODE REVIEW

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/887#-:-MTLpTKG-URM2lBkikdq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/887#-:-MTM15F7AdtsgI8SIfj6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by yangx-jy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/887)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[examples/11-write-with-imm/server.c, line 171 at r1](https://reviewable.io/reviews/pmem/rpma/887#-MT_jVfn0Exf8i7v2V7k:-MT_jVfn0Exf8i7v2V7l:bl6jago) ([raw file](https://github.com/pmem/rpma/blob/92dab0ab50b549d46a21a24433dbbc9fb77718a7/examples/11-write-with-imm/server.c#L171)):*
> ```
> 	} else {
> 		printf("Received value '%u' with immediate data '%u'\n",
> ```
Hi,

I think the previous message is clearer here, because value was written and immediate data is received.  Is there any other message instead?

Best Regards,
Xiao Yang

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/887)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @janekmi and @yangx-jy)

___
*[examples/11-write-with-imm/server.c, line 171 at r1](https://reviewable.io/reviews/pmem/rpma/887#-MT_jVfn0Exf8i7v2V7k:-MT_ovj7499-KvIK3gYo:bhffr4w) ([raw file](https://github.com/pmem/rpma/blob/92dab0ab50b549d46a21a24433dbbc9fb77718a7/examples/11-write-with-imm/server.c#L171)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

> ```
> 	} else {
> 		printf("Received value '%u' with immediate data '%u'\n",
> ```
Hi,

I think the previous message is clearer here, because value was written and immediate data is received.  Is there any other message instead?

Best Regards,
Xiao Yang
</blockquote></details>

Ah, I understand now what the previous message was intended to mean ... So maybe like that:
`"The value '%u' was written together with immediate data '%u'\n"` ?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/887)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @janekmi and @yangx-jy)

___
*[examples/11-write-with-imm/server.c, line 171 at r1](https://reviewable.io/reviews/pmem/rpma/887#-MT_jVfn0Exf8i7v2V7k:-MT_ppNI7hBmaixOKFca:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/92dab0ab50b549d46a21a24433dbbc9fb77718a7/examples/11-write-with-imm/server.c#L171)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Ah, I understand now what the previous message was intended to mean ... So maybe like that:
`"The value '%u' was written together with immediate data '%u'\n"` ?
</blockquote></details>

Done.

**Review by yangx-jy — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/887#-:-MT_rHcA85Hyo1ZPx04N:bnfp4nl)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
