### PR TITLE
common: file comment from environment

### PR DESCRIPTION
**Pull request by grom72**
The custom part of the filename is taken from the environment variable

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/733)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/733)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/733)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/rpma_fio_bench.sh, line 34 at r1](https://reviewable.io/reviews/pmem/rpma/733#-MQkGV9a8usWf5zYqUfX:-MQkGV9a8usWf5zYqUfY:b-awlm6h) ([raw file](https://github.com/pmem/rpma/blob/be965076c2bae0a90b1b771465664ea48a56be1c/tools/rpma_fio_bench.sh#L34)):*
> ```
> free_text_
> ```

`any_text_...`

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/733)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/733)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[tools/rpma_fio_bench.sh, line 34 at r1](https://reviewable.io/reviews/pmem/rpma/733#-MQkjfEVBZf5QjGHmBYE:-MQkjfEVBZf5QjGHmBYF:b9ku31z) ([raw file](https://github.com/pmem/rpma/blob/be965076c2bae0a90b1b771465664ea48a56be1c/tools/rpma_fio_bench.sh#L34)):*
> ```Shell
> 	echo "export REMOTE_JOB_PATH=/custom/jobs/path"
> 	echo "export REMOTE_JOB_MEM_PATH=/path/to/mem (required in case of the GPSPM mode)"
> 	echo "export CUSTOM_PART_OF_FILENAME=free_text_to_be_added_to_every_file_name"
> ```

I think we can give a name to this custom part of the filename. I would name it... a comment? ;-)
So I vote for:

```bash
export COMMENT=...
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/733)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[tools/rpma_fio_bench.sh, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/733#-MQl0YNZ1bH7axLb0jEO:-MQl0YN_5qmZGX5rmZoU:b-dd2xv4) ([raw file](https://github.com/pmem/rpma/blob/be965076c2bae0a90b1b771465664ea48a56be1c/tools/rpma_fio_bench.sh#L20)):*
> ```
>  <all|read|write> <all|bw-bs|bw-dp-exp|bw-dp-lin|bw-th|lat>
> ```

The brackets should not be changed:

```
 [all|read|write] [all|bw-bs|bw-dp-exp|bw-dp-lin|bw-th|lat]
```

AFAIK:
`<...>` - means obligatory options
`[...]` - means optional options

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/733)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[tools/rpma_fio_bench.sh, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/733#-MQl0YNZ1bH7axLb0jEO:-MQpIkQS2FBwWT45pO2r:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/be965076c2bae0a90b1b771465664ea48a56be1c/tools/rpma_fio_bench.sh#L20)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  <all|read|write> <all|bw-bs|bw-dp-exp|bw-dp-lin|bw-th|lat>
> ```

The brackets should not be changed:

```
 [all|read|write] [all|bw-bs|bw-dp-exp|bw-dp-lin|bw-th|lat]
```

AFAIK:
`<...>` - means obligatory options
`[...]` - means optional options
</blockquote></details>

Done.
___
*[tools/rpma_fio_bench.sh, line 34 at r1](https://reviewable.io/reviews/pmem/rpma/733#-MQkGV9a8usWf5zYqUfX:-MQpIlXmBXKfgmSVZzWt:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/be965076c2bae0a90b1b771465664ea48a56be1c/tools/rpma_fio_bench.sh#L34)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> free_text_
> ```

`any_text_...`
</blockquote></details>

Done.
___
*[tools/rpma_fio_bench.sh, line 34 at r1](https://reviewable.io/reviews/pmem/rpma/733#-MQkjfEVBZf5QjGHmBYE:-MQpIn0TDuojmNlZl_l6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/be965076c2bae0a90b1b771465664ea48a56be1c/tools/rpma_fio_bench.sh#L34)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we can give a name to this custom part of the filename. I would name it... a comment? ;-)
So I vote for:

```bash
export COMMENT=...
```
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/733)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/733)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/733#-:-MQpJB4wAHVJpdJ_Qqot:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/733)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/733#-:-MQpzLAs2OD-hXQIEUpL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
