### PR TITLE
examples: fix arguments of 08-messages-ping-pong example on SoftRoCE

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/341)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
:goat:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/341#-:-MGHrQhM34pxjG3JSCXd:bdycps0)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[examples/run-all-on-SoftRoCE.sh, line 64 at r1](https://reviewable.io/reviews/pmem/rpma/341#-MGHrAOI6dtaDsexITax:-MGHrAOI6dtaDsexITay:bemd8o3) ([raw file](https://github.com/pmem/rpma/blob/54f463c64a3dc42bfd1c44abfa365a7062c3a44c/examples/run-all-on-SoftRoCE.sh#L64)):*
> ```
>  $ROUNDS
> ```
$SLEEP is missing

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/341)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[examples/run-all-on-SoftRoCE.sh, line 64 at r1](https://reviewable.io/reviews/pmem/rpma/341#-MGHrAOI6dtaDsexITax:-MGHsqmm4H4m91OGyk_a:b-hfgd5m) ([raw file](https://github.com/pmem/rpma/blob/54f463c64a3dc42bfd1c44abfa365a7062c3a44c/examples/run-all-on-SoftRoCE.sh#L64)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
>  $ROUNDS
> ```
$SLEEP is missing
</blockquote></details>

it is optional

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/341)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[examples/run-all-on-SoftRoCE.sh, line 64 at r1](https://reviewable.io/reviews/pmem/rpma/341#-MGHrAOI6dtaDsexITax:-MGHuoJs8dBRvqBJdJtq:b-sczii4) ([raw file](https://github.com/pmem/rpma/blob/54f463c64a3dc42bfd1c44abfa365a7062c3a44c/examples/run-all-on-SoftRoCE.sh#L64)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

it is optional
</blockquote></details>

as word_2, word_3 in example above

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/341)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[examples/run-all-on-SoftRoCE.sh, line 64 at r1](https://reviewable.io/reviews/pmem/rpma/341#-MGHrAOI6dtaDsexITax:-MGHv7cTCH2u9o9bNRsO:bjcfj8t) ([raw file](https://github.com/pmem/rpma/blob/54f463c64a3dc42bfd1c44abfa365a7062c3a44c/examples/run-all-on-SoftRoCE.sh#L64)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

as word_2, word_3 in example above
</blockquote></details>

Yes, of course, I do not want to add sleeping because it makes the test lasts longer

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/341#-:-MGHwhjkDuNKfdJy4pgQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/341#-:-MGHy8w_1_X6quohsnps:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
