### PR TITLE
test: add rpma_ep_next_conn_req multithreaded test

### PR DESCRIPTION
**Pull request by ewanglong**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1023)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1023)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @ewanglong)

___
*[tests/multithreaded/common/mtt.c, line 339 at r1](https://reviewable.io/reviews/pmem/rpma/1023#-MZG--En0ZRuTYz1K2mt:-MZG--En0ZRuTYz1K2mu:b-ov4imm) ([raw file](https://github.com/pmem/rpma/blob/153d214dbdd6f03a1166a0986126cfb2da9620b7/tests/multithreaded/common/mtt.c#L339)):*
> ```C
> 			ret = pthread_tryjoin_np(threads[i], (void **)&tr);
> 			if (ret == EBUSY) {
> 				pthread_cancel(threads[i]);
> ```

Clever but it is not what we need here.
We need a client-side. Otherwise, we are testing only the first part of this API call (start -> wait for connection) completely omitting the second part (wait for completion -> stop).

@ldorau is currently engaged in developing a standard for handling both client and server threads. I will draft this PR till then.

In the meantime, I highly recommend taking a look here: https://github.com/pmem/rpma/issues/1007#issuecomment-824779298 since there you can find many API calls which do not require establishing a connection.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1023)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @ewanglong)

___
*[tests/multithreaded/common/mtt.c, line 339 at r1](https://reviewable.io/reviews/pmem/rpma/1023#-MZG--En0ZRuTYz1K2mt:-MZvQ6cR3-_6yIExpr8l:b-n4rgjs) ([raw file](https://github.com/pmem/rpma/blob/153d214dbdd6f03a1166a0986126cfb2da9620b7/tests/multithreaded/common/mtt.c#L339)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Clever but it is not what we need here.
We need a client-side. Otherwise, we are testing only the first part of this API call (start -> wait for connection) completely omitting the second part (wait for completion -> stop).

@ldorau is currently engaged in developing a standard for handling both client and server threads. I will draft this PR till then.

In the meantime, I highly recommend taking a look here: https://github.com/pmem/rpma/issues/1007#issuecomment-824779298 since there you can find many API calls which do not require establishing a connection.
</blockquote></details>

@ewanglong you can come back to this PR. Please take a look at how @ldorau has used the new MTT-framework feature which allows spawning a child process dedicated e.g. as another part of the connection: https://github.com/pmem/rpma/pull/1037

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1023)* status: 0 of 11 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tests/multithreaded/common/mtt.c, line 339 at r1](https://reviewable.io/reviews/pmem/rpma/1023#-MZG--En0ZRuTYz1K2mt:-M_1SC2NDBCyqybroduO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/153d214dbdd6f03a1166a0986126cfb2da9620b7/tests/multithreaded/common/mtt.c#L339)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

@ewanglong you can come back to this PR. Please take a look at how @ldorau has used the new MTT-framework feature which allows spawning a child process dedicated e.g. as another part of the connection: https://github.com/pmem/rpma/pull/1037
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 11 files at r1, 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1023)* status: all files reviewed, 22 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/ep/rpma_ep_next_conn_req.c, line 10 at r2](https://reviewable.io/reviews/pmem/rpma/1023#-M_5226R-D8ehE92nopk:-M_5226R-D8ehE92nopl:bbl3xqi) ([raw file](https://github.com/pmem/rpma/blob/338fa8259cf146832f26d69f4c26c2430777baf4/tests/multithreaded/ep/rpma_ep_next_conn_req.c#L10)):*
> ```C
> #include <stdlib.h>
> #include <pthread.h>
> #include <unistd.h>
> ```

These two are not needed.
___
*[tests/multithreaded/ep/rpma_ep_next_conn_req.c, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/1023#-M_5285wCxcePPHVJxQ1:-M_525xgDeJEGyrW4NzR:bp5xnqt) ([raw file](https://github.com/pmem/rpma/blob/338fa8259cf146832f26d69f4c26c2430777baf4/tests/multithreaded/ep/rpma_ep_next_conn_req.c#L15)):*
> ```C
> #include "mtt.h"
> 
> #define CHILD_PROCESS_DELAY_US		1000
> ```

It is not a robust solution. We have to develop a synchronization technique. I suggest using semaphores.
It requires a few more includes:

```c
#include <fcntl.h>
#include <sys/stat.h>
#include <semaphore.h>
```

Sadly, at this point of development, the only solution I can think of requires using two semaphores. So, both prestates require pointers to two semaphores:

```c
sem_t *ep_ready_sem;
sem_t *conn_reqs_ready_sem;
```

Please see other comments for more details.
___
*[tests/multithreaded/ep/rpma_ep_next_conn_req.c, line 47 at r2](https://reviewable.io/reviews/pmem/rpma/1023#-M_4sqC28Sut0sRPUcF3:-M_4sqC28Sut0sRPUcF4:b-3kar6d) ([raw file](https://github.com/pmem/rpma/blob/338fa8259cf146832f26d69f4c26c2430777baf4/tests/multithreaded/ep/rpma_ep_next_conn_req.c#L47)):*
> ```C
> 	if ((ret = rpma_utils_get_ibv_context(pr->addr,
> 			RPMA_UTIL_IBV_CONTEXT_LOCAL, &pr->dev)))
> 		MTT_RPMA_ERR(tr, "rpma_utils_get_ibv_context", ret);
> ```

You have to `return;` on error immediately.
___
*[tests/multithreaded/ep/rpma_ep_next_conn_req.c, line 50 at r2](https://reviewable.io/reviews/pmem/rpma/1023#-M_4sv9U72XL3u4n1EeP:-M_4sv9U72XL3u4n1EeQ:bn1uj74) ([raw file](https://github.com/pmem/rpma/blob/338fa8259cf146832f26d69f4c26c2430777baf4/tests/multithreaded/ep/rpma_ep_next_conn_req.c#L50)):*
> ```C
> 
> 	if ((ret = rpma_peer_new(pr->dev, &pr->peer)))
> 		MTT_RPMA_ERR(tr, "rpma_peer_new", ret);
> ```

`return;`
___
*[tests/multithreaded/ep/rpma_ep_next_conn_req.c, line 55 at r2](https://reviewable.io/reviews/pmem/rpma/1023#-M_4t5Bn7iakOKzLt_w6:-M_4t5Bo2oZOUSuWHOlo:b9drn6v) ([raw file](https://github.com/pmem/rpma/blob/338fa8259cf146832f26d69f4c26c2430777baf4/tests/multithreaded/ep/rpma_ep_next_conn_req.c#L55)):*
> ```C
> 	MTT_PORT_SET(pr->port, 0);
> 	if ((ret = rpma_ep_listen(pr->peer, pr->addr, MTT_PORT_STR, &pr->ep)))
> 		MTT_RPMA_ERR(tr, "rpma_ep_listen", ret);
> ```

`rpma_peer_delete()` is missing.
___
*[tests/multithreaded/ep/rpma_ep_next_conn_req.c, line 55 at r2](https://reviewable.io/reviews/pmem/rpma/1023#-M_5J_enAvul_Pez2wvF:-M_5J_enAvul_Pez2wvG:b-u4my3c) ([raw file](https://github.com/pmem/rpma/blob/338fa8259cf146832f26d69f4c26c2430777baf4/tests/multithreaded/ep/rpma_ep_next_conn_req.c#L55)):*
> ```C
> 	MTT_PORT_SET(pr->port, 0);
> 	if ((ret = rpma_ep_listen(pr->peer, pr->addr, MTT_PORT_STR, &pr->ep)))
> 		MTT_RPMA_ERR(tr, "rpma_ep_listen", ret);
> ```

When the endpoint is ready we can unlock the `ep_ready_sem` and start waiting for connection requests.

```c
sem_post(pr->ep_ready_sem);
sem_wait(pr->conn_reqs_ready_sem);
```
___
*[tests/multithreaded/ep/rpma_ep_next_conn_req.c, line 65 at r2](https://reviewable.io/reviews/pmem/rpma/1023#-M_51rkIBoN1A-k2QooF:-M_51rkIBoN1A-k2QooG:b-sgumlc) ([raw file](https://github.com/pmem/rpma/blob/338fa8259cf146832f26d69f4c26c2430777baf4/tests/multithreaded/ep/rpma_ep_next_conn_req.c#L65)):*
> ```C
> 		struct mtt_result *tr)
> {
> 	struct prestate *pr = (struct prestate *)prestate;
> ```

`warning: unused variable ‘pr’`
___
*[tests/multithreaded/ep/rpma_ep_next_conn_req.c, line 88 at r2](https://reviewable.io/reviews/pmem/rpma/1023#-M_4tJgC63En0-bZNdqG:-M_4tJgC63En0-bZNdqH:b-fraaar) ([raw file](https://github.com/pmem/rpma/blob/338fa8259cf146832f26d69f4c26c2430777baf4/tests/multithreaded/ep/rpma_ep_next_conn_req.c#L88)):*
> ```C
> 	if (ret) {
> 		MTT_RPMA_ERR(result, "rpma_ep_next_conn_req", ret);
> 		return;
> ```

Not required.
___
*[tests/multithreaded/ep/rpma_ep_next_conn_req.c, line 133 at r2](https://reviewable.io/reviews/pmem/rpma/1023#-M_5JvlT-4Te4fgbOCFG:-M_5JvlT-4Te4fgbOCFH:b-a38fv3) ([raw file](https://github.com/pmem/rpma/blob/338fa8259cf146832f26d69f4c26c2430777baf4/tests/multithreaded/ep/rpma_ep_next_conn_req.c#L133)):*
> ```C
> 	struct rpma_peer *peer = NULL;
> 	struct rpma_conn_req *req = NULL;
> 	struct rpma_conn *conn = NULL;
> ```

You have to divide the process implemented here into few stages:
1. waiting for the endpoint semaphore
2. posting all connection requests
3. Unlocking the `conn_reqs_ready_sem` semaphore
4. Handling the rest of the connection process
    - getting an event
    - disconnecting
    - deleting

Because of this, you have to keep all the created connections between stages 2 and 4 which requires having a dynamic array of pointers.

```c
struct rpma_conn **conns;
conns = calloc(pr->threads_num, sizeof(struct rpma_conn *));
/* validation */
```
___
*[tests/multithreaded/ep/rpma_ep_next_conn_req.c, line 136 at r2](https://reviewable.io/reviews/pmem/rpma/1023#-M_5KjB024O9B9kwc7Hm:-M_5KjB024O9B9kwc7Hn:b-s3hmk9) ([raw file](https://github.com/pmem/rpma/blob/338fa8259cf146832f26d69f4c26c2430777baf4/tests/multithreaded/ep/rpma_ep_next_conn_req.c#L136)):*
> ```C
> 	int ret = 0;
> 
> 	usleep(CHILD_PROCESS_DELAY_US);
> ```

Not needed.
___
*[tests/multithreaded/ep/rpma_ep_next_conn_req.c, line 136 at r2](https://reviewable.io/reviews/pmem/rpma/1023#-M_5Kmyl2FzEOpBDAVzV:-M_5KmymBzcJr-4haHLL:b-fcn878) ([raw file](https://github.com/pmem/rpma/blob/338fa8259cf146832f26d69f4c26c2430777baf4/tests/multithreaded/ep/rpma_ep_next_conn_req.c#L136)):*
> ```C
> 	int ret = 0;
> 
> 	usleep(CHILD_PROCESS_DELAY_US);
> ```

`sem_wait(pr->ep_ready_sem);` + validation.
___
*[tests/multithreaded/ep/rpma_ep_next_conn_req.c, line 149 at r2](https://reviewable.io/reviews/pmem/rpma/1023#-M_51QdZ-fp8AakPCLOF:-M_51Qd_CEWFho8kYc_U:bpoj8cz) ([raw file](https://github.com/pmem/rpma/blob/338fa8259cf146832f26d69f4c26c2430777baf4/tests/multithreaded/ep/rpma_ep_next_conn_req.c#L149)):*
> ```C
> 	MTT_PORT_INIT;
> 	MTT_PORT_SET(pr->port, 0);
> 	for (int counts = 0; counts < pr->threads_num; counts++) {
> ```

`warning: comparison of integer expressions of different signedness: ‘int’ and ‘unsigned int’`
___
*[tests/multithreaded/ep/rpma_ep_next_conn_req.c, line 155 at r2](https://reviewable.io/reviews/pmem/rpma/1023#-M_5KxVH7dnZQ3cjojEB:-M_5KxVH7dnZQ3cjojEC:b-m7seoj) ([raw file](https://github.com/pmem/rpma/blob/338fa8259cf146832f26d69f4c26c2430777baf4/tests/multithreaded/ep/rpma_ep_next_conn_req.c#L155)):*
> ```C
> 			goto err_peer_delete;
> 
> 		if ((ret = rpma_conn_req_connect(&req, NULL, &conn))) {
> ```

`&conns[i]`
___
*[tests/multithreaded/ep/rpma_ep_next_conn_req.c, line 159 at r2](https://reviewable.io/reviews/pmem/rpma/1023#-M_5KrAEBXjLZXV1dhmA:-M_5KrAEBXjLZXV1dhmB:bqvfqca) ([raw file](https://github.com/pmem/rpma/blob/338fa8259cf146832f26d69f4c26c2430777baf4/tests/multithreaded/ep/rpma_ep_next_conn_req.c#L159)):*
> ```C
> 				(void) rpma_conn_req_delete(&req);
> 			goto err_peer_delete;
> 		}
> ```

This is the end of stage 2. Here you have to end the for-loop.
___
*[tests/multithreaded/ep/rpma_ep_next_conn_req.c, line 161 at r2](https://reviewable.io/reviews/pmem/rpma/1023#-M_5L4Og-vy376uvLX2Z:-M_5L4Og-vy376uvLX2_:b-s3hmk9) ([raw file](https://github.com/pmem/rpma/blob/338fa8259cf146832f26d69f4c26c2430777baf4/tests/multithreaded/ep/rpma_ep_next_conn_req.c#L161)):*
> ```C
> 		}
> 
> 		usleep(CHILD_PROCESS_DELAY_US);
> ```

Not needed.
___
*[tests/multithreaded/ep/rpma_ep_next_conn_req.c, line 161 at r2](https://reviewable.io/reviews/pmem/rpma/1023#-M_5L8994hC_ZwcmV4f6:-M_5L8994hC_ZwcmV4f7:b2wgc9a) ([raw file](https://github.com/pmem/rpma/blob/338fa8259cf146832f26d69f4c26c2430777baf4/tests/multithreaded/ep/rpma_ep_next_conn_req.c#L161)):*
> ```C
> 		}
> 
> 		usleep(CHILD_PROCESS_DELAY_US);
> ```

Stage 3. Unlocking the connection requests semaphore.

```c
ret = sem_post(pr->conn_reqs_ready_sem);
/* validation */
```
___
*[tests/multithreaded/ep/rpma_ep_next_conn_req.c, line 163 at r2](https://reviewable.io/reviews/pmem/rpma/1023#-M_5LOC64NDg45BEoEYF:-M_5LOC64NDg45BEoEYG:bdpwe5v) ([raw file](https://github.com/pmem/rpma/blob/338fa8259cf146832f26d69f4c26c2430777baf4/tests/multithreaded/ep/rpma_ep_next_conn_req.c#L163)):*
> ```C
> 		usleep(CHILD_PROCESS_DELAY_US);
> 
> 		/* disconnect the connection */
> ```

Start of stage 4. Here we need another for-loop.

You are missing here collecting an event:

```c
	if ((ret = rpma_conn_next_event(conns[i], &event)))
		goto err_conn_delete;
```
___
*[tests/multithreaded/ep/rpma_ep_next_conn_req.c, line 178 at r2](https://reviewable.io/reviews/pmem/rpma/1023#-M_5Lw2sAq1ifDYn6WI4:-M_5Lw2sAq1ifDYn6WI5:bf992xq) ([raw file](https://github.com/pmem/rpma/blob/338fa8259cf146832f26d69f4c26c2430777baf4/tests/multithreaded/ep/rpma_ep_next_conn_req.c#L178)):*
> ```C
> 	return 0;
> 
> err_conn_delete:
> ```

Here we need to free the `conns` dynamic array.
___
*[tests/multithreaded/ep/rpma_ep_next_conn_req.c, line 178 at r2](https://reviewable.io/reviews/pmem/rpma/1023#-M_5M-mTB37kC9_X2757:-M_5M-mTB37kC9_X2758:b7nbxg3) ([raw file](https://github.com/pmem/rpma/blob/338fa8259cf146832f26d69f4c26c2430777baf4/tests/multithreaded/ep/rpma_ep_next_conn_req.c#L178)):*
> ```C
> 	return 0;
> 
> err_conn_delete:
> ```

Because we have multiple connections in the flight we need more sophisticated error handling e.g. cleaning up the existing connections where processing one of them has failed.
___
*[tests/multithreaded/ep/rpma_ep_next_conn_req.c, line 193 at r2](https://reviewable.io/reviews/pmem/rpma/1023#-M_5Meu5C9y4vxNLaU6t:-M_5Meu5C9y4vxNLaU6u:b-8c7opd) ([raw file](https://github.com/pmem/rpma/blob/338fa8259cf146832f26d69f4c26c2430777baf4/tests/multithreaded/ep/rpma_ep_next_conn_req.c#L193)):*
> ```C
> 	if (mtt_parse_args(argc, argv, &args))
> 		return -1;
> ```

Rough. I plan to think more about simplifying interprocess communication for the sake of the MT testing. But so far, it is the best we can get.

```c
	sem_t *ep_ready_sem = sem_open("/mt_rpma_ep_next_conn_req_ep_ready_sem", O_CREAT, 0600, 0);
	if (ep_ready_sem == NULL) {
		return errno;
	}
	sem_t *conn_reqs_ready_sem = sem_open("/mt_rpma_ep_next_conn_conn_reqs_ready_sem", O_CREAT, 0600, 0);
	if (conn_reqs_ready_sem == NULL) {
		return errno;
	}
```
___
*[tests/multithreaded/ep/rpma_ep_next_conn_req.c, line 194 at r2](https://reviewable.io/reviews/pmem/rpma/1023#-M_5MlcC4oSpAOGlvfYS:-M_5MlcC4oSpAOGlvfYT:b-iuykum) ([raw file](https://github.com/pmem/rpma/blob/338fa8259cf146832f26d69f4c26c2430777baf4/tests/multithreaded/ep/rpma_ep_next_conn_req.c#L194)):*
> ```C
> 		return -1;
> 
> 	struct prestate prestate = {args.addr, args.port, NULL, NULL, NULL};
> ```

`ep_ready_sem, conn_reqs_ready_sem`
___
*[tests/multithreaded/ep/rpma_ep_next_conn_req.c, line 196 at r2](https://reviewable.io/reviews/pmem/rpma/1023#-M_5Mmy51ZcBliGlaP65:-M_5Mmy51ZcBliGlaP66:b-iuykum) ([raw file](https://github.com/pmem/rpma/blob/338fa8259cf146832f26d69f4c26c2430777baf4/tests/multithreaded/ep/rpma_ep_next_conn_req.c#L196)):*
> ```C
> 	struct prestate prestate = {args.addr, args.port, NULL, NULL, NULL};
> 	struct child_prestate cld_prestate = {args.addr, args.port,
> 				args.threads_num};
> ```

`ep_ready_sem, conn_reqs_ready_sem`

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1023)* status: all files reviewed, 22 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/ep/rpma_ep_next_conn_req.c, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/1023#-M_5285wCxcePPHVJxQ1:-M_AxdCt55zpCu8xqpN0:b-5a0qg6) ([raw file](https://github.com/pmem/rpma/blob/338fa8259cf146832f26d69f4c26c2430777baf4/tests/multithreaded/ep/rpma_ep_next_conn_req.c#L15)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is not a robust solution. We have to develop a synchronization technique. I suggest using semaphores.
It requires a few more includes:

```c
#include <fcntl.h>
#include <sys/stat.h>
#include <semaphore.h>
```

Sadly, at this point of development, the only solution I can think of requires using two semaphores. So, both prestates require pointers to two semaphores:

```c
sem_t *ep_ready_sem;
sem_t *conn_reqs_ready_sem;
```

Please see other comments for more details.
</blockquote></details>

I'm thinking about how to integrate semaphores into the framework.
Please take a look at this draft: https://github.com/pmem/rpma/pull/1050
All comments are welcome.

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1023)* status: all files reviewed, 23 unresolved discussions (waiting on @ewanglong)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1023#-M_eifkh0qStGk6C_aGI:-M_eifkh0qStGk6C_aGJ:bksmgig) (no related file):*
I have discussed the idea of introducing interprocess synchronization with @grom72 and we have understood that the proposition I have made is halfbaked. We think we can do better. But it requires some time. We think that the subject will be picked up in two weeks. In the meantime, I think it will be best for you to do other multithreaded tests which are still to do or rewrite. Here you can find a list: https://github.com/pmem/rpma/issues/1007

Sorry for delaying you for the second time. Starting up writing this test is a long shot. ;-)

For now, I will redraft this PR.

---

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1023)* status: 8 of 11 files reviewed, 23 unresolved discussions (waiting on @ewanglong, @grom72, and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1023#-M_eifkh0qStGk6C_aGI:-MbHOyFN-yva29PP6p7z:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I have discussed the idea of introducing interprocess synchronization with @grom72 and we have understood that the proposition I have made is halfbaked. We think we can do better. But it requires some time. We think that the subject will be picked up in two weeks. In the meantime, I think it will be best for you to do other multithreaded tests which are still to do or rewrite. Here you can find a list: https://github.com/pmem/rpma/issues/1007

Sorry for delaying you for the second time. Starting up writing this test is a long shot. ;-)

For now, I will redraft this PR.
</blockquote></details>

Done.

---
___
*[tests/multithreaded/ep/rpma_ep_next_conn_req.c, line 10 at r2](https://reviewable.io/reviews/pmem/rpma/1023#-M_5226R-D8ehE92nopk:-MbHOzlNCFdzEUWnxlep:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/338fa8259cf146832f26d69f4c26c2430777baf4/tests/multithreaded/ep/rpma_ep_next_conn_req.c#L10)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

These two are not needed.
</blockquote></details>

Done.
___
*[tests/multithreaded/ep/rpma_ep_next_conn_req.c, line 47 at r2](https://reviewable.io/reviews/pmem/rpma/1023#-M_4sqC28Sut0sRPUcF3:-MbHNoXI8R-Dym2q9aEo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/338fa8259cf146832f26d69f4c26c2430777baf4/tests/multithreaded/ep/rpma_ep_next_conn_req.c#L47)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You have to `return;` on error immediately.
</blockquote></details>

Done.
___
*[tests/multithreaded/ep/rpma_ep_next_conn_req.c, line 50 at r2](https://reviewable.io/reviews/pmem/rpma/1023#-M_4sv9U72XL3u4n1EeP:-MbHNqZo8LIXUyJFodmy:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/338fa8259cf146832f26d69f4c26c2430777baf4/tests/multithreaded/ep/rpma_ep_next_conn_req.c#L50)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`return;`
</blockquote></details>

Done.
___
*[tests/multithreaded/ep/rpma_ep_next_conn_req.c, line 55 at r2](https://reviewable.io/reviews/pmem/rpma/1023#-M_4t5Bn7iakOKzLt_w6:-MbHOBL55eQXalZ4MD3Z:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/338fa8259cf146832f26d69f4c26c2430777baf4/tests/multithreaded/ep/rpma_ep_next_conn_req.c#L55)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`rpma_peer_delete()` is missing.
</blockquote></details>

Done.
___
*[tests/multithreaded/ep/rpma_ep_next_conn_req.c, line 65 at r2](https://reviewable.io/reviews/pmem/rpma/1023#-M_51rkIBoN1A-k2QooF:-MbHPDM32RdzmTh2MnmC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/338fa8259cf146832f26d69f4c26c2430777baf4/tests/multithreaded/ep/rpma_ep_next_conn_req.c#L65)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`warning: unused variable ‘pr’`
</blockquote></details>

Done.
___
*[tests/multithreaded/ep/rpma_ep_next_conn_req.c, line 88 at r2](https://reviewable.io/reviews/pmem/rpma/1023#-M_4tJgC63En0-bZNdqG:-MbHPOy6CjTIKH3o8qOp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/338fa8259cf146832f26d69f4c26c2430777baf4/tests/multithreaded/ep/rpma_ep_next_conn_req.c#L88)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not required.
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1023)* status: 8 of 11 files reviewed, 23 unresolved discussions (waiting on @ewanglong, @grom72, and @janekmi)

**Comment by janekmi** [comment]
We need to do some prework before we will be able to address this issue sufficiently. Closing for now.

Ref: https://github.com/pmem/rpma/pull/1050

**Pull request closed without merging**
