### PR TITLE
rpma: analysis of thread safety: rpma_log_

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1772)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1772)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`THREAD_SAFETY.md` line 45 at r1](https://reviewable.io/reviews/pmem/rpma/1772#-N3-LhRv2mLSJRkyRPgj:-N3-LhRv2mLSJRkyRPgk:b-y2kwcg) ([raw file](https://github.com/pmem/rpma/blob/9a7a788515123fc34aa5ed131c355d8b8f3b5ee2/THREAD_SAFETY.md#L45)):*
> ```Markdown
> - rpma_mr_advise
> - rpma_log_get_threshold
> - rpma_log_set_function
> ```

Is it possible that we set up a log function in one thread and another will be corrupted because of calling the "partially modified pointer" value?



_Code quote:_
```Markdown
rpma_log_set_function
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1772)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`THREAD_SAFETY.md` line 45 at r1](https://reviewable.io/reviews/pmem/rpma/1772#-N3-LhRv2mLSJRkyRPgj:-N3-NiL97QYtV5mE6J3u:b-uqk7km) ([raw file](https://github.com/pmem/rpma/blob/9a7a788515123fc34aa5ed131c355d8b8f3b5ee2/THREAD_SAFETY.md#L45)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Is it possible that we set up a log function in one thread and another will be corrupted because of calling the "partially modified pointer" value?
</blockquote></details>

No, because it is modified using `__sync_bool_compare_and_swap` - please check in the code.



_Code quote:_
```Markdown
rpma_log_set_function
```

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1772#-:-N3-UpyNBwo1XtmbD-lR:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1772)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1772)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
