### PR TITLE
test: add rpma_conn_cfg_new multithreaded test

### PR DESCRIPTION
**Pull request by ewanglong**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1063)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1063)* status: all files reviewed, 9 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/conn/rpma_conn_cfg_new.c, line 18 at r1](https://reviewable.io/reviews/pmem/rpma/1063#-MaF7Vpc3H_UDQpq2ZZE:-MaF7Vpc3H_UDQpq2ZZF:bgsceeg) ([raw file](https://github.com/pmem/rpma/blob/14bd40b6d838eaefd85fabd1379a55619e196bd3/tests/multithreaded/conn/rpma_conn_cfg_new.c#L18)):*
> ```C
> 	uint32_t sq_size;	/* SQ size */
> 	uint32_t rq_size;	/* RQ size */
> };
> ```

It violates the librpma API. Please remove it.
___
*[tests/multithreaded/conn/rpma_conn_cfg_new.c, line 21 at r1](https://reviewable.io/reviews/pmem/rpma/1063#-MaF8uYY3tl7gaj-yQc7:-MaF8uYY3tl7gaj-yQc8:b-o4vnj7) ([raw file](https://github.com/pmem/rpma/blob/14bd40b6d838eaefd85fabd1379a55619e196bd3/tests/multithreaded/conn/rpma_conn_cfg_new.c#L21)):*
> ```C
> 
> struct prestate {
> 	struct rpma_conn_cfg *cfg_ptr_exp;
> ```

cfg_exp
___
*[tests/multithreaded/conn/rpma_conn_cfg_new.c, line 25 at r1](https://reviewable.io/reviews/pmem/rpma/1063#-MaF8vxX2msYsXxbaqrz:-MaF8vxX2msYsXxbaqs-:b2ni0cf) ([raw file](https://github.com/pmem/rpma/blob/14bd40b6d838eaefd85fabd1379a55619e196bd3/tests/multithreaded/conn/rpma_conn_cfg_new.c#L25)):*
> ```C
> 
> struct state {
> 	struct rpma_conn_cfg *cfg_ptr;
> ```

cfg
___
*[tests/multithreaded/conn/rpma_conn_cfg_new.c, line 29 at r1](https://reviewable.io/reviews/pmem/rpma/1063#-MaF7p3R7dWu7DaG85x8:-MaF7p3R7dWu7DaG85x9:b-l18wvr) ([raw file](https://github.com/pmem/rpma/blob/14bd40b6d838eaefd85fabd1379a55619e196bd3/tests/multithreaded/conn/rpma_conn_cfg_new.c#L29)):*
> ```C
> 
> /*
>  * prestate_init -- creates a new connection configuration object
> ```

`create`
___
*[tests/multithreaded/conn/rpma_conn_cfg_new.c, line 58 at r1](https://reviewable.io/reviews/pmem/rpma/1063#-MaF7sgr3m1-jezEK8nA:-MaF7sgs88QvSHtjWqLx:b-s3bbgf) ([raw file](https://github.com/pmem/rpma/blob/14bd40b6d838eaefd85fabd1379a55619e196bd3/tests/multithreaded/conn/rpma_conn_cfg_new.c#L58)):*
> ```C
> 
> /*
>  * thread -- creates a new connection configuration object
> ```

create
___
*[tests/multithreaded/conn/rpma_conn_cfg_new.c, line 59 at r1](https://reviewable.io/reviews/pmem/rpma/1063#-MaF7ubV7ODq1vKk5DRP:-MaF7ubV7ODq1vKk5DRQ:ba298e6) ([raw file](https://github.com/pmem/rpma/blob/14bd40b6d838eaefd85fabd1379a55619e196bd3/tests/multithreaded/conn/rpma_conn_cfg_new.c#L59)):*
> ```C
> /*
>  * thread -- creates a new connection configuration object
>  * and check if its default sizes are expected
> ```

sizes -> values
___
*[tests/multithreaded/conn/rpma_conn_cfg_new.c, line 73 at r1](https://reviewable.io/reviews/pmem/rpma/1063#-MaF7yy07XDzsi0sgFFP:-MaF7yy07XDzsi0sgFFQ:b1qhmea) ([raw file](https://github.com/pmem/rpma/blob/14bd40b6d838eaefd85fabd1379a55619e196bd3/tests/multithreaded/conn/rpma_conn_cfg_new.c#L73)):*
> ```C
> 	}
> 
> 	if (st->cfg_ptr->timeout_ms != pr->cfg_ptr_exp->timeout_ms ||
> ```

`rpma_conn_cfg_get_cq_size(cfg) != rpma_conn_cfg_get_cq_size(pr->cfg_exp)`

Please adjust other comparisons accordingly.
___
*[tests/multithreaded/conn/rpma_conn_cfg_new.c, line 77 at r1](https://reviewable.io/reviews/pmem/rpma/1063#-MaF8VLs8SCEB76oKi3T:-MaF8VLs8SCEB76oKi3U:bfvnf5m) ([raw file](https://github.com/pmem/rpma/blob/14bd40b6d838eaefd85fabd1379a55619e196bd3/tests/multithreaded/conn/rpma_conn_cfg_new.c#L77)):*
> ```C
> 		st->cfg_ptr->sq_size != pr->cfg_ptr_exp->sq_size ||
> 		st->cfg_ptr->rq_size != pr->cfg_ptr_exp->rq_size)
> 		MTT_ERR(tr, "rpma_conn_cfg_new create an unexpected value",
> ```

I think we can simplify this error message e.g. `"cfg != pr->cfg_ptr"`.
___
*[tests/multithreaded/conn/rpma_conn_cfg_new.c, line 82 at r1](https://reviewable.io/reviews/pmem/rpma/1063#-MaF8npo3IC7Wastu_nD:-MaF8npo3IC7Wastu_nE:b16qkkl) ([raw file](https://github.com/pmem/rpma/blob/14bd40b6d838eaefd85fabd1379a55619e196bd3/tests/multithreaded/conn/rpma_conn_cfg_new.c#L82)):*
> ```C
> 
> /*
>  * fini -- free the state
> ```

... the connection configuration object

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1063)* status: 1 of 2 files reviewed, 9 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/multithreaded/conn/rpma_conn_cfg_new.c, line 18 at r1](https://reviewable.io/reviews/pmem/rpma/1063#-MaF7Vpc3H_UDQpq2ZZE:-MaRVACK-1n6gIzbkkl8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/14bd40b6d838eaefd85fabd1379a55619e196bd3/tests/multithreaded/conn/rpma_conn_cfg_new.c#L18)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It violates the librpma API. Please remove it.
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_cfg_new.c, line 21 at r1](https://reviewable.io/reviews/pmem/rpma/1063#-MaF8uYY3tl7gaj-yQc7:-MaRVAx_3rysJFgs_Fc8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/14bd40b6d838eaefd85fabd1379a55619e196bd3/tests/multithreaded/conn/rpma_conn_cfg_new.c#L21)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

cfg_exp
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_cfg_new.c, line 25 at r1](https://reviewable.io/reviews/pmem/rpma/1063#-MaF8vxX2msYsXxbaqrz:-MaRVBbD7yAs7i9O6xra:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/14bd40b6d838eaefd85fabd1379a55619e196bd3/tests/multithreaded/conn/rpma_conn_cfg_new.c#L25)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

cfg
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_cfg_new.c, line 29 at r1](https://reviewable.io/reviews/pmem/rpma/1063#-MaF7p3R7dWu7DaG85x8:-MaRVCHd0WPoqWQtYXFH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/14bd40b6d838eaefd85fabd1379a55619e196bd3/tests/multithreaded/conn/rpma_conn_cfg_new.c#L29)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`create`
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_cfg_new.c, line 58 at r1](https://reviewable.io/reviews/pmem/rpma/1063#-MaF7sgr3m1-jezEK8nA:-MaRVCpi4xCbEikhr8ZN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/14bd40b6d838eaefd85fabd1379a55619e196bd3/tests/multithreaded/conn/rpma_conn_cfg_new.c#L58)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

create
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_cfg_new.c, line 59 at r1](https://reviewable.io/reviews/pmem/rpma/1063#-MaF7ubV7ODq1vKk5DRP:-MaRVNRS6FqeWrYkWjZA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/14bd40b6d838eaefd85fabd1379a55619e196bd3/tests/multithreaded/conn/rpma_conn_cfg_new.c#L59)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

sizes -> values
</blockquote></details>

Done.

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1063)* status: 1 of 2 files reviewed, 9 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/conn/rpma_conn_cfg_new.c, line 73 at r1](https://reviewable.io/reviews/pmem/rpma/1063#-MaF7yy07XDzsi0sgFFP:-MaRVQUw9-UdNRETPi9G:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/14bd40b6d838eaefd85fabd1379a55619e196bd3/tests/multithreaded/conn/rpma_conn_cfg_new.c#L73)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`rpma_conn_cfg_get_cq_size(cfg) != rpma_conn_cfg_get_cq_size(pr->cfg_exp)`

Please adjust other comparisons accordingly.
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_cfg_new.c, line 77 at r1](https://reviewable.io/reviews/pmem/rpma/1063#-MaF8VLs8SCEB76oKi3T:-MaRVRG_9uDNHS1bZfre:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/14bd40b6d838eaefd85fabd1379a55619e196bd3/tests/multithreaded/conn/rpma_conn_cfg_new.c#L77)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we can simplify this error message e.g. `"cfg != pr->cfg_ptr"`.
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_cfg_new.c, line 82 at r1](https://reviewable.io/reviews/pmem/rpma/1063#-MaF8npo3IC7Wastu_nD:-MaRVS-x03sfpd3mjfmH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/14bd40b6d838eaefd85fabd1379a55619e196bd3/tests/multithreaded/conn/rpma_conn_cfg_new.c#L82)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

... the connection configuration object
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1063)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/conn/rpma_conn_cfg_new.c, line 59 at r1](https://reviewable.io/reviews/pmem/rpma/1063#-MaF7ubV7ODq1vKk5DRP:-Mam9_2yEKaKitYX5Xjx:b-jk3iyn) ([raw file](https://github.com/pmem/rpma/blob/14bd40b6d838eaefd85fabd1379a55619e196bd3/tests/multithreaded/conn/rpma_conn_cfg_new.c#L59)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`create a new connection configuration object and check its default values`
___
*[tests/multithreaded/conn/rpma_conn_cfg_new.c, line 112 at r2](https://reviewable.io/reviews/pmem/rpma/1063#-MamBTmICyirnYtvOhQ5:-MamBTmICyirnYtvOhQ6:bfc24ai) ([raw file](https://github.com/pmem/rpma/blob/85c534587ecf7578e9d65e86c213bd086bdf8046/tests/multithreaded/conn/rpma_conn_cfg_new.c#L112)):*
> ```C
> 	if (timeout_ms != timeout_ms_exp ||	cq_size != cq_size_exp ||
> 		sq_size != sq_size_exp || rq_size != rq_size_exp)
> 		MTT_ERR(tr, "cfg != pr->cfg_ptr", EINVAL);
> ```

A lot of duplicate code. I think it can be a little bit simplified e.g.

```c
struct conn_cfg_values {
	int timeout_ms;
	uint32_t cq_size;
	uint32_t sq_size;
	uint32_t rq_size;
}

static int
conn_cfg_get_all(struct rpma_conn_cfg *cfg, struct conn_cfg_values *vals, struct mtt_result *tr) {
    /* call all getters and write output to the respective fields of the vals structure */
    /* return 1 on error or 0 on success */
}

static void
thread(/* ... */) {
    /* ... */

   if (conn_cfg_get_all(st->cfg, &cfg_vals)
       return;

   if (conn_cfg_get_all(st->cfg_exp, &cfg_exp_vals)
       return;

   if (memcmp(&cfg_vals, &cfg_exp_vals, sizeof(struct conn_cfg_values) != 0)
       MTT_ERR(tr, "cfg_vals != cfg_exp_vals", EINVAL);
}
```

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1063)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/conn/rpma_conn_cfg_new.c, line 59 at r1](https://reviewable.io/reviews/pmem/rpma/1063#-MaF7ubV7ODq1vKk5DRP:-Mb4NBDK3BlfK__nvulx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/14bd40b6d838eaefd85fabd1379a55619e196bd3/tests/multithreaded/conn/rpma_conn_cfg_new.c#L59)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`create a new connection configuration object and check its default values`
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_cfg_new.c, line 112 at r2](https://reviewable.io/reviews/pmem/rpma/1063#-MamBTmICyirnYtvOhQ5:-Mb4N9R62nuPPAbFZZna:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/85c534587ecf7578e9d65e86c213bd086bdf8046/tests/multithreaded/conn/rpma_conn_cfg_new.c#L112)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

A lot of duplicate code. I think it can be a little bit simplified e.g.

```c
struct conn_cfg_values {
	int timeout_ms;
	uint32_t cq_size;
	uint32_t sq_size;
	uint32_t rq_size;
}

static int
conn_cfg_get_all(struct rpma_conn_cfg *cfg, struct conn_cfg_values *vals, struct mtt_result *tr) {
    /* call all getters and write output to the respective fields of the vals structure */
    /* return 1 on error or 0 on success */
}

static void
thread(/* ... */) {
    /* ... */

   if (conn_cfg_get_all(st->cfg, &cfg_vals)
       return;

   if (conn_cfg_get_all(st->cfg_exp, &cfg_exp_vals)
       return;

   if (memcmp(&cfg_vals, &cfg_exp_vals, sizeof(struct conn_cfg_values) != 0)
       MTT_ERR(tr, "cfg_vals != cfg_exp_vals", EINVAL);
}
```
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1063)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/multithreaded/conn/rpma_conn_cfg_new.c, line 30 at r3](https://reviewable.io/reviews/pmem/rpma/1063#-Mb5RDEEEHz2LV2aqq0N:-Mb5RDEEEHz2LV2aqq0O:b-fuhp06) ([raw file](https://github.com/pmem/rpma/blob/ac84b1a8a48bf6c87e46e4f0167728b7fe8b72a3/tests/multithreaded/conn/rpma_conn_cfg_new.c#L30)):*
> ```C
> static int
> conn_cfg_get_all(struct rpma_conn_cfg *cfg, struct conn_cfg_values *vals,
> 				struct mtt_result *tr)
> ```

Indentation.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1063)* status: all files reviewed, 3 unresolved discussions (waiting on @ewanglong and @janekmi)

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1063)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[tests/multithreaded/conn/rpma_conn_cfg_new.c, line 30 at r3](https://reviewable.io/reviews/pmem/rpma/1063#-Mb5RDEEEHz2LV2aqq0N:-MbBMLXU1PEejyambxKx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ac84b1a8a48bf6c87e46e4f0167728b7fe8b72a3/tests/multithreaded/conn/rpma_conn_cfg_new.c#L30)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Indentation.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1063)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1063#-:-MbBN2dI6BJUFd97zNY1:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1063)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @osalyk)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1063#-:-MbBW6Oc6ZRYRBteYdw-:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1063)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1063#-:-MbB_3WG4IW2ZIiAniTb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Pull request merged**
