### PR TITLE
tools: perf: separate Figure and Benchmark oneseries

### PR DESCRIPTION
**Pull request by janekmi**
Requires:

- [x] #1361
- [x] #1364 
- [x] #1366 
- [x] #1367

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1368)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1368)* status: 0 of 15 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1368)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1368#-MpkwZtg98CDEMum64yP:-MpkwZtg98CDEMum64yQ:bxpmse7) (no related file):*
CI builds fail:
https://github.com/ldorau/rpma/actions/runs/1520902820

---

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1368)* status: 0 of 15 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 15 files at r1, 7 of 10 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1368#-:-Mpl5PHD6-n5tjXNWQHh:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 15 files at r1, 7 of 10 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1368)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/figure/base.py, line 48 at r3](https://reviewable.io/reviews/pmem/rpma/1368#-Mpl6mS374f-QuYCqXte:-Mpl6mS374f-QuYCqXtf:b-77qf8d) ([raw file](https://github.com/pmem/rpma/blob/5ea56bdb6b2de88b568e3067c8492ae72ddab786/tools/perf/lib/figure/base.py#L48)):*
> ```
> """XXX"""
> ```

When will all XXXs be replaced?

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1368)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1368)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/lib/figure/base.py, line 48 at r3](https://reviewable.io/reviews/pmem/rpma/1368#-Mpl6mS374f-QuYCqXte:-MplAVal-aS3A0PnCLjc:b-8sgh52) ([raw file](https://github.com/pmem/rpma/blob/5ea56bdb6b2de88b568e3067c8492ae72ddab786/tools/perf/lib/figure/base.py#L48)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> """XXX"""
> ```

When will all XXXs be replaced?
</blockquote></details>

#1371

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1368)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1368#-:-MplAcQJ7_uqyMsAtSgJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1368)* status: all files reviewed, 1 unresolved discussion

___
*[-- commits, line 6 at r3](https://reviewable.io/reviews/pmem/rpma/1368#-MplAmG7Ex8lgD7LsKLR):*
> ```
>   lib.figure.base.Figure instances contain the original set of series.
>   In order to execute, each of the series initiates
>   lib.benchmark.base.Benchmark instances.
> ```
Do we have this information stored somewhere else or at least we can add this information to documentation?

**Pull request merged**
