### PR TITLE
common: add to CI Debug and Release builds with clang compiler

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/308)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 32 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/308)* status: 1 of 32 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[utils/docker/run-build.sh, line 234 at r1](https://reviewable.io/reviews/pmem/rpma/308#-MFq0GEA5KxBb9eiZB5T:-MFq0GEA5KxBb9eiZB5U:btngo7l) ([raw file](https://github.com/pmem/rpma/blob/0bab23b7131edad615586e0a00f4e3d9bc869306/utils/docker/run-build.sh#L234)):*
> ```Shell
> echo
> echo "##################################################################"
> echo "### Verify build and install (in dir: ${PREFIX}) (RELEASE, clang)"
> ```

The list of steps and permutations become pretty extensive here... can we make the compiler a job parameter? So we will end up e.g.:

- Ubuntu + gcc (both Release and Debug; we will see if will make sense to also make it a job parameter)
- Fedora + clang (both Release and Debug)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/308)* status: 1 of 32 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[utils/docker/run-build.sh, line 234 at r1](https://reviewable.io/reviews/pmem/rpma/308#-MFq0GEA5KxBb9eiZB5T:-MG3Xq1ED5aQxVbA4Rug:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0bab23b7131edad615586e0a00f4e3d9bc869306/utils/docker/run-build.sh#L234)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The list of steps and permutations become pretty extensive here... can we make the compiler a job parameter? So we will end up e.g.:

- Ubuntu + gcc (both Release and Debug; we will see if will make sense to also make it a job parameter)
- Fedora + clang (both Release and Debug)
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 32 files at r1, 4 of 31 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/308#-:-MG3tlAw84hvsBIl442B:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by ldorau** [comment]
@grom72 please review

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/308#-:-MGCWHz27KY55-Bdi-GH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 32 files at r1, 2 of 31 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/308)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 31 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/308#-:-MGIJDQc8jHzCNLTZZLy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/308#-:-MGILjIHEhjhSdGefSqZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by ldorau** [comment]
Rebased on current master

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/308)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — APPROVED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/308)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[.travis.yml, line 18 at r4](https://reviewable.io/reviews/pmem/rpma/308#-MGNKt6NAZi1Q21kzrpd:-MGNKt6NAZi1Q21kzrpe:b5jy7p1) ([raw file](https://github.com/pmem/rpma/blob/88948c371e58184ba0672e6db2558a89ee0c4a70/.travis.yml#L18)):*
> ```YAML
>     - OS=fedora OS_VER=31    TYPE=normal CC=clang
>     - OS=ubuntu OS_VER=19.10 TYPE=normal CC=gcc COVERAGE=1
>     - OS=ubuntu OS_VER=19.10 TYPE=coverity CC=gcc
> ```

You do not want to keep symmetry here?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/308)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @janekmi)

___
*[.travis.yml, line 18 at r4](https://reviewable.io/reviews/pmem/rpma/308#-MGNKt6NAZi1Q21kzrpd:-MGNMCbD7OsrDtxDTbaS:bqmjwcz) ([raw file](https://github.com/pmem/rpma/blob/88948c371e58184ba0672e6db2558a89ee0c4a70/.travis.yml#L18)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You do not want to keep symmetry here?
</blockquote></details>

Added.

**Review by janekmi — APPROVED** [review]
:lgtm_strong: 

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/308#-:-MGNNbOKEAEWsc0oZaPq:b-uwkowd)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
