### PR TITLE
test: reorganization of the 'utils' unit test

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/274)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/274#-:-MF5Ic3M7MQ112P5GRKe:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/274#-:-MF63Z0h6d_hZBPmySiK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
Rebased

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/274#-:-MF7ZVu27bZNqRtQ9hTb:b9x2p3v)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @janekmi and @osalyk)

**Review by janekmi — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/274)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
