### PR TITLE
common: organize Dockerfile

### PR DESCRIPTION
**Pull request by Patryk717**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1927)

### CODE REVIEW

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 18 of 18 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1927#-:-N7QHna87ZaT2dxnjewr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)

**Review by Patryk717 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1927)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[`utils/docker/images/Dockerfile.fedora-33` line 53 at r1](https://reviewable.io/reviews/pmem/rpma/1927#-N7Qj-_RC4v0QotpJYTh:-N7UOz9XD7TxE4qeASAC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5cea5ca47cd8a1cecead395885e732a8cdd4beef/utils/docker/images/Dockerfile.fedora-33#L53)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

TOOLS_PYTHON_DEPS
</blockquote></details>

Done.

**Review by osalyk — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1927)* status: 17 of 18 files reviewed, 3 unresolved discussions (waiting on @grom72, @ldorau, and @Patryk717)

___
*[`utils/docker/images/Dockerfile.fedora-rawhide` line 47 at r2](https://reviewable.io/reviews/pmem/rpma/1927#-N7UaJUNBGqPc76kHc_s:-N7UaJUNBGqPc76kHc_t:undefined) ([raw file](https://github.com/pmem/rpma/blob/7f712e141dc3ff9a4be6e6c10fd8d1701ef67eb3/utils/docker/images/Dockerfile.fedora-rawhide#L47)):*
> ```
> 
> # performance tools deps
> ENV TOOLS_DEPS  "\
> ```





_Suggestion:_
```
ENV TOOLS_DEPS "\
```
___
*[`utils/docker/images/Dockerfile.rockylinux-8.4` line 64 at r2](https://reviewable.io/reviews/pmem/rpma/1927#-N7Uab2G4OpHZCvwUz9C:-N7Uab2G4OpHZCvwUz9D:b-l6mwxj) ([raw file](https://github.com/pmem/rpma/blob/7f712e141dc3ff9a4be6e6c10fd8d1701ef67eb3/utils/docker/images/Dockerfile.rockylinux-8.4#L64)):*
> ```Roff
> 	$BASE_DEPS \
> 	$RPMA_DEPS \
> 	$EXAMPLES_DEPS \
> ```

remove

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1927)* status: all files reviewed, 2 unresolved discussions (waiting on @Patryk717)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1927#-:-N7VJXz8ENt9KLS4vZ8B:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @Patryk717)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 15 of 18 files at r1, 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1927#-:-N7VSZar1IRYtEsUw5R6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1927)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)

**Pull request merged**
