### PR TITLE
test: add MT test for rpma_conn_req_connect()

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #1928

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1931)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1931)* status: 1 of 5 files reviewed, all discussions resolved (waiting on @grom72)

**Review by haichangsi — COMMENTED** [review]
Remember about the changelog ;)

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1931#-:-N7VMkDs9l-u2Va_OvBb:b7dmm16)* status: 1 of 7 files reviewed, all discussions resolved (waiting on @grom72)

**Review by osalyk — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 2 of 4 files at r2, 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1931)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
@haichangsi Done

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1931#-:-N7VZQQAAgE-0Qa1vdlV:b-d33hx0)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @grom72 and @osalyk)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1931#-:-N7VkJ2h1WvCY_lCg_nB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1931#-:-N7W-mUx2B9yPKALmHTW:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
