### PR TITLE
test: suppression format definition

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1850)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1850)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1850)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1850)* status: all files reviewed, 4 unresolved discussions (waiting on @osalyk)

___
*[`tests/drd.supp` line 387 at r1](https://reviewable.io/reviews/pmem/rpma/1850#-N54GvCH05crJ3t2mfdu:-N54GvCH05crJ3t2mfdv:b-5y9u7y) ([raw file](https://github.com/pmem/rpma/blob/031b3ec6a33669765fe621f98532549602f432c3/tests/drd.supp#L387)):*
> ```
> }
> 
> # Suppression format
> ```

```
#
# All suppressions should follow the following format:
#
```

And this should be located at the top of each file.



_Code quote:_
```
# Suppression format
#
```
___
*[`tests/drd.supp` line 389 at r1](https://reviewable.io/reviews/pmem/rpma/1850#-N54JWEi9VkeFs6omDhJ:-N54JWEi9VkeFs6omDhK:bm69x77) ([raw file](https://github.com/pmem/rpma/blob/031b3ec6a33669765fe621f98532549602f432c3/tests/drd.supp#L389)):*
> ```
> # Suppression format
> #
> # OS: OS version
> ```

```
# OS: a version of OS
# OFED: a version of OFED if used
# libibverbs: a version of libibverbs
# librdmacm: a version of librdmacm
```



_Code quote:_
```
# OS: OS version
# OFED: OFED version if used
# libibverbs: libibverbs version
# librdmacm: librdmacm version
```
___
*[`tests/drd.supp` line 393 at r1](https://reviewable.io/reviews/pmem/rpma/1850#-N54GdPv2-SqAYO7geJH:-N54GdPv2-SqAYO7geJI:b-whcq21) ([raw file](https://github.com/pmem/rpma/blob/031b3ec6a33669765fe621f98532549602f432c3/tests/drd.supp#L393)):*
> ```
> # libibverbs: libibverbs version
> # librdmacm: librdmacm version
> #
> ```

`rdma-core: a version of the 'rdma-core' package if installed`
___
*[`tests/helgrind.supp` line 412 at r1](https://reviewable.io/reviews/pmem/rpma/1850#-N54KFo_9bWUBHbHD1hF:-N54KFo_9bWUBHbHD1hG:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/031b3ec6a33669765fe621f98532549602f432c3/tests/helgrind.supp#L412)):*
> ```
> # OS: OS version
> # OFED: OFED version if used
> # libibverbs: libibverbs version
> ```

.



_Code quote:_
```
# Suppression format
#
# OS: OS version
# OFED: OFED version if used
# libibverbs: libibverbs version
# librdmacm: librdmacm version
#
```

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1850)* status: all files reviewed, 5 unresolved discussions (waiting on @osalyk)

___
*[`tests/drd.supp` line 388 at r1](https://reviewable.io/reviews/pmem/rpma/1850#-N54CvJd4noD66KcPLNh:-N54UxvUEz34F3yjKWwe:be8rsic) ([raw file](https://github.com/pmem/rpma/blob/031b3ec6a33669765fe621f98532549602f432c3/tests/drd.supp#L388)):*
> ```
> 
> # Suppression format
> #
> ```

Public API calls should be mentioned here.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1850)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`tests/drd.supp` line 387 at r1](https://reviewable.io/reviews/pmem/rpma/1850#-N54GvCH05crJ3t2mfdu:-N54VLHwAoceRJX-RWp2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/031b3ec6a33669765fe621f98532549602f432c3/tests/drd.supp#L387)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
#
# All suppressions should follow the following format:
#
```

And this should be located at the top of each file.

</blockquote></details>

Done.
___
*[`tests/drd.supp` line 388 at r1](https://reviewable.io/reviews/pmem/rpma/1850#-N54CvJd4noD66KcPLNh:-N54VU-C78a9x5daDiOW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/031b3ec6a33669765fe621f98532549602f432c3/tests/drd.supp#L388)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Public API calls should be mentioned here.
</blockquote></details>

Done.
___
*[`tests/drd.supp` line 389 at r1](https://reviewable.io/reviews/pmem/rpma/1850#-N54JWEi9VkeFs6omDhJ:-N54VZEf-QS7IetloKdy:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/031b3ec6a33669765fe621f98532549602f432c3/tests/drd.supp#L389)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
# OS: a version of OS
# OFED: a version of OFED if used
# libibverbs: a version of libibverbs
# librdmacm: a version of librdmacm
```

</blockquote></details>

Done.
___
*[`tests/drd.supp` line 393 at r1](https://reviewable.io/reviews/pmem/rpma/1850#-N54GdPv2-SqAYO7geJH:-N54VgFS3G6Sogt4aixc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/031b3ec6a33669765fe621f98532549602f432c3/tests/drd.supp#L393)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`rdma-core: a version of the 'rdma-core' package if installed`
</blockquote></details>

Done.
___
*[`tests/helgrind.supp` line 412 at r1](https://reviewable.io/reviews/pmem/rpma/1850#-N54KFo_9bWUBHbHD1hF:-N54VyF861jHQjYiwH9F:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/031b3ec6a33669765fe621f98532549602f432c3/tests/helgrind.supp#L412)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1850)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1850#-N54YIm-DgBB2iMqfW_I:-N54YIm-DgBB2iMqfW_J:bl9191q) (no related file):*
We should be prepared for 3 types of suppressions
- general one (on external API level) 
```
{
...
fun:ibv_dontfork_range
...
}
```
- explicit librpma API call
```
{
...
fun:rpma_conn_cfg_set_timeout
...
}
```
- detailed external one (on external API) 
```
{
fun:funA
fun:funB
fun:funC
fun:function_call_used directly form_public_API
}
```

___
___
*[`tests/drd.supp` line 20 at r2](https://reviewable.io/reviews/pmem/rpma/1850#-N54WYvK78lti76WluQ7:-N54WYvK78lti76WluQ8:b-oxt04e) ([raw file](https://github.com/pmem/rpma/blob/839a368d329e425af86446905f76e609d495ec0e/tests/drd.supp#L20)):*
> ```
> # - rpma_mr_reg
> #
> # {
> ```

#
# Assessment: (XXX - to mark assessment that is not done yet)
#
# This suppression does not indicate a lack of MT safety.
# Explanation why ...
or
# This suppression indicates a lack of MT safety.

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1850)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[`tests/drd.supp` line 20 at r2](https://reviewable.io/reviews/pmem/rpma/1850#-N54WYvK78lti76WluQ7:-N54_v-MA84TkdSd6wwV:bpg6jnn) ([raw file](https://github.com/pmem/rpma/blob/839a368d329e425af86446905f76e609d495ec0e/tests/drd.supp#L20)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

#
# Assessment: (XXX - to mark assessment that is not done yet)
#
# This suppression does not indicate a lack of MT safety.
# Explanation why ...
or
# This suppression indicates a lack of MT safety.

</blockquote></details>

Where are all my ``#``?

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1850)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1850#-N54YIm-DgBB2iMqfW_I:-N54hbdD5nGshOeVNevh:b-896fix) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

We should be prepared for 3 types of suppressions
- general one (on external API level) 
```
{
...
fun:ibv_dontfork_range
...
}
```
- explicit librpma API call
```
{
...
fun:rpma_conn_cfg_set_timeout
...
}
```
- detailed external one (on external API) 
```
{
fun:funA
fun:funB
fun:funC
fun:function_call_used directly form_public_API
}
```
</blockquote></details>

Done.

___
___
*[`tests/drd.supp` line 20 at r2](https://reviewable.io/reviews/pmem/rpma/1850#-N54WYvK78lti76WluQ7:-N54gBZ-588bHy1KJo6h:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/839a368d329e425af86446905f76e609d495ec0e/tests/drd.supp#L20)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Where are all my ``#``?
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1850)* status: all files reviewed, 10 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`tests/drd.supp` line 22 at r3](https://reviewable.io/reviews/pmem/rpma/1850#-N54vQxe6WiiD0h5Qyrg:-N54vQxe6WiiD0h5Qyrh:b-yn2hft) ([raw file](https://github.com/pmem/rpma/blob/64fe827f1c0b39e743729d98e8c8d3884e2ae3a3/tests/drd.supp#L22)):*
> ```
> #
> # Occurs in traces of:
> # - function name
> ```

`a function name of public API of librpma`



_Code quote:_
```
function name
```
___
*[`tests/helgrind.supp` line 22 at r3](https://reviewable.io/reviews/pmem/rpma/1850#-N54vYHeEHCwBwaBB8OD:-N54vYHeEHCwBwaBB8OE:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/64fe827f1c0b39e743729d98e8c8d3884e2ae3a3/tests/helgrind.supp#L22)):*
> ```
> #
> # Occurs in traces of:
> # - function name
> ```

.



_Code quote:_
```
function name
```
___
*[`tests/helgrind.supp` line 23 at r3](https://reviewable.io/reviews/pmem/rpma/1850#-N54vZwM4OaSdpL5Ryyi:-N54vZwM4OaSdpL5Ryyj:b-3qazkw) ([raw file](https://github.com/pmem/rpma/blob/64fe827f1c0b39e743729d98e8c8d3884e2ae3a3/tests/helgrind.supp#L23)):*
> ```
> # Occurs in traces of:
> # - function name
> #
> ```

only one empty line here



_Code quote:_
```
#
#
```
___
*[`tests/helgrind.supp` line 27 at r3](https://reviewable.io/reviews/pmem/rpma/1850#-N54vdQOCpHs3uOK8eTA:-N54vdQOCpHs3uOK8eTB:bcxj3jp) ([raw file](https://github.com/pmem/rpma/blob/64fe827f1c0b39e743729d98e8c8d3884e2ae3a3/tests/helgrind.supp#L27)):*
> ```
> # There are 3 types of suppressions:
> #
> # - general one (on external API level)
> ```

`1) general one  (on an external API)`



_Code quote:_
```
- general
```
___
*[`tests/helgrind.supp` line 36 at r3](https://reviewable.io/reviews/pmem/rpma/1850#-N54w-_F3odj9dG8dVAo:-N54w-_F3odj9dG8dVAp:b7fyrcg) ([raw file](https://github.com/pmem/rpma/blob/64fe827f1c0b39e743729d98e8c8d3884e2ae3a3/tests/helgrind.supp#L36)):*
> ```
> # }
> #
> # - explicit librpma API call
> ```

`2) explicit ...`



_Code quote:_
```
- explicit
```
___
*[`tests/helgrind.supp` line 45 at r3](https://reviewable.io/reviews/pmem/rpma/1850#-N54w71ZEmTtXOaEREBT:-N54w71ZEmTtXOaEREBU:b298wcz) ([raw file](https://github.com/pmem/rpma/blob/64fe827f1c0b39e743729d98e8c8d3884e2ae3a3/tests/helgrind.supp#L45)):*
> ```
> # }
> #
> # - detailed external one (on external API)
> ```

`3) detailed ...`



_Code quote:_
```
- detailed
```
___
*[`tests/helgrind.supp` line 45 at r3](https://reviewable.io/reviews/pmem/rpma/1850#-N54wAAt3XMU-EEzirqj:-N54wAAt3XMU-EEzirqk:b-ugojfp) ([raw file](https://github.com/pmem/rpma/blob/64fe827f1c0b39e743729d98e8c8d3884e2ae3a3/tests/helgrind.supp#L45)):*
> ```
> # }
> #
> # - detailed external one (on external API)
> ```

`(on an external API)`



_Code quote:_
```
(on external API)
```

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 2 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1850)* status: all files reviewed, 7 unresolved discussions (waiting on @osalyk)

**Review by grom72 — APPROVED** [review]
:goat:

> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1850#-:-N55-lov0jyfl1Dui9iS:bdycps0)* status: all files reviewed, 7 unresolved discussions (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1850)* status: 0 of 2 files reviewed, 7 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`tests/drd.supp` line 22 at r3](https://reviewable.io/reviews/pmem/rpma/1850#-N54vQxe6WiiD0h5Qyrg:-N552FdT1ggSaKPUcNS-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/64fe827f1c0b39e743729d98e8c8d3884e2ae3a3/tests/drd.supp#L22)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`a function name of public API of librpma`
</blockquote></details>

Done.
___
*[`tests/helgrind.supp` line 22 at r3](https://reviewable.io/reviews/pmem/rpma/1850#-N54vYHeEHCwBwaBB8OD:-N552PCg8UyTBrMm-zLM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/64fe827f1c0b39e743729d98e8c8d3884e2ae3a3/tests/helgrind.supp#L22)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`tests/helgrind.supp` line 23 at r3](https://reviewable.io/reviews/pmem/rpma/1850#-N54vZwM4OaSdpL5Ryyi:-N552Sqe9R95-9Fq75sz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/64fe827f1c0b39e743729d98e8c8d3884e2ae3a3/tests/helgrind.supp#L23)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

only one empty line here
</blockquote></details>

Done.
___
*[`tests/helgrind.supp` line 27 at r3](https://reviewable.io/reviews/pmem/rpma/1850#-N54vdQOCpHs3uOK8eTA:-N552YW_AxDzbPYqVmqj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/64fe827f1c0b39e743729d98e8c8d3884e2ae3a3/tests/helgrind.supp#L27)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`1) general one  (on an external API)`
</blockquote></details>

Done.
___
*[`tests/helgrind.supp` line 36 at r3](https://reviewable.io/reviews/pmem/rpma/1850#-N54w-_F3odj9dG8dVAo:-N552bwu-JLMc0PWU0uK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/64fe827f1c0b39e743729d98e8c8d3884e2ae3a3/tests/helgrind.supp#L36)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`2) explicit ...`
</blockquote></details>

Done.
___
*[`tests/helgrind.supp` line 45 at r3](https://reviewable.io/reviews/pmem/rpma/1850#-N54w71ZEmTtXOaEREBT:-N552fRwEMKhEy7YeSj0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/64fe827f1c0b39e743729d98e8c8d3884e2ae3a3/tests/helgrind.supp#L45)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`3) detailed ...`
</blockquote></details>

Done.
___
*[`tests/helgrind.supp` line 45 at r3](https://reviewable.io/reviews/pmem/rpma/1850#-N54wAAt3XMU-EEzirqj:-N552kZ04dbYVyzippuA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/64fe827f1c0b39e743729d98e8c8d3884e2ae3a3/tests/helgrind.supp#L45)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`(on an external API)`
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1850)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[`tests/drd.supp` line 26 at r4](https://reviewable.io/reviews/pmem/rpma/1850#-N555OF097JthMYss5yp:-N555OF097JthMYss5yq:b-ugojfp) ([raw file](https://github.com/pmem/rpma/blob/c0bb1f204571a3c55fb07d4cdc61369ceac80459/tests/drd.supp#L26)):*
> ```
> # There are 3 types of suppressions:
> #
> # 1) general one (on external API level)
> ```

`(on an external API)`



_Code quote:_
```
(on external API level)
```
___
*[`tests/helgrind.supp` line 27 at r3](https://reviewable.io/reviews/pmem/rpma/1850#-N54vdQOCpHs3uOK8eTA:-N555Yg4CX4pRc2SUOIp:b-ugojfp) ([raw file](https://github.com/pmem/rpma/blob/64fe827f1c0b39e743729d98e8c8d3884e2ae3a3/tests/helgrind.supp#L27)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`(on an external API)`

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1850)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[`tests/drd.supp` line 26 at r4](https://reviewable.io/reviews/pmem/rpma/1850#-N555OF097JthMYss5yp:-N555zFb0K4jL5MmfzVk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c0bb1f204571a3c55fb07d4cdc61369ceac80459/tests/drd.supp#L26)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`(on an external API)`
</blockquote></details>

Done.
___
*[`tests/helgrind.supp` line 27 at r3](https://reviewable.io/reviews/pmem/rpma/1850#-N54vdQOCpHs3uOK8eTA:-N556CDr1Z4-pomzzzKW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/64fe827f1c0b39e743729d98e8c8d3884e2ae3a3/tests/helgrind.supp#L27)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`(on an external API)`
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1850#-:-N55D3eo6gwdLgjinU8j:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1850#-:-N55O80i4TjQXrohp6VO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1850)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
