### PR TITLE
tools: rename high_level_setup_figure and copy it to the output directory

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1210)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1210)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/report.json.example, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1210#-MhrN_QF7H-sq6ODqukj:-MhrN_QHC-kD6FbJiUPq:boqwmf2) ([raw file](https://github.com/pmem/rpma/blob/7fb81d26fd907f909c3897fad1e26bb139b0967e/tools/perf/report.json.example#L2)):*
> ```
> {
>     "_comment": "high_level_setup_figure requires making the path absolute",
> ```

You forgot about something.
___
*[tools/perf/lib/Report.py, line 69 at r1](https://reviewable.io/reviews/pmem/rpma/1210#-MhrQcwfCNoIqAwMwgFm:-MhrPb4D2-nTHYWsKSQL:b-ud0sjs) ([raw file](https://github.com/pmem/rpma/blob/7fb81d26fd907f909c3897fad1e26bb139b0967e/tools/perf/lib/Report.py#L69)):*
> ```Python
>         # copy schematic
>         shutil.copy(self.variables['configuration']['schematic'], self.result_dir)
>         self.variables['configuration']['schematic'] = os.path.basename(self.variables['configuration']['schematic'])
> ```

I'm pretty sure it is not the right place for it. Let's see what will happen when you will upgrade the test. ;-)
___
*[tools/perf/tests/lib/report/test_init.py, line 56 at r1](https://reviewable.io/reviews/pmem/rpma/1210#-MhrQF1gESUvEOcBzrOx:-MhrQF1gESUvEOcBzrOy:b-qn6bfp) ([raw file](https://github.com/pmem/rpma/blob/7fb81d26fd907f909c3897fad1e26bb139b0967e/tools/perf/tests/lib/report/test_init.py#L56)):*
> ```Python
>                 'excerpt': {}
>             },
>             'schematic': 'Figure_0.png'
> ```

A rich request but the test is a little poor. :D
Please provide here a good relative or absolute path so you can verify if it was modified later on.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1210)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/report.json.example, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1210#-MhrN_QF7H-sq6ODqukj:-MhricrbD6RyVZx505dd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7fb81d26fd907f909c3897fad1e26bb139b0967e/tools/perf/report.json.example#L2)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You forgot about something.
</blockquote></details>

Done.
___
*[tools/perf/lib/Report.py, line 69 at r1](https://reviewable.io/reviews/pmem/rpma/1210#-MhrQcwfCNoIqAwMwgFm:-MhridvvEr7L555xZAau:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7fb81d26fd907f909c3897fad1e26bb139b0967e/tools/perf/lib/Report.py#L69)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I'm pretty sure it is not the right place for it. Let's see what will happen when you will upgrade the test. ;-)
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/report/test_init.py, line 56 at r1](https://reviewable.io/reviews/pmem/rpma/1210#-MhrQF1gESUvEOcBzrOx:-Mhrieio4KR2Jx4EC2bg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7fb81d26fd907f909c3897fad1e26bb139b0967e/tools/perf/tests/lib/report/test_init.py#L56)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

A rich request but the test is a little poor. :D
Please provide here a good relative or absolute path so you can verify if it was modified later on.
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1210)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/tests/lib/report/test_init.py, line 36 at r2](https://reviewable.io/reviews/pmem/rpma/1210#-Mhro8h8CZ72gfTYrclw:-Mhro8h8CZ72gfTYrclx:b9r57ae) ([raw file](https://github.com/pmem/rpma/blob/9dacbc53cb034700010a9f8c65d3ec9a79f75167/tools/perf/tests/lib/report/test_init.py#L36)):*
> ```Python
> PART_DUMMY = "dummy"
> SCHEMATIC_FILE = 'Figure.png'
> SCHEMATIC_PATH = 'xxx/' + SCHEMATIC_FILE
> ```

`xxx` is reserved for things that require changes. Please use something else.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1210)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/tests/lib/report/test_init.py, line 36 at r2](https://reviewable.io/reviews/pmem/rpma/1210#-Mhro8h8CZ72gfTYrclw:-MhrpCEpElu3Ifk7Yxln:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9dacbc53cb034700010a9f8c65d3ec9a79f75167/tools/perf/tests/lib/report/test_init.py#L36)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`xxx` is reserved for things that require changes. Please use something else.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1210#-:-MhsH6S83f9_aRxIXDi7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
