### PR TITLE
rpma: add bool *is_rcq argument to rpma_conn_wait

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1654)

### CODE REVIEW

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1654#-:-N-XlhVw-ZHcNtMtNuIh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1654)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[src/conn.c, line 226 at r1](https://reviewable.io/reviews/pmem/rpma/1654#-N-XkrT37I8HJSBNBTBL:-N-XkrT37I8HJSBNBTBM:bdc96as) ([raw file](https://github.com/pmem/rpma/blob/01d0037adc85a17466168615582eb920430daa59/src/conn.c#L226)):*
> ```C
> 		return RPMA_E_NO_COMPLETION;
> 
> 	bool is_rcq_temp;
> ```

bool is_rcq_temp = false;



_Code quote:_
```C
bool is_rcq_temp;
```
___
*[src/conn.c, line 229 at r1](https://reviewable.io/reviews/pmem/rpma/1654#-N-XkuQ3EmihVZAMD5mQ:-N-XkuQ3EmihVZAMD5mR:bjdqao8) ([raw file](https://github.com/pmem/rpma/blob/01d0037adc85a17466168615582eb920430daa59/src/conn.c#L229)):*
> ```C
> 	if (ev_cq == rpma_cq_get_ibv_cq(conn->cq)) {
> 		*cq = conn->cq;
> 		is_rcq_temp = false;
> ```

redundant



_Code quote:_
```C
		is_rcq_temp = false;
```
___
*[src/conn.c, line 230 at r1](https://reviewable.io/reviews/pmem/rpma/1654#-N-XkhJM6KkvOXo9Puwo:-N-XkhJM6KkvOXo9Puwp:brb2wek) ([raw file](https://github.com/pmem/rpma/blob/01d0037adc85a17466168615582eb920430daa59/src/conn.c#L230)):*
> ```C
> 		*cq = conn->cq;
> 		is_rcq_temp = false;
> 	} else if (ev_cq == rpma_cq_get_ibv_cq(conn->rcq)) {
> ```

what if we have no RCQ?



_Code quote:_
```C
} else if (ev_cq == rpma_cq_get_ibv_cq(conn->rcq)) {
```
___
*[src/conn.c, line 234 at r1](https://reviewable.io/reviews/pmem/rpma/1654#-N-XkMeU99ATYSrwFbRt:-N-XkMeV77S0Vx5Dgp9d:b-soskv2) ([raw file](https://github.com/pmem/rpma/blob/01d0037adc85a17466168615582eb920430daa59/src/conn.c#L234)):*
> ```C
> 		is_rcq_temp = true;
> 	} else {
> 		*cq = NULL;
> ```

As I remember we do not set arguments values in case an error is returned



_Code quote:_
```C
*cq = NULL;
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1654)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1654)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1654)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[src/conn.c, line 226 at r1](https://reviewable.io/reviews/pmem/rpma/1654#-N-XkrT37I8HJSBNBTBL:-N-Y5Dw-4o9pEV0vfK1t:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/01d0037adc85a17466168615582eb920430daa59/src/conn.c#L226)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

bool is_rcq_temp = false;
</blockquote></details>

Done.
___
*[src/conn.c, line 229 at r1](https://reviewable.io/reviews/pmem/rpma/1654#-N-XkuQ3EmihVZAMD5mQ:-N-Y5F-895TkaGHoY4Bw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/01d0037adc85a17466168615582eb920430daa59/src/conn.c#L229)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

redundant
</blockquote></details>

Done.
___
*[src/conn.c, line 230 at r1](https://reviewable.io/reviews/pmem/rpma/1654#-N-XkhJM6KkvOXo9Puwo:-N-Y69X-EU6PPdhfphH8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/01d0037adc85a17466168615582eb920430daa59/src/conn.c#L230)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

what if we have no RCQ?
</blockquote></details>

Done.
___
*[src/conn.c, line 234 at r1](https://reviewable.io/reviews/pmem/rpma/1654#-N-XkMeU99ATYSrwFbRt:-N-Y7Bm9AVpPao782xRk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/01d0037adc85a17466168615582eb920430daa59/src/conn.c#L234)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

As I remember we do not set arguments values in case an error is returned
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1654)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @grom72 and @osalyk)

___
*[src/conn.c, line 226 at r2](https://reviewable.io/reviews/pmem/rpma/1654#-N-Y8RBoDNVNEEwYF-Sd:-N-YCjkS7Yg_uT5AOEvp:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/af4287994e13762c48506f192b1505915251af5f/src/conn.c#L226)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```
	if (conn->cq && (rpma_cq_get_ibv_cq(conn->cq) == ev_cq)) {
		*cq = conn->cq;
		if (is_rcq)
			*is_rcq = false;
	} else if (conn->rcq && (rpma_cq_get_ibv_cq(conn->rcq) == ev_cq)) {
		*cq = conn->rcq;
		if (is_rcq)
			*is_rcq = true;
	} else {

		RPMA_LOG_ERROR("ibv_get_cq_event() returned unknown CQ");
		return RPMA_E_UNKNOWN;
	}
```
</blockquote></details>

Done

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1654)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1654#-:-N-ZKsqDBjJJF6NuFzFs:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
