### PR TITLE
common: fix 'initialize' with 'initiate' where needed

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/458)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/458#-:-MIIVtO88y38jXLzzGeV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/458#-:-MIIgMP1D07Xq79uvrez:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[examples/06-multiple-connections/server.c, line 200 at r1](https://reviewable.io/reviews/pmem/rpma/458#-MIIfX9REr1sx7wE-eSl:-MIIfX9SDDI4vroBJN8F:b-cuwv59) ([raw file](https://github.com/pmem/rpma/blob/51f9cb235449a599752c15b4b0044f84019b2a62/examples/06-multiple-connections/server.c#L200)):*
I think this sentence requires a little rewrite:

> No matter what, the disconnection process will be initiated.

What do you think?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/458)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @janekmi and @osalyk)

___
*[examples/06-multiple-connections/server.c, line 200 at r1](https://reviewable.io/reviews/pmem/rpma/458#-MIIfX9REr1sx7wE-eSl:-MIIs_8BDnk8dHia3aPT:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/51f9cb235449a599752c15b4b0044f84019b2a62/examples/06-multiple-connections/server.c#L200)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think this sentence requires a little rewrite:

> No matter what, the disconnection process will be initiated.

What do you think?
</blockquote></details>

Done

**Review by janekmi — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/458)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
