### PR TITLE
tools: add path of the input file to the json_from_file() output

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1106)

### CODE REVIEW

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1106#-:-MdHtpfz0H-ZvZjR8LrJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1106)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/lib/common.py, line 33 at r1](https://reviewable.io/reviews/pmem/rpma/1106#-MdMUXwGBmyE2wZCHp8G:-MdMUXwGBmyE2wZCHp8H:b-427sm2) ([raw file](https://github.com/pmem/rpma/blob/356fba4a1d2a9999622da0420eef1e5bcd2e165c/tools/perf/lib/common.py#L33)):*
> ```Python
>         data = json.load(read_file)
>     # save path of the input file
>     data['input_file'] = string
> ```

I have just realized... this works on the assumption the read JSON structure is a dictionary whereas it may also be a list. So it won't work in the general case.

We have to build a dictionary on our own e.g.

```python
return {'input_file': string, 'json': data}
```

or return a tuple:

```python
return (string, data)
```

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1106)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/lib/Figure.py, line 97 at r2](https://reviewable.io/reviews/pmem/rpma/1106#-MdNj2VA-SeBkG1OEiOl:-MdNj2VA-SeBkG1OEiOm:bnmnkfg) ([raw file](https://github.com/pmem/rpma/blob/0ce57a00b39640c99407476ba666cf8ffe6d3a1f/tools/perf/lib/Figure.py#L97)):*
> ```Python
>                 '.json')
>             data = json_from_file(idfile)
>             rows = data['json']
> ```

You can put these two lines into a single line:

```python
rows = json_from_file(idfile)['json']
```
___
*[tools/perf/lib/Figure.py, line 109 at r2](https://reviewable.io/reviews/pmem/rpma/1106#-MdNjFSV2TwVO1KfpUEF:-MdNjFSV2TwVO1KfpUEG:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/0ce57a00b39640c99407476ba666cf8ffe6d3a1f/tools/perf/lib/Figure.py#L109)):*
> ```Python
>         if os.path.exists(series_path):
>             data = json_from_file(series_path)
>             figures = data['json']
> ```

.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1106)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/lib/Figure.py, line 97 at r2](https://reviewable.io/reviews/pmem/rpma/1106#-MdNj2VA-SeBkG1OEiOl:-MdQMzi0ARPkZAMAlDy9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0ce57a00b39640c99407476ba666cf8ffe6d3a1f/tools/perf/lib/Figure.py#L97)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You can put these two lines into a single line:

```python
rows = json_from_file(idfile)['json']
```
</blockquote></details>

Done.
___
*[tools/perf/lib/Figure.py, line 109 at r2](https://reviewable.io/reviews/pmem/rpma/1106#-MdNjFSV2TwVO1KfpUEF:-MdQN-OeEiNhDgxoSWq4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0ce57a00b39640c99407476ba666cf8ffe6d3a1f/tools/perf/lib/Figure.py#L109)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1106#-:-MdR8P4A5BNiSh9O-x_1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1106#-:-MdRoQsY1c-PWaQGOvm8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
