### PR TITLE
tools: missing direct_wrte_to_pmem exception added

### PR DESCRIPTION
**Pull request by grom72**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1460)

### CODE REVIEW

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1460#-:-Ms4qZHPCxYbuMDt-IgO:bg7igkv)* status: 0 of 1 files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1460)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1460)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1460)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 95 at r2](https://reviewable.io/reviews/pmem/rpma/1460#-Ms5f_Ep61ccQbqHrlZ3:-Ms5f_Ep61ccQbqHrlZ4:b-grqpav) ([raw file](https://github.com/pmem/rpma/blob/fda60e9d73aa997255d68d213a417bf0ab1ed0c5/tools/perf/lib/benchmark/runner/fio.py#L95)):*
> ```Python
>         # pick the settings predefined for the chosen mode
>         if 'direct_write_to_pmem' not in self.__benchmark.requirements:
>             raise ValueError(MISSING_KEY_MSG.format('direct_write_to_pmem'))
> ```

It should be added just before:
```
        self.__direct_write_to_pmem = \
            int(self.__benchmark.requirements['direct_write_to_pmem'])
```



_Code quote:_
```Python
        if 'direct_write_to_pmem' not in self.__benchmark.requirements:
            raise ValueError(MISSING_KEY_MSG.format('direct_write_to_pmem'))
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1460)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 95 at r2](https://reviewable.io/reviews/pmem/rpma/1460#-Ms5f_Ep61ccQbqHrlZ3:-Ms5gehi1OmzNtQz1qvE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fda60e9d73aa997255d68d213a417bf0ab1ed0c5/tools/perf/lib/benchmark/runner/fio.py#L95)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It should be added just before:
```
        self.__direct_write_to_pmem = \
            int(self.__benchmark.requirements['direct_write_to_pmem'])
```
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1460#-:-Ms5iD6MCURebtPVsqRB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
