### PR TITLE
tools: check if ib_tool is present remotely

### PR DESCRIPTION
**Pull request by osalyk**
- [x] #1339

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1345)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1345)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau and @osalyk)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 36 at r1](https://reviewable.io/reviews/pmem/rpma/1345#-MpGsAJiDzr_Wgn-xOBK:-MpGsAJiDzr_Wgn-xOBL:bmpy12q) ([raw file](https://github.com/pmem/rpma/blob/0d7d6f687ab5ad9620f2eefb3d09ef46e5399d7d/tools/perf/lib/benchmark/runner/ib_read.py#L36)):*
> ```
> the local
> ```

the remote

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1345)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1345)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 36 at r1](https://reviewable.io/reviews/pmem/rpma/1345#-MpGsAJiDzr_Wgn-xOBK:-MpGtTld59gdAvWiM6bf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0d7d6f687ab5ad9620f2eefb3d09ef46e5399d7d/tools/perf/lib/benchmark/runner/ib_read.py#L36)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> the local
> ```

the remote
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1345#-:-MpGtf4G0raGtCkkxJyP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1345#-:-MpH-uDp52zEE2E1bkMO:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1345)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1345)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1345)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 38 at r3](https://reviewable.io/reviews/pmem/rpma/1345#-MpQB4Vx8lCP1tWIe3Bk:-MpQB4Vx8lCP1tWIe3Bl:bcaw93z) ([raw file](https://github.com/pmem/rpma/blob/c29b82349525f27ee371032f51ff80e985d76f6c/tools/perf/lib/benchmark/runner/ib_read.py#L38)):*
> ```Python
> 
>         output = RemoteCmd.run_sync(self.__config, "which " +
>                                     self.__settings['ib_tool'], None)
> ```

You are missing something. ;-)

Ref: https://github.com/pmem/rpma/blob/master/tools/perf/config.json.example#L13
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 38 at r3](https://reviewable.io/reviews/pmem/rpma/1345#-MpQBFRS2d3MhQlCc07I:-MpQBFRS2d3MhQlCc07J:bjk9c0b) ([raw file](https://github.com/pmem/rpma/blob/c29b82349525f27ee371032f51ff80e985d76f6c/tools/perf/lib/benchmark/runner/ib_read.py#L38)):*
> ```Python
> 
>         output = RemoteCmd.run_sync(self.__config, "which " +
>                                     self.__settings['ib_tool'], None)
> ```

Using the `RemoteCmd` API seems pretty nice. ;-)
:+1:

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1345)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 38 at r3](https://reviewable.io/reviews/pmem/rpma/1345#-MpQB4Vx8lCP1tWIe3Bk:-MpQE60zBkJaR8DEpyVQ:b-nj8tht) ([raw file](https://github.com/pmem/rpma/blob/c29b82349525f27ee371032f51ff80e985d76f6c/tools/perf/lib/benchmark/runner/ib_read.py#L38)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You are missing something. ;-)

Ref: https://github.com/pmem/rpma/blob/master/tools/perf/config.json.example#L13
</blockquote></details>

Right, `REMOTE_IB_PATH` should be used here - the ib tool does not have to be in the system PATH

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1345)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 38 at r3](https://reviewable.io/reviews/pmem/rpma/1345#-MpQB4Vx8lCP1tWIe3Bk:-MpQKKSY8aB-AZPBj9k-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c29b82349525f27ee371032f51ff80e985d76f6c/tools/perf/lib/benchmark/runner/ib_read.py#L38)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Right, `REMOTE_IB_PATH` should be used here - the ib tool does not have to be in the system PATH
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1345)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 38 at r3](https://reviewable.io/reviews/pmem/rpma/1345#-MpQB4Vx8lCP1tWIe3Bk:-MpQNJdb1-cBNuRCEp5E:bl8mftv) ([raw file](https://github.com/pmem/rpma/blob/c29b82349525f27ee371032f51ff80e985d76f6c/tools/perf/lib/benchmark/runner/ib_read.py#L38)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Maybe in this way it will be more clear?
```
cmd = ' '.join('which', self.__config.get('REMOTE_IB_PATH', ''), self.__settings['ib_tool'])
output = RemoteCmd.run_sync(self.__config, cmd, None)
```

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1345)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1345)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 38 at r3](https://reviewable.io/reviews/pmem/rpma/1345#-MpQB4Vx8lCP1tWIe3Bk:-MpQVb3lEHweYVNqD_pR:bmv2987) ([raw file](https://github.com/pmem/rpma/blob/c29b82349525f27ee371032f51ff80e985d76f6c/tools/perf/lib/benchmark/runner/ib_read.py#L38)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Maybe in this way it will be more clear?
```
cmd = ' '.join('which', self.__config.get('REMOTE_IB_PATH', ''), self.__settings['ib_tool'])
output = RemoteCmd.run_sync(self.__config, cmd, None)
```

</blockquote></details>

For paths please use `os.path.join()`.
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 37 at r5](https://reviewable.io/reviews/pmem/rpma/1345#-MpQVtZu9R6CdVKIcMOp:-MpQVtZu9R6CdVKIcMOq:b-bi2hez) ([raw file](https://github.com/pmem/rpma/blob/975b32cb50cabc312d8213e330dc4cf4a7f7f33a/tools/perf/lib/benchmark/runner/ib_read.py#L37)):*
> ```Python
>                              .format(self.__settings['ib_tool']))
> 
>         output = RemoteCmd.run_sync(self.__config, "which " +
> ```

Maybe the `RemoteCmd` API should just accept lists?

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1345)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 38 at r3](https://reviewable.io/reviews/pmem/rpma/1345#-MpQB4Vx8lCP1tWIe3Bk:-MpQZYxP0DwKZk8hT3BQ:bqkw3k) ([raw file](https://github.com/pmem/rpma/blob/c29b82349525f27ee371032f51ff80e985d76f6c/tools/perf/lib/benchmark/runner/ib_read.py#L38)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

For paths please use `os.path.join()`.
</blockquote></details>

os.path.join adds "/" so that "which" fails

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1345)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 37 at r5](https://reviewable.io/reviews/pmem/rpma/1345#-MpQVtZu9R6CdVKIcMOp:-MpQfYtR-1HhyZd2ZpBm:b1iwnya) ([raw file](https://github.com/pmem/rpma/blob/975b32cb50cabc312d8213e330dc4cf4a7f7f33a/tools/perf/lib/benchmark/runner/ib_read.py#L37)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Maybe the `RemoteCmd` API should just accept lists?
</blockquote></details>

Maybe in a separate PR

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1345)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 38 at r3](https://reviewable.io/reviews/pmem/rpma/1345#-MpQB4Vx8lCP1tWIe3Bk:-MpQfM2P19EO9eCwZrAS:b-w03jzf) ([raw file](https://github.com/pmem/rpma/blob/c29b82349525f27ee371032f51ff80e985d76f6c/tools/perf/lib/benchmark/runner/ib_read.py#L38)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

os.path.join adds "/" so that "which" fails
</blockquote></details>

@osalyk `os.path.join` works for me, please try this:
```
from os import path

ib_path = path.join(self.__config.get('REMOTE_IB_PATH', ''),
                    self.__settings['ib_tool'])
cmd = ' '.join(['which', ib_path])
output = RemoteCmd.run_sync(self.__config, cmd, None)
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1345)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 38 at r3](https://reviewable.io/reviews/pmem/rpma/1345#-MpQB4Vx8lCP1tWIe3Bk:-MpQgkLiBDkMl7jDE0bD:bm8csmu) ([raw file](https://github.com/pmem/rpma/blob/c29b82349525f27ee371032f51ff80e985d76f6c/tools/perf/lib/benchmark/runner/ib_read.py#L38)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@osalyk `os.path.join` works for me, please try this:
```
from os import path

ib_path = path.join(self.__config.get('REMOTE_IB_PATH', ''),
                    self.__settings['ib_tool'])
cmd = ' '.join(['which', ib_path])
output = RemoteCmd.run_sync(self.__config, cmd, None)
```
</blockquote></details>

You're right, thanks :)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1345)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1345#-:-MpQlODi1ejZ56MFLaJx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
