### PR TITLE
rpma: adopt usage_to_access to support iWARP specificity XXX

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1029)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1029)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[src/mr.c, line 70 at r1](https://reviewable.io/reviews/pmem/rpma/1029#-MZIe_3g-n5OHaUL1D7v:-MZIe_3g-n5OHaUL1D7w:b4opow3) ([raw file](https://github.com/pmem/rpma/blob/b7179c50364cc67e6c51c4d9da9212012e560bdd/src/mr.c#L70)):*
> ```
> usage_to_access(struct rpma_peer *peer, int usage)
> ```
usage_to_access(int usage, struct rpma_peer *peer)

BTW
do we need a whole peer here?
in this case, shall we move usage_to_access to peer_usage_to_access?
___
*[src/peer.c, line 158 at r1](https://reviewable.io/reviews/pmem/rpma/1029#-MZIegBX6bJcoB50pwo1:-MZIegBX6bJcoB50pwo2:b-38bhzz) ([raw file](https://github.com/pmem/rpma/blob/b7179c50364cc67e6c51c4d9da9212012e560bdd/src/peer.c#L158)):*
> ```C
>  */
> enum ibv_transport_type
> rpma_peer_get_transport_type(struct rpma_peer *peer)
> ```

inline?

**Review by grom72 — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1029)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1029)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[src/mr.c, line 70 at r1](https://reviewable.io/reviews/pmem/rpma/1029#-MZIe_3g-n5OHaUL1D7v:-MZXf1vs4oYVcONfwZDj:b422gh) ([raw file](https://github.com/pmem/rpma/blob/b7179c50364cc67e6c51c4d9da9212012e560bdd/src/mr.c#L70)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> usage_to_access(struct rpma_peer *peer, int usage)
> ```
usage_to_access(int usage, struct rpma_peer *peer)

BTW
do we need a whole peer here?
in this case, shall we move usage_to_access to peer_usage_to_access?
</blockquote></details>

Yes. I like the idea. Moved.
___
*[src/peer.c, line 158 at r1](https://reviewable.io/reviews/pmem/rpma/1029#-MZIegBX6bJcoB50pwo1:-MZXf7q3BZuyU732GWQs:bu4ephv) ([raw file](https://github.com/pmem/rpma/blob/b7179c50364cc67e6c51c4d9da9212012e560bdd/src/peer.c#L158)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

inline?
</blockquote></details>

Dropped.

**Review by ldorau — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1029)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Comment by janekmi** [comment]
Ref: #1044

**Pull request closed without merging**
