### PR TITLE
tools: create_report_figures.sh big revamp

### PR DESCRIPTION
**Pull request by janekmi**
**Tip**: This script was almost completely rewritten. I recommend reading just the final shape since comparing it to what was here previously may be confusing.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/803)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/803)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi)

___
*[tools/create_report_figures.sh, line 45 at r1](https://reviewable.io/reviews/pmem/rpma/803#-MST4RyB4fUDzU5DrrlR:-MST4RyB4fUDzU5DrrlS:b-3wdsa7) ([raw file](https://github.com/pmem/rpma/blob/96c0673140d1f323d88905ec82e44dff4ba36d37/tools/create_report_figures.sh#L45)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>     echo "export READ_LAT_MACHINE=MACHINE"
>     echo "export READ_BW_MACHINE=MACHINE"
>     echo "export WRITE_LAT_MACHINE=MACHINE"
>     echo "export WRITE_BW_MACHINE=MACHINE"
>     echo "export MIX_LAT_MACHINE=MACHINE"
>     echo "export MIX_BW_MACHINE=MACHINE"
> ```
</details>


I would replace all `=MACHINE"` with `=<machine>"` - IMHO it would more readable.
___
*[tools/create_report_figures.sh, line 56 at r1](https://reviewable.io/reviews/pmem/rpma/803#-MST2rrb3EUlDEwvb3eE:-MST2rrb3EUlDEwvb3eF:b-q3kskk) ([raw file](https://github.com/pmem/rpma/blob/96c0673140d1f323d88905ec82e44dff4ba36d37/tools/create_report_figures.sh#L56)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> report)
>     ;;
> appendix)
>     ;;
> ```
</details>


```
report|appendix)
    ;;
```
___
*[tools/create_report_figures.sh, line 127 at r1](https://reviewable.io/reviews/pmem/rpma/803#-MST4tnS7GYGQv6shCs0:-MST4tnS7GYGQv6shCs1:b6d7gtp) ([raw file](https://github.com/pmem/rpma/blob/96c0673140d1f323d88905ec82e44dff4ba36d37/tools/create_report_figures.sh#L127)):*
> ```
>  if [ "$#" -gt "0" ]; then
> ```

` if [ $# -gt 0 ]; then`
___
*[tools/create_report_figures.sh, line 273 at r1](https://reviewable.io/reviews/pmem/rpma/803#-MST5Fa6DmA-aQMKaUB-:-MST5Fa6DmA-aQMKaUB0:blhx6a9) ([raw file](https://github.com/pmem/rpma/blob/96c0673140d1f323d88905ec82e44dff4ba36d37/tools/create_report_figures.sh#L273)):*
> ```
>  if [ "$#" -gt "0" ]; then
> ```

.
___
*[tools/create_report_figures.sh, line 308 at r1](https://reviewable.io/reviews/pmem/rpma/803#-MST5LLu9fLwsS1GMkTQ:-MST5LLu9fLwsS1GMkTR:b-1fer39) ([raw file](https://github.com/pmem/rpma/blob/96c0673140d1f323d88905ec82e44dff4ba36d37/tools/create_report_figures.sh#L308)):*
> ```
>     if [ "$#" -gt 0 ]; then
> ```

.
___
*[tools/create_report_figures.sh, line 456 at r1](https://reviewable.io/reviews/pmem/rpma/803#-MST5bZZ7LvOQ_CeXUGQ:-MST5bZZ7LvOQ_CeXUGR:by1oiau) ([raw file](https://github.com/pmem/rpma/blob/96c0673140d1f323d88905ec82e44dff4ba36d37/tools/create_report_figures.sh#L456)):*
> ```
> [ ! -d "$REPORT_DIR" ] && mkdir $REPORT_DIR
> ```

`mkdir -p $REPORT_DIR`

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/803)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @ldorau)

___
*[tools/create_report_figures.sh, line 56 at r1](https://reviewable.io/reviews/pmem/rpma/803#-MST2rrb3EUlDEwvb3eE:-MSWsgrJCrc6q_-Ue6OB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/96c0673140d1f323d88905ec82e44dff4ba36d37/tools/create_report_figures.sh#L56)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> report)
>     ;;
> appendix)
>     ;;
> ```

```
report|appendix)
    ;;
```
</blockquote></details>

Done.
___
*[tools/create_report_figures.sh, line 127 at r1](https://reviewable.io/reviews/pmem/rpma/803#-MST4tnS7GYGQv6shCs0:-MSWsxuI0wCRZonbDpFw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/96c0673140d1f323d88905ec82e44dff4ba36d37/tools/create_report_figures.sh#L127)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  if [ "$#" -gt "0" ]; then
> ```

` if [ $# -gt 0 ]; then`
</blockquote></details>

Done.
___
*[tools/create_report_figures.sh, line 273 at r1](https://reviewable.io/reviews/pmem/rpma/803#-MST5Fa6DmA-aQMKaUB-:-MSWsyUzEOQg3L5X5B4A:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/96c0673140d1f323d88905ec82e44dff4ba36d37/tools/create_report_figures.sh#L273)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  if [ "$#" -gt "0" ]; then
> ```

.
</blockquote></details>

Done.
___
*[tools/create_report_figures.sh, line 308 at r1](https://reviewable.io/reviews/pmem/rpma/803#-MST5LLu9fLwsS1GMkTQ:-MSWsyxuCTAhLhjXpkgX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/96c0673140d1f323d88905ec82e44dff4ba36d37/tools/create_report_figures.sh#L308)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>     if [ "$#" -gt 0 ]; then
> ```

.
</blockquote></details>

Done.
___
*[tools/create_report_figures.sh, line 456 at r1](https://reviewable.io/reviews/pmem/rpma/803#-MST5bZZ7LvOQ_CeXUGQ:-MSWtEPD0qMxYMnMXDuT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/96c0673140d1f323d88905ec82e44dff4ba36d37/tools/create_report_figures.sh#L456)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> [ ! -d "$REPORT_DIR" ] && mkdir $REPORT_DIR
> ```

`mkdir -p $REPORT_DIR`
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/803)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/803#-:-MSWtikZ6kEXtbaQHHth:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/803#-:-MSX11h-C_J-bcgKsL5j:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/803)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
