### PR TITLE
Fixed log level names - to avoid problems with klockwork

### PR DESCRIPTION
**Pull request by grom72**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/389)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/389)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/389#-:-MGrvfu84gi_OcHH7jrc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/389#-:-MGs57AW9o-vVliyNnis:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/389)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/389#-MHO3ZLP3eXaWBOT0u0y:-MHO3ZLP3eXaWBOT0u0z:b-rsoow6) (no related file):*
Do we have any sources claiming that such PR makes any change for klockwork?

---

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/389)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/389#-MHO3ZLP3eXaWBOT0u0y:-MHPHTwJ7j11iyKGixjb:b-9wh9vx) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Do we have any sources claiming that such PR makes any change for klockwork?
</blockquote></details>

We have to marge it to see results.

---

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/389)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/389)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tests/unit/log_default/function.c, line 53 at r1](https://reviewable.io/reviews/pmem/rpma/389#-MHkggwT3aoOLj9MGDJ6:-MHkggwT3aoOLj9MGDJ7:bqry2jw) ([raw file](https://github.com/pmem/rpma/blob/245f47c70aca0520686582c49904f57fdc89fbaa/tests/unit/log_default/function.c#L53)):*
> ```
> rpma_log_level_names[
> ```

Why do those strings have one space less than in log_default.c ?

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/389)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/389)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/389#-MHO3ZLP3eXaWBOT0u0y:-MHm7CaL8fDI1sJQJVMb:b-896fix) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

We have to marge it to see results.
</blockquote></details>

Done.

---
___
*[tests/unit/log_default/function.c, line 53 at r1](https://reviewable.io/reviews/pmem/rpma/389#-MHkggwT3aoOLj9MGDJ6:-MHoO5hH6Xj9a2t-CKwF:b-896fjb) ([raw file](https://github.com/pmem/rpma/blob/245f47c70aca0520686582c49904f57fdc89fbaa/tests/unit/log_default/function.c#L53)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> rpma_log_level_names[
> ```

Why do those strings have one space less than in log_default.c ?
</blockquote></details>

Done

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/389)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Comment by ldorau** [comment]
> Do we have any sources claiming that such PR makes any change for klockwork?

@janekmi The description of this issue at Klocwork's web page gives hope that this patch will fix some issue. Let's try ...

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/389)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/389#-MHO3ZLP3eXaWBOT0u0y:-MHp8Kl28bzZ35rvDWsA:b-fa7qbx) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The description of this issue at Klocwork's web page gives hope that this patch will fix some issue. Let's try ...

---

**Pull request merged**
