### PR TITLE
test: various minor fixes

### PR DESCRIPTION
**Pull request by ldorau**
Fix various minor issues occurring while compiling with clang.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/302)

### CODE REVIEW

**Review by pbalcer — APPROVED** [review]

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 24 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/302#-:-MFnx-7W9gRH7lF8kI90:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> Reviewed 24 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/302)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/302#-:-MFoIaO-395qoh61XxDS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 24 of 24 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/302)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[tests/unit/log/threshold.c, line 15 at r1](https://reviewable.io/reviews/pmem/rpma/302#-MFpySzB5fsPFfY6FKzj:-MFpySzC6cf1_4fcll-o:b-hpls4l) ([raw file](https://github.com/pmem/rpma/blob/f0c8cc69eb842d3832d72287b3b7189b4d6f0462/tests/unit/log/threshold.c#L15)):*
> ```C
> #include "librpma.h"
> 
> #define INVALID_THRESHOLD_MOCK	- 1
> ```

```c
#define INVALID_THRESHOLD_MOCK (rpma_log_treshold)(-1)
```
___
*[tests/unit/log/threshold.c, line 16 at r1](https://reviewable.io/reviews/pmem/rpma/302#-MFpyqU_0KRYFThuZw7Q:-MFpyqU_0KRYFThuZw7R:b-5lenu7) ([raw file](https://github.com/pmem/rpma/blob/f0c8cc69eb842d3832d72287b3b7189b4d6f0462/tests/unit/log/threshold.c#L16)):*
> ```C
> 
> #define INVALID_THRESHOLD_MOCK	- 1
> #define INVALID_LEVEL_MOCK	- 2
> ```

Not related but as long as we agree to fix also the neighbouring mock...

```c
#define INVALID_LEVEL_MOCK (-2)
```
___
*[tests/unit/log/threshold.c, line 104 at r1](https://reviewable.io/reviews/pmem/rpma/302#-MFpygkXAFiLlRMPUoTg:-MFpygkXAFiLlRMPUoTh:b-mox4zf) ([raw file](https://github.com/pmem/rpma/blob/f0c8cc69eb842d3832d72287b3b7189b4d6f0462/tests/unit/log/threshold.c#L104)):*
> ```C
> {
> 	rpma_log_level level;
> 	for (int i = RPMA_LOG_THRESHOLD; i <= RPMA_LOG_THRESHOLD_AUX; i++) {
> ```

unsigned?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/302)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tests/unit/log/threshold.c, line 15 at r1](https://reviewable.io/reviews/pmem/rpma/302#-MFpySzB5fsPFfY6FKzj:-MG2PIuh0prjHfvW5JnZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f0c8cc69eb842d3832d72287b3b7189b4d6f0462/tests/unit/log/threshold.c#L15)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
#define INVALID_THRESHOLD_MOCK (rpma_log_treshold)(-1)
```
</blockquote></details>

Done.
___
*[tests/unit/log/threshold.c, line 16 at r1](https://reviewable.io/reviews/pmem/rpma/302#-MFpyqU_0KRYFThuZw7Q:-MG2PJOr-XZ7kuYizAE5:bvkqils) ([raw file](https://github.com/pmem/rpma/blob/f0c8cc69eb842d3832d72287b3b7189b4d6f0462/tests/unit/log/threshold.c#L16)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not related but as long as we agree to fix also the neighbouring mock...

```c
#define INVALID_LEVEL_MOCK (-2)
```
</blockquote></details>

```
[ 57%] Building C object tests/unit/log/CMakeFiles/log-threshold.dir/threshold.c.o
/home/ldorau/work/rpma/tests/unit/log/threshold.c:38:4: error: implicit conversion changes signedness: 'rpma_log_threshold' to 'rpma_log_level' [-Werror,-Wsign-conversion]
                        INVALID_LEVEL_MOCK);
                        ^~~~~~~~~~~~~~~~~~
/home/ldorau/work/rpma/tests/unit/log/threshold.c:16:29: note: expanded from macro 'INVALID_LEVEL_MOCK'
#define INVALID_LEVEL_MOCK      ((rpma_log_threshold)(-2))
                                 ^~~~~~~~~~~~~~~~~~~~~~~~
/home/ldorau/work/rpma/tests/unit/log/threshold.c:50:4: error: implicit conversion changes signedness: 'rpma_log_threshold' to 'rpma_log_level' [-Werror,-Wsign-conversion]
                        INVALID_LEVEL_MOCK);
                        ^~~~~~~~~~~~~~~~~~
/home/ldorau/work/rpma/tests/unit/log/threshold.c:16:29: note: expanded from macro 'INVALID_LEVEL_MOCK'
#define INVALID_LEVEL_MOCK      ((rpma_log_threshold)(-2))
                                 ^~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
```
___
*[tests/unit/log/threshold.c, line 104 at r1](https://reviewable.io/reviews/pmem/rpma/302#-MFpygkXAFiLlRMPUoTg:-MG2QJit60SYdTUOqA8W:bnxgrih) ([raw file](https://github.com/pmem/rpma/blob/f0c8cc69eb842d3832d72287b3b7189b4d6f0462/tests/unit/log/threshold.c#L104)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

unsigned?
</blockquote></details>

1) After changing to 'unsigned' the line will be too long, it will have to be broken in two parts and become less readable 
2) AFAIK the 'for' loop is the fastest with 'int' index
Is it worth changing? Does it improve anything?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/302)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tests/unit/log/threshold.c, line 16 at r1](https://reviewable.io/reviews/pmem/rpma/302#-MFpyqU_0KRYFThuZw7Q:-MG2RMZj-iNF9RBdPbkj:btxl9jl) ([raw file](https://github.com/pmem/rpma/blob/f0c8cc69eb842d3832d72287b3b7189b4d6f0462/tests/unit/log/threshold.c#L16)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
[ 57%] Building C object tests/unit/log/CMakeFiles/log-threshold.dir/threshold.c.o
/home/ldorau/work/rpma/tests/unit/log/threshold.c:38:4: error: implicit conversion changes signedness: 'rpma_log_threshold' to 'rpma_log_level' [-Werror,-Wsign-conversion]
                        INVALID_LEVEL_MOCK);
                        ^~~~~~~~~~~~~~~~~~
/home/ldorau/work/rpma/tests/unit/log/threshold.c:16:29: note: expanded from macro 'INVALID_LEVEL_MOCK'
#define INVALID_LEVEL_MOCK      ((rpma_log_threshold)(-2))
                                 ^~~~~~~~~~~~~~~~~~~~~~~~
/home/ldorau/work/rpma/tests/unit/log/threshold.c:50:4: error: implicit conversion changes signedness: 'rpma_log_threshold' to 'rpma_log_level' [-Werror,-Wsign-conversion]
                        INVALID_LEVEL_MOCK);
                        ^~~~~~~~~~~~~~~~~~
/home/ldorau/work/rpma/tests/unit/log/threshold.c:16:29: note: expanded from macro 'INVALID_LEVEL_MOCK'
#define INVALID_LEVEL_MOCK      ((rpma_log_threshold)(-2))
                                 ^~~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
```
</blockquote></details>

The previous comment is wrong, please ignore it ;-)

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/302)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/302)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[tests/unit/log/threshold.c, line 37 at r2](https://reviewable.io/reviews/pmem/rpma/302#-MG3Oca48HwbomTJKpNh:-MG3Oca48HwbomTJKpNi:b3kre) ([raw file](https://github.com/pmem/rpma/blob/b8729f7072dcd4fc5e4e604d932dcdfd1663cc3e/tests/unit/log/threshold.c#L37)):*
> ```C
> {
> 	int ret = rpma_log_set_threshold(
> 			(rpma_log_threshold)RPMA_LOG_THRESHOLD,
> ```

?
___
*[tests/unit/log/threshold.c, line 75 at r2](https://reviewable.io/reviews/pmem/rpma/302#-MG3OnnL35IXO9KkpMkf:-MG3OnnL35IXO9KkpMkg:b3kre) ([raw file](https://github.com/pmem/rpma/blob/b8729f7072dcd4fc5e4e604d932dcdfd1663cc3e/tests/unit/log/threshold.c#L75)):*
> ```C
> {
> 	int ret = rpma_log_get_threshold(
> 			(rpma_log_threshold)RPMA_LOG_THRESHOLD,
> ```

?
___
*[tests/unit/log/threshold.c, line 88 at r2](https://reviewable.io/reviews/pmem/rpma/302#-MG3Oi2885Yeo7_-TNQa:-MG3Oi2885Yeo7_-TNQb:bupx73o) ([raw file](https://github.com/pmem/rpma/blob/b8729f7072dcd4fc5e4e604d932dcdfd1663cc3e/tests/unit/log/threshold.c#L88)):*
> ```C
> {
> 	int ret = rpma_log_get_threshold(INVALID_THRESHOLD_MOCK,
> 			NULL);
> ```

Does not fit into a single line?
___
*[tests/unit/log/threshold.c, line 104 at r2](https://reviewable.io/reviews/pmem/rpma/302#-MG3OmAs-xNqlC5CMPPe:-MG3OmAs-xNqlC5CMPPf:b-xt2u08) ([raw file](https://github.com/pmem/rpma/blob/b8729f7072dcd4fc5e4e604d932dcdfd1663cc3e/tests/unit/log/threshold.c#L104)):*
> ```C
> 				j++) {
> 			int ret = rpma_log_set_threshold(
> 					(rpma_log_threshold)i, j);
> ```

Single line?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/302)* status: 20 of 24 files reviewed, 4 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)

___
*[tests/unit/log/threshold.c, line 37 at r2](https://reviewable.io/reviews/pmem/rpma/302#-MG3Oca48HwbomTJKpNh:-MG3PTbmCIFmbiOk3xU_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b8729f7072dcd4fc5e4e604d932dcdfd1663cc3e/tests/unit/log/threshold.c#L37)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[tests/unit/log/threshold.c, line 75 at r2](https://reviewable.io/reviews/pmem/rpma/302#-MG3OnnL35IXO9KkpMkf:-MG3PkP_8z9aTjm5L46W:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b8729f7072dcd4fc5e4e604d932dcdfd1663cc3e/tests/unit/log/threshold.c#L75)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[tests/unit/log/threshold.c, line 88 at r2](https://reviewable.io/reviews/pmem/rpma/302#-MG3Oi2885Yeo7_-TNQa:-MG3PovI6QnLMXvEL0r7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b8729f7072dcd4fc5e4e604d932dcdfd1663cc3e/tests/unit/log/threshold.c#L88)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Does not fit into a single line?
</blockquote></details>

Done.
___
*[tests/unit/log/threshold.c, line 104 at r2](https://reviewable.io/reviews/pmem/rpma/302#-MG3OmAs-xNqlC5CMPPe:-MG3Q-nP3o3-hqr6lPjD:bjuh88d) ([raw file](https://github.com/pmem/rpma/blob/b8729f7072dcd4fc5e4e604d932dcdfd1663cc3e/tests/unit/log/threshold.c#L104)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Single line?
</blockquote></details>

Too long

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/302#-:-MG3QXivCWFSK2TncCqD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
