### PR TITLE
An option to show all environment variables used by the tool

### PR DESCRIPTION
**Pull request by grom72**
Requires:
- [x] #733

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/734)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/734)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[tools/rpma_fio_bench.sh, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/734#-MQkHcG-9xzTgOkZFck2:-MQkHcG-9xzTgOkZFck3:b-l72ejg) ([raw file](https://github.com/pmem/rpma/blob/c8fe2789a22efdafed471d4721fb13a24a54f38f/tools/rpma_fio_bench.sh#L20)):*
> ```
>  <all|read|write> <all|bw-bs|bw-dp-exp|bw-dp-lin|bw-th|lat>"
> ```

The brackets should not be changed:

```
 [all|read|write] [all|bw-bs|bw-dp-exp|bw-dp-lin|bw-th|lat]
```
___
*[tools/rpma_fio_bench.sh, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/734#-MQkHtnV7hyLZ4oECiCx:-MQkHtnW4RBrODRgl7yJ:b-nqyxpu) ([raw file](https://github.com/pmem/rpma/blob/c8fe2789a22efdafed471d4721fb13a24a54f38f/tools/rpma_fio_bench.sh#L48)):*
> ```
> by script
> ```

by the script
___
*[tools/rpma_fio_bench.sh, line 68 at r1](https://reviewable.io/reviews/pmem/rpma/734#-MQkILP75BVHbTqbeTij:-MQkILP75BVHbTqbeTik:begbjbs) ([raw file](https://github.com/pmem/rpma/blob/c8fe2789a22efdafed471d4721fb13a24a54f38f/tools/rpma_fio_bench.sh#L68)):*
> ```
> if [ "$#" -gt 0 -a "$1" == "--env" ]; then
> ```

`if [ "$1" == "--env" ]; then` 

is enough.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/734)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/rpma_fio_bench.sh, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/734#-MQkHcG-9xzTgOkZFck2:-MQko4uLDKiJ1bJfO_mC:b3acp0q) ([raw file](https://github.com/pmem/rpma/blob/c8fe2789a22efdafed471d4721fb13a24a54f38f/tools/rpma_fio_bench.sh#L20)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  <all|read|write> <all|bw-bs|bw-dp-exp|bw-dp-lin|bw-th|lat>"
> ```

The brackets should not be changed:

```
 [all|read|write] [all|bw-bs|bw-dp-exp|bw-dp-lin|bw-th|lat]
```
</blockquote></details>

This is part of #733. Do you have any clear guidelines on this? I can not look up anything clear stating the rules.
___
*[tools/rpma_fio_bench.sh, line 64 at r1](https://reviewable.io/reviews/pmem/rpma/734#-MQkpCil0jpjWcjuW4KZ:-MQkpCim959wWa6Ynmbr:btt7jym) ([raw file](https://github.com/pmem/rpma/blob/c8fe2789a22efdafed471d4721fb13a24a54f38f/tools/rpma_fio_bench.sh#L64)):*
> ```Shell
> 	echo "export SHORT_RUNTIME=$SHORT_RUNTIME"
> 	echo "export TRACER=$TRACER"
> 	echo "export REMOTE_TRACER=$REMOTE_TRACER"
> ```

I can imagine not having duplicated set of strings as we are having here e.g.:

```bash
USAGE_VARIABLES_STR=" \
export VAR=\\$VAR"

function usage() {
    VAR="default var value"
    echo "$USAGE_VARIABLES" > envsubst
}

function show_environment() {
    echo "$USAGE_VARIABLES" > envsubst
}
```

But I'm not sure if it will be more concise. It would hopefully introduce less duplicated strings.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/734)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tools/rpma_fio_bench.sh, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/734#-MQkHcG-9xzTgOkZFck2:-MQl100T97P9Y2E-AeFZ:bow7361) ([raw file](https://github.com/pmem/rpma/blob/c8fe2789a22efdafed471d4721fb13a24a54f38f/tools/rpma_fio_bench.sh#L20)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This is part of #733. Do you have any clear guidelines on this? I can not look up anything clear stating the rules.
</blockquote></details>

OK, moved to #733

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/734)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[tools/rpma_fio_bench.sh, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/734#-MQkHcG-9xzTgOkZFck2:-MQpIsvI5vzRWMEYXz7i:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c8fe2789a22efdafed471d4721fb13a24a54f38f/tools/rpma_fio_bench.sh#L20)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK, moved to #733 
</blockquote></details>

Done.
___
*[tools/rpma_fio_bench.sh, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/734#-MQkHtnV7hyLZ4oECiCx:-MQpKJsm9ryi2j_yxk5x:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c8fe2789a22efdafed471d4721fb13a24a54f38f/tools/rpma_fio_bench.sh#L48)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> by script
> ```

by the script
</blockquote></details>

Done.
___
*[tools/rpma_fio_bench.sh, line 68 at r1](https://reviewable.io/reviews/pmem/rpma/734#-MQkILP75BVHbTqbeTij:-MQpKMhIDuYBRLs_2Set:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c8fe2789a22efdafed471d4721fb13a24a54f38f/tools/rpma_fio_bench.sh#L68)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> if [ "$#" -gt 0 -a "$1" == "--env" ]; then
> ```

`if [ "$1" == "--env" ]; then` 

is enough.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/734)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/734)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/734#-:-MQpzmWY6cXPrnv2a8tf:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/734)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/734#-MQpzw4N18JepXL7SLG6:-MQpzw4ODfDEIPMMdmqz:b-8cioiv) (no related file):*
Please rebase.

---

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/734)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/734#-:-MQq-OPADYj8xv3HVzlv:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/734)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/734#-MQpzw4N18JepXL7SLG6:-MQqU5Px2tQ24Q0wgH2C:bb7f2mf) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please rebase.
</blockquote></details>

done

---

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/734)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/734)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

**Review by janekmi — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/734)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by janekmi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/734#-:-MQqgIIv7-UaokMzJYEP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/734)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
@grom72 please rebase

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/734#-:-MQqgUNJCVsq5tJEwjxa:bgjc1nd)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/734)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/734#-MQqga0I-mGPwxnZ84Gd:-MQqga0I-mGPwxnZ84Ge:bgjc1nd) (no related file):*
@grom72 please rebase

---

**Review by grom72 — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/734#-:-MQrK1FdBr329o8Eqcp8:bb6un1j)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72, @janekmi, and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/734#-MQqga0I-mGPwxnZ84Gd:-MQrKA2dCgehEJh7QEcC:bl7eklv) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@grom72 please rebase
</blockquote></details>

I hope it is OK now.

---

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/734)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/734)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/734#-MQqga0I-mGPwxnZ84Gd:-MQrL6Io-XOfOuLr8ug9:b-896fix) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I hope it is OK now.
</blockquote></details>

Done.

---

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/734)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
