### PR TITLE
rpma: add examples for rpma_conn_wait()

### PR DESCRIPTION
**Pull request by grom72**
https://github.com/pmem/rpma/issues/1743 will be implemented later.
This PR introduces only the flag to be able to merge all-new examples
with the target API.

- [ ] #1849

This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1898)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 12 files at r2, 20 of 21 files at r4, 5 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1898)* status: all files reviewed, 8 unresolved discussions (waiting on @grom72)

___
*[`-- commits` line 37 at r5](https://reviewable.io/reviews/pmem/rpma/1898#-N5nAWYh97MNQue4V2OG):*
`rpma: add flags argument to rpma_conn_wait()`



_Code quote:_
```
rpma: additional parameter to be able extend functionality
```
___
*[`-- commits` line 40 at r5](https://reviewable.io/reviews/pmem/rpma/1898#-N5nAek7DkqLWPllnFYM):*
introduces



_Code quote:_
```
intorduce
```
___
*[`-- commits` line 40 at r5](https://reviewable.io/reviews/pmem/rpma/1898#-N5nAjgPESJURq8tuPDV):*
merge



_Code quote:_
```
mergee
```
___
*[`-- commits` line 40 at r5](https://reviewable.io/reviews/pmem/rpma/1898#-N5nCFUIEn6z7oSYzPCC):*
the flag argument



_Code quote:_
```
the flag
```
___
*[`-- commits` line 41 at r5](https://reviewable.io/reviews/pmem/rpma/1898#-N5nAnHG7UMSOD-QIKsw):*
with the new API.



_Code quote:_
```
with target API
```
___
*[`src/conn.c` line 229 at r5](https://reviewable.io/reviews/pmem/rpma/1898#-N5nBSS_8yajqg4Aasuj:-N5nBSS_8yajqg4Aasuk:b-2963qo) ([raw file](https://github.com/pmem/rpma/blob/6eaf99b398cc0312502323d4a9f50dd96c426db2/src/conn.c#L229)):*
> ```C
>  * channel from CQ or RCQ, ack it and return a CQ that caused the event
>  * in the cq argument and a boolean value saying if it is RCQ or not
>  * in the is_rcq argument (if is_rcq is not NULL)
> ```

), (a comma at the end)



_Code quote:_
```C
)
```
___
*[`src/conn.c` line 230 at r5](https://reviewable.io/reviews/pmem/rpma/1898#-N5nBCNY0Eyi6sfHqtph:-N5nBCNY0Eyi6sfHqtpi:bscu4cq) ([raw file](https://github.com/pmem/rpma/blob/6eaf99b398cc0312502323d4a9f50dd96c426db2/src/conn.c#L230)):*
> ```C
>  * in the cq argument and a boolean value saying if it is RCQ or not
>  * in the is_rcq argument (if is_rcq is not NULL)
>  * flags parameter is added to ensure backward compatibility in the future when
> ```

the flags argument



_Code quote:_
```C
flags parameter
```
___
*[`src/conn.c` line 231 at r5](https://reviewable.io/reviews/pmem/rpma/1898#-N5nB8nh6kPtkRYRTIKC:-N5nB8nh6kPtkRYRTIKD:b32wof) ([raw file](https://github.com/pmem/rpma/blob/6eaf99b398cc0312502323d4a9f50dd96c426db2/src/conn.c#L231)):*
> ```C
>  * in the is_rcq argument (if is_rcq is not NULL)
>  * flags parameter is added to ensure backward compatibility in the future when
>  * https://github.com/pmem/rpma/issues/1743 will be implemented
> ```

is



_Code quote:_
```C
will be
```

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1898)* status: 26 of 27 files reviewed, 8 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`-- commits` line 41 at r5](https://reviewable.io/reviews/pmem/rpma/1898#-N5nAnHG7UMSOD-QIKsw):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

with the new API.
</blockquote></details>

Done.
___
*[`src/conn.c` line 229 at r5](https://reviewable.io/reviews/pmem/rpma/1898#-N5nBSS_8yajqg4Aasuj:-N5nLb6T0hhJ3m87DKqR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6eaf99b398cc0312502323d4a9f50dd96c426db2/src/conn.c#L229)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

), (a comma at the end)
</blockquote></details>

Done.
___
*[`src/conn.c` line 230 at r5](https://reviewable.io/reviews/pmem/rpma/1898#-N5nBCNY0Eyi6sfHqtph:-N5nLbXEEQRTuizVx9oV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6eaf99b398cc0312502323d4a9f50dd96c426db2/src/conn.c#L230)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

the flags argument
</blockquote></details>

Done.
___
*[`src/conn.c` line 231 at r5](https://reviewable.io/reviews/pmem/rpma/1898#-N5nB8nh6kPtkRYRTIKC:-N5nLbtI3xf4CmhhRLHT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6eaf99b398cc0312502323d4a9f50dd96c426db2/src/conn.c#L231)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

is
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1898)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[`-- commits` line 40 at r5](https://reviewable.io/reviews/pmem/rpma/1898#-N5nAek7DkqLWPllnFYM):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

introduces
</blockquote></details>

fix spelling
___
*[`-- commits` line 41 at r5](https://reviewable.io/reviews/pmem/rpma/1898#-N5nAnHG7UMSOD-QIKsw):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1898#-:-N5nT3WVEsn43SjVhCXO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 12 files at r2, 20 of 21 files at r4, 4 of 5 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1898#-:-N5nqaLt8HGTYJe_nQse:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1898)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
