### PR TITLE
tools: perf: report_create.py scaffolding

### PR DESCRIPTION
**Pull request by janekmi**
Requires:

- [x] #1068 

This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1075)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 8 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1075)* status: 8 of 11 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/report_create.py, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/1075#-Mb9x9z2AxuHV5y4ZpWn:-Mb9x9z2AxuHV5y4ZpWo:b575jal) ([raw file](https://github.com/pmem/rpma/blob/1816c5b3b43114759b1c0c88736203ef0338b69b/tools/perf/report_create.py#L20)):*
> ```
> repor (
> ```

`report (`
___
*[tools/perf/lib/Bench.py, line 23 at r1](https://reviewable.io/reviews/pmem/rpma/1075#-Mb9yPMF6usZFqRjNPno:-Mb9yPMF6usZFqRjNPnp:b-plfrsr) ([raw file](https://github.com/pmem/rpma/blob/1816c5b3b43114759b1c0c88736203ef0338b69b/tools/perf/lib/Bench.py#L23)):*
> ```
> # XXX
> ```

What does `XXX` mean here? Could you elaborate?

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1075)* status: 9 of 11 files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1075)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1075)* status: 8 of 11 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/report_create.py, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/1075#-Mb9x9z2AxuHV5y4ZpWn:-MbARz4873W7cTePD7tT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1816c5b3b43114759b1c0c88736203ef0338b69b/tools/perf/report_create.py#L20)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> repor (
> ```

`report (`
</blockquote></details>

Done.
___
*[tools/perf/lib/Bench.py, line 23 at r1](https://reviewable.io/reviews/pmem/rpma/1075#-Mb9yPMF6usZFqRjNPno:-MbATTBhEn4JyiBwm6gV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1816c5b3b43114759b1c0c88736203ef0338b69b/tools/perf/lib/Bench.py#L23)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> # XXX
> ```

What does `XXX` mean here? Could you elaborate?

</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1075#-:-MbAZD3X8RDtlXS_DkYP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1075#-:-MbAhVebBkVOsvWNgi02:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1075)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
