### PR TITLE
rpma: add rpma_mr_get_ptr() and rpma_mr_get_size()

### PR DESCRIPTION
**Pull request by yangx-jy**
Ref #870

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/925)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/925)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @yangx-jy)

___
*[src/librpma.map, line 47 at r1](https://reviewable.io/reviews/pmem/rpma/925#-MW-qtp2EfcgsYXRqZjO:-MW-qtp2EfcgsYXRqZjP:b2ap5p6) ([raw file](https://github.com/pmem/rpma/blob/ecfd6bd06f81b64e64e5eb44be43474e88b2564e/src/librpma.map#L47)):*
> ```
> rpma_mr_get_mm_ptr
> ```
rpma_mr_get_ptr
___
*[src/mr.c, line 482 at r1](https://reviewable.io/reviews/pmem/rpma/925#-MW-qmPA3K64Kew-mHOJ:-MW-qmPA3K64Kew-mHOK:b-e7eaw6) ([raw file](https://github.com/pmem/rpma/blob/ecfd6bd06f81b64e64e5eb44be43474e88b2564e/src/mr.c#L482)):*
> ```
> mm_ptr
> ```
ptr
___
*[src/include/librpma.h, line 1014 at r1](https://reviewable.io/reviews/pmem/rpma/925#-MW-qNNvBntspP2OIlR6:-MW-qNNvBntspP2OIlR7:b-e7eaw6) ([raw file](https://github.com/pmem/rpma/blob/ecfd6bd06f81b64e64e5eb44be43474e88b2564e/src/include/librpma.h#L1014)):*
> ```
> mm_ptr
> ```
ptr
___
*[src/include/librpma.h, line 1016 at r1](https://reviewable.io/reviews/pmem/rpma/925#-MW-qfvH8AS31JCdY708:-MW-qfvH8AS31JCdY709:bmvajvo) ([raw file](https://github.com/pmem/rpma/blob/ecfd6bd06f81b64e64e5eb44be43474e88b2564e/src/include/librpma.h#L1016)):*
> ```
> address off
> ```
pointer to
___
*[src/include/librpma.h, line 1025 at r1](https://reviewable.io/reviews/pmem/rpma/925#-MW-prja8tMCNztMW1bA:-MW-prja8tMCNztMW1bB:b1ebnbg) ([raw file](https://github.com/pmem/rpma/blob/ecfd6bd06f81b64e64e5eb44be43474e88b2564e/src/include/librpma.h#L1025)):*
> ```
> size
> ```
ptr
___
*[src/include/librpma.h, line 1030 at r1](https://reviewable.io/reviews/pmem/rpma/925#-MW-qYiOBME4bUVOd2_s:-MW-qYiOBME4bUVOd2_t:b-e7eaw6) ([raw file](https://github.com/pmem/rpma/blob/ecfd6bd06f81b64e64e5eb44be43474e88b2564e/src/include/librpma.h#L1030)):*
> ```
> mm_ptr
> ```
ptr

**Review by yangx-jy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/925)* status: 0 of 7 files reviewed, 6 unresolved discussions (waiting on @grom72)

___
*[src/librpma.map, line 47 at r1](https://reviewable.io/reviews/pmem/rpma/925#-MW-qtp2EfcgsYXRqZjO:-MW2cUP4-WVJ5ik_-lL1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ecfd6bd06f81b64e64e5eb44be43474e88b2564e/src/librpma.map#L47)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> rpma_mr_get_mm_ptr
> ```
rpma_mr_get_ptr
</blockquote></details>

Done.
___
*[src/mr.c, line 482 at r1](https://reviewable.io/reviews/pmem/rpma/925#-MW-qmPA3K64Kew-mHOJ:-MW2cXIJ3ux4nqPKLuk1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ecfd6bd06f81b64e64e5eb44be43474e88b2564e/src/mr.c#L482)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> mm_ptr
> ```
ptr
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1014 at r1](https://reviewable.io/reviews/pmem/rpma/925#-MW-qNNvBntspP2OIlR6:-MW2cZ5iDXo6UJ7UOMgi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ecfd6bd06f81b64e64e5eb44be43474e88b2564e/src/include/librpma.h#L1014)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> mm_ptr
> ```
ptr
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1016 at r1](https://reviewable.io/reviews/pmem/rpma/925#-MW-qfvH8AS31JCdY708:-MW2c_dS85IwOMGX42Mz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ecfd6bd06f81b64e64e5eb44be43474e88b2564e/src/include/librpma.h#L1016)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> address off
> ```
pointer to
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1025 at r1](https://reviewable.io/reviews/pmem/rpma/925#-MW-prja8tMCNztMW1bA:-MW2ccvh0LUb5FZg6ioe:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ecfd6bd06f81b64e64e5eb44be43474e88b2564e/src/include/librpma.h#L1025)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> size
> ```
ptr
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1030 at r1](https://reviewable.io/reviews/pmem/rpma/925#-MW-qYiOBME4bUVOd2_s:-MW2ce833rUF5fWYKph1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ecfd6bd06f81b64e64e5eb44be43474e88b2564e/src/include/librpma.h#L1030)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> mm_ptr
> ```
ptr
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 7 files at r1, 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/925)* status: 6 of 7 files reviewed, 11 unresolved discussions (waiting on @grom72 and @yangx-jy)

___
*[examples/02-read-to-volatile/client.c, line 93 at r2](https://reviewable.io/reviews/pmem/rpma/925#-MW46PDX70J5HrPVykEi:-MW46PDYEWkhGTRVnEg7:bchwasz) ([raw file](https://github.com/pmem/rpma/blob/8be4e68b707c4324fb2273b9acb24791974a75be/examples/02-read-to-volatile/client.c#L93)):*
> ```C
> 	ret = rpma_mr_get_size(dst_mr, &get_size);
> 	if (ret || get_size != KILOBYTE)
> 		goto err_mr_dereg;
> ```

I do not like the idea. The new APIs have their application but we should not suggest to the end-users they should verify the returned values just in case.
___
*[src/include/librpma.h, line 1006 at r2](https://reviewable.io/reviews/pmem/rpma/925#-MW4A_cu2HxLeNYxHdL1:-MW4A_cu2HxLeNYxHdL2:b-1tne7x) ([raw file](https://github.com/pmem/rpma/blob/8be4e68b707c4324fb2273b9acb24791974a75be/src/include/librpma.h#L1006)):*
> ```objc
> 
> /** 3
>  * rpma_mr_get_ptr - a local registered memory address
> ```

get a memory region pointer from the local memory registration object
___
*[src/include/librpma.h, line 1016 at r2](https://reviewable.io/reviews/pmem/rpma/925#-MW4BCISBPCsMUU2m5h7:-MW4BCISBPCsMUU2m5h8:bo6qsmy) ([raw file](https://github.com/pmem/rpma/blob/8be4e68b707c4324fb2273b9acb24791974a75be/src/include/librpma.h#L1016)):*
> ```objc
>  *
>  * DESCRIPTION
>  * rpma_mr_get_ptr() gets pointer to the local registered memory.
> ```

gets a memory region pointer from the local memory registration object.
___
*[src/include/librpma.h, line 1033 at r2](https://reviewable.io/reviews/pmem/rpma/925#-MW4B_7R-9clQQISYOd9:-MW4B_7R-9clQQISYOdA:b-pyks9v) ([raw file](https://github.com/pmem/rpma/blob/8be4e68b707c4324fb2273b9acb24791974a75be/src/include/librpma.h#L1033)):*
> ```objc
> 
> /** 3
>  * rpma_mr_get_size - a local registered memory size
> ```

get a memory region size from the local memory registration object
___
*[src/include/librpma.h, line 1043 at r2](https://reviewable.io/reviews/pmem/rpma/925#-MW4BggGACsW5nhh2zqu:-MW4BggGACsW5nhh2zqv:be25bws) ([raw file](https://github.com/pmem/rpma/blob/8be4e68b707c4324fb2273b9acb24791974a75be/src/include/librpma.h#L1043)):*
> ```objc
>  *
>  * DESCRIPTION
>  * rpma_mr_get_size() gets size of the local registered memory.
> ```

gets a memory region size from the local memory registration object

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/925)* status: all files reviewed, 18 unresolved discussions (waiting on @grom72 and @yangx-jy)

___
*[tests/unit/mr/mr-local.c, line 5 at r2](https://reviewable.io/reviews/pmem/rpma/925#-MW4CJuF3Zwmo0JVf0fh:-MW4CJuF3Zwmo0JVf0fi:b2kp8kc) ([raw file](https://github.com/pmem/rpma/blob/8be4e68b707c4324fb2273b9acb24791974a75be/tests/unit/mr/mr-local.c#L5)):*
> ```C
> 
> /*
>  * mr-local.c -- the local memory region serialization unit tests
> ```

local memory registration object getters unit tests
___
*[tests/unit/mr/mr-local.c, line 24 at r2](https://reviewable.io/reviews/pmem/rpma/925#-MW4CwAf6ZAnLY76OGnj:-MW4CwAf6ZAnLY76OGnk:b-uz5cx0) ([raw file](https://github.com/pmem/rpma/blob/8be4e68b707c4324fb2273b9acb24791974a75be/tests/unit/mr/mr-local.c#L24)):*
> ```C
>  * get_size__mr_NULL - NULL mr is invalid
>  */
> static void get_size__mr_NULL(void **unused)
> ```

Please wrap the function return type as follows:

```c
static void
get_size__mr_NULL(void **unused)
```

Please apply to all other functions in this .c file.
___
*[tests/unit/mr/mr-local.c, line 98 at r2](https://reviewable.io/reviews/pmem/rpma/925#-MW4DNEW95FYYgwNxuX-:-MW4DNEXCRMKy5peyZZZ:b-2fsbsn) ([raw file](https://github.com/pmem/rpma/blob/8be4e68b707c4324fb2273b9acb24791974a75be/tests/unit/mr/mr-local.c#L98)):*
> ```C
>  * get_ptr__ptr_NULL - NULL ptr is invalid
>  */
> static void get_ptr__desc_NULL(void **pprestate)
> ```

desc -> ptr
___
*[tests/unit/mr/mr-local.c, line 113 at r2](https://reviewable.io/reviews/pmem/rpma/925#-MW4DPg77mf9iKIU39q9:-MW4DPg77mf9iKIU39qA:b-2fsbsn) ([raw file](https://github.com/pmem/rpma/blob/8be4e68b707c4324fb2273b9acb24791974a75be/tests/unit/mr/mr-local.c#L113)):*
> ```C
>  * get_ptr__mr_NULL_ptr_NULL - NULL mr and NULL ptr are invalid
>  */
> static void get_ptr__mr_NULL_desc_NULL(void **unused)
> ```

desc -> ptr
___
*[tests/unit/mr/mr-local.c, line 143 at r2](https://reviewable.io/reviews/pmem/rpma/925#-MW4DkrM9ebsBSUXywB2:-MW4DkrM9ebsBSUXywB3:bn7r110) ([raw file](https://github.com/pmem/rpma/blob/8be4e68b707c4324fb2273b9acb24791974a75be/tests/unit/mr/mr-local.c#L143)):*
> ```C
> 		IBV_ACCESS_REMOTE_READ | IBV_ACCESS_LOCAL_WRITE, NULL};
> 
> static const struct CMUnitTest tests_descriptor[] = {
> ```

tests_mr_local
___
*[tests/unit/mr/mr-local.c, line 144 at r2](https://reviewable.io/reviews/pmem/rpma/925#-MW4Dc1t6cVJXqkyr-pI:-MW4Dc1t6cVJXqkyr-pJ:b-wt0gyt) ([raw file](https://github.com/pmem/rpma/blob/8be4e68b707c4324fb2273b9acb24791974a75be/tests/unit/mr/mr-local.c#L144)):*
> ```C
> 
> static const struct CMUnitTest tests_descriptor[] = {
> 	/* rpma_mr_get_size() unit test */
> ```

test -> test**s**
___
*[tests/unit/mr/mr-local.c, line 158 at r2](https://reviewable.io/reviews/pmem/rpma/925#-MW4DfbUBP5GnO0XvKoi:-MW4DfbUBP5GnO0XvKoj:b-wt0gyt) ([raw file](https://github.com/pmem/rpma/blob/8be4e68b707c4324fb2273b9acb24791974a75be/tests/unit/mr/mr-local.c#L158)):*
> ```C
> 		&prestate),
> 
> 	/* rpma_mr_get_ptr() unit test */
> ```

test -> test**s**

**Comment by yangx-jy** [comment]
___
*[examples/02-read-to-volatile/client.c, line 93 at r2](https://reviewable.io/reviews/pmem/rpma/925#-MW46PDX70J5HrPVykEi:-MW4H5VN2iddiV3HAYT0:b-lfztkl) ([raw file](https://github.com/pmem/rpma/blob/8be4e68b707c4324fb2273b9acb24791974a75be/examples/02-read-to-volatile/client.c#L93)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I do not like the idea. The new APIs have their application but we should not suggest to the end-users they should verify the returned values just in case.
</blockquote></details>

How about removing the related code directly？In other words, make user decide how to use local mr APIs.

**Review by yangx-jy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/925)* status: 4 of 6 files reviewed, 18 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[src/include/librpma.h, line 1006 at r2](https://reviewable.io/reviews/pmem/rpma/925#-MW4A_cu2HxLeNYxHdL1:-MW4Lcyg38qRVPMyCbE6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8be4e68b707c4324fb2273b9acb24791974a75be/src/include/librpma.h#L1006)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

get a memory region pointer from the local memory registration object
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1016 at r2](https://reviewable.io/reviews/pmem/rpma/925#-MW4BCISBPCsMUU2m5h7:-MW4LNBx1mUTK_qX2bcD:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8be4e68b707c4324fb2273b9acb24791974a75be/src/include/librpma.h#L1016)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

gets a memory region pointer from the local memory registration object.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1033 at r2](https://reviewable.io/reviews/pmem/rpma/925#-MW4B_7R-9clQQISYOd9:-MW4LA_J0Q5SHUjMK98O:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8be4e68b707c4324fb2273b9acb24791974a75be/src/include/librpma.h#L1033)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

get a memory region size from the local memory registration object
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1043 at r2](https://reviewable.io/reviews/pmem/rpma/925#-MW4BggGACsW5nhh2zqu:-MW4LpBx8cxtQzf_F8R8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8be4e68b707c4324fb2273b9acb24791974a75be/src/include/librpma.h#L1043)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

gets a memory region size from the local memory registration object
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-local.c, line 5 at r2](https://reviewable.io/reviews/pmem/rpma/925#-MW4CJuF3Zwmo0JVf0fh:-MW4KQ3XDrmgiTV4_gdD:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8be4e68b707c4324fb2273b9acb24791974a75be/tests/unit/mr/mr-local.c#L5)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

local memory registration object getters unit tests
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-local.c, line 24 at r2](https://reviewable.io/reviews/pmem/rpma/925#-MW4CwAf6ZAnLY76OGnj:-MW4KnGPEQFuRWLKqFXt:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8be4e68b707c4324fb2273b9acb24791974a75be/tests/unit/mr/mr-local.c#L24)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please wrap the function return type as follows:

```c
static void
get_size__mr_NULL(void **unused)
```

Please apply to all other functions in this .c file.
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-local.c, line 98 at r2](https://reviewable.io/reviews/pmem/rpma/925#-MW4DNEW95FYYgwNxuX-:-MW4JDtk5tCHavHPq7JM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8be4e68b707c4324fb2273b9acb24791974a75be/tests/unit/mr/mr-local.c#L98)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

desc -> ptr
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-local.c, line 113 at r2](https://reviewable.io/reviews/pmem/rpma/925#-MW4DPg77mf9iKIU39q9:-MW4JDI5-_h_HB1cEwMc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8be4e68b707c4324fb2273b9acb24791974a75be/tests/unit/mr/mr-local.c#L113)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

desc -> ptr
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-local.c, line 143 at r2](https://reviewable.io/reviews/pmem/rpma/925#-MW4DkrM9ebsBSUXywB2:-MW4IzUb0EbFAWpwgFmS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8be4e68b707c4324fb2273b9acb24791974a75be/tests/unit/mr/mr-local.c#L143)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

tests_mr_local
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-local.c, line 144 at r2](https://reviewable.io/reviews/pmem/rpma/925#-MW4Dc1t6cVJXqkyr-pI:-MW4Ir1y82X7ba8zqo_8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8be4e68b707c4324fb2273b9acb24791974a75be/tests/unit/mr/mr-local.c#L144)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

test -> test**s**
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-local.c, line 158 at r2](https://reviewable.io/reviews/pmem/rpma/925#-MW4DfbUBP5GnO0XvKoi:-MW4IqaTAqDdWhlY5Bz5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8be4e68b707c4324fb2273b9acb24791974a75be/tests/unit/mr/mr-local.c#L158)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

test -> test**s**
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 3 of 6 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/925)* status: all files reviewed, 18 unresolved discussions (waiting on @grom72 and @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/925)* status: all files reviewed, 20 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)

___
*[src/include/librpma.h, line 1007 at r3](https://reviewable.io/reviews/pmem/rpma/925#-MW4jo559CNCeMkili4S:-MW4jo567sxqw-mfO99r:b-7fojt3) ([raw file](https://github.com/pmem/rpma/blob/0a8be7080df5ef82564d35cd76eff6d6d5506bb6/src/include/librpma.h#L1007)):*
> ```
>  * rpma_mr_get_ptr - get a memory region pointer from the local memory
>  * registration object
> ```

This description has to fit into one line, because only the first line will get to the generated manual - see:
`$ man build/doc/rpma_mr_get_ptr.3`
___
*[src/include/librpma.h, line 1036 at r3](https://reviewable.io/reviews/pmem/rpma/925#-MW4kGoP0a09vJq_Jjts:-MW4kGoP0a09vJq_Jjtt:b-51v6cr) ([raw file](https://github.com/pmem/rpma/blob/0a8be7080df5ef82564d35cd76eff6d6d5506bb6/src/include/librpma.h#L1036)):*
> ```
>  * rpma_mr_get_size - get a memory region size from the local memory
>  * registration object
> ```

This description has to fit into one line, because only the first line will get to the generated manual - see:
`$ man build/doc/rpma_mr_get_size.3`

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/925)* status: all files reviewed, 20 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)

___
*[src/include/librpma.h, line 1007 at r3](https://reviewable.io/reviews/pmem/rpma/925#-MW4jo559CNCeMkili4S:-MW4kt7L5YzHJ8L6UEoR:bemgqzz) ([raw file](https://github.com/pmem/rpma/blob/0a8be7080df5ef82564d35cd76eff6d6d5506bb6/src/include/librpma.h#L1007)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  * rpma_mr_get_ptr - get a memory region pointer from the local memory
>  * registration object
> ```

This description has to fit into one line, because only the first line will get to the generated manual - see:
`$ man build/doc/rpma_mr_get_ptr.3`
</blockquote></details>

... and the second one is moved to the `DESCRIPTION` section ...
___
*[src/include/librpma.h, line 1036 at r3](https://reviewable.io/reviews/pmem/rpma/925#-MW4kGoP0a09vJq_Jjts:-MW4l-698X8tmS0D09un:bemgqzz) ([raw file](https://github.com/pmem/rpma/blob/0a8be7080df5ef82564d35cd76eff6d6d5506bb6/src/include/librpma.h#L1036)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  * rpma_mr_get_size - get a memory region size from the local memory
>  * registration object
> ```

This description has to fit into one line, because only the first line will get to the generated manual - see:
`$ man build/doc/rpma_mr_get_size.3`
</blockquote></details>

... and the second one is moved to the `DESCRIPTION` section ...

**Review by yangx-jy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/925)* status: all files reviewed, 20 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[src/include/librpma.h, line 1007 at r3](https://reviewable.io/reviews/pmem/rpma/925#-MW4jo559CNCeMkili4S:-MW7K5Zk5exl3OWQyUdq:b4mm374) ([raw file](https://github.com/pmem/rpma/blob/0a8be7080df5ef82564d35cd76eff6d6d5506bb6/src/include/librpma.h#L1007)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

... and the second one is moved to the `DESCRIPTION` section ...
</blockquote></details>

Good catch.

This issue is casued by src2man command which only reads one line for the description of NAME.
I have shorten the description of NAME, as below:
rpma_mr_get_ptr - get a local memory region pointer
rpma_mr_get_size - get a local memory region size
___
*[src/include/librpma.h, line 1036 at r3](https://reviewable.io/reviews/pmem/rpma/925#-MW4kGoP0a09vJq_Jjts:-MW7Kqxs7uJsRylMesoX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0a8be7080df5ef82564d35cd76eff6d6d5506bb6/src/include/librpma.h#L1036)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

... and the second one is moved to the `DESCRIPTION` section ...
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/925)* status: all files reviewed, 19 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)

___
*[src/include/librpma.h, line 1006 at r2](https://reviewable.io/reviews/pmem/rpma/925#-MW4A_cu2HxLeNYxHdL1:-MW8l2DM867jipKgE_Di:b-7prqtc) ([raw file](https://github.com/pmem/rpma/blob/8be4e68b707c4324fb2273b9acb24791974a75be/src/include/librpma.h#L1006)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@janekmi This is too long - it does not fit into one line.

Maybe "`get the pointer to the local memory region`" ?
___
*[src/include/librpma.h, line 1033 at r2](https://reviewable.io/reviews/pmem/rpma/925#-MW4B_7R-9clQQISYOd9:-MW8m-LF7CRf8xJbeS03:bu18038) ([raw file](https://github.com/pmem/rpma/blob/8be4e68b707c4324fb2273b9acb24791974a75be/src/include/librpma.h#L1033)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@janekmi This is too long - it does not fit into one line.

Maybe "`get the size of the local memory region`" ?
___
*[src/include/librpma.h, line 1007 at r3](https://reviewable.io/reviews/pmem/rpma/925#-MW4jo559CNCeMkili4S:-MW8la4d4L0UC-CUSIRm:b-jmr7rg) ([raw file](https://github.com/pmem/rpma/blob/0a8be7080df5ef82564d35cd76eff6d6d5506bb6/src/include/librpma.h#L1007)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Good catch.

This issue is casued by src2man command which only reads one line for the description of NAME.
I have shorten the description of NAME, as below:
rpma_mr_get_ptr - get a local memory region pointer
rpma_mr_get_size - get a local memory region size
</blockquote></details>

Maybe "`get the pointer to the local memory region`" ? IMHO it is more clear.
___
*[src/include/librpma.h, line 1036 at r3](https://reviewable.io/reviews/pmem/rpma/925#-MW4kGoP0a09vJq_Jjts:-MW8m6uOEK6w-tZahGqE:boxk150) ([raw file](https://github.com/pmem/rpma/blob/0a8be7080df5ef82564d35cd76eff6d6d5506bb6/src/include/librpma.h#L1036)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Maybe "`get the size of the local memory region`" ? IMHO it is more clear.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/925)* status: all files reviewed, 9 unresolved discussions (waiting on @grom72, @ldorau, and @yangx-jy)

___
*[src/include/librpma.h, line 1033 at r2](https://reviewable.io/reviews/pmem/rpma/925#-MW4B_7R-9clQQISYOd9:-MW8pTbS07_EXLY9e1px:b-8fx2u7) ([raw file](https://github.com/pmem/rpma/blob/8be4e68b707c4324fb2273b9acb24791974a75be/src/include/librpma.h#L1033)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@janekmi This is too long - it does not fit into one line.

Maybe "`get the size of the local memory region`" ?
</blockquote></details>

:+1: 
___
*[src/include/librpma.h, line 1007 at r3](https://reviewable.io/reviews/pmem/rpma/925#-MW4jo559CNCeMkili4S:-MW8pC_43_WeuW1KLowN:b-hfuwc6) ([raw file](https://github.com/pmem/rpma/blob/0a8be7080df5ef82564d35cd76eff6d6d5506bb6/src/include/librpma.h#L1007)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Maybe "`get the pointer to the local memory region`" ? IMHO it is more clear.
</blockquote></details>

I like the @ldorau idea.

**Review by yangx-jy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/925)* status: 5 of 6 files reviewed, 9 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[src/include/librpma.h, line 1007 at r3](https://reviewable.io/reviews/pmem/rpma/925#-MW4jo559CNCeMkili4S:-MW8wLXZCgETTPm86snm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0a8be7080df5ef82564d35cd76eff6d6d5506bb6/src/include/librpma.h#L1007)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I like the @ldorau idea.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/925)* status: all files reviewed, 8 unresolved discussions (waiting on @grom72 and @janekmi)

**Review by yangx-jy — COMMENTED** [review]
Hi @janekmi 

Do you have any comment on the new PR?

Best Regards,
Xiao Yang 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/925#-:-MWcKrbW3xHT7_rjDecn:b-lq6r2z)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/925#-:-MWe_dYX2TTBOVNW-VXS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Comment by yangx-jy** [comment]
Hi @grom72 @janekmi @ldorau 

All comments have been resolved so I wonder if we can merge the PR now?

Best Regards,
Xiao Yang

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/925)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[tests/unit/mr/mr-local.c, line 117 at r5](https://reviewable.io/reviews/pmem/rpma/925#-MXBXh8fD5rNxLCFb7Wm:-MXBXh8g2SBGYcZ2jJ4v:b9za4qt) ([raw file](https://github.com/pmem/rpma/blob/3d5478855b3434b040bf2db047a6b68e134de964/tests/unit/mr/mr-local.c#L117)):*
> ```C
> 
> /*
>  * get_ptr__mr_NULL_ptr_NULL - NULL mr and NULL ptr are invalid
> ```

mr_ptr_NULL - just like get_size

**Review by yangx-jy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/925)* status: 4 of 6 files reviewed, 1 unresolved discussion (waiting on @janekmi, @ldorau, and @osalyk)

___
*[src/include/librpma.h, line 1007 at r3](https://reviewable.io/reviews/pmem/rpma/925#-MW4jo559CNCeMkili4S:-MWcLpas4wF8dnv0Y3Ys:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0a8be7080df5ef82564d35cd76eff6d6d5506bb6/src/include/librpma.h#L1007)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-local.c, line 117 at r5](https://reviewable.io/reviews/pmem/rpma/925#-MXBXh8fD5rNxLCFb7Wm:-MXBfT7A0MKr0GPQOqRc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3d5478855b3434b040bf2db047a6b68e134de964/tests/unit/mr/mr-local.c#L117)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

mr_ptr_NULL - just like get_size
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/925#-:-MXBjk9R85MidGjKhiX-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/925#-:-MXBjoLE0n8J5rYBInnT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Pull request merged**
