### PR TITLE
tools: clean up base.py

### PR DESCRIPTION
**Pull request by ldorau**
Commands will be dumped inside the runners, so in the following files:
- ib_read.py and
- fio.py

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1394)

### CODE REVIEW

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1394#-:-MqGHSxG3FQQGwGShED5:bg7igkv)* status: 0 of 1 files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1394)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1394#-MqII6kc2wdbup4ma6Fc:-MqII6kc2wdbup4ma6Fd:bmrakyb) (no related file):*
Do we have already PR for this purpose or would it be better to copy ` # XXX DUMP_CMDS?` to new locations?

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1394)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1394#-MqII6kc2wdbup4ma6Fc:-MqIs-Mn507ACnXaAj25:b-qslg2v) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Do we have already PR for this purpose or would it be better to copy ` # XXX DUMP_CMDS?` to new locations?
</blockquote></details>

A comment added.

Done.

---

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1394#-:-MqJMSeL51rhLdaPDFcZ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Pull request merged**
