### PR TITLE
common: fix README.md and INSTALL.md

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1347)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1347)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1347)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1347)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[INSTALL.md, line 15 at r1](https://reviewable.io/reviews/pmem/rpma/1347#-MpQoTGn6nOoF5O-o5lY:-MpQmzpYETZKyiWw3eLO:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/5c91aaaba1cbdaf4075e1d5bbc5a07e24972bc15/INSTALL.md#L15)):*
> ```Markdown
> - librdmacm-dev(el)
> - libcmocka-dev(el) == 1.1.5-26-g672c5ce (please see [our docker script](./utils/docker/images/install-cmocka.sh)
>     to install the verified revision)
> ```

.
___
*[INSTALL.md, line 23 at r1](https://reviewable.io/reviews/pmem/rpma/1347#-MpQoUd0AU5EtobOj6t7:-MpQoUd1-XgXXsiaESAX:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/5c91aaaba1cbdaf4075e1d5bbc5a07e24972bc15/INSTALL.md#L23)):*
> ```Markdown
> - groff
> - txt2man == 1.7.0 (please see [our docker script](./utils/docker/images/install-txt2man.sh)
>     to install the verified revision)
> ```

.
___
*[README.md, line 26 at r1](https://reviewable.io/reviews/pmem/rpma/1347#-MpQnqEP1gZyHbV_b8FV:-MpQnqEP1gZyHbV_b8FW:bdzd1sc) ([raw file](https://github.com/pmem/rpma/blob/5c91aaaba1cbdaf4075e1d5bbc5a07e24972bc15/README.md#L26)):*
> ```Markdown
> [Persistent Memory Over Traditional RDMA White Paper - Part 1](https://software.intel.com/content/www/us/en/develop/articles/persistent-memory-replication-over-traditional-rdma-part-1-understanding-remote-persistent.html) -
> which describes a technology behind RPMA. **Note:** Parts 2-4 relates directly to librpmem library
> which is a predecessor of librpma. So parts 2-4 do not relate exactly to how librpma works.
> ```

I'm just wondering... you come to us to do some fixes and you have decided to break lines at random? xD

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1347)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @lukaszstolarczuk)

___
*[README.md, line 26 at r1](https://reviewable.io/reviews/pmem/rpma/1347#-MpQnqEP1gZyHbV_b8FV:-MpQoy81C4gfvaXZQ7LH:bs45kul) ([raw file](https://github.com/pmem/rpma/blob/5c91aaaba1cbdaf4075e1d5bbc5a07e24972bc15/README.md#L26)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I'm just wondering... you come to us to do some fixes and you have decided to break lines at random? xD
</blockquote></details>

:smile_cat: I got to admit, you got me :wink:

I just looked at it and these lines seem too long. The unfortunate part is, that the very long links (like the paper link above) are hard to break properly, I guess, and it looks a bit weird.

Anyway, say a word and I'll fix it (the way you like it) or change it back :man_cartwheeling:

**Comment by lukaszstolarczuk** [comment]
> you come to us 

image

also random pic, I just instantly saw you like this 😄

**Review by janekmi — CHANGES_REQUESTED** [review]
I got the same picture in mind when I was writing to you. xD

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1347#-:-MpR1b1V5X8AoA7Oltmj:b-i0fj28)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[README.md, line 26 at r1](https://reviewable.io/reviews/pmem/rpma/1347#-MpQnqEP1gZyHbV_b8FV:-MpR1mdY0tGPY_CxYr3T:b4pokbg) ([raw file](https://github.com/pmem/rpma/blob/5c91aaaba1cbdaf4075e1d5bbc5a07e24972bc15/README.md#L26)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

:smile_cat: I got to admit, you got me :wink:

I just looked at it and these lines seem too long. The unfortunate part is, that the very long links (like the paper link above) are hard to break properly, I guess, and it looks a bit weird.

Anyway, say a word and I'll fix it (the way you like it) or change it back :man_cartwheeling: 
</blockquote></details>

Bring it back,
sing it back,
bring it back to me...

:wink:

**Review by lukaszstolarczuk — COMMENTED** [review]
:smile: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1347#-:-MpRuf0A6SigxMNhREye:b-ve3yvb)* status: 0 of 2 files reviewed, 3 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[INSTALL.md, line 15 at r1](https://reviewable.io/reviews/pmem/rpma/1347#-MpQoTGn6nOoF5O-o5lY:-MpRuhrO2xKf42ZWHhUP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5c91aaaba1cbdaf4075e1d5bbc5a07e24972bc15/INSTALL.md#L15)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[INSTALL.md, line 23 at r1](https://reviewable.io/reviews/pmem/rpma/1347#-MpQoUd0AU5EtobOj6t7:-MpRuiD0Dp2ifqoNp67h:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5c91aaaba1cbdaf4075e1d5bbc5a07e24972bc15/INSTALL.md#L23)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[README.md, line 26 at r1](https://reviewable.io/reviews/pmem/rpma/1347#-MpQnqEP1gZyHbV_b8FV:-MpRv-f_B6KXPX4_seox:bbmyzpg) ([raw file](https://github.com/pmem/rpma/blob/5c91aaaba1cbdaf4075e1d5bbc5a07e24972bc15/README.md#L26)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Bring it back,
sing it back,
bring it back to me...

:wink: 
</blockquote></details>

Savvy.

No hard feelings, but only because I like Moloko :wink:

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1347#-:-MpZ-aBbB-FneuxZpVKz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1347#-:-MpeoAk96PC4pa1MjR0T:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Pull request merged**
