### PR TITLE
common: MTT and integration tests require valgrind and RDMA connection

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #1874
- [x] #1880 
- [ ] #1881

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1876)

### CODE REVIEW

**Review by haichangsi — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1876)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`tests/CMakeLists.txt` line 54 at r1](https://reviewable.io/reviews/pmem/rpma/1876#-N5Yt6TG6PH5X8zVpNgm:-N5Yt6TG6PH5X8zVpNgn:byr0qz3) ([raw file](https://github.com/pmem/rpma/blob/88e88ce5fdfacf3350b2252601ecdd750b805484/tests/CMakeLists.txt#L54)):*
> ```CMake
> 	endif()
> 
> 	message(STATUS "NOTICE: all multi-threaded and integration tests will be disabled, "
> ```

if it matters then no coma here

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1876)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[`CMakeLists.txt` line 273 at r1](https://reviewable.io/reviews/pmem/rpma/1876#-N5YyZD_6n2DUmkrZYYB:-N5YyZD_6n2DUmkrZYYC:b-w0g6fg) ([raw file](https://github.com/pmem/rpma/blob/88e88ce5fdfacf3350b2252601ecdd750b805484/CMakeLists.txt#L273)):*
> ```CMake
> 	endif()
> 
> 	if(DEBUG_FAULT_INJECTION)
> ```

documentation says:
```cmake -DCMAKE_BUILD_TYPE=Debug -DTESTS_RDMA_CONNECTION=ON -DDEBUG_FAULT_INJECTION=ON ..```
see #1874 
Do we raly need Valgrind for integration tests?



_Code quote:_
```CMake
	if(DEBUG_FAULT_INJECTION)
		message(FATAL_ERROR "Valgrind not found, so integration tests cannot be run, "
				"but DEBUG_FAULT_INJECTION is ON. "
				"Install valgrind or set DEBUG_FAULT_INJECTION to OFF.")
	endif()
```
___
*[`tests/CMakeLists.txt` line 54 at r1](https://reviewable.io/reviews/pmem/rpma/1876#-N5YwcueCg1SCNeh6J4T:-N5YwcueCg1SCNeh6J4U:b-djxkwu) ([raw file](https://github.com/pmem/rpma/blob/88e88ce5fdfacf3350b2252601ecdd750b805484/tests/CMakeLists.txt#L54)):*
> ```CMake
> 	endif()
> 
> 	message(STATUS "NOTICE: all multi-threaded and integration tests will be disabled, "
> ```

this message will never be shown for the integration tests due to ``FATAL_ERROR`` above

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1876)* status: all files reviewed, 4 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[`CMakeLists.txt` line 263 at r3](https://reviewable.io/reviews/pmem/rpma/1876#-N5_7Xbr9tSo07e2td-5:-N5_7Xbr9tSo07e2td-6:undefined) ([raw file](https://github.com/pmem/rpma/blob/2bd4e13a5c997cbd58ad7db90e67dcbf9e0dbcc1/CMakeLists.txt#L263)):*
> ```CMake
> else()
> 	message(STATUS "NOTICE: valgrind not found! - the tests requiring valgrind "
> 			"(drd/helgrind/memcheck multi-threaded tests and integration tests) cannot be run!")
> ```





_Suggestion:_
```CMake
"(multi-threaded tests and integration tests) cannot be run!"
```
___
*[`DEVELOPMENT.md` line 96 at r3](https://reviewable.io/reviews/pmem/rpma/1876#-N5_7fRn6HPaTBuENQ2Q:-N5_7fRn6HPaTBuENQ2R:undefined) ([raw file](https://github.com/pmem/rpma/blob/2bd4e13a5c997cbd58ad7db90e67dcbf9e0dbcc1/DEVELOPMENT.md#L96)):*
> ```Markdown
> 
> In order to run the multi-threaded or the integration tests:
> 1. A correctly configured RDMA-capable network interface (SoftRoCE or RDMA HW) with an IP address assigned is required.
> ```





_Suggestion:_
```Markdown
0. Valgrind must be installed to run both the multi-threaded tests and integration tests.
1.
```
___
*[`DEVELOPMENT.md` line 128 at r3](https://reviewable.io/reviews/pmem/rpma/1876#-N5_7p-1Dt0vGfT3Isag:-N5_7p-20GdI0Ufy6pzt:blv6ulo) ([raw file](https://github.com/pmem/rpma/blob/2bd4e13a5c997cbd58ad7db90e67dcbf9e0dbcc1/DEVELOPMENT.md#L128)):*
> ```Markdown
> ```
> 
> 2. In order to run the **integration tests** build the librpma library with the `TESTS_RDMA_CONNECTION` and the `DEBUG_FAULT_INJECTION` CMake variables set to `ON`. Valgrind must be installed to run the integration tests. It is good to set also the `CMAKE_BUILD_TYPE` CMake variable to `Debug` to be able to see the debug information in case of failures:
> ```

Let's move to the common part above.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1876)* status: 3 of 7 files reviewed, 4 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[`CMakeLists.txt` line 263 at r3](https://reviewable.io/reviews/pmem/rpma/1876#-N5_7Xbr9tSo07e2td-5:-N5_G_GD5LqtsbEcjA7Y:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2bd4e13a5c997cbd58ad7db90e67dcbf9e0dbcc1/CMakeLists.txt#L263)):*
> ```CMake
> else()
> 	message(STATUS "NOTICE: valgrind not found! - the tests requiring valgrind "
> 			"(drd/helgrind/memcheck multi-threaded tests and integration tests) cannot be run!")
> ```

Done.
___
*[`DEVELOPMENT.md` line 96 at r3](https://reviewable.io/reviews/pmem/rpma/1876#-N5_7fRn6HPaTBuENQ2Q:-N5_GxKR5t3Pb9vXs8Wc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2bd4e13a5c997cbd58ad7db90e67dcbf9e0dbcc1/DEVELOPMENT.md#L96)):*
> ```Markdown
> 
> In order to run the multi-threaded or the integration tests:
> 1. A correctly configured RDMA-capable network interface (SoftRoCE or RDMA HW) with an IP address assigned is required.
> ```

Done.
___
*[`DEVELOPMENT.md` line 128 at r3](https://reviewable.io/reviews/pmem/rpma/1876#-N5_7p-1Dt0vGfT3Isag:-N5_Giqe9-8xt8-72cLt:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2bd4e13a5c997cbd58ad7db90e67dcbf9e0dbcc1/DEVELOPMENT.md#L128)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Let's move to the common part above.
</blockquote></details>

Done.

**Review by grom72 — APPROVED** [review]
> Reviewed 3 of 4 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1876)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1876#-:-N5_NSGzB1o54D2D8uTs:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

**Review by haichangsi — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1876#-:-N5_bSvu6WN3GupQMjO8:bnfp4nl)* status: 2 of 7 files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1876)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by haichangsi — COMMENTED** [review]
> Reviewed 2 of 4 files at r4, 5 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1876)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r4, 2 of 5 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1876#-:-N5dxA5S5hoYkObcZCu5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
