### PR TITLE
tools: set cpu_load_range

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1235)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1235)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/lib/Benchmark.py, line 173 at r1](https://reviewable.io/reviews/pmem/rpma/1235#-MiM_zvX5e-PKxVdZJ2M:-MiM_zvYBYc-EOgLBamJ:b-sl48ta) ([raw file](https://github.com/pmem/rpma/blob/2ab452cbb964985a45af935bd4d02fa2cef1fab0/tools/perf/lib/Benchmark.py#L173)):*
> ```Python
> 
>         if 'cpu_load_range' in self.oneseries:
>             if self.oneseries['cpu_load_range'] == '75_99':
> ```

What if `self.oneseries['cpu_load_range'] == '00_99'`?

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1235)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/Benchmark.py, line 173 at r1](https://reviewable.io/reviews/pmem/rpma/1235#-MiM_zvX5e-PKxVdZJ2M:-MiMagL23tUkAN-9xCTC:b5mckw4) ([raw file](https://github.com/pmem/rpma/blob/2ab452cbb964985a45af935bd4d02fa2cef1fab0/tools/perf/lib/Benchmark.py#L173)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

What if `self.oneseries['cpu_load_range'] == '00_99'`?
</blockquote></details>

This is the default value.

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1235)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/lib/Benchmark.py, line 173 at r1](https://reviewable.io/reviews/pmem/rpma/1235#-MiM_zvX5e-PKxVdZJ2M:-MiMb8jW7na9g_jY1e-L:b-3cwuqe) ([raw file](https://github.com/pmem/rpma/blob/2ab452cbb964985a45af935bd4d02fa2cef1fab0/tools/perf/lib/Benchmark.py#L173)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

This is the default value.
</blockquote></details>

I do not like creating such dependencies. I think it will be easier this way:

```python
if 'cpu_load_range' in self.oneseries:
    env['CPU_LOAD_RANGE'] = self.oneseries['cpu_load_range']
```

Don't you think?

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1235)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1235)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[tools/perf/lib/Benchmark.py, line 173 at r1](https://reviewable.io/reviews/pmem/rpma/1235#-MiM_zvX5e-PKxVdZJ2M:-MiQLiSe41WPieLGbXh3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2ab452cbb964985a45af935bd4d02fa2cef1fab0/tools/perf/lib/Benchmark.py#L173)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I do not like creating such dependencies. I think it will be easier this way:

```python
if 'cpu_load_range' in self.oneseries:
    env['CPU_LOAD_RANGE'] = self.oneseries['cpu_load_range']
```

Don't you think?
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1235#-:-MiQ_gwy-gyPM26TCUB4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1235#-:-MiR-Ob_C_eyeyYjo2Qm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
