### PR TITLE
tools: update BENCHMARKING.md file

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/919)

### CODE REVIEW

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/919#-:-MUxCH-j-efqbQ66ep3O:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by janekmi — CHANGES_REQUESTED** [review]
:laughing: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/919#-:-MV1PWbk5fib9EEW3twG:bc52tdo)* status: all files reviewed, 7 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/BENCHMARKING.md, line 119 at r1](https://reviewable.io/reviews/pmem/rpma/919#-MV1NKYTDnsFq_0VEJn-:-MV1NKYTDnsFq_0VEJn0:bhvcog1) ([raw file](https://github.com/pmem/rpma/blob/cb456d5162033a0c4385afd8fec5ba9df004aa03/tools/perf/BENCHMARKING.md#L119)):*
> Instead of running all separate workloads you can run a comprehensive set of workloads ~~using the following set of commands~~ and generate the RPMA performance report. **To generate a report, follow these steps:**

Please keep most of this message.
___
*[tools/perf/BENCHMARKING.md, line 121 at r1](https://reviewable.io/reviews/pmem/rpma/919#-MV1Og3D8mbTMUZHGPho:-MV1Og3D8mbTMUZHGPhp:bkkjvvk) ([raw file](https://github.com/pmem/rpma/blob/3b67cecc59cbdb7adbd9bfc5f977b464d7b3145c/tools/perf/BENCHMARKING.md#L121)):*
> ```Markdown
> ### To generate a report, follow these steps:
> 
> #### 1) Run all benchmarks required for the performance report:
> ```

One `#` less. I think.
___
*[tools/perf/BENCHMARKING.md, line 131 at r1](https://reviewable.io/reviews/pmem/rpma/919#-MV1OnRf-OPq3_BBCAQN:-MV1OnRf-OPq3_BBCAQO:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/3b67cecc59cbdb7adbd9bfc5f977b464d7b3145c/tools/perf/BENCHMARKING.md#L131)):*
> ```Markdown
> ```
> 
> #### 2) Generate Figures and Appendix charts for the performance report:
> ```

.
___
*[tools/perf/BENCHMARKING.md, line 152 at r1](https://reviewable.io/reviews/pmem/rpma/919#-MV1OrDFBwBkpvwGmvYY:-MV1OrDFBwBkpvwGmvYZ:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/3b67cecc59cbdb7adbd9bfc5f977b464d7b3145c/tools/perf/BENCHMARKING.md#L152)):*
> ```Markdown
> ```
> 
> #### 3) Prepare custom report parts (optional):
> ```

.
___
*[tools/perf/BENCHMARKING.md, line 158 at r1](https://reviewable.io/reviews/pmem/rpma/919#-MV1PJ9t1usNTRW1x455:-MV1PJ9t1usNTRW1x456:b-380rew) ([raw file](https://github.com/pmem/rpma/blob/3b67cecc59cbdb7adbd9bfc5f977b464d7b3145c/tools/perf/BENCHMARKING.md#L158)):*
> ```Markdown
> $ for f in report_xyz/*.copyme; do mv "$f" "${f/.copyme/}"; done
> # edit the report_xyz/*.md files to represent details of your configuration
> # prepare a view of the configuration high-level RPMA performance test (setup.png)
> ```

prepare a high-level view of the performance test configuration (setup.png)
___
*[tools/perf/BENCHMARKING.md, line 161 at r1](https://reviewable.io/reviews/pmem/rpma/919#-MV1Ou--7P20RZKJu5VP:-MV1Ou--7P20RZKJu5VQ:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/3b67cecc59cbdb7adbd9bfc5f977b464d7b3145c/tools/perf/BENCHMARKING.md#L161)):*
> ```Markdown
> ```
> 
> #### 4) Generate the performance report and appendices:
> ```

.
___
*[tools/perf/BENCHMARKING.md, line 136 at r2](https://reviewable.io/reviews/pmem/rpma/919#-MV1PRIY5I27K_8a78HK:-MV1PRIY5I27K_8a78HL:b-7d22d2) ([raw file](https://github.com/pmem/rpma/blob/bdef7a97761b7ce23371954e8890807494026563/tools/perf/BENCHMARKING.md#L136)):*
> ```Markdown
> $ mkdir -p results/MACHINE_A
> $ mv *.csv results/MACHINE_A
> $ export DATA_PATH=/results
> ```

~~/~~

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/919)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/BENCHMARKING.md, line 119 at r1](https://reviewable.io/reviews/pmem/rpma/919#-MV1NKYTDnsFq_0VEJn-:-MV1b5JLCW41RRTpxErT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cb456d5162033a0c4385afd8fec5ba9df004aa03/tools/perf/BENCHMARKING.md#L119)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

> Instead of running all separate workloads you can run a comprehensive set of workloads ~~using the following set of commands~~ and generate the RPMA performance report. **To generate a report, follow these steps:**

Please keep most of this message.
</blockquote></details>

Done.
___
*[tools/perf/BENCHMARKING.md, line 121 at r1](https://reviewable.io/reviews/pmem/rpma/919#-MV1Og3D8mbTMUZHGPho:-MV1bA277nl6AeTzMuwg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3b67cecc59cbdb7adbd9bfc5f977b464d7b3145c/tools/perf/BENCHMARKING.md#L121)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

One `#` less. I think.
</blockquote></details>

Done.
___
*[tools/perf/BENCHMARKING.md, line 131 at r1](https://reviewable.io/reviews/pmem/rpma/919#-MV1OnRf-OPq3_BBCAQN:-MV1bBMp-mRsPxuuaauq:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3b67cecc59cbdb7adbd9bfc5f977b464d7b3145c/tools/perf/BENCHMARKING.md#L131)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/BENCHMARKING.md, line 152 at r1](https://reviewable.io/reviews/pmem/rpma/919#-MV1OrDFBwBkpvwGmvYY:-MV1bEl8-xH1UA7x-QvO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3b67cecc59cbdb7adbd9bfc5f977b464d7b3145c/tools/perf/BENCHMARKING.md#L152)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/BENCHMARKING.md, line 158 at r1](https://reviewable.io/reviews/pmem/rpma/919#-MV1PJ9t1usNTRW1x455:-MV1bKlPAk-ka3nqbwxp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3b67cecc59cbdb7adbd9bfc5f977b464d7b3145c/tools/perf/BENCHMARKING.md#L158)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

prepare a high-level view of the performance test configuration (setup.png)
</blockquote></details>

Done.
___
*[tools/perf/BENCHMARKING.md, line 161 at r1](https://reviewable.io/reviews/pmem/rpma/919#-MV1Ou--7P20RZKJu5VP:-MV1bFnd6B3Th4PoCov_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3b67cecc59cbdb7adbd9bfc5f977b464d7b3145c/tools/perf/BENCHMARKING.md#L161)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/BENCHMARKING.md, line 136 at r2](https://reviewable.io/reviews/pmem/rpma/919#-MV1PRIY5I27K_8a78HK:-MV1bE690_6x8zr1GR4D:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bdef7a97761b7ce23371954e8890807494026563/tools/perf/BENCHMARKING.md#L136)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

~~/~~
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/919)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/BENCHMARKING.md, line 121 at r3](https://reviewable.io/reviews/pmem/rpma/919#-MV2jr2uE5D59SXN_vGx:-MV2jr2uE5D59SXN_vGy:b-z4vukt) ([raw file](https://github.com/pmem/rpma/blob/d2d1e6bae3339ed11c9447633266ca636dd96951/tools/perf/BENCHMARKING.md#L121)):*
> ```Markdown
> Instead of running all separate workloads you can run a comprehensive set of workloads and generate the RPMA performance report.
> 
> ### To generate a report, follow these steps:
> ```

This should not be a header. Please add it to the preceding paragraph.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/919#-:-MVGpULa2EMx0ldDNMb-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
