### PR TITLE
tools: retry to connect the client of ib tool

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #1404 

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1406)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1406)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1406#-MqSftoj4e-aWJzxC2Rh:-MqSftoj4e-aWJzxC2Ri:b-3igxye) (no related file):*
Shall we add short sleep in __server_start to avoid this problem?
Later we could monitor __server_start RemoteCmd output to search for ib_read_XXX output:
```
************************************
* Waiting for client to connect... *
************************************
```

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1406)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1406#-MqSftoj4e-aWJzxC2Rh:-MqTHaVP8aIGS0CCAUu2:b-z7tf56) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Shall we add short sleep in __server_start to avoid this problem?
Later we could monitor __server_start RemoteCmd output to search for ib_read_XXX output:
```
************************************
* Waiting for client to connect... *
************************************
```



</blockquote></details>

1) There is already a short sleep before retrying:
```
 time.sleep(0.1) # wait 0.1 sec for server to start
```

2) I will try to parse server's output for this message, but I think that retrying to connect the client is more practical - what do you think?

---

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1406)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1406#-MqSftoj4e-aWJzxC2Rh:-MqTR_fi53fJZmpGB6ka:b-twxc11) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

1) There is already a short sleep before retrying:
```
 time.sleep(0.1) # wait 0.1 sec for server to start
```

2) I will try to parse server's output for this message, but I think that retrying to connect the client is more practical - what do you think?
</blockquote></details>

If we assume silent retrying, then it is OK, but otherwise it will be annoying to see RETRY message almost every time the benchmark is run

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1406)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1406#-MqSftoj4e-aWJzxC2Rh:-MqTUk534CIO2VvYVhNJ:b32w0x) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

If we assume silent retrying, then it is OK, but otherwise it will be annoying to see RETRY message almost every time the benchmark is run
</blockquote></details>

OK

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1406)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1406#-MqTa5yP0MTeZJBqj7WS:-MqTa5yP0MTeZJBqj7WT:bqeplii) (no related file):*
@osalyk please review

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1406)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1406#-MqSftoj4e-aWJzxC2Rh:-MqTt4n82AJ89aZPDZRg:bgllyyj) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK
</blockquote></details>

@grom72  Unfortunately this:
*"Later we could monitor __server_start RemoteCmd output to search for ib_read_XXX output:"*
does not work on CentOS 8 for unknown reason :-(
See: https://github.com/ldorau/rpma/commit/dc48aa72c43d06af16e23173b129ffa0f9c22667
and the output is following:
```
STARTING benchmark for MODE=lat TOOL=ib_read IP=192.168.101.4 ...
[size: 256, threads: 1, tx_depth: 1, iters: 27678723] (duration: ~60s)
__wait_till_server_listens...
```
and the client hangs on waiting for output from the server and receives nothing...
(It works correctly on Arch Linux)

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1406)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1406#-MqSftoj4e-aWJzxC2Rh:-MqTuExW0EERvxE1cmeg:b-adbolu) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@grom72  Unfortunately this:
*"Later we could monitor __server_start RemoteCmd output to search for ib_read_XXX output:"*
does not work on CentOS 8 for unknown reason :-(
See: https://github.com/ldorau/rpma/commit/dc48aa72c43d06af16e23173b129ffa0f9c22667
and the output is following:
```
STARTING benchmark for MODE=lat TOOL=ib_read IP=192.168.101.4 ...
[size: 256, threads: 1, tx_depth: 1, iters: 27678723] (duration: ~60s)
__wait_till_server_listens...
```
and the client hangs on waiting for output from the server and receives nothing...
(It works correctly on Arch Linux)

</blockquote></details>

... so the only thing I can do more is to add a short sleep in __server_start ...

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1406)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1406#-MqSftoj4e-aWJzxC2Rh:-MqTwji_7SgvZQsny6BB:b95ss0t) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

... so the only thing I can do more is to add a short sleep in __server_start ...
</blockquote></details>

Added a short sleep.

@grom72 Done

---

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1406#-:-MqU6UQB7ZOdXm1gPelg:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1406#-MqSftoj4e-aWJzxC2Rh:-MqU6Prr13tcLazBitrr:bo4jnfr) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Added a short sleep.

@grom72 Done
</blockquote></details>

We will come back to this later 
:lgtm:

---

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1406)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1406#-:-MqUBfb60r3awMw98JQp:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Pull request merged**
