### PR TITLE
tools: control xscale

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1133)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1133)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/lib/Figure.py, line 163 at r1](https://reviewable.io/reviews/pmem/rpma/1133#-MdvKRwOAk_P6Si_jGnI:-MdvKRwOAk_P6Si_jGnJ:bl8wdt7) ([raw file](https://github.com/pmem/rpma/blob/aff6e9d5b43bdc72ac5527a54934fb74ec22dbee/tools/perf/lib/Figure.py#L163)):*
> ```
> # XXX linear / log
> ```

please update the comment

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1133)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/lib/Figure.py, line 163 at r1](https://reviewable.io/reviews/pmem/rpma/1133#-MdvKRwOAk_P6Si_jGnI:-MdvPMur-KksNzu2T9eu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/aff6e9d5b43bdc72ac5527a54934fb74ec22dbee/tools/perf/lib/Figure.py#L163)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> # XXX linear / log
> ```

please update the comment
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1133)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1133#-:-MdvPf6oETq_zPUhrCC4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1133)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/lib/Figure.py, line 40 at r2](https://reviewable.io/reviews/pmem/rpma/1133#-MdvcwWBEk9jsQXLPNVa:-MdvcwWBEk9jsQXLPNVb:b-fu664q) ([raw file](https://github.com/pmem/rpma/blob/76cf2c3e1ecc6e35a920b0568119411496643015/tools/perf/lib/Figure.py#L40)):*
> ```Python
>             self.xscale = self.output['xscale']
>         except KeyError:
>             self.xscale = 'log'
> ```

```python
self.xscale = self.output.get('xscale', 'log')
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1133)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[tools/perf/lib/Figure.py, line 40 at r2](https://reviewable.io/reviews/pmem/rpma/1133#-MdvcwWBEk9jsQXLPNVa:-MdviGBW3a4Hw_lndLIX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/76cf2c3e1ecc6e35a920b0568119411496643015/tools/perf/lib/Figure.py#L40)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```python
self.xscale = self.output.get('xscale', 'log')
```
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1133)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1133#-:-MdvzHF1-2KD7dZHMTZP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
