### PR TITLE
examples: replace rpma_write_atomic() with rpma_atomic_write()

### PR DESCRIPTION
**Pull request by osalyk**
- [x] #1595 #1601

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1607)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1607)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1607)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @ldorau and @osalyk)

___
*[CHANGELOG.md, line 13 at r4](https://reviewable.io/reviews/pmem/rpma/1607#-MxYiAMTDePqf6An1Ec8:-MxYiAMTDePqf6An1Ec9:bhrhmlu) ([raw file](https://github.com/pmem/rpma/blob/56f9b087aac200336710aaf978940b3172da7074/CHANGELOG.md#L13)):*
> ```Markdown
>   - rpma_atomic_write - initiates the atomic 8 bytes write operation
> 
> ### Fixed
> ```

```
### Changed
- example 07 uses rpma_atomic_write() instead of rpma_write_atomic()

### Fixed
```



_Code quote:_
```Markdown
### Fixed
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1607)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[-- commits, line 5 at r4](https://reviewable.io/reviews/pmem/rpma/1607#-MxYiiAtCf3--UWMQ5cM):*
`examples: replace rpma_write_atomic() with rpma_atomic_write()`



_Code quote:_
```
examples: change rpma_write_atomic() to rpma_atomic_write()
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1607)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[-- commits, line 5 at r4](https://reviewable.io/reviews/pmem/rpma/1607#-MxYiiAtCf3--UWMQ5cM):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`examples: replace rpma_write_atomic() with rpma_atomic_write()`
</blockquote></details>

Done.
___
*[CHANGELOG.md, line 13 at r4](https://reviewable.io/reviews/pmem/rpma/1607#-MxYiAMTDePqf6An1Ec8:-MxYnm6B-jfvIryLGsD1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/56f9b087aac200336710aaf978940b3172da7074/CHANGELOG.md#L13)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
### Changed
- example 07 uses rpma_atomic_write() instead of rpma_write_atomic()

### Fixed
```
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1607)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[examples/07-atomic-write/client.c, line 48 at r2](https://reviewable.io/reviews/pmem/rpma/1607#-MxZ0PLdAgsIUr61iQMx:-MxZQT0m0hr4gAZd4DcV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e7dfa7f665e42b99569f6004db0b1527e0cac5b8/examples/07-atomic-write/client.c#L48)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It would be much simpler to define it as a union:
```c
	union {
		uint64_t uint64;
		char buf[sizeof(uint64_t)];
	} used;
```
and use `used.uint64` when you need a number or `used.buf` when you need an array and `sizeof(used)` when you need the size.
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 133 at r2](https://reviewable.io/reviews/pmem/rpma/1607#-MxYjmfwDc2zwm1PDnkJ:-MxZQTW_9yvNwJSh2dbq:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e7dfa7f665e42b99569f6004db0b1527e0cac5b8/examples/07-atomic-write/client.c#L133)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please use `memcpy` instead.
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1607)* status: all files reviewed, 6 unresolved discussions (waiting on @osalyk)

___
*[examples/07-atomic-write/client.c, line 25 at r6](https://reviewable.io/reviews/pmem/rpma/1607#-MxZcKHV075fpRLPH4rc:-MxZcKHV075fpRLPH4rd:b-eb24w2) ([raw file](https://github.com/pmem/rpma/blob/13bccd91c966638440038eaeb5fdbc63bd2d213d/examples/07-atomic-write/client.c#L25)):*
> ```C
> #define LOCAL_DATA_OFFSET	offsetof(struct mr_ptr_s, data)
> #define LOCAL_DATA_SIZE		(KILOBYTE - sizeof(uint64_t))
> #define MAX_WORD_LENGTH		(LOCAL_DATA_SIZE - 1)
> ```

```c
#define MAX_WORD_LENGTH		(KILOBYTE - 1)
```



_Code quote:_
```C
#define MAX_WORD_LENGTH		(LOCAL_DATA_SIZE - 1)
```
___
*[examples/07-atomic-write/client.c, line 49 at r6](https://reviewable.io/reviews/pmem/rpma/1607#-MxZbRm5ClQJ6PEKpCqj:-MxZbRm5ClQJ6PEKpCqk:b-6be4fh) ([raw file](https://github.com/pmem/rpma/blob/8c6084be012df5cc2ef8016d16e51b57f3db9ffa/examples/07-atomic-write/client.c#L49)):*
> ```C
> 	struct ibv_wc wc;
> 	union {
> 		uint64_t uint64_t;
> ```

```c
uint64_t uint64;
```

(`uint64_t` is a name of type)



_Code quote:_
```C
uint64_t
```
___
*[examples/07-atomic-write/client.c, line 135 at r6](https://reviewable.io/reviews/pmem/rpma/1607#-MxZb1OB64zOh9ste_z9:-MxZb1OB64zOh9ste_zA:b-2zikxa) ([raw file](https://github.com/pmem/rpma/blob/8c6084be012df5cc2ef8016d16e51b57f3db9ffa/examples/07-atomic-write/client.c#L135)):*
> ```C
> 	}
> 
> 	memcpy(used.buf, (char *)mr_ptr, sizeof(used));
> ```

Why `(char *)`?
```c
memcpy(&used, mr_ptr, sizeof(used));
```



_Code quote:_
```C
(char *)
```
___
*[examples/07-atomic-write/client.c, line 136 at r6](https://reviewable.io/reviews/pmem/rpma/1607#-MxZamVj3v6ZGpBrKUcO:-MxZamVj3v6ZGpBrKUcP:b2ngqix) ([raw file](https://github.com/pmem/rpma/blob/8c6084be012df5cc2ef8016d16e51b57f3db9ffa/examples/07-atomic-write/client.c#L136)):*
> ```C
> 
> 	memcpy(used.buf, (char *)mr_ptr, sizeof(used));
> 	printf("used value: %ld\n", used.uint64_t);
> ```

%lu



_Code quote:_
```C
%ld
```
___
*[examples/07-atomic-write/client.c, line 158 at r6](https://reviewable.io/reviews/pmem/rpma/1607#-MxZcid096JwiJXURYc7:-MxZcid096JwiJXURYc8:b-y13i3f) ([raw file](https://github.com/pmem/rpma/blob/8c6084be012df5cc2ef8016d16e51b57f3db9ffa/examples/07-atomic-write/client.c#L158)):*
> ```C
> 	for (int i = 3; i < argc; ++i) {
> 		char *word = mr_ptr;
> 		strcpy(word, argv[i]);
> ```

It should stay, as is:
```c
		strncpy(word, argv[i], MAX_WORD_LENGTH);
		/* make sure the word is always null-terminated */
		word[MAX_WORD_LENGTH] = 0;
```



_Code quote:_
```C
		strcpy(word, argv[i]);
```
___
*[examples/07-atomic-write/client.c, line 171 at r6](https://reviewable.io/reviews/pmem/rpma/1607#-MxZbLe4DylI_eRId81c:-MxZbLe4DylI_eRId81d:bckx716) ([raw file](https://github.com/pmem/rpma/blob/8c6084be012df5cc2ef8016d16e51b57f3db9ffa/examples/07-atomic-write/client.c#L171)):*
> ```C
> 			break;
> 
> 		used.uint64_t += (uint64_t)word_size;
> ```

```c
used.uint64 += word_size;
```



_Code quote:_
```C
used.uint64_t += (uint64_t)word_size;
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1607)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @ldorau)

___
*[examples/07-atomic-write/client.c, line 25 at r6](https://reviewable.io/reviews/pmem/rpma/1607#-MxZcKHV075fpRLPH4rc:-MxZfS7834wy7hy1KlW3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/13bccd91c966638440038eaeb5fdbc63bd2d213d/examples/07-atomic-write/client.c#L25)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```c
#define MAX_WORD_LENGTH		(KILOBYTE - 1)
```

</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 49 at r6](https://reviewable.io/reviews/pmem/rpma/1607#-MxZbRm5ClQJ6PEKpCqj:-MxZfhKXB1w9-pqgQs5t:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8c6084be012df5cc2ef8016d16e51b57f3db9ffa/examples/07-atomic-write/client.c#L49)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```c
uint64_t uint64;
```

(`uint64_t` is a name of type)
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 135 at r6](https://reviewable.io/reviews/pmem/rpma/1607#-MxZb1OB64zOh9ste_z9:-MxZfpfH0TzbGnw7T4d8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8c6084be012df5cc2ef8016d16e51b57f3db9ffa/examples/07-atomic-write/client.c#L135)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why `(char *)`?
```c
memcpy(&used, mr_ptr, sizeof(used));
```
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 136 at r6](https://reviewable.io/reviews/pmem/rpma/1607#-MxZamVj3v6ZGpBrKUcO:-MxZfsMa02g_9gdBA6Dn:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8c6084be012df5cc2ef8016d16e51b57f3db9ffa/examples/07-atomic-write/client.c#L136)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

%lu
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 158 at r6](https://reviewable.io/reviews/pmem/rpma/1607#-MxZcid096JwiJXURYc7:-MxZg2-M0nWuQ7YSPe92:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8c6084be012df5cc2ef8016d16e51b57f3db9ffa/examples/07-atomic-write/client.c#L158)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It should stay, as is:
```c
		strncpy(word, argv[i], MAX_WORD_LENGTH);
		/* make sure the word is always null-terminated */
		word[MAX_WORD_LENGTH] = 0;
```

</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 171 at r6](https://reviewable.io/reviews/pmem/rpma/1607#-MxZbLe4DylI_eRId81c:-MxZgGq60vjlGK_dIccu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8c6084be012df5cc2ef8016d16e51b57f3db9ffa/examples/07-atomic-write/client.c#L171)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```c
used.uint64 += word_size;
```

</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1607)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[examples/07-atomic-write/client.c, line 135 at r6](https://reviewable.io/reviews/pmem/rpma/1607#-MxZb1OB64zOh9ste_z9:-MxZjE7o5u0tSh2qO7OV:b-p2afgy) ([raw file](https://github.com/pmem/rpma/blob/8c6084be012df5cc2ef8016d16e51b57f3db9ffa/examples/07-atomic-write/client.c#L135)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

```c
memcpy(&used, ...
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1607)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1607#-MxZjYj65ftc6DAhiBGZ:-MxZjYj71_eyK8dSXwNf:b-f08ulq) (no related file):*
Please rebase onto the current #1595

---

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1607)* status: 2 of 7 files reviewed, 2 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1607#-MxZjYj65ftc6DAhiBGZ:-MxZnAbF3EaG4-R6Yuex:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please rebase onto the current #1595
</blockquote></details>

Done.

---
___
*[examples/07-atomic-write/client.c, line 135 at r6](https://reviewable.io/reviews/pmem/rpma/1607#-MxZb1OB64zOh9ste_z9:-MxZnA2-3UArdGgsOrLq:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8c6084be012df5cc2ef8016d16e51b57f3db9ffa/examples/07-atomic-write/client.c#L135)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```c
memcpy(&used, ...
```

</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 3 of 5 files at r8, 2 of 2 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1607)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1607)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1607#-MxZjYj65ftc6DAhiBGZ:-MxZpDol-lcisGD5zXqx:b-unluc2) (no related file):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The CircleCI build passed :-)

---

**Review by ldorau — APPROVED** [review]
> Reviewed 6 of 6 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1607)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 2 files at r9, 1 of 6 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1607)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1607#-:-MxdV7RE9RMallPt_dx0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1607)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[examples/07-atomic-write/client.c, line 50 at r10](https://reviewable.io/reviews/pmem/rpma/1607#-MxdeVOU5MkgpCdNZmsB:-MxdeVOU5MkgpCdNZmsC:b-4hekvd) ([raw file](https://github.com/pmem/rpma/blob/a0d4bee131156efb8dd56dbe12e5ff0d6288b3d5/examples/07-atomic-write/client.c#L50)):*
> ```C
> 	struct ibv_wc wc;
> 	union {
> 		uint64_t uint64;
> ```

@ldorau shall we ensure that ```used ``` buffer is at least 8 char long?
```	union {
		uint64_t uint64;
		char buf[sizeof(uint64_t)];
		char dummy[8];
	} used;
```



_Code quote:_
```C
	union {
		uint64_t uint64;
		char buf[sizeof(uint64_t)];
	} used;
```

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1607)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[examples/07-atomic-write/client.c, line 50 at r10](https://reviewable.io/reviews/pmem/rpma/1607#-MxdeVOU5MkgpCdNZmsB:-MxdfGtPB6Fxm2hKZ9qp:b-l1r6ce) ([raw file](https://github.com/pmem/rpma/blob/a0d4bee131156efb8dd56dbe12e5ff0d6288b3d5/examples/07-atomic-write/client.c#L50)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

@ldorau shall we ensure that ```used ``` buffer is at least 8 char long?
```	union {
		uint64_t uint64;
		char buf[sizeof(uint64_t)];
		char dummy[8];
	} used;
```
</blockquote></details>


	union {
		uint64_t uint64;
		char buf[8];
	} used;

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1607)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[examples/07-atomic-write/client.c, line 50 at r10](https://reviewable.io/reviews/pmem/rpma/1607#-MxdeVOU5MkgpCdNZmsB:-MxdhhP-EaIH9uifVuEI:b-v4v5v1) ([raw file](https://github.com/pmem/rpma/blob/a0d4bee131156efb8dd56dbe12e5ff0d6288b3d5/examples/07-atomic-write/client.c#L50)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>


	union {
		uint64_t uint64;
		char buf[8];
	} used;
</blockquote></details>

```c
union {
	uint64_t uint64;
	char buf[8]; /* atomic write requires exactly 8-bytes buffer */
} used;
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1607)* status: 5 of 7 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[examples/07-atomic-write/client.c, line 50 at r10](https://reviewable.io/reviews/pmem/rpma/1607#-MxdeVOU5MkgpCdNZmsB:-Mxdjks677_lvuYDiHBW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a0d4bee131156efb8dd56dbe12e5ff0d6288b3d5/examples/07-atomic-write/client.c#L50)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```c
union {
	uint64_t uint64;
	char buf[8]; /* atomic write requires exactly 8-bytes buffer */
} used;
```
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1607)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
:goat:

> Reviewed 2 of 2 files at r11, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1607#-:-MxdhaSP8AKiEeWo-yLB:bnd2vnu)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1607#-:-MxdkTyY2Z564iuwhT4W:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1607)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
