### PR TITLE
test: add rpma_conn_cfg_set_sq_size multithreaded test

### PR DESCRIPTION
**Pull request by ewanglong**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1098)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1098)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

___
*[tests/multithreaded/conn/rpma_conn_cfg_set_sq_size.c, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1098#-Mcxe9KfDYedTml7v6-P:-Mcxe9KfDYedTml7v6-Q:b3nsx2h) ([raw file](https://github.com/pmem/rpma/blob/53379f9e5007b3aec1af646a6a2b1fed1a39ed60/tests/multithreaded/conn/rpma_conn_cfg_set_sq_size.c#L13)):*
> ```
> Q_SIZE_EXP
> ```

Please rename it to` Q_SIZE_EXPECTED` because `EXP` is ambiguous.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1098)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

___
*[tests/multithreaded/conn/rpma_conn_cfg_set_sq_size.c, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1098#-Mcxe9KfDYedTml7v6-P:-Mcxfcgr-Rp09fmZo7Sw:b-ad4r11) ([raw file](https://github.com/pmem/rpma/blob/53379f9e5007b3aec1af646a6a2b1fed1a39ed60/tests/multithreaded/conn/rpma_conn_cfg_set_sq_size.c#L13)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> Q_SIZE_EXP
> ```

Please rename it to` Q_SIZE_EXPECTED` because `EXP` is ambiguous.
</blockquote></details>

A comment is enough here.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1098)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[tests/multithreaded/conn/rpma_conn_cfg_set_sq_size.c, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1098#-Mcxe9KfDYedTml7v6-P:-McxfFO--ym0oFvGUWrm:bxwr8e9) ([raw file](https://github.com/pmem/rpma/blob/53379f9e5007b3aec1af646a6a2b1fed1a39ed60/tests/multithreaded/conn/rpma_conn_cfg_set_sq_size.c#L13)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> Q_SIZE_EXP
> ```

Please rename it to` Q_SIZE_EXPECTED` because `EXP` is ambiguous.
</blockquote></details>

This also looks common. Please put it inside `rpma_conn_cfg_common.h` named as e.g. RPMA_CONN_CFG_Q_SIZE_EXP/_EXPECTED.
The exact suffix is discussed in #1097.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1098)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tests/multithreaded/conn/rpma_conn_cfg_set_sq_size.c, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1098#-Mcxe9KfDYedTml7v6-P:-Mcxgrd5-hS04-uyQFrB:b32v57) ([raw file](https://github.com/pmem/rpma/blob/53379f9e5007b3aec1af646a6a2b1fed1a39ed60/tests/multithreaded/conn/rpma_conn_cfg_set_sq_size.c#L13)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This also looks common. Please put it inside `rpma_conn_cfg_common.h` named as e.g. RPMA_CONN_CFG_Q_SIZE_EXP/_EXPECTED.
The exact suffix is discussed in #1097.
</blockquote></details>

+1

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1098)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[tests/multithreaded/conn/rpma_conn_cfg_set_sq_size.c, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1098#-Mcxe9KfDYedTml7v6-P:-MdKXuVv7jLHMRqZZ6fv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/53379f9e5007b3aec1af646a6a2b1fed1a39ed60/tests/multithreaded/conn/rpma_conn_cfg_set_sq_size.c#L13)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1098)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/multithreaded/conn/rpma_conn_cfg_set_cq_size.c, line 39 at r2](https://reviewable.io/reviews/pmem/rpma/1098#-MdLq1n80c_GJcRWvwth:-MdLq1n93yX3if0pJPON:b-b5u9lz) ([raw file](https://github.com/pmem/rpma/blob/213d3cb88d09e0041d5d024fad058736f460fa7f/tests/multithreaded/conn/rpma_conn_cfg_set_cq_size.c#L39)):*
> ```
> 		MTT_ERR(tr, "cq_size != RPMA_CONN_CFG_COMMON_Q_SIZE_EXP",
> 				EINVAL);
> ```

This change should be submitted in a separate PR.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1098)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tests/multithreaded/conn/rpma_conn_cfg_set_cq_size.c, line 39 at r2](https://reviewable.io/reviews/pmem/rpma/1098#-MdLq1n80c_GJcRWvwth:-MdNlsD7-wx_rj7teCQo:br0gdpm) ([raw file](https://github.com/pmem/rpma/blob/213d3cb88d09e0041d5d024fad058736f460fa7f/tests/multithreaded/conn/rpma_conn_cfg_set_cq_size.c#L39)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 		MTT_ERR(tr, "cq_size != RPMA_CONN_CFG_COMMON_Q_SIZE_EXP",
> 				EINVAL);
> ```

This change should be submitted in a separate PR.
</blockquote></details>

Sad but true. Please comply.

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1098)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[tests/multithreaded/conn/rpma_conn_cfg_set_cq_size.c, line 39 at r2](https://reviewable.io/reviews/pmem/rpma/1098#-MdLq1n80c_GJcRWvwth:-MdPcjuO1DhIWQo_vDcV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/213d3cb88d09e0041d5d024fad058736f460fa7f/tests/multithreaded/conn/rpma_conn_cfg_set_cq_size.c#L39)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Sad but true. Please comply.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1098)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1098)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1098#-MdQNh-X5Wz9GxeQIKwi:-MdQNh-X5Wz9GxeQIKwj:b-n6khor) (no related file):*
Please rebase

---

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1098)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1098#-MdQNh-X5Wz9GxeQIKwi:-MdQXsZfEj1M_JbKwvKh:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please rebase
</blockquote></details>

Done.

---

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1098)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1098#-:-MdQpGQp3gyHDB8E9guG:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1098#-:-MdRVMaB38V4-c8HoxPo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Pull request merged**
