### PR TITLE
tools: copy file to a remote node

### PR DESCRIPTION
**Pull request by osalyk**
- [x] #1339 
- [x] #1348

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1350)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1350)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1350)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1350)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/lib/remote_cmd.py, line 29 at r2](https://reviewable.io/reviews/pmem/rpma/1350#-MpQQiia--SXLooR40SL:-MpQQiia--SXLooR40SM:b-jrcxiz) ([raw file](https://github.com/pmem/rpma/blob/a1c15758417d8d6febdadc6ab2a37d6f289b0fab/tools/perf/lib/remote_cmd.py#L29)):*
> ```Python
>     @classmethod
>     def __connect_to_host(cls, config):
>         """connct to remote host"""
> ```

connect
___
*[tools/perf/lib/remote_cmd.py, line 46 at r2](https://reviewable.io/reviews/pmem/rpma/1350#-MpQRenX6m8V6Sl28ODv:-MpQRenX6m8V6Sl28ODw:bvvw5vy) ([raw file](https://github.com/pmem/rpma/blob/a1c15758417d8d6febdadc6ab2a37d6f289b0fab/tools/perf/lib/remote_cmd.py#L46)):*
> ```Python
> 
>         scp = SCPClient(ssh_client.get_transport())
>         scp.put(local_dir, remote_dir)
> ```

If `local_dir` is really a directory the documentation states `recursive=True` has to be set. Otherwise, please name it in a way it will resemble a file or list of files e.g. `files`. xD

Ref: https://github.com/jbardin/scp.py/blob/master/scp.py#L151

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1350)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tools/perf/lib/remote_cmd.py, line 46 at r2](https://reviewable.io/reviews/pmem/rpma/1350#-MpQRenX6m8V6Sl28ODv:-MpQTLeEDHUkVusDmDk2:bt0k905) ([raw file](https://github.com/pmem/rpma/blob/a1c15758417d8d6febdadc6ab2a37d6f289b0fab/tools/perf/lib/remote_cmd.py#L46)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

If `local_dir` is really a directory the documentation states `recursive=True` has to be set. Otherwise, please name it in a way it will resemble a file or list of files e.g. `files`. xD

Ref: https://github.com/jbardin/scp.py/blob/master/scp.py#L151
</blockquote></details>

I think it should be one `file`.

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1350)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[tools/perf/lib/remote_cmd.py, line 46 at r2](https://reviewable.io/reviews/pmem/rpma/1350#-MpQRenX6m8V6Sl28ODv:-MpQWDQa8zqAoYap6iEV:b-aznpl5) ([raw file](https://github.com/pmem/rpma/blob/a1c15758417d8d6febdadc6ab2a37d6f289b0fab/tools/perf/lib/remote_cmd.py#L46)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I think it should be one `file`.
</blockquote></details>

The `scp.put()` interface call it files. We do nothing other than just pass this argument to the scp.
Don't see a reason to limit its semantics. :thinking:

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1350)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tools/perf/lib/remote_cmd.py, line 46 at r2](https://reviewable.io/reviews/pmem/rpma/1350#-MpQRenX6m8V6Sl28ODv:-MpQa9m85OAc-rfn1FJY:b-9h3vh8) ([raw file](https://github.com/pmem/rpma/blob/a1c15758417d8d6febdadc6ab2a37d6f289b0fab/tools/perf/lib/remote_cmd.py#L46)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The `scp.put()` interface call it files. We do nothing other than just pass this argument to the scp.
Don't see a reason to limit its semantics. :thinking: 
</blockquote></details>

OK, let's use the same (`files`)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1350)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/lib/remote_cmd.py, line 29 at r2](https://reviewable.io/reviews/pmem/rpma/1350#-MpQQiia--SXLooR40SL:-MpQd5YC2_hUGLmPhYSP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a1c15758417d8d6febdadc6ab2a37d6f289b0fab/tools/perf/lib/remote_cmd.py#L29)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

connect
</blockquote></details>

Done.
___
*[tools/perf/lib/remote_cmd.py, line 46 at r2](https://reviewable.io/reviews/pmem/rpma/1350#-MpQRenX6m8V6Sl28ODv:-MpQdQm-7Id9vEtMuu4c:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a1c15758417d8d6febdadc6ab2a37d6f289b0fab/tools/perf/lib/remote_cmd.py#L46)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK, let's use the same (`files`)
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1350)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1350#-:-MpQleGR7VqZxcaXhgN4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1350#-:-MpQlloJ5Qz6pGyVnOJQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
