### PR TITLE
[WIP] tools: results handling moved to Runner class

### PR DESCRIPTION
**Pull request by grom72**
More common functionality is moving from common.py and from fio.py and ib_read.py to Runner class.
- [x] #1461
- [ ] #1452 
- [x] #1453
- [ ] #1454 
- [ ] #1455

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1456)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1456)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by Patryk717 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1456#-:-Ms-z179CV5dRG8pMPfD:bdycpsm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1456)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1456)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1456)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1456)* status: 1 of 13 files reviewed, all discussions resolved (waiting on @grom72 and @ldorau)

**Pull request closed without merging**
