### PR TITLE
common: remove the TESTS_USE_VALGRIND option

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #1874

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1880)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1880)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1880#-N5ZohODDDBqi0cq2Hui:-N5ZohODDDBqi0cq2Huj:b-kftovu) (no related file):*
is it OK to add these flags whenever Valgrind is detected?



_Code quote (from CMakeLists.txt):_
```CMake
	add_flag(-DVG_MEMCHECK_ENABLED=1)
	add_flag(-DVG_DRD_ENABLED=1)
	add_flag(-DVG_HELGRIND_ENABLED=1)
```

___

**Review by grom72 — APPROVED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1880)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1880#-:-N5_678c1S3zonL1DRP4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1880#-:-N5_M1Fo6FNDNcusXnrB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
