### PR TITLE
common: add missing cases to rpma_err_2str() + replace RPMA_E_NO_NEXT with RPMA_E_NO_EVENT

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/465)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/465)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[src/rpma_err.c, line 50 at r1](https://reviewable.io/reviews/pmem/rpma/465#-MIJMiFfCL3UQTxd9_5e:-MIJMiFfCL3UQTxd9_5f:b-7m98op) ([raw file](https://github.com/pmem/rpma/blob/d89f6037ce87dd503e2e8213a045a74963b46af1/src/rpma_err.c#L50)):*
> ```C
> 		return "Invalid argument";
> 	case RPMA_E_NO_COMPLETION:
> 		return "No completion available";
> ```

next?
___
*[src/rpma_err.c, line 51 at r1](https://reviewable.io/reviews/pmem/rpma/465#-MIJMlZg7L0kbw0vsY19:-MIJMlZg7L0kbw0vsY1A:bbclhi7) ([raw file](https://github.com/pmem/rpma/blob/d89f6037ce87dd503e2e8213a045a74963b46af1/src/rpma_err.c#L51)):*
> ```C
> 	case RPMA_E_NO_COMPLETION:
> 		return "No completion available";
> 	case RPMA_E_NO_NEXT:
> ```

It looks a bit weird. Maybe it should be named RPMA_E_NO_EVENT?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/465)* status: 0 of 8 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[src/rpma_err.c, line 50 at r1](https://reviewable.io/reviews/pmem/rpma/465#-MIJMiFfCL3UQTxd9_5e:-MIJNVaRC_VI0LWoaZ0i:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d89f6037ce87dd503e2e8213a045a74963b46af1/src/rpma_err.c#L50)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

next?
</blockquote></details>

Done.
___
*[src/rpma_err.c, line 51 at r1](https://reviewable.io/reviews/pmem/rpma/465#-MIJMlZg7L0kbw0vsY19:-MIJOAE6B8dlz7C4E_d0:biw8y1v) ([raw file](https://github.com/pmem/rpma/blob/d89f6037ce87dd503e2e8213a045a74963b46af1/src/rpma_err.c#L51)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It looks a bit weird. Maybe it should be named RPMA_E_NO_EVENT?
</blockquote></details>

Right. Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 8 of 8 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/465#-:-MIJOg29Dm35wjzDSqXM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/465#-:-MIJWl9OELZxyrpkz8ou:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
