### PR TITLE
rpma: implement rpma_conn_req_recv() and its unit tests

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #327 

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/326)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/326)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[tests/unit/conn_req/conn_req-common.h, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/326#-MG8ogme8eLXQUIWJoYM:-MG8ogme8eLXQUIWJoYN:b-wxg8ud) ([raw file](https://github.com/pmem/rpma/blob/f71e021415177b5f2cc59e30dd3a76679da99678/tests/unit/conn_req/conn_req-common.h#L20)):*
> ```objc
> #define MOCK_LEN		(size_t)0xC415
> #define MOCK_FLAGS		(int)0xC416
> #define MOCK_OP_CONTEXT		(void *)0xC417
> ```

Can some of these go to test-common.h?
___
*[tests/unit/conn_req/conn_req-recv.c, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/326#-MG8oGjmCJdKcJnrQBoL:-MG8oGjnDN8UmFSGQaCV:bb7opcw) ([raw file](https://github.com/pmem/rpma/blob/f71e021415177b5f2cc59e30dd3a76679da99678/tests/unit/conn_req/conn_req-recv.c#L48)):*
> ```C
>  */
> static void
> recv__req_dst_src_NULL(void **unused)
> ```

src?
___
*[tests/unit/conn_req/conn_req-recv.c, line 90 at r1](https://reviewable.io/reviews/pmem/rpma/326#-MG8oNBlAqN4QHZKArKn:-MG8oNBlAqN4QHZKArKo:b-s3hmk9) ([raw file](https://github.com/pmem/rpma/blob/f71e021415177b5f2cc59e30dd3a76679da99678/tests/unit/conn_req/conn_req-recv.c#L90)):*
> ```C
> 	cmocka_unit_test_setup_teardown(recv__success,
> 		setup__conn_req_new, teardown__conn_req_new),
> 	cmocka_unit_test(NULL)
> ```

Not needed.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/326)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tests/unit/conn_req/conn_req-common.h, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/326#-MG8ogme8eLXQUIWJoYM:-MG8rIwD7B0oVxBtJe9r:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f71e021415177b5f2cc59e30dd3a76679da99678/tests/unit/conn_req/conn_req-common.h#L20)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Can some of these go to test-common.h?
</blockquote></details>

Done.
___
*[tests/unit/conn_req/conn_req-recv.c, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/326#-MG8oGjmCJdKcJnrQBoL:-MG8pDhM0qiPqXcFBKAa:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f71e021415177b5f2cc59e30dd3a76679da99678/tests/unit/conn_req/conn_req-recv.c#L48)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

src?
</blockquote></details>

Done.
___
*[tests/unit/conn_req/conn_req-recv.c, line 90 at r1](https://reviewable.io/reviews/pmem/rpma/326#-MG8oNBlAqN4QHZKArKn:-MG8pJ89BlogvrCdqsTq:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f71e021415177b5f2cc59e30dd3a76679da99678/tests/unit/conn_req/conn_req-recv.c#L90)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not needed.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/326#-:-MG9Bs7W5eI1Z5U4tPvu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/326#-:-MGCsXsN61rEj6UkkQJx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
