### PR TITLE
tools: check if the FORCE_REMOTE_DIRECT_WRITE_TO_PMEM value is equal …

### PR DESCRIPTION
**Pull request by osalyk**
…to the REMOTE_DIRECT_WRITE_TO_PMEM value

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/950)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/950)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/rpma_fio_bench.sh, line 147 at r1](https://reviewable.io/reviews/pmem/rpma/950#-MW-JtRZ975ejk6oP6zZ:-MW-JtRZ975ejk6oP6z_:b-qkrtph) ([raw file](https://github.com/pmem/rpma/blob/544481348ccdc6a7d62b47aa40c914b11a842a7f/tools/perf/rpma_fio_bench.sh#L147)):*
> ```Shell
> 	echo
> 	if [ -n "$FORCE_REMOTE_DIRECT_WRITE_TO_PMEM" -a "$FORCE_REMOTE_DIRECT_WRITE_TO_PMEM" != "$REMOTE_DIRECT_WRITE_TO_PMEM" ]; then
> 		echo "Error: FORCE_REMOTE_DIRECT_WRITE_TO_PMEM is set, but REMOTE_SUDO_NOPASSWD does not equal 1."
> ```

```sh
Error: FORCE_REMOTE_DIRECT_WRITE_TO_PMEM != REMOTE_DIRECT_WRITE_TO_PMEM ($FORCE_REMOTE_DIRECT_WRITE_TO_PMEM != $REMOTE_DIRECT_WRITE_TO_PMEM), but REMOTE_SUDO_NOPASSWD does not equal 1.
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/950)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/rpma_fio_bench.sh, line 147 at r1](https://reviewable.io/reviews/pmem/rpma/950#-MW-JtRZ975ejk6oP6zZ:-MW-LjJsAcLH3Z6a4_ws:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/544481348ccdc6a7d62b47aa40c914b11a842a7f/tools/perf/rpma_fio_bench.sh#L147)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```sh
Error: FORCE_REMOTE_DIRECT_WRITE_TO_PMEM != REMOTE_DIRECT_WRITE_TO_PMEM ($FORCE_REMOTE_DIRECT_WRITE_TO_PMEM != $REMOTE_DIRECT_WRITE_TO_PMEM), but REMOTE_SUDO_NOPASSWD does not equal 1.
```
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/950)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/rpma_fio_bench.sh, line 148 at r2](https://reviewable.io/reviews/pmem/rpma/950#-MW-MYD-DcmOekm-wvcx:-MW-MYD01evcQNpCxvbn:btkol6x) ([raw file](https://github.com/pmem/rpma/blob/bd393c078e9143e36c01d6ccbd48ed99057b7c6a/tools/perf/rpma_fio_bench.sh#L148)):*
> ```Shell
> 	if [ -n "$FORCE_REMOTE_DIRECT_WRITE_TO_PMEM" -a "$FORCE_REMOTE_DIRECT_WRITE_TO_PMEM" != "$REMOTE_DIRECT_WRITE_TO_PMEM" ]; then
> 		echo "Error: FORCE_REMOTE_DIRECT_WRITE_TO_PMEM != REMOTE_DIRECT_WRITE_TO_PMEM ($FORCE_REMOTE_DIRECT_WRITE_TO_PMEM != $REMOTE_DIRECT_WRITE_TO_PMEM),"
> 		echo "       and REMOTE_SUDO_NOPASSWD does not equal 1."
> ```

does -> is? @ldorau

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/950)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/rpma_fio_bench.sh, line 148 at r2](https://reviewable.io/reviews/pmem/rpma/950#-MW-NsHa4HEKp63cec6U:-MW-NsHa4HEKp63cec6V:bv0nzfp) ([raw file](https://github.com/pmem/rpma/blob/bd393c078e9143e36c01d6ccbd48ed99057b7c6a/tools/perf/rpma_fio_bench.sh#L148)):*
> ```Shell
> 	if [ -n "$FORCE_REMOTE_DIRECT_WRITE_TO_PMEM" -a "$FORCE_REMOTE_DIRECT_WRITE_TO_PMEM" != "$REMOTE_DIRECT_WRITE_TO_PMEM" ]; then
> 		echo "Error: FORCE_REMOTE_DIRECT_WRITE_TO_PMEM != REMOTE_DIRECT_WRITE_TO_PMEM ($FORCE_REMOTE_DIRECT_WRITE_TO_PMEM != $REMOTE_DIRECT_WRITE_TO_PMEM),"
> 		echo "       and REMOTE_SUDO_NOPASSWD does not equal 1."
> ```

equal -> equal to

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/950)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/rpma_fio_bench.sh, line 148 at r2](https://reviewable.io/reviews/pmem/rpma/950#-MW-MYD-DcmOekm-wvcx:-MW-UPqPB3CAbEkWrPp_:bknj2ov) ([raw file](https://github.com/pmem/rpma/blob/bd393c078e9143e36c01d6ccbd48ed99057b7c6a/tools/perf/rpma_fio_bench.sh#L148)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

does -> is? @ldorau 
</blockquote></details>

According to www.oxfordlearnersdictionaries.com in maths operations 'equal' is used as a verb:
https://www.oxfordlearnersdictionaries.com/definition/english/equal_2
https://www.oxfordlearnersdictionaries.com/topic/maths-and-measurement?level=b1
https://www.oxfordlearnersdictionaries.com/definition/english/equal_1

so the current version is OK
___
*[tools/perf/rpma_fio_bench.sh, line 148 at r2](https://reviewable.io/reviews/pmem/rpma/950#-MW-NsHa4HEKp63cec6U:-MW-UpJh3Ek07E6qK4kX:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/bd393c078e9143e36c01d6ccbd48ed99057b7c6a/tools/perf/rpma_fio_bench.sh#L148)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

equal -> equal to
</blockquote></details>

.

**Review by janekmi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/950#-:-MW-X-0Y-H6QnjZv2M-B:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/950#-:-MW-XqlM70yzkVzmqtsF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
