### PR TITLE
rpma: add rpma_conn_req_get_private_data()

### PR DESCRIPTION
**Pull request by ewanglong**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/911)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/911)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @ewanglong)

___
*[src/conn_req.c, line 494 at r2](https://reviewable.io/reviews/pmem/rpma/911#-MUNlJMk8xoBlmd6qOES:-MUNlJMk8xoBlmd6qOET:bxggdvi) ([raw file](https://github.com/pmem/rpma/blob/e9ccbb031b9de1f401c17fed906235e24c10ea30/src/conn_req.c#L494)):*
> ```C
> {
> 	if (req == NULL || pdata == NULL)
> 		return RPMA_E_INVAL;
> ```

This line is not covered by unit tests.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/911)* status: 4 of 5 files reviewed, 6 unresolved discussions (waiting on @ewanglong)

___
*[src/conn_req.c, line 486 at r2](https://reviewable.io/reviews/pmem/rpma/911#-MUNrSGg0s655DJdkxhl:-MUNrSGg0s655DJdkxhm:b-dy8e5f) ([raw file](https://github.com/pmem/rpma/blob/e9ccbb031b9de1f401c17fed906235e24c10ea30/src/conn_req.c#L486)):*
> ```C
> 
> /*
>  * rpma_conn_req_get_private_data - get a pointer to the incoming connection's
> ```

`-` -> `--`
___
*[src/include/librpma.h, line 1963 at r2](https://reviewable.io/reviews/pmem/rpma/911#-MUNu0NGAUVg0v4mxw_K:-MUNu0NGAUVg0v4mxw_L:b-2mv5lc) ([raw file](https://github.com/pmem/rpma/blob/e9ccbb031b9de1f401c17fed906235e24c10ea30/src/include/librpma.h#L1963)):*
> ```objc
>  * rpma_conn_req_get_private_data() obtains the pointer to the connection's
>  * private data given by the other side of the connection before the connection
>  * is fully established.
> ```

~~fully~~ conveys here no meaning.
___
*[src/include/librpma.h, line 1969 at r2](https://reviewable.io/reviews/pmem/rpma/911#-MUNuUjWBEoWFEeKktvV:-MUNuUjWBEoWFEeKktvW:b-ssmh64) ([raw file](https://github.com/pmem/rpma/blob/e9ccbb031b9de1f401c17fed906235e24c10ea30/src/include/librpma.h#L1969)):*
> ```objc
>  * Use rpma_conn_get_private_data(3) to get a pointer to the connection's
>  * private data if access to it is still required after the connection is
>  * established.
> ```

This part is the result of the way in which we handle the private data. I think we should consider improving this use case.

Ref: #912 
___
*[src/include/librpma.h, line 1983 at r2](https://reviewable.io/reviews/pmem/rpma/911#-MUNxAis9HNld1QcQxjX:-MUNxAis9HNld1QcQxjY:b7wyyp5) ([raw file](https://github.com/pmem/rpma/blob/e9ccbb031b9de1f401c17fed906235e24c10ea30/src/include/librpma.h#L1983)):*
> ```objc
>  * SEE ALSO
>  * rpma_conn_get_private_data(3), rpma_ep_next_conn_req(3), librpma(7)
>  * and https://pmem.io/rpma/
> ```

I would add here also `rpma_conn_get_private_data()` since it is referrenced in the body.
___
*[src/include/librpma.h, line 1989 at r2](https://reviewable.io/reviews/pmem/rpma/911#-MUNszIQ2tbcCPWLeWwX:-MUNszIQ2tbcCPWLeWwY:bf2zz7e) ([raw file](https://github.com/pmem/rpma/blob/e9ccbb031b9de1f401c17fed906235e24c10ea30/src/include/librpma.h#L1989)):*
> ```objc
> 
> ```

Redundant empty lines.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/911)* status: all files reviewed, 7 unresolved discussions (waiting on @ewanglong)

___
*[tests/unit/conn_req/conn_req-connect.c, line 445 at r2](https://reviewable.io/reviews/pmem/rpma/911#-MUNxi318fTXu8pt1lg5:-MUNxi318fTXu8pt1lg6:bhb2p3o) ([raw file](https://github.com/pmem/rpma/blob/e9ccbb031b9de1f401c17fed906235e24c10ea30/tests/unit/conn_req/conn_req-connect.c#L445)):*
> ```C
> 	assert_int_equal(conn, MOCK_CONN);
> }
> ```

This test should go to a separate file `conn_req-private_data.c`

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/911)* status: 2 of 6 files reviewed, 7 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

___
*[src/conn_req.c, line 486 at r2](https://reviewable.io/reviews/pmem/rpma/911#-MUNrSGg0s655DJdkxhl:-MUfeTzX421Y-hoookbc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e9ccbb031b9de1f401c17fed906235e24c10ea30/src/conn_req.c#L486)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`-` -> `--`
</blockquote></details>

Done.
___
*[src/conn_req.c, line 494 at r2](https://reviewable.io/reviews/pmem/rpma/911#-MUNlJMk8xoBlmd6qOES:-MUfeSnb6AyShqOz3LwC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e9ccbb031b9de1f401c17fed906235e24c10ea30/src/conn_req.c#L494)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

This line is not covered by unit tests.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1963 at r2](https://reviewable.io/reviews/pmem/rpma/911#-MUNu0NGAUVg0v4mxw_K:-MUfeWiu4SXy0KrrUKC2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e9ccbb031b9de1f401c17fed906235e24c10ea30/src/include/librpma.h#L1963)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

~~fully~~ conveys here no meaning.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1983 at r2](https://reviewable.io/reviews/pmem/rpma/911#-MUNxAis9HNld1QcQxjX:-MUfeYSR0RMFQjYAuQ8r:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e9ccbb031b9de1f401c17fed906235e24c10ea30/src/include/librpma.h#L1983)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I would add here also `rpma_conn_get_private_data()` since it is referrenced in the body.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1989 at r2](https://reviewable.io/reviews/pmem/rpma/911#-MUNszIQ2tbcCPWLeWwX:-MUfeZ-qCks011Sj9a7y:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e9ccbb031b9de1f401c17fed906235e24c10ea30/src/include/librpma.h#L1989)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Redundant empty lines.
</blockquote></details>

Done.
___
*[tests/unit/conn_req/conn_req-connect.c, line 445 at r2](https://reviewable.io/reviews/pmem/rpma/911#-MUNxi318fTXu8pt1lg5:-MUfe_2c7ZxV7wxnZfAP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e9ccbb031b9de1f401c17fed906235e24c10ea30/tests/unit/conn_req/conn_req-connect.c#L445)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This test should go to a separate file `conn_req-private_data.c`
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/911)* status: 2 of 6 files reviewed, 8 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

___
*[tests/unit/conn_req/CMakeLists.txt, line 3 at r3](https://reviewable.io/reviews/pmem/rpma/911#-MUhQzRU8OCWFFLd_MU-:-MUhQzRV91ZyylXFwFyQ:by1hvcl) ([raw file](https://github.com/pmem/rpma/blob/0bf8609809a540d32b36b582ba8f592a0afa63e6/tests/unit/conn_req/CMakeLists.txt#L3)):*
> ```
> Copyright 2020,
> ```

tests/unit/conn_req/CMakeLists.txt:1: error: wrong copyright date: (is: 2020, should be: 2020-2021)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/911)* status: 3 of 6 files reviewed, 8 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[src/conn_req.c, line 494 at r2](https://reviewable.io/reviews/pmem/rpma/911#-MUNlJMk8xoBlmd6qOES:-MUhS9Cn4sxRke3quRLt:btrxok1) ([raw file](https://github.com/pmem/rpma/blob/e9ccbb031b9de1f401c17fed906235e24c10ea30/src/conn_req.c#L494)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Done.
</blockquote></details>

The builds fail and there is no new coverage report ...

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/911)* status: 5 of 6 files reviewed, 7 unresolved discussions (waiting on @ewanglong)

___
*[src/include/librpma.h, line 1983 at r2](https://reviewable.io/reviews/pmem/rpma/911#-MUNxAis9HNld1QcQxjX:-MUiZoFgBSKyvsW0QIrF:bwod9ch) ([raw file](https://github.com/pmem/rpma/blob/e9ccbb031b9de1f401c17fed906235e24c10ea30/src/include/librpma.h#L1983)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Sorry, I have missed it. It is ok. Please return the `(3)`.
___
*[tests/unit/conn_req/CMakeLists.txt, line 40 at r3](https://reviewable.io/reviews/pmem/rpma/911#-MUi_ByF-kDTaVtMq8d2:-MUi_ByF-kDTaVtMq8d3:b-54pt2a) ([raw file](https://github.com/pmem/rpma/blob/0bf8609809a540d32b36b582ba8f592a0afa63e6/tests/unit/conn_req/CMakeLists.txt#L40)):*
> ```CMake
> add_test_conn_req(new)
> add_test_conn_req(recv)
> add_test_conn_req(private_data)
> ```

Please keep alphabetical order.
___
*[tests/unit/conn_req/conn_req-private_data.c, line 5 at r3](https://reviewable.io/reviews/pmem/rpma/911#-MUi_RivEGANPyXvpb1o:-MUi_RivEGANPyXvpb1p:b126qtu) ([raw file](https://github.com/pmem/rpma/blob/0bf8609809a540d32b36b582ba8f592a0afa63e6/tests/unit/conn_req/conn_req-private_data.c#L5)):*
> ```C
> 
> /*
>  * conn_req-connect.c -- the rpma_conn_req_connect() unit tests
> ```

```
conn_req-private_data.c -- the rpma_conn_get_private_data() unit tests
```

___
*[tests/unit/conn_req/conn_req-private_data.c, line 8 at r3](https://reviewable.io/reviews/pmem/rpma/911#-MUi_hDA8AfwZbi_Xg3b:-MUi_hDA8AfwZbi_Xg3c:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/0bf8609809a540d32b36b582ba8f592a0afa63e6/tests/unit/conn_req/conn_req-private_data.c#L8)):*
> ```C
>  *
>  * APIs covered:
>  * - rpma_conn_req_connect()
> ```

.

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/911)* status: 3 of 6 files reviewed, 7 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

___
*[src/conn_req.c, line 494 at r2](https://reviewable.io/reviews/pmem/rpma/911#-MUNlJMk8xoBlmd6qOES:-MUqp8e8Eg6R8lL8vSAe:b-h6p0qs) ([raw file](https://github.com/pmem/rpma/blob/e9ccbb031b9de1f401c17fed906235e24c10ea30/src/conn_req.c#L494)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The builds fail and there is no new coverage report ...
</blockquote></details>

Repush it and build passed.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/911)* status: 4 of 6 files reviewed, 6 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/unit/conn_req/CMakeLists.txt, line 3 at r3](https://reviewable.io/reviews/pmem/rpma/911#-MUhQzRU8OCWFFLd_MU-:-MUrGgFR4GaYJY20cUkE:bpyfs04) ([raw file](https://github.com/pmem/rpma/blob/0bf8609809a540d32b36b582ba8f592a0afa63e6/tests/unit/conn_req/CMakeLists.txt#L3)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> Copyright 2020,
> ```

tests/unit/conn_req/CMakeLists.txt:1: error: wrong copyright date: (is: 2020, should be: 2020-2021)
</blockquote></details>

No "2021", but "2020-2021"

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/911)* status: 4 of 6 files reviewed, 6 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[src/include/librpma.h, line 1969 at r2](https://reviewable.io/reviews/pmem/rpma/911#-MUNuUjWBEoWFEeKktvV:-MUrOuoj2OGwYzRwPPMh:bfh0fhv) ([raw file](https://github.com/pmem/rpma/blob/e9ccbb031b9de1f401c17fed906235e24c10ea30/src/include/librpma.h#L1969)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This part is the result of the way in which we handle the private data. I think we should consider improving this use case.

Ref: #912 
</blockquote></details>

make an experiment change like below:
in src/conn.c
rpma_conn_set_private_data(struct rpma_conn *conn,
		struct rpma_conn_private_data *pdata)
{
	//return rpma_private_data_copy(&conn->data, pdata);
	if (pdata->ptr == NULL)
		return 0;

	conn->data.ptr = pdata->ptr;
	conn->data.len = pdata->len;

	return 0;

}

and in function rpma_conn_req_accept of src/conn_req.c,
remove this line rpma_private_data_discard. seems it works by simple example test.
So the function rpma_private_data_discard is not needed?
And maybe next steps need change all involved unit/integration tests code?

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/911)* status: all files reviewed, 12 unresolved discussions (waiting on @ewanglong)

___
*[src/include/librpma.h, line 1969 at r2](https://reviewable.io/reviews/pmem/rpma/911#-MUNuUjWBEoWFEeKktvV:-MUyYiyf5fzm6E5fYvZd:bab7vbs) ([raw file](https://github.com/pmem/rpma/blob/e9ccbb031b9de1f401c17fed906235e24c10ea30/src/include/librpma.h#L1969)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

make an experiment change like below:
in src/conn.c
rpma_conn_set_private_data(struct rpma_conn *conn,
		struct rpma_conn_private_data *pdata)
{
	//return rpma_private_data_copy(&conn->data, pdata);
	if (pdata->ptr == NULL)
		return 0;

	conn->data.ptr = pdata->ptr;
	conn->data.len = pdata->len;

	return 0;

}

and in function rpma_conn_req_accept of src/conn_req.c,
remove this line rpma_private_data_discard. seems it works by simple example test.
So the function rpma_private_data_discard is not needed?
And maybe next steps need change all involved unit/integration tests code?
</blockquote></details>

Sorry. This comment should not be a blocking one.
___
*[tests/unit/conn_req/conn_req-private_data.c, line 14 at r4](https://reviewable.io/reviews/pmem/rpma/911#-MUy_nVIC7T90lXZ59fe:-MUy_nVIC7T90lXZ59ff:b-ly79ia) ([raw file](https://github.com/pmem/rpma/blob/3fa67e757cec99706cbc3cdf50dd0290d9fdf460/tests/unit/conn_req/conn_req-private_data.c#L14)):*
> ```C
> #include "test-common.h"
> 
> static struct conn_req_new_test_state prestate_conn_cfg_default;
> ```

It is not used.
___
*[tests/unit/conn_req/conn_req-private_data.c, line 17 at r4](https://reviewable.io/reviews/pmem/rpma/911#-MUyaYvf1o24eFvWh1qN:-MUyaYvf1o24eFvWh1qO:bh1uaho) ([raw file](https://github.com/pmem/rpma/blob/3fa67e757cec99706cbc3cdf50dd0290d9fdf460/tests/unit/conn_req/conn_req-private_data.c#L17)):*
> ```C
> 
> /*
>  * connect_via_accept_wi_pdata__success --
> ```

I recommend using this name: `get_private_data__success`
And I prefer this comment: `happy day scenario`
Referring to the complete (pretty long) name of the API call introduces a lot of redundancy knowing this whole `.c` file is about a single API call.
___
*[tests/unit/conn_req/conn_req-private_data.c, line 21 at r4](https://reviewable.io/reviews/pmem/rpma/911#-MUyaUFpEUVuljpsXeFS:-MUyaUFpEUVuljpsXeFT:b-573fdd) ([raw file](https://github.com/pmem/rpma/blob/3fa67e757cec99706cbc3cdf50dd0290d9fdf460/tests/unit/conn_req/conn_req-private_data.c#L21)):*
> ```C
>  */
> static void
> connect_via_accept_wi_pdata__success_incoming(void **unused)
> ```

get_private_data__success
___
*[tests/unit/conn_req/conn_req-private_data.c, line 52 at r4](https://reviewable.io/reviews/pmem/rpma/911#-MUyaCv9BWVnRoJBM-my:-MUyaCv9BWVnRoJBM-mz:b-5aep3l) ([raw file](https://github.com/pmem/rpma/blob/3fa67e757cec99706cbc3cdf50dd0290d9fdf460/tests/unit/conn_req/conn_req-private_data.c#L52)):*
> ```C
> 	/* run test */
> 	struct rpma_conn *conn = NULL;
> 	ret = rpma_conn_req_connect(&cstate->req, NULL, &conn);
> ```

I think you do not need this here.
___
*[tests/unit/conn_req/conn_req-private_data.c, line 61 at r4](https://reviewable.io/reviews/pmem/rpma/911#-MUyapfH00hPtvVhB5wJ:-MUyapfH00hPtvVhB5wK:b-6n4fh0) ([raw file](https://github.com/pmem/rpma/blob/3fa67e757cec99706cbc3cdf50dd0290d9fdf460/tests/unit/conn_req/conn_req-private_data.c#L61)):*
> ```C
> 
> /*
>  * connect_via_accept_wi_pdata__null_req -- rpma_conn_req_get_private_data()
> ```

get_private_data__conn_req_NULL -- conn_req NULL is invalid
___
*[tests/unit/conn_req/conn_req-private_data.c, line 65 at r4](https://reviewable.io/reviews/pmem/rpma/911#-MUyamGF5hDqqenRbKFO:-MUyamGF5hDqqenRbKFP:b70ye1z) ([raw file](https://github.com/pmem/rpma/blob/3fa67e757cec99706cbc3cdf50dd0290d9fdf460/tests/unit/conn_req/conn_req-private_data.c#L65)):*
> ```C
>  */
> static void
> connect_via_accept_wi_pdata__null_req(void **unused)
> ```

get_private_data__conn_req_NULL
___
*[tests/unit/conn_req/conn_req-private_data.c, line 87 at r4](https://reviewable.io/reviews/pmem/rpma/911#-MUyaf-eCrSan5SJIata:-MUyaf-eCrSan5SJIatb:bmn7uax) ([raw file](https://github.com/pmem/rpma/blob/3fa67e757cec99706cbc3cdf50dd0290d9fdf460/tests/unit/conn_req/conn_req-private_data.c#L87)):*
> ```C
> 	/* get private data */
> 	struct rpma_conn_private_data data;
> 	int ret = rpma_conn_req_get_private_data(NULL, &data);
> ```

To test this you need only a valid data pointer. Please remove everything else.
___
*[tests/unit/conn_req/conn_req-private_data.c, line 94 at r4](https://reviewable.io/reviews/pmem/rpma/911#-MUyacIyBTIgGsq0qEW-:-MUyacIyBTIgGsq0qEW0:byve3ty) ([raw file](https://github.com/pmem/rpma/blob/3fa67e757cec99706cbc3cdf50dd0290d9fdf460/tests/unit/conn_req/conn_req-private_data.c#L94)):*
> ```C
> 	/* run test */
> 	struct rpma_conn *conn = NULL;
> 	ret = rpma_conn_req_connect(&cstate->req, NULL, &conn);
> ```

It is not needed.
___
*[tests/unit/conn_req/conn_req-private_data.c, line 103 at r4](https://reviewable.io/reviews/pmem/rpma/911#-MUybalH6ntCjAcEdQpi:-MUybalI2hNUNvmTJJKf:bcbm3aa) ([raw file](https://github.com/pmem/rpma/blob/3fa67e757cec99706cbc3cdf50dd0290d9fdf460/tests/unit/conn_req/conn_req-private_data.c#L103)):*
> ```C
> 
> /*
>  * connect_via_accept_wi_pdata__null_req -- rpma_conn_req_get_private_data()
> ```

`get_private_data__pdata_NULL -- pdata NULL is invalid`
___
*[tests/unit/conn_req/conn_req-private_data.c, line 107 at r4](https://reviewable.io/reviews/pmem/rpma/911#-MUybk4_Dc0uP-IG5KMQ:-MUybk4_Dc0uP-IG5KMR:bi63z4w) ([raw file](https://github.com/pmem/rpma/blob/3fa67e757cec99706cbc3cdf50dd0290d9fdf460/tests/unit/conn_req/conn_req-private_data.c#L107)):*
> ```C
>  */
> static void
> connect_via_accept_wi_pdata__null_pdata(void **unused)
> ```

get_private_data__pdata_NULL
___
*[tests/unit/conn_req/conn_req-private_data.c, line 135 at r4](https://reviewable.io/reviews/pmem/rpma/911#-MUyblGt9Ydt2NqdozNR:-MUyblGt9Ydt2NqdozNS:b-s3hmk9) ([raw file](https://github.com/pmem/rpma/blob/3fa67e757cec99706cbc3cdf50dd0290d9fdf460/tests/unit/conn_req/conn_req-private_data.c#L135)):*
> ```C
> 	/* run test */
> 	struct rpma_conn *conn = NULL;
> 	ret = rpma_conn_req_connect(&cstate->req, NULL, &conn);
> ```

Not needed.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/911)* status: all files reviewed, 3 unresolved discussions (waiting on @ewanglong)

___
*[tests/unit/conn_req/conn_req-private_data.c, line 103 at r4](https://reviewable.io/reviews/pmem/rpma/911#-MUybalH6ntCjAcEdQpi:-MV0ZVRN75e3ZEwSnHwU:bqmq1q4) ([raw file](https://github.com/pmem/rpma/blob/3fa67e757cec99706cbc3cdf50dd0290d9fdf460/tests/unit/conn_req/conn_req-private_data.c#L103)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`get_private_data__pdata_NULL -- pdata NULL is invalid`
</blockquote></details>

`NULL` is missing.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/911)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/911)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[src/include/librpma.h, line 1969 at r2](https://reviewable.io/reviews/pmem/rpma/911#-MUNuUjWBEoWFEeKktvV:-MV0a5FuD_8Tu7ghy3R2:bvsp50d) ([raw file](https://github.com/pmem/rpma/blob/e9ccbb031b9de1f401c17fed906235e24c10ea30/src/include/librpma.h#L1969)):*
> To test this you
___
*[tests/unit/conn_req/CMakeLists.txt, line 3 at r3](https://reviewable.io/reviews/pmem/rpma/911#-MUhQzRU8OCWFFLd_MU-:-MV0asI08SQyPlEPo0tl:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0bf8609809a540d32b36b582ba8f592a0afa63e6/tests/unit/conn_req/CMakeLists.txt#L3)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No "2021", but "2020-2021"
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/911#-:-MV0b26c3tAdTaOiqRuB:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 3 files at r4, 1 of 1 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/911)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/911)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/911#-:-MV0bTCZ2nhXIBlJPSjc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/911)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Pull request merged**
