### PR TITLE
examples: add rpma_mr_advise

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1505)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1505)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

___
*[examples/05-flush-to-persistent/server.c, line 179 at r1](https://reviewable.io/reviews/pmem/rpma/1505#-MtrGTL121t6VvdcjIOs:-MtrGTL121t6VvdcjIOt:bxgi06r) ([raw file](https://github.com/pmem/rpma/blob/fa6aabf33bee40e13f200357a7025949a84e31e8/examples/05-flush-to-persistent/server.c#L179)):*
> ```C
> 
> #ifdef USE_LIBPMEM
> 	char *path = argv[3];
> ```

`if (argc >= 4) {` has to be added before.



_Code quote:_
```C
char *path = argv[3];
```
___
*[examples/05-flush-to-persistent/server.c, line 180 at r1](https://reviewable.io/reviews/pmem/rpma/1505#-MtrGj1e1wDALUl861H8:-MtrGj1e1wDALUl861H9:b-m37y3d) ([raw file](https://github.com/pmem/rpma/blob/fa6aabf33bee40e13f200357a7025949a84e31e8/examples/05-flush-to-persistent/server.c#L180)):*
> ```C
> #ifdef USE_LIBPMEM
> 	char *path = argv[3];
> 	if (is_pmem && strstr(path, "/dev/dax") == NULL) {
> ```

Please add a comment just before this line
`# rpma_mr_advise() should be called only in case of FsDAX`



_Code quote:_
```C
if (is_pmem && strstr(path, "/dev/dax") == NULL) {
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1505)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[examples/05-flush-to-persistent/server.c, line 179 at r1](https://reviewable.io/reviews/pmem/rpma/1505#-MtrGTL121t6VvdcjIOs:-MtrNoTTEicg6mTomYek:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fa6aabf33bee40e13f200357a7025949a84e31e8/examples/05-flush-to-persistent/server.c#L179)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`if (argc >= 4) {` has to be added before.
</blockquote></details>

Done.
___
*[examples/05-flush-to-persistent/server.c, line 180 at r1](https://reviewable.io/reviews/pmem/rpma/1505#-MtrGj1e1wDALUl861H8:-MtrNoDdBPzgDM9n4Ijd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fa6aabf33bee40e13f200357a7025949a84e31e8/examples/05-flush-to-persistent/server.c#L180)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please add a comment just before this line
`# rpma_mr_advise() should be called only in case of FsDAX`
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1505)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1505)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[examples/05-flush-to-persistent/server.c, line 18 at r2](https://reviewable.io/reviews/pmem/rpma/1505#-MttHgAW6YNsHFAwIo0O:-MttHgAX91W48oMXSsr8:b-ic7os2) ([raw file](https://github.com/pmem/rpma/blob/58050b64692c53ddb6385fab7341b3936b5e6400/examples/05-flush-to-persistent/server.c#L18)):*
> ```C
> #include <libpmem.h>
> #define USAGE_STR "usage: %s <server_address> <port> [<pmem-path>] " \
> 	"[direct-pmem-write]\n"
> ```

Either here or in README.md we should mention about possibility to use either DevDAX or FsDAX pmem path



_Code quote:_
```C
#define USAGE_STR "usage: %s <server_address> <port> [<pmem-path>] " \
	"[direct-pmem-write]\n"
```

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1505)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[examples/05-flush-to-persistent/server.c, line 18 at r2](https://reviewable.io/reviews/pmem/rpma/1505#-MttHgAW6YNsHFAwIo0O:-MtvyVquCZK7mxNoqRon:bfmcqr4) ([raw file](https://github.com/pmem/rpma/blob/58050b64692c53ddb6385fab7341b3936b5e6400/examples/05-flush-to-persistent/server.c#L18)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Either here or in README.md we should mention about possibility to use either DevDAX or FsDAX pmem path
</blockquote></details>

@grom72  Can it be:
```c
#include <libpmem.h>
/* 
 * <pmem-path> can be:
 * - a Device DAX (/dev/dax0.0 for example) or 
 * - a file on File System DAX (/mnt/pmem/file for example).
 */
#define USAGE_STR "usage: %s <server_address> <port> [<pmem-path>] " \
	"[direct-pmem-write]\n"
```
in each file?

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1505)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[examples/05-flush-to-persistent/server.c, line 18 at r2](https://reviewable.io/reviews/pmem/rpma/1505#-MttHgAW6YNsHFAwIo0O:-Mtw-RSZ-aCpac1sMp9S:b-1m7m2d) ([raw file](https://github.com/pmem/rpma/blob/58050b64692c53ddb6385fab7341b3936b5e6400/examples/05-flush-to-persistent/server.c#L18)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@grom72  Can it be:
```c
#include <libpmem.h>
/* 
 * <pmem-path> can be:
 * - a Device DAX (/dev/dax0.0 for example) or 
 * - a file on File System DAX (/mnt/pmem/file for example).
 */
#define USAGE_STR "usage: %s <server_address> <port> [<pmem-path>] " \
	"[direct-pmem-write]\n"
```
in each file?
</blockquote></details>

Looks good. Shall we add anything to usage string?

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1505)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[examples/05-flush-to-persistent/server.c, line 18 at r2](https://reviewable.io/reviews/pmem/rpma/1505#-MttHgAW6YNsHFAwIo0O:-MtwA2hJ4KdQVpORlQum:b-kdxmfw) ([raw file](https://github.com/pmem/rpma/blob/58050b64692c53ddb6385fab7341b3936b5e6400/examples/05-flush-to-persistent/server.c#L18)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Looks good. Shall we add anything to usage string?
</blockquote></details>

In a separate PR.

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1505#-:-MtwAlcsC9D4lWPZhtfj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — APPROVED** [review]
Please rebase to master.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1505#-:-MtwAz69-hypYYyD2R7I:b-hdrve0)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1505)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 3 files at r3, 4 of 5 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1505)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
