### PR TITLE
doc: add SEE ALSO section (ep, rpma)

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/495)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/495)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[src/include/librpma.h, line 1610 at r1](https://reviewable.io/reviews/pmem/rpma/495#-MITVH_P9FB26JxRZRO-:-MITVH_P9FB26JxRZRO0:b-8og528) ([raw file](https://github.com/pmem/rpma/blob/16c7e5a9663683b58e484bcc99728b17c5467d7b/src/include/librpma.h#L1610)):*
> ```objc
>  * SEE ALSO
>  * rpma_conn_cfg_new(3), rpma_conn_req_delete(3), rpma_conn_req_connect(3),
>  * rpma_conn_req_new(3), rpma_ep_listen(3) and https://pmem.io/rpma/
> ```

I think conn_req_new in this context does not make sense.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/495)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[src/include/librpma.h, line 1610 at r1](https://reviewable.io/reviews/pmem/rpma/495#-MITVH_P9FB26JxRZRO-:-MITpPytC2iMp1DeKDJ2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/16c7e5a9663683b58e484bcc99728b17c5467d7b/src/include/librpma.h#L1610)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think conn_req_new in this context does not make sense.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/495#-:-MITrhfk1rl0wCwVANKx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/495#-:-MITwZXe8j6pz5i9qRiv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
