### PR TITLE
doc: separate receive CQ & rpma_mr_advise()

### PR DESCRIPTION
**Pull request by janekmi**
Ref: #1080 #1220

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1216)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1216)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1216#-:-MhwPO0f5gWuVMQPMVyY:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by yangx-jy — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1216)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1216#-Miyowox-LLJBIX7HYDP:-Miyowox-LLJBIX7HYDQ:bg7igkv) (no related file):*
:lgtm: 

---

**Comment by janekmi** [comment]
Have to consider also the newest update #1220

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1216)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72 and @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1216#-Miyowox-LLJBIX7HYDP:-MjoKG8o8b2pTEZCmyL8:b-pyzkpu) (no related file):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

:lgtm: 
</blockquote></details>

Done. ;-)

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1216#-MjoKIhJ2n1iA-86pDy5:-MjoKIhJ2n1iA-86pDy6:biqy2yb) (no related file):*
Preview: https://janekmi.github.io/rpma/manpages/master/librpma.7.html

---

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1216)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1216#-:-MkBOcPi5SVCL6U8QUtt:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1216)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1216#-Miyowox-LLJBIX7HYDP:-MkBOyBH1ueP-3xniFlQ:bb5rorp) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Done. ;-)
</blockquote></details>

:lgtm:  :-)

---

**Pull request merged**
