### PR TITLE
doc: improve the documentation to rpma_utils... functions

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/414)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/414)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[src/include/librpma.h, line 55 at r1](https://reviewable.io/reviews/pmem/rpma/414#-MHjyXYo8C7qQKfeUFMv:-MHjyXYo8C7qQKfeUFMw:b-l52rfj) ([raw file](https://github.com/pmem/rpma/blob/3a98fa56aa7b9d6f935d4995787cfad9adbc5d54/src/include/librpma.h#L55)):*
> ```
> ;}
> ```

Is it correct ? ;}

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/414)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/include/librpma.h, line 55 at r1](https://reviewable.io/reviews/pmem/rpma/414#-MHjyXYo8C7qQKfeUFMv:-MHk0UaSC9ORZgWwxW2D:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3a98fa56aa7b9d6f935d4995787cfad9adbc5d54/src/include/librpma.h#L55)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> ;}
> ```

Is it correct ? ;}
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/414)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[src/include/librpma.h, line 65 at r2](https://reviewable.io/reviews/pmem/rpma/414#-MHk1qVJ81YAa5D-b5bC:-MHk1qVJ81YAa5D-b5bD:b9xy6h6) ([raw file](https://github.com/pmem/rpma/blob/c8a2358fd20f3e3b42a2ae81e4d765439526bee5/src/include/librpma.h#L65)):*
> ```
> ibv_context
> ```

rpma_util_ibv_context_type

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/414)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/include/librpma.h, line 65 at r2](https://reviewable.io/reviews/pmem/rpma/414#-MHk1qVJ81YAa5D-b5bC:-MHk56zz2XJUfNNpSbsA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c8a2358fd20f3e3b42a2ae81e4d765439526bee5/src/include/librpma.h#L65)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> ibv_context
> ```

rpma_util_ibv_context_type
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/414)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[src/include/librpma.h, line 65 at r3](https://reviewable.io/reviews/pmem/rpma/414#-MHkCJi4-HMroLgF251p:-MHkCJi4-HMroLgF251q:buk38hf) ([raw file](https://github.com/pmem/rpma/blob/4c52771243c7298e904cb7fc126ba4ba1006f22f/src/include/librpma.h#L65)):*
> ```
> rpma_util_ibv_context_type
> ```

Excuse me, one more issue:

```
Possible values of 'enum rpma_util_ibv_context_type type' to lookup for:
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/414)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[src/include/librpma.h, line 65 at r3](https://reviewable.io/reviews/pmem/rpma/414#-MHkCJi4-HMroLgF251p:-MHkCk306grKlLzlZITQ:bvasczx) ([raw file](https://github.com/pmem/rpma/blob/4c52771243c7298e904cb7fc126ba4ba1006f22f/src/include/librpma.h#L65)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> rpma_util_ibv_context_type
> ```

Excuse me, one more issue:

```
Possible values of 'enum rpma_util_ibv_context_type type' to lookup for:
```

</blockquote></details>

Or maybe:

`Possible values of the 'type' argument:`

@grom72 what do you think?

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/414)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/include/librpma.h, line 65 at r3](https://reviewable.io/reviews/pmem/rpma/414#-MHkCJi4-HMroLgF251p:-MHkE0D69rQLldD_Ml2k:bmeyrwp) ([raw file](https://github.com/pmem/rpma/blob/4c52771243c7298e904cb7fc126ba4ba1006f22f/src/include/librpma.h#L65)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Or maybe:

`Possible values of the 'type' argument:`

@grom72 what do you think?
</blockquote></details>

:+1:

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/414)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[src/include/librpma.h, line 65 at r3](https://reviewable.io/reviews/pmem/rpma/414#-MHkCJi4-HMroLgF251p:-MHkET0N18V-PEt-bfrm:b-rg8q8j) ([raw file](https://github.com/pmem/rpma/blob/4c52771243c7298e904cb7fc126ba4ba1006f22f/src/include/librpma.h#L65)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

So: `Possible values of the 'type' argument:`

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/414)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/include/librpma.h, line 65 at r3](https://reviewable.io/reviews/pmem/rpma/414#-MHkCJi4-HMroLgF251p:-MHkF8TIBmeldOEuRYbZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4c52771243c7298e904cb7fc126ba4ba1006f22f/src/include/librpma.h#L65)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

So: `Possible values of the 'type' argument:`
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/414#-:-MHkI2fXC7oDAt6J56wZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/414)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[src/include/librpma.h, line 66 at r3](https://reviewable.io/reviews/pmem/rpma/414#-MHkIyTO6IlHE9FUNp_T:-MHkIyTO6IlHE9FUNp_U:b-wt0w6t) ([raw file](https://github.com/pmem/rpma/blob/4c52771243c7298e904cb7fc126ba4ba1006f22f/src/include/librpma.h#L66)):*
> ```
> lookup for a local device
> ```
lookup for device based given on local address

...
lookup for device based on given remote address

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/414)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[src/include/librpma.h, line 66 at r3](https://reviewable.io/reviews/pmem/rpma/414#-MHkIyTO6IlHE9FUNp_T:-MHkKD0-BtvPfCfwv9_m:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4c52771243c7298e904cb7fc126ba4ba1006f22f/src/include/librpma.h#L66)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> lookup for a local device
> ```
lookup for device based given on local address

...
lookup for device based on given remote address
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/414)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[src/include/librpma.h, line 66 at r5](https://reviewable.io/reviews/pmem/rpma/414#-MHkc5cC9nahUfv1_s8V:-MHkc5cD51g29jlGQ__z:bc73rwa) ([raw file](https://github.com/pmem/rpma/blob/96e1e6322b47a681f2734b99c36b66f4e3b5e78a/src/include/librpma.h#L66)):*
> ```objc
>  * and message-based QP communication.
>  * Possible values of the 'type' argument:
>  * - RPMA_UTIL_IBV_CONTEXT_LOCAL - lookup for device
> ```

a device
___
*[src/include/librpma.h, line 67 at r5](https://reviewable.io/reviews/pmem/rpma/414#-MHkc7NE0RY8nwQBSJ8N:-MHkc7NE0RY8nwQBSJ8O:b-huuxs0) ([raw file](https://github.com/pmem/rpma/blob/96e1e6322b47a681f2734b99c36b66f4e3b5e78a/src/include/librpma.h#L67)):*
> ```objc
>  * Possible values of the 'type' argument:
>  * - RPMA_UTIL_IBV_CONTEXT_LOCAL - lookup for device
>  * based given on local address
> ```

on the local
___
*[src/include/librpma.h, line 68 at r5](https://reviewable.io/reviews/pmem/rpma/414#-MHkcBZY3bYCW5imTxIW:-MHkcBZY3bYCW5imTxIX:bc73rwa) ([raw file](https://github.com/pmem/rpma/blob/96e1e6322b47a681f2734b99c36b66f4e3b5e78a/src/include/librpma.h#L68)):*
> ```objc
>  * - RPMA_UTIL_IBV_CONTEXT_LOCAL - lookup for device
>  * based given on local address
>  * - RPMA_UTIL_IBV_CONTEXT_REMOTE - lookup for device
> ```

a device
___
*[src/include/librpma.h, line 69 at r5](https://reviewable.io/reviews/pmem/rpma/414#-MHkcEbH1VcgcVGqwgjP:-MHkcEbH1VcgcVGqwgjQ:b-v6fq1k) ([raw file](https://github.com/pmem/rpma/blob/96e1e6322b47a681f2734b99c36b66f4e3b5e78a/src/include/librpma.h#L69)):*
> ```objc
>  * based given on local address
>  * - RPMA_UTIL_IBV_CONTEXT_REMOTE - lookup for device
>  * based on given remote address
> ```

on the given remote address

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/414)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[src/include/librpma.h, line 67 at r5](https://reviewable.io/reviews/pmem/rpma/414#-MHkc7NE0RY8nwQBSJ8N:-MHkcYjBDGawaawKaVQz:btnt93h) ([raw file](https://github.com/pmem/rpma/blob/96e1e6322b47a681f2734b99c36b66f4e3b5e78a/src/include/librpma.h#L67)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

on the local
</blockquote></details>

on the given local

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/414)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/include/librpma.h, line 66 at r5](https://reviewable.io/reviews/pmem/rpma/414#-MHkc5cC9nahUfv1_s8V:-MHkip9d0gx2o503_TkK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/96e1e6322b47a681f2734b99c36b66f4e3b5e78a/src/include/librpma.h#L66)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

a device
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 67 at r5](https://reviewable.io/reviews/pmem/rpma/414#-MHkc7NE0RY8nwQBSJ8N:-MHkixiVEls-S_T-Rzzm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/96e1e6322b47a681f2734b99c36b66f4e3b5e78a/src/include/librpma.h#L67)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

on the given local
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 68 at r5](https://reviewable.io/reviews/pmem/rpma/414#-MHkcBZY3bYCW5imTxIW:-MHkiyzm2ZUmB9M3V7vX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/96e1e6322b47a681f2734b99c36b66f4e3b5e78a/src/include/librpma.h#L68)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

a device
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 69 at r5](https://reviewable.io/reviews/pmem/rpma/414#-MHkcEbH1VcgcVGqwgjP:-MHkj8HT05aGGISpI6wj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/96e1e6322b47a681f2734b99c36b66f4e3b5e78a/src/include/librpma.h#L69)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

on the given remote address
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/414#-:-MHkllzw2amH1Qb2auLo:bnfp4nl)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/414)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/414)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[src/include/librpma.h, line 58 at r6](https://reviewable.io/reviews/pmem/rpma/414#-MHoSCsB0q1uZTGHUUA0:-MHoSCsB0q1uZTGHUUA1:b-2lgi8r) ([raw file](https://github.com/pmem/rpma/blob/5d3ba4b56f72b3756d4c9c7fdd76fda6ccb40955/src/include/librpma.h#L58)):*
> ```
> dev
> ```
device to avoid shortcuts
or @janekmi, @ldorau - shall we use here full name device_context?
___
*[src/include/librpma.h, line 73 at r6](https://reviewable.io/reviews/pmem/rpma/414#-MHoSIb35t5IvRlfm2ei:-MHoSIb35t5IvRlfm2ej:b-lts2e) ([raw file](https://github.com/pmem/rpma/blob/5d3ba4b56f72b3756d4c9c7fdd76fda6ccb40955/src/include/librpma.h#L73)):*
> ```
> dev
> ```
device

**Pull request merged**
