### PR TITLE
examples: make common functions accept conn_cfg

### PR DESCRIPTION
**Pull request by yangx-jy**
pass conn_cfg into client_connect() and server_accept_connection().

Signed-off-by: Xiao Yang <yangx.jy@fujitsu.com>

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1067)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> ```
> cfg
> ```
Are you going to add any example with not NULL configuration?

> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1067#-:-Ma94HDU-fINmJLKHcpn:bevx9g9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by yangx-jy — COMMENTED** [review]
Yes.

In example-09, I am going to use the seperate receiving CQ which needs custom configuration, like this:
```
struct rpma_conn_cfg *cfg = NULL;
ret = rpma_conn_cfg_new(&cfg);

ret = rpma_conn_cfg_set_rcq_size(cfs, 10);

ret = client_connect(peer, addr, port, NULL, &conn)
``` 

Besides, I will implement the seperate receiveing CQ after #1035 is merged.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1067#-:-Ma97MraAF9U5pfPFDkK:b-v4i17k)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by grom72 — COMMENTED** [review]
Do we need this on the client-side or on the server-side?
We have seen an issue (and need for a separate queue) in the GPSPM server.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1067#-:-MaCE2IwC3xpz75xNmZB:b-6tqhnr)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by yangx-jy — COMMENTED** [review]
Hi @grom72 

In the example, I plan to use a separate queue on both client-side and server-side.  I am not sure if my idea is appropriate.
Could you tell me what the issue is?（i.e. the detailed description of the issue）

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1067#-:-MaCLOjh129fc8Q7USpW:b-vl3ff5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by grom72 — COMMENTED** [review]
Hi @yangx-jy 
we implemented software queue in GPSPM fio engine: ```https://github.com/pmem/fio/blob/aof/engines/librpma_gpspm.c``` to avoid possible deadlock in send and receiv completion processing.
```
        if (cmpl->op == RPMA_OP_RECV)
		++sd->msg_queued_nr;
	else if (cmpl->op == RPMA_OP_SEND)
		++sd->msg_sqe_available;
```
This could be implemented in HW if we have separate completion queues.
There is a plan to adjust the GPSPM example as soon as we have completion queues separated.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1067#-:-MaRfXjMDT5jPSWZr7Mi:b-qcrzd9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Comment by yangx-jy** [comment]
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1067#-MbGwK_W7SXGoiKHUtkH:-MbGwK_W7SXGoiKHUtkI:b-sjh75a) (no related file):*
Hi @ldorau @janekmi

Is it OK to merge the PR first? #1080 depends on it and I put it into #1080 for now.

---

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1067#-:-MbKOU6M6eFWmdMqvgph:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1067#-MbGwK_W7SXGoiKHUtkH:-MbKNnRNCIEt4qGizARW:bn8hzc1) (no related file):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi @ldorau @janekmi

Is it OK to merge the PR first? #1080 depends on it and I put it into #1080 for now.
</blockquote></details>

It is OK for me.

---

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1067)* status: all files reviewed, 5 unresolved discussions (waiting on @yangx-jy)

___
*[examples/common/common-conn.h, line 56 at r1](https://reviewable.io/reviews/pmem/rpma/1067#-MbtsMko4_ovY9MHSkKp:-MbtsMko4_ovY9MHSkKq:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/bb1cc54b832e402ab98b29b5deeb57e103a31e35/examples/common/common-conn.h#L56)):*
> ```objc
> int client_connect(struct rpma_peer *peer, const char *addr, const char *port,
> 		struct rpma_conn_cfg *cfg,
> 		struct rpma_conn_private_data *pdata,
> ```

.
___
*[examples/common/common-conn.h, line 61 at r1](https://reviewable.io/reviews/pmem/rpma/1067#-MbtsNTt4__ujMibTMhO:-MbtsNTt4__ujMibTMhP:b-xby2pb) ([raw file](https://github.com/pmem/rpma/blob/bb1cc54b832e402ab98b29b5deeb57e103a31e35/examples/common/common-conn.h#L61)):*
> ```objc
> int server_accept_connection(struct rpma_ep *ep, struct rpma_conn_cfg *cfg,
> 		struct rpma_conn_private_data *pdata,
> 		struct rpma_conn **conn_ptr);
> ```

.

If you don't mind.
___
*[examples/common/common-conn.c, line 66 at r1](https://reviewable.io/reviews/pmem/rpma/1067#-Mbts0jJEfLunEqlis52:-Mbts0jJEfLunEqlis53:b3deqza) ([raw file](https://github.com/pmem/rpma/blob/bb1cc54b832e402ab98b29b5deeb57e103a31e35/examples/common/common-conn.c#L66)):*
> ```C
> client_connect(struct rpma_peer *peer, const char *addr, const char *port,
> 		struct rpma_conn_cfg *cfg,
> 		struct rpma_conn_private_data *pdata,
> ```

These two lines can easily go together.
___
*[examples/common/common-conn.c, line 110 at r1](https://reviewable.io/reviews/pmem/rpma/1067#-MbtsJ2MDoYDJ1tqEhaM:-MbtsJ2MDoYDJ1tqEhaN:b-xby2pb) ([raw file](https://github.com/pmem/rpma/blob/bb1cc54b832e402ab98b29b5deeb57e103a31e35/examples/common/common-conn.c#L110)):*
> ```C
> server_accept_connection(struct rpma_ep *ep, struct rpma_conn_cfg *cfg,
> 		struct rpma_conn_private_data *pdata,
> 		struct rpma_conn **conn_ptr)
> ```

.

If you don't mind.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1067#-:-Mbu33R9EzkxChJBqEZf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

___
*[examples/common/common-conn.h, line 61 at r1](https://reviewable.io/reviews/pmem/rpma/1067#-MbtsNTt4__ujMibTMhO:-Mbu3-kGBAr111qLwMvr:b-16147z) ([raw file](https://github.com/pmem/rpma/blob/bb1cc54b832e402ab98b29b5deeb57e103a31e35/examples/common/common-conn.h#L61)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

It will cause 'line > 80 characters' error.
</blockquote></details>

You are right. My bad.
___
*[examples/common/common-conn.c, line 110 at r1](https://reviewable.io/reviews/pmem/rpma/1067#-MbtsJ2MDoYDJ1tqEhaM:-Mbu2uVdEpicT-wpM4Vi:b-16147z) ([raw file](https://github.com/pmem/rpma/blob/bb1cc54b832e402ab98b29b5deeb57e103a31e35/examples/common/common-conn.c#L110)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

It will cause 'line > 80 characters' error.
</blockquote></details>

You are right. My bad.

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1067)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Pull request merged**
