### PR TITLE
examples: fix numeric overflow

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/354)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/354)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[examples/06-multiple-connections/server.c, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/354#-MGO0dx39oB8HJd54Un0:-MGO0dx39oB8HJd54Un1:b9wze81) ([raw file](https://github.com/pmem/rpma/blob/a519cf62fe32c39b42f541fcbf10669dd90b70ec/examples/06-multiple-connections/server.c#L39)):*
> ```
> uint8_t
> ```
what is wrong with int?
can we use more simple types like char? short?

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/354)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/354)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[examples/06-multiple-connections/server.c, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/354#-MGO0dx39oB8HJd54Un0:-MGOFmuh--WUix6zmYEu:b-aq6ahr) ([raw file](https://github.com/pmem/rpma/blob/a519cf62fe32c39b42f541fcbf10669dd90b70ec/examples/06-multiple-connections/server.c#L39)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> uint8_t
> ```
what is wrong with int?
can we use more simple types like char? short?
</blockquote></details>

@osalyk what is the problem here?

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/354)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[examples/06-multiple-connections/server.c, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/354#-MGO0dx39oB8HJd54Un0:-MGbCoLP9-GHZ4mvUQs8:bpwnemi) ([raw file](https://github.com/pmem/rpma/blob/a519cf62fe32c39b42f541fcbf10669dd90b70ec/examples/06-multiple-connections/server.c#L39)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@osalyk what is the problem here?
</blockquote></details>

To calculate clnt->offset, I perform (size_t)(MAX_NAME_SIZE) * i.
clnt->client_id = i;

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/354)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[examples/06-multiple-connections/server.c, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/354#-MGO0dx39oB8HJd54Un0:-MGcTxbp56ZOrH3hhBrq:b9597ln) ([raw file](https://github.com/pmem/rpma/blob/a519cf62fe32c39b42f541fcbf10669dd90b70ec/examples/06-multiple-connections/server.c#L39)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

To calculate clnt->offset, I perform (size_t)(MAX_NAME_SIZE) * i.
clnt->client_id = i;
</blockquote></details>

The actual problem is:
"*The result of expression: '32\*i' generates 4-byte type while casting to a bigger size of 8-byte*",
so the correct fix is the following:
```
		clnt->offset = (size_t)MAX_NAME_SIZE * (size_t)i;
```
There is no need to change any types.
___
*[examples/06-multiple-connections/server.c, line 125 at r1](https://reviewable.io/reviews/pmem/rpma/354#-MGcVMtD3wTGaI8dF-2S:-MGcVMtD3wTGaI8dF-2T:b-a7m4h1) ([raw file](https://github.com/pmem/rpma/blob/a519cf62fe32c39b42f541fcbf10669dd90b70ec/examples/06-multiple-connections/server.c#L125)):*
> ```C
> 		clnt->client_id = i;
> 		clnt->svr = svr;
> 		clnt->offset = (size_t)(MAX_NAME_SIZE) * i;
> ```

```
		clnt->offset = (size_t)MAX_NAME_SIZE * (size_t)i;
```

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/354)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/354)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/354)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[examples/06-multiple-connections/server.c, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/354#-MGO0dx39oB8HJd54Un0:-MGgECND1alQftKqBjhs:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a519cf62fe32c39b42f541fcbf10669dd90b70ec/examples/06-multiple-connections/server.c#L39)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The actual problem is:
"*The result of expression: '32\*i' generates 4-byte type while casting to a bigger size of 8-byte*",
so the correct fix is the following:
```
		clnt->offset = (size_t)MAX_NAME_SIZE * (size_t)i;
```
There is no need to change any types.
</blockquote></details>

Done.
___
*[examples/06-multiple-connections/server.c, line 125 at r1](https://reviewable.io/reviews/pmem/rpma/354#-MGcVMtD3wTGaI8dF-2S:-MGgE-Y39CgEL5d4YGAt:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a519cf62fe32c39b42f541fcbf10669dd90b70ec/examples/06-multiple-connections/server.c#L125)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
		clnt->offset = (size_t)MAX_NAME_SIZE * (size_t)i;
```
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/354)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/354#-:-MGhH9SCDcYLeXWdMhrQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/354#-:-MGhJl3G6gE4xgjz5yF0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/354#-:-MGhKm4B6N2b6biYYowI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
