### PR TITLE
tools: perf: introduce common series params

### PR DESCRIPTION
**Pull request by janekmi**
Requires:

- [x] #1246 

This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1249)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1249#-:-Mi_nPI4-3196TY2updk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1249)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/figure.py, line 124 at r1](https://reviewable.io/reviews/pmem/rpma/1249#-MiaDC__2yerht4IHXOF:-MiaDC_aEQdtP4BhaZih:b-ruyt1v) ([raw file](https://github.com/pmem/rpma/blob/b8ee4e28fcdcd68a7712f8a19cb15c1f25cf9af0/tools/perf/lib/figure.py#L124)):*
> ```
> '{}B'
> ```

What is `B` for here?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1249)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/lib/figure.py, line 124 at r1](https://reviewable.io/reviews/pmem/rpma/1249#-MiaDC__2yerht4IHXOF:-MiaNG2S-xm1icRH1sub:b6k4nlw) ([raw file](https://github.com/pmem/rpma/blob/b8ee4e28fcdcd68a7712f8a19cb15c1f25cf9af0/tools/perf/lib/figure.py#L124)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> '{}B'
> ```

What is `B` for here?
</blockquote></details>

'B' stands for bytes.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1249)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/figure.py, line 124 at r1](https://reviewable.io/reviews/pmem/rpma/1249#-MiaDC__2yerht4IHXOF:-MiaYWSkAr2A_MOj8Xw_:b32w0x) ([raw file](https://github.com/pmem/rpma/blob/b8ee4e28fcdcd68a7712f8a19cb15c1f25cf9af0/tools/perf/lib/figure.py#L124)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

'B' stands for bytes.
</blockquote></details>

OK

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1249)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1249)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1249#-Mifuh3d-08toI4CinJX:-Mifuh3d-08toI4CinJY:b-d20lcy) (no related file):*
I have tested this PR and got this:

```
$ ./report_figures.py --bench report_python/bench.json --report ./report_python/report.json
Traceback (most recent call last):
  File "/mnt/files/repos/rpma/tools/perf/./report_figures.py", line 45, in <module>
    main()
  File "/mnt/files/repos/rpma/tools/perf/./report_figures.py", line 30, in main
    bench = Bench.carry_on(args.bench)
  File "/mnt/files/repos/rpma/tools/perf/lib/bench.py", line 45, in carry_on
    figures = [Figure(f, result_dir) for f in bench['figures']]
  File "/mnt/files/repos/rpma/tools/perf/lib/bench.py", line 45, in <listcomp>
    figures = [Figure(f, result_dir) for f in bench['figures']]
  File "/mnt/files/repos/rpma/tools/perf/lib/figure.py", line 47, in __init__
    self.common_params = data['json'][self.key]['common_params']
KeyError: 'common_params'
```

---

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1249)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1249#-Mifuh3d-08toI4CinJX:-MiufZKL7ruW0hPtC23R:bu7ggx3) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I have tested this PR and got this:

```
$ ./report_figures.py --bench report_python/bench.json --report ./report_python/report.json # _REP_1
Traceback (most recent call last):
  File "/mnt/files/repos/rpma/tools/perf/./report_figures.py", line 45, in <module>
    main()
  File "/mnt/files/repos/rpma/tools/perf/./report_figures.py", line 30, in main
    bench = Bench.carry_on(args.bench)
  File "/mnt/files/repos/rpma/tools/perf/lib/bench.py", line 45, in carry_on
    figures = [Figure(f, result_dir) for f in bench['figures']]
  File "/mnt/files/repos/rpma/tools/perf/lib/bench.py", line 45, in <listcomp>
    figures = [Figure(f, result_dir) for f in bench['figures']]
  File "/mnt/files/repos/rpma/tools/perf/lib/figure.py", line 47, in __init__
    self.common_params = data['json'][self.key]['common_params']
KeyError: 'common_params'
```

</blockquote></details>

This PR changes the JSON "schema" so it now requires a "common_params" field provided. After this change you have either to collect benchmarks one more time or use the following command to regenerate the key JSON files e.g.:

```sh
./report_figures.py --bench ./report_test/bench.json --regenerate_jsons
```

Ref: #1250

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1249)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1249#-Mifuh3d-08toI4CinJX:-Miujk_50jjXiHxRkVHK:bc16daj) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This PR changes the JSON "schema" so it now requires a "common_params" field provided. After this change you have either to collect benchmarks one more time or use the following command to regenerate the key JSON files e.g.:

```sh
./report_figures.py --bench ./report_test/bench.json --regenerate_jsons
```

Ref: #1250
</blockquote></details>

```
$ ./report_figures.py --bench ./report_python/bench.json --regenerate_jsons
Traceback (most recent call last):
  File "/mnt/files/repos/rpma/tools/perf/./report_figures.py", line 40, in <module>
    main()
  File "/mnt/files/repos/rpma/tools/perf/./report_figures.py", line 31, in main
    bench = Bench.carry_on(args.bench)
  File "/mnt/files/repos/rpma/tools/perf/lib/bench.py", line 45, in carry_on
    figures = [Figure(f, result_dir) for f in bench['figures']]
  File "/mnt/files/repos/rpma/tools/perf/lib/bench.py", line 45, in <listcomp>
    figures = [Figure(f, result_dir) for f in bench['figures']]
  File "/mnt/files/repos/rpma/tools/perf/lib/figure.py", line 46, in __init__
    self.common_params = data['json'][self.key]['common_params']
KeyError: 'common_params'
```

---

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1249)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[tools/perf/lib/figure.py, line 137 at r1](https://reviewable.io/reviews/pmem/rpma/1249#-MiaGGfO0E0wpApANOcF:-MiumVeM19T2iAXOQOd4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b8ee4e28fcdcd68a7712f8a19cb15c1f25cf9af0/tools/perf/lib/figure.py#L137)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>             params = {key: rows[0].get(key, value['default'])
>                       for key, value in Figure.COMMON_PARAMS.items()}
>         for row in rows:
>             params = {key: value for key, value in params.items()
>                       if value == row.get(key,
>                                           Figure.COMMON_PARAMS[key]['default'])}
> ```

Could you add a comment what both `params = ` do?
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1249)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ldorau and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1249#-Mifuh3d-08toI4CinJX:-Miun-wb2DnM62Awpksa:b72lu84) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
$ ./report_figures.py --bench ./report_python/bench.json --regenerate_jsons
Traceback (most recent call last):
  File "/mnt/files/repos/rpma/tools/perf/./report_figures.py", line 40, in <module>
    main()
  File "/mnt/files/repos/rpma/tools/perf/./report_figures.py", line 31, in main
    bench = Bench.carry_on(args.bench)
  File "/mnt/files/repos/rpma/tools/perf/lib/bench.py", line 45, in carry_on
    figures = [Figure(f, result_dir) for f in bench['figures']]
  File "/mnt/files/repos/rpma/tools/perf/lib/bench.py", line 45, in <listcomp>
    figures = [Figure(f, result_dir) for f in bench['figures']]
  File "/mnt/files/repos/rpma/tools/perf/lib/figure.py", line 46, in __init__
    self.common_params = data['json'][self.key]['common_params']
KeyError: 'common_params'
```

</blockquote></details>

Please try again.

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1249)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1249#-Mifuh3d-08toI4CinJX:-MiuqeK-2zL6zEZPVtWq:b-8l3pe7) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please try again.
</blockquote></details>

I tried again:
- on PR #1249:  `report_figures.py: error: unrecognized arguments: --regenerate_jsons`
- on PR #1250:  `KeyError: 'common_params'`

---

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1249)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1249#-:-Miuyef5EaETRUR-IRA_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1249#-Mifuh3d-08toI4CinJX:-Miuyb5oCOyRTzn33srn:bno969i) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I tried again:
- on PR #1249:  `report_figures.py: error: unrecognized arguments: --regenerate_jsons`
- on PR #1250:  `KeyError: 'common_params'`
</blockquote></details>

It is OK now.

---

**Pull request merged**
