### PR TITLE
common: add new versions of OSes to nightly CI builds

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1257)

### CODE REVIEW

**Comment by ldorau** [comment]
Builds pass:
https://github.com/ldorau/rpma/actions/runs/1197022777

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1257#-:-MiedLk4EFXglyD928gC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1257)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1257#-MiegHZ0C-V-rgNBkfNo:-MiegHZ14FyuoM90C2ID:b-xl5pzs) (no related file):*
1. How about the latest Ubuntu?
2. When we are sure the latest Ubuntu and Debian works just fine I think we should update the per-PR builds.

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1257)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1257#-MiegHZ0C-V-rgNBkfNo:-Mif-37PC6fFATKW8MBh:b-tsubwv) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

1. How about the latest Ubuntu?
2. When we are sure the latest Ubuntu and Debian works just fine I think we should update the per-PR builds.
</blockquote></details>

1. Ubuntu 21.04 is tested as Ubuntu rolling now. Do you want me to add 21.04 ?
2. OK

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1257)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1257#-MiegHZ0C-V-rgNBkfNo:-Mif1jBkAfTjliQ_rEsW:bf2k7zx) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

1. Ubuntu 21.04 is tested as Ubuntu rolling now. Do you want me to add 21.04 ?
2. OK
</blockquote></details>

Ubuntu 21.04 added.

Done.

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1257)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1257#-MiegHZ0C-V-rgNBkfNo:-Mif3YCdE4lafAb1yBCc:b-8jopga) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Ubuntu 21.04 added.

Done.


</blockquote></details>

See: https://github.com/pmem/rpma/pull/1259

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1257)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1257#-MiegHZ0C-V-rgNBkfNo:-Mif68sl50oEQgYX4YzY:bb6un1j) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

See: https://github.com/pmem/rpma/pull/1259
</blockquote></details>

Done

---

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1257#-:-MifMD_BAFCnxF5lIAyP:bnfp4nl)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1257#-:-Mitl1_w-TRYuSwaVdL4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
