### PR TITLE
rpma: improve examples/README.md file

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1971)

### CODE REVIEW

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1971)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1971)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi and @Patryk717)

___
*[`examples/README.md` line 22 at r1](https://reviewable.io/reviews/pmem/rpma/1971#-N8cV0f95nDueXB7IEW1:-N8cV0f95nDueXB7IEW2:by2b4e8) ([raw file](https://github.com/pmem/rpma/blob/3ddace94dceddd0abd828e0dcbf5b0cc07cf82ba/examples/README.md#L22)):*
> ```Markdown
> 
> 
> ## Running examples on a configured RDMA-capable network interface
> ```

One empty line in between should be enough, I think.



_Code quote:_
```Markdown
**Note**: for more information please check out [this section](../INSTALL.md#for-some-examples-you-also-need).


## Running examples on a configured RDMA-capable network interface
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1971)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau and @Patryk717)

___
*[`examples/README.md` line 22 at r1](https://reviewable.io/reviews/pmem/rpma/1971#-N8cV0f95nDueXB7IEW1:-N8cXKPF4R31lHyld3Bd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3ddace94dceddd0abd828e0dcbf5b0cc07cf82ba/examples/README.md#L22)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

One empty line in between should be enough, I think.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1971#-:-N8cXSnnBvzALeZw1wdZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1971#-:-N8chtFuAg1NyZv11uFQ:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1971)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
