### PR TITLE
test: fix error handling in the rpma_utils-get_ibv_context.c test

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/857)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/857)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 93 at r1](https://reviewable.io/reviews/pmem/rpma/857#-MSldp4B1QSno7FTCr_A:-MSldp4C4y1E7d7hZt-S:b-flv1si) ([raw file](https://github.com/pmem/rpma/blob/7cdfbcd79ae6e1e9f2004ae69f85907dfa291bb7/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L93)):*
> ```C
> 		pthread_join(p_threads[i], NULL);
> 
> 	return 0;
> ```

It seems I was also too tired to notice what we have done. :laughing:
___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 94 at r1](https://reviewable.io/reviews/pmem/rpma/857#-MSldWymCpUeXvJ9Nbrq:-MSldWymCpUeXvJ9Nbrr:b-xblgm2) ([raw file](https://github.com/pmem/rpma/blob/519eaa455187ef98fc076c3cdd709e944c2b33b9/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L94)):*
> ```C
> 			thread_num = i;
> 			/* return -1 on error */
> 			ret = -1;
> ```

Without break it will be overwritten by the next `pthread_create()` call.
___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 98 at r1](https://reviewable.io/reviews/pmem/rpma/857#-MSldgIw7DQ1mybwtIat:-MSldgIw7DQ1mybwtIau:b-s3l7mo) ([raw file](https://github.com/pmem/rpma/blob/519eaa455187ef98fc076c3cdd709e944c2b33b9/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L98)):*
> ```C
> 	}
> 
> 	for (i = thread_num - 1; i >= 0; i--)
> ```

What if an error happened during initialization?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/857)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 94 at r1](https://reviewable.io/reviews/pmem/rpma/857#-MSldWymCpUeXvJ9Nbrq:-MSlfHSKBCbyKdIzQBZW:bm4extq) ([raw file](https://github.com/pmem/rpma/blob/519eaa455187ef98fc076c3cdd709e944c2b33b9/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L94)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Without break it will be overwritten by the next `pthread_create()` call.
</blockquote></details>

O yes, I was sure it was already there :-)
___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 98 at r1](https://reviewable.io/reviews/pmem/rpma/857#-MSldgIw7DQ1mybwtIat:-MSlfTkyBGuyNc375Go-:b-jza791) ([raw file](https://github.com/pmem/rpma/blob/519eaa455187ef98fc076c3cdd709e944c2b33b9/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L98)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

What if an error happened during initialization?
</blockquote></details>

The already created threads will be joined.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/857)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 94 at r1](https://reviewable.io/reviews/pmem/rpma/857#-MSldWymCpUeXvJ9Nbrq:-MSlf_n_D5Oe0TEW4ZXb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/519eaa455187ef98fc076c3cdd709e944c2b33b9/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L94)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

O yes, I was sure it was already there :-)
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/857)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 98 at r1](https://reviewable.io/reviews/pmem/rpma/857#-MSldgIw7DQ1mybwtIat:-MSll6RB-qele-Kwg3TE:butj5sp) ([raw file](https://github.com/pmem/rpma/blob/519eaa455187ef98fc076c3cdd709e944c2b33b9/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L98)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The already created threads will be joined.
</blockquote></details>

The loop goes over all of the threads. They are allocated with `malloc()` so they are not even zero-initialized.
Are you sure it won't crash?
For sure we should at least explicitly ignore the join results e.g. `(void) pthread_join(p_threads[i], NULL);`.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/857)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 98 at r1](https://reviewable.io/reviews/pmem/rpma/857#-MSldgIw7DQ1mybwtIat:-MSlwLZsBeICxLKSvPA4:bj7v7y7) ([raw file](https://github.com/pmem/rpma/blob/519eaa455187ef98fc076c3cdd709e944c2b33b9/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L98)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The loop goes over all of the threads. They are allocated with `malloc()` so they are not even zero-initialized.
Are you sure it won't crash?
For sure we should at least explicitly ignore the join results e.g. `(void) pthread_join(p_threads[i], NULL);`.
</blockquote></details>

1) The loop does not go over all of the threads, but only over the initialized ones, see above:

```
			/*
			 * Set thread_num to the number
			 * of already created threads
			 * to join them below.
			 */
			thread_num = i;
```

2) They are zeroed - they are allocated with calloc() now - another PR has changed that in meantime :-)
3) I have added explicitly ignoring the result of join().

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/857)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 98 at r1](https://reviewable.io/reviews/pmem/rpma/857#-MSldgIw7DQ1mybwtIat:-MSlxQLX4NL3qtwKQscm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/519eaa455187ef98fc076c3cdd709e944c2b33b9/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L98)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

1) The loop does not go over all of the threads, but only over the initialized ones, see above:

```
			/*
			 * Set thread_num to the number
			 * of already created threads
			 * to join them below.
			 */
			thread_num = i;
```

2) They are zeroed - they are allocated with calloc() now - another PR has changed that in meantime :-)
3) I have added explicitly ignoring the result of join().
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/857#-:-MSlxl0n-RTU5CNnM43C:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/857#-:-MSmPRjR5vR5U7sUQLqi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
