### PR TITLE
tools: extend sleep interval between spawning server and client

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/742)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/742)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/rpma_fio_bench.sh, line 210 at r1](https://reviewable.io/reviews/pmem/rpma/742#-MQus0Nb7hF4C1nZOjar:-MQus0Nc76klJI6D1T42:b-46xl77) ([raw file](https://github.com/pmem/rpma/blob/00d9be0108663a599e7237b5cbd244d40f44ac0c/tools/rpma_fio_bench.sh#L210)):*
> ```
> sleep 10
> ```

Please add a message before, sth like:

`echo "Waiting 10 sec for server to start..."`

so that a user doesn't have to think what is going on.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/742)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/rpma_fio_bench.sh, line 210 at r1](https://reviewable.io/reviews/pmem/rpma/742#-MQus0Nb7hF4C1nZOjar:-MQvH5ZQD05b3VUu95cS:b751blq) ([raw file](https://github.com/pmem/rpma/blob/00d9be0108663a599e7237b5cbd244d40f44ac0c/tools/rpma_fio_bench.sh#L210)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Do we need also a delay before the server is started? (To allow previously started fio to shutdown fully)
</blockquote></details>

I do not think so.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/742)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/rpma_fio_bench.sh, line 210 at r1](https://reviewable.io/reviews/pmem/rpma/742#-MQus0Nb7hF4C1nZOjar:-MQvnJMuBXX4ReNipSMj:byuwyp3) ([raw file](https://github.com/pmem/rpma/blob/00d9be0108663a599e7237b5cbd244d40f44ac0c/tools/rpma_fio_bench.sh#L210)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I do not think so.
</blockquote></details>

Just in case the previous fio has not shut down all connections

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/742#-:-MQvnUmi88OoujzFkEol:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/742)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/rpma_fio_bench.sh, line 210 at r1](https://reviewable.io/reviews/pmem/rpma/742#-MQus0Nb7hF4C1nZOjar:-MQvsFng6rs5VF3P0cfp:bmkl4v3) ([raw file](https://github.com/pmem/rpma/blob/00d9be0108663a599e7237b5cbd244d40f44ac0c/tools/rpma_fio_bench.sh#L210)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Just in case the previous fio has not shut down all connections
</blockquote></details>

Anyway I recall the original issue:

Please add a message before, sth like:

`echo "Waiting 10 sec for server to start..."`

so that a user doesn't have to think what is going on.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/742)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/rpma_fio_bench.sh, line 210 at r1](https://reviewable.io/reviews/pmem/rpma/742#-MQus0Nb7hF4C1nZOjar:-MQvzutG-232N6bU4pRk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/00d9be0108663a599e7237b5cbd244d40f44ac0c/tools/rpma_fio_bench.sh#L210)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Anyway I recall the original issue:

Please add a message before, sth like:

`echo "Waiting 10 sec for server to start..."`

so that a user doesn't have to think what is going on.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/742#-:-MQw3iMUDz2asvILnorw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
