### PR TITLE
doc: BIOS settings

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/608)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/608)* status: all files reviewed, 8 unresolved discussions (waiting on @osalyk)

___
*[documentation/perf-tuning-latency.md, line 18 at r1](https://reviewable.io/reviews/pmem/rpma/608#-MNTYiLh3d-85lhV9_qx:-MNTYiLh3d-85lhV9_qy:b8e64s8) ([raw file](https://github.com/pmem/rpma/blob/588c2dc05a64fe527297fb2dd023cd83cda841fe/documentation/perf-tuning-latency.md#L18)):*
> ```Markdown
> ## BIOS settings
> 
> **XXX**: Can we describe this in any greater detail?
> ```

Please drop this line.
___
*[documentation/perf-tuning-latency.md, line 21 at r1](https://reviewable.io/reviews/pmem/rpma/608#-MNTWUUJ5IHTkwq6jY8d:-MNTWUUJ5IHTkwq6jY8e:b-z9gro0) ([raw file](https://github.com/pmem/rpma/blob/588c2dc05a64fe527297fb2dd023cd83cda841fe/documentation/perf-tuning-latency.md#L21)):*
> ```Markdown
> 
> * Platform and CPU related [[1.1]][opt-part-1]
>     * Disable lower CPU power states: C-states[[1.2]][power-states], C1E, and memory and PCI-e power saving states. Settings vary from vendor to vendor so some of them may not be available for you.
> ```

Please add to this line: `... available for you e.g.:`
___
*[documentation/perf-tuning-latency.md, line 22 at r1](https://reviewable.io/reviews/pmem/rpma/608#-MNTX71e7REHalWRdiHn:-MNTX71e7REHalWRdiHo:b-lcklyc) ([raw file](https://github.com/pmem/rpma/blob/588c2dc05a64fe527297fb2dd023cd83cda841fe/documentation/perf-tuning-latency.md#L22)):*
> ```Markdown
> * Platform and CPU related [[1.1]][opt-part-1]
>     * Disable lower CPU power states: C-states[[1.2]][power-states], C1E, and memory and PCI-e power saving states. Settings vary from vendor to vendor so some of them may not be available for you.
>       * Power n Performance - CPU Power and Performance Policy - **Performance**
> ```

This bullet should go to the second point aka other settings. Put it as first on that list.
___
*[documentation/perf-tuning-latency.md, line 23 at r1](https://reviewable.io/reviews/pmem/rpma/608#-MNTXQvC3pTX30FV0lXq:-MNTXQvC3pTX30FV0lXr:b-ljll6n) ([raw file](https://github.com/pmem/rpma/blob/588c2dc05a64fe527297fb2dd023cd83cda841fe/documentation/perf-tuning-latency.md#L23)):*
> ```Markdown
>     * Disable lower CPU power states: C-states[[1.2]][power-states], C1E, and memory and PCI-e power saving states. Settings vary from vendor to vendor so some of them may not be available for you.
>       * Power n Performance - CPU Power and Performance Policy - **Performance**
>       * Power n Performance - Package C-State - **0x0 (C0/C1 state)**
> ```

The hexadecimal is not needed here. Please remove `0x0`. Maybe it is ok to just leave `C0/C1 state`.
___
*[documentation/perf-tuning-latency.md, line 25 at r1](https://reviewable.io/reviews/pmem/rpma/608#-MNTXpqAA9vq1wtn802S:-MNTXpqAA9vq1wtn802T:bhlic77) ([raw file](https://github.com/pmem/rpma/blob/588c2dc05a64fe527297fb2dd023cd83cda841fe/documentation/perf-tuning-latency.md#L25)):*
> ```Markdown
>       * Power n Performance - Package C-State - **0x0 (C0/C1 state)**
>       * Power n Performance - C1E - **Disabled**
>     * Check for other settings that might influence performance. This varies greatly by OEM, but should include anything power related, such as fan speed settings (more is better).
> ```

`... (more is better) e.g.:`
___
*[documentation/perf-tuning-latency.md, line 27 at r1](https://reviewable.io/reviews/pmem/rpma/608#-MNTYOGC76Sb5R-T1qGJ:-MNTYOGC76Sb5R-T1qGK:b-rdspzy) ([raw file](https://github.com/pmem/rpma/blob/588c2dc05a64fe527297fb2dd023cd83cda841fe/documentation/perf-tuning-latency.md#L27)):*
> ```Markdown
>     * Check for other settings that might influence performance. This varies greatly by OEM, but should include anything power related, such as fan speed settings (more is better).
>       * Memory Configuration - Average Power Budget (in mW) **15 mW = 0x3A98**, **18 mW = 0x4650**
>       * Memory Configuration - NVM Performance Setting - **Latency Optimized**
> ```

These two memory-related should go as PMem-related below.
___
*[documentation/perf-tuning-latency.md, line 28 at r1](https://reviewable.io/reviews/pmem/rpma/608#-MNTYXFe59-Wtqd4X7DZ:-MNTYXFf8CDyoB-oDkpp:bxfsczk) ([raw file](https://github.com/pmem/rpma/blob/588c2dc05a64fe527297fb2dd023cd83cda841fe/documentation/perf-tuning-latency.md#L28)):*
> ```Markdown
>       * Memory Configuration - Average Power Budget (in mW) **15 mW = 0x3A98**, **18 mW = 0x4650**
>       * Memory Configuration - NVM Performance Setting - **Latency Optimized**
>       * System Acoustic and Performance Configuration - Set Fan Profile - **0x1 (Performance)**
> ```

- no hex
- no parenthesis
___
*[documentation/perf-tuning-latency.md, line 38 at r1](https://reviewable.io/reviews/pmem/rpma/608#-MNTZ5bC1TR4MBfnGCv2:-MNTZ5bC1TR4MBfnGCv3:b68ilta) ([raw file](https://github.com/pmem/rpma/blob/588c2dc05a64fe527297fb2dd023cd83cda841fe/documentation/perf-tuning-latency.md#L38)):*
> ```Markdown
> * Disable any virtualization options.
>   * Processor Configuration - Intel(R) Virtualization Technology - **Disabled**
>   * Processor Configuration - Intel(R) Hyper-Threading Tech - **Disabled**
> ```

This one belongs to the point one line higher aka `hyper-threading`.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/608)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @janekmi)

___
*[documentation/perf-tuning-latency.md, line 18 at r1](https://reviewable.io/reviews/pmem/rpma/608#-MNTYiLh3d-85lhV9_qx:-MNT_n8d8lzB0T5i9Zmp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/588c2dc05a64fe527297fb2dd023cd83cda841fe/documentation/perf-tuning-latency.md#L18)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please drop this line.
</blockquote></details>

Done.
___
*[documentation/perf-tuning-latency.md, line 21 at r1](https://reviewable.io/reviews/pmem/rpma/608#-MNTWUUJ5IHTkwq6jY8d:-MNTa2Ly3ngjxhTETl_1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/588c2dc05a64fe527297fb2dd023cd83cda841fe/documentation/perf-tuning-latency.md#L21)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please add to this line: `... available for you e.g.:`
</blockquote></details>

Done.
___
*[documentation/perf-tuning-latency.md, line 22 at r1](https://reviewable.io/reviews/pmem/rpma/608#-MNTX71e7REHalWRdiHn:-MNTaGvYAI5wZDCCwGIW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/588c2dc05a64fe527297fb2dd023cd83cda841fe/documentation/perf-tuning-latency.md#L22)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This bullet should go to the second point aka other settings. Put it as first on that list.
</blockquote></details>

Done.
___
*[documentation/perf-tuning-latency.md, line 23 at r1](https://reviewable.io/reviews/pmem/rpma/608#-MNTXQvC3pTX30FV0lXq:-MNTaPCe0EJ1x0979GCv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/588c2dc05a64fe527297fb2dd023cd83cda841fe/documentation/perf-tuning-latency.md#L23)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The hexadecimal is not needed here. Please remove `0x0`. Maybe it is ok to just leave `C0/C1 state`.
</blockquote></details>

Done.
___
*[documentation/perf-tuning-latency.md, line 25 at r1](https://reviewable.io/reviews/pmem/rpma/608#-MNTXpqAA9vq1wtn802S:-MNTaVYV8l4VQX_FfzYT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/588c2dc05a64fe527297fb2dd023cd83cda841fe/documentation/perf-tuning-latency.md#L25)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`... (more is better) e.g.:`
</blockquote></details>

Done.
___
*[documentation/perf-tuning-latency.md, line 27 at r1](https://reviewable.io/reviews/pmem/rpma/608#-MNTYOGC76Sb5R-T1qGJ:-MNTahBPB-5GWVs3fZI3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/588c2dc05a64fe527297fb2dd023cd83cda841fe/documentation/perf-tuning-latency.md#L27)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

These two memory-related should go as PMem-related below.
</blockquote></details>

Done.
___
*[documentation/perf-tuning-latency.md, line 28 at r1](https://reviewable.io/reviews/pmem/rpma/608#-MNTYXFe59-Wtqd4X7DZ:-MNTanZq-3nOex0y5s_H:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/588c2dc05a64fe527297fb2dd023cd83cda841fe/documentation/perf-tuning-latency.md#L28)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

- no hex
- no parenthesis
</blockquote></details>

Done.
___
*[documentation/perf-tuning-latency.md, line 38 at r1](https://reviewable.io/reviews/pmem/rpma/608#-MNTZ5bC1TR4MBfnGCv2:-MNTb22nDL1Id4HIt6ZU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/588c2dc05a64fe527297fb2dd023cd83cda841fe/documentation/perf-tuning-latency.md#L38)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This one belongs to the point one line higher aka `hyper-threading`.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/608#-:-MNTe9vc5Y_5vaMxxYtp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/608)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[documentation/perf-tuning-latency.md, line 27 at r2](https://reviewable.io/reviews/pmem/rpma/608#-MNTeoTiC7oq0ksZ5TdP:-MNTeoTjAd8_bTMinrWv:b-sv9pse) ([raw file](https://github.com/pmem/rpma/blob/ea443dd042ed78115842844e90ab4de6dd9a5f3e/documentation/perf-tuning-latency.md#L27)):*
> ```
> **15 mW = 0x3A98**, **18 mW = 0x4650**
> ```

The hex values are used only in our BMC, the real values are used in the real BIOS, so IMHO just:
```
(for example) **15 mW** or **18 mW**
```
is better.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/608)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[documentation/perf-tuning-latency.md, line 27 at r2](https://reviewable.io/reviews/pmem/rpma/608#-MNTeoTiC7oq0ksZ5TdP:-MNThbto1heYOAu4U1sG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ea443dd042ed78115842844e90ab4de6dd9a5f3e/documentation/perf-tuning-latency.md#L27)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> **15 mW = 0x3A98**, **18 mW = 0x4650**
> ```

The hex values are used only in our BMC, the real values are used in the real BIOS, so IMHO just:
```
(for example) **15 mW** or **18 mW**
```
is better.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/608)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/608)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/608#-:-MNTlObWEIZvxckmBSI2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
