### PR TITLE
tools: report_bench.sh + READ BW

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/785)

### CODE REVIEW

**Comment by ldorau** [comment]
Why isn't it reviewable? ;-)

**Comment by ldorau** [comment]
:lgtm:

**Review by ldorau — APPROVED** [review]
LGTM

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/785)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/785#-:-MS2lNqgAoRgv-FawyQh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
