### PR TITLE
test: add missing unit tests for conn-flush

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/444)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
shall we also have tests:
flush__FLUSH_VISIBILITY_USAGE_EMPTY
and
flush__FLUSH_PERSISTENT_USAGE_EMPTY

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/444#-:-MI0xDk63RCxoDwlnKoq:b-akjr73)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
Here you are ;-)

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/444#-:-MI0zsCeCwaF4ry4bAuZ:b-5ye9c1)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:lgtm: 
:night_with_stars: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/444#-:-MI11QiC8Crvrlnk-vzL:b-qr4l58)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
@osalyk please review

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/444#-:-MI12-mJDPak7fC2bogB:bqeplii)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/444#-:-MI2kWAg-zNHW3xEtJOK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
