### PR TITLE
tools: fix part_write.json

### PR DESCRIPTION
**Pull request by osalyk**
Fixes a bug introduced in PR:
https://github.com/pmem/rpma/commit/296e4e3755079876f31afb5c8060fdf52d64a1ef

This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1596)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1596)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1596#-MwfeS2GDk2irEg5myq3:-MwfeS2GDk2irEg5myq4:b-40m524) (no related file):*
Can you explain what do we fix?

---

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1596)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1596#-MwfeS2GDk2irEg5myq3:-Mwg209c-tUxJRTQiRO0:b-wqftzj) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Can you explain what do we fix?
</blockquote></details>

Fixes a bug introduced in PR:
https://github.com/pmem/rpma/commit/296e4e3755079876f31afb5c8060fdf52d64a1ef

---

**Review by grom72 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1596)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1596#-:-Mwg5P2Z0ebjYVYtNQXD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by haichangsi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1596)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by haichangsi — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1596#-:-MwkCBDVAJXnKxxTV7BZ:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1596)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1596)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[-- commits, line 5 at r3](https://reviewable.io/reviews/pmem/rpma/1596#-Mwzu-7pAkULoZXz1h39):*
`FAIL: commit message exceeds 72 chars per line (commit_len)`



_Code quote:_
```
https://github.com/pmem/rpma/commit/296e4e3755079876f31afb5c8060fdf52d64a1ef
```
___
*[CHANGELOG.md, line 10 at r3](https://reviewable.io/reviews/pmem/rpma/1596#-MwzthFn88TsDfGv73FU:-MwzthFn88TsDfGv73FV:b-h3hmr3) ([raw file](https://github.com/pmem/rpma/blob/1ff932019db2370487de5f19a05b1c5a52a4586c/CHANGELOG.md#L10)):*
> ```Markdown
> ## [Unreleased]
> ### Fixed
> - part_write.json in the benchmarking framework
> ```

`the part_write.json template ...`



_Code quote:_
```Markdown
part_write.json in the benchmarking framework
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1596)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[-- commits, line 5 at r3](https://reviewable.io/reviews/pmem/rpma/1596#-Mwzu-7pAkULoZXz1h39):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`FAIL: commit message exceeds 72 chars per line (commit_len)`
</blockquote></details>

Done.
___
*[CHANGELOG.md, line 10 at r3](https://reviewable.io/reviews/pmem/rpma/1596#-MwzthFn88TsDfGv73FU:-MwzveAv0-yL5miK3ZmY:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1ff932019db2370487de5f19a05b1c5a52a4586c/CHANGELOG.md#L10)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`the part_write.json template ...`
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1596)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
