### PR TITLE
tools: perf: lib.format.FioFormat.parse()

### PR DESCRIPTION
**Pull request by janekmi**
Requires:

- [x] #1332

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1333)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1333)* status: 0 of 11 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1333)* status: 2 of 11 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 11 files at r1, 6 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1333#-:-Mp6AxI859H9qmOf3bOw:bnfp4nl)* status: 9 of 11 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1333)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1333#-:-Mp6JV_z9B-O6egHZr7K:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
