### PR TITLE
tools: ib_read.sh adjust scales

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/793)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/793)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/ib_read.sh, line 91 at r1](https://reviewable.io/reviews/pmem/rpma/793#-MS6gMFt8xL6MUUoTPdQ:-MS6gMFt8xL6MUUoTPdR:b-xx2oej) ([raw file](https://github.com/pmem/rpma/blob/981863ef4d8f740b3866b4591006919c510fba8c/tools/ib_read.sh#L91)):*
> ```
>  5001135 5001135 
> ```

These values should be proportional to the other.
___
*[tools/ib_read.sh, line 145 at r1](https://reviewable.io/reviews/pmem/rpma/793#-MS6gaWo8-grp9ReqZRH:-MS6gaWo8-grp9ReqZRI:b8p01v5) ([raw file](https://github.com/pmem/rpma/blob/981863ef4d8f740b3866b4591006919c510fba8c/tools/ib_read.sh#L145)):*
> ```
> 6002473 6002473 6002473
> ```

.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/793)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tools/ib_read.sh, line 91 at r1](https://reviewable.io/reviews/pmem/rpma/793#-MS6gMFt8xL6MUUoTPdQ:-MS77JtE7eFxTBRMD1wQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/981863ef4d8f740b3866b4591006919c510fba8c/tools/ib_read.sh#L91)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  5001135 5001135 
> ```

These values should be proportional to the other.
</blockquote></details>

Done.
___
*[tools/ib_read.sh, line 145 at r1](https://reviewable.io/reviews/pmem/rpma/793#-MS6gaWo8-grp9ReqZRH:-MS77Kls3na5URAKBhGe:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/981863ef4d8f740b3866b4591006919c510fba8c/tools/ib_read.sh#L145)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 6002473 6002473 6002473
> ```

.
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/793#-:-MS7AUmJ6V67tXN_5qzt:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/793)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/793#-:-MS7GWny5Rl6kGNWDWkw:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/793)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/793#-:-MS7OWRBA7ttw4cJETYE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
