### PR TITLE
rpma: Atomic write with IBV_SEND_FENCE flag

### PR DESCRIPTION
**Pull request by ewanglong**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/603)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/603)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

___
*[src/mr.c, line 171 at r1](https://reviewable.io/reviews/pmem/rpma/603#-MMo7VmN-6dOqAGXb9d5:-MMo7VmN-6dOqAGXb9d6:b-fec79h) ([raw file](https://github.com/pmem/rpma/blob/04078136cb52287db8c9aef702c9cc94ba4fbd50/src/mr.c#L171)):*
> ```C
> 	wr.send_flags = (flags & RPMA_F_COMPLETION_ON_SUCCESS) ?
> 		IBV_SEND_SIGNALED : 0;
> 	wr.send_flags |= (flags & RPMA_F_COMPLETION_ON_ERROR) ?
> ```

I do not understand the condition here. Can you elaborate?

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/603)* status: 0 of 9 files reviewed, 2 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[src/mr.h, line 41 at r2](https://reviewable.io/reviews/pmem/rpma/603#-MMtYrl27IJnBEiGK7PH:-MMtYrl3864O-rqrLB-p:bwhjtfl) ([raw file](https://github.com/pmem/rpma/blob/c8444a464e8e61a4ca6a0d2782c6f037dc082973/src/mr.h#L41)):*
> ```
> int fence
> ```
why is this not combined with other flags?

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/603)* status: 3 of 9 files reviewed, 2 unresolved discussions (waiting on @ewanglong)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 8 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/603)* status: all files reviewed, 7 unresolved discussions (waiting on @ewanglong)

___
*[src/mr.h, line 41 at r2](https://reviewable.io/reviews/pmem/rpma/603#-MMyBCEd2XxFPzAuZljZ:-MMyBCEd2XxFPzAuZlj_:b-597k5y) ([raw file](https://github.com/pmem/rpma/blob/c8444a464e8e61a4ca6a0d2782c6f037dc082973/src/mr.h#L41)):*
> ```
> int
> ```
bool is enough
___
*[src/mr.c, line 171 at r1](https://reviewable.io/reviews/pmem/rpma/603#-MMyB03J89DdpFSTgp5-:-MMyB03J89DdpFSTgp50:b3evbrg) ([raw file](https://github.com/pmem/rpma/blob/04078136cb52287db8c9aef702c9cc94ba4fbd50/src/mr.c#L171)):*
> ```
> flags & RPMA_F_COMPLETION_ON_ERROR
> ```
fence & RPMA_F_SEND_FENCE
___
*[src/include/librpma.h, line 426 at r2](https://reviewable.io/reviews/pmem/rpma/603#-MMyAevW3yJR5bUfEEFz:-MMyAevX5_fUuEafzBv2:b-lsq9s) ([raw file](https://github.com/pmem/rpma/blob/c8444a464e8e61a4ca6a0d2782c6f037dc082973/src/include/librpma.h#L426)):*
> ```
> #define RPMA_F_SEND_NOFENCE		0
> #define RPMA_F_SEND_FENCE		1
> ```
Shall it be in mr.h? as it is not a part of public API yet
___
*[tests/unit/common/test-common.h, line 33 at r2](https://reviewable.io/reviews/pmem/rpma/603#-MMyCbw0D1fsmERaWwQy:-MMyCbw0D1fsmERaWwQz:bcoe0aa) ([raw file](https://github.com/pmem/rpma/blob/c8444a464e8e61a4ca6a0d2782c6f037dc082973/tests/unit/common/test-common.h#L33)):*
> ```
> #define MOCK_NOFENCE		0
> #define MOCK_FENCE			1
> ```
shall we use RPMA_F_SEND_NOFENCE  and RPMA_F_SEND_FENCE instead of MOCK_(NO)FENCE 
or just True/False if we use bool instead of int?
___
*[tests/unit/mr/mr-write.c, line 23 at r2](https://reviewable.io/reviews/pmem/rpma/603#-MMyDBfI5kHwN4fIOtjM:-MMyDBfI5kHwN4fIOtjN:bsn1i8g) ([raw file](https://github.com/pmem/rpma/blob/c8444a464e8e61a4ca6a0d2782c6f037dc082973/tests/unit/mr/mr-write.c#L23)):*
> ```C
>  * with RPMA_E_PROVIDER when send_flags == RPMA_F_COMPLETION_ON_SUCCESS
>  */
> static void
> ```

tests for FENCE are missing

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/603)* status: 3 of 8 files reviewed, 7 unresolved discussions (waiting on @ewanglong, @grom72, @janekmi, and @ldorau)

___
*[src/mr.h, line 41 at r2](https://reviewable.io/reviews/pmem/rpma/603#-MMtYrl27IJnBEiGK7PH:-MN2s5Jm3jxx2R_OFCLv:b-b3ctzq) ([raw file](https://github.com/pmem/rpma/blob/c8444a464e8e61a4ca6a0d2782c6f037dc082973/src/mr.h#L41)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> int fence
> ```
why is this not combined with other flags?
</blockquote></details>

Why  is ` bool fence` not  merged with  `int flags`?
___
*[src/mr.c, line 171 at r1](https://reviewable.io/reviews/pmem/rpma/603#-MMo7VmN-6dOqAGXb9d5:-MN2rrUU8oD9NNGqlqji:bf3uitl) ([raw file](https://github.com/pmem/rpma/blob/04078136cb52287db8c9aef702c9cc94ba4fbd50/src/mr.c#L171)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I do not understand the condition here. Can you elaborate?
</blockquote></details>

I do not understand it either, `wr.send_flags ` can have only `IBV_*` values

**Review by ldorau — COMMENTED** [review]
> Reviewed 4 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/603)* status: 6 of 8 files reviewed, 7 unresolved discussions (waiting on @ewanglong, @grom72, and @janekmi)

**Review by grom72 — COMMENTED** [review]
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/603)* status: all files reviewed, 6 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

___
*[src/mr.h, line 41 at r2](https://reviewable.io/reviews/pmem/rpma/603#-MMtYrl27IJnBEiGK7PH:-MNNDCzfAWTGg9JQvMwC:bb5houf) ([raw file](https://github.com/pmem/rpma/blob/c8444a464e8e61a4ca6a0d2782c6f037dc082973/src/mr.h#L41)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why  is ` bool fence` not  merged with  `int flags`?
</blockquote></details>

because flags is related to public API while fence  is an internal feature

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 9 files at r2, 5 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/603)* status: all files reviewed, 6 unresolved discussions (waiting on @ewanglong, @grom72, and @ldorau)

___
*[src/mr.c, line 172 at r3](https://reviewable.io/reviews/pmem/rpma/603#-MNNIxfN-3G-a5P3EhdF:-MNNIxfN-3G-a5P3EhdG:bh0qo6h) ([raw file](https://github.com/pmem/rpma/blob/0da3f89d5112d4f806e9a62db6081b0cb005698d/src/mr.c#L172)):*
> ```C
> 		IBV_SEND_SIGNALED : 0;
> 	wr.send_flags |= (fence == true) ?
> 		IBV_SEND_FENCE : 0;
> ```

I think this can fit into the previous line.
___
*[tests/unit/common/test-common.h, line 33 at r2](https://reviewable.io/reviews/pmem/rpma/603#-MMyCbw0D1fsmERaWwQy:-MNNJJCM25pTUuw_TZ9U:b-kcmdvt) ([raw file](https://github.com/pmem/rpma/blob/c8444a464e8e61a4ca6a0d2782c6f037dc082973/tests/unit/common/test-common.h#L33)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> #define MOCK_NOFENCE		0
> #define MOCK_FENCE			1
> ```
shall we use RPMA_F_SEND_NOFENCE  and RPMA_F_SEND_FENCE instead of MOCK_(NO)FENCE 
or just True/False if we use bool instead of int?

</blockquote></details>

I like it the way it is.

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/603)* status: all files reviewed, 7 unresolved discussions (waiting on @ewanglong, @grom72, and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/603#-MNNKWe_BqDDGmLCJ36b:-MNNKWea6ktoiAeTiqf0:b-6eixuy) (no related file):*
Please use `common:` prefix for your commit.

---

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/603)* status: all files reviewed, 3 unresolved discussions (waiting on @ewanglong)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/603#-:-MNd2L61AlP-7vLk6snk:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/603)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong)

___
*[src/mr.c, line 171 at r3](https://reviewable.io/reviews/pmem/rpma/603#-MNe9PFADwzcapnKfeVY:-MNe9PFADwzcapnKfeVZ:bmxmidz) ([raw file](https://github.com/pmem/rpma/blob/0da3f89d5112d4f806e9a62db6081b0cb005698d/src/mr.c#L171)):*
> ```
> fence == true
> ```
fence instead of fence == true

and the rest of operator ?  in the same line

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/603#-:-MNglAKlEQFWl8rn8a3L:bnfp4nl)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @ewanglong, @grom72, @janekmi, and @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/603)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 9 files at r2, 2 of 6 files at r3, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/603)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/603#-:-MNhEztYEgJJrb_92s0o:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Pull request merged**
