### PR TITLE
test: add mocks of rpma_ibv_create/destroy_comp_channel

### PR DESCRIPTION
**Pull request by ldorau**
Requires:

- [x] #1663
- [x] #1655 

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1661)

### CODE REVIEW

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1661)* status: 0 of 18 files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1661)* status: 0 of 18 files reviewed, 2 unresolved discussions (waiting on @haichangsi)

___
*[tests/unit/common/mocks-rpma-cq.c, line 117 at r2](https://reviewable.io/reviews/pmem/rpma/1661#-N-cJBsIA5odNYoDK_1C:-N-cJBsJ2kwTKPKHTi1o:b566139) ([raw file](https://github.com/pmem/rpma/blob/ac2687ee9a0c931203f983750fc5c55ede3ada90/tests/unit/common/mocks-rpma-cq.c#L117)):*
> ```C
> 	*channel_ptr = state->channel;
> 
> 	return 0;
> ```

missing failure case



_Code quote:_
```C
	return 0;
```
___
*[tests/unit/common/mocks-rpma-cq.c, line 131 at r2](https://reviewable.io/reviews/pmem/rpma/1661#-N-cJG0XDplZhTiuJFvW:-N-cJG0XDplZhTiuJFvX:b566139) ([raw file](https://github.com/pmem/rpma/blob/ac2687ee9a0c931203f983750fc5c55ede3ada90/tests/unit/common/mocks-rpma-cq.c#L131)):*
> ```C
> 	assert_ptr_equal(channel, state->channel);
> 
> 	return 0;
> ```

missing failure case



_Code quote:_
```C
return 0;
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1661)* status: 0 of 18 files reviewed, all discussions resolved (waiting on @haichangsi)

___
*[tests/unit/common/mocks-rpma-cq.c, line 117 at r2](https://reviewable.io/reviews/pmem/rpma/1661#-N-cJBsIA5odNYoDK_1C:-N-cMt4E4ax4jj5p0cDp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ac2687ee9a0c931203f983750fc5c55ede3ada90/tests/unit/common/mocks-rpma-cq.c#L117)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

missing failure case
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-rpma-cq.c, line 131 at r2](https://reviewable.io/reviews/pmem/rpma/1661#-N-cJG0XDplZhTiuJFvW:-N-cMuyNBf1Th8gLv-hO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ac2687ee9a0c931203f983750fc5c55ede3ada90/tests/unit/common/mocks-rpma-cq.c#L131)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

missing failure case
</blockquote></details>

Done.

**Review by osalyk — APPROVED** [review]
> Reviewed 9 of 10 files at r1, 1 of 9 files at r2, 8 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1661)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 9 files at r2, 1 of 8 files at r3, 1 of 9 files at r5, 1 of 6 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1661)* status: 2 of 18 files reviewed, 4 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)

___
*[tests/unit/common/mocks-rpma-cq.h, line 23 at r7](https://reviewable.io/reviews/pmem/rpma/1661#-N0-hNms8BubFoM3k4Xi:-N0-hNms8BubFoM3k4Xj:b-nd2irb) ([raw file](https://github.com/pmem/rpma/blob/fa84a8ddfa6f35f1ccb80955725212f3ef89bc6c/tests/unit/common/mocks-rpma-cq.h#L23)):*
> ```objc
> };
> 
> struct state_rpma_ibv_destroy_comp_channel {
> ```

Do we need ``state_rpma_ibv_destroy_comp_channel`` structure at all?
Can we do the same thing with ``expected_value()``?



_Code quote:_
```objc
struct state_rpma_ibv_destroy_comp_channel {
	struct ibv_comp_channel *channel;
};
```
___
*[tests/unit/common/mocks-rpma-cq.c, line 129 at r7](https://reviewable.io/reviews/pmem/rpma/1661#-N0-hmRl1DBoSHdJ4HJ1:-N0-hmRl1DBoSHdJ4HJ2:b9r90az) ([raw file](https://github.com/pmem/rpma/blob/fa84a8ddfa6f35f1ccb80955725212f3ef89bc6c/tests/unit/common/mocks-rpma-cq.c#L129)):*
> ```C
> 	state = mock_type(struct state_rpma_ibv_destroy_comp_channel *);
> 
> 	assert_ptr_equal(channel, state->channel);
> ```

Can it be implemented with ``expected_value()``? 



_Code quote:_
```C
assert_ptr_equal(channel, state->channel);
```
___
*[tests/unit/common/mocks-rpma-cq.c, line 131 at r7](https://reviewable.io/reviews/pmem/rpma/1661#-N0-iALn-1PWMX6Bbobz:-N0-iALn-1PWMX6Bboc-:b-jfyvu4) ([raw file](https://github.com/pmem/rpma/blob/fa84a8ddfa6f35f1ccb80955725212f3ef89bc6c/tests/unit/common/mocks-rpma-cq.c#L131)):*
> ```C
> 	assert_ptr_equal(channel, state->channel);
> 
> 	return mock_type(int);
> ```

Do we need our own mock to handle this:
``will_return(rpma_ibv_destroy_comp_channel, MOCK_OK);``
or cmock will handle such a thing itslef?



_Code quote:_
```C
return mock_type(int);
```
___
*[tests/unit/conn/conn-common.c, line 128 at r7](https://reviewable.io/reviews/pmem/rpma/1661#-N0-g9kI8ktl4utTisb8:-N0-g9kI8ktl4utTisb9:b-7u8c05) ([raw file](https://github.com/pmem/rpma/blob/fa84a8ddfa6f35f1ccb80955725212f3ef89bc6c/tests/unit/conn/conn-common.c#L128)):*
> ```C
> 	state_destroy.channel = MOCK_COMP_CHANNEL;
> 	if (cstate->rcq && cstate->channel) {
> 		will_return(rpma_ibv_destroy_comp_channel, &state_destroy);
> ```

Can we skip ``rpm_ibv_destroy_comp_channel`` mock and use ``expect_value()`` directly?



_Code quote:_
```C
will_return(rpma_ibv_destroy_comp_channel, &state_destroy);
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1661)* status: 2 of 18 files reviewed, 4 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)

___
*[tests/unit/common/mocks-rpma-cq.h, line 23 at r7](https://reviewable.io/reviews/pmem/rpma/1661#-N0-hNms8BubFoM3k4Xi:-N0-k1AnADTapZ0G4Xps:b-piyybb) ([raw file](https://github.com/pmem/rpma/blob/fa84a8ddfa6f35f1ccb80955725212f3ef89bc6c/tests/unit/common/mocks-rpma-cq.h#L23)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Do we need ``state_rpma_ibv_destroy_comp_channel`` structure at all?
Can we do the same thing with ``expected_value()``?
</blockquote></details>

Yes, we need. 
We cannot use `expected_value()`, because a value is sometimes NOT expected at all and there is no `expect_value_maybe()` function.
___
*[tests/unit/common/mocks-rpma-cq.c, line 129 at r7](https://reviewable.io/reviews/pmem/rpma/1661#-N0-hmRl1DBoSHdJ4HJ1:-N0-keNh6pSOhNIitQad:b2nhky0) ([raw file](https://github.com/pmem/rpma/blob/fa84a8ddfa6f35f1ccb80955725212f3ef89bc6c/tests/unit/common/mocks-rpma-cq.c#L129)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Can it be implemented with ``expected_value()``? 
</blockquote></details>

No.
___
*[tests/unit/common/mocks-rpma-cq.c, line 131 at r7](https://reviewable.io/reviews/pmem/rpma/1661#-N0-iALn-1PWMX6Bbobz:-N0-kofT9vygZjavPj_d:b-8hkwa1) ([raw file](https://github.com/pmem/rpma/blob/fa84a8ddfa6f35f1ccb80955725212f3ef89bc6c/tests/unit/common/mocks-rpma-cq.c#L131)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Do we need our own mock to handle this:
``will_return(rpma_ibv_destroy_comp_channel, MOCK_OK);``
or cmock will handle such a thing itslef?
</blockquote></details>

I do not understand your question.
___
*[tests/unit/conn/conn-common.c, line 128 at r7](https://reviewable.io/reviews/pmem/rpma/1661#-N0-g9kI8ktl4utTisb8:-N0-kn8j2U4DOt31Q2wx:b2nhky0) ([raw file](https://github.com/pmem/rpma/blob/fa84a8ddfa6f35f1ccb80955725212f3ef89bc6c/tests/unit/conn/conn-common.c#L128)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Can we skip ``rpm_ibv_destroy_comp_channel`` mock and use ``expect_value()`` directly?
</blockquote></details>

No.

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1661)* status: 2 of 18 files reviewed, 4 unresolved discussions (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)

___
*[tests/unit/common/mocks-rpma-cq.h, line 23 at r7](https://reviewable.io/reviews/pmem/rpma/1661#-N0-hNms8BubFoM3k4Xi:-N0-lwwr9y_dtAdhA-2o:b-jcloro) ([raw file](https://github.com/pmem/rpma/blob/fa84a8ddfa6f35f1ccb80955725212f3ef89bc6c/tests/unit/common/mocks-rpma-cq.h#L23)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, we need. 
We cannot use `expected_value()`, because a value is sometimes NOT expected at all and there is no `expect_value_maybe()` function.
</blockquote></details>

But it is only used inside ``if(){ ... }`` in test code
Similar solution is used here:
```
	if (rcq) {
		expect_value(rpma_cq_get_ibv_cq, cq, MOCK_RPMA_RCQ);
		will_return(rpma_cq_get_ibv_cq, MOCK_IBV_RCQ);
	}
```
___
*[tests/unit/common/mocks-rpma-cq.c, line 131 at r7](https://reviewable.io/reviews/pmem/rpma/1661#-N0-iALn-1PWMX6Bbobz:-N0-n_ZQ7obkKs2XPEhB:b-2u6hwd) ([raw file](https://github.com/pmem/rpma/blob/fa84a8ddfa6f35f1ccb80955725212f3ef89bc6c/tests/unit/common/mocks-rpma-cq.c#L131)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I do not understand your question.
</blockquote></details>

Do we need the mock for ``rpma_ibv_destroy_comp_channel``  at all?
Please correct me if I'm wrong as:
It does not implement any logic. Input (arguments) validation and return value set can be implemented directly in the code of tests.

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1661)* status: 2 of 18 files reviewed, 1 unresolved discussion (waiting on @grom72, @haichangsi, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1661#-N001oEq69nQF3-1NK3E:-N001oEq69nQF3-1NK3F:bs1uo3x) (no related file):*
I have in mind sth like this:
```
rpma_ibv_destroy_comp_channel(struct ibv_comp_channel *channel)
{
	check_expected_ptr(channel);
	return mock_type(int);
}
```
```
	if (cstate->get_cqe.shared) {
		expect_value(rpma_ibv_destroy_comp_channel, channel, MOCK_COMP_CHANNEL);
		will_return(rpma_ibv_destroy_comp_channel, MOCK_OK);
	}
```

---

**Comment by ldorau** [comment]
Replaced with https://github.com/pmem/rpma/pull/1668

**Pull request closed without merging**
