### PR TITLE
tools: save intermediate files in case of an error

### PR DESCRIPTION
**Pull request by ldorau**
Save intermediate files in case of an error
for the post mortem analysis.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1273)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1273)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/ib_read.sh, line 272 at r1](https://reviewable.io/reviews/pmem/rpma/1273#-Mj9c_pkCfxmmi1ln5k1:-Mj9c_pkCfxmmi1ln5k2:b2t07sz) ([raw file](https://github.com/pmem/rpma/blob/ffe5e39db992b8a0b2771ec0426b0a4ae28b5c61/tools/perf/ib_read.sh#L272)):*
> ```
>_ input
> ```
```_backup`` or ```_error``` or ```_raw```
___
*[tools/perf/rpma_fio_bench.sh, line 380 at r1](https://reviewable.io/reviews/pmem/rpma/1273#-Mj9cl0fASFn2ExzUsHV:-Mj9cl0fASFn2ExzUsHW:bt8cjh2) ([raw file](https://github.com/pmem/rpma/blob/ffe5e39db992b8a0b2771ec0426b0a4ae28b5c61/tools/perf/rpma_fio_bench.sh#L380)):*
> ```
> _input
> ```
.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1273)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[tools/perf/ib_read.sh, line 272 at r1](https://reviewable.io/reviews/pmem/rpma/1273#-Mj9c_pkCfxmmi1ln5k1:-Mj9exN-E78ExtNXgmKx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ffe5e39db992b8a0b2771ec0426b0a4ae28b5c61/tools/perf/ib_read.sh#L272)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
>_ input
> ```
```_backup`` or ```_error``` or ```_raw```
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 380 at r1](https://reviewable.io/reviews/pmem/rpma/1273#-Mj9cl0fASFn2ExzUsHV:-Mj9ezy7EeivKYYt7iff:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ffe5e39db992b8a0b2771ec0426b0a4ae28b5c61/tools/perf/rpma_fio_bench.sh#L380)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> _input
> ```
.
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1273)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[tools/perf/ib_read.sh, line 272 at r2](https://reviewable.io/reviews/pmem/rpma/1273#-Mj9lHYz3xEbWvEWqSUK:-Mj9lHYz3xEbWvEWqSUL:bjk88aa) ([raw file](https://github.com/pmem/rpma/blob/065e71082c68095a2ee6e06f27a60a244a523f7f/tools/perf/ib_read.sh#L272)):*
> ```
> mv
> ```
```cp```?

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1273)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1273#-:-Mj9nyHVE9FCI63UdEsB:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1273#-:-MjDYKqB74EqXYdLEPMz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
