### PR TITLE
doc: make the main layout h3 RPMA-specific

### PR DESCRIPTION
**Pull request by janekmi**
Preview: https://janekmi.github.io/rpma/documentation/basic-direct-write-to-pmem.html

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/839)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/839)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[_layouts/pmdk.html, line 34 at r1](https://reviewable.io/reviews/pmem/rpma/839#-MSbuWYP2f0HLTnDdEZp:-MSbuWYQ9OURkt7q3c8O:bfe77by) ([raw file](https://github.com/pmem/rpma/blob/f275133793f77ad534620696430949d8141dddf0/_layouts/pmdk.html#L34)):*
> ```
> Remote Persistent Memory Access - PMDK
> ```

It is confusing for me. What does PMDK mean in this context? Maybe `Remote Persistent Memory Access (part of PMDK)`

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/839)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[_layouts/pmdk.html, line 34 at r1](https://reviewable.io/reviews/pmem/rpma/839#-MSbuWYP2f0HLTnDdEZp:-MSbvWc1-B5wWQBLZjWA:b-4xj0ln) ([raw file](https://github.com/pmem/rpma/blob/f275133793f77ad534620696430949d8141dddf0/_layouts/pmdk.html#L34)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> Remote Persistent Memory Access - PMDK
> ```

It is confusing for me. What does PMDK mean in this context? Maybe `Remote Persistent Memory Access (part of PMDK)`
</blockquote></details>

Maybe think about it as a type of breadcrumbs e.g. `PMDK - Remote Persistent Memory Access`?

Ref: https://www.smashingmagazine.com/2009/03/breadcrumbs-in-web-design-examples-and-best-practices/

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/839)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[_layouts/pmdk.html, line 34 at r1](https://reviewable.io/reviews/pmem/rpma/839#-MSbuWYP2f0HLTnDdEZp:-MSbw3P23oaIex_1PvjP:b2gl1bi) ([raw file](https://github.com/pmem/rpma/blob/f275133793f77ad534620696430949d8141dddf0/_layouts/pmdk.html#L34)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Maybe think about it as a type of breadcrumbs e.g. `PMDK - Remote Persistent Memory Access`?

Ref: https://www.smashingmagazine.com/2009/03/breadcrumbs-in-web-design-examples-and-best-practices/
</blockquote></details>

`PMDK - Remote Persistent Memory Access` would be OK

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/839)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[_layouts/pmdk.html, line 34 at r1](https://reviewable.io/reviews/pmem/rpma/839#-MSbuWYP2f0HLTnDdEZp:-MSbwXGR4LfKh4boNR5S:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f275133793f77ad534620696430949d8141dddf0/_layouts/pmdk.html#L34)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`PMDK - Remote Persistent Memory Access` would be OK
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/839)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/839#-:-MSbwtFWDDWLTX8PanDb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
