### PR TITLE
common: print a message in case pmem won't be able to be used

### PR DESCRIPTION
**Pull request by Patryk717**
Ref: #1089

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1200)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1200)* status: all files reviewed, 3 unresolved discussions (waiting on @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1200#-MhID3JNAh_QjqvHIBAK:-MhID3JNAh_QjqvHIBAL:bify42g) (no related file):*
Please fix the commit message. It is important for Gihub to track relationships between PRs and PRs and issues.

```
Ref: #1089
```

**Note**: `#` is crucial. `Ref` is for the human reader.

Ref: https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls (please read)

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1200#-MhIdMVw1V-CS8ym-lmZ:-MhIdMVw1V-CS8ym-lm_:b-2lru1g) (no related file):*
Please also change the commit message:

```
common: print a message in case pmem won't be able to be used
```

---
___
*[CMakeLists.txt, line 108 at r1](https://reviewable.io/reviews/pmem/rpma/1200#-MhIbd9nBAbzQDR_7E3C:-MhIbd9nBAbzQDR_7E3D:b-ao72z0) ([raw file](https://github.com/pmem/rpma/blob/cdaf905ef7d5897aaefa039aa9b7ec71c2e78397/CMakeLists.txt#L108)):*
> ```CMake
> if(NOT LIBPMEM_FOUND)
> 	message(WARNING "Libpmem is missing. The examples will be unable to use PMem. They will be using DRAM instead.")
> endif()
> ```

After reconsideration, I recommend a small change: `Since libpmem is missing, the examples will be...`
Sorry. ;-)

**Review by Patryk717 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1200)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1200#-MhIdMVw1V-CS8ym-lmZ:-MhIm9MQC3x8gkFoSRSf:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please also change the commit message:

```
common: print a message in case pmem won't be able to be used
```
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1200#-MhID3JNAh_QjqvHIBAK:-MhItgVBBJdgNwtPydV5:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please fix the commit message. It is important for Gihub to track relationships between PRs and PRs and issues.

```
Ref: #1089
```

**Note**: `#` is crucial. `Ref` is for the human reader.

Ref: https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/autolinked-references-and-urls (please read)
</blockquote></details>

Done.

---
___
*[CMakeLists.txt, line 108 at r1](https://reviewable.io/reviews/pmem/rpma/1200#-MhIbd9nBAbzQDR_7E3C:-MhItevN2idtRbFzcm45:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cdaf905ef7d5897aaefa039aa9b7ec71c2e78397/CMakeLists.txt#L108)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

After reconsideration, I recommend a small change: `Since libpmem is missing, the examples will be...`
Sorry. ;-)
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1200#-:-MhIuiD85J6l5A9LnFmV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1200)* status: all files reviewed, 1 unresolved discussion (waiting on @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1200#-MhIw-wy2E9zQORnfbK6:-MhIw-wz0uSx0woMCfzc:b-cg5hlu) (no related file):*
Please rebase on upstream/master. You have something messed up a bit. ;-)

---

**Review by janekmi — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1200)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)

**Review by Patryk717 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1200)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1200#-MhIw-wy2E9zQORnfbK6:-MhJ1srZ5HAH-0qwXlvP:b-7rl0kd) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please rebase on upstream/master. You have something messed up a bit. ;-)
</blockquote></details>

done

---

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1200)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1200#-:-MhN2vmE5Y-X_ekG4Phv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)

**Pull request merged**
