### PR TITLE
rpma: replace localtime_r with gmtime_r [DRAFT]

### PR DESCRIPTION
**Pull request by grom72**
gmtime_r is documented as threadsafe
gmtime_r is recognized as threadsafe by Valgrind

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1894)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1894)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72)

___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/pmem/rpma/1894#-N5j3l2c9Jf0vsO077sA):*
thread-safe



_Code quote:_
```
thread safe
```
___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/pmem/rpma/1894#-N5j3nxn2plWzuCCd2dR):*
thread-safe. (+ dot at the end)



_Code quote:_
```
threadsafe
```
___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/pmem/rpma/1894#-N5j3v3-2My4jVPuDHnI):*
thread-safe. (+ dot at the end)



_Code quote:_
```
threadsafe
```
___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/pmem/rpma/1894#-N5j3we-3jxzA9_WwWCo):*
thread-safe  (+ dot at the end)



_Code quote:_
```
threadsafe
```
___
*[`src/log_default.c` line 67 at r1](https://reviewable.io/reviews/pmem/rpma/1894#-N5j48sl3pE-3fLqip28:-N5j48sl3pE-3fLqip29:b-86bdef) ([raw file](https://github.com/pmem/rpma/blob/62eca6f2bd44f714b7ec9361540c034531d0e983/src/log_default.c#L67)):*
> ```C
> 
> 	/* it cannot fail - please see the note above */
> 	(void) snprintf(buf, buf_size, "%s.%06ld\(UTC ", date, usec);
> ```

Where is the closing bracket?



_Code quote:_
```C
\(UTC ",
```

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1894)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1894)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1894#-N5j4jMWDvkvaLXyD6Tt:-N5j4jMX-vtMO4fndSZl:bp9ki7g) (no related file):*
The `log_default-function_0_none` test fails:
```
-- Stderr:
[  ERROR   ] --- "Jan 01 00:00:00.000000(UTC [123456] *WARN*  foo_bar.c: 199: foo_bar(): Message" != "Jan 01 00:00:00.000000(UTC) [123456] *WARN*  foo_bar.c: 199: foo_bar(): Message"
/home/ldorau/work/rpma/tests/unit/common/mocks-stdio.c:74: error: Check of parameter fprintf_output, function __wrap_fprintf failed
/home/ldorau/work/rpma/tests/unit/log_default/function.c:266: note: Expected parameter declared here
[   LINE   ] --- /home/ldorau/work/rpma/tests/unit/common/mocks-stdio.c:74: error: Failure!
[  ERROR   ] --- "Jan 01 00:00:00.000000(UTC [123456] *WARN*  Message" != "Jan 01 00:00:00.000000(UTC) [123456] *WARN*  Message"
/home/ldorau/work/rpma/tests/unit/common/mocks-stdio.c:74: error: Check of parameter fprintf_output, function __wrap_fprintf failed
/home/ldorau/work/rpma/tests/unit/log_default/function.c:304: note: Expected parameter declared here
[   LINE   ] --- /home/ldorau/work/rpma/tests/unit/common/mocks-stdio.c:74: error: Failure!
[  ERROR   ] --- "Jan 01 00:00:00.000000(UTC [123456] *DEBUG* Message" != "Jan 01 00:00:00.000000(UTC) [123456] *DEBUG* Message"
/home/ldorau/work/rpma/tests/unit/common/mocks-stdio.c:74: error: Check of parameter fprintf_output, function __wrap_fprintf failed
/home/ldorau/work/rpma/tests/unit/log_default/function.c:342: note: Expected parameter declared here
[   LINE   ] --- /home/ldorau/work/rpma/tests/unit/common/mocks-stdio.c:74: error: Failure!
[  PASSED  ] 10 test(s).
[  FAILED  ] tests: 3 test(s), listed below:
[  FAILED  ] function__stderr_path
[  FAILED  ] function__stderr_no_path
[  FAILED  ] function__stderr_no_path_ALWAYS

 3 FAILED TEST(S)
```

It seems that the closing bracket is missing ...

___

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1894)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72)

___
*[`src/log_default.c` line 67 at r1](https://reviewable.io/reviews/pmem/rpma/1894#-N5j48sl3pE-3fLqip28:-N5j8eta-gkZDGd_vhKU:b-q2ja4q) ([raw file](https://github.com/pmem/rpma/blob/62eca6f2bd44f714b7ec9361540c034531d0e983/src/log_default.c#L67)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Where is the closing bracket?
</blockquote></details>

It should be `\(UTC) "` instead of the current `\(UTC "`.



_Code quote:_
```C
\(UTC "
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1894)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1894#-N5jAHA18DKxKknUcSC7:-N5jAHA18DKxKknUcSC8:b384mb5) (no related file):*
https://github.com/ldorau/rpma/runs/7110778500?check_suite_focus=true
```
/rpma/src/log_default.c: In function 'rpma_log_default_function':
/rpma/src/log_default.c:67:49: error: '(UTC) ' directive output may be truncated writing 6 bytes into a region of size between 4 and 38 [-Werror=format-truncation=]
   67 |         (void) snprintf(buf, buf_size, "%s.%06ld\(UTC) ", date, usec);
      |                                                 ^~~~~~~
```
and
```
In file included from /usr/include/stdio.h:894,
                 from /rpma/src/include/librpma.h:17,
                 from /rpma/src/log_default.h:11,
                 from /rpma/src/log_default.c:15:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:71:10: note: '__builtin___snprintf_chk' output between 14 and 48 bytes into a destination of size 45
   71 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   72 |                                    __glibc_objsize (__s), __fmt,
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   73 |                                    __va_arg_pack ());
      |                                    ~~~~~~~~~~~~~~~~~
```

___

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1894)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1894)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1894#-N5j4jMWDvkvaLXyD6Tt:-N5jF54F5zQlqd_ygUXy:bb6un1j) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The `log_default-function_0_none` test fails:
```
-- Stderr:
[  ERROR   ] --- "Jan 01 00:00:00.000000(UTC [123456] *WARN*  foo_bar.c: 199: foo_bar(): Message" != "Jan 01 00:00:00.000000(UTC) [123456] *WARN*  foo_bar.c: 199: foo_bar(): Message"
/home/ldorau/work/rpma/tests/unit/common/mocks-stdio.c:74: error: Check of parameter fprintf_output, function __wrap_fprintf failed
/home/ldorau/work/rpma/tests/unit/log_default/function.c:266: note: Expected parameter declared here
[   LINE   ] --- /home/ldorau/work/rpma/tests/unit/common/mocks-stdio.c:74: error: Failure!
[  ERROR   ] --- "Jan 01 00:00:00.000000(UTC [123456] *WARN*  Message" != "Jan 01 00:00:00.000000(UTC) [123456] *WARN*  Message"
/home/ldorau/work/rpma/tests/unit/common/mocks-stdio.c:74: error: Check of parameter fprintf_output, function __wrap_fprintf failed
/home/ldorau/work/rpma/tests/unit/log_default/function.c:304: note: Expected parameter declared here
[   LINE   ] --- /home/ldorau/work/rpma/tests/unit/common/mocks-stdio.c:74: error: Failure!
[  ERROR   ] --- "Jan 01 00:00:00.000000(UTC [123456] *DEBUG* Message" != "Jan 01 00:00:00.000000(UTC) [123456] *DEBUG* Message"
/home/ldorau/work/rpma/tests/unit/common/mocks-stdio.c:74: error: Check of parameter fprintf_output, function __wrap_fprintf failed
/home/ldorau/work/rpma/tests/unit/log_default/function.c:342: note: Expected parameter declared here
[   LINE   ] --- /home/ldorau/work/rpma/tests/unit/common/mocks-stdio.c:74: error: Failure!
[  PASSED  ] 10 test(s).
[  FAILED  ] tests: 3 test(s), listed below:
[  FAILED  ] function__stderr_path
[  FAILED  ] function__stderr_no_path
[  FAILED  ] function__stderr_no_path_ALWAYS

 3 FAILED TEST(S)
```

It seems that the closing bracket is missing ...
</blockquote></details>

Done

___
___
*[`-- commits` line 4 at r1](https://reviewable.io/reviews/pmem/rpma/1894#-N5j3l2c9Jf0vsO077sA):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

thread-safe
</blockquote></details>

Done.
___
*[`-- commits` line 5 at r1](https://reviewable.io/reviews/pmem/rpma/1894#-N5j3nxn2plWzuCCd2dR):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

thread-safe. (+ dot at the end)
</blockquote></details>

Done.
___
*[`-- commits` line 6 at r1](https://reviewable.io/reviews/pmem/rpma/1894#-N5j3v3-2My4jVPuDHnI):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

thread-safe. (+ dot at the end)
</blockquote></details>

Done.
___
*[`-- commits` line 7 at r1](https://reviewable.io/reviews/pmem/rpma/1894#-N5j3we-3jxzA9_WwWCo):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

thread-safe  (+ dot at the end)
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1894#-:-N5jIMCoDopQIRUStgN8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1894)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by Patryk717 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1894#-:-N6Ho1c179p4uXOUkb-n:bdycpsm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1894)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request closed without merging**
