### PR TITLE
Unify stderr and syslog messages

### PR DESCRIPTION
**Pull request by grom72**
- add procid to stderr message (instead of user-defined prefix)
- adjust stderr time format to follow syslog one

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/447)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/447)* status: 1 of 5 files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[tests/unit/common/mocks-getpid.h, line 15 at r1](https://reviewable.io/reviews/pmem/rpma/447#-MI3Jlc6DgG6ekSH4afn:-MI3Jlc6DgG6ekSH4afo:b-5j5tlj) ([raw file](https://github.com/pmem/rpma/blob/d96e7e817636dd4e27b3dcd2ef8393ce4c0eae66/tests/unit/common/mocks-getpid.h#L15)):*
> ```
> /*
>  * __wrap_getpid -- getpid() mock
>  */
> ```

No brief here - briefs are only in *.c files
___
*[tests/unit/common/mocks-getpid.h, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/447#-MI3JYNo0aE7jMFxL_bw:-MI3JYNp8lNfQ-5kSQRp:bosct38) ([raw file](https://github.com/pmem/rpma/blob/d96e7e817636dd4e27b3dcd2ef8393ce4c0eae66/tests/unit/common/mocks-getpid.h#L17)):*
> ```
> __pid_t
> __wrap_getpid();
> ```

In one line:
`__pid_t __wrap_getpid();`

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 3 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/447)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[tests/unit/common/mocks-getpid.c, line 15 at r1](https://reviewable.io/reviews/pmem/rpma/447#-MI3Lt0D2D_X-3XDyp22:-MI3Lt0D2D_X-3XDyp23:bvjn62w) ([raw file](https://github.com/pmem/rpma/blob/d96e7e817636dd4e27b3dcd2ef8393ce4c0eae66/tests/unit/common/mocks-getpid.c#L15)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> __pid_t
> __wrap_getpid()
> {
> 	int ret = mock_type(int);
> 	return ret;
> }
> ```
</details>


Mocked `getpid()` should be enabled only when needed, in all other cases there should a fallback to the real `getpid()`:

```
int enabled__wrap_getpid = 0;

__pid_t
__wrap_getpid()
{
	if (!enabled__wrap_getpid)
		return __real_getpid();

	int ret = mock_type(int);
	return ret;
}
```

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/447)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/447)* status: 1 of 6 files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[tests/unit/common/mocks-getpid.h, line 15 at r1](https://reviewable.io/reviews/pmem/rpma/447#-MI3Jlc6DgG6ekSH4afn:-MI3rCAx73i3llFslD1I:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d96e7e817636dd4e27b3dcd2ef8393ce4c0eae66/tests/unit/common/mocks-getpid.h#L15)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> /*
>  * __wrap_getpid -- getpid() mock
>  */
> ```

No brief here - briefs are only in *.c files
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-getpid.h, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/447#-MI3JYNo0aE7jMFxL_bw:-MI3rBsV4rJ0Le5GziBT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d96e7e817636dd4e27b3dcd2ef8393ce4c0eae66/tests/unit/common/mocks-getpid.h#L17)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> __pid_t
> __wrap_getpid();
> ```

In one line:
`__pid_t __wrap_getpid();`

</blockquote></details>

Done.
___
*[tests/unit/common/mocks-getpid.c, line 15 at r1](https://reviewable.io/reviews/pmem/rpma/447#-MI3Lt0D2D_X-3XDyp22:-MI3rIEhDn9APTDraLz5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d96e7e817636dd4e27b3dcd2ef8393ce4c0eae66/tests/unit/common/mocks-getpid.c#L15)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> __pid_t
> __wrap_getpid()
> {
> 	int ret = mock_type(int);
> 	return ret;
> }
> ```

Mocked `getpid()` should be enabled only when needed, in all other cases there should a fallback to the real `getpid()`:

```
int enabled__wrap_getpid = 0;

__pid_t
__wrap_getpid()
{
	if (!enabled__wrap_getpid)
		return __real_getpid();

	int ret = mock_type(int);
	return ret;
}
```
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
@osalyk,  review, please.
@janekmi - do you accept such a mechanism to enable mock?

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/447#-:-MI3vCcXCqv-p9-KWUCI:b-lsgrig)* status: 1 of 5 files reviewed, 3 unresolved discussions (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/447)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tests/unit/common/mocks-getpid.c, line 14 at r2](https://reviewable.io/reviews/pmem/rpma/447#-MI3x9YM-5RHGHuxlrDD:-MI3x9YM-5RHGHuxlrDE:b-1w5h39) ([raw file](https://github.com/pmem/rpma/blob/07afd2e2ff65d3b598741dbc5a00351f0aa188dd/tests/unit/common/mocks-getpid.c#L14)):*
> ```C
> 
> /*
>  * grtpid shall be mocked only during tests otherwise ctest with COVERAGE=1
> ```

getpid()

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/447)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[tests/unit/common/mocks-getpid.c, line 14 at r2](https://reviewable.io/reviews/pmem/rpma/447#-MI3x9YM-5RHGHuxlrDD:-MI49tJF6ClTcAxpjdqP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/07afd2e2ff65d3b598741dbc5a00351f0aa188dd/tests/unit/common/mocks-getpid.c#L14)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

getpid()
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/447#-:-MI4A8d53u6ewDfvBL3m:bnfp4nl)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @ldorau and @osalyk)

**Review by grom72 — COMMENTED** [review]
@ldorau ready for your review

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/447#-:-MI4Mb8RC6zXZWy7mdKb:b-lodlgx)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @ldorau and @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/447)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72)

___
*[tests/unit/common/mocks-getpid.c, line 20 at r3](https://reviewable.io/reviews/pmem/rpma/447#-MI51sqw2Zoj0zPW9wxF:-MI51sqx2MSjyM3etbcA:bbatonc) ([raw file](https://github.com/pmem/rpma/blob/aa82577d21ede8e7fa4757b7d33c7eb97da0fb7e/tests/unit/common/mocks-getpid.c#L20)):*
> ```
>  __wrap_getpid -- getpid() mock
> ```

__wrap_getpid -- mock of getpid()
___
*[tests/unit/common/mocks-getpid.c, line 24 at r3](https://reviewable.io/reviews/pmem/rpma/447#-MI51cpW0_3hWwCQblKn:-MI51cpXDg9mmhPL-4bV:bc946pu) ([raw file](https://github.com/pmem/rpma/blob/aa82577d21ede8e7fa4757b7d33c7eb97da0fb7e/tests/unit/common/mocks-getpid.c#L24)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> /*
>  * __wrap_getpid -- getpid() mock
>  */
> __pid_t __real_getpid(void);
> __pid_t
> __wrap_getpid()
> ```
</details>


```
__pid_t __real_getpid(void);

/*
 * __wrap_getpid -- mock of getpid()
 */
__pid_t
__wrap_getpid()
```
___
*[tests/unit/log_default/function.c, line 257 at r3](https://reviewable.io/reviews/pmem/rpma/447#-MI52sFA4ad3_SL-8XRI:-MI52sFA4ad3_SL-8XRJ:btz5c5y) ([raw file](https://github.com/pmem/rpma/blob/aa82577d21ede8e7fa4757b7d33c7eb97da0fb7e/tests/unit/log_default/function.c#L257)):*
> ```
> enable getpid mock
> ```

enable getpid()'s mock 
___
*[tests/unit/log_default/function.c, line 265 at r3](https://reviewable.io/reviews/pmem/rpma/447#-MI530pqEYBfUbaw8iTC:-MI530pqEYBfUbaw8iTD:b-8y5rp6) ([raw file](https://github.com/pmem/rpma/blob/aa82577d21ede8e7fa4757b7d33c7eb97da0fb7e/tests/unit/log_default/function.c#L265)):*
> ```
> disable getpid mock 
> ```

disable getpid()'s mock
___
*[tests/unit/log_default/function.c, line 295 at r3](https://reviewable.io/reviews/pmem/rpma/447#-MI53O6XEUEEM1p-EOet:-MI53O6XEUEEM1p-EOeu:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/aa82577d21ede8e7fa4757b7d33c7eb97da0fb7e/tests/unit/log_default/function.c#L295)):*
> ```C
> 		expect_string(__wrap_fprintf, fprintf_output, msg);
> 
> 		/* enable getpid mock only for test execution */
> ```

.
___
*[tests/unit/log_default/function.c, line 302 at r3](https://reviewable.io/reviews/pmem/rpma/447#-MI53Oh3EIGHln_2p2sx:-MI532FK3tpoZPxsbo-r:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/aa82577d21ede8e7fa4757b7d33c7eb97da0fb7e/tests/unit/log_default/function.c#L302)):*
> ```C
> 				MOCK_MESSAGE);
> 
> 		/* disable getpid mock after test execution */
> ```

.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/447)* status: 3 of 5 files reviewed, 6 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[tests/unit/common/mocks-getpid.c, line 20 at r3](https://reviewable.io/reviews/pmem/rpma/447#-MI51sqw2Zoj0zPW9wxF:-MI554PYBZzr_mdnqhrf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/aa82577d21ede8e7fa4757b7d33c7eb97da0fb7e/tests/unit/common/mocks-getpid.c#L20)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  __wrap_getpid -- getpid() mock
> ```

__wrap_getpid -- mock of getpid()
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-getpid.c, line 24 at r3](https://reviewable.io/reviews/pmem/rpma/447#-MI51cpW0_3hWwCQblKn:-MI555qi8EV8fbc2juUz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/aa82577d21ede8e7fa4757b7d33c7eb97da0fb7e/tests/unit/common/mocks-getpid.c#L24)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> /*
>  * __wrap_getpid -- getpid() mock
>  */
> __pid_t __real_getpid(void);
> __pid_t
> __wrap_getpid()
> ```

```
__pid_t __real_getpid(void);

/*
 * __wrap_getpid -- mock of getpid()
 */
__pid_t
__wrap_getpid()
```
</blockquote></details>

Done.
___
*[tests/unit/log_default/function.c, line 257 at r3](https://reviewable.io/reviews/pmem/rpma/447#-MI52sFA4ad3_SL-8XRI:-MI55BUEBfraYu4SKM4h:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/aa82577d21ede8e7fa4757b7d33c7eb97da0fb7e/tests/unit/log_default/function.c#L257)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> enable getpid mock
> ```

enable getpid()'s mock 
</blockquote></details>

Done.
___
*[tests/unit/log_default/function.c, line 265 at r3](https://reviewable.io/reviews/pmem/rpma/447#-MI530pqEYBfUbaw8iTC:-MI55DDJ3iMsrxtxykJF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/aa82577d21ede8e7fa4757b7d33c7eb97da0fb7e/tests/unit/log_default/function.c#L265)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> disable getpid mock 
> ```

disable getpid()'s mock
</blockquote></details>

Done.
___
*[tests/unit/log_default/function.c, line 295 at r3](https://reviewable.io/reviews/pmem/rpma/447#-MI53O6XEUEEM1p-EOet:-MI55EbkEXfWFmSi97M4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/aa82577d21ede8e7fa4757b7d33c7eb97da0fb7e/tests/unit/log_default/function.c#L295)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/log_default/function.c, line 302 at r3](https://reviewable.io/reviews/pmem/rpma/447#-MI53Oh3EIGHln_2p2sx:-MI55GBPCBLQfs7E4zPj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/aa82577d21ede8e7fa4757b7d33c7eb97da0fb7e/tests/unit/log_default/function.c#L302)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 4 files at r2, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/447)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/447#-:-MI57J70CQL2wCCrhgpH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
