### PR TITLE
common: CI: move Fedora Rawhide with sanitizers build to Nightly_Experimental

### PR DESCRIPTION
**Pull request by ldorau**
Move the Fedora Rawhide with sanitizers build to Nightly_Experimental,
because sanitizers fail all tests for unknown reason for a long time.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1004)

### CODE REVIEW

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1004#-:-MYQ--hCESUJGY3ZNzdF:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[.github/workflows/nightly.yml, line 98 at r2](https://reviewable.io/reviews/pmem/rpma/1004#-MYPy7eK6FJxSsTlB5LX:-MYPy7eK6FJxSsTlB5LY:bpnk3ki) ([raw file](https://github.com/pmem/rpma/blob/86d7c26cdc8f92872e594ce8833979338afc6a38/.github/workflows/nightly.yml#L98)):*
> ```YAML
>                  "N=Ubuntu_Rolling       OS=ubuntu               OS_VER=rolling",
>                  # the build Fedora_Rawhide with sanitizers was moved to Nightly_Experimental
>                  "N=Fedora_Rawhide_no_ASAN  OS=fedora            OS_VER=rawhide  CI_SANITS=OFF",
> ```

The fix is no longer limited to ASAN. Maybe it will be good to update also the name of the build?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1004)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[.github/workflows/nightly.yml, line 98 at r2](https://reviewable.io/reviews/pmem/rpma/1004#-MYPy7eK6FJxSsTlB5LX:-MYQ-nE8-N-cP11MQsOO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/86d7c26cdc8f92872e594ce8833979338afc6a38/.github/workflows/nightly.yml#L98)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The fix is no longer limited to ASAN. Maybe it will be good to update also the name of the build?
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1004#-:-MYQ0EJ_8PG3QqHjddMB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1004#-:-MYcq1xW8JFnXWiSss23:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
