### PR TITLE
examples: make sure the word is always null-terminated

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1553)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1553)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[examples/07-atomic-write/client.c, line 164 at r1](https://reviewable.io/reviews/pmem/rpma/1553#-MvNcOf50VJ5MjRBqYoD:-MvNcOf69b9Z2nQNU3q8:b83vt3i) ([raw file](https://github.com/pmem/rpma/blob/8b6a5f2e4daf79bbc668586fbe102bf67467245b/examples/07-atomic-write/client.c#L164)):*
> ```C
> 
> 	/* make sure the word is always null-terminated */
> 	word[LOCAL_DATA_SIZE - 1] = 0;
> ```

Would it be better to clean the whole mr_ptr just after 
```
	/* prepare memory */
	mr_ptr = (struct mr_ptr_s *)malloc_aligned(KILOBYTE);
	if (mr_ptr == NULL)
		return -1;
```
with ```memset(...)```



_Code quote:_
```C
	/* make sure the word is always null-terminated */
	word[LOCAL_DATA_SIZE - 1] = 0;
```

**Review by haichangsi — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1553#-:-MvNfwIuBWLVzSrcKtye:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1553)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1553)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1553#-:-MvNl_GQ5Jz4Lc1iqnBi:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1553)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
