### PR TITLE
common: handle old signature of rdma_getaddrinfo()

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/409)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/409)* status: all files reviewed, 5 unresolved discussions (waiting on @ldorau)

___
*[CMakeLists.txt, line 121 at r1](https://reviewable.io/reviews/pmem/rpma/409#-MHNtF9qBjVSE8WLyDqY:-MHNtF9qBjVSE8WLyDqZ:b-nwg55o) ([raw file](https://github.com/pmem/rpma/blob/4cb699936b70660d3d926548de0aa70daf4c42dd/CMakeLists.txt#L121)):*
> ```CMake
> # check if librdmacm has correct signature of rdma_getaddrinfo()
> check_signature_rdma_getaddrinfo(SIGNATURE_OK_RDMA_GETADDRINFO)
> if(NOT SIGNATURE_OK_RDMA_GETADDRINFO)
> ```

RDMA_GETADDRINFO_NEW_SIGNATURE?
___
*[CMakeLists.txt, line 124 at r1](https://reviewable.io/reviews/pmem/rpma/409#-MHNt72827snvBl1_4WV:-MHNt729CBNSptKyzFwI:b-57z51v) ([raw file](https://github.com/pmem/rpma/blob/4cb699936b70660d3d926548de0aa70daf4c42dd/CMakeLists.txt#L124)):*
> ```CMake
> 	message(NOTICE "-- Using an old signature of rdma_getaddrinfo()")
> else()
> 	message(NOTICE "-- Correct signature of rdma_getaddrinfo() - Success")
> ```

Using a new signature of ...
___
*[src/CMakeLists.txt, line 36 at r1](https://reviewable.io/reviews/pmem/rpma/409#-MHNtLwACiKW5hvu_LUI:-MHNtLwACiKW5hvu_LUJ:bz9sge5) ([raw file](https://github.com/pmem/rpma/blob/4cb699936b70660d3d926548de0aa70daf4c42dd/src/CMakeLists.txt#L36)):*
> ```CMake
> 
> if(NOT SIGNATURE_OK_RDMA_GETADDRINFO)
> 	target_compile_definitions(rpma PRIVATE OLD_SIGNATURE_RDMA_GETADDRINFO=1)
> ```

RDMA_GETADDRINFO_OLD_SIGNATURE?
___
*[src/info.c, line 51 at r1](https://reviewable.io/reviews/pmem/rpma/409#-MHNvD0W3RYk-dBV9dsJ:-MHNvD0W3RYk-dBV9dsK:buix4vn) ([raw file](https://github.com/pmem/rpma/blob/4cb699936b70660d3d926548de0aa70daf4c42dd/src/info.c#L51)):*
> ```C
> 	/* query */
> 	struct rdma_addrinfo *rai = NULL;
> #ifndef OLD_SIGNATURE_RDMA_GETADDRINFO
> ```

I like more when there is a small number of negations. Can you reorder these cases?
___
*[tests/integration/common/mocks.c, line 605 at r1](https://reviewable.io/reviews/pmem/rpma/409#-MHNvgV_5YKusBg12taL:-MHNvgV_5YKusBg12taM:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/4cb699936b70660d3d926548de0aa70daf4c42dd/tests/integration/common/mocks.c#L605)):*
> ```C
> rdma_getaddrinfo(char *node, char *port,
> 		struct rdma_addrinfo *hints, struct rdma_addrinfo **res)
> #endif
> ```

.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/409)* status: 0 of 13 files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[CMakeLists.txt, line 124 at r1](https://reviewable.io/reviews/pmem/rpma/409#-MHNt72827snvBl1_4WV:-MHPg011ELoHcCu_BQCY:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4cb699936b70660d3d926548de0aa70daf4c42dd/CMakeLists.txt#L124)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Using a new signature of ...
</blockquote></details>

Done.
___
*[src/info.c, line 51 at r1](https://reviewable.io/reviews/pmem/rpma/409#-MHNvD0W3RYk-dBV9dsJ:-MHPgnUj8XAxkBu9dD2W:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4cb699936b70660d3d926548de0aa70daf4c42dd/src/info.c#L51)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I like more when there is a small number of negations. Can you reorder these cases?
</blockquote></details>

Done.
___
*[tests/integration/common/mocks.c, line 605 at r1](https://reviewable.io/reviews/pmem/rpma/409#-MHNvgV_5YKusBg12taL:-MHPgnw62taTA_yvLGk5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4cb699936b70660d3d926548de0aa70daf4c42dd/tests/integration/common/mocks.c#L605)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/409)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/CMakeLists.txt, line 36 at r2](https://reviewable.io/reviews/pmem/rpma/409#-MHR2ZjS-bFEHwHwwCgO:-MHR2ZjS-bFEHwHwwCgP:b8yf55p) ([raw file](https://github.com/pmem/rpma/blob/b9a291ef79a10101daf4b97048b6c3d7fb207fce/src/CMakeLists.txt#L36)):*
> ```CMake
> 
> if(NOT RDMA_GETADDRINFO_NEW_SIGNATURE)
> 	target_compile_definitions(rpma PRIVATE RDMA_GETADDRINFO_OLD_SIGNATURE=1)
> ```

Why not just RDMA_GETADDRINFO_NEW_SIGNATURE cmake variable will define RDMA_GETADDRINFO_NEW_SIGNATURE?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/409)* status: 1 of 13 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[src/CMakeLists.txt, line 36 at r2](https://reviewable.io/reviews/pmem/rpma/409#-MHR2ZjS-bFEHwHwwCgO:-MHRJJkrDVHX3InHzvph:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b9a291ef79a10101daf4b97048b6c3d7fb207fce/src/CMakeLists.txt#L36)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Why not just RDMA_GETADDRINFO_NEW_SIGNATURE cmake variable will define RDMA_GETADDRINFO_NEW_SIGNATURE?
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/409#-:-MHRY6Up1puzAjo-fWoN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/409#-:-MHV8pU32zaBq4VrFw0Q:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
@grom72  please review

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/409#-:-MHY5-g3BTw7PPfW6OGh:b-20wudt)* status: 12 of 13 files reviewed, all discussions resolved (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
@ldorau 
can we reverse the logic of this solution?
RDMA_GETADDRINFO_NEW_SIGNATURE=1 - this is the default/current situation 
I would propose to use flag to indicate that we have an old version of API and have to do "workaround"
RDMA_GETADDRINFO_OLD_SIGNATURE

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/409#-:-MHj-husBC971_qmsedj:b5bae4j)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[src/CMakeLists.txt, line 36 at r4](https://reviewable.io/reviews/pmem/rpma/409#-MHj1iDm6nfd627N4dns:-MHj1iDm6nfd627N4dnt:b-c0mewt) ([raw file](https://github.com/pmem/rpma/blob/a47df85612a2602373d28e1a2b929fcbb80af781/src/CMakeLists.txt#L36)):*
> ```
> target_compile_definitions
> ```
can we use add_flag(-DRDMA_GETADDRINFO_NEW_SIGNATURE=1) in main CMakeList.txt instead?
This flag is common for all sources and could be set once for all compilation units

**Review by grom72 — COMMENTED** [review]
> Reviewed 12 of 12 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/409)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
There already was the reverse logic at the very beginning of this PR, but @janekmi asked me to change to the current one.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/409#-:-MHj3n9Q0bgu28IrwEya:b4vj2sx)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
There had to be double negation in case of the reverse logic, what did not look too nice.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/409#-:-MHj70rk5rDJKx82Gn6K:bw01myr)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
Wait, wait, I will double check it

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/409#-:-MHj9iGvCqwiFZrgM-3T:b-3ly1wu)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
It means that I missed something. Do not want to destroy this PR - I only think that flag RDMA_GETADDRINFO_... shall indicate an abnormal situation. Now it will be set to ON forever.
The old logic was to setup flag when API is OK - in the new approach the flag shall be set in exceptional case - where API is old - what causes a special way of call to be used

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/409#-:-MHjFZcPDajM-7QnkELn:b-80pznn)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
@grom72 changed, you are right, it looks better now

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/409#-:-MHjmiNH4MOsbL9Q61JB:b6h5yff)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[src/CMakeLists.txt, line 36 at r4](https://reviewable.io/reviews/pmem/rpma/409#-MHj1iDm6nfd627N4dns:-MHjmeuq1FnVWapQs36n:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a47df85612a2602373d28e1a2b929fcbb80af781/src/CMakeLists.txt#L36)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> target_compile_definitions
> ```
can we use add_flag(-DRDMA_GETADDRINFO_NEW_SIGNATURE=1) in main CMakeList.txt instead?
This flag is common for all sources and could be set once for all compilation units

</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 4 of 12 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/409)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/409#-:-MHjpntO1BXzRe4Jb3y6:b593w57)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
