### PR TITLE
examples: add common-pmem2_map_file.c and common-pmem2_map_file.c

### PR DESCRIPTION
**Pull request by haichangsi**
inside add_example()

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1745)

### CODE REVIEW

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1745#-:-N2QuHVG-OlzaOJIodsa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by osalyk — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1745)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[`examples/CMakeLists.txt` line 78 at r2](https://reviewable.io/reviews/pmem/rpma/1745#-N2QvG8r4HZ0bGhnHXUP:-N2QvG8r4HZ0bGhnHXUQ:b-woh9uq) ([raw file](https://github.com/pmem/rpma/blob/b88772186732a9e1dff4f28d956fd18502976cca/examples/CMakeLists.txt#L78)):*
> ```CMake
> 		${LIBRPMA_SOURCE_DIR})
> 
> 	if(LIBPMEM2_FOUND)
> ```

Can we add **add_executable(${target} ${EXAMPLE_SRCS} ...** in this place?

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1745)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1745)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[`examples/CMakeLists.txt` line 78 at r2](https://reviewable.io/reviews/pmem/rpma/1745#-N2QvG8r4HZ0bGhnHXUP:-N2kDPR43mmol3CXv9QN:b-v6ptng) ([raw file](https://github.com/pmem/rpma/blob/b88772186732a9e1dff4f28d956fd18502976cca/examples/CMakeLists.txt#L78)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Can we add **add_executable(${target} ${EXAMPLE_SRCS} ...** in this place?
</blockquote></details>

I tried as we discussed but there was a problem with adding this here

**Review by osalyk — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1745#-:-N2p4s1-BKX1i-LM13de:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1745)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1745)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1745#-:-N2pzOmR7WjbjJM7iJvC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
