### PR TITLE
test: move all rpma_conn_cfg MT tests to a separate folder

### PR DESCRIPTION
**Pull request by grom72**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1792)

### CODE REVIEW

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1792#-:-N3NyHy19669WQDjH5XX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1792)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[`tests/multithreaded/CMakeLists.txt` line 3 at r1](https://reviewable.io/reviews/pmem/rpma/1792#-N3dbkjs2gQ_TelD3E1G:-N3dbkjt-V2VCL_I8qOy:b-7k8v92) ([raw file](https://github.com/pmem/rpma/blob/444023d9aba96aed962e020f40d9eb2adcfc3141/tests/multithreaded/CMakeLists.txt#L3)):*
> ```CMake
> #
> # SPDX-License-Identifier: BSD-3-Clause
> # Copyright 2020-2021, Intel Corporation
> ```

2020-2022



_Code quote:_
```CMake
2021
```
___
*[`tests/multithreaded/conn_cfg/CMakeLists.txt` line 3 at r1](https://reviewable.io/reviews/pmem/rpma/1792#-N3dbqIU22MXy_d9Kz_P:-N3dbqIU22MXy_d9Kz_Q:bb6ht37) ([raw file](https://github.com/pmem/rpma/blob/444023d9aba96aed962e020f40d9eb2adcfc3141/tests/multithreaded/conn_cfg/CMakeLists.txt#L3)):*
> ```CMake
> #
> # SPDX-License-Identifier: BSD-3-Clause
> # Copyright 2021-2022, Intel Corporation
> ```

2022



_Code quote:_
```CMake
2021-2022
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1792)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[`tests/multithreaded/CMakeLists.txt` line 3 at r1](https://reviewable.io/reviews/pmem/rpma/1792#-N3dbkjs2gQ_TelD3E1G:-N3dd3VP3YEK7Dmojs2A:bzfq1ky) ([raw file](https://github.com/pmem/rpma/blob/444023d9aba96aed962e020f40d9eb2adcfc3141/tests/multithreaded/CMakeLists.txt#L3)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

2020-2022
</blockquote></details>

@grom72 you should commit from the Intel email address, otherwise copyright dates are not verified ...

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1792)* status: 12 of 14 files reviewed, 2 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[`tests/multithreaded/CMakeLists.txt` line 3 at r1](https://reviewable.io/reviews/pmem/rpma/1792#-N3dbkjs2gQ_TelD3E1G:-N3di3Eq9m0XPAKEV4dL:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/444023d9aba96aed962e020f40d9eb2adcfc3141/tests/multithreaded/CMakeLists.txt#L3)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@grom72 you should commit from the Intel email address, otherwise copyright dates are not verified ...
</blockquote></details>

Done.
___
*[`tests/multithreaded/conn_cfg/CMakeLists.txt` line 3 at r1](https://reviewable.io/reviews/pmem/rpma/1792#-N3dbqIU22MXy_d9Kz_P:-N3di5YL67PdJhhKwWRN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/444023d9aba96aed962e020f40d9eb2adcfc3141/tests/multithreaded/conn_cfg/CMakeLists.txt#L3)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

2022
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1792)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1792)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1792#-:-N3dlW43CAFt9R_RQpD5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by osalyk — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1792)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1792)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1792)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
