### PR TITLE
common: introduce add_cstyle_pep8 for checking Python files

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1086)

### CODE REVIEW

**Comment by ldorau** [comment]
See: https://github.com/ldorau/rpma/actions/runs/920594846

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1086)* status: 2 of 33 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[utils/docker/images/Dockerfile.centos-7, line 57 at r2](https://reviewable.io/reviews/pmem/rpma/1086#-MbjLQ5V6yuOLQUSz6wL:-MbjLQ5V6yuOLQUSz6wM:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/f8438395a57db461a7406c3aca1913c21d177b95/utils/docker/images/Dockerfile.centos-7#L57)):*
> ```
> 
> # Create a symlink for pylint
> RUN ln -s /usr/bin/pylint-3 /usr/bin/pylint
> ```

.
___
*[utils/docker/images/Dockerfile.centos-8, line 59 at r2](https://reviewable.io/reviews/pmem/rpma/1086#-MbjKpDEEj-LKKMpVBPW:-MbjKpDEEj-LKKMpVBPX:bmz46k4) ([raw file](https://github.com/pmem/rpma/blob/f8438395a57db461a7406c3aca1913c21d177b95/utils/docker/images/Dockerfile.centos-8#L59)):*
> ```
> 
> # Create a symlink for pylint
> RUN ln -s /usr/bin/pylint-3 /usr/bin/pylint
> ```

I think it will be better to just extend the FindPYLINT.cmake file.

```cmake
find_program(PYLINT_EXECUTABLE NAMES pylint3 pylint-3 pylint)
```

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1086)* status: 3 of 33 files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[utils/docker/images/Dockerfile.centos-6, line 69 at r2](https://reviewable.io/reviews/pmem/rpma/1086#-MbjNsXD-XRnYWgJ8NJG:-MbjNsXE8-G1EC7dPzUH:b-m2ta8t) ([raw file](https://github.com/pmem/rpma/blob/f8438395a57db461a7406c3aca1913c21d177b95/utils/docker/images/Dockerfile.centos-6#L69)):*
> ```
> # Create a symlink 'pylint' pointing at 'true',
> # in order that all pylint checks succeed.
> RUN ln -s $(which true) /usr/bin/pylint
> ```

It is very hacky. But clever. ;-)

I think since CentOS 6 has reached its end of life we can get rid of it before going onward.

Ref: https://en.wikipedia.org/wiki/CentOS#End-of-support_schedule

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 18 of 26 files at r1, 12 of 15 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1086)* status: all files reviewed, 6 unresolved discussions (waiting on @ldorau)

___
*[.circleci/install-pkgs-ubuntu.sh, line 31 at r2](https://reviewable.io/reviews/pmem/rpma/1086#-MbjS_zt0eNvREdA7D6x:-MbjS_zt0eNvREdA7D6y:b-7rgyif) ([raw file](https://github.com/pmem/rpma/blob/f8438395a57db461a7406c3aca1913c21d177b95/.circleci/install-pkgs-ubuntu.sh#L31)):*
> ```Shell
> 
> TESTS_DEPS="\
> 	pylint3"
> ```

Seemingly ~~3~~ is not needed here.

https://packages.ubuntu.com/search?keywords=pylint3&searchon=names
___
*[tools/perf/report_bench.py, line 44 at r2](https://reviewable.io/reviews/pmem/rpma/1086#-MbjTt5i0WWXmPrt_3H-:-MbjSqdQ5x9_Q50IKfEC:b4nb5h3) ([raw file](https://github.com/pmem/rpma/blob/cde2788acddd07d68b5b730efe1b4affa4c531d7/tools/perf/report_bench.py#L44)):*
> ```Python
>         bench = Bench.carry_on(args.bench)
>     else:
>         raise ValueError(f"Unsupported command: {args.command}") 
> ```

For the record: The f-strings feature is implemented from Python 3.6 whereas Debian 9 (aka stretch) provides Python 3.5.3-1. Debian 9's EOL is June 2022 so I think we will get wider adoption without using f-strings until that time.

Ref: https://www.python.org/dev/peps/pep-0498/
Ref: https://packages.debian.org/stretch/python3
Ref: https://wiki.debian.org/LTS
___
*[tools/perf/report_bench.py, line 44 at r2](https://reviewable.io/reviews/pmem/rpma/1086#-MbjVDIr0iq68XbituMk:-MbjVDIr0iq68XbituMl:b-g6w98y) ([raw file](https://github.com/pmem/rpma/blob/f8438395a57db461a7406c3aca1913c21d177b95/tools/perf/report_bench.py#L44)):*
> ```Python
>         bench = Bench.carry_on(args.bench)
>     else:
>         raise ValueError("Unsupported command")
> ```

```python
raise ValueError('Unsupported command: ' + args.command)
```
___
*[utils/docker/images/Dockerfile.debian-9, line 41 at r2](https://reviewable.io/reviews/pmem/rpma/1086#-MbjRPdH5JKdiZmLpBYq:-MbjRPdH5JKdiZmLpBYr:bcezowm) ([raw file](https://github.com/pmem/rpma/blob/f8438395a57db461a7406c3aca1913c21d177b95/utils/docker/images/Dockerfile.debian-9#L41)):*
> ```
> 
> ENV TESTS_DEPS "\
> 	python3-pylint-common"
> ```

Why not this one: https://packages.debian.org/stretch/pylint3 ?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1086)* status: 2 of 33 files reviewed, 6 unresolved discussions (waiting on @janekmi)

___
*[.circleci/install-pkgs-ubuntu.sh, line 31 at r2](https://reviewable.io/reviews/pmem/rpma/1086#-MbjS_zt0eNvREdA7D6x:-Mbj_GHC5Mt5QExNpEFW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f8438395a57db461a7406c3aca1913c21d177b95/.circleci/install-pkgs-ubuntu.sh#L31)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Seemingly ~~3~~ is not needed here.

https://packages.ubuntu.com/search?keywords=pylint3&searchon=names
</blockquote></details>

Done.
___
*[tools/perf/report_bench.py, line 44 at r2](https://reviewable.io/reviews/pmem/rpma/1086#-MbjVDIr0iq68XbituMk:-Mbj_o4x-G9LIzTIHmJF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f8438395a57db461a7406c3aca1913c21d177b95/tools/perf/report_bench.py#L44)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```python
raise ValueError('Unsupported command: ' + args.command)
```
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.centos-6, line 69 at r2](https://reviewable.io/reviews/pmem/rpma/1086#-MbjNsXD-XRnYWgJ8NJG:-MbjdYZG5c8T1K1Uzq7H:b6npa4x) ([raw file](https://github.com/pmem/rpma/blob/f8438395a57db461a7406c3aca1913c21d177b95/utils/docker/images/Dockerfile.centos-6#L69)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is very hacky. But clever. ;-)

I think since CentOS 6 has reached its end of life we can get rid of it before going onward.

Ref: https://en.wikipedia.org/wiki/CentOS#End-of-support_schedule
</blockquote></details>

https://github.com/pmem/rpma/pull/1088
___
*[utils/docker/images/Dockerfile.centos-7, line 57 at r2](https://reviewable.io/reviews/pmem/rpma/1086#-MbjLQ5V6yuOLQUSz6wL:-MbjbuMg85TrG4WEHhR_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f8438395a57db461a7406c3aca1913c21d177b95/utils/docker/images/Dockerfile.centos-7#L57)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.centos-8, line 59 at r2](https://reviewable.io/reviews/pmem/rpma/1086#-MbjKpDEEj-LKKMpVBPW:-MbjbDxX-gsPS8KhPsTF:b-ht0ukm) ([raw file](https://github.com/pmem/rpma/blob/f8438395a57db461a7406c3aca1913c21d177b95/utils/docker/images/Dockerfile.centos-8#L59)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think it will be better to just extend the FindPYLINT.cmake file.

```cmake
find_program(PYLINT_EXECUTABLE NAMES pylint3 pylint-3 pylint)
```
</blockquote></details>

That's right.
___
*[utils/docker/images/Dockerfile.debian-9, line 41 at r2](https://reviewable.io/reviews/pmem/rpma/1086#-MbjRPdH5JKdiZmLpBYq:-Mbjbq-C43AgBhGoyLto:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f8438395a57db461a7406c3aca1913c21d177b95/utils/docker/images/Dockerfile.debian-9#L41)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Why not this one: https://packages.debian.org/stretch/pylint3 ?
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1086)* status: 2 of 33 files reviewed, 6 unresolved discussions (waiting on @janekmi)

___
*[utils/docker/images/Dockerfile.centos-6, line 69 at r2](https://reviewable.io/reviews/pmem/rpma/1086#-MbjNsXD-XRnYWgJ8NJG:-MbjkfBP021ShwB3MBoR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f8438395a57db461a7406c3aca1913c21d177b95/utils/docker/images/Dockerfile.centos-6#L69)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

https://github.com/pmem/rpma/pull/1088
</blockquote></details>

Done.
___
*[utils/docker/images/Dockerfile.centos-8, line 59 at r2](https://reviewable.io/reviews/pmem/rpma/1086#-MbjKpDEEj-LKKMpVBPW:-Mbjkkne4cNwmszZrzyl:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f8438395a57db461a7406c3aca1913c21d177b95/utils/docker/images/Dockerfile.centos-8#L59)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

That's right.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 31 files at r3, 24 of 24 files at r4, 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1086#-:-MbjpESt3VeI5q8upAau:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Comment by ldorau** [comment]
Before rebasing all build passes: https://github.com/ldorau/rpma/actions/runs/920934376

**Comment by ldorau** [comment]
After rebasing many jobs fail: https://github.com/ldorau/rpma/actions/runs/921067006

**Comment by ldorau** [comment]
Before rebasing all build passes: https://github.com/ldorau/rpma/actions/runs/920934376
After rebasing many jobs fail: https://github.com/ldorau/rpma/actions/runs/921067006

**Review by janekmi — APPROVED** [review]
> Reviewed 1 of 30 files at r6, 24 of 24 files at r7, 5 of 5 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1086)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
Build: https://github.com/ldorau/rpma/actions/runs/921918002

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1086#-:-Mbl1d13EvDDlHivqxJg:bhdybkd)* status: 4 of 36 files reviewed, all discussions resolved (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 32 files at r9, 24 of 24 files at r10, 5 of 5 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1086#-:-Mbl64gw3AvZpOmLMiWM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
