### PR TITLE
tools: Runner class introduction

### PR DESCRIPTION
**Pull request by haichangsi**
This PR introduce the new class - Runner.
The Runner class is design to handle all common operation. In this PR common handling for benchmark, config, idfile, dump_cmds has been added.
The class initialization also covers verification of mandatory configuration/oneseries keys.

test_runner_init.py provides the set of UT for Runner initialization.

test_fio_runner.init.py and test_ib_read_runner_init.py extend some tests to utilize new features of the common superclass.

Unify error messages and exceptions.

Use the same error message and the same exception
when a key has a wrong value.

Runners initialization unit tests.

The ib_read type selection defined in figure.

To follow same schema as in fio configuration
let's define ib_read_[lat|bw] suffix via tool_mode

- - -
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/2027)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2027)* status: 2 of 8 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
:goat: 

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2027#-:-NC4W4Hn-mZ2Qf4akB2I:bdycpsm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2027)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Comment by ldorau** [comment]
Postponed

**Pull request closed without merging**
