### PR TITLE
tools: document config.json parameters

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1486)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1486)* status: 0 of 2 files reviewed, 14 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1486#-MtA5wUR8Z8q44bhUEg0:-MtA5wUS7M66QRYmrwnE:b-efam2n) (no related file):*
Few general issues:
- remote/local vs initiator/target - to be unified
- either we rename config.json.example to config.json.template or we provide more realistic data there:
```
    "server_ip": "192.168.13.206",
    "JOB_NUMA": 0,
    "AUX_PARAMS": "-d rxe_eno1 -R",
...
```
This file shall provide as much as possible useful values
- ```_PATH``` is used in two contexts as path (i.e. REMOTE_FIO_PATH ) and as file name (i.e. REMOTE_JOB_PATH)
Shall this be distinguished somehow? We can do this later. 

---
___
*[tools/perf/CONFIG.JSON.md, line 11 at r1](https://reviewable.io/reviews/pmem/rpma/1486#-MtA2wkvAAX0Yps99dxO:-MtA2wkvAAX0Yps99dxP:b-qq4zx) ([raw file](https://github.com/pmem/rpma/blob/8d0df4f60beb98ec4b66f26e7f7f9a8ac10b0c39/tools/perf/CONFIG.JSON.md#L11)):*
> ```Markdown
> - "platform_generation" - generation of the platform, supported values: "Cascade Lake" or "Ice Lake",
> - "server_ip" - an IP address of the remote node (the RDMA target) (for example: "192.168.0.1"),
> - "JOB_NUMA" - a number of the NUMA node of the RDMA initiator,
> ```

a number of the NUMA node on which benchmarking tools will be run on the RPMA initiator



_Code quote:_
```Markdown
of the RDMA initiator
```
___
*[tools/perf/CONFIG.JSON.md, line 12 at r1](https://reviewable.io/reviews/pmem/rpma/1486#-MtA3Mfs1csmXAcKotP5:-MtA3Mfs1csmXAcKotP6:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/8d0df4f60beb98ec4b66f26e7f7f9a8ac10b0c39/tools/perf/CONFIG.JSON.md#L12)):*
> ```Markdown
> - "server_ip" - an IP address of the remote node (the RDMA target) (for example: "192.168.0.1"),
> - "JOB_NUMA" - a number of the NUMA node of the RDMA initiator,
> - "REMOTE_JOB_NUMA" - a number of the NUMA node of the RDMA target,
> ```

.



_Code quote:_
```Markdown
of the RDMA target
```
___
*[tools/perf/CONFIG.JSON.md, line 14 at r1](https://reviewable.io/reviews/pmem/rpma/1486#-MtA3_WY4f7401TQoRvA:-MtA3_WZ189hEPnwOH5m:bb6exvm) ([raw file](https://github.com/pmem/rpma/blob/8d0df4f60beb98ec4b66f26e7f7f9a8ac10b0c39/tools/perf/CONFIG.JSON.md#L14)):*
> ```Markdown
> - "REMOTE_JOB_NUMA" - a number of the NUMA node of the RDMA target,
> - "REMOTE_DIRECT_WRITE_TO_PMEM" - a state of 'Direct Write to PMem' (true or false)
> - "REMOTE_JOB_MEM_PATH" - a path to a remote PMem (Device DAX or File System DAX), it is not used and can be set to any value if 'filetype' is set to 'malloc' in a figure used in the benchmark.
> ```

. It



_Code quote:_
```Markdown
, it
```
___
*[tools/perf/CONFIG.JSON.md, line 14 at r1](https://reviewable.io/reviews/pmem/rpma/1486#-MtA3eM01W8VYBp1EN7g:-MtA3eM01W8VYBp1EN7h:badshey) ([raw file](https://github.com/pmem/rpma/blob/8d0df4f60beb98ec4b66f26e7f7f9a8ac10b0c39/tools/perf/CONFIG.JSON.md#L14)):*
> ```Markdown
> - "REMOTE_JOB_NUMA" - a number of the NUMA node of the RDMA target,
> - "REMOTE_DIRECT_WRITE_TO_PMEM" - a state of 'Direct Write to PMem' (true or false)
> - "REMOTE_JOB_MEM_PATH" - a path to a remote PMem (Device DAX or File System DAX), it is not used and can be set to any value if 'filetype' is set to 'malloc' in a figure used in the benchmark.
> ```

a PMem on an RPMA target 



_Code quote:_
```Markdown
a remote PMem
```
___
*[tools/perf/CONFIG.JSON.md, line 35 at r1](https://reviewable.io/reviews/pmem/rpma/1486#-MtA4M2F-l0j9IetuBth:-MtA4M2F-l0j9IetuBti:bd6jgjh) ([raw file](https://github.com/pmem/rpma/blob/8d0df4f60beb98ec4b66f26e7f7f9a8ac10b0c39/tools/perf/CONFIG.JSON.md#L35)):*
> ```Markdown
> The optional parameters are following:
> 
> - "AUX_PARAMS" - auxiliary parameters for the local ib_read_* tools,
> ```

tools. Typically used to set IB device with ```-d xxx``` and use rdma_cm for connection setup (```-R```). See ib_read_lat, ib_read_bw man.



_Suggestion:_
```Markdown
tools,
```
___
*[tools/perf/CONFIG.JSON.md, line 36 at r1](https://reviewable.io/reviews/pmem/rpma/1486#-MtA53_rDg11909RkGYX:-MtA53_rDg11909RkGYY:b-v439l4) ([raw file](https://github.com/pmem/rpma/blob/8d0df4f60beb98ec4b66f26e7f7f9a8ac10b0c39/tools/perf/CONFIG.JSON.md#L36)):*
> ```Markdown
> 
> - "AUX_PARAMS" - auxiliary parameters for the local ib_read_* tools,
> - "REMOTE_AUX_PARAMS" - auxiliary parameters for the remote ib_read_* tools,
> ```

tools. See ```AUX_PARAMS``` for additional information.



_Code quote:_
```Markdown
tools,
```
___
*[tools/perf/CONFIG.JSON.md, line 37 at r1](https://reviewable.io/reviews/pmem/rpma/1486#-MtABUXe-oJpx-zL_Prs:-MtABUXe-oJpx-zL_Prt:b80ct6q) ([raw file](https://github.com/pmem/rpma/blob/8d0df4f60beb98ec4b66f26e7f7f9a8ac10b0c39/tools/perf/CONFIG.JSON.md#L37)):*
> ```Markdown
> - "AUX_PARAMS" - auxiliary parameters for the local ib_read_* tools,
> - "REMOTE_AUX_PARAMS" - auxiliary parameters for the remote ib_read_* tools,
> - "REMOTE_JOB_PATH" - a full absolute path to the fio job file on the remote node,
> ```

job file on the remote node. If not provided then the fio job file is copied to /dev/shm.



_Code quote:_
```Markdown
job file on the remote node,
```
___
*[tools/perf/CONFIG.JSON.md, line 37 at r1](https://reviewable.io/reviews/pmem/rpma/1486#-MtACAid3hpwhYQvJO8N:-MtACAid3hpwhYQvJO8O:b-dzkh94) ([raw file](https://github.com/pmem/rpma/blob/8d0df4f60beb98ec4b66f26e7f7f9a8ac10b0c39/tools/perf/CONFIG.JSON.md#L37)):*
> ```Markdown
> - "AUX_PARAMS" - auxiliary parameters for the local ib_read_* tools,
> - "REMOTE_AUX_PARAMS" - auxiliary parameters for the remote ib_read_* tools,
> - "REMOTE_JOB_PATH" - a full absolute path to the fio job file on the remote node,
> ```

Would "an absolute" be enough?



_Suggestion:_
```Markdown
a full absolute
```
___
*[tools/perf/CONFIG.JSON.md, line 37 at r1](https://reviewable.io/reviews/pmem/rpma/1486#-MtACRye5eDZoj0M9ToW:-MtACRye5eDZoj0M9ToX:b-vsenxy) ([raw file](https://github.com/pmem/rpma/blob/8d0df4f60beb98ec4b66f26e7f7f9a8ac10b0c39/tools/perf/CONFIG.JSON.md#L37)):*
> ```Markdown
> - "AUX_PARAMS" - auxiliary parameters for the local ib_read_* tools,
> - "REMOTE_AUX_PARAMS" - auxiliary parameters for the remote ib_read_* tools,
> - "REMOTE_JOB_PATH" - a full absolute path to the fio job file on the remote node,
> ```

Shall this be renamed to REMOTE_JOB_FILE_NAME



_Code quote:_
```Markdown
REMOTE_JOB_PATH
```
___
*[tools/perf/CONFIG.JSON.md, line 58 at r1](https://reviewable.io/reviews/pmem/rpma/1486#-MtA9mqE6A5L430u2Lua:-MtA9mqE6A5L430u2Lub:b-ynp3gd) ([raw file](https://github.com/pmem/rpma/blob/8d0df4f60beb98ec4b66f26e7f7f9a8ac10b0c39/tools/perf/CONFIG.JSON.md#L58)):*
> ```Markdown
> 
> ```json
>     "REMOTE_SUDO_NOPASSWD": true,
> ```

Shall we rename this variable?
REMOTE_SUDO_NOPASSWD_ENABLED or REMOTE_DDIO_CONTOROL_ENABLED?

Relation between REMOTE_SUDO_NOPASSWD and REMOTE_USER/REMOTE_PASS shall be described

Is it so that when we have REMOTE_SUDO_NOPASSWD we do not need to provide user and pass?
If yes then REMOTE_SUDO_NOPASSWD and REMOTE_DDIO_CONTOROL_ENABLED shall be separated.

@osalyk what is your opinion?



_Suggestion:_
```Markdown
REMOTE_SUDO_NOPASSWD 
```
___
*[tools/perf/CONFIG.JSON.md, line 64 at r1](https://reviewable.io/reviews/pmem/rpma/1486#-MtA7v8F1Pj4HjwHp3qR:-MtA7v8G01tyQYJGimMF:brr7nd5) ([raw file](https://github.com/pmem/rpma/blob/8d0df4f60beb98ec4b66f26e7f7f9a8ac10b0c39/tools/perf/CONFIG.JSON.md#L64)):*
> ```Markdown
> [direct-write]: https://pmem.io/rpma/documentation/basic-direct-write-to-pmem.html
> 
> ### Collecting SAR data
> ```

An introduction to remote pre/post commands execution is missing here.

Shall we inform the user that it is possible to define our own values here?
And mark only ```REMOTE_CMD_PRE``` and ```REMOTE_CMD_POST``` as required to run remote pre and post command?



_Code quote:_
```Markdown
### Collecting SAR data
```
___
*[tools/perf/CONFIG.JSON.md, line 67 at r1](https://reviewable.io/reviews/pmem/rpma/1486#-MtA7OYF0n1ck73WBC6W:-MtA7OYF0n1ck73WBC6X:bekioxx) ([raw file](https://github.com/pmem/rpma/blob/8d0df4f60beb98ec4b66f26e7f7f9a8ac10b0c39/tools/perf/CONFIG.JSON.md#L67)):*
> ```Markdown
> 
> ```json
>     "REMOTE_ANOTHER_NUMA": 1,
> ```

perhaps explanation that we would like to use another NUMA node to run an additional process on the remote node 



_Suggestion:_
```Markdown
   "REMOTE_ANOTHER_NUMA": 1,
```
___
*[tools/perf/CONFIG.JSON.md, line 105 at r1](https://reviewable.io/reviews/pmem/rpma/1486#-MtA5i4mDs53sFddw49X:-MtA5i4mDs53sFddw49Y:b-2y5svv) ([raw file](https://github.com/pmem/rpma/blob/8d0df4f60beb98ec4b66f26e7f7f9a8ac10b0c39/tools/perf/CONFIG.JSON.md#L105)):*
> ```Markdown
> ```
> 
> Set the timeout in seconds, the default value is 5 minutes.
> ```

"the timeout" of what?????



_Code quote:_
```Markdown
the timeout
```

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1486)* status: 0 of 2 files reviewed, 11 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1486#-MtA5wUR8Z8q44bhUEg0:-MtCUpV39g4cRSzcG6qk:b3mqr2n) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Few general issues:
- remote/local vs initiator/target - to be unified
- either we rename config.json.example to config.json.template or we provide more realistic data there:
```
    "server_ip": "192.168.13.206",
    "JOB_NUMA": 0,
    "AUX_PARAMS": "-d rxe_eno1 -R",
...
```
This file shall provide as much as possible useful values
- ```_PATH``` is used in two contexts as path (i.e. REMOTE_FIO_PATH ) and as file name (i.e. REMOTE_JOB_PATH)
Shall this be distinguished somehow? We can do this later. 
</blockquote></details>

Few general issues:

- either we rename config.json.example to config.json.template or we provide more realistic data there:
    "server_ip": "192.168.13.206",
    "JOB_NUMA": 0,
    "AUX_PARAMS": "-d rxe_eno1 -R",
...
This file shall provide as many as possible useful values

---

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1486)* status: 0 of 2 files reviewed, 11 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/config.json.example, line 7 at r1](https://reviewable.io/reviews/pmem/rpma/1486#-MtCVxPOARjLoySnKnDg:-MtCVxPOARjLoySnKnDh:b-6nsexe) ([raw file](https://github.com/pmem/rpma/blob/35169adce66368d36f2bf694b8cbaf0c4e842b56/tools/perf/config.json.example#L7)):*
> ```
>     "JOB_NUMA": 999,
>     "AUX_PARAMS": "-d XXX -R",
>     "IB_PATH": "path",
> ```

Let leave it as it was.



_Code quote:_
```
    "JOB_NUMA": 999,
    "AUX_PARAMS": "-d XXX -R",
    "IB_PATH": "path",
    "FIO_PATH": "path",
    "REMOTE_USER": "user",
    "REMOTE_PASS": "pass",

    "REMOTE_JOB_NUMA": 999,
    "REMOTE_AUX_PARAMS": "-d XXX -R",
    "REMOTE_IB_PATH": "path",
    "REMOTE_DIRECT_WRITE_TO_PMEM": false,
    "REMOTE_FIO_PATH": "path",
    "REMOTE_JOB_PATH": "path",
```

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1486)* status: 0 of 2 files reviewed, 11 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1486)* status: 0 of 2 files reviewed, 11 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1486#-MtA5wUR8Z8q44bhUEg0:-MtCmi5K7beKKzMa9fuf:b3g98ix) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Few general issues:

- either we rename config.json.example to config.json.template or we provide more realistic data there:
    "server_ip": "192.168.13.206",
    "JOB_NUMA": 0,
    "AUX_PARAMS": "-d rxe_eno1 -R",
...
This file shall provide as many as possible useful values


</blockquote></details>

I do not change `config.json.example` at all, OK?

---
___
*[tools/perf/CONFIG.JSON.md, line 11 at r1](https://reviewable.io/reviews/pmem/rpma/1486#-MtA2wkvAAX0Yps99dxO:-MtC_ZG2EMLhhvD3XE4C:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8d0df4f60beb98ec4b66f26e7f7f9a8ac10b0c39/tools/perf/CONFIG.JSON.md#L11)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

a number of the NUMA node on which benchmarking tools will be run on the RPMA initiator
</blockquote></details>

Done.
___
*[tools/perf/CONFIG.JSON.md, line 12 at r1](https://reviewable.io/reviews/pmem/rpma/1486#-MtA3Mfs1csmXAcKotP5:-MtC_ZoB51T1QGJauaRi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8d0df4f60beb98ec4b66f26e7f7f9a8ac10b0c39/tools/perf/CONFIG.JSON.md#L12)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/CONFIG.JSON.md, line 14 at r1](https://reviewable.io/reviews/pmem/rpma/1486#-MtA3_WY4f7401TQoRvA:-MtCb4IjEs4cP8rtCucf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8d0df4f60beb98ec4b66f26e7f7f9a8ac10b0c39/tools/perf/CONFIG.JSON.md#L14)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

. It
</blockquote></details>

Done.



_Code quote:_
```Markdown
ath to a remote PMem (Device DAX or File System DAX), it is not used a
```
___
*[tools/perf/CONFIG.JSON.md, line 14 at r1](https://reviewable.io/reviews/pmem/rpma/1486#-MtA3eM01W8VYBp1EN7g:-MtCdxT6A_qoTEu5Ssey:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8d0df4f60beb98ec4b66f26e7f7f9a8ac10b0c39/tools/perf/CONFIG.JSON.md#L14)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

a PMem on an RPMA target 
</blockquote></details>

Done.
___
*[tools/perf/CONFIG.JSON.md, line 35 at r1](https://reviewable.io/reviews/pmem/rpma/1486#-MtA4M2F-l0j9IetuBth:-MtCeRIW4Mv417s1IHs4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8d0df4f60beb98ec4b66f26e7f7f9a8ac10b0c39/tools/perf/CONFIG.JSON.md#L35)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

tools. Typically used to set IB device with ```-d xxx``` and use rdma_cm for connection setup (```-R```). See ib_read_lat, ib_read_bw man.
</blockquote></details>

Done.
___
*[tools/perf/CONFIG.JSON.md, line 36 at r1](https://reviewable.io/reviews/pmem/rpma/1486#-MtA53_rDg11909RkGYX:-MtCeXuX4tevLsi0eQe4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8d0df4f60beb98ec4b66f26e7f7f9a8ac10b0c39/tools/perf/CONFIG.JSON.md#L36)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

tools. See ```AUX_PARAMS``` for additional information.
</blockquote></details>

Done.
___
*[tools/perf/CONFIG.JSON.md, line 37 at r1](https://reviewable.io/reviews/pmem/rpma/1486#-MtABUXe-oJpx-zL_Prs:-MtCgJ0_DuoKSVYNj8eI:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8d0df4f60beb98ec4b66f26e7f7f9a8ac10b0c39/tools/perf/CONFIG.JSON.md#L37)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

job file on the remote node. If not provided then the fio job file is copied to /dev/shm.
</blockquote></details>

Done.
___
*[tools/perf/CONFIG.JSON.md, line 37 at r1](https://reviewable.io/reviews/pmem/rpma/1486#-MtACAid3hpwhYQvJO8N:-MtCiPg-256WMkL-qWM8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8d0df4f60beb98ec4b66f26e7f7f9a8ac10b0c39/tools/perf/CONFIG.JSON.md#L37)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Would "an absolute" be enough?
</blockquote></details>

Done.
___
*[tools/perf/config.json.example, line 7 at r1](https://reviewable.io/reviews/pmem/rpma/1486#-MtCVxPOARjLoySnKnDg:-MtCidHd9E3VDvJx1bYJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/35169adce66368d36f2bf694b8cbaf0c4e842b56/tools/perf/config.json.example#L7)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Let leave it as it was.
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1486)* status: 0 of 2 files reviewed, 11 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[tools/perf/CONFIG.JSON.md, line 37 at r1](https://reviewable.io/reviews/pmem/rpma/1486#-MtACRye5eDZoj0M9ToW:-MtCnwEG1lx7e3Okkxvj:b16i7my) ([raw file](https://github.com/pmem/rpma/blob/8d0df4f60beb98ec4b66f26e7f7f9a8ac10b0c39/tools/perf/CONFIG.JSON.md#L37)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Shall this be renamed to REMOTE_JOB_FILE_NAME
</blockquote></details>

But it is not only a file name, but an absolute path to the fio job file on the remote node, so `REMOTE_JOB_FILE_ABSOLUTE_PATH` ? I think the current one is better and can stay.
___
*[tools/perf/CONFIG.JSON.md, line 58 at r1](https://reviewable.io/reviews/pmem/rpma/1486#-MtA9mqE6A5L430u2Lua:-MtCozrF0abkDJYLf-bN:b6nb26t) ([raw file](https://github.com/pmem/rpma/blob/8d0df4f60beb98ec4b66f26e7f7f9a8ac10b0c39/tools/perf/CONFIG.JSON.md#L58)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Shall we rename this variable?
REMOTE_SUDO_NOPASSWD_ENABLED or REMOTE_DDIO_CONTOROL_ENABLED?

Relation between REMOTE_SUDO_NOPASSWD and REMOTE_USER/REMOTE_PASS shall be described

Is it so that when we have REMOTE_SUDO_NOPASSWD we do not need to provide user and pass?
If yes then REMOTE_SUDO_NOPASSWD and REMOTE_DDIO_CONTOROL_ENABLED shall be separated.

@osalyk what is your opinion?
</blockquote></details>

`REMOTE_SUDO_NOPASSWD` means that `sudo` does not ask for password on the remote node, nothing more, so it is OK.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1486)* status: all files reviewed, 11 unresolved discussions (waiting on @grom72)

___
*[tools/perf/CONFIG.JSON.md, line 64 at r1](https://reviewable.io/reviews/pmem/rpma/1486#-MtA7v8F1Pj4HjwHp3qR:-MtD0WSn25RohqYfnk5V:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/8d0df4f60beb98ec4b66f26e7f7f9a8ac10b0c39/tools/perf/CONFIG.JSON.md#L64)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

An introduction to remote pre/post commands execution is missing here.

Shall we inform the user that it is possible to define our own values here?
And mark only ```REMOTE_CMD_PRE``` and ```REMOTE_CMD_POST``` as required to run remote pre and post command?
</blockquote></details>

Done

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1486#-:-MtD23mY7U9EhkwUBmwi:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1486#-MtA5wUR8Z8q44bhUEg0:-MtD0yyP3VRum0_AEU_O:b32w0x) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I do not change `config.json.example` at all, OK?
</blockquote></details>

OK

---

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1486)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
