### PR TITLE
test: "ut-" prefix for unit tests' names

### PR DESCRIPTION
**Pull request by grom72**
Add "ut-" prefix to all unit tests' names to be able to filter
them out while running ctest:

```
$ ctest
...
 74/169 Test  #74: ut-utils-ibv_context_is_odp_capable_0_none .............................   Passed    0.03 sec
        Start  75: ut-log_default-init-fini_0_none
 75/169 Test  #75: ut-log_default-init-fini_0_none ........................................   Passed    0.03 sec
        Start  76: ut-log_default-function_0_none
 76/169 Test  #76: ut-log_default-function_0_none .........................................   Passed    0.03 sec
        Start  77: multithreaded-conn_cfg-get_cq_size_0_none
 77/169 Test  #77: multithreaded-conn_cfg-get_cq_size_0_none ..............................   Passed    0.03 sec
...
```
```
$ ctest -E "ut-"
Test project /home/rpma/repos/rpma/build
      Start  1: multithreaded-conn_cfg-get_cq_size_0_none
 1/93 Test  #1: multithreaded-conn_cfg-get_cq_size_0_none ..............................   Passed    0.04 sec
...
```

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1907)

### CODE REVIEW

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1907)* status: 0 of 18 files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by osalyk — CHANGES_REQUESTED** [review]
> Reviewed 17 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1907)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @grom72, @haichangsi, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1907#-N5tuyA_3xSQh6ZATBaB:-N5tuyA_3xSQh6ZATBaC:bl5kkic) (no related file):*
Please correct the number of commits

___

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1907)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @haichangsi and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1907#-N5tuyA_3xSQh6ZATBaB:-N680crM9P63Akd2HgWp:b-896fix) (no related file):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Please correct the number of commits
</blockquote></details>

Done.

___

**Review by Patryk717 — COMMENTED** [review]
:goat: 

> Reviewed 17 of 17 files at r2, 2 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1907#-:-N6HwIk0A4pnb79tgUv1:bdycpsm)* status: 19 of 21 files reviewed, 1 unresolved discussion (waiting on @haichangsi, @osalyk, and @Patryk717)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r3, 1 of 3 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1907#-:-N6MB-MBB4ZGZWr-RYsc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by haichangsi — COMMENTED** [review]
:lgtm:

> Reviewed 17 of 17 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1907#-:-N6r34So08QmRDmWTlME:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by osalyk — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1907)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
