### PR TITLE
tools: perf: document lib.Requirement

### PR DESCRIPTION
**Pull request by janekmi**
Requires:

- [x] #1374

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1375)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1375)* status: 0 of 13 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 11 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1375)* status: 11 of 13 files reviewed, 2 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[tools/perf/lib/Requirement.py, line 11 at r1](https://reviewable.io/reviews/pmem/rpma/1375#-Mpp7UKbBR_G9vG-VReV:-Mpp7UKbBR_G9vG-VReW:bqkrje) ([raw file](https://github.com/pmem/rpma/blob/4136dbb2fbaf41f06764fc176e1b3375ff80f14c/tools/perf/lib/Requirement.py#L11)):*
> ```
> controlling a single requirement
> ```
Can we add a short description of Requirement
e.g. Requirement is a condition that must be satisfied to run Benchmark (e.g. XXX)
___
*[tools/perf/lib/Requirement.py, line 89 at r1](https://reviewable.io/reviews/pmem/rpma/1375#-Mpp78LE-syvYpoTqp8F:-Mpp78LFBSmaRJLlxiAX:bo6ofjm) ([raw file](https://github.com/pmem/rpma/blob/4136dbb2fbaf41f06764fc176e1b3375ff80f14c/tools/perf/lib/Requirement.py#L89)):*
> ```
> ·········
> ```

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1375)* status: 11 of 13 files reviewed, 5 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[tools/perf/lib/Requirement.py, line 52 at r1](https://reviewable.io/reviews/pmem/rpma/1375#-MppD0C94aLGuJIPqf4T:-MppD0C94aLGuJIPqf4U:b-hgb2n4) ([raw file](https://github.com/pmem/rpma/blob/4136dbb2fbaf41f06764fc176e1b3375ff80f14c/tools/perf/lib/Requirement.py#L52)):*
> ```
> __pick
> ```
__bind?
___
*[tools/perf/lib/Requirement.py, line 64 at r1](https://reviewable.io/reviews/pmem/rpma/1375#-MppCCMoBbrZjVVJ7NZz:-MppCCMoBbrZjVVJ7N_-:b-2pthly) ([raw file](https://github.com/pmem/rpma/blob/4136dbb2fbaf41f06764fc176e1b3375ff80f14c/tools/perf/lib/Requirement.py#L64)):*
> ```
>         `lib.benchmark.base.Benchmark.requirements` taken out from elements
>         of the `benchmarks` dictionary are used to create a list of
> ```
"for the given `benchmarks' dictionary" instead of "taken out from elements of the `benchmarks` dictionary"
___
*[tools/perf/lib/Requirement.py, line 65 at r1](https://reviewable.io/reviews/pmem/rpma/1375#-MppBLqQB1IbLjm7Agnq:-MppBLqQB1IbLjm7Agnr:bkevn7o) ([raw file](https://github.com/pmem/rpma/blob/4136dbb2fbaf41f06764fc176e1b3375ff80f14c/tools/perf/lib/Requirement.py#L65)):*
> ```
>         ... From this list are removed all duplicates.
> ```
All duplicates are removed from the list.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1375)* status: 11 of 13 files reviewed, 5 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[tools/perf/lib/Requirement.py, line 11 at r1](https://reviewable.io/reviews/pmem/rpma/1375#-Mpp7UKbBR_G9vG-VReV:-MppLs3KBou1tJL1N_XQ:b-xcrpq8) ([raw file](https://github.com/pmem/rpma/blob/4136dbb2fbaf41f06764fc176e1b3375ff80f14c/tools/perf/lib/Requirement.py#L11)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> controlling a single requirement
> ```
Can we add a short description of Requirement
e.g. Requirement is a condition that must be satisfied to run Benchmark (e.g. XXX)
</blockquote></details>

The Requirement is a set of conditions that must be satisfied to run Benchmark (e.g. XXX)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1375)* status: 12 of 13 files reviewed, 5 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1375)* status: 12 of 13 files reviewed, 6 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[tools/perf/lib/Requirement.py, line 130 at r1](https://reviewable.io/reviews/pmem/rpma/1375#-MppNV6f3zYQh0UYIAL_:-MppNV6f3zYQh0UYIALa:b-vl77t0) ([raw file](https://github.com/pmem/rpma/blob/4136dbb2fbaf41f06764fc176e1b3375ff80f14c/tools/perf/lib/Requirement.py#L130)):*
> ```
> ·········
> ```
.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1375)* status: 12 of 13 files reviewed, 7 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[tools/perf/lib/Requirement.py, line 157 at r1](https://reviewable.io/reviews/pmem/rpma/1375#-MppRTzj2pKRxWFdgF5L:-MppRTzj2pKRxWFdgF5M:b-vl77t0) ([raw file](https://github.com/pmem/rpma/blob/4136dbb2fbaf41f06764fc176e1b3375ff80f14c/tools/perf/lib/Requirement.py#L157)):*
> ```
> ·········
> ```
.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1375)* status: 4 of 13 files reviewed, 7 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/lib/Requirement.py, line 11 at r1](https://reviewable.io/reviews/pmem/rpma/1375#-Mpp7UKbBR_G9vG-VReV:-MppRynmAVzrIDxcQTGk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4136dbb2fbaf41f06764fc176e1b3375ff80f14c/tools/perf/lib/Requirement.py#L11)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

The Requirement is a set of conditions that must be satisfied to run Benchmark (e.g. XXX)
</blockquote></details>

Done.
___
*[tools/perf/lib/Requirement.py, line 52 at r1](https://reviewable.io/reviews/pmem/rpma/1375#-MppD0C94aLGuJIPqf4T:-MppS4cO9r8lL6vExJes:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4136dbb2fbaf41f06764fc176e1b3375ff80f14c/tools/perf/lib/Requirement.py#L52)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> __pick
> ```
__bind?
</blockquote></details>

Done.
___
*[tools/perf/lib/Requirement.py, line 64 at r1](https://reviewable.io/reviews/pmem/rpma/1375#-MppCCMoBbrZjVVJ7NZz:-MppSbd81dlhe6z1zbTm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4136dbb2fbaf41f06764fc176e1b3375ff80f14c/tools/perf/lib/Requirement.py#L64)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
>         `lib.benchmark.base.Benchmark.requirements` taken out from elements
>         of the `benchmarks` dictionary are used to create a list of
> ```
"for the given `benchmarks' dictionary" instead of "taken out from elements of the `benchmarks` dictionary"
</blockquote></details>

Done.
___
*[tools/perf/lib/Requirement.py, line 65 at r1](https://reviewable.io/reviews/pmem/rpma/1375#-MppBLqQB1IbLjm7Agnq:-MppTu9tBTnvlhoNftaC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4136dbb2fbaf41f06764fc176e1b3375ff80f14c/tools/perf/lib/Requirement.py#L65)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
>         ... From this list are removed all duplicates.
> ```
All duplicates are removed from the list.
</blockquote></details>

Done.
___
*[tools/perf/lib/Requirement.py, line 89 at r1](https://reviewable.io/reviews/pmem/rpma/1375#-Mpp78LE-syvYpoTqp8F:-MppJxJM8F8uYr0xjmJV:b-sgjmh) ([raw file](https://github.com/pmem/rpma/blob/4136dbb2fbaf41f06764fc176e1b3375ff80f14c/tools/perf/lib/Requirement.py#L89)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> ·········
> ```

</blockquote></details>

This is why I have started from an attempt to enable pylint for this file. ;-)
But I have left this idea. Done.
___
*[tools/perf/lib/Requirement.py, line 130 at r1](https://reviewable.io/reviews/pmem/rpma/1375#-MppNV6f3zYQh0UYIAL_:-MppRJVfDUFBhWmdOpSm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4136dbb2fbaf41f06764fc176e1b3375ff80f14c/tools/perf/lib/Requirement.py#L130)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> ·········
> ```
.
</blockquote></details>

Done.
___
*[tools/perf/lib/Requirement.py, line 157 at r1](https://reviewable.io/reviews/pmem/rpma/1375#-MppRTzj2pKRxWFdgF5L:-MppTvIJ9NGEFhgI1JNz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4136dbb2fbaf41f06764fc176e1b3375ff80f14c/tools/perf/lib/Requirement.py#L157)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> ·········
> ```
.
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1375)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1375)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — COMMENTED** [review]
> Reviewed 10 of 10 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1375)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1375)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1375#-:-MpqLMOhEhPL3Nby2KYa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1375)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1375)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/lib/Requirement.py, line 30 at r3](https://reviewable.io/reviews/pmem/rpma/1375#-MpqNNUj-sreNEVUV0-Q:-MpqNNUj-sreNEVUV0-R:b4729qz) ([raw file](https://github.com/pmem/rpma/blob/47197681e17e4e5ecf2bcb801137676e2e5616e4/tools/perf/lib/Requirement.py#L30)):*
> ```
> """A string representation of the object"""
> ```

Please leave it, it is not so obvious to me
___
*[tools/perf/lib/Requirement.py, line 63 at r3](https://reviewable.io/reviews/pmem/rpma/1375#-MpqRU_KCVED1JWgVcWl:-MpqRU_L197wRXJBnxQn:b-1exp2d) ([raw file](https://github.com/pmem/rpma/blob/a775ac89d416e016a85ce494d1fbd73318b407a3/tools/perf/lib/Requirement.py#L63)):*
> ```
> all benchmarks making the requirement
> ```

all benchmarks that make the requirement

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1375)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[tools/perf/lib/Requirement.py, line 30 at r3](https://reviewable.io/reviews/pmem/rpma/1375#-MpqNNUj-sreNEVUV0-Q:-MpqZY6r91PXWc2kz-vO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/47197681e17e4e5ecf2bcb801137676e2e5616e4/tools/perf/lib/Requirement.py#L30)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> """A string representation of the object"""
> ```

Please leave it, it is not so obvious to me
</blockquote></details>

Done.
___
*[tools/perf/lib/Requirement.py, line 63 at r3](https://reviewable.io/reviews/pmem/rpma/1375#-MpqRU_KCVED1JWgVcWl:-MpqZrUCCjw5_xboHFOL:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a775ac89d416e016a85ce494d1fbd73318b407a3/tools/perf/lib/Requirement.py#L63)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> all benchmarks making the requirement
> ```

all benchmarks that make the requirement
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1375)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/lib/Requirement.py, line 81 at r4](https://reviewable.io/reviews/pmem/rpma/1375#-MpqceJt8vK5PKOLexls:-MpqceJt8vK5PKOLexlt:bz4q7z1) ([raw file](https://github.com/pmem/rpma/blob/7ba2e10ca21140ac67d751957d016af380bd66dd/tools/perf/lib/Requirement.py#L81)):*
> ```
>             A `dict` of `lib.benchmark.base.Benchmark` objects.
>               Where each keys are `lib.benchmark.base.Benchmark.identifier`.
> ```

"each" is singular,so :

```
... objects,
where each key comes from `lib.benchmark.base.Benchmark.identifier`.
```
___
*[tools/perf/lib/Requirement.py, line 200 at r4](https://reviewable.io/reviews/pmem/rpma/1375#-MpqdmLj9c40w72zKuXa:-MpqdmLk8BDKX8mbikT3:b-xenqoc) ([raw file](https://github.com/pmem/rpma/blob/7ba2e10ca21140ac67d751957d016af380bd66dd/tools/perf/lib/Requirement.py#L200)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
>         """Dump all benchmarks
> 
>         The dump ends up on stdout.
>         """
> ```
</details>


```
        """Dump all benchmarks to stdout"""
```

?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1375)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/lib/Requirement.py, line 81 at r4](https://reviewable.io/reviews/pmem/rpma/1375#-MpqceJt8vK5PKOLexls:-MpsOCMB6GUyJTu1tsU9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7ba2e10ca21140ac67d751957d016af380bd66dd/tools/perf/lib/Requirement.py#L81)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>             A `dict` of `lib.benchmark.base.Benchmark` objects.
>               Where each keys are `lib.benchmark.base.Benchmark.identifier`.
> ```

"each" is singular,so :

```
... objects,
where each key comes from `lib.benchmark.base.Benchmark.identifier`.
```

</blockquote></details>

Done.
___
*[tools/perf/lib/Requirement.py, line 200 at r4](https://reviewable.io/reviews/pmem/rpma/1375#-MpqdmLj9c40w72zKuXa:-MpsODH_DdiDnMIuAdZa:b-yw8ca2) ([raw file](https://github.com/pmem/rpma/blob/7ba2e10ca21140ac67d751957d016af380bd66dd/tools/perf/lib/Requirement.py#L200)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>         """Dump all benchmarks
> 
>         The dump ends up on stdout.
>         """
> ```

```
        """Dump all benchmarks to stdout"""
```

?
</blockquote></details>

Any better?

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1375)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

___
*[tools/perf/lib/Requirement.py, line 200 at r4](https://reviewable.io/reviews/pmem/rpma/1375#-MpqdmLj9c40w72zKuXa:-MptxCRH4xBku_IHRV3w:b-1ctm1u) ([raw file](https://github.com/pmem/rpma/blob/7ba2e10ca21140ac67d751957d016af380bd66dd/tools/perf/lib/Requirement.py#L200)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Any better?
</blockquote></details>

Much better

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1375#-:-MptxHFk17vlgws9jYce:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
