### PR TITLE
test: verify channel in rpma_conn_new()

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #1668

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1666)

### CODE REVIEW

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1666)* status: 0 of 11 files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1666)* status: 1 of 11 files reviewed, 1 unresolved discussion (waiting on @grom72, @haichangsi, and @ldorau)

___
*[tests/unit/conn_req/conn_req-connect.c, line 333 at r1](https://reviewable.io/reviews/pmem/rpma/1666#-N0-jlDd2SFA9k1bEQp3:-N0-jlDd2SFA9k1bEQp4:b-4298rn) ([raw file](https://github.com/pmem/rpma/blob/c990a72496bddaf0823b47ec63aac776b9544365/tests/unit/conn_req/conn_req-connect.c#L333)):*
> ```C
> 
> 	struct state_rpma_ibv_destroy_comp_channel state_destroy;
> 	state_destroy.channel = MOCK_COMP_CHANNEL;
> ```

MOCK_GET_CHANNEL(cstate)



_Code quote:_
```C
MOCK_COMP_CHANNEL
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1666)* status: 1 of 11 files reviewed, 1 unresolved discussion (waiting on @grom72 and @haichangsi)

___
*[tests/unit/conn_req/conn_req-connect.c, line 333 at r1](https://reviewable.io/reviews/pmem/rpma/1666#-N0-jlDd2SFA9k1bEQp3:-N00HZKT4-70eD2tWMEF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c990a72496bddaf0823b47ec63aac776b9544365/tests/unit/conn_req/conn_req-connect.c#L333)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

MOCK_GET_CHANNEL(cstate)
</blockquote></details>

Done.

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 11 files at r1, 1 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1666#-:-N00KQ0RAUqpODj3hvjr:bnfp4nl)* status: 3 of 11 files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 11 files at r1, 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1666)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 2 of 11 files at r1, 1 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1666#-:-N00PDni6BOroCZvdWn2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1666)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
