### PR TITLE
tools: perf: update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by janekmi**
- add pylint and pdoc3
- add a section about the Python documentation
- pytest and pylint are already in the CI

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1356)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1356#-:-MpRJg3V0aApL9Eqkpqn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1356)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/CONTRIBUTING.md, line 30 at r1](https://reviewable.io/reviews/pmem/rpma/1356#-MpSAE97AjGmpTG3gfCB:-MpSAE986bntf_FCu1DW:bfnqkk1) ([raw file](https://github.com/pmem/rpma/blob/71a9891b7b29b6a59ff5ab6bb30124743be819af/tools/perf/CONTRIBUTING.md#L30)):*
> ```
> `pdoc3` do not generate
> ```

`pdoc3` does not generate
___
*[tools/perf/CONTRIBUTING.md, line 30 at r1](https://reviewable.io/reviews/pmem/rpma/1356#-MpSARVQB_W0W6Ru4QsU:-MpSARVQB_W0W6Ru4QsV:b-1zu6kb) ([raw file](https://github.com/pmem/rpma/blob/71a9891b7b29b6a59ff5ab6bb30124743be819af/tools/perf/CONTRIBUTING.md#L30)):*
> ```
> Inside the `lib/` subdirectory is a regular `index.html` file
> ```

There is a regular `index.html` file inside the `lib/` subdirectory ...
___
*[tools/perf/CONTRIBUTING.md, line 36 at r1](https://reviewable.io/reviews/pmem/rpma/1356#-MpSArclBzPtkrHJ_D3p:-MpSArclBzPtkrHJ_D3q:b-l1w5hp) ([raw file](https://github.com/pmem/rpma/blob/71a9891b7b29b6a59ff5ab6bb30124743be819af/tools/perf/CONTRIBUTING.md#L36)):*
> ```
> module
> ```

modules ?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1356)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[tools/perf/CONTRIBUTING.md, line 30 at r1](https://reviewable.io/reviews/pmem/rpma/1356#-MpSAE97AjGmpTG3gfCB:-MpZ1hC38csiZkD-7iDc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/71a9891b7b29b6a59ff5ab6bb30124743be819af/tools/perf/CONTRIBUTING.md#L30)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> `pdoc3` do not generate
> ```

`pdoc3` does not generate
</blockquote></details>

Done.
___
*[tools/perf/CONTRIBUTING.md, line 30 at r1](https://reviewable.io/reviews/pmem/rpma/1356#-MpSARVQB_W0W6Ru4QsU:-MpZ24xT-NBO07BZb0Jb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/71a9891b7b29b6a59ff5ab6bb30124743be819af/tools/perf/CONTRIBUTING.md#L30)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> Inside the `lib/` subdirectory is a regular `index.html` file
> ```

There is a regular `index.html` file inside the `lib/` subdirectory ...
</blockquote></details>

Done.
___
*[tools/perf/CONTRIBUTING.md, line 36 at r1](https://reviewable.io/reviews/pmem/rpma/1356#-MpSArclBzPtkrHJ_D3p:-MpZ2B_Q5kukJfJX93Zz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/71a9891b7b29b6a59ff5ab6bb30124743be819af/tools/perf/CONTRIBUTING.md#L36)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> module
> ```

modules ?
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1356)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1356#-:-MpenUbE78rr1IP_9oM5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
