### PR TITLE
examples: do not overwrite the previous return value

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/2077)

### CODE REVIEW

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2077#-:-NGGRbaN3JBmski1ks4W:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2077)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`examples/06scch-multiple-connections/server.c` line 123 at r1](https://reviewable.io/reviews/pmem/rpma/2077#-NGGS_UnEOThZjw6Trno:-NGGS_UnEOThZjw6Trnp:ba29w9g) ([raw file](https://github.com/pmem/rpma/blob/960183595606f68f04a718779c538f1f67fe4ec7/examples/06scch-multiple-connections/server.c#L123)):*
> ```C
> 	/* deregister the memory region */
> 	int ret2 = rpma_mr_dereg(&svr->dst_mr);
> 	if (!ret && ret2)
> ```

we either not overwrite or overwrite with ret2 which either 0 or ``an_error_value``



_Suggestion:_
```C
	if (!ret)
		ret = ret2;
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2077)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2077)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72 and @osalyk)

___
*[`examples/06scch-multiple-connections/server.c` line 123 at r1](https://reviewable.io/reviews/pmem/rpma/2077#-NGGS_UnEOThZjw6Trno:-NGGTUCA3YP060QxJN1P:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/960183595606f68f04a718779c538f1f67fe4ec7/examples/06scch-multiple-connections/server.c#L123)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

we either not overwrite or overwrite with ret2 which either 0 or ``an_error_value``
</blockquote></details>

Done.

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2077#-:-NGGfoZY4ISKioMX7mA2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
