### PR TITLE
tools: print out names of log files

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1421)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1421)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 195 at r1](https://reviewable.io/reviews/pmem/rpma/1421#-Mr1x80y7981f83qRqIU:-Mr1x80y7981f83qRqIV:bxgcn8a) ([raw file](https://github.com/pmem/rpma/blob/b45950d2718fb604d34dcf8b04e3365f34640e9f/tools/perf/lib/benchmark/runner/ib_read.py#L195)):*
> ```Python
>         self.__settings['logfile_server'] = name + '-server.log'
>         self.__settings['logfile_client'] = name + '-client.log'
>         print('Server log: {}'.format(self.__settings['logfile_server']))
> ```

Shall always be shown on stdout or only when TRACE/DUMP?

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1421)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1421)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1421)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 195 at r1](https://reviewable.io/reviews/pmem/rpma/1421#-Mr1x80y7981f83qRqIU:-Mr249xl99uUhN8b1lwv:b-v69ogm) ([raw file](https://github.com/pmem/rpma/blob/b45950d2718fb604d34dcf8b04e3365f34640e9f/tools/perf/lib/benchmark/runner/ib_read.py#L195)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Shall always be shown on stdout or only when TRACE/DUMP?
</blockquote></details>

I think they should be printed out always, so that a user could check what happened if a benchmark fails.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1421)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 195 at r1](https://reviewable.io/reviews/pmem/rpma/1421#-Mr1x80y7981f83qRqIU:-Mr24jQ503nmtZ3-808i:b-6gn0zi) ([raw file](https://github.com/pmem/rpma/blob/b45950d2718fb604d34dcf8b04e3365f34640e9f/tools/perf/lib/benchmark/runner/ib_read.py#L195)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I think they should be printed out always, so that a user could check what happened if a benchmark fails.
</blockquote></details>

OK let see how many times we will see this message

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1421#-:-Mr24qIhEhy1JrB_S4VB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1421#-:-Mr2JO7j5qmqjocsAx6v:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
