### PR TITLE
example: printf the error reason

### PR DESCRIPTION
**Pull request by zhijianli88**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1167)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1167)* status: all files reviewed, 9 unresolved discussions (waiting on @zhijianli88)

___
*[examples/03-read-to-persistent/client.c, line 81 at r1](https://reviewable.io/reviews/pmem/rpma/1167#-MfgGA1-5CPrKb9IMu0q:-MfgGA1066cB-p_5Q2Iv:b-7uh2qh) ([raw file](https://github.com/pmem/rpma/blob/1d34931916b0f802bcf3841d467d37338588a19b/examples/03-read-to-persistent/client.c#L81)):*
> ```
> "%s is not pmem like file\n"
> ```

`"%s is not a PMEM file\n"`
@janekmi ?
___
*[examples/03-read-to-persistent/server.c, line 65 at r1](https://reviewable.io/reviews/pmem/rpma/1167#-MfgG_ZYAwo5l3oLR9Dt:-MfgG_ZYAwo5l3oLR9Du:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/1d34931916b0f802bcf3841d467d37338588a19b/examples/03-read-to-persistent/server.c#L65)):*
> ```C
> 		/* pmem is expected */
> 		if (!is_pmem) {
> 			(void) fprintf(stderr, "%s is not pmem like file\n",
> ```

.
___
*[examples/04-write-to-persistent/client.c, line 99 at r1](https://reviewable.io/reviews/pmem/rpma/1167#-MfgGb6qBe23xR77DH0H:-MfgGb6qBe23xR77DH0I:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/1d34931916b0f802bcf3841d467d37338588a19b/examples/04-write-to-persistent/client.c#L99)):*
> ```C
> 		/* pmem is expected */
> 		if (!is_pmem) {
> 			(void) fprintf(stderr, "%s is not pmem like file\n",
> ```

.
___
*[examples/04-write-to-persistent/server.c, line 73 at r1](https://reviewable.io/reviews/pmem/rpma/1167#-MfgGc2j5n5Bt9QwRfx2:-MfgGc2k7E4HvxoIByB0:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/1d34931916b0f802bcf3841d467d37338588a19b/examples/04-write-to-persistent/server.c#L73)):*
> ```C
> 		/* pmem is expected */
> 		if (!is_pmem) {
> 			(void) fprintf(stderr, "%s is not pmem like file\n",
> ```

.
___
*[examples/05-flush-to-persistent/client.c, line 89 at r1](https://reviewable.io/reviews/pmem/rpma/1167#-MfgGd3d9YHCfZULNGQm:-MfgGd3d9YHCfZULNGQn:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/1d34931916b0f802bcf3841d467d37338588a19b/examples/05-flush-to-persistent/client.c#L89)):*
> ```C
> 		/* pmem is expected */
> 		if (!is_pmem) {
> 			(void) fprintf(stderr, "%s is not pmem like file\n",
> ```

.
___
*[examples/05-flush-to-persistent/server.c, line 70 at r1](https://reviewable.io/reviews/pmem/rpma/1167#-MfgGe6d1hBxngN0ai0t:-MfgGe6d1hBxngN0ai0u:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/1d34931916b0f802bcf3841d467d37338588a19b/examples/05-flush-to-persistent/server.c#L70)):*
> ```C
> 		/* pmem is expected */
> 		if (!is_pmem) {
> 			(void) fprintf(stderr, "%s is not pmem like file\n",
> ```

.
___
*[examples/07-atomic-write/server.c, line 81 at r1](https://reviewable.io/reviews/pmem/rpma/1167#-MfgGf74CsiaFO6BSHMV:-MfgGf74CsiaFO6BSHMW:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/1d34931916b0f802bcf3841d467d37338588a19b/examples/07-atomic-write/server.c#L81)):*
> ```C
> 		/* pmem is expected */
> 		if (!is_pmem) {
> 			(void) fprintf(stderr, "%s is not pmem like file\n",
> ```

.
___
*[examples/09-flush-to-persistent-GPSPM/client.c, line 102 at r1](https://reviewable.io/reviews/pmem/rpma/1167#-MfgGh7156at2ufCha3B:-MfgGh7156at2ufCha3C:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/1d34931916b0f802bcf3841d467d37338588a19b/examples/09-flush-to-persistent-GPSPM/client.c#L102)):*
> ```C
> 		/* pmem is expected */
> 		if (!is_pmem) {
> 			(void) fprintf(stderr, "%s is not pmem like file\n",
> ```

.
___
*[examples/09-flush-to-persistent-GPSPM/server.c, line 78 at r1](https://reviewable.io/reviews/pmem/rpma/1167#-MfgGiFR9lJgXh0HNLDM:-MfgGiFR9lJgXh0HNLDN:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/1d34931916b0f802bcf3841d467d37338588a19b/examples/09-flush-to-persistent-GPSPM/server.c#L78)):*
> ```C
> 		/* pmem is expected */
> 		if (!is_pmem) {
> 			(void) fprintf(stderr, "%s is not pmem like file\n",
> ```

.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1167)* status: all files reviewed, 9 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[examples/03-read-to-persistent/client.c, line 81 at r1](https://reviewable.io/reviews/pmem/rpma/1167#-MfgGA1-5CPrKb9IMu0q:-MfgMi0E7SC1pPxkBHDQ:batrbd7) ([raw file](https://github.com/pmem/rpma/blob/1d34931916b0f802bcf3841d467d37338588a19b/examples/03-read-to-persistent/client.c#L81)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> "%s is not pmem like file\n"
> ```

`"%s is not a PMEM file\n"`
@janekmi ?
</blockquote></details>

I think we should use the `pmem_map_file()` documentation to construct this message e.g.:

`%s is not actual pmem\n`

Ref: https://pmem.io/pmdk/manpages/linux/v1.11/libpmem/pmem_is_pmem.3

**Comment by yangx-jy** [comment]
___
*[examples/03-read-to-persistent/client.c, line 81 at r1](https://reviewable.io/reviews/pmem/rpma/1167#-MfgGA1-5CPrKb9IMu0q:-MfgNzSb-Jnm0mTIA3UF:bkk2zv1) ([raw file](https://github.com/pmem/rpma/blob/1d34931916b0f802bcf3841d467d37338588a19b/examples/03-read-to-persistent/client.c#L81)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we should use the `pmem_map_file()` documentation to construct this message e.g.:

`%s is not actual pmem\n`

Ref: https://pmem.io/pmdk/manpages/linux/v1.11/libpmem/pmem_is_pmem.3
</blockquote></details>

+1,  because `path` is either file or device. ^_^

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1167)* status: all files reviewed, 9 unresolved discussions (waiting on @janekmi and @zhijianli88)

___
*[examples/03-read-to-persistent/client.c, line 81 at r1](https://reviewable.io/reviews/pmem/rpma/1167#-MfgGA1-5CPrKb9IMu0q:-MfgPTozCamNmK8IBG7g:b9d8mxz) ([raw file](https://github.com/pmem/rpma/blob/1d34931916b0f802bcf3841d467d37338588a19b/examples/03-read-to-persistent/client.c#L81)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

+1,  because `path` is either file or device. ^_^
</blockquote></details>

so `%s is not an actual pmem\n` (+ an)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1167)* status: all files reviewed, 9 unresolved discussions (waiting on @janekmi and @zhijianli88)

___
*[examples/03-read-to-persistent/client.c, line 81 at r1](https://reviewable.io/reviews/pmem/rpma/1167#-MfgGA1-5CPrKb9IMu0q:-MfgPnuq15lRd4bq1JRd:b-9izp7c) ([raw file](https://github.com/pmem/rpma/blob/1d34931916b0f802bcf3841d467d37338588a19b/examples/03-read-to-persistent/client.c#L81)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

so `%s is not an actual pmem\n` (+ an)
</blockquote></details>

or maybe ` %s is not an actual PMEM\n` ?

**Comment by zhijianli88** [comment]
> or maybe ` %s is not an actual PMEM\n` ?

updated

**Review by ldorau — APPROVED** [review]
> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1167)* status: all files reviewed, 9 unresolved discussions (waiting on @janekmi and @zhijianli88)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1167#-:-MfkrFDX4DVY1a7qgm_o:bnfp4nl)* status: all files reviewed, 9 unresolved discussions (waiting on @janekmi and @zhijianli88)

**Comment by yangx-jy** [comment]
___
*[examples/03-read-to-persistent/client.c, line 81 at r1](https://reviewable.io/reviews/pmem/rpma/1167#-MfgGA1-5CPrKb9IMu0q:-MgO8UHX0mqPJm4v72Ym:bdjq0dc) ([raw file](https://github.com/pmem/rpma/blob/1d34931916b0f802bcf3841d467d37338588a19b/examples/03-read-to-persistent/client.c#L81)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

or maybe ` %s is not an actual PMEM\n` ?
</blockquote></details>

`an actual PMEM` is fine to me.

**Review by yangx-jy — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1167#-:-MgO8qr70O-5CfIlYmF3:bnfp4nl)* status: all files reviewed, 9 unresolved discussions (waiting on @janekmi and @zhijianli88)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1167#-:-MgPg6fKDGEM5fuk2jG-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zhijianli88)

**Pull request merged**
