### PR TITLE
common: correct checking signature of rdma_getaddrinfo() for clang

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/569)

### CODE REVIEW

**Comment by ldorau** [comment]
@janekmi @grom72 please review - it is the continuation and improvement of https://github.com/pmem/rpma/pull/559

**Comment by ldorau** [comment]
It has been tested on other Linux distros here: https://github.com/ldorau/rpma/actions/runs/335513069 - all builds passed

**Review by ldorau — COMMENTED** [review]
Rebased

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/569#-:-MKt63Xr0Pt2gnEccX8G:b9x2p3v)* status: 0 of 1 files reviewed, all discussions resolved

**Review by janekmi — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/569)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[cmake/functions.cmake, line 180 at r2](https://reviewable.io/reviews/pmem/rpma/569#-MLNsaEe1YMJqwhyq6C5:-MLNsPJ37494ug6ulbXC:b1m2qvi) ([raw file](https://github.com/pmem/rpma/blob/0b87b45f0fc38a674aba0d49b329f9f8a707528c/cmake/functions.cmake#L180)):*
> ```CMake
> 			set(DISCARDED_QUALIFIERS_FLAG "-Werror;-Wincompatible-pointer-types-discards-qualifiers")
> 		endif()
> 	endif()
> ```

Can you put the flag you want to check into the variable sooner?
So you will probably have only a single call to `CHECK_C_COMPILER_FLAG()` and for sure far fewer repetitions of the flag string.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/569)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @janekmi)

___
*[cmake/functions.cmake, line 180 at r2](https://reviewable.io/reviews/pmem/rpma/569#-MLNsaEe1YMJqwhyq6C5:-MLOAeVQ73i_aKw5HPvx:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/0b87b45f0fc38a674aba0d49b329f9f8a707528c/cmake/functions.cmake#L180)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Can you put the flag you want to check into the variable sooner?
So you will probably have only a single call to `CHECK_C_COMPILER_FLAG()` and for sure far fewer repetitions of the flag string.
</blockquote></details>

Done

**Review by ldorau — COMMENTED** [review]
All tests passed: https://github.com/ldorau/rpma/actions/runs/347827687

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/569#-:-MLOB0Kb7I4KRNyBsn3i:bylj9if)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/569#-:-MLOI_682jjCiOofru3H:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
@grom72 @osalyk please review

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/569#-:-MLOOuoQ2mPBS0nYOYBt:bg7id4e)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/569#-:-MLRPib05UYKds7htvOZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/569#-:-MLRpX2L9vMACxaDuV8E:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
