### PR TITLE
test: remove old integration tests

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1834)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1834)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1834#-N4X5f6N4a9qfowmPhNG:-N4X5f6N4a9qfowmPhNH:b-w6mp22) (no related file):*
Worth to be mentioned in CHANGELOG.md

___

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1834)* status: 10 of 14 files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1834#-N4X5f6N4a9qfowmPhNG:-N4XFGY3Bj2zlS-fhQX3:b-896fix) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Worth to be mentioned in CHANGELOG.md
</blockquote></details>

Done.

___

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1834)* status: 13 of 14 files reviewed, 4 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[`-- commits` line 3 at r3](https://reviewable.io/reviews/pmem/rpma/1834#-N4XczZZ2T7d169z8zUp):*
remove old integration tests



_Code quote:_
```
remove integration tests
```
___
*[`CHANGELOG.md` line 29 at r3](https://reviewable.io/reviews/pmem/rpma/1834#-N4Xd1iL0X12kMQLJMXw:-N4Xd1iL0X12kMQLJMXx:b-as2j0p) ([raw file](https://github.com/pmem/rpma/blob/ca443bbc221e6a5b520769341bab98954fb5017b/CHANGELOG.md#L29)):*
> ```Markdown
> 
> ### Removed
> - integration tests
> ```

old integration tests



_Code quote:_
```Markdown
integration tests
```
___
*[`tests/unit/common/mocks-rdma_cm.c` line 192 at r3](https://reviewable.io/reviews/pmem/rpma/1834#-N4XdKRzCm-aPpGhe5e8:-N4XdKRzCm-aPpGhe5e9:bvnn0br) ([raw file](https://github.com/pmem/rpma/blob/66f112303d3e2b06d659c856b47debe3e4670952/tests/unit/common/mocks-rdma_cm.c#L192)):*
> ```C
> 	assert_non_null(conn_param);
> 	assert_null(conn_param->private_data);
> 	assert_int_equal(conn_param->private_data_len, 0);
> ```

Why couldn't it be left?



_Code quote:_
```C
	assert_null(conn_param->private_data);
	assert_int_equal(conn_param->private_data_len, 0);
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1834)* status: 13 of 14 files reviewed, 5 unresolved discussions (waiting on @grom72 and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1834#-N4XdemqBZwhejYAWUU5:-N4XdemqBZwhejYAWUU6:b-ujmq67) (no related file):*
Rebase please

___

**Review by grom72 — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1834)* status: all files reviewed, 4 unresolved discussions (waiting on @osalyk)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1834#-:-N4XfIOz-GMPbW3UcJTs:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1834)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1834#-N4XdemqBZwhejYAWUU5:-N4_wQm34JEGtmJYAesE:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Rebase please
</blockquote></details>

Done.

___
___
*[`-- commits` line 3 at r3](https://reviewable.io/reviews/pmem/rpma/1834#-N4XczZZ2T7d169z8zUp):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

remove old integration tests
</blockquote></details>

Done.
___
*[`CHANGELOG.md` line 29 at r3](https://reviewable.io/reviews/pmem/rpma/1834#-N4Xd1iL0X12kMQLJMXw:-N4_wanTBssWrvhno8y3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ca443bbc221e6a5b520769341bab98954fb5017b/CHANGELOG.md#L29)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

old integration tests
</blockquote></details>

Done.
___
*[`tests/unit/common/mocks-rdma_cm.c` line 192 at r3](https://reviewable.io/reviews/pmem/rpma/1834#-N4XdKRzCm-aPpGhe5e8:-N4_yJGF1veiLYAAy3tn:b-kcz7gh) ([raw file](https://github.com/pmem/rpma/blob/66f112303d3e2b06d659c856b47debe3e4670952/tests/unit/common/mocks-rdma_cm.c#L192)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why couldn't it be left?
</blockquote></details>

This is what the mock of this function looked like in the old integration tests.
So that you can test the uncovered path indicated by @grom72 .

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1834)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[`tests/unit/conn_req/conn_req-connect.c` line 569 at r4](https://reviewable.io/reviews/pmem/rpma/1834#-N4aDg-mBkuU0FOi8ijB:-N4aDg-n6VQHERyfsT95:b-dhyvfb) ([raw file](https://github.com/pmem/rpma/blob/3bd9d9df93bd44f47cb0efacd9c5dca6b95c9658/tests/unit/conn_req/conn_req-connect.c#L569)):*
> ```C
> 
> 	/* run test */
> 	static char buff[] = DEFAULT_VALUE;
> ```

It should not be `static`.



_Code quote:_
```C
static char buff[] = DEFAULT_VALUE;
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1834)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[`tests/unit/conn_req/conn_req-connect.c` line 569 at r4](https://reviewable.io/reviews/pmem/rpma/1834#-N4aDg-mBkuU0FOi8ijB:-N4aGvz7EXhJWgjAJtci:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3bd9d9df93bd44f47cb0efacd9c5dca6b95c9658/tests/unit/conn_req/conn_req-connect.c#L569)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It should not be `static`.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1834)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1834#-:-N4aItOh83YedcJQ0v0b:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
