### PR TITLE
rpma: analysis of thread safety: rpma_conn_req_

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #1757

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1759)

### CODE REVIEW

**Review by osalyk — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1759)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1759)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`THREAD_SAFETY.md` line 36 at r1](https://reviewable.io/reviews/pmem/rpma/1759#-N2zBF8d4xyVMs1VJsxx:-N2zBF8d4xyVMs1VJsxy:bvzvo45) ([raw file](https://github.com/pmem/rpma/blob/87e5a775bfda89f56112a7be1c4b45fcca918c6c/THREAD_SAFETY.md#L36)):*
> ```Markdown
> - rpma_conn_req_recv
> 
> are thread-safe only if each thread operates on a **separate connection request** (`struct rpma_conn_req`) used only by this one thread. They are not thread-safe if threads operate on one connection request common for more than one thread.
> ```

I think it is acceptable to pass conn_req between threads.



_Suggestion:_
```Markdown
one thread at a time.
```

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1759)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1759#-:-N2zz_qpChJg2AsBRlwt:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1759#-:-N3-1pt0-M1f7PKs14h3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
