### PR TITLE
tools: perf: introduce cpuload appendices

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1042)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1042)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/csv_compare.py, line 353 at r1](https://reviewable.io/reviews/pmem/rpma/1042#-MZuullP4jXaekz-wgzV:-MZuullP4jXaekz-wgzW:b-p8t82c) ([raw file](https://github.com/pmem/rpma/blob/9c3be648903d49478bce2b56b7cc9fe772c48916/tools/perf/csv_compare.py#L353)):*
> ```
> , 'lat_all']:
> ```

Does this change belong to "introduce cpuload appendices" ?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1042)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/csv_compare.py, line 353 at r1](https://reviewable.io/reviews/pmem/rpma/1042#-MZuullP4jXaekz-wgzV:-MZvKhmcEpYHXXhlc3JM:btrqzz1) ([raw file](https://github.com/pmem/rpma/blob/9c3be648903d49478bce2b56b7cc9fe772c48916/tools/perf/csv_compare.py#L353)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> , 'lat_all']:
> ```

Does this change belong to "introduce cpuload appendices" ?
</blockquote></details>

Yes. `lat_all` is yet another layout that allows providing both `arg_axis` and `arg_xscale` that allow draw lat_all(cpuload) figures. Required for generating cpuload appendices.

Still, I have made this separate so I can prepare a separate PR for this. But this change does not make much sense without the context of the cpuload appendices.

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1042)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

___
*[tools/perf/csv_compare.py, line 353 at r1](https://reviewable.io/reviews/pmem/rpma/1042#-MZuullP4jXaekz-wgzV:-MZvP7CH9ffH9cO2JzTQ:b32w0x) ([raw file](https://github.com/pmem/rpma/blob/9c3be648903d49478bce2b56b7cc9fe772c48916/tools/perf/csv_compare.py#L353)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Yes. `lat_all` is yet another layout that allows providing both `arg_axis` and `arg_xscale` that allow draw lat_all(cpuload) figures. Required for generating cpuload appendices.

Still, I have made this separate so I can prepare a separate PR for this. But this change does not make much sense without the context of the cpuload appendices.
</blockquote></details>

OK

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1042#-:-MZvP9WOBIVNe6QWOSCc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1042#-:-MZwCNh62qPf0n-pcVE0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
