### PR TITLE
tools: remove not supported mode

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/760)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/760)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/rpma_fio_bench.sh, line 342 at r1](https://reviewable.io/reviews/pmem/rpma/760#-MR_t_bS5m_TUr-vgeKx:-MR_t_bS5m_TUr-vgeKy:b-dnv2wi) ([raw file](https://github.com/pmem/rpma/blob/db9bfeaa84ae46d320712f11e9e101546248f01c/tools/rpma_fio_bench.sh#L342)):*
> ```Shell
> 			esac
> 		fi
> 		for m in $MODES; do
> ```

Please give a space between `if` and `for`.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/760)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/rpma_fio_bench.sh, line 342 at r1](https://reviewable.io/reviews/pmem/rpma/760#-MR_t_bS5m_TUr-vgeKx:-MR_uW0WDPDag_vOB33P:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/db9bfeaa84ae46d320712f11e9e101546248f01c/tools/rpma_fio_bench.sh#L342)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please give a space between `if` and `for`.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/760#-:-MRaB7b1323DgUj8OSd5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/760#-:-MRcUYeo2IZLKjIwd8FH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/760)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/760#-:-MRdO7EMCD1QCoSphVg4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
