### PR TITLE
examples/04-write-to-persistent: correct the return value

### PR DESCRIPTION
**Pull request by zhijianli88**
Generally, program should exit with non-zero if there is something wrong

Signed-off-by: Li Zhijian <lizhijian@cn.fujitsu.com>

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1140)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1140)* status: all files reviewed, 1 unresolved discussion (waiting on @zhijianli88)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1140#-Mf2psds4Jw4Wp5U8seK:-Mf2psdt30IuEjY6wkQ4:bg0h391) (no related file):*
Please change the commit title 
from: "examples/04-write-to-persistent: correct the return value"
to: "examples: 04-write-to-persistent: correct the return value"

---

**Comment by zhijianli88** [comment]
> > Reviewed 2 of 2 files at r1.
> > _[Reviewable](https://reviewable.io/reviews/pmem/rpma/1140)_ status: all files reviewed, 1 unresolved discussion (waiting on @zhijianli88)
> 
> _[a discussion](https://reviewable.io/reviews/pmem/rpma/1140#-Mf2psds4Jw4Wp5U8seK:-Mf2psdt30IuEjY6wkQ4:bg0h391) (no related file):_
> Please change the commit title
> from: "examples/04-write-to-persistent: correct the return value"
> to: "examples: 04-write-to-persistent: correct the return value"

Fixed

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1140)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zhijianli88)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1140#-:-Mf6QDfU2VH4gv2AM1t9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zhijianli88)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1140#-:-MfECQAT1hAlhzdcdPV1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @zhijianli88)

**Pull request merged**
