### PR TITLE
rpma: replace localtime() with localtime_r()

### PR DESCRIPTION
**Pull request by ldorau**
Replace localtime() with localtime_r() in rpma_get_timestamp_prefix(),
because:
- localtime_r() has "MT-Safe env locale" attributes(7),
while
- localtime() has "MT-Unsafe race:tmbuf env locale" attributes(7).

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1859)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1859)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[`tests/drd.supp` line 102 at r1](https://reviewable.io/reviews/pmem/rpma/1859#-N5Er7j09pn9LvttHI6n:-N5Er7j17Cz7wJFpVHCz:ba3nlz7) ([raw file](https://github.com/pmem/rpma/blob/428e4c6847e7e5d032f310c5d72cf39ec646f6dc/tests/drd.supp#L102)):*
> ```
>    ...
>    fun:__tz_convert
>    ...
> ```

Let's keep full context here.
I do not understand this suppression:
```
# OS: ubuntu-2204:2022.04.1 of CircleCI
{
   Race while reading the name of time zone ("GMT").
   drd:ConflictingAccess
   fun:bcmp
   fun:__tzstring_len
   fun:__tzstring
   fun:__tzfile_compute
   fun:__tz_convert
   fun:rpma_log_default_function
   ...
}
```
where is such a path in the code?



_Suggestion:_
```
fun:rpma_get_timestamp_prefix
```
___
*[`tests/helgrind.supp` line 102 at r1](https://reviewable.io/reviews/pmem/rpma/1859#-N5EuRlr5oGrjy2G6Uzr:-N5EuRlr5oGrjy2G6Uzs:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/428e4c6847e7e5d032f310c5d72cf39ec646f6dc/tests/helgrind.supp#L102)):*
> ```
>    ...
>    fun:__tz_convert
>    ...
> ```

.



_Suggestion:_
```
fun:rpma_get_timestamp_prefix
```

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1859)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[`tests/drd.supp` line 98 at r1](https://reviewable.io/reviews/pmem/rpma/1859#-N5FD8M7EdBZrMfR7CSs:-N5FD8M7EdBZrMfR7CSt:undefined) ([raw file](https://github.com/pmem/rpma/blob/428e4c6847e7e5d032f310c5d72cf39ec646f6dc/tests/drd.supp#L98)):*
> ```
> #
> {
>    Race while reading the name of time zone ("GMT").
> ```





_Suggestion:_
```
{
   Race while reading the name of time zone ("GMT").
   drd:ConflictingAccess
   ...
   fun:__tz_convert
   fun:rpma_get_timestamp_prefix
   fun:rpma_log_default_function
   ...
}

{   
   Race while reading the name of time zone ("GMT"). false-positive due to unknown Valgrind issue on CircleCI
   drd:ConflictingAccess
   ...
   fun:__tz_convert
   ...
   fun:rpma_log_default_function
   ...
}
```
___
*[`tests/helgrind.supp` line 104 at r1](https://reviewable.io/reviews/pmem/rpma/1859#-N5FDeudAGcD3jIirGgz:-N5FDeudAGcD3jIirGh-:undefined) ([raw file](https://github.com/pmem/rpma/blob/428e4c6847e7e5d032f310c5d72cf39ec646f6dc/tests/helgrind.supp#L104)):*
> ```
>    ...
>    fun:rpma_log_default_function
>    ...
> ```





_Suggestion:_
```
{
   Race while reading the name of time zone ("GMT").
   Helgrind:Race
   ...
   fun:__tz_convert
   fun:rpma_get_timestamp_prefix
   fun:rpma_log_default_function
   ...
}
{
   Race while reading the name of time zone ("GMT"). false-positive due to unknown Valgrind issue on CircleCI
   Helgrind:Race
   ...
   fun:__tz_convert
   ...
   fun:rpma_log_default_function
   ...
}
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1859)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[`tests/drd.supp` line 98 at r1](https://reviewable.io/reviews/pmem/rpma/1859#-N5FD8M7EdBZrMfR7CSs:-N5FfU7_BX-TB2gGsG8a:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/428e4c6847e7e5d032f310c5d72cf39ec646f6dc/tests/drd.supp#L98)):*
> ```
> #
> {
>    Race while reading the name of time zone ("GMT").
> ```

Done.
___
*[`tests/helgrind.supp` line 104 at r1](https://reviewable.io/reviews/pmem/rpma/1859#-N5FDeudAGcD3jIirGgz:-N5FfT_H2f4asd7JJ1-d:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/428e4c6847e7e5d032f310c5d72cf39ec646f6dc/tests/helgrind.supp#L104)):*
> ```
>    ...
>    fun:rpma_log_default_function
>    ...
> ```

Done.

**Review by grom72 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1859)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1859#-:-N5Fmn-V6XGKVKQmnWpz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 4 of 6 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1859#-:-N5GEOUq-i-_r2uVeqGe:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Comment by ldorau** [comment]
Ref: https://github.com/pmem/rpma/issues/994

**Pull request merged**
