### PR TITLE
tools: remove the old Benchmarking toolchain

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1248)

### CODE REVIEW

**Review by ldorau — APPROVED** [review]
> Reviewed 30 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1248)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1248#-:-MiWNMu88_w_RBOtmKI1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 30 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1248)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1248#-MiWg0bK408Ov2eFcqMA:-MiWg0bK408Ov2eFcqMB:bf6w3ua) (no related file):*
Please also delete:

- https://github.com/osalyk/rpma/blob/delete_old_tool/tools/perf/create_report.py

Requires slight changes:

- https://github.com/osalyk/rpma/blob/delete_old_tool/tools/perf/templates/part_preamble.md
- https://github.com/osalyk/rpma/blob/delete_old_tool/tools/perf/templates/part_read.md

---
___
*[tools/perf/BENCHMARKING.md, line 114 at r1](https://reviewable.io/reviews/pmem/rpma/1248#-MiWesy89L7Bpf9Wabfl:-MiWesy9-z6c-62Guq5t:bxk8pxi) ([raw file](https://github.com/pmem/rpma/blob/e547f6bbf5b0eef4c542e01ccf7fe75ad8b136e5/tools/perf/BENCHMARKING.md#L114)):*
> ```Markdown
> ```
> 
> With the help of additional parameters, you can adjust various aspects of the output.
> ```

I recommend leaving this part as long as we document how to use the new toolset to achieve the same exact result achievable the way it is described now.
___
*[tools/perf/csv_compare.py, line 0 at r1](https://reviewable.io/reviews/pmem/rpma/1248#-MiWfEPQAVXdfWuql6bD:-MiWfEPQAVXdfWuql6bE:b-joc59l) ([raw file](https://github.com/pmem/rpma/blob/a959cc35123e1403cad9dd5f709971eb79650bc4/tools/perf/csv_compare.py#L0)):*
I recommend leaving it in the repo for a few more days.

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1248)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1248)* status: 28 of 33 files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1248#-MiWg0bK408Ov2eFcqMA:-MiWsQK_34NpD5E0YUO4:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please also delete:

- https://github.com/osalyk/rpma/blob/delete_old_tool/tools/perf/create_report.py

Requires slight changes:

- https://github.com/osalyk/rpma/blob/delete_old_tool/tools/perf/templates/part_preamble.md
- https://github.com/osalyk/rpma/blob/delete_old_tool/tools/perf/templates/part_read.md
</blockquote></details>

Done.

---
___
*[tools/perf/BENCHMARKING.md, line 114 at r1](https://reviewable.io/reviews/pmem/rpma/1248#-MiWesy89L7Bpf9Wabfl:-MiWrToa6CTyFRjLu3yo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e547f6bbf5b0eef4c542e01ccf7fe75ad8b136e5/tools/perf/BENCHMARKING.md#L114)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I recommend leaving this part as long as we document how to use the new toolset to achieve the same exact result achievable the way it is described now.
</blockquote></details>

Done.
___
*[tools/perf/csv_compare.py, line  at r1](https://reviewable.io/reviews/pmem/rpma/1248#-MiWfEPQAVXdfWuql6bD:-MiWrokB3U_DE9JewNUW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a959cc35123e1403cad9dd5f709971eb79650bc4/tools/perf/csv_compare.py#L)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I recommend leaving it in the repo for a few more days.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1248)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1248)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/BENCHMARKING.md, line 43 at r2](https://reviewable.io/reviews/pmem/rpma/1248#-MiWxgDq7Koco7zgKhgh:-MiWxgDq7Koco7zgKhgi:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/4f6c3e59a34d46ffc592396590ef5c8f8ef46986/tools/perf/BENCHMARKING.md#L43)):*
> ```Markdown
> ```
> 
> To use the reporting tools (e.g. `csv_compare.py`, `report_bench.py`, `report_figures.py`, `report_create.py`), you must additionally install:
> ```

.
___
*[tools/perf/csv_compare.py, line 122 at r2](https://reviewable.io/reviews/pmem/rpma/1248#-MiWxt7Z6aYW2NcwFURS:-MiWxt7Z6aYW2NcwFURT:b3kre) ([raw file](https://github.com/pmem/rpma/blob/4f6c3e59a34d46ffc592396590ef5c8f8ef46986/tools/perf/csv_compare.py#L122)):*
> ```Python
> def get_label(column):
>     """Find a text label for an axis describing a provided CSV column.
> ```

?

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1248)* status: 31 of 33 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/csv_compare.py, line 122 at r2](https://reviewable.io/reviews/pmem/rpma/1248#-MiWxt7Z6aYW2NcwFURS:-MiWzFac94HaiiZtF-q0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4f6c3e59a34d46ffc592396590ef5c8f8ef46986/tools/perf/csv_compare.py#L122)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done.
___
*[tools/perf/BENCHMARKING.md, line 43 at r2](https://reviewable.io/reviews/pmem/rpma/1248#-MiWxgDq7Koco7zgKhgh:-MiWz3kG2h_JY9m7UrV4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4f6c3e59a34d46ffc592396590ef5c8f8ef46986/tools/perf/BENCHMARKING.md#L43)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1248#-:-MiXPoIX5ihtRVxP6rQV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — COMMENTED** [review]
Shall we remove the whole old staff in one step? Or shall we remove old the part related to the complete report creation, and left i.e. csv_compare.py?

> Reviewed 1 of 30 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1248#-:-MiZicuk3-kiUgiyfqky:b-ssc025)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1248)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1248)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1248#-:-Mi_9fa60lKONLbOsj0X:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1248)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
