### PR TITLE
tools: add all report parts

### PR DESCRIPTION
**Pull request by janekmi**
- XXX workload configs are still missing (dummy)

Requires:
- [x] #808

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/814)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/814)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/templates/introduction.md.template, line 9 at r1](https://reviewable.io/reviews/pmem/rpma/814#-MSWIQRdDh3XsqJx0p49:-MSWIQRdDh3XsqJx0p4A:b-7q7pt4) ([raw file](https://github.com/pmem/rpma/blob/c8bdd20b344d2b6c53f4e163df8fa0ec3e1c5620/tools/templates/introduction.md.template#L9)):*
> ```
> six Intel&reg; Optane&trade; Persistent Memory devices
> ```
interleaving to be mentioned here
___
*[tools/templates/introduction.md.template, line 9 at r1](https://reviewable.io/reviews/pmem/rpma/814#-MSWIXkL1jHh4zvKDp9O:-MSWIXkL1jHh4zvKDp9P:b-543ib9) ([raw file](https://github.com/pmem/rpma/blob/c8bdd20b344d2b6c53f4e163df8fa0ec3e1c5620/tools/templates/introduction.md.template#L9)):*
> ```
> for 
> ```
on

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/814)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

___
*[tools/templates/introduction.md.template, line 9 at r1](https://reviewable.io/reviews/pmem/rpma/814#-MSWIQRdDh3XsqJx0p49:-MSWxUboCRksn5aPjgFe:b-uyzj2y) ([raw file](https://github.com/pmem/rpma/blob/c8bdd20b344d2b6c53f4e163df8fa0ec3e1c5620/tools/templates/introduction.md.template#L9)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> six Intel&reg; Optane&trade; Persistent Memory devices
> ```
interleaving to be mentioned here
</blockquote></details>

Not a part of this PR. #808
___
*[tools/templates/introduction.md.template, line 9 at r1](https://reviewable.io/reviews/pmem/rpma/814#-MSWIXkL1jHh4zvKDp9O:-MSWxZ9yE0wVOgm5oGF7:b-dyc0qd) ([raw file](https://github.com/pmem/rpma/blob/c8bdd20b344d2b6c53f4e163df8fa0ec3e1c5620/tools/templates/introduction.md.template#L9)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> for 
> ```
on
</blockquote></details>

Please repost in the #808

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/814)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/814#-:-MSXYrNz5HuqvAVPFiZq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
