### PR TITLE
examples: add rpma_mr_advise to the rest of examples

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1510)

### CODE REVIEW

**Review by haichangsi — COMMENTED** [review]
I some examples (e.g. 3) there was a problem with unused variable is_pmem when I tried to put her outside ifdef. That's why I decided to add my changes without ifdef

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1510#-:-MtwXC1K2sZTiJZHojnW:b-y55hyw)* status: 0 of 5 files reviewed, 1 unresolved discussion

___
*[examples/09-flush-to-persistent-GPSPM/server.c, line 202 at r1](https://reviewable.io/reviews/pmem/rpma/1510#-MtwX6vH6qIFFzgqn3m1:-MtwX6vH6qIFFzgqn3m2:b-q67zob) ([raw file](https://github.com/pmem/rpma/blob/e87f2d18b5679b769f7f9bf48da0487880d72772/examples/09-flush-to-persistent-GPSPM/server.c#L202)):*
> ```C
> 		/* rpma_mr_advise() should be called only in case of FsDAX */
> 		if (is_pmem && strstr(path, "/dev/dax") == NULL) {
> 			ret = rpma_mr_advise(msg_mr, 0, KILOBYTE,
> ```

I am not sure if I should use a different offset here

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1510)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1510#-MtwZoXZ19bxABKAHN9p):*
examples: add rpma_mr_advise to rest of examples



_Code quote:_
```
examples: add rpma_mr_advise
```
___
*[examples/09-flush-to-persistent-GPSPM/server.c, line 199 at r1](https://reviewable.io/reviews/pmem/rpma/1510#-Mtw_aBH5vy_H9y_-1b4:-Mtw_aBH5vy_H9y_-1b5:b4xrp75) ([raw file](https://github.com/pmem/rpma/blob/e87f2d18b5679b769f7f9bf48da0487880d72772/examples/09-flush-to-persistent-GPSPM/server.c#L199)):*
> ```C
> 
> 		if (argc >= 4) {
> 		char *path = argv[3];
> ```

Wrong indentation



_Code quote:_
```C
		if (argc >= 4) {
		char *path = argv[3];
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1510)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[examples/09-flush-to-persistent-GPSPM/server.c, line 178 at r1](https://reviewable.io/reviews/pmem/rpma/1510#-Mtw_mLR-oeopcSoW0EV:-Mtw_mLR-oeopcSoW0EW:b4xrp75) ([raw file](https://github.com/pmem/rpma/blob/e87f2d18b5679b769f7f9bf48da0487880d72772/examples/09-flush-to-persistent-GPSPM/server.c#L178)):*
> ```C
> 
> 		if (argc >= 4) {
> 		char *path = argv[3];
> ```

Wrong indentation



_Code quote:_
```C
		if (argc >= 4) {
		char *path = argv[3];
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1510)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[examples/09-flush-to-persistent-GPSPM/server.c, line 175 at r1](https://reviewable.io/reviews/pmem/rpma/1510#-Mtwagxo1E9Sp3Hw_Wuy:-Mtwagxo1E9Sp3Hw_Wuz:bz0emnb) ([raw file](https://github.com/pmem/rpma/blob/e87f2d18b5679b769f7f9bf48da0487880d72772/examples/09-flush-to-persistent-GPSPM/server.c#L175)):*
> ```C
> 				RPMA_MR_USAGE_FLUSH_TYPE_VISIBILITY),
> 			&mr)))
> 		goto err_ep_shutdown;
> ```

Lack of `}` at the end



_Code quote:_
```C
	/* register the memory */
	if ((ret = rpma_mr_reg(peer, mr_ptr, mr_size,
			RPMA_MR_USAGE_WRITE_DST |
			(is_pmem ? RPMA_MR_USAGE_FLUSH_TYPE_PERSISTENT :
				RPMA_MR_USAGE_FLUSH_TYPE_VISIBILITY),
			&mr)))
		goto err_ep_shutdown;
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1510)* status: 4 of 5 files reviewed, 5 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[examples/09-flush-to-persistent-GPSPM/server.c, line 175 at r1](https://reviewable.io/reviews/pmem/rpma/1510#-Mtwagxo1E9Sp3Hw_Wuy:-Mtwg5bB9_p5NgrS0fFi:b784xuy) ([raw file](https://github.com/pmem/rpma/blob/e87f2d18b5679b769f7f9bf48da0487880d72772/examples/09-flush-to-persistent-GPSPM/server.c#L175)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Lack of `}` at the end
</blockquote></details>

It is a one line if
___
*[examples/09-flush-to-persistent-GPSPM/server.c, line 178 at r1](https://reviewable.io/reviews/pmem/rpma/1510#-Mtw_mLR-oeopcSoW0EV:-MtwgI659LIIthvTwGDo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e87f2d18b5679b769f7f9bf48da0487880d72772/examples/09-flush-to-persistent-GPSPM/server.c#L178)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Wrong indentation
</blockquote></details>

Done.
___
*[examples/09-flush-to-persistent-GPSPM/server.c, line 199 at r1](https://reviewable.io/reviews/pmem/rpma/1510#-Mtw_aBH5vy_H9y_-1b4:-MtwgIgk6nhYYIbLKlr_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e87f2d18b5679b769f7f9bf48da0487880d72772/examples/09-flush-to-persistent-GPSPM/server.c#L199)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Wrong indentation
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1510)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[examples/09-flush-to-persistent-GPSPM/server.c, line 175 at r1](https://reviewable.io/reviews/pmem/rpma/1510#-Mtwagxo1E9Sp3Hw_Wuy:-Mtwj3jvBa2lktsB8qz-:b-nilirk) ([raw file](https://github.com/pmem/rpma/blob/e87f2d18b5679b769f7f9bf48da0487880d72772/examples/09-flush-to-persistent-GPSPM/server.c#L175)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

It is a one line if
</blockquote></details>

You are right :-)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1510)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @haichangsi)

___
*[examples/09-flush-to-persistent-GPSPM/server.c, line 202 at r1](https://reviewable.io/reviews/pmem/rpma/1510#-MtwX6vH6qIFFzgqn3m1:-Mtwl8p0B4MNzZlPEGSa:behxas1) ([raw file](https://github.com/pmem/rpma/blob/e87f2d18b5679b769f7f9bf48da0487880d72772/examples/09-flush-to-persistent-GPSPM/server.c#L202)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

I am not sure if I should use a different offset here
</blockquote></details>

The second `if ` is not needed, because the messaging memory is always in DRAM
___
*[examples/09-flush-to-persistent-GPSPM/server.c, line 198 at r2](https://reviewable.io/reviews/pmem/rpma/1510#-MtwkoS01KOI45OrsXou:-MtwkoS01KOI45OrsXov:behxas1) ([raw file](https://github.com/pmem/rpma/blob/014b9693ff05c86387164f5b79ea6cc6f083864e/examples/09-flush-to-persistent-GPSPM/server.c#L198)):*
> ```C
> 	}
> 
> 	if (argc >= 4) {
> ```

The second `if ` is not needed, because the messaging memory is always in DRAM



_Code quote:_
```C
if (argc >= 4) {
```

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1510)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

**Review by ldorau — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1510)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1510)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1510)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

___
*[examples/03-read-to-persistent/server.c, line 94 at r4](https://reviewable.io/reviews/pmem/rpma/1510#-MtwyXVh3DQ5oeJ9s5j2:-MtwyXVh3DQ5oeJ9s5j3:b-yqm2zq) ([raw file](https://github.com/pmem/rpma/blob/23001208d10b820a85a4af044403dddc585b7c11/examples/03-read-to-persistent/server.c#L94)):*
> ```C
> 		if (mr_size - dst_offset < KILOBYTE) {
> 			fprintf(stderr, "%s too small (%zu < %zu)\n",
> 					path, mr_size, KILOBYTE + dst_offset);
> ```

pmem_path



_Code quote:_
```C
path
```

**Review by ldorau — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1510#-:-MtwzhU27Sx_iGYsW8lD:bdycpsm)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1510)* status: all files reviewed, 7 unresolved discussions (waiting on @haichangsi)

___
*[examples/03-read-to-persistent/server.c, line 43 at r4](https://reviewable.io/reviews/pmem/rpma/1510#-Mtx5EIj8NZx80UU4LNf:-Mtx5EIj8NZx80UU4LNg:b68e5h3) ([raw file](https://github.com/pmem/rpma/blob/23001208d10b820a85a4af044403dddc585b7c11/examples/03-read-to-persistent/server.c#L43)):*
> ```C
> 	char *port = argv[2];
> 	char *pmem_path = NULL;
> 	if (argc >= 4)
> ```

#ifdef USE_LIBPMEM
	char *pmem_path = NULL;
	if (argc >= 4)
		pmem_path = argv[3];
#endif



_Code quote:_
```C
	char *pmem_path = NULL;
	if (argc >= 4)
		pmem_path = argv[3];
```
___
*[examples/04-write-to-persistent/server.c, line 50 at r4](https://reviewable.io/reviews/pmem/rpma/1510#-Mtx4GD6E8c87cKGrcID:-Mtx4GD6E8c87cKGrcIE:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/23001208d10b820a85a4af044403dddc585b7c11/examples/04-write-to-persistent/server.c#L50)):*
> ```C
> 	char *addr = argv[1];
> 	char *port = argv[2];
> 	char *pmem_path = NULL;
> ```

.



_Code quote:_
```C
	char *pmem_path = NULL;
	if (argc >= 4)
		pmem_path = argv[3];
```
___
*[examples/05-flush-to-persistent/server.c, line 46 at r4](https://reviewable.io/reviews/pmem/rpma/1510#-Mtx4NtA5Z_KPyx9Kp2F:-Mtx4NtA5Z_KPyx9Kp2G:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/23001208d10b820a85a4af044403dddc585b7c11/examples/05-flush-to-persistent/server.c#L46)):*
> ```C
> 	char *addr = argv[1];
> 	char *port = argv[2];
> 	char *pmem_path = NULL;
> ```

.



_Code quote:_
```C
	char *pmem_path = NULL;
	if (argc >= 4)
		pmem_path = argv[3];
```
___
*[examples/07-atomic-write/server.c, line 56 at r4](https://reviewable.io/reviews/pmem/rpma/1510#-Mtx4R0w9xfJaI252Xwy:-Mtx4R0w9xfJaI252Xwz:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/23001208d10b820a85a4af044403dddc585b7c11/examples/07-atomic-write/server.c#L56)):*
> ```C
> 	char *addr = argv[1];
> 	char *port = argv[2];
> 	char *pmem_path = NULL;
> ```

.



_Code quote:_
```C
	char *pmem_path = NULL;
	if (argc >= 4)
		pmem_path = argv[3];
```
___
*[examples/09-flush-to-persistent-GPSPM/server.c, line 46 at r4](https://reviewable.io/reviews/pmem/rpma/1510#-Mtx4SfWEo1O5TXJPvuP:-Mtx4SfWEo1O5TXJPvuQ:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/23001208d10b820a85a4af044403dddc585b7c11/examples/09-flush-to-persistent-GPSPM/server.c#L46)):*
> ```C
> 	char *addr = argv[1];
> 	char *port = argv[2];
> 	char *pmem_path = NULL;
> ```

.



_Code quote:_
```C
	char *pmem_path = NULL;
	if (argc >= 4)
		pmem_path = argv[3];
```

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1510)* status: all files reviewed, 8 unresolved discussions (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1510#-Mtx5uYJD1vjmyRnjhtf:-Mtx5uYJD1vjmyRnjhtg:b-tipptm) (no related file):*
All changes in this PR shall be wrapped with
``` 
#ifdef USE_LIBPMEM
...
#endif
```



_Code quote (from examples/03-read-to-persistent/server.c):_
```C
#ifdef USE_LIBPMEM
```

---

**Review by grom72 — COMMENTED** [review]
> Reviewed 4 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1510)* status: all files reviewed, 8 unresolved discussions (waiting on @haichangsi)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1510)* status: all files reviewed, 8 unresolved discussions (waiting on @haichangsi)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1510)* status: all files reviewed, 8 unresolved discussions (waiting on @grom72 and @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1510#-Mtx5uYJD1vjmyRnjhtf:-Mtx99Oo4my55K0IdZPq:bh89l1a) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

All changes in this PR shall be wrapped with
``` 
#ifdef USE_LIBPMEM
...
#endif
```
</blockquote></details>

No, `#ifdef USE_LIBPMEM` can be used only in places where libpmem is required

---

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1510)* status: all files reviewed, 8 unresolved discussions (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1510#-Mtx5uYJD1vjmyRnjhtf:-Mtx9pda0BHZd4phxMFj:b-dydbla) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No, `#ifdef USE_LIBPMEM` can be used only in places where libpmem is required
</blockquote></details>

the problem is that new code (below) shall be wrapped as it is only possible when libpmem is used



_Code quote (from examples/04-write-to-persistent/server.c):_
```C
	/* rpma_mr_advise() should be called only in case of FsDAX */
	if (is_pmem && strstr(pmem_path, "/dev/dax") == NULL) {
		ret = rpma_mr_advise(mr, 0, mr_size,
			IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE,
			IBV_ADVISE_MR_FLAG_FLUSH);
		if (ret)
			goto err_mr_dereg;
	}
```

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1510)* status: all files reviewed, 8 unresolved discussions (waiting on @grom72 and @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1510#-Mtx5uYJD1vjmyRnjhtf:-MtxC5mSEmNnqioYGLTT:b-vi194c) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

the problem is that new code (below) shall be wrapped as it is only possible when libpmem is used
</blockquote></details>

OK, you are right.

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1510)* status: all files reviewed, 9 unresolved discussions (waiting on @grom72 and @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1510#-MtxCrI2811AOMGMHtLu:-MtxCrI36X_o4HogohbU:b-qkpvsw) (no related file):*
Rebase on the current master, please

---

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1510)* status: 0 of 5 files reviewed, 8 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 4 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1510)* status: 4 of 5 files reviewed, 7 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1510#-:-MuAPWVrEn_d2phY5_uk:bnfp4nl)* status: 4 of 5 files reviewed, 6 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

**Review by ldorau — APPROVED** [review]
> Reviewed 5 of 5 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1510)* status: all files reviewed, 5 unresolved discussions (waiting on @haichangsi)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1510)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1510#-:-MuAQiSLC78F4U9oUieG:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

**Pull request merged**
