### PR TITLE
examples: incorporate peer's configuration 

### PR DESCRIPTION
**Pull request by janekmi**
Requires:
- [x] #382
- [x] #378 

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/384)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
> Reviewed 6 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/384)* status: 6 of 11 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[examples/05-flush-to-persistent/server.c, line 154 at r1](https://reviewable.io/reviews/pmem/rpma/384#-MGqpIS10QINp9j_uiMv:-MGqpIS10QINp9j_uiMw:bd524ec) ([raw file](https://github.com/pmem/rpma/blob/634c853db2fdafa6dca449a12b8003458866835f/examples/05-flush-to-persistent/server.c#L154)):*
> ```C
> 
> 	/* configure peer's auto flush state */
> 	if (argc >= 6) {
> ```

argc == 6

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/384)* status: 6 of 11 files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[examples/05-flush-to-persistent/server.c, line 154 at r1](https://reviewable.io/reviews/pmem/rpma/384#-MGqpIS10QINp9j_uiMv:-MGr7xMg7kGm8L3hL3n9:b-iddtts) ([raw file](https://github.com/pmem/rpma/blob/634c853db2fdafa6dca449a12b8003458866835f/examples/05-flush-to-persistent/server.c#L154)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

argc == 6
</blockquote></details>

I really don't care whether the user provided any additional strings. ;-)

**Review by ldorau — COMMENTED** [review]
@janekmi please rebase

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/384#-:-MGs46KhEbd5_yANXkwm:b-f7mnt4)* status: 6 of 11 files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
> Reviewed 4 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/384)* status: 6 of 11 files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
> Reviewed 3 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/384)* status: 9 of 11 files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/384)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[examples/05-flush-to-persistent/README.md, line 32 at r2](https://reviewable.io/reviews/pmem/rpma/384#-MGsCL0v0PR4lYxagAik:-MGsCL0v0PR4lYxagAil:b-d7x3gr) ([raw file](https://github.com/pmem/rpma/blob/f83b965f4e1d219f9c9e841017020f57d6cd888f/examples/05-flush-to-persistent/README.md#L32)):*
> ```Markdown
> 
> ```bash
> [user@server]$ ./server $server_address $port [<pmem-path>] [<ddio>] [<auto_flush>]
> ```

`examples/run-all-on-SoftRoCE.sh` can be updated to reflect those changes

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/384)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[examples/05-flush-to-persistent/README.md, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/384#-MGsCZDg6En-FEti2wUD:-MGsCZDg6En-FEti2wUE:b-ukshsw) ([raw file](https://github.com/pmem/rpma/blob/f83b965f4e1d219f9c9e841017020f57d6cd888f/examples/05-flush-to-persistent/README.md#L15)):*
> ```
> is allowed
> ```

`it is allowed`
___
*[examples/05-flush-to-persistent/README.md, line 16 at r2](https://reviewable.io/reviews/pmem/rpma/384#-MGsCgtd3bHtcHL2ePtG:-MGsCgtd3bHtcHL2ePtH:b55no8m) ([raw file](https://github.com/pmem/rpma/blob/f83b965f4e1d219f9c9e841017020f57d6cd888f/examples/05-flush-to-persistent/README.md#L16)):*
> ```
> on current
> ```

`on the current`

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/384)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/384)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi)

___
*[examples/05-flush-to-persistent/server.c, line 113 at r2](https://reviewable.io/reviews/pmem/rpma/384#-MGsDvUDCv2y0Wef9jIO:-MGsDvUDCv2y0Wef9jIP:b-nsqcu9) ([raw file](https://github.com/pmem/rpma/blob/f83b965f4e1d219f9c9e841017020f57d6cd888f/examples/05-flush-to-persistent/server.c#L113)):*
> ```C
> 	}
> #endif /* USE_LIBPMEM */
> ```

redundant empty line
___
*[examples/05-flush-to-persistent/server.c, line 144 at r2](https://reviewable.io/reviews/pmem/rpma/384#-MGsE4dL0nU9N8QcbaHU:-MGsE4dL0nU9N8QcbaHV:b1piqbl) ([raw file](https://github.com/pmem/rpma/blob/f83b965f4e1d219f9c9e841017020f57d6cd888f/examples/05-flush-to-persistent/server.c#L144)):*
> ```
> rpma_peer_cfg_set_ddio
> ```

There is no such function now.
___
*[examples/05-flush-to-persistent/server.c, line 155 at r2](https://reviewable.io/reviews/pmem/rpma/384#-MGsEBMTChL1jbIb7r3G:-MGsEBMTChL1jbIb7r3H:b-k55eep) ([raw file](https://github.com/pmem/rpma/blob/f83b965f4e1d219f9c9e841017020f57d6cd888f/examples/05-flush-to-persistent/server.c#L155)):*
> ```
> rpma_peer_cfg_set_auto_flush
> ```

There is no such function now.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/384)* status: all files reviewed, 8 unresolved discussions (waiting on @janekmi)

___
*[examples/07-atomic-write/client.c, line 78 at r2](https://reviewable.io/reviews/pmem/rpma/384#-MGsEPQTCoU6UsCl1C1Z:-MGsEPQTCoU6UsCl1C1_:bduzlfr) ([raw file](https://github.com/pmem/rpma/blob/f83b965f4e1d219f9c9e841017020f57d6cd888f/examples/07-atomic-write/client.c#L78)):*
> ```
> rpma_peer_cfg_set_ddio(
> ```

There is no such function now.
___
*[examples/07-atomic-write/client.c, line 80 at r2](https://reviewable.io/reviews/pmem/rpma/384#-MGsERJs0xXmXnFo8qwB:-MGsERJs0xXmXnFo8qwC:b8bszle) ([raw file](https://github.com/pmem/rpma/blob/f83b965f4e1d219f9c9e841017020f57d6cd888f/examples/07-atomic-write/client.c#L80)):*
> ```
> rpma_peer_cfg_get_persistent_flush_supported
> ```

There is no such function now.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 9 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/384)* status: all files reviewed, 8 unresolved discussions (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/384)* status: 0 of 17 files reviewed, 8 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[examples/05-flush-to-persistent/README.md, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/384#-MGsCZDg6En-FEti2wUD:-MGwDIAX3DhYeto1WoIg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f83b965f4e1d219f9c9e841017020f57d6cd888f/examples/05-flush-to-persistent/README.md#L15)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> is allowed
> ```

`it is allowed`
</blockquote></details>

Done.
___
*[examples/05-flush-to-persistent/README.md, line 16 at r2](https://reviewable.io/reviews/pmem/rpma/384#-MGsCgtd3bHtcHL2ePtG:-MGwDJFNCsoJKqWg4rd_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f83b965f4e1d219f9c9e841017020f57d6cd888f/examples/05-flush-to-persistent/README.md#L16)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> on current
> ```

`on the current`
</blockquote></details>

Done.
___
*[examples/05-flush-to-persistent/README.md, line 32 at r2](https://reviewable.io/reviews/pmem/rpma/384#-MGsCL0v0PR4lYxagAik:-MGwFn4j8kuox-AhRYru:bp7rcug) ([raw file](https://github.com/pmem/rpma/blob/f83b965f4e1d219f9c9e841017020f57d6cd888f/examples/05-flush-to-persistent/README.md#L32)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`examples/run-all-on-SoftRoCE.sh` can be updated to reflect those changes
</blockquote></details>

At this point, we are do not providing any PMem path so I think we can for now skip this also.
___
*[examples/05-flush-to-persistent/server.c, line 113 at r2](https://reviewable.io/reviews/pmem/rpma/384#-MGsDvUDCv2y0Wef9jIO:-MGwCkmV2AwbR-klM6-D:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f83b965f4e1d219f9c9e841017020f57d6cd888f/examples/05-flush-to-persistent/server.c#L113)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

redundant empty line
</blockquote></details>

Done.
___
*[examples/05-flush-to-persistent/server.c, line 144 at r2](https://reviewable.io/reviews/pmem/rpma/384#-MGsE4dL0nU9N8QcbaHU:-MGwClIYDygjDC8Iv38u:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f83b965f4e1d219f9c9e841017020f57d6cd888f/examples/05-flush-to-persistent/server.c#L144)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> rpma_peer_cfg_set_ddio
> ```

There is no such function now.
</blockquote></details>

Done.
___
*[examples/05-flush-to-persistent/server.c, line 155 at r2](https://reviewable.io/reviews/pmem/rpma/384#-MGsEBMTChL1jbIb7r3G:-MGwClq0EPacXg-jBDTP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f83b965f4e1d219f9c9e841017020f57d6cd888f/examples/05-flush-to-persistent/server.c#L155)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> rpma_peer_cfg_set_auto_flush
> ```

There is no such function now.
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 78 at r2](https://reviewable.io/reviews/pmem/rpma/384#-MGsEPQTCoU6UsCl1C1Z:-MGwEumwEan5yPL8CCVr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f83b965f4e1d219f9c9e841017020f57d6cd888f/examples/07-atomic-write/client.c#L78)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> rpma_peer_cfg_set_ddio(
> ```

There is no such function now.
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 80 at r2](https://reviewable.io/reviews/pmem/rpma/384#-MGsERJs0xXmXnFo8qwB:-MGwEv2m25NLLCaNGkED:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f83b965f4e1d219f9c9e841017020f57d6cd888f/examples/07-atomic-write/client.c#L80)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> rpma_peer_cfg_get_persistent_flush_supported
> ```

There is no such function now.
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 12 of 23 files at r3, 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/384)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[examples/05-flush-to-persistent/README.md, line 32 at r2](https://reviewable.io/reviews/pmem/rpma/384#-MGsCL0v0PR4lYxagAik:-MGwL0b9A9WPjq-cahIP:b32w0x) ([raw file](https://github.com/pmem/rpma/blob/f83b965f4e1d219f9c9e841017020f57d6cd888f/examples/05-flush-to-persistent/README.md#L32)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

At this point, we are do not providing any PMem path so I think we can for now skip this also.
</blockquote></details>

OK

**Review by ldorau — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/384#-:-MGwLcb363ECBDe2wYnx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> Reviewed 4 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/384)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi)

___
*[examples/05-flush-to-persistent/README.md, line 31 at r5](https://reviewable.io/reviews/pmem/rpma/384#-MGwskZo0Xt_CxOGyt-O:-MGwskZo0Xt_CxOGyt-P:b42jp05) ([raw file](https://github.com/pmem/rpma/blob/8496299b46239766bb82dd4528a0bee9fdfaa615/examples/05-flush-to-persistent/README.md#L31)):*
> ```
> [<ddio>] [<auto_flush>]
> ```
different usage than the one defined in server.c
___
*[examples/05-flush-to-persistent/server.c, line 19 at r5](https://reviewable.io/reviews/pmem/rpma/384#-MGwpwZf3poXJNOvKiQ8:-MGwpwZg8wls9gqJm4tu:baf5giu) ([raw file](https://github.com/pmem/rpma/blob/8496299b46239766bb82dd4528a0bee9fdfaa615/examples/05-flush-to-persistent/server.c#L19)):*
> ```
> direct-pmem-write
> ```
would it be better to use well-known terminology of ddio?

it is not clear that instead of [direct-pmem-write] we should type "on"

An example of a call will be very helpful here ...
___
*[examples/05-flush-to-persistent/server.c, line 147 at r5](https://reviewable.io/reviews/pmem/rpma/384#-MGwrmuA5OjRWcsNN82h:-MGwrmuA5OjRWcsNN82i:b-1by9hb) ([raw file](https://github.com/pmem/rpma/blob/8496299b46239766bb82dd4528a0bee9fdfaa615/examples/05-flush-to-persistent/server.c#L147)):*
> ```
> (void) rpma_peer_cfg_delete(&pcfg);
> 			goto err_free;
> ```
```
goto err_pcfg_delete;
```
___
*[examples/05-flush-to-persistent/server.c, line 221 at r5](https://reviewable.io/reviews/pmem/rpma/384#-MGwsHyHBDq-t14Suz1m:-MGwsHyHBDq-t14Suz1n:bkhyftv) ([raw file](https://github.com/pmem/rpma/blob/8496299b46239766bb82dd4528a0bee9fdfaa615/examples/05-flush-to-persistent/server.c#L221)):*
> ```
> err_free:
> ```
```
err_mr_free
```
___
*[examples/07-atomic-write/client.c, line 194 at r5](https://reviewable.io/reviews/pmem/rpma/384#-MGws_-G66LLNgZEICHj:-MGws_-H1IBJzH3RSQSH:b3x0mq9) ([raw file](https://github.com/pmem/rpma/blob/8496299b46239766bb82dd4528a0bee9fdfaa615/examples/07-atomic-write/client.c#L194)):*
> ```
> err_free
> ```
.
___
*[examples/07-atomic-write/README.md, line 31 at r5](https://reviewable.io/reviews/pmem/rpma/384#-MGwtWt01PgMxo_MPUXC:-MGwtWt1BQAidKwTAyFz:bfcs1l8) ([raw file](https://github.com/pmem/rpma/blob/8496299b46239766bb82dd4528a0bee9fdfaa615/examples/07-atomic-write/README.md#L31)):*
> ```Markdown
> **Note**: For the sake of simplicity, the client assumes unilaterally that
> the server has the persistent flush support.
> ```

can we reuse solution from example 05?

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/384)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi)

___
*[examples/05-flush-to-persistent/server.c, line 19 at r5](https://reviewable.io/reviews/pmem/rpma/384#-MGwpwZf3poXJNOvKiQ8:-MHLL7wr3QxgzmwDXB-c:b-i7hiwf) ([raw file](https://github.com/pmem/rpma/blob/8496299b46239766bb82dd4528a0bee9fdfaa615/examples/05-flush-to-persistent/server.c#L19)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> direct-pmem-write
> ```
would it be better to use well-known terminology of ddio?

it is not clear that instead of [direct-pmem-write] we should type "on"

An example of a call will be very helpful here ...
</blockquote></details>

:lizard:

**Pull request merged**
