### PR TITLE
test: use simulated errno on all unit tests

### PR DESCRIPTION
**Pull request by yangx-jy**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1093)

### CODE REVIEW

**Review by yangx-jy — COMMENTED** [review]
https://app.circleci.com/pipelines/github/pmem/rpma/238/workflows/067a62c6-df79-4336-aac5-923bdd5ade6c/jobs/245

 issue #1079  instead of this PR caused the failure of MT-test. 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1093#-:-McE-iiiD9iPo5dgwTRn:b9xmez2)* status: 0 of 22 files reviewed, all discussions resolved

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 7 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1093)* status: 7 of 22 files reviewed, 6 unresolved discussions (waiting on @yangx-jy)

___
*[tests/unit/conn/conn-new.c, line 322 at r1](https://reviewable.io/reviews/pmem/rpma/1093#-McPD0lSEWWmaNZwfg2O:-McPD0lSEWWmaNZwfg2P:b-mytih1) ([raw file](https://github.com/pmem/rpma/blob/e37d46f075f184959022a03fef73794bbca0aaca/tests/unit/conn/conn-new.c#L322)):*
> ... after rpma_cq_delete() **failed** with MOCK_ERRNO
___
*[tests/unit/conn/conn-next_event.c, line 159 at r1](https://reviewable.io/reviews/pmem/rpma/1093#-McPDMLv21xMV9oNC0Mc:-McPDMLv21xMV9oNC0Md:b-nddavj) ([raw file](https://github.com/pmem/rpma/blob/e37d46f075f184959022a03fef73794bbca0aaca/tests/unit/conn/conn-next_event.c#L159)):*
> ```C
> 
> /*
>  * next_event__data_store_E_NOMEM - rpma_private_data_store fails
> ```

rpma_private_data_store **()**
___
*[tests/unit/conn_req/conn_req-delete.c, line 75 at r1](https://reviewable.io/reviews/pmem/rpma/1093#-McPE7rQ2LzG1_VDmro_:-McPE7rR38w5gzuWJNw1:b-s433r6) ([raw file](https://github.com/pmem/rpma/blob/e37d46f075f184959022a03fef73794bbca0aaca/tests/unit/conn_req/conn_req-delete.c#L75)):*
> rpma_cq_delete() fails with MOCK_ERRNO whereas subsequent (rdma_reject(), rdma_ack_cm_event()) fails with MOCK_ERRNO2
___
*[tests/unit/conn_req/conn_req-delete.c, line 218 at r1](https://reviewable.io/reviews/pmem/rpma/1093#-McPEo2rDs-flzi95--5:-McPEo2rDs-flzi95--6:b-o4fqz2) ([raw file](https://github.com/pmem/rpma/blob/e37d46f075f184959022a03fef73794bbca0aaca/tests/unit/conn_req/conn_req-delete.c#L218)):*
> ```C
> /*
>  * delete_via_destroy__cq_delete_ERRNO_subsequent_ERRNO2 --
>  * rdma_destroy_id() fail with MOCK_ERRNO2 after rpma_cq_delete()
> ```

rdma_destroy_id() **fails** with...
___
*[tests/unit/conn_req/conn_req-from_cm_event.c, line 163 at r1](https://reviewable.io/reviews/pmem/rpma/1093#-McPFAUt9npHtqU_pD6Z:-McPFAUt9npHtqU_pD6_:bj1b1ci) ([raw file](https://github.com/pmem/rpma/blob/e37d46f075f184959022a03fef73794bbca0aaca/tests/unit/conn_req/conn_req-from_cm_event.c#L163)):*
> ```C
> /*
>  * from_cm_event__create_qp_ERRNO_subsequent_ERRNO2 -- rpma_peer_create_qp()
>  * fails with MOCK_ERRNO followed by rpma_cq_delete() fails with MOCK_ERRNO2
> ```

rpma_peer_create_qp() fails with MOCK_ERRNO2 after rpma_cq_delete() failed with MOCK_ERRNO
___
*[tests/unit/conn_req/conn_req-from_cm_event.c, line 226 at r1](https://reviewable.io/reviews/pmem/rpma/1093#-McPuXey3aWnachZgvvn:-McPuXey3aWnachZgvvo:b-uej6ha) ([raw file](https://github.com/pmem/rpma/blob/e37d46f075f184959022a03fef73794bbca0aaca/tests/unit/conn_req/conn_req-from_cm_event.c#L226)):*
> ```C
> /*
>  * from_cm_event__malloc_ERRNO_subsequent_ERRNO2 -- malloc() fails with
>  * MOCK_ERRNO followed by rpma_cq_delete() fails with MOCK_ERRNO2
> ```

rpma_cq_delete() fails with MOCK_ERRNO2 after malloc() failed with MOCK_ERRNO

**Review by yangx-jy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1093)* status: 3 of 22 files reviewed, 6 unresolved discussions (waiting on @janekmi)

___
*[tests/unit/conn/conn-new.c, line 322 at r1](https://reviewable.io/reviews/pmem/rpma/1093#-McPD0lSEWWmaNZwfg2O:-McSWYNt5IEtM5SHwZrG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e37d46f075f184959022a03fef73794bbca0aaca/tests/unit/conn/conn-new.c#L322)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

> ... after rpma_cq_delete() **failed** with MOCK_ERRNO
</blockquote></details>

Done.
___
*[tests/unit/conn/conn-next_event.c, line 159 at r1](https://reviewable.io/reviews/pmem/rpma/1093#-McPDMLv21xMV9oNC0Mc:-McSW_BY6lf_Vim0wcLW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e37d46f075f184959022a03fef73794bbca0aaca/tests/unit/conn/conn-next_event.c#L159)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

rpma_private_data_store **()**
</blockquote></details>

Done.
___
*[tests/unit/conn_req/conn_req-delete.c, line 75 at r1](https://reviewable.io/reviews/pmem/rpma/1093#-McPE7rQ2LzG1_VDmro_:-McSD3wM8OFjUL4w5Y1g:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e37d46f075f184959022a03fef73794bbca0aaca/tests/unit/conn_req/conn_req-delete.c#L75)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

> rpma_cq_delete() fails with MOCK_ERRNO whereas subsequent (rdma_reject(), rdma_ack_cm_event()) fails with MOCK_ERRNO2
</blockquote></details>

Done.
___
*[tests/unit/conn_req/conn_req-delete.c, line 218 at r1](https://reviewable.io/reviews/pmem/rpma/1093#-McPEo2rDs-flzi95--5:-McSD3IR1RQ8PEFa1PHv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e37d46f075f184959022a03fef73794bbca0aaca/tests/unit/conn_req/conn_req-delete.c#L218)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

rdma_destroy_id() **fails** with...
</blockquote></details>

Done.
___
*[tests/unit/conn_req/conn_req-from_cm_event.c, line 163 at r1](https://reviewable.io/reviews/pmem/rpma/1093#-McPFAUt9npHtqU_pD6Z:-McSY1Yb0scsG5zsNwcx:b-5yvzgo) ([raw file](https://github.com/pmem/rpma/blob/e37d46f075f184959022a03fef73794bbca0aaca/tests/unit/conn_req/conn_req-from_cm_event.c#L163)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

rpma_peer_create_qp() fails with MOCK_ERRNO2 after rpma_cq_delete() failed with MOCK_ERRNO
</blockquote></details>

Done.

Should be  "rpma_cq_delete() fails with MOCK_ERRNO2 after rpma_peer_create_qp() failed with MOCK_ERRNO"
___
*[tests/unit/conn_req/conn_req-from_cm_event.c, line 226 at r1](https://reviewable.io/reviews/pmem/rpma/1093#-McPuXey3aWnachZgvvn:-McSYTzaCNLiz-3_FnN1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e37d46f075f184959022a03fef73794bbca0aaca/tests/unit/conn_req/conn_req-from_cm_event.c#L226)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

rpma_cq_delete() fails with MOCK_ERRNO2 after malloc() failed with MOCK_ERRNO
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
> Reviewed 4 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1093)* status: 7 of 22 files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 22 files at r1, 2 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1093)* status: 11 of 22 files reviewed, 6 unresolved discussions (waiting on @yangx-jy)

___
*[tests/unit/conn_req/conn_req-new.c, line 345 at r2](https://reviewable.io/reviews/pmem/rpma/1093#-McTm6fh77cItBaZnlJn:-McTm6fh77cItBaZnlJo:b4f1xbz) ([raw file](https://github.com/pmem/rpma/blob/7e7ccbded0964a0a8417d6a25943e472f736571e/tests/unit/conn_req/conn_req-new.c#L345)):*
> ```C
> /*
>  * new__malloc_ERRNO_subsequent_ERRNO2 -- malloc() fails with MOCK_ERRNO
>  * whereas subsequent calls fail with MOCK_ERRNO2
> ```

... subsequent (rpma_cq_delete(), rdma_destroy_id()) fail with...
___
*[tests/unit/cq/cq-new_delete.c, line 65 at r2](https://reviewable.io/reviews/pmem/rpma/1093#-McTmeTa77EaZNTTDpiB:-McTmeTb1MBylEei2P-f:b-dgw6ie) ([raw file](https://github.com/pmem/rpma/blob/7e7ccbded0964a0a8417d6a25943e472f736571e/tests/unit/cq/cq-new_delete.c#L65)):*
> ```C
>  * new__create_cq_ERRNO_subsequent_ERRNO2 -- ibv_create_cq() fails
>  * with MOCK_ERRNO whereas subsequent ibv_destroy_comp_channel()
>  * fails with MOCK_ERRNO2
> ```

ibv_destroy_comp_channel() fails with MOCK_ERRNO2 after ibv_create_cq() failed with MOCK_ERRNO
___
*[tests/unit/cq/cq-new_delete.c, line 220 at r2](https://reviewable.io/reviews/pmem/rpma/1093#-McTnTRA1sWTQtPof2RT:-McTnTRA1sWTQtPof2RU:btopizu) ([raw file](https://github.com/pmem/rpma/blob/7e7ccbded0964a0a8417d6a25943e472f736571e/tests/unit/cq/cq-new_delete.c#L220)):*
> ```C
>  * delete__destroy_cq_ERRNO_subsequent_ERRNO2 -- ibv_destroy_cq()
>  * fails with MOCK_ERRNO whereas subsequent ibv_destroy_comp_channel()
>  * fails with MOCK_ERRNO2
> ```

ibv_destroy_comp_channel() fails with MOCK_ERRNO2 after ibv_destroy_cq() failed with MOCK_ERRNO
___
*[tests/unit/flush/flush-new.c, line 58 at r2](https://reviewable.io/reviews/pmem/rpma/1093#-McTo-a9EC4Opc66y3jG:-McTo-a9EC4Opc66y3jH:bprdks4) ([raw file](https://github.com/pmem/rpma/blob/7e7ccbded0964a0a8417d6a25943e472f736571e/tests/unit/flush/flush-new.c#L58)):*
> ```C
> 
> /*
>  * new__apm_mmap_E_NOMEM -- mmap() fails with MAP_FAILED
> ```

new__apm_mmap_MAP_FAILED
___
*[tests/unit/flush/flush-new.c, line 78 at r2](https://reviewable.io/reviews/pmem/rpma/1093#-McToOe-8xQiksxoIllj:-McToOe01JlBAT0RUv-U:b-l8r2fp) ([raw file](https://github.com/pmem/rpma/blob/7e7ccbded0964a0a8417d6a25943e472f736571e/tests/unit/flush/flush-new.c#L78)):*
> ```C
> 
> /*
>  * new__apm_mr_reg_E_NOMEM -- rpma_mr_reg() fails with RPMA_E_NOMEM
> ```

new__apm_mr_reg_E_NOMEM_munmap_ERRNO
___
*[tests/unit/flush/flush-new.c, line 78 at r2](https://reviewable.io/reviews/pmem/rpma/1093#-McToU7r8rZu1lXa-T5Y:-McToU7r8rZu1lXa-T5Z:b-4sri0s) ([raw file](https://github.com/pmem/rpma/blob/7e7ccbded0964a0a8417d6a25943e472f736571e/tests/unit/flush/flush-new.c#L78)):*
> ```C
> 
> /*
>  * new__apm_mr_reg_E_NOMEM -- rpma_mr_reg() fails with RPMA_E_NOMEM
> ```

munmap() fails with MOCK_ERRNO after rpma_mr_reg() failed with RPMA_E_NOMEM

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 22 files at r1, 6 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1093)* status: 21 of 22 files reviewed, 8 unresolved discussions (waiting on @yangx-jy)

___
*[tests/unit/mr/mr-reg.c, line 242 at r2](https://reviewable.io/reviews/pmem/rpma/1093#-McTpOz35xU_jfydiUMv:-McTpOz35xU_jfydiUMw:b-8zjjb5) ([raw file](https://github.com/pmem/rpma/blob/7e7ccbded0964a0a8417d6a25943e472f736571e/tests/unit/mr/mr-reg.c#L242)):*
> ```C
> 
> 	/* configure mocks */
> 	will_return_maybe(ibv_dereg_mr, MOCK_ERRNO);
> ```

It doesn't seem optional. It is required for the test to succeed.
___
*[tests/unit/peer/peer-new.c, line 109 at r2](https://reviewable.io/reviews/pmem/rpma/1093#-McTq6YT11z3xzDdn2n5:-McTq6YT11z3xzDdn2n6:b-fp2rbo) ([raw file](https://github.com/pmem/rpma/blob/7e7ccbded0964a0a8417d6a25943e472f736571e/tests/unit/peer/peer-new.c#L109)):*
> ```C
> /*
>  * new__alloc_pd_ERRNO -- ibv_alloc_pd() fails with MOCK_ERRNO
>  * (arbitrarily picked error which is not ENOMEM)
> ```

This comment is redundant. This line describes what MOCK_ERRNO is. Please remove.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1093)* status: all files reviewed, 9 unresolved discussions (waiting on @yangx-jy)

___
*[tests/unit/info/info-common.h, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/1093#-McTrdod9QqI7mLAFHce:-McTrdog2386N7gA65TI:b-i7j0up) ([raw file](https://github.com/pmem/rpma/blob/7e7ccbded0964a0a8417d6a25943e472f736571e/tests/unit/info/info-common.h#L15)):*
> ```objc
> 
> #include "cmocka_headers.h"
> #include "test-common.h"
> ```

`info-common.h` does not require `test-common.h`. I think this header should be added to:
- `info-new.c`
- `info-resolve_addr.c`
- `info-bind_addr.c`

**Review by yangx-jy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1093)* status: 13 of 22 files reviewed, 9 unresolved discussions (waiting on @janekmi)

___
*[tests/unit/conn_req/conn_req-new.c, line 345 at r2](https://reviewable.io/reviews/pmem/rpma/1093#-McTm6fh77cItBaZnlJn:-McU1d0D53voJ605Mzv8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7e7ccbded0964a0a8417d6a25943e472f736571e/tests/unit/conn_req/conn_req-new.c#L345)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

... subsequent (rpma_cq_delete(), rdma_destroy_id()) fail with...
</blockquote></details>

Done.
___
*[tests/unit/cq/cq-new_delete.c, line 65 at r2](https://reviewable.io/reviews/pmem/rpma/1093#-McTmeTa77EaZNTTDpiB:-McU1hcuAKL5SyzyQqx7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7e7ccbded0964a0a8417d6a25943e472f736571e/tests/unit/cq/cq-new_delete.c#L65)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

ibv_destroy_comp_channel() fails with MOCK_ERRNO2 after ibv_create_cq() failed with MOCK_ERRNO
</blockquote></details>

Done.
___
*[tests/unit/cq/cq-new_delete.c, line 220 at r2](https://reviewable.io/reviews/pmem/rpma/1093#-McTnTRA1sWTQtPof2RT:-McU1khlC2ccRjoLIt2F:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7e7ccbded0964a0a8417d6a25943e472f736571e/tests/unit/cq/cq-new_delete.c#L220)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

ibv_destroy_comp_channel() fails with MOCK_ERRNO2 after ibv_destroy_cq() failed with MOCK_ERRNO
</blockquote></details>

Done.
___
*[tests/unit/flush/flush-new.c, line 58 at r2](https://reviewable.io/reviews/pmem/rpma/1093#-McTo-a9EC4Opc66y3jG:-McU1n7J0yB6Apobk8wN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7e7ccbded0964a0a8417d6a25943e472f736571e/tests/unit/flush/flush-new.c#L58)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

new__apm_mmap_MAP_FAILED
</blockquote></details>

Done.
___
*[tests/unit/flush/flush-new.c, line 78 at r2](https://reviewable.io/reviews/pmem/rpma/1093#-McToOe-8xQiksxoIllj:-McU1rib6dy9ayZsnYAx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7e7ccbded0964a0a8417d6a25943e472f736571e/tests/unit/flush/flush-new.c#L78)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

new__apm_mr_reg_E_NOMEM_munmap_ERRNO
</blockquote></details>

Done.
___
*[tests/unit/flush/flush-new.c, line 78 at r2](https://reviewable.io/reviews/pmem/rpma/1093#-McToU7r8rZu1lXa-T5Y:-McU1uah7wLj_GnziW9L:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7e7ccbded0964a0a8417d6a25943e472f736571e/tests/unit/flush/flush-new.c#L78)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

munmap() fails with MOCK_ERRNO after rpma_mr_reg() failed with RPMA_E_NOMEM
</blockquote></details>

Done.
___
*[tests/unit/info/info-common.h, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/1093#-McTrdod9QqI7mLAFHce:-McU1xW20a8qG7ySzI1n:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7e7ccbded0964a0a8417d6a25943e472f736571e/tests/unit/info/info-common.h#L15)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`info-common.h` does not require `test-common.h`. I think this header should be added to:
- `info-new.c`
- `info-resolve_addr.c`
- `info-bind_addr.c`
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-reg.c, line 242 at r2](https://reviewable.io/reviews/pmem/rpma/1093#-McTpOz35xU_jfydiUMv:-McU2-9p4krmLqkSwg4D:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7e7ccbded0964a0a8417d6a25943e472f736571e/tests/unit/mr/mr-reg.c#L242)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It doesn't seem optional. It is required for the test to succeed.
</blockquote></details>

Done.
___
*[tests/unit/peer/peer-new.c, line 109 at r2](https://reviewable.io/reviews/pmem/rpma/1093#-McTq6YT11z3xzDdn2n5:-McU20VZ3Tlh03hEakXe:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7e7ccbded0964a0a8417d6a25943e472f736571e/tests/unit/peer/peer-new.c#L109)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This comment is redundant. This line describes what MOCK_ERRNO is. Please remove.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 9 of 9 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1093#-:-MctFf2G2W_hQykyz-pX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by yangx-jy — COMMENTED** [review]
Perhaps, we need @ldorau to review it before merging it.  ^_^

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1093#-:-Mcvj-Q15pkkve2JaCxB:b864usl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1093#-:-McxtvZzDCghzUJBb7RZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Comment by yangx-jy** [comment]
@janekmi @osalyk 

Thank you for reviewing it.  I can continue focusing on #1080 now.  ^_^

**Pull request merged**
