### PR TITLE
common: remove hardcoded timeout from info.c module

### PR DESCRIPTION
**Pull request by janekmi**
This one of many steps leading to allow configuring various aspects of the library behaviour.

TODO:
- [x] tests

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/313)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/313)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[src/info.c, line 101 at r1](https://reviewable.io/reviews/pmem/rpma/313#-MG3cOvm5Fn9lwaM0R-k:-MG3cOvm5Fn9lwaM0R-l:b-7ylqb2) ([raw file](https://github.com/pmem/rpma/blob/d4e9a27c9a0ed2aad699f31b06c62726824c36f1/src/info.c#L101)):*
> ```C
>  *
>  * ASSUMPTIONS
>  * - XXX id != NULL && info != NULL
> ```

XXX ?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/313)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/info.c, line 101 at r1](https://reviewable.io/reviews/pmem/rpma/313#-MG3cOvm5Fn9lwaM0R-k:-MG3esou1SDpRGOyJS32:b-v93ups) ([raw file](https://github.com/pmem/rpma/blob/d4e9a27c9a0ed2aad699f31b06c62726824c36f1/src/info.c#L101)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

XXX ?
</blockquote></details>

This a TODO mark. These conditions are unnecessarily checked in this function whereas they can be done via assumptions mechanism.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/313)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[src/info.c, line 101 at r1](https://reviewable.io/reviews/pmem/rpma/313#-MG3cOvm5Fn9lwaM0R-k:-MG3fTHR5q1RHzwfvTKB:b-y1ie6k) ([raw file](https://github.com/pmem/rpma/blob/d4e9a27c9a0ed2aad699f31b06c62726824c36f1/src/info.c#L101)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This a TODO mark. These conditions are unnecessarily checked in this function whereas they can be done via assumptions mechanism.
</blockquote></details>

So please add a comment like: "These conditions are unnecessarily checked in this function whereas they can be done via assumptions mechanism."

**Review by ldorau — COMMENTED** [review]
Builds fail

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/313#-:-MG3n9no358yNZT_BanQ:b-c0150s)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — COMMENTED** [review]
No any more.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/313#-:-MG4EPen3ow55dYViUUJ:b-6yyawl)* status: 11 of 13 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/313#-:-MG4Fpn16WfVH3wQ1W5O:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/313#-:-MG7VQfQ7uDzMIsPoVXN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/313#-:-MG7Zax21KaloQwU4Fqx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
