### PR TITLE
tools: fio.py: implement __server_start and __server_stop

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1412)

### CODE REVIEW

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1412)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1412)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @haichangsi and @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1412)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @haichangsi, @ldorau, and @osalyk)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 148 at r1](https://reviewable.io/reviews/pmem/rpma/1412#-MqnoH2s6aO1bBPFMq3w:-MqnoH2s6aO1bBPFMq3x:b1aqbqo) ([raw file](https://github.com/pmem/rpma/blob/2a99d5975ee74cb8cc1ea33e6704c487bc13db09/tools/perf/lib/benchmark/runner/fio.py#L148)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
>         r_job_path = self.__config.get('REMOTE_JOB_PATH',
>                                        '/dev/shm/librpma_{}-server.fio'\
>                                        .format(self.__tool_mode))
>         RemoteCmd.copy_to_remote(self.__config,
>                                  "./fio_jobs/librpma_{}-server.fio"\
>                                  .format(self.__tool_mode), r_job_path)
> ```
</details>


I think it is better readable in this way:
```
        def_path = '/dev/shm/librpma_{}-server.fio'.format(self.__tool_mode)
        r_job_path = self.__config.get('REMOTE_JOB_PATH', def_path)
        if r_job_path == '':
            r_job_path = def_path
        job_file = "./fio_jobs/librpma_{}-server.fio".format(self.__tool_mode)
        RemoteCmd.copy_to_remote(self.__config, job_file, r_job_path)
```


`REMOTE_JOB_PATH` can be the empty string, so the following check is necessary:
```
        if r_job_path == '':
            r_job_path = def_path
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1412)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @haichangsi, @ldorau, and @osalyk)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 150 at r1](https://reviewable.io/reviews/pmem/rpma/1412#-MqnvcgI0R5cdtakwa4O:-MqnvcgI0R5cdtakwa4P:b-h4p362) ([raw file](https://github.com/pmem/rpma/blob/2a99d5975ee74cb8cc1ea33e6704c487bc13db09/tools/perf/lib/benchmark/runner/fio.py#L150)):*
> ```
> RemoteCmd.run_async(self.__config, args, env)
> ```

`r_job_path` is missing in `args`

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1412)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 106 at r1](https://reviewable.io/reviews/pmem/rpma/1412#-Mqrp3fN67ruHZLFYuuc:-Mqrp3fN67ruHZLFYuud:bz9k7wz) ([raw file](https://github.com/pmem/rpma/blob/2a99d5975ee74cb8cc1ea33e6704c487bc13db09/tools/perf/lib/benchmark/runner/fio.py#L106)):*
> ```
> 'direct_write_to_pmem': str(False), # XXX
> ```

What about setting `direct_write_to_pmem` ?

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1412)* status: all files reviewed, 4 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 106 at r1](https://reviewable.io/reviews/pmem/rpma/1412#-Mqrp3fN67ruHZLFYuuc:-Mqrqv9o1FxshaDHieUS:b-yzo0re) ([raw file](https://github.com/pmem/rpma/blob/2a99d5975ee74cb8cc1ea33e6704c487bc13db09/tools/perf/lib/benchmark/runner/fio.py#L106)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 'direct_write_to_pmem': str(False), # XXX
> ```

What about setting `direct_write_to_pmem` ?
</blockquote></details>

= `str(int(self.__config['REMOTE_DIRECT_WRITE_TO_PMEM']))`
___
*[tools/perf/lib/benchmark/runner/fio.py, line 112 at r1](https://reviewable.io/reviews/pmem/rpma/1412#-Mqrr2-01ZrpdnJsXUoF:-Mqrr2-01ZrpdnJsXUoG:b-73luql) ([raw file](https://github.com/pmem/rpma/blob/2a99d5975ee74cb8cc1ea33e6704c487bc13db09/tools/perf/lib/benchmark/runner/fio.py#L112)):*
> ```
> # XXX
> ```

???

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1412)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1412)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 106 at r1](https://reviewable.io/reviews/pmem/rpma/1412#-Mqrp3fN67ruHZLFYuuc:-Mqs2F_G1F3rURI3XWyU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2a99d5975ee74cb8cc1ea33e6704c487bc13db09/tools/perf/lib/benchmark/runner/fio.py#L106)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

= `str(int(self.__config['REMOTE_DIRECT_WRITE_TO_PMEM']))`
</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/runner/fio.py, line 112 at r1](https://reviewable.io/reviews/pmem/rpma/1412#-Mqrr2-01ZrpdnJsXUoF:-Mqs2TDo6EIV_1Ub7fbH:b-89ntrc) ([raw file](https://github.com/pmem/rpma/blob/2a99d5975ee74cb8cc1ea33e6704c487bc13db09/tools/perf/lib/benchmark/runner/fio.py#L112)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> # XXX
> ```

???
</blockquote></details>

I look forward to #1391
___
*[tools/perf/lib/benchmark/runner/fio.py, line 148 at r1](https://reviewable.io/reviews/pmem/rpma/1412#-MqnoH2s6aO1bBPFMq3w:-Mqs3KQW8dko7OMaKc-p:b-12pkbn) ([raw file](https://github.com/pmem/rpma/blob/2a99d5975ee74cb8cc1ea33e6704c487bc13db09/tools/perf/lib/benchmark/runner/fio.py#L148)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>         r_job_path = self.__config.get('REMOTE_JOB_PATH',
>                                        '/dev/shm/librpma_{}-server.fio'\
>                                        .format(self.__tool_mode))
>         RemoteCmd.copy_to_remote(self.__config,
>                                  "./fio_jobs/librpma_{}-server.fio"\
>                                  .format(self.__tool_mode), r_job_path)
> ```

I think it is better readable in this way:
```
        def_path = '/dev/shm/librpma_{}-server.fio'.format(self.__tool_mode)
        r_job_path = self.__config.get('REMOTE_JOB_PATH', def_path)
        if r_job_path == '':
            r_job_path = def_path
        job_file = "./fio_jobs/librpma_{}-server.fio".format(self.__tool_mode)
        RemoteCmd.copy_to_remote(self.__config, job_file, r_job_path)
```


`REMOTE_JOB_PATH` can be the empty string, so the following check is necessary:
```
        if r_job_path == '':
            r_job_path = def_path
```

</blockquote></details>

This is what the get() method does
___
*[tools/perf/lib/benchmark/runner/fio.py, line 150 at r1](https://reviewable.io/reviews/pmem/rpma/1412#-MqnvcgI0R5cdtakwa4O:-MqsnlzsAFLaxPt84hOH:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/2a99d5975ee74cb8cc1ea33e6704c487bc13db09/tools/perf/lib/benchmark/runner/fio.py#L150)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> RemoteCmd.run_async(self.__config, args, env)
> ```

`r_job_path` is missing in `args`
</blockquote></details>

Done

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1412)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 106 at r1](https://reviewable.io/reviews/pmem/rpma/1412#-Mqrp3fN67ruHZLFYuuc:-MqsrMNuAQq6k5Wy1b7s:btojbfd) ([raw file](https://github.com/pmem/rpma/blob/2a99d5975ee74cb8cc1ea33e6704c487bc13db09/tools/perf/lib/benchmark/runner/fio.py#L106)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Great!
___
*[tools/perf/lib/benchmark/runner/fio.py, line 112 at r1](https://reviewable.io/reviews/pmem/rpma/1412#-Mqrr2-01ZrpdnJsXUoF:-MqstGkWCA2hsTQ9phY7:b8guvo3) ([raw file](https://github.com/pmem/rpma/blob/2a99d5975ee74cb8cc1ea33e6704c487bc13db09/tools/perf/lib/benchmark/runner/fio.py#L112)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

I look forward to #1391
</blockquote></details>

You do not have to. You have `if` here, so it works now. `XXX` can be removed in my opinion. What do you think?
___
*[tools/perf/lib/benchmark/runner/fio.py, line 148 at r1](https://reviewable.io/reviews/pmem/rpma/1412#-MqnoH2s6aO1bBPFMq3w:-Mqsqk7478JlsVmyLDRo:b4b55r1) ([raw file](https://github.com/pmem/rpma/blob/2a99d5975ee74cb8cc1ea33e6704c487bc13db09/tools/perf/lib/benchmark/runner/fio.py#L148)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

This is what the get() method does
</blockquote></details>

No, get() works only if there is no such key in the dict, but if there is such key in the dict and it is set to empty string, then `r_job_path` will be set to the empty string too, what is wrong.
___
*[tools/perf/lib/benchmark/runner/fio.py, line 114 at r3](https://reviewable.io/reviews/pmem/rpma/1412#-MqstD720emiHCKk1wE9:-MqstD720emiHCKk1wEA:b-q1eawv) ([raw file](https://github.com/pmem/rpma/blob/98c5919d9ef905e922f76202821bb0bba28cd330/tools/perf/lib/benchmark/runner/fio.py#L114)):*
> ```
>         if 'cpu' in settings.keys():
>             # XXX
>             env.append('cpuload={}'.format(settings['cpu']))
> ```

`cpu` -> `cpuload`

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1412)* status: all files reviewed, 4 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 112 at r3](https://reviewable.io/reviews/pmem/rpma/1412#-Mqszf3WEzLLnMRZ4tTV:-Mqszf3WEzLLnMRZ4tTW:b-pwz6vp) ([raw file](https://github.com/pmem/rpma/blob/98c5919d9ef905e922f76202821bb0bba28cd330/tools/perf/lib/benchmark/runner/fio.py#L112)):*
> ```
> settings.keys():
> ```

`settings.keys()` -> `settings`

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1412)* status: all files reviewed, 7 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 103 at r3](https://reviewable.io/reviews/pmem/rpma/1412#-Mqt0y642MHpIwW0p3qt:-Mqt0y642MHpIwW0p3qu:b-4t4je4) ([raw file](https://github.com/pmem/rpma/blob/98c5919d9ef905e922f76202821bb0bba28cd330/tools/perf/lib/benchmark/runner/fio.py#L103)):*
> ```
> args = ['numactl', '-N', r_numa_n, self.__r_fio_path]
> ```

Please move `# XXX nice to have REMOTE_TRACER` before this line - this is the right place for this comment.
___
*[tools/perf/lib/benchmark/runner/fio.py, line 110 at r3](https://reviewable.io/reviews/pmem/rpma/1412#-Mqt0MDR9a79y6L6XVrj:-Mqt0MDR9a79y6L6XVrk:b-dymbm9) ([raw file](https://github.com/pmem/rpma/blob/98c5919d9ef905e922f76202821bb0bba28cd330/tools/perf/lib/benchmark/runner/fio.py#L110)):*
> ```
>                'busy_wait_polling={}'\
>                    .format(self.__benchmark.oneseries.get('busy_wait_polling',
>                                                           True)),
> ```

It is not well readable in my opinion. Maybe in this way?
```
        busy_wait_polling = \
            self.__benchmark.oneseries.get('busy_wait_polling', True)
        env = ['serverip={}'.format(self.__config['server_ip']),
               ....
               'busy_wait_polling={}'.format(busy_wait_polling),
```
___
*[tools/perf/lib/benchmark/runner/fio.py, line 142 at r3](https://reviewable.io/reviews/pmem/rpma/1412#-Mqt0rdY3Lnyz9mOxZzs:-Mqt0rdY3Lnyz9mOxZzt:b-yjjzmn) ([raw file](https://github.com/pmem/rpma/blob/98c5919d9ef905e922f76202821bb0bba28cd330/tools/perf/lib/benchmark/runner/fio.py#L142)):*
> ```
>  # XXX nice to have REMOTE_TRACER
> ```

It should be moved above

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1412)* status: all files reviewed, 7 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 112 at r1](https://reviewable.io/reviews/pmem/rpma/1412#-Mqrr2-01ZrpdnJsXUoF:-Mqt1xY1AMTRafO_iD5L:b-l6gg6) ([raw file](https://github.com/pmem/rpma/blob/2a99d5975ee74cb8cc1ea33e6704c487bc13db09/tools/perf/lib/benchmark/runner/fio.py#L112)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

You do not have to. You have `if` here, so it works now. `XXX` can be removed in my opinion. What do you think?
</blockquote></details>

#1391 is merged

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1412)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 112 at r1](https://reviewable.io/reviews/pmem/rpma/1412#-Mqrr2-01ZrpdnJsXUoF:-MqsuWPm2hVbA3FeId_Q:b32wtd) ([raw file](https://github.com/pmem/rpma/blob/2a99d5975ee74cb8cc1ea33e6704c487bc13db09/tools/perf/lib/benchmark/runner/fio.py#L112)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

#1391 is merged
</blockquote></details>

ok
___
*[tools/perf/lib/benchmark/runner/fio.py, line 148 at r1](https://reviewable.io/reviews/pmem/rpma/1412#-MqnoH2s6aO1bBPFMq3w:-Mqt9lbA1v5lVVMWjzqj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2a99d5975ee74cb8cc1ea33e6704c487bc13db09/tools/perf/lib/benchmark/runner/fio.py#L148)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No, get() works only if there is no such key in the dict, but if there is such key in the dict and it is set to empty string, then `r_job_path` will be set to the empty string too, what is wrong.
</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/runner/fio.py, line 103 at r3](https://reviewable.io/reviews/pmem/rpma/1412#-Mqt0y642MHpIwW0p3qt:-Mqt9u8tBkl4caatKVQI:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/98c5919d9ef905e922f76202821bb0bba28cd330/tools/perf/lib/benchmark/runner/fio.py#L103)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> args = ['numactl', '-N', r_numa_n, self.__r_fio_path]
> ```

Please move `# XXX nice to have REMOTE_TRACER` before this line - this is the right place for this comment.

</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/runner/fio.py, line 110 at r3](https://reviewable.io/reviews/pmem/rpma/1412#-Mqt0MDR9a79y6L6XVrj:-MqtAJef1fNrl5putmwV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/98c5919d9ef905e922f76202821bb0bba28cd330/tools/perf/lib/benchmark/runner/fio.py#L110)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>                'busy_wait_polling={}'\
>                    .format(self.__benchmark.oneseries.get('busy_wait_polling',
>                                                           True)),
> ```

It is not well readable in my opinion. Maybe in this way?
```
        busy_wait_polling = \
            self.__benchmark.oneseries.get('busy_wait_polling', True)
        env = ['serverip={}'.format(self.__config['server_ip']),
               ....
               'busy_wait_polling={}'.format(busy_wait_polling),
```
</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/runner/fio.py, line 112 at r3](https://reviewable.io/reviews/pmem/rpma/1412#-Mqszf3WEzLLnMRZ4tTV:-MqtAZEJ4FKNr9j-2HK6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/98c5919d9ef905e922f76202821bb0bba28cd330/tools/perf/lib/benchmark/runner/fio.py#L112)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> settings.keys():
> ```

`settings.keys()` -> `settings`
</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/runner/fio.py, line 114 at r3](https://reviewable.io/reviews/pmem/rpma/1412#-MqstD720emiHCKk1wE9:-MqsucTSAJkP7cussR3-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/98c5919d9ef905e922f76202821bb0bba28cd330/tools/perf/lib/benchmark/runner/fio.py#L114)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>         if 'cpu' in settings.keys():
>             # XXX
>             env.append('cpuload={}'.format(settings['cpu']))
> ```

`cpu` -> `cpuload`
</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/runner/fio.py, line 142 at r3](https://reviewable.io/reviews/pmem/rpma/1412#-Mqt0rdY3Lnyz9mOxZzs:-MqtAa4IC6VtWpGWTyVj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/98c5919d9ef905e922f76202821bb0bba28cd330/tools/perf/lib/benchmark/runner/fio.py#L142)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  # XXX nice to have REMOTE_TRACER
> ```

It should be moved above
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1412)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1412)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1412)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1412#-Mr-BuMT78C95UHRwBE4:-Mr-BuMU0ADkTigsmOaH:br9st29) (no related file):*
rebase please

---

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1412)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1412#-Mr-BuMT78C95UHRwBE4:-Mr16TIRDtgdUkorrRb2:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

rebase please
</blockquote></details>

Done.

---

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1412#-:-Mr16VCA0szTZfX1221y:bnfp4nl)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1412)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1412)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1412)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
