### PR TITLE
tools: ib_read bw-bs add missing thread column

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/642)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/642)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/ib_read.sh, line 128 at r1](https://reviewable.io/reviews/pmem/rpma/642#-MO5mkQVE8qQtidIHHqO:-MO5mkQVE8qQtidIHHqP:b-j1vr49) ([raw file](https://github.com/pmem/rpma/blob/d7a000dee1901d5abbf5d4aed36dd392edfb0b26/tools/ib_read.sh#L128)):*
> ```
> echo -n "1," >> $OUTPUT
> ```

No, it should be exactly the same like below:

`echo -n "${TH}," >> $OUTPUT`

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/642)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/ib_read.sh, line 128 at r1](https://reviewable.io/reviews/pmem/rpma/642#-MO5mkQVE8qQtidIHHqO:-MO6JmVD8oLF5J3s4l5c:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d7a000dee1901d5abbf5d4aed36dd392edfb0b26/tools/ib_read.sh#L128)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> echo -n "1," >> $OUTPUT
> ```

No, it should be exactly the same like below:

`echo -n "${TH}," >> $OUTPUT`
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/642)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/642#-:-MO6KDpWB5_5SLQC-Pr4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
