### PR TITLE
tools: check if all required parameters are set in the config

### PR DESCRIPTION
**Pull request by ldorau**
... and do not require auxiliary parameters.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1485)

### CODE REVIEW

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1485#-:-Mt97hxNEuTJbA6wJzTP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1485)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/lib/bench.py, line 84 at r1](https://reviewable.io/reviews/pmem/rpma/1485#-MtCBye58bSO-r-kxCTf:-MtCBye58bSO-r-kxCTg:b178vuy) ([raw file](https://github.com/pmem/rpma/blob/2354139605911a78cb2529d50b83e0c3e519f4d5/tools/perf/lib/bench.py#L84)):*
> ```Python
>     __REQUIRED_CONFIG_PARAMS = [
>         'platform_generation', 'server_ip', 'JOB_NUMA', 'REMOTE_JOB_NUMA',
>         'REMOTE_DIRECT_WRITE_TO_PMEM', 'REMOTE_JOB_MEM_PATH']
> ```

Shouldn't 'REMOTE_DIRECT_WRITE_TO_PMEM' only be checked if we don't have 'REMOTE_RNIC_PCIE_ROOT_PORT' and 'REMOTE_SUDO_NOPASSWD' set?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1485)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/lib/bench.py, line 84 at r1](https://reviewable.io/reviews/pmem/rpma/1485#-MtCBye58bSO-r-kxCTf:-MtCKbzD3S49cUvyFIyz:b-ta9e2k) ([raw file](https://github.com/pmem/rpma/blob/2354139605911a78cb2529d50b83e0c3e519f4d5/tools/perf/lib/bench.py#L84)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Shouldn't 'REMOTE_DIRECT_WRITE_TO_PMEM' only be checked if we don't have 'REMOTE_RNIC_PCIE_ROOT_PORT' and 'REMOTE_SUDO_NOPASSWD' set?
</blockquote></details>

This is true in case of Cascade Lake platforms, but in case of Ice Lake platforms it is not.
But we can skip it here, because it is checked always later in Requirements.

Removed.

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, 2 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1485#-:-MtCS33A65B1nHH60neQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1485#-:-MtCSE9q4NQLm8nsGrlG:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
