### PR TITLE
tools: docstring and unittests for kvtable.lines2str()

### PR DESCRIPTION
**Pull request by janekmi**
Requires:

- [x] #1121
- [x] #1119

Ref:

- a lot easier to review in the context of #1122

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1123)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1123)* status: 1 of 11 files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 9 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1123)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/kvtable.py, line 13 at r2](https://reviewable.io/reviews/pmem/rpma/1123#-MdpWIP-21slZbWKjrzd:-MdpWIP0D-Cc2U-fWbYi:b-md3791) ([raw file](https://github.com/pmem/rpma/blob/392495514fd967f13dd0cefde09c1804f777a1f1/tools/perf/lib/kvtable.py#L13)):*
> ```
> ····
> ```

Spaces?

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 11 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1123)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1123#-:-MdpXJdV6Qtaf4rl6tN5:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1123)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/lib/kvtable.py, line 13 at r2](https://reviewable.io/reviews/pmem/rpma/1123#-MdpWIP-21slZbWKjrzd:-Mdp_PsWE7SUh166mPpx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/392495514fd967f13dd0cefde09c1804f777a1f1/tools/perf/lib/kvtable.py#L13)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> ····
> ```

Spaces?
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1123#-:-Mdp_cFZ05Og6um_U_hp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1123)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1123#-MdpeiVX5vZWmGTED1Ar:-MdpeiVY2S7poq8gP3y6:b-n6khor) (no related file):*
Please rebase

---

**Review by ldorau — APPROVED** [review]
> Reviewed 10 of 10 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1123)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1123#-:-Mdph2905j3V2T8H_x2u:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1123#-:-Mdq5l9v7bf1VlYCHc_k:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1123)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
