### PR TITLE
common: run-build.sh python test coverage

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1498)

### CODE REVIEW

**Review by haichangsi — COMMENTED** [review]
I can see that the build failed, locally it was ok because I have coverage lib installed. I assumed that this is not gonna be a problem loooking at CONTRIBUTING.md. Should I use a different lib?

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1498#-:-MtNNLHSAGKgXyh_JgZE:b-e8zgow)* status: 0 of 1 files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1498)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1498)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1498)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1498)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1498#-MtOCY1v1acpcuDh8mHX:-MtOCY1v1acpcuDh8mHY:bbjqin2) (no related file):*
You have to add the required package to the Docker images

---

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1498)* status: 1 of 30 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1498#-MtOCY1v1acpcuDh8mHX:-MtgUE_2-2MGWMaCYSFB:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

You have to add the required package to the Docker images
</blockquote></details>

Done.

---

**Review by ldorau — COMMENTED** [review]
> Reviewed 29 of 29 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1498)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1498)* status: all files reviewed, 4 unresolved discussions (waiting on @haichangsi)

___
*[utils/docker/run-build.sh, line 148 at r2](https://reviewable.io/reviews/pmem/rpma/1498#-MtlPJmH425HgOpvHZit:-MtlPJmH425HgOpvHZiu:b-lixp94) ([raw file](https://github.com/pmem/rpma/blob/51f38198ebdde9ed1e097ab30151aaab79de491c/utils/docker/run-build.sh#L148)):*
> ```Shell
> 
> 	# run pytest with coverage
> 	PYTEST_COVERAGE="coverage run -m"
> ```

"coverage" is installed (by the `pip` command) only for the current user, so you have to add its path to the `PATH` environment variable here.



_Code quote:_
```Shell
PYTEST_COVERAGE="coverage run -m"
```
___
*[utils/docker/run-build.sh, line 149 at r2](https://reviewable.io/reviews/pmem/rpma/1498#-MtlQ8V527nsA8rGIC8y:-MtlQ8V527nsA8rGIC8z:b-pxy6uu) ([raw file](https://github.com/pmem/rpma/blob/51f38198ebdde9ed1e097ab30151aaab79de491c/utils/docker/run-build.sh#L149)):*
> ```Shell
> 	# run pytest with coverage
> 	PYTEST_COVERAGE="coverage run -m"
> 	PYTEST="${PYTEST_COVERAGE} ${PYTEST}"
> ```

Please read carefully the help of  `coverage run`. The `-m` option requires "*an importable Python module, not a script path*"



_Code quote:_
```Shell
	PYTEST="${PYTEST_COVERAGE} ${PYTEST}"
```
___
*[utils/docker/run-build.sh, line 150 at r2](https://reviewable.io/reviews/pmem/rpma/1498#-MtlSzIq9pT3uMSuG7Cd:-MtlSzIr2QXyRq8jyNg0:b-qi7p6g) ([raw file](https://github.com/pmem/rpma/blob/51f38198ebdde9ed1e097ab30151aaab79de491c/utils/docker/run-build.sh#L150)):*
> ```Shell
> 	PYTEST_COVERAGE="coverage run -m"
> 	PYTEST="${PYTEST_COVERAGE} ${PYTEST}"
> 	REPORT="coverage report"
> ```

Please add the `-i` option here (`coverage report -i`) to ignore strange errors occurring on Arch Linux like:
`No source for code: '/mnt/files/repos/rpma/rep-10>'.`



_Code quote:_
```Shell
coverage report
```
___
*[utils/docker/run-build.sh, line 153 at r2](https://reviewable.io/reviews/pmem/rpma/1498#-MtlTT2CASi4kRkPSoWM:-MtlTT2CASi4kRkPSoWN:bfkscmn) ([raw file](https://github.com/pmem/rpma/blob/51f38198ebdde9ed1e097ab30151aaab79de491c/utils/docker/run-build.sh#L153)):*
> ```Shell
> 	cd $WORKDIR/tools/perf/
> 	eval $PYTEST
> 	eval $REPORT
> ```

Please run just:
```
	coverage report -i
```
instead of:
```
	REPORT="coverage report -i"
	eval $REPORT
```



_Code quote:_
```Shell
	REPORT="coverage report"
	cd $WORKDIR/tools/perf/
	eval $PYTEST
	eval $REPORT
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1498)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[utils/docker/run-build.sh, line 148 at r2](https://reviewable.io/reviews/pmem/rpma/1498#-MtlPJmH425HgOpvHZit:-MtrM-nA0a345sqct0lV:b-ebnwmj) ([raw file](https://github.com/pmem/rpma/blob/51f38198ebdde9ed1e097ab30151aaab79de491c/utils/docker/run-build.sh#L148)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

"coverage" is installed (by the `pip` command) only for the current user, so you have to add its path to the `PATH` environment variable here.
</blockquote></details>

I used 'export', not sure this is the way
___
*[utils/docker/run-build.sh, line 149 at r2](https://reviewable.io/reviews/pmem/rpma/1498#-MtlQ8V527nsA8rGIC8y:-MtrME2z-U_HP3UEB3KE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/51f38198ebdde9ed1e097ab30151aaab79de491c/utils/docker/run-build.sh#L149)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please read carefully the help of  `coverage run`. The `-m` option requires "*an importable Python module, not a script path*"
</blockquote></details>

Done.
___
*[utils/docker/run-build.sh, line 150 at r2](https://reviewable.io/reviews/pmem/rpma/1498#-MtlSzIq9pT3uMSuG7Cd:-MtrMEUf-69W_IYMXJmM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/51f38198ebdde9ed1e097ab30151aaab79de491c/utils/docker/run-build.sh#L150)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please add the `-i` option here (`coverage report -i`) to ignore strange errors occurring on Arch Linux like:
`No source for code: '/mnt/files/repos/rpma/rep-10>'.`
</blockquote></details>

Done.
___
*[utils/docker/run-build.sh, line 153 at r2](https://reviewable.io/reviews/pmem/rpma/1498#-MtlTT2CASi4kRkPSoWM:-MtrMHIBAEnHhbw7hkgp:bwuh6w8) ([raw file](https://github.com/pmem/rpma/blob/51f38198ebdde9ed1e097ab30151aaab79de491c/utils/docker/run-build.sh#L153)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please run just:
```
	coverage report -i
```
instead of:
```
	REPORT="coverage report -i"
	eval $REPORT
```
</blockquote></details>

If my 'export' is correct then it has to stay like that

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 30 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1498)* status: 1 of 30 files reviewed, 3 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[utils/docker/run-build.sh, line 148 at r2](https://reviewable.io/reviews/pmem/rpma/1498#-MtlPJmH425HgOpvHZit:-MtrMugT8EG3VZsDgEFk:b-4lf64r) ([raw file](https://github.com/pmem/rpma/blob/51f38198ebdde9ed1e097ab30151aaab79de491c/utils/docker/run-build.sh#L148)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

I used 'export', not sure this is the way
</blockquote></details>

It will not work. 
`which` will not find it, because it is not in the system `PATH` variable. You have to add path of the local `coverage` (where it has been installed by `pip`) to the system `PATH` environment variable (using `export` - this is OK).
___
*[utils/docker/run-build.sh, line 149 at r2](https://reviewable.io/reviews/pmem/rpma/1498#-MtlQ8V527nsA8rGIC8y:-MtrNaPV0Ewd_-E9EEIx:br7sr4m) ([raw file](https://github.com/pmem/rpma/blob/51f38198ebdde9ed1e097ab30151aaab79de491c/utils/docker/run-build.sh#L149)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet
___
*[utils/docker/run-build.sh, line 153 at r2](https://reviewable.io/reviews/pmem/rpma/1498#-MtlTT2CASi4kRkPSoWM:-MtrNkIA5flzuoONOC08:b-8u8ny) ([raw file](https://github.com/pmem/rpma/blob/51f38198ebdde9ed1e097ab30151aaab79de491c/utils/docker/run-build.sh#L153)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

If my 'export' is correct then it has to stay like that
</blockquote></details>

It is not :-(

**Review by ldorau — COMMENTED** [review]
> Reviewed 29 of 30 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1498)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1498)* status: 0 of 30 files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[utils/docker/run-build.sh, line 148 at r2](https://reviewable.io/reviews/pmem/rpma/1498#-MtlPJmH425HgOpvHZit:-MuPnfqbEtjMCt162lSf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/51f38198ebdde9ed1e097ab30151aaab79de491c/utils/docker/run-build.sh#L148)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It will not work. 
`which` will not find it, because it is not in the system `PATH` variable. You have to add path of the local `coverage` (where it has been installed by `pip`) to the system `PATH` environment variable (using `export` - this is OK).
</blockquote></details>

Done.
___
*[utils/docker/run-build.sh, line 149 at r2](https://reviewable.io/reviews/pmem/rpma/1498#-MtlQ8V527nsA8rGIC8y:-MuPngJL48kgVzud4Q8T:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/51f38198ebdde9ed1e097ab30151aaab79de491c/utils/docker/run-build.sh#L149)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not yet
</blockquote></details>

Done.
___
*[utils/docker/run-build.sh, line 153 at r2](https://reviewable.io/reviews/pmem/rpma/1498#-MtlTT2CASi4kRkPSoWM:-MuPnh4N9s7TvgMjELTy:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/51f38198ebdde9ed1e097ab30151aaab79de491c/utils/docker/run-build.sh#L153)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It is not :-(
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 30 of 30 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1498)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
It is OK. Please rebase.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1498#-:-MuQQtl26AL5uUTQslCv:b-3c7woo)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1498)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1498#-MuQQyzXE7D8J0vxtD7v:-MuQQyzY25M2rjatkqFd:b-nhsp7b) (no related file):*
Rebase plesae.

---

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 30 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1498)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1498)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1498#-MuQwgW70uWSJBSle8IO:-MuQwgW70uWSJBSle8IP:b2v3goa) (no related file):*
This PR has to wait until the devel-new-python branch is merged into master, because the Docker images are pushed out only on the master branch and CI builds of this PR on the devel-new-python branch will always fail.

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1498)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1498#-MuQwgW70uWSJBSle8IO:-MuUv3-aBEyslZXq75Fn:bfi6l2u) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

This PR has to wait until the devel-new-python branch is merged into master, because the Docker images are pushed out only on the master branch and CI builds of this PR on the devel-new-python branch will always fail.
</blockquote></details>

The devel-new-python branch has been merged into master. Please rebase.

---

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1498)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1498#-MuQQyzXE7D8J0vxtD7v:-MuV3Doj-V5C9l2JoAaj:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Rebase plesae.
</blockquote></details>

Done.

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1498)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[utils/docker/run-build.sh, line 148 at r4](https://reviewable.io/reviews/pmem/rpma/1498#-MuVGyO_BDS5k92zTD9x:-MuVGyOaAmZzKz4TLBeG:b6pgbra) ([raw file](https://github.com/pmem/rpma/blob/13daf6147fe9b9d33884bde39d9f9eceeb3f7a6f/utils/docker/run-build.sh#L148)):*
> ```Shell
> 
> 	# add local pip installations to the PATH
> 	export PATH=$PATH:~/.local/bin/
> ```

The new coverage conflicts with the current one for C language.

`if [ "$COVERAGE" == "1" ]; then` the old version of code should be run and the new one otherwise:

```
if [ "$COVERAGE" == "1" ]; then
	# run pytest
	cd $WORKDIR/tools/perf/
	eval $PYTEST
else
       ....
fi

cd -
```



_Code quote:_
```Shell
	# add local pip installations to the PATH
	export PATH=$PATH:~/.local/bin/

	# run pytest with coverage
	cd $WORKDIR/tools/perf/
	coverage run -m pytest
	# '-i' to ignore errors on Arch Linux (caused by a bug)
	coverage report -i
	cd -
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1498)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[utils/docker/run-build.sh, line 148 at r4](https://reviewable.io/reviews/pmem/rpma/1498#-MuVGyO_BDS5k92zTD9x:-MuVI95p2gIB2VQFYD8H:b5drg06) ([raw file](https://github.com/pmem/rpma/blob/13daf6147fe9b9d33884bde39d9f9eceeb3f7a6f/utils/docker/run-build.sh#L148)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The new coverage conflicts with the current one for C language.

`if [ "$COVERAGE" == "1" ]; then` the old version of code should be run and the new one otherwise:

```
if [ "$COVERAGE" == "1" ]; then
	# run pytest
	cd $WORKDIR/tools/perf/
	eval $PYTEST
else
       ....
endif

cd -
```
</blockquote></details>

Not `endif` but `fi` of course.

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1498)* status: 0 of 30 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[utils/docker/run-build.sh, line 148 at r4](https://reviewable.io/reviews/pmem/rpma/1498#-MuVGyO_BDS5k92zTD9x:-MuVMJmF6UNUrnEX5n4z:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/13daf6147fe9b9d33884bde39d9f9eceeb3f7a6f/utils/docker/run-build.sh#L148)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not `endif` but `fi` of course.
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 30 of 30 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1498)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

___
*[utils/docker/run-build.sh, line 151 at r5](https://reviewable.io/reviews/pmem/rpma/1498#-MuVTlAL0wDUvOG4K75A:-MuVTlAL0wDUvOG4K75B:batv3ox) ([raw file](https://github.com/pmem/rpma/blob/e685bd1ae610340af9c904c0900938e0f8ef9643/utils/docker/run-build.sh#L151)):*
> ```Shell
> 	if [ "$COVERAGE" == "1" ]; then
> 	# run pytest
> 	eval $PYTEST
> ```

wrong indentation



_Code quote:_
```Shell
	# run pytest
	eval $PYTEST
```
___
*[utils/docker/run-build.sh, line 157 at r5](https://reviewable.io/reviews/pmem/rpma/1498#-MuVTsDE1DDWiuEEg9bJ:-MuVTsDE1DDWiuEEg9bK:batv3ox) ([raw file](https://github.com/pmem/rpma/blob/e685bd1ae610340af9c904c0900938e0f8ef9643/utils/docker/run-build.sh#L157)):*
> ```Shell
> 	# run pytest with coverage
> 	coverage run -m pytest
> 	# '-i' to ignore errors on Arch Linux (caused by a bug)
> ```

wrong indentation



_Code quote:_
```Shell
	# add local pip installations to the PATH
	export PATH=$PATH:~/.local/bin/
	# run pytest with coverage
	coverage run -m pytest
	# '-i' to ignore errors on Arch Linux (caused by a bug)
	coverage report -i
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1498)* status: 29 of 30 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[utils/docker/run-build.sh, line 151 at r5](https://reviewable.io/reviews/pmem/rpma/1498#-MuVTlAL0wDUvOG4K75A:-MuVb8WbCowoqgfmMdfU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e685bd1ae610340af9c904c0900938e0f8ef9643/utils/docker/run-build.sh#L151)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

wrong indentation
</blockquote></details>

Done.
___
*[utils/docker/run-build.sh, line 157 at r5](https://reviewable.io/reviews/pmem/rpma/1498#-MuVTsDE1DDWiuEEg9bJ:-MuVb8uK3a6RtHWGtxKi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e685bd1ae610340af9c904c0900938e0f8ef9643/utils/docker/run-build.sh#L157)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

wrong indentation
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1498)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1498#-:-MuVexY8B-N5De-jMCFL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1498#-:-MujJiie9bAjSYMXKl7x:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1498)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

___
*[utils/docker/run-build.sh, line 149 at r6](https://reviewable.io/reviews/pmem/rpma/1498#-MujKARsEFag8Juqk7Dk:-MujKARsEFag8Juqk7Dl:bm5rub6) ([raw file](https://github.com/pmem/rpma/blob/5ddc2d5e7b28b8474b3307429443317643a78ab9/utils/docker/run-build.sh#L149)):*
> ```Shell
> 	cd $WORKDIR/tools/perf/
> 
> 	if [ "$COVERAGE" == "1" ]; then
> ```

Please add a comment above:
```
	# The python coverage corrupts the results of the C coverage,
	# so we have to run them exclusively:
	if [ "$COVERAGE" == "1" ]; then
```



_Code quote:_
```Shell
if [ "$COVERAGE" == "1" ]; then
```
___
*[utils/docker/run-build.sh, line 151 at r6](https://reviewable.io/reviews/pmem/rpma/1498#-MujMxdKCichUc9VbGXB:-MujMxdKCichUc9VbGXC:b-hdgpvo) ([raw file](https://github.com/pmem/rpma/blob/5ddc2d5e7b28b8474b3307429443317643a78ab9/utils/docker/run-build.sh#L151)):*
> ```Shell
> 	if [ "$COVERAGE" == "1" ]; then
> 		# run pytest
> 		eval $PYTEST
> ```

```
		# Run only pytest, because the C coverage
		# is checked in this build.
		eval $PYTEST
```



_Code quote:_
```Shell
		# run pytest
		eval $PYTEST
```
___
*[utils/docker/run-build.sh, line 155 at r6](https://reviewable.io/reviews/pmem/rpma/1498#-MujN3Cs3VksNeU63ftQ:-MujN3Cs3VksNeU63ftR:bxi1fhu) ([raw file](https://github.com/pmem/rpma/blob/5ddc2d5e7b28b8474b3307429443317643a78ab9/utils/docker/run-build.sh#L155)):*
> ```Shell
> 		# add local pip installations to the PATH
> 		export PATH=$PATH:~/.local/bin/
> 		# run pytest with coverage
> ```

```
		# run pytest and check the coverage of python tests
```



_Code quote:_
```Shell
# run pytest with coverage
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1498)* status: 29 of 30 files reviewed, 3 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[utils/docker/run-build.sh, line 149 at r6](https://reviewable.io/reviews/pmem/rpma/1498#-MujKARsEFag8Juqk7Dk:-MukNQ5HAbgk-oIDrO37:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5ddc2d5e7b28b8474b3307429443317643a78ab9/utils/docker/run-build.sh#L149)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please add a comment above:
```
	# The python coverage corrupts the results of the C coverage,
	# so we have to run them exclusively:
	if [ "$COVERAGE" == "1" ]; then
```
</blockquote></details>

Done.
___
*[utils/docker/run-build.sh, line 151 at r6](https://reviewable.io/reviews/pmem/rpma/1498#-MujMxdKCichUc9VbGXB:-MukNR3Z8eN0XKpe-mrx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5ddc2d5e7b28b8474b3307429443317643a78ab9/utils/docker/run-build.sh#L151)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
		# Run only pytest, because the C coverage
		# is checked in this build.
		eval $PYTEST
```
</blockquote></details>

Done.
___
*[utils/docker/run-build.sh, line 155 at r6](https://reviewable.io/reviews/pmem/rpma/1498#-MujN3Cs3VksNeU63ftQ:-MukNQfn4F4ie2beAQli:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5ddc2d5e7b28b8474b3307429443317643a78ab9/utils/docker/run-build.sh#L155)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
		# run pytest and check the coverage of python tests
```

</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1498)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
