### PR TITLE
tools: implement __result_append and __result_is_done

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1395)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1395)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[tools/perf/lib/benchmark/runner/common.py, line 25 at r1](https://reviewable.io/reviews/pmem/rpma/1395#-MqJeosu8Zr4lwex8NFW:-MqJeosu8Zr4lwex8NFX:b6e96iw) ([raw file](https://github.com/pmem/rpma/blob/3717b3a9258de6fad1d295f0677aef1f4d91b370/tools/perf/lib/benchmark/runner/common.py#L25)):*
> ```
> result_append(result: dict, data: list, idfile: str)
> ```
Shall result_append have a similar args order as result_is_done has?
```result_append(data: list, idfile: str, result: dict)
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1395)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1395)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/perf/lib/benchmark/runner/common.py, line 25 at r1](https://reviewable.io/reviews/pmem/rpma/1395#-MqJeosu8Zr4lwex8NFW:-MqJhSoB9mmYQX7MoyML:bgmv70s) ([raw file](https://github.com/pmem/rpma/blob/3717b3a9258de6fad1d295f0677aef1f4d91b370/tools/perf/lib/benchmark/runner/common.py#L25)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> result_append(result: dict, data: list, idfile: str)
> ```
Shall result_append have a similar args order as result_is_done has?
```result_append(data: list, idfile: str, result: dict)
```

</blockquote></details>

First of all, they have different arguments, so they cannot have similar order of them.
An order is suited to what a command does:

The `result_append()` function:

- def result_append(**result**: dict, **data**: list, **idfile**: str) -> None

appends the **result** to the **data** and to the **idfile**.

And the `result_is_done()` function:

- def result_is_done(**data**: list, **x_key**: str, **x_value**: int) -> bool

checks if the **data** list has the **x_key** with the **x_value** value.


The last one could be changed to:

- def result_is_done(**x_key**: str, **x_value**: int, **data**: list) -> bool

(look for the **x_key** with the **x_value** value in the  **data** list)

Is it better for you?

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1395)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/lib/benchmark/runner/common.py, line 25 at r1](https://reviewable.io/reviews/pmem/rpma/1395#-MqJeosu8Zr4lwex8NFW:-MqJl9bzE0mhSqmZZmya:b-tpzwra) ([raw file](https://github.com/pmem/rpma/blob/3717b3a9258de6fad1d295f0677aef1f4d91b370/tools/perf/lib/benchmark/runner/common.py#L25)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

First of all, they have different arguments, so they cannot have similar order of them.
An order is suited to what a command does:

The `result_append()` function:

- def result_append(**result**: dict, **data**: list, **idfile**: str) -> None

appends the **result** to the **data** and to the **idfile**.

And the `result_is_done()` function:

- def result_is_done(**data**: list, **x_key**: str, **x_value**: int) -> bool

checks if the **data** list has the **x_key** with the **x_value** value.


The last one could be changed to:

- def result_is_done(**x_key**: str, **x_value**: int, **data**: list) -> bool

(look for the **x_key** with the **x_value** value in the  **data** list)

Is it better for you?
</blockquote></details>

**data** is a more-less synonym of **self** in both function APIs so I suggest putting it in the front

def result_append(data: list, idfile: str, result: dict) -> None
append the **data** and **idfile** with **result**

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1395)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/perf/lib/benchmark/runner/common.py, line 25 at r1](https://reviewable.io/reviews/pmem/rpma/1395#-MqJeosu8Zr4lwex8NFW:-MqJn2duEW25nCUStWQf:bppzcqs) ([raw file](https://github.com/pmem/rpma/blob/3717b3a9258de6fad1d295f0677aef1f4d91b370/tools/perf/lib/benchmark/runner/common.py#L25)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

**data** is a more-less synonym of **self** in both function APIs so I suggest putting it in the front

def result_append(data: list, idfile: str, result: dict) -> None
append the **data** and **idfile** with **result**
</blockquote></details>

But the order in English is different!

You can append something-1 to something-2, so

You **append** the **result** to the **data** and to the **idfile**.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1395)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/perf/lib/benchmark/runner/common.py, line 25 at r1](https://reviewable.io/reviews/pmem/rpma/1395#-MqJeosu8Zr4lwex8NFW:-MqJtsCX1b75b3QYaid-:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/3717b3a9258de6fad1d295f0677aef1f4d91b370/tools/perf/lib/benchmark/runner/common.py#L25)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

But the order in English is different!

You can append something-1 to something-2, so

You **append** the **result** to the **data** and to the **idfile**.

</blockquote></details>

Done

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1395)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1395)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1395#-:-MqLAfcR--KbZKYA5F1R:bdycpsm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1395#-:-MqO993d-opMWnSleqCU:bnfp4nl)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @grom72)

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1395#-:-MqOAfnb7yJ0Yn1JKk47:bg7igkv)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
