### PR TITLE
doc: perf-tuning-latency RDMA

### PR DESCRIPTION
**Pull request by janekmi**
Preview: https://janekmi.github.io/rpma/documentation/perf-tuning-latency.html

Requires:
- [x] #595
- [x] #600

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/596)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/596)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/596)* status: all files reviewed, 7 unresolved discussions (waiting on @janekmi)

___
*[documentation/perf-tuning-latency.md, line 98 at r1](https://reviewable.io/reviews/pmem/rpma/596#-MM_pi1FDmF9LNRTr9nk:-MM_pi1G-CMC3CdfVz3C:bcnl72a) ([raw file](https://github.com/pmem/rpma/blob/8b51ba55d5b7a230eb108c50203c80ab9f943e7f/documentation/perf-tuning-latency.md#L98)):*
> ```Markdown
> sudo cpupower frequency-set --max $FREQ
> ```
> ## RDMA-capable network interface
> ```

please add one empty line before `## RDMA-capable network interface`
___
*[documentation/perf-tuning-latency.md, line 106 at r1](https://reviewable.io/reviews/pmem/rpma/596#-MM_rCNhEFul6CLdMgWJ:-MM_rCNiD7vp-lErNjhr:bbacz0t) ([raw file](https://github.com/pmem/rpma/blob/8b51ba55d5b7a230eb108c50203c80ab9f943e7f/documentation/perf-tuning-latency.md#L106)):*
> ```Markdown
> ### Link mode [[3.2]][mlx-port-speed]
> 
> * List supported link modes.
> ```

The full stop looks strange at the of this line, maybe ':' instead?
___
*[documentation/perf-tuning-latency.md, line 109 at r1](https://reviewable.io/reviews/pmem/rpma/596#-MM_q5PK6apBSusqaax3:-MM_q5PK6apBSusqaax4:b-fqj2qi) ([raw file](https://github.com/pmem/rpma/blob/8b51ba55d5b7a230eb108c50203c80ab9f943e7f/documentation/perf-tuning-latency.md#L109)):*
> ```
> ethtool ens785f0
> ```

Commands are usually prefixed with the prompt sign '$':

```sh
$ ethtool ens785f0
```
___
*[documentation/perf-tuning-latency.md, line 121 at r1](https://reviewable.io/reviews/pmem/rpma/596#-MM_rQXRBNpUAO7Us6A4:-MM_rQXRBNpUAO7Us6A5:b4ucwks) ([raw file](https://github.com/pmem/rpma/blob/8b51ba55d5b7a230eb108c50203c80ab9f943e7f/documentation/perf-tuning-latency.md#L121)):*
> ```
> lue.
> ```

`:` ?
___
*[documentation/perf-tuning-latency.md, line 124 at r1](https://reviewable.io/reviews/pmem/rpma/596#-MM_qjV6EnsvSbAuQm1t:-MM_qjV6EnsvSbAuQm1u:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/8b51ba55d5b7a230eb108c50203c80ab9f943e7f/documentation/perf-tuning-latency.md#L124)):*
> ```Markdown
> 
> ```sh
> sudo ethtool -s ens785f0 speed 100000 autoneg off
> ```

.
___
*[documentation/perf-tuning-latency.md, line 129 at r1](https://reviewable.io/reviews/pmem/rpma/596#-MM_qv4gCITCP5a489Hv:-MM_qv4gCITCP5a489Hw:b-nd8l8c) ([raw file](https://github.com/pmem/rpma/blob/8b51ba55d5b7a230eb108c50203c80ab9f943e7f/documentation/perf-tuning-latency.md#L129)):*
> ```
> Set the MTU 
> ```

`Set MTU ...` 
___
*[documentation/perf-tuning-latency.md, line 132 at r1](https://reviewable.io/reviews/pmem/rpma/596#-MM_qkhT70pa7T-s4JKd:-MM_qkhT70pa7T-s4JKe:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/8b51ba55d5b7a230eb108c50203c80ab9f943e7f/documentation/perf-tuning-latency.md#L132)):*
> ```Markdown
> 
> ```sh
> ifconfig ens785f0 mtu 4200
> ```

.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/596)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[documentation/perf-tuning-latency.md, line 98 at r1](https://reviewable.io/reviews/pmem/rpma/596#-MM_pi1FDmF9LNRTr9nk:-MM_tMOb8peS9HOl02ZB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8b51ba55d5b7a230eb108c50203c80ab9f943e7f/documentation/perf-tuning-latency.md#L98)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

please add one empty line before `## RDMA-capable network interface`
</blockquote></details>

Done.
___
*[documentation/perf-tuning-latency.md, line 106 at r1](https://reviewable.io/reviews/pmem/rpma/596#-MM_rCNhEFul6CLdMgWJ:-MM_tTPv2lew82hDAPWG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8b51ba55d5b7a230eb108c50203c80ab9f943e7f/documentation/perf-tuning-latency.md#L106)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The full stop looks strange at the of this line, maybe ':' instead?
</blockquote></details>

Done.
___
*[documentation/perf-tuning-latency.md, line 109 at r1](https://reviewable.io/reviews/pmem/rpma/596#-MM_q5PK6apBSusqaax3:-MM_tYJu8RSotiB35BgS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8b51ba55d5b7a230eb108c50203c80ab9f943e7f/documentation/perf-tuning-latency.md#L109)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> ethtool ens785f0
> ```

Commands are usually prefixed with the prompt sign '$':

```sh
$ ethtool ens785f0
```
</blockquote></details>

Done.
___
*[documentation/perf-tuning-latency.md, line 121 at r1](https://reviewable.io/reviews/pmem/rpma/596#-MM_rQXRBNpUAO7Us6A4:-MM_t_B_2OojDdXl2sXN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8b51ba55d5b7a230eb108c50203c80ab9f943e7f/documentation/perf-tuning-latency.md#L121)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> lue.
> ```

`:` ?
</blockquote></details>

Done.
___
*[documentation/perf-tuning-latency.md, line 124 at r1](https://reviewable.io/reviews/pmem/rpma/596#-MM_qjV6EnsvSbAuQm1t:-MM_t_su6xaR_NIxSH2u:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8b51ba55d5b7a230eb108c50203c80ab9f943e7f/documentation/perf-tuning-latency.md#L124)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[documentation/perf-tuning-latency.md, line 129 at r1](https://reviewable.io/reviews/pmem/rpma/596#-MM_qv4gCITCP5a489Hv:-MM_tco3-ZiCQ3H9032r:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8b51ba55d5b7a230eb108c50203c80ab9f943e7f/documentation/perf-tuning-latency.md#L129)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> Set the MTU 
> ```

`Set MTU ...` 
</blockquote></details>

Done.
___
*[documentation/perf-tuning-latency.md, line 132 at r1](https://reviewable.io/reviews/pmem/rpma/596#-MM_qkhT70pa7T-s4JKd:-MM_tug25QeSGroMNoQv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8b51ba55d5b7a230eb108c50203c80ab9f943e7f/documentation/perf-tuning-latency.md#L132)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/596#-:-MM_uMBcEivmbI1hMb8a:bnfp4nl)* status: all files reviewed, 7 unresolved discussions (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/596#-:-MM_uSoP72LwhBiJw8P_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
