### PR TITLE
tools: introduce a new csv compare layout (bw_vs_bs)

### PR DESCRIPTION
**Pull request by janekmi**
```sh
$ ./csv_compare.py --legend ib_read_bw --output_title "A show off of the new layout" \
ib_read_bw-ds-1th-20-12-08-221604.csv --output_layout bw_vs_bs
```

compare

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/644)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/644)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/csv_compare.py, line 53 at r1](https://reviewable.io/reviews/pmem/rpma/644#-MO5pXz00Jk2L-zj5Kwh:-MO5pXz1-PKpZ3sSN1iN:b-ocqt42) ([raw file](https://github.com/pmem/rpma/blob/96006042798888924d479c23e0514d6f064949bf/tools/csv_compare.py#L53)):*
> ```
> ax, dfs
> ```

What do `ax` and  `dfs` mean? A bit more comments please, because incomprehensible variables make the whole code incomprehensible...
___
*[tools/csv_compare.py, line 56 at r1](https://reviewable.io/reviews/pmem/rpma/644#-MO5qGmDC3xvaQz8giT8:-MO5qGmDC3xvaQz8giT9:b5kzfmw) ([raw file](https://github.com/pmem/rpma/blob/96006042798888924d479c23e0514d6f064949bf/tools/csv_compare.py#L56)):*
> ```
> df
> ```

`df` ?

.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/644)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tools/csv_compare.py, line 53 at r1](https://reviewable.io/reviews/pmem/rpma/644#-MO5pXz00Jk2L-zj5Kwh:-MO6YIqZCOg5tti5nZJg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/96006042798888924d479c23e0514d6f064949bf/tools/csv_compare.py#L53)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> ax, dfs
> ```

What do `ax` and  `dfs` mean? A bit more comments please, because incomprehensible variables make the whole code incomprehensible...
</blockquote></details>

Done.
___
*[tools/csv_compare.py, line 56 at r1](https://reviewable.io/reviews/pmem/rpma/644#-MO5qGmDC3xvaQz8giT8:-MO6YJsoBxdNmoof4AVS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/96006042798888924d479c23e0514d6f064949bf/tools/csv_compare.py#L56)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> df
> ```

`df` ?

.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/644)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

___
*[tools/csv_compare.py, line 53 at r1](https://reviewable.io/reviews/pmem/rpma/644#-MO5pXz00Jk2L-zj5Kwh:-MO6cK_w6Dw6vhrhxZN1:b-ucfknh) ([raw file](https://github.com/pmem/rpma/blob/96006042798888924d479c23e0514d6f064949bf/tools/csv_compare.py#L53)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thanks!

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/644#-:-MO6cMvI8ZhBoMNrxVt8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
