### PR TITLE
tools: ib_read.py: implement __server_start and __server_stop

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #1351
- [x] #1378 

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1352)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1352)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 94 at r4](https://reviewable.io/reviews/pmem/rpma/1352#-MpqXFui16aqTlq7xRSg:-MpqXFui16aqTlq7xRSh:bu0k98b) ([raw file](https://github.com/pmem/rpma/blob/8fac133d5614eb01f1e9e292ecf742824c6ebf83/tools/perf/lib/benchmark/runner/ib_read.py#L94)):*
> ```Python
>         r_numa_n = str(self.__config['REMOTE_JOB_NUMA'])
>         r_ib_path = ''.join([self.__config['REMOTE_IB_PATH'],
>                              settings['ib_tool']])
> ```

`os.path.join()`
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 108 at r4](https://reviewable.io/reviews/pmem/rpma/1352#-MpqY2KP3lR9cob3w211:-MpqY2KP3lR9cob3w212:bjecwak) ([raw file](https://github.com/pmem/rpma/blob/8fac133d5614eb01f1e9e292ecf742824c6ebf83/tools/perf/lib/benchmark/runner/ib_read.py#L108)):*
> ```Python
>         with open(settings['logfile_server'], 'w', encoding='utf-8') as log:
>             log.write(stdout)
>             log.write(stderr)
> ```

```python
with ... as log:
    log.write('Stdout:\n{}\nStderr:\n{}'.format(self.__server.stdout, self.__server.stderr))
```
?
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 105 at r5](https://reviewable.io/reviews/pmem/rpma/1352#-MpqYqRbAhaTLvZXY-ek:-MpqYqRbAhaTLvZXY-el:b-546qx9) ([raw file](https://github.com/pmem/rpma/blob/f1d057ebcd19d81c0b2af8ffc15a22a544d5896e/tools/perf/lib/benchmark/runner/ib_read.py#L105)):*
> ```Python
>         self.__server.wait()
>         stdout = self.__server.stdout.read().decode().strip()
>         stderr = self.__server.stderr.read().decode().strip()
> ```

Can you provide references? I want to understand better what you have done here.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1352)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 94 at r4](https://reviewable.io/reviews/pmem/rpma/1352#-MpqXFui16aqTlq7xRSg:-MpqbojZDXfu1CmhpFt1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8fac133d5614eb01f1e9e292ecf742824c6ebf83/tools/perf/lib/benchmark/runner/ib_read.py#L94)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`os.path.join()`
</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 105 at r5](https://reviewable.io/reviews/pmem/rpma/1352#-MpqYqRbAhaTLvZXY-ek:-MpqZYwp9y-RCfNU5-Z8:b-rpkez6) ([raw file](https://github.com/pmem/rpma/blob/f1d057ebcd19d81c0b2af8ffc15a22a544d5896e/tools/perf/lib/benchmark/runner/ib_read.py#L105)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Can you provide references? I want to understand better what you have done here.
</blockquote></details>

https://www.programcreek.com/python/example/4561/paramiko.SSHClient 
:-D

**Review by janekmi — APPROVED** [review]
:goat: 

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1352#-:-Mptul2_8VhWDO_vkv1p:bdycpsm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 105 at r5](https://reviewable.io/reviews/pmem/rpma/1352#-MpqYqRbAhaTLvZXY-ek:-MptueOMCMBmxY8qKqGU:b-jhyysx) ([raw file](https://github.com/pmem/rpma/blob/f1d057ebcd19d81c0b2af8ffc15a22a544d5896e/tools/perf/lib/benchmark/runner/ib_read.py#L105)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

https://www.programcreek.com/python/example/4561/paramiko.SSHClient 
:-D
</blockquote></details>

Got it. Thanks.

**Review by osalyk — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1352)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 98 at r8](https://reviewable.io/reviews/pmem/rpma/1352#-MpvdKtWAa6UzOKABOZ2:-MpvdKtWAa6UzOKABOZ3:bp6c60h) ([raw file](https://github.com/pmem/rpma/blob/22ae51d14950de3503190f80f7667c88700e3d43/tools/perf/lib/benchmark/runner/ib_read.py#L98)):*
> ```Python
>         args = ['numactl', '-N', r_numa_n, r_ib_path, *r_aux_params]
>         # XXX add option to dump the command
>         self.__server = RemoteCmd.run_async(self.__config, args, None)
> ```

The env parameter is set to None by default

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1352)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi and @osalyk)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 98 at r8](https://reviewable.io/reviews/pmem/rpma/1352#-MpvdKtWAa6UzOKABOZ2:-Mpve0SI8XMbApoVTi65:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/22ae51d14950de3503190f80f7667c88700e3d43/tools/perf/lib/benchmark/runner/ib_read.py#L98)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

The env parameter is set to None by default
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1352#-:-MpveFlM-PG68purrutC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1352#-:-Mpvgw1O6T6BwiAO6jC0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
