### PR TITLE
tools: add cpuio and busy_wait_polling to AOF server fio job files

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/956)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/956#-:-MW474NZ6uMFFydj_zXG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/956)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/956#-MW4G8gb9CKDkKu94XqU:-MW4G8gb9CKDkKu94XqV:b-haj1ml) (no related file):*
fio_jobs/librpma_aof_hw-server.fio misses:

```sh
[cpuio]
ioengine=cpuio
cpuload=${cpuload}
numjobs=${cores_per_socket}
```

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/956)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/956#-MW4G8gb9CKDkKu94XqU:-MW4PI7qA0AScDK0wynN:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

fio_jobs/librpma_aof_hw-server.fio misses:

```sh
[cpuio]
ioengine=cpuio
cpuload=${cpuload}
numjobs=${cores_per_socket}
```
</blockquote></details>

Done.

---

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/956#-:-MW4Uv_nAGYgvgiRaa3z:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
