### PR TITLE
rpma: rename rpma.c to utils.c as it is a utils functions src file.

### PR DESCRIPTION
**Pull request by grom72**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1803)

### CODE REVIEW

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1803#-:-N3Yqy2O2d0jYZxw8SmP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1803)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[`tests/integration/example-01-connection/CMakeLists.txt` line 30 at r1](https://reviewable.io/reviews/pmem/rpma/1803#-N3dcHcWEPYvEFSS2oF_:-N3dcHcX4vk7offSXpxi:b-2j55bp) ([raw file](https://github.com/pmem/rpma/blob/1111effbee1b0268e60a76a1159ed709111bc611/tests/integration/example-01-connection/CMakeLists.txt#L30)):*
> ```CMake
> 	${LIBRPMA_SOURCE_DIR}/peer_cfg.c
> 	${LIBRPMA_SOURCE_DIR}/private_data.c
> 	${LIBRPMA_SOURCE_DIR}/utils.c
> ```

Alphabetical order



_Code quote:_
```CMake
${LIBRPMA_SOURCE_DIR}/utils.c
```
___
*[`tests/integration/example-02-read-to-volatile/CMakeLists.txt` line 31 at r1](https://reviewable.io/reviews/pmem/rpma/1803#-N3dcPGVCyBq3vAfad5K:-N3dcPGVCyBq3vAfad5L:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/1111effbee1b0268e60a76a1159ed709111bc611/tests/integration/example-02-read-to-volatile/CMakeLists.txt#L31)):*
> ```CMake
> 	${LIBRPMA_SOURCE_DIR}/peer_cfg.c
> 	${LIBRPMA_SOURCE_DIR}/private_data.c
> 	${LIBRPMA_SOURCE_DIR}/utils.c
> ```

.
___
*[`tests/integration/example-04-write-to-persistent/CMakeLists.txt` line 31 at r1](https://reviewable.io/reviews/pmem/rpma/1803#-N3dcQa60DU6UyTCMIx_:-N3dcQa60DU6UyTCMIxa:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/1111effbee1b0268e60a76a1159ed709111bc611/tests/integration/example-04-write-to-persistent/CMakeLists.txt#L31)):*
> ```CMake
> 	${LIBRPMA_SOURCE_DIR}/peer_cfg.c
> 	${LIBRPMA_SOURCE_DIR}/private_data.c
> 	${LIBRPMA_SOURCE_DIR}/utils.c
> ```

.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1803)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[`tests/integration/example-01-connection/CMakeLists.txt` line 30 at r1](https://reviewable.io/reviews/pmem/rpma/1803#-N3dcHcWEPYvEFSS2oF_:-N3djveH3lixpfZtcRN4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f3b76e0cf0c03501e092c88f8cd18e83ab91c054/tests/integration/example-01-connection/CMakeLists.txt#L30)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Alphabetical order
</blockquote></details>

Done.
___
*[`tests/integration/example-02-read-to-volatile/CMakeLists.txt` line 31 at r1](https://reviewable.io/reviews/pmem/rpma/1803#-N3dcPGVCyBq3vAfad5K:-N3djw6DB1ORwk2SKvu4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f3b76e0cf0c03501e092c88f8cd18e83ab91c054/tests/integration/example-02-read-to-volatile/CMakeLists.txt#L31)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`tests/integration/example-04-write-to-persistent/CMakeLists.txt` line 31 at r1](https://reviewable.io/reviews/pmem/rpma/1803#-N3dcQa60DU6UyTCMIx_:-N3djwYM9J9RGAkEsePS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f3b76e0cf0c03501e092c88f8cd18e83ab91c054/tests/integration/example-04-write-to-persistent/CMakeLists.txt#L31)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1803)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1803#-N3doYEO30QMXC73fA7J:-N3doYEO30QMXC73fA7K:b-v3kov0) (no related file):*
CI builds fail

___

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1803)* status: 6 of 7 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`tests/integration/example-02-read-to-volatile/CMakeLists.txt` line 30 at r2](https://reviewable.io/reviews/pmem/rpma/1803#-N3doMoH6kG529mHhGcI:-N3dprpy7cvWkjkTEho_:bxqrnhw) ([raw file](https://github.com/pmem/rpma/blob/5d7a90d1cd3157e9db01a4bb9bb796dc852e6067/tests/integration/example-02-read-to-volatile/CMakeLists.txt#L30)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why have you removed `private_data.c`?
</blockquote></details>

By mistake ;)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1803)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1803#-:-N3dqf4bDh9XmXQtMC2j:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by osalyk — APPROVED** [review]
> Reviewed 3 of 3 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1803)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1803)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
