### PR TITLE
tools: perf: allow running benchmarks via various runners

### PR DESCRIPTION
**Pull request by janekmi**
- dummy runner existed previously and it has just gained an explicit entity
- bash runner is only a copy of already existing code using the rpma_fio_bench.sh and ib_read.sh scripts which
- will be hopefully soon replaced by a fully Python-based runner

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1322)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1322)* status: 0 of 16 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
> Reviewed 15 of 16 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1322)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @janekmi, @ldorau, and @osalyk)

___
*[tools/perf/lib/benchmark/base.py, line 8 at r1](https://reviewable.io/reviews/pmem/rpma/1322#-MocBoAP-_tW4hpbJGdP:-MocBoAP-_tW4hpbJGdQ:bu1a8bl) ([raw file](https://github.com/pmem/rpma/blob/8ff5e0f0f7218b4db1edf3d2ed00b60bf17fc949/tools/perf/lib/benchmark/base.py#L8)):*
> ```Python
> 
> #
> # benchmark.py -- a single benchmark object (EXPERIMENTAL)
> ```

base.py

**Review by ldorau — COMMENTED** [review]
> Reviewed 6 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1322)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @janekmi, @ldorau, and @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1322)* status: 15 of 16 files reviewed, 3 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[tools/perf/lib/benchmark/runner/__init__.py, line 7 at r1](https://reviewable.io/reviews/pmem/rpma/1322#-MocYoNV7ThsjYD8hzYm:-MocYoNV7ThsjYD8hzYn:bhrnli6) ([raw file](https://github.com/pmem/rpma/blob/8ff5e0f0f7218b4db1edf3d2ed00b60bf17fc949/tools/perf/lib/benchmark/runner/__init__.py#L7)):*
> ```
> (intentionally empty)
> ```

It is not empty
___
*[tools/perf/lib/benchmark/runner/dummy.py, line 42 at r1](https://reviewable.io/reviews/pmem/rpma/1322#-MocZSCy3r9O-OwOmCqO:-MocZSCz505LqF0G-DwM:b4qww4w) ([raw file](https://github.com/pmem/rpma/blob/8ff5e0f0f7218b4db1edf3d2ed00b60bf17fc949/tools/perf/lib/benchmark/runner/dummy.py#L42)):*
> ```Python
>         else:
>             output = [cls.__random_point() for _ in range(3)]
>         with open(benchmark.get_output_file(result_dir), 'w') as file:
> ```

PEP8 Error: `W1514: Using open without explicitly specifying an encoding (unspecified-encoding)`

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1322)* status: 15 of 16 files reviewed, 4 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[tools/perf/lib/benchmark/runner/dummy.py, line 35 at r1](https://reviewable.io/reviews/pmem/rpma/1322#-MochAeD4a314o1mmqEY:-MochAeE1JgOZ2Tshn7J:b6ufed7) ([raw file](https://github.com/pmem/rpma/blob/8ff5e0f0f7218b4db1edf3d2ed00b60bf17fc949/tools/perf/lib/benchmark/runner/dummy.py#L35)):*
> ```
> 'rw' in benchmark.oneseries['rw']
> ```

Is it correct?
Shouldn't it be: `benchmark.oneseries['rw'] == 'rw' ` ?

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1322)* status: 15 of 16 files reviewed, 4 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1322)* status: 15 of 16 files reviewed, 6 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[tools/perf/lib/benchmark/base.py, line 25 at r1](https://reviewable.io/reviews/pmem/rpma/1322#-MoclmU9Co0uvugAgnoM:-MoclmU9Co0uvugAgnoN:bridto8) ([raw file](https://github.com/pmem/rpma/blob/8ff5e0f0f7218b4db1edf3d2ed00b60bf17fc949/tools/perf/lib/benchmark/base.py#L25)):*
> ```
> When oneseries belongs to a Figure
> ```

Please explain those two cases: when oneseries belongs to a Figure and when it does not?
And what does it mean?
___
*[tools/perf/lib/benchmark/base.py, line 101 at r1](https://reviewable.io/reviews/pmem/rpma/1322#-MocyduF813sELWRHhIS:-MocyduF813sELWRHhIT:b-m5jtgw) ([raw file](https://github.com/pmem/rpma/blob/8ff5e0f0f7218b4db1edf3d2ed00b60bf17fc949/tools/perf/lib/benchmark/base.py#L101)):*
> ```
> cache
> ```

Maybe `get_oneseries` ?

**Review by ldorau — COMMENTED** [review]
> Reviewed 3 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1322)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1322)* status: all files reviewed, 8 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/tests/lib/benchmark/runner/test_dummy_run.py, line 22 at r1](https://reviewable.io/reviews/pmem/rpma/1322#-Mod3PSL80Mq7DzZycI7:-Mod3PSM8bkQoqAD5jAi:b-wbl38q) ([raw file](https://github.com/pmem/rpma/blob/8ff5e0f0f7218b4db1edf3d2ed00b60bf17fc949/tools/perf/tests/lib/benchmark/runner/test_dummy_run.py#L22)):*
> ```
> """XXX random vs not random results source"""
> ```

Could you elaborate?
___
*[tools/perf/tests/lib/benchmark/runner/test_dummy_run.py, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1322#-Mod3vzvAE01QZsjNylp:-Mod3vzvAE01QZsjNylq:b-2qx1b7) ([raw file](https://github.com/pmem/rpma/blob/8ff5e0f0f7218b4db1edf3d2ed00b60bf17fc949/tools/perf/tests/lib/benchmark/runner/test_dummy_run.py#L39)):*
> ```
> open(output, mode='r')
> ```

.
(encoding is missing)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1322)* status: all files reviewed, 9 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/tests/lib/benchmark/runner/test_bash_run.py, line 73 at r1](https://reviewable.io/reviews/pmem/rpma/1322#-ModXlTCAbmmRgUf310i:-ModXlTCAbmmRgUf310j:b-mpq4et) ([raw file](https://github.com/pmem/rpma/blob/8ff5e0f0f7218b4db1edf3d2ed00b60bf17fc949/tools/perf/tests/lib/benchmark/runner/test_bash_run.py#L73)):*
> ```
>     def run_mock(args, env, check):
>         assert len(args) == 5
> ```

`nonlocal output_file` is missing here

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 16 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1322)* status: all files reviewed, 9 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/tests/lib/benchmark/runner/test_bash_run.py, line 241 at r1](https://reviewable.io/reviews/pmem/rpma/1322#-ModZkWz8SHcGn3K0br7:-ModZkX-3nQRJGxzU98E:b-trwqw0) ([raw file](https://github.com/pmem/rpma/blob/8ff5e0f0f7218b4db1edf3d2ed00b60bf17fc949/tools/perf/tests/lib/benchmark/runner/test_bash_run.py#L241)):*
> ```
> def test_gpspm_no_busy_wait_polling(readwrite, mode, oneseries_bash, tmpdir, monkeypatch):
>     """filetype=pmem when no REMOTE_JOB_MEM_PATH provided"""
> ```

wrong comment

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1322)* status: all files reviewed, 11 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/lib/benchmark/base.py, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/1322#-Moeb1geARHzsn_4e8tU:-Moeb1geARHzsn_4e8tV:b21n6zf) ([raw file](https://github.com/pmem/rpma/blob/8ff5e0f0f7218b4db1edf3d2ed00b60bf17fc949/tools/perf/lib/benchmark/base.py#L48)):*
> ```
> self.req = oneseries['requirements']
> ```
___
*[tools/perf/lib/benchmark/base.py, line 56 at r1](https://reviewable.io/reviews/pmem/rpma/1322#-Moeacv95d9cKx59mGsJ:-Moeacv95d9cKx59mGsK:b-51017h) ([raw file](https://github.com/pmem/rpma/blob/8ff5e0f0f7218b4db1edf3d2ed00b60bf17fc949/tools/perf/lib/benchmark/base.py#L56)):*
> ```Python
>     def __eq__(self, other):
>         """A comparison function"""
>         # The same benchmark run under different requirements
> ```

Two same benchmarks running under different requirements are two different benchmarks. I would say this sounds better

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1322)* status: 11 of 16 files reviewed, 10 unresolved discussions (waiting on @haichangsi, @ldorau, and @osalyk)

___
*[tools/perf/lib/benchmark/base.py, line 8 at r1](https://reviewable.io/reviews/pmem/rpma/1322#-MocBoAP-_tW4hpbJGdP:-MoeTBDZ7cjtPZU8873A:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8ff5e0f0f7218b4db1edf3d2ed00b60bf17fc949/tools/perf/lib/benchmark/base.py#L8)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

base.py
</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/base.py, line 25 at r1](https://reviewable.io/reviews/pmem/rpma/1322#-MoclmU9Co0uvugAgnoM:-MoeTQj1-LLFCxoDmonG:bk2mf1s) ([raw file](https://github.com/pmem/rpma/blob/8ff5e0f0f7218b4db1edf3d2ed00b60bf17fc949/tools/perf/lib/benchmark/base.py#L25)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> When oneseries belongs to a Figure
> ```

Please explain those two cases: when oneseries belongs to a Figure and when it does not?
And what does it mean?
</blockquote></details>

Yeah... a rough edge of this solution. This part was just moved from lib.Benchmark.
I will explain all of these in the documentation which is planned for the upcoming days.
Maybe we will come with a nicer solution.
___
*[tools/perf/lib/benchmark/base.py, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/1322#-Moeb1geARHzsn_4e8tU:-MofTu8aAmkEEtltqp36:b-8dl0zt) ([raw file](https://github.com/pmem/rpma/blob/8ff5e0f0f7218b4db1edf3d2ed00b60bf17fc949/tools/perf/lib/benchmark/base.py#L48)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

> ```
> self.req = oneseries['requirements']
> ```

</blockquote></details>

Nope. The condition above, by being false, determined the oneseries dictionary does not have such a key.
I see this code can be simplified e.g.

```python
self.req = oneseries.pop('requirements', {})
```

But I do not want to refactor this code now. It is a lot of copied code with a purpose more important than fixing all imperfections.
___
*[tools/perf/lib/benchmark/base.py, line 56 at r1](https://reviewable.io/reviews/pmem/rpma/1322#-Moeacv95d9cKx59mGsJ:-MofWTbd1m2asKDSQYYq:bmijjy6) ([raw file](https://github.com/pmem/rpma/blob/8ff5e0f0f7218b4db1edf3d2ed00b60bf17fc949/tools/perf/lib/benchmark/base.py#L56)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Two same benchmarks running under different requirements are two different benchmarks. I would say this sounds better
</blockquote></details>

Your proposition is interesting. I haven't seen such a construction. I have to get familiarized with it. In the meantime, I have proposed something simpler. Maybe less controversial.

**Note**: I know Reviewable do not follow, but this code has been only copied to another file. I do not consider changing it because it is not the purpose of this PR.
___
*[tools/perf/lib/benchmark/base.py, line 101 at r1](https://reviewable.io/reviews/pmem/rpma/1322#-MocyduF813sELWRHhIS:-MoeU3ayEVhp-1zhFfPv:bq1vcru) ([raw file](https://github.com/pmem/rpma/blob/8ff5e0f0f7218b4db1edf3d2ed00b60bf17fc949/tools/perf/lib/benchmark/base.py#L101)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> cache
> ```

Maybe `get_oneseries` ?
</blockquote></details>

It is a part of the naming convention used for all the classes of this "package".
The idea is to have an obviously named function providing a dictionary representation of the state of the (whatever) object for the purpose of writing it down to a file.
___
*[tools/perf/lib/benchmark/runner/__init__.py, line 7 at r1](https://reviewable.io/reviews/pmem/rpma/1322#-MocYoNV7ThsjYD8hzYm:-MoeUuXh4MEl5yJ3s873:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8ff5e0f0f7218b4db1edf3d2ed00b60bf17fc949/tools/perf/lib/benchmark/runner/__init__.py#L7)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> (intentionally empty)
> ```

It is not empty
</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/runner/dummy.py, line 35 at r1](https://reviewable.io/reviews/pmem/rpma/1322#-MochAeD4a314o1mmqEY:-MoeV19m8Jh6B4H11G2r:b9kji1b) ([raw file](https://github.com/pmem/rpma/blob/8ff5e0f0f7218b4db1edf3d2ed00b60bf17fc949/tools/perf/lib/benchmark/runner/dummy.py#L35)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 'rw' in benchmark.oneseries['rw']
> ```

Is it correct?
Shouldn't it be: `benchmark.oneseries['rw'] == 'rw' ` ?
</blockquote></details>

Yes. It is. You can have either 'rw' or 'randrw'.
___
*[tools/perf/lib/benchmark/runner/dummy.py, line 42 at r1](https://reviewable.io/reviews/pmem/rpma/1322#-MocZSCy3r9O-OwOmCqO:-MofYtkh-egAzR2C4zTj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8ff5e0f0f7218b4db1edf3d2ed00b60bf17fc949/tools/perf/lib/benchmark/runner/dummy.py#L42)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

PEP8 Error: `W1514: Using open without explicitly specifying an encoding (unspecified-encoding)`
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_bash_run.py, line 73 at r1](https://reviewable.io/reviews/pmem/rpma/1322#-ModXlTCAbmmRgUf310i:-MofTf4I57VKqCx26r5V:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8ff5e0f0f7218b4db1edf3d2ed00b60bf17fc949/tools/perf/tests/lib/benchmark/runner/test_bash_run.py#L73)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>     def run_mock(args, env, check):
>         assert len(args) == 5
> ```

`nonlocal output_file` is missing here
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_bash_run.py, line 241 at r1](https://reviewable.io/reviews/pmem/rpma/1322#-ModZkWz8SHcGn3K0br7:-Mof_0deBKnz4q0dM4JF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8ff5e0f0f7218b4db1edf3d2ed00b60bf17fc949/tools/perf/tests/lib/benchmark/runner/test_bash_run.py#L241)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> def test_gpspm_no_busy_wait_polling(readwrite, mode, oneseries_bash, tmpdir, monkeypatch):
>     """filetype=pmem when no REMOTE_JOB_MEM_PATH provided"""
> ```

wrong comment
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_dummy_run.py, line 22 at r1](https://reviewable.io/reviews/pmem/rpma/1322#-Mod3PSL80Mq7DzZycI7:-Mofa93hE3rpcD-G0cqf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8ff5e0f0f7218b4db1edf3d2ed00b60bf17fc949/tools/perf/tests/lib/benchmark/runner/test_dummy_run.py#L22)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> """XXX random vs not random results source"""
> ```

Could you elaborate?
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_dummy_run.py, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1322#-Mod3vzvAE01QZsjNylp:-Mofa9rcBG34QdBOY18f:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8ff5e0f0f7218b4db1edf3d2ed00b60bf17fc949/tools/perf/tests/lib/benchmark/runner/test_dummy_run.py#L39)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> open(output, mode='r')
> ```

.
(encoding is missing)
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1322)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi, @janekmi, and @osalyk)

___
*[tools/perf/tests/lib/benchmark/runner/test_bash_run.py, line 237 at r2](https://reviewable.io/reviews/pmem/rpma/1322#-Moh0Zt9Ee6tfL6YqOr9:-Moh0Zt9Ee6tfL6YqOrA:b-frw73f) ([raw file](https://github.com/pmem/rpma/blob/8583a4ad8aef8b951df8eeb1c9ddf885931a3d69/tools/perf/tests/lib/benchmark/runner/test_bash_run.py#L237)):*
> ```
> @pytest.mark.parametrize('readwrite', ['write', 'randwrite'])
> ```

Why have you removed the rest? 
` ['read', 'randread', 'write', 'randwrite', 'rw', 'randrw'])`

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1322)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi, @ldorau, and @osalyk)

___
*[tools/perf/tests/lib/benchmark/runner/test_bash_run.py, line 237 at r2](https://reviewable.io/reviews/pmem/rpma/1322#-Moh0Zt9Ee6tfL6YqOr9:-MohGBdm8XjD_evFeFEq:bv31ejq) ([raw file](https://github.com/pmem/rpma/blob/8583a4ad8aef8b951df8eeb1c9ddf885931a3d69/tools/perf/tests/lib/benchmark/runner/test_bash_run.py#L237)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> @pytest.mark.parametrize('readwrite', ['write', 'randwrite'])
> ```

Why have you removed the rest? 
` ['read', 'randread', 'write', 'randwrite', 'rw', 'randrw'])`
</blockquote></details>

The gpspm engine does not support reads nor any other modes making use of reads.

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1322)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi and @osalyk)

**Review by osalyk — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1322)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1322#-:-MohcyCz9uRyEtpCuz_7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1322#-:-MohgN8y3T22IRr7UoxK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1322)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
