### PR TITLE
tools: adjust existing figures to the new python framework

### PR DESCRIPTION
**Pull request by ldorau**
This PR will be merged to the new `devel-new-python` branch:
https://github.com/pmem/rpma/tree/devel-new-python

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1393)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 4 of 5 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1393)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/figures/read.json, line 87 at r2](https://reviewable.io/reviews/pmem/rpma/1393#-MqFIZU8ACq-PwDuZiyE:-MqFIZU8ACq-PwDuZiyF:b-bujh3o) ([raw file](https://github.com/pmem/rpma/blob/61a5e81eae97c9d9c24c671e14812ba2011d82ca/tools/perf/figures/read.json#L87)):*
> ```
> "rw": "read"
> ```
Do we need this?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1393)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/perf/figures/read.json, line 87 at r2](https://reviewable.io/reviews/pmem/rpma/1393#-MqFIZU8ACq-PwDuZiyE:-MqG8TA46KA6cu22FJnX:b-c72wq5) ([raw file](https://github.com/pmem/rpma/blob/61a5e81eae97c9d9c24c671e14812ba2011d82ca/tools/perf/figures/read.json#L87)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> "rw": "read"
> ```
Do we need this?
</blockquote></details>

Yes, of course:
`ValueError: the following key is missing in the figure: rw`
That is the design.

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1393#-:-MqGIbvN-5G8Qk8LhPBX:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1393)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/figures/read.json, line 87 at r2](https://reviewable.io/reviews/pmem/rpma/1393#-MqFIZU8ACq-PwDuZiyE:-MqIIdR1AqCseiP1aIVu:b4er0j2) ([raw file](https://github.com/pmem/rpma/blob/61a5e81eae97c9d9c24c671e14812ba2011d82ca/tools/perf/figures/read.json#L87)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, of course:
`ValueError: the following key is missing in the figure: rw`
That is the design.
</blockquote></details>

so in this case we should use tool: ib_bw instead of ib_read to avoid redundancy in names

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1393)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/perf/figures/read.json, line 87 at r2](https://reviewable.io/reviews/pmem/rpma/1393#-MqFIZU8ACq-PwDuZiyE:-MqIt_Zv-M_2MfaSwU3N:bx1u80r) ([raw file](https://github.com/pmem/rpma/blob/61a5e81eae97c9d9c24c671e14812ba2011d82ca/tools/perf/figures/read.json#L87)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

so in this case we should use tool: ib_bw instead of ib_read to avoid redundancy in names
</blockquote></details>

No, `ib_read` is common for LAT and BW modes, so we cannot use `ib_bw` instead.

It's just a coincidence that ib_read_* tools have 'read' in the name. `fio` does not, so we cannot parse name of a tool and we have to set it explicitly. It would be more complicated if set `'rw'` only in case of `fio` and in case of `ib_read_(lat/bw)` not.
So summarizing: the redundancy in names is better than higher level of complexity.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1393#-:-MqJFW1n2GJCvnaeW-H3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1393#-:-MqStZJh55Zv-dtgPRQN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1393)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Comment by ldorau** [comment]
The PR is ready to be merged, but I will merge it, when we cannot go further without it.

**Review by haichangsi — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1393#-:-MqZ9Vjf-ydwt6yjZ6tS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1393)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @grom72)

**Review by osalyk — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1393)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @grom72 and @osalyk)

**Pull request merged**
