### PR TITLE
common: 1.0.0-rc1 release

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1990)

### CODE REVIEW

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1990#-:-NA9Grn04wQliE4d4bPz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1990#-:-NA9HKARDvlBuJs8kevx:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1990)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1990#-:-NA9KDIz1_bhZSUIBRrX:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
