### PR TITLE
tools: perf: fix the benchmarking dump

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1362)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1362)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/Requirement.py, line 119 at r1](https://reviewable.io/reviews/pmem/rpma/1362#-MpflCCTBRKkA2nrBoLp:-MpflCCTBRKkA2nrBoLq:blkf6yj) ([raw file](https://github.com/pmem/rpma/blob/c63988ddb3c727f9f7768aefc0942f8761628495/tools/perf/lib/Requirement.py#L119)):*
> ```
> print(b)
> ```

So it is not written to a file now?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1362)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/lib/Requirement.py, line 119 at r1](https://reviewable.io/reviews/pmem/rpma/1362#-MpflCCTBRKkA2nrBoLp:-MpfmSxm8SEsTttMKc29:bomrf5l) ([raw file](https://github.com/pmem/rpma/blob/c63988ddb3c727f9f7768aefc0942f8761628495/tools/perf/lib/Requirement.py#L119)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> print(b)
> ```

So it is not written to a file now?
</blockquote></details>

It is just a dump e.g.:

```sh
$ ./report_bench --dump run ...
```

What you are probably thinking of is `cache()`.

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1362)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1362#-:-MpfqnfqEYyb3_AR-xdK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1362#-:-MpgVFk2CwjwPRHm9kuS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1362)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
