### PR TITLE
test: mt: introduce an example test

### PR DESCRIPTION
**Pull request by janekmi**
Requires:
- [x] ~~#999~~
- [x] #1003

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1000)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1000)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tests/multithreaded/example/example.c, line 87 at r1](https://reviewable.io/reviews/pmem/rpma/1000#-MYIp3I_8Mpj8qWjqMa9:-MYIp3I_8Mpj8qWjqMaA:b-41sg25) ([raw file](https://github.com/pmem/rpma/blob/3ce7f7d39cca57ff4bda3704f5d3fcee50d60958/tests/multithreaded/example/example.c#L87)):*
> ```
> MTT_THREAD_ERR
> ```
would it be better to convert this macro into an inline function?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1000)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tests/multithreaded/example/example.c, line 87 at r1](https://reviewable.io/reviews/pmem/rpma/1000#-MYIp3I_8Mpj8qWjqMa9:-MYJlOJZDNQPrz0Wq3Nx:bh9gjtd) ([raw file](https://github.com/pmem/rpma/blob/3ce7f7d39cca57ff4bda3704f5d3fcee50d60958/tests/multithreaded/example/example.c#L87)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> MTT_THREAD_ERR
> ```
would it be better to convert this macro into an inline function?
</blockquote></details>

Yes. It would be and it can be done.
In a different PR. :-)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1000)* status: 2 of 6 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tests/multithreaded/example/example.c, line 87 at r1](https://reviewable.io/reviews/pmem/rpma/1000#-MYIp3I_8Mpj8qWjqMa9:-MYJv324709trIl4JpLm:bbm7egw) ([raw file](https://github.com/pmem/rpma/blob/3ce7f7d39cca57ff4bda3704f5d3fcee50d60958/tests/multithreaded/example/example.c#L87)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Yes. It would be and it can be done.
In a different PR. :-)
</blockquote></details>

#1003

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 3 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1000)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1000)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1000)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

___
*[tests/multithreaded/example/example.c, line 87 at r1](https://reviewable.io/reviews/pmem/rpma/1000#-MYIp3I_8Mpj8qWjqMa9:-MYKJQVd10TOG87X3am5:bf73luw) ([raw file](https://github.com/pmem/rpma/blob/3ce7f7d39cca57ff4bda3704f5d3fcee50d60958/tests/multithreaded/example/example.c#L87)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

#1003 
</blockquote></details>

Or maybe it is not a good concept

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1000)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/example/example.c, line 58 at r2](https://reviewable.io/reviews/pmem/rpma/1000#-MYKacrZEPnPNX7K372J:-MYKacrZEPnPNX7K372K:bte8w0l) ([raw file](https://github.com/pmem/rpma/blob/1c30abc1cfba9fb976fae83efd9ff8c1a51eda82/tests/multithreaded/example/example.c#L58)):*
> ```
>  * ... ; here should go
>  * everything that is not thread-safe and/or should be prepared in a sequential
>  * manner
> ```

Everything that is not thread-safe and/or everything what should be prepared in a sequential manner should go here.
___
*[tests/multithreaded/example/example.c, line 78 at r2](https://reviewable.io/reviews/pmem/rpma/1000#-MYKc01p5j33pfia83t0:-MYKc01p5j33pfia83t1:b5i4l41) ([raw file](https://github.com/pmem/rpma/blob/1c30abc1cfba9fb976fae83efd9ff8c1a51eda82/tests/multithreaded/example/example.c#L78)):*
> ```
>  ... ; here should go
>  * everything that is thread-safe and makes preparation for the test execution
> ```

Everything that is thread-safe and everything what makes preparation for the test execution should go here.
___
*[tests/multithreaded/example/example.c, line 105 at r2](https://reviewable.io/reviews/pmem/rpma/1000#-MYKcpjw653xN3aqoDO2:-MYKcpjw653xN3aqoDO3:b-filrs6) ([raw file](https://github.com/pmem/rpma/blob/1c30abc1cfba9fb976fae83efd9ff8c1a51eda82/tests/multithreaded/example/example.c#L105)):*
> ```
>  ... ; here should go everything that
>  * can be cleaned up after the test in a thread-safe manner
> ```

Everything that can be cleaned up after the test in a thread-safe manner should go here.
___
*[tests/multithreaded/example/example.c, line 120 at r2](https://reviewable.io/reviews/pmem/rpma/1000#-MYKd2Z56gxEo0DlbKMl:-MYKd2Z56gxEo0DlbKMm:b4aooo8) ([raw file](https://github.com/pmem/rpma/blob/1c30abc1cfba9fb976fae83efd9ff8c1a51eda82/tests/multithreaded/example/example.c#L120)):*
> ```
>  ... ; here should go everything
>  * that has to be cleaned up after the test but is not thread-safe
> ```

Everything that has to be cleaned up after the test but is not thread-safe should go here.

**Review by ldorau — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1000#-:-MYKdbF41rpZLbxjvc2V:bdycpsm)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

**Review by ldorau — COMMENTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1000)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1000)* status: 5 of 6 files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[tests/multithreaded/example/example.c, line 58 at r2](https://reviewable.io/reviews/pmem/rpma/1000#-MYKacrZEPnPNX7K372J:-MYKlX160noOqv_3Yb3V:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1c30abc1cfba9fb976fae83efd9ff8c1a51eda82/tests/multithreaded/example/example.c#L58)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  * ... ; here should go
>  * everything that is not thread-safe and/or should be prepared in a sequential
>  * manner
> ```

Everything that is not thread-safe and/or everything what should be prepared in a sequential manner should go here.
</blockquote></details>

Done.
___
*[tests/multithreaded/example/example.c, line 78 at r2](https://reviewable.io/reviews/pmem/rpma/1000#-MYKc01p5j33pfia83t0:-MYKljEl9QpQ5VIBpKdY:b-t8iu7q) ([raw file](https://github.com/pmem/rpma/blob/1c30abc1cfba9fb976fae83efd9ff8c1a51eda82/tests/multithreaded/example/example.c#L78)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  ... ; here should go
>  * everything that is thread-safe and makes preparation for the test execution
> ```

Everything that is thread-safe and everything what makes preparation for the test execution should go here.
</blockquote></details>

The current statement imposes two requirements connected by AND making it a cross-section of both requirements.



Whereas reading your proposition I see a union of both requirements


___
*[tests/multithreaded/example/example.c, line 105 at r2](https://reviewable.io/reviews/pmem/rpma/1000#-MYKcpjw653xN3aqoDO2:-MYKoydLB-fSChmjYBCy:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1c30abc1cfba9fb976fae83efd9ff8c1a51eda82/tests/multithreaded/example/example.c#L105)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  ... ; here should go everything that
>  * can be cleaned up after the test in a thread-safe manner
> ```

Everything that can be cleaned up after the test in a thread-safe manner should go here.
</blockquote></details>

Done.
___
*[tests/multithreaded/example/example.c, line 120 at r2](https://reviewable.io/reviews/pmem/rpma/1000#-MYKd2Z56gxEo0DlbKMl:-MYKqS7L7P4mtYlB6HmT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1c30abc1cfba9fb976fae83efd9ff8c1a51eda82/tests/multithreaded/example/example.c#L120)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  ... ; here should go everything
>  * that has to be cleaned up after the test but is not thread-safe
> ```

Everything that has to be cleaned up after the test but is not thread-safe should go here.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1000#-:-MYOCXBOArA4FsyxwST2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

___
*[tests/multithreaded/example/example.c, line 78 at r2](https://reviewable.io/reviews/pmem/rpma/1000#-MYKc01p5j33pfia83t0:-MYOA0Tf5wiNKN-7QxOa:b-irszqq) ([raw file](https://github.com/pmem/rpma/blob/1c30abc1cfba9fb976fae83efd9ff8c1a51eda82/tests/multithreaded/example/example.c#L78)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The current statement imposes two requirements connected by AND making it a cross-section of both requirements.



Whereas reading your proposition I see a union of both requirements


</blockquote></details>

Why? 

1) Your version: (everything that is thread-safe) AND (makes preparation for the test execution)
2) My version: (Everything that is thread-safe) AND (**[everything what]** makes preparation for the test execution)

The only difference is that I have added "everything what" after "AND" in my version. Why do you think it changes the logic?

The current (new) version is OK for me.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1000)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

___
*[tests/multithreaded/example/example.c, line 78 at r2](https://reviewable.io/reviews/pmem/rpma/1000#-MYKc01p5j33pfia83t0:-MYOQxYC7emw9svq-Otq:b6vvohs) ([raw file](https://github.com/pmem/rpma/blob/1c30abc1cfba9fb976fae83efd9ff8c1a51eda82/tests/multithreaded/example/example.c#L78)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why? 

1) Your version: (everything that is thread-safe) AND (makes preparation for the test execution)
2) My version: (Everything that is thread-safe) AND (**[everything what]** makes preparation for the test execution)

The only difference is that I have added "everything what" after "AND" in my version. Why do you think it changes the logic?

The current (new) version is OK for me.
</blockquote></details>

Because of the additional pronoun of course. :-)
We can discuss this fascinating linguistic issue offline. Thanks.

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1000)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1000)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tests/multithreaded/common/mtt.h, line 65 at r4](https://reviewable.io/reviews/pmem/rpma/1000#-MYOT5RxAnnkDYzMnBLx:-MYOT5RxAnnkDYzMnBLy:b-qx995a) ([raw file](https://github.com/pmem/rpma/blob/bbe88d8c196c5b1591581610620568179a9ff493/tests/multithreaded/common/mtt.h#L65)):*
> ```
> mtt_thread_init_fini
> ```
mtt_thread_init_fini_tunc

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1000)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[tests/multithreaded/common/mtt.h, line 65 at r4](https://reviewable.io/reviews/pmem/rpma/1000#-MYOT5RxAnnkDYzMnBLx:-MYPnfZI7RR268Zk73C-:b-gp7n1j) ([raw file](https://github.com/pmem/rpma/blob/bbe88d8c196c5b1591581610620568179a9ff493/tests/multithreaded/common/mtt.h#L65)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> mtt_thread_init_fini
> ```
mtt_thread_init_fini_tunc
</blockquote></details>

It is kinda nice you are fixing issues you have pointed out. Thanks. :-)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1000)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:goat: - documentation of `typedef void (*mtt_thread_init_fini_func)(unsigned id, void *prestate,
		void **state_ptr, struct mtt_result *result);` is needed

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1000#-:-MYUK0Lt3AUAybfB3k_V:byra4an)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1000)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
#1012 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1000#-:-MYeaj190_SBCNJj7emd:bbm7f6q)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
