### PR TITLE
doc: improve the documentation to rpma_err... functions

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/432)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/432)* status: all files reviewed, 4 unresolved discussions (waiting on @osalyk)

___
*[src/include/librpma.h, line 1305 at r1](https://reviewable.io/reviews/pmem/rpma/432#-MHzyvzr-foK8aSfVKk3:-MHzyvzr-foK8aSfVKk4:bms0ldr) ([raw file](https://github.com/pmem/rpma/blob/5791bbb683ad98ec90978d8afbee1e4fb3f072cd/src/include/librpma.h#L1305)):*
> ```objc
>  *
>  * DESCRIPTION
>  * Returns the last provider error.
> ```

`rpma_err_get_provider_error() returns ...`
___
*[src/include/librpma.h, line 1308 at r1](https://reviewable.io/reviews/pmem/rpma/432#-MHzz2rs0lDzVbW7Hdqz:-MHzz2rs0lDzVbW7Hdr-:b-bw48ux) ([raw file](https://github.com/pmem/rpma/blob/5791bbb683ad98ec90978d8afbee1e4fb3f072cd/src/include/librpma.h#L1308)):*
> ```
> can not
> ```

cannot
___
*[src/include/librpma.h, line 1337 at r1](https://reviewable.io/reviews/pmem/rpma/432#-MHzz5W16WvZWTkBXStN:-MHzz5W16WvZWTkBXStO:b-bw48ux) ([raw file](https://github.com/pmem/rpma/blob/5791bbb683ad98ec90978d8afbee1e4fb3f072cd/src/include/librpma.h#L1337)):*
> ```
> can not
> ```

cannot
___
*[src/include/librpma.h, line 1355 at r1](https://reviewable.io/reviews/pmem/rpma/432#-MHzz93VAVNIrgPNVen0:-MHzz93VAVNIrgPNVen1:b-oepdr4) ([raw file](https://github.com/pmem/rpma/blob/5791bbb683ad98ec90978d8afbee1e4fb3f072cd/src/include/librpma.h#L1355)):*
> ```
> rpma_err_2str(i
> ```

`rpma_err_2str() returns ...`

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/432)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[src/include/librpma.h, line 1305 at r1](https://reviewable.io/reviews/pmem/rpma/432#-MHzyvzr-foK8aSfVKk3:-MI-LnAa9NsW187bxY3H:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5791bbb683ad98ec90978d8afbee1e4fb3f072cd/src/include/librpma.h#L1305)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`rpma_err_get_provider_error() returns ...`
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1308 at r1](https://reviewable.io/reviews/pmem/rpma/432#-MHzz2rs0lDzVbW7Hdqz:-MI-LprI53Kah6SwvbxU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5791bbb683ad98ec90978d8afbee1e4fb3f072cd/src/include/librpma.h#L1308)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> can not
> ```

cannot
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1337 at r1](https://reviewable.io/reviews/pmem/rpma/432#-MHzz5W16WvZWTkBXStN:-MI-Lshx2rxK0c7OphpS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5791bbb683ad98ec90978d8afbee1e4fb3f072cd/src/include/librpma.h#L1337)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> can not
> ```

cannot
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1355 at r1](https://reviewable.io/reviews/pmem/rpma/432#-MHzz93VAVNIrgPNVen0:-MI-LwlH7eGbBPGhhSxd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5791bbb683ad98ec90978d8afbee1e4fb3f072cd/src/include/librpma.h#L1355)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> rpma_err_2str(i
> ```

`rpma_err_2str() returns ...`
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/432)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[src/include/librpma.h, line 1355 at r1](https://reviewable.io/reviews/pmem/rpma/432#-MHzz93VAVNIrgPNVen0:-MI-Mc4x5Mc-XDRR32Ih:b-t4o2dq) ([raw file](https://github.com/pmem/rpma/blob/5791bbb683ad98ec90978d8afbee1e4fb3f072cd/src/include/librpma.h#L1355)):*
> ```
>  returns const
> ```

 returns THE const ...

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/432)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
Please rebase (to restart Travis build)

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/432#-:-MI35m_l2egM9vfUXnbb:bulq6h1)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
@grom72 please review

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/432#-:-MI388c43GcrvOhS_eNS:bgjoyzx)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/432#-:-MI3Xsle8AWyAVfpe4sQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/432)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[src/include/librpma.h, line 1399 at r4](https://reviewable.io/reviews/pmem/rpma/432#-MI4MMLYB9uQ8842BuwC:-MI4MMLYB9uQ8842BuwD:b-1npn80) ([raw file](https://github.com/pmem/rpma/blob/01a752e12feace122060ff0bcb5ebba7987499fb/src/include/librpma.h#L1399)):*
> ```
> error
> ```
error stored in errno varable

**Review by grom72 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/432#-:-MI4NIQr1vHatSfoOGq7:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/432)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/432)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[src/include/librpma.h, line 1399 at r4](https://reviewable.io/reviews/pmem/rpma/432#-MI4MMLYB9uQ8842BuwC:-MI4z-pbC06dHoV_CMFF:b-pvehj7) ([raw file](https://github.com/pmem/rpma/blob/01a752e12feace122060ff0bcb5ebba7987499fb/src/include/librpma.h#L1399)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> error
> ```
error stored in errno varable
</blockquote></details>

@grom72 Could you propose the whole sentence ?

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/432)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/include/librpma.h, line 1399 at r4](https://reviewable.io/reviews/pmem/rpma/432#-MI4MMLYB9uQ8842BuwC:-MI55PDj6jYu4-PNVv0Q:bsfmll2) ([raw file](https://github.com/pmem/rpma/blob/01a752e12feace122060ff0bcb5ebba7987499fb/src/include/librpma.h#L1399)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@grom72 Could you propose the whole sentence ?
</blockquote></details>

returns the last provider error given by *errno* variable

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/432)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[src/include/librpma.h, line 1399 at r4](https://reviewable.io/reviews/pmem/rpma/432#-MI4MMLYB9uQ8842BuwC:-MI55oWIDn5AkquxmsdD:b-qp4tir) ([raw file](https://github.com/pmem/rpma/blob/01a752e12feace122060ff0bcb5ebba7987499fb/src/include/librpma.h#L1399)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

returns the last provider error given by *errno* variable
</blockquote></details>

... by THE ...

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/432)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/432)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[src/include/librpma.h, line 1399 at r4](https://reviewable.io/reviews/pmem/rpma/432#-MI4MMLYB9uQ8842BuwC:-MI6IS5r8_Vikt-jA_D9:b4ew3wd) ([raw file](https://github.com/pmem/rpma/blob/01a752e12feace122060ff0bcb5ebba7987499fb/src/include/librpma.h#L1399)):*
Maybe even simpler:

> ... returns the last errno value reported by the provider.

?

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/432)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[src/include/librpma.h, line 1399 at r4](https://reviewable.io/reviews/pmem/rpma/432#-MI4MMLYB9uQ8842BuwC:-MIA8N652MuwBGbgIWoC:b-8fx2u7) ([raw file](https://github.com/pmem/rpma/blob/01a752e12feace122060ff0bcb5ebba7987499fb/src/include/librpma.h#L1399)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Maybe even simpler:

> ... returns the last errno value reported by the provider.

?
</blockquote></details>

:+1:

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/432)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/include/librpma.h, line 1399 at r4](https://reviewable.io/reviews/pmem/rpma/432#-MI4MMLYB9uQ8842BuwC:-MIB5QAj6GQnUX_33vuE:b-8fx2u7) ([raw file](https://github.com/pmem/rpma/blob/01a752e12feace122060ff0bcb5ebba7987499fb/src/include/librpma.h#L1399)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

:+1:

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/432)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[src/include/librpma.h, line 1399 at r4](https://reviewable.io/reviews/pmem/rpma/432#-MI4MMLYB9uQ8842BuwC:-MIDxIfvBZC6ox6GIOnv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/01a752e12feace122060ff0bcb5ebba7987499fb/src/include/librpma.h#L1399)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/432#-:-MIEZkA37mLMzp1U5cSq:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/432)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/432)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
