### PR TITLE
tools: perf: document lib.compare

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1384)

### CODE REVIEW

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1384)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1384)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @haichangsi and @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1384#-:-MpvF8537hW20qN3v196:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1384)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/lib/compare.py, line 167 at r1](https://reviewable.io/reviews/pmem/rpma/1384#-MpvFJJfCAvnzMI8VyvN:-MpvFJJfCAvnzMI8VyvO:b-3ycsnz) ([raw file](https://github.com/pmem/rpma/blob/09c914c5400b322df0ff72eb58571dcc6f369746/tools/perf/lib/compare.py#L167)):*
> ```
>         are browsed in order to fall all occurances of the figure.
> ```

1) fall ? maybe find ?
2) occurances - > occurances
___
*[tools/perf/lib/compare.py, line 168 at r1](https://reviewable.io/reviews/pmem/rpma/1384#-MpvFZaDB501nXSBY-qg:-MpvFZaDB501nXSBY-qh:b5i8hwc) ([raw file](https://github.com/pmem/rpma/blob/09c914c5400b322df0ff72eb58571dcc6f369746/tools/perf/lib/compare.py#L168)):*
> ```
>  occurances
> ```

occurances - > occurances
___
*[tools/perf/lib/compare.py, line 177 at r1](https://reviewable.io/reviews/pmem/rpma/1384#-MpvFn1O7yDBFqFnrr6Z:-MpvFn1O7yDBFqFnrr6_:bd7dhc9) ([raw file](https://github.com/pmem/rpma/blob/09c914c5400b322df0ff72eb58571dcc6f369746/tools/perf/lib/compare.py#L177)):*
> ```Python
>         - the figure exists in two `lib.bench.Bench` instances named: Alfa and
>           Beta.
>         - The resulting figure will be have the follwing series:
> ```

follwing -> following

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1384#-:-MpvLxos-lCwsDc4s3ye:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
