### PR TITLE
tools: set up DDIO remotely via rpma_fio_bench.sh

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/772)

### CODE REVIEW

**Comment by ldorau** [comment]
Required #774

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/772)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/772#-MRzFjW29bSIcp8V1Zhs:-MRzFjW29bSIcp8V1Zht:bywtbpq) (no related file):*
We have three variables that are interrelated:
- REMOTE_SUDO_NO_NOPASSWD
- REMOTE_RNIC_PCIE_ROOT_PORT
- REMOTE_DIRECT_WRITE_TO_PMEM

I think about something like:

```sh
if [ $REMOTE_SUDO_NO_NOPASSWD -eq 0]; then
    # REMOTE_DIRECT_WRITE_TO_PMEM has to be set
    # skip tests which requires other REMOTE_DIRECT_WRITE_TO_PMEM value
else
    # REMOTE_RNIC_PCIE_ROOT_PORT has to be set
    # fail if setting a required DDIO value failed
fi
```

---
___
*[tools/rpma_fio_bench.sh, line 104 at r1](https://reviewable.io/reviews/pmem/rpma/772#-MRysrq3CL0STsaylUlz:-MRysrq3CL0STsaylUm-:b-cdl5pw) ([raw file](https://github.com/pmem/rpma/blob/3cf12ab16b82db0915fe73091221c603f556ef82/tools/rpma_fio_bench.sh#L104)):*
> ```Shell
> if [ "$REMOTE_SUDO_NO_NOPASSWD" != "1" ]; then
>     echo "WARNING! sudo (called on the remote side) will prompt for password!"
> fi
> ```

So there is no way to proceed with turning on/off DDIO.
I think we should print the warning and skip toggling DDIO or just exit.
___
*[tools/rpma_fio_bench.sh, line 257 at r1](https://reviewable.io/reviews/pmem/rpma/772#-MRzFHWI0Sd55sasafdz:-MRzFHWI0Sd55sasafe-:bryfj) ([raw file](https://github.com/pmem/rpma/blob/3cf12ab16b82db0915fe73091221c603f556ef82/tools/rpma_fio_bench.sh#L257)):*
> ```Shell
> 			echo "Error: setting DDIO to '$DDIO_MODE' failed"
> 			exit 1
> 		fi
> ```

Successful change of DDIO status effectively changes the `REMOTE_DIRECT_WRITE_TO_PMEM` value.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/772)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/772#-MRzFjW29bSIcp8V1Zhs:-MS1Iuf0-BdRYxrpT9T8:b-igdsvw) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

We have three variables that are interrelated:
- REMOTE_SUDO_NO_NOPASSWD
- REMOTE_RNIC_PCIE_ROOT_PORT
- REMOTE_DIRECT_WRITE_TO_PMEM

I think about something like:

```sh
if [ $REMOTE_SUDO_NO_NOPASSWD -eq 0]; then
    # REMOTE_DIRECT_WRITE_TO_PMEM has to be set
    # skip tests which requires other REMOTE_DIRECT_WRITE_TO_PMEM value
else
    # REMOTE_RNIC_PCIE_ROOT_PORT has to be set
    # fail if setting a required DDIO value failed
fi
```
</blockquote></details>

Would it be still possible to use the script without DDIO feature?

---
___
*[tools/rpma_fio_bench.sh, line 104 at r1](https://reviewable.io/reviews/pmem/rpma/772#-MRysrq3CL0STsaylUlz:-MS1IX2k1-4WL-Mejb-g:b32v57) ([raw file](https://github.com/pmem/rpma/blob/3cf12ab16b82db0915fe73091221c603f556ef82/tools/rpma_fio_bench.sh#L104)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

So there is no way to proceed with turning on/off DDIO.
I think we should print the warning and skip toggling DDIO or just exit.
</blockquote></details>

+1

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/772)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/772#-MRzFjW29bSIcp8V1Zhs:-MS1gxjo5raAJxoBcLjv:b-bswvbx) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Would it be still possible to use the script without DDIO feature?
</blockquote></details>

@janekmi How do you want to "skip tests which require other REMOTE_DIRECT_WRITE_TO_PMEM value" ? Is there a possiblity to skip some of tests?

---

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/772)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/rpma_fio_bench.sh, line 133 at r1](https://reviewable.io/reviews/pmem/rpma/772#-MS22q1R79mzsxOm9XUF:-MS22q1R79mzsxOm9XUG:baad1te) ([raw file](https://github.com/pmem/rpma/blob/3cf12ab16b82db0915fe73091221c603f556ef82/tools/rpma_fio_bench.sh#L133)):*
> ```Shell
> 		REMOTE_JOB_DEST="filename=$REMOTE_JOB_MEM_PATH"
> 		;;
> 	esac
> ```

It is unfortunate `DDIO_QUERY` is completely reverse to `REMOTE_DIRECT_WRITE_TO_PMEM` value. Here you can prepare e.g. `REQUIRED_REMOTE_DIRECT_WRITE_TO_PMEM`...
___
*[tools/rpma_fio_bench.sh, line 257 at r1](https://reviewable.io/reviews/pmem/rpma/772#-MS23YEtDqzmn6lzLMs8:-MS23YEtDqzmn6lzLMs9:b-wfky4l) ([raw file](https://github.com/pmem/rpma/blob/3cf12ab16b82db0915fe73091221c603f556ef82/tools/rpma_fio_bench.sh#L257)):*
> ```Shell
> 			echo "Error: setting DDIO to '$DDIO_MODE' failed"
> 			exit 1
> 		fi
> ```

... Whereas here you can:

```sh
if [ $REMOTE_SUDO_NO_NOPASSWD -eq 0 ]; then
    # set remote DDIO state
    # update REMOTE_DIRECT_WRITE_TO_PMEM
fi

if [ $REMOTE_DIRECT_WRITE_TO_PMEM -ne $REQUIRED_REMOTE_DIRECT_WRITE_TO_PMEM]; then
    return # the requirement not met - skip
fi
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/772)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tools/rpma_fio_bench.sh, line 104 at r1](https://reviewable.io/reviews/pmem/rpma/772#-MRysrq3CL0STsaylUlz:-MS2QWW22QGmgFPZLf5P:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3cf12ab16b82db0915fe73091221c603f556ef82/tools/rpma_fio_bench.sh#L104)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[tools/rpma_fio_bench.sh, line 133 at r1](https://reviewable.io/reviews/pmem/rpma/772#-MS22q1R79mzsxOm9XUF:-MS2UAz1Czc7lwjiNu_D:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3cf12ab16b82db0915fe73091221c603f556ef82/tools/rpma_fio_bench.sh#L133)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is unfortunate `DDIO_QUERY` is completely reverse to `REMOTE_DIRECT_WRITE_TO_PMEM` value. Here you can prepare e.g. `REQUIRED_REMOTE_DIRECT_WRITE_TO_PMEM`...
</blockquote></details>

Done.
___
*[tools/rpma_fio_bench.sh, line 257 at r1](https://reviewable.io/reviews/pmem/rpma/772#-MRzFHWI0Sd55sasafdz:-MS2Y5ELBSk-L7fB27bh:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3cf12ab16b82db0915fe73091221c603f556ef82/tools/rpma_fio_bench.sh#L257)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Successful change of DDIO status effectively changes the `REMOTE_DIRECT_WRITE_TO_PMEM` value.
</blockquote></details>

Done.
___
*[tools/rpma_fio_bench.sh, line 257 at r1](https://reviewable.io/reviews/pmem/rpma/772#-MS23YEtDqzmn6lzLMs8:-MS2Y5ZI7UWcrSRplQPC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3cf12ab16b82db0915fe73091221c603f556ef82/tools/rpma_fio_bench.sh#L257)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

... Whereas here you can:

```sh
if [ $REMOTE_SUDO_NO_NOPASSWD -eq 0 ]; then
    # set remote DDIO state
    # update REMOTE_DIRECT_WRITE_TO_PMEM
fi

if [ $REMOTE_DIRECT_WRITE_TO_PMEM -ne $REQUIRED_REMOTE_DIRECT_WRITE_TO_PMEM]; then
    return # the requirement not met - skip
fi
```
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/772)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/rpma_fio_bench.sh, line 271 at r2](https://reviewable.io/reviews/pmem/rpma/772#-MS2Z2vn3gOaXK3pYEMH:-MS2Z2vo327PWwGDOmm-:byziv39) ([raw file](https://github.com/pmem/rpma/blob/cca948e0bfb12656f2bd5960015eadd9f31784d0/tools/rpma_fio_bench.sh#L271)):*
> ```Shell
> 		elif [ $REMOTE_DIRECT_WRITE_TO_PMEM -ne $REQUIRED_REMOTE_DIRECT_WRITE_TO_PMEM ]; then
> 			echo "Error: REMOTE_DIRECT_WRITE_TO_PMEM does not have the required value ($REQUIRED_REMOTE_DIRECT_WRITE_TO_PMEM)"
> 			exit 1
> ```

Why not just skip? `return`?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/772)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/rpma_fio_bench.sh, line 271 at r2](https://reviewable.io/reviews/pmem/rpma/772#-MS2Z2vn3gOaXK3pYEMH:-MS2Zc8KD6duAj5CDRre:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cca948e0bfb12656f2bd5960015eadd9f31784d0/tools/rpma_fio_bench.sh#L271)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Why not just skip? `return`?
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/772#-:-MS2ZsuJ5bdS2P5xdOoA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/772)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/rpma_fio_bench.sh, line 89 at r3](https://reviewable.io/reviews/pmem/rpma/772#-MS2bqD7BUNuUEavn-rH:-MS2bqD7BUNuUEavn-rI:bj9hzod) ([raw file](https://github.com/pmem/rpma/blob/41729f4688e87806649e82fa02c8da639c11f6bd/tools/rpma_fio_bench.sh#L89)):*
> ```
> elif [ -z "$REMOTE_RNIC_PCIE_ROOT_PORT" ]; then
> 	usage "REMOTE_RNIC_PCIE_ROOT_PORT not set"
> ```
Shall this be optional if we do not want to use a remote DDIO setup?
or general flag to enable/disable remote DDIO control?
Please remember that the fio itself monitors correctness of the remote DDIO?

**Comment by ldorau** [comment]
@grom72 Done

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/772)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/rpma_fio_bench.sh, line 89 at r3](https://reviewable.io/reviews/pmem/rpma/772#-MS2bqD7BUNuUEavn-rH:-MS2fQO53NnpAL1LzcE9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/41729f4688e87806649e82fa02c8da639c11f6bd/tools/rpma_fio_bench.sh#L89)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> elif [ -z "$REMOTE_RNIC_PCIE_ROOT_PORT" ]; then
> 	usage "REMOTE_RNIC_PCIE_ROOT_PORT not set"
> ```
Shall this be optional if we do not want to use a remote DDIO setup?
or general flag to enable/disable remote DDIO control?
Please remember that the fio itself monitors correctness of the remote DDIO?
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/772)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/772#-:-MS37kbQB0tjAZdH06wU:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/772)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/772)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Pull request merged**
