### PR TITLE
tools: fix fstring in _load_template

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1163)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1163)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/lib/Part.py, line 69 at r1](https://reviewable.io/reviews/pmem/rpma/1163#-MfbgmZa3jEq1JuQsNKK:-MfbgmZa3jEq1JuQsNKL:b2nhwlw) ([raw file](https://github.com/pmem/rpma/blob/e1145ec77d24a7f1d2dc0ac1fceeb22cb7fb0f0f/tools/perf/lib/Part.py#L69)):*
> ```Python
> 
>     def _load_template(self):
>         self.md_template = self.env.get_template("part_{}.md".format(self.name))
> ```

`'`

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1163)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/Part.py, line 69 at r1](https://reviewable.io/reviews/pmem/rpma/1163#-MfbgmZa3jEq1JuQsNKK:-MfbreTO2BkF_8J8q_Ia:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e1145ec77d24a7f1d2dc0ac1fceeb22cb7fb0f0f/tools/perf/lib/Part.py#L69)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`'`
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1163#-:-MfcJNXP4dvFjDnzjF3b:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1163#-:-MfgBh8u2asL0oXUEjy1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
