### PR TITLE
tools: busy-wait-poling added to mandatory keys

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1536)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1536)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1536#-:-MuzGLzlC8raRhBymcpc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1536)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 347 at r1](https://reviewable.io/reviews/pmem/rpma/1536#-MuzJzS48AEQHNQatfJJ:-MuzJzS48AEQHNQatfJK:b-r4yftk) ([raw file](https://github.com/pmem/rpma/blob/2ffe21e01301d0b2a7c8dff35dcd9b11d5456a3c/tools/perf/lib/benchmark/runner/fio.py#L347)):*
> ```Python
>         'rw': ['read', 'write', 'rw', 'randread', 'randwrite', 'randrw'],
>         'filetype': ['malloc', 'pmem'],
>         'busy_wait_polling': [True, False]
> ```

I have checked and it should not be required:
https://github.com/pmem/rpma/blob/master/tools/perf/lib/benchmark/runner/fio.py#L172

@osalyk Could you confirm ?



_Code quote:_
```Python
 'busy_wait_polling': [True, False]
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1536)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1536#-MuzOaAa6bKden2AZ8Ja:-MuzOaAa6bKden2AZ8Jb:b-quh9as) (no related file):*
This line has to be updated: 
https://github.com/pmem/rpma/blob/master/tools/perf/lib/benchmark/runner/fio.py#L172

It should be required, but only if `'tool_mode' == 'gpspm'`

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1536#-MuzOvVO4nL1qNPcbCVu:-MuzOvVO4nL1qNPcbCVv:bljql3d) (no related file):*
Figures have to be updated too: `busy_wait_polling` has to be set to True for the GPSPM mode.

---
___
*[tools/perf/lib/benchmark/runner/fio.py, line 347 at r1](https://reviewable.io/reviews/pmem/rpma/1536#-MuzJzS48AEQHNQatfJJ:-MuzNje7DB3iJCyTWFcj:b-rl3ci5) ([raw file](https://github.com/pmem/rpma/blob/2ffe21e01301d0b2a7c8dff35dcd9b11d5456a3c/tools/perf/lib/benchmark/runner/fio.py#L347)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I have checked and it should not be required:
https://github.com/pmem/rpma/blob/master/tools/perf/lib/benchmark/runner/fio.py#L172

@osalyk Could you confirm ?
</blockquote></details>

We have agreed with @osalyk that it should be required, but only for the `'tool_mode' == 'gpspm'` case, so it cannot be added here, but separately in `__init__`.

Additionally:
1) this line has to be updated: I have checked and it should not be required:
https://github.com/pmem/rpma/blob/master/tools/perf/lib/benchmark/runner/fio.py#L172
2) and figures have to be updated too: `busy_wait_polling` has to be set for the GPSPM mode.

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1536)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @haichangsi, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1536#-MuzOvVO4nL1qNPcbCVu:-Mv0d8iHExjtTZfnfZkV:b-yr19bf) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Figures have to be updated too: `busy_wait_polling` has to be set to True for the GPSPM mode.
</blockquote></details>

Should I just delete series with 'busy_wait_polling" == false?

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1536#-MuzOaAa6bKden2AZ8Ja:-Mv0dQI75iaBgjdNkrCM:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

This line has to be updated: 
https://github.com/pmem/rpma/blob/master/tools/perf/lib/benchmark/runner/fio.py#L172

It should be required, but only if `'tool_mode' == 'gpspm'`

</blockquote></details>

Done.

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1536)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1536#-MuzOvVO4nL1qNPcbCVu:-Mv2m6VT0p6JlAKDHvqF:bjwozv1) (no related file):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Should I just delete series with 'busy_wait_polling" == false?
</blockquote></details>

No, I was not too precise ;-) , excuse me. 
Every benchmark of GPSPM mode has to have `busy_wait_polling` set now, because it became required from now on.
So first, you have to verify if all figures of GPSPM benchmarks have `busy_wait_polling` set:
1) If it is set, do not change its value.
2) If it is not, set it to True.

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1536#-MuzOaAa6bKden2AZ8Ja:-Mv2nVS430gZW580SHzN:b19fk4a) (no related file):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

get() with the default value is not needed any more

---
___
*[tools/perf/lib/benchmark/runner/fio.py, line 175 at r2](https://reviewable.io/reviews/pmem/rpma/1536#-Mv2nB5F7k8HsyrnrK_M:-Mv2nB5G8dphsfsjQtQi:b-hmyjk4) ([raw file](https://github.com/pmem/rpma/blob/6f02318375892246429773041a251a9b4d127fd3/tools/perf/lib/benchmark/runner/fio.py#L175)):*
> ```Python
>             raise ValueError(MISSING_KEY_MSG.format('busy_wait_polling'))
>         busy_wait_polling = \
>             int(self.__benchmark.oneseries.get('busy_wait_polling', True))
> ```

Please update it - get with the default value is not needed any more



_Code quote:_
```Python
int(self.__benchmark.oneseries.get('busy_wait_polling', True))
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1536)* status: all files reviewed, 4 unresolved discussions (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1536#-Mv2w2v3AoyKv0-8gFzI:-Mv2w2v3AoyKv0-8gFzJ:b-ptsk9x) (no related file):*
CI builds failed
(please run `pytest` locally before pushing out)

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1536)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1536#-MuzOaAa6bKden2AZ8Ja:-Mv32h4-8CeLzb7Eqcrf:bhsixg0) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

get() with the default value is not needed any more
</blockquote></details>

That is OK, leave it as is.

---
___
*[tools/perf/lib/benchmark/runner/fio.py, line 175 at r2](https://reviewable.io/reviews/pmem/rpma/1536#-Mv2nB5F7k8HsyrnrK_M:-Mv32Xem9md0qgyyH6-z:bhsixg0) ([raw file](https://github.com/pmem/rpma/blob/6f02318375892246429773041a251a9b4d127fd3/tools/perf/lib/benchmark/runner/fio.py#L175)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please update it - get with the default value is not needed any more
</blockquote></details>

That is OK, leave it as is.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1536)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 173 at r2](https://reviewable.io/reviews/pmem/rpma/1536#-Mv34Vo62Bg9Cdo-6emy:-Mv34Vo62Bg9Cdo-6emz:ba1wrc9) ([raw file](https://github.com/pmem/rpma/blob/6f02318375892246429773041a251a9b4d127fd3/tools/perf/lib/benchmark/runner/fio.py#L173)):*
> ```Python
>         if (self.__tool_mode == 'gpspm' and
>                 'busy_wait_polling' not in self.__benchmark.oneseries):
>             raise ValueError(MISSING_KEY_MSG.format('busy_wait_polling'))
> ```

Move it to the beginning of `__validate`, please.



_Code quote:_
```Python
        if (self.__tool_mode == 'gpspm' and
                'busy_wait_polling' not in self.__benchmark.oneseries):
            raise ValueError(MISSING_KEY_MSG.format('busy_wait_polling'))
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1536)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1536#-MuzOvVO4nL1qNPcbCVu:-Mv3jRfNEULa7NptTS2H:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No, I was not too precise ;-) , excuse me. 
Every benchmark of GPSPM mode has to have `busy_wait_polling` set now, because it became required from now on.
So first, you have to verify if all figures of GPSPM benchmarks have `busy_wait_polling` set:
1) If it is set, do not change its value.
2) If it is not, set it to True.
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1536#-Mv2w2v3AoyKv0-8gFzI:-Mv3jSV_0IhiovkWBDtn:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

CI builds failed
(please run `pytest` locally before pushing out)
</blockquote></details>

Done.

---
___
*[tools/perf/lib/benchmark/runner/fio.py, line 173 at r2](https://reviewable.io/reviews/pmem/rpma/1536#-Mv34Vo62Bg9Cdo-6emy:-Mv3jT37EwcLYk6TSMnN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6f02318375892246429773041a251a9b4d127fd3/tools/perf/lib/benchmark/runner/fio.py#L173)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Move it to the beginning of `__validate`, please.
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1536)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[-- commits, line 2 at r3](https://reviewable.io/reviews/pmem/rpma/1536#-Mv3qZz69QVI-u-j9GQk):*
the GPSPM mode



_Code quote:_
```
the gpspm tool mode
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1536)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ldorau)

___
*[-- commits, line 2 at r3](https://reviewable.io/reviews/pmem/rpma/1536#-Mv3qZz69QVI-u-j9GQk):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

the GPSPM mode
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1536)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1536#-:-Mv43WsH17Eqzazy2nSz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
