### PR TITLE
tools: add filename_format to templates

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1589)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1589)* status: 1 of 4 files reviewed, 2 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[tools/perf/templates/part_cpuload.json, line 45 at r1](https://reviewable.io/reviews/pmem/rpma/1589#-MwB_ro4BTQfIctv5exZ:-MwB_ro4BTQfIctv5ex_:bf57be8) ([raw file](https://github.com/pmem/rpma/blob/09c1ef52d06f2b317d0023917839c45d6093f297/tools/perf/templates/part_cpuload.json#L45)):*
> ```JSON
>                 "numjobs=1",
>                 "size=100MiB",
>                 "filename=/dev/dax/path # for Device Dax",
> ```

`/dev/daxX.Y` in all places



_Code quote:_
```JSON
/dev/dax/path
```
___
*[tools/perf/templates/part_cpuload.json, line 46 at r1](https://reviewable.io/reviews/pmem/rpma/1589#-MwBa9sw5kI30tJyQQev:-MwBa9sw5kI30tJyQQew:bnfmraf) ([raw file](https://github.com/pmem/rpma/blob/09c1ef52d06f2b317d0023917839c45d6093f297/tools/perf/templates/part_cpuload.json#L46)):*
> ```JSON
>                 "size=100MiB",
>                 "filename=/dev/dax/path # for Device Dax",
>                 "filename_format=/mnt/pmem/file # for Filesystem DAX",
> ```

`# for File System DAX` in all places



_Code quote:_
```JSON
# for Filesystem DAX
```

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1589)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1589#-MwBa9Se1Wq8sserZyAF:-MwBa9Se1Wq8sserZyAG:byh41ye) (no related file):*
Shall we mention this in CHANGELOG.md?

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1589)* status: all files reviewed, 6 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/templates/part_read.json, line 16 at r1](https://reviewable.io/reviews/pmem/rpma/1589#-MwBafDBBSjo-GVyeJvh:-MwBafDBBSjo-GVyeJvi:b-ftpl0a) ([raw file](https://github.com/pmem/rpma/blob/09c1ef52d06f2b317d0023917839c45d6093f297/tools/perf/templates/part_read.json#L16)):*
> ```JSON
>             "numjobs=1",
>             "size=100MiB",
>             "filename={malloc, /dev/dax/path} # for DRAM & Device DAX",
> ```

`for DRAM or Device DAX`



_Code quote:_
```JSON
for DRAM & Device DAX
```
___
*[tools/perf/templates/part_write.json, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1589#-MwBaj0m2j0-FKsC0LaR:-MwBaj0m2j0-FKsC0LaS:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/09c1ef52d06f2b317d0023917839c45d6093f297/tools/perf/templates/part_write.json#L39)):*
> ```JSON
>                 "numjobs=1",
>                 "size=100MiB",
>                 "filename={malloc, /dev/dax/path} # for DRAM & Device DAX",
> ```

.



_Code quote:_
```JSON
for DRAM & Device DAX
```
___
*[tools/perf/templates/part_write.json, line 89 at r1](https://reviewable.io/reviews/pmem/rpma/1589#-MwBal6z8ai9XKvwUN02:-MwBal6z8ai9XKvwUN03:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/09c1ef52d06f2b317d0023917839c45d6093f297/tools/perf/templates/part_write.json#L89)):*
> ```JSON
>                 "numjobs=$numjobs",
>                 "size=100MiB",
>                 "filename={{malloc, /dev/dax/path}} # for DRAM & Device DAX",
> ```

.



_Code quote:_
```JSON
for DRAM & Device DAX"
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1589)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1589#-MwBa9Se1Wq8sserZyAF:-MwBbn_2-kls3SdgSJaO:b2nign6) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Shall we mention this in CHANGELOG.md?
</blockquote></details>

yes

---

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1589)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/templates/part_cpuload.json, line 45 at r1](https://reviewable.io/reviews/pmem/rpma/1589#-MwB_ro4BTQfIctv5exZ:-MwBb8CB9Yf5wjowZWR5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/09c1ef52d06f2b317d0023917839c45d6093f297/tools/perf/templates/part_cpuload.json#L45)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`/dev/daxX.Y` in all places
</blockquote></details>

Done.
___
*[tools/perf/templates/part_cpuload.json, line 46 at r1](https://reviewable.io/reviews/pmem/rpma/1589#-MwBa9sw5kI30tJyQQev:-MwBbOOuECaT3PmFIGuA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/09c1ef52d06f2b317d0023917839c45d6093f297/tools/perf/templates/part_cpuload.json#L46)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`# for File System DAX` in all places
</blockquote></details>

Done.
___
*[tools/perf/templates/part_read.json, line 16 at r1](https://reviewable.io/reviews/pmem/rpma/1589#-MwBafDBBSjo-GVyeJvh:-MwBbeoyAw3xTcwQj9ii:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/09c1ef52d06f2b317d0023917839c45d6093f297/tools/perf/templates/part_read.json#L16)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`for DRAM or Device DAX`
</blockquote></details>

Done.
___
*[tools/perf/templates/part_write.json, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1589#-MwBaj0m2j0-FKsC0LaR:-MwBbfx99tl0s3NwLDDL:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/09c1ef52d06f2b317d0023917839c45d6093f297/tools/perf/templates/part_write.json#L39)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/templates/part_write.json, line 89 at r1](https://reviewable.io/reviews/pmem/rpma/1589#-MwBal6z8ai9XKvwUN02:-MwBbgWD5_Fu0Kca6v9D:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/09c1ef52d06f2b317d0023917839c45d6093f297/tools/perf/templates/part_write.json#L89)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1589)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1589)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1589#-MwBa9Se1Wq8sserZyAF:-MwBgH6o7lEvauXG3su5:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

yes
</blockquote></details>

Done.

---

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1589)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[CHANGELOG.md, line 14 at r3](https://reviewable.io/reviews/pmem/rpma/1589#-MwBh9bf8P8vVzIfWNON:-MwBhwHrDppHEQ1exTo3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1889e108eafeecab36ad5ed02fc7e411f7d3dc66/CHANGELOG.md#L14)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It was NOT released in 0.12.0-rc1 ...

```
## [Unreleased]
### Fixed
- templates with fio configuration in the benchmarking framework

## [0.12.0-rc1] - 2022-02-14
### Removed
```
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1589)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1589)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1589#-MwBkNsO15VZ3cu4Q4QQ:-MwBkNsO15VZ3cu4Q4QR:b-ldau24) (no related file):*
Please squash commits into one.

---

**Review by ldorau — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1589)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1589#-:-MwBmynp2qeRckfFC5TH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
