### PR TITLE
tools: copy the provided report.json to the result_dir

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1237)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1237)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/lib/Report.py, line 60 at r1](https://reviewable.io/reviews/pmem/rpma/1237#-MiR-OnJCWKCIhyX0I2D:-MiR-OnJCWKCIhyX0I2E:b-ezl9bz) ([raw file](https://github.com/pmem/rpma/blob/df29668a79869d1c22ada5aadffabae8807592b4/tools/perf/lib/Report.py#L60)):*
> ```Python
>         self.variables['configuration']['schematic'] = os.path.basename(self.variables['configuration']['schematic'])
>         # copy report.json file
>         shutil.copy(input_file, self.result_dir)
> ```

I think it fits better after this line:
https://github.com/pmem/rpma/blob/master/tools/perf/report_create.py#L38

With a nice comment like: `copying report.json file to the result dir for future reference`

**Review by janekmi — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1237)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1237)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/Report.py, line 60 at r1](https://reviewable.io/reviews/pmem/rpma/1237#-MiR-OnJCWKCIhyX0I2D:-MiR5A_ME5FOBrh9jfXu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/df29668a79869d1c22ada5aadffabae8807592b4/tools/perf/lib/Report.py#L60)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think it fits better after this line:
https://github.com/pmem/rpma/blob/master/tools/perf/report_create.py#L38

With a nice comment like: `copying report.json file to the result dir for future reference`
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1237#-:-MiRXxEY0GgE0sa2llfT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1237#-:-MiRaTh8ENrDP3eA-TOU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
