### PR TITLE
examples: use libpmem2 or libpmem in example 03

### PR DESCRIPTION
**Pull request by Patryk717**
First part add libpmem2 to examples_03

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1314)

### CODE REVIEW

**Review by grom72 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1314)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi, @ldorau, and @Patryk717)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1314)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi, @ldorau, and @Patryk717)

___
*[-- commits, line 2 at r6](https://reviewable.io/reviews/pmem/rpma/1314#-Mw_kkIh5nLTqvEi87G9):*
examples: replace libpmem with libpmem2 in example 03



_Code quote:_
```
examples: add libpmem2 to examples_03
```

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1314)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi, @ldorau, and @Patryk717)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1314)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @Patryk717)

___
*[examples/03-read-to-persistent/client.c, line 71 at r3](https://reviewable.io/reviews/pmem/rpma/1314#-Mn0sQIn-v_O8HUzYeO7:-MwzUOgN-jHcLiQQCO-j:boh00xc) ([raw file](https://github.com/pmem/rpma/blob/cb21ace5909d52613177890874c73446252a9646/examples/03-read-to-persistent/client.c#L71)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Builds are failing because of this now
</blockquote></details>

(waiting for the fix)
___
*[examples/03-read-to-persistent/client.c, line 71 at r5](https://reviewable.io/reviews/pmem/rpma/1314#-Mn5TS8tD9OYD5IYctV7:-MwzURlfD-P6WTbcX9nE:boh00xc) ([raw file](https://github.com/pmem/rpma/blob/281fc86089fe5554fa2d218ee6f62a50b37bccdb/examples/03-read-to-persistent/client.c#L71)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

yes i looked, w8 i fix it
</blockquote></details>

(waiting for the fix)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1314)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi and @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1314#-Mx4NVayDsAsUBqpeA7i:-Mx4NVayDsAsUBqpeA7j:b-ujmq67) (no related file):*
Rebase please

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1314)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi and @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1314#-Mx4dlcT6DR_Mxro8hu3:-Mx4dlcU6cePVCLN6vPT:b-akn0xm) (no related file):*
@patryk717  please change this PR so that fio could use libpmem if libpmem2 is not available in OS.

---

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1314)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi and @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1314#-Mx4dlcT6DR_Mxro8hu3:-Mx4n2EO0z4wZ43V_4c-:b6k3jb6) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@patryk717  please change this PR so that fio could use libpmem if libpmem2 is not available in OS.
</blockquote></details>

fio or example 03?

---
___
*[examples/03-read-to-persistent/client.c, line 131 at r6](https://reviewable.io/reviews/pmem/rpma/1314#-MnAF8tyE95THooZCg1Y:-Mx4n7Av53S_LrJVJKXc:bb71lgq) ([raw file](https://github.com/pmem/rpma/blob/553b9d6449f0beac668e38563c00f95c12382a8a/examples/03-read-to-persistent/client.c#L131)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, I agree. It should be `PMEM` or `PMem` here.
</blockquote></details>

PMem

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1314)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi, @Patryk717, and @Pzbierski)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1314#-Mx4dlcT6DR_Mxro8hu3:-Mx4oliC2nnSiOrQh83q:b-7r0aq0) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

fio or example 03?
</blockquote></details>

@pzbierski @patryk717 "example 03" of course :-D

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1314)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi, @Patryk717, and @Pzbierski)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1314)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi, @Patryk717, and @Pzbierski)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1314)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi, @Patryk717, and @Pzbierski)

**Review by Patryk717 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1314)* status: 0 of 121 files reviewed, 6 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, @Patryk717, and @Pzbierski)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1314#-Mx4NVayDsAsUBqpeA7i:-MxIqkJw2_46A03y_PTo:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Rebase please
</blockquote></details>

Done.

---
___
*[-- commits, line 2 at r6](https://reviewable.io/reviews/pmem/rpma/1314#-Mw_kkIh5nLTqvEi87G9):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

examples: replace libpmem with libpmem2 in example 03
</blockquote></details>

Done.
___
*[examples/03-read-to-persistent/client.c, line 71 at r3](https://reviewable.io/reviews/pmem/rpma/1314#-Mn0sQIn-v_O8HUzYeO7:-MxJ0VUmCJAj9A6Nq8MZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cb21ace5909d52613177890874c73446252a9646/examples/03-read-to-persistent/client.c#L71)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

(waiting for the fix)
</blockquote></details>

Done.
___
*[examples/03-read-to-persistent/client.c, line 131 at r6](https://reviewable.io/reviews/pmem/rpma/1314#-MnAF8tyE95THooZCg1Y:-MxJ-U95EsK2_2gw4mpr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/553b9d6449f0beac668e38563c00f95c12382a8a/examples/03-read-to-persistent/client.c#L131)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

PMem
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 118 of 121 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1314)* status: 118 of 121 files reviewed, 6 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, @Patryk717, and @Pzbierski)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1314)* status: 118 of 121 files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, @Patryk717, and @Pzbierski)

___
*[-- commits, line 2 at r12](https://reviewable.io/reviews/pmem/rpma/1314#-MxJhTG-7eLfWofUlAw4):*
to 03 example



_Code quote:_
```
to examples_03
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1314)* status: 119 of 121 files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @Patryk717)

___
*[examples/03-read-to-persistent/CMakeLists.txt, line 60 at r13](https://reviewable.io/reviews/pmem/rpma/1314#-MxJle0qAmriwNlkcj6E:-MxJle0qAmriwNlkcj6F:be77zlk) ([raw file](https://github.com/pmem/rpma/blob/51272e673e144554ee063e1295a1aa6725606ccd/examples/03-read-to-persistent/CMakeLists.txt#L60)):*
> ```CMake
> 			PRIVATE USE_LIBPMEM)
> 	endif()
> 	endif()
> ```

Only one `endif` is needed here I think ;-)



_Code quote:_
```CMake
	endif()
	endif()
```

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1314)* status: 119 of 121 files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @Patryk717)

**Review by Patryk717 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1314)* status: 118 of 121 files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @Patryk717)

___
*[examples/03-read-to-persistent/CMakeLists.txt, line 60 at r13](https://reviewable.io/reviews/pmem/rpma/1314#-MxJle0qAmriwNlkcj6E:-MxJr_w3Ef52x8_Q_iPV:b-5g9o7c) ([raw file](https://github.com/pmem/rpma/blob/51272e673e144554ee063e1295a1aa6725606ccd/examples/03-read-to-persistent/CMakeLists.txt#L60)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Only one `endif` is needed here I think ;-)
</blockquote></details>

yes, done

**Review by Patryk717 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1314)* status: 118 of 121 files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[-- commits, line 2 at r12](https://reviewable.io/reviews/pmem/rpma/1314#-MxJhTG-7eLfWofUlAw4):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

to 03 example
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 3 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1314)* status: 119 of 121 files reviewed, 1 unresolved discussion (waiting on @grom72, @janekmi, and @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1314)* status: 119 of 121 files reviewed, 2 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1314#-MxKRYL68yzYiPEHFLZD:-MxKRYL73kPZgD1AU4Of:b-1qw6m8) (no related file):*
`EXAMPLE_USE_LIBPMEM2_IF_FOUND` should be replaced with `EXAMPLE_USE_LIBPMEM_IF_FOUND` in 
https://github.com/Patryk717/rpma/blob/libpmem2_to_examples_03/examples/CMakeLists.txt#L80

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1314)* status: 119 of 121 files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1314#-MxKSDau8d0MTB-BsEoM:-MxKSDau8d0MTB-BsEoN:b-uc3r8q) (no related file):*
The `USE_LIBPMEM2` part of code does not build:
https://github.com/ldorau/rpma/runs/5424010674?check_suite_focus=true

---

**Review by ldorau — CHANGES_REQUESTED** [review]
The current CI builds were built with `libpmem(1)`.

The `USE_LIBPMEM2` part of code (using `libpmem2`) does not build:
https://github.com/ldorau/rpma/runs/5424010674?check_suite_focus=true

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1314#-:-MxKWNkw-rCwLWL2n_2Z:b6d842r)* status: 119 of 121 files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @Patryk717)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1314#-MxKSDau8d0MTB-BsEoM:-MxKWhyXBJ4tBBxHDkKj:b3e6gs7) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The `USE_LIBPMEM2` part of code does not build:
https://github.com/ldorau/rpma/runs/5424010674?check_suite_focus=true
</blockquote></details>

The current CI builds were built with libpmem(1).

The `USE_LIBPMEM2` part of code (using `libpmem2`) does not build:
https://github.com/ldorau/rpma/runs/5424010674?check_suite_focus=true

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1314)* status: 119 of 121 files reviewed, 4 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @Patryk717)

___
*[-- commits, line 2 at r15](https://reviewable.io/reviews/pmem/rpma/1314#-MxKXx7S0j-G7Z5lm9Ty):*
"`examples: use libpmem2 or libpmem in example 03`" is better.



_Code quote:_
```
examples: add libpmem2 to 03 example
```

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 3 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1314)* status: 120 of 122 files reviewed, 2 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @Patryk717)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 3 files at r16.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1314)* status: 121 of 122 files reviewed, 8 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @Patryk717)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 3 files at r16.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1314)* status: all files reviewed, 8 unresolved discussions (waiting on @janekmi and @Patryk717)

**Review by osalyk — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1314)* status: all files reviewed, 14 unresolved discussions (waiting on @janekmi and @Patryk717)

___
*[examples/03-read-to-persistent/client.c, line 91 at r16](https://reviewable.io/reviews/pmem/rpma/1314#-Mxi-y4pCylKZwVUyHZh:-Mxi-y4q1VxFVxdyAq4Q:b8f9s22) ([raw file](https://github.com/pmem/rpma/blob/6f826a03300f36734fb2f87392c9d7cd1b2c5859/examples/03-read-to-persistent/client.c#L91)):*
> ```C
> 		}
> 
> 		if (pmem2_config_new(&cfg) != 0) {
> ```

ret = pmem2_config_new(&cfg)
if (ret) {
    ...
}
___
*[examples/03-read-to-persistent/client.c, line 96 at r16](https://reviewable.io/reviews/pmem/rpma/1314#-Mxi0IQV5r9VQSjyC8Ad:-Mxi0IQV5r9VQSjyC8Ae:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/6f826a03300f36734fb2f87392c9d7cd1b2c5859/examples/03-read-to-persistent/client.c#L96)):*
> ```C
> 		}
> 
> 		if (pmem2_source_from_fd(&src, fd) != 0) {
> ```

.
___
*[examples/03-read-to-persistent/client.c, line 101 at r16](https://reviewable.io/reviews/pmem/rpma/1314#-Mxi15rNE8YLlcIZbIgH:-Mxi15rNE8YLlcIZbIgI:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/6f826a03300f36734fb2f87392c9d7cd1b2c5859/examples/03-read-to-persistent/client.c#L101)):*
> ```C
> 		}
> 
> 		if (pmem2_config_set_required_store_granularity(cfg,
> ```

.
___
*[examples/03-read-to-persistent/server.c, line 76 at r16](https://reviewable.io/reviews/pmem/rpma/1314#-Mxi1sK_0rKzb5_3hhce:-Mxi1sK_0rKzb5_3hhcf:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/6f826a03300f36734fb2f87392c9d7cd1b2c5859/examples/03-read-to-persistent/server.c#L76)):*
> ```C
> 		}
> 
> 		if (pmem2_config_new(&cfg) != 0) {
> ```

.
___
*[examples/03-read-to-persistent/server.c, line 81 at r16](https://reviewable.io/reviews/pmem/rpma/1314#-Mxi1uhR136oej0n9dz7:-Mxi1uhR136oej0n9dz8:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/6f826a03300f36734fb2f87392c9d7cd1b2c5859/examples/03-read-to-persistent/server.c#L81)):*
> ```C
> 		}
> 
> 		if (pmem2_source_from_fd(&src, fd) != 0) {
> ```

.
___
*[examples/03-read-to-persistent/server.c, line 86 at r16](https://reviewable.io/reviews/pmem/rpma/1314#-Mxi1vIN9MrVBTrT5Sz4:-Mxi1vIN9MrVBTrT5Sz5:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/6f826a03300f36734fb2f87392c9d7cd1b2c5859/examples/03-read-to-persistent/server.c#L86)):*
> ```C
> 		}
> 
> 		if (pmem2_config_set_required_store_granularity(cfg,
> ```

.

**Review by osalyk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1314)* status: all files reviewed, 15 unresolved discussions (waiting on @janekmi and @Patryk717)

___
*[examples/03-read-to-persistent/server.c, line 367 at r16](https://reviewable.io/reviews/pmem/rpma/1314#-MxiKm821V6xPsg7lOGN:-MxiKm821V6xPsg7lOGO:b-883oy1) ([raw file](https://github.com/pmem/rpma/blob/6f826a03300f36734fb2f87392c9d7cd1b2c5859/examples/03-read-to-persistent/server.c#L367)):*
> ```C
> 
> #ifdef USE_LIBPMEM2
> err_source_delete:
> ```

The resource release sequence is incorrect. (server and client)

**Pull request closed without merging**
