### PR TITLE
tools: perf: split lib.figure.base.Figure

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1367)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1367)* status: 0 of 15 files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1367)* status: 0 of 16 files reviewed, all discussions resolved (waiting on @grom72 and @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 7 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1367)* status: 8 of 16 files reviewed, all discussions resolved (waiting on @grom72 and @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 15 files at r1, 2 of 3 files at r2, 1 of 8 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1367)* status: 12 of 16 files reviewed, all discussions resolved (waiting on @grom72 and @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 4 of 15 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1367)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/lib/figure/html.py, line 11 at r3](https://reviewable.io/reviews/pmem/rpma/1367#-MpkqDFT6IZj1IgVxidi:-MpkqDFU7r8wzWDk3NcB:bcfjzv1) ([raw file](https://github.com/pmem/rpma/blob/896972a673a67686cead59d5a3934892a9bfebfb/tools/perf/lib/figure/html.py#L11)):*
> ```
> "XXX
> ```
___
*[tools/perf/lib/figure/image.py, line 11 at r3](https://reviewable.io/reviews/pmem/rpma/1367#-MpkqOsd54LnEKUWMwfQ:-MpkqOsd54LnEKUWMwfR:b-snvz2n) ([raw file](https://github.com/pmem/rpma/blob/896972a673a67686cead59d5a3934892a9bfebfb/tools/perf/lib/figure/image.py#L11)):*
> ```
> XXX
> ```
___
*[tools/perf/lib/figure/image.py, line 25 at r3](https://reviewable.io/reviews/pmem/rpma/1367#-MpkqVZv0H0jQz0oirbI:-MpkqVZv0H0jQz0oirbJ:b2n3480) ([raw file](https://github.com/pmem/rpma/blob/896972a673a67686cead59d5a3934892a9bfebfb/tools/perf/lib/figure/image.py#L25)):*
> ```
> def __points_to_xy(points):
>     xslist = [p[0] for p in points]
> ```

doc-string is missing

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1367)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/lib/figure/html.py, line 11 at r3](https://reviewable.io/reviews/pmem/rpma/1367#-MpkqDFT6IZj1IgVxidi:-MpktdHI56ixAmDQwBbt:b-8sgh52) ([raw file](https://github.com/pmem/rpma/blob/896972a673a67686cead59d5a3934892a9bfebfb/tools/perf/lib/figure/html.py#L11)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> "XXX
> ```

</blockquote></details>

#1371
___
*[tools/perf/lib/figure/image.py, line 11 at r3](https://reviewable.io/reviews/pmem/rpma/1367#-MpkqOsd54LnEKUWMwfQ:-Mpktjnr7fN_dSVqcdIx:b-8sgh52) ([raw file](https://github.com/pmem/rpma/blob/896972a673a67686cead59d5a3934892a9bfebfb/tools/perf/lib/figure/image.py#L11)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> XXX
> ```

</blockquote></details>

#1371
___
*[tools/perf/lib/figure/image.py, line 25 at r3](https://reviewable.io/reviews/pmem/rpma/1367#-MpkqVZv0H0jQz0oirbI:-MpktJFkAVDB46bx2ski:b-wirtwy) ([raw file](https://github.com/pmem/rpma/blob/896972a673a67686cead59d5a3934892a9bfebfb/tools/perf/lib/figure/image.py#L25)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> def __points_to_xy(points):
>     xslist = [p[0] for p in points]
> ```

doc-string is missing
</blockquote></details>

docstring is not required for nonpublic functions. TBH I even delete some docstrings because they seem to convey no additional meaning.

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1367)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1367#-:-Mpkwtfn27nim5PGk7H_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1367#-:-Mpl1EVi-Uj4YjjdLTCM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
> Reviewed 5 of 15 files at r1, 2 of 3 files at r2, 1 of 8 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1367)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1367)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1367#-:-Mpl2YXr5EEKEvR4RoaI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
