### PR TITLE
doc: move documentation to the 'manpages' directory

### PR DESCRIPTION
**Pull request by ldorau**
It is a preparation to adding the documentation of v0.9.0.
The documentation will be located in the following directories:
- ./manpages/master - docs of the current 'master' branch
- ./manpages/v0.9.0 - docs of v0.9.0

The #538 PR has to be merged just after having merged this one.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/536)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 60 of 60 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/536#-:-MIci8Gr3Lpx4GG86vjO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
we have to keep this link alive for at least two weeks:

https://pmem.io/rpma/master/librpma.7.html

it could be some kind of redirection.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/536#-:-MIdB2GT8ekjca6O90Z4:bjisbpi)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
Aha, so better let's postpone moving this documantation ... I will adjust other PRs.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/536#-:-MIdGAFXDvxanS5hZ5b4:b-9ccobd)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by ldorau** [comment]
Postponed

**Review by janekmi — COMMENTED** [review]
We can set up a simple redirect to the new localization: https://www.rapidtables.com/web/dev/html-redirect.html

> Reviewed 60 of 60 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/536#-:-MIdqLy290divlqKFGpL:bdd5lad)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by ldorau** [comment]
@janekmi @grom72 @osalyk Reopened, redirection added.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 61 of 61 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/536#-:-MIruYAg94-1-uToU8o4:bnfp4nl)* status: 62 of 63 files reviewed, all discussions resolved

**Comment by ldorau** [comment]
It works: https://ldorau.github.io/rpma/

**Review by grom72 — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/536#-:-MIwWR1v1yxf6jbxMA4P:bkywwy7)* status: 62 of 63 files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
> Reviewed 3 of 61 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/536)* status: 62 of 63 files reviewed, all discussions resolved

**Pull request merged**
