### PR TITLE
tools: describe REMOTE_PMEM_PATH in details

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1500)

### CODE REVIEW

**Review by osalyk — APPROVED** [review]
:lgtm_strong: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1500#-:-MtcX2__-ugEI-IIljPA:b-uwkowd)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1500)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1500#-Mtd-vl5A8DTq4XLFR9P:-Mtd-vl5A8DTq4XLFR9Q:b-9biy3h) (no related file):*
Would it be better to refer to a Fio command option --filename_format?
(https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-filename-format)

---
___
*[tools/perf/CONFIG.JSON.md, line 14 at r1](https://reviewable.io/reviews/pmem/rpma/1500#-MtcvmUN10p2pqN91AJ8:-MtcvmUN10p2pqN91AJ9:b-d35ifx) ([raw file](https://github.com/pmem/rpma/blob/77c250051f177ab96691cc5312e9e7c9058332f5/tools/perf/CONFIG.JSON.md#L14)):*
> ```Markdown
> - "REMOTE_JOB_NUMA" - a number of the NUMA node on which benchmarking tools will be run on the RPMA target,
> - "REMOTE_DIRECT_WRITE_TO_PMEM" - a state of 'Direct Write to PMem' (true or false). It is not required in case of Cascade Lake platforms, when "REMOTE_SUDO_NOPASSWD" is set to true and "REMOTE_RNIC_PCIE_ROOT_PORT" is set correctly (for more details see ["Optional parameters"](#optional-parameters) below).
> - "REMOTE_PMEM_PATH" - a path to a PMem on an RPMA target (Device DAX or File System DAX). In case of Device DAX it should be an absolute path to a DAX device (for example "/dev/dax0.0"). In case of File System DAX it should be an absolute path to a non-existing file on this file system, which fio will use as a template to create separate files for each fio job (for example: "/mnt/pmem/file", where "/mnt/pmem/" is a directory where File System DAX is mounted on and "/mnt/pmem/file" does not exist; fio will create files with names "/mnt/pmem/file.NNN"). "REMOTE_PMEM_PATH" is not used and can be set to any value if 'filetype' is set to 'malloc' in a figure used in the benchmark.
> ```

it should be a filename template containing an absolute path to a FsDAX folder concatenating with the filename's prefix, which fio will use to create separate files names for each fio job



_Suggestion:_
```Markdown
it should be an absolute path to a non-existing file on this file system, which fio will use as a template to create separate files for each fio job
```
___
*[tools/perf/CONFIG.JSON.md, line 14 at r1](https://reviewable.io/reviews/pmem/rpma/1500#-MtcwtqYDUx3OKgPCAoD:-MtcwtqYDUx3OKgPCAoE:b3hpdlx) ([raw file](https://github.com/pmem/rpma/blob/77c250051f177ab96691cc5312e9e7c9058332f5/tools/perf/CONFIG.JSON.md#L14)):*
> ```Markdown
> - "REMOTE_JOB_NUMA" - a number of the NUMA node on which benchmarking tools will be run on the RPMA target,
> - "REMOTE_DIRECT_WRITE_TO_PMEM" - a state of 'Direct Write to PMem' (true or false). It is not required in case of Cascade Lake platforms, when "REMOTE_SUDO_NOPASSWD" is set to true and "REMOTE_RNIC_PCIE_ROOT_PORT" is set correctly (for more details see ["Optional parameters"](#optional-parameters) below).
> - "REMOTE_PMEM_PATH" - a path to a PMem on an RPMA target (Device DAX or File System DAX). In case of Device DAX it should be an absolute path to a DAX device (for example "/dev/dax0.0"). In case of File System DAX it should be an absolute path to a non-existing file on this file system, which fio will use as a template to create separate files for each fio job (for example: "/mnt/pmem/file", where "/mnt/pmem/" is a directory where File System DAX is mounted on and "/mnt/pmem/file" does not exist; fio will create files with names "/mnt/pmem/file.NNN"). "REMOTE_PMEM_PATH" is not used and can be set to any value if 'filetype' is set to 'malloc' in a figure used in the benchmark.
> ```

why we should ensure that ```/mnt/pmem/file``` does not exist if Fio creates file ```/mnt/pmem/file.NNN```?



_Suggestion:_
```Markdown
and "/mnt/pmem/file" does not exist
```
___
*[tools/perf/CONFIG.JSON.md, line 14 at r1](https://reviewable.io/reviews/pmem/rpma/1500#-MtcxS9kD4hrGNiKb8y4:-MtcxS9kD4hrGNiKb8y5:bxe9b17) ([raw file](https://github.com/pmem/rpma/blob/77c250051f177ab96691cc5312e9e7c9058332f5/tools/perf/CONFIG.JSON.md#L14)):*
> ```Markdown
> - "REMOTE_JOB_NUMA" - a number of the NUMA node on which benchmarking tools will be run on the RPMA target,
> - "REMOTE_DIRECT_WRITE_TO_PMEM" - a state of 'Direct Write to PMem' (true or false). It is not required in case of Cascade Lake platforms, when "REMOTE_SUDO_NOPASSWD" is set to true and "REMOTE_RNIC_PCIE_ROOT_PORT" is set correctly (for more details see ["Optional parameters"](#optional-parameters) below).
> - "REMOTE_PMEM_PATH" - a path to a PMem on an RPMA target (Device DAX or File System DAX). In case of Device DAX it should be an absolute path to a DAX device (for example "/dev/dax0.0"). In case of File System DAX it should be an absolute path to a non-existing file on this file system, which fio will use as a template to create separate files for each fio job (for example: "/mnt/pmem/file", where "/mnt/pmem/" is a directory where File System DAX is mounted on and "/mnt/pmem/file" does not exist; fio will create files with names "/mnt/pmem/file.NNN"). "REMOTE_PMEM_PATH" is not used and can be set to any value if 'filetype' is set to 'malloc' in a figure used in the benchmark.
> ```

NNN" where NNN is an actual job number. See Fio filename_format command option (https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-filename-format).



_Code quote:_
```Markdown
NNN"
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1500)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1500#-:-Mtg39_O2_MxRpW-a5Lf:bg7igkv)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1500)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1500)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @grom72 and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1500#-Mtd-vl5A8DTq4XLFR9P:-Mthr_YK85i1p-30LXTi:b-896fix) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Would it be better to refer to a Fio command option --filename_format?
(https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-filename-format)

</blockquote></details>

Done.

---
___
*[tools/perf/CONFIG.JSON.md, line 14 at r1](https://reviewable.io/reviews/pmem/rpma/1500#-MtcwtqYDUx3OKgPCAoD:-Mthohem4NW64m42akIA:b-u2tmuz) ([raw file](https://github.com/pmem/rpma/blob/77c250051f177ab96691cc5312e9e7c9058332f5/tools/perf/CONFIG.JSON.md#L14)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

why we should ensure that ```/mnt/pmem/file``` does not exist if Fio creates file ```/mnt/pmem/file.NNN```?
</blockquote></details>

It does not have to exist, but it may.
___
*[tools/perf/CONFIG.JSON.md, line 14 at r1](https://reviewable.io/reviews/pmem/rpma/1500#-MtcxS9kD4hrGNiKb8y4:-MthrZFFEtzhO1m3J9MQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/77c250051f177ab96691cc5312e9e7c9058332f5/tools/perf/CONFIG.JSON.md#L14)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

NNN" where NNN is an actual job number. See Fio filename_format command option (https://fio.readthedocs.io/en/latest/fio_doc.html#cmdoption-arg-filename-format).
</blockquote></details>

Done.
___
*[tools/perf/CONFIG.JSON.md, line 14 at r1](https://reviewable.io/reviews/pmem/rpma/1500#-MtcvmUN10p2pqN91AJ8:-MthrbjH-sZ3Cg8LUQtA:b-47ebij) ([raw file](https://github.com/pmem/rpma/blob/77c250051f177ab96691cc5312e9e7c9058332f5/tools/perf/CONFIG.JSON.md#L14)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

it should be a filename template containing an absolute path to a FsDAX folder concatenating with the filename's prefix, which fio will use to create separate files names for each fio job
</blockquote></details>

IMHO it is too complicated, see the current version

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1500)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/CONFIG.JSON.md, line 14 at r2](https://reviewable.io/reviews/pmem/rpma/1500#-Mtj2rb83MdbHnscH7XQ:-Mtj2rb946mXWiLS12_G:b-tbq1mr) ([raw file](https://github.com/pmem/rpma/blob/cfa10bb5288175f92698b9dd519d33d7c394c2fc/tools/perf/CONFIG.JSON.md#L14)):*
> ```Markdown
> - "REMOTE_JOB_NUMA" - a number of the NUMA node on which benchmarking tools will be run on the RPMA target,
> - "REMOTE_DIRECT_WRITE_TO_PMEM" - a state of 'Direct Write to PMem' (true or false). It is not required in case of Cascade Lake platforms, when "REMOTE_SUDO_NOPASSWD" is set to true and "REMOTE_RNIC_PCIE_ROOT_PORT" is set correctly (for more details see ["Optional parameters"](#optional-parameters) below).
> - "REMOTE_PMEM_PATH" - a path to a PMem on an RPMA target (Device DAX or File System DAX). In case of Device DAX it should be an absolute path to a DAX device (for example "/dev/dax0.0"). In case of File System DAX it should be an absolute path to a file (that may not exist) on this file system, which fio will use as a template to create separate files for each fio job (for example: "/mnt/pmem/file", where "/mnt/pmem/" is a directory where File System DAX is mounted on; fio will create files with names "/mnt/pmem/file.N", where N is the incremental number of the worker thread or process - see the [filename_format command line option][filename-format] for more details). This "REMOTE_PMEM_PATH" is not used and can be set to any value if 'filetype' is set to 'malloc' in a figure used in the benchmark.
> ```

I think this part can be removed. We need only a path template, not a path to file.

```in case of File System DAX it should be an absolute path, which fio will```



_Suggestion:_
```Markdown
in case of File System DAX it should be an absolute path to a file (that may not exist) on this file system, which fio will
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1500)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[tools/perf/CONFIG.JSON.md, line 14 at r2](https://reviewable.io/reviews/pmem/rpma/1500#-Mtj2rb83MdbHnscH7XQ:-MtlNPZB0H_PsvlSGeF5:bphhkui) ([raw file](https://github.com/pmem/rpma/blob/cfa10bb5288175f92698b9dd519d33d7c394c2fc/tools/perf/CONFIG.JSON.md#L14)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I think this part can be removed. We need only a path template, not a path to file.

```in case of File System DAX it should be an absolute path, which fio will```
</blockquote></details>

I do not understand what part could be removed and what should be the final version according to you ?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1500)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[tools/perf/CONFIG.JSON.md, line 14 at r2](https://reviewable.io/reviews/pmem/rpma/1500#-Mtj2rb83MdbHnscH7XQ:-MtlOGot1Ef5dBOIRYqb:b-iyg70r) ([raw file](https://github.com/pmem/rpma/blob/cfa10bb5288175f92698b9dd519d33d7c394c2fc/tools/perf/CONFIG.JSON.md#L14)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I do not understand what part could be removed and what should be the final version according to you ?
</blockquote></details>

Besides, a user is NOT supposed to provide a template, but only a file name, which is used by the benchmarking framework to create a template that is passed to fio.

A user should provide only a file name, not a template.

**Review by haichangsi — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1500#-:-MtlfsKkB5tMC2dhvson:bdycpsm)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1500)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/CONFIG.JSON.md, line 14 at r2](https://reviewable.io/reviews/pmem/rpma/1500#-Mtj2rb83MdbHnscH7XQ:-MtllY_C85CVbqZ7p3Aa:b-pzlvzj) ([raw file](https://github.com/pmem/rpma/blob/cfa10bb5288175f92698b9dd519d33d7c394c2fc/tools/perf/CONFIG.JSON.md#L14)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Besides, a user is NOT supposed to provide a template, but only a file name, which is used by the benchmarking framework to create a template that is passed to fio.

A user should provide only a file name, not a template.
</blockquote></details>

TO REMOVE:  ```to a file (that may not exist) on this file system```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1500)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/perf/CONFIG.JSON.md, line 14 at r2](https://reviewable.io/reviews/pmem/rpma/1500#-Mtj2rb83MdbHnscH7XQ:-MtqKbP39cNFdBtCAiUE:bdid0wi) ([raw file](https://github.com/pmem/rpma/blob/cfa10bb5288175f92698b9dd519d33d7c394c2fc/tools/perf/CONFIG.JSON.md#L14)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

TO REMOVE:  ```to a file (that may not exist) on this file system```
</blockquote></details>

It cannot be removed, because it cannot be a path to a directory (`/mnt/pmem` for example).

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1500#-:-MttQvTv5Y8GVBnmjiud:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
