### PR TITLE
common: roadmap update (12/28/20)

### PR DESCRIPTION
**Pull request by grom72**
Updated version to be seen here:
https://github.com/grom72/rpma/blob/roadmap/ROADMAP.md

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/702)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/702)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72)

___
*[ROADMAP.md, line 10 at r1](https://reviewable.io/reviews/pmem/rpma/702#-MPhyCcFENdMtmSZtQW8:-MPhyCcFENdMtmSZtQW9:b-k7uejr) ([raw file](https://github.com/pmem/rpma/blob/99aba323e65590d8830bbc848c302c3457ac671c/ROADMAP.md#L10)):*
> ```Markdown
> **Note:**
> 
> Please take a look at [Contributing.md](Contributing.md) before you start developing.
> ```

```
**Note**: Please take a look at...
```
___
*[ROADMAP.md, line 10 at r1](https://reviewable.io/reviews/pmem/rpma/702#-MPhyTyY97vAecIxbYDI:-MPhyTyY97vAecIxbYDJ:bixi7vz) ([raw file](https://github.com/pmem/rpma/blob/99aba323e65590d8830bbc848c302c3457ac671c/ROADMAP.md#L10)):*
> ```Markdown
> **Note:**
> 
> Please take a look at [Contributing.md](Contributing.md) before you start developing.
> ```

CONTRIBUTING
___
*[ROADMAP.md, line 32 at r1](https://reviewable.io/reviews/pmem/rpma/702#-MPhyvmi1GigJkAVPcRE:-MPhyvmjBvnHpb9FybWv:b-fdgtly) ([raw file](https://github.com/pmem/rpma/blob/99aba323e65590d8830bbc848c302c3457ac671c/ROADMAP.md#L32)):*
> ```Markdown
> The librpma fio engine is distinguished as a separate value built on the top of the librpma library with its own roadmap that will not affect the librpma release cycle.
> 
> You can follow actual development of the Fio engine on [github.com/pmem/fio](https://github.com/pmem/fio) repo. 
> ```

**the**  actual
___
*[ROADMAP.md, line 34 at r1](https://reviewable.io/reviews/pmem/rpma/702#-MPhz0Ak4n_keAfIP0uo:-MPhz0Ak4n_keAfIP0up:b-hicvwe) ([raw file](https://github.com/pmem/rpma/blob/99aba323e65590d8830bbc848c302c3457ac671c/ROADMAP.md#L34)):*
> ```Markdown
> You can follow actual development of the Fio engine on [github.com/pmem/fio](https://github.com/pmem/fio) repo. 
> 
> Final version will be upstreamed to the main Fio repository.
> ```

The final
___
*[ROADMAP.md, line 41 at r1](https://reviewable.io/reviews/pmem/rpma/702#-MPhz7wo5pfb_9sAAAIf:-MPhz7wo5pfb_9sAAAIg:b-hveu6y) ([raw file](https://github.com/pmem/rpma/blob/99aba323e65590d8830bbc848c302c3457ac671c/ROADMAP.md#L41)):*
> ```Markdown
> :ballot_box_with_check:|Fio engine for reading|Support for RPMem read operation.|Q4'20
> :construction:|Fio instruction|An instruction that demonstrates how to benchmark librpma using Fio|Q1'21
> :construction:|Fio engine for GPSPM|Fio engine support for GPSPM flush.|Q1'21
> ```

I think the legend is so concise you can repeat it here also.

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/702)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72)

___
*[ROADMAP.md, line 14 at r1](https://reviewable.io/reviews/pmem/rpma/702#-MPhzF7YB54UmN7btUqS:-MPhzF7YB54UmN7btUqT:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/99aba323e65590d8830bbc848c302c3457ac671c/ROADMAP.md#L14)):*
> ```Markdown
> **Note:**
> 
> Please notice that work has been already started for items marked with :construction: status.
> ```

.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/702)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @janekmi)

___
*[ROADMAP.md, line 10 at r1](https://reviewable.io/reviews/pmem/rpma/702#-MPhyCcFENdMtmSZtQW8:-MPi50261uOqcD7i908X:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/99aba323e65590d8830bbc848c302c3457ac671c/ROADMAP.md#L10)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```
**Note**: Please take a look at...
```
</blockquote></details>

Done.
___
*[ROADMAP.md, line 10 at r1](https://reviewable.io/reviews/pmem/rpma/702#-MPhyTyY97vAecIxbYDI:-MPi6Ltb3LIymCW5_tHP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/99aba323e65590d8830bbc848c302c3457ac671c/ROADMAP.md#L10)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

CONTRIBUTING
</blockquote></details>

Done.
___
*[ROADMAP.md, line 14 at r1](https://reviewable.io/reviews/pmem/rpma/702#-MPhzF7YB54UmN7btUqS:-MPi5F9UEC4ossAxTooy:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/99aba323e65590d8830bbc848c302c3457ac671c/ROADMAP.md#L14)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[ROADMAP.md, line 32 at r1](https://reviewable.io/reviews/pmem/rpma/702#-MPhyvmi1GigJkAVPcRE:-MPi5GoH8cC88Rzj7C0U:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/99aba323e65590d8830bbc848c302c3457ac671c/ROADMAP.md#L32)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

**the**  actual
</blockquote></details>

Done.
___
*[ROADMAP.md, line 34 at r1](https://reviewable.io/reviews/pmem/rpma/702#-MPhz0Ak4n_keAfIP0uo:-MPi5HO-09QxF2caM86C:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/99aba323e65590d8830bbc848c302c3457ac671c/ROADMAP.md#L34)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The final
</blockquote></details>

Done.
___
*[ROADMAP.md, line 41 at r1](https://reviewable.io/reviews/pmem/rpma/702#-MPhz7wo5pfb_9sAAAIf:-MPi6Kq65m9pc38Y9XpJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/99aba323e65590d8830bbc848c302c3457ac671c/ROADMAP.md#L41)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think the legend is so concise you can repeat it here also.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/702#-:-MPiQtzw8y7diNosScuj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/702)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72)

___
*[ROADMAP.md, line 6 at r2](https://reviewable.io/reviews/pmem/rpma/702#-MPi_D3A-eOWYgzYN92w:-MPi_D3BElHmrBSb8pAP:b-pg3k92) ([raw file](https://github.com/pmem/rpma/blob/ccc84179da2812aebbf51d81f86135ec0002406e/ROADMAP.md#L6)):*
> ```
>  you; either you expect this item to be added to the library, or you would like to deliver a source code solution for it.
> ```

in brackets?

```
 you (either ... for it).
```
___
*[ROADMAP.md, line 10 at r2](https://reviewable.io/reviews/pmem/rpma/702#-MPi_O2A76THNT6a6o3P:-MPi_O2A76THNT6a6o3Q:blo12oe) ([raw file](https://github.com/pmem/rpma/blob/ccc84179da2812aebbf51d81f86135ec0002406e/ROADMAP.md#L10)):*
> ```
> with :construction: status.
> ```

with THE :construction: status.
___
*[ROADMAP.md, line 21 at r2](https://reviewable.io/reviews/pmem/rpma/702#-MPi_Z6Z4b2SP9ncUe7e:-MPi_Z6Z4b2SP9ncUe7f:by7j39i) ([raw file](https://github.com/pmem/rpma/blob/ccc84179da2812aebbf51d81f86135ec0002406e/ROADMAP.md#L21)):*
> ```
> Introduce verify operation
> ```

Introduce the 'verify' operation
___
*[ROADMAP.md, line 28 at r2](https://reviewable.io/reviews/pmem/rpma/702#-MPi_ldTDedSeQPVWZOp:-MPi_ldTDedSeQPVWZOq:bxurotb) ([raw file](https://github.com/pmem/rpma/blob/ccc84179da2812aebbf51d81f86135ec0002406e/ROADMAP.md#L28)):*
> ```
>  actual 
> ```

current ?

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/702)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[ROADMAP.md, line 10 at r2](https://reviewable.io/reviews/pmem/rpma/702#-MPi_O2A76THNT6a6o3P:-MPigb2U8cbhsooH347e:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ccc84179da2812aebbf51d81f86135ec0002406e/ROADMAP.md#L10)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> with :construction: status.
> ```

with THE :construction: status.
</blockquote></details>

Done.
___
*[ROADMAP.md, line 21 at r2](https://reviewable.io/reviews/pmem/rpma/702#-MPi_Z6Z4b2SP9ncUe7e:-MPigcpT5Bdoy0g4n5t8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ccc84179da2812aebbf51d81f86135ec0002406e/ROADMAP.md#L21)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> Introduce verify operation
> ```

Introduce the 'verify' operation
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/702)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/702#-:-MPihZ5k9FCAIJ7CbX5l:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
