### PR TITLE
rpma: write 'MEMORY MANAGEMENT' section of manual

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/497)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/497)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/include/librpma.h, line 99 at r1](https://reviewable.io/reviews/pmem/rpma/497#-MITfrC_5O4mQlIcLYP7:-MITfrC_5O4mQlIcLYP8:bzif3br) ([raw file](https://github.com/pmem/rpma/blob/d2800f63c09a0af8099650fd840f6a4b788c2dbb/src/include/librpma.h#L99)):*
> ```
> protection
> ```
usage

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/497)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[src/include/librpma.h, line 99 at r1](https://reviewable.io/reviews/pmem/rpma/497#-MITfrC_5O4mQlIcLYP7:-MITiITyEiz2qIE5chxd:bplmj6k) ([raw file](https://github.com/pmem/rpma/blob/d2800f63c09a0af8099650fd840f6a4b788c2dbb/src/include/librpma.h#L99)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> protection
> ```
usage
</blockquote></details>

They are called '`memory protection attributes`' in the manual of `ibv_reg_mr`:

`The argument access describes the desired memory protection attributes`

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/497)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/include/librpma.h, line 106 at r1](https://reviewable.io/reviews/pmem/rpma/497#-MITj2VVAjctvy8DbUgM:-MITj2VW2soJAgBLAsq_:bcygcw1) ([raw file](https://github.com/pmem/rpma/blob/d2800f63c09a0af8099650fd840f6a4b788c2dbb/src/include/librpma.h#L106)):*
> ```objc
>  * - rpma_mr_dereg() which deregisters the memory region and deletes
>  * the local memory registration object.
>  *
> ```

I think we should mention here what is not RDMA specific:
RPMA_MR_USAGE_FLUSH_TYPE_VISIBILITY
RPMA_MR_USAGE_FLUSH_TYPE_PERSISTENT

especially that this is not covered by functions manuals

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/497)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/include/librpma.h, line 99 at r1](https://reviewable.io/reviews/pmem/rpma/497#-MITvSbXBUTDgFe_C6_I:-MITvSbXBUTDgFe_C6_J:b-i04ukx) ([raw file](https://github.com/pmem/rpma/blob/d2800f63c09a0af8099650fd840f6a4b788c2dbb/src/include/librpma.h#L99)):*
> ```objc
>  * MEMORY MANAGEMENT
>  *
>  * Every piece of RAM must be registered and its memory protection attributes
> ```

RAM -> memory (either volatile or persistent)
___
*[src/include/librpma.h, line 100 at r1](https://reviewable.io/reviews/pmem/rpma/497#-MITvhdN0BYPd_vS-8SG:-MITvhdN0BYPd_vS-8SH:byenjc) ([raw file](https://github.com/pmem/rpma/blob/d2800f63c09a0af8099650fd840f6a4b788c2dbb/src/include/librpma.h#L100)):*
> ```objc
>  *
>  * Every piece of RAM must be registered and its memory protection attributes
>  * must be specified in order to be used in an RDMA operation. This can be done
> ```

I think we should use here RPMA specific terms e.g.:
- RDMA - Remote Memory Access and Messaging
- memory protection attributes - usage?
___
*[src/include/librpma.h, line 106 at r1](https://reviewable.io/reviews/pmem/rpma/497#-MITj2VVAjctvy8DbUgM:-MITw0uxA_XWOYSsZr_d:bd8c8q4) ([raw file](https://github.com/pmem/rpma/blob/d2800f63c09a0af8099650fd840f6a4b788c2dbb/src/include/librpma.h#L106)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I think we should mention here what is not RDMA specific:
RPMA_MR_USAGE_FLUSH_TYPE_VISIBILITY
RPMA_MR_USAGE_FLUSH_TYPE_PERSISTENT

especially that this is not covered by functions manuals
</blockquote></details>

If it is not mentioned in the manual it should be mentioned and described there.
I want to have these sections as simple as possible describing only high-level ideas.
___
*[src/include/librpma.h, line 114 at r1](https://reviewable.io/reviews/pmem/rpma/497#-MITwSpgD0TOglaF7Bno:-MITwSph9x3Zm_ia3ZHZ:b-udhcg8) ([raw file](https://github.com/pmem/rpma/blob/d2800f63c09a0af8099650fd840f6a4b788c2dbb/src/include/librpma.h#L114)):*
> ```objc
>  * to the other side it should be decoded by rpma_mr_remote_from_descriptor()
>  * in order to create a remote memory region's structure
>  * which allows transferring data between the peers.
> ```

**Discussing**: Can you split longer sentences to shorter?
___
*[src/include/librpma.h, line 114 at r1](https://reviewable.io/reviews/pmem/rpma/497#-MITxBoX1-H_P7qv_ZB3:-MITxBoX1-H_P7qv_ZB4:bt4isvl) ([raw file](https://github.com/pmem/rpma/blob/d2800f63c09a0af8099650fd840f6a4b788c2dbb/src/include/librpma.h#L114)):*
> ```objc
>  * to the other side it should be decoded by rpma_mr_remote_from_descriptor()
>  * in order to create a remote memory region's structure
>  * which allows transferring data between the peers.
> ```

which allows for Remote Memory Access?
___
*[src/include/librpma.h, line 692 at r1](https://reviewable.io/reviews/pmem/rpma/497#-MITwxOY-ZfZfKEYxA5T:-MITwtkKDZiqTZ6v4jn5:bmeey8k) ([raw file](https://github.com/pmem/rpma/blob/d2800f63c09a0af8099650fd840f6a4b788c2dbb/src/include/librpma.h#L692)):*
> ```objc
>  * Once the descriptor is transferred to the other side it should be decoded
>  * by rpma_mr_remote_from_descriptor() to create a remote memory region's
>  * structure which allows transferring data between the peers.
> ```

... which allows for Remote Memory Access. Please see librpma(7) for details.

?

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/497)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[src/include/librpma.h, line 106 at r1](https://reviewable.io/reviews/pmem/rpma/497#-MITj2VVAjctvy8DbUgM:-MITy4pO4pT2dWgB8w30:b-gp6d6j) ([raw file](https://github.com/pmem/rpma/blob/d2800f63c09a0af8099650fd840f6a4b788c2dbb/src/include/librpma.h#L106)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

If it is not mentioned in the manual it should be mentioned and described there.
I want to have these sections as simple as possible describing only high-level ideas.
</blockquote></details>

But these flags are not known for ordinary RDMA users

**Review by grom72 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/497#-:-MITyfZTEy7DnfFLcwa8:bdycpsm)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi and @ldorau)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/497)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/include/librpma.h, line 106 at r1](https://reviewable.io/reviews/pmem/rpma/497#-MITj2VVAjctvy8DbUgM:-MIU-le3AXaXvrYkR0Ga:b-w8lkhb) ([raw file](https://github.com/pmem/rpma/blob/d2800f63c09a0af8099650fd840f6a4b788c2dbb/src/include/librpma.h#L106)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

But these flags are not known for ordinary RDMA users
</blockquote></details>

None of the possible usage values is known to anybody who did not use RPMA. ;-)
If you think these values need more description please prepare a PR. :-)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/497)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[src/include/librpma.h, line 99 at r1](https://reviewable.io/reviews/pmem/rpma/497#-MITvSbXBUTDgFe_C6_I:-MIUGvVyAFegj-Q9Pj_4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d2800f63c09a0af8099650fd840f6a4b788c2dbb/src/include/librpma.h#L99)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

RAM -> memory (either volatile or persistent)
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 100 at r1](https://reviewable.io/reviews/pmem/rpma/497#-MITvhdN0BYPd_vS-8SG:-MIUGvpU3NddtrmbWlVH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d2800f63c09a0af8099650fd840f6a4b788c2dbb/src/include/librpma.h#L100)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we should use here RPMA specific terms e.g.:
- RDMA - Remote Memory Access and Messaging
- memory protection attributes - usage?
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 114 at r1](https://reviewable.io/reviews/pmem/rpma/497#-MITxBoX1-H_P7qv_ZB3:-MIUJlfx4iufxdMNJFaf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d2800f63c09a0af8099650fd840f6a4b788c2dbb/src/include/librpma.h#L114)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

which allows for Remote Memory Access?
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/497#-:-MIUxIfRATGm2UXvH2j8:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/497#-:-MIV2d4GAivQMR2fqwJY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
