### PR TITLE
tools: adjust the report menu and link to the headers

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/807)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/807)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/807#-MSRB4FV7eBfFYDkX5oj:-MSRB4FV7eBfFYDkX5ok:bhwcpwo) (no related file):*
Is it md or html template?

---

**Review by ldorau — COMMENTED** [review]
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/807)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/807)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/807#-:-MSRuOj27DZsr0BRViU-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/807#-:-MSS8MMY2VdtHYSkWzmj:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/807)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Pull request merged**
