### PR TITLE
tools: perf: introduce report_bench.py --dump mode

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1083)

### CODE REVIEW

**Comment by janekmi** [comment]
The output's example:

```
Requirement: {
    "direct_write_to_pmem": false
} met

Benchmark[0]: not done
- Environment:
platform_generation="Cascade Lake"
server_ip="192.168.102.5"
JOB_NUMA="0"
AUX_PARAMS="-d mlx5_0 -R"
IB_PATH="path"
FIO_PATH="path"
REMOTE_USER="user"
REMOTE_PASS="pass"
REMOTE_JOB_NUMA="0"
REMOTE_AUX_PARAMS="-d mlx5_0 -R"
REMOTE_IB_PATH="path"
REMOTE_SUDO_NOPASSWD="1"
REMOTE_RNIC_PCIE_ROOT_PORT="0000:17:00.0"
REMOTE_DIRECT_WRITE_TO_PMEM="1"
FORCE_REMOTE_DIRECT_WRITE_TO_PMEM="0"
REMOTE_FIO_PATH="path"
REMOTE_JOB_PATH="path"
REMOTE_JOB_MEM_PATH="path"
BUSY_WAIT_POLLING="1"
CPU_LOAD_RANGE="00_99"
REMOTE_ANOTHER_NUMA="1"
REMOTE_RESULTS_DIR="path"
OUTPUT_FILE="/home/nesperf/repos/rpma/tools/perf/report_read/benchmark_0.json"
REMOTE_CMD_PRE="source /opt/intel/sep/sep_vars.sh; numactl -N ${REMOTE_ANOTHER_NUMA} emon -i ${EVENT_LIST} > ${REMOTE_RESULTS_DIR}${RUN_NAME}_emon.dat"
REMOTE_CMD_POST="sleep 10; source /opt/intel/sep/sep_vars.sh; emon -stop"
EVENT_LIST="path"
SHORT_RUNTIME="0"
TRACER="gdbserver localhost:2345"
REMOTE_TRACER="gdbserver localhost:2345"
DO_NOTHING="0"
DUMP_CMDS="0"
- Command: ./ib_read.sh 192.168.102.5 lat

Requirement: {
    "direct_write_to_pmem": true
} met

Benchmark[1]: not done
- Environment:
platform_generation="Cascade Lake"
server_ip="192.168.102.5"
JOB_NUMA="0"
AUX_PARAMS="-d mlx5_0 -R"
IB_PATH="path"
FIO_PATH="path"
REMOTE_USER="user"
REMOTE_PASS="pass"
REMOTE_JOB_NUMA="0"
REMOTE_AUX_PARAMS="-d mlx5_0 -R"
REMOTE_IB_PATH="path"
REMOTE_SUDO_NOPASSWD="1"
REMOTE_RNIC_PCIE_ROOT_PORT="0000:17:00.0"
REMOTE_DIRECT_WRITE_TO_PMEM="1"
FORCE_REMOTE_DIRECT_WRITE_TO_PMEM="1"
REMOTE_FIO_PATH="path"
REMOTE_JOB_PATH="path"
REMOTE_JOB_MEM_PATH="path"
BUSY_WAIT_POLLING="1"
CPU_LOAD_RANGE="00_99"
REMOTE_ANOTHER_NUMA="1"
REMOTE_RESULTS_DIR="path"
OUTPUT_FILE="/home/nesperf/repos/rpma/tools/perf/report_read/benchmark_1.json"
REMOTE_CMD_PRE="source /opt/intel/sep/sep_vars.sh; numactl -N ${REMOTE_ANOTHER_NUMA} emon -i ${EVENT_LIST} > ${REMOTE_RESULTS_DIR}${RUN_NAME}_emon.dat"
REMOTE_CMD_POST="sleep 10; source /opt/intel/sep/sep_vars.sh; emon -stop"
EVENT_LIST="path"
SHORT_RUNTIME="0"
TRACER="gdbserver localhost:2345"
REMOTE_TRACER="gdbserver localhost:2345"
DO_NOTHING="0"
DUMP_CMDS="0"
- Command: ./rpma_fio_bench.sh 192.168.102.5 apm randread lat

Benchmark[2]: not done
- Environment:
platform_generation="Cascade Lake"
server_ip="192.168.102.5"
JOB_NUMA="0"
AUX_PARAMS="-d mlx5_0 -R"
IB_PATH="path"
FIO_PATH="path"
REMOTE_USER="user"
REMOTE_PASS="pass"
REMOTE_JOB_NUMA="0"
REMOTE_AUX_PARAMS="-d mlx5_0 -R"
REMOTE_IB_PATH="path"
REMOTE_SUDO_NOPASSWD="1"
REMOTE_RNIC_PCIE_ROOT_PORT="0000:17:00.0"
REMOTE_DIRECT_WRITE_TO_PMEM="1"
FORCE_REMOTE_DIRECT_WRITE_TO_PMEM="1"
REMOTE_FIO_PATH="path"
REMOTE_JOB_PATH="path"
REMOTE_JOB_MEM_PATH="path"
BUSY_WAIT_POLLING="1"
CPU_LOAD_RANGE="00_99"
REMOTE_ANOTHER_NUMA="1"
REMOTE_RESULTS_DIR="path"
OUTPUT_FILE="/home/nesperf/repos/rpma/tools/perf/report_read/benchmark_2.json"
REMOTE_CMD_PRE="source /opt/intel/sep/sep_vars.sh; numactl -N ${REMOTE_ANOTHER_NUMA} emon -i ${EVENT_LIST} > ${REMOTE_RESULTS_DIR}${RUN_NAME}_emon.dat"
REMOTE_CMD_POST="sleep 10; source /opt/intel/sep/sep_vars.sh; emon -stop"
EVENT_LIST="path"
SHORT_RUNTIME="0"
TRACER="gdbserver localhost:2345"
REMOTE_TRACER="gdbserver localhost:2345"
DO_NOTHING="0"
DUMP_CMDS="0"
- Command: ./rpma_fio_bench.sh 192.168.102.5 apm read lat

```

**Review by ldorau — APPROVED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1083)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm: AFAIKP ;-)

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1083#-:-Mbg9jiy8jCCiOD2oZoA:bdzyuvs)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1083#-:-MbjKbQ6ClOTrqr0Z_9h:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
