### PR TITLE
 test: add rpma_ep_get_fd multithreaded test

### PR DESCRIPTION
**Pull request by ewanglong**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1022)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1022)* status: all files reviewed, 10 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/ep/rpma_ep_get_fd.c, line 38 at r1](https://reviewable.io/reviews/pmem/rpma/1022#-MZG0Uo48sTSHva9KE3Z:-MZG0Uo48sTSHva9KE3_:bt5u7s9) ([raw file](https://github.com/pmem/rpma/blob/c9709b8e63e1455c082c3cf857d895c82887370b/tests/multithreaded/ep/rpma_ep_get_fd.c#L38)):*
> ```C
> 
> 	if ((ret = rpma_utils_get_ibv_context(pr->addr,
> 			RPMA_UTIL_IBV_CONTEXT_REMOTE, &pr->dev)))
> ```

`_CONTEXT_LOCAL`
___
*[tests/multithreaded/ep/rpma_ep_get_fd.c, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1022#-MZG0Z2gDW7INnchdO8O:-MZG0Z2gDW7INnchdO8P:b-jva8a5) ([raw file](https://github.com/pmem/rpma/blob/c9709b8e63e1455c082c3cf857d895c82887370b/tests/multithreaded/ep/rpma_ep_get_fd.c#L39)):*
> ```C
> 	if ((ret = rpma_utils_get_ibv_context(pr->addr,
> 			RPMA_UTIL_IBV_CONTEXT_REMOTE, &pr->dev)))
> 		MTT_RPMA_ERR(tr, "rpma_utils_get_ibv_context", ret);
> ```

return is missing.
___
*[tests/multithreaded/ep/rpma_ep_get_fd.c, line 42 at r1](https://reviewable.io/reviews/pmem/rpma/1022#-MZG0bOl3YiySzHWCj7Y:-MZG0bOl3YiySzHWCj7Z:b-jva8a5) ([raw file](https://github.com/pmem/rpma/blob/c9709b8e63e1455c082c3cf857d895c82887370b/tests/multithreaded/ep/rpma_ep_get_fd.c#L42)):*
> ```C
> 
> 	if ((ret = rpma_peer_new(pr->dev, &pr->peer)))
> 		MTT_RPMA_ERR(tr, "rpma_peer_new", ret);
> ```

return is missing.
___
*[tests/multithreaded/ep/rpma_ep_get_fd.c, line 47 at r1](https://reviewable.io/reviews/pmem/rpma/1022#-MZG0f5eC9N_LLdpYOK3:-MZG0f5eC9N_LLdpYOK4:bpjyflu) ([raw file](https://github.com/pmem/rpma/blob/c9709b8e63e1455c082c3cf857d895c82887370b/tests/multithreaded/ep/rpma_ep_get_fd.c#L47)):*
> ```C
> 	MTT_PORT_SET(pr->port, 0);
> 	if ((ret = rpma_ep_listen(pr->peer, pr->addr, MTT_PORT_STR, &pr->ep)))
> 		MTT_RPMA_ERR(tr, "rpma_ep_listen", ret);
> ```

cleanup the peer object and return.
___
*[tests/multithreaded/ep/rpma_ep_get_fd.c, line 50 at r1](https://reviewable.io/reviews/pmem/rpma/1022#-MZG0iC10eBWHJFWLEsL:-MZG0iC10eBWHJFWLEsM:b-86w0jd) ([raw file](https://github.com/pmem/rpma/blob/c9709b8e63e1455c082c3cf857d895c82887370b/tests/multithreaded/ep/rpma_ep_get_fd.c#L50)):*
> ```C
> 
> 	if ((ret = rpma_ep_get_fd(pr->ep, &pr->exp_ep_fd)))
> 		MTT_RPMA_ERR(tr, "rpma_ep_get_fd", ret);
> ```

cleanup the peer object and the endpoint on error
___
*[tests/multithreaded/ep/rpma_ep_get_fd.c, line 67 at r1](https://reviewable.io/reviews/pmem/rpma/1022#-MZG0xnS2erK6KLm1GKZ:-MZG0xnS2erK6KLm1GK_:bnchovw) ([raw file](https://github.com/pmem/rpma/blob/c9709b8e63e1455c082c3cf857d895c82887370b/tests/multithreaded/ep/rpma_ep_get_fd.c#L67)):*
> ```C
> 
> 	*state_ptr = st;
> }
> ```

You don't need this.
___
*[tests/multithreaded/ep/rpma_ep_get_fd.c, line 77 at r1](https://reviewable.io/reviews/pmem/rpma/1022#-MZG0sZhCHNjHqo8qX3d:-MZG0sZhCHNjHqo8qX3e:bnchovw) ([raw file](https://github.com/pmem/rpma/blob/c9709b8e63e1455c082c3cf857d895c82887370b/tests/multithreaded/ep/rpma_ep_get_fd.c#L77)):*
> ```C
> {
> 	struct prestate *pr = (struct prestate *)prestate;
> 	struct state *st = (struct state *)state;
> ```

You don't need this.
___
*[tests/multithreaded/ep/rpma_ep_get_fd.c, line 81 at r1](https://reviewable.io/reviews/pmem/rpma/1022#-MZG1072E9cDC3_w6nZ3:-MZG1072E9cDC3_w6nZ4:b-jva8a5) ([raw file](https://github.com/pmem/rpma/blob/c9709b8e63e1455c082c3cf857d895c82887370b/tests/multithreaded/ep/rpma_ep_get_fd.c#L81)):*
> ```C
> 	int ret = rpma_ep_get_fd(pr->ep, &st->ep_fd);
> 	if (ret)
> 		MTT_RPMA_ERR(result, "rpma_ep_get_fd", ret);
> ```

return is missing.
___
*[tests/multithreaded/ep/rpma_ep_get_fd.c, line 85 at r1](https://reviewable.io/reviews/pmem/rpma/1022#-MZG13SJDJ5_EuK4fkLB:-MZG13SJDJ5_EuK4fkLC:bsctr3m) ([raw file](https://github.com/pmem/rpma/blob/c9709b8e63e1455c082c3cf857d895c82887370b/tests/multithreaded/ep/rpma_ep_get_fd.c#L85)):*
> ```C
> 	if (st->ep_fd != pr->exp_ep_fd)
> 		MTT_RPMA_ERR(result,
> 		"rpma_ep_get_fd returned an unexpected value", st->ep_fd);
> ```

You have to use MTT_ERR instead of MTT_RPMA_ERR.
___
*[tests/multithreaded/ep/rpma_ep_get_fd.c, line 99 at r1](https://reviewable.io/reviews/pmem/rpma/1022#-MZG19Z-9GKH1eMTbCLG:-MZG19Z-9GKH1eMTbCLH:bnchovw) ([raw file](https://github.com/pmem/rpma/blob/c9709b8e63e1455c082c3cf857d895c82887370b/tests/multithreaded/ep/rpma_ep_get_fd.c#L99)):*
> ```C
> 	free(st);
> 	*state_ptr = NULL;
> }
> ```

You don't need this.

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1022)* status: 5 of 7 files reviewed, 10 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/ep/rpma_ep_get_fd.c, line 38 at r1](https://reviewable.io/reviews/pmem/rpma/1022#-MZG0Uo48sTSHva9KE3Z:-MZLLu8D0yA5yarpK-74:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c9709b8e63e1455c082c3cf857d895c82887370b/tests/multithreaded/ep/rpma_ep_get_fd.c#L38)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`_CONTEXT_LOCAL`
</blockquote></details>

Done.
___
*[tests/multithreaded/ep/rpma_ep_get_fd.c, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1022#-MZG0Z2gDW7INnchdO8O:-MZLMEZiAZH_Vn4kgYmh:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c9709b8e63e1455c082c3cf857d895c82887370b/tests/multithreaded/ep/rpma_ep_get_fd.c#L39)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

return is missing.
</blockquote></details>

Done.
___
*[tests/multithreaded/ep/rpma_ep_get_fd.c, line 42 at r1](https://reviewable.io/reviews/pmem/rpma/1022#-MZG0bOl3YiySzHWCj7Y:-MZLMFZM-iX-dAqipqRa:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c9709b8e63e1455c082c3cf857d895c82887370b/tests/multithreaded/ep/rpma_ep_get_fd.c#L42)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

return is missing.
</blockquote></details>

Done.
___
*[tests/multithreaded/ep/rpma_ep_get_fd.c, line 47 at r1](https://reviewable.io/reviews/pmem/rpma/1022#-MZG0f5eC9N_LLdpYOK3:-MZLMGiiE0nn7k5rMujl:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c9709b8e63e1455c082c3cf857d895c82887370b/tests/multithreaded/ep/rpma_ep_get_fd.c#L47)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

cleanup the peer object and return.
</blockquote></details>

Done.
___
*[tests/multithreaded/ep/rpma_ep_get_fd.c, line 50 at r1](https://reviewable.io/reviews/pmem/rpma/1022#-MZG0iC10eBWHJFWLEsL:-MZLMHxs0YXfg6gMvExU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c9709b8e63e1455c082c3cf857d895c82887370b/tests/multithreaded/ep/rpma_ep_get_fd.c#L50)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

cleanup the peer object and the endpoint on error
</blockquote></details>

Done.
___
*[tests/multithreaded/ep/rpma_ep_get_fd.c, line 67 at r1](https://reviewable.io/reviews/pmem/rpma/1022#-MZG0xnS2erK6KLm1GKZ:-MZLMIqS1YdD8J7uHaRa:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c9709b8e63e1455c082c3cf857d895c82887370b/tests/multithreaded/ep/rpma_ep_get_fd.c#L67)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You don't need this.
</blockquote></details>

Done.
___
*[tests/multithreaded/ep/rpma_ep_get_fd.c, line 77 at r1](https://reviewable.io/reviews/pmem/rpma/1022#-MZG0sZhCHNjHqo8qX3d:-MZLMJTyD8wlDO0TvMSW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c9709b8e63e1455c082c3cf857d895c82887370b/tests/multithreaded/ep/rpma_ep_get_fd.c#L77)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You don't need this.
</blockquote></details>

Done.
___
*[tests/multithreaded/ep/rpma_ep_get_fd.c, line 81 at r1](https://reviewable.io/reviews/pmem/rpma/1022#-MZG1072E9cDC3_w6nZ3:-MZLMKhh4BNGnQd7vS7-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c9709b8e63e1455c082c3cf857d895c82887370b/tests/multithreaded/ep/rpma_ep_get_fd.c#L81)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

return is missing.
</blockquote></details>

Done.
___
*[tests/multithreaded/ep/rpma_ep_get_fd.c, line 85 at r1](https://reviewable.io/reviews/pmem/rpma/1022#-MZG13SJDJ5_EuK4fkLB:-MZLMLQT8AidU-CsG8cq:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c9709b8e63e1455c082c3cf857d895c82887370b/tests/multithreaded/ep/rpma_ep_get_fd.c#L85)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You have to use MTT_ERR instead of MTT_RPMA_ERR.
</blockquote></details>

Done.
___
*[tests/multithreaded/ep/rpma_ep_get_fd.c, line 99 at r1](https://reviewable.io/reviews/pmem/rpma/1022#-MZG19Z-9GKH1eMTbCLG:-MZLMMAk54c6oajiyX7Y:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c9709b8e63e1455c082c3cf857d895c82887370b/tests/multithreaded/ep/rpma_ep_get_fd.c#L99)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You don't need this.
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1022)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/ep/rpma_ep_get_fd.c, line 47 at r1](https://reviewable.io/reviews/pmem/rpma/1022#-MZG0f5eC9N_LLdpYOK3:-MZMIjsa7BeilPjfHcqt:b-3f9yez) ([raw file](https://github.com/pmem/rpma/blob/c9709b8e63e1455c082c3cf857d895c82887370b/tests/multithreaded/ep/rpma_ep_get_fd.c#L47)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`(void) rpma_peer_delete(&pr->peer);`

**Note**: Space between `(void)` and the function is intentionial.
___
*[tests/multithreaded/ep/rpma_ep_get_fd.c, line 19 at r2](https://reviewable.io/reviews/pmem/rpma/1022#-MZMJCS5AgT5x8AgQkvJ:-MZMJCS5AgT5x8AgQkvK:b8cb3or) ([raw file](https://github.com/pmem/rpma/blob/e467357b37d4966c2b2e8ef7e9e94b53a60d5ce5/tests/multithreaded/ep/rpma_ep_get_fd.c#L19)):*
> ```C
> 	struct rpma_peer *peer;
> 	struct rpma_ep *ep;
> 	int exp_ep_fd;
> ```

`ep_fd_exp`
___
*[tests/multithreaded/ep/rpma_ep_get_fd.c, line 55 at r2](https://reviewable.io/reviews/pmem/rpma/1022#-MZMIyAZCsGqJnX6UFu4:-MZMIyAZCsGqJnX6UFu5:b6cdj0b) ([raw file](https://github.com/pmem/rpma/blob/e467357b37d4966c2b2e8ef7e9e94b53a60d5ce5/tests/multithreaded/ep/rpma_ep_get_fd.c#L55)):*
> ```C
> 		MTT_RPMA_ERR(tr, "rpma_ep_get_fd", ret);
> 		rpma_ep_shutdown(&pr->ep);
> 		rpma_peer_delete(&pr->peer);
> ```

```c
		(void) rpma_ep_shutdown(&pr->ep);
		(void) rpma_peer_delete(&pr->peer);
```
___
*[tests/multithreaded/ep/rpma_ep_get_fd.c, line 77 at r2](https://reviewable.io/reviews/pmem/rpma/1022#-MZMJV2z2nnDEVffuHzv:-MZMJV2z2nnDEVffuHzw:b-lxryn5) ([raw file](https://github.com/pmem/rpma/blob/e467357b37d4966c2b2e8ef7e9e94b53a60d5ce5/tests/multithreaded/ep/rpma_ep_get_fd.c#L77)):*
> ```C
> 	if (ep_fd != pr->exp_ep_fd)
> 		MTT_ERR(result,
> 		"rpma_ep_get_fd returned an unexpected value", ep_fd);
> ```

`"ep_fd != ep_fd_exp"`
___
*[tests/multithreaded/ep/rpma_ep_get_fd.c, line 77 at r2](https://reviewable.io/reviews/pmem/rpma/1022#-MZMJas4DTgxCKTJc9PM:-MZMJas4DTgxCKTJc9PN:b-1ox1n4) ([raw file](https://github.com/pmem/rpma/blob/e467357b37d4966c2b2e8ef7e9e94b53a60d5ce5/tests/multithreaded/ep/rpma_ep_get_fd.c#L77)):*
> ```C
> 	if (ep_fd != pr->exp_ep_fd)
> 		MTT_ERR(result,
> 		"rpma_ep_get_fd returned an unexpected value", ep_fd);
> ```

`ep_fd` is not an error code. I recommend using `EINVAL`.

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1022)* status: all files reviewed, 6 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/ep/rpma_ep_get_fd.c, line 77 at r2](https://reviewable.io/reviews/pmem/rpma/1022#-MZMKMZ6ESb5qQrrzYPc:-MZMKMZ6ESb5qQrrzYPd:b-fuhp06) ([raw file](https://github.com/pmem/rpma/blob/e467357b37d4966c2b2e8ef7e9e94b53a60d5ce5/tests/multithreaded/ep/rpma_ep_get_fd.c#L77)):*
> ```C
> 	if (ep_fd != pr->exp_ep_fd)
> 		MTT_ERR(result,
> 		"rpma_ep_get_fd returned an unexpected value", ep_fd);
> ```

Indentation.

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1022)* status: all files reviewed, 6 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/multithreaded/ep/rpma_ep_get_fd.c, line 47 at r1](https://reviewable.io/reviews/pmem/rpma/1022#-MZG0f5eC9N_LLdpYOK3:-MZMQbV32S0gNwTlAcCD:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c9709b8e63e1455c082c3cf857d895c82887370b/tests/multithreaded/ep/rpma_ep_get_fd.c#L47)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`(void) rpma_peer_delete(&pr->peer);`

**Note**: Space between `(void)` and the function is intentionial.

</blockquote></details>

Done.
___
*[tests/multithreaded/ep/rpma_ep_get_fd.c, line 19 at r2](https://reviewable.io/reviews/pmem/rpma/1022#-MZMJCS5AgT5x8AgQkvJ:-MZMQ_FJ3LT7oA8a6Czf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0d739fcc839a0be6a8323ea7e1002604dc3e3388/tests/multithreaded/ep/rpma_ep_get_fd.c#L19)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`ep_fd_exp`
</blockquote></details>

Done.
___
*[tests/multithreaded/ep/rpma_ep_get_fd.c, line 55 at r2](https://reviewable.io/reviews/pmem/rpma/1022#-MZMIyAZCsGqJnX6UFu4:-MZMQc99Dsx9BdO7BJwO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0d739fcc839a0be6a8323ea7e1002604dc3e3388/tests/multithreaded/ep/rpma_ep_get_fd.c#L55)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
		(void) rpma_ep_shutdown(&pr->ep);
		(void) rpma_peer_delete(&pr->peer);
```
</blockquote></details>

Done.
___
*[tests/multithreaded/ep/rpma_ep_get_fd.c, line 77 at r2](https://reviewable.io/reviews/pmem/rpma/1022#-MZMJV2z2nnDEVffuHzv:-MZMQcld6LfHRAO5cKRs:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0d739fcc839a0be6a8323ea7e1002604dc3e3388/tests/multithreaded/ep/rpma_ep_get_fd.c#L77)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`"ep_fd != ep_fd_exp"`
</blockquote></details>

Done.
___
*[tests/multithreaded/ep/rpma_ep_get_fd.c, line 77 at r2](https://reviewable.io/reviews/pmem/rpma/1022#-MZMJas4DTgxCKTJc9PM:-MZMQdh4-c1S-bndJnIK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0d739fcc839a0be6a8323ea7e1002604dc3e3388/tests/multithreaded/ep/rpma_ep_get_fd.c#L77)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`ep_fd` is not an error code. I recommend using `EINVAL`.
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1022)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1022)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tests/multithreaded/ep/rpma_ep_get_fd.c, line 77 at r2](https://reviewable.io/reviews/pmem/rpma/1022#-MZMKMZ6ESb5qQrrzYPc:-MZMOP2Z2l6rq2sGldbe:b3oh8n) ([raw file](https://github.com/pmem/rpma/blob/0d739fcc839a0be6a8323ea7e1002604dc3e3388/tests/multithreaded/ep/rpma_ep_get_fd.c#L77)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Indentation.
</blockquote></details>


Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1022#-:-MZNIdI1AUBjIwbKDKYN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1022#-:-MZNV0pA1Au2R6ZOGnS1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Pull request merged**
