### PR TITLE
doc: add SEE ALSO section (conn)

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/490)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/490)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[src/include/librpma.h, line 1116 at r1](https://reviewable.io/reviews/pmem/rpma/490#-MIT6fLE02exZgtWtMA5:-MIT6fLF7ojVWxCwTDTD:b-mbwjd2) ([raw file](https://github.com/pmem/rpma/blob/7d84b6583fa0e0e2acf1de5d46bd526d6a157132/src/include/librpma.h#L1116)):*
> ```objc
>  *
>  * SEE ALSO
>  * rpma_conn_req_connect(3) and https://pmem.io/rpma/
> ```

- rpma_conn_disconnect
___
*[src/include/librpma.h, line 1246 at r1](https://reviewable.io/reviews/pmem/rpma/490#-MIT70ZY7EoTIT6Qtuk4:-MIT70ZY7EoTIT6Qtuk5:boh7rn0) ([raw file](https://github.com/pmem/rpma/blob/7d84b6583fa0e0e2acf1de5d46bd526d6a157132/src/include/librpma.h#L1246)):*
> ```objc
>  *
>  * SEE ALSO
>  * rpma_conn_delete(3), rpma_conn_req_connect(3) and https://pmem.io/rpma/
> ```

- rpma_conn_next_event
___
*[src/include/librpma.h, line 1393 at r1](https://reviewable.io/reviews/pmem/rpma/490#-MIT7RgNBnyjeWHe5HMS:-MIT7RgNBnyjeWHe5HMT:b7jkctv) ([raw file](https://github.com/pmem/rpma/blob/7d84b6583fa0e0e2acf1de5d46bd526d6a157132/src/include/librpma.h#L1393)):*
> ```objc
>  *
>  * SEE ALSO
>  * rpma_conn_get_private_data(3), rpma_conn_req_new(3) and https://pmem.io/rpma/
> ```

Please add here also all manpages for which you have also listed rpma_conn_req_connect().

**Review by janekmi — COMMENTED** [review]
Great work! :+1: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/490#-:-MIT7e4r5BMLg8E_avxZ:bmqixtq)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/490)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 1116 at r1](https://reviewable.io/reviews/pmem/rpma/490#-MIT6fLE02exZgtWtMA5:-MITAP464oPYhDKcR7ww:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7d84b6583fa0e0e2acf1de5d46bd526d6a157132/src/include/librpma.h#L1116)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

- rpma_conn_disconnect
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1246 at r1](https://reviewable.io/reviews/pmem/rpma/490#-MIT70ZY7EoTIT6Qtuk4:-MITAX-r5QwXUTQHxS8h:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7d84b6583fa0e0e2acf1de5d46bd526d6a157132/src/include/librpma.h#L1246)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

- rpma_conn_next_event
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1393 at r1](https://reviewable.io/reviews/pmem/rpma/490#-MIT7RgNBnyjeWHe5HMS:-MITE24G7aJ7hXoRIqpy:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7d84b6583fa0e0e2acf1de5d46bd526d6a157132/src/include/librpma.h#L1393)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please add here also all manpages for which you have also listed rpma_conn_req_connect().
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/490#-:-MITFBvODPlTPEIrXOA6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/490#-:-MITqvem0tNOgGH9z1_S:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
