### PR TITLE
rpma: rpma_recv 0B message

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/892)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/892)* status: 5 of 7 files reviewed, 7 unresolved discussions (waiting on @osalyk)

___
*[src/mr.h, line 69 at r1](https://reviewable.io/reviews/pmem/rpma/892#-MTjKKdO9MUAhzYyRW6g:-MTjKKdP-vYTm3AFfXuc:b-joo7wc) ([raw file](https://github.com/pmem/rpma/blob/5b0d1033549c19005711c7eefbd5f2a3e202ab74/src/mr.h#L69)):*
> ```
>  * if dst == NULL then offset == 0 && len == 0
> ```

` * dst != NULL || (offset == 0 && len == 0)`
___
*[src/include/librpma.h, line 2247 at r1](https://reviewable.io/reviews/pmem/rpma/892#-MTjPsJY1F4MT3xXtTcQ:-MTjPsJY1F4MT3xXtTcR:b-4jlsxf) ([raw file](https://github.com/pmem/rpma/blob/5b0d1033549c19005711c7eefbd5f2a3e202ab74/src/include/librpma.h#L2247)):*
> ```
> conn or src is NULL
> ```

This is incorrect now. It was correct before.
___
*[src/include/librpma.h, line 2249 at r1](https://reviewable.io/reviews/pmem/rpma/892#-MTjPbx3AKV0Ytr7l0bM:-MTjPbx3AKV0Ytr7l0bN:b-55m0xb) ([raw file](https://github.com/pmem/rpma/blob/5b0d1033549c19005711c7eefbd5f2a3e202ab74/src/include/librpma.h#L2249)):*
> ```
>  * - RPMA_E_INVAL - conn or src is NULL
>  * - RPMA_E_INVAL - flags are not set
>  * - RPMA_E_INVAL - src == NULL && (offset != 0 || len != 0)
> ```

These changes are not related to this PR and should be done in a separate PR.
___
*[src/include/librpma.h, line 2290 at r1](https://reviewable.io/reviews/pmem/rpma/892#-MTjQ1FB0wDhE5xxAnQ_:-MTjQ1FB0wDhE5xxAnQa:b-4jlsxf) ([raw file](https://github.com/pmem/rpma/blob/5b0d1033549c19005711c7eefbd5f2a3e202ab74/src/include/librpma.h#L2290)):*
> ```
> conn or src is NULL
> ```

This is incorrect now. It was correct before.
___
*[src/include/librpma.h, line 2292 at r1](https://reviewable.io/reviews/pmem/rpma/892#-MTjPn0S8FQpLbsCieZ_:-MTjPn0S8FQpLbsCieZa:b-55m0xb) ([raw file](https://github.com/pmem/rpma/blob/5b0d1033549c19005711c7eefbd5f2a3e202ab74/src/include/librpma.h#L2292)):*
> ```
>  * - RPMA_E_INVAL - conn or src is NULL
>  * - RPMA_E_INVAL - flags are not set
>  * - RPMA_E_INVAL - src == NULL && (offset != 0 || len != 0)
> ```

These changes are not related to this PR and should be done in a separate PR.
___
*[src/include/librpma.h, line 2340 at r1](https://reviewable.io/reviews/pmem/rpma/892#-MTjQSeWAIIpScrZ5Der:-MTjQSeWAIIpScrZ5Des:b-wmzsof) ([raw file](https://github.com/pmem/rpma/blob/5b0d1033549c19005711c7eefbd5f2a3e202ab74/src/include/librpma.h#L2340)):*
> ```
> conn or dst is NULL
> ```

`conn is NULL`
___
*[tests/unit/common/mocks-rpma-mr.c, line 141 at r1](https://reviewable.io/reviews/pmem/rpma/892#-MTjO-j7-hsokssxSBnq:-MTjO-j7-hsokssxSBnr:bvhk781) ([raw file](https://github.com/pmem/rpma/blob/bc3208c1a79eea569a437c67112d426ab825d566/tests/unit/common/mocks-rpma-mr.c#L141)):*
> ```
> assert_non_null(dst);
> ```

If you change ASSUMPTIONS in mr.h, all those changes should be reflected here.
So instead of `assert_non_null(dst);` there should be:
```
assert_true(dst != NULL || (offset == 0 && len == 0));
```
now.

Please review (and maybe fix in a separate PR) all such changes you have made recently in your previous pull request(s).

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/892)* status: all files reviewed, 7 unresolved discussions (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/892)* status: all files reviewed, 7 unresolved discussions (waiting on @ldorau)

___
*[src/mr.h, line 69 at r1](https://reviewable.io/reviews/pmem/rpma/892#-MTjKKdO9MUAhzYyRW6g:-MTjTei3CCGhqDLcFPN8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5b0d1033549c19005711c7eefbd5f2a3e202ab74/src/mr.h#L69)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  * if dst == NULL then offset == 0 && len == 0
> ```

` * dst != NULL || (offset == 0 && len == 0)`
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2247 at r1](https://reviewable.io/reviews/pmem/rpma/892#-MTjPsJY1F4MT3xXtTcQ:-MTjTmxnAMfX2RQlYrkI:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5b0d1033549c19005711c7eefbd5f2a3e202ab74/src/include/librpma.h#L2247)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> conn or src is NULL
> ```

This is incorrect now. It was correct before.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2249 at r1](https://reviewable.io/reviews/pmem/rpma/892#-MTjPbx3AKV0Ytr7l0bM:-MTjTyeC6gAEs-O5pggZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5b0d1033549c19005711c7eefbd5f2a3e202ab74/src/include/librpma.h#L2249)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  * - RPMA_E_INVAL - conn or src is NULL
>  * - RPMA_E_INVAL - flags are not set
>  * - RPMA_E_INVAL - src == NULL && (offset != 0 || len != 0)
> ```

These changes are not related to this PR and should be done in a separate PR.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2290 at r1](https://reviewable.io/reviews/pmem/rpma/892#-MTjQ1FB0wDhE5xxAnQ_:-MTjU4XY0Gi5ndv65pYU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5b0d1033549c19005711c7eefbd5f2a3e202ab74/src/include/librpma.h#L2290)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> conn or src is NULL
> ```

This is incorrect now. It was correct before.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2292 at r1](https://reviewable.io/reviews/pmem/rpma/892#-MTjPn0S8FQpLbsCieZ_:-MTjU5702aAU3EHmmt9m:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5b0d1033549c19005711c7eefbd5f2a3e202ab74/src/include/librpma.h#L2292)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  * - RPMA_E_INVAL - conn or src is NULL
>  * - RPMA_E_INVAL - flags are not set
>  * - RPMA_E_INVAL - src == NULL && (offset != 0 || len != 0)
> ```

These changes are not related to this PR and should be done in a separate PR.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2340 at r1](https://reviewable.io/reviews/pmem/rpma/892#-MTjQSeWAIIpScrZ5Der:-MTjU9FVDQhZASSiBwfI:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5b0d1033549c19005711c7eefbd5f2a3e202ab74/src/include/librpma.h#L2340)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> conn or dst is NULL
> ```

`conn is NULL`
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-rpma-mr.c, line 141 at r1](https://reviewable.io/reviews/pmem/rpma/892#-MTjO-j7-hsokssxSBnq:-MTjUTrR4I9UORgMlnIn:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bc3208c1a79eea569a437c67112d426ab825d566/tests/unit/common/mocks-rpma-mr.c#L141)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> assert_non_null(dst);
> ```

If you change ASSUMPTIONS in mr.h, all those changes should be reflected here.
So instead of `assert_non_null(dst);` there should be:
```
assert_true(dst != NULL || (offset == 0 && len == 0));
```
now.

Please review (and maybe fix in a separate PR) all such changes you have made recently in your previous pull request(s).
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
> Reviewed 6 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/892)* status: 4 of 7 files reviewed, 7 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[src/mr.h, line 69 at r1](https://reviewable.io/reviews/pmem/rpma/892#-MTjKKdO9MUAhzYyRW6g:-MTjRlz18PxrHb5nC3xe:b-nm2ut1) ([raw file](https://github.com/pmem/rpma/blob/5b0d1033549c19005711c7eefbd5f2a3e202ab74/src/mr.h#L69)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  * if dst == NULL then offset == 0 && len == 0
> ```

` * dst != NULL || (offset == 0 && len == 0)`
</blockquote></details>

@ldorau has missed `-` at the beginning of the line.
___
*[tests/unit/common/mocks-rpma-mr.c, line 141 at r1](https://reviewable.io/reviews/pmem/rpma/892#-MTjO-j7-hsokssxSBnq:-MTjUYt3Bls98V2ADXHC:b-hfvvn2) ([raw file](https://github.com/pmem/rpma/blob/bc3208c1a79eea569a437c67112d426ab825d566/tests/unit/common/mocks-rpma-mr.c#L141)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> assert_non_null(dst);
> ```

If you change ASSUMPTIONS in mr.h, all those changes should be reflected here.
So instead of `assert_non_null(dst);` there should be:
```
assert_true(dst != NULL || (offset == 0 && len == 0));
```
now.

Please review (and maybe fix in a separate PR) all such changes you have made recently in your previous pull request(s).
</blockquote></details>

@ldorau is right.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/892)* status: 6 of 7 files reviewed, 7 unresolved discussions (waiting on @janekmi and @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/892)* status: all files reviewed, 8 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[src/include/librpma.h, line 2341 at r2](https://reviewable.io/reviews/pmem/rpma/892#-MTjWwIPCaH4Xmf1biNF:-MTjWwIPCaH4Xmf1biNG:b-tg2ab5) ([raw file](https://github.com/pmem/rpma/blob/3d419b976ba09ceab5e54ffb89700ac0e7228689/src/include/librpma.h#L2341)):*
> ```objc
>  *
>  * - RPMA_E_INVAL - conn is NULL
>  * - RPMA_E_INVAL - dst == NULL && (offset != 0 || len != 0)
> ```

`dst == NULL || (offset != 0 || len != 0)`?

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/892)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[src/mr.h, line 69 at r1](https://reviewable.io/reviews/pmem/rpma/892#-MTjKKdO9MUAhzYyRW6g:-MTjWghW7-vj3GV7rNSM:b2nign6) ([raw file](https://github.com/pmem/rpma/blob/5b0d1033549c19005711c7eefbd5f2a3e202ab74/src/mr.h#L69)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

@ldorau has missed `-` at the beginning of the line.
</blockquote></details>

yes

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/892)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 2341 at r2](https://reviewable.io/reviews/pmem/rpma/892#-MTjWwIPCaH4Xmf1biNF:-MTjlIMR64eWqxHl_EeJ:bgw6iz9) ([raw file](https://github.com/pmem/rpma/blob/3d419b976ba09ceab5e54ffb89700ac0e7228689/src/include/librpma.h#L2341)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`dst == NULL || (offset != 0 || len != 0)`?
</blockquote></details>

This version is correct.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/892)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 2341 at r2](https://reviewable.io/reviews/pmem/rpma/892#-MTjWwIPCaH4Xmf1biNF:-MTjnCou62DjchXwsipF:b-fmf0ul) ([raw file](https://github.com/pmem/rpma/blob/3d419b976ba09ceab5e54ffb89700ac0e7228689/src/include/librpma.h#L2341)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

This version is correct.
</blockquote></details>

Yes, it is OK

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/892)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/892#-:-MTjn_DC5As5N-IO_lkz:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/892)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Review by janekmi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/892#-:-MTkWyVZ2LrOFUVAWJCD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
