### PR TITLE
examples: print size of PMem if it is too small

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/2054)

### CODE REVIEW

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2054)* status: 0 of 2 files reviewed, all discussions resolved

**Review by haichangsi — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2054#-:-NFO26IA7H0x-aUOoP8m:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2054)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[`examples/common/common-pmem2_map_file.c` line 48 at r1](https://reviewable.io/reviews/pmem/rpma/2054#-NFO7zg4E2RQ400ngnBx:-NFO7zg4E2RQ400ngnBy:undefined) ([raw file](https://github.com/pmem/rpma/blob/e4f085c9fae9f2c74758a89e569f225c69a29d31/examples/common/common-pmem2_map_file.c#L48)):*
> ```C
> 
> 	if (pmem2_map_get_size(map) < min_size) {
> 		(void) fprintf(stderr, "mapped size for (%s) is too small (%zu < %zu): %s\n",
> ```





_Suggestion:_
```C
		(void) fprintf(stderr, "mapped size for (%s) is too small (actual:%zu - expected:%zu): %s\n",
			path, pmem2_map_get_size(map), min_size, pmem2_errormsg());
```
___
*[`examples/common/common-pmem_map_file.c` line 25 at r1](https://reviewable.io/reviews/pmem/rpma/2054#-NFO8Evx-kwcpyeXKIvN:-NFO8Evx-kwcpyeXKIvO:undefined) ([raw file](https://github.com/pmem/rpma/blob/e4f085c9fae9f2c74758a89e569f225c69a29d31/examples/common/common-pmem_map_file.c#L25)):*
> ```C
> 
> 	if (mem->mr_size < min_size) {
> 		(void) fprintf(stderr, "mapped size for %s is too small (%zu < %zu)\n",
> ```





_Suggestion:_
```C
		(void) fprintf(stderr, "mapped size for %s is too small (actual:%zu - expected:%zu)\n",
				path, mem->mr_size, min_size);
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2054)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[`examples/common/common-pmem2_map_file.c` line 48 at r1](https://reviewable.io/reviews/pmem/rpma/2054#-NFO7zg4E2RQ400ngnBx:-NFOAq2E4nj6H4t75wzd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e4f085c9fae9f2c74758a89e569f225c69a29d31/examples/common/common-pmem2_map_file.c#L48)):*
> ```C
> 
> 	if (pmem2_map_get_size(map) < min_size) {
> 		(void) fprintf(stderr, "mapped size for (%s) is too small (%zu < %zu): %s\n",
> ```

Done.
___
*[`examples/common/common-pmem_map_file.c` line 25 at r1](https://reviewable.io/reviews/pmem/rpma/2054#-NFO8Evx-kwcpyeXKIvN:-NFOAqhu8sMtZF0nkmMy:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e4f085c9fae9f2c74758a89e569f225c69a29d31/examples/common/common-pmem_map_file.c#L25)):*
> ```C
> 
> 	if (mem->mr_size < min_size) {
> 		(void) fprintf(stderr, "mapped size for %s is too small (%zu < %zu)\n",
> ```

Done.

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2054#-:-NFOBFZB5hhMXqnvPleB:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
