### PR TITLE
common: move coverage build from Travis to GHA 

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/472)

### CODE REVIEW

**Comment by ldorau** [comment]
It works:
https://codecov.io/github/pmem/rpma/commit/cf0ff538483f404eb62cd597228192b64d3ab733

**Review by ldorau — COMMENTED** [review]
@lukaszstolarczuk please review

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/472#-:-MILAdEA7-bE7mQQZDbZ:bhzbc7f)* status: 0 of 4 files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
The Coverage build on Travis has been failing very often recently, for example:
https://travis-ci.org/github/ldorau/rpma/builds/731012112

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/472#-:-MILB_Hm63LhtgqqCk5i:bh78a4u)* status: 0 of 4 files reviewed, all discussions resolved

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/472#-:-MIO0aZM8GiVPesO3YSP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/472#-:-MIONoxw-JkxkN4_ffZ0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
