### PR TITLE
common: add info about supported OSes to INSTALL.md

### PR DESCRIPTION
**Pull request by ldorau**
Required:
- [x] #395 
- [x] #421 
- [x] #440

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/366)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/366#-:-MGg-vN17hzY46OSQcMM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/366)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[INSTALL.md, line 15 at r1](https://reviewable.io/reviews/pmem/rpma/366#-MGg7Fk6CfruBDlSc-cI:-MGg7Fk6CfruBDlSc-cJ:b23fom6) ([raw file](https://github.com/pmem/rpma/blob/b8a9288a3aa50e5c2e6d29cf7dc823163b059c3f/INSTALL.md#L15)):*
> ```Markdown
> - Debian 9:     too old version of librdmacm (v1.1.0-2): wrong signature of rdma_getaddrinfo()
> - Ubuntu 16.04: too old version of libibverbs (v1.1.8-1): no ODP support
> ```

@janekmi Do we allow to use librpma without ODP support?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/366)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[INSTALL.md, line 15 at r1](https://reviewable.io/reviews/pmem/rpma/366#-MGg7Fk6CfruBDlSc-cI:-MGgQiqOEFk5VtjUqd5n:bc1r5wx) ([raw file](https://github.com/pmem/rpma/blob/b8a9288a3aa50e5c2e6d29cf7dc823163b059c3f/INSTALL.md#L15)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

@janekmi Do we allow to use librpma without ODP support?
</blockquote></details>

Without ODP support in libibverbs the compilation of librpma fails

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/366)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[INSTALL.md, line 15 at r1](https://reviewable.io/reviews/pmem/rpma/366#-MGg7Fk6CfruBDlSc-cI:-MGgXnsn8vRIeQpA7Pv9:b-oz6qis) ([raw file](https://github.com/pmem/rpma/blob/b8a9288a3aa50e5c2e6d29cf7dc823163b059c3f/INSTALL.md#L15)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Without ODP support in libibverbs the compilation of librpma fails
</blockquote></details>

Shall we have a compilation option to disable ODP fallback support?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/366)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[INSTALL.md, line 15 at r1](https://reviewable.io/reviews/pmem/rpma/366#-MGg7Fk6CfruBDlSc-cI:-MGgsRrk2THcUCPgkFx-:b-z9psp4) ([raw file](https://github.com/pmem/rpma/blob/b8a9288a3aa50e5c2e6d29cf7dc823163b059c3f/INSTALL.md#L15)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Shall we have a compilation option to disable ODP fallback support?
</blockquote></details>

Yes, we will do that later.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/366)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/366)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[INSTALL.md, line 19 at r2](https://reviewable.io/reviews/pmem/rpma/366#-MGnaoFfBxz9Fy-knrjf:-MGnaoFfBxz9Fy-knrjg:b-4jv611) ([raw file](https://github.com/pmem/rpma/blob/fe601f4a573a035aaebc1dfc8ad5766b837041d0/INSTALL.md#L19)):*
> ```Markdown
> - Debian 8:     too old version of CMake (v3.0.2)
> - Ubuntu 14.04: too old version of CMake (v2.8.12.2)
> ```

I think it should not be the first thing the developer will see. I think it will be better to put it at the end of the file and add a note just after the detailed requirements. As I have proposed below.

What do you think?
___
*[INSTALL.md, line 39 at r2](https://reviewable.io/reviews/pmem/rpma/366#-MGnaLXsAm-C_8uCuER4:-MGnaLXsAm-C_8uCuER5:b-nprlcu) ([raw file](https://github.com/pmem/rpma/blob/fe601f4a573a035aaebc1dfc8ad5766b837041d0/INSTALL.md#L39)):*
> ```Markdown
> 
> **Note**: the above revisions are proven to work correctly.
> ```

```
**Note**: See [the list of supported OSes](INSTALL.md##supported-oses).
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/366)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[INSTALL.md, line 19 at r2](https://reviewable.io/reviews/pmem/rpma/366#-MGnaoFfBxz9Fy-knrjf:-MGoEBAh8kml8BTlpmBo:b-el989i) ([raw file](https://github.com/pmem/rpma/blob/fe601f4a573a035aaebc1dfc8ad5766b837041d0/INSTALL.md#L19)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think it should not be the first thing the developer will see. I think it will be better to put it at the end of the file and add a note just after the detailed requirements. As I have proposed below.

What do you think?
</blockquote></details>

I agree. Done.
___
*[INSTALL.md, line 39 at r2](https://reviewable.io/reviews/pmem/rpma/366#-MGnaLXsAm-C_8uCuER4:-MGoEDcL8MaOVmi-kf8l:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fe601f4a573a035aaebc1dfc8ad5766b837041d0/INSTALL.md#L39)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```
**Note**: See [the list of supported OSes](INSTALL.md##supported-oses).
```
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/366#-:-MGp21ra2gyvB4VQ0aGJ:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by ldorau** [comment]
Required:
- [ ] #395 
- [ ] #398

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/366)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by ldorau** [comment]
Required:
- [x] #395 
- [ ] #398
- [ ] #421 
- [ ] #440

**Review by grom72 — COMMENTED** [review]
Does CentOS 6 have support for PMem?

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/366#-:-MI2ST6G-llrQOdzmXGP:bi7tynq)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — COMMENTED** [review]
I do not know

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/366#-:-MI2jHZ22tOxG1ijtWbm:b-w0413j)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
based on official POR PMem AppDir is supported starting from CentOS7

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/366#-:-MI3vbnu30QfeqpPpLU_:byz2zv5)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/366)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
