### PR TITLE
tools: add f(cpuload) to report_bench.sh

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/941)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/941#-:-MVv1K32-cx_wem4Uzt7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/941)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/report_bench.sh, line 56 at r1](https://reviewable.io/reviews/pmem/rpma/941#-MVv633H8mZ4JnbDu546:-MVv633H8mZ4JnbDu547:b83rd24) ([raw file](https://github.com/pmem/rpma/blob/57f04a933eb1ce8ea0e5e740e22ba1b0fb8fd7d5/tools/perf/report_bench.sh#L56)):*
> ```Shell
> 	set -x
> 	for mode in lat bw-bs bw-th lat-cpu bw-cpu bw-cpu-mt; do
> 		[[ "$mode" =~ "cpu" ]] || ./ib_read.sh $SERVER_IP $mode
> ```

I do not think read latency nor read bandwidth under cpuload will be part of the report right now.
Please drop this part.
___
*[tools/perf/report_bench.sh, line 73 at r1](https://reviewable.io/reviews/pmem/rpma/941#-MVvA_Ip0xo_mKgFw_5l:-MVv9ymH3Fpgyzg76Kkq:b-g3wnx8) ([raw file](https://github.com/pmem/rpma/blob/57f04a933eb1ce8ea0e5e740e22ba1b0fb8fd7d5/tools/perf/report_bench.sh#L73)):*
> ```Shell
> 			if [ "$REMOTE_DIRECT_WRITE_TO_PMEM" == "1" -o "$REMOTE_SUDO_NOPASSWD" == "1" ]; then
> 				BUSY_WAIT_POLLING=0 REMOTE_JOB_MEM_PATH=$PMEM \
> 					./rpma_fio_bench.sh $SERVER_IP apm $op $mode
> ```

Please add a note that `BUSY_WAIT_POLLING` does not affect the APM server since it does not wait for completions in any way.
___
*[tools/perf/report_bench.sh, line 79 at r1](https://reviewable.io/reviews/pmem/rpma/941#-MVvAOLLC_VYBX0MS5FV:-MVvAOLLC_VYBX0MS5FW:b-p7r3n) ([raw file](https://github.com/pmem/rpma/blob/57f04a933eb1ce8ea0e5e740e22ba1b0fb8fd7d5/tools/perf/report_bench.sh#L79)):*
> ```Shell
> 				# DDIO=on which is not the default for APM benchmarking.
> 				BUSY_WAIT_POLLING=0 REMOTE_JOB_MEM_PATH=$DRAM FORCE_REMOTE_DIRECT_WRITE_TO_PMEM=0 \
> 					./rpma_fio_bench.sh $SERVER_IP apm $op $mode
> ```

'APMing to DRAM' is not needed in the cpuload comparison. I think these loops may require a split o reorg.
___
*[tools/perf/report_bench.sh, line 94 at r1](https://reviewable.io/reviews/pmem/rpma/941#-MVv6SMXANZCGf6z1-lz:-MVv6SMY3aFZC9OlrrHj:b-velct1) ([raw file](https://github.com/pmem/rpma/blob/57f04a933eb1ce8ea0e5e740e22ba1b0fb8fd7d5/tools/perf/report_bench.sh#L94)):*
> ```Shell
> 	export BUSY_WAIT_POLLING=0
> 	set -x
> 	for mode in lat bw-bs bw-th lat-cpu bw-cpu bw-cpu-mt; do
> ```

Same here. No plans for mixed workload with cpuload.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/941)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/report_bench.sh, line 56 at r1](https://reviewable.io/reviews/pmem/rpma/941#-MVv633H8mZ4JnbDu546:-MVvF3W-35pn5Bw_9Q4z:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/57f04a933eb1ce8ea0e5e740e22ba1b0fb8fd7d5/tools/perf/report_bench.sh#L56)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I do not think read latency nor read bandwidth under cpuload will be part of the report right now.
Please drop this part.
</blockquote></details>

Done.
___
*[tools/perf/report_bench.sh, line 73 at r1](https://reviewable.io/reviews/pmem/rpma/941#-MVvA_Ip0xo_mKgFw_5l:-MVvF7RG2kJ6-bNawcor:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/57f04a933eb1ce8ea0e5e740e22ba1b0fb8fd7d5/tools/perf/report_bench.sh#L73)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please add a note that `BUSY_WAIT_POLLING` does not affect the APM server since it does not wait for completions in any way.
</blockquote></details>

Done.
___
*[tools/perf/report_bench.sh, line 79 at r1](https://reviewable.io/reviews/pmem/rpma/941#-MVvAOLLC_VYBX0MS5FV:-MVvFLnz0GsAc1PJkF5h:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/57f04a933eb1ce8ea0e5e740e22ba1b0fb8fd7d5/tools/perf/report_bench.sh#L79)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

'APMing to DRAM' is not needed in the cpuload comparison. I think these loops may require a split o reorg.
</blockquote></details>

Done.
___
*[tools/perf/report_bench.sh, line 94 at r1](https://reviewable.io/reviews/pmem/rpma/941#-MVv6SMXANZCGf6z1-lz:-MVvFMLJ6ST9lcW7zOzm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/57f04a933eb1ce8ea0e5e740e22ba1b0fb8fd7d5/tools/perf/report_bench.sh#L94)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Same here. No plans for mixed workload with cpuload.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/941#-:-MVvIsXF6vtvfAB7d_iB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/941#-:-MVvLt242wtPZlWqgS4P:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
