### PR TITLE
tools: perf: seal lib.bench

### PR DESCRIPTION
**Pull request by janekmi**
- transform 'raw' members into properties
- copy objects to guard the inner state immutability
- introduce working on copies so the logic stay intact

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1358)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1358)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1358#-:-MpfpeK4-fZsL43nAbFH:bg7igkv)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1358)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1358#-:-MpgPo1f5einq8uPHmFI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1358#-:-MpgRT5eBxvPu--0iplE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
