### PR TITLE
test: generalize suppressions

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1795)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1795)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`tests/drd.supp` line 25 at r1](https://reviewable.io/reviews/pmem/rpma/1795#-N3PuQxz6nWpTpqNF-Ki:-N3PuQxz6nWpTpqNF-Kj:b-ka005f) ([raw file](https://github.com/pmem/rpma/blob/19df9046cb23c80ac4b8ad619af643383d2a9676/tests/drd.supp#L25)):*
> ```
>    drd:ConflictingAccess
>    ...
>    fun:get_timestamp_prefix
> ```

``get_timestamp_prefix`` is a part of librpma



_Suggestion:_
```
   fun:__tz_convert
   fun:get_timestamp_prefix
   fun:rpma_log_default_function
```
___
*[`tests/helgrind.supp` line 26 at r1](https://reviewable.io/reviews/pmem/rpma/1795#-N3Pv0o9CkLkEu5733mQ:-N3Pv0o9CkLkEu5733mR:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/19df9046cb23c80ac4b8ad619af643383d2a9676/tests/helgrind.supp#L26)):*
> ```
>    ...
>    fun:get_timestamp_prefix
>    fun:rpma_log_default_function
> ```

.



_Suggestion:_
```
   fun:__tz_convert
   fun:get_timestamp_prefix
   fun:rpma_log_default_function
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1795)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[`tests/drd.supp` line 25 at r1](https://reviewable.io/reviews/pmem/rpma/1795#-N3PuQxz6nWpTpqNF-Ki:-N3Qif_H4H-_FqcjsNwm:b-d7jef6) ([raw file](https://github.com/pmem/rpma/blob/19df9046cb23c80ac4b8ad619af643383d2a9676/tests/drd.supp#L25)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

``get_timestamp_prefix`` is a part of librpma
</blockquote></details>

Yes, I know that `get_timestamp_prefix` is a part of librpma and in my opinion it should stay as is.
___
*[`tests/helgrind.supp` line 26 at r1](https://reviewable.io/reviews/pmem/rpma/1795#-N3Pv0o9CkLkEu5733mQ:-N3QiuHkAizhkpzp575H:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/19df9046cb23c80ac4b8ad619af643383d2a9676/tests/helgrind.supp#L26)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

.

**Review by osalyk — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1795)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`tests/drd.supp` line 38 at r2](https://reviewable.io/reviews/pmem/rpma/1795#-N3T8jnq8vJBgK30zNZ5:-N3T8jnq8vJBgK30zNZ6:brkha6c) ([raw file](https://github.com/pmem/rpma/blob/e8ed245d0e4a2488a23ff30fe4a0acef5a11abc0/tests/drd.supp#L38)):*
> ```
> }
> ```

Delete an empty line.
___
*[`tests/helgrind.supp` line 101 at r2](https://reviewable.io/reviews/pmem/rpma/1795#-N3T8MNF-d7IkpRQ8tRE:-N3T8MNF-d7IkpRQ8tRF:b-fhokln) ([raw file](https://github.com/pmem/rpma/blob/e8ed245d0e4a2488a23ff30fe4a0acef5a11abc0/tests/helgrind.supp#L101)):*
> ```
>    fun:rpma_conn_req_delete
>    ...
> }
> ```

New line.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1795)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`tests/drd.supp` line 38 at r2](https://reviewable.io/reviews/pmem/rpma/1795#-N3T8jnq8vJBgK30zNZ5:-N3TDTqG22ODPxuoVcBQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e8ed245d0e4a2488a23ff30fe4a0acef5a11abc0/tests/drd.supp#L38)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Delete an empty line.
</blockquote></details>

Done.



_Code quote:_
```
Conflicting load/store in rpma_utils_get_ibv_context()
```
___
*[`tests/helgrind.supp` line 101 at r2](https://reviewable.io/reviews/pmem/rpma/1795#-N3T8MNF-d7IkpRQ8tRE:-N3TDYKk6CftKbhUZAPp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e8ed245d0e4a2488a23ff30fe4a0acef5a11abc0/tests/helgrind.supp#L101)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

New line.
</blockquote></details>

Done.

**Review by osalyk — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1795)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1795#-:-N3Tsfe3EX6YGJKJWU4r:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1795)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1795)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`tests/drd.supp` line 35 at r5](https://reviewable.io/reviews/pmem/rpma/1795#-N3ULt_R9E-6UjXCCI2s:-N3Vafd661fuzHPbq80I:b-ugtths) ([raw file](https://github.com/pmem/rpma/blob/0e713b862cb67545f36c8c173bbb511c15f9868a/tests/drd.supp#L35)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

It seems that we have to make this function call thread-safe.
</blockquote></details>

Why do you think that we have to do that?

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1795)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ldorau and @osalyk)

___
*[`tests/drd.supp` line 35 at r5](https://reviewable.io/reviews/pmem/rpma/1795#-N3ULt_R9E-6UjXCCI2s:-N3Y3wpJAqQR08mhE5L9:bgjv5qj) ([raw file](https://github.com/pmem/rpma/blob/0e713b862cb67545f36c8c173bbb511c15f9868a/tests/drd.supp#L35)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why do you think that we have to do that?
</blockquote></details>

OK, we do not must, but we should as it is a basic function for many other API calls.
We need this for ``rpma_peer`` so as soon as we want to relax the assumption about only one peer in the main thread we should also assume that ``rpma_utils_get_ibv_context`` can be called from many threads.
Additionally, races detected in the context of this function interfere with races e.g. ``rpma_ep_listen``

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1795)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ldorau)

**Comment by ldorau** [comment]
Postponed - the suppressions on master has been changed in meantime...

**Pull request closed without merging**
