### PR TITLE
tools: perf: add preamble to the report

### PR DESCRIPTION
**Pull request by janekmi**
- lib.Part:
	- call items read from part_*.json as constants
	- add set_variables() for variables
	- skip markdown processing for menu() (unnecessary `<p/>`)
	- allow calling content() without custom arguments
- lib.Report:
	- add preamble as the first part of the report
	- provide a dummy variables required for it to render
- templates/part_preamble.md:
	- a slighly adopted copy of various templates/* files
	- updated disclaimer
	- refer variables as it seems to be convenient in the future
- templates/part_read.md:
	- move `<a>Introduction</a>` to part_preamble.md (fix)
	- add missing `<h2>Read from PMem</h2>`

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1176)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1176)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1176)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/templates/part_preamble.md, line 18 at r1](https://reviewable.io/reviews/pmem/rpma/1176#-MfhKQAc6BP4Ond1ByBl:-MfhKQAc6BP4Ond1ByBm:biitpcp) ([raw file](https://github.com/pmem/rpma/blob/bde92e266d45e06fdfaf0a4235d255ad30c84591/tools/perf/templates/part_preamble.md#L18)):*
> ```
> {{test_date}}
> {{authors}}
> ```

They are not printed out in the report - why? Are they empty? How can they be set?

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1176)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1176#-MfhLE3HAXvAYJmRXqzF:-MfhLE3HAXvAYJmRXqzG:b-pu639p) (no related file):*
Builds failed

---

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1176)* status: 2 of 5 files reviewed, 2 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1176#-MfhLE3HAXvAYJmRXqzF:-MfhMGdrD6GwFx2E9w_0:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Builds failed
</blockquote></details>

Done.

---
___
*[tools/perf/templates/part_preamble.md, line 18 at r1](https://reviewable.io/reviews/pmem/rpma/1176#-MfhKQAc6BP4Ond1ByBl:-MfhMSjx3ywUgP1UYWpq:bb33cdy) ([raw file](https://github.com/pmem/rpma/blob/bde92e266d45e06fdfaf0a4235d255ad30c84591/tools/perf/templates/part_preamble.md#L18)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> {{test_date}}
> {{authors}}
> ```

They are not printed out in the report - why? Are they empty? How can they be set?
</blockquote></details>

Yes. They are empty. They will be provided by the `lib.Report` using the `lib.Part.set_variables()`.
It is obviously half-baked. I want to plan what to do next and give you all opportunity to participate.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1176)* status: 3 of 5 files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1176)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1176)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/Part.py, line 94 at r2](https://reviewable.io/reviews/pmem/rpma/1176#-MfhXQCJ4NBX2ciNiYBq:-MfhXQCJ4NBX2ciNiYBr:b-3bivox) ([raw file](https://github.com/pmem/rpma/blob/fcd3db961919c9f8c8554e7f8942b2741a6797ca/tools/perf/lib/Part.py#L94)):*
> ```
> process_markdown=True
> ```

Maybe `convert_html_to_md` ?

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1176)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/Part.py, line 94 at r2](https://reviewable.io/reviews/pmem/rpma/1176#-MfhXQCJ4NBX2ciNiYBq:-MfhYHtl3IK6dAPMT5lV:bxo91uu) ([raw file](https://github.com/pmem/rpma/blob/fcd3db961919c9f8c8554e7f8942b2741a6797ca/tools/perf/lib/Part.py#L94)):*
> convert_html_to_md

I meant `convert_md_to_html` ;-)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1176)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1176#-:-MfkvP-58lASZDAAERh5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1176#-:-MflALN90uz5nhYJTc6O:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1176#-:-MflFTM6Af9d3vA5n251:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1176)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
