### PR TITLE
rpma: correct the order of src_addr and dst_addr

### PR DESCRIPTION
**Pull request by yangx-jy**
Signed-off-by: Xiao Yang <yangx.jy@cn.fujitsu.com>

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/881)

### CODE REVIEW

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/881#-:-MTKB2PH12WUac9KRl9i:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/881)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[src/mr.c, line 132 at r1](https://reviewable.io/reviews/pmem/rpma/881#-MTKVucF3T2fhK8h9Bac:-MTKVucF3T2fhK8h9Bad:bl3pppd) ([raw file](https://github.com/pmem/rpma/blob/6bfcdd1601ed7e0252aac77b7ffc3cd6d5e73b5a/src/mr.c#L132)):*
> ```C
> 	if (ret) {
> 		RPMA_LOG_ERROR_WITH_ERRNO(ret,
> 			"ibv_post_send(dst_addr=0x%x, rkey=0x%x, src_addr=0x%x, length=%u, lkey=0x%x, wr_id=0x%x, opcode=IBV_WR_RDMA_READ, send_flags=%s)",
> ```

This change is unnecessary.
Please look at line 111-116

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/881)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[src/mr.c, line 132 at r1](https://reviewable.io/reviews/pmem/rpma/881#-MTKVucF3T2fhK8h9Bac:-MTKkmGXEm0q_dWXcy8r:b-vikx3q) ([raw file](https://github.com/pmem/rpma/blob/6bfcdd1601ed7e0252aac77b7ffc3cd6d5e73b5a/src/mr.c#L132)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

This change is unnecessary.
Please look at line 111-116
</blockquote></details>

That's right, this change is wrong - it should stay as it is on current master.

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/881)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau and @osalyk)

___
*[src/mr.c, line 132 at r1](https://reviewable.io/reviews/pmem/rpma/881#-MTKVucF3T2fhK8h9Bac:-MTLAXvs2QQvSPZ_JpwT:b-2k173i) ([raw file](https://github.com/pmem/rpma/blob/6bfcdd1601ed7e0252aac77b7ffc3cd6d5e73b5a/src/mr.c#L132)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

That's right, this change is wrong - it should stay as it is on current master.
</blockquote></details>

I agree with @osalyk and @ldorau. For `rpma_read()` the remote address is the source whereas the local address is the destination.

The change is correct for the `rpma_write()` though.

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/881)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau and @osalyk)

**Review by yangx-jy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/881)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi, @ldorau, and @osalyk)

___
*[src/mr.c, line 132 at r1](https://reviewable.io/reviews/pmem/rpma/881#-MTKVucF3T2fhK8h9Bac:-MTLF1k5CiH9ZI7dajCT:b-tbtrwi) ([raw file](https://github.com/pmem/rpma/blob/6bfcdd1601ed7e0252aac77b7ffc3cd6d5e73b5a/src/mr.c#L132)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I agree with @osalyk and @ldorau. For `rpma_read()` the remote address is the source whereas the local address is the destination.

The change is correct for the `rpma_write()` though.
</blockquote></details>

Good catch.  Done.
Only change the order for rpma_mr_write().

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/881)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi and @osalyk)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/881#-:-MTLYc298jH2IhvCYL9E:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/881)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/881#-:-MTLpdQE6kvJZy0rSD7i:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Pull request merged**
