### PR TITLE
tools: add aof option for rpma_fio_bench tool

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/914)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/914)* status: all files reviewed, 7 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/rpma_fio_bench.sh, line 26 at r1](https://reviewable.io/reviews/pmem/rpma/914#-MUiWXju7YGeXOdWTZ5W:-MUiWXju7YGeXOdWTZ5X:bq7ltmh) ([raw file](https://github.com/pmem/rpma/blob/c5fe12a09b9f7b097314eee6f9c68cd006c88f7b/tools/perf/rpma_fio_bench.sh#L26)):*
> ... does not support the 'read', 'randread', 'randwrite', 'rw' and 'randrw' operations.

~~for now~~ seems a bit misleading here since e.g. randwrite won't be supported.
___
*[tools/perf/rpma_fio_bench.sh, line 99 at r1](https://reviewable.io/reviews/pmem/rpma/914#-MUiYEo6908cQKRw_hrI:-MUiYEo6908cQKRw_hrJ:b98ke2n) ([raw file](https://github.com/pmem/rpma/blob/c5fe12a09b9f7b097314eee6f9c68cd006c88f7b/tools/perf/rpma_fio_bench.sh#L99)):*
> ```Shell
> elif [ "$2" == "gpspm" ]; then
> 	case "$3" in
> 	read|randread|rw|randrw)
> ```

Please keep them in the same order as we enumerate in the help.
___
*[tools/perf/rpma_fio_bench.sh, line 105 at r1](https://reviewable.io/reviews/pmem/rpma/914#-MUiYSbc1DsUKCDECHs6:-MUiYSbc1DsUKCDECHs7:b-meseu3) ([raw file](https://github.com/pmem/rpma/blob/c5fe12a09b9f7b097314eee6f9c68cd006c88f7b/tools/perf/rpma_fio_bench.sh#L105)):*
> ```Shell
> elif [ "$2" == "aof" ]; then
> 	case "$3" in
> 	randwrite|read|randread|rw|randrw)
> ```

order.
___
*[tools/perf/rpma_fio_bench.sh, line 106 at r1](https://reviewable.io/reviews/pmem/rpma/914#-MUiXPTaAQGVm9qkt-Y5:-MUiXPTaAQGVm9qkt-Y6:batx2qi) ([raw file](https://github.com/pmem/rpma/blob/c5fe12a09b9f7b097314eee6f9c68cd006c88f7b/tools/perf/rpma_fio_bench.sh#L106)):*
> ```Shell
> 	case "$3" in
> 	randwrite|read|randread|rw|randrw)
> 		usage "The 'aof' mode does not support the '$3' operation for now."
> ```

~~for now~~
___
*[tools/perf/rpma_fio_bench.sh, line 150 at r1](https://reviewable.io/reviews/pmem/rpma/914#-MUiXdKM1Jwp6YyUTG9R:-MUiXdKM1Jwp6YyUTG9S:b-bozfci) ([raw file](https://github.com/pmem/rpma/blob/c5fe12a09b9f7b097314eee6f9c68cd006c88f7b/tools/perf/rpma_fio_bench.sh#L150)):*
> ```Shell
> 		fi
> 		;;
> 	gpspm|aof)
> ```

**Info**: AOF will support GPSPM-like and APM-like modes as well.
___
*[tools/perf/rpma_fio_bench.sh, line 447 at r1](https://reviewable.io/reviews/pmem/rpma/914#-MUiY-dC70ldu-W426si:-MUiY-dC70ldu-W426sj:b2f9tvq) ([raw file](https://github.com/pmem/rpma/blob/c5fe12a09b9f7b097314eee6f9c68cd006c88f7b/tools/perf/rpma_fio_bench.sh#L447)):*
> ```Shell
> 		fi
> 
> 		if [ "$p" == "aof" ]; then
> ```

```sh
elif [ "$p" == "aof" ]; then
```
___
*[tools/perf/rpma_fio_bench.sh, line 449 at r1](https://reviewable.io/reviews/pmem/rpma/914#-MUiYVdW349H7VAlrSPL:-MUiYVdW349H7VAlrSPM:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/c5fe12a09b9f7b097314eee6f9c68cd006c88f7b/tools/perf/rpma_fio_bench.sh#L449)):*
> ```Shell
> 		if [ "$p" == "aof" ]; then
> 			case "$o" in
> 			randwrite|read|randread|rw|randrw)
> ```

.
___
*[tools/perf/fio_jobs/librpma_aof-server.fio, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/914#-MUiZMLGD-UUpJZK-iYK:-MUiZMLGD-UUpJZK-iYL:b-ytja9m) ([raw file](https://github.com/pmem/rpma/blob/c5fe12a09b9f7b097314eee6f9c68cd006c88f7b/tools/perf/fio_jobs/librpma_aof-server.fio#L17)):*
> ```
> # When the client is done it sends the termination notice to the server's thread.
> 
> [server]
> ```

```
mode = sw # XXX
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/914)* status: 0 of 7 files reviewed, 7 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/rpma_fio_bench.sh, line 26 at r1](https://reviewable.io/reviews/pmem/rpma/914#-MUiWXju7YGeXOdWTZ5W:-MUlnnQi2QoKjFJ956DF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c5fe12a09b9f7b097314eee6f9c68cd006c88f7b/tools/perf/rpma_fio_bench.sh#L26)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

> ... does not support the 'read', 'randread', 'randwrite', 'rw' and 'randrw' operations.

~~for now~~ seems a bit misleading here since e.g. randwrite won't be supported.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 99 at r1](https://reviewable.io/reviews/pmem/rpma/914#-MUiYEo6908cQKRw_hrI:-MUloM7qEuGijzzEyRmp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c5fe12a09b9f7b097314eee6f9c68cd006c88f7b/tools/perf/rpma_fio_bench.sh#L99)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please keep them in the same order as we enumerate in the help.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 105 at r1](https://reviewable.io/reviews/pmem/rpma/914#-MUiYSbc1DsUKCDECHs6:-MUloQi9-57Kg-da7gke:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c5fe12a09b9f7b097314eee6f9c68cd006c88f7b/tools/perf/rpma_fio_bench.sh#L105)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

order.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 106 at r1](https://reviewable.io/reviews/pmem/rpma/914#-MUiXPTaAQGVm9qkt-Y5:-MUloTqt9B4OZMGhbZDJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c5fe12a09b9f7b097314eee6f9c68cd006c88f7b/tools/perf/rpma_fio_bench.sh#L106)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

~~for now~~
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 447 at r1](https://reviewable.io/reviews/pmem/rpma/914#-MUiY-dC70ldu-W426si:-MUloeV84PN_DB4nLYed:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c5fe12a09b9f7b097314eee6f9c68cd006c88f7b/tools/perf/rpma_fio_bench.sh#L447)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```sh
elif [ "$p" == "aof" ]; then
```
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 449 at r1](https://reviewable.io/reviews/pmem/rpma/914#-MUiYVdW349H7VAlrSPL:-MUlojdO7OczdFKGSR7o:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c5fe12a09b9f7b097314eee6f9c68cd006c88f7b/tools/perf/rpma_fio_bench.sh#L449)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/fio_jobs/librpma_aof-server.fio, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/914#-MUiZMLGD-UUpJZK-iYK:-MUmsS8i7tQxMAXrglqb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c5fe12a09b9f7b097314eee6f9c68cd006c88f7b/tools/perf/fio_jobs/librpma_aof-server.fio#L17)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```
mode = sw # XXX
```
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/914)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/rpma_fio_bench.sh, line 103 at r2](https://reviewable.io/reviews/pmem/rpma/914#-MUmxFWgC1mCP0br0t2x:-MUmxFWgC1mCP0br0t2y:b-2djifg) ([raw file](https://github.com/pmem/rpma/blob/ea24d5fc681ef2ef2c8b64fe579b244c41315a75/tools/perf/rpma_fio_bench.sh#L103)):*
> ```Shell
> 		;;
> 	esac
> elif [ "$2" == "aof_sw" ] || [ "$2" == "aof_hw" ]; then
> ```

**FYI**: You can also use `-o` for logical OR.

Ref: https://tldp.org/LDP/Bash-Beginners-Guide/html/sect_07_01.html#tab_07_02
___
*[tools/perf/rpma_fio_bench.sh, line 150 at r2](https://reviewable.io/reviews/pmem/rpma/914#-MUmxUzZ2Fi8MOMryzdj:-MUmxUzZ2Fi8MOMryzdk:bipnadt) ([raw file](https://github.com/pmem/rpma/blob/ea24d5fc681ef2ef2c8b64fe579b244c41315a75/tools/perf/rpma_fio_bench.sh#L150)):*
> ```Shell
> 		fi
> 		;;
> 	gpspm|aof_sw)
> ```

I like how having `aof_sw` and `aof_hw` nicely fits into our current codebase. Nice job.
___
*[tools/perf/rpma_fio_bench.sh, line 209 at r2](https://reviewable.io/reviews/pmem/rpma/914#-MUmxkc26O9fUfmuOyrz:-MUmxkc26O9fUfmuOys-:bhp2eih) ([raw file](https://github.com/pmem/rpma/blob/ea24d5fc681ef2ef2c8b64fe579b244c41315a75/tools/perf/rpma_fio_bench.sh#L209)):*
> ```Shell
> 		ITERATIONS=${#BLOCK_SIZE[@]}
> 		NAME_SUFFIX=th${THREADS}_dp${DEPTH}
> 		SYNC=0
> ```

I think you have assigned `SYNC` completely upside down. ;-)
___
*[tools/perf/rpma_fio_bench.sh, line 449 at r2](https://reviewable.io/reviews/pmem/rpma/914#-MUmy4lZC8eZIJYzQfm2:-MUmy4lZC8eZIJYzQfm3:bxnibe7) ([raw file](https://github.com/pmem/rpma/blob/ea24d5fc681ef2ef2c8b64fe579b244c41315a75/tools/perf/rpma_fio_bench.sh#L449)):*
> ```Shell
> 				;;
> 			esac
> 		elif [ "$p" == "aof_sw" ] || [ "$p" == "aof_hw" ]; then
> ```

`-o`. Just saying. ;-)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/914)* status: 3 of 7 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/rpma_fio_bench.sh, line 103 at r2](https://reviewable.io/reviews/pmem/rpma/914#-MUmxFWgC1mCP0br0t2x:-MUn0MtI0fUrCiQAYTuT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ea24d5fc681ef2ef2c8b64fe579b244c41315a75/tools/perf/rpma_fio_bench.sh#L103)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

**FYI**: You can also use `-o` for logical OR.

Ref: https://tldp.org/LDP/Bash-Beginners-Guide/html/sect_07_01.html#tab_07_02
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 209 at r2](https://reviewable.io/reviews/pmem/rpma/914#-MUmxkc26O9fUfmuOyrz:-MUn0vZF0SC8nLXMgevF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ea24d5fc681ef2ef2c8b64fe579b244c41315a75/tools/perf/rpma_fio_bench.sh#L209)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think you have assigned `SYNC` completely upside down. ;-)
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/914)* status: 4 of 7 files reviewed, all discussions resolved

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r2, 1 of 1 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/914)* status: all files reviewed, 4 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/rpma_fio_bench.sh, line 26 at r4](https://reviewable.io/reviews/pmem/rpma/914#-MUn9otB9YH1xBNdhezb:-MUn9otC08vsBUogersr:b-2fb1ms) ([raw file](https://github.com/pmem/rpma/blob/8881c09fd356b60113ee3fae4c73af0481981fbe/tools/perf/rpma_fio_bench.sh#L26)):*
> ```
> mode does not
> ```

`modes do not`
___
*[tools/perf/rpma_fio_bench.sh, line 99 at r4](https://reviewable.io/reviews/pmem/rpma/914#-MUnA5DZB4CuHNpqjxtq:-MUnA5DZB4CuHNpqjxtr:b-k89mc8) ([raw file](https://github.com/pmem/rpma/blob/8881c09fd356b60113ee3fae4c73af0481981fbe/tools/perf/rpma_fio_bench.sh#L99)):*
> ```
> elif [ "$2" == "gpspm" ]; then
> 	case "$3" in
> 	read|randread|rw|randrw)
> ```

This change is not related to the AOF mode.
___
*[tools/perf/fio_jobs/librpma_aof_hw-client.fio, line 21 at r4](https://reviewable.io/reviews/pmem/rpma/914#-MUnBHN9-ObMZ8h_FmG3:-MUnBHN9-ObMZ8h_FmG4:b-8f9shk) ([raw file](https://github.com/pmem/rpma/blob/8881c09fd356b60113ee3fae4c73af0481981fbe/tools/perf/fio_jobs/librpma_aof_hw-client.fio#L21)):*
> ```
> rwmixread=70 # valid only for the 'rw' and 'randrw' readwrite modes
> ```

not valid in the AOF mode
___
*[tools/perf/fio_jobs/librpma_aof_sw-client.fio, line 21 at r4](https://reviewable.io/reviews/pmem/rpma/914#-MUnBQRC8QuTPLOdfuoX:-MUnBQRC8QuTPLOdfuoY:b-g5pai6) ([raw file](https://github.com/pmem/rpma/blob/8881c09fd356b60113ee3fae4c73af0481981fbe/tools/perf/fio_jobs/librpma_aof_sw-client.fio#L21)):*
> ```
> rwmixread=70 # valid only for the 'rw' and 'randrw' readwrite modes
> ```

.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/914)* status: all files reviewed, 5 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[tools/perf/fio_jobs/librpma_aof_hw-client.fio, line 21 at r4](https://reviewable.io/reviews/pmem/rpma/914#-MUnBHN9-ObMZ8h_FmG3:-MUnCI8D5OGKFGUqHxqz:b6zrrk4) ([raw file](https://github.com/pmem/rpma/blob/8881c09fd356b60113ee3fae4c73af0481981fbe/tools/perf/fio_jobs/librpma_aof_hw-client.fio#L21)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> rwmixread=70 # valid only for the 'rw' and 'randrw' readwrite modes
> ```

not valid in the AOF mode
</blockquote></details>

Good catch!
___
*[tools/perf/fio_jobs/librpma_aof_hw-server.fio, line 23 at r4](https://reviewable.io/reviews/pmem/rpma/914#-MUnCtGi5AtR5oh1NLHj:-MUnCtGi5AtR5oh1NLHk:b5dxwih) ([raw file](https://github.com/pmem/rpma/blob/8881c09fd356b60113ee3fae4c73af0481981fbe/tools/perf/fio_jobs/librpma_aof_hw-server.fio#L23)):*
> ```
> direct_write_to_pmem=${direct_write_to_pmem}
> numjobs=${numjobs}
> iodepth=${iodepth}
> ```

Not needed for the hw mode.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/914)* status: 3 of 7 files reviewed, 5 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/rpma_fio_bench.sh, line 26 at r4](https://reviewable.io/reviews/pmem/rpma/914#-MUn9otB9YH1xBNdhezb:-MUnDxwZ1mOl2C9slMdi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8881c09fd356b60113ee3fae4c73af0481981fbe/tools/perf/rpma_fio_bench.sh#L26)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> mode does not
> ```

`modes do not`
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 99 at r4](https://reviewable.io/reviews/pmem/rpma/914#-MUnA5DZB4CuHNpqjxtq:-MUnT7fMDevY6bshFrng:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8881c09fd356b60113ee3fae4c73af0481981fbe/tools/perf/rpma_fio_bench.sh#L99)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> elif [ "$2" == "gpspm" ]; then
> 	case "$3" in
> 	read|randread|rw|randrw)
> ```

This change is not related to the AOF mode.
</blockquote></details>

Done.
___
*[tools/perf/fio_jobs/librpma_aof_hw-client.fio, line 21 at r4](https://reviewable.io/reviews/pmem/rpma/914#-MUnBHN9-ObMZ8h_FmG3:-MUnEExt6pjQ9vj1J4He:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8881c09fd356b60113ee3fae4c73af0481981fbe/tools/perf/fio_jobs/librpma_aof_hw-client.fio#L21)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Good catch!
</blockquote></details>

Done.
___
*[tools/perf/fio_jobs/librpma_aof_sw-client.fio, line 21 at r4](https://reviewable.io/reviews/pmem/rpma/914#-MUnBQRC8QuTPLOdfuoX:-MUnETFm02nU-NMKrpKf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8881c09fd356b60113ee3fae4c73af0481981fbe/tools/perf/fio_jobs/librpma_aof_sw-client.fio#L21)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> rwmixread=70 # valid only for the 'rw' and 'randrw' readwrite modes
> ```

.
</blockquote></details>

Done.
___
*[tools/perf/fio_jobs/librpma_aof_hw-server.fio, line 23 at r4](https://reviewable.io/reviews/pmem/rpma/914#-MUnCtGi5AtR5oh1NLHj:-MUnENXsA0tCw9-VFy63:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8881c09fd356b60113ee3fae4c73af0481981fbe/tools/perf/fio_jobs/librpma_aof_hw-server.fio#L23)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not needed for the hw mode.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/914)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/rpma_fio_bench.sh, line 99 at r4](https://reviewable.io/reviews/pmem/rpma/914#-MUnA5DZB4CuHNpqjxtq:-MUnUtfoCv5WLzHaBal2:bvxvwsh) ([raw file](https://github.com/pmem/rpma/blob/8881c09fd356b60113ee3fae4c73af0481981fbe/tools/perf/rpma_fio_bench.sh#L99)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Please submit a separate PR for this fix

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/914#-:-MUnV9dN5BbE_hWWLUPu:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/914)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/rpma_fio_bench.sh, line 99 at r4](https://reviewable.io/reviews/pmem/rpma/914#-MUnA5DZB4CuHNpqjxtq:-MUnX6795EY_s3CsFDmz:b-8sbesf) ([raw file](https://github.com/pmem/rpma/blob/8881c09fd356b60113ee3fae4c73af0481981fbe/tools/perf/rpma_fio_bench.sh#L99)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please submit a separate PR for this fix
</blockquote></details>

#915

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/914#-:-MUqm14m595wG8t47hdK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
