### PR TITLE
common: remove unneeded dependencies for ndctl and pmdk from Debian 9

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/867)

### CODE REVIEW

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/867#-:-MT6GhspAU55CZTUx1X5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Comment by ldorau** [comment]
The rebuild of Debian 9 docker image:
https://github.com/ldorau/rpma/runs/1863957173

**Comment by ldorau** [comment]
The rebuild of Debian 9 docker image and build:
https://github.com/ldorau/rpma/actions/runs/551685716

**Comment by ldorau** [comment]
Changed commit's name

**Comment by ldorau** [comment]
Incorporated into https://github.com/pmem/rpma/pull/871

**Pull request closed without merging**
