### PR TITLE
examples: make all examples comply the new chars line limit

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1984)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 24 of 24 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1984)* status: all files reviewed, 5 unresolved discussions (waiting on @haichangsi)

___
*[`examples/09-flush-to-persistent-GPSPM/client.c` line 209 at r1](https://reviewable.io/reviews/pmem/rpma/1984#-N9GMajK0zN03CgAUsE6:-N9GMajK0zN03CgAUsE7:b-2or7gt) ([raw file](https://github.com/pmem/rpma/blob/b6f3062a2ac2be8091f2c879b111a0a754e11e77/examples/09-flush-to-persistent-GPSPM/client.c#L209)):*
> ```C
> 	if (wc.opcode != IBV_WC_SEND) {
> 		ret = -1;
> 		(void) fprintf(stderr,
> ```

one line



_Code quote:_
```C
		(void) fprintf(stderr,
				"unexpected wc.opcode value "
```
___
*[`examples/09-flush-to-persistent-GPSPM/client.c` line 234 at r1](https://reviewable.io/reviews/pmem/rpma/1984#-N9GMdlk1zquyJlUbPJg:-N9GMdlk1zquyJlUbPJh:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/b6f3062a2ac2be8091f2c879b111a0a754e11e77/examples/09-flush-to-persistent-GPSPM/client.c#L234)):*
> ```C
> 	if (wc.opcode != IBV_WC_RECV) {
> 		ret = -1;
> 		(void) fprintf(stderr,
> ```

.



_Code quote:_
```C
		(void) fprintf(stderr,
				"unexpected wc.opcode value "
```
___
*[`examples/09-flush-to-persistent-GPSPM/server.c` line 210 at r1](https://reviewable.io/reviews/pmem/rpma/1984#-N9GMoI8BipJO8af9iA4:-N9GMoI8BipJO8af9iA5:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/b6f3062a2ac2be8091f2c879b111a0a754e11e77/examples/09-flush-to-persistent-GPSPM/server.c#L210)):*
> ```C
> 	if (wc.opcode != IBV_WC_RECV) {
> 		ret = -1;
> 		(void) fprintf(stderr,
> ```

.



_Code quote:_
```C
		(void) fprintf(stderr,
				"unexpected wc.opcode value "
```
___
*[`examples/09-flush-to-persistent-GPSPM/server.c` line 273 at r1](https://reviewable.io/reviews/pmem/rpma/1984#-N9GMrS6BfYGky1l6llS:-N9GMrS6BfYGky1l6llT:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/b6f3062a2ac2be8091f2c879b111a0a754e11e77/examples/09-flush-to-persistent-GPSPM/server.c#L273)):*
> ```C
> 	if (wc.opcode != IBV_WC_SEND) {
> 		ret = -1;
> 		(void) fprintf(stderr,
> ```

.



_Code quote:_
```C
		(void) fprintf(stderr,
				"unexpected wc.opcode value "
```
___
*[`examples/09scch-flush-to-persistent-GPSPM/client.c` line 210 at r1](https://reviewable.io/reviews/pmem/rpma/1984#-N9GN-zPDm_GrNYShz8k:-N9GN-zPDm_GrNYShz8l:b-pq8bou) ([raw file](https://github.com/pmem/rpma/blob/b6f3062a2ac2be8091f2c879b111a0a754e11e77/examples/09scch-flush-to-persistent-GPSPM/client.c#L210)):*
> ```C
> 	}
> 	if (flush_resp->op_context != (uint64_t)FLUSH_ID) {
> 		(void) fprintf(stderr,
> ```

one line ?



_Code quote:_
```C
		(void) fprintf(stderr,
				"unexpected flush_resp->op_context value "
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1984)* status: 21 of 24 files reviewed, 5 unresolved discussions (waiting on @ldorau)

___
*[`examples/09-flush-to-persistent-GPSPM/client.c` line 209 at r1](https://reviewable.io/reviews/pmem/rpma/1984#-N9GMajK0zN03CgAUsE6:-N9GW9z54g8t5_L8Kweb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b6f3062a2ac2be8091f2c879b111a0a754e11e77/examples/09-flush-to-persistent-GPSPM/client.c#L209)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

one line
</blockquote></details>

Done.
___
*[`examples/09-flush-to-persistent-GPSPM/client.c` line 234 at r1](https://reviewable.io/reviews/pmem/rpma/1984#-N9GMdlk1zquyJlUbPJg:-N9GViEcCGirk4XrOyNa:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b6f3062a2ac2be8091f2c879b111a0a754e11e77/examples/09-flush-to-persistent-GPSPM/client.c#L234)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`examples/09-flush-to-persistent-GPSPM/server.c` line 210 at r1](https://reviewable.io/reviews/pmem/rpma/1984#-N9GMoI8BipJO8af9iA4:-N9GVpnA4b7upD5l1euG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b6f3062a2ac2be8091f2c879b111a0a754e11e77/examples/09-flush-to-persistent-GPSPM/server.c#L210)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`examples/09-flush-to-persistent-GPSPM/server.c` line 273 at r1](https://reviewable.io/reviews/pmem/rpma/1984#-N9GMrS6BfYGky1l6llS:-N9GVtU0DwQ-_qwee1Fk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b6f3062a2ac2be8091f2c879b111a0a754e11e77/examples/09-flush-to-persistent-GPSPM/server.c#L273)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`examples/09scch-flush-to-persistent-GPSPM/client.c` line 210 at r1](https://reviewable.io/reviews/pmem/rpma/1984#-N9GN-zPDm_GrNYShz8k:-N9GVy1Q6ZYcIQ8PQNYn:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b6f3062a2ac2be8091f2c879b111a0a754e11e77/examples/09scch-flush-to-persistent-GPSPM/client.c#L210)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

one line ?
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1984)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1984#-:-N9GZ0hX2wb5sl5_3wwR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
