### PR TITLE
tools: perf: document lib.remote_cmd

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1386)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1386)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1386)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1386)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1386#-MpvMvAO39o5XMvWlNXT:-MpvMvAO39o5XMvWlNXU:b-loppan) (no related file):*
************* Module lib.bench
/rpma/tools/perf/lib/bench.py:27:18: E1120: No value for argument 'env' in classmethod call (no-value-for-parameter)
/rpma/tools/perf/lib/bench.py:38:16: E1120: No value for argument 'env' in classmethod call (no-value-for-parameter)
************* Module lib.benchmark.runner.fio
/rpma/tools/perf/lib/benchmark/runner/fio.py:34:17: E1120: No value for argument 'env' in classmethod call (no-value-for-parameter)
************* Module lib.benchmark.runner.ib_read
/rpma/tools/perf/lib/benchmark/runner/ib_read.py:40:17: E1120: No value for argument 'env' in classmethod call (no-value-for-parameter)

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1386)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/lib/remote_cmd.py, line 64 at r2](https://reviewable.io/reviews/pmem/rpma/1386#-MpvN-1L43AvCIMUV8-n:-MpvN-1L43AvCIMUV8-o:by36rtf) ([raw file](https://github.com/pmem/rpma/blob/c279caae2da4d39790634f2c44493b5ed23fdb35/tools/perf/lib/remote_cmd.py#L64)):*
> ```
> bool =False
> ```

`bool = False`

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1386)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1386)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ldorau and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1386#-MpvGJIk3MbKWnXD2FxS:-MpvNNVe8FHmRgKBtaSz:b-896fix) (no related file):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

@janekmi please rebase
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1386#-MpvMvAO39o5XMvWlNXT:-MpvNNre3X1uU6mx06tQ:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

************* Module lib.bench
/rpma/tools/perf/lib/bench.py:27:18: E1120: No value for argument 'env' in classmethod call (no-value-for-parameter)
/rpma/tools/perf/lib/bench.py:38:16: E1120: No value for argument 'env' in classmethod call (no-value-for-parameter)
************* Module lib.benchmark.runner.fio
/rpma/tools/perf/lib/benchmark/runner/fio.py:34:17: E1120: No value for argument 'env' in classmethod call (no-value-for-parameter)
************* Module lib.benchmark.runner.ib_read
/rpma/tools/perf/lib/benchmark/runner/ib_read.py:40:17: E1120: No value for argument 'env' in classmethod call (no-value-for-parameter)

</blockquote></details>

Done.

---
___
*[tools/perf/lib/remote_cmd.py, line 64 at r2](https://reviewable.io/reviews/pmem/rpma/1386#-MpvN-1L43AvCIMUV8-n:-MpvNPUR6HXDi9sY5Vj0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c279caae2da4d39790634f2c44493b5ed23fdb35/tools/perf/lib/remote_cmd.py#L64)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> bool =False
> ```

`bool = False`
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1386#-:-MpvNrM-06pK50RsXWH-:bnfp4nl)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1386)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1386#-:-MpvUDY506E54z2TmhCG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
