### PR TITLE
common: add Ubuntu 21.10 to Nightly workflow

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #1410 

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1309)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
The previous error has been fixed.
There is another issue now:
https://github.com/pmem/rpma/runs/4442519890

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1309#-:-MqJbCw08SMtEjqti23P:b-1e02i7)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @grom72 and @janekmi)

**Comment by ldorau** [comment]
See: https://github.com/pmem/rpma/issues/1397

**Review by grom72 — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1309)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Comment by ldorau** [comment]
> See: #1397

All issues fixed. The build pass now:
https://github.com/ldorau/rpma/runs/4482591269

**Review by osalyk — COMMENTED** [review]
> Reviewed 4 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1309)* status: 6 of 7 files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1309#-:-Mqa7YVk2I7VvoIDzrXX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 3 files at r3, 1 of 5 files at r4, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1309#-:-MqmkMHlCdZ3IazvWWKj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
