### PR TITLE
rpma: make other internal API files comply with the new chars line limit

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1994)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 11 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1994)* status: 11 of 12 files reviewed, all discussions resolved (waiting on @ldorau and @osalyk)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1994#-:-NA9V72i7HXC0jQI9HAK:bnfp4nl)* status: 11 of 12 files reviewed, all discussions resolved (waiting on @ldorau and @osalyk)

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1994)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau and @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1994#-:-NA9VSmU0rcMSiQj0Lc_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1994#-:-NA9VimTBMNH-BNNrPEg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1994)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
