### PR TITLE
doc: add documentation for v0.9.0

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/537)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
> Reviewed 2 of 118 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/537)* status: 2 of 118 files reviewed, all discussions resolved

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 63 of 118 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/537)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/537#-MIdtMhX4TfvtoV0FCiH:-MIdtMhX4TfvtoV0FCiI:b-s0h620) (no related file):*
It seems you should also modify _layouts/manual.html. Can you push this branch as yours gh-pages so we can verify if it works correctly?

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/537)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/537#-MIdtMhX4TfvtoV0FCiH:-MIjzvXxATbbeJr_cx5t:bxzudge) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It seems you should also modify _layouts/manual.html. Can you push this branch as yours gh-pages so we can verify if it works correctly?
</blockquote></details>

Pushed

---

**Comment by ldorau** [comment]
It works: https://ldorau.github.io/rpma/

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/537)* status: 0 of 122 files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/537#-MIdtMhX4TfvtoV0FCiH:-MIs1M-w9CCr-tkpgcUG:b-umyddp) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Pushed
</blockquote></details>

It works: https://ldorau.github.io/rpma/

---

**Review by osalyk — COMMENTED** [review]
> Reviewed 6 of 122 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/537)* status: 6 of 122 files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/537)* status: 6 of 122 files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/537#-MIdtMhX4TfvtoV0FCiH:-MIx6X0c1wKl2vITe_Qi:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It works: https://ldorau.github.io/rpma/
</blockquote></details>

Done.

---

**Review by ldorau — COMMENTED** [review]
@grom72 @osalyk please review

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/537#-:-MJ3Nf5ABcflPBFJJAPr:bg7id4e)* status: 1 of 59 files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/537)* status: 1 of 59 files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/537#-MIdtMhX4TfvtoV0FCiH:-MJ5jI5a4Amqp1yFslH1:b-fhrp90) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Fixed and verified.

---

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 116 of 122 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/537#-:-MJ6D1n07tcznzMtWz-U:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/537)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[index.md, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/537#-MJ6PU4YADXAOVI5aEyt:-MJ6PU4YADXAOVI5aEyu:bvn0e37) ([raw file](https://github.com/pmem/rpma/blob/318188436a50a61d58173763fc1f8e3bac38f206/index.md#L15)):*
> ```Markdown
> 
> * for the current [master](./master/librpma.7.html)
> * for [v0.9.0](./releases/v0.9.0/librpma.7.html)
> ```

Why you propose to have only one documentation where you are adding a 0.9.0 specific?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/537)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[index.md, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/537#-MJ6PU4YADXAOVI5aEyt:-MJ6ZTCf6ko_-AMQY9ZT:b-m6dagh) ([raw file](https://github.com/pmem/rpma/blob/318188436a50a61d58173763fc1f8e3bac38f206/index.md#L15)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Why you propose to have only one documentation where you are adding a 0.9.0 specific?
</blockquote></details>

Because both links:

./manpages/master/librpma.7.html
and
./manpages/v0.9.0/librpma.7.html

directs to the same page, which have both versions in the menu. PMDK also has only one link (to master) which directs to all versions.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/537)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[index.md, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/537#-MJ6PU4YADXAOVI5aEyt:-MJ6_jPx0ddnweBWje54:bo3fej0) ([raw file](https://github.com/pmem/rpma/blob/318188436a50a61d58173763fc1f8e3bac38f206/index.md#L15)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Because both links:

./manpages/master/librpma.7.html
and
./manpages/v0.9.0/librpma.7.html

directs to the same page, which have both versions in the menu. PMDK also has only one link (to master) which directs to all versions.
</blockquote></details>

See:
https://ldorau.github.io/rpma/manpages/master/librpma.7.html
and
https://ldorau.github.io/rpma/manpages/v0.9.0/librpma.7.html

shows the same web page.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/537)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[index.md, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/537#-MJ6PU4YADXAOVI5aEyt:-MJ6awKr3atpMvev6100:b-2y05w) ([raw file](https://github.com/pmem/rpma/blob/318188436a50a61d58173763fc1f8e3bac38f206/index.md#L15)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

See:
https://ldorau.github.io/rpma/manpages/master/librpma.7.html
and
https://ldorau.github.io/rpma/manpages/v0.9.0/librpma.7.html

shows the same web page.
</blockquote></details>

OK, but later these pages can be different :-) I will add two links

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/537)* status: 59 of 60 files reviewed, 1 unresolved discussion (waiting on @janekmi and @osalyk)

___
*[index.md, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/537#-MJ6PU4YADXAOVI5aEyt:-MJ6bCZt1lwZvBJje5Uk:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/318188436a50a61d58173763fc1f8e3bac38f206/index.md#L15)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK, but later these pages can be different :-) I will add two links
</blockquote></details>

Done

**Review by ldorau — COMMENTED** [review]
@grom72 please review

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/537#-:-MJT7sO8EasLQF4CgYXw:bgjoyzx)* status: 59 of 60 files reviewed, 1 unresolved discussion (waiting on @janekmi and @osalyk)

___
*[index.md, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/537#-MJ6PU4YADXAOVI5aEyt:-MJT7pWy5q7W7uGIwN0a:b-3p17t8) ([raw file](https://github.com/pmem/rpma/blob/318188436a50a61d58173763fc1f8e3bac38f206/index.md#L15)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done
</blockquote></details>

@janekmi ping

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/537)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/537#-:-MJT9h2b9KQn_YdAa3q5:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — COMMENTED** [review]
@janekmi please review

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/537#-:-MJlUG-42YHghJe2rn5j:b-f79qgk)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 122 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/537)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[index.md, line 14 at r4](https://reviewable.io/reviews/pmem/rpma/537#-MJlpYS7Ag5PwkTEJlxw:-MJlpYS7Ag5PwkTEJlxx:b-5fr4tk) ([raw file](https://github.com/pmem/rpma/blob/0fc22e859a3937f3374281ab082a368249a9dd02/index.md#L14)):*
> ```Markdown
> The documentation is available:
> 
> * for the current [master](./manpages/master/librpma.7.html)
> ```

For an unknown reason, this single webpage is not generating at all (404).
I recommend removing all `.html` from URLs. Even this address works without the extension.
___
*[index.md, line 15 at r4](https://reviewable.io/reviews/pmem/rpma/537#-MJlneCT5WyduTlX9BfZ:-MJlneCUBzdgdqtQ7SJA:b-9dbpwt) ([raw file](https://github.com/pmem/rpma/blob/0fc22e859a3937f3374281ab082a368249a9dd02/index.md#L15)):*
> ```Markdown
> 
> * for the current [master](./manpages/master/librpma.7.html)
> * for [v0.9.0](./manpages/v0.9.0/librpma.7.html)
> ```

The documentation is available **for**:
- the current master
- v0.9.0

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 57 of 122 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/537)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[index.md, line 14 at r4](https://reviewable.io/reviews/pmem/rpma/537#-MJlpYS7Ag5PwkTEJlxw:-MJlrjzp9OI8IUTSzqUX:b-gyhcgx) ([raw file](https://github.com/pmem/rpma/blob/0fc22e859a3937f3374281ab082a368249a9dd02/index.md#L14)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

For an unknown reason, this single webpage is not generating at all (404).
I recommend removing all `.html` from URLs. Even this address works without the extension.
</blockquote></details>

Note you have to fix this also here: https://github.com/ldorau/rpma/blob/gh-pages-for-v0.9.0/_layouts/manual.html#L42 so the script won't add an extension to the generated list.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/537)* status: 59 of 60 files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[index.md, line 14 at r4](https://reviewable.io/reviews/pmem/rpma/537#-MJlpYS7Ag5PwkTEJlxw:-MJz_hrU50WrF8UnSkfe:b-1qdx4r) ([raw file](https://github.com/pmem/rpma/blob/0fc22e859a3937f3374281ab082a368249a9dd02/index.md#L14)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Note you have to fix this also here: https://github.com/ldorau/rpma/blob/gh-pages-for-v0.9.0/_layouts/manual.html#L42 so the script won't add an extension to the generated list.
</blockquote></details>

It is generated, all is OK, see here:

https://ldorau.github.io/rpma/

and

https://ldorau.github.io/rpma/manpages/master/librpma.7.html
___
*[index.md, line 15 at r4](https://reviewable.io/reviews/pmem/rpma/537#-MJlneCT5WyduTlX9BfZ:-MJz_W6xEiots_no6y3Z:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0fc22e859a3937f3374281ab082a368249a9dd02/index.md#L15)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The documentation is available **for**:
- the current master
- v0.9.0
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/537#-:-MJzqHb25b_FcP4S13bZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
