### PR TITLE
rpma: implement rpma_conn_apply_remote_peer_cfg()

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/401)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
:goat: 

> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/401#-:-MHBsYDZ3ZPao7kPzdIn:bdycpsm)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/401#-:-MHF2x9w144lmAgtmO5-:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/401)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/conn.c, line 373 at r2](https://reviewable.io/reviews/pmem/rpma/401#-MHF37CH059WNL47QCZI:-MHF37CH059WNL47QCZJ:b-x2poul) ([raw file](https://github.com/pmem/rpma/blob/a2215214cdaafd621cee1f6f71d963d03bd40144/src/conn.c#L373)):*
> ```
> direct write to pmem is NOT supported
> ```
"Connection does not support Flush to persistency. Check if remote node supports direct write to persistent memory."

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/401)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[src/conn.c, line 373 at r2](https://reviewable.io/reviews/pmem/rpma/401#-MHF37CH059WNL47QCZI:-MHFFPnbBfek9YorZM9Y:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a2215214cdaafd621cee1f6f71d963d03bd40144/src/conn.c#L373)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> direct write to pmem is NOT supported
> ```
"Connection does not support Flush to persistency. Check if remote node supports direct write to persistent memory."
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 7 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/401)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 7 files at r1, 4 of 5 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/401)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[tests/unit/common/mocks-rpma-peer_cfg.h, line 11 at r3](https://reviewable.io/reviews/pmem/rpma/401#-MHLXCof0agjmPBEgZwx:-MHLXCof0agjmPBEgZwy:bknhbi6) ([raw file](https://github.com/pmem/rpma/blob/de25211b81270f7768bcb26ea537003adc773782/tests/unit/common/mocks-rpma-peer_cfg.h#L11)):*
> ```objc
> #define MOCKS_RPMA_PEER_CFG_H
> 
> #endif /* MOCKS_RPMA_PEER_CFG_H */
> ```

This header does not seem necessary. ;-)
___
*[tests/unit/common/mocks-rpma-peer_cfg.c, line 19 at r3](https://reviewable.io/reviews/pmem/rpma/401#-MHLYLsY3BlIlyMa2vLg:-MHLYLsY3BlIlyMa2vLh:b-4ox30u) ([raw file](https://github.com/pmem/rpma/blob/de25211b81270f7768bcb26ea537003adc773782/tests/unit/common/mocks-rpma-peer_cfg.c#L19)):*
> ```C
> int
> rpma_peer_cfg_get_direct_write_to_pmem(struct rpma_peer_cfg *pcfg,
> 		bool *supported)
> ```

I think we should have a test in which we:
- set a non defult supported value
- verify if it allows flushing to persistency

Possibly it will be another flush unit test.
___
*[tests/unit/common/mocks-rpma-peer_cfg.c, line 21 at r3](https://reviewable.io/reviews/pmem/rpma/401#-MHLYG1o4cfwPzby5nMP:-MHLYG1p0KlLMPp6gino:b-5pe4la) ([raw file](https://github.com/pmem/rpma/blob/de25211b81270f7768bcb26ea537003adc773782/tests/unit/common/mocks-rpma-peer_cfg.c#L21)):*
> ```C
> 		bool *supported)
> {
> 	assert_non_null(pcfg);
> ```

pcfg == RPMA_PEER_PCFG?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/401)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tests/unit/common/mocks-rpma-peer_cfg.h, line 11 at r3](https://reviewable.io/reviews/pmem/rpma/401#-MHLXCof0agjmPBEgZwx:-MHLchMZ3YlYmPZxEzY7:b-12jjdt) ([raw file](https://github.com/pmem/rpma/blob/de25211b81270f7768bcb26ea537003adc773782/tests/unit/common/mocks-rpma-peer_cfg.h#L11)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This header does not seem necessary. ;-)
</blockquote></details>

Right :-) Forgot to remove
___
*[tests/unit/common/mocks-rpma-peer_cfg.c, line 21 at r3](https://reviewable.io/reviews/pmem/rpma/401#-MHLYG1o4cfwPzby5nMP:-MHLeFNFDzQA1pRajRk9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/de25211b81270f7768bcb26ea537003adc773782/tests/unit/common/mocks-rpma-peer_cfg.c#L21)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

pcfg == RPMA_PEER_PCFG?
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/401)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

**Review by janekmi — COMMENTED** [review]
> Reviewed 5 of 5 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/401)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by janekmi — COMMENTED** [review]
> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/401)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/401)* status: 8 of 11 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[tests/unit/common/mocks-rpma-peer_cfg.c, line 19 at r3](https://reviewable.io/reviews/pmem/rpma/401#-MHLYLsY3BlIlyMa2vLg:-MHQP0vg8sxjUSK3xnP1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/de25211b81270f7768bcb26ea537003adc773782/tests/unit/common/mocks-rpma-peer_cfg.c#L19)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we should have a test in which we:
- set a non defult supported value
- verify if it allows flushing to persistency

Possibly it will be another flush unit test.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/401#-:-MHQUgVB0dkPXuhR3Teb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
