### PR TITLE
doc: add SEE ALSO section utils and peer

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/486)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/486)* status: 0 of 1 files reviewed, 10 unresolved discussions (waiting on @osalyk)

___
*[src/include/librpma.h, line 215 at r1](https://reviewable.io/reviews/pmem/rpma/486#-MIPVb0y2FjX0wLqZRzL:-MIPVb0y2FjX0wLqZRzM:b-x8ioek) ([raw file](https://github.com/pmem/rpma/blob/5961fd630ac45d524849947a8718f29d5244aac0/src/include/librpma.h#L215)):*
> ```objc
>  * SEE ALSO
>  *
>  * rpma_utils_ibv_context_is_odp_capable(3)
> ```

rpma_peer_new?
___
*[src/include/librpma.h, line 216 at r1](https://reviewable.io/reviews/pmem/rpma/486#-MIPVbqADj6HnfYkkJ98:-MIPVbqADj6HnfYkkJ99:b2nhz1u) ([raw file](https://github.com/pmem/rpma/blob/5961fd630ac45d524849947a8718f29d5244aac0/src/include/librpma.h#L216)):*
> ```objc
>  *
>  * rpma_utils_ibv_context_is_odp_capable(3)
>  * https://pmem.io/rpma/
> ```

and
___
*[src/include/librpma.h, line 252 at r1](https://reviewable.io/reviews/pmem/rpma/486#-MIPVgQL-O_SqkUUffm4:-MIPVgQL-O_SqkUUffm5:b2nhz1u) ([raw file](https://github.com/pmem/rpma/blob/5961fd630ac45d524849947a8718f29d5244aac0/src/include/librpma.h#L252)):*
> ```objc
>  *
>  * rpma_utils_get_ibv_context(3)
>  * https://pmem.io/rpma/
> ```

and
___
*[src/include/librpma.h, line 290 at r1](https://reviewable.io/reviews/pmem/rpma/486#-MIPW5sL8I_BFWQeoGEg:-MIPW5sL8I_BFWQeoGEh:ba2l3ae) ([raw file](https://github.com/pmem/rpma/blob/5961fd630ac45d524849947a8718f29d5244aac0/src/include/librpma.h#L290)):*
> ```objc
>  * rpma_peer_cfg_get_descriptor(3), rpma_peer_cfg_get_descriptor_size(3),
>  * rpma_peer_cfg_get_direct_write_to_pmem(3),
>  * rpma_peer_cfg_set_direct_write_to_pmem(3) and https://pmem.io/rpma/
> ```

rpma_conn_apply_remote_peer_cfg
___
*[src/include/librpma.h, line 322 at r1](https://reviewable.io/reviews/pmem/rpma/486#-MIPWaKMEFPdFRoyFB50:-MIPWaKN8r_r5KXUoKVo:b25vvwr) ([raw file](https://github.com/pmem/rpma/blob/5961fd630ac45d524849947a8718f29d5244aac0/src/include/librpma.h#L322)):*
> ```objc
>  * rpma_peer_cfg_get_descriptor_size(3),
>  * rpma_peer_cfg_get_direct_write_to_pmem(3), rpma_peer_cfg_new(3),
>  * rpma_peer_cfg_set_direct_write_to_pmem(3) and https://pmem.io/rpma/
> ```

I think we can treat rpma_peer_cfg_new() like a kind of a hub where you can find everything you can do with the entity. So maybe just refer the user to rpma_peer_cfg_new() and pmem.io?
___
*[src/include/librpma.h, line 355 at r1](https://reviewable.io/reviews/pmem/rpma/486#-MIPX2d1CjbD2sg9b3ze:-MIPX2d1CjbD2sg9b3zf:bjcp5zz) ([raw file](https://github.com/pmem/rpma/blob/5961fd630ac45d524849947a8718f29d5244aac0/src/include/librpma.h#L355)):*
> ```objc
>  * rpma_peer_cfg_get_descriptor(3), rpma_peer_cfg_get_descriptor_size(3),
>  * rpma_peer_cfg_get_direct_write_to_pmem(3), rpma_peer_cfg_new(3) and
>  * https://pmem.io/rpma/
> ```

.

- _new
- _get_direct (because it is a pair to _set)
- _get_descriptor (because it is the next step)
- _apply (because it is the purpose of _set)
- pmem.io
___
*[src/include/librpma.h, line 389 at r1](https://reviewable.io/reviews/pmem/rpma/486#-MIPXpAWCEQzBxMXvsnk:-MIPXpAX1cPHyOoQEczB:b-bw7bu7) ([raw file](https://github.com/pmem/rpma/blob/5961fd630ac45d524849947a8718f29d5244aac0/src/include/librpma.h#L389)):*
> ```objc
>  * rpma_peer_cfg_get_descriptor(3), rpma_peer_cfg_get_descriptor_size(3),
>  * rpma_peer_cfg_new(3), rpma_peer_cfg_set_direct_write_to_pmem(3) and
>  * https://pmem.io/rpma/
> ```

.

- _new
- _set
- _from_descriptor
- pmem.io
___
*[src/include/librpma.h, line 422 at r1](https://reviewable.io/reviews/pmem/rpma/486#-MIPYA9fCNHAT9jmR80U:-MIPYA9fCNHAT9jmR80V:befpawr) ([raw file](https://github.com/pmem/rpma/blob/5961fd630ac45d524849947a8718f29d5244aac0/src/include/librpma.h#L422)):*
> ```objc
>  * rpma_peer_cfg_get_descriptor_size(3),
>  * rpma_peer_cfg_get_direct_write_to_pmem(3), rpma_peer_cfg_new(3),
>  * rpma_peer_cfg_set_direct_write_to_pmem(3) and https://pmem.io/rpma/
> ```

- _new
- _from_descriptor
- pmem.io
___
*[src/include/librpma.h, line 455 at r1](https://reviewable.io/reviews/pmem/rpma/486#-MIPYKPe3d48Kwv8f1s6:-MIPYKPe3d48Kwv8f1s7:b97zdrt) ([raw file](https://github.com/pmem/rpma/blob/5961fd630ac45d524849947a8718f29d5244aac0/src/include/librpma.h#L455)):*
> ```objc
>  * rpma_peer_cfg_get_descriptor(3), rpma_peer_cfg_get_direct_write_to_pmem(3),
>  * rpma_peer_cfg_new(3), rpma_peer_cfg_set_direct_write_to_pmem(3) and
>  * https://pmem.io/rpma/
> ```

- _new
- _get_descriptor
- pmem.io (everwhere obviously)
___
*[src/include/librpma.h, line 492 at r1](https://reviewable.io/reviews/pmem/rpma/486#-MIPYWdR5d0qyK7NJgeR:-MIPYWdR5d0qyK7NJgeS:b-47417r) ([raw file](https://github.com/pmem/rpma/blob/5961fd630ac45d524849947a8718f29d5244aac0/src/include/librpma.h#L492)):*
> ```objc
>  * rpma_peer_cfg_get_descriptor_size(3),
>  * rpma_peer_cfg_get_direct_write_to_pmem(3), rpma_peer_cfg_new(3),
>  * rpma_peer_cfg_set_direct_write_to_pmem(3) and https://pmem.io/rpma/
> ```

- _new
- _get_descriptor
- _apply

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/486)* status: 0 of 1 files reviewed, 9 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 216 at r1](https://reviewable.io/reviews/pmem/rpma/486#-MIPVbqADj6HnfYkkJ98:-MIPgMddC3Hz0iE5YZYd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5961fd630ac45d524849947a8718f29d5244aac0/src/include/librpma.h#L216)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

and
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 252 at r1](https://reviewable.io/reviews/pmem/rpma/486#-MIPVgQL-O_SqkUUffm4:-MIPgPv_0jBD2VhLdeQE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5961fd630ac45d524849947a8718f29d5244aac0/src/include/librpma.h#L252)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

and
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 290 at r1](https://reviewable.io/reviews/pmem/rpma/486#-MIPW5sL8I_BFWQeoGEg:-MIPgaGu6cxiz1Wnrmz1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5961fd630ac45d524849947a8718f29d5244aac0/src/include/librpma.h#L290)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

rpma_conn_apply_remote_peer_cfg
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 322 at r1](https://reviewable.io/reviews/pmem/rpma/486#-MIPWaKMEFPdFRoyFB50:-MIPgjHa1CRomiCKAsyL:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5961fd630ac45d524849947a8718f29d5244aac0/src/include/librpma.h#L322)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we can treat rpma_peer_cfg_new() like a kind of a hub where you can find everything you can do with the entity. So maybe just refer the user to rpma_peer_cfg_new() and pmem.io?
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 355 at r1](https://reviewable.io/reviews/pmem/rpma/486#-MIPX2d1CjbD2sg9b3ze:-MIPh8oT2YrOTx_4xmzu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5961fd630ac45d524849947a8718f29d5244aac0/src/include/librpma.h#L355)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.

- _new
- _get_direct (because it is a pair to _set)
- _get_descriptor (because it is the next step)
- _apply (because it is the purpose of _set)
- pmem.io
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 389 at r1](https://reviewable.io/reviews/pmem/rpma/486#-MIPXpAWCEQzBxMXvsnk:-MIPhU0f-5HSZ2hdMePN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5961fd630ac45d524849947a8718f29d5244aac0/src/include/librpma.h#L389)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.

- _new
- _set
- _from_descriptor
- pmem.io
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 422 at r1](https://reviewable.io/reviews/pmem/rpma/486#-MIPYA9fCNHAT9jmR80U:-MIPhfCwC8ZNBKYLiC43:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5961fd630ac45d524849947a8718f29d5244aac0/src/include/librpma.h#L422)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

- _new
- _from_descriptor
- pmem.io
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 455 at r1](https://reviewable.io/reviews/pmem/rpma/486#-MIPYKPe3d48Kwv8f1s6:-MIPhsPOEBLwwXrltEC3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5961fd630ac45d524849947a8718f29d5244aac0/src/include/librpma.h#L455)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

- _new
- _get_descriptor
- pmem.io (everwhere obviously)
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 492 at r1](https://reviewable.io/reviews/pmem/rpma/486#-MIPYWdR5d0qyK7NJgeR:-MIPi1PsD4G7x9a_IFVE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5961fd630ac45d524849947a8718f29d5244aac0/src/include/librpma.h#L492)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

- _new
- _get_descriptor
- _apply
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/486)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[src/include/librpma.h, line 290 at r1](https://reviewable.io/reviews/pmem/rpma/486#-MIPW5sL8I_BFWQeoGEg:-MIPnx8c5ScvzDaMUGbN:b79i3zv) ([raw file](https://github.com/pmem/rpma/blob/5961fd630ac45d524849947a8718f29d5244aac0/src/include/librpma.h#L290)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I hate to say this: alph order, please.
___
*[src/include/librpma.h, line 355 at r1](https://reviewable.io/reviews/pmem/rpma/486#-MIPX2d1CjbD2sg9b3ze:-MIPoJTX-n9URmJC8RzD:ba07day) ([raw file](https://github.com/pmem/rpma/blob/5961fd630ac45d524849947a8718f29d5244aac0/src/include/librpma.h#L355)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Alph order, please.
___
*[src/include/librpma.h, line 521 at r2](https://reviewable.io/reviews/pmem/rpma/486#-MIPqZOc9mZvAvn8XcRb:-MIPqZOc9mZvAvn8XcRc:b7eqx6o) ([raw file](https://github.com/pmem/rpma/blob/d47577aec35d352b712ec3645d12d1fd2af7e8f4/src/include/librpma.h#L521)):*
> ```objc
>  * SEE ALSO
>  *
>  * rpma_utils_get_ibv_context(3), rpma_peer_delete(3) and
> ```

- rpma_mr_reg
- rpma_conn_req_new
- rpma_ep_listen

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/486)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 290 at r1](https://reviewable.io/reviews/pmem/rpma/486#-MIPW5sL8I_BFWQeoGEg:-MIQJBxs25XWQyS2IDa1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5961fd630ac45d524849947a8718f29d5244aac0/src/include/librpma.h#L290)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I hate to say this: alph order, please.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 355 at r1](https://reviewable.io/reviews/pmem/rpma/486#-MIPX2d1CjbD2sg9b3ze:-MIQJUdu1GwDzQwZQMG8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5961fd630ac45d524849947a8718f29d5244aac0/src/include/librpma.h#L355)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Alph order, please.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 521 at r2](https://reviewable.io/reviews/pmem/rpma/486#-MIPqZOc9mZvAvn8XcRb:-MIQLXEpAnuhC8zxxEKJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d47577aec35d352b712ec3645d12d1fd2af7e8f4/src/include/librpma.h#L521)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

- rpma_mr_reg
- rpma_conn_req_new
- rpma_ep_listen
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/486)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[src/include/librpma.h, line 287 at r3](https://reviewable.io/reviews/pmem/rpma/486#-MISY0O85hkP14HuOH0e:-MISY0O85hkP14HuOH0f:bjj1uzv) ([raw file](https://github.com/pmem/rpma/blob/477527182333651b27c36797645fc0e5b255a3ef/src/include/librpma.h#L287)):*
> ```
> m(3), and ht
> ```

no comma before 'and' please

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/486)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[src/include/librpma.h, line 287 at r3](https://reviewable.io/reviews/pmem/rpma/486#-MISY0O85hkP14HuOH0e:-MISaYEoEuic7yVr9mJm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/477527182333651b27c36797645fc0e5b255a3ef/src/include/librpma.h#L287)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> m(3), and ht
> ```

no comma before 'and' please
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/486)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/486)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/486#-:-MIStZVfBIOgLmQbgWeR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/486)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/486#-:-MIT21Ai-VOEPDXnQ0lF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/486#-:-MIT2ACp3CsnRHm8uMzE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
