### PR TITLE
tools: convert x/y args into labels

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1082)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1082)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/lib/Figure.py, line 133 at r1](https://reviewable.io/reviews/pmem/rpma/1082#-MbfCF6c8jMP7yRDgsLK:-MbfCF6dCPaEkOmlGUqv:b-bn5zpg) ([raw file](https://github.com/pmem/rpma/blob/4b792bd8101cc10265dded5b4f1e81b2576e8f27/tools/perf/lib/Figure.py#L133)):*
> ```
> return columns.get(column, column)
> ```

`return columns.get(column)` ?

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1082)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/lib/Figure.py, line 123 at r1](https://reviewable.io/reviews/pmem/rpma/1082#-MbgGSum59Dk-gPTPSBO:-MbgGSun6wm9PsqqMBo-:balzv1t) ([raw file](https://github.com/pmem/rpma/blob/4b792bd8101cc10265dded5b4f1e81b2576e8f27/tools/perf/lib/Figure.py#L123)):*
> ```Python
>     def _label(self, column):
>         """Translate the name of a column to a label with a unit"""
>         columns={
> ```

label_by_column?
___
*[tools/perf/lib/Figure.py, line 133 at r1](https://reviewable.io/reviews/pmem/rpma/1082#-MbfCF6c8jMP7yRDgsLK:-MbgF8mr0-l0aTffQK-L:bey19h5) ([raw file](https://github.com/pmem/rpma/blob/4b792bd8101cc10265dded5b4f1e81b2576e8f27/tools/perf/lib/Figure.py#L133)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> return columns.get(column, column)
> ```

`return columns.get(column)` ?
</blockquote></details>

It is a way of providing a default value. Having a raw name of the column is better than synthetic default. @osalyk maybe give a comment here since it is a little bit confusing.

Ref: https://www.w3schools.com/python/ref_dictionary_get.asp

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1082)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/lib/Figure.py, line 133 at r1](https://reviewable.io/reviews/pmem/rpma/1082#-MbfCF6c8jMP7yRDgsLK:-MbgUv0k1U9vCXmb0pAM:btdsfzr) ([raw file](https://github.com/pmem/rpma/blob/4b792bd8101cc10265dded5b4f1e81b2576e8f27/tools/perf/lib/Figure.py#L133)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is a way of providing a default value. Having a raw name of the column is better than synthetic default. @osalyk maybe give a comment here since it is a little bit confusing.

Ref: https://www.w3schools.com/python/ref_dictionary_get.asp
</blockquote></details>

I see.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1082)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/lib/Figure.py, line 123 at r1](https://reviewable.io/reviews/pmem/rpma/1082#-MbgGSum59Dk-gPTPSBO:-MbjL3kFDJGpkvt2yZW4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4b792bd8101cc10265dded5b4f1e81b2576e8f27/tools/perf/lib/Figure.py#L123)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

label_by_column?
</blockquote></details>

Done.
___
*[tools/perf/lib/Figure.py, line 133 at r1](https://reviewable.io/reviews/pmem/rpma/1082#-MbfCF6c8jMP7yRDgsLK:-MbjNAfF53WNFMMts6mQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4b792bd8101cc10265dded5b4f1e81b2576e8f27/tools/perf/lib/Figure.py#L133)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I see.
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1082)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/lib/Figure.py, line 134 at r2](https://reviewable.io/reviews/pmem/rpma/1082#-MbjYltACmABMPZ9dHPX:-MbjYltACmABMPZ9dHPY:b-1c58kb) ([raw file](https://github.com/pmem/rpma/blob/b1b516d17098e257200d4ddb1a20719bf9ed1419/tools/perf/lib/Figure.py#L134)):*
> If the column is not in the dictionary the default is return value is the raw name of the column.

We do not need to copy-paste the whole function documentation. These are the basics. ;-)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1082)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/Figure.py, line 134 at r2](https://reviewable.io/reviews/pmem/rpma/1082#-MbjYltACmABMPZ9dHPX:-Mbj_DMT6Nx6doph8-9P:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b1b516d17098e257200d4ddb1a20719bf9ed1419/tools/perf/lib/Figure.py#L134)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

> If the column is not in the dictionary the default is return value is the raw name of the column.

We do not need to copy-paste the whole function documentation. These are the basics. ;-)
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1082)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1082#-:-Mbjl9cGD-6m1LBMSp1C:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1082)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/lib/Figure.py, line 134 at r2](https://reviewable.io/reviews/pmem/rpma/1082#-MbjYltACmABMPZ9dHPX:-Mbjm95m9zkaJgpVRN_U:b-e7o3xg) ([raw file](https://github.com/pmem/rpma/blob/b1b516d17098e257200d4ddb1a20719bf9ed1419/tools/perf/lib/Figure.py#L134)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

the default ~~is~~ return value is the raw name of the column.

Sorry. ;-)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1082)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[tools/perf/lib/Figure.py, line 134 at r2](https://reviewable.io/reviews/pmem/rpma/1082#-MbjYltACmABMPZ9dHPX:-MbjncgBDCwfXm2wJlLG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b1b516d17098e257200d4ddb1a20719bf9ed1419/tools/perf/lib/Figure.py#L134)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

the default ~~is~~ return value is the raw name of the column.

Sorry. ;-)
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1082#-:-MbjnjG5Cg7-A_ZoOtEa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
