### PR TITLE
common: move config_softroce.sh to tools folder

### PR DESCRIPTION
**Pull request by grom72**
- [x]  #810

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/811)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/811)* status: 0 of 36 files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/811#-MSi7vn6Ai9WehHUj6YM:-MSi7vn6Ai9WehHUj6YN:b-8cioiv) (no related file):*
Please rebase.

---

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/811)* status: 0 of 42 files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/811#-MSi7vn6Ai9WehHUj6YM:-MSj9N5z2fD6DQ9-t7-l:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please rebase.
</blockquote></details>

Done.

---

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 12 of 36 files at r1, 39 of 43 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/811)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72)

___
*[tools/README.md, line 1 at r2](https://reviewable.io/reviews/pmem/rpma/811#-MSlwq_447AHOGG0kRjK:-MSlwq_447AHOGG0kRjL:b-9rckkw) ([raw file](https://github.com/pmem/rpma/blob/9f3c749b3e575de2be89600138c297537e028899/tools/README.md#L1)):*
> ```Markdown
> librpma tools
> ```

I prefer the `#` type header. I know we are not consistent yet. But having so many markdown templates with the `#` type header indicates it is the most popular in our repo so far.
___
*[tools/README.md, line 4 at r2](https://reviewable.io/reviews/pmem/rpma/811#-MSlwfBF3yfBXzz_xRY7:-MSlwfBF3yfBXzz_xRY8:b-jjy811) ([raw file](https://github.com/pmem/rpma/blob/9f3c749b3e575de2be89600138c297537e028899/tools/README.md#L4)):*
> ```Markdown
> ===
> 
> This directory contains tools that could be usefull for librpma users.
> ```

useful
___
*[tools/README.md, line 6 at r2](https://reviewable.io/reviews/pmem/rpma/811#-MSlwZwvEpr-dZHKZSjN:-MSlwZwvEpr-dZHKZSjO:bmzgwq6) ([raw file](https://github.com/pmem/rpma/blob/9f3c749b3e575de2be89600138c297537e028899/tools/README.md#L6)):*
> ```Markdown
> This directory contains tools that could be usefull for librpma users.
> 
> * [ddio.sh](ddio.sh) script allows monitoring and control 
> ```

controlling
___
*[tools/README.md, line 7 at r2](https://reviewable.io/reviews/pmem/rpma/811#-MSlvWIh2n0Lg9xWu_Jh:-MSlvWIh2n0Lg9xWu_Ji:bbosskm) ([raw file](https://github.com/pmem/rpma/blob/9f3c749b3e575de2be89600138c297537e028899/tools/README.md#L7)):*
> ```Markdown
> 
> * [ddio.sh](ddio.sh) script allows monitoring and control 
> Intel Direct Data IO configuration.
> ```

`Intel&reg; Data Direct I/O`
___
*[tools/README.md, line 10 at r2](https://reviewable.io/reviews/pmem/rpma/811#-MSlvcpM07hkTSs2znrz:-MSlvcpM07hkTSs2zns-:bghnyk) ([raw file](https://github.com/pmem/rpma/blob/9f3c749b3e575de2be89600138c297537e028899/tools/README.md#L10)):*
> ```Markdown
> 
> * [config_softroce.sh](config_softroce.sh) script is used to configuring SoftRoCE.
> (It can be also run from the CMake build directory using 'make config_softroce')
> ```

'make config _softroce' -> `make config_softroce`
Please use backticks.
___
*[tools/README.md, line 12 at r2](https://reviewable.io/reviews/pmem/rpma/811#-MSlw5hx-Vq3kgpUxozi:-MSlw5hx-Vq3kgpUxozj:b-7umqiq) ([raw file](https://github.com/pmem/rpma/blob/9f3c749b3e575de2be89600138c297537e028899/tools/README.md#L12)):*
> ```Markdown
> (It can be also run from the CMake build directory using 'make config_softroce')
> 
> * [perf](perf) sub-directory contains set of tools useful in RPMA benchmarking.
> ```

a set
___
*[tools/README.md, line 12 at r2](https://reviewable.io/reviews/pmem/rpma/811#-MSlw9A_7KCqiiMTEVRY:-MSlw9A_7KCqiiMTEVRZ:b87hw0n) ([raw file](https://github.com/pmem/rpma/blob/9f3c749b3e575de2be89600138c297537e028899/tools/README.md#L12)):*
> ```Markdown
> (It can be also run from the CMake build directory using 'make config_softroce')
> 
> * [perf](perf) sub-directory contains set of tools useful in RPMA benchmarking.
> ```

for RPMA benchmarking

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/811)* status: 4 of 5 files reviewed, 6 unresolved discussions (waiting on @janekmi)

___
*[tools/README.md, line 4 at r2](https://reviewable.io/reviews/pmem/rpma/811#-MSlwfBF3yfBXzz_xRY7:-MSmF4Yt0NWfqAcvkzfm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9f3c749b3e575de2be89600138c297537e028899/tools/README.md#L4)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

useful
</blockquote></details>

Done.
___
*[tools/README.md, line 6 at r2](https://reviewable.io/reviews/pmem/rpma/811#-MSlwZwvEpr-dZHKZSjN:-MSmF5GS4JAiLzWSsLFr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9f3c749b3e575de2be89600138c297537e028899/tools/README.md#L6)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

controlling
</blockquote></details>

Done.
___
*[tools/README.md, line 7 at r2](https://reviewable.io/reviews/pmem/rpma/811#-MSlvWIh2n0Lg9xWu_Jh:-MSmF8D33Uvty_0dHDcs:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9f3c749b3e575de2be89600138c297537e028899/tools/README.md#L7)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`Intel&reg; Data Direct I/O`
</blockquote></details>

Done.
___
*[tools/README.md, line 10 at r2](https://reviewable.io/reviews/pmem/rpma/811#-MSlvcpM07hkTSs2znrz:-MSmF8da1T9VEjdMObgF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9f3c749b3e575de2be89600138c297537e028899/tools/README.md#L10)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

'make config _softroce' -> `make config_softroce`
Please use backticks.
</blockquote></details>

Done.
___
*[tools/README.md, line 12 at r2](https://reviewable.io/reviews/pmem/rpma/811#-MSlw5hx-Vq3kgpUxozi:-MSmEwoKDVUPq8RUQwG2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9f3c749b3e575de2be89600138c297537e028899/tools/README.md#L12)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

a set
</blockquote></details>

Done.
___
*[tools/README.md, line 12 at r2](https://reviewable.io/reviews/pmem/rpma/811#-MSlw9A_7KCqiiMTEVRY:-MSmExEZD4wWTEwsSq9C:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9f3c749b3e575de2be89600138c297537e028899/tools/README.md#L12)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

for RPMA benchmarking
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/811)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tools/README.md, line 7 at r2](https://reviewable.io/reviews/pmem/rpma/811#-MSlvWIh2n0Lg9xWu_Jh:-MSmJD3N2TwMdrkKdq1j:bcz1jhd) ([raw file](https://github.com/pmem/rpma/blob/9f3c749b3e575de2be89600138c297537e028899/tools/README.md#L7)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

IO -> I/O

I'm just referring to the official naming.

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/811)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[tools/README.md, line 10 at r2](https://reviewable.io/reviews/pmem/rpma/811#-MSlvcpM07hkTSs2znrz:-MSmK9NS9ueFibfyi-YD:bw1cc97) ([raw file](https://github.com/pmem/rpma/blob/9f3c749b3e575de2be89600138c297537e028899/tools/README.md#L10)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Triple backticks look weird to me. And it seems not a legal syntax.
I recommend single backticks.

Ref: https://guides.github.com/features/mastering-markdown/

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/811)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/README.md, line 7 at r2](https://reviewable.io/reviews/pmem/rpma/811#-MSlvWIh2n0Lg9xWu_Jh:-MSmj1dHBQMGGarr1E9U:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/9f3c749b3e575de2be89600138c297537e028899/tools/README.md#L7)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

IO -> I/O

I'm just referring to the official naming.
</blockquote></details>

Done
___
*[tools/README.md, line 10 at r2](https://reviewable.io/reviews/pmem/rpma/811#-MSlvcpM07hkTSs2znrz:-MSmj2bu0OQEIRwGTxKS:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/9f3c749b3e575de2be89600138c297537e028899/tools/README.md#L10)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Triple backticks look weird to me. And it seems not a legal syntax.
I recommend single backticks.

Ref: https://guides.github.com/features/mastering-markdown/
</blockquote></details>

Done

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/811#-:-MSmj5my1vz-DPf57AzE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/811#-:-MSmmJqFEG4J42pa-0eX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
