### PR TITLE
examples: add examples/config_softroce.sh script for configuring SoftRoCE

### PR DESCRIPTION
**Pull request by ldorau**
Add the 'utils/rxe_config.sh' script for configuring SoftRoCE
and the 'config_rxe' make target to run it.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/265)

### CODE REVIEW

**Comment by ldorau** [comment]
> do we plan to add this to README or any other file?
> 

So maybe move 'utils/rxe_config.sh' to 'examples/' and add info about both of them to 'examples/README'?
@janekmi @grom72 ?

**Review by grom72 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/265#-:-MF4BJ9pAeP0_DgN8fqY:bdycpsm)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[CMakeLists.txt, line 225 at r4](https://reviewable.io/reviews/pmem/rpma/265#-MF22fTr8yb2H-1QC8Tx:-MF4AnHe8Y_y77A8Qfnn:byjrbrr) ([raw file](https://github.com/pmem/rpma/blob/215094cb9f53748a8280955e6ed808503a55eb41/CMakeLists.txt#L225)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I'm not sure it is a good idea to force the user to learn two new words (SoftRoCE, rxe). I know they are kind of equivalent but it may also raise the question why you have to configure some rxe since you are trying to run tests on SoftRoCE?

What do you think to call it as follows:
```bash
$ make config_softroce
$ make test_softroce
```
Does it look nicer or not? ;-)
</blockquote></details>

softroce does not look like  SoftRoCE so maybe use kernel module name config_*rdma_rxe* instead of config_rxe and in a similar way test_rdma_rxe?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/265)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[CMakeLists.txt, line 225 at r4](https://reviewable.io/reviews/pmem/rpma/265#-MF22fTr8yb2H-1QC8Tx:-MF4GD2Q5RevOeALyPuh:btdbb2k) ([raw file](https://github.com/pmem/rpma/blob/215094cb9f53748a8280955e6ed808503a55eb41/CMakeLists.txt#L225)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

softroce does not look like  SoftRoCE so maybe use kernel module name config_*rdma_rxe* instead of config_rxe and in a similar way test_rdma_rxe?
</blockquote></details>

Another kernel module `siw` can be used instead of `rdma_rxe` too ...
I am for @janekmi 

Done.
___
*[examples/README, line 11 at r4](https://reviewable.io/reviews/pmem/rpma/265#-MF228kA4eYa-x0wocFU:-MF4IF_e-drUfTn9Cpxo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/215094cb9f53748a8280955e6ed808503a55eb41/examples/README#L11)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

> it can be also run from the CMake build directory using `make config_rxe`
</blockquote></details>

Done.
___
*[examples/config_rxe.sh, line 34 at r4](https://reviewable.io/reviews/pmem/rpma/265#-MF21HAe4x2W90kx6XWX:-MF4HgqP2G9Ng3R9RMcF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/215094cb9f53748a8280955e6ed808503a55eb41/examples/config_rxe.sh#L34)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

**Picky**: either dots at the end or no dots at the end.
</blockquote></details>

Done.
___
*[examples/config_rxe.sh, line 39 at r4](https://reviewable.io/reviews/pmem/rpma/265#-MF21SZj4mZlzM6nLfTO:-MF4HhBs7RyB421iL_dA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/215094cb9f53748a8280955e6ed808503a55eb41/examples/config_rxe.sh#L39)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/265)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/265#-:-MF4nEWKB9J5rfLk3Eln:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/265#-:-MF4vgPV8_ExWFwonQxV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
