### PR TITLE
test: add rpma_ep_shutdown mt test

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1872)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1872)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1872)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi and @ldorau)

___
*[`tests/multithreaded/ep/rpma_ep_shutdown.c` line 78 at r1](https://reviewable.io/reviews/pmem/rpma/1872#-N5ZrQps17E9FgXaxhy_:-N5ZrQps17E9FgXaxhya:undefined) ([raw file](https://github.com/pmem/rpma/blob/d407ea0b169db0527598902284bf887e066e020c/tests/multithreaded/ep/rpma_ep_shutdown.c#L78)):*
> ```C
> 	struct state *st = (struct state *)state;
> 
> 	/* shutdown the endpoint */
> ```





_Suggestion:_
```C
/* shutdown and delete the endpoint */
```

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1872)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

**Review by osalyk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1872)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

___
*[`tests/multithreaded/ep/rpma_ep_shutdown.c` line 88 at r1](https://reviewable.io/reviews/pmem/rpma/1872#-N5_NAqGEqI6dpIf6RGi:-N5_NAqGEqI6dpIf6RGj:b-ly6if7) ([raw file](https://github.com/pmem/rpma/blob/d407ea0b169db0527598902284bf887e066e020c/tests/multithreaded/ep/rpma_ep_shutdown.c#L88)):*
> ```C
>  */
> static void
> fini(unsigned id, void *prestate, void **state_ptr,
> ```

Shouldn't this be a seq_fini() function?

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1872)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[`tests/multithreaded/ep/rpma_ep_shutdown.c` line 88 at r1](https://reviewable.io/reviews/pmem/rpma/1872#-N5_NAqGEqI6dpIf6RGi:-N5_iOG585hYMJNshKu2:b3c1p4r) ([raw file](https://github.com/pmem/rpma/blob/d407ea0b169db0527598902284bf887e066e020c/tests/multithreaded/ep/rpma_ep_shutdown.c#L88)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Shouldn't this be a seq_fini() function?
</blockquote></details>

I think you are right because there is a calloc in seq_init. @ldorau ?

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1872)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi and @osalyk)

___
*[`tests/multithreaded/ep/rpma_ep_shutdown.c` line 85 at r1](https://reviewable.io/reviews/pmem/rpma/1872#-N5crdFc0ERAkGFUmUDf:-N5crdFc0ERAkGFUmUDg:b-wdtq5l) ([raw file](https://github.com/pmem/rpma/blob/d407ea0b169db0527598902284bf887e066e020c/tests/multithreaded/ep/rpma_ep_shutdown.c#L85)):*
> ```C
> 
> /*
>  * fini -- shutdown the endpoint and free the state
> ```

`free the state`



_Code quote:_
```C
shutdown the endpoint and free the state
```
___
*[`tests/multithreaded/ep/rpma_ep_shutdown.c` line 88 at r1](https://reviewable.io/reviews/pmem/rpma/1872#-N5_NAqGEqI6dpIf6RGi:-N5crtJQ7z8sTIuhmh34:b-hct9af) ([raw file](https://github.com/pmem/rpma/blob/d407ea0b169db0527598902284bf887e066e020c/tests/multithreaded/ep/rpma_ep_shutdown.c#L88)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

I think you are right because there is a calloc in seq_init. @ldorau ?
</blockquote></details>

It does not matter in this case, because it calls free() only, but for the sake of consistency let's change it to seq_fini().

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1872)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[`tests/multithreaded/ep/rpma_ep_shutdown.c` line 78 at r1](https://reviewable.io/reviews/pmem/rpma/1872#-N5ZrQps17E9FgXaxhy_:-N5dEDMP-haWBYSbXWiX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d407ea0b169db0527598902284bf887e066e020c/tests/multithreaded/ep/rpma_ep_shutdown.c#L78)):*
> ```C
> 	struct state *st = (struct state *)state;
> 
> 	/* shutdown the endpoint */
> ```

Done.
___
*[`tests/multithreaded/ep/rpma_ep_shutdown.c` line 85 at r1](https://reviewable.io/reviews/pmem/rpma/1872#-N5crdFc0ERAkGFUmUDf:-N5dECFl5eTl8fxkXCFP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d407ea0b169db0527598902284bf887e066e020c/tests/multithreaded/ep/rpma_ep_shutdown.c#L85)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`free the state`
</blockquote></details>

Done.
___
*[`tests/multithreaded/ep/rpma_ep_shutdown.c` line 88 at r1](https://reviewable.io/reviews/pmem/rpma/1872#-N5_NAqGEqI6dpIf6RGi:-N5dECXJ8pryF63X88aq:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d407ea0b169db0527598902284bf887e066e020c/tests/multithreaded/ep/rpma_ep_shutdown.c#L88)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It does not matter in this case, because it calls free() only, but for the sake of consistency let's change it to seq_fini().
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1872#-:-N5dEabr1jKt9AcTiT8s:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1872#-:-N5dFjppAV0DImYqnVPI:bg7igkv)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1872)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)

**Review by osalyk — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1872)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[`tests/multithreaded/ep/rpma_ep_shutdown.c` line 49 at r2](https://reviewable.io/reviews/pmem/rpma/1872#-N5dh_lfCZF4_6PQNebu:-N5dh_lfCZF4_6PQNebv:b-1m9nql) ([raw file](https://github.com/pmem/rpma/blob/f29fc915e5e1e9f0091672ed734d9001e99da24b/tests/multithreaded/ep/rpma_ep_shutdown.c#L49)):*
> ```C
> void
> seq_init(unsigned id, void *prestate, void **state_ptr,
> 		struct mtt_result *result)
> ```

One line
___
*[`tests/multithreaded/ep/rpma_ep_shutdown.c` line 74 at r2](https://reviewable.io/reviews/pmem/rpma/1872#-N5dhbXE2XT_8dI6q-1X:-N5dhbXE2XT_8dI6q-1Y:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/f29fc915e5e1e9f0091672ed734d9001e99da24b/tests/multithreaded/ep/rpma_ep_shutdown.c#L74)):*
> ```C
> static void
> thread(unsigned id, void *prestate, void *state,
> 		struct mtt_result *tr)
> ```

.
___
*[`tests/multithreaded/ep/rpma_ep_shutdown.c` line 89 at r2](https://reviewable.io/reviews/pmem/rpma/1872#-N5dhUJD3MckOBFsbbCt:-N5dhUJD3MckOBFsbbCu:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/f29fc915e5e1e9f0091672ed734d9001e99da24b/tests/multithreaded/ep/rpma_ep_shutdown.c#L89)):*
> ```C
> static void
> seq_fini(unsigned id, void *prestate, void **state_ptr,
> 		struct mtt_result *tr)
> ```

.

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1872)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[`tests/multithreaded/ep/rpma_ep_shutdown.c` line 49 at r2](https://reviewable.io/reviews/pmem/rpma/1872#-N5dh_lfCZF4_6PQNebu:-N5du89dCE9zvcPabDNy:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f29fc915e5e1e9f0091672ed734d9001e99da24b/tests/multithreaded/ep/rpma_ep_shutdown.c#L49)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

One line
</blockquote></details>

Done.
___
*[`tests/multithreaded/ep/rpma_ep_shutdown.c` line 74 at r2](https://reviewable.io/reviews/pmem/rpma/1872#-N5dhbXE2XT_8dI6q-1X:-N5du7r52u-41u88u8vQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f29fc915e5e1e9f0091672ed734d9001e99da24b/tests/multithreaded/ep/rpma_ep_shutdown.c#L74)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`tests/multithreaded/ep/rpma_ep_shutdown.c` line 89 at r2](https://reviewable.io/reviews/pmem/rpma/1872#-N5dhUJD3MckOBFsbbCt:-N5du76zBivukXVYdAHS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f29fc915e5e1e9f0091672ed734d9001e99da24b/tests/multithreaded/ep/rpma_ep_shutdown.c#L89)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1872)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @osalyk)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1872#-:-N5duxwlBen6WourQntd:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1872#-:-N5eAhL80EYetgPOe9sG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1872)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
