### PR TITLE
exmaples: fix runnning 07-atomic-write example on SoftRoCE

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/334)

### CODE REVIEW

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/334#-:-MGDviAa7abeyAyoSYLi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/334)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[examples/run-all-on-SoftRoCE.sh, line 56 at r1](https://reviewable.io/reviews/pmem/rpma/334#-MGE1NHF8GzuNWpKZRZ0:-MGE1NHGCwIj86lS27Q-:b-fj22ix) ([raw file](https://github.com/pmem/rpma/blob/d52b1aaf7f89d9a0095c579eceb8aefe42a577ff/examples/run-all-on-SoftRoCE.sh#L56)):*
> ```
> $DIR/client $IP_ADDRESS $PORT "WORD"
> ```
"WORD" "Second WORD" "Last WORD"

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/334)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[examples/run-all-on-SoftRoCE.sh, line 56 at r1](https://reviewable.io/reviews/pmem/rpma/334#-MGE1NHF8GzuNWpKZRZ0:-MGE2WR2A-sgJcDZ9Pcg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d52b1aaf7f89d9a0095c579eceb8aefe42a577ff/examples/run-all-on-SoftRoCE.sh#L56)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> $DIR/client $IP_ADDRESS $PORT "WORD"
> ```
"WORD" "Second WORD" "Last WORD"
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/334)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/334#-:-MGHRJU593T8xhN88CS4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/334#-:-MGHc7Ir7ZJlURkgVjXO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
