### PR TITLE
common: show git diff of the generated documentation

### PR DESCRIPTION
**Pull request by ldorau**
Introduce a possibility to verify if the changed documentation
is correctly formatted before merging it upstream.

If $AUTO_DOC_UPDATE == "1" then pull requests
with the generated documentation are created
only on $GITHUB_REPO and only on the main branch,
otherwise the git diff is printed out to be able
to verify if the new changes in the documentation
are correct.

- - -
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/2096)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2096#-:-NL0w-fdAW31eMLgfSew:bx5ef3g)* status: 0 of 3 files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
The above image is from https://github.com/ldorau/rpma/actions/runs/3846727604/jobs/6552361054 (job #4)

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2096#-:-NL0wFIs19wlsOKQAy8Q:b-28tzyh)* status: 0 of 3 files reviewed, all discussions resolved

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 2 of 2 files at r2, 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2096#-:-NLKXIK3BrrRYtqoS8SU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2096)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2096#-:-NLKyGQVB_bINzJ71jUK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2096)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
