### PR TITLE
common: disable rpma_mr_advise() if IBV_ADVISE_MR flags are not supported

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1905)

### CODE REVIEW

**Comment by ldorau** [comment]
See: https://github.com/ldorau/rpma/actions/runs/2595255577

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1905)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1905)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[`CMakeLists.txt` line 167 at r1](https://reviewable.io/reviews/pmem/rpma/1905#-N5srEqYBT-imUXDItWY:-N5srEqZAV4oHXNQyYH4:b-ybbioa) ([raw file](https://github.com/pmem/rpma/blob/5612baac65783f61a714ba06c7938c41472e0271/CMakeLists.txt#L167)):*
> ```CMake
> 	message(STATUS "All required IBV_ADVISE_MR* flags are supported")
> else()
> 	message(FATAL_ERROR "Required IBV_ADVISE_MR* flags are NOT supported "
> ```

I would propose disabling all examples and integration tests (with proper messages) when ``IBV_ADVISE_MR*`` flags are not available



_Suggestion:_
```CMake
	message(WARNIN "Required IBV_ADVISE_MR* flags are NOT supported "
				"(IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE, and IBV_ADVISE_MR_FLAG_FLUSH ). "
				"Examples will not be built."
				"Integration tests will not be built.")
```
___
*[`cmake/functions.cmake` line 229 at r1](https://reviewable.io/reviews/pmem/rpma/1905#-N5sr0Jy2R6FcE65u3YM:-N5sr0Jz369syvp5-cCP:b-8uuvbk) ([raw file](https://github.com/pmem/rpma/blob/5612baac65783f61a714ba06c7938c41472e0271/cmake/functions.cmake#L229)):*
> ```CMake
> 		/* check if all required IBV_ADVISE_MR* flags are supported */
> 		int main() {
> 			return IBV_ADVISE_MR_ADVICE_PREFETCH | \
> ```

Let's leave only flags that are required by examples



_Suggestion:_
```CMake
			return 
				IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE | \
				IBV_ADVISE_MR_FLAG_FLUSH ;
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1905)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1905)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[`CMakeLists.txt` line 167 at r1](https://reviewable.io/reviews/pmem/rpma/1905#-N5srEqYBT-imUXDItWY:-N5sxc9R25Gj-FGYcJOH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5612baac65783f61a714ba06c7938c41472e0271/CMakeLists.txt#L167)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I would propose disabling all examples and integration tests (with proper messages) when ``IBV_ADVISE_MR*`` flags are not available
</blockquote></details>

Done.
___
*[`cmake/functions.cmake` line 229 at r1](https://reviewable.io/reviews/pmem/rpma/1905#-N5sr0Jy2R6FcE65u3YM:-N5swUBt4_jTJ3bp1YUQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5612baac65783f61a714ba06c7938c41472e0271/cmake/functions.cmake#L229)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Let's leave only flags that are required by examples
</blockquote></details>

Done.

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1905#-:-N5t7vjS6utw69JqpJsC:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1905#-:-N5tZe8-B0S4RtofS-s3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1905)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1905)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1905#-N5t_79Q8dGLUHYT7KkT:-N5t_79Q8dGLUHYT7KkU:bosv7jh) (no related file):*
We should add Fedora 30 to our CI to verify that this works as expected.

___

**Review by haichangsi — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1905#-:-N5taF_LAt_S5V11fhOM:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1905#-:-N6Hts9cCdVjtsbb_l1r:bg7igkv)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1905)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi, @ldorau, and @osalyk)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1905)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @grom72, @haichangsi, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1905#-N5t_79Q8dGLUHYT7KkT:-N7KG3DH7ipMvxSoDKXj:bufov1f) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

We should add Fedora 30 to our CI to verify that this works as expected.
</blockquote></details>

We cannot add Fedora 30 to our CI, because it is EOL, but we can test it of course:

https://github.com/ldorau/rpma/actions/runs/2695736875
https://github.com/ldorau/rpma/runs/7403937256

Done.

___

**Review by ldorau — COMMENTED** [review]
@yangx-jy  please review

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1905#-:-N7KHAcjDRwB-2tPygoo:b-y998r6)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @grom72, @haichangsi, and @osalyk)

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 9 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1905)* status: 2 of 9 files reviewed, 1 unresolved discussion (waiting on @haichangsi, @ldorau, and @osalyk)

___
*[`examples/04-write-to-persistent/CMakeLists.txt` line 19 at r4](https://reviewable.io/reviews/pmem/rpma/1905#-N7KJTQb4ZBAFpBmHcDl:-N7KJTQb4ZBAFpBmHcDm:buhlgwc) ([raw file](https://github.com/pmem/rpma/blob/11aadc9be26cbd0835dd0c68fcd6ab505c61d46e/examples/04-write-to-persistent/CMakeLists.txt#L19)):*
> ```CMake
> # check if all required IBV_ADVISE_MR* flags are supported
> are_ibv_advise_flags_supported(IBV_ADVISE_MR_FLAGS_SUPPORTED)
> if(IBV_ADVISE_MR_FLAGS_SUPPORTED)
> ```

Do we need ``SKIP_IF_IBV_ADVISE_MR_FLAGS_NOT_SUPPORTED=ON`` at all?



_Suggestion:_
```CMake
if(IBV_ADVISE_MR_FLAGS_SUPPORTED)
	message(STATUS "All required IBV_ADVISE_MR* flags are supported")
else()
	message(WARNING "Required IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE and IBV_ADVISE_MR_FLAG_FLUSH flags are NOT supported. Skipping ...")
	return()
endif()
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1905)* status: 2 of 9 files reviewed, 1 unresolved discussion (waiting on @grom72, @haichangsi, and @osalyk)

___
*[`examples/04-write-to-persistent/CMakeLists.txt` line 19 at r4](https://reviewable.io/reviews/pmem/rpma/1905#-N7KJTQb4ZBAFpBmHcDl:-N7KU5h6ELj0X5SpVDTJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/11aadc9be26cbd0835dd0c68fcd6ab505c61d46e/examples/04-write-to-persistent/CMakeLists.txt#L19)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Do we need ``SKIP_IF_IBV_ADVISE_MR_FLAGS_NOT_SUPPORTED=ON`` at all?
</blockquote></details>

Done.

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 7 of 7 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1905#-:-N7KUlxV7U4AWFPclgrO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi and @osalyk)

**Comment by yangx-jy** [comment]
Hi @grom72 @ldorau @haichangsi 

Why do we need to disable all examples when all required IBV_ADVISE_MR flags are not supported?  I prefer to avoid calling `rpma_mr_advise()` for all examples in this case. Calling `rpma_mr_advise()` just improves the performance so all examples without `rpma_mr_advise()` can still work.

**Review by ldorau — COMMENTED** [review]
@yangx-jy do you mean something like this?

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1905#-:-N7Va2dc5CaCliYXYWjS:bbm5q1v)* status: 2 of 18 files reviewed, all discussions resolved (waiting on @grom72, @haichangsi, and @osalyk)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 16 of 16 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1905#-:-N7VcNBCD2TcYhMaRmjT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi and @osalyk)

**Review by ldorau — COMMENTED** [review]
New build: https://github.com/ldorau/rpma/runs/7448260274

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1905#-:-N7Vcln63pZbIlvG5nDK:b-kijyod)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi and @osalyk)

**Review by yangx-jy — COMMENTED** [review]
@ldorau  Yes, this is what I expect.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1905#-:-N7Vf-QU9ubrafFa_6oE:binbvd3)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi, @ldorau, and @osalyk)

___
*[`CMakeLists.txt` line 167 at r6](https://reviewable.io/reviews/pmem/rpma/1905#-N7Vg8Rj9XS0t25N26Rv:-N7Vg8Rj9XS0t25N26Rw:beuw0en) ([raw file](https://github.com/pmem/rpma/blob/940d3a0e2cd82374aba9e0423ddee8f393e689d2/CMakeLists.txt#L167)):*
> ```CMake
> else()
> 	message(WARNING "Required IBV_ADVISE_MR_ADVICE_PREFETCH_WRITE and IBV_ADVISE_MR_FLAG_FLUSH flags are NOT supported. "
> 			"rpma_mr_advise() will not be called in the examples.")
> ```

One more comment:
I hope we can move the duplicate output into `are_ibv_advise_flags_supported()`

**Comment by yangx-jy** [comment]
@grom72  I added another comment below. I hope we can simplify the code by moving duplicate output into `are_ibv_advise_flags_supported()`.  Other than that, it looks good to me. ^_^

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1905)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi, @ldorau, and @osalyk)

**Review by ldorau — COMMENTED** [review]
@yangx-jy Done

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1905#-:-N7_Jzuj9GF_-k6x3ebt:b-ri8mji)* status: 10 of 18 files reviewed, 1 unresolved discussion (waiting on @grom72, @haichangsi, @osalyk, and @yangx-jy)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 9 of 16 files at r6, 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1905#-:-N7_V81_8AcYoN17nvUv:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72, @haichangsi, and @yangx-jy)

**Review by yangx-jy — COMMENTED** [review]
:lgtm:

> Reviewed 9 of 16 files at r6, 8 of 8 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1905#-:-N7aOotXAX3qp64ltq1-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72 and @haichangsi)

**Pull request merged**
