### PR TITLE
rpma: add CONTRIBUTING.md file

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/321)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
Besides the one obvious issue below :lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/321#-:-MG4RUmFCRRL-tx-YT0M:b-gxrrlc)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[CONTRIBUTING.md, line 127 at r1](https://reviewable.io/reviews/pmem/rpma/321#-MG4P25RBGQH1NS2FwfT:-MG4P25RBGQH1NS2FwfU:bef5uvf) ([raw file](https://github.com/pmem/rpma/blob/600872fc0c63d70b56694df938979081fdfd7c43/CONTRIBUTING.md#L127)):*
> ```Markdown
> On our issues page we also gather feature requests and questions. Templates to use
> are `Feature` and `Question`, respectively.  They should help deliver a meaningful
> description of a feature or ask a question to us.
> ```

EOL missing.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/321)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[CONTRIBUTING.md, line 65 at r1](https://reviewable.io/reviews/pmem/rpma/321#-MG3lNP82ItelgW0dR4h:-MG3lNP9CQjjnpzzvKDI:bk259qn) ([raw file](https://github.com/pmem/rpma/blob/600872fc0c63d70b56694df938979081fdfd7c43/CONTRIBUTING.md#L65)):*
> ```
> //
> ```
worth to mention that License text is an exception 
___
*[CONTRIBUTING.md, line 114 at r1](https://reviewable.io/reviews/pmem/rpma/321#-MG3ljBu3zccccbjPEYQ:-MG3ljBu3zccccbjPEYR:b-6spt5l) ([raw file](https://github.com/pmem/rpma/blob/600872fc0c63d70b56694df938979081fdfd7c43/CONTRIBUTING.md#L114)):*
> ```Markdown
> Ref: rpma/issues#1
> ```
> ```

worth to mention that commit messages could be checked before PR is created with given CMAKE option

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/321)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[CONTRIBUTING.md, line 65 at r1](https://reviewable.io/reviews/pmem/rpma/321#-MG3lNP82ItelgW0dR4h:-MG739Fd5g2THwfrisxx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/600872fc0c63d70b56694df938979081fdfd7c43/CONTRIBUTING.md#L65)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> //
> ```
worth to mention that License text is an exception 
</blockquote></details>

Done.
___
*[CONTRIBUTING.md, line 114 at r1](https://reviewable.io/reviews/pmem/rpma/321#-MG3ljBu3zccccbjPEYQ:-MG74zLo18b1wbH_M8dM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/600872fc0c63d70b56694df938979081fdfd7c43/CONTRIBUTING.md#L114)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

worth to mention that commit messages could be checked before PR is created with given CMAKE option
</blockquote></details>

Done.
___
*[CONTRIBUTING.md, line 127 at r1](https://reviewable.io/reviews/pmem/rpma/321#-MG4P25RBGQH1NS2FwfT:-MG7533k9m3PE70n8r-h:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/600872fc0c63d70b56694df938979081fdfd7c43/CONTRIBUTING.md#L127)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

EOL missing.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/321)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[CONTRIBUTING.md, line 65 at r1](https://reviewable.io/reviews/pmem/rpma/321#-MG3lNP82ItelgW0dR4h:-MG79oRJEfcPp603q4Wu:b-9hl3ew) ([raw file](https://github.com/pmem/rpma/blob/600872fc0c63d70b56694df938979081fdfd7c43/CONTRIBUTING.md#L65)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`(except for the License)`

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/321)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)

___
*[CONTRIBUTING.md, line 1 at r2](https://reviewable.io/reviews/pmem/rpma/321#-MG7S_a8EqGdste0QLXw:-MG7S_a8EqGdste0QLXx:b-pt0968) ([raw file](https://github.com/pmem/rpma/blob/ea8a2b4c1b9a7dfb0a00df3f0608a054ab192332/CONTRIBUTING.md#L1)):*
> ```
>  the Remote Persistent Memory Access (RPMA)
> ```

1) no 'the'
2) I propose: `Remote Persistent Memory Access (RPMA) library (librpma)`, because RPMA is a kind of access, not a library ...
___
*[CONTRIBUTING.md, line 8 at r2](https://reviewable.io/reviews/pmem/rpma/321#-MG7TI2n5Ja03BE0i_QK:-MG7TI2n5Ja03BE0i_QL:b-wkvvhs) ([raw file](https://github.com/pmem/rpma/blob/ea8a2b4c1b9a7dfb0a00df3f0608a054ab192332/CONTRIBUTING.md#L8)):*
> ```
> about RPMA,
> ```

about librpma,
___
*[CONTRIBUTING.md, line 55 at r2](https://reviewable.io/reviews/pmem/rpma/321#-MG7TZ1O1T1R_lya7Z1r:-MG7TZ1O1T1R_lya7Z1s:b-wxjipu) ([raw file](https://github.com/pmem/rpma/blob/ea8a2b4c1b9a7dfb0a00df3f0608a054ab192332/CONTRIBUTING.md#L55)):*
> ```Markdown
> ```
> 
> ## Code Contributions
> ```

contributions
___
*[CONTRIBUTING.md, line 63 at r2](https://reviewable.io/reviews/pmem/rpma/321#-MG7TpXBEfHnyflfBHHU:-MG7TpXBEfHnyflfBHHV:bhjhlo5) ([raw file](https://github.com/pmem/rpma/blob/ea8a2b4c1b9a7dfb0a00df3f0608a054ab192332/CONTRIBUTING.md#L63)):*
> ```Markdown
> - The limit of line length is 80 characters.
> - Indent the code with TABs, not spaces. Tab width is 8 characters.
> - Do not break user-visible strings (even when they are longer than 80 characters)
> ```

`..., but make them the only token in the line.` - maybe you will find a better word than `token` ?
___
*[CONTRIBUTING.md, line 120 at r2](https://reviewable.io/reviews/pmem/rpma/321#-MG7V--VAeydHHqYiouA:-MG7V--VAeydHHqYiouB:b-he2jty) ([raw file](https://github.com/pmem/rpma/blob/ea8a2b4c1b9a7dfb0a00df3f0608a054ab192332/CONTRIBUTING.md#L120)):*
> ```Markdown
> ```
> 
> ## Bug Reports
> ```

reports
___
*[CONTRIBUTING.md, line 122 at r2](https://reviewable.io/reviews/pmem/rpma/321#-MG7V0gkA8Jq9YRHOpFE:-MG7V0gkA8Jq9YRHOpFF:bb72x1z) ([raw file](https://github.com/pmem/rpma/blob/ea8a2b4c1b9a7dfb0a00df3f0608a054ab192332/CONTRIBUTING.md#L122)):*
> ```Markdown
> ## Bug Reports
> 
> Bugs for the PMDK project are tracked in our
> ```

RPMA

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/321)* status: all files reviewed, 8 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[CONTRIBUTING.md, line 1 at r2](https://reviewable.io/reviews/pmem/rpma/321#-MG7S_a8EqGdste0QLXw:-MG7VVj_5RQkH_jdravn:bl7wvt3) ([raw file](https://github.com/pmem/rpma/blob/ea8a2b4c1b9a7dfb0a00df3f0608a054ab192332/CONTRIBUTING.md#L1)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  the Remote Persistent Memory Access (RPMA)
> ```

1) no 'the'
2) I propose: `Remote Persistent Memory Access (RPMA) library (librpma)`, because RPMA is a kind of access, not a library ...
</blockquote></details>

Excuse me, after having added `library (librpma)` there should be 'the' before, so my proposal is the following:
```
# Contributing to the Remote Persistent Memory Access (RPMA) library (librpma)
```

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/321)* status: all files reviewed, 8 unresolved discussions (waiting on @grom72 and @osalyk)

**Review by grom72 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/321#-:-MG7ZFWh18ZdsKIErPNB:bdycpsm)* status: all files reviewed, 6 unresolved discussions (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/321)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @ldorau)

___
*[CONTRIBUTING.md, line 65 at r1](https://reviewable.io/reviews/pmem/rpma/321#-MG3lNP82ItelgW0dR4h:-MG7UXINEBP8ICgiQU27:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/600872fc0c63d70b56694df938979081fdfd7c43/CONTRIBUTING.md#L65)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`(except for the License)`
</blockquote></details>

Done.
___
*[CONTRIBUTING.md, line 1 at r2](https://reviewable.io/reviews/pmem/rpma/321#-MG7S_a8EqGdste0QLXw:-MG7heY-09sajTWv1xgH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ea8a2b4c1b9a7dfb0a00df3f0608a054ab192332/CONTRIBUTING.md#L1)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Excuse me, after having added `library (librpma)` there should be 'the' before, so my proposal is the following:
```
# Contributing to the Remote Persistent Memory Access (RPMA) library (librpma)
```
</blockquote></details>

Done.
___
*[CONTRIBUTING.md, line 8 at r2](https://reviewable.io/reviews/pmem/rpma/321#-MG7TI2n5Ja03BE0i_QK:-MG7hibgEvNE_FDb30UQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ea8a2b4c1b9a7dfb0a00df3f0608a054ab192332/CONTRIBUTING.md#L8)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> about RPMA,
> ```

about librpma,
</blockquote></details>

Done.
___
*[CONTRIBUTING.md, line 55 at r2](https://reviewable.io/reviews/pmem/rpma/321#-MG7TZ1O1T1R_lya7Z1r:-MG7hm25DvSte0F89znK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ea8a2b4c1b9a7dfb0a00df3f0608a054ab192332/CONTRIBUTING.md#L55)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

contributions
</blockquote></details>

Done.
___
*[CONTRIBUTING.md, line 63 at r2](https://reviewable.io/reviews/pmem/rpma/321#-MG7TpXBEfHnyflfBHHU:-MG7kabxElTWruzg3OlE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ea8a2b4c1b9a7dfb0a00df3f0608a054ab192332/CONTRIBUTING.md#L63)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`..., but make them the only token in the line.` - maybe you will find a better word than `token` ?
</blockquote></details>

Done.
___
*[CONTRIBUTING.md, line 120 at r2](https://reviewable.io/reviews/pmem/rpma/321#-MG7V--VAeydHHqYiouA:-MG7hCJXB891fzIwEJT5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ea8a2b4c1b9a7dfb0a00df3f0608a054ab192332/CONTRIBUTING.md#L120)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

reports
</blockquote></details>

Done.
___
*[CONTRIBUTING.md, line 122 at r2](https://reviewable.io/reviews/pmem/rpma/321#-MG7V0gkA8Jq9YRHOpFE:-MG7hIzc6gPpS0y11WNQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ea8a2b4c1b9a7dfb0a00df3f0608a054ab192332/CONTRIBUTING.md#L122)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

RPMA
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/321)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/321#-:-MG7m6HhEm2m2j-m_E9Z:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/321)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
