### PR TITLE
examples: use shared completion channel in example 16

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1711)

### CODE REVIEW

**Review by grom72 — APPROVED** [review]
:goat: 

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1711#-:-N0jjwpNCAjzXI5O6GqK:bdycpsm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1711)* status: all files reviewed, 6 unresolved discussions (waiting on @osalyk)

___
*[`examples/16-messages-ping-pong-SHCCH/messages-ping-pong-common.c` line 17 at r1](https://reviewable.io/reviews/pmem/rpma/1711#-N0jlm-MAAMPuCuLSDCG:-N0jlm-MAAMPuCuLSDCH:undefined) ([raw file](https://github.com/pmem/rpma/blob/f0fd9ded02016489690da8784a6d448601932730/examples/16-messages-ping-pong-SHCCH/messages-ping-pong-common.c#L17)):*
> ```C
> 
> static int
> validate_wc(struct ibv_wc *wc, uint64_t *recv,
> ```





_Suggestion:_
```C
validate_wc(struct ibv_wc *wc, uint64_t *recv, bool is_rcq)
```
___
*[`examples/16-messages-ping-pong-SHCCH/messages-ping-pong-common.c` line 21 at r1](https://reviewable.io/reviews/pmem/rpma/1711#-N0jluaABXr8pE-mUB2o:-N0jluaABXr8pE-mUB2p:undefined) ([raw file](https://github.com/pmem/rpma/blob/f0fd9ded02016489690da8784a6d448601932730/examples/16-messages-ping-pong-SHCCH/messages-ping-pong-common.c#L21)):*
> ```C
> {
> 	if (wc->status != IBV_WC_SUCCESS) {
> 		char *func = (wc->opcode == IBV_WC_SEND)? "send" : "recv";
> ```





_Suggestion:_
```C
		char *func = (is_rcq ? "recv" : "send";
```
___
*[`examples/16-messages-ping-pong-SHCCH/messages-ping-pong-common.c` line 29 at r1](https://reviewable.io/reviews/pmem/rpma/1711#-N0jn5eGDKaqB2Ryvpu-:-N0jn5eGDKaqB2Ryvpu0:undefined) ([raw file](https://github.com/pmem/rpma/blob/f0fd9ded02016489690da8784a6d448601932730/examples/16-messages-ping-pong-SHCCH/messages-ping-pong-common.c#L29)):*
> ```C
> 	if (wc->opcode == IBV_WC_SEND) {
> 		*send_cmpl = 1;
> 	} else if (wc->opcode == IBV_WC_RECV) {
> ```





_Suggestion:_
```C
if (is_rcq && wc->opcode == IBV_WC_RECV) {
```
___
*[`examples/16-messages-ping-pong-SHCCH/messages-ping-pong-common.c` line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1711#-N0jnHTl5l-kVu6LLO6w:-N0jnHTl5l-kVu6LLO6x:b-sx84ma) ([raw file](https://github.com/pmem/rpma/blob/f0fd9ded02016489690da8784a6d448601932730/examples/16-messages-ping-pong-SHCCH/messages-ping-pong-common.c#L39)):*
> ```C
> 			return -1;
> 		}
> 		*recv_cmpl = 1;
> ```

obsolete
___
*[`examples/16-messages-ping-pong-SHCCH/messages-ping-pong-common.c` line 56 at r1](https://reviewable.io/reviews/pmem/rpma/1711#-N0jkWGW7wyPpLnLmzeF:-N0jkWGW7wyPpLnLmzeG:bdt2ejr) ([raw file](https://github.com/pmem/rpma/blob/f0fd9ded02016489690da8784a6d448601932730/examples/16-messages-ping-pong-SHCCH/messages-ping-pong-common.c#L56)):*
> ```C
> 	do {
> 		/* wait for the completion to be ready */
> 		if ((ret = rpma_conn_wait(conn, &cq, NULL)))
> ```

why do not we use is_rcq to learn is this a CQ or RCQ?



_Suggestion:_
```C
		if ((ret = rpma_conn_wait(conn, &cq, is_rcq)))
```
___
*[`examples/16-messages-ping-pong-SHCCH/messages-ping-pong-common.c` line 68 at r1](https://reviewable.io/reviews/pmem/rpma/1711#-N0jl9lc9DKZEEdGpQvd:-N0jl9lc9DKZEEdGpQve:undefined) ([raw file](https://github.com/pmem/rpma/blob/f0fd9ded02016489690da8784a6d448601932730/examples/16-messages-ping-pong-SHCCH/messages-ping-pong-common.c#L68)):*
> ```C
> 		/* validate received completions */
> 		for (int i = 0; i < num_got; i++) {
> 			ret = validate_wc(&wc[i], recv, send_cmpl, recv_cmpl);
> ```





_Suggestion:_
```C
			ret = validate_wc(&wc[i], recv, is_rcq);
			if (ret)
				return ret;
			if (is_rcq)
				*recv_cmpl = 1;
			else
				*send_cmpl = 1;
			
```

**Review by grom72 — COMMENTED** [review]
:lgtm_cancel: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1711#-:-N0joQLN4yX9hS3X71Y4:b-qh6tsc)* status: all files reviewed, 6 unresolved discussions (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1711)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72)

___
*[`examples/16-messages-ping-pong-SHCCH/messages-ping-pong-common.c` line 17 at r1](https://reviewable.io/reviews/pmem/rpma/1711#-N0jlm-MAAMPuCuLSDCG:-N0jq6ny5dzJJO9UVmUZ:b-q13rwr) ([raw file](https://github.com/pmem/rpma/blob/f0fd9ded02016489690da8784a6d448601932730/examples/16-messages-ping-pong-SHCCH/messages-ping-pong-common.c#L17)):*
> ```C
> 
> static int
> validate_wc(struct ibv_wc *wc, uint64_t *recv,
> ```

In this example we do not use RCQ
___
*[`examples/16-messages-ping-pong-SHCCH/messages-ping-pong-common.c` line 21 at r1](https://reviewable.io/reviews/pmem/rpma/1711#-N0jluaABXr8pE-mUB2o:-N0jq7pY4Hjm5DdHr_EN:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/f0fd9ded02016489690da8784a6d448601932730/examples/16-messages-ping-pong-SHCCH/messages-ping-pong-common.c#L21)):*
> ```C
> {
> 	if (wc->status != IBV_WC_SUCCESS) {
> 		char *func = (wc->opcode == IBV_WC_SEND)? "send" : "recv";
> ```

.
___
*[`examples/16-messages-ping-pong-SHCCH/messages-ping-pong-common.c` line 29 at r1](https://reviewable.io/reviews/pmem/rpma/1711#-N0jn5eGDKaqB2Ryvpu-:-N0jq8hs1sNqwH2hcgsL:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/f0fd9ded02016489690da8784a6d448601932730/examples/16-messages-ping-pong-SHCCH/messages-ping-pong-common.c#L29)):*
> ```C
> 	if (wc->opcode == IBV_WC_SEND) {
> 		*send_cmpl = 1;
> 	} else if (wc->opcode == IBV_WC_RECV) {
> ```

.
___
*[`examples/16-messages-ping-pong-SHCCH/messages-ping-pong-common.c` line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1711#-N0jnHTl5l-kVu6LLO6w:-N0jqDgrCc6a9Sk5GXVY:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/f0fd9ded02016489690da8784a6d448601932730/examples/16-messages-ping-pong-SHCCH/messages-ping-pong-common.c#L39)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

obsolete
</blockquote></details>

.
___
*[`examples/16-messages-ping-pong-SHCCH/messages-ping-pong-common.c` line 56 at r1](https://reviewable.io/reviews/pmem/rpma/1711#-N0jkWGW7wyPpLnLmzeF:-N0jqFHgDg-7QVoVnhDC:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/f0fd9ded02016489690da8784a6d448601932730/examples/16-messages-ping-pong-SHCCH/messages-ping-pong-common.c#L56)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

why do not we use is_rcq to learn is this a CQ or RCQ?
</blockquote></details>

.
___
*[`examples/16-messages-ping-pong-SHCCH/messages-ping-pong-common.c` line 68 at r1](https://reviewable.io/reviews/pmem/rpma/1711#-N0jl9lc9DKZEEdGpQvd:-N0jqFut-iCL2EgMv_lB:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/f0fd9ded02016489690da8784a6d448601932730/examples/16-messages-ping-pong-SHCCH/messages-ping-pong-common.c#L68)):*
> ```C
> 		/* validate received completions */
> 		for (int i = 0; i < num_got; i++) {
> 			ret = validate_wc(&wc[i], recv, send_cmpl, recv_cmpl);
> ```

.

**Pull request closed without merging**
