### PR TITLE
rpma: make rpma_conn_cfg_set_cq_size thread-safe

### PR DESCRIPTION
**Pull request by grom72**
Requires:
- [x] #1768

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1769)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1769)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1769)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[`src/conn_cfg.c` line 11 at r1](https://reviewable.io/reviews/pmem/rpma/1769#-N3-P8RFDY2t693TxNkS:-N3-P8RFDY2t693TxNkT:b-hxujtb) ([raw file](https://github.com/pmem/rpma/blob/9353298de6b2d7d9884db89e9762d1b152cdc064/src/conn_cfg.c#L11)):*
> ```C
> #include <limits.h>
> #include <stdlib.h>
> #include <stdatomic.h>
> ```

CentOS-7 requires a package for it:
https://github.com/ldorau/rpma/runs/6608890139?check_suite_focus=true
https://github.com/ldorau/rpma/runs/6608889130?check_suite_focus=true



_Code quote:_
```C
#include <stdatomic.h>
```

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1769)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`src/conn_cfg.c` line 11 at r1](https://reviewable.io/reviews/pmem/rpma/1769#-N3-P8RFDY2t693TxNkS:-N30PjOS32f6gpZz8Kqe:b51mkqj) ([raw file](https://github.com/pmem/rpma/blob/9353298de6b2d7d9884db89e9762d1b152cdc064/src/conn_cfg.c#L11)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

CentOS-7 requires a package for it:
https://github.com/ldorau/rpma/runs/6608890139?check_suite_focus=true
https://github.com/ldorau/rpma/runs/6608889130?check_suite_focus=true
</blockquote></details>

Shall I extend the Centos7 setup or shall I convert to the ``__sync_bool_compare_and_swap`` based solution?

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1769)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[`src/conn_cfg.c` line 11 at r1](https://reviewable.io/reviews/pmem/rpma/1769#-N3-P8RFDY2t693TxNkS:-N36XQaMDr-NYKsjcYB3:brt0t01) ([raw file](https://github.com/pmem/rpma/blob/9353298de6b2d7d9884db89e9762d1b152cdc064/src/conn_cfg.c#L11)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Shall I extend the Centos7 setup or shall I convert to the ``__sync_bool_compare_and_swap`` based solution?
</blockquote></details>

`atomic_store()` always succeeds so I think it is better, so I would look for an additional package for CentOS-7 (or even stop supporting CentOS-7 at all)



_Code quote:_
```C
atomic_store
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1769)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[`src/conn_cfg.c` line 11 at r1](https://reviewable.io/reviews/pmem/rpma/1769#-N3-P8RFDY2t693TxNkS:-N33bh9xAHuLj1mZKqXF:bobxi7x) ([raw file](https://github.com/pmem/rpma/blob/9353298de6b2d7d9884db89e9762d1b152cdc064/src/conn_cfg.c#L11)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`atomic_store()` always succeeds so I think it is better, so I would look for an additional package for CentOS-7 (or even stop supporting CentOS-7 at all)
</blockquote></details>

`stdatomic.h` is provided by gcc and clang packages, in case of gcc starting from v4.9:

https://gcc.gnu.org/wiki/C11Status)

but CentOS-7 has gcc v4.8.5:

https://github.com/ldorau/rpma/runs/6608890139?check_suite_focus=true

so if we want to use `atomic_store()` we have to stop supporting CentOS-7 at all ...



_Code quote:_
```C
stdatomic.h
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 5 of 6 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1769)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`src/conn_cfg.c` line 11 at r1](https://reviewable.io/reviews/pmem/rpma/1769#-N3-P8RFDY2t693TxNkS:-N3c7mfeAB6BGiTmrjOB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9353298de6b2d7d9884db89e9762d1b152cdc064/src/conn_cfg.c#L11)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`stdatomic.h` is provided by gcc and clang packages, in case of gcc starting from v4.9:

https://gcc.gnu.org/wiki/C11Status)

but CentOS-7 has gcc v4.8.5:

https://github.com/ldorau/rpma/runs/6608890139?check_suite_focus=true

so if we want to use `atomic_store()` we have to stop supporting CentOS-7 at all ...

</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 6 files at r2, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1769)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1769)* status: 1 of 8 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`CMakeLists.txt` line 159 at r7](https://reviewable.io/reviews/pmem/rpma/1769#-N3chBQT4xRu7VnC87mV:-N3chBQUB9yMSYYKZ_fT:b20f3dk) ([raw file](https://github.com/pmem/rpma/blob/32c47bf0b5317cc74cfde7dad95524f2ac4382d5/CMakeLists.txt#L159)):*
> ```CMake
> 	add_flag(-DATOMIC_STORE_SUPPORTED=1)
> else()
> 	message(WARNING "atomic_store() is NOT supported (too old gcc). Some functions *_set() will not be thread-safe!")
> ```

What about clang?



_Code quote:_
```CMake
(too old gcc)
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1769)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`src/conn_cfg.c` line 11 at r1](https://reviewable.io/reviews/pmem/rpma/1769#-N3-P8RFDY2t693TxNkS:-N3cj7WjAX6IXB2U2NyG:bgnj1v8) ([raw file](https://github.com/pmem/rpma/blob/9353298de6b2d7d9884db89e9762d1b152cdc064/src/conn_cfg.c#L11)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet: https://github.com/ldorau/rpma/runs/6722831423?check_suite_focus=true

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 2 files at r5, 2 of 2 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1769)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[`CMakeLists.txt` line 159 at r7](https://reviewable.io/reviews/pmem/rpma/1769#-N3chBQT4xRu7VnC87mV:-N3dSaXD12-mN7udTHJq:b-l6ur3t) ([raw file](https://github.com/pmem/rpma/blob/32c47bf0b5317cc74cfde7dad95524f2ac4382d5/CMakeLists.txt#L159)):*
> What about clang?
How can we chack this?
___
*[`src/conn_cfg.c` line 11 at r1](https://reviewable.io/reviews/pmem/rpma/1769#-N3-P8RFDY2t693TxNkS:-N3cyy-L4k0aHOawaarg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9353298de6b2d7d9884db89e9762d1b152cdc064/src/conn_cfg.c#L11)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not yet: https://github.com/ldorau/rpma/runs/6722831423?check_suite_focus=true
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1769)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`CMakeLists.txt` line 159 at r7](https://reviewable.io/reviews/pmem/rpma/1769#-N3chBQT4xRu7VnC87mV:-N3dU3R84bdrH2eUPzsq:b-fpwey3) ([raw file](https://github.com/pmem/rpma/blob/32c47bf0b5317cc74cfde7dad95524f2ac4382d5/CMakeLists.txt#L159)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> What about clang?
How can we chack this?
</blockquote></details>

It is already being checked:
https://github.com/pmem/rpma/blob/master/.github/workflows/on_pull_request.yml#L27
https://github.com/pmem/rpma/blob/master/.github/workflows/on_pull_request.yml#L29
so only this message should be fixed:

`(too old gcc/clang compiler)`



_Code quote:_
```CMake
too old gcc
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1769)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[`src/conn_cfg.c` line 11 at r1](https://reviewable.io/reviews/pmem/rpma/1769#-N3-P8RFDY2t693TxNkS:-N3dV2oQADeWw84BRFKn:b-kfl89b) ([raw file](https://github.com/pmem/rpma/blob/9353298de6b2d7d9884db89e9762d1b152cdc064/src/conn_cfg.c#L11)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet - the code has not been changed since my last comment.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r8, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1769)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[`CMakeLists.txt` line 159 at r7](https://reviewable.io/reviews/pmem/rpma/1769#-N3chBQT4xRu7VnC87mV:-N3dY1413zEWsDYHiRHX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/32c47bf0b5317cc74cfde7dad95524f2ac4382d5/CMakeLists.txt#L159)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It is already being checked:
https://github.com/pmem/rpma/blob/master/.github/workflows/on_pull_request.yml#L27
https://github.com/pmem/rpma/blob/master/.github/workflows/on_pull_request.yml#L29
so only this message should be fixed:

`(too old gcc/clang compiler)`
</blockquote></details>

Done.
___
*[`src/conn_cfg.c` line 11 at r1](https://reviewable.io/reviews/pmem/rpma/1769#-N3-P8RFDY2t693TxNkS:-N3dY5w88MEmYBi4HVgQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9353298de6b2d7d9884db89e9762d1b152cdc064/src/conn_cfg.c#L11)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not yet - the code has not been changed since my last comment.
</blockquote></details>

Done.

**Review by osalyk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 6 files at r2, 2 of 4 files at r7, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1769)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`src/conn_cfg.c` line 215 at r9](https://reviewable.io/reviews/pmem/rpma/1769#-N3dYEQM1zi-e6czdbeO:-N3dYEQM1zi-e6czdbeP:b-byfdrb) ([raw file](https://github.com/pmem/rpma/blob/7cc740dc3a4f90bd9b7c2c3a412d764e759b1ff9/src/conn_cfg.c#L215)):*
> ```C
> 
> 	return 0;
> }
> ```

New line
___
*[`tests/drd.supp` line 299 at r9](https://reviewable.io/reviews/pmem/rpma/1769#-N3dYcpe656N9O7lmtno:-N3dYcpe656N9O7lmtnp:b2nhdiv) ([raw file](https://github.com/pmem/rpma/blob/7cc740dc3a4f90bd9b7c2c3a412d764e759b1ff9/tests/drd.supp#L299)):*
> ```
>    fun:rpma_ep_listen
>    ...
> }
> ```

EOF

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1769)* status: 6 of 8 files reviewed, 4 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[`src/conn_cfg.c` line 215 at r9](https://reviewable.io/reviews/pmem/rpma/1769#-N3dYEQM1zi-e6czdbeO:-N3d_z8r2ye_XTQt6bwe:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7cc740dc3a4f90bd9b7c2c3a412d764e759b1ff9/src/conn_cfg.c#L215)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

New line
</blockquote></details>

Done.
___
*[`tests/drd.supp` line 299 at r9](https://reviewable.io/reviews/pmem/rpma/1769#-N3dYcpe656N9O7lmtno:-N3d_zkG5QEGcjq3cbEe:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7cc740dc3a4f90bd9b7c2c3a412d764e759b1ff9/tests/drd.supp#L299)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

EOF
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1769)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @grom72 and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1769#-N3ddQZVEQEWLfOMt7wF:-N3ddQZVEQEWLfOMt7wG:b-ujmq67) (no related file):*
Rebase please

___

**Review by osalyk — COMMENTED** [review]
> Reviewed 2 of 2 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1769)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1769)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @grom72, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1769#-N3ddQZVEQEWLfOMt7wF:-N3dhHBXBYU6ptzEd2cD:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Rebase please
</blockquote></details>

Done.

___

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1769)* status: 5 of 8 files reviewed, 3 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[`tests/multithreaded/conn/rpma_conn_cfg_set_cq_size.c` line 35 at r10](https://reviewable.io/reviews/pmem/rpma/1769#-N3dhEnQ-GqX4NMBbj5w:-N3dirHx2e3stxhUTBf6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d4d2a97d20b3513aa4c247ab50a115cfe2072d2f/tests/multithreaded/conn/rpma_conn_cfg_set_cq_size.c#L35)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Leave this empty line in between, please.
</blockquote></details>

Done.
___
*[`tests/multithreaded/conn/rpma_conn_cfg_set_cq_size.c` line 39 at r10](https://reviewable.io/reviews/pmem/rpma/1769#-N3dhRP_2XTMnlROrWrZ:-N3ditxY1Bgkaa6XZsDK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d4d2a97d20b3513aa4c247ab50a115cfe2072d2f/tests/multithreaded/conn/rpma_conn_cfg_set_cq_size.c#L39)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It should be before the function.
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 3 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1769)* status: 6 of 8 files reviewed, 3 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r10, 2 of 3 files at r11, 1 of 1 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1769)* status: all files reviewed (commit messages unreviewed), 3 unresolved discussions (waiting on @ldorau and @osalyk)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r11, 1 of 1 files at r12, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1769#-:-N3dlfPrCns51EIQMPKU:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1769)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1769)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1769#-:-N3dm61UEWZ0L4ZsL95A:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
