### PR TITLE
test: add possibility to start a server in the MT test framework

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1036)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1036)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tests/multithreaded/common/mtt.h, line 130 at r1](https://reviewable.io/reviews/pmem/rpma/1036#-MZSQ-tdD8cNhdqj3CXy:-MZSQ-tdD8cNhdqj3CXz:b-svp7sz) ([raw file](https://github.com/pmem/rpma/blob/a009d59fad3dbb59ce0ff8fd911843007df40386/tests/multithreaded/common/mtt.h#L130)):*
> ```
> typedef int (*mtt_server_func)(void *prestate);
> ```
Should not we have also id to distinguish different server instances?

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1036)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tests/multithreaded/common/mtt.c, line 246 at r1](https://reviewable.io/reviews/pmem/rpma/1036#-MZSQqY-DCXFeRmHRLpP:-MZSQqY-DCXFeRmHRLpQ:byzq7e5) ([raw file](https://github.com/pmem/rpma/blob/a009d59fad3dbb59ce0ff8fd911843007df40386/tests/multithreaded/common/mtt.c#L246)):*
> ```
> _in_bg
> ```
can we start the server outside the background?
would it be enough to have only simple name `mtt_start_server`

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1036)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[tests/multithreaded/common/mtt.h, line 130 at r1](https://reviewable.io/reviews/pmem/rpma/1036#-MZSQ-tdD8cNhdqj3CXy:-MZSWkDH2dfu7obsVZAo:b6wjuog) ([raw file](https://github.com/pmem/rpma/blob/a009d59fad3dbb59ce0ff8fd911843007df40386/tests/multithreaded/common/mtt.h#L130)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> typedef int (*mtt_server_func)(void *prestate);
> ```
Should not we have also id to distinguish different server instances?
</blockquote></details>

different server instances ?  I think one server can start many threads and listen for many connections, but there should be always only one server process. Am I wrong?
___
*[tests/multithreaded/common/mtt.c, line 246 at r1](https://reviewable.io/reviews/pmem/rpma/1036#-MZSQqY-DCXFeRmHRLpP:-MZSXTEv8zGy-mlfYHAj:b-buo2k1) ([raw file](https://github.com/pmem/rpma/blob/a009d59fad3dbb59ce0ff8fd911843007df40386/tests/multithreaded/common/mtt.c#L246)):*
> outside the background?

What do you mean by `outside the background` ?

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1036)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tests/multithreaded/common/mtt.h, line 130 at r1](https://reviewable.io/reviews/pmem/rpma/1036#-MZSQ-tdD8cNhdqj3CXy:-MZSkgnYBSevltGsUQbI:b-u8puym) ([raw file](https://github.com/pmem/rpma/blob/a009d59fad3dbb59ce0ff8fd911843007df40386/tests/multithreaded/common/mtt.h#L130)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

different server instances ?  I think one server can start many threads and listen for many connections, but there should be always only one server process. Am I wrong?
</blockquote></details>

Q: what will be easier: to set up one server and keep n:1 relation or 
start n servers and keep 1:1 relation between server and client

Q: what if we later want to test server-side calls?
___
*[tests/multithreaded/common/mtt.c, line 246 at r1](https://reviewable.io/reviews/pmem/rpma/1036#-MZSQqY-DCXFeRmHRLpP:-MZSkbGCDYOJYdMT1sTl:b-fvdq9q) ([raw file](https://github.com/pmem/rpma/blob/a009d59fad3dbb59ce0ff8fd911843007df40386/tests/multithreaded/common/mtt.c#L246)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> outside the background?

What do you mean by `outside the background` ?
</blockquote></details>

I mean i propose to remove `_in_bg` suffix

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1036)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1036)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tests/multithreaded/common/mtt.c, line 246 at r1](https://reviewable.io/reviews/pmem/rpma/1036#-MZSQqY-DCXFeRmHRLpP:-MZStZjL4MOz-XGrpl4o:b-k1y5pj) ([raw file](https://github.com/pmem/rpma/blob/a009d59fad3dbb59ce0ff8fd911843007df40386/tests/multithreaded/common/mtt.c#L246)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I mean i propose to remove `_in_bg` suffix
</blockquote></details>

OK. Done.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1036)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[tests/multithreaded/common/mtt.h, line 130 at r1](https://reviewable.io/reviews/pmem/rpma/1036#-MZSQ-tdD8cNhdqj3CXy:-MZSttAA6G3yf2Rrj2q5:b11s4n1) ([raw file](https://github.com/pmem/rpma/blob/a009d59fad3dbb59ce0ff8fd911843007df40386/tests/multithreaded/common/mtt.h#L130)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Q: what will be easier: to set up one server and keep n:1 relation or 
start n servers and keep 1:1 relation between server and client

Q: what if we later want to test server-side calls?
</blockquote></details>

IMHO the current solution is the simplest one. It is simpler to start one server than to start many servers of course.

Besides, if you want to test MT-safety you have to start many threads in one process and not many processes ...

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1036)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1036)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tests/multithreaded/common/mtt.h, line 130 at r2](https://reviewable.io/reviews/pmem/rpma/1036#-MZTav5CB85OFqCmhZ-6:-MZTav5CB85OFqCmhZ-7:b-y2y4hg) ([raw file](https://github.com/pmem/rpma/blob/836e5e67a8989fcadcff2f265ce4fdc42507dc31/tests/multithreaded/common/mtt.h#L130)):*
> ```objc
>  * - prestate - a pointer to the test-provided data.
>  */
> typedef int (*mtt_server_func)(void *prestate);
> ```

I think you should call it more generically. Since it can also be used for testing the server-side, the function provided here may actually implement a client. ;-)
___
*[tests/multithreaded/common/mtt.c, line 298 at r2](https://reviewable.io/reviews/pmem/rpma/1036#-MZTbat87LhfeOy_wh7R:-MZTbat98-76VtJ-7BWu:b-okjx6s) ([raw file](https://github.com/pmem/rpma/blob/836e5e67a8989fcadcff2f265ce4fdc42507dc31/tests/multithreaded/common/mtt.c#L298)):*
> ```C
> 			return -1;
> 		}
> 	}
> ```

I see you have a single server for a test. Do you think I can use the MTT framework to implement multiple threads on the "server-side"? :-D

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1036)* status: all files reviewed, 5 unresolved discussions (waiting on @ldorau)

___
*[tests/multithreaded/common/mtt.h, line 125 at r2](https://reviewable.io/reviews/pmem/rpma/1036#-MZTfRu75tHcgNpiTfMz:-MZTfRu75tHcgNpiTfN-:b-1nxz86) ([raw file](https://github.com/pmem/rpma/blob/836e5e67a8989fcadcff2f265ce4fdc42507dc31/tests/multithreaded/common/mtt.h#L125)):*
> ```objc
> 
> /*
>  * mtt_server_func -- a function type used to start the server process
> ```

a function type used for the child process e.g. as another side of the connection.
___
*[tests/multithreaded/common/mtt.h, line 130 at r2](https://reviewable.io/reviews/pmem/rpma/1036#-MZTav5CB85OFqCmhZ-6:-MZTfNmTAzBskyTfAEsX:b-7kgzj3) ([raw file](https://github.com/pmem/rpma/blob/836e5e67a8989fcadcff2f265ce4fdc42507dc31/tests/multithreaded/common/mtt.h#L130)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think you should call it more generically. Since it can also be used for testing the server-side, the function provided here may actually implement a client. ;-)
</blockquote></details>

mtt_another_side_func? mtt_child_proc_func?
___
*[tests/multithreaded/common/mtt.c, line 264 at r2](https://reviewable.io/reviews/pmem/rpma/1036#-MZTgKxp3ufntQtSoLQ8:-MZTgKxp3ufntQtSoLQ9:b28j8wk) ([raw file](https://github.com/pmem/rpma/blob/836e5e67a8989fcadcff2f265ce4fdc42507dc31/tests/multithreaded/common/mtt.c#L264)):*
> ```C
> 	}
> 
> 	/* the parent returns PID of server */
> ```

the parent returns the PID of the child process
___
*[tests/multithreaded/common/mtt.c, line 420 at r2](https://reviewable.io/reviews/pmem/rpma/1036#-MZTgwXOBSFJyRpjbkN3:-MZTgwXOBSFJyRpjbkN4:b-ac89) ([raw file](https://github.com/pmem/rpma/blob/836e5e67a8989fcadcff2f265ce4fdc42507dc31/tests/multithreaded/common/mtt.c#L420)):*
> ```C
> 		/* check if the server is still running */
> 		if (kill(pid_server, 0) == 0) {
> 			/* kill the server process */
> ```

the child process

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1036)* status: 0 of 2 files reviewed, 5 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tests/multithreaded/common/mtt.h, line 125 at r2](https://reviewable.io/reviews/pmem/rpma/1036#-MZTfRu75tHcgNpiTfMz:-MZWTaUZE6EJlwJZl_fb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/836e5e67a8989fcadcff2f265ce4fdc42507dc31/tests/multithreaded/common/mtt.h#L125)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

a function type used for the child process e.g. as another side of the connection.
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mtt.h, line 130 at r2](https://reviewable.io/reviews/pmem/rpma/1036#-MZTav5CB85OFqCmhZ-6:-MZWSInu3PY5DZ_oFvfx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/836e5e67a8989fcadcff2f265ce4fdc42507dc31/tests/multithreaded/common/mtt.h#L130)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

mtt_another_side_func? mtt_child_proc_func?
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mtt.c, line 264 at r2](https://reviewable.io/reviews/pmem/rpma/1036#-MZTgKxp3ufntQtSoLQ8:-MZWS_Bj5DAnC8Ofw_iC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/836e5e67a8989fcadcff2f265ce4fdc42507dc31/tests/multithreaded/common/mtt.c#L264)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

the parent returns the PID of the child process
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mtt.c, line 298 at r2](https://reviewable.io/reviews/pmem/rpma/1036#-MZTbat87LhfeOy_wh7R:-MZWCOiL865xkqC7xmke:b-exknk0) ([raw file](https://github.com/pmem/rpma/blob/836e5e67a8989fcadcff2f265ce4fdc42507dc31/tests/multithreaded/common/mtt.c#L298)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I see you have a single server for a test. Do you think I can use the MTT framework to implement multiple threads on the "server-side"? :-D
</blockquote></details>

My intention was to have multiple threads tested in the parent process.
___
*[tests/multithreaded/common/mtt.c, line 420 at r2](https://reviewable.io/reviews/pmem/rpma/1036#-MZTgwXOBSFJyRpjbkN3:-MZWSzOc6DXD2oxo1xQV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/836e5e67a8989fcadcff2f265ce4fdc42507dc31/tests/multithreaded/common/mtt.c#L420)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

the child process
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1036)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tests/multithreaded/common/mtt.c, line 298 at r2](https://reviewable.io/reviews/pmem/rpma/1036#-MZTbat87LhfeOy_wh7R:-MZWUbumBHKQqXAs8RGN:bgmpj23) ([raw file](https://github.com/pmem/rpma/blob/836e5e67a8989fcadcff2f265ce4fdc42507dc31/tests/multithreaded/common/mtt.c#L298)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

My intention was to have multiple threads tested in the parent process.
</blockquote></details>

I know. But I can imagine having multiple threads on both sides. :-)
___
*[tests/multithreaded/common/mtt.c, line 281 at r3](https://reviewable.io/reviews/pmem/rpma/1036#-MZWUycf3VksxAaEbA5Z:-MZWUycf3VksxAaEbA5_:bkfxnbn) ([raw file](https://github.com/pmem/rpma/blob/102231259c11855ddc5cca0b7ec2e100d4871078/tests/multithreaded/common/mtt.c#L281)):*
> ```C
> 	unsigned threads_num_to_join = 0;
> 	unsigned threads_num_to_fini = 0;
> 	int pid_child = 0;
> ```

I know both pid and child are nouns. But it seems to me that child is the main concept similarly to the thread. So, I recommend rename it to child_pid.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1036)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/common/mtt.c, line 298 at r2](https://reviewable.io/reviews/pmem/rpma/1036#-MZTbat87LhfeOy_wh7R:-MZWXjhX5gtDAN_ZJf7b:b-9yglp4) ([raw file](https://github.com/pmem/rpma/blob/836e5e67a8989fcadcff2f265ce4fdc42507dc31/tests/multithreaded/common/mtt.c#L298)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I know. But I can imagine having multiple threads on both sides. :-)
</blockquote></details>

Hmm, I am afraid it may be not possible yet. I suppose valgrind will track only the parent process. I will check that.
___
*[tests/multithreaded/common/mtt.c, line 281 at r3](https://reviewable.io/reviews/pmem/rpma/1036#-MZWUycf3VksxAaEbA5Z:-MZWXiti83ruLgQuIg7F:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/102231259c11855ddc5cca0b7ec2e100d4871078/tests/multithreaded/common/mtt.c#L281)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I know both pid and child are nouns. But it seems to me that child is the main concept similarly to the thread. So, I recommend rename it to child_pid.
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1036)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tests/multithreaded/common/mtt.c, line 298 at r2](https://reviewable.io/reviews/pmem/rpma/1036#-MZTbat87LhfeOy_wh7R:-MZWZOcR5eRTY2CPrm5w:brx0yca) ([raw file](https://github.com/pmem/rpma/blob/836e5e67a8989fcadcff2f265ce4fdc42507dc31/tests/multithreaded/common/mtt.c#L298)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Hmm, I am afraid it may be not possible yet. I suppose valgrind will track only the parent process. I will check that.
</blockquote></details>

I do not expect Valgrind to follow both processes. But would be nice. :-) the key is the ease of implementing multithread parties on both sides. :-)

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1036)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1036#-MZWeN1JEfAc0KxqBePz:-MZWeN1JEfAc0KxqBeQ-:b-3y0ltp) (no related file):*
Wouldn't be easier to spawn just a thread?

Sorry for so late architectural comment. It just come to me.

---

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1036)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tests/multithreaded/common/mtt.c, line 298 at r2](https://reviewable.io/reviews/pmem/rpma/1036#-MZTbat87LhfeOy_wh7R:-MZWeN4M2T-jYa7JZN3v:bgm0443) ([raw file](https://github.com/pmem/rpma/blob/836e5e67a8989fcadcff2f265ce4fdc42507dc31/tests/multithreaded/common/mtt.c#L298)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I do not expect Valgrind to follow both processes. But would be nice. :-) the key is the ease of implementing multithread parties on both sides. :-)
</blockquote></details>

Perhaps we should talk about a peer, not about the server, and in this case, I could imagine the scenario where the client part is run in the background, waiting for the server to be started establishing a connection, and waiting for the server to disconnecting when a test is finished.

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1036)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tests/multithreaded/common/mtt.c, line 298 at r2](https://reviewable.io/reviews/pmem/rpma/1036#-MZTbat87LhfeOy_wh7R:-MZWibUQEX52HYEvvHhW:b-zdkzgn) ([raw file](https://github.com/pmem/rpma/blob/836e5e67a8989fcadcff2f265ce4fdc42507dc31/tests/multithreaded/common/mtt.c#L298)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Perhaps we should talk about a peer, not about the server, and in this case, I could imagine the scenario where the client part is run in the background, waiting for the server to be started establishing a connection, and waiting for the server to disconnecting when a test is finished.
</blockquote></details>

No reference to the server here anymore. The peer is somehow reserved in the context of RPMA TBH. If we will stick to forking the process I think keeping it as general as it is now is good enough. No roles assigned.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1036)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1036#-MZWeN1JEfAc0KxqBePz:-MZWleANCrU5ZzlNywb_:b-302sl0) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Wouldn't be easier to spawn just a thread?

Sorry for so late architectural comment. It just come to me.
</blockquote></details>

It would be easier, but not correct, because valgrind would check MT-safety of server vs. client, but they should be separate processes, not threads.

---
___
*[tests/multithreaded/common/mtt.c, line 298 at r2](https://reviewable.io/reviews/pmem/rpma/1036#-MZTbat87LhfeOy_wh7R:-MZWmOEP4Wp86gC6Dnr6:b-h6ages) ([raw file](https://github.com/pmem/rpma/blob/836e5e67a8989fcadcff2f265ce4fdc42507dc31/tests/multithreaded/common/mtt.c#L298)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

No reference to the server here anymore. The peer is somehow reserved in the context of RPMA TBH. If we will stick to forking the process I think keeping it as general as it is now is good enough. No roles assigned.
</blockquote></details>

OK, @janekmi Is any issue to be fixed here?

**Review by ldorau — COMMENTED** [review]
The CircleCI build failed, because of https://github.com/pmem/rpma/pull/1039

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1036#-:-MZWpLNsACWGI_6hxM6j:bar8vqg)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1036)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1036#-MZWeN1JEfAc0KxqBePz:-MZWuOk64cluWkcOKQbj:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It would be easier, but not correct, because valgrind would check MT-safety of server vs. client, but they should be separate processes, not threads.
</blockquote></details>

Done.

---
___
*[tests/multithreaded/common/mtt.c, line 298 at r2](https://reviewable.io/reviews/pmem/rpma/1036#-MZTbat87LhfeOy_wh7R:-MZWuN5m-jQjw5M9ni3s:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/836e5e67a8989fcadcff2f265ce4fdc42507dc31/tests/multithreaded/common/mtt.c#L298)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK, @janekmi Is any issue to be fixed here?
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1036#-:-MZWy7ir3YqGlD_lR74r:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
