### PR TITLE
rpma: rpma_conn_req_recv scaffolding

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/317)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/317)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[src/include/librpma.h, line 548 at r1](https://reviewable.io/reviews/pmem/rpma/317#-MG2zfQ28jr4Yb9UrV0b:-MG2zfQ28jr4Yb9UrV0c:bgbzz7x) ([raw file](https://github.com/pmem/rpma/blob/9526af8a253b4ebaeba830a423742aed6f71cd00/src/include/librpma.h#L548)):*
> ```
> Initialize the receive operation which prepares
> ```

Initialize the receive operation. It prepares ...

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/317)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/include/librpma.h, line 548 at r1](https://reviewable.io/reviews/pmem/rpma/317#-MG2zfQ28jr4Yb9UrV0b:-MG3-XCp3yM-H3IipwKq:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9526af8a253b4ebaeba830a423742aed6f71cd00/src/include/librpma.h#L548)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> Initialize the receive operation which prepares
> ```

Initialize the receive operation. It prepares ...
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/317)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/317#-:-MG30VfX7-Yrf_Wirjn9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
Missing reference to flags documentation in all API calls, anyhow :lgtm: 

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/317#-:-MG3Cs6k1ffAEbaLKU6v:bcmim35)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
