### PR TITLE
tools: introduce REMOTE_CMD_PRE/_POST

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/933)

### CODE REVIEW

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/933)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/933)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/rpma_fio_bench.sh, line 341 at r1](https://reviewable.io/reviews/pmem/rpma/933#-MVa3XRdDmVm8NovY_Zo:-MVa3XRdDmVm8NovY_Zp:bo6p9pq) ([raw file](https://github.com/pmem/rpma/blob/23ca5b14d8aa9ce23cc2a06eebab418cd3dbbb5d/tools/perf/rpma_fio_bench.sh#L341)):*
> ```
> 			fi
> 			# copy config to the server
> ```

Maybe add an empty line in between ?
___
*[tools/perf/rpma_fio_bench.sh, line 460 at r1](https://reviewable.io/reviews/pmem/rpma/933#-MVa3vne0yZf9NnjAfAe:-MVa3vne0yZf9NnjAfAf:b-j5aqew) ([raw file](https://github.com/pmem/rpma/blob/23ca5b14d8aa9ce23cc2a06eebab418cd3dbbb5d/tools/perf/rpma_fio_bench.sh#L460)):*
> ```
> of the remote job NUMA
> ```

of the remote NUMA node `REMOTE_JOB_NUMA`

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/933)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/rpma_fio_bench.sh, line 464 at r1](https://reviewable.io/reviews/pmem/rpma/933#-MVa4qhf2MroxR9ysAA_:-MVa4qhf2MroxR9ysAAa:b5g96cu) ([raw file](https://github.com/pmem/rpma/blob/23ca5b14d8aa9ce23cc2a06eebab418cd3dbbb5d/tools/perf/rpma_fio_bench.sh#L464)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> export REMOTE_JOB_NUMA_CPULIST=$( \
> 	sshpass -p "$REMOTE_PASS" -v ssh -o StrictHostKeyChecking=no \
> 	$REMOTE_USER@$SERVER_IP \
> 	"cat /sys/devices/system/node/node${REMOTE_JOB_NUMA}/cpulist")
> ```
</details>


I think the value of  `REMOTE_JOB_NUMA_CPULIST` should be validated. If any of the commands inside fails, it can contain an error message.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/933)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/rpma_fio_bench.sh, line 341 at r1](https://reviewable.io/reviews/pmem/rpma/933#-MVa3XRdDmVm8NovY_Zo:-MVa5n_j2_fq8vNSssoH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/23ca5b14d8aa9ce23cc2a06eebab418cd3dbbb5d/tools/perf/rpma_fio_bench.sh#L341)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 			fi
> 			# copy config to the server
> ```

Maybe add an empty line in between ?
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 460 at r1](https://reviewable.io/reviews/pmem/rpma/933#-MVa3vne0yZf9NnjAfAe:-MVaTUIZ4ld5a5roJdr3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/23ca5b14d8aa9ce23cc2a06eebab418cd3dbbb5d/tools/perf/rpma_fio_bench.sh#L460)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> of the remote job NUMA
> ```

of the remote NUMA node `REMOTE_JOB_NUMA`
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 464 at r1](https://reviewable.io/reviews/pmem/rpma/933#-MVa4qhf2MroxR9ysAA_:-MVaTUtP6b91V0z0ndhD:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/23ca5b14d8aa9ce23cc2a06eebab418cd3dbbb5d/tools/perf/rpma_fio_bench.sh#L464)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> export REMOTE_JOB_NUMA_CPULIST=$( \
> 	sshpass -p "$REMOTE_PASS" -v ssh -o StrictHostKeyChecking=no \
> 	$REMOTE_USER@$SERVER_IP \
> 	"cat /sys/devices/system/node/node${REMOTE_JOB_NUMA}/cpulist")
> ```

I think the value of  `REMOTE_JOB_NUMA_CPULIST` should be validated. If any of the commands inside fails, it can contain an error message.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/933#-:-MVahv1Y2SSnTZugj4m9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/933#-:-MVajyjn0E1SYXfzXulX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
