### PR TITLE
tools: add spacing before the figures' titles

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1239)

### CODE REVIEW

**Comment by ldorau** [comment]
image

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1239#-:-MiRZPIJBdOD9Vd6Zf45:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1239)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/lib/figure.py, line 265 at r2](https://reviewable.io/reviews/pmem/rpma/1239#-MiR_01JE7af3IaPSz_5:-MiR_01JE7af3IaPSz_6:b-xwuw2x) ([raw file](https://github.com/pmem/rpma/blob/c380f7def7e153716248162abe98c084be412d49/tools/perf/lib/figure.py#L265)):*
> ```Python
>     def to_html(self, figno):
>         """Combine a Figure's png and data table into a single HTML snippet"""
>         html = "<h4 style='margin-top:80.0pt'>Figure {}. {}</h4>". \
> ```

It should go here: https://github.com/pmem/rpma/blob/master/tools/perf/templates/layout.html#L13

```css
h4 {
    margin-top: 80pt;
}
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1239)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/figure.py, line 265 at r2](https://reviewable.io/reviews/pmem/rpma/1239#-MiR_01JE7af3IaPSz_5:-MiR_cAh1tSZKF9PuhHe:bu4c51g) ([raw file](https://github.com/pmem/rpma/blob/c380f7def7e153716248162abe98c084be412d49/tools/perf/lib/figure.py#L265)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It should go here: https://github.com/pmem/rpma/blob/master/tools/perf/templates/layout.html#L13

```css
h4 {
    margin-top: 80pt;
}
```
</blockquote></details>

But in this way it will affect all <h4> tags ... Do we really want that?
I think only figures' titles should have this spacing.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1239)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/figure.py, line 265 at r2](https://reviewable.io/reviews/pmem/rpma/1239#-MiR_01JE7af3IaPSz_5:-MiRaA_T8f11K3FfMyK-:b98kas8) ([raw file](https://github.com/pmem/rpma/blob/c380f7def7e153716248162abe98c084be412d49/tools/perf/lib/figure.py#L265)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

But in this way it will affect all <h4> tags ... Do we really want that?
I think only figures' titles should have this spacing.
</blockquote></details>

But in this way it will affect all `<h4>` tags ... Do we really want that?
I think only figures' titles should have this spacing.

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1239)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/lib/figure.py, line 265 at r2](https://reviewable.io/reviews/pmem/rpma/1239#-MiR_01JE7af3IaPSz_5:-MiRaGib0YFjDIWGT_Jd:b-2hix6i) ([raw file](https://github.com/pmem/rpma/blob/c380f7def7e153716248162abe98c084be412d49/tools/perf/lib/figure.py#L265)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

But in this way it will affect all `<h4>` tags ... Do we really want that?
I think only figures' titles should have this spacing.
</blockquote></details>

So far only figures use h4. If you want to be really really sure you can add here a `class='figure'`.
So the css will look as follows:

```css
h4.figure {
    margin-top: 80pt;
}
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1239)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @janekmi and @osalyk)

___
*[tools/perf/lib/figure.py, line 265 at r2](https://reviewable.io/reviews/pmem/rpma/1239#-MiR_01JE7af3IaPSz_5:-MiRbTUI830r6uZa_-u1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c380f7def7e153716248162abe98c084be412d49/tools/perf/lib/figure.py#L265)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

So far only figures use h4. If you want to be really really sure you can add here a `class='figure'`.
So the css will look as follows:

```css
h4.figure {
    margin-top: 80pt;
}
```
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1239)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1239#-:-MiRcK06CkwNek0W5Ayp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
