### PR TITLE
tools: take out the menu from the layout to a dedicated file

### PR DESCRIPTION
**Pull request by janekmi**
Requires:
- [x] #832

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/833)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/833#-:-MSaZgaKE5OhrJfNmGyK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/833#-:-MSbGV82CPu5dMguKdcy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/833)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/create_report.py, line 25 at r3](https://reviewable.io/reviews/pmem/rpma/833#-MSbsl7c-hSniUzjhTTl:-MSbsl7c-hSniUzjhTTm:b-p4e8f9) ([raw file](https://github.com/pmem/rpma/blob/4e671a7a8adb29702f4c4bd953b0ec8b16e544b9/tools/create_report.py#L25)):*
> ```
> CONTENTS = [
>      \
>     'audience', 'authors', 'bios', 'configuration_common', \
> ```

```
CONTENTS = [  \
    'audience', 'authors', 'bios', 'configuration_common', \
```

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/833)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/create_report.py, line 25 at r3](https://reviewable.io/reviews/pmem/rpma/833#-MSbsl7c-hSniUzjhTTl:-MSbu8E9BkpP8jG-_Vru:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4e671a7a8adb29702f4c4bd953b0ec8b16e544b9/tools/create_report.py#L25)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> CONTENTS = [
>      \
>     'audience', 'authors', 'bios', 'configuration_common', \
> ```

```
CONTENTS = [  \
    'audience', 'authors', 'bios', 'configuration_common', \
```

</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/833)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/create_report.py, line 25 at r3](https://reviewable.io/reviews/pmem/rpma/833#-MSbsl7c-hSniUzjhTTl:-MSbvXpp3rPUOyBk5IpK:brrow4x) ([raw file](https://github.com/pmem/rpma/blob/4e671a7a8adb29702f4c4bd953b0ec8b16e544b9/tools/create_report.py#L25)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`CONTENTS = [  \`

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/833)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/833#-:-MSbwOjU6CiVrEBlubWJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
