### PR TITLE
tools: add randread, randwrite and randrw to fio rw modes

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1481)

### CODE REVIEW

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1481#-:-Mt2F6LL6KDDJdAQC5VT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1481#-:-Mt2F6LL6KDDJdAQC5VT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1481#-:-Mt2FxVa8NX8czVS8SW5:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1481#-:-Mt2FI2w1GcSgrHotspR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
