### PR TITLE
examples: fix syntax in README.md of the 05 example

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/466)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/466)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[examples/05-flush-to-persistent/README.md, line 31 at r1](https://reviewable.io/reviews/pmem/rpma/466#-MIJNr2JC_ayCUc_taCU:-MIJNr2JC_ayCUc_taCV:bb6nve2) ([raw file](https://github.com/pmem/rpma/blob/a959ca539feced73a02fcb8d35e2c101161c1257/examples/05-flush-to-persistent/README.md#L31)):*
> ```Markdown
> 
> ```bash
> [user@server]$ ./server $server_address $port [<pmem-path>] [direct-pmem-write]
> ```

< >?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/466)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[examples/05-flush-to-persistent/README.md, line 31 at r1](https://reviewable.io/reviews/pmem/rpma/466#-MIJNr2JC_ayCUc_taCU:-MIJOUVR-W0Ub4PkkGk8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a959ca539feced73a02fcb8d35e2c101161c1257/examples/05-flush-to-persistent/README.md#L31)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

< >?
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/466#-:-MIJP6DL-XGnj38gsLTw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/466#-:-MIJWxdL11UNMZ0LqF5i:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
