### PR TITLE
test: fix creating the descriptor in example-02-read-to-volatile

### PR DESCRIPTION
**Pull request by ldorau**
The current code works by accident.
The private data has to contain a descriptor (a buffer with serialized data),
because it will be read by rpma_mr_remote_from_descriptor() in the client.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/388)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/388)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/388#-MHEwDQO6qNKDak5sdj9:-MHEwDQO6qNKDak5sdjA:bbsw7eb) ([raw file](https://github.com/pmem/rpma/blob/561dfd2987fa5e0d0bc9ec5a4c5458e5e27912ec/tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c#L39)):*
> ```
> create_descriptor
> ```
why do we have here custom function instead of using rpma_mr_remote_from_descriptor
this is an integration test I do not see a point to have a separate implementation of this functionality
___
*[tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c, line 162 at r1](https://reviewable.io/reviews/pmem/rpma/388#-MHExQOK9Urlypf1KD7w:-MHExQOK9Urlypf1KD7x:bs7nwcc) ([raw file](https://github.com/pmem/rpma/blob/561dfd2987fa5e0d0bc9ec5a4c5458e5e27912ec/tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c#L162)):*
> ```
> rpma_mr_descriptor desc, *pdesc = &desc;
> ```
___
*[tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c, line 163 at r1](https://reviewable.io/reviews/pmem/rpma/388#-MHEwbwm8YZR-JFR-zaD:-MHEwbwm8YZR-JFR-zaE:b96ny4l) ([raw file](https://github.com/pmem/rpma/blob/561dfd2987fa5e0d0bc9ec5a4c5458e5e27912ec/tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c#L163)):*
> ```
> create_descriptor((&buff, &desc);
> ```
```
rpma_mr_remote_from_descriptor(&buff, &pdesc);
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/388)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/388#-MHEwDQO6qNKDak5sdj9:-MHFGHHA73KS8-ENH6Em:b-3977pw) ([raw file](https://github.com/pmem/rpma/blob/561dfd2987fa5e0d0bc9ec5a4c5458e5e27912ec/tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c#L39)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> create_descriptor
> ```
why do we have here custom function instead of using rpma_mr_remote_from_descriptor
this is an integration test I do not see a point to have a separate implementation of this functionality
</blockquote></details>

1) We are creating the descriptor, so if any, we would have to use `rpma_mr_get_descriptor()`, not `rpma_mr_remote_from_descriptor()`
2) We cannot use `rpma_mr_get_descriptor(struct rpma_mr_local *mr, rpma_mr_descriptor *desc)` because it takes `struct rpma_mr_local *mr` as an argument, but `struct rpma_mr_local mr` is a private, internal structure, so we cannot use it. We have defined `struct private_data_buffer` instead.
___
*[tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c, line 162 at r1](https://reviewable.io/reviews/pmem/rpma/388#-MHExQOK9Urlypf1KD7w:-MHFHFizAqJnhV_IRvv7:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/561dfd2987fa5e0d0bc9ec5a4c5458e5e27912ec/tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c#L162)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> rpma_mr_descriptor desc, *pdesc = &desc;
> ```

</blockquote></details>

.
___
*[tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c, line 163 at r1](https://reviewable.io/reviews/pmem/rpma/388#-MHEwbwm8YZR-JFR-zaD:-MHFHGaV99V_4f8Ghbmo:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/561dfd2987fa5e0d0bc9ec5a4c5458e5e27912ec/tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c#L163)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> create_descriptor((&buff, &desc);
> ```
```
rpma_mr_remote_from_descriptor(&buff, &pdesc);
```
</blockquote></details>

.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/388)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/388#-MHEwDQO6qNKDak5sdj9:-MHG49gx14q0kpXp1lKb:bvaq8nx) ([raw file](https://github.com/pmem/rpma/blob/561dfd2987fa5e0d0bc9ec5a4c5458e5e27912ec/tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c#L39)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

1) We are creating the descriptor, so if any, we would have to use `rpma_mr_get_descriptor()`, not `rpma_mr_remote_from_descriptor()`
2) We cannot use `rpma_mr_get_descriptor(struct rpma_mr_local *mr, rpma_mr_descriptor *desc)` because it takes `struct rpma_mr_local *mr` as an argument, but `struct rpma_mr_local mr` is a private, internal structure, so we cannot use it. We have defined `struct private_data_buffer` instead.
</blockquote></details>

so in this case I would prefer to have a function that creates a descriptor based on explicit given 4 values instead of heaving one cryptic private_data_buffer structure

or
;)
set of macros that define such a structure ...
#define DESCRIPTOR (x,y,z,a) {x, .... 
char buff[] = DESCRIPTOR(1,3,56,789)

https://code.woboq.org/userspace/glibc/string/endian.h.html
___
*[tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c, line 21 at r2](https://reviewable.io/reviews/pmem/rpma/388#-MHG3UjZ86CJ2PXMUDeX:-MHG3UjZ86CJ2PXMUDeY:bjoi34e) ([raw file](https://github.com/pmem/rpma/blob/636691cd2999ae1f7495be5c8a483196fe83c49c/tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c#L21)):*
> ```
> struct private_data_buffer
> ```
would it be easier for reading just to copy here a struct rpma_mr_remote => struct rpma_mr_remote_mock
struct rpma_mr_remote {
	uint64_t raddr; /* the base virtual address of the memory region */
	uint64_t size; /* the size of the memory being registered */
	uint32_t rkey; /* remote key of the memory region */
	enum rpma_mr_plt plt; /* placement of the memory region */
};
private data buffer term has already well defined semantic in librpma (connection private data)

Do we need this structure at all?
___
*[tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c, line 39 at r2](https://reviewable.io/reviews/pmem/rpma/388#-MHG2kOc4-Kc0pGEqX3v:-MHG2kOd2OFAFfJtOSb9:b-h2bm34) ([raw file](https://github.com/pmem/rpma/blob/636691cd2999ae1f7495be5c8a483196fe83c49c/tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c#L39)):*
> ```
> struct private_data_buffer *priv_data
> ```
```
const struct private_data_buffer const *priv_data  
```
to indicate what is input what is output

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/388)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @grom72)

___
*[tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/388#-MHEwDQO6qNKDak5sdj9:-MHKjPyr0Q2dXfXTm0hj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/561dfd2987fa5e0d0bc9ec5a4c5458e5e27912ec/tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c#L39)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

so in this case I would prefer to have a function that creates a descriptor based on explicit given 4 values instead of heaving one cryptic private_data_buffer structure

or
;)
set of macros that define such a structure ...
#define DESCRIPTOR (x,y,z,a) {x, .... 
char buff[] = DESCRIPTOR(1,3,56,789)

https://code.woboq.org/userspace/glibc/string/endian.h.html

</blockquote></details>

Done.
___
*[tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c, line 162 at r1](https://reviewable.io/reviews/pmem/rpma/388#-MHExQOK9Urlypf1KD7w:-MHKjRMNEigE9_kNe2ax:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/561dfd2987fa5e0d0bc9ec5a4c5458e5e27912ec/tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c#L162)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c, line 163 at r1](https://reviewable.io/reviews/pmem/rpma/388#-MHEwbwm8YZR-JFR-zaD:-MHKjRsv7D58Xpj-H01N:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/561dfd2987fa5e0d0bc9ec5a4c5458e5e27912ec/tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c#L163)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c, line 21 at r2](https://reviewable.io/reviews/pmem/rpma/388#-MHG3UjZ86CJ2PXMUDeX:-MHKjSae1r9oYz-EGALW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/636691cd2999ae1f7495be5c8a483196fe83c49c/tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c#L21)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> struct private_data_buffer
> ```
would it be easier for reading just to copy here a struct rpma_mr_remote => struct rpma_mr_remote_mock
struct rpma_mr_remote {
	uint64_t raddr; /* the base virtual address of the memory region */
	uint64_t size; /* the size of the memory being registered */
	uint32_t rkey; /* remote key of the memory region */
	enum rpma_mr_plt plt; /* placement of the memory region */
};
private data buffer term has already well defined semantic in librpma (connection private data)

Do we need this structure at all?
</blockquote></details>

Done.
___
*[tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c, line 39 at r2](https://reviewable.io/reviews/pmem/rpma/388#-MHG2kOc4-Kc0pGEqX3v:-MHKjQhrALgAHKOjyTfi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/636691cd2999ae1f7495be5c8a483196fe83c49c/tests/integration/example-02-read-to-volatile/example-02-read-to-volatile.c#L39)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> struct private_data_buffer *priv_data
> ```
```
const struct private_data_buffer const *priv_data  
```
to indicate what is input what is output
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/388#-:-MHNFZcI4Y4is11GY3qI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/388#-:-MHO7KtWBNJxDSRe77Sm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
