### PR TITLE
common: replace echos with set -x when installing packages

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [ ] #2118 

---

This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/2120)

### CODE REVIEW

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2120)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2120#-:-NQAa5J44HeVGq4U-pPp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2120)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2120)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @yangx-jy)

___
*[`utils/docker/run-build.sh` line 249 at r3](https://reviewable.io/reviews/pmem/rpma/2120#-NQPF6M-6pZF9oLM4NC1:-NQPImqJ-Vr3VKE2xF2c:bw561ol) ([raw file](https://github.com/pmem/rpma/blob/8c9ad133b6830a1a2660444b203728e69d9f11f7/utils/docker/run-build.sh#L249)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

@ldorau 

One more question that is not related to this PR.
Do you know why we need to add `&& true` for `rpm` command?
</blockquote></details>

There is a bug here. It should be `|| true` to prevent from failing the build when this command fails (like `set +e`). See: https://github.com/pmem/rpma/pull/2121

**Pull request merged**
