### PR TITLE
tools: update standard CSV description

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/639)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/639)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/csv2standardized.py, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/639#-MO5gd6U0oS-BG99rIuB:-MO5gd6V2vSxw_L0biad:bncc157) ([raw file](https://github.com/pmem/rpma/blob/59a432a92ec56c9c76c29daab685f59f2eb156f5/tools/csv2standardized.py#L17)):*
> ```Python
> # The standardized-CSV format columns are (in order):
> # - threads - number of threads [1] (optional)
> # - bs - block size [B]
> ```

'bs' is the first column

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/639)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tools/csv2standardized.py, line 23 at r1](https://reviewable.io/reviews/pmem/rpma/639#-MO5jtzF8T43zi2wQjFH:-MO5jtzF8T43zi2wQjFI:b-k2gsrl) ([raw file](https://github.com/pmem/rpma/blob/59a432a92ec56c9c76c29daab685f59f2eb156f5/tools/csv2standardized.py#L23)):*
> ```
> avg
> ```

avg. (https://writingexplained.org/english-abbreviations/average)

Why not just `average`?
___
*[tools/csv2standardized.py, line 32 at r1](https://reviewable.io/reviews/pmem/rpma/639#-MO5k6EY3PIX5rizs4i5:-MO5k6EY3PIX5rizs4i6:bgmkckb) ([raw file](https://github.com/pmem/rpma/blob/59a432a92ec56c9c76c29daab685f59f2eb156f5/tools/csv2standardized.py#L32)):*
> ```
> avg
> ```

.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/639)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[tools/csv2standardized.py, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/639#-MO5gd6U0oS-BG99rIuB:-MO6FJsC2AoLX34p2FpI:bg3zesm) ([raw file](https://github.com/pmem/rpma/blob/59a432a92ec56c9c76c29daab685f59f2eb156f5/tools/csv2standardized.py#L17)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

'bs' is the first column
</blockquote></details>

You have to consider all possible outputs:

```python
fio_output_names = [
    'threads', 'bs', 'ops', 'lat_min', 'lat_max', 'lat_avg', 'lat_stdev', 
    'lat_pctl_99.0', 'lat_pctl_99.9', 'lat_pctl_99.99', 'lat_pctl_99.999',
    'bw_min', 'bw_max', 'bw_avg']

ib_lat_output_names = [
    'bs', 'ops', 'lat_min', 'lat_max', 'lat_mode', 'lat_avg', 'lat_stdev',
    'lat_pctl_99.0', 'lat_pctl_99.9']

ib_bw_output_names = [
    'threads', 'bs', 'ops', 'bw_avg', 'msg_rate']
```

Where you can see `threads` is first but it is optional for now. This is what I meant.
___
*[tools/csv2standardized.py, line 23 at r1](https://reviewable.io/reviews/pmem/rpma/639#-MO5jtzF8T43zi2wQjFH:-MO6Fw0-4h2kC0Ad1ip8:bbrznxs) ([raw file](https://github.com/pmem/rpma/blob/59a432a92ec56c9c76c29daab685f59f2eb156f5/tools/csv2standardized.py#L23)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> avg
> ```

avg. (https://writingexplained.org/english-abbreviations/average)

Why not just `average`?
</blockquote></details>

Because I like consistency... If we are using min, max so why not write just avg instead of average.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/639)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tools/csv2standardized.py, line 23 at r1](https://reviewable.io/reviews/pmem/rpma/639#-MO5jtzF8T43zi2wQjFH:-MO6H-TRCC9_XeAJzg3C:b-bmj5e7) ([raw file](https://github.com/pmem/rpma/blob/59a432a92ec56c9c76c29daab685f59f2eb156f5/tools/csv2standardized.py#L23)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Because I like consistency... If we are using min, max so why not write just avg instead of average.
</blockquote></details>

So it should be `avg.` (https://writingexplained.org/english-abbreviations/average)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/639#-:-MO6HCD59NmhNwCxAPQ4:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/csv2standardized.py, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/639#-MO5gd6U0oS-BG99rIuB:-MO6H8EV6sugzvgLdK08:b-xd3vm6) ([raw file](https://github.com/pmem/rpma/blob/59a432a92ec56c9c76c29daab685f59f2eb156f5/tools/csv2standardized.py#L17)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You have to consider all possible outputs:

```python
fio_output_names = [
    'threads', 'bs', 'ops', 'lat_min', 'lat_max', 'lat_avg', 'lat_stdev', 
    'lat_pctl_99.0', 'lat_pctl_99.9', 'lat_pctl_99.99', 'lat_pctl_99.999',
    'bw_min', 'bw_max', 'bw_avg']

ib_lat_output_names = [
    'bs', 'ops', 'lat_min', 'lat_max', 'lat_mode', 'lat_avg', 'lat_stdev',
    'lat_pctl_99.0', 'lat_pctl_99.9']

ib_bw_output_names = [
    'threads', 'bs', 'ops', 'bw_avg', 'msg_rate']
```

Where you can see `threads` is first but it is optional for now. This is what I meant.
</blockquote></details>

You're right.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/639)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tools/csv2standardized.py, line 23 at r1](https://reviewable.io/reviews/pmem/rpma/639#-MO5jtzF8T43zi2wQjFH:-MO6JBCSAz-ApFQ79N3H:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/59a432a92ec56c9c76c29daab685f59f2eb156f5/tools/csv2standardized.py#L23)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

So it should be `avg.` (https://writingexplained.org/english-abbreviations/average)
</blockquote></details>

Done.
___
*[tools/csv2standardized.py, line 32 at r1](https://reviewable.io/reviews/pmem/rpma/639#-MO5k6EY3PIX5rizs4i5:-MO6JBq76aJF7wHpSezq:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/59a432a92ec56c9c76c29daab685f59f2eb156f5/tools/csv2standardized.py#L32)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> avg
> ```

.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/639)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/639#-:-MO6KRC5E77vhRuVwVp_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
