### PR TITLE
test: standardize the code style in test files

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/2014)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 46 of 46 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2014)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[`CHANGELOG.md` line 20 at r1](https://reviewable.io/reviews/pmem/rpma/2014#-NBBjzip8ZbfSRxCNjOc:-NBBjzip8ZbfSRxCNjOd:bikm8lw) ([raw file](https://github.com/pmem/rpma/blob/1eff079706227ddef243f30256c8d5494a248e68/CHANGELOG.md#L20)):*
> ```Markdown
> ### Changed
> - unified coding style in the source files
> - unified coding style in the test files
> ```

```
### Changed
- unified coding style in the source and the test files
```



_Code quote:_
```Markdown
### Changed
- unified coding style in the source files
- unified coding style in the test files
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2014)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`CHANGELOG.md` line 20 at r1](https://reviewable.io/reviews/pmem/rpma/2014#-NBBjzip8ZbfSRxCNjOc:-NBBkk57Cazw92V4I06m:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1eff079706227ddef243f30256c8d5494a248e68/CHANGELOG.md#L20)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
### Changed
- unified coding style in the source and the test files
```
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 46 of 46 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2014)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2014#-:-NBBn9M3EuHMCqWMEXv8:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2014#-:-NBBo5oE365c6KYG325H:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
