### PR TITLE
test: add suppression documentation

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1776)

### CODE REVIEW

**Review by osalyk — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1776)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @haichangsi and @osalyk)

___
*[`tests/drd.supp` line 24 at r1](https://reviewable.io/reviews/pmem/rpma/1776#-N33uWNe8iXQVHuR9F3n:-N33uWNe8iXQVHuR9F3o:b-867xyf) ([raw file](https://github.com/pmem/rpma/blob/03622e4ead8ef88396ee2c2cce604ed76c89746f/tests/drd.supp#L24)):*
> ```
> # 	    (NULL == (info = localtime(&ts.tv_sec)))) {
> # 		memcpy(buf, error_message, sizeof(error_message));
> # 		return;
> ```

Please remove.



_Code quote:_
```
# static void
# get_timestamp_prefix(char *buf, size_t buf_size)
# {
# 	struct tm *info;
# 	char date[24];
# 	struct timespec ts;
# 	long usec;
#
# 	const char error_message[] = "[time error] ";
#
# 	if (clock_gettime(CLOCK_REALTIME, &ts) ||
# 	    (NULL == (info = localtime(&ts.tv_sec)))) {
# 		memcpy(buf, error_message, sizeof(error_message));
# 		return;
# 	}
```
___
*[`tests/helgrind.supp` line 23 at r1](https://reviewable.io/reviews/pmem/rpma/1776#-N33uhNw0vi2pZ5mAqgl:-N33uhNw0vi2pZ5mAqgm:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/03622e4ead8ef88396ee2c2cce604ed76c89746f/tests/helgrind.supp#L23)):*
> ```
> # 	if (clock_gettime(CLOCK_REALTIME, &ts) ||
> # 	    (NULL == (info = localtime(&ts.tv_sec)))) {
> # 		memcpy(buf, error_message, sizeof(error_message));
> ```

.



_Code quote:_
```
# static void
# get_timestamp_prefix(char *buf, size_t buf_size)
# {
# 	struct tm *info;
# 	char date[24];
# 	struct timespec ts;
# 	long usec;
#
# 	const char error_message[] = "[time error] ";
#
# 	if (clock_gettime(CLOCK_REALTIME, &ts) ||
# 	    (NULL == (info = localtime(&ts.tv_sec)))) {
# 		memcpy(buf, error_message, sizeof(error_message));
# 		return;
# 	}
```

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1776)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @haichangsi, @ldorau, and @osalyk)

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1776)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[`tests/drd.supp` line 24 at r1](https://reviewable.io/reviews/pmem/rpma/1776#-N33uWNe8iXQVHuR9F3n:-N36JFNl-f6F8nnAatqF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/03622e4ead8ef88396ee2c2cce604ed76c89746f/tests/drd.supp#L24)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Please remove.
</blockquote></details>

Done.
___
*[`tests/helgrind.supp` line 23 at r1](https://reviewable.io/reviews/pmem/rpma/1776#-N33uhNw0vi2pZ5mAqgl:-N36JKmL36VGiKvY_nEL:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/03622e4ead8ef88396ee2c2cce604ed76c89746f/tests/helgrind.supp#L23)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by osalyk — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1776)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1776)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1776)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1776)* status: all files reviewed, 4 unresolved discussions (waiting on @haichangsi)

___
*[`tests/drd.supp` line 12 at r2](https://reviewable.io/reviews/pmem/rpma/1776#-N3QkwK3E5_sUi3j9Olu:-N3QkwK3E5_sUi3j9Olv:bw8mg6p) ([raw file](https://github.com/pmem/rpma/blob/29dbf19a9ed8d9320addffc1e1adb3eae571b163/tests/drd.supp#L12)):*
> ```
> #
> # The rpma_log_default_function uses static void get_timestamp_prefix(char *buf, size_t buf_size).
> # Definition:
> ```

I think this code snippet is redundant, because it does not add nor explain anything. It is enough just to describe that in words, for example:
- `rpma_log_default_function()` calls `get_timestamp_prefix()` that calls `localtime()` which is not thread-safe, because ...



_Code quote:_
```
# Definition:
# static void
# get_timestamp_prefix(char *buf, size_t buf_size)
# {
# 	struct tm *info;
# 	char date[24];
# 	struct timespec ts;
# 	long usec;
#
# 	const char error_message[] = "[time error] ";
#
# 	if (clock_gettime(CLOCK_REALTIME, &ts) ||
# 	    (NULL == (info = localtime(&ts.tv_sec)))) {
# 		memcpy(buf, error_message, sizeof(error_message));
# 		return;
# 	}
```
___
*[`tests/drd.supp` line 33 at r2](https://reviewable.io/reviews/pmem/rpma/1776#-N3Qkz7DB5sVoeUI1_Uz:-N3Qkz7DB5sVoeUI1_V-:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/29dbf19a9ed8d9320addffc1e1adb3eae571b163/tests/drd.supp#L33)):*
> ```
> # {
> #   static struct tm tt;
> #   ... setting tt member variables
> ```

.



_Code quote:_
```
# struct tm *localtime(time_t *timer)
# {
#   static struct tm tt;
#   ... setting tt member variables
#   return &tt;
# }
```
___
*[`tests/helgrind.supp` line 13 at r2](https://reviewable.io/reviews/pmem/rpma/1776#-N3Qj_x6BM68Jx-wRzde:-N3Qj_x6BM68Jx-wRzdf:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/29dbf19a9ed8d9320addffc1e1adb3eae571b163/tests/helgrind.supp#L13)):*
> ```
> # The rpma_log_default_function uses static void get_timestamp_prefix(char *buf, size_t buf_size).
> # Definition:
> # static void
> ```

.



_Code quote:_
```
# Definition:
# static void
# get_timestamp_prefix(char *buf, size_t buf_size)
# {
# 	struct tm *info;
# 	char date[24];
# 	struct timespec ts;
# 	long usec;
#
# 	const char error_message[] = "[time error] ";
#
# 	if (clock_gettime(CLOCK_REALTIME, &ts) ||
# 	    (NULL == (info = localtime(&ts.tv_sec)))) {
# 		memcpy(buf, error_message, sizeof(error_message));
# 		return;
# 	}
```
___
*[`tests/helgrind.supp` line 34 at r2](https://reviewable.io/reviews/pmem/rpma/1776#-N3QkfgkAO4p8T5Kgqf8:-N3Qkfgl5FQdT4OQq9lN:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/29dbf19a9ed8d9320addffc1e1adb3eae571b163/tests/helgrind.supp#L34)):*
> ```
> #   static struct tm tt;
> #   ... setting tt member variables
> #   return &tt;
> ```

.



_Code quote:_
```
# struct tm *localtime(time_t *timer)
# {
#   static struct tm tt;
#   ... setting tt member variables
#   return &tt;
# }
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1776)* status: 0 of 2 files reviewed, 4 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[`tests/drd.supp` line 12 at r2](https://reviewable.io/reviews/pmem/rpma/1776#-N3QkwK3E5_sUi3j9Olu:-N46YFa91_ZlUkK9e5wz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/29dbf19a9ed8d9320addffc1e1adb3eae571b163/tests/drd.supp#L12)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I think this code snippet is redundant, because it does not add nor explain anything. It is enough just to describe that in words, for example:
- `rpma_log_default_function()` calls `get_timestamp_prefix()` that calls `localtime()` which is not thread-safe, because ...
</blockquote></details>

Done.
___
*[`tests/drd.supp` line 33 at r2](https://reviewable.io/reviews/pmem/rpma/1776#-N3Qkz7DB5sVoeUI1_Uz:-N46YGJ5CCyraCevY8BC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/29dbf19a9ed8d9320addffc1e1adb3eae571b163/tests/drd.supp#L33)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`tests/helgrind.supp` line 13 at r2](https://reviewable.io/reviews/pmem/rpma/1776#-N3Qj_x6BM68Jx-wRzde:-N46YH-X08GsQLFQsjjV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/29dbf19a9ed8d9320addffc1e1adb3eae571b163/tests/helgrind.supp#L13)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`tests/helgrind.supp` line 34 at r2](https://reviewable.io/reviews/pmem/rpma/1776#-N3QkfgkAO4p8T5Kgqf8:-N46YHaa5qDC6AtsJmZi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/29dbf19a9ed8d9320addffc1e1adb3eae571b163/tests/helgrind.supp#L34)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1776)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1776)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request closed without merging**
