### PR TITLE
test: adapt rpma_perr_cfg_new mtt to the new test template

### PR DESCRIPTION
**Pull request by grom72**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1767)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1767)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1767)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1767)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1767)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[`tests/multithreaded/peer/rpma_peer_cfg_new.c` line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1767#-N3drijO4hO1U0gUM9Pv:-N3dspzl2LGygFALgjKA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8b17233b22af903b316289097e1fc7755530607b/tests/multithreaded/peer/rpma_peer_cfg_new.c#L2)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

2021-2022
</blockquote></details>

Done.
___
*[`tests/multithreaded/peer/rpma_peer_cfg_new.c` line 8 at r1](https://reviewable.io/reviews/pmem/rpma/1767#-N3drpsJ16jA9J4bES2a:-N3dsqLH0243OmBuF0cA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8b17233b22af903b316289097e1fc7755530607b/tests/multithreaded/peer/rpma_peer_cfg_new.c#L8)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

empty line
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1767)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @ldorau and @osalyk)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1767#-:-N3du3WW0I3S7w3VlyGw:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1767)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1767)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
