### PR TITLE
common: tools: ib_read_lat.sh

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/605)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/605)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/ib_read_lat.sh, line 42 at r1](https://reviewable.io/reviews/pmem/rpma/605#-MNO3Thx6vJhUPDpWjBR:-MNO3Thy8ixlPBEGo3vg:bpodltw) ([raw file](https://github.com/pmem/rpma/blob/092389d0cd9fc7f74bde073b62f67cc0d26c4ccd/tools/ib_read_lat.sh#L42)):*
Doubled:
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> elif [ -z "$REMOTE_PASS" ]; then
>     usage "REMOTE_PASS not set"
> elif [ -z "$REMOTE_PASS" ]; then
>     usage "REMOTE_PASS not set"
> ```
</details>

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/605)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/ib_read_lat.sh, line 42 at r1](https://reviewable.io/reviews/pmem/rpma/605#-MNO3Thx6vJhUPDpWjBR:-MNO3sQ28Jw1baAScws5:blar4s3) ([raw file](https://github.com/pmem/rpma/blob/092389d0cd9fc7f74bde073b62f67cc0d26c4ccd/tools/ib_read_lat.sh#L42)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Doubled:

> ```
> elif [ -z "$REMOTE_PASS" ]; then
>     usage "REMOTE_PASS not set"
> elif [ -z "$REMOTE_PASS" ]; then
>     usage "REMOTE_PASS not set"
> ```

</blockquote></details>

I meant: repeated

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/605)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tools/ib_read_lat.sh, line 45 at r1](https://reviewable.io/reviews/pmem/rpma/605#-MNO7C25A31kbodjfNCh:-MNO7C25A31kbodjfNCi:bslblhm) ([raw file](https://github.com/pmem/rpma/blob/092389d0cd9fc7f74bde073b62f67cc0d26c4ccd/tools/ib_read_lat.sh#L45)):*
> ```Shell
> elif [ -z "$REMOTE_JOB_NUMA" ]; then
>     usage "REMOTE_JOB_NUMA not set"
> fi
> ```

we need LOCAL_ REMOTE_DEVICE for these machines where not the first ib interface is used
___
*[tools/ib_read_lat.sh, line 54 at r1](https://reviewable.io/reviews/pmem/rpma/605#-MNO6wsV-xtc59nQXrJI:-MNO6wsV-xtc59nQXrJJ:b-p1bmrr) ([raw file](https://github.com/pmem/rpma/blob/092389d0cd9fc7f74bde073b62f67cc0d26c4ccd/tools/ib_read_lat.sh#L54)):*
> ```
>  
> ```
-R to enable on machines where rdma_cm QP are required
___
*[tools/ib_read_lat.sh, line 58 at r1](https://reviewable.io/reviews/pmem/rpma/605#-MNO768I8Cda8aRKJ7pD:-MNO768I8Cda8aRKJ7pE:b-8mdvt2) ([raw file](https://github.com/pmem/rpma/blob/092389d0cd9fc7f74bde073b62f67cc0d26c4ccd/tools/ib_read_lat.sh#L58)):*
> ```Shell
>     # XXX --duration hides detailed statistics
>     echo "[size: $ds, iters: $ITERATIONS] (duration: ~60s)"
>     numactl -N $NUMA ib_read_lat --size $ds --iters $ITERATIONS \
> ```

-R 
.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/605)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tools/ib_read_lat.sh, line 45 at r1](https://reviewable.io/reviews/pmem/rpma/605#-MNO7C25A31kbodjfNCh:-MNOA9uu9jWztmqYb6ZN:b-duu3jf) ([raw file](https://github.com/pmem/rpma/blob/092389d0cd9fc7f74bde073b62f67cc0d26c4ccd/tools/ib_read_lat.sh#L45)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

we need LOCAL_ REMOTE_DEVICE for these machines where not the first ib interface is used
</blockquote></details>

I will do separate PR about this

**Review by grom72 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/605#-:-MNOAGdF0tudk0TdCASQ:bdycpsm)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/605)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/ib_read_lat.sh, line 42 at r1](https://reviewable.io/reviews/pmem/rpma/605#-MNO3Thx6vJhUPDpWjBR:-MNOBxLQ0hBHPcd8EfVw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/092389d0cd9fc7f74bde073b62f67cc0d26c4ccd/tools/ib_read_lat.sh#L42)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I meant: repeated
</blockquote></details>

Done.
___
*[tools/ib_read_lat.sh, line 54 at r1](https://reviewable.io/reviews/pmem/rpma/605#-MNO6wsV-xtc59nQXrJI:-MNOCwK22m0Nd4f6OnOB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/092389d0cd9fc7f74bde073b62f67cc0d26c4ccd/tools/ib_read_lat.sh#L54)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
>  
> ```
-R to enable on machines where rdma_cm QP are required
</blockquote></details>

Done.
___
*[tools/ib_read_lat.sh, line 58 at r1](https://reviewable.io/reviews/pmem/rpma/605#-MNO768I8Cda8aRKJ7pD:-MNOCxxA6AI2D44RFRDM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/092389d0cd9fc7f74bde073b62f67cc0d26c4ccd/tools/ib_read_lat.sh#L58)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

-R 
.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/605)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/605#-:-MNOMNF76Q-gV3p-H5Eo:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/605)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tools/ib_read_lat.sh, line 18 at r3](https://reviewable.io/reviews/pmem/rpma/605#-MNOa9rH8bfqAOLmcK55:-MNOa9rH8bfqAOLmcK56:b-7p6ikl) ([raw file](https://github.com/pmem/rpma/blob/65684559e86c83427c323b203619b7820fb751e1/tools/ib_read_lat.sh#L18)):*
> ```
> OUTPUT=ib_read_lat-$(date +%y-%m-%d-%H%M%S).csv
> LOG_ERR=/dev/shm/ib_read_lat_err.log
> ```

```
TIMESTAMP=$(date +%y-%m-%d-%H%M%S)
OUTPUT=ib_read_lat-${TIMESTAMP}.csv
LOG_ERR=/dev/shm/ib_read_lat_err-${TIMESTAMP}.log
```

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/605)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/ib_read_lat.sh, line 33 at r3](https://reviewable.io/reviews/pmem/rpma/605#-MNOcCQl-4c81eHfsSTl:-MNOcCQl-4c81eHfsSTm:b126kgh) ([raw file](https://github.com/pmem/rpma/blob/65684559e86c83427c323b203619b7820fb751e1/tools/ib_read_lat.sh#L33)):*
> ```Shell
>     echo "export REMOTE_JOB_NUMA=0"
>     echo "export REMOTE_AUX_PARAMS="
>     exit 1
> ```

can we add here a real examples of AUX_PARAM?
```
echo
echo "export  AUX_PARAM=-d mlx5_0 -R"
echo "export  REMOTE_AUX_PARAM=-d mlx5_0 -R"
```

perhaps at the end
after a separate line?

**Review by grom72 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/605#-:-MNOoNWX2eX1-WFfFGYx:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/605)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/ib_read_lat.sh, line 18 at r3](https://reviewable.io/reviews/pmem/rpma/605#-MNOa9rH8bfqAOLmcK55:-MNOoysv7-QjjAmI-Dt3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/65684559e86c83427c323b203619b7820fb751e1/tools/ib_read_lat.sh#L18)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> OUTPUT=ib_read_lat-$(date +%y-%m-%d-%H%M%S).csv
> LOG_ERR=/dev/shm/ib_read_lat_err.log
> ```

```
TIMESTAMP=$(date +%y-%m-%d-%H%M%S)
OUTPUT=ib_read_lat-${TIMESTAMP}.csv
LOG_ERR=/dev/shm/ib_read_lat_err-${TIMESTAMP}.log
```


</blockquote></details>

Done.
___
*[tools/ib_read_lat.sh, line 33 at r3](https://reviewable.io/reviews/pmem/rpma/605#-MNOcCQl-4c81eHfsSTl:-MNOpRSU7F-Nn1pI0in-:b-1jpk6e) ([raw file](https://github.com/pmem/rpma/blob/65684559e86c83427c323b203619b7820fb751e1/tools/ib_read_lat.sh#L33)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

can we add here a real examples of AUX_PARAM?
```
echo
echo "export  AUX_PARAM=-d mlx5_0 -R"
echo "export  REMOTE_AUX_PARAM=-d mlx5_0 -R"
```

perhaps at the end
after a separate line?

</blockquote></details>

I think we can just add them as they are. All of these lines are only examples. 😉

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/605)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/605#-:-MNOrQJe9OOtgFdH1sC9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/605#-:-MNSU6l00hpGavhLv4lz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
