### PR TITLE
rpma: librpma.7: Direct Write to PMem

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/484)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/484)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 46 at r1](https://reviewable.io/reviews/pmem/rpma/484#-MIPeempB5VkLKHAOhwO:-MIPeempB5VkLKHAOhwP:bmjwlbp) ([raw file](https://github.com/pmem/rpma/blob/14f043729ce6a684a29b93ebd68e0964d93972df/src/include/librpma.h#L46)):*
> ```
> remote peers to write to platform's
> ```
RDMA HW to access persistent memory directly

I'm not sure if we talk about local or remote peer here
___
*[src/include/librpma.h, line 51 at r1](https://reviewable.io/reviews/pmem/rpma/484#-MIPPcuw4IDIQCL8HVQT:-MIPPcuw4IDIQCL8HVQU:b-tak1zn) ([raw file](https://github.com/pmem/rpma/blob/14f043729ce6a684a29b93ebd68e0964d93972df/src/include/librpma.h#L51)):*
> ```
> platforms
> ```
Intel platforms
___
*[src/include/librpma.h, line 52 at r1](https://reviewable.io/reviews/pmem/rpma/484#-MIPe-lz3oIazYavdPOi:-MIPe-m-DXBKdeOoZdVD:bdn3elr) ([raw file](https://github.com/pmem/rpma/blob/14f043729ce6a684a29b93ebd68e0964d93972df/src/include/librpma.h#L52)):*
> ```
> Direct Data
> ```
Intel Direct Data

**Review by grom72 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/484#-:-MIPhiFXBiLYtZ-Y7r4U:b6e9vsk)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/484)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/484)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[src/include/librpma.h, line 46 at r1](https://reviewable.io/reviews/pmem/rpma/484#-MIPeempB5VkLKHAOhwO:-MIPtBtK749Pezmy6jEj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/14f043729ce6a684a29b93ebd68e0964d93972df/src/include/librpma.h#L46)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> remote peers to write to platform's
> ```
RDMA HW to access persistent memory directly

I'm not sure if we talk about local or remote peer here
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 51 at r1](https://reviewable.io/reviews/pmem/rpma/484#-MIPPcuw4IDIQCL8HVQT:-MIPtIfc5ddCVbeW5SmW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/14f043729ce6a684a29b93ebd68e0964d93972df/src/include/librpma.h#L51)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> platforms
> ```
Intel platforms
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 52 at r1](https://reviewable.io/reviews/pmem/rpma/484#-MIPe-lz3oIazYavdPOi:-MIPtJby7AZljRdLoHY2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/14f043729ce6a684a29b93ebd68e0964d93972df/src/include/librpma.h#L52)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Direct Data
> ```
Intel Direct Data
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/484)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/484)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 45 at r2](https://reviewable.io/reviews/pmem/rpma/484#-MISGfcv-In7xh_KFFKT:-MISGfcv-In7xh_KFFKU:b8ipoof) ([raw file](https://github.com/pmem/rpma/blob/0bc6384e8ed43605645e0063e982983027ed8ad2/src/include/librpma.h#L45)):*
> ```
> of the platform
> ```

of a platform
___
*[src/include/librpma.h, line 46 at r2](https://reviewable.io/reviews/pmem/rpma/484#-MISH1Zp5AM5kvM8sdC3:-MISH1Zp5AM5kvM8sdC4:bilvtho) ([raw file](https://github.com/pmem/rpma/blob/0bc6384e8ed43605645e0063e982983027ed8ad2/src/include/librpma.h#L46)):*
> ```
> RDMA-capable network interface
> ```

an RDMA-capable network interface
___
*[src/include/librpma.h, line 48 at r2](https://reviewable.io/reviews/pmem/rpma/484#-MISHJSc6osICNnZpsVw:-MISHJSc6osICNnZpsVx:borhxuz) ([raw file](https://github.com/pmem/rpma/blob/0bc6384e8ed43605645e0063e982983027ed8ad2/src/include/librpma.h#L48)):*
> ```
> e.g. caching mechanisms
>  * existing on the data way
> ```

`on the data's way.`

or maybe even shorter:

`e.g. existing caching mechanisms.`

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/484)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 49 at r2](https://reviewable.io/reviews/pmem/rpma/484#-MISIV69Ew0TLxWqeqg5:-MISIV69Ew0TLxWqeqg6:bnrqsp8) ([raw file](https://github.com/pmem/rpma/blob/0bc6384e8ed43605645e0063e982983027ed8ad2/src/include/librpma.h#L49)):*
> ```
> ... is possible when it is not may corrupt ...
> ```

Incorrect sentence, I do not understand it at all.
___
*[src/include/librpma.h, line 51 at r2](https://reviewable.io/reviews/pmem/rpma/484#-MISIsQ39cZJhAVLiha1:-MISIsQ39cZJhAVLiha2:brjg15w) ([raw file](https://github.com/pmem/rpma/blob/0bc6384e8ed43605645e0063e982983027ed8ad2/src/include/librpma.h#L51)):*
> ```
> to do to enable
> ```

to do in order to enable

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/484)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/include/librpma.h, line 45 at r2](https://reviewable.io/reviews/pmem/rpma/484#-MISGfcv-In7xh_KFFKT:-MISplYz98i8hZsmTnbO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0bc6384e8ed43605645e0063e982983027ed8ad2/src/include/librpma.h#L45)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> of the platform
> ```

of a platform
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 46 at r2](https://reviewable.io/reviews/pmem/rpma/484#-MISH1Zp5AM5kvM8sdC3:-MISpzd39nRyQoqwu7C0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0bc6384e8ed43605645e0063e982983027ed8ad2/src/include/librpma.h#L46)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> RDMA-capable network interface
> ```

an RDMA-capable network interface
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 48 at r2](https://reviewable.io/reviews/pmem/rpma/484#-MISHJSc6osICNnZpsVw:-MISq-eT4fY0GBbYk-v8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0bc6384e8ed43605645e0063e982983027ed8ad2/src/include/librpma.h#L48)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> e.g. caching mechanisms
>  * existing on the data way
> ```

`on the data's way.`

or maybe even shorter:

`e.g. existing caching mechanisms.`

</blockquote></details>

Done.
___
*[src/include/librpma.h, line 49 at r2](https://reviewable.io/reviews/pmem/rpma/484#-MISIV69Ew0TLxWqeqg5:-MISr4mc1kBt2dcweNiK:b4lcx7p) ([raw file](https://github.com/pmem/rpma/blob/0bc6384e8ed43605645e0063e982983027ed8ad2/src/include/librpma.h#L49)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> ... is possible when it is not may corrupt ...
> ```

Incorrect sentence, I do not understand it at all.
</blockquote></details>

How about it now? Better?
___
*[src/include/librpma.h, line 51 at r2](https://reviewable.io/reviews/pmem/rpma/484#-MISIsQ39cZJhAVLiha1:-MISra2u1n7MOtGqYkXr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0bc6384e8ed43605645e0063e982983027ed8ad2/src/include/librpma.h#L51)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> to do to enable
> ```

to do in order to enable
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/484)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[src/include/librpma.h, line 49 at r2](https://reviewable.io/reviews/pmem/rpma/484#-MISIV69Ew0TLxWqeqg5:-MIT1aMP02Q9EoMjkJmv:bnmmihb) ([raw file](https://github.com/pmem/rpma/blob/0bc6384e8ed43605645e0063e982983027ed8ad2/src/include/librpma.h#L49)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

How about it now? Better?
</blockquote></details>

Much better :-) It is OK now.
___
*[src/include/librpma.h, line 50 at r3](https://reviewable.io/reviews/pmem/rpma/484#-MIT1gILBpoLnkadAEI3:-MIT1gILBpoLnkadAEI4:b-uv6u0u) ([raw file](https://github.com/pmem/rpma/blob/0dc44288ab3890c55ef9c02bb590fca7d1479f3b/src/include/librpma.h#L50)):*
> ```
> PMem so **Direct
> ```

`... PMem, so that is why **Direct ...`

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/484)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/include/librpma.h, line 50 at r3](https://reviewable.io/reviews/pmem/rpma/484#-MIT1gILBpoLnkadAEI3:-MITAgYN8kigM_Ozs6iy:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0dc44288ab3890c55ef9c02bb590fca7d1479f3b/src/include/librpma.h#L50)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> PMem so **Direct
> ```

`... PMem, so that is why **Direct ...`
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/484)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/484#-:-MITCAAi08umHU5F-HT-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/484#-:-MITERLW2fdxTXNOoHUe:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/484)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
