### PR TITLE
rpma: adopt usage_to_access to support iWARP specificity

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1044)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1044)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[src/peer.c, line 32 at r1](https://reviewable.io/reviews/pmem/rpma/1044#-MZwF3R47rVFw0KEIUbi:-MZwF3R47rVFw0KEIUbj:bmfs4d3) ([raw file](https://github.com/pmem/rpma/blob/ad6a127eaaa2797deb7a32e905cb1f7b471b6305/src/peer.c#L32)):*
> ```C
> };
> 
> /* helper functions */
> ```

This is not a helper any more. It is an internal API now.
___
*[src/peer.c, line 54 at r1](https://reviewable.io/reviews/pmem/rpma/1044#-MZwFElP22S2exvzAt6K:-MZwFElP22S2exvzAt6L:bywamzy) ([raw file](https://github.com/pmem/rpma/blob/ad6a127eaaa2797deb7a32e905cb1f7b471b6305/src/peer.c#L54)):*
> ```C
> 		access |= IBV_ACCESS_LOCAL_WRITE;
> 
> 		/* XXX */
> ```

Just a reminder.
___
*[tests/unit/peer/peer-common.h, line 28 at r1](https://reviewable.io/reviews/pmem/rpma/1044#-MZwFfjw7bKoAzbrE47Y:-MZwFfjw7bKoAzbrE47Z:b-cqd94y) ([raw file](https://github.com/pmem/rpma/blob/ad6a127eaaa2797deb7a32e905cb1f7b471b6305/tests/unit/peer/peer-common.h#L28)):*
> ```objc
>  * RPMA_MR_USAGE_* values.
>  */
> #define MOCK_USAGE		(unsigned)255
> ```

Can we just make it a combination instead of using a hardcoded value?
___
*[tests/unit/peer/peer-mr_reg.c, line 40 at r1](https://reviewable.io/reviews/pmem/rpma/1044#-MZwHNsC8XQ6Yz5zGyvv:-MZwHNsC8XQ6Yz5zGyvw:b-jsg33s) ([raw file](https://github.com/pmem/rpma/blob/ad6a127eaaa2797deb7a32e905cb1f7b471b6305/tests/unit/peer/peer-mr_reg.c#L40)):*
> ```C
> 	struct ibv_mr *mr = NULL;
> 	int ret = rpma_peer_mr_reg(peer, &mr, MOCK_ADDR,
> 				MOCK_LEN, MOCK_USAGE);
> ```

Since the usage -> access calculation is now a part of the peer module I think also the testing of it should go here.
Moreover, we will need two protection domains: one iWARP and one non-iWARP to test both implementations.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1044)* status: 8 of 10 files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[src/peer.c, line 32 at r1](https://reviewable.io/reviews/pmem/rpma/1044#-MZwF3R47rVFw0KEIUbi:-MZwIoT29Qwn5FbPCKWi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ad6a127eaaa2797deb7a32e905cb1f7b471b6305/src/peer.c#L32)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This is not a helper any more. It is an internal API now.
</blockquote></details>

Done.
___
*[src/peer.c, line 54 at r1](https://reviewable.io/reviews/pmem/rpma/1044#-MZwFElP22S2exvzAt6K:-MZwIp0tEUu-tgkL3wez:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ad6a127eaaa2797deb7a32e905cb1f7b471b6305/src/peer.c#L54)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Just a reminder.
</blockquote></details>

Done.
___
*[tests/unit/peer/peer-common.h, line 28 at r1](https://reviewable.io/reviews/pmem/rpma/1044#-MZwFfjw7bKoAzbrE47Y:-MZwKLjPBnOtVfgL3DdW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ad6a127eaaa2797deb7a32e905cb1f7b471b6305/tests/unit/peer/peer-common.h#L28)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Can we just make it a combination instead of using a hardcoded value?
</blockquote></details>

Done.
___
*[tests/unit/peer/peer-mr_reg.c, line 40 at r1](https://reviewable.io/reviews/pmem/rpma/1044#-MZwHNsC8XQ6Yz5zGyvv:-MZwMq7t9Yrb0fYrL2rN:b-u266r4) ([raw file](https://github.com/pmem/rpma/blob/ad6a127eaaa2797deb7a32e905cb1f7b471b6305/tests/unit/peer/peer-mr_reg.c#L40)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Since the usage -> access calculation is now a part of the peer module I think also the testing of it should go here.
Moreover, we will need two protection domains: one iWARP and one non-iWARP to test both implementations.
</blockquote></details>

Can it be done as a separate pull request?

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1044)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[src/peer.c, line 33 at r2](https://reviewable.io/reviews/pmem/rpma/1044#-MZwN6Ea7MWPq8OFVkPJ:-MZwN6Ea7MWPq8OFVkPK:b-83xg5e) ([raw file](https://github.com/pmem/rpma/blob/bfe745971305edf2a7d603ce6fb1001126ac811d/src/peer.c#L33)):*
> ```C
> 
> /*
>  * usage_to_access -- convert usage to access
> ```

Name.
___
*[src/peer.c, line 80 at r2](https://reviewable.io/reviews/pmem/rpma/1044#-MZwNKzc0w3cXDDMA0uY:-MZwNKzc0w3cXDDMA0uZ:b-ej85ya) ([raw file](https://github.com/pmem/rpma/blob/bfe745971305edf2a7d603ce6fb1001126ac811d/src/peer.c#L80)):*
> ```C
> }
> 
> /* internal librpma API */
> ```

Bring it one function up. ;-)
___
*[tests/unit/peer/peer-mr_reg.c, line 40 at r1](https://reviewable.io/reviews/pmem/rpma/1044#-MZwHNsC8XQ6Yz5zGyvv:-MZwNffj06mK_uPMTfbl:b-whxj2x) ([raw file](https://github.com/pmem/rpma/blob/ad6a127eaaa2797deb7a32e905cb1f7b471b6305/tests/unit/peer/peer-mr_reg.c#L40)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Can it be done as a separate pull request?
</blockquote></details>

I can agree to it if you will leave a big XXX somewhere. xD

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1044)* status: 9 of 10 files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[src/peer.c, line 33 at r2](https://reviewable.io/reviews/pmem/rpma/1044#-MZwN6Ea7MWPq8OFVkPJ:-MZwONFF-QK00tJJ0xVn:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bfe745971305edf2a7d603ce6fb1001126ac811d/src/peer.c#L33)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Name.
</blockquote></details>

Done.
___
*[src/peer.c, line 80 at r2](https://reviewable.io/reviews/pmem/rpma/1044#-MZwNKzc0w3cXDDMA0uY:-MZwOTEo8o_a5wNCkq-O:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bfe745971305edf2a7d603ce6fb1001126ac811d/src/peer.c#L80)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Bring it one function up. ;-)
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1044)* status: 7 of 10 files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tests/unit/peer/peer-mr_reg.c, line 40 at r1](https://reviewable.io/reviews/pmem/rpma/1044#-MZwHNsC8XQ6Yz5zGyvv:-MZw_Oth4Z4-7Yn1C5iE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ad6a127eaaa2797deb7a32e905cb1f7b471b6305/tests/unit/peer/peer-mr_reg.c#L40)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I can agree to it if you will leave a big XXX somewhere. xD
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1044)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tests/unit/peer/peer-mr_reg.c, line 166 at r3](https://reviewable.io/reviews/pmem/rpma/1044#-MZwuvR9EHMzkiVwNVny:-MZwuvRA8NPw_cuv-10I:b-stddi2) ([raw file](https://github.com/pmem/rpma/blob/5fbfa085587813f4955e31d4a74d2b719836a1b2/tests/unit/peer/peer-mr_reg.c#L166)):*
> ```C
> 	struct ibv_pd *mock_ibv_pd = MOCK_IBV_PD;
> 
> 	int n_iters = sizeof(usage2access) / sizeof(struct usage2access_s);
> ```

These should come as prestates.
___
*[tests/unit/peer/peer-mr_reg.c, line 166 at r3](https://reviewable.io/reviews/pmem/rpma/1044#-MZwvJjW-T_nIHAFy6JX:-MZwvJjW-T_nIHAFy6JY:br90t82) ([raw file](https://github.com/pmem/rpma/blob/5fbfa085587813f4955e31d4a74d2b719836a1b2/tests/unit/peer/peer-mr_reg.c#L166)):*
> ```C
> 	struct ibv_pd *mock_ibv_pd = MOCK_IBV_PD;
> 
> 	int n_iters = sizeof(usage2access) / sizeof(struct usage2access_s);
> ```

Having these, tests for `rpma_mr_reg()` are too extensive: https://github.com/pmem/rpma/blob/master/tests/unit/mr/mr-reg.c#L23

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1044)* status: 8 of 11 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tests/unit/peer/peer-mr_reg.c, line 166 at r3](https://reviewable.io/reviews/pmem/rpma/1044#-MZwuvR9EHMzkiVwNVny:-M_0DgpJEkZVYmYDEcR7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5fbfa085587813f4955e31d4a74d2b719836a1b2/tests/unit/peer/peer-mr_reg.c#L166)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

These should come as prestates.
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1044)* status: 8 of 12 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tests/unit/peer/peer-mr_reg.c, line 166 at r3](https://reviewable.io/reviews/pmem/rpma/1044#-MZwvJjW-T_nIHAFy6JX:-M_0I5fXCMSzNQXuaPzk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5fbfa085587813f4955e31d4a74d2b719836a1b2/tests/unit/peer/peer-mr_reg.c#L166)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Having these, tests for `rpma_mr_reg()` are too extensive: https://github.com/pmem/rpma/blob/master/tests/unit/mr/mr-reg.c#L23
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1044)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[tests/unit/peer/peer-common.h, line 47 at r4](https://reviewable.io/reviews/pmem/rpma/1044#-M_0NVJr80aaIsbj9Uha:-M_0NVJr80aaIsbj9Uhb:b-7kzkvm) ([raw file](https://github.com/pmem/rpma/blob/4d3180239ba0ab94b0eebcafc27fbb8da7247a41/tests/unit/peer/peer-common.h#L47)):*
> ```objc
> 	int is_odp_capable;
> 	struct rpma_peer *peer;
> };
> ```

Please put this structure just before `setup__peer_prestates()`.
___
*[tests/unit/peer/peer-common.h, line 55 at r4](https://reviewable.io/reviews/pmem/rpma/1044#-M_0NPG20LZy9TLNli42:-M_0NPG20LZy9TLNli43:bpysbtl) ([raw file](https://github.com/pmem/rpma/blob/4d3180239ba0ab94b0eebcafc27fbb8da7247a41/tests/unit/peer/peer-common.h#L55)):*
> ```objc
> int teardown__peer(void **peer_ptr);
> 
> int setup__peer_prestates(void **in_out);
> ```

pprestate
___
*[tests/unit/peer/peer-common.h, line 56 at r4](https://reviewable.io/reviews/pmem/rpma/1044#-M_0NQ5D8UnCQWlNBc9e:-M_0NQ5D8UnCQWlNBc9f:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/4d3180239ba0ab94b0eebcafc27fbb8da7247a41/tests/unit/peer/peer-common.h#L56)):*
> ```objc
> 
> int setup__peer_prestates(void **in_out);
> int teardown__peer_prestates(void **peer_ptr);
> ```

.
___
*[tests/unit/peer/peer-common.c, line 81 at r4](https://reviewable.io/reviews/pmem/rpma/1044#-M_0NrnbBCGoizjVQTSn:-M_0NrnbBCGoizjVQTSo:b-rzcv70) ([raw file](https://github.com/pmem/rpma/blob/4d3180239ba0ab94b0eebcafc27fbb8da7247a41/tests/unit/peer/peer-common.c#L81)):*
> ```C
>  * Note:
>  * - in - int is_odp_capable
>  * - out - struct rpma_peer *
> ```

Copy-pasted inadequately.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1044)* status: 10 of 12 files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[tests/unit/peer/peer-common.h, line 47 at r4](https://reviewable.io/reviews/pmem/rpma/1044#-M_0NVJr80aaIsbj9Uha:-M_0VKEi2YGfWQHnsQ7r:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4d3180239ba0ab94b0eebcafc27fbb8da7247a41/tests/unit/peer/peer-common.h#L47)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please put this structure just before `setup__peer_prestates()`.
</blockquote></details>

Done.
___
*[tests/unit/peer/peer-common.h, line 55 at r4](https://reviewable.io/reviews/pmem/rpma/1044#-M_0NPG20LZy9TLNli42:-M_0VKfE4I7awET5CPGp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4d3180239ba0ab94b0eebcafc27fbb8da7247a41/tests/unit/peer/peer-common.h#L55)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

pprestate
</blockquote></details>

Done.
___
*[tests/unit/peer/peer-common.h, line 56 at r4](https://reviewable.io/reviews/pmem/rpma/1044#-M_0NQ5D8UnCQWlNBc9e:-M_0VL4s8lPcJC3dbN35:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4d3180239ba0ab94b0eebcafc27fbb8da7247a41/tests/unit/peer/peer-common.h#L56)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/peer/peer-common.c, line 81 at r4](https://reviewable.io/reviews/pmem/rpma/1044#-M_0NrnbBCGoizjVQTSn:-M_0TCkQ3j82Wncp3U86:b-qilrzy) ([raw file](https://github.com/pmem/rpma/blob/4d3180239ba0ab94b0eebcafc27fbb8da7247a41/tests/unit/peer/peer-common.c#L81)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Copy-pasted inadequately.
</blockquote></details>

It is not the same as in `setup__peer()` - I have changed it, but perhaps it will be better to remove it at all.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1044#-:-M_0ZFvJE6Ekg3RqHmsM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1044#-:-M_0i-XE8bv5JaitGTIh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
