### PR TITLE
common: migrate from Docker Hub to GitHub Container Registry

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/547)

### CODE REVIEW

**Comment by ldorau** [comment]
Tested on my fork: 
1) https://github.com/ldorau/rpma/actions/runs/299070482
2) https://github.com/ldorau/rpma/actions/runs/299070982

**Comment by ldorau** [comment]
It has been already merged in PMDK: https://github.com/pmem/pmdk/pull/5009

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 6 files at r1, 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/547#-:-MJSqQ0T-0uiW6HqGKs9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by ldorau** [comment]
Maybe we will come back to GitHub Container Registry when it comes out of Beta and starts working within our organization as expected... Closing for now.

**Comment by ldorau** [comment]
Tested on my fork - it works:
1) https://github.com/ldorau/rpma/actions/runs/335889560
2) https://github.com/ldorau/rpma/actions/runs/335920508

**Comment by ldorau** [comment]
@grom72 @janekmi @osalyk please review

**Review by lukaszstolarczuk — COMMENTED** [review]
teeny tiny change requested, but :lgtm: 

when it's merged and first image is pushed you have to login as pmem-bot and make rpma docker image(s) public

> Reviewed 2 of 6 files at r1, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/547#-:-MKoyzcE3DYFjsbuaOOt:bdd8f16)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[.github/workflows/gha.yml, line 7 at r3](https://reviewable.io/reviews/pmem/rpma/547#-MKop5vz6Gc4cTInWDCE:-MKop5vz6Gc4cTInWDCF:b-bmorog) ([raw file](https://github.com/pmem/rpma/blob/88287f7a3d6c3761f817316ff8b59fc9f7a66c2a/.github/workflows/gha.yml#L7)):*
> ```YAML
> env:
>     GITHUB_REPO: pmem/rpma
>     DOCKER_REPO: ghcr.io/pmem/rpma
> ```

remember to update this value in nightly build if you merge it
___
*[utils/docker/images/push-image.sh, line 42 at r3](https://reviewable.io/reviews/pmem/rpma/547#-MKoyGw5-JiQVZwWXLHZ:-MKoyGw5-JiQVZwWXLH_:b422szx) ([raw file](https://github.com/pmem/rpma/blob/88287f7a3d6c3761f817316ff8b59fc9f7a66c2a/utils/docker/images/push-image.sh#L42)):*
> ```Shell
> TAG="0.1-${OS}-${OS_VER}"
> 
> # Check if the image tagged with pmdk/OS-VER exists locally
> ```

`pmdk` ;)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r1, 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/547)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[.github/workflows/gha.yml, line 7 at r3](https://reviewable.io/reviews/pmem/rpma/547#-MKop5vz6Gc4cTInWDCE:-MKp38RA65VtR1_46wyt:b6zrrkh) ([raw file](https://github.com/pmem/rpma/blob/88287f7a3d6c3761f817316ff8b59fc9f7a66c2a/.github/workflows/gha.yml#L7)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

remember to update this value in nightly build if you merge it
</blockquote></details>

Good catch.
___
*[utils/docker/images/push-image.sh, line 51 at r3](https://reviewable.io/reviews/pmem/rpma/547#-MKp3jh55pyG-MfgWMO3:-MKp3jh55pyG-MfgWMO4:b-q407tw) ([raw file](https://github.com/pmem/rpma/blob/88287f7a3d6c3761f817316ff8b59fc9f7a66c2a/utils/docker/images/push-image.sh#L51)):*
> ```Shell
> 
> # Log in to ${DOCKER_REPO}
> echo "${GH_CR_PAT}" | docker login ghcr.io -u="${GH_CR_USER}" --password-stdin
> ```

`ghcr.io` hardcoded?

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/547)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[.github/workflows/gha.yml, line 7 at r3](https://reviewable.io/reviews/pmem/rpma/547#-MKop5vz6Gc4cTInWDCE:-MKp4zPtB8KhcMGosZxT:bd4rais) ([raw file](https://github.com/pmem/rpma/blob/88287f7a3d6c3761f817316ff8b59fc9f7a66c2a/.github/workflows/gha.yml#L7)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Good catch.
</blockquote></details>

@ldorau you can now rebase and do this in this PR.

**Review by ldorau — COMMENTED** [review]
@lukaszstolarczuk Thanks!

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/547#-:-MKs6uer0YdJvB5vqsly:bc28g2d)* status: 3 of 7 files reviewed, 3 unresolved discussions (waiting on @janekmi and @lukaszstolarczuk)

___
*[.github/workflows/gha.yml, line 7 at r3](https://reviewable.io/reviews/pmem/rpma/547#-MKop5vz6Gc4cTInWDCE:-MKs9ANcCBnwBiVxGLd4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/88287f7a3d6c3761f817316ff8b59fc9f7a66c2a/.github/workflows/gha.yml#L7)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

@ldorau you can now rebase and do this in this PR.
</blockquote></details>

Done.
___
*[utils/docker/images/push-image.sh, line 42 at r3](https://reviewable.io/reviews/pmem/rpma/547#-MKoyGw5-JiQVZwWXLHZ:-MKs9BONCbO1HqtiSZwj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/88287f7a3d6c3761f817316ff8b59fc9f7a66c2a/utils/docker/images/push-image.sh#L42)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`pmdk` ;)
</blockquote></details>

Done.
___
*[utils/docker/images/push-image.sh, line 51 at r3](https://reviewable.io/reviews/pmem/rpma/547#-MKp3jh55pyG-MfgWMO3:-MKsA_bGAewte6ZxOoVw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/88287f7a3d6c3761f817316ff8b59fc9f7a66c2a/utils/docker/images/push-image.sh#L51)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`ghcr.io` hardcoded?
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/547)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/547#-:-MKsxmCi1KeSLJLEciMv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
