### PR TITLE
tools: complete config.json.example file

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1081)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1081)* status: all files reviewed, 7 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/config.json.example, line 26 at r1](https://reviewable.io/reviews/pmem/rpma/1081#-MbLlUu694Ghzpn5UprJ:-MbLlUu694Ghzpn5UprK:b-sjn9y) ([raw file](https://github.com/pmem/rpma/blob/0fa452f8e0caf461232b7aad0cea83b85488abba/tools/perf/config.json.example#L26)):*
> ```
>     "REMOTE_RESULTS_DIR": "/tmp/",
>     "_comment": "In case you would like to collect sar data:",
>     "REMOTE_CMD_PRE": "rm -f \${REMOTE_RESULTS_DIR}sar.dat; numactl -N \${REMOTE_ANOTHER_NUMA} sar -u -P \${REMOTE_JOB_NUMA_CPULIST} -o \${REMOTE_RESULTS_DIR}sar.dat 5 > /dev/null",
> ```

`\` is not required to introduce `$` to these strings. I suppose it might work just fine without any escaping. Alternatively, you may need to introduce `\\$` instead.

Can you confirm which way will work base on a simple and short experiment?

Obviously, based on the result of the experiment, please adjust all lines.
___
*[tools/perf/config.json.example, line 32 at r1](https://reviewable.io/reviews/pmem/rpma/1081#-MbLn-7QEHQRNyB7I57A:-MbLn-7QEHQRNyB7I57B:bezco72) ([raw file](https://github.com/pmem/rpma/blob/0fa452f8e0caf461232b7aad0cea83b85488abba/tools/perf/config.json.example#L32)):*
> ```
>     "REMOTE_CMD_PRE": "source /opt/intel/sep/sep_vars.sh; numactl -N \${REMOTE_ANOTHER_NUMA} emon -i \${EVENT_LIST} > \${REMOTE_RESULTS_DIR}\${RUN_NAME}_emon.dat",
>     "REMOTE_CMD_POST": "sleep 10; source /opt/intel/sep/sep_vars.sh; emon -stop",
>     "_comment": "DEBUG",
> ```

`Debug:`
___
*[tools/perf/config.json.example, line 33 at r1](https://reviewable.io/reviews/pmem/rpma/1081#-MbLm_4l-YkKF1VRzSqA:-MbLm_4l-YkKF1VRzSqB:b2rzcyg) ([raw file](https://github.com/pmem/rpma/blob/0fa452f8e0caf461232b7aad0cea83b85488abba/tools/perf/config.json.example#L33)):*
> ```
>     "REMOTE_CMD_POST": "sleep 10; source /opt/intel/sep/sep_vars.sh; emon -stop",
>     "_comment": "DEBUG",
>     "SHORT_RUNTIME": 0,
> ```

`false`
___
*[tools/perf/config.json.example, line 36 at r1](https://reviewable.io/reviews/pmem/rpma/1081#-MbLmew6BvjhPIy-53cI:-MbLmew6BvjhPIy-53cJ:b2rzcyg) ([raw file](https://github.com/pmem/rpma/blob/0fa452f8e0caf461232b7aad0cea83b85488abba/tools/perf/config.json.example#L36)):*
> ```
>     "TRACER": "gdbserver localhost:2345",
>     "REMOTE_TRACER": "gdbserver localhost:2345",
>     "DO_NOTHING": 1,
> ```

`false`
___
*[tools/perf/config.json.example, line 37 at r1](https://reviewable.io/reviews/pmem/rpma/1081#-MbLmfxk4aOVsClGzzNg:-MbLmfxk4aOVsClGzzNh:b2rzcyg) ([raw file](https://github.com/pmem/rpma/blob/0fa452f8e0caf461232b7aad0cea83b85488abba/tools/perf/config.json.example#L37)):*
> ```
>     "REMOTE_TRACER": "gdbserver localhost:2345",
>     "DO_NOTHING": 1,
>     "DUMP_CMDS": 1,
> ```

`false`
___
*[tools/perf/config.json.example, line 38 at r1](https://reviewable.io/reviews/pmem/rpma/1081#-MbLmn0T9Z3DVmSN3t-h:-MbLmn0T9Z3DVmSN3t-i:b-me96dq) ([raw file](https://github.com/pmem/rpma/blob/0fa452f8e0caf461232b7aad0cea83b85488abba/tools/perf/config.json.example#L38)):*
> ```
>     "DO_NOTHING": 1,
>     "DUMP_CMDS": 1,
>     "OUTPUT_FILE": "output_file.csv",
> ```

This is not a debug option. I think it will be better to put it before `PRE_`.
___
*[tools/perf/config.json.example, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1081#-MbLmj7a7OcdAOXDE1qQ:-MbLmj7a7OcdAOXDE1qR:b-l5z3i) ([raw file](https://github.com/pmem/rpma/blob/0fa452f8e0caf461232b7aad0cea83b85488abba/tools/perf/config.json.example#L39)):*
> ```
>     "DUMP_CMDS": 1,
>     "OUTPUT_FILE": "output_file.csv",
>     "_comment": "XXX",
> ```

Please delete.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1081)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/config.json.example, line 26 at r1](https://reviewable.io/reviews/pmem/rpma/1081#-MbLlUu694Ghzpn5UprJ:-MbMHhIkAx-H95GtVt01:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0fa452f8e0caf461232b7aad0cea83b85488abba/tools/perf/config.json.example#L26)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`\` is not required to introduce `$` to these strings. I suppose it might work just fine without any escaping. Alternatively, you may need to introduce `\\$` instead.

Can you confirm which way will work base on a simple and short experiment?

Obviously, based on the result of the experiment, please adjust all lines.
</blockquote></details>

Done.
___
*[tools/perf/config.json.example, line 32 at r1](https://reviewable.io/reviews/pmem/rpma/1081#-MbLn-7QEHQRNyB7I57A:-MbMDukh5bdo-dMNaXkl:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0fa452f8e0caf461232b7aad0cea83b85488abba/tools/perf/config.json.example#L32)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`Debug:`
</blockquote></details>

Done.
___
*[tools/perf/config.json.example, line 33 at r1](https://reviewable.io/reviews/pmem/rpma/1081#-MbLm_4l-YkKF1VRzSqA:-MbMDxI57QnH9Jc3idyb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0fa452f8e0caf461232b7aad0cea83b85488abba/tools/perf/config.json.example#L33)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`false`
</blockquote></details>

Done.
___
*[tools/perf/config.json.example, line 36 at r1](https://reviewable.io/reviews/pmem/rpma/1081#-MbLmew6BvjhPIy-53cI:-MbMDzlk9poMltupeIAE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0fa452f8e0caf461232b7aad0cea83b85488abba/tools/perf/config.json.example#L36)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`false`
</blockquote></details>

Done.
___
*[tools/perf/config.json.example, line 37 at r1](https://reviewable.io/reviews/pmem/rpma/1081#-MbLmfxk4aOVsClGzzNg:-MbME103-87rprd_3n8d:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0fa452f8e0caf461232b7aad0cea83b85488abba/tools/perf/config.json.example#L37)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`false`
</blockquote></details>

Done.
___
*[tools/perf/config.json.example, line 38 at r1](https://reviewable.io/reviews/pmem/rpma/1081#-MbLmn0T9Z3DVmSN3t-h:-MbME64g2nJCWIOZVjpM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0fa452f8e0caf461232b7aad0cea83b85488abba/tools/perf/config.json.example#L38)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This is not a debug option. I think it will be better to put it before `PRE_`.
</blockquote></details>

Done.
___
*[tools/perf/config.json.example, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1081#-MbLmj7a7OcdAOXDE1qQ:-MbME8Se2KQN_InhlF-T:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0fa452f8e0caf461232b7aad0cea83b85488abba/tools/perf/config.json.example#L39)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please delete.
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1081)* status: all files reviewed, 8 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tools/perf/config.json.example, line 24 at r2](https://reviewable.io/reviews/pmem/rpma/1081#-Mb_TiCm9A7D3fQPWVCY:-Mb_TiCn0PvgTrm4AFLn:b-j5du9d) ([raw file](https://github.com/pmem/rpma/blob/e02c5a7e41b939ab23cefabe32bf457f36dbc2c3/tools/perf/config.json.example#L24)):*
> ```
>  "/tmp/",
> ```

Why not "path" ?

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1081)* status: all files reviewed, 8 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/config.json.example, line 24 at r2](https://reviewable.io/reviews/pmem/rpma/1081#-Mb_TiCm9A7D3fQPWVCY:-Mb_Uo5e-5CWAty4Ao_I:b-a392i7) ([raw file](https://github.com/pmem/rpma/blob/e02c5a7e41b939ab23cefabe32bf457f36dbc2c3/tools/perf/config.json.example#L24)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  "/tmp/",
> ```

Why not "path" ?
</blockquote></details>

Taken from bench_common.sh

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1081)* status: all files reviewed, 8 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/config.json.example, line 24 at r2](https://reviewable.io/reviews/pmem/rpma/1081#-Mb_TiCm9A7D3fQPWVCY:-Mb_fvhO7T5-GxyZr93E:b-ad6j5w) ([raw file](https://github.com/pmem/rpma/blob/e02c5a7e41b939ab23cefabe32bf457f36dbc2c3/tools/perf/config.json.example#L24)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Taken from bench_common.sh
</blockquote></details>

I think it should be "path" too.

@janekmi ?

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1081)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/config.json.example, line 24 at r2](https://reviewable.io/reviews/pmem/rpma/1081#-Mb_TiCm9A7D3fQPWVCY:-Mb_iKk10f25s46IPn5U:b-lp56xv) ([raw file](https://github.com/pmem/rpma/blob/e02c5a7e41b939ab23cefabe32bf457f36dbc2c3/tools/perf/config.json.example#L24)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I think it should be "path" too.

@janekmi ?
</blockquote></details>

I am for @ldorau's approach. Consistency is the only rule we have so far for this part of the infrastructure.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1081)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/config.json.example, line 24 at r2](https://reviewable.io/reviews/pmem/rpma/1081#-Mb_TiCm9A7D3fQPWVCY:-Mba-pjNBMCbI-IaiQib:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e02c5a7e41b939ab23cefabe32bf457f36dbc2c3/tools/perf/config.json.example#L24)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I am for @ldorau's approach. Consistency is the only rule we have so far for this part of the infrastructure.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1081)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1081#-:-Mba5qSe4eCF5jG5v9Zd:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1081#-:-MbeqESN6pYgk9T_CBJu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
