### PR TITLE
doc: Direct Write to PMem - cleanup

### PR DESCRIPTION
**Pull request by janekmi**
Preview: https://janekmi.github.io/rpma/documentation/basic-direct-write-to-pmem.html

This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/842)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/842)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[documentation/basic-direct-write-to-pmem.md, line 66 at r1](https://reviewable.io/reviews/pmem/rpma/842#-MSdQlop03URcld4dhF_:-MSdQlou6iNMsyC_0GoU:b-byfdrb) ([raw file](https://github.com/pmem/rpma/blob/c58a9dd7aad4f5b6b3ae1a5bd1fcccb5ec847d8c/documentation/basic-direct-write-to-pmem.md#L66)):*
> ```Markdown
> [dpdk]: https://www.dpdk.org/wp-content/uploads/sites/35/2018/09/Roman-Sudarikov-DPDK_PRC_Summit_Sudarikov.pptx
> 
> [lspci]: https://man7.org/linux/man-pages/man8/lspci.8.html
> ```

New line

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/842)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[documentation/basic-direct-write-to-pmem.md, line 5 at r1](https://reviewable.io/reviews/pmem/rpma/842#-MSdUg1o9QjUl0k2l71r:-MSdUg1o9QjUl0k2l71s:byzvrm9) ([raw file](https://github.com/pmem/rpma/blob/c58a9dd7aad4f5b6b3ae1a5bd1fcccb5ec847d8c/documentation/basic-direct-write-to-pmem.md#L5)):*
> ```Markdown
> layout: pmdk
> ---
> ```

##Remote Persistent Memory Access

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/842)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[documentation/basic-direct-write-to-pmem.md, line 5 at r1](https://reviewable.io/reviews/pmem/rpma/842#-MSdUg1o9QjUl0k2l71r:-MSe1Yf9AAHNXnAH0Snz:bydug1d) ([raw file](https://github.com/pmem/rpma/blob/c58a9dd7aad4f5b6b3ae1a5bd1fcccb5ec847d8c/documentation/basic-direct-write-to-pmem.md#L5)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

##Remote Persistent Memory Access 
</blockquote></details>

Have you seen the preview: https://janekmi.github.io/rpma/documentation/perf-tuning.html ?
The lack of reference to RPMA has been solved differently.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/842)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[documentation/basic-direct-write-to-pmem.md, line 66 at r1](https://reviewable.io/reviews/pmem/rpma/842#-MSdQlop03URcld4dhF_:-MSe25qZAOpDJU8LM_Uo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c58a9dd7aad4f5b6b3ae1a5bd1fcccb5ec847d8c/documentation/basic-direct-write-to-pmem.md#L66)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

New line
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/842)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[documentation/basic-direct-write-to-pmem.md, line 20 at r2](https://reviewable.io/reviews/pmem/rpma/842#-MSflVJA-kK0nTSl7SFM:-MSflVJA-kK0nTSl7SFN:b82uap5) ([raw file](https://github.com/pmem/rpma/blob/5ee879dc93c496759498ecbdda9487204a3cb4cc/documentation/basic-direct-write-to-pmem.md#L20)):*
> ```
> workloads turning 
> ```

`workloads, turning ` (add a comma)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/842#-:-MSfn-rFDmG0mF_yTYtx:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/842)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/842#-:-MSgOs1KA1B5-J1a2XiG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
