### PR TITLE
tools: separate the unique outputs of rpma_fio_bench.sh and ib_read.sh

### PR DESCRIPTION
**Pull request by yangx-jy**
don't mess up the unique outputs of rpma_fio_bench.sh and ib_read.sh.

Signed-off-by: Xiao Yang <yangx.jy@fujitsu.com>

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1131)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1131)* status: 2 of 3 files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by ldorau — APPROVED** [review]
:lgtm: when one my issue is fixed

> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1131#-:-Me9NfmECksQTpOXmn_T:bd6qhd4)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[tools/perf/bench_common.sh, line 16 at r1](https://reviewable.io/reviews/pmem/rpma/1131#-Me9LuoB5r_dXrmIqHrz:-Me9LuoB5r_dXrmIqHs-:bpqabdb) ([raw file](https://github.com/pmem/rpma/blob/78816d2683cfd2f4ad9c36a92bf6beb8d0680458/tools/perf/bench_common.sh#L16)):*
> ```
> "Script $FILENAME is not support"
> ```

"The script $FILENAME is not supported"

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1131)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[tools/perf/bench_common.sh, line 16 at r1](https://reviewable.io/reviews/pmem/rpma/1131#-Me9LuoB5r_dXrmIqHrz:-MeAFlL_CsesdPvWP0O_:b-eu27xz) ([raw file](https://github.com/pmem/rpma/blob/78816d2683cfd2f4ad9c36a92bf6beb8d0680458/tools/perf/bench_common.sh#L16)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> "Script $FILENAME is not support"
> ```

"The script $FILENAME is not supported"
</blockquote></details>

supported

**Comment by yangx-jy** [comment]
> > "The script $FILENAME is not supported"
> 
> supported

Sorry, replaced `support` with `supported`.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1131)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1131#-:-MfXe5SkEYDWhiqLcZ03:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1131)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1131)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[tools/perf/bench_common.sh, line 73 at r3](https://reviewable.io/reviews/pmem/rpma/1131#-MfYh6hI66F1KOIwjYyb:-MfYh6hI66F1KOIwjYyc:bqycy07) ([raw file](https://github.com/pmem/rpma/blob/19f394fc7e68d28ac2311e983d6393812d8c6efb/tools/perf/bench_common.sh#L73)):*
> ```Shell
> 	echo
> 	if [ "$FILENAME" = "rpma_fio_bench.sh" ]; then
> 		echo "Usage: $0 <server_ip> all|apm|gpspm|aof_sw|aof_hw [all|read|randread|write|randwrite|rw|randrw] [all|bw-bs|bw-dp-exp|bw-dp-lin|bw-th|bw-cpu|bw-cpu-mt|l    at|lat-cpu]"
> ```

`l    at` too many spaces. ;-)

**Comment by yangx-jy** [comment]
___
*[tools/perf/bench_common.sh, line 73 at r3](https://reviewable.io/reviews/pmem/rpma/1131#-MfYh6hI66F1KOIwjYyb:-Mf_fNdv6g2I3KjgRaon:b-v6e6sz) ([raw file](https://github.com/pmem/rpma/blob/19f394fc7e68d28ac2311e983d6393812d8c6efb/tools/perf/bench_common.sh#L73)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`l    at` too many spaces. ;-)
</blockquote></details>

Done.  Good eyes. ^_^

**Review by ldorau — APPROVED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1131)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1131#-:-MfaT5HH3BhDiLqaZoHh:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1131#-:-MgPXvow44AW3Bz_ybZn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Pull request merged**
