### PR TITLE
common: tools: ddio.sh

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/597)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/597)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/ddio.sh, line 14 at r1](https://reviewable.io/reviews/pmem/rpma/597#-MM_xU8Y31w4mlEUyfef:-MM_xU8Y31w4mlEUyfeg:b5jjoq5) ([raw file](https://github.com/pmem/rpma/blob/b7b37c359c0c6edee6903313b2488ac9af28441a/tools/ddio.sh#L14)):*
> ```
> usage()
> ```

Why not `function usage()` ?
___
*[tools/ddio.sh, line 16 at r1](https://reviewable.io/reviews/pmem/rpma/597#-MM_y4e1AQLwqzZsWoUH:-MM_y4e20RYU_JSttZag:bu4nns7) ([raw file](https://github.com/pmem/rpma/blob/b7b37c359c0c6edee6903313b2488ac9af28441a/tools/ddio.sh#L16)):*
> ```
> 
> 	[ "$1" ] && echo Error: $1
> ```

Is it supposed to print error on any non-empty argument?
___
*[tools/ddio.sh, line 77 at r1](https://reviewable.io/reviews/pmem/rpma/597#-MM_ylNe1ep-crBfQym9:-MM_ylNe1ep-crBfQymA:b-yvuxlm) ([raw file](https://github.com/pmem/rpma/blob/b7b37c359c0c6edee6903313b2488ac9af28441a/tools/ddio.sh#L77)):*
<details><summary><i alt="summary">Quoted 15 lines of code…</i></summary>

> ```
> Criteria:
> (TPH=0 OR TPHDIS=1 OR
>     (TPH=1 AND Tag=0 AND CIPCTRL[28]=1)) AND
> (NS=0 OR NoSnoopOrWrEn=0) AND
> Non-DCA Write
> ---
> So allocating flows (aka DDIO) are disabled if:
> (use_allocating_flow_wr=0 AND
>     TPHDIS=1 AND
>     NoSnoopOrWrEn=0)
> and enabled otherwise.
> Where:
> perfctrlsts_0[7] is use_allocating_flow_wr (default: 0x1)
> perfctrlsts_0[3] is NoSnoopOrWrEn (default: 0x0)
> perfctrlsts_1[9] is TPHDIS (default: 0x0)
> ```
</details>


They are kind of magic spells for me ;-) I do not understand anything here ;-)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/597)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tools/ddio.sh, line 115 at r1](https://reviewable.io/reviews/pmem/rpma/597#-MMa1ZEu09BS1REvVKqO:-MMa1ZEu09BS1REvVKqP:bbahs32) ([raw file](https://github.com/pmem/rpma/blob/b7b37c359c0c6edee6903313b2488ac9af28441a/tools/ddio.sh#L115)):*
> ```
> 	_log "setpci -s $device $register"
> 	_log "=$valhex"
> ```

Does it execute those commands or only logs them ?

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/597)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[tools/ddio.sh, line 52 at r1](https://reviewable.io/reviews/pmem/rpma/597#-MMa1q41-DTQgZVEINyG:-MMa1q41-DTQgZVEINyH:by5qt6w) ([raw file](https://github.com/pmem/rpma/blob/b7b37c359c0c6edee6903313b2488ac9af28441a/tools/ddio.sh#L52)):*
> ```
> excerpt()
> ```

`function excerpt()` ?

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/597)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/597)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[tools/ddio.sh, line 14 at r1](https://reviewable.io/reviews/pmem/rpma/597#-MM_xU8Y31w4mlEUyfef:-MMa40r8Ab8932CMB-I3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b7b37c359c0c6edee6903313b2488ac9af28441a/tools/ddio.sh#L14)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> usage()
> ```

Why not `function usage()` ?
</blockquote></details>

Done.
___
*[tools/ddio.sh, line 16 at r1](https://reviewable.io/reviews/pmem/rpma/597#-MM_y4e1AQLwqzZsWoUH:-MMa6PYr3UvYhPRkaylg:b-a89lhn) ([raw file](https://github.com/pmem/rpma/blob/b7b37c359c0c6edee6903313b2488ac9af28441a/tools/ddio.sh#L16)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 
> 	[ "$1" ] && echo Error: $1
> ```

Is it supposed to print error on any non-empty argument?
</blockquote></details>

Yes. I have tried to make it more bulletproof. What do you think?
___
*[tools/ddio.sh, line 52 at r1](https://reviewable.io/reviews/pmem/rpma/597#-MMa1q41-DTQgZVEINyG:-MMa41_C0m23oM9FKwAv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b7b37c359c0c6edee6903313b2488ac9af28441a/tools/ddio.sh#L52)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> excerpt()
> ```

`function excerpt()` ?
</blockquote></details>

Done.
___
*[tools/ddio.sh, line 77 at r1](https://reviewable.io/reviews/pmem/rpma/597#-MM_ylNe1ep-crBfQym9:-MMa45BDDPa3JlJRJmfA:bf21ns2) ([raw file](https://github.com/pmem/rpma/blob/b7b37c359c0c6edee6903313b2488ac9af28441a/tools/ddio.sh#L77)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> Criteria:
> (TPH=0 OR TPHDIS=1 OR
>     (TPH=1 AND Tag=0 AND CIPCTRL[28]=1)) AND
> (NS=0 OR NoSnoopOrWrEn=0) AND
> Non-DCA Write
> ---
> So allocating flows (aka DDIO) are disabled if:
> (use_allocating_flow_wr=0 AND
>     TPHDIS=1 AND
>     NoSnoopOrWrEn=0)
> and enabled otherwise.
> Where:
> perfctrlsts_0[7] is use_allocating_flow_wr (default: 0x1)
> perfctrlsts_0[3] is NoSnoopOrWrEn (default: 0x0)
> perfctrlsts_1[9] is TPHDIS (default: 0x0)
> ```

They are kind of magic spells for me ;-) I do not understand anything here ;-) 
</blockquote></details>

I know, it is messed up. You can read more here: http://janekmi.github.io/2020/06/21/ddio.html. But I do not expect you to wrap your head around it. Nonetheless, it would be kinda nice to have additional confirmation.
___
*[tools/ddio.sh, line 115 at r1](https://reviewable.io/reviews/pmem/rpma/597#-MMa1ZEu09BS1REvVKqO:-MMa4yac1Z9FqOMlPajZ:b-7wjxvj) ([raw file](https://github.com/pmem/rpma/blob/b7b37c359c0c6edee6903313b2488ac9af28441a/tools/ddio.sh#L115)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 	_log "setpci -s $device $register"
> 	_log "=$valhex"
> ```

Does it execute those commands or only logs them ?
</blockquote></details>

It just does conditional logging. No execution.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/597#-:-MMa8VRA3AQ5LP1WC5-Q:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

___
*[tools/ddio.sh, line 16 at r1](https://reviewable.io/reviews/pmem/rpma/597#-MM_y4e1AQLwqzZsWoUH:-MMa87Fw5mhmxK_arKj7:bo0pbb6) ([raw file](https://github.com/pmem/rpma/blob/b7b37c359c0c6edee6903313b2488ac9af28441a/tools/ddio.sh#L16)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Yes. I have tried to make it more bulletproof. What do you think?
</blockquote></details>

It is OK

**Pull request merged**
