### PR TITLE
test: fix incorrect names of test files

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/520)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/520#-:-MIYZXyCDVHJx7EhaH0d:bnfp4nl)* status: 0 of 22 files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/520)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 22 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/520#-:-MIYdQGK2QV6WHtRTwS2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 21 of 22 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/520#-:-MIZ8Dr97Pl7YhOEVuMD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
