### PR TITLE
tools: save results of sar in a separate file for each run

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/934)

### CODE REVIEW

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/934#-:-MVs7fijEa72OK3MqaGD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/934)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/rpma_fio_bench.sh, line 332 at r1](https://reviewable.io/reviews/pmem/rpma/934#-MVv3mNF2V5hQVByxGL8:-MVv3mNF2V5hQVByxGL9:b-5h1xg8) ([raw file](https://github.com/pmem/rpma/blob/7bf125d1c09a3a8e1683591342537fadfd69292e/tools/perf/rpma_fio_bench.sh#L332)):*
> ```Shell
> 		esac
> 
> 		export RUN_NAME=${NAME}_bs${BS}_th${TH}_dp${DP}
> ```

NAME contains this data: bs, th, dp (NAME_SUFFIX)
Maybe this way:
lat)
    Z-AXIS=bs${BS}
    ...
esac

export RUN_NAME=${NAME}_${Z-AXIS}

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/934)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi and @osalyk)

___
*[tools/perf/rpma_fio_bench.sh, line 332 at r1](https://reviewable.io/reviews/pmem/rpma/934#-MVv3mNF2V5hQVByxGL8:-MW-6o8h6r8AC6oBH4Kg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7bf125d1c09a3a8e1683591342537fadfd69292e/tools/perf/rpma_fio_bench.sh#L332)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

NAME contains this data: bs, th, dp (NAME_SUFFIX)
Maybe this way:
lat)
    Z-AXIS=bs${BS}
    ...
esac

export RUN_NAME=${NAME}_${Z-AXIS}
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/934#-:-MW-7fGS8i5ZH-FMTRCc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
