### PR TITLE
rpma: write 'DEBUGGING AND ERROR HANDLING' section of manual

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/478)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/478)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[src/include/librpma.h, line 133 at r1](https://reviewable.io/reviews/pmem/rpma/478#-MIP-lz83kUZZ2hZG2t9:-MIP-lz83kUZZ2hZG2tA:bbx0n63) ([raw file](https://github.com/pmem/rpma/blob/e5270d46e4ee71b4dd9cae4606e16313b71d3ca0/src/include/librpma.h#L133)):*
> ```objc
>  * All functions (except of rpma_log_set_function()) return a negative
>  * error code on failure. Error codes returned by functions are described
>  * in their manuals.
> ```

I do not like that you are explicitly enumerating which functions do not return error codes. It is hard to maintain in the long term. Moreover, I want to see here what all of these means for a user e.g.

```
When RPMA API function can fail it returns an error code according to its respective manual. Checking if the returned value is non-negative is the only programmatically available way to verify if the API call succeeded.
```
___
*[src/include/librpma.h, line 135 at r1](https://reviewable.io/reviews/pmem/rpma/478#-MIP0c8R87JFqxMWc6GB:-MIP0c8R87JFqxMWc6GC:b-v0xp5j) ([raw file](https://github.com/pmem/rpma/blob/e5270d46e4ee71b4dd9cae4606e16313b71d3ca0/src/include/librpma.h#L135)):*
> ```objc
>  * in their manuals.
>  *
>  * The librpma library implements a logging API:
> ```

Same here, what the logging is for here e.g.:

```
The librpma library implements a logging API which may give additional information on the error and during normal operation as well according to current logging threshold levels.
```

After the above, I will go with the rest of the body. Whereas the list of functions I will give at the end.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/478)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 133 at r1](https://reviewable.io/reviews/pmem/rpma/478#-MIP-lz83kUZZ2hZG2t9:-MIP3hm_BXcrvqdA0gek:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e5270d46e4ee71b4dd9cae4606e16313b71d3ca0/src/include/librpma.h#L133)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I do not like that you are explicitly enumerating which functions do not return error codes. It is hard to maintain in the long term. Moreover, I want to see here what all of these means for a user e.g.

```
When RPMA API function can fail it returns an error code according to its respective manual. Checking if the returned value is non-negative is the only programmatically available way to verify if the API call succeeded.
```
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 135 at r1](https://reviewable.io/reviews/pmem/rpma/478#-MIP0c8R87JFqxMWc6GB:-MIP6CGj3Wz5MnuxS1pC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e5270d46e4ee71b4dd9cae4606e16313b71d3ca0/src/include/librpma.h#L135)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Same here, what the logging is for here e.g.:

```
The librpma library implements a logging API which may give additional information on the error and during normal operation as well according to current logging threshold levels.
```

After the above, I will go with the rest of the body. Whereas the list of functions I will give at the end.
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/478)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[src/include/librpma.h, line 151 at r2](https://reviewable.io/reviews/pmem/rpma/478#-MIPID2BAwBEvSFhkZ2x:-MIPID2BAwBEvSFhkZ2y:bfa0159) ([raw file](https://github.com/pmem/rpma/blob/bf0c73453317a4f1cf2648e4ac897ebcbde59504/src/include/librpma.h#L151)):*
> ```objc
>  * - rpma_log_set_threshold() - set the logging threshold level
>  * - rpma_log_get_threshold() - get the logging threshold level
>  * - rpma_log_set_function() - set the logging function.
> ```

You have already mentioned all of these functions in the body. Maybe get rid of these?
___
*[src/include/librpma.h, line 152 at r2](https://reviewable.io/reviews/pmem/rpma/478#-MIPJC684u4mfTOIksOf:-MIPJC6901D_7359EmeU:b-v03hne) ([raw file](https://github.com/pmem/rpma/blob/bf0c73453317a4f1cf2648e4ac897ebcbde59504/src/include/librpma.h#L152)):*
> ```objc
>  * - rpma_log_get_threshold() - get the logging threshold level
>  * - rpma_log_set_function() - set the logging function.
>  *
> ```

Please refer the user to the example: https://github.com/pmem/rpma/tree/master/examples/log

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/478)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[src/include/librpma.h, line 1976 at r2](https://reviewable.io/reviews/pmem/rpma/478#-MIPcic11i4_vS2UfAb3:-MIPcic11i4_vS2UfAb4:b-pxgmza) ([raw file](https://github.com/pmem/rpma/blob/bf0c73453317a4f1cf2648e4ac897ebcbde59504/src/include/librpma.h#L1976)):*
> ```
> a negative
> ```
do we want to propagate this semantic to all API calls documentation?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/478)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/include/librpma.h, line 1976 at r2](https://reviewable.io/reviews/pmem/rpma/478#-MIPcic11i4_vS2UfAb3:-MIPs2WD1xCQ2hmc6YF7:b-a5mbp0) ([raw file](https://github.com/pmem/rpma/blob/bf0c73453317a4f1cf2648e4ac897ebcbde59504/src/include/librpma.h#L1976)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> a negative
> ```
do we want to propagate this semantic to all API calls documentation?
</blockquote></details>

It is pretty common in our header. If some calls still missing this I don't mind adding it.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/478)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/include/librpma.h, line 1976 at r2](https://reviewable.io/reviews/pmem/rpma/478#-MIPcic11i4_vS2UfAb3:-MISDxz61WyKXAtUGbOO:b-vrqccj) ([raw file](https://github.com/pmem/rpma/blob/bf0c73453317a4f1cf2648e4ac897ebcbde59504/src/include/librpma.h#L1976)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is pretty common in our header. If some calls still missing this I don't mind adding it.
</blockquote></details>

@grom72 It already is in all librpma API.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/478)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[src/include/librpma.h, line 152 at r2](https://reviewable.io/reviews/pmem/rpma/478#-MIPJC684u4mfTOIksOf:-MISFQ1dC8DpKFbMQVEL:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bf0c73453317a4f1cf2648e4ac897ebcbde59504/src/include/librpma.h#L152)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please refer the user to the example: https://github.com/pmem/rpma/tree/master/examples/log
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1976 at r2](https://reviewable.io/reviews/pmem/rpma/478#-MIPcic11i4_vS2UfAb3:-MISFtmE6tF53Ebc5uNh:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bf0c73453317a4f1cf2648e4ac897ebcbde59504/src/include/librpma.h#L1976)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@grom72 It already is in all librpma API.
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/478)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[src/include/librpma.h, line 131 at r2](https://reviewable.io/reviews/pmem/rpma/478#-MISEJgZ4iH1iGsGwszr:-MISEJgZ4iH1iGsGwszs:b-moigpm) ([raw file](https://github.com/pmem/rpma/blob/bf0c73453317a4f1cf2648e4ac897ebcbde59504/src/include/librpma.h#L131)):*
> ```
> negative error code
> ```
non-zero error code
___
*[src/include/librpma.h, line 131 at r2](https://reviewable.io/reviews/pmem/rpma/478#-MISF2PUBi2X4u0B06-8:-MISF2PUBi2X4u0B06-9:bas9dqj) ([raw file](https://github.com/pmem/rpma/blob/bf0c73453317a4f1cf2648e4ac897ebcbde59504/src/include/librpma.h#L131)):*
> ```
> If a librpma API function may fail, it returns a negative error code
> according to its manual.
> ```
Each librpma API function returns a non-zero error code in case it fails.
Detail error codes meaning are described in functions manuals.
___
*[src/include/librpma.h, line 140 at r2](https://reviewable.io/reviews/pmem/rpma/478#-MISEqzg6q7rXheCopMP:-MISEqzg6q7rXheCopMQ:b-471t5o) ([raw file](https://github.com/pmem/rpma/blob/bf0c73453317a4f1cf2648e4ac897ebcbde59504/src/include/librpma.h#L140)):*
> ```
> print
> ```
handle
___
*[src/include/librpma.h, line 143 at r2](https://reviewable.io/reviews/pmem/rpma/478#-MISFdw15dNAxwtaF1fo:-MISFdw15dNAxwtaF1fp:b-6gbym6) ([raw file](https://github.com/pmem/rpma/blob/bf0c73453317a4f1cf2648e4ac897ebcbde59504/src/include/librpma.h#L143)):*
> ```
> a pointer to
> ```
to be removed
___
*[src/include/librpma.h, line 146 at r2](https://reviewable.io/reviews/pmem/rpma/478#-MISEc5p8tlyPnfnu_nd:-MISEc5p8tlyPnfnu_ne:b-6l5l0a) ([raw file](https://github.com/pmem/rpma/blob/bf0c73453317a4f1cf2648e4ac897ebcbde59504/src/include/librpma.h#L146)):*
> ```
> rpma_log_set_threshold()/rpma_log_get_threshold()
> ```
___
*[src/include/librpma.h, line 1976 at r2](https://reviewable.io/reviews/pmem/rpma/478#-MIPcic11i4_vS2UfAb3:-MISFsXP9EzGxqMzdLdT:blcsb7y) ([raw file](https://github.com/pmem/rpma/blob/bf0c73453317a4f1cf2648e4ac897ebcbde59504/src/include/librpma.h#L1976)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Yes, I know, but shall we just assume that non-zero return is correct, non error returned value?

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/478)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[src/include/librpma.h, line 1976 at r2](https://reviewable.io/reviews/pmem/rpma/478#-MIPcic11i4_vS2UfAb3:-MISGHty63bfKsk4Ts6l:bn4c0fj) ([raw file](https://github.com/pmem/rpma/blob/bf0c73453317a4f1cf2648e4ac897ebcbde59504/src/include/librpma.h#L1976)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Yes, I know, but shall we just assume that non-zero return is correct, non error returned value?
</blockquote></details>

All our examples verify only if ret value si != 0

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/478)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[src/include/librpma.h, line 131 at r2](https://reviewable.io/reviews/pmem/rpma/478#-MISEJgZ4iH1iGsGwszr:-MISTaRa6FJTEEHV9XkK:b1scr29) ([raw file](https://github.com/pmem/rpma/blob/bf0c73453317a4f1cf2648e4ac897ebcbde59504/src/include/librpma.h#L131)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> negative error code
> ```
non-zero error code

</blockquote></details>

Why? Is there a function that returns >0 error code in case of failure?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/478)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[src/include/librpma.h, line 140 at r2](https://reviewable.io/reviews/pmem/rpma/478#-MISEqzg6q7rXheCopMP:-MISUxq6Ez1JJsJ3HvNz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bf0c73453317a4f1cf2648e4ac897ebcbde59504/src/include/librpma.h#L140)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> print
> ```
handle
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 143 at r2](https://reviewable.io/reviews/pmem/rpma/478#-MISFdw15dNAxwtaF1fo:-MISVIDJ3fKf_V4FNe1p:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bf0c73453317a4f1cf2648e4ac897ebcbde59504/src/include/librpma.h#L143)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> a pointer to
> ```
to be removed
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 146 at r2](https://reviewable.io/reviews/pmem/rpma/478#-MISEc5p8tlyPnfnu_nd:-MISVId3D0MVRCaUxewm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bf0c73453317a4f1cf2648e4ac897ebcbde59504/src/include/librpma.h#L146)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> rpma_log_set_threshold()/rpma_log_get_threshold()
> ```

</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1976 at r2](https://reviewable.io/reviews/pmem/rpma/478#-MIPcic11i4_vS2UfAb3:-MISVkLgEOagz3ev8pds:bod8lh1) ([raw file](https://github.com/pmem/rpma/blob/bf0c73453317a4f1cf2648e4ac897ebcbde59504/src/include/librpma.h#L1976)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

All our examples verify only if ret value si != 0 
</blockquote></details>

Hmm, all of our API functions have this:

```
 * RETURN VALUE
 * rpma_*() function returns 0 on success or a negative
 * error code on failure.
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/478)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[src/include/librpma.h, line 131 at r2](https://reviewable.io/reviews/pmem/rpma/478#-MISF2PUBi2X4u0B06-8:-MISX_pg-P1RX_YehbMC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bf0c73453317a4f1cf2648e4ac897ebcbde59504/src/include/librpma.h#L131)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> If a librpma API function may fail, it returns a negative error code
> according to its manual.
> ```
Each librpma API function returns a non-zero error code in case it fails.
Detail error codes meaning are described in functions manuals.
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/478#-:-MISZi6AEgrsnCV2odfL:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[src/include/librpma.h, line 144 at r3](https://reviewable.io/reviews/pmem/rpma/478#-MISZuB19riVEUm1T5HK:-MISZuB19riVEUm1T5HL:b-ftgqd9) ([raw file](https://github.com/pmem/rpma/blob/493a756a20af2db5698a120141f302bf3ff156d7/src/include/librpma.h#L144)):*
> ```
> a user-defined function
> ```
a user-defined, thread safety, function

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/478)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[src/include/librpma.h, line 144 at r3](https://reviewable.io/reviews/pmem/rpma/478#-MISZuB19riVEUm1T5HK:-MISaDIuB3PfT4IcS9z4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/493a756a20af2db5698a120141f302bf3ff156d7/src/include/librpma.h#L144)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> a user-defined function
> ```
a user-defined, thread safety, function
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/478)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/include/librpma.h, line 149 at r4](https://reviewable.io/reviews/pmem/rpma/478#-MISsS0nEd2dX7O6PnIQ:-MISsS0nEd2dX7O6PnIR:bkm27rh) ([raw file](https://github.com/pmem/rpma/blob/1a8eadbff8b8dd0a641ac25b365b8e37988711fa/src/include/librpma.h#L149)):*
> ```objc
>  * rpma_log_set_threshold()/rpma_log_get_threshold().
>  *
>  * There is an example of usage of logging functions:
> ```

the usage

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/478)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[src/include/librpma.h, line 149 at r4](https://reviewable.io/reviews/pmem/rpma/478#-MISsS0nEd2dX7O6PnIQ:-MIT3dEg31qHs9JCgRG_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1a8eadbff8b8dd0a641ac25b365b8e37988711fa/src/include/librpma.h#L149)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

the usage
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/478)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/478#-:-MIT7uG91P8uD-o-kQoo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
