### PR TITLE
rpma: fix description of usage of PMem in the integration tests

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1841)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1841)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[`DEVELOPMENT.md` line 132 at r1](https://reviewable.io/reviews/pmem/rpma/1841#-N4a7G-a0KnrmKdzd0YC:-N4a7G-a0KnrmKdzd0YD:b45h) ([raw file](https://github.com/pmem/rpma/blob/bb942b062f5865b5523f769a512322705b5caec5/DEVELOPMENT.md#L132)):*
> ```Markdown
> from the main directory of the librpma repository.
> 
> If the `<pmem-path>` argument is used:
> ```





_Suggestion:_
```Markdown
To run the examples on the PMem please provide a PMem path either as `<pmem-path>` argument (a DAX device or a file on a file system DAX):

```sh
$ ./examples/run-all-examples.sh ./build/examples/ --fault-injection <pmem-path>
```

or via the `RPMA_EXAMPLES_PMEM_PATH` environment variable set.
If both of them are set, the command line argument `<pmem-path>` will be used.
`<pmem-path>` has to start with '/'.
```


<!-- Sent from Reviewable.io -->

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1841)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1841)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`DEVELOPMENT.md` line 132 at r1](https://reviewable.io/reviews/pmem/rpma/1841#-N4a7G-a0KnrmKdzd0YC:-N4aIdNm4s3xxgTpi0mN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bb942b062f5865b5523f769a512322705b5caec5/DEVELOPMENT.md#L132)):*
> ```Markdown
> from the main directory of the librpma repository.
> 
> If the `<pmem-path>` argument is used:
> ```

Done.

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1841#-:-N4aLiDI-Mtu-ul6H4Qn:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1841)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`DEVELOPMENT.md` line 132 at r1](https://reviewable.io/reviews/pmem/rpma/1841#-N4a7G-a0KnrmKdzd0YC:-N4aPfxt8dDwW_oexnRe:b-voa6xb) ([raw file](https://github.com/pmem/rpma/blob/bb942b062f5865b5523f769a512322705b5caec5/DEVELOPMENT.md#L132)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@grom72  ping

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1841#-:-N4ah0Mw9ADm8VMIK8OH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
