### PR TITLE
examples: fix build examples with libpmem

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1878)

### CODE REVIEW

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1878#-:-N5Zn0rVCV2rBh4so9YI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1878)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1878)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[`examples/CMakeLists.txt` line 84 at r1](https://reviewable.io/reviews/pmem/rpma/1878#-N5d7OhlAaH2UMYtN4Jq:-N5d7OhmAG_uiACbToqT:b-dgqgco) ([raw file](https://github.com/pmem/rpma/blob/0b25e36e14b3db9eeabbdfd5806b714e9f80a9cf/examples/CMakeLists.txt#L84)):*
> ```CMake
> 		target_compile_definitions(${target}
> 			PRIVATE USE_LIBPMEM2)
> 	elseif(LIBPMEM_FOUND)
> ```

@osalyk  @grom72  What about a simpler fix?
```
	endif()
	#
	# XXX revert it to:
	# elseif(LIBPMEM_FOUND)
	# when all examples have support for libpmem2.
	#
	if(LIBPMEM_FOUND)
```
see https://github.com/pmem/rpma/pull/1885 - less changes in the code and less merge conflicts in the future.



_Code quote:_
```CMake
elseif(LIBPMEM_FOUND)
```
___
*[`examples/CMakeLists.txt` line 95 at r1](https://reviewable.io/reviews/pmem/rpma/1878#-N5d839T1PtVsaf8jGBf:-N5d839T1PtVsaf8jGBg:batv3ox) ([raw file](https://github.com/pmem/rpma/blob/0b25e36e14b3db9eeabbdfd5806b714e9f80a9cf/examples/CMakeLists.txt#L95)):*
> ```CMake
> 	if(EXAMPLE_USE_LIBPMEM_IF_FOUND AND LIBPMEM_FOUND)
>                target_include_directories(${target}
>                        PRIVATE ${LIBPMEM_INCLUDE_DIRS})
> ```

wrong indentation



_Code quote:_
```CMake
               target_include_directories(${target}
                       PRIVATE ${LIBPMEM_INCLUDE_DIRS})
               target_link_libraries(${target} ${LIBPMEM_LIBRARIES})
               target_compile_definitions(${target}
                       PRIVATE USE_LIBPMEM)
       endif()
```

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1878)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1878#-N5d9bLy2-chR3pDzd4Z:-N5d9bLz1fALyrCV3M2g:bknibq3) (no related file):*
Would it be better to use ``USE_LIBPMEM_IF_FOUND`` option to say what version of libpmem should be used by examples?
0- none, 1-libpmem, 2-libpmem2
Later we could extend this option to use it dynamically for different version of examples (DRAM/PMEM/PMEM2) running on system when all libraries are installed.



_Code quote (from examples/CMakeLists.txt):_
```CMake
USE_LIBPMEM_IF_FOUND 
```

___

**Comment by osalyk** [comment]
Fixed at #1885

**Pull request closed without merging**
