### PR TITLE
tools: add error messages to Benchmark.run()

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1135)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1135#-:-Me-Q0fwBwpw_riYiDK1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1135)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/lib/Benchmark.py, line 99 at r1](https://reviewable.io/reviews/pmem/rpma/1135#-Me0piVG-QNbb9FyDQxP:-Me0piVG-QNbb9FyDQxQ:bidjf7r) ([raw file](https://github.com/pmem/rpma/blob/a04994666f0d995daa4f233f0c3ade1539219a68/tools/perf/lib/Benchmark.py#L99)):*
> ```Python
>     def _benchmark_args(self, env):
>         if 'tool' not in self.oneseries:
>             print("error: 'tool' is missing in the figure")
> ```

I think a more standard way of doing this is just providing a message to the exception.

```python
raise ValueError("'tool' is missing in the figure")
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1135)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi and @osalyk)

___
*[tools/perf/lib/Benchmark.py, line 99 at r1](https://reviewable.io/reviews/pmem/rpma/1135#-Me0piVG-QNbb9FyDQxP:-Me3yK0g6ZLFhEuf7npG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a04994666f0d995daa4f233f0c3ade1539219a68/tools/perf/lib/Benchmark.py#L99)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think a more standard way of doing this is just providing a message to the exception.

```python
raise ValueError("'tool' is missing in the figure")
```
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1135)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/lib/Benchmark.py, line 103 at r2](https://reviewable.io/reviews/pmem/rpma/1135#-Me46t003nwMYELTmKhQ:-Me46t003nwMYELTmKhR:bcyeze7) ([raw file](https://github.com/pmem/rpma/blob/724efcbd32e704f141199fb689a00c626b1b54cf/tools/perf/lib/Benchmark.py#L103)):*
> ```Python
>             raise ValueError("'mode' is missing in the figure")
>         if 'server_ip' not in env:
>             raise ValueError("'server_ip' is missing in the environment")
> ```

... in the configuration.

`server_ip` is meant to be provided via the `config.json`.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1135)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/Benchmark.py, line 103 at r2](https://reviewable.io/reviews/pmem/rpma/1135#-Me46t003nwMYELTmKhQ:-Me4BP-6ELuSL0jumaRz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/724efcbd32e704f141199fb689a00c626b1b54cf/tools/perf/lib/Benchmark.py#L103)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

... in the configuration.

`server_ip` is meant to be provided via the `config.json`.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1135#-:-Me4cBUH0ZpVxwX8009C:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
