### PR TITLE
test: fix checking if valgrind -s option is supported

### PR DESCRIPTION
**Pull request by ldorau**
The 'valgrind -s date' command can fail also because of valgrind
issues in the 'date' command, not only because of unknown '-s' option.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1866)

### CODE REVIEW

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1866#-:-N5FnUSiCE8tLnb8-VMv:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1866)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
The '-s' option works now: 
https://app.circleci.com/pipelines/github/ldorau/rpma/4396/workflows/a016411c-c0f4-4863-ae2f-9bb3a0343198/jobs/4483

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1866#-:-N5Fvxo96eoBabVniUtO:bltd151)* status: 0 of 3 files reviewed, all discussions resolved (waiting on @grom72)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1866#-:-N5GFDD1DRoVsEU68Qpv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1866)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
