### PR TITLE
test: add missing suppression for drd

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1039)

### CODE REVIEW

**Comment by ldorau** [comment]
See: https://app.circleci.com/pipelines/github/ldorau/rpma/357/workflows/ce5d6209-6141-49bb-87f6-3a9174a50885/jobs/369

**Review by ldorau — COMMENTED** [review]
See: https://app.circleci.com/pipelines/github/ldorau/rpma/365/workflows/272cd121-1202-4f2a-a440-742977938d90/jobs/377

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1039#-:-MZSvP4e0WYkvcrEfPyA:b-8vvlau)* status: 0 of 1 files reviewed, all discussions resolved

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1039#-:-MZTXYxPCEFBzVHSRlIr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
See: https://app.circleci.com/pipelines/github/ldorau/rpma/367/workflows/39480b30-1c5f-4a0f-9358-ef3332415412/jobs/379

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1039#-:-MZWosdW5efUq1NdeJrw:be3ntyf)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1039)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
