### PR TITLE
doc: improve formatting

### PR DESCRIPTION
**Pull request by osalyk**
** ... ** -> \f[B] ... \f[R]
\* ... * -> \f[I] ... \f[R]

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/529)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/529#-:-MIZGCAL13C-32ePgdbI:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/529)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/529#-:-MIZGIPp1uY3M7kBwG1C:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/529)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/529#-MIZGuxxEOJ5ZchLn2gD:-MIZGuxxEOJ5ZchLn2gE:b-ffovoc) (no related file):*
Wait, there is a build running: https://github.com/ldorau/rpma/actions/runs/282390558

---

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/529)* status: :shipit: complete! all files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/pmem/rpma/529#-MIZGuxxEOJ5ZchLn2gD:-MIZKI7338P_X-62q9AE:b-pxppp) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Wait, there is a build running: https://github.com/ldorau/rpma/actions/runs/282390558
</blockquote></details>

All tests passed

---

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/529#-:-MIZN9Dy67d8NoRVqesy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
