### PR TITLE
tools: perf: FioRunner (scaffolding)

### PR DESCRIPTION
**Pull request by janekmi**
Requires:

- [x] #1328

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1330)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 9 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1330)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1330)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 76 at r1](https://reviewable.io/reviews/pmem/rpma/1330#-MorTqZk7FsHfkLfnWPR:-MorTqZk7FsHfkLfnWPS:brvrbky) ([raw file](https://github.com/pmem/rpma/blob/876fbe3b44b9492a62d5443dd174fdbb59889817/tools/perf/lib/benchmark/runner/fio.py#L76)):*
> ```
>             # XXX a new required config.json argument or has to be read
>             # from the remote system
> ```

Please explain. It is not clear to me.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1330)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1330)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 66 at r1](https://reviewable.io/reviews/pmem/rpma/1330#-Mos8clN8LahjjjejeTR:-Mos8clO8Rxfnaw7INl_:b-yftyht) ([raw file](https://github.com/pmem/rpma/blob/876fbe3b44b9492a62d5443dd174fdbb59889817/tools/perf/lib/benchmark/runner/fio.py#L66)):*
> ```
> # pylint: disable=unused-variable
> ```

Please add `# XXX to be removed when variables are used` before

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1330)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 109 at r1](https://reviewable.io/reviews/pmem/rpma/1330#-MosVHJA0a0isa4VFQID:-MosVHJA0a0isa4VFQIE:be2e77c) ([raw file](https://github.com/pmem/rpma/blob/876fbe3b44b9492a62d5443dd174fdbb59889817/tools/perf/lib/benchmark/runner/fio.py#L109)):*
> ```
>  config 
> ```

fio job file

**Review by ldorau — COMMENTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1330)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1330#-:-MoslG53Aa479qRrc2o0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 10 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1330#-:-MosqZH5AifS9vcyk7Cl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1330)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
