### PR TITLE
test: add missing unit tests for rpma_conn_delete()

### PR DESCRIPTION
**Pull request by ldorau**
Required:

- [x] #1663
- [x] #1655 
- [x] #1668

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1662)

### CODE REVIEW

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1662)* status: 0 of 19 files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 9 of 15 files at r3, 2 of 14 files at r4, 12 of 12 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1662#-:-N00KnY28jsmIrjW5PVn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 14 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1662#-:-N00OrRz6diQbeKLcOYC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1662)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
> Reviewed 3 of 5 files at r6, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1662)* status: 23 of 24 files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 5 files at r6, 2 of 2 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1662#-:-N00nhxnBtLE2ouKAmbA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
