### PR TITLE
common: use logging module in the RPMA library

### PR DESCRIPTION
**Pull request by janekmi**
Requires:

- [x] #277

This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/278)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
We should show more information about the parameters  of failed calls if we can do this without big effort
or later add also some debug/info message for every public function call parameters
this is the way we could help end-users to identify the root cause of the problem
1) run application -> error situation -> general error message
2)change the logging level to debug/info
3) rerun application -> see full diagnostic in the log

> Reviewed 42 of 42 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/278#-:-MF6zt_A2cbehFJxwScT:bo229si)* status: all files reviewed, 7 unresolved discussions (waiting on @janekmi)

___
*[src/common.h, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/278#-MF6zBd4BD3T22QJyiVu:-MF6zBd4BD3T22QJyiVv:b-h55ltp) ([raw file](https://github.com/pmem/rpma/blob/8d8140bf9d01f79e4126c0c4ce42ac06654e8ecc/src/common.h#L2)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> /*
>  * SPDX-License-Identifier: BSD-3-Clause
>  * Copyright 2020, Intel Corporation
>  */
> ```
</details>

/* SPDX-License-Identifier: BSD-3-Clause */
/* Copyright 2020, Intel Corporation  */
___
*[src/flush.c, line 60 at r1](https://reviewable.io/reviews/pmem/rpma/278#-MF6yZ_KCrPiv_xJwL3g:-MF6yZ_KCrPiv_xJwL3h:bweqkrb) ([raw file](https://github.com/pmem/rpma/blob/8d8140bf9d01f79e4126c0c4ce42ac06654e8ecc/src/flush.c#L60)):*
> ```
> RPMA_LOG_ERROR_WITH_ERRNO("sysconf", Rpma_provider_error);
> ```
it will be worth to display also here the value of sysconf() input param
___
*[src/flush.c, line 61 at r1](https://reviewable.io/reviews/pmem/rpma/278#-MF6yqn0EE6GimssgpLv:-MF6yqn0EE6GimssgpLw:b7ezyii) ([raw file](https://github.com/pmem/rpma/blob/8d8140bf9d01f79e4126c0c4ce42ac06654e8ecc/src/flush.c#L61)):*
> ```
> RPMA_E_PROVIDER
> ```
it is not a provider error, but let's leave it as it is
___
*[src/info.c, line 56 at r1](https://reviewable.io/reviews/pmem/rpma/278#-MF6zbPSA0hZIZeZuSCw:-MF6zbPSA0hZIZeZuSCx:b8gta8s) ([raw file](https://github.com/pmem/rpma/blob/8d8140bf9d01f79e4126c0c4ce42ac06654e8ecc/src/info.c#L56)):*
> ```
> RPMA_LOG_ERROR_WITH_ERRNO("rdma_getaddrinfo"
> ```
rdma_getaddrinfo parameters to be displayed here
___
*[src/log_internal.h, line 49 at r1](https://reviewable.io/reviews/pmem/rpma/278#-MF6xienBziJJyoXW-8F:-MF6xienBziJJyoXW-8G:b57mdgz) ([raw file](https://github.com/pmem/rpma/blob/8d8140bf9d01f79e4126c0c4ce42ac06654e8ecc/src/log_internal.h#L49)):*
> ```
> RPMA_LOG_ERRNO(
> ```
do we need this?
___
*[tests/unit/common/mocks-rpma-log.c, line 19 at r1](https://reviewable.io/reviews/pmem/rpma/278#-MF7-OEv18wd4JciIMwD:-MF7-OEv18wd4JciIMwE:b-ovsenh) ([raw file](https://github.com/pmem/rpma/blob/8d8140bf9d01f79e4126c0c4ce42ac06654e8ecc/tests/unit/common/mocks-rpma-log.c#L19)):*
> ```C
>  */
> static void
> mock_function(rpma_log_level level, const char *file_name,
> ```

is it a part of this request or some dependencies?
___
*[tests/unit/common/mocks-rpma-utils.c, line 44 at r1](https://reviewable.io/reviews/pmem/rpma/278#-MF7-br58pmTHVVKVULq:-MF7-br58pmTHVVKVULr:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/8d8140bf9d01f79e4126c0c4ce42ac06654e8ecc/tests/unit/common/mocks-rpma-utils.c#L44)):*
> ```C
>  */
> const char *
> rpma_utils_conn_event_2str(enum rpma_conn_event conn_event)
> ```

.

**Review by janekmi — COMMENTED** [review]
I like the idea. But I also think it can be divided into two steps. First add necessary logging calls. Second add nice to have / advanced debug logging.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/278#-:-MF7oYN77ZRN429rpi5x:b-94t13e)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[src/flush.c, line 60 at r1](https://reviewable.io/reviews/pmem/rpma/278#-MF6yZ_KCrPiv_xJwL3g:-MF7oxV6DiLKMf_B-e_6:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/8d8140bf9d01f79e4126c0c4ce42ac06654e8ecc/src/flush.c#L60)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> RPMA_LOG_ERROR_WITH_ERRNO("sysconf", Rpma_provider_error);
> ```
it will be worth to display also here the value of sysconf() input param
</blockquote></details>

.
___
*[src/flush.c, line 61 at r1](https://reviewable.io/reviews/pmem/rpma/278#-MF6yqn0EE6GimssgpLv:-MF7p0Uu-Vv8EdDOIZi7:b-6vy5pj) ([raw file](https://github.com/pmem/rpma/blob/8d8140bf9d01f79e4126c0c4ce42ac06654e8ecc/src/flush.c#L61)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> RPMA_E_PROVIDER
> ```
it is not a provider error, but let's leave it as it is
</blockquote></details>

Yeah. If you have a better idea I think we can fix this in a separate PR.
___
*[src/info.c, line 56 at r1](https://reviewable.io/reviews/pmem/rpma/278#-MF6zbPSA0hZIZeZuSCw:-MF7pCURDRGyf7o4d5Q7:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/8d8140bf9d01f79e4126c0c4ce42ac06654e8ecc/src/info.c#L56)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> RPMA_LOG_ERROR_WITH_ERRNO("rdma_getaddrinfo"
> ```
rdma_getaddrinfo parameters to be displayed here
</blockquote></details>

.
___
*[tests/unit/common/mocks-rpma-log.c, line 19 at r1](https://reviewable.io/reviews/pmem/rpma/278#-MF7-OEv18wd4JciIMwD:-MF7pkkh5ckQtlK0t2Nj:bwl778z) ([raw file](https://github.com/pmem/rpma/blob/8d8140bf9d01f79e4126c0c4ce42ac06654e8ecc/tests/unit/common/mocks-rpma-log.c#L19)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

is it a part of this request or some dependencies?
</blockquote></details>

It is required if any module has logging calls. Then you need the logging function pointer. If it may be called it will work better if the pointer is not NULL. ;-) This function will be also later part of the logging validation.
___
*[tests/unit/common/mocks-rpma-utils.c, line 44 at r1](https://reviewable.io/reviews/pmem/rpma/278#-MF7-br58pmTHVVKVULq:-MF7qtXQ8iixxbnbDzMo:bbbmdsg) ([raw file](https://github.com/pmem/rpma/blob/8d8140bf9d01f79e4126c0c4ce42ac06654e8ecc/tests/unit/common/mocks-rpma-utils.c#L44)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

This used in some module for logging purposes so it has to be mocked since it is a part of the utils module.

**Review by grom72 — COMMENTED** [review]
I will add to the next sprint scope as without detail information log information has no value - I mean does not allow a user to identify the problem
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/278#-:-MF9H_0D6Nfyc4g1Sg7e:b-12prw7)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/278)* status: 8 of 22 files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[src/common.h, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/278#-MF6zBd4BD3T22QJyiVu:-MF9eTHs3AhytLI-7L8P:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8d8140bf9d01f79e4126c0c4ce42ac06654e8ecc/src/common.h#L2)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> /*
>  * SPDX-License-Identifier: BSD-3-Clause
>  * Copyright 2020, Intel Corporation
>  */
> ```
/* SPDX-License-Identifier: BSD-3-Clause */
/* Copyright 2020, Intel Corporation  */
</blockquote></details>

Done.
___
*[src/log_internal.h, line 49 at r1](https://reviewable.io/reviews/pmem/rpma/278#-MF6xienBziJJyoXW-8F:-MF9ebuX--e5o7Wh7zm4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8d8140bf9d01f79e4126c0c4ce42ac06654e8ecc/src/log_internal.h#L49)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> RPMA_LOG_ERRNO(
> ```
do we need this?
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 4 of 16 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/278)* status: 12 of 22 files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/278#-:-MF9fr_KBNI6x0oHsJss:bnfp4nl)* status: 12 of 22 files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/278)* status: 12 of 22 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[src/conn_req.c, line 366 at r2](https://reviewable.io/reviews/pmem/rpma/278#-MF9gihMElPUX5HpbhmD:-MF9gihMElPUX5HpbhmE:b9an14) ([raw file](https://github.com/pmem/rpma/blob/795e64b5d498fdbb5deedd1474155545cb804cc9/src/conn_req.c#L366)):*
> ```
> rpma_info_resolve_addr
> ```
missing LOG_ERROR

**Review by grom72 — COMMENTED** [review]
> Reviewed 3 of 16 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/278)* status: 15 of 22 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[src/ep.c, line 184 at r2](https://reviewable.io/reviews/pmem/rpma/278#-MF9hNao9vnxaWr6tHid:-MF9hNap0H39fudrHBTW:b-pir7m3) ([raw file](https://github.com/pmem/rpma/blob/795e64b5d498fdbb5deedd1474155545cb804cc9/src/ep.c#L184)):*
> ```
> ret = RPMA_E_INVAL
> ```
good place for warning

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/278)* status: 13 of 22 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[src/conn_req.c, line 366 at r2](https://reviewable.io/reviews/pmem/rpma/278#-MF9gihMElPUX5HpbhmD:-MF9mr6Q0UYfjmNaq5xL:b3zvni7) ([raw file](https://github.com/pmem/rpma/blob/795e64b5d498fdbb5deedd1474155545cb804cc9/src/conn_req.c#L366)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> rpma_info_resolve_addr
> ```
missing LOG_ERROR
</blockquote></details>

`rpma_info_resolve_addr()` already has logging inside.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 16 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/278)* status: 13 of 23 files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — COMMENTED** [review]
> Reviewed 7 of 42 files at r1, 1 of 16 files at r2, 1 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/278)* status: 14 of 23 files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 42 files at r1, 2 of 16 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/278)* status: 14 of 23 files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tests/unit/common/mocks-rpma-log.c, line 23 at r3](https://reviewable.io/reviews/pmem/rpma/278#-MF9pWMD9We8akbX04WT:-MF9pWMD9We8akbX04WU:b-nsqcu9) ([raw file](https://github.com/pmem/rpma/blob/62b3102a4c4ad9c0f5f631ffa34740c78f883292/tests/unit/common/mocks-rpma-log.c#L23)):*
> ```C
> 	const char *message_format, ...)
> {
> ```

redundant empty line

**Review by ldorau — COMMENTED** [review]
> Reviewed 6 of 16 files at r2, 4 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/278)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[src/conn.c, line 228 at r3](https://reviewable.io/reviews/pmem/rpma/278#-MF9q9YI2XyjteHFQPGB:-MF9q9YI2XyjteHFQPGC:b-f8ehv5) ([raw file](https://github.com/pmem/rpma/blob/62b3102a4c4ad9c0f5f631ffa34740c78f883292/src/conn.c#L228)):*
> ```
> Requesting a disconnection
> ```

Requesting for disconnection

**Review by ldorau — COMMENTED** [review]
:goat: :-)

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/278#-:-MF9rJPa-LYPASv8TLin:b-wmy1vk)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/278)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/278#-:-MF9tbcq6tgpVaOyvnHm:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/278)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tests/unit/common/mocks-rpma-log.c, line 23 at r3](https://reviewable.io/reviews/pmem/rpma/278#-MF9pWMD9We8akbX04WT:-MF9srXM90sHA_XQuLfX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/62b3102a4c4ad9c0f5f631ffa34740c78f883292/tests/unit/common/mocks-rpma-log.c#L23)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

redundant empty line
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/278)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[src/conn.c, line 461 at r3](https://reviewable.io/reviews/pmem/rpma/278#-MF9tRAD9UcNkRuKIq4m:-MF9tRAE960liT2XBgw8:brsnuor) ([raw file](https://github.com/pmem/rpma/blob/62b3102a4c4ad9c0f5f631ffa34740c78f883292/src/conn.c#L461)):*
> ```
> ERROR
> ```
WARNING??

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/278)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/conn.c, line 461 at r3](https://reviewable.io/reviews/pmem/rpma/278#-MF9tRAD9UcNkRuKIq4m:-MFA44hhAIu1C-cniC6y:b9yz060) ([raw file](https://github.com/pmem/rpma/blob/62b3102a4c4ad9c0f5f631ffa34740c78f883292/src/conn.c#L461)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> ERROR
> ```
WARNING??
</blockquote></details>

```c
/* an errors that could be handled in the upper level */
RPMA_LOG_LEVEL_WARNING,
```

I do not understand what the user can do with an unexpected opcode. It seems something went awfully wrong since we have full control over the connection so no unknown opcodes should appear.

I will leave it as is. We can discuss it later.

**Pull request merged**
