### PR TITLE
tools: Runner class introduction

### PR DESCRIPTION
**Pull request by haichangsi**
This PR introduce new class Runner.
The Runner class is design to handle all common operation.
In this PR common handling for benchmark, config, idfile
has been added

test_runner_init.py proivdes set of UT for Runner initialization.

test_fio_runner.init.py and test_ib_read_runner_init.py
extend some tests to utilize new features of common superclass

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1531)

### CODE REVIEW

**Review by haichangsi — COMMENTED** [review]
As @grom72 said it first pr should look like that, tell me if I did it correctly @ldorau please

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1531#-:-MupU94_EWuWwVMxxplZ:b-27jhfo)* status: 0 of 8 files reviewed, all discussions resolved

**Review by haichangsi — COMMENTED** [review]
Also current version of the devel-new-python already has Tomek's PR 'extend unit test' but he also said that this should be my second PR so I decided to leave the version without it 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1531#-:-MuqYhfQ3bHPLq4Xl6jw:b37rthj)* status: 0 of 8 files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1531)* status: 0 of 8 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1531)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @haichangsi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1531#-MutNRsd7F-LJ6OgUU50:-MutNRse5wq9msNBLOoA:b-p6ne6n) (no related file):*
Please fix the copyright dates:
```
tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py:1: error: wrong copyright date: (is: 2021-2021, should be: 2021-2022)
tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py:1: error: wrong copyright date: (is: 2021-2021, should be: 2021-2022)
```

---

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 8 files at r1, 3 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1531)* status: 4 of 8 files reviewed, 1 unresolved discussion (waiting on @grom72, @haichangsi, and @ldorau)

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1531)* status: 6 of 8 files reviewed, 6 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 204 at r2](https://reviewable.io/reviews/pmem/rpma/1531#-MwayEZ23E6tkXtU8ZOJ:-MwayEZ23E6tkXtU8ZOK:b-cjbwel) ([raw file](https://github.com/pmem/rpma/blob/8357773950f9631f3fc70549ce28020417100c66/tools/perf/lib/benchmark/runner/fio.py#L204)):*
> ```Python
>         args = env + args
>         # dump a command to the log file
>         if self._dump_cmds:
> ```

why only one underscore ```_```?



_Code quote:_
```Python
_dump_cmds
```
___
*[tools/perf/lib/benchmark/runner/fio.py, line 252 at r2](https://reviewable.io/reviews/pmem/rpma/1531#-MwayXL38EO83rG4EBpi:-MwayXL38EO83rG4EBpj:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/8357773950f9631f3fc70549ce28020417100c66/tools/perf/lib/benchmark/runner/fio.py#L252)):*
> ```Python
>             timeout = 300 # the default timeout is 5 minutes
>         # dump a command to the log file
>         if self._dump_cmds:
> ```

.



_Code quote:_
```Python
_dump_cmds
```
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 115 at r2](https://reviewable.io/reviews/pmem/rpma/1531#-MwayaPy4j4_20d3dyEH:-MwayaPy4j4_20d3dyEI:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/8357773950f9631f3fc70549ce28020417100c66/tools/perf/lib/benchmark/runner/ib_read.py#L115)):*
> ```Python
>         args = ['numactl', '-N', r_numa_n, self.__r_ib_path, *r_aux_params]
>         # dump a command to the log file
>         if self._dump_cmds:
> ```

.



_Code quote:_
```Python
_dump_cmds
```
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 158 at r2](https://reviewable.io/reviews/pmem/rpma/1531#-MwayeL8Afe55BNjPlEs:-MwayeL8Afe55BNjPlEt:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/8357773950f9631f3fc70549ce28020417100c66/tools/perf/lib/benchmark/runner/ib_read.py#L158)):*
> ```Python
>                 it_opt, server_ip]
>         # dump a command to the log file
>         if self._dump_cmds:
> ```

.



_Suggestion:_
```Python
_dump_cmds
```
___
*[tools/perf/lib/benchmark/runner/runner.py, line 38 at r2](https://reviewable.io/reviews/pmem/rpma/1531#-Mwb-SZR6Vi34nkpyu3M:-Mwb-SZR6Vi34nkpyu3N:b-6r75gd) ([raw file](https://github.com/pmem/rpma/blob/8357773950f9631f3fc70549ce28020417100c66/tools/perf/lib/benchmark/runner/runner.py#L38)):*
> ```Python
> 
>             for key in self.__ONESERIES_REQUIRED:
>                 if key not in self._benchmark.oneseries:
> ```

_oneseries



_Code quote:_
```Python
_benchmark.oneseries
```

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1531)* status: 6 of 8 files reviewed, 6 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1531#-MutNRsd7F-LJ6OgUU50:-Mwb8P-c3OqnLBk5qx6f:bq1ijai) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please fix the copyright dates:
```
tools/perf/tests/lib/benchmark/runner/test_fio_runner_init.py:1: error: wrong copyright date: (is: 2021-2021, should be: 2021-2022)
tools/perf/tests/lib/benchmark/runner/test_ib_read_runner_init.py:1: error: wrong copyright date: (is: 2021-2021, should be: 2021-2022)
```

</blockquote></details>

I thing we should add unit tests for this new class

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1531)* status: 6 of 8 files reviewed, 6 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1531#-MutNRsd7F-LJ6OgUU50:-MwbC3MyDLR1eR4jTl3z:b-uinaa2) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I thing we should add unit tests for this new class
</blockquote></details>

Yes, but this issue is about fixing the copyright dates ;-)

---

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1, 1 of 6 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1531)* status: all files reviewed, 7 unresolved discussions (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1531#-MwbO_bu2Z3NveJiL9sH:-MwbO_bu2Z3NveJiL9sI:bishmsm) (no related file):*
I think we should add unit tests for this new class

---

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1531)* status: all files reviewed, 8 unresolved discussions (waiting on @haichangsi)

___
*[tools/perf/tests/lib/benchmark/runner/test_runner_init.py, line 17 at r2](https://reviewable.io/reviews/pmem/rpma/1531#-MwhKcLnB1jmkeIt_Ngx:-MwhKcLnB1jmkeIt_Ngy:b-8152de) ([raw file](https://github.com/pmem/rpma/blob/8357773950f9631f3fc70549ce28020417100c66/tools/perf/tests/lib/benchmark/runner/test_runner_init.py#L17)):*
> ```Python
> 
> from lib.benchmark.runner.runner import Runner
> __ONESERIES_MINI = {'tool': 'tool', 'mode': 'mode', 'tool_mode': 'tool_mode'}
> ```

I would suggest having a different values for key and value.



_Code quote:_
```Python
tool
```
___
*[tools/perf/tests/lib/benchmark/runner/test_runner_init.py, line 54 at r2](https://reviewable.io/reviews/pmem/rpma/1531#-MwhLGXuBInb0VlUocyV:-MwhLGXuBInb0VlUocyW:b-o1juk4) ([raw file](https://github.com/pmem/rpma/blob/8357773950f9631f3fc70549ce28020417100c66/tools/perf/tests/lib/benchmark/runner/test_runner_init.py#L54)):*
> ```Python
> 
>     assert runner is None
> ```

these scenarios are not covered by unit tests



_Code quote (from tools/perf/lib/benchmark/runner/runner.py):_
```Python
            if self._benchmark is None:
                raise RuntimeError("Benchmark is missing")

            if self._oneseries is None:
                raise RuntimeError("OneSeries is missing")
```

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1531)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

___
*[tools/perf/tests/lib/benchmark/runner/test_runner_init.py, line 17 at r2](https://reviewable.io/reviews/pmem/rpma/1531#-MwhKcLnB1jmkeIt_Ngx:-MwkSAHj5fDxN7S6loAV:b-48quk7) ([raw file](https://github.com/pmem/rpma/blob/8357773950f9631f3fc70549ce28020417100c66/tools/perf/tests/lib/benchmark/runner/test_runner_init.py#L17)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I would suggest having a different values for key and value.
</blockquote></details>

i.e. 'tool`: `some_tool`
___
*[tools/perf/tests/lib/benchmark/runner/test_runner_init.py, line 54 at r2](https://reviewable.io/reviews/pmem/rpma/1531#-MwhLGXuBInb0VlUocyV:-MwkSPNg4tKR9VhdViSQ:b-uhltsi) ([raw file](https://github.com/pmem/rpma/blob/8357773950f9631f3fc70549ce28020417100c66/tools/perf/tests/lib/benchmark/runner/test_runner_init.py#L54)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

these scenarios are not covered by unit tests
</blockquote></details>

test_runner_init_failed_no_benchmark
test_runner_init_failed_no_onseries



_Code quote:_
```Python
test_runner_init_failed_no_config
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1531)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1531#-MutNRsd7F-LJ6OgUU50:-MwzUum017VsGdPX0On1:bucrczu) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, but this issue is about fixing the copyright dates ;-)
</blockquote></details>

CI builds fail.

---

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1531)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

**Comment by ldorau** [comment]
Postponed to an undefined future.

**Pull request closed without merging**
