### PR TITLE
tools: make old bash test framework the second option

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1344)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1344)* status: all files reviewed, 4 unresolved discussions (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1344#-MpGg5OE-hqqkvrC6Civ:-MpGg5OF4r-pNGMgAZz-:b-lvinyh) (no related file):*
Please rename the commit's and PR's titles to something like this:

`tools: make old bash test framework the second option`

---
___
*[tools/perf/BENCHMARKING.md, line 59 at r1](https://reviewable.io/reviews/pmem/rpma/1344#-MpGhSb_7EI-myrriTuG:-MpGhSb_7EI-myrriTuH:bc0nmus) ([raw file](https://github.com/pmem/rpma/blob/5049765fc03b536821340aa77c6e20b8e27fa316/tools/perf/BENCHMARKING.md#L59)):*
> ```
> ## Reporting
> ```

`## Generating a report`
___
*[tools/perf/BENCHMARKING.md, line 63 at r1](https://reviewable.io/reviews/pmem/rpma/1344#-MpGhwb952QP8AFYnViz:-MpGhwbA8D97vnXqRbru:b-s2eojr) ([raw file](https://github.com/pmem/rpma/blob/5049765fc03b536821340aa77c6e20b8e27fa316/tools/perf/BENCHMARKING.md#L63)):*
> ```
> Instead of running all separate workloads you can run a comprehensive set of workloads and generate the RPMA performance report.
> 
> To generate a report, follow these steps:
> ```

```
In order to generate the RPMA performance report, follow these steps:
```
___
*[tools/perf/BENCHMARKING.md, line 144 at r1](https://reviewable.io/reviews/pmem/rpma/1344#-MpGiLkL0tfZhug4eR5z:-MpGiLkL0tfZhug4eR6-:b-9cf6yi) ([raw file](https://github.com/pmem/rpma/blob/5049765fc03b536821340aa77c6e20b8e27fa316/tools/perf/BENCHMARKING.md#L144)):*
> ```
> ## Running workloads
> ```

```
## Running separate workloads

Instead of running a comprehensive set of workloads you can run any separate subset of them.
```

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1344)* status: all files reviewed, 6 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[tools/perf/BENCHMARKING.md, line 9 at r1](https://reviewable.io/reviews/pmem/rpma/1344#-MpGiwgx8K09LiGJ3gQO:-MpGiwgx8K09LiGJ3gQP:b-m0g2qm) ([raw file](https://github.com/pmem/rpma/blob/5049765fc03b536821340aa77c6e20b8e27fa316/tools/perf/BENCHMARKING.md#L9)):*
> ```Markdown
> ## Requirements
> 
> To use the benchmarking tools (e.g. `ib_read.sh`, `rpma_fio_bench.sh`), you must have several components installed in your system:
> ```

~~(e.g. `ib_read.sh`, `rpma_fio_bench.sh`)~~

Please also remove this reference.
___
*[tools/perf/BENCHMARKING.md, line 63 at r1](https://reviewable.io/reviews/pmem/rpma/1344#-MpGhwb952QP8AFYnViz:-MpGkz979CjKeGBbFhi9:b-8fx2u7) ([raw file](https://github.com/pmem/rpma/blob/5049765fc03b536821340aa77c6e20b8e27fa316/tools/perf/BENCHMARKING.md#L63)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> Instead of running all separate workloads you can run a comprehensive set of workloads and generate the RPMA performance report.
> 
> To generate a report, follow these steps:
> ```

```
In order to generate the RPMA performance report, follow these steps:
```
</blockquote></details>

:+1: 
___
*[tools/perf/BENCHMARKING.md, line 144 at r1](https://reviewable.io/reviews/pmem/rpma/1344#-MpGiLkL0tfZhug4eR5z:-MpGm2akEbld4Zo3_uQv:b-dhlquk) ([raw file](https://github.com/pmem/rpma/blob/5049765fc03b536821340aa77c6e20b8e27fa316/tools/perf/BENCHMARKING.md#L144)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> ## Running workloads
> ```

```
## Running separate workloads

Instead of running a comprehensive set of workloads you can run any separate subset of them.
```
</blockquote></details>

... subset of them. There are a few tools...

:+1: 
___
*[tools/perf/BENCHMARKING.md, line 202 at r1](https://reviewable.io/reviews/pmem/rpma/1344#-MpGaBxCEffs4nETNAtc:-MpGaBxCEffs4nETNAtd:b8n5v4r) ([raw file](https://github.com/pmem/rpma/blob/5049765fc03b536821340aa77c6e20b8e27fa316/tools/perf/BENCHMARKING.md#L202)):*
> ```Markdown
> ```
> 
> With the help of additional parameters, you can adjust various aspects of the output.
> ```

EOL is missing.

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1344)* status: all files reviewed, 6 unresolved discussions (waiting on @haichangsi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1344#-MpGg5OE-hqqkvrC6Civ:-MpGmXFIAuSbrsQbREu0:b-8fx2u7) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please rename the commit's and PR's titles to something like this:

`tools: make old bash test framework the second option`
</blockquote></details>

:+1: 

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1344)* status: all files reviewed, 6 unresolved discussions (waiting on @haichangsi and @ldorau)

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1344)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1344#-MpGg5OE-hqqkvrC6Civ:-MpHgrAkCwKqS56LkDjp:bb6un1j) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

Done

---
___
*[tools/perf/BENCHMARKING.md, line 9 at r1](https://reviewable.io/reviews/pmem/rpma/1344#-MpGiwgx8K09LiGJ3gQO:-MpHgBK0CyaaQjgDJlTR:b-mnm3ab) ([raw file](https://github.com/pmem/rpma/blob/5049765fc03b536821340aa77c6e20b8e27fa316/tools/perf/BENCHMARKING.md#L9)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

~~(e.g. `ib_read.sh`, `rpma_fio_bench.sh`)~~

Please also remove this reference.
</blockquote></details>

Done, I also think that this sentence is more correct in eng
___
*[tools/perf/BENCHMARKING.md, line 59 at r1](https://reviewable.io/reviews/pmem/rpma/1344#-MpGhSb_7EI-myrriTuG:-MpHgfhb4LM2OtcHFNqp:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/5049765fc03b536821340aa77c6e20b8e27fa316/tools/perf/BENCHMARKING.md#L59)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> ## Reporting
> ```

`## Generating a report`
</blockquote></details>

Done
___
*[tools/perf/BENCHMARKING.md, line 63 at r1](https://reviewable.io/reviews/pmem/rpma/1344#-MpGhwb952QP8AFYnViz:-MpHgi7f1i1ntZaPo7WV:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/5049765fc03b536821340aa77c6e20b8e27fa316/tools/perf/BENCHMARKING.md#L63)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

Done
___
*[tools/perf/BENCHMARKING.md, line 144 at r1](https://reviewable.io/reviews/pmem/rpma/1344#-MpGiLkL0tfZhug4eR5z:-MpHgldB3E9iKF7aHbpr:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/5049765fc03b536821340aa77c6e20b8e27fa316/tools/perf/BENCHMARKING.md#L144)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

... subset of them. There are a few tools...

:+1: 
</blockquote></details>

Done
___
*[tools/perf/BENCHMARKING.md, line 202 at r1](https://reviewable.io/reviews/pmem/rpma/1344#-MpGaBxCEffs4nETNAtc:-MpHgnJb1qsAAPQd7fo5:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/5049765fc03b536821340aa77c6e20b8e27fa316/tools/perf/BENCHMARKING.md#L202)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

EOL is missing.
</blockquote></details>

Done

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1344)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @haichangsi, @janekmi, and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1344#-MpIZNfWBjk9sHUgmCya:-MpIZNfWBjk9sHUgmCyb:bpetlmo) (no related file):*
Please squash those two commits into one with the correct title:



---

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1344)* status: all files reviewed, 5 unresolved discussions (waiting on @haichangsi and @janekmi)

___
*[tools/perf/BENCHMARKING.md, line 9 at r1](https://reviewable.io/reviews/pmem/rpma/1344#-MpGiwgx8K09LiGJ3gQO:-MpIaMDB3LrEauN1fl8s:b84x3aq) ([raw file](https://github.com/pmem/rpma/blob/5049765fc03b536821340aa77c6e20b8e27fa316/tools/perf/BENCHMARKING.md#L9)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done, I also think that this sentence is more correct in eng
</blockquote></details>

Yes, I agree, except for `in your system` - please leave it as it was before.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1344)* status: all files reviewed, 6 unresolved discussions (waiting on @haichangsi and @janekmi)

___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/pmem/rpma/1344#-MpIbJ8IAr5ujsAy6LRg):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> New commits in r1 on 11/24/2021 at 10:46 AM:
> - 5049765: common: perf: introduce report_figures.py compare mode
> 
> New commits in r2 on 11/24/2021 at 5:02 PM:
> - e6f8da1: tools: make old bash test framework the second option
> ```
</details>


Please squash those two commits into one with the correct title (`tools: make old bash test framework the second option`).

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1344)* status: all files reviewed, 6 unresolved discussions (waiting on @haichangsi and @janekmi)

___
*[tools/perf/BENCHMARKING.md, line 9 at r1](https://reviewable.io/reviews/pmem/rpma/1344#-MpGiwgx8K09LiGJ3gQO:-MpIcoFq96UnR3VzgaG9:b-xybsfb) ([raw file](https://github.com/pmem/rpma/blob/5049765fc03b536821340aa77c6e20b8e27fa316/tools/perf/BENCHMARKING.md#L9)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, I agree, except for `in your system` - please leave it as it was before.
</blockquote></details>

I meant it should be "`in your system`"

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1344#-:-MpMRTBZEerE69c1kBfU:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1344#-:-MpMVMD_5hdLLITjZwms:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1344)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1344#-MpIZNfWBjk9sHUgmCya:-MpMWFQC8I3QTY3LEy2H:bb6un1j) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please squash those two commits into one with the correct title:



</blockquote></details>

Done

---
___
*[-- commits, line 5 at r2](https://reviewable.io/reviews/pmem/rpma/1344#-MpIbJ8IAr5ujsAy6LRg):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> New commits in r1 on 11/24/2021 at 10:46 AM:
> - 5049765: common: perf: introduce report_figures.py compare mode
> 
> New commits in r2 on 11/24/2021 at 5:02 PM:
> - e6f8da1: tools: make old bash test framework the second option
> ```

Please squash those two commits into one with the correct title (`tools: make old bash test framework the second option`).
</blockquote></details>

Done
___
*[tools/perf/BENCHMARKING.md, line 9 at r1](https://reviewable.io/reviews/pmem/rpma/1344#-MpGiwgx8K09LiGJ3gQO:-MpMWKLWDihCFe2LWSI0:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/5049765fc03b536821340aa77c6e20b8e27fa316/tools/perf/BENCHMARKING.md#L9)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I meant it should be "`in your system`"
</blockquote></details>

Done

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1344#-:-MpMWVDq3Q9k84VQTnGM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by osalyk — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1344)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
