### PR TITLE
 test: add rpma_mr_reg multithreaded test

### PR DESCRIPTION
**Pull request by ewanglong**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1033)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1033)* status: all files reviewed, 10 unresolved discussions (waiting on @ewanglong)

___
*[tests/cmake/ctest_helpers.cmake, line 235 at r1](https://reviewable.io/reviews/pmem/rpma/1033#-MZMMkQl-ZMRaDkUbkse:-MZMMkQl-ZMRaDkUbksf:b-9f89g4) ([raw file](https://github.com/pmem/rpma/blob/ab7586d96e2a1694d38095e0a7bbc59e7da58b67/tests/cmake/ctest_helpers.cmake#L235)):*
> ```CMake
> 
> 	prepend(srcs ${CMAKE_CURRENT_SOURCE_DIR} ${srcs})
> 	add_executable(${target} ${TEST_MT_COMMON_DIR}/mtt.c ${EXAMPLES_COMMON_DIR}/common-conn.c
> ```

We do not need this. I think we will tailor something better fitted to MT-tests needs.
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 12 at r1](https://reviewable.io/reviews/pmem/rpma/1033#-MZMN8Y6EbHpfmrXLEK6:-MZMN8Y6EbHpfmrXLEK7:b-s3hmk9) ([raw file](https://github.com/pmem/rpma/blob/ab7586d96e2a1694d38095e0a7bbc59e7da58b67/tests/multithreaded/mr/rpma_mr_reg.c#L12)):*
> ```C
> 
> #include "mtt.h"
> #include "common-conn.h"
> ```

Not needed.
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 14 at r1](https://reviewable.io/reviews/pmem/rpma/1033#-MZMN6O10Q9ecoZe8W68:-MZMN6O10Q9ecoZe8W69:b-fmbqsv) ([raw file](https://github.com/pmem/rpma/blob/ab7586d96e2a1694d38095e0a7bbc59e7da58b67/tests/multithreaded/mr/rpma_mr_reg.c#L14)):*
> ```C
> #include "common-conn.h"
> 
> #define HELLO_STR "Hello client!"
> ```

#define KILOBYTE 1024
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 57 at r1](https://reviewable.io/reviews/pmem/rpma/1033#-MZML0Ee7FQm8yMRC4c6:-MZML0Ee7FQm8yMRC4c7:b8kzxn6) ([raw file](https://github.com/pmem/rpma/blob/ab7586d96e2a1694d38095e0a7bbc59e7da58b67/tests/multithreaded/mr/rpma_mr_reg.c#L57)):*
> ```C
> 		rpma_peer_delete(&pr->peer);
> 		return;
> 	}
> ```

You don't need an endpoint to do memory registration.
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 73 at r1](https://reviewable.io/reviews/pmem/rpma/1033#-MZMLDwW0u7hYhdO6G8z:-MZMLDwW0u7hYhdO6G9-:b-2zqckd) ([raw file](https://github.com/pmem/rpma/blob/ab7586d96e2a1694d38095e0a7bbc59e7da58b67/tests/multithreaded/mr/rpma_mr_reg.c#L73)):*
> ```C
> 	}
> 
> 	st->mr_size = strlen(HELLO_STR) + 1;
> ```

You can use just a `KILOBYTE`. No need to go so specific.
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 101 at r1](https://reviewable.io/reviews/pmem/rpma/1033#-MZMLR0DEcnWZahY1zBb:-MZMLR0DEcnWZahY1zBc:bhiyujx) ([raw file](https://github.com/pmem/rpma/blob/ab7586d96e2a1694d38095e0a7bbc59e7da58b67/tests/multithreaded/mr/rpma_mr_reg.c#L101)):*
> ```C
> 		MTT_RPMA_ERR(result, "rpma_mr_reg", ret);
> 		free(st->mr_ptr);
> 		st->mr_ptr = NULL;
> ```

You do not need to do cleanup here.
All fini steps should be triggered anyways.
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 114 at r1](https://reviewable.io/reviews/pmem/rpma/1033#-MZMM47sDM_nXyKIe4ox:-MZMM47sDM_nXyKIe4oy:b-hfx61t) ([raw file](https://github.com/pmem/rpma/blob/ab7586d96e2a1694d38095e0a7bbc59e7da58b67/tests/multithreaded/mr/rpma_mr_reg.c#L114)):*
> ```C
> 	struct state *st = (struct state *)*state_ptr;
> 
> 	int ret;
> ```

```c
struct state *st = (struct state *)*state_ptr;
int ret

if (st->mr_ptr) {
```

instead of

```c
struct state *st = (struct state *)*state_ptr;

int ret;
if (st->mr_ptr) {
```
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 115 at r1](https://reviewable.io/reviews/pmem/rpma/1033#-MZMMOc31fslNskpCAS9:-MZMMOc31fslNskpCASA:b-kii9c4) ([raw file](https://github.com/pmem/rpma/blob/ab7586d96e2a1694d38095e0a7bbc59e7da58b67/tests/multithreaded/mr/rpma_mr_reg.c#L115)):*
> ```C
> 
> 	int ret;
> 	if (st->mr_ptr) {
> ```

st->mr
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 120 at r1](https://reviewable.io/reviews/pmem/rpma/1033#-MZMMRCv6-26rbC_d-qV:-MZMMRCv6-26rbC_d-qW:bvewlwr) ([raw file](https://github.com/pmem/rpma/blob/ab7586d96e2a1694d38095e0a7bbc59e7da58b67/tests/multithreaded/mr/rpma_mr_reg.c#L120)):*
> ```C
> 		free(st->mr_ptr);
> 	}
> ```

Freeing `st->mr_ptr` should be done unconditionally.
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 135 at r1](https://reviewable.io/reviews/pmem/rpma/1033#-MZMMaQI2kBEeXnWv1QV:-MZMMaQI2kBEeXnWv1QW:b-s3hmk9) ([raw file](https://github.com/pmem/rpma/blob/ab7586d96e2a1694d38095e0a7bbc59e7da58b67/tests/multithreaded/mr/rpma_mr_reg.c#L135)):*
> ```C
> 
> 	if ((ret = rpma_ep_shutdown(&pr->ep)))
> 		MTT_RPMA_ERR(tr, "rpma_ep_shutdown", ret);
> ```

Not needed.

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1033)* status: 2 of 4 files reviewed, 10 unresolved discussions (waiting on @janekmi)

___
*[tests/cmake/ctest_helpers.cmake, line 235 at r1](https://reviewable.io/reviews/pmem/rpma/1033#-MZMMkQl-ZMRaDkUbkse:-MZM_AhZ7mKxYPVo_DfJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ab7586d96e2a1694d38095e0a7bbc59e7da58b67/tests/cmake/ctest_helpers.cmake#L235)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

We do not need this. I think we will tailor something better fitted to MT-tests needs.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 12 at r1](https://reviewable.io/reviews/pmem/rpma/1033#-MZMN8Y6EbHpfmrXLEK6:-MZM_BnBBlNGyAOX_Cw-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ab7586d96e2a1694d38095e0a7bbc59e7da58b67/tests/multithreaded/mr/rpma_mr_reg.c#L12)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not needed.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 14 at r1](https://reviewable.io/reviews/pmem/rpma/1033#-MZMN6O10Q9ecoZe8W68:-MZM_CK--v4rh2YUZXRd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ab7586d96e2a1694d38095e0a7bbc59e7da58b67/tests/multithreaded/mr/rpma_mr_reg.c#L14)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

#define KILOBYTE 1024
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 57 at r1](https://reviewable.io/reviews/pmem/rpma/1033#-MZML0Ee7FQm8yMRC4c6:-MZM_D1CChVeMs3p_XMv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ab7586d96e2a1694d38095e0a7bbc59e7da58b67/tests/multithreaded/mr/rpma_mr_reg.c#L57)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You don't need an endpoint to do memory registration.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 73 at r1](https://reviewable.io/reviews/pmem/rpma/1033#-MZMLDwW0u7hYhdO6G8z:-MZM_DcTCZCHn1asFd--:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ab7586d96e2a1694d38095e0a7bbc59e7da58b67/tests/multithreaded/mr/rpma_mr_reg.c#L73)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You can use just a `KILOBYTE`. No need to go so specific.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 101 at r1](https://reviewable.io/reviews/pmem/rpma/1033#-MZMLR0DEcnWZahY1zBb:-MZM_FxG-WfmZb_IfntB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ab7586d96e2a1694d38095e0a7bbc59e7da58b67/tests/multithreaded/mr/rpma_mr_reg.c#L101)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You do not need to do cleanup here.
All fini steps should be triggered anyways.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 114 at r1](https://reviewable.io/reviews/pmem/rpma/1033#-MZMM47sDM_nXyKIe4ox:-MZM_H0UAzlPiuo1Y76K:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ab7586d96e2a1694d38095e0a7bbc59e7da58b67/tests/multithreaded/mr/rpma_mr_reg.c#L114)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
struct state *st = (struct state *)*state_ptr;
int ret

if (st->mr_ptr) {
```

instead of

```c
struct state *st = (struct state *)*state_ptr;

int ret;
if (st->mr_ptr) {
```
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 115 at r1](https://reviewable.io/reviews/pmem/rpma/1033#-MZMMOc31fslNskpCAS9:-MZM_HcS8QxxqScn7BdM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ab7586d96e2a1694d38095e0a7bbc59e7da58b67/tests/multithreaded/mr/rpma_mr_reg.c#L115)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

st->mr
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 120 at r1](https://reviewable.io/reviews/pmem/rpma/1033#-MZMMRCv6-26rbC_d-qV:-MZM_IEU26hdMV78Y5JU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ab7586d96e2a1694d38095e0a7bbc59e7da58b67/tests/multithreaded/mr/rpma_mr_reg.c#L120)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Freeing `st->mr_ptr` should be done unconditionally.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 135 at r1](https://reviewable.io/reviews/pmem/rpma/1033#-MZMMaQI2kBEeXnWv1QV:-MZM_5jgEAgucICpUL1K:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ab7586d96e2a1694d38095e0a7bbc59e7da58b67/tests/multithreaded/mr/rpma_mr_reg.c#L135)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not needed.
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1033)* status: all files reviewed, 6 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 23 at r2](https://reviewable.io/reviews/pmem/rpma/1033#-MZMtnpc-xIEQ1nsA4UF:-MZMtnpc-xIEQ1nsA4UG:b51d36q) ([raw file](https://github.com/pmem/rpma/blob/0b9f8990d7ed5581447003024f0dcfec16162d87/tests/multithreaded/mr/rpma_mr_reg.c#L23)):*
> ```C
> struct state {
> 	void *mr_ptr;
> 	size_t mr_size;
> ```

I think we can use `KILOBYTE` directly. The intermediate variable is not needed.
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 28 at r2](https://reviewable.io/reviews/pmem/rpma/1033#-MZMubsyAHQFClcHI_Af:-MZMubsyAHQFClcHI_Ag:b-7n6vzu) ([raw file](https://github.com/pmem/rpma/blob/0b9f8990d7ed5581447003024f0dcfec16162d87/tests/multithreaded/mr/rpma_mr_reg.c#L28)):*
> ```C
> 
> /*
>  * prestate_init -- obtain an ibv_context for a remote IP address
> ```

local
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 45 at r2](https://reviewable.io/reviews/pmem/rpma/1033#-MZMuhqD0Z5wfWAOsndy:-MZMuhqD0Z5wfWAOsndz:b-s3hmk9) ([raw file](https://github.com/pmem/rpma/blob/0b9f8990d7ed5581447003024f0dcfec16162d87/tests/multithreaded/mr/rpma_mr_reg.c#L45)):*
> ```C
> 	if ((ret = rpma_peer_new(pr->dev, &pr->peer))) {
> 		MTT_RPMA_ERR(tr, "rpma_peer_new", ret);
> 		return;
> ```

Not needed.
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 50 at r2](https://reviewable.io/reviews/pmem/rpma/1033#-MZMuqYd9HfllLFe0B9v:-MZMuqYd9HfllLFe0B9w:b6e61ml) ([raw file](https://github.com/pmem/rpma/blob/0b9f8990d7ed5581447003024f0dcfec16162d87/tests/multithreaded/mr/rpma_mr_reg.c#L50)):*
> ```C
> 
> /*
>  * init -- allocate state and allocate and fill the memory
> ```

allocate state and memory region
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 63 at r2](https://reviewable.io/reviews/pmem/rpma/1033#-MZMtxYYBToayqh0v2IC:-MZMtxYYBToayqh0v2ID:b-bwgl9o) ([raw file](https://github.com/pmem/rpma/blob/0b9f8990d7ed5581447003024f0dcfec16162d87/tests/multithreaded/mr/rpma_mr_reg.c#L63)):*
> ```C
> 
> 	st->mr_size = KILOBYTE;
> 	st->mr_ptr = calloc(1, st->mr_size);
> ```

Yeah... but we have to do an aligned malloc... Please just copy-paste the function from the examples' common to mtt.c/.h e.g. `mtt_malloc_alligned()`.
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 74 at r2](https://reviewable.io/reviews/pmem/rpma/1033#-MZMv1xyE872Py0EARdl:-MZMv1xyE872Py0EARdm:b277ymm) ([raw file](https://github.com/pmem/rpma/blob/0b9f8990d7ed5581447003024f0dcfec16162d87/tests/multithreaded/mr/rpma_mr_reg.c#L74)):*
> ```C
> 
> /*
>  * thread -- register the memory
> ```

memory region

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1033)* status: 3 of 6 files reviewed, 6 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 23 at r2](https://reviewable.io/reviews/pmem/rpma/1033#-MZMtnpc-xIEQ1nsA4UF:-MZNTd9l4iucHwUCDEKT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0b9f8990d7ed5581447003024f0dcfec16162d87/tests/multithreaded/mr/rpma_mr_reg.c#L23)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we can use `KILOBYTE` directly. The intermediate variable is not needed.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 28 at r2](https://reviewable.io/reviews/pmem/rpma/1033#-MZMubsyAHQFClcHI_Af:-MZNTZs097c4h635af0d:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0b9f8990d7ed5581447003024f0dcfec16162d87/tests/multithreaded/mr/rpma_mr_reg.c#L28)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

local
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 45 at r2](https://reviewable.io/reviews/pmem/rpma/1033#-MZMuhqD0Z5wfWAOsndy:-MZNT_ff5E9v7EwTZnSx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0b9f8990d7ed5581447003024f0dcfec16162d87/tests/multithreaded/mr/rpma_mr_reg.c#L45)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not needed.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 50 at r2](https://reviewable.io/reviews/pmem/rpma/1033#-MZMuqYd9HfllLFe0B9v:-MZNTaVhEakasQyHhHUz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0b9f8990d7ed5581447003024f0dcfec16162d87/tests/multithreaded/mr/rpma_mr_reg.c#L50)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

allocate state and memory region
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 63 at r2](https://reviewable.io/reviews/pmem/rpma/1033#-MZMtxYYBToayqh0v2IC:-MZNTdlc9sTzdc8Rmkfz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0b9f8990d7ed5581447003024f0dcfec16162d87/tests/multithreaded/mr/rpma_mr_reg.c#L63)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Yeah... but we have to do an aligned malloc... Please just copy-paste the function from the examples' common to mtt.c/.h e.g. `mtt_malloc_alligned()`.
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 74 at r2](https://reviewable.io/reviews/pmem/rpma/1033#-MZMv1xyE872Py0EARdl:-MZNTbBP9OeVfn7K1TtW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0b9f8990d7ed5581447003024f0dcfec16162d87/tests/multithreaded/mr/rpma_mr_reg.c#L74)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

memory region
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1033)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong)

___
*[tests/helgrind.supp, line 185 at r3](https://reviewable.io/reviews/pmem/rpma/1033#-MZN_JYk-9NEv3pKC7H6:-MZN_JYk-9NEv3pKC7H7:b-julw0n) ([raw file](https://github.com/pmem/rpma/blob/eebb9b63592713e3413649b1b224a0935032d873/tests/helgrind.supp#L185)):*
> ```
>    ...
> }
> ```

```
#
# Assesment: XXX required
#
# Probably these suppressions do not indicate a lack of MT safety.
#
```
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 63 at r2](https://reviewable.io/reviews/pmem/rpma/1033#-MZMtxYYBToayqh0v2IC:-MZN_WAu5XVArr1vw3qj:b24576u) ([raw file](https://github.com/pmem/rpma/blob/0b9f8990d7ed5581447003024f0dcfec16162d87/tests/multithreaded/mr/rpma_mr_reg.c#L63)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Would you make it a function? :-)

e.g. `mtt_malloc_alligned()`
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 69 at r3](https://reviewable.io/reviews/pmem/rpma/1033#-MZN_fEv-Xy7kBI6eonp:-MZN_fEv-Xy7kBI6eonq:b-sw1xok) ([raw file](https://github.com/pmem/rpma/blob/eebb9b63592713e3413649b1b224a0935032d873/tests/multithreaded/mr/rpma_mr_reg.c#L69)):*
> ```C
> 	}
> 
> 	memset(st->mr_ptr, 0, KILOBYTE);
> ```

Is it required?
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 84 at r3](https://reviewable.io/reviews/pmem/rpma/1033#-MZNa6S80IojExHCYsDQ:-MZNa6S9De0kTZNA5oJD:b-ohryfx) ([raw file](https://github.com/pmem/rpma/blob/eebb9b63592713e3413649b1b224a0935032d873/tests/multithreaded/mr/rpma_mr_reg.c#L84)):*
> ```C
> 
> 	int ret = rpma_mr_reg(pr->peer, st->mr_ptr, KILOBYTE,
> 				RPMA_MR_USAGE_READ_SRC, &st->mr);
> ```

One tab too deep indentation.

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1033)* status: 4 of 8 files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[tests/helgrind.supp, line 185 at r3](https://reviewable.io/reviews/pmem/rpma/1033#-MZN_JYk-9NEv3pKC7H6:-MZNxoO-5V3kTTFntdjR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/eebb9b63592713e3413649b1b224a0935032d873/tests/helgrind.supp#L185)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```
#
# Assesment: XXX required
#
# Probably these suppressions do not indicate a lack of MT safety.
#
```
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 63 at r2](https://reviewable.io/reviews/pmem/rpma/1033#-MZMtxYYBToayqh0v2IC:-MZNxpBY13MqWUv0z4mn:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0b9f8990d7ed5581447003024f0dcfec16162d87/tests/multithreaded/mr/rpma_mr_reg.c#L63)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Would you make it a function? :-)

e.g. `mtt_malloc_alligned()`
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 69 at r3](https://reviewable.io/reviews/pmem/rpma/1033#-MZN_fEv-Xy7kBI6eonp:-MZNxpr-0x5Ihl7tvVbQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/eebb9b63592713e3413649b1b224a0935032d873/tests/multithreaded/mr/rpma_mr_reg.c#L69)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Is it required?
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 84 at r3](https://reviewable.io/reviews/pmem/rpma/1033#-MZNa6S80IojExHCYsDQ:-MZNxqMOCczMmt-ng6-o:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/eebb9b63592713e3413649b1b224a0935032d873/tests/multithreaded/mr/rpma_mr_reg.c#L84)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

One tab too deep indentation.
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1033)* status: all files reviewed, 3 unresolved discussions (waiting on @ewanglong)

___
*[tests/helgrind.supp, line 179 at r4](https://reviewable.io/reviews/pmem/rpma/1033#-MZWjMSkCi56Y0pIXt_L:-MZWjMSkCi56Y0pIXt_M:b-7x7oe) ([raw file](https://github.com/pmem/rpma/blob/81b279a8bf31fd79afe39a2b091fc5a58971eeb5/tests/helgrind.supp#L179)):*
> ```
> #
> # Probably these suppressions do not indicate a lack of MT safety.
> #
> ```

I just have realized this type of comment is way higher. And it is even better since we do not have even an initial assessment of these suppressions so we can not even vaguely state their thread-safety.

Please remove. Sorry.
___
*[tests/multithreaded/common/mtt.c, line 242 at r4](https://reviewable.io/reviews/pmem/rpma/1033#-MZWjxjm9mOoVzD69GmT:-MZWjxjm9mOoVzD69GmU:b-o11lk1) ([raw file](https://github.com/pmem/rpma/blob/81b279a8bf31fd79afe39a2b091fc5a58971eeb5/tests/multithreaded/common/mtt.c#L242)):*
> ```C
>  */
> void *
> mtt_malloc_aligned(size_t size)
> ```

Since this function may be called from the thread we have to accept here a `struct mtt_result *tr` object.
So the error handling will look as follow:

```c
	long pagesize = sysconf(_SC_PAGESIZE);
	if (pagesize < 0) {
		MTT_ERR(tr, "sysconf", errno);
		return NULL;
	}

	/* allocate a page size aligned local memory pool */
	void *mem;
	int ret = posix_memalign(&mem, (size_t)pagesize, size);
	if (ret) {
		MTT_ERR(tr, "posix_memalign", errno);
		return NULL;
	}
```
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 65 at r4](https://reviewable.io/reviews/pmem/rpma/1033#-MZWlKYw-iRnGtstnn17:-MZWlKYw-iRnGtstnn18:b-bsad9j) ([raw file](https://github.com/pmem/rpma/blob/81b279a8bf31fd79afe39a2b091fc5a58971eeb5/tests/multithreaded/mr/rpma_mr_reg.c#L65)):*
> ```C
> 		free(st);
> 		return;
> 	}
> ```

Having implemented the `mtt_malloc_aligned()` error handling as I proposed above here you only need:

```c
	st->mr_ptr = mtt_malloc_aligned(KILOBYTE, tr);
	if (st->mr_ptr == NULL) {
		free(st);
		return;
	}
```

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1033)* status: 4 of 8 files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tests/helgrind.supp, line 179 at r4](https://reviewable.io/reviews/pmem/rpma/1033#-MZWjMSkCi56Y0pIXt_L:-MZWrQqb-gKGydup9az-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/81b279a8bf31fd79afe39a2b091fc5a58971eeb5/tests/helgrind.supp#L179)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I just have realized this type of comment is way higher. And it is even better since we do not have even an initial assessment of these suppressions so we can not even vaguely state their thread-safety.

Please remove. Sorry.
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mtt.c, line 242 at r4](https://reviewable.io/reviews/pmem/rpma/1033#-MZWjxjm9mOoVzD69GmT:-MZWrRYH-weIXEYepB3r:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/81b279a8bf31fd79afe39a2b091fc5a58971eeb5/tests/multithreaded/common/mtt.c#L242)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Since this function may be called from the thread we have to accept here a `struct mtt_result *tr` object.
So the error handling will look as follow:

```c
	long pagesize = sysconf(_SC_PAGESIZE);
	if (pagesize < 0) {
		MTT_ERR(tr, "sysconf", errno);
		return NULL;
	}

	/* allocate a page size aligned local memory pool */
	void *mem;
	int ret = posix_memalign(&mem, (size_t)pagesize, size);
	if (ret) {
		MTT_ERR(tr, "posix_memalign", errno);
		return NULL;
	}
```
</blockquote></details>

Done.
___
*[tests/multithreaded/mr/rpma_mr_reg.c, line 65 at r4](https://reviewable.io/reviews/pmem/rpma/1033#-MZWlKYw-iRnGtstnn17:-MZWrS5VAsYpAiyMqy4e:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/81b279a8bf31fd79afe39a2b091fc5a58971eeb5/tests/multithreaded/mr/rpma_mr_reg.c#L65)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Having implemented the `mtt_malloc_aligned()` error handling as I proposed above here you only need:

```c
	st->mr_ptr = mtt_malloc_aligned(KILOBYTE, tr);
	if (st->mr_ptr == NULL) {
		free(st);
		return;
	}
```
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1033#-:-MZXOfyh8lsJgXJixjqi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1033)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1033#-MZXQZzyAi7l5lvG228Q:-MZXQZzyAi7l5lvG228R:b-8cioiv) (no related file):*
Please rebase.

---

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1033)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1033#-MZXQZzyAi7l5lvG228Q:-MZYOO_kE67vQnc_pa6u:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please rebase.
</blockquote></details>

Done.

---

**Review by janekmi — APPROVED** [review]
> Reviewed 3 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1033)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Pull request merged**
