### PR TITLE
examples: explain <pmem-path> in PMEM_USAGE

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1509)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
:goat:

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1509#-:-Mtx3F15Bq3UR_a945K1:bnd2vnu)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1509#-Mtx3GbT1SmW2pjm6SoG:-Mtx3GbU3KDhGXsTVX_d:bhnn8di) (no related file):*
Do we have any test to verify that this works as expected?

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1509)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1509#-Mtx3GbT1SmW2pjm6SoG:-Mtx4d5mB2uDpC5ueNpP:b-73n2rm) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Do we have any test to verify that this works as expected?
</blockquote></details>

Only manual. 
We do not have any tests for examples. 
How do you want to test messages printed by examples? 

---

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1509)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
```
$ ./examples/03-read-to-persistent/client
usage: ./examples/03-read-to-persistent/client <server_address> <port> [<pmem-path>]
where <pmem-path> can be:
  - a Device DAX (/dev/dax0.0 for example) or
  - a file on File System DAX (/mnt/pmem/file for example)
$ ./examples/03-read-to-persistent/server 
usage: ./examples/03-read-to-persistent/server <server_address> <port> [<pmem-path>]
where <pmem-path> can be:
  - a Device DAX (/dev/dax0.0 for example) or
  - a file on File System DAX (/mnt/pmem/file for example)
$ ./examples/04-write-to-persistent/client 
usage: ./examples/04-write-to-persistent/client <server_address> <port> [<pmem-path>]
where <pmem-path> can be:
  - a Device DAX (/dev/dax0.0 for example) or
  - a file on File System DAX (/mnt/pmem/file for example)
$ ./examples/04-write-to-persistent/server 
usage: ./examples/04-write-to-persistent/server <server_address> <port> [<pmem-path>]
where <pmem-path> can be:
  - a Device DAX (/dev/dax0.0 for example) or
  - a file on File System DAX (/mnt/pmem/file for example)
$ ./examples/05-flush-to-persistent/client 
usage: ./examples/05-flush-to-persistent/client <server_address> <port> [<pmem-path>]
where <pmem-path> can be:
  - a Device DAX (/dev/dax0.0 for example) or
  - a file on File System DAX (/mnt/pmem/file for example)
$ ./examples/05-flush-to-persistent/server 
usage: ./examples/05-flush-to-persistent/server <server_address> <port> [<pmem-path>] [direct-pmem-write]
where <pmem-path> can be:
  - a Device DAX (/dev/dax0.0 for example) or
  - a file on File System DAX (/mnt/pmem/file for example)
$ ./examples/07-atomic-write/server 
usage: ./examples/07-atomic-write/server <server_address> <port> [<pmem-path>]
where <pmem-path> can be:
  - a Device DAX (/dev/dax0.0 for example) or
  - a file on File System DAX (/mnt/pmem/file for example)
$ ./examples/09-flush-to-persistent-GPSPM/client  
usage: ./examples/09-flush-to-persistent-GPSPM/client <server_address> <port> [<pmem-path>]
where <pmem-path> can be:
  - a Device DAX (/dev/dax0.0 for example) or
  - a file on File System DAX (/mnt/pmem/file for example)
$ ./examples/09-flush-to-persistent-GPSPM/server
usage: ./examples/09-flush-to-persistent-GPSPM/server <server_address> <port> [<pmem-path>]
where <pmem-path> can be:
  - a Device DAX (/dev/dax0.0 for example) or
  - a file on File System DAX (/mnt/pmem/file for example)
```

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1509#-:-Mtx7R3b235njumfGcIh:b-ip52cm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1509#-:-Mtx841K42GB_ASvc4a7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 15 of 15 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1509#-:-Mu9n5KeAYVEtHrVfNvn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1509#-:-MuAGtZr5hD7tVHaUXyB:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1509)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
