### PR TITLE
common: version number to include patch version always

### PR DESCRIPTION
**Pull request by grom72**
This is a proposal.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/514)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/514)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[CMakeLists.txt, line 23 at r1](https://reviewable.io/reviews/pmem/rpma/514#-MIV_eH45DoBVZsXK5Ge:-MIV_eH45DoBVZsXK5Gf:b-rsftih) ([raw file](https://github.com/pmem/rpma/blob/329ae4b3bc81e175eecf5a6fab6fca2063a6ff10/CMakeLists.txt#L23)):*
> ```CMake
> if (VERSION_PATCH GREATER 0)
> 	set(VERSION ${VERSION}.${VERSION_PATCH})
> endif()
> ```

The question is: 

Do we want to have release 1.0.0 or 1.0 ?

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/514)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[CMakeLists.txt, line 23 at r1](https://reviewable.io/reviews/pmem/rpma/514#-MIV_eH45DoBVZsXK5Ge:-MIVeqpr9N_r8uKirXp4:b-xcvpge) ([raw file](https://github.com/pmem/rpma/blob/329ae4b3bc81e175eecf5a6fab6fca2063a6ff10/CMakeLists.txt#L23)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The question is: 

Do we want to have release 1.0.0 or 1.0 ? 
</blockquote></details>

the question is not about 1.0.0 vs 1.0 but about 1.0 evolving to 1.0.1 or 0.9 evolving to 0.9.1 when we do some minor fixes not related to API

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/514)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/514#-:-MIVmMUp9-xCUbJKEyys:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/514#-:-MIXd2mS07yRA-Iq0BBp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/514)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/514#-:-MIYCymI84gPcELsVyz6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[CMakeLists.txt, line 23 at r1](https://reviewable.io/reviews/pmem/rpma/514#-MIV_eH45DoBVZsXK5Ge:-MIYCk6_AvLg9gDu46gF:bwhtpqq) ([raw file](https://github.com/pmem/rpma/blob/329ae4b3bc81e175eecf5a6fab6fca2063a6ff10/CMakeLists.txt#L23)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

the question is not about 1.0.0 vs 1.0 but about 1.0 evolving to 1.0.1 or 0.9 evolving to 0.9.1 when we do some minor fixes not related to API
</blockquote></details>

This is why I like so much the proposed versioning standard. Somebody has already thought about it. ;-)

**Pull request merged**
