### PR TITLE
common: log_default unit tests

### PR DESCRIPTION
**Pull request by janekmi**
Greatly inspired by #157. Thank you @grom72.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/248)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/248)* status: 3 of 10 files reviewed, 19 unresolved discussions (waiting on @grom72, @janekmi, @ldorau, and @osalyk)

___
*[tests/unit/common/mocks-rpma-log.c, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/248#-MEvvrT8DRKsPKLLdu3V:-MF1gzO-0PcoXvbzNgIc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/695b30979b7057e1719ea5e6e0bd6cd355761480/tests/unit/common/mocks-rpma-log.c#L13)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> RPMA_LOG_THRESHOLD_PRIMARY_DEFAULT,
> 		RPMA_LOG_THRESHOLD_SECONDARY_DEFAULT
> ```
do we execute tests with debug or nondebug?
RPMA_LOG_THRESHOLD_PRIMARY_DEFAULT is interpreted differently so shall we either skip this #define or force also to execute tests with non-debug
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-stdio.c, line 21 at r1](https://reviewable.io/reviews/pmem/rpma/248#-MEvwiJdCIlGoSonyM2W:-MF1h6Ks5IonvA9IcacE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/695b30979b7057e1719ea5e6e0bd6cd355761480/tests/unit/common/mocks-stdio.c#L21)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> if (ret)
> ```
if(ret < 0) 
we should not allow forcing proper ret value but wrong execution results
this part of mock is to force error behavior so negative return code shall be used
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-stdio.c, line 27 at r1](https://reviewable.io/reviews/pmem/rpma/248#-MEvu0Ko6xF_HUJ5I-G2:-MF1o5c4CKOc3WnTxGIF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/695b30979b7057e1719ea5e6e0bd6cd355761480/tests/unit/common/mocks-stdio.c#L27)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> 0
> ```
ret
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-stdio.c, line 37 at r1](https://reviewable.io/reviews/pmem/rpma/248#-MEvx2Bt1_E1rVQjnwoe:-MF1hCfl2D1PGwdxKYDZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/695b30979b7057e1719ea5e6e0bd6cd355761480/tests/unit/common/mocks-stdio.c#L37)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> if (ret)
> ```
if (ret < 0)
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-stdio.c, line 46 at r1](https://reviewable.io/reviews/pmem/rpma/248#-MEvu4pn2dD_eUvz437I:-MF1hFUNBoaf_OYmHaUM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/695b30979b7057e1719ea5e6e0bd6cd355761480/tests/unit/common/mocks-stdio.c#L46)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> 0
> ```
.
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-stdio.c, line 71 at r1](https://reviewable.io/reviews/pmem/rpma/248#-MEvxdl7-QaMwcpXlwPm:-MF1hxlR-ogFlk1JirFi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/695b30979b7057e1719ea5e6e0bd6cd355761480/tests/unit/common/mocks-stdio.c#L71)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> cmd == MOCK_VALIDATE
> ```
what is the third case?
MOCK_IGNORE_RESULTS? - this shall be at least documented that e.g. **0** is used to skip validation


</blockquote></details>

Done.
___
*[tests/unit/common/mocks-stdio.c, line 72 at r1](https://reviewable.io/reviews/pmem/rpma/248#-MEvu86wEtb3DZa8NWa3:-MF1hyKBC-EAz_nb9U-N:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/695b30979b7057e1719ea5e6e0bd6cd355761480/tests/unit/common/mocks-stdio.c#L72)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> 0
> ```
.
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-syslog.c, line 38 at r1](https://reviewable.io/reviews/pmem/rpma/248#-MEvyVfX89n7ymWps8Wt:-MF1i7RNEnEYWJP7f9F8:b4qktdr) ([raw file](https://github.com/pmem/rpma/blob/695b30979b7057e1719ea5e6e0bd6cd355761480/tests/unit/common/mocks-syslog.c#L38)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> syslog(int priority, const char *format, ...)
> ```
syslog(int __pri, const char *__fmt, ...) was taken from official include file

</blockquote></details>

Yeah... this version was taken from the official manual page. I have no idea which has higher precedence. xD Please leave it as is, to reduce the effort needed.
___
*[tests/unit/common/mocks-syslog.c, line 44 at r1](https://reviewable.io/reviews/pmem/rpma/248#-MEvyHgHAubcdOT7utQb:-MF1idmK84aQgCG1YPy-:bk1fahj) ([raw file](https://github.com/pmem/rpma/blob/695b30979b7057e1719ea5e6e0bd6cd355761480/tests/unit/common/mocks-syslog.c#L44)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> __real_vsnprintf(syslog_output, MOCK_BUFF_LEN, format, ap);
> 	assert_true(ret > 0);
> ```
why not vsnprintf directly (+ mock_setup)?
perhaps this is the reason why we should test separately stderr and syslog
</blockquote></details>

As we have discussed offline: I think there is not a good solution. I prefer to force mocking vsnprintf along with syslog just to avoid calling a mocked implementation by accident. Just because it is easier to catch the issue.
___
*[tests/unit/common/mocks-syslog.c, line 52 at r1](https://reviewable.io/reviews/pmem/rpma/248#-MEvyi-V-a07O62M9j7e:-MF1jGD38tK5Ah1K2BDD:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/695b30979b7057e1719ea5e6e0bd6cd355761480/tests/unit/common/mocks-syslog.c#L52)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> MOCK_VALIDATE
> ```
. -MOCK_SKIP_VALIDATION shall be at least documented
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-time.c, line 54 at r1](https://reviewable.io/reviews/pmem/rpma/248#-MEvz8ssCF6pmbvbur8Y:-MF1kpaC8RcjFVuOb2JJ:bqjy5rv) ([raw file](https://github.com/pmem/rpma/blob/695b30979b7057e1719ea5e6e0bd6cd355761480/tests/unit/common/mocks-time.c#L54)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

	/* check that format string is not empty */
	assert_int_not_equal(*__format, '\0');
</blockquote></details>

Done. Now I am using the __real_ implementation so all possible checks are done during the final output validation.
___
*[tests/unit/common/mocks-time.c, line 58 at r1](https://reviewable.io/reviews/pmem/rpma/248#-MEvzUyR7mScu6L9blHP:-MF1wANR9zhEntOhmqH5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/695b30979b7057e1719ea5e6e0bd6cd355761480/tests/unit/common/mocks-time.c#L58)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

	/* check expected input time */
	struct tm *tp = mock_type(struct tm *);
	assert_memory_equal(__tp, tp, sizeof(struct tm));

	/* check enough space in result buffer */
	assert_in_range(__maxsize, strlen(s) + 1, 1024);
</blockquote></details>

Done.
___
*[tests/unit/log_default/function.c, line 5 at r1](https://reviewable.io/reviews/pmem/rpma/248#-MEw-E0e1Jd4gBYW77d5:-MF1lCpd-xsasHnNAS3v:b4zgb5m) ([raw file](https://github.com/pmem/rpma/blob/695b30979b7057e1719ea5e6e0bd6cd355761480/tests/unit/log_default/function.c#L5)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> function.c
> ```
default_function.c
</blockquote></details>

I do not like this name either. But it is correct according to our rules. I prefer to apply them consistently.
___
*[tests/unit/log_default/function.c, line 91 at r1](https://reviewable.io/reviews/pmem/rpma/248#-MEw-Yig5fKkT-ohHaet:-MF1lVxzEzGhmLyLDYpk:bmzx0sn) ([raw file](https://github.com/pmem/rpma/blob/695b30979b7057e1719ea5e6e0bd6cd355761480/tests/unit/log_default/function.c#L91)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Rpma_log_threshold[RPMA_LOG_THRESHOLD_PRIMARY] = RPMA_LOG_DISABLED;
> ```
#define RPMA_LOG(level, format, ...) \
	if (level <= **Rpma_log_threshold[RPMA_LOG_THRESHOLD_PRIMARY]** && \
			NULL != Rpma_log_function) { \
		Rpma_log_function(level, __FILE__, __LINE__, __func__, \
				format, ##__VA_ARGS__); \
magic is here
</blockquote></details>

This is tested in the log/macros.c unit tests. No need to do it again. This is a part of the log module (not the log_default module). I know this division is not ideal.  We will get used to it or we will come up with a better idea.
___
*[tests/unit/log_default/function.c, line 108 at r1](https://reviewable.io/reviews/pmem/rpma/248#-MEw1JKC3cQ8F8ElGwAz:-MF1mn57DY0PRZ2RzOZO:bdbkr0l) ([raw file](https://github.com/pmem/rpma/blob/695b30979b7057e1719ea5e6e0bd6cd355761480/tests/unit/log_default/function.c#L108)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> rpma_log_default_function
> ```
do we have tests that verify proper mapping of macros RPMA_LOG and similar to proper calls of Rpma_log_function?
</blockquote></details>

Yes. This is done in the log/macros.c unit test.
___
*[tests/unit/log_default/function.c, line 304 at r1](https://reviewable.io/reviews/pmem/rpma/248#-MEw0TWm1ydJ0e7sipLZ:-MF1nFOyBFaG1I9sfe87:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/695b30979b7057e1719ea5e6e0bd6cd355761480/tests/unit/log_default/function.c#L304)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> MOCK_PASSTHROUGH
> ```
not mentioned in syslog mock documentation
</blockquote></details>

Done.
___
*[tests/unit/log_default/init-fini.c, line 25 at r1](https://reviewable.io/reviews/pmem/rpma/248#-MF-3jEu4HcqsF-uVQRA:-MF1nMYQD26EMS9laYIN:bqe3jrw) ([raw file](https://github.com/pmem/rpma/blob/695b30979b7057e1719ea5e6e0bd6cd355761480/tests/unit/log_default/init-fini.c#L25)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> rpma_log_default_init();
> ```
shall we use rpma_log_init here and check that rpma_log_default_function is setup?
(assert_ptr_equal(Rpma_log_function, rpma_log_default_function); )
or combine this test with log init-fini as we know that normal init touch also syslog?

</blockquote></details>

I understand the division of log and log_default modules may seem like an architectural sugar. I know there is a lot you can simplify by breaking the separation of modules but I guess it is true almost always when you introduce a separation of modules. We will see how this division will work out for us.
___
*[tests/unit/log_default/init-fini.c, line 38 at r1](https://reviewable.io/reviews/pmem/rpma/248#-MEw1ll567IZnoYJVfcO:-MF1nwuB4RIUlHuCBO6I:bq9s22b) ([raw file](https://github.com/pmem/rpma/blob/695b30979b7057e1719ea5e6e0bd6cd355761480/tests/unit/log_default/init-fini.c#L38)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> rpma_log_default_fini
> ```
inline function?
</blockquote></details>

It is called only once during the whole life of the library. No point.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/248)* status: 3 of 10 files reviewed, 19 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[tests/unit/log_default/function.c, line 190 at r1](https://reviewable.io/reviews/pmem/rpma/248#-MEw01ma9u0jMT7XHNyx:-MF20Add4eQiTgAS0ePg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/695b30979b7057e1719ea5e6e0bd6cd355761480/tests/unit/log_default/function.c#L190)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> function__syslog_relative_path
> ```
almost the same - can we have a parameter what name is used?
and call the same test two times with short and long path?? 
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 9 files at r1, 7 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/248)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/248#-:-MF4A56p1yz6MxRmlWaR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
:rocket: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/248#-:-MF4V-JrA4BHn79nTx1x:biyjirz)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 9 files at r1, 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/248)* status: all files reviewed, 7 unresolved discussions (waiting on @janekmi)

___
*[tests/unit/common/mocks-rpma-log.c, line 14 at r2](https://reviewable.io/reviews/pmem/rpma/248#-MF4m4RmAE66WH70khyF:-MF4m4RmAE66WH70khyG:b-o60i1b) ([raw file](https://github.com/pmem/rpma/blob/cd49aad1338a632bc8192e43f5e90fafcaf1e77a/tests/unit/common/mocks-rpma-log.c#L14)):*
> ```
> RPMA_LOG_DISABLED, /* RPMA_LOG_THRESHOLD */
> 		RPMA_LOG_DISABLED /* RPMA_LOG_THRESHOLD_AUX */
> ```

(picky) please make comments aligned (a tab instead of a space before them)
___
*[tests/unit/common/mocks-stdio.h, line 16 at r2](https://reviewable.io/reviews/pmem/rpma/248#-MF4mJEGBi5ixLRoXrOF:-MF4mJEHE7tMzy5nsaDI:b-nsqcu9) ([raw file](https://github.com/pmem/rpma/blob/cd49aad1338a632bc8192e43f5e90fafcaf1e77a/tests/unit/common/mocks-stdio.h#L16)):*
> ```objc
> 
> #define MOCK_BUFF_LEN		1024
> ```

redundant empty line
___
*[tests/unit/common/mocks-stdio.h, line 20 at r2](https://reviewable.io/reviews/pmem/rpma/248#-MF4mNmAC6tIdYR3hNCK:-MF4mNmAC6tIdYR3hNCL:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/cd49aad1338a632bc8192e43f5e90fafcaf1e77a/tests/unit/common/mocks-stdio.h#L20)):*
> ```objc
> 
> int __wrap_vsnprintf(char *str, size_t size, const char *format, va_list ap);
> ```

.
___
*[tests/unit/common/mocks-stdio.h, line 22 at r2](https://reviewable.io/reviews/pmem/rpma/248#-MF4mOo01u2Jrx0JXaLu:-MF4mOo1AR0evvBXUll6:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/cd49aad1338a632bc8192e43f5e90fafcaf1e77a/tests/unit/common/mocks-stdio.h#L22)):*
> ```objc
> 
> int __wrap_snprintf(char *str, size_t size, const char *format, ...);
> ```

.
___
*[tests/unit/common/mocks-stdio.h, line 24 at r2](https://reviewable.io/reviews/pmem/rpma/248#-MF4mPRY7NKY57luy32o:-MF4mPRZBevqXOJbo_UU:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/cd49aad1338a632bc8192e43f5e90fafcaf1e77a/tests/unit/common/mocks-stdio.h#L24)):*
> ```objc
> 
> int __wrap_fprintf(FILE *stream, const char *format, ...);
> ```

.
___
*[tests/unit/common/mocks-stdio.c, line 42 at r2](https://reviewable.io/reviews/pmem/rpma/248#-MF4nHig3PX9vH509oDA:-MF4nHig3PX9vH509oDB:blovwys) ([raw file](https://github.com/pmem/rpma/blob/cd49aad1338a632bc8192e43f5e90fafcaf1e77a/tests/unit/common/mocks-stdio.c#L42)):*
> ```
> __real_vsnprintf
> ```

__real_snprintf ?
___
*[tests/unit/common/mocks-stdio.c, line 61 at r2](https://reviewable.io/reviews/pmem/rpma/248#-MF4nT1aBFvl8_ux3WV8:-MF4nT1aBFvl8_ux3WV9:b-6rrh5f) ([raw file](https://github.com/pmem/rpma/blob/cd49aad1338a632bc8192e43f5e90fafcaf1e77a/tests/unit/common/mocks-stdio.c#L61)):*
> ```
> __real_vsnprintf
> ```

__real_fprintf ?

**Review by ldorau — COMMENTED** [review]
> Reviewed 5 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/248)* status: all files reviewed, 13 unresolved discussions (waiting on @janekmi)

___
*[tests/unit/common/mocks-rpma-log.c, line 4 at r2](https://reviewable.io/reviews/pmem/rpma/248#-MF4oSq98XfRuV5MmstH:-MF4oSq98XfRuV5MmstI:bijyr2z) ([raw file](https://github.com/pmem/rpma/blob/cd49aad1338a632bc8192e43f5e90fafcaf1e77a/tests/unit/common/mocks-rpma-log.c#L4)):*
<details><summary><i alt="summary">Quoted 4 lines of code…</i></summary>

> ```
> /*
>  * SPDX-License-Identifier: BSD-3-Clause
>  * Copyright 2020, Intel Corporation
>  */
> ```
</details>


```
// SPDX-License-Identifier: BSD-3-Clause
/* Copyright 2020, Intel Corporation */
```
___
*[tests/unit/common/mocks-stdio.h, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/248#-MF4oc2Y14YWVukQ1ZHr:-MF4oc2Y14YWVukQ1ZHs:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/cd49aad1338a632bc8192e43f5e90fafcaf1e77a/tests/unit/common/mocks-stdio.h#L2)):*
> ```objc
> /*
>  * SPDX-License-Identifier: BSD-3-Clause
> ```

.
___
*[tests/unit/common/mocks-stdio.c, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/248#-MF4oeIM8NPhfTmhyAc5:-MF4oeIM8NPhfTmhyAc6:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/cd49aad1338a632bc8192e43f5e90fafcaf1e77a/tests/unit/common/mocks-stdio.c#L2)):*
> ```C
> /*
>  * SPDX-License-Identifier: BSD-3-Clause
> ```

.
___
*[tests/unit/common/mocks-syslog.c, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/248#-MF4ogh55dqVuViszB2h:-MF4ogh55dqVuViszB2i:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/cd49aad1338a632bc8192e43f5e90fafcaf1e77a/tests/unit/common/mocks-syslog.c#L2)):*
> ```C
> /*
>  * SPDX-License-Identifier: BSD-3-Clause
> ```

.
___
*[tests/unit/common/mocks-time.c, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/248#-MF4opwfAOmELkkud6We:-MF4opwfAOmELkkud6Wf:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/cd49aad1338a632bc8192e43f5e90fafcaf1e77a/tests/unit/common/mocks-time.c#L2)):*
> ```C
> /*
>  * SPDX-License-Identifier: BSD-3-Clause
> ```

.
___
*[tests/unit/log_default/function.c, line 18 at r2](https://reviewable.io/reviews/pmem/rpma/248#-MF4pDYr-bMCtohz5Dlb:-MF4pDYr-bMCtohz5Dlc:b-tvmwkg) ([raw file](https://github.com/pmem/rpma/blob/cd49aad1338a632bc8192e43f5e90fafcaf1e77a/tests/unit/log_default/function.c#L18)):*
> ```
> in the order
> ```

in the following order

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 9 files at r1, 1 of 7 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/248)* status: all files reviewed, 13 unresolved discussions (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/248)* status: 4 of 10 files reviewed, 13 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[tests/unit/common/mocks-rpma-log.c, line 4 at r2](https://reviewable.io/reviews/pmem/rpma/248#-MF4oSq98XfRuV5MmstH:-MF5Levz3ouJkcvTp91r:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cd49aad1338a632bc8192e43f5e90fafcaf1e77a/tests/unit/common/mocks-rpma-log.c#L4)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> /*
>  * SPDX-License-Identifier: BSD-3-Clause
>  * Copyright 2020, Intel Corporation
>  */
> ```

```
// SPDX-License-Identifier: BSD-3-Clause
/* Copyright 2020, Intel Corporation */
```
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-rpma-log.c, line 14 at r2](https://reviewable.io/reviews/pmem/rpma/248#-MF4m4RmAE66WH70khyF:-MF5LlSI49tAsOzqGyag:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cd49aad1338a632bc8192e43f5e90fafcaf1e77a/tests/unit/common/mocks-rpma-log.c#L14)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> RPMA_LOG_DISABLED, /* RPMA_LOG_THRESHOLD */
> 		RPMA_LOG_DISABLED /* RPMA_LOG_THRESHOLD_AUX */
> ```

(picky) please make comments aligned (a tab instead of a space before them)
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-stdio.h, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/248#-MF4oc2Y14YWVukQ1ZHr:-MF5LzUN7q7lFm1HelYc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cd49aad1338a632bc8192e43f5e90fafcaf1e77a/tests/unit/common/mocks-stdio.h#L2)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-stdio.h, line 16 at r2](https://reviewable.io/reviews/pmem/rpma/248#-MF4mJEGBi5ixLRoXrOF:-MF5M5qG5S8OAX6EdPPP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cd49aad1338a632bc8192e43f5e90fafcaf1e77a/tests/unit/common/mocks-stdio.h#L16)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

redundant empty line
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-stdio.h, line 20 at r2](https://reviewable.io/reviews/pmem/rpma/248#-MF4mNmAC6tIdYR3hNCK:-MF5M7Pf7e4aFKR12ydr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cd49aad1338a632bc8192e43f5e90fafcaf1e77a/tests/unit/common/mocks-stdio.h#L20)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-stdio.h, line 22 at r2](https://reviewable.io/reviews/pmem/rpma/248#-MF4mOo01u2Jrx0JXaLu:-MF5M9ak99Ckq4wjgc7K:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cd49aad1338a632bc8192e43f5e90fafcaf1e77a/tests/unit/common/mocks-stdio.h#L22)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-stdio.h, line 24 at r2](https://reviewable.io/reviews/pmem/rpma/248#-MF4mPRY7NKY57luy32o:-MF5MAJJ9leVPjXch2CP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cd49aad1338a632bc8192e43f5e90fafcaf1e77a/tests/unit/common/mocks-stdio.h#L24)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-stdio.c, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/248#-MF4oeIM8NPhfTmhyAc5:-MF5MDFl9CJnpEOZgJdp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cd49aad1338a632bc8192e43f5e90fafcaf1e77a/tests/unit/common/mocks-stdio.c#L2)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-stdio.c, line 42 at r2](https://reviewable.io/reviews/pmem/rpma/248#-MF4nHig3PX9vH509oDA:-MF5MZSY3w-hNYcHytF4:b4argpb) ([raw file](https://github.com/pmem/rpma/blob/cd49aad1338a632bc8192e43f5e90fafcaf1e77a/tests/unit/common/mocks-stdio.c#L42)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> __real_vsnprintf
> ```

__real_snprintf ?
</blockquote></details>

I do not know a way to pass variadic args into snprintf. Am I missing something?
___
*[tests/unit/common/mocks-stdio.c, line 61 at r2](https://reviewable.io/reviews/pmem/rpma/248#-MF4nT1aBFvl8_ux3WV8:-MF5Ml3u0oGDKQkelJvM:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/cd49aad1338a632bc8192e43f5e90fafcaf1e77a/tests/unit/common/mocks-stdio.c#L61)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> __real_vsnprintf
> ```

__real_fprintf ?
</blockquote></details>

.
___
*[tests/unit/common/mocks-syslog.c, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/248#-MF4ogh55dqVuViszB2h:-MF5MqAa5Z2g35DCv_0W:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cd49aad1338a632bc8192e43f5e90fafcaf1e77a/tests/unit/common/mocks-syslog.c#L2)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/common/mocks-time.c, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/248#-MF4opwfAOmELkkud6We:-MF5MscO8_AN1DAm7xrw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cd49aad1338a632bc8192e43f5e90fafcaf1e77a/tests/unit/common/mocks-time.c#L2)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/log_default/function.c, line 18 at r2](https://reviewable.io/reviews/pmem/rpma/248#-MF4pDYr-bMCtohz5Dlb:-MF5N-jvEjx15wchclvX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cd49aad1338a632bc8192e43f5e90fafcaf1e77a/tests/unit/log_default/function.c#L18)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> in the order
> ```

in the following order
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 6 of 6 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/248)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[tests/unit/common/mocks-stdio.c, line 42 at r2](https://reviewable.io/reviews/pmem/rpma/248#-MF4nHig3PX9vH509oDA:-MF5PGO52YJeCISBtNPF:b-panwnd) ([raw file](https://github.com/pmem/rpma/blob/cd49aad1338a632bc8192e43f5e90fafcaf1e77a/tests/unit/common/mocks-stdio.c#L42)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I do not know a way to pass variadic args into snprintf. Am I missing something?
</blockquote></details>

No, it is OK

**Review by ldorau — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/248#-:-MF5PXMpDOqe-JBEkv9Q:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
