### PR TITLE
test: mt: simplify the mtt.h header

### PR DESCRIPTION
**Pull request by janekmi**
Take the mtt_base_file_name defintion to mtt.c.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1018)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1018)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tests/multithreaded/common/mtt.h, line 32 at r1](https://reviewable.io/reviews/pmem/rpma/1018#-MYx2TULAZuRK2CBsnKa:-MYx2TULAZuRK2CBsnKb:bq776k0) ([raw file](https://github.com/pmem/rpma/blob/358f211975655ef378468f215ecd1b7b469b1cba/tests/multithreaded/common/mtt.h#L32)):*
> ```
> ????????
> const char *mtt_base_file_name(const char *file_name);
> ```
Did not we agree that function documentation is located in the header file?

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1018)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1018#-MYxRp6SEV9wdSpvm-db:-MYxRp6SEV9wdSpvm-dc:b-qdjvvp) (no related file):*
What is the rationale for this change?

---

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1018)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1018#-MYxRp6SEV9wdSpvm-db:-MYxYAOCAlJegQFd4a8U:b-eqojql) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

What is the rationale for this change?
</blockquote></details>

1. simplify the mtt.h header
2. having a static function in the header introduces no value and makes the header harder to follow.

---
___
*[tests/multithreaded/common/mtt.h, line 32 at r1](https://reviewable.io/reviews/pmem/rpma/1018#-MYx2TULAZuRK2CBsnKa:-MYxZtV87pWDx3pB4jY6:b-c7vmpr) ([raw file](https://github.com/pmem/rpma/blob/358f211975655ef378468f215ecd1b7b469b1cba/tests/multithreaded/common/mtt.h#L32)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> ????????
> const char *mtt_base_file_name(const char *file_name);
> ```
Did not we agree that function documentation is located in the header file?
</blockquote></details>

Yes. I had run out of ideas. Thank you for motivating me to take another look at this.

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1018)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1018#-MYxRp6SEV9wdSpvm-db:-MYxkell2RKfkZmTukS6:bnqzcsv) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

1. simplify the mtt.h header
2. having a static function in the header introduces no value and makes the header harder to follow.
</blockquote></details>

OK, thx

---

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1018#-:-MYxklEA9XSDQ6sw38_q:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1018)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1018#-:-MYybuKTBJzPDY2hCFlQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1018)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
