### PR TITLE
test: add Conn_no_rcq_with_channel

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #1670

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1671)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1671)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[tests/unit/conn/conn-common.h, line 46 at r1](https://reviewable.io/reviews/pmem/rpma/1671#-N00VQTp7Ti3dKE0JZ7n:-N00VQTp7Ti3dKE0JZ7o:be33j3o) ([raw file](https://github.com/pmem/rpma/blob/49e99a738a8b5b02dc361be6b2366b44f40a3b6d/tests/unit/conn/conn-common.h#L46)):*
> ```objc
> extern struct conn_test_state Conn_no_rcq_with_channel;
> extern struct conn_test_state Conn_with_rcq_no_channel;
> extern struct conn_test_state Conn_with_rcq_and_channel;
> ```

Conn_with_rcq_with_channel



_Code quote:_
```objc
Conn_with_rcq_and_channel
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1671)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tests/unit/conn/conn-common.h, line 46 at r1](https://reviewable.io/reviews/pmem/rpma/1671#-N00VQTp7Ti3dKE0JZ7n:-N00YMtv9xAPs_4RKT0Y:b-izkpme) ([raw file](https://github.com/pmem/rpma/blob/49e99a738a8b5b02dc361be6b2366b44f40a3b6d/tests/unit/conn/conn-common.h#L46)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Conn_with_rcq_with_channel
</blockquote></details>

In a separate PR

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1671)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tests/unit/conn/conn-common.h, line 46 at r1](https://reviewable.io/reviews/pmem/rpma/1671#-N00VQTp7Ti3dKE0JZ7n:-N00ZRfu2Zavi2Zqpz3O:b6npek2) ([raw file](https://github.com/pmem/rpma/blob/49e99a738a8b5b02dc361be6b2366b44f40a3b6d/tests/unit/conn/conn-common.h#L46)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

In a separate PR
</blockquote></details>

https://github.com/pmem/rpma/pull/1672

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 3 files at r2, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1671)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
