### PR TITLE
tools: ib_read.py: implement __client_run

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #1351 

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1346)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1346)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1346)* status: all files reviewed, 5 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 15 at r1](https://reviewable.io/reviews/pmem/rpma/1346#-MpvsoStCESmp7-hnypg:-MpvsoStCESmp7-hnyph:b6ratk6) ([raw file](https://github.com/pmem/rpma/blob/f9086bfbc0c1403baa5248b2eb9b30cce2e41d14/tools/perf/lib/benchmark/runner/ib_read.py#L15)):*
> ```Python
> import sys
> import re
> import subprocess as sub
> ```

I'm not really a fan of this alias. It is used only twice and I haven't seen such an alias for this package.
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 137 at r1](https://reviewable.io/reviews/pmem/rpma/1346#-MpvsgbN1ZKZ6aZD4z51:-MpvsgbN1ZKZ6aZD4z52:bjo1ija) ([raw file](https://github.com/pmem/rpma/blob/f9086bfbc0c1403baa5248b2eb9b30cce2e41d14/tools/perf/lib/benchmark/runner/ib_read.py#L137)):*
> ```Python
>         line = re.sub(r'[ ]*$', '', line)
>         line = re.sub(r'\s+', ' ', line)
>         return line
> ```

These probably should fit into `lib.format.ib_read_lat.py`.
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 156 at r1](https://reviewable.io/reviews/pmem/rpma/1346#-Mpvu8hFDtauOIitDlkO:-Mpvu8hFDtauOIitDlkP:b-mbg6mz) ([raw file](https://github.com/pmem/rpma/blob/f9086bfbc0c1403baa5248b2eb9b30cce2e41d14/tools/perf/lib/benchmark/runner/ib_read.py#L156)):*
> ```Python
>         except sub.CalledProcessError as err:
>             print('\nstdout:\n{}\nstderr:\n{}\n'.format(err.stdout, err.stderr))
>             sys.exit(err.returncode)
> ```

```python
except ValueError as err:
      err.message = err.message + " hello"
      raise # re-raise current exception
```

Ref: https://stackoverflow.com/a/9157277

Using `sys.exit()` in this case looks odd.
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 164 at r1](https://reviewable.io/reviews/pmem/rpma/1346#-Mpvt_6F4zRqzH8cgptI:-Mpvt_6F4zRqzH8cgptJ:bjo1ija) ([raw file](https://github.com/pmem/rpma/blob/f9086bfbc0c1403baa5248b2eb9b30cce2e41d14/tools/perf/lib/benchmark/runner/ib_read.py#L164)):*
> ```Python
>         # grepping and normalization common for both lat and bw modes
>         line = self.grep_output(ret.stdout, str(settings['bs']))
>         nline = self.normalize_line(line)
> ```

These probably should fit into `lib.format.ib_read_lat.py`.
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 167 at r1](https://reviewable.io/reviews/pmem/rpma/1346#-Mpvtg9T4p5PbGH43_rY:-Mpvtg9T4p5PbGH43_rZ:b-97ur55) ([raw file](https://github.com/pmem/rpma/blob/f9086bfbc0c1403baa5248b2eb9b30cce2e41d14/tools/perf/lib/benchmark/runner/ib_read.py#L167)):*
> ```Python
> 
>         formatter = fmt.IbReadLatFormat if self.__mode == 'lat' \
>                                         else fmt.IbReadBwFormat
> ```

:thinking: maybe it should be a part of `__SETTINGS_BS_MODE` definitions?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1346)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 137 at r1](https://reviewable.io/reviews/pmem/rpma/1346#-MpvsgbN1ZKZ6aZD4z51:-MpzGBA_0FllV_EcSvI2:b-31jmse) ([raw file](https://github.com/pmem/rpma/blob/f9086bfbc0c1403baa5248b2eb9b30cce2e41d14/tools/perf/lib/benchmark/runner/ib_read.py#L137)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

These probably should fit into `lib.format.ib_read_lat.py`.
</blockquote></details>

But it is not specific for LAT - it is common for LAT and BW. 
Should we add sth like `format/ib_read_common` ???
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 164 at r1](https://reviewable.io/reviews/pmem/rpma/1346#-Mpvt_6F4zRqzH8cgptI:-MpzG-93A7XbO1PPJr31:b-31jmse) ([raw file](https://github.com/pmem/rpma/blob/f9086bfbc0c1403baa5248b2eb9b30cce2e41d14/tools/perf/lib/benchmark/runner/ib_read.py#L164)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

These probably should fit into `lib.format.ib_read_lat.py`.
</blockquote></details>

But it is not specific for LAT - it is common for LAT and BW. 
Should we add sth like `format/ib_read_common` ???

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1346)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 15 at r1](https://reviewable.io/reviews/pmem/rpma/1346#-MpvsoStCESmp7-hnypg:-MpzKbwJ0yg-Pqss667u:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f9086bfbc0c1403baa5248b2eb9b30cce2e41d14/tools/perf/lib/benchmark/runner/ib_read.py#L15)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I'm not really a fan of this alias. It is used only twice and I haven't seen such an alias for this package.
</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 156 at r1](https://reviewable.io/reviews/pmem/rpma/1346#-Mpvu8hFDtauOIitDlkO:-MpzLgU-5MW-eHgZPFRF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f9086bfbc0c1403baa5248b2eb9b30cce2e41d14/tools/perf/lib/benchmark/runner/ib_read.py#L156)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```python
except ValueError as err:
      err.message = err.message + " hello"
      raise # re-raise current exception
```

Ref: https://stackoverflow.com/a/9157277

Using `sys.exit()` in this case looks odd.
</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 167 at r1](https://reviewable.io/reviews/pmem/rpma/1346#-Mpvtg9T4p5PbGH43_rY:-MpzMftOAoXxXtD6PbIv:b3x845f) ([raw file](https://github.com/pmem/rpma/blob/f9086bfbc0c1403baa5248b2eb9b30cce2e41d14/tools/perf/lib/benchmark/runner/ib_read.py#L167)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

:thinking: maybe it should be a part of `__SETTINGS_BS_MODE` definitions?
</blockquote></details>

Moved to `__init__`

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1346)* status: 0 of 3 files reviewed, 5 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 137 at r1](https://reviewable.io/reviews/pmem/rpma/1346#-MpvsgbN1ZKZ6aZD4z51:-MpzXPOm6O4q0Mnt9hze:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/f9086bfbc0c1403baa5248b2eb9b30cce2e41d14/tools/perf/lib/benchmark/runner/ib_read.py#L137)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

But it is not specific for LAT - it is common for LAT and BW. 
Should we add sth like `format/ib_read_common` ???
</blockquote></details>

Done
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 164 at r1](https://reviewable.io/reviews/pmem/rpma/1346#-Mpvt_6F4zRqzH8cgptI:-MpzXW-I0NiO52N3aig7:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/f9086bfbc0c1403baa5248b2eb9b30cce2e41d14/tools/perf/lib/benchmark/runner/ib_read.py#L164)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

But it is not specific for LAT - it is common for LAT and BW. 
Should we add sth like `format/ib_read_common` ???
</blockquote></details>

Done

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r3, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1346)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 156 at r1](https://reviewable.io/reviews/pmem/rpma/1346#-Mpvu8hFDtauOIitDlkO:-MpzgiwX5PvgKZO_8A8g:b-m226cl) ([raw file](https://github.com/pmem/rpma/blob/f9086bfbc0c1403baa5248b2eb9b30cce2e41d14/tools/perf/lib/benchmark/runner/ib_read.py#L156)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

`err.message = err.message + " hello"`
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 143 at r5](https://reviewable.io/reviews/pmem/rpma/1346#-Mpzh5-r9xnZsJqWQlPK:-Mpzh5-r9xnZsJqWQlPL:b-bs2c25) ([raw file](https://github.com/pmem/rpma/blob/d533e2d9b4ad8ad6c9e3eac99a8f54be05694b93/tools/perf/lib/benchmark/runner/ib_read.py#L143)):*
> ```Python
> 
>         line = fmt.grep_output(ret.stdout, str(settings['bs']))
>         csv = fmt.line2csv(line)
> ```

Please call these two from within `.parse()`.
___
*[tools/perf/lib/format/__init__.py, line 16 at r5](https://reviewable.io/reviews/pmem/rpma/1346#-MpzhFqP9ceYD3ogpvzB:-MpzhFqP9ceYD3ogpvzC:b3q8obz) ([raw file](https://github.com/pmem/rpma/blob/d533e2d9b4ad8ad6c9e3eac99a8f54be05694b93/tools/perf/lib/format/__init__.py#L16)):*
> ```Python
> from .ib_read_bw import IbReadBwFormat
> from .ib_read_lat import IbReadLatFormat
> from .ib_read_common import *
> ```

It is not a good practice. Please enumerate both explicit.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1346)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 156 at r1](https://reviewable.io/reviews/pmem/rpma/1346#-Mpvu8hFDtauOIitDlkO:-MpzjC3P1g81wR0uYwzA:bufq8s4) ([raw file](https://github.com/pmem/rpma/blob/f9086bfbc0c1403baa5248b2eb9b30cce2e41d14/tools/perf/lib/benchmark/runner/ib_read.py#L156)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`err.message = err.message + " hello"`
</blockquote></details>

why hello ?

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1346)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 156 at r1](https://reviewable.io/reviews/pmem/rpma/1346#-Mpvu8hFDtauOIitDlkO:-Mpzjtop50dXBcqWd2s-:b-8o428w) ([raw file](https://github.com/pmem/rpma/blob/f9086bfbc0c1403baa5248b2eb9b30cce2e41d14/tools/perf/lib/benchmark/runner/ib_read.py#L156)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

why hello ?
</blockquote></details>

Please replace `"hello"` with your message. ;-)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1346)* status: 0 of 5 files reviewed, 3 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 156 at r1](https://reviewable.io/reviews/pmem/rpma/1346#-Mpvu8hFDtauOIitDlkO:-Mpzs3GqAGEc4smZ5OZS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f9086bfbc0c1403baa5248b2eb9b30cce2e41d14/tools/perf/lib/benchmark/runner/ib_read.py#L156)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please replace `"hello"` with your message. ;-)
</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 143 at r5](https://reviewable.io/reviews/pmem/rpma/1346#-Mpzh5-r9xnZsJqWQlPK:-Mpzqly21vexp4k05LJE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d533e2d9b4ad8ad6c9e3eac99a8f54be05694b93/tools/perf/lib/benchmark/runner/ib_read.py#L143)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please call these two from within `.parse()`.
</blockquote></details>

Done.
___
*[tools/perf/lib/format/__init__.py, line 16 at r5](https://reviewable.io/reviews/pmem/rpma/1346#-MpzhFqP9ceYD3ogpvzB:-MpzqnEE2kWkf6CnzT1f:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d533e2d9b4ad8ad6c9e3eac99a8f54be05694b93/tools/perf/lib/format/__init__.py#L16)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is not a good practice. Please enumerate both explicit.
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1346)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/lib/format/ib_read_bw.py, line 73 at r7](https://reviewable.io/reviews/pmem/rpma/1346#-Mq-nY004BqAps-LjZ-7:-Mq-nY004BqAps-LjZ-8:b-ejidw2) ([raw file](https://github.com/pmem/rpma/blob/0769f180d8e5345bffff71401c542fe756c5c17b/tools/perf/lib/format/ib_read_bw.py#L73)):*
> ```Python
>             'bs': data[2],
>             'ops': data[3],
>             'bw_avg': round(data[5], 2)
> ```

```python
pattern = '([0-9]+)[ ]+([0-9]+)[ ]+([0-9.]+)[ ]+([0-9.]+)[\t ]+([0-9.]+)'
found = re.search(pattern, output)
return {
    'threads': threads,
    'iodepth': iodepth,
    'bs': int(found.group(1)),
    'ops': float(found.group(6)),
    'bw_avg': round(float(found.group(4)), 2)
}
```

**Note**: It seems both `threads` and `iodepth` are non-optional parameters of `.parse()`.
___
*[tools/perf/lib/format/ib_read_lat.py, line 72 at r7](https://reviewable.io/reviews/pmem/rpma/1346#-Mq-pJsx9lA_xIPNB1H0:-Mq-pJsy63ZPPWY96WLL:bihqzou) ([raw file](https://github.com/pmem/rpma/blob/0769f180d8e5345bffff71401c542fe756c5c17b/tools/perf/lib/format/ib_read_lat.py#L72)):*
> ```Python
>             'lat_stdev': data[6],
>             'lat_pctl_99.0': data[7],
>             'lat_pctl_99.9': data[8]
> ```

.

**Note** obviously a different regex pattern is needed for the ib_read_lat output.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1346)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 156 at r1](https://reviewable.io/reviews/pmem/rpma/1346#-Mpvu8hFDtauOIitDlkO:-MqEMuVD8WAhz_DicqUY:b-qcl4re) ([raw file](https://github.com/pmem/rpma/blob/f9086bfbc0c1403baa5248b2eb9b30cce2e41d14/tools/perf/lib/benchmark/runner/ib_read.py#L156)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

It does not work in case of `CalledProcessError` - it seems `CalledProcessError.stdout` cannot be modified.
___
*[tools/perf/lib/format/ib_read_bw.py, line 73 at r7](https://reviewable.io/reviews/pmem/rpma/1346#-Mq-nY004BqAps-LjZ-7:-MqEN9cOABH65dip4GQN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0769f180d8e5345bffff71401c542fe756c5c17b/tools/perf/lib/format/ib_read_bw.py#L73)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```python
pattern = '([0-9]+)[ ]+([0-9]+)[ ]+([0-9.]+)[ ]+([0-9.]+)[\t ]+([0-9.]+)'
found = re.search(pattern, output)
return {
    'threads': threads,
    'iodepth': iodepth,
    'bs': int(found.group(1)),
    'ops': float(found.group(6)),
    'bw_avg': round(float(found.group(4)), 2)
}
```

**Note**: It seems both `threads` and `iodepth` are non-optional parameters of `.parse()`.
</blockquote></details>

Done.
___
*[tools/perf/lib/format/ib_read_lat.py, line 72 at r7](https://reviewable.io/reviews/pmem/rpma/1346#-Mq-pJsx9lA_xIPNB1H0:-MqENg5D-DzRmvaWOqYW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0769f180d8e5345bffff71401c542fe756c5c17b/tools/perf/lib/format/ib_read_lat.py#L72)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.

**Note** obviously a different regex pattern is needed for the ib_read_lat output.
</blockquote></details>

Done.

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1346)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1346)* status: 0 of 5 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/lib/format/ib_read_bw.py, line 73 at r7](https://reviewable.io/reviews/pmem/rpma/1346#-Mq-nY004BqAps-LjZ-7:-MqK1yMi5gscYRPUdN0y:b-dao53p) ([raw file](https://github.com/pmem/rpma/blob/0769f180d8e5345bffff71401c542fe756c5c17b/tools/perf/lib/format/ib_read_bw.py#L73)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@janekmi ping ;-)
___
*[tools/perf/lib/format/ib_read_lat.py, line 72 at r7](https://reviewable.io/reviews/pmem/rpma/1346#-Mq-pJsx9lA_xIPNB1H0:-MqK20VN8ToR-D_gwOLH:b-dao53p) ([raw file](https://github.com/pmem/rpma/blob/0769f180d8e5345bffff71401c542fe756c5c17b/tools/perf/lib/format/ib_read_lat.py#L72)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@janekmi ping ;-)

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 5 files at r8, 1 of 1 files at r11.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1346)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/lib/format/ib_read_bw.py, line 27 at r11](https://reviewable.io/reviews/pmem/rpma/1346#-MqOGvWM78LvL-01F_vJ:-MqOGvWM78LvL-01F_vK:b-qwlo4b) ([raw file](https://github.com/pmem/rpma/blob/cea793b9c4394c27c5ed17223aa7a20cc8f70db3/tools/perf/lib/format/ib_read_bw.py#L27)):*
> ```
> read_csv
> ```
do we still need it?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1346)* status: 3 of 5 files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tools/perf/lib/format/ib_read_bw.py, line 27 at r11](https://reviewable.io/reviews/pmem/rpma/1346#-MqOGvWM78LvL-01F_vJ:-MqOQLV7DDbN97GS-oZq:b2nhswy) ([raw file](https://github.com/pmem/rpma/blob/cea793b9c4394c27c5ed17223aa7a20cc8f70db3/tools/perf/lib/format/ib_read_bw.py#L27)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> read_csv
> ```
do we still need it?
</blockquote></details>

Yes

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1346)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1346)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 17 at r11](https://reviewable.io/reviews/pmem/rpma/1346#-MqOVTk9CsS_U-BbKxEC:-MqOVTkA0_A8T_HJ2pPB:b-db3z8t) ([raw file](https://github.com/pmem/rpma/blob/cea793b9c4394c27c5ed17223aa7a20cc8f70db3/tools/perf/lib/benchmark/runner/ib_read.py#L17)):*
> ```
> fmt
> ```
format

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1346)* status: 2 of 5 files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 17 at r11](https://reviewable.io/reviews/pmem/rpma/1346#-MqOVTk9CsS_U-BbKxEC:-MqOWGdt3KKLruoFabDy:b78c26n) ([raw file](https://github.com/pmem/rpma/blob/cea793b9c4394c27c5ed17223aa7a20cc8f70db3/tools/perf/lib/benchmark/runner/ib_read.py#L17)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> fmt
> ```
format
</blockquote></details>

Names conflict

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 3 files at r12, 1 of 1 files at r13.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1346)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 3 files at r12.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1346)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1346#-:-MqOXPfJ865NYP9BMP_1:bnfp4nl)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @janekmi)

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1346#-:-MqOXRnj9t6GrXKv2nXw:b593w57)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @janekmi)

**Pull request merged**
