### PR TITLE
tools: kvtable.lines2str(): check if 'lines' is iterable

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1119)

### CODE REVIEW

**Review by janekmi — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1119)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1119#-Mdc1jyb8rzOyVSeh2tl:-Mdc1jyb8rzOyVSeh2tm:bwkwttg) (no related file):*
In anticipation of the new development schema, I took your PR as an example. Please take a look #1123.
The idea is as follow:
- to write a function I should be able to describe what it is doing in natural language (docstring)
- to be sufficiently sure my implementation is correct I should write a test or two to test a general idea

Sorry for directly using your work but otherwise doing a review is a lottery. ;-)
I hope you won't be mad. ;-)

---
___
*[tools/perf/lib/kvtable.py, line 12 at r2](https://reviewable.io/reviews/pmem/rpma/1119#-Mdc5M2dA_j89nSKnpZe:-Mdc5M2dA_j89nSKnpZf:btt6r9n) ([raw file](https://github.com/pmem/rpma/blob/8064968ef57e5f561e5059ff78451cdc966104fa/tools/perf/lib/kvtable.py#L12)):*
> ```Python
> 
> def lines2str(lines, sep = "\n"):
>     if type(lines) is str:
> ```

I have used `instanceof()` because supposedly it is more versatile.
___
*[tools/perf/lib/kvtable.py, line 12 at r2](https://reviewable.io/reviews/pmem/rpma/1119#-Mdc5ZSMD08OptAtdzko:-Mdc5ZSMD08OptAtdzkp:bigqgi8) ([raw file](https://github.com/pmem/rpma/blob/e1bd8f39e980fe0ae83f3dc5fa1f2b168627725b/tools/perf/lib/kvtable.py#L12)):*
> ```Python
> 
> def lines2str(lines, sep = "\n"):
>     """Merge a list of lines into a single string"""
> ```

Please do not remove docstrings. ;-)

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1119)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1119#-Mdc1jyb8rzOyVSeh2tl:-MdiY7689DATTnQbV19T:br2tk7w) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

In anticipation of the new development schema, I took your PR as an example. Please take a look #1123.
The idea is as follow:
- to write a function I should be able to describe what it is doing in natural language (docstring)
- to be sufficiently sure my implementation is correct I should write a test or two to test a general idea

Sorry for directly using your work but otherwise doing a review is a lottery. ;-)
I hope you won't be mad. ;-)
</blockquote></details>

I have rethought my approach. Since we are in a transition stage, we can merge implementation and tests independently. So, the implementation is here whereas docstrings and tests I have provided in #1123. Nobody was harmed during my thought process. ;-)

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1119)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/lib/kvtable.py, line 12 at r2](https://reviewable.io/reviews/pmem/rpma/1119#-Mdc5M2dA_j89nSKnpZe:-Mdp5EDpAzeBhq15eJSB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8064968ef57e5f561e5059ff78451cdc966104fa/tools/perf/lib/kvtable.py#L12)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I have used `instanceof()` because supposedly it is more versatile.
</blockquote></details>

Done.
___
*[tools/perf/lib/kvtable.py, line 12 at r2](https://reviewable.io/reviews/pmem/rpma/1119#-Mdc5ZSMD08OptAtdzko:-Mdp5EYY8wqe52UZf2U9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e1bd8f39e980fe0ae83f3dc5fa1f2b168627725b/tools/perf/lib/kvtable.py#L12)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please do not remove docstrings. ;-)
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1119#-:-MdpQxg_2Vgu40-MZnap:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

___
*[tools/perf/lib/kvtable.py, line 16 at r3](https://reviewable.io/reviews/pmem/rpma/1119#-MdpQyu3C-yiAZrARvNu:-MdpQyu3C-yiAZrARvNv:b-r3gkhf) ([raw file](https://github.com/pmem/rpma/blob/bc1ae26f5c42e18283ddd953753e89d01d45afed/tools/perf/lib/kvtable.py#L16)):*
> ```Python
>         return lines
>     if hasattr(lines, '__iter__'):
>         # merge a list of lines into a single string
> ```

Seems redundant.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1119#-:-MdpRekl4rgssYH_ByS3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
