### PR TITLE
doc: improve the documentation to rpma_peer... functions

### PR DESCRIPTION
**Pull request by osalyk**
- [x] #425 

This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/420)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/420)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/420)* status: all files reviewed, 10 unresolved discussions (waiting on @osalyk)

___
*[src/include/librpma.h, line 159 at r1](https://reviewable.io/reviews/pmem/rpma/420#-MHypdYT85AwGjL00maI:-MHypdYT85AwGjL00maJ:b-9unw59) ([raw file](https://github.com/pmem/rpma/blob/a9ad4f41807742a3fd335ffb43bfae17f5400ea6/src/include/librpma.h#L159)):*
> ```objc
>  *
>  * DESCRIPTION
>  * rpma_peer_cfg_delete() delete the peer configuration object.
> ```

deletes
___
*[src/include/librpma.h, line 185 at r1](https://reviewable.io/reviews/pmem/rpma/420#-MHypzZG1-ic2o_BLjz0:-MHypzZG1-ic2o_BLjz1:b90d51a) ([raw file](https://github.com/pmem/rpma/blob/a9ad4f41807742a3fd335ffb43bfae17f5400ea6/src/include/librpma.h#L185)):*
> ```
> declare
>  * direct write to PMEM support.
> ```

`declareS the support of the direct write to PMEM.` - more in one line please
___
*[src/include/librpma.h, line 212 at r1](https://reviewable.io/reviews/pmem/rpma/420#-MHyquYdD0F47hkKpIQ1:-MHyquYdD0F47hkKpIQ2:b37j2up) ([raw file](https://github.com/pmem/rpma/blob/a9ad4f41807742a3fd335ffb43bfae17f5400ea6/src/include/librpma.h#L212)):*
> ```
> check direct write to PMEM support.
> ```

`checkS the support of the direct write to PMEM.`
___
*[src/include/librpma.h, line 238 at r1](https://reviewable.io/reviews/pmem/rpma/420#-MHyrDmvB2KRatpvNYUE:-MHyrDmvB2KRatpvNYUF:b-id8vc9) ([raw file](https://github.com/pmem/rpma/blob/a9ad4f41807742a3fd335ffb43bfae17f5400ea6/src/include/librpma.h#L238)):*
> ```
> a peer configuration
> ```

`the peer configuration`
___
*[src/include/librpma.h, line 238 at r1](https://reviewable.io/reviews/pmem/rpma/420#-MHyrHu40UbO1c8G3dYh:-MHyrHu5EaEFEvMkgSfB:bb7gsbm) ([raw file](https://github.com/pmem/rpma/blob/a9ad4f41807742a3fd335ffb43bfae17f5400ea6/src/include/librpma.h#L238)):*
> ```objc
>  *
>  * DESCRIPTION
>  * rpma_peer_cfg_get_descriptor() get a descriptor of a peer configuration.
> ```

gets
___
*[src/include/librpma.h, line 264 at r1](https://reviewable.io/reviews/pmem/rpma/420#-MHyrLL11QMxWwgGJ6jC:-MHyrLL11QMxWwgGJ6jD:bb7gsbm) ([raw file](https://github.com/pmem/rpma/blob/a9ad4f41807742a3fd335ffb43bfae17f5400ea6/src/include/librpma.h#L264)):*
> ```objc
>  *
>  * DESCRIPTION
>  * rpma_peer_cfg_get_descriptor_size() get size of the peer configuration
> ```

gets
___
*[src/include/librpma.h, line 292 at r1](https://reviewable.io/reviews/pmem/rpma/420#-MHyrU2I1U4eDdRbwBbN:-MHyrU2I1U4eDdRbwBbO:blgct78) ([raw file](https://github.com/pmem/rpma/blob/a9ad4f41807742a3fd335ffb43bfae17f5400ea6/src/include/librpma.h#L292)):*
> ```
> create
> ```

createS
___
*[src/include/librpma.h, line 292 at r1](https://reviewable.io/reviews/pmem/rpma/420#-MHyra-F22mjrlywZhwk:-MHyra-F22mjrlywZhwl:bvnqm5m) ([raw file](https://github.com/pmem/rpma/blob/a9ad4f41807742a3fd335ffb43bfae17f5400ea6/src/include/librpma.h#L292)):*
> ```
> a peer configuration
> ```

a peer configuration object
___
*[src/include/librpma.h, line 293 at r1](https://reviewable.io/reviews/pmem/rpma/420#-MHyrcSQ1hma0GQlhqJ9:-MHyrcSQ1hma0GQlhqJA:b-25imlt) ([raw file](https://github.com/pmem/rpma/blob/a9ad4f41807742a3fd335ffb43bfae17f5400ea6/src/include/librpma.h#L293)):*
> ```
> from a descriptor
> ```

from THE descriptor
___
*[src/include/librpma.h, line 355 at r1](https://reviewable.io/reviews/pmem/rpma/420#-MHyrgpx6tfPJk9lVOyX:-MHyrgpx6tfPJk9lVOyY:b-9unw65) ([raw file](https://github.com/pmem/rpma/blob/a9ad4f41807742a3fd335ffb43bfae17f5400ea6/src/include/librpma.h#L355)):*
> ```objc
>  *
>  * DESCRIPTION
>  * rpma_peer_delete() delete the peer object.
> ```

deleteS

**Review by ldorau — COMMENTED** [review]
@osalyk please verify the rest of those PRs against the analogous issues.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/420#-:-MHyrmdeBcIO9VdxEG27:b-269p9c)* status: all files reviewed, 10 unresolved discussions (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/420)* status: all files reviewed, 10 unresolved discussions (waiting on @ldorau)

___
*[src/include/librpma.h, line 159 at r1](https://reviewable.io/reviews/pmem/rpma/420#-MHypdYT85AwGjL00maI:-MHz3Skb3WE4VWFr8tnv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a9ad4f41807742a3fd335ffb43bfae17f5400ea6/src/include/librpma.h#L159)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

deletes
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 185 at r1](https://reviewable.io/reviews/pmem/rpma/420#-MHypzZG1-ic2o_BLjz0:-MHz3f-AAWaNjhY8wVdA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a9ad4f41807742a3fd335ffb43bfae17f5400ea6/src/include/librpma.h#L185)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> declare
>  * direct write to PMEM support.
> ```

`declareS the support of the direct write to PMEM.` - more in one line please


</blockquote></details>

Done.
___
*[src/include/librpma.h, line 212 at r1](https://reviewable.io/reviews/pmem/rpma/420#-MHyquYdD0F47hkKpIQ1:-MHz3oEK37fvJphLeQJg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a9ad4f41807742a3fd335ffb43bfae17f5400ea6/src/include/librpma.h#L212)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> check direct write to PMEM support.
> ```

`checkS the support of the direct write to PMEM.`
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 238 at r1](https://reviewable.io/reviews/pmem/rpma/420#-MHyrDmvB2KRatpvNYUE:-MHz3vmiDkmooWOP9NNg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a9ad4f41807742a3fd335ffb43bfae17f5400ea6/src/include/librpma.h#L238)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> a peer configuration
> ```

`the peer configuration`
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 238 at r1](https://reviewable.io/reviews/pmem/rpma/420#-MHyrHu40UbO1c8G3dYh:-MHz3xh134YAwNKKXh7e:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a9ad4f41807742a3fd335ffb43bfae17f5400ea6/src/include/librpma.h#L238)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

gets
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 264 at r1](https://reviewable.io/reviews/pmem/rpma/420#-MHyrLL11QMxWwgGJ6jC:-MHz48mCDg2jQhE6fDIh:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a9ad4f41807742a3fd335ffb43bfae17f5400ea6/src/include/librpma.h#L264)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

gets
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 292 at r1](https://reviewable.io/reviews/pmem/rpma/420#-MHyrU2I1U4eDdRbwBbN:-MHz4Efn2O_a6gKAPpTA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a9ad4f41807742a3fd335ffb43bfae17f5400ea6/src/include/librpma.h#L292)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> create
> ```

createS
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 292 at r1](https://reviewable.io/reviews/pmem/rpma/420#-MHyra-F22mjrlywZhwk:-MHz4HVU2ppPer1bI2Vz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a9ad4f41807742a3fd335ffb43bfae17f5400ea6/src/include/librpma.h#L292)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> a peer configuration
> ```

a peer configuration object
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 293 at r1](https://reviewable.io/reviews/pmem/rpma/420#-MHyrcSQ1hma0GQlhqJ9:-MHz4Laq9gMs-4ACQ0wz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a9ad4f41807742a3fd335ffb43bfae17f5400ea6/src/include/librpma.h#L293)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> from a descriptor
> ```

from THE descriptor
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 355 at r1](https://reviewable.io/reviews/pmem/rpma/420#-MHyrgpx6tfPJk9lVOyX:-MHz4QH1EyO6XX8vmZJG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a9ad4f41807742a3fd335ffb43bfae17f5400ea6/src/include/librpma.h#L355)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

deleteS
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/420)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/420#-:-MHz69-u2a-biGdgkwy6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
@grom72 please review

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/420#-:-MHz6BIe1bGyJLjwQDYc:bgjoyzx)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/420)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/420#-:-MI-BV5g-w0HYoqk15RT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/420)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/420)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[src/include/librpma.h, line 240 at r2](https://reviewable.io/reviews/pmem/rpma/420#-MI-GfvOEdLYeC7-tj_D:-MI-GfvOEdLYeC7-tj_E:bf515tb) ([raw file](https://github.com/pmem/rpma/blob/22898a627a0de3364d228d4a477a46b1b35baaf4/src/include/librpma.h#L240)):*
> ```
> gets a descriptor
> ```

gets THE descriptor

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/420)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/include/librpma.h, line 240 at r2](https://reviewable.io/reviews/pmem/rpma/420#-MI-GfvOEdLYeC7-tj_D:-MI-HIcJ34CuK9O7WAF4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/22898a627a0de3364d228d4a477a46b1b35baaf4/src/include/librpma.h#L240)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> gets a descriptor
> ```

gets THE descriptor
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/420)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
