### PR TITLE
rpma: remove the invalidation of the private data pointer

### PR DESCRIPTION
**Pull request by ewanglong**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/945)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/945)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @ewanglong)

___
*[tests/unit/conn/conn-private_data.c, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/945#-MW3_Xnq1Ph7kSUhDvo3:-MW3_Xnq1Ph7kSUhDvo4:bmrb61c) ([raw file](https://github.com/pmem/rpma/blob/6a9c12962e9a7399d2a1e0ab5cd5dbb4e0777411/tests/unit/conn/conn-private_data.c#L2)):*
> ```C
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2020, Intel Corporation */
> ```

/* Copyright 2020-2021, Intel Corporation */

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/945)* status: 2 of 5 files reviewed, 6 unresolved discussions (waiting on @ewanglong)

___
*[src/conn.c, line 101 at r1](https://reviewable.io/reviews/pmem/rpma/945#-MW3hdF709nBFTlVZNqt:-MW3hdF709nBFTlVZNqu:b-1t5uhb) ([raw file](https://github.com/pmem/rpma/blob/6a9c12962e9a7399d2a1e0ab5cd5dbb4e0777411/src/conn.c#L101)):*
> ```C
> 
> /*
>  * rpma_conn_set_private_data -- set the private data of the CM ID
> ```

rpma_conn_transfer_private_data -- transfer the private data to the connection (a take over)
___
*[src/conn.c, line 101 at r1](https://reviewable.io/reviews/pmem/rpma/945#-MW3i8Ny2NWgkQkF-q-y:-MW3i8Ny2NWgkQkF-q-z:bqoaqg3) ([raw file](https://github.com/pmem/rpma/blob/6a9c12962e9a7399d2a1e0ab5cd5dbb4e0777411/src/conn.c#L101)):*
> ```C
> 
> /*
>  * rpma_conn_set_private_data -- set the private data of the CM ID
> ```

**Note**: Make sure to update the `conn.h` file.
___
*[src/conn.c, line 108 at r1](https://reviewable.io/reviews/pmem/rpma/945#-MW3epD76HwdkBmQWBxJ:-MW3epD76HwdkBmQWBxK:b-mjn46b) ([raw file](https://github.com/pmem/rpma/blob/6a9c12962e9a7399d2a1e0ab5cd5dbb4e0777411/src/conn.c#L108)):*
> ```C
> {
> 	if (conn == NULL || pdata == NULL)
> 		return RPMA_E_INVAL;
> ```

You might have noticed this assumptions in the header file:

```
 * ASSUMPTIONS
 * - conn != NULL && pdata != NULL
```

It means you do not have to validate these arguments since it is already done by the upper layer.
___
*[src/conn.c, line 111 at r1](https://reviewable.io/reviews/pmem/rpma/945#-MW3gD0j0-3I3M8lcCYD:-MW3gD0j0-3I3M8lcCYE:b-i23uro) ([raw file](https://github.com/pmem/rpma/blob/6a9c12962e9a7399d2a1e0ab5cd5dbb4e0777411/src/conn.c#L111)):*
> ```C
> 
> 	conn->data.ptr = pdata->ptr;
> 	conn->data.len = pdata->len;
> ```

I consider zero-ing the source pointers e.g.

```c
pdata->ptr = NULL;
pdata->len = 0;
```

Just in case somebody will miss the private data was taken over by the connection object and would try to free it.
___
*[src/conn.c, line 113 at r1](https://reviewable.io/reviews/pmem/rpma/945#-MW3g5SxB7I6hTcTCSbQ:-MW3g5SxB7I6hTcTCSbR:bm5yshj) ([raw file](https://github.com/pmem/rpma/blob/6a9c12962e9a7399d2a1e0ab5cd5dbb4e0777411/src/conn.c#L113)):*
> ```C
> 	conn->data.len = pdata->len;
> 
> 	return 0;
> ```

If it cannot fail it should not have a return value.

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/945)* status: 2 of 5 files reviewed, 7 unresolved discussions (waiting on @ewanglong)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/945#-MW3iiO5BP6Dp02P0ydO:-MW3iiO5BP6Dp02P0ydP:b75ycnq) (no related file):*
It seems after this change `rpma_private_data_copy()` is not needed any more.
Please remove it and all its tests.

---

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/945)* status: 3 of 5 files reviewed, 7 unresolved discussions (waiting on @ewanglong)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/945)* status: all files reviewed, 11 unresolved discussions (waiting on @ewanglong)

___
*[tests/unit/conn/conn-private_data.c, line 84 at r1](https://reviewable.io/reviews/pmem/rpma/945#-MW3lMnH8w2Sp47dnBWF:-MW3lMnH8w2Sp47dnBWG:b-vx5oov) ([raw file](https://github.com/pmem/rpma/blob/6a9c12962e9a7399d2a1e0ab5cd5dbb4e0777411/tests/unit/conn/conn-private_data.c#L84)):*
> ```C
> 	assert_ptr_equal(check_data.ptr, NULL);
> 	assert_int_equal(check_data.len, 0);
> }
> ```

Violates the assumptions. Please see the `conn.h` header for details.
___
*[tests/unit/conn/conn-private_data.c, line 102 at r1](https://reviewable.io/reviews/pmem/rpma/945#-MW3labk6oRm8DyK8b0L:-MW3labk6oRm8DyK8b0M:b-vx5oov) ([raw file](https://github.com/pmem/rpma/blob/6a9c12962e9a7399d2a1e0ab5cd5dbb4e0777411/tests/unit/conn/conn-private_data.c#L102)):*
> ```C
> 	/* verify the results of rpma_conn_set_private_data() */
> 	assert_int_equal(ret, RPMA_E_INVAL);
> }
> ```

Violates the assumptions. Please see the `conn.h` header for details.
___
*[tests/unit/conn/conn-private_data.c, line 108 at r1](https://reviewable.io/reviews/pmem/rpma/945#-MW3oSMgDdlib8vJJ-bj:-MW3oSMh3nDIxa9EGsCb:b-8ktdea) ([raw file](https://github.com/pmem/rpma/blob/6a9c12962e9a7399d2a1e0ab5cd5dbb4e0777411/tests/unit/conn/conn-private_data.c#L108)):*
> ```C
>  */
> static void
> set_private_data__success(void **cstate_ptr)
> ```

transfer_private_data__success
___
*[tests/unit/conn/conn-private_data.c, line 124 at r1](https://reviewable.io/reviews/pmem/rpma/945#-MW3o_QC9sYPXp1Yyxzc:-MW3o_QC9sYPXp1Yyxzd:b-s0a6n5) ([raw file](https://github.com/pmem/rpma/blob/6a9c12962e9a7399d2a1e0ab5cd5dbb4e0777411/tests/unit/conn/conn-private_data.c#L124)):*
> ```C
> 
> 	/* verify the results of rpma_conn_set_private_data() */
> 	assert_int_equal(ret, MOCK_OK);
> ```

If we agree to zero the source of the private data after the transfer you should verify the effect here.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/945)* status: all files reviewed, 11 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[src/conn.c, line 111 at r1](https://reviewable.io/reviews/pmem/rpma/945#-MW3gD0j0-3I3M8lcCYD:-MW4e1DB7koS4qAPRgjh:b32v57) ([raw file](https://github.com/pmem/rpma/blob/6a9c12962e9a7399d2a1e0ab5cd5dbb4e0777411/src/conn.c#L111)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I consider zero-ing the source pointers e.g.

```c
pdata->ptr = NULL;
pdata->len = 0;
```

Just in case somebody will miss the private data was taken over by the connection object and would try to free it.
</blockquote></details>

+1
___
*[tests/unit/conn/conn-private_data.c, line 124 at r1](https://reviewable.io/reviews/pmem/rpma/945#-MW3o_QC9sYPXp1Yyxzc:-MW4esNAB8fK92WWImec:b32v57) ([raw file](https://github.com/pmem/rpma/blob/6a9c12962e9a7399d2a1e0ab5cd5dbb4e0777411/tests/unit/conn/conn-private_data.c#L124)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

If we agree to zero the source of the private data after the transfer you should verify the effect here.
</blockquote></details>

+1

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/945)* status: all files reviewed, 11 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[src/conn.c, line 108 at r1](https://reviewable.io/reviews/pmem/rpma/945#-MW3epD76HwdkBmQWBxJ:-MW4gSbY7uKmEBucNxdB:b32v57) ([raw file](https://github.com/pmem/rpma/blob/6a9c12962e9a7399d2a1e0ab5cd5dbb4e0777411/src/conn.c#L108)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You might have noticed this assumptions in the header file:

```
 * ASSUMPTIONS
 * - conn != NULL && pdata != NULL
```

It means you do not have to validate these arguments since it is already done by the upper layer.
</blockquote></details>

+1
___
*[tests/unit/conn/conn-private_data.c, line 84 at r1](https://reviewable.io/reviews/pmem/rpma/945#-MW3lMnH8w2Sp47dnBWF:-MW4fjDA6qe2Qg1DbZhi:bu2slk) ([raw file](https://github.com/pmem/rpma/blob/6a9c12962e9a7399d2a1e0ab5cd5dbb4e0777411/tests/unit/conn/conn-private_data.c#L84)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Violates the assumptions. Please see the `conn.h` header for details.
</blockquote></details>

See assumptions in the header file:

```
 * ASSUMPTIONS
 * - conn != NULL && pdata != NULL
```

It (pdata == NULL) cannot happen, so this test case is impossible and should be removed.
___
*[tests/unit/conn/conn-private_data.c, line 102 at r1](https://reviewable.io/reviews/pmem/rpma/945#-MW3labk6oRm8DyK8b0L:-MW4gBlr1YVMvOirmNiR:b-7s3yfg) ([raw file](https://github.com/pmem/rpma/blob/6a9c12962e9a7399d2a1e0ab5cd5dbb4e0777411/tests/unit/conn/conn-private_data.c#L102)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Violates the assumptions. Please see the `conn.h` header for details.
</blockquote></details>

See assumptions in the header file:

```
 * ASSUMPTIONS
 * - conn != NULL && pdata != NULL
```

It (conn == NULL) cannot happen, so this test case is impossible and should be removed.

**Review by ewanglong — COMMENTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/945)* status: 0 of 13 files reviewed, 11 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/945#-MW3iiO5BP6Dp02P0ydO:-MW7efZE3SXvBdqNEgVd:b-896fjx) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It seems after this change `rpma_private_data_copy()` is not needed any more.
Please remove it and all its tests.
</blockquote></details>

Done

---
___
*[src/conn.c, line 101 at r1](https://reviewable.io/reviews/pmem/rpma/945#-MW3hdF709nBFTlVZNqt:-MW7evuY2kRV6cCr4W2H:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6a9c12962e9a7399d2a1e0ab5cd5dbb4e0777411/src/conn.c#L101)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

rpma_conn_transfer_private_data -- transfer the private data to the connection (a take over)
</blockquote></details>

Done.
___
*[src/conn.c, line 101 at r1](https://reviewable.io/reviews/pmem/rpma/945#-MW3i8Ny2NWgkQkF-q-y:-MW7ewgT3c5OwA6wNHIN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6a9c12962e9a7399d2a1e0ab5cd5dbb4e0777411/src/conn.c#L101)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

**Note**: Make sure to update the `conn.h` file.
</blockquote></details>

Done.
___
*[src/conn.c, line 108 at r1](https://reviewable.io/reviews/pmem/rpma/945#-MW3epD76HwdkBmQWBxJ:-MW7es_4B9SXXeQeRbWB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6a9c12962e9a7399d2a1e0ab5cd5dbb4e0777411/src/conn.c#L108)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[src/conn.c, line 111 at r1](https://reviewable.io/reviews/pmem/rpma/945#-MW3gD0j0-3I3M8lcCYD:-MW7ev6p7koEGkNCOYlZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6a9c12962e9a7399d2a1e0ab5cd5dbb4e0777411/src/conn.c#L111)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[src/conn.c, line 113 at r1](https://reviewable.io/reviews/pmem/rpma/945#-MW3g5SxB7I6hTcTCSbQ:-MW7eucS0x-Zd77US8pd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6a9c12962e9a7399d2a1e0ab5cd5dbb4e0777411/src/conn.c#L113)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

If it cannot fail it should not have a return value.
</blockquote></details>

Done.
___
*[tests/unit/conn/conn-private_data.c, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/945#-MW3_Xnq1Ph7kSUhDvo3:-MW7h5zr8OhcT6ZR5W9T:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6a9c12962e9a7399d2a1e0ab5cd5dbb4e0777411/tests/unit/conn/conn-private_data.c#L2)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

/* Copyright 2020-2021, Intel Corporation */
</blockquote></details>

Done.
___
*[tests/unit/conn/conn-private_data.c, line 84 at r1](https://reviewable.io/reviews/pmem/rpma/945#-MW3lMnH8w2Sp47dnBWF:-MW7h93M5SYMsDRLaGVz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6a9c12962e9a7399d2a1e0ab5cd5dbb4e0777411/tests/unit/conn/conn-private_data.c#L84)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

See assumptions in the header file:

```
 * ASSUMPTIONS
 * - conn != NULL && pdata != NULL
```

It (pdata == NULL) cannot happen, so this test case is impossible and should be removed.
</blockquote></details>

Done.
___
*[tests/unit/conn/conn-private_data.c, line 102 at r1](https://reviewable.io/reviews/pmem/rpma/945#-MW3labk6oRm8DyK8b0L:-MW7h9nH6TTiVqgCe3lT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6a9c12962e9a7399d2a1e0ab5cd5dbb4e0777411/tests/unit/conn/conn-private_data.c#L102)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

See assumptions in the header file:

```
 * ASSUMPTIONS
 * - conn != NULL && pdata != NULL
```

It (conn == NULL) cannot happen, so this test case is impossible and should be removed.
</blockquote></details>

Done.
___
*[tests/unit/conn/conn-private_data.c, line 108 at r1](https://reviewable.io/reviews/pmem/rpma/945#-MW3oSMgDdlib8vJJ-bj:-MW7hADx29mAqxDCzMBR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6a9c12962e9a7399d2a1e0ab5cd5dbb4e0777411/tests/unit/conn/conn-private_data.c#L108)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

transfer_private_data__success
</blockquote></details>

Done.
___
*[tests/unit/conn/conn-private_data.c, line 124 at r1](https://reviewable.io/reviews/pmem/rpma/945#-MW3o_QC9sYPXp1Yyxzc:-MW7hAsJ73BxuhY8blDQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6a9c12962e9a7399d2a1e0ab5cd5dbb4e0777411/tests/unit/conn/conn-private_data.c#L124)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 8 of 13 files at r2, 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/945)* status: all files reviewed, 15 unresolved discussions (waiting on @ewanglong and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/945#-MW8iWso2TwFEGNQtK-M:-MW8iWsp0R34Wa7zDQIm:bfekabf) (no related file):*
The CI builds fail.

---
___
*[src/conn_req.c, line 159 at r3](https://reviewable.io/reviews/pmem/rpma/945#-MW8_YETE5kGcTIKbrb0:-MW8_YETE5kGcTIKbrb1:bns1prz) ([raw file](https://github.com/pmem/rpma/blob/1d50225669dab83e040c7606eee951be5a975c68/src/conn_req.c#L159)):*
> ```
> err_conn_delete:
> 	(void) rpma_conn_delete(&conn);
> ```

```
/rpma/src/conn_req.c: In function 'rpma_conn_req_accept':
/rpma/src/conn_req.c:158:1: error: label 'err_conn_delete' defined but not used [-Werror=unused-label]
  158 | err_conn_delete:
      | ^~~~~~~~~~~~~~~
```
___
*[src/include/librpma.h, line 1414 at r3](https://reviewable.io/reviews/pmem/rpma/945#-MW8NpWMCYtFJVb-jW6z:-MW8NpWMCYtFJVb-jW7-:b-l0mwfo) ([raw file](https://github.com/pmem/rpma/blob/1d50225669dab83e040c7606eee951be5a975c68/src/include/librpma.h#L1414)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
> struct rpma_conn {
> 	struct rdma_cm_id *id; /* a CM ID of the connection */
> 	struct rdma_event_channel *evch; /* event channel of the CM ID */
> 	struct ibv_comp_channel *channel; /* completion event channel */
> 	struct ibv_cq *cq; /* completion queue of the CM ID */
> 	struct rpma_conn_private_data data; /* private data of the CM ID */
> 	struct rpma_flush *flush; /* flushing object */
> 	bool direct_write_to_pmem; /* direct write to pmem is supported */
> };
> ```
</details>


This is a private structure of librpma and cannot be included the public header.
___
*[tests/unit/common/mocks-rpma-conn.c, line 78 at r3](https://reviewable.io/reviews/pmem/rpma/945#-MW8iy0H2XT1qVcWGjNY:-MW8iy0H2XT1qVcWGjNZ:be18mkf) ([raw file](https://github.com/pmem/rpma/blob/1d50225669dab83e040c7606eee951be5a975c68/tests/unit/common/mocks-rpma-conn.c#L78)):*
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>

> ```
> int
> rpma_conn_transfer_private_data(struct rpma_conn *conn,
> 		struct rpma_conn_private_data *pdata)
> {
> 	assert_non_null(conn);
> 	assert_non_null(pdata);
> 	check_expected(conn);
> 	check_expected(pdata->ptr);
> 	check_expected(pdata->len);
> }
> ```
</details>


Missing `return`

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 13 files at r2, 4 of 5 files at r3, 4 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/945)* status: all files reviewed, 5 unresolved discussions (waiting on @ewanglong and @ldorau)

___
*[src/conn.c, line 32 at r1](https://reviewable.io/reviews/pmem/rpma/945#-MW8sOJ6DRbPIbsbJTqe:-MW8sCg8Asfnic-PoH1z:b5bu9lh) ([raw file](https://github.com/pmem/rpma/blob/6a9c12962e9a7399d2a1e0ab5cd5dbb4e0777411/src/conn.c#L32)):*
> ```C
> 
> 	bool direct_write_to_pmem; /* direct write to pmem is supported */
> };
> ```

This structure stays where it is. Please return it to the original place.
___
*[src/include/librpma.h, line 1414 at r3](https://reviewable.io/reviews/pmem/rpma/945#-MW8NpWMCYtFJVb-jW6z:-MW8swyp5tpEMBDXibt3:b-qfxebq) ([raw file](https://github.com/pmem/rpma/blob/1d50225669dab83e040c7606eee951be5a975c68/src/include/librpma.h#L1414)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Movied it to conn.h to let some unit test build pass.
</blockquote></details>

This structure (and many more others) are internal for its *.c file on purpose.
It forces us to maintain its internal independence and use only its API instead of manually creating convenient to use objects which can not exist in nature.

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/945)* status: 8 of 12 files reviewed, 5 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/945#-MW8iWso2TwFEGNQtK-M:-MW8zIRq48t66LQ_r5QU:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The CI builds fail.
</blockquote></details>

Done.

---
___
*[src/conn.c, line 32 at r1](https://reviewable.io/reviews/pmem/rpma/945#-MW8sOJ6DRbPIbsbJTqe:-MW8zJGe7abOAmKzTDj7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6a9c12962e9a7399d2a1e0ab5cd5dbb4e0777411/src/conn.c#L32)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This structure stays where it is. Please return it to the original place.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1414 at r3](https://reviewable.io/reviews/pmem/rpma/945#-MW8NpWMCYtFJVb-jW6z:-MW8wGdBES6Xg6u99eDy:b-osf579) ([raw file](https://github.com/pmem/rpma/blob/1d50225669dab83e040c7606eee951be5a975c68/src/include/librpma.h#L1414)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This structure (and many more others) are internal for its *.c file on purpose.
It forces us to maintain its internal independence and use only its API instead of manually creating convenient to use objects which can not exist in nature.
</blockquote></details>

if moving back to .c, there are below build error.
tests/unit/conn/conn-common.c:106:17: error: invalid use of undefined type ‘struct rpma_conn’
  106 |     cstate->conn->data.ptr);

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/945)* status: 8 of 12 files reviewed, 5 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[src/include/librpma.h, line 1414 at r3](https://reviewable.io/reviews/pmem/rpma/945#-MW8NpWMCYtFJVb-jW6z:-MW8zRk_81E3fAdJRgYF:b-k1y5pj) ([raw file](https://github.com/pmem/rpma/blob/1d50225669dab83e040c7606eee951be5a975c68/src/include/librpma.h#L1414)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

if moving back to .c, there are below build error.
tests/unit/conn/conn-common.c:106:17: error: invalid use of undefined type ‘struct rpma_conn’
  106 |     cstate->conn->data.ptr);

</blockquote></details>

OK. Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 2 of 4 files at r4, 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/945#-:-MW99KBt9EOitit6BKhp:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/945)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
> Reviewed 3 of 13 files at r2, 3 of 5 files at r3, 3 of 4 files at r4, 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/945)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/945)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

___
*[tests/unit/conn/conn-private_data.c, line 92 at r5](https://reviewable.io/reviews/pmem/rpma/945#-MWcRYQc6GLPYP5z1pbJ:-MWcRYQc6GLPYP5z1pbK:b-kvv35w) ([raw file](https://github.com/pmem/rpma/blob/1119b9e237216f197f9d7f482692533985d32ed9/tests/unit/conn/conn-private_data.c#L92)):*
> ```C
> 	/* set expected private data */
> 	cstate->data.ptr = MOCK_PRIVATE_DATA;
> 	cstate->data.len = MOCK_PDATA_LEN;
> ```

It seems the end of the test. Nothing more will be validated. Why setting this pointer here?

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/945)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tests/unit/conn/conn-private_data.c, line 92 at r5](https://reviewable.io/reviews/pmem/rpma/945#-MWcRYQc6GLPYP5z1pbJ:-MWcUCsi-Py7f9Cln1ji:bsjerow) ([raw file](https://github.com/pmem/rpma/blob/1119b9e237216f197f9d7f482692533985d32ed9/tests/unit/conn/conn-private_data.c#L92)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It seems the end of the test. Nothing more will be validated. Why setting this pointer here?
</blockquote></details>

Because during teardown__conn_delete() it needs check "expect_value(rpma_private_data_discard, pdata->ptr,
				cstate->data.ptr);". But in rpma_conn_transfer_private_data, the pdata->ptr was zeroed. So need set it back.

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/945)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

___
*[tests/unit/conn/conn-private_data.c, line 90 at r5](https://reviewable.io/reviews/pmem/rpma/945#-MWcWXiP8OUcEshvX78L:-MWcW6Yt9e5khzKXcmRP:b-w5vdm) ([raw file](https://github.com/pmem/rpma/blob/1119b9e237216f197f9d7f482692533985d32ed9/tests/unit/conn/conn-private_data.c#L90)):*
> ```C
> 	assert_int_equal(check_data.len, MOCK_PDATA_LEN);
> 
> 	/* set expected private data */
> ```

set expected private data which will be used during teardown

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/945)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @grom72, @janekmi, and @ldorau)

___
*[tests/unit/conn/conn-private_data.c, line 90 at r5](https://reviewable.io/reviews/pmem/rpma/945#-MWcWXiP8OUcEshvX78L:-MWcXw2l1QZvc5pa81mP:bs7wumb) ([raw file](https://github.com/pmem/rpma/blob/1119b9e237216f197f9d7f482692533985d32ed9/tests/unit/conn/conn-private_data.c#L90)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

set expected private data which will be used during teardown
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/945#-:-MWcYVYkBo_gSKk0w3-7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/945)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong)

___
*[0001-rpma-remove-the-invalidation-of-the-private-data-poi.patch, line 59 at r7](https://reviewable.io/reviews/pmem/rpma/945#-MWca7Rb42hW9RsXKPeH:-MWca7Rb42hW9RsXKPeI:b8g31uy) ([raw file](https://github.com/pmem/rpma/blob/c669b39c274fad58511ec3d95da6316598ed7793/0001-rpma-remove-the-invalidation-of-the-private-data-poi.patch#L59)):*
> ```Diff
>  
> -- 
> 2.27.0.windows.1
> ```

Something went wrong here. Please remove.
___
*[cmake-build-debug/CMakeFiles/clion-log.txt, line 1 at r7](https://reviewable.io/reviews/pmem/rpma/945#-MWcaBwu-PSNvKumUaCv:-MWcaBwu-PSNvKumUaCw:b-41f8id) ([raw file](https://github.com/pmem/rpma/blob/c669b39c274fad58511ec3d95da6316598ed7793/cmake-build-debug/CMakeFiles/clion-log.txt#L1)):*
> ```vimhelp
> Toolchains are not configured Configure
> ```

Same here. Please remove.

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/945)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Pull request merged**
