### PR TITLE
test: add rpma_conn_cfg_set_cq_size multithreaded test

### PR DESCRIPTION
**Pull request by ewanglong**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1097)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1097)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @ewanglong)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1097)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

___
*[tests/multithreaded/conn/rpma_conn_cfg_set_cq_size.c, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1097#-McxaGNQ-gUcuMwXe-0L:-McxaGNQ-gUcuMwXe-0M:b-cyqcrf) ([raw file](https://github.com/pmem/rpma/blob/f80f14291ef5f1d0a1954dfbb35c1e2a0137bf96/tests/multithreaded/conn/rpma_conn_cfg_set_cq_size.c#L13)):*
> ```
> Q_SIZE_EXP
> ```

Please rename it to `Q_SIZE_EXPECTED` because `EXP` is ambiguous

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1097)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong and @ldorau)

___
*[tests/multithreaded/conn/rpma_conn_cfg_set_cq_size.c, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1097#-McxaGNQ-gUcuMwXe-0L:-Mcxd3op2gnoAPZ8awuU:b-yp601z) ([raw file](https://github.com/pmem/rpma/blob/f80f14291ef5f1d0a1954dfbb35c1e2a0137bf96/tests/multithreaded/conn/rpma_conn_cfg_set_cq_size.c#L13)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> Q_SIZE_EXP
> ```

Please rename it to `Q_SIZE_EXPECTED` because `EXP` is ambiguous
</blockquote></details>

Yeah. We have built a lot of code with an assumption that suffix `_exp`/`_EXP` means expected.
I'm not sure we want to use `_expected` instead. @ldorau if you think it will be more comprehensible I think we can address it in another PR.
Maybe a comment is enough? What do you think?
___
*[tests/multithreaded/conn/rpma_conn_cfg_set_cq_size.c, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1097#-Mcxdz0I-WzZiqOVqWqn:-Mcxdz0J82yoxoO8A0Ug:byr428s) ([raw file](https://github.com/pmem/rpma/blob/f80f14291ef5f1d0a1954dfbb35c1e2a0137bf96/tests/multithreaded/conn/rpma_conn_cfg_set_cq_size.c#L39)):*
> ```C
> 
> 	*state_ptr = st;
> }
> ```

This function is common for all rpma_conn_cfg_set/_get* tests. So, it makes sense to make it common.
Please make a separate `rpma_conn_cfg_common.c/.h` files for this `init()` and `fini()` below.
I think these two should be also renamed as `rpma_conn_cfg_common_init/_fini()`.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1097)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/conn/rpma_conn_cfg_set_cq_size.c, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1097#-McxaGNQ-gUcuMwXe-0L:-McxfDSJBKKm7RhsAlPp:b-9vv375) ([raw file](https://github.com/pmem/rpma/blob/f80f14291ef5f1d0a1954dfbb35c1e2a0137bf96/tests/multithreaded/conn/rpma_conn_cfg_set_cq_size.c#L13)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Yeah. We have built a lot of code with an assumption that suffix `_exp`/`_EXP` means expected.
I'm not sure we want to use `_expected` instead. @ldorau if you think it will be more comprehensible I think we can address it in another PR.
Maybe a comment is enough? What do you think?
</blockquote></details>

OK, a comment is enough here.
___
*[tests/multithreaded/conn/rpma_conn_cfg_set_cq_size.c, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1097#-Mcxdz0I-WzZiqOVqWqn:-McxfUmG0Wq2rs48F95G:b32v57) ([raw file](https://github.com/pmem/rpma/blob/f80f14291ef5f1d0a1954dfbb35c1e2a0137bf96/tests/multithreaded/conn/rpma_conn_cfg_set_cq_size.c#L39)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This function is common for all rpma_conn_cfg_set/_get* tests. So, it makes sense to make it common.
Please make a separate `rpma_conn_cfg_common.c/.h` files for this `init()` and `fini()` below.
I think these two should be also renamed as `rpma_conn_cfg_common_init/_fini()`.
</blockquote></details>

+1

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1097)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/conn/rpma_conn_cfg_set_cq_size.c, line 17 at r1](https://reviewable.io/reviews/pmem/rpma/1097#-McxfvBLBeMO6Nomnio8:-McxfvBLBeMO6Nomnio9:b-m2b6w6) ([raw file](https://github.com/pmem/rpma/blob/f80f14291ef5f1d0a1954dfbb35c1e2a0137bf96/tests/multithreaded/conn/rpma_conn_cfg_set_cq_size.c#L17)):*
> ```C
> struct state {
> 	struct rpma_conn_cfg *cfg_ptr;
> };
> ```

FYI This structure also should be a part of the common header and named as e.g. `struct rpma_conn_cfg_common_state`.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1097)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong and @ldorau)

___
*[tests/multithreaded/conn/rpma_conn_cfg_set_cq_size.c, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1097#-McxaGNQ-gUcuMwXe-0L:-Mcxh4fE2BXbzDv7P5Ft:bqhonvj) ([raw file](https://github.com/pmem/rpma/blob/f80f14291ef5f1d0a1954dfbb35c1e2a0137bf96/tests/multithreaded/conn/rpma_conn_cfg_set_cq_size.c#L13)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK, a comment is enough here.
</blockquote></details>

I suggest to settle this as follows (`rpma_conn_cfg_common.h`):

```c
/* an expected queue size */
#define RPMA_CONN_CFG_COMMON_Q_SIZE_EXP 20
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1097)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/multithreaded/conn/rpma_conn_cfg_set_cq_size.c, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1097#-McxaGNQ-gUcuMwXe-0L:-Mcxi1Cq-TmtPDdYHNWL:b-rlyq4r) ([raw file](https://github.com/pmem/rpma/blob/f80f14291ef5f1d0a1954dfbb35c1e2a0137bf96/tests/multithreaded/conn/rpma_conn_cfg_set_cq_size.c#L13)):*
> /* an expected queue size */

+1 but `the expected`:

`/* the expected queue size */`

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1097)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong and @ldorau)

___
*[tests/multithreaded/conn/rpma_conn_cfg_set_cq_size.c, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1097#-McxaGNQ-gUcuMwXe-0L:-McxiE_xCzPleU44Q-KJ:b-8fx2u7) ([raw file](https://github.com/pmem/rpma/blob/f80f14291ef5f1d0a1954dfbb35c1e2a0137bf96/tests/multithreaded/conn/rpma_conn_cfg_set_cq_size.c#L13)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> /* an expected queue size */

+1 but `the expected`:

`/* the expected queue size */`
</blockquote></details>

:+1:

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1097)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tests/multithreaded/conn/rpma_conn_cfg_set_cq_size.c, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1097#-McxaGNQ-gUcuMwXe-0L:-Md0GCf8EiN0VNVfQi5I:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f80f14291ef5f1d0a1954dfbb35c1e2a0137bf96/tests/multithreaded/conn/rpma_conn_cfg_set_cq_size.c#L13)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_cfg_set_cq_size.c, line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1097#-Mcxdz0I-WzZiqOVqWqn:-Md0GDjh0uXb_Kut0aTb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f80f14291ef5f1d0a1954dfbb35c1e2a0137bf96/tests/multithreaded/conn/rpma_conn_cfg_set_cq_size.c#L39)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1097)* status: all files reviewed, 10 unresolved discussions (waiting on @ewanglong and @ldorau)

___
*[tests/multithreaded/conn/rpma_conn_cfg_common.h, line 5 at r2](https://reviewable.io/reviews/pmem/rpma/1097#-Md0z96056WrLOIBKiNW:-Md0z9611yO8Q0_Hg55L:bko5eh4) ([raw file](https://github.com/pmem/rpma/blob/328010885ba36a79c18afae8c837d2c61f27ddf6/tests/multithreaded/conn/rpma_conn_cfg_common.h#L5)):*
> ```objc
> 
> /*
>  * rpma_conn_cfg_common.h -- common definition for rpma_conn_cfg_xxx mtt
> ```

xxx -> * tests
mtt -> multithreaded tests
___
*[tests/multithreaded/conn/rpma_conn_cfg_common.h, line 8 at r2](https://reviewable.io/reviews/pmem/rpma/1097#-Md0zN-v3UyPi_TBR9Zj:-Md0zN-v3UyPi_TBR9Zk:b-pc3jd) ([raw file](https://github.com/pmem/rpma/blob/328010885ba36a79c18afae8c837d2c61f27ddf6/tests/multithreaded/conn/rpma_conn_cfg_common.h#L8)):*
> ```objc
>  */
> 
> #ifndef RPMA_CONN_CFG_COMMON
> ```

MTT_...
___
*[tests/multithreaded/conn/rpma_conn_cfg_common.h, line 11 at r2](https://reviewable.io/reviews/pmem/rpma/1097#-Md0zbpx1dOlMOJ4Hj22:-Md0zbpx1dOlMOJ4Hj23:b-s3hmjs) ([raw file](https://github.com/pmem/rpma/blob/328010885ba36a79c18afae8c837d2c61f27ddf6/tests/multithreaded/conn/rpma_conn_cfg_common.h#L11)):*
> ```objc
> #define RPMA_CONN_CFG_COMMON
> 
> #include <librpma.h>
> ```

Not needed?
___
*[tests/multithreaded/conn/rpma_conn_cfg_common.h, line 16 at r2](https://reviewable.io/reviews/pmem/rpma/1097#-Md0zpv825WL1jOVn43p:-Md0zpv825WL1jOVn43q:bpmr0qr) ([raw file](https://github.com/pmem/rpma/blob/328010885ba36a79c18afae8c837d2c61f27ddf6/tests/multithreaded/conn/rpma_conn_cfg_common.h#L16)):*
> ```objc
> #define RPMA_CONN_CFG_COMMON_Q_SIZE_EXP 20
> 
> struct state {
> ```

rpma_conn_cfg_common_state
___
*[tests/multithreaded/conn/rpma_conn_cfg_common.h, line 21 at r2](https://reviewable.io/reviews/pmem/rpma/1097#-Md0zw962kWAxqILG0PD:-Md0zw962kWAxqILG0PE:byuexqa) ([raw file](https://github.com/pmem/rpma/blob/328010885ba36a79c18afae8c837d2c61f27ddf6/tests/multithreaded/conn/rpma_conn_cfg_common.h#L21)):*
> ```objc
> 
> void
> rpma_conn_cfg_common_init(unsigned id, void *prestate, void **state_ptr,
> ```

void rpma_conn_cfg_common_init(...
___
*[tests/multithreaded/conn/rpma_conn_cfg_common.h, line 25 at r2](https://reviewable.io/reviews/pmem/rpma/1097#-Md1--fN43e_Cp-qDcOJ:-Md1--fN43e_Cp-qDcOK:bj8ykts) ([raw file](https://github.com/pmem/rpma/blob/328010885ba36a79c18afae8c837d2c61f27ddf6/tests/multithreaded/conn/rpma_conn_cfg_common.h#L25)):*
> ```objc
> 
> void
> rpma_conn_cfg_common_fini(unsigned id, void *prestate, void **state_ptr,
> ```

void rpma_conn_cfg_common_fini(...
___
*[tests/multithreaded/conn/rpma_conn_cfg_common.h, line 28 at r2](https://reviewable.io/reviews/pmem/rpma/1097#-Md1-3xg0DpzxqXBcynr:-Md1-3xg0DpzxqXBcyns:b-pc3jd) ([raw file](https://github.com/pmem/rpma/blob/328010885ba36a79c18afae8c837d2c61f27ddf6/tests/multithreaded/conn/rpma_conn_cfg_common.h#L28)):*
> ```objc
> 		struct mtt_result *tr);
> 
> #endif /* RPMA_CONN_CFG_COMMON */
> ```

MTT_...
___
*[tests/multithreaded/conn/rpma_conn_cfg_common.c, line 5 at r2](https://reviewable.io/reviews/pmem/rpma/1097#-Md1-6jm-SA_-Ma7bDmI:-Md1-6jm-SA_-Ma7bDmJ:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/328010885ba36a79c18afae8c837d2c61f27ddf6/tests/multithreaded/conn/rpma_conn_cfg_common.c#L5)):*
> ```C
> 
> /*
>  * rpma_conn_cfg_common.c -- common part for rpma_conn_cfg_xxx mtt
> ```

.

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1097)* status: all files reviewed, 11 unresolved discussions (waiting on @ewanglong and @ldorau)

___
*[tests/multithreaded/conn/rpma_conn_cfg_common.h, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/1097#-Md13Jh3260OVUA49Ilu:-Md13Jh3260OVUA49Ilv:b-ft4vyz) ([raw file](https://github.com/pmem/rpma/blob/328010885ba36a79c18afae8c837d2c61f27ddf6/tests/multithreaded/conn/rpma_conn_cfg_common.h#L2)):*
> ```objc
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2021, Intel Corporation */
> ```

Something is wrong here:

```
error: wrong format of SPDX tag in the file: /rpma/tests/multithreaded/conn/rpma_conn_cfg_common.h
Error(s) in copyright headers found!
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1097)* status: all files reviewed, 10 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/conn/rpma_conn_cfg_common.h, line 1 at r2](https://reviewable.io/reviews/pmem/rpma/1097#-Md1N0OtEl64X7aIKFNZ:-Md1N0OtEl64X7aIKFN_:b-clyikx) ([raw file](https://github.com/pmem/rpma/blob/328010885ba36a79c18afae8c837d2c61f27ddf6/tests/multithreaded/conn/rpma_conn_cfg_common.h#L1)):*
> ```
> // SPDX-License-Identifier: BSD-3-Clause
> ```

```
/* SPDX-License-Identifier: BSD-3-Clause */
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1097)* status: all files reviewed, 10 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/multithreaded/conn/rpma_conn_cfg_common.h, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/1097#-Md13Jh3260OVUA49Ilu:-Md1N8xg6GxMcVgkEU7o:b-ri8eml) ([raw file](https://github.com/pmem/rpma/blob/328010885ba36a79c18afae8c837d2c61f27ddf6/tests/multithreaded/conn/rpma_conn_cfg_common.h#L2)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Something is wrong here:

```
error: wrong format of SPDX tag in the file: /rpma/tests/multithreaded/conn/rpma_conn_cfg_common.h
Error(s) in copyright headers found!
```
</blockquote></details>

```
/* SPDX-License-Identifier: BSD-3-Clause */
```

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1097)* status: all files reviewed, 10 unresolved discussions (waiting on @ewanglong and @ldorau)

___
*[tests/multithreaded/conn/rpma_conn_cfg_common.h, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/1097#-Md13Jh3260OVUA49Ilu:-Md1sdB9CvzKH6YwgLBS:b-n1wjxz) ([raw file](https://github.com/pmem/rpma/blob/328010885ba36a79c18afae8c837d2c61f27ddf6/tests/multithreaded/conn/rpma_conn_cfg_common.h#L2)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
/* SPDX-License-Identifier: BSD-3-Clause */
```

</blockquote></details>

```c
/* SPDX-License-Identifier: BSD-3-Clause */
/* Copyright 2021, Intel Corporation */
```

@ldorau :+1: 
Ref: https://www.kernel.org/doc/html/v4.18/process/license-rules.html#license-identifier-syntax

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1097)* status: all files reviewed, 10 unresolved discussions (waiting on @ewanglong)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1097)* status: all files reviewed, 10 unresolved discussions (waiting on @ewanglong)

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1097)* status: 1 of 4 files reviewed, 10 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tests/multithreaded/conn/rpma_conn_cfg_common.h, line 1 at r2](https://reviewable.io/reviews/pmem/rpma/1097#-Md1N0OtEl64X7aIKFNZ:-MdFOR3j0KHuPbFzyy_X:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/328010885ba36a79c18afae8c837d2c61f27ddf6/tests/multithreaded/conn/rpma_conn_cfg_common.h#L1)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> // SPDX-License-Identifier: BSD-3-Clause
> ```

```
/* SPDX-License-Identifier: BSD-3-Clause */
```

</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_cfg_common.h, line 2 at r2](https://reviewable.io/reviews/pmem/rpma/1097#-Md13Jh3260OVUA49Ilu:-MdFOq5h4xboKfZfcLvW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/328010885ba36a79c18afae8c837d2c61f27ddf6/tests/multithreaded/conn/rpma_conn_cfg_common.h#L2)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
/* SPDX-License-Identifier: BSD-3-Clause */
/* Copyright 2021, Intel Corporation */
```

@ldorau :+1: 
Ref: https://www.kernel.org/doc/html/v4.18/process/license-rules.html#license-identifier-syntax
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_cfg_common.h, line 5 at r2](https://reviewable.io/reviews/pmem/rpma/1097#-Md0z96056WrLOIBKiNW:-MdFOSu6Aga9HZWhAltW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/328010885ba36a79c18afae8c837d2c61f27ddf6/tests/multithreaded/conn/rpma_conn_cfg_common.h#L5)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

xxx -> * tests
mtt -> multithreaded tests
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_cfg_common.h, line 8 at r2](https://reviewable.io/reviews/pmem/rpma/1097#-Md0zN-v3UyPi_TBR9Zj:-MdFOArK3KZdOUeCsAYj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/328010885ba36a79c18afae8c837d2c61f27ddf6/tests/multithreaded/conn/rpma_conn_cfg_common.h#L8)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

MTT_...
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_cfg_common.h, line 11 at r2](https://reviewable.io/reviews/pmem/rpma/1097#-Md0zbpx1dOlMOJ4Hj22:-MdFODImBfpOluK_h3MF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/328010885ba36a79c18afae8c837d2c61f27ddf6/tests/multithreaded/conn/rpma_conn_cfg_common.h#L11)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Not needed?
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_cfg_common.h, line 16 at r2](https://reviewable.io/reviews/pmem/rpma/1097#-Md0zpv825WL1jOVn43p:-MdFODxO4Vdr5JfJL7m1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/328010885ba36a79c18afae8c837d2c61f27ddf6/tests/multithreaded/conn/rpma_conn_cfg_common.h#L16)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

rpma_conn_cfg_common_state
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_cfg_common.h, line 21 at r2](https://reviewable.io/reviews/pmem/rpma/1097#-Md0zw962kWAxqILG0PD:-MdFOG8D1kffzhwSc6bJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/328010885ba36a79c18afae8c837d2c61f27ddf6/tests/multithreaded/conn/rpma_conn_cfg_common.h#L21)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

void rpma_conn_cfg_common_init(...
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_cfg_common.h, line 25 at r2](https://reviewable.io/reviews/pmem/rpma/1097#-Md1--fN43e_Cp-qDcOJ:-MdFOGyv6vdobKvYTZmK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/328010885ba36a79c18afae8c837d2c61f27ddf6/tests/multithreaded/conn/rpma_conn_cfg_common.h#L25)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

void rpma_conn_cfg_common_fini(...
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_cfg_common.h, line 28 at r2](https://reviewable.io/reviews/pmem/rpma/1097#-Md1-3xg0DpzxqXBcynr:-MdFOHkP2V6gODalF5IO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/328010885ba36a79c18afae8c837d2c61f27ddf6/tests/multithreaded/conn/rpma_conn_cfg_common.h#L28)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

MTT_...
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_cfg_common.c, line 5 at r2](https://reviewable.io/reviews/pmem/rpma/1097#-Md1-6jm-SA_-Ma7bDmI:-MdFOILw7nfQdkfErabg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/328010885ba36a79c18afae8c837d2c61f27ddf6/tests/multithreaded/conn/rpma_conn_cfg_common.c#L5)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1097)* status: all files reviewed, 10 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/multithreaded/conn/rpma_conn_cfg_common.c, line 23 at r3](https://reviewable.io/reviews/pmem/rpma/1097#-MdG3kb9CKrIiJUmRzdL:-MdG3kb9CKrIiJUmRzdM:b-llwrwf) ([raw file](https://github.com/pmem/rpma/blob/67a45d044a6d7dd6c212a7a57e7c7fb658cc7e73/tests/multithreaded/conn/rpma_conn_cfg_common.c#L23)):*
> ```
> calloc(1, sizeof(struct rpma_conn_cfg_common_state));
> ```

`calloc(1, sizeof(*st));` and it could maybe even fit into the previous line ?:

```
(struct rpma_conn_cfg_common_state *)calloc(1, sizeof(*st));
```

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1097)* status: all files reviewed, 10 unresolved discussions (waiting on @ewanglong and @janekmi)

**Review by ldorau — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1097#-:-MdG4gNd3huf_5TZz30t:bdycpsm)* status: all files reviewed, 10 unresolved discussions (waiting on @ewanglong and @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r3, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1097#-:-MdGJhWgAjfMJP9tEJOQ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1097)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tests/multithreaded/conn/rpma_conn_cfg_common.c, line 23 at r3](https://reviewable.io/reviews/pmem/rpma/1097#-MdG3kb9CKrIiJUmRzdL:-MdGDlij-WEz-4KQXYU4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/67a45d044a6d7dd6c212a7a57e7c7fb658cc7e73/tests/multithreaded/conn/rpma_conn_cfg_common.c#L23)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> calloc(1, sizeof(struct rpma_conn_cfg_common_state));
> ```

`calloc(1, sizeof(*st));` and it could maybe even fit into the previous line ?:

```
(struct rpma_conn_cfg_common_state *)calloc(1, sizeof(*st));
```

</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1097)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1097#-:-MdH2bY44uCPGWm4Hjrr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Pull request merged**
