### PR TITLE
tools: set DIR for the ddio.sh script

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1126)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1126)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/bench_common.sh, line 176 at r2](https://reviewable.io/reviews/pmem/rpma/1126#-MdrN-u73eGImHShoPDv:-MdrN-u73eGImHShoPDw:bnesilf) ([raw file](https://github.com/pmem/rpma/blob/3b75b6a5450dbb2c0006667d6e8e31ae424bd5f6/tools/perf/bench_common.sh#L176)):*
> the remote path...

I think it is more of a remote path. I have confused it with the local one at the beginning.
___
*[tools/perf/ib_read.sh, line 153 at r2](https://reviewable.io/reviews/pmem/rpma/1126#-MdrNTRvE5cxb85lQL_R:-MdrNTRvE5cxb85lQL_S:b-vz7qac) ([raw file](https://github.com/pmem/rpma/blob/3b75b6a5450dbb2c0006667d6e8e31ae424bd5f6/tools/perf/ib_read.sh#L153)):*
> ```Shell
> 	REQUIRED_REMOTE_DIRECT_WRITE_TO_PMEM=0
> 
> 	set_ddio /dev/shm
> ```

Do you have any idea what was the original value of this variable? xD

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1126)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/bench_common.sh, line 176 at r2](https://reviewable.io/reviews/pmem/rpma/1126#-MdrN-u73eGImHShoPDv:-MduMzgG6fBD_sZ-Ph_h:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3b75b6a5450dbb2c0006667d6e8e31ae424bd5f6/tools/perf/bench_common.sh#L176)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

> the remote path...

I think it is more of a remote path. I have confused it with the local one at the beginning.
</blockquote></details>

Done.
___
*[tools/perf/ib_read.sh, line 153 at r2](https://reviewable.io/reviews/pmem/rpma/1126#-MdrNTRvE5cxb85lQL_R:-MduM1SkBI5PnMLGRjgY:b3o1n1r) ([raw file](https://github.com/pmem/rpma/blob/3b75b6a5450dbb2c0006667d6e8e31ae424bd5f6/tools/perf/ib_read.sh#L153)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Do you have any idea what was the original value of this variable? xD
</blockquote></details>

/dev/shm I think

**Review by osalyk — COMMENTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1126)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1126#-:-MdukgNH1A91EPiffld3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1126#-:-MdumLWZ1UOoH0191u5d:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
