### PR TITLE
rpma: cleanup the ROADMAP.md

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/983)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/983)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[ROADMAP.md, line 1 at r1](https://reviewable.io/reviews/pmem/rpma/983#-MXlWQMgCEQRHtCOI-iN:-MXlWQMgCEQRHtCOI-iO:bhns80o) ([raw file](https://github.com/pmem/rpma/blob/cdbec85032344a3e03abee931f5e6895f55cfdbe/ROADMAP.md#L1)):*
I would introduce what is going on with a sentence or two e.g.:

> After the initial stage of development and having a growing community of developers we have decided to move the librpma roadmap fully on GitHub. We are planning to posting there and discussing ideas for future improvements to the library.
>
> Please join us: https://github.com/pmem/rpma/issues
___
*[ROADMAP.md, line 4 at r1](https://reviewable.io/reviews/pmem/rpma/983#-MXlYOhRDv4KnDOIqFF0:-MXlYOhRDv4KnDOIqFF1:bndngkl) ([raw file](https://github.com/pmem/rpma/blob/cdbec85032344a3e03abee931f5e6895f55cfdbe/ROADMAP.md#L4)):*
> ```Markdown
> # The librpma Fio engine roadmap [04/08/2021]
> Legacy content of this file was moved to separate GitHub issues on page:
> https://github.com/pmem/rpma/issues
> ```

The librpma FIO engine is already out there. Please give it a try: https://github.com/axboe/fio

In the meantime, we are still working on new concepts and improvements to the existing engines.

If you feel the vibe, please join us here: https://github.com/pmem/fio
___
*[ROADMAP.md, line 6 at r1](https://reviewable.io/reviews/pmem/rpma/983#-MXlXUxx1pLOYyKoHdra:-MXlXUxx1pLOYyKoHdrb:bqpvtrn) ([raw file](https://github.com/pmem/rpma/blob/cdbec85032344a3e03abee931f5e6895f55cfdbe/ROADMAP.md#L6)):*
> ```Markdown
> https://github.com/pmem/rpma/issues
>  
> Additionally to that, you can find there current issues, feature requests/ideas etc.
> ```

I would drop this sentence.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/983)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[ROADMAP.md, line 1 at r1](https://reviewable.io/reviews/pmem/rpma/983#-MXlWQMgCEQRHtCOI-iN:-MXl_FaI3aZClEPbqdKO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cdbec85032344a3e03abee931f5e6895f55cfdbe/ROADMAP.md#L1)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I would introduce what is going on with a sentence or two e.g.:

> After the initial stage of development and having a growing community of developers we have decided to move the librpma roadmap fully on GitHub. We are planning to posting there and discussing ideas for future improvements to the library.
>
> Please join us: https://github.com/pmem/rpma/issues
</blockquote></details>

Done.
___
*[ROADMAP.md, line 4 at r1](https://reviewable.io/reviews/pmem/rpma/983#-MXlYOhRDv4KnDOIqFF0:-MXl_Nbm1Cozn0fol2xu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cdbec85032344a3e03abee931f5e6895f55cfdbe/ROADMAP.md#L4)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The librpma FIO engine is already out there. Please give it a try: https://github.com/axboe/fio

In the meantime, we are still working on new concepts and improvements to the existing engines.

If you feel the vibe, please join us here: https://github.com/pmem/fio
</blockquote></details>

Done.
___
*[ROADMAP.md, line 6 at r1](https://reviewable.io/reviews/pmem/rpma/983#-MXlXUxx1pLOYyKoHdra:-MXl_lFa-U2Extu8fApR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cdbec85032344a3e03abee931f5e6895f55cfdbe/ROADMAP.md#L6)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I would drop this sentence.
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/983)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[ROADMAP.md, line 4 at r2](https://reviewable.io/reviews/pmem/rpma/983#-MXqCJKQ7Y8kEuoXb6rz:-MXqCJKQ7Y8kEuoXb6s-:b-vy5xs7) ([raw file](https://github.com/pmem/rpma/blob/e76fd5795f6a2486a9aa67305a9a1fcce334b9e8/ROADMAP.md#L4)):*
> ```
> Please join us: https://github.com/pmem/rpma/issues
> ```
Please join us: https://github.com/pmem/rpma/issues if you find any of the items listed there interesting for you (either you expect this item to be added to the library, or you would like to deliver a source code solution for it).
___
*[ROADMAP.md, line 13 at r2](https://reviewable.io/reviews/pmem/rpma/983#-MXqCVRbE9GUe2FkuZEj:-MXqCVRbE9GUe2FkuZEk:b-809yo5) ([raw file](https://github.com/pmem/rpma/blob/e76fd5795f6a2486a9aa67305a9a1fcce334b9e8/ROADMAP.md#L13)):*
> ```
> Please let us know if you find any of the items listed below interesting for you (either you expect this item to be added to the library, or you would like to deliver a source code solution for it).
> ```
I would drop this sentence (move it to the rpma/issues  section)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/983)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi and @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/983)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[ROADMAP.md, line 4 at r2](https://reviewable.io/reviews/pmem/rpma/983#-MXqCJKQ7Y8kEuoXb6rz:-MXqjWsDBW3LM9snTCE0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e76fd5795f6a2486a9aa67305a9a1fcce334b9e8/ROADMAP.md#L4)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Please join us: https://github.com/pmem/rpma/issues
> ```
Please join us: https://github.com/pmem/rpma/issues if you find any of the items listed there interesting for you (either you expect this item to be added to the library, or you would like to deliver a source code solution for it).

</blockquote></details>

Done.
___
*[ROADMAP.md, line 13 at r2](https://reviewable.io/reviews/pmem/rpma/983#-MXqCVRbE9GUe2FkuZEj:-MXqjZhpCraZyQC_3w5J:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e76fd5795f6a2486a9aa67305a9a1fcce334b9e8/ROADMAP.md#L13)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Please let us know if you find any of the items listed below interesting for you (either you expect this item to be added to the library, or you would like to deliver a source code solution for it).
> ```
I would drop this sentence (move it to the rpma/issues  section)
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/983)* status: all files reviewed, 8 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)

___
*[ROADMAP.md, line 2 at r3](https://reviewable.io/reviews/pmem/rpma/983#-MY3fQcl1vtIM7RM1FA6:-MY3fQcl1vtIM7RM1FA7:b-y1ygvf) ([raw file](https://github.com/pmem/rpma/blob/3650da3c0e49f428797dde31b60b30f973a0a7ff/ROADMAP.md#L2)):*
> ```
> We are planning to posting there and discussing ideas for future improvements to the library.
> ```

We are planning to post and discuss ideas about future improvements of the library there.
___
*[ROADMAP.md, line 4 at r3](https://reviewable.io/reviews/pmem/rpma/983#-MY3fode0oGklxp2CGPk:-MY3fodfBcqzAtmRRNWh:boo4s5s) ([raw file](https://github.com/pmem/rpma/blob/3650da3c0e49f428797dde31b60b30f973a0a7ff/ROADMAP.md#L4)):*
> ```
> Please join us: 
> ```

Please join us at: 
___
*[ROADMAP.md, line 4 at r3](https://reviewable.io/reviews/pmem/rpma/983#-MY3fwJl26IlQMVtysxH:-MY3fwJl26IlQMVtysxI:b-hkfrbs) ([raw file](https://github.com/pmem/rpma/blob/3650da3c0e49f428797dde31b60b30f973a0a7ff/ROADMAP.md#L4)):*
> ```
> library, or 
> ```

library or  (no comma)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/983)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[ROADMAP.md, line 2 at r3](https://reviewable.io/reviews/pmem/rpma/983#-MY3fQcl1vtIM7RM1FA6:-MY3w2uM5u6-3N5uhlpv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3650da3c0e49f428797dde31b60b30f973a0a7ff/ROADMAP.md#L2)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> We are planning to posting there and discussing ideas for future improvements to the library.
> ```

We are planning to post and discuss ideas about future improvements of the library there.
</blockquote></details>

Done.
___
*[ROADMAP.md, line 4 at r3](https://reviewable.io/reviews/pmem/rpma/983#-MY3fode0oGklxp2CGPk:-MY3w7Iv63m0keX7dILH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3650da3c0e49f428797dde31b60b30f973a0a7ff/ROADMAP.md#L4)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> Please join us: 
> ```

Please join us at: 
</blockquote></details>

Done.
___
*[ROADMAP.md, line 4 at r3](https://reviewable.io/reviews/pmem/rpma/983#-MY3fwJl26IlQMVtysxH:-MY3wBfz-8fUe-OdyoTh:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3650da3c0e49f428797dde31b60b30f973a0a7ff/ROADMAP.md#L4)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> library, or 
> ```

library or  (no comma)
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/983)* status: all files reviewed, 7 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[ROADMAP.md, line 13 at r4](https://reviewable.io/reviews/pmem/rpma/983#-MY43GQg-ut_loB7yp46:-MY43GQg-ut_loB7yp47:b-5ewaue) ([raw file](https://github.com/pmem/rpma/blob/8d636a66bcb25ce0bca4b9563a4cf5747a28f6b7/ROADMAP.md#L13)):*
> ```
> **Note**: Please take a look at [CONTRIBUTING.md](CONTRIBUTING.md) before you start developing.
> ```
Let's move it before the Fio section to invite people to join the librpma development.

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/983)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @osalyk)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/983)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/983)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[ROADMAP.md, line 13 at r4](https://reviewable.io/reviews/pmem/rpma/983#-MY43GQg-ut_loB7yp46:-MY46flt7DG0OjjDxuKi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8d636a66bcb25ce0bca4b9563a4cf5747a28f6b7/ROADMAP.md#L13)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> **Note**: Please take a look at [CONTRIBUTING.md](CONTRIBUTING.md) before you start developing.
> ```
Let's move it before the Fio section to invite people to join the librpma development.  
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/983)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @janekmi)

**Review by grom72 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/983#-:-MY4Ltld3VQN2OEpF1jo:bdycpsm)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/983#-:-MY4UBme3Pti5Z6fmMwS:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/983#-:-MY4o18554a7RKW_KfFK:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/983)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/983#-:-MY5SMc92VkU-Y9oQGjo:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
