### PR TITLE
doc: update perf-tuning.md for ICX

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1629)

### CODE REVIEW

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1629#-:-MypjRju5yqJj4H_yU20:bg7igkv)* status: 0 of 1 files reviewed, all discussions resolved

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1629)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1629#-MyqEVN58zwebGuPAQOc:-MyqEVN58zwebGuPAQOd:bke6vwm) (no related file):*
It does not seem to be the same file ... ? 

---
___
*[documentation/perf-tuning.md, line 68 at r1](https://reviewable.io/reviews/pmem/rpma/1629#-MyqF687-QdmNM_DvMd9:-MyqF687-QdmNM_DvMdA:bfrf67o) ([raw file](https://github.com/pmem/rpma/blob/ede03cb4cf5478b508300fd492e9dfbe0f94a5fc/documentation/perf-tuning.md#L68)):*
> ```Markdown
> 
> * [1.1] [Optimizing Computer Applications for Latency: Part 1: Configuring the Hardware][opt-part-1]
> * [1.2] [Intel: Power Management States: P-States, C-States, and Package C-States][power-states]
> ```

There is something different on the pmem.io:

```
#### References

* [1.1] [Optimizing Computer Applications for Latency: Part 1: Configuring the Hardware][optimizing-computer]
* [1.2] [Intel: Power Management States: P-States, C-States, and Package C-States][management-states]
* [1.3] [Intel® Optane™ Persistent Memory 200 Series Brief][persistent-memory]
* [1.4] [Intel® Turbo Boost Technology 2.0 - Higher Performance When You Need It Most][turbo-boost]

[optimizing-computer]: https://software.intel.com/content/www/us/en/develop/articles/optimizing-computer-applications-for-latency-part-1-configuring-the-hardware.html
[management-states]: https://software.intel.com/content/www/us/en/develop/articles/power-management-states-p-states-c-states-and-package-c-states.html
[persistent-memory]: https://www.intel.com/content/www/us/en/products/docs/memory-storage/optane-persistent-memory/optane-persistent-memory-200-series-brief.html
[turbo-boost]: https://www.intel.com/content/www/us/en/architecture-and-technology/turbo-boost/turbo-boost-technology.html

```



_Code quote:_
```Markdown
### References

* [1.1] [Optimizing Computer Applications for Latency: Part 1: Configuring the Hardware][opt-part-1]
* [1.2] [Intel: Power Management States: P-States, C-States, and Package C-States][power-states]
* [1.3] [Intel® Optane™ Persistent Memory 200 Series Brief][pmem-200-brief]
* [1.4] [Intel® Turbo Boost Technology 2.0 - Higher Performance When You Need It Most][turbo]

[opt-part-1]: https://software.intel.com/content/www/us/en/develop/articles/optimizing-computer-applications-for-latency-part-1-configuring-the-hardware.html
[power-states]: https://software.intel.com/content/www/us/en/develop/articles/power-management-states-p-states-c-states-and-package-c-states.html
[pmem-200-brief]: https://www.intel.com/content/www/us/en/products/docs/memory-storage/optane-persistent-memory/optane-persistent-memory-200-series-brief.html
[turbo]: https://www.intel.com/content/www/us/en/architecture-and-technology/turbo-boost/turbo-boost-technology.html

## CPU
```

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1629)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1629#-MyqEVN58zwebGuPAQOc:-MyqOPfRB2eC9OWvxF54:bo0pbb6) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It does not seem to be the same file ... ? 
</blockquote></details>

It is OK

---
___
*[documentation/perf-tuning.md, line 68 at r1](https://reviewable.io/reviews/pmem/rpma/1629#-MyqF687-QdmNM_DvMd9:-MyqOEnpC51TGpZdN9LJ:b-95puag) ([raw file](https://github.com/pmem/rpma/blob/ede03cb4cf5478b508300fd492e9dfbe0f94a5fc/documentation/perf-tuning.md#L68)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

There is something different on the pmem.io:

```
#### References

* [1.1] [Optimizing Computer Applications for Latency: Part 1: Configuring the Hardware][optimizing-computer]
* [1.2] [Intel: Power Management States: P-States, C-States, and Package C-States][management-states]
* [1.3] [Intel® Optane™ Persistent Memory 200 Series Brief][persistent-memory]
* [1.4] [Intel® Turbo Boost Technology 2.0 - Higher Performance When You Need It Most][turbo-boost]

[optimizing-computer]: https://software.intel.com/content/www/us/en/develop/articles/optimizing-computer-applications-for-latency-part-1-configuring-the-hardware.html
[management-states]: https://software.intel.com/content/www/us/en/develop/articles/power-management-states-p-states-c-states-and-package-c-states.html
[persistent-memory]: https://www.intel.com/content/www/us/en/products/docs/memory-storage/optane-persistent-memory/optane-persistent-memory-200-series-brief.html
[turbo-boost]: https://www.intel.com/content/www/us/en/architecture-and-technology/turbo-boost/turbo-boost-technology.html

```
</blockquote></details>

OK, it is OK :-)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1629#-:-MyqOSOQ-775mnNPNPmr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
