### PR TITLE
examples: use shared completion channel in example 13 (server part)

### PR DESCRIPTION
**Pull request by osalyk**
- [x] #1705 

This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1704)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1704)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @ldorau and @osalyk)

___
*[`examples/CMakeLists.txt` line 107 at r1](https://reviewable.io/reviews/pmem/rpma/1704#-N0ejei86pQ7viWAPiib:-N0ejei86pQ7viWAPiic:b-y1mdn0) ([raw file](https://github.com/pmem/rpma/blob/844d711cfbf6c19152db13982bcc4b1a8fc2bcf8/examples/CMakeLists.txt#L107)):*
> ```CMake
> add_example(NAME 01-connection BIN client
> 	SRCS 01-connection/client.c)
> add_example(NAME 02-read-to-volatile BIN server USE_LIBIBVERBS
> ```

Please add `common/common-conn.c` and `USE_LIBIBVERBS` inside `add_example()` for all examples.



_Code quote:_
```CMake
add_example(NAME 02-read-to-volatile BIN server USE_LIBIBVERBS
	SRCS 02-read-to-volatile/server.c common/common-conn.c)
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1704)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[`examples/common/common-conn.c` line 214 at r1](https://reviewable.io/reviews/pmem/rpma/1704#-N0eoXOx6LEzV8IApj-b:-N0eoXOy6vB6ph_TS2IG:brohbmr) ([raw file](https://github.com/pmem/rpma/blob/844d711cfbf6c19152db13982bcc4b1a8fc2bcf8/examples/common/common-conn.c#L214)):*
> ```C
> 		return ret;
> 
> 	char *func = (opcode == IBV_WC_SEND)? "send" : "recv";
> ```

`char *name` or `char *func_name`



_Code quote:_
```C
char *func
```
___
*[`examples/common/common-conn.c` line 229 at r1](https://reviewable.io/reviews/pmem/rpma/1704#-N0eof2T3wbGUpX3ncI_:-N0eof2T3wbGUpX3ncIa:b-pp4w9n) ([raw file](https://github.com/pmem/rpma/blob/844d711cfbf6c19152db13982bcc4b1a8fc2bcf8/examples/common/common-conn.c#L229)):*
> ```C
> 		return -1;
> 	}
> 	return 0;
> ```

one empty line in between, please



_Code quote:_
```C
	}
	return 0;
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1704)* status: 2 of 4 files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[`examples/CMakeLists.txt` line 107 at r1](https://reviewable.io/reviews/pmem/rpma/1704#-N0ejei86pQ7viWAPiib:-N0ez-3Z97gSki1-p51m:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/844d711cfbf6c19152db13982bcc4b1a8fc2bcf8/examples/CMakeLists.txt#L107)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please add `common/common-conn.c` and `USE_LIBIBVERBS` inside `add_example()` for all examples.
</blockquote></details>

Done.
___
*[`examples/common/common-conn.c` line 214 at r1](https://reviewable.io/reviews/pmem/rpma/1704#-N0eoXOx6LEzV8IApj-b:-N0expTA6nPyJGCSTFa4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/844d711cfbf6c19152db13982bcc4b1a8fc2bcf8/examples/common/common-conn.c#L214)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`char *name` or `char *func_name`
</blockquote></details>

Done.
___
*[`examples/common/common-conn.c` line 229 at r1](https://reviewable.io/reviews/pmem/rpma/1704#-N0eof2T3wbGUpX3ncI_:-N0ey8l4CQMULAk_yPcL:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/844d711cfbf6c19152db13982bcc4b1a8fc2bcf8/examples/common/common-conn.c#L229)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

one empty line in between, please
</blockquote></details>

Done.

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1704)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[`examples/common/common-conn.h` line 75 at r1](https://reviewable.io/reviews/pmem/rpma/1704#-N0f63I9BYlXQLiCVwE1:-N0f63I9BYlXQLiCVwE2:bvqaob) ([raw file](https://github.com/pmem/rpma/blob/844d711cfbf6c19152db13982bcc4b1a8fc2bcf8/examples/common/common-conn.h#L75)):*
> ```objc
> 
> int wait_and_validate_completion(struct rpma_conn *conn, struct ibv_wc *wc, struct rpma_cq *cq,
> 		enum ibv_wc_opcode opcode);
> ```

It will be more beneficial and universal to return information about which rpma_cq delivers wc
See: https://github.com/pmem/rpma/issues/1700
I suggest reordering arguments: inputs, parameters, outputs

BTW do we need wc and cq outside this function?
If not we should remove them from API (``*wc``, ``*cq``).



_Suggestion:_
```objc
int wait_and_validate_completion(struct rpma_conn *conn, enum ibv_wc_opcode expected_opcode, 
struct ibv_wc *wc, bool *is_rcq);
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1704)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1704)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1704)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`examples/common/common-conn.h` line 75 at r1](https://reviewable.io/reviews/pmem/rpma/1704#-N0f63I9BYlXQLiCVwE1:-N0f7EF50n8hAWUkIP6T:b32v57) ([raw file](https://github.com/pmem/rpma/blob/844d711cfbf6c19152db13982bcc4b1a8fc2bcf8/examples/common/common-conn.h#L75)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

It will be more beneficial and universal to return information about which rpma_cq delivers wc
See: https://github.com/pmem/rpma/issues/1700
I suggest reordering arguments: inputs, parameters, outputs

BTW do we need wc and cq outside this function?
If not we should remove them from API (``*wc``, ``*cq``).
</blockquote></details>

+1

**Review by ldorau — COMMENTED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1704)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1704)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — CHANGES_REQUESTED** [review]
:goat: 

> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1704#-:-N0fU6kqAM1evkdpiq7K:bdycpsm)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[`examples/common/common-conn.c` line 216 at r2](https://reviewable.io/reviews/pmem/rpma/1704#-N0fTtc-Dqmzfqn7yDm1:-N0fTtc-Dqmzfqn7yDm2:b6y0u7f) ([raw file](https://github.com/pmem/rpma/blob/d7cdd115283983aec2e6d4c8b4ccd485ec7609e5/examples/common/common-conn.c#L216)):*
> ```C
> 	char *func_name = (opcode == IBV_WC_SEND)? "send" : "recv";
> 	if (wc->status != IBV_WC_SUCCESS) {
> 		(void) fprintf(stderr, "rpma_%s() failed: %s\n",
> ```

We have a new line length limit -> chars



_Suggestion:_
```C
		(void) fprintf(stderr, "rpma_%s() failed: %s\n", func_name,
			ibv_wc_status_str(wc->status));
```
___
*[`examples/common/common-conn.c` line 222 at r2](https://reviewable.io/reviews/pmem/rpma/1704#-N0fU2Gt3fyMaXo4ihLj:-N0fU2Gt3fyMaXo4ihLk:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/d7cdd115283983aec2e6d4c8b4ccd485ec7609e5/examples/common/common-conn.c#L222)):*
> ```C
> 
> 	if (wc->opcode != opcode) {
> 		(void) fprintf(stderr,
> ```

.



_Code quote:_
```C
		(void) fprintf(stderr,
				"unexpected wc.opcode value "
				"(0x%" PRIXPTR " != 0x%" PRIXPTR ")\n",
				(uintptr_t)wc->opcode,
				(uintptr_t)opcode);
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1704)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[`examples/common/common-conn.c` line 216 at r2](https://reviewable.io/reviews/pmem/rpma/1704#-N0fTtc-Dqmzfqn7yDm1:-N0iePugBojAy4J_aCvM:b-jvtz6h) ([raw file](https://github.com/pmem/rpma/blob/d7cdd115283983aec2e6d4c8b4ccd485ec7609e5/examples/common/common-conn.c#L216)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

We have a new line length limit -> chars
</blockquote></details>

The limit is 100 chars now.
___
*[`examples/common/common-conn.c` line 222 at r2](https://reviewable.io/reviews/pmem/rpma/1704#-N0fU2Gt3fyMaXo4ihLj:-N0ieY600B9R5FPb8GLF:b-jvtz6h) ([raw file](https://github.com/pmem/rpma/blob/d7cdd115283983aec2e6d4c8b4ccd485ec7609e5/examples/common/common-conn.c#L222)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

The limit is 100 chars now.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1704)* status: 2 of 4 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`examples/common/common-conn.c` line 216 at r2](https://reviewable.io/reviews/pmem/rpma/1704#-N0fTtc-Dqmzfqn7yDm1:-N0ig3N27dkC1hyHWDuz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d7cdd115283983aec2e6d4c8b4ccd485ec7609e5/examples/common/common-conn.c#L216)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The limit is 100 chars now.
</blockquote></details>

Done.
___
*[`examples/common/common-conn.c` line 222 at r2](https://reviewable.io/reviews/pmem/rpma/1704#-N0fU2Gt3fyMaXo4ihLj:-N0igkaXAK-fQ8wXRdGg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d7cdd115283983aec2e6d4c8b4ccd485ec7609e5/examples/common/common-conn.c#L222)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The limit is 100 chars now.
</blockquote></details>

Done.

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1704#-:-N0iiOe57pgT_UQkAZ60:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1704)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1704#-:-N0il99O2EqNDOJAqWYT:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
