### PR TITLE
doc: improve the documentation to rpma... functions

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/430)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/430)* status: all files reviewed, 6 unresolved discussions (waiting on @osalyk)

___
*[src/include/librpma.h, line 1031 at r1](https://reviewable.io/reviews/pmem/rpma/430#-MHzy9vF9r5c3Cc2V94h:-MHzy9vF9r5c3Cc2V94i:b-8d2jlm) ([raw file](https://github.com/pmem/rpma/blob/458c2d5b7cdce023b4ec788f94d2dadd8b6939e9/src/include/librpma.h#L1031)):*
> ```objc
>  *
>  * DESCRIPTION
>  * Initialize the read operation (transferring data from
> ```

`rpma_read() initializes ...`
___
*[src/include/librpma.h, line 1066 at r1](https://reviewable.io/reviews/pmem/rpma/430#-MHzyGZEC-6o4kwZk2wa:-MHzyGZEC-6o4kwZk2wb:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/458c2d5b7cdce023b4ec788f94d2dadd8b6939e9/src/include/librpma.h#L1066)):*
> ```objc
>  *
>  * DESCRIPTION
>  * Initialize the write operation (transferring data from
> ```

.
___
*[src/include/librpma.h, line 1103 at r1](https://reviewable.io/reviews/pmem/rpma/430#-MHzyHa51ZMrLo90OxHL:-MHzyHa51ZMrLo90OxHM:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/458c2d5b7cdce023b4ec788f94d2dadd8b6939e9/src/include/librpma.h#L1103)):*
> ```objc
>  *
>  * DESCRIPTION
>  * Initialize the atomic write operation (transferring data from
> ```

.
___
*[src/include/librpma.h, line 1155 at r1](https://reviewable.io/reviews/pmem/rpma/430#-MHzyKUlBAfc2wZgB0tU:-MHzyKUlBAfc2wZgB0tV:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/458c2d5b7cdce023b4ec788f94d2dadd8b6939e9/src/include/librpma.h#L1155)):*
> ```objc
>  *
>  * DESCRIPTION
>  * Initialize the flush operation (finalizing a transfer of data to
> ```

.
___
*[src/include/librpma.h, line 1194 at r1](https://reviewable.io/reviews/pmem/rpma/430#-MHzyLKL7SegMs9Lgvj2:-MHzyLKL7SegMs9Lgvj3:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/458c2d5b7cdce023b4ec788f94d2dadd8b6939e9/src/include/librpma.h#L1194)):*
> ```objc
>  *
>  * DESCRIPTION
>  * Initialize the send operation which transfers a message from the local
> ```

.
___
*[src/include/librpma.h, line 1224 at r1](https://reviewable.io/reviews/pmem/rpma/430#-MHzyMbc2cFCl15-wTRe:-MHzyMbc2cFCl15-wTRf:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/458c2d5b7cdce023b4ec788f94d2dadd8b6939e9/src/include/librpma.h#L1224)):*
> ```objc
>  *
>  * DESCRIPTION
>  * Initialize the receive operation which prepares a buffer for a message
> ```

.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/430)* status: all files reviewed, 6 unresolved discussions (waiting on @ldorau)

___
*[src/include/librpma.h, line 1031 at r1](https://reviewable.io/reviews/pmem/rpma/430#-MHzy9vF9r5c3Cc2V94h:-MI-JQ9dBDbNp6lPXk4H:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/458c2d5b7cdce023b4ec788f94d2dadd8b6939e9/src/include/librpma.h#L1031)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`rpma_read() initializes ...`
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1066 at r1](https://reviewable.io/reviews/pmem/rpma/430#-MHzyGZEC-6o4kwZk2wa:-MI-JU8m6fe0iQjNT9A6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/458c2d5b7cdce023b4ec788f94d2dadd8b6939e9/src/include/librpma.h#L1066)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1103 at r1](https://reviewable.io/reviews/pmem/rpma/430#-MHzyHa51ZMrLo90OxHL:-MI-JY4iDOV4a7K4Zo4O:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/458c2d5b7cdce023b4ec788f94d2dadd8b6939e9/src/include/librpma.h#L1103)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1155 at r1](https://reviewable.io/reviews/pmem/rpma/430#-MHzyKUlBAfc2wZgB0tU:-MI-JfK_-Tul7Ve4265H:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/458c2d5b7cdce023b4ec788f94d2dadd8b6939e9/src/include/librpma.h#L1155)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1194 at r1](https://reviewable.io/reviews/pmem/rpma/430#-MHzyLKL7SegMs9Lgvj2:-MI-JjQ7BAvOysBNz7b-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/458c2d5b7cdce023b4ec788f94d2dadd8b6939e9/src/include/librpma.h#L1194)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1224 at r1](https://reviewable.io/reviews/pmem/rpma/430#-MHzyMbc2cFCl15-wTRe:-MI-JnPV-p1d2059lfZc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/458c2d5b7cdce023b4ec788f94d2dadd8b6939e9/src/include/librpma.h#L1224)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/430)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
@osalyk please rebase

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/430#-:-MI2t0yg7kDuzXt0U1vK:bqeco5y)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
Done.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/430#-:-MI2uUDq8V-TmZ6X5QI2:b-896fix)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/430)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
@grom72 please review

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/430#-:-MI384JMCUovNL6b3tIc:bgjoyzx)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/430#-:-MI3XOw-EnlUCzHpNZTp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
@ldorau shall we use initiates instead of initializes for every function that starts some operation?
we can initialize a structure for read operation but we initiate the read operation

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/430#-:-MI4JDJG4AopeEUlDuxx:b-36sic5)* status: all files reviewed, 6 unresolved discussions (waiting on @osalyk)

___
*[src/include/librpma.h, line 1125 at r4](https://reviewable.io/reviews/pmem/rpma/430#-MI4ILKz5JRTesXJr8J1:-MI4ILKz5JRTesXJr8J2:b-4z4mq4) ([raw file](https://github.com/pmem/rpma/blob/649ff6a92290e17d6d082ec9205844c0edb2f5cb/src/include/librpma.h#L1125)):*
> ```
> initializes
> ```
initiates
___
*[src/include/librpma.h, line 1160 at r4](https://reviewable.io/reviews/pmem/rpma/430#-MI4IP4Y8B_BWBF7g83Q:-MI4IP4Y8B_BWBF7g83R:b-4z4mq4) ([raw file](https://github.com/pmem/rpma/blob/649ff6a92290e17d6d082ec9205844c0edb2f5cb/src/include/librpma.h#L1160)):*
> ```
> initializes
> ```
initiates
___
*[src/include/librpma.h, line 1197 at r4](https://reviewable.io/reviews/pmem/rpma/430#-MI4JYOP2tOgV0FR9-lR:-MI4JYOP2tOgV0FR9-lS:byzpjkz) ([raw file](https://github.com/pmem/rpma/blob/649ff6a92290e17d6d082ec9205844c0edb2f5cb/src/include/librpma.h#L1197)):*
> ```
> initializes
> ```
i
___
*[src/include/librpma.h, line 1249 at r4](https://reviewable.io/reviews/pmem/rpma/430#-MI4Iz4IEz2pgpbrkRuE:-MI4Iz4IEz2pgpbrkRuF:b-4z4mq4) ([raw file](https://github.com/pmem/rpma/blob/649ff6a92290e17d6d082ec9205844c0edb2f5cb/src/include/librpma.h#L1249)):*
> ```
> initializes
> ```
initiates
___
*[src/include/librpma.h, line 1288 at r4](https://reviewable.io/reviews/pmem/rpma/430#-MI4Jc98AAWpJkLYQte3:-MI4Jc98AAWpJkLYQte4:byzpjjc) ([raw file](https://github.com/pmem/rpma/blob/649ff6a92290e17d6d082ec9205844c0edb2f5cb/src/include/librpma.h#L1288)):*
> ```
> initializes
> ```
.
___
*[src/include/librpma.h, line 1320 at r4](https://reviewable.io/reviews/pmem/rpma/430#-MI4IXY89ToKZyKpSW0o:-MI4IXY9C0EwrP4tPlLV:b-4z4mq4) ([raw file](https://github.com/pmem/rpma/blob/649ff6a92290e17d6d082ec9205844c0edb2f5cb/src/include/librpma.h#L1320)):*
> ```
> initializes
> ```
initiates

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/430#-:-MI4KU6CCv_2Vqmy6q0A:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/430)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/430)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/430)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[src/include/librpma.h, line 1197 at r4](https://reviewable.io/reviews/pmem/rpma/430#-MI4JYOP2tOgV0FR9-lR:-MI57Zw_8y7f9yvWKGdV:b-imifsb) ([raw file](https://github.com/pmem/rpma/blob/649ff6a92290e17d6d082ec9205844c0edb2f5cb/src/include/librpma.h#L1197)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> initializes
> ```
i
</blockquote></details>

initiates

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/430)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[src/include/librpma.h, line 1125 at r4](https://reviewable.io/reviews/pmem/rpma/430#-MI4ILKz5JRTesXJr8J1:-MI57vvt7bhd1ZbEmkiS:b-8fx2u7) ([raw file](https://github.com/pmem/rpma/blob/649ff6a92290e17d6d082ec9205844c0edb2f5cb/src/include/librpma.h#L1125)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> initializes
> ```
initiates
</blockquote></details>

:+1: 
___
*[src/include/librpma.h, line 1160 at r4](https://reviewable.io/reviews/pmem/rpma/430#-MI4IP4Y8B_BWBF7g83Q:-MI57yGx09aaipGJqtdl:b-8fx2u7) ([raw file](https://github.com/pmem/rpma/blob/649ff6a92290e17d6d082ec9205844c0edb2f5cb/src/include/librpma.h#L1160)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> initializes
> ```
initiates
</blockquote></details>

:+1:

**Review by ldorau — COMMENTED** [review]
I think we will fix that in all places in a separate PR

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/430#-:-MI5uu1o7Mx3wUHC2SMC:bsebmjr)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/430)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[src/include/librpma.h, line 1125 at r4](https://reviewable.io/reviews/pmem/rpma/430#-MI4ILKz5JRTesXJr8J1:-MI5vZPk8mcJfwWuvuhd:bunqm94) ([raw file](https://github.com/pmem/rpma/blob/649ff6a92290e17d6d082ec9205844c0edb2f5cb/src/include/librpma.h#L1125)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

We will fix that in all places in a separate PR.
___
*[src/include/librpma.h, line 1160 at r4](https://reviewable.io/reviews/pmem/rpma/430#-MI4IP4Y8B_BWBF7g83Q:-MI5vbmBAgC8nDVKCxfp:b5kkv1e) ([raw file](https://github.com/pmem/rpma/blob/649ff6a92290e17d6d082ec9205844c0edb2f5cb/src/include/librpma.h#L1160)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

We will fix that in all places in a separate PR.
___
*[src/include/librpma.h, line 1197 at r4](https://reviewable.io/reviews/pmem/rpma/430#-MI4JYOP2tOgV0FR9-lR:-MI5vdJx0jzsTa5kYcRq:b5kkv1e) ([raw file](https://github.com/pmem/rpma/blob/649ff6a92290e17d6d082ec9205844c0edb2f5cb/src/include/librpma.h#L1197)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

initiates
</blockquote></details>

We will fix that in all places in a separate PR.

**Pull request merged**
