### PR TITLE
tools: take out the menu from the layout to a dedicated file (fix)

### PR DESCRIPTION
**Pull request by janekmi**
Ref: #833

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/843)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/843)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/templates/.gitignore, line 6 at r1](https://reviewable.io/reviews/pmem/rpma/843#-MSdSNbV4vKFBoeB49FF:-MSdSNbV4vKFBoeB49FG:bg38ac3) ([raw file](https://github.com/pmem/rpma/blob/21d6896cbdecd20dc1a7941899474a25703c445c/tools/templates/.gitignore#L6)):*
> ```ignore
> !appendices.md
> !report_header.md
> !report_menu.html
> ```

Why  report-menu.html file od excluded

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/843)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/templates/.gitignore, line 6 at r1](https://reviewable.io/reviews/pmem/rpma/843#-MSdSNbV4vKFBoeB49FF:-MSe0VT57kZ_NEgvJu9S:b-vxrr4q) ([raw file](https://github.com/pmem/rpma/blob/21d6896cbdecd20dc1a7941899474a25703c445c/tools/templates/.gitignore#L6)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Why  report-menu.html file od excluded 
</blockquote></details>

Because of the upper level .gitignore which ignores all files matching `report_*` expression.
I know the tools directory is messy and requires consideration and imposing a good structure.

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/843)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/843#-:-MSfnVCT7gGxUJfIXqoC:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/843#-:-MSgOleV1xLob9xVeWK8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
