### PR TITLE
common: standardize RDMA configuration variable names

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1814)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1814)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[`CMakeLists.txt` line 49 at r1](https://reviewable.io/reviews/pmem/rpma/1814#-N3yN4Xy0sdqIWPwFSWd:-N3yTXLr4bSmB531Sh6I:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/743550404ebf3fb29aaaedac2a45c403623ea212/CMakeLists.txt#L49)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

a configured RDMA-capable network interface
</blockquote></details>

Done.
___
*[`tests/CMakeLists.txt` line 32 at r1](https://reviewable.io/reviews/pmem/rpma/1814#-N3yNqUBCmBjjyqyTD1d:-N3yWPOK8ujpeMQXY8bh:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/743550404ebf3fb29aaaedac2a45c403623ea212/tests/CMakeLists.txt#L32)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It does not have to be SoftRoCE. It can be also a real RDMA HW. The whole message should be changed accordingly.
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1814)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`tests/CMakeLists.txt` line 33 at r2](https://reviewable.io/reviews/pmem/rpma/1814#-N3zXN9v70KmKKgzCygg:-N40pqaE9QgnPSwscDqv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6824e5b3395a074da5ed953a66506490c545fec1/tests/CMakeLists.txt#L33)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

a configured RDMA-capable network interface
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1814)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1814#-:-N41Ic4l-favupjSwqdO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1814#-:-N41ud-B5maYsCbsuHve:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1814)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 4 of 6 files at r1, 1 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1814#-:-N42ZBQo6aHd-PJuOrJ2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1814)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
