### PR TITLE
test: add missing rpma_conn_send tests

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/883)

### CODE REVIEW

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/883)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
The CodeCov report is OK now:
https://codecov.io/gh/pmem/rpma/tree/065f7b224f148260453cbd7e11a6964b9cfa7d45

:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/883#-:-MTKR3Eg5YGs2CQLKqlo:b2a8clb)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/883#-:-MTK_lZ_210Wh_nLkeof:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/883)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
