### PR TITLE
common: tools: benchmarking step-by-step

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/606)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/606)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tools/BENCHMARKING.md, line 7 at r1](https://reviewable.io/reviews/pmem/rpma/606#-MNT-lkuBvYWnDEIRv-a:-MNT-lkv6j4SlSUhB4og:b2nd3nd) ([raw file](https://github.com/pmem/rpma/blob/80ce54073291134d620a3cc6d8588bbd9de7bafc/tools/BENCHMARKING.md#L7)):*
> ```
> a RPMA read
> ```

the ...
___
*[tools/BENCHMARKING.md, line 11 at r1](https://reviewable.io/reviews/pmem/rpma/606#-MNT-tSy5H-o6nsVXV9B:-MNT-tSy5H-o6nsVXV9C:b7bkslh) ([raw file](https://github.com/pmem/rpma/blob/80ce54073291134d620a3cc6d8588bbd9de7bafc/tools/BENCHMARKING.md#L11)):*
> ```
> vaiours
> ```

various
___
*[tools/BENCHMARKING.md, line 14 at r1](https://reviewable.io/reviews/pmem/rpma/606#-MNT029IDtrWk7XQXk3x:-MNT029IDtrWk7XQXk3y:b-hl6eyr) ([raw file](https://github.com/pmem/rpma/blob/80ce54073291134d620a3cc6d8588bbd9de7bafc/tools/BENCHMARKING.md#L14)):*
> ```
>  XXX
> ```

Is it a draft PR ?

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/606)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[tools/BENCHMARKING.md, line 32 at r1](https://reviewable.io/reviews/pmem/rpma/606#-MNT0LMH8gXMKIMWjEhB:-MNT0LMH8gXMKIMWjEhC:bx7jr0o) ([raw file](https://github.com/pmem/rpma/blob/80ce54073291134d620a3cc6d8588bbd9de7bafc/tools/BENCHMARKING.md#L32)):*
> ```
> vaiours
> ```

.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/606)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[tools/BENCHMARKING.md, line 7 at r1](https://reviewable.io/reviews/pmem/rpma/606#-MNT-lkuBvYWnDEIRv-a:-MNT4y9R6qnMGaWwqr3U:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/80ce54073291134d620a3cc6d8588bbd9de7bafc/tools/BENCHMARKING.md#L7)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> a RPMA read
> ```

the ...
</blockquote></details>

Done.
___
*[tools/BENCHMARKING.md, line 11 at r1](https://reviewable.io/reviews/pmem/rpma/606#-MNT-tSy5H-o6nsVXV9B:-MNT53UZ9xjUy2TIHgMv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/80ce54073291134d620a3cc6d8588bbd9de7bafc/tools/BENCHMARKING.md#L11)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> vaiours
> ```

various
</blockquote></details>

Done.
___
*[tools/BENCHMARKING.md, line 14 at r1](https://reviewable.io/reviews/pmem/rpma/606#-MNT029IDtrWk7XQXk3x:-MNT4BPn07ePf3-76ewr:bnh037q) ([raw file](https://github.com/pmem/rpma/blob/80ce54073291134d620a3cc6d8588bbd9de7bafc/tools/BENCHMARKING.md#L14)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  XXX
> ```

Is it a draft PR ?
</blockquote></details>

Nope. This is a placeholder for the exact tool name to come.
___
*[tools/BENCHMARKING.md, line 32 at r1](https://reviewable.io/reviews/pmem/rpma/606#-MNT0LMH8gXMKIMWjEhB:-MNT53us4aGh43KfSFvl:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/80ce54073291134d620a3cc6d8588bbd9de7bafc/tools/BENCHMARKING.md#L32)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> vaiours
> ```

.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/606)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/606)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/BENCHMARKING.md, line 5 at r2](https://reviewable.io/reviews/pmem/rpma/606#-MNTLvPR0WQo0YUW2hMB:-MNTLvPS2LqOOhyy6WqG:bfqdys1) ([raw file](https://github.com/pmem/rpma/blob/0257ca9d3bc67157b96b449972c4d027c59066d6/tools/BENCHMARKING.md#L5)):*
> ```
> As a baseline are used the generally accepted tools like `ib_read_lat`, `ib_read_bw` etc. 
> ```

As a baseline the generally accepted tools like `ib_read_lat`, `ib_read_bw` etc. are used  ...

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/606)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/BENCHMARKING.md, line 5 at r2](https://reviewable.io/reviews/pmem/rpma/606#-MNTLvPR0WQo0YUW2hMB:-MNTO2zL3oGb_WQn09ui:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0257ca9d3bc67157b96b449972c4d027c59066d6/tools/BENCHMARKING.md#L5)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> As a baseline are used the generally accepted tools like `ib_read_lat`, `ib_read_bw` etc. 
> ```

As a baseline the generally accepted tools like `ib_read_lat`, `ib_read_bw` etc. are used  ...
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/606#-:-MNTOFKX9L4y7Mpzh101:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
