### PR TITLE
test: add tests for the Executor runner

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #1470 

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1448)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
12 new tests pass:

```
platform linux -- Python 3.10.1, pytest-6.2.5, py-1.11.0, pluggy-0.13.1
rootdir: /mnt/files/repos/rpma
collected 12 items                                                                                                                               

tools/perf/tests/lib/benchmark/runner/test_base_run.py ............      [100%]

===== 12 passed in 0.03s =
```

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1448#-:-MrSUeiPAdvUohto_tJU:b7r91v6)* status: 0 of 5 files reviewed, all discussions resolved

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 5 files at r3, 5 of 5 files at r4, 4 of 5 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1448)* status: 9 of 10 files reviewed, 5 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1448#-Ms65ObSEv0gsQNRq7wc:-Ms65ObT4tKi9OWOKMCU:b-4helnp) (no related file):*
We should not go too far with these tests as runner.run() shall be testes separately
Following tests are required:
- Positive test cases for FioRunner and IbReadRunner (as they are)
- Negative test case with unknown Runner -> benchmark.oneseries['tool'] = None, and 'Unknown runner'
- Negative test case with  benchmark.oneseries without 'tool'
The rest shall be tested on the runner level. 

---
___
*[tools/perf/tests/lib/benchmark/runner/test_executor_run.py, line 139 at r5](https://reviewable.io/reviews/pmem/rpma/1448#-Ms6AiS53qPEe_S74hSb:-Ms6AiS53qPEe_S74hSc:b-4phnih) ([raw file](https://github.com/pmem/rpma/blob/b64003efd910b92e8604171cdf134fed31249855/tools/perf/tests/lib/benchmark/runner/test_executor_run.py#L139)):*
> ```Python
>     assert not benchmark.is_done()
> 
> @pytest.mark.parametrize('key', ['tool_mode', 'mode', 'rw'])
> ```

```@pytest.mark.parametrize('key', ['tool'])```



_Code quote:_
```Python
@pytest.mark.parametrize('key', ['tool_mode', 'mode', 'rw'])
```
___
*[tools/perf/tests/lib/benchmark/runner/test_executor_run.py, line 169 at r5](https://reviewable.io/reviews/pmem/rpma/1448#-Ms68qEZ3hsPHqF4ne6v:-Ms68qE_E4625iV-U0ZE:byswooa) ([raw file](https://github.com/pmem/rpma/blob/b64003efd910b92e8604171cdf134fed31249855/tools/perf/tests/lib/benchmark/runner/test_executor_run.py#L169)):*
> ```Python
>     assert not benchmark.is_done()
> 
> @pytest.mark.parametrize('key', ['tool_mode', 'mode', 'rw'])
> ```

@pytest.mark.parametrize('value', ['wrong tool', None])



_Code quote:_
```Python
@pytest.mark.parametrize('key', ['tool_mode', 'mode', 'rw'])
```
___
*[tools/perf/tests/lib/benchmark/runner/test_executor_run.py, line 170 at r5](https://reviewable.io/reviews/pmem/rpma/1448#-Ms6A_Up1pV6Telb4cu-:-Ms6A_Up1pV6Telb4cu0:b-1i8xyw) ([raw file](https://github.com/pmem/rpma/blob/b64003efd910b92e8604171cdf134fed31249855/tools/perf/tests/lib/benchmark/runner/test_executor_run.py#L170)):*
> ```Python
> 
> @pytest.mark.parametrize('key', ['tool_mode', 'mode', 'rw'])
> def test_fio_wrong_value(oneseries_fio, key, tmpdir, monkeypatch):
> ```

```def test_fio_wrong_value(oneseries_fio, value, tmpdir, monkeypatch)```



_Code quote:_
```Python
def test_fio_wrong_value(oneseries_fio, key, tmpdir, monkeypatch):
```
___
*[tools/perf/tests/lib/benchmark/runner/test_executor_run.py, line 177 at r5](https://reviewable.io/reviews/pmem/rpma/1448#-Ms6APg75RrRqACSakwO:-Ms6APg75RrRqACSakwP:bgxnngq) ([raw file](https://github.com/pmem/rpma/blob/b64003efd910b92e8604171cdf134fed31249855/tools/perf/tests/lib/benchmark/runner/test_executor_run.py#L177)):*
> ```Python
>                         run_mock_fail)
>     oneseries = {**oneseries_fio}
>     oneseries[key] = 'wrong_value'
> ```

```    oneseries['tool'] = value
```




_Code quote:_
```Python
    oneseries[key] = 'wrong_value'
```

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1448)* status: 8 of 10 files reviewed, 5 unresolved discussions (waiting on @grom72 and @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1448)* status: 5 of 11 files reviewed, 5 unresolved discussions (waiting on @grom72, @haichangsi, and @pytest)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1448#-Ms65ObSEv0gsQNRq7wc:-MsUd6gvAMqNVMLJTJuC:b-896fix) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

We should not go too far with these tests as runner.run() shall be testes separately
Following tests are required:
- Positive test cases for FioRunner and IbReadRunner (as they are)
- Negative test case with unknown Runner -> benchmark.oneseries['tool'] = None, and 'Unknown runner'
- Negative test case with  benchmark.oneseries without 'tool'
The rest shall be tested on the runner level. 
</blockquote></details>

Done.

---
___
*[tools/perf/tests/lib/benchmark/runner/test_executor_run.py, line 139 at r5](https://reviewable.io/reviews/pmem/rpma/1448#-Ms6AiS53qPEe_S74hSb:-MsUd5uV2_pGq--N_bTh:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b64003efd910b92e8604171cdf134fed31249855/tools/perf/tests/lib/benchmark/runner/test_executor_run.py#L139)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```@pytest.mark.parametrize('key', ['tool'])```
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_executor_run.py, line 169 at r5](https://reviewable.io/reviews/pmem/rpma/1448#-Ms68qEZ3hsPHqF4ne6v:-MsUd5BkCDSzIOcRWBI7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b64003efd910b92e8604171cdf134fed31249855/tools/perf/tests/lib/benchmark/runner/test_executor_run.py#L169)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

@pytest.mark.parametrize('value', ['wrong tool', None])
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_executor_run.py, line 170 at r5](https://reviewable.io/reviews/pmem/rpma/1448#-Ms6A_Up1pV6Telb4cu-:-MsUd4qA0ydUmMqU3oBk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b64003efd910b92e8604171cdf134fed31249855/tools/perf/tests/lib/benchmark/runner/test_executor_run.py#L170)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```def test_fio_wrong_value(oneseries_fio, value, tmpdir, monkeypatch)```
</blockquote></details>

Done.
___
*[tools/perf/tests/lib/benchmark/runner/test_executor_run.py, line 177 at r5](https://reviewable.io/reviews/pmem/rpma/1448#-Ms6APg75RrRqACSakwO:-MsUd4c92zlQ38Y66-HC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b64003efd910b92e8604171cdf134fed31249855/tools/perf/tests/lib/benchmark/runner/test_executor_run.py#L177)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```    oneseries['tool'] = value
```

</blockquote></details>

Done.

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r6, 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1448)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/tests/lib/benchmark/runner/test_executor_run.py, line 36 at r8](https://reviewable.io/reviews/pmem/rpma/1448#-MsUhuLQ3xXxRDZ30DWu:-MsUhuLQ3xXxRDZ30DWv:b-bas4m0) ([raw file](https://github.com/pmem/rpma/blob/d29e065e82028f8c273fa02451922f5f0668a740/tools/perf/tests/lib/benchmark/runner/test_executor_run.py#L36)):*
> ```Python
>                         run_mock_pass)
>     lib.benchmark.runner.Executor.run(benchmark_ib_read, CONFIG, str(tmpdir))
>     # marking a benchmark as 'done' is done outside of the runner
> ```

What is the purpose of this assertion in case we do have run() mock?



_Code quote:_
```Python
    # marking a benchmark as 'done' is done outside of the runner
    assert not benchmark_ib_read.is_done()
```
___
*[tools/perf/tests/lib/benchmark/runner/test_executor_run.py, line 46 at r8](https://reviewable.io/reviews/pmem/rpma/1448#-MsUi3lK7yXaTtxtCy1R:-MsUi3lK7yXaTtxtCy1S:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/d29e065e82028f8c273fa02451922f5f0668a740/tools/perf/tests/lib/benchmark/runner/test_executor_run.py#L46)):*
> ```Python
>                         run_mock_pass)
>     lib.benchmark.runner.Executor.run(benchmark_fio, CONFIG, str(tmpdir))
>     # marking a benchmark as 'done' is done outside of the runner
> ```

.



_Code quote:_
```Python
    # marking a benchmark as 'done' is done outside of the runner
    assert not benchmark_fio.is_done()
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1448)* status: 10 of 11 files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[tools/perf/tests/lib/benchmark/runner/test_executor_run.py, line 36 at r8](https://reviewable.io/reviews/pmem/rpma/1448#-MsUhuLQ3xXxRDZ30DWu:-MsUniP68sRgRBw2k9tF:bq1goit) ([raw file](https://github.com/pmem/rpma/blob/d29e065e82028f8c273fa02451922f5f0668a740/tools/perf/tests/lib/benchmark/runner/test_executor_run.py#L36)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

What is the purpose of this assertion in case we do have run() mock?
</blockquote></details>

In order to make sure `lib.benchmark.runner.Executor.run()` does not modify `is_done`.
(since we have a mock of `lib.benchmark.runner.ib_read.IbReadRunner()` here)
___
*[tools/perf/tests/lib/benchmark/runner/test_executor_run.py, line 46 at r8](https://reviewable.io/reviews/pmem/rpma/1448#-MsUi3lK7yXaTtxtCy1R:-MsUo1ca5G-ivrYy7le2:b-i07xgu) ([raw file](https://github.com/pmem/rpma/blob/d29e065e82028f8c273fa02451922f5f0668a740/tools/perf/tests/lib/benchmark/runner/test_executor_run.py#L46)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

In order to make sure `lib.benchmark.runner.Executor.run()` does not modify `is_done`.
(since we have a mock of `lib.benchmark.runner.fio.FioRunner()`here)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1448#-:-MsUsVHVC__y6I4bZmF3:bnfp4nl)* status: 10 of 11 files reviewed, 1 unresolved discussion (waiting on @grom72)

**Comment by ldorau** [comment]
This PR contains unit tests for already merged https://github.com/pmem/rpma/pull/1470

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1448)* status: 10 of 11 files reviewed, all discussions resolved (waiting on @grom72)

**Review by haichangsi — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1448#-:-MsVQKpe4Cf0Bf6Q7hzt:bdycpsm)* status: 10 of 11 files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1448#-:-MsVxd2wBbrhuHDgJZjR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
