### PR TITLE
common: fix handling PACKAGE_MANAGER in run-build.sh

### PR DESCRIPTION
**Pull request by ldorau**
Fix handling PACKAGE_MANAGER in run-build.sh:
1) PACKAGE_MANAGER has to be set,
2) if PACKAGE_MANAGER is unsupported, install the library from sources

It fixes running run-build.sh locally.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/398)

### CODE REVIEW

**Comment by ldorau** [comment]
It fixes running `run-build.sh` locally.

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/398)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[utils/docker/run-build.sh, line 25 at r1](https://reviewable.io/reviews/pmem/rpma/398#-MH0tvZNDgwp2-tmOPUD:-MH0tvZNDgwp2-tmOPUE:blkio3z) ([raw file](https://github.com/pmem/rpma/blob/d5d6d69c92d2c270b65c1ef2ff87527e88b50ee2/utils/docker/run-build.sh#L25)):*
> ```Shell
> 	# unsupported package manager
> 	PACKAGE_MANAGER=""
> fi
> ```

If you are looking for a way to run `run-build.sh` locally I think it will be batter other way:
```
if PACKAGE_MANAGER != rpm && PACKAGE_MANAGER != deb then
    fail
fi
```

Whereas for `PACKAGE_MANAGER == ""` we can perform an installation from sources.

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/398)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/398)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[utils/docker/run-build.sh, line 25 at r1](https://reviewable.io/reviews/pmem/rpma/398#-MH0tvZNDgwp2-tmOPUD:-MHAZSD7A_Z89x2Eik2b:boizqlp) ([raw file](https://github.com/pmem/rpma/blob/d5d6d69c92d2c270b65c1ef2ff87527e88b50ee2/utils/docker/run-build.sh#L25)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

If you are looking for a way to run `run-build.sh` locally I think it will be batter other way:
```
if PACKAGE_MANAGER != rpm && PACKAGE_MANAGER != deb then
    fail
fi
```

Whereas for `PACKAGE_MANAGER == ""` we can perform an installation from sources.
</blockquote></details>

I do not think so, because if we forget to set `PACKAGE_MANAGER` in a Docker file, building and testing of packages will be quietly skipped and we will not even notice that.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/398)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[utils/docker/run-build.sh, line 25 at r1](https://reviewable.io/reviews/pmem/rpma/398#-MH0tvZNDgwp2-tmOPUD:-MHO23BTDV6YNnnXiAjM:bfx9pui) ([raw file](https://github.com/pmem/rpma/blob/d5d6d69c92d2c270b65c1ef2ff87527e88b50ee2/utils/docker/run-build.sh#L25)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I do not think so, because if we forget to set `PACKAGE_MANAGER` in a Docker file, building and testing of packages will be quietly skipped and we will not even notice that.
</blockquote></details>

You can fail with a notice. Even better. What is the problem?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/398)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[utils/docker/run-build.sh, line 25 at r1](https://reviewable.io/reviews/pmem/rpma/398#-MH0tvZNDgwp2-tmOPUD:-MHPcHnc00qc4OI43O5e:bujts4w) ([raw file](https://github.com/pmem/rpma/blob/d5d6d69c92d2c270b65c1ef2ff87527e88b50ee2/utils/docker/run-build.sh#L25)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You can fail with a notice. Even better. What is the problem?
</blockquote></details>

My comment:

"*I do not think so, because if we forget to set PACKAGE_MANAGER in a Docker file, building and testing of packages will be quietly skipped and we will not even notice that.*"

was addressing this your comment:

"*Whereas for PACKAGE_MANAGER == "" we can perform an installation from sources.*"

There are Linux distributions that have different package manager than RPM and DEB (for example Arch Linux has 'pacman').
I think we do not want to restrict ourselves to supporting only those with RPM and DEB. The current solution makes it possible to build librpma on all linux distros with every possible package manager.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/398)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/398#-MIIowIQDwyOyS6PnJc4:-MIIowIQDwyOyS6PnJc5:b-5b33sq) (no related file):*
We agreed with @ldorau to implement it as follows:
- PACKAGE_MANAGER == "" -> stop with error
- PACKAGE_MANAGER == "none" -> installing RPMA from sources, no packages produced
- PACKAGE_MANAGER == "rpm" OR "deb" -> build packages and install from packages
- PACKAGE_MANAGER == any other value -> stop with error

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/398)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/398#-MIIowIQDwyOyS6PnJc4:-MIJ522g5EvANukHxEeD:bb6un1j) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

We agreed with @ldorau to implement it as follows:
- PACKAGE_MANAGER == "" -> stop with error
- PACKAGE_MANAGER == "none" -> installing RPMA from sources, no packages produced
- PACKAGE_MANAGER == "rpm" OR "deb" -> build packages and install from packages
- PACKAGE_MANAGER == any other value -> stop with error
</blockquote></details>

Done

---
___
*[utils/docker/run-build.sh, line 25 at r1](https://reviewable.io/reviews/pmem/rpma/398#-MH0tvZNDgwp2-tmOPUD:-MIJ53xC5uDqfZwNN1kl:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d5d6d69c92d2c270b65c1ef2ff87527e88b50ee2/utils/docker/run-build.sh#L25)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

My comment:

"*I do not think so, because if we forget to set PACKAGE_MANAGER in a Docker file, building and testing of packages will be quietly skipped and we will not even notice that.*"

was addressing this your comment:

"*Whereas for PACKAGE_MANAGER == "" we can perform an installation from sources.*"

There are Linux distributions that have different package manager than RPM and DEB (for example Arch Linux has 'pacman').
I think we do not want to restrict ourselves to supporting only those with RPM and DEB. The current solution makes it possible to build librpma on all linux distros with every possible package manager.

</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/398#-:-MIJBwny0IpFtxju7ghY:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[utils/docker/run-build.sh, line 32 at r4](https://reviewable.io/reviews/pmem/rpma/398#-MIJBEc49pTTghoVc5-Q:-MIJBEc49pTTghoVc5-R:b-5fxh25) ([raw file](https://github.com/pmem/rpma/blob/8e6b3b2b7e72872faea819bbdb013ef3e36461e5/utils/docker/run-build.sh#L32)):*
> Use 'rpm', 'deb' to build packages or 'none' to install the library from sources
___
*[utils/docker/run-build.sh, line 44 at r4](https://reviewable.io/reviews/pmem/rpma/398#-MIJBVtY0EU7jgZNVwi1:-MIJBVtY0EU7jgZNVwi2:bihvkn8) ([raw file](https://github.com/pmem/rpma/blob/8e6b3b2b7e72872faea819bbdb013ef3e36461e5/utils/docker/run-build.sh#L44)):*
> ```Shell
> 		# unsupported package manager
> 		echo "Error: unsupported PACKAGE_MANAGER: $PACKAGE_MANAGER"
> 		echo "       Use 'none' to install the library from sources."
> ```

Here we can also enumerate available values as I have mentioned above.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/398)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[utils/docker/run-build.sh, line 32 at r4](https://reviewable.io/reviews/pmem/rpma/398#-MIJBEc49pTTghoVc5-Q:-MIJD5bC2bizl75TBqah:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8e6b3b2b7e72872faea819bbdb013ef3e36461e5/utils/docker/run-build.sh#L32)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

> Use 'rpm', 'deb' to build packages or 'none' to install the library from sources
</blockquote></details>

Done.
___
*[utils/docker/run-build.sh, line 44 at r4](https://reviewable.io/reviews/pmem/rpma/398#-MIJBVtY0EU7jgZNVwi1:-MIJD6RhE3HvOZs_hsyp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8e6b3b2b7e72872faea819bbdb013ef3e36461e5/utils/docker/run-build.sh#L44)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Here we can also enumerate available values as I have mentioned above.
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/398#-:-MIJErtRDN-Yb55jZT2_:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/398)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
