### PR TITLE
common: fix 'missing space before/after - operator'

### PR DESCRIPTION
**Pull request by yangx-jy**
cstyle will complain 'missing space before - operator' with an array like:
    static int rets[] = {-1};
cstyle will complain 'missing space after - operator' with an array like:
    static int rets[] = {-1, EAI_SYSTEM, EAI_AGAIN};

Signed-off-by: Xiao Yang <yangx.jy@fujitsu.com>

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1199)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1199)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1199#-MhCgLiu5BVbogEqYjgC:-MhCgLiv19Z7wP-JYoH0:bd1pty) (no related file):*
It reminds me of the fix which has happened some time ago: #1156
Didn't it fix the issue?

---

**Comment by yangx-jy** [comment]
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1199#-MhCgLiu5BVbogEqYjgC:-MhChWgnAdFsmySwrTk2:b2d9tq3) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It reminds me of the fix which has happened some time ago: #1156
Didn't it fix the issue?
</blockquote></details>

The previous #1156 only fixed the following error:
```
cstyle will complain 'missing space before - operator' with an array like:
    static int rets[] = {-1, EAI_SYSTEM, EAI_AGAIN};
```

With #1156, we still get two simliar errors:
```
cstyle will complain 'missing space after - operator' with an array like:
    static int rets[] = {-1, EAI_SYSTEM, EAI_AGAIN};

cstyle will complain 'missing space before - operator' with an array like:
static int rets[] = {-1};
```

---

**Review by janekmi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1199)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1199)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1199)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1199#-:-MhT_iK2C5hIa4vDrxvL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1199#-:-Mhn1u0i4KKMSyZaBigd:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Pull request merged**
