### PR TITLE
tools: perf: adapt to fs-dax mode

### PR DESCRIPTION
**Pull request by ewanglong**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1144)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 4 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1144)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @ewanglong)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1144)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong)

___
*[tools/perf/rpma_fio_bench.sh, line 151 at r1](https://reviewable.io/reviews/pmem/rpma/1144#-Mf3ZoPr8EnUeuGRhilE:-Mf3ZoPs8olBzQFufbsa:bh93kjd) ([raw file](https://github.com/pmem/rpma/blob/c0b74d672ffcbef6562d7ee5b33f14270128425e/tools/perf/rpma_fio_bench.sh#L151)):*
> ```Shell
> 		SERVER_DUMP=${NAME}-server.log
> 		CLIENT_DUMP=${NAME}-client.log
> 		LOG_ERR=${NAME}.log
> ```

Is it really a part of this change?
___
*[tools/perf/rpma_fio_bench.sh, line 277 at r1](https://reviewable.io/reviews/pmem/rpma/1144#-Mf3_Vn03lq20lgk--4Y:-Mf3_Vn03lq20lgk--4Z:btx90nw) ([raw file](https://github.com/pmem/rpma/blob/c0b74d672ffcbef6562d7ee5b33f14270128425e/tools/perf/rpma_fio_bench.sh#L277)):*
> ```Shell
> 			cores_per_socket=${CORES_PER_SOCKET}"
> 
> 		# let FIO generate multiply files based on fs-dax mode
> ```

# pick either a DRAM/DeviceDAX or a FileSystemDAX mode
___
*[tools/perf/rpma_fio_bench.sh, line 279 at r1](https://reviewable.io/reviews/pmem/rpma/1144#-Mf3cmHjEAwk3h0REcUo:-Mf3cmHjEAwk3h0REcUp:b-7nep7b) ([raw file](https://github.com/pmem/rpma/blob/c0b74d672ffcbef6562d7ee5b33f14270128425e/tools/perf/rpma_fio_bench.sh#L279)):*
> ```Shell
> 		# let FIO generate multiply files based on fs-dax mode
> 		if [ "$REMOTE_JOB_DEST" == "malloc" ] || [ "$REMOTE_JOB_DEST" != "${REMOTE_JOB_DEST#/dev/dax}" ]; then
> 			FN_ARG="--filename=${REMOTE_JOB_DEST}"
> ```

So far we do not use ARG prefix/sufix/infix for anything. I do not see a reason to start doing this e.g. we already provide other arguments under the name `$FILTER` according to its role.

Note ARG is so generic it can mean anything. If you want to introduce the use of it you should well define its meaning.

In this case, you can name this variable e.g. `$DEST` to highlight the relation to the `$REMOTE_JOB_DEST`.
___
*[tools/perf/rpma_fio_bench.sh, line 282 at r1](https://reviewable.io/reviews/pmem/rpma/1144#-Mf3btPH79x9jP4s7-iU:-Mf3btPI5ompPj0mioHQ:bqehajx) ([raw file](https://github.com/pmem/rpma/blob/c0b74d672ffcbef6562d7ee5b33f14270128425e/tools/perf/rpma_fio_bench.sh#L282)):*
> ```Shell
> 		else
> 			FN_ARG="--filename_format=${REMOTE_JOB_DEST}.\\\$jobnum"
> 		fi
> ```

I think this if-else statement will look more natural for bash if it will be written as case-in e.g.:

```sh
case "$REMOTE_JOB_DEST" in
    malloc)
    /dev/dax*)
        FN_ARG="--filename=${REMOTE_JOB_DEST}"
        ;;
    *)
        FN_ARG="--filename_format=${REMOTE_JOB_DEST}.\\\$jobnum"
        ;;
esac
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1144)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tools/perf/rpma_fio_bench.sh, line 282 at r1](https://reviewable.io/reviews/pmem/rpma/1144#-Mf3btPH79x9jP4s7-iU:-Mf6W6Vp7bjIh9StHZdc:bwa3q0b) ([raw file](https://github.com/pmem/rpma/blob/c0b74d672ffcbef6562d7ee5b33f14270128425e/tools/perf/rpma_fio_bench.sh#L282)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think this if-else statement will look more natural for bash if it will be written as case-in e.g.:

```sh
case "$REMOTE_JOB_DEST" in
    malloc)
    /dev/dax*)
        FN_ARG="--filename=${REMOTE_JOB_DEST}"
        ;;
    *)
        FN_ARG="--filename_format=${REMOTE_JOB_DEST}.\\\$jobnum"
        ;;
esac
```
</blockquote></details>

```sh
case "$REMOTE_JOB_DEST" in
    malloc|/dev/dax*)
           ...
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1144)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong and @janekmi)

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1144)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong and @ldorau)

___
*[tools/perf/rpma_fio_bench.sh, line 282 at r1](https://reviewable.io/reviews/pmem/rpma/1144#-Mf3btPH79x9jP4s7-iU:-Mf72LiMB9slOdWFFfco:bovg9w0) ([raw file](https://github.com/pmem/rpma/blob/c0b74d672ffcbef6562d7ee5b33f14270128425e/tools/perf/rpma_fio_bench.sh#L282)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```sh
case "$REMOTE_JOB_DEST" in
    malloc|/dev/dax*)
           ...
```
</blockquote></details>

@ldorau :+1:

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1144)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1144)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong)

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1144)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tools/perf/rpma_fio_bench.sh, line 279 at r1](https://reviewable.io/reviews/pmem/rpma/1144#-Mf3cmHjEAwk3h0REcUo:-Mf7Pfe-BxwsaQrULjcF:btptgnb) ([raw file](https://github.com/pmem/rpma/blob/c0b74d672ffcbef6562d7ee5b33f14270128425e/tools/perf/rpma_fio_bench.sh#L279)):*
> DEST
There was already	DEST="$(echo $REMOTE_JOB_DEST | cut -d'/' -f2- | sed 's/\//_/g')" in use at line of 139.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1144)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tools/perf/rpma_fio_bench.sh, line 279 at r1](https://reviewable.io/reviews/pmem/rpma/1144#-Mf3cmHjEAwk3h0REcUo:-Mf7St5c7esy7oLjhrk8:b-oqplrc) ([raw file](https://github.com/pmem/rpma/blob/c0b74d672ffcbef6562d7ee5b33f14270128425e/tools/perf/rpma_fio_bench.sh#L279)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

> DEST
There was already	DEST="$(echo $REMOTE_JOB_DEST | cut -d'/' -f2- | sed 's/\//_/g')" in use at line of 139.

</blockquote></details>

so maybe `JOB_FILE` ?

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1144)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tools/perf/rpma_fio_bench.sh, line 279 at r1](https://reviewable.io/reviews/pmem/rpma/1144#-Mf3cmHjEAwk3h0REcUo:-Mf7Vh8I8rYmiNBpyjFB:bezro3w) ([raw file](https://github.com/pmem/rpma/blob/c0b74d672ffcbef6562d7ee5b33f14270128425e/tools/perf/rpma_fio_bench.sh#L279)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

so maybe `JOB_FILE` ?
</blockquote></details>

`FILE_NAME` ?

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1144)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong and @ldorau)

___
*[tools/perf/rpma_fio_bench.sh, line 277 at r1](https://reviewable.io/reviews/pmem/rpma/1144#-Mf3_Vn03lq20lgk--4Y:-Mf7bDX-4AyhN0g_XOef:b-fx0dr5) ([raw file](https://github.com/pmem/rpma/blob/c0b74d672ffcbef6562d7ee5b33f14270128425e/tools/perf/rpma_fio_bench.sh#L277)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

# pick either a DRAM/DeviceDAX or a FileSystemDAX mode
</blockquote></details>

Sorry for using the capital letters. xD It is meant to be a comment starting from `#`. ;-)
___
*[tools/perf/rpma_fio_bench.sh, line 279 at r1](https://reviewable.io/reviews/pmem/rpma/1144#-Mf3cmHjEAwk3h0REcUo:-Mf7bOKbCAD_lZwUjG3W:bdkomqc) ([raw file](https://github.com/pmem/rpma/blob/c0b74d672ffcbef6562d7ee5b33f14270128425e/tools/perf/rpma_fio_bench.sh#L279)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`FILE_NAME` ?
</blockquote></details>

I like `FILE_NAME`. It nicely corresponds with both `--filename` and `filename_format`.

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1144)* status: 4 of 5 files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/rpma_fio_bench.sh, line 151 at r1](https://reviewable.io/reviews/pmem/rpma/1144#-Mf3ZoPr8EnUeuGRhilE:-MfBLHbw7WSwnr7sJrST:b-hfpv0l) ([raw file](https://github.com/pmem/rpma/blob/c0b74d672ffcbef6562d7ee5b33f14270128425e/tools/perf/rpma_fio_bench.sh#L151)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Is it really a part of this change?
</blockquote></details>

removed
___
*[tools/perf/rpma_fio_bench.sh, line 277 at r1](https://reviewable.io/reviews/pmem/rpma/1144#-Mf3_Vn03lq20lgk--4Y:-MfBLJ4pD-LQC8envHoy:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/c0b74d672ffcbef6562d7ee5b33f14270128425e/tools/perf/rpma_fio_bench.sh#L277)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Sorry for using the capital letters. xD It is meant to be a comment starting from `#`. ;-)
</blockquote></details>

Done
___
*[tools/perf/rpma_fio_bench.sh, line 279 at r1](https://reviewable.io/reviews/pmem/rpma/1144#-Mf3cmHjEAwk3h0REcUo:-MfBLLMQ1iBvtph_LYGG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c0b74d672ffcbef6562d7ee5b33f14270128425e/tools/perf/rpma_fio_bench.sh#L279)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I like `FILE_NAME`. It nicely corresponds with both `--filename` and `filename_format`.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 282 at r1](https://reviewable.io/reviews/pmem/rpma/1144#-Mf3btPH79x9jP4s7-iU:-MfBLMNxBrHIidy-p8eq:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c0b74d672ffcbef6562d7ee5b33f14270128425e/tools/perf/rpma_fio_bench.sh#L282)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

@ldorau :+1: 
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1144)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

**Review by yangx-jy — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1144#-:-MfBslw3CEORW3wOO7us:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1144#-:-MfC1-Nk143iUwFoHaNz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1144#-:-MfC2AnZ97SJXnV1pOuu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Pull request merged**
