### PR TITLE
doc: add settings for latency tuning

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/669)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/669)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[documentation/perf-tuning-latency.md, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/669#-MOabwuT0w7eBdoL94nD:-MOabwuUEhAK_IkkTUtO:b3g73wp) ([raw file](https://github.com/pmem/rpma/blob/d027d38811123dfd64d9c6c3330f7eba7f81a0ea/documentation/perf-tuning-latency.md#L20)):*
> ```
> Power n Performance
> ```

`Power and Performance` - please change it for consistency
___
*[documentation/perf-tuning-latency.md, line 21 at r1](https://reviewable.io/reviews/pmem/rpma/669#-MOac6HM8kyNd6HQX7rS:-MOac6HM8kyNd6HQX7rT:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/d027d38811123dfd64d9c6c3330f7eba7f81a0ea/documentation/perf-tuning-latency.md#L21)):*
> ```Markdown
>     * Disable lower CPU power states: C-states[[1.2]][power-states], C1E, and memory and PCI-e power saving states. Settings vary from vendor to vendor so some of them may not be available for you e.g.:
>       * Power n Performance - Package C-State - **C0/C1 state**
>       * Power n Performance - C1E - **Disabled**
> ```

.
___
*[documentation/perf-tuning-latency.md, line 23 at r1](https://reviewable.io/reviews/pmem/rpma/669#-MOac73q-2CRN3dxFh2Z:-MOac73q-2CRN3dxFh2_:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/d027d38811123dfd64d9c6c3330f7eba7f81a0ea/documentation/perf-tuning-latency.md#L23)):*
> ```Markdown
>       * Power n Performance - C1E - **Disabled**
>     * Check for other settings that might influence performance. This varies greatly by OEM, but should include anything power related, such as fan speed settings (more is better) e.g.:
>       * Power n Performance - CPU Power and Performance Policy - **Performance**
> ```

.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/669)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[documentation/perf-tuning-latency.md, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/669#-MOabwuT0w7eBdoL94nD:-MOaeHkqDIAtgK2rEPCA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d027d38811123dfd64d9c6c3330f7eba7f81a0ea/documentation/perf-tuning-latency.md#L20)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> Power n Performance
> ```

`Power and Performance` - please change it for consistency
</blockquote></details>

Done.
___
*[documentation/perf-tuning-latency.md, line 21 at r1](https://reviewable.io/reviews/pmem/rpma/669#-MOac6HM8kyNd6HQX7rS:-MOaeIw6-OaBCCaQP1e9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d027d38811123dfd64d9c6c3330f7eba7f81a0ea/documentation/perf-tuning-latency.md#L21)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[documentation/perf-tuning-latency.md, line 23 at r1](https://reviewable.io/reviews/pmem/rpma/669#-MOac73q-2CRN3dxFh2Z:-MOaeKip7eJiOIvfpg_-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d027d38811123dfd64d9c6c3330f7eba7f81a0ea/documentation/perf-tuning-latency.md#L23)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/669#-:-MOaehGZ47acLFk5od4C:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/669)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[documentation/perf-tuning-latency.md, line 34 at r2](https://reviewable.io/reviews/pmem/rpma/669#-MOfTIDS-NrAafNBLQH8:-MOfTIDS-NrAafNBLQH9:b5z77ni) ([raw file](https://github.com/pmem/rpma/blob/89d72a60ba20850a75caef3fba24060c7fde35a9/documentation/perf-tuning-latency.md#L34)):*
> ```Markdown
> ### Not yet confirmed [[1.1]][opt-part-1]
> 
> * Ensure that *Intel® Turbo Boost*[[1.4]][turbo] is on.
> ```

Both of them should go here.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/669)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[documentation/perf-tuning-latency.md, line 34 at r2](https://reviewable.io/reviews/pmem/rpma/669#-MOfTIDS-NrAafNBLQH8:-MOfVvOp-UbsSMGiPBbD:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/89d72a60ba20850a75caef3fba24060c7fde35a9/documentation/perf-tuning-latency.md#L34)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Both of them should go here.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/669#-:-MOfXGQc5R2o5gwJcQto:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
