### PR TITLE
test: update CONN_TEST_SETUP_TEARDOWN_WITH_AND_WITHOUT_RCQ()

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1670)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1670)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[tests/unit/conn/conn-common.h, line 27 at r2](https://reviewable.io/reviews/pmem/rpma/1670#-N00VmLc5bU_kD1zDKdF:-N00VmLc5bU_kD1zDKdG:b3dhtct) ([raw file](https://github.com/pmem/rpma/blob/0df6c66b36b5fbad68c275f5aa04fdb4b446d2f1/tests/unit/conn/conn-common.h#L27)):*
> ```objc
> 	{#test_func "__no_rcq_with_channel", (test_func), (setup_func), \
> 		(teardown_func), &Conn_with_rcq_no_channel}, \
> 	{#test_func "__with_rcq_and_channel", (test_func), (setup_func), \
> ```

__with_rcq_with_channel



_Code quote:_
```objc
__with_rcq_and_channel
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1670)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1670)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tests/unit/conn/conn-common.h, line 27 at r2](https://reviewable.io/reviews/pmem/rpma/1670#-N00VmLc5bU_kD1zDKdF:-N00YEwQ6qDFBbBy9J25:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0df6c66b36b5fbad68c275f5aa04fdb4b446d2f1/tests/unit/conn/conn-common.h#L27)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

__with_rcq_with_channel
</blockquote></details>

Done.

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1670#-:-N00ZsqD9DjYJVsi_gvq:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1670#-:-N00_IXO0dq9I5TJknME:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
> Reviewed 1 of 4 files at r4, 3 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1670)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
