### PR TITLE
tools: runners initialization fixes

### PR DESCRIPTION
**Pull request by grom72**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1461)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1461)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 62 at r1](https://reviewable.io/reviews/pmem/rpma/1461#-Ms5TFky1pybMNmoEwoq:-Ms5TFkzAWFLFwQFI5qp:b-e3n4fb) ([raw file](https://github.com/pmem/rpma/blob/688bebae26443d974c1b9c5c73d0aec8fc60548b/tools/perf/lib/benchmark/runner/ib_read.py#L62)):*
> ```Python
>         self.__tool = self.__benchmark.oneseries['tool']
>         if 'mode' not in self.__benchmark.oneseries:
>             raise ValueError(MISSING_KEY_MSG.format('mode'))
> ```

`'mode'` should be checked in ` __ONESERIES_REQUIRED` too: https://github.com/ldorau/rpma/commit/12d6a947fdc48ba0599b3e93b5b189dc1bcfde03



_Code quote:_
```Python
        if 'mode' not in self.__benchmark.oneseries:
            raise ValueError(MISSING_KEY_MSG.format('mode'))
```

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1461)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 62 at r1](https://reviewable.io/reviews/pmem/rpma/1461#-Ms5TFky1pybMNmoEwoq:-Ms5W3LGBGr6vT1xsbXe:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/688bebae26443d974c1b9c5c73d0aec8fc60548b/tools/perf/lib/benchmark/runner/ib_read.py#L62)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`'mode'` should be checked in ` __ONESERIES_REQUIRED` too: https://github.com/ldorau/rpma/commit/12d6a947fdc48ba0599b3e93b5b189dc1bcfde03
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1461#-:-Ms5Ybv8AVDUmtSy3hnC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1461)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1461#-Ms5ozf07gkhphR5dJfd:-Ms5ozf07gkhphR5dJfe:b-ujmq67) (no related file):*
Rebase please

---

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1461)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1461#-Ms5ozf07gkhphR5dJfd:-Ms5sPjRAQWvh4sLkHNm:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Rebase please
</blockquote></details>

Done.

---

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1461)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1461)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1461#-Ms5tmRD5TNFp50y8UTp:-Ms5tmRD5TNFp50y8UTq:b-uwzpu1) (no related file):*
```
R0912: Too many branches (13/12) (too-many-branches)
```

---

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1461)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1461#-Ms5tmRD5TNFp50y8UTp:-Ms5xMWoArvXUMLgjdyH:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
R0912: Too many branches (13/12) (too-many-branches)
```
</blockquote></details>

Done.

---

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1461)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1461)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 116 at r4](https://reviewable.io/reviews/pmem/rpma/1461#-Ms9pLbJE5bM2tLxZwkw:-Ms9pLbJE5bM2tLxZwkx:b-lkrhof) ([raw file](https://github.com/pmem/rpma/blob/3e237b7c580e15b91923a5218991b02d553e7592/tools/perf/lib/benchmark/runner/fio.py#L116)):*
> ```Python
>         self.__set_settings_by_mode()
> 
>         # path to the local fio
> ```

This empty line should not be removed



_Code quote:_
```Python
        self.__set_settings_by_mode()

        # path to the local fio
```
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 64 at r5](https://reviewable.io/reviews/pmem/rpma/1461#-Ms9puG04RJjuEFNnwK9:-Ms9puG04RJjuEFNnwKA:bt4n103) ([raw file](https://github.com/pmem/rpma/blob/a48ab9556634aaecba775910180850e962c221f5/tools/perf/lib/benchmark/runner/ib_read.py#L64)):*
> ```Python
>         self.__tool = self.__benchmark.oneseries['tool']
>         if 'mode' not in self.__benchmark.oneseries:
>             raise ValueError(MISSING_KEY_MSG.format('mode'))
> ```

It is already checked in `__ONESERIES_REQUIRED`



_Code quote:_
```Python
        if 'mode' not in self.__benchmark.oneseries:
            raise ValueError(MISSING_KEY_MSG.format('mode'))
```

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1461)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by osalyk — APPROVED** [review]
:goat: 

> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1461#-:-MsA1Uj179VakaAkhdvO:bdycpsm)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4, 1 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1461)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 116 at r4](https://reviewable.io/reviews/pmem/rpma/1461#-Ms9pLbJE5bM2tLxZwkw:-MsA3prK1x-IEjLCyNeF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3e237b7c580e15b91923a5218991b02d553e7592/tools/perf/lib/benchmark/runner/fio.py#L116)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

This empty line should not be removed
</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 64 at r5](https://reviewable.io/reviews/pmem/rpma/1461#-Ms9puG04RJjuEFNnwK9:-MsA4HgBEbQSY53Wf4wn:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a48ab9556634aaecba775910180850e962c221f5/tools/perf/lib/benchmark/runner/ib_read.py#L64)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It is already checked in `__ONESERIES_REQUIRED`
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1461)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1461#-:-MsA6W-mBKHrqixRHztG:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1461)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 74 at r6](https://reviewable.io/reviews/pmem/rpma/1461#-MsA9DQH9TcBVRqjXpEi:-MsA9DQH9TcBVRqjXpEj:b-lqzdzy) ([raw file](https://github.com/pmem/rpma/blob/8b3dfb150219d85d22af95345f106c27a613ac50/tools/perf/lib/benchmark/runner/fio.py#L74)):*
> ```Python
>             self.__settings['iterations'] = len(cpu_load_range)
> 
>     def __set_results_key__(self) -> None:
> ```

`__set_results_key`



_Code quote:_
```Python
__set_results_key__
```
___
*[tools/perf/lib/benchmark/runner/fio.py, line 98 at r6](https://reviewable.io/reviews/pmem/rpma/1461#-MsA9GTN34lquxEwm2Kf:-MsA9GTN34lquxEwm2Kg:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/8b3dfb150219d85d22af95345f106c27a613ac50/tools/perf/lib/benchmark/runner/fio.py#L98)):*
> ```Python
>                 raise ValueError(MISSING_KEY_MSG.format(key))
>         # pick the result keys base on the benchmark's rw
>         self.__set_results_key__()
> ```

.



_Code quote:_
```Python
__set_results_key__()
```

**Review by ldorau — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1461#-:-MsA9Si3CCmjfmsg3xsS:bdycpsm)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1461#-:-MsAAOCU0YFRB5QRJ4ue:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by Patryk717 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1461#-:-MsAAQFT5BwsmXIvqZIt:bdycpsm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1461)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
