### PR TITLE
rpma: librpma 7 man page scaffolding

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/474)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/474)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 26 at r1](https://reviewable.io/reviews/pmem/rpma/474#-MINIHhK0_xAz5uakQ29:-MINIHhK0_xAz5uakQ2A:b-ig8ahu) ([raw file](https://github.com/pmem/rpma/blob/a931cbcb92fdb61ff6523c2e2a64942fad2a1b01/src/include/librpma.h#L26)):*
> ```
> librpmem.h
> ```

librpma.h
___
*[src/include/librpma.h, line 27 at r1](https://reviewable.io/reviews/pmem/rpma/474#-MINIP0mEzNg9EDKDHA6:-MINIP0mEzNg9EDKDHA7:b-c5nwuu) ([raw file](https://github.com/pmem/rpma/blob/a931cbcb92fdb61ff6523c2e2a64942fad2a1b01/src/include/librpma.h#L27)):*
> ```
> -lrpmem
> ```

-lrpma

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/474)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 166 at r1](https://reviewable.io/reviews/pmem/rpma/474#-MINIoUH5ktZw3iFknmM:-MINIoUH5ktZw3iFknmN:b-s69cng) ([raw file](https://github.com/pmem/rpma/blob/a931cbcb92fdb61ff6523c2e2a64942fad2a1b01/src/include/librpma.h#L166)):*
> ```
> librpma builds on the libibverbs and librdmacm APIs
> ```

librpma is built on the top of libibverbs and librdmacm APIs

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/474)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 22 at r1](https://reviewable.io/reviews/pmem/rpma/474#-MINSW6jASLN8NucwFlE:-MINSW6jASLN8NucwFlF:b-ljzqr0) ([raw file](https://github.com/pmem/rpma/blob/a931cbcb92fdb61ff6523c2e2a64942fad2a1b01/src/include/librpma.h#L22)):*
> ```
> support
> ```

access

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/474)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 32 at r1](https://reviewable.io/reviews/pmem/rpma/474#-MINSlP57xFxPJednTNr:-MINSlP57xFxPJednTNs:bciwwwh) ([raw file](https://github.com/pmem/rpma/blob/a931cbcb92fdb61ff6523c2e2a64942fad2a1b01/src/include/librpma.h#L32)):*
> ```
>     ... devices on
>  * remote hosts ...
> ```

```
    .... devices
 * on remote hosts
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/474)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 161 at r1](https://reviewable.io/reviews/pmem/rpma/474#-MINWPlb56Sqn6dFxDkx:-MINWPlb56Sqn6dFxDky:b9pgvry) ([raw file](https://github.com/pmem/rpma/blob/a931cbcb92fdb61ff6523c2e2a64942fad2a1b01/src/include/librpma.h#L161)):*
> ```
> examples using
> ```

examples OF using

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/474)* status: all files reviewed, 7 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 151 at r1](https://reviewable.io/reviews/pmem/rpma/474#-MINWndP--H9PAF-KX2l:-MINWndP--H9PAF-KX2m:bsnaqbq) ([raw file](https://github.com/pmem/rpma/blob/a931cbcb92fdb61ff6523c2e2a64942fad2a1b01/src/include/librpma.h#L151)):*
> ```
> DEBUGGING AND ERROR HANDLING
> ```

Maybe just `LOGGING` ? There are only `rpma_log_*` functions here.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/474)* status: all files reviewed, 10 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 117 at r1](https://reviewable.io/reviews/pmem/rpma/474#-MINXL2S7wP5nDnGiz5R:-MINXL2S7wP5nDnGiz5S:b-xvyqwq) ([raw file](https://github.com/pmem/rpma/blob/a931cbcb92fdb61ff6523c2e2a64942fad2a1b01/src/include/librpma.h#L117)):*
> ```
> MODE
> ```

MODES
___
*[src/include/librpma.h, line 129 at r1](https://reviewable.io/reviews/pmem/rpma/474#-MINXE462iRBUSHfTl-X:-MINXE462iRBUSHfTl-Y:b-j4wcdv) ([raw file](https://github.com/pmem/rpma/blob/a931cbcb92fdb61ff6523c2e2a64942fad2a1b01/src/include/librpma.h#L129)):*
> ```
> SCALABILITY AND RESOURCE USE
> ```

`SCALABILITY AND CONFIGURATION` ?
___
*[src/include/librpma.h, line 145 at r1](https://reviewable.io/reviews/pmem/rpma/474#-MINX4af9JQ6OgGTk1K0:-MINX4ag8ZsinsddVHqw:btcvkj5) ([raw file](https://github.com/pmem/rpma/blob/a931cbcb92fdb61ff6523c2e2a64942fad2a1b01/src/include/librpma.h#L145)):*
> ```
> ON-DEMAND PAGING SUPPORT
> ```

`ON-DEMAND PAGING (ODP) SUPPORT`

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/474)* status: all files reviewed, 11 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 158 at r1](https://reviewable.io/reviews/pmem/rpma/474#-MIN_x8pCbhxl_CIygII:-MIN_x8pCbhxl_CIygIJ:b2hg1yh) ([raw file](https://github.com/pmem/rpma/blob/a931cbcb92fdb61ff6523c2e2a64942fad2a1b01/src/include/librpma.h#L158)):*
> ```objc
>  * - rpma_log_get_threshold - XXX
>  * - rpma_log_set_function - XXX
>  *
> ```

missing `RETURN CODES`

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/474)* status: all files reviewed, 11 unresolved discussions (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/474)* status: all files reviewed, 12 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 171 at r2](https://reviewable.io/reviews/pmem/rpma/474#-MIOBVfxD7rtw-aLh_VQ:-MIOBVfxD7rtw-aLh_VR:b-7job45) ([raw file](https://github.com/pmem/rpma/blob/fe79a4a1047aa5250fd775ef2a6d731803ca2195/src/include/librpma.h#L171)):*
> ```objc
> #define RPMA_E_NOMEM			(-100003) /* Out of memory */
> #define RPMA_E_INVAL			(-100004) /* Invalid argument */
> #define RPMA_E_NO_COMPLETION	(-100005) /* No next completion available */
> ```

Fix alignment here, please

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/474)* status: all files reviewed, 13 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 77 at r2](https://reviewable.io/reviews/pmem/rpma/474#-MIOCas8BeNEyLl3EVMY:-MIOCas8BeNEyLl3EVMZ:b96p5j7) ([raw file](https://github.com/pmem/rpma/blob/fe79a4a1047aa5250fd775ef2a6d731803ca2195/src/include/librpma.h#L77)):*
> ```
> MESSAGING
> ```

MESSEGING

**Review by pbalcer — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/474)* status: all files reviewed, 13 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[src/include/librpma.h, line 77 at r2](https://reviewable.io/reviews/pmem/rpma/474#-MIOCas8BeNEyLl3EVMY:-MIOGp_P74QJc1gjog5c:b-mz8iuh) ([raw file](https://github.com/pmem/rpma/blob/fe79a4a1047aa5250fd775ef2a6d731803ca2195/src/include/librpma.h#L77)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> MESSAGING
> ```

MESSEGING
</blockquote></details>

MESSAGING :P

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/474)* status: 0 of 1 files reviewed, 13 unresolved discussions (waiting on @ldorau)

___
*[src/include/librpma.h, line 22 at r1](https://reviewable.io/reviews/pmem/rpma/474#-MINSW6jASLN8NucwFlE:-MIOKezuAnR-jkTAViUm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a931cbcb92fdb61ff6523c2e2a64942fad2a1b01/src/include/librpma.h#L22)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> support
> ```

access
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 26 at r1](https://reviewable.io/reviews/pmem/rpma/474#-MINIHhK0_xAz5uakQ29:-MIOHmnn8FwfrvtyPK2D:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a931cbcb92fdb61ff6523c2e2a64942fad2a1b01/src/include/librpma.h#L26)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> librpmem.h
> ```

librpma.h
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 27 at r1](https://reviewable.io/reviews/pmem/rpma/474#-MINIP0mEzNg9EDKDHA6:-MIOHndQCZU116FtqVMP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a931cbcb92fdb61ff6523c2e2a64942fad2a1b01/src/include/librpma.h#L27)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> -lrpmem
> ```

-lrpma
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 32 at r1](https://reviewable.io/reviews/pmem/rpma/474#-MINSlP57xFxPJednTNr:-MIOHvw-6mBK5VjXhje-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a931cbcb92fdb61ff6523c2e2a64942fad2a1b01/src/include/librpma.h#L32)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>     ... devices on
>  * remote hosts ...
> ```

```
    .... devices
 * on remote hosts
```
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 117 at r1](https://reviewable.io/reviews/pmem/rpma/474#-MINXL2S7wP5nDnGiz5R:-MIOI9fzAdGVQCXxu1I6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a931cbcb92fdb61ff6523c2e2a64942fad2a1b01/src/include/librpma.h#L117)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> MODE
> ```

MODES
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 129 at r1](https://reviewable.io/reviews/pmem/rpma/474#-MINXE462iRBUSHfTl-X:-MIOIBxwEPHMdBlBne7H:bstwmis) ([raw file](https://github.com/pmem/rpma/blob/a931cbcb92fdb61ff6523c2e2a64942fad2a1b01/src/include/librpma.h#L129)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> SCALABILITY AND RESOURCE USE
> ```

`SCALABILITY AND CONFIGURATION` ?
</blockquote></details>

I explicitly meant resource use because I want to describe the relationship between the length of queues and how it affects scalability but at the same time consumes resources and may hurt performance at some point.
___
*[src/include/librpma.h, line 145 at r1](https://reviewable.io/reviews/pmem/rpma/474#-MINX4af9JQ6OgGTk1K0:-MIOIoJU4_oW_OAq9pNF:b-705d9n) ([raw file](https://github.com/pmem/rpma/blob/a931cbcb92fdb61ff6523c2e2a64942fad2a1b01/src/include/librpma.h#L145)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> ON-DEMAND PAGING SUPPORT
> ```

`ON-DEMAND PAGING (ODP) SUPPORT`
</blockquote></details>

I think the abbreviation will be mentioned in the body of this section.
___
*[src/include/librpma.h, line 151 at r1](https://reviewable.io/reviews/pmem/rpma/474#-MINWndP--H9PAF-KX2l:-MIOIzIa8yBbrMcNIIOO:b-dqzkqi) ([raw file](https://github.com/pmem/rpma/blob/a931cbcb92fdb61ff6523c2e2a64942fad2a1b01/src/include/librpma.h#L151)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> DEBUGGING AND ERROR HANDLING
> ```

Maybe just `LOGGING` ? There are only `rpma_log_*` functions here.
</blockquote></details>

It is up to you. I will leave it as is. If during writing the body you will realize it makes sense to rename the whole section feel free to do this.
___
*[src/include/librpma.h, line 158 at r1](https://reviewable.io/reviews/pmem/rpma/474#-MIN_x8pCbhxl_CIygII:-MIOJFcf5C_h4HOb0Fht:b-xbbjly) ([raw file](https://github.com/pmem/rpma/blob/a931cbcb92fdb61ff6523c2e2a64942fad2a1b01/src/include/librpma.h#L158)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

missing `RETURN CODES`
</blockquote></details>

I do not see a value for now. If it will become obvious we need a section dedicated to the return codes do not hesitate.
___
*[src/include/librpma.h, line 161 at r1](https://reviewable.io/reviews/pmem/rpma/474#-MINWPlb56Sqn6dFxDkx:-MIOJggYCaV1g6HKGNfS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a931cbcb92fdb61ff6523c2e2a64942fad2a1b01/src/include/librpma.h#L161)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> examples using
> ```

examples OF using
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 166 at r1](https://reviewable.io/reviews/pmem/rpma/474#-MINIoUH5ktZw3iFknmM:-MIOJswuDwPmdcLRBnH9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a931cbcb92fdb61ff6523c2e2a64942fad2a1b01/src/include/librpma.h#L166)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> librpma builds on the libibverbs and librdmacm APIs
> ```

librpma is built on the top of libibverbs and librdmacm APIs
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 77 at r2](https://reviewable.io/reviews/pmem/rpma/474#-MIOCas8BeNEyLl3EVMY:-MIOI43n6hmYoCgedz0M:b-644zon) ([raw file](https://github.com/pmem/rpma/blob/fe79a4a1047aa5250fd775ef2a6d731803ca2195/src/include/librpma.h#L77)):*
<details><summary><i>Previously, pbalcer (Piotr Balcer) wrote…</i></summary><blockquote>

MESSAGING :P
</blockquote></details>

Left as is. x-D
___
*[src/include/librpma.h, line 171 at r2](https://reviewable.io/reviews/pmem/rpma/474#-MIOBVfxD7rtw-aLh_VQ:-MIOKHc6C313Rv-X-03o:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fe79a4a1047aa5250fd775ef2a6d731803ca2195/src/include/librpma.h#L171)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Fix alignment here, please
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/474)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/474#-:-MIOSpJM62Yr8QHteaA1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/474)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/474)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/474#-:-MIObuQP7H2BwLX5f818:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/474)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
