### PR TITLE
examples: fix running example 08srq

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1999)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1999)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[`examples/run-all-examples.sh` line 256 at r1](https://reviewable.io/reviews/pmem/rpma/1999#-NAEJRt_8ax2WLt2lOpl:-NAEJRt_8ax2WLt2lOpm:br0rp7r) ([raw file](https://github.com/pmem/rpma/blob/0e27d0f58f1b5fa1cfaab5937d529cc12765d175/examples/run-all-examples.sh#L256)):*
> ```Shell
> 	echo "*** Running example: $EXAMPLE $VLD_MSG"
> 
> 	# The `else` branch is needed here, because in case of integration tests
> ```

`The default case`



_Code quote:_
```Shell
The `else` branch
```

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1999)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1999)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1999)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[`examples/run-all-examples.sh` line 256 at r1](https://reviewable.io/reviews/pmem/rpma/1999#-NAEJRt_8ax2WLt2lOpl:-NAENFcq464hLPrbuGZc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0e27d0f58f1b5fa1cfaab5937d529cc12765d175/examples/run-all-examples.sh#L256)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`The default case`
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1999#-:-NAEOdrPB3CFh8zNwLzr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
