### PR TITLE
test: add rpma_peer_cfg_new multithreaded test

### PR DESCRIPTION
**Pull request by ewanglong**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/902)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/902)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @ewanglong)

___
*[tests/multithreaded/CMakeLists.txt, line 3 at r1](https://reviewable.io/reviews/pmem/rpma/902#-MU7antHCQCWaVWtFWcE:-MU7antI3Zc-kTpszwz_:b-8e9lgq) ([raw file](https://github.com/pmem/rpma/blob/2dae893eb8983aad5f5b4dd401d39e6beddfab81/tests/multithreaded/CMakeLists.txt#L3)):*
> ```
> 2018-2020
> ```

`2018-2021`

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/902)* status: 2 of 3 files reviewed, all discussions resolved

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/902)* status: all files reviewed, 3 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/peer/rpma_peer_cfg_new.c, line 35 at r2](https://reviewable.io/reviews/pmem/rpma/902#-MUnILdQCgg-GRpiJkL6:-MUnILdQCgg-GRpiJkL7:bu8yx6v) ([raw file](https://github.com/pmem/rpma/blob/ce71b0afb79e640095ddc7c865a8f66ec31636bf/tests/multithreaded/peer/rpma_peer_cfg_new.c#L35)):*
> ```
> 	ret = rpma_peer_cfg_new(&pcfg);
>
> 	if (ret) {
> ```

Remove the empty line in between, please.
___
*[tests/multithreaded/peer/rpma_peer_cfg_new.c, line 63 at r2](https://reviewable.io/reviews/pmem/rpma/902#-MUnIrne2JkPbggeA8JA:-MUnIrne2JkPbggeA8JB:b3jql8c) ([raw file](https://github.com/pmem/rpma/blob/ce71b0afb79e640095ddc7c865a8f66ec31636bf/tests/multithreaded/peer/rpma_peer_cfg_new.c#L63)):*
> ```
> malloc(
> ```

Please use `calloc(1, ...` to have it zeroed
___
*[tests/multithreaded/peer/rpma_peer_cfg_new.c, line 70 at r2](https://reviewable.io/reviews/pmem/rpma/902#-MUnK4j3-X5YWRSoxTQq:-MUnK4j3-X5YWRSoxTQr:b-vnptgi) ([raw file](https://github.com/pmem/rpma/blob/ce71b0afb79e640095ddc7c865a8f66ec31636bf/tests/multithreaded/peer/rpma_peer_cfg_new.c#L70)):*
> ```
> 	struct thread_args *threads_args = malloc(sizeof(struct thread_args)
> 				* (unsigned int)thread_num);
> ```

```
	struct thread_args *threads_args;
	threads_args = calloc(1, sizeof(struct thread_args) *
			(unsigned int)thread_num);
```

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/902)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/902#-:-MUrGESA4Y8PoLk8-VPp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/902)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/peer/rpma_peer_cfg_new.c, line 62 at r3](https://reviewable.io/reviews/pmem/rpma/902#-MUrOVjM9NMATtyYGEis:-MUrOVjM9NMATtyYGEit:b73w5nc) ([raw file](https://github.com/pmem/rpma/blob/49917c4b28ea086adc96e32f7daeb5a8a8445ccb/tests/multithreaded/peer/rpma_peer_cfg_new.c#L62)):*
> ```
> p_threads = calloc(thread_num, sizeof(pthread_t));
> ```

There should be:

```
calloc((size_t)thread_num
```

because of:

```
tests/multithreaded/peer/rpma_peer_cfg_new.c:62:21: error: conversion to ‘size_t’ {aka ‘long unsigned int’} from ‘int’ may change the sign of the result [-Werror=sign-conversion]
   62 |  p_threads = calloc(thread_num, sizeof(pthread_t));
      |                     ^~~~~~~~~~
```
___
*[tests/multithreaded/peer/rpma_peer_cfg_new.c, line 68 at r3](https://reviewable.io/reviews/pmem/rpma/902#-MUrP3om3EdGw_5yU_hL:-MUrP3onAMRofwMR0WiF:b-otfapu) ([raw file](https://github.com/pmem/rpma/blob/49917c4b28ea086adc96e32f7daeb5a8a8445ccb/tests/multithreaded/peer/rpma_peer_cfg_new.c#L68)):*
> ```
> calloc(thread_num,
> ```

There should be:

```
calloc((size_t)thread_num
```

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/902#-:-MUrplo3-Mig8u0I8NzE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/902)* status: all files reviewed, 5 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/CMakeLists.txt, line 3 at r4](https://reviewable.io/reviews/pmem/rpma/902#-MUycFDd3sC1gA1qPNu9:-MUycFDeE-mASBFs2CmI:b-vk8m8g) ([raw file](https://github.com/pmem/rpma/blob/4bfd76e8d2f994176537ede4bdbd9d0a863cabf5/tests/multithreaded/CMakeLists.txt#L3)):*
> ```CMake
> #
> # SPDX-License-Identifier: BSD-3-Clause
> # Copyright 2018-2021, Intel Corporation
> ```

It is pretty bold to have 3 years of copyright for work which has started last year.
@ldorau do you have an idea how it is possible?
___
*[tests/multithreaded/peer/CMakeLists.txt, line 3 at r4](https://reviewable.io/reviews/pmem/rpma/902#-MUyd--PBHfQ_v-TqnwO:-MUyd--PBHfQ_v-TqnwP:bdvqvqu) ([raw file](https://github.com/pmem/rpma/blob/4bfd76e8d2f994176537ede4bdbd9d0a863cabf5/tests/multithreaded/peer/CMakeLists.txt#L3)):*
> ```CMake
> #
> # SPDX-License-Identifier: BSD-3-Clause
> # Copyright 2018-2021, Intel Corporation
> ```

You are adding a new file. How it comes it is so old? ;-)
___
*[tests/multithreaded/peer/rpma_peer_cfg_new.c, line 5 at r4](https://reviewable.io/reviews/pmem/rpma/902#-MUydRUFBUefbwqOJD9L:-MUydRUFBUefbwqOJD9M:bwa43l1) ([raw file](https://github.com/pmem/rpma/blob/4bfd76e8d2f994176537ede4bdbd9d0a863cabf5/tests/multithreaded/peer/rpma_peer_cfg_new.c#L5)):*
> ```C
> 
> /*
>  * rpma_peer_cfg_new.c -- create a new peer configuration object
> ```

I'm not yet sure how we can describe what is going here in any meaningful way.
Since the name of the file already conveys the name of the API the only sensible comment for me for now is:

`multithreaded test`
___
*[tests/multithreaded/peer/rpma_peer_cfg_new.c, line 40 at r4](https://reviewable.io/reviews/pmem/rpma/902#-MUyfsh2Bb3ktuWWkpUl:-MUyfsh2Bb3ktuWWkpUm:bj7loj) ([raw file](https://github.com/pmem/rpma/blob/4bfd76e8d2f994176537ede4bdbd9d0a863cabf5/tests/multithreaded/peer/rpma_peer_cfg_new.c#L40)):*
> ```C
> 		exit(-1);
> 	}
> ```

You have either call `rpma_peer_cfg_delete()` in the thread or outside the working thread after joining all of them.
In the latter case, you can use the argument structure to pass the create `rpma_peer_cfg` object.
___
*[tests/multithreaded/peer/rpma_peer_cfg_new.c, line 89 at r4](https://reviewable.io/reviews/pmem/rpma/902#-MUyeWgY6ejpJocYK2BX:-MUyeWgY6ejpJocYK2BY:bmq32ak) ([raw file](https://github.com/pmem/rpma/blob/4bfd76e8d2f994176537ede4bdbd9d0a863cabf5/tests/multithreaded/peer/rpma_peer_cfg_new.c#L89)):*
> ```C
> 			 * of already created threads
> 			 * to join them below.
> 			 */
> ```

This comment seems to assume the available space is very small. I think it can use more space e.g.:

```c
			/*
			 * Set thread_num to the number of already created
			 * threads to join them below.
			 */
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/902)* status: all files reviewed, 5 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/multithreaded/CMakeLists.txt, line 3 at r4](https://reviewable.io/reviews/pmem/rpma/902#-MUycFDd3sC1gA1qPNu9:-MV0J_3tBab995JUTDYN:b-nx9sv7) ([raw file](https://github.com/pmem/rpma/blob/4bfd76e8d2f994176537ede4bdbd9d0a863cabf5/tests/multithreaded/CMakeLists.txt#L3)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It is pretty bold to have 3 years of copyright for work which has started last year.
@ldorau do you have an idea how it is possible?
</blockquote></details>

It was committed with such wrong date. See:
`$ git log -p ./tests/multithreaded/CMakeLists.txt`

It should be changed to `2020-2021`
___
*[tests/multithreaded/peer/CMakeLists.txt, line 3 at r4](https://reviewable.io/reviews/pmem/rpma/902#-MUyd--PBHfQ_v-TqnwO:-MV0LWmu5M6piRyS4Xu_:b-l61v9j) ([raw file](https://github.com/pmem/rpma/blob/4bfd76e8d2f994176537ede4bdbd9d0a863cabf5/tests/multithreaded/peer/CMakeLists.txt#L3)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You are adding a new file. How it comes it is so old? ;-)
</blockquote></details>

It should be changed to `2020-2021`

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/902)* status: all files reviewed, 5 unresolved discussions (waiting on @ewanglong and @ldorau)

___
*[tests/multithreaded/CMakeLists.txt, line 3 at r4](https://reviewable.io/reviews/pmem/rpma/902#-MUycFDd3sC1gA1qPNu9:-MVF_V4z5G-N7BB5L4Zz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4bfd76e8d2f994176537ede4bdbd9d0a863cabf5/tests/multithreaded/CMakeLists.txt#L3)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It was committed with such wrong date. See:
`$ git log -p ./tests/multithreaded/CMakeLists.txt`

It should be changed to `2020-2021`
</blockquote></details>

Done.

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/902)* status: all files reviewed, 5 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

___
*[tests/multithreaded/peer/CMakeLists.txt, line 3 at r4](https://reviewable.io/reviews/pmem/rpma/902#-MUyd--PBHfQ_v-TqnwO:-MVF_YDm1GUWiyC2vwj_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4bfd76e8d2f994176537ede4bdbd9d0a863cabf5/tests/multithreaded/peer/CMakeLists.txt#L3)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It should be changed to `2020-2021`
</blockquote></details>

Done.

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/902)* status: all files reviewed, 5 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

___
*[tests/multithreaded/peer/rpma_peer_cfg_new.c, line 5 at r4](https://reviewable.io/reviews/pmem/rpma/902#-MUydRUFBUefbwqOJD9L:-MVF__DJEnI7hShC9TpQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4bfd76e8d2f994176537ede4bdbd9d0a863cabf5/tests/multithreaded/peer/rpma_peer_cfg_new.c#L5)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I'm not yet sure how we can describe what is going here in any meaningful way.
Since the name of the file already conveys the name of the API the only sensible comment for me for now is:

`multithreaded test`
</blockquote></details>

Done.

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/902)* status: all files reviewed, 5 unresolved discussions (waiting on @ewanglong, @janekmi, and @ldorau)

___
*[tests/multithreaded/peer/rpma_peer_cfg_new.c, line 40 at r4](https://reviewable.io/reviews/pmem/rpma/902#-MUyfsh2Bb3ktuWWkpUl:-MVF_dtm2yeb04j0JO-6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4bfd76e8d2f994176537ede4bdbd9d0a863cabf5/tests/multithreaded/peer/rpma_peer_cfg_new.c#L40)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You have either call `rpma_peer_cfg_delete()` in the thread or outside the working thread after joining all of them.
In the latter case, you can use the argument structure to pass the create `rpma_peer_cfg` object.
</blockquote></details>

Done.

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/902)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tests/multithreaded/peer/rpma_peer_cfg_new.c, line 89 at r4](https://reviewable.io/reviews/pmem/rpma/902#-MUyeWgY6ejpJocYK2BX:-MVF_kfCBTHrC8XSnFTX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4bfd76e8d2f994176537ede4bdbd9d0a863cabf5/tests/multithreaded/peer/rpma_peer_cfg_new.c#L89)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This comment seems to assume the available space is very small. I think it can use more space e.g.:

```c
			/*
			 * Set thread_num to the number of already created
			 * threads to join them below.
			 */
```
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/902)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/CMakeLists.txt, line 3 at r4](https://reviewable.io/reviews/pmem/rpma/902#-MUycFDd3sC1gA1qPNu9:-MVSwN2SBcYHY9TedjVA:b-8nlap4) ([raw file](https://github.com/pmem/rpma/blob/4bfd76e8d2f994176537ede4bdbd9d0a863cabf5/tests/multithreaded/CMakeLists.txt#L3)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet.
___
*[tests/multithreaded/peer/CMakeLists.txt, line 3 at r4](https://reviewable.io/reviews/pmem/rpma/902#-MUyd--PBHfQ_v-TqnwO:-MVSwRPf2EETtOQKVMgU:b-8nlap4) ([raw file](https://github.com/pmem/rpma/blob/4bfd76e8d2f994176537ede4bdbd9d0a863cabf5/tests/multithreaded/peer/CMakeLists.txt#L3)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet.

**Review by ldorau — COMMENTED** [review]
> Reviewed 3 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/902)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/902)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tests/multithreaded/peer/CMakeLists.txt, line 3 at r4](https://reviewable.io/reviews/pmem/rpma/902#-MUyd--PBHfQ_v-TqnwO:-MVxpz3u6DUnLCdsctBD:b-4bemaq) ([raw file](https://github.com/pmem/rpma/blob/4bfd76e8d2f994176537ede4bdbd9d0a863cabf5/tests/multithreaded/peer/CMakeLists.txt#L3)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not yet.
</blockquote></details>

"2020-2021." right?
___
*[tests/multithreaded/peer/CMakeLists.txt, line 3 at r5](https://reviewable.io/reviews/pmem/rpma/902#-MVxpykECweHvwX9OwLr:-MVxpykECweHvwX9OwLs:byqqm29) ([raw file](https://github.com/pmem/rpma/blob/33270e1702e492cef573487bae66f79e6fc8ea16/tests/multithreaded/peer/CMakeLists.txt#L3)):*
> ```
> # Copyright 2020-2021, Intel Corporation
> ```

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/902)* status: all files reviewed, 5 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/multithreaded/peer/CMakeLists.txt, line 3 at r4](https://reviewable.io/reviews/pmem/rpma/902#-MUyd--PBHfQ_v-TqnwO:-MVzUTVL4kxHx296mNAn:b-8pczgr) ([raw file](https://github.com/pmem/rpma/blob/4bfd76e8d2f994176537ede4bdbd9d0a863cabf5/tests/multithreaded/peer/CMakeLists.txt#L3)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

"2020-2021." right?
</blockquote></details>

It is OK now, thanks

**Review by janekmi — APPROVED** [review]
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/902)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

**Review by janekmi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/902#-:-MW3xybv4LHGpr7U_chu:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/902)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

**Pull request merged**
