### PR TITLE
rpma: initialize rq_size with RPMA_DEFAULT_SRQ_SIZE

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/2060)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2060)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ldorau)

___
*[`src/peer.c` line 100 at r1](https://reviewable.io/reviews/pmem/rpma/2060#-NFiFRkd2Y0CdXGJpH5f:-NFiFRkd2Y0CdXGJpH5g:b-bjxju7) ([raw file](https://github.com/pmem/rpma/blob/abe441f5cd7f2a68f0c398a7bb31ce7d9857cdf8/src/peer.c#L100)):*
> ```C
> 
> #define RPMA_DEFAULT_SRQ_SIZE 20
> 	uint32_t rq_size = RPMA_DEFAULT_SRQ_SIZE;
> ```

If rpma_srq_cfg_get_rq_size() fails (it can't) we have rq_size == 0 and this should not be accepted by ibv_create_srq()



_Suggestion:_
```C
	uint32_t rq_size = 0;
```

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2060)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2060)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`src/peer.c` line 100 at r1](https://reviewable.io/reviews/pmem/rpma/2060#-NFiFRkd2Y0CdXGJpH5f:-NFiKIAB2bHfoztg-nzZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/abe441f5cd7f2a68f0c398a7bb31ce7d9857cdf8/src/peer.c#L100)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

If rpma_srq_cfg_get_rq_size() fails (it can't) we have rq_size == 0 and this should not be accepted by ibv_create_srq()
</blockquote></details>

Done.

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2060)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[`-- commits` line 2 at r2](https://reviewable.io/reviews/pmem/rpma/2060#-NFiKSsHEheUsK9QxEAC):*




_Suggestion:_
```
0
```

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2060#-:-NFiwYfq8WVBpcdTkctw:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2060)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2060)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
