### PR TITLE
common: rpma_conn_cfg scaffolding

### PR DESCRIPTION
**Pull request by janekmi**
Requires:
- [x] #313

This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/324)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 7 of 25 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/324)* status: 7 of 25 files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
> Reviewed 6 of 17 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/324)* status: 6 of 25 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/324#-:-MG7zc0Q4SLK8B2CDTxy:bnfp4nl)* status: 6 of 25 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed 5 of 25 files at r1, 5 of 17 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/324)* status: 16 of 25 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 25 files at r1, 1 of 17 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/324)* status: 18 of 25 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 17 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/324)* status: 14 of 17 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[src/ep.c, line 162 at r4](https://reviewable.io/reviews/pmem/rpma/324#-MG81-MyB_vnMwZ-i_9K:-MG81-Mz8anETHtemRKD:bppxqvc) ([raw file](https://github.com/pmem/rpma/blob/f4ca0af81aa0f94a279aa14dec61d73303705166/src/ep.c#L162)):*
> ```
> get rpma_conn_cfg defaults get from rpma_conn_cfg_default
> ```

?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/324)* status: 13 of 17 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/ep.c, line 162 at r4](https://reviewable.io/reviews/pmem/rpma/324#-MG81-MyB_vnMwZ-i_9K:-MG81pjHC1nBpSkDJvZQ:bvyb82y) ([raw file](https://github.com/pmem/rpma/blob/f4ca0af81aa0f94a279aa14dec61d73303705166/src/ep.c#L162)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> get rpma_conn_cfg defaults get from rpma_conn_cfg_default
> ```

?
</blockquote></details>

better?

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/324)* status: 14 of 17 files reviewed, all discussions resolved

___
*[src/ep.c, line 162 at r4](https://reviewable.io/reviews/pmem/rpma/324#-MG81-MyB_vnMwZ-i_9K:-MG82YVBCq_ccKoJYu5_:b2nign6) ([raw file](https://github.com/pmem/rpma/blob/f4ca0af81aa0f94a279aa14dec61d73303705166/src/ep.c#L162)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

better?
</blockquote></details>

yes

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 17 files at r3, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/324)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/324#-:-MG8AVjvDeXq9vLAUt_t:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
