### PR TITLE
[WIP] tools: Runner with common settings

### PR DESCRIPTION
**Pull request by grom72**
Settings are stored in Runner class

- [x] #1461
- [x] #1452 
- [x] #1453
- [ ] #1454 
- [x] #1455
- [ ] #1456 
- [ ] #1469 

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1458)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1458)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by Patryk717 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1458#-:-Ms4RiV0E_WCWFEGaFZR:bdycpsm)* status: 0 of 10 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 10 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1458)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1458)* status: 1 of 13 files reviewed, all discussions resolved (waiting on @grom72 and @ldorau)

**Pull request closed without merging**
