### PR TITLE
doc: add pkg-config to Build-Deps

### PR DESCRIPTION
**Pull request by kilobyte**
Required.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/548)

### CODE REVIEW

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/548)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/548#-:-MJRkeWE1h1n2d9XP-NA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/548#-:-MJSqdDb9d_Le6487lKu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/548)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
