### PR TITLE
examples: add common-pmem_map_file and signature_check to example04

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1853)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
Is it depend on #1791  ?

> Reviewed 12 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1853#-:-N54xRaoCiuY_8MvIafs:b5n9ban)* status: all files reviewed, 5 unresolved discussions (waiting on @haichangsi)

___
*[`examples/CMakeLists.txt` line 70 at r1](https://reviewable.io/reviews/pmem/rpma/1853#-N54qHt_022s8TwrUl6f:-N54qHt_022s8TwrUl6g:b-m28rg5) ([raw file](https://github.com/pmem/rpma/blob/065b1b0f4bb0bab34e84fcf631c5ee573fb5ef79/examples/CMakeLists.txt#L70)):*
> ```CMake
> 	endif()
> 	if (LIBPMEM2_FOUND)
> 		add_executable(${target} ${EXAMPLE_SRCS}
> ```

why do you cut these lines?
we have 100 characters limits.



_Code quote:_
```CMake
		add_executable(${target} ${EXAMPLE_SRCS}
			common/common-pmem2_map_file.c)
	elseif (LIBPMEM_FOUND)
		add_executable(${target} ${EXAMPLE_SRCS}
			common/common-pmem_map_file.c)
```
___
*[`examples/04-write-to-persistent/client.c` line 72 at r1](https://reviewable.io/reviews/pmem/rpma/1853#-N54s7QwE2S0qXwp4Dmp:-N54s7QwE2S0qXwp4Dmq:bmhhtkm) ([raw file](https://github.com/pmem/rpma/blob/065b1b0f4bb0bab34e84fcf631c5ee573fb5ef79/examples/04-write-to-persistent/client.c#L72)):*
> ```C
> 		char *path = argv[3];
> 
> 		ret = common_pmem_map_file_with_signature_check(path,
> ```

- one line up to 100 characters
- ``common_pmem_map_file_with_signature_check`` with ``size = 0`` initiate the client side



_Suggestion:_
```C
		ret = common_pmem_map_file_with_signature_check(path, 0, &mem);
```
___
*[`examples/04-write-to-persistent/client.c` line 235 at r1](https://reviewable.io/reviews/pmem/rpma/1853#-N54tj2Y4VaJuPtyb3Rn:-N54tj2Y4VaJuPtyb3Ro:undefined) ([raw file](https://github.com/pmem/rpma/blob/065b1b0f4bb0bab34e84fcf631c5ee573fb5ef79/examples/04-write-to-persistent/client.c#L235)):*
> ```C
> 	if (mem.is_pmem) {
> 		common_pmem_unmap_file(&mem);
> 	}
> ```





_Suggestion:_
```C
	if (mem.is_pmem) {
		common_pmem_unmap_file(&mem);

	} else
```
___
*[`examples/04-write-to-persistent/server.c` line 62 at r1](https://reviewable.io/reviews/pmem/rpma/1853#-N54tsTlDR_ooolC0GpP:-N54tsTlDR_ooolC0GpQ:b-auovxv) ([raw file](https://github.com/pmem/rpma/blob/065b1b0f4bb0bab34e84fcf631c5ee573fb5ef79/examples/04-write-to-persistent/server.c#L62)):*
> ```C
> 		pmem_path = argv[3];
> 
> 		ret = common_pmem_map_file_with_signature_check(pmem_path, 0, &mem);
> ```

please check the logic with ``common_pmem_map_file_with_signature_check`` server initializes empty memory so it needs size <> 0



_Suggestion:_
```C
common_pmem_map_file_with_signature_check(pmem_path, sizeof(struct hello_t), &mem);
```
___
*[`examples/04-write-to-persistent/server.c` line 168 at r1](https://reviewable.io/reviews/pmem/rpma/1853#-N54u9eL5XrjeS_xMPwS:-N54u9eL5XrjeS_xMPwT:undefined) ([raw file](https://github.com/pmem/rpma/blob/065b1b0f4bb0bab34e84fcf631c5ee573fb5ef79/examples/04-write-to-persistent/server.c#L168)):*
> ```C
> err_free:
> #ifdef USE_PMEM
> 	if (mem.is_pmem) {
> ```





_Suggestion:_
```C
	if (mem.is_pmem) {
		common_pmem_unmap_file(&mem);

	} else
```

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1853)* status: all files reviewed, 6 unresolved discussions (waiting on @haichangsi)

___
*[`examples/04-write-to-persistent/CMakeLists.txt` line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1853#-N54zKdmEhdJ72o642TE:-N54zKdmEhdJ72o642TF:b-4xreue) ([raw file](https://github.com/pmem/rpma/blob/065b1b0f4bb0bab34e84fcf631c5ee573fb5ef79/examples/04-write-to-persistent/CMakeLists.txt#L39)):*
> ```CMake
> link_directories(${LIBRPMA_LIBRARY_DIRS})
> 
> function(add_example name)
> ```

This code should be moved to the common CMake files.



_Code quote:_
```CMake
function(add_example name)
```

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r2, 3 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1853)* status: 10 of 12 files reviewed, 7 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[`examples/04-write-to-persistent/server.c` line 62 at r1](https://reviewable.io/reviews/pmem/rpma/1853#-N54tsTlDR_ooolC0GpP:-N59rigC6e9gK0ko-0EW:b4g1fqu) ([raw file](https://github.com/pmem/rpma/blob/065b1b0f4bb0bab34e84fcf631c5ee573fb5ef79/examples/04-write-to-persistent/server.c#L62)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

please check the logic with ``common_pmem_map_file_with_signature_check`` server initializes empty memory so it needs size <> 0
</blockquote></details>

``KILOBYTE`` instead of ``sizeof(struct hello_t)``
___
*[`examples/04-write-to-persistent/server.c` line 60 at r3](https://reviewable.io/reviews/pmem/rpma/1853#-N59sG1CEWcB1lCvm6Gu:-N59sG1CEWcB1lCvm6Gv:b9qv5kj) ([raw file](https://github.com/pmem/rpma/blob/e5848c4408fac5ee789bc1f27e6904c8e92433f0/examples/04-write-to-persistent/server.c#L60)):*
> ```C
> 
> 	if (argc >= 4) {
> 		pmem_path = argv[3];
> ```

Documentation is expected here. E.g.:
```		/*
		 * All of the space under the offset is intended for
		 * the string contents. Space is assumed to be at least 1 KiB.
		 */
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 6 files at r2, 1 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1853)* status: all files reviewed, 7 unresolved discussions (waiting on @haichangsi)

**Review by haichangsi — COMMENTED** [review]
yes

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1853#-:-N5KJwbCDx7AMVBkTbui:b2nign6)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[`examples/CMakeLists.txt` line 70 at r1](https://reviewable.io/reviews/pmem/rpma/1853#-N54qHt_022s8TwrUl6f:-N5KKvox9DSsedxW4fet:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/065b1b0f4bb0bab34e84fcf631c5ee573fb5ef79/examples/CMakeLists.txt#L70)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

why do you cut these lines?
we have 100 characters limits.
</blockquote></details>

Done.
___
*[`examples/04-write-to-persistent/CMakeLists.txt` line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1853#-N54zKdmEhdJ72o642TE:-N5KLScl6keYYm1pkXCo:b-16m59m) ([raw file](https://github.com/pmem/rpma/blob/065b1b0f4bb0bab34e84fcf631c5ee573fb5ef79/examples/04-write-to-persistent/CMakeLists.txt#L39)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

This code should be moved to the common CMake files.
</blockquote></details>

I need @ldorau help with this.
___
*[`examples/04-write-to-persistent/client.c` line 72 at r1](https://reviewable.io/reviews/pmem/rpma/1853#-N54s7QwE2S0qXwp4Dmp:-N5KLPca4sOh6PVOdWQZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/065b1b0f4bb0bab34e84fcf631c5ee573fb5ef79/examples/04-write-to-persistent/client.c#L72)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

- one line up to 100 characters
- ``common_pmem_map_file_with_signature_check`` with ``size = 0`` initiate the client side
</blockquote></details>

Done.
___
*[`examples/04-write-to-persistent/client.c` line 235 at r1](https://reviewable.io/reviews/pmem/rpma/1853#-N54tj2Y4VaJuPtyb3Rn:-N5KLb7Y1DNMcnNeJG_w:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/065b1b0f4bb0bab34e84fcf631c5ee573fb5ef79/examples/04-write-to-persistent/client.c#L235)):*
> ```C
> 	if (mem.is_pmem) {
> 		common_pmem_unmap_file(&mem);
> 	}
> ```

Done.
___
*[`examples/04-write-to-persistent/server.c` line 62 at r1](https://reviewable.io/reviews/pmem/rpma/1853#-N54tsTlDR_ooolC0GpP:-N5KM17F7nQIKtLECZt6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/065b1b0f4bb0bab34e84fcf631c5ee573fb5ef79/examples/04-write-to-persistent/server.c#L62)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

``KILOBYTE`` instead of ``sizeof(struct hello_t)``
</blockquote></details>

Done.
___
*[`examples/04-write-to-persistent/server.c` line 168 at r1](https://reviewable.io/reviews/pmem/rpma/1853#-N54u9eL5XrjeS_xMPwS:-N5KN0pfCPiAg-YcqTLu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/065b1b0f4bb0bab34e84fcf631c5ee573fb5ef79/examples/04-write-to-persistent/server.c#L168)):*
> ```C
> err_free:
> #ifdef USE_PMEM
> 	if (mem.is_pmem) {
> ```

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 4 of 8 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1853)* status: 8 of 12 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1853)* status: 8 of 12 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`examples/04-write-to-persistent/CMakeLists.txt` line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1853#-N54zKdmEhdJ72o642TE:-N5Yli5aAsbGX_wwrfTC:b-gs0aga) ([raw file](https://github.com/pmem/rpma/blob/065b1b0f4bb0bab34e84fcf631c5ee573fb5ef79/examples/04-write-to-persistent/CMakeLists.txt#L39)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

I need @ldorau help with this.
</blockquote></details>


@haichangsi It can be done in the following way:

https://github.com/ldorau/rpma/commit/e8810dd6e093fd3dde5d306806312477aba7ae07

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1853)* status: 11 of 13 files reviewed, 2 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[`examples/04-write-to-persistent/CMakeLists.txt` line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1853#-N54zKdmEhdJ72o642TE:-N5ZqCWeBEITo8loapWV:b-j65zqc) ([raw file](https://github.com/pmem/rpma/blob/065b1b0f4bb0bab34e84fcf631c5ee573fb5ef79/examples/04-write-to-persistent/CMakeLists.txt#L39)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

why do we have different function name? ``add_example_with_pmem``

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1853)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @haichangsi)

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1853)* status: 5 of 13 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`examples/cmake/common.cmake` line 36 at r5](https://reviewable.io/reviews/pmem/rpma/1853#-N5Zp8uM8zIOreP7bWW9:-N5_go0SC_9g50XbI5kJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/57243815d2933a7268b283d942891079018ef199/examples/cmake/common.cmake#L36)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

missing end of line
</blockquote></details>

Done.

**Review by grom72 — APPROVED** [review]
> Reviewed 8 of 8 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1853)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1853)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1853)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1853)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1853#-N5oGVxx1Yae5BcQMedf:-N5oGVxyEqcHG6-JjrbI:b-ujmq67) (no related file):*
Rebase please

___

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r4, 1 of 3 files at r5, 1 of 8 files at r6, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1853)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

___
*[`examples/CMakeLists.txt` line 46 at r8](https://reviewable.io/reviews/pmem/rpma/1853#-N5sOjD02SFHYlR-X4Ld:-N5sOjD02SFHYlR-X4Le:b-6m4yb4) ([raw file](https://github.com/pmem/rpma/blob/032c0ff533e3c36a746f572712ee8404a0d72282/examples/CMakeLists.txt#L46)):*
> ```CMake
> 
> function(add_example)
> 	set(options USE_LIBPROTOBUFC)
> ```

As you can see here there is no `USE_LIBIBVERBS` option available.



_Code quote:_
```CMake
	set(options USE_LIBPROTOBUFC)
	set(oneValueArgs NAME BIN)
	set(multiValueArgs SRCS)
```
___
*[`examples/CMakeLists.txt` line 128 at r8](https://reviewable.io/reviews/pmem/rpma/1853#-N5sOcOW3IJN2d-rcaUY:-N5sOcOW3IJN2d-rcaUZ:b-4kckcs) ([raw file](https://github.com/pmem/rpma/blob/032c0ff533e3c36a746f572712ee8404a0d72282/examples/CMakeLists.txt#L128)):*
> ```CMake
> add_example(NAME 04-write-to-persistent BIN server
> 	SRCS 04-write-to-persistent/server.c common/common-hello.c)
> add_example(NAME 04-write-to-persistent BIN client USE_LIBIBVERBS
> ```

There is no such option now.



_Code quote:_
```CMake
USE_LIBIBVERBS
```

**Review by ldorau — APPROVED** [review]
> Reviewed 7 of 8 files at r6, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1853)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1853#-:-N5st6rxDQpKx9xIKST_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
