### PR TITLE
examples: add libpmem2 to example03's server

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1746)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 7 of 7 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1746)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

___
*[`examples/03-read-to-persistent/CMakeLists.txt` line 59 at r1](https://reviewable.io/reviews/pmem/rpma/1746#-N2QuV6GBEfx5YS1wWYa:-N2QuV6GBEfx5YS1wWYb:undefined) ([raw file](https://github.com/pmem/rpma/blob/d2c4ba6ac58f3df42f65350c52f502d42fcd1928/examples/03-read-to-persistent/CMakeLists.txt#L59)):*
> ```CMake
> 		target_compile_definitions(${name}
> 			PRIVATE USE_LIBPMEM2)
> 	endif()
> ```





_Suggestion:_
```CMake
	elseif(LIBPMEM_FOUND)
```
___
*[`examples/03-read-to-persistent/server.c` line 52 at r1](https://reviewable.io/reviews/pmem/rpma/1746#-N2Qujua1UlGbMH9UCgC:-N2Qujua1UlGbMH9UCgD:undefined) ([raw file](https://github.com/pmem/rpma/blob/d2c4ba6ac58f3df42f65350c52f502d42fcd1928/examples/03-read-to-persistent/server.c#L52)):*
> ```C
> 		pmem_path = argv[3];
> 
> 		ret = client_pmem_map_file(pmem_path, &mem);
> ```





_Suggestion:_
```C
		if (client_pmem_map_file(pmem_path, &mem))
			return -1;
```

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1746)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1746)* status: 5 of 7 files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[`examples/03-read-to-persistent/CMakeLists.txt` line 59 at r1](https://reviewable.io/reviews/pmem/rpma/1746#-N2QuV6GBEfx5YS1wWYa:-N2kEfP71de5fcvMYoRn:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d2c4ba6ac58f3df42f65350c52f502d42fcd1928/examples/03-read-to-persistent/CMakeLists.txt#L59)):*
> ```CMake
> 		target_compile_definitions(${name}
> 			PRIVATE USE_LIBPMEM2)
> 	endif()
> ```

Done.
___
*[`examples/03-read-to-persistent/server.c` line 52 at r1](https://reviewable.io/reviews/pmem/rpma/1746#-N2Qujua1UlGbMH9UCgC:-N2kEewz-hltOuo8HSlM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d2c4ba6ac58f3df42f65350c52f502d42fcd1928/examples/03-read-to-persistent/server.c#L52)):*
> ```C
> 		pmem_path = argv[3];
> 
> 		ret = client_pmem_map_file(pmem_path, &mem);
> ```

Done.

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1746#-:-N2kZ4MW7citBL4rwK79:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1746)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 5 of 7 files at r1, 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1746#-:-N2p5fSt3DW-T7CpdJQs:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 7 files at r1, 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1746)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

___
*[`-- commits` line 7 at r2](https://reviewable.io/reviews/pmem/rpma/1746#-N2pziLy0LflAtHzEcAc):*
What is it?



_Code quote:_
```
examples: fix example03
```
___
*[`examples/03-read-to-persistent/client.c` line 58 at r2](https://reviewable.io/reviews/pmem/rpma/1746#-N2q-5YZ5tmq19bjy4oy:-N2q-5YZ5tmq19bjy4oz:bpxz2wg) ([raw file](https://github.com/pmem/rpma/blob/b4b13f8c87975acf93881984ad0aa0b277cb1d2b/examples/03-read-to-persistent/client.c#L58)):*
> ```C
> 
> 	/* resources - memory region */
> 	struct example_mem mem = {NULL, 0, 0, 0, NULL};
> ```

Fix client and rebase, please



_Code quote:_
```C
struct example_mem mem = {NULL, 0, 0, 0, NULL};
```
___
*[`examples/03-read-to-persistent/server.c` line 43 at r2](https://reviewable.io/reviews/pmem/rpma/1746#-N2q--Lj9RBYLZg1jkUn:-N2q--Lj9RBYLZg1jkUo:bbagplg) ([raw file](https://github.com/pmem/rpma/blob/b4b13f8c87975acf93881984ad0aa0b277cb1d2b/examples/03-read-to-persistent/server.c#L43)):*
> ```C
> 
> 	/* resources - memory region */
> 	struct example_mem mem = {NULL, 0, 0, 0, NULL};
> ```

Use `memset()` please.



_Code quote:_
```C
struct example_mem mem = {NULL, 0, 0, 0, NULL};
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 3 of 7 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1746)* status: all files reviewed, 4 unresolved discussions (waiting on @haichangsi)

___
*[`examples/common/common-pmem_map_file.h` line 32 at r2](https://reviewable.io/reviews/pmem/rpma/1746#-N2qKieG4vB5hlTiO-pI:-N2qKieG4vB5hlTiO-pJ:b-v6tem6) ([raw file](https://github.com/pmem/rpma/blob/b4b13f8c87975acf93881984ad0aa0b277cb1d2b/examples/common/common-pmem_map_file.h#L32)):*
> ```objc
> #else
> 	/* let's keep the same structure for both pmem and pmem2 */
> 	void *unused;
> ```

Remove it



_Code quote:_
```objc
#else
	/* let's keep the same structure for both pmem and pmem2 */
	void *unused;
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1746)* status: 3 of 7 files reviewed, 4 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

___
*[`-- commits` line 7 at r2](https://reviewable.io/reviews/pmem/rpma/1746#-N2pziLy0LflAtHzEcAc):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

What is it?
</blockquote></details>

rebased on the pr with client, it is only until the client pr gonna be merged, I did it because of the struct example_mem changes.
___
*[`examples/03-read-to-persistent/client.c` line 58 at r2](https://reviewable.io/reviews/pmem/rpma/1746#-N2q-5YZ5tmq19bjy4oy:-N36HnatANrpky6ubZv0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b4b13f8c87975acf93881984ad0aa0b277cb1d2b/examples/03-read-to-persistent/client.c#L58)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Fix client and rebase, please
</blockquote></details>

Done.
___
*[`examples/03-read-to-persistent/server.c` line 43 at r2](https://reviewable.io/reviews/pmem/rpma/1746#-N2q--Lj9RBYLZg1jkUn:-N36Ho861ntLrijgN2PM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b4b13f8c87975acf93881984ad0aa0b277cb1d2b/examples/03-read-to-persistent/server.c#L43)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Use `memset()` please.
</blockquote></details>

Done.
___
*[`examples/common/common-pmem_map_file.h` line 32 at r2](https://reviewable.io/reviews/pmem/rpma/1746#-N2qKieG4vB5hlTiO-pI:-N36Howh7m7XkcZFneyh:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b4b13f8c87975acf93881984ad0aa0b277cb1d2b/examples/common/common-pmem_map_file.h#L32)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Remove it
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1746#-:-N3JDOBW3G5eR0F2bqq2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
