### PR TITLE
rpma: use 'do { ... } while(0)' in the RPMA_LOG() macro

### PR DESCRIPTION
**Pull request by ldorau**
See: https://kernelnewbies.org/FAQ/DoWhile0

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1695)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
http://gcc.gnu.org/onlinedocs/gcc-4.1.1/gcc/Statement-Exprs.html#Statement-Exprs 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1695#-:-N0VegxA0DDitvSWh-UB:bbhixk5)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1695#-N0VfOuv5YVQZEaHD60_:-N0VfOuv5YVQZEaHD60a:bl7bpgx) (no related file):*
```
({ \
	(level <= Rpma_log_threshold[RPMA_LOG_THRESHOLD] && NULL != Rpma_log_function) ? \
	 Rpma_log_function(level, __FILE__, __LINE__, __func__, format, ##__VA_ARGS__)  : 0 \
})
```

---
___
*[`src/log_internal.h` line 27 at r1](https://reviewable.io/reviews/pmem/rpma/1695#-N0Vela37-xjJFIp32R_:-N0Vela37-xjJFIp32Ra:b-dacxae) ([raw file](https://github.com/pmem/rpma/blob/542cf580f3683282f06a34567bdbfe2f7ab97609/src/log_internal.h#L27)):*
> ```objc
> #define RPMA_LOG(level, format, ...) \
> 	do { \
> 		if (level <= Rpma_log_threshold[RPMA_LOG_THRESHOLD] && \
> ```

Should it fit into one line?
```
		if (level <= Rpma_log_threshold[RPMA_LOG_THRESHOLD] && NULL != Rpma_log_function) { \
```



_Suggestion:_
```objc
		if (level <= Rpma_log_threshold[RPMA_LOG_THRESHOLD] && \
				NULL != Rpma_log_function) { \
	
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1695)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1695#-N0VfOuv5YVQZEaHD60_:-N0VmBIRBUaGo2bfwzsi:b-n1u8ub) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```
({ \
	(level <= Rpma_log_threshold[RPMA_LOG_THRESHOLD] && NULL != Rpma_log_function) ? \
	 Rpma_log_function(level, __FILE__, __LINE__, __func__, format, ##__VA_ARGS__)  : 0 \
})
```
</blockquote></details>

`'do { ... } while(0)' ` is widely and commonly used. Why do you want use something else?

---
___
*[`src/log_internal.h` line 27 at r1](https://reviewable.io/reviews/pmem/rpma/1695#-N0Vela37-xjJFIp32R_:-N0VmdfKCuCNwX5eLQ5_:bpwl91n) ([raw file](https://github.com/pmem/rpma/blob/542cf580f3683282f06a34567bdbfe2f7ab97609/src/log_internal.h#L27)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Should it fit into one line?
```
		if (level <= Rpma_log_threshold[RPMA_LOG_THRESHOLD] && NULL != Rpma_log_function) { \
```
</blockquote></details>

Maybe it should, but it does not.

**Review by grom72 — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1695#-:-N0VnjR18LqhXupy15oT:b593w57)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1695#-N0VfOuv5YVQZEaHD60_:-N0VnI6_9IQWf6wBFME9:b-yjpd37) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`'do { ... } while(0)' ` is widely and commonly used. Why do you want use something else?
</blockquote></details>

I like mentioned above structure :). No do, no while, just more brackets.

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1695)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1695#-N0VfOuv5YVQZEaHD60_:-N0Vs_xVApDs-owRtDsQ:b-lw3w8o) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I like mentioned above structure :). No do, no while, just more brackets.
</blockquote></details>

I prefer using what is widely and commonly used.

---

**Pull request merged**
