### PR TITLE
rpma: implement rpma_send and rpma_recv and add their unit tests

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/306)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/306)* status: all files reviewed, 9 unresolved discussions (waiting on @ldorau)

___
*[tests/unit/conn/conn-recv.c, line 23 at r1](https://reviewable.io/reviews/pmem/rpma/306#-MFq22Zp26HQcDGWCnLC:-MFq22Zp26HQcDGWCnLD:bxsjmlb) ([raw file](https://github.com/pmem/rpma/blob/ccb57d8b36cb8312a441ab8b0d430fdcc90d30e3/tests/unit/conn/conn-recv.c#L23)):*
> ```C
> 	/* run test */
> 	int ret = rpma_recv(NULL, MOCK_RPMA_MR_LOCAL, MOCK_LOCAL_OFFSET,
> 				MOCK_LEN, MOCK_FLAGS, MOCK_OP_CONTEXT);
> ```

Is indentation too deep?
___
*[tests/unit/conn/conn-recv.c, line 37 at r1](https://reviewable.io/reviews/pmem/rpma/306#-MFq2AgM3MmKUTE_2Ier:-MFq2AgM3MmKUTE_2Ies:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/ccb57d8b36cb8312a441ab8b0d430fdcc90d30e3/tests/unit/conn/conn-recv.c#L37)):*
> ```C
> 	/* run test */
> 	int ret = rpma_recv(MOCK_CONN, NULL, MOCK_LOCAL_OFFSET,
> 				MOCK_LEN, MOCK_FLAGS, MOCK_OP_CONTEXT);
> ```

.
___
*[tests/unit/conn/conn-recv.c, line 51 at r1](https://reviewable.io/reviews/pmem/rpma/306#-MFq2SWy1TZLzyphoRVF:-MFq2SWz0iU4vZ2kmAm7:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/ccb57d8b36cb8312a441ab8b0d430fdcc90d30e3/tests/unit/conn/conn-recv.c#L51)):*
> ```C
> 	/* run test */
> 	int ret = rpma_recv(MOCK_CONN, MOCK_RPMA_MR_LOCAL, MOCK_LOCAL_OFFSET,
> 				MOCK_LEN, 0, MOCK_OP_CONTEXT);
> ```

.
___
*[tests/unit/conn/conn-recv.c, line 66 at r1](https://reviewable.io/reviews/pmem/rpma/306#-MFq2RtZ1LVF5t4OAldf:-MFq2RtZ1LVF5t4OAldg:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/ccb57d8b36cb8312a441ab8b0d430fdcc90d30e3/tests/unit/conn/conn-recv.c#L66)):*
> ```C
> 	/* run test */
> 	int ret = rpma_recv(NULL, NULL, MOCK_LOCAL_OFFSET,
> 				MOCK_LEN, 0, MOCK_OP_CONTEXT);
> ```

.
___
*[tests/unit/conn/conn-recv.c, line 91 at r1](https://reviewable.io/reviews/pmem/rpma/306#-MFq2RCCBpH8baVUjFHQ:-MFq2RCD2P3u-Cq3HRrY:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/ccb57d8b36cb8312a441ab8b0d430fdcc90d30e3/tests/unit/conn/conn-recv.c#L91)):*
> ```C
> 	/* run test */
> 	int ret = rpma_recv(cstate->conn, MOCK_RPMA_MR_LOCAL, MOCK_LOCAL_OFFSET,
> 				MOCK_LEN, MOCK_FLAGS, MOCK_OP_CONTEXT);
> ```

.
___
*[tests/unit/conn/conn-send.c, line 23 at r1](https://reviewable.io/reviews/pmem/rpma/306#-MFq2Vfz9gjUxy_i6YnI:-MFq2Vfz9gjUxy_i6YnJ:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/ccb57d8b36cb8312a441ab8b0d430fdcc90d30e3/tests/unit/conn/conn-send.c#L23)):*
> ```C
> 	/* run test */
> 	int ret = rpma_send(NULL, MOCK_RPMA_MR_LOCAL, MOCK_LOCAL_OFFSET,
> 				MOCK_LEN, MOCK_FLAGS, MOCK_OP_CONTEXT);
> ```

.
___
*[tests/unit/conn/conn-send.c, line 37 at r1](https://reviewable.io/reviews/pmem/rpma/306#-MFq32rz5ma0B6BpCN0H:-MFq32rz5ma0B6BpCN0I:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/ccb57d8b36cb8312a441ab8b0d430fdcc90d30e3/tests/unit/conn/conn-send.c#L37)):*
> ```C
> 	/* run test */
> 	int ret = rpma_send(MOCK_CONN, NULL, MOCK_LOCAL_OFFSET,
> 				MOCK_LEN, MOCK_FLAGS, MOCK_OP_CONTEXT);
> ```

.
___
*[tests/unit/conn/conn-send.c, line 51 at r1](https://reviewable.io/reviews/pmem/rpma/306#-MFq351L0BAAzAtFvcjA:-MFq351L0BAAzAtFvcjB:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/ccb57d8b36cb8312a441ab8b0d430fdcc90d30e3/tests/unit/conn/conn-send.c#L51)):*
> ```C
> 	/* run test */
> 	int ret = rpma_send(MOCK_CONN, MOCK_RPMA_MR_LOCAL, MOCK_LOCAL_OFFSET,
> 				MOCK_LEN, 0, MOCK_OP_CONTEXT);
> ```

.
___
*[tests/unit/conn/conn-send.c, line 66 at r1](https://reviewable.io/reviews/pmem/rpma/306#-MFq36nC4HtGxBtwa6Au:-MFq36nC4HtGxBtwa6Av:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/ccb57d8b36cb8312a441ab8b0d430fdcc90d30e3/tests/unit/conn/conn-send.c#L66)):*
> ```C
> 	/* run test */
> 	int ret = rpma_send(NULL, NULL, MOCK_LOCAL_OFFSET,
> 				MOCK_LEN, 0, MOCK_OP_CONTEXT);
> ```

.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/306)* status: all files reviewed, 9 unresolved discussions (waiting on @janekmi)

___
*[tests/unit/conn/conn-recv.c, line 23 at r1](https://reviewable.io/reviews/pmem/rpma/306#-MFq22Zp26HQcDGWCnLC:-MG2J0h1BSUo2j3Mo38M:b-c6gg49) ([raw file](https://github.com/pmem/rpma/blob/ccb57d8b36cb8312a441ab8b0d430fdcc90d30e3/tests/unit/conn/conn-recv.c#L23)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Is indentation too deep?
</blockquote></details>

IMHO no ;-) but of course it can be smaller.

Done.
___
*[tests/unit/conn/conn-recv.c, line 37 at r1](https://reviewable.io/reviews/pmem/rpma/306#-MFq2AgM3MmKUTE_2Ier:-MG2JMfr9GPKbSbCijtr:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ccb57d8b36cb8312a441ab8b0d430fdcc90d30e3/tests/unit/conn/conn-recv.c#L37)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/conn/conn-recv.c, line 51 at r1](https://reviewable.io/reviews/pmem/rpma/306#-MFq2SWy1TZLzyphoRVF:-MG2JQ1A3lUe5CwSiP0B:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ccb57d8b36cb8312a441ab8b0d430fdcc90d30e3/tests/unit/conn/conn-recv.c#L51)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/conn/conn-recv.c, line 66 at r1](https://reviewable.io/reviews/pmem/rpma/306#-MFq2RtZ1LVF5t4OAldf:-MG2JRiZAQ-buRxeJw2i:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ccb57d8b36cb8312a441ab8b0d430fdcc90d30e3/tests/unit/conn/conn-recv.c#L66)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/conn/conn-recv.c, line 91 at r1](https://reviewable.io/reviews/pmem/rpma/306#-MFq2RCCBpH8baVUjFHQ:-MG2JfSv8GiT6b42_gUC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ccb57d8b36cb8312a441ab8b0d430fdcc90d30e3/tests/unit/conn/conn-recv.c#L91)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/conn/conn-send.c, line 23 at r1](https://reviewable.io/reviews/pmem/rpma/306#-MFq2Vfz9gjUxy_i6YnI:-MG2JkBrCB8POYOAmo1m:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ccb57d8b36cb8312a441ab8b0d430fdcc90d30e3/tests/unit/conn/conn-send.c#L23)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/conn/conn-send.c, line 37 at r1](https://reviewable.io/reviews/pmem/rpma/306#-MFq32rz5ma0B6BpCN0H:-MG2JmBy6s8Lh9iVkWWb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ccb57d8b36cb8312a441ab8b0d430fdcc90d30e3/tests/unit/conn/conn-send.c#L37)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/conn/conn-send.c, line 51 at r1](https://reviewable.io/reviews/pmem/rpma/306#-MFq351L0BAAzAtFvcjA:-MG2JtF21mvLYwPOFqpi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ccb57d8b36cb8312a441ab8b0d430fdcc90d30e3/tests/unit/conn/conn-send.c#L51)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/conn/conn-send.c, line 66 at r1](https://reviewable.io/reviews/pmem/rpma/306#-MFq36nC4HtGxBtwa6Au:-MG2Jo5-9yJFxSEqx0HT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ccb57d8b36cb8312a441ab8b0d430fdcc90d30e3/tests/unit/conn/conn-send.c#L66)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/306#-:-MG2KJ1B9T-6Dn1NhEjh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 5 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/306#-:-MG2Tdwa5nOOLamTPH6D:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
