### PR TITLE
common: log ut added for compare_and_swap

### PR DESCRIPTION
**Pull request by grom72**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/515)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/515)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[src/cmocka-compare_and_swap.h, line 10 at r1](https://reviewable.io/reviews/pmem/rpma/515#-MIV_Iq_3Nc9CzektNMY:-MIV_Iq_3Nc9CzektNMZ:bh3o6fy) ([raw file](https://github.com/pmem/rpma/blob/d7f79cdd2501fcf3620db7e418956990b5ca83ef/src/cmocka-compare_and_swap.h#L10)):*
> ```objc
> #include <stdint.h>
> ```

remove empty line
___
*[tests/unit/log/set_log_function.c, line 38 at r1](https://reviewable.io/reviews/pmem/rpma/515#-MIV_fOiDKBqHQn4qURq:-MIV_fOiDKBqHQn4qURr:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/d7f79cdd2501fcf3620db7e418956990b5ca83ef/tests/unit/log/set_log_function.c#L38)):*
> ```C
> 	assert_int_equal(ret, 0);
> 	assert_ptr_equal(Rpma_log_function, custom_function);
> ```

.

**Review by ldorau — COMMENTED** [review]
> Reviewed 3 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/515)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1, 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/515)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[tests/unit/log/CMakeLists.txt, line 31 at r1](https://reviewable.io/reviews/pmem/rpma/515#-MIVdQTrCm0wuUA8u0Fw:-MIVdQTsBbsrM_Tm9YrT:b-2wel1t) ([raw file](https://github.com/pmem/rpma/blob/d7f79cdd2501fcf3620db7e418956990b5ca83ef/tests/unit/log/CMakeLists.txt#L31)):*
<details><summary><i alt="summary">Quoted 6 lines of code…</i></summary>

> ```
> if ("${name}" STREQUAL "threshold")
> 		target_compile_definitions(${test} PRIVATE TEST_MOCK_COMPARE_AND_SWAP)
> 	endif()
> 	if ("${name}" STREQUAL "set_log_function")
> 		target_compile_definitions(${test} PRIVATE TEST_MOCK_COMPARE_AND_SWAP)
> 	endif()
> ```
</details>


```
	if(("${name}" STREQUAL "threshold") OR ("${name}" STREQUAL "set_log_function"))
		target_compile_definitions(${test} PRIVATE TEST_MOCK_COMPARE_AND_SWAP)
	endif()
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/515)* status: 4 of 6 files reviewed, 3 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[src/cmocka-compare_and_swap.h, line 10 at r1](https://reviewable.io/reviews/pmem/rpma/515#-MIV_Iq_3Nc9CzektNMY:-MIVdixQA5eZhgsE1ibg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d7f79cdd2501fcf3620db7e418956990b5ca83ef/src/cmocka-compare_and_swap.h#L10)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

remove empty line
</blockquote></details>

Done.
___
*[tests/unit/log/set_log_function.c, line 38 at r1](https://reviewable.io/reviews/pmem/rpma/515#-MIV_fOiDKBqHQn4qURq:-MIVdiB90KR_vxr-fgGk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d7f79cdd2501fcf3620db7e418956990b5ca83ef/tests/unit/log/set_log_function.c#L38)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/515)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tests/unit/log/CMakeLists.txt, line 31 at r1](https://reviewable.io/reviews/pmem/rpma/515#-MIVdQTrCm0wuUA8u0Fw:-MIVe_ZK-hcXgOcstbh2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d7f79cdd2501fcf3620db7e418956990b5ca83ef/tests/unit/log/CMakeLists.txt#L31)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> if ("${name}" STREQUAL "threshold")
> 		target_compile_definitions(${test} PRIVATE TEST_MOCK_COMPARE_AND_SWAP)
> 	endif()
> 	if ("${name}" STREQUAL "set_log_function")
> 		target_compile_definitions(${test} PRIVATE TEST_MOCK_COMPARE_AND_SWAP)
> 	endif()
> ```

```
	if(("${name}" STREQUAL "threshold") OR ("${name}" STREQUAL "set_log_function"))
		target_compile_definitions(${test} PRIVATE TEST_MOCK_COMPARE_AND_SWAP)
	endif()
```
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/515#-:-MIVf5RfBlwnywb_fyoZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/515)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/515)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/515)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[src/cmocka-compare_and_swap.h, line 18 at r4](https://reviewable.io/reviews/pmem/rpma/515#-MIVmpeO9rwb65CEr35Z:-MIVmpeO9rwb65CEr35_:blbo5b) ([raw file](https://github.com/pmem/rpma/blob/eaf6a472ed9b476a547da87f8c61da38517fb51b/src/cmocka-compare_and_swap.h#L18)):*
<details><summary><i alt="summary">Quoted 9 lines of code…</i></summary>

> ```
> #ifdef TEST_MOCK_COMPARE_AND_SWAP
> extern bool sync_bool_compare_and_swap_void(void **ptr, void *oldval,
> 		void *newval);
> extern bool sync_bool_compare_and_swap_int(int *ptr, int oldval, int newval);
> #else
> #define sync_bool_compare_and_swap_void __sync_bool_compare_and_swap
> #define sync_bool_compare_and_swap_int __sync_bool_compare_and_swap
> #endif
> #endif /* LIBRPMA_CMOCKA_COMPARE_AND_SWAP */
> ```
</details>


It should be done rather like in `cmocka_alloc.h` - without modifying the source code.
Can it be done in such way?

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/515)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/515#-MIVoGMO5NS4OHnIiUN8:-MIVoGMO5NS4OHnIiUN9:b-5an7yq) (no related file):*
I have serious doubts whether we should adjust the library code to the tests ...
We do not have to have 100% code coverage ...

---

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/515)* status: 4 of 6 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/515#-MIVoGMO5NS4OHnIiUN8:-MIXUPK24ZmznSu7Mzva:bt5qyyp) (no related file):*
We did this in several places already
here is the problem that we could not do this in "normal" way as we try to mock compiler defined function (template)
and 
> ```
> #define sync_bool_compare_and_swap_void __sync_bool_compare_and_swap
> #define sync_bool_compare_and_swap_int __sync_bool_compare_and_swap
> ```
follow solution from PMDK 

---
___
*[src/cmocka-compare_and_swap.h, line 18 at r4](https://reviewable.io/reviews/pmem/rpma/515#-MIVmpeO9rwb65CEr35Z:-MIXRFy5E4BXpBuzSmxe:bx63hkr) ([raw file](https://github.com/pmem/rpma/blob/eaf6a472ed9b476a547da87f8c61da38517fb51b/src/cmocka-compare_and_swap.h#L18)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> #ifdef TEST_MOCK_COMPARE_AND_SWAP
> extern bool sync_bool_compare_and_swap_void(void **ptr, void *oldval,
> 		void *newval);
> extern bool sync_bool_compare_and_swap_int(int *ptr, int oldval, int newval);
> #else
> #define sync_bool_compare_and_swap_void __sync_bool_compare_and_swap
> #define sync_bool_compare_and_swap_int __sync_bool_compare_and_swap
> #endif
> #endif /* LIBRPMA_CMOCKA_COMPARE_AND_SWAP */
> ```

It should be done rather like in `cmocka_alloc.h` - without modifying the source code.
Can it be done in such way?


</blockquote></details>

__sync_bool_compare_and_swap is a compiler build-in function (function template)  which could not be directly mocked or redefined

we could not also make sync_bool_compare_and_swap_int/void normal function 

#define sync_bool_compare_and_swap_int(ptr, oldval, newval)  __sync_bool_compare_and_swap(ptr, oldval, newval)

followed by 
#define sync_bool_compare_and_swap_int(ptr, oldval, newval) _test_sync_bool_compare_and_swap(ptr, oldval, newval, __FILE__, __LINE__) rises compilation warning of redefinition sync_bool_compare_and_swap_int

I move default definitions to log.c but it must stay conditional

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/515)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/515)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/515#-MIVoGMO5NS4OHnIiUN8:-MIXmFrIAuX-oPXkUDRU:b-kjblt5) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

We did this in several places already
here is the problem that we could not do this in "normal" way as we try to mock compiler defined function (template)
and 
> ```
> #define sync_bool_compare_and_swap_void __sync_bool_compare_and_swap
> #define sync_bool_compare_and_swap_int __sync_bool_compare_and_swap
> ```
follow solution from PMDK 
</blockquote></details>

(I do not block, it is just a discussion)

Do we have to have 100% code coverage at any cost ? 

In my opinion no. I think these 2 lines of the race-condition handling code may stay uncovered. We should have real multi-threaded tests instead.

BTW: __sync_bool_compare_and_swap is not mocked in PMDK and I cannot see any similarity with PMDK here except of using a define.

---
___
*[src/cmocka-compare_and_swap.h, line 18 at r4](https://reviewable.io/reviews/pmem/rpma/515#-MIVmpeO9rwb65CEr35Z:-MIXkkTs5KwWI6cDBAAJ:b7cgw9n) ([raw file](https://github.com/pmem/rpma/blob/eaf6a472ed9b476a547da87f8c61da38517fb51b/src/cmocka-compare_and_swap.h#L18)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

__sync_bool_compare_and_swap is a compiler build-in function (function template)  which could not be directly mocked or redefined

we could not also make sync_bool_compare_and_swap_int/void normal function 

#define sync_bool_compare_and_swap_int(ptr, oldval, newval)  __sync_bool_compare_and_swap(ptr, oldval, newval)

followed by 
#define sync_bool_compare_and_swap_int(ptr, oldval, newval) _test_sync_bool_compare_and_swap(ptr, oldval, newval, __FILE__, __LINE__) rises compilation warning of redefinition sync_bool_compare_and_swap_int

I move default definitions to log.c but it must stay conditional

</blockquote></details>

IMHO moving the default definitions to log.c is not good. I have asked if it is possible to do that without modifying the source code and the last change modifies the library's source code even more.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/515)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/cmocka-compare_and_swap.h, line 18 at r4](https://reviewable.io/reviews/pmem/rpma/515#-MIVmpeO9rwb65CEr35Z:-MIXuC9k30DfM867HuOl:bs9ksnl) ([raw file](https://github.com/pmem/rpma/blob/eaf6a472ed9b476a547da87f8c61da38517fb51b/src/cmocka-compare_and_swap.h#L18)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

IMHO moving the default definitions to log.c is not good. I have asked if it is possible to do that without modifying the source code and the last change modifies the library's source code even more.
</blockquote></details>

No, I have not found a way to mock __sync_bool_compare_and_swap directly.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/515)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[src/cmocka-compare_and_swap.h, line 18 at r4](https://reviewable.io/reviews/pmem/rpma/515#-MIVmpeO9rwb65CEr35Z:-MIY0npvEBxx5JktrsaI:b7cgw9n) ([raw file](https://github.com/pmem/rpma/blob/eaf6a472ed9b476a547da87f8c61da38517fb51b/src/cmocka-compare_and_swap.h#L18)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

No, I have not found a way to mock __sync_bool_compare_and_swap directly.
</blockquote></details>

IMHO moving the default definitions to log.c is not good. I have asked if it is possible to do that without modifying the source code and the last change modifies the library's source code even more.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/515)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/515#-MIVoGMO5NS4OHnIiUN8:-MIXv8hp8cdnwDaQ90Ce:bv4d2wf) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

(I do not block, it is just a discussion)

Do we have to have 100% code coverage at any cost ? 

In my opinion no. I think these 2 lines of the race-condition handling code may stay uncovered. We should have real multi-threaded tests instead.

BTW: __sync_bool_compare_and_swap is not mocked in PMDK and I cannot see any similarity with PMDK here except of using a define.
</blockquote></details>

I mean they do not  use directly __sync_bool_compare_and_swap but via redefinition __sync_bool_compare_and_swap

---
___
*[src/cmocka-compare_and_swap.h, line 18 at r4](https://reviewable.io/reviews/pmem/rpma/515#-MIVmpeO9rwb65CEr35Z:-MIY13MP5A6hG5kBKcrI:bspg2x5) ([raw file](https://github.com/pmem/rpma/blob/eaf6a472ed9b476a547da87f8c61da38517fb51b/src/cmocka-compare_and_swap.h#L18)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

IMHO moving the default definitions to log.c is not good. I have asked if it is possible to do that without modifying the source code and the last change modifies the library's source code even more.
</blockquote></details>

Ok I will close this PR as there is with c11 stdatomic.h that shall be used instead of gcc compiler feature.

**Comment by grom72** [comment]
The solution to be reworked based on stdatomic.h

**Pull request closed without merging**
