### PR TITLE
tools: adapt script report_bench.sh to run on ICX

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/930)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/930)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/report_bench.sh, line 34 at r1](https://reviewable.io/reviews/pmem/rpma/930#-MVRg0j_6JRfYU57zXlu:-MVRg0j_6JRfYU57zXlv:b4jgwwa) ([raw file](https://github.com/pmem/rpma/blob/34da5be7b9cead274e0dc0d5a2ab070a4d0cd22d/tools/perf/report_bench.sh#L34)):*
> ```Shell
> 	usage "REMOTE_RNIC_PCIE_ROOT_PORT not set"
> elif [ -z "$REMOTE_DIRECT_WRITE_TO_PMEM" -a "$REMOTE_SUDO_NOPASSWD" != "1" ]; then
> 	usage "REMOTE_DIRECT_WRITE_TO_PMEM not set"
> ```

... not set and REMOTE_SUDO_NOPASSWD != 1
___
*[tools/perf/report_bench.sh, line 49 at r1](https://reviewable.io/reviews/pmem/rpma/930#-MVRfT4X9KAq7wurk-5r:-MVRfT4X9KAq7wurk-5s:b-fuhp06) ([raw file](https://github.com/pmem/rpma/blob/34da5be7b9cead274e0dc0d5a2ab070a4d0cd22d/tools/perf/report_bench.sh#L49)):*
> ```Shell
> 		echo "Run APM workloads."
> 	else
> 	        echo "RUN GPSPM workloads."
> ```

Indentation.
___
*[tools/perf/report_bench.sh, line 58 at r1](https://reviewable.io/reviews/pmem/rpma/930#-MVRgPNHES98IQuC2iD7:-MVRgPNHES98IQuC2iD8:b17kh5r) ([raw file](https://github.com/pmem/rpma/blob/34da5be7b9cead274e0dc0d5a2ab070a4d0cd22d/tools/perf/report_bench.sh#L58)):*
> ```Shell
> for mode in lat bw-bs bw-th; do
> 	./ib_read.sh $SERVER_IP $mode
> 	if [ "$REMOTE_DIRECT_WRITE_TO_PMEM" == "1" ] || [ "$REMOTE_SUDO_NOPASSWD" == "1" ]; then
> ```

You sometimes use `-a` sometimes `||`.
Can you use either one or another?
___
*[tools/perf/report_bench.sh, line 80 at r1](https://reviewable.io/reviews/pmem/rpma/930#-MVRgiPp8itTWdsFbJ20:-MVRgiPp8itTWdsFbJ21:b-8ji311) ([raw file](https://github.com/pmem/rpma/blob/34da5be7b9cead274e0dc0d5a2ab070a4d0cd22d/tools/perf/report_bench.sh#L80)):*
> ```Shell
> 			REMOTE_JOB_MEM_PATH=$PMEM ./rpma_fio_bench.sh $SERVER_IP gpspm $op $mode
> 		done
> 	fi
> ```

In this place, I think it will be easier to follow when having both conditions inside the loop instead of heaving two loops e.g.

```sh
for op in write randwirte; do
    if [ ]; then
        # execution
    fi
    if []; then
        # execution
    fi
done
```
Because otherwise, we risk these two loops will diverge in the future when they are meant to stay the same.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/930)* status: all files reviewed, 5 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/report_bench.sh, line 62 at r1](https://reviewable.io/reviews/pmem/rpma/930#-MVRsKT29KKTK-VWda2T:-MVRsKT29KKTK-VWda2U:b-3lhhgt) ([raw file](https://github.com/pmem/rpma/blob/6d0254d1b5ff6df487601e8888ea8f03432f5d88/tools/perf/report_bench.sh#L62)):*
> ```Shell
> 		# DDIO=on which is not the default for APM benchmarking.
> 		FORCE_REMOTE_DIRECT_WRITE_TO_PMEM=0 \
> 			REMOTE_JOB_MEM_PATH=$DRAM ./rpma_fio_bench.sh $SERVER_IP apm $op $mode
> ```

Why it is removed? ;-(

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/930)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/report_bench.sh, line 34 at r1](https://reviewable.io/reviews/pmem/rpma/930#-MVRg0j_6JRfYU57zXlu:-MVSmUtzA5st73sOi_KY:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/34da5be7b9cead274e0dc0d5a2ab070a4d0cd22d/tools/perf/report_bench.sh#L34)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

... not set and REMOTE_SUDO_NOPASSWD != 1
</blockquote></details>

Done.
___
*[tools/perf/report_bench.sh, line 49 at r1](https://reviewable.io/reviews/pmem/rpma/930#-MVRfT4X9KAq7wurk-5r:-MVSmjQb8lFMmk9jOmhy:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/34da5be7b9cead274e0dc0d5a2ab070a4d0cd22d/tools/perf/report_bench.sh#L49)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Indentation.
</blockquote></details>

Done.
___
*[tools/perf/report_bench.sh, line 58 at r1](https://reviewable.io/reviews/pmem/rpma/930#-MVRgPNHES98IQuC2iD7:-MVSnVf52hMRa7k1jaiK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/34da5be7b9cead274e0dc0d5a2ab070a4d0cd22d/tools/perf/report_bench.sh#L58)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You sometimes use `-a` sometimes `||`.
Can you use either one or another?
</blockquote></details>

Done.
___
*[tools/perf/report_bench.sh, line 62 at r1](https://reviewable.io/reviews/pmem/rpma/930#-MVRsKT29KKTK-VWda2T:-MVSo8gZ2jUCfT5eyaOA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6d0254d1b5ff6df487601e8888ea8f03432f5d88/tools/perf/report_bench.sh#L62)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Why it is removed? ;-(
</blockquote></details>

Done.
___
*[tools/perf/report_bench.sh, line 80 at r1](https://reviewable.io/reviews/pmem/rpma/930#-MVRgiPp8itTWdsFbJ20:-MVSoyCQ2Dks-dV-AJHF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/34da5be7b9cead274e0dc0d5a2ab070a4d0cd22d/tools/perf/report_bench.sh#L80)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

In this place, I think it will be easier to follow when having both conditions inside the loop instead of heaving two loops e.g.

```sh
for op in write randwirte; do
    if [ ]; then
        # execution
    fi
    if []; then
        # execution
    fi
done
```
Because otherwise, we risk these two loops will diverge in the future when they are meant to stay the same.
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/930)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/report_bench.sh, line 76 at r2](https://reviewable.io/reviews/pmem/rpma/930#-MVVdJBhDmL0dO725iQ3:-MVVdJBiEm2KNfpQuEPj:brghfxv) ([raw file](https://github.com/pmem/rpma/blob/ee8fac8afccfe756da3509d6470baa0dad6b7064/tools/perf/report_bench.sh#L76)):*
> ```Shell
> 			# DDIO=on which is not the default for APM benchmarking.
> 			FORCE_REMOTE_DIRECT_WRITE_TO_PMEM=0 \
> 				REMOTE_JOB_MEM_PATH=$DRAM ./rpma_fio_bench.sh $SERVER_IP apm $op $mode
> ```

This part should go to the `REMOTE_DIRECT_WRITE_TO_PMEM == 0` case.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/930)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/report_bench.sh, line 76 at r2](https://reviewable.io/reviews/pmem/rpma/930#-MVVdJBhDmL0dO725iQ3:-MVVlE-UArmjdb0wNg-5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ee8fac8afccfe756da3509d6470baa0dad6b7064/tools/perf/report_bench.sh#L76)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This part should go to the `REMOTE_DIRECT_WRITE_TO_PMEM == 0` case.
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/930)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/report_bench.sh, line 50 at r3](https://reviewable.io/reviews/pmem/rpma/930#-MVVyKyb9o7MbNn1Pc8r:-MVVyKyb9o7MbNn1Pc8s:b-d8izv5) ([raw file](https://github.com/pmem/rpma/blob/5f5e39d06fdb23f8d8e14b5f598eff9a2b44d5e1/tools/perf/report_bench.sh#L50)):*
> ```Shell
> 	else
> 		echo "Run all possible workloads with DDIO=ON."
> 	fi
> ```

```sh
echo "Run all workloads possible when Direct Write to PMem = $REMOTE_DIRECT_WRITE_TO_PMEM"
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/930)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/report_bench.sh, line 50 at r3](https://reviewable.io/reviews/pmem/rpma/930#-MVVyKyb9o7MbNn1Pc8r:-MVW0jMF1Z4jaUNjLEgf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5f5e39d06fdb23f8d8e14b5f598eff9a2b44d5e1/tools/perf/report_bench.sh#L50)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```sh
echo "Run all workloads possible when Direct Write to PMem = $REMOTE_DIRECT_WRITE_TO_PMEM"
```
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/930#-:-MVWCTWm9WMzOddycV70:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
