### PR TITLE
rpma: implement rpma_peer_cfg

### PR DESCRIPTION
**Pull request by ldorau**
Required:
- [x] UTs

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/378)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
:goat: 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/378#-:-MGmaABv4NzS1PEZcyw_:bdycpsm)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/378)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[src/peer_cfg.c, line 36 at r2](https://reviewable.io/reviews/pmem/rpma/378#-MGmeoH--n4btUgHmApZ:-MGmeoH--n4btUgHmAp_:b-oditzs) ([raw file](https://github.com/pmem/rpma/blob/0d7842655817f988aa2ae9e033562c3cd47cd49c/src/peer_cfg.c#L36)):*
> ```C
> rpma_peer_cfg_new(struct rpma_peer_cfg **pcfg)
> {
> 	struct rpma_peer_cfg *cfg = malloc(sizeof(*cfg));
> ```

Some time ago, you argued `sizeof(struct rpma_peer_cfg)` is correct.
Or it is any different?
___
*[src/peer_cfg.c, line 133 at r2](https://reviewable.io/reviews/pmem/rpma/378#-MGmjBSw3UGQBY6lQMSM:-MGmjBSw3UGQBY6lQMSN:b-vvcun8) ([raw file](https://github.com/pmem/rpma/blob/0d7842655817f988aa2ae9e033562c3cd47cd49c/src/peer_cfg.c#L133)):*
> ```C
> 	if ((ddio != RPMA_OFF && ddio != RPMA_ON) ||
> 	    (auto_flush != RPMA_OFF && auto_flush != RPMA_ON))
> 		return RPMA_E_NOSUPP;
> ```

EINVAL?
And a good logging message.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/378)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[src/peer_cfg.c, line 36 at r2](https://reviewable.io/reviews/pmem/rpma/378#-MGmeoH--n4btUgHmApZ:-MGmkD6i4xJ3BWLGXb1Q:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0d7842655817f988aa2ae9e033562c3cd47cd49c/src/peer_cfg.c#L36)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Some time ago, you argued `sizeof(struct rpma_peer_cfg)` is correct.
Or it is any different?
</blockquote></details>

Done.
___
*[src/peer_cfg.c, line 133 at r2](https://reviewable.io/reviews/pmem/rpma/378#-MGmjBSw3UGQBY6lQMSM:-MGmrw6Q6TvMlo9zZbCI:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0d7842655817f988aa2ae9e033562c3cd47cd49c/src/peer_cfg.c#L133)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

EINVAL?
And a good logging message.
</blockquote></details>

Done.

**Review by janekmi — COMMENTED** [review]
:sheep: 

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/378#-:-MGmsY6f3AiIL32NyRpI:bgxgcou)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/378)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/peer_cfg.c, line 34 at r5](https://reviewable.io/reviews/pmem/rpma/378#-MGnV9u-CURwfJDr8TP7:-MGnV9u-CURwfJDr8TP8:bvo3rgp) ([raw file](https://github.com/pmem/rpma/blob/f375efde913cb6a025ae293a3ffb294637a33637/src/peer_cfg.c#L34)):*
> ```C
>  */
> int
> rpma_peer_cfg_new(struct rpma_peer_cfg **pcfg)
> ```

Following our naming convention, I guess it should be called `pcfg_ptr`. What do you think?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/378)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[src/peer_cfg.c, line 34 at r5](https://reviewable.io/reviews/pmem/rpma/378#-MGnV9u-CURwfJDr8TP7:-MGo8P_00sXVyu8r9qKR:b-7c7o19) ([raw file](https://github.com/pmem/rpma/blob/f375efde913cb6a025ae293a3ffb294637a33637/src/peer_cfg.c#L34)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Following our naming convention, I guess it should be called `pcfg_ptr`. What do you think?
</blockquote></details>

Right, replaced.

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/378)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/378#-:-MGr4lxLB8yxRbCRJv_T:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> Reviewed 4 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/378)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[src/peer_cfg.c, line 22 at r7](https://reviewable.io/reviews/pmem/rpma/378#-MGrhQu48Z3Qsx2wPj5m:-MGrhQu48Z3Qsx2wPj5n:b-u7flkg) ([raw file](https://github.com/pmem/rpma/blob/447c8cab0a27714fe4b7c07e3af2f701b5ace879/src/peer_cfg.c#L22)):*
> ```
> ON_OFF_TYPE2STR
> ```
ON OFF or true false?
does true means on or off?
___
*[src/peer_cfg.c, line 132 at r7](https://reviewable.io/reviews/pmem/rpma/378#-MGriEe75EsTc8yKgvPt:-MGriEe75EsTc8yKgvPu:bno8yr5) ([raw file](https://github.com/pmem/rpma/blob/447c8cab0a27714fe4b7c07e3af2f701b5ace879/src/peer_cfg.c#L132)):*
> ```
> "new rpma_peer_cfg(direct_write_to_pmem=%s)
> ```
"new rpma_peer_cfg(direct_write_to_pmem %s)" direct_write_to_pmem?"True":"False" or "supported":"unsupported"

alternatively "Support for direct_write_to_pmem=True/False"

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/378)* status: 3 of 4 files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[src/peer_cfg.c, line 22 at r7](https://reviewable.io/reviews/pmem/rpma/378#-MGrhQu48Z3Qsx2wPj5m:-MGruf6F89c6g0qSkajn:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/447c8cab0a27714fe4b7c07e3af2f701b5ace879/src/peer_cfg.c#L22)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> ON_OFF_TYPE2STR
> ```
ON OFF or true false?
does true means on or off?
</blockquote></details>

Done.
___
*[src/peer_cfg.c, line 132 at r7](https://reviewable.io/reviews/pmem/rpma/378#-MGriEe75EsTc8yKgvPt:-MGrufLA6_LgsiPcyP0N:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/447c8cab0a27714fe4b7c07e3af2f701b5ace879/src/peer_cfg.c#L132)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> "new rpma_peer_cfg(direct_write_to_pmem=%s)
> ```
"new rpma_peer_cfg(direct_write_to_pmem %s)" direct_write_to_pmem?"True":"False" or "supported":"unsupported"

alternatively "Support for direct_write_to_pmem=True/False"
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 8 of 9 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/378)* status: 11 of 12 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tests/unit/peer_cfg/peer_cfg-direct_write_to_pmem.c, line 88 at r8](https://reviewable.io/reviews/pmem/rpma/378#-MGs4Ldd-aIxLoWde6fs:-MGs4Lde6H-MFwu_ZG6o:b-1w4vjj) ([raw file](https://github.com/pmem/rpma/blob/7afdd6e9f47e2ab1c0fe79280963a8230e316038/tests/unit/peer_cfg/peer_cfg-direct_write_to_pmem.c#L88)):*
> ```
> rpma_peer_cfg_set_direct_write_to_pmem
> ```
are we able to set a negative (false) value?

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 9 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/378)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/378)* status: 10 of 12 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tests/unit/peer_cfg/peer_cfg-direct_write_to_pmem.c, line 88 at r8](https://reviewable.io/reviews/pmem/rpma/378#-MGs4Ldd-aIxLoWde6fs:-MGs7fVW2qHMu9cjDPvg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7afdd6e9f47e2ab1c0fe79280963a8230e316038/tests/unit/peer_cfg/peer_cfg-direct_write_to_pmem.c#L88)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> rpma_peer_cfg_set_direct_write_to_pmem
> ```
are we able to set a negative (false) value?
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r7, 7 of 9 files at r8, 2 of 2 files at r9.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/378)* status: all files reviewed, 8 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/include/librpma.h, line 150 at r9](https://reviewable.io/reviews/pmem/rpma/378#-MGsACnTCnmVSTKxabS5:-MGsACnTCnmVSTKxabS6:b-7b1r21) ([raw file](https://github.com/pmem/rpma/blob/f7ffe6e868321f1d809b067fa4a781c435c59e9e/src/include/librpma.h#L150)):*
> ```objc
> /** 3
>  * rpma_peer_cfg_set_direct_write_to_pmem - declare if direct write
>  * to PMEM is supported
> ```

If I remember correctly, our documentation does not like multiline comments here.
Maybe just left: `declare support`
___
*[src/include/librpma.h, line 169 at r9](https://reviewable.io/reviews/pmem/rpma/378#-MGsAV1F313TkMckXBer:-MGsAV1F313TkMckXBes:b-g5b7gs) ([raw file](https://github.com/pmem/rpma/blob/f7ffe6e868321f1d809b067fa4a781c435c59e9e/src/include/librpma.h#L169)):*
> ```objc
> /** 3
>  * rpma_peer_cfg_get_direct_write_to_pmem - check if direct write
>  * to PMEM is supported
> ```

`checks support`?
___
*[tests/unit/peer_cfg/CMakeLists.txt, line 13 at r9](https://reviewable.io/reviews/pmem/rpma/378#-MGsAkbpBm6tV_XrODA3:-MGsAkbpBm6tV_XrODA4:b-fuhp06) ([raw file](https://github.com/pmem/rpma/blob/f7ffe6e868321f1d809b067fa4a781c435c59e9e/tests/unit/peer_cfg/CMakeLists.txt#L13)):*
> ```CMake
>               ${name}.c
>               peer_cfg-common.c
> 	      ${TEST_UNIT_COMMON_DIR}/mocks-rpma-log.c
> ```

Indentation.
___
*[tests/unit/peer_cfg/peer_cfg-common.h, line 8 at r9](https://reviewable.io/reviews/pmem/rpma/378#-MGsCdRe2d0UEGyEGIiP:-MGsCdRe2d0UEGyEGIiQ:bx8mf3b) ([raw file](https://github.com/pmem/rpma/blob/f7ffe6e868321f1d809b067fa4a781c435c59e9e/tests/unit/peer_cfg/peer_cfg-common.h#L8)):*
> ```objc
>  */
> 
> #ifndef CONN_CFG_COMMON
> ```

PEER_?
___
*[tests/unit/peer_cfg/peer_cfg-descriptor.c, line 129 at r9](https://reviewable.io/reviews/pmem/rpma/378#-MGsFK_3C0ofO9OLjNyh:-MGsFK_3C0ofO9OLjNyi:b-dlfwxs) ([raw file](https://github.com/pmem/rpma/blob/f7ffe6e868321f1d809b067fa4a781c435c59e9e/tests/unit/peer_cfg/peer_cfg-descriptor.c#L129)):*
> ```C
> 		/* run test of rpma_peer_cfg_from_descriptor() */
> 		rpma_peer_cfg_descriptor desc;
> 		desc.data[0] = (uint8_t)supported;
> ```

Unnecessary cast.
___
*[tests/unit/peer_cfg/peer_cfg-descriptor.c, line 138 at r9](https://reviewable.io/reviews/pmem/rpma/378#-MGsFTWj7zPYP9QgfZeA:-MGsFTWj7zPYP9QgfZeB:b-1fsd9y) ([raw file](https://github.com/pmem/rpma/blob/f7ffe6e868321f1d809b067fa4a781c435c59e9e/tests/unit/peer_cfg/peer_cfg-descriptor.c#L138)):*
> ```C
> 		ret = rpma_peer_cfg_get_descriptor(pcfg, &desc2);
> 		assert_int_equal(ret, MOCK_OK);
> 		assert_int_equal(desc2.data[0], supported);
> ```

rpma_peer_cfg_get_direct_persistent_write()?
___
*[tests/unit/peer_cfg/peer_cfg-direct_write_to_pmem.c, line 41 at r9](https://reviewable.io/reviews/pmem/rpma/378#-MGsGVikA8JqwURbnAtY:-MGsGVikA8JqwURbnAtZ:b-drtqx3) ([raw file](https://github.com/pmem/rpma/blob/f7ffe6e868321f1d809b067fa4a781c435c59e9e/tests/unit/peer_cfg/peer_cfg-direct_write_to_pmem.c#L41)):*
> ```C
> 	/* verify the results */
> 	assert_int_equal(ret, RPMA_E_INVAL);
> }
> ```

Duplicate?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/378)* status: all files reviewed, 8 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[src/include/librpma.h, line 150 at r9](https://reviewable.io/reviews/pmem/rpma/378#-MGsACnTCnmVSTKxabS5:-MGsHVF8A-Ot3C3y0JrB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f7ffe6e868321f1d809b067fa4a781c435c59e9e/src/include/librpma.h#L150)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

If I remember correctly, our documentation does not like multiline comments here.
Maybe just left: `declare support`
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 169 at r9](https://reviewable.io/reviews/pmem/rpma/378#-MGsAV1F313TkMckXBer:-MGsHVrG2rNxPL8Xt33J:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f7ffe6e868321f1d809b067fa4a781c435c59e9e/src/include/librpma.h#L169)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`checks support`?
</blockquote></details>

Done.
___
*[tests/unit/peer_cfg/CMakeLists.txt, line 13 at r9](https://reviewable.io/reviews/pmem/rpma/378#-MGsAkbpBm6tV_XrODA3:-MGsHzFE1bvqnInht6xp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f7ffe6e868321f1d809b067fa4a781c435c59e9e/tests/unit/peer_cfg/CMakeLists.txt#L13)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Indentation.
</blockquote></details>

Done.
___
*[tests/unit/peer_cfg/peer_cfg-common.h, line 8 at r9](https://reviewable.io/reviews/pmem/rpma/378#-MGsCdRe2d0UEGyEGIiP:-MGsI5Px7RUnGSzOnjq0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f7ffe6e868321f1d809b067fa4a781c435c59e9e/tests/unit/peer_cfg/peer_cfg-common.h#L8)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

PEER_?
</blockquote></details>

Done.
___
*[tests/unit/peer_cfg/peer_cfg-descriptor.c, line 129 at r9](https://reviewable.io/reviews/pmem/rpma/378#-MGsFK_3C0ofO9OLjNyh:-MGsIHYf2abiNEbIiT-X:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f7ffe6e868321f1d809b067fa4a781c435c59e9e/tests/unit/peer_cfg/peer_cfg-descriptor.c#L129)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Unnecessary cast.
</blockquote></details>

Done.
___
*[tests/unit/peer_cfg/peer_cfg-descriptor.c, line 138 at r9](https://reviewable.io/reviews/pmem/rpma/378#-MGsFTWj7zPYP9QgfZeA:-MGsJ0GL7ltkuPo9UBmA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f7ffe6e868321f1d809b067fa4a781c435c59e9e/tests/unit/peer_cfg/peer_cfg-descriptor.c#L138)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

rpma_peer_cfg_get_direct_persistent_write()?
</blockquote></details>

Done.
___
*[tests/unit/peer_cfg/peer_cfg-direct_write_to_pmem.c, line 41 at r9](https://reviewable.io/reviews/pmem/rpma/378#-MGsGVikA8JqwURbnAtY:-MGsJBQOE-7exgG6newS:b1r1rkp) ([raw file](https://github.com/pmem/rpma/blob/f7ffe6e868321f1d809b067fa4a781c435c59e9e/tests/unit/peer_cfg/peer_cfg-direct_write_to_pmem.c#L41)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Duplicate?
</blockquote></details>

No, set and get.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r10.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/378#-:-MGwNzJq4lzNgfipv_RQ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Pull request merged**
