### PR TITLE
doc: librpma.7: elaborate

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/530)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/530#-:-MIZHEu2AUNNtDaUDV9E:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/530#-:-MIZHO2Y1Oy6R6kt-Y9v:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/530)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 35 at r1](https://reviewable.io/reviews/pmem/rpma/530#-MIZHFEeBuWRpan_seet:-MIZHFEf1g-kyZz6lHku:b-y9v8t6) ([raw file](https://github.com/pmem/rpma/blob/daa9f6a42512f30be38683409d20b40e293de670/src/include/librpma.h#L35)):*
> ```
> Both available 
> ```

`Both of them are available ...`
___
*[src/include/librpma.h, line 36 at r1](https://reviewable.io/reviews/pmem/rpma/530#-MIZHMln84w8MIxlkP10:-MIZHMln84w8MIxlkP11:b-i749z5) ([raw file](https://github.com/pmem/rpma/blob/daa9f6a42512f30be38683409d20b40e293de670/src/include/librpma.h#L36)):*
> ```
> two Peers
> ```

two peers
___
*[src/include/librpma.h, line 37 at r1](https://reviewable.io/reviews/pmem/rpma/530#-MIZHcEW7m1_ZiQ5VkM7:-MIZHcEW7m1_ZiQ5VkM8:bm2odrb) ([raw file](https://github.com/pmem/rpma/blob/daa9f6a42512f30be38683409d20b40e293de670/src/include/librpma.h#L37)):*
> ```
> Remote PMem
>  * Accessing (RPMA) applications
> ```

`Remote Persistent Memory Access (RPMA) applications` ?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/530)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/include/librpma.h, line 35 at r1](https://reviewable.io/reviews/pmem/rpma/530#-MIZHFEeBuWRpan_seet:-MIZIHLoBWdrQLHRL1iq:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/daa9f6a42512f30be38683409d20b40e293de670/src/include/librpma.h#L35)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> Both available 
> ```

`Both of them are available ...`
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 36 at r1](https://reviewable.io/reviews/pmem/rpma/530#-MIZHMln84w8MIxlkP10:-MIZI9BK3sePVHOv0iF3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/daa9f6a42512f30be38683409d20b40e293de670/src/include/librpma.h#L36)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> two Peers
> ```

two peers
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 37 at r1](https://reviewable.io/reviews/pmem/rpma/530#-MIZHcEW7m1_ZiQ5VkM7:-MIZIGiqAoe7uNNweO6a:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/daa9f6a42512f30be38683409d20b40e293de670/src/include/librpma.h#L37)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> Remote PMem
>  * Accessing (RPMA) applications
> ```

`Remote Persistent Memory Access (RPMA) applications` ?
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/530)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/530#-:-MIZIeSV5v-Fy-OQBgNV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/530)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[src/include/librpma.h, line 27 at r1](https://reviewable.io/reviews/pmem/rpma/530#-MIZI8fa2wjWAYKL5YN9:-MIZI8fb-CmS0DuzONJq:b-kej5tq) ([raw file](https://github.com/pmem/rpma/blob/daa9f6a42512f30be38683409d20b40e293de670/src/include/librpma.h#L27)):*
> ```
> ...
> ```
this looks strange on https://pmem.io/rpma/master/librpma.7.html

**Pull request merged**
