### PR TITLE
tools: add direct_write_to_pmem option

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/753)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/753#-:-MRZOBV-1E2XxN0OKoG3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/753)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/rpma_fio_bench.sh, line 33 at r1](https://reviewable.io/reviews/pmem/rpma/753#-MRZOjx-5NN2zmk-1cgf:-MRZOjx0ApjCF3cBrvZR:backqd) ([raw file](https://github.com/pmem/rpma/blob/b2bb90b369fd4b95893c58a5a28ca0a80c2036af/tools/rpma_fio_bench.sh#L33)):*
> ```Shell
> 	echo "export REMOTE_PASS=pass"
> 	echo "export REMOTE_JOB_NUMA=0"
> 	echo "export REMOTE_DIRECT_WRITE_TO_PMEM=true"
> ```

```
export REMOTE_DIRECT_WRITE_TO_PMEM=true/false (https://pmem.io/rpma/documentation/basic-direct-write-to-pmem.html)
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/753)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[tools/rpma_fio_bench.sh, line 33 at r1](https://reviewable.io/reviews/pmem/rpma/753#-MRZOjx-5NN2zmk-1cgf:-MRZPrzh1n2Sq9C69LkX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b2bb90b369fd4b95893c58a5a28ca0a80c2036af/tools/rpma_fio_bench.sh#L33)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```
export REMOTE_DIRECT_WRITE_TO_PMEM=true/false (https://pmem.io/rpma/documentation/basic-direct-write-to-pmem.html)
```

</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/753#-:-MRZSteQAZFaeoRNwoMk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
