### PR TITLE
rpma: improve INSTALL.md file

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1970)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1970)* status: all files reviewed, 14 unresolved discussions (waiting on @haichangsi and @Patryk717)

___
*[`INSTALL.md` line 31 at r1](https://reviewable.io/reviews/pmem/rpma/1970#-N8c9OWT42Dfax8NfK9x:-N8c9OWT42Dfax8NfK9y:by3k5ow) ([raw file](https://github.com/pmem/rpma/blob/d61265fb8d6dd1da29320ab5e9ca2fe690dbb975/INSTALL.md#L31)):*
> ```Markdown
> to generate the Markdown documentation.
> 
> **Note**: building the documentation can be turned off using the CMake 'BUILD_DOC' option
> ```

``BUILD_DOC`` - use back-ticks please



_Code quote:_
```Markdown
'BUILD_DOC'
```
___
*[`INSTALL.md` line 32 at r1](https://reviewable.io/reviews/pmem/rpma/1970#-N8c9iVe5k-0Vc6SzWP6:-N8c9iVe5k-0Vc6SzWP7:b2vhfm) ([raw file](https://github.com/pmem/rpma/blob/d61265fb8d6dd1da29320ab5e9ca2fe690dbb975/INSTALL.md#L32)):*
> ```Markdown
> 
> **Note**: building the documentation can be turned off using the CMake 'BUILD_DOC' option
> (see [CMake options of the librpma library](DEVELOPMENT.md#cmake-options-of-the-librpma-library) and
> ```

Change the order of these two links to the opposite one.



_Code quote:_
```Markdown
(see [CMake options of the librpma library](DEVELOPMENT.md#cmake-options-of-the-librpma-library) and
[Configuring CMake options](DEVELOPMENT.md#configuring-cmake-options)).
```
___
*[`INSTALL.md` line 38 at r1](https://reviewable.io/reviews/pmem/rpma/1970#-N8cA5vB8GN2b1JTu0b2:-N8cA5vB8GN2b1JTu0b3:b-oe9ddk) ([raw file](https://github.com/pmem/rpma/blob/d61265fb8d6dd1da29320ab5e9ca2fe690dbb975/INSTALL.md#L38)):*
> ```Markdown
> ### For some examples you also need:
> 
> - libpmem-dev(el) >= 1.6
> ```

```
- libpmem-dev(el) >= 1.6 or libpmem2-dev(el) >= 1.11 for examples: ...

```
- list the examples please



_Code quote:_
```Markdown
- libpmem-dev(el) >= 1.6
- libpmem2-dev(el) >= 1.11
```
___
*[`INSTALL.md` line 40 at r1](https://reviewable.io/reviews/pmem/rpma/1970#-N8cAEbd2vTU6vFKkpZK:-N8cAEbd2vTU6vFKkpZL:bus9aar) ([raw file](https://github.com/pmem/rpma/blob/d61265fb8d6dd1da29320ab5e9ca2fe690dbb975/INSTALL.md#L40)):*
> ```Markdown
> - libpmem-dev(el) >= 1.6
> - libpmem2-dev(el) >= 1.11
> - libprotobuf-c-dev(el) >= 1.0
> ```

`- libprotobuf-c-dev(el) >= 1.0 for examples: ... ` - list the examples please



_Code quote:_
```Markdown
- libprotobuf-c-dev(el) >= 1.0
```
___
*[`INSTALL.md` line 46 at r1](https://reviewable.io/reviews/pmem/rpma/1970#-N8c6jf33O-J8DJzPMo8:-N8c6jf41dKYJRA6ZFJL:bgj2xb0) ([raw file](https://github.com/pmem/rpma/blob/d61265fb8d6dd1da29320ab5e9ca2fe690dbb975/INSTALL.md#L46)):*
> ```Markdown
> **Note**: see [the list of the supported OSes](INSTALL.md#os-support).
> 
> **Note**: please be aware that the libpmem2-dev(el) package is not available on some distributions. Use [our script](./utils/docker/images/install-pmdk.sh) to install it manually from sources. You can check all needed additional packages in one of our dockerfiles, for example [here](./utils/docker/images/Dockerfile.archlinux-latest), in the variable called PMDK_DEBS.
> ```

`PMDK_DEPS`



_Code quote:_
```Markdown
PMDK_DEBS
```
___
*[`INSTALL.md` line 46 at r1](https://reviewable.io/reviews/pmem/rpma/1970#-N8cAcQj-UoNeCjFv_iL:-N8cAcQj-UoNeCjFv_iM:bz37tnm) ([raw file](https://github.com/pmem/rpma/blob/d61265fb8d6dd1da29320ab5e9ca2fe690dbb975/INSTALL.md#L46)):*
> ```Markdown
> **Note**: see [the list of the supported OSes](INSTALL.md#os-support).
> 
> **Note**: please be aware that the libpmem2-dev(el) package is not available on some distributions. Use [our script](./utils/docker/images/install-pmdk.sh) to install it manually from sources. You can check all needed additional packages in one of our dockerfiles, for example [here](./utils/docker/images/Dockerfile.archlinux-latest), in the variable called PMDK_DEBS.
> ```

```
[Dockerfiles](./utils/docker/images/)
```



_Code quote:_
```Markdown
dockerfiles
```
___
*[`INSTALL.md` line 46 at r1](https://reviewable.io/reviews/pmem/rpma/1970#-N8cAwjR3J_-zQ9RXC5Y:-N8cAwjR3J_-zQ9RXC5Z:buuel3w) ([raw file](https://github.com/pmem/rpma/blob/d61265fb8d6dd1da29320ab5e9ca2fe690dbb975/INSTALL.md#L46)):*
> ```Markdown
> **Note**: see [the list of the supported OSes](INSTALL.md#os-support).
> 
> **Note**: please be aware that the libpmem2-dev(el) package is not available on some distributions. Use [our script](./utils/docker/images/install-pmdk.sh) to install it manually from sources. You can check all needed additional packages in one of our dockerfiles, for example [here](./utils/docker/images/Dockerfile.archlinux-latest), in the variable called PMDK_DEBS.
> ```

`Dockerfile.ubuntu-22.04` - is more common one



_Code quote:_
```Markdown
Dockerfile.archlinux-latest
```
___
*[`INSTALL.md` line 50 at r1](https://reviewable.io/reviews/pmem/rpma/1970#-N8c6sek42PaZbHRIKWG:-N8c6sek42PaZbHRIKWH:bwa6xs8) ([raw file](https://github.com/pmem/rpma/blob/d61265fb8d6dd1da29320ab5e9ca2fe690dbb975/INSTALL.md#L50)):*
> ```Markdown
> **Note**: libprotobuf-c-dev(el) is needed to run examples: 9 and 9s
> 
> **Note**: Examples that use PMem (3, 4, 5, 7, 9) require only one of the following libraries to run: libpmem or libpmem2. In case of installing both libpmem2 will be used.
> ```

`to be run`



_Code quote:_
```Markdown
to run
```
___
*[`INSTALL.md` line 50 at r1](https://reviewable.io/reviews/pmem/rpma/1970#-N8c6yYs0BnCu4PDH8pR:-N8c6yYs0BnCu4PDH8pS:buua6o8) ([raw file](https://github.com/pmem/rpma/blob/d61265fb8d6dd1da29320ab5e9ca2fe690dbb975/INSTALL.md#L50)):*
> ```Markdown
> **Note**: libprotobuf-c-dev(el) is needed to run examples: 9 and 9s
> 
> **Note**: Examples that use PMem (3, 4, 5, 7, 9) require only one of the following libraries to run: libpmem or libpmem2. In case of installing both libpmem2 will be used.
> ```

`In case of having installed`



_Code quote:_
```Markdown
In case of installing
```
___
*[`INSTALL.md` line 50 at r1](https://reviewable.io/reviews/pmem/rpma/1970#-N8c78nQEdU3hGUBlr5B:-N8c78nQEdU3hGUBlr5C:b-6aiwgl) ([raw file](https://github.com/pmem/rpma/blob/d61265fb8d6dd1da29320ab5e9ca2fe690dbb975/INSTALL.md#L50)):*
> ```Markdown
> **Note**: libprotobuf-c-dev(el) is needed to run examples: 9 and 9s
> 
> **Note**: Examples that use PMem (3, 4, 5, 7, 9) require only one of the following libraries to run: libpmem or libpmem2. In case of installing both libpmem2 will be used.
> ```

`both of them, `



_Code quote:_
```Markdown
both 
```
___
*[`tools/perf/BENCHMARKING.md` line 59 at r1](https://reviewable.io/reviews/pmem/rpma/1970#-N8c5b5lDhASqyrvO9ZS:-N8c5b5lDhASqyrvO9ZT:b-eye2mp) ([raw file](https://github.com/pmem/rpma/blob/d61265fb8d6dd1da29320ab5e9ca2fe690dbb975/tools/perf/BENCHMARKING.md#L59)):*
> ```Markdown
> *Note*: All of the scripts presented in the following sections must be run on the RPMA initiator side.
> 
> In order to test the Python tools you also need:
> ```

`the performance analysis tools`



_Code quote:_
```Markdown
the Python tools
```
___
*[`tools/perf/BENCHMARKING.md` line 63 at r1](https://reviewable.io/reviews/pmem/rpma/1970#-N8c5dfHB8MprNTSwo-G:-N8c5dfHB8MprNTSwo-H:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/d61265fb8d6dd1da29320ab5e9ca2fe690dbb975/tools/perf/BENCHMARKING.md#L63)):*
> ```Markdown
> - pylint
> 
> *Note*: testing the Python tools can be turned off using the CMake 'TESTS_PERF_TOOLS' option
> ```

.



_Code quote:_
```Markdown
the Python tools
```
___
*[`tools/perf/BENCHMARKING.md` line 64 at r1](https://reviewable.io/reviews/pmem/rpma/1970#-N8c6Kle8TnAbviIDX_k:-N8c6Kle8TnAbviIDX_l:b-w4rvbm) ([raw file](https://github.com/pmem/rpma/blob/d61265fb8d6dd1da29320ab5e9ca2fe690dbb975/tools/perf/BENCHMARKING.md#L64)):*
> ```Markdown
> 
> *Note*: testing the Python tools can be turned off using the CMake 'TESTS_PERF_TOOLS' option
> (see [CMake options of the librpma library](DEVELOPMENT.md#cmake-options-of-the-librpma-library) and
> ```

incorrect link (please test all links)
`The 'haichangsi/rpma' repository doesn't contain the 'tools/perf/DEVELOPMENT.md' path in 'install_md'.`



_Code quote:_
```Markdown
DEVELOPMENT.md#cmake-options-of-the-librpma-library
```
___
*[`tools/perf/BENCHMARKING.md` line 65 at r1](https://reviewable.io/reviews/pmem/rpma/1970#-N8c6Sa27A1htQ3a9VnM:-N8c6Sa27A1htQ3a9VnN:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/d61265fb8d6dd1da29320ab5e9ca2fe690dbb975/tools/perf/BENCHMARKING.md#L65)):*
> ```Markdown
> *Note*: testing the Python tools can be turned off using the CMake 'TESTS_PERF_TOOLS' option
> (see [CMake options of the librpma library](DEVELOPMENT.md#cmake-options-of-the-librpma-library) and
> [Configuring CMake options](DEVELOPMENT.md#configuring-cmake-options)).
> ```

.



_Code quote:_
```Markdown
DEVELOPMENT.md#configuring-cmake-options
```

**Review by ldorau — COMMENTED** [review]
Preview:
- https://github.com/haichangsi/rpma/blob/install_md/INSTALL.md and
- https://github.com/haichangsi/rpma/blob/install_md/tools/perf/BENCHMARKING.md

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1970#-:-N8cBdp85v4NTeqhThe3:b-vnz4bu)* status: all files reviewed, 14 unresolved discussions (waiting on @haichangsi and @Patryk717)

**Review by haichangsi — COMMENTED** [review]
yeah, I wanted to add it just now, sorry 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1970#-:-N8cCXZGDqgEf-mU98s0:b-xjbszs)* status: all files reviewed, 14 unresolved discussions (waiting on @ldorau and @Patryk717)

___
*[`INSTALL.md` line 31 at r1](https://reviewable.io/reviews/pmem/rpma/1970#-N8c9OWT42Dfax8NfK9x:-N8cDaml49hUJRtCNGU1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d61265fb8d6dd1da29320ab5e9ca2fe690dbb975/INSTALL.md#L31)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

``BUILD_DOC`` - use back-ticks please
</blockquote></details>

Done.
___
*[`INSTALL.md` line 32 at r1](https://reviewable.io/reviews/pmem/rpma/1970#-N8c9iVe5k-0Vc6SzWP6:-N8cDweN-auZNlBfe-dY:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d61265fb8d6dd1da29320ab5e9ca2fe690dbb975/INSTALL.md#L32)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Change the order of these two links to the opposite one.
</blockquote></details>

Done.
___
*[`INSTALL.md` line 38 at r1](https://reviewable.io/reviews/pmem/rpma/1970#-N8cA5vB8GN2b1JTu0b2:-N8cEMgG3qx0dLtcOIkA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d61265fb8d6dd1da29320ab5e9ca2fe690dbb975/INSTALL.md#L38)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
- libpmem-dev(el) >= 1.6 or libpmem2-dev(el) >= 1.11 for examples: ...

```
- list the examples please
</blockquote></details>

Done.
___
*[`INSTALL.md` line 40 at r1](https://reviewable.io/reviews/pmem/rpma/1970#-N8cAEbd2vTU6vFKkpZK:-N8cENZt1AHgu_BT_sSb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d61265fb8d6dd1da29320ab5e9ca2fe690dbb975/INSTALL.md#L40)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`- libprotobuf-c-dev(el) >= 1.0 for examples: ... ` - list the examples please
</blockquote></details>

Done.
___
*[`INSTALL.md` line 46 at r1](https://reviewable.io/reviews/pmem/rpma/1970#-N8c6jf33O-J8DJzPMo8:-N8cEdOC7Tki5bmZj5P6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d61265fb8d6dd1da29320ab5e9ca2fe690dbb975/INSTALL.md#L46)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`PMDK_DEPS`
</blockquote></details>

Done.
___
*[`INSTALL.md` line 46 at r1](https://reviewable.io/reviews/pmem/rpma/1970#-N8cAcQj-UoNeCjFv_iL:-N8cEqecCAe2lr7O2gki:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d61265fb8d6dd1da29320ab5e9ca2fe690dbb975/INSTALL.md#L46)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
[Dockerfiles](./utils/docker/images/)
```
</blockquote></details>

Done.
___
*[`INSTALL.md` line 46 at r1](https://reviewable.io/reviews/pmem/rpma/1970#-N8cAwjR3J_-zQ9RXC5Y:-N8cEynIDwFwM_XpWjmG:b-axdixe) ([raw file](https://github.com/pmem/rpma/blob/d61265fb8d6dd1da29320ab5e9ca2fe690dbb975/INSTALL.md#L46)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`Dockerfile.ubuntu-22.04` - is more common one
</blockquote></details>

There is no variable called PMDK_DEPS in there, will be after you merge Patryk's PR that's why I chose this one as we discussed on the last daily, you still want me to change it rn?
___
*[`INSTALL.md` line 50 at r1](https://reviewable.io/reviews/pmem/rpma/1970#-N8c6sek42PaZbHRIKWG:-N8cFPkj7Pfx5jtwP6PQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d61265fb8d6dd1da29320ab5e9ca2fe690dbb975/INSTALL.md#L50)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`to be run`
</blockquote></details>

Done.
___
*[`INSTALL.md` line 50 at r1](https://reviewable.io/reviews/pmem/rpma/1970#-N8c6yYs0BnCu4PDH8pR:-N8cFUuE9bmZcejpKJav:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d61265fb8d6dd1da29320ab5e9ca2fe690dbb975/INSTALL.md#L50)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`In case of having installed`
</blockquote></details>

Done.
___
*[`INSTALL.md` line 50 at r1](https://reviewable.io/reviews/pmem/rpma/1970#-N8c78nQEdU3hGUBlr5B:-N8cFVVd4rItUy32665A:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d61265fb8d6dd1da29320ab5e9ca2fe690dbb975/INSTALL.md#L50)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`both of them, `
</blockquote></details>

Done.
___
*[`tools/perf/BENCHMARKING.md` line 59 at r1](https://reviewable.io/reviews/pmem/rpma/1970#-N8c5b5lDhASqyrvO9ZS:-N8cFjZvEathWPS9z7iv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d61265fb8d6dd1da29320ab5e9ca2fe690dbb975/tools/perf/BENCHMARKING.md#L59)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`the performance analysis tools`
</blockquote></details>

Done.
___
*[`tools/perf/BENCHMARKING.md` line 63 at r1](https://reviewable.io/reviews/pmem/rpma/1970#-N8c5dfHB8MprNTSwo-G:-N8cFk856t7_gpHPMM6z:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d61265fb8d6dd1da29320ab5e9ca2fe690dbb975/tools/perf/BENCHMARKING.md#L63)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`tools/perf/BENCHMARKING.md` line 64 at r1](https://reviewable.io/reviews/pmem/rpma/1970#-N8c6Kle8TnAbviIDX_k:-N8cGZfu4LND9fOdWT_d:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d61265fb8d6dd1da29320ab5e9ca2fe690dbb975/tools/perf/BENCHMARKING.md#L64)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

incorrect link (please test all links)
`The 'haichangsi/rpma' repository doesn't contain the 'tools/perf/DEVELOPMENT.md' path in 'install_md'.`
</blockquote></details>

Done.
___
*[`tools/perf/BENCHMARKING.md` line 65 at r1](https://reviewable.io/reviews/pmem/rpma/1970#-N8c6Sa27A1htQ3a9VnM:-N8cG_9e1YqZuP9-EiRJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d61265fb8d6dd1da29320ab5e9ca2fe690dbb975/tools/perf/BENCHMARKING.md#L65)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1970)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @haichangsi, @ldorau, and @Patryk717)

___
*[`INSTALL.md` line 46 at r1](https://reviewable.io/reviews/pmem/rpma/1970#-N8cAcQj-UoNeCjFv_iL:-N8cLHBk2T89GDV7UrR_:b-8nlap4) ([raw file](https://github.com/pmem/rpma/blob/d61265fb8d6dd1da29320ab5e9ca2fe690dbb975/INSTALL.md#L46)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet.
___
*[`INSTALL.md` line 46 at r1](https://reviewable.io/reviews/pmem/rpma/1970#-N8cAwjR3J_-zQ9RXC5Y:-N8cLR4NBxBEDN2xwqU6:bslqa0) ([raw file](https://github.com/pmem/rpma/blob/d61265fb8d6dd1da29320ab5e9ca2fe690dbb975/INSTALL.md#L46)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

There is no variable called PMDK_DEPS in there, will be after you merge Patryk's PR that's why I chose this one as we discussed on the last daily, you still want me to change it rn?
</blockquote></details>

You are right, do not change it. It is OK.

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1970)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi and @Patryk717)

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1970)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @ldorau and @Patryk717)

___
*[`INSTALL.md` line 46 at r1](https://reviewable.io/reviews/pmem/rpma/1970#-N8cAcQj-UoNeCjFv_iL:-N8cSNLMEEeWiA4LvRFp:byuanqd) ([raw file](https://github.com/pmem/rpma/blob/d61265fb8d6dd1da29320ab5e9ca2fe690dbb975/INSTALL.md#L46)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not yet.
</blockquote></details>

Oh sry, I didn't understand you correctly. Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1970)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi and @Patryk717)

___
*[`INSTALL.md` line 16 at r3](https://reviewable.io/reviews/pmem/rpma/1970#-N8cTN-j29RPtFAbODtI:-N8cTN-j29RPtFAbODtJ:b-xv442m) ([raw file](https://github.com/pmem/rpma/blob/c6954c47c08d47e0b6da6184553b5a190eac67ae/INSTALL.md#L16)):*
> ```Markdown
> - libcmocka-dev(el) == 1.1.5-26-g672c5ce (please see [our docker script](./utils/docker/images/install-cmocka.sh) to install the verified revision)
> 
> **Note**: To make sure you have all needed packages installed you can support yourself with [Dockerfiles](./utils/docker/images/) (see the BASE_DEPS and ENV RPMA_DEPS sections)
> ```

`RPMA_DEPS` only



_Code quote:_
```Markdown
ENV RPMA_DEPS
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1970)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau and @Patryk717)

___
*[`INSTALL.md` line 16 at r3](https://reviewable.io/reviews/pmem/rpma/1970#-N8cTN-j29RPtFAbODtI:-N8cX2YT4arIXJhfeY7l:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c6954c47c08d47e0b6da6184553b5a190eac67ae/INSTALL.md#L16)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`RPMA_DEPS` only
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1970#-:-N8cX8i9-lhOWGyHa_Pl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1970#-:-N8goDno0VUyNr5y9R1N:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1970)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
