### PR TITLE
common: organize Dockerfile.Ubuntu-22.04

### PR DESCRIPTION
**Pull request by Patryk717**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1916)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1916)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @Patryk717)

___
*[`utils/docker/images/Dockerfile.ubuntu-22.04` line 27 at r1](https://reviewable.io/reviews/pmem/rpma/1916#-N6MXTbn-fLQFQVCRkQM:-N6MXTbn-fLQFQVCRkQN:b-x7vukc) ([raw file](https://github.com/pmem/rpma/blob/88bd2cbc43ff389d5404a08b321246619797e194/utils/docker/images/Dockerfile.ubuntu-22.04#L27)):*
> ```
> 
> # base deps
> ENV BASE_DEPS "\
> ```

leave it without changes



_Code quote:_
```
ENV BASE_DEPS
```
___
*[`utils/docker/images/Dockerfile.ubuntu-22.04` line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1916#-N6MX_eJ2PZVNLScvES0:-N6MX_eJ2PZVNLScvES1:bw26dum) ([raw file](https://github.com/pmem/rpma/blob/88bd2cbc43ff389d5404a08b321246619797e194/utils/docker/images/Dockerfile.ubuntu-22.04#L39)):*
> ```
> ENV RPMA_DEPS "\
> 	cmake \
> 	cmake-curses-gui \
> ```

Why do we add something new?



_Code quote:_
```
cmake-curses-gui
```

**Review by Patryk717 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1916)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @grom72)

___
*[`utils/docker/images/Dockerfile.ubuntu-22.04` line 27 at r1](https://reviewable.io/reviews/pmem/rpma/1916#-N6MXTbn-fLQFQVCRkQM:-N6MYjfc8gewxfvKg-ws:b2ni9b3) ([raw file](https://github.com/pmem/rpma/blob/88bd2cbc43ff389d5404a08b321246619797e194/utils/docker/images/Dockerfile.ubuntu-22.04#L27)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

leave it without changes
</blockquote></details>

ok 
___
*[`utils/docker/images/Dockerfile.ubuntu-22.04` line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1916#-N6MX_eJ2PZVNLScvES0:-N6MYXPd1c8-I8btMOz5:b-vdhoot) ([raw file](https://github.com/pmem/rpma/blob/88bd2cbc43ff389d5404a08b321246619797e194/utils/docker/images/Dockerfile.ubuntu-22.04#L39)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Why do we add something new?
</blockquote></details>

now i don't know maybe warning or error i try uninstalla and build another one

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1916)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)

**Review by Patryk717 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1916)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @grom72 and @Patryk717)

___
*[`utils/docker/images/Dockerfile.ubuntu-22.04` line 37 at r3](https://reviewable.io/reviews/pmem/rpma/1916#-N6NKXgv-Kf_DM3Ej_Vb:-N6NLFmZ1_-kIcamCbQs:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/82550bb497d613c836a03c934c1d6c37b3973b16/utils/docker/images/Dockerfile.ubuntu-22.04#L37)):*
> ```
> 	whois"
> 
> # Examples_Deps for exampl 9 we need install 'libprotobuf-c-dev'
> ```

Done.
___
*[`utils/docker/images/Dockerfile.ubuntu-22.04` line 55 at r3](https://reviewable.io/reviews/pmem/rpma/1916#-N6NK6z4-eglxClnZ0qf:-N6NL62LCWOWdlgF-U_p:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/82550bb497d613c836a03c934c1d6c37b3973b16/utils/docker/images/Dockerfile.ubuntu-22.04#L55)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

PYTHON_BASE_DEPS
</blockquote></details>

Done.
___
*[`utils/docker/images/Dockerfile.ubuntu-22.04` line 58 at r3](https://reviewable.io/reviews/pmem/rpma/1916#-N6NKAeBD6mItrxRmtTB:-N6NL5jHCtz_OZ2ttdfk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/82550bb497d613c836a03c934c1d6c37b3973b16/utils/docker/images/Dockerfile.ubuntu-22.04#L58)):*
> ```
> 	python3-jinja2"
> 
> ENV TESTS_DEPS "\
> ```

Done.
___
*[`utils/docker/images/Dockerfile.ubuntu-22.04` line 108 at r3](https://reviewable.io/reviews/pmem/rpma/1916#-N6NKrEvBb7a25bSnEhu:-N6NLAY48_8X8mtaXm44:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/82550bb497d613c836a03c934c1d6c37b3973b16/utils/docker/images/Dockerfile.ubuntu-22.04#L108)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

missing empty line at the end of the file
</blockquote></details>

Done.

**Review by osalyk — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1916)* status: all files reviewed, 4 unresolved discussions (waiting on @Patryk717)

___
*[`utils/docker/images/Dockerfile.ubuntu-22.04` line 76 at r4](https://reviewable.io/reviews/pmem/rpma/1916#-N6RKFpi2-yatRP24Dbe:-N6RKFpi2-yatRP24Dbf:b495xlg) ([raw file](https://github.com/pmem/rpma/blob/55dcb6ae78a554a2cc8706a43e1ec9285f617ffd/utils/docker/images/Dockerfile.ubuntu-22.04#L76)):*
> ```
> 	$EXAMPLES_DEPS \
> 	$RPMA_DEPS \
> 	$BASE_PYTHON \
> ```

PYTHON_BASE_DEPS



_Code quote:_
```
BASE_PYTHON
```
___
*[`utils/docker/images/Dockerfile.ubuntu-22.04` line 77 at r4](https://reviewable.io/reviews/pmem/rpma/1916#-N6RKLPQ5zFzPZvBk2st:-N6RKLPQ5zFzPZvBk2su:bh76oqz) ([raw file](https://github.com/pmem/rpma/blob/55dcb6ae78a554a2cc8706a43e1ec9285f617ffd/utils/docker/images/Dockerfile.ubuntu-22.04#L77)):*
> ```
> 	$RPMA_DEPS \
> 	$BASE_PYTHON \
> 	$TESTS_DEPS \
> ```

TOOLS_TESTS_DEPS



_Code quote:_
```
TESTS_DEPS
```

**Review by osalyk — CHANGES_REQUESTED** [review]
Please change commit message, for example:
common: organize Dockerfile.Ubuntu-22.04

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1916#-:-N6S4ZTQ6xVAeYG0-2Z9:b-q6e0fw)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @grom72 and @Patryk717)

___
*[`utils/docker/images/Dockerfile.ubuntu-22.04` line 37 at r6](https://reviewable.io/reviews/pmem/rpma/1916#-N6S59wf4b6aMTISv84N:-N6S59wg-QhC10VuG8F6:bcq8ld2) ([raw file](https://github.com/pmem/rpma/blob/5c1f90da95c3580d02ddf6485925d7c94263b313/utils/docker/images/Dockerfile.ubuntu-22.04#L37)):*
> ```
> 	whois"
> 
> # RPMA deps tools
> ```

RPMA deps libraries



_Code quote:_
```
RPMA deps tools
```
___
*[`utils/docker/images/Dockerfile.ubuntu-22.04` line 55 at r6](https://reviewable.io/reviews/pmem/rpma/1916#-N6S5QpC7ZIq4o003diy:-N6S5QpC7ZIq4o003diz:b-aywit8) ([raw file](https://github.com/pmem/rpma/blob/5c1f90da95c3580d02ddf6485925d7c94263b313/utils/docker/images/Dockerfile.ubuntu-22.04#L55)):*
> ```
> 	libprotobuf-c-dev"
> 
> #Base tools Python Install
> ```

# base Python tools



_Code quote:_
```
#Base tools Python Install
```
___
*[`utils/docker/images/Dockerfile.ubuntu-22.04` line 61 at r6](https://reviewable.io/reviews/pmem/rpma/1916#-N6S5t2D7COL-8u0t-YO:-N6S5t2D7COL-8u0t-YP:bgepchy) ([raw file](https://github.com/pmem/rpma/blob/5c1f90da95c3580d02ddf6485925d7c94263b313/utils/docker/images/Dockerfile.ubuntu-22.04#L61)):*
> ```
> 	python3-pytest"
> 
> # Tools Python Deps
> ```

# Python deps



_Code quote:_
```
# Tools Python Deps
```

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1916)* status: all files reviewed, 8 unresolved discussions (waiting on @osalyk and @Patryk717)

___
*[`utils/docker/images/Dockerfile.ubuntu-22.04` line 55 at r6](https://reviewable.io/reviews/pmem/rpma/1916#-N6S9AZH1rGabxloDJCO:-N6S9AZH1rGabxloDJCP:b-6akd36) ([raw file](https://github.com/pmem/rpma/blob/5c1f90da95c3580d02ddf6485925d7c94263b313/utils/docker/images/Dockerfile.ubuntu-22.04#L55)):*
> ```
> 	libprotobuf-c-dev"
> 
> #Base tools Python Install
> ```

Performance tools deps



_Code quote:_
```
Base tools Python Install
```
___
*[`utils/docker/images/Dockerfile.ubuntu-22.04` line 55 at r6](https://reviewable.io/reviews/pmem/rpma/1916#-N6S5QpC7ZIq4o003diy:-N6S9eLx4GsfMI68QQx_:bj9kz2) ([raw file](https://github.com/pmem/rpma/blob/5c1f90da95c3580d02ddf6485925d7c94263b313/utils/docker/images/Dockerfile.ubuntu-22.04#L55)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

# base Python tools
</blockquote></details>

I think we do not need to use a "Python" word, it is more important to say that these deps are related to the performance benchmarking environment toolset.
___
*[`utils/docker/images/Dockerfile.ubuntu-22.04` line 61 at r6](https://reviewable.io/reviews/pmem/rpma/1916#-N6S9I5y8x1ZL3vU_fba:-N6S9I5y8x1ZL3vU_fbb:b-wvs81e) ([raw file](https://github.com/pmem/rpma/blob/5c1f90da95c3580d02ddf6485925d7c94263b313/utils/docker/images/Dockerfile.ubuntu-22.04#L61)):*
> ```
> 	python3-pytest"
> 
> # Tools Python Deps
> ```

Performance tools python deps



_Code quote:_
```
Tools Python Deps
```

**Review by Patryk717 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1916)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @grom72 and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1916#-N6NkDUBBWJmEWHyjbdG:-N6Rec3q3jt45IWo7D1-:b-896fix) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

@patryk717 please add a comment to every ``ENV ``
</blockquote></details>

Done.

___
___
*[`utils/docker/images/Dockerfile.ubuntu-22.04` line 62 at r3](https://reviewable.io/reviews/pmem/rpma/1916#-N6NKO8J4Al0GpI6vtIY:-N6Reik5A2tKjMjgTY05:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/82550bb497d613c836a03c934c1d6c37b3973b16/utils/docker/images/Dockerfile.ubuntu-22.04#L62)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Do we need this for python or for a normal build?
</blockquote></details>

Done.
___
*[`utils/docker/images/Dockerfile.ubuntu-22.04` line 76 at r4](https://reviewable.io/reviews/pmem/rpma/1916#-N6RKFpi2-yatRP24Dbe:-N6RZVvT1ofNnT2hyU0N:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/55dcb6ae78a554a2cc8706a43e1ec9285f617ffd/utils/docker/images/Dockerfile.ubuntu-22.04#L76)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

PYTHON_BASE_DEPS
</blockquote></details>

Done.
___
*[`utils/docker/images/Dockerfile.ubuntu-22.04` line 77 at r4](https://reviewable.io/reviews/pmem/rpma/1916#-N6RKLPQ5zFzPZvBk2st:-N6RZWB14uz36j9jrlDE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/55dcb6ae78a554a2cc8706a43e1ec9285f617ffd/utils/docker/images/Dockerfile.ubuntu-22.04#L77)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

TOOLS_TESTS_DEPS
</blockquote></details>

Done.
___
*[`utils/docker/images/Dockerfile.ubuntu-22.04` line 37 at r6](https://reviewable.io/reviews/pmem/rpma/1916#-N6S59wf4b6aMTISv84N:-N6SCPLG1u4Xc5m-MLN9:b-7rl0kd) ([raw file](https://github.com/pmem/rpma/blob/5c1f90da95c3580d02ddf6485925d7c94263b313/utils/docker/images/Dockerfile.ubuntu-22.04#L37)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

RPMA deps libraries
</blockquote></details>

done
___
*[`utils/docker/images/Dockerfile.ubuntu-22.04` line 55 at r6](https://reviewable.io/reviews/pmem/rpma/1916#-N6S5QpC7ZIq4o003diy:-N6SCdarEUrcnLxm4EHo:b-6akd36) ([raw file](https://github.com/pmem/rpma/blob/5c1f90da95c3580d02ddf6485925d7c94263b313/utils/docker/images/Dockerfile.ubuntu-22.04#L55)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I think we do not need to use a "Python" word, it is more important to say that these deps are related to the performance benchmarking environment toolset.
</blockquote></details>

Performance tools deps
___
*[`utils/docker/images/Dockerfile.ubuntu-22.04` line 55 at r6](https://reviewable.io/reviews/pmem/rpma/1916#-N6S9AZH1rGabxloDJCO:-N6SCf5b-rlXai6LUx77:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5c1f90da95c3580d02ddf6485925d7c94263b313/utils/docker/images/Dockerfile.ubuntu-22.04#L55)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Performance tools deps
</blockquote></details>

Done.
___
*[`utils/docker/images/Dockerfile.ubuntu-22.04` line 61 at r6](https://reviewable.io/reviews/pmem/rpma/1916#-N6S5t2D7COL-8u0t-YO:-N6SC3eUDDI8aaU4tPfu:b-wvs81e) ([raw file](https://github.com/pmem/rpma/blob/5c1f90da95c3580d02ddf6485925d7c94263b313/utils/docker/images/Dockerfile.ubuntu-22.04#L61)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

# Python deps
</blockquote></details>

Performance tools python deps
___
*[`utils/docker/images/Dockerfile.ubuntu-22.04` line 61 at r6](https://reviewable.io/reviews/pmem/rpma/1916#-N6S9I5y8x1ZL3vU_fba:-N6SCubyE-m1pJLiu83H:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5c1f90da95c3580d02ddf6485925d7c94263b313/utils/docker/images/Dockerfile.ubuntu-22.04#L61)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Performance tools python deps
</blockquote></details>

Done.

**Review by osalyk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1916)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @grom72 and @Patryk717)

___
*[`utils/docker/images/Dockerfile.ubuntu-22.04` line 55 at r6](https://reviewable.io/reviews/pmem/rpma/1916#-N6S5QpC7ZIq4o003diy:-N6SDmiD7zzp4p8dbmHw:by69ypn) ([raw file](https://github.com/pmem/rpma/blob/5c1f90da95c3580d02ddf6485925d7c94263b313/utils/docker/images/Dockerfile.ubuntu-22.04#L55)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

Performance tools deps
</blockquote></details>

# performance tools deps
___
*[`utils/docker/images/Dockerfile.ubuntu-22.04` line 61 at r6](https://reviewable.io/reviews/pmem/rpma/1916#-N6S5t2D7COL-8u0t-YO:-N6SDpyW7uNJXb3cppL_:b-l8e3rm) ([raw file](https://github.com/pmem/rpma/blob/5c1f90da95c3580d02ddf6485925d7c94263b313/utils/docker/images/Dockerfile.ubuntu-22.04#L61)):*
<details><summary><i>Previously, Patryk717 wrote…</i></summary><blockquote>

Performance tools python deps
</blockquote></details>

performance tools python deps

**Review by Patryk717 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1916)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`utils/docker/images/Dockerfile.ubuntu-22.04` line 55 at r6](https://reviewable.io/reviews/pmem/rpma/1916#-N6S5QpC7ZIq4o003diy:-N6SEaAL5WGHE7gT46gH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5c1f90da95c3580d02ddf6485925d7c94263b313/utils/docker/images/Dockerfile.ubuntu-22.04#L55)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

# performance tools deps
</blockquote></details>

Done.
___
*[`utils/docker/images/Dockerfile.ubuntu-22.04` line 61 at r6](https://reviewable.io/reviews/pmem/rpma/1916#-N6S5t2D7COL-8u0t-YO:-N6SE_TUD6LYch0Z7mbK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5c1f90da95c3580d02ddf6485925d7c94263b313/utils/docker/images/Dockerfile.ubuntu-22.04#L61)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

performance tools python deps
</blockquote></details>

Done.

**Review by osalyk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1916)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @grom72, @osalyk, and @Patryk717)

___
*[`-- commits` line 2 at r8](https://reviewable.io/reviews/pmem/rpma/1916#-N6SElS52A5s6y1I8YIl):*
organize



_Suggestion:_
```
- 16e66eb: common: organize Dockerfile.Ubuntu-22.04
```

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1916)* status: all files reviewed, 2 unresolved discussions (waiting on @Patryk717)

___
*[`utils/docker/images/Dockerfile.ubuntu-22.04` line 26 at r8](https://reviewable.io/reviews/pmem/rpma/1916#-N6SGT3y5kiHXUamaICk:-N6SGT3y5kiHXUamaICl:b45h) ([raw file](https://github.com/pmem/rpma/blob/16e66ebbb6ea4efd62425b14c14d09cb52cdfeb3/utils/docker/images/Dockerfile.ubuntu-22.04#L26)):*
> ```
> ENV PATH /home/user/.local/bin:$PATH
> 
> # base deps linux
> ```





_Suggestion:_
```
base Linux deps
```
___
*[`utils/docker/images/Dockerfile.ubuntu-22.04` line 37 at r8](https://reviewable.io/reviews/pmem/rpma/1916#-N6SGMEv6fyZR473duSE:-N6SGMEv6fyZR473duSF:undefined) ([raw file](https://github.com/pmem/rpma/blob/16e66ebbb6ea4efd62425b14c14d09cb52cdfeb3/utils/docker/images/Dockerfile.ubuntu-22.04#L37)):*
> ```
> 	whois"
> 
> # RPMA deps libraries
> ```





_Suggestion:_
```
librpma library deps
```

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1916)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1916#-:-N6S_5OtC-IulwFQmHhn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1916)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)

**Review by haichangsi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1916#-:-N6Sroot72KcaASzF-kF:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)

**Review by grom72 — APPROVED** [review]
Let's wait for final approval from @ldorau 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1916#-:-N6gH9XS-fh-Jpri6Pvd:b8ktdw8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r10, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1916)* status: all files reviewed, 1 unresolved discussion (waiting on @Patryk717)

___
*[`-- commits` line 2 at r10](https://reviewable.io/reviews/pmem/rpma/1916#-N7GBEIGDfMv_aGWg3SZ):*
ubuntu 

(the name of the file is Dockerfile.ubuntu-22.04)



_Code quote:_
```
Ubuntu
```

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1916)* status: all files reviewed, 1 unresolved discussion (waiting on @Patryk717)

**Review by Patryk717 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1916)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ldorau)

___
*[`-- commits` line 2 at r10](https://reviewable.io/reviews/pmem/rpma/1916#-N7GBEIGDfMv_aGWg3SZ):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

ubuntu 

(the name of the file is Dockerfile.ubuntu-22.04)
</blockquote></details>

Done.
___
*[`utils/docker/images/Dockerfile.ubuntu-22.04` line 26 at r8](https://reviewable.io/reviews/pmem/rpma/1916#-N6SGT3y5kiHXUamaICk:-N6SHOoz3cag0NcO10BH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/16e66ebbb6ea4efd62425b14c14d09cb52cdfeb3/utils/docker/images/Dockerfile.ubuntu-22.04#L26)):*
> ```
> ENV PATH /home/user/.local/bin:$PATH
> 
> # base deps linux
> ```

Done.
___
*[`utils/docker/images/Dockerfile.ubuntu-22.04` line 37 at r8](https://reviewable.io/reviews/pmem/rpma/1916#-N6SGMEv6fyZR473duSE:-N6SHWJzBTB430XhtCVN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/16e66ebbb6ea4efd62425b14c14d09cb52cdfeb3/utils/docker/images/Dockerfile.ubuntu-22.04#L37)):*
> ```
> 	whois"
> 
> # RPMA deps libraries
> ```

Done.

**Review by grom72 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1916)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1916)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Patryk717)

**Pull request merged**
