### PR TITLE
test: add rpma_send MT test

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1719)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 11 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1719)* status: 11 of 12 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`tests/multithreaded/conn/rpma_send.c` line 44 at r1](https://reviewable.io/reviews/pmem/rpma/1719#-N0pPTyd-QbaK9zIYUVt:-N0pPTyd-QbaK9zIYUVu:bc5oj0p) ([raw file](https://github.com/pmem/rpma/blob/844e595d42839463dcecd4984f1cbfbd463a298f/tests/multithreaded/conn/rpma_send.c#L44)):*
> ```C
> 
> 	if (wc.status != IBV_WC_SUCCESS) {
> 		MTT_ERR_MSG(result, "rpma_send() failed", -1);
> ```

First, check the opcode, then its status.



_Suggestion:_
```C
	if (wc.opcode != IBV_WC_SEND) {
		MTT_ERR_MSG(result, "unexpected wc.opcode value", -1);
		return;
	}
	
	if (wc.status != IBV_WC_SUCCESS) {
		MTT_ERR_MSG(result, "rpma_send() failed", -1);
		return;
	}
```
___
*[`tests/multithreaded/conn/rpma_write_read.c` line 70 at r1](https://reviewable.io/reviews/pmem/rpma/1719#-N0pQ8kb00DRME7Zz_8F:-N0pQ8kb00DRME7Zz_8G:b-vlk7uw) ([raw file](https://github.com/pmem/rpma/blob/844e595d42839463dcecd4984f1cbfbd463a298f/tests/multithreaded/conn/rpma_write_read.c#L70)):*
> ```C
> 		MTT_ERR_MSG(result, "rpma_cq_wait() failed", ret);
> 		return;
> 	}
> ```

I think that the repeatable sequence of ``rpma_cq_get_wc`` , ``if (wc.status != IBV_WC_SUCCESS) `` and ``if (wc.opcode != IBV_WC_RDMA_READ) {`` should be moved to a separate function in "common".



_Code quote:_
```C
rpma_cq_get_wc
```
___
*[`tests/multithreaded/conn/rpma_write_read.c` line 79 at r1](https://reviewable.io/reviews/pmem/rpma/1719#-N0pPkyn-_7RvCthQAbk:-N0pPkyn-_7RvCthQAbl:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/844e595d42839463dcecd4984f1cbfbd463a298f/tests/multithreaded/conn/rpma_write_read.c#L79)):*
> ```C
> 	}
> 
> 	if (wc.status != IBV_WC_SUCCESS) {
> ```

.



_Suggestion:_
```C
	if (wc.opcode != IBV_WC_RDMA_READ) {
		MTT_ERR_MSG(result, "unexpected wc.opcode value", -1);
		return;
	}
	
	if (wc.status != IBV_WC_SUCCESS) {
		MTT_ERR_MSG(result, "rpma_read() failed", -1);
		return;
	}
```

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1719)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1719#-N0pQra-EY3Pn28sLzyi:-N0pQra-EY3Pn28sLzyj:bzeyy9u) (no related file):*
wait_and_validate will save a lot of redundant code -> see our examples



_Code quote (from tests/multithreaded/conn/rpma_write_read.c):_
```C
	/* wait for a completion of the RDMA write */
	ret = rpma_cq_get_wc(ts->cq, 1, &wc, NULL);
	if (ret) {
		MTT_ERR_MSG(result, "rpma_cq_get_wc() failed", ret);
		return;
	}

	if (wc.status != IBV_WC_SUCCESS) {
		MTT_ERR_MSG(result, "rpma_write() failed", -1);
		return;
	}

	if (wc.opcode != IBV_WC_RDMA_WRITE) {
		MTT_ERR_MSG(result, "unexpected wc.opcode value", -1);
		return;
	}
```

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1719)* status: 2 of 12 files reviewed, 4 unresolved discussions (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1719#-N0pQra-EY3Pn28sLzyi:-N1DF6KB1Av5uXT9oiHn:b-896fix) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

wait_and_validate will save a lot of redundant code -> see our examples
</blockquote></details>

Done.

---
___
*[`tests/multithreaded/conn/rpma_send.c` line 44 at r1](https://reviewable.io/reviews/pmem/rpma/1719#-N0pPTyd-QbaK9zIYUVt:-N1D7PX8-HQU9skMomVE:b-dj4dt8) ([raw file](https://github.com/pmem/rpma/blob/844e595d42839463dcecd4984f1cbfbd463a298f/tests/multithreaded/conn/rpma_send.c#L44)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

First, check the opcode, then its status.
</blockquote></details>

No ... "*If the completion status is other than IBV_WC_SUCCESS, only the following attributes are valid: wr_id, status, qp_num, and vendor_err.*"
___
*[`tests/multithreaded/conn/rpma_write_read.c` line 70 at r1](https://reviewable.io/reviews/pmem/rpma/1719#-N0pQ8kb00DRME7Zz_8F:-N1DF7Zq2VRfT8_m0GIv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/844e595d42839463dcecd4984f1cbfbd463a298f/tests/multithreaded/conn/rpma_write_read.c#L70)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I think that the repeatable sequence of ``rpma_cq_get_wc`` , ``if (wc.status != IBV_WC_SUCCESS) `` and ``if (wc.opcode != IBV_WC_RDMA_READ) {`` should be moved to a separate function in "common".
</blockquote></details>

Done.
___
*[`tests/multithreaded/conn/rpma_write_read.c` line 79 at r1](https://reviewable.io/reviews/pmem/rpma/1719#-N0pPkyn-_7RvCthQAbk:-N1D8ITH3LwmKZ5UyKOB:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/844e595d42839463dcecd4984f1cbfbd463a298f/tests/multithreaded/conn/rpma_write_read.c#L79)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

.

**Review by grom72 — APPROVED** [review]
:goat: 

> Reviewed 10 of 10 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1719#-:-N1DSgpZ8jWKJtSJZbSj:bdycpsm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> Reviewed 6 of 10 files at r3, 4 of 4 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1719)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
> Reviewed 2 of 12 files at r1, 2 of 10 files at r3, 4 of 4 files at r5, 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1719)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[`tests/multithreaded/conn/server_rpma_empty.c` line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1719#-N1EJ0Fi41f69WsIJsYS:-N1EJ0FjDx8AbkZeke-R:bb6ht37) ([raw file](https://github.com/pmem/rpma/blob/844e595d42839463dcecd4984f1cbfbd463a298f/tests/multithreaded/conn/server_rpma_empty.c#L2)):*
> ```C
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2020-2021, Intel Corporation */
> ```

2022
___
*[`tests/multithreaded/conn/server_rpma_send.c` line 2 at r6](https://reviewable.io/reviews/pmem/rpma/1719#-N1EINsMBA7lBo5jDG2c:-N1EINsMBA7lBo5jDG2d:bb6ht37) ([raw file](https://github.com/pmem/rpma/blob/3a83156d7ca0746d32454bb953fca69071188cb5/tests/multithreaded/conn/server_rpma_send.c#L2)):*
> ```C
> // SPDX-License-Identifier: BSD-3-Clause
> /* Copyright 2020-2021, Intel Corporation */
> ```

2022

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1719)* status: 10 of 12 files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`tests/multithreaded/conn/server_rpma_empty.c` line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1719#-N1EJ0Fi41f69WsIJsYS:-N1EKWnT4BIEihvFK78q:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/844e595d42839463dcecd4984f1cbfbd463a298f/tests/multithreaded/conn/server_rpma_empty.c#L2)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

2022
</blockquote></details>

Done.
___
*[`tests/multithreaded/conn/server_rpma_send.c` line 2 at r6](https://reviewable.io/reviews/pmem/rpma/1719#-N1EINsMBA7lBo5jDG2c:-N1EKXCAETtklhttRgez:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3a83156d7ca0746d32454bb953fca69071188cb5/tests/multithreaded/conn/server_rpma_send.c#L2)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

2022
</blockquote></details>

Done.

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1719#-:-N1EN7xw0mJ_C1Mf7jJR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
