### PR TITLE
test: remove duplicate macros in info-common.h

### PR DESCRIPTION
**Pull request by yangx-jy**
some macros in info-common.h has been defined by test-common.h.

Signed-off-by: Xiao Yang <yangx.jy@fujitsu.com>

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1198)

### CODE REVIEW

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1198#-:-MhTXE4Q220zQTIsNulg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1198)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1198#-Mhn0ujx2vrg5NyIO1Rn:-Mhn0ujx2vrg5NyIO1Ro:b-ycross) (no related file):*
You have missed the same issue are also here:
- https://github.com/pmem/rpma/blob/master/tests/unit/ep/ep-common.h#L13

---

**Review by ldorau — COMMENTED** [review]
> Reviewed 3 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1198)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @janekmi, @ldorau, and @yangx-jy)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1198)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1198#-:-Mia_Nv8ArAWxwUQv65E:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1198)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1198#-Mhn0ujx2vrg5NyIO1Rn:-MiahElS41fUhdnToxHJ:b-3p17t8) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You have missed the same issue are also here:
- https://github.com/pmem/rpma/blob/master/tests/unit/ep/ep-common.h#L13
</blockquote></details>

@janekmi ping

---

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1198#-:-Mick0M27wRoG1A771NZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Pull request merged**
