### PR TITLE
test: verify remote_addr and rkey values in the ibv_post_send_mock()

### PR DESCRIPTION
**Pull request by osalyk**
Requires:
- [x]  #882

Ref: #889 

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/893)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/893)* status: 0 of 13 files reviewed, 1 unresolved discussion (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/893#-MTiewnv-QkrwmlQjroc:-MTiewnv-QkrwmlQjrod:bymv1jp) (no related file):*
please rebase

---

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/893)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/893#-MTiewnv-QkrwmlQjroc:-MTitfrX4jkuw70jF0Uc:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

please rebase
</blockquote></details>

Done.

---

**Review by ldorau — APPROVED** [review]
> Reviewed 5 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/893)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/893#-:-MTjJXk6-h5vw6KLonIK:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/893)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tests/unit/mr/mr-common.h, line 46 at r2](https://reviewable.io/reviews/pmem/rpma/893#-MTjPx322n5CjhEdvY6d:-MTjPx33-f1dixCJiTP2:b9m0uj9) ([raw file](https://github.com/pmem/rpma/blob/3a8bf13baf32c811750a0f970bb753c4901ea8da/tests/unit/mr/mr-common.h#L46)):*
> ```objc
> #define MOCK_OP_CONTEXT		(void *)0xC417
> #define MOCK_DESC		(void *)0xC418
> #define MOCK_RADDR		(uint64_t)0x01020304050607
> ```

Since it is a 64-bit value I think it will be better to write it this way: `0x0001020304050607`

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/893)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tests/unit/mr/mr-common.h, line 46 at r2](https://reviewable.io/reviews/pmem/rpma/893#-MTjPx322n5CjhEdvY6d:-MTjRMNU360tvXXsP1gS:b-c0sxu) ([raw file](https://github.com/pmem/rpma/blob/3a8bf13baf32c811750a0f970bb753c4901ea8da/tests/unit/mr/mr-common.h#L46)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Since it is a 64-bit value I think it will be better to write it this way: `0x0001020304050607`
</blockquote></details>

or even `0x0102030405060708`

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/893)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[tests/unit/mr/mr-common.h, line 46 at r2](https://reviewable.io/reviews/pmem/rpma/893#-MTjPx322n5CjhEdvY6d:-MTjW9RS9Th40R6JWAxP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3a8bf13baf32c811750a0f970bb753c4901ea8da/tests/unit/mr/mr-common.h#L46)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

or even `0x0102030405060708` 
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/893)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tests/unit/mr/mr-common.h, line 46 at r2](https://reviewable.io/reviews/pmem/rpma/893#-MTjPx322n5CjhEdvY6d:-MTjWSTu7Nf9_aUDfOCn:br7sr4m) ([raw file](https://github.com/pmem/rpma/blob/3a8bf13baf32c811750a0f970bb753c4901ea8da/tests/unit/mr/mr-common.h#L46)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/893)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[tests/unit/mr/mr-common.h, line 46 at r2](https://reviewable.io/reviews/pmem/rpma/893#-MTjPx322n5CjhEdvY6d:-MTjWfp6AQ4LSXh8clxL:bo4hs2p) ([raw file](https://github.com/pmem/rpma/blob/3a8bf13baf32c811750a0f970bb753c4901ea8da/tests/unit/mr/mr-common.h#L46)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not yet
</blockquote></details>

I forgot to do git push. Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/893#-:-MTjXWoO-W8M-TNLDcNJ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tests/unit/mr/mr-common.h, line 46 at r2](https://reviewable.io/reviews/pmem/rpma/893#-MTjPx322n5CjhEdvY6d:-MTjXFrPAoxavM29BHtW:b-wujuws) ([raw file](https://github.com/pmem/rpma/blob/3a8bf13baf32c811750a0f970bb753c4901ea8da/tests/unit/mr/mr-common.h#L46)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

I forgot to do git push. Done.
</blockquote></details>

@ldorau `0x0102030405060708` is not correct. The value is derived from the DESC_EXP_PMEM/DRAM above.

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/893)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/893)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/893)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tests/unit/mr/mr-common.h, line 46 at r3](https://reviewable.io/reviews/pmem/rpma/893#-MTjYbOW0HoWjYy53lxs:-MTjYbOW0HoWjYy53lxt:bkmpfbc) ([raw file](https://github.com/pmem/rpma/blob/7e3253b8f5668826bb12d7551dc343f956339b66/tests/unit/mr/mr-common.h#L46)):*
> ```objc
> #define MOCK_OP_CONTEXT		(void *)0xC417
> #define MOCK_DESC		(void *)0xC418
> #define MOCK_RADDR		(uint64_t)0x0001020304050607
> ```

Add a newline and a comment before these two.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/893)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[tests/unit/mr/mr-common.h, line 46 at r3](https://reviewable.io/reviews/pmem/rpma/893#-MTjYbOW0HoWjYy53lxs:-MTjmCz2202EePtVug-B:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7e3253b8f5668826bb12d7551dc343f956339b66/tests/unit/mr/mr-common.h#L46)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Add a newline and a comment before these two.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/893)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/893#-:-MTkTRJ8-PIeZsxlEOi8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
