### PR TITLE
test: add librpma_[init/fini]() unit tests

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/287)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/287)* status: 2 of 5 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tests/unit/constructor/constructor.c, line 5 at r1](https://reviewable.io/reviews/pmem/rpma/287#-MFGlwpw3l8h768IRqRm:-MFUW-pGAlxM04sBx1Pi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a08c0cc4cdfa75fbdb24865fc76397131d484439/tests/unit/constructor/constructor.c#L5)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> constructor
> ```
librpma_constructor?
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/287)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[tests/unit/librpma_constructor/librpma_constructor.c, line 14 at r2](https://reviewable.io/reviews/pmem/rpma/287#-MFUkB862_AV_ogKQRZV:-MFUkB862_AV_ogKQRZW:bqd8luh) ([raw file](https://github.com/pmem/rpma/blob/7ab8abf9834fc9fc20b19fb0371b5986b198868f/tests/unit/librpma_constructor/librpma_constructor.c#L14)):*
> ```C
> 
> /*
>  * init_test - librpma_init() unit test
> ```

According to our newest naming rules, I think it will be better to name it e.g. init__success. What do you think?
___
*[tests/unit/librpma_constructor/librpma_constructor.c, line 14 at r2](https://reviewable.io/reviews/pmem/rpma/287#-MFUkQw6-CCrD9WGDceC:-MFUkQw6-CCrD9WGDceD:b-dy8e5f) ([raw file](https://github.com/pmem/rpma/blob/7ab8abf9834fc9fc20b19fb0371b5986b198868f/tests/unit/librpma_constructor/librpma_constructor.c#L14)):*
> ```C
> 
> /*
>  * init_test - librpma_init() unit test
> ```

`-` -> `--`
___
*[tests/unit/librpma_constructor/librpma_constructor.c, line 24 at r2](https://reviewable.io/reviews/pmem/rpma/287#-MFUkV-UBPz3pW_2CUP2:-MFUkV-UBPz3pW_2CUP3:b32v7p) ([raw file](https://github.com/pmem/rpma/blob/7ab8abf9834fc9fc20b19fb0371b5986b198868f/tests/unit/librpma_constructor/librpma_constructor.c#L24)):*
> ```C
> 
> /*
>  * fini_test - librpma_fini() unit test
> ```

..

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/287)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, and @osalyk)

___
*[tests/unit/librpma_constructor/librpma_constructor.c, line 14 at r2](https://reviewable.io/reviews/pmem/rpma/287#-MFUkQw6-CCrD9WGDceC:-MFUmJ6yBP0XiijqqvaW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/7ab8abf9834fc9fc20b19fb0371b5986b198868f/tests/unit/librpma_constructor/librpma_constructor.c#L14)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`-` -> `--`
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/287)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[tests/unit/librpma_constructor/librpma_constructor.c, line 14 at r2](https://reviewable.io/reviews/pmem/rpma/287#-MFUoXGv-bUd-Kppi1hd:-MFUoXGw0I9rPId5Zk8L:b-1bq8h9) ([raw file](https://github.com/pmem/rpma/blob/7ab8abf9834fc9fc20b19fb0371b5986b198868f/tests/unit/librpma_constructor/librpma_constructor.c#L14)):*
> ```C
> 
> /*
>  * init_test - librpma_init() unit test
> ```

`_` -> `__` (double underscore)

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, 2 of 3 files at r2, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/287)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/287#-:-MFV5UJeDCgUbouP8TL-:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/287#-:-MFV5ksM1hNsC_0CK2zD:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Pull request merged**
