### PR TITLE
tools: escape '_' in figure titles

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1229)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1229)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1229#-MiLzgJy74tSj2WoriTQ:-MiLzgJy74tSj2WoriTR:bhl3ikj) (no related file):*
CI builds failed

---

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1229)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1229#-MiLzgJy74tSj2WoriTQ:-MiMBnfK-hKzqEcQ5a0I:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

CI builds failed
</blockquote></details>

Done.

---

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1229#-:-MiMHBaG6xFz5xUvhudH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1229)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/lib/figure.py, line 257 at r2](https://reviewable.io/reviews/pmem/rpma/1229#-MiMSpoY5YjsZl0YGMhc:-MiMSpoY5YjsZl0YGMhd:b-ya25mz) ([raw file](https://github.com/pmem/rpma/blob/3c7d6debbb286da1ce345ac4fc7760dd64162ea8/tools/perf/lib/figure.py#L257)):*
> ```Python
>         """Combine a Figure's png and data table into a single HTML snippet"""
>         html = "<h4>Figure {}. {}</h4>".format(figno,
>                                                self.title.replace('_', '\\_'))
> ```

I recommend creating a static method and use it everywhere where it is needed e.g.:

```python
    @staticmethod
    def escape(string):
        return string.replace('_', '\\_')
```

Note: In this class, it is used at least twice.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1229)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi and @ldorau)

___
*[tools/perf/lib/figure.py, line 257 at r2](https://reviewable.io/reviews/pmem/rpma/1229#-MiMSpoY5YjsZl0YGMhc:-MiQ79Gv8un-ntljtCIH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3c7d6debbb286da1ce345ac4fc7760dd64162ea8/tools/perf/lib/figure.py#L257)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I recommend creating a static method and use it everywhere where it is needed e.g.:

```python
    @staticmethod
    def escape(string):
        return string.replace('_', '\\_')
```

Note: In this class, it is used at least twice.
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1229)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tools/perf/lib/figure.py, line 93 at r3](https://reviewable.io/reviews/pmem/rpma/1229#-MiQ7pCL8c2vZFl3R22G:-MiQ7pCL8c2vZFl3R22H:b-aqr73h) ([raw file](https://github.com/pmem/rpma/blob/0025a68b290a1d12011f51613dff6648588ea567/tools/perf/lib/figure.py#L93)):*
> ```
>     @staticmethod
>     def escape(string):
>         return string.replace('_', '\\_')
> ```

```
************* Module lib.figure
/rpma/tools/perf/lib/figure.py:92:4: C0116: Missing function or method docstring (missing-function-docstring)
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1229)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/lib/figure.py, line 93 at r3](https://reviewable.io/reviews/pmem/rpma/1229#-MiQ7pCL8c2vZFl3R22G:-MiQBilABPQBOuQ-H7A8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0025a68b290a1d12011f51613dff6648588ea567/tools/perf/lib/figure.py#L93)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>     @staticmethod
>     def escape(string):
>         return string.replace('_', '\\_')
> ```

```
************* Module lib.figure
/rpma/tools/perf/lib/figure.py:92:4: C0116: Missing function or method docstring (missing-function-docstring)
```

</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1229)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1229)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/lib/figure.py, line 93 at r4](https://reviewable.io/reviews/pmem/rpma/1229#-MiQMMXV4fsmh89_dPMC:-MiQMMXV4fsmh89_dPMD:b-rgcc4x) ([raw file](https://github.com/pmem/rpma/blob/e16b6e6d38d73017baf8a13dedfbf4966b0ea7d0/tools/perf/lib/figure.py#L93)):*
> ```Python
>     @staticmethod
>     def escape(string):
>         """Escape special characters"""
> ```

... markdown special...

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1229)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/figure.py, line 93 at r4](https://reviewable.io/reviews/pmem/rpma/1229#-MiQMMXV4fsmh89_dPMC:-MiQSgEq-z8N6NlttTku:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e16b6e6d38d73017baf8a13dedfbf4966b0ea7d0/tools/perf/lib/figure.py#L93)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

... markdown special...
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1229#-:-MiQZ_Ys1DqCbrTk5oDe:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
