### PR TITLE
common: test Python perf tools XXX

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1120)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 3 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1120)* status: 3 of 10 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[CMakeLists.txt, line 126 at r1](https://reviewable.io/reviews/pmem/rpma/1120#-MdbhwKz4qVl4bC1Go9v:-MdbhwKz4qVl4bC1Go9w:b-b4fscp) ([raw file](https://github.com/pmem/rpma/blob/e586a885adb1d8511ff35664f731608c346e6833/CMakeLists.txt#L126)):*
> ```
> TEST_PYTHON_TOOLS
> ```

The default value of this variable should be set at the beginning

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1120)* status: 3 of 10 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[CMakeLists.txt, line 258 at r1](https://reviewable.io/reviews/pmem/rpma/1120#-MdbiYDECLC7VBIKq_2m:-MdbiYDECLC7VBIKq_2n:b-laikw0) ([raw file](https://github.com/pmem/rpma/blob/e586a885adb1d8511ff35664f731608c346e6833/CMakeLists.txt#L258)):*
> ```
> if(TEST_PYTHON_TOOLS)
> 	add_subdirectory(tools/perf)
> endif()
> ```

Why didn't you merge this `if` with the previous one?

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1120)* status: 5 of 10 files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by ldorau — COMMENTED** [review]
> Reviewed 4 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1120)* status: 9 of 10 files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1120)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by ldorau — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1120#-:-Mdp_GMgCaTL3_tKzRk6:b6e9vsk)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Comment by janekmi** [comment]
Requires some additional work. Closing for now.

**Pull request closed without merging**
