### PR TITLE
test: Upgrade Circle CI to Ubuntu 22.04

### PR DESCRIPTION
**Pull request by grom72**
---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1800)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1800)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1800#-N3ckiOe-Ecrbl3nZhns:-N3ckiOf5SuFUHlzsjN-:bpy34mu) (no related file):*
Examples are failing:
https://app.circleci.com/pipelines/github/pmem/rpma/1698/workflows/6218035c-2e39-4a34-b095-a93061d1312c/jobs/1711

___

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 2 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1800)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 3 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1800)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1800)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by osalyk — APPROVED** [review]
> Reviewed 2 of 2 files at r3, 2 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1800)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1800)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r3, 1 of 3 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1800)* status: all files reviewed, 9 unresolved discussions (waiting on @grom72)

___
*[`tests/drd.supp` line 246 at r7](https://reviewable.io/reviews/pmem/rpma/1800#-N3dWWr6EXPdaRXGGgUD:-N3dWWr6EXPdaRXGGgUE:bbh8hgm) ([raw file](https://github.com/pmem/rpma/blob/cea9247d1beba136e82c7df6965ef4408e97a3c1/tests/drd.supp#L246)):*
> ```
>    fun:rdma_destroy_id
>    fun:rpma_utils_get_ibv_context
>    fun:thread
> ```

I would remove this from all suppressions.



_Code quote:_
```
fun:thread
```
___
*[`tests/drd.supp` line 304 at r7](https://reviewable.io/reviews/pmem/rpma/1800#-N3dWk0hEz4DcMNqObYA:-N3dWk0hEz4DcMNqObYB:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/cea9247d1beba136e82c7df6965ef4408e97a3c1/tests/drd.supp#L304)):*
> ```
>    fun:rpma_conn_req_destroy
>    fun:rpma_conn_req_delete
>    fun:fini
> ```

.



_Code quote:_
```
fun:fini
```
___
*[`tests/drd.supp` line 326 at r7](https://reviewable.io/reviews/pmem/rpma/1800#-N3dWmWq02CRGrM-noNE:-N3dWmWq02CRGrM-noNF:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/cea9247d1beba136e82c7df6965ef4408e97a3c1/tests/drd.supp#L326)):*
> ```
>    fun:rdma_destroy_id
>    fun:rpma_ep_shutdown
>    fun:fini
> ```

.



_Code quote:_
```
fun:fini
```
___
*[`tests/helgrind.supp` line 226 at r7](https://reviewable.io/reviews/pmem/rpma/1800#-N3dWojr0s9Mn5vWrECI:-N3dWojr0s9Mn5vWrECJ:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/cea9247d1beba136e82c7df6965ef4408e97a3c1/tests/helgrind.supp#L226)):*
> ```
>    fun:rdma_create_id2.part.0
>    fun:rpma_utils_get_ibv_context
>    fun:thread
> ```

.



_Code quote:_
```
fun:thread
```
___
*[`tests/helgrind.supp` line 276 at r7](https://reviewable.io/reviews/pmem/rpma/1800#-N3dWt31-_OLBkDiRjzs:-N3dWt31-_OLBkDiRjzt:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/cea9247d1beba136e82c7df6965ef4408e97a3c1/tests/helgrind.supp#L276)):*
> ```
>    fun:rpma_conn_req_destroy
>    fun:rpma_conn_req_delete
>    fun:fini
> ```

.



_Code quote:_
```
fun:fini
```
___
*[`tests/helgrind.supp` line 281 at r7](https://reviewable.io/reviews/pmem/rpma/1800#-N3dWyN2AWOutWRAhBhw:-N3dWyN2AWOutWRAhBhx:b-f9xmvp) ([raw file](https://github.com/pmem/rpma/blob/cea9247d1beba136e82c7df6965ef4408e97a3c1/tests/helgrind.supp#L281)):*
> ```
> 
> {
>    rpma_ep_listen - Possible data race during write of size 8 at 0x4BA16E8 by thread #91
> ```

Redundant, remove it



_Code quote:_
```
at 0x4BA16E8 by thread #91
```
___
*[`tests/helgrind.supp` line 292 at r7](https://reviewable.io/reviews/pmem/rpma/1800#-N3dX3W-6hwcNPwrGVcN:-N3dX3W-6hwcNPwrGVcO:b-f9xmvp) ([raw file](https://github.com/pmem/rpma/blob/cea9247d1beba136e82c7df6965ef4408e97a3c1/tests/helgrind.supp#L292)):*
> ```
> 
> {
>    rpma_ep_listen - Possible data race during write of size 8 at 0x4BA1770 by thread #7
> ```

Redundant, remove it



_Code quote:_
```
at 0x4BA1770 by thread #7
```
___
*[`tests/memcheck-libibverbs.supp` line 62 at r7](https://reviewable.io/reviews/pmem/rpma/1800#-N3dXHrX2qYV0gYCoM68:-N3dXHrX2qYV0gYCoM69:bj9109p) ([raw file](https://github.com/pmem/rpma/blob/cea9247d1beba136e82c7df6965ef4408e97a3c1/tests/memcheck-libibverbs.supp#L62)):*
> ```
> 
> {
>    To be analised later
> ```

analyzed



_Code quote:_
```
analised
```
___
*[`tests/memcheck-libibverbs.supp` line 71 at r7](https://reviewable.io/reviews/pmem/rpma/1800#-N3dXygPCmynRXI1dCXl:-N3dXygQ63gGyC2pOn59:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/cea9247d1beba136e82c7df6965ef4408e97a3c1/tests/memcheck-libibverbs.supp#L71)):*
> ```
> 
> {
>    To be analised later
> ```

.



_Code quote:_
```
analised
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 4 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1800)* status: 3 of 5 files reviewed, 9 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

**Review by ldorau — APPROVED** [review]
> Reviewed 4 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1800)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1800#-:-N3d_VXj5469QKXr1vdc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1800)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 3 of 4 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1800#-:-N3dbcRN5bU3FEplq336:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1800)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
