### PR TITLE
tools: update BENCHMARKING.md and add simple example of figure

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1484)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1484)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/BENCHMARKING.md, line 60 at r1](https://reviewable.io/reviews/pmem/rpma/1484#-Mt8JlTH0c1fGJa3nOOP:-Mt8JlTIAv9tqFlvu5nP:bgllwdi) ([raw file](https://github.com/pmem/rpma/blob/6b601a8c413dcf3db556b2f51c7d429563ef6c1d/tools/perf/BENCHMARKING.md#L60)):*
> ```Markdown
> ```
> 
> *Note*: All of the scripts presented in the following sections must be run on the client side.
> ```

RPMA initiator



_Code quote:_
```Markdown
client
```
___
*[tools/perf/BENCHMARKING.md, line 79 at r1](https://reviewable.io/reviews/pmem/rpma/1484#-Mt8JBHg41AsSSpvrtDz:-Mt8JBHh8k_BChcp5q81:b-rri1u1) ([raw file](https://github.com/pmem/rpma/blob/6b601a8c413dcf3db556b2f51c7d429563ef6c1d/tools/perf/BENCHMARKING.md#L79)):*
> ```Markdown
> ```
> 
> If you want to continue an interrupted benchmark or if you want to run more benchmarks for different configuration parameters, you can change them in the 'results/bench.json' file and run:
> ```

interrupted benchmarking process



_Code quote:_
```Markdown
interrupted benchmark
```
___
*[tools/perf/BENCHMARKING.md, line 84 at r1](https://reviewable.io/reviews/pmem/rpma/1484#-Mt8JMZg1Sz1CxRUTmXv:-Mt8JMZg1Sz1CxRUTmXw:b-bcyxg1) ([raw file](https://github.com/pmem/rpma/blob/6b601a8c413dcf3db556b2f51c7d429563ef6c1d/tools/perf/BENCHMARKING.md#L84)):*
> ```Markdown
> $ ./report_bench.py continue --bench results/bench.json
> ```
> ```

It will be user friendly to provide a hint on how to run benchmarks on the ICX platform.
Pointing the DIRECT_WRITE_TO_PMEM item in CONFIG.json file
___
*[tools/perf/BENCHMARKING.md, line 137 at r1](https://reviewable.io/reviews/pmem/rpma/1484#-Mt8Hw1n4lCKwOijA_W1:-Mt8Hw1n4lCKwOijA_W2:b-drslsb) ([raw file](https://github.com/pmem/rpma/blob/35169adce66368d36f2bf694b8cbaf0c4e842b56/tools/perf/BENCHMARKING.md#L137)):*
> ```Markdown
> ```sh
> $ ./report_figures.py compare --benches results_1/bench.json results_2/bench.json
> --names results_1 results_2 --result_dir compare
> ```

Can we have here an example result?
It can be based on described later example_read.json
It is not clear what --names means



_Code quote:_
```Markdown
Comparing
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1484)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/BENCHMARKING.md, line 60 at r1](https://reviewable.io/reviews/pmem/rpma/1484#-Mt8JlTH0c1fGJa3nOOP:-Mt8PL6iE_VIaJbkN1VU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6b601a8c413dcf3db556b2f51c7d429563ef6c1d/tools/perf/BENCHMARKING.md#L60)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

RPMA initiator
</blockquote></details>

Done.
___
*[tools/perf/BENCHMARKING.md, line 137 at r1](https://reviewable.io/reviews/pmem/rpma/1484#-Mt8Hw1n4lCKwOijA_W1:-Mt8Pl-Z-mRKJXgwbGWB:br8dh2q) ([raw file](https://github.com/pmem/rpma/blob/35169adce66368d36f2bf694b8cbaf0c4e842b56/tools/perf/BENCHMARKING.md#L137)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Can we have here an example result?
It can be based on described later example_read.json
It is not clear what --names means
</blockquote></details>

What "an example result?" do you want here? A result is a directory with files ....

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1484)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[tools/perf/BENCHMARKING.md, line 84 at r1](https://reviewable.io/reviews/pmem/rpma/1484#-Mt8JMZg1Sz1CxRUTmXv:-Mt8TBdNAnQM7p-kU1nN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6b601a8c413dcf3db556b2f51c7d429563ef6c1d/tools/perf/BENCHMARKING.md#L84)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

It will be user friendly to provide a hint on how to run benchmarks on the ICX platform.
Pointing the DIRECT_WRITE_TO_PMEM item in CONFIG.json file

</blockquote></details>

Done.

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1484)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[tools/perf/BENCHMARKING.md, line 137 at r1](https://reviewable.io/reviews/pmem/rpma/1484#-Mt8Hw1n4lCKwOijA_W1:-Mt96MYU8LtD4K_uHkjG:b2aynx7) ([raw file](https://github.com/pmem/rpma/blob/35169adce66368d36f2bf694b8cbaf0c4e842b56/tools/perf/BENCHMARKING.md#L137)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

What "an example result?" do you want here? A result is a directory with files ....
</blockquote></details>

if we limit to 1 series comparison then it will give 1 picture.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1484)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/perf/BENCHMARKING.md, line 137 at r1](https://reviewable.io/reviews/pmem/rpma/1484#-Mt8Hw1n4lCKwOijA_W1:-Mt9tdTW7j9h-f65vtd3:b-2eddvc) ([raw file](https://github.com/pmem/rpma/blob/35169adce66368d36f2bf694b8cbaf0c4e842b56/tools/perf/BENCHMARKING.md#L137)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

if we limit to 1 series comparison then it will give 1 picture.
</blockquote></details>

1) So can it be any one picture? 
2) Do you want me to commit this picture to the repo?

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1484)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/BENCHMARKING.md, line 137 at r1](https://reviewable.io/reviews/pmem/rpma/1484#-Mt8Hw1n4lCKwOijA_W1:-MtA1YN2AtWq593xHYMN:bcaqvzd) ([raw file](https://github.com/pmem/rpma/blob/35169adce66368d36f2bf694b8cbaf0c4e842b56/tools/perf/BENCHMARKING.md#L137)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

1) So can it be any one picture? 
2) Do you want me to commit this picture to the repo?

</blockquote></details>

Let's forget about a picture, but focus on the ```--name``` option which is unclear when reading the whole command.
Can we replace ``--name``` with ```--prefix``` to inform the user that values will be added at the beginning of series names?

**Review by osalyk — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1484)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1484#-MtCAWcI6tQdWHomvf-7:-MtCAWcJBmpooZb6NYFg:b-8cioiv) (no related file):*
Please rebase.

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1484)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1484#-MtCAWcI6tQdWHomvf-7:-MtCCWIf22ogzu9Ltf3w:b-896fix) (no related file):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Please rebase.
</blockquote></details>

Done.

---
___
*[tools/perf/BENCHMARKING.md, line 137 at r1](https://reviewable.io/reviews/pmem/rpma/1484#-Mt8Hw1n4lCKwOijA_W1:-MtCD2Xv5yltNdnGCxtM:b-gqf9ad) ([raw file](https://github.com/pmem/rpma/blob/35169adce66368d36f2bf694b8cbaf0c4e842b56/tools/perf/BENCHMARKING.md#L137)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Let's forget about a picture, but focus on the ```--name``` option which is unclear when reading the whole command.
Can we replace ``--name``` with ```--prefix``` to inform the user that values will be added at the beginning of series names?
</blockquote></details>

We can change, but in a separate PR. The meaning of this option should be described in the help (`./report_figures.py compare -h
`), not here.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1484)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[tools/perf/BENCHMARKING.md, line 137 at r1](https://reviewable.io/reviews/pmem/rpma/1484#-Mt8Hw1n4lCKwOijA_W1:-MtCFYDa-XHwS1kF8_uY:b-8jonwd) ([raw file](https://github.com/pmem/rpma/blob/35169adce66368d36f2bf694b8cbaf0c4e842b56/tools/perf/BENCHMARKING.md#L137)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

We can change, but in a separate PR. The meaning of this option should be described in the help (`./report_figures.py compare -h
`), not here.
</blockquote></details>

See: https://github.com/pmem/rpma/pull/1487

**Review by osalyk — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1484)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1484)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/BENCHMARKING.md, line 137 at r1](https://reviewable.io/reviews/pmem/rpma/1484#-Mt8Hw1n4lCKwOijA_W1:-MtCG2Dd0iV6Sg8DrOeA:buhg3i5) ([raw file](https://github.com/pmem/rpma/blob/35169adce66368d36f2bf694b8cbaf0c4e842b56/tools/perf/BENCHMARKING.md#L137)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

See: https://github.com/pmem/rpma/pull/1487
</blockquote></details>

Perhaps, it will be good to show here the output of ```./report_figures.py compare -h```.
I like this: https://community.mellanox.com/s/article/ib-read-bw
___
*[tools/perf/BENCHMARKING.md, line 151 at r4](https://reviewable.io/reviews/pmem/rpma/1484#-MtCGbHE1snlNtgYnArv:-MtCGbHE1snlNtgYnArw:b-neiyo1) ([raw file](https://github.com/pmem/rpma/blob/64b9f8eb1a44587571d92841a193fe3ce9558c9d/tools/perf/BENCHMARKING.md#L151)):*
> ```Markdown
> 
> Instead of running a comprehensive set of workloads you can run a simple subset of them.
> In order to do so you have to modify and simplify the existing [figures](./figures/).
> ```

modify



_Code quote:_
```Markdown
modify and simplify
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1484)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72 and @osalyk)

___
*[tools/perf/BENCHMARKING.md, line 137 at r1](https://reviewable.io/reviews/pmem/rpma/1484#-Mt8Hw1n4lCKwOijA_W1:-MtCI9cq5Riew9sYRrrM:b-wlyhww) ([raw file](https://github.com/pmem/rpma/blob/35169adce66368d36f2bf694b8cbaf0c4e842b56/tools/perf/BENCHMARKING.md#L137)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Perhaps, it will be good to show here the output of ```./report_figures.py compare -h```.
I like this: https://community.mellanox.com/s/article/ib-read-bw

</blockquote></details>

To be honest I do not think so - it is not a manual of `./report_figures.py`
___
*[tools/perf/BENCHMARKING.md, line 151 at r4](https://reviewable.io/reviews/pmem/rpma/1484#-MtCGbHE1snlNtgYnArv:-MtCId__Ak4bUq-4wEip:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/64b9f8eb1a44587571d92841a193fe3ce9558c9d/tools/perf/BENCHMARKING.md#L151)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

modify
</blockquote></details>

Done.



_Code quote:_
```Markdown
modify and simplify 
```

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1484)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @grom72, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1484#-MtCHkRDAG7Tr6aMKjuj:-MtCHkRDAG7Tr6aMKjuk:b-8ot5pw) (no related file):*
There are at least two missing items:
- introduction of initiator and target node
- ssh setup (user must execute ssh manually from initiator to target at least once before starting benchmarking process)

---
___
*[tools/perf/BENCHMARKING.md, line 17 at r4](https://reviewable.io/reviews/pmem/rpma/1484#-MtCHEQc60d7KkA0k7Rj:-MtCHEQc60d7KkA0k7Rk:bxtub52) ([raw file](https://github.com/pmem/rpma/blob/64b9f8eb1a44587571d92841a193fe3ce9558c9d/tools/perf/BENCHMARKING.md#L17)):*
> ```Markdown
>  - fio >= 3.27
>  - numactl
>  - sshpass
> ```

Is it needed?



_Code quote:_
```Markdown
sshpass
```
___
*[tools/perf/BENCHMARKING.md, line 18 at r4](https://reviewable.io/reviews/pmem/rpma/1484#-MtCHMrxDXVobZUwAtS4:-MtCHMrxDXVobZUwAtS5:b-u7q6hi) ([raw file](https://github.com/pmem/rpma/blob/64b9f8eb1a44587571d92841a193fe3ce9558c9d/tools/perf/BENCHMARKING.md#L18)):*
> ```Markdown
>  - numactl
>  - sshpass
>  - pciutils (for ddio.sh which may be invoked from `rpma_fio_bench.sh`)
> ```

add information that required only for the CascadeLake platform



_Code quote:_
```Markdown
for ddio.sh which may be invoked from `rpma_fio_bench.sh`
```
___
*[tools/perf/BENCHMARKING.md, line 23 at r4](https://reviewable.io/reviews/pmem/rpma/1484#-MtCHajy0jHIRVeuRtPL:-MtCHajzCnK0PFNvcBsB:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/64b9f8eb1a44587571d92841a193fe3ce9558c9d/tools/perf/BENCHMARKING.md#L23)):*
> ```Markdown
> 
> ```sh
> $ sudo yum install python3 python3-pip numactl sshpass
> ```

.



_Code quote:_
```Markdown
sshpass
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1484)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1484)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

**Review by haichangsi — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1484#-:-MtCWNoJE00fjnnGiZXp:bdycpsm)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1484)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1484#-MtCHkRDAG7Tr6aMKjuj:-MtCZ62L7iCPBXl0uoBM:b-2bb11o) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

There are at least two missing items:
- introduction of initiator and target node
- ssh setup (user must execute ssh manually from initiator to target at least once before starting benchmarking process)
</blockquote></details>

To be done later?

---
___
*[tools/perf/BENCHMARKING.md, line 17 at r4](https://reviewable.io/reviews/pmem/rpma/1484#-MtCHEQc60d7KkA0k7Rj:-MtCVd627Myg-ZJZO2tw:ba3dfob) ([raw file](https://github.com/pmem/rpma/blob/64b9f8eb1a44587571d92841a193fe3ce9558c9d/tools/perf/BENCHMARKING.md#L17)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Is it needed?
</blockquote></details>

Removed
___
*[tools/perf/BENCHMARKING.md, line 18 at r4](https://reviewable.io/reviews/pmem/rpma/1484#-MtCHMrxDXVobZUwAtS4:-MtCWhczCBCHgG2KKzKz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/64b9f8eb1a44587571d92841a193fe3ce9558c9d/tools/perf/BENCHMARKING.md#L18)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

add information that required only for the CascadeLake platform
</blockquote></details>

Done.
___
*[tools/perf/BENCHMARKING.md, line 23 at r4](https://reviewable.io/reviews/pmem/rpma/1484#-MtCHajy0jHIRVeuRtPL:-MtCVuFrC6ezk3fRTBw0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/64b9f8eb1a44587571d92841a193fe3ce9558c9d/tools/perf/BENCHMARKING.md#L23)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1484)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1484#-MtCHkRDAG7Tr6aMKjuj:-MtCZOFW1ozQxPy9A3sv:biz9ll5) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

To be done later?
</blockquote></details>

Yes #1489    

---

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1484#-:-MtC_G7DD_QsF7-ZSW-7:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1484)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/BENCHMARKING.md, line 12 at r6](https://reviewable.io/reviews/pmem/rpma/1484#-MtCapEyEN7OG4qObxYC:-MtCapEz7MbWK_3xpyeU:bxtub52) ([raw file](https://github.com/pmem/rpma/blob/6a495e8f083637ac0606294d5ab488272ba688ea/tools/perf/BENCHMARKING.md#L12)):*
> ```Markdown
>  - python3
>  - python3-pip
>  - pandas
> ```

Is it needed?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1484)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/BENCHMARKING.md, line 12 at r6](https://reviewable.io/reviews/pmem/rpma/1484#-MtCapEyEN7OG4qObxYC:-MtCbnTI9KKeLcYPZI_C:b-55gkp7) ([raw file](https://github.com/pmem/rpma/blob/6a495e8f083637ac0606294d5ab488272ba688ea/tools/perf/BENCHMARKING.md#L12)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Is it needed?
</blockquote></details>

Right, removed



_Code quote:_
```Markdown
pandas
```

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1484#-:-MtCevaQCagJnlYqF6fz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
