### PR TITLE
examples: update 10-send-with-imm's README.md

### PR DESCRIPTION
**Pull request by yangx-jy**
Signed-off-by: Xiao Yang <yangx.jy@cn.fujitsu.com>

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/918)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/918#-:-MUwJw0D0CrI362Ruycz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/918)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[examples/10-send-with-imm/README.md, line 11 at r1](https://reviewable.io/reviews/pmem/rpma/918#-MUxCcIh4FjkRQr6GMlo:-MUxCcIh4FjkRQr6GMlp:bnb49ii) ([raw file](https://github.com/pmem/rpma/blob/230faf99ad4834f1972a81d284c1880a3f5d144f/examples/10-send-with-imm/README.md#L11)):*
> ```
> if word
> ```

`if the 'word'`

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/918)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/918#-:-MUxWCLF4m_O1g-cM2J_:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Pull request merged**
