### PR TITLE
tools: create log file name based on oneseries[tool]

### PR DESCRIPTION
**Pull request by grom72**
Later __set_log_file_names can be moved to superclass

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1439)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1439)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1439)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1439#-:-MrNCaRc8g8Zw4dLPYHt:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 93 at r2](https://reviewable.io/reviews/pmem/rpma/1439#-MrN9jJx1qP4QBQMho3P:-MrNDLut8LMLNutGjKVb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/93c66b23b6423933574695b1f35af80dec2fb90a/tools/perf/lib/benchmark/runner/fio.py#L93)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Move it before `self.__tool_mode`, please
</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 63 at r2](https://reviewable.io/reviews/pmem/rpma/1439#-MrN9ywuEfsELDpWv1S1:-MrNDZNCBWeHqnIONvei:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/93c66b23b6423933574695b1f35af80dec2fb90a/tools/perf/lib/benchmark/runner/ib_read.py#L63)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Move it before `self.__mode`, please
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1439#-:-MrNEw5i6QH-REZF_rQL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1439#-:-MrNUCqN7J4GAbS4Xw4Q:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1439)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
