### PR TITLE
doc: add Optimizing Memory Performance

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/800)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
:lgtm: 

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/800#-:-MSR8Bf2-yAAMOTsuNIK:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
Preview: https://ldorau.github.io/rpma/documentation/basic-reqs-optimizing-memory-performance.html

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/800#-:-MST2BHq3XOCdrJJktYT:b-81hcmq)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/800)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/800#-MSWD8kR2eGdHAG9MaPC:-MSWD8kR2eGdHAG9MaPD:b-er6i3x) (no related file):*
I'm not sure if we should use the "Persistent Memory Development Kit" header.  Perhaps instead we should refer to Remote Persistent Memory Access.

---
___
*[documentation/basic-reqs-optimizing-memory-performance.md, line 7 at r1](https://reviewable.io/reviews/pmem/rpma/800#-MSWCtQ3-4pF7uS76nRv:-MSWCtQ3-4pF7uS76nRw:b-5v91db) ([raw file](https://github.com/pmem/rpma/blob/6219657cf100a5ad58bc99277c1c9ce5050cf9e6/documentation/basic-reqs-optimizing-memory-performance.md#L7)):*
> ```
> Optimizing Memory Performance 
> ```
```Optimizing Memory Performance for Remote Memory Access```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/800)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/800#-MSWD8kR2eGdHAG9MaPC:-MSWR4-RASrk-39dS0Tn:b5v0a6) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I'm not sure if we should use the "Persistent Memory Development Kit" header.  Perhaps instead we should refer to Remote Persistent Memory Access.
</blockquote></details>

See https://pmem.io/rpma/ - all of our GH pages use PMDK layout. Changing this is not a part of this PR.

---
___
*[documentation/basic-reqs-optimizing-memory-performance.md, line 7 at r1](https://reviewable.io/reviews/pmem/rpma/800#-MSWCtQ3-4pF7uS76nRv:-MSWSo7ADZGsPFKYegY3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/6219657cf100a5ad58bc99277c1c9ce5050cf9e6/documentation/basic-reqs-optimizing-memory-performance.md#L7)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Optimizing Memory Performance 
> ```
```Optimizing Memory Performance for Remote Memory Access```


</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/800)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/800)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/800)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[documentation/basic-reqs-optimizing-memory-performance.md, line 5 at r3](https://reviewable.io/reviews/pmem/rpma/800#-MSWllJ44QfObMKFEv7t:-MSWllJ44QfObMKFEv7u:b-rt3zz0) ([raw file](https://github.com/pmem/rpma/blob/b4ab9db2fda0e66a51560b5d56b5af9ebe2429b7/documentation/basic-reqs-optimizing-memory-performance.md#L5)):*
> ```Markdown
> layout: pmdk
> ---
> ```

Do we need this one empty line?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/800)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[documentation/basic-reqs-optimizing-memory-performance.md, line 5 at r3](https://reviewable.io/reviews/pmem/rpma/800#-MSWllJ44QfObMKFEv7t:-MSWmu6Y9j3pYrWyZYYM:b-277w67) ([raw file](https://github.com/pmem/rpma/blob/b4ab9db2fda0e66a51560b5d56b5af9ebe2429b7/documentation/basic-reqs-optimizing-memory-performance.md#L5)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Do we need this one empty line?
</blockquote></details>

It is not necessary, but it looks better - more clear and more readable - for me like that.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/800)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[documentation/basic-reqs-optimizing-memory-performance.md, line 8 at r3](https://reviewable.io/reviews/pmem/rpma/800#-MSWrmUBA2CXL9HnIMg6:-MSWrmUC0xY_M8DzKtSH:bl1hmzt) ([raw file](https://github.com/pmem/rpma/blob/b4ab9db2fda0e66a51560b5d56b5af9ebe2429b7/documentation/basic-reqs-optimizing-memory-performance.md#L8)):*
> ```
> for Remote Memory Access
> ```
no longer needed if we have an additional header above

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/800)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[documentation/basic-reqs-optimizing-memory-performance.md, line 8 at r3](https://reviewable.io/reviews/pmem/rpma/800#-MSWrmUBA2CXL9HnIMg6:-MSWsRosClDdU1l1qJCp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b4ab9db2fda0e66a51560b5d56b5af9ebe2429b7/documentation/basic-reqs-optimizing-memory-performance.md#L8)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> for Remote Memory Access
> ```
no longer needed if we have an additional header above
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/800#-:-MSWxRIw1wCQwEquJSp8:bnfp4nl)* status: 1 of 2 files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/800)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/800)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/800#-MSbZLwR6rKsqlPprAR1:-MSbZLwR6rKsqlPprAR2:b-l8fpgf) (no related file):*
Do we have any references for all of these?

---
___
*[documentation/basic-reqs-optimizing-memory-performance.md, line 19 at r4](https://reviewable.io/reviews/pmem/rpma/800#-MSbZ0gQESStmz1Zj4VL:-MSbZ0gQESStmz1Zj4VM:b-drtqxk) ([raw file](https://github.com/pmem/rpma/blob/82e5695f9455969a33ae0579f07bc3bab4724ada/documentation/basic-reqs-optimizing-memory-performance.md#L19)):*
> ```Markdown
> 3) Use a "balanced" platform configuration:
>    - all available memory channels populated equally
>    - identical DIMMs in all locations (size/speed/rank)
> ```

Duplicate.
___
*[documentation/basic-reqs-optimizing-memory-performance.md, line 21 at r4](https://reviewable.io/reviews/pmem/rpma/800#-MSbZ6ZG0IrSIHqVzpLd:-MSbZ6ZG0IrSIHqVzpLe:b-jfvfjo) ([raw file](https://github.com/pmem/rpma/blob/82e5695f9455969a33ae0579f07bc3bab4724ada/documentation/basic-reqs-optimizing-memory-performance.md#L21)):*
> ```Markdown
>    - identical DIMMs in all locations (size/speed/rank)
> 
> 4) Use a "near-balanced" platform configuration:
> ```

This list seems presenting a few possible alternatives but it is not stated explicitly.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/800)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/800#-MSbZLwR6rKsqlPprAR1:-MSbx5kg85XLVPOGlD2o:b25kse1) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Do we have any references for all of these?
</blockquote></details>

Unfortunately no :-(

---
___
*[documentation/basic-reqs-optimizing-memory-performance.md, line 19 at r4](https://reviewable.io/reviews/pmem/rpma/800#-MSbZ0gQESStmz1Zj4VL:-MSby_Hw4YGLqe7DxWFU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/82e5695f9455969a33ae0579f07bc3bab4724ada/documentation/basic-reqs-optimizing-memory-performance.md#L19)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Duplicate.
</blockquote></details>

Done.
___
*[documentation/basic-reqs-optimizing-memory-performance.md, line 21 at r4](https://reviewable.io/reviews/pmem/rpma/800#-MSbZ6ZG0IrSIHqVzpLd:-MSby_pR2ZTbZCxgL_pi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/82e5695f9455969a33ae0579f07bc3bab4724ada/documentation/basic-reqs-optimizing-memory-performance.md#L21)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This list seems presenting a few possible alternatives but it is not stated explicitly.
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/800)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[documentation/basic-reqs-optimizing-memory-performance.md, line 19 at r4](https://reviewable.io/reviews/pmem/rpma/800#-MSbZ0gQESStmz1Zj4VL:-MSc17d700Mc30mnhMfM:bl2wqht) ([raw file](https://github.com/pmem/rpma/blob/82e5695f9455969a33ae0579f07bc3bab4724ada/documentation/basic-reqs-optimizing-memory-performance.md#L19)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

```
1) Use identical DIMM types throughout the platform:
  - same size, speed and number of ranks
```

and

```
- identical DIMMs in all locations (size/speed/rank)
```

**Review by janekmi — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/800)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/800)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/800#-MScCsqT3dpZZ_p_8Eru:-MScDMcm3tTptOPMxc9c:bowo3b3) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Thinking out loud: wouldn't be easier to just recommend to do it **right** according to this manual and make this whole document a paragraph in the #824.
</blockquote></details>

Yes, I agree

---

**Comment by ldorau** [comment]
Moved to https://github.com/pmem/rpma/pull/824

**Pull request closed without merging**
