### PR TITLE
test: extract common code for MT tests

### PR DESCRIPTION
**Pull request by ldorau**
Extract common connection code from `rpma_conn_get_private_data.c` for a future use.

This patch only refactors the code and does not make any functional modifications.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1635)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1635)* status: 1 of 5 files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1635#-MzUaYTpBj7yRh28yRUf:-MzUehHa3q-MnYEsEnP5:b-fznogt) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

shall we use the ``mtt_`` prefix for common multithreaded tests functions?
</blockquote></details>

Good idea, done.

---

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1635)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tests/multithreaded/common/connect.h, line 5 at r2](https://reviewable.io/reviews/pmem/rpma/1635#-MzUmyAo1Q7S8IHusX90:-MzUmyAp7B2jFNlfU-4Q:bhnucy) ([raw file](https://github.com/pmem/rpma/blob/ae4beb6fef56fb51146f5465cc891adfdf307ab1/tests/multithreaded/common/connect.h#L5)):*
> ```objc
> 
> /*
>  * connect.h -- header for common connection code of multithreaded tests
> ```

``mtt_connect.h``?



_Code quote:_
```objc
connect.h
```
___
*[tests/multithreaded/common/connect.h, line 7 at r2](https://reviewable.io/reviews/pmem/rpma/1635#-MzUmkDP9gjZFUre19Lg:-MzUmkDP9gjZFUre19Lh:bz8pa5l) ([raw file](https://github.com/pmem/rpma/blob/ae4beb6fef56fb51146f5465cc891adfdf307ab1/tests/multithreaded/common/connect.h#L7)):*
> ```objc
>  * connect.h -- header for common connection code of multithreaded tests
>  */
> ```

```
#ifndef MTT_CONNECT_H
#define MTT_CONNECT_H
....
#endif
```
___
*[tests/multithreaded/common/connect.c, line 10 at r2](https://reviewable.io/reviews/pmem/rpma/1635#-MzUnJ4JEdy4qtG6eWSa:-MzUnJ4JEdy4qtG6eWSb:blnlkxv) ([raw file](https://github.com/pmem/rpma/blob/ae4beb6fef56fb51146f5465cc891adfdf307ab1/tests/multithreaded/common/connect.c#L10)):*
> ```C
> #include <stdlib.h>
> #include <librpma.h>
> ```

``#include "mtt_connect.h"``?
___
*[tests/multithreaded/common/connect.c, line 11 at r2](https://reviewable.io/reviews/pmem/rpma/1635#-MzUn7795-p14iIxQkwd:-MzUn7795-p14iIxQkwe:b-s3j209) ([raw file](https://github.com/pmem/rpma/blob/ae4beb6fef56fb51146f5465cc891adfdf307ab1/tests/multithreaded/common/connect.c#L11)):*
> ```C
> #include <librpma.h>
> 
> #include "mtt.h"
> ```

``mtt_connect.c``?



_Code quote:_
```C
connect.c
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1635)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1635)* status: 0 of 5 files reviewed, 5 unresolved discussions (waiting on @grom72)

___
*[tests/multithreaded/common/connect.h, line 5 at r2](https://reviewable.io/reviews/pmem/rpma/1635#-MzUmyAo1Q7S8IHusX90:-MzUsvEI7aVx1-rj6QR4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ae4beb6fef56fb51146f5465cc891adfdf307ab1/tests/multithreaded/common/connect.h#L5)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

``mtt_connect.h``?
</blockquote></details>

Done.
___
*[tests/multithreaded/common/connect.h, line 7 at r2](https://reviewable.io/reviews/pmem/rpma/1635#-MzUmkDP9gjZFUre19Lg:-MzUswJcEQCFqo8HnD7Z:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ae4beb6fef56fb51146f5465cc891adfdf307ab1/tests/multithreaded/common/connect.h#L7)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```
#ifndef MTT_CONNECT_H
#define MTT_CONNECT_H
....
#endif
```
</blockquote></details>

Done.
___
*[tests/multithreaded/common/connect.c, line 10 at r2](https://reviewable.io/reviews/pmem/rpma/1635#-MzUnJ4JEdy4qtG6eWSa:-MzUt0dB33YkLxbTlboH:byve3ty) ([raw file](https://github.com/pmem/rpma/blob/ae4beb6fef56fb51146f5465cc891adfdf307ab1/tests/multithreaded/common/connect.c#L10)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

``#include "mtt_connect.h"``?
</blockquote></details>

It is not needed.
___
*[tests/multithreaded/common/connect.c, line 11 at r2](https://reviewable.io/reviews/pmem/rpma/1635#-MzUn7795-p14iIxQkwd:-MzUt-iv1BzqT-UJySrX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ae4beb6fef56fb51146f5465cc891adfdf307ab1/tests/multithreaded/common/connect.c#L11)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

``mtt_connect.c``?
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1635)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1635)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1635)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1635#-:-MzZCzcxExPvwm7H14Uy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by haichangsi — COMMENTED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1635#-:-MzZazBuDPeNTQVXDV66:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
