### PR TITLE
common: only process valid wc attributes when wc.status is not IBV_WC_SUCCESS

### PR DESCRIPTION
**Pull request by yangx-jy**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1170)

### CODE REVIEW

**Review by ldorau — APPROVED** [review]
> Reviewed 3 of 3 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1170)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1170#-:-Mfgm2AY9mIcJoNG-KEE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by ldorau — APPROVED** [review]
> Reviewed 11 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1170)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1170)* status: all files reviewed, 5 unresolved discussions (waiting on @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1170#-MgerO1tCaXbts8mqPz5:-MgerO1uAhNWodZlVPRU:b-25g25e) (no related file):*
I think we should also add a note to the documentation e.g.

```
RETURN VALUE
The rpma_conn_completion_get() function returns 0 on success or a negative error code on failure. On success, it writes the first available completion to *cmpl*. If *op_status* of the written *cmpl* will not be equal to **IBV_WC_SUCCESS** then only *op_context* of the returned *cmpl* is valid.
```

---
___
*[src/cq.c, line 125 at r3](https://reviewable.io/reviews/pmem/rpma/1170#-MgfBbLcE_P-mysn2ryN:-MgfBbLcE_P-mysn2ryO:b-ov3mhu) ([raw file](https://github.com/pmem/rpma/blob/1fed6b28616b393ad1d1c83923b76eaa11afe74a/src/cq.c#L125)):*
> ```C
> 	cmpl->op_status = wc.status;
> 
> 	if (unlikely(cmpl->op_status != IBV_WC_SUCCESS)) {
> ```

/* When wc.status != IBV_WC_SUCCESS only the following attributes are valid: wr_id, status, qp_num, and vendor_err. */
___
*[tests/unit/cq/cq-get_completion.c, line 101 at r3](https://reviewable.io/reviews/pmem/rpma/1170#-Mgf85tx26dufJoeFNoW:-Mgf85tx26dufJoeFNoX:blz3scd) ([raw file](https://github.com/pmem/rpma/blob/1fed6b28616b393ad1d1c83923b76eaa11afe74a/tests/unit/cq/cq-get_completion.c#L101)):*
> ```C
> /*
>  * get_completion__poll_cq_wc_status_error - ibv_poll_cq() returns
>  * wrong wc.status (wc.status != IBV_WC_SUCCESS)
> ```

I would call it `an error wc.status`.
___
*[tests/unit/cq/cq-get_completion.c, line 105 at r3](https://reviewable.io/reviews/pmem/rpma/1170#-Mgf8nL_3cHl9G8ZR-Mf:-Mgf8nL_3cHl9G8ZR-Mg:b-il3a9s) ([raw file](https://github.com/pmem/rpma/blob/1fed6b28616b393ad1d1c83923b76eaa11afe74a/tests/unit/cq/cq-get_completion.c#L105)):*
> ```C
> static void
> get_completion__poll_cq_wc_status_error(void **cq_ptr)
> {
> ```

```c
assert_int_not_equal(MOCK_WC_STATUS_ERROR, IBV_WC_SUCCESS);
```

Just in case. ;-)
___
*[tests/unit/cq/cq-get_completion.c, line 123 at r3](https://reviewable.io/reviews/pmem/rpma/1170#-MgfACeaEqo7M715oyQ2:-MgfACeaEqo7M715oyQ3:b-xqdwvy) ([raw file](https://github.com/pmem/rpma/blob/1fed6b28616b393ad1d1c83923b76eaa11afe74a/tests/unit/cq/cq-get_completion.c#L123)):*
> ```C
> 	assert_int_equal(ret, 0);
> 	assert_int_equal(cmpl.op_context, MOCK_OP_CONTEXT);
> 	assert_int_equal(cmpl.op_status, MOCK_WC_STATUS_ERROR);
> ```

I think we should also verify that other fields are not modified just in case somebody won't understand your change in the future and decide he needs other fields. xD

```c
struct rpma_completion cmpl_pattern;
memset(&cmpl_pattern, 0xba, sizeof(struct rpma_completion));

/* ... */
struct rpma_completion cmpl = cmpl_pattern;

/* ... */
assert_int_equal(cmpl.op, cmpl_pattern.op);
/* and the rest of the fields which should not be touched at all */
```

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 11 of 11 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1170)* status: all files reviewed, 11 unresolved discussions (waiting on @yangx-jy)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1170#-MgfFPAT9zy6B2HGfjAF:-MgfFPAT9zy6B2HGfjAG:bnsr8nf) (no related file):*
Missing error handling fixes:
- https://github.com/pmem/rpma/blob/master/examples/09-flush-to-persistent-GPSPM/server.c#L236

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1170#-MgfG1YfEk3G0BnL5--U:-MgfG1YfEk3G0BnL5--V:ble2w3y) (no related file):*
Missing error messages when `op_status != IBV_WC_STATUS`:
- https://github.com/pmem/rpma/blob/master/examples/05-flush-to-persistent/client.c#L262
- https://github.com/pmem/rpma/blob/master/examples/08-messages-ping-pong/client.c#L132
- https://github.com/pmem/rpma/blob/master/examples/09-flush-to-persistent-GPSPM/client.c#L265
- https://github.com/pmem/rpma/blob/master/examples/09-flush-to-persistent-GPSPM/server.c#L283

I know it is not what you meant but you have started yourself by incorporating the fix to error messages. xD

---
___
*[examples/02-read-to-volatile/client.c, line 137 at r3](https://reviewable.io/reviews/pmem/rpma/1170#-MgfCJGJ8RV-VOuoyanf:-MgfCJGJ8RV-VOuoyang:b-dtoxhd) ([raw file](https://github.com/pmem/rpma/blob/1fed6b28616b393ad1d1c83923b76eaa11afe74a/examples/02-read-to-volatile/client.c#L137)):*
> ```C
> 	if (cmpl.op_status != IBV_WC_SUCCESS) {
> 		ret = -1;
> 		(void) fprintf(stderr, "rpma_read failed: %s\n",
> ```

rpma_read()
___
*[examples/03-read-to-persistent/server.c, line 186 at r3](https://reviewable.io/reviews/pmem/rpma/1170#-MgfCYIU5C-QOSwQ9-v9:-MgfCYIU5C-QOSwQ9-vA:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/1fed6b28616b393ad1d1c83923b76eaa11afe74a/examples/03-read-to-persistent/server.c#L186)):*
> ```C
> 	if (cmpl.op_status != IBV_WC_SUCCESS) {
> 		ret = -1;
> 		(void) fprintf(stderr, "rpma_read failed: %s\n",
> ```

.
___
*[examples/04-write-to-persistent/client.c, line 250 at r3](https://reviewable.io/reviews/pmem/rpma/1170#-MgfCqfPBrAH1lgS8bgH:-MgfCqfPBrAH1lgS8bgI:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/1fed6b28616b393ad1d1c83923b76eaa11afe74a/examples/04-write-to-persistent/client.c#L250)):*
> ```C
> 	if (cmpl.op_status != IBV_WC_SUCCESS) {
> 		ret = -1;
> 		(void) fprintf(stderr, "rpma_read failed: %s\n",
> ```

.
___
*[examples/06-multiple-connections/server.c, line 237 at r3](https://reviewable.io/reviews/pmem/rpma/1170#-MgfDPcODLcfX4jbibHG:-MgfDPcODLcfX4jbibHH:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/1fed6b28616b393ad1d1c83923b76eaa11afe74a/examples/06-multiple-connections/server.c#L237)):*
> ```C
> 	if (cmpl.op_status != IBV_WC_SUCCESS) {
> 		(void) fprintf(stderr,
> 				"[%d] rpma_read failed: %s\n",
> ```

.

**Review by yangx-jy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1170)* status: 1 of 22 files reviewed, 11 unresolved discussions (waiting on @janekmi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1170#-MgerO1tCaXbts8mqPz5:-MgkUykm2oa5Spd6D_W3:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we should also add a note to the documentation e.g.

```
RETURN VALUE
The rpma_conn_completion_get() function returns 0 on success or a negative error code on failure. On success, it writes the first available completion to *cmpl*. If *op_status* of the written *cmpl* will not be equal to **IBV_WC_SUCCESS** then only *op_context* of the returned *cmpl* is valid.
```
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1170#-MgfFPAT9zy6B2HGfjAF:-MgkUzMvAXA_H62W8I7h:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Missing error handling fixes:
- https://github.com/pmem/rpma/blob/master/examples/09-flush-to-persistent-GPSPM/server.c#L236
</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1170#-MgfG1YfEk3G0BnL5--U:-MgkUzjO6ZpY9-6hAFYy:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Missing error messages when `op_status != IBV_WC_STATUS`:
- https://github.com/pmem/rpma/blob/master/examples/05-flush-to-persistent/client.c#L262
- https://github.com/pmem/rpma/blob/master/examples/08-messages-ping-pong/client.c#L132
- https://github.com/pmem/rpma/blob/master/examples/09-flush-to-persistent-GPSPM/client.c#L265
- https://github.com/pmem/rpma/blob/master/examples/09-flush-to-persistent-GPSPM/server.c#L283

I know it is not what you meant but you have started yourself by incorporating the fix to error messages. xD
</blockquote></details>

Done.

---
___
*[examples/02-read-to-volatile/client.c, line 137 at r3](https://reviewable.io/reviews/pmem/rpma/1170#-MgfCJGJ8RV-VOuoyanf:-MgkV-iA9dQbsSgqCBGP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1fed6b28616b393ad1d1c83923b76eaa11afe74a/examples/02-read-to-volatile/client.c#L137)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

rpma_read()
</blockquote></details>

Done.
___
*[examples/03-read-to-persistent/server.c, line 186 at r3](https://reviewable.io/reviews/pmem/rpma/1170#-MgfCYIU5C-QOSwQ9-v9:-MgkV0ix0VcdNT9mnRrs:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1fed6b28616b393ad1d1c83923b76eaa11afe74a/examples/03-read-to-persistent/server.c#L186)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[examples/04-write-to-persistent/client.c, line 250 at r3](https://reviewable.io/reviews/pmem/rpma/1170#-MgfCqfPBrAH1lgS8bgH:-MgkV1Zj0i-s-7v19qvU:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1fed6b28616b393ad1d1c83923b76eaa11afe74a/examples/04-write-to-persistent/client.c#L250)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[examples/06-multiple-connections/server.c, line 237 at r3](https://reviewable.io/reviews/pmem/rpma/1170#-MgfDPcODLcfX4jbibHG:-MgkV38m7eHqpXq_bZNi:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1fed6b28616b393ad1d1c83923b76eaa11afe74a/examples/06-multiple-connections/server.c#L237)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/cq.c, line 125 at r3](https://reviewable.io/reviews/pmem/rpma/1170#-MgfBbLcE_P-mysn2ryN:-MgkV5aI3ghP7jalcnRf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1fed6b28616b393ad1d1c83923b76eaa11afe74a/src/cq.c#L125)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

/* When wc.status != IBV_WC_SUCCESS only the following attributes are valid: wr_id, status, qp_num, and vendor_err. */
</blockquote></details>

Done.
___
*[tests/unit/cq/cq-get_completion.c, line 101 at r3](https://reviewable.io/reviews/pmem/rpma/1170#-Mgf85tx26dufJoeFNoW:-MgkV7YuB7w4RbK3jEcH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1fed6b28616b393ad1d1c83923b76eaa11afe74a/tests/unit/cq/cq-get_completion.c#L101)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I would call it `an error wc.status`.
</blockquote></details>

Done.
___
*[tests/unit/cq/cq-get_completion.c, line 105 at r3](https://reviewable.io/reviews/pmem/rpma/1170#-Mgf8nL_3cHl9G8ZR-Mf:-MgkV8EW57DFgMgrEcVb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1fed6b28616b393ad1d1c83923b76eaa11afe74a/tests/unit/cq/cq-get_completion.c#L105)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
assert_int_not_equal(MOCK_WC_STATUS_ERROR, IBV_WC_SUCCESS);
```

Just in case. ;-)
</blockquote></details>

Done.
___
*[tests/unit/cq/cq-get_completion.c, line 123 at r3](https://reviewable.io/reviews/pmem/rpma/1170#-MgfACeaEqo7M715oyQ2:-MgkVD4X08Mcds5vlBpR:b-nw6wll) ([raw file](https://github.com/pmem/rpma/blob/1fed6b28616b393ad1d1c83923b76eaa11afe74a/tests/unit/cq/cq-get_completion.c#L123)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we should also verify that other fields are not modified just in case somebody won't understand your change in the future and decide he needs other fields. xD

```c
struct rpma_completion cmpl_pattern;
memset(&cmpl_pattern, 0xba, sizeof(struct rpma_completion));

/* ... */
struct rpma_completion cmpl = cmpl_pattern;

/* ... */
assert_int_equal(cmpl.op, cmpl_pattern.op);
/* and the rest of the fields which should not be touched at all */
```
</blockquote></details>

Done. Initialize `cmpl` to a custom value.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 21 of 21 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1170)* status: all files reviewed, 12 unresolved discussions (waiting on @janekmi and @yangx-jy)

___
*[src/include/librpma.h, line 2561 at r4](https://reviewable.io/reviews/pmem/rpma/1170#-MhSyDS17Z77kafwp3vL:-MhSyDS2Cc1bySXuTvjw:b-5x98km) ([raw file](https://github.com/pmem/rpma/blob/023ac5ca910def67c67a63136d3d9a22fcf12c07/src/include/librpma.h#L2561)):*
> ```
> will not be equal to
> ```

is not equal to

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1170#-:-MhT-2se8zwgIrfL8DDn:bnfp4nl)* status: all files reviewed, 12 unresolved discussions (waiting on @janekmi and @yangx-jy)

**Review by ldorau — COMMENTED** [review]
(1 my issue left)

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1170#-:-MhT-5Zd6_ItpXLz6-9F:b-msclif)* status: all files reviewed, 12 unresolved discussions (waiting on @janekmi and @yangx-jy)

**Review by yangx-jy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1170)* status: 16 of 22 files reviewed, 12 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[src/include/librpma.h, line 2561 at r4](https://reviewable.io/reviews/pmem/rpma/1170#-MhSyDS17Z77kafwp3vL:-MhTV9Vw8PbXlNa5n9Hu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/023ac5ca910def67c67a63136d3d9a22fcf12c07/src/include/librpma.h#L2561)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> will not be equal to
> ```

is not equal to
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1170)* status: all files reviewed, 11 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 15 of 21 files at r4, 6 of 6 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1170#-:-MhmrEXI-cJTM4OCYEXj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Pull request merged**
