### PR TITLE
tools: run pylint on the tests of the runners

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1462)

### CODE REVIEW

**Review by grom72 — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1462)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1462#-:-Ms5KJi27X3ysPpNYyXg:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
All OSes pass now: https://github.com/ldorau/rpma/actions/runs/1634485290

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1462#-:-Ms5oOylDM38NFz3a99d:bg39agz)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1462)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1462#-Ms5pawO39eVoWE05ws9:-Ms5pawPETmWLbDCwpWQ:b955bzy) (no related file):*
Shall we skip test_bash_runner as we are going to remove all bash scripts support?

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1462)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1462#-Ms5pawO39eVoWE05ws9:-Ms5qEMh51T7DCyIMARY:b-26kpvk) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Shall we skip test_bash_runner as we are going to remove all bash scripts support?
</blockquote></details>

How can we skip it?

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1462)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1462#-Ms5pawO39eVoWE05ws9:-Ms5sp3h0KDh6fabmjH0:b-ok8v8o) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

How can we skip it?
</blockquote></details>

I removed this test

---

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1462#-:-Ms5tE5a4_UEhJILw_9-:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
