### PR TITLE
doc: librpma.7: sync and async modes

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/501)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/501)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/501#-:-MITxtFy8p-l57-JJau8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/501)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 124 at r1](https://reviewable.io/reviews/pmem/rpma/501#-MIULi1I7v1SstqH8QvD:-MIULi1I7v1SstqH8QvE:b-ltn8dn) ([raw file](https://github.com/pmem/rpma/blob/cf5b229bd35c915b0df296b1e59620674f700ea7/src/include/librpma.h#L124)):*
> ```
> in a synchronous
> ```

in the synchronous
___
*[src/include/librpma.h, line 129 at r1](https://reviewable.io/reviews/pmem/rpma/501#-MIULn3GDkBk2XlBz8Z2:-MIULn3GDkBk2XlBz8Z3:b-qybh44) ([raw file](https://github.com/pmem/rpma/blob/cf5b229bd35c915b0df296b1e59620674f700ea7/src/include/librpma.h#L129)):*
> ```
>  * - rpma_ep_next_conn_req()
>  * - rpma_conn_prepare_completions()
>  * - rpma_conn_get_next_event()
> ```

```
 * - rpma_ep_next_conn_req(),
 * - rpma_conn_prepare_completions() and
 * - rpma_conn_get_next_event()
```
___
*[src/include/librpma.h, line 132 at r1](https://reviewable.io/reviews/pmem/rpma/501#-MIULwHg3hRKMXtmzQhw:-MIULwHg3hRKMXtmzQhx:b-3kko3y) ([raw file](https://github.com/pmem/rpma/blob/cf5b229bd35c915b0df296b1e59620674f700ea7/src/include/librpma.h#L132)):*
> ```
> respective file descriptors
> ```

`the respective file descriptors`
___
*[src/include/librpma.h, line 140 at r1](https://reviewable.io/reviews/pmem/rpma/501#-MIUMgIMCtx-DGgwMHDJ:-MIUMgIMCtx-DGgwMHDK:b-rdsxfm) ([raw file](https://github.com/pmem/rpma/blob/cf5b229bd35c915b0df296b1e59620674f700ea7/src/include/librpma.h#L140)):*
> ```
>  * Having a file descriptor you can make it non-blocking, at the same time
>  * making non-blocking the respective API call, using fcntl(2) as follows:
> ```

Shorter and simpler sentence, please ;-)
Maybe in this way:

```
When you have a file descriptor, you can make it non-blocking using fcntl(2) as follows:
...
Such change makes the respective API call non-blocking automatically.
```

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/501)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/include/librpma.h, line 124 at r1](https://reviewable.io/reviews/pmem/rpma/501#-MIULi1I7v1SstqH8QvD:-MIV5SkI0Xxk1ecOPXnB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cf5b229bd35c915b0df296b1e59620674f700ea7/src/include/librpma.h#L124)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> in a synchronous
> ```

in the synchronous
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 129 at r1](https://reviewable.io/reviews/pmem/rpma/501#-MIULn3GDkBk2XlBz8Z2:-MIV5X6gCBNRRytHRqTl:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cf5b229bd35c915b0df296b1e59620674f700ea7/src/include/librpma.h#L129)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  * - rpma_ep_next_conn_req()
>  * - rpma_conn_prepare_completions()
>  * - rpma_conn_get_next_event()
> ```

```
 * - rpma_ep_next_conn_req(),
 * - rpma_conn_prepare_completions() and
 * - rpma_conn_get_next_event()
```
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 132 at r1](https://reviewable.io/reviews/pmem/rpma/501#-MIULwHg3hRKMXtmzQhw:-MIV5a9m9Nj1b0JtFJ3K:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cf5b229bd35c915b0df296b1e59620674f700ea7/src/include/librpma.h#L132)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> respective file descriptors
> ```

`the respective file descriptors`
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 140 at r1](https://reviewable.io/reviews/pmem/rpma/501#-MIUMgIMCtx-DGgwMHDJ:-MIV6AwtD2PchUVn6L8P:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cf5b229bd35c915b0df296b1e59620674f700ea7/src/include/librpma.h#L140)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  * Having a file descriptor you can make it non-blocking, at the same time
>  * making non-blocking the respective API call, using fcntl(2) as follows:
> ```

Shorter and simpler sentence, please ;-)
Maybe in this way:

```
When you have a file descriptor, you can make it non-blocking using fcntl(2) as follows:
...
Such change makes the respective API call non-blocking automatically.
```
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/501)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/501#-:-MIVGbtS8V8oKY99a-XN:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
