### PR TITLE
rpma: ib_read.sh tests ib_read_lat and ib_read_bw

### PR DESCRIPTION
**Pull request by ldorau**
Rename ib_read_lat.sh to ib_read.sh and make it
test ib_read_lat and ib_read_bw.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/617)

### CODE REVIEW

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/617#-:-MNd3PRzDxxP9V05POlB:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/ib_read.sh, line 59 at r1](https://reviewable.io/reviews/pmem/rpma/617#-MNd38gWE2Fu2nmhrJrJ:-MNd38gWE2Fu2nmhrJrK:b-czxe9z) ([raw file](https://github.com/pmem/rpma/blob/d297cdbc68be16760757cbc4f0528b20919cba0a/tools/ib_read.sh#L59)):*
> ```Shell
> 	;;
> *)
> 	echo "Wrong mode: $MODE"
> ```

Please use `usage`.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/617#-:-MNd3SJnEBshbOAOLT7J:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/617)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/ib_read.sh, line 59 at r1](https://reviewable.io/reviews/pmem/rpma/617#-MNd38gWE2Fu2nmhrJrJ:-MNhNm-u86lSwx4DlBV2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d297cdbc68be16760757cbc4f0528b20919cba0a/tools/ib_read.sh#L59)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please use `usage`.
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/617#-:-MNhc--Y0FqUUmWUnVNj:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/617)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
