### PR TITLE
test: add missing tests for rpma_conn_req_delete()

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1675)

### CODE REVIEW

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1675#-:-N01DPhiAJG3seU7vD5F:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1675)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1675)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1675#-N02D9a-CXFVgiSQKE5I):*
tests



_Code quote:_
```
test
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1675)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1675#-N02D9a-CXFVgiSQKE5I):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

tests
</blockquote></details>

Done.
___
*[tests/unit/conn_req/conn_req-delete.c, line 614 at r1](https://reviewable.io/reviews/pmem/rpma/1675#-N02BVPl1bJcDDtGFd9d:-N04SYOFBUC1peUsptjl:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/51a52175fe4b429e9db93703463699f836115416/tests/unit/conn_req/conn_req-delete.c#L614)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

wrong indentation
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1675)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1675#-:-N04bVfK6uBjKF25uDLs:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
