### PR TITLE
tools: implement kvtable.dict2kvtable()

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1115)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1115)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/lib/kvtable.py, line 28 at r1](https://reviewable.io/reviews/pmem/rpma/1115#-MdXzbWI4k7GgGA4rtJY:-MdXzbWI4k7GgGA4rtJZ:b-gsfz57) ([raw file](https://github.com/pmem/rpma/blob/e29b18a5a71afcc7f660235b02c2925c1539a6b4/tools/perf/lib/kvtable.py#L28)):*
> ```Python
>             for var, txt in env.items():
>                 line.replace("{" + var + "}", txt)
>         html += "<tr><td>" + item + "</td><td>" + lines2str(desc) + "</td></tr>"
> ```

You assume `item` is a string. Which may be not true. `str(item)` instead?
___
*[tools/perf/lib/kvtable.py, line 28 at r1](https://reviewable.io/reviews/pmem/rpma/1115#-MdXzn_DB_V2ng7IOyJg:-MdXzn_DB_V2ng7IOyJh:b3jd229) ([raw file](https://github.com/pmem/rpma/blob/e29b18a5a71afcc7f660235b02c2925c1539a6b4/tools/perf/lib/kvtable.py#L28)):*
> ```Python
>             for var, txt in env.items():
>                 line.replace("{" + var + "}", txt)
>         html += "<tr><td>" + item + "</td><td>" + lines2str(desc) + "</td></tr>"
> ```

You assume `desc` is a list. TBH `lines2str()` should detect such misuse and return an error.

Ref: #1118

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1115)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/lib/kvtable.py, line 28 at r1](https://reviewable.io/reviews/pmem/rpma/1115#-MdXzbWI4k7GgGA4rtJY:-MdaGR9F0sUMn_CI7pJK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e29b18a5a71afcc7f660235b02c2925c1539a6b4/tools/perf/lib/kvtable.py#L28)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You assume `item` is a string. Which may be not true. `str(item)` instead?
</blockquote></details>

Done.
___
*[tools/perf/lib/kvtable.py, line 28 at r1](https://reviewable.io/reviews/pmem/rpma/1115#-MdXzn_DB_V2ng7IOyJg:-MdaKBTa-8oN1qpB4raf:bg59axr) ([raw file](https://github.com/pmem/rpma/blob/e29b18a5a71afcc7f660235b02c2925c1539a6b4/tools/perf/lib/kvtable.py#L28)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You assume `desc` is a list. TBH `lines2str()` should detect such misuse and return an error.

Ref: #1118
</blockquote></details>

Will be done in a separate PR.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1115)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/lib/kvtable.py, line 28 at r1](https://reviewable.io/reviews/pmem/rpma/1115#-MdXzn_DB_V2ng7IOyJg:-MdaKszZBX0kMeNK7F2t:b6npapm) ([raw file](https://github.com/pmem/rpma/blob/e29b18a5a71afcc7f660235b02c2925c1539a6b4/tools/perf/lib/kvtable.py#L28)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Will be done in a separate PR.
</blockquote></details>

https://github.com/pmem/rpma/pull/1119

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1115)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/lib/kvtable.py, line 28 at r1](https://reviewable.io/reviews/pmem/rpma/1115#-MdXzn_DB_V2ng7IOyJg:-MdaKvuI5NmZlzUdZ5Qg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e29b18a5a71afcc7f660235b02c2925c1539a6b4/tools/perf/lib/kvtable.py#L28)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

https://github.com/pmem/rpma/pull/1119
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1115#-:-MdpPFuN9fGlkbQGKIvf:bnfp4nl)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1115#-:-MdpQez42tXo-jV-Q9x0:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
