### PR TITLE
common: add BUILD_FORCE_NATIVE_ATOMIC_WRITE_NOT_SUPPORTED option

### PR DESCRIPTION
**Pull request by ldorau**
Add BUILD_FORCE_NATIVE_ATOMIC_WRITE_NOT_SUPPORTED option and a relevant test.

- - -
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/2125)

### CODE REVIEW

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2125#-:-NQQvnVfCJX1sAKKuKIy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Comment by yangx-jy** [comment]
Please see #2122

**Review by ldorau — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2125#-:-NQUBj9hDAvpPhGsDJsd:bb6un1j)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @grom72)

**Review by yangx-jy — COMMENTED** [review]
:lgtm:

> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2125#-:-NQUKP7J0RzkGXXetMCl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
