### PR TITLE
test: fix failing log_default-function tests in Release build

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/315)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/315)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tests/unit/log_default/CMakeLists.txt, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/315#-MG2V41vCudpa5SwjZ89:-MG2V41vCudpa5SwjZ8A:bzg11mw) ([raw file](https://github.com/pmem/rpma/blob/704c9a2a31158a18064a584de02e39faef38e1c6/tests/unit/log_default/CMakeLists.txt#L13)):*
> ```
> add_flag("-U_FORTIFY_SOURCE" RELEASE)
> ```
shall we have a separate binary target with -D_FORTIFY_SOURCE that executes all tests except these that fails?

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/315)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/315)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tests/unit/log_default/CMakeLists.txt, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/315#-MG2V41vCudpa5SwjZ89:-MG2VqXxC5F-NCOPQZlc:bqdtsle) ([raw file](https://github.com/pmem/rpma/blob/704c9a2a31158a18064a584de02e39faef38e1c6/tests/unit/log_default/CMakeLists.txt#L13)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> add_flag("-U_FORTIFY_SOURCE" RELEASE)
> ```
shall we have a separate binary target with -D_FORTIFY_SOURCE that executes all tests except these that fails?
</blockquote></details>

We already have now. This patch affects only 'log_default' tests.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/315#-:-MG2WrTk7hUX9ViI8sso:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/315#-:-MG2bB2O3oVcFUr_gQHB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
