### PR TITLE
tools: perf: introduce a CPU_LOAD_RANGE environment

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1030)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1030)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/rpma_fio_bench.sh, line 107 at r1](https://reviewable.io/reviews/pmem/rpma/1030#-MZIr0MwDcaZ5obLTn4O:-MZIr0MwDcaZ5obLTn4P:b21kqfp) ([raw file](https://github.com/pmem/rpma/blob/96f56716f8cc7e299b95aadcb72fc89743823467/tools/perf/rpma_fio_bench.sh#L107)):*
> ```Shell
> 		CPU_LOAD=(${!"CPU_LOAD_$CPU_LOAD_RANGE"})
> 		ITERATIONS=${#CPU_LOAD[@]}
> 		NAME_SUFFIX=th${THREADS}_bs${BLOCK_SIZE}_dp${DEPTH}_cpu${CPU_LOAD_RANGE}
> ```

Not needed.
This is added below ITER=cpu${CPU}
___
*[tools/perf/rpma_fio_bench.sh, line 116 at r1](https://reviewable.io/reviews/pmem/rpma/1030#-MZIrJZtBnoqtss8B5Wr:-MZIrJZtBnoqtss8B5Ws:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/96f56716f8cc7e299b95aadcb72fc89743823467/tools/perf/rpma_fio_bench.sh#L116)):*
> ```Shell
> 		CPU_LOAD=(${!"CPU_LOAD_$CPU_LOAD_RANGE"})
> 		ITERATIONS=${#CPU_LOAD[@]}
> 		NAME_SUFFIX=th${THREADS}_bs${BLOCK_SIZE}_dp${DEPTH}_cpu${CPU_LOAD_RANGE}
> ```

.
___
*[tools/perf/rpma_fio_bench.sh, line 133 at r1](https://reviewable.io/reviews/pmem/rpma/1030#-MZIrKMbEIekYB9Aqm9q:-MZIrKMbEIekYB9Aqm9r:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/96f56716f8cc7e299b95aadcb72fc89743823467/tools/perf/rpma_fio_bench.sh#L133)):*
> ```Shell
> 		CPU_LOAD=(${!"CPU_LOAD_$CPU_LOAD_RANGE"})
> 		ITERATIONS=${#CPU_LOAD[@]}
> 		NAME_SUFFIX=th${THREADS}_bs${BLOCK_SIZE}_dp${DEPTH}_cpu${CPU_LOAD_RANGE}
> ```

.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1030)* status: 1 of 3 files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/rpma_fio_bench.sh, line 107 at r1](https://reviewable.io/reviews/pmem/rpma/1030#-MZIr0MwDcaZ5obLTn4O:-MZIwtdTCvz7Vd12cgwo:b-rldbb1) ([raw file](https://github.com/pmem/rpma/blob/96f56716f8cc7e299b95aadcb72fc89743823467/tools/perf/rpma_fio_bench.sh#L107)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Not needed.
This is added below ITER=cpu${CPU}
</blockquote></details>

1. `ITER` stores the current value of the CPU load whereas I want to add **the CPU range** to the file name
2. Is `ITER` even used anyway? xD
___
*[tools/perf/rpma_fio_bench.sh, line 116 at r1](https://reviewable.io/reviews/pmem/rpma/1030#-MZIrJZtBnoqtss8B5Wr:-MZIxDdX81_1N4-NRLDc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/96f56716f8cc7e299b95aadcb72fc89743823467/tools/perf/rpma_fio_bench.sh#L116)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 133 at r1](https://reviewable.io/reviews/pmem/rpma/1030#-MZIrKMbEIekYB9Aqm9q:-MZIxDukBb4vSAWrvHYS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/96f56716f8cc7e299b95aadcb72fc89743823467/tools/perf/rpma_fio_bench.sh#L133)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1030)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/bench_common.sh, line 35 at r2](https://reviewable.io/reviews/pmem/rpma/1030#-MZJqk_680KXfrSrnDQZ:-MZJqk_7DXeaGyxh-OjL:b2yl62t) ([raw file](https://github.com/pmem/rpma/blob/ca538a78431385eb0e18ad50a15fc62dd4f8448d/tools/perf/bench_common.sh#L35)):*
> ```Shell
> 	echo "export REMOTE_JOB_PATH=$REMOTE_JOB_PATH"
> 	echo "export REMOTE_JOB_MEM_PATH=$REMOTE_JOB_MEM_PATH"
> 	echo "export BUSY_WAIT_POLLING=$BUSY_WAIT_POLLING"
> ```

echo "export CPU_LOAD_RANGE=$CPU_LOAD_RANGE"
___
*[tools/perf/rpma_fio_bench.sh, line 107 at r1](https://reviewable.io/reviews/pmem/rpma/1030#-MZIr0MwDcaZ5obLTn4O:-MZJmirN3DdLENx6FPmZ:b-skji3) ([raw file](https://github.com/pmem/rpma/blob/96f56716f8cc7e299b95aadcb72fc89743823467/tools/perf/rpma_fio_bench.sh#L107)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

1. `ITER` stores the current value of the CPU load whereas I want to add **the CPU range** to the file name
2. Is `ITER` even used anyway? xD
</blockquote></details>

2. to RUN_NAME

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1030)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tools/perf/rpma_fio_bench.sh, line 107 at r1](https://reviewable.io/reviews/pmem/rpma/1030#-MZIr0MwDcaZ5obLTn4O:-MZMH6mQ5zol2HvLQhTB:bo2reya) ([raw file](https://github.com/pmem/rpma/blob/96f56716f8cc7e299b95aadcb72fc89743823467/tools/perf/rpma_fio_bench.sh#L107)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

2. to RUN_NAME
</blockquote></details>

I have missed it. Sorry. ;-)
Nevertheless, `ITER` is per revolution. Whereas I need a description of the whole `benchmark_one()` run.

Done done.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1030)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/bench_common.sh, line 35 at r2](https://reviewable.io/reviews/pmem/rpma/1030#-MZJqk_680KXfrSrnDQZ:-MZMI1eS3UVBgNU5UQ7E:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ca538a78431385eb0e18ad50a15fc62dd4f8448d/tools/perf/bench_common.sh#L35)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

echo "export CPU_LOAD_RANGE=$CPU_LOAD_RANGE"
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1030#-:-MZMOZiw43L59dA8HbwZ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 1 of 1 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1030)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/rpma_fio_bench.sh, line 50 at r3](https://reviewable.io/reviews/pmem/rpma/1030#-MZMSIPIBYj7rPzIbCcG:-MZMSIPJ-B3EkuX_MGet:bsxlenh) ([raw file](https://github.com/pmem/rpma/blob/1837577aaaa635de253ec006d2f9349e43cd3c8a/tools/perf/rpma_fio_bench.sh#L50)):*
> ```
> ${CPU_LOAD_RANGE-00_100} 
> ```

`${CPU_LOAD_RANGE_00_100} `

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1030)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/rpma_fio_bench.sh, line 50 at r3](https://reviewable.io/reviews/pmem/rpma/1030#-MZMSIPIBYj7rPzIbCcG:-MZMSxHXAMGwITOki_eQ:b-98zajm) ([raw file](https://github.com/pmem/rpma/blob/1837577aaaa635de253ec006d2f9349e43cd3c8a/tools/perf/rpma_fio_bench.sh#L50)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> ${CPU_LOAD_RANGE-00_100} 
> ```

`${CPU_LOAD_RANGE_00_100} `
</blockquote></details>

No mistake here. This way I set the default value. (comment) ;-)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1030)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1030#-:-MZMXbV28coQWD0ti-Sf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
