### PR TITLE
rpma: scaffolding for rpma_atomic_write()

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1594)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1594)* status: 3 of 9 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[src/include/librpma.h, line 2491 at r1](https://reviewable.io/reviews/pmem/rpma/1594#-MwaSwJU7qU_MTVNY_gc:-MwaSwJVEdndmPYxIn-D:b-5iizm5) ([raw file](https://github.com/pmem/rpma/blob/371ec6d65de9ff3e1a036be0c37c56fcf5d3731e/src/include/librpma.h#L2491)):*
> ```objc
> 
> /** 3
>  * rpma_write_atomic_8b -- initiate the atomic 8b write operation
> ```

rpma_atomic_write



_Code quote:_
```objc
rpma_write_atomic_8b
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1594)* status: 3 of 9 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[src/include/librpma.h, line 2491 at r1](https://reviewable.io/reviews/pmem/rpma/1594#-MwaSwJU7qU_MTVNY_gc:-Mwabck97Gn0wyLajLx3:b3kre) ([raw file](https://github.com/pmem/rpma/blob/371ec6d65de9ff3e1a036be0c37c56fcf5d3731e/src/include/librpma.h#L2491)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

rpma_atomic_write
</blockquote></details>

?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1594)* status: 0 of 9 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[src/include/librpma.h, line 2491 at r1](https://reviewable.io/reviews/pmem/rpma/1594#-MwaSwJU7qU_MTVNY_gc:-MwamQEp6sHVcd55PnHD:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/371ec6d65de9ff3e1a036be0c37c56fcf5d3731e/src/include/librpma.h#L2491)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

?
</blockquote></details>

Done

**Review by grom72 — APPROVED** [review]
> Reviewed 2 of 9 files at r1, 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1594)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1594#-:-MwasD4bAXn7J6Z-KTJc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1594)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1594)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
