### PR TITLE
tools: change working directory before generating figures

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1188)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1188)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[tools/perf/lib/Figure.py, line 153 at r1](https://reviewable.io/reviews/pmem/rpma/1188#-MgGAkRt0Y_SEkaM9aka:-MgGAkRt0Y_SEkaM9akb:b-qh4ihz) ([raw file](https://github.com/pmem/rpma/blob/f9ccc6d26c037b1c3d87aee624581483a277e72c/tools/perf/lib/Figure.py#L153)):*
> ```Python
>         return os.path.join('.', output)
> 
>     def to_png(self, result_dir):
> ```

The result_dir is provided for the constructor of this object. I think it will be easier to just store it inside the object e.g.

```python
# in the __init__()
self.result_dir = result_dir
```

and just use it from there.
___
*[tools/perf/lib/Figure.py, line 186 at r1](https://reviewable.io/reviews/pmem/rpma/1188#-MgGA2wT3caz5HKtbJ4u:-MgGA2wT3caz5HKtbJ4v:bqj0eu2) ([raw file](https://github.com/pmem/rpma/blob/f9ccc6d26c037b1c3d87aee624581483a277e72c/tools/perf/lib/Figure.py#L186)):*
> ```Python
>         ax.grid(True)
> 
>         os.chdir(result_dir)
> ```

I do not like the idea of changing the working directory for each of the figures. It would make sense if each of them can require a different location. But it is not the case so far. I do like the independence of the Figure object though.

It is a surprising solution to me. But... I will keep it. Thanks.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1188)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/Figure.py, line 153 at r1](https://reviewable.io/reviews/pmem/rpma/1188#-MgGAkRt0Y_SEkaM9aka:-MgGDG0u2n_AHh0YgW-G:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f9ccc6d26c037b1c3d87aee624581483a277e72c/tools/perf/lib/Figure.py#L153)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The result_dir is provided for the constructor of this object. I think it will be easier to just store it inside the object e.g.

```python
# in the __init__()
self.result_dir = result_dir
```

and just use it from there.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1188)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by janekmi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1188#-:-MgIBWl-6A6z7ZDrJE-M:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
