### PR TITLE
common: add information about CircleCi environment

### PR DESCRIPTION
**Pull request by grom72**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/2133)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2133)* status: all files reviewed, 3 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/pmem/rpma/2133#-NWfLVVr-wKl27EV9kQK):*
CircleCI



_Code quote:_
```
CircleCi
```
___
*[`DEVELOPMENT.md` line 226 at r1](https://reviewable.io/reviews/pmem/rpma/2133#-NWfLYFv5Rw7ocplb6uh:-NWfLYFv5Rw7ocplb6ui:bchcr4r) ([raw file](https://github.com/pmem/rpma/blob/fe5ba5093073b8f22d95cfa8a6644b9f88769a52/DEVELOPMENT.md#L226)):*
> ```Markdown
> ```
> 
> # CircleCi validation environment
> ```

CircleCI



_Code quote:_
```Markdown
CircleCi
```
___
*[`DEVELOPMENT.md` line 228 at r1](https://reviewable.io/reviews/pmem/rpma/2133#-NWfLsgw5fh5QZ1lXyxV:-NWfLsgw5fh5QZ1lXyxW:b-e7kcg2) ([raw file](https://github.com/pmem/rpma/blob/fe5ba5093073b8f22d95cfa8a6644b9f88769a52/DEVELOPMENT.md#L228)):*
> ```Markdown
> # CircleCi validation environment
> 
> Visit https://app.circleci.com/pipelines/github/pmem/rpma where most of the library validation process (with native SoftRoCE-based RDMA) is done.
> ```

Hmm... I am not sure about that...



_Code quote:_
```Markdown
most of
```

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2133)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[`-- commits` line 2 at r1](https://reviewable.io/reviews/pmem/rpma/2133#-NWfLVVr-wKl27EV9kQK):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

CircleCI
</blockquote></details>

Done.
___
*[`DEVELOPMENT.md` line 226 at r1](https://reviewable.io/reviews/pmem/rpma/2133#-NWfLYFv5Rw7ocplb6uh:-NWgkB5S3Z-6npEn3Ta_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fe5ba5093073b8f22d95cfa8a6644b9f88769a52/DEVELOPMENT.md#L226)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

CircleCI
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2133)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2133#-:-NWgm7uXCyZhg_w2aJdv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
