### PR TITLE
test: mt: introduce init/fini for prestate

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1019)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1019)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 49 at r1](https://reviewable.io/reviews/pmem/rpma/1019#-MYx3Z-Y1JRdK_Cm9h8Q:-MYx3Z-Y1JRdK_Cm9h8R:b-7gnmc2) ([raw file](https://github.com/pmem/rpma/blob/2f94fbdd37fee4d808803a07df21437ea5398928/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L49)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> 			NULL,
> 			NULL,
> 			NULL,
> 			thread,
> 			NULL,
> 			NULL,
> 			NULL
> ```
</details>

Shall we consider a macro (see cmocka) for a simple test definition?

**Review by grom72 — COMMENTED** [review]
:goat: becomes bigger and bigger ;)

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1019#-:-MYx3rXi3Eowr6TmKNlH:bdi4pyz)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
Everything according to the plan. :sheep:  ;-)

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1019#-:-MYxXlNH6MCU7pDZUr25:bz3dzqf)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 49 at r1](https://reviewable.io/reviews/pmem/rpma/1019#-MYx3Z-Y1JRdK_Cm9h8Q:-MYxXQm5043gg7KDXH1B:brbdzed) ([raw file](https://github.com/pmem/rpma/blob/2f94fbdd37fee4d808803a07df21437ea5398928/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L49)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> 			NULL,
> 			NULL,
> 			NULL,
> 			thread,
> 			NULL,
> 			NULL,
> 			NULL
> ```
Shall we consider a macro (see cmocka) for a simple test definition?
</blockquote></details>

We will see how many such tests we will have.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1019)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tests/multithreaded/common/mtt.h, line 73 at r1](https://reviewable.io/reviews/pmem/rpma/1019#-MYyCTLE5OfJ7wqxYe5v:-MYyCTLE5OfJ7wqxYe5w:bkjd5y2) ([raw file](https://github.com/pmem/rpma/blob/2f94fbdd37fee4d808803a07df21437ea5398928/tests/multithreaded/common/mtt.h#L73)):*
> ```
> to test-provided
> ```

to the ...
___
*[tests/multithreaded/common/mtt.h, line 136 at r1](https://reviewable.io/reviews/pmem/rpma/1019#-MYyCoTrCsHFEewO3BCT:-MYyCoTrCsHFEewO3BCU:b-tmmg9) ([raw file](https://github.com/pmem/rpma/blob/2f94fbdd37fee4d808803a07df21437ea5398928/tests/multithreaded/common/mtt.h#L136)):*
> ```
> 	 * a function called only once before the sequential threads
> 	 * initialization and dedicated to initializing the prestate
> ```

Full sentence please. It is complicated and not clear for me. Maybe like this?

```
A function called only once before the sequential initialization of all threads.
It is dedicated to initializing the prestate.
```
___
*[tests/multithreaded/common/mtt.h, line 167 at r1](https://reviewable.io/reviews/pmem/rpma/1019#-MYyDX4T7eXRJmhdGBk5:-MYyDX4UAu3wDpPF34vg:b6q8bzp) ([raw file](https://github.com/pmem/rpma/blob/2f94fbdd37fee4d808803a07df21437ea5398928/tests/multithreaded/common/mtt.h#L167)):*
> ```
> 	 * a function called only once after the sequential threads clean up
> 	 * and dedicated to cleaning up the prestate
> ```

```
A function called only once after the sequential clean up of all threads.
It is dedicated to cleaning up the prestate.
```
___
*[tests/multithreaded/example/example.c, line 59 at r1](https://reviewable.io/reviews/pmem/rpma/1019#-MYyEEUp7INnqZ6BpEPL:-MYyEEUp7INnqZ6BpEPM:b-c149vc) ([raw file](https://github.com/pmem/rpma/blob/2f94fbdd37fee4d808803a07df21437ea5398928/tests/multithreaded/example/example.c#L59)):*
> ```
>  a called once for all threads prestate initialization
> ```

prestate initialization called once for all threads 
___
*[tests/multithreaded/example/example.c, line 153 at r1](https://reviewable.io/reviews/pmem/rpma/1019#-MYyEKON6_Cl-7aqIfhi:-MYyEKON6_Cl-7aqIfhj:b-2004) ([raw file](https://github.com/pmem/rpma/blob/2f94fbdd37fee4d808803a07df21437ea5398928/tests/multithreaded/example/example.c#L153)):*
> ```
>  a called once for all threads prestate cleanup
> ```

prestate cleanup called once for all threads

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1019)* status: 2 of 4 files reviewed, 6 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tests/multithreaded/common/mtt.h, line 73 at r1](https://reviewable.io/reviews/pmem/rpma/1019#-MYyCTLE5OfJ7wqxYe5v:-MYyMb7K2fdeBs_E_mz5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2f94fbdd37fee4d808803a07df21437ea5398928/tests/multithreaded/common/mtt.h#L73)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> to test-provided
> ```

to the ...
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mtt.h, line 136 at r1](https://reviewable.io/reviews/pmem/rpma/1019#-MYyCoTrCsHFEewO3BCT:-MYyN0h24DgqFzprVXCM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2f94fbdd37fee4d808803a07df21437ea5398928/tests/multithreaded/common/mtt.h#L136)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 	 * a function called only once before the sequential threads
> 	 * initialization and dedicated to initializing the prestate
> ```

Full sentence please. It is complicated and not clear for me. Maybe like this?

```
A function called only once before the sequential initialization of all threads.
It is dedicated to initializing the prestate.
```
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mtt.h, line 167 at r1](https://reviewable.io/reviews/pmem/rpma/1019#-MYyDX4T7eXRJmhdGBk5:-MYyNH_oCWRoQH0sw2gp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2f94fbdd37fee4d808803a07df21437ea5398928/tests/multithreaded/common/mtt.h#L167)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 	 * a function called only once after the sequential threads clean up
> 	 * and dedicated to cleaning up the prestate
> ```

```
A function called only once after the sequential clean up of all threads.
It is dedicated to cleaning up the prestate.
```
</blockquote></details>

Done.
___
*[tests/multithreaded/example/example.c, line 59 at r1](https://reviewable.io/reviews/pmem/rpma/1019#-MYyEEUp7INnqZ6BpEPL:-MYyNOb53Pa_wJEQ92h0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2f94fbdd37fee4d808803a07df21437ea5398928/tests/multithreaded/example/example.c#L59)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  a called once for all threads prestate initialization
> ```

prestate initialization called once for all threads 
</blockquote></details>

Done.
___
*[tests/multithreaded/example/example.c, line 153 at r1](https://reviewable.io/reviews/pmem/rpma/1019#-MYyEKON6_Cl-7aqIfhi:-MYyNUim63mRnGcdocLV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2f94fbdd37fee4d808803a07df21437ea5398928/tests/multithreaded/example/example.c#L153)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  a called once for all threads prestate cleanup
> ```

prestate cleanup called once for all threads 
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1019)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1019#-:-MYyj10S4Se90RJEgPQ3:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1019#-:-MYysf0d4V3KRjyfC49A:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
