### PR TITLE
common: do not ignore errors of src2man

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #437

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/438)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
see #437 - the solution is to remove typedefs

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/438#-:-MHycaj24EcrfNOm1C80:b-vwgm6v)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/438)* status: all files reviewed, 1 unresolved discussion

___
*[src/include/librpma.h, line 1401 at r1](https://reviewable.io/reviews/pmem/rpma/438#-MHynmma89Pqccr9QlXL:-MHynmma89Pqccr9QlXM:b-nke3b7) ([raw file](https://github.com/pmem/rpma/blob/5ea4a1701f50641516b7f201547ace21a0ae5171/src/include/librpma.h#L1401)):*
> ```objc
>  *	#include <librpma.h>
>  *
>  *	int rpma_log_set_threshold(rpma_threshold threshold,
> ```

wrong fix

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/438#-:-MHyvKR12M1EZC-l8Wqu:bnfp4nl)* status: all files reviewed, 1 unresolved discussion

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/438#-:-MHywLOTBBNppfJZ7AVQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
