### PR TITLE
tools: describe the schematic variable in the report.json file

### PR DESCRIPTION
**Pull request by osalyk**
https://github.com/pmem/rpma/issues/1526

- - -
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/2008)

### CODE REVIEW

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2008)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2008)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2008#-NAJ4zZ4CwDWIgcgJWAe:-NAJ4zZ56oHICNAt2g1X:b-cnn9uf) (no related file):*
Do we have a solution in the script to handle this error?

___

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2008)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2008)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2008#-NAJLI9_3F6UUMVJHLIw:-NAJLI9_3F6UUMVJHLIx:b2jipo9) (no related file):*
```
************* Module lib.report.base
/rpma/tools/perf/lib/report/base.py:110:0: C0301: Line too long (94/80) (line-too-long)
```

___

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2008)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2008#-NAJ4zZ4CwDWIgcgJWAe:-NAJOrlGAY2CRMmtSa8q:b-896fix) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Do we have a solution in the script to handle this error?
</blockquote></details>

Done.

___
*[a discussion](https://reviewable.io/reviews/pmem/rpma/2008#-NAJLI9_3F6UUMVJHLIw:-NAJOs1ABLxLT0YeNEUQ:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
************* Module lib.report.base
/rpma/tools/perf/lib/report/base.py:110:0: C0301: Line too long (94/80) (line-too-long)
```
</blockquote></details>

Done.

___
___
*[`tools/perf/lib/report/base.py` line 113 at r2](https://reviewable.io/reviews/pmem/rpma/2008#-NAJKrMB-hevU8NiF1NL:-NAJOqzn6dxv1yC8tuki:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/223595075a4fedc38814c6782b776738f1fa1143/tools/perf/lib/report/base.py#L113)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

1) Please use spaces instead of tabs in a python code and make sure the alignment is correct.

2) Please make sure this code runs correctly
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2008)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`tools/perf/lib/report/base.py` line 113 at r2](https://reviewable.io/reviews/pmem/rpma/2008#-NAJKrMB-hevU8NiF1NL:-NAJR9-wCNBlZ4nCDmws:bdo2yeb) ([raw file](https://github.com/pmem/rpma/blob/223595075a4fedc38814c6782b776738f1fa1143/tools/perf/lib/report/base.py#L113)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

There are tabs still.

Have you run this code?

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2008)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`tools/perf/lib/report/base.py` line 113 at r2](https://reviewable.io/reviews/pmem/rpma/2008#-NAJKrMB-hevU8NiF1NL:-NAJTAek1uid9QyzKb0E:b-ovlyp7) ([raw file](https://github.com/pmem/rpma/blob/223595075a4fedc38814c6782b776738f1fa1143/tools/perf/lib/report/base.py#L113)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

There are tabs still.

Have you run this code?
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2008#-:-NAJTQu997U42sZ8QVDJ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by haichangsi — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2008)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2008)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`tools/perf/BENCHMARKING.md` line 113 at r4](https://reviewable.io/reviews/pmem/rpma/2008#-NAJsQRK47QpL9J2Ps0H:-NAJsQRLED-aVT0xau6G:b-tn2t0r) ([raw file](https://github.com/pmem/rpma/blob/b7ba6f9e9fd733d55c4382c8fed4d2421ed08e00/tools/perf/BENCHMARKING.md#L113)):*
> ```Markdown
> Make a copy of report.json.example (report.json) and adjust it to describe your configuration.
> Prepare a high-level view of the performance test configuration (Figure_0.png)
> and enter into the `schematic` variable in the report.json file
> ```

Prepare a high-level view of the performance test configuration (Figure_0.png)
and put it into the `schematic` variable in the report.json file.



_Code quote:_
```Markdown
Prepare a high-level view of the performance test configuration (Figure_0.png)
and enter into the `schematic` variable in the report.json file
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2008)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[`tools/perf/BENCHMARKING.md` line 113 at r4](https://reviewable.io/reviews/pmem/rpma/2008#-NAJsQRK47QpL9J2Ps0H:-NAJtF8L1ohOz90TRu_U:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/b7ba6f9e9fd733d55c4382c8fed4d2421ed08e00/tools/perf/BENCHMARKING.md#L113)):*
<details><summary><i>Previously, haichangsi (Kacper Stefanski) wrote…</i></summary><blockquote>

Prepare a high-level view of the performance test configuration (Figure_0.png)
and put it into the `schematic` variable in the report.json file.
</blockquote></details>

Done.

**Review by haichangsi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2008#-:-NAJu7X52BxqrFPxmPJV:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2008)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2008#-:-NAO5DhF9JORZ0MQxezJ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
