### PR TITLE
examples: add offset of the used persistent memory

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/2055)

### CODE REVIEW

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2055)* status: 0 of 14 files reviewed, all discussions resolved

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2055)* status: all files reviewed, 4 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2055#-NFO73hd7Btw6QNssABu:-NFO73hd7Btw6QNssABv:btlid03) (no related file):*
Please update also README.md files.

___
___
*[`examples/common/common-map_file_with_signature_check.c` line 27 at r1](https://reviewable.io/reviews/pmem/rpma/2055#-NFO4wVNExqz2NkNhgoV:-NFO4wVNExqz2NkNhgoW:undefined) ([raw file](https://github.com/pmem/rpma/blob/c72241ebb4eb30d915f5e468fb492b4b1fb3b598/examples/common/common-map_file_with_signature_check.c#L27)):*
> ```C
> 	 */
> 	size += mem->pmem_offset + SIGNATURE_LEN;
> 	mem->data_offset = mem->pmem_offset + SIGNATURE_LEN;
> ```





_Suggestion:_
```C
	
	mem->data_offset = mem->pmem_offset + SIGNATURE_LEN;
	size += mem->data_offset;
```
___
*[`examples/common/common-map_file_with_signature_check.c` line 39 at r1](https://reviewable.io/reviews/pmem/rpma/2055#-NFO6gy40O2jznldj2PD:-NFO6gy40O2jznldj2PE:undefined) ([raw file](https://github.com/pmem/rpma/blob/c72241ebb4eb30d915f5e468fb492b4b1fb3b598/examples/common/common-map_file_with_signature_check.c#L39)):*
> ```C
> 
> 	/* beginning of the used persistent memory */
> 	char *pmem_start = mem->mr_ptr + mem->pmem_offset;
> ```





_Suggestion:_
```C
pmem
```
___
*[`examples/common/common-pmem_map_file.h` line 22 at r1](https://reviewable.io/reviews/pmem/rpma/2055#-NFO6L4T9sHK6wkoCi0n:-NFO6L4U48781AWMmQXa:bychq6u) ([raw file](https://github.com/pmem/rpma/blob/c72241ebb4eb30d915f5e468fb492b4b1fb3b598/examples/common/common-pmem_map_file.h#L22)):*
> ```objc
> 	size_t mr_size;
> 	/* offset of the beginning of the used persistent memory */
> 	size_t pmem_offset;
> ```

It is just an offset.



_Suggestion:_
```objc
offset
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2055)* status: 7 of 19 files reviewed, 2 unresolved discussions (waiting on @grom72 and @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2055#-NFO73hd7Btw6QNssABu:-NFO985B9x1ZzZlSYeNE:b-896fix) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Please update also README.md files.
</blockquote></details>

Done.

___
___
*[`examples/common/common-pmem_map_file.h` line 22 at r1](https://reviewable.io/reviews/pmem/rpma/2055#-NFO6L4T9sHK6wkoCi0n:-NFO7zyIEKOp77WfGM8X:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c72241ebb4eb30d915f5e468fb492b4b1fb3b598/examples/common/common-pmem_map_file.h#L22)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

It is just an offset.
</blockquote></details>

Done.

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 5 of 12 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2055)* status: 12 of 19 files reviewed, 3 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[`examples/03-read-to-persistent/README.md` line 30 at r2](https://reviewable.io/reviews/pmem/rpma/2055#-NFO9PhE7cxsSL-4Qg3K:-NFO9PhE7cxsSL-4Qg3L:undefined) ([raw file](https://github.com/pmem/rpma/blob/36c3c99354c2f1d0d3bf867c4527a101d04b5f35/examples/03-read-to-persistent/README.md#L30)):*
> ```Markdown
> 
> ```bash
> [user@client]$ ./client $server_address $port [<pmem-path>] [<pmem-offset>]
> ```





_Suggestion:_
```Markdown
[<pmem-path> [<pmem-offset>]]
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2055)* status: 7 of 19 files reviewed, 3 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[`examples/03-read-to-persistent/README.md` line 30 at r2](https://reviewable.io/reviews/pmem/rpma/2055#-NFO9PhE7cxsSL-4Qg3K:-NFO9n18-dCccUfcRp1q:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/36c3c99354c2f1d0d3bf867c4527a101d04b5f35/examples/03-read-to-persistent/README.md#L30)):*
> ```Markdown
> 
> ```bash
> [user@client]$ ./client $server_address $port [<pmem-path>] [<pmem-offset>]
> ```

Done.



_Code quote:_
```Markdown
[<pmem-path>] [<pmem-offset>]
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2055)* status: 9 of 19 files reviewed, 6 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[`examples/04-write-to-persistent/README.md` line 29 at r2](https://reviewable.io/reviews/pmem/rpma/2055#-NFO9Xuy91nqs1D3TRQF:-NFO9x3i0CYHNPTCwCoP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/36c3c99354c2f1d0d3bf867c4527a101d04b5f35/examples/04-write-to-persistent/README.md#L29)):*
> ```Markdown
> 
> ```bash
> [user@client]$ ./client $server_address $port [<pmem-path>] [<pmem-offset>]
> ```

Done.
___
*[`examples/05-flush-to-persistent/README.md` line 35 at r2](https://reviewable.io/reviews/pmem/rpma/2055#-NFO9bCMCyKziNocAUo3:-NFO9yBA2SI26YllB0As:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/36c3c99354c2f1d0d3bf867c4527a101d04b5f35/examples/05-flush-to-persistent/README.md#L35)):*
> ```Markdown
> 
> ```bash
> [user@client]$ ./client $server_address $port [<pmem-path>] [<pmem-offset>]
> ```

Done.
___
*[`examples/09-flush-to-persistent-GPSPM/README.md` line 42 at r2](https://reviewable.io/reviews/pmem/rpma/2055#-NFO9fN08UDjgme8EQO5:-NFO9z6a5c2yU-NSHQx3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/36c3c99354c2f1d0d3bf867c4527a101d04b5f35/examples/09-flush-to-persistent-GPSPM/README.md#L42)):*
> ```Markdown
> 
> ```bash
> [user@client]$ ./client $server_address $port [<pmem-path>] [<pmem-offset>]
> ```

Done.
___
*[`examples/09scch-flush-to-persistent-GPSPM/README.md` line 47 at r2](https://reviewable.io/reviews/pmem/rpma/2055#-NFO9ig74l6C21Iw0MyZ:-NFO9zkb-2JpCdrgclDD:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/36c3c99354c2f1d0d3bf867c4527a101d04b5f35/examples/09scch-flush-to-persistent-GPSPM/README.md#L47)):*
> ```Markdown
> 
> ```bash
> [user@client]$ ./client $server_address $port [<pmem-path>] [<pmem-offset>]
> ```

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 9 of 10 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2055)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

**Review by haichangsi — COMMENTED** [review]
We should probably also update the CHANGELOG.md

> Reviewed 13 of 14 files at r1, 3 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2055#-:-NFO9Tfo155AP1Dv1tcK:b-41b8x1)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`examples/03-read-to-persistent/README.md` line 36 at r2](https://reviewable.io/reviews/pmem/rpma/2055#-NFOBseJDEr9dDD3bKiG:-NFOBseJDEr9dDD3bKiH:b-1kaoiu) ([raw file](https://github.com/pmem/rpma/blob/36c3c99354c2f1d0d3bf867c4527a101d04b5f35/examples/03-read-to-persistent/README.md#L36)):*
> ```Markdown
>   - a Device DAX (`/dev/dax0.0` for example) or
>   - a file on File System DAX (`/mnt/pmem/file` for example)
> and `<pmem-offset>` is an offset inside the above mentioned PMem device,
> ```

no coma



_Code quote:_
```Markdown
,
```
___
*[`examples/04-write-to-persistent/README.md` line 35 at r2](https://reviewable.io/reviews/pmem/rpma/2055#-NFOC0W0EG0-ugcdOrcI:-NFOC0W0EG0-ugcdOrcJ:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/36c3c99354c2f1d0d3bf867c4527a101d04b5f35/examples/04-write-to-persistent/README.md#L35)):*
> ```Markdown
>   - a Device DAX (`/dev/dax0.0` for example) or
>   - a file on File System DAX (`/mnt/pmem/file` for example)
> and `<pmem-offset>` is an offset inside the above mentioned PMem device,
> ```

.



_Code quote:_
```Markdown
,
```
___
*[`examples/05-flush-to-persistent/README.md` line 41 at r2](https://reviewable.io/reviews/pmem/rpma/2055#-NFOCJRM8qwb_GcmgzW-:-NFOCJRM8qwb_GcmgzW0:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/36c3c99354c2f1d0d3bf867c4527a101d04b5f35/examples/05-flush-to-persistent/README.md#L41)):*
> ```Markdown
>   - a Device DAX (`/dev/dax0.0` for example) or
>   - a file on File System DAX (`/mnt/pmem/file` for example)
> and `<pmem-offset>` is an offset inside the above mentioned PMem device,
> ```

.



_Code quote:_
```Markdown
,
```
___
*[`examples/09-flush-to-persistent-GPSPM/README.md` line 48 at r2](https://reviewable.io/reviews/pmem/rpma/2055#-NFOCd3l1Q76UCyfQSxI:-NFOCd3l1Q76UCyfQSxJ:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/36c3c99354c2f1d0d3bf867c4527a101d04b5f35/examples/09-flush-to-persistent-GPSPM/README.md#L48)):*
> ```Markdown
>   - a Device DAX (`/dev/dax0.0` for example) or
>   - a file on File System DAX (`/mnt/pmem/file` for example)
> and `<pmem-offset>` is an offset inside the above mentioned PMem device,
> ```

.



_Code quote:_
```Markdown
,
```
___
*[`examples/09scch-flush-to-persistent-GPSPM/README.md` line 53 at r2](https://reviewable.io/reviews/pmem/rpma/2055#-NFOChUB7lBXTfMH_glO:-NFOChUB7lBXTfMH_glP:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/36c3c99354c2f1d0d3bf867c4527a101d04b5f35/examples/09scch-flush-to-persistent-GPSPM/README.md#L53)):*
> ```Markdown
>   - a Device DAX (`/dev/dax0.0` for example) or
>   - a file on File System DAX (`/mnt/pmem/file` for example)
> and `<pmem-offset>` is an offset inside the above mentioned PMem device,
> ```

.



_Code quote:_
```Markdown
e,
```

**Review by ldorau — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2055#-:-NFOFO-B-Nz8OOgku4SJ:bb6un1j)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[`examples/03-read-to-persistent/README.md` line 36 at r2](https://reviewable.io/reviews/pmem/rpma/2055#-NFOBseJDEr9dDD3bKiG:-NFOEMrf8VxtG_UiAPtn:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/36c3c99354c2f1d0d3bf867c4527a101d04b5f35/examples/03-read-to-persistent/README.md#L36)):*
<details><summary><i>Previously, haichangsi (Kacper Stefanski) wrote…</i></summary><blockquote>

no coma
</blockquote></details>

Done.
___
*[`examples/04-write-to-persistent/README.md` line 35 at r2](https://reviewable.io/reviews/pmem/rpma/2055#-NFOC0W0EG0-ugcdOrcI:-NFOENcXDt5miiWVtdev:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/36c3c99354c2f1d0d3bf867c4527a101d04b5f35/examples/04-write-to-persistent/README.md#L35)):*
<details><summary><i>Previously, haichangsi (Kacper Stefanski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`examples/05-flush-to-persistent/README.md` line 41 at r2](https://reviewable.io/reviews/pmem/rpma/2055#-NFOCJRM8qwb_GcmgzW-:-NFOEOC154VbZynPSVZ5:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/36c3c99354c2f1d0d3bf867c4527a101d04b5f35/examples/05-flush-to-persistent/README.md#L41)):*
<details><summary><i>Previously, haichangsi (Kacper Stefanski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`examples/09-flush-to-persistent-GPSPM/README.md` line 48 at r2](https://reviewable.io/reviews/pmem/rpma/2055#-NFOCd3l1Q76UCyfQSxI:-NFOEOkw2p9UsWsnUp5W:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/36c3c99354c2f1d0d3bf867c4527a101d04b5f35/examples/09-flush-to-persistent-GPSPM/README.md#L48)):*
<details><summary><i>Previously, haichangsi (Kacper Stefanski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`examples/09scch-flush-to-persistent-GPSPM/README.md` line 53 at r2](https://reviewable.io/reviews/pmem/rpma/2055#-NFOChUB7lBXTfMH_glO:-NFOELbS6cxA7wCbo0k0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/36c3c99354c2f1d0d3bf867c4527a101d04b5f35/examples/09scch-flush-to-persistent-GPSPM/README.md#L53)):*
<details><summary><i>Previously, haichangsi (Kacper Stefanski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.



_Code quote:_
```Markdown
is an offset inside the above mentioned PMem device,
```

**Review by grom72 — APPROVED** [review]
> Reviewed 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2055)* status: all files reviewed, 5 unresolved discussions (waiting on @haichangsi)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2055)* status: all files reviewed, 5 unresolved discussions (waiting on @haichangsi)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2055#-:-NFOIJhD03baYFN3YkM6:bnfp4nl)* status: all files reviewed, 5 unresolved discussions (waiting on @haichangsi)

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2055)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`examples/09scch-flush-to-persistent-GPSPM/README.md` line 53 at r2](https://reviewable.io/reviews/pmem/rpma/2055#-NFOChUB7lBXTfMH_glO:-NFOJDC-4ETHtMMYypy4:bl0b7mn) ([raw file](https://github.com/pmem/rpma/blob/36c3c99354c2f1d0d3bf867c4527a101d04b5f35/examples/09scch-flush-to-persistent-GPSPM/README.md#L53)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

not yet here or maybe there is a problem with reviewable

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2055)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[`examples/09scch-flush-to-persistent-GPSPM/README.md` line 53 at r2](https://reviewable.io/reviews/pmem/rpma/2055#-NFOChUB7lBXTfMH_glO:-NFOJo4Z37BBT6PnghbA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/36c3c99354c2f1d0d3bf867c4527a101d04b5f35/examples/09scch-flush-to-persistent-GPSPM/README.md#L53)):*
<details><summary><i>Previously, haichangsi (Kacper Stefanski) wrote…</i></summary><blockquote>

not yet here or maybe there is a problem with reviewable 
</blockquote></details>

Done.

**Review by haichangsi — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 14 files at r1, 2 of 12 files at r2, 5 of 10 files at r3, 6 of 6 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2055#-:-NFONayM94KgmJdPr8VI:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
