### PR TITLE
doc: Improve the manual of rpma_cq_get_fd()

### PR DESCRIPTION
**Pull request by yangx-jy**
Ref: #1112

Signed-off-by: Xiao Yang <yangx.jy@fujitsu.com>

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1316)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1316)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @grom72 and @yangx-jy)

___
*[src/include/librpma.h, line 2795 at r2](https://reviewable.io/reviews/pmem/rpma/1316#-MnPnm1ABRLHmbGNfwxq:-MnPnm1ABRLHmbGNfwxr:b-zftgy4) ([raw file](https://github.com/pmem/rpma/blob/ce54213e65ca73d290c92936b4aaf4ad5f59b762/src/include/librpma.h#L2795)):*
> ```objc
>  *
>  * DESCRIPTION
>  * rpma_cq_get_fd() gets the completion file descriptor of the CQ. When
> ```

~~completion~~

In my opinion, "gets the file descriptor of the CQ" makes more sense and it is shorter and easier to comprehend.
___
*[src/include/librpma.h, line 2797 at r2](https://reviewable.io/reviews/pmem/rpma/1316#-MnPsfpc1ZMiz0NjyoC2:-MnPsfpc1ZMiz0NjyoC3:b-r0xos2) ([raw file](https://github.com/pmem/rpma/blob/ce54213e65ca73d290c92936b4aaf4ad5f59b762/src/include/librpma.h#L2797)):*
I do not like introducing another entity called a completion event. So far, it is covered by the librpma API and I don't think it has to be passed to the end-user e.g.

> When the next completion in the CQ is ready to consume (rpma_cq_get_completion(3)), the notification is delivered via the file descriptor.
___
*[src/include/librpma.h, line 2799 at r2](https://reviewable.io/reviews/pmem/rpma/1316#-MnPskGE8AWXTMur0ACZ:-MnPskGE8AWXTMur0AC_:b-uo5hp3) ([raw file](https://github.com/pmem/rpma/blob/ce54213e65ca73d290c92936b4aaf4ad5f59b762/src/include/librpma.h#L2799)):*
> ```objc
>  * a userspace process via the file descriptor associated with the CQ.
>  * The default mode of file descriptor is blocking and it can be changed
>  * to the non-blocking mode by fcntl(2). The CQ is either the connection's
> ```

The default mode of **the** file descriptor is blocking **but** it can be changed to **~~the~~** non-blocking mode **using** fcntl(2).
___
*[src/include/librpma.h, line 2802 at r2](https://reviewable.io/reviews/pmem/rpma/1316#-MnPt7fv9O8ozd6ySiVA:-MnPt7fv9O8ozd6ySiVB:b-bizjq3) ([raw file](https://github.com/pmem/rpma/blob/ce54213e65ca73d290c92936b4aaf4ad5f59b762/src/include/librpma.h#L2802)):*
I think it may be useful to add another paragraph:

> Note after spotting the notification using the provided file descriptor you do not have to call rpma_cq_wait(3) before consuming the completion but it may cause that the next call to rpma_cq_wait(3) will notify you of already consumed completion.
___
*[src/include/librpma.h, line 2814 at r2](https://reviewable.io/reviews/pmem/rpma/1316#-MnPt3FoArFH4-KuKXbw:-MnPt3FpEYrOmOGH2cFv:b-58p82g) ([raw file](https://github.com/pmem/rpma/blob/ce54213e65ca73d290c92936b4aaf4ad5f59b762/src/include/librpma.h#L2814)):*
> ```objc
>  * SEE ALSO
>  * rpma_conn_get_cq(3), rpma_conn_get_rcq(3), rpma_cq_wait(3),
>  * rpma_cq_get_completion(3), librpma(7) and https://pmem.io/rpma/
> ```

Please add fcntl(2).

**Review by yangx-jy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1316)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[src/include/librpma.h, line 2795 at r2](https://reviewable.io/reviews/pmem/rpma/1316#-MnPnm1ABRLHmbGNfwxq:-MnQOFNE7v53Z83mAQPj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ce54213e65ca73d290c92936b4aaf4ad5f59b762/src/include/librpma.h#L2795)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

~~completion~~

In my opinion, "gets the file descriptor of the CQ" makes more sense and it is shorter and easier to comprehend.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2797 at r2](https://reviewable.io/reviews/pmem/rpma/1316#-MnPsfpc1ZMiz0NjyoC2:-MnQOHXb7yujfc5h_KTD:bohocg8) ([raw file](https://github.com/pmem/rpma/blob/ce54213e65ca73d290c92936b4aaf4ad5f59b762/src/include/librpma.h#L2797)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I do not like introducing another entity called a completion event. So far, it is covered by the librpma API and I don't think it has to be passed to the end-user e.g.

> When the next completion in the CQ is ready to consume (rpma_cq_get_completion(3)), the notification is delivered via the file descriptor.
</blockquote></details>

Done. With a minor change: `is ready to be consumed by rpma_cq_get_completion(3)`
___
*[src/include/librpma.h, line 2799 at r2](https://reviewable.io/reviews/pmem/rpma/1316#-MnPskGE8AWXTMur0ACZ:-MnQOTBc-w0mqcttynul:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ce54213e65ca73d290c92936b4aaf4ad5f59b762/src/include/librpma.h#L2799)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The default mode of **the** file descriptor is blocking **but** it can be changed to **~~the~~** non-blocking mode **using** fcntl(2).
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2802 at r2](https://reviewable.io/reviews/pmem/rpma/1316#-MnPt7fv9O8ozd6ySiVA:-MnQOUwW71IwmSw-hugH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ce54213e65ca73d290c92936b4aaf4ad5f59b762/src/include/librpma.h#L2802)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think it may be useful to add another paragraph:

> Note after spotting the notification using the provided file descriptor you do not have to call rpma_cq_wait(3) before consuming the completion but it may cause that the next call to rpma_cq_wait(3) will notify you of already consumed completion.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2814 at r2](https://reviewable.io/reviews/pmem/rpma/1316#-MnPt3FoArFH4-KuKXbw:-MnQOVtU9bHb2ub7wysd:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ce54213e65ca73d290c92936b4aaf4ad5f59b762/src/include/librpma.h#L2814)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please add fcntl(2).
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1316)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)

___
*[src/include/librpma.h, line 2785 at r3](https://reviewable.io/reviews/pmem/rpma/1316#-MnQqr83CzrGl5WbA5v8:-MnQqr83CzrGl5WbA5v9:b1tcj8g) ([raw file](https://github.com/pmem/rpma/blob/2beb013411b4fb96daf3a061f8532fc301626c8a/src/include/librpma.h#L2785)):*
> ```
> get the completion file descriptor
> ```
get the completion queue's file descriptor

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1316)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @grom72, @janekmi, and @yangx-jy)

___
*[src/include/librpma.h, line 2795 at r3](https://reviewable.io/reviews/pmem/rpma/1316#-MnQrI-M9dELGnx6bBQI:-MnQrI-M9dELGnx6bBQJ:bxbexi8) ([raw file](https://github.com/pmem/rpma/blob/2beb013411b4fb96daf3a061f8532fc301626c8a/src/include/librpma.h#L2795)):*
> ```
> the CQ
> ```
the completion queue (CQ in short)

**Review by yangx-jy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1316)* status: 0 of 1 files reviewed, 8 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[src/include/librpma.h, line 2785 at r3](https://reviewable.io/reviews/pmem/rpma/1316#-MnQqr83CzrGl5WbA5v8:-MnTlbiv5nx36XL1lEjV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2beb013411b4fb96daf3a061f8532fc301626c8a/src/include/librpma.h#L2785)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> get the completion file descriptor
> ```
get the completion queue's file descriptor
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 2795 at r3](https://reviewable.io/reviews/pmem/rpma/1316#-MnQrI-M9dELGnx6bBQI:-MnTlezt3XLYIycjIYbt:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2beb013411b4fb96daf3a061f8532fc301626c8a/src/include/librpma.h#L2795)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> the CQ
> ```
the completion queue (CQ in short)
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1316)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @grom72 and @janekmi)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1316)* status: all files reviewed, 5 unresolved discussions (waiting on @janekmi)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1316)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[src/include/librpma.h, line 2798 at r4](https://reviewable.io/reviews/pmem/rpma/1316#-Mo8gTmTCUPCpj7GYUe4:-Mo8gDXj2xv6QK_lAAV3:b-f70s98) ([raw file](https://github.com/pmem/rpma/blob/bf7159f2169eddfdb4f81ced4c4748b723562e3b/src/include/librpma.h#L2798)):*
> ```objc
>  * in short). When a next completion in the CQ is ready to be consumed by
>  * rpma_cq_get_completion(3), the notification is delivered to a userspace
>  * process via the file descriptor. The default mode of the file descriptor
> ```

I don't like the "a userspace process" part. For me, the whole header is for the userspace level programming. Why do you think it should be stated here explicitly?

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1316)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72, @janekmi, and @yangx-jy)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1316#-:-MoYkN_X6CVqF0WMf8Zj:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1316)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1316#-:-MoYvaK89MhCDshTuUDM:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Pull request merged**
