### PR TITLE
test: add rpma_conn_cfg_set_timeout multithreaded test

### PR DESCRIPTION
**Pull request by ewanglong**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1064)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1064)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1064#-MaFAgoT0K7ygFbV4riP:-MaFAgoT0K7ygFbV4riQ:br7hkvx) ([raw file](https://github.com/pmem/rpma/blob/d3a1be583959aadfdceda776c96aede2811f0a52/tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c#L13)):*
> ```C
> #include "mtt.h"
> 
> #define MTT_CONN_CFG_TIMEOUT_MS 2000
> ```

TIMEOUT_MS_EXP

It is not a part of the framework. `MTT_` prefix is reserved.
___
*[tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/1064#-MaF9sZL5tJc2tgp02xj:-MaF9sZL5tJc2tgp02xk:b-s3bbgf) ([raw file](https://github.com/pmem/rpma/blob/d3a1be583959aadfdceda776c96aede2811f0a52/tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c#L20)):*
> ```C
> 
> /*
>  * init -- allocate state and creates a new connection configuration object
> ```

create
___
*[tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c, line 44 at r1](https://reviewable.io/reviews/pmem/rpma/1064#-MaFAJu84R-snDqK94PC:-MaFAJu84R-snDqK94PD:b-vgynvd) ([raw file](https://github.com/pmem/rpma/blob/d3a1be583959aadfdceda776c96aede2811f0a52/tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c#L44)):*
> ```C
> /*
>  * thread -- set connection establishment timeout
>  * and check if its value is expected
> ```

... is as expected
___
*[tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c, line 65 at r1](https://reviewable.io/reviews/pmem/rpma/1064#-MaFAWCD0g7dfhd50aip:-MaFAWCD0g7dfhd50aiq:b-vcapht) ([raw file](https://github.com/pmem/rpma/blob/d3a1be583959aadfdceda776c96aede2811f0a52/tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c#L65)):*
> ```C
> 
> 	if (timeout_ms != MTT_CONN_CFG_TIMEOUT_MS)
> 		MTT_ERR(tr, "rpma_conn_cfg_get_timeout got an unexpected value",
> ```

`"timeout_ms != TIMEOUT_MS_EXP"`

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1064)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c, line 13 at r1](https://reviewable.io/reviews/pmem/rpma/1064#-MaFAgoT0K7ygFbV4riP:-MaRUfHZ2rlHUu8I942h:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d3a1be583959aadfdceda776c96aede2811f0a52/tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c#L13)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

TIMEOUT_MS_EXP

It is not a part of the framework. `MTT_` prefix is reserved.
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c, line 20 at r1](https://reviewable.io/reviews/pmem/rpma/1064#-MaF9sZL5tJc2tgp02xj:-MaRUgQfDpwv6ILkrhiz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d3a1be583959aadfdceda776c96aede2811f0a52/tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c#L20)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

create
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c, line 44 at r1](https://reviewable.io/reviews/pmem/rpma/1064#-MaFAJu84R-snDqK94PC:-MaRUh610N8d0J4oexCm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d3a1be583959aadfdceda776c96aede2811f0a52/tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c#L44)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

... is as expected
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c, line 65 at r1](https://reviewable.io/reviews/pmem/rpma/1064#-MaFAWCD0g7dfhd50aip:-MaRV12LAWu9mOE9xKzh:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d3a1be583959aadfdceda776c96aede2811f0a52/tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c#L65)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`"timeout_ms != TIMEOUT_MS_EXP"`
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1064)* status: all files reviewed, 3 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c, line 45 at r2](https://reviewable.io/reviews/pmem/rpma/1064#-MamSg3g6YIZt7wQVYtH:-MamSg3g6YIZt7wQVYtI:bwovfu5) ([raw file](https://github.com/pmem/rpma/blob/c3095248b7142153a2d2d262ffbf09306a64b9ef/tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c#L45)):*
> ```C
>  * thread -- set connection establishment timeout
>  * and check if its value is as expected
>  */
> ```

The line is wrapped too early:

```
/*
 * thread -- set connection establishment timeout and check if its value is
 * as expected
 */
```
___
*[tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c, line 53 at r2](https://reviewable.io/reviews/pmem/rpma/1064#-MamSRgE1SabnG36DwDP:-MamSRgE1SabnG36DwDQ:b-e0ad70) ([raw file](https://github.com/pmem/rpma/blob/c3095248b7142153a2d2d262ffbf09306a64b9ef/tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c#L53)):*
> ```C
> 
> 	if ((ret = rpma_conn_cfg_set_timeout(st->cfg_ptr,
> 				TIMEOUT_MS_EXP))) {
> ```

This line does not have to be wrapped.
___
*[tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c, line 59 at r2](https://reviewable.io/reviews/pmem/rpma/1064#-MamSUAyCQuk9XJeu_un:-MamSUAyCQuk9XJeu_uo:b-e0ad70) ([raw file](https://github.com/pmem/rpma/blob/c3095248b7142153a2d2d262ffbf09306a64b9ef/tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c#L59)):*
> ```C
> 
> 	if ((ret = rpma_conn_cfg_get_timeout(st->cfg_ptr,
> 				&timeout_ms))) {
> ```

This line does not have to be wrapped.

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1064)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c, line 45 at r2](https://reviewable.io/reviews/pmem/rpma/1064#-MamSg3g6YIZt7wQVYtH:-Mb4QUDH4qZCCY8JKwc6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c3095248b7142153a2d2d262ffbf09306a64b9ef/tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c#L45)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The line is wrapped too early:

```
/*
 * thread -- set connection establishment timeout and check if its value is
 * as expected
 */
```
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c, line 53 at r2](https://reviewable.io/reviews/pmem/rpma/1064#-MamSRgE1SabnG36DwDP:-Mb4YjxL5b8C0w92UexD:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c3095248b7142153a2d2d262ffbf09306a64b9ef/tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c#L53)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This line does not have to be wrapped.
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c, line 59 at r2](https://reviewable.io/reviews/pmem/rpma/1064#-MamSUAyCQuk9XJeu_un:-Mb4YkrlBWQqHSLW82QQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c3095248b7142153a2d2d262ffbf09306a64b9ef/tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c#L59)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This line does not have to be wrapped.
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1064)* status: 1 of 2 files reviewed, 6 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c, line 24 at r3](https://reviewable.io/reviews/pmem/rpma/1064#-Mb5UuhL2j94j65ljAX0:-Mb5UuhL2j94j65ljAX1:b-ax49sb) ([raw file](https://github.com/pmem/rpma/blob/9e9253920116538247ca6a66c2875a4f07ad016f/tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c#L24)):*
> ```C
> void
> init(unsigned id, void *prestate, void **state_ptr,
> 		struct mtt_result *tr)
> ```

One line is enough.
___
*[tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c, line 52 at r3](https://reviewable.io/reviews/pmem/rpma/1064#-Mb5VEPTADzhUy4QVYZP:-Mb5VEPTADzhUy4QVYZQ:b16f8lo) ([raw file](https://github.com/pmem/rpma/blob/9e9253920116538247ca6a66c2875a4f07ad016f/tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c#L52)):*
> ```C
> 	int ret, timeout_ms;
> 
> 	ret = rpma_conn_cfg_set_timeout(st->cfg_ptr, TIMEOUT_MS_EXP);
> ```

if ((ret = ... )
As above.
___
*[tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c, line 58 at r3](https://reviewable.io/reviews/pmem/rpma/1064#-Mb5VMUF2oA21kAv6RWJ:-Mb5VMUF2oA21kAv6RWK:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/9e9253920116538247ca6a66c2875a4f07ad016f/tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c#L58)):*
> ```C
> 	}
> 
> 	ret = rpma_conn_cfg_get_timeout(st->cfg_ptr, &timeout_ms);
> ```

.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1064)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1064#-Mb6zYHWDgfqHaU0aFlP:-Mb6zYHWDgfqHaU0aFlQ:bf5ldmx) (no related file):*
Build failed: https://app.circleci.com/pipelines/github/pmem/rpma/194/workflows/74f049b3-b477-4ccc-8d1d-82883a9fed66/jobs/199

---

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1064)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1064#-Mb6zYHWDgfqHaU0aFlP:-MbBH7u21odzqo5_Yd6x:bo45qdm) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Build failed: https://app.circleci.com/pipelines/github/pmem/rpma/194/workflows/74f049b3-b477-4ccc-8d1d-82883a9fed66/jobs/199
</blockquote></details>

Another unit test (`multithreaded-conn-rpma_conn_get_private_data_0_none`) failed in this build.
It is probably caused by an issue in the MT-framework with synchronization between server's and client's processes.

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1064)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1064#-Mb6zYHWDgfqHaU0aFlP:-MbBJ3rc231NhSnCyh7L:bqgymeu) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Another unit test (`multithreaded-conn-rpma_conn_get_private_data_0_none`) failed in this build.
It is probably caused by an issue in the MT-framework with synchronization between server's and client's processes.
</blockquote></details>

I have submitted an issue for that: https://github.com/pmem/rpma/issues/1079

---

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1064)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c, line 24 at r3](https://reviewable.io/reviews/pmem/rpma/1064#-Mb5UuhL2j94j65ljAX0:-MbBMsM7BBtgDzjEZc2P:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9e9253920116538247ca6a66c2875a4f07ad016f/tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c#L24)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

One line is enough.
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c, line 52 at r3](https://reviewable.io/reviews/pmem/rpma/1064#-Mb5VEPTADzhUy4QVYZP:-MbBpqbc33WPWGUWtUoG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9e9253920116538247ca6a66c2875a4f07ad016f/tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c#L52)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

if ((ret = ... )
As above.
</blockquote></details>

Done.
___
*[tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c, line 58 at r3](https://reviewable.io/reviews/pmem/rpma/1064#-Mb5VMUF2oA21kAv6RWJ:-MbBprcb9qLPEhM5m_ka:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/9e9253920116538247ca6a66c2875a4f07ad016f/tests/multithreaded/conn/rpma_conn_cfg_set_timeout.c#L58)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1064)* status: all files reviewed, 5 unresolved discussions (waiting on @ewanglong, @janekmi, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1064#-MbBqkSpAbNh-iQMwJQo:-MbBqkSpAbNh-iQMwJQp:b-8lnxmu) (no related file):*
Please rebase (conflict)

---

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1064)* status: 1 of 2 files reviewed, 5 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1064#-MbBqkSpAbNh-iQMwJQo:-MbEe7ky4Ysyz9cZvqRC:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please rebase (conflict)
</blockquote></details>

Done.

---

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1064#-:-MbKMVBpAsAXmgICbvLu:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1064#-Mb6zYHWDgfqHaU0aFlP:-MbKMFqcB4xsl_ECVrBb:btu5ovg) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I have submitted an issue for that: https://github.com/pmem/rpma/issues/1079
</blockquote></details>

@janekmi ... so this issue can be resolved

---

**Review by ldorau — APPROVED** [review]
@janekmi @osalyk please resolve your issues

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1064#-:-MbKP6EvBbEKyBNv6a0i:b9qrk72)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi and @osalyk)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1064#-:-MbKUr_B0qC80uFbDsVp:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1064)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1064#-:-MbKwZW72CGYD73_WnW2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Pull request merged**
