### PR TITLE
test: mt: give all init/fini steps the same args set

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/999)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/999)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/999#-MYImQzU8FnhrwKANxgT:-MYImQzU8FnhrwKANxgU:bd8ddct) (no related file):*
What is the purpose of having mtt_thread_result in seq_ini/fini?

---
___
*[tests/multithreaded/common/mtt.c, line 40 at r1](https://reviewable.io/reviews/pmem/rpma/999#-MYIm7zpBSLArCrwM3pe:-MYIm7zq9uj4ZXi8HUbZ:b-5d1zrb) ([raw file](https://github.com/pmem/rpma/blob/a8b6670b1f9838bcc0fa0d623cb223cabb249ddf/tests/multithreaded/common/mtt.c#L40)):*
> ```
> ta, tr
> ```
thread_arg, thread_result

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/999)* status: 1 of 2 files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/common/mtt.c, line 263 at r1](https://reviewable.io/reviews/pmem/rpma/999#-MYIntoDDr9-iB-S1PsO:-MYIntoDDr9-iB-S1PsP:b-kdii6z) ([raw file](https://github.com/pmem/rpma/blob/a8b6670b1f9838bcc0fa0d623cb223cabb249ddf/tests/multithreaded/common/mtt.c#L263)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 			if (ta->ret.ret) {
> 				result = ta->ret.ret;
> 				MT_TEST_ERR(ta->id, "%s", ta->ret.errmsg);
> 				goto err_fini_threads_args;
> 			}
> ```
</details>

how is it related to "same args set"?
___
*[tests/multithreaded/common/mtt.c, line 323 at r1](https://reviewable.io/reviews/pmem/rpma/999#-MYIo1dY8LTo7NKh07Nr:-MYIo1dY8LTo7NKh07Ns:bmex9p8) ([raw file](https://github.com/pmem/rpma/blob/a8b6670b1f9838bcc0fa0d623cb223cabb249ddf/tests/multithreaded/common/mtt.c#L323)):*
<details><summary><i alt="summary">Quoted 5 lines of code…</i></summary>

> ```
> 			if (tr_fini.ret) {
> 				MT_TEST_ERR(i, "%s", tr_fini.errmsg);
> 				result = tr_fini.ret;
> 				tr_fini.ret = 0;
> 			}
> ```
</details>

.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/999)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/999)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/999#-MYImQzU8FnhrwKANxgT:-MYJglUiC6Nz0hAsp0Ca:b-muiu82) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

What is the purpose of having mtt_thread_result in seq_ini/fini?
</blockquote></details>

This way all steps have a common way of reporting issues.
Maybe it should be renamed into mtt_result because it is no longer thread-only. :thinking: 

---
___
*[tests/multithreaded/common/mtt.c, line 263 at r1](https://reviewable.io/reviews/pmem/rpma/999#-MYIntoDDr9-iB-S1PsO:-MYJhBFNC4NcWdu52ruv:b-2oh6io) ([raw file](https://github.com/pmem/rpma/blob/a8b6670b1f9838bcc0fa0d623cb223cabb249ddf/tests/multithreaded/common/mtt.c#L263)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> 			if (ta->ret.ret) {
> 				result = ta->ret.ret;
> 				MT_TEST_ERR(ta->id, "%s", ta->ret.errmsg);
> 				goto err_fini_threads_args;
> 			}
> ```
how is it related to "same args set"?
</blockquote></details>

Having the same args set we can report the issue which may have happened and the error message may be out there so no point in not using it.
___
*[tests/multithreaded/common/mtt.c, line 323 at r1](https://reviewable.io/reviews/pmem/rpma/999#-MYIo1dY8LTo7NKh07Nr:-MYJhW4Q0BtaKlUd13qO:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/a8b6670b1f9838bcc0fa0d623cb223cabb249ddf/tests/multithreaded/common/mtt.c#L323)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> 			if (tr_fini.ret) {
> 				MT_TEST_ERR(i, "%s", tr_fini.errmsg);
> 				result = tr_fini.ret;
> 				tr_fini.ret = 0;
> 			}
> ```
.
</blockquote></details>

.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/999)* status: 0 of 3 files reviewed, 4 unresolved discussions (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/999#-MYImQzU8FnhrwKANxgT:-MYJpPAiEgSuAjOhtvMj:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This way all steps have a common way of reporting issues.
Maybe it should be renamed into mtt_result because it is no longer thread-only. :thinking: 
</blockquote></details>

Done.

---

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/999#-:-MYKB26o4YHu4V4h0b_1:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/999)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tests/multithreaded/common/mtt.h, line 45 at r2](https://reviewable.io/reviews/pmem/rpma/999#-MYKGasv83_cVNJPMCN1:-MYKGasv83_cVNJPMCN2:bueef4z) ([raw file](https://github.com/pmem/rpma/blob/b45a508874533901c071444d557fc61d1f769c6f/tests/multithreaded/common/mtt.h#L45)):*
> ```
> typedef void
> ```
documentation is missing
It is important to understand how prestate, state_ptr, results are flowing between _seq_init, init, _finit, _seq_finit

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/999)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tests/multithreaded/common/mtt.h, line 45 at r2](https://reviewable.io/reviews/pmem/rpma/999#-MYKGasv83_cVNJPMCN1:-MYKT7pSAaohfThNyFVY:b-o5d34d) ([raw file](https://github.com/pmem/rpma/blob/b45a508874533901c071444d557fc61d1f769c6f/tests/multithreaded/common/mtt.h#L45)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> typedef void
> ```
documentation is missing
It is important to understand how prestate, state_ptr, results are flowing between _seq_init, init, _finit, _seq_finit
</blockquote></details>

Yes. Documentation is important. It is partially addressed by the example. After the example, we might still need more documentation. Nonetheless, it is not part of this PR.

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/999)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Comment by janekmi** [comment]
Incorporated into #1003.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/999#-:-MYrymlU8Nr5vuppbS_3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request closed without merging**
