### PR TITLE
rpma: enhance rpma_mr_advise() implementation

### PR DESCRIPTION
**Pull request by ewanglong**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1294)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1294)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

___
*[src/mr.c, line 536 at r1](https://reviewable.io/reviews/pmem/rpma/1294#-MkGudqG0T0W4GDciJh7:-MkGudqG0T0W4GDciJh8:b-5g81kw) ([raw file](https://github.com/pmem/rpma/blob/89d6047998020e3aa5729e31e6abb4447be44e7b/src/mr.c#L536)):*
> ```C
> 			return RPMA_E_INVAL;
> 		else
> 			return RPMA_E_PROVIDER;
> ```

Yes. This is what I meant. Please update also doc and tests.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1294)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1294)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1294)* status: 1 of 3 files reviewed, 1 unresolved discussion (waiting on @grom72, @janekmi, and @ldorau)

___
*[src/mr.c, line 536 at r1](https://reviewable.io/reviews/pmem/rpma/1294#-MkGudqG0T0W4GDciJh7:-MkH-QyzAaBkOxxhWx17:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/89d6047998020e3aa5729e31e6abb4447be44e7b/src/mr.c#L536)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Yes. This is what I meant. Please update also doc and tests.
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1294)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong)

___
*[src/include/librpma.h, line 1173 at r2](https://reviewable.io/reviews/pmem/rpma/1294#-MkH4exW04nKuGsQISbK:-MkH4exW04nKuGsQISbL:b-wk1krd) ([raw file](https://github.com/pmem/rpma/blob/2f1a9cd73f8dc0de37489019db0ea91978911ff4/src/include/librpma.h#L1173)):*
> ```objc
>  * rpma_mr_advise() can fail with the following errors:
>  *
>  * - RPMA_E_INVAL - system returned EFAULT or EINVAL
> ```

```
 * - RPMA_E_INVAL - in one of the following:
 *     - the requested range is out of the memory registration bounds
 *     - the memory registration usage does not allow the specific advice
 *     - the flags are invalid
``` 
___
*[src/include/librpma.h, line 1175 at r2](https://reviewable.io/reviews/pmem/rpma/1294#-MkH4VhX7oJ6VCYBhToR:-MkH4VhX7oJ6VCYBhToS:bafyb5v) ([raw file](https://github.com/pmem/rpma/blob/2f1a9cd73f8dc0de37489019db0ea91978911ff4/src/include/librpma.h#L1175)):*
> ```objc
>  * - RPMA_E_INVAL - system returned EFAULT or EINVAL
>  * - RPMA_E_NOSUPP - the operation is not supported by the system
>  * - RPMA_E_PROVIDER - rpma_mr_advise() failed for other errors
> ```

ibv_mr_advise(3)
___
*[tests/unit/mr/mr-advise.c, line 38 at r2](https://reviewable.io/reviews/pmem/rpma/1294#-MkH5gIQEG8n1LbGvCkw:-MkH5gIQEG8n1LbGvCkx:bf0ww35) ([raw file](https://github.com/pmem/rpma/blob/2f1a9cd73f8dc0de37489019db0ea91978911ff4/tests/unit/mr/mr-advise.c#L38)):*
> ```C
> 	expect_value(ibv_advise_mr_mock, sg_list->length, MOCK_LEN);
> 	expect_value(ibv_advise_mr_mock, num_sge, 1);
> 	will_return(ibv_advise_mr_mock, EOPNOTSUPP);
> ```

We have to cover both EOPNOTSUPP and ENOTSUP.
You can do this in a loop I think.
___
*[tests/unit/mr/mr-advise.c, line 68 at r2](https://reviewable.io/reviews/pmem/rpma/1294#-MkH5poU2LXYLE5F_orn:-MkH5poU2LXYLE5F_oro:b-k31g1u) ([raw file](https://github.com/pmem/rpma/blob/2f1a9cd73f8dc0de37489019db0ea91978911ff4/tests/unit/mr/mr-advise.c#L68)):*
> ```C
> 	expect_value(ibv_advise_mr_mock, sg_list->length, MOCK_LEN);
> 	expect_value(ibv_advise_mr_mock, num_sge, 1);
> 	will_return(ibv_advise_mr_mock, EINVAL);
> ```

.
EFAULT

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1294)* status: all files reviewed, 4 unresolved discussions (waiting on @ewanglong)

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1294)* status: 1 of 3 files reviewed, 4 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[src/include/librpma.h, line 1173 at r2](https://reviewable.io/reviews/pmem/rpma/1294#-MkH4exW04nKuGsQISbK:-MkHsWFODLgrqEuN08B0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2f1a9cd73f8dc0de37489019db0ea91978911ff4/src/include/librpma.h#L1173)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```
 * - RPMA_E_INVAL - in one of the following:
 *     - the requested range is out of the memory registration bounds
 *     - the memory registration usage does not allow the specific advice
 *     - the flags are invalid
``` 
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1175 at r2](https://reviewable.io/reviews/pmem/rpma/1294#-MkH4VhX7oJ6VCYBhToR:-MkHsX4-EHvd5QD2P3vz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2f1a9cd73f8dc0de37489019db0ea91978911ff4/src/include/librpma.h#L1175)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

ibv_mr_advise(3)
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-advise.c, line 38 at r2](https://reviewable.io/reviews/pmem/rpma/1294#-MkH5gIQEG8n1LbGvCkw:-MkHsXwJBsuAxvlYYwz7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2f1a9cd73f8dc0de37489019db0ea91978911ff4/tests/unit/mr/mr-advise.c#L38)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

We have to cover both EOPNOTSUPP and ENOTSUP.
You can do this in a loop I think.
</blockquote></details>

Done.
___
*[tests/unit/mr/mr-advise.c, line 68 at r2](https://reviewable.io/reviews/pmem/rpma/1294#-MkH5poU2LXYLE5F_orn:-MkHsYcv24hHUpMLpCkc:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2f1a9cd73f8dc0de37489019db0ea91978911ff4/tests/unit/mr/mr-advise.c#L68)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
EFAULT
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1294)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong)

___
*[src/include/librpma.h, line 1175 at r2](https://reviewable.io/reviews/pmem/rpma/1294#-MkH4VhX7oJ6VCYBhToR:-MkLkC4E5QobDtnKnQ_V:b-3losnt) ([raw file](https://github.com/pmem/rpma/blob/2f1a9cd73f8dc0de37489019db0ea91978911ff4/src/include/librpma.h#L1175)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nope. Please redo.
___
*[src/include/librpma.h, line 1181 at r3](https://reviewable.io/reviews/pmem/rpma/1294#-MkLkP8H0gd8awAbOM6b:-MkLkP8H0gd8awAbOM6c:bqpwicy) ([raw file](https://github.com/pmem/rpma/blob/ba1816dddd5e0e17e2909178027ddc795eb67c62/src/include/librpma.h#L1181)):*
> ```objc
>  *
>  * SEE ALSO
>  * rpma_mr_advise(3), librpma(7) and https://pmem.io/rpma/
> ```

I think we need here:
- rpma_mr_reg(3)
- ibv_mr_advise(3)
- librpma(7)
- pmem.io URL

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1294)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[src/include/librpma.h, line 1175 at r2](https://reviewable.io/reviews/pmem/rpma/1294#-MkH4VhX7oJ6VCYBhToR:-MkLpAX4-T-AmlZn5937:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2f1a9cd73f8dc0de37489019db0ea91978911ff4/src/include/librpma.h#L1175)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Nope. Please redo.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1181 at r3](https://reviewable.io/reviews/pmem/rpma/1294#-MkLkP8H0gd8awAbOM6b:-MkLpEXN8CIvPcBo_c_D:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ba1816dddd5e0e17e2909178027ddc795eb67c62/src/include/librpma.h#L1181)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I think we need here:
- rpma_mr_reg(3)
- ibv_mr_advise(3)
- librpma(7)
- pmem.io URL
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1183 at r3](https://reviewable.io/reviews/pmem/rpma/1294#-MkLp9U34DH4fEKkwmEq:-MkLp9U34DH4fEKkwmEr:b-8bhfw6) ([raw file](https://github.com/pmem/rpma/blob/ba1816dddd5e0e17e2909178027ddc795eb67c62/src/include/librpma.h#L1183)):*
> rpma_mr_reg

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1294#-:-MkLqJp4AT2CRyKAZ6eR:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72, @janekmi, and @ldorau)

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 2 files at r3, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1294)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

___
*[src/include/librpma.h, line 1183 at r3](https://reviewable.io/reviews/pmem/rpma/1294#-MkLp9U34DH4fEKkwmEq:-MkN06PtCEAJNoWv0tvb:b3kre) ([raw file](https://github.com/pmem/rpma/blob/ba1816dddd5e0e17e2909178027ddc795eb67c62/src/include/librpma.h#L1183)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

> rpma_mr_reg
</blockquote></details>

?

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1294#-:-MkN0sG779HK0SERzJhI:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ewanglong)

**Pull request merged**
