### PR TITLE
test: mt: clean up error handling

### PR DESCRIPTION
**Pull request by janekmi**
- rename MTT-API macros:
	- MTT_THREAD_ERR -> MTT_ERR
	- MTT_THREAD_RPMA_ERR -> MTT_RPMA_ERR
- rename internal MTT error helpers:
	- MTT_ERR -> MTT_INTERNAL_ERR
	- MT_TEST_ERR -> MTT_TEST_ERR (fix)
- add to the error messages: file name, line, and function
	- MTT_ERR, MTT_RPMA_ERR
	
An error message after this change will look as follow:

```
[thread #31] rpma_utils_get_ibv_context.c:33 thread() -> rpma_utils_get_ibv_context() failed: Unknown error
```

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1003)

### CODE REVIEW

**Review by ldorau — APPROVED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1003)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1003#-:-MYKB_j5EBwqNyJwRGFa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1003)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tests/multithreaded/common/mtt.h, line 33 at r1](https://reviewable.io/reviews/pmem/rpma/1003#-MYKCuPQ9iA9yRhYaYuh:-MYKCuPR6I2Mlw1hLB57:b-lp483j) ([raw file](https://github.com/pmem/rpma/blob/dcbee163b0ea03bb6980086edb3b287923dd32d8/tests/multithreaded/common/mtt.h#L33)):*
> ```
> static inline void
> mtt_err(...
> ```
with the inline function, we lose the possibility to extend it later to add file and line number.
Do we expect to have line/filename in the future?

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1003)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1003)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[tests/multithreaded/common/mtt.h, line 33 at r1](https://reviewable.io/reviews/pmem/rpma/1003#-MYKCuPQ9iA9yRhYaYuh:-MYKgg2x2ciyrqIQxPbj:b-e7cdyr) ([raw file](https://github.com/pmem/rpma/blob/dcbee163b0ea03bb6980086edb3b287923dd32d8/tests/multithreaded/common/mtt.h#L33)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> static inline void
> mtt_err(...
> ```
with the inline function, we lose the possibility to extend it later to add file and line number.
Do we expect to have line/filename in the future?
</blockquote></details>

Yeah... forgot about that. Done.
___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 21 at r2](https://reviewable.io/reviews/pmem/rpma/1003#-MYKh--M9e_OMu4_drQg:-MYKh--M9e_OMu4_drQh:bozcg4v) ([raw file](https://github.com/pmem/rpma/blob/3b9f90f65d7bf8cfb8702934fa0f9d8bdbf25a0a/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L21)):*
> ```C
>  */
> static void
> thread(unsigned id, void *prestate, void *state,
> ```

FYI: I have dropped the prefix because the file name is attached to the error log so no point in having additionally a prefix.

**Review by ldorau — APPROVED** [review]
still :lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1003#-:-MYKmq1c5w0SxLrm2KR_:b-5fsfav)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1003#-:-MYLGZTk2LR_sfcur-FY:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 21 at r2](https://reviewable.io/reviews/pmem/rpma/1003#-MYKh--M9e_OMu4_drQg:-MYLGS5I7t4b7diKA2bR:b-12ov7u) ([raw file](https://github.com/pmem/rpma/blob/3b9f90f65d7bf8cfb8702934fa0f9d8bdbf25a0a/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L21)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

FYI: I have dropped the prefix because the file name is attached to the error log so no point in having additionally a prefix.
</blockquote></details>

Shall we introduce a test name/title?

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1003)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1003)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 21 at r2](https://reviewable.io/reviews/pmem/rpma/1003#-MYKh--M9e_OMu4_drQg:-MYOPhHq9v7giRxoik3e:b-9obdt3) ([raw file](https://github.com/pmem/rpma/blob/3b9f90f65d7bf8cfb8702934fa0f9d8bdbf25a0a/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L21)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Shall we introduce a test name/title?
</blockquote></details>

I think it has to come up in practice. At this point, it seems redundant.

**Pull request merged**
