### PR TITLE
common: add BUILD_FORCE_ODP_NOT_SUPPORTED option and a relevant test

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/2122)

### CODE REVIEW

**Review by grom72 — APPROVED** [review]
:goat: 

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2122#-:-NQQAd0C3brug9jpAvKA:bdycpsm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Comment by yangx-jy** [comment]
Please reference the design of `BUILD_FORCE_NATIVE_FLUSH_NOT_SUPPORTED` option added by the following URL.
https://github.com/pmem/rpma/pull/2104/commits/eaf7fb5ebc40243b7c7421659b43630390ef4a37

By the way, `BUILD_FORCE_ODP_NOT_SUPPORTED=ON` should disable `ON_DEMAND_PAGING_SUPPORTED` for both CC and cmake.

**Review by ldorau — COMMENTED** [review]
Yes, I missed that `ON_DEMAND_PAGING_SUPPORTED` adds the `ibv_context_is_odp_capable` unit test.
Fixed.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2122#-:-NQU5P0a1Jqgk4nHZG4a:b-us9imq)* status: 1 of 4 files reviewed, all discussions resolved (waiting on @grom72)

**Review by yangx-jy — COMMENTED** [review]
With your update, #2123 can fix the compiler error which is reproduced now. 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2122#-:-NQU6uWcCGuG-NSJZfZz:bdfqelx)* status: 1 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[`CMakeLists.txt` line 149 at r3](https://reviewable.io/reviews/pmem/rpma/2122#-NQU7N_UApoNQkgpSpHS:-NQU7N_UApoNQkgpSpHT:bsliyyj) ([raw file](https://github.com/pmem/rpma/blob/c4500a83020d71c71ff921dd397246e1c418ada8/CMakeLists.txt#L149)):*
> ```CMake
> 	if(BUILD_FORCE_ODP_NOT_SUPPORTED)
> 		message(WARNING "On-Demand Paging (ODP) support in libibverbs is disabled by the BUILD_FORCE_ODP_NOT_SUPPORTED option!")
> 		set(ON_DEMAND_PAGING_SUPPORTED 0)
> ```

How about moving `if(BUILD_FORCE_ODP_NOT_SUPPORTED)` to the front of `is_ODP_supported(ON_DEMAND_PAGING_SUPPORTED)`? In this way, you don't need to set ON_DEMAND_PAGING_SUPPORTED to 0.

**Review by grom72 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2122)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2122)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @grom72 and @yangx-jy)

___
*[`CMakeLists.txt` line 149 at r3](https://reviewable.io/reviews/pmem/rpma/2122#-NQU7N_UApoNQkgpSpHS:-NQU9Bt2DjiErTLrPeLL:bk2lmxo) ([raw file](https://github.com/pmem/rpma/blob/c4500a83020d71c71ff921dd397246e1c418ada8/CMakeLists.txt#L149)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

How about moving `if(BUILD_FORCE_ODP_NOT_SUPPORTED)` to the front of `is_ODP_supported(ON_DEMAND_PAGING_SUPPORTED)`? In this way, you don't need to set ON_DEMAND_PAGING_SUPPORTED to 0.
</blockquote></details>

Yes, it will be even better. Done

**Review by ldorau — COMMENTED** [review]
Yes, it is a good fix. 

@yangx-jy Can I incorporate your fix into this PR?

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2122#-:-NQUC0CyDFipMhhZVyf_:b-a221xd)* status: 0 of 5 files reviewed, 1 unresolved discussion (waiting on @grom72 and @yangx-jy)

**Review by yangx-jy — COMMENTED** [review]
Sure. It's ok to me.
:lgtm:

> Reviewed 1 of 5 files at r5, 4 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2122#-:-NQUC_lo6Lm2Hw5CDUZV:bej2ry0)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Comment by ldorau** [comment]
@yangx-jy Thanks for the fix! :-)

**Pull request merged**
