### PR TITLE
examples: do not wait additional 1 sec for running server

### PR DESCRIPTION
**Pull request by ldorau**
Do not wait additional 1 sec for running server.
This will reduce duration of the integration test by
1008 seconds what is about 17 minutes.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1821)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1821)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1821)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1821)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1821)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

___
*[`examples/run-all-examples.sh` line 263 at r1](https://reviewable.io/reviews/pmem/rpma/1821#-N47nGCB0xr5dODHHA7z:-N48ROBJ62rBuiVR5lw0:b32w0x) ([raw file](https://github.com/pmem/rpma/blob/f650f1e073ae9732c6c887d5922b5f332d28fcab/examples/run-all-examples.sh#L263)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

OK

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1821#-:-N4BDYOzDoJKhBGUQfKE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
