### PR TITLE
tools: add option to run aof workloads in report_bench.sh

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/931)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/931)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/report_bench.sh, line 16 at r1](https://reviewable.io/reviews/pmem/rpma/931#-MVWZtOw4RHxiIfF31OF:-MVWZtOx9fXuDVvbJRX0:b-5jihg5) ([raw file](https://github.com/pmem/rpma/blob/e18cd53cde21ee6d57d763a10be1f3bed072bcee/tools/perf/report_bench.sh#L16)):*
> ```Shell
> 	echo "Error: $1"
> 	echo
> 	echo "Usage: $0 <server_ip> <avg|asvah>"
> ```

'avg' is unfortunate. It is a common abbreviation for 'average'.
___
*[tools/perf/report_bench.sh, line 109 at r1](https://reviewable.io/reviews/pmem/rpma/931#-MVW_M6A2yAZe3vcW4K1:-MVW_M6A2yAZe3vcW4K2:b2yeccu) ([raw file](https://github.com/pmem/rpma/blob/e18cd53cde21ee6d57d763a10be1f3bed072bcee/tools/perf/report_bench.sh#L109)):*
> ```Shell
> 	done
> 	set +x
> fi
> ```

There is no common part for both of these modes. I think we should go without something which is already done for creating figures:
- the mode validation e.g.: https://github.com/pmem/rpma/blob/master/tools/perf/create_report_figures.sh#L68
- running the chosen mode e.g.: https://github.com/pmem/rpma/blob/master/tools/perf/create_report_figures.sh#L622

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/931)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/report_bench.sh, line 16 at r1](https://reviewable.io/reviews/pmem/rpma/931#-MVWZtOw4RHxiIfF31OF:-MVWba41BpGVQahBKU4h:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e18cd53cde21ee6d57d763a10be1f3bed072bcee/tools/perf/report_bench.sh#L16)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

'avg' is unfortunate. It is a common abbreviation for 'average'.
</blockquote></details>

Done.
___
*[tools/perf/report_bench.sh, line 109 at r1](https://reviewable.io/reviews/pmem/rpma/931#-MVW_M6A2yAZe3vcW4K1:-MVX09uu20Zw846uZAbG:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e18cd53cde21ee6d57d763a10be1f3bed072bcee/tools/perf/report_bench.sh#L109)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

There is no common part for both of these modes. I think we should go without something which is already done for creating figures:
- the mode validation e.g.: https://github.com/pmem/rpma/blob/master/tools/perf/create_report_figures.sh#L68
- running the chosen mode e.g.: https://github.com/pmem/rpma/blob/master/tools/perf/create_report_figures.sh#L622
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/931)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/report_bench.sh, line 80 at r2](https://reviewable.io/reviews/pmem/rpma/931#-MVX2_Pl7HX_aY1apk6J:-MVX2_Pl7HX_aY1apk6K:b-2waeny) ([raw file](https://github.com/pmem/rpma/blob/f147f74eec491b5b7f519c8bd12bb84ad1f2c664/tools/perf/report_bench.sh#L80)):*
> ```Shell
> 	done
> done
> set +x
> ```

You forgot about this line.
___
*[tools/perf/report_bench.sh, line 99 at r2](https://reviewable.io/reviews/pmem/rpma/931#-MVX2l_-6Ar-r7wSCzM7:-MVX2l_-6Ar-r7wSCzM8:b-3ncky9) ([raw file](https://github.com/pmem/rpma/blob/2f348eee834d604b21ac19fef4feecc2f0c1a741/tools/perf/report_bench.sh#L99)):*
> ```Shell
> function report_asvah
> {
> 	echo "WRITE LAT/BW"
> ```

WRITE -> AOF

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/931)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/report_bench.sh, line 80 at r2](https://reviewable.io/reviews/pmem/rpma/931#-MVX2_Pl7HX_aY1apk6J:-MVX9TLm76vVQNc4g6I_:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f147f74eec491b5b7f519c8bd12bb84ad1f2c664/tools/perf/report_bench.sh#L80)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You forgot about this line.
</blockquote></details>

Done.
___
*[tools/perf/report_bench.sh, line 99 at r2](https://reviewable.io/reviews/pmem/rpma/931#-MVX2l_-6Ar-r7wSCzM7:-MVX9IpW6BcqSlzrMtan:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2f348eee834d604b21ac19fef4feecc2f0c1a741/tools/perf/report_bench.sh#L99)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

WRITE -> AOF
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/931#-:-MVXA5CJCYReRcRo2H7S:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
