### PR TITLE
common: default CMake settings added to the documentation

### PR DESCRIPTION
**Pull request by grom72**
New column "Default" to present what CMake parameters are set to active values

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/344)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/344)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[INSTALL.md, line 50 at r1](https://reviewable.io/reviews/pmem/rpma/344#-MGIo7pr6i4rRuO6aZw6:-MGIo7pr6i4rRuO6aZw7:bkn6vsn) ([raw file](https://github.com/pmem/rpma/blob/341f6c8ac2421cba931dcec3f435637c62420784/INSTALL.md#L50)):*
> ```
> | GROFF | Path to a program | /usr/bin/groff | /usr/bin/groff |
> ```

```
| GROFF | Path to a program | (a path) | (none) |
```
___
*[INSTALL.md, line 57 at r1](https://reviewable.io/reviews/pmem/rpma/344#-MGIoPx4BMfC-a3jk_S1:-MGIoPx4BMfC-a3jk_S2:bujufg7) ([raw file](https://github.com/pmem/rpma/blob/341f6c8ac2421cba931dcec3f435637c62420784/INSTALL.md#L57)):*
> ```
> | TXT2MAN | Path to a program | /usr/local/bin/txt2man | /usr/local/bin/txt2man |
> ```

```
| TXT2MAN | Path to a program | (a path) | (none) |
```

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/344#-:-MGIoviD5nPFm80wp-pU:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/344)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[INSTALL.md, line 50 at r1](https://reviewable.io/reviews/pmem/rpma/344#-MGIo7pr6i4rRuO6aZw6:-MGIwrFC5hq2Qzz0vSUN:bqc6haz) ([raw file](https://github.com/pmem/rpma/blob/341f6c8ac2421cba931dcec3f435637c62420784/INSTALL.md#L50)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> | GROFF | Path to a program | /usr/bin/groff | /usr/bin/groff |
> ```

```
| GROFF | Path to a program | (a path) | (none) |
```
</blockquote></details>

Done - removed as not settable
___
*[INSTALL.md, line 57 at r1](https://reviewable.io/reviews/pmem/rpma/344#-MGIoPx4BMfC-a3jk_S1:-MGIwx1Y7kreUw9V0hZV:bz5caq7) ([raw file](https://github.com/pmem/rpma/blob/341f6c8ac2421cba931dcec3f435637c62420784/INSTALL.md#L57)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> | TXT2MAN | Path to a program | /usr/local/bin/txt2man | /usr/local/bin/txt2man |
> ```

```
| TXT2MAN | Path to a program | (a path) | (none) |
```
</blockquote></details>

Done - removed as not settable

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/344)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
