### PR TITLE
tools: remove double check of ['filetype'] == 'malloc' condition

### PR DESCRIPTION
**Pull request by grom72**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1501)

### CODE REVIEW

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1501#-:-MtgmZ2W8H7PBaONPWSd:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1501)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 190 at r1](https://reviewable.io/reviews/pmem/rpma/1501#-Mth1t0aEgRHHqA_k8p9:-Mth1t0aEgRHHqA_k8pA:bf7itk5) ([raw file](https://github.com/pmem/rpma/blob/a53fef9a47fe4d4c5d0f559a5de2a21d475b06ae/tools/perf/lib/benchmark/runner/fio.py#L190)):*
> ```Python
>             # create_on_open prevents FIO from creating files
>             # where the engines won't make use of them anyways
>             # since they are using DRAM instead
> ```

Please make full sentences:
```
            # Use DRAM if pmem_path is not provided.
            # create_on_open prevents FIO from creating files
            # where the engines won't make use of them anyways
            # since they are using DRAM instead.
```



_Code quote:_
```Python
            # use DRAM if pmem_path is not provided
            # create_on_open prevents FIO from creating files
            # where the engines won't make use of them anyways
            # since they are using DRAM instead
```

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1501)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau and @osalyk)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 190 at r1](https://reviewable.io/reviews/pmem/rpma/1501#-Mth1t0aEgRHHqA_k8p9:-Mthr2gyB6DRcP5paadB:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a53fef9a47fe4d4c5d0f559a5de2a21d475b06ae/tools/perf/lib/benchmark/runner/fio.py#L190)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please make full sentences:
```
            # Use DRAM if pmem_path is not provided.
            # create_on_open prevents FIO from creating files
            # where the engines won't make use of them anyways
            # since they are using DRAM instead.
```
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1501#-:-Mths6Ej56oSUdP3nD51:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
