### PR TITLE
tools: fix setting rw_order

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1161)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1161)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1161#-MfbJ5oDDHdzCKAcPkS0:-MfbJ5oDDHdzCKAcPkS1:b85fk8) (no related file):*
Since it is a static method I think it will be very easy to write a test for it.

---
___
*[tools/perf/lib/Figure.py, line 69 at r1](https://reviewable.io/reviews/pmem/rpma/1161#-MfbJ02gDgrrQSOIXftL:-MfbJ02gDgrrQSOIXftM:bq0um8e) ([raw file](https://github.com/pmem/rpma/blob/56d73c17ea092adbb946486575e040c06eacec01/tools/perf/lib/Figure.py#L69)):*
> ```Python
>         output = {}
>         if 'rw' in oneseries.keys():
>             output['rw_order'] = 'rand' if oneseries['rw'] in ["randread", "randwrite"] else 'seq'
> ```

`'` instead of `"` for consistency.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1161)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1161#-MfbJ5oDDHdzCKAcPkS0:-MfbVHB24tvzuqgkNpPp:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Since it is a static method I think it will be very easy to write a test for it.
</blockquote></details>

Done.

---
___
*[tools/perf/lib/Figure.py, line 69 at r1](https://reviewable.io/reviews/pmem/rpma/1161#-MfbJ02gDgrrQSOIXftL:-MfbVI2ZCzgTJ9ynxxNe:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/56d73c17ea092adbb946486575e040c06eacec01/tools/perf/lib/Figure.py#L69)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`'` instead of `"` for consistency.
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1161)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/tests/lib/figure/test_oneseries_derivatives.py, line 16 at r2](https://reviewable.io/reviews/pmem/rpma/1161#-Mfbdzup7Ojmj9lqZU4W:-Mfbdzuq6Ztr71mn74Rj:bbv5rzx) ([raw file](https://github.com/pmem/rpma/blob/cee76eed973691b093c340ec2e77d66b36a64fe8/tools/perf/tests/lib/figure/test_oneseries_derivatives.py#L16)):*
> ```Python
>     oneseries = { 'rw' : 'randread' }
>     output = Figure.oneseries_derivatives(oneseries)
>     assert output['rw_order'] == 'rand'
> ```

You do not need four identical tests. You need a test with parameters.

```python
@pytest.mark.parametrize('rw,rw_order', [('randread', 'rand'), ('randwrite', 'rand'), ...])
def test_oneseries_derivatives_randread(rw, rw_order):
    """XXX"""
    output = Figure.oneseries_derivatives({ 'rw' : rw})
    assert output['rw_order'] == rw_order
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1161)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/tests/lib/figure/test_oneseries_derivatives.py, line 16 at r2](https://reviewable.io/reviews/pmem/rpma/1161#-Mfbdzup7Ojmj9lqZU4W:-MfbvzAf0RimsI2Q6Yru:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cee76eed973691b093c340ec2e77d66b36a64fe8/tools/perf/tests/lib/figure/test_oneseries_derivatives.py#L16)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You do not need four identical tests. You need a test with parameters.

```python
@pytest.mark.parametrize('rw,rw_order', [('randread', 'rand'), ('randwrite', 'rand'), ...])
def test_oneseries_derivatives_randread(rw, rw_order):
    """XXX"""
    output = Figure.oneseries_derivatives({ 'rw' : rw})
    assert output['rw_order'] == rw_order
```
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
:goat:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1161#-:-MfcJ4Gb249RfqY3kxB4:bnd2vnu)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/tests/lib/figure/test_oneseries_derivatives.py, line 17 at r3](https://reviewable.io/reviews/pmem/rpma/1161#-MfcE1lXEehfjv82lNcN:-MfcE1lXEehfjv82lNcO:b32w03) ([raw file](https://github.com/pmem/rpma/blob/c96e88dd8978adcff2b5a1d3de5e288696891c7c/tools/perf/tests/lib/figure/test_oneseries_derivatives.py#L17)):*
> ```Python
>     output = Figure.oneseries_derivatives({'rw' : rw})
>     assert output['rw_order'] == rw_order
> ```

NL

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1161)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/tests/lib/figure/test_oneseries_derivatives.py, line 17 at r3](https://reviewable.io/reviews/pmem/rpma/1161#-MfcE1lXEehfjv82lNcN:-MfcKglB-BA4m-FLKH1g:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c96e88dd8978adcff2b5a1d3de5e288696891c7c/tools/perf/tests/lib/figure/test_oneseries_derivatives.py#L17)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

NL
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1161#-:-MfcL1vwCCfZzoN6_t3q:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1161)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/tests/lib/figure/test_oneseries_derivatives.py, line 17 at r3](https://reviewable.io/reviews/pmem/rpma/1161#-MfcE1lXEehfjv82lNcN:-Mff_yNhCF1F-6Cuj6em:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c96e88dd8978adcff2b5a1d3de5e288696891c7c/tools/perf/tests/lib/figure/test_oneseries_derivatives.py#L17)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1161)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/tests/lib/figure/test_oneseries_derivatives.py, line 17 at r3](https://reviewable.io/reviews/pmem/rpma/1161#-MfcE1lXEehfjv82lNcN:-Mffa0kvEat5eUR7BKON:bpwv6yg) ([raw file](https://github.com/pmem/rpma/blob/c96e88dd8978adcff2b5a1d3de5e288696891c7c/tools/perf/tests/lib/figure/test_oneseries_derivatives.py#L17)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@janekmi please resolve

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1161)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1161#-:-Mfg8iDb4Tn07fvzsWWq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
