### PR TITLE
tools: add support for the SKIP_RUNNING_TOOLS option

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1482)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1482)* status: 2 of 8 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 184 at r1](https://reviewable.io/reviews/pmem/rpma/1482#-Mt3dxZ981UDIx-kxUp8:-Mt3dxZ981UDIx-kxUp9:b40jogs) ([raw file](https://github.com/pmem/rpma/blob/5a8d8ea493df0ee93cc4a88e5d1a045dc9ac3542/tools/perf/lib/benchmark/runner/fio.py#L184)):*
> ```Python
>                 .format(self.__tool_mode)
>         job_file = "./fio_jobs/librpma_{}-server.fio".format(self.__tool_mode)
>         RemoteCmd.copy_to_remote(self.__config, job_file, r_job_path)
> ```

Shall we skip this?
See comment below.



_Code quote:_
```Python
RemoteCmd.copy_to_remote(self.__config, job_file, r_job_path)
```
___
*[tools/perf/lib/benchmark/runner/fio.py, line 191 at r1](https://reviewable.io/reviews/pmem/rpma/1482#-Mt3YooL3MROX-jYekmb:-Mt3YooL3MROX-jYekmc:b2p7oy1) ([raw file](https://github.com/pmem/rpma/blob/5a8d8ea493df0ee93cc4a88e5d1a045dc9ac3542/tools/perf/lib/benchmark/runner/fio.py#L191)):*
> ```Python
>             with open(settings['logfile_server'], 'a', encoding='utf-8') as log:
>                 log.write("[server]$ {}".format(' '.join(args)))
>         if not self.__do_nothing:
> ```

Is there any particular reason to filter "do_nothing" so late?
Shall we also skip copying the remote fio job file?



_Code quote:_
```Python
if not self.__do_nothing:
```
___
*[tools/perf/lib/benchmark/runner/fio.py, line 197 at r1](https://reviewable.io/reviews/pmem/rpma/1482#-Mt3eCCQ9I3SdYO_QR2G:-Mt3eCCQ9I3SdYO_QR2H:b-g4mtih) ([raw file](https://github.com/pmem/rpma/blob/5a8d8ea493df0ee93cc4a88e5d1a045dc9ac3542/tools/perf/lib/benchmark/runner/fio.py#L197)):*
> ```Python
>     def __server_stop(self, settings):
>         """wait until server finishes"""
>         if self.__do_nothing:
> ```

```
if self.__server is None:
   return
```



_Code quote:_
```Python
        if self.__do_nothing:
            return
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1482)* status: 2 of 8 files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 184 at r1](https://reviewable.io/reviews/pmem/rpma/1482#-Mt3dxZ981UDIx-kxUp8:-Mt4Qk4h4qCkXlmCsuO_:b6u8azb) ([raw file](https://github.com/pmem/rpma/blob/5a8d8ea493df0ee93cc4a88e5d1a045dc9ac3542/tools/perf/lib/benchmark/runner/fio.py#L184)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Shall we skip this?
See comment below.
</blockquote></details>

No, we shall not - see the answer below.
___
*[tools/perf/lib/benchmark/runner/fio.py, line 191 at r1](https://reviewable.io/reviews/pmem/rpma/1482#-Mt3YooL3MROX-jYekmb:-Mt4Plo-30s_uJYCoYiL:b-7wd2ve) ([raw file](https://github.com/pmem/rpma/blob/5a8d8ea493df0ee93cc4a88e5d1a045dc9ac3542/tools/perf/lib/benchmark/runner/fio.py#L191)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Is there any particular reason to filter "do_nothing" so late?
Shall we also skip copying the remote fio job file?
</blockquote></details>

The reason is what `CONFIG.JSON.md` says: "`DO_NOTHING` *allows running all the machinery but prevents the actual benchmark binaries from being run*", so we can skip only running the actual benchmark binaries, all the rest should be run normally as is.

Maybe `DO_NOT_RUN` or `DO_NOT_RUN_BINARIES` would be a better name than `DO_NOTHING` for that ?
___
*[tools/perf/lib/benchmark/runner/fio.py, line 197 at r1](https://reviewable.io/reviews/pmem/rpma/1482#-Mt3eCCQ9I3SdYO_QR2G:-Mt4R9bM58UxTN_yHznS:b-1f82d4) ([raw file](https://github.com/pmem/rpma/blob/5a8d8ea493df0ee93cc4a88e5d1a045dc9ac3542/tools/perf/lib/benchmark/runner/fio.py#L197)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```
if self.__server is None:
   return
```
</blockquote></details>

The current version is more clear and obvious in my opinion. Who will know when `self.__server is None` ?
` if self.__do_nothing:` is obvious.

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1482)* status: 3 of 8 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 184 at r1](https://reviewable.io/reviews/pmem/rpma/1482#-Mt3dxZ981UDIx-kxUp8:-Mt4Ud_ED1gMkxRR1BrK:b-wfmavd) ([raw file](https://github.com/pmem/rpma/blob/5a8d8ea493df0ee93cc4a88e5d1a045dc9ac3542/tools/perf/lib/benchmark/runner/fio.py#L184)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No, we shall not - see the answer below.
</blockquote></details>

Is there any added value to copy data to the remote node?
___
*[tools/perf/lib/benchmark/runner/fio.py, line 191 at r1](https://reviewable.io/reviews/pmem/rpma/1482#-Mt3YooL3MROX-jYekmb:-Mt4ThqE5Lnu-EQerydY:b-6hbppz) ([raw file](https://github.com/pmem/rpma/blob/5a8d8ea493df0ee93cc4a88e5d1a045dc9ac3542/tools/perf/lib/benchmark/runner/fio.py#L191)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The reason is what `CONFIG.JSON.md` says: "`DO_NOTHING` *allows running all the machinery but prevents the actual benchmark binaries from being run*", so we can skip only running the actual benchmark binaries, all the rest should be run normally as is.

Maybe `DO_NOT_RUN` or `DO_NOT_RUN_BINARIES` would be a better name than `DO_NOTHING` for that ?
</blockquote></details>

How about ```RETURN_DUMMY_RESULTS``` or ```SKIP_BENCHMARKING_STEPS```?
___
*[tools/perf/lib/benchmark/runner/fio.py, line 197 at r1](https://reviewable.io/reviews/pmem/rpma/1482#-Mt3eCCQ9I3SdYO_QR2G:-Mt4TUw80Hx7PEzjTi50:b-p81upb) ([raw file](https://github.com/pmem/rpma/blob/5a8d8ea493df0ee93cc4a88e5d1a045dc9ac3542/tools/perf/lib/benchmark/runner/fio.py#L197)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The current version is more clear and obvious in my opinion. Who will know when `self.__server is None` ?
` if self.__do_nothing:` is obvious.
</blockquote></details>

```self.__server = None``` is in __init__().
So as long as nobody starts any remote command ```self.__server``` shall remain ```None```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1482)* status: 3 of 8 files reviewed, 3 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 184 at r1](https://reviewable.io/reviews/pmem/rpma/1482#-Mt3dxZ981UDIx-kxUp8:-Mt4Yl_XEpfszd5Z_xzc:bcnlgmr) ([raw file](https://github.com/pmem/rpma/blob/5a8d8ea493df0ee93cc4a88e5d1a045dc9ac3542/tools/perf/lib/benchmark/runner/fio.py#L184)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Is there any added value to copy data to the remote node?
</blockquote></details>

There is: checking if it works.
___
*[tools/perf/lib/benchmark/runner/fio.py, line 197 at r1](https://reviewable.io/reviews/pmem/rpma/1482#-Mt3eCCQ9I3SdYO_QR2G:-Mt4Z18o55u_phO_QoRl:b-ut7b53) ([raw file](https://github.com/pmem/rpma/blob/5a8d8ea493df0ee93cc4a88e5d1a045dc9ac3542/tools/perf/lib/benchmark/runner/fio.py#L197)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```self.__server = None``` is in __init__().
So as long as nobody starts any remote command ```self.__server``` shall remain ```None```
</blockquote></details>

Yes, there is of course - we know that, but any other user does not know if it is only there, so they have to check if it is set to NULL anywhere else, so they have to grep the whole file and look for usages of `self.__server` to check that.

And `if self.__do_nothing` is just obvious.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1482)* status: 3 of 8 files reviewed, 3 unresolved discussions (waiting on @grom72)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 191 at r1](https://reviewable.io/reviews/pmem/rpma/1482#-Mt3YooL3MROX-jYekmb:-Mt5BXcBBwKgZJ2TJV8Q:b-wy0eet) ([raw file](https://github.com/pmem/rpma/blob/5a8d8ea493df0ee93cc4a88e5d1a045dc9ac3542/tools/perf/lib/benchmark/runner/fio.py#L191)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

How about ```RETURN_DUMMY_RESULTS``` or ```SKIP_BENCHMARKING_STEPS```?
</blockquote></details>

How about
1) `RETURN_ZEROED_RESULTS` or
2) `RETURN_RANDOM_RESULTS` and return a random integer instead of `0` ?

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1482)* status: 3 of 8 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 184 at r1](https://reviewable.io/reviews/pmem/rpma/1482#-Mt3dxZ981UDIx-kxUp8:-Mt7Clte6_wulWYlL5hE:b-m8vat4) ([raw file](https://github.com/pmem/rpma/blob/5a8d8ea493df0ee93cc4a88e5d1a045dc9ac3542/tools/perf/lib/benchmark/runner/fio.py#L184)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

There is: checking if it works.
</blockquote></details>

But then would it be better to run benchmarks just for a very short time i.e 1s for FIO and 5 iterations for ib_read?
___
*[tools/perf/lib/benchmark/runner/fio.py, line 191 at r1](https://reviewable.io/reviews/pmem/rpma/1482#-Mt3YooL3MROX-jYekmb:-Mt7D49A6yAn0g2TTBOI:buqe287) ([raw file](https://github.com/pmem/rpma/blob/5a8d8ea493df0ee93cc4a88e5d1a045dc9ac3542/tools/perf/lib/benchmark/runner/fio.py#L191)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

How about
1) `RETURN_ZEROED_RESULTS` or
2) `RETURN_RANDOM_RESULTS` and return a random integer instead of `0` ?
</blockquote></details>

I think that we should use the word SKIP to indicate that benchmark engines (fio/ib_read) will not be started at all.
'''USE_DUMMY_PERFORMANCE_EVALUATION_TOOL"
___
*[tools/perf/lib/benchmark/runner/fio.py, line 197 at r1](https://reviewable.io/reviews/pmem/rpma/1482#-Mt3eCCQ9I3SdYO_QR2G:-Mt7DIeo4QXJgiHiKfU_:b-y39o83) ([raw file](https://github.com/pmem/rpma/blob/5a8d8ea493df0ee93cc4a88e5d1a045dc9ac3542/tools/perf/lib/benchmark/runner/fio.py#L197)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, there is of course - we know that, but any other user does not know if it is only there, so they have to check if it is set to NULL anywhere else, so they have to grep the whole file and look for usages of `self.__server` to check that.

And `if self.__do_nothing` is just obvious.
</blockquote></details>

OK - I think we should just fix in separate PR __server_stop() and do nothing if self.__server has not been initialized by __server_start.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1482)* status: 3 of 8 files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 184 at r1](https://reviewable.io/reviews/pmem/rpma/1482#-Mt3dxZ981UDIx-kxUp8:-Mt7PwjAEeVf0ePNGvFn:bz4o3xw) ([raw file](https://github.com/pmem/rpma/blob/5a8d8ea493df0ee93cc4a88e5d1a045dc9ac3542/tools/perf/lib/benchmark/runner/fio.py#L184)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

But then would it be better to run benchmarks just for a very short time i.e 1s for FIO and 5 iterations for ib_read?
</blockquote></details>

No, it would not, because:
1) it is not the SHORT_RUN mode,
2) it would require to have a full HW setup with 2 RNICs, because not all modes can be run on SoftRoCE and DO_NOTHING is intended to be run with no HW and no SoftRoCE
___
*[tools/perf/lib/benchmark/runner/fio.py, line 191 at r1](https://reviewable.io/reviews/pmem/rpma/1482#-Mt3YooL3MROX-jYekmb:-Mt7SY_DCiHcsJugKN-P:bd58qmo) ([raw file](https://github.com/pmem/rpma/blob/5a8d8ea493df0ee93cc4a88e5d1a045dc9ac3542/tools/perf/lib/benchmark/runner/fio.py#L191)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I think that we should use the word SKIP to indicate that benchmark engines (fio/ib_read) will not be started at all.
'''USE_DUMMY_PERFORMANCE_EVALUATION_TOOL"
</blockquote></details>

'''USE_DUMMY_PERFORMANCE_EVALUATION_TOOL" - no, because we do not use any other tool, but we just do not run normal tools, so:
- `DO_NOT_RUN_TOOLS` or
- `SKIP_RUNNING_TOOLS`

?
___
*[tools/perf/lib/benchmark/runner/fio.py, line 197 at r1](https://reviewable.io/reviews/pmem/rpma/1482#-Mt3eCCQ9I3SdYO_QR2G:-Mt7RY2N1vjLm5vXcygc:b-n4xfo5) ([raw file](https://github.com/pmem/rpma/blob/5a8d8ea493df0ee93cc4a88e5d1a045dc9ac3542/tools/perf/lib/benchmark/runner/fio.py#L197)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

OK - I think we should just fix in separate PR __server_stop() and do nothing if self.__server has not been initialized by __server_start.
</blockquote></details>

OK, you have convinced me finally ;-)

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1482)* status: 2 of 8 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 191 at r1](https://reviewable.io/reviews/pmem/rpma/1482#-Mt3YooL3MROX-jYekmb:-Mt7US2M8XTl7OCYOH-G:b-trcvkw) ([raw file](https://github.com/pmem/rpma/blob/5a8d8ea493df0ee93cc4a88e5d1a045dc9ac3542/tools/perf/lib/benchmark/runner/fio.py#L191)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

'''USE_DUMMY_PERFORMANCE_EVALUATION_TOOL" - no, because we do not use any other tool, but we just do not run normal tools, so:
- `DO_NOT_RUN_TOOLS` or
- `SKIP_RUNNING_TOOLS`

?
</blockquote></details>

SKIP_RUNNING_TOOLS

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1482)* status: 0 of 8 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 191 at r1](https://reviewable.io/reviews/pmem/rpma/1482#-Mt3YooL3MROX-jYekmb:-Mt802X42erE62v1stPx:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/5a8d8ea493df0ee93cc4a88e5d1a045dc9ac3542/tools/perf/lib/benchmark/runner/fio.py#L191)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

SKIP_RUNNING_TOOLS
</blockquote></details>

Done

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 8 files at r1, 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1482)* status: 6 of 8 files reviewed, all discussions resolved (waiting on @grom72)

___
*[tools/perf/lib/Requirement.py, line 224 at r3](https://reviewable.io/reviews/pmem/rpma/1482#-Mt8ByGq1CZGvKrMo2g4:-Mt8ByGq1CZGvKrMo2g5:b-rcznbg) ([raw file](https://github.com/pmem/rpma/blob/9836b70aed8bf9af449890b8bf619043e2a78b09/tools/perf/lib/Requirement.py#L224)):*
> ```Python
>         def __set_DDIO(cls, req, config):
>             """set DDIO to the required value"""
>             if config.get('SKIP_RUNNING_TOOLS', False):
> ```

Skipping DDIO is not mentioned in the documentation.



_Code quote:_
```Python
            if config.get('SKIP_RUNNING_TOOLS', False):
                return
```

**Review by grom72 — APPROVED** [review]
:goat: 

> Reviewed 2 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1482#-:-Mt8CRHT5QN3Nyu6G-nf:bdycpsm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1482)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @grom72)

___
*[tools/perf/lib/Requirement.py, line 224 at r3](https://reviewable.io/reviews/pmem/rpma/1482#-Mt8ByGq1CZGvKrMo2g4:-Mt8E_7p8pqz3m8GRa9W:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/9836b70aed8bf9af449890b8bf619043e2a78b09/tools/perf/lib/Requirement.py#L224)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Skipping DDIO is not mentioned in the documentation.
</blockquote></details>

Done

**Review by grom72 — APPROVED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1482#-:-Mt8F-B5CPg4gV7RVXqH:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1482)* status: 6 of 8 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[tools/perf/CONFIG.JSON.md, line 54 at r5](https://reviewable.io/reviews/pmem/rpma/1482#-Mt97EV-3tpUPqtLrdJ5:-Mt97EV-3tpUPqtLrdJ6:b-fkn6w7) ([raw file](https://github.com/pmem/rpma/blob/8cfe61379c2a409bf998d5df53be5eb52c71d48c/tools/perf/CONFIG.JSON.md#L54)):*
> ```Markdown
> ```
> 
> During in-depth analysis of the benchmarking process itself, you may find useful these two options. Where `SKIP_RUNNING_TOOLS` allows running all the machinery but prevents the actual benchmarking binaries and the script setting DDIO ([tools/ddio.sh](./tools/ddio.sh)) from being run and disables copying files to a remote node. Whereas `DUMP_CMDS` allows dumping all commands running the benchmark binaries. You can use either or both of them.
> ```

why such a decision? we have talked to skip only benchmarking?



_Code quote:_
```Markdown
and disables copying files to a remote node
```

**Review by grom72 — COMMENTED** [review]
:lgtm_cancel: 

> Reviewed 2 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1482#-:-Mt97o6KDEbhDpFFvGY0:b8b79qu)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1482)* status: 2 of 8 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/perf/CONFIG.JSON.md, line 54 at r5](https://reviewable.io/reviews/pmem/rpma/1482#-Mt97EV-3tpUPqtLrdJ5:-MtCHFwkDpl470fv_82A:b-ognaa0) ([raw file](https://github.com/pmem/rpma/blob/8cfe61379c2a409bf998d5df53be5eb52c71d48c/tools/perf/CONFIG.JSON.md#L54)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

why such a decision? we have talked to skip only benchmarking?
</blockquote></details>

Excuse me, reverted. 
We will go back to that later.

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1482#-:-MtCJACy66NJheme6JM1:bnfp4nl)* status: 2 of 8 files reviewed, all discussions resolved (waiting on @grom72)

___
*[tools/perf/CONFIG.JSON.md, line 54 at r5](https://reviewable.io/reviews/pmem/rpma/1482#-Mt97EV-3tpUPqtLrdJ5:-MtCJ6Dr7vUX-ZLNJzhv:b-7qs3nd) ([raw file](https://github.com/pmem/rpma/blob/8cfe61379c2a409bf998d5df53be5eb52c71d48c/tools/perf/CONFIG.JSON.md#L54)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Excuse me, reverted. 
We will go back to that later.
</blockquote></details>

Can you make an issue about that?

**Review by grom72 — APPROVED** [review]
> Reviewed 6 of 6 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1482)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1482)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

___
*[tools/perf/CONFIG.JSON.md, line 54 at r5](https://reviewable.io/reviews/pmem/rpma/1482#-Mt97EV-3tpUPqtLrdJ5:-MtCT7F19I414ODMNm7d:bszma80) ([raw file](https://github.com/pmem/rpma/blob/8cfe61379c2a409bf998d5df53be5eb52c71d48c/tools/perf/CONFIG.JSON.md#L54)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Can you make an issue about that?
</blockquote></details>

https://github.com/pmem/rpma/issues/1488

**Review by grom72 — COMMENTED** [review]
> Reviewed 3 of 4 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1482)* status: 7 of 8 files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1482)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1482)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1482)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by Patryk717 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1482#-:-MtHh4Ut9nrv0kbcUA3C:bdycpsm)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1482)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 4 of 6 files at r6, 4 of 4 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1482#-:-MtMcWJz08MUnT1UymGv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
