### PR TITLE
examples: change the write size from KILOBYTE to HELLO_STR_SIZE

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/2016)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2016)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @osalyk)

___
*[`examples/04-write-to-persistent/client.c` line 148 at r1](https://reviewable.io/reviews/pmem/rpma/2016#-NBCfhAO7NEYMdMZkE8V:-NBCfhAP1kWJoeKb43vM:bx3kcs3) ([raw file](https://github.com/pmem/rpma/blob/1038c463dd5dc41b4586232f9406ffa02800a938/examples/04-write-to-persistent/client.c#L148)):*
> ```C
> 	if (ret) {
> 		goto err_mr_remote_delete;
> 	} else if (dst_size < KILOBYTE) {
> ```

The proper condition is as follows:
(see also other examples)



_Suggestion:_
```C
} else if (dst_size < HELLO_STR_SIZE) {
```
___
*[`examples/04-write-to-persistent/client.c` line 152 at r1](https://reviewable.io/reviews/pmem/rpma/2016#-NBCgE6F3ylstlIws5_a:-NBCgE6F3ylstlIws5_b:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/1038c463dd5dc41b4586232f9406ffa02800a938/examples/04-write-to-persistent/client.c#L152)):*
> ```C
> 		fprintf(stderr,
> 				"Remote memory region size too small for writing the data of the assumed size (%zu < %d)\n",
> 				dst_size, KILOBYTE);
> ```

.



_Suggestion:_
```C
				dst_size, HELLO_STR_SIZE);
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2016)* status: all files reviewed, 9 unresolved discussions (waiting on @grom72 and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2016#-NBCVTlU47S-hE_QhtAU:-NBCVTlV5GbeK0YXSDDE:b-hmatcn) (no related file):*
Update `CHANGELOG.md` please

___
___
*[`examples/04-write-to-persistent/client.c` line 148 at r1](https://reviewable.io/reviews/pmem/rpma/2016#-NBCfhAO7NEYMdMZkE8V:-NBCjDZi29JdHVGgU6Pg:b5ws0ct) ([raw file](https://github.com/pmem/rpma/blob/1038c463dd5dc41b4586232f9406ffa02800a938/examples/04-write-to-persistent/client.c#L148)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

The proper condition is as follows:
(see also other examples)
</blockquote></details>

The correct is: 
```c
} else if (dst_size - dst_offset < HELLO_STR_SIZE) {
```
___
*[`examples/04-write-to-persistent/client.c` line 152 at r1](https://reviewable.io/reviews/pmem/rpma/2016#-NBCgE6F3ylstlIws5_a:-NBCjOli-9GvbXVPFJsK:bz538q7) ([raw file](https://github.com/pmem/rpma/blob/1038c463dd5dc41b4586232f9406ffa02800a938/examples/04-write-to-persistent/client.c#L152)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

```c
dst_size - dst_offset, HELLO_STR_SIZE);
```
___
*[`examples/05-flush-to-persistent/client.c` line 144 at r1](https://reviewable.io/reviews/pmem/rpma/2016#-NBCjcV2A3kx159Fw67d:-NBCjcV2A3kx159Fw67e:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/1038c463dd5dc41b4586232f9406ffa02800a938/examples/05-flush-to-persistent/client.c#L144)):*
> ```C
> 	if (ret) {
> 		goto err_mr_remote_delete;
> 	} else if (dst_size < KILOBYTE) {
> ```

.



_Code quote:_
```C
(dst_size < KILOBYTE) 
```
___
*[`examples/05-flush-to-persistent/client.c` line 147 at r1](https://reviewable.io/reviews/pmem/rpma/2016#-NBCjdylAccJ0wnfC-E1:-NBCjdylAccJ0wnfC-E2:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/1038c463dd5dc41b4586232f9406ffa02800a938/examples/05-flush-to-persistent/client.c#L147)):*
> ```C
> 		fprintf(stderr,
> 				"Remote memory region size too small for writing the data of the assumed size (%zu < %d)\n",
> 				dst_size, KILOBYTE);
> ```

.



_Code quote:_
```C
dst_size, KILOBYTE);
```
___
*[`examples/09-flush-to-persistent-GPSPM/client.c` line 156 at r1](https://reviewable.io/reviews/pmem/rpma/2016#-NBCjfk7Bo1-AKfwyPjB:-NBCjfk7Bo1-AKfwyPjC:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/1038c463dd5dc41b4586232f9406ffa02800a938/examples/09-flush-to-persistent-GPSPM/client.c#L156)):*
> ```C
> 	if ((ret = rpma_mr_remote_get_size(dst_mr, &dst_size))) {
> 		goto err_mr_remote_delete;
> 	} else if (dst_size < KILOBYTE) {
> ```

.



_Code quote:_
```C
(dst_size < KILOBYTE)
```
___
*[`examples/09-flush-to-persistent-GPSPM/client.c` line 159 at r1](https://reviewable.io/reviews/pmem/rpma/2016#-NBCjgnI9kVnz3fpcpek:-NBCjgnI9kVnz3fpcpel:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/1038c463dd5dc41b4586232f9406ffa02800a938/examples/09-flush-to-persistent-GPSPM/client.c#L159)):*
> ```C
> 		fprintf(stderr,
> 				"Size of the remote memory region is too small for writing the data of the assumed size (%zu < %d)\n",
> 				dst_size, KILOBYTE);
> ```

.



_Code quote:_
```C
dst_size, KILOBYTE);
```
___
*[`examples/09scch-flush-to-persistent-GPSPM/client.c` line 160 at r1](https://reviewable.io/reviews/pmem/rpma/2016#-NBCjiw2A9ety0TuSyG6:-NBCjiw2A9ety0TuSyG7:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/1038c463dd5dc41b4586232f9406ffa02800a938/examples/09scch-flush-to-persistent-GPSPM/client.c#L160)):*
> ```C
> 	if ((ret = rpma_mr_remote_get_size(dst_mr, &dst_size))) {
> 		goto err_mr_remote_delete;
> 	} else if (dst_size < KILOBYTE) {
> ```

.



_Code quote:_
```C
(dst_size < KILOBYTE) 
```
___
*[`examples/09scch-flush-to-persistent-GPSPM/client.c` line 163 at r1](https://reviewable.io/reviews/pmem/rpma/2016#-NBCjjvDDignSOUWthd-:-NBCjjvDDignSOUWthd0:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/1038c463dd5dc41b4586232f9406ffa02800a938/examples/09scch-flush-to-persistent-GPSPM/client.c#L163)):*
> ```C
> 		fprintf(stderr,
> 				"Size of the remote memory region is too small for writing the data of the assumed size (%zu < %d)\n",
> 				dst_size, KILOBYTE);
> ```

.



_Code quote:_
```C
dst_size, KILOBYTE);
```

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2016)* status: all files reviewed, 9 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[`examples/04-write-to-persistent/client.c` line 148 at r1](https://reviewable.io/reviews/pmem/rpma/2016#-NBCfhAO7NEYMdMZkE8V:-NBCvjil2o7V97G9WIws:b-c904og) ([raw file](https://github.com/pmem/rpma/blob/1038c463dd5dc41b4586232f9406ffa02800a938/examples/04-write-to-persistent/client.c#L148)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

The correct is: 
```c
} else if (dst_size - dst_offset < HELLO_STR_SIZE) {
```
</blockquote></details>

``} else if (dst_size - dst_data->dst_offset < HELLO_STR_SIZE) {``
___
*[`examples/04-write-to-persistent/client.c` line 152 at r1](https://reviewable.io/reviews/pmem/rpma/2016#-NBCgE6F3ylstlIws5_a:-NBCvr-P-sIu3ebL9Z7Y:b-echoyx) ([raw file](https://github.com/pmem/rpma/blob/1038c463dd5dc41b4586232f9406ffa02800a938/examples/04-write-to-persistent/client.c#L152)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```c
dst_size - dst_offset, HELLO_STR_SIZE);
```

</blockquote></details>

dst_size - dst_data->dst_offset, HELLO_STR_SIZE);

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2016)* status: all files reviewed, 9 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[`examples/04-write-to-persistent/client.c` line 148 at r1](https://reviewable.io/reviews/pmem/rpma/2016#-NBCfhAO7NEYMdMZkE8V:-NBCxwyR2InCZIn7z4jT:bea2yyv) ([raw file](https://github.com/pmem/rpma/blob/1038c463dd5dc41b4586232f9406ffa02800a938/examples/04-write-to-persistent/client.c#L148)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

``} else if (dst_size - dst_data->dst_offset < HELLO_STR_SIZE) {``
</blockquote></details>

```c
dst_offset = dst_data->data_offset;
```
see line #156 - this should be just moved up
___
*[`examples/04-write-to-persistent/client.c` line 152 at r1](https://reviewable.io/reviews/pmem/rpma/2016#-NBCgE6F3ylstlIws5_a:-NBCxpuI5XY6dIycxwhh:bea2yyv) ([raw file](https://github.com/pmem/rpma/blob/1038c463dd5dc41b4586232f9406ffa02800a938/examples/04-write-to-persistent/client.c#L152)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

dst_size - dst_data->dst_offset, HELLO_STR_SIZE);
</blockquote></details>

```c
dst_offset = dst_data->data_offset;
```
see line #156 - this should be just moved up
___
*[`examples/04-write-to-persistent/client.c` line 156 at r1](https://reviewable.io/reviews/pmem/rpma/2016#-NBCxhQBAQPt9bsso2-m:-NBCxhQBAQPt9bsso2-n:b-ce9tyb) ([raw file](https://github.com/pmem/rpma/blob/1038c463dd5dc41b4586232f9406ffa02800a938/examples/04-write-to-persistent/client.c#L156)):*
> ```C
> 	}
> 
> 	dst_offset = dst_data->data_offset;
> ```

... here :-)



_Code quote:_
```C
dst_offset = dst_data->data_offset;
```

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2016)* status: all files reviewed, 9 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[`examples/04-write-to-persistent/client.c` line 148 at r1](https://reviewable.io/reviews/pmem/rpma/2016#-NBCfhAO7NEYMdMZkE8V:-NBDnHeD3RKle-59VbrR:b32v57) ([raw file](https://github.com/pmem/rpma/blob/1038c463dd5dc41b4586232f9406ffa02800a938/examples/04-write-to-persistent/client.c#L148)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```c
dst_offset = dst_data->data_offset;
```
see line #156 - this should be just moved up
</blockquote></details>

+1
___
*[`examples/04-write-to-persistent/client.c` line 152 at r1](https://reviewable.io/reviews/pmem/rpma/2016#-NBCgE6F3ylstlIws5_a:-NBDnIu4-vhY4vJGDZAV:b32v57) ([raw file](https://github.com/pmem/rpma/blob/1038c463dd5dc41b4586232f9406ffa02800a938/examples/04-write-to-persistent/client.c#L152)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```c
dst_offset = dst_data->data_offset;
```
see line #156 - this should be just moved up
</blockquote></details>

+1

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2016)* status: all files reviewed, 9 unresolved discussions (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2016)* status: 0 of 9 files reviewed, 9 unresolved discussions (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/2016#-NBCVTlU47S-hE_QhtAU:-NBG_dJyDjm_KP0hsRju:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Update `CHANGELOG.md` please
</blockquote></details>

Done.

___
___
*[`examples/04-write-to-persistent/client.c` line 148 at r1](https://reviewable.io/reviews/pmem/rpma/2016#-NBCfhAO7NEYMdMZkE8V:-NBGa0Ol5yV74ET3-W8x:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1038c463dd5dc41b4586232f9406ffa02800a938/examples/04-write-to-persistent/client.c#L148)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`examples/04-write-to-persistent/client.c` line 152 at r1](https://reviewable.io/reviews/pmem/rpma/2016#-NBCgE6F3ylstlIws5_a:-NBGa_Yh78eYm3S1av9K:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1038c463dd5dc41b4586232f9406ffa02800a938/examples/04-write-to-persistent/client.c#L152)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.
___
*[`examples/05-flush-to-persistent/client.c` line 144 at r1](https://reviewable.io/reviews/pmem/rpma/2016#-NBCjcV2A3kx159Fw67d:-NBGaFCN8HBr0UulFU_j:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1038c463dd5dc41b4586232f9406ffa02800a938/examples/05-flush-to-persistent/client.c#L144)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`examples/05-flush-to-persistent/client.c` line 147 at r1](https://reviewable.io/reviews/pmem/rpma/2016#-NBCjdylAccJ0wnfC-E1:-NBGaFdy14BurVGxkpJ-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1038c463dd5dc41b4586232f9406ffa02800a938/examples/05-flush-to-persistent/client.c#L147)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`examples/09-flush-to-persistent-GPSPM/client.c` line 156 at r1](https://reviewable.io/reviews/pmem/rpma/2016#-NBCjfk7Bo1-AKfwyPjB:-NBGaWyIDFfVlCO-0K18:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1038c463dd5dc41b4586232f9406ffa02800a938/examples/09-flush-to-persistent-GPSPM/client.c#L156)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`examples/09-flush-to-persistent-GPSPM/client.c` line 159 at r1](https://reviewable.io/reviews/pmem/rpma/2016#-NBCjgnI9kVnz3fpcpek:-NBGaXafE2D2wRPSGqOK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1038c463dd5dc41b4586232f9406ffa02800a938/examples/09-flush-to-persistent-GPSPM/client.c#L159)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`examples/09scch-flush-to-persistent-GPSPM/client.c` line 160 at r1](https://reviewable.io/reviews/pmem/rpma/2016#-NBCjiw2A9ety0TuSyG6:-NBGaYCBC2b5WZY4es7j:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1038c463dd5dc41b4586232f9406ffa02800a938/examples/09scch-flush-to-persistent-GPSPM/client.c#L160)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[`examples/09scch-flush-to-persistent-GPSPM/client.c` line 163 at r1](https://reviewable.io/reviews/pmem/rpma/2016#-NBCjjvDDignSOUWthd-:-NBGaYdkAweLrv-1HGCx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/1038c463dd5dc41b4586232f9406ffa02800a938/examples/09scch-flush-to-persistent-GPSPM/client.c#L163)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2016)* status: all files reviewed, 10 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[`examples/04-write-to-persistent/server.c` line 80 at r2](https://reviewable.io/reviews/pmem/rpma/2016#-NBGeUq55acgPJ_Tdq5V:-NBGeUq55acgPJ_Tdq5W:bi24exl) ([raw file](https://github.com/pmem/rpma/blob/56ae91774816fb37a7abc20bc7c98300ee1471ce/examples/04-write-to-persistent/server.c#L80)):*
> ```C
> 			return -1;
> 
> 		mem.mr_size = HELLO_STR_SIZE;
> ```

I would propose explicitly setting ``data_offset`` to ``0`` here and in other examples.
@ldorau I know that we have ``memset`` somewhere above, but it increases code readability.



_Suggestion:_
```C
mem.mr_size = HELLO_STR_SIZE;
mem.data_offset = 0;
```

**Review by ldorau — APPROVED** [review]
> Reviewed 9 of 9 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2016)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`examples/04-write-to-persistent/server.c` line 80 at r2](https://reviewable.io/reviews/pmem/rpma/2016#-NBGeUq55acgPJ_Tdq5V:-NBGj8OXDUaGYlV6wQOH:b32w0x) ([raw file](https://github.com/pmem/rpma/blob/56ae91774816fb37a7abc20bc7c98300ee1471ce/examples/04-write-to-persistent/server.c#L80)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I would propose explicitly setting ``data_offset`` to ``0`` here and in other examples.
@ldorau I know that we have ``memset`` somewhere above, but it increases code readability.
</blockquote></details>

OK

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2016)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2016)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`examples/04-write-to-persistent/server.c` line 80 at r2](https://reviewable.io/reviews/pmem/rpma/2016#-NBGeUq55acgPJ_Tdq5V:-NBGjiUFBYQPHQ1SOhZx:b32v57) ([raw file](https://github.com/pmem/rpma/blob/56ae91774816fb37a7abc20bc7c98300ee1471ce/examples/04-write-to-persistent/server.c#L80)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK
</blockquote></details>

+1

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2016)* status: 5 of 9 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[`examples/04-write-to-persistent/server.c` line 80 at r2](https://reviewable.io/reviews/pmem/rpma/2016#-NBGeUq55acgPJ_Tdq5V:-NBH4Rbo-rmlBY3DA_hx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/56ae91774816fb37a7abc20bc7c98300ee1471ce/examples/04-write-to-persistent/server.c#L80)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2016)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2016#-:-NBHEPt_EA9iUwvvhres:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2016)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2016#-:-NBHj3ycAM62OCOueyZQ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2016)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2016)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2016)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2016)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2016)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
