### PR TITLE
reports: CLX + MLX + CentOS 8.4 + FSDAX

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1622)

### CODE REVIEW

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1622#-:-MyBlQIU2zBH7eL7M5HU:bg7igkv)* status: 0 of 2 files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1622)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[reports/index.md, line 9 at r1](https://reviewable.io/reviews/pmem/rpma/1622#-MyCXTp_4LfPqG1f_bk0:-MyD5X4n31Wd8g1dw8mq:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ca726017f95056cd3a631fc092b6071c1c620d2c/reports/index.md#L9)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

See comments in https://reviewable.io/reviews/pmem/pmem.github.io/222#-MyCW_ee4kOXkr9a3R51
</blockquote></details>

Done.
___
*[reports/RPMA_Perf_report_CLX_MLX_CentOS8.4_FSDAX.pdf, line  at r1](https://reviewable.io/reviews/pmem/rpma/1622#-MyCXZWw-YNgNxrGYFwC:-MyD4u_R8-9v6YV_42zY:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ca726017f95056cd3a631fc092b6071c1c620d2c/reports/RPMA_Perf_report_CLX_MLX_CentOS8.4_FSDAX.pdf#L)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please remove the `reports` directory at all.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1622)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1622#-:-MyE463J4k6F7zzbzR_U:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
