### PR TITLE
examples: add examples for rpma_conn_wait()

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1849)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1849)* status: 0 of 24 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1849#-N54SOJlETnFYWiSs_ra:-N54SOJlETnFYWiSs_rb:b-27g9wz) (no related file):*
@ldorau I think we should rename all-new examples.
Instead of a new number, it will be better to use an old number with some suffix ``s`` indicating that it is the same example but based on a new completion event solution. E.g. ``06s-multiple-connections``

___

**Review by grom72 — COMMENTED** [review]
> Reviewed 9 of 22 files at r1, 12 of 12 files at r2, 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1849)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1849)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1849#-N54SOJlETnFYWiSs_ra:-N54y-kXExQwDgGDfsHY:bqjic64) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

@ldorau I think we should rename all-new examples.
Instead of a new number, it will be better to use an old number with some suffix ``s`` indicating that it is the same example but based on a new completion event solution. E.g. ``06s-multiple-connections``
</blockquote></details>

OK, but what does `s` stand for here?

___

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1849)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1849#-N54SOJlETnFYWiSs_ra:-N55-7jv0mXX31cPKaOX:b-b7sa7v) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK, but what does `s` stand for here?
</blockquote></details>

s = **Shared** Completion Channel

___

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1849)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1849)* status: 3 of 24 files reviewed, all discussions resolved (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1849#-N54SOJlETnFYWiSs_ra:-N55NMq76z_FsLx-OBJn:bhbr65f) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK
</blockquote></details>

@grom72 Done

___

**Review by grom72 — COMMENTED** [review]
> Reviewed 19 of 21 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1849)* status: 22 of 24 files reviewed, all discussions resolved (waiting on @grom72)

**Comment by ldorau** [comment]
Incorporated into https://github.com/pmem/rpma/pull/1898

**Pull request closed without merging**
