### PR TITLE
common: verify if PMDK was successfully installed

### PR DESCRIPTION
**Pull request by ldorau**
Verify if PMDK was successfully installed - fail the build if not.

Ref: https://github.com/pmem/pmdk/issues/5540

Requires:
- [x] #2112 

- - -
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/2109)

### CODE REVIEW

**Comment by ldorau** [comment]
The Rocky Linux 8 and 9 fail because of https://github.com/pmem/pmdk/issues/5540

**Comment by ldorau** [comment]
> The Rocky Linux 8 and 9 builds fail because of [pmem/pmdk#5540](https://github.com/pmem/pmdk/issues/5540)

There is already a fix for that: https://github.com/pmem/rpma/pull/2112

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2109#-:-NPw4DkBEdymg44e4A0B:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Comment by yangx-jy** [comment]
*[`utils/docker/images/install-pmdk.sh` line 19 at r3](https://reviewable.io/reviews/pmem/rpma/2109#-NPzmJ3sDVYSP-hbVTaS:-NPzmJ3t8MqPTmdmornZ:b-fpc70h) ([raw file](https://github.com/pmem/rpma/blob/9e45aa6b254f7c63209417d337f331c0708c8a90/utils/docker/images/install-pmdk.sh#L19)):*
> ```Shell
> 
> set -ex
> ```

If you just want to stop building immediately when getting an error, is it necessary to print debug messages for all commands by adding `x`?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2109)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[`utils/docker/images/install-pmdk.sh` line 19 at r3](https://reviewable.io/reviews/pmem/rpma/2109#-NPzmJ3sDVYSP-hbVTaS:-NPzs4c000SavoTUDksb:b35i00h) ([raw file](https://github.com/pmem/rpma/blob/9e45aa6b254f7c63209417d337f331c0708c8a90/utils/docker/images/install-pmdk.sh#L19)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

If you just want to stop building immediately when getting an error, is it necessary to print debug messages for all commands by adding `x`?
</blockquote></details>

Of course not. It is just very useful to have commands printed out in the build that failed just to be able to see which command failed. Otherwise you would have to add `-x` and run the build again, but the failure may not reproduce in the same way.

**Comment by yangx-jy** [comment]
*[`utils/docker/images/install-pmdk.sh` line 19 at r3](https://reviewable.io/reviews/pmem/rpma/2109#-NPzmJ3sDVYSP-hbVTaS:-NPzwrJsE1K3dlCWqJtq:b-vii9ay) ([raw file](https://github.com/pmem/rpma/blob/9e45aa6b254f7c63209417d337f331c0708c8a90/utils/docker/images/install-pmdk.sh#L19)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Of course not. It is just very useful to have commands printed out in the build that failed just to be able to see which command failed. Otherwise you would have to add `-x` and run the build again, but the failure may not reproduce in the same way.
</blockquote></details>

OK, do you plan to add `x` for other scripts (e.g. install-cmocka.sh)?

**Comment by yangx-jy** [comment]
:lgtm:

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/2109)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[`utils/docker/images/install-pmdk.sh` line 19 at r3](https://reviewable.io/reviews/pmem/rpma/2109#-NPzmJ3sDVYSP-hbVTaS:-NQ-2FGn0Siw2Fw9jM3y:bbv9fqj) ([raw file](https://github.com/pmem/rpma/blob/9e45aa6b254f7c63209417d337f331c0708c8a90/utils/docker/images/install-pmdk.sh#L19)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

OK, do you plan to add `x` for other scripts (e.g. install-cmocka.sh)?
</blockquote></details>

If they start to fail - yes, there is no need to do it now.

**Pull request merged**
