### PR TITLE
test: add rpma_mr_dereg mt test

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1873)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1873)* status: 0 of 2 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1873)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by osalyk — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1873)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[`tests/multithreaded/mr/rpma_mr_dereg.c` line 93 at r2](https://reviewable.io/reviews/pmem/rpma/1873#-N5_NLft2p1M8f6Ff-tv:-N5_NLft2p1M8f6Ff-tw:b-ly6if7) ([raw file](https://github.com/pmem/rpma/blob/a9c54f9e170e243bff8102bbf054995cbd6bbbcc/tests/multithreaded/mr/rpma_mr_dereg.c#L93)):*
> ```C
>  */
> static void
> fini(unsigned id, void *prestate, void **state_ptr,
> ```

Shouldn't this be a seq_fini() function?

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1873)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`tests/multithreaded/mr/rpma_mr_dereg.c` line 93 at r2](https://reviewable.io/reviews/pmem/rpma/1873#-N5_NLft2p1M8f6Ff-tv:-N5_i6yNB0NrrC9-F_dt:b3c1p4r) ([raw file](https://github.com/pmem/rpma/blob/a9c54f9e170e243bff8102bbf054995cbd6bbbcc/tests/multithreaded/mr/rpma_mr_dereg.c#L93)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Shouldn't this be a seq_fini() function?
</blockquote></details>

I think you are right because there is a calloc in seq_init. @ldorau ?

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1873)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[`tests/multithreaded/mr/rpma_mr_dereg.c` line 93 at r2](https://reviewable.io/reviews/pmem/rpma/1873#-N5_NLft2p1M8f6Ff-tv:-N5cseH7BvOyqWvpRfFr:b-hct9af) ([raw file](https://github.com/pmem/rpma/blob/a9c54f9e170e243bff8102bbf054995cbd6bbbcc/tests/multithreaded/mr/rpma_mr_dereg.c#L93)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

I think you are right because there is a calloc in seq_init. @ldorau ?
</blockquote></details>

It does not matter in this case, because it calls free() only, but for the sake of consistency let's change it to seq_fini().

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1873)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1873)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[`tests/multithreaded/mr/rpma_mr_dereg.c` line 93 at r2](https://reviewable.io/reviews/pmem/rpma/1873#-N5_NLft2p1M8f6Ff-tv:-N5dEcS32R7PZTLpFvQk:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a9c54f9e170e243bff8102bbf054995cbd6bbbcc/tests/multithreaded/mr/rpma_mr_dereg.c#L93)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It does not matter in this case, because it calls free() only, but for the sake of consistency let's change it to seq_fini().
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1873#-:-N5dEnym4NzpxW1zYQkf:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Review by osalyk — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1873)* status: all files reviewed, 4 unresolved discussions (waiting on @haichangsi)

___
*[`tests/multithreaded/mr/rpma_mr_dereg.c` line 50 at r3](https://reviewable.io/reviews/pmem/rpma/1873#-N5dhlEb2El_RElYxWjW:-N5dhlEb2El_RElYxWjX:b-1m9nql) ([raw file](https://github.com/pmem/rpma/blob/ccecb6a31b6dc75439b8840ae31ec909d1baa840/tests/multithreaded/mr/rpma_mr_dereg.c#L50)):*
> ```C
> void
> seq_init(unsigned id, void *prestate, void **state_ptr,
> 		struct mtt_result *result)
> ```

One line
___
*[`tests/multithreaded/mr/rpma_mr_dereg.c` line 68 at r3](https://reviewable.io/reviews/pmem/rpma/1873#-N5dhnfT0Av-Qs5YmX0Z:-N5dhnfT0Av-Qs5YmX0_:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/ccecb6a31b6dc75439b8840ae31ec909d1baa840/tests/multithreaded/mr/rpma_mr_dereg.c#L68)):*
> ```C
> 
> 	int ret = rpma_mr_reg(pr->peer, st->mr_ptr, KILOBYTE,
> 			RPMA_MR_USAGE_READ_SRC, &st->mr);
> ```

.
___
*[`tests/multithreaded/mr/rpma_mr_dereg.c` line 78 at r3](https://reviewable.io/reviews/pmem/rpma/1873#-N5dhoVf47Hqh-5nvPzp:-N5dhoVf47Hqh-5nvPzq:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/ccecb6a31b6dc75439b8840ae31ec909d1baa840/tests/multithreaded/mr/rpma_mr_dereg.c#L78)):*
> ```C
> static void
> thread(unsigned id, void *prestate, void *state,
> 		struct mtt_result *result)
> ```

.
___
*[`tests/multithreaded/mr/rpma_mr_dereg.c` line 94 at r3](https://reviewable.io/reviews/pmem/rpma/1873#-N5dhqfY04WIyNh7p_Cl:-N5dhqfY04WIyNh7p_Cm:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/ccecb6a31b6dc75439b8840ae31ec909d1baa840/tests/multithreaded/mr/rpma_mr_dereg.c#L94)):*
> ```C
> static void
> seq_fini(unsigned id, void *prestate, void **state_ptr,
> 		struct mtt_result *tr)
> ```

.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1873)* status: all files reviewed, 4 unresolved discussions (waiting on @osalyk)

**Review by osalyk — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1873)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1873#-:-N5eAWYC2nnwXe8bHznp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1873)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1873)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
