### PR TITLE
common: make CMake more verbose

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
don't hide info while looking for packages, it helps debugging.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/545)

### CODE REVIEW

**Comment by lukaszstolarczuk** [comment]
BTW, i was checking our projects with https://github.com/nlohmann/cmake_min_version and it seems everything is all right with rpma and examples (built as standalone projects)

**Review by ldorau — APPROVED** [review]
Thanks!

:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/545#-:-MJ1hcE8-T2opSKAUveG:b-69ief5)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
@lukaszstolarczuk 

But I got:

```
$ python ./cmake_min_version.py ~/work/rpma
Found 18 CMake binaries from directory tools

[  0%] CMake 3.9.6  ✔ works
[ 20%] CMake 3.4.3  ✘ error
[ 40%] CMake 3.6.3  ✘ error
[ 60%] CMake 3.7.2  ✔ works
[100%] Minimal working version: CMake 3.7.2

cmake_minimum_required(VERSION 3.7.2)
```

???

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/545#-:-MJ24O1O4iIig1WjD5-z:b-7b6a4d)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by ldorau** [comment]
> @lukaszstolarczuk
> 
> But I got:
> 
> ```
> $ python ./cmake_min_version.py ~/work/rpma
> Found 18 CMake binaries from directory tools
> 
> [  0%] CMake 3.9.6  ✔ works
> [ 20%] CMake 3.4.3  ✘ error
> [ 40%] CMake 3.6.3  ✘ error
> [ 60%] CMake 3.7.2  ✔ works
> [100%] Minimal working version: CMake 3.7.2
> 
> cmake_minimum_required(VERSION 3.7.2)
> ```
> 
> ???
> 
> > _[Reviewable](https://reviewable.io/reviews/pmem/rpma/545#-:-MJ24O1O4iIig1WjD5-z:b-7b6a4d)_ status: :shipit: complete! all files reviewed, all discussions resolved

It works:

```
$ python3 ./cmake_min_version.py ~/work/rpma
Found 18 CMake binaries from directory tools

[  0%] CMake 3.9.6  ✔ works
[ 20%] CMake 3.4.3  ✔ works
[ 40%] CMake 3.2.3  ✘ error
       CMakeLists.txt:6 (cmake_minimum_required)
[ 75%] CMake 3.3.2  ✔ works
[100%] Minimal working version: CMake 3.3.2

cmake_minimum_required(VERSION 3.3.2)
```

**Review by ldorau — APPROVED** [review]
@grom72 @osalyk please review

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/545#-:-MJ3LpaM-zI1D-2lc2R9:bg7id4e)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/545#-:-MJ6QbtbAkhCQHzIDu56:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
