### PR TITLE
common: add tests for Release build type to CI

### PR DESCRIPTION
**Pull request by ldorau**
- [x] requires #297

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/292)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
how do two builds influence coverage?

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/292#-:-MFaJVmd4UKj0vNDk_3z:b-93d923)* status: 0 of 1 files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
I do not know yet - the build fails now.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/292#-:-MFdMe2r67mBdU2ZrfP2:b5ma7oe)* status: 0 of 1 files reviewed, all discussions resolved

**Comment by ldorau** [comment]
This PR requires #297.

**Review by janekmi — COMMENTED** [review]
> Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/292)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 3 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/292)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 3 files at r3, 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/292#-:-MFpwPh-4cFUWxs3EgKT:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/292)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tests/unit/log_default/CMakeLists.txt, line 32 at r4](https://reviewable.io/reviews/pmem/rpma/292#-MFzAA_KAa0BvH7ATESK:-MFzAA_L0WxIIlyjWlSf:bwhjiau) ([raw file](https://github.com/pmem/rpma/blob/e32d33cba672382777156367f08c5ea40dd0d722/tests/unit/log_default/CMakeLists.txt#L32)):*
> ```CMake
> 
> build_log_default(init-fini)
> build_log_default(function)
> ```

shall or shall not we have one line empty at the end?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/292)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[tests/unit/log_default/CMakeLists.txt, line 32 at r4](https://reviewable.io/reviews/pmem/rpma/292#-MFzAA_KAa0BvH7ATESK:-MG2V7Vz9eo3aBQzIMPx:b-pzlrf) ([raw file](https://github.com/pmem/rpma/blob/e32d33cba672382777156367f08c5ea40dd0d722/tests/unit/log_default/CMakeLists.txt#L32)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

shall or shall not we have one line empty at the end?
</blockquote></details>

There should be one

**Review by grom72 — COMMENTED** [review]
:goat: `

> Reviewed 3 of 3 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/292#-:-MG-QpQn0VQjeul8BWxX:b-estq9s)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tests/unit/log_default/CMakeLists.txt, line 32 at r4](https://reviewable.io/reviews/pmem/rpma/292#-MFzAA_KAa0BvH7ATESK:-MG3EI8f-I435T70QKmI:b-6ysyh1) ([raw file](https://github.com/pmem/rpma/blob/e32d33cba672382777156367f08c5ea40dd0d722/tests/unit/log_default/CMakeLists.txt#L32)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

There should be one
</blockquote></details>

Missing empty line at the end of the file ...

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/292)* status: 1 of 2 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[tests/unit/log_default/CMakeLists.txt, line 32 at r4](https://reviewable.io/reviews/pmem/rpma/292#-MFzAA_KAa0BvH7ATESK:-MG3On-h4PsraNxef_jf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e32d33cba672382777156367f08c5ea40dd0d722/tests/unit/log_default/CMakeLists.txt#L32)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Missing empty line at the end of the file ...
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/292#-:-MG3PB434s2QedX5AvBF:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Pull request merged**
