### PR TITLE
rpma: only one librpma API call is not thread-safe

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1774)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
;) 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1774#-:-N3-_kVz6KcKcLwHJ0WP:b2nh565)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1774#-:-N3-_pbg8mwFGs2jpxQF:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1774)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1774#-:-N30-dvDBOGc5_cUOfXi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
