### PR TITLE
rpma: add doc + ut for set/get_compl_channel

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1649)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1649)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1649)* status: 2 of 4 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1649)* status: all files reviewed, 7 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[src/include/librpma.h, line 1367 at r1](https://reviewable.io/reviews/pmem/rpma/1649#-N-NMzUI9GBY8XxKF9VF:-N-NMzUI9GBY8XxKF9VG:bmu75mm) ([raw file](https://github.com/pmem/rpma/blob/84d709de08d33bd63afe82489ce302ec5dfdca18/src/include/librpma.h#L1367)):*
> ```objc
> 
> /** 3
>  * rpma_conn_cfg_get_compl_channel - get if the completion channel
> ```

completion event channel



_Code quote:_
```objc
completion channel
```
___
*[src/include/librpma.h, line 1379 at r1](https://reviewable.io/reviews/pmem/rpma/1649#-N-NO6GJ5UkLzhhjBiVG:-N-NO6GJ5UkLzhhjBiVH:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/84d709de08d33bd63afe82489ce302ec5dfdca18/src/include/librpma.h#L1379)):*
> ```objc
>  *
>  * DESCRIPTION
>  * rpma_conn_cfg_get_compl_channel() gets if the completion channel
> ```

.



_Code quote:_
```objc
completion channel
```
___
*[src/include/librpma.h, line 1392 at r1](https://reviewable.io/reviews/pmem/rpma/1649#-N-NNHG06fjfeVpwKJW1:-N-NNHG06fjfeVpwKJW2:b-i3tp9q) ([raw file](https://github.com/pmem/rpma/blob/84d709de08d33bd63afe82489ce302ec5dfdca18/src/include/librpma.h#L1392)):*
> ```objc
>  * - RPMA_E_INVAL - cfg or shared is NULL
>  *
>  * SEE ALSO
> ```

missing references to ``rdma_conn_wait()``which should be a place where the new completion events mechanism is described.



_Code quote:_
```objc
SEE ALSO
```
___
*[src/include/librpma.h, line 1400 at r1](https://reviewable.io/reviews/pmem/rpma/1649#-N-NO8IyBxwMZf8M3_wQ:-N-NO8IyBxwMZf8M3_wR:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/84d709de08d33bd63afe82489ce302ec5dfdca18/src/include/librpma.h#L1400)):*
> ```objc
> 
> /** 3
>  * rpma_conn_cfg_set_compl_channel - set if the completion channel
> ```

.



_Code quote:_
```objc
completion channel
```
___
*[src/include/librpma.h, line 1412 at r1](https://reviewable.io/reviews/pmem/rpma/1649#-N-NOBCf7jyjuSO-l7Qj:-N-NOBCf7jyjuSO-l7Qk:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/84d709de08d33bd63afe82489ce302ec5dfdca18/src/include/librpma.h#L1412)):*
> ```objc
>  *
>  * DESCRIPTION
>  * rpma_conn_cfg_set_compl_channel() sets if the completion channel
> ```

.



_Code quote:_
```objc
completion channel
```
___
*[src/include/librpma.h, line 1424 at r1](https://reviewable.io/reviews/pmem/rpma/1649#-N-NOD2tDpXQ9TI3kz64:-N-NOD2tDpXQ9TI3kz65:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/84d709de08d33bd63afe82489ce302ec5dfdca18/src/include/librpma.h#L1424)):*
> ```objc
>  * - RPMA_E_INVAL - cfg is NULL
>  *
>  * SEE ALSO
> ```

.



_Code quote:_
```objc
SEE ALSO
```
___
*[tests/unit/conn_cfg/conn_cfg-compl_channel.c, line 59 at r1](https://reviewable.io/reviews/pmem/rpma/1649#-N-NMFOjDp_7mpuQDU5l:-N-NMFOjDp_7mpuQDU5m:b435kbz) ([raw file](https://github.com/pmem/rpma/blob/84d709de08d33bd63afe82489ce302ec5dfdca18/tests/unit/conn_cfg/conn_cfg-compl_channel.c#L59)):*
> ```C
> 
> /*
>  * compl_channel__lifecycle -- happy day scenario
> ```

Shall we test the default value? 
Shall we cover the false value also? 



_Code quote:_
```C
happy day scenario
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1649)* status: all files reviewed, 7 unresolved discussions (waiting on @ldorau and @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1649)* status: 3 of 4 files reviewed, 7 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/include/librpma.h, line 1367 at r1](https://reviewable.io/reviews/pmem/rpma/1649#-N-NMzUI9GBY8XxKF9VF:-N-NWUT89LtRUQiOkASe:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/84d709de08d33bd63afe82489ce302ec5dfdca18/src/include/librpma.h#L1367)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

completion event channel
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1379 at r1](https://reviewable.io/reviews/pmem/rpma/1649#-N-NO6GJ5UkLzhhjBiVG:-N-NWXNU8vD4yOQsX_1X:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/84d709de08d33bd63afe82489ce302ec5dfdca18/src/include/librpma.h#L1379)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1392 at r1](https://reviewable.io/reviews/pmem/rpma/1649#-N-NNHG06fjfeVpwKJW1:-N-NWpgJ4eHNmkD1JtRj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/84d709de08d33bd63afe82489ce302ec5dfdca18/src/include/librpma.h#L1392)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

missing references to ``rdma_conn_wait()``which should be a place where the new completion events mechanism is described.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1400 at r1](https://reviewable.io/reviews/pmem/rpma/1649#-N-NO8IyBxwMZf8M3_wQ:-N-NWsfGC9G5dRp0JM-S:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/84d709de08d33bd63afe82489ce302ec5dfdca18/src/include/librpma.h#L1400)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1412 at r1](https://reviewable.io/reviews/pmem/rpma/1649#-N-NOBCf7jyjuSO-l7Qj:-N-NWvJc2AeB6EUJCrW7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/84d709de08d33bd63afe82489ce302ec5dfdca18/src/include/librpma.h#L1412)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1424 at r1](https://reviewable.io/reviews/pmem/rpma/1649#-N-NOD2tDpXQ9TI3kz64:-N-NX-NNB_3bPOhY5Z5J:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/84d709de08d33bd63afe82489ce302ec5dfdca18/src/include/librpma.h#L1424)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[tests/unit/conn_cfg/conn_cfg-compl_channel.c, line 59 at r1](https://reviewable.io/reviews/pmem/rpma/1649#-N-NMFOjDp_7mpuQDU5l:-N-N_MHhA95j_dO2sAqK:b5l9g9k) ([raw file](https://github.com/pmem/rpma/blob/84d709de08d33bd63afe82489ce302ec5dfdca18/tests/unit/conn_cfg/conn_cfg-compl_channel.c#L59)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Shall we test the default value? 
Shall we cover the false value also? 
</blockquote></details>

In other tests we don't do this.

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1649)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ldorau and @osalyk)

___
*[tests/unit/conn_cfg/conn_cfg-compl_channel.c, line 59 at r1](https://reviewable.io/reviews/pmem/rpma/1649#-N-NMFOjDp_7mpuQDU5l:-N-NaXqiBs3k46XgCGDJ:b2vllnj) ([raw file](https://github.com/pmem/rpma/blob/84d709de08d33bd63afe82489ce302ec5dfdca18/tests/unit/conn_cfg/conn_cfg-compl_channel.c#L59)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

In other tests we don't do this.
</blockquote></details>

But here you mention it in the documentation above ;).

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1649)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau and @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1649)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[tests/unit/conn_cfg/conn_cfg-compl_channel.c, line 59 at r1](https://reviewable.io/reviews/pmem/rpma/1649#-N-NMFOjDp_7mpuQDU5l:-N-NhXz2CIDjCqy_8Mqj:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/84d709de08d33bd63afe82489ce302ec5dfdca18/tests/unit/conn_cfg/conn_cfg-compl_channel.c#L59)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

But here you mention it in the documentation above ;).
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1649)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @osalyk)

___
*[src/include/librpma.h, line 1393 at r3](https://reviewable.io/reviews/pmem/rpma/1649#-N-Ns-jSAwYj6AkpujEc:-N-Ns-jSAwYj6AkpujEd:b3kre) ([raw file](https://github.com/pmem/rpma/blob/95cedf6a5bf2a5ddef62434fe6835334e9919c00/src/include/librpma.h#L1393)):*
> ```objc
>  *
>  * SEE ALSO
>  * rpma_conn_cfg_new(3), rdma_conn_wait(3), rpma_conn_cfg_set_compl_channel(3),
> ```

?



_Code quote:_
```objc
rdma_conn_wait
```
___
*[src/include/librpma.h, line 1413 at r3](https://reviewable.io/reviews/pmem/rpma/1649#-N-NsRDmB_-YXcruBWwM:-N-NsRDmB_-YXcruBWwN:bo8n33e) ([raw file](https://github.com/pmem/rpma/blob/95cedf6a5bf2a5ddef62434fe6835334e9919c00/src/include/librpma.h#L1413)):*
> ```objc
>  * DESCRIPTION
>  * rpma_conn_cfg_set_compl_channel() sets if the completion event channel
>  * is shared by CQ and RCQ. If this function is not called, the shared has
> ```

What is `the shared` ?



_Code quote:_
```objc
the shared
```
___
*[src/include/librpma.h, line 1413 at r3](https://reviewable.io/reviews/pmem/rpma/1649#-N-Nsg8P0SI_MoKiCFEI:-N-Nsg8P0SI_MoKiCFEJ:b-jh0ap7) ([raw file](https://github.com/pmem/rpma/blob/95cedf6a5bf2a5ddef62434fe6835334e9919c00/src/include/librpma.h#L1413)):*
> ```objc
>  * DESCRIPTION
>  * rpma_conn_cfg_set_compl_channel() sets if the completion event channel
>  * is shared by CQ and RCQ. If this function is not called, the shared has
> ```

```
 * is shared by CQ and RCQ. If this function is not called,
 * the completion event channel is not shared by CQ and RCQ by default
 * (it is set by rpma_conn_cfg_new(3)).
```



_Code quote:_
```objc
 * is shared by CQ and RCQ. If this function is not called, the shared has
 * the default value (false) set by rpma_conn_cfg_new(3).
```
___
*[src/include/librpma.h, line 1426 at r3](https://reviewable.io/reviews/pmem/rpma/1649#-N-NsH7e94xRjch5Qmx7:-N-NsH7e94xRjch5Qmx8:b3kre) ([raw file](https://github.com/pmem/rpma/blob/95cedf6a5bf2a5ddef62434fe6835334e9919c00/src/include/librpma.h#L1426)):*
> ```objc
>  *
>  * SEE ALSO
>  * rpma_conn_cfg_new(3), rdma_conn_wait(3), rpma_conn_cfg_get_compl_channel(3),
> ```

?



_Code quote:_
```objc
rdma_conn_wait
```
___
*[tests/unit/conn_cfg/conn_cfg-compl_channel.c, line 62 at r3](https://reviewable.io/reviews/pmem/rpma/1649#-N-NuC-Z8HMoWXNgg5M7:-N-NuC-_9baHxo9LZ4w9:b-yq5wxf) ([raw file](https://github.com/pmem/rpma/blob/95cedf6a5bf2a5ddef62434fe6835334e9919c00/tests/unit/conn_cfg/conn_cfg-compl_channel.c#L62)):*
> ```C
>  */
> static void
> get__success(void **cstate_ptr)
> ```

Maybe `get_default__success`  ?



_Code quote:_
```C
get__success
```

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1649)* status: all files reviewed, 5 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[src/include/librpma.h, line 1393 at r3](https://reviewable.io/reviews/pmem/rpma/1649#-N-Ns-jSAwYj6AkpujEc:-N-O1tyl3tT-NOV7C_iA:b-7jij7k) ([raw file](https://github.com/pmem/rpma/blob/95cedf6a5bf2a5ddef62434fe6835334e9919c00/src/include/librpma.h#L1393)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

?
</blockquote></details>

rpma_conn_wait
___
*[src/include/librpma.h, line 1426 at r3](https://reviewable.io/reviews/pmem/rpma/1649#-N-NsH7e94xRjch5Qmx7:-N-O1lnR1BPIrhwyLCVo:b-fasama) ([raw file](https://github.com/pmem/rpma/blob/95cedf6a5bf2a5ddef62434fe6835334e9919c00/src/include/librpma.h#L1426)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

?
</blockquote></details>

rpma_conn_wait(3)

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1649)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1649#-:-N-RxSuM986Ye4AIOH4M:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1649)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1649)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[src/include/librpma.h, line 1413 at r4](https://reviewable.io/reviews/pmem/rpma/1649#-N-U0YfN-rlcFc4vMEkP:-N-U0YfN-rlcFc4vMEkQ:bhtdzhc) ([raw file](https://github.com/pmem/rpma/blob/c21a1e0f97f783a811a6e57d64be8a772d774e69/src/include/librpma.h#L1413)):*
> ```objc
>  * DESCRIPTION
>  * rpma_conn_cfg_set_compl_channel() sets if the completion event channel
>  * is shared by CQ and RCQ. If this function is not called,
> ```

The completion event channel is by default not shared by CQ and RCQ. See rpma_conn_cfg_new(3) for details.



_Suggestion:_
```objc
 If this function is not called,
 * the completion event channel is not shared by CQ and RCQ by default
 * (it is set by rpma_conn_cfg_new(3)).
```

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1649)* status: all files reviewed, 4 unresolved discussions (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1649#-N-U1czH3M33Dt6vxuXW:-N-U1czH3M33Dt6vxuXX:b3r6xoz) (no related file):*
@osalyk please extend ``rpma_conn_cfg_new()`` documentation with default value of  shared completion channel.

---
___
*[src/include/librpma.h, line 1224 at r4](https://reviewable.io/reviews/pmem/rpma/1649#-N-U2HIi3hNpJ7qYZOA7:-N-U2HIi3hNpJ7qYZOA8:bsmo76p) ([raw file](https://github.com/pmem/rpma/blob/c21a1e0f97f783a811a6e57d64be8a772d774e69/src/include/librpma.h#L1224)):*
> ```objc
>  *	.sq_size = 10
>  *	.rq_size = 10
>  *
> ```

shared completion channel documentation is missing

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1649)* status: all files reviewed, 4 unresolved discussions (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1649)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1649#-N-U1czH3M33Dt6vxuXW:-N-WRDbY4CfoQtBB6R1Y:b-896fix) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

@haichangsi please extend ``rpma_conn_cfg_new()`` documentation with default value of  shared completion channel.
</blockquote></details>

Done.

---
___
*[src/include/librpma.h, line 1224 at r4](https://reviewable.io/reviews/pmem/rpma/1649#-N-U2HIi3hNpJ7qYZOA7:-N-WRExV5pQYDfDNKrTR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c21a1e0f97f783a811a6e57d64be8a772d774e69/src/include/librpma.h#L1224)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

shared completion channel documentation is missing
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1413 at r4](https://reviewable.io/reviews/pmem/rpma/1649#-N-U-KS-53WZkRjf4_93:-N-WRRqh6UeO2RManZtA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c21a1e0f97f783a811a6e57d64be8a772d774e69/src/include/librpma.h#L1413)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

is shared by CQ and RCQ or not.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1413 at r4](https://reviewable.io/reviews/pmem/rpma/1649#-N-U0YfN-rlcFc4vMEkP:-N-WRf5H3mRGUAPNyDwC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c21a1e0f97f783a811a6e57d64be8a772d774e69/src/include/librpma.h#L1413)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

The completion event channel is by default not shared by CQ and RCQ. See rpma_conn_cfg_new(3) for details.
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1649)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72, @haichangsi, and @osalyk)

___
*[src/include/librpma.h, line 1416 at r5](https://reviewable.io/reviews/pmem/rpma/1649#-N-WaH7kChqU2J3tOWkJ:-N-WaH7kChqU2J3tOWkK:b-xlgdgj) ([raw file](https://github.com/pmem/rpma/blob/f72229a1149fb6c5233d88ac36ece29e52013ee2/src/include/librpma.h#L1416)):*
> ```objc
>  * DESCRIPTION
>  * rpma_conn_cfg_set_compl_channel() sets if the completion event channel
>  * is shared by CQ and RCQ or not. The completion event channel is by default
> ```

```
 * ... The completion event channel is not shared by CQ and RCQ by default. 
```
(break line as needed) instead of:
```
 * ... The completion event channel is by default
 * not shared by CQ and RCQ. 
```



_Code quote:_
```objc
 * is shared by CQ and RCQ or not. The completion event channel is by default
 * not shared by CQ and RCQ. See rpma_conn_cfg_new(3) for details.
```

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1649)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[src/include/librpma.h, line 1416 at r5](https://reviewable.io/reviews/pmem/rpma/1649#-N-WaH7kChqU2J3tOWkJ:-N-Wcnxn8-eU1ATyDS-3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f72229a1149fb6c5233d88ac36ece29e52013ee2/src/include/librpma.h#L1416)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
 * ... The completion event channel is not shared by CQ and RCQ by default. 
```
(break line as needed) instead of:
```
 * ... The completion event channel is by default
 * not shared by CQ and RCQ. 
```

</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1649)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @haichangsi)

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1649)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @haichangsi)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1649#-:-N-WgjEg-h41qFrCZPMO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1649)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
