### PR TITLE
tools: reorder modes in SETTINGS_BY_MODE

### PR DESCRIPTION
**Pull request by ldorau**
Reorder modes in SETTINGS_BY_MODE so that
they match the ones from ib_read.sh.
It will simplify implementing other things.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1373)

### CODE REVIEW

**Comment by ldorau** [comment]
This patch reorders only the code and does not introduce any changes.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1373#-:-MplLVrn7AZhCw0SCJQ9:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1373)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1373#-MplLa_p3rNoXe8QY3Rz:-MplLa_p3rNoXe8QY3S-:b8b79qu) (no related file):*
:lgtm_cancel: 

---

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1373)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1373#-MplLa_p3rNoXe8QY3Rz:-MplLnDT3x1bljQyDCY-:b5fsa1h) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

:lgtm_cancel: 
</blockquote></details>

I need more time. Don't want to rush.

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1373)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1373#-MplLa_p3rNoXe8QY3Rz:-MplML8h28CIjret0qjt:b32w0x) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I need more time. Don't want to rush.
</blockquote></details>

OK

---

**Review by janekmi — APPROVED** [review]
:lgtm_strong: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1373#-:-MpnNQjADhQEeVKrFdAx:b-uwkowd)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1373#-:-Mpp3AKs11FUGOWHa1zO:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by haichangsi — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1373#-:-MppFyKl6oSMS53fGblZ:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
