### PR TITLE
rpma: update CHANGELOG

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1506)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1506)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[CHANGELOG.md, line 11 at r1](https://reviewable.io/reviews/pmem/rpma/1506#-MttL8KPEmpuo2Eyg1uh:-MttL8KPEmpuo2Eyg1ui:b-yspa1r) ([raw file](https://github.com/pmem/rpma/blob/3052eac212c0a388ecddd6ccdcb2b2c3fcae0cd1/CHANGELOG.md#L11)):*
> ```Markdown
> ### Added
> - Possibility to give an advice about an address range in a memory registration [#1220].
> - Separate receive CQ [#1080].
> ```

Completion Queue (CQ)



_Code quote:_
```Markdown
CQ
```
___
*[CHANGELOG.md, line 47 at r1](https://reviewable.io/reviews/pmem/rpma/1506#-MttLgfXDzYVX7UXaaqN:-MttLgfXDzYVX7UXaaqO:b-hluchn) ([raw file](https://github.com/pmem/rpma/blob/3052eac212c0a388ecddd6ccdcb2b2c3fcae0cd1/CHANGELOG.md#L47)):*
> ```Markdown
> 
> ### Fixed
> - rpma_mr_reg() supports WARP protocol [#1044].
> ```

In my opinion, it is not a fix but new functionality. 
Before that iWARP support was not possible.
To be moved to  Add section:
```Support for iWARPM protocol [#1044]```



_Suggestion:_
```Markdown
- rpma_mr_reg() supports WARP protocol [#1044]
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1506)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[CHANGELOG.md, line 11 at r1](https://reviewable.io/reviews/pmem/rpma/1506#-MttL8KPEmpuo2Eyg1uh:-MtviQgqA9sc6ihZjShu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3052eac212c0a388ecddd6ccdcb2b2c3fcae0cd1/CHANGELOG.md#L11)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Completion Queue (CQ)
</blockquote></details>

Done.
___
*[CHANGELOG.md, line 47 at r1](https://reviewable.io/reviews/pmem/rpma/1506#-MttLgfXDzYVX7UXaaqN:-Mtvi8Nb2hnVRsASyKKn:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3052eac212c0a388ecddd6ccdcb2b2c3fcae0cd1/CHANGELOG.md#L47)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

In my opinion, it is not a fix but new functionality. 
Before that iWARP support was not possible.
To be moved to  Add section:
```Support for iWARPM protocol [#1044]```
</blockquote></details>

Done.

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1506)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
:goat: so far

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1506#-:-MtvsMPrAWzCNmB3X1K4:bu2fge9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
MarkDown preview: https://github.com/ldorau/rpma/blob/rpma-update-CHANGELOG/CHANGELOG.md

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1506#-:-MtwAenz6DxDoZWgUfoB:bnxoq9u)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1506)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[CHANGELOG.md, line 10 at r3](https://reviewable.io/reviews/pmem/rpma/1506#-MtwKLRFB-fBWR8_XaHi:-MtwKLRFB-fBWR8_XaHj:b3djnav) ([raw file](https://github.com/pmem/rpma/blob/48b8c3f110d5ef472a7c9e696c81831295323aa2/CHANGELOG.md#L10)):*
> ```Markdown
> ## [Unreleased]
> ### Added
> - Possibility to give an advice about an address range in a memory registration ([#1220][1220]).
> ```

Unblock FileSystemDAX performance by adding the possibility to use ibv_advice_mr for registered memory



_Code quote:_
```Markdown
Possibility to give an advice about an address range in a memory registration
```
___
*[CHANGELOG.md, line 16 at r3](https://reviewable.io/reviews/pmem/rpma/1506#-MtwOg4g73_KC7mQD-oE:-MtwOg4g73_KC7mQD-oF:b-truxcj) ([raw file](https://github.com/pmem/rpma/blob/48b8c3f110d5ef472a7c9e696c81831295323aa2/CHANGELOG.md#L16)):*
> ```Markdown
> - Send operation with immediate data ([#713][713]).
> - Handling the RDMA_CM_EVENT_REJECTED event ([#802][802]).
> - The [ddio.sh script][ddio] to toggle and query the DDIO (Intel&reg Data Direct I/O Technology) state per PCIe root port on Intel&reg Cascade Lake platforms ([#597][597]).
> ```

Remove here - add at the end as separate section: 'Tools'



_Code quote:_
```Markdown
- The [ddio.sh script][ddio] to toggle and query the DDIO (Intel&reg Data Direct I/O Technology) state per PCIe root port on Intel&reg Cascade Lake platforms ([#597][597]).
- [Benchmarking framework][bench] for the librpma.
```
___
*[CHANGELOG.md, line 18 at r3](https://reviewable.io/reviews/pmem/rpma/1506#-MtwQDv16be44-xinh-E:-MtwQDv16be44-xinh-F:b-j2z97e) ([raw file](https://github.com/pmem/rpma/blob/48b8c3f110d5ef472a7c9e696c81831295323aa2/CHANGELOG.md#L18)):*
> ```Markdown
> - The [ddio.sh script][ddio] to toggle and query the DDIO (Intel&reg Data Direct I/O Technology) state per PCIe root port on Intel&reg Cascade Lake platforms ([#597][597]).
> - [Benchmarking framework][bench] for the librpma.
> - Support for many [Linux distributions and versions][distros] each of them tested [once a day with CI][nightly]:
> ```

I know it is not according to guidelines, but what if we make a separate section at the bottom with the title 'Supported operating systems.



_Code quote:_
```Markdown
- Support for many [Linux distributions and versions][distros] each of them tested [once a day with CI][nightly]:
  - Ubuntu 18.04, 20.04, 21.04, 21.10 and Rolling,
  - Debian 9-11, Stable, Testing and Experimental,
  - Fedora 26-34,
  - CentOS 7 and 8,
  - Rocky Linux 8.4,
  - VzLinux 8,
  - OpenSUSE Leap and Tumbleweed,
  - Arch Linux.
```
___
*[CHANGELOG.md, line 42 at r3](https://reviewable.io/reviews/pmem/rpma/1506#-MtwO8aY9FpdtxhjVLym:-MtwO8aY9FpdtxhjVLyn:b-xncv6m) ([raw file](https://github.com/pmem/rpma/blob/48b8c3f110d5ef472a7c9e696c81831295323aa2/CHANGELOG.md#L42)):*
> ```Markdown
>   - rpma_send_with_imm - initiates the send operation with immediate data,
>   - rpma_write_with_imm - initiates the write operation with immediate data.
> - enum rpma_conn_event: RPMA_CONN_REJECTED ([#802][802]).
> ```

do we have to explicitly show it here if it is already mentioned above?
or can we combine this information where #802 is mentioned for the first time?



_Code quote:_
```Markdown
- enum rpma_conn_event: RPMA_CONN_REJECTED ([#802][802]).
```
___
*[CHANGELOG.md, line 43 at r3](https://reviewable.io/reviews/pmem/rpma/1506#-MtwOYIC7Je3lMlFZmu0:-MtwOYIC7Je3lMlFZmu1:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/48b8c3f110d5ef472a7c9e696c81831295323aa2/CHANGELOG.md#L43)):*
> ```Markdown
>   - rpma_write_with_imm - initiates the write operation with immediate data.
> - enum rpma_conn_event: RPMA_CONN_REJECTED ([#802][802]).
> - enum rpma_op: RPMA_OP_RECV_RDMA_WITH_IMM ([#856][856]).
> ```

.



_Code quote:_
```Markdown
- enum rpma_op: RPMA_OP_RECV_RDMA_WITH_IMM ([#856][856]).
```
___
*[CHANGELOG.md, line 44 at r3](https://reviewable.io/reviews/pmem/rpma/1506#-MtwOZZf3-x03hMgiTo3:-MtwOZZf3-x03hMgiTo4:b-tpsqa8) ([raw file](https://github.com/pmem/rpma/blob/48b8c3f110d5ef472a7c9e696c81831295323aa2/CHANGELOG.md#L44)):*
> ```Markdown
> - enum rpma_conn_event: RPMA_CONN_REJECTED ([#802][802]).
> - enum rpma_op: RPMA_OP_RECV_RDMA_WITH_IMM ([#856][856]).
> ```

[EMPTY LINE AS SEPARATOR]
- Tools
    - The [ddio.sh script][ddio] to toggle and query the DDIO (Intel&reg Data Direct I/O Technology) state per PCIe root port on Intel&reg Cascade Lake platforms ([#597][597]).
    - [Benchmarking framework][bench] for the librpma.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1506)* status: all files reviewed, 6 unresolved discussions (waiting on @ldorau)

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1506)* status: all files reviewed, 4 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[CHANGELOG.md, line 32 at r4](https://reviewable.io/reviews/pmem/rpma/1506#-Mtx1RzB7tO76I1qllYK:-Mtx1RzB7tO76I1qllYL:b-p42eqb) ([raw file](https://github.com/pmem/rpma/blob/89fc784067dfba9172ea72e524761bbb42cc26b8/CHANGELOG.md#L32)):*
> ```Markdown
>   - rpma_send_with_imm - initiates the send operation with immediate data,
>   - rpma_write_with_imm - initiates the write operation with immediate data.
> - Tools:
> ```

separate line as it is separate topic



_Code quote:_
```Markdown
- Tools:
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1506)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[CHANGELOG.md, line 32 at r4](https://reviewable.io/reviews/pmem/rpma/1506#-Mtx1RzB7tO76I1qllYK:-Mtx4JL-0gba7mzPNN7B:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/89fc784067dfba9172ea72e524761bbb42cc26b8/CHANGELOG.md#L32)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

separate line as it is separate topic
</blockquote></details>

Done.

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1506)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ldorau)

___
*[CHANGELOG.md, line 11 at r5](https://reviewable.io/reviews/pmem/rpma/1506#-Mtx6TqBD7t0UzJ1Fan6:-Mtx6TqBD7t0UzJ1Fan7:b-yd36z) ([raw file](https://github.com/pmem/rpma/blob/e33d3f7235c91aff9ffdcf2f9f8f1e16b8ac1603/CHANGELOG.md#L11)):*
> ```Markdown
> ### Added
> - Unblock performance of File System DAX by adding the possibility to use ibv_advice_mr() for registered memory ([#1220][1220]).
> - Separate receive Completion Queue (CQ) ([#1080][1080]).
> ```

```completion queue``` please,
 as we do not use capital letters anywhere in the code and documentation



_Code quote:_
```Markdown
Completion Queue
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1506)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[CHANGELOG.md, line 11 at r5](https://reviewable.io/reviews/pmem/rpma/1506#-Mtx6TqBD7t0UzJ1Fan6:-Mtx7vFW5uRdlTk2UqdF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e33d3f7235c91aff9ffdcf2f9f8f1e16b8ac1603/CHANGELOG.md#L11)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

```completion queue``` please,
 as we do not use capital letters anywhere in the code and documentation
</blockquote></details>

Done.

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1506)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[CHANGELOG.md, line 35 at r6](https://reviewable.io/reviews/pmem/rpma/1506#-MtxBPPJEHNr5Wqpq64W:-MtxBPPK0oKJPUrEpP16:b-8pmizc) ([raw file](https://github.com/pmem/rpma/blob/02dd21cd42c5327530865a8a92a5d03c6921817e/CHANGELOG.md#L35)):*
> ```Markdown
> 
> - Tools:
>   - [ddio.sh script][ddio] to toggle and query the DDIO (Intel&reg Data Direct I/O Technology) state per PCIe root port on Intel&reg Cascade Lake platforms ([#597][597]).
> ```

&reg;



_Code quote:_
```Markdown
&reg
```
___
*[CHANGELOG.md, line 35 at r6](https://reviewable.io/reviews/pmem/rpma/1506#-MtxBS777S3ch-W8xK5S:-MtxBS777S3ch-W8xK5T:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/02dd21cd42c5327530865a8a92a5d03c6921817e/CHANGELOG.md#L35)):*
> ```Markdown
> 
> - Tools:
>   - [ddio.sh script][ddio] to toggle and query the DDIO (Intel&reg Data Direct I/O Technology) state per PCIe root port on Intel&reg Cascade Lake platforms ([#597][597]).
> ```

.



_Code quote:_
```Markdown
&reg
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1506)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @ldorau)

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1506)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @ldorau)

___
*[CHANGELOG.md, line 35 at r6](https://reviewable.io/reviews/pmem/rpma/1506#-MtxBPPJEHNr5Wqpq64W:-MtxBWqf5p_rg6WziClN:b-warmy9) ([raw file](https://github.com/pmem/rpma/blob/02dd21cd42c5327530865a8a92a5d03c6921817e/CHANGELOG.md#L35)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

&reg;
</blockquote></details>

with ```;``` at the end

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1506)* status: all files reviewed (commit messages unreviewed), 2 unresolved discussions (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1506)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[CHANGELOG.md, line 35 at r6](https://reviewable.io/reviews/pmem/rpma/1506#-MtxBPPJEHNr5Wqpq64W:-MtxEwhK7tznyAY2CH20:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/02dd21cd42c5327530865a8a92a5d03c6921817e/CHANGELOG.md#L35)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

with ```;``` at the end
</blockquote></details>

Done.
___
*[CHANGELOG.md, line 35 at r6](https://reviewable.io/reviews/pmem/rpma/1506#-MtxBS777S3ch-W8xK5S:-MtxExsd-sBpJipQu6IJ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/02dd21cd42c5327530865a8a92a5d03c6921817e/CHANGELOG.md#L35)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1506#-:-MtxGB-V3iQTrFreYiqk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
@grom72 `Unblock performance` replaced with `Unblocked performance`

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1506#-:-Mu17arZD8TyIN_u07PC:b-hhiuq)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1506#-:-Mu2_BpyAVdYJM6_qrWe:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1506#-:-Mu9lx3q-xYB2ZAG6jg4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
