### PR TITLE
tools: set names of log files

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1378)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
It sets the following names, for example:
```
/tmp/ib_read_lat-2021-12-01-11:53:35-770239-server.log
/tmp/ib_read_lat-2021-12-01-11:53:35-770239-client.log
```

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1378#-:-MppcrYj2xIA22KIpY8g:b-2zyhd2)* status: 0 of 1 files reviewed, all discussions resolved

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1378)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 70 at r1](https://reviewable.io/reviews/pmem/rpma/1378#-Mppesly-y-dnXpbttUf:-Mppesly-y-dnXpbttUg:b-ji1ymm) ([raw file](https://github.com/pmem/rpma/blob/e1feedc1305f5b53afbcb7296fa56f0c7436ac32/tools/perf/lib/benchmark/runner/ib_read.py#L70)):*
> ```Python
>             self.__results = {}
>         self.__validate()
>         self.__mode = mode
> ```

No need for the intermediate variable?
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 115 at r1](https://reviewable.io/reviews/pmem/rpma/1378#-Mppdk4Q7Oi_JdCWCapD:-Mppdk4Q7Oi_JdCWCapE:b-wl71oz) ([raw file](https://github.com/pmem/rpma/blob/e1feedc1305f5b53afbcb7296fa56f0c7436ac32/tools/perf/lib/benchmark/runner/ib_read.py#L115)):*
> ```Python
>         time_stamp = str(datetime.now())
>         time_stamp = time_stamp.replace(' ', '-')
>         time_stamp = time_stamp.replace('.', '-')
> ```

Can we use `datetime.strftime()` instead?

Ref: https://docs.python.org/3/library/datetime.html#datetime.date.strftime

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1378)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 70 at r1](https://reviewable.io/reviews/pmem/rpma/1378#-Mppesly-y-dnXpbttUf:-MpphBT99X5Ts1BkkmGW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e1feedc1305f5b53afbcb7296fa56f0c7436ac32/tools/perf/lib/benchmark/runner/ib_read.py#L70)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

No need for the intermediate variable?
</blockquote></details>

Done.
___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 115 at r1](https://reviewable.io/reviews/pmem/rpma/1378#-Mppdk4Q7Oi_JdCWCapD:-MpplqYo3S2kq3iSooBW:bb6un1j) ([raw file](https://github.com/pmem/rpma/blob/e1feedc1305f5b53afbcb7296fa56f0c7436ac32/tools/perf/lib/benchmark/runner/ib_read.py#L115)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Can we use `datetime.strftime()` instead?

Ref: https://docs.python.org/3/library/datetime.html#datetime.date.strftime
</blockquote></details>

Done

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1378)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 112 at r2](https://reviewable.io/reviews/pmem/rpma/1378#-MppoLdXAUEEgyykBhh1:-MppoLdXAUEEgyykBhh2:b-f4ds2c) ([raw file](https://github.com/pmem/rpma/blob/8f417f2e6f598e4b8d580bc755d5f86b0a4a55f3/tools/perf/lib/benchmark/runner/ib_read.py#L112)):*
> ```Python
>     def __set_log_files_names(self):
>         """set names of log files"""
>         time_stamp = datetime.now().strftime("%Y-%m-%d-%H:%M:%S-%f")
> ```

`.%f`? It is padded with zeroes so it should fit nicely.

Ref: https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1378)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/benchmark/runner/ib_read.py, line 112 at r2](https://reviewable.io/reviews/pmem/rpma/1378#-MppoLdXAUEEgyykBhh1:-MppzU9W-i5fyD6rG-2i:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/8f417f2e6f598e4b8d580bc755d5f86b0a4a55f3/tools/perf/lib/benchmark/runner/ib_read.py#L112)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`.%f`? It is padded with zeroes so it should fit nicely.

Ref: https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1378#-:-MpqWhMx4OxHv1pTyPqD:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1378#-:-MpuHYx4Dz_CS6jLIhjE:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1378)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — APPROVED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1378)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
