### PR TITLE
examples: add common-pmem_map_file and signature_check to example05

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1854)

### CODE REVIEW

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1854)* status: 0 of 12 files reviewed, 5 unresolved discussions (waiting on @grom72 and @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1854#-N54ywbT636dIJTkF8g4:-N54ywbU0_d5l8veqqAA:bmumhda) (no related file):*
Please add references to basic PR #1791 

___
___
*[`examples/05-flush-to-persistent/client.c` line 61 at r1](https://reviewable.io/reviews/pmem/rpma/1854#-N54ygVy6ic7RzOW5c8N:-N54ygVy6ic7RzOW5c8O:undefined) ([raw file](https://github.com/pmem/rpma/blob/45cf0e1410e00b070d585cd31ce9629eeb80d072/examples/05-flush-to-persistent/client.c#L61)):*
> ```C
> 		char *path = argv[3];
> 
> 		ret = common_pmem_map_file_with_signature_check(path,
> ```





_Suggestion:_
```C
		ret = common_pmem_map_file_with_signature_check(path,0 , &mem);
```
___
*[`examples/05-flush-to-persistent/client.c` line 236 at r1](https://reviewable.io/reviews/pmem/rpma/1854#-N54ySwb1gPYAuGZLacF:-N54ySwb1gPYAuGZLacG:undefined) ([raw file](https://github.com/pmem/rpma/blob/45cf0e1410e00b070d585cd31ce9629eeb80d072/examples/05-flush-to-persistent/client.c#L236)):*
> ```C
> err_free:
> #ifdef USE_PMEM
> 	if (mem.is_pmem) {
> ```





_Suggestion:_
```C
	if (mem.is_pmem) {
		common_pmem_unmap_file(&mem);

	} else
```
___
*[`examples/05-flush-to-persistent/server.c` line 59 at r1](https://reviewable.io/reviews/pmem/rpma/1854#-N54yqIM-xWcVunFqwRi:-N54yqIM-xWcVunFqwRj:undefined) ([raw file](https://github.com/pmem/rpma/blob/45cf0e1410e00b070d585cd31ce9629eeb80d072/examples/05-flush-to-persistent/server.c#L59)):*
> ```C
> 		pmem_path = argv[3];
> 
> 		ret = common_pmem_map_file_with_signature_check(pmem_path, 0, &mem);
> ```





_Suggestion:_
```C
common_pmem_map_file_with_signature_check(pmem_path, sizeof(struct hello_t), &mem);
```
___
*[`examples/05-flush-to-persistent/server.c` line 207 at r1](https://reviewable.io/reviews/pmem/rpma/1854#-N54yWi10S7Z9Lrd5sMQ:-N54yWi10S7Z9Lrd5sMR:undefined) ([raw file](https://github.com/pmem/rpma/blob/45cf0e1410e00b070d585cd31ce9629eeb80d072/examples/05-flush-to-persistent/server.c#L207)):*
> ```C
> err_free:
> #ifdef USE_PMEM
> 	if (mem.is_pmem) {
> ```





_Suggestion:_
```C
	if (mem.is_pmem) {
		common_pmem_unmap_file(&mem);

	} else
```

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 12 files at r1, 2 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1854)* status: 2 of 12 files reviewed, 5 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[`examples/05-flush-to-persistent/CMakeLists.txt` line 39 at r4](https://reviewable.io/reviews/pmem/rpma/1854#-N5B-HB74xo2NkLv2-aS:-N5B-HB74xo2NkLv2-aT:b-ibev0j) ([raw file](https://github.com/pmem/rpma/blob/eff00d8bd3d1a5a89dfa9824ee16e753be994aae/examples/05-flush-to-persistent/CMakeLists.txt#L39)):*
> ```CMake
> link_directories(${LIBRPMA_LIBRARY_DIRS})
> 
> function(add_example name)
> ```

should be moved to common cmake file



_Code quote:_
```CMake
function(add_example name)
```
___
*[`examples/05-flush-to-persistent/server.c` line 59 at r1](https://reviewable.io/reviews/pmem/rpma/1854#-N54yqIM-xWcVunFqwRi:-N5B-5A8BPAwJUnsIDV7:b4g1fqu) ([raw file](https://github.com/pmem/rpma/blob/45cf0e1410e00b070d585cd31ce9629eeb80d072/examples/05-flush-to-persistent/server.c#L59)):*
> ```C
> 		pmem_path = argv[3];
> 
> 		ret = common_pmem_map_file_with_signature_check(pmem_path, 0, &mem);
> ```

``KILOBYTE`` instead of ``sizeof(struct hello_t)``



_Code quote:_
```C
KILOBYTE
```

**Review by haichangsi — COMMENTED** [review]
Ref: #1791 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1854#-:-N5_z8l1AhdClYWgJ9LS:bijqz83)* status: 0 of 13 files reviewed, 5 unresolved discussions (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1854#-N54ywbT636dIJTkF8g4:-N5_z7Cv4RiKSPK8DKmg:b-896fix) (no related file):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Please add references to basic PR #1791 
</blockquote></details>

Done.

___
___
*[`examples/05-flush-to-persistent/CMakeLists.txt` line 39 at r4](https://reviewable.io/reviews/pmem/rpma/1854#-N5B-HB74xo2NkLv2-aS:-N5_um_O0ISl3alpaI65:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/eff00d8bd3d1a5a89dfa9824ee16e753be994aae/examples/05-flush-to-persistent/CMakeLists.txt#L39)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

should be moved to common cmake file
</blockquote></details>

Done.
___
*[`examples/05-flush-to-persistent/client.c` line 236 at r1](https://reviewable.io/reviews/pmem/rpma/1854#-N54ySwb1gPYAuGZLacF:-N5_uuvg5eKVTyuCW24v:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/45cf0e1410e00b070d585cd31ce9629eeb80d072/examples/05-flush-to-persistent/client.c#L236)):*
> ```C
> err_free:
> #ifdef USE_PMEM
> 	if (mem.is_pmem) {
> ```

Done.
___
*[`examples/05-flush-to-persistent/server.c` line 59 at r1](https://reviewable.io/reviews/pmem/rpma/1854#-N54yqIM-xWcVunFqwRi:-N5_vEKV4J0pOeq6U9A0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/45cf0e1410e00b070d585cd31ce9629eeb80d072/examples/05-flush-to-persistent/server.c#L59)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

``KILOBYTE`` instead of ``sizeof(struct hello_t)``
</blockquote></details>

Done.
___
*[`examples/05-flush-to-persistent/server.c` line 207 at r1](https://reviewable.io/reviews/pmem/rpma/1854#-N54yWi10S7Z9Lrd5sMQ:-N5_vG0n35h8wF5V_vbE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/45cf0e1410e00b070d585cd31ce9629eeb80d072/examples/05-flush-to-persistent/server.c#L207)):*
> ```C
> err_free:
> #ifdef USE_PMEM
> 	if (mem.is_pmem) {
> ```

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 12 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1854)* status: 3 of 13 files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by haichangsi — COMMENTED** [review]
Done

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1854#-:-N5dv2jK1lbpzjEdyN_g:bb6un1j)* status: 3 of 13 files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 12 files at r5, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1854)* status: 5 of 13 files reviewed, all discussions resolved (waiting on @grom72)

**Review by grom72 — APPROVED** [review]
> Reviewed 8 of 12 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1854)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1854)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1854#-N5o_Nqr82Ohyj_IdIMa:-N5o_Nqs77D9aGV9MaAA:b-ujmq67) (no related file):*
Rebase please

___

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1854)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1854)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1854#-N5o_Nqr82Ohyj_IdIMa:-N5qT5V81n9aXGPzl8YJ:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Rebase please
</blockquote></details>

Done.

___

**Review by ldorau — APPROVED** [review]
> Reviewed 4 of 12 files at r5, 1 of 1 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1854)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1854#-:-N5sUPkzEgYa2XdqbOUk:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1854)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[`examples/05-flush-to-persistent/client.c` line 234 at r7](https://reviewable.io/reviews/pmem/rpma/1854#-N5sUdvG4izrmBvpcFJ5:-N5sUdvHEqMzABY6ToLi:undefined) ([raw file](https://github.com/pmem/rpma/blob/5dd2656d77f23fd75d6573739575be0c407da040/examples/05-flush-to-persistent/client.c#L234)):*
> ```C
> 	if (mem.is_pmem) {
> 		common_pmem_unmap_file(&mem);
> 	}
> ```





_Suggestion:_
```C
	} else
```

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1854)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1854)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
> Reviewed 8 of 12 files at r5, 1 of 1 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1854)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1854)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`examples/05-flush-to-persistent/client.c` line 234 at r7](https://reviewable.io/reviews/pmem/rpma/1854#-N5sUdvG4izrmBvpcFJ5:-N5stSD76fDZFppmBi0W:bt2vr1b) ([raw file](https://github.com/pmem/rpma/blob/5dd2656d77f23fd75d6573739575be0c407da040/examples/05-flush-to-persistent/client.c#L234)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Fixed.

**Pull request merged**
