### PR TITLE
doc: fix links to pmem.io in the pdf file

### PR DESCRIPTION
**Pull request by osalyk**
Ref: https://github.com/pmem/rpma/issues/1582

This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1586)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
It does not fix #1582

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1586#-:-Mw0SU1M1fpMzusvvsc_:b-ivrbla)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1586#-Mw0RSP0Dj9kwHQYhKcC):*
doc: fix links to pmem.io in the pdf file



_Code quote:_
```
doc: improve pmem.io links
```

**Review by ldorau — COMMENTED** [review]
Ref: #1582

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1586#-:-Mw0VvQj-SRFMlW_ZFBF:bljeq5)* status: all files reviewed, 1 unresolved discussion (waiting on @osalyk)

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1586)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @ldorau)

___
*[-- commits, line 2 at r1](https://reviewable.io/reviews/pmem/rpma/1586#-Mw0RSP0Dj9kwHQYhKcC):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

doc: fix links to pmem.io in the pdf file
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1586)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1586#-:-Mw0Xok2E5rBcrKqIvqH:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1586)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
