### PR TITLE
common: pass conn_cfg via ep_next_conn_req()

### PR DESCRIPTION
**Pull request by janekmi**
Requires:
- [x] #337 
- [x] #331

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/338)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 28 of 28 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/338)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
documentation is incomplete - DESCRIPTION section is missing 

> Reviewed 6 of 28 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/338#-:-MGHq9p-0XVw1ApEW6_S:bodr52f)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tests/unit/ep/ep-next_conn_req.c, line 227 at r1](https://reviewable.io/reviews/pmem/rpma/338#-MGHzsT5DF49zbLdNILE:-MGHzsT5DF49zbLdNILF:buz0f6y) ([raw file](https://github.com/pmem/rpma/blob/3d8667d62681fbe2514173225184d234f6b88a92/tests/unit/ep/ep-next_conn_req.c#L227)):*
> ```
> next_conn_req__success
> ```
success_with_default_config is missing

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/338)* status: 7 of 12 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[tests/unit/ep/ep-next_conn_req.c, line 227 at r1](https://reviewable.io/reviews/pmem/rpma/338#-MGHzsT5DF49zbLdNILE:-MGIG-ERBjoKKOlDKCxw:b-6yyawl) ([raw file](https://github.com/pmem/rpma/blob/3d8667d62681fbe2514173225184d234f6b88a92/tests/unit/ep/ep-next_conn_req.c#L227)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> next_conn_req__success
> ```
success_with_default_config is missing
</blockquote></details>

No any more.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 28 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/338)* status: 7 of 12 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 28 files at r1, 5 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/338)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 5 of 28 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/338#-:-MGIH5xG-oiJk7Z7Rvi5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
> Reviewed 5 of 12 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/338)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/338#-:-MGIM3PI7k-naoDCkofQ:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
