### PR TITLE
tools: implement Part._load_variables()

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1116)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1116#-:-MdqD9BkCsV0Z2KzL8W2:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1116)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/lib/Part.py, line 27 at r1](https://reviewable.io/reviews/pmem/rpma/1116#-Mdvka9F54cef0gVQsHL:-Mdvka9F54cef0gVQsHM:by5ixec) ([raw file](https://github.com/pmem/rpma/blob/64a006d0abf1adc2ca3e286bf053ea4b62e97308/tools/perf/lib/Part.py#L27)):*
> ```Python
>         # preprocess variables['common']
>         # - concat lines "\n" and or (lines2str)
>         for var, txt in variables['common'].items():
> ```

'common' may or may not be present. Please handle both scenarios.
___
*[tools/perf/lib/Part.py, line 32 at r1](https://reviewable.io/reviews/pmem/rpma/1116#-Mdvkrow9hnmBmDcn-YJ:-Mdvkrow9hnmBmDcn-YK:bni9uc1) ([raw file](https://github.com/pmem/rpma/blob/64a006d0abf1adc2ca3e286bf053ea4b62e97308/tools/perf/lib/Part.py#L32)):*
> ```Python
>         # generate HTML tables dict2kvtable()
>         # - take into account the variables['common']
>         for cfg, desc in variables['config'].items():
> ```

'config' is only an example. I know it is not obvious since currently there is only a single example. But in general, I would assume 'common' is something that has to be processed and 'poped out'. Anything else is an input to the template.
___
*[tools/perf/lib/Part.py, line 34 at r1](https://reviewable.io/reviews/pmem/rpma/1116#-Mdvlnk4D8EF9VlzA3mD:-Mdvlnk4D8EF9VlzA3mE:b-yszavk) ([raw file](https://github.com/pmem/rpma/blob/64a006d0abf1adc2ca3e286bf053ea4b62e97308/tools/perf/lib/Part.py#L34)):*
> ```Python
>         for cfg, desc in variables['config'].items():
>             if desc["type"] == "kvtable":
>                 variables['config'][cfg] = dict2kvtable(desc, variables['common'])
> ```

What if a certain value is not a kvtable but is simply a list of lines?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1116)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/lib/Part.py, line 27 at r1](https://reviewable.io/reviews/pmem/rpma/1116#-Mdvka9F54cef0gVQsHL:-Mdvpg6lAEwdgn30BFhO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/64a006d0abf1adc2ca3e286bf053ea4b62e97308/tools/perf/lib/Part.py#L27)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

'common' may or may not be present. Please handle both scenarios.
</blockquote></details>

Done.
___
*[tools/perf/lib/Part.py, line 34 at r1](https://reviewable.io/reviews/pmem/rpma/1116#-Mdvlnk4D8EF9VlzA3mD:-Mdvpz14DgkggJXT4QPM:b-srex3c) ([raw file](https://github.com/pmem/rpma/blob/64a006d0abf1adc2ca3e286bf053ea4b62e97308/tools/perf/lib/Part.py#L34)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

What if a certain value is not a kvtable but is simply a list of lines?
</blockquote></details>

But `desc["type"] == "kvtable"` ????

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1116)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[tools/perf/lib/Part.py, line 34 at r1](https://reviewable.io/reviews/pmem/rpma/1116#-Mdvlnk4D8EF9VlzA3mD:-Mdvsw_6AyT3jn_jRA1e:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/64a006d0abf1adc2ca3e286bf053ea4b62e97308/tools/perf/lib/Part.py#L34)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

But `desc["type"] == "kvtable"` ????
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1116)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @janekmi, @ldorau, and @osalyk)

___
*[tools/perf/lib/Part.py, line 26 at r3](https://reviewable.io/reviews/pmem/rpma/1116#-MdvumJR4aXerkDF1V9q:-MdvumJR4aXerkDF1V9r:b-kvvjud) ([raw file](https://github.com/pmem/rpma/blob/d30e55c5752c05d9ce3ecc0de090022fd8fed974/tools/perf/lib/Part.py#L26)):*
> ```
> concat lines "\n" and or (lines2str)
> ```
**and or**

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1116)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tools/perf/lib/Part.py, line 32 at r1](https://reviewable.io/reviews/pmem/rpma/1116#-Mdvkrow9hnmBmDcn-YJ:-MdwH37R-VNYD-3Ye61z:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/64a006d0abf1adc2ca3e286bf053ea4b62e97308/tools/perf/lib/Part.py#L32)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

'config' is only an example. I know it is not obvious since currently there is only a single example. But in general, I would assume 'common' is something that has to be processed and 'poped out'. Anything else is an input to the template.
</blockquote></details>

Done.
___
*[tools/perf/lib/Part.py, line 26 at r3](https://reviewable.io/reviews/pmem/rpma/1116#-MdvumJR4aXerkDF1V9q:-MdwH1WK8QlmciTtJ0YS:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/d30e55c5752c05d9ce3ecc0de090022fd8fed974/tools/perf/lib/Part.py#L26)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

> ```
> concat lines "\n" and or (lines2str)
> ```
**and or**
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1116#-:-Mdzb1TM4wo4HHg6T9N1:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1116)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1116#-Me0okYgBHqd8Wy7XryA:-Me0okYgBHqd8Wy7XryB:buc7kl2) (no related file):*
The implementation passes all upcoming tests.

Ref: #1134

---
___
*[tools/perf/lib/Part.py, line 32 at r7](https://reviewable.io/reviews/pmem/rpma/1116#-Me0ogwi0WSOnXNf_282:-Me0ogwi0WSOnXNf_283:b8dswry) ([raw file](https://github.com/pmem/rpma/blob/eae91e309afb3d85829ea98ebcffd4a9acb5f968/tools/perf/lib/Part.py#L32)):*
> ```Python
>                 else:
>                     self._process_variables_level(v, common)
>             # replace templates
> ```

templates -> common

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1116)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/Part.py, line 32 at r7](https://reviewable.io/reviews/pmem/rpma/1116#-Me0ogwi0WSOnXNf_282:-Me3k_iW2kQcdZg5skQm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/eae91e309afb3d85829ea98ebcffd4a9acb5f968/tools/perf/lib/Part.py#L32)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

templates -> common
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1116#-:-Me4X27G10vW-R4wFMTq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
