### PR TITLE
common: clean up ignoring __pycache__

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #1466 
- [x] #1464

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1463)

### CODE REVIEW

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1463#-:-MsAENw6-7dO6xxqv0o9:bg7igkv)* status: 0 of 3 files reviewed, all discussions resolved

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1463#-:-MsAKDYR30fG9t8Q82a_:bnfp4nl)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1463#-:-MsAYhvF7bvUC2Q9TClu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> Reviewed 3 of 4 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1463)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
