### PR TITLE
common: 0.12.0-rc1 release

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #1578
- [x] #1577 

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1579)

### CODE REVIEW

**Review by grom72 — APPROVED** [review]
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1579)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1579)* status: 4 of 11 files reviewed, 1 unresolved discussion (waiting on @grom72)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1579#-MvdD_M_3PqHDT2e6dQv:-MvdD_MaDI5u_pfQpDzZ:bkz58kk) (no related file):*
Waiting for https://github.com/pmem/rpma/pull/1577 to be merged

---

**Review by ldorau — COMMENTED** [review]
> Reviewed 7 of 7 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1579)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1579)* status: all files reviewed (commit messages unreviewed), all discussions resolved (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1579#-MvdD_M_3PqHDT2e6dQv:-MveqAhXBCukbSBVv0rY:bwbw51t) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Waiting for https://github.com/pmem/rpma/pull/1577 to be merged
</blockquote></details>

Merged

---

**Review by ldorau — COMMENTED** [review]
> Reviewed 4 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1579)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
