### PR TITLE
rpma: fix the rpma_conn_completion_get() documentation

### PR DESCRIPTION
**Pull request by janekmi**
Markdown formatting is not handled by src2man.

Ref: #1170
Ref: #518

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1208)

### CODE REVIEW

**Comment by janekmi** [comment]
image

Ref: https://pmem.io/rpma/manpages/master/rpma_conn_completion_get.3

**Review by yangx-jy — COMMENTED** [review]
:lgtm:

Sorry, I missed the issue.

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1208#-:-Mhpin3s1BLdcIxkDs1s:b33rfv6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1208#-:-MhqlvrK1cUv83mLu09r:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1208)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
