### PR TITLE
tools: use FORCE_REMOTE_DIRECT_WRITE_TO_PMEM for the baseline DRAM bench

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/791)

### CODE REVIEW

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/791#-:-MS6ekrWCEFiu_SefP_V:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/report_bench.sh, line 52 at r1](https://reviewable.io/reviews/pmem/rpma/791#-MS6eV-RB8Yg6piBDv8r:-MS6eV-S8p4L48HLpW7u:bp5d7m7) ([raw file](https://github.com/pmem/rpma/blob/2b2b8497217d18d2b2ccaf73dd8ac0b08792ab07/tools/report_bench.sh#L52)):*
> ```
> 		# the reference pipeline performance requires APM-style write but with
> 		# DDIO=on which is not the default for APM benchmarking
> ```

Full sentence please.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/791#-:-MS6mMMe8JDnDwzysjpY:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/791)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/report_bench.sh, line 52 at r1](https://reviewable.io/reviews/pmem/rpma/791#-MS6eV-RB8Yg6piBDv8r:-MS6sMx39TPULIIgB5b8:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2b2b8497217d18d2b2ccaf73dd8ac0b08792ab07/tools/report_bench.sh#L52)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 		# the reference pipeline performance requires APM-style write but with
> 		# DDIO=on which is not the default for APM benchmarking
> ```

Full sentence please.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/791)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
