### PR TITLE
test: use strncpy() instead of strcpy()

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/847)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/847#-:-MSgu1b1AI0Y12U1bmLf:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/847)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 82 at r1](https://reviewable.io/reviews/pmem/rpma/847#-MShS4nP7wgQlXnk0lU2:-MShS4nP7wgQlXnk0lU3:b27pgqu) ([raw file](https://github.com/pmem/rpma/blob/568af6f35d8a6453fe53243731808d99dc3db997/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L82)):*
> ```C
> 		threads_args[i].thread_num = i;
> 		strncpy(threads_args[i].addr, addr,
> 			sizeof(threads_args[i].addr));
> ```

Why not just use `MAX_ADDR - 1`?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/847)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 82 at r1](https://reviewable.io/reviews/pmem/rpma/847#-MShS4nP7wgQlXnk0lU2:-MShXhoN8bR4MYDMRNt_:bvo45bl) ([raw file](https://github.com/pmem/rpma/blob/568af6f35d8a6453fe53243731808d99dc3db997/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L82)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Why not just use `MAX_ADDR - 1`?
</blockquote></details>

Just in case something changed, like:

not: `memcpy(cfg_ptr, &Conn_cfg_default, sizeof(struct rpma_conn_cfg));`

but:

`memcpy(cfg_ptr, &Conn_cfg_default, sizeof(*cfg_ptr));`

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/847)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/847)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 82 at r1](https://reviewable.io/reviews/pmem/rpma/847#-MShS4nP7wgQlXnk0lU2:-MSixTvA2iE1NOU5hQfj:b-8ippjn) ([raw file](https://github.com/pmem/rpma/blob/568af6f35d8a6453fe53243731808d99dc3db997/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L82)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Ok. So why not `sizeof(threads_args[i].addr) - 1`?
</blockquote></details>

Just because size of `threads_args[i].addr` equals `sizeof(threads_args[i].addr)` ;-)
so this is the _maximum_ number of bytes we can copy to `threads_args[i].addr`.

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/847)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 82 at r1](https://reviewable.io/reviews/pmem/rpma/847#-MShS4nP7wgQlXnk0lU2:-MSjLNPo00t2XtQKDkut:b-kgno9y) ([raw file](https://github.com/pmem/rpma/blob/568af6f35d8a6453fe53243731808d99dc3db997/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L82)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Just because size of `threads_args[i].addr` equals `sizeof(threads_args[i].addr)` ;-)
so this is the _maximum_ number of bytes we can copy to `threads_args[i].addr`.
</blockquote></details>

If I understand correctly this simplified implementation:

```c
char *
strncpy(char *dest, const char *src, size_t n)
{
    size_t i;

   for (i = 0; i < n && src[i] != '\0'; i++)
        dest[i] = src[i];
    for ( ; i < n; i++)
        dest[i] = '\0';

   return dest;
}
```

It means we are open to having not-NULL-terminated string which won't be the case if we will put ` - 1` here.

Ref: https://linux.die.net/man/3/strncpy

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/847)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi and @osalyk)

___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 82 at r1](https://reviewable.io/reviews/pmem/rpma/847#-MShS4nP7wgQlXnk0lU2:-MSkxmdm4z-_DEDkfU1J:b-5jzk8s) ([raw file](https://github.com/pmem/rpma/blob/568af6f35d8a6453fe53243731808d99dc3db997/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L82)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

If I understand correctly this simplified implementation:

```c
char *
strncpy(char *dest, const char *src, size_t n)
{
    size_t i;

   for (i = 0; i < n && src[i] != '\0'; i++)
        dest[i] = src[i];
    for ( ; i < n; i++)
        dest[i] = '\0';

   return dest;
}
```

It means we are open to having not-NULL-terminated string which won't be the case if we will put ` - 1` here.

Ref: https://linux.die.net/man/3/strncpy
</blockquote></details>

Yes, but only partially, because `threads_args[i].addr` is not zeroed so, `-1` itself does not prevent against not-NULL-terminated string. If we want to do that, we have to add zeroing - what I have just added. I hope it is OK now :-).

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/847)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 66 at r2](https://reviewable.io/reviews/pmem/rpma/847#-MSlZJ808oxz7bx9v5xw:-MSlZJ808oxz7bx9v5xx:bgjpbyu) ([raw file](https://github.com/pmem/rpma/blob/fef625102a77e56e2d7728688b49dfa673e1451c/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L66)):*
> ```C
> 
> 	pthread_t *p_threads;
> 	p_threads = calloc(1, sizeof(pthread_t) * (unsigned int)thread_num);
> ```

`calloc(thread_num, sizeof(pthread_t)`
___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 72 at r2](https://reviewable.io/reviews/pmem/rpma/847#-MSlZRPu-_9VoFWLR5xL:-MSlZRPu-_9VoFWLR5xM:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/fef625102a77e56e2d7728688b49dfa673e1451c/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L72)):*
> ```C
> 	}
> 
> 	struct thread_args *threads_args = calloc(1, sizeof(struct thread_args)
> ```

.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/847)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 66 at r2](https://reviewable.io/reviews/pmem/rpma/847#-MSlZJ808oxz7bx9v5xw:-MSlcM8k5yugX536yH2B:biw8y1v) ([raw file](https://github.com/pmem/rpma/blob/fef625102a77e56e2d7728688b49dfa673e1451c/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L66)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`calloc(thread_num, sizeof(pthread_t)`
</blockquote></details>

Right. Done.
___
*[tests/multithreaded/utils/rpma_utils_get_ibv_context.c, line 72 at r2](https://reviewable.io/reviews/pmem/rpma/847#-MSlZRPu-_9VoFWLR5xL:-MSlcQim1DfUo2QjkxZq:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fef625102a77e56e2d7728688b49dfa673e1451c/tests/multithreaded/utils/rpma_utils_get_ibv_context.c#L72)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/847#-:-MSlg3p6EUe7PLSZ-qBS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
