### PR TITLE
tools: remove bash framework scripts

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1476)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1476)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed 5 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1476)* status: 5 of 6 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1476)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @haichangsi and @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1476#-Mse02I51gVzOV_rRkUN:-Mse02I51gVzOV_rRkUO:bvdsf87) (no related file):*
Please remove also the unit tests of the bash path.

---

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1476)* status: 5 of 8 files reviewed, 1 unresolved discussion (waiting on @haichangsi and @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1476)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @haichangsi and @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1476)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1476#-MseejyOALreo6yKip2r:-MseejyOALreo6yKip2s:b164ecb) (no related file):*
There two more things left to be removed:

1) The whole Bash runner path in the new framework (starting from https://github.com/pmem/rpma/blob/devel-new-python/tools/perf/lib/benchmark/base.py#L193-194)

2) All mentions of all removed files (bench_common.sh, csv2standardized.py, fio_json2csv.py, ib_read.sh, rpma_fio_bench.sh) in all files (except of BENCHMARKING.md)

---
___
*[tools/perf/BENCHMARKING.md, line 145 at r2](https://reviewable.io/reviews/pmem/rpma/1476#-MsefgOY-paT8RYM-aCB:-MsefgOY-paT8RYM-aCC:bnlbysq) ([raw file](https://github.com/pmem/rpma/blob/c8a5f619ebde4753d328df90689eaec203b63369/tools/perf/BENCHMARKING.md#L145)):*
> ```Markdown
> $ ./report_figures.py compare -h
> ```
> # To be deleted
> ```

Please mark the begin and the end of the text to be removed with:
```
# XXX to be removed [BEGIN]
....
(text to be removed)
...
# XXX to be removed [END]

```



_Code quote:_
```Markdown
# To be deleted
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1476)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1476#-Mt73IQ77vfi65t0wzkW:-Mt73IQ77vfi65t0wzkX:bp2n24e) (no related file):*
`csv_compare.py` should be removed too

---

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1476)* status: 7 of 16 files reviewed, 3 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1476#-Mse02I51gVzOV_rRkUN:-Mt7h6i3C8OpX-i6YXQC:bb6un1j) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please remove also the unit tests of the bash path.
</blockquote></details>

Done

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1476#-MseejyOALreo6yKip2r:-Mt7gtri2FmGewqvJXTT:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

There two more things left to be removed:

1) The whole Bash runner path in the new framework (starting from https://github.com/pmem/rpma/blob/devel-new-python/tools/perf/lib/benchmark/base.py#L193-194)

2) All mentions of all removed files (bench_common.sh, csv2standardized.py, fio_json2csv.py, ib_read.sh, rpma_fio_bench.sh) in all files (except of BENCHMARKING.md)

</blockquote></details>

Done.

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1476#-Mt73IQ77vfi65t0wzkW:-Mt7gt1s0tbocou01G6Y:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`csv_compare.py` should be removed too
</blockquote></details>

Done.

---
___
*[tools/perf/BENCHMARKING.md, line 145 at r2](https://reviewable.io/reviews/pmem/rpma/1476#-MsefgOY-paT8RYM-aCB:-Mt7gr3t09bNX4KKr2Rs:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/c8a5f619ebde4753d328df90689eaec203b63369/tools/perf/BENCHMARKING.md#L145)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please mark the begin and the end of the text to be removed with:
```
# XXX to be removed [BEGIN]
....
(text to be removed)
...
# XXX to be removed [END]

```

</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 6 of 9 files at r3, 5 of 5 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1476)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1476#-MseejyOALreo6yKip2r:-Mt7mbud0k0HWMW4N5En:b-mloqzc) (no related file):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Ad 2) - there are 2 mentions left:
```
./tools/perf/config.json.example:2:    "_comment": "A configuration file providing all information describing the system which are necessary to run ./rpma_fio_bench.sh and ./ib_read.sh.",

./tools/perf/lib/benchmark/runner/fio.py:154:        # rpma_fio_bench.sh it is meant to store also a possible 'malloc'
```

---

**Review by ldorau — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1476#-:-Mt7oGqQ4J44UQh0OQbL:bdycpsm)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1476)* status: 16 of 18 files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1476#-MseejyOALreo6yKip2r:-Mt7pQa68A_QMIqaqD5F:b-896fix) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Ad 2) - there are 2 mentions left:
```
./tools/perf/config.json.example:2:    "_comment": "A configuration file providing all information describing the system which are necessary to run ./rpma_fio_bench.sh and ./ib_read.sh.",

./tools/perf/lib/benchmark/runner/fio.py:154:        # rpma_fio_bench.sh it is meant to store also a possible 'malloc'
```
</blockquote></details>

Done.

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1476)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[tools/perf/config.json.example, line 2 at r5](https://reviewable.io/reviews/pmem/rpma/1476#-Mt7s0_j6b58XJgCrXHk:-Mt7s0_k1gTEfcQb8j0g:b-assqf9) ([raw file](https://github.com/pmem/rpma/blob/391d95c79dd89ab3b7a653e059d5eee2fa51b205/tools/perf/config.json.example#L2)):*
> ```
> {
>     "_comment": "A configuration file providing all information describing the system which are necessary to run ./rpma_fio_bench.sh and ./ib_read.sh.",
> ```

It should be left in the following form:
```
    "_comment": "A configuration file providing all information describing the system which are necessary to run ./report_bench.py.",
```



_Code quote:_
```
    "_comment": "A configuration file providing all information describing the system which are necessary to run ./rpma_fio_bench.sh and ./ib_read.sh.",
```

**Review by osalyk — COMMENTED** [review]
> Reviewed 5 of 6 files at r1, 2 of 2 files at r2, 4 of 9 files at r3, 5 of 5 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1476)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1476)* status: 17 of 18 files reviewed, 1 unresolved discussion (waiting on @ldorau and @osalyk)

___
*[tools/perf/config.json.example, line 2 at r5](https://reviewable.io/reviews/pmem/rpma/1476#-Mt7s0_j6b58XJgCrXHk:-Mt85L_Q1wMNfPi68y5T:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/391d95c79dd89ab3b7a653e059d5eee2fa51b205/tools/perf/config.json.example#L2)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It should be left in the following form:
```
    "_comment": "A configuration file providing all information describing the system which are necessary to run ./report_bench.py.",
```
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1476#-:-Mt87xtE2Dk6hXw91uH1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1476#-:-Mt88Mim6cg4WIVACYcN:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1476)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1476#-:-Mt89Ab174Cyp2dNB-hh:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1476)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1, 4 of 9 files at r3, 2 of 5 files at r4, 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1476)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 153 at r6](https://reviewable.io/reviews/pmem/rpma/1476#-Mt8FUqrDL0IiNXuy2ai:-Mt8FUqrDL0IiNXuy2aj:b7vqcsx) ([raw file](https://github.com/pmem/rpma/blob/391d95c79dd89ab3b7a653e059d5eee2fa51b205/tools/perf/lib/benchmark/runner/fio.py#L153)):*
> ```Python
>             # no CPU load
>             args.append('--section=server')
>         # XXX the name REMOTE_JOB_MEM_PATH is unfortunate since for
> ```

Is this anyhow related to context of this PR



_Code quote:_
```Python
        # XXX the name REMOTE_JOB_MEM_PATH is unfortunate since for
        # rpma_fio_bench.sh it is meant to store also a possible 'malloc'
        # value
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 6 files at r1, 2 of 2 files at r2, 3 of 5 files at r4, 1 of 2 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1476)* status: all files reviewed, 1 unresolved discussion (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1476)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 153 at r6](https://reviewable.io/reviews/pmem/rpma/1476#-Mt8FUqrDL0IiNXuy2ai:-Mt8Qh3eCQlZVgYw8FLQ:b-y10qb3) ([raw file](https://github.com/pmem/rpma/blob/391d95c79dd89ab3b7a653e059d5eee2fa51b205/tools/perf/lib/benchmark/runner/fio.py#L153)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Is this anyhow related to context of this PR
</blockquote></details>

Yes, of course. `rpma_fio_bench.sh` is removed, so this comment does not make sense any longer.

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1476)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 153 at r6](https://reviewable.io/reviews/pmem/rpma/1476#-Mt8FUqrDL0IiNXuy2ai:-Mt95xfj4RLDlodBbB0F:bdf890j) ([raw file](https://github.com/pmem/rpma/blob/391d95c79dd89ab3b7a653e059d5eee2fa51b205/tools/perf/lib/benchmark/runner/fio.py#L153)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, of course. `rpma_fio_bench.sh` is removed, so this comment does not make sense any longer.
</blockquote></details>

I remember a discussion with @janekmi to rename this variable in the future when it will not be needed for rpma_fio_bench.sh

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1476)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 153 at r6](https://reviewable.io/reviews/pmem/rpma/1476#-Mt8FUqrDL0IiNXuy2ai:-Mt9u1tfD422bLDep254:b-vmr6jo) ([raw file](https://github.com/pmem/rpma/blob/391d95c79dd89ab3b7a653e059d5eee2fa51b205/tools/perf/lib/benchmark/runner/fio.py#L153)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

I remember a discussion with @janekmi to rename this variable in the future when it will not be needed for rpma_fio_bench.sh
</blockquote></details>

OK, so let's do it in another PR.

**Pull request merged**
