### PR TITLE
test: mt: the function pointers documentation

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1012)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1012)* status: all files reviewed, 6 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/common/mtt.h, line 66 at r1](https://reviewable.io/reviews/pmem/rpma/1012#-MYhciFFDd9ULaNM7nZd:-MYhciFFDd9ULaNM7nZe:b-kn9t23) ([raw file](https://github.com/pmem/rpma/blob/e6017c16641ea0018126a745410722ebeae17481/tests/multithreaded/common/mtt.h#L66)):*
> ```
> a type for a function 
> ```

a type of the function 
___
*[tests/multithreaded/common/mtt.h, line 74 at r1](https://reviewable.io/reviews/pmem/rpma/1012#-MYhcvbI6ay4YjjxOSWY:-MYhcvbI6ay4YjjxOSWZ:bujlfbz) ([raw file](https://github.com/pmem/rpma/blob/e6017c16641ea0018126a745410722ebeae17481/tests/multithreaded/common/mtt.h#L74)):*
> ```
>   ... on all steps. 
> ```

in all steps
___
*[tests/multithreaded/common/mtt.h, line 76 at r1](https://reviewable.io/reviews/pmem/rpma/1012#-MYhdQEn9Pwb0GsmDLDK:-MYhdQEn9Pwb0GsmDLDL:b-h7lxsp) ([raw file](https://github.com/pmem/rpma/blob/e6017c16641ea0018126a745410722ebeae17481/tests/multithreaded/common/mtt.h#L76)):*
> ```
>  ... The test can at any point
>  *               allocate and store here their specific data. 
> ```

The test can allocate and store their specific data here at any point.
___
*[tests/multithreaded/common/mtt.h, line 89 at r1](https://reviewable.io/reviews/pmem/rpma/1012#-MYhcmko7gasKkAdrh12:-MYhcmko7gasKkAdrh13:bl3v85o) ([raw file](https://github.com/pmem/rpma/blob/e6017c16641ea0018126a745410722ebeae17481/tests/multithreaded/common/mtt.h#L89)):*
> ```
> a type for the function 
> ```

.
___
*[tests/multithreaded/common/mtt.h, line 96 at r1](https://reviewable.io/reviews/pmem/rpma/1012#-MYhd4hN-WkFZA_RtCIv:-MYhd4hO9W9ivjiY2P6w:b-qurxkz) ([raw file](https://github.com/pmem/rpma/blob/e6017c16641ea0018126a745410722ebeae17481/tests/multithreaded/common/mtt.h#L96)):*
> ```
>  * - prestate - a pointer to test-provided data passed to all threads on all
>  *              steps. It is shared in a non-thread-safe way.
> ```

.
___
*[tests/multithreaded/common/mtt.h, line 99 at r1](https://reviewable.io/reviews/pmem/rpma/1012#-MYhea-s--3EKSW7s_bY:-MYhea-s--3EKSW7s_bZ:bhi1zgz) ([raw file](https://github.com/pmem/rpma/blob/e6017c16641ea0018126a745410722ebeae17481/tests/multithreaded/common/mtt.h#L99)):*
> ```
> Note it should not be freed during this step.
> ```

Lack of info when it should be freed.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1012)* status: all files reviewed, 7 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/common/mtt.h, line 91 at r1](https://reviewable.io/reviews/pmem/rpma/1012#-MYmoTeD8noDba7X4pRf:-MYmoTeD8noDba7X4pRg:b-rxi3w1) ([raw file](https://github.com/pmem/rpma/blob/e6017c16641ea0018126a745410722ebeae17481/tests/multithreaded/common/mtt.h#L91)):*
> ```
> Arguments
> ```
Would it be better to have common documentation for both functions and by this emphasize that these arguments are exactly the same in all functions calls?

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1012)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tests/multithreaded/common/mtt.h, line 91 at r1](https://reviewable.io/reviews/pmem/rpma/1012#-MYmoTeD8noDba7X4pRf:-MYnKQeI7yuscXfirHsX:b-lpn9q8) ([raw file](https://github.com/pmem/rpma/blob/e6017c16641ea0018126a745410722ebeae17481/tests/multithreaded/common/mtt.h#L91)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> Arguments
> ```
Would it be better to have common documentation for both functions and by this emphasize that these arguments are exactly the same in all functions calls?
</blockquote></details>

I don't think so. Having them separate we can provide more details about the specificity of the use/meaning of each of the arguments in the specific use. Not to mention, the list of arguments for both of them is different.

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1012)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[tests/multithreaded/common/mtt.h, line 66 at r1](https://reviewable.io/reviews/pmem/rpma/1012#-MYhciFFDd9ULaNM7nZd:-MYnVcHlDE_8FjgyAnYF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e6017c16641ea0018126a745410722ebeae17481/tests/multithreaded/common/mtt.h#L66)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> a type for a function 
> ```

a type of the function 
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mtt.h, line 74 at r1](https://reviewable.io/reviews/pmem/rpma/1012#-MYhcvbI6ay4YjjxOSWY:-MYnWbaE6wM5fcZwkPy3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e6017c16641ea0018126a745410722ebeae17481/tests/multithreaded/common/mtt.h#L74)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>   ... on all steps. 
> ```

in all steps
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mtt.h, line 76 at r1](https://reviewable.io/reviews/pmem/rpma/1012#-MYhdQEn9Pwb0GsmDLDK:-MYnWqHv7QEqb9JU2vpO:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e6017c16641ea0018126a745410722ebeae17481/tests/multithreaded/common/mtt.h#L76)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  ... The test can at any point
>  *               allocate and store here their specific data. 
> ```

The test can allocate and store their specific data here at any point.

</blockquote></details>

Done.
___
*[tests/multithreaded/common/mtt.h, line 89 at r1](https://reviewable.io/reviews/pmem/rpma/1012#-MYhcmko7gasKkAdrh12:-MYnWr9a1reOGbh1EIJ1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e6017c16641ea0018126a745410722ebeae17481/tests/multithreaded/common/mtt.h#L89)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> a type for the function 
> ```

.
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mtt.h, line 96 at r1](https://reviewable.io/reviews/pmem/rpma/1012#-MYhd4hN-WkFZA_RtCIv:-MYnWufm0nKSI3SiwpQo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e6017c16641ea0018126a745410722ebeae17481/tests/multithreaded/common/mtt.h#L96)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  * - prestate - a pointer to test-provided data passed to all threads on all
>  *              steps. It is shared in a non-thread-safe way.
> ```

.
</blockquote></details>

Done.
___
*[tests/multithreaded/common/mtt.h, line 99 at r1](https://reviewable.io/reviews/pmem/rpma/1012#-MYhea-s--3EKSW7s_bY:-MYnXoHACM4uFDjI5EZ0:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e6017c16641ea0018126a745410722ebeae17481/tests/multithreaded/common/mtt.h#L99)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> Note it should not be freed during this step.
> ```

Lack of info when it should be freed.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1012)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1012#-:-MYnxVnU05W7zW7WEIOP:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1012)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tests/multithreaded/common/mtt.h, line 91 at r1](https://reviewable.io/reviews/pmem/rpma/1012#-MYmoTeD8noDba7X4pRf:-MYrrBa5E6GyOTqrh5s6:bu7vf82) ([raw file](https://github.com/pmem/rpma/blob/e6017c16641ea0018126a745410722ebeae17481/tests/multithreaded/common/mtt.h#L91)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I don't think so. Having them separate we can provide more details about the specificity of the use/meaning of each of the arguments in the specific use. Not to mention, the list of arguments for both of them is different.
</blockquote></details>

So I suggest adding here a reference to example/example.c where prestate and state have additional documentation.

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1012)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1012)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[tests/multithreaded/common/mtt.h, line 91 at r1](https://reviewable.io/reviews/pmem/rpma/1012#-MYmoTeD8noDba7X4pRf:-MYtkLzs7kI5PsH3yaC3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e6017c16641ea0018126a745410722ebeae17481/tests/multithreaded/common/mtt.h#L91)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

So I suggest adding here a reference to example/example.c where prestate and state have additional documentation.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1012)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1012#-:-MYu6NBmCV0XWcYhIXPp:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
