### PR TITLE
examples: fix memory leak

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/412)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/412)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[examples/09-flush-to-persistent-GPSPM/server.c, line 287 at r1](https://reviewable.io/reviews/pmem/rpma/412#-MHkBSGP61XlJ_5WDIw5:-MHkBSGP61XlJ_5WDIw6:b-g2bzpk) ([raw file](https://github.com/pmem/rpma/blob/fe497689b7a669fb8677d966e6007059d3ad6d9b/examples/09-flush-to-persistent-GPSPM/server.c#L287)):*
> ```C
> 	 * structure.
> 	 */
> 	(void) common_wait_for_conn_close_and_disconnect(&conn);
> ```

Why not `(void) rpma_conn_delete(&conn);` as it was before?
___
*[examples/09-flush-to-persistent-GPSPM/server.c, line 290 at r1](https://reviewable.io/reviews/pmem/rpma/412#-MHk6VrJ2wZqqYUqgxjD:-MHk6VrK5z5YBPQIIA3T:bdrsytq) ([raw file](https://github.com/pmem/rpma/blob/fe497689b7a669fb8677d966e6007059d3ad6d9b/examples/09-flush-to-persistent-GPSPM/server.c#L290)):*
> ```C
> 
> err_req_delete:
> 	if (req)
> ```

This '`if`' is redundant. `rpma_conn_req_delete()` can be called with `req == 0`

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/412)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[examples/09-flush-to-persistent-GPSPM/server.c, line 287 at r1](https://reviewable.io/reviews/pmem/rpma/412#-MHkBSGP61XlJ_5WDIw5:-MHkHMDxAafk8pyG5BMs:b4ypr09) ([raw file](https://github.com/pmem/rpma/blob/fe497689b7a669fb8677d966e6007059d3ad6d9b/examples/09-flush-to-persistent-GPSPM/server.c#L287)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why not `(void) rpma_conn_delete(&conn);` as it was before?
</blockquote></details>

Because it needs to be added in each incorrect path.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/412)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[examples/09-flush-to-persistent-GPSPM/server.c, line 287 at r1](https://reviewable.io/reviews/pmem/rpma/412#-MHkBSGP61XlJ_5WDIw5:-MHkIAIL7_vCzEY0K8Mk:b-s1kq6k) ([raw file](https://github.com/pmem/rpma/blob/fe497689b7a669fb8677d966e6007059d3ad6d9b/examples/09-flush-to-persistent-GPSPM/server.c#L287)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Because it needs to be added in each incorrect path.
</blockquote></details>

No just here, I meant to replace `(void) common_wait_for_conn_close_and_disconnect(&conn);` with  `(void) rpma_conn_delete(&conn); `  exactly here.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/412)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[examples/09-flush-to-persistent-GPSPM/server.c, line 287 at r1](https://reviewable.io/reviews/pmem/rpma/412#-MHkBSGP61XlJ_5WDIw5:-MHkME8w0NmqfxnqmNG1:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fe497689b7a669fb8677d966e6007059d3ad6d9b/examples/09-flush-to-persistent-GPSPM/server.c#L287)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

No just here, I meant to replace `(void) common_wait_for_conn_close_and_disconnect(&conn);` with  `(void) rpma_conn_delete(&conn); `  exactly here.
</blockquote></details>

Done.
___
*[examples/09-flush-to-persistent-GPSPM/server.c, line 290 at r1](https://reviewable.io/reviews/pmem/rpma/412#-MHk6VrJ2wZqqYUqgxjD:-MHkMF2T6o8N7CK3ozpu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fe497689b7a669fb8677d966e6007059d3ad6d9b/examples/09-flush-to-persistent-GPSPM/server.c#L290)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

This '`if`' is redundant. `rpma_conn_req_delete()` can be called with `req == 0`
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/412)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
:lgtm:

@grom please review

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/412#-:-MHkdoYJ2SIFHR0EzAHb:beoi05i)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
I meant:

@grom72 please review (sorry @GroM, please ignore it)

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/412#-:-MHkduV1ExasQLFxn7xn:b-5zl91d)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
@grom72 please review :-)

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/412#-:-MHwC7yZ1-0sG_SdpyMy:bqo5azn)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
I hate goto:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/412#-:-MI-CPXM9SBKOKL7ueKI:b8kiuy5)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/412#-:-MI-CecA35OJAQwMM8lE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/412)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
