### PR TITLE
tools: add EMON commands to REMOTE_CMD_PRE/POST + fixes

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/960)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/960)* status: all files reviewed, 6 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/rpma_fio_bench.sh, line 45 at r1](https://reviewable.io/reviews/pmem/rpma/960#-MWe6-wU20FvkqU1wazr:-MWe6-wU20FvkqU1wazs:b-4a1y89) ([raw file](https://github.com/pmem/rpma/blob/18cac02d63665f1b4ba1c6c8ababf618f2d3e715/tools/perf/rpma_fio_bench.sh#L45)):*
> ```Shell
> 	echo
> 	echo "export REMOTE_ANOTHER_NUMA=1"
> 	echo "export REMOTE_EMON_RESULTS_DIR=/tmp/"
> ```

Please reuse for both sar and emon.
___
*[tools/perf/rpma_fio_bench.sh, line 46 at r1](https://reviewable.io/reviews/pmem/rpma/960#-MWe6Ofj-ssumWCP3Gf_:-MWe6Ofj-ssumWCP3Gfa:b-b35li9) ([raw file](https://github.com/pmem/rpma/blob/18cac02d63665f1b4ba1c6c8ababf618f2d3e715/tools/perf/rpma_fio_bench.sh#L46)):*
> ```Shell
> 	echo "export REMOTE_ANOTHER_NUMA=1"
> 	echo "export REMOTE_EMON_RESULTS_DIR=/tmp/"
> 	echo "export EDP_EVENTS_PATH=/path/to/edp/events/list"
> ```

event_list ;-)
___
*[tools/perf/rpma_fio_bench.sh, line 47 at r1](https://reviewable.io/reviews/pmem/rpma/960#-MWe5NuNE2T8txqApKEa:-MWe5NuNE2T8txqApKEb:bnw600s) ([raw file](https://github.com/pmem/rpma/blob/18cac02d63665f1b4ba1c6c8ababf618f2d3e715/tools/perf/rpma_fio_bench.sh#L47)):*
> ```Shell
> 	echo "export REMOTE_EMON_RESULTS_DIR=/tmp/"
> 	echo "export EDP_EVENTS_PATH=/path/to/edp/events/list"
> 	echo "export REMOTE_CMD_PRE='numactl -N \${REMOTE_ANOTHER_NUMA} emon -i \${EDP_EVENTS} -nb > \${REMOTE_EMON_RESULTS_DIR}\${RUN_NAME}_emon.dat'"
> ```

Please do not replace sar example. Add EMON as another one.
___
*[tools/perf/rpma_fio_bench.sh, line 47 at r1](https://reviewable.io/reviews/pmem/rpma/960#-MWe7nyW6FluhCyp4AS7:-MWe7nyW6FluhCyp4AS8:b-t3ngke) ([raw file](https://github.com/pmem/rpma/blob/18cac02d63665f1b4ba1c6c8ababf618f2d3e715/tools/perf/rpma_fio_bench.sh#L47)):*
> ```Shell
> 	echo "export REMOTE_EMON_RESULTS_DIR=/tmp/"
> 	echo "export EDP_EVENTS_PATH=/path/to/edp/events/list"
> 	echo "export REMOTE_CMD_PRE='numactl -N \${REMOTE_ANOTHER_NUMA} emon -i \${EDP_EVENTS} -nb > \${REMOTE_EMON_RESULTS_DIR}\${RUN_NAME}_emon.dat'"
> ```

It seems you are missing here:

```sh
$ source /opt/intel/sep/sep_vars.sh
```

Before even running emon.
___
*[tools/perf/rpma_fio_bench.sh, line 86 at r1](https://reviewable.io/reviews/pmem/rpma/960#-MWe6vs4-l62SM7CUsZ4:-MWe6vs4-l62SM7CUsZ5:b-xx00ti) ([raw file](https://github.com/pmem/rpma/blob/18cac02d63665f1b4ba1c6c8ababf618f2d3e715/tools/perf/rpma_fio_bench.sh#L86)):*
> ```Shell
> 	echo
> 	echo "export REMOTE_ANOTHER_NUMA=$REMOTE_ANOTHER_NUMA"
> 	echo "export EDP_EVENTS_PATH=$EDP_EVENTS_PATH"
> ```

Please remove. Not used by the script.
___
*[tools/perf/rpma_fio_bench.sh, line 425 at r1](https://reviewable.io/reviews/pmem/rpma/960#-MWe7JjnBYNbQ78RdhBi:-MWe7JjnBYNbQ78RdhBj:b-f2bzjc) ([raw file](https://github.com/pmem/rpma/blob/18cac02d63665f1b4ba1c6c8ababf618f2d3e715/tools/perf/rpma_fio_bench.sh#L425)):*
> ```Shell
> 				echo "$REMOTE_CMD_PRE_SUBST"
> 				sshpass -p "$REMOTE_PASS" -v ssh -o StrictHostKeyChecking=no \
> 					$REMOTE_USER@$SERVER_IP "$REMOTE_CMD_PRE_SUBST > ${REMOTE_EMON_RESULTS_DIR}/${RUN_NAME}_emon.dat" 2>>$LOG_ERR
> ```

It seems unnecessary. Please sort it out.

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/960)* status: all files reviewed, 7 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/rpma_fio_bench.sh, line 423 at r1](https://reviewable.io/reviews/pmem/rpma/960#-MWe8xvG5VNNgwcdSAVG:-MWe8xvG5VNNgwcdSAVH:b-4pjwfc) ([raw file](https://github.com/pmem/rpma/blob/684f4a099123abe3553c826b589cfbcb9b7d30f6/tools/perf/rpma_fio_bench.sh#L423)):*
> ```Shell
> 				echo "$REMOTE_CMD_PRE_SUBST"
> 				sshpass -p "$REMOTE_PASS" -v ssh -o StrictHostKeyChecking=no \
> 					$REMOTE_USER@$SERVER_IP "$REMOTE_CMD_PRE_SUBST" 2>>$LOG_ERR &
> ```

Please leave the `&` character here.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/960)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/rpma_fio_bench.sh, line 45 at r1](https://reviewable.io/reviews/pmem/rpma/960#-MWe6-wU20FvkqU1wazr:-MWenr8478x3CEWsUPC-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/18cac02d63665f1b4ba1c6c8ababf618f2d3e715/tools/perf/rpma_fio_bench.sh#L45)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please reuse for both sar and emon.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 46 at r1](https://reviewable.io/reviews/pmem/rpma/960#-MWe6Ofj-ssumWCP3Gf_:-MWenydA7hLnzUjn1ZCE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/18cac02d63665f1b4ba1c6c8ababf618f2d3e715/tools/perf/rpma_fio_bench.sh#L46)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

event_list ;-)
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 47 at r1](https://reviewable.io/reviews/pmem/rpma/960#-MWe5NuNE2T8txqApKEa:-MWeoEqC8n53H6co9XqQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/18cac02d63665f1b4ba1c6c8ababf618f2d3e715/tools/perf/rpma_fio_bench.sh#L47)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please do not replace sar example. Add EMON as another one.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 47 at r1](https://reviewable.io/reviews/pmem/rpma/960#-MWe7nyW6FluhCyp4AS7:-MWeoUjQ7GG4oDKIPyIp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/18cac02d63665f1b4ba1c6c8ababf618f2d3e715/tools/perf/rpma_fio_bench.sh#L47)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It seems you are missing here:

```sh
$ source /opt/intel/sep/sep_vars.sh
```

Before even running emon.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 86 at r1](https://reviewable.io/reviews/pmem/rpma/960#-MWe6vs4-l62SM7CUsZ4:-MWeoZ0DAEinOgErJF78:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/18cac02d63665f1b4ba1c6c8ababf618f2d3e715/tools/perf/rpma_fio_bench.sh#L86)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please remove. Not used by the script.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 423 at r1](https://reviewable.io/reviews/pmem/rpma/960#-MWe8xvG5VNNgwcdSAVG:-MWeohuk-9DITP2yxWkN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/684f4a099123abe3553c826b589cfbcb9b7d30f6/tools/perf/rpma_fio_bench.sh#L423)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please leave the `&` character here.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 425 at r1](https://reviewable.io/reviews/pmem/rpma/960#-MWe7JjnBYNbQ78RdhBi:-MWeohVn4jfGlXjFJvz2:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/18cac02d63665f1b4ba1c6c8ababf618f2d3e715/tools/perf/rpma_fio_bench.sh#L425)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It seems unnecessary. Please sort it out.
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/960)* status: all files reviewed, 5 unresolved discussions (waiting on @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/960#-MWfG9EcAW7VvtAlY71A:-MWfG9EcAW7VvtAlY71B:b-6dxy05) (no related file):*
Please add to the commit message and the PR something like `+ fixes` since this PR also contain those.

---
___
*[tools/perf/rpma_fio_bench.sh, line 46 at r3](https://reviewable.io/reviews/pmem/rpma/960#-MWfFRJWDPXDnnokd40m:-MWfFRJWDPXDnnokd40n:b-k84qx2) ([raw file](https://github.com/pmem/rpma/blob/f43752ee7caf8f0eb8e4b04f9873e28932461ea9/tools/perf/rpma_fio_bench.sh#L46)):*
> ```Shell
> 	echo "export REMOTE_ANOTHER_NUMA=1"
> 	echo "export REMOTE_RESULTS_DIR=/tmp/"
> 	echo "export REMOTE_CMD_PRE='rm -f \${REMOTE_SAR_RESULTS_DIR}sar.dat; numactl -N \${REMOTE_ANOTHER_NUMA} sar -u -P \${REMOTE_JOB_NUMA_CPULIST} -o \${REMOTE_SAR_RESULTS_DIR}sar.dat 5 > /dev/null'"
> ```

I would insert before sar-specific example something like:
```sh
echo "In case you would like to collect sar data:"
```
___
*[tools/perf/rpma_fio_bench.sh, line 48 at r3](https://reviewable.io/reviews/pmem/rpma/960#-MWfFjwNE94OoMmibTku:-MWfFjwNE94OoMmibTkv:b-982t45) ([raw file](https://github.com/pmem/rpma/blob/f43752ee7caf8f0eb8e4b04f9873e28932461ea9/tools/perf/rpma_fio_bench.sh#L48)):*
> ```Shell
> 	echo "export REMOTE_CMD_PRE='rm -f \${REMOTE_SAR_RESULTS_DIR}sar.dat; numactl -N \${REMOTE_ANOTHER_NUMA} sar -u -P \${REMOTE_JOB_NUMA_CPULIST} -o \${REMOTE_SAR_RESULTS_DIR}sar.dat 5 > /dev/null'"
> 	echo "export REMOTE_CMD_POST='sleep 10; killall -9 sar; sadf -d -- -u -P \${REMOTE_JOB_NUMA_CPULIST} \${REMOTE_SAR_RESULTS_DIR}sar.dat > \${REMOTE_SAR_RESULTS_DIR}sar_\${RUN_NAME}.csv'"
> 	echo
> ```

Maybe even instead of this empty line? Up to you.

```sh
echo "In case you would like to collect emon data:"
```
___
*[tools/perf/rpma_fio_bench.sh, line 51 at r3](https://reviewable.io/reviews/pmem/rpma/960#-MWfASzT5f_QlOus5XcQ:-MWfASzT5f_QlOus5XcR:b-jvc32z) ([raw file](https://github.com/pmem/rpma/blob/f43752ee7caf8f0eb8e4b04f9873e28932461ea9/tools/perf/rpma_fio_bench.sh#L51)):*
> ```Shell
> 	echo "export EVENT_LIST=/path/to/edp/events/list"
> 	echo "export REMOTE_CMD_PRE='source /opt/intel/sep/sep_vars.sh; numactl -N \${REMOTE_ANOTHER_NUMA} emon -i \${EVENT_LIST} > \${REMOTE_RESULTS_DIR}\${RUN_NAME}_emon.dat'"
> 	echo "export REMOTE_CMD_POST='sleep 5; emon -stop'"
> ```

Interestingly you have picked 5 seconds sleep instead of 10 seconds sleep we have for `sar`.
Can you share your argument for this?
___
*[tools/perf/rpma_fio_bench.sh, line 580 at r3](https://reviewable.io/reviews/pmem/rpma/960#-MWfApzqEaKvTqSdvBXU:-MWfApzqEaKvTqSdvBXV:bc0irgz) ([raw file](https://github.com/pmem/rpma/blob/684f4a099123abe3553c826b589cfbcb9b7d30f6/tools/perf/rpma_fio_bench.sh#L580)):*
> ```Shell
> 
> REMOTE_CMD_PRE=$(echo "$REMOTE_CMD_PRE" | envsubst)
> REMOTE_CMD_POST=$(echo "$REMOTE_CMD_POST" | envsubst)
> ```

:clap:

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/960)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/960#-MWfG9EcAW7VvtAlY71A:-MWhKxey7UeDSI0_yYFJ:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please add to the commit message and the PR something like `+ fixes` since this PR also contain those.
</blockquote></details>

Done.

---
___
*[tools/perf/rpma_fio_bench.sh, line 46 at r3](https://reviewable.io/reviews/pmem/rpma/960#-MWfFRJWDPXDnnokd40m:-MWhI_Ff4UAQkkxR1eBf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f43752ee7caf8f0eb8e4b04f9873e28932461ea9/tools/perf/rpma_fio_bench.sh#L46)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I would insert before sar-specific example something like:
```sh
echo "In case you would like to collect sar data:"
```
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 48 at r3](https://reviewable.io/reviews/pmem/rpma/960#-MWfFjwNE94OoMmibTku:-MWhIfwo4SJvI-bVhB5I:b-j69fxz) ([raw file](https://github.com/pmem/rpma/blob/f43752ee7caf8f0eb8e4b04f9873e28932461ea9/tools/perf/rpma_fio_bench.sh#L48)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Maybe even instead of this empty line? Up to you.

```sh
echo "In case you would like to collect emon data:"
```
</blockquote></details>

Done. I'll leave this empty line, it increases readability a bit. ;)
___
*[tools/perf/rpma_fio_bench.sh, line 580 at r3](https://reviewable.io/reviews/pmem/rpma/960#-MWfApzqEaKvTqSdvBXU:-MWhJG0I2AFnPNJ2M-bR:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/684f4a099123abe3553c826b589cfbcb9b7d30f6/tools/perf/rpma_fio_bench.sh#L580)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

:clap: 
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/960#-:-MWhTfed8S_Uau53BraB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — COMMENTED** [review]
shall we somehow indicate what EXPORTs are mandatory?

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/960#-:-MWhcj6MEh4zXkBDM99s:b-f2azf)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by janekmi — APPROVED** [review]
Maybe. We can add something like `(required)` suffix or a `Required:` section. But it maybe not obvious since some of them are required conditionally. Nonetheless, it will be a part of another PR.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/960#-:-MWhdCkr8BumcdrI2hyl:b-eu299n)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/960)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/rpma_fio_bench.sh, line 46 at r4](https://reviewable.io/reviews/pmem/rpma/960#-MWhczYf4ylzXQPcqP5Q:-MWhczYf4ylzXQPcqP5R:beewaji) ([raw file](https://github.com/pmem/rpma/blob/4a0bcd8c1520a25d11849c9625dc0a2a52a663ea/tools/perf/rpma_fio_bench.sh#L46)):*
> ```
> echo "In case you would like to collect sar data:"
> ```
```
echo
echo "In case you would like to collect sar data:"
```
___
*[tools/perf/rpma_fio_bench.sh, line 53 at r4](https://reviewable.io/reviews/pmem/rpma/960#-MWhdkb514D8X1Nj3Q9A:-MWhdkb62UrEWTykS8F9:b-3tdvup) ([raw file](https://github.com/pmem/rpma/blob/4a0bcd8c1520a25d11849c9625dc0a2a52a663ea/tools/perf/rpma_fio_bench.sh#L53)):*
> ```
> sleep 10
> ```
do we need so long post-execution delay?

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/960)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tools/perf/rpma_fio_bench.sh, line 46 at r4](https://reviewable.io/reviews/pmem/rpma/960#-MWhczYf4ylzXQPcqP5Q:-MWi2Kt-9t6phnHWyfI6:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4a0bcd8c1520a25d11849c9625dc0a2a52a663ea/tools/perf/rpma_fio_bench.sh#L46)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> echo "In case you would like to collect sar data:"
> ```
```
echo
echo "In case you would like to collect sar data:"
```
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 53 at r4](https://reviewable.io/reviews/pmem/rpma/960#-MWhdkb514D8X1Nj3Q9A:-MWi2WGi7uGtRUjusjHs:b-35t3z3) ([raw file](https://github.com/pmem/rpma/blob/4a0bcd8c1520a25d11849c9625dc0a2a52a663ea/tools/perf/rpma_fio_bench.sh#L53)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> sleep 10
> ```
do we need so long post-execution delay?
</blockquote></details>

It's just a proposal

**Review by janekmi — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/960)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/960#-:-MWiQhTLDzEyikC10oei:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
