### PR TITLE
rpma: add thread safety analysis of the librpma library

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1799)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 2 files at r2, 1 of 2 files at r7, 1 of 1 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1799)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`THREAD_SAFETY.md` line 17 at r9](https://reviewable.io/reviews/pmem/rpma/1799#-N3TpjzN5g392CXJL3Zj:-N3TpjzO6KsOMmrxrCHr:b32w5d) ([raw file](https://github.com/pmem/rpma/blob/896769973b6d5533765adb2c94b19ae4b938213d/THREAD_SAFETY.md#L17)):*
> ```Markdown
> **If the above assumptions are not met, thread safety of the librpma library is not guaranteed.**
> 
> so **the most common scenarios** are following:
> ```

So



_Code quote:_
```Markdown
so
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1799)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[`THREAD_SAFETY.md` line 17 at r9](https://reviewable.io/reviews/pmem/rpma/1799#-N3TpjzN5g392CXJL3Zj:-N3TrL9A2N2iZrOR9FRE:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/896769973b6d5533765adb2c94b19ae4b938213d/THREAD_SAFETY.md#L17)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

So
</blockquote></details>

Done.

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 2 files at r2, 1 of 2 files at r7.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1799)* status: 3 of 4 files reviewed, 6 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[`THREAD_SAFETY.md` line 12 at r9](https://reviewable.io/reviews/pmem/rpma/1799#-N3TpOFE6k3vVRSEFqc7:-N3TpOFE6k3vVRSEFqc8:undefined) ([raw file](https://github.com/pmem/rpma/blob/896769973b6d5533765adb2c94b19ae4b938213d/THREAD_SAFETY.md#L12)):*
> ```Markdown
> 2) many threads may use the same peer (`struct rpma_peer`) to create separate connections,
> 3) there can be only one endpoint (`struct rpma_ep`) and only one thread can use it (call rpma_ep_next_conn_req() on it),
> 4) the whole process of creating a new connection (`struct rpma_conn`) has to be run by exactly one thread (different threads must not be involved in creating the same connection),
> ```





_Suggestion:_
```Markdown
(`struct rpma_conn_req`)
```
___
*[`THREAD_SAFETY.md` line 19 at r9](https://reviewable.io/reviews/pmem/rpma/1799#-N3Tp_gvEW1HIbDy6V2-:-N3Tp_gw8jMT6OrCGtTt:undefined) ([raw file](https://github.com/pmem/rpma/blob/896769973b6d5533765adb2c94b19ae4b938213d/THREAD_SAFETY.md#L19)):*
> ```Markdown
> so **the most common scenarios** are following:
> 1) on the active side: each thread creates and uses a separate connection (`struct rpma_conn`),
> 2) on the passive side: the main thread establishes the connection but the rest of work (including connection shutdown) is done by a separate thread.
> ```





_Suggestion:_
```Markdown
is done by separate threads (if more than one connection is established)
```
___
*[`THREAD_SAFETY.md` line 19 at r9](https://reviewable.io/reviews/pmem/rpma/1799#-N3Tph-n3jTWkIkKRqUt:-N3Tph-n3jTWkIkKRqUu:undefined) ([raw file](https://github.com/pmem/rpma/blob/896769973b6d5533765adb2c94b19ae4b938213d/THREAD_SAFETY.md#L19)):*
> ```Markdown
> so **the most common scenarios** are following:
> 1) on the active side: each thread creates and uses a separate connection (`struct rpma_conn`),
> 2) on the passive side: the main thread establishes the connection but the rest of work (including connection shutdown) is done by a separate thread.
> ```





_Suggestion:_
```Markdown
is done by a separate thread(s) (if more than one connection is established).
```
___
*[`THREAD_SAFETY.md` line 97 at r9](https://reviewable.io/reviews/pmem/rpma/1799#-N3TrLWZ3zZNDeebTpUI:-N3TrLWZ3zZNDeebTpUJ:bo0a316) ([raw file](https://github.com/pmem/rpma/blob/896769973b6d5533765adb2c94b19ae4b938213d/THREAD_SAFETY.md#L97)):*
> ```Markdown
> - rpma_conn_cfg_set_sq_size
> - rpma_conn_cfg_set_timeout
> - rpma_conn_req_new (calls rpma_conn_cfg_get_*() functions)
> ```

We have several suppressions for this API call. Shall we mark it as NOT thread-safe?



_Code quote:_
```Markdown
rpma_conn_req_new 
```
___
*[`THREAD_SAFETY.md` line 101 at r9](https://reviewable.io/reviews/pmem/rpma/1799#-N3Tq7Y-BiCYfDapBruB:-N3Tq7Y-BiCYfDapBruC:b-mxzue1) ([raw file](https://github.com/pmem/rpma/blob/896769973b6d5533765adb2c94b19ae4b938213d/THREAD_SAFETY.md#L101)):*
> ```Markdown
> are thread-safe only if each thread operates on a **separate connection configuration structure** (`struct rpma_conn_cfg`) used only by this one thread. They are not thread-safe if threads operate on one connection configuration structure common for more than one thread.
> 
> The following API calls of the librpma library:
> ```

Shall we add one more assumption: one ``struct rpma_conn_req`` can be used to create only one ``struct rpma_conn``?



_Code quote:_
```Markdown
The following API calls of the librpma library:
- rpma_conn_req_connect
- rpma_conn_req_delete
- rpma_conn_req_get_private_data
- rpma_conn_req_recv

are thread-safe only if each thread operates on a **separate connection request** (`struct rpma_conn_req`) used only by this one thread. They are not thread-safe if threads operate on one connection request common for more than one thread.
```

**Review by osalyk — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1799)* status: all files reviewed, 5 unresolved discussions (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1799)* status: 3 of 4 files reviewed, 5 unresolved discussions (waiting on @grom72)

___
*[`THREAD_SAFETY.md` line 12 at r9](https://reviewable.io/reviews/pmem/rpma/1799#-N3TpOFE6k3vVRSEFqc7:-N3TujgyBRVitsvO7x0n:b2nhky0) ([raw file](https://github.com/pmem/rpma/blob/896769973b6d5533765adb2c94b19ae4b938213d/THREAD_SAFETY.md#L12)):*
> ```Markdown
> 2) many threads may use the same peer (`struct rpma_peer`) to create separate connections,
> 3) there can be only one endpoint (`struct rpma_ep`) and only one thread can use it (call rpma_ep_next_conn_req() on it),
> 4) the whole process of creating a new connection (`struct rpma_conn`) has to be run by exactly one thread (different threads must not be involved in creating the same connection),
> ```

No.
___
*[`THREAD_SAFETY.md` line 19 at r9](https://reviewable.io/reviews/pmem/rpma/1799#-N3Tp_gvEW1HIbDy6V2-:-N3Ttf5o1dxnZGhet4vm:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/896769973b6d5533765adb2c94b19ae4b938213d/THREAD_SAFETY.md#L19)):*
> ```Markdown
> so **the most common scenarios** are following:
> 1) on the active side: each thread creates and uses a separate connection (`struct rpma_conn`),
> 2) on the passive side: the main thread establishes the connection but the rest of work (including connection shutdown) is done by a separate thread.
> ```

Done.
___
*[`THREAD_SAFETY.md` line 19 at r9](https://reviewable.io/reviews/pmem/rpma/1799#-N3Tph-n3jTWkIkKRqUt:-N3Ttfgd9TyLKFFSKEK9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/896769973b6d5533765adb2c94b19ae4b938213d/THREAD_SAFETY.md#L19)):*
> ```Markdown
> so **the most common scenarios** are following:
> 1) on the active side: each thread creates and uses a separate connection (`struct rpma_conn`),
> 2) on the passive side: the main thread establishes the connection but the rest of work (including connection shutdown) is done by a separate thread.
> ```

Done.
___
*[`THREAD_SAFETY.md` line 97 at r9](https://reviewable.io/reviews/pmem/rpma/1799#-N3TrLWZ3zZNDeebTpUI:-N3U-5xWCTcGLBBkd13D:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/896769973b6d5533765adb2c94b19ae4b938213d/THREAD_SAFETY.md#L97)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

We have several suppressions for this API call. Shall we mark it as NOT thread-safe?
</blockquote></details>

Done.
___
*[`THREAD_SAFETY.md` line 101 at r9](https://reviewable.io/reviews/pmem/rpma/1799#-N3Tq7Y-BiCYfDapBruB:-N3U-4pA3xRyYG15AofL:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/896769973b6d5533765adb2c94b19ae4b938213d/THREAD_SAFETY.md#L101)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Shall we add one more assumption: one ``struct rpma_conn_req`` can be used to create only one ``struct rpma_conn``?
</blockquote></details>

Done.

**Review by grom72 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1799)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
