### PR TITLE
rpma: add main assumptions of the analysis of thread safety

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1755)

### CODE REVIEW

**Review by osalyk — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1755)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1755)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[`THREAD_SAFETY.md` line 9 at r2](https://reviewable.io/reviews/pmem/rpma/1755#-N2viB6ZCETZL4QZeXYM:-N2viB6ZCETZL4QZeXYN:b-n4gvqg) ([raw file](https://github.com/pmem/rpma/blob/dcc502e61a2fbb2cafb0be219b78c35d0fd65757/THREAD_SAFETY.md#L9)):*
> ```Markdown
> - each of the connections (`struct rpma_conn`) can be used by only one thread at the same time,
> 
> so the most common situation is when each thread creates and uses a separate connection (`struct rpma_conn`).
> ```

worth mentioning that the following scenario is valid as well (especially on the passive side):
the main thread establish connection but the rest of work (including connection shutdown is don by separate thread)



_Code quote:_
```Markdown
so the most common situation is when each thread creates and uses a separate connection (`struct rpma_conn`).
```

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1755)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @osalyk)

___
*[`THREAD_SAFETY.md` line 9 at r2](https://reviewable.io/reviews/pmem/rpma/1755#-N2viB6ZCETZL4QZeXYM:-N2wp6ZV-OSngrExBzLb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/dcc502e61a2fbb2cafb0be219b78c35d0fd65757/THREAD_SAFETY.md#L9)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

worth mentioning that the following scenario is valid as well (especially on the passive side):
the main thread establish connection but the rest of work (including connection shutdown is don by separate thread)
</blockquote></details>

Done.

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1755#-:-N2z-Y6SD6ujDYyALb_G:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1755)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[`THREAD_SAFETY.md` line 9 at r2](https://reviewable.io/reviews/pmem/rpma/1755#-N2viB6ZCETZL4QZeXYM:-N2zYgqT1vO997oVaFFU:b-7kj3ei) ([raw file](https://github.com/pmem/rpma/blob/dcc502e61a2fbb2cafb0be219b78c35d0fd65757/THREAD_SAFETY.md#L9)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

@grom72 is it OK? Can you resolve this issue?

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1755#-:-N2zb_5E9wWchpHxeh1l:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
