### PR TITLE
common: CircleCI: install packages with debug symbols

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/988)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/988#-:-MY4AXIn7D-IaU6FinN5:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/988#-:-MY4Do627D8V7itoeUtb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/988#-:-MY4EQoL4WtRTAXlXpmy:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/988)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[.circleci/ddebs.list, line 3 at r1](https://reviewable.io/reviews/pmem/rpma/988#-MY4EkHg4xDUN1iB_BTR:-MY4EkHg4xDUN1iB_BTS:b-1j6oje) ([raw file](https://github.com/pmem/rpma/blob/cde2a338175a98052d35866914aac6fb4805c3af/.circleci/ddebs.list#L3)):*
> ```
> deb http://ddebs.ubuntu.com focal main restricted universe multiverse
> deb http://ddebs.ubuntu.com focal-updates main restricted universe multiverse
> deb http://ddebs.ubuntu.com focal-proposed main restricted universe multiverse
> ```

Please add a comment to the CircleCI config next to the OS image version so both will be kept in sync.

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/988)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/988)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[.circleci/ddebs.list, line 3 at r1](https://reviewable.io/reviews/pmem/rpma/988#-MY4FASb66yXXkX0fzQq:-MY4FASb66yXXkX0fzQr:b-dqxnct) ([raw file](https://github.com/pmem/rpma/blob/cde2a338175a98052d35866914aac6fb4805c3af/.circleci/ddebs.list#L3)):*
> ```
> deb http://ddebs.ubuntu.com focal main restricted universe multiverse
> deb http://ddebs.ubuntu.com focal-updates main restricted universe multiverse
> deb http://ddebs.ubuntu.com focal-proposed main restricted universe multiverse
> ```

https://packages.ubuntu.com/focal/lsb-release

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/988)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @janekmi and @osalyk)

___
*[.circleci/ddebs.list, line 3 at r1](https://reviewable.io/reviews/pmem/rpma/988#-MY4FASb66yXXkX0fzQq:-MY4INyi2bD5qOjD0aeK:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cde2a338175a98052d35866914aac6fb4805c3af/.circleci/ddebs.list#L3)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

https://packages.ubuntu.com/focal/lsb-release
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/988)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi and @osalyk)

___
*[.circleci/ddebs.list, line 3 at r1](https://reviewable.io/reviews/pmem/rpma/988#-MY4FASb66yXXkX0fzQq:-MY4LLwq4oDwV9BGhdLQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/cde2a338175a98052d35866914aac6fb4805c3af/.circleci/ddebs.list#L3)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm_strong: 

> Reviewed 2 of 2 files at r2, 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/988#-:-MY4L09r8xjZs_KGHAtS:b-yncq6h)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
