### PR TITLE
rpma: replace enum typedefs with just enums

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/446)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/446#-:-MI2SyuF4V7hr5G1l_uP:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/446#-:-MI2n_8C2AFKeSOrUBmZ:bdycpsm)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[src/include/librpma.h, line 1487 at r1](https://reviewable.io/reviews/pmem/rpma/446#-MI2nEy_7d8ShJptnaL6:-MI2mp8I6aeM-5Yd7n9l:b7jgb19) ([raw file](https://github.com/pmem/rpma/blob/4859cb92c3793d3fac161146691affa47054ef91/src/include/librpma.h#L1487)):*
> ```objc
>  *	#include <librpma.h>
>  *
>  *	int rpma_log_set_threshold(rpma_threshold threshold,
> ```

enum rpma_log_threshold
___
*[src/include/librpma.h, line 1557 at r1](https://reviewable.io/reviews/pmem/rpma/446#-MI2nKzPBAv1Di7YsTXj:-MI2muwV94x52in67ocz:b7jgb19) ([raw file](https://github.com/pmem/rpma/blob/4859cb92c3793d3fac161146691affa47054ef91/src/include/librpma.h#L1557)):*
> ```objc
>  *	#include <librpma.h>
>  *
>  *	int rpma_log_get_threshold(rpma_threshold threshold,
> ```

enum rpma_log_threshold

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/446)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[src/include/librpma.h, line 1487 at r1](https://reviewable.io/reviews/pmem/rpma/446#-MI2nEy_7d8ShJptnaL6:-MI3AVJDAUWMoTuvDwdz:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4859cb92c3793d3fac161146691affa47054ef91/src/include/librpma.h#L1487)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

enum rpma_log_threshold
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 1557 at r1](https://reviewable.io/reviews/pmem/rpma/446#-MI2nKzPBAv1Di7YsTXj:-MI3BEO6DPRUacrert1k:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4859cb92c3793d3fac161146691affa47054ef91/src/include/librpma.h#L1557)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

enum rpma_log_threshold
</blockquote></details>

Done.

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/446#-:-MI3B_DI-myLn88_tlVr:bnfp4nl)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @grom72)

**Pull request merged**
