### PR TITLE
test: add missing suppression for Helgrind

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1026)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1026)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1026#-MZCwdLVCuOYgSZfsPhG:-MZCwdLVCuOYgSZfsPhH:bc4rwwy) (no related file):*
I assume it fails sporadically?

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1026#-MZCwi483-mD-NKwajTs:-MZCwi483-mD-NKwajTt:b3tfoqa) (no related file):*
We do not have any indications of needing the same suppressions for drd?

---
___
*[tests/helgrind.supp, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/1026#-MZCwyqU5ZWoZihvlQ6H:-MZCwyqV4OnqK0p-3yYq:b1j5272) ([raw file](https://github.com/pmem/rpma/blob/df4dc29686c0cea1519e2941226662df22b43b1f/tests/helgrind.supp#L48)):*
> ```
>    fun:rpma_log_default_function
>    ...
> }
> ```

Can you provide a link to the error log pointing out this issue?

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1026)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1026#-MZCwdLVCuOYgSZfsPhG:-MZD0XNZ1srYaRlMkcxz:bb77ufg) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

I assume it fails sporadically?
</blockquote></details>

Yes.

---
*[a discussion](https://reviewable.io/reviews/pmem/rpma/1026#-MZCwi483-mD-NKwajTs:-MZD0Yj3Bt2-Dfb_bp94:b-71d2s6) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

We do not have any indications of needing the same suppressions for drd?
</blockquote></details>

Not yet, but the suppressions are the same for drd and helgrind so far, so I can add the same for drd too. What do you think?

---
___
*[tests/helgrind.supp, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/1026#-MZCwyqU5ZWoZihvlQ6H:-MZD0ptaBRYECedULTP5:bcxyi1d) ([raw file](https://github.com/pmem/rpma/blob/df4dc29686c0cea1519e2941226662df22b43b1f/tests/helgrind.supp#L48)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Can you provide a link to the error log pointing out this issue?
</blockquote></details>

I cannot. It happened during rebuild with ssh in the ssh session.

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1026)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1026#-MZCwi483-mD-NKwajTs:-MZDDZfa4OANLNMouUT2:b-va6ka4) (no related file):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not yet, but the suppressions are the same for drd and helgrind so far, so I can add the same for drd too. What do you think?
</blockquote></details>

I think it will be better to wait to have a reproduction.

---
___
*[tests/helgrind.supp, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/1026#-MZCwyqU5ZWoZihvlQ6H:-MZDFlav68P5oF6bfO_E:b145xhk) ([raw file](https://github.com/pmem/rpma/blob/df4dc29686c0cea1519e2941226662df22b43b1f/tests/helgrind.supp#L48)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

I cannot. It happened during rebuild with ssh in the ssh session.
</blockquote></details>

Yeah... It is very easy to add another suppression but pretty hard to get rid of it.
I think we should draft this PR and wait for another reproduction if you don't mind.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1026)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tests/helgrind.supp, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/1026#-MZCwyqU5ZWoZihvlQ6H:-MZDLJy47-KvsZviVjyX:b32w0x) ([raw file](https://github.com/pmem/rpma/blob/df4dc29686c0cea1519e2941226662df22b43b1f/tests/helgrind.supp#L48)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Yeah... It is very easy to add another suppression but pretty hard to get rid of it.
I think we should draft this PR and wait for another reproduction if you don't mind.
</blockquote></details>

OK

**Comment by ldorau** [comment]
(waiting for the next reproduction)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1026)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tests/helgrind.supp, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/1026#-MZCwyqU5ZWoZihvlQ6H:-MdR0ZPwEJgpND3Q7TAl:b-9s745n) ([raw file](https://github.com/pmem/rpma/blob/15d28e61306bcbc05164308e7d25630aca2a37bb/tests/helgrind.supp#L48)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK
</blockquote></details>

@janekmi It happened :-)
https://app.circleci.com/pipelines/github/pmem/rpma/272/workflows/067b0634-3104-4f66-9741-bfcfd23fea4d/jobs/279

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1026)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tests/helgrind.supp, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/1026#-MZCwyqU5ZWoZihvlQ6H:-MdR0qTF0Y6NLL6iVK-y:b-rhrsbr) ([raw file](https://github.com/pmem/rpma/blob/15d28e61306bcbc05164308e7d25630aca2a37bb/tests/helgrind.supp#L48)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@janekmi It happened :-)
https://app.circleci.com/pipelines/github/pmem/rpma/272/workflows/067b0634-3104-4f66-9741-bfcfd23fea4d/jobs/279

</blockquote></details>

and the 2nd time:
https://app.circleci.com/pipelines/github/ldorau/rpma/577/workflows/ca8dc534-3cec-408f-9dfe-2c0a8c4fff49/jobs/589

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1026)* status: all files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tests/helgrind.supp, line 48 at r1](https://reviewable.io/reviews/pmem/rpma/1026#-MZCwyqU5ZWoZihvlQ6H:-MdR0x0l5KokmuecuYAp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/15d28e61306bcbc05164308e7d25630aca2a37bb/tests/helgrind.supp#L48)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

and the 2nd time:
https://app.circleci.com/pipelines/github/ldorau/rpma/577/workflows/ca8dc534-3cec-408f-9dfe-2c0a8c4fff49/jobs/589

</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1026#-:-MdR2uQI42vY-9dpACgX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1026#-:-MdRYi0Z57Of9dBKsK1O:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
