### PR TITLE
common: add CircleCI build with SoftRoCE support

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] create a CircleCI account for pmem organization

---

This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/980)

### CODE REVIEW

**Comment by ldorau** [comment]
CircleCI build: https://app.circleci.com/pipelines/github/ldorau/rpma/54/workflows/7da3caea-37d2-443b-9c5f-d540c09777de/jobs/58

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/980)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[utils/docker/images/install-cmocka.sh, line 24 at r2](https://reviewable.io/reviews/pmem/rpma/980#-MXgffUPAvkmqYSTqB4G:-MXgffUPAvkmqYSTqB4H:b-dzmhsq) ([raw file](https://github.com/pmem/rpma/blob/4783aef6a3914136b806cfcf630a2da88d520127/utils/docker/images/install-cmocka.sh#L24)):*
> ```Shell
> sudo make -j$(nproc) install
> cd ../..
> sudo rm -rf cmocka
> ```

It seems this directory is created without `sudo`. So, why you have problems deleting it?

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/980)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[.circleci/install-pkgs-ubuntu.sh, line 4 at r2](https://reviewable.io/reviews/pmem/rpma/980#-MXgjWNY98Ku9t5kzgwJ:-MXgjWNY98Ku9t5kzgwK:bb6ht36) ([raw file](https://github.com/pmem/rpma/blob/4783aef6a3914136b806cfcf630a2da88d520127/.circleci/install-pkgs-ubuntu.sh#L4)):*
> ```Shell
> #
> # SPDX-License-Identifier: BSD-3-Clause
> # Copyright 2020, Intel Corporation
> ```

2021
___
*[.circleci/install-pkgs-ubuntu.sh, line 42 at r2](https://reviewable.io/reviews/pmem/rpma/980#-MXgjOM88vcCWDucSsOa:-MXgjOM88vcCWDucSsOb:b-lr82lo) ([raw file](https://github.com/pmem/rpma/blob/4783aef6a3914136b806cfcf630a2da88d520127/.circleci/install-pkgs-ubuntu.sh#L42)):*
FYI:

> W: --force-yes is deprecated, use one of the options starting with --allow instead.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/980)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[.circleci/install-pkgs-ubuntu.sh, line 4 at r2](https://reviewable.io/reviews/pmem/rpma/980#-MXgjWNY98Ku9t5kzgwJ:-MXjsMlE4BO49Q61Z-L3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/4783aef6a3914136b806cfcf630a2da88d520127/.circleci/install-pkgs-ubuntu.sh#L4)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

2021
</blockquote></details>

Done.
___
*[.circleci/install-pkgs-ubuntu.sh, line 42 at r2](https://reviewable.io/reviews/pmem/rpma/980#-MXgjOM88vcCWDucSsOa:-MXjs-9t7aELLmq0-rPE:bv6zmxv) ([raw file](https://github.com/pmem/rpma/blob/4783aef6a3914136b806cfcf630a2da88d520127/.circleci/install-pkgs-ubuntu.sh#L42)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

FYI:

> W: --force-yes is deprecated, use one of the options starting with --allow instead.
</blockquote></details>

I know, but I do not use it - it can be saved somewhere in the image itself. I use here:

```
-y, --yes, --assume-yes
Automatic yes to prompts. Assume "yes" as answer to all prompts and run non-interactively. If an undesirable situation, such as changing a held package or removing an essential package, occurs then apt-get will abort.
```
___
*[utils/docker/images/install-cmocka.sh, line 24 at r2](https://reviewable.io/reviews/pmem/rpma/980#-MXgffUPAvkmqYSTqB4G:-MXjqHjdBwM9PwYbbw4W:b-ofql6) ([raw file](https://github.com/pmem/rpma/blob/4783aef6a3914136b806cfcf630a2da88d520127/utils/docker/images/install-cmocka.sh#L24)):*
Because

> ```
> sudo make -j$(nproc) install
> ```

creates `install-manifest.txt` owned by root inside it.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/980)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[utils/docker/images/install-cmocka.sh, line 24 at r2](https://reviewable.io/reviews/pmem/rpma/980#-MXgffUPAvkmqYSTqB4G:-MXjucAx5-IMSfut3kAg:b-nviabk) ([raw file](https://github.com/pmem/rpma/blob/4783aef6a3914136b806cfcf630a2da88d520127/utils/docker/images/install-cmocka.sh#L24)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Because

> ```
> sudo make -j$(nproc) install
> ```

creates `install-manifest.txt` owned by root inside it.
</blockquote></details>

And this file:

```
-rw-r--r--   1 root   root      54251 04-08 07:15 ./build/src/CMakeFiles/rpma.dir/compiler_depend.internal
```

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/980#-:-MXkJHPf6hGIEgI1aKGu:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/980#-:-MXkKT369fkmqCcW8HWi:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/980)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
