### PR TITLE
examples: use rpma_cq_get_wc() in all examples

### PR DESCRIPTION
**Pull request by yangx-jy**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1519)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1519)* status: 0 of 14 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1519)* status: 0 of 14 files reviewed, all discussions resolved (waiting on @haichangsi and @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 13 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1519)* status: 13 of 14 files reviewed, 1 unresolved discussion (waiting on @haichangsi, @ldorau, and @yangx-jy)

___
*[examples/08-messages-ping-pong/server.c, line 149 at r1](https://reviewable.io/reviews/pmem/rpma/1519#-MuLcT9uAwbu-68jN2TM:-MuLcT9uAwbu-68jN2TN:b-3pdplc) ([raw file](https://github.com/pmem/rpma/blob/eed6fad2036aea2eebf35245b7e91d5dcf5bc96b/examples/08-messages-ping-pong/server.c#L149)):*
> ```C
> 					(void) fprintf(stderr,
> 						"received completion is not as expected (0x%"
> 						PRIXPTR "!= 0x%" PRIXPTR
> ```

one space is missing before `!`:

`" != 0x%"`



_Code quote:_
```C
"!= 0x%"
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1519)* status: 13 of 14 files reviewed, 3 unresolved discussions (waiting on @haichangsi, @ldorau, and @yangx-jy)

___
*[examples/07-atomic-write/client.c, line 47 at r1](https://reviewable.io/reviews/pmem/rpma/1519#-MuLf5DDABjBNO4R1SVb:-MuLf5DDABjBNO4R1SVc:b-abkcx) ([raw file](https://github.com/pmem/rpma/blob/eed6fad2036aea2eebf35245b7e91d5dcf5bc96b/examples/07-atomic-write/client.c#L47)):*
> ```C
> 	size_t remote_size = 0;
> 	size_t used_offset = 0;
> 	struct rpma_mr_local *local_mr = NULL;
> ```

```
	...
	struct rpma_mr_local *local_mr = NULL;

	/* resources - completions */
	int num_wc_got = 0;
	/* expected number of completions == number of words in command line */
	int exp_num_wc = argc - 3;
	struct ibv_wc wc[exp_num_wc];
```



_Code quote:_
```C
	struct rpma_mr_local *local_mr = NULL;
	int exp_num_wc = argc - 3;
	int num_wc_got = 0;
	struct ibv_wc wc[exp_num_wc];
```
___
*[examples/07-atomic-write/client.c, line 194 at r1](https://reviewable.io/reviews/pmem/rpma/1519#-MuLhVbo38h_gttt0gZa:-MuLhVbo38h_gttt0gZb:byqd9r7) ([raw file](https://github.com/pmem/rpma/blob/eed6fad2036aea2eebf35245b7e91d5dcf5bc96b/examples/07-atomic-write/client.c#L194)):*
> ```C
> 	}
> 
> 	/* one of above operations failed in loops */
> ```

/* one of the above operations in the loop failed */



_Code quote:_
```C
/* one of above operations failed in loops */
```

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1519)* status: all files reviewed, 3 unresolved discussions (waiting on @yangx-jy)

**Review by ldorau — COMMENTED** [review]
All CI builds passed: https://github.com/ldorau/rpma/actions/runs/1751119877

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1519#-:-MuLkFqSByWXZaY154kw:b-3zqmwm)* status: all files reviewed, 3 unresolved discussions (waiting on @yangx-jy)

**Review by yangx-jy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1519)* status: 11 of 14 files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[examples/07-atomic-write/client.c, line 47 at r1](https://reviewable.io/reviews/pmem/rpma/1519#-MuLf5DDABjBNO4R1SVb:-MuOr7Ej726ozcndPCFh:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/eed6fad2036aea2eebf35245b7e91d5dcf5bc96b/examples/07-atomic-write/client.c#L47)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
	...
	struct rpma_mr_local *local_mr = NULL;

	/* resources - completions */
	int num_wc_got = 0;
	/* expected number of completions == number of words in command line */
	int exp_num_wc = argc - 3;
	struct ibv_wc wc[exp_num_wc];
```
</blockquote></details>

Done.
___
*[examples/07-atomic-write/client.c, line 194 at r1](https://reviewable.io/reviews/pmem/rpma/1519#-MuLhVbo38h_gttt0gZa:-MuOr3MV8v6zrcGBIVns:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/eed6fad2036aea2eebf35245b7e91d5dcf5bc96b/examples/07-atomic-write/client.c#L194)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

/* one of the above operations in the loop failed */
</blockquote></details>

Done.
___
*[examples/08-messages-ping-pong/server.c, line 149 at r1](https://reviewable.io/reviews/pmem/rpma/1519#-MuLcT9uAwbu-68jN2TM:-MuOr49f15pP-ytk28xq:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/eed6fad2036aea2eebf35245b7e91d5dcf5bc96b/examples/08-messages-ping-pong/server.c#L149)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

one space is missing before `!`:

`" != 0x%"`
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1519)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1519#-:-MuPIt5YEvB43LxR591O:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 11 of 14 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1519#-:-MuPR2OCAv_PlyTZ0gA4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1519)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 13 of 14 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1519)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[examples/07-atomic-write/client.c, line 204 at r2](https://reviewable.io/reviews/pmem/rpma/1519#-MuQKWiT2e1Wk-kmLRWZ:-MuQKWiU0gLhpbV3TvJp:bnete4a) ([raw file](https://github.com/pmem/rpma/blob/58d13f4cda39a67b5485418fbe19d90de9b10b9c/examples/07-atomic-write/client.c#L204)):*
> ```C
> 		goto err_mr_remote_delete;
> 
> 	if (num_wc_got != exp_num_wc) {
> ```

we can not assume that we collect all completions in one call rpma_cq_get_wc
ibv_get_wc waits only for at least one completion to be returned



_Code quote:_
```C
	if (num_wc_got != exp_num_wc) {
```

**Review by grom72 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1519)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1519)* status: all files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[examples/07-atomic-write/client.c, line 204 at r2](https://reviewable.io/reviews/pmem/rpma/1519#-MuQKWiT2e1Wk-kmLRWZ:-MuQbeJc0FmjXRFsRzZU:b-1wvosz) ([raw file](https://github.com/pmem/rpma/blob/58d13f4cda39a67b5485418fbe19d90de9b10b9c/examples/07-atomic-write/client.c#L204)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

we can not assume that we collect all completions in one call rpma_cq_get_wc
ibv_get_wc waits only for at least one completion to be returned

</blockquote></details>

That's right. @yangx-jy if the first completion will be a completion on error (`RPMA_F_COMPLETION_ON_ERROR`), the program can hang on the second `rpma_cq_wait()` call in the loop. There are two correct solutions:
1) https://github.com/ldorau/rpma/blob/examples-changes/examples/07-atomic-write/client.c#L217
    (branch: https://github.com/ldorau/rpma/tree/examples-changes)
2) the previous logic

The first one would be a good example for the `num_entries > 1` case.

**Comment by yangx-jy** [comment]
___
*[examples/07-atomic-write/client.c, line 204 at r2](https://reviewable.io/reviews/pmem/rpma/1519#-MuQKWiT2e1Wk-kmLRWZ:-MuUUxOZEQQQbQ5XoB9M:btt4jvf) ([raw file](https://github.com/pmem/rpma/blob/58d13f4cda39a67b5485418fbe19d90de9b10b9c/examples/07-atomic-write/client.c#L204)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

That's right. @yangx-jy if the first completion will be a completion on error (`RPMA_F_COMPLETION_ON_ERROR`), the program can hang on the second `rpma_cq_wait()` call in the loop. There are two correct solutions:
1) https://github.com/ldorau/rpma/blob/examples-changes/examples/07-atomic-write/client.c#L217
    (branch: https://github.com/ldorau/rpma/tree/examples-changes)
2) the previous logic

The first one would be a good example for the `num_entries > 1` case.

</blockquote></details>

@ldorau 

The first one seems wrong, we have to call `rpma_cq_wait()` including `ibv_req_notify_cq()` before doing other operations every time.
I think it's not suitable for this 07-atomic-write to use rpma_cq_get_wc() with `num_netries > 1`

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1519)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[examples/07-atomic-write/client.c, line 204 at r2](https://reviewable.io/reviews/pmem/rpma/1519#-MuQKWiT2e1Wk-kmLRWZ:-MuUvNqc8hs0vE1hneuE:b-heegir) ([raw file](https://github.com/pmem/rpma/blob/58d13f4cda39a67b5485418fbe19d90de9b10b9c/examples/07-atomic-write/client.c#L204)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

@ldorau 

The first one seems wrong, we have to call `rpma_cq_wait()` including `ibv_req_notify_cq()` before doing other operations every time.
I think it's not suitable for this 07-atomic-write to use rpma_cq_get_wc() with `num_netries > 1` 
</blockquote></details>

OK, I will check it more deeply later.
Could you revert to the previous logic? It will be good to see the replacement of the old API with the new one without changing the logic.

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1519)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[examples/07-atomic-write/client.c, line 204 at r2](https://reviewable.io/reviews/pmem/rpma/1519#-MuQKWiT2e1Wk-kmLRWZ:-MuV3iBfDlgkAEmUXmzC:bl53yat) ([raw file](https://github.com/pmem/rpma/blob/58d13f4cda39a67b5485418fbe19d90de9b10b9c/examples/07-atomic-write/client.c#L204)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK, I will check it more deeply later.
Could you revert to the previous logic? It will be good to see the replacement of the old API with the new one without changing the logic.
</blockquote></details>

Later we will think about the example for the `num_netries > 1` case.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1519#-:-MuVwG2v4EaQ2T1glNZV:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[examples/07-atomic-write/client.c, line 204 at r2](https://reviewable.io/reviews/pmem/rpma/1519#-MuQKWiT2e1Wk-kmLRWZ:-MuVw0F0CG0AuoXV7VLy:b-k095go) ([raw file](https://github.com/pmem/rpma/blob/58d13f4cda39a67b5485418fbe19d90de9b10b9c/examples/07-atomic-write/client.c#L204)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Later we will think about the example for the `num_netries > 1` case.
</blockquote></details>

@yangx-jy Thanks!

**Comment by yangx-jy** [comment]
___
*[examples/07-atomic-write/client.c, line 204 at r2](https://reviewable.io/reviews/pmem/rpma/1519#-MuQKWiT2e1Wk-kmLRWZ:-MuVvMAwDtTVXLjDQRKg:bpm18e1) ([raw file](https://github.com/pmem/rpma/blob/58d13f4cda39a67b5485418fbe19d90de9b10b9c/examples/07-atomic-write/client.c#L204)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@yangx-jy Thanks!
</blockquote></details>

Done.

I use `rpma_cq_get_wc(cq, 1 &wc, NULL)` on example-07 for now.
Recently, I will also think about how to use the `num_entries > 1` in an example and mark `rpma_cq_get_completion()` as deprecated on doc.

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1519)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[examples/07-atomic-write/client.c, line 204 at r2](https://reviewable.io/reviews/pmem/rpma/1519#-MuQKWiT2e1Wk-kmLRWZ:-MuVx6EN9eje-71ouPe6:b-g94wvs) ([raw file](https://github.com/pmem/rpma/blob/58d13f4cda39a67b5485418fbe19d90de9b10b9c/examples/07-atomic-write/client.c#L204)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Done.

I use `rpma_cq_get_wc(cq, 1 &wc, NULL)` on example-07 for now.
Recently, I will also think about how to use the `num_entries > 1` in an example and mark `rpma_cq_get_completion()` as deprecated on doc.
</blockquote></details>

Thanks a lot for this PR!

As regards marking rpma_cq_get_completion() as deprecated in documentation - a member of RPMA team is already working on this, so please leave this task for him. Could you make a similar change to this one in our fio engine instead (replacing `rpma_cq_get_completion` with `rpma_cq_get_wc` at https://github.com/pmem/fio on the `rpma`branch) ?

**Comment by yangx-jy** [comment]
___
*[examples/07-atomic-write/client.c, line 204 at r2](https://reviewable.io/reviews/pmem/rpma/1519#-MuQKWiT2e1Wk-kmLRWZ:-MuW7xyfAcRD4OalYrnv:bg1hnmu) ([raw file](https://github.com/pmem/rpma/blob/58d13f4cda39a67b5485418fbe19d90de9b10b9c/examples/07-atomic-write/client.c#L204)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Thanks a lot for this PR!

As regards marking rpma_cq_get_completion() as deprecated in documentation - a member of RPMA team is already working on this, so please leave this task for him. Could you make a similar change to this one in our fio engine instead (replacing `rpma_cq_get_completion` with `rpma_cq_get_wc` at https://github.com/pmem/fio on the `rpma`branch) ? 
</blockquote></details>

Hi @ldorau 
OK, I won't update the corresponding doc. It's my pleasure to replace `rpma_cq_get_completion` with `rpma_cq_get_wc` in fio. Is it ok to do it next week?

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1519)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[examples/07-atomic-write/client.c, line 204 at r2](https://reviewable.io/reviews/pmem/rpma/1519#-MuQKWiT2e1Wk-kmLRWZ:-MuW9kLQAPLwCh1cXLgY:bvr3502) ([raw file](https://github.com/pmem/rpma/blob/58d13f4cda39a67b5485418fbe19d90de9b10b9c/examples/07-atomic-write/client.c#L204)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi @ldorau 
OK, I won't update the corresponding doc. It's my pleasure to replace `rpma_cq_get_completion` with `rpma_cq_get_wc` in fio. Is it ok to do it next week?
</blockquote></details>

Great ! It is OK to do it next week (if it will not disturb you in celebrating New Year, of course), thanks!

**Pull request merged**
