### PR TITLE
rpma: log GID addresses in rpma_conn_req_from_id()

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] unit tests

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1634)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
An example output:

The server:

```sh
[nesperf@wp164 build]$ ./examples/01-connection/server 192.168.3.4 7203
Mar 29 01:05:41.467438 [20249] *NOTE*  ep.c:  93: rpma_ep_listen: Waiting for incoming connection on 192.168.3.4:7203
Mar 29 01:05:46.345761 [20249] *NOTE*  conn_req.c: 115: rpma_conn_req_from_id: src GID = 0:0:0:0:0:0:0:0:0:0:255:255:192:168:3:4
Mar 29 01:05:46.345821 [20249] *NOTE*  conn_req.c: 122: rpma_conn_req_from_id: dst GID = 0:0:0:0:0:0:0:0:0:0:255:255:192:168:3:5
Mar 29 01:05:46.347024 [20249] *NOTE*  conn.c: 195: rpma_conn_next_event: Connection established
Received a message: Hello server!
Mar 29 01:05:46.347404 [20249] *NOTE*  conn.c: 235: rpma_conn_disconnect: Requesting for disconnection
Mar 29 01:05:46.347784 [20249] *NOTE*  conn.c: 195: rpma_conn_next_event: Connection closed
```

The client:
```sh
[nesperf@wp165 build]$ ./examples/01-connection/client  192.168.3.4 7203
Mar 29 01:05:35.255583 [36175] *NOTE*  conn_req.c: 115: rpma_conn_req_from_id: src GID = 0:0:0:0:0:0:0:0:0:0:255:255:192:168:3:5
Mar 29 01:05:35.255605 [36175] *NOTE*  conn_req.c: 122: rpma_conn_req_from_id: dst GID = 0:0:0:0:0:0:0:0:0:0:255:255:192:168:3:4
Mar 29 01:05:35.255615 [36175] *NOTE*  conn_req.c: 387: rpma_conn_req_new: Requesting a connection to 192.168.3.4:7203
Mar 29 01:05:35.258356 [36175] *NOTE*  conn.c: 195: rpma_conn_next_event: Connection established
Received a message: Hello client!
Mar 29 01:05:35.258818 [36175] *NOTE*  conn.c: 195: rpma_conn_next_event: Connection closed
Mar 29 01:05:35.259115 [36175] *NOTE*  conn.c: 235: rpma_conn_disconnect: Requesting for disconnection
```

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1634#-:-MzKoHY8CAR4_xguFI-B:bnzgyhv)* status: 0 of 8 files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
All builds passed:
https://github.com/ldorau/rpma/actions/runs/2058630489

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1634#-:-MzKonos5eOOErxPotSl:bvqjeg8)* status: 0 of 8 files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
I'm not sure what is the proper format of GID, but this is what I see in /sys/class/infiniband/XXX/ports/1/gids/7:
`0000:0000:0000:0000:0000:ffff:c0a8:0304`

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1634#-:-MzLirlX8TwGqPETVbIw:b-1te162)* status: 0 of 9 files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
I have chosen the perftest's format:

```
254:128:00:00:00:00:00:00:186:206:246:255:254:117:15:252
00:00:00:00:00:00:00:00:00:00:255:255:192:168:03:04
```

While `ibv_devinfo` uses two different formats:

1) for RoCE v2 (the same GIDs as above):

```
fe80::bace:f6ff:fe75:ffc
::ffff:192.168.3.4
```

2) for RoCE v1:

```
fe80:0000:0000:0000:bace:f6ff:fe75:0ffc
0000:0000:0000:0000:0000:ffff:c0a8:0304
```

@grom72 Which is the best one ? ;-)

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1634#-:-MzOZX-D7-JEsSnRQysd:bwee663)* status: 0 of 9 files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
@grom72  Changed to the following format:
```
fe80:0000:0000:0000:bace:f6ff:fe75:0ffc
0000:0000:0000:0000:0000:ffff:c0a8:0304
```

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1634#-:-MzP2dgC81BHROAhjU_H:b-5kapge)* status: 0 of 9 files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
Server's output:

```
[nesperf@wp164 build]$ ./examples/01-connection/server 192.168.102.4 7203
Mar 29 20:54:42.833616 [34174] *NOTE*  ep.c:  93: rpma_ep_listen: Waiting for incoming connection on 192.168.102.4:7203
Mar 29 20:55:07.913896 [34174] *NOTE*  conn_req.c: 115: rpma_conn_req_from_id: src GID = 0000:0000:0000:0000:0000:ffff:c0a8:6604
Mar 29 20:55:07.913921 [34174] *NOTE*  conn_req.c: 122: rpma_conn_req_from_id: dst GID = 0000:0000:0000:0000:0000:ffff:c0a8:6605
Mar 29 20:55:07.915186 [34174] *NOTE*  conn.c: 195: rpma_conn_next_event: Connection established
Received a message: Hello server!
Mar 29 20:55:07.915560 [34174] *NOTE*  conn.c: 235: rpma_conn_disconnect: Requesting for disconnection
Mar 29 20:55:07.915913 [34174] *NOTE*  conn.c: 195: rpma_conn_next_event: Connection closed
```

Client's output:

```
[nesperf@wp165 build]$ ./examples/01-connection/client  192.168.102.4 7203
Mar 29 20:54:56.665357 [49866] *NOTE*  conn_req.c: 115: rpma_conn_req_from_id: src GID = 0000:0000:0000:0000:0000:ffff:c0a8:6605
Mar 29 20:54:56.665389 [49866] *NOTE*  conn_req.c: 122: rpma_conn_req_from_id: dst GID = 0000:0000:0000:0000:0000:ffff:c0a8:6604
Mar 29 20:54:56.665400 [49866] *NOTE*  conn_req.c: 387: rpma_conn_req_new: Requesting a connection to 192.168.102.4:7203
Mar 29 20:54:56.668196 [49866] *NOTE*  conn.c: 195: rpma_conn_next_event: Connection established
Received a message: Hello client!
Mar 29 20:54:56.668666 [49866] *NOTE*  conn.c: 195: rpma_conn_next_event: Connection closed
Mar 29 20:54:56.668940 [49866] *NOTE*  conn.c: 235: rpma_conn_disconnect: Requesting for disconnection
```

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1634#-:-MzP3T7W0xohosGCHZMQ:b-g1x3yg)* status: 0 of 9 files reviewed, all discussions resolved

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 2 files at r1, 7 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1634)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1634)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 2 files at r1, 8 of 8 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1634#-:-MzTmdp31kBg4IYEOVE1:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by grom72 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1634#-:-MzU_n56EgflInZ7a_GS:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
