### PR TITLE
test: fix the usage of will_return_maybe() in unit tests 

### PR DESCRIPTION
**Pull request by yangx-jy**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1109)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1109)* status: 0 of 16 files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[tests/unit/conn/conn-new.c, line 100 at r1](https://reviewable.io/reviews/pmem/rpma/1109#-MdNrsM57bCQxbLOTq7O:-MdNrsM57bCQxbLOTq7P:bb0wi0w) ([raw file](https://github.com/pmem/rpma/blob/06dec8096e750dc404850e536b38e62cc043ac1e/tests/unit/conn/conn-new.c#L100)):*
> ```C
> 	will_return(rdma_create_event_channel, MOCK_ERRNO);
> 	will_return_maybe(rpma_flush_new, MOCK_OK);
> 	will_return_maybe(__wrap__test_malloc, MOCK_OK);
> ```

The `will_return_maybe()` is used here and in many other unittests because testing the implementation as black-boxy as possible it is not known what will be called first `rdma_create_event_channel()` or `rpma_flush_new()`. So, without the `..._maybe()` function this and many other unittests are tightly coupled with the EXACT implementation where the order of these and many other operations is not determined and may be changed without changing unittests as long as it still complies with all other requirements.

**Review by yangx-jy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1109)* status: 0 of 16 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tests/unit/conn/conn-new.c, line 100 at r1](https://reviewable.io/reviews/pmem/rpma/1109#-MdNrsM57bCQxbLOTq7O:-MdPNUAU59Etp4OOP_jG:b-tvt3pw) ([raw file](https://github.com/pmem/rpma/blob/06dec8096e750dc404850e536b38e62cc043ac1e/tests/unit/conn/conn-new.c#L100)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The `will_return_maybe()` is used here and in many other unittests because testing the implementation as black-boxy as possible it is not known what will be called first `rdma_create_event_channel()` or `rpma_flush_new()`. So, without the `..._maybe()` function this and many other unittests are tightly coupled with the EXACT implementation where the order of these and many other operations is not determined and may be changed without changing unittests as long as it still complies with all other requirements.
</blockquote></details>

Hi @janekmi 

Thanks for your explanation.
Do you know how to run these unit tests in black-boxy?  I didn't realize the order of these functions (`rdma_create_event_channel()`, `rpma_flush_new()`, `test_malloc` is not fixed before.

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1109)* status: 0 of 16 files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[tests/unit/conn/conn-new.c, line 100 at r1](https://reviewable.io/reviews/pmem/rpma/1109#-MdNrsM57bCQxbLOTq7O:-MdRUZ6t5beUHVMta8dC:bvjllpv) ([raw file](https://github.com/pmem/rpma/blob/06dec8096e750dc404850e536b38e62cc043ac1e/tests/unit/conn/conn-new.c#L100)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

Hi @janekmi 

Thanks for your explanation.
Do you know how to run these unit tests in black-boxy?  I didn't realize the order of these functions (`rdma_create_event_channel()`, `rpma_flush_new()`, `test_malloc` is not fixed before.

</blockquote></details>

By the 'black-box' testing I mean testing (or unittesting to be exact) assuming as little as possible about what is going on inside.

Ref: https://en.wikipedia.org/wiki/Black-box_testing

**Review by yangx-jy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1109)* status: 0 of 16 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tests/unit/conn/conn-new.c, line 100 at r1](https://reviewable.io/reviews/pmem/rpma/1109#-MdNrsM57bCQxbLOTq7O:-MdS5KnS1qbfbn3CtjmB:b-vwmsf5) ([raw file](https://github.com/pmem/rpma/blob/06dec8096e750dc404850e536b38e62cc043ac1e/tests/unit/conn/conn-new.c#L100)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

By the 'black-box' testing I mean testing (or unittesting to be exact) assuming as little as possible about what is going on inside.

Ref: https://en.wikipedia.org/wiki/Black-box_testing
</blockquote></details>

The rule (in other words: the usage of `will_return_maybe()`) is not clear for me.
It seems that a lot of unit tests don't use `will_return_maybe()` so how can I know which unit tests should call `will_return_maybe()`.

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1109)* status: 0 of 16 files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[tests/unit/conn/conn-new.c, line 100 at r1](https://reviewable.io/reviews/pmem/rpma/1109#-MdNrsM57bCQxbLOTq7O:-MdS8eXC2RNVVnV_FkbW:b-3j7i9f) ([raw file](https://github.com/pmem/rpma/blob/06dec8096e750dc404850e536b38e62cc043ac1e/tests/unit/conn/conn-new.c#L100)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

The rule (in other words: the usage of `will_return_maybe()`) is not clear for me.
It seems that a lot of unit tests don't use `will_return_maybe()` so how can I know which unit tests should call `will_return_maybe()`.

</blockquote></details>

The rule is as follow:

1. When you test a function that implements a single sequence of operations that can not be implemented in any other order (A -> B -> C) you should NOT use `will_return_maybe()`.
2. Otherwise (e.g. A -> B -> D and C -> D, note both B and C are required to perform D), it depends:
    - When during the test the D step will fail (but all previous steps have to succeed) you should NOT use `will_return_maybe()`.
    - When during the test the B step will fail you should:
        - do NOT use `will_return_maybe()` for the A step because it is required for the B step, but
        - use `will_return_maybe()` for the step C!

This way both implementations will be correct:

```
A
B
C
D
```

as well as:

```
C
A
B
D
```

Or any other order where the C step is executed before the D step but can be performed before and after the A and B steps.

**Review by yangx-jy — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1109)* status: 0 of 16 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tests/unit/conn/conn-new.c, line 100 at r1](https://reviewable.io/reviews/pmem/rpma/1109#-MdNrsM57bCQxbLOTq7O:-MdV2fVH7N0enE4_XuC4:b8ggu59) ([raw file](https://github.com/pmem/rpma/blob/06dec8096e750dc404850e536b38e62cc043ac1e/tests/unit/conn/conn-new.c#L100)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The rule is as follow:

1. When you test a function that implements a single sequence of operations that can not be implemented in any other order (A -> B -> C) you should NOT use `will_return_maybe()`.
2. Otherwise (e.g. A -> B -> D and C -> D, note both B and C are required to perform D), it depends:
    - When during the test the D step will fail (but all previous steps have to succeed) you should NOT use `will_return_maybe()`.
    - When during the test the B step will fail you should:
        - do NOT use `will_return_maybe()` for the A step because it is required for the B step, but
        - use `will_return_maybe()` for the step C!

This way both implementations will be correct:

```
A
B
C
D
```

as well as:

```
C
A
B
D
```

Or any other order where the C step is executed before the D step but can be performed before and after the A and B steps.
</blockquote></details>

Cool. If step C or B will fail, is it OK to use `will_return_maybe()` for step D? (I think it is OK.)

BTW: I have updated the PR to correct the usage of `will_return_maybe().

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1109)* status: 0 of 16 files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

___
*[tests/unit/conn/conn-new.c, line 100 at r1](https://reviewable.io/reviews/pmem/rpma/1109#-MdNrsM57bCQxbLOTq7O:-MdWDnDoDjboo8oXBg__:b6dox3l) ([raw file](https://github.com/pmem/rpma/blob/06dec8096e750dc404850e536b38e62cc043ac1e/tests/unit/conn/conn-new.c#L100)):*
> If step C or B will fail, is it OK to use will_return_maybe() for step D?

No. Because a correct implementation should detect C or B has failed and it can not continue to D. So D should NOT be called.

> BTW: I have updated the PR to correct the usage of `will_return_maybe().

Great. I will try to review it soon.

**Review by ldorau — COMMENTED** [review]
> Reviewed 9 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1109)* status: 9 of 16 files reviewed, 1 unresolved discussion (waiting on @yangx-jy)

**Review by janekmi — APPROVED** [review]
> Reviewed 2 of 16 files at r1, 5 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1109)* status: all files reviewed, 4 unresolved discussions (waiting on @yangx-jy)

___
*[tests/unit/conn/conn-new.c, line 166 at r2](https://reviewable.io/reviews/pmem/rpma/1109#-MeAAG8N3hF2oOYSl583:-MeAAG8O8Cn6SrFcgouo:b-q8g9wx) ([raw file](https://github.com/pmem/rpma/blob/0a4286968812fa3892cc4c8fa8b0771e8c8e0f33/tests/unit/conn/conn-new.c#L166)):*
> ```C
> 	will_return_maybe(rdma_migrate_id, MOCK_OK);
> 	will_return_maybe(rpma_flush_new, MOCK_OK);
> 	will_return_maybe(rpma_flush_delete, MOCK_OK);
> ```

```c
will_return_maybe(rdma_destroy_event_channel, MOCK_OK);
```

Is missing here.
___
*[tests/unit/conn/conn-next_event.c, line 205 at r2](https://reviewable.io/reviews/pmem/rpma/1109#-MeABvxsAx9Ew3Aa3DQI:-MeABvxsAx9Ew3Aa3DQJ:b-b9wgxx) ([raw file](https://github.com/pmem/rpma/blob/0a4286968812fa3892cc4c8fa8b0771e8c8e0f33/tests/unit/conn/conn-next_event.c#L205)):*
> ```C
> 	will_return(rdma_ack_cm_event, MOCK_OK);
> 
> 	will_return(rpma_private_data_store, MOCK_OK);
> ```

Please put this one before the previous two.
Just to keep the logical order.
___
*[tests/unit/conn/conn-next_event.c, line 250 at r2](https://reviewable.io/reviews/pmem/rpma/1109#-MeAC64g4aUSt2InVgxm:-MeAC64hB32c-jK6ERsG:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/0a4286968812fa3892cc4c8fa8b0771e8c8e0f33/tests/unit/conn/conn-next_event.c#L250)):*
> ```C
> 	will_return(rdma_ack_cm_event, MOCK_OK);
> 
> 	will_return(rpma_private_data_store, MOCK_OK);
> ```

.
___
*[tests/unit/mr/mr-reg.c, line 170 at r2](https://reviewable.io/reviews/pmem/rpma/1109#-MeAGelN-l4vMeb7GEKP:-MeAGelN-l4vMeb7GEKQ:b17sylc) ([raw file](https://github.com/pmem/rpma/blob/0a4286968812fa3892cc4c8fa8b0771e8c8e0f33/tests/unit/mr/mr-reg.c#L170)):*
> ```C
> 	mr_reg_args.verrno = MOCK_ERRNO;
> 	will_return(rpma_peer_mr_reg, &mr_reg_args);
> 	will_return_maybe(__wrap__test_malloc, MOCK_OK);
> ```

`will_return_maybe()` for a free is missing here.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 16 files at r1, 1 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1109)* status: all files reviewed, 4 unresolved discussions (waiting on @yangx-jy)

**Review by ldorau — APPROVED** [review]
It will Look Good To Me when the current 4 issues are fixed.

> Reviewed 1 of 16 files at r1, 4 of 14 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1109#-:-MeATjz01IbJMy6LepaA:b-b4zyhl)* status: all files reviewed, 4 unresolved discussions (waiting on @yangx-jy)

**Comment by yangx-jy** [comment]
> > Reviewed 2 of 16 files at r1, 5 of 14 files at r2.
> > _[Reviewable](https://reviewable.io/reviews/pmem/rpma/1109)_ status: all files reviewed, 4 unresolved discussions (waiting on @yangx-jy)
> 
> _[tests/unit/conn/conn-new.c, line 166 at r2](https://reviewable.io/reviews/pmem/rpma/1109#-MeAAG8N3hF2oOYSl583:-MeAAG8O8Cn6SrFcgouo:b-q8g9wx) ([raw file](https://github.com/pmem/rpma/blob/0a4286968812fa3892cc4c8fa8b0771e8c8e0f33/tests/unit/conn/conn-new.c#L166)):_
> 
> > ```c
> > 	will_return_maybe(rdma_migrate_id, MOCK_OK);
> > 	will_return_maybe(rpma_flush_new, MOCK_OK);
> > 	will_return_maybe(rpma_flush_delete, MOCK_OK);
> > ```
> 
> ```c
> will_return_maybe(rdma_destroy_event_channel, MOCK_OK);
> ```
> 
> Is missing here.

It seems wrong because `rdma_destroy_event_channel()` has no return value.

> 
> _[tests/unit/conn/conn-next_event.c, line 205 at r2](https://reviewable.io/reviews/pmem/rpma/1109#-MeABvxsAx9Ew3Aa3DQI:-MeABvxsAx9Ew3Aa3DQJ:b-b9wgxx) ([raw file](https://github.com/pmem/rpma/blob/0a4286968812fa3892cc4c8fa8b0771e8c8e0f33/tests/unit/conn/conn-next_event.c#L205)):_
> 
> > ```c
> > 	will_return(rdma_ack_cm_event, MOCK_OK);
> > 
> > 	will_return(rpma_private_data_store, MOCK_OK);
> > ```
> 
> Please put this one before the previous two.
> Just to keep the logical order.

Done.

> 
> _[tests/unit/conn/conn-next_event.c, line 250 at r2](https://reviewable.io/reviews/pmem/rpma/1109#-MeAC64g4aUSt2InVgxm:-MeAC64hB32c-jK6ERsG:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/0a4286968812fa3892cc4c8fa8b0771e8c8e0f33/tests/unit/conn/conn-next_event.c#L250)):_
> 
> > ```c
> > 	will_return(rdma_ack_cm_event, MOCK_OK);
> > 
> > 	will_return(rpma_private_data_store, MOCK_OK);
> > ```
> 
> .

Done.

> 
> _[tests/unit/mr/mr-reg.c, line 170 at r2](https://reviewable.io/reviews/pmem/rpma/1109#-MeAGelN-l4vMeb7GEKP:-MeAGelN-l4vMeb7GEKQ:b17sylc) ([raw file](https://github.com/pmem/rpma/blob/0a4286968812fa3892cc4c8fa8b0771e8c8e0f33/tests/unit/mr/mr-reg.c#L170)):_
> 
> > ```c
> > 	mr_reg_args.verrno = MOCK_ERRNO;
> > 	will_return(rpma_peer_mr_reg, &mr_reg_args);
> > 	will_return_maybe(__wrap__test_malloc, MOCK_OK);
> > ```
> 
> `will_return_maybe()` for a free is missing here.

It seems wrong because `free()` has no return value.

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1109)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1109#-:-MeAdgdI6lE5FiQ7opf7:bnfp4nl)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1109#-:-Mehvf-K8N0KoOe5P4Cm:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @yangx-jy)

___
*[tests/unit/conn/conn-new.c, line 166 at r2](https://reviewable.io/reviews/pmem/rpma/1109#-MeAAG8N3hF2oOYSl583:-MehvPT19GSObzHLVxb4:b-d5we66) ([raw file](https://github.com/pmem/rpma/blob/0a4286968812fa3892cc4c8fa8b0771e8c8e0f33/tests/unit/conn/conn-new.c#L166)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

It seems wrong because `rdma_destroy_event_channel()` has no return value.
</blockquote></details>

Oh. You are right. Sorry.
___
*[tests/unit/mr/mr-reg.c, line 170 at r2](https://reviewable.io/reviews/pmem/rpma/1109#-MeAGelN-l4vMeb7GEKP:-MehvaXn8EydStzfEV4i:b-8fx2u7) ([raw file](https://github.com/pmem/rpma/blob/0a4286968812fa3892cc4c8fa8b0771e8c8e0f33/tests/unit/mr/mr-reg.c#L170)):*
<details><summary><i>Previously, yangx-jy (Xiao Yang) wrote…</i></summary><blockquote>

It seems wrong because `free()` has no return value.
</blockquote></details>

:+1:

**Pull request merged**
