### PR TITLE
tools: perf: lib.report reorg

### PR DESCRIPTION
**Pull request by janekmi**
Requires:

- [x] #1375

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1379)

### CODE REVIEW

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1379)* status: 0 of 17 files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1379)* status: 0 of 17 files reviewed, all discussions resolved (waiting on @haichangsi and @ldorau)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1379)* status: 1 of 17 files reviewed, all discussions resolved (waiting on @haichangsi and @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 4 of 17 files at r1, 2 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1379)* status: 7 of 17 files reviewed, 3 unresolved discussions (waiting on @grom72, @haichangsi, @janekmi, and @ldorau)

___
*[tools/perf/lib/report/base.py, line 93 at r2](https://reviewable.io/reviews/pmem/rpma/1379#-MpuKIMh3E42GuExIV8F:-MpuKIMh3E42GuExIV8G:bto63iu) ([raw file](https://github.com/pmem/rpma/blob/a4d13a8b967e5d809932c23d302e1e3bfef3d5fe/tools/perf/lib/report/base.py#L93)):*
> ```
> part.variables = {'figure': self.figures}
> ```
do we bind all report figures to every part
___
*[tools/perf/lib/report/base.py, line 116 at r2](https://reviewable.io/reviews/pmem/rpma/1379#-MpuKeUT69GlNLJDaP2E:-MpuKeUT69GlNLJDaP2F:bdqa27q) ([raw file](https://github.com/pmem/rpma/blob/a4d13a8b967e5d809932c23d302e1e3bfef3d5fe/tools/perf/lib/report/base.py#L116)):*
> ```
> Report.figno += 1
> ```
What is the purpose of this line?
___
*[tools/perf/lib/report/base.py, line 152 at r2](https://reviewable.io/reviews/pmem/rpma/1379#-MpuIgSNCIPCKezxwqwm:-MpuIgSO8r3_wKAMMJUo:bua1cqk) ([raw file](https://github.com/pmem/rpma/blob/a4d13a8b967e5d809932c23d302e1e3bfef3d5fe/tools/perf/lib/report/base.py#L152)):*
> ```
> create
> ```
generate

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1379)* status: 7 of 17 files reviewed, 4 unresolved discussions (waiting on @grom72, @haichangsi, @janekmi, and @ldorau)

___
*[tools/perf/lib/report/__init__.py, line 11 at r2](https://reviewable.io/reviews/pmem/rpma/1379#-MpuLOby5jt86LTgWnQL:-MpuLOby5jt86LTgWnQM:bd6o30t) ([raw file](https://github.com/pmem/rpma/blob/a4d13a8b967e5d809932c23d302e1e3bfef3d5fe/tools/perf/lib/report/__init__.py#L11)):*
> ```
> XXX
> ```
Report and Part introduction is missing

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1379)* status: 7 of 17 files reviewed, 4 unresolved discussions (waiting on @grom72, @haichangsi, @janekmi, and @ldorau)

___
*[tools/perf/lib/report/__init__.py, line 11 at r2](https://reviewable.io/reviews/pmem/rpma/1379#-MpuLOby5jt86LTgWnQL:-MpuMwA_0D9ASCMEqeKe:bswg8ut) ([raw file](https://github.com/pmem/rpma/blob/a4d13a8b967e5d809932c23d302e1e3bfef3d5fe/tools/perf/lib/report/__init__.py#L11)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> XXX
> ```
Report and Part introduction is missing
</blockquote></details>

This the reorg PR. The documentation comes with #1381.
___
*[tools/perf/lib/report/base.py, line 93 at r2](https://reviewable.io/reviews/pmem/rpma/1379#-MpuKIMh3E42GuExIV8F:-MpuUJBM1WDsePtgofBH:b-5ub2kh) ([raw file](https://github.com/pmem/rpma/blob/a4d13a8b967e5d809932c23d302e1e3bfef3d5fe/tools/perf/lib/report/base.py#L93)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> part.variables = {'figure': self.figures}
> ```
do we bind all report figures to every part
</blockquote></details>

Yes. But the figure is looked up by a key anyway. Maybe it is a place for improvement.
___
*[tools/perf/lib/report/base.py, line 152 at r2](https://reviewable.io/reviews/pmem/rpma/1379#-MpuIgSNCIPCKezxwqwm:-MpubOpE3fG8Tf_v8bdu:b-xekfl) ([raw file](https://github.com/pmem/rpma/blob/a4d13a8b967e5d809932c23d302e1e3bfef3d5fe/tools/perf/lib/report/base.py#L152)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> create
> ```
generate
</blockquote></details>

We have also `report_create.py`... I think this kind of renaming can be done later on.

**Review by ldorau — COMMENTED** [review]
> Reviewed 9 of 17 files at r1, 2 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1379)* status: 15 of 17 files reviewed, 4 unresolved discussions (waiting on @grom72, @haichangsi, @janekmi, and @ldorau)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1379)* status: 15 of 17 files reviewed, 4 unresolved discussions (waiting on @grom72, @haichangsi, and @ldorau)

___
*[tools/perf/lib/report/base.py, line 116 at r2](https://reviewable.io/reviews/pmem/rpma/1379#-MpuKeUT69GlNLJDaP2E:-Mpuc_9t4Hee5EOLWaTT:bget4mr) ([raw file](https://github.com/pmem/rpma/blob/a4d13a8b967e5d809932c23d302e1e3bfef3d5fe/tools/perf/lib/report/base.py#L116)):*
> ```
>     # a global figure counter needed for numbering figures within the report
>     figno = 0
> ```

Do we need here to mention how jinja2 filters work?

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 17 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1379)* status: 16 of 17 files reviewed, 2 unresolved discussions (waiting on @grom72, @haichangsi, @janekmi, and @ldorau)

___
*[tools/perf/lib/report/base.py, line 93 at r2](https://reviewable.io/reviews/pmem/rpma/1379#-MpuKIMh3E42GuExIV8F:-MpusMJX-jvPKoIgttCl:b-w7w8fu) ([raw file](https://github.com/pmem/rpma/blob/a4d13a8b967e5d809932c23d302e1e3bfef3d5fe/tools/perf/lib/report/base.py#L93)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Yes. But the figure is looked up by a key anyway. Maybe it is a place for improvement.
</blockquote></details>

Please mark the place with XXX as a potential improvement place
___
*[tools/perf/lib/report/base.py, line 116 at r2](https://reviewable.io/reviews/pmem/rpma/1379#-MpuKeUT69GlNLJDaP2E:-Mpuuai2Ducz9pBtSQA-:bsurmof) ([raw file](https://github.com/pmem/rpma/blob/a4d13a8b967e5d809932c23d302e1e3bfef3d5fe/tools/perf/lib/report/base.py#L116)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

> ```
>     # a global figure counter needed for numbering figures within the report
>     figno = 0
> ```

Do we need here to mention how jinja2 filters work?
</blockquote></details>

at least to mention that it is jinja2 relate
___
*[tools/perf/lib/report/variable.py, line 8 at r2](https://reviewable.io/reviews/pmem/rpma/1379#-MpuvI3y10P1c00HxrZz:-MpuvI3y10P1c00Hxr_-:bfanyt1) ([raw file](https://github.com/pmem/rpma/blob/a4d13a8b967e5d809932c23d302e1e3bfef3d5fe/tools/perf/lib/report/variable.py#L8)):*
> ```
> variable
> ```
utils?

**Review by grom72 — COMMENTED** [review]
:goat:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1379#-:-MpuvNjA8gjIkTMA2q53:bdycps0)* status: 16 of 17 files reviewed, 2 unresolved discussions (waiting on @grom72, @haichangsi, @janekmi, and @ldorau)

**Review by grom72 — COMMENTED** [review]
> Reviewed 8 of 17 files at r1, 1 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1379)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 6 of 17 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1379#-:-Mpv0Fgu2veYEYlKwd0l:bnfp4nl)* status: 16 of 17 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1379)* status: 12 of 17 files reviewed, 1 unresolved discussion (waiting on @grom72 and @ldorau)

___
*[tools/perf/lib/report/variable.py, line 8 at r2](https://reviewable.io/reviews/pmem/rpma/1379#-MpuvI3y10P1c00HxrZz:-Mpv1Gc31W2wXUH3MkYX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a4d13a8b967e5d809932c23d302e1e3bfef3d5fe/tools/perf/lib/report/variable.py#L8)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> variable
> ```
utils?
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 4 files at r2, 2 of 4 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1379)* status: 14 of 17 files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[tools/perf/tests/lib/report/test_init.py, line 121 at r6](https://reviewable.io/reviews/pmem/rpma/1379#-Mpv3fLN8pbV9e_qcUGP:-Mpv3fLN8pbV9e_qcUGQ:b-t75zh7) ([raw file](https://github.com/pmem/rpma/blob/f11fde436432e3a907bf3608b502a8e86f0663e7/tools/perf/tests/lib/report/test_init.py#L121)):*
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>

> ```
>     # XXX how to mock a setter?
>     # def set_variables_mock(self, variables):
>     #     if self.name in ["preamble", "footer"]:
>     #         # XXX assert DeepDiff(variables, VARS_DUMMY_OUT) == {}
>     #         assert variables == VARS_DUMMY_OUT
>     #     else:
>     #         assert 'figure' in variables
>     #         assert 'file_dummy' in variables['figure']
>     #         assert 'key_dummy' in variables['figure']['file_dummy']
>     #         assert variables['figure']['file_dummy']['key_dummy'] == \
>     #             Figure(FIGURE_DUMMY, RESULT_DIR)
> ```
</details>


What is a problem with it?

**Review by ldorau — APPROVED** [review]
> Reviewed 1 of 1 files at r5, 2 of 4 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1379)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1379#-:-MpvAUY61XpdwS7OiIt_:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Pull request merged**
