### PR TITLE
rpma: write the 'MESSAGING' section of the librpma.7 manual

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/500)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/500)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/include/librpma.h, line 134 at r1](https://reviewable.io/reviews/pmem/rpma/500#-MITuRr0A7jjLg4VYEH6:-MITuRr0A7jjLg4VYEH7:bih3m76) ([raw file](https://github.com/pmem/rpma/blob/fb0aa74a9e817b24dbfe6cbdfbe40b52897558f3/src/include/librpma.h#L134)):*
> ```objc
>  *   a buffer for a message sent from other side of the connection,
>  *   but it may be used before the connection is established.
>  *
> ```

Memory buffers used for messaging must be registered with rpma_mr_reg() prior to rpma_send/recv function call.

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/500)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/include/librpma.h, line 120 at r1](https://reviewable.io/reviews/pmem/rpma/500#-MITyLQcBweuNM7yFcbr:-MITyLQcBweuNM7yFcbs:b-45dmpk) ([raw file](https://github.com/pmem/rpma/blob/fb0aa74a9e817b24dbfe6cbdfbe40b52897558f3/src/include/librpma.h#L120)):*
> ```objc
>  *
>  * The librpma messaging API allows transferring messages
>  * (buffers of arbitrary data) between the peers.
> ```

We have no buffers in the section about memory management. I want these to correspond with each other.
___
*[src/include/librpma.h, line 124 at r1](https://reviewable.io/reviews/pmem/rpma/500#-MIU-TJ58YWxRryxx9Gc:-MIU-TJ58YWxRryxx9Gd:bofa2ur) ([raw file](https://github.com/pmem/rpma/blob/fb0aa74a9e817b24dbfe6cbdfbe40b52897558f3/src/include/librpma.h#L124)):*
> ```objc
>  * on the remote side to receive the sent data.
>  * The received data are written to those dedicated buffers
>  * and no remote address has to be specified on the local side.
> ```

The received data are written to those dedicated buffers and sender do not have to have a respective remote memory region object to send the message.

:thinking: 
___
*[src/include/librpma.h, line 133 at r1](https://reviewable.io/reviews/pmem/rpma/500#-MITyc_K0JtESC9rgaSH:-MITyc_LAg5V_QKaQyl1:b-tekjay) ([raw file](https://github.com/pmem/rpma/blob/fb0aa74a9e817b24dbfe6cbdfbe40b52897558f3/src/include/librpma.h#L133)):*
> ```objc
>  * - rpma_conn_req_recv() also initiates the receive operation and prepares
>  *   a buffer for a message sent from other side of the connection,
>  *   but it may be used before the connection is established.
> ```

works as rpma_recv() but it may be used before the connection is established.Ye
___
*[src/include/librpma.h, line 133 at r1](https://reviewable.io/reviews/pmem/rpma/500#-MITzbSH1DytJlMf3ICZ:-MITzbSH1DytJlMf3IC_:b-x69qxo) ([raw file](https://github.com/pmem/rpma/blob/fb0aa74a9e817b24dbfe6cbdfbe40b52897558f3/src/include/librpma.h#L133)):*
> ```objc
>  * - rpma_conn_req_recv() also initiates the receive operation and prepares
>  *   a buffer for a message sent from other side of the connection,
>  *   but it may be used before the connection is established.
> ```

Please refer to completions. We are describing here only the initiation of exchange.
___
*[src/include/librpma.h, line 134 at r1](https://reviewable.io/reviews/pmem/rpma/500#-MITuRr0A7jjLg4VYEH6:-MITyou3695ibch0kpoF:bc9lqmq) ([raw file](https://github.com/pmem/rpma/blob/fb0aa74a9e817b24dbfe6cbdfbe40b52897558f3/src/include/librpma.h#L134)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Memory buffers used for messaging must be registered with rpma_mr_reg() prior to rpma_send/recv function call.
</blockquote></details>

Yes, we should also mention this aspect.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/500)* status: 0 of 1 files reviewed, 5 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[src/include/librpma.h, line 120 at r1](https://reviewable.io/reviews/pmem/rpma/500#-MITyLQcBweuNM7yFcbr:-MIUASMxAMV2vYT7Av5L:bgbpzhk) ([raw file](https://github.com/pmem/rpma/blob/fb0aa74a9e817b24dbfe6cbdfbe40b52897558f3/src/include/librpma.h#L120)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

We have no buffers in the section about memory management. I want these to correspond with each other.
</blockquote></details>

So shall I add buffers to the memory management section ?
___
*[src/include/librpma.h, line 124 at r1](https://reviewable.io/reviews/pmem/rpma/500#-MIU-TJ58YWxRryxx9Gc:-MIUEjPKDWlGaIwDLFRv:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fb0aa74a9e817b24dbfe6cbdfbe40b52897558f3/src/include/librpma.h#L124)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The received data are written to those dedicated buffers and sender do not have to have a respective remote memory region object to send the message.

:thinking: 
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 133 at r1](https://reviewable.io/reviews/pmem/rpma/500#-MITyc_K0JtESC9rgaSH:-MIUF5pJ91-s4Hzl6Zdo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fb0aa74a9e817b24dbfe6cbdfbe40b52897558f3/src/include/librpma.h#L133)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

works as rpma_recv() but it may be used before the connection is established.Ye
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 133 at r1](https://reviewable.io/reviews/pmem/rpma/500#-MITzbSH1DytJlMf3ICZ:-MIUFwKR-xIjw1xhd1Pq:b4car1y) ([raw file](https://github.com/pmem/rpma/blob/fb0aa74a9e817b24dbfe6cbdfbe40b52897558f3/src/include/librpma.h#L133)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please refer to completions. We are describing here only the initiation of exchange.
</blockquote></details>

In what way?
___
*[src/include/librpma.h, line 134 at r1](https://reviewable.io/reviews/pmem/rpma/500#-MITuRr0A7jjLg4VYEH6:-MIUFu4g3uRw0-dKatUP:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fb0aa74a9e817b24dbfe6cbdfbe40b52897558f3/src/include/librpma.h#L134)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Yes, we should also mention this aspect.
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/500)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 133 at r1](https://reviewable.io/reviews/pmem/rpma/500#-MITzbSH1DytJlMf3ICZ:-MIV3LRuD6t9sCnX-JsE:b-8fx2u7) ([raw file](https://github.com/pmem/rpma/blob/fb0aa74a9e817b24dbfe6cbdfbe40b52897558f3/src/include/librpma.h#L133)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

In what way?
</blockquote></details>

:+1:

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/500)* status: all files reviewed, 2 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[src/include/librpma.h, line 120 at r1](https://reviewable.io/reviews/pmem/rpma/500#-MITyLQcBweuNM7yFcbr:-MIV3J0oCjymnaXHQwqc:b-8hxtjz) ([raw file](https://github.com/pmem/rpma/blob/fb0aa74a9e817b24dbfe6cbdfbe40b52897558f3/src/include/librpma.h#L120)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

So shall I add buffers to the memory management section ?
</blockquote></details>

Sadly, I have just merged the memory management section... so my proposition is use consequently the following naming:
- buffer - for any 'memory piece'
- memory region - for a buffer which is registered for RMA / Messaging
- message - for a memory region which is specifically registered for Messaging

Does it make sense?
___
*[src/include/librpma.h, line 133 at r1](https://reviewable.io/reviews/pmem/rpma/500#-MITzbSH1DytJlMf3ICZ:-MIV4Af09Nc4xbLqdYdn:b-8ir9v0) ([raw file](https://github.com/pmem/rpma/blob/fb0aa74a9e817b24dbfe6cbdfbe40b52897558f3/src/include/librpma.h#L133)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

:+1: 
</blockquote></details>

A paragraph after this list saying e.g.:

All of these operations are done when the respective completion is generated.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/500)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[src/include/librpma.h, line 120 at r1](https://reviewable.io/reviews/pmem/rpma/500#-MITyLQcBweuNM7yFcbr:-MIVIn3P51OzDlhsgCuv:b-fqutzi) ([raw file](https://github.com/pmem/rpma/blob/fb0aa74a9e817b24dbfe6cbdfbe40b52897558f3/src/include/librpma.h#L120)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Sadly, I have just merged the memory management section... so my proposition is use consequently the following naming:
- buffer - for any 'memory piece'
- memory region - for a buffer which is registered for RMA / Messaging
- message - for a memory region which is specifically registered for Messaging

Does it make sense?
</blockquote></details>

Yes, it does, but I am still not sure what in your opinion should be changed here ...
___
*[src/include/librpma.h, line 133 at r1](https://reviewable.io/reviews/pmem/rpma/500#-MITzbSH1DytJlMf3ICZ:-MIVHpBaDT9pjGWRwQOH:bxjijci) ([raw file](https://github.com/pmem/rpma/blob/fb0aa74a9e817b24dbfe6cbdfbe40b52897558f3/src/include/librpma.h#L133)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

A paragraph after this list saying e.g.:

All of these operations are done when the respective completion is generated.
</blockquote></details>

Excellent! Briefly and about ;-)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/500)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[src/include/librpma.h, line 133 at r1](https://reviewable.io/reviews/pmem/rpma/500#-MITzbSH1DytJlMf3ICZ:-MIVJ7i7CraXlbRHZRR4:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/fb0aa74a9e817b24dbfe6cbdfbe40b52897558f3/src/include/librpma.h#L133)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Excellent! Briefly and about ;-)
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:goat: 

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/500#-:-MIVLuyU0B9jhc4Bioqq:bdycpsm)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[src/include/librpma.h, line 120 at r1](https://reviewable.io/reviews/pmem/rpma/500#-MITyLQcBweuNM7yFcbr:-MIVLhx2EW78vixGlyWG:b7ghsxb) ([raw file](https://github.com/pmem/rpma/blob/fb0aa74a9e817b24dbfe6cbdfbe40b52897558f3/src/include/librpma.h#L120)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Yes, it does, but I am still not sure what in your opinion should be changed here ...
</blockquote></details>

It seems... nothing. But you can review memory management in this context. ;-)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/500)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/include/librpma.h, line 157 at r3](https://reviewable.io/reviews/pmem/rpma/500#-MIVLose-mWL-IkjOBuO:-MIVLose-mWL-IkjOBuP:b-475cvt) ([raw file](https://github.com/pmem/rpma/blob/919b0e6c28b6004b2cba26e6695ae38be561c703/src/include/librpma.h#L157)):*
> ```
> buffers
> ```
bufferes (memory regions)
or
buffers as memory regions

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/500)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[src/include/librpma.h, line 120 at r1](https://reviewable.io/reviews/pmem/rpma/500#-MITyLQcBweuNM7yFcbr:-MIVM2SE6ryUD2B8_ziL:bwu7eqf) ([raw file](https://github.com/pmem/rpma/blob/fb0aa74a9e817b24dbfe6cbdfbe40b52897558f3/src/include/librpma.h#L120)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

It seems... nothing. But you can review memory management in this context. ;-)
</blockquote></details>

OK :-)

**Review by janekmi — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/500)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/500)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @grom72 and @janekmi)

___
*[src/include/librpma.h, line 157 at r3](https://reviewable.io/reviews/pmem/rpma/500#-MIVLose-mWL-IkjOBuO:-MIVWuTj2vXHPxHzqSlD:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/919b0e6c28b6004b2cba26e6695ae38be561c703/src/include/librpma.h#L157)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> buffers
> ```
bufferes (memory regions)
or
buffers as memory regions
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/500#-:-MIVZnx3121XuxzX_ZgD:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/500)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
