### PR TITLE
rpma: check if memory is allocated (rpma_flush_apm)

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/357)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/357)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @osalyk)

___
*[src/flush.c, line 80 at r1](https://reviewable.io/reviews/pmem/rpma/357#-MGO5-noBPakmJwFDul2:-MGO5-npA3zAmMEWCAKL:bk2t4lm) ([raw file](https://github.com/pmem/rpma/blob/a6484c772bda03871bcc824b8f6471742e6d4aff/src/flush.c#L80)):*
> ```C
> 	struct flush_apm *flush_apm = malloc(sizeof(struct flush_apm));
> 	if (flush_apm == NULL) {
> 		free(raw);
> ```

shall we call rpma_mr_dereg for raw at first?

**Review by grom72 — COMMENTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/357)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[tests/unit/flush/flush-new.c, line 124 at r1](https://reviewable.io/reviews/pmem/rpma/357#-MGO5SbbCdIJ3bELhR4v:-MGO5SbbCdIJ3bELhR4w:ben9udu) ([raw file](https://github.com/pmem/rpma/blob/a6484c772bda03871bcc824b8f6471742e6d4aff/tests/unit/flush/flush-new.c#L124)):*
> ```C
> 	will_return(rpma_mr_reg, MOCK_RPMA_MR_LOCAL);
> 	will_return(__wrap__test_malloc, ENOMEM);
> ```

missing rpma_mr_dereg in the sequence

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/357)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @grom72)

___
*[src/flush.c, line 80 at r1](https://reviewable.io/reviews/pmem/rpma/357#-MGO5-noBPakmJwFDul2:-MGO8q7x0qA0KFZd1avu:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a6484c772bda03871bcc824b8f6471742e6d4aff/src/flush.c#L80)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

shall we call rpma_mr_dereg for raw at first?
</blockquote></details>

Done.
___
*[tests/unit/flush/flush-new.c, line 124 at r1](https://reviewable.io/reviews/pmem/rpma/357#-MGO5SbbCdIJ3bELhR4v:-MGO8ony8-1xk4Akjsa-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a6484c772bda03871bcc824b8f6471742e6d4aff/tests/unit/flush/flush-new.c#L124)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

missing rpma_mr_dereg in the sequence
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/357#-:-MGOXm_p3kW0PXupXFK8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/357#-:-MGb6-1e0-MgUBDh8m9i:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/357#-:-MGeXh276OsXI-p9XUGE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
