### PR TITLE
tools: set the actual number of cores

### PR DESCRIPTION
**Pull request by osalyk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/940)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/940)* status: all files reviewed, 3 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/rpma_fio_bench.sh, line 383 at r1](https://reviewable.io/reviews/pmem/rpma/940#-MVv5PYa67U0--ULVNIs:-MVv5PYa67U0--ULVNIt:b-aghh72) ([raw file](https://github.com/pmem/rpma/blob/102151862d3a49eeb8d15c9065fd77c030804a8a/tools/perf/rpma_fio_bench.sh#L383)):*
> ```Shell
> 		esac
> 
> 		if [ -z "$CPU" -o "$CPU" == "0" ]; then
> ```

This change looks like a completely different topic.
A separate PR?
___
*[tools/perf/rpma_fio_bench.sh, line 387 at r1](https://reviewable.io/reviews/pmem/rpma/940#-MVv4b9hD9SGIFP4dAOJ:-MVv4b9i-tPoVMO0ZPsh:bn87dhe) ([raw file](https://github.com/pmem/rpma/blob/102151862d3a49eeb8d15c9065fd77c030804a8a/tools/perf/rpma_fio_bench.sh#L387)):*
> ```Shell
> 		else
> 			FILTER="" # no section filtering so CPU load will be included
> 			CORE_PER_SOCKET=$(lscpu | egrep 'Core' | sed 's/[^0-9]*//g')
> ```

You have to do something like this but on the server side:

```bash
ls -a /sys/devices/system/node/node$REMOTE_JOB_NUMA | grep -E 'cpu[0-9]+' | wc -(sprint goal) 
```

Please see: https://github.com/pmem/rpma/blob/master/tools/perf/rpma_fio_bench.sh#L523
Including the validation step probably.
___
*[tools/perf/rpma_fio_bench.sh, line 387 at r1](https://reviewable.io/reviews/pmem/rpma/940#-MVv57Nl3kFnCrgXuP9v:-MVv57Nl3kFnCrgXuP9w:bpow8o8) ([raw file](https://github.com/pmem/rpma/blob/102151862d3a49eeb8d15c9065fd77c030804a8a/tools/perf/rpma_fio_bench.sh#L387)):*
> ```Shell
> 		else
> 			FILTER="" # no section filtering so CPU load will be included
> 			CORE_PER_SOCKET=$(lscpu | egrep 'Core' | sed 's/[^0-9]*//g')
> ```

Additionally, it should be done around the line: https://github.com/pmem/rpma/blob/master/tools/perf/rpma_fio_bench.sh#L523
Since this value won't change in the mean time.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/940)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/rpma_fio_bench.sh, line 383 at r1](https://reviewable.io/reviews/pmem/rpma/940#-MVv5PYa67U0--ULVNIs:-MVvAmsQ8t1UGWm6GxyF:b-8sbcmx) ([raw file](https://github.com/pmem/rpma/blob/102151862d3a49eeb8d15c9065fd77c030804a8a/tools/perf/rpma_fio_bench.sh#L383)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This change looks like a completely different topic.
A separate PR?
</blockquote></details>

#942 
___
*[tools/perf/rpma_fio_bench.sh, line 387 at r1](https://reviewable.io/reviews/pmem/rpma/940#-MVv4b9hD9SGIFP4dAOJ:-MVv9368CVUafZSbGFGt:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/102151862d3a49eeb8d15c9065fd77c030804a8a/tools/perf/rpma_fio_bench.sh#L387)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You have to do something like this but on the server side:

```bash
ls -a /sys/devices/system/node/node$REMOTE_JOB_NUMA | grep -E 'cpu[0-9]+' | wc -(sprint goal) 
```

Please see: https://github.com/pmem/rpma/blob/master/tools/perf/rpma_fio_bench.sh#L523
Including the validation step probably.
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 387 at r1](https://reviewable.io/reviews/pmem/rpma/940#-MVv57Nl3kFnCrgXuP9v:-MVv9PXh2fh9lh0bOISh:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/102151862d3a49eeb8d15c9065fd77c030804a8a/tools/perf/rpma_fio_bench.sh#L387)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Additionally, it should be done around the line: https://github.com/pmem/rpma/blob/master/tools/perf/rpma_fio_bench.sh#L523
Since this value won't change in the mean time.
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/940)* status: 2 of 3 files reviewed, 3 unresolved discussions (waiting on @janekmi and @osalyk)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/940#-MVvCgMx-zGE4tSxuOeE:-MVvCgMx-zGE4tSxuOeF:be5knu0) (no related file):*
You do not need #942. Please rebase.

---

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/940)* status: all files reviewed, 2 unresolved discussions (waiting on @osalyk)

___
*[tools/perf/rpma_fio_bench.sh, line 387 at r1](https://reviewable.io/reviews/pmem/rpma/940#-MVv57Nl3kFnCrgXuP9v:-MVvDAnL9bGAGZ8w-BUt:b2k2cnj) ([raw file](https://github.com/pmem/rpma/blob/102151862d3a49eeb8d15c9065fd77c030804a8a/tools/perf/rpma_fio_bench.sh#L387)):*
<details><summary><i>Previously, osalyk (Oksana Sałyk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Nope. This is not that line.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/940)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/940#-MVvCgMx-zGE4tSxuOeE:-MVvGfBQ57J6c4PezJOd:b-896fix) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You do not need #942. Please rebase.
</blockquote></details>

Done.

---

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 3 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/940)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tools/perf/rpma_fio_bench.sh, line 538 at r3](https://reviewable.io/reviews/pmem/rpma/940#-MVvHj1M-bCvmItamBjL:-MVvHj1M-bCvmItamBjM:b-dbetpv) ([raw file](https://github.com/pmem/rpma/blob/44cdf8dfe97bda198d60d41a496325c1f4ea8525/tools/perf/rpma_fio_bench.sh#L538)):*
> ```
> export CORE_PER_SOCKET=$(sshpass -p "$REMOTE_PASS" -v ssh -o StrictHostKeyChecking=no \
> 			$REMOTE_USER@$SERVER_IP \
> 			"lscpu | egrep 'Core' | sed 's/[^0-9]*//g'")
> ```

The output should be validated like in case of `REMOTE_JOB_NUMA_CPULIST` above

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/940)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi and @osalyk)

___
*[tools/perf/rpma_fio_bench.sh, line 395 at r3](https://reviewable.io/reviews/pmem/rpma/940#-MVvJLhn7Gi27zVXN2Xv:-MVvJLhn7Gi27zVXN2Xw:b8wuieg) ([raw file](https://github.com/pmem/rpma/blob/44cdf8dfe97bda198d60d41a496325c1f4ea8525/tools/perf/rpma_fio_bench.sh#L395)):*
> ```Shell
> 			direct_write_to_pmem=${REMOTE_DIRECT_WRITE_TO_PMEM} \
> 			busy_wait_polling=${BUSY_WAIT_POLLING} cpuload=${CPU} \
> 			core_per_socket=${CORE_PER_SOCKET}"
> ```

- core**s**
- CORE**S**
?

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/940)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/rpma_fio_bench.sh, line 395 at r3](https://reviewable.io/reviews/pmem/rpma/940#-MVvJLhn7Gi27zVXN2Xv:-MVvLKrbDR3LkU9kOi5V:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/44cdf8dfe97bda198d60d41a496325c1f4ea8525/tools/perf/rpma_fio_bench.sh#L395)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

- core**s**
- CORE**S**
?
</blockquote></details>

Done.
___
*[tools/perf/rpma_fio_bench.sh, line 538 at r3](https://reviewable.io/reviews/pmem/rpma/940#-MVvHj1M-bCvmItamBjL:-MVvKkDo5spRz4bQWCCo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/44cdf8dfe97bda198d60d41a496325c1f4ea8525/tools/perf/rpma_fio_bench.sh#L538)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> export CORE_PER_SOCKET=$(sshpass -p "$REMOTE_PASS" -v ssh -o StrictHostKeyChecking=no \
> 			$REMOTE_USER@$SERVER_IP \
> 			"lscpu | egrep 'Core' | sed 's/[^0-9]*//g'")
> ```

The output should be validated like in case of `REMOTE_JOB_NUMA_CPULIST` above
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/940)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[tools/perf/rpma_fio_bench.sh, line 540 at r4](https://reviewable.io/reviews/pmem/rpma/940#-MVvNbiS9GRz_N69iwoX:-MVvNbiS9GRz_N69iwoY:b-4b5qof) ([raw file](https://github.com/pmem/rpma/blob/f8b48cc64eb2f214db5a75e5eea94930c37babe1/tools/perf/rpma_fio_bench.sh#L540)):*
> ```Shell
> 			"lscpu | egrep 'Core' | sed 's/[^0-9]*//g'")
> # validate the output
> [[ "$CORES_PER_SOCKET" =~ ^[,0-9\\-]+$ ]]
> ```

No:
- `,` or
- `\\-`

allowed in this case.

**Review by osalyk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/940)* status: 2 of 3 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tools/perf/rpma_fio_bench.sh, line 540 at r4](https://reviewable.io/reviews/pmem/rpma/940#-MVvNbiS9GRz_N69iwoX:-MVvOoip4Ry2a1qvAKcV:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/f8b48cc64eb2f214db5a75e5eea94930c37babe1/tools/perf/rpma_fio_bench.sh#L540)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

No:
- `,` or
- `\\-`

allowed in this case.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/940#-:-MVvRK3q-he9AcH1vELp:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/940)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/940#-:-MVv_MKz5pzNXtX0mu5S:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @osalyk)

**Pull request merged**
