### PR TITLE
tools: check if fio is present locally

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1338)

### CODE REVIEW

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1338#-:-MpAj5oR2actrtZ3qzV4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1338)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1338#-:-MpBk_5LA-1aSI6D-nnc:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1338)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 26 at r2](https://reviewable.io/reviews/pmem/rpma/1338#-MpCCV0qBRNPo9a-N6F8:-MpCCV0qBRNPo9a-N6F9:bttq86d) ([raw file](https://github.com/pmem/rpma/blob/e392c3c9f250cec4fcd524035a4de9ee5224d48b/tools/perf/lib/benchmark/runner/fio.py#L26)):*
> ```Python
>             raise ValueError(UNKNOWN_FILETYPE_MSG.format(filetype))
> 
>         fio_local_path = str(self.__config.get('FIO_PATH', "")) + "fio"
> ```

Ref: https://docs.python.org/3/library/os.path.html#os.path.join

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1338)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 26 at r2](https://reviewable.io/reviews/pmem/rpma/1338#-MpCCV0qBRNPo9a-N6F8:-MpCDu_kAWjz30PLCD3v:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/e392c3c9f250cec4fcd524035a4de9ee5224d48b/tools/perf/lib/benchmark/runner/fio.py#L26)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Ref: https://docs.python.org/3/library/os.path.html#os.path.join
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1338)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 27 at r4](https://reviewable.io/reviews/pmem/rpma/1338#-MpCUc-Y-WQViRQOvGP9:-MpCUc-Y-WQViRQOvGPA:bvcug08) ([raw file](https://github.com/pmem/rpma/blob/83ab82e8f1c9eb7cfd167b99408e174196e361a8/tools/perf/lib/benchmark/runner/fio.py#L27)):*
> ```Python
>             raise ValueError(UNKNOWN_FILETYPE_MSG.format(filetype))
> 
>         fio_local_path = join(self.__config.get('FIO_PATH', ""), "fio")
> ```

Mix and match. `'` and `"`. Please harmonize.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1338)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/benchmark/runner/fio.py, line 27 at r4](https://reviewable.io/reviews/pmem/rpma/1338#-MpCUc-Y-WQViRQOvGP9:-MpFtfJe78Emn6aTRxnI:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/83ab82e8f1c9eb7cfd167b99408e174196e361a8/tools/perf/lib/benchmark/runner/fio.py#L27)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Mix and match. `'` and `"`. Please harmonize.
</blockquote></details>

Done.

**Review by haichangsi — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1338)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1338#-:-MpGTDFO8it4Ww-8j_bs:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
