### PR TITLE
common: check if libibverbs has ODP support

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/363)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
Does it have any value except for test/development/integration purposes?
This mus be anyhow checked in runtime to use proper API after rpm installation.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/363#-:-MGbfJwG4FCWRxbKBpB8:b-b7qzxw)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
It checks required version of libibverbs in the CMake phase, as it should be.
Without it, there is a compilation error on older versions, what should not happen.
So it is a fix of required configuration.

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/363#-:-MGbmAWvCaKJ9pOgwovX:bfvq9jo)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/363#-:-MGcF_2G8JYwG-etjS18:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/363)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[CMakeLists.txt, line 112 at r1](https://reviewable.io/reviews/pmem/rpma/363#-MGghlboEyR2j0kyqXc7:-MGghlbpAQT5l7_-idIu:bqka7dr) ([raw file](https://github.com/pmem/rpma/blob/73266fda3c4e605405cbcaa199d0bf14913fc98f/CMakeLists.txt#L112)):*
> ```
> FATAL_ERROR
> ```
WARNING 
and in rpma.c:
```
rpma_utils_ibv_context_is_odp_capable(...) 
{
	if (dev == NULL || is_odp_capable == NULL)
		return RPMA_E_INVAL;

	*is_odp_capable = 0;
#ifdef ON_DEMAND_PAGING_SUPPORTED
...
#endif
return 0;
}
```

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/363#-:-MGgsG4h7lvY9KdWFi9m:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/363)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[CMakeLists.txt, line 112 at r1](https://reviewable.io/reviews/pmem/rpma/363#-MGghlboEyR2j0kyqXc7:-MGgsZVC8fs6NjyFsDB0:b-l68rse) ([raw file](https://github.com/pmem/rpma/blob/73266fda3c4e605405cbcaa199d0bf14913fc98f/CMakeLists.txt#L112)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

> ```
> FATAL_ERROR
> ```
WARNING 
and in rpma.c:
```
rpma_utils_ibv_context_is_odp_capable(...) 
{
	if (dev == NULL || is_odp_capable == NULL)
		return RPMA_E_INVAL;

	*is_odp_capable = 0;
#ifdef ON_DEMAND_PAGING_SUPPORTED
...
#endif
return 0;
}
```
</blockquote></details>

We will do that later, there is much more changes to do.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/363)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[CMakeLists.txt, line 112 at r1](https://reviewable.io/reviews/pmem/rpma/363#-MGghlboEyR2j0kyqXc7:-MGgvD1e5homWQu-aaRa:b2ni9ah) ([raw file](https://github.com/pmem/rpma/blob/73266fda3c4e605405cbcaa199d0bf14913fc98f/CMakeLists.txt#L112)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

We will do that later, there is much more changes to do.
</blockquote></details>

ok

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/363#-:-MGjoEt52Rwl3jD-iUqc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
