### PR TITLE
 common: pass conn_cfg via conn_req_new/_from_cm_event()

### PR DESCRIPTION
**Pull request by janekmi**
Requires:
- [x] #337 
- [x] #331
- [x] #338

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/339)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 9 of 39 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/339)* status: 9 of 15 files reviewed, all discussions resolved

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 16 of 39 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/339#-:-MGISs5xE4zFd9lLb2aL:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
> Reviewed 5 of 39 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/339)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tests/unit/conn_req/conn_req-from_cm_event.c, line 16 at r2](https://reviewable.io/reviews/pmem/rpma/339#-MGIVtG-4h-9SRPvFxP5:-MGIVtG-4h-9SRPvFxP6:b-khjy31) ([raw file](https://github.com/pmem/rpma/blob/ff10caf2d221b5f217bda34984aa8bb319a6ef3b/tests/unit/conn_req/conn_req-from_cm_event.c#L16)):*
> ```C
> #include "mocks-rpma-conn_cfg.h"
> 
> struct conn_cfg_get_q_size_mock_args Get_cqe = {
> ```

static
___
*[tests/unit/conn_req/conn_req-new.c, line 20 at r2](https://reviewable.io/reviews/pmem/rpma/339#-MGIVZ7wBuGdUdEYDq1i:-MGIVZ7wBuGdUdEYDq1j:b-khjy31) ([raw file](https://github.com/pmem/rpma/blob/ff10caf2d221b5f217bda34984aa8bb319a6ef3b/tests/unit/conn_req/conn_req-new.c#L20)):*
> ```C
> };
> 
> struct conn_cfg_get_q_size_mock_args Get_cqe = {
> ```

static

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/339)* status: 13 of 15 files reviewed, 2 unresolved discussions (waiting on @ldorau and @osalyk)

___
*[tests/unit/conn_req/conn_req-from_cm_event.c, line 16 at r2](https://reviewable.io/reviews/pmem/rpma/339#-MGIVtG-4h-9SRPvFxP5:-MGIWrHs3jCxz_TfkzoA:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ff10caf2d221b5f217bda34984aa8bb319a6ef3b/tests/unit/conn_req/conn_req-from_cm_event.c#L16)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

static
</blockquote></details>

Done.
___
*[tests/unit/conn_req/conn_req-new.c, line 20 at r2](https://reviewable.io/reviews/pmem/rpma/339#-MGIVZ7wBuGdUdEYDq1i:-MGIWv0y0os1R7axVtLf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ff10caf2d221b5f217bda34984aa8bb319a6ef3b/tests/unit/conn_req/conn_req-new.c#L20)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

static
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/339)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 39 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/339)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/339#-:-MGI_Nta4JgMtF411kau:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
