### PR TITLE
tools: perf: change 99.999 to 99.99 in the Perf Report

### PR DESCRIPTION
**Pull request by janekmi**
When 99.999 will be stabilized this change can be reverted.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1014)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1014)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tools/perf/create_report_figures.sh, line 301 at r1](https://reviewable.io/reviews/pmem/rpma/1014#-MYs6VK85JgAVPQqN3bD:-MYs6VK98c6faJeaHkEe:b9c6h1d) ([raw file](https://github.com/pmem/rpma/blob/3139432a0b3ac8f25a18d3c6b81722092bdef434/tools/perf/create_report_figures.sh#L301)):*
> ```
>  'Latency (99.9% and 99.999% percentiles)')
> ```

Please add an XXX comment here
___
*[tools/perf/csv_compare.py, line 60 at r1](https://reviewable.io/reviews/pmem/rpma/1014#-MYs6bKcCRb9keBMXmPQ:-MYs6bKcCRb9keBMXmPR:blqr0u9) ([raw file](https://github.com/pmem/rpma/blob/3139432a0b3ac8f25a18d3c6b81722092bdef434/tools/perf/csv_compare.py#L60)):*
> ```
>  'lat_pctl_99.9', 'lat_pctl_99.999'
> ```

.

**Review by grom72 — COMMENTED** [review]
:goat: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1014#-:-MYswmcUBBmy4ibCcTmV:bdycpsm)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1014)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[tools/perf/create_report_figures.sh, line 301 at r1](https://reviewable.io/reviews/pmem/rpma/1014#-MYs6VK85JgAVPQqN3bD:-MYtf5yvBS65TKexml0d:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3139432a0b3ac8f25a18d3c6b81722092bdef434/tools/perf/create_report_figures.sh#L301)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  'Latency (99.9% and 99.999% percentiles)')
> ```

Please add an XXX comment here
</blockquote></details>

Done.
___
*[tools/perf/csv_compare.py, line 60 at r1](https://reviewable.io/reviews/pmem/rpma/1014#-MYs6bKcCRb9keBMXmPQ:-MYtf6PJ-ikz8gHpYCPx:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/3139432a0b3ac8f25a18d3c6b81722092bdef434/tools/perf/csv_compare.py#L60)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
>  'lat_pctl_99.9', 'lat_pctl_99.999'
> ```

.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1014)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1014#-:-MYtfjfvCJ-zqrZK-eXV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
