### PR TITLE
rpma: rpma_conn_cfg_set_... test modification and add suppresions

### PR DESCRIPTION
**Pull request by haichangsi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1861)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1861)* status: 0 of 6 files reviewed, all discussions resolved (waiting on @ldorau)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1861)* status: 0 of 6 files reviewed, 3 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[`tests/drd.supp` line 9 at r1](https://reviewable.io/reviews/pmem/rpma/1861#-N5EAJJe0kaQoDOGWvNH:-N5EAJJe0kaQoDOGWvNI:b7ouiz) ([raw file](https://github.com/pmem/rpma/blob/ce909bb4ea793d58879d2bd0ae739ea5b131428d/tests/drd.supp#L9)):*
> ```
> 
> #
> # All suppressions should follow the following format:
> ```

@haichangsi please use the new format



_Code quote:_
```
#
# All suppressions should follow the following format:
#
```
___
*[`tests/drd.supp` line 438 at r1](https://reviewable.io/reviews/pmem/rpma/1861#-N5EJ4f40Qp_pXr9V_Uw:-N5EJ4f40Qp_pXr9V_Ux:b-7uoi3l) ([raw file](https://github.com/pmem/rpma/blob/ce909bb4ea793d58879d2bd0ae739ea5b131428d/tests/drd.supp#L438)):*
> ```
>    obj:/usr/libexec/valgrind/vgpreload_drd-amd64-linux.so
>    fun:start_thread
>    fun:clone
> ```

Suppressions should look like that:

```
{
   rpma_conn_cfg_set_rq_size - conflicting store of size 4 (multithreaded-conn_cfg-set_rq_size_0_drd)
   drd:ConflictingAccess
   fun:rpma_conn_cfg_set_rq_size
   ...
}
```

This:
```
   fun:thread
   fun:mtt_thread_main
   obj:/usr/libexec/valgrind/vgpreload_drd-amd64-linux.so
   fun:start_thread
   fun:clone
```
should be replaced with `...` in all suppressions.



_Code quote:_
```
{
   rpma_conn_cfg_set_rq_size - conflicting store of size 4 (multithreaded-conn_cfg-set_rq_size_0_drd)
   drd:ConflictingAccess
   fun:rpma_conn_cfg_set_rq_size
   fun:thread
   fun:mtt_thread_main
   obj:/usr/libexec/valgrind/vgpreload_drd-amd64-linux.so
   fun:start_thread
   fun:clone
}
```
___
*[`tests/helgrind.supp` line 9 at r1](https://reviewable.io/reviews/pmem/rpma/1861#-N5EAUQMEe_gKfUlRUYb:-N5EAUQMEe_gKfUlRUYc:b7ouiz) ([raw file](https://github.com/pmem/rpma/blob/ce909bb4ea793d58879d2bd0ae739ea5b131428d/tests/helgrind.supp#L9)):*
> ```
> 
> #
> # All suppressions should follow the following format:
> ```

@haichangsi please use the new format



_Code quote:_
```
#
# All suppressions should follow the following format:
#
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 4 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1861)* status: 4 of 6 files reviewed, 4 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[`tests/multithreaded/conn_cfg/rpma_conn_cfg_set_sq_size.c` line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1861#-N5EKLSB3Pr2r-MaygES:-N5EKLSC3JRItM7i5l2-:b-a6oa95) ([raw file](https://github.com/pmem/rpma/blob/ce909bb4ea793d58879d2bd0ae739ea5b131428d/tests/multithreaded/conn_cfg/rpma_conn_cfg_set_sq_size.c#L39)):*
> ```C
> 
> 	if (sq_size != RPMA_CONN_CFG_COMMON_Q_SIZE_EXP)
> 		MTT_ERR_MSG(tr, "Invalid sq_size: %d instead of %d", -1, sq_size, id);
> ```

Why have you replaced `MTT_ERR()` with `MTT_ERR_MSG()` here ?



_Code quote:_
```C
MTT_ERR_MSG
```

**Review by ldorau — COMMENTED** [review]
> Reviewed 2 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1861)* status: all files reviewed, 4 unresolved discussions (waiting on @haichangsi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1861)* status: all files reviewed, 7 unresolved discussions (waiting on @haichangsi)

___
*[`tests/helgrind.supp` line 456 at r1](https://reviewable.io/reviews/pmem/rpma/1861#-N5EdiYJ3xiAyT9LCDEn:-N5EdiYJ3xiAyT9LCDEo:bgneyzq) ([raw file](https://github.com/pmem/rpma/blob/ce909bb4ea793d58879d2bd0ae739ea5b131428d/tests/helgrind.supp#L456)):*
> ```
>    fun:rpma_conn_cfg_set_rq_size
>    fun:thread
>    fun:mtt_thread_main
> ```

```
{
   rpma_conn_cfg_set_rq_size - possible data race during write of size 4 (multithreaded-conn_cfg-set_rq_size_0_helgrind)
   Helgrind:Race
   fun:rpma_conn_cfg_set_rq_size
   ...
}
```

Please add an analogous suppression for `rpma_conn_cfg_get_rq_size`.



_Code quote:_
```
{
   rpma_conn_cfg_set_rq_size - possible data race during write of size 4 (multithreaded-conn_cfg-set_rq_size_0_helgrind)
   Helgrind:Race
   fun:rpma_conn_cfg_set_rq_size
   fun:thread
   fun:mtt_thread_main
   obj:/usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so
   fun:start_thread
   fun:clone
}
```
___
*[`tests/helgrind.supp` line 465 at r1](https://reviewable.io/reviews/pmem/rpma/1861#-N5EeGwF3M5E3xcUa1Oo:-N5EeGwF3M5E3xcUa1Op:bpwces0) ([raw file](https://github.com/pmem/rpma/blob/ce909bb4ea793d58879d2bd0ae739ea5b131428d/tests/helgrind.supp#L465)):*
> ```
>    rpma_conn_cfg_set_sq_size - possible data race during write of size 4 (multithreaded-conn_cfg-set_sq_size_0_helgrind)
>    Helgrind:Race
>    fun:rpma_conn_cfg_set_sq_size
> ```

Please add an analogous suppression for `rpma_conn_cfg_get_sq_size`.



_Code quote:_
```
fun:rpma_conn_cfg_set_sq_size
```
___
*[`tests/helgrind.supp` line 476 at r1](https://reviewable.io/reviews/pmem/rpma/1861#-N5EeL6K2MwlNhTrGRgl:-N5EeL6K2MwlNhTrGRgm:bzehstr) ([raw file](https://github.com/pmem/rpma/blob/ce909bb4ea793d58879d2bd0ae739ea5b131428d/tests/helgrind.supp#L476)):*
> ```
>    rpma_conn_cfg_set_timeout - possible data race during write of size 4 (multithreaded-conn_cfg-set_timeout_0_helgrind)
>    Helgrind:Race
>    fun:rpma_conn_cfg_set_timeout
> ```

Please add an analogous suppression for `rpma_conn_cfg_get_timeout`.



_Code quote:_
```
fun:rpma_conn_cfg_set_timeout
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1861)* status: all files reviewed, 7 unresolved discussions (waiting on @ldorau)

___
*[`tests/drd.supp` line 9 at r1](https://reviewable.io/reviews/pmem/rpma/1861#-N5EAJJe0kaQoDOGWvNH:-N5EewfHC4hTgbfTBT-p:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ce909bb4ea793d58879d2bd0ae739ea5b131428d/tests/drd.supp#L9)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@haichangsi please use the new format
</blockquote></details>

Done.
___
*[`tests/drd.supp` line 438 at r1](https://reviewable.io/reviews/pmem/rpma/1861#-N5EJ4f40Qp_pXr9V_Uw:-N5Eew4uEdW3YyZWV7-V:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ce909bb4ea793d58879d2bd0ae739ea5b131428d/tests/drd.supp#L438)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Suppressions should look like that:

```
{
   rpma_conn_cfg_set_rq_size - conflicting store of size 4 (multithreaded-conn_cfg-set_rq_size_0_drd)
   drd:ConflictingAccess
   fun:rpma_conn_cfg_set_rq_size
   ...
}
```

This:
```
   fun:thread
   fun:mtt_thread_main
   obj:/usr/libexec/valgrind/vgpreload_drd-amd64-linux.so
   fun:start_thread
   fun:clone
```
should be replaced with `...` in all suppressions.

</blockquote></details>

Done.
___
*[`tests/helgrind.supp` line 9 at r1](https://reviewable.io/reviews/pmem/rpma/1861#-N5EAUQMEe_gKfUlRUYb:-N5EevXG7gbvnoaSXukL:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ce909bb4ea793d58879d2bd0ae739ea5b131428d/tests/helgrind.supp#L9)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

@haichangsi please use the new format
</blockquote></details>

Done.
___
*[`tests/helgrind.supp` line 456 at r1](https://reviewable.io/reviews/pmem/rpma/1861#-N5EdiYJ3xiAyT9LCDEn:-N5Ef47H47OlTfzMaKns:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ce909bb4ea793d58879d2bd0ae739ea5b131428d/tests/helgrind.supp#L456)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

```
{
   rpma_conn_cfg_set_rq_size - possible data race during write of size 4 (multithreaded-conn_cfg-set_rq_size_0_helgrind)
   Helgrind:Race
   fun:rpma_conn_cfg_set_rq_size
   ...
}
```

Please add an analogous suppression for `rpma_conn_cfg_get_rq_size`.

</blockquote></details>

Done.
___
*[`tests/helgrind.supp` line 465 at r1](https://reviewable.io/reviews/pmem/rpma/1861#-N5EeGwF3M5E3xcUa1Oo:-N5Ef5Ec16CgSVohl_GH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ce909bb4ea793d58879d2bd0ae739ea5b131428d/tests/helgrind.supp#L465)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please add an analogous suppression for `rpma_conn_cfg_get_sq_size`.
</blockquote></details>

Done.
___
*[`tests/helgrind.supp` line 476 at r1](https://reviewable.io/reviews/pmem/rpma/1861#-N5EeL6K2MwlNhTrGRgl:-N5Ef6-s9fYzhffU20YX:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ce909bb4ea793d58879d2bd0ae739ea5b131428d/tests/helgrind.supp#L476)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please add an analogous suppression for `rpma_conn_cfg_get_timeout`.
</blockquote></details>

Done.
___
*[`tests/multithreaded/conn_cfg/rpma_conn_cfg_set_sq_size.c` line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1861#-N5EKLSB3Pr2r-MaygES:-N5EfKlf05V72PuqizO_:b-ezsj6l) ([raw file](https://github.com/pmem/rpma/blob/ce909bb4ea793d58879d2bd0ae739ea5b131428d/tests/multithreaded/conn_cfg/rpma_conn_cfg_set_sq_size.c#L39)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Why have you replaced `MTT_ERR()` with `MTT_ERR_MSG()` here ?
</blockquote></details>

I followed Tomek's PR changes. Should I leave it the way it was before?

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1861)* status: all files reviewed, 6 unresolved discussions (waiting on @haichangsi and @ldorau)

___
*[`tests/drd.supp` line 9 at r1](https://reviewable.io/reviews/pmem/rpma/1861#-N5EAJJe0kaQoDOGWvNH:-N5EpHExAWjZP6VPkkn0:bp2m2x3) ([raw file](https://github.com/pmem/rpma/blob/ce909bb4ea793d58879d2bd0ae739ea5b131428d/tests/drd.supp#L9)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet, see https://github.com/pmem/rpma/pull/1862
___
*[`tests/helgrind.supp` line 9 at r1](https://reviewable.io/reviews/pmem/rpma/1861#-N5EAUQMEe_gKfUlRUYb:-N5EpOvL929yrHi6d7S_:bp2m2x3) ([raw file](https://github.com/pmem/rpma/blob/ce909bb4ea793d58879d2bd0ae739ea5b131428d/tests/helgrind.supp#L9)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet, see https://github.com/pmem/rpma/pull/1862
___
*[`tests/helgrind.supp` line 456 at r1](https://reviewable.io/reviews/pmem/rpma/1861#-N5EdiYJ3xiAyT9LCDEn:-N5EpdMxEA946uQ2TDad:b-viho6m) ([raw file](https://github.com/pmem/rpma/blob/ce909bb4ea793d58879d2bd0ae739ea5b131428d/tests/helgrind.supp#L456)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Where is an analogous suppression for `rpma_conn_cfg_get_rq_size`?
___
*[`tests/helgrind.supp` line 465 at r1](https://reviewable.io/reviews/pmem/rpma/1861#-N5EeGwF3M5E3xcUa1Oo:-N5EpiPtAiplkuZLWjk2:bgnesn0) ([raw file](https://github.com/pmem/rpma/blob/ce909bb4ea793d58879d2bd0ae739ea5b131428d/tests/helgrind.supp#L465)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Where is it?
___
*[`tests/helgrind.supp` line 476 at r1](https://reviewable.io/reviews/pmem/rpma/1861#-N5EeL6K2MwlNhTrGRgl:-N5EpmS_DzFG8EFpsBcH:bgnesn0) ([raw file](https://github.com/pmem/rpma/blob/ce909bb4ea793d58879d2bd0ae739ea5b131428d/tests/helgrind.supp#L476)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Where is it?

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1861)* status: all files reviewed, 6 unresolved discussions (waiting on @haichangsi)

___
*[`tests/multithreaded/conn_cfg/rpma_conn_cfg_set_sq_size.c` line 39 at r1](https://reviewable.io/reviews/pmem/rpma/1861#-N5EKLSB3Pr2r-MaygES:-N5EvHX_1cewq25DP4mz:b740f1c) ([raw file](https://github.com/pmem/rpma/blob/ce909bb4ea793d58879d2bd0ae739ea5b131428d/tests/multithreaded/conn_cfg/rpma_conn_cfg_set_sq_size.c#L39)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

OK, but you should keep checking if all is correct when you copy the code ;-),
because you have copied a bug too :-)

The correct expected value is `RPMA_CONN_CFG_COMMON_Q_SIZE_EXP`, not `id`.
</blockquote></details>

please review: https://github.com/pmem/rpma/pull/1863

**Review by grom72 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1861)* status: all files reviewed, 9 unresolved discussions (waiting on @haichangsi)

___
*[`tests/helgrind.supp` line 454 at r1](https://reviewable.io/reviews/pmem/rpma/1861#-N5EwwsCBLhCEYufXTK_:-N5EwwsCBLhCEYufXTKa:undefined) ([raw file](https://github.com/pmem/rpma/blob/ce909bb4ea793d58879d2bd0ae739ea5b131428d/tests/helgrind.supp#L454)):*
> ```
>    rpma_conn_cfg_set_rq_size - possible data race during write of size 4 (multithreaded-conn_cfg-set_rq_size_0_helgrind)
>    Helgrind:Race
>    fun:rpma_conn_cfg_set_rq_size
> ```





_Suggestion:_
```
   fun:rpma_conn_cfg_set_rq_size
   ...
```
___
*[`tests/helgrind.supp` line 470 at r1](https://reviewable.io/reviews/pmem/rpma/1861#-N5Ewkbp57O8YRJ_IL4T:-N5Ewkbp57O8YRJ_IL4U:undefined) ([raw file](https://github.com/pmem/rpma/blob/ce909bb4ea793d58879d2bd0ae739ea5b131428d/tests/helgrind.supp#L470)):*
> ```
>    obj:/usr/libexec/valgrind/vgpreload_helgrind-amd64-linux.so
>    fun:start_thread
>    fun:clone
> ```





_Suggestion:_
```
{
   rpma_conn_cfg_set_sq_size - possible data race during write of size 4 (multithreaded-conn_cfg-set_sq_size_0_helgrind)
   Helgrind:Race
   fun:rpma_conn_cfg_set_sq_size
   ...
}
```
___
*[`tests/helgrind.supp` line 476 at r1](https://reviewable.io/reviews/pmem/rpma/1861#-N5EwsVq156fcpQTNyF9:-N5EwsVq156fcpQTNyFA:undefined) ([raw file](https://github.com/pmem/rpma/blob/ce909bb4ea793d58879d2bd0ae739ea5b131428d/tests/helgrind.supp#L476)):*
> ```
>    rpma_conn_cfg_set_timeout - possible data race during write of size 4 (multithreaded-conn_cfg-set_timeout_0_helgrind)
>    Helgrind:Race
>    fun:rpma_conn_cfg_set_timeout
> ```





_Suggestion:_
```
   fun:rpma_conn_cfg_set_timeout
   ...
```

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1861)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[`tests/drd.supp` line 9 at r1](https://reviewable.io/reviews/pmem/rpma/1861#-N5EAJJe0kaQoDOGWvNH:-N5F5E9X-7odijgD1JZN:bwbtxv3) ([raw file](https://github.com/pmem/rpma/blob/ce909bb4ea793d58879d2bd0ae739ea5b131428d/tests/drd.supp#L9)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet, see #1862
___
*[`tests/drd.supp` line 435 at r3](https://reviewable.io/reviews/pmem/rpma/1861#-N5F5OIGE8dP-lyVJWBp:-N5F5OIGE8dP-lyVJWBq:br3y1cv) ([raw file](https://github.com/pmem/rpma/blob/2707b6804376d23581d0c3de1d0d8f73db01c7e1/tests/drd.supp#L435)):*
> ```
> # Occurs in traces of:
> # - rpma_conn_cfg_set_rq_size
> # - rpma_conn_cfg_get_rq_size
> ```

IMHO this one suppression occurs only in traces of `rpma_conn_cfg_set_rq_size`



_Code quote:_
```
# Occurs in traces of:
# - rpma_conn_cfg_set_rq_size
# - rpma_conn_cfg_get_rq_size
# - rpma_conn_cfg_set_sq_size
# - rpma_conn_cfg_get_sq_size
# - rpma_conn_cfg_set_timeout
# - rpma_conn_cfg_get_timeout
{
   rpma_conn_cfg_set_rq_size - conflicting store of size 4 (multithreaded-conn_cfg-set_rq_size_0_drd)
   drd:ConflictingAccess
   fun:rpma_conn_cfg_set_rq_size
   ...
}
```
___
*[`tests/helgrind.supp` line 9 at r1](https://reviewable.io/reviews/pmem/rpma/1861#-N5EAUQMEe_gKfUlRUYb:-N5F5BKl95EWk90l9x9l:bwbtxv3) ([raw file](https://github.com/pmem/rpma/blob/ce909bb4ea793d58879d2bd0ae739ea5b131428d/tests/helgrind.supp#L9)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet, see #1862
___
*[`tests/helgrind.supp` line 454 at r3](https://reviewable.io/reviews/pmem/rpma/1861#-N5F5fW0BsAVs-AsU4lR:-N5F5fW0BsAVs-AsU4lS:br3y1cv) ([raw file](https://github.com/pmem/rpma/blob/2707b6804376d23581d0c3de1d0d8f73db01c7e1/tests/helgrind.supp#L454)):*
> ```
> # librdmacm: 1.39.0.1
> #
> # Occurs in traces of:
> ```

IMHO this one suppression occurs only in traces of `rpma_conn_cfg_set_rq_size`



_Code quote:_
```
# Occurs in traces of:
# - rpma_conn_cfg_set_rq_size
# - rpma_conn_cfg_set_sq_size
# - rpma_conn_cfg_set_timeout
{
   rpma_conn_cfg_set_rq_size - possible data race during write of size 4 (multithreaded-conn_cfg-set_rq_size_0_helgrind)
   Helgrind:Race
   fun:rpma_conn_cfg_set_rq_size
   ...
}
```

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1861)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[`tests/drd.supp` line 9 at r1](https://reviewable.io/reviews/pmem/rpma/1861#-N5EAJJe0kaQoDOGWvNH:-N5FHhP87S_JPTZB4aqY:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ce909bb4ea793d58879d2bd0ae739ea5b131428d/tests/drd.supp#L9)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not yet, see #1862
</blockquote></details>

Done.
___
*[`tests/drd.supp` line 435 at r3](https://reviewable.io/reviews/pmem/rpma/1861#-N5F5OIGE8dP-lyVJWBp:-N5FHeug5ypNg05NpbTC:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2707b6804376d23581d0c3de1d0d8f73db01c7e1/tests/drd.supp#L435)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

IMHO this one suppression occurs only in traces of `rpma_conn_cfg_set_rq_size`
</blockquote></details>

Done.
___
*[`tests/helgrind.supp` line 9 at r1](https://reviewable.io/reviews/pmem/rpma/1861#-N5EAUQMEe_gKfUlRUYb:-N5FHfSr3yPdK-G2PFUF:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ce909bb4ea793d58879d2bd0ae739ea5b131428d/tests/helgrind.supp#L9)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not yet, see #1862
</blockquote></details>

Done.
___
*[`tests/helgrind.supp` line 454 at r3](https://reviewable.io/reviews/pmem/rpma/1861#-N5F5fW0BsAVs-AsU4lR:-N5FHfuC9uqaIFyf1l7a:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/2707b6804376d23581d0c3de1d0d8f73db01c7e1/tests/helgrind.supp#L454)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

IMHO this one suppression occurs only in traces of `rpma_conn_cfg_set_rq_size`
</blockquote></details>

Done.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1861)* status: all files reviewed, 6 unresolved discussions (waiting on @grom72 and @haichangsi)

___
*[`tests/drd.supp` line 9 at r1](https://reviewable.io/reviews/pmem/rpma/1861#-N5EAJJe0kaQoDOGWvNH:-N5Fc_hsD9CptZpqvUeK:b-7lt9gn) ([raw file](https://github.com/pmem/rpma/blob/ce909bb4ea793d58879d2bd0ae739ea5b131428d/tests/drd.supp#L9)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet, see the example below.
___
*[`tests/drd.supp` line 392 at r4](https://reviewable.io/reviews/pmem/rpma/1861#-N5Fc7Mk3QrgXNBSJ3gB:-N5Fc7Mk3QrgXNBSJ3gC:b-gsk82g) ([raw file](https://github.com/pmem/rpma/blob/ffec3a80d001bdb8d4c25e6d40eeb172872cff22/tests/drd.supp#L392)):*
> ```
> }
> 
> # OS: ubuntu-2204:2022.04.1 of CircleCI
> ```

All suppressions should follow the common format, for example:
```
#
# Assessment: this suppression indicates a lack of MT safety.
#
# OS: ubuntu-2204:2022.04.1 of CircleCI
# libibverbs: 1.39.0.1
# librdmacm: 1.39.0.1
#
# Occurs in traces of:
# - rpma_conn_cfg_set_rq_size
#
{
```



_Code quote:_
```
# OS: ubuntu-2204:2022.04.1 of CircleCI
# libibverbs: 1.39.0.1
# librdmacm: 1.39.0.1
#
# Occurs in traces of:
# - rpma_conn_cfg_set_rq_size





{
```
___
*[`tests/helgrind.supp` line 9 at r1](https://reviewable.io/reviews/pmem/rpma/1861#-N5EAUQMEe_gKfUlRUYb:-N5FcXjV2SR-f9nyyhpj:b-84g7wz) ([raw file](https://github.com/pmem/rpma/blob/ce909bb4ea793d58879d2bd0ae739ea5b131428d/tests/helgrind.supp#L9)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Not yet, see the example above.

**Review by grom72 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1861)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

**Review by grom72 — APPROVED** [review]
> Reviewed 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1861)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

**Review by grom72 — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1861)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

**Review by grom72 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1861)* status: all files reviewed, 3 unresolved discussions (waiting on @haichangsi)

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1861)* status: all files reviewed, 3 unresolved discussions (waiting on @ldorau)

___
*[`tests/drd.supp` line 9 at r1](https://reviewable.io/reviews/pmem/rpma/1861#-N5EAJJe0kaQoDOGWvNH:-N5_lBE9E8snaPWa3a0A:bnu4lzt) ([raw file](https://github.com/pmem/rpma/blob/ce909bb4ea793d58879d2bd0ae739ea5b131428d/tests/drd.supp#L9)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not yet, see the example below.
</blockquote></details>

If this is conditionally thread-safe should I say that indicates lack of MT safe or modify it to "can indicate lack of MT safe". I did it as you did in #1862.
___
*[`tests/drd.supp` line 392 at r4](https://reviewable.io/reviews/pmem/rpma/1861#-N5Fc7Mk3QrgXNBSJ3gB:-N5_lRuj4ONN0DswwuvY:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/ffec3a80d001bdb8d4c25e6d40eeb172872cff22/tests/drd.supp#L392)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

All suppressions should follow the common format, for example:
```
#
# Assessment: this suppression indicates a lack of MT safety.
#
# OS: ubuntu-2204:2022.04.1 of CircleCI
# libibverbs: 1.39.0.1
# librdmacm: 1.39.0.1
#
# Occurs in traces of:
# - rpma_conn_cfg_set_rq_size
#
{
```
</blockquote></details>

Done.
___
*[`tests/helgrind.supp` line 9 at r1](https://reviewable.io/reviews/pmem/rpma/1861#-N5EAUQMEe_gKfUlRUYb:-N5_lT-s47rrb-Sz4Aeu:b3kqx) ([raw file](https://github.com/pmem/rpma/blob/ce909bb4ea793d58879d2bd0ae739ea5b131428d/tests/helgrind.supp#L9)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Not yet, see the example above.
</blockquote></details>

.

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1861)* status: all files reviewed, 2 unresolved discussions (waiting on @haichangsi)

___
*[`tests/drd.supp` line 9 at r1](https://reviewable.io/reviews/pmem/rpma/1861#-N5EAJJe0kaQoDOGWvNH:-N5cn7y_8JEDIgqKN2Nc:b-pzy0mn) ([raw file](https://github.com/pmem/rpma/blob/ce909bb4ea793d58879d2bd0ae739ea5b131428d/tests/drd.supp#L9)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

If this is conditionally thread-safe should I say that indicates lack of MT safe or modify it to "can indicate lack of MT safe". I did it as you did in #1862.
</blockquote></details>

It is OK, as it is now.
___
*[`tests/helgrind.supp` line 9 at r1](https://reviewable.io/reviews/pmem/rpma/1861#-N5EAUQMEe_gKfUlRUYb:-N5cnDVf0ux5LO3C2cDI:b-pzy0mn) ([raw file](https://github.com/pmem/rpma/blob/ce909bb4ea793d58879d2bd0ae739ea5b131428d/tests/helgrind.supp#L9)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

.
</blockquote></details>

It is OK, as it is now.

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1861)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1861#-:-N5cq3ICD5bVcOBYH2GX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — APPROVED** [review]
> Reviewed 2 of 6 files at r1, 2 of 4 files at r3, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1861)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Review by grom72 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1861#-:-N5dBLWBCXq8SyUsTjC3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haichangsi)

**Pull request merged**
