### PR TITLE
rpma: improve CONTRIBUTING.md file

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1961)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
Preview: https://github.com/ldorau/rpma/blob/rpma-improve-CONTRIBUTING.md-file/CONTRIBUTING.md

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1961#-:-N8NabCg0xsM5JfvJivB:b-vyvr0q)* status: 0 of 1 files reviewed, all discussions resolved

**Review by haichangsi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1961#-:-N8NvtEg90dGODhzvE1H:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by Patryk717 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1961#-:-N8Oe318EgSs-gL-2708:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by haichangsi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1961)* status: all files reviewed, 10 unresolved discussions (waiting on @ldorau)

___
*[`CONTRIBUTING.md` line 8 at r1](https://reviewable.io/reviews/pmem/rpma/1961#-N8TESfj25ExoLyPxVXt:-N8TESfj25ExoLyPxVXu:b2niczw) ([raw file](https://github.com/pmem/rpma/blob/0685758e498c07812cbd586a67ce320b8ed6c214/CONTRIBUTING.md#L8)):*
> ```Markdown
> with a conversation about your changes, rather than just writing a bunch
> of code and contributing it out of the blue.
> To propose new features, suggest adding features, or simply start a dialogue about librpma,
> ```

the



_Code quote:_
```Markdown
about librpma
```
___
*[`CONTRIBUTING.md` line 71 at r1](https://reviewable.io/reviews/pmem/rpma/1961#-N8TGTad9zLhfjYgGU9p:-N8TGTad9zLhfjYgGU9q:b-qpmvxh) ([raw file](https://github.com/pmem/rpma/blob/0685758e498c07812cbd586a67ce320b8ed6c214/CONTRIBUTING.md#L71)):*
> ```Markdown
> Here is the list of the most important rules of code formatting:
> 
> - The limit of line length is 100 characters.
> ```

for a 



_Code quote:_
```Markdown
of
```
___
*[`CONTRIBUTING.md` line 77 at r1](https://reviewable.io/reviews/pmem/rpma/1961#-N8TFUxj4Ib0A6MtIDvX:-N8TFUxk8eykXUwDHplY:b-7ud4wy) ([raw file](https://github.com/pmem/rpma/blob/0685758e498c07812cbd586a67ce320b8ed6c214/CONTRIBUTING.md#L77)):*
> ```Markdown
> - Do not use C++ comments `//` (except for the License).
> - Spaces around operators are mandatory.
> - No whitespace is allowed at the end of line.
> ```

a/the



_Code quote:_
```Markdown
of line
```
___
*[`CONTRIBUTING.md` line 78 at r1](https://reviewable.io/reviews/pmem/rpma/1961#-N8TGogM5qpohhHQt3EL:-N8TGogM5qpohhHQt3EM:b2niczw) ([raw file](https://github.com/pmem/rpma/blob/0685758e498c07812cbd586a67ce320b8ed6c214/CONTRIBUTING.md#L78)):*
> ```Markdown
> - Spaces around operators are mandatory.
> - No whitespace is allowed at the end of line.
> - For multi-line macros, do not put whitespace before `\` character.
> ```

the



_Code quote:_
```Markdown
before `\` character
```
___
*[`CONTRIBUTING.md` line 80 at r1](https://reviewable.io/reviews/pmem/rpma/1961#-N8TH3lK592B9RdSXc1J:-N8TH3lK592B9RdSXc1K:b2niczw) ([raw file](https://github.com/pmem/rpma/blob/0685758e498c07812cbd586a67ce320b8ed6c214/CONTRIBUTING.md#L80)):*
> ```Markdown
> - For multi-line macros, do not put whitespace before `\` character.
> - Precede definition of each function with a brief, non-trivial description. (Usually a single line is enough.)
> - Use `XXX` tag to indicate a hack, problematic code, or something to be done.
> ```

the



_Code quote:_
```Markdown
Use `XXX
```
___
*[`CONTRIBUTING.md` line 81 at r1](https://reviewable.io/reviews/pmem/rpma/1961#-N8THAU681Todhsk09xN:-N8THAU681Todhsk09xO:b2niczw) ([raw file](https://github.com/pmem/rpma/blob/0685758e498c07812cbd586a67ce320b8ed6c214/CONTRIBUTING.md#L81)):*
> ```Markdown
> - Precede definition of each function with a brief, non-trivial description. (Usually a single line is enough.)
> - Use `XXX` tag to indicate a hack, problematic code, or something to be done.
> - For pointer variables, place the `*` close to the variable name not pointer type.
> ```

the



_Code quote:_
```Markdown
not pointer
```
___
*[`CONTRIBUTING.md` line 135 at r1](https://reviewable.io/reviews/pmem/rpma/1961#-N8THkcIDqzvz6Z1TFm8:-N8THkcIDqzvz6Z1TFm9:b2niczw) ([raw file](https://github.com/pmem/rpma/blob/0685758e498c07812cbd586a67ce320b8ed6c214/CONTRIBUTING.md#L135)):*
> ```Markdown
> ## Code coverage
> 
> One of the basic principles of delivering a new functionality to a library is to deliver it simultaneously with the unit tests to ensure that the new features behave correctly.
> ```

the



_Code quote:_
```Markdown
to a library
```
___
*[`CONTRIBUTING.md` line 136 at r1](https://reviewable.io/reviews/pmem/rpma/1961#-N8THwHw36sq3Smy2q6J:-N8THwHw36sq3Smy2q6K:b2niczw) ([raw file](https://github.com/pmem/rpma/blob/0685758e498c07812cbd586a67ce320b8ed6c214/CONTRIBUTING.md#L136)):*
> ```Markdown
> 
> One of the basic principles of delivering a new functionality to a library is to deliver it simultaneously with the unit tests to ensure that the new features behave correctly.
> You have to expect that code that degrades the test coverage will not pass the review process unless it is explicitly marked as a draft. Keep in mind that only PRs with 100% coverage can be merged. Please check [DEVELOPMENT.md file](DEVELOPMENT.md) to see how to run all unit tests.
> ```

the



_Code quote:_
```Markdown
check [DEVELOPMENT.md file](DEVELOPMENT.md)
```
___
*[`CONTRIBUTING.md` line 143 at r1](https://reviewable.io/reviews/pmem/rpma/1961#-N8TI-Mq3sscK8RQJyLl:-N8TI-Mq3sscK8RQJyLm:b2niczw) ([raw file](https://github.com/pmem/rpma/blob/0685758e498c07812cbd586a67ce320b8ed6c214/CONTRIBUTING.md#L143)):*
> ```Markdown
> [GitHub Issues Database](https://github.com/pmem/rpma/issues).
> 
> When reporting a new bug, please use `New issue` button.
> ```

the



_Code quote:_
```Markdown
use `New issue` button.
```
___
*[`CONTRIBUTING.md` line 149 at r1](https://reviewable.io/reviews/pmem/rpma/1961#-N8TIYJH9s72lNrTk8gJ:-N8TIYJH9s72lNrTk8gK:b-8lb83l) ([raw file](https://github.com/pmem/rpma/blob/0685758e498c07812cbd586a67ce320b8ed6c214/CONTRIBUTING.md#L149)):*
> ```Markdown
> 
> On our issues page we also gather feature requests and questions. Templates to use
> are `Feature` and `Question`, respectively.  They should help deliver a meaningful
> ```

the or none, description is not countable



_Code quote:_
```Markdown
deliver a meaningful
```

**Review by haichangsi — COMMENTED** [review]
:lgtm_cancel: 

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1961#-:-N8TPOTBEkTATwOIWtNF:b8b79qu)* status: all files reviewed, 10 unresolved discussions (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1961)* status: all files reviewed, 10 unresolved discussions (waiting on @haichangsi)

___
*[`CONTRIBUTING.md` line 8 at r1](https://reviewable.io/reviews/pmem/rpma/1961#-N8TESfj25ExoLyPxVXt:-N8TTeNr2-hP0E1YGjzw:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0685758e498c07812cbd586a67ce320b8ed6c214/CONTRIBUTING.md#L8)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

the
</blockquote></details>

Done.
___
*[`CONTRIBUTING.md` line 71 at r1](https://reviewable.io/reviews/pmem/rpma/1961#-N8TGTad9zLhfjYgGU9p:-N8TToH1B9QUz2ixToRb:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0685758e498c07812cbd586a67ce320b8ed6c214/CONTRIBUTING.md#L71)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

for a 
</blockquote></details>

Done.



_Code quote:_
```Markdown
he limit of line length is 1
```
___
*[`CONTRIBUTING.md` line 77 at r1](https://reviewable.io/reviews/pmem/rpma/1961#-N8TFUxj4Ib0A6MtIDvX:-N8TTtV12C16Fm6CyLKp:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0685758e498c07812cbd586a67ce320b8ed6c214/CONTRIBUTING.md#L77)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

a/the
</blockquote></details>

Done.



_Code quote:_
```Markdown
is allowed at the end of line
```
___
*[`CONTRIBUTING.md` line 78 at r1](https://reviewable.io/reviews/pmem/rpma/1961#-N8TGogM5qpohhHQt3EL:-N8TTzBg3VfWnZUPFjt3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0685758e498c07812cbd586a67ce320b8ed6c214/CONTRIBUTING.md#L78)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

the
</blockquote></details>

Done.



_Code quote:_
```Markdown
ne macros, do not put whitespace before `\` charac
```
___
*[`CONTRIBUTING.md` line 80 at r1](https://reviewable.io/reviews/pmem/rpma/1961#-N8TH3lK592B9RdSXc1J:-N8TU2EF-1NVa-EYtK_7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0685758e498c07812cbd586a67ce320b8ed6c214/CONTRIBUTING.md#L80)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

the
</blockquote></details>

Done.



_Code quote:_
```Markdown
se `XXX` tag t
```
___
*[`CONTRIBUTING.md` line 81 at r1](https://reviewable.io/reviews/pmem/rpma/1961#-N8THAU681Todhsk09xN:-N8TUAqF7TXo9qXNtf8a:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0685758e498c07812cbd586a67ce320b8ed6c214/CONTRIBUTING.md#L81)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

the
</blockquote></details>

Done.



_Code quote:_
```Markdown
not pointer typ
```
___
*[`CONTRIBUTING.md` line 135 at r1](https://reviewable.io/reviews/pmem/rpma/1961#-N8THkcIDqzvz6Z1TFm8:-N8TUG3L0_kuFOO1AhIZ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0685758e498c07812cbd586a67ce320b8ed6c214/CONTRIBUTING.md#L135)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

the
</blockquote></details>

Done.
___
*[`CONTRIBUTING.md` line 136 at r1](https://reviewable.io/reviews/pmem/rpma/1961#-N8THwHw36sq3Smy2q6J:-N8TURrOAZ53tO5vbrvN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0685758e498c07812cbd586a67ce320b8ed6c214/CONTRIBUTING.md#L136)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

the
</blockquote></details>

Done.
___
*[`CONTRIBUTING.md` line 143 at r1](https://reviewable.io/reviews/pmem/rpma/1961#-N8TI-Mq3sscK8RQJyLl:-N8TUWclEqsN9YeTXHCf:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0685758e498c07812cbd586a67ce320b8ed6c214/CONTRIBUTING.md#L143)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

the
</blockquote></details>

Done.
___
*[`CONTRIBUTING.md` line 149 at r1](https://reviewable.io/reviews/pmem/rpma/1961#-N8TIYJH9s72lNrTk8gJ:-N8TUaJv6mEzzdGY-CQg:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0685758e498c07812cbd586a67ce320b8ed6c214/CONTRIBUTING.md#L149)):*
<details><summary><i>Previously, haichangsi (Haichang) wrote…</i></summary><blockquote>

the or none, description is not countable
</blockquote></details>

Done.

**Review by haichangsi — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1961#-:-N8TWQXT2Je43QT31tff:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
