### PR TITLE
test: add rpma_peer_new multithreaded test

### PR DESCRIPTION
**Pull request by ewanglong**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1008)

### CODE REVIEW

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1008)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @ewanglong)

___
*[tests/multithreaded/peer/rpma_peer_new.c, line 110 at r1](https://reviewable.io/reviews/pmem/rpma/1008#-MYcnrtZ8EyWPbUvlIxC:-MYcnrtZ8EyWPbUvlIxD:b9wc8il) ([raw file](https://github.com/pmem/rpma/blob/bdd5301fa70e605560c001344053369543db629d/tests/multithreaded/peer/rpma_peer_new.c#L110)):*
<details><summary><i alt="summary">Quoted 17 lines of code…</i></summary>

> ```
> 	for (i = 0; i < thread_num; i++) {
> 		if ((ret = pthread_create(&p_threads[i], NULL, thread_main,
> 				&threads_args[i])) != 0) {
> 			fprintf(stderr, "Cannot start the thread #%d: %s\n",
> 				i, strerror(ret));
> 			/*
> 			 * Set thread_num to the number of already created
> 			 * threads to join them below.
> 			 */
> 			thread_num = i;
> 			/* return -1 on error */
> 			ret = -1;
> 			break;
> 		}
> 	}
> 	for (i = thread_num - 1; i >= 0; i--)
> 		pthread_join(p_threads[i], NULL);
> ```
</details>


All multi-threaded tests should use the new MT framework like in https://github.com/pmem/rpma/blob/master/tests/multithreaded/utils/rpma_utils_get_ibv_context.c

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1008)* status: 1 of 6 files reviewed, 1 unresolved discussion (waiting on @ewanglong)

___
*[tests/multithreaded/peer/rpma_peer_new.c, line 110 at r1](https://reviewable.io/reviews/pmem/rpma/1008#-MYcnrtZ8EyWPbUvlIxC:-MYcsMK40QLt9fCWyxda:b-m5fmut) ([raw file](https://github.com/pmem/rpma/blob/bdd5301fa70e605560c001344053369543db629d/tests/multithreaded/peer/rpma_peer_new.c#L110)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 	for (i = 0; i < thread_num; i++) {
> 		if ((ret = pthread_create(&p_threads[i], NULL, thread_main,
> 				&threads_args[i])) != 0) {
> 			fprintf(stderr, "Cannot start the thread #%d: %s\n",
> 				i, strerror(ret));
> 			/*
> 			 * Set thread_num to the number of already created
> 			 * threads to join them below.
> 			 */
> 			thread_num = i;
> 			/* return -1 on error */
> 			ret = -1;
> 			break;
> 		}
> 	}
> 	for (i = thread_num - 1; i >= 0; i--)
> 		pthread_join(p_threads[i], NULL);
> ```

All multi-threaded tests should use the new MT framework like in https://github.com/pmem/rpma/blob/master/tests/multithreaded/utils/rpma_utils_get_ibv_context.c

</blockquote></details>

See also: https://github.com/pmem/rpma/pull/1000

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1008)* status: 1 of 6 files reviewed, 2 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/multithreaded/peer/rpma_peer_new.c, line 110 at r1](https://reviewable.io/reviews/pmem/rpma/1008#-MYcnrtZ8EyWPbUvlIxC:-MYhfB50-8iRSU6ZodtE:bgmje75) ([raw file](https://github.com/pmem/rpma/blob/bdd5301fa70e605560c001344053369543db629d/tests/multithreaded/peer/rpma_peer_new.c#L110)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Sorry. We got out of sync. A silver lining is that you should find rewriting this test easy.
</blockquote></details>

See also: https://github.com/pmem/rpma/pull/1012

(#1000 has been already merged)

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1008)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tests/multithreaded/common/server.c, line 1 at r1](https://reviewable.io/reviews/pmem/rpma/1008#-MYecsOuDJR88Nt1ROTT:-MYshz2SEY1ti68AqmVN:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bdd5301fa70e605560c001344053369543db629d/tests/multithreaded/common/server.c#L1)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You do not need a server (or establishing any connection TBH) to test `rpma_peer_new()`.
</blockquote></details>

Done.

**Review by ldorau — COMMENTED** [review]
> Reviewed 5 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1008)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 6 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1008)* status: all files reviewed, 8 unresolved discussions (waiting on @ewanglong and @janekmi)

___
*[tests/multithreaded/peer/rpma_peer_new.c, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/1008#-MYsxgmx4a3tvSBBxJax:-MYsxgmx4a3tvSBBxJay:b-uf0b2q) ([raw file](https://github.com/pmem/rpma/blob/111af20bc5a33a18e7dfd70cd9437548037e2697/tests/multithreaded/peer/rpma_peer_new.c#L15)):*
> ```
> int is_odp_supported_exp;
> ```

IMHO It is not needed.
___
*[tests/multithreaded/peer/rpma_peer_new.c, line 33 at r2](https://reviewable.io/reviews/pmem/rpma/1008#-MYt0yYZC-i2HDAaoDQh:-MYt0yYZC-i2HDAaoDQi:b-jwtgfn) ([raw file](https://github.com/pmem/rpma/blob/111af20bc5a33a18e7dfd70cd9437548037e2697/tests/multithreaded/peer/rpma_peer_new.c#L33)):*
> ```
> struct state *st = (struct state *)calloc(1, sizeof(struct state));
> ```

`error: implicit declaration of function ‘calloc’ [-Werror=implicit-function-declaration]`
___
*[tests/multithreaded/peer/rpma_peer_new.c, line 52 at r2](https://reviewable.io/reviews/pmem/rpma/1008#-MYsx_H2BIyGv18baklJ:-MYsx_H2BIyGv18baklK:bkb6r3y) ([raw file](https://github.com/pmem/rpma/blob/111af20bc5a33a18e7dfd70cd9437548037e2697/tests/multithreaded/peer/rpma_peer_new.c#L52)):*
<details><summary><i alt="summary">Quoted 7 lines of code…</i></summary>

> ```
> 	/* check if the device context's capability supports On-Demand Paging */
> 	ret = rpma_utils_ibv_context_is_odp_capable(pr->dev,
> 				&pr->is_odp_supported_exp);
> 	if (ret) {
> 		MTT_RPMA_ERR(tr, "rpma_utils_ibv_context_is_odp_capable", ret);
> 		return;
> 	}
> ```
</details>


Why do you call `rpma_utils_ibv_context_is_odp_capable()`? IMHO it is not needed.
___
*[tests/multithreaded/peer/rpma_peer_new.c, line 97 at r2](https://reviewable.io/reviews/pmem/rpma/1008#-MYt14Z095jBTQGSPGWW:-MYt14Z095jBTQGSPGWX:bil2d2s) ([raw file](https://github.com/pmem/rpma/blob/111af20bc5a33a18e7dfd70cd9437548037e2697/tests/multithreaded/peer/rpma_peer_new.c#L97)):*
> ```C
> 		MTT_RPMA_ERR(tr, "rpma_peer_delete", ret);
> 
> 	free(st);
> ```

`error: implicit declaration of function ‘free’ [-Werror=implicit-function-declaration]`
___
*[tests/multithreaded/peer/rpma_peer_new.c, line 104 at r2](https://reviewable.io/reviews/pmem/rpma/1008#-MYsygl32XeriC3XNZE3:-MYsygl32XeriC3XNZE4:b-2l02my) ([raw file](https://github.com/pmem/rpma/blob/111af20bc5a33a18e7dfd70cd9437548037e2697/tests/multithreaded/peer/rpma_peer_new.c#L104)):*
> ```
> int ret;
> ```

`error: unused variable ‘ret’ [-Werror=unused-variable]`
___
*[tests/multithreaded/peer/rpma_peer_new.c, line 109 at r2](https://reviewable.io/reviews/pmem/rpma/1008#-MYt1ZjeDQ6ixxz_eLvE:-MYt1ZjeDQ6ixxz_eLvF:b-ok746p) ([raw file](https://github.com/pmem/rpma/blob/111af20bc5a33a18e7dfd70cd9437548037e2697/tests/multithreaded/peer/rpma_peer_new.c#L109)):*
> ```
> {args.addr};
> ```

`{args.addr, NULL, 0};` or  `{args.addr, NULL};` after having removed ` is_odp_supported_exp`

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1008)* status: 5 of 6 files reviewed, 8 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tests/multithreaded/peer/rpma_peer_new.c, line 110 at r1](https://reviewable.io/reviews/pmem/rpma/1008#-MYcnrtZ8EyWPbUvlIxC:-MYu2nMQDqV68eWITM1y:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/bdd5301fa70e605560c001344053369543db629d/tests/multithreaded/peer/rpma_peer_new.c#L110)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

See also: https://github.com/pmem/rpma/pull/1012

(#1000 has been already merged)
</blockquote></details>

Done.
___
*[tests/multithreaded/peer/rpma_peer_new.c, line 15 at r2](https://reviewable.io/reviews/pmem/rpma/1008#-MYsxgmx4a3tvSBBxJax:-MYu2jDIBToCIqnZrg8J:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/111af20bc5a33a18e7dfd70cd9437548037e2697/tests/multithreaded/peer/rpma_peer_new.c#L15)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> int is_odp_supported_exp;
> ```

IMHO It is not needed.
</blockquote></details>

Done.
___
*[tests/multithreaded/peer/rpma_peer_new.c, line 33 at r2](https://reviewable.io/reviews/pmem/rpma/1008#-MYt0yYZC-i2HDAaoDQh:-MYu2kFyACCptdjnPM5W:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/111af20bc5a33a18e7dfd70cd9437548037e2697/tests/multithreaded/peer/rpma_peer_new.c#L33)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> struct state *st = (struct state *)calloc(1, sizeof(struct state));
> ```

`error: implicit declaration of function ‘calloc’ [-Werror=implicit-function-declaration]`
</blockquote></details>

Done.
___
*[tests/multithreaded/peer/rpma_peer_new.c, line 52 at r2](https://reviewable.io/reviews/pmem/rpma/1008#-MYsx_H2BIyGv18baklJ:-MYu2l3l8nJTGJCP-56u:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/111af20bc5a33a18e7dfd70cd9437548037e2697/tests/multithreaded/peer/rpma_peer_new.c#L52)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> 	/* check if the device context's capability supports On-Demand Paging */
> 	ret = rpma_utils_ibv_context_is_odp_capable(pr->dev,
> 				&pr->is_odp_supported_exp);
> 	if (ret) {
> 		MTT_RPMA_ERR(tr, "rpma_utils_ibv_context_is_odp_capable", ret);
> 		return;
> 	}
> ```

Why do you call `rpma_utils_ibv_context_is_odp_capable()`? IMHO it is not needed.
</blockquote></details>

Done.
___
*[tests/multithreaded/peer/rpma_peer_new.c, line 97 at r2](https://reviewable.io/reviews/pmem/rpma/1008#-MYt14Z095jBTQGSPGWW:-MYu2ln6BXs2Po4KvALQ:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/111af20bc5a33a18e7dfd70cd9437548037e2697/tests/multithreaded/peer/rpma_peer_new.c#L97)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

`error: implicit declaration of function ‘free’ [-Werror=implicit-function-declaration]`
</blockquote></details>

Done.
___
*[tests/multithreaded/peer/rpma_peer_new.c, line 104 at r2](https://reviewable.io/reviews/pmem/rpma/1008#-MYsygl32XeriC3XNZE3:-MYu2oPd8nUgA5kiOe_9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/111af20bc5a33a18e7dfd70cd9437548037e2697/tests/multithreaded/peer/rpma_peer_new.c#L104)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> int ret;
> ```

`error: unused variable ‘ret’ [-Werror=unused-variable]`
</blockquote></details>

Done.
___
*[tests/multithreaded/peer/rpma_peer_new.c, line 109 at r2](https://reviewable.io/reviews/pmem/rpma/1008#-MYt1ZjeDQ6ixxz_eLvE:-MYu2i3nCffuaTRP2vlT:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/111af20bc5a33a18e7dfd70cd9437548037e2697/tests/multithreaded/peer/rpma_peer_new.c#L109)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> {args.addr};
> ```

`{args.addr, NULL, 0};` or  `{args.addr, NULL};` after having removed ` is_odp_supported_exp`
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 5 of 6 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1008)* status: all files reviewed, 12 unresolved discussions (waiting on @ewanglong and @ldorau)

___
*[tests/multithreaded/peer/rpma_peer_new.c, line 19 at r3](https://reviewable.io/reviews/pmem/rpma/1008#-MYvkGcX4NvJcbCECysR:-MYvkGcY3sNJ4ppY08cr:bdn7xee) ([raw file](https://github.com/pmem/rpma/blob/5480f4dbb642e4ebe189ae139b6afee14d73713f/tests/multithreaded/peer/rpma_peer_new.c#L19)):*
> ```C
> 
> struct prestate {
> 	char *addr;
> ```

You just need to provide the `struct ibv_context *` so addr is not needed here.
___
*[tests/multithreaded/peer/rpma_peer_new.c, line 46 at r3](https://reviewable.io/reviews/pmem/rpma/1008#-MYvkqXMAX0MCzc-hrQx:-MYvkqXMAX0MCzc-hrQy:b-lcy362) ([raw file](https://github.com/pmem/rpma/blob/5480f4dbb642e4ebe189ae139b6afee14d73713f/tests/multithreaded/peer/rpma_peer_new.c#L46)):*
> ```C
> 	/* obtain an IBV context for a remote IP address */
> 	int ret = rpma_utils_get_ibv_context(pr->addr,
> 			RPMA_UTIL_IBV_CONTEXT_REMOTE, &pr->dev);
> ```

This step is called for each of the threads so you are rewriting this poor prestate pointer over and over again. ;-)
Usually, all the prestate fields should be prepared before even calling `mt_run()`.
So you don't even need to modify prestate fields during the test.
You also do need the sequential init. You just need:
- main (or a dedicated function if you need): rpma_utils_get_ibv_context and prepare prestate
- parallel init: calloc state
- thread: `rpma_peer_new()`
- parallel fini: `rpma_peer_delete()` and free the state
___
*[tests/multithreaded/peer/rpma_peer_new.c, line 57 at r3](https://reviewable.io/reviews/pmem/rpma/1008#-MYvmQkS0N7hld6dHMq3:-MYvmQkS0N7hld6dHMq4:bf33ml0) ([raw file](https://github.com/pmem/rpma/blob/5480f4dbb642e4ebe189ae139b6afee14d73713f/tests/multithreaded/peer/rpma_peer_new.c#L57)):*
> ```C
> /*
>  * thread -- try to create an rpma_peer based on a shared IBV context
>  * and On-Demand Paging capability
> ```

`create rpma_peer based on shared ibv_context`
___
*[tests/multithreaded/peer/rpma_peer_new.c, line 78 at r3](https://reviewable.io/reviews/pmem/rpma/1008#-MYvmrAS4OSkj_v4Ty3k:-MYvmrAS4OSkj_v4Ty3l:b9a922m) ([raw file](https://github.com/pmem/rpma/blob/5480f4dbb642e4ebe189ae139b6afee14d73713f/tests/multithreaded/peer/rpma_peer_new.c#L78)):*
> ```C
> 
> /*
>  * fini -- a parallel step of cleanup
> ```

`delete rpma_peer and free the state`
___
*[tests/multithreaded/peer/rpma_peer_new.c, line 81 at r3](https://reviewable.io/reviews/pmem/rpma/1008#-MYvmldX4_F8eLV_Ent-:-MYvmldX4_F8eLV_Ent0:b-hx94g) ([raw file](https://github.com/pmem/rpma/blob/5480f4dbb642e4ebe189ae139b6afee14d73713f/tests/multithreaded/peer/rpma_peer_new.c#L81)):*
> ```C
>  *
>  * Everything that can be cleaned up after the test in a thread-safe manner
>  * should go here.
> ```

Please do not copy over the generic comments.
___
*[tests/multithreaded/peer/rpma_peer_new.c, line 92 at r3](https://reviewable.io/reviews/pmem/rpma/1008#-MYvnTso4revKJQftL20:-MYvnTso4revKJQftL21:b-yf5cf) ([raw file](https://github.com/pmem/rpma/blob/5480f4dbb642e4ebe189ae139b6afee14d73713f/tests/multithreaded/peer/rpma_peer_new.c#L92)):*
> ```C
> 	int ret = rpma_peer_delete(&st->peer);
> 	if (ret)
> 		MTT_RPMA_ERR(tr, "rpma_peer_delete", ret);
> ```

```c
if ((ret = rpma_peer_delete(&st->peer)))
    MTT_RPMA_ERR(tr, "rpma_peer_delete", ret);
```

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1008)* status: 5 of 6 files reviewed, 12 unresolved discussions (waiting on @janekmi and @ldorau)

___
*[tests/multithreaded/peer/rpma_peer_new.c, line 19 at r3](https://reviewable.io/reviews/pmem/rpma/1008#-MYvkGcX4NvJcbCECysR:-MYwRJo52fE7U_GLcKs0:b994ii6) ([raw file](https://github.com/pmem/rpma/blob/5480f4dbb642e4ebe189ae139b6afee14d73713f/tests/multithreaded/peer/rpma_peer_new.c#L19)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You just need to provide the `struct ibv_context *` so addr is not needed here.
</blockquote></details>

it is used by rpma_utils_get_ibv_context in seq_init.
___
*[tests/multithreaded/peer/rpma_peer_new.c, line 46 at r3](https://reviewable.io/reviews/pmem/rpma/1008#-MYvkqXMAX0MCzc-hrQx:-MYwii3LDCbUQ4ZkZb-E:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5480f4dbb642e4ebe189ae139b6afee14d73713f/tests/multithreaded/peer/rpma_peer_new.c#L46)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

This step is called for each of the threads so you are rewriting this poor prestate pointer over and over again. ;-)
Usually, all the prestate fields should be prepared before even calling `mt_run()`.
So you don't even need to modify prestate fields during the test.
You also do need the sequential init. You just need:
- main (or a dedicated function if you need): rpma_utils_get_ibv_context and prepare prestate
- parallel init: calloc state
- thread: `rpma_peer_new()`
- parallel fini: `rpma_peer_delete()` and free the state
</blockquote></details>

Done.
___
*[tests/multithreaded/peer/rpma_peer_new.c, line 57 at r3](https://reviewable.io/reviews/pmem/rpma/1008#-MYvmQkS0N7hld6dHMq3:-MYwidS34XiOKprwYW0O:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5480f4dbb642e4ebe189ae139b6afee14d73713f/tests/multithreaded/peer/rpma_peer_new.c#L57)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`create rpma_peer based on shared ibv_context`
</blockquote></details>

Done.
___
*[tests/multithreaded/peer/rpma_peer_new.c, line 78 at r3](https://reviewable.io/reviews/pmem/rpma/1008#-MYvmrAS4OSkj_v4Ty3k:-MYwieGG8jQwLfVocUvn:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5480f4dbb642e4ebe189ae139b6afee14d73713f/tests/multithreaded/peer/rpma_peer_new.c#L78)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

`delete rpma_peer and free the state`
</blockquote></details>

Done.
___
*[tests/multithreaded/peer/rpma_peer_new.c, line 81 at r3](https://reviewable.io/reviews/pmem/rpma/1008#-MYvmldX4_F8eLV_Ent-:-MYwigZV-gSIaCIeOt_9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5480f4dbb642e4ebe189ae139b6afee14d73713f/tests/multithreaded/peer/rpma_peer_new.c#L81)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please do not copy over the generic comments.
</blockquote></details>

Done.
___
*[tests/multithreaded/peer/rpma_peer_new.c, line 92 at r3](https://reviewable.io/reviews/pmem/rpma/1008#-MYvnTso4revKJQftL20:-MYwihOK7US8Gd8jNjcH:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5480f4dbb642e4ebe189ae139b6afee14d73713f/tests/multithreaded/peer/rpma_peer_new.c#L92)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```c
if ((ret = rpma_peer_delete(&st->peer)))
    MTT_RPMA_ERR(tr, "rpma_peer_delete", ret);
```
</blockquote></details>

Done.

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1008)* status: all files reviewed, 2 unresolved discussions (waiting on @ewanglong)

___
*[tests/multithreaded/peer/rpma_peer_new.c, line 92 at r3](https://reviewable.io/reviews/pmem/rpma/1008#-MYvnTso4revKJQftL20:-MYxVaeyB02gSEKTX1aa:b-ddrk20) ([raw file](https://github.com/pmem/rpma/blob/5480f4dbb642e4ebe189ae139b6afee14d73713f/tests/multithreaded/peer/rpma_peer_new.c#L92)):*
<details><summary><i>Previously, ewanglong wrote…</i></summary><blockquote>

Done.
</blockquote></details>

You need additional brackets here. It is a way of letting know the compiler you are aware you have an assignment here instead of comparison which most modern compilers detect and will give you a warning at least.
___
*[tests/multithreaded/peer/rpma_peer_new.c, line 54 at r4](https://reviewable.io/reviews/pmem/rpma/1008#-MYxWwKj3nmOw11JLEbE:-MYxWwKj3nmOw11JLEbF:b-6xc9jr) ([raw file](https://github.com/pmem/rpma/blob/10d11e801ad65a2482a09caccaca5ff75e0dbca5/tests/multithreaded/peer/rpma_peer_new.c#L54)):*
> ```C
> 	struct rpma_peer *peer = NULL;
> 	/* create a new peer object */
> 	int ret = rpma_peer_new(pr->dev, &peer);
> ```

You can use `st->peer` directly. The intermediate variable introduces no value.

**Review by ewanglong — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1008)* status: 5 of 6 files reviewed, 2 unresolved discussions (waiting on @janekmi)

___
*[tests/multithreaded/peer/rpma_peer_new.c, line 92 at r3](https://reviewable.io/reviews/pmem/rpma/1008#-MYvnTso4revKJQftL20:-MYx_YrEAAnXsXvQDg0-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/5480f4dbb642e4ebe189ae139b6afee14d73713f/tests/multithreaded/peer/rpma_peer_new.c#L92)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You need additional brackets here. It is a way of letting know the compiler you are aware you have an assignment here instead of comparison which most modern compilers detect and will give you a warning at least.
</blockquote></details>

Done.
___
*[tests/multithreaded/peer/rpma_peer_new.c, line 54 at r4](https://reviewable.io/reviews/pmem/rpma/1008#-MYxWwKj3nmOw11JLEbE:-MYx_ZgsBu21zbLD-u1U:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/10d11e801ad65a2482a09caccaca5ff75e0dbca5/tests/multithreaded/peer/rpma_peer_new.c#L54)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

You can use `st->peer` directly. The intermediate variable introduces no value.
</blockquote></details>

Done.

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1008#-:-MYy8b160-idxyz4UPz8:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1008#-:-MYyGVF27Nn3xhugDWQG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ewanglong)

**Pull request merged**
