### PR TITLE
rpma: write the 'ON-DEMAND PAGING SUPPORT' section of librpma.7 manual

### PR DESCRIPTION
**Pull request by ldorau**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/524)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/524#-:-MIZ48Qc7sNn2RRO0oGb:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/524)* status: all files reviewed, 2 unresolved discussions (waiting on @ldorau)

___
*[src/include/librpma.h, line 251 at r1](https://reviewable.io/reviews/pmem/rpma/524#-MIZ4TVtBaXhtlIhcwvP:-MIZ4TVtBaXhtlIhcwvQ:b-iuwdxc) ([raw file](https://github.com/pmem/rpma/blob/a0fc5a301451a9a1f87097c8d6af0e6799aa5b5e/src/include/librpma.h#L251)):*
> ```objc
>  * The librpma library uses ODP automatically if it is supported,
>  * because rpma_utils_ibv_context_is_odp_capable() is called
>  * by rpma_peer_new() internally.
> ```

Please describe why it is important in the context of PMem.
___
*[src/include/librpma.h, line 251 at r1](https://reviewable.io/reviews/pmem/rpma/524#-MIZ4dtK205AeoA8RPeb:-MIZ4dtK205AeoA8RPec:b-fu2kvg) ([raw file](https://github.com/pmem/rpma/blob/a0fc5a301451a9a1f87097c8d6af0e6799aa5b5e/src/include/librpma.h#L251)):*
> ```objc
>  * The librpma library uses ODP automatically if it is supported,
>  * because rpma_utils_ibv_context_is_odp_capable() is called
>  * by rpma_peer_new() internally.
> ```

The last two lines are a description of the implementation. Not interesting for the end-user.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/524)* status: 0 of 1 files reviewed, 2 unresolved discussions (waiting on @grom72 and @janekmi)

___
*[src/include/librpma.h, line 251 at r1](https://reviewable.io/reviews/pmem/rpma/524#-MIZ4dtK205AeoA8RPeb:-MIZ7axi31ciMxCpJMWW:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a0fc5a301451a9a1f87097c8d6af0e6799aa5b5e/src/include/librpma.h#L251)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The last two lines are a description of the implementation. Not interesting for the end-user.
</blockquote></details>

Done.
___
*[src/include/librpma.h, line 251 at r1](https://reviewable.io/reviews/pmem/rpma/524#-MIZ4TVtBaXhtlIhcwvP:-MIZBcSFCJD9p3waXymM:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/a0fc5a301451a9a1f87097c8d6af0e6799aa5b5e/src/include/librpma.h#L251)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Please describe why it is important in the context of PMem.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/524#-:-MIZFDCc4CVqmW7IPlVq:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/524)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
