### PR TITLE
tools: perf: separate figure.series_in from figure.series

### PR DESCRIPTION
**Pull request by janekmi**
Having two different structures provided under the same field on various stages of processing is confusing.

This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1246)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1246)* status: 1 of 3 files reviewed, all discussions resolved (waiting on @janekmi)

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1246)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @janekmi)

*[a discussion](https://reviewable.io/reviews/pmem/rpma/1246#-MiVvOuv9OXc4P3OuEpP:-MiVvOuv9OXc4P3OuEpQ:b-it48x4) (no related file):*
Could you add a rationale of this change to the commit message?

---

**Review by ldorau — APPROVED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1246#-:-MiWV6UL8qsZEVYnL6R6:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1246#-:-MiWg50d4UTw44ENOc5N:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @janekmi)

**Pull request merged**
