### PR TITLE
common: roadmap updated after demo on 9/3/2020

### PR DESCRIPTION
**Pull request by grom72**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/403)

### CODE REVIEW

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/403)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @grom72)

___
*[ROADMAP.md, line 3 at r1](https://reviewable.io/reviews/pmem/rpma/403#-MHFs4nwAvZjsuXEdZqO:-MHFs4nwAvZjsuXEdZqP:brdan8f) ([raw file](https://github.com/pmem/rpma/blob/0af80ad1329917b8117276b41be2cae56d4b6d1c/ROADMAP.md#L3)):*
> ```Markdown
> # **librpma roadmap [09/04/2020]**
> 
> This document presents the librpma library roadmap as it shaped on 09/04/2020. It lists high-level features that are going to be released with the library release 0.9 and features that are planed to be developed later.
> ```

planned
___
*[ROADMAP.md, line 30 at r1](https://reviewable.io/reviews/pmem/rpma/403#-MHFsTM923EhZpU6XJ59:-MHFsTM923EhZpU6XJ5A:b-idkueu) ([raw file](https://github.com/pmem/rpma/blob/0af80ad1329917b8117276b41be2cae56d4b6d1c/ROADMAP.md#L30)):*
> ```
> Build system suport 
> ```

support
___
*[ROADMAP.md, line 31 at r1](https://reviewable.io/reviews/pmem/rpma/403#-MHFsYg65CWGlIw4y57N:-MHFsYg65CWGlIw4y57O:b-c4y5bg) ([raw file](https://github.com/pmem/rpma/blob/0af80ad1329917b8117276b41be2cae56d4b6d1c/ROADMAP.md#L31)):*
> ```
> demonstrate
> ```

demonstrates
___
*[ROADMAP.md, line 31 at r1](https://reviewable.io/reviews/pmem/rpma/403#-MHFscuc0tH34K9tNEbl:-MHFscuc0tH34K9tNEbm:b-mnsi2t) ([raw file](https://github.com/pmem/rpma/blob/0af80ad1329917b8117276b41be2cae56d4b6d1c/ROADMAP.md#L31)):*
> ```
> of the librpma
> ```

`of librpma` or `of the librpma library`
___
*[ROADMAP.md, line 32 at r1](https://reviewable.io/reviews/pmem/rpma/403#-MHFsmhZ19fUiMnDIUcD:-MHFsmhZ19fUiMnDIUcE:b-tmvv0s) ([raw file](https://github.com/pmem/rpma/blob/0af80ad1329917b8117276b41be2cae56d4b6d1c/ROADMAP.md#L32)):*
> ```
> custom user define 
> ```

`custom, user-defined`
___
*[ROADMAP.md, line 43 at r1](https://reviewable.io/reviews/pmem/rpma/403#-MHFtwIm50JKWLnMat8r:-MHFtwIm50JKWLnMat8s:b-d4e7jq) ([raw file](https://github.com/pmem/rpma/blob/0af80ad1329917b8117276b41be2cae56d4b6d1c/ROADMAP.md#L43)):*
> ```
> Fio engine support is now distinguish as a separate value build on the top of the librpma with own roadmap that will not affect the librpma release cycle.
> ```

Fio engine support is **distinguished now** as a separate value **built** on the top of **librpma** with own roadmap that will not affect the librpma release cycle.

`of librpma` or `of the librpma library`

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/403)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @grom72)

___
*[ROADMAP.md, line 47 at r1](https://reviewable.io/reviews/pmem/rpma/403#-MHFuygZDmHNNEvA_9Ym:-MHFuygZDmHNNEvA_9Yn:bb7nspn) ([raw file](https://github.com/pmem/rpma/blob/0af80ad1329917b8117276b41be2cae56d4b6d1c/ROADMAP.md#L47)):*
> ```Markdown
> ---|---|---|---
> :black_square_button:|Fio engine for writing|Introduce Fio engine example for librpma.|10/02/2020
> :black_square_button:|Fio engine for reading|Support for RPMem Read operation.|Q4'20
> ```

read

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/403)* status: all files reviewed, 7 unresolved discussions (waiting on @grom72)

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/403)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @grom72 and @ldorau)

___
*[ROADMAP.md, line 3 at r1](https://reviewable.io/reviews/pmem/rpma/403#-MHFs4nwAvZjsuXEdZqO:-MHFzeZB90ViUBdDPIma:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0af80ad1329917b8117276b41be2cae56d4b6d1c/ROADMAP.md#L3)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

planned
</blockquote></details>

Done.
___
*[ROADMAP.md, line 32 at r1](https://reviewable.io/reviews/pmem/rpma/403#-MHFsmhZ19fUiMnDIUcD:-MHG-Kld6CXiROdhoNLL:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0af80ad1329917b8117276b41be2cae56d4b6d1c/ROADMAP.md#L32)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> custom user define 
> ```

`custom, user-defined`
</blockquote></details>

Done.
___
*[ROADMAP.md, line 47 at r1](https://reviewable.io/reviews/pmem/rpma/403#-MHFuygZDmHNNEvA_9Ym:-MHG-7tB3K7Aj7jnsd3M:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0af80ad1329917b8117276b41be2cae56d4b6d1c/ROADMAP.md#L47)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

read
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/403)* status: 0 of 1 files reviewed, 7 unresolved discussions (waiting on @ldorau)

___
*[ROADMAP.md, line 30 at r1](https://reviewable.io/reviews/pmem/rpma/403#-MHFsTM923EhZpU6XJ59:-MHG-ca3-QC7kq2baee-:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0af80ad1329917b8117276b41be2cae56d4b6d1c/ROADMAP.md#L30)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> Build system suport 
> ```

support
</blockquote></details>

Done.
___
*[ROADMAP.md, line 31 at r1](https://reviewable.io/reviews/pmem/rpma/403#-MHFscuc0tH34K9tNEbl:-MHG-ZXv6hORUxyKLjIo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0af80ad1329917b8117276b41be2cae56d4b6d1c/ROADMAP.md#L31)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> of the librpma
> ```

`of librpma` or `of the librpma library`
</blockquote></details>

Done.
___
*[ROADMAP.md, line 31 at r1](https://reviewable.io/reviews/pmem/rpma/403#-MHFsYg65CWGlIw4y57N:-MHG-bhx04LH4-iKbZdo:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0af80ad1329917b8117276b41be2cae56d4b6d1c/ROADMAP.md#L31)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> demonstrate
> ```

demonstrates
</blockquote></details>

Done.
___
*[ROADMAP.md, line 43 at r1](https://reviewable.io/reviews/pmem/rpma/403#-MHFtwIm50JKWLnMat8r:-MHG-gPYDQTuALv3r7L7:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/0af80ad1329917b8117276b41be2cae56d4b6d1c/ROADMAP.md#L43)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

> ```
> Fio engine support is now distinguish as a separate value build on the top of the librpma with own roadmap that will not affect the librpma release cycle.
> ```

Fio engine support is **distinguished now** as a separate value **built** on the top of **librpma** with own roadmap that will not affect the librpma release cycle.

`of librpma` or `of the librpma library`

</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/403)* status: all files reviewed, 7 unresolved discussions (waiting on @ldorau)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/403)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[ROADMAP.md, line 32 at r1](https://reviewable.io/reviews/pmem/rpma/403#-MHFsmhZ19fUiMnDIUcD:-MHG13jt0yw2EAiVBmqY:b-o2auvu) ([raw file](https://github.com/pmem/rpma/blob/0af80ad1329917b8117276b41be2cae56d4b6d1c/ROADMAP.md#L32)):*
<details><summary><i>Previously, grom72 (Tomasz Gromadzki) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

defined

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/403)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/403)* status: all files reviewed, 1 unresolved discussion (waiting on @grom72)

___
*[ROADMAP.md, line 32 at r1](https://reviewable.io/reviews/pmem/rpma/403#-MHFsmhZ19fUiMnDIUcD:-MHG1HLq31p3Qi5raHYo:b-6bncvv) ([raw file](https://github.com/pmem/rpma/blob/0af80ad1329917b8117276b41be2cae56d4b6d1c/ROADMAP.md#L32)):*
> ```
> user-define
> ```

user-defineD

**Review by ldorau — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/403)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by ldorau — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/403#-:-MHG5J7H9kmJtrH_nHN3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by janekmi — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/403)* status: all files reviewed, 5 unresolved discussions (waiting on @grom72)

___
*[ROADMAP.md, line 1 at r4](https://reviewable.io/reviews/pmem/rpma/403#-MHO-ZWXCEMXliqfpBHw:-MHO-ZWYBO5J5dv0bsum:bb74peb) ([raw file](https://github.com/pmem/rpma/blob/eebd0edf4d0ce08360a2a25b4db93507f9275906/ROADMAP.md#L1)):*
> ```Markdown
> # **librpma roadmap [08/25/2020]**
> ```

The?
___
*[ROADMAP.md, line 32 at r4](https://reviewable.io/reviews/pmem/rpma/403#-MHNyvToAOEX6jL5XuN4:-MHNyvToAOEX6jL5XuN5:baktx0h) ([raw file](https://github.com/pmem/rpma/blob/15b30b513897a37a61c0c4b6b08bb0a5d31e8081/ROADMAP.md#L32)):*
> ```Markdown
> :black_square_button:|Legacy OS support|Build system support for legacy Linux distributions|09/18/2020
> :black_square_button:|GPSPM example|An example that demonstrates how to implement GPSPM Flushing method on the top of the librpma library|09/18/2020
> :black_square_button:|Log prefix|Enable custom, user-defined prefix in log messages|09/18/2020
> ```

a custom, user-defined...?
___
*[ROADMAP.md, line 42 at r4](https://reviewable.io/reviews/pmem/rpma/403#-MHNzlJkCqR5n_GsiPWj:-MHNzlJkCqR5n_GsiPWk:b35jicz) ([raw file](https://github.com/pmem/rpma/blob/15b30b513897a37a61c0c4b6b08bb0a5d31e8081/ROADMAP.md#L42)):*
> # **The librpma fio engine roadmap [09/04/2020]**
___
*[ROADMAP.md, line 43 at r4](https://reviewable.io/reviews/pmem/rpma/403#-MHO-6c46Ye37h9Y18NJ:-MHO-6c46Ye37h9Y18NK:b-ix85ub) ([raw file](https://github.com/pmem/rpma/blob/15b30b513897a37a61c0c4b6b08bb0a5d31e8081/ROADMAP.md#L43)):*
> ```Markdown
> :black_square_button:|librpma1.0 release|The librpma release 1.0.|Q1'21
> 
> Fio engine support is distinguished now as a separate value built on the top of the librpma library with own roadmap that will not affect the librpma release cycle.
> ```

The librpma FIO engine is distinguished now as a separate value built on the top of the librpma library with its own roadmap that will not affect the librpma release cycle.
___
*[ROADMAP.md, line 54 at r4](https://reviewable.io/reviews/pmem/rpma/403#-MHO0bfB324S7J61tz1E:-MHO0bfB324S7J61tz1F:bp3032p) ([raw file](https://github.com/pmem/rpma/blob/15b30b513897a37a61c0c4b6b08bb0a5d31e8081/ROADMAP.md#L54)):*
> ```Markdown
> ## Contact Us
> 
> For more information about the library roadmap, please contact
> ```

both roadmaps

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/403)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @grom72, @janekmi, and @ldorau)

___
*[ROADMAP.md, line 1 at r4](https://reviewable.io/reviews/pmem/rpma/403#-MHO-ZWXCEMXliqfpBHw:-MHR3xHJEwivE2qZUf9P:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/eebd0edf4d0ce08360a2a25b4db93507f9275906/ROADMAP.md#L1)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The?
</blockquote></details>

Done.
___
*[ROADMAP.md, line 42 at r4](https://reviewable.io/reviews/pmem/rpma/403#-MHNzlJkCqR5n_GsiPWj:-MHR40x08HwOsonBPq_z:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/15b30b513897a37a61c0c4b6b08bb0a5d31e8081/ROADMAP.md#L42)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

> # **The librpma fio engine roadmap [09/04/2020]**
</blockquote></details>

Done.
___
*[ROADMAP.md, line 54 at r4](https://reviewable.io/reviews/pmem/rpma/403#-MHO0bfB324S7J61tz1E:-MHR4Hvx9t_AtLfgXOa9:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/15b30b513897a37a61c0c4b6b08bb0a5d31e8081/ROADMAP.md#L54)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

both roadmaps
</blockquote></details>

Done.

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/403)* status: all files reviewed, 4 unresolved discussions (waiting on @janekmi)

___
*[ROADMAP.md, line 43 at r4](https://reviewable.io/reviews/pmem/rpma/403#-MHO-6c46Ye37h9Y18NJ:-MHR4NV3DRtZNj6w6kL3:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/15b30b513897a37a61c0c4b6b08bb0a5d31e8081/ROADMAP.md#L43)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

The librpma FIO engine is distinguished now as a separate value built on the top of the librpma library with its own roadmap that will not affect the librpma release cycle.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/403#-:-MHRYqVQ8WTzwcgHHAQz:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
