### PR TITLE
common: rdma_getaddrinfo clang detection fix

### PR DESCRIPTION
**Pull request by janekmi**
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/559)

### CODE REVIEW

**Review by grom72 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/559)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[cmake/functions.cmake, line 174 at r1](https://reviewable.io/reviews/pmem/rpma/559#-MK4PNFtAxA4SkbOYTgi:-MK4PNFtAxA4SkbOYTgj:b-y2d8y2) ([raw file](https://github.com/pmem/rpma/blob/20b414af1d04b5e0aa3d45361566c6ea54bce6ad/cmake/functions.cmake#L174)):*
> ```
> 	else()
> 		# the clang compiler ignores the '-Werror=discarded-qualifiers' flag
> 		set(RUN_CHECK_C_SOURCE_COMPILES 0)
> ```
do we need this at all?
if yes shall we have else for above if(C_HAS_Werror_discarded_qualifiers)?

**Review by ldorau — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/559)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[cmake/functions.cmake, line 177 at r1](https://reviewable.io/reviews/pmem/rpma/559#-MK4P0bvBecp0-S88ALy:-MK4P0bvBecp0-S88ALz:b-gx4daj) ([raw file](https://github.com/pmem/rpma/blob/20b414af1d04b5e0aa3d45361566c6ea54bce6ad/cmake/functions.cmake#L177)):*
It seems that this whole snippet:
<details><summary><i alt="summary">Quoted 10 lines of code…</i></summary>

> ```
> 	if(${CMAKE_C_COMPILER} MATCHES "gcc")
> 		# check if the GCC compiler supports the '-Werror=discarded-qualifiers' flag
> 		CHECK_C_COMPILER_FLAG("-Werror=discarded-qualifiers" C_HAS_Werror_discarded_qualifiers)
> 		if(C_HAS_Werror_discarded_qualifiers)
> 			set(RUN_CHECK_C_SOURCE_COMPILES 1)
> 		endif()
> 	else()
> 		# the clang compiler ignores the '-Werror=discarded-qualifiers' flag
> 		set(RUN_CHECK_C_SOURCE_COMPILES 0)
> 	endif()
> ```
</details>


should be replaced with just:

```
		# check if a compiler supports the '-Werror=discarded-qualifiers' flag:
		CHECK_C_COMPILER_FLAG("-Werror=discarded-qualifiers" C_HAS_Werror_discarded_qualifiers)
		if(C_HAS_Werror_discarded_qualifiers)
			set(RUN_CHECK_C_SOURCE_COMPILES 1)
		endif()
```

and the comment below should be also updated, but this change should be carefully tested.
___
*[cmake/functions.cmake, line 200 at r1](https://reviewable.io/reviews/pmem/rpma/559#-MK4Ph5B93MUUpN5Zdru:-MK4Ph5B93MUUpN5Zdrv:b4dom1u) ([raw file](https://github.com/pmem/rpma/blob/20b414af1d04b5e0aa3d45361566c6ea54bce6ad/cmake/functions.cmake#L200)):*
Please update also this comment:

> ```
> an old version of the GCC compiler
> ```

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/559)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[cmake/functions.cmake, line 177 at r1](https://reviewable.io/reviews/pmem/rpma/559#-MK4P0bvBecp0-S88ALy:-MK4_nuk8pTtZU4bTczs:b-zcxtk4) ([raw file](https://github.com/pmem/rpma/blob/20b414af1d04b5e0aa3d45361566c6ea54bce6ad/cmake/functions.cmake#L177)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

It seems that this whole snippet:

> ```
> 	if(${CMAKE_C_COMPILER} MATCHES "gcc")
> 		# check if the GCC compiler supports the '-Werror=discarded-qualifiers' flag
> 		CHECK_C_COMPILER_FLAG("-Werror=discarded-qualifiers" C_HAS_Werror_discarded_qualifiers)
> 		if(C_HAS_Werror_discarded_qualifiers)
> 			set(RUN_CHECK_C_SOURCE_COMPILES 1)
> 		endif()
> 	else()
> 		# the clang compiler ignores the '-Werror=discarded-qualifiers' flag
> 		set(RUN_CHECK_C_SOURCE_COMPILES 0)
> 	endif()
> ```

should be replaced with just:

```
		# check if a compiler supports the '-Werror=discarded-qualifiers' flag:
		CHECK_C_COMPILER_FLAG("-Werror=discarded-qualifiers" C_HAS_Werror_discarded_qualifiers)
		if(C_HAS_Werror_discarded_qualifiers)
			set(RUN_CHECK_C_SOURCE_COMPILES 1)
		endif()
```

and the comment below should be also updated, but this change should be carefully tested.

</blockquote></details>

Clang has just another option for this: `-Wincompatible-pointer-types-discards-qualifiers`

**Review by ldorau — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/559)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

___
*[cmake/functions.cmake, line 177 at r1](https://reviewable.io/reviews/pmem/rpma/559#-MK4P0bvBecp0-S88ALy:-MK4bMzc9C7ADXLLCZKm:b-ochodx) ([raw file](https://github.com/pmem/rpma/blob/20b414af1d04b5e0aa3d45361566c6ea54bce6ad/cmake/functions.cmake#L177)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Clang has just another option for this: `-Wincompatible-pointer-types-discards-qualifiers`
</blockquote></details>

So it could be rather something like that:

```
	if(${CMAKE_C_COMPILER} MATCHES "gcc")
		# check if the GCC compiler supports the '-Werror=discarded-qualifiers' flag
		CHECK_C_COMPILER_FLAG("-Werror=discarded-qualifiers" C_HAS_Werror_discarded_qualifiers)
		if(C_HAS_Werror_discarded_qualifiers)
			set(RUN_CHECK_C_SOURCE_COMPILES 1)
		endif()
	elseif(${CMAKE_C_COMPILER} MATCHES "clang")
		# check if the Clang compiler supports the '-Wincompatible-pointer-types-discards-qualifiers' flag
		CHECK_C_COMPILER_FLAG("-Wincompatible-pointer-types-discards-qualifiers" C_HAS_Werror_discarded_qualifiers)
		if(C_HAS_Werror_discarded_qualifiers)
			set(RUN_CHECK_C_SOURCE_COMPILES 1)
		endif()
	endif()
```

**Review by grom72 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/559)* status: all files reviewed, 3 unresolved discussions (waiting on @janekmi)

**Review by grom72 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/559#-:-MK9fyKsDifYFk-JMlk5:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @janekmi)

**Review by ldorau — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/559)* status: :shipit: complete! all files reviewed, all discussions resolved

___
*[cmake/functions.cmake, line 177 at r1](https://reviewable.io/reviews/pmem/rpma/559#-MK4P0bvBecp0-S88ALy:-MK4e_up0kD3eaCekqfR:bcx5mgu) ([raw file](https://github.com/pmem/rpma/blob/20b414af1d04b5e0aa3d45361566c6ea54bce6ad/cmake/functions.cmake#L177)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

So it could be rather something like that:

```
	if(${CMAKE_C_COMPILER} MATCHES "gcc")
		# check if the GCC compiler supports the '-Werror=discarded-qualifiers' flag
		CHECK_C_COMPILER_FLAG("-Werror=discarded-qualifiers" C_HAS_Werror_discarded_qualifiers)
		if(C_HAS_Werror_discarded_qualifiers)
			set(RUN_CHECK_C_SOURCE_COMPILES 1)
		endif()
	elseif(${CMAKE_C_COMPILER} MATCHES "clang")
		# check if the Clang compiler supports the '-Wincompatible-pointer-types-discards-qualifiers' flag
		CHECK_C_COMPILER_FLAG("-Wincompatible-pointer-types-discards-qualifiers" C_HAS_Werror_discarded_qualifiers)
		if(C_HAS_Werror_discarded_qualifiers)
			set(RUN_CHECK_C_SOURCE_COMPILES 1)
		endif()
	endif()
```
</blockquote></details>

OK, let's improve it in the near future.
___
*[cmake/functions.cmake, line 200 at r1](https://reviewable.io/reviews/pmem/rpma/559#-MK4Ph5B93MUUpN5Zdru:-MK9g5iLCiaAJAd7d_FX:bcx5mgu) ([raw file](https://github.com/pmem/rpma/blob/20b414af1d04b5e0aa3d45361566c6ea54bce6ad/cmake/functions.cmake#L200)):*
<details><summary><i>Previously, ldorau (Lukasz Dorau) wrote…</i></summary><blockquote>

Please update also this comment:

> ```
> an old version of the GCC compiler
> ```

</blockquote></details>

OK, let's improve it in the near future.

**Review by ldorau — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/559#-:-MK9gAUM7oLndPvJtwg3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
