### PR TITLE
tools: store figure/part name using data['input_file']

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #1106

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/1108)

### CODE REVIEW

**Review by janekmi — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1108)* status: all files reviewed, 1 unresolved discussion (waiting on @ldorau)

___
*[tools/perf/lib/Bench.py, line 31 at r1](https://reviewable.io/reviews/pmem/rpma/1108#-MdRYAgo5uXEv71sXh2v:-MdRYAgo5uXEv71sXh2w:b-ysczpd) ([raw file](https://github.com/pmem/rpma/blob/def9c8fb31642ad20176390932e6a6b7f2e3f0ac/tools/perf/lib/Bench.py#L31)):*
> ```Python
>     @classmethod
>     def new(cls, config, figures, result_dir):
>         parts = [ os.path.splitext(os.path.basename(figures['input_file'])) ]
> ```

```python
parts = [ os.path.splitext(os.path.basename(figures['input_file']))[0] ]
```

`os.path.splitext()` retuns a tuple `('filename', '.ext')`.

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1108)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @janekmi)

___
*[tools/perf/lib/Bench.py, line 31 at r1](https://reviewable.io/reviews/pmem/rpma/1108#-MdRYAgo5uXEv71sXh2v:-MdRgDB7AlRnZxu4-206:b-896fix) ([raw file](https://github.com/pmem/rpma/blob/def9c8fb31642ad20176390932e6a6b7f2e3f0ac/tools/perf/lib/Bench.py#L31)):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

```python
parts = [ os.path.splitext(os.path.basename(figures['input_file']))[0] ]
```

`os.path.splitext()` retuns a tuple `('filename', '.ext')`.
</blockquote></details>

Done.

**Review by janekmi — APPROVED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1108#-:-MdS8Y2i1u1RNnxQhSc3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/1108#-:-MdVmAg69OyI7rHEJzaV:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
