### PR TITLE
rpma: replace spaces with tabs in tools/*.sh scripts

### PR DESCRIPTION
**Pull request by ldorau**
Requires:
- [x] #647

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/rpma/653)

### CODE REVIEW

**Review by janekmi — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/653)* status: 0 of 4 files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/pmem/rpma/653#-MO8nMu7CHfvs-lRRzZw:-MO8nMu7CHfvs-lRRzZx:b-hn9w98) (no related file):*
Ready for rebasing.

---

**Review by ldorau — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/653)* status: 0 of 2 files reviewed, all discussions resolved

*[a discussion](https://reviewable.io/reviews/pmem/rpma/653#-MO8nMu7CHfvs-lRRzZw:-MOAb_1t1wsVfG64oQ99:bb6un1j) (no related file):*
<details><summary><i>Previously, janekmi (Jan Michalski) wrote…</i></summary><blockquote>

Ready for rebasing.
</blockquote></details>

Done

---

**Review by grom72 — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/653#-:-MOAcJfzDYpSKbr60j2A:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Review by osalyk — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/rpma/653#-:-MOAchwa5McHw-5FmN3E:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @ldorau)

**Pull request merged**
